### PR TITLE
Support for accessing secured HDFS in Standalone Mode

### PR DESCRIPTION
**Pull request by huozhanfeng**
JIRA Issue:https://issues.apache.org/jira/browse/SPARK-3438

Reading data from secure HDFS into spark is a usefull feature.

### CODE REVIEW

**Comment by nchammas** [comment]
This PR has gone stale. Do we want to update it or close it out?

Also, @huozhanfeng, could you update the title of the PR to "[SPARK-3438] Add support for accessing secured HDFS"? This matches our current convention.

**Comment by pwendell** [comment]
Let's close this issue. There is an alternative PR that is currently ongoing.

**Comment by hsaputra** [comment]
@pwendell : The alternative PR (aka #4106) also being closed. I think you and @tgravescs have narrowed down the use cases to allow standalone Spark to have access to secured HDFS.

This is useful for those launching mini Spark clusters that are deployed in Docker based containers, via Kubernetes for example, that have ephemeral lifetime and only shared with maybe one or two users rather than in a multi-tenant model.

**Comment by vanzin** [comment]
@hsaputra if you don't care about multiple users, just create a principal / keytab pair for each of your workers, and set up a cron job to "kinit" that principal periodically. Then all processes running as the kinit'ed user (you should run the Worker processes as that user) will be able to talk to a secured HDFS.

There's no need to modify Spark for that.

**Comment by tgravescs** [comment]
@vanzin I'm not sure that actually works anymore.  It used to but I think it was broke. See https://issues.apache.org/jira/browse/SPARK-2541

**Comment by hsaputra** [comment]
@vanzin : as @tgravescs mentioned, it did not work anymore hence the need to fix it.

All the PRs and JIRAs for this issue had been closed to point to #4106 which also being closed due to comparisons with YARN mode.

Standalone mode serve different purpose than running in YARN. Most deployment would be for small clusters and semi-private mode where we assume safe way to add keytab for users of Spark.
So we need to consider the use cases rather than mixing it with YARN mode.

@tgravescs and @pwendell have made good cases in this PR why it is needed and I would suggest we revisit this again.

**Comment by vanzin** [comment]
> @vanzin : as @tgravescs mentioned, it did not work anymore hence the need to fix it.

The fix for the bug Tom mentions is separate from distributing keytabs or delegation tokens in an insecure deployment, which is what I'm strongly against.

> Standalone mode serve different purpose than running in YARN. Most deployment would be for small clusters and semi-private mode where we assume safe way to add keytab for users of Spark.

Sorry, I disagree. If you have kerberos, it means you care about security, and here you'd be adding a mechanism for Spark to completely break that.

So: I'm ok with a fix that allows the workaround I mentioned above which seems to be broken by SPARK-2541. I'm against any fix that means exposing user's keytabs or delegation tokens to other users, regardless of whether you think it's ok in your own environment.

**Comment by hsaputra** [comment]
Yes, I think @tgravescs proposal above including moving the key tabs and token to other users.
What I was agreeing was to add fix for that broke  SPARK-2541, which means as you mentioned, there a way to do "kinit" for each user that need access to standalone Spark cluster to access secure HDFS.

@tgravescs : should we reopen SPARK-2541 or SPARK-3438 to fix this?

**Comment by vanzin** [comment]
>  which means as you mentioned, there is a way or process to do "kinit" for each user

That's not what I said at all. What I said is that because spark standalone is insecure, and it runs everything as the same OS user, it should be up to the admin deploying the cluster to kinit *a single user* that will become the "Spark User" for the cluster, and everybody submitting jobs to the Spark standalone master will effectively be running Spark apps as that user.

That way, Spark does not create a security hole in the cluster, because:
- admins have to opt in to this insecure Spark setup
- they can easily revoke privileges by not allowing that Spark user to do anything else in the cluster
- users don't risk having their keytabs or delegation tokens being read by other users

**Comment by hsaputra** [comment]
Ah, I need to clarify, when I said "there is a way or process to do "kinit" for each user" I meant just that. The process of doing kinit or setting up the keytab is NOT done via Spark. 
So, when admin deploying the standalone Spark cluster, it should do the kinit for a user that would be effectively be the active user to run the job and Spark app to access secure HDFS as the principal.

**Comment by vanzin** [comment]
Ok, so we seems like we agree on the overall approach. Regarding SPARK-2541, it used to be that just overriding the `SPARK_USER` env variable would allow you to "impersonate" anyone. Doesn't that work anymore?

That way, if you set `SPARK_USER` to the name of the principal running the Spark daemons, things should work without any modifications to the current code.

**Comment by hsaputra** [comment]
Seemed like now when Executor trying to access HDFS it gets error:

```
Failed on local exception: java.io.IOException: org.apache.hadoop.security.AccessControlException: Client cannot authenticate via:[TOKEN, KERBEROS];
```

**Comment by vanzin** [comment]
Well, is the user logged in (= kinit was run) on all the worker nodes, so that processes have proper kerberos tokens to use?

**Comment by hsaputra** [comment]
@vanzin : yes =(
At least now we have agreement on the approach how to do it in standalone, I will move the discussions to mailing list. Was not my intention to have hijack this PR comment sections, mea culpa.

Thanks to @vanzin for entertaining my concern and comments.

**Pull request closed without merging**
