### PR TITLE
[SPARK-28077][SQL][TEST][FOLLOW-UP] Enable Overlay function tests

### PR DESCRIPTION
**Pull request by beliefer**
## What changes were proposed in this pull request?

This PR is a follow-up to https://github.com/apache/spark/pull/24918

## How was this patch tested?

Pass the Jenkins with the newly update test files.

### CODE REVIEW

**Comment by beliefer** [comment]
@dongjoon-hyun @ueshin Could you take a look at this PR?

**Review by wangyum — APPROVED** [review]

**Comment by beliefer** [comment]
@wangyum  Thanks a lot!

**Comment by maropu** [comment]
LGTM

**Comment by maropu** [comment]
Thanks! Merged to master

**Comment by beliefer** [comment]
@maropu @dongjoon-hyun Thanks for all your job.

**Pull request closed without merging**
