### PR TITLE
[SPARK-23091][ML] Incorrect unit test for approxQuantile

### PR DESCRIPTION
**Pull request by srowen**
## What changes were proposed in this pull request?

Narrow bound on approx quantile test to epsilon from 2*epsilon to match paper

## How was this patch tested?

Existing tests.

### CODE REVIEW

**Review by kchenphy — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by gatorsmile** [comment]
cc @WeichenXu123

**Comment by WeichenXu123** [comment]
LGTM. Thanks! 👍

**Comment by viirya** [comment]
LGTM

**Comment by gatorsmile** [comment]
Thanks! Merged to master/2.3

**Pull request closed without merging**
