### PR TITLE
[SPARK-34021][R] Fix hyper links in SparkR documentation for CRAN submission

### PR DESCRIPTION
**Pull request by HyukjinKwon**
### What changes were proposed in this pull request?

3.0.1 CRAN submission was failed as the reason below:

```
   Found the following (possibly) invalid URLs:
     URL: http://jsonlines.org/ (moved to https://jsonlines.org/)
       From: man/read.json.Rd
             man/write.json.Rd
       Status: 200
       Message: OK
     URL: https://dl.acm.org/citation.cfm?id=1608614 (moved to
https://dl.acm.org/doi/10.1109/MC.2009.263)
       From: inst/doc/sparkr-vignettes.html
       Status: 200
       Message: OK
 ```
 
The links were being redirected now. This PR checked all hyperlinks in the docs such as `href{...}` and `url{...}`, and fixed all in SparkR:

- Fix two problems above.
- Fix http to https
- Fix `https://www.apache.org/ https://spark.apache.org/` -> `https://www.apache.org https://spark.apache.org`.

### Why are the changes needed?

For CRAN submission.

### Does this PR introduce _any_ user-facing change?

Virtually no because it's just cleanup that CRAN requires.

### How was this patch tested?

Manually tested by clicking the links

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
cc @felixcheung and @shivaram. I think we can just start it from Spark 3.1.0 on CRAN.

BTW, I verified all commits that added http(s) links to the docs after Spark 3.0.0:
- https://github.com/apache/spark/commit/f81f11822cbba060d9010ff39c185c45e7e013a2
- https://github.com/apache/spark/commit/0d37f794ef9451199e1b757c1015fc7a8b3931a5
- https://github.com/apache/spark/commit/697fe911acff8335165733a98307bf7a4d4ef331
- https://github.com/apache/spark/commit/56a8510e19b3e0349e41d2a8903f4bf05ca00a28

their links look all valid and there's no move or redirections here. So only fixing the two problems pointed out for Spark 3.0.1 should work.

**Comment by HyukjinKwon** [comment]
Wow, thanks @dongjoon-hyun.

**Review by MaxGekk — COMMENTED** [review]
> Manually tested by clicking the links

Can we do that automatically on our side?

**Comment by HyukjinKwon** [comment]
Not sure. I should I ask what kind of tool they use, actually. Ideally that should be part of `R CMD check` but seems not.

**Comment by HyukjinKwon** [comment]
Merged to master and branch-3.1

**Pull request closed without merging**
