### PR TITLE
[SPARK-29246][CORE] Remove unnecessary imports in `core` module

### PR DESCRIPTION
**Pull request by sev7e0**
### What changes were proposed in this pull request?

Remove unnecessary imports in `core` module.

### Why are the changes needed?

Clean  code for Apache Spark 3.0.0.

### Does this PR introduce any user-facing change?

No.

### How was this patch tested?

Local test.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Hi, @sev7e0 . We usually do module-by-module for this kind of task. Could you find more in `core` module?

**Comment by sev7e0** [comment]
Thanks for your comment. I will try to check the rest of `core`. @dongjoon-hyun

**Comment by dongjoon-hyun** [comment]
Thank you, @sev7e0 . You can use `IntelliJ` feature.

**Comment by sev7e0** [comment]
Hi, @dongjoon-hyun . I have checked the imports in all the files in core and optimized them. Please review. Thank you!

**Comment by dongjoon-hyun** [comment]
ok to test

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. (Pending Jenkins).

Thank you so much, @sev7e0 ! Although GitHub Action already verified the compilation, we had better pass the Jenkins testing. I'll merge this after test completion.

**Review by maropu — APPROVED** [review]

**Comment by sev7e0** [comment]
Ok. Thank you, @dongjoon-hyun and @maropu ！

**Comment by dongjoon-hyun** [comment]
Merged to master.

**Comment by dongjoon-hyun** [comment]
Thank you, @sev7e0 and @maropu .

**Pull request closed without merging**
