### PR TITLE
[SPARK-47428][BUILD][3.5] Upgrade Jetty to 9.4.54.v20240208

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to upgrade Jetty to 9.4.54.v20240208

### Why are the changes needed?

To bring the latest bug fixes.
- https://github.com/jetty/jetty.project/releases/tag/jetty-9.4.54.v20240208
- https://github.com/jetty/jetty.project/releases/tag/jetty-9.4.53.v20231009

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the CIs.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Review by yaooqinn — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @yaooqinn .

**Comment by dongjoon-hyun** [comment]
Python test pipeline failures are irrelevant to this. https://github.com/apache/spark/pull/45416 seems to be the usual suspect.

Screenshot 2024-03-15 at 22 25 09

```
======================================================================
FAIL [0.057s]: test_toPandas_timestmap_tzinfo (pyspark.sql.tests.test_arrow.RDDBasedArrowTests) (arrow_enabled=True)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/spark/spark/python/pyspark/sql/tests/test_arrow.py", line 1099, in test_toPandas_timestmap_tzinfo
    self.check_toPandas_timestmap_tzinfo(arrow_enabled)
  File "/__w/spark/spark/python/pyspark/sql/tests/test_arrow.py", line 1121, in check_toPandas_timestmap_tzinfo
    assert_frame_equal(pdf, expected)
  File "/usr/local/lib/python3.9/dist-packages/pandas/_testing/asserters.py", line 1224, in assert_frame_equal
    assert_series_equal(
  File "/usr/local/lib/python3.9/dist-packages/pandas/_testing/asserters.py", line 931, in assert_series_equal
    assert_attr_equal("dtype", left, right, obj=f"Attributes of {obj}")
  File "/usr/local/lib/python3.9/dist-packages/pandas/_testing/asserters.py", line 415, in assert_attr_equal
    raise_assert_detail(obj, msg, left_attr, right_attr)
  File "/usr/local/lib/python3.9/dist-packages/pandas/_testing/asserters.py", line 599, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: Attributes of DataFrame.iloc[:, 0] (column name="a") are different

Attribute "dtype" are different
[left]:  datetime64[us]
[right]: datetime64[ns]

----------------------------------------------------------------------
Ran 157 tests in 51.209s
```

**Comment by dongjoon-hyun** [comment]
Let me merge this because the commit GitHub Action seems to be fine so far.

**Comment by dongjoon-hyun** [comment]
Merged to branch-3.5.

**Pull request closed without merging**
