### PR TITLE
[SPARK-47299][PYTHON][DOCS] Use the same `versions.json` in the dropdown of different versions of PySpark documents

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to use the same `versions.json` in the dropdown of `different versions` of PySpark documents.

### Why are the changes needed?
As discussed in the email group, using this approach can avoid `maintenance difficulties` and `inconsistencies` that may arise when `multi active release version lines` are released in the future.
image

### Does this PR introduce _any_ user-facing change?
Yes, only for pyspark docs.

### How was this patch tested?
- Manually test.
- Pass GA.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by panbingkun** [comment]
cc @HyukjinKwon @HeartSaVioR

**Review by HeartSaVioR — APPROVED** [review]
+1

@panbingkun Could you please remove the versions.json in pyspark docs as well to be not confused?

**Comment by HeartSaVioR** [comment]
(BTW sorry for visiting this too lately. Was very busy with other stuffs.)

**Comment by panbingkun** [comment]
> +1
> 
> @panbingkun Could you please remove the versions.json in pyspark docs as well to be not confused?

Done

Thank you `very much` for taking the time to review this PR.
❤️

**Comment by HeartSaVioR** [comment]
Thanks! Merging to master/3.5.

**Pull request closed without merging**
