### PR TITLE
[SPARK-17677][SQL] Break WindowExec.scala into multiple files

### PR DESCRIPTION
**Pull request by rxin**
## What changes were proposed in this pull request?

As of Spark 2.0, all the window function execution code are in WindowExec.scala. This file is pretty large (over 1k loc) and has a lot of different abstractions in them. This patch creates a new package sql.execution.window, moves WindowExec.scala in it, and breaks WindowExec.scala into multiple, more maintainable pieces:
- AggregateProcessor.scala
- BoundOrdering.scala
- RowBuffer.scala
- WindowExec
- WindowFunctionFrame.scala
## How was this patch tested?

This patch mostly moves code around, and should not change any existing test coverage.

### CODE REVIEW

**Comment by rxin** [comment]
cc @hvanhovell for review. This is mostly simple copy/paste. I did look over the warnings in IntelliJ and spacing issues.

Also @yhuai and @hvanhovell - I noticed there was virtually 0 unit test coverage for this complicated feature. There are some end-to-end tests, but we should have built unit tests to cover the fundamental classes (e.g. BoundOrdering, RowBuffer, WindowFunctionFrame). We need to be more careful in creating new code & reviewing code.

**Comment by hvanhovell** [comment]
retest this please

**Comment by hvanhovell** [comment]
LGTM - pending jenkins.

**Comment by hvanhovell** [comment]
Merging to master. Thanks!

**Pull request closed without merging**
