### PR TITLE
[SPARK-48749][SQL] Simplify UnaryPositive and eliminate its Catalyst Rules with RuntimeReplaceable

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

Simplify UnaryPositive and eliminate its Catalyst Rules with RuntimeReplacable

### Why are the changes needed?

code simplification

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

new test cases

### Was this patch authored or co-authored using generative AI tooling?

no

### CODE REVIEW

**Comment by yaooqinn** [comment]
cc @cloud-fan @dongjoon-hyun @HyukjinKwon @LuciferYang thanks

**Review by LuciferYang — APPROVED** [review]
+1, LGTM 
thanks @yaooqinn

**Comment by yaooqinn** [comment]
Thank you @LuciferYang, merged to master

**Comment by cloud-fan** [comment]
late LGTM

**Pull request closed without merging**
