### PR TITLE
[SPARK-12820][SQL]Resolve db.table.column

### PR DESCRIPTION
**Pull request by zhichao-li**
Currently spark only support to specify col name like: `table.col`, or `col` in projection, but it's very common that user use `db.table.col` especially when join table across database.
Hive doesn't support this for now but it has been used in lot of other traditional db like mysql.

### CODE REVIEW

**Comment by rxin** [comment]
When we have a database named "a", and two tables:
1. a table also named "a", and a struct column named "b", and a field in the struct named "c".
2. a table named "b", and a column in it named "c"

What happens if the user specifies "a.b.c"?

**Comment by zhichao-li** [comment]
It would return attribute c in table b up on this patch. Any suggestion? throw ambiguous exception for such case?

**Comment by rxin** [comment]
What do we do if the user specifies "a.b" right now? I'd say we should follow that, and make sure we have a test case for it.

**Comment by zhichao-li** [comment]
Would return attribute b in table a.  resolved within the logic of `table.col`

**Comment by chenghao-intel** [comment]
I would say we'd better keep the same checking logic with mysql/hive for the `ambiguous` case, @zhichao-li can you please check that with mysql/hive?

**Comment by zhichao-li** [comment]
@chenghao-intel , mysql(5.5) doesn't support nested data type for now, and hive(1.2.1) doesn't support the usage of "db.table.field" in projection list at the moment.  I guess most of the user work around this by using alias.

**Comment by rxin** [comment]
Thanks for the pull request. I'm going through a list of pull requests to cut them down since the sheer number is breaking some of the tooling we have. Due to lack of activity on this pull request, I'm going to push a commit to close it. Feel free to reopen it or create a new one. We can also continue the discussion on the JIRA ticket.

**Pull request closed without merging**
