### PR TITLE
[SPARK-31102][SQL][3.0] Spark-sql fails to parse when contains comment

### PR DESCRIPTION
**Pull request by javierivanov**
This PR introduces a change to false for the insideComment flag on a newline. Fixing the issue introduced by SPARK-30049. 

Backport to 3.0 from #27920 

Previously on SPARK-30049 a comment containing an unclosed quote produced the following issue:
```
spark-sql> SELECT 1 -- someone's comment here
         > ;
Error in query:
extraneous input ';' expecting <EOF>(line 2, pos 0)

== SQL ==
SELECT 1 -- someone's comment here
;
^^^
```

This was caused because there was no flag for comment sections inside the splitSemiColon method to ignore quotes. SPARK-30049 added that flag and fixed the issue, but introduced the follwoing problem:
```
spark-sql> select
         >   1,
         >   -- two
         >   2;
Error in query:
mismatched input '<EOF>' expecting {'(', 'ADD', 'AFTER', 'ALL', 'ALTER', ...}(line 3, pos 2)
== SQL ==
select
  1,
--^^^
```
This issue is generated by a missing turn-off for the insideComment flag with a newline.

No

- For previous tests using line-continuity(`\`) it was added a line-continuity rule in the SqlBase.g4 file to add the functionality to the SQL context.
- A new test for inline comments was added.

Closes #27920 from javierivanov/SPARK-31102.

Authored-by: Javier Fuentes <j.fuentes.m@icloud.com>
Signed-off-by: Wenchen Fan <wenchen@databricks.com>

### CODE REVIEW

**Comment by cloud-fan** [comment]
ok to test

**Review by cloud-fan — APPROVED** [review]

**Comment by maropu** [comment]
retest this please

**Review by maropu — APPROVED** [review]

**Comment by maropu** [comment]
It seems the failure above is not related to this PR. See: https://github.com/apache/spark/pull/28566

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by maropu** [comment]
Looks nice! Thanks for re-trigger the tests, @HyukjinKwon .

**Comment by AngersZhuuuu** [comment]
retest this please

**Comment by cloud-fan** [comment]
The newly added test all fails. Seems there is something different in branch 3.0.

**Comment by javierivanov** [comment]
> The newly added test all fails. Seems there is something different in branch 3.0.

I added those test by mistake while cherry-picking. Checking.

**Comment by maropu** [comment]
Thanks! Merged to branch-3.0.

**Pull request closed without merging**
