### PR TITLE
[SPARK-15472][SQL][Streaming] Add partitioned `csv`, `json`, `text` format support for FileStreamSink

### PR DESCRIPTION
**Pull request by lw-lin**
## What changes were proposed in this pull request?

This patch adds partitioned `csv`, `json`, `text` format support for `FileStreamSink`.

For each format, this patch adds a dedicated `OutputWriterFactory`, which would return a dedicated `OutputWriter` writing data without using an `OutputCommitter`. This is the same approach taken by [SPARK-14716](https://github.com/apache/spark/pull/12409) in which we had added partitioned `parquet` format support.
## How was this patch tested?

`FileStreamSinkSuite` is expanded to cover the added `csv`, `json`, `text` format:

``` scala
test(" csv - unpartitioned data")
test("json - unpartitioned data")
test("text - unpartitioned data")

test(" csv - partitioned data")
test("json - partitioned data")
test("text - partitioned data")

test(" csv - unpartitioned writing and batch reading")
test("json - unpartitioned writing and batch reading")
test("text - unpartitioned writing and batch reading")

test(" csv - partitioned writing and batch reading")
test("json - partitioned writing and batch reading")
test("text - partitioned writing and batch reading")
```

### CODE REVIEW

**Comment by lw-lin** [comment]
@marmbrus @tdas @zsxwing would you mind taking a look? Thanks!

**Comment by zsxwing** [comment]
@lw-lin I'm wondering if you can add an abstract layer (e.g., AbstractOutputWriterFactory and AbstractOutputWriter) to eliminate the duplicated codes. There are a lot of duplicated codes in these formats and hard to maintain.

**Comment by lw-lin** [comment]
@zsxwing sure let's add an abstract layer. I'll rebase and do this in the next two days or so. Thanks for the review! :-)

**Comment by zsxwing** [comment]
@lw-lin could you update this PR soon? Otherwise, we may not be able to merge into 2.0.

**Comment by lw-lin** [comment]
@zsxwing , yeah let me update this in the next one day or so - I was waiting for https://github.com/apache/spark/pull/13431. Thanks for the reminder!

**Pull request closed without merging**
