### PR TITLE
[MINOR] Fix typo `Exlude` to `Exclude` in `HealthTracker`

### PR DESCRIPTION
**Pull request by cxzl25**
### What changes were proposed in this pull request?
Fix typo

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
exist UT

### CODE REVIEW

**Comment by srowen** [comment]
OK, it's an internal class

**Comment by srowen** [comment]
Could you try rerunning tests? The failure isn't related, I'm sure

**Comment by cxzl25** [comment]
> Could you try rerunning tests? The failure isn't related, I'm sure

Thanks, now GA passed.

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
