### PR TITLE
[SPARK-7558] Demarcate tests in unit-tests.log

### PR DESCRIPTION
**Pull request by andrewor14**
Right now `unit-tests.log` is not of much value because we can't tell where the test boundaries are easily. This patch adds log statements before and after each test to outline the test boundaries, e.g.:

```
===== TEST OUTPUT FOR o.a.s.serializer.KryoSerializerSuite: 'kryo with parallelize for primitive arrays' =====

15/05/27 12:36:39.596 pool-1-thread-1-ScalaTest-running-KryoSerializerSuite INFO SparkContext: Starting job: count at KryoSerializerSuite.scala:230
15/05/27 12:36:39.596 dag-scheduler-event-loop INFO DAGScheduler: Got job 3 (count at KryoSerializerSuite.scala:230) with 4 output partitions (allowLocal=false)
15/05/27 12:36:39.596 dag-scheduler-event-loop INFO DAGScheduler: Final stage: ResultStage 3(count at KryoSerializerSuite.scala:230)
15/05/27 12:36:39.596 dag-scheduler-event-loop INFO DAGScheduler: Parents of final stage: List()
15/05/27 12:36:39.597 dag-scheduler-event-loop INFO DAGScheduler: Missing parents: List()
15/05/27 12:36:39.597 dag-scheduler-event-loop INFO DAGScheduler: Submitting ResultStage 3 (ParallelCollectionRDD[5] at parallelize at KryoSerializerSuite.scala:230), which has no missing parents

...

15/05/27 12:36:39.624 pool-1-thread-1-ScalaTest-running-KryoSerializerSuite INFO DAGScheduler: Job 3 finished: count at KryoSerializerSuite.scala:230, took 0.028563 s
15/05/27 12:36:39.625 pool-1-thread-1-ScalaTest-running-KryoSerializerSuite INFO KryoSerializerSuite:

===== FINISHED o.a.s.serializer.KryoSerializerSuite: 'kryo with parallelize for primitive arrays' =====

...
```

### CODE REVIEW

**Comment by andrewor14** [comment]
@JoshRosen @pwendell

**Comment by JoshRosen** [comment]
Can we modify the style checker / linter to fail the build if someone commits a new test which uses FunSuite directly instead of using SparkFunSuite?

**Comment by pwendell** [comment]
Can you use the same patterns for the start and finish thresholds? Any reason to use `===` and then `***`?

```
===== TEST OUTPUT FOR o.a.s.serializer.KryoSerializerSuite: 'kryo with parallelize for primitive arrays' =====
***** FINISHED o.a.s.serializer.KryoSerializerSuite: 'kryo with parallelize for primitive arrays' *****
```

**Comment by andrewor14** [comment]
I can use the same one. Which one do you prefer?

**Comment by andrewor14** [comment]
I dug into this a bit about why this is failing. It turns out that `core/test` depends on guava 15 (from tachyon), while `core` depends on guava 14. The full error message is a `java.lang.IllegalAccessError` complaining that a certain method in guava cannot be accessed; this is frequently caused by classpath issues.

In commit da0b12f403735470596e427d22a6d8238432dbae we made `catalyst/test` depend on `core/test`. This is a problem since `hive/test` depends on `catalyst/test`, so we are indirectly packaging guava 15 into hive tests.

**Comment by pwendell** [comment]
Can we exclude guava from tachyon in the test dependency?

- Patrick

**Comment by andrewor14** [comment]
Yeah I'm doing that right now

**Comment by andrewor14** [comment]
Alright, it turns out that it was selenium, not tachyon, that was bundling guava 15. I tested out the latest changes locally and tests should now pass.

**Comment by andrewor14** [comment]
@JoshRosen that's a great suggestion, though one that I would prefer to implement after the test scripts are converted to python (ongoing at #5694).

**Comment by JoshRosen** [comment]
Yeah, probably best to introduce the error  / warning gradually, too, since I suspect it would cause a lot of build breaks if we merge PRs that are passing tests w/o retesting with the new build.

**Comment by andrewor14** [comment]
Latest set of tests failed because a new test suite was merged into master in an existing test file :).
This is now fixed as of the latest commit.

**Comment by andrewor14** [comment]
By the way @yhuai I figured out why the `sql.VersionsSuite` was failing. See 888258162cec148133efcdb5bc53e8fe9c8787e1

**Comment by rxin** [comment]
We can easily add a scalastyle check to grep for "FunSuite".

**Comment by rxin** [comment]
@andrewor14 can you bring this up to date?

**Comment by andrewor14** [comment]
I will, but it's still failing a hive-thriftserver test that I'm investigating offline

**Comment by andrewor14** [comment]
This now merges with master cleanly, but it will still fail the `hive-thriftserver` tests until #6493 is merged.

**Comment by andrewor14** [comment]
@rxin I was planning to add it to `run-test-jenkins` after it's converted to python. IMO it shouldn't really be a scala style failure if the user doesn't extend my thing.

**Comment by andrewor14** [comment]
Alright, I just merged #6493 and rebased. The latest run *should* pass...

**Comment by rxin** [comment]
@andrewor14 why shouldn't it? The script is called lint-scala, not just style checks.

**Comment by andrewor14** [comment]
Yes, but the error message the developer gets is the same. It's a little strange from the developer's perspective: they're just extending a class, which is totally legitimate, and suddenly they get `This patch fails Scala style checks`.

Also, it actually won't work unless we exclude certain files, because `SparkFunSuite` does extend `FunSuite`. I just think a better place to do it would be in the PR diff.

**Comment by rxin** [comment]
It's really easy to exclude.
```
//scalastyle:off
//scalastyle:on
```

**Comment by rxin** [comment]
The problem with doing one-off stuff like this is that it is very hard to maintain. Imagine you have some place that you'd need to add FunSuite, or maybe document that includes the word "FunSuite". Since the script we wrote ourselves don't do any syntactic parsing, we will have to change the script itself to add new excludes. These scripts are not very well tested, and then they might just break (i.e. no longer checking) without us knowing.

**Comment by andrewor14** [comment]
I don't see how it's a one-off. Unlike doing it through scalastyle, my proposal actually doesn't require any explicit exclusions because it only checks the diff (i.e. future code). We check for something more specific like `extends FunSuite`, which is unlikely to be mentioned in a comment. I also don't anticipate tests in the future that actually extends `FunSuite` directly, since we want everything to go through the new class (the whole point of this patch).

By the way, I don't actually feel super strongly about this, so if you prefer we can do it through scalastyle. I just find it a little strange to do so because it's not really a style violation.

**Comment by andrewor14** [comment]
Either way let's do it outside of this patch because it's particularly prone to merge conflicts.

**Comment by andrewor14** [comment]
The last tests actually passed (see commit order). I'm merging this into master. If there are follow-up fixes or comments let's address it separately. Thanks everyone.

**Comment by andrewor14** [comment]
Note to self: when we backport this later remember to also back port the two hot fixes:

8c9979337f193c72fd2f1a891909283de53777e3
a4f24123d8857656524c9138c7c067a4b1033a5e

**Comment by steveloughran** [comment]
Regarding backporting, it could be enough to start with copying {{SparkFunSuite}} into 1.3 & 1.4 branches, so that any new patches written against trunk can be applied to those branches without any rewrites being needed. You wouldn't need to patch the existing tests for that, just have new tests switch to it even in the older branches

**Pull request closed without merging**
