### PR TITLE
[SPARK-16617] Upgrade to Avro 1.8.1

### PR DESCRIPTION
**Pull request by benmccann**
## What changes were proposed in this pull request?

Upgrade to Avro 1.8.1
## How was this patch tested?

Ran `mvn test`

### CODE REVIEW

**Comment by srowen** [comment]
In general that has a lot of implications, since I think this will mismatch the version in several Hadoop versions. You probably need to

- Read https://cwiki.apache.org/confluence/display/SPARK/Contributing+to+Spark
- Fix up this PR accordingly
- At least run the script that updates the deps/ files to see that impact
- Check what version Hadoop 2.2 and 2.7 use as references
- Figure out what the upside is in updating to 1.8
- Note any potential incompatibilities here

**Comment by HyukjinKwon** [comment]
FYI, it seems its 1.7.4 for Hadoop 2.7, https://github.com/apache/hadoop/blob/release-2.7.0/hadoop-project/pom.xml#L60-L61 and Hadoop 2.2, https://github.com/apache/hadoop/blob/release-2.2.0/hadoop-project/pom.xml#L62-L63.

**Comment by srowen** [comment]
We probably don't want to mismatch Hadoop's version unless you've vetted this fairly carefully that it is backwards compatible.

**Comment by benmccann** [comment]
>At least run the script that updates the deps/ files to see that impact

Can you point me to the script you're referring to?

> Figure out what the upside is in updating to 1.8

The reason I'm proposing this change is that Avro 1.8 makes the generated classes serializable so that you can create RDDs containing Avro objects.

> Note any potential incompatibilities here

Here's the list of incompatible changes from the [changelog](https://github.com/apache/avro/blob/master/CHANGES.txt):

* AVRO-1334. Java: Update versions of many dependencies. (scottcarey, cutting)
* AVRO-997. Java: For enum values, no longer sometimes permit any Object whose toString() names an enum symbol, but rather always require use of distinct enum types. (Sean Busbey via cutting)
* AVRO-1602. Java: Remove Dapper-style RPC trace facility.  This seems unused and has been a source of build problems.  (cutting)
* AVRO-1586. Build against Hadoop 2. With this change the avro-mapred and trevni-avro JARs without a hadoop1 or hadoop2 Maven classifier are Hadoop 2 artifacts. To use with Hadoop 1, set the classifier to hadoop1. (tomwhite)
* AVRO-1502. Java: Generated classes now implement Serializable. Generated classes need to be regenerated to use this release. (cutting)

**Comment by srowen** [comment]
Have a look at  `dev/test-dependencies.sh --replace-manifest`. I think the big concern is matching the Hadoop dependency, which will be on 1.7.x for 2.x. Updating to the latest 1.7.x seems OK. You can also test this change anyway after making the deps change to see what happens.

**Comment by benmccann** [comment]
I'll close for now until Hadoop 3.x. Thanks

**Pull request closed without merging**
