### PR TITLE
[SPARK-30493][PYTHON][ML] Remove OneVsRestModel setClassifier, setLabelCol and setWeightCol methods

### PR DESCRIPTION
**Pull request by zero323**
### What changes were proposed in this pull request?

Removal of `OneVsRestModel.setClassifier`, `OneVsRestModel.setLabelCol` and `OneVsRestModel.setWeightCol`  methods.

### Why are the changes needed?

Aforementioned methods shouldn't by included by [SPARK-29093](https://issues.apache.org/jira/browse/SPARK-29093), as they're not present in Scala `OneVsRestModel` and have no practical application.

### Does this PR introduce any user-facing change?

Not beyond scope of SPARK-29093].

### How was this patch tested?

Existing tests.

CC @huaxingao @zhengruifeng

### CODE REVIEW

**Comment by huaxingao** [comment]
```setLabelCol``` is still required. The other two should be removed.
Thanks for catching the problem!

**Comment by zero323** [comment]
> `setLabelCol` is still required.

Is it really? [Doesn't seem](https://spark.apache.org/docs/3.0.0-preview2/api/scala/org/apache/spark/ml/classification/OneVsRestModel.html) like Scala counterpart doesn't has one. And ignoring that ‒ when would a `Model` use it?

**Comment by zero323** [comment]
Retest this please.

**Comment by huaxingao** [comment]
```setLabelCol``` is called in ```OneVsRestModel._from_java```

**Comment by huaxingao** [comment]
actually, should use ```_set``` instead of ```setLabelCol``` in ```OneVsRestModel._from_java```.

**Comment by zero323** [comment]
Shouldn't `weightCol` be set as well?

**Comment by huaxingao** [comment]
Yes, I think ```weightCol``` should be set as well for ```OneVsRestModel._from_java/_to_java``` and ```OneVsRest._from_java/_to_java```

**Comment by HyukjinKwon** [comment]
@zero323, please keep and follow the PR template - https://github.com/apache/spark/blob/master/.github/PULL_REQUEST_TEMPLATE

**Comment by zhengruifeng** [comment]
looks reasonably straightforward
@huaxingao Seem we do not need those setter in OVRModel?

**Comment by huaxingao** [comment]
@zhengruifeng Yes. These setters can be removed. The internal methods can use ```_set``` to set ```classifier```, ```labelCol``` and ```weightCol```

**Review by zhengruifeng — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Before merging it, can we update PR description properly please? It's best to avoid having bad PR examples.

**Review by zhengruifeng — APPROVED** [review]

**Comment by zhengruifeng** [comment]
Merged to master, thanks all!

**Comment by zero323** [comment]
> @zero323, please keep and follow the PR template - https://github.com/apache/spark/blob/master/.github/PULL_REQUEST_TEMPLATE

Sorry @HyukjinKwon, it felt more like a follow-up / cleanup, than a full proposal.

**Comment by zero323** [comment]
> Yes, I think `weightCol` should be set as well for `OneVsRestModel._from_java/_to_java` and `OneVsRest._from_java/_to_java`

FYI I've opened [SPARK-30504](https://issues.apache.org/jira/browse/SPARK-30504).

**Pull request closed without merging**
