### PR TITLE
[SPARK-14969][MLLib] Remove duplicate implementation of compute in LogisticGradient

### PR DESCRIPTION
**Pull request by dding3**
## What changes were proposed in this pull request?

This PR removes duplicate implementation of compute in LogisticGradient class
## How was this patch tested?

unit tests

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
(@dding3 I think maybe you can remove the default lines such as "(Please fill in changes proposed in this fix)".)

**Comment by dding3** [comment]
Thanks for your comments. Removed the PR description.

**Comment by hhbyyh** [comment]
LGTM .

**Comment by srowen** [comment]
You can also remove the one in `ANNGradient` right?

**Comment by dding3** [comment]
@srowen Thanks for your review. I have removed it in ANNGradient. Besides, I checked all subclass of Gradient, looks like there is no duplicate implementation now.

**Comment by srowen** [comment]
Jenkins test this please

**Pull request closed without merging**
