### PR TITLE
[SPARK-17647][SQL][FOLLOWUP][MINOR] fix typo

### PR DESCRIPTION
**Pull request by felixcheung**
## What changes were proposed in this pull request?

fix typo

## How was this patch tested?

manual

### CODE REVIEW

**Review by vundela — APPROVED** [review]
Thanks for working on this felixcheung. LGTM

**Comment by HyukjinKwon** [comment]
@felixcheung, the changes are fine to me too but I think we might need to give another scan to find such typos at least in the module or file. I am just worried if small typo PR merged as a reference can be a proper example and many people start to open PRs fixing typos (just what I have felt). I am worried of review/merge/test cost.

**Comment by felixcheung** [comment]
sure, I agree completely, but the reason I opened this PR was because this just went in today with this comment missed.
I wouldn't suggest or try to fix individual typo otherwise

**Comment by HyukjinKwon** [comment]
Yea, I just had to note this just in case someone refers this as a reference. Thanks for bearing with me.

**Comment by felixcheung** [comment]
got it. this was why I answered in details here too.

**Comment by felixcheung** [comment]
merged to master/2.1

**Pull request closed without merging**
