### PR TITLE
[SPARK-7850][BUILD] Hive 0.12.0 profile in POM should be removed

### PR DESCRIPTION
**Pull request by piaozhexiu**
I grep'ed hive-0.12.0 in the source code and removed all the profiles and doc references.

### CODE REVIEW

**Comment by srowen** [comment]
ok to test

**Comment by srowen** [comment]
I'm OK with that if this is true and the intent, but then do we need `hive-0.13.1` anymore either?

**Comment by rxin** [comment]
I think this is the intent - but I will let @marmbrus confirm.

**Comment by witgo** [comment]
The code is useless ?
https://github.com/apache/spark/tree/master/sql/hive

**Comment by chenghao-intel** [comment]
We probably also need to get rid of the HiveShim code as well in hive/hive-thriftserver modules.

**Comment by piaozhexiu** [comment]
@chenghao-intel thank you for pointing it out. I deleted 0.12 shim code.

**Comment by marmbrus** [comment]
@srowen, we should get rid of `-Phive-0.13.1` too.  The build should only ever need to support one version of hive from now on.  Another part of this task (would be nice to do now, but does not have to happen in this PR) is to inline the Hive13 shim, so we don't have this extra indirection anymore [SPARK-6909](https://issues.apache.org/jira/browse/SPARK-6909).

**Comment by piaozhexiu** [comment]
@marmbrus thanks for the confirmation. I removed -Phive-0.13.1 now.

Regarding SPARK-6909, can we do it in a separate PR? I'm happy to do it if no one is planning to do it.

**Comment by rxin** [comment]
Jenkins, retest this please.

**Comment by rxin** [comment]
@piaozhexiu looks good. I will merge once tests come back positive. It'd be great if you have some cycles to help out with SPARK-6909 to inline the Hive 13 stuff.

**Comment by piaozhexiu** [comment]
@rxin thank you! I'll look into SPARK-6909 this week.

**Comment by rxin** [comment]
Thanks. I've merged this in master & 1.4.

**Pull request closed without merging**
