### PR TITLE
[SPARK-27288][SQL] Pruning nested field in complex map key from object serializers

### PR DESCRIPTION
**Pull request by viirya**
## What changes were proposed in this pull request?

In the original PR #24158, pruning nested field in complex map key was not supported, because some methods in schema pruning did't support it at that moment. This is a followup to add it.

## How was this patch tested?

Added tests.

### CODE REVIEW

**Comment by viirya** [comment]
cc @dongjoon-hyun @maropu

**Review by maropu — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
In this case, I'd like to recommend to have a new JIRA issue.

**Comment by dongjoon-hyun** [comment]
cc @dbtsai

**Comment by viirya** [comment]
@dongjoon-hyun Thanks! Created a new JIRA for this.

**Comment by dbtsai** [comment]
LGTM.

**Comment by maropu** [comment]
Thanks! Merged to master.

**Pull request closed without merging**
