### PR TITLE
[SPARK-31369][SQL][DOCS] Documentation for JSON Functions

### PR DESCRIPTION
**Pull request by iRakson**
### What changes were proposed in this pull request?
Documentation for JSON functions

### Why are the changes needed?
To complete the SQL references.

### Does this PR introduce any user-facing change?
Yes. Now users can access JSON functions doc.

### How was this patch tested?
Manually

### CODE REVIEW

**Comment by iRakson** [comment]
@maropu @huaxingao 
Kindly Review this PR

**Comment by HyukjinKwon** [comment]
Hm, I think we don't need this - they will be automatically documented by `ExpressionDescription` you used (see https://spark.apache.org/docs/latest/api/sql/index.html)

**Comment by iRakson** [comment]
> Hm, I think we don't need this - they will be automatically documented by `ExpressionDescription` you used (see https://spark.apache.org/docs/latest/api/sql/index.html)

Actually @maropu asked to add this. If it is not required, i will close it. 

https://issues.apache.org/jira/browse/SPARK-31009?focusedCommentId=17054251&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17054251

**Comment by maropu** [comment]
I asked the same question in https://github.com/apache/spark/pull/28099#discussion_r402102476.
(I'm still wondering if these document pages are really necessary though) Probably, the categorized document pages only for popular built-in function groups (e.g., aggregate, array, and date/time functions) might be more useful for users than a full flatten list of the functions in `api/sql/`. For example the PostgreSQL documents have the categorized pages for the builtin functions:

 - aggregate functions: https://www.postgresql.org/docs/current/functions-aggregate.html
 - date/timestamp functions: https://www.postgresql.org/docs/current/functions-datetime.html
 - JSON functions: https://www.postgresql.org/docs/current/functions-json.html

Probably, I think this is an issue of maintainance cost vs document quality.

cc: @huaxingao @kevinyu98 @gatorsmile

**Comment by huaxingao** [comment]
When I did https://github.com/apache/spark/pull/28157, I actually changed the built-in function page to the following

Screen Shot 2020-04-09 at 11 58 36 PM


I think aggregation function and window function are worthwhile to document separately. We need to document Window function for sure because in query section, we have 
```[ WINDOW { named_window [ , WINDOW named_window, ... ] } ]```
So we need an introduction page to explain what window function is, how to use it, and what window functions Spark supports. Aggregation function is very important, and it can be used as window function as well, so it would be worth having a page to document this too.

@gatorsmile WDYT?

**Comment by HyukjinKwon** [comment]
I actually discussed this with @gatorsmile and @cloud-fan offline. I think we should basically reuse `ExpressionDescription` and generate the function documentation there .

We can add some more tags or fields into `ExpressionDescription`, and generate the documentation just like we do for SQL configuration (see also https://github.com/apache/spark/pull/27459)

**Comment by iRakson** [comment]
@HyukjinKwon @maropu 
Should i close this one then ?

**Comment by HyukjinKwon** [comment]
I think somebody can do the base job to add a field into `ExpressionDescription` and infra to generate the doc like the links I pointed out.

Then we could add the documentations accordingly in this PR,  #28157 and #28120.

@maropu, @huaxingao, @kevinyu98, I am very sorry I happened to check the ongoing on efforts in function documentation. Could we maybe try a way of reusing  https://spark.apache.org/docs/latest/api/sql/index.html?

**Comment by maropu** [comment]
@HyukjinKwon nvm. The proposed approach looks the best to me.

**Comment by maropu** [comment]
@iRakson Yea, closing this looks fine to me. Anyway, thanks for work.

**Comment by HyukjinKwon** [comment]
Yes, I am good with any target version.

**Pull request closed without merging**
