### PR TITLE
[SPARK-16082][SparkR]remove duplicated docs in dapply

### PR DESCRIPTION
**Pull request by NarineK**
## What changes were proposed in this pull request?

Removed unnecessary duplicated documentation in dapply and dapplyCollect.

In this pull request I created separate R docs for dapply and dapplyCollect - kept dapply's documentation separate from dapplyCollect's and referred from one to another via a link.
## How was this patch tested?

Existing test cases.

### CODE REVIEW

**Comment by NarineK** [comment]
cc: @sun-rui, @shivaram @felixcheung

**Comment by shivaram** [comment]
LGTM -- @felixcheung @sun-rui let me know if you have any comments

**Comment by felixcheung** [comment]
LGTM

**Comment by sun-rui** [comment]
LGTM

**Comment by NarineK** [comment]
@shivaram , I've noticed that I didn't associate the pull request with the jira. I've just did it.

**Comment by shivaram** [comment]
Thanks -- I should have noticed it before the merge, but missed it. I have resolved the JIRA and put in a link to the PR there, so I think its all fine.

**Pull request closed without merging**
