### PR TITLE
[SPARK-27899][SQL] Refactor getTableOption() to extract a common method

### PR DESCRIPTION
**Pull request by LantaoJin**
## What changes were proposed in this pull request?

This is a part of #24774, to reduce the code changes made by that.

## How was this patch tested?

Exist UTs.

### CODE REVIEW

**Comment by LantaoJin** [comment]
cc @gatorsmile @wangyum

**Review by gatorsmile — COMMENTED** [review]
LGTM

**Comment by gatorsmile** [comment]
ok to test

**Comment by wangyum** [comment]
retest this please

**Comment by gatorsmile** [comment]
LGTM 

Thanks! Merged to master.

**Pull request closed without merging**
