### PR TITLE
[SPARK-50080][SQL][TESTS] Add benchmark cases for parquet adaptive bloom filter in BloomFilterBenchmark

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

Parquet's AdaptiveBlockSplitBloomFilter is a technique for generating a bloom filter with the optimal bit size according to the number of distinct real data values. It may not come at no cost because it uses multiple BloomFilter candidates at runtime, which could increase CPU usage or time. 

This pull request adds benchmark cases to compare with those that use the default BloomFilter size.

### Why are the changes needed?

Improvement benchmark coverage for common user-orient features from parquet datasource

### Does this PR introduce _any_ user-facing change?

no
### How was this patch tested?

benchmarking golden files attached 

### Was this patch authored or co-authored using generative AI tooling?

no

### CODE REVIEW

**Comment by yaooqinn** [comment]
cc @dongjoon-hyun @LuciferYang thanks

**Review by LuciferYang — APPROVED** [review]
+1, LGTM

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Review by dongjoon-hyun — COMMENTED** [review]
+1, late LGTM.

**Comment by yaooqinn** [comment]
Thank you @HyukjinKwon @dongjoon-hyun @LuciferYang

**Pull request closed without merging**
