### PR TITLE
[SPARK-32088][PYTHON] Pin the timezone in timestamp_seconds doctest

### PR DESCRIPTION
**Pull request by GuoPhilipse**
### What changes were proposed in this pull request?

Add American timezone during timestamp_seconds doctest

### Why are the changes needed?

`timestamp_seconds` doctest in `functions.py` used default timezone to get expected result
For example:

```python
>>> time_df = spark.createDataFrame([(1230219000,)], ['unix_time'])
>>> time_df.select(timestamp_seconds(time_df.unix_time).alias('ts')).collect()
[Row(ts=datetime.datetime(2008, 12, 25, 7, 30))]
```

But when we have a non-american timezone, the test case will get different test result.

For example, when we set current timezone as `Asia/Shanghai`, the test result will be 

```
[Row(ts=datetime.datetime(2008, 12, 25, 23, 30))]
```

So no matter where we run the test case ,we will always get the expected permanent result if we set the timezone on one specific area.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Unit test

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
ok to test

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
@GuoPhilipse, can you elaborate a bit more in the PR description about why it fails with which output?

**Comment by GuoPhilipse** [comment]
> @GuoPhilipse, can you elaborate a bit more in the PR description about why it fails with which output?

sure, will improve it.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @GuoPhilipse and @HyukjinKwon !
Merged to master.

**Comment by MaxGekk** [comment]
Actually, the SQL config `spark.sql.session.timeZone` is not used in PySpark collect() at all. This PR fixes the problem of running the example in a time zone different from `America/Los_Angeles`: https://github.com/apache/spark/pull/28959

**Pull request closed without merging**
