### PR TITLE
[SPARK-41276][SQL][ML][MLLIB][PROTOBUF][PYTHON][R][SS][AVRO] Optimize constructor use of `StructType`

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
There are two main ways to construct `StructType`:

- Primary constructor

```scala
case class StructType(fields: Array[StructField])
```

- Use `Seq` as input constructor

```scala
def apply(fields: Seq[StructField]): StructType = StructType(fields.toArray)
```

These two construction methods are widely used in Spark, but the latter requires an additional collection conversion.

This pr changes the following 3 scenarios to use primary constructor to reduce one collection conversion:

1. For manually create `Seq` input scenes, change to use manually create `Array` input instead, for examaple:

https://github.com/apache/spark/blob/bcf03fe3f86a7230fd977c059b73a58554370d5d/mllib/src/main/scala/org/apache/spark/ml/image/ImageSchema.scala#L55-L63

2. For the scenario where `toSeq` is added to create input for compatibility with Scala 2.13, directly call 'toArray' to instead, for example:

https://github.com/apache/spark/blob/bcf03fe3f86a7230fd977c059b73a58554370d5d/connector/avro/src/main/scala/org/apache/spark/sql/avro/SchemaConverters.scala#L108-L113

3. For scenes whose input is originally `Array`, remove the redundant `toSeq`, for example:

https://github.com/apache/spark/blob/bcf03fe3f86a7230fd977c059b73a58554370d5d/sql/catalyst/src/main/scala/org/apache/spark/sql/types/StructType.scala#L587-L592

All changes involved are local variables, and the input array will not escape and be accidentally change, so it is safe.

### Why are the changes needed?
Reduce unnecessary collection conversion.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?

- Pass GitHub Actions
- Manually test with Scala 2.13, all UTs passed

### CODE REVIEW

**Comment by srowen** [comment]
I assume it's less change to change these usages, rather than swap the implementation of the constructors so that the Array one calls the Seq one? OK if so

**Comment by LuciferYang** [comment]
These Array are local variables, and they will not escape and be changed unexpectedly

**Comment by LuciferYang** [comment]
Yes, not that case

**Comment by LuciferYang** [comment]
For production code, Array one is used in 75 places and Seq one is used in 132 places before this pr

**Comment by srowen** [comment]
Merged to master

**Comment by LuciferYang** [comment]
Thanks @srowen

**Pull request closed without merging**
