### PR TITLE
[SPARK-11544][SQL][test-hadoop1.0] sqlContext doesn't use PathFilter

### PR DESCRIPTION
**Pull request by dilipbiswal**
Apply the user supplied pathfilter while retrieving the files from fs.

### CODE REVIEW

**Comment by dilipbiswal** [comment]
@yhuai Hi Yin, i have created this new PR. Yin, is there a way we can test this using the old and new hadoop configuration before merging in ?

**Comment by yhuai** [comment]
You can put `[test-hadoop1.0]` in the title. Then, our test will run hadoop 1 test.

**Comment by dilipbiswal** [comment]
@yhuai Can you please help to trigger a test ? Thanks much.

**Comment by yhuai** [comment]
test this please

**Comment by yhuai** [comment]
ok to test

**Comment by dilipbiswal** [comment]
@yhuai Hello Yin, the test that fails seems to be unrelated. Failing with 

sbt.ForkMain$ForkError: Job aborted due to stage failure: Task 0 in stage 139.0 failed 1 times, most recent failure: Lost task 0.0 in stage 139.0 (TID 1591, localhost): java.lang.NoClassDefFoundError: au/com/bytecode/opencsv/CSVReader

Not sure if this test is supposed to run OK in this hadoop level. Please advise..

**Comment by yhuai** [comment]
I think that jenkins worker has a weird hive jar.

**Comment by yhuai** [comment]
test this please

**Comment by yhuai** [comment]
Thank you! I am merging this to master and branch 1.6.

**Comment by dilipbiswal** [comment]
@yhuai Thank you Yin.

**Pull request closed without merging**
