### PR TITLE
[DO NOT MERGE] Test NEW GA FAILURE

### PR DESCRIPTION
**Pull request by yaooqinn**
In https://github.com/apache/spark/pull/32144

I encountered with https://github.com/yaooqinn/spark/runs/2344156574?check_suite_focus=true

```
2s
Run apache_spark_ref=`git rev-parse HEAD`
  apache_spark_ref=`git rev-parse HEAD`
  git fetch https://github.com/$GITHUB_REPOSITORY.git ${GITHUB_REF##*/}
  git merge --progress --ff-only FETCH_HEAD
  echo "::set-output name=APACHE_SPARK_REF::$apache_spark_ref"
  shell: /usr/bin/bash -e {0}
  env:
    MODULES_TO_TEST: core, unsafe, kvstore, avro, network-common, network-shuffle, repl, launcher, examples, sketch, graphx
    EXCLUDED_TAGS: 
    INCLUDED_TAGS: 
    HADOOP_PROFILE: hadoop3.2
    HIVE_PROFILE: hive2.3
    CONDA_PREFIX: /usr/share/miniconda
    GITHUB_PREV_SHA: a3a6c5e8401b6af21c329d71928a353432142349
    SPARK_LOCAL_IP: localhost
From https://github.com/yaooqinn/spark
 * branch                  SPARK-35044 -> FETCH_HEAD
fatal: Not possible to fast-forward, aborting.
Error: Process completed with exit code 128.
```

### CODE REVIEW

**Comment by yaooqinn** [comment]
```
Run apache_spark_ref=`git rev-parse HEAD`
  apache_spark_ref=`git rev-parse HEAD`
  git fetch https://github.com/$GITHUB_REPOSITORY.git ${GITHUB_REF##*/}
  git merge --progress --ff-only FETCH_HEAD
  echo "::set-output name=APACHE_SPARK_REF::$apache_spark_ref"
  shell: /usr/bin/bash -e {0}
  env:
    MODULES_TO_TEST: core, unsafe, kvstore, avro, network-common, network-shuffle, repl, launcher, examples, sketch, graphx
    EXCLUDED_TAGS: 
    INCLUDED_TAGS: 
    HADOOP_PROFILE: hadoop3.2
    HIVE_PROFILE: hive2.3
    CONDA_PREFIX: /usr/share/miniconda
    GITHUB_PREV_SHA: 0000000000000000000000000000000000000000
    SPARK_LOCAL_IP: localhost
From https://github.com/gengliangwang/spark
 * branch                  tryNewGA   -> FETCH_HEAD
Updating 2974b70d1e..9536df22cc
Fast-forward
 sql/core/src/test/scala/org/apache/spark/sql/SQLQuerySuite.scala | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
```

GITHUB_PREV_SHA: 0000000000000000000000000000000000000000 this looks weird but from a success build in @gengliangwang 's actions
GITHUB_PREV_SHA: a3a6c5e8401b6af21c329d71928a353432142349, this look correct but can not pass, I am not sure this is related

**Comment by Yikun** [comment]
I met same problem on the 1st error `fatal: Not possible to fast-forward, aborting.`, after some investagations, I found it is caused by `yaooqinn:SPARK-35044` is not synced with apache/spark master, when we use git fetch and git merge to sync code, will raise the fast forward error[1].

Looks like we need a `git rebase` [before fetch and merge](https://github.com/apache/spark/blob/f32114d17e1c022817a16c83f33138a1b8faa7c6/.github/workflows/build_and_test.yml#L188)?

[1] https://stackoverflow.com/questions/13106179/fatal-not-possible-to-fast-forward-aborting/43460847

**Comment by HyukjinKwon** [comment]
Maybe we should remove fast forward option

**Comment by HyukjinKwon** [comment]
@Yikun can you open a PR that removes the -ff option in the sync?  A bit of manual tests in your local is enough given that it breaks many PRs.

**Comment by HyukjinKwon** [comment]
github conflict detection is less strict to `git rebase` given my experience. If we can manage it without `-ff` option, that would be great. If that's difficult, we can do rebase for the time being.

**Comment by Yikun** [comment]
can you open a PR that removes the -ff option in the sync?

@HyukjinKwon

**Comment by HyukjinKwon** [comment]
Yeah, I can :-). I wanted to keep the credits of the investigation made here.

**Comment by HyukjinKwon** [comment]
Thanks @Yikun! I sent a couple of emails related to this in private :-).

**Pull request closed without merging**
