### PR TITLE
SPARK-9210 corrects aggregate function name in exception message

### PR DESCRIPTION
**Pull request by ssimeonov**
[JIRA issue](https://issues.apache.org/jira/browse/SPARK-9210)

### CODE REVIEW

**Comment by srowen** [comment]
CC @marmbrus just in case

**Comment by marmbrus** [comment]
I don't think this is correct: https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala#L147

```scala
scala> sql("SELECT a FROM test GROUP BY b")
org.apache.spark.sql.AnalysisException: expression 'a' is neither present in the group by, nor is it an aggregate function. Add to group by or wrap in first() if you don't care which value you get.;

scala> sql("SELECT first(a) FROM test GROUP BY b")
res3: org.apache.spark.sql.DataFrame = [_c0: int]
```

**Comment by ssimeonov** [comment]
@marmbrus can you please provide a complete example that can execute in `spark-shell`?

You can find a standalone runnable example with complete shell output in [this gist](https://gist.github.com/ssimeonov/72c8a9b01f99e35ba470). Here is the summary of what happens:

```scala
// ERROR RetryingHMSHandler: MetaException(message:NoSuchObjectException(message:Function default.first does not exist))
// INFO FunctionRegistry: Unable to lookup UDF in metastore: org.apache.hadoop.hive.ql.metadata.HiveException: MetaException(message:NoSuchObjectException(message:Function default.first does not exist))
// java.lang.RuntimeException: Couldn't find function first
ctx.sql("select first(num) from test_first group by category").show

// OK
ctx.sql("select first_value(num) from test_first group by category").show
```

Perhaps the difference is that I'm using `HiveContext`?

**Comment by marmbrus** [comment]
Which version of hive/spark are you running?

**Comment by ssimeonov** [comment]
@marmbrus you can see the version and full INFO-level shell output in the gist. I'm running 1.4.1.

**Comment by rxin** [comment]
cc @yhuai since you are working on a related issue.

**Comment by yhuai** [comment]
In Spark 1.4, `first` and `last` were not in function registry. Right now, `first_value` and `last_value` are pointing to Hive's `first_value` and `last_value`, respectively. I am adding these to our function registry as well in https://github.com/apache/spark/pull/8113. @ssimeonov I will update the exception message in #8113.

**Comment by ssimeonov** [comment]
@yhual great

**Comment by JoshRosen** [comment]
Hey @ssimeonov, would you mind closing this PR now that it's change has been incorporated into #8113? Thanks!

**Pull request closed without merging**
