### PR TITLE
[SPARK-8451][SPARK-7287] SparkSubmitSuite should check exit code

### PR DESCRIPTION
**Pull request by andrewor14**
This patch also reenables the tests. Now that we have access to the log4j logs it should be easier to debug the flakiness.

@yhuai @brkyvz

### CODE REVIEW

**Comment by yhuai** [comment]
lgtm

**Comment by andrewor14** [comment]
Ok, I have triggered a bunch of builds for this patch to test the flakiness. We'll see how things go.

**Comment by andrewor14** [comment]
retest this please

**Comment by andrewor14** [comment]
None of the failed tests are `SparkSubmitSuite`. I'm going to merge this.

**Pull request closed without merging**
