### PR TITLE
[SPARK-14387][SQL] Enable Hive-1.x ORC compatibility with spark.sql.hive.convertMetastoreOrc

### PR DESCRIPTION
**Pull request by rajeshbalamohan**
## What changes were proposed in this pull request?

This PR improves ORCFileFormat to handle cases when schema stored in the ORC file does not match the schema stored in metastore. 

ORC Data written by Hive-1.x had virtual column names (HIVE-4243). This is fixed in Hive-2.x, but for data stored using Hive-1.x spark would throw exceptions. To mitigate this, "spark.sql.hve.convertMetastoreOrc" was disabled via SPARK-15705.  However, that would incur
performance penalties as it would go via HiveTableScan and HadoopRDD.  This PR fixes this issue.

Related tickets:
SPARK-15705 : Change the default value of spark.sql.hive.convertMetastoreOrc to false.
SPARK-15705 : Spark won't read ORC schema from metastore for partitioned tables
SPARK-16628 : OrcConversions should not convert an ORC table represented by MetastoreRelation to HadoopFsRelation if metastore schema does not match schema stored in ORC files
## How was this patch tested?

Manual testing by setting "spark.sql.hve.convertMetastoreOrc=true" and querying data stored via Hive-1.x in ORC format. Also ran unit-tests related to sql.

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by rajeshbalamohan** [comment]
Fixed scalastyle issues

**Comment by rxin** [comment]
Can you add a test case?

**Comment by rxin** [comment]
also can you update the title? The current title is very generic. This ticket seems to be solving a specific problem.

**Comment by rajeshbalamohan** [comment]
Thanks @rxin.

Changes:
1. Added test case. Also added sample orc file (392 bytes) from Hive 1.x with format "Type: struct<_col0:int,_col1:string>".   Without this PR change in OrcFileFormat, it would end up throwing "java.lang.IllegalArgumentException: Field "key" does not exist." for the same test case.

2. Fixed the title of the JIRA and the PR.

**Comment by JoshRosen** [comment]
Jenkins, retest this please.

**Comment by dongjoon-hyun** [comment]
Hi, @rajeshbalamohan . I'll refer your commit for SPARK-19459 . You'll be the main author in case of merge.

**Comment by dongjoon-hyun** [comment]
Hi, @rajeshbalamohan .
SPARK-14387 is resolved now. Could you close this PR?

**Pull request closed without merging**
