### PR TITLE
[SPARK-44972][INFRA] Eagerly check if the token is valid to align with the behavior of username/password auth

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

The SPARK-44802 now allows for token authentication when resolving Jira issues in pull request merging. However, the token auth is kinda lazy during the initial handshake, maintainers might get confused someday.

This pull request promptly calls the current_user() function to initiate authentication and provides clear instructions for token expiration.

### Why are the changes needed?

make it easy for maintainers to update their expired Jira tokens.

### Does this PR introduce _any_ user-facing change?

no, for maintainers

### How was this patch tested?

locally verified the code snippet

### Was this patch authored or co-authored using generative AI tooling?

no

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
I created a new JIRA issue because this is worth, @yaooqinn .

**Review by dongjoon-hyun — COMMENTED** [review]
@yaooqinn . I love this feature and completely migrated to this one auth way. If you don't mind, may I propose do this check more early in order to be really `# Eagerly check if the token is valid`? Shall we check at the beginning of the script?

**Comment by yaooqinn** [comment]
Thanks @dongjoon-hyun for the new jira ticket and suggestions

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you for update.

**Comment by dongjoon-hyun** [comment]
I tested and merged this PR with this script.

**Comment by yaooqinn** [comment]
Thanks, @dongjoon-hyun

**Pull request closed without merging**
