### PR TITLE
[SPARK-19617][SS]fix structured streaming restart bug

### PR DESCRIPTION
**Pull request by gf53520**
## What changes were proposed in this pull request?
[SPARK-19617](https://issues.apache.org/jira/browse/SPARK-19645)
    When restart a structured streaming  job, spark will recompute WAL offsets and generate the same hdfs delta file named "currentBatchId.delta" and also generated before job restart .

## How was this patch tested?
   manual tests

### CODE REVIEW

**Comment by gf53520** [comment]
cc @zsxwing

**Comment by gf53520** [comment]
test this please

**Comment by uncleGen** [comment]
retest this please.

**Comment by uncleGen** [comment]
The JIRA ID is not SPARK-19645?

**Comment by zsxwing** [comment]
@gf53520 SPARK-19617 is a different issue. I guess you meant SPARK-19645. Thanks a lot for doing this. However, I merged #17012 as the approach is better and it has a unit test to cover this issue. Could you close this one please?

**Comment by gf53520** [comment]
@zsxwing no problem, But I think that PR exists an small problem that a tmp file of delta file is still reserved in hdfs.

**Comment by zsxwing** [comment]
Good catch. Could you submit a follow up PR to fix it?

**Comment by gf53520** [comment]
@zsxwing  okay,  I will submit a PR to fix it.

**Pull request closed without merging**
