### PR TITLE
[SPARK-26224][SQL][PYTHON][R][FOLLOW-UP] Add notes about many projects in withColumn at SparkR and PySpark as well

### PR DESCRIPTION
**Pull request by HyukjinKwon**
## What changes were proposed in this pull request?

This is a followup of https://github.com/apache/spark/pull/23285. This PR adds the notes into PySpark and SparkR documentation as well.

While I am here, I revised the doc a bit to make it sound a bit more neutral

## How was this patch tested?

Manually built the doc and verified.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @cloud-fan and @mgaido91

**Review by felixcheung — APPROVED** [review]
LGTM. is this also applicable to `withColumnRenamed`?

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
I haven't checked that closely. The reported case was a usecase making sense but I am not sure with `withColumnRenamed` ... Hope we can handle that differently later.

**Comment by mgaido91** [comment]
LGTM, thanks @HyukjinKwon . I don't think `withColumnRenamed` is used by users in big for loops as I have seen for `withColumn`, so I think it is fine not to handle it. Thanks.

**Comment by HyukjinKwon** [comment]
retest this please

**Review by srowen — APPROVED** [review]

**Review by viirya — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Thanks, @felixcheung, @mgaido91, @srowen and @viirya.

Merged to master.

**Pull request closed without merging**
