### PR TITLE
Branch 1.4

### PR DESCRIPTION
**Pull request by GuoNing89**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)
## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by srowen** [comment]
Close this PR @GuoNing89

**Comment by vanzin** [comment]
@GuoNing89  please close this PR.

**Comment by nchammas** [comment]
@srowen @vanzin - Shouldn't some automated process be picking up your comments ("close this PR") and closing this PR? I thought we had something like that.

**Comment by srowen** [comment]
@nchammas Yeah the script or process for that disappeared .. but all it would do is push an empty commit with "closes xxx" in its message. I can do that manually without much work. One moment ...

**Pull request closed without merging**
