### PR TITLE
[SPARK-29932][R][TESTS] lint-r should do non-zero exit in case of errors

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to make `lint-r` exits with non-zero in case of errors. Please note that `lint-r` works correctly when everything are installed correctly.

### Why are the changes needed?

There are two cases which hide errors from Jenkins/AppVeyor/GitHubAction.
1. `lint-r` exits with zero if there is no R installation. 
```bash
$ dev/lint-r
dev/lint-r: line 25: type: Rscript: not found
ERROR: You should install R
$ echo $?
0
```

2. `lint-r` exits with zero if we didn't do `R/install-dev.sh`.
```bash
$ dev/lint-r
Error: You should install SparkR in a local directory with `R/install-dev.sh`.
In addition: Warning message:
In library(SparkR, lib.loc = LOCAL_LIB_LOC, logical.return = TRUE) :
  no library trees found in 'lib.loc'
Execution halted
lintr checks passed.        // <=== Please note here
$ echo $?
0
```

### Does this PR introduce any user-facing change?

No.

### How was this patch tested?

Manually check the above two cases.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Hi, @HyukjinKwon .
Could you review this please?

**Review by srowen — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you for review and approval, @srowen .
Merged to master/2.4.

**Review by HyukjinKwon — COMMENTED** [review]
LGTM too

**Comment by gatorsmile** [comment]
BTW, all the lint check failed since this PR. Any plan to fix it?

**Comment by gatorsmile** [comment]
https://amplab.cs.berkeley.edu/jenkins/view/Spark%20QA%20Compile/job/spark-master-lint/

**Comment by gatorsmile** [comment]
cc @dongjoon-hyun @srowen @HyukjinKwon

**Comment by dongjoon-hyun** [comment]
@gatorsmile . It's Jenkin issue. Please see the log.

**Comment by dongjoon-hyun** [comment]
Please see GitHub Action instead. We add `lint-r` to there. 
- https://github.com/apache/spark/commits/master

**Comment by dongjoon-hyun** [comment]
GitHub Action can work well for this kind of short jobs. We can have a commit-by-commit log from now. `AmbLab Jenkins` doesn't.

We migrated all `Spark QA Compile` dashboard. `lint-r` was the last piece. We will delete the dashboard via https://issues.apache.org/jira/browse/SPARK-29935 .

PG&E cannot touch `GitHub Action` . 😄 
And, everyone can fix `GitHub Action` promptly if something goes wrong. (For Jenkins, we couldn't)

**Pull request closed without merging**
