### PR TITLE
[SPARK-26255][YARN] Apply user provided UI filters  to SQL tab in yarn mode

### PR DESCRIPTION
**Pull request by chakravarthiT**
## What changes were proposed in this pull request?

User specified filters are not applied to SQL tab in yarn mode, as it is overridden by the yarn AmIp filter.
So we need to append user provided filters (spark.ui.filters) with yarn filter.

## How was this patch tested?

【Test step】：

1)  Launch spark sql with authentication filter as below:

2)  spark-sql --master yarn --conf spark.ui.filters=org.apache.hadoop.security.authentication.server.AuthenticationFilter --conf spark.org.apache.hadoop.security.authentication.server.AuthenticationFilter.params="type=simple"

3)  Go to Yarn application list UI link

4) Launch the application master for the Spark-SQL app ID and access all the tabs by appending tab name.

5) It will display an error for all tabs including SQL tab.(before able to access SQL tab,as Authentication filter is not applied for SQL tab)

6) Also can be verified with info logs,that Authentication filter applied to SQL tab.(before it is not applied).

I have attached the behaviour below in following order..

1) Command used
2) Before fix (logs and UI)
3) After fix (logs and UI)

**1) COMMAND USED**:

launching spark-sql with authentication filter.

image

**2) BEFORE FIX:**

**UI result:**
able to access SQL tab.

image

 **logs**:
authentication filter not applied to SQL tab.

image

**3) AFTER FIX:**

**UI result**:

Not able to access SQL tab.

image

**in logs**:

Both yarn filter and Authentication filter applied to SQL tab.

image

### CODE REVIEW

**Comment by chakravarthiT** [comment]
@vanzin @andrewor14 please review

**Comment by vanzin** [comment]
ok to test

**Comment by vanzin** [comment]
BTW I'm not sure what the PR title is saying. Please use it to describe the fix instead.

**Comment by chakravarthiT** [comment]
@vanzin  , updated the title. please review

**Comment by vanzin** [comment]
Merging to master.

**Pull request closed without merging**
