### PR TITLE
[SPARK-31584][WebUI] Fix NullPointerException when parsing event log with InMemoryStore

### PR DESCRIPTION
**Pull request by baohe-zhang**
### What changes were proposed in this pull request?
https://github.com/apache/spark/pull/27716 introduced parent index for InMemoryStore. When the method "deleteParentIndex(Object key)" in InMemoryStore.java is called and the key is not contained in "NaturalKeys v",  A java.lang.NullPointerException will be thrown. This patch fixed the issue by updating the if condition.

### Why are the changes needed?
Fixed a minor bug.

### Does this PR introduce any user-facing change?
No.

### How was this patch tested?
Added a unit test for deleteParentIndex.

### CODE REVIEW

**Review by HeartSaVioR — COMMENTED** [review]
The change looks good to me. It'd be ideal if we can add UT for this to prevent regression - there's InMemoryStoreSuite storing UTs for InMemoryStore.

**Comment by HeartSaVioR** [comment]
cc. @gengliangwang

**Comment by gengliangwang** [comment]
@baohe-zhang Thanks for the fix! 
Could you follow @HeartSaVioR 's to add unit tests?

**Comment by baohe-zhang** [comment]
@gengliangwang sure, I will add unit tests.

**Comment by baohe-zhang** [comment]
@HeartSaVioR @gengliangwang The UT is added. InMemoryStoreSuite.java :249 would throw a NullPointerException if we don't have this fix.

**Comment by gengliangwang** [comment]
ok to test

**Comment by redsanket** [comment]
ok to test

**Review by gengliangwang — APPROVED** [review]
LGTM

**Review by HeartSaVioR — APPROVED** [review]
LGTM. Thanks for the contribution!

**Comment by gengliangwang** [comment]
Thanks, merging to master/3.0

**Pull request closed without merging**
