### PR TITLE
[MINOR][BUILD] Fix Java Linter `LineLength` errors

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
## What changes were proposed in this pull request?

This PR fixes four java linter `LineLength` errors. Those are all `LineLength` errors, but we had better remove all java linter errors before release.
## How was this patch tested?

After pass the Jenkins, `./dev/lint-java`.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Rebased to resolve conflicts.

**Comment by dongjoon-hyun** [comment]
For easy comparison, `lint-java` results are here.

- https://travis-ci.org/dongjoon-hyun/spark/jobs/145738728 (Current master: [SPARK-16303][DOCS][EXAMPLES] ...)
- https://travis-ci.org/dongjoon-hyun/spark/jobs/145738812  (This PR)

**Comment by srowen** [comment]
OK

**Comment by dongjoon-hyun** [comment]
Thank you for review, @srowen !

**Comment by srowen** [comment]
Merged to master, and to 2.0 to make sure the lint errors are gone for release

**Comment by dongjoon-hyun** [comment]
Thank you for merging!

**Pull request closed without merging**
