### PR TITLE
[SPARK-50145][BUILD] Upgrade Jetty to 11.0.24

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to upgrade `Jetty` to 11.0.24 for Apache Spark 4.0.0.

### Why are the changes needed?

To bring the latest bug fixes like the following.
- https://github.com/jetty/jetty.project/pull/12201

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the CIs.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Oops. I forget that we did this before. Let me close this PR.

**Comment by dongjoon-hyun** [comment]
Could you review this PR, @LuciferYang ?

**Comment by dongjoon-hyun** [comment]
The CI is running here.
- https://github.com/dongjoon-hyun/spark/actions/runs/11548078997

**Review by yaooqinn — APPROVED** [review]

**Review by LuciferYang — APPROVED** [review]

**Comment by LuciferYang** [comment]
@dongjoon-hyun a failed test case in k8s it. Shall we retrigger it?

```
[info] - A Spark job with two executors with OnDemand PVC volumes *** FAILED *** (24 seconds, 931 milliseconds)
[info]   The code passed to eventually never returned normally. Attempted 2 times over 11.106691292999999 seconds. Last failure message: An error has occurred.. (VolumeSuite.scala:32)
[info]   org.scalatest.exceptions.TestFailedDueToTimeoutException:
[info]   at org.scalatest.enablers.Retrying$$anon$4.tryTryAgain$2(Retrying.scala:219)
[info]   at org.scalatest.enablers.Retrying$$anon$4.retry(Retrying.scala:226)
[info]   at org.scalatest.concurrent.Eventually.eventually(Eventually.scala:313)
[info]   at org.scalatest.concurrent.Eventually.eventually$(Eventually.scala:312)
[info]   at org.apache.spark.deploy.k8s.integrationtest.KubernetesSuite.eventually(KubernetesSuite.scala:45)
[info]   at org.apache.spark.deploy.k8s.integrationtest.VolumeSuite.checkDisk(VolumeSuite.scala:32)
[info]   at org.apache.spark.deploy.k8s.integrationtest.VolumeSuite.$anonfun$$init$$24(VolumeSuite.scala:169)
[info]   at org.apache.spark.deploy.k8s.integrationtest.VolumeSuite.$anonfun$$init$$24$adapted(VolumeSuite.scala:167)
[info]   at org.apache.spark.deploy.k8s.integrationtest.KubernetesSuite.$anonfun$runSparkApplicationAndVerifyCompletion$12(KubernetesSuite.scala:488)
[info]   at org.apache.spark.deploy.k8s.integrationtest.KubernetesSuite.$anonfun$runSparkApplicationAndVerifyCompletion$12$adapted(KubernetesSuite.scala:488)
[info]   at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:619)
[info]   at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:617)
[info]   at scala.collection.AbstractIterable.foreach(Iterable.scala:935)
[info]   at org.apache.spark.deploy.k8s.integrationtest.KubernetesSuite.runSparkApplicationAndVerifyCompletion(KubernetesSuite.scala:488)
[info]   at org.apache.spark.deploy.k8s.integrationtest.VolumeSuite.$anonfun$$init$$22(VolumeSuite.scala:160)
```

**Comment by dongjoon-hyun** [comment]
Thank you, @yaooqinn and @LuciferYang .

To @LuciferYang , sure. I re-triggered it.

**Comment by dongjoon-hyun** [comment]
All tests passed. Merged to master for Apache Spark 4.0.0 on February 2025.

**Pull request closed without merging**
