### PR TITLE
[SPARK-9864] [DOC] [MLlib] [SQL] Replace since in scaladoc to Since annotation

### PR DESCRIPTION
**Pull request by MechCoder**

### CODE REVIEW

**Comment by MechCoder** [comment]
@mengxr @rxin 

I wrote a small bash script to automate this to an extent (i.e for every file). (https://gist.github.com/MechCoder/fdc77f62050f2f698484) However it fails for some corner cases like badly formatted docs and I am not sure we would be needing this again, so I did not automate it fully.

**Comment by mengxr** [comment]
@MechCoder Could you move the changes in SQL to another PR? I think SQL is fine with `@since` tag. Switching to `@Since` will cause regression in the generated Java API doc. Let's experiment with `@Since` annotation in MLlib first:)

**Comment by MechCoder** [comment]
rebased

**Comment by mengxr** [comment]
I checked all changes and they LGTM:) Thanks for fixing the styles too! Merged into master and branch-1.5. Could you have another PR to add `Since` to constructor params (if they are public)?

**Comment by MechCoder** [comment]
thanks for the merge. I will not be available till Monday itself :( . If this is in a hurry, please feel free to fix it yourself.

**Pull request closed without merging**
