### PR TITLE
[SPARK-47435][SQL] Fix overflow issue of MySQL UNSIGNED TINYINT  caused by SPARK-45561

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

SPARK-45561 mapped java.sql.Types.TINYINT to ByteType in MySQL Dialect, which caused unsigned TINYINT overflow. As regardless of signed or unsigned types, the TINYINT is used for java.sql.Types.

In this PR, we put the signed info into the metadata for mapping TINYINT to short or byte.

### Why are the changes needed?

bugfix

### Does this PR introduce _any_ user-facing change?

Uses can read MySQL UNSIGNED TINYINT values after this PR like versions before 3.5.0 which has breaked since 3.5.1

### How was this patch tested?

new tests

### Was this patch authored or co-authored using generative AI tooling?
no

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
Oh, is this a regression at Apache Spark 3.5.1? Thanks, @yaooqinn .

cc @michaelzhan-db, @MaxGekk , @beliefer,  @cloud-fan, too

**Comment by yaooqinn** [comment]
Thank you @dongjoon-hyun. Yes, this is a 3.5.1 regression.

**Review by cloud-fan — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Merged to master.

Could you make a backporting PR, @yaooqinn ?

**Comment by dongjoon-hyun** [comment]
Thank you, @yaooqinn and @cloud-fan .

**Comment by yaooqinn** [comment]
Thank you, @dongjoon-hyun and @cloud-fan . I will make a backport

**Pull request closed without merging**
