### PR TITLE
[SPARK-20232][Python] Improve combineByKey docs

### PR DESCRIPTION
**Pull request by dgingrich**
## What changes were proposed in this pull request?

Improve combineByKey documentation:

* Add note on memory allocation
* Change example code to use different mergeValue and mergeCombiners

## How was this patch tested?

Doctest.

## Legal

This is my original work and I license the work to the project under the project’s open source license.

### CODE REVIEW

**Comment by holdenk** [comment]
So the associated JIRA says "Doesn't include note about memory allocation (on aggregateBykey)" - what did you want to add in `aggregateBykey`?

**Comment by dgingrich** [comment]
The note meant that `combineByKey` doesn't include the comment about memory allocation that's on `aggregateByKey`.  I did add the memory allocation note to `combineByKey`, starting on line 1810.

**Comment by holdenk** [comment]
Ok sounds good, I just wanted to make sure since the JIRA had it in two separate bullet points and I wasn't sure if it was a second thing you wanted to talk about.

LGTM.

**Comment by holdenk** [comment]
Merged to master, thanks for working on this @dgingrich

**Pull request closed without merging**
