### PR TITLE
[SPARK-40887][K8S] Make `SPARK_DRIVER_LOG_URL_` and `SPARK_DRIVER_ATTRIBUTE_` work for Spark on K8S

### PR DESCRIPTION
**Pull request by turboFei**
### What changes were proposed in this pull request?

As title, Make `SPARK_DRIVER_LOG_URL_` and `SPARK_DRIVER_ATTRIBUTE_` works for Spark on K8S.
### Why are the changes needed?

Now seems `SPARK_DRIVER_LOG_URL_` and `SPARK_DRIVER_ATTRIBUTE_` only work for yarn cluster mode.

We need to make it works for Spark on K8s.

### Does this PR introduce _any_ user-facing change?

Yes, `SPARK_DRIVER_LOG_URL_` and `SPARK_DRIVER_ATTRIBUTE_` works for Spark on K8S after this PR.

### How was this patch tested?

Existing UT.

### CODE REVIEW

**Comment by pan3793** [comment]
Please follow the https://spark.apache.org/contributing.html to

> Go to “Actions” tab on your forked repository and enable “Build and test” and “Report test results” workflows

**Comment by turboFei** [comment]
Gentle ping @dongjoon-hyun

**Comment by turboFei** [comment]
gentle ping @holdenk

**Review by yaooqinn — CHANGES_REQUESTED** [review]
> Now seems SPARK_DRIVER_LOG_URL_ and SPARK_DRIVER_ATTRIBUTE_ only work for yarn cluster mode.

these are for standalone now?


> Make SPARK_DRIVER_LOG_URL_ and SPARK_DRIVER_ATTRIBUTE_ work for Spark on K8S

Doesn't this change affect other schedulers?


> SPARK_DRIVER_LOG_URL_ and SPARK_DRIVER_ATTRIBUTE_ works for Spark on K8S after this PR. & Existing UT.

Don't we need extra UTs for K8s coverages?


PS, I notice that you have changed the code read path, but I don't see the write path? How can we make it work?

**Comment by turboFei** [comment]
thanks for the comments, I will check it.

**Pull request closed without merging**
