### PR TITLE
[SPARK-43256][SQL] Remove error class _LEGACY_ERROR_TEMP_2021

### PR DESCRIPTION
**Pull request by andrej-db**
### What changes were proposed in this pull request?

In the PR, I propose to remove the legacy error class `_LEGACY_ERROR_TEMP_2021` as it is an internal error.
### Why are the changes needed?

User experience improvement w/ Spark SQL.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Tests already exist.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Review by MaxGekk — COMMENTED** [review]
@andrej-db Could you enable GitHub actions in your fork to run builds and tests.

**Review by MaxGekk — COMMENTED** [review]
Can you reproduce the error using public API? if so, please, add a test to `QueryExecutionErrorsSuite` otherwise we should consider to convert the error to an internal one.

**Comment by andrej-db** [comment]
> @andrej-db Could you enable GitHub actions in your fork to run builds and tests.

Done.

**Comment by andrej-db** [comment]
> Can you reproduce the error using public API? if so, please, add a test to `QueryExecutionErrorsSuite` otherwise we should consider to convert the error to an internal one.

Checking...

**Comment by MaxGekk** [comment]
@cloud-fan @hvanhovell We are struggling to reproduce the error. Any ideas how to raise the exception using public API?
https://github.com/apache/spark/blob/c2079b9b13e4884a22c9df4f17520fb5b63cc6bc/sql/api/src/main/scala/org/apache/spark/sql/catalyst/ScalaReflection.scala#L500-L504
Asking you because you had been modifying the code.

**Comment by cloud-fan** [comment]
this seems like an internal error as a scala class must have a primary constructor

**Review by MaxGekk — APPROVED** [review]

**Comment by MaxGekk** [comment]
Waiting for CI.

**Comment by MaxGekk** [comment]
The failed tests are not related to the changes.

+1, LGTM. Merging to master.
Thank you, @andrej-db.

**Comment by MaxGekk** [comment]
@andrej-db Congratulations with your first contribution to Apache Spark!

**Pull request closed without merging**
