### PR TITLE
[SPARK-40941][K8S] Use Java 17 in K8s Dockerfile by default and remove `Dockerfile.java17`

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to use `Java 17` in K8s Dockerfile by default and remove `Dockerfile.java17`.

### Why are the changes needed?

To update for Apache Spark 3.4.0.

```
$ docker run -it --rm kubespark/spark:dev cat /etc/os-release | grep PRETTY
PRETTY_NAME="Ubuntu 22.04.1 LTS"
```

```
$ docker run -it --rm kubespark/spark:dev java -version | grep 64
OpenJDK 64-Bit Server VM Temurin-17.0.4.1+1 (build 17.0.4.1+1, mixed mode, sharing)
```

### Does this PR introduce _any_ user-facing change?

Yes, but only the published docker images will get the latest OS (Ubuntu 22.04.1 LTS) and Java (17 LTS).

### How was this patch tested?

Pass the CIs.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
cc @Yikun

**Comment by dongjoon-hyun** [comment]
Could you review this, @viirya ?

**Review by viirya — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you so much, @viirya . Merged to master for Apache Spark 3.4.

**Comment by Yikun** [comment]
Thanks, late LGTM.

**Comment by dongjoon-hyun** [comment]
Thank you, @Yikun .

**Pull request closed without merging**
