### PR TITLE
[SPARK-49142][CONNECT][PYTHON] Lower Spark Connect client log level to debug

### PR DESCRIPTION
**Pull request by nija-at**
### What changes were proposed in this pull request?

Spark Connect client produces a fair amount of logs but is incorrectly
configured at INFO level. When clients set the global log level to INFO,
a lot of debug level logs are produced.

### Why are the changes needed?

Since we're using the Python logging utility, it's possible for clients and
even other libraries to set the target log level.
When this occurs, a lot of spurious debug log messages are emitted
by the Spark Connect client.

### Does this PR introduce _any_ user-facing change?

Yes. Spark Connect client logs level will now be produced at debug level
and not info level.

### How was this patch tested?

Manually by changing the log levels to see that the messages are emitted
at the right level.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
would be great if we file a JIRA though.

**Review by allisonwang-db — APPROVED** [review]
Not blocking this PR but shall we use the new pyspark logger introduced by @itholic in the future?

**Comment by HyukjinKwon** [comment]
That's actually a good point. @itholic can we replace them all?

**Comment by HyukjinKwon** [comment]
Let me merge this first as we haven't finished swtiching the loggers yer IIUC?

Let's followup @itholic

**Comment by oliverbeagley-pgg** [comment]
Sorry, I'm a random bystander who occasionally skims the commit log for new things in spark and wanders down the rabbit hole, but I've noticed that this has effectively reversed https://github.com/apache/spark/pull/47289, likely incurring the performance hit again. 

For the logs calling `self._proto_to_string` should this not be something like the following?

```py
if logger.isEnabledFor(logging.DEBUG):
    logger.debug("<msg>")
```

**Comment by nija-at** [comment]
You are indeed correct @oliverbeagley-pgg. I assumed incorrectly removing if-statement would clean up the code. 
I will have a follow up PR to fix this up.

**Comment by nija-at** [comment]
I have a PR that fixes this: https://github.com/apache/spark/pull/47667

**Comment by itholic** [comment]
> Let me merge this first as we haven't finished swtiching the loggers yer IIUC?
> 
> Let's followup @itholic

Sorry I missed pings for me here. Will submit a follow-up

**Pull request closed without merging**
