### PR TITLE
[SPARK-24865][SQL] Remove AnalysisBarrier addendum

### PR DESCRIPTION
**Pull request by rxin**
## What changes were proposed in this pull request?
I didn't want to pollute the diff in the previous PR and left some TODOs. This is a follow-up to address those TODOs.

## How was this patch tested?
Should be covered by existing tests.

### CODE REVIEW

**Comment by rxin** [comment]
cc @gatorsmile @cloud-fan

**Review by gatorsmile — COMMENTED** [review]
LGTM

**Comment by gatorsmile** [comment]
retest this please

**Comment by cloud-fan** [comment]
we also need to replace `planWithBarrier` with `logicalPlan` at `Dataset.scala:1960`

**Comment by gatorsmile** [comment]
retest this please

**Comment by gatorsmile** [comment]
retest this please

**Comment by cloud-fan** [comment]
retest this please

**Comment by gatorsmile** [comment]
retest this please

**Comment by gatorsmile** [comment]
streaming tests are very flacky.

**Comment by gatorsmile** [comment]
Thanks! Merged to master.

**Pull request closed without merging**
