### PR TITLE
[SPARK-28342][SQL][TESTS] Replace REL_12_BETA1 to REL_12_BETA2 in PostgresSQL SQL tests

### PR DESCRIPTION
**Pull request by HyukjinKwon**
## What changes were proposed in this pull request?

This PR proposes to replace `REL_12_BETA1` to `REL_12_BETA2` which is latest.

## How was this patch tested?

Manually checked each link and checked via `git grep -r REL_12_BETA1` as well.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
@dongjoon-hyun, seems actually there's no diff to make in Spark SQL files. I was referring this diff https://github.com/postgres/postgres/commit/44e95b5728a4569c494fa4ea4317f8a2f50a206b but that's not in Spark yet ..

**Comment by HyukjinKwon** [comment]
cc @wangyum too

**Comment by dongjoon-hyun** [comment]
Cool! Thank you for confirming. It cleans up my mind. :)

**Comment by wangyum** [comment]
Thank you @HyukjinKwon

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. (I checked f90660a537ea63ff4aa7ca49fc2cf3947bd8d9aa).

Now, there is no remaining `REL_12_BETA1`.
Merged to master (since these are all comments and output files are unchanged.)

**Comment by HyukjinKwon** [comment]
Thank you guys!

**Pull request closed without merging**
