### PR TITLE
[SPARK-5057]Add more details in log when using actor to get infos

### PR DESCRIPTION
**Pull request by WangTaoTheTonic**
https://issues.apache.org/jira/browse/SPARK-5057

### CODE REVIEW

**Comment by ash211** [comment]
Matches error message from 20 lines up, so LGTM

**Comment by JoshRosen** [comment]
I suppose it'd be nice to use string interpolation here, but I guess the old code didn't use it either, so this matches the surrounding style

**Comment by WangTaoTheTonic** [comment]
Jenkins, test this please.

**Comment by WangTaoTheTonic** [comment]
@JoshRosen I also think it's better to use string interpolation. In this class some places use interpolation while others don't. So I changed those who don't to keep consistent.

**Comment by WangTaoTheTonic** [comment]
@JoshRosen  Then is it ok?

**Comment by JoshRosen** [comment]
LGTM, so I'll pull this into `master` (1.3.0).

**Pull request closed without merging**
