### PR TITLE
[SPARK-7718] [SQL] Speed up partitioning by avoiding closure cleaning

### PR DESCRIPTION
**Pull request by andrewor14**
According to @yhuai we spent 6-7 seconds cleaning closures in a partitioning job that takes 12 seconds. Since we provide these closures in Spark we know for sure they are serializable, so we can bypass the cleaning.

### CODE REVIEW

**Comment by andrewor14** [comment]
Also cc/ @pwendell

**Comment by andrewor14** [comment]
@yhuai can you try this and see if you can notice the speedup? (Does the closure get serialized correctly?)

**Comment by liancheng** [comment]
@andrewor14 I can do a local microbenchmark for this.

**Comment by liancheng** [comment]
Used the same micro benchmark configuration and code in #6225. Removing the `clean()` call does help, and leads to a ~6% performance gain.

(Not able to upload `jvisualvm` screenshots right now, will fill them in later.)

**Comment by andrewor14** [comment]
Hm, 6% seems much lower than what I expected. Maybe it's not super worth it.

**Comment by andrewor14** [comment]
How many partitions are used in these benchmark? What did you run?

**Comment by yhuai** [comment]
@andrewor14 Cheng's test did not include my pr (#6252). I just tested this one and #6252. The compilation time is down from 12.6s to 8.3s. My test table has 5000 partitions.

**Comment by andrewor14** [comment]
I see. From @liancheng's PR description at #6225, the 6% speed up is from the `53s`, which is roughly `3.2s`. This is more or less consistent with what @yhuai observed after applying this patch to his PR, where the speed up is roughly `4.3s`.

In other words the real speed up is about 34%!

**Comment by andrewor14** [comment]
After some more offline discussion with @yhuai we decided to remove the unnecessary calls to `Utils.getCallSite` as well, which collectively took up to another `5s` in his `12.6s`. If we skip all of these calls for internal RDDs we may notice another significant speedup.

**Comment by yhuai** [comment]
LGTM. I am going to merge it to master and branch 1.4.

**Pull request closed without merging**
