### PR TITLE
[SPARK-42803][CORE][SQL][ML] Use getParameterCount function instead of getParameterTypes.length

### PR DESCRIPTION
**Pull request by NarekDW**
### What changes were proposed in this pull request?

Since jdk1.8 there is an additional function in reflection API `getParameterCount`, it is better to use that function instead of `getParameterTypes.length` because `getParameterTypes` function makes a copy of the parameter types array every invocation:
```java
    public Class<?>[] getParameterTypes() {
        return parameterTypes.clone();
    }
```
`getParameterCount` returns amount of parameters directly:
```java
    public int getParameterCount() { return parameterTypes.length; }
``` 

### Why are the changes needed?
To avoid redundant arrays creation.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
By existing unit tests

### CODE REVIEW

**Comment by LuciferYang** [comment]
I think we should file a jira to record this

**Comment by NarekDW** [comment]
> I think we should file a jira to tracking this

Done, pls check - https://issues.apache.org/jira/browse/SPARK-42803

**Comment by LuciferYang** [comment]
The pr title should be `[SPARK-42803][CORE][SQL][ML] Use ... `

**Review by srowen — APPROVED** [review]

**Comment by NarekDW** [comment]
> @NarekDW Are there any more similar cases?
> 
> cc @srowen FYI

@LuciferYang  no, these are all

**Review by LuciferYang — APPROVED** [review]

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
