### PR TITLE
[SPARK-16297][SQL] Fix mapping Microsoft SQLServer dialect

### PR DESCRIPTION
**Pull request by meknio**
Fix mapping of StringType to NVARCHAR(MAX)
Fix mapping of BooleanTypeto BIT

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
(I think it would be even nicer if this PR follows https://cwiki.apache.org/confluence/display/SPARK/Contributing+to+Spark)

**Comment by meknio** [comment]
the problem is if it is run with no fix throws an exception and causes the following error:
-"Cannot specify a column width on data type bit."

The problem stems from the fact that the "java.sql.types.BIT" type is mapped as BIT[n] that really must be mapped as BIT.
This concerns the type Boolean.

As for the type String with maximum length of characters it must be mapped as VARCHAR (MAX) instead of TEXT which is a type deprecated in SQLServer.

Here is the list of mappings for SQL Server:
https://msdn.microsoft.com/en-us/library/ms378878(v=sql.110).aspx

**Comment by meknio** [comment]
some updates about ?

**Comment by vanzin** [comment]
@meknio the description in you last comment should be in the first comment in the PR (so that it ends up in the git history).

ok to test

**Comment by srowen** [comment]
@meknio if you'll update as Marcelo says, I'll merge this. Change the description here to contain your comment at https://github.com/apache/spark/pull/13944#issuecomment-229395810

**Comment by vanzin** [comment]
This looks like a nice fix and seems like @meknio is missing in action, so I'll just fix the commit message myself.

Merging to master.

**Pull request closed without merging**
