### PR TITLE
Revert "[SPARK-24601][SPARK-27051][BACKPORT][CORE] Update to Jackson 2.9.8

### PR DESCRIPTION
**Pull request by gatorsmile**
## What changes were proposed in this pull request?

This reverts commit 6f394a20bf49f67b4d6329a1c25171c8024a2fae.

In general, we need to be very cautious about the Jackson upgrade in the patch releases, especially when this upgrade could break the existing behaviors of the external packages or data sources, and generate different results after the upgrade. The external packages and data sources need to change their source code to keep the original behaviors. The upgrade requires more discussions before releasing it, I think.

In the previous PR https://github.com/apache/spark/pull/22071, we added the following claim in our security doc:
> The Rest Submission Server and the MesosClusterDispatcher do not support authentication.  You should ensure that all network access to the REST API & MesosClusterDispatcher (port 6066 and 7077 respectively by default) are restricted to hosts that are trusted to submit jobs.

We need to understand whether this Jackson CVE applies to Spark. Before officially releasing it, we need more inputs from all of you. Currently, I would suggest to revert this upgrade from the upcoming 2.4.3 release, which is trying to fix the accidental default Scala version changes in pre-built artifacts. 

## How was this patch tested?

N/A

### CODE REVIEW

**Comment by wangyum** [comment]
retest this please

**Review by dongjoon-hyun — APPROVED** [review]
Yep. Although I merged that before, I agree the reverting in `branch-2.4`, too. I thought Spark 2.4.3 will be released on July.

+1, LGTM. Merged to branch-2.4 to unblock 2.4.3 in this week.

**Comment by srowen** [comment]
@gatorsmile this is all good but you're still saying this is related to `spark.master.rest.enabled` ; I don't see that it is? just want to make sure we aren't saying this in release notes or something, that there _isn't_ a problem if you disable this.

**Comment by gatorsmile** [comment]
updated. Thanks!

**Comment by aldettinger** [comment]
Hi guys,

  Sorry to comment a closed PR, but it seems so much related to [SPARK-27932](https://issues.apache.org/jira/browse/SPARK-27932) I opened few days ago.

  From what I read, updating the 2.3.x, 2.4.x branches to jackson-databind >= 2.9.8 is not an option.
Do you think there is any chance to upgrade jackson-databind to >= 2.8.11.3 or >= 2.7.9.5 then ?

Many thanks

**Comment by srowen** [comment]
The problem here was a behavior change introduced in 2.7.x, so I think we'd have the same issue in anything after 2.6.x

**Comment by aldettinger** [comment]
Thanks for feedback @srowen, I will comment in [SPARK-27932](https://issues.apache.org/jira/browse/SPARK-27932) that it seems hard to upgrade jackson-databind versions on spark 2.3.x/2.4.x branches.
At the end of the day, those jackson-databind CVEs will come with spark 3 onward.

**Pull request closed without merging**
