### PR TITLE
[SPARK-29079][INFRA] Enable GitHub Action on PR

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR enables GitHub Action on PRs.

### Why are the changes needed?

So far, we detect JDK11 compilation error after merging.
This PR aims to prevent JDK11 compilation error at PR stage.

### Does this PR introduce any user-facing change?

No.

### How was this patch tested?

Manual. See the GitHub Action on this PR.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
cc @srowen and @dbtsai

**Comment by dbtsai** [comment]
LGTM. Merged into master.

**Comment by dongjoon-hyun** [comment]
Thank you for review and merging, @dbtsai !

**Comment by dongjoon-hyun** [comment]
It seems working correctly on `master`.
I'll logically backport this to `branch-2.4`, too.

**Pull request closed without merging**
