### PR TITLE
[DO-NOT-MERGE] Investigate test failures related with SPARK-22395

### PR DESCRIPTION
**Pull request by HyukjinKwon**
## What changes were proposed in this pull request?

This PR is not for merging. There are unexpected and unreproducible test failures which happen in Jenkins. This PR targets to test and investigate it.

## How was this patch tested?

N/A

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
Will take a look bit by bit tomorrow.

**Comment by HyukjinKwon** [comment]
@ueshin and @BryanCutler, do you guys maybe remember / know if / why Pandas and PyArrow are only installed in Python 3 in Jenkins?

I was trying to check diff in Python2 and 3 as the tests looked passing in Python 2 and I suspected Python 3 specific issue, but seems tests related with both PyArrow and Pandas in Python 2 are actually being skipped. Just want to double check if you guys know already.

**Comment by HyukjinKwon** [comment]
Oh BTW, I was trying to check the issue https://github.com/apache/spark/pull/19607#issuecomment-342119675 from top to bottom.

**Comment by HyukjinKwon** [comment]
Will double check it by myself in any event.

**Comment by ueshin** [comment]
> @ueshin and @BryanCutler, do you guys maybe remember / know if / why Pandas and PyArrow are only installed in Python 3 in Jenkins?

I'm afraid I don't know about those but I think Python 2 has Pandas and I guess the version is older than 0.17 from the behavior while I was looking for the workaround at #19607.

**Comment by HyukjinKwon** [comment]
Thanks for quick response. Will try to produce a matrix for it while I am here.

**Comment by HyukjinKwon** [comment]
Here, I printed in amp-jenkins-worker-07

```
PyPy - No Pandas
Python 2.7 Pandas [0.16.0]
Python 3.4 Pandas [0.19.2]

PyPy - No PyArrow
python 2.7 - No PyArrow
Python 3.4 PyArrow [0.4.1]
```

**Comment by HyukjinKwon** [comment]
Will take a look more tonight (KST).

**Comment by ueshin** [comment]
@HyukjinKwon Can you add `time.tzname` to the debug prints to confirm the timezone is changed properly.
FIY, it printed in my local as:

```
('PST', 'PDT')
```

**Comment by HyukjinKwon** [comment]
Mind was:

```
Before ('KST', 'KST')
After ('PST', 'PDT')
```

**Comment by HyukjinKwon** [comment]
I can directly add anything if you want to check, @ueshin. Just feel free to let me know, or I also support to open another PR to figure out if you are willing to. Meanwhile, let me print out few things I want to check.

**Comment by HyukjinKwon** [comment]
@ueshin, now I am getting what you meant by DST. I think you roughly knew this problem but let me describe it more given my debugging.

Looks the problem is in `mktime` and sounds `mktime` is platform-dependent (roughly assuming from codes and docs).

I made a minimised reproducer:

```python
import time
import os
from datetime import datetime
os.environ["TZ"] = "America/Los_Angeles"
time.tzset()
time.mktime(datetime(2100, 4, 4, 4, 4, 4).timetuple())
```

My local, it prints: 

```
4110523444.0
```

On Unbuntu 14.04:

```
4110519844.0
```

Jenkins, it prints:

```
4110519844.0
```

I am not sure if this is easily fixable within Spark as it looks dependent on Python implementation and/or the underlying C library, up to my knowledge and from my reading some docs.

Could you maybe avoid this time within DST for now in your PR? I currently don't have a good idea to fix this with a simple and surgical fix

**Comment by ueshin** [comment]
@HyukjinKwon Awesome! Thanks for the investigation!
I didn't think the "platform-dependent" is so dependent.
I'll update my pr to avoid the time within DST. Thanks!

**Comment by HyukjinKwon** [comment]
Let me leave this closed!

**Comment by BryanCutler** [comment]
Thanks for investigating this @HyukjinKwon !  In regards to the python 2.7 versions, I thought all workers were updated to use pandas 0.19.2 and pyarrow 0.4.1, not just for py3.  I'll bring this up when we start updating Arrow.

**Pull request closed without merging**
