### PR TITLE
[SPARK-46103][INFRA][FOLLOWUP] Unpin jinja2 in Python linter

### PR DESCRIPTION
**Pull request by zhengruifeng**
### What changes were proposed in this pull request?
https://github.com/apache/spark/pull/44012 unpinned jinja2 in doc build, this PR unpin it in Python linter.

this pr is only for master branch, and won't affect branch-3.x daily build

### Why are the changes needed?
to be consistent with requirements.

### Does this PR introduce _any_ user-facing change?
no

### How was this patch tested?
ci

### Was this patch authored or co-authored using generative AI tooling?
no

### CODE REVIEW

**Comment by zhengruifeng** [comment]
cc @itholic @HyukjinKwon

**Comment by zhengruifeng** [comment]
ci link: https://github.com/zhengruifeng/spark/actions/runs/7015244381/job/19084269583

**Review by itholic — APPROVED** [review]
LGTM. Thanks for following up!

**Comment by zhengruifeng** [comment]
merged to master

**Pull request closed without merging**
