### PR TITLE
[SPARK-21052][SQL][Follow-up] Add hash map metrics to join

### PR DESCRIPTION
**Pull request by viirya**
## What changes were proposed in this pull request?

Remove unused `numHashCollisions` and `timeSpentResizingNs` in `BytesToBytesMap`. And change `getAverageProbesPerLookup()` to `getAverageProbesPerLookup` as suggested.

## How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by viirya** [comment]
cc @gatorsmile

**Comment by viirya** [comment]
retest this please.

**Comment by gatorsmile** [comment]
Also `timeSpentResizingNs`

**Comment by gatorsmile** [comment]
LGTM pending Jenkins

**Comment by gatorsmile** [comment]
retest this please

**Comment by gatorsmile** [comment]
Thanks! Merging to master.

**Comment by viirya** [comment]
Thanks @gatorsmile.

**Pull request closed without merging**
