### PR TITLE
[SQL][minor] Removed unused Catalyst logical plan DSL.

### PR DESCRIPTION
**Pull request by rxin**
The Catalyst DSL is no longer used as a public facing API. This pull request removes the UDF and writeToFile feature from it since they are not used in unit tests.

### CODE REVIEW

**Comment by rxin** [comment]
Jenkins, retest this please.

**Comment by marmbrus** [comment]
Whats the motivation here?  I don't think this is really a maintenance burden for us and I know people are using this externally.  I think its good to encourage use of catalyst outside of Spark when it doesn't impact our productivity.

**Comment by rxin** [comment]
Note that the only thing that's removed is the UDF stuff, which is heavily tied to the internals anyway ... (one other thing is writeToFile).

**Comment by marmbrus** [comment]
Oh I see.  The diff looked scarier at first glance.  LGTM then.

**Comment by rxin** [comment]
Yea there were some whitespace change to remove one type hierarchy. Use w=1 to diff ignoring whitespace.

**Comment by rxin** [comment]
Jenkins, retest this please!

**Comment by rxin** [comment]
Jenkins, retest this please.

**Comment by rxin** [comment]
Jenkins, retest this please.

**Pull request closed without merging**
