### PR TITLE
[SPARK-34191][PYTHON][SQL] Add typing for udf overload

### PR DESCRIPTION
**Pull request by pgrz**
### What changes were proposed in this pull request?
Added typing for keyword-only single argument udf overload.

### Why are the changes needed?

The intended use case is:
```
@udf(returnType="string")
def f(x): ...
```

### Does this PR introduce _any_ user-facing change?

Yes - a new typing for udf is considered valid.

### How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @zero323

**Comment by zero323** [comment]
We have a typecheck pipeline here, so "How was this patch tested?" should state "existing tests".   I think it should also be described as introducing user facing change (as this PR changes what structures are considered to be valid by the checker. What do you think @HyukjinKwon?).

Other than that, LGTM.

**Comment by HyukjinKwon** [comment]
Sure, it's best to describe in details, and I trust your judgement on this.

**Comment by HyukjinKwon** [comment]
ok to test

**Comment by pgrz** [comment]
Addressed the comments

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master and branch-3.1.

**Comment by HyukjinKwon** [comment]
@pgrz, do you have a JIRA account? Can you leave a comment in SPARK-34191 so that I can check your account and assign the ticket to you?

**Comment by pgrz** [comment]
Done

**Pull request closed without merging**
