### PR TITLE
[SPARK-28942][WEBUI] Spark in local mode hostname display localhost in the Host Column of Task Summary Page

### PR DESCRIPTION
**Pull request by shivusondur**
### What changes were proposed in this pull request?
In spark-shell local mode, in the task page, host name is coming as localhost
This PR changes it to show machine IP, as shown in the "spark.driver.host" in the environment page

### Why are the changes needed?
To show the proper IP in the task page host column

### Does this PR introduce any user-facing change?
It updates the SPARK UI->Task page->Host Column

### How was this patch tested?
verfied in spark UI

image

### CODE REVIEW

**Comment by suraj95** [comment]
Hello,

I am new to this community. How can I start contributing ?

**Comment by shivusondur** [comment]
@HyukjinKwon @srowen

**Review by srowen — COMMENTED** [review]
OK, I guess that's a little more useful.

**Comment by srowen** [comment]
Merged to master

**Comment by shivusondur** [comment]
@srowen

**Pull request closed without merging**
