### PR TITLE
Revert "[SPARK-49909][SQL] Fix the pretty name of some expressions"

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to revert https://github.com/apache/spark/pull/48385.
This reverts commit 52538f0d9bd1258dc2a0a2ab5bdb953f85d85da9.

### Why are the changes needed?
When upgrading spark from `an old version` to `the latest version`, some end-users may rely on the `original schema` (`although it may not be correct`), which can make the `upgrade` very difficult. so, let's first restore it to its original state.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]

**Review by zhengruifeng — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you for reverting before Apache Spark 3.4.4, @panbingkun .

**Comment by dongjoon-hyun** [comment]
cc @MaxGekk

**Comment by panbingkun** [comment]
Thanks all!

**Review by MaxGekk — COMMENTED** [review]
> Why are the changes needed?
> Only revert.

It would be nice if you provide some reasons for reverting the bug fix.

**Comment by panbingkun** [comment]
> It would be nice if you provide some reasons for reverting the bug fix.

Okay, let me add something for it.

**Review by MaxGekk — APPROVED** [review]

**Comment by MaxGekk** [comment]
+1, LGTM. Merging to master.
Thank you, @panbingkun and @HyukjinKwon @zhengruifeng @dongjoon-hyun for review.

**Pull request closed without merging**
