### PR TITLE
[SPARK-32177][WEBUI] Remove the weird line from near the Spark logo on mouseover in the WebUI

### PR DESCRIPTION
**Pull request by sarutak**
### What changes were proposed in this pull request?

This PR changes `webui.css` to fix a style issue on moving mouse cursor on the Spark logo.

### Why are the changes needed?

In the webui, the Spark logo is on the top right side.
When we move mouse cursor on the logo, a weird underline appears near the logo.
logo_with_line

### Does this PR introduce _any_ user-facing change?

Yes. After this change applied, no more weird line shown even if mouse cursor moves on the logo.
removed-line-from-logo

### How was this patch tested?

By moving mouse cursor on the Spark logo and confirmed no more weird line there.

### CODE REVIEW

**Comment by sarutak** [comment]
retest this please.

**Comment by dongjoon-hyun** [comment]
Hi, @sarutak . If you want to backport this to `branch-3.0`, could you set the JIRA type as `Bug` instead of `Improvement`?

**Comment by dongjoon-hyun** [comment]
BTW, when I tried at Apache Spark 3.0.0 with Safari Private Window mode, I cannot reproduce the weird line. Is this `Chrome` only bug?

**Comment by dongjoon-hyun** [comment]
I verified this bug in 3.1.0-SNAPSHOT, but cannot reproduce at 3.0.1-SNAPSHOT with both Safari and Chrome.
Shall we drop `3.0.0` from the Affected Version in SPARK-32177?

**Comment by sarutak** [comment]
I reproduced it in 3.0.0-SNAPSHOT as follows.
weird-line-3 0 0
It's for the SNAPSHOT so I'll confirm again for the released one.

**Comment by sarutak** [comment]
It's strange but I've confirmed there are no weird line in `3.0.0` and `3.0.1-SNAPSHOT` (maybe, I've seen the line in the 3.0.0's history with 3.1.0's HistoryServer).
So I'll drop `3.0.0` from the Affect Version.

**Comment by dongjoon-hyun** [comment]
Thank you, @sarutak !

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @sarutak .
I verified this manually and this CSS-change PR is irrelevant to Jenkins UT.
Merged to master.

**Pull request closed without merging**
