### PR TITLE
[SPARK-46563][SQL] View simpleString not follow conf spark.sql.debug.maxToStringFields

### PR DESCRIPTION
**Pull request by AngersZhuuuu**
### What changes were proposed in this pull request?
View simpleString not follow conf spark.sql.debug.maxToStringFields

### Why are the changes needed?
When columns is too much, the info is noisy. View simpleString not follow conf spark.sql.debug.maxToStringFields

### Does this PR introduce _any_ user-facing change?
Yea, view's plan will follow ` spark.sql.debug.maxToStringFields`

### How was this patch tested?
No

### Was this patch authored or co-authored using generative AI tooling?
No

### CODE REVIEW

**Review by MaxGekk — COMMENTED** [review]
@AngersZhuuuu Could you check other places, please. I have found a couple more places where we could restrict the number of outputted fields:
```scala
case class ExternalRDDScanExec[T](
...
  override def simpleString(maxFields: Int): String = {
    s"$nodeName${output.mkString("[", ",", "]")}"
  }
```
and
```scala
case class UnresolvedTableSpec(
...
  override def simpleString(maxFields: Int): String = {
    this.copy(properties = Utils.redact(properties).toMap).toString
  }
```

**Review by MaxGekk — APPROVED** [review]
Waiting for CI.

**Comment by AngersZhuuuu** [comment]
> @AngersZhuuuu Could you check other places, please. I have found a couple more places where we could restrict the number of outputted fields:
> 
> ```scala
> case class ExternalRDDScanExec[T](
> ...
>   override def simpleString(maxFields: Int): String = {
>     s"$nodeName${output.mkString("[", ",", "]")}"
>   }
> ```
> 
> and
> 
> ```scala
> case class UnresolvedTableSpec(
> ...
>   override def simpleString(maxFields: Int): String = {
>     this.copy(properties = Utils.redact(properties).toMap).toString
>   }
> ```

Yea, let me check

**Comment by AngersZhuuuu** [comment]
Checked all and done

**Review by yaooqinn — APPROVED** [review]

**Review by HyukjinKwon — APPROVED** [review]

**Comment by AngersZhuuuu** [comment]
The remain failed GA seems not related?

**Comment by MaxGekk** [comment]
> The remain failed GA seems not related?

Seems not.

+1, LGTM. Merging to master.
Thank you, @AngersZhuuuu and @yaooqinn @HyukjinKwon for review.

**Pull request closed without merging**
