### PR TITLE
[SPARK-16362][SQL] Support ArrayType and StructType in vectorization Parquet reader

### PR DESCRIPTION
**Pull request by viirya**
## What changes were proposed in this pull request?

Vectorization parquet reader now doesn't support complex types such as ArrayType, MapType and StructType. We should support it to extend the coverage of performance improvement introduced by vectorization parquet reader. This patch is to add ArrayType and StructType first.
### Main changes
- Obtain repetition and definition level values during converting Parquet schema
  
  We convert Parquet schema to Catalyst DataType in `ParquetSchemaConverter`. Because we need repetition and definition level information during constructing complex types back from Parquet data, this PR obtains the repetition and definition levels for complex types and attaches them to Catalyst `ArrayType`, `MapType` and `StructType`. Accordingly, this PR adds a metadata to these Calalyst DataTypes as a new attribute. Although this PR tries to avoid modifying these Catalyst DataTypes, however, because the column vector in vectorization is corresponding to Catalyst DataType instead of Parquet schema, we can't access the repetition and definition levels for each column if we don't attach them to their assigned DataType.
- Attach `VectorizedColumnReader`  to `ColumnVector`
  
  Because in flat schema each `ColumnVector` is actually a data column, previously the relation between `VectorizedColumnReader` and `ColumnVector` is one-by-one. Now only the `ColumnVector` representing a data column will have corresponding `VectorizedColumnReader`. Then when it is time to read batch, the `ColumnVector` with complex type will delegate to its child `ColumnVector`.
- Implement constructing complex records in `VectorizedColumnReader`
  
  The `readBatch` in `VectorizedColumnReader` is the main method to read data into `ColumnVector`. Previously its behavior is simply to load required number of data according to the data type of the column vector. Now after the data is loaded into the column, we need to construct complex records in its parent column that could be an ArrayType, MapType or StructType. The way to restore the data as complex types is encoding in repetition and definition levels in Parquet. The new method `constructComplexRecords` in `VectorizedColumnReader` implements the logic to restore the complex data. Basically, what `constructComplexRecords` does is to count the continuous values and add array into the parent column if the repetition level value indicates a new record happens. Besides, `constructComplexRecords` also needs to consider the null values. Null values could mean a null record at root level, an empty array or struct. This method considers different cases and sets it correctly.
### Benchmark

```
val N = 10000
withParquetTable((0 until N).map { i =>
  ((i to i + 1000).toList, (i to i + 100).map(_.toString).toList,
    (i to i + 1000).map(_.toDouble / 2).toList,
    ((0 to 10).map(_.toString).toList, (0 to 10).map(_.toString).toList))
}, "t") {
  val benchmark = new Benchmark("Vectorization Parquet for nested types", N)
  benchmark.addCase("Vectorization Parquet reader", 10) { iter =>
    sql("SELECT _1[10], _2[20], _3[30], _4._1[5], _4._2[5] FROM t").collect()
  }
  benchmark.run()
}
```

Disabled vectorization:

```
Java HotSpot(TM) 64-Bit Server VM 1.8.0_71-b15 on Linux 3.19.0-25-generic
Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
Vectorization Parquet for nested types:  Best/Avg Time(ms)    Rate(M/s)   Per Row(ns)   Relative
------------------------------------------------------------------------------------------------
Vectorization Parquet reader                  1706 / 2207          0.0      170580.8       1.0X
```

Enabled vectorization:

```
Java HotSpot(TM) 64-Bit Server VM 1.8.0_71-b15 on Linux 3.19.0-25-generic
Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
Vectorization Parquet for nested types:  Best/Avg Time(ms)    Rate(M/s)   Per Row(ns)   Relative
------------------------------------------------------------------------------------------------
Vectorization Parquet reader                   789 /  972          0.0       78919.4       1.0X
```
## How was this patch tested?

Existing unit tests.

### CODE REVIEW

**Comment by viirya** [comment]
Submitted to see jenkins test results. Benchmark will be run later.

**Comment by viirya** [comment]
retest this please.

**Comment by viirya** [comment]
ok. 3 failed tests remaining...

**Comment by viirya** [comment]
ping @liancheng @yhuai @rxin I think this is ready now. Can you review this?

**Comment by viirya** [comment]
ping @liancheng @yhuai @rxin Can you review this? I think that we should support complex types in vectorization to extend the coverage of performance improvement. Thanks!

**Comment by liancheng** [comment]
@viirya Thanks for your work! This would be very useful. I'll help review this one soon after finishing my 2.0 tasks at hand!

**Comment by viirya** [comment]
@liancheng Thank you!

**Comment by viirya** [comment]
I am going to refactor this a lot.

**Comment by viirya** [comment]
Closed this PR in favor of the refactored one: #14388.

**Pull request closed without merging**
