### PR TITLE
[SPARK-19851][SQL] Add support for EVERY and ANY (SOME) aggregates

### PR DESCRIPTION
**Pull request by dilipbiswal**
## What changes were proposed in this pull request?
Implements Every, Some, Any aggregates in SQL. Logically these aggregate expressions are mapped to Min and Max, respectively. 
```
Every(x) => Min(x)  where x is boolean.
Some(x) => Max(x) where x is boolean.
```

Any is a synonym for Some.

## How was this patch tested?
Added tests in SQLQueryTestSuite, DataframeAggregateSuite

### CODE REVIEW

**Comment by dilipbiswal** [comment]
cc @cloud-fan @gatorsmile

**Comment by cloud-fan** [comment]
Hi @dilipbiswal  sorry for the back and forth, can you try one more approach? Basically we want to evaluate how the simplest logical rewrite looks like.

We can create unevaluatable EVERY and ANY expressions, and create a rule to replace them with MAX and MIN. This rule can be put in the beginning of optimizer like `RewriteDistinctAggregates`. We don't need to create a completed framework to rewrite agg functions.

**Comment by dilipbiswal** [comment]
@cloud-fan Sure.. Let me give that a try. Thanks

**Comment by cloud-fan** [comment]
yea, just a special rule instead of a general agg function rewrite framework.

**Comment by dilipbiswal** [comment]
@cloud-fan OK.. thanks a LOT.

**Pull request closed without merging**
