### PR TITLE
[MINOR][DOCS] Update pandas_pyspark.rst

### PR DESCRIPTION
**Pull request by kamelCased**
### What changes were proposed in this pull request?

Changes to pandas_pyspark.rst:
to --> the 

Changes to best_practices.rst:
APIs... uses --> APIs use
optimization --> optimizations 
This leads to move all data --> This moves all data 
Such APIs should be avoided very large dataset --> Such APIs should be avoided for very large datasets. 
One common issue when pandas-on-Spark users face is the slow performance by default index. --> One common issue that pandas-on-Spark users face is the slow performance due to the default index.

Changes to from_to_dbms.rst:
 it... them --> it... it 

Changes to transform_apply.rst: 
type hints... encouraged to use __ to --> type hints... encouraged to use them to    
The APIs slice... applies --> The APIs slice... apply     
its output is always treated that it belongs to a new different DataFrame --> its output is always treated as though it belongs to a new different DataFrame

Changes to contributing.rst:
pandas DataFrame.value_count --> pandas DataFrame.value_counts()

### Why are the changes needed?

Grammar fix

### Does this PR introduce _any_ user-facing change?

Documentation fix 

### How was this patch tested?

No test needed, same as yesterday's PR

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
@kamelCased while we're here, can we find all these instances, and fix them in one PR?

**Comment by kamelCased** [comment]
@HyukjinKwon I checked it's the last one in this file. I will check the rest of the PySpark docs.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
The test fails because your bunch is not synced to the latest `matster` branch. do you mind rebasing to the latest master branch?

**Comment by HyukjinKwon** [comment]
Also please update PR description to reflect the changes.

**Comment by HyukjinKwon** [comment]
ok to test

**Comment by kamelCased** [comment]
@HyukjinKwon fetched upstream and PR description updated

**Comment by kamelCased** [comment]
@HyukjinKwon fetched upstream and PR description updated

**Comment by kamelCased** [comment]
@HyukjinKwon fetched upstream and PR description updated

**Review by srowen — APPROVED** [review]

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
