### PR TITLE
[SPARK-27706][SQL][WEBUI] Add SQL metrics of numOutputRows for BroadcastExchangeExec

### PR DESCRIPTION
**Pull request by cxzl25**
## What changes were proposed in this pull request?

Add SQL metrics of numOutputRows for BroadcastExchangeExec

### CODE REVIEW

**Comment by cxzl25** [comment]
Current UI
image

Add SQL metrics of numOutputRows
image

number of output rows: 0

You can clearly see the amount of BroadcastExchange output, especially if there is no data output after calculation.

**Comment by cxzl25** [comment]
@cloud-fan  
Can help to see if this change is necessary, if you have free time
If necessary, help trigger the test

**Comment by xy2953396112** [comment]
I think it looks good

**Comment by cxzl25** [comment]
@dongjoon-hyun 
Can you help me review on this PR?

**Comment by cloud-fan** [comment]
ok to test

**Comment by cloud-fan** [comment]
usually we don't add row count metrics to operators that do not change numRows. Why didn't the Filter operator in our screenshot report row count?

**Comment by cxzl25** [comment]
ok, I know, it is really not necessary.

**Pull request closed without merging**
