### PR TITLE
[SPARK-13022] [test-maven] Shade jackson core

### PR DESCRIPTION
**Pull request by tedyu**
See the thread for background information:
http://search-hadoop.com/m/q3RTtYuufRO7LLG

This PR shades com.fasterxml.jackson.core as org.spark-project.jackson

### CODE REVIEW

**Comment by tedyu** [comment]
I can create a JIRA if this PR makes sense.

**Comment by srowen** [comment]
This is probably a good idea but doesn't fully solve the Jackson problem. If a transitive dependency uses Jackson, this doesn't affect it. Still ... can't hurt IMHO

**Comment by tedyu** [comment]
Jenkins, test this please

**Comment by vanzin** [comment]
Hmmm... I don't see how this would help much.

If you're shading one Jackson artifact, you should shade all of them. Otherwise users can get into weird situations by mixing and matching things in their applications. And shading all of jackson is tricky, because you have jackson-annotations and shading annotations doesn't work well with Scala code.

Regarding the original e-mail, if someone wants to use a newer version of jackson in their app, they have two choices:

- they need to use the `spark.{driver,executor}.userClassPathFirst` options and include the jackson jars with their application (with `--jars` or using fat jars)
- they need to override the version of Jackson used in Spark by provide all Jackson artifacts in `spark.{driver,executor}.extraClassPath`.

I'd try those before trying to change anything in Spark at all.

**Comment by tedyu** [comment]
jackson-annotations is in com.fasterxml.jackson.core, right ?

bq. shading annotations doesn't work well with Scala code

If you can give a bit more detail, that would be great.

Thanks

**Comment by vanzin** [comment]
> jackson-annotations is in com.fasterxml.jackson.core, right ?

No, it's a separate artifact (look at the Spark room pom).

> If you can give a bit more detail

https://issues.apache.org/jira/browse/SPARK-11615
Filed by some guy named Ted.

**Comment by tedyu** [comment]
I read the thread referenced by SPARK-11615 again.
But there was no clear statement on why shading annotation wouldn't work.

Test suite passed.

I think this PR would make Spark dependencies easier to handle.

**Comment by vanzin** [comment]
> But there was no clear statement on why shading annotation wouldn't work.

How so? The whole point of that thread is that shading annotations does not work. See the spark-shell problem that lead to that bug being filed, and the following message of why shading annotations does not work in Scala:

http://search-hadoop.com/m/q3RTtKpb7h1hVLvz1&subj=Re+Anybody+hit+this+issue+in+spark+shell+

Before even considering any of these changes, I'd like proof that existing solutions to this kind of problem (userClassPathFirst, overriding Spark's classpath) do not work.

**Comment by vanzin** [comment]
Oh, forgot one thing:

> Test suite passed.

Note that the change that caused SPARK-11615 *also* passed the test suite. That happens for two reasons:

- by default, tests are run with sbt, which doesn't do shading
- even if you trigger a maven build, tests are run before shading, with the original jars in the classpath, so you wouldn't catch that anyway.

In any case, you should add `[test-maven]` to your PR title to trigger a maven build.

**Comment by tedyu** [comment]
Thanks for the reminder, Marcelo

I am wondering if jackson-annotations dependency is really needed.

**Comment by tedyu** [comment]
By dropping jackson-annotations dependency I was able to get compilation pass.

If there is no objection, I can open another JIRA / PR for dropping jackson-annotations dependency.

**Comment by vanzin** [comment]
> By dropping jackson-annotations dependency

How did you drop it? Jackson annotations are used in several places (do `git grep @Json`).

**Comment by tedyu** [comment]
Thanks for the pointer

**Pull request closed without merging**
