### PR TITLE
[SPARK-21487][CORE][WEB UI] Change extension of mustache template files to .mustache

### PR DESCRIPTION
**Pull request by santosh-d3vpl3x**
### What changes were proposed in this pull request?
Change extension of mustache template files to .mustache from .html.

### Why are the changes needed?
These are used as mustache files but they use `.html` extension instead of `.mustache`.
Kerberised yarn applies auth filter twice on `.html` files causing `Request is a replay (34)`. This leads to blank pages in Spark UI and users are mostly left with a lot of guess work. Changing it to correct `.mustache` makes it render correctly as a welcome change.

### Does this PR introduce _any_ user-facing change?
for kerberised clusters, the executors and stages pages should start working again.

### How was this patch tested?
Two ways: 
- Ran spark locally and in kerberised cluster with and without knox. verify that it works. ✅
- Test cases in this CI. ✅

### CODE REVIEW

**Comment by srowen** [comment]
It's not a troublesome change, but seems hacky. Is there no way to fix the auth filter?

**Comment by santosh-d3vpl3x** [comment]
> It's not a troublesome change, but seems hacky. Is there no way to fix the auth filter?

I have seen a few attempts but not sure if it actually ever worked, we went through hadoop upgrades in hope that closed tickets on hadoop/yarn side would fix the issue but it proved to be futile.

Also, `.html` is a wrong extension for mustache template files for beginners. Mustache repo advertises `.mustache` as a correct extension. So not sure if it is really all that hacky.

**Comment by srowen** [comment]
Hm, are they 'mustache templates'? they seem like plain old HTML files. I don't have a specific concern, but concerned about changing the extension breaking something else that won't know to interpret this as HTML? probalby not an issue

**Comment by santosh-d3vpl3x** [comment]
> Hm, are they 'mustache templates'? they seem like plain old HTML files. 

Thats how they are treated at present even though couple of them don't really contain any templatised variables.
```js
var apps = $(Mustache.render($(template).filter("#history-summary-template").html(),data));
```
```js
tasksSummary.append(Mustache.render($(template).filter("#stages-summary-template").html()));
```
```js
executorsSummary.append(Mustache.render($(template).filter("#executors-summary-template").html(), data));
```

>I don't have a specific concern, but concerned about changing the extension breaking something else that won't know to interpret this as HTML? probalby not an issue
I static handler part in spark on server side and the renderer on client, couldn't find anything concerning.

**Comment by santosh-d3vpl3x** [comment]
Would one of you like to have a look @gengliangwang @LuciferYang?

**Pull request closed without merging**
