### PR TITLE
[SPARK-15057][GRAPHX] Remove stale TODO comment for making `enum` in GraphGenerators

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
## What changes were proposed in this pull request?

This PR removes a stale TODO comment in `GraphGenerators.scala`
## How was this patch tested?

Just comment removed.

### CODE REVIEW

**Comment by srowen** [comment]
I disagree with this. Quadrants are conventionally referred to by number (really, 1-4 not 0-3, but hey) rather than a letter. This is a private API anyway. I don't think this is improved with an enum.

**Comment by dongjoon-hyun** [comment]
Hi, @srowen . Thank you for review!
Then, may I just update this PR by simply removing the `TODO` comments?
```
// TODO(crankshaw) turn result into an enum (or case class for pattern matching}
```
Actually what I wanted to do was removing that long-lasting TODO comment. :)

**Comment by srowen** [comment]
I personally favor trivially resolving this by removing the TODO. I don't recognize the ABCD notation for quadrants anyway.

**Comment by dongjoon-hyun** [comment]
Oh, actually, the ABCD notation comes from the description of that function.
https://github.com/dongjoon-hyun/spark/blob/SPARK-15057/graphx/src/main/scala/org/apache/spark/graphx/util/GraphGenerators.scala#L181

```
   * <pre>
   *
   *          dst ->
   * (x,y) ***************  _
   *       |      |      |  |
   *       |  a   |  b   |  |
   *  src  |      |      |  |
   *   |   ***************  | T
   *  \|/  |      |      |  |
   *       |   c  |   d  |  |
   *       |      |      |  |
   *       ***************  -
   * </pre>
```

**Comment by srowen** [comment]
That makes more sense, OK. It's not referring to the usual quadrant I - IV in the plane. I think that's still not the recommended way to make enums in Scala (?) and may simply not be worth changing now, IMHO.

**Comment by dongjoon-hyun** [comment]
Sure. I just thought `enum` improves the `return` and `match` exhaustiveness, but I agree with your opinion, too.
I'll update this PR for just removing TODO.

**Comment by dongjoon-hyun** [comment]
Thank you for making decision for this PR, @srowen .
I updated the PR and JIRA accordingly. Now, this just removes comment.

**Comment by dongjoon-hyun** [comment]
Could you merge this PR, @srowen ?

**Comment by srowen** [comment]
OK, merged to master

**Comment by dongjoon-hyun** [comment]
Thank you, @srowen .

**Comment by rxin** [comment]
Since this is very low risk, I'm going to cherry-pick this in branch-2.0 too to minimize the diff.

**Comment by dongjoon-hyun** [comment]
Thank you, @rxin . :)

**Pull request closed without merging**
