### PR TITLE
[SPARK-43990][BUILD] Upgrade `kubernetes-client` to 6.7.2

### PR DESCRIPTION
**Pull request by bjornjorgensen**
### What changes were proposed in this pull request?
Upgrade kubernetes-client from 6.7.0 to 6.7.2

### Why are the changes needed?
[Release notes 6.7.1](https://github.com/fabric8io/kubernetes-client/releases/tag/v6.7.1)
[Release notes 6.7.2](https://github.com/fabric8io/kubernetes-client/releases/tag/v6.7.2)

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
It seems that this is 5th commit for this dependency. It looks like we will have 6.7.2 in a month. Maybe, shall we hold on until July 1st if there is no urgency with those two bugs, @bjornjorgensen ?
```
$ git log --oneline --since 2023-05-01 | grep kubernetes-client
592857945c [SPARK-43950][BUILD] Upgrade `kubernetes-client` to 6.7.0
c87061fbcb [SPARK-43581][BUILD][K8S] Upgrade `kubernetes-client` to 6.6.2
2bcfebf8a9 [SPARK-43455][BUILD][K8S] Bump kubernetes-client 6.6.1
b550f2b1f4 [SPARK-43355][K8S][BUILD] Upgrade `kubernetes-client` to 6.6.0
```

**Comment by bjornjorgensen** [comment]
yes, I know the reason for this is that SNYK are sending me mail about [SNYK-JAVA-COMSQUAREUPOKHTTP3-2958044](https://security.snyk.io/vuln/SNYK-JAVA-COMSQUAREUPOKHTTP3-2958044)
image

**Comment by dongjoon-hyun** [comment]
Could you explain a little more which commit fixes that?
- https://github.com/fabric8io/kubernetes-client/compare/v6.7.0...v6.7.1

**Comment by bjornjorgensen** [comment]
hmm.. you are right about that they are on 3.12.1
but "Maybe, shall we hold on until July 1st" why July 1st?

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. The python linter failure is flaky one. Thank you for waiting and updating, @bjornjorgensen .

Since they usually don't release x.y.3, I believe we can merge this for Apache Spark 3.5.0.

**Pull request closed without merging**
