### PR TITLE
[SPARK-5052] Add common/base classes to fix guava methods signatures.

### PR DESCRIPTION
**Pull request by elmer-garduno**
Fixes problems with incorrect method signatures related to shaded classes. For discussion see the jira issue.

### CODE REVIEW

**Comment by srowen** [comment]
You're right that I think this is too broad. I think I misspoke earlier. Isn't the theory here that you can bring a later version if Optional with you in your app?  Spark barely uses its API. If your copy of Optional hides the one in Spark, which is only there to keep the signature the same, is that OK?

**Comment by elmer-garduno** [comment]
I tried that before using spark.files.userClassPathFirst, but it resulted in a java.lang.NoClassDefFoundError: org/apache/spark/Partition ([full stack trace](https://gist.github.com/elmer-garduno/e65e3d992357253c6111)), which seemed bad enough to not go that way, but maybe someone else here knows the correct way to achieve it.

**Comment by elmer-garduno** [comment]
The problem seems to be fixed when using `spark-submit` instead of `spark-class`, that seems to set the appropriate precedence on the classpaths, so no need for any special flags or changes here.

Thanks

**Comment by elmer-garduno** [comment]
Reopening, the problem is still there when running on the standalone cluster.

**Comment by elmer-garduno** [comment]
@vanzin, any input here? Running with the patched code seems to solve the problem. Running on 1.2.0 standalone cluster generates the following errors:

a) `java.lang.NoSuchMethodError: com.google.common.base.Optional.transform(Lcom/google/common/base/Function;)Lcom/google/common/base/Optional;` as explained on the issue.
b) `java.lang.NoClassDefFoundError: org/apache/spark/Partition;` when running with `spark.files.userClassPathFirst=true`.

**Comment by srowen** [comment]
This one always confuses me, but here's what I think I know:

The compiled `Optional` in Spark won't have the "correct" (meaning, matching the Google Guava `Optional`) signatures on its methods since other Guava classes are shaded. It's there for the Spark API to compile against the Guava class in the package that the user app expects.

Apps that uses the API method that uses `Optional` will be bundling Guava. Spark uses Guava 14, although in theory you can use any version... that still has the very few methods on `Optional` that Spark actually calls, I suppose. Because Spark will be using the user app's copy of `Optional` at runtime.

You say you tried it and got `java.lang.NoClassDefFoundError: org/apache/spark/Partition` though. That's weird. `Optional` will be in a different classloader (?) but shouldn't refer to Spark classes. Right? if there's a problem it's somewhere in there, since that's where how I thought this works seems to not match your experience. Or else, there's something else subtly not-quite-right about how the user app is run here.

**Comment by vanzin** [comment]
Damn, exposing `Optional` in the API turned out to be a minefield... I see the problem and I don't see a good solution other than adding `Function` to the list of exclusions.

That being said, I think only `Function` should be added. The [source](https://code.google.com/p/guava-libraries/source/browse/guava/src/com/google/common/base/Function.java?name=master) indicates it has no references to other types, so hopefully it shouldn't cause any other issues...

**Comment by elmer-garduno** [comment]
I tried adding Function before, but it had some runtime dependencies.
Please see the last part of the third comment on
https://issues.apache.org/jira/plugins/servlet/mobile#issue/SPARK-5052.

**Comment by elmer-garduno** [comment]
Thanks, that worked, I updated the PR to reflect those changes. And here is a list of the actual classes that get included into the jar:

jar tf assembly/target/scala-2.10/spark-assembly-1.3.0-SNAPSHOT-hadoop1.2.1.jar |grep com.google.common.base
com/google/common/base/
com/google/common/base/Absent.class
com/google/common/base/Function.class
com/google/common/base/Optional$1$1.class
com/google/common/base/Optional$1.class
com/google/common/base/Optional.class
com/google/common/base/Present.class
com/google/common/base/Supplier.class

**Comment by vanzin** [comment]
Latest version LGTM. Thanks!

**Comment by srowen** [comment]
Although further creep of the unshading-of-the-shading feels risky, it seems to resolve a problem, and is in principle OK on the same grounds that unshading `Optional` is. I'm still puzzled about why using Guava 14 isn't working but wouldn't argue with solving a problem this way.

**Comment by elmer-garduno** [comment]
Thanks all, anything else left to be done here?

**Comment by vanzin** [comment]
Not from your side, you just need a committer to notice this PR. :-) @pwendell ?

**Comment by elmer-garduno** [comment]
Ping?

**Comment by elmer-garduno** [comment]
Jenkins test this please.

**Comment by pwendell** [comment]
Jenkins, test this please.

**Comment by pwendell** [comment]
LGTM although it's now been rolled into #3658 (@vanzin - maybe we can merge this one first just so we give credit correctly to @elmer-garduno).

**Comment by vanzin** [comment]
Yeah, no problem. I just didn't want to cause a regression later when my changes go in.

**Comment by pwendell** [comment]
Jenkins, retest this please.

**Comment by elmer-garduno** [comment]
Thanks for merging!

**Pull request closed without merging**
