### PR TITLE
[SPARK-16858] [SQL] [TEST] Removal of TestHiveSharedState

### PR DESCRIPTION
**Pull request by gatorsmile**
### What changes were proposed in this pull request?

This PR is to remove `TestHiveSharedState`. 

Also, this is also associated with the Hive refractoring for removing `HiveSharedState`.
### How was this patch tested?

The existing test cases

### CODE REVIEW

**Comment by rxin** [comment]
LGTM pending Jenkins.

**Comment by gatorsmile** [comment]
The failure is caused by the `SharedState` is not shared between different sessions. Since we are not using `SparkSession` in `TestHive`. Thus, we still need extra logics to sharing the `SharedState` between different sessions.

Now, we can remove `TestHiveSharedState`, but we still need to explicitly have a `HiveSharedState`.

**Comment by gatorsmile** [comment]
Updated the PR description.

**Comment by gatorsmile** [comment]
@rxin @yhuai The code is ready for review. Thanks!

**Comment by rxin** [comment]
Merging in master.

**Pull request closed without merging**
