### PR TITLE
[SPARK-18638][BUILD] Upgrade sbt, Zinc, and Maven plugins

### PR DESCRIPTION
**Pull request by weiqingy**
## What changes were proposed in this pull request?
This PR is to upgrade:
```
   sbt: 0.13.11 -> 0.13.13,
   zinc: 0.3.9 -> 0.3.11,
   maven-assembly-plugin: 2.6 -> 3.0.0
   maven-compiler-plugin: 3.5.1 -> 3.6.
   maven-jar-plugin: 2.6 -> 3.0.2
   maven-javadoc-plugin: 2.10.3 -> 2.10.4
   maven-source-plugin: 2.4 -> 3.0.1
   org.codehaus.mojo:build-helper-maven-plugin: 1.10 -> 1.12
   org.codehaus.mojo:exec-maven-plugin: 1.4.0 -> 1.5.0
```

The sbt release notes since the last version we used are: [v0.13.12](https://github.com/sbt/sbt/releases/tag/v0.13.12)  and [v0.13.13 ](https://github.com/sbt/sbt/releases/tag/v0.13.13).

## How was this patch tested?
Pass build and the existing tests.

### CODE REVIEW

**Comment by weiqingy** [comment]
Hi, @JoshRosen I am wondering if I should also upgrade sbt plugins in this PR? What do you think of this upgrade? Your suggestion will be helpful. Thanks.

**Comment by JoshRosen** [comment]
Upgrading to 0.13.13 is a great idea, especially since we might see compilation speed improvements due to https://github.com/sbt/sbt/pull/2754. Let's update the plugins separately.

**Comment by srowen** [comment]
Related -- how about updating zinc to 0.3.11?

Also I think you'll need to update scripts in `build/` to download a newer SBT. There are a few more changes to this.

**Comment by weiqingy** [comment]
@JoshRosen Thanks for the reply. I have checked the status of each sbt plugin. Except the plugins below, all other plugins are up-to-date.

- sbt-assembly: 0.11.2 -> 0.14.3
- sbteclipse-plugin: 4.0.0 -> 5.0.1
- org.ow2.asm/asm: 5.0.3 ->   5.1 (6.0_ALPHA is out)
- org.ow2.asm/asm-commons: 5.0.3  ->  5.1 (6.0_ALPHA it out)

May I create another jira to track the upgrade of these plugins? I can work on it too.

**Comment by weiqingy** [comment]
@srowen Thanks for the feedback. I will check the scripts in `build/`. Yes, I will upgrade zinc too. Should I create another jira to track the zinc upgrade? or we can merge the upgrade into this PR? The latest version of zinc is 0.3.13, how about upgrading zinc to 0.3.13 instead of 0.3.11?

**Comment by JoshRosen** [comment]
Let's update Zinc here. I wasn't aware that the 0.13.13 version Zinc was available (its release cycle is slightly behind SBT's).

**Comment by weiqingy** [comment]
@JoshRosen OK. I will update Zinc to 0.3.11, the latest stable version (The version of Zinc downloaded from "`Download the latest stable version`" in [Zinc github](https://github.com/typesafehub/zinc) is `zinc-0.3.11`)

**Comment by srowen** [comment]
Regarding plugin updates: I wouldn't mind updating the Maven plugins too while you're at it. `mvn versions:display-plugin-updates` will show you all the candidates. Some changes we can't or won't take but simple maintenance updates to plugins are generally fine.

**Comment by dongjoon-hyun** [comment]
nit. In PR description, 0.3.9 instead of 0.13.9 ?
> zinc: 0.13.9 -> 0.3.11,

**Comment by weiqingy** [comment]
@srowen Thanks for the information.

For sbt update, I think, currently, the only file needed to change is `project/build.properties`. The [Jenkins build console output](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/69365/consoleFull)  shows “`sbt 0.13.13`” has been downloaded and used in that build. Correct me if I miss anything.
```
Attempting to fetch sbt
Launching sbt from build/sbt-launch-0.13.13.jar
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
Getting org.scala-sbt sbt 0.13.13 ...
```
I have updated zinc and maven plugins. `mvn versions:display-plugin-updates` shows the following plugin updates are available:
```
[INFO]   maven-assembly-plugin .................................. 2.6 -> 3.0.0
[INFO]   maven-compiler-plugin ................................ 3.5.1 -> 3.6.0
[INFO]   maven-jar-plugin ....................................... 2.6 -> 3.0.2
[INFO]   maven-javadoc-plugin ............................... 2.10.3 -> 2.10.4
[INFO]   maven-source-plugin .................................... 2.4 -> 3.0.1
[INFO]   org.codehaus.mojo:build-helper-maven-plugin ............ 1.10 -> 1.12
[INFO]   org.codehaus.mojo:exec-maven-plugin .................. 1.4.0 -> 1.5.0
```
Also, in `Building Spark Project External Flume Sink 2.1.0-SNAPSHOT`,
```
The following plugin updates are available:
[INFO]   org.apache.avro:avro-maven-plugin .................... 1.7.7 -> 1.8.1
```
```
 <plugin>
    <groupId>org.apache.avro</groupId>
    <artifactId>avro-maven-plugin</artifactId>
    <version>${avro.version}</version>
    <configuration>
      <!-- Generate the output in the same directory as the sbt-avro-plugin -->
      <outputDirectory>${project.basedir}/target/scala-${scala.binary.version}/src_managed/main/compiled_avro</outputDirectory>
    </configuration>
    <executions>
      <execution>
        <phase>generate-sources</phase>
        <goals>
          <goal>idl-protocol</goal>
        </goals>
      </execution>
    </executions>
  </plugin>
```
If we want to update `avro-maven-plugin` from 1.7.7 to 1.8.1, we need to change the value of `<avro.version>1.7.7</avro.version> `in `spark-parent_2.11` pom file. That will affect some decencies, e.g.
```
<dependency>
   <groupId>org.apache.avro</groupId>
   <artifactId>avro</artifactId>
   <version>${avro.version}</version>
   <scope>${hadoop.deps.scope}</scope>
</dependency>
```
```
<dependency>
   <groupId>org.apache.avro</groupId>
   <artifactId>avro-ipc</artifactId>
   <classifier>tests</classifier>
   <version>${avro.version}</version>
   <scope>test</scope>
</dependency>
```
......

 

So avro-maven-plugin was not updated in this PR.

**Comment by weiqingy** [comment]
Thanks, @dongjoon-hyun Yes, Good catch. I have updated the description.

**Comment by weiqingy** [comment]
I will update the PR to fix the deprecation warnings in project/SparkBuild.scala.

**Review by srowen — APPROVED** [review]
That LGTM. The sbt.version change does also make the build download the newer SBT. We could do plugin updates separately but these are pretty harmless, so maybe fine to do a "build tool update" all at once here. I am even OK with this for 2.1?

**Comment by dongjoon-hyun** [comment]
+1 for 2.1!

**Comment by weiqingy** [comment]
Hi, @srowen Thanks for the review. I have updated the PR to fix deprecation warnings (about '`previousArtifact`', '`/`', '`stringToReference`', '`<+= `' operator, '`t3ToTable3`', '`<<=`' operator) based on the following references:
- http://www.scala-sbt.org/0.13/docs/Migrating-from-sbt-012x.html
- http://www.scala-sbt.org/0.13/sxr/sbt/Reference.scala.html
- https://github.com/sbt/sbt/issues/971  

The current fixes failed the MiMa tests. I will look into it.
    
As to the sbt plugins, @JoshRosen suggested to update them in a separate PR, so I think it’s better to confirm with him again.

**Comment by srowen** [comment]
Do you happen to know if the changes to the SBT build will still work with earlier versions of SBT? that is, is it just some cleanup or some required change?

Regarding plugins, maven plugins and SBT plugins are the same sort of thing. I don't mind updating any of them here too, or not.

**Comment by weiqingy** [comment]
Hi, @srowen I have fixed deprecation warnings. We should also use mimaBinaryIssueFilters and mimaPreviousArtifacts instead of deprecated binaryIssueFilters and previousArtifacts in MimaBuild.scala. The reason why yesterday’s commits failed the MiMa tests is previousArtifacts was used in MimaBuild.scala while mimaPreviousArtifacts was used in SparkBuild.scala. MimaBuild.scala and SparkBuild.scala should use consistent functions. Could you please help to review the PR again?

I have created a separate jira [SPARK-18697](https://issues.apache.org/jira/browse/SPARK-18697) to upgrade sbt plugins. I will submit a PR for it after this PR is merged. I was trying to upgrade sbt plugins locally, but, besides plugins.sbt, multiple places need to be changed, e.g. some errors below need to be fixed. So I think it’s better to minimize the current PR.

```
[error] /root/spark/project/SparkBuild.scala:600: object Plugin is not a member of package sbtassembly
[error]   import sbtassembly.Plugin._
[error]                      ^
[error] /root/spark/project/SparkBuild.scala:601: not found: value AssemblyKeys
[error]   import AssemblyKeys._
[error]          ^
[error] /root/spark/project/SparkBuild.scala:605: not found: value assemblySettings
[error]   lazy val settings = assemblySettings ++ Seq(
[error]                       ^
[error] /root/spark/project/SparkBuild.scala:635: object Plugin is not a member of package sbtassembly
[error]   import sbtassembly.Plugin._
[error]                      ^
[error] /root/spark/project/SparkBuild.scala:636: not found: value AssemblyKeys
[error]   import AssemblyKeys._
```

**Comment by srowen** [comment]
Merged to master. It's a build change and probably fine for 2.1 but it's non-trivial.

**Pull request closed without merging**
