### PR TITLE
[WIP] Purge `amp-jenkins-worker-05` local maven repository

### PR DESCRIPTION
**Pull request by dongjoon-hyun**

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Retest this please

**Comment by dongjoon-hyun** [comment]
Retest this please

**Comment by dongjoon-hyun** [comment]
Retest this please

**Comment by dongjoon-hyun** [comment]
Retest this please

**Comment by dongjoon-hyun** [comment]
Retest this please

**Comment by dongjoon-hyun** [comment]
This is happening now on that `amp-jenkins-worker-05`.
- https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/122746/

cc @srowen

**Comment by dongjoon-hyun** [comment]
Purge seems to finish successfully. 
I triggered `branch-3.0` job.
- https://amplab.cs.berkeley.edu/jenkins/view/Spark%20QA%20Test%20(Dashboard)/job/spark-branch-3.0-test-sbt-hadoop-3.2-hive-2.3/492/console

**Comment by dongjoon-hyun** [comment]
Interesting. The failure is the same. Maybe, we missed something.
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-install-plugin:3.0.0-M1:install (default-cli) on project spark-parent_2.12: ArtifactInstallerException: Failed to install metadata org.apache.spark:spark-parent_2.12/maven-metadata.xml: Could not parse metadata /home/jenkins/.m2/repository/org/apache/spark/spark-parent_2.12/maven-metadata-local.xml: in epilog non whitespace content is not allowed but got > (position: END_TAG seen ...</metadata>\n>... @13:2) -> [Help 1]
```

**Comment by srowen** [comment]
Hm ok I think somehow the failure is too early in the process. There might be a way to do it but I think Shane just has to log in and clear it

**Pull request closed without merging**
