### PR TITLE
[SPARK-20443][MLLIB][ML] set ALS blockify size

### PR DESCRIPTION
**Pull request by mpjlu**
## What changes were proposed in this pull request?

The blockSize of MLLIB ALS is very important for ALS performance.
In our test, when the blockSize is 128, the performance is about 4X comparing with the blockSize is 4096 (default value).
The following are our test results:
BlockSize(recommendationForAll time)
128(124s), 256(160s), 512(184s), 1024(244s), 2048(332s), 4096(488s), 8192(OOM)

The Test Environment:
3 workers: each work 10 core, each work 30G memory, each work 1 executor.
The Data: User 480,000, and Item 17,000

## How was this patch tested?
The existing UT

### CODE REVIEW

**Comment by MLnick** [comment]
Just to confirm, the #users is 48 million, #items is 1.7 million?

**Comment by MLnick** [comment]
Or is it 48,000 and 1,700?

**Comment by mpjlu** [comment]
users is 480,000, items is 170,000. Thanks

**Comment by MLnick** [comment]
ok. And it is the timing for `recommendProductsForUsers`? Or `recommendUsersForProducts`?

**Comment by mpjlu** [comment]
RecommandProductsForUsers. Thanks

**Comment by MLnick** [comment]
It's interesting to see the performance difference. I've also been looking at performance of recommend all but haven't gotten to varying the block sizes just yet.

I'm potentially in favor of exposing it as a param - but what you've got here doesn't do anything to the public API so how does that help?

**Comment by mpjlu** [comment]
Thanks @MLnick . Could you please review my another PR for recommend all performance problem.
https://github.com/apache/spark/pull/17742.
Sorry, I forget user cannot call recommendForAll directly for this PR.

**Comment by mpjlu** [comment]
Hi @MLnick , since #17742 is merged into branch-2.2, and this PR is related with PR17742. Should we close this PR and open a new PR based on branch-2.2.

**Comment by mpjlu** [comment]
retest this please

**Comment by mpjlu** [comment]
Because I don't have the environment to continue this work, I will close it. Thanks.

**Pull request closed without merging**
