### PR TITLE
[SPARK-39440][CORE][UI] Add a config to disable event timeline

### PR DESCRIPTION
**Pull request by wangyum**
### What changes were proposed in this pull request?

This pr introduces a config to disable event timeline on UI pages.

### Why are the changes needed?

Speed up UI. We usually don't care about the event timeline:
image

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

manual and unit test.

### CODE REVIEW

**Comment by wangyum** [comment]
@sarutak @gengliangwang

**Comment by wangyum** [comment]
> Nit: shall we have a new test case in `UISeleniumSuite`?

Have added the UT.

**Review by gengliangwang — APPROVED** [review]
Thanks for the work!

**Comment by gengliangwang** [comment]
Thanks, merging to master

**Review by dongjoon-hyun — COMMENTED** [review]
+1, Looks like a nice feature and safe because there is no default behavior change.

Thank you, @wangyum and @gengliangwang .

**Pull request closed without merging**
