### PR TITLE
[SPARK-20763][SQL][Backport-2.1] The function of `month` and `day` return the value which is not we expected.

### PR DESCRIPTION
**Pull request by 10110346**
## What changes were proposed in this pull request?

This PR is to backport #17997 to Spark 2.1

when the date before "1582-10-04", the function of month and day return the value which is not we expected.
How was this patch tested?

unit tests

### CODE REVIEW

**Comment by wzhfy** [comment]
Wrong branch (branch-2.1 instead of master)?

**Comment by 10110346** [comment]
This change has  Merged  to master/2.2  in PR #17997
The current  PR  just submits a backport PR to 2.1 @gatorsmile @wzhfy

**Comment by wzhfy** [comment]
@10110346 I mean you want to merge this into branch-2.1, not master, right?

**Comment by 10110346** [comment]
yes,merge this into branch-2.1

**Comment by wzhfy** [comment]
So can you change this?
> 10110346  wants to merge 2 commits into **apache:master** from 10110346:wip_lx_0516

**Comment by ueshin** [comment]
@10110346 Hi, I guess you created a topic branch from `master`, but you need to create the topic branch from `branch-2.1` and then submit a pr to the `branch-2.1`.

**Comment by 10110346** [comment]
ok, thanks @wzhfy  @ueshin

**Pull request closed without merging**
