### PR TITLE
[SPARK-44080][SQL] Support overriding SQL configurations for new connections

### PR DESCRIPTION
**Pull request by wangyum**
### What changes were proposed in this pull request?

This PR adds a ServletHandler to support overriding SQL configurations for new connections.

### Why are the changes needed?

To support overriding the SQL config default value for new connections without restart SparkContext. The use cases:
1. Disable a newly introduced feature if it has a bug.
2. Fine-tune the value of some configurations. For example: `spark.sql.files.maxPartitionNum` ,`spark.sql.parquet.pushdown.inFilterThreshold`.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Manual test.

1. Test function as expected:
```
yumwang@LM-SHC-16508156 spark % bin/beeline -u "jdbc:hive2://localhost:10000/" -e "set spark.sql.cbo.enabled;"              
...
+------------------------+--------+
|          key           | value  |
+------------------------+--------+
| spark.sql.cbo.enabled  | false  |
+------------------------+--------+
1 row selected (0.14 seconds)

yumwang@LM-SHC-16508156 spark % curl "http://localhost:4040/sqlserver/overridesqlconf/?key=spark.sql.cbo.enabled&value=true" 

yumwang@LM-SHC-16508156 spark % bin/beeline -u "jdbc:hive2://localhost:10000/" -e "set spark.sql.cbo.enabled;"             
...
+------------------------+--------+
|          key           | value  |
+------------------------+--------+
| spark.sql.cbo.enabled  | true   |
+------------------------+--------+
1 row selected (0.115 seconds)
```
3. Test UI:

image

image

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @gengliangwang and @sarutak FYI

**Review by dongjoon-hyun — COMMENTED** [review]
Hi, @wangyum . This looks like admin user level features. When there are many users, it seems that the changed configuration may cause a query failure for a user who runs always the same query. Did I understand correctly?

**Comment by wangyum** [comment]
@dongjoon-hyun Yes. It's admin user level features.

**Comment by wangyum** [comment]
cc @cloud-fan  @yaooqinn @juliuszsompolski

**Comment by cloud-fan** [comment]
does it have to be a UI feature? What if we provide command line tools or REST API to change the config value for a `SparkContext`?

**Comment by yaooqinn** [comment]
Yeah. Currently, the Spark UI serves only for monitoring and not for administration purposes.

**Comment by wangyum** [comment]
@cloud-fan 
At the beginning, I also would like to achieve it by changing the config of `SparkContext`, but changing the config of `SparkContext` cannot overwrite the configuration already contained in [initialSessionOptions](https://github.com/apache/spark/blob/071feabbd4325504332679dfa620bc5ee4359370/sql/core/src/main/scala/org/apache/spark/sql/SparkSession.scala#L257).

The advantage of the UI feature over the REST API is that it can display configurations that have been overridden.

@yaooqinn Spark UI is not only for monitoring, it can also kill jobs.

**Pull request closed without merging**
