### PR TITLE
[SPARK-14417] Deprecation fixes from Scala 2.10.

### PR DESCRIPTION
**Pull request by aa8y**
## What changes were proposed in this pull request?

Fixed a bunch of deprecation warnings I saw when compiling the current Spark `master`.
## How was this patch tested?

No new unit tests needed as far as I know.

### CODE REVIEW

**Comment by hvanhovell** [comment]
@aa8y please check if these will compile with scala 2.10

**Comment by aa8y** [comment]
@hvanhovell I am not sure how to do that. Still learning working with SBT. Any tips?

**Comment by hvanhovell** [comment]
could you try: 
```
./dev/change-scala-version.sh 2.10
./build/sbt -Pscala-2.10 clean compile
```

And see if that works?

**Comment by aa8y** [comment]
I still feel like it is compiling with 2.11 looking at the output on the console. But it did fail, unable to resolve a library dependency, with the version set to 2.10
```
> ./dev/change-scala-version.sh 2.10
./dev/../assembly/pom.xml
...
./dev/../docs/_plugins/copy_api_dirs.rb
```
```
> ./build/sbt -Pscala-2.10 clean compile
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
...
[info] Resolving org.scala-lang.modules#scala-async_2.11;0.9.1 ...
...
[info] Resolving org.scala-lang.modules#scala-xml_2.11;1.0.2 ...
...
[info] Packaging /Users/aallamsetty/code/spark-fork/mllib-local/target/scala-2.11/spark-mllib-local_2.11-2.0.0-SNAPSHOT.jar ...
...
[info] Resolving org.scala-lang#jline;2.11.8 ...
[warn] 	module not found: org.scala-lang#jline;2.11.8
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/scala-lang/jline/2.11.8/jline-2.11.8.pom
[warn] ==== Maven2 Local: tried
[warn]   file:/Users/aallamsetty/.m2/repository/org/scala-lang/jline/2.11.8/jline-2.11.8.pom
[warn] ==== local: tried
[warn]   /Users/aallamsetty/.ivy2/local/org.scala-lang/jline/2.11.8/ivys/ivy.xml
[info] Resolving jline#jline;2.12.1 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.scala-lang#jline;2.11.8: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[info] Resolving org.scala-lang#scala-library;2.11.8 ...
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn] 		org.scala-lang:jline:2.11.8 ((com.typesafe.sbt.pom.MavenHelper) MavenHelper.scala#L76)
[warn] 		  +- org.apache.spark:spark-repl_2.11:2.0.0-SNAPSHOT
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
...
sbt.ResolveException: unresolved dependency: org.scala-lang#jline;2.11.8: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:313)
...
	at java.lang.Thread.run(Thread.java:745)
[error] (repl/*:update) sbt.ResolveException: unresolved dependency: org.scala-lang#jline;2.11.8: not found
[error] Total time: 230 s, completed Apr 24, 2016 11:56:05 AM
```
which doesn't seem to be a problem when compiled with 2.11 in a similar manner.
```
> ./dev/change-scala-version.sh 2.11
./dev/../assembly/pom.xml
...
./dev/../docs/_plugins/copy_api_dirs.rb
```
```
> ./build/sbt -Pscala-2.11 clean compile
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
...
[warn] 81 warnings found
[success] Total time: 193 s, completed Apr 24, 2016 12:00:06 PM
```

**Comment by hvanhovell** [comment]
@JoshRosen how can I switch the SBT build to scala 2.10?

**Comment by srowen** [comment]
No, I know these break 2.10. That's why they haven't been zapped yet.

**Comment by hvanhovell** [comment]
Ok, that settles is it then.  @aa8y could you close this? Thanks for working on it though.

**Comment by aa8y** [comment]
@srowen, @hvanhovell I'll close this ticket. I am assuming support for Scala 2.10 will be ceased in Spark 2.0.0. Can this be reopened once the work for that has been done (looking at SPARK-14417)?

**Comment by jodersky** [comment]
If I recall correctly, Scala 2.10 will stay for 2.0.0 (probably not for all future 2.x releases though, it could be removed as soon as 2.1.0). However, I see no problem in reopening the issue when the time comes, you or any committer can do that.
I would suggest you rename the pr to include the jira number, something like `[SPARK-14417] Deprecation fixes from Scala 2.10`, before you close it. That way it will be linked to from the issue tracker for the future.

thanks for working on this

**Comment by aa8y** [comment]
Known issue which cannot be fixed until Spark ceases support for Scala 2.10.

**Pull request closed without merging**
