### PR TITLE
[SPARK-14514][DOC] Add python example for VectorSlicer

### PR DESCRIPTION
**Pull request by zhengruifeng**
## What changes were proposed in this pull request?

Add the missing python example for VectorSlicer
## How was this patch tested?

manual tests

### CODE REVIEW

**Comment by holdenk** [comment]
So this one differs slightly from the Scala example, it might make sense to have a follow JIRA for once/if AttributeGroup is exposed in Python to also update this example. What do you think?

**Comment by zhengruifeng** [comment]
@holdenk I agree with you. Wrapper for AttributeGroup is missing now.

**Comment by holdenk** [comment]
Rad, maybe @jkbradley can take a look at this PR?

**Comment by jkbradley** [comment]
test this please

**Comment by jkbradley** [comment]
LGTM pending an updated run of the tests

I agree we can update this later after Attributes are exposed in Python.  We want to re-evaluate the attribute/metadata API first.

**Comment by jkbradley** [comment]
Merging with master
Thanks @zhengruifeng !

**Pull request closed without merging**
