### PR TITLE
[SPARK-11284] [ML] ALS produces float predictions instead of double

### PR DESCRIPTION
**Pull request by dahlem**
@mengxr 
This pull request just changes the float predictions into doubles with corresponding changes to use the double precision BLAS APIs.

[LIRA issue SPARK-11284](https://issues.apache.org/jira/browse/SPARK-11284)

### CODE REVIEW

**Comment by mengxr** [comment]
@dahlem Any issue with float precision? The ratings do not have high precision anyway. Changing it to double precision increases the shuffle size by a lot. If you want to make the `RegressionEvaluator` work with `ALS`, you can cast the label type to Double in `RegressionEvaluator`.

**Comment by felixcheung** [comment]
Shouldn't this be fixed/casted in the `RegressionEvaluator` instead?

**Comment by dahlem** [comment]
That makes sense. I fixed it on my branch and will create a pull request
against a new ticket.

**Comment by mengxr** [comment]
@dahlem If you plan to make a new pull request, could you close this PR manually? We don't have direct access to close Spark PRs. Thanks!

**Pull request closed without merging**
