### PR TITLE
[PYTHON] [SPARK-32797] updating mypy to 0.910 so that tests will run

### PR DESCRIPTION
**Pull request by shaneknapp**
### What changes were proposed in this pull request?
updating the anaconda py36 environment to use the latest version of mypy (0.910)

### Why are the changes needed?
so that tests run

### Does this PR introduce _any_ user-facing change?
no

### How was this patch tested?
jenkins will test

### CODE REVIEW

**Comment by shaneknapp** [comment]
test this please

**Comment by shaneknapp** [comment]
test this please (i've disable mypy on the workers until the style checks are fixed, see https://issues.apache.org/jira/browse/SPARK-32797 for more details)

**Comment by HyukjinKwon** [comment]
@shaneknapp, I think maybe it's also related to Python version that runs mypy. Maybe we can just remove mypy in Jenkins for now since we're running it in GitHub Actions anyway.

**Comment by shaneknapp** [comment]
> @shaneknapp, I think maybe it's also related to Python version that runs mypy. Maybe we can just remove mypy in Jenkins for now since we're running it in GitHub Actions anyway.

sgtm!  i'll close this now.

**Comment by HyukjinKwon** [comment]
👍

**Pull request closed without merging**
