### PR TITLE
[SPARK-8115] [SQL] Remove TestData

### PR DESCRIPTION
**Pull request by BenFradet**
This PR aims to bring the test datasets closer to the test suites.

### CODE REVIEW

**Comment by rxin** [comment]
@BenFradet thanks for doing this. I think this is fairly useful & important, but the best time to merge this is during our QA period for 1.5.0, i.e. in the first 2 weeks of Aug, to avoid creating a lot of conflicts.

Can we revisit this after Aug 1?

**Comment by BenFradet** [comment]
Sure, no problem.

**Comment by rxin** [comment]
@BenFradet After we've cut the release branch for 1.5, it would be great to bring this up-to-date so we can merge it. Thanks!

**Comment by BenFradet** [comment]
Yup, will do later in the week.

**Comment by BenFradet** [comment]
I have no idea why both of those tests ([this one](https://github.com/apache/spark/blob/master/sql/core/src/test/scala/org/apache/spark/sql/JoinSuite.scala#L151) and [this one](https://github.com/apache/spark/blob/master/sql/core/src/test/scala/org/apache/spark/sql/DataFrameSuite.scala#L617)) are failing, much help needed cc @rxin.

Will rebase soon.

**Comment by rxin** [comment]
Thanks @BenFradet. Looks like @andrewor14 is working on this at the same time to also get rid of the singleton TestSQLContext in order for his own tests to pass.

https://github.com/apache/spark/pull/8111

He will incorporate your changes into that.

**Comment by BenFradet** [comment]
Ok, thanks for keeping me in the loop.

**Comment by BenFradet** [comment]
@rxin Should I close this then?

**Comment by rxin** [comment]
Actually it looks like @andrewor14's patch just moved TestData somewhere else to remove the singleton. Maybe we should still bring this one up to date once his merges ... :)

**Comment by andrewor14** [comment]
Don't we want a common collection of test data shared among different tests? It helps reducing duplicate code.

**Comment by rxin** [comment]
No it is better to have the data closer to the test cases. Right now for
most test cases it is hard to know what the correct answers should be
because the input data is not defined in the test case (or even same file).

**Comment by BenFradet** [comment]
@rxin @andrewor14

This patch doesnt really make sense with the introduction of [SQLTestData](https://github.com/apache/spark/blob/master/sql/core/src/test/scala/org/apache/spark/sql/test/SQLTestData.scala) in #8111, does it?

**Comment by JoshRosen** [comment]
Hey @BenFradet, would you mind closing this PR for now? While I think that we may eventually remove TestData, this PR is going to be really merge-conflict prone and I think it would be easier for one of the committers to take it over and handle fixing the conflicts. If we do that, we'll be sure to credit your initial work here and use it as the foundation for our patch. Thanks!

**Comment by BenFradet** [comment]
Sure, no problem.

**Pull request closed without merging**
