### PR TITLE
[SPARK-12315][SQL] isnotnull operator not pushed down for JDBC datasource.

### PR DESCRIPTION
**Pull request by HyukjinKwon**
https://issues.apache.org/jira/browse/SPARK-12315
`IsNotNull` filter is not being pushed down for JDBC datasource.

It looks it is SQL standard according to [SQL-92](http://www.contrib.andrew.cmu.edu/~shadow/sql/sql1992.txt), SQL:1999, [SQL:2003](http://www.wiscorp.com/sql_2003_standard.zip) and [SQL:201x](http://www.wiscorp.com/sql20nn.zip) and I believe most databases support this.

In this PR, I simply added the case for `IsNotNull` filter to produce a proper filter string.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Actually the test for this PR is not correctly being tested with the result but I just added it just like the other predicate tests. I will correct the test as soon as https://github.com/apache/spark/pull/10221 is merged.

**Comment by jodersky** [comment]
duplicate of #10286

**Comment by HyukjinKwon** [comment]
I updated the test for this since https://github.com/apache/spark/pull/10221 is merged.

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
cc @rxin @marmbrus

**Comment by rxin** [comment]
Next time please submit a single PR for these, since they are all in one place and are conflicting with each other...

**Comment by rxin** [comment]
I've merged this. Thanks.

**Pull request closed without merging**
