### PR TITLE
[SPARK-43888][CONNECT][FOLLOW-UP] Spark Connect client should depend on common-utils explicitly

### PR DESCRIPTION
**Pull request by amaliujia**
### What changes were proposed in this pull request?

 Spark Connect client should depend on common-utils directly.

### Why are the changes needed?

Spark Connect client is already depending on `common-utils` transitively. We should make this dependency explicit. 

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

N/A

### CODE REVIEW

**Comment by amaliujia** [comment]
@hvanhovell @cloud-fan

**Comment by LuciferYang** [comment]
I think `common-utils` should be shaded into the `connect-client-jvm` module uber jar, so that users can still just use `connect-client-jvm` module

**Review by cloud-fan — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Yeah, I think it has to be shaded

**Comment by amaliujia** [comment]
@LuciferYang can you share an example of how to shade the module by maven and sbt (I guess we have to do both sides)?

**Comment by LuciferYang** [comment]
@amaliujia sorry to missing message, you can refer to

https://github.com/apache/spark/blob/958b85418034d3bdce56a7520c0728d666c79480/connector/connect/client/jvm/pom.xml#L165

for maven.

sbt should not require additional configuration, I think the existing assembly configurations will auto packaging this module

**Comment by amaliujia** [comment]
@LuciferYang thank you so much!

It seems just be a line of change. Done.

**Comment by hvanhovell** [comment]
Merging.

**Pull request closed without merging**
