### PR TITLE
[Example][python] Solved input file path error

### PR DESCRIPTION
**Pull request by nmolkeri**
## What changes were proposed in this pull request?

While running the examples file there was an error to read data from data directory. Changed code to read from the directory.

### CODE REVIEW

**Comment by rxin** [comment]
This is pretty weird, because it means this would fail with a different path. Maybe we should just look up the current file path and do ../../../../ ...

**Comment by nmolkeri** [comment]
Can you be more clear with the "Maybe we should just look up the current file path and do ../../../../ ..." part. 

Thank you.

**Comment by rxin** [comment]
I was referring to finding the absolute path of the example file, and then use that to find the absolute path of the data.

**Comment by srowen** [comment]
Example would be invoked from the project root, right?

**Comment by nmolkeri** [comment]
Yes they can be invoked. 

````
Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe.
: org.apache.hadoop.mapred.InvalidInputException: Input path does not exist: file:/Users/niranjan/chico/630/Spark/spark/examples/src/main/python/mllib/data/mllib/sample_binary_classification_data.txt
````
This was the error I got when trying to run from my forked master repo. So I fixed it to get the input from correct path. It was taking example folder as the source for data files.

**Comment by srowen** [comment]
My question is where you run the example from? the working directory.

**Comment by nmolkeri** [comment]
yes.

**Pull request closed without merging**
