### PR TITLE
[SPARK-47261][SQL] Assign better name for errors _LEGACY_ERROR_TEMP_1172, _LEGACY_ERROR_TEMP_1173, and _LEGACY_ERROR_TEMP_1174

### PR DESCRIPTION
**Pull request by junyuc25**
### What changes were proposed in this pull request?

Assign better name for error _LEGACY_ERROR_TEMP_1172, _LEGACY_ERROR_TEMP_1173, and _LEGACY_ERROR_TEMP_1174.

### Why are the changes needed?

Proper name improves user experience with Spark SQL.

### Does this PR introduce _any_ user-facing change?

Yes.

### How was this patch tested?

Added new tests and ran all the tests in the suite: 
```
org.apache.spark.sql.execution.datasources.parquetParquetSchemaSuite
org.apache.spark.SparkThrowableSuite
```

### Was this patch authored or co-authored using generative AI tooling?

No

### CODE REVIEW

**Comment by junyuc25** [comment]
Hi @MaxGekk @cloud-fan , I raise a quick PR for https://issues.apache.org/jira/browse/SPARK-47261. Do you mind taking a quick look? Thanks.

**Comment by junyuc25** [comment]
Hi @LuciferYang @yaooqinn, not sure if you could take a look at this quick PR to refine the names for some legacy error types?

**Review by MaxGekk — APPROVED** [review]

**Comment by MaxGekk** [comment]
+1, LGTM. Merging to master.
Thank you, @junyuc25.

**Comment by MaxGekk** [comment]
@junyuc25 Do you have an account the JIRA: https://issues.apache.org/jira/browse/SPARK-47261 ? If so, please, leave a comment in the ticket like you working on the ticket otherwise create an account.

So far, I will assign the ticket to me, and when I get your account name, I'll reassign the ticket.

**Pull request closed without merging**
