### PR TITLE
[SPARK-5661]function hasShutdownDeleteTachyonDir should use shutdownDeleteTachyonPaths to determine whether contains file

### PR DESCRIPTION
**Pull request by viper-kun**
hasShutdownDeleteTachyonDir(file: TachyonFile) should use shutdownDeleteTachyonPaths(not shutdownDeletePaths) to determine Whether contain file. To solve it ,delete two unused function.

### CODE REVIEW

**Comment by viper-kun** [comment]
cc @haoyuan

**Comment by srowen** [comment]
These do appear unused, at the moment, but what's the need to delete them? They could plausibly be useful later; it's not completely useless code. (Normally changes need a JIRA too, although this is borderline)

**Comment by viper-kun** [comment]
@srowen  
ok. if it is useful later; we should change it like this
def hasShutdownDeleteTachyonDir(file: TachyonFile): Boolean = {
    val absolutePath = file.getPath()
    shutdownDeleteTachyonPaths.synchronized {
      shutdownDeleteTachyonPaths.contains(absolutePath)
    }
  }

**Comment by JoshRosen** [comment]
I think we should create a JIRA for this, if only to help us keep track of where this change is committed.

**Comment by haoyuan** [comment]
Thanks @viper-kun 

Agree w/ @JoshRosen

**Comment by viper-kun** [comment]
ok. i will create a JIRA.

**Comment by srowen** [comment]
ok to test

**Comment by srowen** [comment]
OK, that change seems reasonable as a bug fix.
Isn't it weird to have Tachyon specific support code in such a common `Utils` class? Shouldn't this go to the Tachyon block manager or something?

**Comment by viper-kun** [comment]
@srowen  it is a static function and unused now. I think we should better leave it in Utils class now.

**Comment by srowen** [comment]
@haoyuan what do you think about moving these methods to `TachyonBlockManager`? one is unused and the other is used only in that class. I understand Tachyon deps are already part of core, but, it seems funny to have them show up in the common `Utils` class. Along the way we have to either fix the bug in the `has` method or delete it, yes.

**Pull request closed without merging**
