### PR TITLE
Set null as default value for TaskContextImpl#taskMemoryManager

### PR DESCRIPTION
**Pull request by tedyu**
@JoshRosen 
Please take a look.

### CODE REVIEW

**Comment by rxin** [comment]
Jenkins, add to whitelist.

**Comment by JoshRosen** [comment]
@rxin I think the motivation for this was to minimize some changes to rest code.  If we're going to make this change, shouldn't we also back out the test related changes from my patch in order to benefit from the reduced merge conflicts?

**Comment by rxin** [comment]
(I was simply adding Ted to the whitelist so he wouldn't need to wait for us to start jenkins)

**Comment by rxin** [comment]
@tedyu  I'm not sure how useful this change is, as it might make it easier to get null pointer exception?

**Comment by tedyu** [comment]
From what I can tell (e.g. JavaAPISuite), null taskMemoryManager is passed in existing tests.
This doesn't seem to increase the chance of NPE.

I agree with Josh that tests should make use of this default value.

**Comment by rxin** [comment]
But this increases the chance of NPE for non-test code added from now on, doesn't it?

**Comment by tedyu** [comment]
I found two places where taskMemoryManager is used:
DAGScheduler#runLocallyWithinThread()
Executor#run()
taskMemoryManager is constructed in both places.

See if I missed any reference.

**Comment by rxin** [comment]
The focus of my comment was on "from now on"... not existing code.

**Comment by tedyu** [comment]
Right.

**Pull request closed without merging**
