### PR TITLE
[SPARK-38560][SQL] If `Sum`, `Count`, `Any` accompany with distinct, cannot do partial agg push down.

### PR DESCRIPTION
**Pull request by beliefer**
### What changes were proposed in this pull request?
Spark could partial push down sum(distinct col), count(distinct col) if data source have multiple partitions, and Spark will sum the value again.
So the result may not correctly.

### Why are the changes needed?
Fix the bug push down sum(distinct col), count(distinct col) to data source and return incorrect result.

### Does this PR introduce _any_ user-facing change?
'Yes'.
Users will see the correct behavior.

### How was this patch tested?
New tests.

### CODE REVIEW

**Comment by beliefer** [comment]
ping @huaxingao cc @cloud-fan

**Comment by cloud-fan** [comment]
I don't think it's a problem of JDBC v2. It's a problem of the pushdown framework. Distinct aggregate functions have very special planning rule and it's very complicated to do partial pushdown.

My suggestion is to only do complete pushdown if there exists distinct aggregate functions, in the pushdown framework.

**Comment by beliefer** [comment]
> My suggestion is to only do complete pushdown if there exists distinct aggregate functions, in the pushdown framework.
OK. The pushdown framework only do complete pushdown if there exists distinct aggregate functions now.

**Review by cloud-fan — APPROVED** [review]

**Comment by cloud-fan** [comment]
thanks, merging to master/3.3!

**Comment by beliefer** [comment]
@cloud-fan Thank you very much!

**Pull request closed without merging**
