### PR TITLE
[SPARK-27577][MLlib] Correct thresholds downsampled in BinaryClassificationMetrics

### PR DESCRIPTION
**Pull request by shishaochen**
## What changes were proposed in this pull request?

Choose the last record in chunks when calculating metrics with downsampling in `BinaryClassificationMetrics`.

## How was this patch tested?

A new unit test is added to verify thresholds from downsampled records.

### CODE REVIEW

**Comment by shishaochen** [comment]
@srowen Could you please have a look at this pull request? Thanks a lot!

**Comment by srowen** [comment]
This doesn't look like a bug. I can't understand the argument in the JIRA why the last vs first element of a bin is more representative. Both are approximations.

**Comment by shishaochen** [comment]
@srowen Yes, both are approximations. But it has less error if we choose the last element in each chunk as the threshold.
And the essential problem is that, the so-called "downsampling" is not real sampling. The [code behind](https://github.com/apache/spark/blob/master/mllib/src/main/scala/org/apache/spark/mllib/evaluation/BinaryClassificationMetrics.scala#L196) calculates AUC based on statistics (like TP, NP, TF, NF) of all elements.
```scala
counts.mapPartitions(_.grouped(grouping.toInt).map { pairs =>
  // The score of the combined point will be just the first one's score
  val firstScore = pairs.head._1
  // The point will contain all counts in this chunk
  val agg = new BinaryLabelCounter()
  pairs.foreach(pair => agg += pair._2)
  (firstScore, agg)
})
```
You can see, counters (`BinaryLabelCounter`) of all elements are merged into one instead of return the first element directly.
Thus, from the definition of `threshold`, the score of the last element (which is the minimal one) is the right threshold to use when inference.
In online systems, we need choose the right threshold to predict whether an instance is positive (`score>=threshold`) or negative (`score<threshold`).

**Comment by srowen** [comment]
I still don't see the argument that the first or last is better. They are simply the endpoints of the range of scores within the bin. As the number of bins increases, the range is smaller. If you are worried about this difference, you need more bins. Your argument cuts two ways: having a slightly higher threshold than desired can cause as many problems as slightly negative.

What would be possibly better here is to compute the score of a bin as a weighted average of its elements. That would be OK though you'd have to change many tests. I think the current implementation is designed to match scikit (?)

**Comment by shishaochen** [comment]
@srowen Get your point!
Actually, if we choose score of the last element in each chunk as threshold, the calculated Recall, Precision, FMeasure on each threshold are exactly the same as those when no sampling (`numBins=0`).
In other words, **they are accurate metrics**. The only difference is the count of thresholds when printing precision/recall/f1 curve compared to downsampling.
Thus, why not return the correct metrics of full data set but approximate values?

**Comment by srowen** [comment]
Ah OK I agree with you, I see the argument now. It comes from the fact that the scores are sorted _descending_. The score of each bin is currently its maximum, not minimum. The precision / recall for each bin is calculated as if all of the instances in the bin were classified as positive. This only makes sense if the score is the minimum.

You might mention something to this effect in the comment in the code.
Also I think this may change some test results; let's see.

**Comment by shishaochen** [comment]
@srowen Great thanks for your patience!
I have added explanation in code comments at [BinaryClassificationMetrics.scala](https://github.com/apache/spark/pull/24470/commits/147f239b47e7317d9a4454820a4e099c98c536dc). Do these following words match your expectations?
```scala
counts.mapPartitions(_.grouped(grouping.toInt).map { pairs =>
  // The score of the combined point will be just the last one's score, which is also
  // the minimal in each chunk since all scores are already sorted in descending.
  val lastScore = pairs.last._1
  // The combined point will contain all counts in this chunk. Thus, calculated
  // metrics (like precision, recall, etc.) on its score (or so-called threshold) are
  // the same as those without sampling.
  val agg = new BinaryLabelCounter()
  pairs.foreach(pair => agg += pair._2)
  (lastScore, agg)
})
```
Besides, I have scanned all unit tests and class references in the Spark code repository. None of them uses `numBins` but one unit test [BinaryClassificationMetricsSuite](https://github.com/apache/spark/blob/master/mllib/src/test/scala/org/apache/spark/mllib/evaluation/BinaryClassificationMetricsSuite.scala#L172), which only tests the ROC curve without threshold. Thus, it is safe to merge this pull request.

**Review by srowen — APPROVED** [review]

**Comment by shishaochen** [comment]
@srowen Execuse me, is there anything I should do before merging this pull request? Thanks a lot!

**Comment by srowen** [comment]
No, I leave these open for a day or two to make sure there aren't more comments.

**Comment by srowen** [comment]
Merged to master/2.4/2.3

**Pull request closed without merging**
