### PR TITLE
[SPARK-42823][SQL] `spark-sql` shell supports multipart namespaces for initialization

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

Currently, we only support initializing spark-sql shell with a single-part schema, which also must be forced to the session catalog.

#### case 1, specifying catalog field for v1sessioncatalog
```sql
bin/spark-sql --database spark_catalog.default

Exception in thread "main" org.apache.spark.sql.catalyst.analysis.NoSuchDatabaseException: Database 'spark_catalog.default' not found
```

#### case 2, setting the default catalog to another one

```sql
bin/spark-sql -c spark.sql.defaultCatalog=testcat -c spark.sql.catalog.testcat=org.apache.spark.sql.execution.datasources.v2.jdbc.JDBCTableCatalog -c spark.sql.catalog.testcat.url='jdbc:derby:memory:testcat;create=true' -c spark.sql.catalog.testcat.driver=org.apache.derby.jdbc.AutoloadedDriver -c spark.sql.catalogImplementation=in-memory  --database SYS
23/03/16 18:40:49 WARN ObjectStore: Failed to get database sys, returning NoSuchObjectException
Exception in thread "main" org.apache.spark.sql.catalyst.analysis.NoSuchDatabaseException: Database 'sys' not found

```
In this PR, we switch to use-statement to support multipart namespaces, which helps us resovle
to catalog correctly.

### Why are the changes needed?

Make spark-sql shell better support the v2 catalog framework.

### Does this PR introduce _any_ user-facing change?

Yes, `--database` option supports multipart namespaces and works for v2 catalogs now. And you will see this behavior on spark web ui.

### How was this patch tested?

new ut

### CODE REVIEW

**Comment by yaooqinn** [comment]
cc @HyukjinKwon @cloud-fan @dongjoon-hyun, thanks

**Comment by dongjoon-hyun** [comment]
Thank you for pinging me, @yaooqinn .

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. It looks like worthy to bring to Apache Spark 3.4.0.
Merged to master/3.4.

**Comment by yaooqinn** [comment]
thank you @dongjoon-hyun

**Comment by dongjoon-hyun** [comment]
You're welcome!

**Comment by cloud-fan** [comment]
late LGTM

**Pull request closed without merging**
