### PR TITLE
Revert "[SPARK-33861][SQL] Simplify conditional in predicate"

### PR DESCRIPTION
**Pull request by wangyum**
This reverts commit 32d4a2b and 3aa4e11.

### CODE REVIEW

**Review by cloud-fan — APPROVED** [review]

**Review by HyukjinKwon — APPROVED** [review]

**Comment by wangyum** [comment]
Merged to master, branch-3.3 and branch-3.2

**Comment by dongjoon-hyun** [comment]
Thank you for reverting, @wangyum .

**Comment by dongjoon-hyun** [comment]
Sorry, but I missed that this is an ancient patch. To @wangyum , we need a new JIRA when we revert already released patches.

**Comment by wangyum** [comment]
OK. https://issues.apache.org/jira/browse/SPARK-40493

**Comment by dongjoon-hyun** [comment]
Thank you, @wangyum .

**Pull request closed without merging**
