### PR TITLE
[SPARK-15485] [SQL] [DOCS] Spark SQL Configuration

### PR DESCRIPTION
**Pull request by gatorsmile**
#### What changes were proposed in this pull request?

So far, the page Configuration in the official documentation does not have a section for Spark SQL. 
http://spark.apache.org/docs/latest/configuration.html

For Spark users, the information and default values of these public configuration parameters are very useful. This PR is to add this missing section to the configuration.html.

@rxin @yhuai @marmbrus 
#### How was this patch tested?

Below is the generated webpage. 
screenshot 2016-05-23 11 35 57
screenshot 2016-05-23 11 37 38
screenshot 2016-05-23 11 36 11
screenshot 2016-05-23 11 36 18

### CODE REVIEW

**Comment by rxin** [comment]
It's good to document, but I think things like these will go stale very quickly and become inconsistent. For SQL, don't we already have a command that returns the list of documented config options? Why not just ask users to run that?

If the command doesn't work, we should fix it.

**Comment by gatorsmile** [comment]
uh, I see. We have a command `set -v`, which returns all the public SQL configuration with the current values and descriptions. 

Let me change it and document this command in this Configuration page.

**Comment by gatorsmile** [comment]
@rxin How about the current version?

**Comment by rxin** [comment]
Merging in master/2.0. Thanks.

**Pull request closed without merging**
