### PR TITLE
Fix run-tests.py typos

### PR DESCRIPTION
**Pull request by wjur**
## What changes were proposed in this pull request?

The PR fixes typos in an error message in dev/run-tests.py.

### CODE REVIEW

**Comment by srowen** [comment]
"Can't" isn't a typo; the other one is. This is pretty trivial, but hey.

**Comment by srowen** [comment]
Jenkins test this please

**Comment by wjur** [comment]
Ok, I know, my other intention was to unify it with the rest of the messages (other messages use "cannot" instead of "can't").

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
