### PR TITLE
SPARK-2285 [CORE] Give various TaskEndReason subclass more descriptive names

### PR DESCRIPTION
**Pull request by srowen**
Was this all that you had in mind @rxin -- just a rename? or did I miss the point. The other subclasses look fairly descriptive as class names go, like `TaskKilled`.

### CODE REVIEW

**Comment by rxin** [comment]
This is what I had in mind. @andrewor14 can you comment on whether this will break the event log stuff?

**Comment by andrewor14** [comment]
Yeah, this breaks backward compatibility if people are trying to parse old event logs with this version of Spark. We'll need to parse the string `Success` as well in `taskEndReasonFromJson`. If you do this then it would be good to add a backwards compatibility test in JsonProtocolSuite.

**Comment by srowen** [comment]
Hm, I wonder if it's worth it then, just for a rename from Success to TaskSucceeded?

**Comment by rxin** [comment]
Hmm, maybe it is not worth it in this case. Maybe for Spark 2.0 we can just do the rename :)

**Comment by andrewor14** [comment]
Ok, let's close this issue then. :)

**Pull request closed without merging**
