### PR TITLE
[SPARK-30303][SQL] Fix match error in percentile function when the percentage is null

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

Similar to #26905

```sql
spark-sql> select percentile(1, null);
19/12/19 16:35:04 ERROR SparkSQLDriver: Failed in [select percentile(1, null)]
scala.MatchError: null


spark-sql> select percentile(1, array(0.0, null)); -- null is illegal but treat as zero
``` 

### Why are the changes needed?
bugfix

### Does this PR introduce any user-facing change?

yes, select percentile(1, null); throws AnalysisException instead.

### How was this patch tested?

add ut

### CODE REVIEW

**Comment by yaooqinn** [comment]
cc @cloud-fan the problem of percentile is similar to percentile_approx

**Comment by srowen** [comment]
Let's fix it in one JIRA/PR if they're this related

**Comment by dongjoon-hyun** [comment]
+1 for @srowen 's advice.

**Comment by maropu** [comment]
+1, too, for easy-to-reviews.

**Comment by yaooqinn** [comment]
merged to https://github.com/apache/spark/pull/26905, thanks for your suggestions.

**Pull request closed without merging**
