### PR TITLE
[MINOR][UI] Fix Duration tips of Stage Table on UI

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

After https://github.com/apache/spark/commit/c07a50b86254578625be777b1890ff95e832ac6e the duration of a stage on UI does not display as stage `completion time - submission time`, the `completion time - 1st task launch time`.

In this PR, we fix the tips to prevent misleading.

### Why are the changes needed?

the description of Stage Duration confuses me for a long time as it is not consistent with the job duration if the job has one stage only.

### Does this PR introduce _any_ user-facing change?

yes, UI changes.

### How was this patch tested?

Passing GA

### CODE REVIEW

**Comment by yaooqinn** [comment]
cc @cloud-fan @Ngone51

**Comment by cloud-fan** [comment]
looks reasonable. @Ngone51 can you signoff this?

**Review by Ngone51 — APPROVED** [review]
LGTM

**Comment by Ngone51** [comment]
Thanks, merged to master!

**Pull request closed without merging**
