### PR TITLE
[SPARK-8638] [SQL] Window Function Performance Improvements - Cleanup

### PR DESCRIPTION
**Pull request by hvanhovell**
This PR contains a few clean-ups that are a part of SPARK-8638: a few style issues got fixed, and a few tests were moved.

Git commit message is wrong BTW :(...

### CODE REVIEW

**Comment by hvanhovell** [comment]
cc @yhuai

**Comment by yhuai** [comment]
ok to test






On Sun, Jul 19, 2015 at 9:02 AM -0700, "UCB AMPLab" <notifications@github.com> wrote:












Can one of the admins verify this patch?

**Comment by hvanhovell** [comment]
@yhuai Don't think jenkins picked up your OK.

**Comment by yhuai** [comment]
ok to test

**Comment by yhuai** [comment]
ah, I guess it is because I replied through email. Let's see if jenkins gets it this time.

**Comment by yhuai** [comment]
LGTM. Will merge it to master once it passes jenkins.

**Comment by yhuai** [comment]
I am merging it to master.

**Pull request closed without merging**
