### PR TITLE
[SPARK-44863][UI][FOLLOWUP] Move Mima rules to v40excludes

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

Move Mima rules added by SPARK-44863 to v40excludes

### Why are the changes needed?

SPARK-44863 is targeting 4.0 eventually

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

mima tests

### Was this patch authored or co-authored using generative AI tooling?

no

### CODE REVIEW

**Comment by yaooqinn** [comment]
cc @dongjoon-hyun @zhengruifeng

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you so much, @yaooqinn .

**Review by LuciferYang — APPROVED** [review]

**Review by zhengruifeng — APPROVED** [review]

**Review by HyukjinKwon — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Merged to master.

**Comment by yaooqinn** [comment]
thanks @dongjoon-hyun @LuciferYang @HyukjinKwon @zhengruifeng

**Pull request closed without merging**
