### PR TITLE
[MINOR] Close old PRs that should be closed but have not been

### PR DESCRIPTION
**Pull request by srowen**
Closes #11598 
Closes #7278 
Closes #13882 
Closes #12053 
Closes #14125 
Closes #8760 
Closes #12848 
Closes #14224

### CODE REVIEW

**Comment by rxin** [comment]
LGTM

**Comment by rxin** [comment]
Merging in master.

**Comment by rxin** [comment]
Actually I'm having trouble with the merge script. You should merge this yourself.

**Comment by srowen** [comment]
Yeah you have to temporarily add `--allow-empty` to the commit command in the merge script. I didn't try to add it permanently as it might accidentally allow something we don't want to happen, but who knows.

**Pull request closed without merging**
