### PR TITLE
[SPARK-24801][CORE] Avoid memory waste by empty byte[] arrays in SaslEncryption$EncryptedMessage

### PR DESCRIPTION
**Pull request by countmdm**
## What changes were proposed in this pull request?

Initialize SaslEncryption$EncryptedMessage.byteChannel lazily,
so that empty, not yet used instances of ByteArrayWritableChannel
referenced by this field don't use up memory.

I analyzed a heap dump from Yarn Node Manager where this code is used, and found that there are over 40,000 of the above objects in memory, each with a big empty byte[] array. The reason they are all there is because of Netty queued up a large number of messages in memory  before transferTo() is called. There is a small number of netty ChannelOutboundBuffer objects, and then collectively , via linked lists starting from their flushedEntry data fields, they end up referencing over 40K ChannelOutboundBuffer$Entry objects, which ultimately reference EncryptedMessage objects.

## How was this patch tested?

Ran all the tests locally.

### CODE REVIEW

**Comment by countmdm** [comment]
Yes.

**Comment by squito** [comment]
Ok to test

**Comment by squito** [comment]
can you add something in the PR description about how this is important because sometimes many of these messages queue up in netty's ChannelOutboundBuffer before transferTo() is called?  its discussed in the jira, but good to have here too

**Comment by squito** [comment]
@zsxwing @jerryshao @Victsm you might be interested in this

**Review by felixcheung — COMMENTED** [review]
I like it, but this will still create the byte channel right? is there a way to reuse it?

**Comment by kiszk** [comment]
Does it make sense to release `byteChannel` at `deallocate()`?
```
if (byteChannel != null) {
  byteChannel = null;
}
```

**Comment by squito** [comment]
> I like it, but this will still create the byte channel right? is there a way to reuse it?

we could create a pool, though management becomes a bit more complex.  would you ever shrink the pool, or would it always stay the same size?  I guess it shouldn't grow more than 1 byte array per io thread.

I'd rather get this simple fix in first before doing anything more complicated ...

**Comment by squito** [comment]
> Does it make sense to release byteChannel at deallocate()?

you could, just to let GC kick in a *bit* earlier, but I don't think its going to make a big difference.  (Netty's ByteBufs must be since they may be owned by netty's internal pools and never gc'ed)

**Comment by kiszk** [comment]
I see. SGTM.
Would it be possible to attach heap profiling (allocated size for each type) before and after this PR to record the difference?

**Comment by countmdm** [comment]
Thank you very much for your responses, @squito. I agree with all you said.

@kiszk the heap dump that prompted me to make this change was obtained from a customer, who probably ran into some unusual situation. So, not being a spark expert, I am not sure how to reproduce this problem. Of course, normally I am all for measuring the app's memory before and after the change to make sure it worked.

**Comment by kiszk** [comment]
@countmdm I see. We may be interested in ratio regarding `byte[] / all allocated memory` before and after. Not interested in other objects (e.g. an object including customer's name).

**Comment by countmdm** [comment]
@kiszk the situation "before" is well understood. In the respective SPARK-24801 ticket I present a fragment from the analysis of this heap dump by jxray (www.jxray.com). It shows that ~2.5GB of memory, or 64% of the used heap size, is wasted by ~40.5 thousand emtpty byte[] arrays in question:

2,597,946K (64.1%): byte[]: 40583 / 100% of empty 2,597,946K (64.1%)
↖org.apache.spark.network.util.ByteArrayWritableChannel.data
↖org.apache.spark.network.sasl.SaslEncryption$EncryptedMessage.byteChannel
↖io.netty.channel.ChannelOutboundBuffer$Entry.msg
...

However, we don't, and probably cannot, get the real "after" evidence. That's because, as I said, I don't know how to reproduce the situation in house. And I think it's very unlikely that the customer can easily reproduce it either, let alone accept our patched code and collect the necessary data before and after the fix. However, I believe this fix is simple and obvious enough, and thus we can be pretty sure that with it, in the above situation there would simply be no problematic byte[] arrays anymore, and memory consumption will be 64% smaller.

**Comment by kiszk** [comment]
@countmdm Sorry for overlooking the JIRA description. I got the situation.
While the memory pool could be, it is too complex.

LGTM

**Comment by felixcheung** [comment]
SGTM

________________________________

**Comment by squito** [comment]
lgtm

will wait a bit for any more comments before merging

**Comment by dongjoon-hyun** [comment]
+1, LGTM, too.

**Comment by squito** [comment]
merged to master, thanks!

**Pull request closed without merging**
