### PR TITLE
[SPARK-38566][SQL][3.3] Revert the parser changes for DEFAULT column support

### PR DESCRIPTION
**Pull request by MaxGekk**
### What changes were proposed in this pull request?
Revert the commit https://github.com/apache/spark/commit/e21cb62d02c85a66771822cdd49c49dbb3e44502 from `branch-3.3`.

### Why are the changes needed?
See discussion in the PR https://github.com/apache/spark/pull/35690.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
By existing test suites.

### CODE REVIEW

**Comment by MaxGekk** [comment]
@HyukjinKwon This is the PR created from scratch, but still GAs are not triggered.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @MaxGekk . Pending CI.

I'm also not sure about the reason why the CI is not triggered here.

**Comment by dongjoon-hyun** [comment]
cc @dtenedor and @gengliangwang , too

**Comment by gengliangwang** [comment]
Actually having this in 3.3 can return a better error message if users are running queries with column default.
I am fine with either way, keep it or revert it. It's up to @MaxGekk

**Review by gengliangwang — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
We agreed on reverting already, @gengliangwang . :)

**Comment by gengliangwang** [comment]
Thanks, merging to 3.3

**Comment by MaxGekk** [comment]
@gengliangwang FYI, GAs haven't been triggered yet.

**Comment by gengliangwang** [comment]
@dongjoon-hyun Yes
@MaxGekk yes I found it and deleted my comment :)

**Comment by HyukjinKwon** [comment]
It's passed at https://github.com/MaxGekk/spark/runs/5581819136?check_suite_focus=true so we can merge it anyway

**Comment by HyukjinKwon** [comment]
Will make a fix soon.

**Comment by MaxGekk** [comment]
Merging to branch-3.3. Thank you, @gengliangwang @dongjoon-hyun and @HyukjinKwon for review.

**Pull request closed without merging**
