### PR TITLE
[SPARK-47057][PYTHON] Reeanble MyPy data test

### PR DESCRIPTION
**Pull request by HyukjinKwon**
### What changes were proposed in this pull request?

This is a followup of https://github.com/apache/spark/pull/45115 that enables MyPy data test.

### Why are the changes needed?

To reenable MyPy data test.

### Does this PR introduce _any_ user-facing change?

No, test-only.

### How was this patch tested?

Manually ran the test via `./dev/lint-python`.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM (if CI passes)

**Comment by dongjoon-hyun** [comment]
It seems that there are more leftover~ Could you take a look at them?

**Comment by ueshin** [comment]
We should also upgrade the minimum version?

https://github.com/apache/spark/blob/3901c6e1c63f300066847ae9393a8b424d7bb0c0/dev/lint-python#L21

**Comment by HyukjinKwon** [comment]
Ah .. the results depend on Python version. Let me fix.

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
