### PR TITLE
[SPARK-27640][SQL][SS] Avoid duplicate lookups for datasource through provider

### PR DESCRIPTION
**Pull request by beliefer**
## What changes were proposed in this pull request?

Spark SQL using code as follows to lookup datasource.
`DataSource.lookupDataSource(source, sparkSession.sqlContext.conf)`
But exists some duplicate call.
In simple terms, repeated calls don't seem to have big performance problems, but if you look at the details, you know that it includes some Java reflection.
AFAIK, Java reflection will result in significant performance issue.
The oracle website [https://docs.oracle.com/javase/tutorial/reflect/index.html](https://docs.oracle.com/javase/tutorial/reflect/index.html) contains some performance description about Java reflection:

```
Performance Overhead
Because reflection involves types that are dynamically resolved, certain Java virtual machine optimizations can not be performed. Consequently, reflective operations have slower performance than their non-reflective counterparts, and should be avoided in sections of code which are called frequently in performance-sensitive applications.
```

I have found some performance cost test of Java reflection as follows:
[https://blog.frankel.ch/performance-cost-of-reflection/](https://blog.frankel.ch/performance-cost-of-reflection/) contains performance cost test.
[https://stackoverflow.com/questions/435553/java-reflection-performance](https://stackoverflow.com/questions/435553/java-reflection-performance) has a discussion of java reflection.

## How was this patch tested?

Exists UT.

### CODE REVIEW

**Comment by beliefer** [comment]
cc @srowen @cloud-fan

**Comment by cloud-fan** [comment]
thanks for improving it! I think it's a valid change but I'm not sure if it's worth this 40 LOC change just to save duplicated lookup.

**Comment by beliefer** [comment]
> thanks for improving it! I think it's a valid change but I'm not sure if it's worth this 40 LOC change just to save duplicated lookup.

Although there are 40 changes here, they are very easy to understand.

**Comment by gaborgsomogyi** [comment]
Today I've had time and made a deeper look. As cloud-fan said the change itself looks correct but I can't say it would make the code more readable.

**Comment by beliefer** [comment]
> Today I've had time and made a deeper look. As cloud-fan said the change itself looks correct but I can't say it would make the code more readable.

Thanks for your review! Could you tell me reason affect readability?

**Comment by cloud-fan** [comment]
I don't see a big problem with this double lookup issue. It won't have any real performance problems and it only exists in data source v1.

That said, I don't have a strong willing to merge this but I'm fine if others think it's worth to merge.

**Comment by beliefer** [comment]
> I don't see a big problem with this double lookup issue. It won't have any real performance problems and it only exists in data source v1.
> 
> That said, I don't have a strong willing to merge this but I'm fine if others think it's worth to merge.

In simple terms, repeated calls don't seem to have big performance problems, but if you look at the details, you know that it includes some `Java SPI`, traversing and reflection.
I think there exists a little performance problems.

**Comment by beliefer** [comment]
@srowen Could you help me review this PR, thanks!

**Comment by beliefer** [comment]
cc @srowen

**Comment by beliefer** [comment]
cc @dongjoon-hyun

**Comment by dongjoon-hyun** [comment]
Thank you for ping me, @beliefer . However, the reviewers' comment are consistent. And, I also agree that. AFAIK, you didn't provide more evidences for your claim about the performance problem. Without evidence, we can not make a progress. Could you investigate more and give us some numbers for your claim?
> you know that it includes some Java SPI, traversing and reflection.
> I think there exists a little performance problems.

**Comment by beliefer** [comment]
> Thank you for ping me, @beliefer . However, the reviewers' comments are consistent. And, I also agree with that. AFAIK, you didn't provide more evidences for your claim about the performance problem. Without evidence, we can not make a progress. Could you investigate more and give us some numbers for your claim?
> 
> > you know that it includes some Java SPI, traversing and reflection.
> > I think there exists a little performance problems.

Thanks for your reply. AFAIK, java reflection will result in significant performance issue.
The oracle website`https://docs.oracle.com/javase/tutorial/reflect/index.html` contains some description about performance:
```
Performance Overhead
Because reflection involves types that are dynamically resolved, certain Java virtual machine optimizations can not be performed. Consequently, reflective operations have slower performance than their non-reflective counterparts, and should be avoided in sections of code which are called frequently in performance-sensitive applications.
```
`https://blog.frankel.ch/performance-cost-of-reflection/` contains performance cost test.

**Pull request closed without merging**
