### PR TITLE
[SPARK-15148][SQL] Upgrade Univocity library from 2.0.2 to 2.1.0

### PR DESCRIPTION
**Pull request by HyukjinKwon**
## What changes were proposed in this pull request?

https://issues.apache.org/jira/browse/SPARK-15148

Mainly it improves the performance roughtly about 30%-40% according to the [release note](https://github.com/uniVocity/univocity-parsers/releases/tag/v2.1.0). For the details of the purpose is described in the JIRA.

This PR upgrades Univocity library from 2.0.2 to 2.1.0. 
## How was this patch tested?

Existing tests should cover this.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @rxin and @jbax (who is the author of Univocity library and suggested this change).

**Comment by rxin** [comment]
LGTM pending Jenkins.

**Comment by holdenk** [comment]
So doing a quick grep shows that we are using the newly deprecated method `setParseUnescapedQuotes` and `setParseUnescapedQuotesUntilDelimiter`, we should update to `setUnescapedQuoteHandling` as per the release notes ( https://github.com/uniVocity/univocity-parsers/releases )

If its really urgent to get this upgrade in quickly, lets make a follow up JIRA to move away from these deprecated functions for the next release.

**Comment by HyukjinKwon** [comment]
Thanks, @holdenk! It is not urgent. I can do this in this PR.

**Comment by holdenk** [comment]
Great!

**Comment by srowen** [comment]
LGTM, except that it needs a rebase now

**Comment by rxin** [comment]
Merging in master/branch-2.0.

**Pull request closed without merging**
