### PR TITLE
[SPARK-41636][SQL] Make sure `selectFilters` returns predicates in deterministic order

### PR DESCRIPTION
**Pull request by Hisoka-X**
### What changes were proposed in this pull request?
Method `DataSourceStrategy#selectFilters`, which is used to determine "pushdown-able" filters, does not preserve the order of the input Seq[Expression] nor does it return the same order across the same plans. This is resulting in CodeGenerator cache misses even when the exact same LogicalPlan is executed. 

This PR to make sure `selectFilters` returns predicates in deterministic order.

### Why are the changes needed?
Make sure `selectFilters` returns predicates in deterministic order, to reduce the probability of codegen cache misses.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
add new test.

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]
Making sense to me

**Review by viirya — APPROVED** [review]
Good point.

**Comment by HyukjinKwon** [comment]
Merged to master and branch-3.5.

**Comment by cloud-fan** [comment]
late LGTM

**Pull request closed without merging**
