### PR TITLE
[SPARK-31267][SQL] Flaky test: WholeStageCodegenSparkSubmitSuite.Generated code on driver should not embed platform-specific constant

### PR DESCRIPTION
**Pull request by tianshizz**
### What changes were proposed in this pull request?

Allow customized timeouts for `runSparkSubmit`, which will make flaky tests more likely to pass by using a larger timeout value.

I was able to reproduce the test failure on my laptop, which took 1.5 - 2 minutes to finish the test. After increasing the timeout, the test now can pass locally.

### Why are the changes needed?

This allows slow tests to use a larger timeout, so they are more likely to succeed.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

The test was able to pass on my local env after the change.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
ok to test

**Comment by tianshizz** [comment]
cc @gatorsmile @dbtsai

**Comment by maropu** [comment]
Thanks for the work, @tianshizz . btw, have you checked a root cause of the flaky failure is just a timeout, e.g., from jenkins logs?

**Comment by tianshizz** [comment]
@maropu I'm not able to see the jenkins log, but I was able to reproduce it on my own laptop, which is quite slow... It needs 1.5 - 2 minutes to finish that test. After increasing the timeout to 3 minutes, it can pass.

**Comment by maropu** [comment]
retest this please

**Review by maropu — APPROVED** [review]

**Comment by maropu** [comment]
Could you put the info ` It needs 1.5 - 2 minutes to finish that test` in the PR description, too?

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master and branch-3.0.

**Pull request closed without merging**
