### PR TITLE
[SPARK-8148] Do not use FloatType in partition column inference.

### PR DESCRIPTION
**Pull request by rxin**
Use DoubleType instead to be more stable and robust.

### CODE REVIEW

**Comment by rxin** [comment]
cc @liancheng

**Comment by rxin** [comment]
The other thing we should consider, although I'm less sure about, is whether we should skip IntegerType and go straight to LongType.

**Comment by liancheng** [comment]
I'm worrying about skipping `FloatType` (and possibly `IntegerType`) might break existing user code because the partition column data types gets changed. Especially when the inferred schema gets persisted in places like Parquet file metadata and metastore.

**Comment by rxin** [comment]
If it is persisted in the metastore, then inference is no longer used, isn't it?

And why would partition columns be stored in Parquet file metadata?

**Comment by liancheng** [comment]
Had offline discussion with @rxin. There can be rare corner cases where compatibility issues may arise. However, stop using `FloatType` in this case can eliminate these corner cases. So we would like to have this and add a note in release notes.

**Pull request closed without merging**
