### PR TITLE
[SPARK-15364][ML][PySpark] Implement PySpark picklers for ml.Vector and ml.Matrix under spark.ml.python

### PR DESCRIPTION
**Pull request by viirya**
## What changes were proposed in this pull request?

Now we have PySpark picklers for new and old vector/matrix, individually. However, they are all implemented under `PythonMLlibAPI`. To separate spark.mllib from spark.ml, we should implement the picklers of new vector/matrix under `spark.ml.python` instead.
## How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by viirya** [comment]
retest this please.

**Comment by mengxr** [comment]
@viirya I think we need a test for the picklers. See https://github.com/apache/spark/blob/master/mllib/src/test/scala/org/apache/spark/mllib/api/python/PythonMLLibAPISuite.scala#L29.

**Comment by viirya** [comment]
@mengxr the tests are added. Please take a look if you have time. Thanks.

**Comment by viirya** [comment]
retest this please.

**Comment by viirya** [comment]
ping @mengxr

**Comment by viirya** [comment]
ping @mengxr Any more comments? Thanks!

**Comment by mengxr** [comment]
LGTM. Merged into master and branch-2.0. Thanks!

**Comment by viirya** [comment]
@mengxr Thank you.

**Pull request closed without merging**
