### PR TITLE
[SPARK-41824][CONNECT][PYTHON] Ingore the doctest for explain of connect

### PR DESCRIPTION
**Pull request by beliefer**
### What changes were proposed in this pull request?
Currently, the output of explain API is different between pyspark, scala and connect.
There already created a dataframe with
`df = spark.createDataFrame([(14, "Tom"), (23, "Alice"), (16, "Bob")], ["age", "name"]) `
and then execute
`df.explain()`
The output of pyspark show below.
```
    == Physical Plan ==
    *(1) Scan ExistingRDD[age...,name...]
```
But the scala and connect API output different content.
```
    == Physical Plan ==
    LocalTableScan [age#1148L, name#1149]
    <BLANKLINE>
    <BLANKLINE>
```
The similar issue occurs when executing `df.explain(mode="formatted")` too.

It's actually implementation details in PySpark. It would be difficult to make it matched. So this PR want ignore the two doc tests.

### Why are the changes needed?
Currently, the output of explain API is different between pyspark, scala and connect.
This PR want ignore the two doc tests.

### Does this PR introduce _any_ user-facing change?
'No'.
New feature.

### How was this patch tested?
Manual tests.

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]
Let's remove the comment with the JIRA number too. LGTM otherwise.

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by zhengruifeng** [comment]
LGTM, thank you @beliefer 

the df in PySpark will create a RDD at first, which can not be matched in Connect

**Comment by beliefer** [comment]
@HyukjinKwon @zhengruifeng Thank you!

**Pull request closed without merging**
