### PR TITLE
[SPARK-32462][WEBUI] Reset previous search text for datatable

### PR DESCRIPTION
**Pull request by sarutak**
### What changes were proposed in this pull request?

This PR proposes to change the behavior of DataTable for stage-page and executors-page not to save the previous search text.

### Why are the changes needed?

DataTable is used in stage-page and executors-page for pagination and filter tasks/executors by search text.
In the current implementation, search text is saved so if we visit stage-page for a job, the previous search text is filled in the textbox and the task table is filtered.
I'm sometimes surprised by this behavior as the stage-page lists no tasks because tasks are filtered by the previous search text.
I think, it's not useful.

### Does this PR introduce _any_ user-facing change?

Yes. Search text is no longer saved.

### How was this patch tested?

New testcase with the following command.
```
$ build/sbt -Dguava.version=27.0-jre -Dtest.default.exclude.tags= -Dspark.test.webdriver.chrome.driver=/path/to/chromedriver "testOnly org.apache.spark.ui.ChromeUISeleniumSuite -- -z Search"
```

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. I agree with the purpose described by @sarutak . Keeping search text is a kind of UX feature to reduce re-typing, but I believe we can remove it from Apache Spark 3.1.0 to achieve simplicity by preventing user confusions.

Also, I verified this PR manually.

cc @gengliangwang , @gatorsmile

**Comment by dongjoon-hyun** [comment]
Merged to master for Apache Spark 3.1.0 on December 2020.

**Comment by sarutak** [comment]
@dongjoon-hyun 
> Keeping search text is a kind of UX feature to reduce re-typing, but I believe we can remove it from Apache Spark 3.1.0 to achieve simplicity by preventing user confusions.

I see. Thank you for the notification.

**Pull request closed without merging**
