### PR TITLE
[MINOR][UI] Correct JobPage's skipped/pending tableHeaderId

### PR DESCRIPTION
**Pull request by linzebing**
### What changes were proposed in this pull request?

Current Spark Web UI job page's header link of pending/skipped stages is inconsistent with their statuses. See the picture below:
image

### Why are the changes needed?

The code determining the `pendingOrSkippedTableId` has the wrong logic. As explained in the code:
> If the job is completed, then any pending stages are displayed as "skipped" [code pointer](https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/ui/jobs/JobPage.scala#L266)

This PR fixes the logic for `pendingOrSkippedTableId` which aligns with the stage statuses.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Verified that header link is consistent with stage status with the fix.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @sarutak and @gengliangwang FYI

**Comment by sarutak** [comment]
ok to test.

**Review by sarutak — APPROVED** [review]

**Comment by sarutak** [comment]
Though the screenshot seems to be from `2.4`, I confirmed that `master` also has this issue.
I verified the change with the following script.
```
val stage = sc.parallelize(1 to 10).map(x => (x, x)).reduceByKey(_ + _)
stage.collect
stage.map { x => {Thread.sleep(60000); x} }.reduceByKey(_ + _).collect
```

**Review by gengliangwang — APPROVED** [review]

**Comment by sarutak** [comment]
Merged to `master`, `branch-3.1`, `branch-3.0` and `branch-2.4`. Thanks @linzebing !

**Pull request closed without merging**
