### PR TITLE
[SPARK-5938][SQL] Generate Row from JSON string efficiently

### PR DESCRIPTION
**Pull request by viirya**
When we generate `Row` from JSON String, we zip the schema with index for every record and update current row's fields. That is inefficient.

This pr prepares the necessary functions for updating row's fields in advance, and reuses them for every row.

This pr also reuses a `GenericMutableRow`  instead of creating a new row for every record.

### CODE REVIEW

**Comment by viirya** [comment]
cc @marmbrus.

**Comment by viirya** [comment]
@marmbrus please take a look of this when you have time. Thanks!

**Comment by viirya** [comment]
@marmbrus do you have time to take a look of this?

**Comment by marmbrus** [comment]
Not until after the 1.3 release.

**Comment by liancheng** [comment]
@viirya Could you please add a brief overview of your update in the PR description? It's not only for the sake of code review. PR descriptions are merged into the Git history together with PRs, thus can be greatly helpful when tracking Git history. Thanks!

**Comment by viirya** [comment]
@liancheng Description is updated. Please take a look when you have time. Thanks!

**Comment by viirya** [comment]
@marmbrus @liancheng Please take time to review this. Thanks!

**Comment by marmbrus** [comment]
Sorry for the delay here.  Can you post a performance comparison?

/cc @yhuai

**Comment by viirya** [comment]
I have tried to compare the performance difference. However, no significant improvement can be found.

Data: 6000 rows of `complexFieldAndType1` in `TestJsonData`. Call `jsonRDD` to create two json RDDs.

old:
29 seconds, 714 milliseconds
29 seconds, 654 milliseconds
29 seconds, 590 milliseconds
29 seconds, 556 milliseconds
29 seconds, 461 milliseconds


new:
29 seconds, 272 milliseconds
29 seconds, 358 milliseconds
28 seconds, 991 milliseconds
29 seconds, 118 milliseconds
28 seconds, 926 milliseconds

Because this pr can't bring much performance improvement, I am closing it now.

**Pull request closed without merging**
