### PR TITLE
[SPARK-25673][BUILD] Remove Travis CI which enables Java lint check

### PR DESCRIPTION
**Pull request by HyukjinKwon**
## What changes were proposed in this pull request?

https://github.com/apache/spark/pull/12980 added Travis CI file mainly for linter because we disabled Java lint check in Jenkins.

It's enabled as of https://github.com/apache/spark/pull/21399 and now SBT runs it. Looks we can now remove the file added before.

## How was this patch tested?

N/A

Closes #22665

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @srowen and @dongjoon-hyun

**Review by srowen — APPROVED** [review]

**Review by felixcheung — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master and branch-2.4.

Thanks @srowen and @felixcheung.

**Review by dongjoon-hyun — COMMENTED** [review]
+1, late LGTM.

**Comment by dongjoon-hyun** [comment]
Thank you for taking care of this, @HyukjinKwon .

**Pull request closed without merging**
