### PR TITLE
[SPARK-29879][CORE]Support unbounded waiting for RPC reply

### PR DESCRIPTION
**Pull request by wenxuanguan**
### What changes were proposed in this pull request?

Support unbounded waiting for RPC reply with the call `RpcEndpointRef.askSync[T: ClassTag](message: Any, timeout: RpcTimeout)`

### Why are the changes needed?

At present, we hard code long duration to represent never timeout as below
```scala
timeout = new RpcTimeout(365.days, "barrierTimeout")
```
with the support of unbounded waiting, we can do as below
```scala
timeout = new RpcTimeout(Duration.Inf, "barrierTimeout")
```

### Does this PR introduce any user-facing change?

No

### How was this patch tested?

N/A

### CODE REVIEW

**Comment by jiangxb1987** [comment]
Do you really have a training job that runs over a year?

**Comment by wenxuanguan** [comment]
@jiangxb1987 Thanks for your reply.
> Do you really have a training job that runs over a year? 

No, but what I try to do is a way to not set a specific timeout value with `RpcEndpointRef.askSync()`, in the situation where never timeout until replied or interrupted by other event. 
Such as `BarrierTaskContext.barrier()` set a long timeout value which would not be reached, and a `SparkException` will be thrown by `BarrierCoordinator` on timeout.

**Comment by jiangxb1987** [comment]
sorry I'm not convinced this change is necessary.

**Comment by wenxuanguan** [comment]
@jiangxb1987 ok, and I will close the pr. Thanks for your review.

**Pull request closed without merging**
