### PR TITLE
[SPARK-45791][CONNECT][TESTS] Rename `SparkConnectSessionHodlerSuite.scala` to `SparkConnectSessionHolderSuite.scala`

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to fix a typo `Hodler` in file name.
- `SparkConnectSessionHodlerSuite.scala` (from)
- `SparkConnectSessionHolderSuite.scala` (to)

It's also unmatched with the class name in the file because class name itself is correct.

https://github.com/apache/spark/blob/3363c2af3f6a59363135451d251f25e328a4fddf/connector/connect/server/src/test/scala/org/apache/spark/sql/connect/service/SparkConnectSessionHodlerSuite.scala#L37

### Why are the changes needed?

This is a typo from the original PR.
- https://github.com/apache/spark/pull/41580

Since the original PR is shipped as Apache Spark 3.5.0, I created a JIRA instead of a follow-up. We need to backport this patch to `branch-3.5`.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the CIs.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
cc @HyukjinKwon and @rangadi

**Review by yaooqinn — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @yaooqinn ! Merged to master/3.5.

**Review by HyukjinKwon — COMMENTED** [review]
LGTM :-)

**Comment by rangadi** [comment]
Thanks for fixing this!

**Comment by juliuszsompolski** [comment]
Now that ReleaseSession exists, we don't HODL the session excessively anymore :-)

**Pull request closed without merging**
