### PR TITLE
[SPARK-18719] Add spark.ui.showConsoleProgress to configuration docs

### PR DESCRIPTION
**Pull request by nchammas**
This PR adds `spark.ui.showConsoleProgress` to the configuration docs.

I tested this PR by building the docs locally and confirming that this change shows up as expected.

Relates to #3029.

### CODE REVIEW

**Comment by nchammas** [comment]
cc @davies

**Review by srowen — APPROVED** [review]
Seems OK. You might add a little more prose if you're going to do this, lifted from the javadoc:

```
 * ConsoleProgressBar shows the progress of stages in the next line of the console. It poll the
 * status of active stages from `sc.statusTracker` periodically, the progress bar will be showed
 * up after the stage has ran at least 500ms. If multiple stages run in the same time, the status
 * of them will be combined together, showed in one line.
```

**Comment by nchammas** [comment]
@srowen - Good call. Will elaborate a bit based on what you posted.

**Comment by nchammas** [comment]
@srowen - OK, I elaborated a bit based on the snippet you posted. Feel free to nitpick on the wording. Would be happy to tweak further.

**Comment by davies** [comment]
lgtm, merging into master

**Comment by nchammas** [comment]
@davies - Should this also be cherry-picked into 2.0 and 2.1?

I think this config has been there for a while, just without documentation. 😊

**Pull request closed without merging**
