### PR TITLE
[SPARK-49801][FOLLOWUP][INFRA] Update `pandas` to 2.2.3 in `pages.yml` too

### PR DESCRIPTION
**Pull request by bjornjorgensen**
### What changes were proposed in this pull request?
Fix doc build.

### Why are the changes needed?
in https://github.com/apache/spark/pull/48269 

> Oh, this seems to break GitHub Action Jekyll.

https://github.com/apache/spark/actions/runs/11063509911/job/30742286270
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/sphinx/config.py", line 332, in eval_config_file
    exec(code, namespace)
  File "/home/runner/work/spark/spark/python/docs/source/conf.py", line 33, in <module>
    generate_supported_api(output_rst_file_path)
  File "/home/runner/work/spark/spark/python/pyspark/pandas/supported_api_gen.py", line 102, in generate_supported_api
    _check_pandas_version()
  File "/home/runner/work/spark/spark/python/pyspark/pandas/supported_api_gen.py", line 116, in _check_pandas_version
    raise ImportError(msg)
ImportError: Warning: pandas 2.2.3 is required; your version is 2.2.2"

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by bjornjorgensen** [comment]
Followup to https://github.com/apache/spark/pull/48269 
@yaooqinn @dongjoon-hyun

**Review by yaooqinn — APPROVED** [review]

**Comment by bjornjorgensen** [comment]
@yaooqinn should I call it "[FOLLOWUP][SPARK-49801][PYTHON][PS][BUILD] Update pandas to 2.2.3" ?

**Comment by yaooqinn** [comment]
The PR title LGTM

**Review by LuciferYang — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you.

To @bjornjorgensen , please don't reuse the original PR title in the followup. The PR title should describe what this PR aims to do.

**Pull request closed without merging**
