### PR TITLE
Revert "[SPARK-17549][SQL] Only collect table size stat in driver for cached relation."

### PR DESCRIPTION
**Pull request by yhuai**
This reverts commit 39e2bad6a866d27c3ca594d15e574a1da3ee84cc because of the problem mentioned at https://issues.apache.org/jira/browse/SPARK-17549?focusedCommentId=15505060&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15505060

### CODE REVIEW

**Comment by yhuai** [comment]
cc @vanzin

**Comment by vanzin** [comment]
If it's not too much trouble, keeping the workaround in CodeGenerator.scala would be nice. Otherwise LGTM.

**Comment by yhuai** [comment]
Oh, right. Will do that.






On Tue, Sep 20, 2016 at 8:57 AM -0700, "Marcelo Vanzin" <notifications@github.com> wrote:












If it's not too much trouble, keeping the workaround in CodeGenerator.scala would be nice. Otherwise LGTM.

**Comment by yhuai** [comment]
Done.

**Comment by yhuai** [comment]
I will merge this PR to master and branch 2.0 once it passes jenkins.

**Comment by yhuai** [comment]
@vanzin  I am merging this PR to master and branch 2.0

**Pull request closed without merging**
