### PR TITLE
[SPARK-2991] Implement RDD lazy transforms for scanLeft and scan

### PR DESCRIPTION
**Pull request by erikerlandson**
Discussion of implementations:
http://erikerlandson.github.io/blog/2014/08/09/implementing-an-rdd-scanleft-transform-with-cascade-rdds/
http://erikerlandson.github.io/blog/2014/08/12/implementing-parallel-prefix-scan-as-a-spark-rdd-transform/

### CODE REVIEW

**Comment by petro-rudenko** [comment]
+1 for this. Useful feature to calculate distributed cumulative sum.

**Comment by JoshRosen** [comment]
Any updates on this?  Will you publish this as part of Silex like you did with #1839?

**Comment by erikerlandson** [comment]
@JoshRosen, yes I plan on adding this to [silex](https://github.com/willb/silex) in the near future.   If you like I can close it.

**Comment by erikerlandson** [comment]
I migrated this PR to the 3rd party silex project:
https://github.com/willb/silex/pull/28

**Pull request closed without merging**
