### PR TITLE
[MINOR][BUILD] Add Scala 2.12 profile back for branch-2.4 build

### PR DESCRIPTION
**Pull request by dbtsai**

### CODE REVIEW

**Comment by dbtsai** [comment]
@vanzin @dongjoon-hyun

**Review by dongjoon-hyun — APPROVED** [review]
Oops. Yep. I missed this during reviewing https://github.com/apache/spark/pull/23931  .
Thank you, @dbtsai .

+1, LGTM.

**Review by srowen — APPROVED** [review]
I think this is OK. The scala-2.12 profile is a no-op in master, but it does exist.

**Comment by dbtsai** [comment]
@srowen although it's a no-op in master, but the current build script will fail in 2.4 branch. I am still debating should we use the script in master to build the release or the script in the branch to build the release. I feel it's very hard to maintain a script in master which works for previous version in branches.

**Comment by dongjoon-hyun** [comment]
Merged to master. The script is tested by @dbtsai , too.

**Pull request closed without merging**
