### PR TITLE
[SPARK-42134][SQL] Fix getPartitionFiltersAndDataFilters() to handle filters without referenced attributes

### PR DESCRIPTION
**Pull request by peter-toth**
### What changes were proposed in this pull request?
This is a small correctness fix to `DataSourceUtils.getPartitionFiltersAndDataFilters()` to handle filters without any referenced attributes correctly. E.g. without the fix the following query on ParquetV2 source:
```
spark.conf.set("spark.sql.sources.useV1SourceList", "")
spark.range(1).write.mode("overwrite").format("parquet").save(path)
df = spark.read.parquet(path).toDF("i")
f = udf(lambda x: False, "boolean")(lit(1))
val r = df.filter(f)
r.show()
```
returns
```
+---+
|  i|
+---+
|  0|
+---+
```
but it should return with empty results.
The root cause of the issue is that during `V2ScanRelationPushDown` a filter that doesn't reference any column is incorrectly identified as partition filter.

### Why are the changes needed?
To fix a correctness issue.

### Does this PR introduce _any_ user-facing change?
Yes, fixes a correctness issue.

### How was this patch tested?
Added new UT.

### CODE REVIEW

**Comment by peter-toth** [comment]
cc @cloud-fan, @huaxingao

**Review by huaxingao — APPROVED** [review]

**Comment by huaxingao** [comment]
Merged to 3.3/master. Thanks for fix this @peter-toth

**Comment by peter-toth** [comment]
Thanks for the quik review!

**Comment by cloud-fan** [comment]
late LGTM

**Pull request closed without merging**
