### PR TITLE
[SPARK-48225][BUILD] Upgrade `sbt` to 1.10.0

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to try `sbt` to 1.10.0. 

### Why are the changes needed?

So far, we couldn't upgrade SBT like the following.
- #45345
- #45312
- #44407
- #44516
- #44008
- #42673

Previously, we couldn't upgrade SBT due to its issues like the dependency resolution. SBT 1.10.0 is updated with Coursier 2.1.9 .

- https://github.com/sbt/sbt/releases/tag/v1.10.0
- https://github.com/sbt/sbt/releases/tag/v1.9.9
- https://github.com/sbt/sbt/releases/tag/v1.9.8
- https://github.com/sbt/sbt/releases/tag/v1.9.7
- https://github.com/sbt/sbt/releases/tag/v1.9.6
- https://github.com/sbt/sbt/releases/tag/v1.9.5
- https://github.com/sbt/sbt/releases/tag/v1.9.4

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the CIs.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
This is a new test to check if the bug is fixed or not.

cc @panbingkun and @LuciferYang .

**Comment by dongjoon-hyun** [comment]
Unfortunately, it turns out that the bug still exists.
```
[error] lmcoursier.internal.shaded.coursier.error.FetchError$DownloadingArtifacts: Error fetching artifacts:
[error] file:/root/.m2/repository/org/scala-lang/scala-library/2.13.10/scala-library-2.13.10.jar: not found: /root/.m2/repository/org/scala-lang/scala-library/2.13.10/scala-library-2.13.10.jar
[error] 
```

**Comment by dongjoon-hyun** [comment]
Let me open this PR for a while before closing.

**Comment by LuciferYang** [comment]
@dongjoon-hyun I was discussing this issue with @panbingkun  offline yesterday. From the responses of sbt and coursier, it seems difficult to solve this problem in the short term without some handling of `Resolver.mavenLocal`. I suggest that @panbingkun conduct some performance tests to determine whether this issue can be bypassed by disabling `Resolver.mavenLocal`:

- https://github.com/sbt/sbt/issues/7506#issuecomment-1972591578
- https://github.com/coursier/coursier/issues/2942

**Comment by dongjoon-hyun** [comment]
Thank you so much for sharing!

**Comment by panbingkun** [comment]
> @dongjoon-hyun I was discussing this issue with @panbingkun offline yesterday. From the responses of sbt and coursier, it seems difficult to solve this problem in the short term without some handling of `Resolver.mavenLocal`. I suggest that @panbingkun conduct some performance tests to determine whether this issue can be bypassed by disabling `Resolver.mavenLocal`:
> 
> * [When there is a corrupted jar in Maven's local repo, it will fail sbt/sbt#7506 (comment)](https://github.com/sbt/sbt/issues/7506#issuecomment-1972591578)
> * [When there is a corrupted jar in Maven's local repo, it will fail. coursier/coursier#2942](https://github.com/coursier/coursier/issues/2942)

Yeah, let me do some performance tests.

**Pull request closed without merging**
