### PR TITLE
[SPARK-7721][INFRA][FOLLOW-UP] Remove cloned coverage repo after posting HTMLs

### PR DESCRIPTION
**Pull request by HyukjinKwon**
## What changes were proposed in this pull request?

This PR proposes to remove cloned `pyspark-coverage-site` repo.

it doesn't looks a problem in PR builder but somehow it's problematic in `spark-master-test-sbt-hadoop-2.7`.

## How was this patch tested?

Jenkins.

### CODE REVIEW

**Comment by shaneknapp** [comment]
i don't think this is necessary at all.  the build clones the git repo,  issues a `git clean -fdx` and then runs `dev/run-tests`.

**Comment by HyukjinKwon** [comment]
Yes .. so I was wondering why `pyspark-coverage-site` is left over in the build `spark-master-test-sbt-hadoop-2.7` specifically. It's being failed because `pyspark-coverage-site` files are being checked if it has a license header or not, which is being done at the first phase of the build ..

`pyspark-coverage-site` is being cloned almost at the last step so it shouldn't be there. I suspected if the previous affects it somehow .. or I am misunderstanding this completely.

**Comment by shaneknapp** [comment]
also, this PR isn't needed.  i'd rather keep any filesystem ops in the build config, not the test code itself.

**Comment by HyukjinKwon** [comment]
Let me leave this open in case we want it. cc @shaneknapp and @srowen.

**Review by srowen — APPROVED** [review]

**Comment by shaneknapp** [comment]
this PR is fine, but i really like the approach in https://github.com/apache/spark/pull/24950 better.

**Comment by shaneknapp** [comment]
since this was fixed in https://github.com/apache/spark/pull/24950 (https://amplab.cs.berkeley.edu/jenkins/job/spark-master-test-sbt-hadoop-2.7/6046/console), i would recommend that we close this and not merge the changes in.

```
========================================================================
Running Apache RAT checks
========================================================================
Attempting to fetch rat
RAT checks passed.
```

**Comment by srowen** [comment]
I'm OK either way on this one. It seems like good cleanup but isn't essential now.

**Comment by shaneknapp** [comment]
> I'm OK either way on this one. It seems like good cleanup but isn't essential now.

same.

**Comment by HyukjinKwon** [comment]
I don't strongly feel about this PR too. Let me just merge this one just to be safer - shouldn't hurt something in any way ...

**Comment by shaneknapp** [comment]
i had to manually clean up all of the workers and remove existing `pyspark-coverage-site` dirs to get the build green again.

why `git clean -fdx` isn't actually removing that dir is beyond me.  :\

for an example, see:  https://amplab.cs.berkeley.edu/jenkins/job/spark-master-test-sbt-hadoop-2.7/6047/console

this is the output of the `git clean -fdx` command:
```
[spark-master-test-sbt-hadoop-2.7] $ /bin/bash /tmp/hudson4664062016256370877.sh
Removing R/lib/
Removing R/pkg/man/
Removing dev/sparktestsupport/__init__.pyc
Removing dev/sparktestsupport/modules.pyc
Removing dev/sparktestsupport/shellutils.pyc
Removing dev/sparktestsupport/toposort.pyc
Removing lib/
Removing pyspark-coverage-site/
Removing target/
```

great!  `pyspark-coverage-site` removed!  yay!

however:
```
========================================================================
Running Apache RAT checks
========================================================================
Attempting to fetch rat
Could not find Apache license headers in the following files:
 !????? /home/jenkins/workspace/spark-master-test-sbt-hadoop-2.7/pyspark-coverage-site/index.html
 !????? /home/jenkins/workspace/spark-master-test-sbt-hadoop-2.7/pyspark-coverage-site/jquery.ba-throttle-debounce.min.js
 !????? /home/jenkins/workspace/spark-master-test-sbt-hadoop-2.7/pyspark-coverage-site/jquery.hotkeys.js
 !????? /home/jenkins/workspace/spark-master-test-sbt-hadoop-2.7/pyspark-coverage-site/jquery.isonscreen.js
 !????? /home/jenkins/workspace/spark-master-test-sbt-hadoop-2.7/pyspark-coverage-site/jquery.min.js
 !????? /home/jenkins/workspace/spark-master-test-sbt-hadoop-2.7/pyspark-coverage-site/jquery.tablesorter.min.js
 !????? /home/jenkins/workspace/spark-master-test-sbt-hadoop-2.7/pyspark-coverage-site/pyspark_cloudpickle_py.html
 !????? /home/jenkins/workspace/spark-master-test-sbt-hadoop-2.7/pyspark-coverage-site/pyspark_heapq3_py.html
 !????? /home/jenkins/workspace/spark-master-test-sbt-hadoop-2.7/pyspark-coverage-site/pyspark_join_py.html
```

so i ran this command to clean stuff up:  `$ pssh -h centos_workers.txt -i "rm -rf workspace/spark-master-test-sbt-hadoop-2.7/pyspark-coverage-site/"`

then i launched a build, and it passed the RAT check:
https://amplab.cs.berkeley.edu/jenkins/job/spark-master-test-sbt-hadoop-2.7/6056/

**Pull request closed without merging**
