### PR TITLE
[SPARK-38006][SQL] Clean up duplicated planner logic for window operators

### PR DESCRIPTION
**Pull request by c21**
### What changes were proposed in this pull request?

Both `WindowExec.scala` and `WindowInPandasExec.scala` have some duplicated logic with regarded to query planning (`output`, `requiredChildDistribution/Ordering`, `outputPartitioning/Ordering`). We can move these logic into their common parent `WindowExecBase` to reduce duplication.

### Why are the changes needed?

Clean up existing code for better readability.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Existing test as this is just refactoring.

### CODE REVIEW

**Comment by c21** [comment]
@cloud-fan could you help take a look when you have time? Thanks.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Let's get rid of unused imports though :-):

```
[error] /__w/spark/spark/sql/core/src/main/scala/org/apache/spark/sql/execution/python/WindowInPandasExec.scala:30:54: Unused import
[error] import org.apache.spark.sql.catalyst.plans.physical.{AllTuples, ClusteredDistribution, Distribution, Partitioning}
[error]                                                      ^
[error] /__w/spark/spark/sql/core/src/main/scala/org/apache/spark/sql/execution/python/WindowInPandasExec.scala:30:65: Unused import
[error] import org.apache.spark.sql.catalyst.plans.physical.{AllTuples, ClusteredDistribution, Distribution, Partitioning}
[error]                                                                 ^
[error] /__w/spark/spark/sql/core/src/main/scala/org/apache/spark/sql/execution/python/WindowInPandasExec.scala:30:88: Unused import
[error] import org.apache.spark.sql.catalyst.plans.physical.{AllTuples, ClusteredDistribution, Distribution, Partitioning}
[error]                                                                                        ^
[error] /__w/spark/spark/sql/core/src/main/scala/org/apache/spark/sql/execution/python/WindowInPandasExec.scala:30:102: Unused import
[error] import org.apache.spark.sql.catalyst.plans.physical.{AllTuples, ClusteredDistribution, Distribution, Partitioning}
[error]                                                                                                      ^
[error] /__w/spark/spark/sql/core/src/main/scala/org/apache/spark/sql/execution/window/WindowExec.scala:23:53: Unused import
[error] import org.apache.spark.sql.catalyst.plans.physical._
```

**Comment by c21** [comment]
@HyukjinKwon - oops, thanks for reminder, removed.

**Review by cloud-fan — APPROVED** [review]

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Comment by c21** [comment]
Thank you @HyukjinKwon and @cloud-fan for review!

**Pull request closed without merging**
