### PR TITLE
[SPARK-42447][INFRA] Remove Hadoop 2 GitHub Action job

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to remove `Hadoop 2` GitHub Action job for Apache Spark 3.5+

### Why are the changes needed?

We are removing Hadoop 2 support and the job has been broken for three weeks already.
- https://github.com/apache/spark/actions/workflows/build_hadoop2.yml

Screenshot 2023-02-15 at 12 41 42 AM

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Manual review.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
cc @HyukjinKwon

**Review by yaooqinn — APPROVED** [review]

**Review by HyukjinKwon — APPROVED** [review]

**Comment by LuciferYang** [comment]
late LGTM

**Comment by dongjoon-hyun** [comment]
Thank you, @yaooqinn , @HyukjinKwon , @LuciferYang .

**Comment by bjornjorgensen** [comment]
So now we can upgrade guava?

**Comment by dongjoon-hyun** [comment]
Not yet, @bjornjorgensen ~ :) Please hold on any significant changes until Apache Spark 3.4 is released. We still need to backport many bug fixes during Apache Spark 3.4 RC period. Here I just removed the broken CI which no one will take care.

**Comment by vkn1234** [comment]
> Not yet, @bjornjorgensen ~ :) Please hold on any significant changes until Apache Spark 3.4 is released. We still need to backport many bug fixes during Apache Spark 3.4 RC period. Here I just removed the broken CI which no one will take care.

disable guava 20 too?

**Comment by HyukjinKwon** [comment]
I remember Guava upgrade is also blocked by Hive .. IIRC ..

**Pull request closed without merging**
