### PR TITLE
[SPARK-25556][SPARK-17636][SPARK-31026][SPARK-31060][FOLLOWUP][3.0] Fix build error due to conf version

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This fixes the build error.

### Why are the changes needed?

`branch-3.0` doesn't have conf version.

### Does this PR introduce any user-facing change?

No.

### How was this patch tested?

Passing the GitHub Action is enough.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
cc @cloud-fan , @dbtsai , @HyukjinKwon

**Review by cloud-fan — APPROVED** [review]
thanks for fixing!

**Comment by dongjoon-hyun** [comment]
Thank you, @cloud-fan .
Since GitHub Action passed, I'll merge this to `branch-3.0`.

**Comment by HyukjinKwon** [comment]
LGTM thanks @dongjoon-hyun for resolving the conflicts.

**Comment by dbtsai** [comment]
Thanks @dongjoon-hyun !!!

**Pull request closed without merging**
