### PR TITLE
DO NOT MERGE: Testing KafkaDelegationTokenSuite with testRetry in Jenkins

### PR DESCRIPTION
**Pull request by gaborgsomogyi**

### CODE REVIEW

**Comment by gaborgsomogyi** [comment]
The expectation is to see at least one failure and successful retry.

**Comment by gaborgsomogyi** [comment]
Hm, after spending a full day with investigation seems like it's way much more complicated than I've thought...

**Comment by gaborgsomogyi** [comment]
retest this please

**Comment by gaborgsomogyi** [comment]
retest this please

**Comment by gaborgsomogyi** [comment]
@HyukjinKwon @dongjoon-hyun @HeartSaVioR I'm digging the amplab job results to find a console log where it's failing but haven't found anything till now. Do you know at least one which is still available? I would like to understand the server configuration more...

**Comment by HeartSaVioR** [comment]
I'm not sure which log you would want to find, but for build 119458, this is the log file:

https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/119458/artifact/external/kafka-0-10-sql/target/unit-tests.log

**Comment by gaborgsomogyi** [comment]
Where it was failing before. I'm looking for an execution where I can see the console log + the unit test log together. The one you've show is a special crafted one by me.

**Comment by gaborgsomogyi** [comment]
retest this please

**Comment by gaborgsomogyi** [comment]
retest this please

**Comment by gaborgsomogyi** [comment]
Finally, it's reproduced. I've attached the results to https://issues.apache.org/jira/browse/SPARK-30541

**Comment by gaborgsomogyi** [comment]
Closing this because just opened https://github.com/apache/spark/pull/27877 to test a solution.

**Pull request closed without merging**
