### PR TITLE
[SPARK-11807] Remove support for Hadoop < 2.2

### PR DESCRIPTION
**Pull request by rxin**
i.e. Hadoop 1 and Hadoop 2.0

### CODE REVIEW

**Comment by srowen** [comment]
This is the right start; of course I'd also like to remove support for <2.6 but that's a different question.

There's a lot more that can be cleaned up here, mostly calls to APIs deprecated in 2.x, and some more removal of reflection. Would you like to do that here too, or should I open a companion PR?

**Comment by rxin** [comment]
Feel free to open a new PR. This mostly just does the bare minimal to reduce the build complexity.

What do we gain by dropping Hadoop 2.2 and 2.4? Beyond QA infra, are there any code changes that can be simplified?

**Comment by rxin** [comment]
Forgot to mention - going to merge this one.

**Comment by JoshRosen** [comment]
I'm going to go ahead and disable the corresponding master branch Jenkins builds in order to reduce load.

**Comment by srowen** [comment]
Yeah the benefits of supporting only 2.6 would be roughly:

- Another Jenkins build or two goes away
- Less JAR hell to reason about / newer transitive dependencies 
- Can use newer APIs, mostly YARN (I'm thinking of the history server stuff from the looong standing SPARK-1537)
- Bug fixes

I'm going to put together a change to remove the old deprecated API calls from <2.2, and will try to quantify what else can go away, to better quantify that part.

**Pull request closed without merging**
