### PR TITLE
[SPARK-12060][Core]Avoid memory copy in JavaSerializerInstance.serialize

### PR DESCRIPTION
**Pull request by zsxwing**
`JavaSerializerInstance.serialize` uses `ByteArrayOutputStream.toByteArray` to get the serialized data. `ByteArrayOutputStream.toByteArray` needs to copy the content in the internal array to a new array. However, since the array will be converted to `ByteBuffer` at once, we can avoid the memory copy.

This PR added `ByteBufferOutputStream` to access the protected `buf` and convert it to a `ByteBuffer` directly.

### CODE REVIEW

**Comment by vanzin** [comment]
LGTM pending tests.

**Comment by zsxwing** [comment]
retest this please

**Comment by srowen** [comment]
Yeah that looks nice, low-touch too.

**Comment by zsxwing** [comment]
Merging to master and 1.6

**Comment by zsxwing** [comment]
Just found a lot places use `ByteBuffer.array` directly and this patch will break them. Just reverted it before fixing the `ByteBuffer.array` issue.

**Pull request closed without merging**
