### PR TITLE
[SPARK-18391] Openstack deployment mode for any Spark version since 1.0

### PR DESCRIPTION
**Pull request by al-indigo**
This change adds a link to universal way to deploy Apache Spark since 1.0 up to 2.0.1 with any supported version of Hadoop in Openstack environment.

We utilize vanilla images (nothing pre-installed is needed; note it works only for cloud images of OS [but it's reasonable])

We support YARN-mode, Apache Ignite, NFS-mount, Jupyter notebooks, etc as optional on-demand options.

All the work is licensed Apache 2.0 explicitly.

The scenario was developed at Institute for System Programming of the Russian Academy of Sciences.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Could you please fix the title to the one that summerises what this PR proposes?

**Comment by rxin** [comment]
Hm we typically don't link to 3rd party things that way. Sorry please close this.

**Comment by rxin** [comment]
@al-indigo mind closing the pull request?

**Comment by srowen** [comment]
@al-indigo you can add this to spark-packages.org or I can put it on https://cwiki.apache.org/confluence/display/SPARK/Third+Party+Projects

**Comment by al-indigo** [comment]
@rxin I just thought that it makes sense to have links for Amazon EC2 and Openstack at the same place since the deployments are for the same purpose and provides the same CLI options for different cloud platforms

I thought that amplab scripts are 3rd party too, and we had a conversation in incubator-spark repository in October-November 2013 about it; as far as I remember Matei Zaharia recommended us to make a separate repository and have a link to it from Spark docs.

If you insist, I will close this PR and use @srowen ; I'm just worried about Spark users can discover it in docs much easier than in wiki or spark-packages

**Comment by srowen** [comment]
@al-indigo this document describes integrations that are part of Spark (or were in the case of EC2, which was only halfway in Spark and kind of spun back out, and could arguably be removed from this list) rather than 3rd-party project.

**Comment by al-indigo** [comment]
@srowen Ok, got your point, thanks

**Comment by al-indigo** [comment]
@srowen excuse me, I forgot to say that if you add it to Wiki, it would be great (you may close pr again as you see the comment)

**Pull request closed without merging**
