### PR TITLE
[SPARK-40255][YARN][TESTS]  Increase `BaseYarnClusterSuite#runSpark` timeout from 3 minutes to 5 minutes

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr Increase `BaseYarnClusterSuite#runSpark` timeout from 3 minutes to 5 minutes to make the tests extends `BaseYarnClusterSuite` more stable.

### Why are the changes needed?
Make flaky test stable.

### Does this PR introduce _any_ user-facing change?
No, just for test.

### How was this patch tested?
Pass GitHub Actions

### CODE REVIEW

**Comment by LuciferYang** [comment]
https://github.com/apache/spark/pull/37605#issuecomment-1221814039

cc @HyukjinKwon I suspect the flaky test  is caused by machine load.  After the timeout is increased, there is no failure yet, let's test and check more times

**Comment by LuciferYang** [comment]
I'm not sure if my GA can't reproduce the issue

**Comment by HyukjinKwon** [comment]
Hm, I doubt if the timeout is the actual problem. This test doesn't take too much time if you run locally actually.

**Comment by LuciferYang** [comment]
> Hm, I doubt if the timeout is the actual problem. This test doesn't take too much time if you run locally actually.

OK, let me see how to get the startup log of the failed instance to get more information

**Pull request closed without merging**
