### PR TITLE
changes with lambda (closure)

### PR DESCRIPTION
**Pull request by suyogchoudhari**
created same programs with JAVA8 lambda notations

### CODE REVIEW

**Comment by srowen** [comment]
I think you opened this by mistake? do you mind closing this PR?

**Comment by suyogchoudhari** [comment]
Hi Sean, 
I added it by purpose, thinking jdk 1.7 will end of life and to get immediate comparison with lambda for beginners. Planning to submit all other programs with lambda too.

If it doesn't make sense to you. I will close this out.

Regards,
Suyog

**Comment by srowen** [comment]
There's no explanation of how this fits into Spark, no descriptive title, etc. Yes, this would not be accepted this way. Please read https://cwiki.apache.org/confluence/display/SPARK/Contributing+to+Spark but I don't think this makes a useful example relative to what's already in the project.

**Comment by suyogchoudhari** [comment]
Thanks Sean. My bad. I will try to add something meaningful.

**Pull request closed without merging**
