### PR TITLE
[SPARK-19447] Fixing input metrics for range operator.

### PR DESCRIPTION
**Pull request by ala**
## What changes were proposed in this pull request?

This change introduces a new metric "number of generated rows". It is used exclusively for Range, which is a leaf in the query tree, yet doesn't read any input data, and therefore cannot report "recordsRead".

Additionally the way in which the metrics are reported by the JIT-compiled version of Range was changed. Previously, it was immediately reported that all the records were produced. This could be confusing for a user monitoring execution progress in the UI. Now, the metric is updated gradually.

In order to avoid negative impact on Range performance, the code generation was reworked. The values are now produced in batches in the tighter inner loop, while the metrics are updated in the outer loop.

The change also contains a number of unit tests, which should help ensure the correctness of metrics for various input sources.

## How was this patch tested?

Unit tests.

### CODE REVIEW

**Comment by hvanhovell** [comment]
add to whitelist

**Comment by hvanhovell** [comment]
ok to test

**Comment by rxin** [comment]
LGTM

**Comment by rxin** [comment]
Merging in master. Thanks.

**Pull request closed without merging**
