### PR TITLE
[Doc] Fix typo in sql hive doc

### PR DESCRIPTION
**Pull request by dhruve**
Change is too trivial to file a JIRA.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Maybe I think you could try to find other typoes together (at least in other docs as you fix a typo in documentation). It seems too minor in my opinion.

**Comment by dhruve** [comment]
I wasn't scanning explicitly for these typoes. I have seen individual commits addressing such typoes earlier so submitted the super trivial change. If unnecessary we can close this.

**Comment by HyukjinKwon** [comment]
Yeap, it is true and I think it is acceptable but maybe we should avoid. I guess we don't want flooding small fixes for typoes.

**Comment by srowen** [comment]
Yeah, I'd prefer to encourage fixing a bunch of stuff at once, and discourage truly non-functional changes that don't meaningfully clarify something. If you add up the time everyone spends looking at it it's, shockingly, like hundreds of dollars of time. OK, I can merge it as the fastest way to resolve this but it's not worth it in general.

**Pull request closed without merging**
