### PR TITLE
[SPARK-32814][PYTHON] Replace __metaclass__ field with metaclass keyword

### PR DESCRIPTION
**Pull request by zero323**
### What changes were proposed in this pull request?

Replace `__metaclass__` fields with `metaclass` keyword in the class statements.

### Why are the changes needed?

`__metaclass__` is no longer supported in Python 3. This means, for example, that types are no longer handled as singletons. 

```
>>> from pyspark.sql.types import BooleanType                                                                                                                                                                      
>>> BooleanType() is BooleanType()                                                                                                                                                                                 
False
```

and classes, which suppose to be abstract, are not

```
>>> import inspect                                                                                                                                                                                                 
>>> from pyspark.ml import Estimator                                                                                                                                                                               
>>> inspect.isabstract(Estimator)                                                                                                                                                                                  
False
```

### Does this PR introduce _any_ user-facing change?

Yes (classes which were no longer abstract or singleton in Python 3, are now), though visible changes should be consider a bug-fix.

### How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by zero323** [comment]
cc @HyukjinKwon 

Note: I'm opening this as a follow-up, but I wonder if it deserves a separate ticket ‒ technically speaking it looks like a bug, and we might want to backport it to 3.0.

**Comment by HyukjinKwon** [comment]
Thanks @zero323. Yeah, I think it's better to just file a separate JIRA to manage and track separately.

**Review by HyukjinKwon — APPROVED** [review]
Looks good otherwise.

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
