### PR TITLE
[SPARK-14170] [infra] Simplify the PR template and remove it when merging.

### PR DESCRIPTION
**Pull request by vanzin**
This change modifies the template so that all instructions are together at
the top, which makes it easy to remove the template in the merge script,
just in case people forget. It's also less intrusive since it doesn't
require contributors to write their commit message in the middle of the
template.

### CODE REVIEW

**Comment by vanzin** [comment]
Github doesn't actually show the modified template, so I'll have to manually test things locally some other way... (I tested "fake merging" existing PRs and that's working as before.)

**Comment by vanzin** [comment]
Argh the rendering looks horrible, I'll have to find a better way...

**Comment by vanzin** [comment]
prtmpl

**Comment by vanzin** [comment]
Looks a bit large, open to suggestions (or to even just live with the current template...). Avoiding the bullet list would help, at the cost of making the test a little more dense.

**Comment by srowen** [comment]
Looks OK to me.

**Comment by rxin** [comment]
I'm against the change to remove the template and simply provide instructions. The problem is that most prs don't follow things like this. I think just having the merge script removes the extra phases people don't delete is sufficient to accomplish your purpose.

**Comment by rxin** [comment]
In addition, to make this more robust towards future changes, we can also just have the merge script read the content of the contributing.md and delete the non-title phrases.

**Comment by srowen** [comment]
@rxin the template stays in place; the content is effectively the same too. I think the change here is just auto-removing the boilerplate, which was the purpose. I didn't follow your comment as a result, including the test field note?

I also wouldn't mind pushing `CONTRIBUTING.md` up in people's faces as the default text with a note to delete it, and with the auto-removing mechanism still in place. This is just a question of what the text used here is.

**Comment by vanzin** [comment]
@rxin do you mean you prefer the style where people replace portions of the template with text?

I can see why some would prefer that, but it makes a little harder to remove text. For example, you can't remote the `## How was this patch tested?` part because people generally write like this:

    ## How was this patch tested?

    unit tests

So if you remove it, the message becomes a little nonsensical. You can remove the `(Please blah blah` instructions, but those provide just a minor gain - and people generally remove them anyway.

Anyway, I'm ok with just leaving things as is, although personally I kinda dislike the noise added to every commit message.

**Comment by rxin** [comment]
As I said, just read the contributing.md file in, for each line that is not heading, remove the line from the pr description.

**Comment by vanzin** [comment]
Sure, but as I said, that still leaves the annoying (for me) noise - the headings - in every commit message; given that people generally remove the other lines, there's very little gain in doing what you suggest.

Anyway, I'll close this, since I don't see much gain in remove just those lines.

**Pull request closed without merging**
