### PR TITLE
[SPARK-36871][SQL]Migrate CreateViewStatement to v2 command

### PR DESCRIPTION
**Pull request by huaxingao**
### What changes were proposed in this pull request?
Migrate `CreateViewStatement`  to v2 command framework

### Why are the changes needed?
Migrate to the standard V2 framework

### Does this PR introduce _any_ user-facing change?
no

### How was this patch tested?
existing tests

### CODE REVIEW

**Comment by huaxingao** [comment]
cc @cloud-fan

**Review by cloud-fan — APPROVED** [review]
LGTM, please fix code conflicts

**Review by cloud-fan — APPROVED** [review]

**Comment by huaxingao** [comment]
retest this please

**Review by cloud-fan — APPROVED** [review]

**Comment by huaxingao** [comment]
Thanks!

**Pull request closed without merging**
