### PR TITLE
[SPARK-5423][Core] Cleanup resources in DiskMapIterator.finalize to ensure deleting the temp file

### PR DESCRIPTION
**Pull request by zsxwing**
This PR adds a `finalize` method in DiskMapIterator to clean up the resources even if some exception happens during processing data.

### CODE REVIEW

**Comment by andrewor14** [comment]
Ok, LGTM I'm merging this into master and 1.3 thanks for fixing this @zsxwing

**Comment by nishkamravi2** [comment]
@zsxwing @andrewor14  I'm noticing a significant performance regression with this commit (SPARK-6142). Commenting out finalize recovers performance (as expected). Finalize is generally considered unhealthy for production code (can create indefinite performance issues and doesn't guarantee cleanup). Should we consider reverting this fix for 1.3 and contemplating an alternate one?

**Comment by andrewor14** [comment]
Thanks for reporting this. I will just revert this one altogether and consider a different alternative after the release. This bug has been an issue since 1.0 and is not so critical that we have to rush in an alternative fix for the release. In the future we may want to consider an alternative that uses weak references instead.

**Comment by nishkamravi2** [comment]
Sounds good, thanks.

**Comment by zsxwing** [comment]
How many failure tasks in your test? If no failure task, looks weird. In the happy path, the `finalize` method should only check `closed` and exit. @nishkamravi2 do you have any number about the significant performance regression?

**Pull request closed without merging**
