### PR TITLE
[SPARK-12025] [SparkR] Rename some window rank function names for SparkR

### PR DESCRIPTION
**Pull request by yanboliang**
Change `cumeDist -> cume_dist, denseRank -> dense_rank, percentRank -> percent_rank, rowNumber -> row_number` at SparkR side.
There are two reasons that we should make this change:
- We should follow the [naming convention rule of R](http://www.inside-r.org/node/230645)
- Spark DataFrame has deprecated the old convention (such as `cumeDist`) and will remove it in Spark 2.0.

It's better to fix this issue before 1.6 release, otherwise we will make breaking API change.
cc @shivaram @sun-rui

### CODE REVIEW

**Comment by sun-rui** [comment]
code change looks good. New names have no conflict with R base package.

But I don't see they are deprecated now? Could you point to me the discussion or JIRA that they will be removed in Spark 2.0?
If they are deprecated, I am fine with the name change.
If they are not deprecated, could we add new names as aliases, while keeping the old names at the same time?

**Comment by yanboliang** [comment]
@sun-rui Thanks for your comments. You can get the issue from the [source code](https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/functions.scala#L563) and this PR(#9930).

**Comment by sun-rui** [comment]
@yanboliang, thanks for your info. I didn't look at the latest code:)

LGTM

**Comment by shivaram** [comment]
LGTM. Thanks @yanboliang -- BTW were these APIs were present in SparkR 1.5 ? If so we'll need to update the release docs about this change.

**Comment by felixcheung** [comment]
@shivaram they were added only for Spark 1.6, so no need to update release doc on breaking changes
https://github.com/apache/spark/commit/dc3220ce11c7513b1452c82ee82cb86e908bcc2d
https://github.com/apache/spark/commit/40c77fb23a1ee0a4e69d735ee6247f83b7e13b92

But the new names seem to mask methods from dplyr.

**Pull request closed without merging**
