### PR TITLE
[SPARK-50135][BUILD] Upgrade ZooKeeper to 3.9.3

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to upgrade `ZooKeeper` from `3.9.2` to `3.9.3`.

### Why are the changes needed?
The full release notes: https://zookeeper.apache.org/doc/r3.9.3/releasenotes.html

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
It looks good to me, @panbingkun . Is the PR ready?

**Comment by panbingkun** [comment]
> It looks good to me, @panbingkun . Is the PR ready?

Yep,thanks. ❤️

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @panbingkun .
Merged to master.

**Comment by HyukjinKwon** [comment]
Surprisingly this caused the test failures in Spark Connect specifically for Mac .... 


```
/python/run-tests --python-executables=python3 --testnames "pyspark.sql.tests.connect.test_connect_collection"
```

With this PR:

```
google.protobuf.runtime_version.VersionError: Detected incompatible Protobuf Gencode/Runtime versions when loading spark/connect/base.proto: gencode 5.28.3 runtime 5.28.2. Runtime version cannot be older than the linked gencode version. See Protobuf version guarantees at https://protobuf.dev/support/cross-version-runtime-guarantee.
```

Without this PR:

```
Running PySpark tests. Output is in /.../spark/python/unit-tests.log
Will test against the following Python executables: ['python3']
Will test the following Python tests: ['pyspark.sql.tests.connect.test_connect_collection']
python3 python_implementation is CPython
python3 version is: Python 3.11.9
Starting test(python3): pyspark.sql.tests.connect.test_connect_collection (temp output: /.../spark/python/target/c288c2b5-a11a-4d12-8169-3947c2db9cdc/python3__pyspark.sql.tests.connect.test_connect_collection__rwwdqgag.log)
Finished test(python3): pyspark.sql.tests.connect.test_connect_collection (16s)
Tests passed in 16 seconds
```

...

Let me revert this for now because the change is sort of trivial but seems like this affects all developers with Mac ..

**Comment by zhengruifeng** [comment]
thanks @HyukjinKwon for addressing this issue. Python developers had been blocked for 2 weeks. 

IIRC, this is not the first time that some Python tests only fails with MacOS.
This kind of issue is hard to fix, I actually attempted to resolve it by reverting some suspicious PRs and comparing with versions of OSS GA, but failed to find the root cause.

Is it possible to add a lightweight MacOS GA job to guard basic PySpark functionality? @dongjoon-hyun @Yikun @LuciferYang

**Comment by HyukjinKwon** [comment]
We have MacOS test at https://github.com/apache/spark/actions/workflows/build_maven_java21_macos15.yml but we're not running PySpark tests now. We could improve this furhter.

**Comment by panbingkun** [comment]
> Surprisingly this caused the test failures in Spark Connect specifically for Mac ....
> 
> ```
> /python/run-tests --python-executables=python3 --testnames "pyspark.sql.tests.connect.test_connect_collection"
> ```
> 
> With this PR:
> 
> ```
> google.protobuf.runtime_version.VersionError: Detected incompatible Protobuf Gencode/Runtime versions when loading spark/connect/base.proto: gencode 5.28.3 runtime 5.28.2. Runtime version cannot be older than the linked gencode version. See Protobuf version guarantees at https://protobuf.dev/support/cross-version-runtime-guarantee.
> ```
> 
> Without this PR:
> 
> ```
> Running PySpark tests. Output is in /.../spark/python/unit-tests.log
> Will test against the following Python executables: ['python3']
> Will test the following Python tests: ['pyspark.sql.tests.connect.test_connect_collection']
> python3 python_implementation is CPython
> python3 version is: Python 3.11.9
> Starting test(python3): pyspark.sql.tests.connect.test_connect_collection (temp output: /.../spark/python/target/c288c2b5-a11a-4d12-8169-3947c2db9cdc/python3__pyspark.sql.tests.connect.test_connect_collection__rwwdqgag.log)
> Finished test(python3): pyspark.sql.tests.connect.test_connect_collection (16s)
> Tests passed in 16 seconds
> ```
> 
> ...
> 
> Let me revert this for now because the change is sort of trivial but seems like this affects all developers with Mac ..

Thank you for helping to fix it. Let me investigate it. Thanks!

**Comment by dongjoon-hyun** [comment]
Thank you for the head-up and recovery.

**Comment by LuciferYang** [comment]
Are all current PySpark tests run in a container environment? Even if the os is specified as mac-os, are the existing images still based on Ubuntu? Or is this Python-Only on macOS joob supposed to run in a physical machine environment?

**Comment by panbingkun** [comment]
I think I have identified this issue and will submit a new PR this afternoon to solve it.

**Comment by zhengruifeng** [comment]
> Are all current PySpark tests run in a container environment? Even if the os is specified as mac-os, are the existing images still based on Ubuntu? Or is this Python-Only on macOS joob supposed to run in a physical machine environment?

yes, the are always container job.
we should add a MacOS non-container job for this purpose, or make a MacOS image instead of Ubuntu image

**Comment by panbingkun** [comment]
- When we use `sbt` to compile the Spark project, in directory `assembly/target/scala-2.13/jars/`, we will find `netty related dependencies`, some are version `4.1.110.Final`, some are version `4.1.113.Final`, as follow:
```


```


and `./python/run-tests --python-executables=python3 --testnames "pyspark.sql.tests.connect.test_connect_collection"` will failed.
```

```

- When we use `maven` to compile the Spark project, in directory `assembly/target/scala-2.13/jars`, we will find `netty related dependencies`,  all are version `4.1.110.Final`, as follow:
```
(pyspark) ➜  jars git:(master) ✗ ls -1 netty-*4*
netty-all-4.1.110.Final.jar
netty-buffer-4.1.110.Final.jar
netty-codec-4.1.110.Final.jar
netty-codec-http-4.1.110.Final.jar
netty-codec-http2-4.1.110.Final.jar
netty-codec-socks-4.1.110.Final.jar
netty-common-4.1.110.Final.jar
netty-handler-4.1.110.Final.jar
netty-handler-proxy-4.1.110.Final.jar
netty-resolver-4.1.110.Final.jar
netty-tcnative-boringssl-static-2.0.66.Final-linux-aarch_64.jar
netty-tcnative-boringssl-static-2.0.66.Final-linux-x86_64.jar
netty-tcnative-boringssl-static-2.0.66.Final-osx-aarch_64.jar
netty-tcnative-boringssl-static-2.0.66.Final-osx-x86_64.jar
netty-tcnative-boringssl-static-2.0.66.Final-windows-x86_64.jar
netty-transport-4.1.110.Final.jar
netty-transport-classes-epoll-4.1.110.Final.jar
netty-transport-classes-kqueue-4.1.110.Final.jar
netty-transport-native-epoll-4.1.110.Final-linux-aarch_64.jar
netty-transport-native-epoll-4.1.110.Final-linux-riscv64.jar
netty-transport-native-epoll-4.1.110.Final-linux-x86_64.jar
netty-transport-native-kqueue-4.1.110.Final-osx-aarch_64.jar
netty-transport-native-kqueue-4.1.110.Final-osx-x86_64.jar
netty-transport-native-unix-common-4.1.110.Final.jar
```

And `./python/run-tests --python-executables=python3 --testnames "pyspark.sql.tests.connect.test_connect_collection"` will succeed.
```shell
(pyspark) ➜  spark-community git:(master) ✗ ./python/run-tests --python-executables=python3 --testnames "pyspark.sql.tests.connect.test_connect_collection"
Running PySpark tests. Output is in /Users/panbingkun/Developer/spark/spark-community/python/unit-tests.log
Will test against the following Python executables: ['python3']
Will test the following Python tests: ['pyspark.sql.tests.connect.test_connect_collection']
python3 python_implementation is CPython
python3 version is: Python 3.9.19
Starting test(python3): pyspark.sql.tests.connect.test_connect_collection (temp output: /Users/panbingkun/Developer/spark/spark-community/python/target/f5aa47b5-2b52-4106-a997-30e54b1316e6/python3__pyspark.sql.tests.connect.test_connect_collection__5e2svetz.log)
Finished test(python3): pyspark.sql.tests.connect.test_connect_collection (15s)
Tests passed in 15 seconds
```

-

**Comment by LuciferYang** [comment]
How was '4.1.113' introduced?

**Comment by LuciferYang** [comment]
```
<exclusion> 
       <groupId>org.jboss.netty</groupId> 
       <artifactId>netty</artifactId> 
     </exclusion> 
```

Here, what is excluded is the dependency on netty 3.x. The groupId for netty 3.x and 4.x is different.

**Comment by panbingkun** [comment]
cc @HyukjinKwon @LuciferYang 
> We have MacOS test at https://github.com/apache/spark/actions/workflows/build_maven_java21_macos15.yml but we're not running PySpark tests now. We could improve this furhter.

Based on the above conclusions and analysis, I believe that any compilation based on `Maven` may not detect this issue in advance.

**Comment by panbingkun** [comment]
> ```
> <exclusion> 
>        <groupId>org.jboss.netty</groupId> 
>        <artifactId>netty</artifactId> 
>      </exclusion> 
> ```
> 
> Here, what is excluded is the dependency on netty 3.x. The groupId for netty 3.x and 4.x is different.

image

**Comment by panbingkun** [comment]
A new pr for it: https://github.com/apache/spark/pull/48771

**Comment by panbingkun** [comment]
> we should change to exclude
> 
> ```
> <exclusion> 
>        <groupId>io.netty</groupId> 
>        <artifactId>*</artifactId> 
>      </exclusion> 
> ```
> 
> from zookeeper instead of
> 
> ```
> <exclusion> 
>        <groupId>org.jboss.netty</groupId> 
>        <artifactId>netty</artifactId> 
>      </exclusion> 
> ```
> 
> `org.jboss.netty` is the groupId of netty 3.x

It doesn't seem to work, I've tried it and I can confirm again.

**Comment by panbingkun** [comment]
> we should change to exclude
> 
> ```
> <exclusion> 
>        <groupId>io.netty</groupId> 
>        <artifactId>*</artifactId> 
>      </exclusion> 
> ```
> 
> from zookeeper instead of
> 
> ```
> <exclusion> 
>        <groupId>org.jboss.netty</groupId> 
>        <artifactId>netty</artifactId> 
>      </exclusion> 
> ```
> 
> `org.jboss.netty` is the groupId of netty 3.x

Unfortunately, this issue still exists.

image

```shell
(pyspark) ➜  spark-community git:(master) ✗ cd assembly/target/scala-2.13/jars
(pyspark) ➜  jars git:(master) ✗ ls -1 netty-*
netty-all-4.1.110.Final.jar
netty-buffer-4.1.113.Final.jar
netty-codec-4.1.113.Final.jar
netty-codec-http-4.1.110.Final.jar
netty-codec-http2-4.1.110.Final.jar
netty-codec-socks-4.1.110.Final.jar
netty-common-4.1.113.Final.jar
netty-handler-4.1.113.Final.jar
netty-handler-proxy-4.1.110.Final.jar
netty-resolver-4.1.113.Final.jar
netty-tcnative-boringssl-static-2.0.66.Final-linux-aarch_64.jar
netty-tcnative-boringssl-static-2.0.66.Final-linux-x86_64.jar
netty-tcnative-boringssl-static-2.0.66.Final-osx-aarch_64.jar
netty-tcnative-boringssl-static-2.0.66.Final-osx-x86_64.jar
netty-tcnative-boringssl-static-2.0.66.Final-windows-x86_64.jar
netty-tcnative-boringssl-static-2.0.66.Final.jar
netty-tcnative-classes-2.0.66.Final.jar
netty-transport-4.1.113.Final.jar
netty-transport-classes-epoll-4.1.113.Final.jar
netty-transport-classes-kqueue-4.1.110.Final.jar
netty-transport-native-epoll-4.1.113.Final-linux-aarch_64.jar
netty-transport-native-epoll-4.1.113.Final-linux-riscv64.jar
netty-transport-native-epoll-4.1.113.Final-linux-x86_64.jar
netty-transport-native-kqueue-4.1.110.Final-osx-aarch_64.jar
netty-transport-native-kqueue-4.1.110.Final-osx-x86_64.jar
netty-transport-native-unix-common-4.1.113.Final.jar
```

**Comment by LuciferYang** [comment]
> > we should change to exclude
> > ```
> > <exclusion> 
> >        <groupId>io.netty</groupId> 
> >        <artifactId>*</artifactId> 
> >      </exclusion> 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > from zookeeper instead of
> > ```
> > <exclusion> 
> >        <groupId>org.jboss.netty</groupId> 
> >        <artifactId>netty</artifactId> 
> >      </exclusion> 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `org.jboss.netty` is the groupId of netty 3.x
> 
> Unfortunately, this issue still exists.
> 
> image
> ```shell
> (pyspark) ➜  spark-community git:(master) ✗ cd assembly/target/scala-2.13/jars
> (pyspark) ➜  jars git:(master) ✗ ls -1 netty-*
> netty-all-4.1.110.Final.jar
> netty-buffer-4.1.113.Final.jar
> netty-codec-4.1.113.Final.jar
> netty-codec-http-4.1.110.Final.jar
> netty-codec-http2-4.1.110.Final.jar
> netty-codec-socks-4.1.110.Final.jar
> netty-common-4.1.113.Final.jar
> netty-handler-4.1.113.Final.jar
> netty-handler-proxy-4.1.110.Final.jar
> netty-resolver-4.1.113.Final.jar
> netty-tcnative-boringssl-static-2.0.66.Final-linux-aarch_64.jar
> netty-tcnative-boringssl-static-2.0.66.Final-linux-x86_64.jar
> netty-tcnative-boringssl-static-2.0.66.Final-osx-aarch_64.jar
> netty-tcnative-boringssl-static-2.0.66.Final-osx-x86_64.jar
> netty-tcnative-boringssl-static-2.0.66.Final-windows-x86_64.jar
> netty-tcnative-boringssl-static-2.0.66.Final.jar
> netty-tcnative-classes-2.0.66.Final.jar
> netty-transport-4.1.113.Final.jar
> netty-transport-classes-epoll-4.1.113.Final.jar
> netty-transport-classes-kqueue-4.1.110.Final.jar
> netty-transport-native-epoll-4.1.113.Final-linux-aarch_64.jar
> netty-transport-native-epoll-4.1.113.Final-linux-riscv64.jar
> netty-transport-native-epoll-4.1.113.Final-linux-x86_64.jar
> netty-transport-native-kqueue-4.1.110.Final-osx-aarch_64.jar
> netty-transport-native-kqueue-4.1.110.Final-osx-x86_64.jar
> netty-transport-native-unix-common-4.1.113.Final.jar
> ```

Ok ~ I'll investigate if there's a simpler method later

**Comment by panbingkun** [comment]
The final solution is to upgrade `netty` to version `1.1.114` first, and then upgrade `zookeeper`.
I have verified locally that the `netty...` generated by compiling with `sbt` is version `1.1.114`

**Pull request closed without merging**
