### PR TITLE
[SPARK-28683][BUILD] Upgrade Scala to 2.12.10

### PR DESCRIPTION
**Pull request by wangyum**
## What changes were proposed in this pull request?

This PR upgrade Scala to **2.12.10**.

Release notes:
- Fix regression in large string interpolations with non-String typed splices
- Revert "Generate shallower ASTs in pattern translation"
- Fix regression in classpath when JARs have 'a.b' entries beside 'a/b' 

- Faster compiler: 5–10% faster since 2.12.8
- Improved compatibility with JDK 11, 12, and 13
- Experimental support for build pipelining and outline type checking

More details:
https://github.com/scala/scala/releases/tag/v2.12.10
https://github.com/scala/scala/releases/tag/v2.12.9

## How was this patch tested?

Existing tests

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by dongjoon-hyun** [comment]
The failure seems relevant, @wangyum . Could you check the failures?

**Comment by srowen** [comment]
Wow that's a weird one, but I played with it and, bizarrely this change in the generate code makes it work:

```
      } else if ($o2 == null) {
        return -$sortOrder * $nullOrder;
      }
```

to

```
      } else if ($o2 == null) {
        return -$sortOrder * ${nullOrder.toString};
      }
```

I can only guess something goes wrong in string interpolation because `nullOrder` is a `NullOrder` and typedef for an `Int`, and is boxed to `Integer` somewhere, but something believes it is a String.

... and then I decided to search for open bugs and yep this is it:
https://github.com/scala/bug/issues/11665

We may just need to wait for 2.12.10

**Comment by wangyum** [comment]
Thank you @srowen Let's  wait for 2.12.10.

**Comment by dongjoon-hyun** [comment]
Hi, All. Let's reuse SPARK-28683 for 2.12.10. I reopened it.

**Comment by wangyum** [comment]
```
sbt.ResolveException: unresolved dependency: com.typesafe.genjavadoc#genjavadoc-plugin_2.12.10;0.13: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:320)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
```
Let's wait for `genjavadoc-plugin_2.12.10`: https://repo1.maven.org/maven2/com/typesafe/genjavadoc/

**Comment by srowen** [comment]
OK by me, once the javadoc plugin is available and tests pass. Looks like the problem with string interpolation was resolved.

**Comment by dongjoon-hyun** [comment]
Thank you, @wangyum and @srowen . Yes. Let's retry when it becomes ready.

**Comment by wangyum** [comment]
retest this please

**Comment by wangyum** [comment]
genjavadoc 0.14 has released: https://repo1.maven.org/maven2/com/typesafe/genjavadoc/genjavadoc-plugin_2.12.10/0.14/

**Comment by dongjoon-hyun** [comment]
Finally! Thanks!

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by srowen** [comment]
Well... that's weird. Lots of tests fail because they get slightly different answers, and almost all look like tests that depend on a seeded random number generator at some level.

Take https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/110781/testReport/test.org.apache.spark/JavaAPISuite/sample/ for example.

```
  @Test
  public void sample() {
    List<Integer> ints = IntStream.iterate(1, x -> x + 1)
      .limit(20)
      .boxed()
      .collect(Collectors.toList());
    JavaRDD<Integer> rdd = sc.parallelize(ints);
    // the seeds here are "magic" to make this work out nicely
    JavaRDD<Integer> sample20 = rdd.sample(true, 0.2, 8);
    assertEquals(2, sample20.count());
    JavaRDD<Integer> sample20WithoutReplacement = rdd.sample(false, 0.2, 2);
    assertEquals(4, sample20WithoutReplacement.count());
  }
```

It's seeded, so ought to produce the same answer. This has worked the same way for a long time, giving that particular answer with that particular seed. It's pretty straightforwardly using a java.util.Random, seeded. What could have changed?

At the moment I'm wondering if somehow a compiler or collections change causes the input to be partitioned differently or iterated over differently. Still thinking about it and reviewing the (pretty minor) Scala changes.

One way or the other I don't think we can let the behavior change for a seeded sample, but not clear whether it's some subtle assumption Spark makes or something else going on.

**Comment by dongjoon-hyun** [comment]
Oh, then, Scala 2.12.10 seems to have a breaking change like that. I agree we should not upgrade if then. I'll take a look today, too. I guess it will end up with reporting another issue to the Scala community. 😞

**Comment by srowen** [comment]
I'll investigate a little more to narrow down what the difference even seems to be. I think we do need to figure it out eventually because people will want to use 2.12.10 and we want the enhancements.

**Comment by shaneknapp** [comment]
test this please

**Comment by kiszk** [comment]
When I take a look at `RandomSuite`, most of the code is executed thru (generated) Java. IIUC, only `setSeed`, `hashSeed`, and `next` methods in `XORShiftRandom` are written in Scala...

**Comment by kiszk** [comment]
After tracing this test, I believe `MurmurHash3.bytesHash` returns a different value between Scala 2.10.8 and 2.10.10. I am investigating the reason.

**Comment by kiszk** [comment]
I am curious that [this change](https://github.com/scala/scala/commit/846ee2b1a47014c69ebd2352d91d467be74918b5#diff-ac889f851e109fc4387cd738d52ce177) on 2019/1 may affect the result.

Scala 2.10.8 was released on [2018/12](https://github.com/scala/scala/releases/tag/v2.12.8)
Scala 2.10.10 was released on [2019/9](https://github.com/scala/scala/releases/tag/v2.12.10)

**Comment by dongjoon-hyun** [comment]
Thank you for sharing the investigation result, @kiszk !
It's surprising because [the original issue](https://github.com/scala/bug/issues/10690) is reported on Jan 15, 2018 .

**Comment by dongjoon-hyun** [comment]
Hi, All. I'd recommend to use the old one for `XORShiftRandom`.

@wangyum . Please add `MurmurHash3.arraySeed` like the following.
- core/src/main/scala/org/apache/spark/util/random/XORShiftRandom.scala
```scala
   private[random] def hashSeed(seed: Long): Long = {
     val bytes = ByteBuffer.allocate(java.lang.Long.BYTES).putLong(seed).array()
-    val lowBits = MurmurHash3.bytesHash(bytes)
+    val lowBits = MurmurHash3.bytesHash(bytes, MurmurHash3.arraySeed)
     val highBits = MurmurHash3.bytesHash(bytes, lowBits)
     (highBits.toLong << 32) | (lowBits.toLong & 0xFFFFFFFFL)
   }
```

**Comment by dongjoon-hyun** [comment]
Hmm. It may be worth of having another PR to make it sure.

**Comment by srowen** [comment]
Yep before we decide what to do, it's worth seeing whether this is the issue. @dongjoon-hyun to match https://github.com/scala/scala/commit/846ee2b1a47014c69ebd2352d91d467be74918b5#diff-ac889f851e109fc4387cd738d52ce177 don't we need both calls to change `bytesHash` to `arrayHash`? I may not have thought about it as much as you have though.

**Comment by dongjoon-hyun** [comment]
I quickly checked that the failures on `catalyst` module and `DatasetSuite`, `DataFrameStatSuite`, `JsonSuite`, `CSVSuite` of `sql` module. All of them are fixed with that change.

**Comment by wangyum** [comment]
I applied SPARK-29124 to this PR. Let's see if all tests can pass.

**Comment by wangyum** [comment]
retest this please

**Comment by wangyum** [comment]
retest this please

**Comment by wangyum** [comment]
retest this please

**Comment by wangyum** [comment]
retest this please

**Comment by srowen** [comment]
@dongjoon-hyun ah OK, I see what you did now. By using the equivalent two-arg `bytesHash` method, the behavior didn't change. But the implementation of two-arg `bytesHash` didn't change in Scala 2.12.10 so it avoids a behavior change.

Looks promising that tests have passed here once.

**Comment by dongjoon-hyun** [comment]
Yes. Right, @srowen !

**Comment by dongjoon-hyun** [comment]
So, if the last Jenkins run passes, this PR looks ready for me.
- SBT (https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/110854/console)
- Maven/JDK11 (https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/110901/testReport)
- Maven/JDK8 (https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/110911/testReport, Pending)

**Review by dongjoon-hyun — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Hmm. The last test has been running 5 hr 43 min already. It seems that we will hit timeout soon. :(

**Comment by dongjoon-hyun** [comment]
The last run passed all Scala/Java UTs and moved to Python test.
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  05:24 h
[INFO] Finished at: 2019-09-18T12:39:46-07:00
[INFO] ------------------------------------------------------------------------
```

**Comment by kiszk** [comment]
LGTM, pending Jenkins

**Comment by dongjoon-hyun** [comment]
I checked and noticed that the PR Builder timeout `430m`. It looks safe. I was confused with the other Jenkins job configurations which are shorter than this.

**Comment by dongjoon-hyun** [comment]
Hmm. It's weird because it's terminated before the configuration.
Screen Shot 2019-09-18 at 1 28 27 PM

**Comment by dongjoon-hyun** [comment]
Anyway, this Scala change looks safe to me. I'll merge this to master. Thank you, @wangyum , @srowen , @kiszk !

Please make a backport to `branch-2.4`.

**Pull request closed without merging**
