### PR TITLE
[SPARK-16875][SQL] Add args checking for DataSet randomSplit and sample

### PR DESCRIPTION
**Pull request by zhengruifeng**
## What changes were proposed in this pull request?

Add the missing args-checking for randomSplit and sample
## How was this patch tested?

unit tests

### CODE REVIEW

**Comment by srowen** [comment]
LGTM. I wonder if we should even disallow a 0% sample, but, OK as-is.

**Comment by srowen** [comment]
Ah, let's do this for the RDD API too eh?

**Comment by zhengruifeng** [comment]
@srowen Right. I just add those checking for RDD.

**Comment by srowen** [comment]
Merged to master / 2.0

**Pull request closed without merging**
