### PR TITLE
[SPARK-6431][Streaming][Kafka] Error message for partition metadata requ...

### PR DESCRIPTION
**Pull request by koeninger**
...ests

The original reported problem was misdiagnosed; the topic just didn't exist yet.  Agreed upon solution was to improve error handling / message

### CODE REVIEW

**Comment by harishreedharan** [comment]
I am not sure if I can ask Jenkins to test a patch that isn't mine, but I will try and see if Jenkins likes me.

**Comment by harishreedharan** [comment]
Jenkins, test this please

**Comment by harishreedharan** [comment]
LGTM btw :-)

**Comment by srowen** [comment]
ok to test

**Pull request closed without merging**
