### PR TITLE
[MLLIB] [SPARK-2222] Add multiclass evaluation metrics

### PR DESCRIPTION
**Pull request by avulanov**
Adding two classes: 
1) MulticlassMetrics implements various multiclass evaluation metrics
2) MulticlassMetricsSuite implements unit tests for MulticlassMetrics

### CODE REVIEW

**Comment by tolgap** [comment]
@avulanov You have added a class called `MulticlassMetrics`, but I do not understand how it operates on multiclass classification? I would understand the usage if it accepts `RDD[(Vector, Vector)]`, but it uses `RDD[(Double, Double)]` and that seems to me like binary classification?

Can you give me an example for... say: the MNIST dataset (10 output neurons). Thanks!

**Comment by avulanov** [comment]
@tolgap As documentation suggests, `MulticlassMetrics` accepts `predictionAndLabels`, an RDD of (prediction, label) pairs, where `prediction` is the predicted class/label, `label` is the actual class/label.

For example:

    import org.apache.spark.mllib.util.MLUtils
    import org.apache.spark.mllib.classification.ANNClassifier
    import org.apache.spark.mllib.evaluation.MulticlassMetrics
    
    /* load mnist data */
    val data = MLUtils.loadLibSVMFile(sc, "mnist_file_in_svm_format")
    val split = data.randomSplit(Array(0.9, 0.1), 11L)
    val training = split(0)
    val test = split(1)
    /* train ANN with hidden layer of 32 neurons */
    /* (input and output layer sizes will be derived from the data) */
    val model = ANNClassifier.train(train, Array[Int](32), 40, 1.0, 1e-4)
    val predictionAndLabels = test.map( lp => (model.predict(lp.features), lp.label))
    val metrics = new MulticlassMetrics(predictionAndLabels)
    println("Accuracy:" + metrics.precision)

**Comment by tolgap** [comment]
@avulanov How many neurons does the output layer have in this case? 1 or 10? Because my current implementation has an output layer of 10 neurons, e.g:

```scala
val output = Array[Double](7.466E-4, 4.16464E-9, 0.0, 0.0, 0.99462, /*..*/)
```
In this case, this example has the highest probability of being the digit `4` (fifth element has highest probability).

**Comment by avulanov** [comment]
@tolgap ANNClassifier will create 10 output neurons for mnist, 10 is the number of distinct labels derived from the data. Each class usually is encoded with a separate output neuron, especially when there are no explicit relations (or ordering) between classes.

**Pull request closed without merging**
