### PR TITLE
[SPARK-39441][SQL] Speed up DeduplicateRelations

### PR DESCRIPTION
**Pull request by allisonwang-db**
### What changes were proposed in this pull request?

This PR improves the performance of the Analyzer rule `DeduplicateRelations`. It removes the new HashSet created by each recursive call and uses a global HashSet to keep track of the visited relations.

### Why are the changes needed?

Improve Analyzer performance. Here is the result of TPCDSQuerySuite:
```
// Before this PR
org.apache.spark.sql.catalyst.analysis.DeduplicateRelations  269181786 / 1028666896   124 / 1302
// After this PR
org.apache.spark.sql.catalyst.analysis.DeduplicateRelations  144507333 / 643810447    124 / 1302
```

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Existing unit tests.

### CODE REVIEW

**Comment by LuciferYang** [comment]
```
// Before this PR
org.apache.spark.sql.catalyst.analysis.DeduplicateRelations  269181786 / 1028666896   124 / 1302
// After this PR
org.apache.spark.sql.catalyst.analysis.DeduplicateRelations  144507333 / 643810447    124 / 1302
```

Is the result generated by GA? The result of running on Apple Slicon  is not obvious:


```
// Before this PR                                
org.apache.spark.sql.catalyst.analysis.DeduplicateRelations                           160016165 / 616311392                         124 / 1302                                
// After this PR
org.apache.spark.sql.catalyst.analysis.DeduplicateRelations                           142171253 / 605930543                       124 / 1302  
```

**Comment by allisonwang-db** [comment]
@LuciferYang I am running on M1 as well. Indeed the runtime for the TPCDSQuerySuite can vary over the runs.

**Comment by allisonwang-db** [comment]
cc @cloud-fan

**Review by cloud-fan — APPROVED** [review]

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Pull request closed without merging**
