### PR TITLE
[SPARK-10931][PYSPARK][ML] PySpark ML Models should contain Param values

### PR DESCRIPTION
**Pull request by evanyc15**
PySpark spark.ml Models are generally wrappers around Java objects and do not even contain Param values. This JIRA is for copying the Param values from the Estimator to the model.
This can likely be solved by modifying Estimator.fit to copy Param values, but should also include proper unit tests.

### CODE REVIEW

**Comment by holdenk** [comment]
Just a heads up that this has merge conflicts that need to be resolved so jenkins can the tests on it.

**Comment by evanyc15** [comment]
Hey all,

I've resolved the merge conflicts.

Thanks,

**Comment by sethah** [comment]
This approach only copies shared params like `HasFeatureCol` through class inheritance. Parameters defined in the actual model itself are not copied, so this patch won't mimic the scala side exactly. For example, the `NaiveBayes` smoothing parameter is not copied to the Naive Bayes model. It seems like we should copy all params from estimator to model, not just shared ones. Doing so likely requires manually copying those parameters through the model constructor or similar approach. The other approach proposed by @jkbradley in [the jira](https://issues.apache.org/jira/browse/SPARK-10931) is to override `getattr` but has the problem of not generating docs.

I like the latter approach but the lack of doc generation may be a deal breaker. cc @holdenk

**Comment by holdenk** [comment]
@jkbradley probably is the best to check with, I'm not sure how important the pydoc generation would be for the models. The approach often taken in the scala code is to make a shared Params class that both the model and the estimator inherit which seems like it might offer some nice tradeoffs (we don't have to duplicate the list of params everywhere, custom params are able to be copied, and doc gen works) but it does add some extra bit of code per-model so if we don't care about the pydoc that much it might not be a good solution

**Comment by jkbradley** [comment]
Sorry for the slow response on this.  I definitely would want the doc available.  This will depend on the decision made on [https://issues.apache.org/jira/browse/SPARK-14033], so I'll hold off on a detailed review.  But in the meantime, I'll play around with possible solutions.

**Comment by jkbradley** [comment]
We decided not to do SPARK-14033, so this can proceed.  I'll try a few possibilities, but let me know if you have updates!

**Comment by jkbradley** [comment]
add to whitelist

**Comment by jkbradley** [comment]
Jenkins test this please

**Comment by jkbradley** [comment]
It will be great to get this into 2.0.  I still haven't found time to test solutions which avoid copying a lot of code, but I hope to soon.

**Comment by jkbradley** [comment]
@evanyc15 Let me know if you'd like help getting this PR merged.  I know you waited a long time. Thanks!

**Comment by evanyc15** [comment]
Hey Joseph,

I'll work on getting the merge conflicts resolved.

Thank you

**Comment by jkbradley** [comment]
OK, thanks!

**Comment by evanyc15** [comment]
Hey Joseph,

Just pushed in the new changes.

Thank you

**Comment by evanyc15** [comment]
Jenkins, test this please.

**Comment by evanyc15** [comment]
CC @MLnick. Can you please review my code?
Thank you

**Comment by MLnick** [comment]
@evanyc15 this won't make 2.0, so I'll take a look after 2.0 release. By the way, you need to rebase to master in order to avoid pulling in all the commits in the PR

**Comment by evanyc15** [comment]
Updated branch to the newest Spark changes

**Comment by vanzin** [comment]
@evanyc15 the PR looks really messed up now. Can you fix it, or close it and open a new one please? thanks

**Comment by evanyc15** [comment]
Yeah, I'll take a look. Thanks

**Comment by evanyc15** [comment]
New Pull Request #14653 created for this.

**Pull request closed without merging**
