### PR TITLE
[SPARK-23461][R]vignettes should include model predictions for some ML models

### PR DESCRIPTION
**Pull request by huaxingao**
## What changes were proposed in this pull request?

Add model predictions for Linear Support Vector Machine (SVM) Classifier, Logistic Regression, GBT, RF and DecisionTree in vignettes.

## How was this patch tested?

Manually ran the test and checked the result.

### CODE REVIEW

**Review by felixcheung — COMMENTED** [review]
can you check what the output pdf/html content looks like? we sometimes has a long or unreadable output, that doesn't quite fit in the vignettes

**Comment by huaxingao** [comment]
Here is the output for Linear SVM Classifier in sparkr-vignettes.html.
```
prediction <- predict(model, training)
head(select(prediction, "Class", "Sex", "Age", "Freq", "Survived", "prediction"))
##   Class    Sex   Age Freq Survived prediction
## 1   1st   Male Child    0       No        Yes
## 2   2nd   Male Child    0       No        Yes
## 3   3rd   Male Child   35       No        Yes
## 4  Crew   Male Child    0       No        Yes
## 5   1st Female Child    0       No        Yes
## 6   2nd Female Child    0       No        Yes
```

**Comment by felixcheung** [comment]
ok then, thanks

**Comment by felixcheung** [comment]
LGTM

**Comment by felixcheung** [comment]
merged to master

**Comment by huaxingao** [comment]
@felixcheung Thanks a lot for your help!

**Pull request closed without merging**
