### PR TITLE
[SPARK-44277][BUILD] Upgrade to Avro 1.11.2

### PR DESCRIPTION
**Pull request by iemejia**
### What changes were proposed in this pull request?

Upgrade Avro dependency to version 1.11.2

### Why are the changes needed?

To keep up with upstream

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Normal Spark build tests.

### CODE REVIEW

**Comment by iemejia** [comment]
R: @dongjoon-hyun

**Comment by HyukjinKwon** [comment]
Looks fine but mind retriggering https://github.com/iemejia/spark/runs/14739443286?

**Review by yaooqinn — APPROVED** [review]

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Review by dongjoon-hyun — COMMENTED** [review]
+1, late LGTM. Thank you, @iemejia and all.

**Pull request closed without merging**
