### PR TITLE
SPARK-8918 Add @since tags to mllib.clustering

### PR DESCRIPTION
**Pull request by XiaoqingWang**

### CODE REVIEW

**Comment by mengxr** [comment]
ok to test

**Comment by mengxr** [comment]
@yu-iskw Could you help review this PR? Thanks!

**Comment by yu-iskw** [comment]
Alright. I'll check this PR later.

**Comment by yu-iskw** [comment]
@XiaoqingWang thank you for the contribution! And sorry for the delay of my response. It seems that you added the annotations based on `branch-1.4`. However, such a `GaussianMixtureModel.predict(point: Vector)` method doesn't exist on the mater branch. I have no idea why SPARK-8481 wasn't merged into the mater branch. I am asking that to @jkbradley at #6906.

Apart from that, it seems that you try to merge this PR into `branch-1.4`. According to JIRA, the target version SPARK-8918 is 1.5.0. I think you should implement this PR based on the master branch and send a PR to the master branch. 

Could you close this PR and then resend a new one to change the target branch. Since we can't change the target branch after sending a PR. And you should add annotations based on the master branch. Thanks!

**Comment by mengxr** [comment]
@XiaoqingWang Could you send the PR to the master branch as @yu-iskw suggested?

**Comment by jkbradley** [comment]
Pinging for updates  (Thanks!)

**Comment by mengxr** [comment]
I'm taking this PR over. Thanks @XiaoqingWang for making the initial pass!

**Comment by XiaoqingWang** [comment]
a new pull request (apache/spark#8229) for this has been submited,I am sorry for the delay,please help to review ,thanks

**Pull request closed without merging**
