### PR TITLE
[SPARK-43956][SQL][3.3] Fix the bug doesn't display column's sql for Percentile[Cont|Disc]

### PR DESCRIPTION
**Pull request by beliefer**
### What changes were proposed in this pull request?
This PR used to backport https://github.com/apache/spark/pull/41436 to 3.3

### Why are the changes needed?
Fix the bug doesn't display column's sql for Percentile[Cont|Disc].

### Does this PR introduce _any_ user-facing change?
'Yes'.
Users could see the correct sql information.

### How was this patch tested?
Test cases updated.

### CODE REVIEW

**Review by MaxGekk — APPROVED** [review]
Waiting for CI.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by dongjoon-hyun** [comment]
All tests passed. Merged to branch-3.3.

**Comment by dongjoon-hyun** [comment]
Thank you, @beliefer and @MaxGekk .

**Comment by beliefer** [comment]
@dongjoon-hyun @MaxGekk Thank you!

**Pull request closed without merging**
