### PR TITLE
[SPARK-5447][SQL] Replace reference 'schema rdd' with DataFrame @rxin.

### PR DESCRIPTION
**Pull request by darroyocazorla**

### CODE REVIEW

**Comment by sarutak** [comment]
ok to test

**Comment by sarutak** [comment]
LGTM.

**Comment by rxin** [comment]
LGTM too.

**Comment by rxin** [comment]
Jenkins, ok to test.

**Comment by rxin** [comment]
I'm going to merge this. Thanks.

**Pull request closed without merging**
