### PR TITLE
[SPARK-35693][SS][TEST] Add plan check for stream-stream join unit test

### PR DESCRIPTION
**Pull request by c21**
### What changes were proposed in this pull request?

The changed [unit test](https://github.com/apache/spark/blob/master/sql/core/src/test/scala/org/apache/spark/sql/streaming/StreamingJoinSuite.scala#L566) was introduce in https://github.com/apache/spark/pull/21587, to fix the planner side of thing for stream-stream join. Ideally check the query result should catch the bug, but it would be better to add plan check to make the purpose of unit test more clearly and catch future bug from planner change. 

### Why are the changes needed?

Improve unit test.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Changed test itself.

### CODE REVIEW

**Comment by c21** [comment]
cc @cloud-fan (original author) if you have time to take a look, thanks.

**Comment by c21** [comment]
Close & Reopen PR to trigger unit test on github action again.

**Review by cloud-fan — APPROVED** [review]

**Comment by c21** [comment]
Rebased to latest master.

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Comment by c21** [comment]
Thank you @cloud-fan for review!

**Pull request closed without merging**
