### PR TITLE
[SPARK-13548][BUILD] Move tags and unsafe modules into common

### PR DESCRIPTION
**Pull request by rxin**
## What changes were proposed in this pull request?

This patch moves tags and unsafe modules into common directory to remove 2 top level non-user-facing directories.
## How was this patch tested?

Jenkins should suffice.

### CODE REVIEW

**Comment by rxin** [comment]
cc @srowen are there other things we can easily do?

**Comment by srowen** [comment]
I like this -- I assume `common` is for modules that don't even depend on Spark Core and could even be separated from Spark. That seems true of both of these, so, OK.

The next change I'd suggest is putting `extras/*` into `external`, and likewise for both `docker*` modules.

The only weird thing there is that `java8-tests` isn't exactly "external". I suppose it goes away as soon as Spark requires Java 8, so if it's odd, at least it won't last too long.

I'd also like to unify the various "config / build / binary" dirs, but that's going to be a little more disruptive or need more discussion about the theory.

**Comment by rxin** [comment]
"I suppose it goes away as soon as Spark requires Java 8, so if it's odd, at least it won't last too long."

That's probably at least one year away...!

**Comment by rxin** [comment]
Alright merging this in master.

**Pull request closed without merging**
