### PR TITLE
[SPARK-39219][DOC] Promote Structured Streaming over DStream

### PR DESCRIPTION
**Pull request by HeartSaVioR**
### What changes were proposed in this pull request?

This PR proposes to add NOTE section for DStream guide doc to promote Structured Streaming. 

Screenshot:

screenshot-spark-streaming-programming-guide-change

### Why are the changes needed?

We see efforts of community are more focused on Structured Streaming (based on Spark SQL) than Spark Streaming (DStream). We would like to encourage end users to use Structured Streaming than Spark Streaming whenever possible for their workloads.

### Does this PR introduce _any_ user-facing change?

Yes, doc change.

### How was this patch tested?

N/A

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
cc. @gengliangwang

**Comment by HeartSaVioR** [comment]
It would be ideal if we can ship this change to all release branches.

**Review by gengliangwang — APPROVED** [review]
LGTM! I once found this confusing too.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @HeartSaVioR and @gengliangwang .

**Comment by HeartSaVioR** [comment]
Thanks all, merging to master/3.3/3.2/3.1 (assuming 3.1 is still not EOL)

**Pull request closed without merging**
