### PR TITLE
[SPARK-29256][DOCS] Fix typo in building document

### PR DESCRIPTION
**Pull request by TomokoKomiyama**
### What changes were proposed in this pull request?
 Changed 'Phive-thriftserver' to ' -Phive-thriftserver'.

### Why are the changes needed?
 Typo 

### Does this PR introduce any user-facing change?
Yes.

### How was this patch tested?
Manually tested.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
ok to test

**Comment by dongjoon-hyun** [comment]
Thanks. Looks correct, @TomokoKomiyama . Is this the last typo? Could you try to find more instance on that document?

**Comment by TomokoKomiyama** [comment]
@dongjoon-hyun I tried it, but I can't find so far.

Thank you for teaching me about `[MINOR]`.

**Comment by srowen** [comment]
Merged to master. You don't need a JIRA for MINOR issues

**Comment by dongjoon-hyun** [comment]
Thank you, @TomokoKomiyama and @srowen .

**Pull request closed without merging**
