### PR TITLE
[WIP][SPARK-XXXX]Turns `pre-built package` into a link to pre-built packages

### PR DESCRIPTION
**Pull request by IRobL**
Thanks for sending a pull request!  Here are some tips for you:
  1. If this is your first time, please read our contributor guidelines: https://spark.apache.org/contributing.html
  2. Ensure you have added or run the appropriate tests for your PR: https://spark.apache.org/developer-tools.html
  3. If the PR is unfinished, add '[WIP]' in your PR title, e.g., '[WIP][SPARK-XXXX] Your PR title ...'.
  4. Be sure to keep the PR description updated to reflect all changes.
  5. Please write your PR title to summarize what this PR proposes.
  6. If possible, provide a concise example to reproduce the issue for a faster review.

### What changes were proposed in this pull request?

Please clarify what changes you are proposing. The purpose of this section is to outline the changes and how this PR fixes the issue. 
If possible, please consider writing useful notes for better and faster reviews in your PR. See the examples below.
  1. If you refactor some codes with changing classes, showing the class hierarchy will help reviewers.
  2. If you fix some SQL features, you can provide some references of other DBMSes.
  3. If there is design documentation, please add the link.
  4. If there is a discussion in the mailing list, please add the link.

### Why are the changes needed?

Please clarify why the changes are needed. For instance,
  1. If you propose a new API, clarify the use case for a new API.
  2. If you fix a bug, you can clarify why it is a bug.
-->

### Does this PR introduce any user-facing change?

If yes, please clarify the previous behavior and the change this PR proposes - provide the console output, description and/or an example to show the behavior difference if possible.
If no, write 'No'.
-->

### How was this patch tested?

If tests were added, say they were added here. Please make sure to add some test cases that check the changes thoroughly including negative and positive cases if possible.
If it was tested in a way different from regular unit tests, please clarify how you tested step by step, ideally copy and paste-able, so that other reviewers can test and check, and descendants can verify in the future.
If tests were not added, please describe why they were not added and/or why it was difficult to add.
-->

### CODE REVIEW

**Comment by srowen** [comment]
This is OK, but please clean up the PR description and title per https://spark.apache.org/contributing.html
Any other text that could be usefully turned into a link?

**Comment by IRobL** [comment]
https://archive.apache.org/dist/spark/spark-2.2.0/

**Comment by srowen** [comment]
Where is that? update the PR and description accordingly, please.

**Comment by IRobL** [comment]
Thank you, great work on this repo, btw!

**Comment by srowen** [comment]
Oh I didn't merge this - closed it for lack of followup. See above

**Comment by IRobL** [comment]
Yes, I understand the situation.  I meant it's ok that it's a PR.  It's probably easier that the link be in a PR than adding it to the readme itself on master.  I don't really have a Jira anyway.

**Pull request closed without merging**
