### PR TITLE
[SPARK-23674] Add Spark ML Listener for Tracking ML Pipeline Status

### PR DESCRIPTION
**Pull request by jmwdpk**
coauthored with @merlintang  mingjie tang  tangrock@gmail.com

## What changes were proposed in this pull request?

In order to keep track of the status of Spark ML pipeline, trait MLListenEvent to monitor the [jira](https://issues.apache.org/jira/browse/SPARK-23674) proposed events was added; trait MLListener  used onEvent method to overide doPostEvent in ListenerBus and post the events to specific listener. 

In Pipeline.scala, PipelineStage now extends with ListenerBus, so that the related events can be posted to specific listener by doPostEvent. All pipeline related events were posted to all registered listeners by postToAll

In ReadWrite.scala, MLWriter now extends with ListenerBus, so that the save-related events can be posted to specific listener

## How was this patch tested?

When testing the features, a recorder was created as a mutable buffer to catch/listen to the actual pipeline events, all the events were added to the recorder by the overridden onEvent method in the newly created MLListener, which was add to the object(pipeline/newPipelineModel/pipelineWritter/pipelineModelWritter) corresponding to the operation(fit/transform/save/save) associated with each type of event, finally the actual captured events were compared with the expected events specified in the tests.

Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Comment by merlintang** [comment]
@jmwdpk can you update this pr, since there is conflict. I have update this pr. https://github.com/merlintang/spark/commits/SPARK-23674

**Comment by merlintang** [comment]
@holdenk can you look at this PR? thanks in advance.

**Comment by merlintang** [comment]
ok to test

**Comment by HyukjinKwon** [comment]
It was taken over by `https://github.com/apache/spark/pull/23263`.

**Pull request closed without merging**
