### PR TITLE
[SPARK-3665][GraphX] Java API for GraphX

### PR DESCRIPTION
**Pull request by ankurdave**
Adds JavaGraph (which also contains methods from GraphOps), JavaVertexRDD, JavaEdgeRDD, and tests for these classes.

### CODE REVIEW

**Comment by andrewor14** [comment]
Hi @ankurdave is this still targeted for 1.4 now?

**Comment by brennonyork** [comment]
Would also like to know the status. This looks to be the last piece to graduate GraphX from alpha to stable re: [SPARK-3664](https://issues.apache.org/jira/browse/SPARK-3664).

**Comment by rxin** [comment]
@brennonyork graphx has already graduated from alpha. We will make sure this goes into 1.4.

**Comment by sryza** [comment]
Mind tagging this with [GRAPHX] so it can get sorted properly?

**Comment by kdatta** [comment]
I had to add the Junit dependency in graphx/pom.xml to compile. Did you see this issue? We might have to update the pom file.

-Kushal.

**Comment by srowen** [comment]
@ankurdave what happened to this? should this PR be closed?

**Comment by JoshRosen** [comment]
Hey @ankurdave, it looks like this PR has gone stale, so do you mind closing it for now and re-opening it once you're ready to work on it again?

**Comment by kdatta** [comment]
Hi Josh, Ankur,

We have a dependence on this story for PyGraphX. We are close to completing the PyGraphX work and would like this code to be reviewed and approved.

Thanks,
-Kushal.

**Comment by srowen** [comment]
(For Jenkins:) Do you mind closing this PR then?

**Comment by kdatta** [comment]
Don't mind at all. We will submit the design doc of PyGraphX by early next week. Will close this PR after.

**Comment by ankurdave** [comment]
@JoshRosen @srowen Sorry I didn't see your requests to close earlier. Closing now.

**Pull request closed without merging**
