### PR TITLE
[Spark-27584][MLlib] Add 'Mean reciprocal rank' to RankingMetrics

### PR DESCRIPTION
**Pull request by pntuananh**
## What changes were proposed in this pull request?

Add 'Mean reciprocal rank' to RankingMetrics, which is usually used for ranking evaluation.

## How was this patch tested?

Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Comment by srowen** [comment]
I don't think this is important enough to add... .mllib is a legacy API anyway.

**Comment by holdenk** [comment]
+1 mllib is no longer under active development (bug fixes only).

**Comment by holdenk** [comment]
What about adding mean recipricoal rank to the new ML apis?

**Comment by srowen** [comment]
@holdenk yeah fair point. Right now the .ml implementation doesn't already support meanAveragePrecision or anything. I think that could be a fine separate PR.

**Pull request closed without merging**
