### PR TITLE
[SPARK-37052][CORE] Spark should only pass --verbose argument to main class when is sql shell

### PR DESCRIPTION
**Pull request by AngersZhuuuu**
### What changes were proposed in this pull request?
In https://github.com/apache/spark/pull/32163 spark pass `--verbose` to main class o support spark-sql shell can use verbose argument too. 
But for other shell main class such as saprk-shell, it's intercepter don't support `--verbose`, so we should only pass `--verbose` for sql shell

### Why are the changes needed?
Fix bug

### Does this PR introduce _any_ user-facing change?
No

### CODE REVIEW

**Comment by AngersZhuuuu** [comment]
ping @cloud-fan @HyukjinKwon @yaooqinn @LuciferYang

**Comment by LuciferYang** [comment]
@toujours33 let us pick this to our branch to verify it

**Review by yaooqinn — APPROVED** [review]
LGTM

**Review by HyukjinKwon — APPROVED** [review]

**Review by cloud-fan — APPROVED** [review]

**Review by LuciferYang — APPROVED** [review]
LGTM(nonbinding)

**Comment by cloud-fan** [comment]
thanks, merging to master/3.2!

**Pull request closed without merging**
