### PR TITLE
[SPARK-25594] [Core] Avoid maintaining task information when UI is disabled

### PR DESCRIPTION
**Pull request by mridulm**
## What changes were proposed in this pull request?

Avoid maintaining task information in live spark application when UI is disabled.
For long running application, with large number of tasks, this ended up causing OOM in our tests.

## How was this patch tested?

Long running test successfully ran for 34 hours with steady memory, when it used to fail in 28 hours with OOM earlier.

### CODE REVIEW

**Comment by mridulm** [comment]
ok to test

**Comment by mridulm** [comment]
+CC @vanzin, @tgravescs

**Comment by shahidki31** [comment]
Hi @mridulm , Can't we limit the task information by setting 'spark.ui.retainedTasks' lesser, to avoid OOM? correct me if I am wrong.

**Comment by mridulm** [comment]
This is a regression introduced in 2.3; unfortunately we did not notice it
until now.

**Comment by gengliangwang** [comment]
Hi @mridulm ,

it seems that the changes will affect the metrics in `SparkStatusTracker`, e.g.  number of active tasks in `getExecutorInfos` or `getStageInfo` .

Maybe we should maintain number of active/total/complete/failed tasks as well.

**Comment by vanzin** [comment]
@gengliangwang is right; there are still things that need to be done when the UI is disabled; job, stage and executor info are all still exposed even if the UI is disabled, and the task even callbacks update those.

It might be as easy as not adding the task to `liveTasks` in `onTaskStart`, but haven't really looked in detail.

**Comment by mridulm** [comment]
@vanzin , @gengliangwang To clarify earlier behavior - if UI is disabled, any task related metrics were reported as zero: granularity of update was at the stage level.
UI is typically disabled when application does not want additional overheads associated with it (users leverage history server to see the application state) : particularly in multi-tenant settings (like thrift server) or very large applications (processing PB's of data).
If UI is enabled (default) or if application is not `live` (history server), task events would be processed.

Unfortunately, application + config, which used to work before 2.3 are now throwing OOM (typically, the long running tests are run for 7+ days to find any kerberos related issues - here a LR stress test failed within 28 hours) - and large part of the heap was occupied by TaskDataWrapper; making this a regression.

**Comment by mridulm** [comment]
@vanzin any reason why liveStore is hardcoded to be in-memory ? Any implications of making it disk backed ? That might be another option to unblock - requires a config change to existing applications; but way better than OOM

**Comment by mridulm** [comment]
> I tried that a lot while writing this code, but the disk store is just too slow

That is unfortunate ... I was actually hoping that would be a good compromise if expanded api needs to be preserved.

>  if UI is disabled, any task related metrics were reported as zero:

I was incorrect in this regard - they were not zero, but JobProgressListener had stage/job counters which maintained this.
This was limited to job and stage level though - keeping the actual overhead fairly minimal and honoring spark.ui.retainedStages/spark.ui.retainedJobs.


Given this, current PR would be a functionality regression - since we end up loosing information we would otherwise expose.

**Comment by mridulm** [comment]
I will close the PR and document in our tests to use spark.ui.retainedTasks = 1 (or some very low value) : which will, in effect, be equivalent to this PR - and loose information anyway; but will be specific to the application which choose to do it (and which does not care about the api).

**Pull request closed without merging**
