### PR TITLE
[SPARK-36166][TESTS][FOLLOWUP] Add BLOCK_SCALA_VERSION to sparktestssupport/__init__.py

### PR DESCRIPTION
**Pull request by sarutak**
### What changes were proposed in this pull request?

This is a followup PR for SPARK-36166 (#33411), which adds `BLOCK_SCALA_VERSION` to `sparktestssupport/__init__.py`.

### Why are the changes needed?

The following command fails due to the definition is missing.
```
SCALA_PROFILE=scala2.12 dev/run-tests.py
```

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

The command shown above works.

### CODE REVIEW

**Comment by sarutak** [comment]
cc: @HyukjinKwon

**Comment by HyukjinKwon** [comment]
oops, thanks man!

**Comment by HyukjinKwon** [comment]
Merged to master and branch-3.2.

**Comment by dongjoon-hyun** [comment]
Thank you, @sarutak .

**Pull request closed without merging**
