### PR TITLE
[SPARK-15012][SQL] Simplify configuration API further

### PR DESCRIPTION
**Pull request by andrewor14**
## What changes were proposed in this pull request?
1. Remove all the `spark.setConf` etc. Just expose `spark.conf`
2. Make `spark.conf` take in things set in the core `SparkConf` as well, otherwise users may get confused

This was done for both the Python and Scala APIs.
## How was this patch tested?

`SQLConfSuite`, python tests.

### CODE REVIEW

**Comment by andrewor14** [comment]
@rxin

**Comment by andrewor14** [comment]
Note: this will conflict with #12784. The python changes there should be merged first.

**Comment by andrewor14** [comment]
OK, #12784 is now merged. Let's retest this please.

**Comment by yhuai** [comment]
test this please

**Comment by yhuai** [comment]
LGTM

**Comment by yhuai** [comment]
```
======================================================================
ERROR [0.000s]: test_conf (pyspark.sql.tests.SQLTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jenkins/workspace/NewSparkPullRequestBuilder/python/pyspark/sql/tests.py", line 1400, in test_conf
    spark.setConf("bogo", "sipeo")
AttributeError: 'SparkSession' object has no attribute 'setConf'

----------------------------------------------------------------------
Ran 93 tests in 94.519s

FAILED (errors=1)

Generating XML reports...
```

**Pull request closed without merging**
