### PR TITLE
[SPARK-45741][BUILD] Upgrade Netty to 4.1.100.Final

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to upgrade `Netty` to 4.1.100.Final.

### Why are the changes needed?

To bring the latest bug fixes
- https://github.com/netty/netty/milestone/280?closed=1
- https://github.com/netty/netty/releases/tag/netty-4.1.100.Final

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the CIs.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Review by viirya — APPROVED** [review]
Pending CI

**Comment by dongjoon-hyun** [comment]
Thank you, @viirya !

**Review by LuciferYang — APPROVED** [review]
+1, LGTM

**Comment by dongjoon-hyun** [comment]
Thank you, @LuciferYang .

**Comment by dongjoon-hyun** [comment]
Merged to master for Apache Spark 4.0.0.

**Comment by ulysseskan** [comment]
@dongjoon-hyun Netty 4.1.100 also [fixes an HTTP2 DDOS attack vector](https://netty.io/news/2023/10/10/4-1-100-Final.html).  Are there any plans to bring Netty 4.1.100 into Apache Spark 3.x in the next 2 months?

**Comment by dongjoon-hyun** [comment]
No, we don't have for now, @ulysseskan .

**Comment by 1210170281-yyds** [comment]
将 Netty 4.1.100 引入 Apache Spark 3.x中会不会有问题

**Pull request closed without merging**
