### PR TITLE
[SPARK-17558] Bump Hadoop 2.7 version from 2.7.2 to 2.7.3

### PR DESCRIPTION
**Pull request by rxin**
## What changes were proposed in this pull request?

This patch bumps the Hadoop version in hadoop-2.7 profile from 2.7.2 to 2.7.3, which was recently released and contained a number of bug fixes.
## How was this patch tested?

The change should be covered by existing tests.

### CODE REVIEW

**Comment by rxin** [comment]
cc @JoshRosen @srowen

**Comment by srowen** [comment]
+1, can't hurt

**Comment by rxin** [comment]
Merging in master/2.0.

**Comment by srowen** [comment]
The only difference was that you're also making 2.7 the default, which isn't bad or anything. Otherwise i think it was just an oversight. There's way too much traffic to keep track of unfortunately, which is why I encourage steps to reduce the noise on lists/JIRA/PRs.

You have a couple WIP PRs you've bene updating for a while so I also sort of look past yours unfortunately in the email flood as I think they're just WIP updates.

**Comment by steveloughran** [comment]
thanks for clarifying; sometimes I feel that my patches get under reviewed —which holds for Hadoop too, where some have been outstanding for so long they're approach school age

**Comment by srowen** [comment]
https://github.com/apache/spark/pull/14731 is waiting on your response if I read it correctly; https://github.com/apache/spark/pull/12004 is a WIP (not sure if that's going to get merged anyway); https://github.com/apache/spark/pull/9571 seems to have some comments from Marcelo;  https://github.com/apache/spark/pull/14646 I'm not sure is necessary -- was it to be committed? https://github.com/apache/spark/pull/13579 has a question for you from Marcelo. I'm not sure you're being ignored?

**Pull request closed without merging**
