### PR TITLE
Revert "[SPARK-41498] Propagate metadata through Union"

### PR DESCRIPTION
**Pull request by cloud-fan**
This reverts commit 827ca9b82476552458e8ba7b01b90001895e8384.

### What changes were proposed in this pull request?

After more thinking, it's a bit fragile to propagate metadata columns through Union. We have added quite some new fields in the file source `_metadata` metadata column such as `row_index`, `block_start`, etc. Some are parquet only. The same thing may happen in other data sources as well. If one day one table under Union adds a new metadata column (or add a new field if the metadata column is a struct type), but other tables under Union do not have this new column, then Union can't propagate metadata columns and the query will suddenly fail to analyze.

To be future-proof, let's revert this support.

### Why are the changes needed?

to make the analysis behavior more robust.

### Does this PR introduce _any_ user-facing change?

Yes, but propagating metadata columns through Union is not released yet.

### How was this patch tested?

N/A

### CODE REVIEW

**Comment by cloud-fan** [comment]
cc @fred-db @bart-samwel

**Comment by cloud-fan** [comment]
also cc @xinrong-meng , this should be included in 3.4.0

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. I agree with @cloud-fan .

**Comment by dongjoon-hyun** [comment]
Merged to master/3.4.

**Pull request closed without merging**
