### PR TITLE
[DOCS][SPARKR] Use verbose names for family annotations in functions.R

### PR DESCRIPTION
**Pull request by zero323**
## What changes were proposed in this pull request?

- Change current short annotations (same as Scala `@group`) to verbose names (same as Scala `@groupname`). 

    Before:

    image

    After:
    image

- Add missing `@family` annotations.

## How was this patch tested?

`check-cran.R` (skipping tests), manual inspection.

### CODE REVIEW

**Comment by zero323** [comment]
Note: if multiple functions use the same `@rdname`, there is only `@family` annotation to avoid duplicated _See also_ section.

**Review by felixcheung — APPROVED** [review]
LGTM

**Comment by felixcheung** [comment]
merged to master. thanks!

**Comment by zero323** [comment]
Thanks Felix!

**Pull request closed without merging**
