### PR TITLE
[SPARK-28715][SQL] Introduce collectInPlanAndSubqueries and subqueriesAll in QueryPlan

### PR DESCRIPTION
**Pull request by dbaliafroozeh**
## What changes were proposed in this pull request?

Introduces the collectInPlanAndSubqueries and subqueriesAll methods in QueryPlan that consider all the plans in the query plan, including the ones in nested subqueries.

## How was this patch tested?

Unit test added

### CODE REVIEW

**Comment by hvanhovell** [comment]
ok to test

**Comment by hvanhovell** [comment]
ok to test

**Review by hvanhovell — APPROVED** [review]
LGTM - pending jenkins

**Comment by dongjoon-hyun** [comment]
ok to test

**Comment by hvanhovell** [comment]
Merging to master. Thanks!

**Pull request closed without merging**
