### PR TITLE
[SPARK-48116][INFRA][FOLLOW-UP] Deduplicate pyspark.pandas skipping logic

### PR DESCRIPTION
**Pull request by HyukjinKwon**
### What changes were proposed in this pull request?

This PR is another try of https://github.com/apache/spark/pull/46380 that is a followup of https://github.com/apache/spark/pull/46367 that simplifies the build and deduplicate them.

### Why are the changes needed?

To fix the condition, and make it deduplicated.

### Does this PR introduce _any_ user-facing change?

No, dev-only.

### How was this patch tested?

Will test in my own fork: https://github.com/HyukjinKwon/spark/actions/runs/8948215777

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Tested at https://github.com/HyukjinKwon/spark/actions/runs/8948215777/job/24581131687

cc @dongjoon-hyun

**Comment by HyukjinKwon** [comment]
Screenshot 2024-05-04 at 2 21 43 PM

vs

Screenshot 2024-05-04 at 2 22 15 PM

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by dongjoon-hyun** [comment]
Feel free to merge when you think it's ready, @HyukjinKwon .
Thank you so much!

**Comment by HyukjinKwon** [comment]
Will merge later when I get back home :-)

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by dongjoon-hyun** [comment]
Thank you a lot!

**Pull request closed without merging**
