### PR TITLE
[SPARK-34309][BUILD][FOLLOWUP] Upgrade Caffeine to 2.9.2

### PR DESCRIPTION
**Pull request by sarutak**
### What changes were proposed in this pull request?

This PR upgrades Caffeine to `2.9.2`.
Caffeine was introduced in SPARK-34309 (#31517). At the time that PR was opened, the latest version of caffeine was `2.9.1` but now `2.9.2` is available.

### Why are the changes needed?

`2.9.2` have the following improvements (https://github.com/ben-manes/caffeine/releases/tag/v2.9.2).

* Fixed reading an intermittent null weak/soft value during a concurrent write
* Fixed extraneous eviction when concurrently removing a collected entry after a writer resurrects it with a new mapping
* Fixed excessive retries of discarding an expired entry when the fixed duration period is extended, thereby resurrecting it

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

CIs.

### CODE REVIEW

**Comment by sarutak** [comment]
Considering the [discussion](https://github.com/apache/spark/pull/31517#issuecomment-897405632), that it's a little bit possible that that PR is reverted but it's better to upgrade it if we retain that change.

**Review by HyukjinKwon — APPROVED** [review]
I'm good w/ this.

**Comment by sarutak** [comment]
Thanks. Merging to `master`.

**Comment by dongjoon-hyun** [comment]
+1, LGTM, too.

**Pull request closed without merging**
