### PR TITLE
[SPARK-46475][BUILD] Upgrade RoaringBitmap to 1.0.1

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to upgrade `RoaringBitmap` from `1.0.0` to `1.0.1`, the last upgrade occurred 3 months ago.

### Why are the changes needed?
Release notes: https://github.com/RoaringBitmap/RoaringBitmap/releases/tag/1.0.1
This version includes some performance improvements:
- More performant LongUtils.compareHigh()
- Use isEmpty() on bitmap instead of getCardinality() > 0

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Is this still `Draft`, @panbingkun ?

**Comment by panbingkun** [comment]
> Is this still `Draft`, @panbingkun ?

Let me add the results of `org.apache.spark.MapStatusesConvertBenchmark`.
JDK 17:
JDK 21:

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by dongjoon-hyun** [comment]
Merged to master for Apache Spark 4.
Thank you, @panbingkun .

**Pull request closed without merging**
