### PR TITLE
[SPARK-12433][CORE][TEST][RFC/WIP] Make parts of spark core testing api public

### PR DESCRIPTION
**Pull request by holdenk**
```
Apache Spark has a wide variety of internal tests, but many of the APIs used for testing are private. To allow external developers to easily test their Spark programs we should expose a minimal set of testing APIs.

Since Spark’s current tests are primarily written with scalatest & junit - these are the two testing library bases that we will support. Much of the desired functionality already exists in the Spark code base, all that is required is making slimmed down versions of existing test bases (so that the API to support remains small) and making them visible.

For core the primary thing we want to abstract away is creating & cleaning up a SparkContext. If we assume that each test will not do anything destructive to the SparkContext this is perhaps unnecessary. This is based on the current LocalSparkContext in testing, we would just need to change its visibility.
```

This PR moves the SharedSparkContext to main in org.apache.spark.utils.testing and introduces a Java version of the API (SharedJavaSparkContext) for Java tests (while also updating JavaAPISuite to use the new SharedJavaSparkContext).

### CODE REVIEW

**Comment by rxin** [comment]
Sorry I don't think we should have this. Also Spark runtime shouldn't depend on a specific version of scalatest.

**Comment by holdenk** [comment]
I'd chatted some with @mateiz about having some public testing API (although not necessarily this approach). @rxin do you think not just so much this approach or not a good idea for Spark its self?

**Comment by rxin** [comment]
It might be useful to have some public testing of some form, but I don't think depending on junit or scalatest is going to fly. I also don't want to just in an ad-hoc way expose some new APIs in Spark. When we did that in the past, we ended up regretting those decisions soon in the future because it limits what we can change.

**Comment by holdenk** [comment]
Ok - I've got the design document and the APIs are based on current internal APIs if you have a chance to look at the API thoughts and give some feedback I'd appreciate it ( https://docs.google.com/document/d/1FBg1qWbzjW0fKt6YxzNEn7vJ7l2y1ZfeM0CSP3JJIBI/edit?usp=sharing )- but I understand if too busy. I can go ahead and close this PR in the meantime since putting the testing inside of the respective components seems like a no go.

**Pull request closed without merging**
