### PR TITLE
[SPARK-32920][FOLLOW-UP][CORE] Shutdown shuffleMergeFinalizeScheduler when DAGScheduler stop 

### PR DESCRIPTION
**Pull request by Ngone51**
### What changes were proposed in this pull request?

Call `shuffleMergeFinalizeScheduler.shutdownNow()` in `DAGScheduler.stop()`.

### Why are the changes needed?

Avoid the thread leak.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass existing tests.

### CODE REVIEW

**Comment by Ngone51** [comment]
cc @mridulm @venkata91

**Comment by venkata91** [comment]
LGTM. Thanks for fixing it @Ngone51

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @Ngone51 and @venkata91

**Comment by dongjoon-hyun** [comment]
Merged to master/3.2.

cc @gengliangwang

**Comment by mridulm** [comment]
Late LGTM, nice catch @Ngone51 !
Thanks for the reviews @dongjoon-hyun, @venkata91

**Pull request closed without merging**
