### PR TITLE
[SPARK-38779] [SQL][Tests] Unify the pushed operator checking between FileSource test suite and JDBCV2Suite

### PR DESCRIPTION
**Pull request by huaxingao**
### What changes were proposed in this pull request?
In `JDBCV2Suite`, we use `checkPushedInfo` to check the pushed down operators. Will do the same for `FileSourceAggregatePushDownSuite`
```
  private def checkPushedInfo(df: DataFrame, expectedPlanFragment: String): Unit = {
    df.queryExecution.optimizedPlan.collect {
      case _: DataSourceV2ScanRelation =>
        checkKeywordsExistsInExplain(df, expectedPlanFragment)
    }
  }
```

### Why are the changes needed?
Make `FileSourceAggregatePushDownSuite` have the same way to check pushed down operators as `JDBCV2Suite` .

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Existing tests

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Given the size of the patch, we need a new JIRA issue for this, @huaxingao .

**Review by srowen — APPROVED** [review]

**Comment by huaxingao** [comment]
@dongjoon-hyun I created Spark-38779 for this. Thanks!

**Review by HyukjinKwon — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @huaxingao , @srowen , @HyukjinKwon .
The linter error is irrelevant to this.

**Comment by huaxingao** [comment]
Thanks all!

**Pull request closed without merging**
