### PR TITLE
[SPARK-6696] [SQL] Adds HiveContext.refreshTable to PySpark

### PR DESCRIPTION
**Pull request by liancheng**
[Review on Reviewable](https://reviewable.io/reviews/apache/spark/5349)

### CODE REVIEW

**Comment by liancheng** [comment]
Didn't write a test for this because we don't have Hive testing infra like `TestHive` in Scala code for PySpark yet. I opened this PR to make code snippets in #5348 more complete. But then I realize we can always use `sqlCtx.sql("REFRESH TABLE my_table")` in Python. So this PR doesn't seem that necessary.

Tested this locally with the following snippet:

```python
import tempfile, shutil

jsonFile = tempfile.mkdtemp()
shutil.rmtree(jsonFile)
sqlCtx.createDataFrame([("a", "b")])\
      .toJSON()\
      .saveAsTextFile(jsonFile)
sqlCtx.sql(
    "CREATE TABLE jt " +
    "USING org.apache.spark.sql.json " +
    "OPTIONS (path '%s')" % jsonFile)
sqlCtx.sql("SELECT * FROM jt").show()
# _1 _2
# a  b

shutil.rmtree(jsonFile)
sqlCtx.createDataFrame([("a", "b", "c")])\
      .toJSON()\
      .saveAsTextFile(jsonFile)
sqlCtx.sql("SELECT * FROM jt").show()
# _1 _2
# a  b

sqlCtx.refreshTable("jt")
sqlCtx.sql("SELECT * FROM jt").show()
# _1 _2 _3
# a  b  c
```

**Comment by rxin** [comment]
Can't we add that testing snippet to tests.py?

**Comment by liancheng** [comment]
We need a properly configured Hive environment to run the test. I can add a simple `TestHive`-like class to do metastore / warehouse configurations though.

**Comment by marmbrus** [comment]
Thanks, I merged this to master.  Would be great to add a TestHive wrapper in a followup PR.

**Pull request closed without merging**
