### PR TITLE
[SPARK-32924][WEBUI] Make duration column in master UI sorted in the correct order

### PR DESCRIPTION
**Pull request by baohe-zhang**
### What changes were proposed in this pull request?

Make the "duration" column in standalone mode master UI sorted by numeric duration, hence the column can be sorted by the correct order.

Before changes:
image

After changes:
image

### Why are the changes needed?

Fix a UI bug to make the sorting consistent across different pages.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Ran several apps with different durations and verified the duration column on the master page can be sorted correctly.

### CODE REVIEW

**Review by tooptoop4 — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @baohe-zhang and @tooptoop4 .

I verified this manually.

**Comment by dongjoon-hyun** [comment]
Merged to master/3.1/3.0/2.4.

cc @viirya since he is the release manager for Apache Spark 2.4.8.

**Comment by dongjoon-hyun** [comment]
BTW, what is your JIRA id, @baohe-zhang ?

**Comment by dongjoon-hyun** [comment]
cc @gengliangwang , too

**Comment by baohe-zhang** [comment]
@dongjoon-hyun My jira user id is `Baohe Zhang`

**Review by gengliangwang — COMMENTED** [review]
late lgtm

**Comment by dongjoon-hyun** [comment]
Thank you, @baohe-zhang . I assigned SPARK-32924 to you.
Thank you for review, @gengliangwang !

**Comment by baohe-zhang** [comment]
@dongjoon-hyun Thanks!

**Pull request closed without merging**
