### PR TITLE
[SPARK-34419][SQL] Move PartitionTransforms.scala to scala directory

### PR DESCRIPTION
**Pull request by sunchao**
### What changes were proposed in this pull request?

Move `PartitionTransforms.scala` from `sql/catalyst/src/main/java/org/apache/spark/sql/catalyst/expressions` to `sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions`.

### Why are the changes needed?

We should put java/scala files to their corresponding directories.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

N/A

### CODE REVIEW

**Comment by sunchao** [comment]
@dongjoon-hyun @viirya could you take a look? this is a trivial change.

**Review by viirya — APPROVED** [review]
lgtm

**Comment by viirya** [comment]
Thanks. Merging to master.

**Review by dongjoon-hyun — COMMENTED** [review]
+1, late LGTM. Thanks!

**Pull request closed without merging**
