### PR TITLE
[SPARK-45589][PYTHON][DOCS] Supplementary exception class

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to supplementary exception class for pyspark docs.

### Why are the changes needed?
Currently, there are only the following classes in the document,
image

Actually:
image

### Does this PR introduce _any_ user-facing change?
Yes, more complete documentation on exception classes.

### How was this patch tested?
- Pass GA.
- Manually test.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by panbingkun** [comment]
Before:
image


After:

**Comment by panbingkun** [comment]
@zhengruifeng @allisonwang-db @HyukjinKwon

**Comment by HyukjinKwon** [comment]
cc @itholic

**Review by HyukjinKwon — APPROVED** [review]

**Review by itholic — APPROVED** [review]
👍

**Review by zhengruifeng — APPROVED** [review]

**Review by MaxGekk — COMMENTED** [review]
Just wonder wouldn't be better to maintain alphabetical order in the list?

**Comment by panbingkun** [comment]
> Just wonder wouldn't be better to maintain alphabetical order in the list?

Yeah, I also noticed this today, but I have slightly reviewed the documents for other projects, such as `pandas`
It doesn't seem to be sorted alphabetically either.
https://pandas.pydata.org/docs/reference/frame.html
image

Of course, in my opinion, I think alphabetical order is easier to find 😄
Should we do this?

**Comment by MaxGekk** [comment]
> Should we do this?

Since you are adding a half of items, please, do that.

**Review by allisonwang-db — APPROVED** [review]
Awesome! Yea let's sort them in alphabetical order.

**Comment by panbingkun** [comment]
> > Should we do this?
> 
> Since you are adding a half of items, please, do that.

Done.

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
