### PR TITLE
[SPARK-11744][Launcher] Fix print version throw exception when using pyspark shell

### PR DESCRIPTION
**Pull request by jerryshao**
Exception details can be seen here (https://issues.apache.org/jira/browse/SPARK-11744).

### CODE REVIEW

**Comment by vanzin** [comment]
LGTM (although you could probably have a single flag for both).

**Comment by jerryshao** [comment]
OK, will update the code.

**Comment by vanzin** [comment]
Merging to master/1.6.

**Comment by nchammas** [comment]
Thanks @jerryshao and @vanzin for resolving this.

**Pull request closed without merging**
