### PR TITLE
[SPARK-29291][CORE][SQL][STREAMING][MLLIB] Change procedure-like declaration to function + Unit for 2.13

### PR DESCRIPTION
**Pull request by srowen**
### What changes were proposed in this pull request?

Scala 2.13 emits a deprecation warning for procedure-like declarations:

```
def foo() {
 ...
```

This is equivalent to the following, so should be changed to avoid a warning:

```
def foo(): Unit = {
  ...
```

### Why are the changes needed?

It will avoid about a thousand compiler warnings when we start to support Scala 2.13. I wanted to make the change in 3.0 as there are less likely to be back-ports from 3.0 to 2.4 than 3.1 to 3.0, for example, minimizing that downside to touching so many files.

Unfortunately, that makes this quite a big change.

### Does this PR introduce any user-facing change?

No behavior change at all.

### How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
It's huge~ :) nit. Just for consistency, could you add `: Unit` for the following three, too?

```
$ git grep "run() = {"
core/src/test/scala/org/apache/spark/SparkContextSuite.scala:    val thread = new Thread() { override def run() = {result = sc.getLocalProperty("testProperty")}}
core/src/test/scala/org/apache/spark/SparkContextSuite.scala:      override def run() = {sc.setLocalProperty("testProperty", "testValue")}}
core/src/test/scala/org/apache/spark/SparkContextSuite.scala:      override def run() = {result = sc.getLocalProperty("testProperty")}}
```

**Comment by srowen** [comment]
Sure, those aren't technically procedure-like syntax, so don't know if they emit a warning, but yes that seems fine.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by dongjoon-hyun** [comment]
Since this PR is big and will get conflicts soon, I'll merge this, @srowen .

**Comment by srowen** [comment]
Yep, thanks. I think this is pretty inevitable for 2.13 support. It helps me now as I bang through all the compile errors and start to fix them.

**Pull request closed without merging**
