### PR TITLE
[MINOR] Typo in ShuffleMapStage.scala

### PR DESCRIPTION
**Pull request by Smith-Cruise**
Simple typo

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
It's okay but mind checking if there are some more typos to fix around here? I am sure there are more.

**Comment by kiszk** [comment]
Also, we are sure there is the same type in other files.

**Comment by Smith-Cruise** [comment]
Okay, I will keep looking. Because I'm studying the Spark source code recently, it will takes some time.

**Comment by HyukjinKwon** [comment]
@Smith-Cruise BTW, let's keep the PR description although it's very minor.

**Pull request closed without merging**
