### PR TITLE
[SPARK-44678][BUILD][3.5] Downgrade Hadoop to 3.3.4

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to downgrade the Apache Hadoop dependency to 3.3.4 in `Apache Spark 3.5` in order to prevent any regression from `Apache Spark 3.4.x`. In other words, although `Apache Spark 3.5.x` will lose many bug fixes of Apache Hadoop 3.3.5 and 3.3.6, it will be in the same situation with `Apache Spark 3.4.x`.
- SPARK-44197 Upgrade Hadoop to 3.3.6 (#41744)
- SPARK-42913 Upgrade Hadoop to 3.3.5 (#39124)
- SPARK-43448 Remove dummy dependency `hadoop-openstack` (#41133)

On top of reverting SPARK-44197 and SPARK-42913, this PR has additional dependency exclusion change due to the following.
- SPARK-43880 Organize `hadoop-cloud` in standard maven project structure (#41380)

### Why are the changes needed?

There is a community report on S3A committer performance regression. Although it's one liner fix, there is no available Hadoop release with that fix at this time.
- HADOOP-18757: Bump corePoolSize of HadoopThreadPoolExecutor in s3a committer (https://github.com/apache/hadoop/pull/5706)

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the CIs.

### CODE REVIEW

**Review by pan3793 — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @pan3793 .

Also, cc @LuciferYang , @sunchao , @viirya

**Review by sunchao — APPROVED** [review]
LGTM

**Review by viirya — APPROVED** [review]

**Comment by viirya** [comment]
Looks good to me.

**Comment by dongjoon-hyun** [comment]
Thank you, @sunchao , @viirya , @pan3793 .
Merged to branch-3.4 for Apache Spark 3.5.0 RC2.

**Comment by LuciferYang** [comment]
late LGTM

**Pull request closed without merging**
