### PR TITLE
[WIP][K8S] Spark operator

### PR DESCRIPTION
**Pull request by jkremser**
ascii

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Hi, @jkremser . Thank you for making a PR.

1. Please follow the PR template. The template is for the community, but this PR intentionally ignore it. The screencast should be an additional attachment for that.
2. Is this the following? Please give a clear explanation if this is your own contribution.
- https://github.com/GoogleCloudPlatform/spark-on-k8s-operator
3. Could you send an email to `dev@spark.apache.org` about this and why this should be inside `Apache Spark` project?

**Comment by dongjoon-hyun** [comment]
cc @holdenk

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
Hi, @jkremser . Thank you for making a PR.

1. Please follow the PR template. The template is for the community, but this PR intentionally ignore it. The screencast should be an additional attachment for that.
2. Is this the following? Please give a clear explanation if this is your own contribution.
- https://github.com/GoogleCloudPlatform/spark-on-k8s-operator
3. Could you send an email to `dev@spark.apache.org` about this and why this should be inside `Apache Spark` project?

**Comment by holdenk** [comment]
Yeah idk if we want this in Spark it's self. The dev@ mailing list is probably the right place to raise this discussion. There are a lot hard coded things in here we would need to change.

**Comment by nrchakradhar** [comment]
This is same as https://github.com/radanalyticsio/spark-operator.

**Comment by dongjoon-hyun** [comment]
Thanks, @nrchakradhar . For me, this seems to dumped from that repo by the author.

I took a look. The current status is difficult to be considered for Apache project contribution because there is no Apache license header and the remaining package name authorship `radanalytics`.

I'd like to recommend @jkremser to reopen this after cleaning up the PR by adding licenses and remove the authorship package name. I'm close this for now.

**Comment by holdenk** [comment]
I think before putting in work on this PR getting buy-in from the `dev@` list might be a good next first step.

**Comment by dongjoon-hyun** [comment]
Definitely, +1 for @holdenk 's comment.

**Comment by jkremser** [comment]
Thanks for looking into this. Ok, I will open the discussion on the dev list. I wanted to have the PR open before the summit and put the link on the slides.

And yes, it's basically dump of that repo (radanalyticsio/spark-operator) with couple of modifications. I for instance aligned the versions of the libraries to be the same as those that are used by Spark.

> Is this the following? Please give a clear explanation if this is your own contribution.
https://github.com/GoogleCloudPlatform/spark-on-k8s-operator

No, it's different operator written in Java and it supports three different custom resources, `SparkCluster` (spark running in standalone mode in the pods), `SparkApplication` (this has the same API as the operator from GCP, so it's using spark-on-k8s scheduling) and `SparkHistoryServer`. So there is some overlap, but it's a different thing. This operator is also available on [operatorhub.io](operatorhub.io) ([link](https://operatorhub.io/operator/radanalytics-spark))

**Comment by skonto** [comment]
@dongjoon-hyun  @holdenk There are many operator projects out there but does not make sense to be part of the core project. Same for the Flink project. Btw in other PRs people complained about the code base being to large so this is another argument to avoid adding a lot of "external" stuff. Moreover the resource manager stuff logically belong outside of this project but for historical reasons they were kept here since the effort for the common  resource manager API never happened.

**Comment by liyinan926** [comment]
Agreed with what @skonto said. This doesn't feel like something that is necessarily part of core Spark.

**Pull request closed without merging**
