### PR TITLE
SPARK-8623. Hadoop RDDs fail to properly serialize configuration

### PR DESCRIPTION
**Pull request by sryza**

### CODE REVIEW

**Comment by vanzin** [comment]
LGTM if this fixes the NPEs. Yay!

**Comment by sryza** [comment]
jenkins, retest this please

**Comment by JoshRosen** [comment]
LGTM as well.

**Comment by JoshRosen** [comment]
Saw confirmation on JIRA that this patch fixes the issue, so I'm going to merge to master.

**Pull request closed without merging**
