### PR TITLE
[SPARK-34011][SQL] Refresh cache in `ALTER TABLE .. RENAME TO PARTITION`

### PR DESCRIPTION
**Pull request by MaxGekk**
### What changes were proposed in this pull request?
1. Invoke `refreshTable()` from `AlterTableRenamePartitionCommand.run()` after partitions renaming. In particular, this re-creates the cache associated with the modified table.
2. Refresh the cache associated with tables from v2 table catalogs in the `ALTER TABLE .. RENAME TO PARTITION` command.

### Why are the changes needed?
This fixes the issues portrayed by the example:
```sql
spark-sql> CREATE TABLE tbl1 (col0 int, part0 int) USING parquet PARTITIONED BY (part0);
spark-sql> INSERT INTO tbl1 PARTITION (part0=0) SELECT 0;
spark-sql> INSERT INTO tbl1 PARTITION (part0=1) SELECT 1;
spark-sql> CACHE TABLE tbl1;
spark-sql> SELECT * FROM tbl1;
0	0
1	1
spark-sql> ALTER TABLE tbl1 PARTITION (part0=0) RENAME TO PARTITION (part=2);
spark-sql> SELECT * FROM tbl1;
0	0
1	1
```
The last query must not return `0	2` since `0  0` was renamed by previous command.

### Does this PR introduce _any_ user-facing change?
Yes. After the changes for the example above:
```sql
...
spark-sql> ALTER TABLE tbl1 PARTITION (part=0) RENAME TO PARTITION (part=2);
spark-sql> SELECT * FROM tbl1;
0	2
1	1
```

### How was this patch tested?
By running the affected test suite:
```
$ build/sbt -Phive-2.3 -Phive-thriftserver "test:testOnly *AlterTableRenamePartitionSuite"
```

### CODE REVIEW

**Comment by MaxGekk** [comment]
@dongjoon-hyun @sunchao @imback82 Could you review this PR, please.

**Review by sunchao — APPROVED** [review]
LGTM (non-binding). Thanks @MaxGekk !

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master, branch-3.1 and branch-3.0.

**Comment by HyukjinKwon** [comment]
@MaxGekk, it has a conflict. Do you mind opening a backport PR?

**Comment by MaxGekk** [comment]
@HyukjinKwon Here is the backport to `branch-3.1` and `branch-3.0`: https://github.com/apache/spark/pull/31060 . I ran new tests in 3.0 locally.

**Pull request closed without merging**
