### PR TITLE
[SPARK-8574] org/apache/spark/unsafe doesn't honor the java source/ta…

### PR DESCRIPTION
**Pull request by tgravescs**
…rget versions.

I basically copied the compatibility rules from the top level pom.xml into here.  Someone more familiar with all the options in the top level pom may want to make sure nothing else should be copied on down.

With this is allows me to build with jdk8 and run with lower versions.  Source shows compiled for jdk6 as its supposed to.

### CODE REVIEW

**Comment by JoshRosen** [comment]
AFAIK Maven was supposed to inherit those settings from the parent POM.  Is there an option that we have to set to do that instead?

**Comment by JoshRosen** [comment]
Actually, the duplication is probably fine, but I'm just curious to understand why the other approach didn't work.

**Comment by tgravescs** [comment]
I'm not a maven expert but I think it only inherits elements not declared in the child. 
So since the unsafe/pom.xml declares javacArgs, I don't think it inherits the parents properties for those. 

I'm happy to change if someone has a better solution.

**Comment by tgravescs** [comment]
Looking a bit more at the mvn docs I might be able to use combine.children="append".
I'll give that a try.

**Comment by JoshRosen** [comment]
@tgravescs If the append option worked, feel free to merge this into master and branch-1.4.

**Comment by srowen** [comment]
LGTM. Yes you're right about how Maven handles this

**Comment by tgravescs** [comment]
thanks for the reviews. I merged to master and branch-1.4.

**Comment by sujkh85** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

sujkh@naver.com 님께 보내신 메일 <Re: [spark] [SPARK-8574] org/apache/spark/unsafe doesn't honor the java source/ta… (#6989)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Pull request closed without merging**
