### PR TITLE
[SPARK-36393][BUILD][3.1] Try to raise memory for GHA

### PR DESCRIPTION
**Pull request by viirya**
### What changes were proposed in this pull request?

According to the feedback from GitHub, the change causing memory issue has been rolled back. We can try to raise memory again for GA.

### Why are the changes needed?

Trying higher memory settings for GA. It could speed up the testing time.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

GA

### CODE REVIEW

**Comment by viirya** [comment]
cc @dongjoon-hyun @HyukjinKwon

**Comment by viirya** [comment]
cc @gengliangwang

**Comment by dongjoon-hyun** [comment]
GitHub Action seems to fail for some reasons.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by viirya** [comment]
```
 ======================================================================
ERROR [1.864s]: test_reuse_worker_of_parallelize_range (pyspark.tests.test_worker.WorkerReuseTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/spark/spark/python/pyspark/tests/test_worker.py", line 178, in test_reuse_worker_of_parallelize_range
    self.assertTrue(pid in previous_pids)
AssertionError: False is not true
```

Looks flaky test failure and unrelated.

**Comment by viirya** [comment]
Thanks @HyukjinKwon ! Merging to 3.1.

**Pull request closed without merging**
