### PR TITLE
[SPARK-13379] [MLlib] Fix MLlib LogisticRegressionWithLBFGS set regularization incorrectly

### PR DESCRIPTION
**Pull request by yanboliang**
## What changes were proposed in this pull request?

Fix MLlib LogisticRegressionWithLBFGS regularization map as:
`SquaredL2Updater` -> `elasticNetParam = 0.0`
`L1Updater` -> `elasticNetParam = 1.0`
cc @dbtsai 
## How was the this patch tested?

unit tests

### CODE REVIEW

**Comment by rxin** [comment]
Question: do you see the pull request template?

**Comment by yanboliang** [comment]
@rxin I saw the template, but I think this change is very easy to understand, so ...

**Comment by rxin** [comment]
Thanks - I was checking to see if the template shows up or not, because a number of pull requests don't follow it. I think it's a good idea to follow this as much as possible, since it'd encourage the newer contributors to actually think about testing.

**Comment by rxin** [comment]
Regarding testing: how does this work with unit tests? If the old code passes all the tests ...

**Comment by yanboliang** [comment]
This is due to we don't have excellent test coverage.

**Comment by rxin** [comment]
So this wasn't really tested by unit tests ...

**Comment by yanboliang** [comment]
Yep, I cleaned up the description.

**Comment by dbtsai** [comment]
+1 on copying the tests from ML LOR tests.

**Comment by yanboliang** [comment]
OK, I will copy tests from ML.

**Comment by yanboliang** [comment]
@dbtsai I have copied tests from ML.

**Comment by dbtsai** [comment]
The default value in R's GLMNET is `1E-7`, and the default value in original LBFGS implementation is `1E-8`. In order to provide better and consistent result, let's change it to `1E-6` in a separate PR.

**Comment by dbtsai** [comment]
LGTM. Merged into master. Thanks.

**Comment by yanboliang** [comment]
@dbtsai Thanks! I will send another PR for consistent convergence tolerance.

**Pull request closed without merging**
