### PR TITLE
[SPARK-14721][SQL] Remove HiveContext (part 2)

### PR DESCRIPTION
**Pull request by andrewor14**
## What changes were proposed in this pull request?

This removes the class `HiveContext` itself along with all code usages associated with it. The bulk of the work was already done in #12485. This is mainly just code cleanup and actually removing the class.

Note: A couple of things will break after this patch. These will be fixed separately.
- the python HiveContext
- all the documentation / comments referencing HiveContext
- there will be no more HiveContext in the REPL (fixed by #12589)
## How was this patch tested?

No change in functionality.

### CODE REVIEW

**Comment by andrewor14** [comment]
Hm, seems that I'll need to fix the python thing in this patch.

**Comment by andrewor14** [comment]
retest this please

**Comment by rxin** [comment]
The changes look good to me.

**Comment by yhuai** [comment]
LGTM

**Comment by andrewor14** [comment]
Thanks merging into master.

**Pull request closed without merging**
