### PR TITLE
[SPARK-9461] [mllib] [python] [streaming] disabled two flaky mllib streaming pyspark lin/log reg tests

### PR DESCRIPTION
**Pull request by jkbradley**
CC: @mengxr  @rxin

### CODE REVIEW

**Comment by jkbradley** [comment]
If these suddenly became flaky, then a bunch more are probably going to fail as well, until we can find the root cause (which I suspect is not in streaming ML, but deeper).  But we can commit this in case it helps...

**Comment by jkbradley** [comment]
Maybe it's from streaming? [https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/38935/consoleFull]

**Comment by jkbradley** [comment]
Maybe I won't commit this for now since these tests don't seem *that* flaky...but @mengxr feel free to commit it if you like (though in that case we should probably disable a lot more PySpark Streaming ML tests).

**Comment by mengxr** [comment]
I would wait for another failure. It is not clear whether this is caused by some other changes in Streaming or Python. If that is the case, we should revert those changes instead of disabling existing tests.

**Comment by tdas** [comment]
This is being fixed with #7797 I am going to merge that and then we wont need to ignore them. Hopefully.

**Comment by jkbradley** [comment]
Awesome, thanks!

**Comment by tdas** [comment]
I have merged that #7797. I would keep this PR open a little while just in case it still does not solve the flakiness.

**Comment by jkbradley** [comment]
I'm closing this

**Pull request closed without merging**
