### PR TITLE
[SPARK-34548][SQL][FOLLOW-UP] Call toSeq to recover Scala 2.13 build in RemoveNoopUnion

### PR DESCRIPTION
**Pull request by viirya**
### What changes were proposed in this pull request?

Call `toSeq` to fix Scala 2.13 build error.

### Why are the changes needed?

It is needed to fix 2.13 build error.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by viirya** [comment]
cc @dongjoon-hyun @HyukjinKwon

**Review by maropu — APPROVED** [review]

**Review by HyukjinKwon — APPROVED** [review]

**Comment by maropu** [comment]
The last GA test run in the previous PR failed? I didn't see that though.

**Comment by HyukjinKwon** [comment]
Yeah, it did ... https://github.com/apache/spark/runs/2002190893 https://github.com/apache/spark/runs/2018276934

**Comment by HyukjinKwon** [comment]
Scala 2.13 build passed .. let me merge this to make other builds pass.

**Comment by dongjoon-hyun** [comment]
+1, LGTM. Thanks!

**Comment by viirya** [comment]
Yea, didn't notice it. Sorry for that. Will re-check it next time.

**Pull request closed without merging**
