### PR TITLE
[MINOR] Clean up an unnecessary variable

### PR DESCRIPTION
**Pull request by weixiuli**
### What changes were proposed in this pull request?
Clean up an unnecessary variable.
### Why are the changes needed?

There is an unnecessary variable, we should clean up it.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Passed GA.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Can we find similar instances, and fix them in one go?

**Comment by weixiuli** [comment]
> Can we find similar instances, and fix them in one go?

It is the only place I found.

**Comment by HyukjinKwon** [comment]
IIRC, IntelliJ has an inspection for unused variables, etc. It would be great to find the same instances and fix them in batch.

**Comment by srowen** [comment]
Yeah at least within all of sql/ or something

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
