### PR TITLE
[SPARK-15457][MLLIB][ML] Eliminate some warnings from MLlib about deprecations

### PR DESCRIPTION
**Pull request by jkbradley**
## What changes were proposed in this pull request?

Several classes and methods have been deprecated and are creating lots of build warnings in branch-2.0. This issue is to identify and fix those items:
- WithSGD classes: Change to make class not deprecated, object deprecated, and public class constructor deprecated. Any public use will require a deprecated API. We need to keep a non-deprecated private API since we cannot eliminate certain uses: Python API, streaming algs, and examples.
  - Use in PythonMLlibAPI: Change to using private constructors
  - Streaming algs: No warnings after we un-deprecate the classes
  - Examples: Deprecate or change ones which use deprecated APIs
- MulticlassMetrics fields (precision, etc.)
- LinearRegressionSummary.model field
## How was this patch tested?

Existing tests.  Checked for warnings manually.

### CODE REVIEW

**Comment by srowen** [comment]
LGTM. I will do one more pass to clear up build warnings before the final release so I might be able to clean up stragglers, if any, later

**Comment by holdenk** [comment]
@srowen willing to help with that too btw :)

**Comment by jkbradley** [comment]
Thanks!  I'll merge this with master and branch-2.0 then.

**Comment by jkbradley** [comment]
I'll also leave the JIRA open to remind us to check for remaining items.

**Pull request closed without merging**
