### PR TITLE
[SPARK-30378][ML][PYSPARK][FOLLOWUP] Remove Param fields provided by _FactorizationMachinesParams

### PR DESCRIPTION
**Pull request by zero323**
### What changes were proposed in this pull request?

Removal of following `Param` fields:

- `factorSize`
- `fitLinear`
- `miniBatchFraction`
- `initStd`
- `solver`

from `FMClassifier` and `FMRegressor`

### Why are the changes needed?

This `Param` members are already provided by `_FactorizationMachinesParams`

https://github.com/apache/spark/blob/0f3d744c3f19750ab03eeae3606e122dcffae5df/python/pyspark/ml/regression.py#L2303-L2318

which is mixed into `FMRegressor`:

https://github.com/apache/spark/blob/0f3d744c3f19750ab03eeae3606e122dcffae5df/python/pyspark/ml/regression.py#L2350

and `FMClassifier`:

https://github.com/apache/spark/blob/0f3d744c3f19750ab03eeae3606e122dcffae5df/python/pyspark/ml/classification.py#L2793

### Does this PR introduce any user-facing change?

No

### How was this patch tested?

Manual testing.

### CODE REVIEW

**Comment by srowen** [comment]
@mob-ai what do you think? You added this in https://github.com/apache/spark/pull/26124/files

**Comment by huaxingao** [comment]
LGTM. Thanks for catching the problem. @zero323

**Comment by hahadsg** [comment]
> @mob-ai what do you think? You added this in https://github.com/apache/spark/pull/26124/files

LGTM. This is more concise.

**Comment by mob-ai** [comment]
> @mob-ai what do you think? You added this in https://github.com/apache/spark/pull/26124/files

LGTM. This is more concise.

**Review by zhengruifeng — APPROVED** [review]

**Comment by srowen** [comment]
Merged to master

**Comment by zero323** [comment]
Thanks.

**Pull request closed without merging**
