### PR TITLE
[SPARK-30972][SQL] PruneHiveTablePartitions should be executed as earlyScanPushDownRules

### PR DESCRIPTION
**Pull request by Ngone51**
### What changes were proposed in this pull request?

Make rule `PruneHiveTablePartitions` to execute as `earlyScanPushDownRules`.

### Why are the changes needed?

Similar to rule `PruneFileSourcePartitions`, `PruneHiveTablePartitions` should also be executed as earlyScanPushDownRules to eliminate the impact on statistic computation later.

### Does this PR introduce any user-facing change?

No.

### How was this patch tested?

Pass Jenkins.

### CODE REVIEW

**Comment by Ngone51** [comment]
cc @cloud-fan @fuwhu Please take a look.

**Review by cloud-fan — APPROVED** [review]
makes sense to me

**Review by gengliangwang — APPROVED** [review]

**Comment by gengliangwang** [comment]
Thanks, merging to master.

**Comment by cloud-fan** [comment]
thanks, merging to master/3.0!

**Comment by Ngone51** [comment]
thanks all!

**Pull request closed without merging**
