### PR TITLE
[SPARK-15539][SQL] DROP TABLE throw exception if table doesn't exist

### PR DESCRIPTION
**Pull request by andrewor14**
## What changes were proposed in this pull request?

Same as #13302, but for DROP TABLE.
## How was this patch tested?

`DDLSuite`

### CODE REVIEW

**Comment by andrewor14** [comment]
@hvanhovell

**Comment by andrewor14** [comment]
@yhuai

**Comment by yhuai** [comment]
Seems we should convert those disabled tests to our tests? Or we should put those disabled tests to HiveQuerySuite or HiveWindowFunctionQuerySuite?

**Comment by andrewor14** [comment]
OK, let's do that in a follow-up patch. Thanks, merging into master 2.0.

**Comment by andrewor14** [comment]
https://issues.apache.org/jira/browse/SPARK-15576

**Pull request closed without merging**
