### PR TITLE
SPARK-12898. Consider having dummyCallSite for HiveTableScan

### PR DESCRIPTION
**Pull request by rajeshbalamohan**
Currently, HiveTableScan runs with getCallSite which is really expensive and shows up when scanning through large table with partitions (e.g TPC-DS) which slows down the overall runtime of the job. It would be good to consider having dummyCallSite in HiveTableScan.

### CODE REVIEW

**Comment by rxin** [comment]
Can you explain more about "HiveTableScan runs with getCallSite which is really expensive and shows up when scanning through large table with partitions"? What's expensive?

**Comment by rajeshbalamohan** [comment]
getCallSite gets the thread stack trace (+ additional processing). This is executed numerous number of times when running a query on TPC-DS  (with 1800+ partition files) dataset. I have attached the profiler info in SPARK-12898 (https://issues.apache.org/jira/secure/attachment/12783232/callsiteProf.png).  Having dummycallsite eliminates these stracktrace calls and reduces the overall job runtime.

**Comment by JoshRosen** [comment]
I think that we may have seen similar `getCallSite` issues in the past, if my memory's right (try searching JIRA).

**Comment by rxin** [comment]
Thanks for the explanation. It would be great to add comment in the code that you are changing to explain why the duummy callsite is useful.

**Comment by rajeshbalamohan** [comment]
Thanks for review. I have added a comment in the code for the same.

**Comment by rxin** [comment]
LGTM pending tests.

**Comment by rxin** [comment]
Merging this in master. Thanks.

**Comment by rxin** [comment]
BTW @rajeshbalamohan in the future can you follow the format for your pull request title?

[SPARK-xxxx][SQL] ....

Thanks.

**Pull request closed without merging**
