### PR TITLE
[SPARK-11608][MLLIB][DOC] Added migration guide for MLlib 1.6

### PR DESCRIPTION
**Pull request by jkbradley**
No known breaking changes, but some deprecations and changes of behavior.

CC: @mengxr

### CODE REVIEW

**Comment by jkbradley** [comment]
Note: I have generated the docs and tested the links.

**Comment by jkbradley** [comment]
CC @thunterdb Could you please check this?  The content should be OK since @mengxr verified it previously.

**Comment by thunterdb** [comment]
This looks good to me.

**Comment by jkbradley** [comment]
OK thanks!
Merging with master and branch-1.6

**Pull request closed without merging**
