### PR TITLE
Allow sequences (tuples and lists) as pivot values argument in PySpark.

### PR DESCRIPTION
**Pull request by wrobell**
Both tuples and lists are accepted by PySpark on runtime.

### CODE REVIEW

**Comment by holdenk** [comment]
Jenkins ok to test

**Comment by holdenk** [comment]
This looks reasonable to me, I'm not very familiar with the typing code for Python yet so cc @zero323

**Comment by zero323** [comment]
Technically speaking, `Sequence` is more than `Tuple` or `List`, but Py4J [should be able map](https://www.py4j.org/advanced_topics.html) any `Sequence` in the same way (I've done some rough testing on custom `Sequence` implementation to be sure, and it seems to work fine).

**Review by zero323 — APPROVED** [review]
LGTM, subject to passing tests.

**Comment by HyukjinKwon** [comment]
@wrobell, can you file a JIRA (see https://spark.apache.org/contributing.html), and enable GitHub Actions in your fork repo (see https://github.com/apache/spark/pull/33083/checks?check_run_id=2913538608)?

Also please keep the GIthub PR template (https://github.com/apache/spark/blob/master/.github/PULL_REQUEST_TEMPLATE) and format PR title properly.

**Comment by HyukjinKwon** [comment]
Otherwise, looks fine to me too. I'll leave it to him.

**Comment by zero323** [comment]
> Otherwise, looks fine to me too. I'll leave it to him.

Sure, I'll handle this once pending comments are addressed.

**Comment by zero323** [comment]
Gentle ping @wrobell

**Comment by wrobell** [comment]
Sorry, but due to personal circumstances I will not be able to help with this for next couple of weeks.

**Pull request closed without merging**
