### PR TITLE
[SPARK-38622][BUILD] Upgrade jersey to 2.35

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr aims to upgrade jersey to 2.35

### Why are the changes needed?
This jersey version starts to [support JDK 16](https://github.com/eclipse-ee4j/jersey/pull/4785) and the change reports as follows:

- https://github.com/eclipse-ee4j/jersey/releases/tag/2.35

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass GA

### CODE REVIEW

**Review by martin-g — APPROVED** [review]

**Review by srowen — APPROVED** [review]
This seems fine. Usually I'd ask if there are any changes that are particularly important for Spark, or any possible breaking changes. Here it seems like just small bug fixes.

**Comment by LuciferYang** [comment]
This is the first version of Jersey that supports JDK 16. Unfortunately, not JDK 17. Others seem to be just small bug fix

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by LuciferYang** [comment]
thanks all

**Pull request closed without merging**
