### PR TITLE
[SPARK-24869][SQL] Fix SaveIntoDataSourceCommand's input Dataset does not use Cached Data

### PR DESCRIPTION
**Pull request by wangyum**
## What changes were proposed in this pull request?

This PR fix 2 things:
1. Fix `SaveIntoDataSourceCommand`'s input Dataset does not use Cached Data.
2. Fix `SaveIntoDataSourceCommand`s web ui when writing data.

## How was this patch tested?
unit tests and  manual tests

Manual test web UI:
```scala
val udf1 = udf({ (x: Int, y: Int) => x + y })
val df = spark.range(0, 3).toDF("a").withColumn("b", udf1(col("a"), lit(10)))
df.write.mode(SaveMode.Overwrite).jdbc(jdbcUrl, jdbcTable, new Properties)
```
**Before this PR**:
image

**After this PR:**

image

### CODE REVIEW

**Comment by wangyum** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
retest this please
--

**Comment by HyukjinKwon** [comment]
retest this please

**Pull request closed without merging**
