### PR TITLE
[SPARK-13648] Add Hive Cli to classes for isolated classloader

### PR DESCRIPTION
**Pull request by preecet**
## What changes were proposed in this pull request?

Adding the hive-cli classes to the classloader
## How was this patch tested?

The hive Versionssuite tests were run

This is my original work and I license the work to the project under the project's open source license.

### CODE REVIEW

**Comment by preecet** [comment]
Copy of recent developemrnt mailing list comment.

I have been testing 1.6.1RC1 using the IBM Java SDK.

I notice a problem ( with the org.apache.spark.sql.hive.client.VersionsSuite tests ) after a recent Spark 1.6.1 change.
Pull request - https://github.com/apache/spark/commit/f7898f9e2df131fa78200f6034508e74a78c2a44

The change introduced a dependency on org.apache.hadoop.hive.cli.CliSessionState in org.apache.spark.sql.hive.client.ClientWrapper.

In particular the following test was added
if (originalState.isInstanceOf[CliSessionState]) {

The problem is that VersionsSuite test uses an isolated classloader in order to test various versions of Hive. However the classpath of the isolated classloader does not contain CliSessionState.

The behaviour of isInstanceOf[CliSessionState]) is JVM vendor specific. In particular whether this code causes the CliSessionState class to be loaded. ( It does not for openjdk, but does for IBM JDK ). Hence this call can throw a classnotfound exception.

**Comment by rxin** [comment]
cc @marmbrus

**Comment by marmbrus** [comment]
ok to test

**Comment by marmbrus** [comment]
LGTM pending tests

**Comment by marmbrus** [comment]
Thanks, merging to master and 1.6.

**Comment by adrian-wang** [comment]
Why we need `hive-cli` here? This is not version specific.

**Comment by preecet** [comment]
Because ClientWrapper calls isInstanceOf[CliSessionState] and so needs to load the class CliSessionstate. In the testcase ClientWraper has been loaded by the isolated class loader.

**Pull request closed without merging**
