### PR TITLE
[SPARK-44367][SQL][UI] Show error message on UI for each failed query

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

This PR adds an 'error message' col to the failed query execution table on the SQL/DataFrame tab of UI. 

### Why are the changes needed?

The SQL tab of UI is not helping to detect SQL errors. This PR will provide users with a clear understanding of why their queries have failed.

### Does this PR introduce _any_ user-facing change?

SQL tab of UI shows errors for failed queries

### How was this patch tested?

built and tested locally

image

### CODE REVIEW

**Comment by yaooqinn** [comment]
cc @cloud-fan @dongjoon-hyun @HyukjinKwon @sarutak thanks

**Comment by cloud-fan** [comment]
what's the old way to know the query error in the UI?

**Comment by yaooqinn** [comment]
@cloud-fan 

- check the related failed job IDs for physical failures but not logical ones
- (STS-specific) ThriftServer Page
- Attach custom a UITab

**Comment by cloud-fan** [comment]
If we click one query and enter the detail query page, will we see the error message before this PR?

**Comment by yaooqinn** [comment]
> If we click one query and enter the detail query page, will we see the error message before this PR?

NO

**Comment by yaooqinn** [comment]
Hi @cloud-fan, Do you have any other concerns?

**Comment by cloud-fan** [comment]
I'm not good at UI design but it seems a bit overkill to put the full error message in a column. Shall we only put the error class name (or java exception class name) in the column, and put the full error message in the query details page?

**Comment by yaooqinn** [comment]
We can follow the task error on StagePage and the execution error on ThriftPage, display the first line which can be used to represent the error class, and toggle to show the collapsed details. WDYT?

**Comment by yaooqinn** [comment]
How about this?

image


image

**Review by cloud-fan — APPROVED** [review]

**Comment by yaooqinn** [comment]
Thanks, merged to master and 3.5.

PS, K8s IT failures are irrelevant.

**Pull request closed without merging**
