### PR TITLE
[SPARK-27129][Minor]Add JSON event serialization methods in JSONUtils for blacklist events

### PR DESCRIPTION
**Pull request by shahidki31**
## What changes were proposed in this pull request?

Added  methods in JSONUtils class for JSON event serialization and deserialization methods for SparkListener black list events, like 'SparkListenerExecutorBlacklisted', 'SparkListenerNodeBlacklistedForStage'  etc.

## How was this patch tested?

Existing tests, also updated UT.

### CODE REVIEW

**Comment by shahidki31** [comment]
cc @vanzin please review.

**Comment by vanzin** [comment]
Why would you want this at all?

They're already serialized just fine, aren't they?

I'm just going to close this directly.

**Comment by VaibhavDesai** [comment]
**[Test build Jenkins build has finished](https://ci-dev.ngcc.nvidia.com/job/vaibhavd_spark/106/testReport)** for PR 24059 at commit [`2fc837d`](https://github.com/apache/spark/commit/2fc837d74837b216ffb723baaed8f89e9f841f95).
 * This patch **fails RAT tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

**Comment by VaibhavDesai** [comment]
**[Test build Jenkins build has finished](https://ci-dev.ngcc.nvidia.com/job/vaibhavd_spark/106/testReport)** for PR 24059 at commit [`2fc837d`](https://github.com/apache/spark/commit/2fc837d74837b216ffb723baaed8f89e9f841f95).
 * This patch **fails RAT tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

**Comment by VaibhavDesai** [comment]
**[Test build Jenkins build has finished](https://ci-dev.ngcc.nvidia.com/job/vaibhavd_spark/106/testReport)** for PR 24059 at commit [`2fc837d`](https://github.com/apache/spark/commit/2fc837d74837b216ffb723baaed8f89e9f841f95).
 * This patch **fails RAT tests**.
 * This patch merges cleanly.
 * This patch adds no public classes.

**Comment by VaibhavDesai** [comment]
**[Test build Jenkins build has started](https://ci-dev.ngcc.nvidia.com/job/vaibhavd_spark/106/testReport)** for PR 24059 at commit [`2fc837d`](https://github.com/apache/spark/commit/2fc837d74837b216ffb723baaed8f89e9f841f95).

**Comment by vanzin** [comment]
@VaibhavDesai what are you doing? Would you mind not spamming the PR?

**Comment by VaibhavDesai** [comment]
Sorry, I am deleting it. I was testing out a feature that I was trying to implement.

**Comment by VaibhavDesai** [comment]
**[Test build Jenkins build has started](https://ci-dev.ngcc.nvidia.com/job/vaibhavd_spark/106/testReport)** for PR 24059 at commit [`2fc837d`](https://github.com/apache/spark/commit/2fc837d74837b216ffb723baaed8f89e9f841f95).

**Pull request closed without merging**
