### PR TITLE
[SPARK-48646][PYTHON] Refine Python data source API docstring and type hints

### PR DESCRIPTION
**Pull request by allisonwang-db**
### What changes were proposed in this pull request?

This PR improves the docstring and type hints for classes and methods in `datasource.py`.

### Why are the changes needed?

To improve type hint and docstring.

### Does this PR introduce _any_ user-facing change?

No 

### How was this patch tested?

Existing docs test.

### Was this patch authored or co-authored using generative AI tooling?

No

### CODE REVIEW

**Comment by allisonwang-db** [comment]
cc @HyukjinKwon

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Let's fix MyPy failures though:

```
annotations failed mypy checks:
python/pyspark/sql/worker/python_streaming_sink_runner.py:118: error: Unused "type: ignore" comment  [unused-ignore]
python/pyspark/sql/worker/python_streaming_sink_runner.py:120: error: Unused "type: ignore" comment  [unused-ignore]
python/pyspark/sql/worker/commit_data_source_write.py:93: error: Unused "type: ignore" comment  [unused-ignore]
python/pyspark/sql/worker/commit_data_source_write.py:95: error: Unused "type: ignore" comment  [unused-ignore]
```

**Comment by xinrong-meng** [comment]
LGTM after tests passed, thank you!

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
