### PR TITLE
[SPARK-4908][SQL]narrow the scope of synchronized for PR 3834

### PR DESCRIPTION
**Pull request by baishuo**
compared with  https://github.com/apache/spark/pull/3834,  this PR narrow the scope of synchronized

### CODE REVIEW

**Comment by liancheng** [comment]
ok to test

**Comment by liancheng** [comment]
This LGTM, thanks!

**Comment by liancheng** [comment]
But why this PR is marked as "hotfix"? Does it break anything?

**Comment by marmbrus** [comment]
Yeah, generally hot fixes are reserved for things like "the build is broken and we need to fix it now"

**Comment by baishuo** [comment]
Hi @liancheng and @marmbrus I had remove [hotfix] from the title.

**Comment by baishuo** [comment]
Indeed, the code passed all the test when I do test locally,  I had [hotfix] to title just because i want illustrate that this is not the final solution of [SPARK-4908]

**Comment by baishuo** [comment]
Hi @marmbrus ,can this PR be merged? :)

**Comment by marmbrus** [comment]
Do we know that `HiveShim.getCommandProcessor(` and stuff are threadsafe?  Since we only use this for DDL operations and not actually querying this seems more risky than worthwhile to me.  Thoughts?

**Comment by liancheng** [comment]
`HiveShim.getCommandProcess` delegates to methods defined in `CommandProcessorFactory`, which tries to find a cached `Driver` object and initialize it. The underlying `Driver` cache map is synchronized. However, I'm not quite sure whether `Driver` is thread-safe. Also, `HiveServer2` actually creates a new `Driver` instance for every SQL statement and never caches them. Considering all the above, I'd agree that the risks is greater than the benefits. A better solution for this is to avoid using `HiveShim.getCommandProcess` (which caches `Driver` objects) but mimicing what `HiveServer2` does and create new `Driver` instances for every SQL statement.

**Comment by liancheng** [comment]
@baishuo Would you mind closing this PR? The `Driver.plan` field is not properly synchronized; otherwise we wouldn't need the synchronization at all. And other parts of `Driver` are not obviously thread-safe. Considering DDL operations is infrequent, synchronize the whole function is both safe and performance insensitive.

**Comment by baishuo** [comment]
no problem,clolse it :)

**Pull request closed without merging**
