### PR TITLE
[SPARK-47098][INFRA] Migrate from AppVeyor to GitHub Actions for SparkR tests on Windows

### PR DESCRIPTION
**Pull request by HyukjinKwon**
### What changes were proposed in this pull request?

This PR proposes to migrate from AppVeyor to GitHub Actions for SparkR tests on Windows.

### Why are the changes needed?

Reduce the tools we use for better maintenance.

### Does this PR introduce _any_ user-facing change?

No, dev-only.

### How was this patch tested?

- [x] Tested in my fork

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Definitely, +100 for this approach. 😄

**Comment by HyukjinKwon** [comment]
Tests passed at https://github.com/HyukjinKwon/spark/actions/runs/7972756928/job/21765182579. This PR is ready.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

It's a great achievement for Apache Spark community CI, @HyukjinKwon .

Merged to master. Let's see the result.

**Comment by dongjoon-hyun** [comment]
The INFRA issue is resolved now.

**Comment by HyukjinKwon** [comment]
AWESOME!

**Pull request closed without merging**
