### PR TITLE
[SPARK-7724] [SQL] Support Intersect/Except in Catalyst DSL.

### PR DESCRIPTION
**Pull request by smola**

### CODE REVIEW

**Comment by marmbrus** [comment]
ok to test

**Comment by marmbrus** [comment]
test this please

**Comment by rxin** [comment]
This pull request reminds me that we should remove a lot of stuff from the dsl, since they are no longer for public use  (mostly just internal testing).

**Comment by marmbrus** [comment]
Merged to master and 1.4

**Pull request closed without merging**
