### PR TITLE
[DONT'MERGE] Unify the version of `scala-maven-plugin` used by `hadoop-2` and `hadoop-3` profile

### PR DESCRIPTION
**Pull request by LuciferYang**

### CODE REVIEW

**Comment by LuciferYang** [comment]
Since SPARK-40651 dropped Hadoop2 binary distribution from release process, I think `scala-maven-plugin` used by hadoop-2 profile will no longer block execution of docker release script. So I hope to unify the version of `scala-maven-plugin`, I'm doing some tests, such as full compilation, `make-distribution.sh`, full testing and module testing.

I want to do this work because the change of [Scala 2.13(since 2.13.9)](https://github.com/scala/scala/pull/9982)and the `-release` options supported after `scala-maven-plugin` 4.7.2, but I'm not sure whether it's the right time, so I haven't filed Jira yet. I want to hear your suggestions @dongjoon-hyun .

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
No, the Hadoop2 downstream users can use the release scripts still.
>  I think scala-maven-plugin used by hadoop-2 profile will no longer block execution of docker release script

**Comment by LuciferYang** [comment]
Thanks @dongjoon-hyun let me close this one

**Comment by dongjoon-hyun** [comment]
Thank you for closing, @LuciferYang .

**Pull request closed without merging**
