### PR TITLE
Modified NAMESPACE to allow user to access lapply and map actions on …

### PR DESCRIPTION
**Pull request by mhnatiuk**
## What changes were proposed in this pull request?

I made lapply, lapplyParition, map and reduce available as methods that operate on Spark DataFrame. This is needed for common operations, such as calculating statistic over columns of DataFrame
## How was this patch tested?

No specific unit test needed. run-test.sh positive

### CODE REVIEW

**Comment by mhnatiuk** [comment]
I made also manual test. It seems that I didn't fully understand how SparkR lapply works. My research shows that it operates on the list of rows rather than columns as normal lapply works. Can anybody verify this?

**Comment by srowen** [comment]
Have a look at https://cwiki.apache.org/confluence/display/SPARK/Contributing+to+Spark and consider asking a question first rather than making a PR.

**Comment by rxin** [comment]
Actually we want to remove the RDD-like APIs in R. The only reason we haven't done it yet (they are only hidden but not removed right now) is because we haven't implemented UDFs in R yet.

**Comment by mhnatiuk** [comment]
Please close this PR

**Comment by shivaram** [comment]
@mhnatiuk We don't have permission to close this PR, but you should have permission to do so

**Pull request closed without merging**
