### PR TITLE
[SPARK-35363][SQL][FOLLOWUP] Use fresh name for findNextJoinRows instead of hardcoding it

### PR DESCRIPTION
**Pull request by c21**
### What changes were proposed in this pull request?

This is a followup from discussion in https://github.com/apache/spark/pull/32495#discussion_r632283178 . The hardcoded function name `findNextJoinRows` is not a real problem now as we always do code generation for SMJ's children separately. But this change is to make it future proof in case this assumption changed in the future.

### Why are the changes needed?

Fix the potential reliability issue.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Existing unit tests.

### CODE REVIEW

**Comment by c21** [comment]
cc @cloud-fan, thanks.

**Review by cloud-fan — APPROVED** [review]

**Comment by c21** [comment]
The failed test seems not relevant here, restarted test - https://github.com/c21/spark/actions/runs/841165886 .

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Merged to master. Thank you, @c21 and @cloud-fan .

**Comment by c21** [comment]
Thank you @dongjoon-hyun and @cloud-fan for review!

**Pull request closed without merging**
