### PR TITLE
[MINOR][DOC] Fix Java example code in Column's comments

### PR DESCRIPTION
**Pull request by da-liii**
## What changes were proposed in this pull request?
Fix scaladoc in Column

## How was this patch tested?
None

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
ok to test

**Review by HyukjinKwon — APPROVED** [review]

**Review by srowen — APPROVED** [review]

**Comment by kiszk** [comment]
Do we need to update the following similar examples, too?

Column.scala
```
   * {{{
   *   // Example: encoding gender string column into integer.
   *
   *   // Scala:
   *   people.select(when(people("gender") === "male", 0)
   *     .when(people("gender") === "female", 1)
   *     .otherwise(2))
   *
   *   // Java:
   *   people.select(when(col("gender").equalTo("male"), 0)
   *     .when(col("gender").equalTo("female"), 1)
   *     .otherwise(2))
   * }}}
```

functions.scala
```
   * {{{
   *   // Example: encoding gender string column into integer.
   *
   *   // Scala:
   *   people.select(when(people("gender") === "male", 0)
   *     .when(people("gender") === "female", 1)
   *     .otherwise(2))
   *
   *   // Java:
   *   people.select(when(col("gender").equalTo("male"), 0)
   *     .when(col("gender").equalTo("female"), 1)
   *     .otherwise(2))
   * }}}
```

**Comment by HyukjinKwon** [comment]
Yea if there are more instances found, we better fix them together

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by srowen** [comment]
I'm going to merge this, as the additional example quoted above should actually work, assuming one imported the 'col' function. In Java, `people("foo")` would be wrong but `col("foo")` is not (necessarily).

**Pull request closed without merging**
