### PR TITLE
[SPARK-33257][PYTHON][SQL] Support Column inputs in PySpark ordering functions (asc*, desc*)

### PR DESCRIPTION
**Pull request by zero323**
### What changes were proposed in this pull request?

This PR adds support for passing `Column`s as input to PySpark sorting functions.

### Why are the changes needed?

According to SPARK-26979, PySpark functions should support both Column and str arguments, when possible.

### Does this PR introduce _any_ user-facing change?

PySpark users can now provide both `Column` and `str` as an argument for `asc*` and `desc*` functions.

### How was this patch tested?

New unit tests.

### CODE REVIEW

**Comment by zero323** [comment]
I'll adjust this, once SPARK-33250 is merged.

**Comment by HyukjinKwon** [comment]
Thank you @zero323. I merged that PR. This PR looks pretty good.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by zero323** [comment]
Thanks @HyukjinKwon!

**Pull request closed without merging**
