### PR TITLE
[SPARK-35023][BUILD] Migrate from deprecated `in` to `slash` syntax in SBT build file

### PR DESCRIPTION
**Pull request by gemelen**
### What changes were proposed in this pull request?

SBT 1.5.0 deprecates `in` syntax from 0.13.x, so build file adjustment
is recommended.
See https://www.scala-sbt.org/1.x/docs/Migrating-from-sbt-013x.html#Migrating+to+slash+syntax

### Why are the changes needed?

Removes significant amount of deprecation warnings and prepares to syntax removal in next versions of SBT.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Build should pass on GH Actions.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Hi, @gemelen . GitHub Action seems to complain. Could you fix it?

**Comment by gemelen** [comment]
@dongjoon-hyun yes, sure.

**Comment by gemelen** [comment]
I wasn't able to reproduce latest test errors. Could please somebody re-launch the tests here?

**Comment by HyukjinKwon** [comment]
Thanks @gemelen for tracking and fixing SBT. BTW, I think it should be best to file a JIRA and link it to the PR.

**Comment by gemelen** [comment]
@HyukjinKwon @dongjoon-hyun 
ticket for tracking created.
please review.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
