### PR TITLE
[SPARK-45417][PYTHON] Make InheritableThread inherit the active session

### PR DESCRIPTION
**Pull request by clee704**
### What changes were proposed in this pull request?
Make `InheritableThread` and `inheritable_thread_target` inherit the active session.

### Why are the changes needed?
Sometimes the active session can be null in Python threads, even with `InheritableThread` or `inheritable_thread_target`.

Example:

```python
# repro.py
# run as: bin/spark-submit repro.py
from multiprocessing.pool import ThreadPool
from pyspark import inheritable_thread_target
from pyspark.sql import SparkSession

spark = SparkSession.builder.appName("Test").getOrCreate()
spark.sparkContext.setLogLevel("ERROR")

def f(i, spark):
    print(f"{i} spark = {spark}")
    print(f"{i} active session = {SparkSession.getActiveSession()}")
    print(f"{i} local property foo = {spark.sparkContext.getLocalProperty('foo')}")
    spark = SparkSession.builder.appName("Test").getOrCreate()
    print(f"{i} spark = {spark}")
    print(f"{i} active session = {SparkSession.getActiveSession()}")

pool = ThreadPool(4)
spark.sparkContext.setLocalProperty("foo", "bar")
pool.starmap(inheritable_thread_target(f), [(i, spark) for i in range(4)])
```

### Does this PR introduce _any_ user-facing change?
Yes. When using `InheritableThread` or `inheritable_thread_target`, the active session will be copied from the parent thread.

### How was this patch tested?
`python/run-tests --testnames pyspark.tests.test_pin_thread`

### Was this patch authored or co-authored using generative AI tooling?
No

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Mind taking a look at the linter failure? https://github.com/clee704/spark/actions/runs/6462049944/job/17543011013

**Comment by HyukjinKwon** [comment]
ping @clee704 I think we should fix this in. Mind taking a look at the linter failure?

**Comment by clee704** [comment]
> ping @clee704 I think we should fix this in. Mind taking a look at the linter failure?

It seems mypy 0.982 has a bug. Maybe we should consider upgrading it?

**Comment by HyukjinKwon** [comment]
cc @WeichenXu123 mind helping reviewing this please.

**Comment by HyukjinKwon** [comment]
> It seems mypy 0.982 has a bug. Maybe we should consider upgrading it?
Let's work around for now, e.g., `# ignore`

**Comment by clee704** [comment]
@WeichenXu123 @HyukjinKwon Can we reopen it? It's still an active issue

**Pull request closed without merging**
