### PR TITLE
SPARK-2372 [MLLIB] Grouped Optimization/Learning

### PR DESCRIPTION
**Pull request by kellrott**
The purpose of this patch is the enable MLLib to better handle scenarios where the user would want to do learning on multiple feature/label sets at the same time. Rather then schedule each learning task separately, this patch lets the user create a single RDD with an Int key to represent the 'group' sets of entries belong to.

This patch establishing the GroupedOptimizer trait, for which GroupedGradientDescent  has been implemented. This systems differs from the original Optimizer trait in that the original optimize method accepted RDD[(Int, Vector)] the new GroupedOptimizer accepts RDD[(Int, (Double, Vector))].
The difference is that the GroupedOptimizer uses a 'group' ID key in the RDD to multiplex multiple optimization operations in the same RDD.

This patch also establishes the GroupedGeneralizedLinearAlgorithm trait, for which the 'run' method has had the RDD[LabeledPoint] input replaced with RDD[(Int,LabeledPoint)].

This patch also provides a unit test and utility to take the results of MLUtils.kFold and turn it into a single grouped RDD, ready for simultaneous learning.

### CODE REVIEW

**Comment by nchammas** [comment]
This PR hasn't been updated in a while.

@kellrott @mengxr What's the status of this PR? Do we need to ping anybody for input?

**Comment by mengxr** [comment]
@nchammas @kellrott Sorry that I haven't got a time to review this PR. The main issue is that this PR is not small. Though there are no break changes, the added code is very similar to the ungrouped and hence we have to maintain both in the future. I'm wondering how this compared to letting Spark launching multiple jobs at the same time but using existing code.

Given the current backlog, I'd suggest maintaining it as a Spark package (http://spark-packages.org/). So users can grab them easily and try.

**Comment by kellrott** [comment]
This was originally written as a response to Spark didn't scale to having
multiple jobs running at the same time (
http://mail-archives.apache.org/mod_mbox/incubator-spark-user/201407.mbox/%3CCAKXMip2he3MoCuU09hf5dXrEQ7kgc3RvNUJtSU54w82baWnj6A@mail.gmail.com%3E
). One of the main reasons it wasn't written as an external package was
that too much of the mllib code was marked as private and couldn't be used.

Kyle

**Comment by srowen** [comment]
That makes sense. Given the current state of the world, do you mind closing this PR?

**Pull request closed without merging**
