### PR TITLE
[SPARK-39944][BUILD] Upgrade dropwizard metrics to 4.2.10

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr upgrade dropwizard metrics from 4.2.7 to 4.2.10 and changes the links [http://metrics.dropwizard.io/4.2.0](http://metrics.dropwizard.io/4.2.0) in `docs/monitoring.md` to [https://metrics.dropwizard.io/4.2.0](https://metrics.dropwizard.io/4.2.0)

### Why are the changes needed?
There are 3 versions after 4.2.7, the release notes as follows:

- https://github.com/dropwizard/metrics/releases/tag/v4.2.8
- https://github.com/dropwizard/metrics/releases/tag/v4.2.9
- https://github.com/dropwizard/metrics/releases/tag/v4.2.10

The new version brings a new API for more type safe of registering gauges(https://github.com/dropwizard/metrics/pull/2642)

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass GitHub Actions

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]

**Review by dongjoon-hyun — COMMENTED** [review]
Thank you, @LuciferYang . Please update the doc together.
```
$ git grep 4.2.0 docs/monitoring.md
docs/monitoring.md:Executor memory metrics are also exposed via the Spark metrics system based on the [Dropwizard metrics library](http://metrics.dropwizard.io/4.2.0).
docs/monitoring.md:[Dropwizard Metrics Library](http://metrics.dropwizard.io/4.2.0).
docs/monitoring.md:see [Dropwizard library documentation for details](https://metrics.dropwizard.io/4.2.0/getting-started.html).
docs/monitoring.md:  [Dropwizard/Codahale Metric Sets for JVM instrumentation](https://metrics.dropwizard.io/4.2.0/manual/jvm.html)
```

**Comment by LuciferYang** [comment]
@dongjoon-hyun There should be no new page to update. [https://metrics.dropwizard.io/4.2.0/](https://metrics.dropwizard.io/4.2.0/) seems to be the latest,  there is no `https://metrics.dropwizard.io/4.2.10/` similar pages exist. If it's my problem, please correct me.



In addition, do we need to change `http` to `https`? For example:

```
docs/monitoring.md:Executor memory metrics are also exposed via the Spark metrics system based on the [Dropwizard metrics library](http://metrics.dropwizard.io/4.2.0).

```

**Comment by dongjoon-hyun** [comment]
Oh, got it. It's too bad for us because we cannot have a matched doc inevitably. For `https`, yes, it will be better to have `https` if it works.

**Review by dongjoon-hyun — APPROVED** [review]

**Comment by LuciferYang** [comment]
> Oh, got it. It's too bad for us because we cannot have a matched doc inevitably. For `https`, yes, it will be better to have `https` if it works.
OK， will update this later

**Comment by LuciferYang** [comment]
> > Oh, got it. It's too bad for us because we cannot have a matched doc inevitably. For `https`, yes, it will be better to have `https` if it works.
> 
> OK， will update this later

done

**Review by srowen — APPROVED** [review]

**Comment by srowen** [comment]
I think the error is unrelated, but can we trigger tests again here?

**Comment by LuciferYang** [comment]
image


Sparkr test failed, and it should not pass all now, master has the same problem

https://github.com/apache/spark/runs/7643052356?check_suite_focus=true

**Comment by dongjoon-hyun** [comment]
Yes, https://github.com/apache/spark/pull/37399 is trying to fix the SparkR failure .
Let me merge this. Thank you, @LuciferYang , @HyukjinKwon , @srowen .

**Comment by LuciferYang** [comment]
thanks @dongjoon-hyun @HyukjinKwon @srowen

**Pull request closed without merging**
