### PR TITLE
[SPARK-14941][SQL] Remove runtime HiveConf

### PR DESCRIPTION
**Pull request by rxin**
## What changes were proposed in this pull request?

This patch replaces most of the use of the runtime execution HiveConf with SQLConf instead.
## How was this patch tested?

Updated existing tests to reflect the change.

### CODE REVIEW

**Comment by gatorsmile** [comment]
To save your time, I hit the same errors. Want to share what I found. One test case called `SQLConf.clear()` and cleaned all the configurations. When we reloading the conf, we did not load the Hive-related configurations.

It might not be the best way to fix the issue. Below is what I changed. Hopefully, it helps you in this PR. Thanks!

https://github.com/apache/spark/pull/12081/commits/1da261a395bd799b6942e04fa142372a5bee3a8c

**Comment by rxin** [comment]
Thanks, @gatorsmile!

**Comment by rxin** [comment]
One thing is that I'm trying to get rid of the HiveConf, so I can't just apply your change directly.

**Comment by gatorsmile** [comment]
I see. : )

**Comment by rxin** [comment]
OK I pushed a fix. Let's see if that works ...

**Comment by rxin** [comment]
Closing this one as https://github.com/apache/spark/pull/12770 subsumes this.

**Pull request closed without merging**
