### PR TITLE
[SPARK-26026][BUILD] Published Scaladoc jars missing from Maven Central

### PR DESCRIPTION
**Pull request by srowen**
## What changes were proposed in this pull request?

This restores scaladoc artifact generation, which got dropped with the Scala 2.12 update. The change looks large, but is almost all due to needing to make the InterfaceStability annotations top-level classes (i.e. `@InterfaceStability.Stable` -> `@Stable`), unfortunately. A few inner class references had to be qualified too.

Lots of scaladoc warnings now reappear. We can choose to disable generation by default and enable for releases, later.

## How was this patch tested?

N/A; build runs scaladoc now.

### CODE REVIEW

**Review by felixcheung — APPROVED** [review]
LG, how do we check for these kind of things in the future?

**Comment by srowen** [comment]
How do we check if doc artifacts were built? well, honestly we (meaning, I) should have noticed this in our releases. Docs were obviously generated for the public site, just not the artifacts that get downloaded into IDEs.

Now, the artifacts are always built with the build, so we'll notice if it breaks. We'll also get a lot of build warnings (again), which we may not like, and decide to put this behind the release profile. And then deal with (rare?) breakage at release time.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by srowen** [comment]
Merged to master

**Comment by cloud-fan** [comment]
Is it a requirement to put annotation class top level?

**Pull request closed without merging**
