### PR TITLE
[SPARK-33412][SQL] OverwriteByExpression should resolve its delete condition based on the table relation not the input query

### PR DESCRIPTION
**Pull request by cloud-fan**
### What changes were proposed in this pull request?

Make a special case in `ResolveReferences`, which resolves `OverwriteByExpression`'s condition expression based on the table relation instead of the input query.

### Why are the changes needed?

The condition expression is passed to the table implementation at the end, so we should resolve it using table schema. Previously it works because we have a hack in `ResolveReferences` to delay the resolution if `outputResolved == false`. However, this hack doesn't work for tables accepting any schema like https://github.com/delta-io/delta/pull/521 . We may wrongly resolve the delete condition using input query's outout columns which don't match the table column names.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

existing tests and updated test in v2 write.

### CODE REVIEW

**Comment by cloud-fan** [comment]
cc @rdblue @dongjoon-hyun  @imback82  @HeartSaVioR

**Review by HyukjinKwon — APPROVED** [review]

**Review by brkyvz — APPROVED** [review]
LGTM. Thank you!

**Review by LantaoJin — APPROVED** [review]
Test passed in delta lake. LGTM

**Comment by HyukjinKwon** [comment]
Merged to master. It has conflict with branch-3.0. @cloud-fan mind opening a PR for branch-3.0?

**Comment by cloud-fan** [comment]
PR for 3.0: https://github.com/apache/spark/pull/30328

**Pull request closed without merging**
