### PR TITLE
[SPARK-45109][SQL][CONNECT][3.4] Fix log function in Connect

### PR DESCRIPTION
**Pull request by peter-toth**
### What changes were proposed in this pull request?
This is a backport PR of https://github.com/apache/spark/pull/42869 as the 1 argument `log` function should point to `ln`. (Please note that the original https://github.com/apache/spark/pull/42863 doesn't need to be backported as `aes_descrypt` and `ln` is not implemented in Connect in Spark 3.4.)

### Why are the changes needed?
Bugfix.

### Does this PR introduce _any_ user-facing change?
No, these Spark Connect functions haven't been released.

### How was this patch tested?
Exsiting UTs.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Actually, SPARK-45109 didn't land at branch-3.4 yet.

Since this is a first commit, shall we say it like `This is a backport ...` instead of `This is a follow-up...`, @peter-toth , in the PR description?
> This is a follow-up PR to https://github.com/apache/spark/pull/42863, the 1 argument log function should also point to ln.

**Review by dongjoon-hyun — APPROVED** [review]
(Pending CIs)

**Comment by zhengruifeng** [comment]
@dongjoon-hyun the functions https://issues.apache.org/jira/browse/SPARK-45109 was introduced in 3.5

**Review by zhengruifeng — APPROVED** [review]

**Comment by peter-toth** [comment]
> Actually, [SPARK-45109](https://issues.apache.org/jira/browse/SPARK-45109) didn't land at branch-3.4 yet.
> 
> Since this is a first commit, shall we say it like `This is a backport ...` instead of `This is a follow-up...`, @peter-toth , in the PR description?

Thanks @dongjoon-hyun, I rephrased the PR description to make it clear why we need this backport.

**Comment by dongjoon-hyun** [comment]
Thank you, @peter-toth and @zhengruifeng .
Merged to branch-3.4.

**Pull request closed without merging**
