### PR TITLE
[SPARK-34570][SQL] Remove dead code from constructors of [Hive]SessionStateBuilder

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

the parameter - `options` is never used. The changes here was part of https://github.com/apache/spark/pull/30642, It got reverted for easier backporting #30642 as a hotfix by https://github.com/apache/spark/pull/30642/commits/dad24543aa7bb7cc81d2a8522112eb797b015633, this PR brings it back to master.

### Why are the changes needed?

remove unless dead code

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

Passing CI is enough.

### CODE REVIEW

**Comment by yaooqinn** [comment]
cc @cloud-fan @maropu thanks for reviewing

**Review by srowen — APPROVED** [review]
Looks OK pending tests.

**Review by maropu — APPROVED** [review]

**Comment by maropu** [comment]
The test failure in GitHub Actions is not related to this, so I'll merge this.

**Comment by maropu** [comment]
Merged to master.

**Comment by yaooqinn** [comment]
thanks @maropu

**Pull request closed without merging**
