### PR TITLE
[SPARK-9815] Rename PlatformDependent.UNSAFE -> Platform.

### PR DESCRIPTION
**Pull request by rxin**
PlatformDependent.UNSAFE is way too verbose.

### CODE REVIEW

**Comment by rxin** [comment]
cc @davies for quick review.

I also plan to add some debugging functionality to help diagnose segfault.

**Comment by davies** [comment]
Isn't it more clear to use UNSAFE than Platform? otherwise LGTM.

**Comment by rxin** [comment]
@davies I didn't think of Unsafe since it was named PlatformDependent from the beginning (which I think came from Netty).

I agree that Unsafe is more clear, but also worry that unsafe is too "scary" ( probably why the new Unsafe-like feature in the JVM is being called Variable Handles http://openjdk.java.net/jeps/193 )

**Comment by davies** [comment]
@rxin That makes sense, merging this into master and 1.5.

**Pull request closed without merging**
