### PR TITLE
[SPARK-32200][WEBUI] Redirect to the history page when accessed to /history on the HistoryServer without appliation id

### PR DESCRIPTION
**Pull request by sarutak**
### What changes were proposed in this pull request?

This PR proposes to change the HistoryServer to redirect to the history page when we access to /history without application id.

### Why are the changes needed?

In the current master, status code 400 will be returned when we access to /history.
So I wonder it's better to redirect to the history page for the better UX.

### Does this PR introduce _any_ user-facing change?

Yes. In the current master, if we access to /history without application id, we will see like the following page.
history-400
After this change applied, we will be redirected to the history page.

### How was this patch tested?

New test added.

### CODE REVIEW

**Comment by sarutak** [comment]
retest this please.

**Comment by sarutak** [comment]
retest this please.

**Comment by sarutak** [comment]
retest this please.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you always, @sarutak .
Merged to master for Apache Spark 3.1.0 (December 2020).

**Pull request closed without merging**
