### PR TITLE
[SPARK-13576] [build] [test-maven] Don't create assembly for examples.

### PR DESCRIPTION
**Pull request by vanzin**
As part of the goal to stop creating assemblies in Spark, this change
modifies the mvn and sbt builds to not create an assembly for examples.

Instead, dependencies are copied to the build directory (under
target/scala-xx/jars), and in the final archive, into the "examples/jars"
directory.

To avoid having to deal too much with Windows batch files, I made examples
run through the launcher library; the spark-submit launcher now has a
special mode to run examples, which adds all the necessary jars to the
spark-submit command line, and replaces the bash and batch scripts that
were used to run examples. The scripts are now just a thin wrapper around
spark-submit; another advantage is that now all spark-submit options are
supported.

There are a few glitches; in the mvn build, a lot of duplicated dependencies
get copied, because they are promoted to "compile" scope due to extra
dependencies in the examples module (such as HBase). In the sbt build,
all dependencies are copied, because there doesn't seem to be an easy
way to filter things.

I plan to clean some of this up when the rest of the tasks are finished.
When the main assembly is replaced with jars, we can remove duplicate jars
from the examples directory during packaging.

Tested by running SparkPi in: maven build, sbt build, dist created by
make-distribution.sh.

Finally: note that running the "assembly" target in sbt doesn't build
the examples anymore. You need to run "package" for that.

### CODE REVIEW

**Comment by JoshRosen** [comment]
I think there's some slight overlap between this and #11178, so it would be great if you could also review that PR.

**Comment by vanzin** [comment]
Hmm, looks like forcing jars to be exported (instead of the generated classes directory) broke some tests...

**Comment by vanzin** [comment]
So would anybody care to take a look at this? @srowen? @JoshRosen?

**Comment by srowen** [comment]
I like the cleanup. I don't feel strongly about the change either way, but I also think there's not much value in offering example assembly JARs. They're really source code examples.

**Comment by vanzin** [comment]
> but I also think there's not much value in offering example assembly JARs

I think it's nice to be able to run a quick Spark app at least to know things are working, although spark-shell can be used for most of those cases.

One future enhancement would be to get these examples out of the main tarball distributions. They're rather large, because of all the dependencies, so that would reduce the package sizes considerably.

**Comment by vanzin** [comment]
retest this please

**Comment by vanzin** [comment]
SQL test failure, I assume unrelated? retest this please

**Comment by vanzin** [comment]
I plan to merge this after tests pass.

**Comment by vanzin** [comment]
retest this please

**Comment by vanzin** [comment]
This is failing a sql job that seems unrelated to this change.

```
Exchange SinglePartition, None
+- WholeStageCodegen
   :  +- TungstenAggregate(key=[], functions=[(count(1),mode=Partial,isDistinct=false)], output=[count#3206L])
   :     +- Scan org.apache.spark.sql.execution.datasources.text.DefaultSource@332a5bae part: struct<>, data: struct<value:string>[] InputPaths: file:/home/jenkins/workspace/SparkPullRequestBuilder%403/sql/core/target/scala-2.11/test-classes/text-suite.txt

	at test.org.apache.spark.sql.JavaDataFrameSuite.testTextLoad(JavaDataFrameSuite.java:321)
Caused by: java.io.IOException: No input paths specified in job
	at test.org.apache.spark.sql.JavaDataFrameSuite.testTextLoad(JavaDataFrameSuite.java:321)
```

retest this please

**Comment by vanzin** [comment]
retest this please

**Comment by vanzin** [comment]
retest this please

**Comment by vanzin** [comment]
Yay! Merging to master.

**Comment by vanzin** [comment]
Merging to master.

**Pull request closed without merging**
