### PR TITLE
[SPARK-31889][BUILD] Docker release script does not allocate enough memory to reliably publish

### PR DESCRIPTION
**Pull request by holdenk**
### What changes were proposed in this pull request?
Allow overriding the zinc options in the docker release and set a higher so the publish step can succeed consistently.

### Why are the changes needed?

The publish step experiences memory pressure.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?
Running test locally with fake user to see if publish step (besides svn part) succeeds

### CODE REVIEW

**Comment by holdenk** [comment]
cc @srowen @cloud-fan

**Comment by srowen** [comment]
Also seems fine.

**Comment by holdenk** [comment]
Two failures are spurious (failures in Java unit tests).
Jenkins retest this please.

**Comment by holdenk** [comment]
Ran locally as "fake@apache.org" seems to work fine.

**Pull request closed without merging**
