### PR TITLE
[SPARK-6453][Mesos] Some Mesos*Suite have a different package with their classes

### PR DESCRIPTION
**Pull request by jongyoul**
- Moved Suites from o.a.s.s.mesos to o.a.s.s.cluster.mesos

### CODE REVIEW

**Comment by srowen** [comment]
Jenkins, retest this please.

**Comment by srowen** [comment]
LGTM. That does look like a small oversight.

**Comment by srowen** [comment]
The test looks like some strange unrelated failure in building the final assembly. All tests actually pass, so I think this PR (which just moves tests, which pass) is OK.

**Comment by jongyoul** [comment]
@srowen Yes, All tests passed in the test log. Do you know what the problem is?

**Pull request closed without merging**
