### PR TITLE
[DO NOT MERGE] Test partition

### PR DESCRIPTION
**Pull request by cloud-fan**

### CODE REVIEW

**Comment by cloud-fan** [comment]
cc @yhuai

**Comment by cloud-fan** [comment]
retest this please

**Comment by yhuai** [comment]
test this please

**Comment by yhuai** [comment]
test this please

**Comment by yhuai** [comment]
test this please

**Comment by rxin** [comment]
What's this about? Close it?

**Comment by cloud-fan** [comment]
I'm trying to test the newly added partition stuff in hive 0.13, but was stucked by other issues of hive 0.13. Will revisit it later.

**Pull request closed without merging**
