### PR TITLE
[SPARK-15209] Fix display of job descriptions with single quotes in web UI timeline

### PR DESCRIPTION
**Pull request by JoshRosen**
## What changes were proposed in this pull request?

This patch fixes an escaping bug in the Web UI's event timeline that caused Javascript errors when displaying timeline entries whose descriptions include single quotes. 

The original bug can be reproduced by running

``` scala
sc.setJobDescription("double quote: \" ")
sc.parallelize(1 to 10).count()

sc.setJobDescription("single quote: ' ")
sc.parallelize(1 to 10).count() 
```

and then browsing to the driver UI. Previously, this resulted in an "Uncaught SyntaxError" because the single quote from the description was not escaped and ended up closing a Javascript string literal too early.

The fix implemented here is to change the relevant Javascript to define its string literals using double-quotes. Our escaping logic already properly escapes double quotes in the description, so this is safe to do.
## How was this patch tested?

Tested manually in `spark-shell` using the following cases:

``` scala
sc.setJobDescription("double quote: \" ")
sc.parallelize(1 to 10).count()

sc.setJobDescription("single quote: ' ")
sc.parallelize(1 to 10).count() 

sc.setJobDescription("ampersand: &")
sc.parallelize(1 to 10).count()

sc.setJobDescription("newline: \n text after newline ")
sc.parallelize(1 to 10).count() 

sc.setJobDescription("carriage return: \r text after return ")
sc.parallelize(1 to 10).count() 
```

/cc @sarutak for review.

### CODE REVIEW

**Comment by sarutak** [comment]
@JoshRosen Thanks for reporting this issue.
For single-quotation and double-quotation,  it LGTM but I noticed \n and \r can cause similar issue.
Further more, we should escape \\uXXXX (hex literals) or \\OOO (octal literals) right?

**Comment by andrewor14** [comment]
LGTM

**Comment by JoshRosen** [comment]
Just pushed a commit to address problems with newlines and carriage returns. I didn't go so far as to replace newlines with `<br>` in order to make them actually appear as newlines, though; rather, I only focused on making sure that they wouldn't cause Javascript parsing errors. I tested Unicode escapes using emoji and it seems to work fine.

**Comment by sarutak** [comment]
LGTM. Merging in `master` and `branch-1.6`. Thanks @JoshRosen !
I've found another bug related to job descriptions while reviewing and I've open a PR (#13016).

**Pull request closed without merging**
