### PR TITLE
[SPARK-38866][BUILD] Update ORC to 1.7.4

### PR DESCRIPTION
**Pull request by williamhyun**
### What changes were proposed in this pull request?
This PR aims to update ORC to version 1.7.4.

### Why are the changes needed?
This will bring the following bug fixes.
- https://github.com/apache/orc/milestone/7?closed=1

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass the CIs.

### CODE REVIEW

**Comment by williamhyun** [comment]
Although the GitHub Action shows a weird error, it's running currently.
- https://github.com/williamhyun/spark/actions/runs/2152228399

**Review by dongjoon-hyun — COMMENTED** [review]
Thank you for testing Apache ORC 1.7.4 RC0 with Apache Spark, @williamhyun .

**Comment by williamhyun** [comment]
cc: @dongjoon-hyun

**Comment by williamhyun** [comment]
This is running at
- https://github.com/williamhyun/spark/actions/runs/2175610118

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. I checked the GitHub Action result.

Screen Shot 2022-04-16 at 12 24 49 AM

**Comment by dongjoon-hyun** [comment]
Thank you, @williamhyun . Merged to master/3.3.

**Pull request closed without merging**
