### PR TITLE
[SPARK-38103][SQL] Migrate parsing errors of transform into the new error framework

### PR DESCRIPTION
**Pull request by yutoacts**
### What changes were proposed in this pull request?

In this PR, I migrated parsing errors of transform listed below into the new error framework.

- transformNotSupportQuantifierError
- transformWithSerdeUnsupportedError
- tooManyArgumentsForTransformError
- notEnoughArgumentsForTransformError
- invalidTransformArgumentError

### Why are the changes needed?

Porting the parsing errors of transform into the new error framework should improve user experience with Spark SQL.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

`$ build/sbt "test:testOnly *QueryParsingErrorsSuite"`

### CODE REVIEW

**Comment by yutoacts** [comment]
@MaxGekk As far as I attemptted, there is no SQL statement that triggers `notEnoughArgumentsForTransformError` and `invalidTransformArgumentError` for now. 
For instance, the statement `CREATE TABLE table(col int) PARTITIONED BY (years())` ends up causing the error message generated by parser instead of `notEnoughArgumentsForTransformError` generated by `AstBuilder`.

I would like to know if there's any statement that triggers those two exceptions.

**Review by MaxGekk — COMMENTED** [review]
> if not, I think we can either remove them or update grammar rule to make them triggerable.

If these exceptions are not user facing error, let's remove them from QueryExecutionErrors and don't use error classes.

> there is no SQL statement that triggers notEnoughArgumentsForTransformError and invalidTransformArgumentError for now

@rdblue Could you help to trigger the error since your PR https://github.com/apache/spark/pull/24117 added the exception but there are no tests for them, it seems.

**Comment by MaxGekk** [comment]
> there is no SQL statement that triggers notEnoughArgumentsForTransformError and invalidTransformArgumentError for now

@yutoacts Let's remove `notEnoughArgumentsForTransformError` and `invalidTransformArgumentError` from `QueryParsingErrors` and throw `IllegalStateException` since the exceptions are not user facing errors.

**Review by MaxGekk — APPROVED** [review]

**Comment by MaxGekk** [comment]
+1, LGTM. Merging to master.
Thank you, @yutoacts.

**Pull request closed without merging**
