### PR TITLE
[SPARK-14277][CORE] Upgrade Snappy Java to 1.1.2.4

### PR DESCRIPTION
**Pull request by sitalkedia**
## What changes were proposed in this pull request?

Upgrade snappy to 1.1.2.4 to improve snappy read/write performance.
## How was this patch tested?

Tested by running a job on the cluster and saw 7.5% cpu savings after this change.

### CODE REVIEW

**Comment by JoshRosen** [comment]
Jenkins, this is ok to test.

**Comment by JoshRosen** [comment]
LGTM pending Jenkins. Thanks!

**Comment by JoshRosen** [comment]
(Can you remove the "(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)" section from the PR Description?)

**Comment by JoshRosen** [comment]
Merging to master. Thanks!

(By the way, please keep reporting these hotspots that your profiling is uncovering; this is very useful feedback.)

**Comment by sitalkedia** [comment]
@JoshRosen - Thanks a lot for helping out on this. We are trying to port some of our large hadoop jobs to Spark and we are seeing these performance bottlenecks. We will definitely keep reporting them as we discover more.

**Pull request closed without merging**
