### PR TITLE
[SPARK-17156][ML][EXAMPLE] Add multiclass logistic regression Scala Example

### PR DESCRIPTION
**Pull request by jaceklaskowski**
## What changes were proposed in this pull request?

New example for `MultinomialLogisticRegression` ML algorithm.
## How was this patch tested?

local build + run-example

### CODE REVIEW

**Comment by sethah** [comment]
This is going to have to be changed after [SPARK-17163](https://issues.apache.org/jira/browse/SPARK-17163). Sorry about the confusion! We'll still want to make an example with multiclass, though, so maybe we can reuse some of this :)

**Comment by jaceklaskowski** [comment]
I don't mind adapting the example to the upcoming changes and I can work on it. But..

SPARK-17163 has no Fix Version/s field assigned so I'm reading it that it's not clear whether the change gets into the next release or not. Given 2.0.1 might be out in a couple of weeks I believe accepting the example now and changing it later (once SPARK-17163 gets merged) is a viable strategy. What do you think?

/cc @srowen @wangmiao1981

**Comment by sethah** [comment]
We are trying to move quite fast on 17163. I will submit a PR for it soon (not sure how long review will take). The issue here is that the current example will show users how to use an estimator called `MultinomialLogisticRegression` which won't even exist after 17163. I'm not sure it's worth it, but I'm not sure what the goals are for minor releases either. I would appreciate others' opinions.

**Comment by jaceklaskowski** [comment]
Any news on that @sethah? I've seen some discussions about the changes to unify the interfaces, but am wondering how close the other PRs are so I could help with that one myself.

**Comment by sethah** [comment]
@jaceklaskowski You can see https://github.com/apache/spark/pull/14834

**Comment by MLnick** [comment]
by the way multi-class LR will be in 2.1 not 2.0.1, so we do have some time to wait for #14834

**Comment by jaceklaskowski** [comment]
Thanks @MLnick. What would you suggest with the PR then (after the comments from @sethah)? Please guide.

**Comment by sethah** [comment]
https://github.com/apache/spark/pull/14834 is merged now. We did not implement a new API, but we can still update the logistic regression examples to show the new multiclass functionality.

**Comment by jaceklaskowski** [comment]
@sethah Anything to improve the example. I'm open for suggestions and improve the example (to learn that part better). Thanks!

**Comment by sethah** [comment]
I think we should add an example for multiclass classification, to demonstrate that it works in 2.1+. We also need to update the documentation that says we only support binary.

**Comment by sethah** [comment]
I think we should close this. The new example and the user guide should be updated against [SPARK-17239](https://issues.apache.org/jira/browse/SPARK-17239). @jaceklaskowski If you'd still like to do it, please let me know otherwise I am happy to do it. We should try to get this in soon. Thanks!

**Comment by jaceklaskowski** [comment]
@sethah I seem to have missed the other comment with the notes what has to be done to make the PR an example for the change. Sorry.

Since I'm very new to it and the only way to learn it better is to help with the PR here or the one that's coming, I'd like to be engaged one way or the other.

I'm gonna close this PR (to make it consistent JIRA-wise) and open another with the changes you've mentioned to have the example aligned with the changes and the requirements.

Thanks @sethah for your help! See you in the other PR...

**Pull request closed without merging**
