### PR TITLE
[SPARK-5576][SQL] saveAsTable into Hive fails due to duplicate columns

### PR DESCRIPTION
**Pull request by danosipov**
Fix issue with Hive incompatibility with case sensitive columns

### CODE REVIEW

**Comment by sryza** [comment]
Mind adding [SQL] to the title so it gets sorted properly?

**Comment by danosipov** [comment]
@sryza no problem, done

**Comment by marmbrus** [comment]
ok to test

**Comment by danosipov** [comment]
I need some pointers on where to look into why the Pyspark tests failed. @JoshRosen ?

**Comment by JoshRosen** [comment]
I think that the failures here are due to changes to the method signatures in SQLContext: PySpark SQL code depended on the old signatures, which is causing this to fail:

```
**********************************************************************
File "/home/jenkins/workspace/SparkPullRequestBuilder/python/pyspark/sql.py", line 1595, in pyspark.sql.SQLContext.jsonRDD
Failed example:
    sqlCtx.jsonRDD(sc.parallelize(['{}',
            '{"key0": {"key1": "value1"}}'])).collect()
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib64/python2.6/doctest.py", line 1253, in __run
        compileflags, 1) in test.globs
      File "<doctest pyspark.sql.SQLContext.jsonRDD[13]>", line 2, in <module>
        '{"key0": {"key1": "value1"}}'])).collect()
      File "/home/jenkins/workspace/SparkPullRequestBuilder/python/pyspark/sql.py", line 1614, in jsonRDD
        df = self._ssql_ctx.jsonRDD(jrdd.rdd(), samplingRatio)
      File "/home/jenkins/workspace/SparkPullRequestBuilder/python/lib/py4j-0.8.2.1-src.zip/py4j/java_gateway.py", line 538, in __call__
        self.target_id, self.name)
      File "/home/jenkins/workspace/SparkPullRequestBuilder/python/lib/py4j-0.8.2.1-src.zip/py4j/protocol.py", line 304, in get_return_value
        format(target_id, '.', name, value))
    Py4JError: An error occurred while calling o76.jsonRDD. Trace:
    py4j.Py4JException: Method jsonRDD([class org.apache.spark.rdd.MapPartitionsRDD, class java.lang.Double]) does not exist
    	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:333)
    	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:342)
    	at py4j.Gateway.invoke(Gateway.java:252)
    	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
    	at py4j.commands.CallCommand.execute(CallCommand.java:79)
    	at py4j.GatewayConnection.run(GatewayConnection.java:207)
    	at java.lang.Thread.run(Thread.java:745)


**********************************************************************
File "/home/jenkins/workspace/SparkPullRequestBuilder/python/pyspark/sql.py", line 1598, in pyspark.sql.SQLContext.jsonRDD
Failed example:
    sqlCtx.jsonRDD(sc.parallelize(['{"key0": null}',
            '{"key0": {"key1": "value1"}}'])).collect()
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib64/python2.6/doctest.py", line 1253, in __run
        compileflags, 1) in test.globs
      File "<doctest pyspark.sql.SQLContext.jsonRDD[14]>", line 2, in <module>
        '{"key0": {"key1": "value1"}}'])).collect()
      File "/home/jenkins/workspace/SparkPullRequestBuilder/python/pyspark/sql.py", line 1614, in jsonRDD
        df = self._ssql_ctx.jsonRDD(jrdd.rdd(), samplingRatio)
      File "/home/jenkins/workspace/SparkPullRequestBuilder/python/lib/py4j-0.8.2.1-src.zip/py4j/java_gateway.py", line 538, in __call__
        self.target_id, self.name)
      File "/home/jenkins/workspace/SparkPullRequestBuilder/python/lib/py4j-0.8.2.1-src.zip/py4j/protocol.py", line 304, in get_return_value
        format(target_id, '.', name, value))
    Py4JError: An error occurred while calling o76.jsonRDD. Trace:
    py4j.Py4JException: Method jsonRDD([class org.apache.spark.rdd.MapPartitionsRDD, class java.lang.Double]) does not exist
    	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:333)
    	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:342)
    	at py4j.Gateway.invoke(Gateway.java:252)
    	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
    	at py4j.commands.CallCommand.execute(CallCommand.java:79)
    	at py4j.GatewayConnection.run(GatewayConnection.java:207)
    	at java.lang.Thread.run(Thread.java:745)
```

**Comment by danosipov** [comment]
Is there a way to refresh the signatures its using? Sorry, I haven't used PySpark much...

**Comment by JoshRosen** [comment]
Try grepping through the PySpark source to find places where we call `jsonRDD`.  It looks like your PR added another parameter, so any callers are going to have to be updated to provide that parameter.

**Comment by danosipov** [comment]
Hmm, I tried to keep it backwards compatible by only adding it to internal methods, and it doesn't look like PySpark is using any of them. I also made them optional by providing a default - not sure if Java/Python are able to see those.
Thanks - I'll try to fix it.

**Comment by JoshRosen** [comment]
Even though the Scala method has a default, from Java's POV it compiles down to a method without default arguments.  One way to fix this is to provide an overloaded Scala method that accepts the same set of old arguments and which calls the new method with an explicit default (e.g. the way that you'd add a new parameter in Java while retaining backwards-compatibility).

**Comment by danosipov** [comment]
Got you - thanks for the explanation, Josh!

**Comment by marmbrus** [comment]
Thanks for pointing out this issue and working on a solution!

I'm a little hesitant to bake the solution into JSON as this seems like something that could happen with any data source.  Also it seems like you might be able to work around it without making changes to the library itself.  Would something like this work for you (assuming I add `coalesce` to the dataframe DSL)?

```scala
val projection = df.schema
  .map(_.name)
  .groupBy(_.toLowerCase)
  .map { 
    case (lowerCase, otherCases) => 
      coalsece(otherCases.map(df(_)).as(lowerCase)) 
  }

df.select(projection: _*)
```

**Comment by danosipov** [comment]
@marmbrus I think that would work - I should be able to save the Hive table as
```
df.select(projection: _*).saveAsTable("name")
```
and it would have the expected schema & data?

I'm not sure how prevalent the issue is among other users data sets, so whatever solution you think is optimal makes sense.

**Comment by marmbrus** [comment]
Yeah, I think that should work (assuming you are okay with picking a random value in the case a record has two different fields that collapse into the same lower case name, which is what I think your version does too).  I'll make sure we add `coalesce` to the DSL before the 1.3 release.

I'd even consider adding this as a method to dataframe if enough users have this need, but you are the first as far as I know.  Either way I think doing it with a projection is probably better than changing the JSON library.

**Comment by danosipov** [comment]
Works for me - can you delete the PR if no longer need it? I'll keep the fork for local testing.

**Comment by marmbrus** [comment]
Only you (as the creator) can close the PR since apache doesn't grant commiters any special github privileges.  We have a hack where we make a commit that says "Closes #xxxx" but we only do that rarely.

**Pull request closed without merging**
