### PR TITLE
[SPARK-47512][SS] Tag operation type used with RocksDB state store instance lock acquisition/release

### PR DESCRIPTION
**Pull request by anishshri-db**
### What changes were proposed in this pull request?
Tag operation type used with RocksDB state store instance lock acquisition/release

### Why are the changes needed?
Currently its impossible to tell which operation/thread tried to acquire/release the RocksDB instance lock which is crucial in debugging issues around RocksDB instance lock acquisition

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Added unit tests

```
[info] RocksDBSuite:
12:34:41.365 WARN org.apache.hadoop.util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[info] - disallow concurrent updates to the same RocksDB instance - with colFamiliesEnabled=true (with changelog checkpointing) (1 second, 634 milliseconds)
[info] - disallow concurrent updates to the same RocksDB instance - with colFamiliesEnabled=true (without changelog checkpointing) (654 milliseconds)
[info] - disallow concurrent updates to the same RocksDB instance - with colFamiliesEnabled=false (with changelog checkpointing) (609 milliseconds)
[info] - disallow concurrent updates to the same RocksDB instance - with colFamiliesEnabled=false (without changelog checkpointing) (584 milliseconds)
12:34:45.319 WARN org.apache.spark.sql.execution.streaming.state.RocksDBSuite:
```

Verified updated logs
```
sql/core/target/unit-tests.log:1958:13:38:41.698 concurrent-test-thread-3 INFO RocksDB [Thread-17]: RocksDB instance was acquired by [ThreadId: Some(158)] for opType=load_store
sql/core/target/unit-tests.log:2235:13:38:41.886 concurrent-test-thread-3 INFO RocksDB [Thread-17]: RocksDB instance was released by [ThreadId: Some(158)] for opType=load_store
sql/core/target/unit-tests.log:2236:13:38:41.886 pool-1-thread-1-ScalaTest-running-RocksDBSuite INFO RocksDB [Thread-17]: RocksDB instance was acquired by [ThreadId: Some(17)] for opType=close_store
sql/core/target/unit-tests.log:2239:13:38:41.889 pool-1-thread-1-ScalaTest-running-RocksDBSuite INFO RocksDB [Thread-17]: RocksDB instance was released by [ThreadId: Some(17)] for opType=close_store
sql/core/target/unit-tests.log:2249:13:38:41.896 pool-1-thread-1-ScalaTest-running-RocksDBSuite INFO RocksDB [Thread-17]: RocksDB instance was acquired by [ThreadId: Some(17)] for opType=load_store
sql/core/target/unit-tests.log:2518:13:38:41.950 pool-1-thread-1-ScalaTest-running-RocksDBSuite INFO RocksDB [Thread-17]: RocksDB instance was acquired by [ThreadId: Some(17)] for opType=load_store
sql/core/target/unit-tests.log:2562:13:38:42.139 pool-1-thread-1-ScalaTest-running-RocksDBSuite INFO RocksDB [Thread-17]: RocksDB instance was released by [ThreadId: Some(17)] for opType=load_store
sql/core/target/unit-tests.log:2563:13:38:42.139 concurrent-test-thread-2 INFO RocksDB [Thread-17]: RocksDB instance was acquired by [ThreadId: Some(181)] for opType=load_store
sql/core/target/unit-tests.log:2607:13:38:42.293 concurrent-test-thread-2 INFO RocksDB [Thread-17]: RocksDB instance was released by [ThreadId: Some(181)] for opType=load_store
sql/core/target/unit-tests.log:2608:13:38:42.293 pool-1-thread-1-ScalaTest-running-RocksDBSuite INFO RocksDB [Thread-17]: RocksDB instance was acquired by [ThreadId: Some(17)] for opType=load_store
sql/core/target/unit-tests.log:2611:13:38:42.319 pool-1-thread-1-ScalaTest-running-RocksDBSuite INFO RocksDB [Thread-17]: RocksDB instance was acquired by [ThreadId: Some(17)] for opType=rollback_store
sql/core/target/unit-tests.log:2612:13:38:42.319 pool-1-thread-1-ScalaTest-running-RocksDBSuite INFO RocksDB [Thread-17]: RocksDB instance was released by [ThreadId: Some(17)] for opType=rollback_store
sql/core/target/unit-tests.log:2614:13:38:42.319 concurrent-test-thread-3 INFO RocksDB [Thread-17]: RocksDB instance was acquired by [ThreadId: Some(193)] for opType=load_store
sql/core/target/unit-tests.log:2942:13:38:42.525 concurrent-test-thread-3 INFO RocksDB [Thread-17]: RocksDB instance was released by [ThreadId: Some(193)] for opType=load_store
```

### Was this patch authored or co-authored using generative AI tooling?
No

### CODE REVIEW

**Comment by anishshri-db** [comment]
@sahnib @HeartSaVioR - PTAL, thx !

**Review by HeartSaVioR — APPROVED** [review]
+1 pending CI

**Review by sahnib — APPROVED** [review]
LGTM

**Comment by HeartSaVioR** [comment]
Thanks! Merging to master.

**Pull request closed without merging**
