### PR TITLE
[SPARK-42271][CONNECT][PYTHON] Reuse UDF test cases under `pyspark.sql.tests`

### PR DESCRIPTION
**Pull request by xinrong-meng**
### What changes were proposed in this pull request?
Reuse UDF test cases under `pyspark.sql.tests`.

### Why are the changes needed?
Reach parity to the vanilla PySpark.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Unit tests.

SPARK-41661

### CODE REVIEW

**Review by zhengruifeng — APPROVED** [review]
LGTM pending CI

**Comment by xinrong-meng** [comment]
CC @HyukjinKwon @grundprinzip

**Comment by xinrong-meng** [comment]
Test failures are not related to the PR. I will rebase to the latest master.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master and branch-3.4.

**Pull request closed without merging**
