### PR TITLE
[SPARK-22417][PYTHON][FOLLOWUP][BRANCH-2.2] Fix for createDataFrame from pandas.DataFrame with timestamp

### PR DESCRIPTION
**Pull request by ueshin**
## What changes were proposed in this pull request?

This is a follow-up of #19646 for branch-2.2.
The original pr breaks branch-2.2 because the cherry-picked patch doesn't include some code which exists in master.

## How was this patch tested?

Existing tests.

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]

**Comment by BryanCutler** [comment]
LGTM, thanks @ueshin !

**Comment by HyukjinKwon** [comment]
I think we can merge this first to branch-2.2, and then re-run the test in `19701` ..

**Comment by ueshin** [comment]
Thanks for reviewing! merging to branch-2.2.

**Comment by dongjoon-hyun** [comment]
Thank you, @ueshin !

**Pull request closed without merging**
