### PR TITLE
[SPARK-7255] [Streaming] [Documentation] Added documentation for spark.streaming.kafka.maxRetries

### PR DESCRIPTION
**Pull request by BenFradet**
Added documentation for spark.streaming.kafka.maxRetries

### CODE REVIEW

**Comment by srowen** [comment]
Does it need to be said that this only applies to the direct receiver?

**Comment by BenFradet** [comment]
I think so yes now that you mention it.

**Comment by koeninger** [comment]
Somewhat nitpicky, but I'd say something like "maximum number of consecutive trials", just to make it clear it's not a limit for the lifetime of the job.

Again, thanks for noticing this.

**Comment by BenFradet** [comment]
Yup, no problem, will adjust that.

**Comment by koeninger** [comment]
Yknow, I just looked at the code for other reasons, and it is the number of retries, not tries (so the default setting of 1 means a max of 2 consecutive attempts).  Sorry for being spacey earlier in the jira ticket.

    val o = kc.getLatestLeaderOffsets(currentOffsets.keySet)
    if (o.isLeft) {
      val err = o.left.get.toString
      if (retries <= 0) {
        throw new SparkException(err)

**Comment by BenFradet** [comment]
Do you think it will be clear enough if we still keep the default value at
1 and explains this means 2 tries maximum?

Or should we change the default value or the code or the name of the conf?

**Comment by koeninger** [comment]
I think the code, the name of the conf, and the default setting are all
correct.

1 retry means try initially, retry once, then give up, for a total of 2
attempts.

**Comment by BenFradet** [comment]
Ok, will update the doc accordingly.

**Comment by BenFradet** [comment]
Updated the doc to explain the default value.

**Pull request closed without merging**
