### PR TITLE
[SPARK-29011][BUILD] Update netty-all from 4.1.30-Final to 4.1.39-Final.

### PR DESCRIPTION
**Pull request by n-marion**
### What changes were proposed in this pull request?
Upgrade netty-all to latest in the 4.1.x line which is 4.1.39-Final.

### Why are the changes needed?
Currency of dependencies.

### Does this PR introduce any user-facing change?
No.

### How was this patch tested?
Existing unit-tests against master branch.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
ok to test.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @n-marion .
Merged to master.
cc @srowen .

**Comment by dongjoon-hyun** [comment]
Could you make a backport to `branch-2.4` since `branch-2.4` is our LTS branch?

**Comment by n-marion** [comment]
> Could you make a backport to `branch-2.4` since `branch-2.4` is our LTS branch?

#25732

**Pull request closed without merging**
