### PR TITLE
[SPARK-26788][yarn] Remove SchedulerExtensionService.

### PR DESCRIPTION
**Pull request by vanzin**
Since the yarn module is actually private to Spark, this interface was never
actually "public". Since it has no use inside of Spark, let's avoid adding
a yarn-specific extension that isn't public, and point any potential users
are more general solutions (like using a SparkListener).

### CODE REVIEW

**Review by felixcheung — APPROVED** [review]
is there deprecation note on the yarn doc page?

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Review by srowen — APPROVED** [review]

**Comment by vanzin** [comment]
> is there deprecation note on the yarn doc page?

I'm not sure it's even mentioned, but will check. If it's not, I'd rather just no call attention to it (it's never in javadocs, for example).

**Comment by vanzin** [comment]
No mention of the config key or the class name in the documentation, so I think we're good.

**Comment by vanzin** [comment]
Unrelated test failures... they're really weird, as if the YARN mini cluster stopped running containers for > 10 min. No idea what happened.

**Comment by vanzin** [comment]
retest this please

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
cc @steveloughran

**Comment by vanzin** [comment]
So lots of "approvals", but will anyone actually merge the change?

**Comment by srowen** [comment]
Go for it, I dont' see any objections and your judgment is obviously solid in this areas.

**Comment by vanzin** [comment]
I know I can merge my own PRs, I'm just questioning this pattern that I see a lot where people approve PRs but nobody merges them.

**Comment by srowen** [comment]
For me personally it's that I know you can merge them and maybe want to let you pull the trigger as you know best that you don't have anything else you want to do with it, and also maybe which branches it should back port too. I'll merge this one.

**Comment by srowen** [comment]
(For non-committer PRs, I flag the email for followup in 1-3 days in Gmail, and yes I would then merge it, not just leave it approved indefinitely)

**Comment by HyukjinKwon** [comment]
Yup, I think in the same way of @srowen's.

**Pull request closed without merging**
