### PR TITLE
[MINOR][COMMON] Fix copy-paste oversight in variable naming

### PR DESCRIPTION
**Pull request by bjornjon**
## What changes were proposed in this pull request?

JavaUtils.java has methods to convert time and byte strings for internal use, this change renames a variable used in byteStringAs(), from timeError to byteError.

### CODE REVIEW

**Comment by srowen** [comment]
OK, that by itself is probably too minor to bother with. It's not a bad change, but maybe you can look through other similar stretches of code to see if other similar copy / paste errors have been made? it'd be good to try to investigate these in batch as much as possible

**Comment by bjornjon** [comment]
Sounds good. I'll see what I can spot while reading through the code. Whats the best way to review previous suggested changes like this that were to minor to go in? Maybe some of them are still outstanding and I can batch them together.

**Comment by srowen** [comment]
I highlighted it just because there have been a few in the past couple days. It's not so much that unrelated tiny changes should be batched together, but that maybe there are other related tiny changes that would be turned up with a search. There may not be, in which case, it's probably OK to merge this.

**Comment by bjornjon** [comment]
Read through all the code in common. No similar oversights, at least not with variable naming.

**Comment by andrewor14** [comment]
This passed compilation. Merging into master 1.6.

**Pull request closed without merging**
