### PR TITLE
[SPARK-35424][SHUFFLE] Remove some useless code in the ExternalBlockHandler.

### PR DESCRIPTION
**Pull request by weixiuli**
### What changes were proposed in this pull request?

Remove some useless code in the ExternalBlockHandler.

### Why are the changes needed?
There is some useless code in the ExternalBlockHandler, so we may remove it.

### Does this PR introduce _any_ user-facing change?
No
### How was this patch tested?

Exist unittests.

### CODE REVIEW

**Review by srowen — COMMENTED** [review]
It doesn't appear to be used, yes. I think this is also a pretty internal class and module, so probably OK, but is it worth removing just in case? it could be deprecated instead just to be safe.

**Review by mridulm — APPROVED** [review]

**Comment by weixiuli** [comment]
@srowen @approval do you have any questions, thanks.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by weixiuli** [comment]
Thank you so  much ! @HyukjinKwon  @srowen @mridulm

**Pull request closed without merging**
