### PR TITLE
[SPARK-27159][SQL]update mssql server dialect to support binary type

### PR DESCRIPTION
**Pull request by zhulipeng**
## What changes were proposed in this pull request?

Change the binary type mapping from default blob to varbinary(max) for mssql server.
https://docs.microsoft.com/en-us/sql/t-sql/data-types/binary-and-varbinary-transact-sql?view=sql-server-2017
image

## How was this patch tested?

Unit test.

### CODE REVIEW

**Comment by srowen** [comment]
What's the difference in SQL Server? I'm just wondering if there are any compatibility problems with older versions, or whether there's an upside to changing the type?

**Comment by dongjoon-hyun** [comment]
ok to test

**Comment by lipzhu** [comment]
> What's the difference in SQL Server? I'm just wondering if there are any compatibility problems with older versions, or whether there's an upside to changing the type?



> What's the difference in SQL Server? I'm just wondering if there are any compatibility problems with older versions, or whether there's an upside to changing the type?

@srowen This is a bug fix for writing binary data back to MsSql Server. 
#24099 
https://github.com/apache/spark/blob/9ee60a6fe0eed6e6d4e1b4387f51849bda0c6b9c/external/docker-integration-tests/src/test/scala/org/apache/spark/sql/jdbc/MsSqlServerIntegrationSuite.scala#L170

`===== FINISHED o.a.s.sql.jdbc.MsSqlServerIntegrationSuite: 'Basic write test' =====

- Basic write test *** FAILED ***
  com.microsoft.sqlserver.jdbc.SQLServerException: Column, parameter, or variable #5: Cannot find data type BLOB.
  at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:256)
  at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1621)
  at com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:868)
  at com.microsoft.sqlserver.jdbc.SQLServerStatement$StmtExecCmd.doExecute(SQLServerStatement.java:768)
  at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7194)
  at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2930)
  at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:248)
  at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:223)
  at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeUpdate(SQLServerStatement.java:711)
  at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.createTable(JdbcUtils.scala:868)`

**Comment by wangyum** [comment]
retest this please

**Comment by srowen** [comment]
What is this test that is failing -- something you have added locally? Looks OK though. Indeed BLOB doesn't seem to be supported.

**Comment by lipzhu** [comment]
> What is this test that is failing -- something you have added locally? Looks OK though. Indeed BLOB doesn't seem to be supported.

Yes, I just add a unit test to read/write Mssql Server through jdbc.
image

I have added this test case to MsSql server docker integration test suite in another PR. #24099

**Review by srowen — APPROVED** [review]

**Comment by srowen** [comment]
Merged to master

**Comment by dongjoon-hyun** [comment]
Hi, @lipzhu and @srowen .
I'll backport this bugfix to `branch-2.4`.

I did a clean cherry-pick to `branch-2.4` and tested this locally.

Thank you, @lipzhu and @srowen .

**Pull request closed without merging**
