### PR TITLE
[SPARK-37314][K8S][BUILD] Upgrade kubernetes-client to 5.10.1

### PR DESCRIPTION
**Pull request by sarutak**
### What changes were proposed in this pull request?

This PR upgrades kubernetes-client from `5.9.0` to `5.10.1`.

### Why are the changes needed?

kubernetes-client 5.10.0 and 5.10.1 were released, which include some bug fixes.

https://github.com/fabric8io/kubernetes-client/releases/tag/v5.10.0
https://github.com/fabric8io/kubernetes-client/releases/tag/v5.10.1

Especially, the connection leak issue would affect Spark.
https://github.com/fabric8io/kubernetes-client/issues/3561

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

CIs.

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM (Pending CIs)

**Comment by dongjoon-hyun** [comment]
Retest this please

**Comment by dongjoon-hyun** [comment]
There are two known failures, but this PR has another failure. Although it looks like a flaky one, I re-trigger tests to make it sure.
```
- Run SparkRemoteFileTest using a remote data file *** FAILED ***
```

**Review by wangyum — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
`Run SparkRemoteFileTest using a remote data file` passed. Merged to master.
```
KubernetesSuite:
- Run SparkPi with no resources
- Run SparkPi with no resources & statefulset allocation
- Run SparkPi with a very long application name.
- Use SparkLauncher.NO_RESOURCE
- Run SparkPi with a master URL without a scheme.
- Run SparkPi with an argument.
- Run SparkPi with custom labels, annotations, and environment variables.
- All pods have the same service account by default
- Run extraJVMOptions check on driver
- Run SparkRemoteFileTest using a remote data file
- Verify logging configuration is picked from the provided SPARK_CONF_DIR/log4j.properties
- Run SparkPi with env and mount secrets.
- Run PySpark on simple pi.py example
- Run PySpark to test a pyfiles example
- Run PySpark with memory customization
- Run in client mode.
- Start pod creation from template
- PVs with local hostpath storage on statefulsets
- PVs with local hostpath and storageClass on statefulsets
- PVs with local storage
- Launcher client dependencies
- SPARK-33615: Launcher client archives
- SPARK-33748: Launcher python client respecting PYSPARK_PYTHON
- SPARK-33748: Launcher python client respecting spark.pyspark.python and spark.pyspark.driver.python
- Launcher python client dependencies using a zip file
- Test basic decommissioning
...
```

**Pull request closed without merging**
