### PR TITLE
[SPARK-16236] [SQL] Add Path Option back to Load API in DataFrameReader

### PR DESCRIPTION
**Pull request by gatorsmile**
#### What changes were proposed in this pull request?

@koertkuipers identified the PR https://github.com/apache/spark/pull/13727/ changed the behavior of `load` API. After the change, the `load` API does not add the value of `path` into the `options`. Thank you!

This PR is to add the option `path` back to `load()` API in `DataFrameReader`, if and only if users specify one and only one `path` in the `load` API. For example, users can see the `path` option after the following API call,

``` Scala
spark.read
  .format("parquet")
  .load("/test")
```
#### How was this patch tested?

Added test cases.

### CODE REVIEW

**Comment by gatorsmile** [comment]
cc @rxin @tdas @koertkuipers

**Comment by gatorsmile** [comment]
cc @rxin The code is ready for review. Thanks!

**Comment by rxin** [comment]
LGTM -- cc @tdas to take a look since he wrote the original patch.

**Comment by liancheng** [comment]
LGTM.

**Comment by rxin** [comment]
Merging in master/2.0.

**Comment by zsxwing** [comment]
I noticed that the Python API is inconsistent here: https://github.com/apache/spark/blob/1aad8c6e59c1e8b18a3eaa8ded93ff6ad05d83df/python/pyspark/sql/readwriter.py#L147

It always calls `def load(paths: String*)`.

**Comment by gatorsmile** [comment]
@zsxwing Let me try to fix it. Thanks!

**Comment by gatorsmile** [comment]
The problem also exists in the other APIs:
like parquet, json and others.
https://github.com/apache/spark/blob/25520e976275e0d1e3bf9c73128ef4dec4618568/sql/core/src/main/scala/org/apache/spark/sql/DataFrameReader.scala#L407-L410

Let me fix them in the same PR. Thanks!

**Comment by zsxwing** [comment]
@gatorsmile parquet, json or other file formats support both `path` and `paths` options. So that's not a problem.

**Comment by gatorsmile** [comment]
@zsxwing If we just provide one `path` in the function input, it will not put `path` into the `options`. The API `parquet(path: String)`still calls `load(paths : _*)`, instead of `load(path)`. Thus, we will introduce inconsistent behavior, compared with `load(path: String)`.

Could you review the new PR I just submitted? Let me know if anything is not appropriate. https://github.com/apache/spark/pull/13965. Thanks!

**Comment by koertkuipers** [comment]
For parquet, json etc. path not being put in options is not an issue since
they don't retrieve it from the options

**Pull request closed without merging**
