### PR TITLE
[SPARK-6184][SQL] Relocate logDebug to correct location in ResolveSortReferences

### PR DESCRIPTION
**Pull request by viirya**
`logDebug` messages in `ResolveSortReferences` are incorrectly placed. This pr fixes it. Besides, directly using `p.output` instead of `projectList.map(_.toAttribute)`.

### CODE REVIEW

**Comment by chenghao-intel** [comment]
LTGM, but is it possible go after #4892 ? :)

**Comment by chenghao-intel** [comment]
Hopefully this PR doesn't conflict with #4892

**Comment by viirya** [comment]
@chenghao-intel Thanks! Looks like they shouldn't conflict.

**Comment by viirya** [comment]
CC @marmbrus.

**Comment by marmbrus** [comment]
I'm not really sure I would say these debugging messages are in the "wrong place".  They are in the place that they needed to be when I was debugging this code, and they aren't really intended for anything other than that.  The change to use .output instead is more concise, but is a no-op.  While its good to have simple code, there is a limited amount of time that can be spent reviewing and merging PRs and I'd rather most PRs came with test cases that were failing previously and are now fixed.

**Comment by viirya** [comment]
ok. let's close this.

**Pull request closed without merging**
