### PR TITLE
[SPARK-22221][SQL][FOLLOWUP] Externalize spark.sql.execution.arrow.maxRecordsPerBatch

### PR DESCRIPTION
**Pull request by BryanCutler**
## What changes were proposed in this pull request?

This is a followup to #19575 which added a section on setting max Arrow record batches and this will externalize the conf that was referenced in the docs.

## How was this patch tested?
NA

### CODE REVIEW

**Comment by BryanCutler** [comment]
cc @gatorsmile

**Comment by gatorsmile** [comment]
Thanks for submitting this follow-up PR. Originally, I planned to do it with the other renaming work.

**Comment by BryanCutler** [comment]
Oh, this conf isn't used for any of the group UDFs, but if you prefer to combine it there, I will close this

**Comment by BryanCutler** [comment]
retest this please

**Comment by gatorsmile** [comment]
LGTM

Thanks! Merged to master/2.3

**Pull request closed without merging**
