### PR TITLE
[SPARK-38011][SQL] Remove duplicated and useless configuration in ParquetFileFormat

### PR DESCRIPTION
**Pull request by yikf**
### What changes were proposed in this pull request?
Currently, we called `ParquetWriteSupport.setSchema(requiredSchema, hadoopConf)` when ParquetFileFormat buildReaderWithPartition, and this helper method set `org.apache.spark.sql.parquet.row.attributes` and `parquet.writer.version`, actually,  the former is already set and latter is useless when parquetRead

### Why are the changes needed?
duplicated configuration

### Does this PR introduce _any_ user-facing change?
no, duplicated configuration only

### How was this patch tested?
Existing tests

### CODE REVIEW

**Comment by LuciferYang** [comment]
A similar situation exists in `ParquetScan#createReaderFactory`

**Comment by Yikf** [comment]
> A similar situation exists in `ParquetScan#createReaderFactory`

Thanks a log for your reminder, updated

**Comment by Yikf** [comment]
@cloud-fan Could you please take a look when you have a time? Thanks

**Review by cloud-fan — APPROVED** [review]

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Comment by sadikovi** [comment]
@Yikf The PR description mentions that we already set parquet writer version. Can you point where it is set after this change?

**Comment by sadikovi** [comment]
Also, should `ParquetWriteSupport.setSchema` be removed altogether if it is not used?

**Comment by LuciferYang** [comment]
> @Yikf The PR description mentions that we already set parquet writer version. Can you point where it is set after this change?

`writer version` is useless when reading

**Comment by sadikovi** [comment]
Yes, I see. I missed the context, needed to click to expand the code. I thought the code was removed from the write path.

**Pull request closed without merging**
