### PR TITLE
[SPARK-15925][SQL][SPARKR] Replaces registerTempTable with createOrReplaceTempView

### PR DESCRIPTION
**Pull request by liancheng**
## What changes were proposed in this pull request?

This PR replaces `registerTempTable` with `createOrReplaceTempView` as a follow-up task of #12945.
## How was this patch tested?

Existing SparkR tests.

### CODE REVIEW

**Comment by shivaram** [comment]
Thanks @liancheng - there is a style error because line length exceeded 100 chars. 

Also we'll need to note this breaking change in the programming guide  (http://spark.apache.org/docs/latest/sparkr.html#migration-guide) -- If we are doing that in a separate PR it'll be good to open a JIRA for it.

**Comment by shivaram** [comment]
Otherwise code change LGTM

**Comment by liancheng** [comment]
@shivaram Thanks for the review. I'm updating the SQL programming guide in #13592, will document it. (Actually that's why I found that this API hadn't been update.)

**Comment by shivaram** [comment]
Merging this to master and branch-2.0

**Pull request closed without merging**
