### PR TITLE
[SPARK-35292][PYTHON] Delete redundant parameter in mypy configuration

### PR DESCRIPTION
**Pull request by garawalid**
### What changes were proposed in this pull request?

The parameter **no_implicit_optional** is defined twice in the mypy configuration, [ligne 20](https://github.com/apache/spark/blob/master/python/mypy.ini#L20) and ligne 105.

### Why are the changes needed?

We would like to keep the mypy configuration clean.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

This patch can be tested with `dev/lint-python`

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @zero323 FYI

**Comment by HyukjinKwon** [comment]
@garawalid, would you mind taking a look for https://github.com/apache/spark/pull/32418/checks?check_run_id=2487946353 and enable GitHub Actions please? Apache Spark leverages forked repository's GItHub Actions for building and testing the changes in the PR.

**Comment by garawalid** [comment]
@HyukjinKwon, thanks for pointing this out, it's done.

**Comment by srowen** [comment]
Jenkins retest this please

**Review by srowen — APPROVED** [review]

**Review by zero323 — APPROVED** [review]

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
