### PR TITLE
[SPARK-46069][SQL][FOLLOWUP] Make sure the cast expression is date type when unwrap timestamp type to date type

### PR DESCRIPTION
**Pull request by wankunde**
### What changes were proposed in this pull request?

A followup of https://github.com/apache/spark/pull/43982 
* make sure the cast expression is date type when unwrap timestamp type to date type
* Change the function name from `unwrapTimeStampToDate` to `unwrapTimestampToDate`

### Why are the changes needed?

A followup.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Exists UT

### Was this patch authored or co-authored using generative AI tooling?

No

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Hi, @wankunde .
- The follow-up should not reuse the original PR title. Please use a proper PR title for your code itself.
```
- Cast(fromExp, _, timeZoneId, evalMode), ts @ Literal(value, _))
+ Cast(fromExp: DateType, _, timeZoneId, evalMode), ts @ Literal(value, _))
```

- Could you re-trigger the CIs or provide the CI link?

**Review by HyukjinKwon — APPROVED** [review]
Agree with @dongjoon-hyun 's. The change itself LGTM.

**Comment by wankunde** [comment]
> Hi, @wankunde .
> 
> * The follow-up should not reuse the original PR title. Please use a proper PR title for your code itself.
> 
> ```
> - Cast(fromExp, _, timeZoneId, evalMode), ts @ Literal(value, _))
> + Cast(fromExp: DateType, _, timeZoneId, evalMode), ts @ Literal(value, _))
> ```
> 
> * Could you re-trigger the CIs or provide the CI link?

Thanks for your remind, update the PR title and re-trigger the CI, thanks

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thanks!

**Comment by dongjoon-hyun** [comment]
Oh, @wankunde . It's a compilation failure.

```
[error] /home/runner/work/spark/spark/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/optimizer/UnwrapCastInBinaryComparison.scala:142:21: fruitless type test: a value of type org.apache.spark.sql.catalyst.expressions.Expression cannot also be a org.apache.spark.sql.types.DateType
```

**Comment by wangyum** [comment]
@wankunde Please fix the PR description.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Pull request closed without merging**
