### PR TITLE
[SPARK-30415][SQL]Improve Readability of SQLConf Doc

### PR DESCRIPTION
**Pull request by iRakson**
### What changes were proposed in this pull request?
SQLCOnf Doc updated.

### Why are the changes needed?
Some doc comments were not written properly. Space was missing at many places. This patch updates the doc.

### Does this PR introduce any user-facing change?
No.

### How was this patch tested?
Documentation update.

### CODE REVIEW

**Review by MaxGekk — APPROVED** [review]

**Comment by srowen** [comment]
Jenkins test this please

**Comment by iRakson** [comment]
Retest this please

**Comment by srowen** [comment]
Jenkins test this please

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
