### PR TITLE
[SPARK-19684] [DOCS] Remove developer info from docs.

### PR DESCRIPTION
**Pull request by kayousterhout**
This commit moves developer-specific information from the release-
specific documentation in this repo to the developer tools page on
the main Spark website. This commit relies on this PR on the
Spark website: https://github.com/apache/spark-website/pull/33.

@srowen

### CODE REVIEW

**Review by srowen — APPROVED** [review]

**Comment by kayousterhout** [comment]
Ignored the appveyor failure based on advice from @shivaram that this was broken by the SQL folks (and it does seem clearly unrelated to this PR), and merged this into master.  Thanks for the review @srowen.

**Comment by shivaram** [comment]
Just to clarify what I meant is that there was a similar error fixed due to Hadoop / SQL issues by @HyukjinKwon in https://github.com/apache/spark/pull/16927 - I'll see if this happens again and file a issue if it does

**Comment by shivaram** [comment]
Hmm I think this specific one timed out, so it might not be worth investigating https://ci.appveyor.com/project/ApacheSoftwareFoundation/spark/build/824-master/messages

**Comment by HyukjinKwon** [comment]
Let me run a build in my account to double check and create a JIRA with cc'ing you if it is broken.

**Comment by HyukjinKwon** [comment]
Thanks for cc'ing me.

**Comment by HyukjinKwon** [comment]
Ah, this one seems timed out because it exceeds the 1 hour limitation in AppVeyor. It seems now R tests could take longer than an hour including the build rarely.

This limit could be increased a bit by asking a bit. My account has 1 and half hours (I asked when I tried to run some Scala/Java tests). Let me maybe try to ask increasing it first if you all think it is fine.

If it can be a problem with the increased time in the future, let me try to split the tests as I did for Scala/Java tests in my account.

**Comment by shivaram** [comment]
Yeah asking them for 1.5hr seems like a good first step. We can also see what fraction of time it takes for build vs. tests. I guess we can't make builds faster without some effort, but we could look at making the tests faster or running a subset of them (for example the RDD tests in SparkR are probably not high priority as the API is private etc.)

**Comment by HyukjinKwon** [comment]
I see. Sure. Just as a side note, if you download the log, it prints the times.

In this case, it was so close assuming from the last log :).

```
[00:59:47] Windows-specific tests: .
[00:59:47] 
[00:59:47] Warnings -----------------------------------------------------------------------
[00:59:47] 1. infer types and check types (@test_sparkSQL.R#109) - unable to identify current timezone 'C':
[00:59:47] please set environment variable 'TZ'
[00:59:47] 
[00:59:47] DONE ===========================================================================
```

**Comment by HyukjinKwon** [comment]
I have a confirmation that it is increased to 90 mins now.

**Comment by shivaram** [comment]
Thanks - will keep an eye out to see if the time out errors are gone.

**Pull request closed without merging**
