### PR TITLE
[SPARK-20661][SparkR][Test] SparkR tableNames() test fails

### PR DESCRIPTION
**Pull request by falaki**
## What changes were proposed in this pull request?
Cleaning existing temp tables before running tableNames tests

## How was this patch tested?
SparkR Unit tests

### CODE REVIEW

**Comment by yhuai** [comment]
@felixcheung fyi. I think the main problem of this test is that it will be broken if tests executed before this one leak any table. I think this change makes sense. I will merge it once it passes jenkins.

**Comment by shivaram** [comment]
LGTM. Thanks @falaki  -- BTW is this a problem only on master or should we also backport this ?

**Comment by falaki** [comment]
@shivaram it seems to have started today with this build: https://amplab.cs.berkeley.edu/jenkins/view/Spark%20QA%20Test/job/spark-master-test-sbt-hadoop-2.7/2844/consoleFull

The build just before that does not have the failure: https://amplab.cs.berkeley.edu/jenkins/view/Spark%20QA%20Test/job/spark-master-test-sbt-hadoop-2.7/2843/consoleFull

**Comment by yhuai** [comment]
Seems 2.2 build is fine. But, I'd like to get this merged in branch-2.2 since this test will fail if any previous tests leak tables.

**Comment by yhuai** [comment]
Thanks @falaki. Merging to master and branch-2.2.

**Comment by felixcheung** [comment]
Hmm, do we know why temp tables are getting leak since https://github.com/apache/spark/pull/17649

But not before?

**Comment by yhuai** [comment]
I do not think https://github.com/apache/spark/pull/17649 caused the problem. I saw failures without that internally.

**Comment by felixcheung** [comment]
ah ok, i thought we said it was this build introducing this failure https://github.com/apache/spark/pull/17892#issuecomment-299920986

thanks, it's good to know

**Pull request closed without merging**
