### PR TITLE
[Minor][Doc] In Dataset docs, remove self link to Dataset and add link to Column

### PR DESCRIPTION
**Pull request by techaddict**
## What changes were proposed in this pull request?

Documentation Fix

### CODE REVIEW

**Comment by rxin** [comment]
hm I'm actually not sure whether we always want to link, especially self links given it's already on the same file.

**Comment by techaddict** [comment]
@rxin I'm also biased on not doing self-links, but there are already so many self-links on datasets docs So we should either remove those or add these to make everything consistent.

**Comment by rxin** [comment]
Alright do you want to update the pr to remove them instead?

**Comment by techaddict** [comment]
@rxin Sure

**Comment by techaddict** [comment]
@rxin Done 👍

**Comment by rxin** [comment]
LGTM pending tests.

can you update the title to say

"[Minor][Doc] In Dataset docs, remove self link to Dataset and add link to Column"

**Comment by rxin** [comment]
Merging in master/2,0.

**Pull request closed without merging**
