### PR TITLE
Fixed links to the API

### PR DESCRIPTION
**Pull request by aseigneurin**

### CODE REVIEW

**Comment by srowen** [comment]
LGTM

**Comment by mengxr** [comment]
@aseigneurin Please send the patch to master branch instead of a release branch unless it is a bug fix in particular to that branch. You can close this PR and open another PR to change the target branch. Thanks!

**Comment by aseigneurin** [comment]
@mengxr: Done here: https://github.com/apache/spark/pull/8838

**Comment by srowen** [comment]
Thanks @aseigneurin you can close this first PR

**Pull request closed without merging**
