### PR TITLE
[SPARK-15395][Core]Use getHostString to create RpcAddress (backport for 1.6)

### PR DESCRIPTION
**Pull request by zsxwing**
## What changes were proposed in this pull request?

Backport #13185 to branch 1.6.
## How was this patch tested?

Jenkins unit tests.

### CODE REVIEW

**Comment by zzcclp** [comment]
retest this please

**Comment by zsxwing** [comment]
Merging to1.6

**Comment by zzcclp** [comment]
@zsxwing , why does this pr be reverted in branch-1.6?

**Comment by zsxwing** [comment]
@zzcclp see https://issues.apache.org/jira/browse/SPARK-16017

**Pull request closed without merging**
