### PR TITLE
[SPARK-35666][ML]  gemv skip array shape checking

### PR DESCRIPTION
**Pull request by zhengruifeng**
### What changes were proposed in this pull request?
In existing impls, it is common case that the vector/matrix need to be sliced/copied just due to shape match.
which makes the logic complex and introduce extra costing of slicing & copying.

### Why are the changes needed?
1, avoid slicing and copying due to shape checking;
2, simpify the usages;

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
existing testsuites

### CODE REVIEW

**Comment by zhengruifeng** [comment]
retest this please

**Comment by zhengruifeng** [comment]
friendly ping @srowen @WeichenXu123

**Review by srowen — COMMENTED** [review]
Looks ok pending tests

**Comment by zhengruifeng** [comment]
retest this please

**Comment by zhengruifeng** [comment]
@srowen I think this PR is ready.

**Review by srowen — APPROVED** [review]

**Comment by zhengruifeng** [comment]
retest this please

**Comment by zhengruifeng** [comment]
Merged to master, thanks @srowen for reviewing!

**Pull request closed without merging**
