### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by jaceklaskowski**
Two typos squashed.

BTW Let me know how to proceed with other typos if I ran across any. I don't feel well to leave them aside as much as sending pull requests with such tiny changes. Guide me.

### CODE REVIEW

**Comment by srowen** [comment]
To lower the overhead, maybe you can take a pass over all of the project to detect typos? a spell-checker will turn up way too many false positives, but half an hour skimming them might flag a few more fixes. Inevitably small fixes will just turn up in the course of other work, but whatever can be done to batch together tiny but thematically similar changes would be appreciated.

**Comment by srowen** [comment]
Disregard the failure, it's unrelated

**Comment by jaceklaskowski** [comment]
Ok, deal. I can run a spell-checker and see what I can fix within a half-an-hour timeframe. Should I go and create a JIRA task for it? Any particular module/package to look at during the timeframe?

Thanks @srowen for the help!

**Comment by srowen** [comment]
If it's a handful of typos I wouldn't bother with a JIRA. I think the operating theory is JIRA = what and PR = how, and if those are virtually the same there's no point in duplicating. 

I'd focus on docs I suppose as it is much more to be read. In fact I don't know if you could reasonably search scala source for typos because of all the false positives, but searching generated scaladoc might be reasonable. Still, sounds possibly too noisy to search.

**Comment by rxin** [comment]
+1

If you are doing a lot of these, it'd be great to batch them. Don't be mistaken - the effort is hugely appreciated!

**Comment by jaceklaskowski** [comment]
Thanks @rxin @srowen for support! It took me 30 minutes to find and use `aspell` on a single Scala package and it drove me crazy with tons of false positives - every Scala class name was wrong :(

I'd rather be spending my time on fixing the typos in the docs as I know where few typos lurk.

Thanks again!

**Comment by srowen** [comment]
Yeah that's fine, I think Scala files may be too much to bear. I just use the spell-checker in the IDE as I find it a little easier to manage. Docs are indeed higher value and easier to manage.

**Comment by rxin** [comment]
@jaceklaskowski is this ready to be merged or are you waiting to submit more?

**Comment by jaceklaskowski** [comment]
I need few more hours. I'll ping you. Thanks.

**Comment by srowen** [comment]
It's fine if this is what you've found. I can merge

**Comment by jaceklaskowski** [comment]
All for now. Merge at will. Thanks.

**Comment by srowen** [comment]
Merged to master/1.5

**Pull request closed without merging**
