### PR TITLE
[SPARK-30954][ML][R]Make class name the same as file name

### PR DESCRIPTION
**Pull request by kevinyu98**
### What changes were proposed in this pull request?

Based on [Spark-30954](https://issues.apache.org/jira/browse/SPARK-30954), under `org.apache.spark.ml.r`, most class names are the same as the file name, except these class namees

- `DecisionTreeClassificationWrapper.scala`

- `GBTClassificationWrapper.scala`

- `GBTRegressionWrapper.scala`

- `RandomForestClassificationWrapper.scala`

- `RandomForestRegressionWrapper.scala`

### Why are the changes needed?

Make the name consistence in the `R` package.

### Does this PR introduce any user-facing change?

No

### How was this patch tested?

run the R test

`./R/run-tests.sh`

### CODE REVIEW

**Comment by kevinyu98** [comment]
@huaxingao

**Comment by huaxingao** [comment]
@kevinyu98 
Hi Kevin, thanks for working on this. I think you missed ```DecisionTreeREgressionWrapper.scala```. Also, the title of your PR is not right ```[parkSPARK-30954]```

**Comment by kevinyu98** [comment]
@huaxingao thanks, I added `DecisionTreeREgressionWrapper.scala`.

**Comment by huaxingao** [comment]
I think it's easier to rename the scala files:
```
DecisionTreeClassificationWrapper.scala -> DecisionTreeClassifierWrapper.scala

DecisionTreeRegressionWrapper.scala -> DecisionTreeRegressorWrapper.scala

GBTClassificationWrapper.scala -> GBTClassifierWrapper.scala

GBTRegressionWrapper.scala -> GBTRegressorWrapper.scala

RandomForestClassificationWrapper.scala -> RandomForestClassifierWrapper.scala

RandomForestRegressionWrapper.scala -> RandomForestRegressorWrapper.scala
```
cc @zhengruifeng

**Comment by kevinyu98** [comment]
@huaxingao @zhengruifeng, I opened another pr to make the file name changes. I will close this one. thanks. [pr27940](https://github.com/apache/spark/pull/27940)

**Comment by dongjoon-hyun** [comment]
Hi, @kevinyu98 . I'll close this PR because #27940 got two approval already.

**Comment by kevinyu98** [comment]
@dongjoon-hyun Thanks very much.

**Pull request closed without merging**
