### PR TITLE
[SPARK-8356][SQL] Reconcile callUDF and callUdf

### PR DESCRIPTION
**Pull request by BenFradet**
Deprecates `callUdf` in favor of `callUDF`.

### CODE REVIEW

**Comment by marmbrus** [comment]
@rxin is there any reason to not deprecate the `callUDF` functions (other than the string one that has been renamed here?  They seem redundant with `val myUDF = udf(...)` and they don't handle input coercion.

**Comment by BenFradet** [comment]
pinging @marmbrus and @rxin

**Comment by marmbrus** [comment]
Can we also please deprecate the `def callUDF(f: FunctionN[_]...` functions with a message that says to use `udf(...)` instead?  Thanks!

**Comment by BenFradet** [comment]
Will do, glad to hear this is sorted.

**Comment by marmbrus** [comment]
Thanks!  Merging to master.

**Comment by BenFradet** [comment]
Thank you for helping me out.

**Comment by marmbrus** [comment]
Mind fixing these?  I think its okay to drop the tests in order to make the build clean, given the function is deprecated (and I think there is no way to avoid the warning here).

```
[warn] /home/michael/spark/sql/core/src/test/scala/org/apache/spark/sql/DataFrameSuite.scala:309: method callUdf in object functions is deprecated: Use callUDF
[warn]       df.select($"id", callUdf("simpleUdf", $"value")),
[warn]                        ^
[warn] /home/michael/spark/sql/core/src/test/scala/org/apache/spark/sql/SQLQuerySuite.scala:146: method callUDF in object functions is deprecated: Use udf
[warn]     val dfWithId = df.withColumn("id", callUDF(id, StringType))
[warn]                                        ^
```

**Comment by BenFradet** [comment]
Will do.

**Comment by BenFradet** [comment]
Should I replace calls to the old ```callUDF``` by ```udf``` as well?
There are some in mllib such as [this one](https://github.com/apache/spark/blob/master/mllib/src/main/scala/org/apache/spark/ml/Transformer.scala#L119).

**Comment by marmbrus** [comment]
Yeah, that would be awesome where possible.  Unfortunately, I think we may also need to add back in a version of `callUDF` that takes in `DataType`s for its input and output parameters.  In some places [like this](https://github.com/apache/spark/blob/master/mllib/src/main/scala/org/apache/spark/ml/Transformer.scala#L119) no `TypeTags` are available for `udf` to use for inference.

/cc @mengxr

**Comment by BenFradet** [comment]
Would it be possible to reopen the PR or should I open another one?

**Comment by marmbrus** [comment]
Open a new JIRA and PR please.

**Pull request closed without merging**
