### PR TITLE
[SPARK-49541][BUILD] Upgrade log4j2 to 2.24.1

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to upgrade log4j2 from `2.22.1` to `2.24.1`.

### Why are the changes needed?
- The full release notes:
https://github.com/apache/logging-log4j2/releases/tag/rel%2F2.24.1
https://github.com/apache/logging-log4j2/releases/tag/rel%2F2.24.0
https://github.com/apache/logging-log4j2/releases/tag/rel%2F2.23.1
https://github.com/apache/logging-log4j2/releases/tag/rel%2F2.23.0

- The new version contains some bug fixes:
Fix regression in JdkMapAdapterStringMap performance. (https://github.com/apache/logging-log4j2/issues/2238)
Fix NPE in PatternProcessor for a UNIX_MILLIS pattern (https://github.com/apache/logging-log4j2/issues/2346)
Fix that parameterized message formatting throws an exception when there are insufficient number of parameters. It previously simply
didn't replace the '{}' sequence. The behavior changed in 2.21.0 and should be restored for backward compatibility. (https://github.com/apache/logging-log4j2/issues/2380)
Fix putAll() in the default thread context map implementation (https://github.com/apache/logging-log4j2/pull/2942)

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by LuciferYang** [comment]
https://github.com/apache/spark/pull/48057#discussion_r1752095345

Upon further analysis, it appears that there are some issues with the method `copyAndPutAll` in `org.apache.logging.log4j.internal.map.UnmodifiableArrayBackedMap`. From the debugging process, it seems that the intention here is to put `executor_id -> 1` into an `UnmodifiableArrayBackedMap` that already contains `data -> some-data`. However, the resulting map only contains `executor_id -> 1`. I believe this is not as expected.

image

image

**Comment by LuciferYang** [comment]
try to fix this issue: https://github.com/apache/logging-log4j2/pull/2942

**Comment by LuciferYang** [comment]
> try to fix this issue: [apache/logging-log4j2#2942](https://github.com/apache/logging-log4j2/pull/2942)

Fixed, let's wait 2.24.1

**Comment by LuciferYang** [comment]
Testing log4j 2.24.1 https://github.com/apache/spark/pull/48310

**Comment by LuciferYang** [comment]
@panbingkun 2.24.1 should be able to pass the tests. Could you please update the PR, including the PR title and description? We can continue to move forward with this PR.

**Review by LuciferYang — APPROVED** [review]
+1, LGTM

image

But  it's best to retrigger the Docker integrated tests :)

**Comment by panbingkun** [comment]
> +1, LGTM
> 
> image
> But it's best to retrigger the Docker integrated tests :)

Done.

**Comment by LuciferYang** [comment]
Merged into master for Spark 4.0. Thanks @panbingkun

**Comment by dongjoon-hyun** [comment]
Thank you, @panbingkun and @LuciferYang .

**Pull request closed without merging**
