### PR TITLE
[SPARK-45166][PYTHON] Clean up unused code paths for pyarrow<4

### PR DESCRIPTION
**Pull request by zhengruifeng**
### What changes were proposed in this pull request?
Clean up unused code paths for pyarrow<4

### Why are the changes needed?
the minimum version had been upgraded to 4.0.0 in https://issues.apache.org/jira/browse/SPARK-44183

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
updated CI

### Was this patch authored or co-authored using generative AI tooling?
No

### CODE REVIEW

**Comment by zhengruifeng** [comment]
cc @HyukjinKwon @dongjoon-hyun

**Review by HyukjinKwon — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @zhengruifeng and @HyukjinKwon .
Pending CIs.

**Review by yaooqinn — APPROVED** [review]

**Review by dongjoon-hyun — COMMENTED** [review]
Could you check the PySpark UT failure?

In addition to the style issue,
```
flake8 checks failed:
./python/pyspark/sql/pandas/types.py:64:5: F401 'distutils.version.LooseVersion' imported but unused
    from distutils.version import LooseVersion
    ^
1     F401 'distutils.version.LooseVersion' imported but unused
```

**Review by dongjoon-hyun — APPROVED** [review]
Pending CIs.

**Comment by dongjoon-hyun** [comment]
Could you re-trigger the failed PySpark pipeline?

**Comment by zhengruifeng** [comment]
> Could you re-trigger the failed PySpark pipeline?

sure

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
