### PR TITLE
[SPARK-29152][CORE][2.4] Executor Plugin shutdown when dynamic allocation is enabled

### PR DESCRIPTION
**Pull request by iRakson**
### What changes were proposed in this pull request?
Added a Shutdown Hook in `executor.scala` which will ensure that executor's `stop()` method is always called.

### Why are the changes needed?
In case executors are not going down gracefully, their `stop()` is not called. 

### Does this PR introduce any user-facing change?
No.

### How was this patch tested?
Manually

### CODE REVIEW

**Comment by iRakson** [comment]
cc @dongjoon-hyun

**Comment by dongjoon-hyun** [comment]
ok to test

**Comment by dongjoon-hyun** [comment]
Thank you, @iRakson !

**Comment by dongjoon-hyun** [comment]
Retest this please

**Comment by iRakson** [comment]
I will check the issue.

**Comment by dongjoon-hyun** [comment]
Thank you, @iRakson !

**Comment by vanzin** [comment]
There are a bunch of OOM errors in the test output. They all seem to be on the driver side, which is not touched by this PR, so it's unclear to me how the change here could cause those failures.

I can't reproduce the OOM locally, but if someone can and is able to attach a debugger or get a heap dump, it could help.

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by dongjoon-hyun** [comment]
According to the failure history, this PR always fails with Maven at the following. And, mostly, it causes non-OOM failures.
```
BarrierTaskContextSuite:
- global sync by barrier() call
- support multiple barrier() call within a single task *** FAILED ***
  org.apache.spark.SparkException: Job aborted due to stage failure: Could not recover from a failed barrier ResultStage. Most recent failure reason: Stage failed because barrier task ResultTask(0, 1) finished unsuccessfully.
```

**Comment by vanzin** [comment]
That's what is reported on the UI. But if you look at the actual unit-tests.log file, there are a bunch of OOM errors. From the latest timed out run:

```
===== TEST OUTPUT FOR o.a.s.scheduler.BarrierTaskContextSuite: 'support multiple barrier() call within a single task' =====

...

19/12/18 10:08:53.307 rpc-server-4270-2 ERROR TransportRequestHandler: Error sending result RpcResponse{requestId=6150562811854402958, body=NioManagedBuffer{buf=java.nio.HeapByteBuffer[pos=0 lim=47 cap=64]}} to /127.0.0.1:43378; closing connection
io.netty.handler.codec.EncoderException: java.lang.OutOfMemoryError: Java heap space
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:716)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:708)
```

**Comment by dongjoon-hyun** [comment]
Oh, got it, @vanzin .

**Comment by dongjoon-hyun** [comment]
Ping, @iRakson .

**Comment by iRakson** [comment]
Retest this please.

**Comment by dongjoon-hyun** [comment]
Retest this please

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by iRakson** [comment]
@dongjoon-hyun @vanzin 
Please take a look at this approach for solving this issue.
Earlier i was adding a shutdown hook in the `executor.scala` which calls stop() method of executors.

Instead of adding a shutdown hook, now i am passing `StopExecutor` call to executors before killing them. This way they will stop themselves on their own before being killed.

I think this approach is better than forcing a shutdown hook.

**Comment by iRakson** [comment]
retest this please.

**Comment by dongjoon-hyun** [comment]
Retest this please

**Comment by iRakson** [comment]
gentle ping @dongjoon-hyun @vanzin

**Comment by dongjoon-hyun** [comment]
If this one is better, shall we update `master` and `branch-3.0` first?
We had better be consistent in all active branches if there is no reason.

**Comment by iRakson** [comment]
> If this one is better, shall we update `master` and `branch-3.0` first?
> We had better be consistent in all active branches if there is no reason.

Yes. Actually that is what I was thinking as well. We should update it in master and 3.0 as well.

I have one doubt though. 
Should I create a new JIRA and raise PR for that, I mean that way it will be better to track the changes ?

**Comment by dongjoon-hyun** [comment]
Since 3.0 is not released yet, you can create a follow-up PR like `[SPARK-29152][CORE][FOLLOWUP]` on master branch.

**Comment by iRakson** [comment]
> Since 3.0 is not released yet, you can create a follow-up PR like `[[SPARK-29152](https://issues.apache.org/jira/browse/SPARK-29152)][CORE][FOLLOWUP]` on master branch.

@dongjoon-hyun 
I did not see this comment before creating another [JIRA](https://issues.apache.org/jira/projects/SPARK/issues/SPARK-31478?filter=addedrecently). :( I am extremely sorry.
Please review this [PR](https://github.com/apache/spark/pull/28254)

**Comment by iRakson** [comment]
retest this please

**Comment by iRakson** [comment]
retest this please

**Comment by iRakson** [comment]
retest this please

**Comment by iRakson** [comment]
@dongjoon-hyun @vanzin  I have tested this a couple of times, older approach of adding shutdownhook is working fine. Last failure is unrelated to this. Also about the other approach, I think Vanzin's comment is valid one. Covering all the executor exit scenarios can be difficult. This seems a better fix to our problem.

**Comment by iRakson** [comment]
cc @srowen

**Comment by iRakson** [comment]
@dongjoon-hyun @vanzin Can we get this in 2.4 ?
I think now this is fine. It should not break the code. 
I have already tested this multiple times.

**Comment by dongjoon-hyun** [comment]
Hi, @iRakson . So, this is your final decision and are you going to close #28254 ?
This PR looks like to be reverted into the original patch. In that case, we don't need #28254 , do we?

**Comment by iRakson** [comment]
> Hi, @iRakson . So, this is your final decision and are you going to close #28254 ?
> This PR looks like to be reverted into the original patch. In that case, we don't need #28254 , do we?

Yeah, we don't need #28254 .

**Comment by iRakson** [comment]
#28254 has been closed.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @iRakson and @vanzin .
Merged to branch-2.4.

**Comment by dongjoon-hyun** [comment]
Unfortunately, this seems to break all `branch-2.4` Jenkins jobs again.
- https://amplab.cs.berkeley.edu/jenkins/view/Spark%20QA%20Test%20(Dashboard)/job/spark-branch-2.4-test-maven-hadoop-2.6/909/ (Failed)
- https://amplab.cs.berkeley.edu/jenkins/view/Spark%20QA%20Test%20(Dashboard)/job/spark-branch-2.4-test-maven-hadoop-2.7/912/ (Still running with UT failures)
- https://amplab.cs.berkeley.edu/jenkins/view/Spark%20QA%20Test%20(Dashboard)/job/spark-branch-2.4-test-sbt-hadoop-2.6/921/ (Failed)
- https://amplab.cs.berkeley.edu/jenkins/view/Spark%20QA%20Test%20(Dashboard)/job/spark-branch-2.4-test-sbt-hadoop-2.7/923/ (Failed)

 I'm still monitoring the Apache Spark Jenkins farm.

**Comment by dongjoon-hyun** [comment]
The situation is the same. There are OOM errors.
```
java.lang.OutOfMemoryError: OOM while handling another exception
	at org.apache.spark.executor.FetchFailureHidingRDD.compute(ExecutorSuite.scala:377)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:310)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:123)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$11.apply(Executor.scala:416)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:422)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
20/06/14 16:21:15.737 ScalaTest-main-running-ExecutorSuite INFO ExecutorSuite: 
```

**Comment by dongjoon-hyun** [comment]
Sorry again, @iRakson . I fully understand you spent lots of time to make this contribution and the failed test cases passed individually and locally. However, we cannot keep this patch in `branch-2.4` because this will hide all the other failures.

I admit that this is my bad because I reviewed and merged the same PR twice and reverted. With two tries, we proved that the original patch has some issue with `branch-2.4` definitely. Instead of putting more efforts on this, shall we move on to use new Apache Spark 3.0.0 since we have 3.0.0 release now? Technically, the original bug is a behavior since Apache Spark 2.4.0.

For now, I'll revert this commit to recover `branch-2.4`. The hang situation looks worse than the other failures.

**Comment by iRakson** [comment]
@dongjoon-hyun Its behaviour is pretty confusing. But yeah, if this is breaking branch again then we should not keep it. Yes, this patch failed twice so we must move on.

Thank you for actively monitoring this patch. :) :)

**Comment by attilapiros** [comment]
I know why. Here is the reason and the fix: https://github.com/apache/spark/pull/32748

**Pull request closed without merging**
