### PR TITLE
[SPARK-6028][Core]Remerge #6457: new RPC implemetation and also pick #8905

### PR DESCRIPTION
**Pull request by zsxwing**
This PR just reverted https://github.com/apache/spark/commit/02144d6745ec0a6d8877d969feb82139bd22437f to remerge #6457 and also included the commits in #8905.

### CODE REVIEW

**Comment by zsxwing** [comment]
Looks like a red flag:
```
Test Result (1 failure / +1)
org.apache.spark.rpc.netty.NettyRpcEnvSuite.self: call in onStop
```
I will investigate it.

**Comment by zsxwing** [comment]
retest this please

**Comment by vanzin** [comment]
I looked just at the recent patches, assuming the others just contain the code that had already been reviewed. LGTM pending tests.

**Comment by zsxwing** [comment]
retest this please

**Comment by rxin** [comment]
I've merged this.

**Pull request closed without merging**
