### PR TITLE
[SPARK-12610][SQL] Left Anti Join

### PR DESCRIPTION
**Pull request by hvanhovell**
### What changes were proposed in this pull request?

This PR adds support for `LEFT ANTI JOIN` to Spark SQL. A `LEFT ANTI JOIN` is the exact opposite of a `LEFT SEMI JOIN` and can be used to identify rows in one dataset that are not in another dataset. Note that `nulls` on the left side of the join cannot match a row on the right hand side of the join; the result is that left anti join will always select a row with a `null` in one or more of its keys.

We currently add support for the following SQL join syntax:

```
SELECT   *
FROM      tbl1 A
          LEFT ANTI JOIN tbl2 B
           ON A.Id = B.Id
```

Or using a dataframe:

```
tbl1.as("a").join(tbl2.as("b"), $"a.id" === $"b.id", "left_anti)
```

This PR provides serves as the basis for implementing `NOT EXISTS` and `NOT IN (...)` correlated sub-queries. It would also serve as good basis for implementing an more efficient `EXCEPT` operator.

The PR has been (losely) based on PR's by both @davies (https://github.com/apache/spark/pull/10706) and @chenghao-intel (https://github.com/apache/spark/pull/10563); credit should be given where credit is due.

This PR adds supports for `LEFT ANTI JOIN` to `BroadcastHashJoin` (including codegeneration), `ShuffledHashJoin` and `BroadcastNestedLoopJoin`. 
### How was this patch tested?

Added tests to `JoinSuite` and ported `ExistenceJoinSuite` from https://github.com/apache/spark/pull/10563.

cc @davies @chenghao-intel @rxin

### CODE REVIEW

**Comment by davies** [comment]
LGTM, pending tests.

**Comment by rxin** [comment]
Merging in master.

**Comment by gatorsmile** [comment]
@hvanhovell It sounds like something is wrong? 
```scala
  test("left anti join") {
    val df = Seq(1, 3).toDF("int")
    val df2 = Seq(1, 5).toDF("int2")

    checkAnswer(
      df.as("a").join(df2.as("b"), $"a.int" === $"b.int2", "left_anti"),
      Row(3) :: Nil)
  }
```

**Comment by hvanhovell** [comment]
Yeah it is broken for the BroadcastHashJoin unique key case :(...: https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/execution/joins/BroadcastHashJoinExec.scala#L358-L373

I am gonna open a JIRA and create a PR today.

**Pull request closed without merging**
