### PR TITLE
[SPARK-46324][SQL][PYTHON] Fix the output name of pyspark.sql.functions.user and session_user

### PR DESCRIPTION
**Pull request by HyukjinKwon**
### What changes were proposed in this pull request?

This PR proposes to fix `user()` and `session_user()` to have the same names in its output name.

### Why are the changes needed?

To show the correct name of the functions being used.

### Does this PR introduce _any_ user-facing change?

Yes.

```scala
spark.range(1).select(user(), session_user()).show()
```

Before:

```
+--------------+--------------+
|current_user()|current_user()|
+--------------+--------------+
|  hyukjin.kwon|  hyukjin.kwon|
+--------------+--------------+
```

After:

```
+--------------+--------------+
|        user()|session_user()|
+--------------+--------------+
|  hyukjin.kwon|  hyukjin.kwon|
+--------------+--------------+
```

### How was this patch tested?

Manually tested, and unittests were added.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Review by zhengruifeng — APPROVED** [review]

**Comment by zhengruifeng** [comment]
LGTM

**Comment by dongjoon-hyun** [comment]
Could you re-trigger the failed pipelines once more?

**Comment by dongjoon-hyun** [comment]
Merged to master.

**Comment by HyukjinKwon** [comment]
Thank you!

**Pull request closed without merging**
