### PR TITLE
[SPARK-34261][SQL] Avoid side effect if create exists temporary function

### PR DESCRIPTION
**Pull request by ulysses-you**
### What changes were proposed in this pull request?

Add function exists check before load resource.

### Why are the changes needed?

We should not add jar into classpath if the create temporary function is already exists.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Add test.

### CODE REVIEW

**Review by srowen — COMMENTED** [review]
It seems fine to me if this doesn't change behavior, just fails earlier.

**Comment by ulysses-you** [comment]
thanks @srowen , also cc @maropu @cloud-fan

**Review by maropu — APPROVED** [review]

**Comment by maropu** [comment]
Thanks! Merged to master.

**Comment by ulysses-you** [comment]
thanks for merging !

**Pull request closed without merging**
