### PR TITLE
[SPARK-11332] [ML] Refactored to use ml.feature.Instance instead of WeightedLeastSquare.Instance

### PR DESCRIPTION
**Pull request by nakul02**
WeightedLeastSquares now uses the common Instance class in ml.feature instead of a private one.

### CODE REVIEW

**Comment by dbtsai** [comment]
Jenkins, test this please.

**Comment by holdenk** [comment]
@nakul02 : You probably want to copy the JIRA description over (or write something descriptive) in the PRs description.

**Comment by holdenk** [comment]
This looks good to me. What are your thoughts @dbtsai ?

**Comment by dbtsai** [comment]
Thanks. Merged into master.

**Pull request closed without merging**
