### PR TITLE
[SPARK-9236][Core] Make defaultPartitioner not reuse a parent RDD's partitioner if it has 0 partitions

### PR DESCRIPTION
**Pull request by huitseeker**
See also comments on https://issues.apache.org/jira/browse/SPARK-9236

### CODE REVIEW

**Comment by srowen** [comment]
Seems pretty reasonable to me. CC @mateiz who might have been the last person to actually touch or write that bit of code.

**Comment by mateiz** [comment]
Looks good to me too.

**Comment by huitseeker** [comment]
Cool ! I've corrected the Scala style errors, so all that's left is to kick a new build.

**Comment by huitseeker** [comment]
The test failure seems unrelated. Is the test known to be flaky ?
```
[info] - Naive Bayes Multinomial *** FAILED *** (128 milliseconds)
[info]   closeFit(scala.math.`package`.exp(thetaData.apply(i._2).apply(j)), scala.math.`package`.exp(model.theta.apply(i._1).apply(j)), 0.05) was false (NaiveBayesSuite.scala:115)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:500)
[info]   at org.scalatest.FunSuite.newAssertionFailedException(FunSuite.scala:1555)
[info]   at org.scalatest.Assertions$AssertionsHelper.macroAssert(Assertions.scala:466)
[info]   at org.apache.spark.mllib.classification.NaiveBayesSuite$$anonfun$validateModelFit$2$$anonfun$apply$2.apply$mcVI$sp(NaiveBayesSuite.scala:115)
[info]   at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:141)
[info]   at org.apache.spark.mllib.classification.NaiveBayesSuite$$anonfun$validateModelFit$2.apply(NaiveBayesSuite.scala:114)
[info]   at org.apache.spark.mllib.classification.NaiveBayesSuite$$anonfun$validateModelFit$2.apply(NaiveBayesSuite.scala:113)
[info]   at scala.collection.Iterator$class.foreach(Iterator.scala:727)
[info]   at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
[info]   at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
[info]   at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[info]   at org.apache.spark.mllib.classification.NaiveBayesSuite.validateModelFit(NaiveBayesSuite.scala:113)
[info]   at org.apache.spark.mllib.classification.NaiveBayesSuite$$anonfun$7.apply$mcV$sp(NaiveBayesSuite.scala:147)
[info]   at org.apache.spark.mllib.classification.NaiveBayesSuite$$anonfun$7.apply(NaiveBayesSuite.scala:133)
[info]   at org.apache.spark.mllib.classification.NaiveBayesSuite$$anonfun$7.apply(NaiveBayesSuite.scala:133)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
```

**Pull request closed without merging**
