### PR TITLE
SPARK-5239 [CORE] JdbcRDD throws "java.lang.AbstractMethodError: oracle.jdbc.driver.xxxxxx.isClosed()Z"

### PR DESCRIPTION
**Pull request by srowen**
This is a completion of https://github.com/apache/spark/pull/4033 which was withdrawn for some reason.

### CODE REVIEW

**Comment by srowen** [comment]
Jenkins, retest this please.

**Comment by marmbrus** [comment]
Hey @srowen, we are working on a fix for the failing thrift server tests. /cc @liancheng

**Comment by srowen** [comment]
OK phew, good to know it's probably not this change.

**Comment by marmbrus** [comment]
test this please

**Comment by liancheng** [comment]
Yeah, the Thrift server test failure has been fixed by #4484 and #4499.

**Pull request closed without merging**
