### PR TITLE
[SPARK-36576][SS] Improve range split calculation for Kafka Source minPartitions option

### PR DESCRIPTION
**Pull request by noslowerdna**
### What changes were proposed in this pull request?

Proposing that the `KafkaOffsetRangeCalculator`'s range calculation logic be modified to exclude small (i.e. un-split) partitions from the overall proportional distribution math, in order to more reasonably divide the large partitions when they are accompanied by many small partitions, and to provide optimal behavior for cases where a `minPartitions` value is deliberately computed based on the volume of data being read.

### Why are the changes needed?

While the [documentation](https://spark.apache.org/docs/latest/structured-streaming-kafka-integration.html) does contain a clear disclaimer,

> Please note that this configuration is like a hint: the number of Spark tasks will be **approximately** `minPartitions`. It can be less or more depending on rounding errors or Kafka partitions that didn't receive any new data.

there are cases where the calculated Kafka partition range splits can differ greatly from expectations. For evenly distributed data and most `minPartitions` values this would not be a major or commonly encountered concern. However when the distribution of data across partitions is very heavily skewed, somewhat surprising range split calculations can result.

For example, given the following input data:

- 1 partition containing 10,000 messages
- 1,000 partitions each containing 1 message

Spark processing code loading from this collection of 1,001 partitions may decide that it would like each task to read no more than 1,000 messages. Consequently, it could specify a `minPartitions` value of 1,010 — expecting the single large partition to be split into 10 equal chunks, along with the 1,000 small partitions each having their own task. That is far from what actually occurs. The `KafkaOffsetRangeCalculator` algorithm ends up splitting the large partition into 918 chunks of 10 or 11 messages, two orders of magnitude from the desired maximum message count per task and nearly double the number of Spark tasks hinted in the configuration.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Existing unit tests and added new unit tests

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
ok to test

**Comment by HeartSaVioR** [comment]
@noslowerdna Thanks for the contribution!
We leverage Github Action in individual's fork to run test in Github. Could you please follow the instruction below?
https://spark.apache.org/developer-tools.html#github-workflow-tests

**Comment by HeartSaVioR** [comment]
The new calculation looks better to me, but let's have double confirmation.
cc. @tdas @zsxwing @viirya @gaborgsomogyi @xuanyuanking

**Review by viirya — COMMENTED** [review]
Thanks for this work. Looks promising. I will look at the details tomorrow.

**Comment by noslowerdna** [comment]
@HeartSaVioR Thank you for the review. I think the documentation at https://spark.apache.org/developer-tools.html#github-workflow-tests needs to be slightly updated for this recent change: https://github.com/apache/spark/commit/2974b70d1efd4b1c5cfe7e2467766f0a9a1fec82?  I don't see a manual "Run workflow" option for the Build and test action, like the Benchmark action does have, as Benchmark still has a [workflow_dispatch](https://github.com/apache/spark/blob/master/.github/workflows/benchmark.yml#L4) event trigger. Anyway after enabling the workflow for my fork, I am seeing a Build and test workflow run automatically queued now for new commits so it looks like the tests should be running soon.

**Review by viirya — COMMENTED** [review]
I'm okay with the change. I will leave it to @HeartSaVioR.

**Review by HeartSaVioR — APPROVED** [review]
+1

I'll run the build again and merge once the build passes.

**Comment by HeartSaVioR** [comment]
retest this, please

**Comment by HeartSaVioR** [comment]
Thanks @noslowerdna for the contribution! I merged into master.

**Comment by xuanyuanking** [comment]
Nice improvement, thanks @noslowerdna!

**Pull request closed without merging**
