### PR TITLE
[SPARK-8510] [CORE] [PYSPARK] NumPy arrays and matrices as values in sequence files

### PR DESCRIPTION
**Pull request by paberline**
Using the DoubleArrayWritable example, I have added support for storing NumPy arrays and matrices as value elements of Sequence Files.

Each value element is a discrete matrix or array. This is useful where you have many matrices that you don't want to join into a single Spark Data Frame to store in a Parquet file.

There seems to be demand for this functionality:

http://mail-archives.us.apache.org/mod_mbox/spark-user/201506.mbox/%3CCAJQK-mg1PUCc_hkV=Q3n-01iOQ_pkWE1g-c39XiMCo3KhqngQg@mail.gmail.com%3E

### CODE REVIEW

**Comment by paberline** [comment]
https://issues.apache.org/jira/browse/SPARK-8510

**Comment by paberline** [comment]
https://issues.apache.org/jira/browse/SPARK-8510

**Comment by JoshRosen** [comment]
Mind copying some of the description into the PR description here so that it becomes part of the commit message? Having a description here makes things easier for us to review.

Also, do you mind re-formatting your PR title to match the convention used by our other PRs?

**Comment by paberline** [comment]
Using the DoubleArrayWritable example, I have added support for storing NumPy double arrays and matrices as arrays of doubles and nested arrays of doubles as value elements of Sequence Files.

Each value element is a discrete matrix or array. This is useful where you have many matrices that you don't want to join into a single Spark Data Frame to store in a Parquet file.

Pandas DataFrames can be easily converted to and from NumPy matrices, so I've also added the ability to store the schema-less data from DataFrames and Series that contain double data.

There seems to be demand for this functionality:

http://mail-archives.us.apache.org/mod_mbox/spark-user/201506.mbox/%3CCAJQK-mg1PUCc_hkV=Q3n-01iOQ_pkWE1g-c39XiMCo3KhqngQg@mail.gmail.com%3E

**Comment by JoshRosen** [comment]
Oh, I meant as the description here:

image

**Comment by paberline** [comment]
I've received a suggestion this PR could be improved by using np.save(z) to serialize the data and also preserve metadata about the NumPy array. I'm going to incorporate this suggestion. Please hold off reviewing this PR until I push commits for this.

**Comment by sujkh85** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

sujkh@naver.com 님께 보내신 메일 <Re: [spark] [SPARK-8510] [CORE] [PYSPARK] NumPy arrays and matrices as values in sequence files (#6995)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by paberline** [comment]
I want to work on this some more to incorporate the improvement suggestion I have received.

**Pull request closed without merging**
