### PR TITLE
[WIP][SPARK-40083][SHUFFLE] Add shuffle index cache timebased expire policy

### PR DESCRIPTION
**Pull request by wangshengjie123**
### What changes were proposed in this pull request?

add shuffle index cache time-based expire policy

### Why are the changes needed?

Clean up unused cache save memory.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

UT

### CODE REVIEW

**Review by JoshRosen — COMMENTED** [review]
Do you have an example of a real-world situation where old cache entries caused performance or memory usage problems? There's already a cache size limit, controlled by `spark.shuffle.service.index.cache.size`. If you have a cluster that is regularly / continuously running Spark applications, wouldn't the cache quickly hit its size limit and stay there? Shouldn't the shuffle server / YARN AM be configured so that it performs adequately even if the cache hits is maximum size?

**Comment by wangshengjie123** [comment]
> 

Thanks @JoshRosen  for review this pr. 

We have the the situation in our production environment, we set `spark.shuffle.service.index.cache.size` to 256m, we found it need about 2 day to reach the cache limit size and old cache those apps already finished still in old gen memory.  

As you suggested, we adjusted NM memory size to solve the memory problem, also we could adjust cache limit size.

But sometimes we need to face the face business growth and adjust NM memory is an expensive operation, so this pr just a optimization for cache， i am not sure this is a common case but useful for our situation. 

Thanks again @JoshRosen  for your reply.

**Comment by JoshRosen** [comment]
If the primary intent is to clean up cache entries associated with finished Spark applications, is there a way that we could do this more directly? 

In `ExternalShuffleBlockResolver.applicationRemoved` it looks like we have some logic that can start an asynchronous background task to clean up the shuffle files. Maybe we could somehow remove the cache entries in a similar manner (e.g. either by doing this during the file deletion, taking advantage of the fact that the cache keys are filenames, or by iterating over the cache's keys and deleting files in the deleted application's directory (we'd have to check the iteration semantic to make sure this is safe)).

Doing this cleanup at application-removal time would avoid the need to have a time-based config (which could be hard to tune appropriately).

**Comment by mridulm** [comment]
Agree, if this is for completed applications, we should be handling it in `applicationRemoved`
There is cleanup there already - looks like the cache is not getting evicted from.

The same applies to `indexCache` in `RemoteBlockPushResolver` also. +CC @otterc

**Comment by wangshengjie123** [comment]
> Agree with @JoshRosen, if this is for completed applications, we should be handling it in `applicationRemoved` There is cleanup there already - looks like the cache is not getting evicted from.
> 
> The same applies to `indexCache` in `RemoteBlockPushResolver` also. +CC @otterc

Yeah, can`t agree more, let me do this，thanks @JoshRosen @mridulm 

Change pr to WIP

**Pull request closed without merging**
