### PR TITLE
[SPARK-26081][SQL][FOLLOW-UP] Use foreach instead of misuse of map (for Unit)

### PR DESCRIPTION
**Pull request by HyukjinKwon**
## What changes were proposed in this pull request?

This PR proposes to use foreach instead of misuse of map (for Unit). This could cause some weird errors potentially and it's not a good practice anyway. See also SPARK-16694

## How was this patch tested?

N/A

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by MaxGekk** [comment]
Just wondering to not misuse it in the future.

> This could cause some weird errors potentially...

What kind of problems could it cause in the case of `Option`? Additional wrapping by `Some`? ... but `close()` is called not so often. 

 > it's not a good practice anyway ...

Is it good practice to depend on called function? If `close()` of `UnivocityGenerator` will be changed in the future and will return `Boolean` instead of `Unit`, will you change `foreach` back to `map`?

**Comment by HyukjinKwon** [comment]
I don't think currently it causes actual problem for now .. simply using `foreach` is preferred over `map` when the output from `map` is not used.

Good practice is to call `map` only when the return is explicitly used. If `close()` returns `Boolean` in the future, it turn return `Boolean` explicitly. ...

**Comment by HyukjinKwon** [comment]
I mean, it's not like case by case. This pattern can cause an issue as described in SPARK-16694 and it's better to avoid it in general whenever `map`'s output is not used.

**Review by srowen — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Thanks, merged to master.

**Pull request closed without merging**
