### PR TITLE
[SPARK-8731] Beeline doesn't work with -e option when started in background

### PR DESCRIPTION
**Pull request by zhouyifan279**
### What changes were proposed in this pull request?
Append jline option "-Djline.terminal=jline.UnsupportedTerminal" to  enable the Beeline process to run in background.

### Why are the changes needed?
Currently, if we execute spark Beeline in background, the Beeline process stops immediately.
image

### Does this PR introduce _any_ user-facing change?
User will be able to execute Spark Beeline in background. 

### How was this patch tested?

1. Start Spark ThriftServer
2. Execute command `./bin/beeline -u "jdbc:hive2://localhost:10000" -e "select 1;" &`
3. Verify Beeline process output in console:
image

### Note

Beeline works fine on Windows when backgrounded:
image

### CODE REVIEW

**Comment by zhouyifan279** [comment]
cc @yaooqinn

**Review by yaooqinn — APPROVED** [review]
LGTM

**Comment by zhouyifan279** [comment]
Beeline works fine on Windows when backgrounded:
image

**Review by itholic — APPROVED** [review]
LGTM2

**Comment by yaooqinn** [comment]
thanks, merged to master/3.3/3.2

**Comment by wangyum** [comment]
@zhouyifan279 Could you provide your apache jira id? We need to set the assignee:
image

**Pull request closed without merging**
