### PR TITLE
[SPARK-14730][ML] Expose ColumnPruner as feature transformer

### PR DESCRIPTION
**Pull request by BenFradet**
## What changes were proposed in this pull request?

The column pruner transformer present in RFormula was made public
## How was this patch tested?

Unit tests were written

### CODE REVIEW

**Comment by BenFradet** [comment]
@yanboliang 
Could you please take a look at this when you have the chance? Thanks.

**Comment by BenFradet** [comment]
@yanboliang should I close this?

**Comment by manugarri** [comment]
Any word on when is this going to be available in PySpark?

**Comment by BenFradet** [comment]
@manugarri I don't think there was much interest in this PR.

Would you care to weigh in @jkbradley @yanboliang?

**Comment by davireis** [comment]
Just weighting in the motivations: 

https://0xdata.atlassian.net/browse/SW-224
http://apache-spark-developers-list.1001551.n3.nabble.com/spark-ml-Why-is-private-class-ColumnPruner-td16863.html

And my own use case: I have a dataframe with two textual columns on which I want to run apply a LDAModel. This model was trained in a different dataset, and although I can reset its input (setFeatureCol), I cannot reset its output (no setTopicDistributionCol in the trained model). Since both applications of LDAModel will output in the same column name, my pipeline barfs. If I had ColumnPruner, I could just combine it with SQLTransformer to rename the output column. Alternatively LDAModel itself could be fixed, or I could build a WithColumnRenamedTransformer. But ColumnPruner would suffice as primitive for many use cases I believe, since most of the other simple schema manipulations can be achieved with SQLTransformer. Maybe I am missing some already in-place alternatives, but from what I understand, I can only achieve what I want now with a custom transformer.

**Comment by manugarri** [comment]
@davireis that is a similar use case than mine.

**Pull request closed without merging**
