### PR TITLE
[MINOR][TEST][SQL] Make in-limit.sql more robust

### PR DESCRIPTION
**Pull request by cloud-fan**
### What changes were proposed in this pull request?

For queries like `t1d in (SELECT t2d FROM  t2 ORDER  BY t2c LIMIT 2)`, the result can be non-deterministic as the result of the subquery may output different results (it's not sorted by `t2d` and it has shuffle).

This PR makes the test more robust by sorting the output column.

### Why are the changes needed?

avoid flaky test

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

N/A

### CODE REVIEW

**Comment by cloud-fan** [comment]
cc @HyukjinKwon @maropu

**Review by HyukjinKwon — APPROVED** [review]
LGTM

**Review by maropu — APPROVED** [review]
LGTM, too.

**Comment by HyukjinKwon** [comment]
The tests this PR fix passed.

Merged to master, branch-3.0 and branch-2.4.

**Pull request closed without merging**
