### PR TITLE
[SPARK-39119][BUILD] Upgrade Hadoop to 3.3.3

### PR DESCRIPTION
**Pull request by sunchao**
### What changes were proposed in this pull request?

This PR aims to upgrade to Hadoop 3.3.3, which was just announced today.

### Why are the changes needed?

Hadoop 3.3.3 has many bug fixes as well as CVE fixes. Please check [release notes](https://hadoop.apache.org/docs/r3.3.3/hadoop-project-dist/hadoop-common/release/3.3.3/RELEASENOTES.3.3.3.html) and [change log](https://hadoop.apache.org/docs/r3.3.3/hadoop-project-dist/hadoop-common/release/3.3.3/CHANGELOG.3.3.3.html).

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the CIs.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Yay! Thank you, @sunchao !

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
Hi, @sunchao . Please don't use the latest Maven.

It has a bug which ignores the dependency in `profile`. So, this PR screwed `hadoop-2` dependency.

**Comment by dongjoon-hyun** [comment]
cc @MaxGekk

**Comment by MaxGekk** [comment]
> cc @MaxGekk

I just hope you are not going to backport this to 3.3 ;-)

**Comment by dongjoon-hyun** [comment]
It's great to see the official one!

**Comment by dongjoon-hyun** [comment]
Shall we convert to a normal PR by removing `[WIP]` in the title and convert to `Ready for review` status?

**Comment by sunchao** [comment]
Sure @dongjoon-hyun . Updated.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you so much, @sunchao .
Merged to master for Apache Spark 3.4.

**Comment by sunchao** [comment]
Thanks @dongjoon-hyun !

**Pull request closed without merging**
