### PR TITLE
[SPARK-49446][BUILD] Upgrade jetty to 11.0.23

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr aims to upgrade jetty from 11.0.21 to 11.0.23.

### Why are the changes needed?
The new version brings an optimization elated to `HttpConnection`
- https://github.com/jetty/jetty.project/pull/12156: Improvements to HttpConnection when reading 0 bytes

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass GitHub Actions

### Was this patch authored or co-authored using generative AI tooling?
No

### CODE REVIEW

**Comment by LuciferYang** [comment]
Test first

**Review by dongjoon-hyun — COMMENTED** [review]
Looks working. :)

**Comment by LuciferYang** [comment]
Updated the PR description. @dongjoon-hyun  Could you please help review it  if you have time? Thanks ~

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @LuciferYang .

**Comment by LuciferYang** [comment]
Thanks @dongjoon-hyun ~

**Pull request closed without merging**
