### PR TITLE
[SPARK-23529][K8s] Support mounting hostPath volumes for executors

### PR DESCRIPTION
**Pull request by madanadit**
## What changes were proposed in this pull request?

This PR introduces a new config `spark.kubernetes.executor.volumes` taking a values of the form  `hostPath:containerPath[:ro|rw][,...]`; where  `hostPath` is the path for the executor pod volume, `containerPath` is the mount path and `ro` is read-only mode.

The use case is to enable short-circuit writes to distributed storage on k8s. The Alluxio File System uses domain sockets to enable short-circuit writes from the client to worker memory when co-located on the same host machine. A directory, lets say /tmp/domain on the host, is mounted on the Alluxio worker container as well as the Alluxio client ( = Spark executor) container. The worker creates a domain socket /tmp/domain/d and if the client container mounts the same directory, it can write directly to the Alluxio worker w/o passing through network stack. The end result is faster data access when data is local.

## How was this patch tested?

Manual testing on a k8s v1.8 cluster. Unit tests added to `ExecutorPodFactorySuite`.

### CODE REVIEW

**Comment by madanadit** [comment]
@foxish Can you take a look?. Thanks!

**Comment by foxish** [comment]
ok to test

**Comment by madanadit** [comment]
@foxish The failure seems to be because of `SparkRemoteFileTest` missing from branch-2.3 (only present in master branch). Which branch do you recommend targeting this PR towards?

**Comment by felixcheung** [comment]
hi there - you should always open PR on master. we could backport to "older releases" as needed, or ask you to open a separate PR that is based on branch-2.3 (like this one you have now)

**Comment by madanadit** [comment]
Thanks  @felixcheung!. I've re targeted to master in this [PR](https://github.com/apache/spark/pull/21032). Closing this one.

**Pull request closed without merging**
