### PR TITLE
[SPARK-27214]Upgrading locality level when task set is starving

### PR DESCRIPTION
**Pull request by liupc**
## What changes were proposed in this pull request?

Currently, Spark locality wait mechanism is not friendly for large job, when number of tasks is large（e.g. 10000+）and with a large number of executors(e.g. 2000), executors may be launched on some nodes  where the locality is not the best(not the same nodes hold HDFS blocks). There are cases when `TaskSetManager.lastLaunchTime` is refreshed due to task finished within `spark.locality.wait` and re-launch new tasks, but due to there are only few of `PROCESS_LOCAL` executors, the launch rate is not fast enough to schedule all pending tasks soon, so that locality level could not be upgraded in time and lots of pending tasks will wait a long time. 

In this case, when `spark.dynamicAllocation.enabled=true`, then lots of executors may be removed by Driver due to become idle and finally slow down the job.

We encountered this issue in our production spark cluster, it caused lots of resources wasting and slowed down user's application.

This PR will optimize this by following formula:

Suppose numPendingTasks=10000, localityExecutionGainFactor=0.1, probabilityOfNextLocalitySchedule=0.5

```
maxTolerableStarvingTime = numTasksCanRun * medianOfTaskExecutionTime * localityExecutionGainFactor * probabilityOfNextLocalitySchedule

totalStarvingTime = sum(starvingTimeByTasks)

if (totalStarvingTime > maxTolerableStarvingTime)

{  upgrading locality level... }
```

## How was this patch tested?

Exist UT & added UT

Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Comment by liupc** [comment]
cc @srowen @vanzin @squito

**Comment by squito** [comment]
I think this is actually a pretty big change in behavior, and at the very least would need to go behind a conf.  I had a dicussion with Kay Ousterhout about this type of situation and delay scheduling (need to search for the jira ...) -- I had not proposed this solution, but something along these lines, and she said that to some extent, this was the intended behavior for when there were multiple active jobs in a "job server" style deployment.  Then it is OK for one job to end up waiting a while, to keep resources free for another job which might be able to use those resources with better locality.

In the meanwhile, I've actually often advised users on large clusters to turn the locality wait down to 0 (the odds of getting locality goes down on larger clusters anyway).  Have you considered that?  Note that spark still tries to schedule for locality even with the wait = 0; it just doesn't *wait* until it gets the desired locality.

While your proposal is reasonable, its also really hard to say whether its a good idea in general.  One big change that you're not calling out -- it *always* turns off delay-scheduling until some task has finished.  That could be a very big change for some use cases.

**Comment by liupc** [comment]
@squito  Thank you for your reply. I think this PR is useful in batch processing when a single job is submitted. 

> to some extent, this was the intended behavior for when there were multiple active jobs in a "job server" style deployment. Then it is OK for one job to end up waiting a while, to keep resources free for another job which might be able to use those resources with better locality.

I don't agree with this, because it's non-deterministic, you can hardly say the delay scheduling brings gains or pains. What's more, I think this multi-job cases in SparkSQL thriftserver, these resources allocation which considering locality should be done in the Scheduler like FIFOScheduler/FairScheduler etc. And in multi-jobs cases with FIFO scheduler, if we let one job to end up waiting a long time while let later job running more resources, it seems breaks what user has expected: The first comes should be executed fast and finished first.

> In the meanwhile, I've actually often advised users on large clusters to turn the locality wait down to 0 (the odds of getting locality goes down on larger clusters anyway). Have you considered that? Note that spark still tries to schedule for locality even with the wait = 0; it just doesn't wait until it gets the desired locality.

Yes, set `spark.locality.wait=0` works in this case, and I just use this conf to temporarily fix this issue before this solution in batch mode. But I think set to zero is a little bit aggressive, and it's not easy for users to decide how large a cluster is a large cluster. So it's not bad to add this option for batch processing.

> One big change that you're not calling out -- it always turns off delay-scheduling until some task has finished. That could be a very big change for some use cases.

Yes, this change is big, it may breaks the delay scheduling, so I agree with your suggestion to add an option to enable it, or we can just enable it when the `SchedulingMode` is `FIFO`, this is mostly used in Batch processing.

**Comment by squito** [comment]
I find the prior issue is https://issues.apache.org/jira/browse/SPARK-18886, there is a long discussion there.

**Comment by tgravescs** [comment]
I also hit this same issue and the work around was to set the locality wait to 0 which works fine, but not really ideal if you want locality to work.  So I think it would be nice to get it fixed.  One thing is that since networks have increased in speed the benefit of exact locality isn't as critical for many jobs.  But for certain jobs I can see that you want it, but only if the task runtime  is long enough.  I need to look more at the background discussions in the jira @squito referenced though.

**Comment by liupc** [comment]
Yes, It's better to be fixed if we can find out a graceful way. Actually, as I mentioned in the PR description, if enabled dynamic allocaiton, the idle of the executors may cause executors to be removed and not reallocate new executors until the `numExecutorsTarget` is reset. This is really bad and even can not meet the point of `Letting other parallel TSM or job use resources with locality`

Ref:
https://github.com/apache/spark/blob/0bb716bac38488bc216fbda29ce54e93751e641b/core/src/main/scala/org/apache/spark/ExecutorAllocationManager.scala#L388


```
    // Do not request more executors if it would put our target over the upper bound
    if (numExecutorsTarget >= maxNumExecutors) {
      logDebug(s"Not adding executors because our current target total " +
        s"is already $numExecutorsTarget (limit $maxNumExecutors)")
      numExecutorsToAdd = 1
      return 0
    }


```

**Comment by tgravescs** [comment]
If that is the case we should separate that out and fix that bug as that really seems like a separate issue.   But I thought the removeExecutors code wouldn't remove idle executors if it would put it under the target number. see SPARK-21656. Which version of spark are you using?

**Comment by liupc** [comment]
@tgravescs ah..I'm using spark2.1, the issue seems to be fixed  on 2.2+ by the PR you given. 
Then, we can focus on the locality issue and maybe more discussion. If you got any good idea please let me know, Thank you!

**Comment by squito** [comment]
what's the latest here?  @liupc should this PR be closed for now while we consider the solution for the locality issues?

**Comment by liupc** [comment]
Yes, we can close this PR for now. Thank you @squito

**Pull request closed without merging**
