### PR TITLE
[SPARK-20842] [SQL] Upgrade to 1.2.2 for Hive Metastore Client 1.2 

### PR DESCRIPTION
**Pull request by gatorsmile**
### What changes were proposed in this pull request?
Hive 1.2.2 release is available. Below is the list of bugs fixed in 1.2.2

https://issues.apache.org/jira/secure/ReleaseNote.jspa?version=12332952&styleName=Text&projectId=12310843

### How was this patch tested?
N/A

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
+1, LGTM.

**Comment by gatorsmile** [comment]
cc @cloud-fan

**Review by dongjoon-hyun — APPROVED** [review]
Is it possible for us to have this for both master and branch-2.2?

**Comment by cloud-fan** [comment]
retest this please

**Comment by cloud-fan** [comment]
LGTM, merging to master!

**Pull request closed without merging**
