### PR TITLE
[SPARK-48852][CONNECT] Fix string trim function in connect

### PR DESCRIPTION
**Pull request by biruktesf-db**
### What changes were proposed in this pull request?

Changed the order of arguments passed in the connect client's trim function call to match [`sql/core/src/main/scala/org/apache/spark/sql/functions.scala`](https://github.com/apache/spark/blob/f2dd0b3338a6937bbfbea6cd5fffb2bf9992a1f3/sql/core/src/main/scala/org/apache/spark/sql/functions.scala#L4322)

### Why are the changes needed?

This change fixes a correctness bug in spark connect where a query to trim characters `s` from a column will be replaced by a substring of `s`.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Updated golden files for [`/connector/connect/client/jvm/src/test/scala/org/apache/spark/sql/PlanGenerationTestSuite.scala`](https://github.com/apache/spark/blob/f2dd0b3338a6937bbfbea6cd5fffb2bf9992a1f3/connector/connect/client/jvm/src/test/scala/org/apache/spark/sql/PlanGenerationTestSuite.scala#L1815) and added an additional test to verify correctness. 

### Was this patch authored or co-authored using generative AI tooling?

No

### CODE REVIEW

**Review by allisonwang-db — COMMENTED** [review]
Can we add some tests for this?

**Review by HyukjinKwon — APPROVED** [review]

**Review by zhengruifeng — APPROVED** [review]
Good catch

**Comment by zhengruifeng** [comment]
Just check that we don't have such bug in python side, because the parameter `trimString` is missing. I will send a PR to add it later.

**Comment by biruktesf-db** [comment]
> Just check that we don't have such bug in python side, because the parameter `trimString` is missing. I will send a PR to add it later.

We don't have this bug on the python side right now as we don't support `trim(column, trimString)` and `trim(column)` works as expected. I can check it after it's added or add it myself after this PR. Thanks!

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
