### PR TITLE
[SPARK-31732][TESTS] Disable some flaky tests temporarily

### PR DESCRIPTION
**Pull request by cloud-fan**
### What changes were proposed in this pull request?

It's quite annoying to be blocked by flaky tests in several PRs. This PR disables them. The tests come from 3 PRs I'm recently watching:
https://github.com/apache/spark/pull/28526
https://github.com/apache/spark/pull/28463
https://github.com/apache/spark/pull/28517

### Why are the changes needed?

To make PR builder more stable

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

N/A

### CODE REVIEW

**Comment by cloud-fan** [comment]
cc @dongjoon-hyun @HyukjinKwon @gatorsmile

**Comment by dongjoon-hyun** [comment]
Hi, @cloud-fan . So, you are targeting this PR only in `master/3.0`. Did I understand correctly?

**Comment by dongjoon-hyun** [comment]
Do you know how frequently it fail? In master Jenkins build, the following failures occur, too.
- org.apache.spark.scheduler.BarrierTaskContextSuite.global sync by barrier() call
- org.apache.spark.sql.kafka010.KafkaMicroBatchV1SourceSuite.subscribing topic by pattern with topic deletions

**Comment by dongjoon-hyun** [comment]
In another PR (https://github.com/apache/spark/pull/28509#issuecomment-629203078), `BarrierTaskContextSuite.support multiple barrier() call within a single task`.
```
org.apache.spark.scheduler.BarrierTaskContextSuite.support multiple barrier() call within a single task
sbt.ForkMain$ForkError: org.scalatest.exceptions.TestFailedException: 1031 was not less than or equal to 1000
	at org.scalatest.Assertions.newAssertionFailedException(Assertions.scala:530)
```
- https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/122655/testReport/org.apache.spark.scheduler/BarrierTaskContextSuite/support_multiple_barrier___call_within_a_single_task/

**Comment by HyukjinKwon** [comment]
@dongjoon-hyun, actually some of them are not related to the corrupt local repository. This was in  amp-jenkins-worker-03 
 https://amplab.cs.berkeley.edu/jenkins/job/NewSparkPullRequestBuilder/5029/.
Looks the corrupt repo was cleaned at amp-jenkins-worker-05 assuming the dependeny tests pass at https://amplab.cs.berkeley.edu/jenkins/job/NewSparkPullRequestBuilder/5039/ (?).

I am retriggering the builds for now. Let's disable them and run the RC if they are still frequently failed.

**Comment by cloud-fan** [comment]
@dongjoon-hyun I'll disable these tests as well, please let me know if you see more.

**Comment by dongjoon-hyun** [comment]
Thanks. @cloud-fan .  I'm +1 for disabling the above, too.

Yes, @HyukjinKwon . The above are really flaky tests. What I meant was `amp-jenkins-worker-05` failure was independent annoying stuff since there is no way to investigate more.

**Comment by HyukjinKwon** [comment]
retest this please

**Review by HyukjinKwon — APPROVED** [review]
LGTM

**Comment by HyukjinKwon** [comment]
retest this please

**Review by maropu — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you all.
Merged to master/3.0.

**Comment by dongjoon-hyun** [comment]
cc @rxin since he is a release manager of 3.0.0.
(Also, cc @gatorsmile )

**Pull request closed without merging**
