### PR TITLE
[SPARK-9886][CORE] Fix to use ShutdownHookManager in

### PR DESCRIPTION
**Pull request by naveenminchu**
ExternalBlockStore.scala

### CODE REVIEW

**Comment by srowen** [comment]
LGTM, but not sure how we missed this one. It makes me wonder if there's a particular reason for it. But I don't see a reason the current implementation would guarantee some behavior that's required.

**Comment by JoshRosen** [comment]
Hey, can we add a linter rule to ban uses of "Runtime.getRuntime.addShutdownHook", similar to our existing rule for "Class.forName", which recommends using our own utility function instead?

**Comment by naveenminchu** [comment]
Hi @JoshRosen, Are you suggesting to go ahead look over "Runtime.getRuntime.addShutdownHook" use and get rid of same

**Comment by JoshRosen** [comment]
@naveenminchu, yeah, I'm suggesting that we add a rule to `scalastyle-config.xml` (like https://github.com/apache/spark/blob/bc1ff9f4a41401599d3a87fb3c23a2078228a29b/scalastyle-config.xml#L160), add excludes to ignore the legitimate uses, then fix any violations that we find (see #7350 for an example of this)

I suppose the Scalastyle lint doesn't catch similar problems in Java code, but I say "let's not let perfect be the enemy of the good" here; it's better to have some checks vs. no checks.

**Comment by srowen** [comment]
The comment from @vanzin on the JIRA indicated he wasn't sure whether the other 2 usages were better left alone as they're used in particular stand-alone processes. But I suppose it doesn't really hurt to use the fancy wrapper in those cases too.

**Comment by andrewor14** [comment]
Merging into master 1.6. We can add the scalastyle check later.

**Comment by tedyu** [comment]
There're still 4 references to Runtime.getRuntime.addShutdownHook() in the code base.
Should they be replaced with ShutdownHookManager ?

**Comment by andrewor14** [comment]
I believe so, and we can also add a scalastyle check that Josh suggested

**Comment by tedyu** [comment]
Created #10325

**Comment by naveenminchu** [comment]
@tedyu Thanks for making those changes

**Pull request closed without merging**
