### PR TITLE
[SPARK-18849][ML][SPARKR][DOC] vignettes final check update

### PR DESCRIPTION
**Pull request by felixcheung**
## What changes were proposed in this pull request?

doc cleanup

## How was this patch tested?

~~vignettes is not building for me. I'm going to kick off a full clean build and try again and attach output here for review.~~
Output html here: https://felixcheung.github.io/sparkr-vignettes.html

### CODE REVIEW

**Comment by felixcheung** [comment]
rebased on #16284

**Comment by felixcheung** [comment]
@jkbradley @shivaram @mengxr @wangmiao1981

**Comment by shivaram** [comment]
LGTM. But I haven't been looking at the vignette PRs closely, so it might better if @mengxr took a loo k as well

**Comment by shivaram** [comment]
Merging this to master, branch-2.1 - to catch the next RC. @mengxr feel free to open a follow up if you find anything ?

**Comment by mengxr** [comment]
I would vote for some logical grouping (instead of alphabetical ordering) and keep the sections in the same order, but it is not very necessary.

**Pull request closed without merging**
