### PR TITLE
[SPARK-15973] [PYSPARK] Fix GroupedData Documentation

### PR DESCRIPTION
**Pull request by josh-howes**
_This contribution is my original work and that I license the work to the project under the project's open source license._
## What changes were proposed in this pull request?

Documentation updates to PySpark's GroupedData
## How was this patch tested?

Manual Tests

### CODE REVIEW

**Comment by MLnick** [comment]
ok to test

**Comment by josh-howes** [comment]
Hello, first commit here.  Trying to get started by tackling some "trival" tickets around documentation.  I'm at a loss about how my changes are causing the unit tests to fail in `types.py`.  Any help would be appreciated.

**Comment by vlad17** [comment]
The issue is that there are still some references to the old `GroupedData._jdf` attribute - if you click on the the Jenkins link you'll find where (but I pasted below too):
Error Message

```
'GroupedData' object has no attribute '_jdf'
Stacktrace

Traceback (most recent call last):
  File "/home/jenkins/workspace/SparkPullRequestBuilder/python/pyspark/sql/tests.py", line 682, in test_aggregator
    self.assertEqual([Row(**{"AVG(key#0)": 49.5})], g.mean().collect())
  File "/home/jenkins/workspace/SparkPullRequestBuilder/python/pyspark/sql/group.py", line 40, in _api
    jdf = getattr(self._jdf, name)(_to_seq(self.sql_ctx._sc, cols))
AttributeError: 'GroupedData' object has no attribute '_jdf'
```

**Comment by rxin** [comment]
Thanks - merging in master/2.0.

**Comment by rxin** [comment]
@josh-howes what's your jira id?

**Comment by josh-howes** [comment]
@rxin, I just created a ASF Jira Account.  I didn't have one previously.  Here's my info: full name is Josh Howes and username is (josh dot howes at gmail dot com).

**Pull request closed without merging**
