### PR TITLE
[SPARK-40663][SQL] Migrate execution errors onto error classes: _LEGACY_ERROR_TEMP_2076-2100

### PR DESCRIPTION
**Pull request by itholic**
### What changes were proposed in this pull request?

This PR proposes to migrate 25 execution errors onto temporary error classes with the prefix `_LEGACY_ERROR_TEMP_2076` to `_LEGACY_ERROR_TEMP_2100`.

The error classes are prefixed with `_LEGACY_ERROR_TEMP_` indicates the dev-facing error messages, and won't be exposed to end users.

### Why are the changes needed?

To speed-up the error class migration.

The migration on temporary error classes allow us to analyze the errors, so we can detect the most popular error classes.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

```
$ build/sbt "sql/testOnly org.apache.spark.sql.SQLQueryTestSuite"
$ build/sbt "test:testOnly *SQLQuerySuite"
```

### CODE REVIEW

**Comment by MaxGekk** [comment]
@itholic Could you resolve conflicts here, please.

**Comment by MaxGekk** [comment]
@itholic Please, fix the test failures:
```
[error] /home/runner/work/spark/spark/sql/catalyst/src/main/scala/org/apache/spark/sql/errors/QueryExecutionErrors.scala:1006:25: parameter 'messageParameters' is already specified at parameter position 2
[error] Note that 'errorSubClass' is not a parameter name of the invoked method.
[error]       messageParameters = Map("optionName" -> optionName))
[error]                         ^
[error] /home/runner/work/spark/spark/sql/catalyst/src/main/scala/org/apache/spark/sql/errors/QueryExecutionErrors.scala:1044:25: parameter 'messageParameters' is already specified at parameter position 2
[error] Note that 'errorSubClass' is not a parameter name of the invoked method.
[error]       messageParameters = Map.empty)
[error]                         ^
[error] two errors found
```

**Comment by itholic** [comment]
Fixed, thanks! :-)

**Review by MaxGekk — APPROVED** [review]
Waiting for CI.

**Comment by MaxGekk** [comment]
+1, LGTM. Merging to master.
Thank you, @itholic.

**Pull request closed without merging**
