### PR TITLE
[SPARK-11778][SQL]:add regression test

### PR DESCRIPTION
**Pull request by huaxingao**
Fix regression test for SPARK-11778.
 @marmbrus
Could you please take a look?
Thank you very much!!

### CODE REVIEW

**Comment by marmbrus** [comment]
ok to test

**Comment by huaxingao** [comment]
I couldn't figure out why the tests failed, but it doesn't seem to me that my new test suite caused the failure.  Is it OK to have a retest? 
Thanks a lot!!

**Comment by squito** [comment]
Jenkins, retest this please

**Comment by rxin** [comment]
Thanks - I'm merging this.

**Pull request closed without merging**
