### PR TITLE
[SPARK-21911][ML][FOLLOW-UP] Fix doc for parallel ML Tuning in PySpark

### PR DESCRIPTION
**Pull request by WeichenXu123**
## What changes were proposed in this pull request?

Fix doc issue mentioned here: https://github.com/apache/spark/pull/19122#issuecomment-340111834

## How was this patch tested?

N/A

### CODE REVIEW

**Comment by viirya** [comment]
retest this please.

**Comment by jkbradley** [comment]
LGTM pending tests

**Comment by WeichenXu123** [comment]
retest this please.

**Comment by holdenk** [comment]
Jenkins retest this please.

**Comment by holdenk** [comment]
LGTM pending jenkins as well.

**Comment by jkbradley** [comment]
merging with master
Thanks!

**Pull request closed without merging**
