### PR TITLE
upgrade joda-time: 2.9 -> 2.9.2

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Comment by rxin** [comment]
You'd need to update the dependency list too.

**Comment by zsxwing** [comment]
ok to test

**Comment by zsxwing** [comment]
@sullis could you create a JIRA for tracking it? This is not a minor change. Please read docs here about how to contribute to Spark: https://cwiki.apache.org/confluence/display/SPARK/Contributing+to+Spark#ContributingtoSpark-ContributingCodeChanges

**Comment by JoshRosen** [comment]
Ping @sullis, can you please create a JIRA for this?

**Comment by HyukjinKwon** [comment]
Could I ask what is the purpose of bumping up the version? Is this being bumped for no reason?

**Comment by HyukjinKwon** [comment]
If so, I think I can create a JIRA and PR based on this with some descriptions for the changes from `2.9` to `2.9.3` if you guess this PR is abandoned.

**Comment by holdenk** [comment]
There are a few minor bug fixes in 2.9.3 that might be good to have access to.

**Comment by srowen** [comment]
@sullis do you mind closing this if you aren't going to update it?
If we can identify any useful changes, sure, fine to update to 2.9.3

**Comment by HyukjinKwon** [comment]
Since it looks this upgrades it to `2.9.2` not the latest ` 2.9.3` which includes possible issues for Spark, @sullis is not answering anymore and it looks this PR is abandoned, I submitted a new PR based on this.

**Pull request closed without merging**
