### PR TITLE
[SPARK-8621] [SQL] crosstab exception when one of the value is empty

### PR DESCRIPTION
**Pull request by animeshbaranawal**
1. Supported Empty String Analysis in parseAttributeName function.
2. String Arguments containing two continuous " ` " character also supported.

cc @rxin @marmbrus

### CODE REVIEW

**Comment by JoshRosen** [comment]
Can you add a regression test?

**Comment by animeshbaranawal** [comment]
Didn't get you @JoshRosen . Are not the crossTab tests already present in DataFrameStatSuite.scala?

**Comment by JoshRosen** [comment]
Yes but it looks like this patch fixes a bug without adding a test that could have reproduced / exposed that bug.  The fact that there was a bug in the old code but no test failed suggests that our test coverage was insufficient.

**Comment by JoshRosen** [comment]
Maybe you have an unstaged test change that didn't get committed here?

**Comment by animeshbaranawal** [comment]
Okay will add a suitable test.

**Comment by rxin** [comment]
cc @cloud-fan can you review this? thanks.

**Comment by cloud-fan** [comment]
Hi @animeshbaranawal , thanks for fixing this!
Spark SQL should allow any kind of string as column name and that's my bad that I mistakenly deny empty string when wrote `parseAttributeName`. I have opened https://github.com/apache/spark/pull/7149 to fix this with less changing and added test, do you mind have a look?

**Pull request closed without merging**
