### PR TITLE
[SPARK-47172][CORE][3.5] Add support for AES-GCM for RPC encryption

### PR DESCRIPTION
**Pull request by sweisdb**
### What changes were proposed in this pull request?

This change adds AES-GCM as an optional AES cipher mode for RPC encryption. The current default is using AES-CTR without any authentication. That would allow someone on the network to easily modify RPC contents on the wire and impact Spark behavior. See [SPARK-47172](https://issues.apache.org/jira/browse/SPARK-47172) for more details.

### Why are the changes needed?

The current default is using AES-CTR without any authentication. That would allow someone on the network to easily modify RPC contents on the wire and impact Spark behavior.

### Does this PR introduce _any_ user-facing change?

Yes, it adds an additional configuration flag is reflected in the documentation.

### How was this patch tested?

Existing unit tests are all ensured to pass. New unit tests are written to explicitly test GCM support and to verify that modifying ciphertext content will cause an exception and fail.

`build/sbt "network-common/test:testOnly"`
`build/sbt "network-common/test:testOnly org.apache.spark.network.crypto.AuthIntegrationSuite"` `build/sbt "network-common/test:testOnly org.apache.spark.network.crypto.AuthEngineSuite"`

### Was this patch authored or co-authored using generative AI tooling?

Nope.

### CODE REVIEW

**Comment by sweisdb** [comment]
The build is failing on unrelated code. @Ngone51 or @mridulm, do you have tips how to proceed?

**Comment by sweisdb** [comment]
There's a build error that needs to be addressed:
```
[error] /home/runner/work/spark/spark/common/network-common/src/main/java/org/apache/spark/network/crypto/GcmTransportCipher.java:148:1:  error: incompatible types: Buffer cannot be converted to ByteBuffer
[error]                     .flip();
[error]                          ^
[error] /home/runner/work/spark/spark/common/network-common/src/main/java/org/apache/spark/network/util/ByteBufferWriteableChannel.java:44:1:  error: incompatible types: Buffer cannot be converted to ByteBuffer
[error]         ByteBuffer temp = src.slice().limit(bytesToWrite);
[error]                                            ^2 errors
```

**Comment by Ngone51** [comment]
> Error: Previously present field "1" with name "source_info" on message "RelationCommon" was deleted.
> Error: buf found 1 breaking changes.

@HyukjinKwon Do you know how to reslove such breaking check failure? Note the breaking change is not introduced by this PR.

**Comment by HyukjinKwon** [comment]
we can ignore it for now

**Comment by Ngone51** [comment]
Thanks, merged to branch-3.5.

**Pull request closed without merging**
