### PR TITLE
[SPARK-7275] [SQL] [WIP] Make LogicalRelation public

### PR DESCRIPTION
**Pull request by gweidner**
Marked as work-in-progress to facilitate review as additional information requested to confirm justification for public vs private.

### CODE REVIEW

**Comment by rxin** [comment]
Why does this need to be public?

**Comment by gweidner** [comment]
Thank you Reynold for your time.  The reporter of the issue stated being private "makes it harder to work with full logical plans from third party packages".  I observed based on history that is was always private and requested more specific details from the reporter regarding "full logical plans from third party packages".

**Comment by rxin** [comment]
Do you mind closing this pull request for now and let's move the discussion to that JIRA ticket? Thanks.

**Comment by gweidner** [comment]
No problem - my apologies for opening the pull request before getting sufficient justification and clarification of use-case scenario for changing from private to public. Thank you!

**Comment by rxin** [comment]
No worry it's good!

**Pull request closed without merging**
