### PR TITLE
[SPARK-45726][CONNECT] Make Dataset.collectResult private

### PR DESCRIPTION
**Pull request by heyihong**
### What changes were proposed in this pull request?

- Make Dataset.collectResult private

### Why are the changes needed?

- Less is more. It is not an API that exposes in the original Spark or PySpark.

### Does this PR introduce _any_ user-facing change?

Yes, Dataset.collectResul is no longer public

### How was this patch tested?

- Existing tests

### CODE REVIEW

**Comment by heyihong** [comment]
@hvanhovell @juliuszsompolski @HyukjinKwon Please take a look

**Comment by hvanhovell** [comment]
@heyihong the cat is already out of bag. I don't want to put it back in.

**Comment by heyihong** [comment]
> @heyihong the cat is already out of bag. I don't want to put it back in.

I don't have a strong opinion on either but exposing collectResult but not exposing the return type [SparkResult](https://github.com/apache/spark/blob/master/connector/connect/common/src/main/scala/org/apache/spark/sql/connect/client/SparkResult.scala#L36) be private[sql] seems inconsistent to me since SparkResult is private[sql].

**Review by dongjoon-hyun — COMMENTED** [review]
I believe we can do this at Apache Spark 4.0.0 after deprecating it at Apache Spark 3.5.1.

**Comment by HyukjinKwon** [comment]
Agree ^

**Comment by hvanhovell** [comment]
I'd like to keep this in since it is a more flexible way of working with results.

**Comment by HyukjinKwon** [comment]
Yeah, let's keep it then.

**Comment by dongjoon-hyun** [comment]
Got it, if you insist, @hvanhovell .

**Comment by dongjoon-hyun** [comment]
According to the above discussion result, let me close this PR. We can re-open this later if something is changed in the future.

**Pull request closed without merging**
