### PR TITLE
[SPARK-31435][DOCS] Add SPARK_JARS_DIR enviroment variable

### PR DESCRIPTION
**Pull request by planga82**
### What changes were proposed in this pull request?

Add SPARK_JARS_DIR enviroment variable (new) to Spark configuration documentation
Related with SPARK-31432, that issue introduces new environment variable that is documented.

### Why are the changes needed?

We need to have this new enviroment variable documented so the users can use it.

### Does this PR introduce any user-facing change?

Only documentation
image

### How was this patch tested?

Documentatión generated in local.

### CODE REVIEW

**Comment by planga82** [comment]
CC @marblejenka, @maropu, @srowen

**Comment by srowen** [comment]
Shouldn't this just be part of https://github.com/apache/spark/pull/28200 ?

**Comment by planga82** [comment]
Yes, it make sense.
@marblejenka, if you want to use this in your pull request, use it

**Comment by HyukjinKwon** [comment]
I picked up this commit and manually moved to #28200.

**Pull request closed without merging**
