### PR TITLE
[SPARK-37754][PYTHON] Fix black version in dev/reformat-python

### PR DESCRIPTION
**Pull request by chia7712**
### What changes were proposed in this pull request?

Make version of `black` in `reformat-python` be consistent to `build_and_test.yml`

related to #35021

### Why are the changes needed?

If we install the old version of black recommended by `reformat-python`, it produces style error happening on `python/pyspark/shuffle.py`

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

This patch only changes the error message

### CODE REVIEW

**Review by zero323 — APPROVED** [review]

**Comment by zero323** [comment]
Could you please adjust the title to match the format we use, i.e. `[SPARK-37754][PYTHON] ...`?

**Comment by chia7712** [comment]
> Could you please adjust the title to match the format we use, i.e. [SPARK-37754][PYTHON] Fix black version in dev/reformat-python?

done

**Comment by zero323** [comment]
Maybe, we should  also set Black version explicitly in `dev/pyproject.toml`

```patch
diff --git a/dev/pyproject.toml b/dev/pyproject.toml
index b90257fc03..0ad817988e 100644
--- a/dev/pyproject.toml
+++ b/dev/pyproject.toml
@@ -25,6 +25,9 @@ testpaths = [
 ]
 
 [tool.black]
+# When changing the version, we have to update
+# GitHub workflow version and dev/reformat-python
+required-version = "21.12b0"
 line-length = 100
 target-version = ['py37']
 include = '\.pyi?$'
```

@HyukjinKwon  WDYT?

**Comment by HyukjinKwon** [comment]
@chia7712 let's fix as @zero323 suggested.

**Comment by chia7712** [comment]
> let's fix as @zero323 suggested.

done

**Review by HyukjinKwon — APPROVED** [review]

**Comment by zero323** [comment]
Merged into master.

**Pull request closed without merging**
