### PR TITLE
[SPARK-17329] [BUILD] Don't build PRs with -Pyarn unless YARN code changed

### PR DESCRIPTION
**Pull request by srowen**
## What changes were proposed in this pull request?

Only build PRs with -Pyarn if YARN code was modified.
## How was this patch tested?

Jenkins tests (will look to verify whether -Pyarn was included in the PR builder for this one.)

### CODE REVIEW

**Comment by srowen** [comment]
CC @vanzin

**Comment by tgravescs** [comment]
does this make a big time difference?  Otherwise lots of things in core affect yarn. mesos and standalone are always built since not different modules, seems like a easy sanity test to leave it being built but if huge time save then

**Comment by tgravescs** [comment]
guess I missed mesos being moved to its own module just saw them changing to build that way also. So I guess nevermind.  I am curious how long it takes though?
If we see problems with it we can always change back.

**Comment by srowen** [comment]
Looks like it's about 7 minutes 32 seconds out of 1 hour 49 minutes to build/test YARN, as of say https://amplab.cs.berkeley.edu/jenkins/view/Spark%20QA%20Test%20(Dashboard)/job/spark-master-test-maven-hadoop-2.7/1657/consoleFull  It's not much, but not trivial.

Yeah the thing is, everything depends on core really, so we should really test everything _unless_ core has been changed. But we selectively build some modules anyway as I suppose the PR builder is only to catch 99% of problems, with the full Jenkins tests actually testing everything.

Yeah this came up because of Mesos and it seemed like YARN could use a similar treatment since it's also a separable module and profile.

**Comment by tgravescs** [comment]
ok, sounds reasonable.

**Comment by vanzin** [comment]
I think this is fine just to make YARN behave like the others. There's already special logic to disable expensive YARN tests when YARN code does not change.

The way dependencies work means that if you change some code in core, that will trigger YARN compilation, just not the extra YARN tests. If you look at this PR's build, you can see it enables -Pyarn:

https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/64710/consoleText

LGTM.

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
