### PR TITLE
[SPARK-24948][SHS][BACKPORT-2.3] Delegate check access permissions to the file system

### PR DESCRIPTION
**Pull request by mgaido91**
## What changes were proposed in this pull request?

In `SparkHadoopUtil. checkAccessPermission`,  we consider only basic permissions in order to check whether a user can access a file or not. This is not a complete check, as it ignores ACLs and other policies a file system may apply in its internal. So this can result in returning wrongly that a user cannot access a file (despite he actually can).

The PR proposes to delegate to the filesystem the check whether a file is accessible or not, in order to return the right result. A caching layer is added for performance reasons.

## How was this patch tested?

added UT

### CODE REVIEW

**Comment by mgaido91** [comment]
cc @jerryshao @mridulm

**Comment by jerryshao** [comment]
Please change the title to add branch 2.3 backport tag.

**Comment by HyukjinKwon** [comment]
retest this please

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by jerryshao** [comment]
merging to branch-2.3.

**Comment by jerryshao** [comment]
@mgaido91 already merged to branch 2.3, please close this PR.

**Comment by mgaido91** [comment]
Thanks @jerryshao , closing.

**Pull request closed without merging**
