### PR TITLE
[Spark-5111][SQL]HiveContext and Thriftserver cannot work in secure cluster beyond hadoop2.5

### PR DESCRIPTION
**Pull request by zhzhan**
Hive0.13 cannot work with secure cluster in hadoop-2.5 and beyound. Due to "java.lang.NoSuchFieldError: SASL_PROPS" error. Need to backport some hive-0.14 fix into spark, since there is no effort to upgrade hive to 0.14 support in spark.

### CODE REVIEW

**Comment by zhzhan** [comment]
@marmbrus Can you take a look at this and let you know if you have any concern?

**Comment by liancheng** [comment]
@zhzhan Would you mind to give a summary of the code added in this PR? I feel kinda hesitant to have this... Mostly because Spark doesn't explicitly support Hadoop 2.5.0 and above versions.

**Comment by zhzhan** [comment]
@liancheng This is to port HIVE-7620 into spark to solve hadoop incompatibility issue.  It will replace the getHadoopSaslProperties in org.apache.hadoop.hive.thrift.HadoopThriftAuthBridge20S if necessary by checking the hadoop version.

https://issues.apache.org/jira/browse/HIVE-7620

I agree the code may not be fitting into the overall code base. But it is broken in hive-0.13 connecting to secure cluster hadoop-2.5 and beyond due to this issue. If hive-0.14 will be supported soon, this patch may not be critical.

By the way, hadoop-2.6 and beyond is becoming main stream in my point of view.

**Comment by zhzhan** [comment]
@liancheng  By the way, if you think it can be merged to upstream, please let me know. Because SparkSQLCLIDriver also need to replace the method to make it work.

  def main(args: Array[String]) {
+    HiveInstrumentationAgent.instrument
    val oproc = new OptionsProcessor()
    if (!oproc.process_stage1(args)) {
      System.exit(1)
    }

**Comment by WangTaoTheTonic** [comment]
@zhzhan Hey Could you describe the error and your configurations in detail please? As we now use Hive 13 + Hadoop 2.7 in our product and never ran into this.

And now Spark could support working with Hive 14 now, per https://github.com/apache/spark/commit/4eb48ed1dadee80d78ada5d15884dd348c46ad27. Is there still this issue?

**Comment by zhzhan** [comment]
@WangTaoTheTonic The problem happens with spark-1.3 and hadoop-2.6 in kerberos cluster. With hive-0.14 support, I suppose the problem may be gone, but I didn't verify it yet. I will close it since hive-0.14 is supported.

**Comment by bolkedebruin** [comment]
@zhzhan @WangTaoTheTonic  I just cloned the latest and this issue still seems to exist. This is on Hadoop 2.6 from HDP 2.2 and Hive 0.14 + Kerberos

**Comment by bolkedebruin** [comment]
To make it a bit more specific: the latest spark does not support secure hive 0.14 yet. I tried the patch but this fails when using a yarn cluster (spark-shell --master yarn-client) in SparkContext. I move the patch to be able to be used in SparkContext and that got me a bit further. However, I couldn't set it in HiveContext anymore and this seems to be required to function, ie. if I remove the patch from HiveContext but leave it in SparkContext it fails. So it seems to be required twice (maybe due to isolated loading? just a guess), but the patch fails in the second instance.

**Pull request closed without merging**
