### PR TITLE
[BUILD] Support building with SBT on encrypted Linux partitions

### PR DESCRIPTION
**Pull request by marmbrus**

### CODE REVIEW

**Comment by srowen** [comment]
As I recall from previous discussions, this was lightly rejected on the grounds that it created artifacts that are incompatible in subtle ways since the classes are named differently, and that might be too confusing:
https://issues.apache.org/jira/browse/SPARK-4820
Hm, I thought it was someone else besides just me saying that ...

**Comment by marmbrus** [comment]
Ah, thanks for the context @srowen!

@pwendell, do we have any concrete reports of this actually causing any incompatibilities in practice?  Given that the change is only going to affect the SBT build (which is never used for distribution artifacts), I'm inclined to merge this patch to simplify the development workflow.  As an anecdote, we have been using this option in our internal build (of Spark and other code) for over a year now and have not encountered any problems.

**Comment by pwendell** [comment]
No there are no known issues, just general wondering whether this could mess up compatibility in some subtle way, for instance if some longer exposed classes are renamed because of this. But I guess it only changes the filename and not the bytecode name of the class, so it should be fine.

Michael - maybe we should also update it for maven now as well if we're going to do this (see the JIRA) and close the JIRA. Otherwise, pretty likely someone will post the same thing for Maven.

**Comment by marmbrus** [comment]
Talk with @pwendell off-line and seems since we don't publish with SBT this is pretty safe.  He asked me to update the docs to make it clear why we don't do this for maven (though if someone from the scala side says this is safe, I'd argue to do it there too).

@srowen any further objections to merging this?

**Comment by marmbrus** [comment]
test this please

**Comment by srowen** [comment]
Hm, doesn't the class file name affect how it's found? that's how the classloader finds the class. I also don't know of a specific instance where this created a problem, but the fact that it needs to be set means something about the output will change. What was the additional bit of info you mention that says this is safe? If it really is verifiably never going to change the linking result, then it doesn't matter, but seems like it would by changing file names.

Is building on an encrypted file system common? Yes the SBT build would only be for developers though the inconsistency is a little worrying, so I think it best to do it both places or neither.

**Comment by marmbrus** [comment]
You are right that it will effect how the class is found, but if I understand correctly, we are shortening generated classes that will only be referenced internally.  For example, a class that is created for a closure inside of a function such as `StreamingJobProgressListener$$anonfun$lastReceivedBatchRecords$1$$anonfun$apply$5$$anonfun$apply$6.class`

I think building on encrypted file systems is becoming more common.  Most corporate laptops I have owned required it, and it was the default when I installed ubuntu on my desktop.

Regarding doing it for maven, we can.  I was going going for the minimal change that would make my dev workflow easier.

**Comment by srowen** [comment]
Yeah I doubt it will affect any user-facing code since those class names aren't massive. It might affect compatibility between two builds of Spark, since these functions get referenced in closures. It might be surprising that Spark built at the same tag on encrypted vs unencrypted file systems isn't compatible. That said I don't have any concrete evidence of this being a problem in practice. I think this is fine as a 'canary'? Nit: maven -> Maven in the doc change. LGTM.

**Comment by pwendell** [comment]
Yeah it's becoming much more common so I'd say let's just go for it across both builds. Otherwise if there is some subtle issue caused by this, it will be super confusing that it only affects one build too.

**Comment by JoshRosen** [comment]
@marmbrus Is this change still necessary?  If not, it might be nice to close this out in order to cut down on the patch queue for the Build component.

**Comment by marmbrus** [comment]
I have a workaround now (build in a docker container), but it anyone wants to pick this up I think it would be useful.

**Pull request closed without merging**
