### PR TITLE
[SPARK-37256][SQL] Replace `ScalaObjectMapper` with `ClassTagExtensions` to fix compilation warning

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
There are some compilation warning log like follows:
```
[WARNING] [Warn] /spark/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/util/RebaseDateTime.scala:268: [deprecation @ org.apache.spark.sql.catalyst.util.RebaseDateTime.loadRebaseRecords.mapper.$anon | origin=com.fasterxml.jackson.module.scala.ScalaObjectMapper | version=2.12.1] trait ScalaObjectMapper in package scala is deprecated (since 2.12.1): ScalaObjectMapper is deprecated because Manifests are not supported in Scala3 
```

Refer to the recommendations of `jackson-module-scala`, this PR use `ClassTagExtensions`  instead of `ScalaObjectMapper`  to fix this compilation warning

### Why are the changes needed?
Fix compilation warning

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass the Jenkins or GitHub Action

### CODE REVIEW

**Review by HyukjinKwon — DISMISSED** [review]

**Comment by LuciferYang** [comment]
Should we merge this ?

**Comment by HyukjinKwon** [comment]
Actually do you know when `ClassTagExtensions` and `DefaultScalaModule` are introduced in which Jackson version? I would like to know the potential impact by this e.g., changing Jackson version in the downstream.

**Comment by LuciferYang** [comment]
@HyukjinKwon @dongjoon-hyun 

`ClassTagExtensions`  introduced in Jackson 2.12.2(https://github.com/FasterXML/jackson-module-scala/pull/498) and `DefaultScalaModule` Is an old API, this PR does not change it.

Then I found that Spark 3.2 use Jackson 2.12.3 and Spark 3.1 use Jackson 2.10.0, so this change can be applied to Spark 3.2, but not Spark 3.1

**Comment by LuciferYang** [comment]
ok

**Review by srowen — APPROVED** [review]

**Comment by LuciferYang** [comment]
thanks @srowen

**Pull request closed without merging**
