### PR TITLE
Update known_translations for contributor names

### PR DESCRIPTION
**Pull request by yhuai**
## What changes were proposed in this pull request?
Update known_translations per https://github.com/apache/spark/pull/16423#issuecomment-269739634

### CODE REVIEW

**Comment by yhuai** [comment]
cc @lw-lin

**Comment by lw-lin** [comment]
this lgtm, thanks!

**Comment by lw-lin** [comment]
sorry, I made a mistake. It should really be: `Yuhai Cen`, rather than `Yuhai Ceng`. could you fix it?

**Comment by yhuai** [comment]
done

**Comment by yhuai** [comment]
I am merging this to master.

**Pull request closed without merging**
