### PR TITLE
[SPARK-26605][yarn] Update AM's credentials when creating tokens.

### PR DESCRIPTION
**Pull request by vanzin**
This ensures new executors in client mode also get the new tokens,
instead of being started with potentially expired tokens.

### CODE REVIEW

**Comment by tgravescs** [comment]
I assume this only applies when using keytab?

**Comment by vanzin** [comment]
Correct. Otherwise the tokens are the same for the lifetime of the AM, there are no new tokens...

**Comment by abellina** [comment]
Just for my edification, and need to look through the code, if the -keytab option is not being used, this is not an issue?

**Comment by vanzin** [comment]
Ping?

**Review by gaborgsomogyi — APPROVED** [review]
LGTM.

**Comment by vanzin** [comment]
Merging to 2.4.

**Pull request closed without merging**
