### PR TITLE
[SPARK-45212][INFRA] Install independent Python linter dependencies for branch-3.5

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr install independent Python linter dependencies for branch-3.5 to make the daily test of branch-3.5 uses the correct dependencies for Python linter checking.

### Why are the changes needed?
The daily test of branch-3.5 failed during Python linter check:
- https://github.com/apache/spark/actions/runs/6221638911/job/16884068430

image

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
- Pass GitHub Actions
- Monitor branch-3.5 daily test

### Was this patch authored or co-authored using generative AI tooling?
No

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by zhengruifeng** [comment]
LGTM

**Comment by panbingkun** [comment]
+1, LGTM.

**Comment by dongjoon-hyun** [comment]
Merged to master. Thank you, @LuciferYang and all.

**Pull request closed without merging**
