### PR TITLE
[SPARK-16475][SQL] Broadcast Hint for SQL Queries

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
## What changes were proposed in this pull request?

This PR aims to achieve the following two goals in Spark SQL.

**1. Generic Hint Syntax**
The generic hints are parsed and transformed into concrete hints by `SubstituteHints` of **Analyzer**. The unknown hints are removed, too. For example, `Hint("MAPJOIN")` is transformed into `BroadcastJoin` and other hints are removed currently.

``` sql
SELECT /*+ MAPJOIN(t) */ * FROM t
SELECT /*+ STREAMTABLE(a,b,c) */ * FROM t
SELECT /*+ INDEX(t emp_job_ix) */ * FROM t
```

Unlink Hive, `NEWMAPJOIN(t)` is allowed for accepting new Spark Hints.

**2. Broadcast Hints**
The followings are recognized. Technically, broadcast hints are matched `UnresolvedRelation` to support Hive `MetastoreRelation`. The style of `database_name.table_name` is not allowed in this PR.

``` sql
SELECT /*+ MAPJOIN(t) */ * FROM t JOIN u ON t.id = u.id
SELECT /*+ BROADCAST(u) */ * FROM t JOIN u ON t.id = u.id
SELECT /*+ BROADCASTJOIN(u) */ * FROM t JOIN u ON t.id = u.id
```

**Examples**

``` scala
scala> spark.range(1000000000).createOrReplaceTempView("t")
scala> spark.range(1000000000).createOrReplaceTempView("u")

scala> sql("SELECT * FROM t JOIN u ON t.id = u.id").explain
== Physical Plan ==
*SortMergeJoin [id#0L], [id#4L], Inner
:- *Sort [id#0L ASC], false, 0
:  +- Exchange hashpartitioning(id#0L, 200)
:     +- *Range (0, 1000000000, splits=8)
+- *Sort [id#4L ASC], false, 0
   +- ReusedExchange [id#4L], Exchange hashpartitioning(id#0L, 200)

scala> sql("SELECT /*+ MAPJOIN(t) */ * FROM t JOIN u ON t.id = u.id").explain
== Physical Plan ==
*BroadcastHashJoin [id#0L], [id#4L], Inner, BuildLeft
:- BroadcastExchange HashedRelationBroadcastMode(List(input[0, bigint, false]))
:  +- *Range (0, 1000000000, splits=8)
+- *Range (0, 1000000000, splits=8)

scala> sql("SELECT /*+ MAPJOIN(u) */ * FROM t JOIN u ON t.id = u.id").explain
== Physical Plan ==
*BroadcastHashJoin [id#0L], [id#4L], Inner, BuildRight
:- *Range (0, 1000000000, splits=8)
+- BroadcastExchange HashedRelationBroadcastMode(List(input[0, bigint, false]))
   +- *Range (0, 1000000000, splits=8)

scala> sql("CREATE TABLE hive_t(id INT)")
res5: org.apache.spark.sql.DataFrame = []

scala> sql("CREATE TABLE hive_u(id INT)")
res6: org.apache.spark.sql.DataFrame = []

scala> sql("SELECT /*+ MAPJOIN(hive_u) */ * FROM hive_t JOIN hive_u ON hive_t.id = hive_u.id").explain
== Physical Plan ==
*BroadcastHashJoin [id#28], [id#29], Inner, BuildRight
:- *Filter isnotnull(id#28)
:  +- HiveTableScan [id#28], MetastoreRelation default, hive_t
+- BroadcastExchange HashedRelationBroadcastMode(List(cast(input[0, int, false] as bigint)))
   +- *Filter isnotnull(id#29)
      +- HiveTableScan [id#29], MetastoreRelation default, hive_u

scala> sql("SELECT * FROM hive_t JOIN hive_u ON hive_t.id = hive_u.id").explain
== Physical Plan ==
*SortMergeJoin [id#36], [id#37], Inner
:- *Sort [id#36 ASC], false, 0
:  +- Exchange hashpartitioning(id#36, 200)
:     +- *Filter isnotnull(id#36)
:        +- HiveTableScan [id#36], MetastoreRelation default, hive_t
+- *Sort [id#37 ASC], false, 0
   +- Exchange hashpartitioning(id#37, 200)
      +- *Filter isnotnull(id#37)
         +- HiveTableScan [id#37], MetastoreRelation default, hive_u
```

The many previous discussions on this issue are at https://github.com/apache/spark/pull/14132 .
## How was this patch tested?

Pass the Jenkins tests with new testcases.

### CODE REVIEW

**Comment by rxin** [comment]
Why creating a new pull request? All the discussions were in the other pull request.

**Comment by dongjoon-hyun** [comment]
Oh, it's just because the previous PR page with 363 comments becomes too slow to view in my laptop. Since the most recent discussion was ended two days ago with implementations. I think it's safe and better for being review again here. I can move some summary of the previous discussion decision into here, too.

**Comment by dongjoon-hyun** [comment]
Rebased to resolve conflicts on `SqlBase.g4`.

**Comment by dongjoon-hyun** [comment]
Hi, @cloud-fan .
Could you review this PR about HINT when you have some time?

**Comment by dongjoon-hyun** [comment]
Resolve conflicts.

**Comment by watermen** [comment]
Do this PR support multiple JOINs(`SELECT * FROM t1 JOIN t2 ON t1.key = t2.key JOIN t3 ON t1.key = t3.key`)?

**Comment by dongjoon-hyun** [comment]
Oh, sorry for late response, @watermen . I missed your message. Yes. This supports multiple joins.

**Comment by dongjoon-hyun** [comment]
For your testcase, I will check again locally and add as a test case to ensure that.

**Comment by dongjoon-hyun** [comment]
Hi, @watermen . You can try that like this.
```scala
scala> spark.range(1000000000).createOrReplaceTempView("t1")
scala> spark.range(1000000000).createOrReplaceTempView("t2")
scala> spark.range(1000000000).createOrReplaceTempView("t3")
scala> sql("SELECT * FROM t1 JOIN t2 ON t1.id = t2.id JOIN t3 ON t1.id = t3.id").explain
== Physical Plan ==
*SortMergeJoin [id#0L], [id#8L], Inner
:- *SortMergeJoin [id#0L], [id#4L], Inner
:  :- *Sort [id#0L ASC], false, 0
:  :  +- Exchange hashpartitioning(id#0L, 200)
:  :     +- *Range (0, 1000000000, splits=8)
:  +- *Sort [id#4L ASC], false, 0
:     +- ReusedExchange [id#4L], Exchange hashpartitioning(id#0L, 200)
+- *Sort [id#8L ASC], false, 0
   +- ReusedExchange [id#8L], Exchange hashpartitioning(id#0L, 200)

scala> sql("SELECT /*+ MAPJOIN(t1) */ * FROM t1 JOIN t2 ON t1.id = t2.id JOIN t3 ON t1.id = t3.id").explain
== Physical Plan ==
*SortMergeJoin [id#0L], [id#8L], Inner
:- *Sort [id#0L ASC], false, 0
:  +- Exchange hashpartitioning(id#0L, 200)
:     +- *BroadcastHashJoin [id#0L], [id#4L], Inner, BuildLeft
:        :- BroadcastExchange HashedRelationBroadcastMode(List(input[0, bigint, false]))
:        :  +- *Range (0, 1000000000, splits=8)
:        +- *Range (0, 1000000000, splits=8)
+- *Sort [id#8L ASC], false, 0
   +- Exchange hashpartitioning(id#8L, 200)
      +- *Range (0, 1000000000, splits=8)

scala> sql("SELECT /*+ MAPJOIN(t2) */ * FROM t1 JOIN t2 ON t1.id = t2.id JOIN t3 ON t1.id = t3.id").explain
== Physical Plan ==
*SortMergeJoin [id#0L], [id#8L], Inner
:- *Sort [id#0L ASC], false, 0
:  +- Exchange hashpartitioning(id#0L, 200)
:     +- *BroadcastHashJoin [id#0L], [id#4L], Inner, BuildRight
:        :- *Range (0, 1000000000, splits=8)
:        +- BroadcastExchange HashedRelationBroadcastMode(List(input[0, bigint, false]))
:           +- *Range (0, 1000000000, splits=8)
+- *Sort [id#8L ASC], false, 0
   +- Exchange hashpartitioning(id#8L, 200)
      +- *Range (0, 1000000000, splits=8)

scala> sql("SELECT /*+ MAPJOIN(t3) */ * FROM t1 JOIN t2 ON t1.id = t2.id JOIN t3 ON t1.id = t3.id").explain
== Physical Plan ==
*BroadcastHashJoin [id#0L], [id#8L], Inner, BuildRight
:- *SortMergeJoin [id#0L], [id#4L], Inner
:  :- *Sort [id#0L ASC], false, 0
:  :  +- Exchange hashpartitioning(id#0L, 200)
:  :     +- *Range (0, 1000000000, splits=8)
:  +- *Sort [id#4L ASC], false, 0
:     +- ReusedExchange [id#4L], Exchange hashpartitioning(id#0L, 200)
+- BroadcastExchange HashedRelationBroadcastMode(List(input[0, bigint, false]))
   +- *Range (0, 1000000000, splits=8)
```

**Comment by dongjoon-hyun** [comment]
Rebased to resolve conflicts.

**Comment by dongjoon-hyun** [comment]
Hi, @rxin .
Could you give me some guide for this `Broadcast Hint for SQL Queries` if you have sometime?

**Comment by dongjoon-hyun** [comment]
Hi, @gatorsmile .
Could you review this PR when you have some time?

**Comment by dongjoon-hyun** [comment]
Rebased to resolve the conflicts.

**Comment by dongjoon-hyun** [comment]
Resolve the conflicts.

**Comment by dongjoon-hyun** [comment]
Retest this please

**Comment by rxin** [comment]
Mind closing this for now? Let's open it once we've done the view canonicalization work. This pr will be much simpler. We should do both in 2.2.

**Comment by dongjoon-hyun** [comment]
Thank you for guide.

**Comment by rxin** [comment]
@dongjoon-hyun do you have time to update the pull request now the view canonicalization work is done? Basically we can remove all the SQL generation stuff.

**Comment by rxin** [comment]
Actually I have some time. I will submit a pr based on this.

**Comment by dongjoon-hyun** [comment]
Oh.

**Pull request closed without merging**
