### PR TITLE
[SPARK-11551][DOC][Example]Replace example code in ml-features.md using include_example

### PR DESCRIPTION
**Pull request by somideshmukh**
Replaced Java and Scala code,pls check only spark-115551

### CODE REVIEW

**Comment by yinxusen** [comment]
@somideshmukh Thanks for working on this!

**Comment by yinxusen** [comment]
@somideshmukh Pls follow [Spark Style Guide](https://cwiki.apache.org/confluence/display/SPARK/Spark+Code+Style+Guide). E.g. All Java code should follow 2-indention style.

**Comment by yinxusen** [comment]
@somideshmukh Do you still have time for this? I can help if you don't have enough time.

**Comment by somideshmukh** [comment]
I am working on this,today it will be completed

**Pull request closed without merging**
