### PR TITLE
[SPARK-36270][BUILD][3.1] Change memory settings for enabling GA

### PR DESCRIPTION
**Pull request by viirya**
### What changes were proposed in this pull request?

Trying to adjust build memory settings and serial execution to re-enable GA.

### Why are the changes needed?

GA tests are failed recently due to return code 137. We need to adjust build settings to make GA work.

### Does this PR introduce _any_ user-facing change?

No, dev only.

### How was this patch tested?

GA

### CODE REVIEW

**Comment by viirya** [comment]
cc @dongjoon-hyun @HyukjinKwon @gengliangwang

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM (Pending CIs)

**Comment by viirya** [comment]
Thanks. GA, Jenkins are passed. Merging to 3.1.

**Review by HyukjinKwon — COMMENTED** [review]
Lgtm

**Pull request closed without merging**
