### PR TITLE
[SPARK-28863][SQL][FOLLOWUP] Make sure optimized plan will not be re-analyzed

### PR DESCRIPTION
**Pull request by cloud-fan**
### What changes were proposed in this pull request?

It's a known issue that re-analyzing an optimized plan can lead to various issues. We made several attempts to avoid it from happening, but the current solution `AlreadyOptimized` is still not 100% safe, as people can inject catalyst rules to call analyzer directly.

This PR proposes a simpler and safer idea: we set the `analyzed` flag to true after optimization, and analyzer will skip processing plans whose `analyzed` flag is true.

### Why are the changes needed?

make the code simpler and safer

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

existing tests.

### CODE REVIEW

**Comment by cloud-fan** [comment]
cc @brkyvz

**Comment by maropu** [comment]
The change looks reasonable to me.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master and branch-3.1.

@cloud-fan, it has a conflict with branch-3.0. Do you mind opening a backport PR?

**Comment by brkyvz** [comment]
late LGTM. I believe this is a much more robust solution

**Pull request closed without merging**
