### PR TITLE
[SPARK-42218][BUILD] Upgrade `netty` to version 4.1.87.Final

### PR DESCRIPTION
**Pull request by bjornjorgensen**
### What changes were proposed in this pull request?
Upgrade netty from version 4.1.86.Final to version 4.1.87.Final

### Why are the changes needed?
[New netty release witch fix some bugs. ](https://netty.io/news/2023/01/12/4-1-87-Final.html)

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA

### CODE REVIEW

**Comment by bjornjorgensen** [comment]
@LuciferYang you did a review on the last one https://github.com/apache/spark/pull/39116
Will you have a look at this one? And should we have this in branch 3.4?

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM (Pending CIs). 

Also, +1 for backporting to branch-3.4 and testing via RC1.

cc @xinrong-meng because she is the release manager of Apache Spark 3.4.

**Review by LuciferYang — APPROVED** [review]
+1, LGTM

**Comment by LuciferYang** [comment]
Can you re-trigger the failed GA task? @bjornjorgensen

**Comment by dongjoon-hyun** [comment]
SparkR failure seems to be irrelevant. Merged to master/3.4.

**Pull request closed without merging**
