### PR TITLE
[SPARK-13203] Add scalastyle rule banning use of mutable.SynchronizedBuffer

### PR DESCRIPTION
**Pull request by ted-yu**
See discussion at the tail of #11059

@andrewor14 
Please review

### CODE REVIEW

**Comment by ted-yu** [comment]
Jenkins, test this please.

**Comment by andrewor14** [comment]
can you add one for `SynchronizedMap` as well

**Comment by ted-yu** [comment]
```
external/kafka/src/test/scala/org/apache/spark/streaming/kafka/KafkaStreamSuite.scala:    val result = new mutable.HashMap[String, Long]() with mutable.SynchronizedMap[String, Lo
extras/kinesis-asl/src/test/scala/org/apache/spark/streaming/kinesis/KinesisStreamSuite.scala:      with mutable.SynchronizedMap[Time, (Array[SequenceNumberRanges], Seq[Int])]
streaming/src/main/scala/org/apache/spark/streaming/dstream/FileInputDStream.scala:    new mutable.HashMap[Time, Array[String]] with mutable.SynchronizedMap[Time, Array[String]]
streaming/src/main/scala/org/apache/spark/streaming/dstream/FileInputDStream.scala:      new mutable.HashMap[Time, Array[String]] with mutable.SynchronizedMap[Time, Array[String]
streaming/src/test/scala/org/apache/spark/streaming/StreamingListenerSuite.scala:import scala.collection.mutable.{ArrayBuffer, HashMap, SynchronizedBuffer, SynchronizedMap}
streaming/src/test/scala/org/apache/spark/streaming/StreamingListenerSuite.scala:  val failureReasons = new HashMap[Int, String] with SynchronizedMap[Int, String]
```
Since SynchronizedMap is used, should I open another JIRA ?

**Comment by ted-yu** [comment]
```
external/kafka/src/test/scala/org/apache/spark/streaming/kafka/DirectKafkaStreamSuite.scala:      new ArrayBuffer[(String, String)] with mutable.SynchronizedBuffer[(String, Strin
external/kafka/src/test/scala/org/apache/spark/streaming/kafka/DirectKafkaStreamSuite.scala:    val collectedData = new mutable.ArrayBuffer[String]() with mutable.SynchronizedBuf
external/kafka/src/test/scala/org/apache/spark/streaming/kafka/DirectKafkaStreamSuite.scala:    val collectedData = new mutable.ArrayBuffer[String]() with mutable.SynchronizedBuf
external/kafka/src/test/scala/org/apache/spark/streaming/kafka/DirectKafkaStreamSuite.scala:      new ArrayBuffer[(String, String)] with mutable.SynchronizedBuffer[(String, Strin
external/kafka/src/test/scala/org/apache/spark/streaming/kafka/DirectKafkaStreamSuite.scala:      new mutable.ArrayBuffer[Array[String]]() with mutable.SynchronizedBuffer[Array[S
external/kafka/src/test/scala/org/apache/spark/streaming/kafka/DirectKafkaStreamSuite.scala:  val collectedData = new mutable.ArrayBuffer[String]() with mutable.SynchronizedBuffe
streaming/src/main/scala/org/apache/spark/streaming/receiver/ReceiverSupervisorImpl.scala:    with mutable.SynchronizedBuffer[BlockGenerator]
streaming/src/test/scala/org/apache/spark/streaming/TestSuiteBase.scala:import scala.collection.mutable.SynchronizedBuffer
streaming/src/test/scala/org/apache/spark/streaming/receiver/BlockGeneratorSuite.scala:    val pushedData = new mutable.ArrayBuffer[Any] with mutable.SynchronizedBuffer[Any]
streaming/src/test/scala/org/apache/spark/streaming/receiver/BlockGeneratorSuite.scala:    val addedData = new mutable.ArrayBuffer[Any] with mutable.SynchronizedBuffer[Any]
streaming/src/test/scala/org/apache/spark/streaming/receiver/BlockGeneratorSuite.scala:    val addedMetadata = new mutable.ArrayBuffer[Any] with mutable.SynchronizedBuffer[Any]
streaming/src/test/scala/org/apache/spark/streaming/util/RecurringTimerSuite.scala:    val results = new mutable.ArrayBuffer[Long]() with mutable.SynchronizedBuffer[Long]
streaming/src/test/scala/org/apache/spark/streaming/util/RecurringTimerSuite.scala:    val results = new mutable.ArrayBuffer[Long]() with mutable.SynchronizedBuffer[Long]
```
Should the above be cleaned as addendum to #11059 or, using this PR ?

**Comment by ted-yu** [comment]
Jenkins, test this please.

**Comment by ted-yu** [comment]
Logged SPARK-13204 for replacing mutable.SynchronizedMap

**Comment by ted-yu** [comment]
Jenkins, test this please.

**Comment by ted-yu** [comment]
Jenkins, test this please.

**Comment by andrewor14** [comment]
I think there's some overlap between this patch and #11067

**Comment by ted-yu** [comment]
Jenkins, test this please.

**Comment by ted-yu** [comment]
Some files in this PR are not covered by #11067
@holdenk 
I can base my PR on yours.

Let me know what you think.

**Comment by ted-yu** [comment]
Jenkins, test this please

**Comment by holdenk** [comment]
I'd probably just wait for the streaming PR to also get merged in - makes it simpler.

**Comment by ted-yu** [comment]
Jenkins, test this please

**Comment by ted-yu** [comment]
Jenkins, test this please

**Comment by ted-yu** [comment]
Jenkins, test this please

**Comment by ted-yu** [comment]
Jenkins, test this please

**Comment by ted-yu** [comment]
I am trying to add an Array to ConcurrentLinkedQueue (collectedData) in Scala 2.11:
```
stream.foreachRDD { rdd => Collections.addAll(collectedData, rdd.collect()) }
```
I got the following compilation error:
```
[error]  found   : java.util.concurrent.ConcurrentLinkedQueue[(String, String)]
[error]  required: java.util.Collection[_ >: java.io.Serializable]
[error] Note: (String, String) <: Any, but Java-defined trait Collection is invariant in type E.
[error] You may wish to investigate a wildcard type such as `_ <: Any`. (SLS 3.2.10)
[error]     stream.foreachRDD { rdd => Collections.addAll(allReceived, rdd.collect()) }
```

**Comment by holdenk** [comment]
@ted-yu you can use Arrays.asList with the splat syntax along with the ConcurrentLinkedQueues add all method:

`collectedData.addAll(Arrays.asList(rdd.collect():_*))`

**Comment by ted-yu** [comment]
Jenkins, test this please.

**Comment by ted-yu** [comment]
Jenkins, test this please.

**Comment by ted-yu** [comment]
There is no error in DirectKafkaStreamSuite.scala

Once [~holdenk]'s PR goes in, I will rebase.

**Comment by srowen** [comment]
@ted-yu please close this PR, or go ahead and make it only about the issue you filed: a scalastyle rule.

**Comment by ted-yu** [comment]
DirectKafkaStreamSuite.scala is not covered by #11067
Addition of scalastyle rule would not pass even after #11067 goes in.

Should I open a seperate PR for DirectKafkaStreamSuite.scala ?

**Comment by srowen** [comment]
Of course, this depends on the new rule passing for the whole project. If an existing PR means to catch all occurrences of the issue the rule would flag, then it needs to cover this case too. You should comment on https://github.com/apache/spark/pull/11067, not here. I see no reason you would open another PR.

**Comment by ted-yu** [comment]
bq. If an existing PR means to catch all occurrences of the issue the rule would flag, then it needs to cover this case too

In this case, looks like SPARK-13151 should cover all occurrences.

**Pull request closed without merging**
