### PR TITLE
[SPARK-8482] Added M4 instances to the list.

### PR DESCRIPTION
**Pull request by pradeepchhetri**
AWS recently added M4 instances (https://aws.amazon.com/blogs/aws/the-new-m4-instance-type-bonus-price-reduction-on-m3-c4/).

### CODE REVIEW

**Comment by srowen** [comment]
https://cwiki.apache.org/confluence/display/SPARK/Contributing+to+Spark
Usually we ask for JIRAs

**Comment by pradeepchhetri** [comment]
@srowen I created a JIRA ticket and updated the title with that.

**Comment by JoshRosen** [comment]
We might as well include the new Tc.large instance while we're at it: https://aws.amazon.com/blogs/aws/new-t2-large-instances/

**Comment by pradeepchhetri** [comment]
@JoshRosen Thank you for reminding it. Added t2.large as well.

**Comment by JoshRosen** [comment]
Jenkins, this is ok to test.

(So the Python style checks are run)

**Comment by JoshRosen** [comment]
Jenkins, this is ok to test.

**Comment by JoshRosen** [comment]
Jenkins, retest this please.

**Comment by JoshRosen** [comment]
(Retesting to test a build script change)

**Comment by JoshRosen** [comment]
@davies @ahirreddy The tests here passed, but the test-selection logic was _too_ good:  by skipping all of the Scala / Java tests, we didn't write any JUnit XML files, causing Jenkins to mark the build as failed.  Maybe we should just add a dummy XML file to the build / repo to avoid this (or see if we can somehow configure the Jenkins plugin to be more permissive w.r.t missing report files (the artifact upload plugin is robust against this, for example)).

**Comment by srowen** [comment]
LGTM. This is safe to commit in that there was no actual test failure due to this right?

**Comment by JoshRosen** [comment]
Yeah it should be fine to commit; go ahead.

**Comment by shivaram** [comment]
Merging this

**Pull request closed without merging**
