### PR TITLE
[SPARK-39316][FOLLOWUP][SQL][TESTS] Update q83.ansi golden files result

### PR DESCRIPTION
**Pull request by wangyum**
### What changes were proposed in this pull request?

Re-generate golden files:
```
SPARK_GENERATE_GOLDEN_FILES=1 SPARK_ANSI_SQL_MODE=true build/sbt "sql/testOnly *PlanStability*Suite"
```

### Why are the changes needed?

To make tests pass with ANSI mode.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

N/A

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
Thank you for quick fix, @wangyum .

**Comment by dongjoon-hyun** [comment]
cc @ulysses-you and @cloud-fan

**Review by ulysses-you — APPROVED** [review]
thank you for the fix !

**Review by HyukjinKwon — APPROVED** [review]

**Review by cloud-fan — APPROVED** [review]
thanks!

**Comment by cloud-fan** [comment]
merging to master!

**Pull request closed without merging**
