### PR TITLE
[SPARK-34387][CORE][TESTS] Add ZStandardBenchmark

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to add ZStandardBenchmark as a base-line.

### Why are the changes needed?

This will prevent any regression when we upgrade Zstandard library in the future.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Manually.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Could you review this PR, @HyukjinKwon , @maropu , @viirya ? This is a baseline for ZStandardCompression to prevent any regression in the future.

**Review by maropu — APPROVED** [review]
Looks fine

**Review by viirya — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Oh, thank you, @maropu and @viirya !

**Comment by dongjoon-hyun** [comment]
Merged to master because this is irrelevant to the UT or IT.

**Review by HyukjinKwon — COMMENTED** [review]
lgtm2

**Comment by dongjoon-hyun** [comment]
Thank you, @HyukjinKwon !

**Pull request closed without merging**
