### PR TITLE
[SPARK-11112] DAG visualization: display RDD callsite

### PR DESCRIPTION
**Pull request by andrewor14**
screen shot 2015-11-01 at 9 42 33 am
@mateiz @sarutak

### CODE REVIEW

**Comment by andrewor14** [comment]
retest this please

**Comment by sarutak** [comment]
Thanks @andrewor14 , I'll look into this soon!

**Comment by mateiz** [comment]
Thanks for adding this! The UI itself looks good to me.

**Comment by sarutak** [comment]
It LGTM.
I looked into this and tried to work this with some jobs.

**Comment by sarutak** [comment]
If you are not planing additional changes on this and no one has comments, I'll commit this.

**Comment by andrewor14** [comment]
OK, merging into master. Thanks.

**Comment by andrewor14** [comment]
OK, I'm merging this myself because I want to get it into 1.6. Thanks.

**Pull request closed without merging**
