### PR TITLE
[SPARK-38744][SQL][TESTS] Test the error class: NON_LITERAL_PIVOT_VALUES

### PR DESCRIPTION
**Pull request by panbingkun**
## What changes were proposed in this pull request?
This PR aims to add a test for the error class NON_LITERAL_PIVOT_VALUES to `QueryCompilationErrorsSuite`.

### Why are the changes needed?
The changes improve test coverage, and document expected error messages in tests.

### Does this PR introduce any user-facing change?
No

### How was this patch tested?
By running new test:
```
$ build/sbt "sql/testOnly *QueryCompilationErrorsSuite*"
```

### CODE REVIEW

**Comment by panbingkun** [comment]
Add tests for the error classes PIVOT_VALUE_DATA_TYPE_MISMATCH to QueryCompilationErrorsSuite. 
Resolved by: https://issues.apache.org/jira/browse/SPARK-38748 (https://github.com/apache/spark/pull/36400)

**Comment by LuciferYang** [comment]
GA test failed

```
2022-05-02T12:32:09.6882052Z - NON_LITERAL_PIVOT_VALUES: literal expressions required for pivot values *** FAILED *** (33 milliseconds)
2022-05-02T12:32:09.6902974Z   "...es, found 'earnings#[6618]'" did not equal "...es, found 'earnings#[12]'" (QueryErrorsSuiteBase.scala:42)
2022-05-02T12:32:09.6908401Z   Analysis:
2022-05-02T12:32:09.6912861Z   "...es, found 'earnings#[6618]'" -> "...es, found 'earnings#[12]'"
2022-05-02T12:32:09.6931343Z   org.scalatest.exceptions.TestFailedException:
2022-05-02T12:32:09.6935932Z   at org.scalatest.Assertions.newAssertionFailedException(Assertions.scala:472)
2022-05-02T12:32:09.6940988Z   at org.scalatest.Assertions.newAssertionFailedException$(Assertions.scala:471)
2022-05-02T12:32:09.6945673Z   at org.scalatest.Assertions$.newAssertionFailedException(Assertions.scala:1231)
2022-05-02T12:32:09.6950146Z   at org.scalatest.Assertions$AssertionsHelper.macroAssert(Assertions.scala:1295)
2022-05-02T12:32:09.6954703Z   at org.apache.spark.sql.errors.QueryErrorsSuiteBase.checkErrorClass(QueryErrorsSuiteBase.scala:42)
2022-05-02T12:32:09.6959336Z   at org.apache.spark.sql.errors.QueryErrorsSuiteBase.checkErrorClass$(QueryErrorsSuiteBase.scala:25)
2022-05-02T12:32:09.6964366Z   at org.apache.spark.sql.errors.QueryCompilationErrorsSuite.checkErrorClass(QueryCompilationErrorsSuite.scala:33)
2022-05-02T12:32:09.6969252Z   at org.apache.spark.sql.errors.QueryCompilationErrorsSuite.$anonfun$new$76(QueryCompilationErrorsSuite.scala:540)
2022-05-02T12:32:09.6973788Z   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
2022-05-02T12:32:09.6978035Z   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
2022-05-02T12:32:09.6983165Z   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
2022-05-02T12:32:09.6988157Z   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
2022-05-02T12:32:09.6992897Z   at org.scalatest.Transformer.apply(Transformer.scala:22)
2022-05-02T12:32:09.6997625Z   at org.scalatest.Transformer.apply(Transformer.scala:20)
2022-05-02T12:32:09.7002558Z   at org.scalatest.funsuite.AnyFunSuiteLike$$anon$1.apply(AnyFunSuiteLike.scala:190)
2022-05-02T12:32:09.7007513Z   at org.apache.spark.SparkFunSuite.withFixture(SparkFunSuite.scala:203)
2022-05-02T12:32:09.7043074Z   at org.scalatest.funsuite.AnyFunSuiteLike.invokeWithFixture$1(AnyFunSuiteLike.scala:188)
2022-05-02T12:32:09.7059733Z   at org.scalatest.funsuite.AnyFunSuiteLike.$anonfun$runTest$1(AnyFunSuiteLike.scala:200)
2022-05-02T12:32:09.7065437Z   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
```

**Comment by panbingkun** [comment]
> GA test failed
> 
> ```
> 2022-05-02T12:32:09.6882052Z - NON_LITERAL_PIVOT_VALUES: literal expressions required for pivot values *** FAILED *** (33 milliseconds)
> 2022-05-02T12:32:09.6902974Z   "...es, found 'earnings#[6618]'" did not equal "...es, found 'earnings#[12]'" (QueryErrorsSuiteBase.scala:42)
> 2022-05-02T12:32:09.6908401Z   Analysis:
> 2022-05-02T12:32:09.6912861Z   "...es, found 'earnings#[6618]'" -> "...es, found 'earnings#[12]'"
> 2022-05-02T12:32:09.6931343Z   org.scalatest.exceptions.TestFailedException:
> 2022-05-02T12:32:09.6935932Z   at org.scalatest.Assertions.newAssertionFailedException(Assertions.scala:472)
> 2022-05-02T12:32:09.6940988Z   at org.scalatest.Assertions.newAssertionFailedException$(Assertions.scala:471)
> 2022-05-02T12:32:09.6945673Z   at org.scalatest.Assertions$.newAssertionFailedException(Assertions.scala:1231)
> 2022-05-02T12:32:09.6950146Z   at org.scalatest.Assertions$AssertionsHelper.macroAssert(Assertions.scala:1295)
> 2022-05-02T12:32:09.6954703Z   at org.apache.spark.sql.errors.QueryErrorsSuiteBase.checkErrorClass(QueryErrorsSuiteBase.scala:42)
> 2022-05-02T12:32:09.6959336Z   at org.apache.spark.sql.errors.QueryErrorsSuiteBase.checkErrorClass$(QueryErrorsSuiteBase.scala:25)
> 2022-05-02T12:32:09.6964366Z   at org.apache.spark.sql.errors.QueryCompilationErrorsSuite.checkErrorClass(QueryCompilationErrorsSuite.scala:33)
> 2022-05-02T12:32:09.6969252Z   at org.apache.spark.sql.errors.QueryCompilationErrorsSuite.$anonfun$new$76(QueryCompilationErrorsSuite.scala:540)
> 2022-05-02T12:32:09.6973788Z   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
> 2022-05-02T12:32:09.6978035Z   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
> 2022-05-02T12:32:09.6983165Z   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
> 2022-05-02T12:32:09.6988157Z   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
> 2022-05-02T12:32:09.6992897Z   at org.scalatest.Transformer.apply(Transformer.scala:22)
> 2022-05-02T12:32:09.6997625Z   at org.scalatest.Transformer.apply(Transformer.scala:20)
> 2022-05-02T12:32:09.7002558Z   at org.scalatest.funsuite.AnyFunSuiteLike$$anon$1.apply(AnyFunSuiteLike.scala:190)
> 2022-05-02T12:32:09.7007513Z   at org.apache.spark.SparkFunSuite.withFixture(SparkFunSuite.scala:203)
> 2022-05-02T12:32:09.7043074Z   at org.scalatest.funsuite.AnyFunSuiteLike.invokeWithFixture$1(AnyFunSuiteLike.scala:188)
> 2022-05-02T12:32:09.7059733Z   at org.scalatest.funsuite.AnyFunSuiteLike.$anonfun$runTest$1(AnyFunSuiteLike.scala:200)
> 2022-05-02T12:32:09.7065437Z   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
> ```

Done! Thansks @LuciferYang

**Review by MaxGekk — APPROVED** [review]

**Comment by MaxGekk** [comment]
+1, LGTM. Merging to master.
Thank you, @panbingkun and @LuciferYang for review.

**Pull request closed without merging**
