### PR TITLE
[SPARK-34111][BUILD][3.1] Deconflict the jars jakarta.servlet-api-4.0.3.jar and javax.servlet-api-3.1.0.jar

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

Use the right name for the artifact `javax.servlet-api` in hadoop 3.2 profile

### Why are the changes needed?

fix deps issue

### Does this PR introduce _any_ user-facing change?

no
### How was this patch tested?

1. should pass existing jenkins
2. I have manually tested a spark application with the `javax.servlet-api-3.1.0.jar` deleted and it worked fine

### CODE REVIEW

**Comment by yaooqinn** [comment]
cc @HyukjinKwon @dongjoon-hyun

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM (Pending CIs)
Thank you, @yaooqinn .

**Comment by HyukjinKwon** [comment]
I think this causes the test being hanging:
Screen Shot 2021-01-17 at 6 20 32 PM

I will lower the priority of this ticket from Blocker to Critical since we haven't found an explicitly known issue in Apache Spark yet by this, and this is at least fixed in master by shading the Hadoop client by SPARK-33212, which I think is a good step forward. cc @gatorsmile FYI.

I will cut the RC Monday PST. It will be good to have this fix, though.

**Comment by yaooqinn** [comment]
I have tested andpassed  the hanging ut locally. seems a github action issue

**Comment by yaooqinn** [comment]
GA Looks OK now? @HyukjinKwon @dongjoon-hyun

**Comment by HyukjinKwon** [comment]
let me retrigger few more times.

**Comment by dongjoon-hyun** [comment]
+1 for @HyukjinKwon 's decision.

**Comment by HyukjinKwon** [comment]
@yaooqinn would you mind pushing 3 empty commits individually so we can run the builds more in parallel?

**Comment by HyukjinKwon** [comment]
Okay, I found that hanging happens in another PR too. Let me merge this in.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by yaooqinn** [comment]
thanks~ @HyukjinKwon. And sorry for late reply

**Comment by HyukjinKwon** [comment]
Merged to branch-3.1.

It's okay. thanks for fixing this.

**Pull request closed without merging**
