### PR TITLE
[SPARK-38353][PYTHON] Instrument __enter__ and __exit__ magic methods for Pandas API on Spark

### PR DESCRIPTION
**Pull request by heyihong**
### What changes were proposed in this pull request?

- Add magic method \_\_enter\_\_ and \_\_exit\_\_ into **the special_function list**

### Why are the changes needed?

- Improve the usage data accuracy for **with statement** so that external \_\_enter\_\_ and \_\_exit\_\_ calls are captured instead of internal calls

For example, for the code below:

```python
pdf = pd.DataFrame(
    [(0.2, 0.3), (0.0, 0.6), (0.6, 0.0), (0.2, 0.1)], columns=["dogs", "cats"]
)
psdf = ps.from_pandas(pdf)

with psdf.spark.cache() as cached_df:
    self.assert_eq(isinstance(cached_df, CachedDataFrame), True)
    self.assert_eq(
        repr(cached_df.spark.storage_level), repr(StorageLevel(True, True, False, True))
    )
 ```

Pandas-on-Spark usage logger records the internal call [self.spark.unpersist()](https://github.com/apache/spark/blob/master/python/pyspark/pandas/frame.py#L12518) since \_\_enter\_\_ and \_\_exit\_\_ methods of [CachedDataFrame](https://github.com/apache/spark/blob/master/python/pyspark/pandas/frame.py#L12492) are not instrumented. 

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Existing unit tests

### CODE REVIEW

**Comment by itholic** [comment]
Could you elaborate more detail why do we need `__enter__` and `__exit__` to the usage log for pandas API on Spark ??

Why adding `__enter__` and `__exit__` improve the instrumentation accuracy for example ?

And could you also fill the description for JIRA ticket (https://issues.apache.org/jira/browse/SPARK-38353) ??

**Comment by HyukjinKwon** [comment]
cc @ueshin FYI

**Comment by heyihong** [comment]
> 

@itholic Sure, I updated both the PR and JIRA description about why do we need __enter__ and __exit__ to the usage log for pandas API on Spark with an example. Could you take another look when you time?

**Comment by itholic** [comment]
Thanks! I made some minor fix from the JIRA title and description, `pandas module` -> `pandas API on Spark`.

Could you address the nit below:
- `Pandas module` to `pandas API on Spark` in the PR title.
- `pandas usage logger` to `pandas-on-Spark usage logger` in the PR description.
?

Otherwise, LGTM.

**Review by itholic — APPROVED** [review]

**Review by HyukjinKwon — APPROVED** [review]

**Review by Yikun — APPROVED** [review]
Emm, PR's description is really unfriendly for me. lol, after take a deep look, it enables usage logger in Pandas on Spark for ContextManager usage, record in `__enter__` and `__exit__`.

LGTM.

**Comment by heyihong** [comment]
Merged to master and branch-3.2.

**Comment by HyukjinKwon** [comment]
Merged to master and branch-3.2.

:-).

**Comment by HyukjinKwon** [comment]
Congrats for being Apache Spark contributor @heyihong 🎊

**Comment by heyihong** [comment]
> Emm, PR's description is really unfriendly for me. lol, after take a deep look, it enables usage logger in Pandas on Spark for ContextManager usage, record in `__enter__` and `__exit__`.
> 
> LGTM.

This pr probably cannot fix the accuracy issue for functions with @contextmanager decorator. I am going to have another pull request to address that.

**Pull request closed without merging**
