### PR TITLE
[SPARK-33029][CORE][WEBUI] Fix the UI executor page incorrectly marking the driver as excluded

### PR DESCRIPTION
**Pull request by baohe-zhang**
### What changes were proposed in this pull request?
Filter out the driver entity when updating the exclusion status of live executors(including the driver), so the UI won't be marked as excluded in the UI even if the node that hosts the driver has been marked as excluded.

### Why are the changes needed?
Before this change, if we run spark with the standalone mode and with spark.blacklist.enabled=true. The driver will be marked as excluded when the host that hosts that driver has been marked as excluded. While it's incorrect because the exclude list feature will exclude executors only and the driver is still active.
image
After the fix, the driver won't be marked as excluded.
image

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Manual test. Reopen the UI and see the driver is no longer marked as excluded.

### CODE REVIEW

**Comment by baohe-zhang** [comment]
cc @tgravescs

**Comment by dongjoon-hyun** [comment]
To retriever GitHub Action, could you rebase to the master branch, @baohe-zhang ?

**Comment by baohe-zhang** [comment]
> To retriever GitHub Action, could you rebase to the master branch, @baohe-zhang ?

Done.

**Comment by tgravescs** [comment]
it looks like you need to fix up the test:

 [info] - executor node excludeOnFailure *** FAILED *** (220 milliseconds)

I think we had the file have the driver as excluded

**Comment by baohe-zhang** [comment]
@tgravescs The unit tests are fixed.

**Review by tgravescs — APPROVED** [review]
looks good pending tests run, the last one was unrelated so kicked it again.

**Comment by dongjoon-hyun** [comment]
Thank you, @baohe-zhang and @tgravescs .
cc @HyukjinKwon since this affects 3.0/3.1/3.2.

**Comment by HyukjinKwon** [comment]
Thanks @dongjoon-hyun. cc @gengliangwang and @sarutak FYI

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Merged to master/3.1.

**Comment by dongjoon-hyun** [comment]
Could you make a backport to branch-3.0, @baohe-zhang ?

**Comment by baohe-zhang** [comment]
@dongjoon-hyun Sure I will make a backport.

**Comment by dongjoon-hyun** [comment]
Thanks!

**Pull request closed without merging**
