### PR TITLE
[SPARK-7936] [SQL] Add configuration for initial size of hash for aggregation and limit

### PR DESCRIPTION
**Pull request by navis**
Added two configuration 
1. spark.sql.aggregation.hash.initSize : initialize size of hash. Applied to both(final, partial) aggregation
2. spark.sql.partial.aggregation.maxEntry : max size of hash for partial aggregation. should not be used for final aggregation

### CODE REVIEW

**Comment by JoshRosen** [comment]
For the initial size, you might also want to update this for the UnsafeFixedWidthAggregationMap on line 293-ish in the original file.

**Comment by yhuai** [comment]
ok to test

**Comment by navis** [comment]
Ran test in local env with init=5, limit=5 and passed all the (spark-sql) tests

**Comment by andrewor14** [comment]
@navis same comment on your other patch, I think the config should be under the `spark.sql.partialAggregation.*` namespace instead.

**Comment by JoshRosen** [comment]
@andrewor14 @rxin, is this configuration still useful now that we have the ability to spill during aggregation?

**Comment by rxin** [comment]
Probably not as useful now. @navis what do you think? If it no longer applies, we should close this pull request. Thanks!

**Pull request closed without merging**
