### PR TITLE
[SPARK-13982][SparkR] KMean's predict: Features output column name is an unclear, automatically genetared text

### PR DESCRIPTION
**Pull request by NarineK**
## What changes were proposed in this pull request?

In KMean's predict the output column name of the features was set to something like this: "vecAssembler_522ba59ea239__output", which is the default output column name of the "VectorAssembler".
I set a value "features" which is more intuitive and human readable
Before fix: 
    predict(model, training)
    DataFrame[Sepal_Length:double, Sepal_Width:double, Petal_Length:double, Petal_Width:double,    **vecAssembler_522ba59ea239__output: vector**, prediction:int]

After fix: 
    DataFrame[Sepal_Length:double, Sepal_Width:double, Petal_Length:double, Petal_Width:double,    **features:vector**, prediction:int]
## How was this patch tested?

All previous test cases pass!

### CODE REVIEW

**Comment by NarineK** [comment]
@yanboliang, would you ,please, take a look at this ?

**Comment by yanboliang** [comment]
@NarineK This looks good to me. But I think we should wait the discussion of SPARK-14147, I vote that it should not output feature column in SparkR.

**Comment by jkbradley** [comment]
It looks like [https://github.com/apache/spark/pull/12039] solved this.  Can you please verify and close this PR if so?  Thanks!

**Comment by NarineK** [comment]
thanks, will close this.

**Pull request closed without merging**
