### PR TITLE
[SPARK-32781[SQL] Non-ASCII characters are mistakenly omitted in the middle of intervals

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

This PR fails the interval values parsing when they contain non-ASCII characters which are silently omitted right now.

e.g. the case below should be invalid

```
select interval 'interval中文 1 day'
```

### Why are the changes needed?

bugfix, intervals should fail when containing invalid characters

### Does this PR introduce _any_ user-facing change?

yes, 

#### before

select interval 'interval中文 1 day'  results 1 day, now it fails with

```
org.apache.spark.sql.catalyst.parser.ParseException

Cannot parse the INTERVAL value: interval中文 1 day
```

### How was this patch tested?

new tests

### CODE REVIEW

**Comment by yaooqinn** [comment]
cc @cloud-fan @maropu @WangGuangxin, thanks, let's fix this before https://github.com/apache/spark/pull/29627 to reduce code diff in tests

**Comment by cloud-fan** [comment]
thanks, merging to master/3.0!

**Comment by cloud-fan** [comment]
@yaooqinn can you open a new PR for 3.0?

**Comment by yaooqinn** [comment]
@cloud-fan we need to backport 9a35b93c8a02939bf02437f47501d55223b6a283 first

**Pull request closed without merging**
