### PR TITLE
[SPARK-14181] TrainValidationSplit should have HasSeed

### PR DESCRIPTION
**Pull request by yinxusen**
https://issues.apache.org/jira/browse/SPARK-14181

TrainValidationSplit should have HasSeed for the random split of RDD. I also changed the random split from the RDD function to the DataFrame function.

### CODE REVIEW

**Comment by yinxusen** [comment]
test it please

**Comment by jkbradley** [comment]
Could you please modify a unit test to set the seed so we test this code path?

**Comment by yinxusen** [comment]
Sure, will do it soon.

**Comment by yinxusen** [comment]
@jkbradley Add seed into tests including test with linear/logistic regression and save/load.

**Comment by jkbradley** [comment]
LGTM
Merging with master
Thanks!

**Pull request closed without merging**
