### PR TITLE
[SPARK-39869][SQL][TESTS] Fix flaky hive - slow tests because of out-of-memory

### PR DESCRIPTION
**Pull request by HyukjinKwon**
### What changes were proposed in this pull request?

This PR adds some manual `System.gc`. I know enough that this doesn't guarantee the garbage collection and sounds somewhat funny but it works in my experience so far, and I did such hack in some places before.

### Why are the changes needed?

To deflake the tests.

### Does this PR introduce _any_ user-facing change?

No, dev and test-only.

### How was this patch tested?

CI in this PR should test it out.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Guys, I am merging this because the flakiness doesn't get reproduced in my fork, and I think we should fix these ASAP.

**Comment by HyukjinKwon** [comment]
posthoc reviews are welcome.

**Comment by HyukjinKwon** [comment]
Merged to master.

**Review by dongjoon-hyun — COMMENTED** [review]
+1, LGTM.
According to the test failure link in SPARK-39869, I support this best-effort approach.

**Comment by LuciferYang** [comment]
Late LGTM

**Pull request closed without merging**
