### PR TITLE
[SPARK-18286][ML] Add Scala/Java examples for MinHash and RandomProjection

### PR DESCRIPTION
**Pull request by jiayue-zhang**
## What changes were proposed in this pull request?

Add Scala/Java/Python examples for MinHash and RandomProjection

## How was this patch tested?

`./bin/run-example ml.MinHashExample`
`./bin/run-example ml.JavaMinHashExample`
`./bin/run-example ml.RandomProjectionExample`
`./bin/run-example ml.JavaRandomProjectionExample`

### CODE REVIEW

**Comment by yanboliang** [comment]
Jenkins add to whitelist

**Comment by yanboliang** [comment]
ok to test

**Comment by yanboliang** [comment]
@jkbradley @MLnick @srowen Could you help to add @bravo-zhang to whitelist? Thanks.

**Comment by srowen** [comment]
Jenkins add to whitelist

**Comment by srowen** [comment]
Looking good, excepting that there are no python examples?

**Comment by yanboliang** [comment]
@srowen The Python API is still under review at #15768. Would you mind to take a look? Thanks.

**Review by srowen — APPROVED** [review]
It looks OK to me, though given how much is being discussed in SPARK-18081 it might even be better to make sure this is consistent with its outcome, which also includes examples.

**Comment by jkbradley** [comment]
Linking [https://issues.apache.org/jira/browse/SPARK-18392] since it will alter the public API for LSH

**Comment by bravo-zhang** [comment]
This PR can be closed since https://github.com/apache/spark/pull/15795 has merged

**Comment by jkbradley** [comment]
Ah, thank you @bravo-zhang !

**Pull request closed without merging**
