### PR TITLE
[SPARK-7352] [MLLIB] ml.feature.IDF should rename minDocFreq to minDocCount

### PR DESCRIPTION
**Pull request by gweidner**
Renamed minDocFreq to minDocCount while maintaining case in 2 files:
mllib/src/main/scala/org/apache/spark/ml/feature/IDF.scala
mllib/src/test/scala/org/apache/spark/ml/feature/IDFSuite.scala

Also added 'number' in descriptions.  Note did not rename minDocFreq in the corresponding mllib versions (i.e., mllib\feature\IDF.scala).

### CODE REVIEW

**Comment by mengxr** [comment]
@gweidner Is `minDocFreq` incorrect here? Document frequency is well-defined term.

**Comment by gweidner** [comment]
Thank you Xiangrui for your time and feedback.  My fault for not questioning/researching in the JIRA before doing the pull request.  I just saw your comment referencing the Stanford link.

**Comment by jkbradley** [comment]
@gweidner  Could you please close this PR?  Thanks regardless!

**Comment by gweidner** [comment]
Sure thing and sorry for taking up both of your time with a review.  I should have done more due diligence in the JIRA first.  The code changes quickly and my fault for rushing a PR.  Thanks again for the information!

**Pull request closed without merging**
