### PR TITLE
[SPARK-32160][CORE][PYSPARK][3.0] Add a config to switch allow/disallow to create SparkContext in executors.

### PR DESCRIPTION
**Pull request by ueshin**
### What changes were proposed in this pull request?

This is a backport of #29278, but with allowing to create `SparkContext` in executors by default.

This PR adds a config to switch allow/disallow to create `SparkContext` in executors.

- `spark.driver.allowSparkContextInExecutors`

### Why are the changes needed?

Some users or libraries actually create `SparkContext` in executors.
We shouldn't break their workloads.

### Does this PR introduce _any_ user-facing change?

Yes, users will be able to disallow to create `SparkContext` in executors with the config disabled.

### How was this patch tested?

More tests are added.

### CODE REVIEW

**Comment by ueshin** [comment]
Jenkins, retest this please.

**Comment by ueshin** [comment]
Jenkins, retest this please.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
Merged to branch-3.0.

**Comment by dongjoon-hyun** [comment]
For the configuration namespace, I have a question about that. Please see the original PR.
https://github.com/apache/spark/pull/29278#pullrequestreview-460256338

**Comment by HyukjinKwon** [comment]
Yeah, it makes sense. Thanks for pointing that out.

**Pull request closed without merging**
