### PR TITLE
[SPARK-38194][FOLLOWUP] Update executor config description for memoryOverheadFactor

### PR DESCRIPTION
**Pull request by Kimahriman**
Follow up for https://github.com/apache/spark/pull/35912#pullrequestreview-915755215, update the executor memoryOverheadFactor to mention the 0.4 default for non-jvm jobs as well.

### What changes were proposed in this pull request?

Doc update

### Why are the changes needed?

To clarify new configs

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Existing UTs

### CODE REVIEW

**Comment by Kimahriman** [comment]
@tgravescs if the language sounds good I'll open a 3.3 PR

**Comment by Yikun** [comment]
https://github.com/apache/spark/blame/master/docs/running-on-kubernetes.md#L362

Looks like we also missed a change in k8s doc, could you also change `spark.kubernetes.memoryOverheadFactor` to `spark.{driver, executor}.memoryOverheadFactor`?

**Comment by tgravescs** [comment]
yeah looks good, other then the place @Yikun  pointed out, if you can update that it would be great.

**Review by srowen — APPROVED** [review]

**Comment by Kimahriman** [comment]
Updated that as well

**Review by tgravescs — APPROVED** [review]

**Review by Yikun — APPROVED** [review]
Thanks! LGTM

**Comment by srowen** [comment]
Merged to master / 3.3 (to match what this follows up)

**Comment by Kimahriman** [comment]
Thanks, wasn't sure if I was going to need to open a separate PR for that

**Comment by Yikun** [comment]
@Kimahriman no need anymore :)

In general, committer will help you backport commits to target branches if no conflict with target branches.

**Pull request closed without merging**
