### PR TITLE
[SPARK-9924] [WEB UI] Don't schedule checkForLogs while some of them …

### PR DESCRIPTION
**Pull request by tgravescs**
Cherry-pick this to branch 1.5.

### CODE REVIEW

**Comment by vanzin** [comment]
I didn't notice any changes from the original, is that right? LGTM either way.

**Comment by tgravescs** [comment]
yep, no changes just cherry-pick... I don't know that I needed the pr but figured would put it up anywa

**Comment by vanzin** [comment]
failure is not related, but just in case. retest this please

**Comment by vanzin** [comment]
wtf?

**Comment by vanzin** [comment]
branch-1.5 should be fixed now. retest this please

**Comment by vanzin** [comment]
Hmm seems like github wasn't synchronized yet. retest this please.

**Comment by tgravescs** [comment]
retest this please

**Comment by vanzin** [comment]
merging

**Comment by vanzin** [comment]
@tgravescs could you close this? I don't think it's closed automatically since it's in a branch. Thanks!

**Comment by tgravescs** [comment]
thanks @vanzin, closing

**Pull request closed without merging**
