### PR TITLE
[SPARK-3562]Periodic cleanup event logs

### PR DESCRIPTION
**Pull request by viper-kun**
link #2391

### CODE REVIEW

**Comment by suyanNone** [comment]
Is thi patch ok to merge?

**Comment by vanzin** [comment]
I'm not a committer so I can't merge the patch. But it has merge conflicts now, so that at least needs to be fixed.

**Comment by suyanNone** [comment]
@vanzin  = =! I got it,  sigh~

**Comment by viper-kun** [comment]
I have file a new pr #4214

**Comment by vanzin** [comment]
@viper-kun could you close this one in that case? thanks!

**Pull request closed without merging**
