### PR TITLE
[SPARK-21357][DStreams] FileInputDStream not remove out of date RDD

### PR DESCRIPTION
**Pull request by xiaobaimao-linux**
## What changes were proposed in this pull request?

```DStreams
         class FileInputDStream

 [line 162]   protected[streaming] override def clearMetadata(time: Time) {
    batchTimeToSelectedFiles.synchronized {
      val oldFiles = batchTimeToSelectedFiles.filter(_._1 < (time - rememberDuration))
      batchTimeToSelectedFiles --= oldFiles.keys

```
The above code does not remove the old generatedRDDs. "super.clearMetadata(time)" was added to the beginning of clearMetadata to remove the old generatedRDDs.

## How was this patch tested?

At the end of clearMetadata, the testing code (print the number of generatedRDDs) was added to check the old RDDS were removed manually.

### CODE REVIEW

**Comment by srowen** [comment]
Seems reasonable, but, I am sort of not sure why it hasn't come up before. @tdas?

**Comment by shaofei007** [comment]
@tdas
 how do you think about this PR please?

@asfgit
Can we close it please?

**Comment by srowen** [comment]
@shaofei007 I actually think your fix is correct, so I wouldn't close it. The comment says: `  /** Clear the old time-to-files mappings along with old RDDs */` But only the superclass method clears the old RDDs. In the absence of any comments to the contrary, I'd merge this, at least to master

**Review by srowen — APPROVED** [review]

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
