### PR TITLE
[SPARK-8677][SQL] Fix non-terminating decimal expansion for decimal divide operation

### PR DESCRIPTION
**Pull request by viirya**
JIRA: https://issues.apache.org/jira/browse/SPARK-8677

### CODE REVIEW

**Comment by davies** [comment]
LGTM, merging this into master, thanks!

**Comment by JihongMA** [comment]
Thanks for fixing this division problem.  after rebasing with the fix, I noticed one more issue w.r.t the accuracy of Decimal computation.

scala> val aa = Decimal(2) / Decimal(3);
aa: org.apache.spark.sql.types.Decimal = 1

when a Decimal is defined as Decimal.Unlimited, if we inherit the scale value of the result from its parent, we will see big accuracy issue as shown in the above example output, once we go coupe round of division over decimal data vs. double data. below is a sample output from my run while testing my code change, as you can see the result is far off from its double counterpart,  since you guys have been fixing issue around Decimal, would like to see if we can work out a more proper fix in this context, is there guideline about precision/scale settings for Decimal.Unlimited when it comes to division operation? 

10:27:46.042 WARN org.apache.spark.sql.catalyst.expressions.CombinePartialStdFunction: COMBINE STDDEV DOUBLE-------4.0 , 0.8VALUE
10:27:46.137 WARN org.apache.spark.sql.catalyst.expressions.CombinePartialStdFunction: COMBINE STDDEV DECIMAL-------4.29000 , 0.858VALUE

**Comment by viirya** [comment]
@JihongMA Thanks for reporting this.
As I tested, this behavior is the same as for Java's BigDecimal. So I am wondering if this is really a problem to fix? Because when you create `Decimal(2)` or `java.math.BigDecimal(2)`, actually you mean to create it with precision 1 and scale 0, right? So isn't that the result can be expected?

    scala> val t = new java.math.BigDecimal(2)
    t: java.math.BigDecimal = 2
    scala> val s = new java.math.BigDecimal(3)
    s: java.math.BigDecimal = 3
    scala> t.divide(s)
    java.lang.ArithmeticException: Non-terminating decimal expansion; no exact representable decimal result.
      at java.math.BigDecimal.divide(BigDecimal.java:1616)
      ... 33 elided
    scala> t.divide(s, BigDecimal.RoundingMode.HALF_UP.id)
    res24: java.math.BigDecimal = 1

**Comment by JihongMA** [comment]
@viirya  I have opened a JIRA https://issues.apache.org/jira/browse/SPARK-8800, and have put more detailed specification I found how to handle decimal division in the case of Decimal.Unlimited type.   I propose we should return exact result whenever possible,  in the case of infinite long precision/scale case, fall back to the limit 38 or whatever as what hive has done. 

here is another example where we should return 0.125 instead of 0

scala> val aa = Decimal(1) /Decimal(8)
aa: org.apache.spark.sql.types.Decimal = 0

**Pull request closed without merging**
