### PR TITLE
[SPARK-33342][WEBUI] fix the wrong url and display name of blocking thread in threadDump page.

### PR DESCRIPTION
**Pull request by echohlne**
### What changes were proposed in this pull request?
fix the wrong url and display name of blocking thread in threadDump page.
The blockingThreadId variable passed to the page should be of string type instead of Option type.

### Why are the changes needed?
blocking threadId in the ui page is not displayed well, and the corresponding  url cannot be redirected normally

### Does this PR introduce _any_ user-facing change?
NO

### How was this patch tested?
The pr  only involves minor changes to the page and does not affect other functions, 
The manual test results are as follows. The thread name displayed on the page is correct, and you can click on the URL to jump to the corresponding url

shows_ok

### CODE REVIEW

**Comment by akiyamaneko** [comment]
friendly ping @gengliangwang

**Comment by srowen** [comment]
So the value in the URL is something like "Some(23235)"? yeah that's wrong, good fix.

**Comment by srowen** [comment]
Jenkins test this please

**Review by gengliangwang — APPROVED** [review]
LGTM, thanks for the fix

**Comment by gengliangwang** [comment]
Thanks, merging to master

**Pull request closed without merging**
