### PR TITLE
[SPARK-42821][SQL] Remove unused parameters in splitFiles methods

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to remove unused parameters in PartitionedFileUtil.splitFiles methods

### Why are the changes needed?
Make the code more concise.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA.

### CODE REVIEW

**Comment by LuciferYang** [comment]
This function a bit special, It was discussed a long time ago ...
https://github.com/apache/spark/pull/37862#issuecomment-1249419779

**Comment by panbingkun** [comment]
> This function a bit special, It was discussed a long time ago ... [#37862 (comment)](https://github.com/apache/spark/pull/37862#issuecomment-1249419779)

If it's a public API, we should mark it; If not, we should correct our problem.

**Comment by LuciferYang** [comment]
Personally, I think it's definitely possible to change it in Spark 4.0, but I wasn't sure before.

**Comment by srowen** [comment]
Not a public API but probably not worth 'fixing' before spark 4 indeed

**Comment by panbingkun** [comment]
> Not a public API but probably not worth 'fixing' before spark 4 indeed

OK, Let's fix it after spark 4 release.
I will close it.

**Review by LuciferYang — APPROVED** [review]
+1, LGTM if test pass

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
