### PR TITLE
Exclude httpFileServer for local operation.

### PR DESCRIPTION
**Pull request by prb**
This would also make a fine configuration parameter.

### CODE REVIEW

**Comment by prb** [comment]
https://issues.apache.org/jira/browse/SPARK-5340

**Comment by JoshRosen** [comment]
Jenkins, this is ok to test.

**Comment by JoshRosen** [comment]
I don't think that you can just null out `httpFileServer` in local mode because methods like `addJar` call methods on it and we have to support those features in local mode (even though they're effectively no-ops) so that jobs designed to run on clusters can be tested locally.

Can you explain your motivation for disabling this in local mode?

**Comment by prb** [comment]
I have Spark embedded within a web service that is using Jetty 9, so the classes for Jetty (along with those for Jersey) are unavailable.  The system works with this change; I can chase some of the plumbing if there are a known set of touchpoints.

I would argue that the right thing to do is to make all of the non-computation pieces of the system possible to disable conveniently.  (This is a selfish wish for people like me who want to use Spark as a library and not a standalone server/service.)  That is already the case with the UI and the pretty (but gratuitous) status output.

**Comment by JoshRosen** [comment]
@prb Can you see whether #3130 (shading Jetty in Spark) addresses your use-case?

**Comment by prb** [comment]
The approach in #3130 would probably work for me.   As Spark evolves, it would be nice to have the perspective that Spark is a library that other systems (including the various decorations of Spark with UI, etc.) can build on.  (I bumped my head on logging initialization issues a while back, too...)

**Comment by JoshRosen** [comment]
I don't think that we want to add a mechanism to disable `httpFileServer` since it's necessary for `addFile` / `addJar` to work correctly.

If you'd like to propose new features, could you file issues on the Spark JIRA (https://issues.apache.org/jira/browse/SPARK), since that's the best place to have feature discussions?

Since it looks like #3130 will address this and because we can't easily disable `httpFileServer`, do you mind closing this PR?  Thanks!

**Comment by prb** [comment]
Yup.  I'll close it up; thanks for the discussion.  FWIW, I'd still look at the dependence on `httpFileServer` as a non-feature if not an outright bug.  (I can think of lots of reasons (e.g., security) not to want a system to spin-up an HTTP service on a randomly assigned port.)

**Pull request closed without merging**
