### PR TITLE
[SPARK-8835][Streaming] Provide pluggable Congestion Strategies for Receiver-based Streams

### PR DESCRIPTION
**Pull request by huitseeker**
The new (destructive) strategies avoid leaving elements in the TCP buffer, leading to breakages at the sender level when this buffer finally drops them.

### CODE REVIEW

**Comment by huitseeker** [comment]
Pinging @srowen for an 'ok to test'.
Also, if you're asking yourself why some tests are in "ignore" : the answer is in the commit messages.

**Comment by tdas** [comment]
ok to test.

**Comment by tdas** [comment]
I think this requires a good design doc for me to make sense of the overall idea, and discuss the design. Its hard to discuss the design in the PR.

**Comment by rxin** [comment]
Thanks for the pull request. I'm going through a list of pull requests to cut them down since the sheer number is breaking some of the tooling we have. Due to lack of activity on this pull request, I'm going to push a commit to close it. Feel free to reopen it or create a new one.

**Pull request closed without merging**
