### PR TITLE
[SPARK-32106][SQL][FOLLOWUP] Fix flaky tests in transform.sql

### PR DESCRIPTION
**Pull request by maropu**
### What changes were proposed in this pull request?

This PR intends to fix flaky GitHub Actions (GA) tests below in `transform.sql` (this flakiness does not seem to happen in the Jenkins tests):
- https://github.com/apache/spark/runs/1592987501
- https://github.com/apache/spark/runs/1593196242
- https://github.com/apache/spark/runs/1595496305
- https://github.com/apache/spark/runs/1596309555

This is because the error message is different between test runs in GA (the error message seems to be truncated indeterministically) ,e.g.,
```
# https://github.com/apache/spark/runs/1592987501
Expected "...h status 127. Error:[ /bin/bash: some_non_existent_command: command not found]", but got "...h status 127. Error:[]" Result did not match for query #2

# https://github.com/apache/spark/runs/1593196242
Expected "...istent_command: comm[and not found]", but got "...istent_command: comm[]" Result did not match for query #2
```
The root cause of this indeterministic behaviour happening only in GA is not clear though, this test throws SparkException consistently even in GA. So, this PR proposes to make the test just check if it will be thrown when running it.

This PR comes from the @dongjoon-hyun comment: https://github.com/apache/spark/pull/29414/files#r547414513

### Why are the changes needed?

Bugfix.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Added tests.

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Could you describe what was the root cause of the flakiness, @maropu ?

**Comment by AngersZhuuuu** [comment]
Seems some subprocess didn't write error message to stderrBuffer in `checkFailureAndPropagate`

**Comment by maropu** [comment]
> Seems some subprocess didn't write error message to stderrBuffer in checkFailureAndPropagate

hm, that might be so because the error message seems to be truncated indeterministically. But, it seems this flakiness happens only in GA tests. So, I'm not really sure about why...

**Comment by AngersZhuuuu** [comment]
> > Seems some subprocess didn't write error message to stderrBuffer in checkFailureAndPropagate
> 
> hm, that might be so because the error message seems to be truncated indeterministically. But, it seems this flakiness happens only in GA tests. So, I'm not really sure about why...

Not sure +1...

**Comment by maropu** [comment]
> Could you describe what was the root cause of the flakiness, @maropu ?

Yea, thanks for the comment, @dongjoon-hyun and I've updated the description. I actually don't know what the root cause is now. So, the current approach of this PR just rewrote the test in a safer way. Any suggestion?

**Comment by dongjoon-hyun** [comment]
Then, could you add a few empty commits in this PR to verify the stableness, @maropu ?

**Review by HyukjinKwon — APPROVED** [review]
Looks good. +1 for @dongjoon-hyun's suggestion to trigger few more times with empty commits.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. (Pending GitHub Action `sql - slow tests` results)
Thank you for the investigation and this quick fix.

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by maropu** [comment]
Thanks, all!

**Pull request closed without merging**
