### PR TITLE
[SPARK-7565][SQL] Also consider java string in writePrimitive for StringType

### PR DESCRIPTION
**Pull request by viirya**
JIRA: https://issues.apache.org/jira/browse/SPARK-7565

### CODE REVIEW

**Comment by yhuai** [comment]
I feel the problem is the json parser not the parquet writer. We should convert the string to UTF8Stirng during the parsing process. I will take a look.

**Comment by yhuai** [comment]
https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/json/JacksonParser.scala#L150-160 looks suspicious. Also, https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/json/JacksonParser.scala#L179-188 looks like the same bug.

**Comment by davies** [comment]
@yhuai @JoshRosen  I will create another PR to fix these.

**Comment by davies** [comment]
This will be fixed by https://github.com/apache/spark/pull/6299

**Comment by yhuai** [comment]
@viirya Thank you for the fix and test cases! However, seems the problem is the JSON parser part instead of the parquet writer side (see our above discussion). @davies has opened #6299 for the JSON parser part fix. How about we close this one?

**Comment by viirya** [comment]
Sure.

**Pull request closed without merging**
