### PR TITLE
[SPARK-12934] use try-with-resources for streams

### PR DESCRIPTION
**Pull request by tedyu**
@liancheng please take a look

### CODE REVIEW

**Comment by zsxwing** [comment]
I guess the caller should close the stream?

**Comment by tedyu** [comment]
Looking at current code, that is not the case.

**Comment by zsxwing** [comment]
Yeah, it's because only ByteArrayInputStream/ByteArrayOutputStream is used. I think we should document that who should close the stream.

**Comment by tedyu** [comment]
```
ERROR: Timeout after 15 minutes
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from https://github.com/apache/spark.git
```

**Comment by tedyu** [comment]
Jenkins, test this please.

**Comment by liancheng** [comment]
Thanks, LGTM. I'm merging this.

**Pull request closed without merging**
