### PR TITLE
[SPARK-24533] Typesafe rebranded to lightbend. Changing the build downloads path

### PR DESCRIPTION
**Pull request by redsanket**
## What changes were proposed in this pull request?
Typesafe has rebranded to lightbend. Just changing the downloads path to avoid redirection

## How was this patch tested?
Tested by running build/mvn -DskipTests package

Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Comment by tgravescs** [comment]
ok to test

**Comment by tgravescs** [comment]
test this please

**Comment by tgravescs** [comment]
+1, lgtm seems downloads.typesafe.com just redirects to downloads.lightbend.com now.

**Comment by vanzin** [comment]
Merging to master.

**Pull request closed without merging**
