### PR TITLE
[SPARK-45113][PYTHON][DOCS] Refine docstrings of `collect_list/collect_set`

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr refine docstring of `collect_list/collect_set` and add some new examples.

### Why are the changes needed?
To improve PySpark documentation

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass Github Actions

### Was this patch authored or co-authored using generative AI tooling?
No

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]
LGTM if tests pass

**Comment by LuciferYang** [comment]
Yeah, all test passed

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by zhengruifeng** [comment]
late lgtm

**Comment by LuciferYang** [comment]
Thanks @HyukjinKwon @zhengruifeng

**Pull request closed without merging**
