### PR TITLE
[SPARK-45847][SQL][TESTS] CliSuite flakiness due to non-sequential guarantee for stdout&stderr

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

In CliSuite, This PR adds a retry for tests that write errors to STDERR. 

### Why are the changes needed?

To fix flakiness tests as below
https://github.com/chenhao-db/apache-spark/actions/runs/6791437199/job/18463313766
https://github.com/dongjoon-hyun/spark/actions/runs/6753670527/job/18361206900

```sql
[info]   Spark master: local, Application Id: local-1699402393189
[info]   spark-sql> /* SELECT /*+ HINT() 4; */;
[info]   
[info]   [PARSE_SYNTAX_ERROR] Syntax error at or near ';'. SQLSTATE: 42601 (line 1, pos 26)
[info]   
[info]   == SQL ==
[info]   /* SELECT /*+ HINT() 4; */;
[info]   --------------------------^^^
[info]   
[info]   spark-sql> /* SELECT /*+ HINT() 4; */ SELECT 1;
[info]   1
[info]   Time taken: 1.499 seconds, Fetched 1 row(s)
[info]   
[info]   [UNCLOSED_BRACKETED_COMMENT] Found an unclosed bracketed comment. Please, append */ at the end of the comment. SQLSTATE: 42601
[info]   == SQL ==
[info]   /* Here is a unclosed bracketed comment SELECT 1;
[info]   spark-sql> /* Here is a unclosed bracketed comment SELECT 1;
[info]   spark-sql> /* SELECT /*+ HINT() */ 4; */;
[info]   spark-sql> 
```

As you can see the fragment above, the query on the 3rd line from the bottom, came from STDOUT, was printed later than its error output, came from STDERR.

In this scenario, the error output would not match anything and would simply go unnoticed. Finally, timed out and failed.

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

existing tests and CI

### Was this patch authored or co-authored using generative AI tooling?

no

### CODE REVIEW

**Comment by yaooqinn** [comment]
cc @cloud-fan @dongjoon-hyun @LuciferYang

**Review by LuciferYang — APPROVED** [review]

**Review by cloud-fan — APPROVED** [review]

**Comment by yaooqinn** [comment]
Thank you, merged to master and 3.5

**Comment by LuciferYang** [comment]
> Thank you, merged to master and 3.5

https://github.com/xieshuaihu/spark/actions/runs/6809263793/job/18515214023

Seems also need to pick to branch-3.4

**Comment by yaooqinn** [comment]
Thanks, @LuciferYang, cherry-picked to 3.4

**Pull request closed without merging**
