### PR TITLE
[SPARK-6763][SQL] Add CountMinSketch to DataFrame for estimating frequencies

### PR DESCRIPTION
**Pull request by viirya**
JIRA: https://issues.apache.org/jira/browse/SPARK-6763

### CODE REVIEW

**Comment by rxin** [comment]
Can you give an example of what your returned DataFrame looks like?

**Comment by viirya** [comment]
For input DataFrame with a column name "A":

      A
      1
     10
      5
     10
      8

The returned DataFrame has two columns "A" and "A_freq" where "A" lists the uniques values of the column "A" in the input DataFrame, and "A_freq" lists the corresponding minimum counts.

      A       A_freq
      1          1   
     10          2
      5          1
      8          1

**Comment by viirya** [comment]
@rxin Is it good to have this as an aggregation function too? If so, I will update it too.

**Comment by MLnick** [comment]
@rxin @hvanhovell @yhuai  should this be synced up with #8362 in terms of implementation approach?

**Comment by hvanhovell** [comment]
@MLnick I guess it depends. The other ```dataframe.stat``` functions have not been implemented as UDAFs, so this is not nessecary. However I do think that CMS is a usefull UDAF to have.

**Comment by rxin** [comment]
I'm going to close this pull request. If this is still relevant and you are interested in pushing it forward, please open a new pull request. Thanks!

**Pull request closed without merging**
