### PR TITLE
[Minor][YARN] Move YarnSchedulerBackendSuite to resource-managers/yarn directory.

### PR DESCRIPTION
**Pull request by yanboliang**
## What changes were proposed in this pull request?
#16092 moves YARN resource manager related code to resource-managers/yarn directory. The test case ```YarnSchedulerBackendSuite``` was added after that but with the wrong place. I move it to correct directory in this PR.

## How was this patch tested?
Existing test.

### CODE REVIEW

**Comment by yanboliang** [comment]
Jenkins, test this please.

**Comment by yanboliang** [comment]
cc @rxin @vanzin @srowen

**Comment by rxin** [comment]
LGTM

**Review by srowen — APPROVED** [review]

**Comment by yanboliang** [comment]
Merged into master. Thanks for reviewing.

**Pull request closed without merging**
