### PR TITLE
[SPARK-12858] [CORE] Remove duplicated code in metrics

### PR DESCRIPTION
**Pull request by BenFradet**
I noticed there is some duplicated code in the sinks regarding the poll period.
Also, parts of the metrics.properties template were unclear.
This PR aims to fix both issues.

### CODE REVIEW

**Comment by BenFradet** [comment]
I'll add a test suite for the HasPollingPeriod trait.

**Comment by BenFradet** [comment]
The reason for the failed build is not reflected in the code change, weird.
Will relaunch a build once I'm done with the test suite.

**Comment by BenFradet** [comment]
Ping @JoshRosen and @rxin

**Comment by JoshRosen** [comment]
FYI, I think the review of the code changes here is going to take a low priority:

- AFAIK this isn't fixing any urgent bugs.
- Some of these metrics sinks aren't well tested, so doing big refactorings to them carries a lot of risk. Thus, we might need a more careful review to make sure this doesn't break anything.

**Comment by BenFradet** [comment]
Yup, no problem, thanks for the update.

**Comment by BenFradet** [comment]
Do you think it'd be worth investigating if tests are feasible?

**Comment by JoshRosen** [comment]
Suggestion: we can merge the documentation fixes separately. I'm not especially motivated to review these code changes if they're just internal cleanup / refactoring, since this isn't a high-activity component and I'd prefer to just leave known working code in place.

Therefore, here's my proposal:

- Close this PR and open a new one which contains only documentation fixes. This can be merged quickly.
- If there are bugfixes / behavior changes, submit _only_ those changes as separate small and easy to review PRs.
- Don't do the giant refactoring for refactoring's sake; it's not worth the risk + review time.

**Comment by BenFradet** [comment]
Sure.
I was just curious about how the metrics worked and stumbled upon this.
My thinking was that it'd become clumsy to maintain 5 times the same code in the long run.

Anyway, should I repurpose the jira or create another one?

**Comment by JoshRosen** [comment]
Create new JIRAs as you submit PRs.

**Pull request closed without merging**
