### PR TITLE
[Minor][Build] Remove empty tags in parent pom.xml

### PR DESCRIPTION
**Pull request by keypointt**
## What changes were proposed in this pull request?

Remove empty tags in parent pom.xml

When I was working on another ticket and scanning code files randomly, I found these empty tags. I'm not sure if it is needed, or these empty tags are left on purpose.

If this is not a valid PR, please just let me know and I'll close it.
## How was this patch tested?

Tested by re-building the project on my local machine.

### CODE REVIEW

**Comment by srowen** [comment]
No, I don't think any of these can be removed. Why would you assume an empty tag is meaningless? that's not true in any XML format.

**Comment by keypointt** [comment]
Hi Sean do you mind to explain a bit the meaning of the empty tags?

Is it mean these empty paras can be set via command line like `mvn compile -paraA -paraB`?

I googled around and didn't find a satisfying answer. Thanks a lot

**Comment by srowen** [comment]
The first one sets a property with an empty value. I think this is necessary to refer to it in the Maven build even if it doesn't have a default value. The rest -- refer to the plugin docs for that they mean. Empty tags are perfectly meaningful in XML.

**Comment by keypointt** [comment]
I get it now, thank you Sean for explaining this 👍

**Pull request closed without merging**
