### PR TITLE
[SPARK-17499][SPARKR][FOLLOWUP] Check null first for layers in spark.mlp to avoid warnings in test results

### PR DESCRIPTION
**Pull request by HyukjinKwon**
## What changes were proposed in this pull request?

Some tests in `test_mllib.r` are as below:

``` r
expect_error(spark.mlp(df, layers = NULL), "layers must be a integer vector with length > 1.")
expect_error(spark.mlp(df, layers = c()), "layers must be a integer vector with length > 1.")
```

The problem is, `is.na` is internally called via `na.omit` in `spark.mlp` which causes warnings as below:

```
Warnings -----------------------------------------------------------------------
1. spark.mlp (@test_mllib.R#400) - is.na() applied to non-(list or vector) of type 'NULL'

2. spark.mlp (@test_mllib.R#401) - is.na() applied to non-(list or vector) of type 'NULL'
```
## How was this patch tested?

Manually tested. Also, Jenkins tests and AppVeyor.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @felixcheung and @shivaram

**Comment by shivaram** [comment]
Thanks @HyukjinKwon  - Fix looks good. But isn't it better to do the check before we do the na.omit / as.integer ? Or will that miss some cases ?

**Comment by HyukjinKwon** [comment]
Sure, I trust your judgement. Coould you please guide me please?  (Is there a common logic to check this?)

**Comment by HyukjinKwon** [comment]
Sorry, I left and removed a wring comment. Please ignore that. Sure, I will rather try to add an explicit check before that.

**Comment by felixcheung** [comment]
Hmm, thanks.

I thought we had "turn warning to error" in test - any idea why these didn't error out in the PR before it was merged?

**Comment by HyukjinKwon** [comment]
Sure, I will take a look for this.

**Comment by HyukjinKwon** [comment]
Hm.. I took some issues in `testthat` and I think that is an expected behaviour(?). (Please take a look for the issue 224 in `testthat`). I asked a question to the author of that library.

Meanwhile, I will try to fix this one first.

**Comment by felixcheung** [comment]
you mean issue 224 of testthat on github? doesn't seem like it's related?

**Comment by felixcheung** [comment]
change LGTM to me.

**Comment by HyukjinKwon** [comment]
Oh I meant 244.

**Comment by felixcheung** [comment]
According to this fix https://github.com/hadley/testthat/commit/64036395cf0f2556cdd181dddb219e498f4be370
this is fixed in testthat v1.0.2? I recall we are running 1.1.0 in Jenkins?

**Comment by HyukjinKwon** [comment]
Hm. Actually, I was wondering if it really works and I am still looking here and there.

My `testthat` version in my local is `v.1.0.2`. but it seems not working as below:

```r
> packageVersion("testthat")
[1] ‘1.0.2’
> library(testthat)
> test_that('warning bug', expect_error({options(warn = 2); warning('toto')}) )
Error: Test failed: 'warning bug'
* {
    ...
} did not throw an error.
```

If it is really fixed, I think this should not fail. hm.. am I missing something?

**Comment by felixcheung** [comment]
It might be slightly different how `expect_error` would handle that, I was more thinking
```
test_that('warning bug', options(warn = 2); warning('toto') )
```

should fail the test.

I think we could look into that separately.
I'll merge this PR today.

**Comment by HyukjinKwon** [comment]
Sure, filed in https://issues.apache.org/jira/browse/SPARK-17674

**Pull request closed without merging**
