### PR TITLE
Add role and checkpoint support for Mesos backend

### PR DESCRIPTION
**Pull request by iven**
This commit also changes Mesos version to 0.14.0, which is the earliest
version supporting these features.

### CODE REVIEW

**Comment by andrewor14** [comment]
Hi @ash211 @tnachen @iven what is the state of this PR? It seems very outdated since some of the discussion revolves around Spark 0.9. Maybe we should close this issue for now and open another PR associated with SPARK-4899 when there is more interest in the issue.

**Comment by tnachen** [comment]
@andrewor14 I agree to close this for now, we can work on this later when it's needed.

**Comment by srowen** [comment]
Mind closing this PR @iven ?

**Comment by iven** [comment]
@srowen It's OK. I'm not currently using Spark.

**Pull request closed without merging**
