### PR TITLE
Revert [SPARK-27300][GRAPH] Add Spark Graph modules and dependencies

### PR DESCRIPTION
**Pull request by srowen**
This reverts commit 709387d66003b9f9c847488c101156a71231eddf.

See https://issues.apache.org/jira/browse/SPARK-27300?focusedCommentId=16990048&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16990048 and previous mailing list discussions.

### What changes were proposed in this pull request?

Revert the addition of skeleton graph API modules for Spark 3.0.

### Why are the changes needed?

It does not appear that content will be added to the module for Spark 3, so I propose avoiding committing to the modules, which are no-ops now, in the upcoming major 3.0 release.

### Does this PR introduce any user-facing change?

No, the modules were not released.

### How was this patch tested?

Existing tests, but mostly N/A.

### CODE REVIEW

**Comment by srowen** [comment]
CC @s1ck @dongjoon-hyun @mengxr @rxin

**Comment by dongjoon-hyun** [comment]
Although I merged the original PR, I'm +1 for @srowen 's decision according to the current AS-IS status.

**Review by dongjoon-hyun — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
This is a dependency and module PR and all build combination test passed by GitHub Action.
Jenkins UT result is irrelevant because there was no added tests before.
Merged to master.

**Comment by s1ck** [comment]
Thx @srowen for picking this up. I closed the related PRs ... Farewell!

**Pull request closed without merging**
