### PR TITLE
Revert "[SPARK-29721][SQL] Prune unnecessary nested fields from Generate without Project

### PR DESCRIPTION
**Pull request by viirya**
This reverts commit a0e63b61e7c5d55ae2a9213b95ab1e87ac7c203c.

### What changes were proposed in this pull request?

This reverts the patch at #26978 based on @gatorsmile's suggestion.

### Why are the changes needed?

Original patch #26978 has not considered a corner case. We may need to put more time on ensuring we can cover all cases.

### Does this PR introduce any user-facing change?

No

### How was this patch tested?

Unit test.

### CODE REVIEW

**Comment by viirya** [comment]
cc @gatorsmile

**Comment by viirya** [comment]
retest this please

**Review by gatorsmile — APPROVED** [review]
LGTM

Thanks for your work!

**Comment by dongjoon-hyun** [comment]
Late LGTM.

**Comment by dongjoon-hyun** [comment]
And 'branch-3.0'?

**Comment by dongjoon-hyun** [comment]
Hi, @gatorsmile . When you reopen this JIRA issue, please remove `Fix Version`, too.

**Comment by dongjoon-hyun** [comment]
I'll backport this to `branch-3.0` and remove `Fix Version=3.0` from the JIRA.

**Pull request closed without merging**
