### PR TITLE
[SPARK-13437][SQL] Introduce InternalColumn and MutableColumn

### PR DESCRIPTION
**Pull request by kiszk**
## What changes were proposed in this pull request?

This PR introduce `InternalColumn` and `MutableColumn` to abstract a columnar storage at code generation as an analogy with `InternalRow`. This would allow us to use different implementations of column storage.
For now, `ColumnarVector` extends `InternalRow` and `MutableColumn`.
## How was the this patch tested?

Succeeded to compile

### CODE REVIEW

**Comment by nongli** [comment]
What's the value of doing this?

**Comment by kiszk** [comment]
There are three values of doing this.

a. **Make APIs clean and readable**: A mandatory set ofAPIs are well represented by introducing such an abstract class. The values of a. is already shown by introducing ``InternalRow``

b. **Abstract implementation of columnar storage**: To use accessors defined in an abstract class, generated code and runtime code for operations can be portable among different types of columnar storage. For example, ``ColumnVector``, ``ColumnAccessor``, and possible Apache Arrow.
In the current  generated code of whole stage code gen, accesses to elements is well abstracted. The generated code does not take care of an actual class of ``InternalRow``.
The values of b. is already shown by introducing ``InternalRow``

````
    protected void processNext() throws java.io.IOException {
      while (input.hasNext()) {
        InternalRow inputadapter_row = (InternalRow) input.next();
        boolean inputadapter_isNull = inputadapter_row.isNullAt(0)
        ...
````

c. **Do not degrade runtime performance**: If we make getter methods final, JIT compiler will inline these method and eliminate method calls. Thus, this abstraction does not degrade performance, as done in `InternalRow`. The values of c. is already shown by introducing ``InternalRow``

**Comment by kiszk** [comment]
cc: @davies

**Comment by kiszk** [comment]
Dear @nongli and @davies , I would appreciate it your review and comments about this abstraction.

**Comment by davies** [comment]
For now, I did not see the value to do this. I think we can defer it to the day we actually need it.

Maybe @nongli could say more on it.

**Comment by kiszk** [comment]
Thru my recent activities, I realized it is unnecessary. Let me close this.

**Pull request closed without merging**
