### PR TITLE
[SPARK-26697][CORE] Log local & remote block sizes.

### PR DESCRIPTION
**Pull request by squito**
## What changes were proposed in this pull request?

To help debugging failed or slow tasks, its really useful to know the
size of the blocks getting fetched.  Though that is available at the
debug level, debug logs aren't on in general -- but there is already an
info level log line that this augments a little.

## How was this patch tested?

Ran very basic local-cluster mode app, looked at logs.  Example line:

```
INFO ShuffleBlockFetcherIterator: Getting 2 (194.0 B) non-empty blocks including 1 (97.0 B) local blocks and 1 (97.0 B) remote blocks
```

Full suite via jenkins.

### CODE REVIEW

**Review by tgravescs — APPROVED** [review]
+1 pending jenkins

**Comment by tgravescs** [comment]
test this please

**Review by srowen — APPROVED** [review]

**Comment by vanzin** [comment]
Merging to master.

**Comment by joshrosen-stripe** [comment]
(A few months late to the party here)

Thanks for working on this!  I'm currently debugging some FetchFailed issues and this extra verbosity is helpful 💯

**Pull request closed without merging**
