### PR TITLE
[SPARK-32024][WEBUI][FOLLOWUP] Quick fix on test failure on missing when statements

### PR DESCRIPTION
**Pull request by HeartSaVioR**
### What changes were proposed in this pull request?

This patch fixes the test failure due to the missing when statements for destination path. Note that it didn't fail on master branch, because 245aee9 got rid of size call in destination path, but still good to not depend on 245aee9.

### Why are the changes needed?

The build against branch-3.0 / branch-2.4 starts to fail after merging SPARK-32024 (#28859) and this patch will fix it.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Ran modified UT against master / branch-3.0 / branch-2.4.

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
cc. @dongjoon-hyun @gengliangwang @zhli1142015

This patch should be ported back to branch-3.0 / branch-2.4 as well. Please take a look. Thanks!

**Comment by dongjoon-hyun** [comment]
Hi, @HeartSaVioR .
Could you make two addition PRs directly to `branch-3.0` and `branch-2.4`?
We had better verify the actual Jenkins Result.

**Comment by HeartSaVioR** [comment]
OK will raise PRs for branch-3.0 and branch-2.4 as well.

**Comment by dongjoon-hyun** [comment]
Thank you so much! Sorry for asking those additional items.

**Comment by HeartSaVioR** [comment]
My pleasure :) Thanks again for watching Jenkins builds thoughtfully.

**Comment by HeartSaVioR** [comment]
#29047 #29048

**Comment by zhli1142015** [comment]
Thank you @HeartSaVioR , this looks good to me.

**Comment by HyukjinKwon** [comment]
Thanks @dongjoon-hyun and @HeartSaVioR.

**Comment by HyukjinKwon** [comment]
retest this please

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master, branch-3.0 and branch-2.4.

**Comment by HyukjinKwon** [comment]
Oh! I missed https://github.com/apache/spark/pull/29046#issuecomment-655807255 comment. I will monitor the test results.

**Comment by HeartSaVioR** [comment]
Thanks all for the quick review and merging!

**Pull request closed without merging**
