### PR TITLE
[DO-NOT-MERGE] Check if 19721 breaks a CRAN

### PR DESCRIPTION
**Pull request by HyukjinKwon**
## What changes were proposed in this pull request?

Do not merge this. Simply to run a build and check the results. Will close this as soon as the build is triggered.

## How was this patch tested?

N/A

### CODE REVIEW

**Comment by gatorsmile** [comment]
I think the CRAN break is not caused by that PR https://github.com/apache/spark/pull/19721

**Comment by gatorsmile** [comment]
The failure should not be related to Spark

**Comment by HyukjinKwon** [comment]
Ah, sure. I just wanted to double check. Thanks @gatorsmile!

**Comment by HyukjinKwon** [comment]
Could I revert a04f2bea67c9abf4149d33ac6c319cd4f85344d5 back maybe?

**Comment by gatorsmile** [comment]
I prefer to asking the original author for resubmitting the PR.

**Comment by HyukjinKwon** [comment]
Sure, that also works. Thanks @gatorsmile.

**Pull request closed without merging**
