### PR TITLE
[SPARK-12009][Yarn]Avoid to re-allocating yarn container while driver want to stop all Executors 

### PR DESCRIPTION
**Pull request by lianhuiwang**
when it is yarn-cluster mode and user had called sc.stop(), but main function continue to run, need to shut down reporterThread in order to avoid to re-allocating containers. 
@suyanNone  @vanzin @andrewor14 Can you take a look at this? Thanks.

### CODE REVIEW

**Comment by suyanNone** [comment]
no... actually, it is not good idea....Executor may be killed by Yarn due to some reason...or just akka disconnected...
and I hope you can close this, I will working for that to find a more reasonable solution....

**Comment by lianhuiwang** [comment]
@suyanNone yes, what you said is right. Now stop reportThread when TaskSchedulerImpl.stop() has been called. @jerryshao

**Comment by suyanNone** [comment]
@lianhuiwang
I prefer call sc.requestTotalExecutor(0), because we can't foresee user's behave after sc.stop
and I already refine in my previous modification version. thanks for  you if you can take some time to look it

**Comment by lianhuiwang** [comment]
yes, i think #9992 is better that this PR. I closed it. @suyanNone Thanks.

**Pull request closed without merging**
