### PR TITLE
[SPARK-21278][PYSPARK] Upgrade to Py4J 0.10.6

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
## What changes were proposed in this pull request?

This PR aims to bump Py4J in order to fix the following float/double bug.
Py4J 0.10.5 fixes this (https://github.com/bartdag/py4j/issues/272) and the latest Py4J is 0.10.6.

**BEFORE**
```
>>> df = spark.range(1)
>>> df.select(df['id'] + 17.133574204226083).show()
+--------------------+
|(id + 17.1335742042)|
+--------------------+
|       17.1335742042|
+--------------------+
```

**AFTER**
```
>>> df = spark.range(1)
>>> df.select(df['id'] + 17.133574204226083).show()
+-------------------------+
|(id + 17.133574204226083)|
+-------------------------+
|       17.133574204226083|
+-------------------------+
```

## How was this patch tested?

Manual.

### CODE REVIEW

**Review by srowen — COMMENTED** [review]
Seems reasonable to me to upgrade for 2.3.0, for the reasons we mentioned on the 0.10.5 PR

**Comment by dongjoon-hyun** [comment]
Thank you again, @srowen !

**Comment by dongjoon-hyun** [comment]
As expected, it passed all the tests. 
Also, cc @holdenk .

**Comment by holdenk** [comment]
LGTM

**Comment by dongjoon-hyun** [comment]
Thank you for review, @holdenk .

**Comment by holdenk** [comment]
Merged to master, thanks for the upgrade and keeping on top of the underlying issue.

**Comment by dongjoon-hyun** [comment]
Thank you for merging, @holdenk .

**Pull request closed without merging**
