### PR TITLE
[SPARK-5689][Doc] Document what can be run in different YARN modes

### PR DESCRIPTION
**Pull request by Sephiroth-Lin**

### CODE REVIEW

**Comment by srowen** [comment]
I don't object to this, although most of the YARN-related content here is almost all redundant, since it doesn't change between Python and Scala/Java, and this is a YARN-related doc. The docs are kind of out of order now since the explanation of `SparkPi` followed the python example. I am not sure this adds enough value.

**Comment by srowen** [comment]
(That is, I don't think this is quite what https://issues.apache.org/jira/browse/SPARK-5689 is getting at; a simple statement of what can be run now might be sufficient rather than duplicating this much.)

**Comment by tgravescs** [comment]
For this I was actually thinking just making a statement about specifically what can be run in either mode.  Perhaps around paragraph on line 215 where we discuss the two modes. 

interactive shell(s) (both pyspark, spark-sql, spark-shell) can only be in used client mode.    That might be it since we recently added the python support for cluster mode.

**Comment by tgravescs** [comment]
Jenkins, test this please

**Comment by andrewor14** [comment]
I actually don't think we should merge this. It's not specific to YARN that interactive shells cannot run in cluster mode. I agree that we should have a centralized table somewhere that details what applications are supported on what modes, but this doesn't seem like the right place.

**Pull request closed without merging**
