### PR TITLE
[SPARK-11233][SQL] register cosh in function registry

### PR DESCRIPTION
**Pull request by shagunsodhani**

### CODE REVIEW

**Comment by rxin** [comment]
Jenkins, test this please.

**Comment by rxin** [comment]
@shagunsodhani can you change the title to "[SPARK-11233][SQL] register cosh in function registry".

**Comment by shagunsodhani** [comment]
@rxin :+1:

**Comment by srutis** [comment]
Sruti S <sruti.shivakumar@gmail.com>
9:29 AM (4 hours ago)

to Shagun 

A quick look through the source of FunctionRegistry.scala  seems to indicate that the function is missing from a lookup table, so it looks like a simple fix to add the entry will resolve the issue.

object FunctionRegistry {

  type FunctionBuilder = Seq[Expression] => Expression

  val expressions: Map[String, (ExpressionInfo, FunctionBuilder)] = Map(
                                                             ...
                                                             ...

// math functions
    expression[Acos]("acos"),
    expression[Asin]("asin"),
    expression[Atan]("atan"),
    expression[Atan2]("atan2"),
    expression[Bin]("bin"),
    expression[Cbrt]("cbrt"),
    expression[Ceil]("ceil"),
    expression[Ceil]("ceiling"),
    expression[Cos]("cos"),
 /* Add here ---> */ expression[Cosh]("cosh"),

**Comment by JoshRosen** [comment]
Jenkins, this is ok to test.

**Comment by rxin** [comment]
Thanks - I've merged this.

**Pull request closed without merging**
