### PR TITLE
[SPARK-14804][Spark][Graphx] Fix Graph vertexRDD/EdgeRDD checkpoint results ClassCastException

### PR DESCRIPTION
**Pull request by suyanNone**
## What changes were proposed in this pull request?

The PR fixed  compute chain from CheckpointRDD<-vertexRDDImp to  CheckpointRDD<-partitionRDD<- vertexRDDImpl
## How was this patch tested?

unit test

### CODE REVIEW

**Comment by suyanNone** [comment]
mistake to open, close first

**Comment by tdas** [comment]
This fix is roughly in the right direction. However there are two major concerns. 
- It changes the behavior of VertexRDD.isCheckpointed() which is a public method. 
- There must be new tests added to make sure this does not happen again. I dont see any new tests that checkpoints, forces the checkpoint by count/collect, and then collects again. 

Ping @jkbradley

**Comment by tdas** [comment]
also, ping @rxin

**Comment by tdas** [comment]
Actually, correction. Here is a better fix. The key problem here is that the RDD internal logic for computing from checkpoints, depends on a public, override-able API. This is wrong. Either the `isCheckpointed` should have been marked final, or the internal `isCheckpointedAndMaterialized` should not have depended on `isCheckpointed` (see [here](https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/rdd/RDD.scala#L1592)).

So the simplest, and correct solution is probably (not tested) to change `isCheckpointedAndMaterialzed`.
```
  private[spark] def isCheckpointedAndMaterialized: Boolean = checkpointData.exists(_.isCheckpointed)
```


```

**Comment by jkbradley** [comment]
CC: @ankurdave  just making you aware of this

**Comment by suyanNone** [comment]
@tdas agree, `isCheckpointed` should be final, in current code, `isCheckpointed` exposed as public is for testing?

**Comment by tdas** [comment]
Okay so can you update this PR according to the discussion, and add the necessary tests as well?

**Comment by neggert** [comment]
Not sure what's going on regarding the multiple PRs for this issue, but I cherry-picked this PR on top of 1.6.2 and it fixed the problem for me.

**Pull request closed without merging**
