### PR TITLE
[SPARK-29410][BUILD] Update commons-beanutils to 1.9.4

### PR DESCRIPTION
**Pull request by peter-toth**
### What changes were proposed in this pull request?
This PR updates commons-beanutils to 1.9.4.

### Why are the changes needed?
CVE fixed in 1.9.4: http://commons.apache.org/proper/commons-beanutils/javadocs/v1.9.4/RELEASE-NOTES.txt

### Does this PR introduce any user-facing change?
No.

### How was this patch tested?
Existing UTs.

### CODE REVIEW

**Comment by peter-toth** [comment]
retest this please

**Review by srowen — COMMENTED** [review]
Looks OK pending tests. Jenkins is down now though

**Comment by wangyum** [comment]
retest this please

**Review by wangyum — APPROVED** [review]

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
