### PR TITLE
[SPARK-16872][ML] Add Gaussian NB

### PR DESCRIPTION
**Pull request by zhengruifeng**
## What changes were proposed in this pull request?
Add Gaussian NB

## How was this patch tested?
existing tests and added tests

### CODE REVIEW

**Comment by zhengruifeng** [comment]
Jenkins, retest this please

**Comment by zhengruifeng** [comment]
Jenkins, retest this please

**Comment by MLnick** [comment]
The previous PR had some discussion around whether this should be a new estimator or not. It's not clear why you've opened a new PR?

It's also not clear that decision was actually made. I think the consensus was more towards making GaussianNB a distinct estimator / model combination.

cc @sethah

**Comment by zhengruifeng** [comment]
@MLnick  Sorry to reply late. It is a long time since I got the last comments in the previous PR https://github.com/apache/spark/pull/15324, so I thought that community may dislike that design.

I am still OK whether GNB be a distinct estimator or not. If someone can shepherd this the previous PR, I am OK to reopen it.

**Pull request closed without merging**
