### PR TITLE
[SPARK-39655][CORE] Add a config to limit the number of RDD partitions

### PR DESCRIPTION
**Pull request by wangyum**
### What changes were proposed in this pull request?

This PR adds a config to limit the number of RDD partitions.
The default value is: `Int.MaxValue`. The recommended value is: `1200000`.

### Why are the changes needed?

A large number of partitions can cause driver instability, especially for Spark Hive thriftserver. It affects other users. A common case is that the join condition is incorrectly, such as:
image

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Unit test.

### CODE REVIEW

**Comment by wangyum** [comment]
cc @cloud-fan

**Comment by cloud-fan** [comment]
This reminds me of `CheckCartesianProducts`. In general, it's a bit hard to predict bad queries and fail earlier. Will https://github.com/apache/spark/pull/37014 solve your issue?

**Comment by wangyum** [comment]
> This reminds me of `CheckCartesianProducts`. In general, it's a bit hard to predict bad queries and fail earlier. Will #37014 solve your issue?

That can not solve the case where the input is very large and can't coalesce shuffle partitions. For example:
```sql
select * from large_table1(10000 partitions) t1 join large_table2(10000 partitions) t2 on t1.id = t1.id;
```

**Comment by wangyum** [comment]
> OK, but your approach doesn't fix all the issues. With AQE, a complicated query may have run for a while and the cartesian product fails in the last query stage.

Yes. This is mainly to prevent a bad query affecting the stability of the thrift server. Another case is: `a join b on a.id = b.id = a.name = b.name`, https://github.com/apache/spark/pull/29728

**Comment by cloud-fan** [comment]
> This is mainly to prevent a bad query affecting the stability of the thrift server.

I think we need better resource isolation here. Cartesian product is not the only place that can generate a super big Spark job with tons of tasks. Shall we have a mechanism in Spark Core to limit the task slots used by one thriftserver user?

**Pull request closed without merging**
