### PR TITLE
[SPARK-35593][K8S][TESTS][FOLLOWUP] Run KubernetesLocalDiskShuffleDataIOSuite on a dedicated JVM

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to run `KubernetesLocalDiskShuffleDataIOSuite` on a dedicated JVM.

### Why are the changes needed?

In Jenkins environment, `KubernetesLocalDiskShuffleDataIOSuite` and `ExternalShuffleServiceSuite` currently hit issues.
- https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/140019/
Screen Shot 2021-06-19 at 10 33 20 AM

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the Jenkins.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
cc @gengliangwang and @viirya

**Review by viirya — COMMENTED** [review]
The two `KubernetesLocalDiskShuffleDataIOSuite` and `ExternalShuffleServiceSuite` interfere each others?

**Comment by dongjoon-hyun** [comment]
Yes, `KubernetesLocalDiskShuffleDataIOSuite` has some assumption that the other shuffle storage directory is not used and try to touch it. That seems to be the reason.

**Review by viirya — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @viirya ! Merged to master.

**Pull request closed without merging**
