### PR TITLE
[SPARK-29741][WEBUI] Spark Application UI- In Environment tab add "Search" option

### PR DESCRIPTION
**Pull request by amanomer**
### What changes were proposed in this pull request?
Added search option on Environment tab.

### Why are the changes needed?
As there are different sections in Environment tab now for information's and properties like
Runtime Information,Spark Properties,Hadoop Properties, System Properties & Classpath Entries, better to give one Search field .So it wil be easy to search any parameter value even though we don't know in which section it will come.

### Does this PR introduce any user-facing change?
Yes. Environment page will be a having a search option.

### How was this patch tested?
Manually. Screenshot attached.

image

### CODE REVIEW

**Comment by srowen** [comment]
Why not just command-F in the browser?

**Comment by amanomer** [comment]
It will highlight the keyword but doesn't filter the fields. Plus, at environment tab, property list is very long which makes difficult to go over entire list.

**Comment by amanomer** [comment]
cc @srowen @cloud-fan

**Comment by srowen** [comment]
So, this expands sections that have matches, and hides the others? OK I get it. I am still not sure whether it's worth adding, as they're all expanded by default and you're usually searching for a more specific string, so you'll jump right to it.

**Comment by amanomer** [comment]
Currently, properties are categorized into different sections such as runtime, spark, hadoop, etc, so when I want to search any property with keyword, I need to know its category, after this PR I can just input my keyword in search and only those properties which have that keyword will be shown. And also I think search option is useful here because environment page have a long list of properties under almost every section.

**Comment by srowen** [comment]
Why would you need to know the category? I'm still missing this.

**Comment by amanomer** [comment]
Cases when we don't know property's whole name, but we have some keywords like 'adaptive', 'block'. These keywords can be input in search text and only properties containing that keyword will be filtered and shown.
I think for these cases, search option will be helpful?

**Comment by srowen** [comment]
Again, that's what Cmd-F does already. I don't see the benefit... except that if one has collapsed the sections this helps expand them.

**Comment by amanomer** [comment]
Is showing fields which matches the keyword and hiding irrelevant information not useful?

**Comment by srowen** [comment]
But that is what Cmd-F does too. I'm still missing the difference other than what I gave above.

**Comment by amanomer** [comment]
Okay.

**Comment by amanomer** [comment]
Reason which you have mentioned is enough to get this search bar?

**Comment by srowen** [comment]
Well, they're expanded by default. I think someone coming to find a property just searches straight away. I'm neutral on the added UI element therefore.

**Comment by amanomer** [comment]
What to do then? Do we need feedback from other members on this?

**Comment by srowen** [comment]
Sure, if someone favors merging it I won't oppose it. Otherwise, this should be closed.

**Comment by amanomer** [comment]
cc @gatorsmile @HyukjinKwon

**Comment by amanomer** [comment]
@srowen Hadoop Properties, System Properties and Classpath Entries tables are collapsed by default.

**Comment by amanomer** [comment]
https://github.com/apache/spark/blob/d555f8fcc964e6e81f2d849de62d06877dca70c5/core/src/main/scala/org/apache/spark/ui/env/EnvironmentPage.scala#L78-L105

**Comment by srowen** [comment]
Oh, did that change in master? doesn't look that way on 2.4.x. OK I think that's a compelling enough reason.

**Comment by HyukjinKwon** [comment]
Hm, to me Im still not sure .. cc @gengliangwang WDYT

**Comment by gengliangwang** [comment]
I am +0 with this one. I think I will still use `cmd+f` for searching.

> Hadoop Properties, System Properties and Classpath Entries tables are collapsed by default.

In such a case, it also makes sense to hide the search result of System Properties and Classpath Entries by default.

**Comment by tgravescs** [comment]
In some ways if we are going to enhance it, I would rather see it in datatables like the executors and task pages and you get search and pagination for free, but that will be more work.

**Pull request closed without merging**
