### PR TITLE
[MINOR][SQL] Print stacktrace when NoClassDefFoundError in HiveDelegationToken

### PR DESCRIPTION
**Pull request by Ted-Jiang**
### What changes were proposed in this pull request?

When i get `HiveDelegationToken` in spark-subimit cluster mode,  It failed without stack trace. I think its better add it for trouble shooting.  

before 

```
2022-09-02T07:56:43,897 WARN  [main] security.HiveDelegationTokenProvider : You are attempting to use the org.apache.spark.sql.hive.security.HiveDelegationTokenProvider, but your Spark distribution is not built with Hive libraries
```
After will print the before message + NoSuchMethod..... （sorry for lost the log）

### CODE REVIEW

**Comment by Ted-Jiang** [comment]
@wangyum PTAL

**Review by HyukjinKwon — COMMENTED** [review]
@Ted-Jiang mind filling the PR description? Would be great to show the warning message before/after this change.

**Review by srowen — APPROVED** [review]

**Comment by srowen** [comment]
Merged to master

**Review by dongjoon-hyun — COMMENTED** [review]
+1, LGTM.

**Pull request closed without merging**
