### PR TITLE
[SPARK-45455][SQL][JDBC] Improve the rename interface of Postgresdialet

### PR DESCRIPTION
**Pull request by caicancai**
close: #45455

### What changes were proposed in this pull request?

improve rename interface.
捕获

change to
spark1

### Why are the changes needed?

At first, the newtable of the renameTable interface of postgresdialect does not specify a namespace. I optimized it according to the rename interface of other xxdialect.
And jdbcdialect also defaults to this way of writing to specify the database.

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

yes

### Was this patch authored or co-authored using generative AI tooling?

no

### CODE REVIEW

**Comment by beliefer** [comment]
Could you add more detail to description?

**Comment by caicancai** [comment]
> Could you add more detail to description?

Thank you, this was my oversight.I have added

**Comment by beliefer** [comment]
Because this is your first PR, please reference other PR's description.

**Comment by caicancai** [comment]
> Because this is your first PR, please reference other PR's description.

thank you

**Comment by caicancai** [comment]
cli seems to report an error in pyspark, but I did not change this part
Error message: Error: Value cannot be null. (Parameter 'ContainerId')

**Comment by beliefer** [comment]
Please use `git rebase` to rebase master branch and do not use `git merge`.

**Pull request closed without merging**
