### PR TITLE
[SPARK-11091] [SQL] Change spark.sql.canonicalizeView to spark.sql.nativeView.

### PR DESCRIPTION
**Pull request by yhuai**
https://issues.apache.org/jira/browse/SPARK-11091

### CODE REVIEW

**Comment by cloud-fan** [comment]
also need to change this comment https://github.com/apache/spark/blob/master/sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveQl.scala#L540

**Comment by cloud-fan** [comment]
LGTM, pending test.

**Comment by yhuai** [comment]
test this please

**Comment by yhuai** [comment]
Merging to master.

**Pull request closed without merging**
