### PR TITLE
[SPARK-32287][TESTS][FOLLOWUP] Add debugging for flaky ExecutorAllocationManagerSuite

### PR DESCRIPTION
**Pull request by tgravescs**
### What changes were proposed in this pull request?

fixing flaky test in ExecutorAllocationManagerSuite. The issue is that there is a timing issue when we do a reset as to when the numExecutorsToAddPerResourceProfileId gets reset. The fix is to just always set those values back to 1 when we call reset().

### Why are the changes needed?

fixing flaky test in ExecutorAllocationManagerSuite

### Does this PR introduce _any_ user-facing change?

no
### How was this patch tested?

ran the unit test via this PR a bunch of times and the fix seems to be working.

### CODE REVIEW

**Comment by tgravescs** [comment]
ok ok one more run, if everything looks good, I'll clean it up.

**Comment by tgravescs** [comment]
@HyukjinKwon @dongjoon-hyun this is ready for review now.  I ran the fix a bunch of times here and it seems to be working fine.

**Review by HyukjinKwon — APPROVED** [review]
Looks making sense given the analysis made in the PR description.

Thanks @tgravescs.

**Comment by HyukjinKwon** [comment]
Let me rather merge this in and see how it goes. Merging it in since the last commit only removed the logs.

**Comment by HyukjinKwon** [comment]
Merged to master and branch-3.0.

**Comment by Ngone51** [comment]
Hi @tgravescs Flaky `ExecutorAllicationSuite` shows up again. Not sure it's a separate issue or it hadn't been fixed completely before:

https://github.com/apache/spark/pull/29579/checks?check_run_id=1046920591
https://github.com/apache/spark/pull/29580/checks?check_run_id=1047095026

**Comment by tgravescs** [comment]
the first one has other test failures taskset manager, taskscheduler, dagascheduler and it touched scheduler and dynamic allocation stuff, I suggest they fix all the other tests first to make sure its not really related to the PR.

**Comment by tgravescs** [comment]
the other one could perhaps be the scheduler first run at 0 as I see 2 requests when I think there should just be 1.  Perhaps we  should just change that to make sure.  I ran quite a few times on the last one and never saw the failure, of course people have been modifying that test since as well.

**Comment by HyukjinKwon** [comment]
Let's wait and see a bit more maybe?

FWIW, Such kind of flakiness is sort of tricky to fix. e.g.) last time I had to make 5 PRs to fix the flakiness in pip packaging test ..

**Comment by tgravescs** [comment]
that sounds good. I'll probably fix the initial value at some point anyway just so we rule it out and it doesn't cause problems, but it might be a few days before I get to it.

**Pull request closed without merging**
