### PR TITLE
[SPARK-38563][PYTHON] Upgrade to Py4J 0.10.9.4

### PR DESCRIPTION
**Pull request by HyukjinKwon**
### What changes were proposed in this pull request?

This PR upgrade Py4J 0.10.9.4, with relevant documentation changes.

### Why are the changes needed?

Py4J 0.10.9.3 has a resource leak issue when pinned thread mode is enabled - it's enabled by default in PySpark at https://github.com/apache/spark/commit/41af409b7bcfe1b3960274c0b3085bcc1f9d1c98.
We worked around this by enforcing users to use `InheritableThread` or `inhteritable_thread_target` as a workaround.
After upgrading, we don't need to enforce users anymore because it automatically cleans up, see also https://github.com/py4j/py4j/pull/471

### Does this PR introduce _any_ user-facing change?

Yes, users don't have to use `InheritableThread` or `inhteritable_thread_target` to avoid resource leaking problem anymore.

### How was this patch tested?

CI in this PR should test it out.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @WeichenXu123 FYI

**Comment by wangyum** [comment]
Py4J 0.10.9.4 has a resource leak issue?

**Comment by HyukjinKwon** [comment]
Oops, I meant 0.10.9.3. Just fixed.

**Review by wangyum — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Thanks!

**Comment by HyukjinKwon** [comment]
Merged to master, branch-3.3 and branch-3.2.

**Review by dongjoon-hyun — COMMENTED** [review]
+1, LGTM. Thank you, @HyukjinKwon and @wangyum .

**Review by dongjoon-hyun — COMMENTED** [review]
Oh, @HyukjinKwon .

Is `Py4J 0.10.9.4` tested with `Python 3.10.x`? This commit seems to break Python 3.10.x environment like the following.

```
apache-spark-master-python/python/lib/py4j-0.10.9.4-src.zip/py4j/clientserver.py", line 12, in <module>
06:58:13 ImportError: cannot import name 'Callable' from 'collections' (/Users/dongjoon/.pyenv/versions/3.10.1/lib/python3.10/collections/__init__.py)
```

**Comment by dongjoon-hyun** [comment]
It seems that Py4J has no test coverage for Python 3.10.
- https://www.py4j.org/download.html
Screen Shot 2022-03-17 at 2 08 31 PM

**Comment by dongjoon-hyun** [comment]
Sorry but let me create reverting PRs for this.
- https://github.com/apache/spark/pull/35903

**Comment by dongjoon-hyun** [comment]
For Apache Spark 3.2, I'm fine because we didn't support Python 3.10 before.

**Comment by HyukjinKwon** [comment]
Yeah I'm making another fix and release now. We can revert it for now too. Thanks for checking this!

**Comment by HyukjinKwon** [comment]
I made a fix, and fixing CI now (https://github.com/py4j/py4j/pull/477). I will make another release, and upgrade it back soon.

**Comment by dongjoon-hyun** [comment]
Thank you!

**Pull request closed without merging**
