### PR TITLE
[SPARK-10158] [PySpark] [MLlib] ALS better error message when using Long IDs

### PR DESCRIPTION
**Pull request by BryanCutler**
Added catch for casting Long to Int exception when PySpark ALS Ratings are serialized.  It is easy to accidentally use Long IDs for user/product and before, it would fail with a somewhat cryptic "ClassCastException: java.lang.Long cannot be cast to java.lang.Integer."  Now if this is done, a more descriptive error is shown, e.g. "PickleException: Ratings id 1205640308657491975 exceeds max integer value of 2147483647."

### CODE REVIEW

**Comment by andrewor14** [comment]
@mengxr

**Comment by BryanCutler** [comment]
Hi @mengxr , is this fix worth pushing or should I close it up?

**Comment by andrewor14** [comment]
retest this please. This looks like an OK change. Any comments @mengxr @jkbradley?

**Comment by srowen** [comment]
I'll merge to master if there are no further comments

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
