### PR TITLE
[SPARK-33800][SQL] Remove command name in AnalysisException message when a relation is not resolved

### PR DESCRIPTION
**Pull request by imback82**
### What changes were proposed in this pull request?

Based on the discussion https://github.com/apache/spark/pull/30743#discussion_r543124594, this PR proposes to remove the command name in AnalysisException message when a relation is not resolved.

For some of the commands that use `UnresolvedTable`, `UnresolvedView`, and `UnresolvedTableOrView` to resolve an identifier, when the identifier cannot be resolved, the exception will be something like `Table or view not found for 'SHOW TBLPROPERTIES': badtable`. The command name (`SHOW TBLPROPERTIES` in this case) should be dropped to be consistent with other existing commands.

### Why are the changes needed?

To make the exception message consistent.

### Does this PR introduce _any_ user-facing change?

Yes, the exception message will be changed from
```
Table or view not found for 'SHOW TBLPROPERTIES': badtable
```
to
```
Table or view not found: badtable
```
for commands that use `UnresolvedTable`, `UnresolvedView`, and `UnresolvedTableOrView` to resolve an identifier.

### How was this patch tested?

Updated existing tests.

### CODE REVIEW

**Comment by imback82** [comment]
cc @cloud-fan

**Review by cloud-fan — APPROVED** [review]

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Comment by imback82** [comment]
@cloud-fan Should we also remove command name from the following:
https://github.com/apache/spark/blob/728a1298afa78c6acd7cdc4c21ee441120c34716/sql/catalyst/src/main/scala/org/apache/spark/sql/QueryCompilationErrors.scala#L188-L196

We can do `s"$quoted is a temp view, but a table is expected"` and `s"$quoted is a temp view, but a table or permanent view is expected."` respectively. WDYT?

**Comment by cloud-fan** [comment]
Since we don't have a clear rule about when a command expects table only and when a command expects table or view, I think it still makes sense to clarify it in the error message, e.g. `'$cmd' expects a table or permanent view.`

**Pull request closed without merging**
