### PR TITLE
[SPARK-35516][WEBUI] Storage UI tab Storage Level tool tip correction

### PR DESCRIPTION
**Pull request by lidiyag**
### What changes were proposed in this pull request?
Fixed tooltip for "Storage" tab in UI

### Why are the changes needed?
Tooltip correction was needed

### Does this PR introduce _any_ user-facing change?
Yes

### How was this patch tested?
Manually tested

### CODE REVIEW

**Comment by lidiyag** [comment]
@dongjoon-hyun  @srowen please take a look

**Comment by sarutak** [comment]
ok to test.

**Comment by sarutak** [comment]
@lidiyag 
This change itself seems fine to me but could you enable GitHub Actions on your repository?
https://github.com/apache/spark/pull/32664/checks?check_run_id=2669145945

**Comment by lidiyag** [comment]
gentle ping @sarutak @dongjoon-hyun @srowen

**Comment by sarutak** [comment]
@lidiyag
This is a trivial change and checks on Jenkins passed so it LGTM but next time,  please resolve the issue I mentioned before.
```
This change itself seems fine to me but could you enable GitHub Actions on your repository?
https://github.com/apache/spark/pull/32664/checks?check_run_id=2669145945
```

**Comment by sarutak** [comment]
Merged to `master`.

**Comment by sarutak** [comment]
@lidiyag BTW, do you have a JIRA account? We need to set your name to `Assignee` field in JIRA.
https://issues.apache.org/jira/browse/SPARK-35516

**Comment by lidiyag** [comment]
@sarutak my jira id is lidiyag. I ahve enables github actions in my repo. Thanks for merging:)

**Comment by sarutak** [comment]
@lidiyag I found. Thanks.

**Pull request closed without merging**
