### PR TITLE
[SPARK-48674][Connect] Extracted error handling functions from SparkConnectService to a trait.

### PR DESCRIPTION
**Pull request by sethiaarun**
Since SparkConnect gRPC server can have multiple services (addService function on NettyServerBuilder) and these functions can be reused across services, specially when we would like to extend sparkconnect with various services.

### What changes were proposed in this pull request?

Extracted error handling functions from SparkConnectService to a trait. By doing this we can reuse these functions across multiple service implementations. Since we can add multiple Bindable service handlers to SparkConnect gRPC server it will be easy to use such common functions to handle errors and exceptions.  

### Why are the changes needed?

Code refactoring, to make code reusable for the community when they would like to create additional services for the SparkConnect.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

yes

### Was this patch authored or co-authored using generative AI tooling?

No

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Mind filing a JIRA please? See also https://spark.apache.org/contributing.html

**Comment by sethiaarun** [comment]
added JIRA - https://issues.apache.org/jira/browse/SPARK-48674

**Review by allisonwang-db — COMMENTED** [review]
The PR looks good, but why it's targeting branch-3.4?

**Comment by sethiaarun** [comment]
Thanks @allisonwang-db. Ideally it should be for all versions of spark >=3.4 (where connect module is present). Let me create a new PR target to [main](apache:master).

**Comment by HyukjinKwon** [comment]
Why do we need this for branch-3.4? If it's just refactoring, it shouldn't be backported, and the change should be made in master branch alone.

**Pull request closed without merging**
