### PR TITLE
[SPARK-12145][SQL] Hive Authorization V2 interface requires the username information from SessionState

### PR DESCRIPTION
**Pull request by winningsix**
We need to pass username information to SessionState in order to initial the Hive authorization V2.

### CODE REVIEW

**Comment by winningsix** [comment]
Hi @vanzin 
This PR includes two parts:
1. Add user information to SessionState which is required to initialize the authorizer.
2. Add parser rules to fallback "SET ROLE [rolename]" to Hive driver
Could you please help me review this patch? Thank you!

**Comment by vanzin** [comment]
This is not really my area, but I'm sure SQL guys will pick this up. ok to test

**Comment by hvanhovell** [comment]
@winningsix are you still working on this?

**Comment by winningsix** [comment]
Hi @hvanhovell , I am still working on this. It would be great if you or some one can review this PR. Thank you!

**Comment by winningsix** [comment]
Hi @hvanhovell @rxin , could you help me review this changes? I have updated the original pull request since changes in #10905.

**Comment by rxin** [comment]
Thanks for the pull request. I'm going through a list of pull requests to cut them down since the sheer number is breaking some of the tooling we have. Due to lack of activity on this pull request, I'm going to push a commit to close it. Feel free to reopen it or create a new one. We can also continue the discussion on the JIRA ticket.

**Pull request closed without merging**
