### PR TITLE
[SPARK-16209] [SQL] Convert Hive Tables in PARQUET/ORC to Data Source Tables for CREATE TABLE AS SELECT

### PR DESCRIPTION
**Pull request by gatorsmile**
#### What changes were proposed in this pull request?

Currently, the following created tables will be Hive Table.

``` SQL
CREATE TABLE t STORED AS parquet SELECT 1 as a, 1 as b
```

``` SQL
CREATE TABLE t1
ROW FORMAT SERDE 'org.apache.hadoop.hive.ql.io.orc.OrcSerde'
STORED AS
INPUTFORMAT 'org.apache.hadoop.hive.ql.io.orc.OrcInputFormat'
OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.orc.OrcOutputFormat'
SELECT col1, col2 from t3
```

When users create table as query with `STORED AS` or `ROW FORMAT` and `spark.sql.hive.convertCTAS` is set to `true`, we will not convert them to data source tables. Actually, for parquet and orc formats, we still can convert them to data source table even if the users use `STORED AS` or `ROW FORMAT`.
#### How was this patch tested?

Added test cases for both ORC and PARQUET

### CODE REVIEW

**Comment by yhuai** [comment]
With your PR, if users specify `ROW FORMAT SERDE 'org.apache.hadoop.hive.ql.io.orc.OrcSerde'`, will we convert?

**Comment by gatorsmile** [comment]
Nope. If users do not specify the intput and output formats. We will use the default `INPUTFORMAT`, which is `org.apache.hadoop.mapred.TextInputFormat` and the default `OUTPUTFORMAT`, which is `org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat`. This is different from the standard input and output formats for `ORC`: `org.apache.hadoop.hive.ql.io.orc.OrcInputFormat` and `org.apache.hadoop.hive.ql.io.orc.OrcOutputFormat`. 

I am not sure whether we should still convert it. Please let me know if you think we should still convert them. Thanks!

**Comment by gatorsmile** [comment]
This is not contained in https://github.com/apache/spark/pull/14482. Should I leave it open? Or should I fix the conflict after https://github.com/apache/spark/pull/14482 is merged?

**Comment by cloud-fan** [comment]
I don't think it's a very useful feature, and we may surprise users as they do use hive syntax to specify row format.

For advanced users, they can easily use `USING xxx` to explicitly create a data source table for better performance.

**Comment by gatorsmile** [comment]
I see. Let me close it.

**Pull request closed without merging**
