### PR TITLE
[SPARK-29533][SQL][TESTS][FOLLOWUP] Regenerate the result on EC2 

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This is a follow-up of https://github.com/apache/spark/pull/26189 to regenerate the result on EC2.

### Why are the changes needed?

This will be used for the other PR reviews.

### Does this PR introduce any user-facing change?

No.

### How was this patch tested?

N/A.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
@MaxGekk , @HyukjinKwon , @cloud-fan 
This is preparation for https://github.com/apache/spark/pull/26190 .

**Review by MaxGekk — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you for review and approval, @MaxGekk !

**Comment by dbtsai** [comment]
LGTM. Merged into master. Thanks!

**Comment by dongjoon-hyun** [comment]
Thank you so much for review and approval, @dbtsai !

**Pull request closed without merging**
