### PR TITLE
[SPARK-9358][SQL]UnsafeRowConcat to concatenate UnsafeRow together

### PR DESCRIPTION
**Pull request by yjshen**
JIRA: https://issues.apache.org/jira/browse/SPARK-9358

cc @rxin

### CODE REVIEW

**Comment by yjshen** [comment]
Jenkins, retest this please.

**Comment by yjshen** [comment]
these unrelated failure occurs occasionally and hard to reproduce locally.
```
org.apache.spark.sql.hive.execution.HiveCompatibilitySuite.auto_sortmerge_join_16
org.apache.spark.sql.hive.execution.HiveCompatibilitySuite.correlationoptimizer11
org.apache.spark.sql.hive.execution.SQLQuerySuite.CTAS with serde
org.apache.spark.sql.hive.execution.SortMergeCompatibilitySuite.auto_sortmerge_join_16
org.apache.spark.sql.hive.execution.SortMergeCompatibilitySuite.correlationoptimizer11
```

**Comment by yjshen** [comment]
Jenkins, retest this please.

**Comment by rxin** [comment]
Those tests have been flaky.

**Comment by rxin** [comment]
One thing is that you should just pre-build the positions of the variable length data and use a loop to go through it, rather than loop through everything all the time.

**Comment by yjshen** [comment]
Close since it's taken over by @rxin.

**Pull request closed without merging**
