### PR TITLE
[SPARK-39677][SQL][DOCS] Fix args formatting of the regexp and like functions

### PR DESCRIPTION
**Pull request by MaxGekk**
### What changes were proposed in this pull request?
In the PR, I propose to fix args formatting of some regexp functions by adding explicit new lines. That fixes the following items in arg lists.

Before:

Screenshot 2022-07-05 at 09 48 28

After:

Screenshot 2022-07-05 at 11 06 13

### Why are the changes needed?
To improve readability of Spark SQL docs.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
By building docs and checking manually:
```
$ SKIP_SCALADOC=1 SKIP_PYTHONDOC=1 SKIP_RDOC=1 bundle exec jekyll build
```

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]

**Comment by MaxGekk** [comment]
Merging to master/3.3/3.2/3.1. Thank you, @HyukjinKwon for review.

**Comment by MaxGekk** [comment]
The changes cause conflicts in 3.2 and 3.1 (probably). I will backport this PR separately.

**Comment by cloud-fan** [comment]
late LGTM

**Review by dongjoon-hyun — COMMENTED** [review]
+1, late LGTM.

**Pull request closed without merging**
