### PR TITLE
SPARK-5458. Refer to aggregateByKey instead of combineByKey in docs

### PR DESCRIPTION
**Pull request by sryza**

### CODE REVIEW

**Comment by srowen** [comment]
Is the idea simply that `aggregateByKey` is higher-level and most people don't need to go all the way to `combineByKey`? There's nothing wrong with `combineByKey` per se right?

**Comment by sryza** [comment]
Exactly

**Comment by pwendell** [comment]
I think this text also appears in `python/pyspark/rdd.py` - maybe we should udate that as well?

**Comment by sryza** [comment]
Good point, updated the patch

**Comment by pwendell** [comment]
LGTM

**Pull request closed without merging**
