### PR TITLE
Initial checkin EventHubsReceiver.

### PR DESCRIPTION
**Pull request by shanyu**
This is the initial check-in of EventHubsReceiver code. I put the project in external/eventhubs folder and added an example EventHubsEventCount.scala to the examples project.

Signed-off-by: Shanyu Zhao shzhao@microsoft.com

### CODE REVIEW

**Comment by shanyu** [comment]
This is the pull request for SPARK-9514: Add EventHubsReceiver to support Spark Streaming using Azure EventHubs

**Comment by CodingCat** [comment]
You have to add [SPARK-9514] in the title~https://cwiki.apache.org/confluence/display/SPARK/Contributing+to+Spark#ContributingtoSpark-PullRequest

**Comment by pwendell** [comment]
hey @shanyu - we are not adding third party integrations like this in the spark codebase. The best route is to create a third party package. See spark-packages.org for more information. I'd propose closing this issue in favor of a package.

**Comment by andrewor14** [comment]
@shanyu in the future could you add the JIRA [SPARK-9514] to the title of this patch? See how other patches are opened. Also it seems that the resolution here is to close this PR and move the changes to a Spark package, since the changes here are quite specific to Azure.

**Pull request closed without merging**
