### PR TITLE
[SPARK-22476][R] Add dayofweek function to R

### PR DESCRIPTION
**Pull request by HyukjinKwon**
## What changes were proposed in this pull request?

This PR adds `dayofweek` to R API:

```r
data <- list(list(d = as.Date("2012-12-13")),
             list(d = as.Date("2013-12-14")),
             list(d = as.Date("2014-12-15")))
df <- createDataFrame(data)
collect(select(df, dayofweek(df$d)))
```

```
  dayofweek(d)
1            5
2            7
3            2
```

## How was this patch tested?

Manual tests and unit tests in `R/pkg/tests/fulltests/test_sparkSQL.R`

### CODE REVIEW

**Review by felixcheung — APPROVED** [review]
LGTM!

**Comment by HyukjinKwon** [comment]
Thanks for review @felixcheung. BTW, looks AppVeyor was failed by a different reason .. ?

```
> packageVersion('knitr'); packageVersion('rmarkdown'); packageVersion('testthat'); packageVersion('e1071'); packageVersion('survival')
Error in packageVersion("knitr") : package 'knitr' not found
Execution halted
Command exited with code 1
```

**Comment by HyukjinKwon** [comment]
retest this please

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by HyukjinKwon** [comment]
Thank you @felixcheung and @dongjoon-hyun for review.

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
