### PR TITLE
[SPARK-46504][PS][TESTS][FOLLOWUPS] Moving more slow tests out of `IndexesTests`

### PR DESCRIPTION
**Pull request by zhengruifeng**
### What changes were proposed in this pull request?
Moving more slow tests out of `IndexesTests`

### Why are the changes needed?
for testing parallelism

### Does this PR introduce _any_ user-facing change?
no, test-only

### How was this patch tested?
ci

### Was this patch authored or co-authored using generative AI tooling?
no

### CODE REVIEW

**Comment by zhengruifeng** [comment]
cc @HyukjinKwon and @itholic

**Comment by zhengruifeng** [comment]
ci https://github.com/zhengruifeng/spark/actions/runs/7381378235/job/20079850099

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by zhengruifeng** [comment]
thanks @HyukjinKwon

**Pull request closed without merging**
