### PR TITLE
[SPARK-46142][INFRA] Remove `dev/ansible-for-test-node` directory

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to remove `dev/ansible-for-test-node` directory from `master` branch for Apache Spark 4.0.0 because it has been broken already.

### Why are the changes needed?

This directory was a legacy for Spark 3.2.0 and older. Currently, it's not only unused, but also incompatible completely. Specifically, all Java/Python versions and K8s versions are incompatible. Definitely, there is no usage of this.
- [Java 8](https://github.com/apache/spark/blob/7a0d0411aa02e7e1b6beb393966ada2c54c09870/dev/ansible-for-test-node/roles/common/tasks/system_packages.yml#L17)
- [Java 11](https://github.com/apache/spark/blob/7a0d0411aa02e7e1b6beb393966ada2c54c09870/dev/ansible-for-test-node/roles/common/tasks/system_packages.yml#L10)
- [Python 2](https://github.com/apache/spark/blob/master/dev/ansible-for-test-node/roles/jenkins-worker/files/python_environments/spark-py2-pip.txt)
- [Python 3.6](https://github.com/apache/spark/blob/master/dev/ansible-for-test-node/roles/jenkins-worker/files/python_environments/spark-py36-spec.txt)
- [Minikube 1.18.1](https://github.com/apache/spark/blob/7a0d0411aa02e7e1b6beb393966ada2c54c09870/dev/ansible-for-test-node/roles/jenkins-worker/defaults/main.yml#L14)
- [K8s 1.17.3](https://github.com/apache/spark/blob/7a0d0411aa02e7e1b6beb393966ada2c54c09870/dev/ansible-for-test-node/roles/jenkins-worker/defaults/main.yml#L19C14-L19C20)

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Manual review.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Could you review this, @LuciferYang ?

**Review by LuciferYang — APPROVED** [review]
+1,LGTM

**Comment by LuciferYang** [comment]
Merged into master. Thanks @dongjoon-hyun ~

**Comment by dongjoon-hyun** [comment]
Thank you, @LuciferYang !

**Pull request closed without merging**
