### PR TITLE
[SPARK-23112][DOC] Update ML migration guide with breaking and behavior changes.

### PR DESCRIPTION
**Pull request by MLnick**
Add breaking changes, as well as update behavior changes, to `2.3` ML migration guide.

## How was this patch tested?

Doc only

### CODE REVIEW

**Review by felixcheung — APPROVED** [review]

**Comment by MLnick** [comment]
@felixcheung just added a few more behavior changes I found. Should be final now.

**Review by felixcheung — APPROVED** [review]

**Review by WeichenXu123 — APPROVED** [review]
LGTM. Thanks!

**Comment by MLnick** [comment]
Merged to master / branch-2.3. Thanks!

**Comment by WeichenXu123** [comment]
@MLnick 
Forget one fix: https://github.com/apache/spark/pull/18797
I doubt whether this fix should go into "behavior change". It influences iteration number for algos use LBFGS, although it is a bugfix (this bug is introduced in spark 2.2).

**Comment by MLnick** [comment]
Didn't this go into 2.2.1?

**Comment by WeichenXu123** [comment]
ah, yes, it backport to 2.2 😳

**Pull request closed without merging**
