### PR TITLE
[SPARK-34116][SS][TEST] Separate state store numKeys metric test and validate metrics after committing

### PR DESCRIPTION
**Pull request by viirya**
### What changes were proposed in this pull request?

This patch proposes to pull the test of `numKeys` metric into a separate test in `StateStoreSuite`.

### Why are the changes needed?

Right now in `StateStoreSuite`, the tests of get/put/remove/commit are mixed with `numKeys` metric test. I found it is flaky when I was testing with other `StateStore` implementation.

Current test logic is tightly bound to the in-memory map behavior of `HDFSBackedStateStore`. For example, put can immediately show up in the `numKeys` metric.

But for a `StateStore` implementation relying on external storage, e.g. RocksDB, the metric might be updated once the data is actually committed. And `StateStoreSuite` should be a common test suite for all kinds of StateStore implementations.

Specifically, we also are able to check these metrics after state store is updated (committed). So I think we can refactor the test a little bit to make it easier to incorporate other `StateStore` externally.

### Does this PR introduce _any_ user-facing change?

No, dev only.

### How was this patch tested?

Unit test.

### CODE REVIEW

**Comment by viirya** [comment]
cc @HeartSaVioR @dongjoon-hyun @HyukjinKwon

**Review by dongjoon-hyun — APPROVED** [review]
I'm fine with this change, but do you know what is the root cause of flakiness?
>  I found it is flaky when I was testing with other StateStore implementation.

**Comment by viirya** [comment]
> I'm fine with this change, but do you know what is the root cause of flakiness?

Current test logic is tightly bound to the in-memory map behavior of `HDFSBackedStateStore`. For example, `put` can immediately show up in the `numKeys` metric.

But for a StateStore implementation relying on external storage, e.g. RocksDB, the metric might be updated once the data is actually committed.

**Comment by dongjoon-hyun** [comment]
Then, could you revise the title a little more specifically by saying like `Validate metrics after committing`

**Comment by viirya** [comment]
Updated the title. Thanks @dongjoon-hyun

**Comment by dongjoon-hyun** [comment]
Thank you, @viirya . Merged to master/3.1.

**Comment by HyukjinKwon** [comment]
LGTM2

**Pull request closed without merging**
