### PR TITLE
[SPARK-25780][CORE]Scheduling the tasks which have no higher level locality first

### PR DESCRIPTION
**Pull request by 10110346**
## What changes were proposed in this pull request?
For example:
An application has two executors: (exe1, host1), (exe2,host2), and 3 tasks with locality:  {task0, Seq(TaskLocation("host1", "exec1"))}, {task1, Seq(TaskLocation("host1", "exec1"), TaskLocation("host2"))},  {task2, Seq(TaskLocation("host2")}

If task0 is runing in exe1, when `allowedLocality` is NODE_LOCAL for exe2, it is better to schedule task2 fisrt, not task1, because task1 may be scheduled to exe1 later.

## How was this patch tested?
Added a UT

### CODE REVIEW

**Comment by 10110346** [comment]
retest this please

**Comment by Ngone51** [comment]
IIUC, If task1 want to be scheduled on exec1, so, task0 must release exec1 before localityWaits timeout at NODE_LOCAL, right ? So, my concern is whether this change would contribute to a good improvement for locality schedule. Because, as far as I know, localityWaits time is always short.

BTW, why don't you take RACK_LOCALITY into account, either ?

**Comment by 10110346** [comment]
> 
> 
> IIUC, If task1 want to be scheduled on exec1, so, task0 must release exec1 before localityWaits timeout at NODE_LOCAL, right ? So, my concern is whether this change would contribute to a good improvement for locality schedule. Because, as far as I know, localityWaits time is always short.
> 
> BTW, why don't you take RACK_LOCALITY into account, either ?

The default value of localityWaits is 3s, I donnot think 3s is short.
Yeah, RACK_LOCALITY should be took into account, if NODE_LOCALITY is ok, I will add it, thanks

**Comment by 10110346** [comment]
retest this please

**Comment by pgandhi999** [comment]
Looks like an important change to me, cc @tgravescs What do you think?

**Pull request closed without merging**
