### PR TITLE
[SPARK-12588] Remove HttpBroadcast in Spark 2.0.

### PR DESCRIPTION
**Pull request by rxin**
We switched to TorrentBroadcast in Spark 1.1, and HttpBroadcast has been undocumented since then. It's time to remove it in Spark 2.0.

### CODE REVIEW

**Comment by JoshRosen** [comment]
Also need to update the docs in a couple of places: in docs/security.md (search for broadcast).

Probably also want to remove the `spark.broadcast.factory` configuration and update docs/configuration.md.

**Comment by JoshRosen** [comment]
Oh, and also remove `spark.broadcast.port`.

**Comment by rxin** [comment]
Thanks for finding those. I will let mima run first and then fix all of them in one shot.

**Comment by JoshRosen** [comment]
Oh, and you can also get rid of `BroadcastFactory`: it's currently a `@DeveloperApi` trait but it won't serve a purpose after you remove the `spark.broadcast.factory` conf.

**Comment by rxin** [comment]
We might want to keep that internally in order to implement other broadcast functionalities though.

**Comment by rxin** [comment]
I'd definitely remove the developerapi annotation.

**Comment by rxin** [comment]
OK I pushed another update. PTAL.

**Comment by JoshRosen** [comment]
Should we add the deprecated / removed configs to https://github.com/apache/spark/blob/b244297966be1d09f8e861cfe2d8e69f7bed84da/core/src/main/scala/org/apache/spark/SparkConf.scala#L537 ?

**Comment by JoshRosen** [comment]
LGTM, by the way.

**Comment by rxin** [comment]
Thanks - merging this one.

**Pull request closed without merging**
