### PR TITLE
[SPARK-24907][SQL][WIP] Migrate JDBC DataSource to JDBCDataSourceV2 Read using DataSourceV2 API

### PR DESCRIPTION
**Pull request by tengpeng**
## What changes were proposed in this pull request?

(After the update of DataSourceV2 API, this PR will be updated)

Changes: Migrate JDBC DataSource to JDBCDataSourceV2 Read using DataSourceV2 API

- This PR is minimum viable and other JDBC features will be added soon, but it is ready for review to see if we are in the right direction.
- This PR also contains a minor improvement on DataSourceOptions (to make it serializable). 
- It does not support DLL due to the limitations of the new API

## How was this patch tested?
New unit tests.

### CODE REVIEW

**Comment by tengpeng** [comment]
@gatorsmile Got you. I will update the implementation after DataSourceV2 API changes.

**Comment by xianyinxin** [comment]
Any update on this? @tengpeng

**Comment by tengpeng** [comment]
@xianyinxin I have not followed the progress on the V2 APIs for a while, but I am still interested in implementing the V2 APIs for JDBC. I am OK to co-authored if you are interested in this PR.

**Comment by shivsood** [comment]
@tengpeng i can also help co-author here. Should we start fixing this branch or create a new branch based on latest V2? I have a local branch with with basic scaffolding for read and write paths based on latest V2. I have not push that out as yet, i can if you want to start using this.  FYI to @xianyinxin @gaborgsomogyi who have also expressed their interest in authoring this.

**Comment by xianyinxin** [comment]
Glad you have already some work on this @shivsood . Since this is a private repo which is not allowed multi people push each one's code, my suggestion is folk this repo, cherry-pick @tengpeng 's commit, rebase it based on current V2 code, apply your fix, and push your code to your own branch, and then submit pr @shivsood . Would you agree? @shivsood @tengpeng

**Comment by shivsood** [comment]
Sound's ok to me. I will try try to get this out soon.

Regards,
Shiv

**Comment by shivsood** [comment]
@Xianyin Xin <xianyin.xxy@alibaba-inc.com> if i just create Work In
Progress PR . Is it possible for all of us to collaborate on that PR? I am
wondering if forking my repo is must have?

@tengpeng <https://github.com/tengpeng> - are you ok with this approach?

Regards,
Shiv

**Comment by xianyinxin** [comment]
@shivsood OK for me.

**Comment by shivsood** [comment]
@Xianyin Xin <xianyin.xxy@alibaba-inc.com>  @tengpeng
<https://github.com/tengpeng> - I added you as collaborators. Pushed by
changes dsv2_jdbc branch in this repo. I have *not* created a <draft> PR as
this is just scaffolding code. Also experimenting with this collaboration
model :-)

@tengpeng <https://github.com/tengpeng> if you are ok , can u cherry-pick
your changes to dsv2_jdbc branch? or i can do that as i get to work
tomorrow.

Regards,
Shiv

**Comment by xianyinxin** [comment]
@shivsood Accepted. Seems good.

**Comment by shivsood** [comment]
@tengpeng Tried cherry-picking your change. It's not a direct cherry pick. Directory paths have changed and updated files also have changes. Some of your work in JDBCOptionsV2  , JDBCDataSourceV2.scala and Test is very much relevant, but needs to be adapted into the new baseline.  Suggest you take a shot at manually merging and make a commit?

**Comment by shivsood** [comment]
@gaborgsomogyi have added you as collaborator

**Comment by gaborgsomogyi** [comment]
@shivsood thanks for considering me as collaborator. Since I'm mainly in the streaming area my main intention is to implement Structured Streaming source/sink based on the SQL implementation. Additionally you've guys already picked this up so I'm contributing in this effort with review comments.

**Comment by shivsood** [comment]
> Since I'm mainly in the streaming area my main intention is to implement Structured Streaming source/sink based on the SQL implementation. Additionally you've guys already picked this up so I'm contributing in this effort with review comment

@gaborgsomogyi Thanks. Reviews would be a great help indeed. Also look forward to your streaming source/sinks work.

**Comment by shivsood** [comment]
@tengpeng @xianyinxin @gaborgsomogyi  
Pushed a PR with scaffolding for read/write paths and first draft implementation of write( append) path based on current APIs https://github.com/apache/spark/pull/25211 
Readme.md added for high level work items. Find it at org/apache/spark/sql/execution/datasources/v2/jdbc/Readme.md.

Feel free to comment/contribute as relevant. Thanks.

**Pull request closed without merging**
