### PR TITLE
[SPARK-36900][TESTS][BUILD] Increase test memory to 6g for Java 11

### PR DESCRIPTION
**Pull request by srowen**
### What changes were proposed in this pull request?

Increase JVM test memory from 4g to 6g.

### Why are the changes needed?

Running tests under Java 11 fails consistently on a few tests without more memory. The tests do legitimately grab a lot of memory, I believe. It's not super clear why memory usage is different in Java 11, but, also seems fine to just give comfortably more heap to tests for now.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Existing tests, run manually with Java 11.

### CODE REVIEW

**Comment by viirya** [comment]
Seems it fails with OOM in GA.

**Comment by srowen** [comment]
I can't quite make out if the test failure is spurious or not, or due to memory?

**Comment by dongjoon-hyun** [comment]
Since it landed to master/3.2, could you monitor the GitHub Action status on those branches for a while, @srowen ?

**Comment by HyukjinKwon** [comment]
Looks like TPC-DS got flaky after this change ..

**Comment by srowen** [comment]
Hm, weird, I wonder how more memory can cause a problem? is the VM running OOM? (where do I see the error)
I can dial it back to 5g and see how it goes?

**Comment by HyukjinKwon** [comment]
Yeah

**Pull request closed without merging**
