### PR TITLE
[SPARK-36573][BUILD][TEST] Add a default value to ORACLE_DOCKER_IMAGE

### PR DESCRIPTION
**Pull request by LucaCanali**
### What changes were proposed in this pull request?
Currently, the procedure to run the Oracle Integration Suite is based on building the Oracle RDBMS image from the Dockerfiles provided by Oracle.
Recently, Oracle has started providing database images, see  https://container-registry.oracle.com
Moreover an Oracle employee is maintaining Oracle XE images that are streamlined for testing at https://hub.docker.com/r/gvenzl/oracle-xe and https://github.com/gvenzl/oci-oracle-xe This solves the issue that official images are quite large and make testing resource-intensive and slow.
This proposes to document the available options and to introduce a default value for ORACLE_DOCKER_IMAGE

### Why are the changes needed?
This change will make it easier and faster to run the Oracle Integration Suite, removing the need to manually build an Oracle DB image.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Manually tested:
```
export ENABLE_DOCKER_INTEGRATION_TESTS=1
./build/sbt -Pdocker-integration-tests "testOnly org.apache.spark.sql.jdbc.OracleIntegrationSuite"
./build/sbt -Pdocker-integration-tests "testOnly org.apache.spark.sql.jdbc.v2.OracleIntegrationSuite"
```

### CODE REVIEW

**Comment by sarutak** [comment]
ok to test.

**Comment by sarutak** [comment]
@LucaCanali Could you apply this change for `v2.OracleIntegrationSuite` too?
Also, could you reflect this change to GA job by chainging `build_and_test.yml`?

**Review by sarutak — APPROVED** [review]
LGTM. Pending GA.
cc: @HyukjinKwon @dongjoon-hyun

**Comment by dongjoon-hyun** [comment]
Thank you for pinging me, @sarutak .

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. It's nice. Thank you, @LucaCanali and @sarutak .

**Comment by dongjoon-hyun** [comment]
Merged to master for Apache Spark 3.3.0.

**Comment by LucaCanali** [comment]
Thank you @sarutak and @dongjoon-hyun

**Pull request closed without merging**
