### PR TITLE
[SPARK-7517] Rename 'unsafe' to 'managedmemory'

### PR DESCRIPTION
**Pull request by JoshRosen**
This patch renames the `unsafe` package to `managedmemory` and updates all relevant SparkConf configurations and class names to reflect this new naming convention.

I think that the new names are less scary to users and more informative to readers. For example, ManagedMemoryRow seems like a better clearer than UnsafeRow.  Similarly, ManagedMemoryShuffleManager seems more descriptive than UnsafeShuffleManager.

This patch should be merged into master and branch-1.4 so that we can rename the configurations before they appear in any public release.

### CODE REVIEW

**Comment by JoshRosen** [comment]
(Test comment to test a feature on spark-prs).

**Comment by marmbrus** [comment]
Not to spend too much time deciding the color of this bikeshed... but what do you think about just `unmanaged` instead?  With the current name there is a lot of `managedmemory.memory` which is kind of redundant.  Also, a managed language is usually one that _has_ garbage collection and in this case that is what we are avoiding.

**Comment by rxin** [comment]
The thing that matters the most here is the config variable naming. Internal names we can change easily. Also we should keep in mind that in the future, likely everything will be "managed", so maybe there isn't much point to say managed vs unmanaged in the future.

**Comment by pwendell** [comment]
What about having the configs be under `managedMemory` but having the internal package name be `managed`? That's my personal preference.

**Comment by marmbrus** [comment]
+1 to patricks suggestion

**Comment by JoshRosen** [comment]
Sounds good; I'll update this patch in a little bit.

**Comment by JoshRosen** [comment]
Per some offline discussion, we're going to leave this at the current name `unsafe` for now.  The package name doesn't really matter that much because it's not user-facing; we only have to worry about the names of user-facing configs, which we'll address in other patches.  Therefore, I'll close this PR for now.

**Pull request closed without merging**
