### PR TITLE
[SPARK-14408][CORE] Changed RDD.treeAggregate to use fold instead of reduce

### PR DESCRIPTION
**Pull request by HyukjinKwon**
## What changes were proposed in this pull request?

Previously, `RDD.treeAggregate` used `reduceByKey` and `reduce` in its implementation, neither of which technically allows the `seq`/`combOps` to modify and return their first arguments.

This PR uses `foldByKey` and `fold` instead and notes that `aggregate` and `treeAggregate` are semantically identical in the Scala doc.

Note that this had some test failures by unknown reasons. This was actually fixed in https://github.com/apache/spark/commit/e3554605b36bdce63ac180cc66dbdee5c1528ec7.

The root cause was, the `zeroValue` now becomes `AFTAggregator` and it compares `totalCnt` (where the value is actually 0). It starts merging one by one and it keeps returning `this` where `totalCnt` is 0. So, this looks not the bug in the current change.

This is now fixed in the commit. So, this should pass the tests.

## How was this patch tested?

Test case added in `RDDSuite`.

Closes #12217

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @jkbradley, @srowen and @NathanHowell, I opened this at least to check if it really passes the tests.

**Comment by HyukjinKwon** [comment]
cc @jkbradley, @srowen and @NathanHowell, I opened this at least to check if it really passes the tests after fixing the doc error and test.

**Review by srowen — APPROVED** [review]
LGTM in that it is the same change that looked good before but is rebased and happens to pass tests now. There is no real difference in the change right?

**Comment by HyukjinKwon** [comment]
@srowen, Yes. I just double checked that only diff is - https://github.com/apache/spark/pull/18198/commits/9eda23e02adb78a23f2638f414d1eea3816248f2 and https://github.com/apache/spark/pull/18198/commits/016d479df9a162b640032f31678abcfb668a078e.

**Comment by srowen** [comment]
Any comments @jkbradley ? I imagine you approve, now that tests pass.

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
