### PR TITLE
[SPARK-19450] Replace askWithRetry with askSync.

### PR DESCRIPTION
**Pull request by jinxing64**
## What changes were proposed in this pull request?

`askSync` is already added in `RpcEndpointRef` (see SPARK-19347 and https://github.com/apache/spark/pull/16690#issuecomment-276850068) and `askWithRetry` is marked as deprecated. 
As mentioned SPARK-18113(https://github.com/apache/spark/pull/16503#event-927953218):

>askWithRetry is basically an unneeded API, and a leftover from the akka days that doesn't make sense anymore. It's prone to cause deadlocks (exactly because it's blocking), it imposes restrictions on the caller (e.g. idempotency) and other things that people generally don't pay that much attention to when using it.

Since `askWithRetry` is just used inside spark and not in user logic. It might make sense to replace all of them with `askSync`.

## How was this patch tested?
This PR doesn't change code logic, existing unit test can cover.

### CODE REVIEW

**Comment by jinxing64** [comment]
https://github.com/apache/spark/pull/16690#discussion_r101616883 causes the build to produce lots of deprecation warnings. 
@srowen @vanzin  How do you think about this ?

**Comment by srowen** [comment]
If it was just an internal API that's not supposed to be used not, and `askSync` is supposed to be the right thing to call in all instances, then, yes this is the right thing to do. However I wonder if we're missing something because this wasn't done initially.

**Comment by jinxing64** [comment]
Both `askSync` and `askWithRetry` are blocking, the only difference is the "retry"(default is 3 times) when the rpc is failed. Callers of this method do not necessarily rely on this "retry".

**Comment by vanzin** [comment]
ok to test

**Comment by vanzin** [comment]
The change LGTM pending tests.

**Comment by vanzin** [comment]
retest this please

**Comment by srowen** [comment]
Merged to master

**Comment by jinxing64** [comment]
@srowen @vanzin 
Thanks a lot for the work on this ~

**Pull request closed without merging**
