### PR TITLE
[SPARK-25598][STREAMING][BUILD][test-maven] Remove flume connector in Spark 3

### PR DESCRIPTION
**Pull request by srowen**
## What changes were proposed in this pull request?

Removes all vestiges of Flume in the build, for Spark 3.
I don't think this needs Jenkins config changes.

## How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by vanzin** [comment]
+1, would be good to test with maven just in case.

**Comment by zsxwing** [comment]
LGTM

**Comment by srowen** [comment]
Passes with Maven and SBT, and sounds like broad support. It's clean to remove, so I'll go ahead for 3.0

**Comment by srowen** [comment]
Merged to master so I can get on with removing Kafka 0.8

**Pull request closed without merging**
