### PR TITLE
[SPARK-9095] [SQL] Removes the old Parquet support

### PR DESCRIPTION
**Pull request by liancheng**
This PR removes the old Parquet support:
- Removes the old `ParquetRelation` together with related SQL configuration, plan nodes, strategies, utility classes, and test suites.
- Renames `ParquetRelation2` to `ParquetRelation`
- Renames `RowReadSupport` and `RowRecordMaterializer` to `CatalystReadSupport` and `CatalystRecordMaterializer` respectively, and moved them to separate files.
  
  This follows naming convention used in other Parquet data models implemented in parquet-mr. It should be easier for developers who are familiar with Parquet to follow.

There's still some other code that can be cleaned up. Especially `RowWriteSupport`. But I'd like to leave this part to SPARK-8848.

### CODE REVIEW

**Comment by liancheng** [comment]
retest this please

**Comment by liancheng** [comment]
retest this please

**Comment by liancheng** [comment]
cc @marmbrus

**Comment by rxin** [comment]
Thanks - I've merged this.

**Pull request closed without merging**
