### PR TITLE
[SPARK-30055][k8s] Allow configuration of restart policy for Kubernetes pods

### PR DESCRIPTION
**Pull request by khogeland**
### What changes were proposed in this pull request?

This allows the configuration of the restart policy for drivers and executors running on Kubernetes.

### Why are the changes needed?

The current restart policies are hard-coded to "Never". Restarting a failed application requires deleting and rescheduling all of its pods, which is very slow, requires external management, and drops any cache that exists in memory or container filesystem. The driver will still reschedule evicted executors.

There is also no way, with the current lack of sidecar support, to run a long-running streaming application with injected sidecar containers that need to restart on failure (sidecar containers will not affect the pod phase). This PR solves that by allowing streaming applications to set "Always" for all pods.

### Does this PR introduce any user-facing change?

New configuration properties `spark.kubernetes.driver.restartPolicy` and `spark.kubernetes.executor.restartPolicy` were added.

### How was this patch tested?

I manually verified the changes worked and ran the test script. I didn't add unit tests because it didn't seem like the tests would prove anything useful. Should I? 🤷‍♂

### CODE REVIEW

**Review by adipolak — COMMENTED** [review]
Using "Always" for executor policy might harm the broadcasting and cacheing as well.
What is the scenario where we would like to restart the executor completely?

**Comment by khogeland** [comment]
Could you elaborate on how restarting the process might harm broadcasting or caching?

I don't know of a scenario where you _wouldn't_ want to restart the executor in-place. I see no clear benefit to deleting the container and sending a new pod to the k8s scheduler.

**Comment by adipola** [comment]
I will try to explain.
This is an old diagram but it is still relevant. Each executor can receive multiple tasks. 
The task shared memory is the Cache, which can hold the broadcast and cached Dataframes/Rdd.

Let's say we have a scenario where the broadcast is used heavily and one of the tasks fails. The driver will just re-send the task to a different executor or the same one until it succeeds or the driver fails. No need to resend broadcast since no new executors were loaded. 
Now, let's assume we restart the executors, then we will have to send the broadcast again since all executors need to have this information in their cache.

Here are some questions to clarify the solution, in what scenario "always" restarting the executors are better than the driver resending tasks? what kind of failure is handled here? 


image

**Comment by khogeland** [comment]
>Now, let's assume we restart the executors

I think you're misunderstanding what the restart policy does. The restart policy is a Kubernetes setting that controls what the host does when the pod containers exit (in this case, when the executor process exits). Setting the restart policy to always tells the host to always restart executors _that have exited._ It is a failure handling mechanism.

**Comment by khogeland** [comment]
Not sure how to push this forwards. 

Random tag... @dongjoon-hyun @tgravescs, you've both merged k8s changes recently, could you review or recommend someone to review?

**Comment by tgravescs** [comment]
I'm somewhat still learning k8s details so it will take me a bit to review and we have holidays coming up so it might be at the new year before I get time.
I am a little concerned with the side affects of this so that is why I need to make sure I understand.
For instance if you have k8s restart the Driver is all the other code in place for it to really recover?  ie you have running executors, so what happens to them, does it find them, does it kill them and restart, etc..
The executor side seems a little more straight forward as long as Spark handles it properly.  Does it just show up as new executor and does it handle losing the other one properly?

cc @mccheah

**Comment by mccheah** [comment]
If the driver pod restarts, what happens to the executor pods that were running in the previous execution of the application? We would want to make sure we're not leaking executor pods. The executor pods may not be able to contact the driver however and might choose to exit accordingly.

**Comment by khogeland** [comment]
>We would want to make sure we're not leaking executor pods.

Executors are identified by a label containing the application ID ([here](https://github.com/apache/spark/blob/a2f502cf53b6b00af7cb80b6f38e64cf46367595/resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/k8s/ExecutorPodsWatchSnapshotSource.scala#L40)), which is put by SparkSubmit in the driver's Spark configuration via a ConfigMap ([here](https://github.com/apache/spark/blob/946aef05351a9db4c5a352992bc5556a6914ea6f/resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/k8s/features/BasicDriverFeatureStep.scala#L158) and [here](https://github.com/apache/spark/blob/02c5b4f76337cc3901b8741887292bb4478931f3/resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/k8s/submit/KubernetesClientApplication.scala#L100)). If the driver process restarts, it will have the same app ID and will be able to locate the executors from the previous run.

>The executor pods may not be able to contact the driver however and might choose to exit accordingly.

It looks like the default timeout for that is 10 minutes of failure to heartbeat to the driver: https://github.com/apache/spark/blob/ad238a2238a9d0da89be4424574436cbfaee579d/core/src/main/scala/org/apache/spark/internal/config/package.scala#L210-L216
It obviously shouldn't take that long to restart the driver, and in any case, the retry is effectively infinite if the executor is configured to restart when it exits. The driver address also doesn't change when the driver process is restarted. Although it is for some reason a k8s service, meaning the route will be broken while the driver pod is unready. So, in the worst case, the executor hits its 10 second timeout before reconnecting successfully.

**Comment by mccheah** [comment]
> If the driver process restarts, it will have the same app ID and will be able to locate the executors from the previous run.

So the scary part here is that the driver will try to start more executors on its restart, right? So say we have 10 executors from the previous run - these 10 will attempt to contact the driver after it restarts - but won't the driver go to create 10 more on the restart, so now we have 20 executors for the application?

**Comment by vanzin** [comment]
What happens when you restart an executor reusing the same pod, meaning it will have the same configuration as before and thus the same executor ID? Other backends don't do this, rather they allocate new executors, so Spark tends to not behave well if a completely new executor connects back with a recycled executor ID. (It will also make history interesting.)

This sounds a bit risky to me, and the only advantage I'm seeing here is avoiding the resource allocation step in the k8s server.

**Comment by khogeland** [comment]
Responding to this first because I think it's important to frame this change correctly:
>This sounds a bit risky to me and the only advantage I'm seeing here is avoiding the resource allocation step in the k8s server.

- This will allow someone to use the standard Spark distro to deploy a basic workload without relying on manual intervention or 3rd party software for failure handling. That's a big step in the direction of true native support for Kubernetes in Spark (the next step being using the Kubernetes controllers: [SPARK-24122](https://issues.apache.org/jira/browse/SPARK-24122?jql=project%20%3D%20SPARK%20AND%20text%20~%20restartpolicy#)). The current implementation is a great start, but a complicated external scheduler process is still _required_ to run production Spark applications on Kubernetes. (@liyinan926, I think you may find this discussion interesting!)
- The scheduling delay should't be understated. Between scheduling, image pulls, init containers, JVM/Spark startup, this is in practice often a multiple-minute delay in application execution.
- Another advantage is better persistence of cached data across the application. If the driver exits, the executors don't get shut down, so they keep their BlockManager cache (correct me if I'm wrong here, btw). And the executor doesn't lose its filesystem on driver or executor restart.

>So the scary part here is that the driver will try to start more executors on its restart, right? 

No, it will discover the executor pods from the previous run before checking how many need to be scheduled. (Although, there is a startup race condition that I'll push a fix for, `ExecutorPodsPollingSnapshotSource` needs to be polled once to populate the snapshot store before the allocator is started).

> What happens when you restart an executor reusing the same pod, meaning it will have the same configuration as before and thus the same executor ID?

This is an excellent question, and I'll dig into this. If reusing the executor ID isn't supported, could it just be randomly generated on startup?

**Comment by mccheah** [comment]
> No, it will discover the executor pods from the previous run before checking how many need to be scheduled (i.e. 0).

I think we really want an integration test that captures this behavior. That would also help to validate this behavior across Kubernetes upgrades, although we'd have to push upgrades to Minikube to track this. How hard would that be to build?

**Comment by liyinan926** [comment]
My biggest concern is around changing the default `restartPolicy` of executor pods to `Always`, which doesn't sound appropriate for batch run-to-completion workloads like Spark jobs. By changing it to `Always`, you introduce two competing controls of executor pods: the driver that manages the lifecycle of executor pods, and kubelets that manage the restarts of them. This is particularly a problem if a user chooses to keep the executor pods around by setting `spark.kubernetes.executor.deleteOnTermination=false`. In this particular case, the executor pods will be restarted indefinitely because they will not be deleted upon completion. A default `restartPolicy` of `OnFailure` makes much more sense. With that being said, however, I do think that executor restart in this context is a concern of the Spark core and driver, instead of the kubelets.

**Comment by vanzin** [comment]
> If the driver exits, the executors don't get shut down, so they keep their BlockManager cache (correct me if I'm wrong here, btw). And the executor doesn't lose its filesystem on driver or executor restart.

Yes, you are wrong there. All things that Spark stores (mainly: shuffle data, RDD blocks, and broadcast variables) are tied to specific instances of those things in the driver's memory. If your driver dies, the references to the "parents" go away; even if the executor doesn't lose that data, the new driver has no idea about how to use them, since it may have a completely different view of those things in memory, or take a completely different path depending on how the user application keeps its state.

So I still don't see how this will help with anything except maybe avoiding the k8s scheduling cost.

**Comment by khogeland** [comment]
If I changed the executor default back to `Never`, but left it configurable, would that be more agreeable? Yinan makes a good point, `Always` is not ideal for batch use cases. However, we have indefinitely-running streaming use cases where we need all pods to be restarted with as little downtime and churn as possible. We also have sidecar containers that need to be restarted on failure, which is not possible with the current restart policy.

>We no longer use an init-container, so there's no latency of waiting for init-containers to complete.

We inject init containers to set up auth secrets on all of our pods, so that's still a concern for us.

**Comment by liyinan926** [comment]
Not against making it configurable as long as the behavior of `restartPolicy` other than `Never` is well understood in this context. Particularly, if it gets set to `Always`, what's the implication of that for batch run-to-completion jobs? Even for streaming jobs that need to continuously run, is it simply a matter of restarting the executor pods that inherit the same executor IDs?

Further, I'm not 100% sure how kubelet sets the state of an executor pod if the executor container completes in between restarts, when `restartPolicy=Always`. As mentioned above, there could be race condition here between the driver that's supposed to delete completed executor pods, and kubelets that are supposed to handle restarts.

In workloads like Deployments and StatefulSets, things are totally different because `Always` is the only `restartPolicy` available. It makes perfect sense for the kubelet to handle restarts of pods, without the Deployment/StatefulSet controllers needing to worry about that matter at all. In this context, however, the driver is the controller for executor pods that have the notion of completion and the driver manages the lifecycle of all executor pods. There's not such a clean separation of concerns between the driver and kubelet in this case.

**Comment by mccheah** [comment]
I'd normally be ok with making this configurable, but I'm wary of the fact that the behavior isn't well defined at all when the pods restart in this particular context. It would be up to the user to know how to use the restart policy in a manner that doesn't cause unwanted behavior.

**Comment by mccheah** [comment]
Definitely think if this is configurable it should default to `Never`, because the behavior is indeed ill-defined in the other cases. I know that a default policy of `Always` would cause trouble in our internal usage of Spark on K8s if we took this change and didn't handle the restarting pods accordingly.

**Comment by khogeland** [comment]
> Particularly, if it gets set to Always, what's the implication of that for batch run-to-completion jobs?

I think this is a documentation concern, because it's strongly recommended you don't use kubelet restart with batch mode (due to lingering executors after driver completion). At least, if you're trying to execute at-most-once, you can't guarantee the deletion of the executor when the driver completes.

>Further, I'm not 100% sure how kubelet sets the state of an executor pod if the executor container completes in between restarts

The pod phase stays as "Running", it's only the container status that is updated (which Spark doesn't use). The operator will need to be updated to support that, which I have the code for, I've just been waiting until I know how this PR will end up.

>Even for streaming jobs that need to continuously run, is it simply a matter of restarting the executor pods that inherit the same executor IDs?

It looks like no backends currently recycle executor IDs, so I'm going to investigate if it's possible to avoid any issues by having the executors generate their own IDs during startup on k8s.

>It would be up to the user to know how to use the restart policy in a manner that doesn't cause unwanted behavior.

Agreed, I'll need to add some documentation here. The driver restart policy is self-explanatory, but the executor restart has subtleties that need explanation.

**Comment by khogeland** [comment]
Just pushed a couple improvements to address concerns in this thread:

- Reverted the executor default to "Never", with updated documentation advising against changing the default in non-streaming cases
- Fixed the race condition in executor scheduling by populating the snapshot store immediately in the main thread
- Added a random suffix to the ID in the executor startup script to prevent restarting with the same ID

**Comment by holdenk** [comment]
Thanks for working on this @khogeland. I like the idea of allowing people to configure the restart policy. I'm curious how this would work with Spark's dynamic scale down? When Spark cleans up the executors is does so by asking them to exit. Would it make sense to warn people about this and suggest they choose between `Never` and `OnFailure` in the description?

**Comment by khogeland** [comment]
Good call, @holdenk, I found a conflict here while digging through the dynamic allocation code. The restart policy itself shouldn't mess up the dynamic scaling, but the allocator maps executor IDs to pods 1:1 via the label selector, so randomizing the executor ID on startup doesn't work. I would need to add some hacky string manipulation on the ID to get the label back out. 

Considering all the tricky edge cases that executors presents, and with https://github.com/apache/spark/pull/27568 handling the silent failure scenarios, I think it's best to reduce this PR's scope to the much more straightforward driver restart policy.

**Comment by holdenk** [comment]
Jenkins restart this please

**Comment by holdenk** [comment]
err sorry I need more coffee
Jenkins ok to test

**Comment by holdenk** [comment]
tentative LGTM pending jenkins

**Comment by holdenk** [comment]
Jenkins retest this please.

**Pull request closed without merging**
