### PR TITLE
[SPARK-8963][ML] cleanup tests in linear regression suite

### PR DESCRIPTION
**Pull request by holdenk**
Simplify model weight assertions to use vector comparision, switch to using absTol when comparing with 0.0 intercepts

### CODE REVIEW

**Comment by holdenk** [comment]
jenkins, retest this please

**Comment by dbtsai** [comment]
LGTM. But this is cleanup for LiR. Please create another JIRA for this, and update the title. Thanks.

**Comment by holdenk** [comment]
Isn't SPARK-8913 the right jira?

**Comment by dbtsai** [comment]
This JIRA is for cleaning test in LoR but you are cleaning LiR in this PR.

**Comment by dbtsai** [comment]
Please submit separate PR for LoR. Please add new story for cleaning up LiR test code, and update the title. This one is ready to be merged.

**Comment by holdenk** [comment]
Oh whoops, sorry.

**Comment by dbtsai** [comment]
Merged into master. Thanks.

**Pull request closed without merging**
