### PR TITLE
[SPARK-25033] Bump Apache commons.{httpclient, httpcore}

### PR DESCRIPTION
**Pull request by Fokko**
## What changes were proposed in this pull request?

Bump the versions of Apache commons.{httpclient, httpcore} to make it congruent with Stocator.

Changelog httpclient: https://archive.apache.org/dist/httpcomponents/httpclient/RELEASE_NOTES-4.5.x.txt
Changelog httpcore: https://archive.apache.org/dist/httpcomponents/httpcore/RELEASE_NOTES.txt

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)
(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Comment by kiszk** [comment]
@fokko Do we need to update files under `dev/deps`?

**Comment by Fokko** [comment]
Good point @kiszk. I've just updated the files.

**Comment by kiszk** [comment]
This change looks non-risky to me.
cc @swoen @HyukjinKwon

**Comment by HyukjinKwon** [comment]
ok to test

**Review by HyukjinKwon — APPROVED** [review]

**Comment by Fokko** [comment]
I don't really understand the error, can a Spark expert elaborate what's going on here?

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
If you find this is unrelated, you could trigger another test here

**Comment by kiszk** [comment]
retest this please

**Comment by kiszk** [comment]
LGTM

**Comment by Fokko** [comment]
Nice! What was the issue with Travis? Feels like some caching to me :)

**Comment by HyukjinKwon** [comment]
We don't currently run Travis in Apache.

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by gatorsmile** [comment]
The bump is fine but this is not for making it congruent with Stocator, which is just an external connector.

**Pull request closed without merging**
