### PR TITLE
changing persistence engine trait to an abstract class

### PR DESCRIPTION
**Pull request by nirandaperera**

### CODE REVIEW

**Comment by ScrapCodes** [comment]
Hi @nirandaperera, can you create the jira with the issue you are fixing here. That way we would know why this change was done.

**Comment by rxin** [comment]
Jenkins, test this please.

**Comment by rxin** [comment]
(and yes would be great to create a jira ticket and put the title here)

**Comment by rxin** [comment]
I created the JIRA ticket: https://issues.apache.org/jira/browse/SPARK-7307

**Pull request closed without merging**
