### PR TITLE
[SPARK-46968][SQL] Replace `UnsupportedOperationException` by `SparkUnsupportedOperationException` in `sql`

### PR DESCRIPTION
**Pull request by MaxGekk**
### What changes were proposed in this pull request?
In the PR, I propose to replace all `UnsupportedOperationException` by `SparkUnsupportedOperationException` in `sql` code base, and introduce new legacy error classes with the `_LEGACY_ERROR_TEMP_` prefix.

### Why are the changes needed?
To unify Spark SQL exception, and port Java exceptions on Spark exceptions with error classes.

### Does this PR introduce _any_ user-facing change?
Yes, it can if user's code assumes some particular format of `UnsupportedOperationException` messages.

### How was this patch tested?
By running the affected test suites:
```
$ build/sbt "core/testOnly *SparkThrowableSuite"
```

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by MaxGekk** [comment]
@cloud-fan @LuciferYang @beliefer @panbingkun @dongjoon-hyun The purpose of this PR is to migrate the rest (let me know if I missed something) of `UnsupportedOperationException` on error classes using `SparkUnsupportedOperationException` in the `sql` code base. I excluded API classes intentionally to don't break existing user code.

**Comment by dongjoon-hyun** [comment]
Oh, is this the last one, @MaxGekk ?
> The purpose of this PR is to migrate the rest (let me know if I missed something) of UnsupportedOperationException on error classes using SparkUnsupportedOperationException in the sql code base. I excluded API classes intentionally to don't break existing user code.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @MaxGekk . Merged to master.

**Comment by LuciferYang** [comment]
late LGTM.

**Pull request closed without merging**
