### PR TITLE
[SPARK-27737][FOLLOW-UP][SQL][test-hadoop3.2] Update Hive test jars from 2.3.4 to 2.3.5

### PR DESCRIPTION
**Pull request by wangyum**
## What changes were proposed in this pull request?

This pr update `hive-contrib-2.3.4.jar` to `hive-contrib-2.3.5.jar` and `hive-hcatalog-core-2.3.4.jar` to `hive-hcatalog-core-2.3.5.jar`.

## How was this patch tested?

Existing test

### CODE REVIEW

**Comment by wangyum** [comment]
cc @dongjoon-hyun @HyukjinKwon

**Comment by wangyum** [comment]
retest this please

**Review by felixcheung — APPROVED** [review]
ok, but we really shouldn't have hive jar under spark/tree/master/sql/hive/src/test/resources

**Comment by felixcheung** [comment]
test jars ok when the source is included, but not for hive-*

**Review by HyukjinKwon — APPROVED** [review]

**Comment by wangyum** [comment]
Thank you @felixcheung I will try to add these jars to pom.xml in the future.

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Review by dongjoon-hyun — APPROVED** [review]

**Comment by wangyum** [comment]
retest this please

**Pull request closed without merging**
