### PR TITLE
[SPARK-31183][SQL][FOLLOWUP] Move rebase tests to `AvroSuite` and check the rebase flag out of function bodies

### PR DESCRIPTION
**Pull request by MaxGekk**
### What changes were proposed in this pull request?
1. The tests added by #27953 are moved from `AvroLogicalTypeSuite` to `AvroSuite`.
2. Checking of the `rebaseDateTime` flag is moved out from functions bodies.

### Why are the changes needed?
1. The tests are moved because they are not directly related to logical types.
2. Checking the flag out of functions bodies should improve performance.

### Does this PR introduce any user-facing change?
No

### How was this patch tested?
By running Avro tests via the command `build/sbt avro/test`

### CODE REVIEW

**Comment by MaxGekk** [comment]
@HyukjinKwon @cloud-fan Please, review the PR.

**Review by HyukjinKwon — APPROVED** [review]

**Review by cloud-fan — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master and branch-3.0.

**Comment by dongjoon-hyun** [comment]
Hi, All.
This seems to break all Jenkins job on `branch-3.0` consistently.
- https://amplab.cs.berkeley.edu/jenkins/view/Spark%20QA%20Test%20(Dashboard)/job/spark-branch-3.0-test-sbt-hadoop-3.2-hive-2.3/223/
```
org.apache.spark.sql.avro.AvroV1LogicalTypeSuite.Logical type: user specified output schema with different timestamp types
org.apache.spark.sql.avro.AvroV1Suite.SPARK-31183: rebasing milliseconds timestamps in write
org.apache.spark.sql.avro.AvroV2LogicalTypeSuite.Logical type: user specified output schema with different timestamp types
org.apache.spark.sql.avro.AvroV2Suite.SPARK-31183: rebasing milliseconds timestamps in write
```

**Comment by dongjoon-hyun** [comment]
The answers are different. It seems that we need more date-time related patches at `branch-3.0`. I'm not sure what it is.
```
!== Correct Answer - 2 ==                        == Spark Answer - 2 ==
!struct<>                                        struct<timestamp_millis:timestamp,timestamp_micros:timestamp>
![1969-12-31 16:00:01.0,1969-12-31 16:00:02.0]   [1969-12-31 16:00:01.0,1970-01-23 19:33:20.0]
![1969-12-31 16:11:06.0,1969-12-31 16:16:39.0]   [1969-12-31 16:11:06.0,2001-08-28 05:00:00.0]
```

Given the above, I'll try to recover `branch-3.0` first by reverting this. Please make a separate PR on `branch-3.0` to see the result.

**Comment by HyukjinKwon** [comment]
Thanks @dongjoon-hyun.

**Comment by MaxGekk** [comment]
The problem is commits of this PR in master and in branch-3.0 are different:
master:
DateTimeUtils.microsToMillis at https://github.com/apache/spark/commit/b402bc900ab89e6fceb9b0a37c597e8914864f11#diff-01fea32e6ec6bcf6f34d06282e08705aR155

branch-3.0:
DateTimeUtils.fromMillis at https://github.com/apache/spark/commit/a6f3e3b096e2d7a39e0b2fdec6452e6d633baf7e#diff-01fea32e6ec6bcf6f34d06282e08705aR155

The `fromMillis()` in branch-3.0 is `millisToMicros()` but not `microsToMillis()` actually. The renaming was done in master by https://github.com/apache/spark/pull/27618

**Comment by MaxGekk** [comment]
Here is the backport of this PR with bug fix: https://github.com/apache/spark/pull/27977

**Comment by HyukjinKwon** [comment]
Ah, sorry, seems it was my mistake. Thanks @MaxGekk

**Pull request closed without merging**
