### PR TITLE
[SPARK-10398] [DOCS] Migrate Spark download page to use new lua mirroring scripts

### PR DESCRIPTION
**Pull request by srowen**
Migrate Apache download closer.cgi refs to new closer.lua

This is the bit of the change that affects the project docs; I'm implementing the changes to the Apache site separately.

### CODE REVIEW

**Comment by lresende** [comment]
LGTM. I have also closed my PR.

**Comment by JoshRosen** [comment]
LGTM.

**Comment by srowen** [comment]
The failures must be spurious. One is a doc-only change; the other affects a docker script that isn't involved in the tests here. (Actually I'm not sure that download link would work as it's used there anyway, but a different story). Merging to 1.5 and master

**Comment by nchammas** [comment]
> (Actually I'm not sure that download link would work as it's used there anyway, but a different story).

FYI: It's not working for me. I think it has to do with Apache's Lua script, though.

[Related discussion](https://mail-archives.apache.org/mod_mbox/spark-dev/201511.mbox/%3CCAOhmDzdbHUvN9AM7iUxntCDzxKSRYMUCo8wyUErS30kuZpROGA%40mail.gmail.com%3E) on spark-dev.

**Pull request closed without merging**
