### PR TITLE
[SPARK-5061][SQL] SQLContext: overload createParquetFile

### PR DESCRIPTION
**Pull request by alexbaretta**
Overload taking a StructType instead of TypeTag

### CODE REVIEW

**Comment by nchammas** [comment]
cc @marmbrus

Btw @alexbaretta, when/if this PR gets merged into the codebase, your full name (not just your GitHub username) will be used as the author, so there's no need to put your name in the PR title.

**Comment by alexbaretta** [comment]
@nchammas Thanks for the tip. I am obviously a newbie here, so I greatly value feedback.

**Comment by marmbrus** [comment]
ok to test

**Comment by marmbrus** [comment]
The implementation here looks reasonable.  @alexbaretta can you elaborate on what your use case is?  We are doing a clean-up of the API and I was actually wondering if we should remove these methods that just create parquet metadata files.

Also please change the PR title to `[SPARK-5061][SQL] SQLContext: overload createParquetFile`

/cc @rxin

**Comment by alexbaretta** [comment]
@marmbrus

Michael,

I did not realize the title could be changed. Thanks for pointing it out.

Regarding the use case: I have large, unwieldy CSV files from a data vendor. Each comes with a machine readable schema file. In my code I parse the schema files and construct StructType objects describing the rows of the CSV file. Correspondingly, I create a SchemaRDD from the CSV files by parsing them according to the schema. I then want to save these SchemaRDDs to parquet for faster processing. The createParquetFile method allows me to create an empty parquet directory in HDFS which I register as SparkSQL table. Finally, I call the inserInto method on my large SchemaRDDs derived from my CSV files to save them to the parquet files. Works quite well actually, speeding up the computation of univariate statistics from tens of minutes on a 256 core cluster down to less than ten seconds.

**Comment by marmbrus** [comment]
Thanks for the info, sounds like an interesting use case.  Would just calling `saveAsParquetFile` on the  `SchemaRDD` also work for you?

**Comment by alexbaretta** [comment]
Hmmm... I guess it would. Thanks for pointing it out.

**Comment by rxin** [comment]
If that works, maybe we can close this for now?

**Comment by pwendell** [comment]
Let's close this issue to keep the queue clean, pending any new discussion.

**Comment by alexbaretta** [comment]
Yes, I guess it could work, although I haven't been able to try it yet. Let me close this.

**Pull request closed without merging**
