### PR TITLE
SPARK-10759 [MLlib] Add python example to model selection via cross-validation

### PR DESCRIPTION
**Pull request by JeremyNixon**
Python example in the same form as the Scala and Java examples. Successfully rendered on my local server and run through pyspark, results match those from the Scala example.

### CODE REVIEW

**Comment by sethah** [comment]
One question is whether we should be using `{% include_example %}` when adding new examples to the documentation. We could separate it out into different PRs, but then we are duplicating code (this example already exists [here](https://github.com/apache/spark/blob/master/examples/src/main/python/ml/cross_validator.py)).

@yinxusen could you advise?

**Comment by yinxusen** [comment]
It's better to reuse current cross validator with `{% include_example %}` other than writing it directly in markdown file.

**Comment by yinxusen** [comment]
Refer to https://github.com/apache/spark/pull/11126 and JIRA https://issues.apache.org/jira/browse/SPARK-11337

**Comment by JeremyNixon** [comment]
yinxusen, I have a PR here with the solution to just this example that takes advantage of {% include_example %}, though accepting it would make this example inconsistent with the rest of the examples in this doc. 

I'm also going to go ahead and create a branch with all of the examples fixed with {% include_example %} to make them consistent with one another and take advantage of the automatic testing and dryer code. Would you prefer that I submit that PR here, or create a new JIRA stating that all are fixed?

**Comment by JeremyNixon** [comment]
yinxusen, I went ahead and changed all of the examples in this doc to use {% include_example %} as well as updated the python cross validation example. Let me know if it's acceptable to make all of the changes within this JIRA, or if you'd prefer they be separated. 

I also notice that a JIRA exists (https://issues.apache.org/jira/browse/SPARK-13012) for converting the original examples to use {% include_example %}. The PR makes the same changes that are here, except does not include the change to the python example for cross-validation that this JIRA is supposed to be for.

**Comment by mengxr** [comment]
ok to test

**Comment by yinxusen** [comment]
@JeremyNixon Could you merge the PR with the master?

**Comment by JeremyNixon** [comment]
@yinxusen Will do.

**Comment by yinxusen** [comment]
Yes. Can we close the issue? Since you have https://github.com/apache/spark/pull/11240

**Comment by JeremyNixon** [comment]
@yinxusen Two things - 

I finished an implementation of train-validation-split so that we could finish the examples for this doc here: https://github.com/apache/spark/compare/master...JeremyNixon:train_val_split_python, not sure if it belongs in this PR or should be done separately. #11240 requires one small update, which I can push now.

**Comment by yinxusen** [comment]
@JeremyNixon Give a PR under JIRA https://issues.apache.org/jira/browse/SPARK-12877 of the train-validation-split in PySpark. You can add the train-validation-split along with that JIRA. I think we can merge https://github.com/apache/spark/pull/11240 first.

**Comment by MLnick** [comment]
@JeremyNixon is this PR still alive?

**Comment by JeremyNixon** [comment]
@MLnick Dead PR, work completed with a combination of https://github.com/apache/spark/commit/230bbeaa614ed0ee87ecceece42355dd9a4bacb3 and https://github.com/apache/spark/commit/02b1fefffb00d50c1076a26f2f3f41f3c1fa0001. Thanks for the heads up.

**Pull request closed without merging**
