### PR TITLE
[SPARK-23001] [SQL] Fix NullPointerException when DESC a database with NULL description

### PR DESCRIPTION
**Pull request by gatorsmile**
## What changes were proposed in this pull request?
When users' DB description is NULL, users might hit `NullPointerException`. This PR is to fix the issue.

## How was this patch tested?
Added test cases

### CODE REVIEW

**Comment by gatorsmile** [comment]
retest this please

**Comment by gatorsmile** [comment]
cc @cloud-fan @sameeragarwal

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by cloud-fan** [comment]
thanks, merging to master/2.3!

**Pull request closed without merging**
