### PR TITLE
[SPARK-36953][PYTHON] Expose SQL state and error class in PySpark exceptions

### PR DESCRIPTION
**Pull request by HyukjinKwon**
### What changes were proposed in this pull request?

This PR proposes to leverage the error message framework by exposing the methods below:

- `getErrorClass`
- `getSqlState`

at captured PySpark SQL exceptions (from `SparkThrowable`).

In addition, this PR adds a bit of refactoring. Previously the exception capture was done by string comparison which is flaky. Now, the logic leverages `isInstanceOf` on JVM.

### Why are the changes needed?

Users can leverage the error class and SQL state codes by:

```python
try:
    ...
except AnalysisException as e:
    if e.getSqlState().startswith("4"):
        ...
```

### Does this PR introduce _any_ user-facing change?

Yes, users now can get `getErrorClass` and `getSqlState` from SQL exceptions.

### How was this patch tested?

Manually tested, and unittests were added.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @karenfeng @ueshin FYI

**Comment by HyukjinKwon** [comment]
This PR is ready for a look.

**Comment by HyukjinKwon** [comment]
This PR is ready for a look.

**Review by karenfeng — APPROVED** [review]
It'd be great to have this! I don't have much to say about the Python code; @ueshin would know better.

**Review by ueshin — COMMENTED** [review]
Left two comments.
Otherwise, LGTM.

**Review by ueshin — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
