### PR TITLE
[SPARK-44461][SS][PYTHON][CONNECT] Verify Python Version for spark connect streaming workers

### PR DESCRIPTION
**Pull request by WweiL**
### What changes were proposed in this pull request?

Add python version check for spark connect streaming `foreachBatch_worker` and `listener_worker`

### Why are the changes needed?

Necessary check

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

I believe it can be skipped here

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master and branch-3.5.

**Review by rangadi — COMMENTED** [review]
Thanks for the fix and using existing methods for these checks.

**Comment by dongjoon-hyun** [comment]
Unfortunately, this seems to break `branch-3.5` because #42135 is only at `master` branch.
- https://github.com/apache/spark/actions/runs/5816499174/job/15769708008
```
[error] /home/runner/work/spark/spark/core/src/main/scala/org/apache/spark/api/python/StreamingPythonRunner.scala:86:5: not found: value PythonWorkerUtils
[error]     PythonWorkerUtils.writePythonVersion(pythonVer, dataOut)
[error]     ^
```

Let me revert this from `branch-3.5` first.

We can make a `branch-3.5` specific patch or backport #42135 . I'm fine with both approaches.

Also, cc @ueshin since he is the author of #42135 .

**Comment by dongjoon-hyun** [comment]
This is reverted from branch-3.5 via https://github.com/apache/spark/commit/fc58395f08ba81e84e60b9f0260f257a6f8b4fc1 . I'm monitoring branch-3.5 GitHub Action job now.

**Comment by ueshin** [comment]
#42135 contains master specific changes, but I'm fine with partially backporting it.
@WweiL Please let me know if you want the backport.

**Comment by WweiL** [comment]
@dongjoon-hyun Thanks for reverting it!

**Comment by HyukjinKwon** [comment]
Thanks @dongjoon-hyun

**Comment by WweiL** [comment]
@ueshin Thanks! I could partially backport it

**Pull request closed without merging**
