### PR TITLE
[SPARK-17429][SQL] use ImplicitCastInputTypes with function Length

### PR DESCRIPTION
**Pull request by cenyuhai**
## What changes were proposed in this pull request?

select length(11);
select length(2.0);
these sql will return errors, but hive is ok.
this PR will support casting input types implicitly for function length
the correct result is:
select length(11) return 2
select length(2.0) return 3

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
The only one error looks just about the changed behavior in `StringFunctionsSuite`. Could you fix that?

**Comment by hvanhovell** [comment]
I am still not 100% convinced that we should do this. Why is this useable in the first place? It seems to me that someone has made a mistake when this happens.

Hive compatibility is not a goal in itself. We want users to have a similar experience (for an easy transition), but this doesn't mean we want to support every (outlandish) corner case.

**Comment by cenyuhai** [comment]
@hvanhovell Why hive is so popular? because hive is compatible and stable. From the user's point of view, hive is easy to use. Users need not care about types all the time. I agree that hive compatibility is not the goal, but making spark-sql easier to use is my goal, are you?

**Comment by hvanhovell** [comment]
@cenyuhai why would you want to know the string length of a numeric type?

**Comment by cenyuhai** [comment]
In this case , we store a business type by int (to decrease record size). for example, xxx are machine error types, xxxx are application types.

**Comment by hvanhovell** [comment]
Ok, that is somewhat convincing. I'll support this since this does have a huge impact.

LGTM - merging to master.

**Pull request closed without merging**
