### PR TITLE
[SPARK-24865][FOLLOW-UP] Remove AnalysisBarrier LogicalPlan Node

### PR DESCRIPTION
**Pull request by gatorsmile**
## What changes were proposed in this pull request?
Remove the AnalysisBarrier LogicalPlan node, which is useless now.

## How was this patch tested?
N/A

### CODE REVIEW

**Comment by gatorsmile** [comment]
cc @rxin @cloud-fan

**Comment by cloud-fan** [comment]
LGTM

**Review by felixcheung — APPROVED** [review]

**Comment by cloud-fan** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
