### PR TITLE
[SPARK-4231][MLLIB][Examples] MAP calculation added to examples.MovieLensALS

### PR DESCRIPTION
**Pull request by debasish83**
MAP calculation driver to MovieLensALS was not part of SPARK-3066 merge. Added the driver in this PR.

@mengxr the results changed compared to my old runs. Any idea if some internal ALS tuning has changed (I remember per user regularization change for implicit feedback but that should not change explicit results) ?

MAP calculation:

./bin/spark-submit --master spark://TUSCA09LMLVT00C.local:7077 --class org.apache.spark.examples.mllib.MovieLensALS --jars ~/.m2/repository/com/github/scopt/scopt_2.10/3.2.0/scopt_2.10-3.2.0.jar --total-executor-cores 4 --executor-memory 4g --driver-memory 1g ./examples/target/spark-examples_2.10-1.4.0-SNAPSHOT.jar --lambda 0.065 --metrics map ~/datasets/ml-1m/ratings.dat

Got 1000209 ratings from 6040 users on 3706 movies.
Training: 800163, test: 200046.
Test users 6035 MAP 0.019697998843987024

RMSE calculation:

./bin/spark-submit --master spark://TUSCA09LMLVT00C.local:7077 --class org.apache.spark.examples.mllib.MovieLensALS --jars ~/.m2/repository/com/github/scopt/scopt_2.10/3.2.0/scopt_2.10-3.2.0.jar --total-executor-cores 4 --executor-memory 4g --driver-memory 1g ./examples/target/spark-examples_2.10-1.4.0-SNAPSHOT.jar --lambda 0.065 --metrics rmse ~/datasets/ml-1m/ratings.dat

Got 1000209 ratings from 6040 users on 3706 movies.
Training: 800116, test: 200093.
Test RMSE = 0.8558133665979457

### CODE REVIEW

**Comment by srowen** [comment]
This is turning an example into a small utility function. I'm a little wary of this. We've had people find these examples in the past and mistakenly assume they're the entire Spark implementation. Is this adding much to this as a simple example of executing ALS?

**Comment by debasish83** [comment]
@srowen ideally we should move both the utilities to compute rmse and MAP on a MatrixFactorizationModel to a common place from examples since they are the APIs that user can directly call during the model cross validation..may be it can be moved into ml pipeline ?

**Comment by mengxr** [comment]
@debasish83 What were the changes you observed? Could you list the metrics before for comparison? We reverted the change to lambda-scaling for implicit. So the metrics should be close to your previous runs.

**Comment by debasish83** [comment]
Stats from my old run:

./bin/spark-submit --master spark://TUSCA09LMLVT00C.local:7077 --class org.apache.spark.examples.mllib.MovieLensALS --jars ~/.m2/repository/com/github/scopt/scopt_2.10/3.2.0/scopt_2.10-3.2.0.jar --total-executor-cores 4 --executor-memory 4g --driver-memory 1g ./examples/target/spark-examples_2.10-1.4.0-SNAPSHOT.jar --lambda 0.065 --metrics map ~/datasets/ml-1m/ratings.dat

rank = default

Got 1000209 ratings from 6040 users on 3706 movies.

Training: 800187, test: 200022.
Test users 6035 MAP 0.03499984595868497

**Comment by debasish83** [comment]
Implicit lambda should not affect the explicit results....I will take a closer look into the recommendForAll and compare with my old version..

**Comment by debasish83** [comment]
RMSE is similar in my old runs..so the ALS core did not change...the MAP driver code is also same since I just migrated it from my PR.

TUSCA09LMLVT00C:spark-irmetrics v606014$ ./bin/spark-submit --master spark://TUSCA09LMLVT00C.local:7077 --class org.apache.spark.examples.mllib.MovieLensALS --jars ~/.m2/repository/com/github/scopt/scopt_2.10/3.2.0/scopt_2.10-3.2.0.jar --total-executor-cores 4 --executor-memory 4g --driver-memory 1g ./examples/target/spark-examples_2.10-1.4.0-SNAPSHOT.jar --lambda 0.065 --metrics rmse ~/datasets/ml-1m/ratings.dat
2015-05-03 09:58:04.904 java[33124:1903] Unable to load realm mapping info from SCDynamicStore
15/05/03 09:58:06 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Got 1000209 ratings from 6040 users on 3706 movies.                             
Training: 800952, test: 199257.
Test RMSE = 0.8558204583570717

I will compare the recommendForAll output from my branch and the merged code.

**Comment by MLnick** [comment]
I'd agree that computing evaluation metrics on ALS models should probably be moved into some evaluation utility class, and done in a way that integrates with the new cross-validation ML pipeline. The example could then call those utility functions.

**Comment by debasish83** [comment]
@mengxr if you could please point to the ML pipeline module where I should add it, I can do the change...

**Comment by srowen** [comment]
@debasish83 looks like you can close this? https://github.com/apache/spark/pull/3098 was merged and resolved it?

**Comment by debasish83** [comment]
@srowen actually I am not sure if MAP calculation got added in ML pipeline or not...I will look into it and if someone else already added it, I will close the PR

**Comment by rxin** [comment]
I'm going to close this pull request. If this is still relevant and you are interested in pushing it forward, please open a new pull request. Thanks!

**Pull request closed without merging**
