### PR TITLE
SPARK-8918 Add @since tags to mllib.clustering

### PR DESCRIPTION
**Pull request by XiaoqingWang**
I am so sorry for the delay.

### CODE REVIEW

**Comment by yu-iskw** [comment]
@XiaoqingWang thank you for sending a new PR. However, the target branch is the `branch-1.5`, not "master". You should implement them based on the `master` branch.

**Comment by XiaoqingWang** [comment]
this request is based on branch-1.5 and  pull to the branch-1.5, is that right based on master and pull to branch-1.5 ? thanks

**Comment by mengxr** [comment]
New PRs should be sent to the master branch and backported to release branches if needed, unless this is a particular fix for a release branch only. Could you close this PR and #7662 and submit another PR to the master branch? Thanks!

**Comment by XiaoqingWang** [comment]
thanks, https://github.com/apache/spark/pull/8256,based on master pull to master,please help to review,7662 has been closed

**Comment by mengxr** [comment]
@XiaoqingWang Do you mind closing this PR as well? Thanks!

**Comment by yinyao123** [comment]
OK

**Pull request closed without merging**
