### PR TITLE
[SPARK-45689][SPARK-45690][SPARK-45691][CORE][SQL] Clean up the deprecated API usage related to `StringContext/StringOps/RightProjection/LeftProjection/Either` and type use of `BufferedIterator/CanBuildFrom/Traversable`

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr Clean up the deprecated API usage related to `StringContext/StringOps/RightProjection/LeftProjection/Either`

- StringContext

```scala
@deprecated("use same-named method on StringContext companion object", "2.13.0")
def checkLengths(args: scala.collection.Seq[Any]): Unit = scCheckLengths(args, parts)

@deprecated("use processEscapes", "2.13.0")
def treatEscapes(str: String): String = processEscapes(str)
```
- StringOps

```scala
@deprecated("Use `s.replace` as an exact replacement", "2.13.2")
def replaceAllLiterally(literal: String, replacement: String): String = s.replace(literal, replacement)
```

- Either

```scala
@deprecated("Either is now right-biased, use methods directly on Either", "2.13.0")
def right = Either.RightProjection(this)
```

- LeftProjection
```scala
@deprecated("use `Either.swap.getOrElse` instead", "2.13.0")
def get: A = e match {
    case Left(a) => a
    case _       => throw new NoSuchElementException("Either.left.get on Right")
}
```

- RightProjection
```scala
@deprecated("Either is now right-biased, calls to `right` should be removed", "2.13.0")
final case class RightProjection[+A, +B](e: Either[A, B]) {
...
    @deprecated("Use `Either.toOption.get` instead", "2.13.0")
    def get: B = e match {
      case Right(b) => b
      case _        => throw new NoSuchElementException("Either.right.get on Left")
    }
...
}
```

This pr also clean up type use of `BufferedIterator/CanBuildFrom/Traversable`

```scala
  @deprecated("Use scala.collection.BufferedIterator instead of scala.BufferedIterator", "2.13.0")
  type BufferedIterator[+A] = scala.collection.BufferedIterator[A]
```

```scala
  @deprecated("Use Iterable instead of Traversable", "2.13.0")
  type Traversable[+A] = scala.collection.Iterable[A]
```

```scala
  @deprecated("Use scala.collection.BuildFrom instead", "2.13.0")
  type CanBuildFrom[-From, -A, +C] = scala.collection.BuildFrom[From, A, C]
```

### Why are the changes needed?
Clean up the deprecated Scala API usage

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass GitHub Actions

### Was this patch authored or co-authored using generative AI tooling?
No

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]
It's fine but I think we should probably fix them in batch.

**Comment by LuciferYang** [comment]
I've merged changes related to SPARK-45690 and SPARK-45691  into this one.

**Review by yaooqinn — APPROVED** [review]

**Review by beliefer — APPROVED** [review]
LGTM if tests passed.

**Comment by LuciferYang** [comment]
Merged into master for Spark 4.0. Thanks @HyukjinKwon @yaooqinn @beliefer

**Pull request closed without merging**
