### PR TITLE
[SPARK-31983][WEBUI][3.0] Fix sorting for duration column in structured streaming tab

### PR DESCRIPTION
**Pull request by iRakson**
### What changes were proposed in this pull request?
Sorting result for duration column in tables of structured streaming tab is wrong sometimes.
Screenshot 2020-06-13 at 1 58 53 PM

We are sorting on string, which results in this behaviour. 
`sorttable_numeric` and `sorttable_customkey` is used to fix this.

Refer [this](https://github.com/apache/spark/pull/28752#issuecomment-643451586) and [this](https://github.com/apache/spark/pull/28752#issuecomment-643569254)

After changes : 
Screenshot 2020-06-13 at 8 05 32 PM

### Why are the changes needed?
Sorting results are wrong for duration column in tables of structured streaming tab.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Screenshots attached.

### CODE REVIEW

**Comment by iRakson** [comment]
cc @srowen @sarutak @gengliangwang @HyukjinKwon

**Review by srowen — APPROVED** [review]
Looks reasonable to me.

**Comment by sarutak** [comment]
LGTM. Merged to `branch-3.0`.

**Comment by iRakson** [comment]
Thank You. @srowen @sarutak :)

**Pull request closed without merging**
