### PR TITLE
[SPARK-19857][yarn] Correctly calculate next credential update time.

### PR DESCRIPTION
**Pull request by vanzin**
Add parentheses so that both lines form a single statement; also add
a log message so that the issue becomes more explicit if it shows up
again.

Tested manually with integration test that exercises the feature.

### CODE REVIEW

**Comment by squito** [comment]
lgtm

I couldn't believe this at first, I had to verify by running this for myself:

```scala
scala> :paste
// Entering paste mode (ctrl-D to finish)
val x = 7
  - 1
// Exiting paste mode, now interpreting.

x: Int = 7
res0: Int = -1
```

**Comment by mridulm** [comment]
This is one of the scarey bugs I see in scala code ... the benefits of an explicit delimiter !
Wondering if it is possible to generalize this as a scala style check ...

LGTM

**Comment by srowen** [comment]
Scalac flags some forms of this as does IJ but here the dangling line had a side effect so isn't obvious it isn't on purpose to the analyzer I guess

**Comment by vanzin** [comment]
Merging to master / 2.1.

**Comment by jerryshao** [comment]
Thanks @vanzin for this fix. Sorry to bring in this bug, haven't noticed this Scala formatting issue before.

**Pull request closed without merging**
