### PR TITLE
[SPARK-12446][SQL][BACKPORT-1.6] Add unit tests for JDBCRDD internal functions

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
No tests done for JDBCRDD#compileFilter.

Author: Takeshi YAMAMURO <linguin.m.s@gmail.com>

Closes #10409 from maropu/AddTestsInJdbcRdd.

(cherry picked from commit 8c1b867cee816d0943184c7b485cd11e255d8130)

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
This is the first commit for #16021.
cc @gatorsmile .

**Comment by gatorsmile** [comment]
Can you please add [Backport-1.6] to the PR title?

**Comment by dongjoon-hyun** [comment]
Sorry for missing that tag. Thank you!

**Comment by gatorsmile** [comment]
LGTM

**Comment by gatorsmile** [comment]
Thanks! Merged to 1.6. 

Could you close the PR?

**Comment by dongjoon-hyun** [comment]
Thank you! I'll close this and proceed to next.

**Pull request closed without merging**
