### PR TITLE
[DOCUMENTATION] fixed typos in python programming guide

### PR DESCRIPTION
**Pull request by mortada**
## What changes were proposed in this pull request?

minor typo
## How was this patch tested?

minor typo in the doc, should be self explanatory

### CODE REVIEW

**Comment by srowen** [comment]
That's fine, though while you're here can you maybe scan this and related files for typos in comments, docs?

**Comment by mortada** [comment]
sure will do

**Comment by mortada** [comment]
@srowen I went through the docs, found a few more minor fixes

**Comment by srowen** [comment]
Jenkins test this please

**Comment by srowen** [comment]
OK, the others are more like slightly better writing but that's fine.

**Comment by srowen** [comment]
Merged to master/2.0

**Pull request closed without merging**
