### PR TITLE
[SPARK-15250][SQL] Remove deprecated json API in DataFrameReader

### PR DESCRIPTION
**Pull request by HyukjinKwon**
## What changes were proposed in this pull request?

This PR removes the old `json(path: String)` API which is covered by the new `json(paths: String*)`.
## How was this patch tested?

Jenkins tests (existing tests should cover this)

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Related with https://github.com/apache/spark/pull/12904 and https://github.com/apache/spark/pull/12921.

@andrewor14 Do you mind if I review this?

**Comment by HyukjinKwon** [comment]
(Sorry, I left a wrong comment referring unrelated PRs here and I removed that.)

**Comment by HyukjinKwon** [comment]
cc @rxin 

(I see doc tests and test in Python is still using `SqlContext`. Do you mind if I correct this in another PR?)

**Comment by rxin** [comment]
LGTM - merging in master/2.0.

**Comment by rxin** [comment]
Yes please submit another pr for those.

**Comment by tdas** [comment]
For future reference. Removing this method broke source compatibility in case as 
```
Option(path).map(spark.read.json)  // does not compile, after this patch.
```
In this sort of shorthand of functions using 1 parameter, works only if the method signature has one parameter and does not work when the method has varargs.

**Comment by HyukjinKwon** [comment]
@tdas Thanks, I will keep in mind.

**Pull request closed without merging**
