### PR TITLE
[SPARK-37013][SQL] Forbid `%0$` usage explicitly to ensure `format_string` has same behavior when using Java 8 and Java 17

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
The following sql has different behavior when using Java 8 and Java 17

```
--PostgreSQL throw ERROR:  format specifies argument 0, but arguments are numbered from 1
select format_string('%0$s', 'Hello');
```

**Use Java 8**

```
-- !query
select format_string('%0$s', 'Hello')
-- !query schema
struct<format_string(%0$s, Hello):string>
-- !query output
Hello
```

**Use Java 17**

```
-- !query
select format_string('%0$s', 'Hello')
-- !query schema
struct<>
-- !query output
java.util.IllegalFormatArgumentIndexException
Illegal format argument index = 0
```

The difference in this behavior comes from  the change of `j.u.Formatter.FormatSpecifier.index` method: 

Java 8

```
        private int index(String s) {
            if (s != null) {
                try {
                    index = Integer.parseInt(s.substring(0, s.length() - 1));
                } catch (NumberFormatException x) {
                    assert(false);
                }
            } else {
                index = 0;
            }
            return index;
        }
```

Java 17

```java
        private void index(String s, int start, int end) {
            if (start >= 0) {
                try {
                    // skip the trailing '$'
                    index = Integer.parseInt(s, start, end - 1, 10);
                    if (index <= 0) {
                       throw new IllegalFormatArgumentIndexException(index);
                    }
                } catch (NumberFormatException x) {
                    throw new IllegalFormatArgumentIndexException(Integer.MIN_VALUE);
                }
            }
        }
```

A `index <= 0` condition is added here to ensure `%0$` as a  `IllegalFormatArgumentIndexException` expression.

So the main change of this pr is add a require check to `FormatString` to manually disable `%0$` to ensure that Java 17 and Java 8 have the same behavior.

### Why are the changes needed?
Pass UT with JDK 17

### Does this PR introduce _any_ user-facing change?
The wrong usage like `format_string('%0$s', str)` can no longer be used, which is also consistent with PostgreSQL.

### How was this patch tested?
- Pass the Jenkins or GitHub Action
- Manual test `mvn clean install -pl sql/core -am -Dtest=none -DwildcardSuites=org.apache.spark.sql.SQLQueryTestSuite` with Java 11 and  Java 17 passed

### CODE REVIEW

**Comment by srowen** [comment]
I'm kinda confused - seems like using index 0 was always disallowed: https://docs.oracle.com/javase/8/docs/api/java/util/Formatter.html
"The first argument is referenced by "1$", the second by "2$", etc."

I wonder how it ever worked or what it did? If it was illegal to begin with, we could just let Java 17 enforce it. I'm OK with explicitly enforcing it in order to avoid behavior difference across JVMs for the same Spark version too. I would not edit the format string, I think.

Wouldn't all the numbered indices have to change anyway? otherwise editing the string might result in two arguments at position 1.

**Comment by LuciferYang** [comment]
> I'm kinda confused - seems like using index 0 was always disallowed: https://docs.oracle.com/javase/8/docs/api/java/util/Formatter.html
"The first argument is referenced by "1$", the second by "2$", etc."

Let me check this

**Comment by LuciferYang** [comment]
We can use the following case to test it

```
 import java.util.Locale
    import java.util.Formatter
    val sb = new StringBuffer()
    // Send all output to the Appendable object sb
    val formatter = new Formatter(sb, Locale.US)

    // Explicit argument indices may be used to re-order output.
    formatter.format("%4$2s %3$2s %2$2s %1$2s", "a", "b", "c", "d")
    assert(sb.toString == " d  c  b  a")
    sb.delete(0, sb.length())
    assert(sb.toString.isEmpty)
    formatter.format("%4$2s %3$2s %2$2s %0$2s", "a", "b", "c", "d")
    assert(sb.toString == " d  c  b  a")
```

This case is similar to the example written in the https://docs.oracle.com/javase/8/docs/api/java/util/Formatter.html

image


The new case tests both `%4$2s %3$2s %2$2s %1$2s` and `%4$2s %3$2s %2$2s %0$2s` and they passed when use Java 8,  although "The first argument is referenced by "1$", the second by "2$", etc." is specified in the document,  but `%0$` is not prohibited, and the result of `%0$` is equivalent to `%1$`.

The result of running the above case using Java 11 is the same as that of Java 8.

And Exceptions are thrown only when the above case is run using Java 17

```
Illegal format argument index = 0
java.util.IllegalFormatArgumentIndexException: Illegal format argument index = 0
    at java.base/java.util.Formatter$FormatSpecifier.index(Formatter.java:2808)
    at java.base/java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2879)
    at java.base/java.util.Formatter.parse(Formatter.java:2747)
    at java.base/java.util.Formatter.format(Formatter.java:2671)
    at java.base/java.util.Formatter.format(Formatter.java:2625)
```

**Comment by LuciferYang** [comment]
OK ~

**Review by srowen — APPROVED** [review]

**Comment by wangyum** [comment]
Do we need to add an item in `docs/sql-migration-guide.md`? since it's a breaking change for Java 8/11 user.

**Review by srowen — APPROVED** [review]

**Review by wangyum — APPROVED** [review]

**Pull request closed without merging**
