### PR TITLE
typo: StogeLevel -> StorageLevel

### PR DESCRIPTION
**Pull request by SiarheiFedartsou**
### What changes were proposed in this pull request?
Just a typo fix.

### Why are the changes needed?
Just to make things cleaner.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?
It seems no testing required.

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Thank you. Could you check if this is the last typo in this file, @SiarheiFedartsou ?

**Comment by bjornjorgensen** [comment]
Hi, can you enable GitHub Actions in your forked repository https://github.com/apache/spark/runs/11093613572

**Comment by SiarheiFedartsou** [comment]
> Thank you. Could you check if this is the last typo in this file, @SiarheiFedartsou ?

Hey, it seems so - at least how me non-native English allows me to say :)

**Comment by SiarheiFedartsou** [comment]
> Hi, can you enable GitHub Actions in your forked repository https://github.com/apache/spark/runs/11093613572

Hey @bjornjorgensen, done!

**Comment by srowen** [comment]
Just for completeness can you try rerunning tests? I'm sure it doesn't affect functionality

**Comment by SiarheiFedartsou** [comment]
@srowen I am not sure I am able to - it seems only maintainers can do so.

**Comment by srowen** [comment]
You can push an empty commit at least. Or can you just check the linter passes locally? That's the only real concern, maybe line length

**Comment by SiarheiFedartsou** [comment]
@srowen done :+1:

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
