### PR TITLE
[SPARK-13535] [SQL] Fix Analysis Exceptions when Using Backticks in Transform Clause

### PR DESCRIPTION
**Pull request by gatorsmile**
#### What changes were proposed in this pull request?

``` SQL
FROM
(FROM test SELECT TRANSFORM(key, value) USING 'cat' AS (`thing1` int, thing2 string)) t
SELECT thing1 + 1
```

This query returns an analysis error, like:

```
Failed to analyze query: org.apache.spark.sql.AnalysisException: cannot resolve '`thing1`' given input columns: [`thing1`, thing2]; line 3 pos 7
'Project [unresolvedalias(('thing1 + 1), None)]
+- SubqueryAlias t
   +- ScriptTransformation [key#2,value#3], cat, [`thing1`#6,thing2#7], HiveScriptIOSchema(List(),List(),Some(org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe),Some(org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe),List((field.delim,   )),List((field.delim,   )),Some(org.apache.hadoop.hive.ql.exec.TextRecordReader),Some(org.apache.hadoop.hive.ql.exec.TextRecordWriter),false)
      +- SubqueryAlias test
         +- Project [_1#0 AS key#2,_2#1 AS value#3]
            +- LocalRelation [_1#0,_2#1], [[1,1],[2,2],[3,3],[4,4],[5,5]]
```

The backpacks of `thing1` should be cleaned before entering Parser/Analyzer. This PR fixes this issue.
#### How was this patch tested?

Added a test case and modified an existing test case

### CODE REVIEW

**Comment by gatorsmile** [comment]
@hvanhovell @viirya Could you review the changes? Thanks!

**Comment by rxin** [comment]
I don't get it. Is the pull request about supporting backticks? Or change something to use backticks?

**Comment by gatorsmile** [comment]
So far, if we use backticks, analyzer is unable to process it. When we parse the plan, we did not remove the backticks. In `CatalystQl`, we clean the backticks for all the attribute/alias names if users use it. 

Before the PR fix, we do not clean backticks. The name of `attributeReference` is \`thing1\`. When analyzing the node `Project`, Analyzer is unable to find it (i.e., `thing1`) from the child's output, in which the column name is \`thing1\` instead of `thing1`, and thus, report the following error:
```
cannot resolve '`thing1`' given input columns: [`thing1`, thing2]; line 3 pos 7
```

The error message is pretty confusing. This message is issued from 
```scala
            a.failAnalysis(s"cannot resolve '${a.sql}' given input columns: [$from]")
```
The backstick in the first  '\`thing1\`' is added by the function call `a.sql`. The backstick in the second  '\`thing1\`' is part of the name. Thus, they look the same, but they are different in our plan.

**Comment by gatorsmile** [comment]
This PR is to make it works. `HiveQl` clean \`. After the fix, users can use backticks in Script Transformation now.  
```
FROM
(FROM test SELECT TRANSFORM(key, value) USING 'cat' AS (`thing1` int, thing2 string)) t
SELECT thing1 + 1
```

The issue was exposed when we generate SQL from plan. This issue blocks another PR, which has not been submitted.

**Comment by gatorsmile** [comment]
retest this please

**Comment by rxin** [comment]
Can you update the title? The current title is fairly confusing, and I'm not sure if it accurately captures what you are fixing.

**Comment by gatorsmile** [comment]
Sure, let me do it.

**Comment by gatorsmile** [comment]
retest this please

**Comment by gatorsmile** [comment]
retest this please

**Comment by gatorsmile** [comment]
retest this please

**Comment by gatorsmile** [comment]
retest this please

**Comment by viirya** [comment]
@gatorsmile the failed test is not related to this, I have sumbitted a pr to fix it. Before it is merged, the test you ask to retest will be failed very frequently.

**Comment by gatorsmile** [comment]
yeah, but this PR is so unlucky. 100% failure : )

**Comment by gatorsmile** [comment]
@cloud-fan Could you take a look at this? Thanks!

**Comment by gatorsmile** [comment]
ping @cloud-fan : ) I think this is a simple fix. Could you review it? Another PR for converting Script Transform to SQL is waiting for this fix. Thank you!

**Comment by cloud-fan** [comment]
LGTM.  cc @hvanhovell

**Comment by gatorsmile** [comment]
Thank you! @cloud-fan : )

**Comment by hvanhovell** [comment]
LGTM

**Comment by hvanhovell** [comment]
Merging this to master. Thanks!

**Pull request closed without merging**
