### PR TITLE
[SPARK-48677][BUILD] Upgrade `scalafmt` to 3.8.2

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to upgrade `scalafmt` to 3.8.2.

### Why are the changes needed?
- The full release notes: https://github.com/scalameta/scalafmt/releases/tag/v3.8.2
The last upgrade occurred 2 months ago.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA.
Manually test:
```
sh dev/scalastyle
-e Scalastyle checks passed.
```

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by panbingkun** [comment]
cc @HyukjinKwon

**Comment by HyukjinKwon** [comment]
Can you check there are some code modification, and run this? This script is only effective when there are some changes IIRC.

**Comment by panbingkun** [comment]
> Can you check there are some code modification, and run this? This script is only effective when there are some changes IIRC.
The verification process is as follows:
- positive
  ```
  (base) ➜  spark-community git:(SPARK-48677) ✗ git diff
  ```
  image

  ```
  (base) ➜  spark-community git:(SPARK-48677) ✗ sh dev/scalastyle
  -e Scalastyle checks passed.
  ```

- negative
  ```
  (base) ➜  spark-community git:(SPARK-48677) ✗ git diff
  ```
  image
 
```
(base) ➜  spark-community git:(SPARK-48677) ✗ sh dev/scalastyle
-e Scalastyle checks failed at following occurrences:
[error] /Users/panbingkun/Developer/spark/spark-community/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/v2/AlterNamespaceSetPropertiesExec.scala:35:4: Are you sure you want to println? If yes, wrap the code block with
[error]       // scalastyle:off println
[error]       println(...)
[error]       // scalastyle:on println
[error] Total time: 19 s, completed Jun 21, 2024, 8:15:30 AM
  ```

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
