### PR TITLE
[SPARK-25468][WEBUI] Highlight current page index in the spark UI

### PR DESCRIPTION
**Pull request by Adamyuanyuan**
## What changes were proposed in this pull request?

This PR is highlight current page index in the spark UI and history server UI,
https://issues.apache.org/jira/browse/SPARK-25468
I have add the following code in webui.css 
```
.paginate_button.active>a {
    color: #999999;
    text-decoration: underline;
}
```
## How was this patch tested?
Manual tests for Chrome, Firefox and Safari
Before modifying:
image

After modifying:
image

### CODE REVIEW

**Comment by wangyum** [comment]
Yes. I hit this issue also.

**Comment by gengliangwang** [comment]
Hi @Adamyuanyuan ,
Please specify the code changes in your PR description. I take a quick check and you have added 
```
 .paginate_button.active {
    outline: none;
    background-color: #2b2b2b;
  }
```

Personally I feel that the color is not good looking. Currently we change the background to this color when the mouse pointer is over the element. Maybe we can set another color for this highlight for distinguish from that? 
Or we can change the border color only instead of the background.

**Comment by Adamyuanyuan** [comment]
@gengliangwang Thanks for reminder, I also think this color is not good looking. I tried to change the background color before, but I'm not sure which is better, please give me some opinion to choose:
1. 
image
2. 
image
3. 
image

I prefer scheme 1 or scheme 3, scheme 3 is which I‘m borrowing from Spark UI of Stages Tab:

**Comment by gengliangwang** [comment]
@Adamyuanyuan Thanks for the update! 
+1 for the option 1 :)

**Comment by srowen** [comment]
Rather than modify jquery, can we override this in Spark-specific CSS? otherwise we might lose customizations when updating jquery.

**Comment by Adamyuanyuan** [comment]
> Rather than modify jquery, can we override this in Spark-specific CSS? otherwise we might lose customizations when updating jquery.

Thanks for your advice, I think override is a better way.

**Comment by Adamyuanyuan** [comment]
Hi, @srowen, I find in SparkUI, the problem still exists:
image
image

I had moved ".paginate_button.active > a" to spark specific  webui.css.  And manual tests for Chrome, Firefox and Safari.

**Comment by Adamyuanyuan** [comment]
Another way is create a new css file such as historypage-specific.css, and add link in dataTablesHeaderNodes from UIUtils.scala, make new file only loaded when the table are used, like this:
```
  def dataTablesHeaderNodes: Seq[Node] = {
    <link rel="stylesheet"
          href={prependBaseUri("/static/jquery.dataTables.1.10.4.min.css")} type="text/css"/>
    <link rel="stylesheet"
          href={prependBaseUri("/static/dataTables.bootstrap.css")} type="text/css"/>
    <link rel="stylesheet" href={prependBaseUri("/static/jsonFormatter.min.css")} type="text/css"/>
    
    <link rel="stylesheet"
          href={prependBaseUri("/static/historypage-specific.css")} type="text/css"/>

    <script src={prependBaseUri("/static/jquery.dataTables.1.10.4.min.js")}></script>
    <script src={prependBaseUri("/static/jquery.cookies.2.2.0.min.js")}></script>
    <script src={prependBaseUri("/static/jquery.blockUI.min.js")}></script>
    <script src={prependBaseUri("/static/dataTables.bootstrap.min.js")}></script>
    <script src={prependBaseUri("/static/jsonFormatter.min.js")}></script>
    <script src={prependBaseUri("/static/jquery.mustache.js")}></script>
  }
```
But I think it's a bit redundant.

**Comment by srowen** [comment]
I think the change is fine, if it works and if it maybe causes the same behavior in the whole UI.

**Review by srowen — APPROVED** [review]

**Review by dongjoon-hyun — COMMENTED** [review]
@Adamyuanyuan . Could you update the title to `[SPARK-25468][WEBUI] Highlight ...`?

**Comment by Adamyuanyuan** [comment]
@dongjoon-hyun OK, modified.

**Comment by srowen** [comment]
Merged to master/2.4

**Pull request closed without merging**
