### PR TITLE
[SPARK-40728][BUILD] Upgrade ASM to 9.4

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This PR aims to upgrade ASM to 9.4.

### Why are the changes needed?
xbean-asm9-shaded 4.22 upgrade to use ASM 9.4:

- https://github.com/apache/geronimo-xbean/pull/32
- https://asm.ow2.io/versions.html
- https://issues.apache.org/jira/browse/XBEAN-336

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass GitHub Actions

### CODE REVIEW

**Review by srowen — APPROVED** [review]

**Comment by LuciferYang** [comment]
image

It's a little strange. I can successfully build locally, but GA cannot download the new jars.

**Comment by LuciferYang** [comment]
covert to draft first and let's wait some time

**Comment by zhengruifeng** [comment]
LGTM pending CI

**Comment by LuciferYang** [comment]
Sorry, we may need to wait a few days, I found it is still at [staging](https://repository.apache.org/content/groups/staging/org/apache/xbean/xbean-asm9-shaded/4.22/) .May be  the Jfrog service I used locally delegate the staging ...

**Review by itholic — APPROVED** [review]
LGTM when the test pass

**Comment by LuciferYang** [comment]
All passed

**Review by dongjoon-hyun — COMMENTED** [review]
+1, LGTM. Thank you all.

**Pull request closed without merging**
