### PR TITLE
[SPARK-33313][TESTS][R][3.0][2.4] Add testthat 3.x support

### PR DESCRIPTION
**Pull request by HyukjinKwon**
### What changes were proposed in this pull request?

This PR proposes to port back https://github.com/apache/spark/pull/30219 but keeps testthat 1.x support in other branches.

This PR modifies `R/pkg/tests/run-all.R` by:

- ~Removing `testthat` 1.x support, as Jenkins has been upgraded to 2.x with SPARK-30637 and this code is no longer relevant.~
- Add `testthat` 3.x support to avoid CI failures.

### Why are the changes needed?

Currently used internal API has been removed in the latest `testthat` release.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Tests executed against `testthat == 2.3.2` and `testthat == 3.0.0`

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
@zero323 are you online? I'll merge this once the tests pass to unblock other builds in other branches but please take a look even after it was merged if you find some time.

**Review by srowen — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Thanks @srowen.

**Comment by HyukjinKwon** [comment]
I made some more additional changes to reduce the diff compared to master branch. I will merge as soon as the tests pass.

**Comment by HyukjinKwon** [comment]
Merged to branch-3.0 and branch-2.4.

**Pull request closed without merging**
