### PR TITLE
[SPARK-33475][BUILD] Bump ANTLR runtime version to 4.8-1

### PR DESCRIPTION
**Pull request by maropu**
### What changes were proposed in this pull request?

This PR intends to upgrade ANTLR runtime from 4.7.1 to 4.8-1.

### Why are the changes needed?

Release note of v4.8 and v4.7.2 (the v4.7.2 release has a few minor bug fixes for java targets): 
 - v4.8: https://github.com/antlr/antlr4/releases/tag/4.8
 - v4.7.2: https://github.com/antlr/antlr4/releases/tag/4.7.2

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

GA tests.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @hvanhovell FYI

**Review by hvanhovell — APPROVED** [review]
LGTM

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by dongjoon-hyun** [comment]
Late LGTM. Thank you all.

**Comment by HyukjinKwon** [comment]
Just quick question:

Do you guys know the diff between 4.8-1 vs 4.8? The official release seems to be 4.8 https://www.antlr.org/download/index.html - I checked the pom files and jars too.

**Comment by HyukjinKwon** [comment]
Maybe let's just use the 4.8 that's matched with the official releases there ...

Thanks for pointing this out, @bozhang2820. Mind making a quick followup to match this to 4.8?

**Comment by bozhang2820** [comment]
> Maybe let's just use the 4.8 that's matched with the official releases there ...
> 
> Thanks for pointing this out, @bozhang2820. Mind making a quick followup to match this to 4.8?

Sure. Created https://github.com/apache/spark/pull/32603.

**Pull request closed without merging**
