### PR TITLE
[SPARK-9833] [yarn] Add options to disable delegation token retrieval.

### PR DESCRIPTION
**Pull request by vanzin**
This allows skipping the code that tries to talk to Hive and HBase to
fetch delegation tokens, in case that somehow conflicts with the application
being run.

### CODE REVIEW

**Comment by vanzin** [comment]
retest this please

**Comment by vanzin** [comment]
retest this please

**Comment by vanzin** [comment]
retest this please

**Comment by vanzin** [comment]
sigh. retest this please

**Comment by vanzin** [comment]
retest this please

**Comment by tgravescs** [comment]
I'm not against this just wondering what the use case is here? Did you actually run into an issue?

**Comment by vanzin** [comment]
> Did you actually run into an issue?

Yes actually. Hive-on-Spark uses Spark to execute jobs, but not for metastore access. The inherited configuration sometimes has references to classes that are not in the Spark classpath (HS2 has access to those classes), and this code will try to load those classes and fail.

You could add these classes or filter the configuration, but the fact is that this application has no need for this feature, and there's no explicit way to disable it right now.

**Comment by vanzin** [comment]
retest this please

**Comment by tgravescs** [comment]
changes lgtm. Only thing would be if we want to make some common config name spark.yarn.access.* or other for everything access/token/security related.

@sryza  thoughts

**Comment by vanzin** [comment]
@tgravescs I chose a slightly different name than you suggested, how does that sound?

**Comment by tgravescs** [comment]
+1, looks good. go ahead and commit.

**Pull request closed without merging**
