### PR TITLE
[SPARK-45329][PYTHON][CONNECT] DataFrame methods skip pandas conversion

### PR DESCRIPTION
**Pull request by zhengruifeng**
### What changes were proposed in this pull request?
DataFrame methods avoid pandas conversion if possible

### Why are the changes needed?
minor optimization:

before: `arrow table` -> `pandas dataframe` -> `scalar result`

after: `arrow table` -> `scalar result`

### Does this PR introduce _any_ user-facing change?
no

### How was this patch tested?
ci

### Was this patch authored or co-authored using generative AI tooling?
no

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @xinrong-meng

**Comment by xinrong-meng** [comment]
Failed tests seem to be irrelevant to the PR, please retrigger them.
Otherwise looks great!
It would be nice to extract `table[0][0].to_py()` as a method or add a comment to help understand what it does. I don't have a strong opinion on that though.

**Review by xinrong-meng — APPROVED** [review]

**Comment by zhengruifeng** [comment]
> Failed tests seem to be irrelevant to the PR, please retrigger them. Otherwise looks great! It would be nice to extract `table[0][0].to_py()` as a method or add a comment to help understand what it does. I don't have a strong opinion on that though.

hmm, `table[0][0]` is to exact the first column of the first row, I guess it maybe straightforward

**Comment by zhengruifeng** [comment]
thanks, merged to master

**Pull request closed without merging**
