### PR TITLE
[SPARK-10816][SS] Support session window natively

### PR DESCRIPTION
**Pull request by HeartSaVioR**
### What changes were proposed in this pull request?

This PR proposes to support native session window. Please refer the comments/design doc in SPARK-10816 for more details on the rationalization and design (could be outdated a bit compared to the PR).

The definition of the boundary of "session window" is [the timestamp of start event ~ the timestamp of last event + gap duration). That said, unlike time window, session window is a dynamic window which can expand if new input row is added to the session. To handle expansion of session window, Spark defines session window per input row, and "merge" windows if they can be merged (boundaries are overlapped).

This PR leverages two different approaches on merging session windows:

1. merging session windows with Spark's aggregation logic (a variant of sort aggregation)
2. updating session window for all rows bound to the same session, and applying aggregation logic afterwards

First one is preferable as it outperforms compared to the second one, though it can be only used if merging session window can be applied altogether with aggregation. It is not applicable on all the cases, so second one is used to cover the remaining cases.

This PR also applies the optimization on merging input rows and existing sessions with retaining the order (group keys + start timestamp of session window), leveraging the fact the number of existing sessions per group key won't be huge.

The state format is versioned, so that we can bring a new state format if we find a better one.

### Why are the changes needed?

For now, to deal with sessionization, Spark requires end users to play with (flat)MapGroupsWithState directly which has a couple of major drawbacks:

1. (flat)MapGroupsWithState is lower level API and end users have to code everything in details for defining session window and merging windows
2. built-in aggregate functions cannot be used and end users have to deal with aggregation by themselves
3. (flat)MapGroupsWithState is only available in Scala/Java.

With native support of session window, end users simply use "session_window" like they use "window" for tumbling/sliding window, and leverage built-in aggregate functions as well as UDAFs to simply define aggregations.

Quoting the query example from test suite:

```
    val inputData = MemoryStream[(String, Long)]

    // Split the lines into words, treat words as sessionId of events
    val events = inputData.toDF()
      .select($"_1".as("value"), $"_2".as("timestamp"))
      .withColumn("eventTime", $"timestamp".cast("timestamp"))
      .selectExpr("explode(split(value, ' ')) AS sessionId", "eventTime")
      .withWatermark("eventTime", "30 seconds")

    val sessionUpdates = events
      .groupBy(session_window($"eventTime", "10 seconds") as 'session, 'sessionId)
      .agg(count("*").as("numEvents"))
      .selectExpr("sessionId", "CAST(session.start AS LONG)", "CAST(session.end AS LONG)",
        "CAST(session.end AS LONG) - CAST(session.start AS LONG) AS durationMs",
        "numEvents")
```

which is same as StructuredSessionization (native session window is shorter and clearer even ignoring model classes).

https://github.com/apache/spark/blob/39542bb81f8570219770bb6533c077f44f6cbd2a/examples/src/main/scala/org/apache/spark/examples/sql/streaming/StructuredSessionization.scala#L66-L105 

(Worth noting that the code in StructuredSessionization only works with processing time. The code doesn't consider old event can update the start time of old session.)

### Does this PR introduce _any_ user-facing change?

Yes. This PR brings the new feature to support session window on both batch and streaming query, which adds a new function "session_window" which usage is similar with "window".

### How was this patch tested?

New test suites. Also tested with benchmark code.

### CODE REVIEW

**Comment by viirya** [comment]
> This PR leverages two different approaches on merging session windows:
>    1. merging session windows with Spark's aggregation logic (a variant of sort aggregation)
>    2. updating session window for all rows bound to the same session, and applying aggregation logic afterwards

Is the second one the approach we took in #31570?

**Comment by HeartSaVioR** [comment]
> Is the second one the approach we took in #31570?

It's not copied from #31570 but the approach is similar. Actually, my old PR was having both approaches to address all cases.

**Comment by HeartSaVioR** [comment]
retest this, please

**Comment by HeartSaVioR** [comment]
cc. @tdas @zsxwing @viirya @xuanyuanking @gaborgsomogyi @Ngone51

Appreciate your efforts on reviewing. Thanks!

**Comment by HeartSaVioR** [comment]
Please let me know if the code diff is too huge to review in a single PR. I can leave this PR as reference and break down to several PRs. Probably need to add more code to ensure there're proper test suites per PR, but I can volunteer to add the new test suites. Really appreciated if someone can help adding test suites as well.

**Comment by xuanyuanking** [comment]
I can help to add test suites for the breakdown PRs. Let's leave this one as a panoramic pre-view PR for few days. Make sure others have no more opinions on the whole picture.

**Comment by viirya** [comment]
Sounds good to me. I will also help on new test suites.

**Comment by HeartSaVioR** [comment]
@xuanyuanking @viirya 
Sounds great! Thanks for lending your hands.

My current plan on breakdown of PR follows:

* UpdatingSessionIterator + UpdatingSessionIteratorSuite
* StreamingSessionWindowStateManager and relevant changes (StateStoreType, SymmetricHashJoinStateManager) - no test suite for StreamingSessionWindowStateManager now, volunteer welcome!
* MergingSortWithSessionWindowStateIterator - no test suite for now. volunteer welcome, or I can volunteer
* MergingSessionIterator - there's no test for AggregateIterator implementations so far, but would be good if we can have one for this
* all other parts including physical exec node for above iterators

Appreciate the voices on the plan; I'm also OK to attach physical exec node along with iterator (e.g. UpdatingSessionIterator + UpdatingSessionExec).

**Comment by HeartSaVioR** [comment]
Let me go through filing PRs as there doesn't look to be further voice on the overall direction.

**Comment by HeartSaVioR** [comment]
I filed 5 JIRA issues for all parts, and submitted 3 PRs which are not dependent to others. Remaining 2 parts depend on others and I'll deal with them once we merge dependents.

**Comment by xuanyuanking** [comment]
```
(no dependency) MergingSessionIterator - there's no test for AggregateIterator implementations so far, but would be good if we can have one for this. volunteer welcome!.
```
I'll take a look for this in this week :) .

**Comment by viirya** [comment]
Will take a look too. Thanks.

**Comment by HeartSaVioR** [comment]
UPDATE: I've added test suite for MergingSessionIterator and updated the relevant PR.

**Comment by HeartSaVioR** [comment]
UPDATE: I've added test suite for state store manager PR.

**Pull request closed without merging**
