### PR TITLE
[SPARK-34630][PYTHON] Add typehint for pyspark.__version__

### PR DESCRIPTION
**Pull request by Yikun**
### What changes were proposed in this pull request?
This PR adds the typehint of pyspark.__version__, which was mentioned in [SPARK-34630](https://issues.apache.org/jira/browse/SPARK-34630).

### Why are the changes needed?
There were some short discussion happened in https://github.com/apache/spark/pull/31823#discussion_r593830911 .

After further deep investigation on [1][2], we can see the `pyspark.__version__` is added by [setup.py](https://github.com/apache/spark/blob/c06758834e6192b1888b4a885c612a151588b390/python/setup.py#L201), it makes `__version__` embedded into pyspark module, that means the `__init__.pyi` is the right place to add the typehint for `__version__`. 

So, this patch adds the type hint `__version__` in pyspark/__init__.pyi.

[1] [PEP-396 Module Version Numbers](https://www.python.org/dev/peps/pep-0396/)
[2] https://packaging.python.org/guides/single-sourcing-package-version/
### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
1. Disable the ignore_error on
https://github.com/apache/spark/blob/ee7bf7d9628384548d09ac20e30992dd705c20f4/python/mypy.ini#L132

2. Run mypy:
- Before fix
```shell
(venv) ➜  spark git:(SPARK-34629) ✗ mypy --config-file python/mypy.ini python/pyspark | grep version
python/pyspark/pandas/spark/accessors.py:884: error: Module has no attribute "__version__"
```

- After fix
```shell
(venv) ➜  spark git:(SPARK-34629) ✗ mypy --config-file python/mypy.ini python/pyspark | grep version
```
no output

### CODE REVIEW

**Comment by Yikun** [comment]
cc @dannymeijer @zero323 @HyukjinKwon

**Review by HyukjinKwon — APPROVED** [review]
LGTM

**Comment by HyukjinKwon** [comment]
Merged to master and branch-3.1.

But @zero323 feel free to post-hoc review since you're the expert here :-)

**Comment by zero323** [comment]
I think it will require some changes. First of all `__version__` is defined in `python.version`

https://github.com/apache/spark/blob/0e761c7307e780bd1d6cfe40e3d17ad003768411/python/pyspark/version.pyi#L19

so we shouldn't really annotate it directly in `pyspark.__init__`.

It is imported there, but not placed in `__all__`, so it formally not considered as exported. 

We could cheat a bit and simply have 

```python
from pyspark.version import __version__  as __version__
```

but to be consistent, we should also add `__version__` to `__all__` and drop `noqa: F401` from 
 
https://github.com/apache/spark/blob/512f6258071666c3da07f6e6c6299d653a1cc370/python/pyspark/__init__.py#L63

**Comment by Yikun** [comment]
@zero323 It makes sense to me, we should make the `__version__` as exported, and I added a followup https://github.com/apache/spark/pull/32125 to fix it.

**Pull request closed without merging**
