### PR TITLE
[SPARK-25900][WEBUI]When the page number is more than the total page size, then fall back to the first page

### PR DESCRIPTION
**Pull request by shahidki31**
## What changes were proposed in this pull request?

When we give the page number more than the maximum page number, webui is throwing an exception. It would be better if fall back to the default page, instead of throwing the exception in the web ui.

## How was this patch tested?
Before PR:
screenshot from 2018-10-31 23-41-37

After PR:
screenshot from 2018-10-31 23-54-23

### CODE REVIEW

**Comment by shahidki31** [comment]
The code here (and all the other pages) intended to check out of bound exception and fall back to the first page. 
https://github.com/apache/spark/blob/bc9f9b4d6e6ac983a903a0b9a3a668950dc0b2a7/core/src/main/scala/org/apache/spark/ui/jobs/AllJobsPage.scala#L236-L244

**Review by srowen — APPROVED** [review]
I suppose the first page is better than an error here, and if it matches other pages' behavior, seems fine.

**Comment by shahidki31** [comment]
Yes. Thank you @srowen

**Review by gengliangwang — CHANGES_REQUESTED** [review]
Sorry but personally I am against the change.
In the page we already able to get the total number and total page size, so we just need to check to input and show some error message in the page(before page navigation).
Fall back to the first page is weird. User may not know what happen.

**Comment by shahidki31** [comment]
@gengliangwang IMHO, We should try to avoid exceptions in the WEBUI. 

User will come to know which page he is, from the page navigation bar.

**Comment by gengliangwang** [comment]
I prefer to  just highlight the invalid output. E.g.

image

image

**Comment by shahidki31** [comment]
The current behavior is, If we enter a value more than the maximum page number, the page navigation bar shows the user is in first page and throws an exception. So, if we really want to throw exception, then page navigation bar also need to change accordingly.

But still I believe, falling back to the first page is better. May be we can highlight above the table, that "Invalid page number, falling back to first page"

**Comment by gengliangwang** [comment]
> May be we can highlight above the table, that "Invalid page number, falling back to first page"

Yes, that's what I mean. 
No big deal but falling back to the first page seems unnecessary, we can return the same page again.

**Comment by srowen** [comment]
Returning to the current or last page seems fine too. No error message really needed IMHO.
However it sounds like other pages already go to the 1st page on invalid input? I'd also like to stay consistent.

**Comment by shahidki31** [comment]
Hi @srowen , The current behavior of WEBUI is,
1) When user enters a page size more than current page size, It falls back to first page (In all the pages)
2) When the user enters a page more than the maximum page number, page navigate to first page but throws an exception.

After the PR,
1) Behavior is same as before
2) Instead of throwing exception, page falls back into first page and display it contents.



> Returning to the current or last page seems fine too. No error message really needed IMHO.
Returning to current page seems more code change is required. Because we are getting all the parameters related to page from the url. Currently we are not passing any parameter to get which page he was previously. 
Also to make it consistent with the page size behaviour, we can return first page.

**Comment by gengliangwang** [comment]
> Returning to current page seems more code change is required. Because we are getting all the parameters related to page from the url. Currently we are not passing any parameter to get which page the user was on previously.

I come up with a new idea: how about navigate to the last page(max page number)? That makes more sense IMHO.

**Comment by srowen** [comment]
Yes if the behavior is consistent across pages that sounds like fine behavior.

**Comment by shahidki31** [comment]
Hi @gengliangwang , Yes. That also doable. Currently when the IndexOutOfBound Exception comes, the page is navigating to the first page. Also to make the behavior consistent with the page size check, I have preferred first page.

screenshot from 2018-11-01 22-07-43

**Comment by shahidki31** [comment]
Hi @srowen , After the PR, the following check also can be removed, because the check is for preventing the OutOfBoundException, But no OutOfBound exception happens after the PR.
screenshot from 2018-11-01 22-23-15

**Comment by shahidki31** [comment]
I have modified based on @gengliangwang 's suggestion. Also, we can remove the check for page size in all the page class, because we handle the same in the pagedTable class.

**Review by srowen — APPROVED** [review]
Yeah that's great cleanup if we can definitely handle the page and page size correctly right here.

**Comment by shahidki31** [comment]
We can remove the method 'prevPageSizeFormField' from pagedTable and corresponding page classes. Because this method is no longer required, as it was for checking IndexOutOfBound.

https://github.com/apache/spark/blob/e91b607719886b57d1550a70c0f9df4342d72989/core/src/main/scala/org/apache/spark/ui/PagedTable.scala#L83

**Comment by shahidki31** [comment]
I have tested all the scenarios in the WEBUI, and it is working as per expected.

**Review by gengliangwang — APPROVED** [review]
LGTM! Thanks for the work!

**Comment by shahidki31** [comment]
Thank you @gengliangwang

**Comment by shahidki31** [comment]
Jenkins, retest this please

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by shahidki31** [comment]
@srowen @gengliangwang There is one more place where the WEBUI can throw an exception.
https://github.com/apache/spark/blob/1a7abf3f453f7d6012d7e842cf05f29f3afbb3bc/core/src/main/scala/org/apache/spark/ui/PagedTable.scala#L36-L38

I will update the PR.

**Comment by shahidki31** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by shahidki31** [comment]
Hi @HyukjinKwon, Could you please retrigger the PR builder?

**Comment by gengliangwang** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by srowen** [comment]
Merged to master

**Comment by shahidki31** [comment]
Thank you @srowen

**Pull request closed without merging**
