### PR TITLE
[SPARK-37791][EXAMPLES] Use log4j2 in examples

### PR DESCRIPTION
**Pull request by williamhyun**
### What changes were proposed in this pull request?
This PR aims to use log4j2 in examples. 

### Why are the changes needed?
Since Spark is migrating to log4j2, we best use this in our examples. 

### Does this PR introduce _any_ user-facing change?
No. 

### How was this patch tested?
Manually review.

### CODE REVIEW

**Comment by williamhyun** [comment]
cc: @viirya and @dongjoon-hyun

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @williamhyun .

To @viirya , is there a reason why we still have these `log4j` usage instead of `log4j2`?

**Comment by viirya** [comment]
@dongjoon-hyun I missed these `log4j` usage in the examples. Actually they are on log4j 1.x bridge api, not log4j 1.x now. We should also move them to log4j2.

**Comment by dongjoon-hyun** [comment]
Got it. Thank you, @viirya . 

Merged to master. Thank you, @williamhyun and @viirya .

**Comment by dongjoon-hyun** [comment]
@williamhyun . While you are here, could you add a scalastyle to ban `org.apache.log4j`? It would be very helpful for preparing the removal of the bridge.

**Comment by viirya** [comment]
FYI. I'm going to remove bridge api usage at #35075.

**Comment by williamhyun** [comment]
Oh, I made a PR for adding a new checkstyle rule without seeing, #35075 .
- https://github.com/apache/spark/pull/35077

What can I proceed with #35075 , @viirya and @dongjoon-hyun ?

**Comment by dongjoon-hyun** [comment]
No problem. Just please wait a while. We will merge @viirya 's PR first. Then, you can rebase your PR against master branch, @williamhyun .

**Pull request closed without merging**
