### PR TITLE
[SPARK-21188][CORE] releaseAllLocksForTask should synchronize the whole method

### PR DESCRIPTION
**Pull request by liufengdb**
## What changes were proposed in this pull request?

Since the objects `readLocksByTask`, `writeLocksByTask` and `info`s are coupled and supposed to be modified by other threads concurrently, all the read and writes of them in the method `releaseAllLocksForTask` should be protected by a single synchronized block like other similar methods. 

## How was this patch tested?

existing tests

### CODE REVIEW

**Review by srowen — APPROVED** [review]
I think you have a point but CC @JoshRosen

**Comment by zsxwing** [comment]
ok to test.

cc @JoshRosen

**Comment by gatorsmile** [comment]
add to whitelist

**Comment by jiangxb1987** [comment]
retest this please

**Comment by JoshRosen** [comment]
I actually asked @liufengdb to submit this PR after he spotted this problem while debugging a test.

I did a bit of digging and spotted where this bug was introduced: in https://github.com/JoshRosen/spark/commit/b9d6e181db0c7293b0b00b3a679716f652df936f, an intermediate commit in an old PR, this was introduced when refactoring one map from a thread-safe LoadingCache (where entires were implicitly created) to an explicit map with explicit registration (which used synchronization). In making this change I incorrectly preserved a bad synchronization pattern which was unnecessarily fine-grained.

Therefore this looks like the right change to me so I'm going to retest and merge.

**Comment by JoshRosen** [comment]
jenkins retest this please

**Comment by zsxwing** [comment]
retest this please

**Comment by jiangxb1987** [comment]
retest this please

**Comment by zsxwing** [comment]
LGTM. Merging to master. Thanks!

**Pull request closed without merging**
