### PR TITLE
[SPARK-11297] Add new code tags

### PR DESCRIPTION
**Pull request by yinxusen**
@mengxr https://issues.apache.org/jira/browse/SPARK-11297

Add new code tags to hold the same look and feel with previous documents.

### CODE REVIEW

**Comment by rxin** [comment]
Can you post a before and after screenshot?

**Comment by yinxusen** [comment]
The original doc:

screen shot 2015-10-25 at 8 23 21 pm

doc with include_example

screen shot 2015-10-25 at 8 19 27 pm

doc with this PR:

screen shot 2015-10-25 at 8 21 56 pm

**Comment by yinxusen** [comment]
I just saw the difference between include_example.rb generated HTML and the original {% highlight %} generated HTML. The latter one substitutes some labels like \<div xxx\>\<pre\> with null string, and adds some new labels such as \<code class="language-scala" ...\>. The code itself has no effect on the font size, but I saw the CSS file at `spark/docs/_site/css` does.

**Comment by mengxr** [comment]
@yinxusen Could you check whether `Pygments` provides options to customize CSS? It seems possible from their doc: http://pygments.org/docs/quickstart/.

**Comment by yinxusen** [comment]
@mengxr Sure I'll try to do it.

**Comment by yinxusen** [comment]
@mengxr The simplest way to change the view is adding a css font constrain:

```css
div .highlight pre {
  font-size: 12px;
}
```

It controls the elements inslide `<div class="highlight"><pre>xxxxxx</pre></div>`. I also check the font sizes of other code examples, and they are 12px, which is defined in bootstrap.min.css. Instead of changing the code tag, I think modifing the css is better.

**Comment by mengxr** [comment]
LGTM. Merged into master. Thanks!

**Pull request closed without merging**
