### PR TITLE
[SPARK-31213][SQL] Arrange the sequence of the config of Spark SQL.

### PR DESCRIPTION
**Pull request by beliefer**
### What changes were proposed in this pull request?
The configuration of Spark SQL is a bit messy. Sorting them out can improve readability.
The configuration of sequence looks like below:
```
spark.sql.sources.A
spark.sql.sources.B
spark.sql.parquet.C
...
spark.sql.sources.D
spark.sql.optimizer.E
...
spark.sql.sources.F
spark.sql.parquet.G
...
```

### Why are the changes needed?
Improve readability.

### Does this PR introduce any user-facing change?
'No'.

### How was this patch tested?
Jenkins test.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
It's going to make tracking more difficult. In SQL documentation, they are already rendered as grouped by the namespace correctly so the actual benefit is just a bit of more code readability, which I think it isn't worthwhile.

**Review by HyukjinKwon — COMMENTED** [review]
It's going to make tracking more difficult. In SQL documentation, they are already rendered as grouped by the namespace correctly so the actual benefit is just a bit of more code readability, which I think it isn't worthwhile.

**Comment by beliefer** [comment]
@HyukjinKwon Yes, this PR just improve the readability. I've been trying for half a day to make them look more reasonable. This PR just adjusts the order of the code without any extra risk.

**Comment by srowen** [comment]
Yeah it's one of those totally reasonable things, that also complicates `git blame` and understanding where a change originally came from. I'm kind of neutral on it.

**Comment by beliefer** [comment]
I've looked at the history of GIT. These configuration items have been moved many times, even from different classes and modules. So these movements are relatively minor.

**Comment by HyukjinKwon** [comment]
Okay, I am neutral too. I don't mind if any committer merges.

**Pull request closed without merging**
