### PR TITLE
[doc][streaming] Fixed broken link in mllib section

### PR DESCRIPTION
**Pull request by BenFradet**
The commit message is pretty self-explanatory.

### CODE REVIEW

**Comment by srowen** [comment]
( -> [ LGTM. If I don't get to it first -- someone run jekyll locally instead of waiting for Jenkins to make sure the link is now OK.

**Comment by BenFradet** [comment]
I did run it locally, for information.

**Comment by mengxr** [comment]
Merged into master and branch-1.3. Thanks!

**Comment by BenFradet** [comment]
Glad I could help!

**Pull request closed without merging**
