### PR TITLE
revert [SPARK-22785][SQL] remove ColumnVector.anyNullsSet

### PR DESCRIPTION
**Pull request by cloud-fan**
## What changes were proposed in this pull request?

In https://github.com/apache/spark/pull/19980 , we thought `anyNullsSet` can be simply implemented by `numNulls() > 0`. This is logically true, but may have performance problems.

`OrcColumnVector` is an example. It doesn't have the `numNulls` property, only has a `noNulls` property. We will lose a lot of performance if we use `numNulls() > 0` to check null.

This PR simply revert #19980, with a renaming to call it `hasNull`. Better name suggestions are welcome, e.g. `nullable`?

## How was this patch tested?

existing test

### CODE REVIEW

**Comment by cloud-fan** [comment]
cc @kiszk @ueshin @viirya

**Comment by ueshin** [comment]
LGTM, and the name `hasNull` sounds fine to me, too.

**Comment by viirya** [comment]
Overall LGTM. One question is, at #19980, we replace `anyNullsSet` with some predicate of `numNulls` (like `numNulls == 0` or `numNulls` > 0) in many places, shall we use `hasNull` now for those checks?

**Comment by kiszk** [comment]
LGTM. It is fine with me for `hasNull`, to.

**Comment by cloud-fan** [comment]
thanks, merging to master/2.3!

**Comment by dongjoon-hyun** [comment]
Hi, @cloud-fan .
I reopen the JIRA since it's technically reverted. You can resolve that back with a new title like `Renaming anyNullsSet to hasNull` or something.

**Comment by cloud-fan** [comment]
thanks @dongjoon-hyun !

**Pull request closed without merging**
