### PR TITLE
[SPARK-30068][TESTS]Ignore ThriftServerPageSuite test

### PR DESCRIPTION
**Pull request by shahidki31**
ThriftServerPageSuite tests are failing due to mocking HttpServletRequest. This PR is to ignore the test, till fix the mock issue

### CODE REVIEW

**Comment by shahidki31** [comment]
Jenkins test this please

**Comment by shahidki31** [comment]
cc @wangyum

**Comment by wangyum** [comment]
Sorry @shahidki31. We didn't run test by Github actions: https://github.com/apache/spark/blob/master/.github/workflows/master.yml#L70
I tested it by another project:
https://github.com/spark-thriftserver/spark/pull/1/files#diff-85180f5a40eb76e2c165a40f7b73ff76R32

**Comment by shahidki31** [comment]
@wangyum Ok fine. Is it okay to merge this to unblock the tests?

**Comment by shahidki31** [comment]
@wangyum @dongjoon-hyun Is it okay to merge?

**Comment by dongjoon-hyun** [comment]
Shall we try to fix the root cause first?

**Comment by shahidki31** [comment]
@dongjoon-hyun It seems some issue with class loader, when using mockito. It seems SQL module doesn't have this issue. It would be great if you could help me to fix this issue, as I can't reproduce it in local setup.

**Pull request closed without merging**
