### PR TITLE
[SPARK-18674][SQL][Follow-Up] improve the error message of using join

### PR DESCRIPTION
**Pull request by gatorsmile**
### What changes were proposed in this pull request?
Added a test case for using joins with nested fields. 

### How was this patch tested?
N/A

### CODE REVIEW

**Comment by gatorsmile** [comment]
cc @cloud-fan @hvanhovell

**Comment by gatorsmile** [comment]
retest this please

**Comment by cloud-fan** [comment]
shall we put the test in `ResolveNaturalJoinSuite` and follow the code style there?

**Comment by rxin** [comment]
OK if you are improving this, can you fix the grammar? "USING column `col1.field1` can not be resolved with the left join side, the left output is: [col1]" technically is grammatically incorrect.

**Comment by gatorsmile** [comment]
Sure, will do it. Thanks!

**Comment by gatorsmile** [comment]
Just tried MySQL. The message is not good to me:
```
mysql> select * from t1 inner join t2 using (col2);
ERROR 1054 (42S22): Unknown column 'col2' in 'from clause'
```

Will try to improve it by:
```
Using column `col1.field1` cannot be resolved on the left side of the join. The left-side columns: [col1]
```

**Comment by rxin** [comment]
That SGTM

**Comment by rxin** [comment]
LGTM pending tests.

**Comment by gatorsmile** [comment]
retest this please

**Comment by cloud-fan** [comment]
thanks, merging to master/2.1!

**Pull request closed without merging**
