### PR TITLE
[SPARK-23510][SQL] Support Hive 2.2 and Hive 2.3 metastore 

### PR DESCRIPTION
**Pull request by gatorsmile**
## What changes were proposed in this pull request?
This is based on https://github.com/apache/spark/pull/20668 for supporting Hive 2.2 and Hive 2.3 metastore.

When we merge the PR, we should give the major credit to @wangyum 

## How was this patch tested?
Added the test cases

### CODE REVIEW

**Comment by gatorsmile** [comment]
retest this please

**Comment by gatorsmile** [comment]
cc @cloud-fan

**Comment by cloud-fan** [comment]
LGTM. In the future we should refactor this part so that adding a new version doesn't need to touch so many files.

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Pull request closed without merging**
