### PR TITLE
[SPARK-31253][SQL][followup] Add metrics to AQE shuffle reader

### PR DESCRIPTION
**Pull request by cloud-fan**
### What changes were proposed in this pull request?

This is a followup of https://github.com/apache/spark/pull/28022, to address three issues:
1. Add an assert in `CustomShuffleReaderExec` to make sure the partitions specs are all `PartialMapperPartitionSpec` or none.
2. Do not use `lazy val` for `partitionDataSizeMetrics` and `skewedPartitionMetrics`, as they will be merged into `metrics`, and `lazy val` will be serialized.
3. mark `metrics` as `transient`, as it's only used at driver-side
4. move `FileUtils.byteCountToDisplaySize` to `logDebug`, to save some calculation if log level is above debug.

### Why are the changes needed?

followup improvement

### Does this PR introduce any user-facing change?

no

### How was this patch tested?

existing tests

### CODE REVIEW

**Comment by cloud-fan** [comment]
cc @maryannxue @JkSelf

**Review by maryannxue — APPROVED** [review]
LGTM.

**Comment by gatorsmile** [comment]
Thanks! Merged to master.

**Comment by cloud-fan** [comment]
Shall we have AQE SQL metrics in 3.0 as well? Otherwise the AQE query plan is hard to debug. also cc @rxin @dongjoon-hyun

**Comment by dongjoon-hyun** [comment]
+1 for backporting the original and this follow-up to `branch-3.0`.
Thank you for pinging me, @cloud-fan .

**Pull request closed without merging**
