### PR TITLE
[SPARK-38096][BUILD] Update sbt to 1.6.2

### PR DESCRIPTION
**Pull request by martin-g**
### What changes were proposed in this pull request?

This PR aims to upgrade SBT to 1.6.2.

### Why are the changes needed?

Sbt 1.6.2 was released with minor improvements - https://eed3si9n.com/sbt-1.6.2

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

GA and AppVeyor.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
@martin-g mind enabling GitHub Actions in your forked repository? See also https://github.com/apache/spark/runs/5049316939

**Review by HyukjinKwon — APPROVED** [review]
LGTM if tests pass

**Comment by martin-g** [comment]
> @martin-g mind enabling GitHub Actions in your forked repository?

This was the reason why the first PR failed. Then I've enabled GHA on my fork and restarted the GHA checks by close+reopen the PR, but the AppVeyor check was still seeing the PR as closed. So, I closed the previous PR and opened this one.

**Review by LuciferYang — APPROVED** [review]
LGTM +1

**Comment by HyukjinKwon** [comment]
Ah, I see. Do you mind rebasing or pushing an empty commit e.g., `git commit --allow-empty`?

**Comment by martin-g** [comment]
@HyukjinKwon Push empty commit for this PR ? Is it needed ? All seems good here.
The problematic PR was https://github.com/apache/spark/pull/35387. Its [check](https://github.com/apache/spark/runs/5049316939) failed.
But all checks for this PR passed.

**Comment by HyukjinKwon** [comment]
Seems like it's disabled in your forked repo (https://github.com/martin-g/spark/actions/workflows/build_and_test.yml):

Screen Shot 2022-02-03 at 9 38 07 PM

Yeah, it passed in AppVeyor but the main build has not actually got triggered. I think it's best to make sure the main build passes.

**Comment by HyukjinKwon** [comment]
👍

**Comment by martin-g** [comment]
Thanks for explaining! It seems there were more clicks needed!
I've enabled all workflows but `Close stale PRs` and `Publish Snapshot `.
I've just rebased from laster master and force pushed.

**Comment by martin-g** [comment]
Is it expected the build in my fork to fail with:
```

2s
Run echo "APACHE_SPARK_REF=$(git rev-parse HEAD)" >> $GITHUB_ENV
From https://github.com/martin-g/spark
 * branch                  master     -> FETCH_HEAD
Already up to date. (nothing to squash)
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
Error: Process completed with exit code 1.
```
e.g. https://github.com/martin-g/spark/runs/5052103135?check_suite_focus=true
It fails because there is nothing to merge at https://github.com/apache/spark/blob/b63a577b656b5fc56feef1666d1f4d1048b945fe/.github/workflows/build_and_test.yml#L119

**Comment by martin-g** [comment]
https://github.com/martin-g/spark/runs/5051700359 started earlier. Its job `Sync the current branch with the latest in Apache Spark` started at `Thu, 03 Feb 2022 12:46:10 GMT` and merged few files:
```
Thu, 03 Feb 2022 12:46:10 GMT
Run echo "APACHE_SPARK_REF=$(git rev-parse HEAD)" >> $GITHUB_ENV
Thu, 03 Feb 2022 12:46:10 GMT From https://github.com/martin-g/spark
Thu, 03 Feb 2022 12:46:10 GMT  * branch                  sbt-1.6.2  -> FETCH_HEAD
Thu, 03 Feb 2022 12:46:11 GMT Updating 6347857f0b..2a04a12f29
Thu, 03 Feb 2022 12:46:11 GMT Fast-forward
Thu, 03 Feb 2022 12:46:11 GMT Squash commit -- not updating HEAD
Thu, 03 Feb 2022 12:46:11 GMT  dev/appveyor-install-dependencies.ps1 | 2 +-
Thu, 03 Feb 2022 12:46:11 GMT  project/build.properties              | 2 +-
Thu, 03 Feb 2022 12:46:11 GMT  2 files changed, 2 insertions(+), 2 deletions(-)
Thu, 03 Feb 2022 12:46:11 GMT [master 5d149ac393] Merged commit
Thu, 03 Feb 2022 12:46:11 GMT  2 files changed, 2 insertions(+), 2 deletions(-)
```

but https://github.com/martin-g/spark/runs/5052103135?check_suite_focus=true had nothing to merge and failed:
```
Thu, 03 Feb 2022 13:20:01 GMT
Run echo "APACHE_SPARK_REF=$(git rev-parse HEAD)" >> $GITHUB_ENV
Thu, 03 Feb 2022 13:20:02 GMT From https://github.com/martin-g/spark
Thu, 03 Feb 2022 13:20:02 GMT  * branch                  master     -> FETCH_HEAD
Thu, 03 Feb 2022 13:20:02 GMT Already up to date. (nothing to squash)
Thu, 03 Feb 2022 13:20:03 GMT On branch master
Thu, 03 Feb 2022 13:20:03 GMT Your branch is up to date with 'origin/master'.
Thu, 03 Feb 2022 13:20:03 GMT
Thu, 03 Feb 2022 13:20:03 GMT nothing to commit, working tree clean
Thu, 03 Feb 2022 13:20:03 GMT Error: Process completed with exit code 1.
```

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by dongjoon-hyun** [comment]
The last commit passed. Merged to master.
- https://github.com/martin-g/spark/runs/5051700359

**Comment by dongjoon-hyun** [comment]
Welcome to the Apache Spark community, @martin-g .
I added you to the Apache Spark contributor group and assigned SPARK-38096 to you.

**Pull request closed without merging**
