### PR TITLE
[SPARK-16359][STREAMING][KAFKA] unidoc skip kafka 0.10

### PR DESCRIPTION
**Pull request by koeninger**
## What changes were proposed in this pull request?

during sbt unidoc task, skip the streamingKafka010 subproject and filter kafka 0.10 classes from the classpath, so that at least existing kafka 0.8 doc can be included in unidoc without error
## How was this patch tested?

sbt spark/scalaunidoc:doc | grep -i error

### CODE REVIEW

**Comment by srowen** [comment]
It doesn't work to only keep the 0.10 classes? I was hoping they'd be a superset of 0.8 for these purposes. Can we skip generating javadoc for one of them rather than modify the classpath, if necessary?

**Comment by koeninger** [comment]
Keeping the 0.10 classes might work if we want to skip publishing 0.8, but
trying to skip publishing 0.10 did not work until I modified the classpath
for the unidoc task.  0.8 would error, apparently due to changed methods in
0.10. Skipping both might work.

Either way there's still the question of where / how to publish the api doc
for the Kafka connector.  Only options I can see are publish it
separately;  or run unidoc with the exclusions, run scaladoc for the
excluded project(s), then script merging them.

**Comment by srowen** [comment]
I suppose publishing one version's docs is better than none. Is it possible to publish 0.10 only?

**Comment by shivaram** [comment]
I just noticed that our nightly docs build has been failing with an error related to kafka (Example [1]). Will this PR fix this or should we open a new JIRA for this ?

[1] https://amplab.cs.berkeley.edu/jenkins/view/Spark%20Packaging/job/spark-branch-2.0-docs/209/consoleFull

**Comment by srowen** [comment]
Same error, yes.

**Comment by tdas** [comment]
Does anyone know why does unidoc fail? Is it because unidoc is combining both kafka 0.8 and 0.10 in the compile path and therefore causing problems?

**Comment by tdas** [comment]
In any case, we have to release rc2 soon and that cannot be done with a broken unidoc. And between 0.8 and 0.10, 0.8 is higher priority for having docs because it is stable API. So LGTM for this PR, will merge to master and 2.0 as soon as tests pass.

**Comment by koeninger** [comment]
That build error looks hive related... I can try merging latest master

@tdas yes, the reason unidoc is failing is because it's throwing all dependencies from all subprojects into one classpath when running scaladoc/javadoc

**Comment by koeninger** [comment]
From this + looking at jenkins, it seems like master is broken

**Comment by tdas** [comment]
yeah. @zsxwing is looking into it.

**Comment by tdas** [comment]
Since build passed, merging this to master and 2.0

**Pull request closed without merging**
