### PR TITLE
[SPARK-48872][PYTHON] Reduce the overhead of _capture_call_site

### PR DESCRIPTION
**Pull request by ueshin**
### What changes were proposed in this pull request?

Reduces the overhead of `inspect.stack` in `_capture_call_site` by inlining `inspect.stack` with using `generator` instead of `list`.
Also, specify `context=0` for `inspect.getframeinfo` to avoid unnecessary field retrievals.

### Why are the changes needed?

The `_capture_call_site` has inevitable overhead when `Column` operations happen a lot, but it can be reduced.

E.g.,

```py
from functools import reduce

def alias_schema():
    return df.select(reduce(lambda x, y: x.alias(f"col_a_{y}"), range(20), F.col("a"))).schema
profile(alias_schema)
```

Screenshot 2024-07-11 at 15 24 31

The function calls and duration are:

- before

```
        18013240 function calls (18012760 primitive calls) in 2.327 seconds

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
...
      200    0.001    0.000    2.231    0.011 /.../python/pyspark/errors/utils.py:164(_capture_call_site)

```

- after

```
         1421240 function calls (1420760 primitive calls) in 0.265 seconds

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
...
      200    0.001    0.000    0.182    0.001 /.../python/pyspark/errors/utils.py:165(_capture_call_site)

```

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

The existing tests.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by ueshin** [comment]
cc @itholic @HyukjinKwon @zhengruifeng

**Review by itholic — APPROVED** [review]
LGTM if test passes.

nit: maybe do we want to add the `[PYTHON]` label for the PR title??

**Comment by ueshin** [comment]
> nit: maybe do we want to add the [PYTHON] label for the PR title??

Oops, forgot it. Thanks!

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
