### PR TITLE
[SPARK-32531][SQL][TEST] Add benchmarks for nested structs and arrays for different file formats

### PR DESCRIPTION
**Pull request by msamirkhan**
### What changes were proposed in this pull request?
Added benchmarks and tests for reading/writing nested/array'd structs.

### Why are the changes needed?
We had found that Spark performance was slow as compared to PIG on some schemas in our pipelines. On investigation, it was these cases which were the problem and they were not being profiled by the current benchmarks.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Ran benchmarks and tests using jdk-1.8

### CODE REVIEW

**Comment by viirya** [comment]
ok to test

**Comment by dongjoon-hyun** [comment]
Thank you for your first contribution, @msamirkhan !

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
Could you split the PR into two because your `ReadSchemaTest` test coverage addition is worth to have an independent JIRA ID?

**Comment by msamirkhan** [comment]
> Could you split the PR into two because your `ReadSchemaTest` test coverage addition is worth to have an independent JIRA ID?

Yes, will do that.

**Comment by msamirkhan** [comment]
> Could you split the PR into two because your `ReadSchemaTest` test coverage addition is worth to have an independent JIRA ID?

Apologies for the delay. Split the tests into https://github.com/apache/spark/pull/29573

**Pull request closed without merging**
