### PR TITLE
[SPARK] [Scheduler] Configurable default scheduling mode

### PR DESCRIPTION
**Pull request by blyncsy-david-lewis**
Pulling default values for scheduling mode from spark conf.

### CODE REVIEW

**Comment by jiangxb1987** [comment]
Could you elaborate on the scenario that you should need to make these settings configurable?

**Comment by blyncsy-david-lewis** [comment]
I have a multiuser application where I use the userId as the name of the scheduling pool so that users are balanced equally by spark and within a user's workload I can set the scheduling mode to FAIR (or whatever I want). It is unreasonable to specify xml for each user and restart spark, so this patch allows me to specify the default configuration used by undefined pools.

**Comment by varuvish** [comment]
Can you guarantee that your users share an even workload? With this setup you could potentially have a user with a high workload using 1/#users resources. Wouldn't using the queue feature be better?

**Review by varunvish910 — COMMENTED** [review]
Can you guarantee that your users share an even workload? With this setup you could potentially have a user with a high workload using 1/#users resources. Wouldn't using the queue feature be better?

**Comment by HyukjinKwon** [comment]
ping @blyncsy-david-lewis for @varuvish 's comment. Otherwise let me propose to close it for now.

**Pull request closed without merging**
