### PR TITLE
[SPARK-40933][SQL] Reimplement df.stat.{cov, corr} with built-in sql functions

### PR DESCRIPTION
**Pull request by zhengruifeng**
### What changes were proposed in this pull request?
Make df.stat.{cov, corr} consistent with sql functions

### Why are the changes needed?
it is weird to have two implemetations in SQL

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
existing UTs

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]
LGTM but to confirm, are they exactly same? or are there corcer case behaciour differences? If there are, we should note it in the migration guide.

**Comment by zhengruifeng** [comment]
seems different null handling, let me update this PR

**Comment by zhengruifeng** [comment]
@HyukjinKwon as far as I know, they are the seem now. 

the original tests didn't cover null handling and empty dataset, I add a new UT to make sure no behavior change.

**Review by itholic — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
