### PR TITLE
[SPARK-9926] [SQL] parallelize file listing for partitioned Hive table

### PR DESCRIPTION
**Pull request by piaozhexiu**
Instead of listing files on a per-partition basis, listing all the partitions together in parallel improves query performance quite a bit.

Here are benchmark results of my test query in the [jira](https://issues.apache.org/jira/browse/SPARK-9926) w/ setting `mapreduce.input.fileinputformat.list-status.num-threads` to 25-
- Parquet-backed Hive table
- Partitioned by dateint and hour
- Stored on S3

| # of files | # of partitions | before | after | improvement |
| --- | --- | --- | --- | --- |
| 972 | 1 | 38 secs | 20 secs | 1.9x |
| 13646 | 24 | 354  secs | 28 secs | 12x |
| 136222 | 240 | 3507  secs | 156 secs | 22x |

The changes include-
- Added a new property `spark.sql.hive.parallelFileListing` that enables parallel file listing in a partitioned Hive table backed by Hadoop storage such as HDFS and S3. By default, false.
- When the property is true, `TableReader` computes input splits for all the partitions in parallel and cache them in `HadoopRDD`.
- In `HadoopRDD.getPartitions()`, first check whether input splits are already computed, and if so, reuse them.

### CODE REVIEW

**Comment by piaozhexiu** [comment]
For some reason, jenkins keeps getting timed out.

**Comment by watermen** [comment]
retest this please

**Comment by piaozhexiu** [comment]
I think unit tests time out because multiple test cases concurrently access `inputSplitsCache` that I introduced in `SparkHadoopUtil`. I will convert that central cache into local cache in `HadoopRDDs`. Hopefully that will fix the time out.

**Comment by piaozhexiu** [comment]
This PR is superseded by #8512. Closing.

**Pull request closed without merging**
