### PR TITLE
[SPARK-41769][MINOR] Remove useless semicolons

### PR DESCRIPTION
**Pull request by smallzhongfeng**
### What changes were proposed in this pull request?

Remove useless semicolons. 

### Why are the changes needed?

Scala syntax does not require semicolons.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Origin uts.

### CODE REVIEW

**Review by srowen — COMMENTED** [review]
This is just too minor to bother with, unless you're removing all of them

**Comment by smallzhongfeng** [comment]
> This is just too minor to bother with, unless you're removing all of them

Yes. At present, I have searched all the codes, and there is no similar use

**Comment by smallzhongfeng** [comment]
> This is just too minor to bother with, unless you're removing all of them

At present, I have searched all the codes, and there is no similar use.

**Comment by srowen** [comment]
Oof ok that's a lot of change. The only downside is it could add spurious merge conflicts, for no real gain. I think we'd just fix this when otherwise touching the code

**Comment by smallzhongfeng** [comment]
> Oof ok that's a lot of change. The only downside is it could add spurious merge conflicts, for no real gain. I think we'd just fix this when otherwise touching the code

Yes, the essence is to standardize the code.

**Comment by smallzhongfeng** [comment]
> Oof ok that's a lot of change. The only downside is it could add spurious merge conflicts, for no real gain. I think we'd just fix this when otherwise touching the code

Agree with you, but I think the solution is not complicated to others.

**Comment by smallzhongfeng** [comment]
@HyukjinKwon @srowen Please tell me whether the pr is reasonable. Could you give me some suggestions?

**Comment by srowen** [comment]
I don't think it's worth bulk-changing if it's that many, and not really worth changing bits and pieces just for this. I'd just leave it. semicolons are legal, even if superfluous

**Comment by smallzhongfeng** [comment]
Thanks for your suggestion. So I have closed it.

**Pull request closed without merging**
