### PR TITLE
[SPARK-19057][ML] Instances' weight must be non-negative

### PR DESCRIPTION
**Pull request by zhengruifeng**
## What changes were proposed in this pull request?
1, add non-negative checking in `Instance`
2, fix doc

## How was this patch tested?
existing tests

### CODE REVIEW

**Comment by srowen** [comment]
The doc fixes look unrelated; let's exclude those?
There are many weight fields/args in .ml that should probably also be checked -- would you please skim them and see if there are other obviously points where the caller could supply a weight that's negative? I agree that there is almost never a good reason to supply them, though in some particular cases you can make out a coherent meaning.

**Comment by sethah** [comment]
I tend to think the actual algorithms should handle invalid weights, instead of adding that check into instance creation. Also, this will add overhead each time an instance is created. 

Unless this solves some specific problem, I'm not sure I'm in favor of the change.

**Comment by srowen** [comment]
Reasonable, yeah, though I think the usages in the existing algorithms will all have no meaningful interpretation of negative weights. At the least this could be more targeted to code paths where they will definitely not have meaning, and where they can be checked once, early.

**Comment by jkbradley** [comment]
+1 for @sethah 's comment: Algorithms should validate input data.  Some already do: https://github.com/apache/spark/blob/b67b35f76b684c5176dc683e7491fd01b43f4467/mllib/src/main/scala/org/apache/spark/ml/classification/LogisticRegression.scala#L341

**Comment by zhengruifeng** [comment]
@srowen OK. This is the list of algs that deals with weights:

**Comment by zhengruifeng** [comment]
Agreed. Now five algs inherit `HasWeightCol`: GLR/LoR/LiR/NB/IsotonicReg
I found that some algs use `RDD[Instance]` in `train` : GLR/LoR/LiR 
```
val instances: RDD[Instance] =
      dataset.select(col($(labelCol)), w, col($(featuresCol))).rdd.map {
        case Row(label: Double, weight: Double, features: Vector) =>
          Instance(label, weight, features)
      }
```
NB can also be modified to start with `RDD[Instance]`.
We can create a new API `extractInstance` in `Predictor` and validate weight in it, like the way that we check `label` in `extractLabeledPoints(dataset: Dataset[_], numClasses: Int)` in `Classifier`.
For IsotonicReg, we add a validatation in `extractWeightedLabeledPoints`.
What about this plan? @srowen @sethah @jkbradley

**Comment by zhengruifeng** [comment]
I think it better to discuss in the JIRA. When we come to an agreement, I will reopen this pr.

**Pull request closed without merging**
