### PR TITLE
[SPARK-34970][SQL][SERCURITY][3.1] Redact map-type options in the output of explain()

### PR DESCRIPTION
**Pull request by gengliangwang**
### What changes were proposed in this pull request?

The `explain()` method prints the arguments of tree nodes in logical/physical plans. The arguments could contain a map-type option that contains sensitive data.
We should map-type options in the output of `explain()`. Otherwise, we will see sensitive data in explain output or Spark UI.
image

### Why are the changes needed?

Data security.

### Does this PR introduce _any_ user-facing change?

Yes, redact the map-type options in the output of `explain()`

### How was this patch tested?

Unit tests

### CODE REVIEW

**Comment by gengliangwang** [comment]
This is to backport https://github.com/apache/spark/pull/32066 to branch-3.1

**Review by maropu — APPROVED** [review]

**Comment by gengliangwang** [comment]
merging to 3.1

**Comment by dongjoon-hyun** [comment]
@gengliangwang Could you make a backport to branch-3.0, too?

**Comment by gengliangwang** [comment]
@dongjoon-hyun Sure, I will backport to 3.0 and update the JIRA

**Comment by dongjoon-hyun** [comment]
Thank you!

**Pull request closed without merging**
