### PR TITLE
[SPARK-36384][CORE][DOC] Add doc for shuffle checksum

### PR DESCRIPTION
**Pull request by Ngone51**
### What changes were proposed in this pull request?

Add doc for the shuffle checksum configs in `configuration.md`.

### Why are the changes needed?

doc 

### Does this PR introduce _any_ user-facing change?

No, since Spark 3.2 hasn't been released.

### How was this patch tested?

Pass existed tests.

### CODE REVIEW

**Comment by Ngone51** [comment]
cc @mridulm @otterc Please take a look, thanks!

**Review by otterc — APPROVED** [review]
Looks good to me.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master and branch-3.2.

**Comment by mridulm** [comment]
Late LGTM, thanks for adding this @Ngone51 !

**Comment by Ngone51** [comment]
Thanks all!

**Comment by Ngone51** [comment]
Thanks all!

**Pull request closed without merging**
