### PR TITLE
[SPARK-38949][SQL][3.3] Wrap SQL statements by double quotes in error messages

### PR DESCRIPTION
**Pull request by MaxGekk**
### What changes were proposed in this pull request?
In the PR, I propose to wrap any SQL statement in error messages by double quotes "", and apply new implementation of `QueryErrorsBase.toSQLStmt()` to all exceptions in `Query.*Errors` w/ error classes. Also this PR modifies all affected tests, see the list in the section "How was this patch tested?".

### Why are the changes needed?
To improve user experience with Spark SQL by highlighting SQL statements in error massage and make them more visible to users.

### Does this PR introduce _any_ user-facing change?
Yes. The changes might influence on error messages that are visible to users.

Before:
```sql
The operation DESC PARTITION is not allowed
```

After:
```sql
The operation "DESC PARTITION" is not allowed
```

### How was this patch tested?
By running affected test suites:
```
$ build/sbt "sql/testOnly *QueryExecutionErrorsSuite"
$ build/sbt "sql/testOnly *QueryParsingErrorsSuite"
$ build/sbt "sql/testOnly *QueryCompilationErrorsSuite"
$ build/sbt "test:testOnly *QueryCompilationErrorsDSv2Suite"
$ build/sbt "test:testOnly *ExtractPythonUDFFromJoinConditionSuite"
$ build/sbt "testOnly *PlanParserSuite"
$ build/sbt "sql/testOnly *SQLQueryTestSuite -- -z transform.sql"
$ build/sbt "sql/testOnly *SQLQueryTestSuite -- -z join-lateral.sql"
$ build/sbt "sql/testOnly *SQLQueryTestSuite -- -z describe.sql"
```

Authored-by: Max Gekk <max.gekk@gmail.com>
Signed-off-by: Max Gekk <max.gekk@gmail.com>
(cherry picked from commit 5aba2b38beae6e1baf6f0c6f9eb3b65cf607fe77)
Signed-off-by: Max Gekk <max.gekk@gmail.com>

### CODE REVIEW

**Comment by MaxGekk** [comment]
@cloud-fan @HyukjinKwon @gengliangwang Could you approve the backport, please.

**Review by gengliangwang — APPROVED** [review]

**Review by cloud-fan — APPROVED** [review]

**Comment by MaxGekk** [comment]
GAs passed. Merging to 3.3.
Thank you, @gengliangwang and @cloud-fan for review.

**Review by HyukjinKwon — COMMENTED** [review]
Max, quick question. Why dose it not fix what the PR description says at https://github.com/MaxGekk/spark/blob/1bdb7552bf9c1543e35cef6773e01adb5830f40c/sql/core/src/test/resources/sql-tests/results/describe.sql.out#L465?

**Comment by MaxGekk** [comment]
@HyukjinKwon After offline discussion w/ @srielau, I reverted the changes by https://github.com/apache/spark/pull/36363

**Pull request closed without merging**
