### PR TITLE
[SPARK-19789][SS]Add the shortcut of .format("parquet").option("path", "/hdfs/path").partitionBy("col1", "col2").start()	

### PR DESCRIPTION
**Pull request by CodingCat**
## What changes were proposed in this pull request?

as said in the title, everytime I use parquet, I need to type a long string
Being consistent with DataFrameReader/Writer, DataStreamReader, add parquet shortcut for this case

## How was this patch tested?

existing test

### CODE REVIEW

**Comment by CodingCat** [comment]
@zsxwing , mind reviewing it?

**Comment by CodingCat** [comment]
ping

**Comment by CodingCat** [comment]
ping

**Comment by zsxwing** [comment]
Sorry for the delay. There was a debate in the initial PR and we decided to not add it: https://github.com/apache/spark/pull/13653#r66888185

**Comment by CodingCat** [comment]
OK, close this one

**Comment by CodingCat** [comment]
thanks

**Pull request closed without merging**
