### PR TITLE
[SPARK-45122][DOCS] Automate updating versions.json

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
- After PR [[SPARK-44742] [PYTHON] [DOCS] Add Spark version drop down to the PySpark doc site](https://github.com/apache/spark/pull/42428), our PySpark documents began to support dropdown boxes for easy selection of older versions.
We should automate the updates to the versions.json file.
- The pr aims to make automate updating versions.json.

### Why are the changes needed?
- To implement the following discussion:
https://github.com/apache/spark/pull/42428#discussion_r1301571573
image

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
- Manually test
- Pass GA.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by panbingkun** [comment]
Let it run CI first.

**Comment by panbingkun** [comment]
cc @srowen @HyukjinKwon

**Comment by srowen** [comment]
Seems OK. We also have to at some point remove older releases from the dropdown

**Comment by panbingkun** [comment]
> Seems OK. We also have to at some point remove older releases from the dropdown

At present, I haven't thought of it because it seems difficult to define `what is older releases`? Perhaps manual deletion is a possible option.

**Pull request closed without merging**
