### PR TITLE
[SPARK-38129][SQL] Adaptively enable timeout for BroadcastQueryStageExec in AQE

### PR DESCRIPTION
**Pull request by weixiuli**
### What changes were proposed in this pull request?
In the [SPARK-36414](https://issues.apache.org/jira/browse/SPARK-36414), it disabled timeout for all BroadcastQueryStageExecs in AQE,  there may be a regression in AQE when a BroadcastQueryStageExec doesn't come from shuffle query stages, such as a large table misjudged a small one in broadcastHashJoin，and broadcasting the table may take a long time which is no better than SortMergeJoin(when the job timeout and rerun it with spark.sql.autoBroadcastJoinThreshold=-1), and the timeout is necessary for BroadcastQueryStageExec in this case.

So, we should disable timeout for BroadcastQueryStageExec when it comes from shuffle query stages which runtime statistics are usually correct in AQE, but should enable timeout for it when it comes from others which statistics may be incorrect, and keep it the same as non-AQE.

### Why are the changes needed?

Avoid regression in AQE 

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Add unittests.

### CODE REVIEW

**Comment by weixiuli** [comment]
ping @yaooqinn   @cloud-fan Could you help me to take a look when you have time? thanks.

**Comment by cloud-fan** [comment]
This reverts [SPARK-36414](https://issues.apache.org/jira/browse/SPARK-36414), right? If a query has many broadcast stages (not converted from shuffle), and the broadcast may be waiting to be scheduled for a long time, having a timeout will break valid queries.

Unfortunately, we don't have a good solution for it today. One idea is to make the broadcast itself dynamic: it should cancel the job if it has already collected much data at the driver side.

**Comment by weixiuli** [comment]
> This reverts [SPARK-36414](https://issues.apache.org/jira/browse/SPARK-36414), right? 

This does not revert  [SPARK-36414](https://issues.apache.org/jira/browse/SPARK-36414)，it keep disable timeout for broadcast stages that is converted from  shuffle  in AQE.
> One idea is to make the broadcast itself dynamic: it should cancel the job if it has already collected much data at the driver side.

This is a good idea, in fact, JD production has done that by checkinng whether broadcast Stages have tasks running In non-AQE.  If a broadcast stage timeout with no one task running, means that it is not scheduled and should retry wait(we use spark.sql.broadcastMaxRetries to do that), if a broadcast stage timeout with some tasks running, we should cancel the job.

What do you think about the mechanism above to use for AQE  broadcast stages(not converted from shuffle)?  @cloud-fan

**Comment by cloud-fan** [comment]
> it keeps the disable timeout for broadcast stages that is converted from shuffle in AQE.

This is not sufficient. The timeout can never be accurate because the scheduler is a black box to the SQL engine. We don't know what happens there and are not sure we should keep waiting or give up.

The same problem applies to your proposal as well. Maybe the broadcast job has been waiting for 10 mins and submits the first task, then hits timeout and is killed.

I think the broadcast job should take care of the data size, not time. The scheduler is a black box and time doesn't tell much. But data size is accurate. The broadcast job knows when one task completes and gets the result of this task. If the collected data size is too large, we can fail this broadcast job (or turn it back to shuffle join?).

**Comment by weixiuli** [comment]
@cloud-fan  I agree with you, BTW disable timeout for all broadcast stages in AQE is not reasonable, right?  should we disable timeout for broadcast stages  that is converted from shuffle in AQE firstly, and to solve the broadcast stages that is not converted from shuffle  secondly ?

**Pull request closed without merging**
