### PR TITLE
[SPARK-28647][WEBUI] Recover additional metric feature and remove additional-metrics.js

### PR DESCRIPTION
**Pull request by sarutak**
## What changes were proposed in this pull request?

By SPARK-17019, `On Heap Memory` and `Off Heap Memory` are introduced as optional metrics.
But they are not displayed because they are made `display: none` in css and there are no way to appear them.

I know #22595 also try to resolve this issue but that will use `additional-metrics.js`.
Initially, `additional-metrics.js` is created for `StagePage` but `StagePage` currently uses `stagepage.js` for its additional metrics to be toggle because `DataTable (one of jQuery plugins)` was introduced and we needed another mechanism to add/remove columns for additional metrics.

Now that `ExecutorsPage` also uses `DataTable` so it might be better to introduce same mechanism as `StagePage` for additional metrics.

Screenshot from 2019-08-10 05-37-25

And then, we can remove `additional-metrics.js` which is no longer used from anywhere.

## How was this patch tested?

After this change is applied, I confirmed `ExecutorsPage` and `StagePage` are properly rendered and all checkboxes for additional metrics work.

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Hi, @sarutak . 
So, do you mean the feature is refactored correctly?
1. `expand-additional-metrics` is used `[SPARK-17019][CORE] Expose on-heap and off-heap memory usage in various places` (a4491626ed8169f0162a0dfb78736c9b9e7fb434).
2. According to the comment, https://github.com/apache/spark/pull/22595#issuecomment-509055933, and your comment, it's not working as of now.

I'm wondering if we keep the same feature which SPARK-17019 aimed originally. Could you give me some pointer? For GPU support, #25037 wants to this additional metric features. So, I want to be careful before removal.

cc @jerryshao , @tgravescs

**Comment by dongjoon-hyun** [comment]
Also, could you file a JIRA issue since this might cause some issues later. `JIRA ID` is a better pointer than `the git hash` in that case.

**Comment by tgravescs** [comment]
I agree with @dongjoon-hyun  please file a jira for this.  It does looks like its something I missed when we did the StagePage.

I kind of think the new PR is probably easier for users to read with separate columns but your point is valid, it would be nice to know if there is anything else missing there.  Also the last comments on the new PR are to separate out columns, not sure if this code would help with that at all, but I'm guessing we can reuse code from the Stage Page if you want to keep the look the same.

**Review by srowen — COMMENTED** [review]
Looks OK to me.

**Comment by sarutak** [comment]
OK, I've filed.
@dongjoon-hyun 
> expand-additional-metrics is used [SPARK-17019][CORE] Expose on-heap and off-heap memory usage in various places (a449162).
It seems `expand-additionl-metrics` is not used in the current code but...

> According to the comment, #22595 (comment), and your comment, it's not working as of now.
Yes, this PR seems to conflict with #22595.

So, how about having check-boxes for toggle like implemented in Stage Page?

**Comment by hacker131** [comment]
LGTM

**Comment by hacker131** [comment]
LGTM

**Comment by sarutak** [comment]
@dongjoon-hyun If we need a mechanism for optional metrics for `ExecutorPage`, we can do like the latest commit and we can get like a folowing UI.

Screenshot from 2019-08-10 05-37-25

**Comment by srowen** [comment]
@sarutak go ahead and update the title/description to reflect what this is adding now

**Comment by sarutak** [comment]
@srowen Thanks for reminding me. I've updated.

**Review by srowen — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Great! Thank you, @sarutak . I checked the fixed UI. 

Also, thank you, @srowen , @tgravescs , @hacker131 .

Merged to master.

**Comment by dongjoon-hyun** [comment]
Could you make a backporting PR, @sarutak ? There is a conflict on `branch-2.4`.

**Comment by sarutak** [comment]
@dongjoon-hyun O.K. I'll do it this week.

**Comment by dongjoon-hyun** [comment]
Thank you so much, @sarutak !

**Pull request closed without merging**
