### PR TITLE
Master

### PR DESCRIPTION
**Pull request by nbawzl2004**

### CODE REVIEW

**Comment by sryza** [comment]
Did you mean to submit this as a pull request?

**Comment by srowen** [comment]
Mind closing this PR?

**Comment by JoshRosen** [comment]
It looks like you submitted this by accident.  Do you mind closing this issue?  Thanks!

**Comment by nbawzl2004** [comment]
No, I don't mind. It is a mistake! I am so sorry about that.

2015-04-06 23:56 GMT-07:00 Josh Rosen <notifications@github.com>:

> It looks like you submitted this by accident. Do you mind closing this
> issue? Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apache/spark/pull/5258#issuecomment-90404405>.
>



-- 
Best,
Frank Wu

**Comment by vanzin** [comment]
@nbawzl2004 you need to explicitly close the PR, others can't do that for you...

**Pull request closed without merging**
