### PR TITLE
[SPARK-35905][SQL][TESTS] Fix UT to clean up table/view in SQLQuerySuite 

### PR DESCRIPTION
**Pull request by AngersZhuuuu**
### What changes were proposed in this pull request?
Fix UT mistake in SQLQuerySuite

### Why are the changes needed?
Fix UT mistake in SQLQuerySuite

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Existed UT

### CODE REVIEW

**Comment by AngersZhuuuu** [comment]
FYI @dongjoon-hyun

**Review by dongjoon-hyun — COMMENTED** [review]
Thank you for fixing this, @AngersZhuuuu .
Could you make a separate PR because this cannot have the same fix version of the original PR?
The original PR's fix version is `2.4.8, 3.0.2, 3.1.0`. Your PR can be 3.2.0/3.1.3/3.0.4, but not `2.4.0,3.0.2,3.1.0`.

**Comment by dongjoon-hyun** [comment]
One more thing: `Fix UT mistake in SQLQuerySuite` doesn't give any idea. Why don't you say that what you are doing here. For example, `Adding withTable ...`?

**Comment by AngersZhuuuu** [comment]
@dongjoon-hyun Should I add SPARK-35905 to UT title?

**Comment by dongjoon-hyun** [comment]
It's okay, but you should remove '[FOLLOWUP]'. BTW, is this the only case in that test suite file?

**Comment by AngersZhuuuu** [comment]
> It's okay to add that, but you should remove '[FOLLOWUP]'. BTW, is this the only case in that test suite file?

Check again,  should have fix all table/view in this UT

**Comment by AngersZhuuuu** [comment]
retest this please

**Comment by dongjoon-hyun** [comment]
Thank you for fixing all of them, @AngersZhuuuu . Merged to master.

**Pull request closed without merging**
