### PR TITLE
[SPARK-9513] [SQL] [PySpark] Add python API for DataFrame functions

### PR DESCRIPTION
**Pull request by davies**
This adds Python API for those DataFrame functions that is introduced in 1.5.

There is issue with serialize byte_array in Python 3, so some of functions (for BinaryType) does not have tests.

cc @rxin

### CODE REVIEW

**Comment by rxin** [comment]
LGTM - I didn't look that closely though. Are there any tricky parts that I should pay attention to?

**Comment by davies** [comment]
I just did a round, it should be ready now, waiting for tests.

**Comment by rxin** [comment]
Thanks - merging.

**Comment by shivaram** [comment]
I think I just found a minor bug in this --- the `crc` function in python calls `md5` instead of calling `crc` ?

**Comment by rxin** [comment]
I will fix that ... thanks for spotting it.

**Pull request closed without merging**
