### PR TITLE
[SPARK-19441] [SQL] Remove IN type coercion from PromoteStrings

### PR DESCRIPTION
**Pull request by gatorsmile**
### What changes were proposed in this pull request?
The removed codes for `IN` are not reachable, because the previous rule `InConversion` already resolves the type coercion issues. 

### How was this patch tested?
N/A

### CODE REVIEW

**Comment by gatorsmile** [comment]
retest this please

**Comment by gatorsmile** [comment]
retest this please

**Comment by gatorsmile** [comment]
retest this please

**Comment by gatorsmile** [comment]
retest this please

**Comment by gatorsmile** [comment]
retest this please

**Comment by dongjoon-hyun** [comment]
Retest this please

**Comment by dongjoon-hyun** [comment]
+1

**Comment by gatorsmile** [comment]
cc @cloud-fan

**Comment by gatorsmile** [comment]
retest this please

**Comment by cloud-fan** [comment]
LGTM, merging to master!

**Pull request closed without merging**
