### PR TITLE
[SPARK-37854][CORE] Replace type check with pattern matching in Spark code

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?

There are many method use `isInstanceOf  + asInstanceOf` for type conversion in Spark code now, the main change of this pr is replace `type check` with `pattern matching` for code simplification.

### Why are the changes needed?
Code simplification

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass GA

### CODE REVIEW

**Review by srowen — APPROVED** [review]
Fine, anything else like this we can improve?

**Comment by LuciferYang** [comment]
May be other similar ones, let me check it

**Review by andrewchoi5 — APPROVED** [review]

**Comment by srowen** [comment]
Are they all meaningful simplifications beyond just avoiding an if, and instanceOf? I'd fix more if you can yes

**Comment by LuciferYang** [comment]
> Are they all meaningful simplifications beyond just avoiding an if, and instanceOf? I'd fix more if you can yes

I have finished the other changes, but I haven't submitted it yet. All of them are use `case match` instead of type check, there seems to be no more code simplification.

**Review by dongjoon-hyun — APPROVED** [review]
Look like a nice approach. Are we waiting for @LuciferYang 's additional commit?

**Comment by LuciferYang** [comment]
I can push other fixes in this pr and update the pr description. what do you think @dongjoon-hyun @srowen

**Comment by srowen** [comment]
I would add other similar simplifications, yes

**Comment by LuciferYang** [comment]
> I would add other similar simplifications, yes

OK ~

**Comment by dongjoon-hyun** [comment]
+1 for @srowen 's comment.

**Comment by LuciferYang** [comment]
Already pushed other fix,  I will update pr description later and check CI status.  Set this pr to draft first.

**Comment by LuciferYang** [comment]
On the other hand, there is a case can't change:

https://github.com/apache/spark/blob/fcc51767aa4a594868eff33a7ddd8c5242006cd8/sql/catalyst/src/test/scala/org/apache/spark/sql/catalyst/expressions/ObjectExpressionsSuite.scala#L54-L65

if the `equals` method change to 


```
override def equals(other: Any): Boolean = {
      other match {
        case inner: Inner => value == inner.value
        case _ => false
      }
    }
```

the UT `SPARK-23584 NewInstance should support interpreted execution` in ObjectExpressionsSuite will failed

**Review by srowen — APPROVED** [review]
Looks like good cleanup. You can remove "WIP"

**Comment by srowen** [comment]
Merged to master

**Comment by LuciferYang** [comment]
thanks all

**Pull request closed without merging**
