### PR TITLE
[SPARK-14573][PYSPARK][BUILD] Fix PyDoc Makefile & highlighting issues

### PR DESCRIPTION
**Pull request by holdenk**
## What changes were proposed in this pull request?

The PyDoc Makefile used "=" rather than "?=" for setting env variables so it overwrote the user values. This ignored the environment variables we set for linting allowing warnings through. This PR also fixes the warnings that had been introduced.
## How was this patch tested?

manual local export & make

### CODE REVIEW

**Comment by holdenk** [comment]
cc @BryanCutler who ran into this issue

**Comment by BryanCutler** [comment]
`?=` seems to do the trick, LGTM

**Comment by srowen** [comment]
LGTM

**Comment by holdenk** [comment]
If this looks OK to people it would be good to merge before anymore PyDoc highlighting inconsistencies make it into master. Maybe @JoshRosen or @davies could merge could also take a quick look and merge this if its ok as they are the most recent committers on the Makefile?

**Comment by srowen** [comment]
Looks like a clean improvement; merged to master

**Pull request closed without merging**
