### PR TITLE
[SPARK-10973][ML][PYTHON] Fix IndexError exception on SparseVector when asked for index after the last non-zero entry

### PR DESCRIPTION
**Pull request by zero323**
See https://github.com/apache/spark/pull/9009 for details.

### CODE REVIEW

**Comment by jkbradley** [comment]
This patch includes updates to a lot of pom files.  Can you please remove those?

(Thanks for sending all of these backports, btw!)

**Comment by zero323** [comment]
@jkbradley Should be OK now.

**Comment by jkbradley** [comment]
I'll wait for the test to finish, but regardless, I'll merge this into branch-1.3.  I tested it locally, and it worked.

**Comment by jkbradley** [comment]
Merging with branch-1.3
Thanks for all of the patches!

**Pull request closed without merging**
