### PR TITLE
[SPARK-14602][yarn] Use SparkConf to propagate the list of cached files.

### PR DESCRIPTION
**Pull request by vanzin**
This change avoids using the environment to pass this information, since
with many jars it's easy to hit limits on certain OSes. Instead, it encodes
the information into the Spark configuration propagated to the AM.

The first problem that needed to be solved is a chicken & egg issue: the
config file is distributed using the cache, and it needs to contain information
about the files that are being distributed. To solve that, the code now treats
the config archive especially, and uses slightly different code to distribute
it, so that only its cache path needs to be saved to the config file.

The second problem is that the extra information would show up in the Web UI,
which made the environment tab even more noisy than it already is when lots
of jars are listed. This is solved by two changes: the list of cached files
is now read only once in the AM, and propagated down to the ExecutorRunnable
code (which actually sends the list to the NMs when starting containers). The
second change is to unset those config entries after the list is read, so that
the SparkContext never sees them.

Tested with both client and cluster mode by running "run-example SparkPi". This
uploads a whole lot of files when run from a build dir (instead of a distribution,
where the list is cleaned up), and I verified that the configs do not show
up in the UI.

### CODE REVIEW

**Comment by jerryshao** [comment]
LGTM.

**Comment by steveloughran** [comment]
I don't see anything that would cause problems with YARN. Good to see that `ApplicationMaster` does log what it's creating ... that'll be critical if/when executors stop launching

**Comment by tgravescs** [comment]
Jenkins test this please

**Comment by tgravescs** [comment]
changes look good.  Unit test failure looks unrelated but kicked again.

I wonder if we shouldn't have the webui just not print internal() configs rather then us manually removing things from the sparkConf.  Not sure if there is anything else expecting internal ones to be there though since its generic listener

**Comment by steveloughran** [comment]
Thomas: regarding credential printing, what about having some regexps of things not to print. In particular, credentials to talk to S3, Azure &c are things that may get into the spark conf, which you don't want to have broadly visible

**Comment by tgravescs** [comment]
@steveloughran not sure I follow, what configs are you referring to?   I haven't used S3/Azure with spark so not sure how those are specified.   The configs shouldn't be visible unless the user gives another user view access to the web ui.   This feels like a separate issue then internal configs vs user specified configs but I guess could use a similar mechanism.

**Comment by vanzin** [comment]
> I wonder if we shouldn't have the webui just not print internal() configs

That would be optimal, but there's work that needs to be done before that can happen. For starters, SparkConf needs to keep track of known configs (the way SQLConf does) so that it knows which ones are internal.

**Comment by vanzin** [comment]
unrelated test failure, but... retest this please.

**Comment by vanzin** [comment]
Anyway, all the interesting tests are passing, so I'll leave this here for a little bit in case there are more comments before pushing it.

**Comment by vanzin** [comment]
That same unrelated test is failing, so merging this to master.

**Pull request closed without merging**
