### PR TITLE
[SPARK-40833][K8S] Cleanup apt lists cache

### PR DESCRIPTION
**Pull request by Yikun**
### What changes were proposed in this pull request?
Remove unused apt lists cache

### Why are the changes needed?
Clean cache to reduce docker image size.

This is also [recommanded](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#run) by docker community:

```
$ docker run --user 0:0 -ti apache/spark bash
root@5d1ca347279e:/opt/spark/work-dir# ls /var/lib/apt/lists/
auxfiles								     lock
deb.debian.org_debian_dists_bullseye-updates_InRelease			     partial
deb.debian.org_debian_dists_bullseye-updates_main_binary-arm64_Packages.lz4  security.debian.org_debian-security_dists_bullseye-security_InRelease
deb.debian.org_debian_dists_bullseye_InRelease				     security.debian.org_debian-security_dists_bullseye-security_main_binary-arm64_Packages.lz4
deb.debian.org_debian_dists_bullseye_main_binary-arm64_Packages.lz4
root@5d1ca347279e:/opt/spark/work-dir# du --max-depth=1 -h /var/lib/apt/lists/
4.0K	/var/lib/apt/lists/partial
4.0K	/var/lib/apt/lists/auxfiles
17M	/var/lib/apt/lists/
```

### Does this PR introduce _any_ user-facing change?
Yes in some level, image size is reduced.

### How was this patch tested?
K8s CI passed

### CODE REVIEW

**Comment by Yikun** [comment]
cc @dongjoon-hyun

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @Yikun .
Merged to master for Apache Spark 3.4.0.

**Comment by dongjoon-hyun** [comment]
Ur, @Yikun . Why do you use a different style per repo?
- https://github.com/apache/spark-docker/pull/14/files
```
- rm -rf /var/cache/apt/*
+ rm -rf /var/cache/apt/* && \
+ rm -rf /var/lib/apt/lists/*
```

**Comment by Yikun** [comment]
@dongjoon-hyun After spark-docker PR merged, I found the Python docker file are using one line style, so keep the same style in spark repo.

I'd also like to sync this style to spark-docker. : ), from functions view it's same, put similar function cmd (rm in here) in one line is better.

**Comment by Yikun** [comment]
BTW, what do you think about the dockerfile being in sync between spark-docker and spark?

spark-docker contains some changes for non-k8s to meet the requirements of DOI. such as, remove print line in entrypoint, add users, expose port. Do we want to also sync them in spark repo?

**Comment by dongjoon-hyun** [comment]
We don't need to sync~ If we really want to sync, we had better make `spark-docker` git repo as a submodule of `spark` repo.

**Comment by Yikun** [comment]
@dongjoon-hyun OK, thanks, let's just keep different for now! If a submodule is really needed, we can do it in future.

**Comment by dongjoon-hyun** [comment]
Ya, feel free to propose any changes if it helps you and don't blocked by me. You are now a committer with more power, @Yikun . :)

**Pull request closed without merging**
