### PR TITLE
[SPARK-39829][BUILD] Upgrade `log4j2` to 2.18.0

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to upgrade log4j2 to 2.18.0.

### Why are the changes needed?

This will bring 53 patches.
- https://logging.apache.org/log4j/2.x/changes-report.html#a2.18.0
- https://issues.apache.org/jira/projects/LOG4J2/versions/12351152

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the CIs

### CODE REVIEW

**Comment by LuciferYang** [comment]
Seems we need to wait for https://github.com/apache/spark/pull/37243

**Comment by dongjoon-hyun** [comment]
Yes, this is not urgent. We can wait, @LuciferYang .

**Review by HyukjinKwon — APPROVED** [review]

**Review by LuciferYang — APPROVED** [review]
LGTM +1

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
