### PR TITLE
[SPARK-7768][CORE][SQL] Open UserDefinedType as a Developer API

### PR DESCRIPTION
**Pull request by srowen**
### What changes were proposed in this pull request?

UserDefinedType and UDTRegistration become public Developer APIs, not package-private to Spark.

### Why are the changes needed?

This proposes to simply open up the UserDefinedType class as a developer API. It was public in 1.x, but closed in 2.x for some possible redesign that does not seem to have happened.

Other libraries have managed to define UDTs anyway by inserting shims into the Spark namespace, and this evidently has worked OK. But package isolation in Java 9+ breaks this.

The logic here is mostly: this is de facto a stable API, so can at least be open to developers with the usual caveats about developer APIs.

Open questions:

- Is there in fact some important redesign that's needed before opening it? The comment to this effect is from 2016
- Is this all that needs to be opened up? Like PythonUserDefinedType?
- Should any of this be kept package-private?

This was first proposed in https://github.com/apache/spark/pull/16478 though it was a larger change, but, the other API issues it was fixing seem to have been addressed already (e.g. no need to return internal Spark types). It was never really reviewed.

My hunch is that there isn't much downside, and some upside, to just opening this as-is now.

### Does this PR introduce _any_ user-facing change?

UserDefinedType becomes visible to developers to subclass.

### How was this patch tested?

Existing tests; there is no change to the existing logic.

### CODE REVIEW

**Comment by srowen** [comment]
@viirya @cloud-fan you may be best placed to say whether there are any concerns about this that I don't know of, or what else needs to be opened.

**Review by viirya — COMMENTED** [review]
Hmm, I'm not sure about the reason of against opening this API. Maybe there was a plan to revamp UDT stuff? But as this was put into private package for not a short term. And I don't see any obvious change. I guess it's okay now?

**Comment by xkrogen** [comment]
Seems like #16478 is a good improvement that makes UDT both more performant and much easier to use. The only downside I see is that it is a breaking change to the UDT API -- which is okay to make now as it is private, but becomes less okay once we make it public with this PR. Is there any chance we can push out #16478 before this PR? I see @viirya has been trying for a few years now ...

**Comment by srowen** [comment]
Yeah I was primarily looking at #16478 but it seems like some of those API changes are already made? the API doesn't seem to refer to internal Spark classes anymore. And @viirya closed it just now :)

**Comment by viirya** [comment]
Hmm, I am not aware of some API changes was made. I closed it because seems to me these users want is to open UDT API. I'm not sure if these API changes are in need or not. And you know it was not reviewed for many years...

**Comment by viirya** [comment]
I just checked current UDT classes. Looks like it still uses internal Spark classes. Actually as mentioned in previous comment, I don't see any obvious improvement in UDT in recent years, if I don't miss anything.

**Comment by srowen** [comment]
Hm, where are those types in the two newly public classes? I don't see any.

**Comment by xkrogen** [comment]
I believe we're talking about these methods on `UserDefinedType`:
```
  def serialize(obj: UserType): Any
  def deserialize(datum: Any): UserType
```
They use `Any` so it doesn't _look_ like they require use of internal Spark APIs, but based on my understanding of @viirya's PR they are expecting types such as `InternalRow`

**Comment by srowen** [comment]
Ah, I get it. That's what I was looking for. `InternalRow` is not technically private, though informally so, being part of the `.catalyst` package. For those that have much more experience implementing a UDT with the hack: in practice must you assume it's an `InternalRow`?

If so then yeah I see the argument that this API needs to change first before being made public. We _can_ just open it up to continue to enable the hack, and that buys something. But it makes it harder to modify the API to something more proper later.

So what about #16478 @viirya ? is that still a sound proposal for refactoring the interface? That seems more ideal to add first.

**Comment by HyukjinKwon** [comment]
cc @mengxr and @WeichenXu123 too since ML already uses it internally.
cc @cloud-fan and @rxin too. I remember it was discussed somewhere that we need to have a better design. Also ANSI describes UDT but that's pretty different from Spark's UDT IIRC. cc @hvanhovell too FYI.

**Comment by viirya** [comment]
> So what about #16478 @viirya ? is that still a sound proposal for refactoring the interface? That seems more ideal to add first.

Hm, yea, the refactoring is trying to hide internal classes such as `UnsafeArrayData`, `GenericInternalRow`, etc. from UDT usage. So the developers use Scala classes when writing UDTs. Although as UDT is private for many years, I guess the developers just use Spark namespace to code their UDTs with internal classes for a while. Technically, yes, it seems more ideal to refactor and hide internal classes first.

**Comment by jnh5y** [comment]
Hi all, LocationTech GeoMesa is a consumer of the previously package private UDT/UDF APIs in order implement spatial data types (like Point, LineString, Polygon) and associated functions (intersects, intersection, union, convexhull, etc.).

I can appreciate the nature of the API developed here, and it has made good sense for it to private while forming.  With Java 8, as a downstream consumer of the (private) API, we can do things like this: https://github.com/locationtech/geomesa/tree/main/geomesa-spark/geomesa-spark-sql/src/main/scala/org/apache/spark/sql and it works. 

Folks like @metasim and myself have watched the previous UDT PRs to see if those improvements would make it.  With Java 11 and later caring about split packages, this issue is more important for these integrations.  If something isn't done to address it, projects which are using the private API to implement UDT/UDFs are sunk on Java 11:(.

This last time that the change came up, Simeon or Sean noted that just opening up these classes may allow us to move integration code out of the org.apache.spark packages.  In terms of changes, if the community cannot settle on the proposed improvements in a timely fashion, I'd say that this is a great compromise.

All that said, as a developer on a downstream project, I know that the integration UDTs/UDFs and the associated Catalyst optimizations will change routinely as Spark releases minor and major versions.  (We have used reflection to paper over changes that have come up in the optimizer rules over time.)

I think marking this as a DeveloperApi reflects the idea that things can change.  I'd be quite happy to see this PR and other UDT improvements land in either order.

**Comment by srowen** [comment]
It does sound like ideally the API would be refactored. @viirya I didn't see pushback on your redesign.

We can just open this up, which at least re-enables the current 'hacky' but working path for third-party UDFs. The only downside is it exposes an API which _should_ change. If that refactoring is controversial (is it even?), there's an argument to open it up and caveat it: it may well change again. I expect third parties are expecting that (see above), and, if we refactor now it will already break the current unsupported integrations in Java 8 too.

My motive is that geospatial use cases are relatively important, so want there to be at least any working path right now.

To that end I'd still support opening this (this PR), but, still not sure we can't merge @viirya 's change as well? even also for 3.2?

**Comment by srowen** [comment]
@jnh5y @viirya I got a good question from @marmbrus - can you support user-defined types by just defining an Encoder for it? so that it can work in a Dataset?

**Comment by jnh5y** [comment]
@srowen Good question!  To be honest, I think it'd probably take an hour or two of fiddling for me to answer correctly and with confidence.

That said, the goal of the geospatial use case is to enable spatial UDTs, associated UDFs, and Catalyst optimization rules.  I would guess that the encoder approach would only help with the first of those.  

So, yeah, do Encoders allow one to implement UDFs and/or Catalyst optimizations?  (This is the question which I think would take me some time to figure out.:)  If the answer is "no", then I think we could reason that the answer to @marmbrus's question is no as well.)

**Comment by metasim** [comment]
> @jnh5y @viirya I got a good question from @marmbrus - can you support user-defined types by just defining an Encoder for it? so that it can work in a Dataset?

@srowen I'll jump in here as I've contended with this quite a lot. If I understand the question, the answer is "no", at least not for `TileUDT`, and I doubt it for `AbstractGeometryUDT` (but the use cases are actually quite different).  RasterFrames has [a host of `Encoder`s](https://github.com/locationtech/rasterframes/tree/develop/core/src/main/scala/org/locationtech/rasterframes/encoders), and defaults to that modality whenever possible. But the computational dynamics of spatiotemporal raster data require further optimizations, provided for by using UDTs.

For `TileUDT`, there are a couple things going on:
 
1. Geospatial raster data is what I call "heavy data" (there's not just many rows, but those rows are very thick). Raster data is relatively expensive to read, consumes a lot of memory, and comes in many encodings and arbitrary projections. Often in an analysis a lot of reasoning can be done over the metadata of the raster, filtering out rows or providing opportunities for logical plan optimization before the raster data is even read into memory. We defer reading of the pixels/cells until absolutely necessary. Therefore, behind `TileUDT` we are implementing old-school OO information hiding and polymorphism to enable lazy evaluation of raster data, [implementing](https://github.com/locationtech/rasterframes/blob/0da9aa936fc4dc0e27a91ca5809bc0416b0c4174/core/src/main/scala/org/apache/spark/sql/rf/TileUDT.scala#L83-L89) essentially two specializations: logically, a "RasterRefTile" (lazy Tile) and a "RealizedTile" (eager Tile). Once the plan identifies the need for pixels/cells the "RasterRefTile" is converted to a "RealizedTile"
2. The structure of a TileUDT has and is evolving. We need information hiding to keep users from depending on the internal structure, and to provide us with backwards compatible migration paths that `Encoder`s alone are not able to provide.
3. Serialization to/from Parquet is UDT aware, so reading in a RasterFrames Parquet file maintains type coherence in a way `Encoder`s alone would not
4. Serialization to/from PySpark, while extremely expensive (because Spark's Arrow encoder doesn't support UDTs), does allow for nice user-facing ergonomics whereby we can have a first-class `Tile` Python class mirroring the JVM instance that, again, hides the nasty details of the raster structure while providing NumPy and Pandas interoperability. I don't think we'd be able to provide the same ergonomics if we relied on UDTs alone.

I'll note the PySpark use case is also very pertinent to [interoperability](https://github.com/locationtech/rasterframes/blob/develop/pyrasterframes/src/main/python/geomesa_pyspark/types.py) between GeoMesa's `AbstractGeometryUDT` and Python's Shapely library.

I hope all this helps, and doesn't just confuse things further. In short, we tried to avoid UDTs for quite a while in RasterFrames, but with one of our primary goals being usability by data scientists and analysts (not software engineers), we found UDTs as the perfect mechanism to hide the sausage making while allowing us to provide reliability and stability in the execution engine.

**Comment by viirya** [comment]
> @jnh5y @viirya I got a good question from @marmbrus - can you support user-defined types by just defining an Encoder for it? so that it can work in a Dataset?

This sounds a more tremendous change than the PR I proposed. I think `Encoder` is for converting JVM object to top-level row in Spark SQL. Currently `Encoder` is a pretty abstract trait without any defined APIs, excepts for returning its schema and class tag. Only one implementation of `Encoder` is `ExpressionEncoder`, and it looks more for internal usage as it is based on catalyst expressions.

If using `Encoder` for user-defined types is the plan, we probably need to add public API for users to define `Encoder`?

**Comment by maropu** [comment]
I feel the @viirya's refactoring looks reasonable to prevent 3rd-party developers from seeing internal structures if we will make it public. We still have any other concern? I read the discussions above and no one seems to be explicitly against it though.

Btw, is it okay to make classes in the `catalyst` package visible (as a developer api) to 3rd-party developers? IIUC they are internally private and most of the existing developer APIs are actually located in the `core` package:
```
$grep -nr "@DeveloperApi" ./catalyst/src/main/scala/org/apache/spark/sql/ | wc -l
       1
$grep -nr "@DeveloperApi" ./core/src/main/scala/org/apache/spark/sql | wc -l
      32
```
Any policy for that?

**Comment by srowen** [comment]
It's a good point - catalyst classes are not technically private, but by convention are not considered an API. People do hook into them anyway, at their own risk.

My argument for this simple change to just open it anyway is basically: it will just keep the status-quo in Java 9+. Improving the API is a good thing, but will actually break some usages of UDT. Which is fine: they're not an API. But, I suppose it also means that changing it _later_, even after opening it as a DeveloperApi is not really much more disruptive.

It's either that or indeed revive @viirya 's PR and get that merged. I also didn't hear objections, nor did I hear much review, which makes me uneasy as it's a fairly important internal component.

I'd like to reach _some_ resolution here to keep the status quo working on Java 11, which we now support, and this is an imperfect but easy temporary fix. Is that reasonable?

**Comment by viirya** [comment]
It sounds really making sense to me. So seems to have the status quo working in Java 9+ sounds good idea and no (or just little) harm. Because `UserDefinedType` is somehow well-known and used across Spark users, improving the API before opening it as a DeveloperApi or later, in this case is not too much different.

**Comment by srowen** [comment]
Waiting just one more round for any comments. I'd like to go with this change for now.

**Comment by maropu** [comment]
> Improving the API is a good thing, but will actually break some usages of UDT. Which is fine: they're not an API. But, I suppose it also means that changing it later, even after opening it as a DeveloperApi is not really much more disruptive.

Yea, it looks a reasonable direction to me, so I support it.

**Review by maropu — APPROVED** [review]

**Review by HyukjinKwon — COMMENTED** [review]
Sean, BTW, the genjavadoc failure seems because of:

```
[error] /home/runner/work/spark/spark/mllib/target/java/org/apache/spark/ml/linalg/MatrixUDT.java:3:1:  error: unexpected text
[error]  * User-defined type for {@link Matrix} in {@link mllib-local} which allows easy interaction with SQL
[error]                                            ^
[error] /home/runner/work/spark/spark/mllib/target/java/org/apache/spark/ml/linalg/VectorUDT.java:3:1:  error: unexpected text
[error]  * User-defined type for {@link Vector} in {@link mllib-local} which allows easy interaction with SQL
[error]                                            ^
```

I think opening `UserDefinedType` triggers the documentation validation in the sub-types too for some reasons. Maybe we should just fix it `[[mllib-local]]` to `` `mllib-local` ``

**Comment by srowen** [comment]
Thanks @HyukjinKwon , I fixed that. I do see the failure you mention, but I see lots of them. Are those 'normal', the rest of the errors? I recall we've long had this problem with some of the doc generation but generally ignored it.

**Comment by HyukjinKwon** [comment]
Yeah .. they are actually warnings but they are turned into errors iff there's one error. I tried hard to fix it but badly failed (SPARK-20840).

**Review by HyukjinKwon — APPROVED** [review]
I am good with this change.

**Review by viirya — APPROVED** [review]
lgtm

**Comment by viirya** [comment]
cc @cloud-fan

**Pull request closed without merging**
