### PR TITLE
[SPARK-2827][GraphX]Add degree distribution operators in GraphOps for GraphX

### PR DESCRIPTION
**Pull request by luluorta**

### CODE REVIEW

**Comment by maropu** [comment]
What't the status of this patch?
If possibly merged into the master, I'll refactor the codes and add unit tests.

**Comment by ankurdave** [comment]
@maropu I'd like to merge this. It would be great if you could fix it up, maybe in a new PR.

**Comment by maropu** [comment]
Ok, I'll take it.

**Comment by maropu** [comment]
The new PR done, and plz review it.

**Comment by srowen** [comment]
Close this PR if it's the old version please.

**Comment by andrewor14** [comment]
Hi @maropu would you mind closing this PR? It's confusing to have both open.

**Pull request closed without merging**
