### PR TITLE
[SPARK-32977][SQL][DOCS] Fix JavaDoc on Default Save Mode

### PR DESCRIPTION
**Pull request by RussellSpitzer**
### What changes were proposed in this pull request?

The default is always ErrorsOnExist regardless of DataSource version. Fixing the JavaDoc to reflect this.

### Why are the changes needed?

To fix documentation

### Does this PR introduce _any_ user-facing change?

Doc change.

### How was this patch tested?

Manual.

### CODE REVIEW

**Comment by RussellSpitzer** [comment]
@brkyvz  - Could you please review this re: our conversation a while back :)

**Comment by RussellSpitzer** [comment]
@rdblue  You may want to take a look as well if you have a moment

**Comment by rdblue** [comment]
+1

**Comment by RussellSpitzer** [comment]
Some random image reading thing failed in Pyspark tests, can't imagine that it's related ;)

**Comment by HyukjinKwon** [comment]
Yeah, that's a known flaky test.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
It would have been better if we keep [the PR template](https://github.com/apache/spark/blob/master/.github/PULL_REQUEST_TEMPLATE) though.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. I recovered the PR description and revised the PR title.
Thank you, @RussellSpitzer , @rdblue , @HyukjinKwon .
Merged to master/3.0

**Pull request closed without merging**
