### PR TITLE
[SPARK-19078][ML] hashingTF,ChiSqSelector,IDF,StandardScaler,PCA transform avoid extra vector conversion

### PR DESCRIPTION
**Pull request by zhengruifeng**
## What changes were proposed in this pull request?

This pr modify transform to direct use ml.linalg in hashingTF,ChiSqSelector,IDF,StandardScaler,PCA.

## How was this patch tested?
existing tests

### CODE REVIEW

**Comment by zhengruifeng** [comment]
cc @yanboliang

**Comment by imatiach-msft** [comment]
I think you might need to add [ML] to the pull request name, eg:
[SPARK-19078][ML] hashingTF,ChiSqSelector,IDF,StandardScaler,PCA transform avoid extra vector conversion

I like the changes but I'm not sure if we want to directly port the code instead of using the ml lib code, since now if there are bugs in ml or mllib a developer would have to make changes in two places instead of one.  I'm a new contributor myself so I'm not sure what is traditionally recommended in cases like this.  It looks like in some cases it should be possible to refactor duplicate code to one place and have both ml and mllib call into the same method?  Maybe that would address my concern.  Thoughts?

**Comment by zhengruifeng** [comment]
@imatiach-msft Thanks for your suggestion and reviewing. I start this PR because I found that in source same `// TODO: Make the transformer natively in ml framework to avoid extra conversion.` appears in several places.

**Comment by sethah** [comment]
Is this a duplicate of [SPARK-18385](https://issues.apache.org/jira/browse/SPARK-18385). Can you please see the discussion on the PR: https://github.com/apache/spark/pull/15831/files

**Comment by zhengruifeng** [comment]
@sethah Yes. I will close the duplicated PR and JIRA, and help to reivewing that PR.

**Pull request closed without merging**
