### PR TITLE
Revert "[SPARK-24152][R][TESTS] Disable check-cran from run-tests.sh"

### PR DESCRIPTION
**Pull request by viirya**
### What changes were proposed in this pull request?

This reverts commit 91d990162f13acde546d01e1163ed3e898cbf9a7.

### Why are the changes needed?

CRAN check is pretty important for R package, we should enable it.

### Does this PR introduce any user-facing change?

No

### How was this patch tested?

Unit tests.

### CODE REVIEW

**Comment by viirya** [comment]
cc @dongjoon-hyun @HyukjinKwon

**Comment by viirya** [comment]
Let's check if CRAN check is back.

**Comment by viirya** [comment]
The CRAN issue looks resolved now.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.
Thank you, @viirya . Merged to master/2.4.

**Review by HyukjinKwon — COMMENTED** [review]
LGTM too. Thanks all.

**Pull request closed without merging**
