### PR TITLE
[SPARK-25504][Docs] Update doc about retained tasks, jobs and executions

### PR DESCRIPTION
**Pull request by shahidki31**
## What changes were proposed in this pull request?

Updated the documentation about spark.ui.retainedTasks, spark.ui.retainedJobs, spark.ui.retainedStages

## How was this patch tested?
NA

### CODE REVIEW

**Comment by shahidki31** [comment]
Hi @srowen , Some of the users seems getting confused with the threshold values, is it worth to update the docs? Thanks

**Review by srowen — COMMENTED** [review]
I am not sure it clarifies. Soft threshold implies it can retain more than the max. I also don't think we want to say it's definitely at least 90%. What is an example of this creating confusion?

**Comment by shahidki31** [comment]
In the JIRA, when the user want retainedTasks as 60000, actually retained around 58000. 
As per the code, it retained atleast 0.9*retainedTasks to retainedTasks. if we can clearly specify about the threshold, the confusion doesn't arises.
If it is okay with the documentation, I can close the PR.

**Comment by srowen** [comment]
I think the existing docs are fine.

**Pull request closed without merging**
