### PR TITLE
[Minor] document edge case of updateFunc usage

### PR DESCRIPTION
**Pull request by emilyselwood**
## What changes were proposed in this pull request?

Include documentation of the fact that the updateFunc is sometimes called with no new values. This is documented in the main documentation here: https://spark.apache.org/docs/latest/streaming-programming-guide.html#updatestatebykey-operation however from the docs included with the code it is not clear that this is the case.

## How was this patch tested?

PR only changes comments. Confirmed code still builds.

### CODE REVIEW

**Review by srowen — APPROVED** [review]
I believe that's correct.

**Review by HyukjinKwon — COMMENTED** [review]
Sounds it changes the permission from ...

```bash
-rw-r--r--  ... PairDStreamFunctions.scala
```

to an executable ...

```bash
-rwxr-xr-x   ... PairDStreamFunctions.scala*
```

**Comment by wselwood** [comment]
Good catch @HyukjinKwon Sorry about that.

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
