### PR TITLE
[SPARK-37889][SQL] Replace Log4j2 MarkerFilter with RegexFilter

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

Log4j2 MarkerFilter can not suppress

```
10:55:54.597 ERROR org.apache.thrift.server.TThreadPoolServer: Thrift error occurred during processing of message.
org.apache.thrift.transport.TTransportException: null
	at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:132) ~[libthrift-0.12.0.jar:0.12.0]
```

We shall use RegexFilter instead

### Why are the changes needed?

bugfix

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

run `build/sbt -Phive -Phive-thriftserver "hive-thriftserver/testOnly *ThriftServerWithSparkContextInBinarySuite"` locally and checked

### CODE REVIEW

**Comment by yaooqinn** [comment]
cc @viirya @HyukjinKwon

**Review by HyukjinKwon — APPROVED** [review]

**Review by viirya — APPROVED** [review]

**Comment by viirya** [comment]
@yaooqinn Can you re-trigger the GA? Looks it was passed, but it still shows some checks haven't completed yet...

**Comment by HyukjinKwon** [comment]
oops, sorry I think that's a bug from my Pr (https://github.com/apache/spark/pull/35179#issuecomment-1011881076). @Yikun is fixing it 🙏 .

I think we can just merge - the test seems it passed.

**Comment by yaooqinn** [comment]
https://github.com/yaooqinn/spark/runs/4798434360 manually checked the test result which shows OK

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by viirya** [comment]
Okay, looks good.

**Pull request closed without merging**
