### PR TITLE
[SPARK-36244][BUILD] Upgrade zstd-jni to 1.5.0-3 to avoid a bug about buffer size calculation

### PR DESCRIPTION
**Pull request by sarutak**
### What changes were proposed in this pull request?

This PR upgrades `zstd-jni` from `1.5.0-2` to `1.5.0-3`.
`1.5.0-3` was released few days ago.
This release resolves an issue about buffer size calculation, which can affect usage in Spark.
https://github.com/luben/zstd-jni/releases/tag/v1.5.0-3

### Why are the changes needed?

It might be a corner case that skipping length is greater than `2^31 - 1` but it's possible to affect Spark.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

CI.

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. (Pending Jenkins)

**Comment by sarutak** [comment]
retest this please.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
BTW, Jenkins doesn't run dependency test. Let's make sure testing it locally and verifiy it passes ..

**Comment by dongjoon-hyun** [comment]
Dependency test is covered here.
- https://github.com/sarutak/spark/runs/3124666363?check_suite_focus=true

Merged to master/3.2

**Pull request closed without merging**
