### PR TITLE
[SPARK-40020][SQL][FOLLOWUP] Some more code cleanup

### PR DESCRIPTION
**Pull request by cloud-fan**
### What changes were proposed in this pull request?

This is a followup of https://github.com/apache/spark/pull/37415 , to add a bit more cleanups:
1. Revert the changes in `command/tables.scala` and `command/views.scala`. They are not necessary and I forgot to remove them before merging.
2. Remove `SessionCatalogAndTable` which is not used anywhere.
3. Further simplify `ResoveSessionCatalog` for CREATE commands against the v1 catalog.
4. Attach v1 catalog name in `RefreshFunctionCommand`
5. A few more small cleanups that were missed in #37415 

### Why are the changes needed?

code cleanup

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

existing tests

### CODE REVIEW

**Review by srowen — APPROVED** [review]

**Comment by LuciferYang** [comment]
```
org.apache.spark.sql.connector.DataSourceV2FunctionSuite
org.apache.spark.sql.connector.DataSourceV2SQLSuite
```
It seems that the test failure is related to this pr

**Comment by cloud-fan** [comment]
cc @ulysses-you @viirya

**Comment by viirya** [comment]
Seems unrelated?

```
[error] /home/runner/work/spark/spark/sql/hive-thriftserver/src/main/java/org/apache/hive/service/auth/HttpAuthUtils.java:36:1:  error: package org.apache.http.protocol does not exist
[error] import org.apache.http.protocol.BasicHttpContext;
[error]                                ^
[error] /home/runner/work/spark/spark/sql/hive-thriftserver/src/main/java/org/apache/hive/service/auth/HttpAuthUtils.java:156:1:  error: cannot find symbol
[error]     private final HttpContext httpContext;
[error]                   ^  symbol:   class HttpContext
[error]   location: class HttpKerberosClientAction
[error] 3 errors
```

**Review by viirya — APPROVED** [review]

**Review by ulysses-you — APPROVED** [review]

**Comment by cloud-fan** [comment]
thanks for review, merging to master!

**Pull request closed without merging**
