### PR TITLE
[SPARK-7109] [SQL] Push down left side filter for left semi join

### PR DESCRIPTION
**Pull request by scwf**
Now in spark sql optimizer we only push down right side filter for left semi join, actually we can push down left side filter because left semi join is doing filter on left table essentially.

### CODE REVIEW

**Comment by scwf** [comment]
i will try to add a test case for this

**Comment by scwf** [comment]
added test

**Comment by scwf** [comment]
Jenkins, retest this please

**Comment by scwf** [comment]
Jenkins, retest this please

**Comment by scwf** [comment]
Jenkins, retest this please

**Comment by scwf** [comment]
Jenkins, retest this please

**Comment by scwf** [comment]
It's very strange that compile with hive12 passed but failed for hive13, and my locally building on hive13 is ok

**Comment by scwf** [comment]
oh, my bad, i need rebase my branch since master rename apply -> execute

**Comment by chenghao-intel** [comment]
LGTM

**Comment by scwf** [comment]
@rxin @marmbrus any comment here?

**Comment by marmbrus** [comment]
Thanks, merged to master.

**Pull request closed without merging**
