### PR TITLE
[SPARK-20298][SparkR][MINOR] fixed spelling mistake "charactor"

### PR DESCRIPTION
**Pull request by bdwyer2**
## What changes were proposed in this pull request?

Fixed spelling of "charactor"

## How was this patch tested?

Spelling change only

### CODE REVIEW

**Comment by wangmiao1981** [comment]
LGTM

**Comment by wangmiao1981** [comment]
Jenkins, test this please.

**Comment by gatorsmile** [comment]
ok to test

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
