### PR TITLE
[SPARK-10822] Move contents of spark-unsafe subproject into spark-core

### PR DESCRIPTION
**Pull request by JoshRosen**
As a pre-requisite to other memory-management changes, I think that we should move the contents of the spark-unsafe subproject into spark-core and should remove that subproject.

### CODE REVIEW

**Comment by rxin** [comment]
LGTM

**Comment by JoshRosen** [comment]
Jenkins, retest this please.

**Comment by srowen** [comment]
As long as use of unsafe can still be turned off and is still pretty 'private' inside core, seems like it doesn't change much.

**Comment by andrewor14** [comment]
retest this please

**Comment by JoshRosen** [comment]
For some context, the reason that I want to move these classes is because it would be nice to integrate the TaskMemoryManager and ExecutorMemoryManager with other parts of Spark Core (as part of the unified memory management story). If we were to simply move the TaskMemoryManager class to Spark Core, then we couldn't use it in the classes in the Unsafe package (which doesn't depend on core).

Now that I think about this more, though, I think that there might be a different restructuring which would let us move those classes without having as broad an impact on the package. Therefore, let's hold off on merging this for now while I investigate to see whether there's an alternative that won't introduce this dependency problem.

**Pull request closed without merging**
