### PR TITLE
[MINOR][UI] Increasing the number of significant digits for Fraction Cached of RDD

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

This PR is a typo improvement for increasing the number of significant digits for Fraction Cached of RDD that shows on the Storage Tab.

### Why are the changes needed?

improves accuracy and precision

image

### Does this PR introduce _any_ user-facing change?

Yes, the Fraction Cached on Storage Page increases the fractional length from 0 to 2

### How was this patch tested?

locally verified

### CODE REVIEW

**Comment by yaooqinn** [comment]
cc @sarutak @HyukjinKwon thanks

**Review by sarutak — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master and branch-3.5.

**Comment by dongjoon-hyun** [comment]
Thank you. Is this Apache Spark 3.5-only bug fix?

**Comment by HyukjinKwon** [comment]
Oh I just cherry-picked this because it seems fairly minor but I don't mind reverting this out of branch-3.5

**Pull request closed without merging**
