### PR TITLE
Problem select empty ORC table

### PR DESCRIPTION
**Pull request by pprado**
## Error when I selected empty ORC table

> [pprado@hadoop-m ~]$ beeline -u jdbc:hive2://
> WARNING: Use "yarn jar" to launch YARN applications.
> Connecting to jdbc:hive2://
> Connected to: Apache Hive (version 1.2.1000.2.4.2.0-258)
> Driver: Hive JDBC (version 1.2.1000.2.4.2.0-258)
> Transaction isolation: TRANSACTION_REPEATABLE_READ
> Beeline version 1.2.1000.2.4.2.0-258 by Apache Hive

On beeline => `create table my_test (id int, name String) stored as orc;`
On beeline => `select * from my_test;`

> 16/05/13 18:18:57 [main]: ERROR hdfs.KeyProviderCache: Could not find uri with key [dfs.encryption.key.provider.uri] to create a keyProvider !!
> OK
> +-------------+---------------+--+
> | my_test.id  | my_test.name  |
> +-------------+---------------+--+
> +-------------+---------------+--+
> No rows selected (1.227 seconds)

Hive is OK!

Now, when i execute pyspark.

> Welcome to
>     SPARK   version 1.6.1
> 
> Using Python version 2.6.6 (r266:84292, Jul 23 2015 15:22:56)
> SparkContext available as sc, HiveContext available as sqlContext.

PySpark => `sqlContext.sql("select * from my_test")`

> 16/05/13 18:33:41 INFO ParseDriver: Parsing command: select \* from my_test
> 16/05/13 18:33:41 INFO ParseDriver: Parse Completed
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/hdp/2.4.2.0-258/spark/python/pyspark/sql/context.py", line 580, in sql
>     return DataFrame(self._ssql_ctx.sql(sqlQuery), self)
>   File "/usr/hdp/2.4.2.0-258/spark/python/lib/py4j-0.9-src.zip/py4j/java_gateway.py", line 813, in __call__
>   File "/usr/hdp/2.4.2.0-258/spark/python/pyspark/sql/utils.py", line 53, in deco
>     raise IllegalArgumentException(s.split(': ', 1)[1], stackTrace)
> pyspark.sql.utils.IllegalArgumentException: u'orcFileOperator: path hdfs://hadoop-m.c.sva-0001.internal:8020/apps/hive/warehouse/my_test does not have valid orc files matching the pattern'

when i create parquet table, it's all right. I do not have problem.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
I think it would be good if you follow  https://cwiki.apache.org/confluence/display/SPARK/Spark+Code+Style+Guide.

**Comment by pprado** [comment]
Why?
Em 13 de mai de 2016 9:08 PM, "Hyukjin Kwon" <notifications@github.com>
escreveu:

**Comment by HyukjinKwon** [comment]
Because I guess this is a contribution to Spark and there is a guide for this. It seems there are a lot of things wrong with this PR (e.g. no JIRA).

**Comment by pprado** [comment]
Sorry, I tried to follow this document:

https://cwiki.apache.org/confluence/display/SPARK/Contributing+to+Spark#ContributingtoSpark-ContributingBugReports

Jira is not the best tool for bug reporting.

Again, sorry if you do not follow good documentation practices expected for
you, but I think more important to report a very serious BUG, which did not
exist in version 1.6.0.

Thanks,
Pedro Prado

2016-05-13 21:30 GMT-03:00 Hyukjin Kwon <notifications@github.com>:

**Comment by HyukjinKwon** [comment]
In https://cwiki.apache.org/confluence/display/SPARK/Contributing+to+Spark#ContributingtoSpark-ContributingBugReports , It seems not suggesting to create a PR first but ask it to mailing list first.

Also, It seems not a very serious bug according to the guide. It seems priority of JIRA can be `minor` or `major`.

And, I think it is more important to follow the guide. Otherwise, it would be chaotic to deal with issues and PRs because it seems Spark is a really active and popular project.

**Comment by HyukjinKwon** [comment]
For me, I would like to say this might better be closed if this PR does not propose code changes. I think It would be nicer if the bug report is in the JIRA.

**Comment by andrewor14** [comment]
Let's close this PR. This patch isn't opened against the correct branch anyway.

**Pull request closed without merging**
