### PR TITLE
[SPARK-4985] [SQL] parquet support for date type

### PR DESCRIPTION
**Pull request by adrian-wang**
This PR might have some issues with #3732 ,
and this would have merge conflicts with #3820 so the review can be delayed till that 2 were merged.

### CODE REVIEW

**Comment by adrian-wang** [comment]
[HIVE-8119](https://issues.apache.org/jira/browse/HIVE-8119) have been merged into hive trunk. I'll test my patch based on that.

**Comment by adrian-wang** [comment]
I have tested my code with hive trunk, it is compatible.

/cc @marmbrus @rxin @liancheng @yhuai

**Comment by marmbrus** [comment]
This looks pretty good to me.  Can you add a test that actually exercises the read/write path?

**Comment by marmbrus** [comment]
Sorry, looks like this has conflicts again. :(  I would love to include it in 1.3.1 if you have time to update soon! :)

**Comment by adrian-wang** [comment]
rebased

**Comment by adrian-wang** [comment]
@marmbrus

**Comment by liancheng** [comment]
Thanks! Merged into master and branch-1.3.

**Pull request closed without merging**
