### PR TITLE
[SPARK-43956][SQL] Fix the bug doesn't display column's sql for Percentile[Cont|Disc]

### PR DESCRIPTION
**Pull request by beliefer**
### What changes were proposed in this pull request?
Last year, I committed `Percentile[Cont|Disc]` functions for Spark SQL.
Recently, I found the sql method of `Percentile[Cont|Disc]` doesn't display column's sql suitably.
This PR will fix the bug.

### Why are the changes needed?
Fix the bug doesn't display column's sql for `Percentile[Cont|Disc]`.

### Does this PR introduce _any_ user-facing change?
'Yes'.
Users could see the correct sql information.

### How was this patch tested?
Test cases updated.

### CODE REVIEW

**Review by wangyum — APPROVED** [review]

**Review by MaxGekk — APPROVED** [review]

**Comment by MaxGekk** [comment]
> Last year, I committed Percentile[Cont|Disc] functions for Spark SQL.

@beliefer This is too much ago for the follow up. Could you open a separate JIRA for this, and point out the versions 3.3 as the affected version.

**Comment by beliefer** [comment]
> @beliefer This is too much ago for the follow up. Could you open a separate JIRA for this, and point out the versions 3.3 as the affected version.

OK

**Comment by wangyum** [comment]
Merged to master.

**Comment by beliefer** [comment]
@wangyum @MaxGekk Thank you!

**Comment by beliefer** [comment]
@wangyum Do we need merge this to 3.3 and 3.4?

**Comment by wangyum** [comment]
I'm +1 for backporting this to 3.4 and 3.3 if you want.

**Pull request closed without merging**
