### PR TITLE
[SPARK-2103][Streaming] Change to ClassTag for KafkaInputDStream and fix reflection issue

### PR DESCRIPTION
**Pull request by jerryshao**
This PR updates previous Manifest for KafkaInputDStream's Decoder to ClassTag, also fix the problem addressed in [SPARK-2103](https://issues.apache.org/jira/browse/SPARK-2103).

Previous Java interface cannot actually get the type of Decoder, so when using this Manifest to reconstruct the decode object will meet reflection exception.

Also for other two Java interfaces, ClassTag[String] is useless because calling Scala API will get the right implicit ClassTag.

Current Kafka unit test cannot actually verify the interface. I've tested these interfaces in my local and distribute settings.

### CODE REVIEW

**Comment by salex89** [comment]
I'm not sure if this is the exactly same issue, but I am experience this with Spark 1.2.1 and Scala 2.10.4 also.

**Comment by jerryshao** [comment]
Hi @salex89 , seems your exception is a little different to this PR, maybe I need a careful look at this exception, thanks for your reporting.

**Comment by salex89** [comment]
OK, sorry for necroposting then. Should I open an issue on JIRA with the snippet?

**Comment by jerryshao** [comment]
Yeah, please do it and describe it in detail so we can easily reproduce it.

**Pull request closed without merging**
