### PR TITLE
[SPARK-48576][SQL] Rename UTF8_BINARY_LCASE to UTF8_LCASE

### PR DESCRIPTION
**Pull request by uros-db**
### What changes were proposed in this pull request?
Renaming `UTF8_BINARY_LCASE` collation to `UTF8_LCASE`.

### Why are the changes needed?
As part of the collation effort in Spark, we've moved away from byte-by-byte logic towards character-by-character logic, so what we used to call `UTF8_BINARY_LCASE` is now more precisely `UTF8_LCASE`. For example, string searching in UTF8_LCASE now works on character-level (rather than on byte-level), which is reflected in this PRs: https://github.com/apache/spark/pull/46511, https://github.com/apache/spark/pull/46589, https://github.com/apache/spark/pull/46682, https://github.com/apache/spark/pull/46761, https://github.com/apache/spark/pull/46762. In addition, string comparison also works on character-level now, as per the changes introduced in this PR: https://github.com/apache/spark/pull/46700.

### Does this PR introduce _any_ user-facing change?
Yes, what was previously named `UTF8_BINARY_LCASE` collation, will from now on be named `UTF8_LCASE`.

### How was this patch tested?
Existing tests.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by superdiaodiao** [comment]
Hi~
May I ask why we need to rename it?

**Comment by uros-db** [comment]
of course, I'll update the PR description with more details soon

but shortly: as part of the collation effort in Spark, we've moved away from byte-by-byte logic towards code point per code point logic, so what we used to call UTF8_BINARY_LCASE is now UTF8_LCASE, as this describes more precisely what is going on

here's a couple PRs regarding these changes:
https://github.com/apache/spark/pull/46700
https://github.com/apache/spark/pull/46761
https://github.com/apache/spark/pull/46762
https://github.com/apache/spark/pull/46682
https://github.com/apache/spark/pull/46589
https://github.com/apache/spark/pull/46682

**Comment by superdiaodiao** [comment]
> of...

got it, thanks

**Comment by uros-db** [comment]
all checks good, but several conflicts popping up

adding @mkaravel @dbatomic @cloud-fan for review

**Review by mkaravel — APPROVED** [review]
LGTM, but one of the tests is failing.

**Comment by uros-db** [comment]
adding @dbatomic and @cloud-fan to review

**Review by cloud-fan — APPROVED** [review]

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Pull request closed without merging**
