### PR TITLE
[SPARK-40737][CONNECT][FOLLOW-UP] Regenerate protos for `DataFrameWriter`

### PR DESCRIPTION
**Pull request by zhengruifeng**
### What changes were proposed in this pull request?
Regenerate protos for `DataFrameWriter`

### Why are the changes needed?
to make sure protos are latest

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
existing UT

### CODE REVIEW

**Comment by zhengruifeng** [comment]
@amaliujia @HyukjinKwon

**Review by HyukjinKwon — APPROVED** [review]

**Comment by amaliujia** [comment]
LGTM

**Comment by zhengruifeng** [comment]
Merged into master

**Comment by grundprinzip** [comment]
@zhengruifeng Thank you! I missed this when I split my PR into Scala and Python.

**Pull request closed without merging**
