### PR TITLE
[SPARK-32676][3.0][ML] Fix double caching in KMeans/BiKMeans

### PR DESCRIPTION
**Pull request by huaxingao**
### What changes were proposed in this pull request?
backporting https://github.com/apache/spark/pull/29501

### Why are the changes needed?
avoid double caching

### Does this PR introduce _any_ user-facing change?
no

### How was this patch tested?
Existing tests

### CODE REVIEW

**Comment by huaxingao** [comment]
Merged to 3.0.

**Comment by dongjoon-hyun** [comment]
Hi, @huaxingao . When you merge to old branch, please update the JIRA consistently.

SPARK-32676 still has an outdated fix version (3.1.0).

**Comment by huaxingao** [comment]
Updated. Thanks for reminding me @dongjoon-hyun

**Comment by dongjoon-hyun** [comment]
Thank YoU! :)

**Pull request closed without merging**
