### PR TITLE
[SPARK-41154][SQL] Incorrect relation caching for queries with time travel spec

### PR DESCRIPTION
**Pull request by ulysses-you**
### What changes were proposed in this pull request?

Add TimeTravelSpec to the key of relation cache in AnalysisContext.

### Why are the changes needed?

Correct the relation resolution for the same table but different TimeTravelSpec.

### Does this PR introduce _any_ user-facing change?

yes, bug fix

### How was this patch tested?

add test

### CODE REVIEW

**Comment by ulysses-you** [comment]
cc @cloud-fan @huaxingao

**Review by singhpk234 — APPROVED** [review]
Nice catch !

**Comment by cloud-fan** [comment]
there is another cache in `SessionCatalog.tableRelationCache`, shall we update it as well?

**Comment by ulysses-you** [comment]
`SessionCatalog` is used for v1 catalog (i.e. hive), I do not think that supports time travel

**Comment by huaxingao** [comment]
LGTM. Thanks for fixing this! @ulysses-you

**Review by huaxingao — APPROVED** [review]

**Comment by cloud-fan** [comment]
thanks, merging to master/3.3!

**Comment by cloud-fan** [comment]
Oh wait a minute. Due to the spark catalog extension (set via `spark.sql.catalog.spark_catalog`), we can have tables supporting time travel in the v1 catalog as well. I think `SessionCatalog.tableRelationCache` also need a fix

**Comment by cloud-fan** [comment]
thanks, merging to master/3.3!

**Comment by cloud-fan** [comment]
it has conflicts with 3.3, @ulysses-you can you create a backport PR? thanks!

**Comment by ulysses-you** [comment]
thank you all, created https://github.com/apache/spark/pull/38741 for branch-3.3

**Pull request closed without merging**
