### PR TITLE
[SPARK-32704][SQL][FOLLOWUP] Corrects version values of plan logging configs in SQLConf

### PR DESCRIPTION
**Pull request by maropu**
### What changes were proposed in this pull request?

This PR intends to correct version values (`3.0.0` -> `3.1.0`) of three configs below in `SQLConf`:
 - spark.sql.planChangeLog.level
 - spark.sql.planChangeLog.rules
 - spark.sql.planChangeLog.batches

This PR comes from https://github.com/apache/spark/pull/29544#discussion_r503049350.

### Why are the changes needed?

Bugfix.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

N/A

### CODE REVIEW

**Comment by maropu** [comment]
cc: @HyukjinKwon @gatorsmile

**Review by HyukjinKwon — APPROVED** [review]

**Comment by maropu** [comment]
Thanks for the check, @HyukjinKwon !

**Comment by maropu** [comment]
GA passed, so I'll merge this. Thanks!

**Comment by maropu** [comment]
Merged to master.

**Pull request closed without merging**
