### PR TITLE
[SPARK-7830] [Docs] [MLlib] Adding logistic regression to the list of Multiclass Classification Supported Methods documentation

### PR DESCRIPTION
**Pull request by dusenberrymw**
Added logistic regression to the list of Multiclass Classification Supported Methods in the MLlib Classification and Regression documentation, as it was missing.

### CODE REVIEW

**Comment by srowen** [comment]
Does LR do multiclass in MLlib?

**Comment by dusenberrymw** [comment]
Yeah it does, it was added here [https://github.com/apache/spark/commit/b1aa8fe988301b924048039529234278aeb0298a], and the main documentation for LR already has info on it [https://github.com/apache/spark/commit/b1aa8fe988301b924048039529234278aeb0298a].  It's just missing from the table on the Classification and Regression documentation page.

**Comment by dusenberrymw** [comment]
Also, I just noticed that the "Binary Classification" link on the same Classification and Regression page was also broken due to this issue, so I updated it to point to the "Classification" section of Linear Methods.

**Comment by jkbradley** [comment]
LGTM pending tests.  Thanks!

**Comment by jkbradley** [comment]
Merging into master and branch-1.4

**Pull request closed without merging**
