### PR TITLE
[SPARK-40850][SQL] Fix test case interpreted queries may execute Codegen

### PR DESCRIPTION
**Pull request by Hisoka-X**
### What changes were proposed in this pull request?

Fix `CodegenInterpretedPlanTest` always will execute Codegen even set `spark.sql.codegen.factoryMode` to `NO_CODEGEN`. We should set `spark.sql.codegen.wholeStage` to `false` too.

### Why are the changes needed?
Fix test case

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Add breakpoint on `WholeStageCodegenExec::doConsume`. Even set `spark.sql.codegen.factoryMode` to `NO_CODEGEN`, the `WholeStageCodegenExec::doConsume` also will be executed. When set `spark.sql.codegen.wholeStage` to `false`, the logic will skip.

### CODE REVIEW

**Comment by Hisoka-X** [comment]
cc @HyukjinKwon @MaxGekk

**Comment by Hisoka-X** [comment]
cc @holdenk

**Review by MaxGekk — APPROVED** [review]

**Comment by MaxGekk** [comment]
@Hisoka-X How about other places, like:
https://github.com/apache/spark/blob/f26bdb7bfde56e4856a2f962162f204ba2dbb1c1/sql/core/src/test/scala/org/apache/spark/sql/errors/QueryExecutionErrorsSuite.scala#L81

Could you re-check them too, please ... or open an JIRA if you don't have time.

**Comment by MaxGekk** [comment]
+1, LGTM. Merging to master.
Thank you, @Hisoka-X.

**Comment by Hisoka-X** [comment]
Thanks @MaxGekk

**Pull request closed without merging**
