### PR TITLE
[SPARK-21845] [SQL] [test-maven]  Make codegen fallback of expressions configurable

### PR DESCRIPTION
**Pull request by gatorsmile**
## What changes were proposed in this pull request?
We should make codegen fallback of expressions configurable. So far, it is always on. We might hide it when our codegen have compilation bugs. Thus, we should also disable the codegen fallback when running test cases.

## How was this patch tested?
Added test cases

### CODE REVIEW

**Comment by maropu** [comment]
Jenkins, retest this please.

**Comment by dongjoon-hyun** [comment]
Hi, @gatorsmile . 
Could you trigger Maven build, too?

**Comment by gatorsmile** [comment]
Sure

**Comment by gatorsmile** [comment]
retest this please

**Review by dongjoon-hyun — APPROVED** [review]
Thank you for Maven run! +1, LGTM.

**Comment by gatorsmile** [comment]
Thanks! Merging to master.

**Pull request closed without merging**
