### PR TITLE
[SPARK-22843][R] Adds localCheckpoint in R

### PR DESCRIPTION
**Pull request by HyukjinKwon**
## What changes were proposed in this pull request?

This PR proposes to add `localCheckpoint(..)` in R API.

```r
df <- localCheckpoint(createDataFrame(iris))
```

## How was this patch tested?

Unit tests added in `R/pkg/tests/fulltests/test_sparkSQL.R`

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @felixcheung, could you check if I understood your intention correctly?

**Comment by felixcheung** [comment]
Yes LGTM
Btw is there a better way to test localCheckpoint that it is not writing to checkpointDir?

**Comment by HyukjinKwon** [comment]
I tried to check if there is a easier way but not sure. Scala side seems checking the plan as well but I think I can't simply do it in R side and don't think it's worth ..

**Comment by felixcheung** [comment]
Fair enough. Calling it, is good enough.

**Review by felixcheung — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

Thank you @felixcheung.

**Pull request closed without merging**
