### PR TITLE
[WIP][SPARK-40586][CONNECT] Decouple plan transformation and validation on server side

### PR DESCRIPTION
**Pull request by beliefer**
### What changes were proposed in this pull request?
Project connect, from some perspectives, can be thought as replacing the SQL parser to generate a parsed (but the difference that is unresolved) plan, then the plan is passed to the analyzer. This means that connect should also do validation on the proto as there are many in-validate parser cases that analyzer does not expect to see, which potentially could cause problems if connect only pass through the proto (of course have it translated) to analyzer.
Meanwhile I think this is a good idea to decouple the validation and transformation so that we have two stages:
stage 1: proto validation. For example validate if necessary fields are populated or not.
stage 2: transformation, which convert the proto to a plan with assumption that the plan is valid parsed version of the plan.

This PR checks before transformation through a simple proxy pattern.

Because there are a lot of job to do, this PR only given an example(e.g. `checkReadRel`). So that acilitate communication and discussion.

### Why are the changes needed?
Decouple plan transformation and validation on server side

### Does this PR introduce _any_ user-facing change?
'No'.
Just update the inner implementation.

### How was this patch tested?
Exists test cases.

### CODE REVIEW

**Comment by beliefer** [comment]
ping @HyukjinKwon @hvanhovell @zhengruifeng cc @amaliujia

**Comment by amaliujia** [comment]
I personally like this direction which is separating validation and transforming. The main benefit is code readability and also structure the code in a more logical way. 


cc @grundprinzip

**Comment by grundprinzip** [comment]
@beliefer First of all, thanks a lot for the proposal and the approach to improving the quality and readability of the Spark Connect code.

Personally, I don't think this change is a good approach for the following reasons:

* The logic in `checkRelation` essentially becomes a shadow path to the logic in the actual planner. For the reviewer of the code and the writer, this means they have to validate the code and the behavior in two places and make sure that the behaviors are congruent.
* In addition, when reviewing these changes of the refactoring, it is already hard now to reason about the probability of regression because the refactoring is not just purely cosmetic but for example, changes the actual branches and conditions of the planning logic. I agree that some of the removed branches are unreachable after the checker is introduced but I wanted to raise the complication of the review itself.
* Lastly, I think that this separation in general will reduce the reviewability of the code because the refactoring extracts non-trivial logical analysis that is easier understood close to where it's actually evaluated.

That said, I think we definitely have room for improvement to increase the readability and style of the code to make it easier to contribute. Maybe there are slightly smaller and more incremental ways to improve it?

Thanks again for trying the approach!

**Comment by beliefer** [comment]
@grundprinzip Thank you for your review. I agree your opinion that list three issues. This PR provides a proposal that references `Analyzer` and `CheckAnalysis`. As you said, `Analyzer` and `CheckAnalysis` exists the three issues too. If we can't accept this proposal, so do we need to review Analyzer` and `CheckAnalysis` ?

**Pull request closed without merging**
