### PR TITLE
SPARK-4921. TaskSetManager.dequeueTask returns PROCESS_LOCAL for NO_PREF ...

### PR DESCRIPTION
**Pull request by sryza**
...tasks

### CODE REVIEW

**Comment by mateiz** [comment]
@sryza any progress investigating this? FYI those NO_PREF tasks can be returned when the locality level is "any" and "rack_local" too. See TaskLocality.scala. If you don't show a concrete benefit from this, I'd suggest closing the issue and not changing it. The way I see it, this could break the scheduling order in existing jobs, with minimal benefit in performance (just avoiding one small delay for datasets that include both combined and non-combined files).

**Comment by sryza** [comment]
My conclusion (sorry if it was unclear above) was that dequeueTask returning NO_PREF instead of PROCESS_LOCAL should have no effect at all.  I still think it's worth changing for clarity, but it's obviously less important.

In what cases would dequeueTask return NO_PREF tasks when maxLocality=RACK_LOCAL or ANY?  My understanding is that, in a single resourceOffers call, dequeueTask gets called multiple times in order of TaskLocality, so any NO_PREF tasks would be returned when it's called with maxLocality=NO_PREF.  And none would remain when ANY and RACK_LOCAL come around.

**Comment by sryza** [comment]
I'm going to close this as "Won't Fix" as this has been open for a long time, touches sensitive code, and is mainly a code cleanup issue.

**Comment by zsxwing** [comment]
@sryza, could you reopen this one? 

TaskInfo will be sent to SparkListener. Without this patch, for NO_PREF RDDs, their `taskLocality`s in `TaskInfo` will be `PROCESS_LOCAL`, and the user can see it in SparkListener. Test codes:
```
    import org.apache.spark.scheduler.{SparkListenerTaskStart, SparkListener}
    sc.addSparkListener(new SparkListener{
      override def onTaskStart(taskStart: SparkListenerTaskStart): Unit = {
        println("taskLocality: " + taskStart.taskInfo.taskLocality)
      }
    })
    sc.parallelize(1 to 10, 1).count()
```

**Comment by sryza** [comment]
@zsxwing I have sadly lost most of the context on this issue and don't have time to pick it back up at the moment.

What you point out does seem to be an issue, though.  Definitely feel free to take my patch if you think it's the right fix.

**Comment by zsxwing** [comment]
retest this please

**Comment by zsxwing** [comment]
I think this is the right fix. However, more pairs of eyes on this change would be better.

**Comment by rxin** [comment]
I'm going to close this pull request. If this is still relevant and you are interested in pushing it forward, please open a new pull request. Thanks!

**Pull request closed without merging**
