### PR TITLE
[SPARK-22690][ML] Imputer inherit HasOutputCols

### PR DESCRIPTION
**Pull request by zhengruifeng**
## What changes were proposed in this pull request?
make `Imputer` inherit `HasOutputCols`

## How was this patch tested?
existing tests

### CODE REVIEW

**Comment by zhengruifeng** [comment]
No other algs output multi-column for now

**Comment by holdenk** [comment]
LGTM pending Jenkins.

**Comment by zhengruifeng** [comment]
retest this please

**Comment by zhengruifeng** [comment]
retest this please

**Comment by MLnick** [comment]
LGTM thanks!

**Comment by WeichenXu123** [comment]
LGTM.

**Pull request closed without merging**
