### PR TITLE
SPARK-2168 [Spark core] Use relative URIs for the app links in the History Server.

### PR DESCRIPTION
**Pull request by elyast**
Removing full URI leaving only relative path in link to the completed application plus unit test

### CODE REVIEW

**Comment by andrewor14** [comment]
I see. Nevertheless it would be good to merge the tests in master too. Feel free to open a new PR just for the test.

**Comment by andrewor14** [comment]
Actually, let's retest this please

**Comment by andrewor14** [comment]
Looks like branch-1.0 is consistently failing tests (not related to this PR)

**Comment by srowen** [comment]
Is this still live? I think this PR should be closed in any event, but the test can go in master in a separate PR. Otherwise let's close this.

**Comment by elyast** [comment]
Fine with me, I will add tests on master with new PR

**Pull request closed without merging**
