### PR TITLE
[SPARK-36345][INFRA] Update PySpark GitHubAction docker image to 20210730

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to upgrade PySpark GitHub Action job to use the latest docker image `20210730` having `sklearn` and `mlflow` additionally.
- https://github.com/dongjoon-hyun/ApacheSparkGitHubActionImage/commit/5ca94453d1108dfe40bceb8872387a1b19b0c783

```
$ docker run -it --rm dongjoon/apache-spark-github-action-image:20210730 python3.9 -m pip list | grep mlflow
mlflow                    1.19.0

$ docker run -it --rm dongjoon/apache-spark-github-action-image:20210730 python3.9 -m pip list | grep sklearn
sklearn                   0.0
```

### Why are the changes needed?

This will save the installation time.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the GitHub Action PySpark jobs.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
cc @HyukjinKwon

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master and branch-3.2.

**Comment by HyukjinKwon** [comment]
the test failure shouldn't be related. it's from my mistake https://github.com/apache/spark/pull/33596

**Comment by ueshin** [comment]
Oh, wait. Actually pandas in the docker images was upgraded to 1.3.1. I guess it caused the test failures.

```
pandas                    1.3.1
```

**Comment by HyukjinKwon** [comment]
Oh I a bit rushed to merge. @ueshin would you mind taking a quick look please for pandas 1.3.1 upgrade? I can't work on it at this moment. Reverting it for now is fine to me too.

**Comment by ueshin** [comment]
Or we can disable the tests for now (#33598).

**Comment by dongjoon-hyun** [comment]
This is reverted.
- https://github.com/apache/spark/commit/95a5c1702d28ac737794e0cdad541e83322e2f8e

**Comment by ueshin** [comment]
@dongjoon-hyun This was also merged to 3.2. Could you revert it as well? Thanks!

**Comment by HyukjinKwon** [comment]
Thanks guys!!

**Comment by HyukjinKwon** [comment]
> @dongjoon-hyun This was also merged to 3.2. Could you revert it as well? Thanks!

Done 👍

**Comment by dongjoon-hyun** [comment]
Oh. Thanks, @HyukjinKwon . I missed the ping here.

**Pull request closed without merging**
