### PR TITLE
[SPARK-42885][K8S][BUILD] Upgrade `kubernetes-client` to 6.5.1

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to upgrade `kubernetes-client` to 6.5.1.

### Why are the changes needed?

To bring the latest bug fixes.
- https://github.com/fabric8io/kubernetes-client/releases/tag/v6.5.1

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the CIs

### CODE REVIEW

**Comment by amaliujia** [comment]
LGTM

**Comment by dongjoon-hyun** [comment]
Thank you, @amaliujia . 

Also, could you review this PR, @viirya ?

**Review by viirya — APPROVED** [review]

**Review by viirya — COMMENTED** [review]
Looks good and CI also passed.

**Comment by dongjoon-hyun** [comment]
Thank you, @viirya . Merged to master for Apache Spark 3.5.

**Pull request closed without merging**
