### PR TITLE
[SPARK-31203][BUILD] Upgrade derby to 10.14.2.0 from 10.12.1.1

### PR DESCRIPTION
**Pull request by Udbhav30**
### What changes were proposed in this pull request?
This PR(SPARK-31203) aims to upgrade derby.

Some major changes from this upgrade are
[DERBY-6987](https://issues.apache.org/jira/browse/DERBY-6987)   The default Network Server security policy file could be trimmed down somewhat.
[DERBY-6986](https://issues.apache.org/jira/browse/DERBY-6986)  Network Server COMMAND_TESTCONNECTION need not try to open a database
[DERBY-6726](https://issues.apache.org/jira/browse/DERBY-6726)	NPE from trigger

### Why are the changes needed?
To bring some bug fixes.

### Does this PR introduce any user-facing change?
no

### How was this patch tested?
manual build

### CODE REVIEW

**Comment by Udbhav30** [comment]
cc @dongjoon-hyun

**Comment by maropu** [comment]
ok to test

**Comment by maropu** [comment]
Could you leave some major changes from `10.12.1.1` to `10.14.2.0` in the PR descritpion? e.g., https://github.com/apache/spark/pull/27860#issue-385900495

**Review by dongjoon-hyun — COMMENTED** [review]
Hi, @Udbhav30 . Thank you for making a PR. BTW, in a production environment, Apache Hive Metastore is used instead of `Derby`. I don't think this PR is a security related patch. Also, those network features of Derby are not used by Apache Spark, are they?

Also, this increases the inconsistency from Hive modules which use `10.10.2.0` in `hive-1.2` and `hive-2.3` profiles. We don't use `Hive 3.0+`.
```
Apache Hive 3.0.0 ~ 4.0.0-SNAPSHOT
<derby.version>10.14.1.0</derby.version>

Apache Hive 1.2.0 ~ 2.3.7-SNAPSHOT
<derby.version>10.10.2.0</derby.version>
```

cc @wangyum

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by HyukjinKwon** [comment]
Yeah, Derby isn't for production purpose - separate Metastore is supposed to be used. I don't think that security issue actually matters too. Also, yes, I wouldn't upgrade derby but rather try to match with Hive's side. 

Furthermore, different Derby can be picked up (see https://github.com/apache/spark/pull/20944).  Sharing it will potentially cause an issue; therefore, technically upgrading does not fully address the issue you pointed out.

-1 from me.

**Comment by Udbhav30** [comment]
Hi @dongjoon-hyun , i opened the PR because of the security fix. If you suggest this PR is not required then i will close it.
Please provide your suggestions thanks.

**Comment by HyukjinKwon** [comment]
If the security issue doesn't directly affect the project, we dont necessarily have to upgrade it. Given that we don't use Derby in production and the upgrade doesn't look completely handling the issue even if it affects Spark, seems not worthwhile upgrading for now.

Can you describe how Spark is affected by the security issue you mentioned?

**Comment by dongjoon-hyun** [comment]
Thank you all!

**Pull request closed without merging**
