### PR TITLE
[SPARK-22857] Optimize code by inspecting code

### PR DESCRIPTION
**Pull request by xubo245**
Optimize code by inspecting code, including:
remove some unused import
change invoking array size method to length method
use head method

## What changes were proposed in this pull request?

Optimize code by inspecting code

## How was this patch tested?

No

### CODE REVIEW

**Comment by srowen** [comment]
In the past we've said 'no' to random small changes to the code like this. Some changes like _ to null probably aren't worth it at all. (0) to .head is the same, I think.

Removing unused imports is OK, and I personally am OK with .size to .length for arrays because it avoids an implicit conversion. But, it needs to be done consistently or not at all.

**Comment by xubo245** [comment]
ok

**Comment by xubo245** [comment]
Ok, I remove some changes.

**Review by srowen — COMMENTED** [review]
I would do all or nothing. I am sure there are more array issues at least

**Comment by xubo245** [comment]
@srowen  I find all related array size warning, 


are there any other issues?

**Comment by srowen** [comment]
There are lots more than this, no. I don't think it's worthwhile, unless you're finding several that might cause a performance problem.

**Pull request closed without merging**
