### PR TITLE
[SPARK-48787][BUILD] Upgrade Kafka to 3.7.1

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to upgrade `kafka` from `3.7.0` to `3.7.1`.

### Why are the changes needed?
https://downloads.apache.org/kafka/3.7.1/RELEASE_NOTES.html

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by panbingkun** [comment]
cc @dongjoon-hyun

**Comment by HyukjinKwon** [comment]
cc @HeartSaVioR

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @panbingkun .
Merged to master for Apache Spark 4.0.0-preview2.

**Comment by HeartSaVioR** [comment]
Upgrading bugfix version sounds fine and less risky unless any system test captures some issue. Thanks for the fix.

**Pull request closed without merging**
