### PR TITLE
[SPARK-4387][PySpark] Refactoring python profiling code to make it extensible

### PR DESCRIPTION
**Pull request by udnay**
This is a refactor of the [profiling feature](https://github.com/apache/spark/commit/c5414b681868a0a11cc5a94184116e66e8d3e9c0) done by @davies 

This will allow us to hook in custom profilers and output sinks more easily.

### CODE REVIEW

**Comment by udnay** [comment]
Sorry, just saw this. Thanks @davies

**Comment by pwendell** [comment]
@udnay this does not merge cleanly. Can you rebase it?

**Comment by davies** [comment]
@pwendell I had create another PR #3901 to fix the conflict, also there are some refactor there. 

@udnay Would you mind to close this one?

**Comment by udnay** [comment]
Replaced by #3901

**Pull request closed without merging**
