### PR TITLE
[SPARK-43917][PS][INFRA] Upgrade `pandas` to 2.0.2

### PR DESCRIPTION
**Pull request by bjornjorgensen**
### What changes were proposed in this pull request?
Upgrade pandas from 2.0.0 to 2.0.2

### Why are the changes needed?
This fixes some regressions and bugs. 

[Whats new in 2.0.2](https://pandas.pydata.org/docs/whatsnew/v2.0.2.html)

[Whats new in 2.0.1](https://pandas.pydata.org/docs/whatsnew/v2.0.1.html)

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
cc @itholic and @HyukjinKwon according to the previous comments on Pandas 2.0.0 PR.

**Comment by itholic** [comment]
It's pretty makes sense to me although we still need to discuss the potential behavior changes for future updates.

**Comment by itholic** [comment]
It looks pretty making sense to me since it's not introduce any extra test skipping or behavior changes.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Pull request closed without merging**
