### PR TITLE
[SPARK-38267][CORE][SQL][SS] Replace pattern matches on boolean expressions with conditional statements

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr uses `conditional statements` to simplify `pattern matches on boolean`:

**Before**

```scala
val bool: Boolean
bool match {
    case true => do something when bool is true
    case false => do something when bool is false
} 
```

**After**

```scala
val bool: Boolean
if (bool) {     
  do something when bool is true   
} else {     
  do something when bool is false   
} 
```

### Why are the changes needed?
Simplify unnecessary pattern match.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass GA

### CODE REVIEW

**Comment by srowen** [comment]
It's minor but I do tend to agree this use of match is strictly less readable.

**Review by srowen — APPROVED** [review]
Are there more instances?

**Comment by LuciferYang** [comment]
That's all

**Comment by srowen** [comment]
Merged to master

**Comment by LuciferYang** [comment]
thanks @srowen

**Pull request closed without merging**
