### PR TITLE
[SPARK-31128][WebUI] Fix Uncaught TypeError in streaming statistics page

### PR DESCRIPTION
**Pull request by gengliangwang**
### What changes were proposed in this pull request?

There is a minor issue in https://github.com/apache/spark/pull/26201
In the streaming statistics page, there is such error
```
streaming-page.js:211 Uncaught TypeError: Cannot read property 'top' of undefined
at SVGCircleElement.<anonymous> (streaming-page.js:211)
at SVGCircleElement.__onclick (d3.min.js:1)
```
in the console after clicking the timeline graph.
image

This PR is to fix it.
### Why are the changes needed?

Fix the error of javascript execution.

### Does this PR introduce any user-facing change?

No, the error shows up in the console.

### How was this patch tested?

Manual test.

### CODE REVIEW

**Comment by gengliangwang** [comment]
cc @uncleGen @sarutak @zsxwing 
An alternative way is to add a new boolean parameter `addClickEvent` in the method `drawTimeline`, which is cleaner but touches more code.

**Review by dongjoon-hyun — COMMENTED** [review]
Hi, @gengliangwang . 
The patch itself looks correct to me. Could you give us how to verify your PR?
Does the error happen always?

**Comment by gengliangwang** [comment]
@dongjoon-hyun I ran some streaming queries and visit the page "/StreamingQuery/statistics", click the graph and check the console output in Chrome.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by gengliangwang** [comment]
Thanks, merging to master/3.0

**Pull request closed without merging**
