### PR TITLE
[SPARK-15095] [SQL] drop binary mode in ThriftServer

### PR DESCRIPTION
**Pull request by davies**
## What changes were proposed in this pull request?

This PR drop the support for binary mode in ThriftServer, only HTTP mode is supported now, to reduce the maintain burden.

The code to support binary mode is still kept, just in case if we want it  in future.
## How was this patch tested?

Updated tests to use HTTP mode.

### CODE REVIEW

**Comment by davies** [comment]
cc @rxin

**Comment by rxin** [comment]
LGTM as long as we get tests to pass.

**Comment by rxin** [comment]
Merging in master/branch-2.0.

**Comment by epahomov** [comment]
I've created a ticket to revert these changes - https://issues.apache.org/jira/browse/SPARK-15934

**Pull request closed without merging**
