### PR TITLE
[SPARK-32577][SQL][TEST] Fix the config value for shuffled hash join in test in-joins.sql

### PR DESCRIPTION
**Pull request by c21**
### What changes were proposed in this pull request?

We found the `in-join.sql` does not test shuffled hash join properly in https://issues.apache.org/jira/browse/SPARK-32577, but didn't find a good way to fix it. Given we now have a test config to enforce shuffled hash join in https://github.com/apache/spark/pull/33182, we can fix the test here now as well.

### Why are the changes needed?

Fix test to have better test coverage.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Reran the test to compare the output, and verified the query plan manually to make sure shuffled hash join being used.

### CODE REVIEW

**Comment by c21** [comment]
cc @cloud-fan, thanks.

**Review by cloud-fan — APPROVED** [review]

**Comment by cloud-fan** [comment]
are there more places that need to fix?

**Review by HyukjinKwon — APPROVED** [review]

**Comment by c21** [comment]
It seems not searchable in repo, let me try to figure out all places tomorrow. Thanks.

**Comment by HyukjinKwon** [comment]
let me just merge it in then.

**Comment by HyukjinKwon** [comment]
Merged to master and branch-3.2.

**Comment by c21** [comment]
Thank you @HyukjinKwon and @cloud-fan for review! Will submit another PR for other changes.

**Pull request closed without merging**
