### PR TITLE
SPARK-18844[MLLIB] Add more binary classification metrics to BinaryClassificationMetrics

### PR DESCRIPTION
**Pull request by sandecho**
## What changes were proposed in this pull request?

In this PR, more binary classification metrics has been added to BinaryClassificationMetrics as mentioned in SPARK-18844
## How was this patch tested?
By running existing unit test

Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Comment by sandecho** [comment]
[SPARK-18844.zip](https://github.com/apache/spark/files/1708136/SPARK-18844.zip)

**Comment by sandecho** [comment]
ok to test. Jenkins, add to whitelist.

**Comment by srowen** [comment]
I'm not sure there was support to make this change. The value of these additional metrics is pretty marginal.

**Comment by sandecho** [comment]
Srowen: Will the result of the test not be posted?

**Comment by sandecho** [comment]
I will generate the patch once again and submit

**Comment by srowen** [comment]
As I say, I don't think this would be merged anyway.

**Comment by sandecho** [comment]
Then why was the status of JIRA left open from so many days. It was supposed to be closed earlier.

**Comment by sandecho** [comment]
As a first time contributor and a novice on it, I would submit the final patch and leave it up to you. You can merge it or leave it. I will close the pull request after that, whether patch is accepted or not.

**Comment by sandecho** [comment]
I have committed the changes. Can you please run the test?

**Comment by sandecho** [comment]
Can you please run the test again?
[SPARK-JIRA-18844.zip](https://github.com/apache/spark/files/1724418/SPARK-JIRA-18844.zip)

**Comment by srowen** [comment]
This doesn't even merge, so tests can't run.

**Pull request closed without merging**
