### PR TITLE
SPARK-11882: Custom scheduler support

### PR DESCRIPTION
**Pull request by jacek-lewandowski**

### CODE REVIEW

**Comment by ScrapCodes** [comment]
Hi @jacek-lewandowski, thanks for the patch !. Are you using the custom mode ? Or did you try your patch against a custom deploy mode ?

**Comment by jacek-lewandowski** [comment]
@ScrapCodes - yes, we are building Spark on top of this change and it is working correctly.

**Comment by rxin** [comment]
Thanks for the pull request. I'm going through a list of pull requests to cut them down since the sheer number is breaking some of the tooling we have. Due to lack of activity on this pull request, I'm going to push a commit to close it. Feel free to reopen it or create a new one.

**Comment by cerisier** [comment]
This is pure awesome. Any chance of this being revisited someday ?

**Pull request closed without merging**
