### PR TITLE
[SPARK-12958] [CORE] Adding Map accumulator String->Long

### PR DESCRIPTION
**Pull request by sourind**
Users can use this to accumulate long values against String keys

@srowen Can you please give permission for testing it in Jenkins ?

### CODE REVIEW

**Comment by jodersky** [comment]
Just saw the discussion on the JIRA.
IMO this is a bit too specific, wouldn't it make sense to include a more generic version of MapAccumulatorParam. Something like MapAccumulatorParam[A, B], where B has to have an implicit AccumulatorParam[B] itself?

**Comment by sourind** [comment]
Thanks for looking into it. Most of the time, string keys should solve the
problem but yes, no harm in making it more generic. I will work on it and
submit a new patch.

**Comment by rxin** [comment]
Do we need this in Spark? It seems like it is just a few lines of code.

**Comment by sourind** [comment]
There is a TODO in Accumulators.scala
<https://github.com/apache/spark/blob/302bb569f3e1f09e2e7cea5e4e7f5c6953b0fc82/core/src/main/scala/org/apache/spark/Accumulator.scala#L159>
for
adding different accumulator params (Lists, Strings etc.). This change is
similar to that.
Also, with this change people can accumulate values for keys that are not
initially defined in the driver -therefore, allowing users to define
metrics at runtime.
Let me know  your thoughts on this.

Thanks,
Souri

**Comment by JoshRosen** [comment]
I'm against this in its current form; this seems like a niche feature for which there's not high demand.

**Comment by andrewor14** [comment]
I agree with @JoshRosen. It seems this map param is essentially a collection of a few individual Long accums, and the user can manage that better themselves. Also, the user can always write their own map param if they want.

@sourind let's close this PR.

**Comment by sourind** [comment]
Sure.

--Souri

**Comment by srowen** [comment]
@sourind please close this pull request

**Pull request closed without merging**
