### PR TITLE
[SPARK-2750][WEB UI] Add https support to the Web UI

### PR DESCRIPTION
**Pull request by vanzin**

### CODE REVIEW

**Comment by vanzin** [comment]
This is a fixed up version of #5664.

**Comment by vanzin** [comment]
retest this please

**Comment by vanzin** [comment]
retest this please

**Comment by shaneknapp** [comment]
jenkins test this please

**Comment by shaneknapp** [comment]
jenkins test this please

**Comment by vanzin** [comment]
unrelated test failures. anybody want to take a look at the changes? /cc @andrewor14 @WangTaoTheTonic

**Comment by vanzin** [comment]
retest this please

**Comment by vanzin** [comment]
retest this please

**Comment by WangTaoTheTonic** [comment]
Sorry for late. Think you need update codes to the newest and see if the test cases fine.
Then we do some review and function tests.

**Comment by vanzin** [comment]
retest this please

**Comment by vanzin** [comment]
retest this please

**Comment by WangTaoTheTonic** [comment]
It seems conflicted :(

**Comment by vanzin** [comment]
Yeah, my own fault most probably.

**Comment by vanzin** [comment]
retest this please

**Comment by vanzin** [comment]
Seemingly unrelated failures. retest this please

**Comment by vanzin** [comment]
retest this please

**Comment by vanzin** [comment]
wtf. retest this please

**Comment by vanzin** [comment]
retest this please

**Comment by vanzin** [comment]
retest this please

**Comment by vanzin** [comment]
retest this please

**Comment by vanzin** [comment]
While jenkins continues to ignore me, does anyone have any comment about the actual changes?

retest this please

**Comment by vanzin** [comment]
Yay, finally. Any comments anyone? Otherwise I'll push this soon-ish.

**Comment by vanzin** [comment]
retest this please

**Comment by vanzin** [comment]
Alright, merging this since nobody seems concerned about anything.

**Comment by pritpalm** [comment]
I want to enable https on spark UI. I added following config to spark-defaults.config, but when we access spark ui via https::/<ip>:8080 or https://<ip>:443 or https://<ip>:8480, it's not able to connect.

spark.ui.https.enabled true
spark.ssl.keyPassword abcd
spark.ssl.keyStore rtmqa-clientid.jks
spark.ssl.keyStorePassword changeit

**Comment by LizzyMiao** [comment]
@vanzin @WangTaoTheTonic  @scwf   can you provide a doc or something that we can follow to use https for our spark web ui?  Thank you!

**Comment by vanzin** [comment]
@LizzyMiao it's already in the Spark documentation. If you need further help I suggest using the project's user mailing list. Github is for code-related discussions, not a general user forum.

**Pull request closed without merging**
