### PR TITLE
[SPARK-36942][PYTHON] Inline type hints for python/pyspark/sql/readwriter.py

### PR DESCRIPTION
**Pull request by xinrong-meng**
### What changes were proposed in this pull request?
Inline type hints for python/pyspark/sql/readwriter.py

### Why are the changes needed?
Currently, `python/pyspark/sql/readwriter.pyi` is used for type hints, which doesn't support type checking within function bodies. So we inline type hints for python/pyspark/sql/readwriter.py to enable type checking within function bodies.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Existing tests

### CODE REVIEW

**Comment by xinrong-databricks** [comment]
CC @ueshin @HyukjinKwon @itholic @zero323

**Review by HyukjinKwon — APPROVED** [review]

**Review by ueshin — APPROVED** [review]
Otherwise, LGTM.

**Review by zero323 — COMMENTED** [review]
I rebased this locally to f678c75d3940b2887fdb2621691b791b95d79469 and see the following errors

```
python/pyspark/sql/readwriter.py:785: error: Argument 2 to "_to_seq" has incompatible type "Tuple[Union[str, List[str]], ...]"; expected "Iterable[Union[Column, str]]"  [arg-type]
python/pyspark/sql/readwriter.py:844: error: Argument 2 to "_to_seq" has incompatible type "Tuple[Optional[str], ...]"; expected "Iterable[Union[Column, str]]"  [arg-type]
python/pyspark/sql/readwriter.py:889: error: Argument 2 to "_to_seq" has incompatible type "Tuple[Optional[str], ...]"; expected "Iterable[Union[Column, str]]"  [arg-type]
```

**Comment by zero323** [comment]
LGTM, once pypy issue is resolved.

**Pull request closed without merging**
