### PR TITLE
[SPARK-20279][WEB-UI]In web ui,'Only showing 200' should be changed to 'only showing last 200'.

### PR DESCRIPTION
**Pull request by guoxiaolongzte**
## What changes were proposed in this pull request?

In web ui,'Only showing 200' should be changed to 'only showing last 200' in the page of 'jobs' or stages.

purpose:
I think, the description about add 'last', the purpose is to ensure that users more clearly know that the current show 'jobs or stages', is the latest 200 'jobs or stages', Or the beginning 200 of the 'jobs or stages'.

please see the attachment of 'SPARK-20279'.
url:https://issues.apache.org/jira/browse/SPARK-20279

## How was this patch tested?
unit tests,manual tests

Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Comment by srowen** [comment]
I'm not sure this is accurate, given how sort order can be changed? maybe not, but it's at least ambiguous, and don't think it adds enough to change this.

**Comment by ajbozarth** [comment]
I agree with @srowen we left it that way since sorting can change

**Comment by guoxiaolongzte** [comment]
sorting can change?I do not think so.
Even if the sorting is only show the last 200, and I raised the issue is not contradictory.
The last 200 are the concept of a batch of data.

**Comment by srowen** [comment]
Even if so it's not worth changing. This should be closed

**Pull request closed without merging**
