### PR TITLE
[SPARK-47453][SQL][DOCKER][BUILD][TESTS] Upgrade MySQL docker image version to 8.3.0

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

Upgrade MySQL docker image version to 8.3.0

### Why are the changes needed?

test dependencies upgrading

### Does this PR introduce _any_ user-facing change?

no
### How was this patch tested?

passed locally with:
`./build/sbt -Pdocker-integration-tests  "docker-integration-tests/testOnly *MySQLIntegrationSuite"`
### Was this patch authored or co-authored using generative AI tooling?

no

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM (Pending CIs), @yaooqinn .

**Comment by dongjoon-hyun** [comment]
Merged to master for Apache Spark 4.0.0.

**Comment by yaooqinn** [comment]
Thank you @dongjoon-hyun

**Comment by pan3793** [comment]
Hi, @yaooqinn and @dongjoon-hyun, MySQL 8.3 is not an LTS version while 8.0 is, as an RDBMS, a non-LTS version is not likely adopted widely than LTS.

https://dev.mysql.com/blog-archive/introducing-mysql-innovation-and-long-term-support-lts-versions/

Also, Spark officially only supports LTS Java versions, like JDK 17 and 21, but not 22. I would recommend using MySQL 8.0 until the next LTS version is available.

**Comment by dongjoon-hyun** [comment]
It's an interesting suggestion. However, I don't think Apache Spark has such a community policy for MySQL LTS support so far, @pan3793 . 

Do you have a concern that MySQL community doesn't follow `Semantic Versioning` and will break something between 8.0 and 8.3?

**Comment by dongjoon-hyun** [comment]
According to your request, why don't you send an email to initiate the discussion about the discussion, @pan3793 ? We can make it as a new community policy (JDBC LTS?) if needed.

**Comment by yaooqinn** [comment]
Is it necessary for a test/dev dependency to be a strict LTS? Is it even comparable with policies of adopting JDKs?
 
- The connector/j version was bumped up before this server-side change.
- It's nice to pre-check if any behavior changes when upgrading to the latest. So far so good.

According to suggestions by MySQL official https://dev.mysql.com/doc/refman/8.3/en/upgrade-paths.html

> It is necessary to upgrade to the latest innovation releases (for example, from MySQL 8.2 to 8.3) regularly to keep up with the latest bug fixes and security patches.

**Comment by dongjoon-hyun** [comment]
+1 for @yaooqinn ’s comment.

**Comment by pan3793** [comment]
@dongjoon-hyun thanks for your suggestion, I sent an email to the `user`/`dev` mailing list, but limited the scope to MySQL version policy since I have less knowledge of other RDBMS.

https://lists.apache.org/thread/rqso3mf3ll1p2sfw02wzcxbjo2xno6go

@yaooqinn I would say, yes, MySQL(including the similar product provided by Cloud vendors, i.e. Amazon RDS for MySQL) is one of the most important infrastructures today.

> Is it even comparable with policies of adopting JDKs?

**Comment by dongjoon-hyun** [comment]
Thank you. I replied.
- https://lists.apache.org/thread/mz1ww4wsqd5sfwkokrn938l2nlyx2vqg

**Pull request closed without merging**
