### PR TITLE
[SPARK-39784][SQL][FOLLOW-UP] Use BinaryComparison instead of Predicate (if) for type check

### PR DESCRIPTION
**Pull request by huaxingao**
### What changes were proposed in this pull request?
follow up this [comment](https://github.com/apache/spark/pull/37197#discussion_r928570992)

### Why are the changes needed?
code simplification

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Existing test

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Could you remove `isBinaryComparisonOperator`, @huaxingao ?

https://github.com/apache/spark/blob/6b2492628c60fc1c4f70889c71cc3a9403a0adbc/sql/core/src/main/scala/org/apache/spark/sql/catalyst/util/V2ExpressionBuilder.scala#L272-L277

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Review by cloud-fan — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Merged to master. The TPC-DS integration test seems to be still flaky.

**Comment by huaxingao** [comment]
Thanks @dongjoon-hyun @cloud-fan

**Pull request closed without merging**
