### PR TITLE
[MINOR][PySpark] update _shared_params_code_gen.py

### PR DESCRIPTION
**Pull request by zhengruifeng**
## What changes were proposed in this pull request?

1, add arg-checkings for `tol` and `stepSize` to  keep in line with `SharedParamsCodeGen.scala`
2, fix one typo
## How was this patch tested?

local build

### CODE REVIEW

**Comment by yanboliang** [comment]
@zhengruifeng If you make change for ```_shared_params_code_gen.py```, please run ```python _shared_params_code_gen.py > shared.py``` to update ```shared.py``` as well.
Are you checked for all non-consistent param docs between Scala and Python? It's better we can do it in a big sweep.

**Comment by zhengruifeng** [comment]
@yanboliang  I have checked all the SharedParams. I will make a review of other params in pyspark.

**Comment by holdenk** [comment]
@zhengruifeng Can you please run the the shared.py file as @yanboliang suggested? The codegen isn't run automatically.

**Comment by zhengruifeng** [comment]
@holdenk Ok, I will update it.

**Comment by yanboliang** [comment]
LGTM

**Comment by MLnick** [comment]
LGTM, merged to master and branch-2.0. Thanks!

**Pull request closed without merging**
