### PR TITLE
[MLLIB][SPARK-4675] Find similar products and similar users in MatrixFactorizationModel

### PR DESCRIPTION
**Pull request by sbourke**
Using the latent feature space that is learnt in MatrixFactorizationModel, I have added 2 new functions to find similar products and similar users. A user of the API can for example pass a product ID, and get the closest products based on the feature space.

### CODE REVIEW

**Comment by srowen** [comment]
I kind of like this functionality; @sbourke are you in a position to continue with this? I think it needs a few typo fixes and commentary about its function. This is really about computing similar users and items rather than recommending items to users or users to items. I also think it has to include dividing by the norms to be cosine similarity.

**Comment by debasish83** [comment]
@srowen we have to be a bit careful since dense blas has to be used...I have a internal version with dot and it needs to be more faster..also one at a time is not a good idea...there has to be block dense matrix * block dense matrix operation...that way we can reuse native dgemm...

**Comment by srowen** [comment]
Agree, although this is no worse than the existing implementation for recommendation (it reuses it even).

**Comment by debasish83** [comment]
agreed...Dense BLAS will be a common optimization to item->item, user->user and user->item APIs...

**Comment by debasish83** [comment]
@MLnick @srowen I did an experiment where I computed brute force topK similar items using cosine distance and compared the intersection with item factor based brute force topK similar items using cosine distance after running implicit factorization...intersection is only 42%...this is inline with Google Correlate paper where they have to do an additional reorder step in real feature space to increase the recall (intersect)...did you guys also see similar results for item->item validation ?

**Comment by MLnick** [comment]
Not sure I follow completely - do you mean you compared cosine sim between raw (ie "rating") item vectors, and cosine sim computed from item factor vectors? I would imagine they would be quite different...

I always just use factor vectors

**Comment by srowen** [comment]
I have not benchmarked these since neither is a "correct" answer to benchmark against the other. The cosine similarity isn't really that valid in the original feature space. It might still be interesting to know how different the answers are but they're probably going to be fairly different on purpose.

**Comment by debasish83** [comment]
@MLnick yes that's what I did...I have to convince users why use factor vectors :-) For user->item recommendation, convincing is easy by showing the ranking improvement through ALS

@srowen without coming up with a validation strategy, someone might propose to run a different algorithm (KMeans on raw feature space followed by (item->cluster) join (cluster->items)) and claims his item->item results are better...how do we know whether ALS based flow is producing better result or KMeans based flow ? NNALS can be thought of soft-kmeans as well and so these flows are very similar.

I am focused on implicit feedback here because then only we can run either KMeans or Similarity on raw feature space...With explicit feedback, I agree that cosine similarity is not valid in original feature space. But in most practical datasets, we are dealing with implicit feedback.

**Comment by debasish83** [comment]
Let's continue the validation discussion on https://github.com/apache/spark/pull/6213. The PR introduces batch gemm based similarity computation in MatrixFactorizationModel using kernel abstraction. Do need the online version as well that Steven added or it can be extracted out of batch results ? My focus was more on speeding up batch computation...

**Comment by rxin** [comment]
I'm going to close this pull request. If this is still relevant and you are interested in pushing it forward, please open a new pull request. Thanks!

**Pull request closed without merging**
