### PR TITLE
[SPARK-5058] Part 2. Typos and broken URL

### PR DESCRIPTION
**Pull request by jongyoul**
- Also fixed java link

### CODE REVIEW

**Comment by jongyoul** [comment]
retest this please

**Comment by srowen** [comment]
Looks like a good follow-on change to https://github.com/apache/spark/pull/3877 . I noted that github seems to redirect the `/tree` URLs to `/blob` URLs (that's not what's being 'fixed' here) and we have a mix of both, but yeah, when changing links we can just point to `/blob` as well.

**Comment by rxin** [comment]
Thanks. Merging in master.

**Pull request closed without merging**
