### PR TITLE
[SPARK-3533][Core] Add saveAsTextFileByKey() method to RDDs

### PR DESCRIPTION
**Pull request by saurfang**
This adds the functionality of saving a `RDD[(K, V)]` to multiple text files split by key. It covers Scala/Java/Python API. 

This is based on the Stackoverflow answer linked in the original JIRA and  https://github.com/apache/spark/pull/4895. 
Furthermore, I have fixed an issue where part filenames were not included in the paths causing executors to override each other. Tests verify written contents.

I'm very intrigued by @silasdavis's approach to use `MultipleOutputs` providing a more generic interface to write arbitrary outputs by key: https://gist.github.com/silasdavis/d1d1f1f7ab78249af462
However I have been unsuccessful porting it to work with Hadoop 1 mapred API.

Therefore I'm put forth this PR that achieves the simpler but highly requested goal of writing text files only.

### CODE REVIEW

**Comment by n-my** [comment]
Can't wait for that to be released :+1:

**Comment by silasdavis** [comment]
Let's not make the best the enemy of the good. I can base the more general approach off this work when I have time.

**Comment by davies** [comment]
@silasdavis What's the progress on your side?

**Comment by utkarsh2012** [comment]
@saurfang Do you plan to merge this or you are waiting for @silasdavis's changes?

**Comment by saurfang** [comment]
I myself definitely want to get this merged. That being said, this will require a spark committer to drive the process. If you feel strongly about this feature, voice your support on the JIRA. I can rebase this PR if there are interests in merging.

**Comment by davies** [comment]
@saurfang This could be done easily with DataFrame APIs:
```
val df = rdd.map(t => Row(gen_key(t), t)).toDF("key", "text")
df.write.partitionBy("key").text(path)
```

DataFrame APIs also support many other data type and file formats.

Would you mind close this PR and put this workaround in the JIRA?

**Comment by saurfang** [comment]
Thanks @davies. This looks to be a very reasonable workaround.

**Pull request closed without merging**
