### PR TITLE
SPARK-6085 Part. 2 Increase default value for memory overhead

### PR DESCRIPTION
**Pull request by jongyoul**
- fixed a description of spark.mesos.executor.memoryOverhead from 7% to 10%
- This is a second part of SPARK-6085

### CODE REVIEW

**Comment by jongyoul** [comment]
@srowen Review this PR, please. This is a second part of SPARK-6085 which you committed. I just fixed a small documentation, so I don't make another issue.

**Comment by srowen** [comment]
Yes this needs to be update. There are some small pre-existing problems with this text though, which should be fixed here too. 

MiB is a mebibyte, but the value is actually in MB, or megabytes. I imagine that a lot of code/text elsewhere maybe talks about MB when it means MiB, but here this should match Mesos docs which indicate that passing 384 will mean 384MB.

More importantly, I realized that the logic is slightly different here between Mesos and YARN. In YARN, the overhead is always completely overrideable by setting `spark.yarn.executor.memoryOverhead`. It merely defaults to the greater of 384, or 10% of the executor memory. In the Mesos `MemoryUtils`, yes, it's the max of 10% of executor memory, or `spark.mesos.memoryOverhead` which defaults to 384.

I think this is an unintentional difference that should be rectified? right now the caller has no way of overriding the 10% minimum, which doesn't seem right.

I'm OK to commit this (I can change "MiB") since it would correctly reflect the logic now, but I'd welcome it if you follow up by reviewing the argument above and look at changing `MemoryUtils` in a separate issue.

**Comment by jongyoul** [comment]
@srowen I'm sorry not for understanding your opinion fully - I'm not a native english -, do you mean that it's proper to use "MB" instead of "MiB"? I've found Mesos project used that "MB" has meant "MiB". And I'll follow up an unintentional difference in a separate issue, too.

**Comment by srowen** [comment]
Yes MB and MiB are different things. It looks like Mesos says it uses "MB" so I'd match that, I suppose. Are you saying that Mesos doc is wrong?

**Comment by jongyoul** [comment]
@srowen No, Mesos doc is not wrong, and I mean that Mesos also uses MB as same as MiB.

**Comment by srowen** [comment]
OK, I think this should be merged as-is now since it correctly describes the current behavior. You are welcome to open an issue that then changes that behavior to be consistent with YARN, which I imagine is what was intended.

**Pull request closed without merging**
