### PR TITLE
[SPARK-36009][GRAPHX] Add missing GraphX classes to registerKryoClasses util method

### PR DESCRIPTION
**Pull request by matthewrj**
### What changes were proposed in this pull request?
Add `ShippableVertexPartition` and `RoutingTablePartition` to the classes registered with Kryo in `GraphXUtils.registerKryoClasses`.

### Why are the changes needed?
`VertexRDDImpl` uses an `RDD[ShippableVertexPartition[VD]]` however, `GraphXUtils.registerKryoClasses` does not register `ShippableVertexPartition`. This means when running with `spark.kryo.registrationRequired` set to `true`, we get a "Class is not registered" exception. This is an issue as it prevents other unregistered classes from being discovered using `spark.kryo.registrationRequired` as the first unregistered class found halts the whole job. It also potentially decreases the serialised size of the RDD when using Kryo.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Tested manually by running with `spark.kryo.registrationRequired` set to `true` and verifying no "Class is not registered" exception was thrown.

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Thank you for making a PR, @matthewrj . Does your PR pass the test locally in your environment?

**Comment by matthewrj** [comment]
> Thank you for making a PR, @matthewrj . Does your PR pass the test locally in your environment?

Yes, it does now.

**Comment by dongjoon-hyun** [comment]
ok to test

**Comment by dongjoon-hyun** [comment]
BTW, I'm wondering if you have a comparison number before and after your PR. Do you see any noticeable performance gain with this PR?

**Comment by matthewrj** [comment]
No, I haven't done any performance tests. Like I said in the PR description, my motivation was to be able to turn on `spark.kryo.registrationRequired` and find any classes I hadn't registered. Since it would stop the job as soon as it got to `ShippableVertexPartition`, I need this to be registered so I can see if there are other classes my job tries to serialize after `ShippableVertexPartition`.

**Comment by dongjoon-hyun** [comment]
If your goal is the following, does this PR include all classes for enabling `spark.kryo.registrationRequired`? Otherwise, there is not much real benefit with this.
> my motivation was to be able to turn on spark.kryo.registrationRequired and find any classes I hadn't registered

**Comment by mridulm** [comment]
Agree with @dongjoon-hyun, can you try this locally and ensure you get the full set of classes required ?

**Comment by srowen** [comment]
(We'll want a JIRA for this too if it goes forward: https://spark.apache.org/contributing.html )

**Comment by maropu** [comment]
@matthewrj kingly ping; +1 for the @srowen comment. Could you file jira for this improvement?

**Comment by matthewrj** [comment]
Hi sorry for the delayed response. I've created a ticket here: https://issues.apache.org/jira/browse/SPARK-36009

I've tested this locally and I can run successfully with `spark.kryo.registrationRequired`. I have used these changes to debug my own classes not being registered.

**Comment by srowen** [comment]
Jenkins retest this please

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
