### PR TITLE
[SPARK-34343][SQL][TESTS] Add missing test for some non-array types in PostgreSQL

### PR DESCRIPTION
**Pull request by sarutak**
### What changes were proposed in this pull request?

This PR added tests for some non-array types in PostgreSQL.
PostgreSQL supports wide range of types (https://www.postgresql.org/docs/13/datatype.html) and `PostgresIntegrationSuite` contains tests for some types but ones for the following types are missing.

* bit varying
* point
* line
* lseg
* box
* path
* polygon
* circle
* pg_lsn
* macaddr
* macaddr8
* numeric
* pg_snapshot
* real
* time
* timestamp
* tsquery
* tsvector
* txid_snapshot
* xml

NOTE: Handling money types can be buggy so this PR doesn't add tests for those types.

### Why are the changes needed?

To ensure those types work with Spark well.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Extended `PostgresIntegrationSuite`.

### CODE REVIEW

**Comment by sarutak** [comment]
For reviews: As I mentioned in the description, handling money types can be buggy and I'll fix it in #31442 .
Also, arrays of some types are not supported so I'll fix the issue in #31419 .

**Review by srowen — APPROVED** [review]
Looks good if it passes.

**Comment by sarutak** [comment]
SPARK-34357 (#31473) changed the type-mapping of JDBC `time` from `Integer` to `Timestamp` so I've modified the test for `time` in this PR to follow the previous change.
I also confirmed the modified test passes.

**Review by maropu — APPROVED** [review]
okay, I've checked that `PostgresIntegrationSuite` passes.

**Comment by maropu** [comment]
Thanks! Merged to master.

**Pull request closed without merging**
