### PR TITLE
[DONT MERGE] Enabled `ImportOrder` check of Java code

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr enabled ImportOrder check of Java code

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass GA

### CODE REVIEW

**Comment by LuciferYang** [comment]
The example of following the `ImportOrder` check rule:

```java
import java.io.IOException;
import java.nio.ByteBuffer;
import java.util.Arrays;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;

import com.google.common.collect.ImmutableMap;
import com.google.common.collect.Sets;
import org.junit.Test;
import org.mockito.stubbing.Answer;
import org.mockito.stubbing.Stubber;

import org.apache.spark.network.buffer.ManagedBuffer;
import org.apache.spark.network.buffer.NioManagedBuffer;
import org.apache.spark.network.util.MapConfigProvider;
import org.apache.spark.network.util.TransportConf;

import static org.apache.spark.network.shuffle.RetryingBlockTransferor.BlockTransferStarter;
import static org.junit.Assert.*;
import static org.mockito.Mockito.*;
```

**Comment by srowen** [comment]
I think this is mostly too much noise to bother with. Most imports are nearly-correctly-ordered and it matters little anyway. If there is a weaker check we can enforce (e.g. are imports grouped, if not ordered, correctly) that might be OK to try to enforce

**Comment by LuciferYang** [comment]
Set `order` to `false` can ignore the order check

**Comment by LuciferYang** [comment]
@srowen for `static imports`, would you mind dividing them into separate groups?

**Comment by LuciferYang** [comment]
> So we can accept a weak rule similar to the following: imports are grouped and interior of each group can be disordered ?

If this, still 180 files need to be changed :(

**Comment by LuciferYang** [comment]
So should we remove this `TODO`, It seems unlikely to have a chance to finish it ...

**Comment by srowen** [comment]
We could, I also don't care much about the TODO statement either

**Comment by LuciferYang** [comment]
> We could, I also don't care much about the TODO statement either

ok

**Pull request closed without merging**
