### PR TITLE
[SPARK-8101] [CORE] Upgrade netty to avoid memory leak accord to netty #3837 issues

### PR DESCRIPTION
**Pull request by srowen**
Update to Netty 4.0.28-Final

### CODE REVIEW

**Comment by srowen** [comment]
Jenkins, retest this please

**Comment by srowen** [comment]
Jenkins, retest this please

**Comment by rxin** [comment]
Jenkins, retest this please.

**Comment by srowen** [comment]
https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/34458/console
Another fetch error

**Comment by srowen** [comment]
Jenkins, retest this please

**Pull request closed without merging**
