### PR TITLE
[SPARK-45052][SQL][PYTHON][CONNECT][3.5] Make function aliases output column name consistent with SQL

### PR DESCRIPTION
**Pull request by zhengruifeng**
### What changes were proposed in this pull request?
backport https://github.com/apache/spark/pull/42775 to 3.5

### Why are the changes needed?
to make `func(col)` consistent with `expr(func(col))`

### Does this PR introduce _any_ user-facing change?
yes

### How was this patch tested?
ci

### Was this patch authored or co-authored using generative AI tooling?
no

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]

**Comment by zhengruifeng** [comment]
merged to branch-3.5

**Comment by zhengruifeng** [comment]
cc @yaooqinn I found that the `dev/merge_spark_pr.py` doesn't close the PR targeting non-master branches.

**Comment by yaooqinn** [comment]
This may be an issue with GitHub. I confirmed that your commit message includes "Closes #XXX".

Seems the `default branch` is a requirement.

> The issue will be closed when you merge the commit into the default branch, but the pull request that contains the commit will not be listed as a linked pull request.

**Comment by zhengruifeng** [comment]
@yaooqinn thanks for the investigation.

**Pull request closed without merging**
