### PR TITLE
[SPARK-11579] [ML] avoid creating new optimizer in ANN

### PR DESCRIPTION
**Pull request by hhbyyh**
jira: https://issues.apache.org/jira/browse/SPARK-11579

This is a proposal based on some customer feedback. 
Currently method SGDOptimizer and LBFGSOptimizer in FeedForwardTrainer create new optimizer every time they got invoked, this is not quite intuitive since users think they are still using the existing optimizer when they write:

```
feedForwardTrainer
.SGDOptimizer
.setMiniBatchFraction(0.002)
```

yet it actually creates a new optimizer without other properties which were set previously.

### CODE REVIEW

**Comment by jkbradley** [comment]
@avulanov  Could you please take a look? Thanks!

**Comment by avulanov** [comment]
@jkbradley If we want to follow the logic "users think they are still using the existing optimizer when they access the optimizer", then there should be two private variables for each optimizer instead of one. The proposed fix creates a new optimizer if user switches from SGD to LBFGS and the mentioned logic breaks. 

By the way, `FeedForwardTrainer` is `ML` private, so it should not be used by users. In practice, the creation of new optimizer never happens because the public class `MultilayerPerceptronClassifier` uses LBFGS only.

**Comment by hhbyyh** [comment]
@avulanov Thanks for review. 
The only possible concern I got is LBFGSOptimizer/SGDOptimizer appears to be getter, yet they are setters. 

I sent an update which changes the function name only.

**Comment by jkbradley** [comment]
@avulanov Thanks that makes sense.

@hhbyyh I'd agree with not creating a new optimizer every time, if this were a public API.  Is there a real need for it to be public currently?

Eventually, it'd be nice to have it public and have it follow the same logic as GLM optimizers.  But perhaps we can skip this for now?

**Comment by hhbyyh** [comment]
OK. I'll close this. Thanks for helping review.

**Pull request closed without merging**
