### PR TITLE
[SPARK-19646][CORE][STREAMING] binaryRecords replicates records in scala API

### PR DESCRIPTION
**Pull request by srowen**
## What changes were proposed in this pull request?

Use `BytesWritable.copyBytes`, not `getBytes`, because `getBytes` returns the underlying array, which may be reused when repeated reads don't need a different size, as is the case with binaryRecords APIs

## How was this patch tested?

Existing tests

### CODE REVIEW

**Comment by hvanhovell** [comment]
LGTM - pending jenkins

**Comment by hvanhovell** [comment]
@srowen should we add a regression test? It seems weird that we didn't catch this in tests.

**Review by uncleGen — APPROVED** [review]

**Comment by srowen** [comment]
Agreed, I fixed the tests to actually fix this, and generally cleaned up the relevant test code

**Comment by srowen** [comment]
Merged to master/2.1/2.0 as it's a reasonably important bug

**Comment by srowen** [comment]
Oops, pick was clean into 2.1 but it actually resulted in an error: https://amplab.cs.berkeley.edu/jenkins/view/Spark%20QA%20Test%20(Dashboard)/job/spark-branch-2.1-test-sbt-hadoop-2.7/374/consoleFull

Fixing now ...

**Pull request closed without merging**
