### PR TITLE
WIP: [SPARK-27998] [SQL] Add support for double-quoted named expressions

### PR DESCRIPTION
**Pull request by andygrove**
### What changes were proposed in this pull request?

Spark SQL currently only supports backticks for identifiers. ANSI SQL allows double-quoted strings for identifiers.

This PR adds support for double-quoted identifiers for named expressions (column aliases) without changing the use of double-quoted strings as SQL strings in other contexts. Backticks are also still supported.

Specific changes:

- Split `STRING` lexer rule into `SINGLE_QUOTED_STRING` and `DOUBLE_QUOTED_STRING`
- Update most parser rules to allow `SINGLE_QUOTED_STRING` or `DOUBLE_QUOTED_STRING` instead of `STRING`
- Update parser rule for `namedExpression` to allow `quotedIdentifier` (backticks) or `DOUBLE_QUOTED_STRING`

### Why are the changes needed?

To allow ANSI SQL double-quoted identifiers to be used for column aliases.

### Does this PR introduce _any_ user-facing change?

Yes, it allows double quotes to be used as well as backticks for named expressions.

### How was this patch tested?

New UT added.

### CODE REVIEW

**Comment by srielau** [comment]
I think this this is worrysome for two reasons

1. It adds confusion between what is a string and what is an identifier.
2. It singles out a specific kind of an identifier (column) and a specific narrow kind of context (column aliasing in the select list).

I totally  for a switch that sets whether double quotes are used for identifiers or strings.
but it should be:

1. Pick one
2. Holistic

**Comment by andygrove** [comment]
> I think this this is worrysome for two reasons
> 
>     1. It adds confusion between what is a string and what is an identifier.
> 
>     2. It singles out a specific kind of an identifier (column) and a specific narrow kind of context (column aliasing in the select list).
> 
> 
> I'm totally for a switch that sets whether double quotes are used for identifiers or strings. but it should be:
> 
>     1. Pick one
> 
>     2. Holistic

My original PR was to change the meaning of double quotes to be identifiers instead of strings but the [feedback](https://github.com/apache/spark/pull/35853#issuecomment-1093676903) was that it was too late to make a change this large. However, maybe we can introduce a configuration option to determine how this is handled, as suggested [here](https://github.com/apache/spark/pull/35853#issuecomment-1095156190).

**Comment by runitao** [comment]
please retest

**Comment by srielau** [comment]
> > I think this this is worrysome for two reasons
> > ```
> > 1. It adds confusion between what is a string and what is an identifier.
> > 
> > 2. It singles out a specific kind of an identifier (column) and a specific narrow kind of context (column aliasing in the select list).
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I'm totally for a switch that sets whether double quotes are used for identifiers or strings. but it should be:
> > ```
> > 1. Pick one
> > 
> > 2. Holistic
> > ```
> 
> My original PR was to change the meaning of double quotes to be identifiers instead of strings but the [feedback](https://github.com/apache/spark/pull/35853#issuecomment-1093676903) was that it was too late to make a change this large. However, maybe we can introduce a configuration option to determine how this is handled, as suggested [here](https://github.com/apache/spark/pull/35853#issuecomment-1095156190).

I think a config would be appropriate.

**Pull request closed without merging**
