### PR TITLE
[SPARK-9409] [build] make-distribution.sh now copies any files in the conf directory.

### PR DESCRIPTION
**Pull request by deanwampler**
make-distribution.sh modified to copy all files in `conf` to the target archive, not just the `*.template` files. This makes it convenient to build an archive with custom property and configuration files. The change has no affect on the build unless a user explicit adds new files to the directory.

### CODE REVIEW

**Comment by srowen** [comment]
Are there any foreseeable drawbacks to this? stuff that might be in conf that might not be intended for a distro? CC @pwendell

**Comment by deanwampler** [comment]
Right now, there are only `*.template` files.

**Comment by pwendell** [comment]
I might slightly prefer to just allow users to specify files with something like `--conf X --conf Y` and then those files are put in the conf directory of the distribution. The issue with the proposed approach is (a) it sort of changes the nature of make-distribution, which to this point has assumed everything is computable from an unmodified spark source tree (b) it's a breaking change from earlier versions so could have minor unexpected annoyances for people.

In terms of having this feature at all vs not having it in the first place. It seems like the best user workaround without having this in the script is to just add a conf post-hoc, which could involve untarring and re-tarring, which is pretty cumbersome. So I do think it's good to come up with some solution that makes this easy for packagers to add a conf.

**Comment by deanwampler** [comment]
That would work. If a new script is created, it could also offer a hook for adding user libraries to the `CLASSPATH`, perhaps in a `lib/user` or `lib/site` directory. The run time scripts would need to add this directory to the `CLASSPATH`, too.

**Comment by JoshRosen** [comment]
@deanwampler, given that it seems like we've decided to not merge this PR as-is, would you mind closing it for now? You can always re-open this PR or submit a new one if you want to pursue the approach of adding a new configuration for this. Thanks!

**Pull request closed without merging**
