### PR TITLE
Adding zipPartitions to PySpark

### PR DESCRIPTION
**Pull request by jegonzal**
The following adds support for `zipPartitions` to PySpark.  This is accomplished by modifying the PySpark `worker` (in both daemon and non-deamon mode) to open a second socket back to the Spark process.  The second socket is used to send tuple from the second iterator in `zipPartitions` enabling the user defined function to pull tuples from both iterators at different rates without requiring a back-and-forth protocol over the primary socket.  The single socket protocol design was considered but creates issues with the built-in serializers and would require much larger changes.  The second socket is always created at the launch of the worker process and is simply ignored if it is not needed.

### CODE REVIEW

**Comment by jegonzal** [comment]
@davies and @JoshRosen let me know what you think of this design.

**Comment by jegonzal** [comment]
retest this please

**Comment by jegonzal** [comment]
retest this please

**Comment by jegonzal** [comment]
retest this please

**Comment by jegonzal** [comment]
retest this please

**Comment by jegonzal** [comment]
@davies and @JoshRosen I have finished a working prototype that passes the tests.  I would be interested in your thoughts.

**Comment by davies** [comment]
@jegonzal Thanks for working on this, could you create a JIRA to track it?

Given the fact that Python is much slower than Scala/Java, I want to suggest another approach for zipPartition() for Python, dump the two partitions into disk then read back in Python, it will looks like this:

```
def zipPartitions(f, *rdds):
     jzipped = dumpPartitionsIntoDisk([rdd._jrdd for rdd in rdds]):
     # each partition of zipped is a list of path of dumped files
     zipped = RDD(jzipped, UTF8Serializer())
     def readPartition(iter):
          paths = list(iter):
          iters = [rdds[i]._deserializer.load_stream(open(p, ‘rb’))   for i, p in enumerate(paths)]
          return f(*iters)
     return zipped.mapPartition(readPartition)
```

`dumpPartitionsIntoDisk` should be implemented in Java/Scala, zip all the Java RDD together, then dump each stream within a partition into a file in disk, return the paths.

**Comment by jegonzal** [comment]
@davies thanks for taking look!  I will open a JIRA issue later today.

With respect to the disk based design, I had considered it but it has a few limitations.  First it breaks the lazy evaluation model which (while not critical) was something I wanted to avoid.  Second, and perhaps more importantly, I wanted to avoid writing both relations completely to disk since it is possible that one may only need to be partially processed or require subsequent disk processing.  I should add that the Python performance is actually pretty reasonable :-) for basic data-processing tasks so I wanted a design that would retain the current level of performance.

**Comment by davies** [comment]
The one socket for PythonRDD is already pretty complicated (considering how propagate exception and how to re-use it), adding another will make it even complicated (two socket in different status), so I'd try to avoid that. The new introduced and not-common-used zipPartititon() should not brings bugs for existing workload. I'd -1 for current approach, cc @JoshRosen .

Another try could be that only open second socket (not re-used) when zipPartition() is called, this may reduce the risk for existing workload.

**Comment by rxin** [comment]
@jegonzal as discussed offline, let's just implement this in your private fork for now. Do you mind closing the pull request? Thanks.

**Pull request closed without merging**
