### PR TITLE
[SPARK-45104][UI] Upgrade `graphlib-dot.min.js` to 1.0.2

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

This PR update the `graphlib-dot` library, https://github.com/dagrejs/graphlib-dot/compare/v0.5.2...v1.0.2, this library is used to read and parse dot files to graphics.

### Why are the changes needed?

Update UI js libraries

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

build and verify locally

image

### Was this patch authored or co-authored using generative AI tooling?

no

### CODE REVIEW

**Review by srowen — APPROVED** [review]

**Review by dongjoon-hyun — COMMENTED** [review]
Just a question. How can I check if the old file is 0.6.4, @yaooqinn ? I'm a little confused because it's v0.5.2 according to the head of the delete file.
```
/*v0.5.2*/(function...
```

**Comment by dongjoon-hyun** [comment]
The PR description also says `v0.5.2`. Maybe, the title has a typo, `0.6.4` instead of `0.5.2`?
> This PR update the graphlib-dot library, https://github.com/dagrejs/graphlib-dot/compare/v0.5.2...v1.0.2, this library is used to read and parse dot files to graphics.

**Comment by dongjoon-hyun** [comment]
If needed, please change the PR title and JIRA title together.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM (except one question about the PR title)

**Comment by dongjoon-hyun** [comment]
I removed `from 0.6.4` from the PR title and JIRA title.

Merged to master for Apache Spark 4.0.0. Thank you, @yaooqinn and all.

**Comment by yaooqinn** [comment]
You are right，thank you @dongjoon-hyun for fixing the title. I didn't seem to be sober after a small bicycle accident yesterday morning:)

**Pull request closed without merging**
