### PR TITLE
[SPARK-23192] [SQL] Keep the Hint after Using Cached Data

### PR DESCRIPTION
**Pull request by gatorsmile**
## What changes were proposed in this pull request?

The hint of the plan segment is lost, when the plan segment is replaced by the cached data.

```Scala
      val df1 = spark.createDataFrame(Seq((1, "4"), (2, "2"))).toDF("key", "value")
      val df2 = spark.createDataFrame(Seq((1, "1"), (2, "2"))).toDF("key", "value")
      df2.cache()
      val df3 = df1.join(broadcast(df2), Seq("key"), "inner")
```

This PR is to fix it.

## How was this patch tested?
Added a test

### CODE REVIEW

**Comment by gatorsmile** [comment]
cc @cloud-fan @zsxwing @sameeragarwal

**Comment by sameeragarwal** [comment]
LGTM

**Review by jiangxb1987 — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by jiangxb1987** [comment]
retest this please

**Comment by gatorsmile** [comment]
Since the last change is just to change the test case name, I merge this PR.

**Comment by gatorsmile** [comment]
Thanks! Merged to master/2.3

**Pull request closed without merging**
