### PR TITLE
[SPARK-50515][CORE] Add read-only interface to `SparkConf`

### PR DESCRIPTION
**Pull request by pmenon**
### What changes were proposed in this pull request?
This PR lifts read-only APIs of `SparkConf` into a new `ReadOnlySparkConf`. `SparkContext` now exposes a new read-only API to the conf through `SparkContext.getReadOnlyConf`, which can be used by clients outside the `spark` package if they require only read-only access. The new API avoids copying the entire (potentially large) conf as in `SparkContext.getConf`. This PR also changes all appropriate call sites to use the new API.

### Why are the changes needed?
Cloning the entire conf adds unnecessary CPU overhead due to copying, and GC overhead due to cleanup. Both affect tail latencies on certain workloads.

### Does this PR introduce _any_ user-facing change?
It adds a new public API `SparkContext.getReadOnlyConf`.

### How was this patch tested?
It is a refactoring PR, so we rely on existing tests.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Review by dongjoon-hyun — DISMISSED** [review]
Thank you for making a PR, @pmenon . Please file a JIRA issue.

**Comment by dongjoon-hyun** [comment]
I converted this to `Draft` due to the `Conflicting files`. You can convert this back to a normal PR when the PR is ready.

Screenshot 2024-12-06 at 13 06 33

**Comment by LuciferYang** [comment]
- https://github.com/pmenon/spark/actions/runs/12207099390/job/34057905545

image

**Review by cloud-fan — APPROVED** [review]

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Pull request closed without merging**
