### PR TITLE
[SPARK-17947] [SQL] Add Doc and Comment about spark.sql.debug

### PR DESCRIPTION
**Pull request by gatorsmile**
### What changes were proposed in this pull request?

Just document the impact of `spark.sql.debug`:

When enabling the debug, Spark SQL internal table properties are not filtered out; however, some related DDL commands (e.g., Analyze Table and CREATE TABLE LIKE) might not work properly.
### How was this patch tested?

N/A

### CODE REVIEW

**Comment by rxin** [comment]
Why do they not work properly?

**Comment by gatorsmile** [comment]
You can see the failed test cases in the PR: https://github.com/apache/spark/pull/15478

`ANALYZE TABLE` will fail due to the [checking](https://github.com/apache/spark/blob/6ce1b675ee9fc9a6034439c3ca00441f9f172f84/sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveExternalCatalog.scala#L111-L115
) when we try to alter the table properties. 

`SHOW CREATE TABLE` also outputs the table properties that should not be part of the output CREAT TABLE statement.

`CREATE TABLE LIKE` always excludes all the table properties of the source table. However, we might make a change in this part. This is still waiting for your input in another PR. See the [discussion](https://github.com/apache/spark/pull/14531#issuecomment-252147424)

**Comment by cloud-fan** [comment]
@rxin because we are assuming that all the hive hacks are isolated inside `HiveExternalCatalog`, but the debug mode will break it and spread the hive metastore specific table properties outside of `HiveExternalCatalog`. Then some commands like `SHOW CREATE TABLE`, `ALTER TABLE` will be broken, but should be ok as it's a "debug" mode anyway.

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Pull request closed without merging**
