### PR TITLE
[SPARK-28466][SQL] fix sts FileSystem closed error when to call Hive.moveFile

### PR DESCRIPTION
**Pull request by AngersZhuuuu**
## What changes were proposed in this pull request?

When we close a session of STS, if this session has done some SQL about insert, then other session do CTAS/INSERT and trigger Hive.moveFile, DFSClient will do checkOpen and throw java.io.IOException: Filesystem closed.

**Root cause** :
When we first execut SQL like CTAS/INSERT,  it will call Hive.moveFile, during this method, it will initialize this field SessionState.hdfsEncryptionShim , when initialize this field, it will initialize a FS.
image

But this FS is under current HiveSessionImpleWithUgi.sessionUgi, so when we close this session, it will call `FileSystem.closeForUgi()`, above FileSystem will be closed, then during other session execute SQL like CTAS/INSERT,  such error will happen since FS has been close. 

Some one may be confused why HiveServer2 won't appear this problem : 

- In HiveServer2, each session has it's own SessionState, so close current session's FS is ok.
- In SparkThriftServer, all session interact with hive through one HiveClientImpl, it has only one SessionState, when we call method with HiveClientImpl, it will call **withHiveState** first to set HiveClientImpl's sessionState to current Thread.

## How was this patch tested?

manual tested

### CODE REVIEW

**Comment by AngersZhuuuu** [comment]
Gental ping  @Deegue  @xianyinxin @wangyum @jerryshao

**Comment by AngersZhuuuu** [comment]
@jerryshao @wangyum 
How about make HiveClientImple's sessionState to be ThreadLocal? since multi thread call HiveClientImpl 's method  situation  only happens on SparkThirftServer or other code written by the user with executing SQL concurrently

**Review by srowen — COMMENTED** [review]
Yikes, this looks complicated. Is there any other simpler fix if this is meant to be a quick follow up or was this a separate existing issue?

**Comment by AngersZhuuuu** [comment]
> Yikes, this looks complicated. Is there any other simpler fix if this is meant to be a quick follow up or was this a separate existing issue?

Since about HDFS Encryption, code in  each version of hive is different, in hive v1.1/v1.2/v1.3/v2.0/v2.0   hdfsEncryptionShim will be initialized on one FS, then above error will  happen,  in v2.2/v2.3/v3.0, hdfsEncryptionShim's API has changed a lot.  It's hard to change hive code, and many user may use their own hive version jars.

**Comment by Deegue** [comment]
Hi @AngersZhuuuu , is this similar to [[SPARK-21067]](https://issues.apache.org/jira/browse/SPARK-21067)?

**Comment by AngersZhuuuu** [comment]
> Hi @AngersZhuuuu , is this similar to [[SPARK-21067]](https://issues.apache.org/jira/browse/SPARK-21067)?

Yes, in this pr's description, youc an know the root cause about that error. But my method is not good enough. 
If you just use Hive1.2.1  ， below PR is ok https://github.com/apache/spark/pull/25197

**Comment by HyukjinKwon** [comment]
Does that mean if we set `fs.hdfs.impl.disable.cache=true`, then it work fine?

**Comment by srowen** [comment]
Are you saying this only affects Hive 1, or only Hive 2? I wasn't clear from the comment above pointing to https://github.com/apache/spark/pull/25197

**Comment by AngersZhuuuu** [comment]
> Does that mean if we set `fs.hdfs.impl.disable.cache=true`, then it work fine as a workaround?

will work

**Comment by AngersZhuuuu** [comment]
> Are you saying this only affects Hive 1, or only Hive 2? I wasn't clear from the comment above pointing to #25197

Since for hive version higher than 2.2, getHdfsEncryptionShim()  method changed,  it will create map for FS -> HdfsEncryptionShim, so pr #25179  won't work fine for all situation. since his method only initial current FS. if if there is a situation for cross cluster, it won't work well.

**Comment by AngersZhuuuu** [comment]
> Are you saying this only affects Hive 1, or only Hive 2? I wasn't clear from the comment above pointing to #25197

My method is also not good enough, close it.

**Comment by felixcheung** [comment]
We still need a fix for this issue, I think?

**Comment by AngersZhuuuu** [comment]
> We still need a fix for this issue, I think?

Yeah, still need, since config `fs.*.impl.disable.cache`=true is not the best ideal. 
But I haven't find a better way for hive version higher then 2.2.

**Pull request closed without merging**
