### PR TITLE
[SPARK-38085][SQL][FOLLOWUP] Do not fail too early for DeleteFromTable

### PR DESCRIPTION
**Pull request by cloud-fan**
### What changes were proposed in this pull request?

`DeleteFromTable` has been in Spark for a long time and there are existing Spark extensions to compile `DeleteFromTable` to physical plans. However, the new analyzer rule `RewriteDeleteFromTable` fails very early if the v2 table does not support delete. This breaks certain Spark extensions which can still execute `DeleteFromTable` for certain v2 tables.

This PR simply removes the error throwing in `RewriteDeleteFromTable`. It's a safe change because:
1. the new delete-related rules only match v2 table with `SupportsRowLevelOperations`, so won't be affected by this change
2. the planner rule will fail eventually if the v2 table doesn't support deletion. Spark eagerly executes commands so Spark users can still see this error immediately.

### Why are the changes needed?

To not break existing Spark extesions.

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

existing tests

### CODE REVIEW

**Comment by cloud-fan** [comment]
@aokolnychyi @viirya @dongjoon-hyun

**Comment by viirya** [comment]
It looks good to me. Just a bit confused by:

> However, the new analyzer rule RewriteDeleteFromTable fails very early if the v2 table does not support delete. This breaks certain Spark extensions which can still execute DeleteFromTable for certain v2 tables.

So, `RewriteDeleteFromTable` fails if the v2 table does not support delete. Why Spark extensions still can execute `DeleteFromTable` for them, if they don't support?

**Comment by cloud-fan** [comment]
When `DeleteFromTable`  was added, there is no row-based DS v2 delete API, so the spark extension just match `DeleteFromTable` with certain kinds of v2 tables. "does not support delete" means does not use DS v2 API to indicate the table supports deletion.

**Review by viirya — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
Thank you, @cloud-fan . +1, LGTM.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master and branch-3.3.

**Comment by aokolnychyi** [comment]
LGTM too.

**Pull request closed without merging**
