### PR TITLE
[SPARK-16259] [PYSPARK] cleanup options in DataFrame read/write API

### PR DESCRIPTION
**Pull request by davies**
## What changes were proposed in this pull request?

There are some duplicated code for options in DataFrame reader/writer API, this PR clean them up, it also fix a bug for `escapeQuotes` of csv().
## How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by davies** [comment]
cc @rxin

**Comment by shaneknapp** [comment]
jenkins, test this please

**Comment by felixcheung** [comment]
looks good!

**Comment by rxin** [comment]
LGTM - merging in master/2.0. Thanks!

**Comment by zsxwing** [comment]
@rxin why don't we merge this one to 2.0?

**Comment by rxin** [comment]
Feel free to do it - but please take another careful look before you cherry pick.

**Comment by zsxwing** [comment]
Merged to 2.0 as well.

**Pull request closed without merging**
