### PR TITLE
[SPARK-44841][FOLLOWUP] Add migration guide for the behavior change

### PR DESCRIPTION
**Pull request by itholic**
### What changes were proposed in this pull request?

This PR followups for https://github.com/apache/spark/pull/42525.

### Why are the changes needed?

To fill the missing migration guide for the behavior change.

### Does this PR introduce _any_ user-facing change?

No, this is migration guide update.

### How was this patch tested?

The existing CI should pass.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by bjornjorgensen** [comment]
Hi, can I change this to 
In Spark 4.0, when using the ``value_counts`` function from the pandas API on Spark, the resulting column name for all objects is set to ``'count'``. If ``normalize=True`` is passed, it will be set to ``'proportion'``. Additionally, the index will be named after the original object.
If yes, I can open a followup. 

image

**Comment by HyukjinKwon** [comment]
WDYT @itholic ^

**Comment by itholic** [comment]
Yeah, at least we have to fix the typo "propotion" to "proportion". Otherwise I don't think it's absolutely necessary, but please feel free to made a change. I have no strong opinion unless it doesn't include the wrong information.

Thanks for catching the typo, @bjornjorgensen !

**Pull request closed without merging**
