### PR TITLE
[SPARK-37941][SQL] Use error classes in the compilation errors of casting

### PR DESCRIPTION
**Pull request by ivoson**
### What changes were proposed in this pull request?
Migrate the following errors in QueryCompilationErrors onto use error classes:
upCastFailureError
unsupportedAbstractDataTypeForUpCastError
cannotUpCastAsAttributeError

### Why are the changes needed?
Porting casting errors to new error framework.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Existing UT.

### CODE REVIEW

**Comment by ivoson** [comment]
cc @MaxGekk

Since there are some existing test cases in [EncoderResolutionSuite](https://github.com/apache/spark/blob/v3.2.0/sql/catalyst/src/test/scala/org/apache/spark/sql/catalyst/encoders/EncoderResolutionSuite.scala), I am wondering whether we would like to move all compilation error cases to one test Suite. If we do that, the test file could be pretty big.

**Comment by MaxGekk** [comment]
> I am wondering whether we would like to move all compilation error cases to one test Suite.

We should add a test per every error class.

> If we do that, the test file could be pretty big.

Need to try to reduce the number of error classes. For example, https://github.com/apache/spark/pull/35272

**Comment by ivoson** [comment]
Thanks @MaxGekk . Will add the test case.

**Comment by ivoson** [comment]
Closing and open another PR https://github.com/apache/spark/pull/35366

**Pull request closed without merging**
