### PR TITLE
[SPARK-34855][CORE] Avoid local lazy variable in SparkContext.getCallSite

### PR DESCRIPTION
**Pull request by viirya**
### What changes were proposed in this pull request?

`SparkContext.getCallSite` uses local lazy variable. In Scala 2.11, local lazy val requires synchronization so for large number of job submissions in the same context, it will be a bottleneck. This only for branch-2.4 as we drop Scala 2.11 support at SPARK-26132.

### Why are the changes needed?

To avoid possible bottleneck for large number of job submissions in the same context.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by viirya** [comment]
cc @HyukjinKwon @srowen @lxian

**Review by HyukjinKwon — APPROVED** [review]
LGTM if tests pass

**Comment by HyukjinKwon** [comment]
The test failures is from https://github.com/apache/spark/commit/102b7239faf481958e5771064008e930237ee597 I reverted.

**Comment by HyukjinKwon** [comment]
I manually rebased

**Comment by viirya** [comment]
Thanks @HyukjinKwon

**Comment by HyukjinKwon** [comment]
Merged to branch-2.4.

**Comment by mridulm** [comment]
Late LGTM, nice fix @lxian, @viirya !

**Pull request closed without merging**
