### PR TITLE
[SPARK-27412][Core][WIP]Add a new shuffle manager: PmemShuffleManager

### PR DESCRIPTION
**Pull request by xuechendi**
PmemShuffleManager is used to write/read shuffle data and external sorter spilled data to Persistent Memory Device, and leverage PMDK to fully drive PMem device and retrieve exellent bandwidth and latency.
https://issues.apache.org/jira/browse/SPARK-27412

Signed-off-by: Chendi Xue <chendi.xue@intel.com>

## What changes were proposed in this pull request?

No codes change in current spark, while add a new shuffle manager with a bunch of new files.

## How was this patch tested?

This patch passed functional test, running spark on yarn with hdfs as back-end and performed terasort, repartition and random forest tests.

Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Review by attilapiros — COMMENTED** [review]
I have not read your PR through but l would have some questions:

1) As this was done almost no existing code change (except adding sqlite-jdbc as dependency) why would you like to add it to Spark directly I mean have you considered adding it as an external package/plugin (https://spark-packages.org)?

2) The building of the C++ code is not integrated at all (best would be avoided if it is possible maybe by creating a separate artifact which released separately)?

3) Its testing is not solved at all: I would expect some existing shuffle manger tests to switch to this PmemShuffleManager and run the tests besides that as well

**Comment by attilapiros** [comment]
Yes, I have seen the design doc. 

NIT: In the PR title you should use [Core] instead of [Shuffle]. 
That is a category which used on the Spark PR UI: https://spark-prs.appspot.com/.

**Comment by xuechendi** [comment]
@attilapiros , I see, I have changed it to core.

**Comment by xuechendi** [comment]
@srowen , I see, I will make native codes as an external package.

**Pull request closed without merging**
