### PR TITLE
[SPARK-44594][SS] Remove redundant method parameter in kafka connector

### PR DESCRIPTION
**Pull request by zhaomin1423**
### What changes were proposed in this pull request?

There are have redundant parameters in org.apache.spark.sql.kafka010.KafkaWriter#validateQuery and org.apache.spark.sql.kafka010.KafkaWriter#write, can remove them.
### Why are the changes needed?

They are not used, remove them to make the code more concise.

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

Existing can test it.

### CODE REVIEW

**Comment by zhaomin1423** [comment]
After run ./dev/scalafmt, some unmodified code is formatted.

**Comment by HyukjinKwon** [comment]
cc @HeartSaVioR FYI

**Comment by LuciferYang** [comment]
> After run ./dev/scalafmt, some unmodified code is formatted.

Please don't do this, scalafmt is only used to format the `connect` module

**Comment by LuciferYang** [comment]
@zhaomin1423 Sorry for the confusion, to be precise, only the `connect` modules needs to be forced to execute `scalafmt`, for other modules, we should avoid making unrelated modifications to keep the changes as minimal as possible.

**Comment by LuciferYang** [comment]
On the other hand, could you file a new JIRA for this pr?

**Comment by zhaomin1423** [comment]
> @zhaomin1423 Sorry for the confusion, to be precise, only the `connect` modules needs to be forced to execute `scalafmt`, for other modules, we should avoid making unrelated modifications to keep the changes as minimal as possible.

Thanks for the explanation, I'm a newcomer. Do we need to update the description of the documentation to avoid misunderstanding for newcomers.

**Comment by zhaomin1423** [comment]
> On the other hand, could you file a new JIRA for this pr?

Yes, I don't have a permission, have already applied, waiting for approval.

**Comment by zhaomin1423** [comment]
> > On the other hand, could you file a new JIRA for this pr?
> 
> Yes, I don't have a permission, have already applied, waiting for approval.

I file and edit the title, PTAL.

**Comment by LuciferYang** [comment]
Although these two APIs are limited to the `kafka010` package, I also searched GitHub and it seems that no other project uses these two APIs. Perhaps modifying them is safe, but it is best to follow @HeartSaVioR 's decision

**Comment by PhilDakin** [comment]
@LuciferYang what decision are you referring to here? I was unable to find anything in the mail list.

Should this PR + corresponding Jira be closed?

**Review by LuciferYang — APPROVED** [review]
+1, LGTM

**Review by HeartSaVioR — APPROVED** [review]
+1
This is not a user facing change so doesn't need to be future-proofing. Whenever we want to verify the query with params we can pass the param again.

**Comment by LuciferYang** [comment]
Merged into master for Spark 4.0. Thanks @zhaomin1423 @HeartSaVioR and @HyukjinKwon

**Comment by zhaomin1423** [comment]
> Merged into master for Spark 4.0. Thanks @zhaomin1423 @HeartSaVioR and @HyukjinKwon

Thanks for your help

**Pull request closed without merging**
