### PR TITLE
[SPARK-8783] [SQL] CTAS with WITH clause does not work

### PR DESCRIPTION
**Pull request by sirpkt**
Currently, CTESubstitution only handles the case that WITH is on the top of the plan.
I think it SHOULD handle the case that WITH is child of CTAS.
This patch simply changes 'match' to 'transform' for recursive search of WITH in the plan.

### CODE REVIEW

**Comment by JoshRosen** [comment]
Jenkins, this is ok to test.

**Comment by sarutak** [comment]
ok to test.

**Comment by JoshRosen** [comment]
Jenkins, retest this please.

**Comment by marmbrus** [comment]
Thanks!  Merging to master.

**Pull request closed without merging**
