### PR TITLE
[SPARK-44133][PYTHON] Upgrade MyPy from 0.920 to 0.982

### PR DESCRIPTION
**Pull request by HyukjinKwon**
### What changes were proposed in this pull request?

This PR upgrade MyPy version from 0.920 to 0.982.

### Why are the changes needed?

To detect type related changes better by static analysys.

### Does this PR introduce _any_ user-facing change?

No, dev-only.

### How was this patch tested?

```bash
./dev/linter-python
```

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @zhengruifeng

**Review by zhengruifeng — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by HyukjinKwon** [comment]
Thanks!

**Comment by LuciferYang** [comment]
@HyukjinKwon Is it possible the `./dev/lint-python` check failure of branches-3.3 and branch-3.4 is related to this upgrade?
They started failing 3 weeks ago.

- branch-3.3 like https://github.com/apache/spark/actions/runs/5342554872/jobs/9684543933

image


- branch-3.4 like https://github.com/apache/spark/actions/runs/5343637126/jobs/9687046955

image

**Comment by HyukjinKwon** [comment]
Ahh ..

**Comment by HyukjinKwon** [comment]
Or simply skip that linter .. sigh..

**Pull request closed without merging**
