### PR TITLE
[SPARK-43246][BUILD] Ignore `privateClasses` and `privateMembers` from connect mima check as default

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
The main change of this pr as follows:

1. Like `dev/mima`, use `GenerateMIMAIgnore` to generate `.generated-mima-member-excludes` and `.generated-mima-class-excludes`
2. Make `CheckConnectJvmClientCompatibility` use `.generated-mima-member-excludes` and `.generated-mima-class-excludes` as default `ProblemFilters` to excludes `privateClasses` and `privateMembers` from mima check result.
3. Ignore the `ProblemFilters` add by https://github.com/apache/spark/pull/40898

### Why are the changes needed?
Ignore privateClasses and privateMembers from connect mima check as default

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
`CheckConnectJvmClientCompatibility` should pass

### CODE REVIEW

**Comment by hvanhovell** [comment]
@LuciferYang can you update.

Overall this looks good to me. Can you make sure we don't exclude too many cases?

**Comment by LuciferYang** [comment]
```
Error: Exception in thread "main" java.lang.IllegalArgumentException: Unsupported class file major version 61
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:195)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:176)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:162)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:283)
	at org.clapper.classutil.asm.ClassFile$.load(ClassFinderImpl.scala:222)
	at org.clapper.classutil.ClassFinder.classData(ClassFinder.scala:404)
	at org.clapper.classutil.ClassFinder.$anonfun$processOpenZip$2(ClassFinder.scala:359)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
	at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:486)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:492)
	at scala.collection.Iterator.toStream(Iterator.scala:1417)
	at scala.collection.Iterator.toStream$(Iterator.scala:1416)
	at scala.collection.AbstractIterator.toStream(Iterator.scala:1431)
	at scala.collection.Iterator.$anonfun$toStream$1(Iterator.scala:1417)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1173)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1163)
	at scala.collection.immutable.Stream.$anonfun$$plus$plus$1(Stream.scala:372)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1173)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1163)
	at scala.collection.immutable.Stream.$anonfun$$plus$plus$1(Stream.scala:372)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1173)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1163)
	at scala.collection.immutable.Stream.$anonfun$map$1(Stream.scala:418)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1173)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1163)
	at scala.collection.immutable.Stream.filterImpl(Stream.scala:506)
	at scala.collection.immutable.Stream$.$anonfun$filteredTail$1(Stream.scala:1260)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1173)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1163)
	at scala.collection.immutable.Stream$.$anonfun$filteredTail$1(Stream.scala:1260)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1173)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1163)
	at scala.collection.generic.Growable.loop$1(Growable.scala:57)
	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:61)
	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
	at scala.collection.immutable.Set$SetBuilderImpl.$plus$plus$eq(Set.scala:381)
	at scala.collection.immutable.Set$SetBuilderImpl.$plus$plus$eq(Set.scala:329)
	at scala.collection.TraversableLike.to(TraversableLike.scala:786)
	at scala.collection.TraversableLike.to$(TraversableLike.scala:783)
	at scala.collection.AbstractTraversable.to(Traversable.scala:108)
	at scala.collection.TraversableOnce.toSet(TraversableOnce.scala:360)
	at scala.collection.TraversableOnce.toSet$(TraversableOnce.scala:360)
	at scala.collection.AbstractTraversable.toSet(Traversable.scala:108)
	at org.apache.spark.tools.GenerateMIMAIgnore$.getClasses(GenerateMIMAIgnore.scala:[15](https://github.com/LuciferYang/spark/actions/runs/4998621687/jobs/8954833741#step:14:16)6)
	at org.apache.spark.tools.GenerateMIMAIgnore$.privateWithin(GenerateMIMAIgnore.scala:57)
	at org.apache.spark.tools.GenerateMIMAIgnore$.main(GenerateMIMAIgnore.scala:1[22](https://github.com/LuciferYang/spark/actions/runs/4998621687/jobs/8954833741#step:14:23))
	at org.apache.spark.tools.GenerateMIMAIgnore.main(GenerateMIMAIgnore.scala)
Error: Process completed with exit code 1.
```

After rebase the code, the `connect-jvm-client-mima-check` will run failed as above, it seems that master branch has a dependency compiled by Java 17, let me investigate first.

**Comment by LuciferYang** [comment]
> ```
> Error: Exception in thread "main" java.lang.IllegalArgumentException: Unsupported class file major version 61
> 	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:195)
> 	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:176)
> 	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:162)
> 	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:283)
> 	at org.clapper.classutil.asm.ClassFile$.load(ClassFinderImpl.scala:222)
> 	at org.clapper.classutil.ClassFinder.classData(ClassFinder.scala:404)
> 	at org.clapper.classutil.ClassFinder.$anonfun$processOpenZip$2(ClassFinder.scala:359)
> 	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
> 	at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:486)
> 	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:492)
> 	at scala.collection.Iterator.toStream(Iterator.scala:1417)
> 	at scala.collection.Iterator.toStream$(Iterator.scala:1416)
> 	at scala.collection.AbstractIterator.toStream(Iterator.scala:1431)
> 	at scala.collection.Iterator.$anonfun$toStream$1(Iterator.scala:1417)
> 	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1173)
> 	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1163)
> 	at scala.collection.immutable.Stream.$anonfun$$plus$plus$1(Stream.scala:372)
> 	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1173)
> 	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1163)
> 	at scala.collection.immutable.Stream.$anonfun$$plus$plus$1(Stream.scala:372)
> 	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1173)
> 	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1163)
> 	at scala.collection.immutable.Stream.$anonfun$map$1(Stream.scala:418)
> 	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1173)
> 	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1163)
> 	at scala.collection.immutable.Stream.filterImpl(Stream.scala:506)
> 	at scala.collection.immutable.Stream$.$anonfun$filteredTail$1(Stream.scala:1260)
> 	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1173)
> 	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1163)
> 	at scala.collection.immutable.Stream$.$anonfun$filteredTail$1(Stream.scala:1260)
> 	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1173)
> 	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1163)
> 	at scala.collection.generic.Growable.loop$1(Growable.scala:57)
> 	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:61)
> 	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
> 	at scala.collection.immutable.Set$SetBuilderImpl.$plus$plus$eq(Set.scala:381)
> 	at scala.collection.immutable.Set$SetBuilderImpl.$plus$plus$eq(Set.scala:329)
> 	at scala.collection.TraversableLike.to(TraversableLike.scala:786)
> 	at scala.collection.TraversableLike.to$(TraversableLike.scala:783)
> 	at scala.collection.AbstractTraversable.to(Traversable.scala:108)
> 	at scala.collection.TraversableOnce.toSet(TraversableOnce.scala:360)
> 	at scala.collection.TraversableOnce.toSet$(TraversableOnce.scala:360)
> 	at scala.collection.AbstractTraversable.toSet(Traversable.scala:108)
> 	at org.apache.spark.tools.GenerateMIMAIgnore$.getClasses(GenerateMIMAIgnore.scala:[15](https://github.com/LuciferYang/spark/actions/runs/4998621687/jobs/8954833741#step:14:16)6)
> 	at org.apache.spark.tools.GenerateMIMAIgnore$.privateWithin(GenerateMIMAIgnore.scala:57)
> 	at org.apache.spark.tools.GenerateMIMAIgnore$.main(GenerateMIMAIgnore.scala:1[22](https://github.com/LuciferYang/spark/actions/runs/4998621687/jobs/8954833741#step:14:23))
> 	at org.apache.spark.tools.GenerateMIMAIgnore.main(GenerateMIMAIgnore.scala)
> Error: Process completed with exit code 1.
> ```
> 
> After rebase the code, the `connect-jvm-client-mima-check` will run failed as above, it seems that master branch has a dependency compiled by Java 17, let me investigate first.

change of [9620361](https://github.com/apache/spark/pull/40925/commits/9620361a677013725befabaa262603f7a450ff32) will fix this issue, I will make a separate pr to upgrade the asm version of tools module, submitted just to verify that `connect-jvm-client-mima-check` can execute successfully with this one

**Comment by LuciferYang** [comment]
> Can you make sure we don't exclude too many cases?

Will double check this later

**Comment by LuciferYang** [comment]
@hvanhovell 

I think there is a scenario here that we need to clarify:

- Firstly, there may be the following definitions in the sql module

```scala
package org.apache.spark.sql

class ClassA {
  def functionA(): DataFrame = ...

  private[sql] def functionA(): DataFrame = ...
}

```

There are two functions with the same name `functionA` in ClassA and one is defined as `private[sql]`.


- Afterwards, we may define the corresponding ClassA in the connect client module as follows:


```scala
package org.apache.spark.sql

class ClassA {

}

```

Then, if we run the mima check, the check results will pass even if there is no definition related to `functionA` in ClassA of connect client module, this because `private[sql] def functionA` is in `.generated-mima-member-excludes` as default , and this will be equivalent to we manually adding `ProblemFilters.exclude[Problem]("org.apache.spark.sql.ClassA.functionA")`.

In this scenario, we need to ensure that the function identified as `private[package]` and other functions in same class use different names to avoid above problem.

Do you think this is acceptable? Or should we keep the manual exclude?

**Pull request closed without merging**
