### PR TITLE
SPARK-5408: Use -XX:MaxPermSize specified by user instead of default in ...

### PR DESCRIPTION
**Pull request by jacek-lewandowski**
...ExecutorRunner and DriverRunner

### CODE REVIEW

**Comment by srowen** [comment]
That looks reasonable to me.

**Comment by vanzin** [comment]
If the user-defined java options are appended to the Spark defined ones, shouldn't they override the latter? That way you'd have both `-XX:MaxPermSize=128m` in the command line and also the user-defined value, and the user-defined value would "win" by being later in the command line.

Also, you have a typo in the PR title.

**Comment by srowen** [comment]
@vanzin I agree, I'd imagine this actually works as expected here since the last one wins. This still feels like a small good thing just so anyone looking at the command line is less likely to be confused.

**Comment by vanzin** [comment]
I'm just trying to understand whether there's a larger bug here that applies to more than just that option. Because the bug seems to imply the user setting is not used at all.

**Comment by jacek-lewandowski** [comment]
I guess I should be overridden, but I couldn't find any specification which says that it actually works in this way.

**Comment by pwendell** [comment]
@jacek-lewandowski in practice have you found they aren't overwritten?

**Comment by jacek-lewandowski** [comment]
@pwendell for JVM which I use it is overwritten. But this is only one JVM. As I said - if such behaviour is in JVM specification - that's good. However if it is not, this should be considered as non-deterministic. I couldn't find that information.

**Comment by srowen** [comment]
I merged PR https://github.com/apache/spark/pull/4203 but don't think we need to back port it, so this can be closed.

**Comment by srowen** [comment]
Mind closing this PR?

**Pull request closed without merging**
