### PR TITLE
[SPARK-49721][BUILD] Upgrade `protobuf-java` to 3.25.5

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to upgrade `protobuf-java` to 3.25.5.

### Why are the changes needed?

To bring the latest bug fixes.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the CIs.

### Was this patch authored or co-authored using generative AI tooling?

No.

Closes #48170

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Could you review this PR when you have some time, @viirya ?

**Review by viirya — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @viirya .

**Review by HyukjinKwon — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @HyukjinKwon !

**Comment by dongjoon-hyun** [comment]
Merged to master.

**Pull request closed without merging**
