### PR TITLE
[SPARK-47164][SQL] Make Default Value From Wider Type Narrow Literal of v2 behave the same as v1

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

This PR makes the default value from a `wider-type-narrow-value` literal of pass v2 check
### Why are the changes needed?

v1/v2 consistency

### Does this PR introduce _any_ user-facing change?

no
### How was this patch tested?

new test

### Was this patch authored or co-authored using generative AI tooling?
no

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @dtenedor

**Review by dtenedor — APPROVED** [review]
Thanks for the fix!

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by cloud-fan** [comment]
late LGTM

**Pull request closed without merging**
