### PR TITLE
[SPARK-41543][K8S] Add `TOTAL_SHUFFLE_WRITE` executor roll policy

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to add new roll policy, `TOTAL_SHUFFLE_WRITE`.

### Why are the changes needed?

To provide a new built-in policy to the users.

### Does this PR introduce _any_ user-facing change?

No, this is a new policy.

### How was this patch tested?

Pass the CIs.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
This is another one, @viirya . For the doc update (including your previous review comments), I'm going to proceed separately.

**Review by viirya — APPROVED** [review]
Thanks @dongjoon-hyun. That sounds good to me.

**Comment by dongjoon-hyun** [comment]
Thank you so much, @viirya .

**Comment by dongjoon-hyun** [comment]
Merged to master for Apache Spark 3.4.0.

**Pull request closed without merging**
