### PR TITLE
[MINOR][SS][DOCS] Fix a typo in the documentation of GroupState

### PR DESCRIPTION
**Pull request by Dobiasd**
### What changes were proposed in this pull request?

Fixing some typos in the documenting comments.

### Why are the changes needed?

To make reading the docs more pleasant.

### Does this PR introduce _any_ user-facing change?

Yes, since the user sees the docs.

### How was this patch tested?

It was not tested, because no code was changed.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
This is fine but @Dobiasd:

1. would you mind taking a look and see if there are more typos since we're here?
2. Also, please keep the [GitHub pull request template](https://github.com/apache/spark/blob/master/.github/PULL_REQUEST_TEMPLATE).
3. Please take a look for https://github.com/apache/spark/pull/32400/checks?check_run_id=2467844791 and enable GItHub Actions for your repository so your PR can be properly tested.

**Comment by Dobiasd** [comment]
@HyukjinKwon Thanks for the help. :+1:

- GitHub actions already was enabled for my forked repo: https://i.imgur.com/CTEkw1R.png
- I've rebased my branch on upstream master and force-pushed as described.
- My comment is updated now, using the template.
- Using Grammarly, I've fixed some more typos in the comments of `GroupState.scala`.

**Comment by HyukjinKwon** [comment]
ok to test

**Comment by HyukjinKwon** [comment]
Thanks @Dobiasd. Your forked repository doesn't run the tests at https://github.com/Dobiasd/spark/actions .. your branch looks sync'ed with the latest Apache Spark `master` branch too hm

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Hm, but the tests should pass though before merging it in. Do other repositories of yours run GitHub Actions workflows properly?

**Comment by HyukjinKwon** [comment]
Oh, I can see now: https://github.com/Dobiasd/spark/actions. Would you mind squahsing your comments and pushing it into this PR? e.g.) `git rebase upstream/master -i`, mark the second commit as `s`, and `git push origin patch-1 --force`

**Comment by Dobiasd** [comment]
Ah, when going directly to https://github.com/Dobiasd/spark/actions, it showed this: https://i.imgur.com/NA9PgLB.png

I've clicked on "I understand my workflows, go ahead and enable them". So it should be working now. :slightly_smiling_face:

**Comment by Dobiasd** [comment]
The changes are squashed into one commit now. :heavy_check_mark:

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
