### PR TITLE
[SPARK-45837][CONNECT] Improve logging information in handling retries

### PR DESCRIPTION
**Pull request by cdkrot**
### What changes were proposed in this pull request?

Add suppressed exception when handling retries

### Why are the changes needed?

Improves user and debugging experience by showing underlying error.

### Does this PR introduce _any_ user-facing change?

Better exceptions.

### How was this patch tested?
Hand testing

### Was this patch authored or co-authored using generative AI tooling?
NA

### CODE REVIEW

**Comment by cdkrot** [comment]
@juliuszsompolski you asked for moving this here :).

**Review by hvanhovell — APPROVED** [review]
LGTM

**Review by juliuszsompolski — APPROVED** [review]
Thanks!

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM (Pending CIs)

**Comment by dongjoon-hyun** [comment]
Could you re-trigger CI, @cdkrot ?

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
