### PR TITLE
[SPARK-12350] [core] Don't log errors when requested stream is not found.

### PR DESCRIPTION
**Pull request by vanzin**
If a client requests a non-existent stream, just send a failure message
back, without logging any error on the server side (since it's not a
server error).

On the executor side, avoid error logs by translating any errors during
transfer to a `ClassNotFoundException`, so that loading the class is
retried on a the parent class loader. This can mask IO errors during
transmission, but the most common cause is that the class is not
served by the remote end.

### CODE REVIEW

**Comment by jodersky** [comment]
Unfortunatly I now get another, similar error message in spark-shell
```
15/12/16 14:00:48 ERROR NettyRpcEnv: Error downloading stream /classes/org/apache/spark/sql/catalyst/expressions/Object.class.
java.lang.RuntimeException: Stream '/classes/org/apache/spark/sql/catalyst/expressions/Object.class' was not found.
	at org.apache.spark.network.client.TransportResponseHandler.handle(TransportResponseHandler.java:219)
	at org.apache.spark.network.server.TransportChannelHandler.channelRead0(TransportChannelHandler.java:106)
	at org.apache.spark.network.server.TransportChannelHandler.channelRead0(TransportChannelHandler.java:51)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at org.apache.spark.network.util.TransportFrameDecoder.channelRead(TransportFrameDecoder.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by vanzin** [comment]
Hmm, I did not notice that when testing, but will clean it up.

**Comment by jodersky** [comment]
Sorry to bother you again, there is one more error message that appears. This can be fixed by changing `repl/src/main/scala/org/apache/spark/repl/ExecutorClassLoader.scala`, line 162 to a `logDebug` instead of a `logError`

**Comment by vanzin** [comment]
Hmm, that one shouldn't just be a log change. What's the code you're running to actually hit that?

**Comment by jodersky** [comment]
I'm running the code snippet from the original JIRA:
```scala
import org.apache.spark.ml.feature.VectorAssembler
val df = sc.parallelize(List((1,2), (3,4))).toDF
val assembler = new VectorAssembler().setInputCols(Array("_1", "_2")).setOutputCol("features")
assembler.transform(df).show
```
in the spark shell spawned from the sbt `sparkShell` task

**Comment by zsxwing** [comment]
> Hmm, that one shouldn't just be a log change. What's the code you're running to actually hit that?

The problem here is there is no special exception for not found class in the server side. It's just a `RuntimeException`.

**Comment by vanzin** [comment]
I was running in local-cluster mode, I think that's why I was not seeing the executor-side log. Let me see if I can get rid of it easily.

**Comment by vanzin** [comment]
retest this please

**Comment by yhuai** [comment]
@vanzin So, the problem is that we log the error that should not be logged instead of we fail to code-gen?

**Comment by vanzin** [comment]
There's no failure anywhere; we're just logging exceptions that shouldn't necessarily be logged.

**Comment by zsxwing** [comment]
LGTM

**Comment by jodersky** [comment]
Solved for me too now

**Comment by yhuai** [comment]
test this please

**Comment by vanzin** [comment]
Merging to master.

**Pull request closed without merging**
