### PR TITLE
[SAPRK-25011][ML]add PrefixSpan to __all__ in fpm.py

### PR DESCRIPTION
**Pull request by hhbyyh**
## What changes were proposed in this pull request?

jira: https://issues.apache.org/jira/browse/SPARK-25011

add prefix to __all__ in fpm.py

## How was this patch tested?

existing unit test.

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Looks we should fix the doc in PrefixSpan too. LGTM if the check pass.

**Comment by hhbyyh** [comment]
Ah, this triggers the doc check. Updating.

**Comment by hhbyyh** [comment]
Thanks for the review @HyukjinKwon.

**Comment by hhbyyh** [comment]
BTW, @HyukjinKwon, do you know who's still reviewing the ML PRs? I have a few old PRs and I really want to know which're considered meaningful.

**Comment by HyukjinKwon** [comment]
I am not sure. ML is not my area but I am pretty sure who you know are basically who I know .. ping me if that's minor or trivial like this. I can review and merge.

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by HyukjinKwon** [comment]
@hhbyyh BTW, there's typo for the JIRA ticket in the title. Not a big deal though better to match.

**Pull request closed without merging**
