### PR TITLE
[SPARK-8887][SQL]Explicit define which data types can be used as dynamic partition columns

### PR DESCRIPTION
**Pull request by yjshen**
This PR enforce dynamic partition column data type requirements by adding analysis rules.

JIRA: https://issues.apache.org/jira/browse/SPARK-8887

### CODE REVIEW

**Comment by yjshen** [comment]
I mistakenly delete the branch on github, sorry about this.

**Comment by yjshen** [comment]
@rxin @liancheng

**Comment by liancheng** [comment]
This is exactly the same as #8132, right?

**Comment by yjshen** [comment]
yes, it's the same, I mistakenly deleted them both on github, and reopened a new PR here

**Comment by liancheng** [comment]
OK. This LGTM, but I'd like to ask @rxin for a final review.

**Comment by rxin** [comment]
Merging in master.

**Pull request closed without merging**
