### PR TITLE
[SPARK-49947][SQL][TESTS] Upgrade `MsSql` docker image version

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to upgrade the `MsSql` docker image version from `2022-CU14-ubuntu-22.04` to `2022-CU15-ubuntu-22.04`.

### Why are the changes needed?
This will help Apache Spark test the latest `MsSql`.
https://hub.docker.com/r/microsoft/mssql-server
image

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by panbingkun** [comment]
image

**Review by MaxGekk — COMMENTED** [review]
@milastdbx Could you review this PR, please.

**Comment by panbingkun** [comment]
> @milastdbx Could you review this PR, please.

Thanks @MaxGekk @milastdbx

**Review by MaxGekk — APPROVED** [review]

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
