### PR TITLE
[SPARK-43169][INFRA][FOLLOWUP] Add more memory for mima check

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr aims to change `-Xmx` from `4196` to `120` for dev/mima to avoid `GC overhead limit exceeded`.

### Why are the changes needed?
Make `dev/mina` stable on GitHub Action.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Manually check that `GC overhead limit exceeded` no longer exists

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Thanks for the PR. Let's wait and see.

**Comment by LuciferYang** [comment]
> Thanks for the PR. Let's wait and see.

ok

**Comment by LuciferYang** [comment]
```
[info] *** 4 TESTS FAILED ***
[error] Failed tests:
[error] 	org.apache.spark.sql.UserDefinedFunctionE2ETestSuite
[error] (connect-client-jvm / Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 114 s (01:54), completed Apr 20, 2023 4:32:20 AM
```

https://github.com/LuciferYang/spark/actions/runs/4749019479/jobs/8438173582

Rerunning these four cases still failed ....

**Comment by HyukjinKwon** [comment]
Hmmmm ....

**Comment by LuciferYang** [comment]
@HyukjinKwon It seems inevitable to fail, not random... 

local run `build/sbt "connect-client-jvm/test` 3 times, all four cases have failed.

I'll go have lunch first and  investigate in the afternoon ...

**Comment by HyukjinKwon** [comment]
Seems like it was because of https://github.com/apache/spark/commit/09a43531d30346bb7c8d213822513dc35c70f82e. Let's close this :-). Thanks for your effort though.

**Comment by LuciferYang** [comment]
@HyukjinKwon Do you know the maximum memory that GA instances can use? 

I checked the logs and found that with the same memory configuration, logs similar to `In the last 10 seconds, 5.524 (55.8%) were spent in GC` are printed more times in GA than locally

**Comment by HyukjinKwon** [comment]
Its 7GB / 2cores IIRC (https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources)

**Comment by LuciferYang** [comment]
hmm... I suggest add more memory. I have seen new `GC overhead limit exceeded.` on GA today. If 7G is available, we can directly make the mima check use 5G

**Comment by LuciferYang** [comment]
Can you help me to re open this one ? @HyukjinKwon

**Comment by LuciferYang** [comment]
thanks @HyukjinKwon

**Comment by HyukjinKwon** [comment]
Actually MiMa check seems fine, and doesn;t seem failing.

**Comment by LuciferYang** [comment]
@pan3793 I remember you provided an OOM case this morning. Can you provide a link?

**Comment by pan3793** [comment]
> @pan3793 I remember you provided an OOM case this morning. Can you provide a link?

https://github.com/pan3793/spark/actions/runs/4746374013/jobs/8431906344

**Comment by LuciferYang** [comment]
OK, Let's open this pr for a few days. If the master has  mima check OOM, there is no need to resubmit

**Comment by Hisoka-X** [comment]
OOM too. https://github.com/Hisoka-X/spark/actions/runs/4751425402/jobs/8441304002

**Comment by LuciferYang** [comment]
> OOM too. https://github.com/Hisoka-X/spark/actions/runs/4751425402/jobs/8441304002

with 5g?

**Comment by Hisoka-X** [comment]
> > OOM too. https://github.com/Hisoka-X/spark/actions/runs/4751425402/jobs/8441304002
> 
> with 5g?

No, I didn't change anything, so it will be 4G?

**Comment by LuciferYang** [comment]
> > > OOM too. https://github.com/Hisoka-X/spark/actions/runs/4751425402/jobs/8441304002
> > 
> > 
> > with 5g?
> 
> No, I didn't change anything, so it will be 4G?

4196m now, It seems that 4196m is not stable enough now

**Comment by LuciferYang** [comment]
Test once more

**Comment by LuciferYang** [comment]
From the GA task logs, it can be seen that using 5g only 1 ~ 2 `for better performance` related logs during mima check

**Comment by LuciferYang** [comment]
> Its 7GB / 2cores IIRC (https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources)

After multiple verifications, I suggest change -Xmx to 5120. From the logs, it will significantly reduce the number of GCs and the amount of time consumed, and there will be no `GC overhead limit exceeded` issue again

**Comment by LuciferYang** [comment]
@HyukjinKwon 

https://github.com/LuciferYang/spark/actions/runs/4776155966/jobs/8491000795

See `GC overhead limit exceeded` again

**Review by HyukjinKwon — APPROVED** [review]

**Comment by zhengruifeng** [comment]
mima test OOM again https://github.com/apache/spark/actions/runs/4783257117/jobs/8503361722

**Comment by zhengruifeng** [comment]
merged to master

**Comment by LuciferYang** [comment]
Thanks @zhengruifeng @HyukjinKwon @pan3793 @Hisoka-X

**Pull request closed without merging**
