### PR TITLE
[DO-NOT-MERGE] trigger CI

### PR DESCRIPTION
**Pull request by HeartSaVioR**

### CODE REVIEW

**Comment by LuciferYang** [comment]
To solve the stability of `sql-others`, `hive-others` and `tpcds`?

**Comment by HeartSaVioR** [comment]
I'm only targeting to sql-others as I see almost consistent failure in sql-others, though I had to touch some code here to trigger test run. Are you investigating the same?

**Comment by HyukjinKwon** [comment]
Seems like TPC-DS consistently fails too most likely because of out-of-memory. I worked around this by splitting the queries to run but .. it'd be great if we can find a way to fix this up. I'll likely take a look too around early next week.

**Comment by HyukjinKwon** [comment]
Made a PR for TPC-DS https://github.com/apache/spark/pull/37270

**Comment by LuciferYang** [comment]
```
sbt.ForkMain 34895 failed with exit code 137[0m
2022-07-24T06:25:51.5368193Z [0m[[0m[33mwarn[0m] [0m[0mIn the last 5506 seconds, 21.985 (0.4%) were spent in GC. [Heap: 2.99GB free of 3.62GB, max 3.62GB] Consider increasing the JVM heap using `-Xmx` or try a different collector, e.g. `-XX:+UseG1GC`, for better performance.[0m
```

Sorry for the late reply,  I found that before GA task was killed, there would be logs like the one above, can we try to increase `-Xmx`?

In addition, can we get the content of `dmesg`?

**Comment by HyukjinKwon** [comment]
cc @Yikun too FYI

**Comment by LuciferYang** [comment]
https://github.com/apache/spark/blob/72b55ccf8327c00e173ab6130fdb428ad0d5aacc/project/SparkBuild.scala#L1194-L1199


I change the 2 `-Xmx4g` in `SparkBuild.scala` to `-Xmx3200m` and add `-XX:+UseG1GC` options, but still found logs as follows:

```
sbt.ForkMain 42403 failed with exit code 137
2022-07-26T05:27:04.8785522Z [warn] In the last 3341 seconds, 19.769 (0.6%) were spent in GC. [Heap: 3.28GB free of 3.99GB, max 3.99GB] Consider increasing the JVM heap using `-Xmx` or try a different collector, e.g. `-XX:+UseG1GC`, for better performance.
2022-07-26T05:27:06.9932313Z [error] (hive / Test / test) sbt.TestsFailedException: Tests unsuccessful
2022-07-26T05:27:07.0186283Z [error] Total time: 3343 s (55:43), completed Jul 26, 2022 5:27:07 AM
2022-07-26T05:27:07.7573628Z [error] running /home/runner/work/spark/spark/build/sbt -Phadoop-3 -Phive -Dtest.include.tags=org.apache.spark.tags.SlowHiveTest hive/test ; received return code 1
```

The max heap size still 4GB,  it doesn't seem understandable,

**Comment by Yikun** [comment]
Sorry for late reply, I'm busy in some local meeting recent days.

> In addition, can we get the content of dmesg?

@LuciferYang  We can add a separate step like:
```
- name: Print debug info
  if: failure()
  run: |
    # print demsg info
```

**Comment by LuciferYang** [comment]
> Sorry for late reply, I'm busy in some local meeting recent days.
> 
> > In addition, can we get the content of dmesg?
> 
> @LuciferYang We can add a separate step like:
> 
> ```
> - name: Print debug info
>   if: failure()
>   run: |
>     # print demsg info
> ```

Thanks for your reply, I have tested,  the account executing GA should not have permission to execute `demsg` and  GA test should already stability now :)

**Comment by HyukjinKwon** [comment]
Let me close this one. I believe all are fixed now.

**Pull request closed without merging**
