### PR TITLE
[MINOR] Fix some typos

### PR DESCRIPTION
**Pull request by for08**
What changes were proposed in this pull request?
Fix some typos in the code comments.
Why are the changes needed?
Modify these two comment mistakes and make code comments more standardized.
Does this PR introduce any user-facing change?
No
How was this patch tested?
No test required

### CODE REVIEW

**Review by HyukjinKwon — COMMENTED** [review]
That;s fine but mind fixing more typos since we're here? Also please keep the PR template https://github.com/apache/spark/blob/master/.github/PULL_REQUEST_TEMPLATE

**Comment by for08** [comment]
> That;s fine but mind fixing more typos since we're here? Also please keep the PR template https://github.com/apache/spark/blob/master/.github/PULL_REQUEST_TEMPLATE



> Can one of the admins verify this patch?

I reopen this PR according to the suggestions of srowen and bjornjorgensen. As a beginner, I will continue to learn and use, not just fixing more typos.

**Comment by for08** [comment]
I reopen this PR according to the suggestions of srowen and bjornjorgensen.
















At 2022-12-19 11:30:19, "UCB AMPLab" ***@***.***> wrote:

Can one of the admins verify this patch?

**Comment by for08** [comment]
I reopen this PR according to the suggestions of srowen and bjornjorgensen. As a beginner, I will continue to learn and use, not just fixing more typos.
















At 2022-12-19 09:13:59, "Hyukjin Kwon" ***@***.***> wrote:

@HyukjinKwon commented on this pull request.

That;s fine but mind fixing more typos since we're here? Also please keep the PR template https://github.com/apache/spark/blob/master/.github/PULL_REQUEST_TEMPLATE

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Okay.

Merged to master.

**Pull request closed without merging**
