### PR TITLE
[SPARK-15741][PYSPARK][ML] Pyspark cleanup of set default seed to None

### PR DESCRIPTION
**Pull request by BryanCutler**
## What changes were proposed in this pull request?

Several places set the seed Param default value to None which will translate to a zero value on the Scala side.  This is unnecessary because a default fixed value already exists and if a test depends on a zero valued seed, then it should explicitly set it to zero instead of relying on this translation.  These cases can be safely removed except for the ALS doc test, which has been changed to set the seed value to zero.
## How was this patch tested?

Ran PySpark tests locally

### CODE REVIEW

**Comment by BryanCutler** [comment]
@MLnick , does this seem reasonable?
cc @yanboliang

**Comment by MLnick** [comment]
LGTM

**Comment by BryanCutler** [comment]
Thanks @MLnick , can this be merged or do we need to wait until 2.0 is cut?

**Comment by MLnick** [comment]
jenkins retest this please

**Comment by mengxr** [comment]
Merged into master and branch-2.0. Thanks!

**Comment by BryanCutler** [comment]
Thanks @mengxr and @MLnick!

**Pull request closed without merging**
