### PR TITLE
[SPARK-31532][SPARK-31234][SQL][FOLLOWUP] Use lowercases for GLOBAL_TEMP_DATABASE  config in SparkSessionBuilderSuite

### PR DESCRIPTION
**Pull request by maropu**
### What changes were proposed in this pull request?

This PR intends to fix test code for using lowercases for the `GLOBAL_TEMP_DATABASE` config in `SparkSessionBuilderSuite`. The handling of the config is different between branch-3.0+ and branch-2.4. In branch-3.0+, Spark always lowercases a value in the config, so I think we had better always use lowercases for it in the test.

This comes from the @dongjoon-hyun 
 comment: https://github.com/apache/spark/pull/28316#issuecomment-619303160

### Why are the changes needed?

To fix the test failure in branch-2.4.

### Does this PR introduce any user-facing change?

No.

### How was this patch tested?

Fixed the test.

### CODE REVIEW

**Comment by maropu** [comment]
cc: @dongjoon-hyun @cloud-fan @yaooqinn

**Review by yaooqinn — APPROVED** [review]

**Comment by yaooqinn** [comment]
LGTM. shall we tag SPARK-31234 too？

**Comment by dongjoon-hyun** [comment]
Hi, @maropu . 
Sorry. I wasn't clear enough. I mean a follow PR for branch-2.4 only.
We should keep `.config(GLOBAL_TEMP_DATABASE.key, ...` part for test coverage.
I meant to change the string in `assert`.

**Comment by maropu** [comment]
Ah, I see. I'll close this.

**Pull request closed without merging**
