### PR TITLE
[SPARK-22042] [FOLLOW-UP] [SQL] ReorderJoinPredicates can break when child's partitioning is not decided

### PR DESCRIPTION
**Pull request by tejasapatil**
## What changes were proposed in this pull request?

This is a followup PR of https://github.com/apache/spark/pull/19257 where @gatorsmile had left couple comments wrt code style.

## How was this patch tested?

Doesn't change any functionality. Will depend on build to see if no checkstyle rules are violated.

### CODE REVIEW

**Comment by tejasapatil** [comment]
checked the test case failure but I dont think its related to this PR. 

```
org.apache.spark.sql.execution.datasources.parquet.ParquetQuerySuite.(It is not a test it is a sbt.testing.SuiteSelector)
org.scalatest.exceptions.TestFailedDueToTimeoutException: The code passed to eventually never returned normally. Attempted 651 times over 10.008601144 seconds. Last failure message: There are 1 possibly leaked file streams..
```

**Comment by tejasapatil** [comment]
Jenkins retest this please

**Comment by gengliangwang** [comment]
retest this please

**Comment by gengliangwang** [comment]
retest this please

**Review by gatorsmile — APPROVED** [review]

**Comment by gatorsmile** [comment]
LGTM 

Thanks! Merged to master.

**Pull request closed without merging**
