### PR TITLE
[MINOR][K8S] Print the driver pod name instead of Some(name) if absent

### PR DESCRIPTION
**Pull request by yaooqinn**
Print the driver pod name instead of Some(name) if absent

### Why are the changes needed?

fix error hint

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

new test

### CODE REVIEW

**Comment by yaooqinn** [comment]
cc @dongjoon-hyun thank you

**Comment by yaooqinn** [comment]
retest this please

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
Hi, @yaooqinn .
Do you think this is the minimal patch to do that? If you don't mind, could you minimize this PR please? :)

**Comment by yaooqinn** [comment]
thanks, @dongjoon-hyun, minimized the patch

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you so much, @yaooqinn .
Merged to master.

**Comment by dongjoon-hyun** [comment]
I resolved the conflicts and backported this to branch-3.1 too.

**Comment by yaooqinn** [comment]
thank you @dongjoon-hyun

**Pull request closed without merging**
