### PR TITLE
[MINOR][SQL] Fix a typo at 'spark.sql.sources.fileCompressionFactor' error message in SQLConf

### PR DESCRIPTION
**Pull request by Ted-Jiang**
### What changes were proposed in this pull request?

 fix typo in SQLConf

### Why are the changes needed?

typo fix to increase readability

### How was this patch tested?

no test

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
@Ted-Jiang, can you double check and see if there are other typos in this file while we're here?

**Comment by Ted-Jiang** [comment]
> @Ted-Jiang, can you double check and see if there are other typos in this file while we're here?
Sure！

**Comment by srowen** [comment]
Jenkins test this please

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
