### PR TITLE
[SPARK-47875][CORE] Remove `spark.deploy.recoverySerializer`

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This is a logical revert of SPARK-46205
- #44113
- #44118

### Why are the changes needed?

The initial implementation didn't handle the class initialization logic properly.
Until we have a fix, I'd like to revert this from `master` branch.

### Does this PR introduce _any_ user-facing change?

No, this is not released yet.

### How was this patch tested?

Pass the CIs.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Sorry but could you review this reverting PR, @viirya ? While I've running this, I found my mistake.

**Review by viirya — APPROVED** [review]

**Comment by viirya** [comment]
Pending CI. Thanks @dongjoon-hyun

**Comment by dongjoon-hyun** [comment]
Thank you so much for swift help. I'll make it sure that all CIes passes.

**Review by viirya — COMMENTED** [review]
In original PR, there are a few change to `FileSystemPersistenceEngine.scala`, do we need to revert it too?

**Comment by dongjoon-hyun** [comment]
Yes, there are other commits about `compression` code and some neutral changes. I believe it will be okay and the final goal is to bring it back again.

**Comment by dongjoon-hyun** [comment]
I removed the missed SPARK-46205 test case.

**Pull request closed without merging**
