### PR TITLE
[SPARK-1143] Separate pool tests into their own suite.

### PR DESCRIPTION
**Pull request by kayousterhout**
The current TaskSchedulerImplSuite includes some tests that are
actually for the TaskSchedulerImpl, but the remainder of the tests avoid using
the TaskSchedulerImpl entirely, and actually test the pool and scheduling
algorithm mechanisms. This commit separates the pool/scheduling algorithm
tests into their own suite, and also simplifies those tests.

The pull request replaces #339.

### CODE REVIEW

**Comment by rxin** [comment]
LGTM ...

**Comment by kayousterhout** [comment]
Jenkins, retest this please

**Comment by kayousterhout** [comment]
@tdas what's the status with these (seemingly unreliable) Kafka tests? Should they be disabled?

**Comment by pwendell** [comment]
Looks good, 'Ill pull it in.

**Pull request closed without merging**
