### PR TITLE
[SPARK-13610][ML] Create a Transformer to disassemble vectors in Data…

### PR DESCRIPTION
**Pull request by leonfl**
JIRA Issue: https://issues.apache.org/jira/browse/SPARK-13610

## What changes were proposed in this pull request?

Add a VectorDisassembler used for disassemble the vector field to single fields.

## How was this patch tested?

Unit tests have added into ml for this feature.

### CODE REVIEW

**Comment by srowen** [comment]
I don't think this is worth adding. It's pretty easy to pull out a single fiedl from a vector already.

**Comment by leonfl** [comment]
It's a method like VectorAssembler, which make user easy to handle single fields and vector field.
Pull out a single field is easy, but for all single fields in a vector, it still need some code by users. This Transformer will make user easy understand and use, right?

**Comment by leonfl** [comment]
@mengxr, could you help to check this patch? Thanks

**Comment by leonfl** [comment]
@jkbradley, Could you also help to check this patch cause you are familiar with this defect, Thanks.

**Comment by mrjrdnthms** [comment]
I could use this. I have udf to pick out single values I want but my implementation is slow: here is my python udf:
`probTrue_udf = udf(lambda value: value[1].item(), FloatType())`
I was hoping there would be a lower level api that did the disassemble transformation quickly.

**Comment by leonfl** [comment]
@mrjrdnthms , this is implemented by UDF, which will run a little bit slower, but easy to use.
If you want it run faster, you can implement it using mappatition and row iterator instead of udf.
That implementation will reduce the running time a lot.

**Comment by mrjrdnthms** [comment]
@leonfl The python udf is too slow for my task. By "mappatition and row iterator" do you mean doing the transformation on the RDD directly instead of the dataframe? Sorry for the basic question. I am new to spark. And thanks for help.

**Comment by leonfl** [comment]
@mrjrdnthms ,Yes, your understand is correct, in scala it like this:

```
    val rows: RDD[Row] = df.rdd.map(
      rowIn => {
        // handle the rowIn and return a Row
      }
    )
    val newDF = df.sqlContext.createDataFrame(rows, /*create the newDF schema*/)
```

**Comment by AlbertPlaPlanas** [comment]
Was this ever implemented?

**Comment by HarborZeng** [comment]
such a great transformer, don't understand why they chose to ingore this patch.

**Comment by diegoxfx** [comment]
> I don't think this is worth adding. It's pretty easy to pull out a single fiedl from a vector already.

It is not possible to retrieve a single element from VectorAssembler, it's only possible to retrieve a subset of the array, but it is still an array the element

**Pull request closed without merging**
