### PR TITLE
[SPARK-32271][ML] Add option for k-fold cross-validation to CrossValidator

### PR DESCRIPTION
**Pull request by adjordan**
### What changes were proposed in this pull request?

I have added a `method` parameter to `CrossValidator.scala` to allow the user to choose between repeated random sub-sampling cross-validation (current behavior) and _k_-fold cross-validation (optional new behavior). The default method is random sub-sampling cross-validation.

If _k_-fold cross-validation is chosen, the new behavior is as follows:

1. Instead of splitting the input dataset into _k_ training and validation sets, I split them into _k_ folds; for each fold of training, one of the _k_ splits is selected for validation, and the others are unioned together for training.
2. Instead of caching each training and validation set _k_ times, I cache each of the folds once.
3. Instead of waiting for every model to finish training on fold _n_ before moving on to fold _n+1_, new fold/model combinations will be trained as soon as resources are available.
4. Instead of creating one `Future` per model for each fold in series, all `Future`s for each fold & parameter grid pair are created and trained in parallel.
5. A new `Int` parameter is added to the `Future` (now `Future[Int, Double]` instead of `Future[Double]`) in order to keep track of which `Future` belongs to which parameter grid.

### Why are the changes needed?

These changes allow the user to choose between repeated random sub-sampling cross-validation (current behavior) and _k_-fold cross-validation (optional new behavior). These changes:
1. Allow the user to choose between two types of cross-validation.
2. (If _k_-fold is chosen) Only require caching the entire dataset once (instead of _k_ times in repeated random sub-sampling cross-validation, as it does now).
3. (If _k_-fold is chosen) Free resources to train new model/fold combinations as soon as the previous one finishes. Currently, a model can only train one fold at a time. If _k_-fold is chosen, the added functionality will allow the `fit` to train multiple folds at once for the same model, and, in the case of a grid search, allow it to train multiple model/fold combinations at once, without needing to wait for the slowest model to fit the first fold before moving onto the second.

### Does this PR introduce _any_ user-facing change?

Yes. This PR introduces the `setMethod` method to `CrossValidator`. If the `method` parameter is not set, the behavior will be the same as it has always been.

### How was this patch tested?

Unit tests will be added.

### CODE REVIEW

**Comment by adjordan** [comment]
This is ready for review!

**Comment by adjordan** [comment]
@viirya

**Comment by huaxingao** [comment]
ok to test

**Review by viirya — COMMENTED** [review]
This actually changes how we do cross validation. See https://en.wikipedia.org/wiki/Cross-validation_(statistics)#k-fold_cross-validation and https://en.wikipedia.org/wiki/Cross-validation_(statistics)#Repeated_random_sub-sampling_validation.

**Comment by adjordan** [comment]
@viirya Sorry, can you explain? I don't see how it changes anything, it just allows models from multiple folds to be run in parallel.

**Comment by viirya** [comment]
Do you read the above too links? The current approach is repeated random sub-sampling validation, this PR changes to k-fold cross-validation.

**Comment by adjordan** [comment]
Yes, I know the difference between the two. I just assumed that `MLUtils.kFold` was doing the splits according to the k-fold method, not the random sub-sampling method. But I suppose changing the name of that method is outside the scope of what I'm trying to add.

In that case, it seems that I should add an addition `method` parameter where you can select k-fold or random sub-sampling. If I end up doing that, should I continue with this PR or open a new one?

Thoughts @viirya?

**Comment by adjordan** [comment]
I've done a first pass at including both options. Tomorrow I'll clean it up and add the necessary unit tests.

**Comment by adjordan** [comment]
@viirya I made the changes and added unit tests. Let me know what you think.

**Review by viirya — COMMENTED** [review]
> Instead of waiting for every model to finish training on fold n before moving on to fold n+1, new fold/model combinations will be trained as soon as resources are available.

We already fit models in parallel for each fold now. Considering the resource requirement of fitting model might not be small, I'm wondering if how many advantages in practice making all folds in parallel could have.

This new approach can reduce the caching times on training and validation datasets. I think sampling should not be so heavy, so I guess it is close to cache the entire dataset. For current CrossValidator, we can also cache the entire dataset to speed up training/validation sampling.

Based on the few points, although I think the new approach might work better than current one in some cases, I am not sure if it is better in most of cases in practice. At lease you need to have enough resources to fit all models in all folds in parallel.

I have no strong option about this.

**Comment by adjordan** [comment]
@viirya I certainly have many situations wherein this new approach is better, which is what caused me to open this pull request in the first place. Would it be helpful if this was labeled an "expert" parameter, like some other classes have?

**Comment by adjordan** [comment]
@viirya While it may not work better if the user has limited resources, it will never work worse, and it introduces a new way to do cross-validation that was previously unavailable.

**Comment by adjordan** [comment]
@viirya What's the status of this? Can this be merged?

**Comment by adjordan** [comment]
@HyukjinKwon Tagging you because I saw you approved some recent PRs. I still strongly believe this functionality is worth having. Can we take a look?

**Pull request closed without merging**
