### PR TITLE
[SPARK-50004][SQL] Integrate `_LEGACY_ERROR_TEMP_3327` into `FIELD_NOT_FOUND`

### PR DESCRIPTION
**Pull request by itholic**
### What changes were proposed in this pull request?

This PR proposes to integrate `_LEGACY_ERROR_TEMP_3327` into `FIELD_NOT_FOUND`

### Why are the changes needed?

To improve the error message by assigning proper error condition and SQLSTATE

### Does this PR introduce _any_ user-facing change?

No, only user-facing error message improved

### How was this patch tested?

Updated the existing tests

### Was this patch authored or co-authored using generative AI tooling?

No

### CODE REVIEW

**Review by MaxGekk — APPROVED** [review]

**Review by dongjoon-hyun — COMMENTED** [review]
Could you re-trigger the failed test pipelines, @itholic ?

**Review by MaxGekk — CHANGES_REQUESTED** [review]
The failed test is related to your changes:
```
[info] - alterTable: add field to missing column fails *** FAILED *** (12 milliseconds)
[info]   "[FIELD_NOT_FOUND] No such struct field `missing_col` in `id`, `data`. SQLSTATE: 42704" did not contain "Cannot find" (V2SessionCatalogSuite.scala:452)
[info]   org.scalatest.exceptions.TestFailedException:
```
@itholic Please, fix it.

**Comment by itholic** [comment]
Fixed the failed tests. Thanks!

**Review by MaxGekk — APPROVED** [review]

**Comment by MaxGekk** [comment]
+1, LGTM. Merging to master.
Thank you, @itholic.

**Pull request closed without merging**
