### PR TITLE
[SPARK-15011][SQL] Re-enable 'analyze MetastoreRelations' in hive StatisticsSuite

### PR DESCRIPTION
**Pull request by hvanhovell**
## What changes were proposed in this pull request?

This test re-enables the `analyze MetastoreRelations` in `org.apache.spark.sql.hive.StatisticsSuite`. 

The flakiness of this test was traced back to a shared configuration option, `hive.exec.compress.output`, in `TestHive`. This property was set to `true` by the `HiveCompatibilitySuite`. I have added configuration resetting logic to `HiveComparisonTest`, in order to prevent such a thing from happening again.
## How was this patch tested?

Is a test.

### CODE REVIEW

**Comment by hvanhovell** [comment]
I'll trigger a bunch of tests and see what happens.

**Comment by hvanhovell** [comment]
Ok I suspect that not all tables are created in the same way. Added some code to dump the table metadata.

**Comment by hvanhovell** [comment]
Seems to be related to the sequence in which tests are executed... Perhaps `src` is changed during tests.

**Comment by rxin** [comment]
Looks like there are some failures ...

**Comment by hvanhovell** [comment]
cc @JoshRosen

**Comment by rxin** [comment]
Merging in master/2.0.

**Pull request closed without merging**
