### PR TITLE
[SPARK-7263] Add new shuffle manager which stores shuffle blocks in Parquet

### PR DESCRIPTION
**Pull request by massie**
This commit adds a new Spark shuffle manager which reads and writes shuffle data to Apache Parquet files. Parquet has a File interface (not a streaming interface) because it is column-oriented and seeks in a File for metadata information, e.g. schemas, statistics. As such, this implementation fetches remote data to local, temporary blocks before the data is passed to Parquet for reading.

This managers uses the following spark configuration parameters to configure Parquet: `spark.shuffle.parquet.{compression, blocksize, pagesize, enabledictionary}.`

There is a `spark.shuffle.parquet.fallback` configuration option which allows users to specify a fallback shuffle manager. If the Parquet manager finds that the classes being shuffled have no schema information, and therefore can't be used, it will fallback to the specified fallback manager. With this PR, only Avro `IndexedRecords` are supported in the Parquet shuffle; however, it is straight-forward to extend this to other serialization systems that Parquet supports, e.g. Apache Thrift. If there is no `spark.shuffle.parquet.fallback` defined, any shuffle objects which are not compatible with Parquet will cause an error to be thrown which lists the incompatible objects.

Because the `ShuffleDependency` forwards the key, value and combined class information, a full schema can be generated before the first read/write. This allows for less errors (since reflection isn't used) and makes support for null values possible without complex code.

The `ExternalSorter`, if needed, is setup to not spill to disk if Parquet is used. In the future, an `ExternalSorter` would need to be created that can read/write Parquet.

Only record-level metrics are supported at this time. Byte-level metrics are not currently supported and are complicated somewhat by column compression.

### CODE REVIEW

**Comment by massie** [comment]
This PR currently only has four new tests to show that:

* the fallback shuffle for non-Avro objects works
* the Parquet shuffle is able to shuffle *with and without* map-side aggregation (combiner)
* the Parquet shuffle is able to shuffle null values

I'm submitting this PR to solicit feedback about the overall approach. Once reviewer have given this approach their blessing, I'll spend a few days writing targeted tests. Please let me know what parts of this change concern you most to help inform my test writing.

**Comment by sryza** [comment]
Is my understanding correct that, with this shuffle manager, we wouldn't be able to do reduce-side that sorts records, or any map-side spilling?

**Comment by massie** [comment]
Map-side aggregation is supported in this pull request. If you look at the `ParquetShuffleManager.parquetShuffleCanBeUsed()` method, you'll see that it generates an Avro schema which take into consideration which class of objects will be spilled. The `ParquetShuffleWriter.write()` method, aggregates and then writes using this schema (the `ParquetShuffleReader.read()` just uses the schema stored in Parquet by the writer).

The `ExternalSorter` currently uses the Spark `Serializer` interface to read/write objects during the spill. If you like, I can easily have the Parquet shuffle reader follow that same pattern for now since it will work, even though it's not ideal.

**Comment by sryza** [comment]
Having the Parquet shuffle reader follow that pattern seems preferable to me over failing when spilling would be required.

**Comment by massie** [comment]
Done. The Parquet shuffle reader behaves identically to the hash shuffle reader now and uses the defined Spark Serializer.

**Comment by massie** [comment]
Jenkins has just been reconfigured to fix a testing infra bug. I'm going to kill the current build and start a new one.

Jenkins, test this please.

**Comment by massie** [comment]
Jenkins, test this please.

**Comment by massie** [comment]
I'm not sure why Jenkins is calling out changes to 
```
class DecisionTreeClassificationModel(DecisionTreeModel):
class RandomForestClassificationModel(TreeEnsembleModels):
class GBTClassificationModel(TreeEnsembleModels):
class DecisionTreeModel(JavaModel):
class TreeEnsembleModels(JavaModel):
class DecisionTreeRegressionModel(DecisionTreeModel):
class RandomForestRegressionModel(TreeEnsembleModels):
class GBTRegressionModel(TreeEnsembleModels):
```
since this PR makes no changes to them.

**Comment by massie** [comment]
I just rebased on master to fix a pom.xml conflict. Both `parquet-avro` and `parquet-thrift` were added in #7231, so they don't need to be added here.

**Comment by massie** [comment]
Jenkins, test this please.

**Comment by massie** [comment]
Looks like Jenkins was in a bad state. I'll kick it to test again.

**Comment by massie** [comment]
Jenkins, test this please.

**Comment by massie** [comment]
I've opened PR #7403 which includes only the changes to the Spark shuffle, serializing the class paths. I'll rebase this PR to only have the Parquet shuffle implementation work. I'm hoping the separating these will make it easier to review.

**Comment by massie** [comment]
Jenkins, test this please.

**Comment by massie** [comment]
Once #7403 is merged, I'll rebase this PR on and fix the conflicts.

**Comment by massie** [comment]
Now that #7403 is merged, I've rebased this PR on top of `master`. This PR is ready for review now, when someone has the time. Thanks.

**Comment by cpwais** [comment]
Might this make some 2.0.x release of Spark?

**Comment by rxin** [comment]
I'm gong to close this for now. Next year we might actually come back and revisit this - probably not with the current parquet implementation since it is not very efficient, but some sort of columnar format.

**Pull request closed without merging**
