### PR TITLE
[SPARK-13015][Docs] Replace example code in mllib-data-types.md using include_example

### PR DESCRIPTION
**Pull request by keypointt**
Replace example code in mllib-data-types.md using include_example
https://issues.apache.org/jira/browse/SPARK-13015

The example code in the user guide is embedded in the markdown and hence it is not easy to test. It would be nice to automatically test them. This JIRA is to discuss options to automate example code testing and see what we can do in Spark 1.6.

Goal is to move actual example code to spark/examples and test compilation in Jenkins builds. Then in the markdown, we can reference part of the code to show in the user guide. This requires adding a Jekyll tag that is similar to https://github.com/jekyll/jekyll/blob/master/lib/jekyll/tags/include.rb, e.g., called include_example.
`{% include_example scala/org/apache/spark/examples/mllib/LocalVectorExample.scala %}`
Jekyll will find `examples/src/main/scala/org/apache/spark/examples/mllib/LocalVectorExample.scala` and pick code blocks marked "example" and replace code block in 
`{% highlight %}`
 in the markdown. 

See more sub-tasks in parent ticket: https://issues.apache.org/jira/browse/SPARK-11337

### CODE REVIEW

**Comment by mengxr** [comment]
ok to test

**Comment by mengxr** [comment]
cc @yinxusen

**Comment by yinxusen** [comment]
@keypointt Examples in the PR are all small ones. I am not sure whether we merge them or not. Either we use this PR https://github.com/apache/spark/pull/9430 to rewrite it, or we just leave this markdown file unchanged. @mengxr What do you think about it?

**Comment by srowen** [comment]
What's the resolution here -- just leave these as-is?

**Comment by yinxusen** [comment]
@keypointt How about we close this for now? There are too many small example codes. If we need all example codes out of markdown files, we can reopen it then. Thanks so much and sorry about that!

**Comment by keypointt** [comment]
@yinxusen sure, no problem. I'm closing it.

**Pull request closed without merging**
