### PR TITLE
[SPARK-19606][MESOS] Support constraints in spark-dispatcher

### PR DESCRIPTION
**Pull request by philipphoffmann**
The `MesosClusterScheduler` doesn't handle the `spark.mesos.constraints`
setting (as opposed to `MesosCoarseGrainedSchedulerBackend`).

## What changes were proposed in this pull request?

This commit introduces the necessary changes to handle the offer
constraints.

## How was this patch tested?

unit test

### CODE REVIEW

**Comment by skonto** [comment]
Please fix the title for the PR and include the related jira issue.

**Comment by philipphoffmann** [comment]
Created a Jira and linked it

**Comment by philipphoffmann** [comment]
rebase to master

**Comment by aroundthecode** [comment]
Any hope to see this resolved ?

**Pull request closed without merging**
