### PR TITLE
[SPARK-12363][Mllib][Backport-1.3] Remove setRun and fix PowerIterationClustering failed test

### PR DESCRIPTION
**Pull request by viirya**
## What changes were proposed in this pull request?

Backport JIRA-SPARK-12363 to branch-1.3.
## How was the this patch tested?

Unit test.

cc @mengxr

### CODE REVIEW

**Comment by viirya** [comment]
retest this please.

**Comment by viirya** [comment]
Don't know why test_reduce_by_key_and_window_with_none_invFunc in pyspark/streaming/tests.py is failed. This PR doesn't touch streaming code...

**Comment by mengxr** [comment]
test this please

**Comment by viirya** [comment]
It failed at the same streaming python test. I will run that test locally with clear branch-1.3 codebase to see if it can pass.

**Comment by viirya** [comment]
Roughly check the git log, I found that the failed test is committed in latest commit at branch-1.3.

**Comment by viirya** [comment]
This test fails at clearly checkouted branch-1.3 codebase. We should open another PR to fix it...

**Comment by viirya** [comment]
Open #11339 for the failed test.

**Comment by mengxr** [comment]
test this please

**Comment by viirya** [comment]
retest this please.

**Comment by mengxr** [comment]
The build actually passed. I'm merging this one in. Thanks for backporting the fix!

**Comment by viirya** [comment]
@mengxr Thanks!

**Pull request closed without merging**
