### PR TITLE
[SPARK-30644][SQL][TEST] Remove query index from the golden files of SQLQueryTestSuite	

### PR DESCRIPTION
**Pull request by gatorsmile**
### What changes were proposed in this pull request?

This PR is to remove query index from the golden files of SQLQueryTestSuite	

### Why are the changes needed?

Because the SQLQueryTestSuite's golden files have the query index for each query, removal of any query statement [except the last one] will generate many unneeded difference. This will make code review harder. The number of changed lines is misleading. 

### Does this PR introduce any user-facing change?
No

### How was this patch tested?
N/A

### CODE REVIEW

**Comment by gatorsmile** [comment]
cc @dongjoon-hyun @maropu

**Comment by dongjoon-hyun** [comment]
Ya. I agree that this causes too many meaningless diff although the original intention was good.

**Comment by maropu** [comment]
Yeah, it looks reasonable to me. We still need `-- !query` and `-- !query output` as separators? It seems PgSQL has such a separator in the golden files, e.g., : https://github.com/postgres/postgres/blob/REL_12_STABLE/src/test/regress/expected/groupingsets.out

**Comment by gatorsmile** [comment]
I think the separators are still needed. 

```
select grouping(a), a, array_agg(b),
       rank(a) within group (order by b nulls first),
       rank(a) within group (order by b nulls last)
  from (values (1,1),(1,4),(1,5),(3,1),(3,2)) v(a,b)
 group by rollup (a) order by a;
 grouping | a |  array_agg  | rank | rank 
----------+---+-------------+------+------
        0 | 1 | {1,4,5}     |    1 |    1
        0 | 3 | {1,2}       |    3 |    3
        1 |   | {1,4,5,1,2} |    1 |    6
(3 rows)
```

The PgSQL golden files look cleaner, but it only shows the output column names, but does not output the column data types.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Merged to master.
Thank you, @gatorsmile and @maropu .

**Review by HyukjinKwon — COMMENTED** [review]
LGTM too

**Comment by maropu** [comment]
yea, it looks fine. late LGTM.

**Pull request closed without merging**
