### PR TITLE
Revert "[SPARK-22938][SQL][FOLLOWUP] Assert that SQLConf.get is acces…

### PR DESCRIPTION
**Pull request by cloud-fan**
…sed only on the driver"

This reverts commit a4206d58e05ab9ed6f01fee57e18dee65cbc4efc.

This is from https://github.com/apache/spark/pull/21299 and to ease the review of it.

### CODE REVIEW

**Comment by cloud-fan** [comment]
cc @gatorsmile @viirya @jiangxb1987

**Comment by gatorsmile** [comment]
LGTM

**Comment by HyukjinKwon** [comment]
lgtm too

**Comment by HyukjinKwon** [comment]
LGTM too

**Comment by jiangxb1987** [comment]
Personally I feel it should be safe to do the revert since we have a better approach, but I'd prefer to hear what @squito think about this.

**Comment by cloud-fan** [comment]
to unblock the improvement PR, I'm going to merge it first and rebase that PR. I will still keep the driver-side check for `SparkSession`, which is what @squito concerned before.

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Comment by squito** [comment]
sure this is fine, but we'll see the flakiness back in the builds till https://github.com/apache/spark/pull/21299 is merged, right?

**Pull request closed without merging**
