### PR TITLE
SPARK-7441 Implement microbatch functionality so that Spark Streaming can process a large backlog of existing files discovered in batch in smaller batches

### PR DESCRIPTION
**Pull request by emres**
Implement microbatch functionality so that Spark Streaming can process a huge backlog of existing files discovered in batch in smaller batches.

Spark Streaming can process already existing files in a directory, and depending on the value of "spark.streaming.minRememberDuration" (60 seconds by default, see [SPARK-3276](https://issues.apache.org/jira/browse/SPARK-3276) for more details), this might mean that a Spark Streaming application can receive thousands, or hundreds of thousands of files within the first batch interval. This, in turn, leads to something like a 'flooding' effect for the streaming application, that tries to deal with a huge number of existing files in a single batch interval.

We will propose a very simple change to `org.apache.spark.streaming.dstream.FileInputDStream`, so that, based on a configuration property such as `spark.streaming.microbatch.size`, it will either keep its default behavior when `spark.streaming.microbatch.size` will have the default value of 0 (meaning as many as has been discovered as new files in the current batch interval), or will process new files in groups of `spark.streaming.microbatch.size` (e.g. in groups of 100s).

We have tested this patch in one of our customers, and it's been running successfully for weeks (e.g. there were cases where our Spark Streaming application was stopped, and in the meantime tens of thousands file were created in a directory, and our Spark Streaming application had to process those existing files after it was started).

### CODE REVIEW

**Comment by andrewor14** [comment]
ok to test. @tdas

**Comment by tdas** [comment]
This does not have any unit tests. Can you add some unit tests to this PR?

**Comment by andrewor14** [comment]
@emres are you still actively working on this? Mind addressing @tdas' comments to add unit tests?

**Comment by andrewor14** [comment]
Let's close this patch for now since there hasn't been activity for more than 3 months. We can always re-open it later if there's more interest.

**Comment by rxin** [comment]
I'm going to close this pull request. If this is still relevant and you are interested in pushing it forward, please open a new pull request. Thanks!

**Comment by michellemay** [comment]
Can we reopen this PR ?

**Pull request closed without merging**
