### PR TITLE
[SPARK-20576][SQL] Support generic hint function in Dataset/DataFrame

### PR DESCRIPTION
**Pull request by rxin**
## What changes were proposed in this pull request?
We allow users to specify hints (currently only "broadcast" is supported) in SQL and DataFrame. However, while SQL has a standard hint format (/*+ ... */), DataFrame doesn't have one and sometimes users are confused that they can't find how to apply a broadcast hint. This ticket adds a generic hint function on DataFrame that allows using the same hint on DataFrames as well as SQL.

As an example, after this patch, the following will apply a broadcast hint on a DataFrame using the new hint function:

```
df1.join(df2.hint("broadcast"))
```

## How was this patch tested?
Added a test case in DataFrameJoinSuite.

### CODE REVIEW

**Comment by gatorsmile** [comment]
LGTM pending Jenkins

**Comment by rxin** [comment]
Actually somebody should add the Python / R wrapper.

cc @felixcheung

**Comment by cloud-fan** [comment]
LGTM

**Comment by zero323** [comment]
> Actually somebody should add the Python / R wrapper.

I can add both, once it is merged.

**Comment by felixcheung** [comment]
just a thought - `hint` sounds fairly generic, especially in R as `hint(df, ...)`

**Comment by rxin** [comment]
Merging in master/branch-2.2.

**Comment by rxin** [comment]
@felixcheung do you worry about conflicts?

**Comment by rxin** [comment]
BTW I filed follow-up tickets for Python/R at https://issues.apache.org/jira/browse/SPARK-20576

**Pull request closed without merging**
