### PR TITLE
[SPARK-45111][BUILD] Upgrade maven to 3.9.4

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
    This PR aims to upgrade Maven to 3.8.8 from 3.9.4.
    
### Why are the changes needed?
The new version [lift JDK minimum to JDK 8](https://issues.apache.org/jira/browse/MNG-7452) and [make the build work on JDK 20](https://issues.apache.org/jira/browse/MNG-7743) . It also brings a series of bug fixes, such as [Fix deadlock during forked lifecycle executions](https://issues.apache.org/jira/browse/MNG-7487), along with a number of new optimizations like [Profile activation by packaging](https://issues.apache.org/jira/browse/MNG-6609). On the other hand, the new version replaces 'Wagon' with 'native http' as the new [Maven Resolver transport](https://maven.apache.org/guides/mini/guide-resolver-transport.html), coupled with a range of targeted performance enhancements（See the upgrades related to Maven Resolver）.
    
For other updates, refer to the corresponding release notes:
    
- https://maven.apache.org/docs/3.9.0/release-notes.html | https://github.com/apache/maven/releases/tag/maven-3.9.0
- https://maven.apache.org/docs/3.9.1/release-notes.html | https://github.com/apache/maven/releases/tag/maven-3.9.1
- https://maven.apache.org/docs/3.9.2/release-notes.html | https://github.com/apache/maven/releases/tag/maven-3.9.2
- https://maven.apache.org/docs/3.9.3/release-notes.html | https://github.com/apache/maven/releases/tag/maven-3.9.3
- https://maven.apache.org/docs/3.9.4/release-notes.html | https://github.com/apache/maven/releases/tag/maven-3.9.4
    
### Does this PR introduce _any_ user-facing change?
No
    
### How was this patch tested?
    
- Pass GitHub Actions
- Manual test :
    
run `build/mvn -version` wll trigger download `apache-maven-3.9.4-bin.tar.gz`
    
```
exec: curl --silent --show-error -L https://www.apache.org/dyn/closer.lua/maven/maven-3/3.9.4/binaries/apache-maven-3.9.4-bin.tar.gz?action=download
```
    
### Was this patch authored or co-authored using generative AI tooling?
No

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
So, is it good, @LuciferYang ?

**Comment by srowen** [comment]
LGTM

**Comment by LuciferYang** [comment]
Seems this version is okay, but let me run more tests just to be sure. @dongjoon-hyun @srowen

**Comment by LuciferYang** [comment]
I think this one is ready to go

**Review by dongjoon-hyun — COMMENTED** [review]
+1, LGTM. Thank you.

**Review by dongjoon-hyun — COMMENTED** [review]
BTW, for the record, Maven has been working with Java 21-ea already.

The JIRA mentioned in this PR is about adding Java 20 to GitHub Action Java matrix and to adjust their test code, `TestRepositoryConnector.java`. Given that, there was no actual issues to the Java 20+ users.

- https://issues.apache.org/jira/browse/MNG-7743
- https://github.com/apache/maven/pull/1065

**Comment by LuciferYang** [comment]
Thanks @srowen 
Thanks for your correction. @dongjoon-hyun

**Pull request closed without merging**
