### PR TITLE
[SPARK-16193] [TESTS] Address flaky ExternalAppendOnlyMapSuite spilling tests

### PR DESCRIPTION
**Pull request by srowen**
## What changes were proposed in this pull request?

Make spill tests wait until job has completed before returning the number of stages that spilled
## How was this patch tested?

Existing Jenkins tests.

### CODE REVIEW

**Comment by srowen** [comment]
See also https://github.com/apache/spark/pull/9124 and CC @andrewor14

**Comment by andrewor14** [comment]
LGTM

**Comment by srowen** [comment]
Jenkins retest this please

**Comment by srowen** [comment]
Merged to master/2.0/1.6

**Pull request closed without merging**
