### PR TITLE
[SPARK-19421][ML][PySpark] Remove numClasses and numFeatures methods in LinearSVC

### PR DESCRIPTION
**Pull request by zhengruifeng**
## What changes were proposed in this pull request?
Methods `numClasses` and `numFeatures` in LinearSVCModel are already usable by inheriting `JavaClassificationModel`
we should not explicitly add them.

## How was this patch tested?
existing tests

### CODE REVIEW

**Comment by zhengruifeng** [comment]
ping @jkbradley

**Comment by wangmiao1981** [comment]
@zhengruifeng Thanks for pointing it out. I think we should remove it. LGTM

**Comment by holdenk** [comment]
The original PR was merged a few days ago, would you be OK with making a new JIRA just to avoid confusion? You can make it related to the previous JIRA. But otherwise looks good to me.

**Comment by zhengruifeng** [comment]
@holdenk I created another jira to track this issue. Thanks all for revewing!

**Comment by zhengruifeng** [comment]
ping @jkbradley

**Comment by holdenk** [comment]
This looks good, merging into master. Thanks for doing this cleanup work @zhengruifeng :)

**Pull request closed without merging**
