### PR TITLE
[SPARK-8605] Exclude files in StreamingContext. textFileStream

### PR DESCRIPTION
**Pull request by ConcurrencyPractitioner**
## What changes were proposed in this pull request?

In this PR, a extra boolean expression was added to test if a regex was present. If returned true, then we exclude the file.

## How was this patch tested?

No tests were added.

### CODE REVIEW

**Comment by ConcurrencyPractitioner** [comment]
Jenkins test this please

**Comment by jerryshao** [comment]
> a extra boolean expression was added to test if a regex was present.

Can you please explain what's the meaning of "if a regex was present"?

Seems the fix is not so necessary. If you want to filter out some temp files, you can write your own `filter` instead of using Spark Streaming's default one.

**Comment by ConcurrencyPractitioner** [comment]
@jerryshao  In Spark Streaming, I think ```.tmp``` is used as a suffix to indicate that the object was a file, although I do not know if this is universal.

**Comment by gaborgsomogyi** [comment]
Don't really understand the issue itself. Which filesystem used this case? Why is it not possible to use Hadoop-compatible filesystem like HDFS for instance? This supports atomic rename. [See here](https://hadoop.apache.org/docs/stable/hadoop-project-dist/hadoop-common/filesystem/introduction.html#Atomicity)

**Pull request closed without merging**
