### PR TITLE
[Minor][Doc] Fix typo

### PR DESCRIPTION
**Pull request by kiszk**
## What changes were proposed in this pull request?

This PR fixes typo regarding `auxiliary verb + verb[s]`. This is a follow-on of #21956.

## How was this patch tested?

N/A

### CODE REVIEW

**Comment by kiszk** [comment]
cc @HyukjinKwon

**Comment by kiszk** [comment]
retest this please

**Review by HyukjinKwon — APPROVED** [review]
LGTM

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
