### PR TITLE
[SPARK-49550][BUILD] Upgrade Hadoop to 3.4.1

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to upgrade Apache Hadoop to 3.4.1.

### Why are the changes needed?

To bring the latest bug fixes.

- http://hadoop.apache.org/docs/r3.4.1/index.html
- http://hadoop.apache.org/docs/r3.4.1/hadoop-project-dist/hadoop-common/release/3.4.1/RELEASENOTES.3.4.1.html
- http://hadoop.apache.org/docs/r3.4.1/hadoop-project-dist/hadoop-common/release/3.4.1/CHANGELOG.3.4.1.html 

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the CIs.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
This is blocked by 
- https://github.com/apache/hadoop/pull/7079

**Comment by dongjoon-hyun** [comment]
For the record, all tests passed except K8s Integration Tests trying to download 3.4.1 directly. So, I casted +1 for Apache Hadoop 3.4.1 RC3.
```
[info] Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: org.apache.hadoop#hadoop-aws;3.4.1: not found]
```

**Review by viirya — APPROVED** [review]
Pending CI

**Comment by dongjoon-hyun** [comment]
Thank you, @viirya . Yes, this is tested already but I retriggered this because the master branch was broken recently and I recovered a few hours ago. I'll make it sure that all tests pass.

Screenshot 2024-10-18 at 14 27 10

**Comment by dongjoon-hyun** [comment]
All tests passed. Merged to master for Apache Spark 4.0.0 on February 2025.

**Pull request closed without merging**
