### PR TITLE
[SPARK-31014][CORE][3.0] InMemoryStore: remove key from parentToChildrenMap when removing key from CountingRemoveIfForEach

### PR DESCRIPTION
**Pull request by HeartSaVioR**
### What changes were proposed in this pull request?

This patch addresses missed spot on SPARK-30964 (#27716) - SPARK-30964 added secondary index which defines the relationship between parent - children and able to operate all children for given parent faster.

While SPARK-30964 handled the addition and deletion of secondary index in InstanceList properly, it missed to add code to handle deletion of secondary index in CountingRemoveIfForEach, resulting to the leak of indices. This patch adds the deletion of secondary index in CountingRemoveIfForEach.

### Why are the changes needed?

Described above.

### Does this PR introduce any user-facing change?

No.

### How was this patch tested?

N/A, as relevant field and class are marked as private, and it cannot be checked in higher level. I'm not sure we want to adjust scope to add a test.

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
cc. @gengliangwang

**Review by gengliangwang — APPROVED** [review]

**Comment by HeartSaVioR** [comment]
```
[error] /home/jenkins/workspace/SparkPullRequestBuilder@4/sql/catalyst/src/main/scala/org/apache/spark/sql/internal/SQLConf.scala:385: value version is not a member of org.apache.spark.internal.config.ConfigBuilder
[error] possible cause: maybe a semicolon is missing before `value version'?
[error]     .version("3.0.0")
[error]      ^
[error] one error found
```

Weird failure. Will check the recent branch-3.0.

**Comment by HeartSaVioR** [comment]
OK we should be very careful while cherry-picking commit to `branch-3.0` as they're now diverged. The build failure is due to this: `.version` is not available in `branch-3.0`.

I'll raise a PR to fix it soon.

**Comment by HeartSaVioR** [comment]
#27826 to fix build failure.

**Comment by dongjoon-hyun** [comment]
Thanks, @HeartSaVioR . The PR is merged.

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by HeartSaVioR** [comment]
retest this, please

**Comment by HeartSaVioR** [comment]
retest this, please

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @HeartSaVioR and @gengliangwang .
Merged to 3.0.

**Comment by HeartSaVioR** [comment]
Thanks for reviewing and merging!

**Pull request closed without merging**
