### PR TITLE
[SPARK-42158][SQL][3.4] Integrate _LEGACY_ERROR_TEMP_1003 into FIELD_NOT_FOUND

### PR DESCRIPTION
**Pull request by itholic**
### What changes were proposed in this pull request?

backport for https://github.com/apache/spark/pull/39706

### Why are the changes needed?

We should want to include PRs related to error classes into Spark 3.4.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

The CI should pass.

### CODE REVIEW

**Comment by itholic** [comment]
Reopened wrong cherry pick(https://github.com/apache/spark/pull/39828) here.
@cloud-fan @MaxGekk @HyukjinKwon FYI

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
Hi, @itholic . If you don't mind, please change the PR title style to have `[3.4]` at the end of tags. :) 

```
$ git log --oneline --author=itholic -n6
b3ebb69e38 (HEAD -> branch-3.4, apache/branch-3.4) [SPARK-42232][SQL] Rename error class: `UNSUPPORTED_FEATURE.JDBC_TRANSACTION`
8dae1245e3 [3.4][SPARK-41490][SQL] Assign name to _LEGACY_ERROR_TEMP_2441
03b2a7da77 [3.4][SPARK-41489][SQL] Assign name to _LEGACY_ERROR_TEMP_2415
c421b51943 [3.4][SPARK-41488][SQL] Assign name to _LEGACY_ERROR_TEMP_1176 (and 1177)
c4f750b1e2 [3.4][SPARK-42229][CORE] Migrate `SparkCoreErrors` into error classes
5b84b679d8 [3.4][SPARK-42239][SQL] Integrate `MUST_AGGREGATE_CORRELATED_SCALAR_SUBQUERY`
```

**Comment by itholic** [comment]
Updated.
Thanks @dongjoon-hyun !

**Comment by cloud-fan** [comment]
thanks, merging to 3.4!

**Review by dongjoon-hyun — COMMENTED** [review]
Thank you, @itholic and @cloud-fan .

**Pull request closed without merging**
