### PR TITLE
[SPARK-44585][MLLIB] Fix warning condition in MLLib RankingMetrics ndcgAk

### PR DESCRIPTION
**Pull request by guilhem-depop**
### What changes were proposed in this pull request?

This PR fixes the condition to raise the following warning in MLLib's RankingMetrics ndcgAk function: "# of ground truth set and # of relevance value set should be equal, check input data"

The logic for raising warnings is faulty at the moment: it raises a warning if the `rel` input is empty and `lab.size` and `rel.size` are not equal.

The logic should be to raise a warning if `rel` input is **not empty** and `lab.size` and `rel.size` are not equal.

This warning was added in the following PR: https://github.com/apache/spark/pull/36843

### Why are the changes needed?

With the current logic, RankingMetrics will:
- raise incorrect warning when a user is using it in the "binary" mode (i.e. no relevance values in the input)
- not raise warning (that could be necessary) when the user is using it in the "non-binary" model (i.e. with relevance values in the input)

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
No change made to the test suite for RankingMetrics: https://github.com/uchiiii/spark/blob/a172172329cc78b50f716924f2a344517deb71fc/mllib/src/test/scala/org/apache/spark/mllib/evaluation/RankingMetricsSuite.scala

### CODE REVIEW

**Comment by guilhem-depop** [comment]
FYI @uchiiii @srowen (since you implemented/reviewed https://github.com/apache/spark/pull/36843)

**Comment by srowen** [comment]
Also, this needs a JIRA, and needs to be connected in the title
https://spark.apache.org/contributing.html

**Comment by guilhem-depop** [comment]
@srowen here's the ticket: https://issues.apache.org/jira/browse/SPARK-44585

**Review by srowen — APPROVED** [review]

**Comment by srowen** [comment]
Merged to master/3.5/3.4

**Pull request closed without merging**
