### PR TITLE
[SPARK-48586][SS][FOLLOWUP] RocksDB and RocksDBFileManager code style changes

### PR DESCRIPTION
**Pull request by riyaverm-db**
### What changes were proposed in this pull request?
This is a follow up PR to #46942 addressing the style changes that were requested. 

### Why are the changes needed?
Style changes added.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Not applicable.

### Was this patch authored or co-authored using generative AI tooling?
No

### CODE REVIEW

**Review by HeartSaVioR — APPROVED** [review]
+1 pending CI

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by HyukjinKwon** [comment]
It has a conflict in 3.5 and 3.4. Mind creating a backport PR @riyaverm-db ?

**Comment by HeartSaVioR** [comment]
Backport PR for 3.5 contains this followup fix, so we just need to merge that PR to be done.

**Pull request closed without merging**
