### PR TITLE
[SPARK-10169] [SQL] [BRANCH-1.4] Partial aggregation's plan is wrong when a grouping expression is used as an argument of the aggregate fucntion

### PR DESCRIPTION
**Pull request by yhuai**
https://issues.apache.org/jira/browse/SPARK-10169

### CODE REVIEW

**Comment by yhuai** [comment]
hmm. seems it triggers another bug?

btw, the failed test is `org.apache.spark.sql.SQLQuerySuite.grouping on nested fields`.

**Comment by cloud-fan** [comment]
Before 1.5, `ExtractValue` chain may have intermedia and unnecessary `Alias`es inside it, so we trim `Alias`es upon `ExtractValue` before compare 2 `Expression`s in a lot places including [here](https://github.com/apache/spark/pull/8379/files#diff-820e654df2a5133c0f86c17e2fc5512eR165).
However, when we use `transformDown`, we may loose the top level `Alias`. For example, `'a.getField("b")` is a grouping expression and `'a.getField("b").as("attribute")` is an aggregate expression, 
with `transformDown`, the rewritten aggregate expression will be `'a.getField("b")` which is wrong.

The commit to fix the wrong `Alias` trimming is https://github.com/apache/spark/commit/da7bbb9435dae9a3bedad578599d96ea858f349e, which is not easy to backport I think. So maybe we need to add some ugly code to hadle the top level `Alias`es specially.

**Comment by cloud-fan** [comment]
btw I have sent a PR on your branch, let's see if that can work :)

**Comment by marmbrus** [comment]
LGTM

**Comment by marmbrus** [comment]
Thanks guys, merged!

**Pull request closed without merging**
