### PR TITLE
[SPARK-34307][SQL] TakeOrderedAndProjectExec avoid shuffle if input rdd has single partition

### PR DESCRIPTION
**Pull request by zhengruifeng**
### What changes were proposed in this pull request?
when the child rdd has only one partition, skip the shuffle

### Why are the changes needed?
avoid unnecessary shuffle

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
existing testsuites

### CODE REVIEW

**Comment by zhengruifeng** [comment]
testCode:
```
val df = spark.read.format("libsvm").load("/d0/Dev/Opensource/spark/data/mllib/sample_multiclass_classification_data.txt")

df.rdd.getNumPartitions

df.sort('label).limit(100).show
```

master:
limit-job-2021-02-01-12-48-06

limit-master-2021-02-01-12-47-29


this PR:
limit-job-pr-2021-02-01-13-00-41

limit-pr-2021-02-01-13-01-40

**Review by cloud-fan — APPROVED** [review]

**Comment by cloud-fan** [comment]
We may have more operators that adding shuffle in the `doExecute` method instead of the planner, but this fix looks correct to me. Also cc @viirya @maropu

**Review by HyukjinKwon — APPROVED** [review]

**Review by viirya — APPROVED** [review]

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Comment by zhengruifeng** [comment]
thanks all for reviewing!

> We may have more operators that adding shuffle in the doExecute method instead of the planner

I will look for other similar operators that may skip shuffle like this PR.

**Comment by maropu** [comment]
late lgtm

**Pull request closed without merging**
