### PR TITLE
[SPARK-16303][DOCS][EXAMPLES] Minor Scala/Java example update

### PR DESCRIPTION
**Pull request by liancheng**
## What changes were proposed in this pull request?

This PR moves one and the last hard-coded Scala example snippet from the SQL programming guide into `SparkSqlExample.scala`. It also renames all Scala/Java example files so that all "Sql" in the file names are updated to "SQL".
## How was this patch tested?

Manually verified the generated HTML page.

### CODE REVIEW

**Comment by yhuai** [comment]
LGTM. Can we reuse a existing jira number?

**Comment by rxin** [comment]
FWIW I think it'd be better to name the file SparkSQLExamples, rather than SparkSqlExamples. It just feels weird to have SparkSql.  And I'm talking about both Scala and Python.

**Comment by liancheng** [comment]
Reused JIRA number SPARK-16303 and renamed Scala/Java example file names. Python examples are not being updated to use the `include_example` tag yet. The PR (#14098) is still in WIP status.

**Comment by yhuai** [comment]
Thanks. Merging to master and branch 2.0.

**Pull request closed without merging**
