### PR TITLE
[SPARK-11342] [TESTS] Allow to set hadoop profile when running dev/ru…

### PR DESCRIPTION
**Pull request by zjffdu**
…n_tests

### CODE REVIEW

**Comment by zjffdu** [comment]
Test Failed due to network issue
```
ERROR: Timeout after 15 minutes
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from https://github.com/apache/spark.git
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:735)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:983)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1016)
	at hudson.scm.SCM.checkout(SCM.java:485)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1277)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:610)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:532)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:408)
Caused by: hudson.plugins.git.GitException: Command "git fetch --tags --progress https://github.com/apache/spark.git +refs/pull/9295/*:refs/remotes/origin/pr/9295/*" returned status code 143:
```

**Comment by srowen** [comment]
OK, can't hurt I suppose. LGTM.

**Comment by srowen** [comment]
Jenkins, test this please

**Comment by srowen** [comment]
Clearly, the tests still ran per usual, which was the necessary thing to test. The rest is a spurious failure. I'm going to merge.

**Pull request closed without merging**
