### PR TITLE
[SPARK-44751][SQL][FOLLOWUP] Change `xmlExpressions.scala` package name

### PR DESCRIPTION
**Pull request by Hisoka-X**
### What changes were proposed in this pull request?
The `xmlExpressions.scala` file in package `org.apache.spark.sql.catalyst.expressions`, but it package name is `org.apache.spark.sql.catalyst.expressions.xml`.

### Why are the changes needed?
Fix not correct package name.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
exist test.

### Was this patch authored or co-authored using generative AI tooling?
No

### CODE REVIEW

**Review by LuciferYang — DISMISSED** [review]
+1, LGTM

**Review by dongjoon-hyun — COMMENTED** [review]
Hi, @Hisoka-X . This should be a follow-up of SPARK-44751 instead of `MINOR`.

In addition, this broke the compilation due to the following. Could you fix it?

```
[error] /home/runner/work/spark/spark/sql/core/src/main/scala/org/apache/spark/sql/functions.scala:33:54: Unused import
[error] import org.apache.spark.sql.catalyst.expressions.xml._
```

**Comment by sandip-db** [comment]
> Also, we need to check the original intention, @Hisoka-X . If the original intention is to create a new namespace `xml`, we need to create a directory and move this file into it instead of this PR.
> 

This PR is fine. It was a slippage. I didn't intend to create a new namespace `xml`.

**Review by cloud-fan — APPROVED** [review]

**Review by HyukjinKwon — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
Thank you for the confirmation, @sandip-db .

+1, LGTM.

**Review by dongjoon-hyun — COMMENTED** [review]
Oh, the unit test failure looks interesting. Could you fix the unit test failure, @Hisoka-X ?

```
ExpressionsSchemaSuite:
[info] - Check schemas for expression examples *** FAILED *** (1 second, 440 milliseconds)
[info]   "SELECT s[ec(0])" did not equal "SELECT s[chema_of_xml('<p><a>1</a></p>'])" SQL query did not match (ExpressionsSchemaSuite.scala:183)
[info]   Analysis:
[info]   "SELECT s[ec(0])" -> "SELECT s[chema_of_xml('<p><a>1</a></p>'])"
```

**Comment by LuciferYang** [comment]
Need re-generate `sql-expression-schema.md` due to the package name changed.

```
diff --git a/sql/core/src/test/resources/sql-functions/sql-expression-schema.md b/sql/core/src/test/resources/sql-functions/sql-expression-schema.md
index d21ceaeb14b..4fd493d1a3c 100644
--- a/sql/core/src/test/resources/sql-functions/sql-expression-schema.md
+++ b/sql/core/src/test/resources/sql-functions/sql-expression-schema.md
@@ -274,6 +274,7 @@
 | org.apache.spark.sql.catalyst.expressions.RowNumber | row_number | SELECT a, b, row_number() OVER (PARTITION BY a ORDER BY b) FROM VALUES ('A1', 2), ('A1', 1), ('A2', 3), ('A1', 1) tab(a, b) | struct<a:string,b:int,row_number() OVER (PARTITION BY a ORDER BY b ASC NULLS FIRST ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW):int> |
 | org.apache.spark.sql.catalyst.expressions.SchemaOfCsv | schema_of_csv | SELECT schema_of_csv('1,abc') | struct<schema_of_csv(1,abc):string> |
 | org.apache.spark.sql.catalyst.expressions.SchemaOfJson | schema_of_json | SELECT schema_of_json('[{"col":0}]') | struct<schema_of_json([{"col":0}]):string> |
+| org.apache.spark.sql.catalyst.expressions.SchemaOfXml | schema_of_xml | SELECT schema_of_xml('<p><a>1</a></p>') | struct<schema_of_xml(<p><a>1</a></p>):string> |
 | org.apache.spark.sql.catalyst.expressions.Sec | sec | SELECT sec(0) | struct<SEC(0):double> |
 | org.apache.spark.sql.catalyst.expressions.Second | second | SELECT second('2009-07-30 12:58:59') | struct<second(2009-07-30 12:58:59):int> |
 | org.apache.spark.sql.catalyst.expressions.SecondsToTimestamp | timestamp_seconds | SELECT timestamp_seconds(1230219000) | struct<timestamp_seconds(1230219000):timestamp> |
@@ -365,6 +366,7 @@
 | org.apache.spark.sql.catalyst.expressions.WeekOfYear | weekofyear | SELECT weekofyear('2008-02-20') | struct<weekofyear(2008-02-20):int> |
 | org.apache.spark.sql.catalyst.expressions.WidthBucket | width_bucket | SELECT width_bucket(5.3, 0.2, 10.6, 5) | struct<width_bucket(5.3, 0.2, 10.6, 5):bigint> |
 | org.apache.spark.sql.catalyst.expressions.WindowTime | window_time | SELECT a, window.start as start, window.end as end, window_time(window), cnt FROM (SELECT a, window, count(*) as cnt FROM VALUES ('A1', '2021-01-01 00:00:00'), ('A1', '2021-01-01 00:04:30'), ('A1', '2021-01-01 00:06:00'), ('A2', '2021-01-01 00:01:00') AS tab(a, b) GROUP by a, window(b, '5 minutes') ORDER BY a, window.start) | struct<a:string,start:timestamp,end:timestamp,window_time(window):timestamp,cnt:bigint> |
+| org.apache.spark.sql.catalyst.expressions.XmlToStructs | from_xml | SELECT from_xml('<p><a>1</a><b>0.8</b></p>', 'a INT, b DOUBLE') | struct<from_xml(<p><a>1</a><b>0.8</b></p>):struct<a:int,b:double>> |
 | org.apache.spark.sql.catalyst.expressions.XxHash64 | xxhash64 | SELECT xxhash64('Spark', array(123), 2) | struct<xxhash64(Spark, array(123), 2):bigint> |
 | org.apache.spark.sql.catalyst.expressions.Year | year | SELECT year('2016-07-30') | struct<year(2016-07-30):int> |
 | org.apache.spark.sql.catalyst.expressions.ZipWith | zip_with | SELECT zip_with(array(1, 2, 3), array('a', 'b', 'c'), (x, y) -> (y, x)) | struct<zip_with(array(1, 2, 3), array(a, b, c), lambdafunction(named_struct(y, namedlambdavariable(), x, namedlambdavariable()), namedlambdavariable(), namedlambdavariable())):array<struct<y:string,x:int>>> |
@@ -426,7 +428,6 @@
 | org.apache.spark.sql.catalyst.expressions.aggregate.VariancePop | var_pop | SELECT var_pop(col) FROM VALUES (1), (2), (3) AS tab(col) | struct<var_pop(col):double> |
 | org.apache.spark.sql.catalyst.expressions.aggregate.VarianceSamp | var_samp | SELECT var_samp(col) FROM VALUES (1), (2), (3) AS tab(col) | struct<var_samp(col):double> |
 | org.apache.spark.sql.catalyst.expressions.aggregate.VarianceSamp | variance | SELECT variance(col) FROM VALUES (1), (2), (3) AS tab(col) | struct<variance(col):double> |
-| org.apache.spark.sql.catalyst.expressions.xml.SchemaOfXml | schema_of_xml | SELECT schema_of_xml('<p><a>1</a></p>') | struct<schema_of_xml(<p><a>1</a></p>):string> |
 | org.apache.spark.sql.catalyst.expressions.xml.XPathBoolean | xpath_boolean | SELECT xpath_boolean('<a><b>1</b></a>','a/b') | struct<xpath_boolean(<a><b>1</b></a>, a/b):boolean> |
 | org.apache.spark.sql.catalyst.expressions.xml.XPathDouble | xpath_double | SELECT xpath_double('<a><b>1</b><b>2</b></a>', 'sum(a/b)') | struct<xpath_double(<a><b>1</b><b>2</b></a>, sum(a/b)):double> |
 | org.apache.spark.sql.catalyst.expressions.xml.XPathDouble | xpath_number | SELECT xpath_number('<a><b>1</b><b>2</b></a>', 'sum(a/b)') | struct<xpath_number(<a><b>1</b><b>2</b></a>, sum(a/b)):double> |
@@ -435,5 +436,4 @@
 | org.apache.spark.sql.catalyst.expressions.xml.XPathList | xpath | SELECT xpath('<a><b>b1</b><b>b2</b><b>b3</b><c>c1</c><c>c2</c></a>','a/b/text()') | struct<xpath(<a><b>b1</b><b>b2</b><b>b3</b><c>c1</c><c>c2</c></a>, a/b/text()):array<string>> |
 | org.apache.spark.sql.catalyst.expressions.xml.XPathLong | xpath_long | SELECT xpath_long('<a><b>1</b><b>2</b></a>', 'sum(a/b)') | struct<xpath_long(<a><b>1</b><b>2</b></a>, sum(a/b)):bigint> |
 | org.apache.spark.sql.catalyst.expressions.xml.XPathShort | xpath_short | SELECT xpath_short('<a><b>1</b><b>2</b></a>', 'sum(a/b)') | struct<xpath_short(<a><b>1</b><b>2</b></a>, sum(a/b)):smallint> |
-| org.apache.spark.sql.catalyst.expressions.xml.XPathString | xpath_string | SELECT xpath_string('<a><b>b</b><c>cc</c></a>','a/c') | struct<xpath_string(<a><b>b</b><c>cc</c></a>, a/c):string> |
-| org.apache.spark.sql.catalyst.expressions.xml.XmlToStructs | from_xml | SELECT from_xml('<p><a>1</a><b>0.8</b></p>', 'a INT, b DOUBLE') | struct<from_xml(<p><a>1</a><b>0.8</b></p>):struct<a:int,b:double>> |
\ No newline at end of file
+| org.apache.spark.sql.catalyst.expressions.xml.XPathString | xpath_string | SELECT xpath_string('<a><b>b</b><c>cc</c></a>','a/c') | struct<xpath_string(<a><b>b</b><c>cc</c></a>, a/c):string> |
\ No newline at end of file

```

**Comment by HyukjinKwon** [comment]
Build: https://github.com/Hisoka-X/spark/actions/runs/6311502792/job/17135609795

**Review by srowen — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by EnricoMi** [comment]
This is strange, calling into any SQL function in org.apache.spark.sql.functions fails for latest 4.0.0-SNAPSHOT

```
sum($"id")

java.lang.NoClassDefFoundError: org/apache/spark/sql/catalyst/expressions/xml/XmlToStructs

Cause: java.lang.ClassNotFoundException: org.apache.spark.sql.catalyst.expressions.xml.XmlToStructs
  at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
  at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
```

This works perfectly fine from the spark-shell but not from a Scala application that depends on the Spark SNAPSHOT jars.

I have no idea why `XmlToStructs` is being looked for in `org.apache.spark.sql.catalyst.expressions.xml`.

I have removed all caching of SNAPSHOT jars.

I have last seen this working on Sep 27th: https://github.com/G-Research/spark-extension/actions/runs/6330717992/job/17193860638
and first failing on Oct, 10th: https://github.com/G-Research/spark-extension/actions/runs/6419624422/job/17556921640#step:3:4482

**Comment by EnricoMi** [comment]
This is it, the spark-sql snapshot is outdated. I thought `sbt publishLocal` in Spark master would have fixed that for me.

Who is best to reach out to fix the snapshots? cc @HyukjinKwon

**Comment by cloud-fan** [comment]
cc @dongjoon-hyun as well. I'm also curious about how these processes are maintained. Do we have a bot to release the snapshot release?

**Comment by EnricoMi** [comment]
Looks like there is a GitHub workflow that publishes snapshots, and it is failing since Sep, 14th, producing inconsistent snapshots: https://github.com/apache/spark/actions/workflows/publish_snapshot.yml

**Comment by LuciferYang** [comment]
https://github.com/apache/spark/blob/0257b77528a3a0d0ba08df5363470e4bc5928b06/build/mvn#L39

By default, the peak memory usage for a full compile with Maven and Java 17 is about 6.1GB. Maybe we can try reducing the -Xmx from 4G to 3G to lower peak memory usage (peak memory usage with -Xmx3G is slightly more than 5G),  but reducing `-Xmx` will also result in about a 10% loss in compile performance.

**Comment by LuciferYang** [comment]
> https://github.com/apache/spark/blob/0257b77528a3a0d0ba08df5363470e4bc5928b06/build/mvn#L39
> 
> By default, the peak memory usage for a full compile with Maven and Java 17 is about 6.1GB. Maybe we can try reducing the -Xmx from 4G to 3G to lower peak memory usage (peak memory usage with -Xmx3G is slightly more than 5G), but reducing `-Xmx` will also result in about a 10% loss in compile performance.

The premise of this attempt is due to insufficient memory, causing the compile container to be killed. But here I also have a question, the compile container should have 7G of memory available, it doesn't seem to exceed this limit.

**Comment by HyukjinKwon** [comment]
We should fix https://github.com/apache/spark/actions/workflows/publish_snapshot.yml

**Comment by HyukjinKwon** [comment]
Made a quick PR that potentially can fix it.

**Comment by EnricoMi** [comment]
> We should fix https://github.com/apache/spark/actions/workflows/publish_snapshot.yml

The issue has been fixed by #43538, thanks!

**Pull request closed without merging**
