### PR TITLE
[SPARK-43255][SQL] Replace the error class _LEGACY_ERROR_TEMP_2020 by an internal error

### PR DESCRIPTION
**Pull request by JinHelin404**
### What changes were proposed in this pull request?

Change the error class_LEGACY_ERROR_TEMP_2022 to internal error as it cannot be accessed by public API.

### Why are the changes needed?

User experience improvement

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Tests already exist.

### Was this patch authored or co-authored using generative AI tooling?

No

### CODE REVIEW

**Comment by amaliujia** [comment]
If I am not wrong: `StaticInvoke` could trigger this error and `StaticInvoke` could be used by a user.

**Comment by amaliujia** [comment]
cc @MaxGekk

**Comment by eejbyfeldt** [comment]
@MaxGekk To me it seems correct to make it an internal error. I think the cases it could come up from using user defined types in the Scala API are meant to be captured earlier by other code and it failing with this would indicate a spark bug.

>  If I am not wrong: StaticInvoke could trigger this error and StaticInvoke could be used by a user?

> I saw in the past users use StaticInvoke in their library.

My understanding is that classes `org.apache.spark.sql.catalyst` were consider semi private/developer api.  But I have not really found the documentation where this is clarified so maybe I have misunderstood something. Anyway to me it does not seem realistic to provide good errors for all possible missuses of classes that live in there.

**Comment by MaxGekk** [comment]
@JinHelin404 Do you have an account at OSS JIRA: https://issues.apache.org/jira/browse/SPARK-43255? If so, please, leave a comment in the ticket (I will assign it to you) otherwise submit a request for the account.

**Comment by JinHelin404** [comment]
> @JinHelin404 Do you have an account at OSS JIRA: https://issues.apache.org/jira/browse/SPARK-43255? If so, please, leave a comment in the ticket (I will assign it to you) otherwise submit a request for the account.

@MaxGekk I have left a comment.

**Comment by MaxGekk** [comment]
+1, LGTM. Merging to master.
Thank you, @JinHelin404 and @eejbyfeldt @amaliujia for review.

**Pull request closed without merging**
