### PR TITLE
[SPARK-8657] [YARN] Fail to upload resource to viewfs

### PR DESCRIPTION
**Pull request by litao-buptsse**
Fail to upload resource to viewfs in spark-1.4
JIRA Link: https://issues.apache.org/jira/browse/SPARK-8657

### CODE REVIEW

**Comment by srowen** [comment]
OK to test

**Comment by litao-buptsse** [comment]
@srowen #7125 passes all tests. You can consider to merge it to master.

**Comment by srowen** [comment]
Please be patient, this will be dealt with when other issues are done.

**Comment by litao-buptsse** [comment]
@srowen :ok:

**Comment by litao-buptsse** [comment]
@srowen Thanks for your help :smiley:

**Pull request closed without merging**
