### PR TITLE
[DOCS]Update configuration.md

### PR DESCRIPTION
**Pull request by KraFusion**
changed $SPARK_HOME/conf/spark-default.conf to $SPARK_HOME/conf/spark-defaults.conf

no testing necessary as this was a change to documentation.

### CODE REVIEW

**Comment by KraFusion** [comment]
@HyukjinKwon the same instance did exist in the spark website repo, PR has been merged.
Not sure what to change the title to, the PR instructions don't cover simple typo fixes in documentation that don't have an associated JIRA.  Should I prefix the current title with [DOCS] ?

**Comment by srowen** [comment]
Huh OK I thought I looked and this had been fixed. Good catch. Also there's an instance in `cloud-integration.md`, worth fixing too.

**Review by felixcheung — APPROVED** [review]

**Comment by srowen** [comment]
Merged to master. For the future, a better title and bundling these in one PR would be preferable.

**Comment by KraFusion** [comment]
@srowen Thanks!
yes, my bad. next time I will bundle (better yet I will look for the same issue elsewhere in the docs), and I'll use a better title.

**Pull request closed without merging**
