### PR TITLE
[SPARK-8736] [ml] GBTRegressor should not threshold prediction

### PR DESCRIPTION
**Pull request by jkbradley**
Changed GBTRegressor so it does NOT threshold the prediction.  Added test which fails with bug but works after fix.

CC: @feynmanliang  @mengxr

### CODE REVIEW

**Comment by feynmanliang** [comment]
LGTM. Is there anything we can reference against to test correctness (rather than simply testing that it's not doing classification)?

**Comment by jkbradley** [comment]
It'd be good to test vs. another library, but it's a bit hard to find one which can run things exactly the same way.  I'll look around a bit.

**Comment by jkbradley** [comment]
The best libraries out there implement TreeBoost, which extends the basic GBT algorithm we have in Spark.  That's in JIRA form for now.  I'll leave the comparison as a to-do.

**Comment by mengxr** [comment]
Merged into master and branch-1.4. Thanks!

**Pull request closed without merging**
