### PR TITLE
[SPARK-44614][PYTHON][CONNECT] Add missing packages in setup.py

### PR DESCRIPTION
**Pull request by ueshin**
### What changes were proposed in this pull request?

Adds missing packages in `setup.py`.

### Why are the changes needed?

The following packages are not listed in `setup.py`.

- `pyspark.sql.connect.avro`
- `pyspark.sql.connect.client`
- `pyspark.sql.connect.streaming`
- `pyspark.ml.connect`

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

The existing tests.

### CODE REVIEW

**Comment by ueshin** [comment]
cc @HyukjinKwon @zhengruifeng @rangadi

**Review by HyukjinKwon — APPROVED** [review]

**Comment by ueshin** [comment]
Let's wait for #42250 for 3.5.

**Review by zhengruifeng — APPROVED** [review]

**Review by beliefer — APPROVED** [review]

**Comment by ueshin** [comment]
Let me merge this now as #42250 still fails.
For 3.5, #42257 that won't conflict with #42250.

**Comment by ueshin** [comment]
Merging to master.

**Pull request closed without merging**
