### PR TITLE
SPARK-5805 Fixed the type error in documentation.

### PR DESCRIPTION
**Pull request by emres**
Fixes SPARK-5805 : Fix the type error in the final example given in MLlib - Clustering documentation.

### CODE REVIEW

**Comment by mengxr** [comment]
LGTM.

**Comment by mengxr** [comment]
Merged into master and branch-1.3 (skipped Jenkins because this only contains doc changes.)

@emres This PR contains changes to GMM. It won't be able to merge into branch-1.2. Could you send a patch to branch-1.2? Thanks!

**Comment by emres** [comment]
I would gladly do that, but I'm not sure exactly how to send a patch to a
particular branch, e.g. branch-1.2

What I have done was simply to fork the original Spark repository, create a
new branch in my forked repository with the same name as JIRA issue number,
commit my change and just send a pull request via Github.

How can I send a patch to branch-1.2 after having done what I described
above?

--
Emre


On Fri, Feb 13, 2015 at 9:40 PM, Xiangrui Meng <notifications@github.com>
wrote:

> Merged into master and branch-1.3 (skipped Jenkins because this only
> contains doc changes.)
>
> @emres <https://github.com/emres> This PR contains changes to GMM. It
> won't be able to merge into branch-1.2. Could you send a patch to
> branch-1.2? Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apache/spark/pull/4596#issuecomment-74323195>.
>



-- 
Emre Sevinc

**Comment by srowen** [comment]
@emres basically you would check out `branch-1.2`, make a new branch from there, make your change again (minus the change to GMM which won't exist), and then simply submit that PR like this one. You can note it's a backport.

**Comment by srowen** [comment]
Ah, BTW, the reason you had these merge conflicts is because your change actually modified a lot of lines trailing whitespace. Ideally we would have undone those and just committed your one-liner. Anyway, I can merge the new PR.

**Pull request closed without merging**
