### PR TITLE
[SPARK-12558][FOLLOW-UP] AnalysisException when multiple functions applied in GROUP BY clause

### PR DESCRIPTION
**Pull request by dilipbiswal**
Addresses the comments from Yin.
https://github.com/apache/spark/pull/10520

### CODE REVIEW

**Comment by dilipbiswal** [comment]
@yhuai Hi Yin, i have tried to modify the other tests in this file to use withTempTable. Hopefully that is ok..

**Comment by cloud-fan** [comment]
ok to test

**Comment by yhuai** [comment]
can we just change that single test?

**Comment by dilipbiswal** [comment]
@yhuai Sure.

**Comment by dilipbiswal** [comment]
@cloud-fan Can you please help trigger a retest ? Thanks !!

**Comment by cloud-fan** [comment]
retest this please

**Comment by dilipbiswal** [comment]
cc @yhuai

**Comment by yhuai** [comment]
LGTM. Thanks! Merging to master and branch 1.6.

**Pull request closed without merging**
