### PR TITLE
SPARK-1691: Support quoted arguments inside of spark-submit.

### PR DESCRIPTION
**Pull request by pwendell**
This is a fairly straightforward fix. The bug was reported by @vanzin and the fix was proposed by @deanwampler and myself. Please take a look!

### CODE REVIEW

**Comment by ganeshm25** [comment]
@koertkuipers i am trying to do achieve running the multiple driver-java-options with Spark 1.4.2 inside a bash script? is there a solution you found for this ?

**Comment by koertkuipers** [comment]
@ganeshm25 it seems to work in newer spark versions. i havent tried in spark 1.4.2. however its still very tricky to get it right and i would prefer a simpler solution.

**Comment by ganeshm25** [comment]
@koertkuipers can you the most recent syntax that you used to achieve the same?

**Comment by koertkuipers** [comment]
```OPTS+=" --driver-java-options \"-Da=b -Dx=y\""```

**Pull request closed without merging**
