### PR TITLE
[SPARK-32100][CORE][TESTS] Add WorkerDecommissionExtendedSuite

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to add `WorkerDecomissionExtendedSuite` for various worker decommission combinations.

### Why are the changes needed?

This will improve the test coverage.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the Jenkins.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
cc @dbtsai and @holdenk

**Comment by holdenk** [comment]
LGTM, better test coverage for stuff in core is good :) Thanks @dongjoon-hyun :)

**Comment by dongjoon-hyun** [comment]
Thank you, @holdenk !

**Comment by dongjoon-hyun** [comment]
All Scala/Java/PySpark test passed, current R tests are running.
Merged to master for Apache Spark 3.1.0.

**Comment by HyukjinKwon** [comment]
Wait .. the SPIP hasn't technically passed yet ...

**Comment by HyukjinKwon** [comment]
Let's make it pass quickly first so we don't have to block all these APIs. I am supportive of the SPIP FWIW.

**Comment by holdenk** [comment]
This is not an API change just increases test coverage on already merged code. I’ll bring the SPIP to a vote this week, just been dealing with resolving some misunderstandings first.

**Comment by HyukjinKwon** [comment]
Yeah, I just removed as I thought it's unnecessary to raise an issue here; but if we should technically speak, SPIP wasn't passed. It's odds to merge related PRs. We should technically more think about reverting the other codes rather than merging more codes when the SPIP is in progress.

I guess it's practically fine - and that's why I just decided to remove the comments but technically I don't think this is right.

**Pull request closed without merging**
