### PR TITLE
[SPARK-25861][Minor][WEBUI] Remove unused refreshInterval parameter from the headerSparkPage method.

### PR DESCRIPTION
**Pull request by shahidki31**
## What changes were proposed in this pull request?
'refreshInterval' is not used any where in the headerSparkPage method. So, we don't need to pass the parameter while calling the  'headerSparkPage' method.

## How was this patch tested?
Existing tests

### CODE REVIEW

**Comment by shahidki31** [comment]
cc @dongjoon-hyun @felixcheung

**Comment by gengliangwang** [comment]
Looks like the parameter is not used from the first day?
https://github.com/apache/spark/pull/290/files#diff-b8adb646ef90f616c34eb5c98d1ebd16R140

**Comment by shahidki31** [comment]
Hi @gengliangwang , Yes the parameter is not used from the beginning.

**Review by srowen — APPROVED** [review]

**Comment by shahidki31** [comment]
I will fix the build error.

**Comment by shahidki31** [comment]
retest this please

**Review by felixcheung — APPROVED** [review]
LGTM pending jenkins

**Review by gengliangwang — APPROVED** [review]
LGTM

**Comment by gengliangwang** [comment]
retest this please.

**Comment by shahidki31** [comment]
Seems random error.
Jenkins, retest this please.

**Comment by srowen** [comment]
That's a spurious failure, something's wrong with the build machine

**Comment by srowen** [comment]
Jenkins add to whitelist

**Comment by shahidki31** [comment]
The failure is unrelated to the PR. It is a known failure. https://issues.apache.org/jira/browse/SPARK-25923

**Comment by shahidki31** [comment]
Jenkins, retest this please

**Comment by srowen** [comment]
Merged to master

**Comment by shahidki31** [comment]
Thank you @srowen

**Pull request closed without merging**
