### PR TITLE
[SPARK-10214][SparkR][Docs] Improve SparkR Column, DataFrame API docs

### PR DESCRIPTION
**Pull request by yu-iskw**
cc: @shivaram 
## Summary
- Add @name tags to each methods in DataFrame.R and column.R
- Replace `@rdname column` with `@rdname {each_func}`. i.e. alias method : `@rdname column` =>  `@rdname alias`
## Generated PDF File

https://drive.google.com/file/d/0B9biIZIU47lLNHN2aFpnQXlSeGs/view?usp=sharing
## JIRA

[[SPARK-10214] Improve SparkR Column, DataFrame API docs - ASF JIRA](https://issues.apache.org/jira/browse/SPARK-10214)

### CODE REVIEW

**Comment by shivaram** [comment]
@yu-iskw I don't seem to have permission to access the google drive PDF ?

**Comment by yu-iskw** [comment]
@shivaram sorry, I modified the permission.

**Comment by shivaram** [comment]
From the PDF it looks like there are 3 or 4 more such methods: I could spot `cache`, `count`, `describe`, `printSchema` and `show` -- Or are these different for some reason I have missed ?

**Comment by shivaram** [comment]
Also one more minor thing is that the `DataFrame-class` somehow has details about the `agg` methods. I am not sure why that happened though

**Comment by yu-iskw** [comment]
It's my fault. I have fixed them.

**Comment by shivaram** [comment]
LGTM. Will merge once Jenkins passes

**Comment by yu-iskw** [comment]
Thank you for merging it!

**Pull request closed without merging**
