### PR TITLE
Revert "[SPARK-24418][BUILD] Upgrade Scala to 2.11.12 and 2.12.6"

### PR DESCRIPTION
**Pull request by dbtsai**
This reverts commit c7967c6049327a03b63ea7a3b0001a97d31e309d.

Because of the `printWelcome` message regression described in [https://issues.apache.org/jira/browse/SPARK-25138](https://issues.apache.org/jira/browse/SPARK-25138), to provide our users best experience, @gatorsmile and I agree that we either revert the Scala upgrade or merge #21749 which uses reflection to fix the printing ordering.

I'm leaning toward to merge #21749 since I worry reverting the Scala upgrade will break the work for Scala 2.12. On the other hand, fixing the printing ordering using reflection is not clean.

### CODE REVIEW

**Comment by srowen** [comment]
Oh, what went wrong @dbtsai ?

**Comment by dbtsai** [comment]
Because of the `printWelcome` message regression described in `https://issues.apache.org/jira/browse/SPARK-25138`, to have our users best experience, @gatorsmile and I agree that we either revert the Scala upgrade or merge https://github.com/apache/spark/pull/21749 which uses reflection to fix the printing ordering. 

I'm leaning toward merging https://github.com/apache/spark/pull/21749 since  I worry reverting the scala upgrade will break the work for Scala 2.12. On the other hand, fixing the printing ordering using reflection is not clean.

**Comment by rxin** [comment]
Can you add to the pr description why we are reverting? Just copy paste what you had above. Thanks.

**Comment by gatorsmile** [comment]
Thank you! @dbtsai Let us see whether this can pass all the tests?

**Comment by srowen** [comment]
I see, doesn't look like we lose a critical fix or improvement with the down-grade, and this wasn't released in 2.3.x. OK. I prefer to fix-forward, too, but am neutral on whether the cost of the workaround is worth it.

But does it affect 2.12? yeah that would be a bigger deal. But the original commit didn't seem to touch the 2.12 REPL.

**Comment by dbtsai** [comment]
@gatorsmile we also need to run the tests for 2.12 manually.

@srowen This PR will revert Scala 2.12.6 back to 2.12.4 since 2.12.6 also removes the hacks we used to initialize Spark. I worry it will have a negative impact on the recent work of Scala 2.12 support.

**Comment by gatorsmile** [comment]
@dbtsai Have you tried to run it in scala 2.12? We still can do the upgrade after Apache 2.4 RC.

**Comment by dbtsai** [comment]
@gatorsmile I have not find a time yesterday to run tests with Scala 2.12. I'll try to do it today.

**Comment by srowen** [comment]
By the way the 2.12 build will still fail, so that won't tell you much. 

I think we need 2.12.6 to fix a Java 8 related issue? Don't have it handy though.

Sorry if I'm being dense here but didn't all those REPL changes just concern 2.11? I did not see any 2.12 change except the version

**Comment by dbtsai** [comment]
@srowen We were overwriting `def loadFiles(settings: Settings) ` in https://github.com/scala/scala/blob/v2.11.6/src/repl/scala/tools/nsc/interpreter/ILoop.scala#L853 to initialize the Spark context. 

It's not available in newer version of Scala such as [2.12.6](https://github.com/scala/scala/blob/v2.12.6/src/repl/scala/tools/nsc/interpreter/ILoop.scala)  

The REPL code are shared by 2.11 and 2.12, right? So reverting the REPL code will fail 2.12 build.

**Comment by srowen** [comment]
Yeah that's right, we have had two parallel trees for different Scala versions just for reasons like this. There is less forked code now than with 2.10 vs 2.11. If you think we can merge all the code into one tree with some reflection then I think that's really worth it rather than reverting this.

**Comment by dbtsai** [comment]
Closed this PR since we're in favor of https://github.com/apache/spark/pull/21749

**Pull request closed without merging**
