### PR TITLE
[Minor] Fix doc typo for describing primitiveTerm effectiveness condition

### PR DESCRIPTION
**Pull request by viirya**
It should be `true` instead of `false`?

### CODE REVIEW

**Comment by srowen** [comment]
I don't know enough to be sure if the change is right, but, I suggest the PR title be made more meaningful than "fix document typo' since it will become a commit message. I agree this does not necessarily need a JIRA.

**Comment by viirya** [comment]
@srowen Thanks. Using a more meaningful title now.

**Comment by viirya** [comment]
I think this is a minor one. Does anyone know if the change is correct? Thanks!

**Comment by srowen** [comment]
CC @marmbrus

**Comment by marmbrus** [comment]
Merged to master and 1.3

**Pull request closed without merging**
