### PR TITLE
[SPARK-6855] [SPARKR] Set R includes to get the right collate order.

### PR DESCRIPTION
**Pull request by shivaram**
This prevents tools like devtools::document creating invalid collate orders

### CODE REVIEW

**Comment by shivaram** [comment]
cc @cafreeman @davies

**Comment by cafreeman** [comment]
You may want to pull in the schema changes from earlier today since SQLtypes.R was replaced with schema.R

**Comment by shivaram** [comment]
@cafreeman We will pull that change in #5436 and @davies will take care of merging it correctly.

**Comment by davies** [comment]
LGTM.

@shivaram Could you merge this today?  then I can rebase #5436

**Comment by shivaram** [comment]
Thanks @davies - I don't think the error has anything to do with this PR, but let me retest it anyways to be safe

Jenkins, retest this please

**Pull request closed without merging**
