### PR TITLE
[SPARK-41058][CONNECT] Remove unused import in commands.proto

### PR DESCRIPTION
**Pull request by dengziming**
### What changes were proposed in this pull request?
expressions.proto is not used in commands.proto

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
github CI

### CODE REVIEW

**Comment by LuciferYang** [comment]
looks fine

**Review by itholic — APPROVED** [review]
LGTM

**Comment by cloud-fan** [comment]
@amaliujia can you take a look?

**Review by LuciferYang — APPROVED** [review]
+1, LGTM

**Comment by amaliujia** [comment]
@dengziming I have missed this PR because there was no JIRA created under https://issues.apache.org/jira/browse/SPARK-39375 (I was monitoring works happened there). 

Since you are doing this change, can you create a JIRA for removing unused code (then update PR title with the JIRA included) and BTW remove some other unused code in connect project? 

I am seeing one example at https://github.com/apache/spark/blob/0add57a1c0290a158666027afb3e035728d2dcee/connector/connect/src/main/scala/org/apache/spark/sql/connect/service/SparkConnectStreamHandler.scala#L61. 


There are also unused imports probably existing that we can further clean up.

**Comment by amaliujia** [comment]
LGTM

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Pull request closed without merging**
