### PR TITLE
[SPARK-32457][ML] logParam thresholds in DT/GBT/FM/LR/MLP

### PR DESCRIPTION
**Pull request by zhengruifeng**
### What changes were proposed in this pull request?
logParam `thresholds` in DT/GBT/FM/LR/MLP

### Why are the changes needed?
param `thresholds` is logged in NB/RF, but not in other ProbabilisticClassifier

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
existing testsuites

### CODE REVIEW

**Review by srowen — APPROVED** [review]

**Review by huaxingao — APPROVED** [review]

**Comment by huaxingao** [comment]
@srowen quick question: for a small and safe improvement like this, do we merge into 3.0 too?

**Comment by srowen** [comment]
Generally it's bug fixes that are back-ported to maintenance branches, and even there the question is risk vs benefit.
Doc backports happen too, because they're very low risk and because the latest release (thus latest docs) are often from a maintenance branch.
For small improvements, you could argue it's very low risk, but they usually don't have much upside, so I wouldn't unless there's a good reason. There's always some odd chance the behavior change might impact something.
This is pretty safe, just don't see a compelling reason to backport it, unless you are arguing it's a tiny bug fix.

**Comment by huaxingao** [comment]
@srowen Got it, thanks!  I will merge this to master only. I will merge the doc PR for MLlib BLAS native acceleration to both master and 3.0.

**Comment by huaxingao** [comment]
Merged to master. Thanks @zhengruifeng @srowen

**Comment by zhengruifeng** [comment]
Thanks all!

**Pull request closed without merging**
