### PR TITLE
[SPARK-30756][SQL] Fix `ThriftServerWithSparkContextSuite` on spark-branch-3.0-test-sbt-hadoop-2.7-hive-2.3

### PR DESCRIPTION
**Pull request by HyukjinKwon**
### What changes were proposed in this pull request?

This PR tries #26710 (comment) way to fix the test.

### Why are the changes needed?

To make the tests pass.

### Does this PR introduce any user-facing change?

No.

### How was this patch tested?

Jenkins will test first, and then `on spark-branch-3.0-test-sbt-hadoop-2.7-hive-2.3` will test it out.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
@dongjoon-hyun, @wangyum, @shaneknapp, @srowen this is about `SPARK-30756`. I can't reproduce with the same profiles in PR builder and in my local. I wanted to try this way https://github.com/apache/spark/pull/26710#discussion_r352008959

Do you guys mind if I merge and see if this fixes [`spark-branch-3.0-test-sbt-hadoop-2.7-hive-2.3` ](https://amplab.cs.berkeley.edu/jenkins/view/Spark%20QA%20Test%20(Dashboard)/job/spark-branch-3.0-test-sbt-hadoop-2.7-hive-2.3/)?

**Review by wangyum — APPROVED** [review]

**Review by cloud-fan — APPROVED** [review]

**Comment by cloud-fan** [comment]
shall we merge it to master as well?

**Comment by shaneknapp** [comment]
tbh, i don't mind.

**Comment by HyukjinKwon** [comment]
Yup, I will do that.

**Comment by HyukjinKwon** [comment]
I will port forward to the master once the tests pass.

**Comment by HyukjinKwon** [comment]
Merged to master and branch-3.0.

**Comment by HyukjinKwon** [comment]
Okay, seems the test fixed.

**Comment by dongjoon-hyun** [comment]
Late LGTM. Thank you for fixing that, @HyukjinKwon !

**Pull request closed without merging**
