### PR TITLE
[SPARK-25439][TESTS][SQL] Fixes TPCHQuerySuite datatype of customer.c_nationkey to BIGINT according to spec

### PR DESCRIPTION
**Pull request by npoggi**
## What changes were proposed in this pull request?
Fixes TPCH DDL datatype of `customer.c_nationkey` from `STRING` to `BIGINT` according to spec and `nation.nationkey` in `TPCHQuerySuite.scala`. The rest of the keys are OK.
Note, this will lead to **non-comparable previous results** to new runs involving the customer table.

## How was this patch tested?
Manual tests

### CODE REVIEW

**Comment by npoggi** [comment]
CC @gatorsmile @abehm

**Review by dongjoon-hyun — APPROVED** [review]
Thank you for your first contribution, @npoggi .

+1, LGTM.

**Comment by dongjoon-hyun** [comment]
nit. Could you make the title shorter like `[SPARK-25439][TEST][SQL] Fix TPCH customer.c_nationkey datatype to BIGINT`?

**Comment by dongjoon-hyun** [comment]
ok to test

**Comment by gatorsmile** [comment]
retest this please

**Review by gatorsmile — COMMENTED** [review]
LGTM pending Jenkins.

**Comment by gatorsmile** [comment]
Thanks! Merged to master/2.4

**Comment by gatorsmile** [comment]
This is a pure test only PR. Backporting to 2.3 is optional.

**Comment by dongjoon-hyun** [comment]
I got it~ Oh, 2.3.2-rc6 is made.

**Pull request closed without merging**
