### PR TITLE
[SPARK-5108][BUILD] Jackson dependency management for Hadoop-2.6.0 support

### PR DESCRIPTION
**Pull request by zhzhan**
There is dependency compatibility issue. Currently hadoop-2.6.0 use 1.9.13 for jackson. Upgrade to the same version to make it consistent.

### CODE REVIEW

**Comment by vanzin** [comment]
Isn't the right fix to create a hadoop-2.6 profile that sets that version, while keeping the 1.8.8 version for the hadoop-2.4 profile?

**Comment by srowen** [comment]
@vanzin I don't think so here, for two reasons. Actually Hadoop 2.4 already uses this version. And, the issue with Hadoop 2.6 is just that it depends on 2 new artifacts from Jackson. Merely managing their version in `<dependencyManagement>` doesn't do anything if the artifacts aren't used. Net-net I think this is a good change but see my comments on the other PR https://github.com/apache/spark/pull/3914

@zhzhan You don't need to keep opening new PRs. Push more commits (force push if needed) to change the existing PR.

**Comment by vanzin** [comment]
@srowen where do you see the 1.9.13 dependency in hadoop-2.4? I'm looking at branch-2.4 in the hadoop sources and only see 1.8.8 there. When I investigated this in the past, parquet had a dependency on 1.9.13, but parquet is not part of hadoop.

The extra artifacts aren't actually used by Spark anywhere, although if someone tries to use certain hadoop APIs they might run into issues (as I did when I tried to talk to the Yarn ATS). So that change is fine.

**Comment by vanzin** [comment]
BTW, in #2982 I named the variable `codehaus.jackson.version` for clarity, to avoid a possible conflict with the fasterxml version of the library (used, at the moment, in the sql/ module).

**Comment by srowen** [comment]
@vanzin Hm, maybe that's what I'm seeing. If I `mvn -Pyarn -Dhadoop.version=2.4.0 -Dverbose dependency:tree` I see

```
[INFO] |  +- org.apache.hadoop:hadoop-hdfs:jar:2.4.0:compile
...
[INFO] |  |  +- (org.codehaus.jackson:jackson-core-asl:jar:1.8.8:compile - version managed from 1.9.13; omitted for duplicate)
[INFO] |  |  +- (org.codehaus.jackson:jackson-mapper-asl:jar:1.8.8:compile - version managed from 1.9.13; omitted for duplicate)
```

But yeah if I remove the overrides, it looks like Hadoop uses 1.8.8.

So we could...

- Just also manage Hadoop 2.6 down to 1.8.8 (and just manage the new artifact versions). No new profile.
- Manage everything up to Jackson 1.9.13. I don't know 100% this works but would have thought it's safer than managing down. That said it was managed down for a reason I presume
- Make the new profile and take the hit on yet more profile complexity

**Comment by vanzin** [comment]
Well, either choice (forcing it down to 1.8.8 or up to 1.9.13) is dangerous if the library doesn't have strict compatibility guarantees. If it's reasonably compatible - that is, if newer versions have strictly new APIs and didn't change or remove any old ones, forcing the version up would be best.

So I guess forcing the version up is ok if hadoop-2.4 libraries are ok with it. I haven't tested that case, though, so that's my only concern here.

**Comment by zhzhan** [comment]
@vanzin @srowen I will test on hadoop2.4

**Comment by zhzhan** [comment]
I tested on profile 2.4 and didn't see problem. But the upgrade may still  potentially have impact on other modules. Will wait  for a while to see whether other people have further comments.

**Comment by vanzin** [comment]
@zhzhan you'll need to fix merge conflicts now (since my change referenced above was pushed).

**Comment by srowen** [comment]
This came up again on the mailing list -- can't find a permalink but it's the message titled "run time exceptions in Spark 1.2.0 manual build together with OpenStack hadoop driver". I suggest committing a variant on this change. Leave the default version at 1.8.8 to be more conservative vis-a-vis Hadoop 1.x, but update all the Hadoop 2.x profiles to set the Jackson version to 1.9.13. That would seem to solve all the problems.

**Comment by zhzhan** [comment]
@srowen I agree it may be safer only upgrading hadoop-2.x.  @pwendell can you take a look at the change and let me know if you have any concern?

**Comment by zhzhan** [comment]
@pwendell Can you take a look at this? Do you think it would be better create another hadoop-2.6 profile to solve the issue?

**Comment by srowen** [comment]
This looks like the right change to me. If @pwendell has no further comments in a day or two I think I can merge it. It would solve a problem reported a couple times.

**Comment by zhzhan** [comment]
@srowen Thanks for following this up.

**Pull request closed without merging**
