### PR TITLE
 [SPARK-11962] WIP: Added functions  `attempt` and `getOption`.

### PR DESCRIPTION
**Pull request by aa8y**
## What changes were proposed in this pull request?

Add methods to get `Try` and `Option` types from a `Row`. The code is _not merge ready_. But I was not sure how I could get feedback without a PR. I've added two major methods to Row, `attempt`
and `getOption`. The former returns a `Try` while the latter returns an `Option`.
- `attempt` was added after a comment was made in PR #10247, where it was suggested I not return None when certain exceptions are thrown. But in my opinion, throwing exceptions from a function which returns an `Option` is not a good use case.
- I am not in love with the name `attempt`. Would welcome suggestions. I wanted to use `try` but it's a keyword.
- In `RowTest`, the tests testing for `ClassCastException` fail. I am not sure what I am doing wrong in the code here. Would appreciate feedback.
## How was this patch tested?

Tests have been added to `RowTest` to test the newly added methods.

### CODE REVIEW

**Comment by holdenk** [comment]
@aa8y  So generally [WIP] is how people will tag a PR as something which is a work in progress but not ready to be merged. You can also ask for feedback on the dev@ list or by pinging individuals in your JIRA who might have opnionins.

I haven't had a chance to look through the code - but it seems like there is a really big change to the gitignore file which is unrellated and you likely don't need for the intended purpose of this PR.

**Comment by aa8y** [comment]
@holdenk: I will keep in mind your suggestions in the future. The change in the .gitignore was that I sorted the contents. I can replace it with what's on master in the next commit. However please ignore the .gitignore file for now. If you could give some feedback on the other stuff, that would be great. Thanks!

**Comment by hvanhovell** [comment]
@aa8y what is the use case for this?

**Comment by aa8y** [comment]
@hvanhovell The end use case for both `attempt` and `getOption` is to get values out of a row object without throwing an exception. However, in one of my previous PRs, #10247 (which didn't have an `attempt` method), it was pointed out by @marmbrus that the `getOption` method caught exceptions and converted them to `None`s. His PoV was that exceptions should not be caught as that hid important information. But since the whole reason of `getOption` was to *not* throw exceptions, I introduced the `attempt` method which returns `Success` and `Failure` objects, which do not lose information and `getOption`, which does and returns a `Some` or `None`.

**Comment by aa8y** [comment]
@srowen I would really appreciate if you could review this WIP PR as well. I'll close it of course once I get all the feedback. On @holdenk's suggestion I did send an email to `dev@spark` but haven't received any responses. Might have been a weekend thing though :)

**Comment by aa8y** [comment]
PR being closed as it was pointing to my `master`. The new PR is #12708.

**Comment by aa8y** [comment]
PR being closed as it was pointing to my `master`. The new PR is #12708.

**Pull request closed without merging**
