### PR TITLE
[SPARK-28755][R][TESTS] Increase tolerance in 'spark.mlp' SparkR test for JDK 11

### PR DESCRIPTION
**Pull request by HyukjinKwon**
### What changes were proposed in this pull request?

This PR proposes to increase the tolerance for the exact value comparison in `spark.mlp` test. I don't know the root cause but some tolerance is already expected. I suspect it is not a big deal considering all other tests pass.

The values are fairly close:

JDK 8:

```
-24.28415, 107.8701, 16.86376, 1.103736, 9.244488
```

JDK 11:

```
-24.33892, 108.0316, 16.89082, 1.090723, 9.260533
```

### Why are the changes needed?

To fully support JDK 11. See, for instance, #25443 and #25423 for ongoing efforts.

### Does this PR introduce any user-facing change?

No

### How was this patch tested?

Manually tested on the top of https://github.com/apache/spark/pull/25472 with JDK 11

```bash
./build/mvn -DskipTests -Psparkr -Phadoop-3.2 package
./bin/sparkR
```

```R
absoluteSparkPath <- function(x) {
  sparkHome <- sparkR.conf("spark.home")
  file.path(sparkHome, x)
}
df <- read.df(absoluteSparkPath("data/mllib/sample_multiclass_classification_data.txt"),
              source = "libsvm")
model <- spark.mlp(df, label ~ features, blockSize = 128, layers = c(4, 5, 4, 3),
                   solver = "l-bfgs", maxIter = 100, tol = 0.00001, stepSize = 1, seed = 1)
summary <- summary(model)
head(summary$weights, 5)
```

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
@felixcheung and @shivaram, we're actually a bit rushing to let Hive 2.3.6 (with JDK 11 fix) release and Spark uses it to support JDK 11 in Spark 3. (see https://github.com/apache/spark/pull/25405#issuecomment-520303800, https://github.com/apache/spark/pull/25443 and https://github.com/apache/spark/pull/25423 for instance).

If you guys won't mind, I will just merge this. This is test-only and won't affect anything in main codes.

**Comment by shivaram** [comment]
@HyukjinKwon Sure it sounds fine to me. Lets file another JIRA to track where this error is coming from?

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Review by srowen — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @HyukjinKwon and @srowen .
Merged to master.

**Comment by HyukjinKwon** [comment]
> @HyukjinKwon Sure it sounds fine to me. Lets file another JIRA to track where this error is coming from?

Sure, let me file it in few days soon (after #25443)

**Pull request closed without merging**
