### PR TITLE
[SPARK-45153][BUILD][PS] Rebalance testing time for `pyspark-pandas-connect-part1`

### PR DESCRIPTION
**Pull request by itholic**
### What changes were proposed in this pull request?

This PR proposes to rebalance the tests for `pyspark-pandas-connect-part1`.

### Why are the changes needed?

We rebalance the CI by splitting slow tests into multiple parts, but `pyspark-pandas-connect-part1` takes almost an hour than other splitted `pyspark-pandas-connect-partx` tests as below:

|pyspark-pandas-connect-part0|pyspark-pandas-connect-part1|pyspark-pandas-connect-part2|
|--|--|--|
|1h 51m|2h 55m|1h 54m|

### Does this PR introduce _any_ user-facing change?

No, this PR is proposed to improve the build infra.

### How was this patch tested?

We should manually check the CI from GitHub Actions after PR is opened.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Thank you for keeping improving this, @itholic .

**Comment by itholic** [comment]
Result summary:

|pyspark-pandas-connect-part0|pyspark-pandas-connect-part1|pyspark-pandas-connect-part2|pyspark-pandas-connect-part3|
|--|--|--|--|
|1h 55m|1h 56m|1h 50m|1h 32m|

Now each tests run within 2 hrs. I think it seems to be better balanced than before.

cc @HyukjinKwon @dongjoon-hyun WDYT?

**Review by dongjoon-hyun — APPROVED** [review]
+1, it looks good to me. Thank you, @itholic .

**Comment by dongjoon-hyun** [comment]
Merged to master for Apache Spark 4.0.0.

**Review by HyukjinKwon — COMMENTED** [review]
Nice, LGTM thanks!

**Pull request closed without merging**
