### PR TITLE
add support for zipping a sequence of RDDs

### PR DESCRIPTION
**Pull request by mohitjaggi**
a proposed fix for https://issues.apache.org/jira/browse/SPARK-3489

### CODE REVIEW

**Comment by srowen** [comment]
ok to test

**Comment by srowen** [comment]
(This would need a JIRA, if it proceeds.) How strong is the need for this? you can always zip several RDDs together directly with several calls. It gets unwieldy with a lot of RDDs, but do you need to do that? you lose type safety in this method. I wonder if, is there a common need to zip an RDD with 2-3 others, we can just add utility overloads for that, that preserve type safety too.

**Comment by JoshRosen** [comment]
@srowen We already have versions of zipPartitions for zipping together up to 4 RDDs.

Is there a common enough use case for this feature that we would want to expose this non-type-safe API?

**Comment by srowen** [comment]
Ah right, I was looking at `zip` rather than `zipPartitions`. Yes the overloads are already there for `zipPartitions` and I don't see value in adding more. At best, add overloads for `zip`? but I also wonder about the use case, since you can still achieve this if really needed by calling `zipPartitions` overloads to make your own `zip`.

**Comment by srowen** [comment]
Do you mind closing this PR?

**Comment by mohitjaggi** [comment]
closing on sean's request. i have a workaround.

**Pull request closed without merging**
