### PR TITLE
[SPARK-36613][SQL][SS] Use EnumSet as the implementation of Table.capabilities method return value

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
The `Table.capabilities` method return a `java.util.Set` of `TableCapability` enumeration type, which is implemented using `java.util.HashSet` now. Such Set can be replaced `with java.util.EnumSet` because `EnumSet` implementations can be much more efficient compared to other sets.

### Why are the changes needed?
Use more appropriate data structures.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?

- Pass GA or Jenkins Tests.
- Add a new benchmark to compare `create` and `contains` operation between `EnumSet` and `HashSet`

### CODE REVIEW

**Comment by LuciferYang** [comment]
cc @srowen @dongjoon-hyun @HyukjinKwon @rednaxelafx

**Review by srowen — APPROVED** [review]
Looks like a fine optimization

**Comment by srowen** [comment]
Merged to master

**Comment by LuciferYang** [comment]
thanks @srowen

**Pull request closed without merging**
