### PR TITLE
[SPARK-29821] Allow calling non-aggregate SQL functions with column name

### PR DESCRIPTION
**Pull request by amanomer**
### What changes were proposed in this pull request?
Added `isnan()` for string parameter.

### Why are the changes needed?
Currently, some functions can be called only with Column parameter while others can be called by both Column and String parameter. This behavior should be consistent.

### Does this PR introduce any user-facing change?
No

### How was this patch tested?
Unit test added.

### CODE REVIEW

**Comment by maropu** [comment]
IIRC we don't actively add an interface for string column names in functions. plz use `stringExpr` instead. cc: @HyukjinKwon @srowen

**Comment by dongjoon-hyun** [comment]
+1 for @maropu 's comment.

**Review by srowen — COMMENTED** [review]
Yeah there may be places where a string is accepted as a col name, but I think it's for historical reasons and not something we'd continue to try to support.

**Comment by maropu** [comment]
Similar PRs to support string columns periodically come up, so it might be worth leaving some notes about this historical policy for referring to it...

**Comment by HyukjinKwon** [comment]
haha actually we left a note

https://github.com/apache/spark/blob/6f687691ef6212c125f4023fcd79839ee9244049/sql/core/src/main/scala/org/apache/spark/sql/functions.scala#L58-L60

**Comment by maropu** [comment]
@HyukjinKwon Ah, I didn't notice that! Thanks for letting me know.

**Pull request closed without merging**
