### PR TITLE
[MINOR] Remove unnecessary `imports`

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to remove unnecessary imports, include:
- `import scala.collection.immutable.Seq`
- `import scala.collection.immutable.IndexedSeq`

### Why are the changes needed?
Keep the code tidy.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

BTW, do you know why this is not detected by `UnusedImport` rule?

**Comment by panbingkun** [comment]
> +1, LGTM.
> 
> BTW, do you know why this is not detected by `UnusedImport` rule?

After this PR (which should be after `scala 2.13`), we see that `scala.collection.immutable.IndexedSeq` has been added to `src/library/scala/package.scala`, and this class means that we do not need to explicitly import when using `IndexedSeq`
https://github.com/scala/scala/commit/457dfd07449a8b7943b2a6c614fb57ea2a7b452e#diff-4b7ff743cb5f9fa1d39314acc17d6d0eebd6b9d74ce333dd6c5549cca13de731
image
image

**Comment by dongjoon-hyun** [comment]
To @panbingkun , please don't use `[WIP]` in the PR title. GitHub `Draft` feature is better to prevent meting.

It seems that you forget `[WIP]` of the PR title frequently. :)

**Comment by panbingkun** [comment]
> To @panbingkun , please don't use `[WIP]` in the PR title. GitHub `Draft` feature is better to prevent meting.
> 
> It seems that you forget `[WIP]` of the PR title frequently. :)

Yeah, I was in a hurry to have `breakfast` just now, and I forgot to remove it. Sorry, haha ❤️

**Pull request closed without merging**
