### PR TITLE
[SPARK-44833][CONNECT] Fix sending Reattach too fast after Execute

### PR DESCRIPTION
**Pull request by juliuszsompolski**
### What changes were proposed in this pull request?

Redo the retry logic, so that getting a new iterator via ReattachExecute does not depend on "firstTry", but there is logic in "callIter" with unsetting the iterator when a new one is needed.

### Why are the changes needed?

After an "INVALID_HANDLE.OPERATION_NOT_FOUND" error, client would realize that the failure in ReattachExecute was because the initial ExecutePlan didn't reach the server. It would then call another ExecutePlan, and it will throw a RetryException to let the retry logic handle retrying. However, the retry logic would then immediately send a ReattachExecute, and the client will want to use the iterator of the reattach.

However, on the server the ExecutePlan and ReattachExecute could race with each other:
* ExecutePlan didn't reach executeHolder.runGrpcResponseSender(responseSender) in SparkConnectExecutePlanHandler yet.
* ReattachExecute races around and reaches executeHolder.runGrpcResponseSender(responseSender) in SparkConnectReattachExecuteHandler first.
* When ExecutePlan reaches executeHolder.runGrpcResponseSender(responseSender), and executionObserver.attachConsumer(this) is called in ExecuteGrpcResponseSender of ExecutePlan, it will kick out the ExecuteGrpcResponseSender of ReattachExecute.

So even though ReattachExecute came later, it will get interrupted by the earlier ExecutePlan and finish with a INVALID_CURSOR.DISCONNECTED error.

After this change, such a race between ExecutePlan / ReattachExecute can still happens, but the client should no longer send these requests in such quick succession.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Integration testing.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by juliuszsompolski** [comment]
@hvanhovell @HyukjinKwon

**Review by hvanhovell — APPROVED** [review]
LGTM

**Review by HyukjinKwon — APPROVED** [review]
Thanks for fixing Python side together. LGTM

**Comment by juliuszsompolski** [comment]
https://github.com/juliuszsompolski/apache-spark/actions/runs/6076122424/job/16483638602
This module timed out. All connect related tests finished successfuly.

**Comment by HyukjinKwon** [comment]
Merged to master and branch-3.5.

**Comment by MaxGekk** [comment]
Isn't this error related to your changes?
```
starting mypy annotations test...
annotations failed mypy checks:
python/pyspark/sql/connect/client/reattach.py:149: error: Incompatible types in assignment (expression has type "None", variable has type "Iterator[ExecutePlanResponse]")  [assignment]
python/pyspark/sql/connect/client/reattach.py:254: error: Incompatible types in assignment (expression has type "None", variable has type "Iterator[ExecutePlanResponse]")  [assignment]
python/pyspark/sql/connect/client/reattach.py:[25](https://github.com/apache/spark/actions/runs/6093065151/job/16532169212#step:19:26)8: error: Incompatible types in assignment (expression has type "None", variable has type "Iterator[ExecutePlanResponse]")  [assignment]
Found 3 errors in 1 file (checked 703 source files)
```

**Comment by HyukjinKwon** [comment]
Yeah, let me make a quick followup.

**Comment by HyukjinKwon** [comment]
https://github.com/apache/spark/pull/42830

**Comment by juliuszsompolski** [comment]
Thank you @HyukjinKwon .
Does CI linting not catch this?

**Comment by HyukjinKwon** [comment]
Actually it did :-) https://github.com/juliuszsompolski/apache-spark/actions/runs/6076122424/job/16483638163

**Comment by juliuszsompolski** [comment]
huh, I don't know how I missed it when I was checking and commenting https://github.com/apache/spark/pull/42806#issuecomment-1706640901 ...
Thanks again!

**Pull request closed without merging**
