### PR TITLE
[SPARK-8870][MLlib]Use SQLContext.getOrCreate in model save/load

### PR DESCRIPTION
**Pull request by y-shimizu**
I replace `new SQLContext(sc)` to `SQLContext.getOrCreate` in mllib main.
but I don't modify all tests, because each test case expect fresh SQLContext.

### CODE REVIEW

**Comment by mengxr** [comment]
ok to test

**Comment by mengxr** [comment]
LGTM pending Jenkins.

**Comment by sarutak** [comment]
Does this work when we use multiple SparkContext in one application?

**Comment by mengxr** [comment]
@sarutak We use the SparkContext from input, just not creating new SQLContexts.

**Comment by sarutak** [comment]
I know the motivation of re-using SQLContexts but I wonder save/load really don't have chances they receive another instance of SparkContext with different configuration in one application. 
For example, even it maybe rare case, does following code work with this patch?

```
val conf = new SparkConf().setAppName("...").setMaster("...")
val sc1 = new SparkContext(conf)
...
NaiveBayesModel.save(sc1, path1)
sc1.stop
...
val sc2 = new SparkContext(conf)
...
NaiveBayesModel.save(sc2, path2)  // may fail?
```

**Comment by tdas** [comment]
@sarutak This code will not work because sc2 will throw an error that there cannot be two active sparkcontexts in the same JVM. 

@mengxr The point of getOrCreate is to get a SQLContext if one is already active, rather than creating a new SQLContext. If there isnt any active, then a new one will be started using the provided SparkContext.

**Comment by mengxr** [comment]
Thanks for the discussion! Given the fact that creating a SQLContext is very lightweight, maybe we should keep the existing code. @y-shimizu Sorry for misunderstanding the purpose of `getOrCreate`. I will mark the JIRA "won't fix". Do you mind closing this PR for now? Thanks!

**Comment by sarutak** [comment]
@tdas Thanks for your upplementary explanation.
@mengxr Sorry for my poor explanation.
@y-shimizu We should keep the existing code but thanks for trying to contribute anyway.

**Pull request closed without merging**
