### PR TITLE
[SPARK-6078][CORE] create event log dir if not exists

### PR DESCRIPTION
**Pull request by liyezhang556520**
when event log directory does not exists, spark just throw IlleagalArgumentException and stop the job. User need manually create directory first. It's better to create the directory automatically if the directory does not exists.

### CODE REVIEW

**Comment by JoshRosen** [comment]
This looks like a duplicate of #4120 / https://issues.apache.org/jira/browse/SPARK-5311, which we marked as "Won't Fix": https://github.com/apache/spark/pull/4120#issuecomment-72954989

**Comment by JoshRosen** [comment]
If we do decide to create directories, then we should only create the last missing directory, not all missing parent directories.

**Comment by liyezhang556520** [comment]
Hi @JoshRosen, it's duplicate with  https://issues.apache.org/jira/browse/SPARK-5311, now that it won't fix, should I also close this PR? 
But it is really not user friendly to manually create directory if user wants to put file in a new directory.

**Comment by JoshRosen** [comment]
@srowen @vanzin @andrewor14, what are your thoughts on the usability / security trade-offs here?

**Comment by srowen** [comment]
FWIW I think the reasoning at https://github.com/apache/spark/pull/4120#issuecomment-72954989 still stands and so we should also close this PR + JIRA as a duplicate.

**Comment by andrewor14** [comment]
Yes, we purposefully removed this feature. @liyezhang556520 would you mind closing this?

**Comment by liyezhang556520** [comment]
sure, I'll close this PR then, thanks for your review @JoshRosen, @srowen  @andrewor14

**Pull request closed without merging**
