### PR TITLE
[SPARK-7873] Allow KryoSerializerInstance to create multiple streams at the same time

### PR DESCRIPTION
**Pull request by JoshRosen**
This is a somewhat obscure bug, but I think that it will seriously impact KryoSerializer users who use custom registrators which disabled auto-reset. When auto-reset is disabled, then this breaks things in some of our shuffle paths which actually end up creating multiple OutputStreams from the same shared SerializerInstance (which is unsafe). 

This was introduced by a patch (SPARK-3386) which enables serializer re-use in some of the shuffle paths, since constructing new serializer instances is actually pretty costly for KryoSerializer.  We had already fixed another corner-case (SPARK-7766) bug related to this, but missed this one.

I think that the root problem here is that KryoSerializerInstance can be used in a way which is unsafe even within a single thread, e.g. by creating multiple open OutputStreams from the same instance or by interleaving deserialize and deserializeStream calls. I considered a smaller patch which adds assertions to guard against this type of "misuse" but abandoned that approach after I realized how convoluted the Scaladoc became.

This patch fixes this bug by making it legal to create multiple streams from the same KryoSerializerInstance.  Internally, KryoSerializerInstance now implements a  `borrowKryo()` / `releaseKryo()` API that's backed by a "pool" of capacity 1. Each call to a KryoSerializerInstance method will borrow the Kryo, do its work, then release the serializer instance back to the pool. If the pool is empty and we need an instance, it will allocate a new Kryo on-demand. This makes it safe for multiple OutputStreams to be opened from the same serializer. If we try to release a Kryo back to the pool but the pool already contains a Kryo, then we'll just discard the new Kryo. I don't think there's a clear benefit to having a larger pool since our usages tend to fall into two cases, a) where we only create a single OutputStream and b) where we create a huge number of OutputStreams with the same lifecycle, then destroy the KryoSerializerInstance (this is what's happening in the bypassMergeSort code path that my regression test hits).

### CODE REVIEW

**Comment by pwendell** [comment]
Jenkins, retest this please.

**Comment by JoshRosen** [comment]
Pushed a new test demonstrating another problem: back-to-back deserialize / deserializeStream calls aren't safe, even if you close the stream first.  This was a problem in the old code, too, and can lead to silent data corruption.

**Comment by JoshRosen** [comment]
Alright, this should be ready for a first pass of reviews.  I'm going to work on updating the comments shortly.

**Comment by JoshRosen** [comment]
Whoops, meant to post this comment earlier:

I think that he root problem here is that KryoSerializerInstance can be used in a way which is unsafe even within a single thread, e.g. by creating multiple open OutputStreams from the same instance or by interleaving deserialize and deserializeStream calls.  I considered a smaller patch which adds assertions to guard against this type of "misuse" but abandoned that approach after I realized how convoluted the Scaladoc became.

I just pushed a WIP commit which illustrates my proposed fix.  In a nutshell, I think that rather than using a single `Kryo` instance in KryoSerializerInstance, we should implement a `borrowKryo()` / `releaseKryo()` API that's backed by a "pool" of capacity 1.  In the common case, every call to a KryoSerializerInstnace method, do its work, then release the serializer instance back to the pool.  If the pool is empty and we need an instance, we'll allocate a new Kryo on-demand.  This makes it safe for multiple OutputStreams to be opened from the same serializer.  If we try to release a Kryo back to the pool but the pool already contains a Kryo, then we'll just discard the new Kryo.  I don't think there's a clear benefit to having a larger pool since our usages tend to fall into two cases, a) where we only create a single OutputStream and b) where we create a huge number of OutputStreams with the same lifecycle, then destroy the KryoSerializerInstance (this is what's happening in the bypassMergeSort code path that my failing test hits).

**Comment by zsxwing** [comment]
LGTM

**Comment by JoshRosen** [comment]
Thanks for reviewing.  Don't merge this yet; I need to update the description and comments.

**Comment by JoshRosen** [comment]
I've revised the pull request description and pushed a new commit which adds a few more comments.

**Comment by JoshRosen** [comment]
Jenkins, retest this please.

**Comment by JoshRosen** [comment]
Jenkins, retest this please.

**Comment by JoshRosen** [comment]
Flaky Python test...

**Comment by JoshRosen** [comment]
@zsxwing @pwendell unless you have additional feedback, I think that this should now be good to go for the next RC.

**Comment by zsxwing** [comment]
LGTM

**Comment by pwendell** [comment]
Okay, merging this - thanks guys.

**Pull request closed without merging**
