### PR TITLE
[SPARK-32687][SQL] Let CostBasedJoinReorder produce relatively deterministic optimization result

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
The optimization result of `CostBasedJoinReorder` is non-deterministic now, it affected by the input order if there have more than one same cost candidate plans.

In this pr give a way to make it deterministic as much as possible, the main change of this pr as follow:

- Sort the items which use to produce candidate plans in descending order according to `rowCount` and `sizeInBytes` to ensure the deterministic of input items as much as possible.

- Change to use `LinkedHashMap` instead of `HashMap` to make sure that items are inserted and iterated in the same order.

- Add a new test case to `StarJoinCostBasedReorderSuite` to verify all input permutations have the same optimization result

- Regenerate golden files used by `TPCDSV2_7_PlanStabilityWithStatsSuite`, `TPCDSV1_4_PlanStabilityWithStatsSuite` and `TPCDSModifiedPlanStabilityWithStatsSuite` affected by this sort behavior

### Why are the changes needed?
Let `CostBasedJoinReorder` produce optimization result, independent of input order. 

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?

- Add a new test case named `Test 7: SPARK-32687 Verify all input permutations have the same optimization result`

- Scala 2.12: Pass the Jenkins or GitHub Action

### CODE REVIEW

**Comment by LuciferYang** [comment]
cc @srowen @cloud-fan @HyukjinKwon @dongjoon-hyun, this pr try to resolved the problems we discuss in [SPARK-32526](https://github.com/apache/spark/pull/29434)

**Comment by LuciferYang** [comment]
@srowen @dongjoon-hyun this issue also blocking the progress of `sql/core` module pass all test in Scala 2.13, some test failed of `TPCDSV2_7_PlanStabilityWithStatsSuite ` and `TPCDSV1_4_PlanStabilityWithStatsSuite ` as follow:

TPCDSV2_7_PlanStabilityWithStatsSuite:
- check simplified sf100 (tpcds-v2.7.0/q6) *** FAILED ***
- check simplified sf100 (tpcds-v2.7.0/q72) *** FAILED ***


TPCDSV1_4_PlanStabilityWithStatsSuite:
- check simplified sf100 (tpcds-v1.4/q6) *** FAILED ***
- check simplified sf100 (tpcds-v1.4/q13) *** FAILED ***
- check simplified sf100 (tpcds-v1.4/q19) *** FAILED ***
- check simplified sf100 (tpcds-v1.4/q31) *** FAILED ***
- check simplified sf100 (tpcds-v1.4/q61) *** FAILED ***
- check simplified sf100 (tpcds-v1.4/q62) *** FAILED ***
- check simplified sf100 (tpcds-v1.4/q66) *** FAILED ***
- check simplified sf100 (tpcds-v1.4/q72) *** FAILED ***
- check simplified sf100 (tpcds-v1.4/q84) *** FAILED ***
- check simplified sf100 (tpcds-v1.4/q85) *** FAILED ***
- check simplified sf100 (tpcds-v1.4/q99) *** FAILED ***

But with this pr, they are all passed.

**Comment by maropu** [comment]
add to whitelist

**Comment by LuciferYang** [comment]
There are too many conflicting files after SPARK-32755, I will resolve it first

**Comment by LuciferYang** [comment]
[43a2649](https://github.com/apache/spark/pull/29638/commits/43a26499dde250c376013a8a933679fe61669835) and [a057137](https://github.com/apache/spark/pull/29638/commits/a057137779c5f92d8c31190075ddc9601b3a9d5d) resolve d conflict files

**Comment by LuciferYang** [comment]
A little sad, SPARK-32755  blocking compilation of SQL / catalyst module,  Is there any way to ensure that the modules that have passed will not be failed again .... @srowen

**Comment by srowen** [comment]
@LuciferYang are you sure? tests passed for that PR. Build jobs seem fine. https://amplab.cs.berkeley.edu/jenkins/view/Spark%20QA%20Test%20(Dashboard)/
What are you seeing?

**Review by viirya — COMMENTED** [review]
Hmm, why this is needed? Firstly I thought CostBasedJoinReorder will produce non-deterministic for same query. But I looked at the JIRA description, seems for different input, the rule will produce different output. Doesn't it sound reasonable? Different input causes different output.

**Comment by LuciferYang** [comment]
> @LuciferYang are you sure? tests passed for that PR. Build jobs seem fine. https://amplab.cs.berkeley.edu/jenkins/view/Spark%20QA%20Test%20(Dashboard)/
What are you seeing?
@srowen Sorry, it my mistake,  What I meant was  SPARK-32755 blocking compilation of sql/ catalyst module in Scala 2.13, not Scala 2.12

**Comment by LuciferYang** [comment]
> Hmm, why this is needed? Firstly I thought CostBasedJoinReorder will produce non-deterministic for same query. But I looked at the JIRA description, seems for different input, the rule will produce different output. Doesn't it sound reasonable? Different input causes different output.

@viirya viirya Sorry, I didn't describe it clearly. Actually, there are 2 problems we found in  SPARK-32526:

1. For same Scala version,  different input causes different output as I describe in SPARK-32687, for example:

```
d1.join(t3).join(t4).join(f1).join(d3).join(d2)
  .where((nameToAttr("d1_c2") === nameToAttr("t3_c1")) &&
          (nameToAttr("t3_c2") === nameToAttr("t4_c2")) &&
          (nameToAttr("d1_pk") === nameToAttr("f1_fk1")) &&
          (nameToAttr("f1_fk2") === nameToAttr("d2_pk")) &&
          (nameToAttr("f1_fk3") === nameToAttr("d3_pk")))
```

and 

```
d1.join(t3).join(f1).join(d2).join(t4).join(d3)
 .where((nameToAttr("d1_c2") === nameToAttr("t3_c1")) &&
          (nameToAttr("t3_c2") === nameToAttr("t4_c2")) &&
          (nameToAttr("d1_pk") === nameToAttr("f1_fk1")) &&
          (nameToAttr("f1_fk2") === nameToAttr("d2_pk")) &&
          (nameToAttr("f1_fk3") === nameToAttr("d3_pk")))
```
have different optimization result, I think this is acceptable if the candidates have same cost, but @cloud-fan has some different view in https://github.com/apache/spark/pull/29434, I'm not sure I understand it correctly.


2.  For different Scala version (2.12 vs 2.13), same input maybe causes different output,  for example

```
d1.join(t3).join(t4).join(f1).join(d2).join(t5).join(t6).join(d3).join(t1).join(t2)
        .where((nameToAttr("d1_c2") === nameToAttr("t3_c1")) &&
          (nameToAttr("t3_c2") === nameToAttr("t4_c2")) &&
          (nameToAttr("d1_pk") === nameToAttr("f1_fk1")) &&
          (nameToAttr("f1_fk2") === nameToAttr("d2_pk")) &&
          (nameToAttr("d2_c2") === nameToAttr("t5_c1")) &&
          (nameToAttr("t5_c2") === nameToAttr("t6_c2")) &&
          (nameToAttr("f1_fk3") === nameToAttr("d3_pk")) &&
          (nameToAttr("d3_c2") === nameToAttr("t1_c1")) &&
          (nameToAttr("t1_c2") === nameToAttr("t2_c2")))
```
in Scala 2.12 and Scala 2.13 have different optimization result. If everyone thinks that `different input causes different output` is reasonable,  I will close this first. But maybe we also need resolve problem 2, I will describe the problem in another jira based on problem 2 and try to fix it.

**Comment by LuciferYang** [comment]
@viirya I'm also entangled in this issue :(

**Comment by srowen** [comment]
@LuciferYang SPARK-32755 is resolved now. What are you blocked on?

**Comment by gatorsmile** [comment]
cc @maryannxue @cloud-fan

**Comment by LuciferYang** [comment]
I will give a simplified fix to resolve `same input has different output with different Scala version ` issue in another pr, close this first.

**Pull request closed without merging**
