### PR TITLE
[MINOR] Fix a typo in FsHistoryProvider loginfo

### PR DESCRIPTION
**Pull request by sungpeo**
## What changes were proposed in this pull request?
a typo in logging. (just added `: `)

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
It's okay but mind double checking if there are some more typos around here? I am sure there are more and let's fix it while we're here.

**Comment by HyukjinKwon** [comment]
Also, let's keep the PR template (https://github.com/apache/spark/blob/master/.github/PULL_REQUEST_TEMPLATE).

**Comment by srowen** [comment]
Jenkins test this please

**Comment by srowen** [comment]
Jenkins test this please

**Comment by srowen** [comment]
OK, merged to master

**Pull request closed without merging**
