### PR TITLE
[MINOR][DOCS] Typo fix in cloud-integration.md

### PR DESCRIPTION
**Pull request by fishmandev**
### What changes were proposed in this pull request?
Typo fix

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
@fishmandev, let's make sure filling PR description although this is trivial change. While we're here, mind checking if there are more typos to fix around here?

Also, Github Actions in your forked repository should be enable to run CI, see also https://github.com/apache/spark/pull/34129/checks?check_run_id=3733907992

**Comment by fishmandev** [comment]
> Also, Github Actions in your forked repository should be enable to run CI

Done it.

> While we're here, mind checking if there are more typos to fix around here?

[I have a question regarding this part of the text:](https://github.com/apache/spark/blame/master/docs/cloud-integration.md#L31)
```In order to store hundreds of petabytes of data without any single points of failure, object stores replace the classic file system directory tree with a simpler model of `object-name => data`.```

Why is the plural used for 'SPOF' in this context? Or is it a typo?
```... without any``` **```single point```** ```of failure, ...```

@HyukjinKwon, what do you think about it?

**Comment by srowen** [comment]
Either works, to my ear. There is not one SPOF, there are not multiple SPOFs => there are none

**Comment by srowen** [comment]
Jenkins test this please

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
