### PR TITLE
[SPARK-33963][SQL] Canonicalize `HiveTableRelation` w/o table stats

### PR DESCRIPTION
**Pull request by MaxGekk**
### What changes were proposed in this pull request?
Skip table stats in canonicalizing of `HiveTableRelation`.

### Why are the changes needed?
The changes fix a regression comparing to Spark 3.0, see SPARK-33963.

### Does this PR introduce _any_ user-facing change?
Yes. After changes Spark behaves as in the version 3.0.1.

### How was this patch tested?
By running new UT:
```
$ build/sbt -Phive-2.3 -Phive-thriftserver "test:testOnly *CachedTableSuite"
```

### CODE REVIEW

**Comment by MaxGekk** [comment]
@cloud-fan @viirya @wangyum @advancedxy Highly likely this regression is caused by https://github.com/apache/spark/pull/25306. Please, review the bug fix.

**Review by viirya — APPROVED** [review]

**Comment by MaxGekk** [comment]
jenkins, retest this, please

**Review by HyukjinKwon — APPROVED** [review]
LGTM2

**Comment by HyukjinKwon** [comment]
Merged to master, branch-3.1 and branch-3.0.

**Comment by cloud-fan** [comment]
late LGTM

**Comment by advancedxy** [comment]
late LGTM, but curious why Spark-33963 triggered this regression in Spark 3.1 but not in Spark 3.0.

**Comment by MaxGekk** [comment]
@advancedxy There should be 2 conditions to fail:
1. Canonicalized plan includes table stats
2. Different table stats in already cached plan in the cache and in the plan to check.

Both 3.0 and master includes table stats to canonicalized plan of `HiveTableRelation` but cached plan in master does not contains table stats due to this PR https://github.com/apache/spark/pull/30598. In the master, we have another code for `CACHE TABLE` comparing to 3.0.

master:
```
      sparkSession.sharedState.cacheManager.cacheQuery(
        sparkSession,
        planToCache,
        Some(relationName))
```

3.0:
```
      sparkSession.catalog.cacheTable(tableIdent.quotedString)
```

3.0 puts plans with stats to the cache but master doesn't. And the test performs the check `assert(spark.catalog.isCached(t))` which internally looks for `sparkSession.table(tableName)` in the cache. And the plan for `sparkSession.table(tableName)` includes tables stats. As a consequence, the assert passes.

**Comment by advancedxy** [comment]
Thanks for the detailed explanation

**Pull request closed without merging**
