### PR TITLE
[SPARK-25084][SQL] distribute by on multiple columns may lead to code…

### PR DESCRIPTION
**Pull request by LantaoJin**
…gen issue

## What changes were proposed in this pull request?

"distribute by" on multiple columns may lead to codegen issue

## How was this patch tested?

manual test

### CODE REVIEW

**Comment by LantaoJin** [comment]
@cloud-fan @jerryshao

**Comment by jerryshao** [comment]
ok to test.

**Comment by LantaoJin** [comment]
ok to test.

**Comment by LantaoJin** [comment]
@jerryshao Could you help to trigger test build please?

**Comment by LantaoJin** [comment]
Add unit test with a rand() column in 'distribute by'

**Comment by kiszk** [comment]
retest this please

**Comment by LantaoJin** [comment]
Seems #22066 has changed the implementation with a similar approach. I will close this one.

**Pull request closed without merging**
