### PR TITLE
[SPARK-16489][SQL] Guard against variable reuse mistakes in expression code generation

### PR DESCRIPTION
**Pull request by rxin**
## What changes were proposed in this pull request?

In code generation, it is incorrect for expressions to reuse variable names across different instances of itself. As an example, SPARK-16488 reports a bug in which pmod expression reuses variable name "r".

This patch updates ExpressionEvalHelper test harness to always project two instances of the same expression, which will help us catch variable reuse problems in expression unit tests. This patch also fixes the bug in crc32 expression. 
## How was this patch tested?

This is a test harness change, but I also created a new test suite for testing the test harness.

### CODE REVIEW

**Comment by rxin** [comment]
This pr will fail until https://github.com/apache/spark/pull/14144 makes it in.

**Comment by rxin** [comment]
cc @sameeragarwal

**Comment by sameeragarwal** [comment]
LGTM

**Comment by rxin** [comment]
Merging in master/2.0.

**Pull request closed without merging**
