### PR TITLE
[branch-1.0][SPARK-4355] ColumnStatisticsAggregator doesn't merge mean correctly

### PR DESCRIPTION
**Pull request by mengxr**
This backports the bug fix in #3220.

### CODE REVIEW

**Comment by JoshRosen** [comment]
This looks like a legitimate build break / test failure in `branch-1.0`, possibly related to SPARK_HOME settings in the sbt build; I'm investigating now; see #3864 for more details.

**Comment by mengxr** [comment]
test this please

**Comment by rxin** [comment]
What do we do with this?

**Comment by JoshRosen** [comment]
@rxin I think folks have been holding off on merging branch 1.0 backports because the tests usually fail there, although in many cases I think that's because our test stability improvements haven't been backported to that branch, leaving those tests much more prone to spurious failures due to timing issues port contention, etc.

Since the number of branch-1.0 backports is so small, we could just merge them in now as long as they compile and choose to fix up the tests later or run the tests in an environment with less contention (e.g. a dedicated EC2 node rather than AMPLab Jenkins).  This isn't an ideal situation, but I think it might be better than just closing these PRs or leaving them to clutter up the review queue.

**Comment by JoshRosen** [comment]
Jenkins, retest this please.

**Comment by mengxr** [comment]
test this please

**Comment by srowen** [comment]
In order to close this out, is it worth just merging this into 1.0 as @JoshRosen  suggests? 
Same for some of these other back-ports to 0.9 or 1.0.

**Comment by mengxr** [comment]
Okay. Merge into branch-1.0:)

**Pull request closed without merging**
