### PR TITLE
[SPARK-10474] [SQL] Aggregation fails to allocate memory for pointer array

### PR DESCRIPTION
**Pull request by andrewor14**
When `TungstenAggregation` hits memory pressure, it switches from hash-based to sort-based aggregation in-place. However, in the process we try to allocate the pointer array for writing to the new `UnsafeExternalSorter` _before_ actually freeing the memory from the hash map. This lead to the following exception:

```
 java.io.IOException: Could not acquire 65536 bytes of memory
        at org.apache.spark.util.collection.unsafe.sort.UnsafeExternalSorter.initializeForWriting(UnsafeExternalSorter.java:169)
        at org.apache.spark.util.collection.unsafe.sort.UnsafeExternalSorter.spill(UnsafeExternalSorter.java:220)
        at org.apache.spark.sql.execution.UnsafeKVExternalSorter.<init>(UnsafeKVExternalSorter.java:126)
        at org.apache.spark.sql.execution.UnsafeFixedWidthAggregationMap.destructAndCreateExternalSorter(UnsafeFixedWidthAggregationMap.java:257)
        at org.apache.spark.sql.execution.aggregate.TungstenAggregationIterator.switchToSortBasedAggregation(TungstenAggregationIterator.scala:435)
```

### CODE REVIEW

**Comment by andrewor14** [comment]
@yhuai

**Comment by yhuai** [comment]
Looks good. @rxin or @JoshRosen can any of you take a final look?

**Comment by andrewor14** [comment]
also @davies

**Comment by davies** [comment]
@andrewor14 Since we will refactor all the memory management in 1.6, and this PR does fix the problem, so LGTM.

**Comment by andrewor14** [comment]
OK, I'm merging into master and 1.5. Thanks for the reviews.

**Pull request closed without merging**
