### PR TITLE
[SQL] SPARK-5309: Use Dictionary for Binary->String conversion

### PR DESCRIPTION
**Pull request by MickDavies**
Use of Dictionary will reduce conversion overhead which is significant when converting from Binary in UTF to Java String.
Dictionaries are use in Parquet where columns hold a limited set of values which is often the case.

### CODE REVIEW

**Comment by MickDavies** [comment]
I have not written explicit tests for this. I think it will be covered by existing tests, but I am trying to verify that. 
Do you have any tests that cover performance?

**Comment by ash211** [comment]
Jenkins this is ok to test

**Comment by MickDavies** [comment]
I've looked through ParquetQuerySuite and ParquetQuerySuite2 and its not obvious that there are tests that will exercise this change. I.e. where Parquet uses dictionary encoding for Strings. Most test String columns have strings with incrementing values that will result in unique values, and I don't think these will be encoded in dictionaries.

I think it would be good to add an explicit test to ParquetQuerySuite2, which I'll try to do this evening.

**Comment by squito** [comment]
Jenkins retest this please

**Comment by MickDavies** [comment]
I tried to rebase - not sure why but lots of other commits seemed to get pulled in. I am going to try again with a new PR.

**Pull request closed without merging**
