### PR TITLE
[MINOR][Core] fix warnings on depreciated methods in MesosClusterSchedulerSuite and DiskBlockObjectWriterSuite

### PR DESCRIPTION
**Pull request by keypointt**
## What changes were proposed in this pull request?

Fixed warnings below after scanning through warnings during build:

```
[warn] /home/jenkins/workspace/SparkPullRequestBuilder/core/src/test/scala/org/apache/spark/scheduler/cluster/mesos/MesosClusterSchedulerSuite.scala:34: imported `Utils' is permanently hidden by definition of object Utils in package mesos
[warn] import org.apache.spark.scheduler.cluster.mesos.Utils
[warn]                                                 ^
```

and

```
[warn] /home/jenkins/workspace/SparkPullRequestBuilder/core/src/test/scala/org/apache/spark/storage/DiskBlockObjectWriterSuite.scala:113: method shuffleBytesWritten in class ShuffleWriteMetrics is deprecated: use bytesWritten instead
[warn]     assert(writeMetrics.shuffleBytesWritten === file.length())
[warn]                         ^
[warn] /home/jenkins/workspace/SparkPullRequestBuilder/core/src/test/scala/org/apache/spark/storage/DiskBlockObjectWriterSuite.scala:119: method shuffleBytesWritten in class ShuffleWriteMetrics is deprecated: use bytesWritten instead
[warn]     assert(writeMetrics.shuffleBytesWritten === file.length())
[warn]                         ^
[warn] /home/jenkins/workspace/SparkPullRequestBuilder/core/src/test/scala/org/apache/spark/storage/DiskBlockObjectWriterSuite.scala:131: method shuffleBytesWritten in class ShuffleWriteMetrics is deprecated: use bytesWritten instead
[warn]     assert(writeMetrics.shuffleBytesWritten === file.length())
[warn]                         ^
[warn] /home/jenkins/workspace/SparkPullRequestBuilder/core/src/test/scala/org/apache/spark/storage/DiskBlockObjectWriterSuite.scala:135: method shuffleBytesWritten in class ShuffleWriteMetrics is deprecated: use bytesWritten instead
[warn]     assert(writeMetrics.shuffleBytesWritten === file.length())
[warn]                         ^
```
## How was this patch tested?

Tested manually on local laptop.

### CODE REVIEW

**Comment by srowen** [comment]
Deprecated methods may still be used in tests because they still need testing. As in the PR, these are not necessarily things to be changed. However I am not sure these usages are for the purpose of testing the deprecated methods, given their descriptions. I think this is OK to change. It does appear to mean things like shuffleBytesWritten has no test as a result, but, it's probably OK as it's clearly going to stay implemented as a simple alias.

**Comment by keypointt** [comment]
Thanks a lot Sean. Actually, I run these tests on my laptop and they all pass. And also, it built several times on Spark Jenkins, and every time it fails at different suites (like random failure).

More is that the failure msg is saying `class JacksonParser ` is added but what I did is just a tiny touch on the tests.
```
This patch adds the following public classes (experimental):
class JacksonParser(
```

Maybe better I just close this one

**Comment by srowen** [comment]
I'm quite sure the failure is spurious, as is the MiMa warning (it's just grepping the commit log for "class")

**Comment by srowen** [comment]
Jenkins retest this please

**Comment by keypointt** [comment]
hi @srowen , above 2 builds are using exactly the code but one failed and the other passed. I checked the failed reason and it's `org.apache.spark.sql.hive.HiveSparkSubmitSuite`, different from all previous failure reasons.

Maybe this one is beyond my capability to solve...

**Comment by srowen** [comment]
Yeah it's just a flaky test. Although people try to fix those over time, with thousands of integration tests, a few can be like that.

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
