### PR TITLE
[SPARK-6730][SQL] Allow using keyword as identifier in OPTIONS

### PR DESCRIPTION
**Pull request by viirya**
JIRA: https://issues.apache.org/jira/browse/SPARK-6730

It is very possible that keyword will be used as identifier in `OPTIONS`, this pr makes it works.

However, another approach is that we can request that `OPTIONS` can't include keywords and has to use alternative identifier (e.g. table -> cassandraTable) if needed.

If so, please let me know to close this pr. Thanks.

### CODE REVIEW

**Comment by alexliu68** [comment]
I vote to have keyword as identifier in OPTIONS. Existing code fails without giving meaningful error message if the keyword is on OPTIONS.

**Comment by marmbrus** [comment]
I think this feature seems reasonable.  Only question is, can we do it with a regex parser like we did with datatypes instead?

**Comment by yhuai** [comment]
You can find the data type parser at [here](https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/types/DataTypeParser.scala).

**Comment by viirya** [comment]
ok. regex parser makes it simpler. Thanks @marmbrus @yhuai

**Comment by marmbrus** [comment]
Thanks!  Merged to master.

**Pull request closed without merging**
