### PR TITLE
[SPARK-19868] conflict TasksetManager lead to spark stopped

### PR DESCRIPTION
**Pull request by liujianhuiouc**
## What changes were proposed in this pull request?

We must set the taskset to zombie before the DAGScheduler handles the taskEnded event. It's possible the taskEnded event will cause the DAGScheduler to launch a new stage attempt (this happens when map output data was lost), and if this happens before the taskSet has been set to zombie, it will appear that we have conflicting task sets.

### CODE REVIEW

**Comment by srowen** [comment]
CC @kayousterhout or @squito

**Comment by squito** [comment]
This looks like the right change.  In fact, I could have sworn we had recently merged in something like this -- maybe there is another pr still in flight which includes this?  @jinxing64 perhaps this is in one of your open prs?

The description needs to be updated, and we really should have a unit test (though with a very quick look I don't see a good way to test, I'll need to think about that part).  Here is my suggestion for the description:

> We must set the taskset to zombie before the dagscheduler handles the `taskEnded` event, because that event may cause the dagscheduler to launch another task attempt.  If that happens before the taskSet has been set to zombie, it will appear that we have conflicting task sets.

> The code worked before this change because dagScheduler.taskEnded() is async, so the task ended was almost always processed after the zombie status had been updated.  However, that left a race, which would occasionally go the wrong way.

**Comment by squito** [comment]
Jenkins, ok to test

**Comment by kayousterhout** [comment]
Looks good.  Expanding on Imran's comment, how about:

We must set the taskset to zombie before the DAGScheduler handles the taskEnded event.  It's possible the taskEnded event will cause the DAGScheduler to launch a new stage attempt (this happens when map output data was lost), and if this happens before the taskSet has been set to zombie, it will appear that we have conflicting task sets.

**Comment by jinxing64** [comment]
@squito 
Thanks for notification :) this is not in my pr.

**Comment by kayousterhout** [comment]
@liujianhuiouc do you have time to update the comment here?  It would be great to get this in soon.

**Comment by squito** [comment]
to be clear, I agree with Kay's rewording (in particular, I meant stage attempt, not task attempt).

Also I think its worth including a test.  You can use this: https://github.com/squito/spark/commit/3da535f5664746f57928c693a45cdc1ffdce5311

I know its very narrowly focused but it seems worth including.

**Comment by liujianhuiouc** [comment]
ok, I will  update that.

**Comment by kayousterhout** [comment]
@liujianhuiouc have you had time to fix this up yet?

**Comment by liujianhuiouc** [comment]
@kayousterhout I have already update the comments, and fix this issue, do you mean i should merge the test case by squito

**Comment by kayousterhout** [comment]
Yes can you also merge @squito's test case?

**Comment by liujianhuiouc** [comment]
@kayousterhout Done

**Comment by liujianhuiouc** [comment]
@kayousterhout Done

**Comment by squito** [comment]
lgtm assuming tests pass

**Comment by liujianhuiouc** [comment]
@squito tests fails

**Comment by liujianhuiouc** [comment]
@squito update the no-args ManualClock constructor with initialized time

**Comment by squito** [comment]
Jenkins, retest this please

**Comment by squito** [comment]
Looks like the tests were manually killed (-9).

Thanks for catching that and fixing @liujianhuiouc

**Comment by kayousterhout** [comment]
LGTM merged this to master

**Comment by zsxwing** [comment]
I think `handleFailedTask` has the similar issue. Right?

**Comment by squito** [comment]
hmm I think you're right @zsxwing that we should be updating `isZombie` before `sched.dagScheduler.taskEnded` and `sched.dagScheduler.taskSetFailed` is called, just to keep state consistent.  I don't think you'll actually hit the bug described here, as (a) if it was from a fetch failure, `isZombie` is already set first or if (b) its just a regular task failure, and it leads to the stage getting aborted, then there aren't any more retries of the stage anyway.

**Pull request closed without merging**
