### PR TITLE
[SPARK-7743] [SQL] Parquet 1.7

### PR DESCRIPTION
**Pull request by darkone23**
Resolves [SPARK-7743](https://issues.apache.org/jira/browse/SPARK-7743).

Trivial changes of versions, package names, as well as a small issue in `ParquetTableOperations.scala`

``` diff
-    val readContext = getReadSupport(configuration).init(
+    val readContext = ParquetInputFormat.getReadSupportInstance(configuration).init(
```

Since ParquetInputFormat.getReadSupport was made package private in the latest release.

Thanks
-- Thomas Omans

### CODE REVIEW

**Comment by rxin** [comment]
Jenkins, test this please.

**Comment by rxin** [comment]
Jenkins, test this please.

**Comment by rxin** [comment]
Do you mind updating the pull request title to say Parquet 1.7?

**Comment by eggsby** [comment]
Looks like I forgot to update the test code - will get to that ASAP.

**Comment by eggsby** [comment]
Whoops, looks like I just missed one package name replacement somehow.

I force pushed a fix and flattened the history.  Ready to test again :)

**Comment by rxin** [comment]
Jenkins, retest this please.

**Comment by eggsby** [comment]
Hm, not sure where `parquet.ParquetRelation` in [SQLContext](https://github.com/eggsby/spark/blob/e80e09e8515a9c3f4fc9d4aefcdf0a8015f43679/sql/core/src/main/scala/org/apache/spark/sql/SQLContext.scala#L1090) is coming from, but it's not org.apache.parquet - I'll dig a little deeper and see what is up.

**Comment by eggsby** [comment]
Figured it out, that was a package local reference - I actually missed some string based classloading using the old package names.

Working on a fix now.

**Comment by eggsby** [comment]
Fixed the pyspark examples and the Class.forName classloading in the test suites.

I've been having trouble running these integration tests on my laptop, apologies for the inconvenience.

**Comment by rxin** [comment]
Jenkins, retest this please.

**Comment by eggsby** [comment]
Looks like I blindly replaced some other package local references to `parquet.ClassName` to `org.apache.parquet.ClassName` - this was really confusing, but should be fixed now. :pray:

**Comment by rxin** [comment]
Jenkins, ok to test.

**Comment by liancheng** [comment]
retest this please

**Comment by liancheng** [comment]
@saucam also opened PR #5889 for upgrading Parquet, but 1.7.0 hadn't been released then, so he was upgrading to 1.6.0. However, the better part of #5889 is that, it also cleans up some code we added to workaround some Parquet bugs. My suggestion is, we may first try to make this PR in since it upgrades to 1.7.0, and all those renaming stuff worth a separate PR. Then I can work with @saucam to bring #5889 up to date.

@saucam How do you think?

**Comment by saucam** [comment]
hey @liancheng , sounds ok to me. We can rebase once these changes are merged.

**Comment by eggsby** [comment]
Those last two failures appear somewhat consistent, but jenkins isn't much help in showing what they are:

```
[error] Got a return code of 143 on line 211 of the run-tests script.
```

And yet no test failures reported through surefire....

I'll try to pin down what is failing sometime today, any help is appreciated :)

**Comment by srowen** [comment]
@vanzin did you say (offline) that you had some concerns about whether this ended up breaking something for user apps? or did you + Hari decide it wasn't a problem?

**Comment by vanzin** [comment]
I did (and still do) have concerns, because upgrading a dependency changes the classpath user applications see. And now, suddenly, all the old `parquet.*` packages are going to disappear, which may affect existing user applications.

I don't know enough about Spark's use of parquet to know whether any parquet types end up leaking through the API somehow, though. If that case doesn't exist, then this change would be a little more palatable. But, generally, upgrading dependencies like this is a little bit sketchy from a user's perspective.

**Comment by eggsby** [comment]
@vanzin - if people are depending on parquet transitively through spark then they simply need to make their dependency explicit, but yes - sparks public facing signatures that expose **parquet types will need to be updated downstream in user code in order to compile**.

This is inevitable unless spark intends to stay on an incubating release candidate version of parquet until some major version change like 2.0 - and is willing to accommodate the parquet bugs that come along with that.

Please be advised of the associated risk, but I still believe upgrading parquet is a good idea.

**Comment by rxin** [comment]
We don't expose Parquet in the API. If other projects depended on Parquet, the appropriate thing for them to do is to declare explicitly, which in this case would be fine.

The current Parquet version is way to buggy (i.e. no filter pushdown). We definitely need to upgrade.

**Comment by pwendell** [comment]
@rxin user apps aren't isolated though, so it isn't free to upgrade dependencies. But I agree we should upgrade this one, it's buggy and a pretty old version of a fast moving library.

We could also shade parquet down the road. In my experience though we tend to have way more issues with mature and super widely used libraries like jetty.

For young libraries where consumers are anyways constantly upgrading because they are buggy, these haven't in the past been the ones causing users the most trouble.

**Comment by rxin** [comment]
It's a different package name, so users can even use older versions of Parquet.

**Comment by pwendell** [comment]
Oh I see- then it really doesn't interfere. Users can just add the existing one.

**Comment by liancheng** [comment]
We definitely want to upgrade this one, since it has some major bugs that causes filter push-down completely unusable, which causes noticeable negative impacts on performance.

@eggsby As for the build failure, return code 143 means the process got killed by a `SIGTERM`. I guess it's because the build timed out. Let's just have another try first.

**Comment by liancheng** [comment]
retest this please

**Comment by liancheng** [comment]
@eggsby I meant, I don't think the build failure is caused by bumping Parquet version.

**Comment by rxin** [comment]
Thanks. I'm going to merge this into master.

**Comment by oliviertoupin** [comment]
To late for this to make it in Spark 1.4? Seems it would fix a lot of small things.

**Comment by eggsby** [comment]
Thanks all.

:balloon: :star2: :tada:

**Comment by rxin** [comment]
Sorry this won't make it into 1.4. Dependency bumps are risky in general and we have already cut release candidates for 1.4.

You can however do a special build yourself with this though.

**Comment by JoshRosen** [comment]
Looking through some of the Jenkins pull request builder logs, I've noticed some noisier log output from Parquet:

```
ileReader: Initiating action with parallelism: 5
Jun 4, 2015 3:04:45 PM INFO: org.apache.parquet.hadoop.ParquetFileReader: Initiating action with parallelism: 5
Jun 4, 2015 3:04:45 PM INFO: org.apache.parquet.hadoop.ParquetFileReader: reading summary file: file:/tmp/spark-a698f45b-c33a-4601-abdc-ca878a2fa499/test_insert_parquet/_common_metadata
Jun 4, 2015 3:04:45 PM WARNING: org.apache.parquet.hadoop.ParquetRecordReader: Can not initialize counter due to context is not a instance of TaskInputOutputContext, but is org.apache.hadoop.mapreduce.task.TaskAttemptContextImpl
Jun 4, 2015 3:04:45 PM WARNING: org.apache.parquet.hadoop.ParquetRecordReader: Can not initialize counter due to context is not a instance of TaskInputOutputContext, but is org.apache.hadoop.mapreduce.task.TaskAttemptContextImpl
Jun 4, 2015 3:04:45 PM INFO: org.apache.parquet.hadoop.InternalParquetRecordReader: RecordReader initialized will read a total of 5 records.
Jun 4, 2015 3:04:45 PM INFO: org.apache.parquet.hadoop.InternalParquetRecordReader: at row 0. reading next block
Jun 4, 2015 3:04:45 PM INFO: org.apache.parquet.hadoop.InternalParquetRecordReader: block read in memory in 0 ms. row count = 5
Jun 4, 2015 3:04:45 PM INFO: org.apache.parquet.hadoop.InternalParquetRecordReader: RecordReader initialized will read a total of 5 records.
Jun 4, 2015 3:04:45 PM INFO: org.apache.parquet.hadoop.InternalParquetRecordReader: at row 0. reading next block
Jun 4, 2015 3:04:45 PM INFO: org.apache.parquet.hadoop.InternalParquetRecordReader: block read in memory in 1 ms. row count = 5
Jun 4, 2015 3:04:45 PM INFO: org.apache.parquet.hadoop.ParquetFileReader: Initiating action with parallelism: 5
Jun 4, 2015 3:04:45 PM INFO: org.apache.parquet.hadoop.codec.CodecConfig: Compression: GZIP
Jun 4, 2015 3:04:45 PM INFO: org.apache.parquet.hadoop.ParquetOutputFormat: Parquet block size to 134217728
Jun 4, 2015 3:04:45 PM INFO: org.apache.parquet.hadoop.ParquetOutputFormat: Parquet page size to 1048576
Jun 4, 2015 3:04:45 PM INFO: org.apache.parquet.hadoop.ParquetOutputFormat: Parquet dictionary page size to 1048576
Jun 4, 2015 3:04:45 PM INFO: 
```

Can someone file a JIRA and investigate?

**Comment by vanzin** [comment]
Seems like the log4j.properties for sql/ needs to be updated to match the new package names.

**Comment by liancheng** [comment]
@JoshRosen @vanzin Filed SPARK-8118 for this. Adjusting `ParquetRelation.enableLogForwarding()` should fix this.

**Comment by kostya-sh** [comment]
BTW `enableLogForwarding()` should be updated as well, because name of the logger has been changed to `org.apache.parquet`. From parquet-mr Log:

    // add a default handler in case there is none
    Logger logger = Logger.getLogger(Log.class.getPackage().getName());

Another problem with `enableLogForwarding()` is that it doesn't hold to created loggers that can be garbage collected and all configuration changes will be gone. From https://docs.oracle.com/javase/6/docs/api/java/util/logging/Logger.html javadocs:  _It is important to note that the Logger returned by one of the getLogger factory methods may be garbage collected at any time if a strong reference to the Logger is not kept._

I've created https://issues.apache.org/jira/browse/SPARK-8122

**Pull request closed without merging**
