### PR TITLE
[SPARK-41309][SQL] Reuse `INVALID_SCHEMA.NON_STRING_LITERAL` instead of  `_LEGACY_ERROR_TEMP_1093`

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr aims reuse `INVALID_SCHEMA.NON_STRING_LITERAL` instead of `_LEGACY_ERROR_TEMP_1093`.

### Why are the changes needed?
Proper names of error classes to improve user experience with Spark SQL.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass GitHub Actions

### CODE REVIEW

**Comment by LuciferYang** [comment]
Test first

**Review by MaxGekk — COMMENTED** [review]
LGTM in general. Could you port related JSON/CSV tests on `checkError()`

**Comment by LuciferYang** [comment]
[381a5fb](https://github.com/apache/spark/pull/38830/commits/381a5fb940d6e996e9abdf6ff6cb23f308e87e5f) change the tests use `checkError()`

**Review by MaxGekk — APPROVED** [review]
Waiting for CI.

**Comment by LuciferYang** [comment]
```
[error] /home/runner/work/spark/spark/connector/connect/src/test/scala/org/apache/spark/sql/connect/planner/SparkConnectPlannerSuite.scala:441:67: value setI32 is not a member of org.apache.spark.connect.proto.Expression.Literal.Builder
[error]                   .setLiteral(proto.Expression.Literal.newBuilder.setI32(32))))
[error]                                                                   ^
[error] /home/runner/work/spark/spark/connector/connect/src/test/scala/org/apache/spark/sql/connect/planner/SparkConnectPlannerSuite.scala:446:67: value setI32 is not a member of org.apache.spark.connect.proto.Expression.Literal.Builder
[error]                   .setLiteral(proto.Expression.Literal.newBuilder.setI32(32)))))
[error]                                                                   ^
[error] /home/runner/work/spark/spark/connector/connect/src/test/scala/org/apache/spark/sql/connect/planner/SparkConnectPlannerSuite.scala:466:69: value setI32 is not a member of org.apache.spark.connect.proto.Expression.Literal.Builder
[error]                     .setLiteral(proto.Expression.Literal.newBuilder.setI32(32)))))
[error]                                                                     ^
[error] three errors found
```

Seems the compile error not related to this pr

**Comment by LuciferYang** [comment]
rebase to fix compile error

**Comment by MaxGekk** [comment]
+1, LGTM. Merging to master.
Thank you, @LuciferYang.

**Pull request closed without merging**
