### PR TITLE
[SPARK-5770] forbid user to overwrite jar using addJar()

### PR DESCRIPTION
**Pull request by XuTingjun**

### CODE REVIEW

**Comment by srowen** [comment]
This change doesn't make sense; it does not seem to relate to the issue you are reporting. It sounds like you are exercising the case where overwrite is enabled, but you've taken out the logic to handle it.

**Comment by XuTingjun** [comment]
Sorry, I think it's very difficult to unload the old jar and load the new jar to the classloader, maybe no solution. 
So I think the good way is restricting users do this thing, and throw the exception to tell the user.

**Comment by srowen** [comment]
The current code path appears to correctly overwrite the old file with a new one. If you're saying you think it doesn't, have you debugged way? I don't think you can just take this out.

**Comment by XuTingjun** [comment]
I have test it in spark-shell. Yearh the new jar will overwrite the old one in local dir, but the classloader has not updated. They are inconsistent. It will confuse users.

**Comment by srowen** [comment]
OK, in any event, this change can't be made. It affects other code using this method.
I am not sure (?) that this is the intended effect of `addJar`. You can add new jars; overwriting probably doesn't make the classes unload, yes. That could be an argument for disallowing overwrite for this use case, but not an argument for removing the functionality from this method for everyone.

**Comment by XuTingjun** [comment]
I also think it's controversial, but can we make the log more reasonable?

**Comment by srowen** [comment]
I suppose I'm saying that this kind of thing doesn't belong in `Utils`. It's not generally a problem to try to copy and overwrite files. If anything I think you're arguing that overwrite should be set to false just for JARs. It is false by default.

**Comment by XuTingjun** [comment]
Though it's false by default, but "spark.files.overwrite" is exposed to user. So I think we should set overwrite just false only to JARS?

**Comment by XuTingjun** [comment]
@srowen,
I think overwrite jar file has no meaning, because now code doesn't support loader new jar file. So I think forbid use to do this is more reasonable.
I add a param "isJar" to distinguish file overwite and jar overwrite.

**Comment by srowen** [comment]
Rather than add a new flag, why not just disallow overwrite in these cases?
I'd like someone else to review the logic too before forbidding this. That is, I would not want this to cause an error in a common case, just because a jar changed, but where the caller does not care about updating the classloader.

**Comment by XuTingjun** [comment]
Thanks, @srowen. I think there have the users who starts a long-running sparkcontext, and add jars to run different cases.

**Comment by srowen** [comment]
@XuTingjun I'm not sure what you're responding to. I'm first suggesting that this code change can be simpler and doesn't seem to need a new flag. But I'm also suggesting that restricting this behavior may cause errors when the user doesn't care about reloading classes. Maybe it can be a warning only.

**Pull request closed without merging**
