### PR TITLE
[SPARK-7733] [CORE] [BUILD] Update build, code to use Java 7 for 1.5.0+

### PR DESCRIPTION
**Pull request by srowen**
Update build to use Java 7, and remove some comments and special-case support for Java 6.

### CODE REVIEW

**Comment by srowen** [comment]
How would people feel about:

- Using try-with-resources where possible? I count ~50 instances, mostly in Java tests, that could use this. In some cases it would actually mean reliably closing resources where they weren't before (almost all in tests), and remove a bit of code, but worth the noise?
- Trying to use `java.nio.file.Files` instead of Guava `Files` and other things like `Objects`? Worth lessening Guava's grip on the code, or not worth the remote risk of breakage?
- `switch` on String instead of `if-else`? 3 places where this is possible

I'm going to rule out the diamond operator change for now as there is just too much all over.

**Comment by vanzin** [comment]
LGTM. As for the suggestions, they're nice, but I don't think it's worth it to go change the code just because. We can navigate towards the new APIs in new code and slowly port over old code (as other modifications are made to it).

**Comment by vanzin** [comment]
@srowen this seems to have fallen off your radar? It would be nice to get this in (as an "official" confirmation that yeah, it's ok to use java 7 APIs).

**Comment by srowen** [comment]
Yeah I was waiting until the noise of 1.4 died down just in case somehow this interfered with merging stuff in master and then into 1.4, but I think we can go ahead shortly. I will rebase.

**Comment by srowen** [comment]
I'm going to push the button this one, making Java 7 the real default for `master` (1.5+).

**Pull request closed without merging**
