### PR TITLE
[SPARK-12735] Consolidate & move spark-ec2 to AMPLab managed repository.

### PR DESCRIPTION
**Pull request by rxin**

### CODE REVIEW

**Comment by rxin** [comment]
This should be merged together with https://github.com/amplab/spark-ec2/pull/21

**Comment by srowen** [comment]
+1

**Comment by nchammas** [comment]
There was once talk of leaving the `spark-ec2` executable in here and just downloading the script from the AMPLab repo on execution. That way users can continue to use the script as though it lived in the Spark repo.

Are we not doing that anymore? It's fine with me either way; I'm just checking.

**Comment by JoshRosen** [comment]
Given the scope of other deprecations / changes in Spark 2.0, I personally think that it's okay to leave out the wrapper script which forwards to the new repo. Note that I would support the wrapper / forwarder script if this change was targeted at a 1.x release, but for 2.x I think it's okay to just make this change and add migration instructions in the release notes.

**Comment by nchammas** [comment]
Sounds fine with me and I agree with your position. :+1:

I hope this makes it easier for people to contribute to spark-ec2.

**Comment by rxin** [comment]
@shivaram I'm going to merge this one first. Let me know if there is a problem with the move. I can easily revert this.

**Pull request closed without merging**
