### PR TITLE
[SPARK-13065] [Streaming] streaming-twitter pass twitter4j.FilterQuery argument to TwitterUtils.createStream()

### PR DESCRIPTION
**Pull request by agsachin**

### CODE REVIEW

**Comment by agsachin** [comment]
List of changes:
1) Added support for passing FilterQuery object instead of just Seq of keywords
2) Java had more flexible Api syntax than that of Scala so added similar Api syntax for Scala also 
3) added test cases for the all the new Api's

**Comment by agsachin** [comment]
cc @tdas , please review this... or add some one who can review ?

**Comment by agsachin** [comment]
cc @tdas , any inputs on this PR..

**Comment by BenFradet** [comment]
I invite you to read #1717 as this has been proposed and rejected before.

**Comment by agsachin** [comment]
@BenFradet  

That's was a long thread , after reading all still I am not able to make conclusion what is final decision.
There is no package in spark packages also and twitter has not been moved out of spark, to me this seems to be a better approach, If any major changes happens in twitter4j api then we can move twitter out of spark.

**Comment by BenFradet** [comment]
Basically, the thread says that this belongs outside of Spark in a third party package.

**Comment by agsachin** [comment]
@srowen Is anyone working on third-party package for twitter, [reference](https://github.com/apache/spark/pull/1717): 

I suggest to add FilterQuery support to existing api, and move twitter Api's out of spark whenever a bigger changes is done on twitter4j api side till that time we can have twitter in spark, continuing existing api with some enhancements.

**Comment by srowen** [comment]
This is just an example integration, and I don't think it's worth investing in pretending it's a fully supported utility API. I'd close this PR but make a more elaborate integration in your own project.

**Pull request closed without merging**
