### PR TITLE
[SPARK-40484][BUILD] Upgrade log4j2 to 2.19.0

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr aims to upgrade log4j2 from 2.18.0 to 2.19.0.

### Why are the changes needed?
Log4j 2.19.0 contains new features and fixes, and this version begin to support for slf4j2:

- https://issues.apache.org/jira/browse/LOG4J2-3583 
- https://issues.apache.org/jira/browse/LOG4J2-2975

all changes can be found in the latest [changes report](https://logging.apache.org/log4j/2.x/changes-report.html#a2.19.0).

### Does this PR introduce _any_ user-facing change?
No, log4j 2.19.0 maintains binary compatibility with previous releases.

### How was this patch tested?
Pass GitHub Actions

### CODE REVIEW

**Comment by LuciferYang** [comment]
Test first

**Review by srowen — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

cc @viirya

**Review by viirya — APPROVED** [review]

**Comment by viirya** [comment]
Thanks. Merging to master.

**Comment by LuciferYang** [comment]
thanks @viirya @srowen @dongjoon-hyun

**Pull request closed without merging**
