### PR TITLE
[SPARK-4903][SQL]Backport the bug fix for SPARK-4903

### PR DESCRIPTION
**Pull request by yhuai**
The original fix was a part of https://issues.apache.org/jira/browse/SPARK-4912 (commit https://github.com/apache/spark/commit/6463e0b9e8067cce70602c5c9006a2546856a9d6).

### CODE REVIEW

**Comment by marmbrus** [comment]
Thanks, merged.

**Comment by kayousterhout** [comment]
Thanks!!

**Comment by marmbrus** [comment]
Can you close this issue please?

**Comment by yhuai** [comment]
Sure. Closing it.

**Pull request closed without merging**
