### PR TITLE
[SPARK-30324][SQL] Simplify JSON field access through dot notation

### PR DESCRIPTION
**Pull request by brkyvz**
### What changes were proposed in this pull request?

Allows JSON strings to be parsed through dot and bracket notation instead of having to write "get_json_object". We add a feature flag to control this behavior.

The column needs to be a JSON object for this to work. JSON arrays are not supported and would return nulls. If a column is a JSON array, e.g. `[{"a":1},{"a":2},...]`, `explode(from_json(colName, expr("array<string>")))` can be used to first explode the array into the JSON objects.

While the JSON column can be resolved case insensitively, the JSON fields are case sensitive.
For example, imagine the column `foo`:
```
{"a":"bar", "b":{"field1":"v1"}}
```

`foo.b.field1`, `FOO.b.field1` would work, but `foo.B.FIELD1` would return a null value.

### Why are the changes needed?

get_json_object is a hard to use and verbose API. This API would greatly help data engineers store their data as raw json columns, and data analysts access the fields that they care about, without having to deal with complicated UDFs, and JSON parsing code.

### Does this PR introduce any user-facing change?

Yes, StringType fields that contain JSON now will be accessible through dot notation.

### How was this patch tested?

Unit tests

### CODE REVIEW

**Review by MaxGekk — COMMENTED** [review]
@brkyvz Are you going to support arrays and maps as well? Should we follow SQL/JSON:
http://www.sai.msu.su/~megera/postgres/files/c067367_ISO_IEC_TR_19075-6_2017.pdf
and/or PostgreSQL implementation of jsonpath:
https://github.com/obartunov/sqljsondoc/blob/master/README.jsonpath.md

**Comment by brkyvz** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
Yeah, can we follow any standard and/or reference?

**Comment by brkyvz** [comment]
@HyukjinKwon Snowflake uses `:` notation on the column before getting nested fields. I think that's the most obvious and nicest one:
https://docs.snowflake.net/manuals/user-guide/querying-semistructured.html#dot-notation

Splunk requires you to use `spath` before you can specify which column you want:
https://www.crestdatasys.com/blogs/how-to-extract-complex-field-from-nested-json-events-using-splunk-spl/

IMHO I like Snowflake's API, because it is quite explicit. You have a clear separation between which part is case insensitive matching, and which part is case sensitive. And it is also clear that you're extracting a field from a semi-structured data format, instead of assuming the column is already parsed.

**Comment by brkyvz** [comment]
cc @marmbrus

**Comment by marmbrus** [comment]
> IMHO I like Snowflake's API, because it is quite explicit. 
I agree, but thats not what the description of this PR says?

**Comment by brkyvz** [comment]
I didn't implement it that way, since it was a new syntax. I put out that
as an option. Happy to implement it that way.

**Pull request closed without merging**
