### PR TITLE
[SPARK-33205][BUILD] Bump snappy-java version to 1.1.8

### PR DESCRIPTION
**Pull request by maropu**
### What changes were proposed in this pull request?

This PR intends to upgrade snappy-java from 1.1.7.5 to 1.1.8.

### Why are the changes needed?

For performance improvements; the released `snappy-java` bundles the latest `Snappy` v1.1.8 binaries with small performance improvements.
 - snappy-java release note: https://github.com/xerial/snappy-java/releases/tag/1.1.8
 - snappy release note: https://github.com/google/snappy/releases/tag/1.1.8  

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

GA tests.

### CODE REVIEW

**Review by srowen — APPROVED** [review]
Looks OK pending tests

**Review by Fokko — APPROVED** [review]
Thanks!

Let's do the same for Parquet: https://github.com/apache/parquet-mr/pull/833

**Review by kiszk — APPROVED** [review]

**Review by viirya — APPROVED** [review]

**Comment by viirya** [comment]
Thanks. Merging to master.

**Comment by dongjoon-hyun** [comment]
Great! Thank you all!

**Comment by maropu** [comment]
Thanks, all~

**Pull request closed without merging**
