### PR TITLE
[SPARK-7086][Deploy]Do not retry when public service start on port

### PR DESCRIPTION
**Pull request by WangTaoTheTonic**
https://issues.apache.org/jira/browse/SPARK-7086

I just fix it in master side and maybe there are more to fix?

//cc @andrewor14

### CODE REVIEW

**Comment by WangTaoTheTonic** [comment]
Jenkins, retest this please

**Comment by srowen** [comment]
This is related to https://github.com/apache/spark/pull/5575. I am not sure this is something we must force on users. There could be decent reasons to retry binding, and it doesn't 'hurt' except to waste a few tries. This is also a little arbitrary to change the behavior on just a few services. I don't think we should do this.

**Comment by WangTaoTheTonic** [comment]
Considering one condition: user submit apps to master with a port config, let's say `spark://somehost:7077`, and let workers connect to master same way. Once master open another port, for instance 7078, it will be unavailable to submit apps or accept works' registeration.

I know that retrying policy decrease probability of failing when launching master but in the meantime it increase the chance for others to connect it.

Besides I have taken a look at start-all.sh, and it pass one specify port to slave node to launch worker. Obviously worker could not take to master when master take a different port with the passed one.

@srowen I thought it must make some trouble if we take that retries on "public" port unless we found other way to solve it.

**Comment by srowen** [comment]
This change merely causes it to never retry. It doesn't cause the master to use another port, right? That would be bad for the reason you give, but this is changing the retry property.

**Comment by WangTaoTheTonic** [comment]
If retry, then master will use another port. We can see it from `Utils.scala`:
>for (offset <- 0 to maxRetries) {
...
((startPort + offset - 1024) % (65536 - 1024)) + 1024

>logWarning(s"Service$serviceString could not bind on port $tryPort. " +
            s"Attempting port ${tryPort + 1}.")

**Comment by srowen** [comment]
Ah, we don't have this change committed yet: https://github.com/apache/spark/pull/3314 (Or, a variant on this.) The right-er way to fix this is to be able to express a range of ports, which might only include 1 port, in which case there would be no more retries anyway. I suggesting focusing on resolving SPARK-4449 as a way to fix this.

**Comment by WangTaoTheTonic** [comment]
After taking a look at  https://github.com/apache/spark/pull/3314 and discussion with @scwf offline, we both think the "speifty port range for each" idea is better for issue [SPARK-7086](https://issues.apache.org/jira/browse/SPARK-7086) and [SPARK-4449](https://issues.apache.org/jira/browse/SPARK-4449). 

So I will close this and keep track at https://github.com/apache/spark/pull/3314.

@srowen  Thanks for your comments and nice idea. :smiley:

**Pull request closed without merging**
