### PR TITLE
[MINOR][SQL] Remove unused an error class and query error methods

### PR DESCRIPTION
**Pull request by MaxGekk**
### What changes were proposed in this pull request?
In the PR, I propose to remove the unused error class `CANNOT_INFER_DATE` and some unused methods/parameters from `QueryExecutionErrors` and `QueryCompilationErrors`.

### Why are the changes needed?
To improve code maintainability.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
By existing tests, GA.

### CODE REVIEW

**Comment by MaxGekk** [comment]
@panbingkun @LuciferYang @itholic @cloud-fan @srielau Could you review this PR, please.

**Review by itholic — APPROVED** [review]
+1, LGTM

**Comment by MaxGekk** [comment]
Merging to master. Thank you, @itholic for review.

**Comment by LuciferYang** [comment]
late LGTM

**Pull request closed without merging**
