### PR TITLE
[SPARK-44419][SQL] Support to extract partial filters of datasource v2 table and push them down

### PR DESCRIPTION
**Pull request by caican00**
### What changes were proposed in this pull request?
For this query
```
explain select * from iceberg_xxx.tmp.xxx_tst_pat 
where date = 20221011 or (date = 20221012 and char_length(col2)=8)
```

Before Optimization，no predicates were pushed down.
image

After Optimization, `(date = 20221011 OR date = 20221012)` was pushed down.
image

### Why are the changes needed?
Performance optimization.
Avoid full table scanning.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
New UT.

### CODE REVIEW

**Comment by caican00** [comment]
Could you help me to review this PR? 
gently ping @huaxingao

**Comment by Yikf** [comment]
Could you share the plan string before and after optimization?

**Comment by caican00** [comment]
> Could you share the plan string before and after optimization?

Thanks for reviewing. I added screenshots of before and after optimization to the description.

**Comment by caican00** [comment]
Could you help me to review this PR?
gently ping @huaxingao
Thanks.

**Comment by caican00** [comment]
gently ping @ulysses-you 
Could you help to review this patch? Thanks

**Pull request closed without merging**
