### PR TITLE
[SPARK-39060][SQL] Typo in error messages of decimal overflow

### PR DESCRIPTION
**Pull request by vitaliili-db**
### What changes were proposed in this pull request?

This PR removes extra curly bracket from debug string for Decimal type in SQL.

### Why are the changes needed?

Typo in error messages of decimal overflow.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

By running updated test:
```
$ build/sbt "sql/testOnly org.apache.spark.sql.SQLQueryTestSuite -- -z decimalArithmeticOperations.sql"
```

### CODE REVIEW

**Review by sunchao — APPROVED** [review]

**Review by yaooqinn — APPROVED** [review]
LGTM

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
seems like some more tests should be fixed tho.

**Review by MaxGekk — APPROVED** [review]

**Review by singhpk234 — APPROVED** [review]

**Comment by MaxGekk** [comment]
+1, LGTM. Merging to master.
Thank you, @vli-databricks and all for review.

**Comment by MaxGekk** [comment]
@vli-databricks Could you backport the changes to branch-3.3 (the PR causes conflicts in 3.3 while merging), please.

**Pull request closed without merging**
