### PR TITLE
[MINOR][SQL][DOCS] Update schema_of_csv and schema_of_json doc

### PR DESCRIPTION
**Pull request by viirya**
### What changes were proposed in this pull request?

This minor PR updates the docs of `schema_of_csv` and `schema_of_json`. They allow foldable string column instead of a string literal now.

### Why are the changes needed?

The function doc of  `schema_of_csv` and `schema_of_json` are not updated accordingly with previous PRs.

### Does this PR introduce _any_ user-facing change?

Yes, update user-facing doc.

### How was this patch tested?

Unit test.

### CODE REVIEW

**Comment by viirya** [comment]
cc @HyukjinKwon @cloud-fan

**Review by HyukjinKwon — APPROVED** [review]

**Review by maropu — APPROVED** [review]

**Review by MaxGekk — COMMENTED** [review]
Should we fix Python API? or it supports only literals?
- https://github.com/apache/spark/blob/4c8ee8856cb9714d433456fb0ce44dfebb00d83f/python/pyspark/sql/functions.py#L3530
- https://github.com/apache/spark/blob/4c8ee8856cb9714d433456fb0ce44dfebb00d83f/python/pyspark/sql/functions.py#L3567

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM (except @MaxGekk 's comments).

**Comment by HyukjinKwon** [comment]
Let me just merge this in. All relevant tests such as build and linters passed

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by viirya** [comment]
Thanks all!

**Pull request closed without merging**
