### PR TITLE
[SPARK-10381] Fix mixup of taskAttemptNumber & attemptId in OutputCommitCoordinator (branch-1.4 backport)

### PR DESCRIPTION
**Pull request by JoshRosen**
This is a backport of #8544 to `branch-1.4` for inclusion in 1.4.2.

### CODE REVIEW

**Comment by JoshRosen** [comment]
Jenkins, retest this please.

**Comment by JoshRosen** [comment]
Jenkins, retest this please.

**Comment by JoshRosen** [comment]
Jenkins, retest this please.

**Comment by yhuai** [comment]
LGTM. We can merge it once jenkins is good.

**Comment by JoshRosen** [comment]
It looks like there haven't been any new commits to branch-1.4 since when this was last tested, so I'm going to merge this now.

**Pull request closed without merging**
