### PR TITLE
[SPARK-22797][ML][PYTHON] Bucketizer support multi-column

### PR DESCRIPTION
**Pull request by zhengruifeng**
### What changes were proposed in this pull request?
Bucketizer support multi-column in the python side

### Why are the changes needed?
Bucketizer should support multi-column like the scala side.

### Does this PR introduce any user-facing change?
yes, this PR add new Python API

### How was this patch tested?
added testsuites

### CODE REVIEW

**Comment by zhengruifeng** [comment]
The previous pr https://github.com/apache/spark/pull/19892 was reverted because it cause following py test suite failure, see issue https://github.com/apache/spark/pull/20410 for detail.
Now, this issue was already fixed by https://issues.apache.org/jira/browse/SPARK-23234.

**Comment by zhengruifeng** [comment]
cc @srowen @mgaido91 @BryanCutler @holdenk

**Comment by mgaido91** [comment]
LGTM

**Comment by zhengruifeng** [comment]
retest this please

**Review by srowen — APPROVED** [review]
Looks good pending tests (Jenkins is offline)

**Comment by zhengruifeng** [comment]
Merged to master. Thanks all for reviewing!

**Pull request closed without merging**
