### PR TITLE
[SPARK-45767][CORE] Delete `TimeStampedHashMap` and its UT

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to delete `TimeStampedHashMap` and its UT.

### Why are the changes needed?
During Pr https://github.com/apache/spark/pull/43578, we found that the class `TimeStampedHashMap` is no longer in use. Based on the suggestion, we have removed it. https://github.com/apache/spark/pull/43578#discussion_r1378687555

- First time this class `TimeStampedHashMap` be introduced:
https://github.com/apache/spark/commit/b18d70870a33a4783c6b3b787bef9b0eec30bce0#diff-77b12178a7036c71135074c6ddf7d659e5a69906264d5e3061087e4352e304ed introduced this data structure
- After https://github.com/apache/spark/pull/22339, this class `TimeStampedHashMap` is only being used in UT `TimeStampedHashMapSuite`. 
So, after Spark 3.0, this data structure has not been used by any production code of Spark.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by panbingkun** [comment]
cc @LuciferYang @dongjoon-hyun

**Comment by panbingkun** [comment]
The issue of `appveyor` is not related to this PR.
https://github.com/apache/spark/pull/43631

**Comment by LuciferYang** [comment]
I think the description of the PR should be clearer, like when this class was introduced, why it is no longer used, instead of referencing a comments.

**Comment by panbingkun** [comment]
> I think the description of the PR should be clearer, like when this class was introduced, why it is no longer used, instead of referencing a comments.

Done.

**Review by LuciferYang — APPROVED** [review]
+1, LGTM if test pass

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Review by beliefer — APPROVED** [review]

**Comment by LuciferYang** [comment]
Merged into master for Spark 4.0. Thanks @panbingkun @dongjoon-hyun and @beliefer

**Pull request closed without merging**
