### PR TITLE
[SPARK-40040][SQL] Push local limit to both sides if join condition is empty

### PR DESCRIPTION
**Pull request by wangyum**
### What changes were proposed in this pull request?

Similar to https://github.com/apache/spark/pull/31567. This PR enhances `LimitPushDown` to support  push local limit to both sides if it is outer join and join condition is empty. It is safe to push down because without join condition is actually a cross join.

### Why are the changes needed?

Improve query performance. For example:
image

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Unit test.

### CODE REVIEW

**Comment by wangyum** [comment]
cc @cloud-fan

**Comment by cloud-fan** [comment]
cc @sigmod

**Comment by cloud-fan** [comment]
The idea is very simple. We should explain the rationale for this optimization in the PR description, instead of giving a screenshot which doesn't provide much value to understand this optimization.

**Review by cloud-fan — APPROVED** [review]

**Comment by cloud-fan** [comment]
cc @sigmod

**Comment by wangyum** [comment]
Merged to master.

**Pull request closed without merging**
