### PR TITLE
[SPARK-6185][SQL] Deltele repeated TOKEN. "TOK_CREATEFUNCTION"  and  "TOK_SHOWINDEXES"

### PR DESCRIPTION
**Pull request by pzzs**
Line 65    "TOK_SHOWINDEXES"
Line 66    "TOK_SHOWINDEXES"

Line 84    "TOK_CREATEFUNCTION"
Line 106  "TOK_CREATEFUNCTION"

### CODE REVIEW

**Comment by chenghao-intel** [comment]
ok to test

**Comment by chenghao-intel** [comment]
Good catch, LGTM.

**Comment by adrian-wang** [comment]
Maybe we can sort all these tokens in alphabetic order to avoid duplicate.

**Comment by DoingDone9** [comment]
Anyone could test it? @chenghao-intel @marmbrus

**Comment by yhuai** [comment]
ok to test

**Comment by DoingDone9** [comment]
@yhuai  Could it be merged?

**Comment by adrian-wang** [comment]
Again, I think we'd better sort these tokens in alphabetic order to avoid further duplicate

**Comment by marmbrus** [comment]
+1 to sorting.

**Comment by DoingDone9** [comment]
It is a good idea that to sorting  , i will do it @adrian-wang  @marmbrus  @chenghao-intel

**Comment by DoingDone9** [comment]
I hava opened a new pr for sorting  these tokens in alphabetic. 
https://github.com/apache/spark/pull/4973 @yhuai  @marmbrus

**Comment by srowen** [comment]
Mind closing this PR?

**Comment by DoingDone9** [comment]
yes  i will close it @srowen

**Pull request closed without merging**
