### PR TITLE
[SPARK-39042][CORE][SQL][SS] Use `Map.values()` instead of `Map.entrySet()` in scene that don't use keys

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
Some code in Spark use `Map.entrySet()`, but doesn't need a keys, this pr use `Map.values()` to simplified them.

### Why are the changes needed?
Code simplification

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass GA

### CODE REVIEW

**Comment by LuciferYang** [comment]
This is all

**Review by srowen — APPROVED** [review]
Any other instances? this is fine

**Comment by LuciferYang** [comment]
only found these now

**Review by srowen — APPROVED** [review]

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
