### PR TITLE
[Minor] Remove permission for execution from spark-shell.cmd

### PR DESCRIPTION
**Pull request by sarutak**
.cmd files in bin is not set permission for execution except for spark-shell.cmd.
Let's unify that.

### CODE REVIEW

**Comment by andrewor14** [comment]
Hm, looks like everything else (not cmd) has 755 permissions though (except `load-spark-env.sh`)

**Comment by sarutak** [comment]
Yes *.sh has 755 permissions but all cmd files except for spark-shell.cmd has 655. Is there any policy?

**Comment by srowen** [comment]
All other *.cmd files are 644 actually. I assume it's because .cmd files are Windows scripts and POSIX permission bits won't matter for them. If so, then the permissions are pretty irrelevant, but `spark-shell.cmd` could be 644 purely for consistency.

`load-spark-env.sh` could be 755, but I imagine it's not since it's not meant to be something executed by itself. It's sourced in other scripts. By that logic I'm not sure `compute-classpath.sh` should have execute bit set, but don't know.

**Comment by vanzin** [comment]
BTW, I was testing some things on Windows the other day, and the 644 permissions did turn out to be an issue. Probably because I was rsyncing the files from a Linux host and rsync would then translate the permissions to not allow them to be executable on the Windows side...

**Comment by srowen** [comment]
Since this is trivial and makes the .cmd file match the others, I'll merge this.

**Comment by JoshRosen** [comment]
I've also merged this into `branch-1.3` (1.3.0).

**Pull request closed without merging**
