### PR TITLE
[SPARK-9727][STREAMING][BUILD] Updated streaming kinesis SBT project name to be more consistent

### PR DESCRIPTION
**Pull request by tdas**

### CODE REVIEW

**Comment by tdas** [comment]
@zsxwing Take a look.

**Comment by zsxwing** [comment]
LGTM

**Comment by tdas** [comment]
retest this please.

**Comment by tdas** [comment]
retest this please.

**Comment by tdas** [comment]
I think I will merge this. Two test runs have passed and I made sure that the python tests were run, which ensures that all the requires streaming JARs were generated correctly.

**Comment by tdas** [comment]
Thanks @zsxwing  for reviewing. Merging this to master and 1.5

**Pull request closed without merging**
