### PR TITLE
[SPARK-7267][SQL]Push down Project when it's child is Limit

### PR DESCRIPTION
**Pull request by pzzs**
SQL

```
select key from (select key,value from t1 limit 100) t2 limit 10
```

Optimized Logical Plan before modifying

```
== Optimized Logical Plan ==
Limit 10
  Project key#228
    Limit 100
      MetastoreRelation default, t1, None
```

Optimized Logical Plan after modifying

```
== Optimized Logical Plan ==
Limit 10
  Limit 100
    Project key#228
      MetastoreRelation default, t1, None
```

After this, we can combine limits

### CODE REVIEW

**Comment by rxin** [comment]
Jenkins, test this please.

**Comment by scwf** [comment]
Retest this please

**Comment by rxin** [comment]
Jenkins, test this please.

**Comment by rxin** [comment]
Thanks. Merging in master.

**Pull request closed without merging**
