### PR TITLE
[SPARK-37105][TEST] Pass all UTs in `sql/hive` with Java 17

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
The main change of this pr as follows:

- Add `extraJavaTestArgs` to `argLine` of `scalatest-maven-plugin` in `sql/hive/pom.xml`
- Add  `--add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED` to default java module options because some UTs failed due to

```
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private volatile int java.util.concurrent.atomic.AtomicBoolean.value accessible: module java.base does not "opens java.util.concurrent.atomic" to unnamed module @2744cc4a
```
 

### Why are the changes needed?
Pass UT with JDK 17

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?

- Pass the Jenkins or GitHub Action
- Manual test use Java17 build + Java17 run (both openjdk version "17" 2021-09-14 LTS)

Add `extraJavaTestArgs` to `scalatest-maven-plugin` in `sql/hive/pom.xml`  first and use Java 17 to run the following two commands:
 
```
build/mvn clean install -Phadoop-3.2 -Phive-2.3 -Phive -pl sql/hive -am -DskipTests
build/mvn test -Phadoop-3.2 -Phive-2.3 -Phive -pl sql/hive
```

**Before**

```
Run completed in 1 hour, 2 minutes, 3 seconds.
Total number of tests run: 3547
Suites: completed 117, aborted 0
Tests: succeeded 3525, failed 22, canceled 6, ignored 605, pending 0
*** 22 TESTS FAILED ***
```

**After**

```
Run completed in 1 hour, 4 minutes, 41 seconds.
Total number of tests run: 3547
Suites: completed 117, aborted 0
Tests: succeeded 3547, failed 0, canceled 6, ignored 605, pending 0
All tests passed.
```

- Manual test use Java8 build + Java17 run

Use Java 8(openjdk version "1.8.0_292") to run the build command:

```
build/mvn clean install -Phadoop-3.2 -Phive-2.3 -Phive -pl sql/hive -am -DskipTests
```

And Java 17(openjdk version "17" 2021-09-14 LTS) to run the test command:

```
build/mvn test -Phadoop-3.2 -Phive-2.3 -Phive -pl sql/hive
```

**Before**

```
Run completed in 1 hour, 1 minute, 10 seconds.
Total number of tests run: 3547
Suites: completed 117, aborted 0
Tests: succeeded 3525, failed 22, canceled 6, ignored 605, pending 0
*** 22 TESTS FAILED ***
```

**After**

```
Run completed in 1 hour, 6 minutes, 6 seconds.
Total number of tests run: 3547
Suites: completed 117, aborted 0
Tests: succeeded 3547, failed 0, canceled 6, ignored 605, pending 0
All tests passed.

```

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by viirya** [comment]
@dongjoon-hyun This is for a while but do you remember how did you resolve it? I encountered this recently on Intel Macbook Pro with macOS Ventura 13.2 + Java 11 (openjdk 11.0.18).

**Comment by dongjoon-hyun** [comment]
Oh, what is your specific situation (branch and error message), @viirya ? Is it Apache Spark 3.3.2 RC1 vote?

**Comment by viirya** [comment]
I got 

```[INFO] Running org.apache.spark.network.crypto.AuthEngineSuite     
WARNING: /usr/local/Cellar/openjdk@11/11.0.18/libexec/openjdk.jdk/Contents/Home/bin/java is loading libcrypto in an unsafe way
```

when running on `master` branch.

**Review by HyukjinKwon — COMMENTED** [review]
sorry I was opening a wrong tab. Ignore this comment.

**Pull request closed without merging**
