### PR TITLE
[MINOR][SQL][TESTS] Move ResolveDefaultColumnsSuite to 'o.a.s.sql'

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR moves `ResolveDefaultColumnsSuite` from `catalyst/analysis` package to `sql` package.

### Why are the changes needed?

To fix the code layout.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the CI

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
cc @dtenedor and @gengliangwang

**Comment by dtenedor** [comment]
LGTM! Thanks @dongjoon-hyun for the clean up.

**Review by gengliangwang — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @dtenedor and @gengliangwang 

I verified the relocated suite manually.
```
$ build/sbt "sql/testOnly *.ResolveDefaultColumnsSuite"
...
[info] ResolveDefaultColumnsSuite:
12:21:59.363 WARN org.apache.hadoop.util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[info] - column without default value defined (null as default) (4 seconds, 19 milliseconds)
[info] - column with default value defined (1 second, 28 milliseconds)
[info] - INSERT into partitioned tables (1 second, 435 milliseconds)
[info] - SPARK-43085: Column DEFAULT assignment for target tables with multi-part names (555 milliseconds)
[info] - SPARK-43313: Column default values with implicit coercion from provided values (473 milliseconds)
12:22:07.418 WARN org.apache.spark.sql.ResolveDefaultColumnsSuite:

===== POSSIBLE THREAD LEAK IN SUITE o.a.s.sql.ResolveDefaultColumnsSuite, threads: ForkJoinPool.commonPool-worker-27 (daemon=true), ForkJoinPool.commonPool-worker-19 (daemon=true), rpc-boss-3-1 (daemon=true), ForkJoinPool.commonPool-worker-5 (daemon=true), shuffle-boss-6-1 (daemon=true), ForkJoinPool.commonPool-worker-23 (daemon=true), ForkJoinPool.commonPool-worker-9 (daemon=true) =====
[info] Run completed in 9 seconds, 362 milliseconds.
[info] Total number of tests run: 5
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 5, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[success] Total time: 28 s, completed Jun 8, 2023, 12:22:07 PM
```

**Comment by dongjoon-hyun** [comment]
Merged to master/3.4.

**Pull request closed without merging**
