### PR TITLE
[SPARK-41442][SQL][FOLLOWUP] SQLMetric should not expose -1 value as it's invalid

### PR DESCRIPTION
**Pull request by cloud-fan**
### What changes were proposed in this pull request?

This is a followup of https://github.com/apache/spark/pull/38969 to fix a regression.

SQL UI is not the only way for end users to see the SQL metrics. They can also access the accumulator values in the physical plan programmatically via query execution listener. We should be consistent with the SQL UI and not expose the -1 value.

### Why are the changes needed?

make SQL UI and the accumulator value consistent

### Does this PR introduce _any_ user-facing change?

Yes, as end users can access accumulator values directly.

### How was this patch tested?

existing tests

### CODE REVIEW

**Comment by cloud-fan** [comment]
cc @viirya

**Review by viirya — APPROVED** [review]

**Review by viirya — COMMENTED** [review]
Thanks for creating this followup!

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Review by dongjoon-hyun — COMMENTED** [review]
+1, LGTM. Thank you!

**Pull request closed without merging**
