### PR TITLE
[SPARK-38519][SQL] AQE throw exception should respect SparkFatalException

### PR DESCRIPTION
**Pull request by ulysses-you**
### What changes were proposed in this pull request?

Throw underlying exception in `SparkFatalException`

### Why are the changes needed?

BroadcastExchangeExec will wrap fatal exception inside SparkFatalException and unwarp it  before throw.

AQE should also respect SparkFatalException  and throw original error.

Before:
```
Caused by: org.apache.spark.util.SparkFatalException
	at org.apache.spark.sql.execution.exchange.BroadcastExchangeExec.$anonfun$relationFuture$1(BroadcastExchangeExec.scala:168)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withThreadLocalCaptured$1(SQLExecution.scala:191)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748) 
```

### Does this PR introduce _any_ user-facing change?

yes, the exception may be changed

### How was this patch tested?

manually tested

### CODE REVIEW

**Comment by ulysses-you** [comment]
cc @cloud-fan @HyukjinKwon @yaooqinn

**Comment by HyukjinKwon** [comment]
@maryannxue FYI

**Comment by ulysses-you** [comment]
gently ping since 3.3.0 will be cut soon. thank you !

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Comment by ulysses-you** [comment]
thank you for merging !

**Pull request closed without merging**
