### PR TITLE
[SPARK-44138][SQL] Prohibit non-deterministic expressions, subqueries and aggregates in MERGE conditions

### PR DESCRIPTION
**Pull request by aokolnychyi**
### What changes were proposed in this pull request?

This PR adds descriptive errors for cases when MERGE statements that are converted into executable plans by Spark contain unsupported expressions such as non-deterministic functions, subqueries, and aggregates.

### Why are the changes needed?

These changes are needed as the current version of the row-level framework does not support these operations. Keep in mind the new validation only applies to MERGE statements that are rewritten by `RewriteMergeIntoTable`. Data sources that inject their own implementation are NOT affected.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

This PR comes with tests.

### CODE REVIEW

**Comment by aokolnychyi** [comment]
The test failure is unrelated, triggered again.

```
org.apache.spark.storage.BlockManagerProactiveReplicationSuite
```

**Comment by aokolnychyi** [comment]
@dongjoon-hyun, this is a follow-up PR to #41448 and #41577.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @aokolnychyi .
Merged to master for Apache Spark 3.5.0.

**Comment by aokolnychyi** [comment]
Thank you, @dongjoon-hyun!

**Pull request closed without merging**
