### PR TITLE
[SPARK-31002][CORE][DOC][3.0] Add version information to the configuration of Core

### PR DESCRIPTION
**Pull request by beliefer**
### What changes were proposed in this pull request?
This PR follows https://github.com/apache/spark/pull/27847 and used to spark3.0.

### Why are the changes needed?
Supplemental configuration version information.

### Does this PR introduce any user-facing change?
'No'.

### How was this patch tested?
Jenkins test.

### CODE REVIEW

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
Hi, @beliefer .
`.version` is used in `master` only.

**Comment by dongjoon-hyun** [comment]
I'll close this PR to prevent accidental merging. Please let me know if there is an explicit request from another committer about this. We can discuss about that here.

**Comment by dongjoon-hyun** [comment]
Got it. I saw the history on the original PR.
cc @gatorsmile and @HyukjinKwon

**Comment by HyukjinKwon** [comment]
Thanks for double checking, @dongjoon-hyun.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to branch-3.0.

**Comment by dongjoon-hyun** [comment]
Thanks!

**Comment by beliefer** [comment]
@HyukjinKwon Due to some problems previously communicated, this PR not back port docs.
The origin Commit in this ticket:
https://github.com/apache/spark/pull/27847
https://github.com/apache/spark/pull/27852
https://github.com/apache/spark/pull/27913
https://github.com/apache/spark/pull/27931
Do I need to resubmit a PR for the changes of documents related above four PR? or you revert this PR and back port the origin four PR?

**Comment by HyukjinKwon** [comment]
Hm, I see. Let me revert back https://github.com/apache/spark/commit/a5444db82ace1bfca32ec8d5b9f9823e91ac9511 and https://github.com/apache/spark/commit/af7fa9d12622c3b2b169c4a58d143bc21ed9e784.

Can you open a PR again that picks original commits? Let's sync the commit logs between master and branch-3.0.

**Comment by HyukjinKwon** [comment]
Reverted from branch-3.0 due to commit log mismatches.

**Comment by beliefer** [comment]
You not need revert af7fa9d. because `SQL` not exists pure documents.

**Comment by beliefer** [comment]
I will supplement docs for a5444db.

**Comment by HyukjinKwon** [comment]
But there are differences between https://github.com/apache/spark/pull/28116 and https://github.com/apache/spark/pull/27691. We should keep the commit logs - don't need to combine followups into single PRs.

**Comment by HyukjinKwon** [comment]
@beliefer, my goal here is to keep the exact same commit logs between master and branch-3.0. What I expect in your PR is to, in any way, point out each commit merged in master so that I can see the tests pass against branch-3.0 and backport accordingly.

I can only cherry-pick and manually backport the PR links or commit logs you pointed out; otherwise, I should manually verify each PR as you did duplicatedly.

**Comment by HyukjinKwon** [comment]
Keeping the exact same commit log is useful when you revert a specific change. For example, you can directly `git revert [a specific commit]` against both `master` and `branch-3.0` identically.

If the commit logs are different, you should manually edit the codes when you revert it from `branch-3.0`.

**Comment by beliefer** [comment]
I understand now. You means I create PR to check the change is good for branch-3.0. The check PR list related commit log. If the PR pass the Jenkins test, you will follow the list to back port each origin PR.
All work is done except https://github.com/apache/spark/pull/28149. Thanks for your hard work too.

**Pull request closed without merging**
