### PR TITLE
[SPARK-22154] add a shutdown hook that explains why the output is terminating

### PR DESCRIPTION
**Pull request by liu-zhaokun**
It would be nice to add a shutdown hook here that explains why the output is terminating. Otherwise if the worker dies the executor logs will silently stop.

### CODE REVIEW

**Comment by liu-zhaokun** [comment]
It says that "It would be nice to add a shutdown hook here that explains why the output is terminating. Otherwise if the worker dies the executor logs will silently stop" in "TODO",I think it is justified.

**Comment by srowen** [comment]
Why a shutdown hook instead of something in the lifecycle of this process?

**Comment by liu-zhaokun** [comment]
@srowen 
Sorry,I do not understand what you mean，could you explain it again?

**Comment by srowen** [comment]
Where does the worker exit normally or in case of an error? Why not log there?

**Comment by liu-zhaokun** [comment]
@srowen 
This hook is only for DriverRunner.I think there was some log like this for normal executor when worker shutdown.

**Comment by jiangxb1987** [comment]
I'm going to close this PR because it goes stale, please feel free to reopen it or open another PR if anyone have more thoughts on this issue.

**Pull request closed without merging**
