### PR TITLE
Update MimaExcludes now Spark 1.6 is in Maven.

### PR DESCRIPTION
**Pull request by rxin**

### CODE REVIEW

**Comment by rxin** [comment]
Looks like I'm misunderstanding how mima works ... closing this pr.

**Comment by rxin** [comment]
Reopening -- since I might've

**Comment by JoshRosen** [comment]
@rxin, it looks like this has now passed MiMa checks in case you want to merge it.

**Comment by rxin** [comment]
Merging - thanks.

**Pull request closed without merging**
