### PR TITLE
[SPARK-22172][CORE] Worker hangs when the external shuffle service port is already in use

### PR DESCRIPTION
**Pull request by devaraj-kavali**
## What changes were proposed in this pull request?

Handling the NonFatal exceptions while starting the external shuffle service, if there are any NonFatal exceptions it logs and continues without the external shuffle service.

## How was this patch tested?

I verified it manually, it logs the exception and continues to serve without external shuffle service when BindException occurs.

### CODE REVIEW

**Comment by jerryshao** [comment]
IMO I think it might be better to throw an exception instead of shifting to another shuffle. Since user want to use external shuffle explicitly, letting user to know the issues and fix the issue would be better. 

Besides, this will lead to an issue if Cluster manager changing to not start shuffle service, while Spark application still assume external shuffle is on, and tries to connect to external shuffle service.

**Comment by devaraj-kavali** [comment]
Thanks @jerryshao for the comment.

> IMO I think it might be better to throw an exception instead of not starting shuffle service. Since user want to use external shuffle explicitly, letting user to know the issues and fix the issue would be better.

I considered this before creating PR but the Node Manager continues to run when spark shuffle service gets BindException, thought to make the behavior inline with NM spark shuffle.

Please let me know if you think to make the Worker to go down on external shuffle service start failure I can update this PR.

**Comment by devaraj-kavali** [comment]
@jerryshao Please let me know if you don't convince with the above comment, I can make the changes to PR to make Worker do down on external shuffle service start failure.

**Comment by jerryshao** [comment]
Sorry for the late response. I understand you purpose now. I think such behavior discrepancy is not a big problem. 

I guess the reason why NM still run with exception is that NM doesn't serve only for Spark, but also MR/TEZ, so the failure of Spark external service should not affect MR's.

Based on your comment above, I don't have a strong preference on either, I think both are OK. Maybe you can ping others to get their feedbacks.

**Comment by jiangxb1987** [comment]
IMO we should throw a new Exception in order to fail fast, it may cause some weird issues running with an ESS that you can't connect to.

**Comment by devaraj-kavali** [comment]
@jiangxb1987 Thanks for the comment, I made the change which throws exception and exits the worker.

**Comment by jerryshao** [comment]
I'm OK with the current changes.

**Comment by jerryshao** [comment]
OK, let me merge to master branch.

**Comment by cloud-fan** [comment]
we should update PR description too, but it's too late now...

**Comment by jerryshao** [comment]
Sorry I didn't notice it, will double-check next time.

**Pull request closed without merging**
