### PR TITLE
[MINOR][GRAPHX] Correct typos in the sub-modules: graphx, external, and examples

### PR DESCRIPTION
**Pull request by jsoref**
### What changes were proposed in this pull request?

This PR intends to fix typos in the sub-modules: graphx, external, and examples.
Split per @holdenk https://github.com/apache/spark/pull/30323#issuecomment-725159710

NOTE: The misspellings have been reported at https://github.com/jsoref/spark/commit/706a726f87a0bbf5e31467fae9015218773db85b#commitcomment-44064356

### Why are the changes needed?

Misspelled words make it harder to read / understand content.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

No testing was performed

### CODE REVIEW

**Comment by maropu** [comment]
ok to test

**Comment by maropu** [comment]
Since `examples` and `external` are not updated actively, could you add typo fixes for them in this PR?
https://gist.github.com/maropu/c737f1a40ea48758d8bb397bc078dc68#file-gistfile1-txt-L123-L148

**Comment by jsoref** [comment]
Dropped 60ccc957ee41bf145c9721f2b1d0154ae8f7a579 as it was dependent on the part of 894462594ad52fae13bb8481e001b4a66ed818a9 that's outside this scope.

**Review by maropu — APPROVED** [review]

**Review by srowen — APPROVED** [review]

**Comment by maropu** [comment]
Thanks! Merged to master. Could you open a PR to backport this into branch-3.0/2.4? Minor though, it would be nice to fix them there, too, for better code quality.

**Pull request closed without merging**
