### PR TITLE
[SPARK-33086][FOLLOW-UP] Remove unused Optional import from pyspark.resource.profile stub

### PR DESCRIPTION
**Pull request by zero323**
### What changes were proposed in this pull request?

Remove unused `typing.Optional` import from `pyspark.resource.profile` stub.

### Why are the changes needed?

Since SPARK-32319 we don't allow unused imports.  However, this one slipped both local and CI tests for some reason.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Existing tests and mypy check.

### CODE REVIEW

**Comment by zero323** [comment]
cc @HyukjinKwon (sorry, I should've seen that).

**Review by srowen — APPROVED** [review]

**Review by HyukjinKwon — APPROVED** [review]
It's okay since the PR is already open but let's avoid fixing only a couple of in a separate PR in general. They don't affect the main codes and can be fixed together when you touch these codes later.

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by zero323** [comment]
> It's okay since the PR is already open but let's avoid fixing only a couple of in a separate PR in general. They don't affect the main codes and can be fixed together when you touch these codes later.

Noted. I couldn't identify why it didn't trigger error in CI and thought it is better to fix it now, before it starts failing build at some point in the future.

Thanks.

**Pull request closed without merging**
