### PR TITLE
[SPARK-40993][CONNECT][PYTHON][DOCS] Migrate markdown style README to PySpark Development Documentation 

### PR DESCRIPTION
**Pull request by amaliujia**
### What changes were proposed in this pull request?

This PR consolidates the development facing documentation of Spark Connect Python client into existing PySpark development doc (more specifically: `python/docs/developmement/testing.rst`).

### Why are the changes needed?

Improve development documentation.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Documentation check script.

### CODE REVIEW

**Comment by amaliujia** [comment]
cc @HyukjinKwon @grundprinzip

**Review by HyukjinKwon — DISMISSED** [review]
LGTM from a cursory look. Thanks for doing this.

cc @itholic mind double checking if anything is broken or inconsistent?

**Comment by HyukjinKwon** [comment]
Yeah, I am fine with that.

**Comment by itholic** [comment]
Looks good, and I'm also fine with.

**Comment by HyukjinKwon** [comment]
Fixed in https://github.com/apache/spark/pull/38470 for now.

Per https://github.com/apache/spark/pull/38477#issuecomment-1299705536, let me close this for now.

**Comment by HyukjinKwon** [comment]
Sicen we're going to package together, let's migrate this docs too. cc @zhengruifeng too

**Pull request closed without merging**
