### PR TITLE
[SPARK-27823][CORE] Add an abstraction layer for resource handling

### PR DESCRIPTION
**Pull request by tgravescs**
## What changes were proposed in this pull request?

Add an abstraction layer for the Resource layer stuff to make it more readable.  
I think the only actual behavioral change here is that now you can specify both a resourceFileOpt and the discovery script for different resources and it will join them together.  Previously it only allowed one or the other option to be used.  I did also add in one more warning for the user when the resource configurations will waste resources.

## How was this patch tested?

Unit tests and ran on local cluster, yarn

### CODE REVIEW

**Comment by tgravescs** [comment]
@jiangxb1987 @mengxr

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by tgravescs** [comment]
looking at test failures to see if I can reproduce locally

**Comment by mengxr** [comment]
making a pass

**Comment by mengxr** [comment]
@tgravescs I will do some refactoring and send a PR to you.

**Comment by tgravescs** [comment]
@mengxr  please just put up a PR

**Comment by mengxr** [comment]
will do

**Pull request closed without merging**
