### PR TITLE
[SPARK-21668][CORE] Ability to run driver programs within a container

### PR DESCRIPTION
**Pull request by tashoyan**
## What changes were proposed in this pull request?

When running inside a container, driver program provides a driver host set to the container IP address. This IP address is visible only on the machine where the container is running. Spark executors running on other machines are not able to communicate to the driver program.
Now driver program may use standard SPARK_PUBLIC_DNS variable in order to expose driver host to executors. Just declare SPARK_PUBLIC_DNS=_host machine where the container is running_ in spark-env.sh within the container. Thanks to exposed ports, all requests from executors are forwarded to the driver program within the container.
[SPARK-21668](https://issues.apache.org/jira/browse/SPARK-21668)

## How was this patch tested?

I have tested this modification manually. I have a Spark cluster on 3 machines. I run my Spark application in a Docker container; the host machine belongs to the same network as my Spark cluster.

### CODE REVIEW

**Comment by tashoyan** [comment]
@vanzin @srowen @jerryshao would you you review please?

**Comment by vanzin** [comment]
Have you tried using `spark.driver.host` / `spark.driver.bindAddress` for this (SPARK-4563)? I'm pretty sure I tested exactly the scenario you mention when working on that.

**Comment by tashoyan** [comment]
So the working configuration is:
* set `spark.driver.host` to the IP address of the host machine
* set `spark.driver.bindAddress` to the IP address of the container
I tried this configuration with Spark 2.1.1 and 2.2.0. Works fine!
@vanzin thank you for pointing me to the right issue. I think we can close this PR and mark  [SPARK-21668](https://issues.apache.org/jira/browse/SPARK-21668) as a duplicate of [SPARK-4563](https://issues.apache.org/jira/browse/SPARK-4563).
The working Docker image is here: [docker-spark-submit](https://github.com/tashoyan/docker-spark-submit).

**Comment by vanzin** [comment]
Great, I closed the bug. Please close the PR too.

**Pull request closed without merging**
