### PR TITLE
[SparkR][Minor] Fix windowPartitionBy example

### PR DESCRIPTION
**Pull request by junyangq**
## What changes were proposed in this pull request?

The usage in the original example is incorrect. This PR fixes it.
## How was this patch tested?

Manual test.

### CODE REVIEW

**Comment by felixcheung** [comment]
LGTM

**Comment by shivaram** [comment]
@junyangq @felixcheung The test error is due to an unrelated issue caused when we upgraded testthat on Jenkins. I'm sending a fix for it now

**Comment by junyangq** [comment]
@shivaram I see. Thanks for letting us know.

**Comment by shivaram** [comment]
The fix is in #14904

**Comment by shivaram** [comment]
Jenkins, retest this please

**Comment by shivaram** [comment]
Merging this into master and branch-2.0

**Pull request closed without merging**
