### PR TITLE
[SPARK-21693][R][ML] Reduce max iterations in Linear SVM test in R to speed up AppVeyor build

### PR DESCRIPTION
**Pull request by HyukjinKwon**
## What changes were proposed in this pull request?

This PR proposes to reduce max iteration in Linear SVM test in SparkR. This particular test elapses roughly 5 mins on my Mac and over 20 mins on Windows.

The root cause appears, it triggers 2500ish jobs by the default 100 max iterations. In Linux, `daemon.R` is forked but on Windows another process is launched, which is extremely slow. 

So, given my observation, there are many processes (not forked) ran on Windows, which makes the differences of elapsed time.

After reducing the max iteration to 10, the total jobs in this single test is reduced to 550ish.

After reducing the max iteration to 5, the total jobs in this single test is reduced to 360ish.

## How was this patch tested?

Manually tested the elapsed times.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
I think I need to make sure it reduces the time significantly before cc'ing someone to review. I expect the decreas of 15ish mins.

**Review by srowen — APPROVED** [review]
Sounds good. Can you get away with even fewer iterations?

**Comment by HyukjinKwon** [comment]
Yes, it looked so. Let me give a try in my local and push a commit to check.

**Comment by HyukjinKwon** [comment]
Build started: [SparkR] `ALL` [PR-19722](https://ci.appveyor.com/project/spark-test/spark/branch/FCAF9D64-08C7-4199-8986-F2A6DD76A906)
Build started: [SparkR] `ALL` [PR-19722](https://ci.appveyor.com/project/spark-test/spark/branch/930D0519-A427-4D8D-9372-757B31429E45)
Build started: [SparkR] `ALL` [PR-19722](https://ci.appveyor.com/project/spark-test/spark/branch/F80F59CA-9CC2-4273-82B6-6A0F95724E6A)

**Comment by HyukjinKwon** [comment]
I checked it speeded up in https://ci.appveyor.com/project/ApacheSoftwareFoundation/spark/build/1909-master but the test seems hanging in `SparkSQL functions`, which seems unrelated. I triggered three more builds above to verify it.

**Comment by HyukjinKwon** [comment]
Yea, the first build speeded up roughly about 30 minutes - https://ci.appveyor.com/project/ApacheSoftwareFoundation/spark/build/1909-master. I triggered more builds here for sure with my account..

**Comment by HyukjinKwon** [comment]
cc @felixcheung and @shivaram too. This one finally reduces the time!

**Comment by felixcheung** [comment]
LGTM cool stuff, if we get the same result in less iterations

Let’s get this into 2.2 as well

**Comment by felixcheung** [comment]
merged to master/cherry pick to 2.2

**Comment by HyukjinKwon** [comment]
Thank you @srowen and @felixcheung for review! and thanks @mgaido91 and @dongjoon-hyun for your thumbs up :D.

**Pull request closed without merging**
