### PR TITLE
[SPARK-10305] [SQL] fix create DataFrame from Python class

### PR DESCRIPTION
**Pull request by davies**
cc @jkbradley

### CODE REVIEW

**Comment by jkbradley** [comment]
LGTM, though I'm still waiting for it to compile locally for testing my use case.

**Comment by davies** [comment]
@jkbradley one hint is that you do need to assembly to test python changes :)

**Comment by jkbradley** [comment]
Oops, too late : /

**Comment by jkbradley** [comment]
It works!  LGTM

**Comment by davies** [comment]
Merged into master and 1.5 branch.

**Comment by jkbradley** [comment]
Thanks a lot!

**Pull request closed without merging**
