### PR TITLE
[SPARK-10113][SQL] Explicit error message for unsigned Parquet logical types

### PR DESCRIPTION
**Pull request by HyukjinKwon**
Parquet supports some unsigned datatypes. However, Since Spark does not support unsigned datatypes, it needs to emit an exception with a clear message rather then with the one saying illegal datatype.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @liancheng

**Comment by liancheng** [comment]
Would you please rename the PR title to "Explicit error message for unsigned Parquet logical types"? Since this PR doesn't introduce "support" for unsigned types.

Otherwise LGTM. Thanks!

**Comment by marmbrus** [comment]
This seems fine for now, but its not clear to me why the right answer isn't to read it in as a higher precision signed type.

**Comment by marmbrus** [comment]
Merging to master and 1.6

**Comment by liancheng** [comment]
@marmbrus That's also an option, but seems somewhat confusing to me. Especially, in this way `UINT_64` has to be mapped to a fractional type. Besides, I just checked and realized that none of those built-in data models in parquet-mr implements any of these unsigned logical types.

**Pull request closed without merging**
