### PR TITLE
[SPARK-19973] Display num of executors for the stage.

### PR DESCRIPTION
**Pull request by jinxing64**
## What changes were proposed in this pull request?

In `StagePage` the total num of executors are not displayed. Since executorId may not be consecutive. It is useful to display the total number, which is useful when check how many executors are supplied during the stage.

## How was this patch tested?
Manually test.

### CODE REVIEW

**Comment by srowen** [comment]
No, just putting a number in the UI isn't correct. I am not sure this has that much value.
This isn't how we manage changes anyway. Please read http://spark.apache.org/contributing.html

**Comment by jinxing64** [comment]
@srowen 
Thanks a lot for quick reply. When we check the reason why a stage ran today much longer than yesterday, we want to know how many executors are supplied. We don't want to count the executor one by one. A total number of executors make sense here.

**Comment by srowen** [comment]
I don't think this is understandable as the executor count. It would also show the total count of executors include dead ones.

**Comment by jinxing64** [comment]
The executor metrics are updated to `StageUIData` when receive executor hear beat.
Yes, the longevity of the executor may not cover the whole stage, but it was once active during the stage.

**Comment by rxin** [comment]
Can you put a screenshot here? Might actually be useful to have.

**Comment by jinxing64** [comment]
screenshot

**Comment by jinxing64** [comment]
@rxin Thanks a lot. I added a number after `Aggregated Metrics by Executor`

**Comment by jerryshao** [comment]
I think it is good to have such count, but just this `(2)` is a little strange, maybe we could change the description so people will know the meanings of this `(2)`.

**Comment by jinxing64** [comment]
@jerryshao 
Thanks a lot you can help review, really appreciate. I will give a description soon.

**Comment by jinxing64** [comment]
screenshot2

**Comment by jinxing64** [comment]
@rxin @jerryshao 
I uploaded another screenshot and give a short description there.
Now it is (2 executors supplied).

**Comment by jerryshao** [comment]
IMO "(2 executors)" should be enough :).

**Comment by jinxing64** [comment]
Sure, that would be cool :) Thanks again you can help review this.

**Comment by jinxing64** [comment]
screenshot3

**Comment by jinxing64** [comment]
@rxin @jerryshao @srowen 
I've refined the description and uploaded the screenshot of latest version. Please take another look.

**Comment by srowen** [comment]
Do you intend to show the number of active executors? Don't think that's what this does and I am not sure it helps to show the total number of dead and alive.

**Comment by jinxing64** [comment]
I want to show the number of executors once active during the stage. `StageUIData` gets updated when receiving the hear beat from executor.

**Comment by harounemohammedi** [comment]
@jinxing64 I think it's helpful, can you please add the total time of an application to the Spark UI

**Comment by jinxing64** [comment]
@harounemohammedi 
Thanks a lot for comment on this. I'm hesitate to include the `total time` in this pr.

**Comment by rxin** [comment]
Your screenshot had 3 executors. Why does it say 2?

**Comment by jinxing64** [comment]
@rxin because I killed executor1 and it is not active during this stage.

**Comment by rxin** [comment]
That would be pretty confusing wouldn't it? The table has 3 entries and the title says only 2.

**Comment by jinxing64** [comment]
@rxin
Yes, I'm so confused by the second screenshot I posted.
The only reason I can find is that the `stageData` in `ExecutorTable` is none thread safe. Size(2 executors) returned; maybe at this point, new executor is inserted.

**Comment by jiangxb1987** [comment]
Are you still working on this? @jinxing64

**Comment by jinxing64** [comment]
Sorry, I will close it for now.

**Pull request closed without merging**
