### PR TITLE
[SPARK-28919][INFRA] Add more profiles for JDK8/11 build test for Github workflow

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to add `-Pyarn -Pmesos -Pkubernetes -Phive -Phive-thriftserver -Phadoop-3.2 -Phadoop-cloud` profiles to GitHub workflow conf.

### Why are the changes needed?

Currently, we build with JDK8 and test with JDK8/11 in Jenkins.
And, we use GitHub Workflow for JDK8/JDK11 building test.
To test JDK11 fully, we need to enable `hive` and `hadoop-3.2` profiles for `Hive 2.3.6` and `Hadoop 3.2`. Also, this PR adds all resource manager modules, too.

### Does this PR introduce any user-facing change?

No. In addition, Jenkins workload will be the same because this is specific to GitHub workflow.

### How was this patch tested?

See the GitHub workflow run result.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Hi, @dbtsai . Is there a way to trigger this on PR?

**Comment by viirya** [comment]
make a tiny change to corresponding modules?

**Comment by dbtsai** [comment]
@dongjoon-hyun yes, you can. 

See

https://help.github.com/en/articles/events-that-trigger-workflows

make it on pull request.

Thanks.

**Comment by dongjoon-hyun** [comment]
Thank you, @dbtsai .

**Comment by viirya** [comment]
retest this please.

**Comment by dongjoon-hyun** [comment]
Thank you for retriggering, @viirya .

**Review by HyukjinKwon — APPROVED** [review]
Change seems fine if tests pass

**Comment by dongjoon-hyun** [comment]
Thank you for review and updating PR title, @HyukjinKwon .

**Review by viirya — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you all.
Merged to master.

**Pull request closed without merging**
