### PR TITLE
revert PR#10896 and PR#14865

### PR DESCRIPTION
**Pull request by cloud-fan**
## What changes were proposed in this pull request?

according to the discussion in the original PR #10896 and the new approach PR #14876 , we decided to revert these 2 PRs and go with the new approach.
## How was this patch tested?

N/A

### CODE REVIEW

**Comment by cloud-fan** [comment]
cc @maropu @hvanhovell @yhuai 

@maropu  after this, do you wanna take over #14876 and keep working on it? thanks!

**Comment by maropu** [comment]
@cloud-fan yea, thanks! If no problem, I'll take it over.

**Comment by cloud-fan** [comment]
merging to master!

**Comment by maropu** [comment]
okay, thanks!

**Pull request closed without merging**
