### PR TITLE
[SPARK-26218][SQL][FOLLOW UP] Fix the corner case of codegen when casting float to Integer

### PR DESCRIPTION
**Pull request by luluorta**
### What changes were proposed in this pull request?
This is a followup of [#27151](https://github.com/apache/spark/pull/27151). It fixes the same issue for the codegen path.

### Why are the changes needed?
Result corrupt.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Added Unit test.

### CODE REVIEW

**Comment by luluorta** [comment]
cc @turboFei @cloud-fan

**Comment by cloud-fan** [comment]
ok to test

**Comment by cloud-fan** [comment]
add to whitelist

**Comment by luluorta** [comment]
retest this please

**Review by cloud-fan — APPROVED** [review]

**Comment by cloud-fan** [comment]
retest this please

**Comment by cloud-fan** [comment]
GA passed, merging to master, thanks!

**Pull request closed without merging**
