### PR TITLE
[SPARK-38261][INFRA] Add missing R packages from base image

### PR DESCRIPTION
**Pull request by khalidmammadov**
Current GitHub workflow job **Linters, licenses, dependencies and documentation generation** is missing R packages to complete Documentation and API build.

**Build and test** -  is not failing as these packages are installed on the base image.

We need to keep them in-sync IMO with the base image for easy switch back to ubuntu runner when ready.

Reference: [**The base image**](https://hub.docker.com/layers/dongjoon/apache-spark-github-action-image/20220207/images/sha256-af09d172ff8e2cbd71df9a1bc5384a47578c4a4cc293786c539333cafaf4a7ce?context=explore)

### What changes were proposed in this pull request?
Adding missing packages to the workflow file 

### Why are the changes needed?
To make them inline with the base image config and make the job task **complete** for standalone execution (i.e. without this image)

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
GitHub builds and in the local Docker containers

### CODE REVIEW

**Comment by khalidmammadov** [comment]
Related: https://github.com/apache/spark/pull/35516

**Review by HyukjinKwon — APPROVED** [review]
Okay, I guess we should better list them all.

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by dongjoon-hyun** [comment]
This is backported to branch-3.2.

**Pull request closed without merging**
