### PR TITLE
[SPARK-30801][SQL] Subqueries should not be AQE-ed if main query is not

### PR DESCRIPTION
**Pull request by maryannxue**
### What changes were proposed in this pull request?
This PR makes sure AQE is either enabled or disabled for the entire query, including the main query and all subqueries.
Currently there are unsupported queries by AQE, e.g., queries that contain DPP filters. We need to make sure that if the main query is unsupported, none of the sub-queries should apply AQE, otherwise it can lead to performance regressions due to missed opportunity of sub-query reuse.

### Why are the changes needed?
To get rid of potential perf regressions when AQE is turned on.

### Does this PR introduce any user-facing change?
No.

### How was this patch tested?
Updated DynamicPartitionPruningSuite:
1. Removed the existing workaround `withSQLConf(SQLConf.ADAPTIVE_EXECUTION_ENABLED.key, "false")`
2. Added `DynamicPartitionPruningSuiteAEOn` and `DynamicPartitionPruningSuiteAEOff` to enable testing this suite with AQE on and off options
3. Added a check in `checkPartitionPruningPredicate` to verify that the subqueries are always in sync with the main query in terms of whether AQE is applied.

### CODE REVIEW

**Comment by maryannxue** [comment]
cc @cloud-fan @gatorsmile

**Comment by cloud-fan** [comment]
LGTM, can you fix conflicts?

**Comment by maryannxue** [comment]
retest this please

**Comment by cloud-fan** [comment]
LGTM, merging to master/3.0!

**Pull request closed without merging**
