### PR TITLE
[SPARK-37992][PYTHON] Restore Mypy version checks in dev/lint-python

### PR DESCRIPTION
**Pull request by zero323**
### What changes were proposed in this pull request?

This PR restores Mypy version checks in `dev/lint-python`

Additionally, `MINIMUM_MYPY` is updated to match one used in GitHub workflow.

### Why are the changes needed?

These were accidentally removed in SPARK-36997.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Run `dev/lint-python` with versions satisfying and violating constraints, to ensure correct behavior.

### CODE REVIEW

**Comment by zero323** [comment]
cc @HyukjinKwon

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
cc @itholic FYI

**Comment by HyukjinKwon** [comment]
Python linter check passed.

Merged to master.

**Comment by zero323** [comment]
Thanks @HyukjinKwon and sorry for introducing this issue in the first place!

**Comment by HyukjinKwon** [comment]
Thanks for fixing this!

**Comment by itholic** [comment]
Cool. Thanks!

**Pull request closed without merging**
