### PR TITLE
[SPARK-44028][BUILD] Upgrade Apache `commons-io` to 2.13.0

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr aims to upgrade Apache `commons-io` from 2.12.0 to 2.13.0

### Why are the changes needed?
The new version bring some bug fixes, like:

- [IO-791](https://issues.apache.org/jira/browse/IO-791) : Regression in FileUtils.touch() - no longer creates parent directories
- [IO-796](https://issues.apache.org/jira/browse/IO-796) : FileAlreadyExistsException in PathUtils.createParentDirectories(Path, LinkOption, FileAttribute...)
- [IO-798](https://issues.apache.org/jira/browse/IO-798) : DeferredFileOutputStream throws exception when system temp dir is a symlink

The full release notes as follows:
- https://commons.apache.org/proper/commons-io/changes-report.html#a2.13.0

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?

- Pass GitHub Actions

### CODE REVIEW

**Comment by LuciferYang** [comment]
Test first

**Review by HyukjinKwon — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @LuciferYang .

**Comment by dongjoon-hyun** [comment]
Merged to master for Apache Spark 3.5.0. Thank you, @LuciferYang and @HyukjinKwon .

**Comment by LuciferYang** [comment]
Thanks @dongjoon-hyun @HyukjinKwon

**Pull request closed without merging**
