### PR TITLE
[SPARK-8515][ML][WIP] Improve ML Attribute API

### PR DESCRIPTION
**Pull request by viirya**
## What changes were proposed in this pull request?

The current ML attribute API has issues like inefficiency and less scalability. This work proposes new ML attribute API with main changes:

* Support spark vector-typed attributes.
* Simplify vector-typed attribute serialization.

### Indices range of attributes

Attributes which can be included in vector-typed attributes have indices range properties that record the indices that the attributes represent in vectors. For example, if 0 to 2 dimensions in a vector are all numeric attributes with same properties. We can use one numeric attribute recorded with indices range as [0, 2] for the 3 attributes.

### Sparse vector attributes

Vector attributes represents vector-typed columns. A vector attribute has attributes recorded with indices range in the vector. The indices without attributes are unresolved attributes which won't be serialized and don't occupy memory.

### Compatibility with current attribute APIs

The attributes created using current attribute APIs in metadata of `StructField` can be read and converted to new attributes.

## How was this patch tested?

Unit tests for attribute types. Compatibility tests.

### CODE REVIEW

**Comment by viirya** [comment]
retest this please.

**Comment by viirya** [comment]
retest this please.

**Comment by viirya** [comment]
Will re-open when this is ready.

**Comment by VDuda** [comment]
Following the issue, does this mean that this PR resolves https://issues.apache.org/jira/browse/SPARK-8515 ?

**Comment by viirya** [comment]
@VDuda Thanks for asking. This is a big change. I hope this PR can resolve SPARK-8515.

Most APIs are ready. I'm working on the compatibility with current attribute APIs. When it is ready, I'll re-open this for review.

**Comment by viirya** [comment]
@MLnick Can you take a look and give me some suggestion? Thanks.

**Comment by viirya** [comment]
Before the discussion of attribute API is finalized, I think the review won't be started. Close this for now and maybe re-open in the future.

**Pull request closed without merging**
