### PR TITLE
[SPARK-19358][CORE] LiveListenerBus shall log the event name when dropping them due to a fully filled queue

### PR DESCRIPTION
**Pull request by CodingCat**
## What changes were proposed in this pull request?

Some dropped event will make the whole application behaves unexpectedly, e.g. some UI problem...we shall log the dropped event name to facilitate the debugging

## How was this patch tested?

Existing tests

### CODE REVIEW

**Comment by CodingCat** [comment]
jenkins, retest this please

**Comment by CodingCat** [comment]
@srowen  mind looking at it? it's a simple improvement

**Comment by mridulm** [comment]
This PR will log only the first event which got dropped.
The first event which got droped need not necessarily have a correlation to the actual event(s) flooding the queue.

The PR description is slightly incorrect - it logs the entire event, and not just the name.

**Comment by mridulm** [comment]
Instead of keeping track of the history of dropped events, which will become expensive very fast, how about logging the current event (if dropped) when we log at [#L146][https://github.com/apache/spark/blob/6ee28423ad1b2e6089b82af64a31d77d3552bb38/core/src/main/scala/org/apache/spark/scheduler/LiveListenerBus.scala#L146]
There can be a logTrace line at line [133][https://github.com/apache/spark/blob/6ee28423ad1b2e6089b82af64a31d77d3552bb38/core/src/main/scala/org/apache/spark/scheduler/LiveListenerBus.scala#L133] if you do want to log all dropped events.

**Comment by CodingCat** [comment]
@mridulm what I thought is that logging the events which are <b>sampled</b> from the timeline may not provide meaningful info to the user 

the current implementation will clean the events queue for every minute to reduce the memory foot print, what do you think?

**Comment by mridulm** [comment]
@CodingCat Thinking more, I propose the following:

There are two changes here :

a) Changing the log message in onDropEvent()
If the queue is getting swamped due to a specific event (type), sampled message emitted helps here. If the event queue is getting swamping due to slow downstream processing or general application slowness - then it wont help.
Given the potential confusion, I think reverting onDropEvent() to earlier code is better.

b) Logging all dropped message.
This is primarily a spark developer feature, and as such the change is extremely expensive without too much upside. logTrace is a better alternative - it has zero overhead when not enabled, keeps the user logs clean when there is a spike and allows for developers to debug and get more info when required.

**Comment by CodingCat** [comment]
@mridulm thanks, I have changed the code

**Comment by mridulm** [comment]
I probably did not convey my idea properly ...
What I meant was, the only change required be :
`logTrace(s"Dropping events $event")` in `def onDropEvent(event: SparkListenerEvent): Unit`
There is no need to aggregate, etc.

**Comment by HyukjinKwon** [comment]
@CodingCat is this still active and any opinion on ^?

**Comment by CodingCat** [comment]
@mridulm but that still log the first dropped message, which cannot provide enough evidence for debugging, right?

**Comment by mridulm** [comment]
`onDropEvent` is invoked for every dropped event : not just the first.
If all you need is a way to find out what the dropped events were - simply enable trace logging for the class after addition of the log line.
With everything else being the same, you will see TRACE log message with all the dropped events.

**Comment by CodingCat** [comment]
you mean outside of https://github.com/apache/spark/pull/16697/files#diff-ca0fe05a42fd5edcab8a1bdaa8e58db9R210?

**Comment by mridulm** [comment]
Yes. If inside, you are right - only the first will be logged !

**Comment by jiangxb1987** [comment]
Should we merge this PR? @mridulm

**Comment by jiangxb1987** [comment]
retest this please

**Comment by cloud-fan** [comment]
LGTM, pending tests

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Pull request closed without merging**
