### PR TITLE
[SPARK-9294][SQL] cleanup comments, code style, naming typo for the new aggregation

### PR DESCRIPTION
**Pull request by cloud-fan**
fix some comments and code style for https://github.com/apache/spark/pull/7458

### CODE REVIEW

**Comment by cloud-fan** [comment]
cc @yhuai

**Comment by yhuai** [comment]
@cloud-fan Thanks! How about we create a sub-task under SPARK-4366 for this clean up work?

**Comment by yhuai** [comment]
@cloud-fan btw, can you help me add one more change in the PR? In https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/Analyzer.scala#L536, we use `case other if isDistinct =>` to do the match. Can you change it to `case other: AggregateExpression1 if isDistinct =>`? I think a tighter scope for the condition is better because `isDistinct` is only applicable to aggregate functions.

**Comment by yhuai** [comment]
LGTM. Thanks for the cleanup work!

**Comment by rxin** [comment]
I've merged this.

**Pull request closed without merging**
