### PR TITLE
[SPARK-46831][INFRA][FOLLOWUP] Fix a wrong JIRA ID in MimaExcludes

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This is a follow-up of 
- #44901

### Why are the changes needed?

To fix the wrong JIRA ID information.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Manual review.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
cc @MaxGekk

**Review by xinrong-meng — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @xinrong-meng .

**Comment by dongjoon-hyun** [comment]
I'll resolve the conflict and merge.

**Comment by dongjoon-hyun** [comment]
Merged to master.

**Pull request closed without merging**
