### PR TITLE
[SPARK-7276][DataFrame] speed up DataFrame.select by collapsing Project

### PR DESCRIPTION
**Pull request by cloud-fan**

### CODE REVIEW

**Comment by rxin** [comment]
Thanks - can you add a test case in DataFrameSuite also?

**Comment by cloud-fan** [comment]
cc @rxin, it's a quick fix but kind of ugly.

1. we can't disable eager analysis for this case.
2. the code is duplicated in Optimizer
3. break caching semantics as you said.

Actually I was thinking if it's bug or just wrong usage?

**Comment by rxin** [comment]
It's not really incorrect usage since the underlying engine is supposed to be very smart and take care of these cases ...

**Comment by rxin** [comment]
Would be great to minimize code duplication (maybe moving common stuff into a function in the optimizer)

**Comment by cloud-fan** [comment]
Relax the goal from "optimize into one `Project`" to "at most two `Project`s", to support disable eager analysis.

**Comment by cloud-fan** [comment]
Hi @rxin , I can get emails from JIRA, so just mention me at JIRA is OK. BTW, it's May Day holiday, so I may not be able to response in time :)

**Comment by rxin** [comment]
cc @marmbrus

**Comment by cloud-fan** [comment]
Retest this please.

**Comment by marmbrus** [comment]
Thanks for the fix!  Merging to master and 1.4.

**Pull request closed without merging**
