### PR TITLE
[SPARK-13812][SPARKR] Fix SparkR lint-r test errors.

### PR DESCRIPTION
**Pull request by sun-rui**
## What changes were proposed in this pull request?

This PR fixes all newly captured SparkR lint-r errors after the lintr package is updated from github.
## How was this patch tested?

dev/lint-r
SparkR unit tests

### CODE REVIEW

**Comment by sun-rui** [comment]
Discussion:
in dev/lint-r.R:
{code}
if ("lintr" %in% row.names(installed.packages())  == FALSE) {
  devtools::install_github("jimhester/lintr")
}
{code}

It seems that we should remove the if condition, so that the lintr package can update-to-date.
But this may have some problems:
1. User has install intr package in root priviledge;
2. Calling devtools::install_github each time seems time-consuming?

**Comment by sun-rui** [comment]
Jenkins, retest this please

**Comment by felixcheung** [comment]
looks good

**Comment by shivaram** [comment]
Thanks @sun-rui -- LGTM. Merging this

**Comment by sun-rui** [comment]
@shivaram, if we don't change dev/lint-r.R to install latest version of the lintr package, could you help to call for the Jenkins maintainer to manually update the installed lintr package so that future style issues can be caught in Jenkins tests?

**Comment by shivaram** [comment]
cc @shaneknapp

**Comment by shaneknapp** [comment]
hi!
i'll circle up w/shiv tomorrow and get this sorted.  :)

**Comment by shaneknapp** [comment]
i'm currently installing the latest lintr on all of our jenkins workers.  this should finish in ~15 mins

**Comment by shaneknapp** [comment]
ok done

**Comment by sun-rui** [comment]
@shaneknapp, thanks!

**Pull request closed without merging**
