### PR TITLE
[SPARK-42773][DOCS][PYTHON] Minor update to 3.4.0 version change message for Spark Connect

### PR DESCRIPTION
**Pull request by aldogrut**
### What changes were proposed in this pull request?
Changing the 3.4.0 version change message for PySpark functionality from "Support Spark Connect" to "Supports Spark Connect".

### Why are the changes needed?
Grammatical improvement.

### Does this PR introduce _any_ user-facing change?
Yes, these messages are shown in the user-facing PySpark documentation.

### How was this patch tested?
Built Spark and the documentation successfully on my computer and checked the PySpark documentation.
./build/sbt -Phive clean package
PRODUCTION=1 SKIP_RDOC=1 bundle exec jekyll build

supports_spark_connect_version_change_message

### CODE REVIEW

**Comment by itholic** [comment]
Seems like there are some more unchanged docstrings in several files as below:
```
spark % git grep "Support Spark Connect"
python/pyspark/sql/column.py:            Support Spark Connect.
python/pyspark/sql/column.py:            Support Spark Connect.
python/pyspark/sql/dataframe.py:            Support Spark Connect.
python/pyspark/sql/dataframe.py:            Support Spark Connect.
python/pyspark/sql/udf.py:            Support Spark Connect.
python/pyspark/sql/udf.py:            Support Spark Connect.
```
Btw, you can change the all strings at once by running the shell command in terminal such as:
```shell
find . -name "*.py" -exec perl -pi -e 's/Support Spark Connect/Supports Spark Connect/g' {} \;
```

**Comment by itholic** [comment]
Looks good otherwise

**Review by itholic — APPROVED** [review]
LGTM

**Review by zhengruifeng — APPROVED** [review]

**Comment by zhengruifeng** [comment]
LGTM pending CI

**Comment by zhengruifeng** [comment]
thank you @allanf-db , merged into master/branch-3.4

**Pull request closed without merging**
