### PR TITLE
[SPARK-12232][SPARKR] New R API for read.table to avoid name conflict

### PR DESCRIPTION
**Pull request by felixcheung**
@shivaram sorry it took longer to fix some conflicts, this is the change to add an alias for `table`

### CODE REVIEW

**Comment by sun-rui** [comment]
How about "tableToDF"  ? there are some API methods having table in their names, like "createExternalTable", "saveAsTable", "tables". "tableToDF" is shorter and consistent.

**Comment by felixcheung** [comment]
I'm not sure - `table` in R generally is associated with `data.frame` (think `read.table`) or the popular `data.table`, I actually think `saveAsTable` and `tables` should be updated for clarity as well.

**Comment by felixcheung** [comment]
@shivaram @sun-rui any thought on this?

**Comment by sun-rui** [comment]
IMO, In the context of Spark, `table` means SQL table. Now that we have so many existing APIs using table in their names, as a new API, it is better to be consistent.

**Comment by shivaram** [comment]
Sorry for the delay in getting back on this - I agree that using `table` to refer to SQL table is probably fine. Also since this will go into 2.0 we can probably remove some of the old functions like `tables` instead of marking them as deprecated ?

**Comment by felixcheung** [comment]
Sure - I think we are saying this should be called `tableToDF`. What about `tables`, `saveToTable`, `cacheTable`, `dropTempTable`, or `tableNames`?

**Comment by shivaram** [comment]
So `tableToDF` actually sounds good to me and its fine to assume that somebody using SparkR thinks of table as a SQL table, so `saveToTable`, `dropTempTable` etc. sound fine to me. 

We should definitely remove `table` which conflicts with base R and is completely unrelated. As for `tables` I'm also inclined to remove it especially if `tableNames` returns the same thing. Anyway you can open a new JIRA for discussing the rename / removal as well.

**Comment by felixcheung** [comment]
right.. `tables` is returning a DataFrame whereas `tableNames` is returning a vector? I'll open a JIRA to discuss these two.

For this, are we ok to remove `table` now, instead of .Deprecate I have here?

**Comment by shivaram** [comment]
Yes - removing `table` is fine.

**Comment by shivaram** [comment]
We should make a note in the release notes / deprecation from 1.x to 2.0 list somewhere as well
cc @rxin

**Comment by felixcheung** [comment]
These's the migration guide: http://spark.apache.org/docs/latest/sparkr.html#migration-guide

**Comment by felixcheung** [comment]
Done, updated code, tests, and doc.

**Comment by shivaram** [comment]
Thanks. LGTM. I'll just keep this open for a few hours to see if @sun-rui has any comments

**Comment by sun-rui** [comment]
LGTM

**Pull request closed without merging**
