### PR TITLE
[SPARK-44103][INFRA] Make pending container jobs cancelable

### PR DESCRIPTION
**Pull request by zhengruifeng**
### What changes were proposed in this pull request?
Make pending container jobs (pyspark/sparkr/linter) cancelable, to release the resources ASAP.

### Why are the changes needed?
to release the resources ASAP.

before this PR when we click the `Cancel Workflow`,  container jobs can not be cancelled, no matter the status (running or pending).

In this PR, we can cancel the pending container jobs. Note that the running ones still can not be cancelled.

### Does this PR introduce _any_ user-facing change?
no, test-only

### How was this patch tested?
manually check

### CODE REVIEW

**Comment by zhengruifeng** [comment]
click `Cancel Workflow` when the sql/core tests are running and the pyspark/sparkr/linter are pending.

before this PR:
Screenshot 2023-06-20 at 12 02 11

after this PR:
Screenshot 2023-06-20 at 13 55 38

**Comment by HyukjinKwon** [comment]
Oh, this is nice!

**Review by HyukjinKwon — APPROVED** [review]
Nice, LGTM if it works!

**Comment by zhengruifeng** [comment]
@HyukjinKwon thanks, I will check this PR a few more times

**Review by Yikun — APPROVED** [review]
Looks reasonable, the `always()` was for trigger pyspark/sparkr/lint job even if the parent infra-image build job skiped (You could check branch job works or not to make sure the PR is work as expected or not).

Consider [1], `The always expression is best used at the step level or on tasks that you expect to run even when a job is canceled.`, obviously, we want to skip the job if we cancel it. so as [2] suggested, `!cancelled()` is a good choice.

[1] https://docs.github.com/en/actions/learn-github-actions/expressions#always
[2] https://github.com/orgs/community/discussions/26303#discussioncomment-3251302

**Review by LuciferYang — APPROVED** [review]

**Comment by zhengruifeng** [comment]
I checked again:

normally, all jobs run successfully; (e.g. https://github.com/zhengruifeng/spark/actions/runs/5320253537/jobs/9637448689)

and if we click `Cancel Workflow`, non started container jobs can be canceled (e.g. https://github.com/zhengruifeng/spark/actions/runs/5329117265)

**Comment by zhengruifeng** [comment]
merged to master

thank you @HyukjinKwon @Yikun @LuciferYang

**Pull request closed without merging**
