### PR TITLE
[SPARK-44615][CONNECT][TESTS] rename spark connect client suites to avoid conflict

### PR DESCRIPTION
**Pull request by cg505**
### What changes were proposed in this pull request?

Before this change, each of the following names referred to a suite in `sql/core` and a duplicate-named suite in `connector/connect/client/jvm`:
- `org.apache.spark.sql.streaming.StreamingQuerySuite`
- `org.apache.spark.sql.DataFrameStatSuite`
- `org.apache.spark.sql.DatasetSuite`

This change renames spark connect client version of these suites to avoid the name conflict.

### Why are the changes needed?

Currently there are two identically named classes which can cause confusion and potential build issues.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Test-only change

### CODE REVIEW

**Review by zhenlineo — APPROVED** [review]
LGTM

**Comment by zhenlineo** [comment]
cc @hvanhovell

**Comment by zhenlineo** [comment]
Minor improvement to 3.5.0 too.

**Review by hvanhovell — APPROVED** [review]
LGTM

**Review by LuciferYang — APPROVED** [review]
+1, LGTM

**Comment by LuciferYang** [comment]
Merged into master/3.5. Thanks @cg505 @hvanhovell and @zhenlineo

**Pull request closed without merging**
