### PR TITLE
[MINOR][INFRA] Rename master.yml to build_and_test.yml

### PR DESCRIPTION
**Pull request by HyukjinKwon**
### What changes were proposed in this pull request?

This PR renames `master.yml` to `build_and_test.yml` to indicate this is the workflow that builds and runs the tests.

### Why are the changes needed?

Just for readability. `master.yml` looks like the name of the branch (to me).

### Does this PR introduce _any_ user-facing change?

No, dev-only.

### How was this patch tested?

GitHub Actions build in this PR will test it out.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @dongjoon-hyun, @gengliangwang and @viirya, this is a very minor stuff. I am preparing to backport GitHub Actions for SPARK-32249 and thought it's less readable. WDYT?

**Comment by dongjoon-hyun** [comment]
+1. No problem.

**Review by dongjoon-hyun — APPROVED** [review]
(Pending GitHub Action)

**Review by viirya — APPROVED** [review]
Nice for less confusion.

**Review by gengliangwang — APPROVED** [review]
+1 👍

**Comment by HyukjinKwon** [comment]
Thanks guys. Let me merge this after I cherry-pick Github Actions to other branches (at https://github.com/apache/spark/pull/29460)

**Comment by gengliangwang** [comment]
@HyukjinKwon shall we merge this one to unblock https://github.com/apache/spark/pull/29460 and https://github.com/apache/spark/pull/29454 ?

**Comment by HyukjinKwon** [comment]
Yup. Merged to master.

**Comment by HyukjinKwon** [comment]
Yup, let's do that. Thanks @gengliangwang.

**Comment by gengliangwang** [comment]
Thanks, merging to master

**Comment by HyukjinKwon** [comment]
Thanks @gengliangwang!

**Pull request closed without merging**
