### PR TITLE
[SPARK-16712]  Update Ivy artifacts statement for dev/audit

### PR DESCRIPTION
**Pull request by jayunit100**
## What changes were proposed in this pull request?

Updating the readme regarding ivy artifacts for dev/audit 
## How was this patch tested?

No testing.

### CODE REVIEW

**Comment by jayunit100** [comment]
Fixes https://github.com/apache/spark/pull/14347

**Comment by srowen** [comment]
@jayunit100 this whole directory is about to be deleted anyway, so I think this is redundant.

**Comment by jayunit100** [comment]
Hmmm... Ok, so What are we replacing audit tests with?

**Comment by srowen** [comment]
Nothing is replacing it per se. I believe it's original purpose was to verify some basic apps compiled against the API. It hasn't been used or maintained in a while. This kind of verification is properly the role of the standard test harness. So I suppose you can say it's redundant with the unit and integration tests.

**Pull request closed without merging**
