### PR TITLE
[SPARK-28818][SQL][2.4] Respect source column nullability in the arrays created by `freqItems()`

### PR DESCRIPTION
**Pull request by maropu**
### What changes were proposed in this pull request?
This PR replaces the hard-coded non-nullability of the array elements returned by `freqItems()` with a nullability that reflects the original schema. Essentially [the functional change](https://github.com/apache/spark/pull/25575/files#diff-bf59bb9f3dc351f5bf6624e5edd2dcf4R122) to the schema generation is:
```
StructField(name + "_freqItems", ArrayType(dataType, false))
```
Becomes:
```
StructField(name + "_freqItems", ArrayType(dataType, originalField.nullable))
```

Respecting the original nullability prevents issues when Spark depends on `ArrayType`'s `containsNull` being accurate. The example that uncovered this is calling `collect()` on the dataframe (see [ticket](https://issues.apache.org/jira/browse/SPARK-28818) for full repro). Though it's likely that there a several places where this could cause a problem. 

I've also refactored a small amount of the surrounding code to remove some unnecessary steps and group together related operations.

Note: This is the backport PR of #25575 and the credit should be @MGHawes.

### Why are the changes needed?
I think it's pretty clear why this change is needed. It fixes a bug that currently prevents users from calling `df.freqItems.collect()` along with potentially causing other, as yet unknown, issues.

### Does this PR introduce any user-facing change?
Nullability of columns when calling freqItems on them is now respected after the change.

### How was this patch tested?
I added a test that specifically tests the carry-through of the nullability as well as explicitly calling `collect()` to catch the exact regression that was observed. I also ran the test against the old version of the code and it fails as expected.

### CODE REVIEW

**Comment by maropu** [comment]
cc: @HyukjinKwon @MGHawes @dot-vlad

**Review by kiszk — APPROVED** [review]

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
Hi, @maropu . Apache Spark community respects the original authorship during backporting. Shall we respect the original authorship? If you changed something significantly, you can be an co-author, but you should not remove the original author.

**Comment by srowen** [comment]
What are you referring to here @dongjoon-hyun ... the requester and author do not seem to be available to do this work. The JIRA remains credited to the origin author. The original PR is linked here.

**Comment by dongjoon-hyun** [comment]
The commit of this PR, @srowen .

**Comment by maropu** [comment]
Thanks for the check, @dongjoon-hyun and @srowen . I was thinking we can rewrite the author by the merge scprit. Am I wrong?

**Comment by dongjoon-hyun** [comment]
That's right~ Please do that, @maropu .

**Review by dongjoon-hyun — APPROVED** [review]

**Comment by maropu** [comment]
Ur...did I have to cherry-pick the original commit and resolve the conflict to keep the original author? I might misunderstant it though.

**Comment by dongjoon-hyun** [comment]
Yes. That's the correct way which I expected in order to prevent any accidental merging.
> Ur...did I have to cherry-pick the original commit and resolve the conflict to keep the original author? I might misunderstant it though.

**Comment by maropu** [comment]
I have no intention of being a co-author since this is the same with the original one, so I'll rewrite the author in this commit and merge this into branch-2.4.

**Comment by dongjoon-hyun** [comment]
Yep, but please make it sure. Every committer can merge your PR without noticing the authorship change.

**Comment by maropu** [comment]
okay, thanks~, @dongjoon-hyun

**Comment by srowen** [comment]
OK, I mean, I'd also consider @maropu the author of this _backport_. Sure cherry-pick takes care of that but it also kind of loses some info about who did the conflict resolution, etc. Either way seems reasonable.

**Comment by maropu** [comment]
Merged to branch-2.4 (NOTE: I checked that the lead author in the commit has been rewritten)

**Comment by dongjoon-hyun** [comment]
Thank you, @maropu . I checked.

**Comment by dongjoon-hyun** [comment]
Sure, @srowen . We respect both efforts. That's the reason why we introduced the `lead-author` and `co-author` into our official `merge-script`. Now, we have a better way to clarify the authorship than the PR description. I'm happy because @maropu applied the best way for both contributors (@MGHawes and @maropu ).

**Comment by HyukjinKwon** [comment]
Thanks @maropu for tacking care of this. I was stuck in some other works so my response was a bit slow.

FYI, the commits in other branches are not counted by GitHub, and the main contributions are being counted and shown properly. Maybe it's not a big deal especially given that we keep the authors in the main PR, commit, the backporting PR description, JIRA and etc.

I would more like to encourage committers/other contributors to help porting back things especially when the PR authors go inactive.

**Comment by maropu** [comment]
> I would more like to encourage committers/other contributors to help porting back things especially when the PR authors go inactive. 

Thanks, @HyukjinKwon . Yea, I will be careful for that.

**Pull request closed without merging**
