### PR TITLE
[SPARK-13951] Add nested Pipeline load/save supports in PySpark

### PR DESCRIPTION
**Pull request by yinxusen**
## What changes were proposed in this pull request?

https://issues.apache.org/jira/browse/SPARK-13951
1. Scala side `Pipeline` changes:
   - Change `Param[Array[PipelineStage]]` to `StageArrayParam` to support Java competible function.
2. Python side changes:
   - wrapper: Add a `JavaConvertible` to support those stages that are not a `JavaWrapper`.
   - wrapper: Add a `ConvertUtil` to support the Python-Scala converting for both `JavaWrapper` and `JavaConvertible`.
   - pipeline: `Pipeline` and `PipelineModel` now extend from `JavaConvertible`.
   - pipeline: `PipelineMLReader`, `PipelineMLWriter`, `PipelineModelMLReader`, and `PipelineModelMLWriter` now use `ConvertUtils`.
## How was this patch tested?

Test with Python unit test for both pipeline save/load and nested-pipeline save/load.

### CODE REVIEW

**Comment by yinxusen** [comment]
test it please

**Comment by yinxusen** [comment]
@jkbradley 

MiMa tests failed for changing to the `StageArrayParam`. But I think we need a new Param like `ArrayParam[T]` with the Java compatible `w` function. Otherwise, it's hard to build an array-param in Python side.

**Comment by jkbradley** [comment]
I'll take a look

**Comment by jkbradley** [comment]
I think we should be able to implement this using Python only, and definitely without breaking the Scala/Java API.  Let me prototype a little, and get back to you.

**Comment by jkbradley** [comment]
@yinxusen Thanks very much for working on this issue.  After looking at it, I think we should use a different approach entirely in Python.  I also found some issues with the current Python ML persistence setup, which I'd like to clean up.  I'd like to take over this issue.  Could you please close this PR and, if you have time, help review my PR for it: [https://github.com/apache/spark/pull/11866]?

Thanks a lot for your understanding.

**Pull request closed without merging**
