### PR TITLE
[SPARK-13280] [streaming] Use a better logger name for FileBasedWriteAheadLog.

### PR DESCRIPTION
**Pull request by vanzin**
The new logger name is under the org.apache.spark namespace.
The detection of the caller name was also enhanced a bit to ignore
some common things that show up in the call stack.

### CODE REVIEW

**Comment by vanzin** [comment]
retest this please

**Comment by andrewor14** [comment]
@tdas

**Comment by tdas** [comment]
LGTM.

**Comment by vanzin** [comment]
ok merging

**Pull request closed without merging**
