### PR TITLE
[SPARK-14383] [SQL] missing "|" in the g4 file

### PR DESCRIPTION
**Pull request by bomeng**
## What changes were proposed in this pull request?

A very trivial one. It missed "|" between DISTRIBUTE and UNSET.
## How was this patch tested?

I do not think it is really needed.

### CODE REVIEW

**Comment by holdenk** [comment]
Might be good to add to the existing unit tests since it was possibly a regression from the previous grammar?

**Comment by hvanhovell** [comment]
@bomeng good catch. You can test this easily by using these as identifiers.

**Comment by bomeng** [comment]
@hvanhovell Could you please tell me how to test? You mean manual test or else? Besides this, I have some questions to ask but not related to this JIRA. I do found there are lots of non-keyword are missing in the current g4 file, some of them are defined but not added to the non-keyword list. Is it planned to do? Another question is for "createTableUsing", "OPTIONS" (new non-hive keyword) was introduced instead of "TBLPROPERTIES", is there any reason for that?

**Comment by hvanhovell** [comment]
@bomeng `DISTRIBUTE` `UNSET` have been defined as one rule, so we cannot use them as identifiers. This will fail for instance: `select unset from x` whereas `select TBLPROPERTIES from x` would work.

The `OPTIONS` keyword is part of the spark native `CREATE [TEMPORARY] TABLE table USING codec [OPTIONS (opt1 'foo', opt2 'bar')] [AS SELECT ...]` syntax; we still support that.

You have a point regarding the missing non-reserved keywords. This is however not as black and white as you would expect. There are a few things to consider:
A lot of non-reserved keywords can cause code blowups. This is much better in ANTLR4 than in ANTLR3 but is still a thing we need to be careful about:

- There is a difference between keywords that are non-reserved and SQL2003 keywords. Personally I think the grammar we are using shouldn't be to restrictive, and we should allow as much as sanely possible.
- We shouldn't have to many (non-reserved) keywords at all. Case and point of this are DataTypes. In this case you would have to do the parsing twice, once syntactically and once semantically. So now we allow any identifier as a `DataType` and have the `AstBuilder` throw exceptions when we cannot figure out which `DataType` should be used.
- There is a minor regression. Hive allowed us to use `LEFT`/`RIGHT`/`FULL` as identifiers, this causes some trouble with joins; so we made them reserved.

I have created https://issues.apache.org/jira/browse/SPARK-14398 to track this.

**Comment by hvanhovell** [comment]
LGTM

**Comment by andrewor14** [comment]
Merged into master. Good catch.

**Pull request closed without merging**
