### PR TITLE
[SPARK-17561] [DOCS] DataFrameWriter documentation formatting problems

### PR DESCRIPTION
**Pull request by srowen**
## What changes were proposed in this pull request?

Fix `<ul> / <li>` problems in SQL scaladoc.
## How was this patch tested?

Scaladoc build and manual verification of generated HTML.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Hi @srowen, I support this PR and it's a super minor but would this be sensible if we re-indent child elements in the XML?

**Comment by rxin** [comment]
LGTM - merging in master/2.0.

**Comment by rxin** [comment]
I merged this in master but there's a conflict with branch-2.0. Can you create a patch for 2.0?

**Comment by srowen** [comment]
Sure, I just merged it to 2.0 and resolved the conflict because that was straightforward here.

**Pull request closed without merging**
