### PR TITLE
[SPARK-35007][SQL] support numeric type

### PR DESCRIPTION
**Pull request by zheniantoushipashi**
What changes were proposed in this pull request?

Spark's  numeric  is  a synonym of  decimal

this pr add support for numeric type

Why are the changes needed?

my  code need  needs to use NUMERIC type in spark2.4 version but not support now

How was this patch tested?
Existing tests.

### CODE REVIEW

**Comment by wangyum** [comment]
Please make pr against master branch:
image

**Comment by zheniantoushipashi** [comment]
ok

**Comment by zheniantoushipashi** [comment]
> Please make pr against master branch:
> image

Hello, my pr is developed based on branch 2.4, why should I submit it to the master branch? The master branch already supports numeric, I want to double commit to the 2.4 branch

**Comment by wangyum** [comment]
Then, please use Spark 3.x. In general, `branch-2.4` only accepts bug fixes. Please see Versioning Policy: http://spark.apache.org/versioning-policy.html

**Comment by zheniantoushipashi** [comment]
> Then, please use Spark 3.x. In general, `branch-2.4` only accepts bug fixes. Please see Versioning Policy: http://spark.apache.org/versioning-policy.html

ok

**Pull request closed without merging**
