### PR TITLE
Revert "[SPARK-32481][CORE][SQL] Support truncate table to move data to trash"

### PR DESCRIPTION
**Pull request by gatorsmile**
### What changes were proposed in this pull request?

This reverts commit 065f17386d1851d732b4c1badf1ce2e14d0de338, which is not part of any released version. That is, this is an unreleased feature

### Why are the changes needed?

I like the concept of Trash, but I think this PR might just resolve a very specific issue by introducing a mechanism without a proper design doc. This could make the usage more complex.

I think we need to consider the big picture. Trash directory is an important concept. If we decide to introduce it, we should consider all the code paths of Spark SQL that could delete the data, instead of Truncate only. We also need to consider what is the current behavior if the underlying file system does not provide the API `Trash.moveToAppropriateTrash`. Is the exception good? How about the performance when users are using the object store instead of HDFS? Will it impact the GDPR compliance? 

In sum, I think we should not merge the PR https://github.com/apache/spark/pull/29552 without the design doc and implementation plan. That is why I reverted it before the code freeze of Spark 3.1

### Does this PR introduce _any_ user-facing change?
Reverted the original commit

### How was this patch tested?
The existing tests.

### CODE REVIEW

**Comment by gatorsmile** [comment]
cc @Udbhav30 @sunchao @viirya @dongjoon-hyun @HyukjinKwon

**Comment by dongjoon-hyun** [comment]
Got it, @gatorsmile .

**Comment by HyukjinKwon** [comment]
I am okay with this revert.

**Comment by Udbhav30** [comment]
Sure got it

**Comment by sunchao** [comment]
Thanks for pinging @gatorsmile . Agree with your reasoning and +1 on this.

**Comment by viirya** [comment]
Looks okay.

**Review by HyukjinKwon — APPROVED** [review]

**Review by viirya — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
