### PR TITLE
[SPARK-43974][CONNECT][BUILD][FOLLOWUP] Upgrade buf to v1.23.1

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr is followup SPARK-43974.

### Why are the changes needed?
image

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA.

### CODE REVIEW

**Comment by panbingkun** [comment]
cc @zhengruifeng

**Comment by LuciferYang** [comment]
Can you add some descriptions in the `Why are the changes needed?`?  It is difficult to search in the commit log with screenshots.

**Comment by HyukjinKwon** [comment]
How does this related to https://github.com/apache/spark/pull/41933?

**Comment by LuciferYang** [comment]
> How does this related to #41933?

I think they fixed the same issue

**Comment by panbingkun** [comment]
> How does this related to #41933?

Yes, that's right.

**Pull request closed without merging**
