### PR TITLE
[SPARK-38593][SS] Carry over the metric of the number of dropped late events into SessionWindowStateStoreSaveExec

### PR DESCRIPTION
**Pull request by HeartSaVioR**
### What changes were proposed in this pull request?

This PR proposes to carry over the metric of the number of dropped late events from SessionWindowStateStoreRestoreExec to SessionWindowStateStoreSaveExec, so that state operator progress for session window aggregation operator will have correct number.

### Why are the changes needed?

The number of dropped late events for session window aggregation was missed in the mechanism of SS metrics (state operator progress).

### Does this PR introduce _any_ user-facing change?

Yes, the number of dropped late events for session window aggregation will be taken into account for state operator progress in streaming listener, as well as a graph on late events in the SS UI page.

### How was this patch tested?

Modified UT.

### CODE REVIEW

**Review by viirya — COMMENTED** [review]
why do we need to "carry" metrics from other operator...

**Comment by HeartSaVioR** [comment]
We issue the "same" stateful operator ID for both nodes, no? They are "logically" a single operator.

The thing we split the execution node down to two is "implementation details", which end users should not be required to reason about. The thing we take the route of different execution nodes for streaming aggregation and "session window" streaming aggregation is also "implementation details".

**Comment by HeartSaVioR** [comment]
If it feels like hacky for us, we can go down a long way, define a new interface/operator which is in charge to collect the metrics from various physical nodes having same stateful operator ID, and implement it. Would it be good given the fact the only exceptional case is session window aggregation as of now?

**Comment by viirya** [comment]
It looks hacky, but I'm fine with it.

BTW, as a reminder, for the such issues, I'm fine if you want to work on it. But please let me know in advance next time. So we don't need to step on others toes. Thank you.

**Review by viirya — APPROVED** [review]

**Comment by HeartSaVioR** [comment]
It would be nice to clear out what happened to clear the misunderstanding. Here's the thing happened to us.

It was me asked you to extend your work. If I planned to work this, I would have said nothing in previous PR. Really, I did nothing before your next PR is up.

I went through reviewing, and realized we had miscommunication. I thought I was very clear to explain that we should update the existing metric so that the mechanism of SS metric will function correctly. e.g. I pointed out the graph of late events in SS UI to be sure we no longer be confused. I thought we were in agreement in the latest comments of previous PR, and I realized I was wrong.

I tried crafting a code in case if I'm missing, e.g. what if it is not feasible to fulfill my requirement in any way. Turned out I could craft this code in ~15 mins. If the work took longer, I would have stopped and tried to resolve miscommunication instead.

That was what exactly happened. I apologize all the things happened here. But showing 40 lines of changes turned out to be more effective than explaining the requirements with details.

**Comment by HeartSaVioR** [comment]
Anyway, let's close the loop. Merging to master.

**Comment by HeartSaVioR** [comment]
I just realized SPARK-38549 was included in 3.3 - let's ship sibling PRs together. Will merge to 3.3 as well.

**Comment by viirya** [comment]
I'm fine with it. Thanks for the explanation. I suppose you won't do it usually, but I'd just like to remind that this is not a good practice for the community. Rarely we open another PR in parallel with original PR. It seems only happened if the original PR is out of sync for a while and we cannot connect to the author. Anyway, thanks for the work. At least the issue is resolved.

**Pull request closed without merging**
