### PR TITLE
[Minor] Fix some indent issues.

### PR DESCRIPTION
**Pull request by wangyum**
## What changes were proposed in this pull request?

Fix some indent issues.

## How was this patch tested?

existing tests.

### CODE REVIEW

**Review by srowen — COMMENTED** [review]
Is this causing any problem?

**Comment by wangyum** [comment]
Indent issues look ununified description:
display

**Comment by srowen** [comment]
OK. I don't think this is worth bothering with.

**Comment by srowen** [comment]
Merged to master anyway

**Pull request closed without merging**
