### PR TITLE
[SPARK-16162] Remove dead code OrcTableScan.

### PR DESCRIPTION
**Pull request by bchocho**
## What changes were proposed in this pull request?

SPARK-14535 removed all calls to class OrcTableScan. This removes the dead code.
## How was this patch tested?

Existing unit tests.

### CODE REVIEW

**Comment by rxin** [comment]
LGTM pending tests.

**Comment by rxin** [comment]
Merging in master.

**Comment by rxin** [comment]
@dafrista you should add the email associated with your commit to your github account.

**Comment by dafrista** [comment]
@rxin Done, thanks!

**Pull request closed without merging**
