### PR TITLE
[SPARK-33684][BUILD] Upgrade httpclient from 4.5.6 to 4.5.13

### PR DESCRIPTION
**Pull request by sarutak**
### What changes were proposed in this pull request?

This PR upgrades `commons.httpclient` from `4.5.6` to `4.5.13`.
4.5.6 is released over 2 years ago and now we can use more stable `4.5.13`.
https://archive.apache.org/dist/httpcomponents/httpclient/RELEASE_NOTES-4.5.x.txt

### Why are the changes needed?

To follow the more stable release.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Should be done by the existing tests.

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]

**Review by dongjoon-hyun — COMMENTED** [review]
+1 for Apache Spark 3.2.0.

Please run `dev/test-dependencies.sh --replace-manifest`, @sarutak .

**Comment by sarutak** [comment]
@dongjoon-hyun Yeah, I forgot to do it. Thanks!

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. (Pending CIs). Thanks, @sarutak .

**Comment by dongjoon-hyun** [comment]
Merged to master for Apache Spark 3.2.

**Pull request closed without merging**
