### PR TITLE
[SPARK-34775][SQL] Push down limit through window when partitionSpec is not empty

### PR DESCRIPTION
**Pull request by leoluan2009**
This is a followup from https://github.com/apache/spark/pull/31691. Push down limit through Window when the partitionSpec of all window functions is not empty and the same order is used.

### What changes were proposed in this pull request?

Push down limit through Window when the partitionSpec of all window functions is not empty

### Why are the changes needed?

Improve query performance.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Unit test.

### CODE REVIEW

**Comment by leoluan2009** [comment]
Will add new Unit test later

**Comment by leoluan2009** [comment]
cc @wangyum

**Review by wangyum — CHANGES_REQUESTED** [review]
Could you add more test cases to `LimitPushdownThroughWindowSuite`?

**Comment by wangyum** [comment]
It seems Impala supports this optimization:
https://issues.apache.org/jira/browse/IMPALA-9983
https://issues.apache.org/jira/browse/IMPALA-9853

**Pull request closed without merging**
