### PR TITLE
[SPARK-43007][BUILD] Upgrade rocksdbjni to 8.0.0

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr aims to upgrade rocksdbjni from 7.10.2 to 8.0.0.

### Why are the changes needed?
This version bring some bug fix about `Get` and `MultiGet `, the full release notes as follows:

- https://github.com/facebook/rocksdb/releases/tag/v8.0.0

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?

- Pass GitHub Actions
- Manual test `RocksDBBenchmark`:

**7.10.2**

```
[INFO] Running org.apache.spark.util.kvstore.RocksDBBenchmark
                                                count   mean    min     max     95th
dbClose                                         4       0.362   0.307   0.510   0.510
dbCreation                                      4       70.556  3.823   272.036 272.036
naturalIndexCreateIterator                      1024    0.005   0.002   1.396   0.007
naturalIndexDescendingCreateIterator            1024    0.007   0.007   0.063   0.009
naturalIndexDescendingIteration                 1024    0.006   0.004   0.236   0.009
naturalIndexIteration                           1024    0.006   0.004   0.054   0.010
randomDeleteIndexed                             1024    0.028   0.019   0.246   0.038
randomDeletesNoIndex                            1024    0.014   0.012   0.041   0.018
randomUpdatesIndexed                            1024    0.084   0.033   30.028  0.095
randomUpdatesNoIndex                            1024    0.033   0.029   0.759   0.037
randomWritesIndexed                             1024    0.120   0.034   54.254  0.124
randomWritesNoIndex                             1024    0.038   0.032   1.918   0.043
refIndexCreateIterator                          1024    0.004   0.004   0.017   0.006
refIndexDescendingCreateIterator                1024    0.003   0.003   0.027   0.004
refIndexDescendingIteration                     1024    0.007   0.005   0.114   0.009
refIndexIteration                               1024    0.007   0.005   0.045   0.010
sequentialDeleteIndexed                         1024    0.024   0.018   1.944   0.028
sequentialDeleteNoIndex                         1024    0.015   0.012   0.039   0.019
sequentialUpdatesIndexed                        1024    0.044   0.036   0.910   0.057
sequentialUpdatesNoIndex                        1024    0.037   0.032   0.868   0.046
sequentialWritesIndexed                         1024    0.047   0.040   2.261   0.056
sequentialWritesNoIndex                         1024    0.041   0.033   3.577   0.045
```

**8.0.0**

```
[INFO] Running org.apache.spark.util.kvstore.RocksDBBenchmark
                                                count   mean    min     max     95th
dbClose                                         4       0.320   0.233   0.562   0.562
dbCreation                                      4       71.171  3.778   272.587 272.587
naturalIndexCreateIterator                      1024    0.006   0.002   1.460   0.009
naturalIndexDescendingCreateIterator            1024    0.007   0.006   0.063   0.008
naturalIndexDescendingIteration                 1024    0.008   0.004   0.377   0.013
naturalIndexIteration                           1024    0.006   0.004   0.060   0.010
randomDeleteIndexed                             1024    0.030   0.020   0.338   0.052
randomDeletesNoIndex                            1024    0.016   0.013   0.050   0.020
randomUpdatesIndexed                            1024    0.087   0.032   29.873  0.096
randomUpdatesNoIndex                            1024    0.036   0.032   0.592   0.041
randomWritesIndexed                             1024    0.121   0.033   54.702  0.123
randomWritesNoIndex                             1024    0.040   0.034   1.530   0.047
refIndexCreateIterator                          1024    0.005   0.003   0.023   0.007
refIndexDescendingCreateIterator                1024    0.003   0.003   0.026   0.005
refIndexDescendingIteration                     1024    0.007   0.005   0.051   0.009
refIndexIteration                               1024    0.007   0.005   0.052   0.010
sequentialDeleteIndexed                         1024    0.021   0.017   0.133   0.025
sequentialDeleteNoIndex                         1024    0.015   0.012   0.041   0.018
sequentialUpdatesIndexed                        1024    0.046   0.036   2.035   0.055
sequentialUpdatesNoIndex                        1024    0.040   0.028   0.798   0.050
sequentialWritesIndexed                         1024    0.049   0.042   2.578   0.055
sequentialWritesNoIndex                         1024    0.035   0.029   3.229   0.039
```

- Checked core module UTs with rocksdb live ui

```
export LIVE_UI_LOCAL_STORE_DIR=/${basedir}/spark-ui    
build/mvn clean install -pl core -am -Dtest.exclude.tags=org.apache.spark.tags.ExtendedLevelDBTest -fn
```

All test passed

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
+1 for Apache Spark 3.5.0 because we have enough time to upgrade to the newer versions. Thank you, @LuciferYang .

However, let's wait for two more days.

**Comment by LuciferYang** [comment]
Thanks @dongjoon-hyun 
OK~ let's wait for some more days

**Comment by dongjoon-hyun** [comment]
Merged to master. Thank you for waiting.

**Comment by HeartSaVioR** [comment]
Sorry for post-review. It'd be nice if you don't mind running below benchmark as well.
sql/core/src/test/scala/org/apache/spark/sql/execution/benchmark/StateStoreBasicOperationsBenchmark.scala
The test is more likely about performance of WriteBatch rather than RocksDB itself but that's something we use in RocksDB state store provider.

**Comment by dongjoon-hyun** [comment]
Thank you, @HeartSaVioR . To @LuciferYang , could you address the above comment?

**Comment by LuciferYang** [comment]
> Thank you, @HeartSaVioR . To @LuciferYang , could you address the above comment?

OK, Let me update the results of `StateStoreBasicOperationsBenchmark ` in a follow-up

**Comment by LuciferYang** [comment]
Need to update later because

image

**Pull request closed without merging**
