### PR TITLE
[SPARK-32231][R][INFRA] Use Hadoop 3.2 winutils in AppVeyor build

### PR DESCRIPTION
**Pull request by HyukjinKwon**
### What changes were proposed in this pull request?

This PR proposes to use Hadoop 3 winutils to make AppVeyor builds pass. Currently it's being failed as below
https://ci.appveyor.com/project/ApacheSoftwareFoundation/spark/builds/33976604

### Why are the changes needed?

To recover the build in AppVeyor.

### Does this PR introduce _any_ user-facing change?

No, dev-only.

### How was this patch tested?

AppVeyor build will test it out.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @dongjoon-hyun FYI

**Comment by dongjoon-hyun** [comment]
Thank you, @HyukjinKwon !

**Comment by dongjoon-hyun** [comment]
cc @steveloughran , too.

**Comment by dongjoon-hyun** [comment]
4 failures in `org.apache.hadoop.io.nativeio.NativeIO$POSIX.stat`. It seems Hadoop 3.0 bug on Windows OS.
```
== testthat results  ===========================================================
2086[ OK: 13 | SKIPPED: 0 | WARNINGS: 0 | FAILED: 0 ]
2087v |  OK F W S | Context
2088v |  11       | binary functions [35.6 s]
2089x |   0 4     | functions on binary files [7.6 s]
2090--------------------------------------------------------------------------------
2091test_binaryFile.R:34: error: saveAsObjectFile()/objectFile() following textFile() works
2092java.lang.UnsatisfiedLinkorg.apache.hadoop.io.nativeio.NativeIO$POSIX.stat(Ljava/lang/String;)Lorg/apache/hadoop/io/nativeio/NativeIO$POSIX$Stat;
2093	at org.apache.hadoop.io.nativeio.NativeIO$POSIX.stat(Native Method)
2094	at org.apache.hadoop.io.nativeio.NativeIO$POSIX.getStat(NativeIO.java:460)
2095
```

**Comment by dongjoon-hyun** [comment]
Hi, @steveloughran . Sorry but, do you know if there is a known issue about Hadoop 3.x on Windows?

**Comment by dongjoon-hyun** [comment]
For this PR, I'm testing on Windows. I'll make a PR to you.

**Comment by dongjoon-hyun** [comment]
Hi, @HyukjinKwon . I made a PR to you. Could you review and merge that?
- https://github.com/HyukjinKwon/spark/pull/5

**Comment by HyukjinKwon** [comment]
Awesome!

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. AppVeyor passed.

**Comment by HyukjinKwon** [comment]
Merged to master.

Thanks, @dongjoon-hyun.

**Pull request closed without merging**
