### PR TITLE
[SPARK-37820][SQL] Replace ApacheCommonBase64 with JavaBase64 for string funcs

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

Replace Base64 on ApacheCommonBase64 with native support (https://docs.oracle.com/javase/8/docs/api/java/util/Base64.html)  for Base-64 encode/decode.

ApacheCommonBase64 obeys http://www.ietf.org/rfc/rfc2045.txt with url-safe off according to its doc, so we choose `java.util.Base64.Decoder#RFC2045`

### Why are the changes needed?

1. Performace gain
  - http://java-performance.info/base64-encoding-and-decoding-performance/
  - have done benchmarks against jdk8/11, shown 2-5x faster

2. reduce dependencies after we replace other related places

### Does this PR introduce _any_ user-facing change?

NO

### How was this patch tested?

- Existing StringExpressionSuite
- benchmarks

### CODE REVIEW

**Comment by yaooqinn** [comment]
cc @cloud-fan @dongjoon-hyun @HyukjinKwon, thanks very much

**Review by cloud-fan — APPROVED** [review]

**Review by HyukjinKwon — APPROVED** [review]

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
Thank you, @yaooqinn . I have two requests.

- Could you regenerate the benchmark result by using GitHub Action?
- Could you add Java 17 benchmark result?

For the others, it looks good.

**Comment by yaooqinn** [comment]
> Could you regenerate the benchmark result by using GitHub Action?

Thanks, @dongjoon-hyun any instructions for triggering this step?

**Comment by dongjoon-hyun** [comment]
Yes, Here it is, `Running benchmarks in your forked repository`. It's easy.
- https://spark.apache.org/developer-tools.html

**Comment by yaooqinn** [comment]
I have found the guide, thanks

**Comment by yaooqinn** [comment]
Extraordinary feature! @dongjoon-hyun @HyukjinKwon 

> Yes, Here it is, `Running benchmarks in your forked repository`. It's easy and nice tool which @HyukjinKwon contributed.
> 
> * https://spark.apache.org/developer-tools.html

**Comment by dongjoon-hyun** [comment]
Are the benchmark result ready, @yaooqinn ? :)

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Merged to master.
Thank you, @yaooqinn , @cloud-fan , @HyukjinKwon .

**Pull request closed without merging**
