### PR TITLE
[SPARK-21236] Make the threshold of using HighlyCompressedStatus configurable.

### PR DESCRIPTION
**Pull request by jinxing64**
## What changes were proposed in this pull request?

Currently the threshold of using `HighlyCompressedMapStatus` is hardcoded 2000.
We could make this configurable. Thus users having enough memory on driver can configure the threshold to be larger thus to save the size of blocks more accurately in `CompressedMapStatus`.

### CODE REVIEW

**Review by jiangxb1987 — COMMENTED** [review]
This change LGTM, should we also add a new test case in `MapStatusSuite` ？

**Comment by jinxing64** [comment]
Sure, thanks for review :)

**Comment by jinxing64** [comment]
Jenkins, retest this please.

**Comment by srowen** [comment]
It's probably OK, but what's the use case for configuring it? when would a caller know to set it higher or lower? just trying to figure out if this is a meaningful knob.

**Comment by jiangxb1987** [comment]
I guess the size of blocks are not very accurately stored in `HighlyCompressedMapStatus`, so if we have enough memory in the driver, we prefer to store them in `CompressedMapStatus `.

**Comment by jinxing64** [comment]
Yes, this is discussed ever in https://github.com/apache/spark/pull/16989 . Only average size of blocks are stored in `HighlyCompressedMapStatus`. If driver has enough memory, we can store more accurately in `CompressedMapStatus`. This is pretty useful for example controlling shuffle blocks.

**Comment by jinxing64** [comment]
Jenkins, retest this please.

**Comment by jinxing64** [comment]
Jenkins, retest this please.

**Comment by cloud-fan** [comment]
is this still useful after we have https://github.com/apache/spark/pull/18031 ?

I think users can just set `spark.shuffle.accurateBlockThreshold` to a lower value if they want to esitimate shuffle block size more accurate.

**Comment by jinxing64** [comment]
True. I just try to make it more complete and refine the hardcode.
`spark.shuffle.accurateBlockThreshold` is useful, but sometimes it's hard for user to tune it("how low is enough? and at the same time I want to control the size of `MapStatus` within a fixed bound). This is corner case anyway. 
I can close this pr if you think it too trivial.

**Comment by cloud-fan** [comment]
every new config comes with a cost that users have to learn about it. For this case users already have a config(`spark.shuffle.accurateBlockThreshold`) to tune it, and this config is also hard to tune IMO.

Let's close it first. If we get a real use case that needs this config, we can reopen.

**Comment by jinxing64** [comment]
Sure :)

**Pull request closed without merging**
