### PR TITLE
[SPARK-28145][K8S] safe runnable in polling executor source

### PR DESCRIPTION
**Pull request by onursatici**
## What changes were proposed in this pull request?

Add error handling to `ExecutorPodsPollingSnapshotSource`

### CODE REVIEW

**Comment by liyinan926** [comment]
ok to test

**Review by srowen — COMMENTED** [review]
This merely makes sure the error is logged, right? the thread still dies on exception.

**Comment by onursatici** [comment]
@srowen I think it will log and not throw `NonFatal` exceptions now.

**Comment by onursatici** [comment]
@srowen from what I understand, this will log and not throw `NonFatal` exceptions now. https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/util/Utils.scala#L1333

**Comment by srowen** [comment]
Yep, I mean, the thread will still exit after the error is logged. I think that's still your intent? but the JIRA suggests that exiting on error is the problem.

**Comment by onursatici** [comment]
Yea so this `Runnable` is enqueued via `ScheduledExecutorService::scheduleWithFixedDelay`, so if any execution of this runnable throws, then all subsequent runs will be cancelled.

**Review by srowen — APPROVED** [review]

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
