### PR TITLE
[SPARK-43660][CONNECT][PS][FOLLOWUP] Remove JVM dependency for resample

### PR DESCRIPTION
**Pull request by itholic**
### What changes were proposed in this pull request?

This is follow-up for https://github.com/apache/spark/pull/41877 to remove JVM dependency.

### Why are the changes needed?

To remove JVM dependency from Pandas API on Spark with Spark Connect.

### Does this PR introduce _any_ user-facing change?

No, it's internal handling.

### How was this patch tested?

The existing UT.

### CODE REVIEW

**Comment by itholic** [comment]
cc @HyukjinKwon addressing https://github.com/apache/spark/pull/41877/files#r1286739868.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by HyukjinKwon** [comment]
Oops, I didn't see the tests are still running. Reverting

**Comment by HyukjinKwon** [comment]
@itholic please fix the linter

**Comment by itholic** [comment]
CI passed. @HyukjinKwon FYI

**Comment by zhengruifeng** [comment]
LGTM, merged to master

**Pull request closed without merging**
