### PR TITLE
[SPARK-8278] Remove non-streaming JSON reader.

### PR DESCRIPTION
**Pull request by rxin**

### CODE REVIEW

**Comment by rxin** [comment]
This is basically #6728 but brought up to date.

**Comment by rxin** [comment]
cc @yhuai  and @NathanHowell  I noticed the streaming jackson implementation doesn't support COLUMN_NAME_OF_CORRUPT_RECORD anymore. Is this going to be a problem?

**Comment by yhuai** [comment]
@rxin Streaming jackson implementation does handle corrupt record (see https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/json/JacksonParser.scala#L39 and https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/json/InferSchema.scala#L37).

**Comment by rxin** [comment]
Ah ok. It just reads from the config directly. I'm going to merge this then.

**Pull request closed without merging**
