### PR TITLE
[R] DO NOT MERGE debugging R packages

### PR DESCRIPTION
**Pull request by shaneknapp**
### What changes were proposed in this pull request?

no changes

### Why are the changes needed?

no changes

### Does this PR introduce any user-facing change?
no

### How was this patch tested?

via build system

### CODE REVIEW

**Comment by shaneknapp** [comment]
totally weird:

```
Warning message:
roxygen2 requires Encoding: UTF-8 
```

but the build env has that set:
`LANG | en_US.UTF-8`

maybe we need to s/en_us\.// on the env var?

**Comment by shaneknapp** [comment]
ok, `htmltools` resinstalled, which seems to have helped.

also, i don't think we ever had `arrow` installed...  i'll put that on the list as well.

**Comment by shaneknapp** [comment]
> also, i don't think we ever had `arrow` installed... i'll put that on the list as well.

um, this is a much bigger project apparently, as i need to build arrow from source to create the C++ libs.

definitely out of scope of this PR.

**Comment by shaneknapp** [comment]
> ok, `htmltools` resinstalled, which seems to have helped.

also `yaml`, which seems to be the final package...  i hope lol

**Comment by shaneknapp** [comment]
test this please

**Comment by shaneknapp** [comment]
test this please

**Comment by shaneknapp** [comment]
> > ok, `htmltools` resinstalled, which seems to have helped.
> 
> also `yaml`, which seems to be the final package... i hope lol

and `plyr`...  re https://github.com/apache/spark/pull/27456#issuecomment-582195489

**Comment by shaneknapp** [comment]
test this please

**Comment by shaneknapp** [comment]
> > ok, `htmltools` resinstalled, which seems to have helped.
> 
> also `yaml`, which seems to be the final package... i hope lol

add `e1071` as well

**Comment by shaneknapp** [comment]
test this please

**Comment by shaneknapp** [comment]
WOOT!

@HyukjinKwon do you want to open a PR to revert this change:  
https://github.com/apache/spark/pull/27460/files#diff-9e63dce390dd4d80c6abe3413a8b1984R34

we might as well add the LANG setting for `DESCRIPTION` and make roxygen2 happy again:
https://github.com/apache/spark/pull/27468/commits/ecbc087873c06b83ca563c162abed2f6f0bf7ba1

**Comment by HyukjinKwon** [comment]
Thanks, @shaneknapp. I will take a followup action accordingly.

**Pull request closed without merging**
