### PR TITLE
[SPARK-25657][SQL][TEST] Refactor HashBenchmark to use main method

### PR DESCRIPTION
**Pull request by wangyum**
## What changes were proposed in this pull request?

Refactor `HashBenchmark` to use main method.
1. use `spark-submit`:
```console
bin/spark-submit --class  org.apache.spark.sql.HashBenchmark --jars ./core/target/spark-core_2.11-3.0.0-SNAPSHOT-tests.jar ./sql/catalyst/target/spark-catalyst_2.11-3.0.0-SNAPSHOT-tests.jar
```

2. Generate benchmark result:
```console
SPARK_GENERATE_BENCHMARK_FILES=1 build/sbt "catalyst/test:runMain org.apache.spark.sql.HashBenchmark"
```

## How was this patch tested?
manual tests

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Also, please review and merge https://github.com/wangyum/spark/pull/16 .

**Comment by wangyum** [comment]
retest this please

**Comment by wangyum** [comment]
retest this please

**Review by dongjoon-hyun — APPROVED** [review]
Thank you, @wangyum .

+1, LGTM. Merged to master.

**Pull request closed without merging**
