### PR TITLE
[SPARK-30289][FOLLOWUP][DOC] Update the migration guide for `spark.sql.legacy.ctePrecedencePolicy`

### PR DESCRIPTION
**Pull request by xuanyuanking**
### What changes were proposed in this pull request?
Fix the migration guide document for `spark.sql.legacy.ctePrecedence.enabled`, which is introduced in #27579.

### Why are the changes needed?
The config value changed.

### Does this PR introduce any user-facing change?
No.

### How was this patch tested?
Document only.

### CODE REVIEW

**Comment by xuanyuanking** [comment]
cc @viirya @cloud-fan

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Now we started to build the documentation in PR builders as well https://github.com/apache/spark/pull/27782/checks?check_run_id=483869358. I will merge once this passes.

**Comment by viirya** [comment]
Cannot use laptop now. LGTM.

**Comment by cloud-fan** [comment]
LGTM

**Comment by HyukjinKwon** [comment]
Merged to master and branch-3.0.

**Comment by xuanyuanking** [comment]
Thanks!

**Pull request closed without merging**
