### PR TITLE
[SPARK-45704][BUILD] Fix compile warning - using symbols inherited from a superclass shadow symbols defined in an outer scope

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
After upgrade to scala 2.13, when using symbols inherited from a superclass shadow symbols defined in an outer scope, the following warning will appear:
```
[error] /Users/panbingkun/Developer/spark/spark-community/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/predicates.scala:1315:39: reference to child is ambiguous;
[error] it is both defined in the enclosing method apply and inherited in the enclosing anonymous class as value child (defined in class IsNull)
[error] In Scala 2, symbols inherited from a superclass shadow symbols defined in an outer scope.
[error] Such references are ambiguous in Scala 3. To continue using the inherited symbol, write `this.child`.
[error] Or use `-Wconf:msg=legacy-binding:s` to silence this warning. [quickfixable]
[error] Applicable -Wconf / @nowarn filters for this fatal warning: msg=<part of the message>, cat=other, site=org.apache.spark.sql.catalyst.expressions.IsUnknown.apply
[error]       override def sql: String = s"(${child.sql} IS UNKNOWN)"
[error]                                       ^
```
The pr aims to fix it.

### Why are the changes needed?
Prepare for upgrading to scala 3.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
- Pass GA
- Manually test:
   ```
   build/sbt -Phadoop-3 -Pdocker-integration-tests -Pspark-ganglia-lgpl -Pkinesis-asl -Pkubernetes -Phive-thriftserver -Pconnect -Pyarn -Phive -Phadoop-cloud -Pvolcano -Pkubernetes-integration-tests Test/package streaming-kinesis-asl-assembly/assembly connect/assembly
   ```

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by LuciferYang** [comment]
Let's remove `"-Wconf:msg=legacy-binding:s"` from SparkBuild and pom.xml

**Comment by panbingkun** [comment]
> Let's remove `"-Wconf:msg=legacy-binding:s"` from SparkBuild and pom.xml

Done.

**Review by LuciferYang — APPROVED** [review]
+1, LGTM if test pass

**Review by dongjoon-hyun — APPROVED** [review]
Could you revise the PR title a little more specific, @panbingkun ?

**Comment by panbingkun** [comment]
> Could you revise the PR title a little more specific, @panbingkun ?

Done

**Comment by dongjoon-hyun** [comment]
Thank you so much, @panbingkun . Merged to master.

**Pull request closed without merging**
