### PR TITLE
[SPARK-8923] [Documentation, MLlib] Add @since tags to mllib.fpm

### PR DESCRIPTION
**Pull request by rahulpalamuttam**

### CODE REVIEW

**Comment by mengxr** [comment]
@rahulpalamuttam `@since` means the Spark version when the method is first introduced. Some of the methods under `mllib.fpm` should be since 1.3.0. Please check the instructions on https://issues.apache.org/jira/browse/SPARK-7751. We don't need `@since` tag for private methods.

**Comment by rahulpalamuttam** [comment]
I've fixed the versions and removed the tags on private methods and classes.

**Comment by mengxr** [comment]
ok to test

**Comment by mengxr** [comment]
LGTM pending Jenkins

**Comment by mengxr** [comment]
Merged into master. Thanks!

**Comment by stumped2** [comment]
Please do not do anything to close this PR. It is being used in a support ticket to GitHub.

**Comment by mengxr** [comment]
@stumped2 Any update about the status?

**Comment by stumped2** [comment]
Sorry, closing now.

**Pull request closed without merging**
