### PR TITLE
[SPARK-17254][SQL] Add StopAfter physical plan for the filtering that can be stopped early

### PR DESCRIPTION
**Pull request by viirya**
## What changes were proposed in this pull request?

This is motivated by:

From https://issues.apache.org/jira/secure/attachment/12778890/BucketedTables.pdf:

For some data which are sorted such as bucketed table with SORT BY, the filtering on it can be stopped early if the filtering condition satisfies some requirements. For example, the filtering like “WHERE id < 10” can be stopped as soon as the first row on which the id column is with values equal to or more than 10 is seen. I.e., once the condition is false, the filtering can be stopped.

This pr adds a new `StopAfterExec` physical plan to achieve this.

Design document: https://issues.apache.org/jira/secure/attachment/12834609/stop-after-physical-plan.pdf
### Benchmark

```
val N = 500L << 18
val df = sparkSession.range(N).sort("id").persist()
runBenchmark("range/sort/filter/sum", N) {
  df.filter("id < 10").groupBy().sum().collect()
}
```

Before this patch:

```
Java HotSpot(TM) 64-Bit Server VM 1.8.0_102-b14 on Linux 4.4.20-moby
Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
range/sort/filter/sum:                   Best/Avg Time(ms)    Rate(M/s)   Per Row(ns)   Relative
------------------------------------------------------------------------------------------------
range/sort/filter/sum wholestage off           266 /  389        493.4           2.0       1.0X
range/sort/filter/sum wholestage on            170 /  208        771.9           1.3       1.6X
```

After this patch:

```
Java HotSpot(TM) 64-Bit Server VM 1.8.0_102-b14 on Linux 4.4.20-moby
Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
range/sort/filter/sum:                   Best/Avg Time(ms)    Rate(M/s)   Per Row(ns)   Relative
------------------------------------------------------------------------------------------------
range/sort/filter/sum wholestage off           141 /  207        928.4           1.1       1.0X
range/sort/filter/sum wholestage on             49 /   67       2694.1           0.4       2.9X
```
## How was this patch tested?

Jenkins tests. Manually test.

### CODE REVIEW

**Comment by cloud-fan** [comment]
Is it possible to speed up the whole-stage-on case? We can create a new physical operator `FilterOnSortedData` to isolate this special logic.

**Comment by viirya** [comment]
@cloud-fan If this direction is okay for you, I can investigate it further.

**Comment by cloud-fan** [comment]
If the filter condition is deterministic, I think this is a good optimization, especially for bucketed(with SORT BY) table, cc @yhuai @gatorsmile

**Comment by viirya** [comment]
Re-open it and see if we can have some consensus about this direction.

**Comment by rxin** [comment]
This would really only be interesting if it works with whole stage code gen; otherwise it is not really interesting.

In addition, it'd make sense to have an explicit operator for this, e.g. StopAfter, so it is obvious in the explain plan.

**Comment by cloud-fan** [comment]
@viirya can you try to create a new operator for this optimization and make it work with whole-stage-codegen? thanks!

**Comment by rxin** [comment]
FYI this is a relevant paper http://www.comp.nus.edu.sg/~tankl/cs5208/readings/enough.pdf

**Comment by rxin** [comment]
So I'd recommend closing this for now. @viirya you are welcome to work on it still, but it should:

1. Be obvious in explain (e.g. through an operator) that this behavior exists.
2. Works for code gen.
3. Modular logic, ideally determined by the query planner.
4. Correct.

One thing we need to decide is whether the final improvement is worth the complexity.

**Comment by gatorsmile** [comment]
@viirya This is a pretty interesting. Based on the suggestion from @rxin let us discuss it? Also cc @ioana-delaney @nsyca

**Comment by viirya** [comment]
@rxin Thanks for recommendation! Let me close it now and work on it.

**Comment by viirya** [comment]
retest this please.

**Comment by ioana-delaney** [comment]
@viirya Hi Simon, I have some general comments/questions:
1. It will help to include in the design document some example queries together with their corresponding optimized + physical plans. 
2. I looked at the new test suite and all the examples are simple examples using DFs. Can we include some more complex examples? Maybe some examples referencing the bucketed tables that you reference in this PR. Another example using some more complex SQL e.g. select * from (select t1.c1 + t2.c1 as col1 from t1, t2 where t1.c1 = t2.c1 order by col1) v1 where v1.col1 < 10
```SQL
== Physical Plan ==
*Sort [col1#2 ASC NULLS FIRST], true, 0
+- Exchange rangepartitioning(col1#2 ASC NULLS FIRST, 5)
   +- *Project [(c1#12 + c1#15) AS col1#2]
      +- *SortMergeJoin [c1#12], [c1#15], Inner, ((c1#12 + c1#15) < 10)
         :- *Sort [c1#12 ASC NULLS FIRST], false, 0
         :  +- Exchange hashpartitioning(c1#12, 5)
         :     +- HiveTableScan [c1#12], MetastoreRelation default, t1
         +- *Sort [c1#15 ASC NULLS FIRST], false, 0
            +- Exchange hashpartitioning(c1#15, 5)
               +- HiveTableScan [c1#15], MetastoreRelation default, t2
```

3.In the above plan, is the local predicate c1#12 + c1#15 < 10 applied after the join, or as part of the join? i.e. does it stop the join execution once the values are outside the range? 

4.An observation is that besides the above SQL query, which might already work today, I couldn’t easily find other SQL examples that would benefit from this optimization since most of the predicates are pushed down to base tables, which in general are not ordered. I can think of some Having predicates, but they probably don't qualify.

5. Your changes look very general. Are you also supporting Filters over Bucketed tables, which you reference in this PR? 

6. Do Bucketed tables allow inserts/appends? How will that work with your optimization? 

Thanks

**Comment by viirya** [comment]
@ioana-delaney Thanks for review!

I replied few points first. I will add the tests you mentioned later.

4. This feature is motivated from the bucketed (and sorted, of course) table jira. For this case, the Filter can be applied on the sorted data. At that time, we can leverage it and optimize the filtering. Another case I can think is cached data, when you cache sorted data as I did in the current tests, the Filter won't be pushed down and will work on the sorted data directly.

5. Yeah. From the view of `StopAfter` operator, it only cares about if the child is sorted or not. If the bucketed table is sorted too, it can support it. Of course I will add a test for it.

6. Yes it does. Currently if the bucketed table is inserted or appended, we can't guarantee its sort order. So it will be skipped.

**Comment by viirya** [comment]
@ioana-delaney 

About your point 3, I don't see a separated Filter in this physical plan. This change only converts Filter to StopAfter. I think this change won't apply on it.

**Comment by viirya** [comment]
@ioana-delaney I've added the test using bucketed table. Please take a look. Thanks.

**Comment by viirya** [comment]
ping @rxin @cloud-fan Please review this when you have time. Thanks!

**Comment by viirya** [comment]
Close this for now. Re-open if anyone is interested in this.

**Pull request closed without merging**
