### PR TITLE
Get default Locale

### PR DESCRIPTION
**Pull request by Gschiavon**
## What changes were proposed in this pull request?

Get default Locale in UtilsSuite.scala in order to make it work with different Locales than US.

## How was this patch tested?

Running UtilsSuite.scala 

Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Comment by srowen** [comment]
No, because the project is purposely not locale sensitive at this level.

**Comment by Gschiavon** [comment]
As far as I saw there are other test cases that set default locale to US. This case is not passing when your jvm default locale value differs from "US".

**Comment by srowen** [comment]
Ah, the problem is the reverse really, but there is a problem. `"...".format(...)` is locale-sensitive in Scala, and this is a place where that matters. The `Utils` method needs to change to use `formalLocal` with `Locale.US`. Open a JIRA for it, and close this and reopen vs `master` with that fix.

**Comment by Gschiavon** [comment]
Ok, I got it. I will do that then. 
Thanks.

**Pull request closed without merging**
