### PR TITLE
[SPARK-8533][Streaming] Upgrade Flume to 1.6.0

### PR DESCRIPTION
**Pull request by harishreedharan**

### CODE REVIEW

**Comment by srowen** [comment]
This is probably fine, but are there any potential incompatibilities or significant differences between the two that would affect any users? might be worth a scan through the release notes and/or resolved JIRAs as a sanity check.

**Comment by srowen** [comment]
Ping @harishreedharan I am sure you wouldn't propose this otherwise, but, just wanted to understand what if any potential incompatibilities this entails, particularly regarding dependencies. Do you know of any risks?

**Comment by harishreedharan** [comment]
I am on vacation till Sunday. Please feel free to merge this - if I have
any concerns at that time I will make some noise.

On Tuesday, June 30, 2015, Sean Owen <notifications@github.com> wrote:

> Ping @harishreedharan <https://github.com/harishreedharan> I am sure you
> wouldn't propose this otherwise, but, just wanted to understand what if any
> potential incompatibilities this entails, particularly regarding
> dependencies. Do you know of any risks?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apache/spark/pull/6939#issuecomment-117159663>.
>


-- 

Thanks,
Hari

**Comment by tdas** [comment]
I will wait for the #6830 to be merged which is more contentious. Some things may need to be updated in this PR if there are conflicts. And then we will be able to run flume scala, java and python tests against 1.6.0 to see if there are potential issues.

**Comment by harishreedharan** [comment]
ping @tdas

**Comment by tdas** [comment]
Jenkins, test this please.

**Comment by harishreedharan** [comment]
This pyspark test has been failing all over:
```
======================================================================
FAIL: test_time_with_timezone (__main__.SQLTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jenkins/workspace/SparkPullRequestBuilder/python/pyspark/sql/tests.py", line 716, in test_time_with_timezone
    self.assertEqual(now, now1)
AssertionError: datetime.datetime(2015, 7, 9, 20, 56, 12, 108430) != datetime.datetime(2015, 7, 9, 20, 56, 12, 108429)
```

@marmbrus - In case you are not aware.

**Comment by davies** [comment]
@harishreedharan Will fix the flaky test by #7344

**Comment by srowen** [comment]
Since https://github.com/apache/spark/pull/6830 is merged and this passes, anyone object to merging?

**Comment by tdas** [comment]
LGTM, since all scala/java/python tests pass, this is good to go. I am merging this to master.

**Comment by tdas** [comment]
Hey @harishreedharan i have merged this. Somehow this PR was not closed automatically. Can you close it?

**Pull request closed without merging**
