### PR TITLE
[SPARK-14103][SQL] Parse unescaped quotes in CSV data source.

### PR DESCRIPTION
**Pull request by HyukjinKwon**
## What changes were proposed in this pull request?

This PR resolves the problem during parsing unescaped quotes in input data. For example, currently the data below:

```
"a"b,ccc,ddd
e,f,g
```

produces a data below:
- **Before**

``` bash
["a"b,ccc,ddd[\n]e,f,g]  <- as a value.
```
- **After**

``` bash
["a"b], [ccc], [ddd]
[e], [f], [g]
```

This PR bumps up the Univocity parser's version. This was fixed in `2.0.2`, https://github.com/uniVocity/univocity-parsers/issues/60.
## How was this patch tested?

Unit tests in `CSVSuite` and `sbt/sbt scalastyle`.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @srowen

**Comment by srowen** [comment]
LGTM

**Comment by HyukjinKwon** [comment]
@rxin Could you maybe take another look or merge this please?

**Comment by rxin** [comment]
Thanks - I actually run into this issue yesterday! Merging.

**Pull request closed without merging**
