### PR TITLE
[SPARK-20636] Add the rule TransposeWindow to the optimization batch

### PR DESCRIPTION
**Pull request by gatorsmile**
## What changes were proposed in this pull request?

This PR is a follow-up of the PR https://github.com/apache/spark/pull/17899. It is to add the rule TransposeWindow the optimizer batch. 

## How was this patch tested?
The existing tests.

### CODE REVIEW

**Comment by gatorsmile** [comment]
cc @ptkool @jiangxb1987 @cloud-fan

**Comment by cloud-fan** [comment]
That PR also added an end-to-end test, does this mean that test is not valid?

**Comment by gatorsmile** [comment]
We can compare the plans and see whether the rule takes an effect.

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Review by jiangxb1987 — APPROVED** [review]
LGTM

**Comment by cloud-fan** [comment]
Jenkins passes, which means the previously added end-to-end test can't not show the benefit of this rule. We should update it.

**Comment by ptkool** [comment]
I'm not sure how this ended up being omitted. `TransposeWindowSuite` will be fine since it creates a simple optimizer from this rule and a few others. The new test added to `DataFrameWindowFunctionsSuite` should pass with or without this rule added to the optimizer batch.

**Comment by cloud-fan** [comment]
LGTM

**Comment by gatorsmile** [comment]
Thanks! Merged to master.

**Pull request closed without merging**
