### PR TITLE
[SPARK-36410][CORE][SQL][STRUCTURED STREAMING][EXAMPLES] Replace anonymous classes with lambda expressions

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
The main change of this pr is replace anonymous classes with lambda expressions in Java code

**Before**
```java
 new Thread(new Runnable() {
    @Override
    public void run() {
      // run thread
    }
  });
```

**After**

```java
new Thread(() -> {
    // run thread
  });
```

### Why are the changes needed?
Code Simpilefications.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?

- Pass the Jenkins or GitHub Action
- Manually test `JavaUserDefinedScalar` with command 
   `bin/spark-submit run-example org.apache.spark.examples.sql.JavaUserDefinedScalar` passed

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
> Pass the Jenkins or GitHub Action

The changes look good but can you also run the examples that you're fixing manually to verify the changes?

**Comment by LuciferYang** [comment]
> The changes look good but can you also run the examples that you're fixing manually to verify the changes?

OK ~

**Comment by LuciferYang** [comment]
> The changes look good but can you also run the examples that you're fixing manually to verify the changes?

@HyukjinKwon 

1. I manually verified `JavaUserDefinedScalar` with command 

```shell
bin/spark-submit run-example org.apache.spark.examples.sql.JavaUserDefinedScalar
```
The result is right

2. I don't have a kinesis service to test now, so I revert the change of `JavaKinesisWordCountASL` in this pr
3. I found the examples can't run in the IDE (such as IntelliJ), I created a new Jira( SPARK-36422 ) to  track it

**Review by HyukjinKwon — APPROVED** [review]

**Comment by LuciferYang** [comment]
ping @HyukjinKwon

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by LuciferYang** [comment]
Thanks @HyukjinKwon ~ do I need to do anything for Spark 3.2 or older?

**Pull request closed without merging**
