### PR TITLE
[SPARK-34005][CORE] Update peak memory metrics for each Executor on task end

### PR DESCRIPTION
**Pull request by sarutak**
### What changes were proposed in this pull request?

This PR makes `AppStatusListener` update the peak memory metrics for each Executor on task end like other peak memory metrics (e.g, stage, executors in a stage).

### Why are the changes needed?

When `AppStatusListener#onExecutorMetricsUpdate` is called, peak memory metrics for Executors, stages and executors in a stage are updated but currently, the metrics only for Executors are not updated on task end.

### Does this PR introduce _any_ user-facing change?

Yes. Executor peak memory metrics is updated more accurately.

### How was this patch tested?

After I run a job with `local-cluster[1,1,1024]` and visited `/api/v1/<appid>/executors`, I confirmed `peakExecutorMemory` metrics is shown for an Executor even though the life time of each job is very short .
I also modify the json files for `HistoryServerSuite`.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @gengliangwang, @jiangxb1987 and @Ngone51 FYI

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @sarutak .
Merged to master for Apache Spark 3.2.0.

**Comment by gengliangwang** [comment]
@sarutak @dongjoon-hyun shall we port this to branch-3.1 as well?

**Comment by dongjoon-hyun** [comment]
This is registered as an improvement for 3.2.0, @gengliangwang .

**Comment by dongjoon-hyun** [comment]
cc @HyukjinKwon since he is the release manager.

**Comment by sarutak** [comment]
Hmm, I registered this improvement for `3.2` but  there is a similar change (#30858) merged into `3.1`.

**Comment by dongjoon-hyun** [comment]
That was merged a month ago (Dec 20, 2020).

**Comment by HyukjinKwon** [comment]
I am fine with backporting improvements if it's clearly safe. For example, I did backport some changes like https://github.com/apache/spark/commit/c3d8352ca1a59ce5cc37840919c0e799f5150efa too.

**Comment by dongjoon-hyun** [comment]
+1 for the release manager's decision for this specific commit.

**Comment by sarutak** [comment]
O.K, I'll open a backport PR.

**Pull request closed without merging**
