### PR TITLE
[SPARK-22309][ML] Remove unused param in `LDAModel.getTopicDistributionMethod`

### PR DESCRIPTION
**Pull request by zhengruifeng**
## What changes were proposed in this pull request?
Remove unused param in `LDAModel.getTopicDistributionMethod` 

## How was this patch tested?
existing tests

### CODE REVIEW

**Comment by srowen** [comment]
This is probably OK but let's focus away from making many tiny unrelated changes

**Comment by BryanCutler** [comment]
LGTM

**Comment by BryanCutler** [comment]
fyi it looks like this is cleanup from removing a broadcast in #18152

**Comment by srowen** [comment]
Agree, I've merged the JIRA. Merged to master

**Pull request closed without merging**
