### PR TITLE
[DOCS] [MINOR] Fixed scaladoc java example syntax in DataSet

### PR DESCRIPTION
**Pull request by ashishawasthi**
## What changes were proposed in this pull request?

Fixed scaladoc java example syntax in DataSet.scala
## How was this patch tested?

No new tests required as this is a doc example change
Existing tests passed (using ./dev/run-tests)

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
@ashishawasthi Then, I think you can take out `[SPARK-15223]` which I guess it is not related. Also, It would be nicer if the title does not have `@rxin` at the end. Lastly, `p.s.` might better be left in comments because it might not related with the PR description itself.

**Comment by ashishawasthi** [comment]
I didn't create a new JIRA as the [guidelines](https://cwiki.apache.org/confluence/display/SPARK/Contributing+to+Spark#ContributingtoSpark-JIRA) say, "trivial changes, where the what should change is virtually the same as the how it should change do not require a JIRA"

**Comment by srowen** [comment]
He is not suggesting you make a JIRA

**Comment by ashishawasthi** [comment]
Owen, I'm not making any JIRA, just moved that comment out of description, as suggested.

**Comment by ashishawasthi** [comment]
@srowen I'm not creating JIRA, just moved the line from description to comment as suggested by @HyukjinKwon

**Comment by ashishawasthi** [comment]
closing as already fixed in repo

**Pull request closed without merging**
