### PR TITLE
[SPARK-47932][SQL][TESTS] Avoid using legacy commons-lang

### PR DESCRIPTION
**Pull request by pan3793**
### What changes were proposed in this pull request?

Remove usage of `commons-lang` and in favor `commons-lang3`

### Why are the changes needed?

Migrate `commons-lang` to `commons-lang3`

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Pass GA.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by smileyboy2019** [comment]
Structured Streaming supports writing Spark SQL and using SQL to write stream processing logic. Is this possible, similar to the syntax of Flink. SQL can satisfy the flow processing process.

**Comment by pan3793** [comment]
@smileyboy2019 the question is irrelevant to this PR, please ask questions in the mailing list or Slack.

**Review by LuciferYang — APPROVED** [review]

**Comment by pan3793** [comment]
@smileyboy2019 Please STOP spamming on this thread. You can refer to https://spark.apache.org/community.html to subscribe to Spark Mailing lists and ask questions.

**Comment by LuciferYang** [comment]
Merged into master for Spark 4.0. Thanks @pan3793

**Pull request closed without merging**
