### PR TITLE
[SPARK-47665][SQL] Use SMALLINT to Write ShortType to MYSQL

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

This PR uses MySQL SMALLINT to write ShortType to MYSQL, as we read SMALLINT as ShortType. 

### Why are the changes needed?

SMALLINT fits better for ShortType and plays roundtrip for r/w.

### Does this PR introduce _any_ user-facing change?
yes, type mapping changes

### How was this patch tested?
new tests

### Was this patch authored or co-authored using generative AI tooling?
no

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Could you resolve the conflicts, @yaooqinn ?

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM (Pending CIs).

**Comment by yaooqinn** [comment]
Thank you @dongjoon-hyun

**Comment by yaooqinn** [comment]
Thank you @dongjoon-hyun. Merged to master.

PS: The impact on existing workloads is trivial, as users are still able to write shorts to pre-defined int-tables

**Pull request closed without merging**
