### PR TITLE
[SPARK-6857][SQL] Add support of numpy types for Python SQL schema inference

### PR DESCRIPTION
**Pull request by viirya**
JIRA https://issues.apache.org/jira/browse/SPARK-6857

### CODE REVIEW

**Comment by viirya** [comment]
Need numpy module...

**Comment by davies** [comment]
We need to convert the numpy types into Python types anyway, so I think it's better to be done BEFORE inferring schema, then we do not need to change types.py, also user could do the conversion by themselves.

**Comment by jkbradley** [comment]
@viirya  Thank you for your PR!  However, based on the JIRA discussion, I think it will be best if we close this PR and mark the JIRA as not a problem (since UDTs are probably a better fix for this issue long-term).  Would you mind closing the PR?

**Comment by viirya** [comment]
ok, I'm close it.

**Pull request closed without merging**
