### PR TITLE
[SPARK-42833][SQL] Refactor `applyExtensions` in `SparkSession`

### PR DESCRIPTION
**Pull request by kazuyukitanimura**
### What changes were proposed in this pull request?
This PR proposes to do a minor refactoring in `SparkSession`, particularly the private method `applyExtensions`

### Why are the changes needed?
This is a pure refactoring to reduce some code duplications such as `getConf.get(StaticSQLConf.SPARK_SESSION_EXTENSIONS).getOrElse(Seq.empty)`

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Existing tests

### CODE REVIEW

**Comment by kazuyukitanimura** [comment]
cc @dongjoon-hyun @sunchao @viirya

**Comment by dongjoon-hyun** [comment]
Thank you for pinging me, @kazuyukitanimura .

**Comment by dongjoon-hyun** [comment]
cc @cloud-fan and @HyukjinKwon , too.

**Review by sunchao — APPROVED** [review]
LGTM

**Review by viirya — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @kazuyukitanimura and all.
Merged to master for Apache Spark 3.5.

**Comment by kazuyukitanimura** [comment]
Thank you!

**Comment by cloud-fan** [comment]
late LGTM

**Pull request closed without merging**
