### PR TITLE
[SPARK-31807][INFRA] Use python 3 style in release-build.sh

### PR DESCRIPTION
**Pull request by williamhyun**
### What changes were proposed in this pull request?

This PR aims to use the style that is compatible with both python 2 and 3.

### Why are the changes needed?

This will help python 3 migration.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Manual.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
ok to test

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master and branch-3.0.

**Comment by williamhyun** [comment]
Thank you, @HyukjinKwon !

**Comment by dongjoon-hyun** [comment]
Hi, @williamhyun and @HyukjinKwon .
I cherry-pick this to branch-2.4 to fix GitHub Action snapshot publishing.

cc @viirya

**Comment by viirya** [comment]
Got it. Thanks @dongjoon-hyun

**Comment by HyukjinKwon** [comment]
Thanks!

**Pull request closed without merging**
