### PR TITLE
[SPARK-40280][SQL][FOLLOWUP][3.2] Fix 'ParquetFilterSuite' issue

### PR DESCRIPTION
**Pull request by zzcclp**
### What changes were proposed in this pull request?
Use `Operators.And` instead of `Operators.In` in ParquetFilterSuite, the `org.apache.parquet.filter2.predicate.Operators.In` was added in the parquet 1.12.3, but spark branch-3.2 uses the parquet 1.12.2.

### Why are the changes needed?
Fix 'ParquetFilterSuite' compile error after merging #37747 :
The `org.apache.parquet.filter2.predicate.Operators.In` was added in the parquet 1.12.3, but spark branch-3.2 uses the parquet 1.12.2.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Existing UT.

### CODE REVIEW

**Review by wangyum — APPROVED** [review]

**Comment by zzcclp** [comment]
@revans2 @cloud-fan @wangyum please take a review, thanks.

**Review by revans2 — APPROVED** [review]

**Review by tgravescs — APPROVED** [review]

**Comment by tgravescs** [comment]
thanks for fixing @zzcclp  I should have built it on these before merging

**Review by huaxingao — APPROVED** [review]

**Comment by huaxingao** [comment]
The test failure doesn't seem to be related to this PR. I will merge this PR.

**Comment by huaxingao** [comment]
@zzcclp Could you please update the PR description to fill all the required information?

**Comment by huaxingao** [comment]
Merged to 3.2. Thanks @zzcclp for fixing this! Also thanks @tgravescs @revans2 @wangyum for reviewing!

**Comment by zzcclp** [comment]
> @zzcclp Could you please update the PR description to fill all the required information?

Done.

**Pull request closed without merging**
