### PR TITLE
[SPARK-47077][BUILD][TEST] Fix sbt build Revert [SPARK-44445][BUILD][TESTS]

### PR DESCRIPTION
**Pull request by holdenk**
### What changes were proposed in this pull request?

This reverts commit f5b1e37c9e6a4ec2fd897f97cd4526415e6c0e49.

### Why are the changes needed?
Building with sbt & JDK11 or 17 (executed after reload & clean ;compile;catalyst/testOnly org.apache.spark.sql.catalyst.optimizer.FilterPushdownSuite) results in

 
[error] /home/holden/repos/spark/core/src/test/scala/org/apache/spark/deploy/history/ChromeUIHistoryServerSuite.scala:20:8: object WebDriver is not a member of package org.openqa.selenium
[error] import org.openqa.selenium.WebDriver
[error]        ^
[error] /home/holden/repos/spark/core/src/test/scala/org/apache/spark/deploy/history/ChromeUIHistoryServerSuite.scala:33:27: not found: type WebDriver
[error]   override var webDriver: WebDriver = _
[error]                           ^
[error] /home/holden/repos/spark/core/src/test/scala/org/apache/spark/deploy/history/ChromeUIHistoryServerSuite.scala:37:29: Class org.openqa.selenium.remote.AbstractDriverOptions not found - continuing with a stub.
[error]     val chromeOptions = new ChromeOptions
[error]                             ^
[error] /home/holden/repos/spark/core/src/test/scala/org/apache/spark/deploy/history/RealBrowserUIHistoryServerSuite.scala:24:8: object WebDriver is not a member of package org.openqa.selenium
[error] import org.openqa.selenium.WebDriver
[error]        ^
[error] /home/holden/repos/spark/core/src/test/scala/org/apache/spark/deploy/history/RealBrowserUIHistoryServerSuite.scala:43:27: not found: type WebDriver
[error]   implicit var webDriver: WebDriver
[error]                           ^
[error] /home/holden/repos/spark/core/src/test/scala/org/apache/spark/deploy/history/ChromeUIHistoryServerSuite.scala:39:21: Class org.openqa.selenium.remote.RemoteWebDriver not found - continuing with a stub.
[error]     webDriver = new ChromeDriver(chromeOptions)
[error]                     ^
[error] /home/holden/repos/spark/core/src/test/scala/org/apache/spark/deploy/history/ChromeUIHistoryServerSuite.scala:20:28: Unused import
[error] Applicable -Wconf / @nowarn filters for this fatal warning: msg=<part of the message>, cat=unused-imports, site=org.apache.spark.deploy.history
[error] import org.openqa.selenium.WebDriver
[error]                            ^
[error] /home/holden/repos/spark/core/src/test/scala/org/apache/spark/deploy/history/HistoryServerSuite.scala:36:8: object WebDriver is not a member of package org.openqa.selenium
[error] import org.openqa.selenium.WebDriver
[error]        ^
[error] /home/holden/repos/spark/core/src/test/scala/org/apache/spark/deploy/history/HistoryServerSuite.scala:383:29: not found: type WebDriver
[error]     implicit val webDriver: WebDriver = new HtmlUnitDriver
[error]                             ^
[error] /home/holden/repos/spark/core/src/test/scala/org/apache/spark/deploy/history/HistoryServerSuite.scala:37:8: Class org.openqa.selenium.WebDriver not found - continuing with a stub.
[error] import org.openqa.selenium.htmlunit.HtmlUnitDriver
[error]        ^
[error] /home/holden/repos/spark/core/src/test/scala/org/apache/spark/deploy/history/HistoryServerSuite.scala:383:45: Class org.openqa.selenium.Capabilities not found - continuing with a stub.
[error]     implicit val webDriver: WebDriver = new HtmlUnitDriver
[error]                                             ^
[error] /home/holden/repos/spark/core/src/test/scala/org/apache/spark/deploy/history/HistoryServerSuite.scala:470:9: Symbol 'type org.openqa.selenium.WebDriver' is missing from the classpath.
[error] This symbol is required by 'value org.scalatestplus.selenium.WebBrowser.go.driver'.
[error] Make sure that type WebDriver is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[error] A full rebuild may help if 'WebBrowser.class' was compiled against an incompatible version of org.openqa.selenium.
[error]         go to target.toExternalForm
[error]         ^
[error] /home/holden/repos/spark/core/src/test/scala/org/apache/spark/deploy/history/HistoryServerSuite.scala:470:12: could not find implicit value for parameter driver: org.openqa.selenium.WebDriver
[error]         go to target.toExternalForm
[error]            ^
[error] /home/holden/repos/spark/core/src/test/scala/org/apache/spark/deploy/history/HistoryServerSuite.scala:36:28: Unused import
[error] Applicable -Wconf / @nowarn filters for this fatal warning: msg=<part of the message>, cat=unused-imports, site=org.apache.spark.deploy.history
[error] import org.openqa.selenium.WebDriver
[error]                            ^
[error] /home/holden/repos/spark/core/src/test/scala/org/apache/spark/deploy/history/RealBrowserUIHistoryServerSuite.scala:24:28: Unused import
[error] Applicable -Wconf / @nowarn filters for this fatal warning: msg=<part of the message>, cat=unused-imports, site=org.apache.spark.deploy.history
[error] import org.openqa.selenium.WebDriver
[error]                            ^
[error] /home/holden/repos/spark/core/src/test/scala/org/apache/spark/deploy/history/RealBrowserUIHistoryServerSuite.scala:27:47: Unused import
[error] Applicable -Wconf / @nowarn filters for this fatal warning: msg=<part of the message>, cat=unused-imports, site=org.apache.spark.deploy.history
[error] import org.scalatest.matchers.should.Matchers._
[error]                                               ^
[error] /home/holden/repos/spark/core/src/test/scala/org/apache/spark/ui/ChromeUISeleniumSuite.scala:20:8: object JavascriptExecutor is not a member of package org.openqa.selenium
[error] import org.openqa.selenium.{JavascriptExecutor, WebDriver}
[error]        ^
[error] /home/holden/repos/spark/core/src/test/scala/org/apache/spark/ui/ChromeUISeleniumSuite.scala:32:27: not found: type WebDriver
[error]   override var webDriver: WebDriver with JavascriptExecutor = _
[error]                           ^
[error] /home/holden/repos/spark/core/src/test/scala/org/apache/spark/ui/ChromeUISeleniumSuite.scala:32:42: not found: type JavascriptExecutor
[error]   override var webDriver: WebDriver with JavascriptExecutor = _
[error]                                          ^
[error] /home/holden/repos/spark/core/src/test/scala/org/apache/spark/ui/RealBrowserUISeleniumSuite.scala:20:8: object By is not a member of package org.openqa.selenium
[error] import org.openqa.selenium.{By, JavascriptExecutor, WebDriver}
[error]        ^
[error] /home/holden/repos/spark/core/src/test/scala/org/apache/spark/ui/RealBrowserUISeleniumSuite.scala:39:27: not found: type WebDriver
[error]   implicit var webDriver: WebDriver with JavascriptExecutor
[error]                           ^
[error] /home/holden/repos/spark/core/src/test/scala/org/apache/spark/ui/RealBrowserUISeleniumSuite.scala:39:42: not found: type JavascriptExecutor
[error]   implicit var webDriver: WebDriver with JavascriptExecutor
[error]                                          ^
[error] /home/holden/repos/spark/core/src/test/scala/org/apache/spark/ui/ChromeUISeleniumSuite.scala:20:29: Unused import
[error] Applicable -Wconf / @nowarn filters for this fatal warning: msg=<part of the message>, cat=unused-imports, site=org.apache.spark.ui
[error] import org.openqa.selenium.{JavascriptExecutor, WebDriver}
[error]                             ^
[error] /home/holden/repos/spark/core/src/test/scala/org/apache/spark/ui/ChromeUISeleniumSuite.scala:20:49: Unused import
[error] Applicable -Wconf / @nowarn filters for this fatal warning: msg=<part of the message>, cat=unused-imports, site=org.apache.spark.ui
[error] import org.openqa.selenium.{JavascriptExecutor, WebDriver}
[error]                                                 ^
[error] /home/holden/repos/spark/core/src/test/scala/org/apache/spark/ui/RealBrowserUISeleniumSuite.scala:20:29: Unused import
[error] Applicable -Wconf / @nowarn filters for this fatal warning: msg=<part of the message>, cat=unused-imports, site=org.apache.spark.ui
[error] import org.openqa.selenium.{By, JavascriptExecutor, WebDriver}
[error]                             ^
[error] /home/holden/repos/spark/core/src/test/scala/org/apache/spark/ui/RealBrowserUISeleniumSuite.scala:20:33: Unused import
[error] Applicable -Wconf / @nowarn filters for this fatal warning: msg=<part of the message>, cat=unused-imports, site=org.apache.spark.ui
[error] import org.openqa.selenium.{By, JavascriptExecutor, WebDriver}
[error]                                 ^
[error] /home/holden/repos/spark/core/src/test/scala/org/apache/spark/ui/RealBrowserUISeleniumSuite.scala:20:53: Unused import
[error] Applicable -Wconf / @nowarn filters for this fatal warning: msg=<part of the message>, cat=unused-imports, site=org.apache.spark.ui
[error] import org.openqa.selenium.{By, JavascriptExecutor, WebDriver}
[error]                                                     ^
[error] /home/holden/repos/spark/core/src/test/scala/org/apache/spark/ui/RealBrowserUISeleniumSuite.scala:23:47: Unused import
[error] Applicable -Wconf / @nowarn filters for this fatal warning: msg=<part of the message>, cat=unused-imports, site=org.apache.spark.ui
[error] import org.scalatest.matchers.should.Matchers._
[error]                                               ^
[error] /home/holden/repos/spark/core/src/test/scala/org/apache/spark/ui/UISeleniumSuite.scala:32:8: object By is not a member of package org.openqa.selenium
[error] import org.openqa.selenium.{By, WebDriver}
[error]        ^
[error] /home/holden/repos/spark/core/src/test/scala/org/apache/spark/ui/UISeleniumSuite.scala:87:27: not found: type WebDriver
[error]   implicit var webDriver: WebDriver = _
[error]                           ^
[error] /home/holden/repos/spark/core/src/test/scala/org/apache/spark/ui/UISeleniumSuite.scala:21:18: Unused import
[error] Applicable -Wconf / @nowarn filters for this fatal warning: msg=<part of the message>, cat=unused-imports, site=org.apache.spark.ui
[error] import java.util.Locale
[error]                  ^
[error] /home/holden/repos/spark/core/src/test/scala/org/apache/spark/ui/UISeleniumSuite.scala:32:29: Unused import
[error] Applicable -Wconf / @nowarn filters for this fatal warning: msg=<part of the message>, cat=unused-imports, site=org.apache.spark.ui
[error] import org.openqa.selenium.{By, WebDriver}
[error]                             ^
[error] /home/holden/repos/spark/core/src/test/scala/org/apache/spark/ui/UISeleniumSuite.scala:32:33: Unused import
[error] Applicable -Wconf / @nowarn filters for this fatal warning: msg=<part of the message>, cat=unused-imports, site=org.apache.spark.ui
[error] import org.openqa.selenium.{By, WebDriver}
[error]                                 ^
[error] /home/holden/repos/spark/sql/catalyst/src/test/scala/org/apache/spark/sql/catalyst/optimizer/FilterPushdownSuite.scala: expected start of definition, but was Token(VAL,val,28273,val)
[warn] one warning found
[error] 33 errors found
[error] stack trace is suppressed; run last catalyst / scalaStyleOnTest for the full output
[error] (core / Test / compileIncremental) Compilation failed
[error] (catalyst / scalaStyleOnTest) Failing because of negative scalastyle result
[error] Total time: 16 s, completed Feb 16, 2024, 3:05:47 PM

### Does this PR introduce _any_ user-facing change?

Test only

### How was this patch tested?
Local sbt testing

### Was this patch authored or co-authored using generative AI tooling?
No

### CODE REVIEW

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
Sorry but could you give me some background or reproducible procedures, @holdenk ?

**Comment by dongjoon-hyun** [comment]
From the following PR description, Apache Spark 4.0 only support Java 17+, doesn't it?

> Building with sbt & JDK11 or 17

**Comment by dongjoon-hyun** [comment]
FYI, all GitHub Action works fine without any compilation failure like that. The is the result from my environment.
```
$ java -version
openjdk version "17.0.10" 2024-01-16 LTS
OpenJDK Runtime Environment AppleJDK-17.0.10.7.1 (build 17.0.10+7-LTS)
OpenJDK 64-Bit Server VM AppleJDK-17.0.10.7.1 (build 17.0.10+7-LTS, mixed mode, sharing)

$ build/sbt
sbt:spark-parent> clean ;compile;catalyst/testOnly org.apache.spark.sql.catalyst.optimizer.FilterPushdownSuite
...
[info] FilterPushdownSuite:
[info] - eliminate subqueries (21 milliseconds)
[info] - simple push down (12 milliseconds)
[info] - combine redundant filters (12 milliseconds)
[info] - do not combine non-deterministic filters even if they are identical (10 milliseconds)
[info] - SPARK-16164: Filter pushdown should keep the ordering in the logical plan (7 milliseconds)
[info] - SPARK-16994: filter should not be pushed through limit (3 milliseconds)
[info] - can't push without rewrite (11 milliseconds)
[info] - nondeterministic: can always push down filter through project with deterministic field (11 milliseconds)
[info] - nondeterministic: can't push down filter through project with nondeterministic field (4 milliseconds)
[info] - nondeterministic: can't push down filter through aggregate with nondeterministic field (6 milliseconds)
[info] - nondeterministic: push down part of filter through aggregate with deterministic field (9 milliseconds)
[info] - filters: combines filters (5 milliseconds)
[info] - joins: push to either side (8 milliseconds)
[info] - joins: push to one side (6 milliseconds)
[info] - joins: do not push down non-deterministic filters into join condition (2 milliseconds)
[info] - joins: push to one side after transformCondition (6 milliseconds)
[info] - joins: rewrite filter to push to either side (4 milliseconds)
[info] - joins: push down left semi join (6 milliseconds)
[info] - joins: push down left outer join #1 (6 milliseconds)
[info] - joins: push down right outer join #1 (6 milliseconds)
[info] - joins: push down left outer join #2 (5 milliseconds)
[info] - joins: push down right outer join #2 (6 milliseconds)
[info] - joins: push down left outer join #3 (6 milliseconds)
[info] - joins: push down right outer join #3 (13 milliseconds)
[info] - joins: push down left outer join #4 (6 milliseconds)
[info] - joins: push down right outer join #4 (10 milliseconds)
[info] - joins: push down left outer join #5 (6 milliseconds)
[info] - joins: push down right outer join #5 (9 milliseconds)
[info] - joins: can't push down (4 milliseconds)
[info] - joins: conjunctive predicates (8 milliseconds)
[info] - joins: conjunctive predicates #2 (3 milliseconds)
[info] - joins: conjunctive predicates #3 (7 milliseconds)
[info] - joins: push down where clause into left anti join (5 milliseconds)
[info] - joins: only push down join conditions to the right of a left anti join (4 milliseconds)
[info] - joins: only push down join conditions to the right of an existence join (4 milliseconds)
[info] - generate: predicate referenced no generated column (9 milliseconds)
[info] - generate: non-deterministic predicate referenced no generated column (7 milliseconds)
[info] - generate: part of conjuncts referenced generated column (6 milliseconds)
[info] - generate: all conjuncts referenced generated column (2 milliseconds)
[info] - aggregate: push down filter when filter on group by expression (7 milliseconds)
[info] - aggregate: don't push down filter when filter not on group by expression (5 milliseconds)
[info] - aggregate: push down filters partially which are subset of group by expressions (8 milliseconds)
[info] - aggregate: push down filters with alias (5 milliseconds)
[info] - aggregate: push down filters with literal (9 milliseconds)
[info] - aggregate: don't push down filters that are nondeterministic (7 milliseconds)
[info] - SPARK-17712: aggregate: don't push down filters that are data-independent (6 milliseconds)
[info] - aggregate: don't push filters if the aggregate has no grouping expressions (3 milliseconds)
[info] - SPARK-32940: aggregate: push filters through first, last and collect (17 milliseconds)
[info] - union (11 milliseconds)
[info] - expand (19 milliseconds)
[info] - predicate subquery: push down simple (15 milliseconds)
[info] - predicate subquery: push down complex (8 milliseconds)
[info] - SPARK-20094: don't push predicate with IN subquery into join condition (11 milliseconds)
[info] - Window: predicate push down -- basic (24 milliseconds)
[info] - Window: predicate push down -- predicates with compound predicate using only one column (5 milliseconds)
[info] - Window: predicate push down -- multi window expressions with the same window spec (5 milliseconds)
[info] - Window: predicate push down -- multi window specification - 1 (9 milliseconds)
[info] - Window: predicate push down -- multi window specification - 2 (7 milliseconds)
[info] - Window: predicate push down -- predicates with multiple partitioning columns (5 milliseconds)
[info] - Window: predicate push down -- complex predicate with the same expressions !!! IGNORED !!!
[info] - Window: no predicate push down -- predicates are not from partitioning keys (5 milliseconds)
[info] - Window: no predicate push down -- partial compound partition key (4 milliseconds)
[info] - Window: no predicate push down -- complex predicates containing non partitioning columns (4 milliseconds)
[info] - Window: no predicate push down -- complex predicate with different expressions (5 milliseconds)
[info] - watermark pushdown: no pushdown on watermark attribute #1 (121 milliseconds)
[info] - watermark pushdown: no pushdown for nondeterministic filter (5 milliseconds)
[info] - watermark pushdown: full pushdown (2 milliseconds)
[info] - watermark pushdown: no pushdown on watermark attribute #2 (2 milliseconds)
[info] - push down predicate through expand (2 milliseconds)
[info] - SPARK-28345: PythonUDF predicate should be able to pushdown to join (2 milliseconds)
[info] - push down filter predicates through inner join (10 milliseconds)
[info] - push down join predicates through inner join (2 milliseconds)
[info] - push down complex predicates through inner join (5 milliseconds)
[info] - push down predicates(with NOT predicate) through inner join (3 milliseconds)
[info] - push down predicates through left join (2 milliseconds)
[info] - push down predicates through right join (4 milliseconds)
[info] - SPARK-32302: avoid generating too many predicates (3 milliseconds)
[info] - push down predicate through multiple joins (4 milliseconds)
[info] - SPARK-37828: Push down filters through RebalancePartitions (3 milliseconds)
[info] - SPARK-46707: push down predicate with sequence (without step) through joins (4 milliseconds)
[info] - SPARK-46707: push down predicate with sequence (without step) through aggregates (5 milliseconds)
[info] - SPARK-46707: combine predicate with sequence (without step) with other filters (3 milliseconds)
[info] Run completed in 1 second, 946 milliseconds.
[info] Total number of tests run: 81
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 81, failed 0, canceled 0, ignored 1, pending 0
[info] All tests passed.
[success] Total time: 52 s, completed Feb 16, 2024, 3:21:56 PM
```

**Comment by dongjoon-hyun** [comment]
How can I help you, @holdenk ?

**Comment by holdenk** [comment]
So with JDK11 (or 17) run:
`sbt` then run:
```
reload
clean
;compile;catalyst/testOnly org.apache.spark.sql.catalyst.optimizer.FilterPushdownSuite
```

I've run this on DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"
with
`openjdk 17.0.9 2023-10-17` and `openjdk 11.0.21 2023-10-17` respectively.

I'm on x86 but that shouldn't make a difference? Maybe my maven cache is screwy let me blow it away and try again.

**Comment by dongjoon-hyun** [comment]
First of all, why do you insist to run `openjdk 11.0.21 2023-10-17`?
You know that we dropped Java 11, doesn't you?

**Comment by holdenk** [comment]
Yeah I just have both on my system and when I get unexpected compile errors I sometimes jump back to an earlier JDK to see if that's the issue.

**Comment by dongjoon-hyun** [comment]
I'm trying to follow your procedure locally. I didn't try `reload` part in https://github.com/apache/spark/pull/45144#issuecomment-1949475905 .

BTW, did you try to clear up the Maven and Ivy cache?

**Comment by holdenk** [comment]
I did an `rm -rf ~/.m2/repository` and `rm -rf ~/.ivy/cache` and re-ran it and it passed fine. My bad for not checking that it's (it was compiling fine prior to my rebase + reload though so I didn't suspect a corrupted/invalid artifact).

**Comment by dongjoon-hyun** [comment]
Oh, great!

**Comment by dongjoon-hyun** [comment]
Thank you for closing.

**Pull request closed without merging**
