### PR TITLE
[SPARK-13211][STREAMING] Deprecate certain constructors of StreamingContext's

### PR DESCRIPTION
**Pull request by lw-lin**
## What changes were proposed in this pull request?

These constructors, each of which takes a checkpoint path parameter, are deprecated by this PR:
- `StreamingContext`'s
  - `this(path: String, hadoopConf: Configuration)`
  - `this(path: String)`
  - `this(path: String, sparkContext: SparkContext)`
- `JavaStreamingContext`'s
  - `this(path: String)`
  - `this(path: String, hadoopConf: Configuration)`
## How was this patch tested?

Existing test suits.

### CODE REVIEW

**Comment by lw-lin** [comment]
As reported in [\[Spark-13211\]](https://issues.apache.org/jira/browse/SPARK-13211), `StreamingContext` would throw `NoSuchElementException` when created from non-existent checkpoint directory.

Actually, the `SparkContext.getOrCreate(path, ...)` was added in https://github.com/apache/spark/commit/a1b8dd53e3474dae2c49b30bc9719c7f6b98c7cc as the major API for users to create a `StreamingContext` from some checkpoint; see http://spark.apache.org/docs/latest/streaming-programming-guide.html#checkpointing. `SparkContext.getOrCreate(path, ...)` checks if the path exists, checks if any valid checkpoint file exists in the given path, and does or does not re-throw the exception when encounter one.

**Comment by srowen** [comment]
This doesn't address the problem. The existing API you're purporting to deprecate is still entirely fine and necessary. We're talking about a better error message when, incorrectly, later, a checkpoint directory is required but none was specified.

**Comment by srowen** [comment]
@lw-lin  you can close this PR given https://github.com/apache/spark/pull/12174

**Comment by lw-lin** [comment]
@srowen sure, thank you for this review, :-)

**Pull request closed without merging**
