### PR TITLE
[SPARK-13551] [MLLib] Fix wrong comment and remove meanless lines in mllib.JavaBisectingKMeansExample

### PR DESCRIPTION
**Pull request by zhengruifeng**
JIRA: https://issues.apache.org/jira/browse/SPARK-13551
## What changes were proposed in this pull request?

Fix wrong comment and remove meanless lines in mllib.JavaBisectingKMeansExample
## How was this patch tested?

manual test

### CODE REVIEW

**Comment by srowen** [comment]
Agree, but you don't need to bother with a JIRA

**Comment by srowen** [comment]
Jenkins, test this please

**Comment by zhengruifeng** [comment]
@srowen Sorry, but can I make a PR without JIRA?

**Comment by mengxr** [comment]
Merged into master. Thanks!

**Pull request closed without merging**
