### PR TITLE
[SPARK-21205][SQL] pmod(number, 0) should be null.

### PR DESCRIPTION
**Pull request by wangyum**
## What changes were proposed in this pull request?
Hive `pmod(3.13, 0)`:
```:sql
hive> select pmod(3.13, 0);
OK
NULL
Time taken: 2.514 seconds, Fetched: 1 row(s)
hive> 
```

Spark `mod(3.13, 0)`:
```:sql
spark-sql> select mod(3.13, 0);
NULL
spark-sql> 
```

But the Spark `pmod(3.13, 0)`:
```:sql
spark-sql> select pmod(3.13, 0);
17/06/25 09:35:58 ERROR SparkSQLDriver: Failed in [select pmod(3.13, 0)]
java.lang.NullPointerException
	at org.apache.spark.sql.catalyst.expressions.Pmod.pmod(arithmetic.scala:504)
	at org.apache.spark.sql.catalyst.expressions.Pmod.nullSafeEval(arithmetic.scala:432)
	at org.apache.spark.sql.catalyst.expressions.BinaryExpression.eval(Expression.scala:419)
	at org.apache.spark.sql.catalyst.expressions.UnaryExpression.eval(Expression.scala:323)
...
```
This PR make `pmod(number, 0)` to null.

## How was this patch tested?
unit tests

### CODE REVIEW

**Comment by srowen** [comment]
I don't know enough to review the change but I believe you're correct. Dividing by zero also results in NULL right?

**Comment by gatorsmile** [comment]
cc @wzhfy

**Comment by wangyum** [comment]
Jenkins, retest this please

**Comment by wangyum** [comment]
Jenkins, retest this please

**Comment by wangyum** [comment]
Jenkins, retest this please

**Comment by wangyum** [comment]
@HyukjinKwon Could you help review this?

**Comment by hvanhovell** [comment]
retest this please

**Review by hvanhovell — APPROVED** [review]
LGTM - merging to master

**Pull request closed without merging**
