### PR TITLE
[SPARK-30228][BUILD][2.4] Update zstd-jni to 1.4.4-3

### PR DESCRIPTION
**Pull request by seayoun**
### What changes were proposed in this pull request?

Change zstd-jni version to version 1.4.4-3

### Why are the changes needed?

This old zstd-jni(tag 1.3.3-2) has probability to read less data when shuffle read.
The `ZstdInputStream` in zstd-jni(tag 1.3.3-2) maybe return 0 after a read function call, this doesn't meet the standard of `InputStream` and the `InputStream` will not return 0 unless len is 0; Spark will use a BufferedInputStream wrapped to ZstdInputStream, when ZstdInputStream read call return 0, BufferedInputStream will consider the 0 as the end of read and exit, this can lead data loss.
zstd-jni issues:
https://github.com/luben/zstd-jni/issues/159
zstd-jni commits:
https://github.com/luben/zstd-jni/commit/7eec5581b8ccb0d98350ad5ba422337eebbbe70e

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @dongjoon-hyun FYI

**Review by HyukjinKwon — COMMENTED** [review]
Can you also run `./dev/test-dependencies.sh --replace-manifest`?

**Comment by cloud-fan** [comment]
Usually, we don't upgrade dependencies in released branches. But this is a correctness bug and I think we can make an exception here.

**Comment by cloud-fan** [comment]
ok to test

**Comment by seayoun** [comment]
> Can you also run `./dev/test-dependencies.sh --replace-manifest`?

OK

**Review by cloud-fan — APPROVED** [review]

**Comment by cloud-fan** [comment]
cc @srowen as well

**Comment by seayoun** [comment]
> Usually, we don't upgrade dependencies in released branches. But this is a correctness bug and I think we can make an exception here.

@cloud-fan It's hard to add an exception here because it is imperceptible for spark, because spark use `BufferedInputStream` to deal with `ZstdInputStream` return 0, it's not in spark's core but the jdk.

**Review by srowen — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Yeah this one is fine.

**Review by HyukjinKwon — APPROVED** [review]

**Review by dongjoon-hyun — COMMENTED** [review]
Since this is marked as a correctness issue, do you think we can have a test case, @seayoun ?
Also, I'm wondering why 1.4.4-3? The target commit is in 1.3.5-x, too.

**Comment by dongjoon-hyun** [comment]
In the JIRA, I found the following, but the reason for the version choice is missing.
> So, I think it's nessary to upgrade zstd-jni version to 1.4.4-3 in spark2.4 for spark2.4 has a wide use in production.

**Comment by srowen** [comment]
It could be hard to reproduce zstd returning 0 bytes before EOF. If we can we'd mostly be testing what zstd tests already - the stream just never returns 0 bytes before done. If it's pretty hard to test, I think it's OK to merge without a specific test.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by dongjoon-hyun** [comment]
Merged to branch-2.4.

**Comment by seayoun** [comment]
> In the JIRA, I found the following, but the reason for the version choice is missing.
> 
> > So, I think it's nessary to upgrade zstd-jni version to 1.4.4-3 in spark2.4 for spark2.4 has a wide use in production.
Another issue for ZstdInputStream. It happends in 1.4.4-3
https://github.com/luben/zstd-jni/issues/110

**Comment by dongjoon-hyun** [comment]
Thanks, @seeyoun . You meant that another issue is fixed at 1.4.4-3, right? (Instead of `happens in 1.4.4-3`)
> Another issue for ZstdInputStream. It happends in 1.4.4-3

**Pull request closed without merging**
