### PR TITLE
[SPARK-21801][SPARKR][TEST] set random seed for predictable test

### PR DESCRIPTION
**Pull request by felixcheung**
## What changes were proposed in this pull request?

set.seed() before running tests

## How was this patch tested?

jenkins, appveyor

### CODE REVIEW

**Comment by WeichenXu123** [comment]
I found `NaiveBayes` also possible to fail. Founded here #18538 . Hope this can works!

https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/81316/console

```
2. Error: spark.naiveBayes (@test_mllib_classification.R#482) ------------------
java.lang.IllegalArgumentException: requirement failed: The input column stridx_5a965aeed344 should have at least two distinct values.
	at scala.Predef$.require(Predef.scala:224)
	at org.apache.spark.ml.feature.OneHotEncoder$$anonfun$5.apply(OneHotEncoder.scala:113)
...
1: spark.naiveBayes(traindf, clicked ~ ., smoothing = 0) at /home/jenkins/workspace/SparkPullRequestBuilder/R/pkg/tests/fulltests/test_mllib_classification.R:482
2: spark.naiveBayes(traindf, clicked ~ ., smoothing = 0)
3: .local(data, formula, ...)
4: callJStatic("org.apache.spark.ml.r.NaiveBayesWrapper", "fit", formula, data@sdf, 
       smoothing, handleInvalid)
5: invokeJava(isStatic = TRUE, className, methodName, ...)
6: handleErrors(returnStatus, conn)
7: stop(readString(conn))

DONE ===========================================================================
Error: Test failures
Execution halted
```

**Comment by felixcheung** [comment]
Yes, the issue is with random sampling, and this PR should fix all of these.
I'm not sure why I haven't seen them much before - they have been around for years - appreciate bringing these up, we should track them with JIRA.

**Comment by felixcheung** [comment]
jenkins, retest this please

**Comment by felixcheung** [comment]
+ @shivaram could you do a quick review? given this change I'd love to get some feedback

**Comment by felixcheung** [comment]
jenkins, retest this please

**Comment by felixcheung** [comment]
jenkins, retest this please

**Comment by shivaram** [comment]
Should we set this before the call to `test_package` ? It'll be good to have it for the CRAN tests as well ?

**Review by WeichenXu123 — APPROVED** [review]
LGTM. Thanks!

**Comment by felixcheung** [comment]
possibly - I think it would be a good idea to leave this to the jenkins path for now to make sure it works, given how sensitive the CRAN path is....

**Comment by felixcheung** [comment]
jenkins, retest this please

**Comment by felixcheung** [comment]
ah?
```
[error] running /home/jenkins/workspace/SparkPullRequestBuilder/dev/lint-r ; process was terminated by signal 9
Attempting to post to Github...
```

**Comment by felixcheung** [comment]
jenkins, retest this please

**Comment by felixcheung** [comment]
merged to master

**Pull request closed without merging**
