### PR TITLE
Update py4j to 0.9.

### PR DESCRIPTION
**Pull request by kevincox**
Py4J 0.9 has a performance improvement for `unescape_new_line` which significantly reduces the time required to transfer large strings.

cc @angelini

### CODE REVIEW

**Comment by JoshRosen** [comment]
Jenkins, this is ok to test.

**Comment by kevincox** [comment]
Updated to reference the right package.

**Comment by giwa** [comment]
Is this duplicated? #8615

**Comment by kevincox** [comment]
It looks like it is.

**Comment by srowen** [comment]
Yes, do you mind closing this PR? best to search JIRA and/or PRs first.

**Pull request closed without merging**
