### PR TITLE
[SPARK-20626][SPARKR] address date test warning with timezone on windows

### PR DESCRIPTION
**Pull request by felixcheung**
## What changes were proposed in this pull request?

set timezone on windows

## How was this patch tested?

unit test, AppVeyor

### CODE REVIEW

**Comment by felixcheung** [comment]
similar flaky test around ml, with this in the log
```
Exception in thread "SparkListenerBus" java.lang.IllegalAccessError: Attempted to access garbage collected accumulator 50693
	at org.apache.spark.util.AccumulatorContext$$anonfun$get$1.apply(AccumulatorV2.scala:265)
	at org.apache.spark.util.AccumulatorContext$$anonfun$get$1.apply(AccumulatorV2.scala:261)
	at scala.Option.map(Option.scala:146)
	at org.apache.spark.util.AccumulatorContext$.get(AccumulatorV2.scala:261)
	at org.apache.spark.util.AccumulatorV2.name(AccumulatorV2.scala:88)
	at org.apache.spark.sql.execution.metric.SQLMetric.toInfo(SQLMetrics.scala:67)
	at org.apache.spark.sql.execution.ui.SQLListener$$anonfun$onTaskEnd$1.apply(SQLListener.scala:216)
	at org.apache.spark.sql.execution.ui.SQLListener$$anonfun$onTaskEnd$1.apply(SQLListener.scala:216)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.apache.spark.sql.execution.ui.SQLListener.onTaskEnd(SQLListener.scala:216)
	at org.apache.spark.scheduler.SparkListenerBus$class.doPostEvent(SparkListenerBus.scala:45)
	at org.apache.spark.scheduler.LiveListenerBus.doPostEvent(LiveListenerBus.scala:36)
	at org.apache.spark.scheduler.LiveListenerBus.doPostEvent(LiveListenerBus.scala:36)
	at org.apache.spark.util.ListenerBus$class.postToAll(ListenerBus.scala:63)
	at org.apache.spark.scheduler.LiveListenerBus.postToAll(LiveListenerBus.scala:36)
	at org.apache.spark.scheduler.LiveListenerBus$$anon$1$$anonfun$run$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(LiveListenerBus.scala:94)
	at org.apache.spark.scheduler.LiveListenerBus$$anon$1$$anonfun$run$1$$anonfun$apply$mcV$sp$1.apply(LiveListenerBus.scala:79)
	at org.apache.spark.scheduler.LiveListenerBus$$anon$1$$anonfun$run$1$$anonfun$apply$mcV$sp$1.apply(LiveListenerBus.scala:79)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.apache.spark.scheduler.LiveListenerBus$$anon$1$$anonfun$run$1.apply$mcV$sp(LiveListenerBus.scala:78)
	at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1268)
	at org.apache.spark.scheduler.LiveListenerBus$$anon$1.run(LiveListenerBus.scala:77
```

**Comment by felixcheung** [comment]
merged to master/2.2

**Comment by yhuai** [comment]
@felixcheung Seems master build is broken because R tests are broken (https://amplab.cs.berkeley.edu/jenkins/view/Spark%20QA%20Test/job/spark-master-test-sbt-hadoop-2.7/2844/console). I am not sure if this PR caused that. Can you help to take a look?

**Comment by felixcheung** [comment]
No, don't think so. Is there a recent change to catalog APIs - the failed tests are with table names.

**Comment by felixcheung** [comment]
@yhuai @gatorsmile how about https://github.com/apache/spark/pull/17649

**Pull request closed without merging**
