### PR TITLE
[SPARK-6824] Fill the docs for DataFrame API in SparkR

### PR DESCRIPTION
**Pull request by hqzizania**
This patch also removes the RDD docs from being built as a part of roxygen just by the method to delete 
" ' '" of " #' ".

### CODE REVIEW

**Comment by shivaram** [comment]
Jenkins, retest this please

**Comment by shivaram** [comment]
Thanks @hqzizania - This is the right approach for this PR. There are a couple of more docs that we should make private -- one is the Broadcast class and its members like `setValue`, `clearBroadcastVariables` etc. and the other is methods in SparkContext like `parallelize`, `textFile` etc. Since RRDD is private, we shouldn't have docs for methods which generate them as well.

**Comment by hqzizania** [comment]
@shivaram  I've remove docs about broadcast and context, and check Rd files with ones in NAMESPACE. But I wonder why length(rdd) exists in DataFrame export in NAMESPACE? and why export("sparkRSQL.init",
       "sparkRHive.init") written twice in NAMESPACE?

**Comment by shivaram** [comment]
Thanks @hqzizania - I missed that fact that `length` doesn't exist in DataFrame. We can remove it for now from the namespace. In the future we could add a length and `dim` function

Also the duplicates should be removed as well

**Comment by shivaram** [comment]
Thanks @hqzizania - LGTM. We could do a few more cleanups later based on how the knitr documents look (I think some of the rdnames we use might be good to change etc.) but lets do that in a follow up PR

**Pull request closed without merging**
