### PR TITLE
[SPARK-6784] [SQL] Clean up all the inbound/outbound conversions for DateType

### PR DESCRIPTION
**Pull request by scwf**
/cc @yhuai and @davies

### CODE REVIEW

**Comment by marmbrus** [comment]
Sorry for the confusion, but this JIRA was not about adding methods for mutating data columns, but fixing places in the execution engine where you could get errors because the types are not handled correctly.

**Comment by scwf** [comment]
@marmbrus, thanks your explain. But after i go through the DateType related code i think we have converted date type to int when execution. 
I added a unit test for date type support.

**Comment by marmbrus** [comment]
You are correct that most of the places have been converted but there are still some mistakes.  For example, I believe date columns in partitioning columns.  JDBC was also doing the conversion wrong when the ticket was opened, but I believe that has been fixed now.

**Comment by scwf** [comment]
For date columns in partitioning columns, should i start this work after #5526 is in, right?

**Comment by marmbrus** [comment]
Check with @adrian-wang who might be working on the partitioning column issue already.

**Comment by adrian-wang** [comment]
For the idea of `getDate` and `setDate` interface I think it is already rejected in #2284 . And I'm working on partitioning column already...

**Comment by scwf** [comment]
i am closing this

**Pull request closed without merging**
