### PR TITLE
[SPARK-10608][CORE] disable reduce locality as default

### PR DESCRIPTION
**Pull request by liyezhang556520**
for details, pls refer to [SPARK-10608](https://issues.apache.org/jira/browse/SPARK-10608)

### CODE REVIEW

**Comment by liyezhang556520** [comment]
jenkins, retest this please

**Comment by zsxwing** [comment]
@liyezhang556520 could you update this PR? Thanks!

**Comment by liyezhang556520** [comment]
@zsxwing , Since the original implementation has changed a lot, let me close this PR/JIRA first, if the issue still exists, I'll reopen.

**Pull request closed without merging**
