### PR TITLE
[SPARK-35920][BUILD] Upgrade to Chill 0.10.0

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to upgrade Chill to 0.10.0.

### Why are the changes needed?

This is a maintenance release having cross-compilation to 2.12.14 and 2.13.6 .
- https://github.com/twitter/chill/releases/tag/v0.10.0

### Does this PR introduce _any_ user-facing change?

No, this is a dependency change.

### How was this patch tested?

Pass the CIs.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Could you review this, @srowen ?

**Review by HyukjinKwon — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @HyukjinKwon . Merged to master.

**Comment by gao634209276** [comment]
Is this tested? When I was compiling the unsafe module, I found that esotericsoftware was missing a dependency and reported an error

**Comment by dongjoon-hyun** [comment]
@gao634209276 . Could you show your procedure?

> Is this tested? I found that the unsafe module is missing a dependency: com.esotericsoftware:kryo-shaded

As I wrote on the PR, SBT and Maven works fine with `unsafe` module.
- https://github.com/apache/spark/pull/33131

**Pull request closed without merging**
