### PR TITLE
[SPARK-32028][WEBUI][2.4] fix app id link for multi attempts app in history summary page

### PR DESCRIPTION
**Pull request by srowen**
This is simply a backport of https://github.com/apache/spark/pull/28867 to branch-2.4

### CODE REVIEW

**Comment by srowen** [comment]
@zhli1142015 does this back port look correct? It wasn't a 100% clean cherry-pick but I think I got the change mapped correctly.

**Comment by srowen** [comment]
Jenkins, test this please

**Comment by zhli1142015** [comment]
@srowen , thanks for taking care this. This looks good to me.

**Comment by srowen** [comment]
Jenkins test this please

**Comment by dongjoon-hyun** [comment]
Thank you, @srowen and @zhli1142015 .

**Comment by srowen** [comment]
Jenkins retest this please

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Merged to branch-2.4.

**Pull request closed without merging**
