### PR TITLE
[MINOR][DOCS] Fix typos 

### PR DESCRIPTION
**Pull request by sudoliyang**
### What changes were proposed in this pull request?

Fix typos in the repo.

### Why are the changes needed?

Improve readability.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

No tests are needed.

### CODE REVIEW

**Comment by bjornjorgensen** [comment]
@srowen FYI

**Review by srowen — APPROVED** [review]
Looks good but see if you can re-run tests for good measure

**Comment by sudoliyang** [comment]
I did enable action on my forked repo and rebase to `apache/spark` master. 
Can anyone re-run the workflows?

**Comment by HyukjinKwon** [comment]
Mind double checking? Seems they are not running https://github.com/sudoliyang/spark/actions

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
