### PR TITLE
[SPARK-40607][CORE][SQL][MLLIB][SS] Remove redundant string interpolator operations

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr remove redundant string interpolator operations in Spark code, and the change of this pr does not include the code related to logs, exceptions, and `configurations.doc`.

### Why are the changes needed?
Clean up unnecessary function calls

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass Github Actions

### CODE REVIEW

**Comment by LuciferYang** [comment]
The amount of change is relatively large. Is it worth doing this?

**Comment by LuciferYang** [comment]
This pr not include `examples` and `test`

**Comment by LuciferYang** [comment]
The changed code is mainly divided into 3 categories: logs, exceptions, and others, log and exception related codes account for the majority

**Comment by LuciferYang** [comment]
> The changed code is mainly divided into 3 categories: logs, exceptions, and others, log and exception related codes account for the majority

**Comment by srowen** [comment]
Yeah it's just so much code churn and potential for merge conflicts for very little gain. Are there any of these that seem to be in a hot code path?

**Comment by LuciferYang** [comment]
Set to draft before change completed

**Review by srowen — APPROVED** [review]
OK, that seems more motivated and targeted. I think this could be OK

**Comment by LuciferYang** [comment]
thanks @srowen

**Comment by srowen** [comment]
Merged to master

**Comment by LuciferYang** [comment]
thanks @srowen

**Comment by HyukjinKwon** [comment]
Hey, let's avoid making such changes. I think this kind of stuff is to have a rule and sweep away which is actually rejected in https://github.com/apache/spark/pull/15960.

**Comment by srowen** [comment]
Yeah, this was much cut down to instances where it might matter. It's trivial though

**Comment by LuciferYang** [comment]
> Hey, let's avoid making such changes. I think this kind of stuff is to have a rule and sweep away which is actually rejected in #15960.

Okay, I see ~ thanks ~

**Comment by LuciferYang** [comment]
@HyukjinKwon Need to revert? Or do need to backport to other branches? Or keep the status quo?

**Pull request closed without merging**
