### PR TITLE
[SPARK-38988][PYTHON] Suppress PerformanceWarnings of `DataFrame.info`

### PR DESCRIPTION
**Pull request by xinrong-meng**
### What changes were proposed in this pull request?
Suppress PerformanceWarnings of DataFrame.info

### Why are the changes needed?
To improve usability.

### Does this PR introduce _any_ user-facing change?
No. Only PerformanceWarnings of DataFrame.info are suppressed.

### How was this patch tested?
Manual tests.

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]
I think it's fine. LGTM

**Comment by bjornjorgensen** [comment]
Thank you, @xinrong-databricks 
I did test this manually in a docker image. And now it don't show the  "PerformanceWarning: DataFrame is highly fragmented....." 

I do have a hope that we can have this PR in 3.3. This error message was not printed so many times in earlier releases.

**Comment by xinrong-databricks** [comment]
Thanks @bjornjorgensen for the verification!

@HyukjinKwon Would you think we may backport it to 3.3?

**Comment by HyukjinKwon** [comment]
Yeah

**Comment by HyukjinKwon** [comment]
Merged to master and branch-3.3.

**Pull request closed without merging**
