### PR TITLE
[WIP][SPARK-35954] Upgrade Apache Curator Dependency to 4.2.0

### PR DESCRIPTION
**Pull request by nirousseau**
WIP / DESCRIPTION TBD

Issue : https://issues.apache.org/jira/browse/SPARK-35954

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
cc @sunchao since @nirousseau wrote the following in the JIRA.
> Spark 3.2.0 aims to support Hadoop 3.3.1 ; this Hadoop release bundles the following shared libraries :
curator-client-4.2.0.jar
curator-framework-4.2.0.jar
curator-recipes-4.2.0.jar
zookeeper-3.5.6.jar
zookeeper-jute-3.5.6.jar

**Comment by dongjoon-hyun** [comment]
ok to test

**Comment by sunchao** [comment]
Thanks @dongjoon-hyun for pinging. Yes I think it's a good idea to keep the curator (and zookeeper?) version in sync with what come from Hadoop, similar to #28897.

**Comment by dongjoon-hyun** [comment]
Thank you for the confirmation, @sunchao .

**Comment by nirousseau** [comment]
as expected, it breaks tests, I will try to setup a local dev env and fix library changes asap.

**Comment by dongjoon-hyun** [comment]
Thank you for working on this, @nirousseau .

> as expected, it breaks tests, I will try to setup a local dev env and fix library changes asap.

**Comment by dongjoon-hyun** [comment]
I'll close this PR for now, @nirousseau . Feel free to reopen when the PR is ready. Thanks.

**Pull request closed without merging**
