### PR TITLE
[SPARK-29877][GRAPHX] static PageRank allow checkPoint from previous computations

### PR DESCRIPTION
**Pull request by JoanFM**
### What changes were proposed in this pull request?
Add an optional parameter to the staticPageRank computation with the result of a previous PageRank computation. This would make the algorithm start from a different starting point closer to the convergence configuration

### Why are the changes needed?
https://issues.apache.org/jira/browse/SPARK-29877

It would be really helpful to have the possibility, when computing staticPageRank to use a previous computation as a checkpoint to continue the iterations.

### Does this PR introduce any user-facing change?
Yes, it allows to start the static  page Rank computation from the point where an earlier one finished.

Example: Compute 10 iteration first, and continue for 3 more iterations
```scala
val partialPageRank = graph.ops.staticPageRank(numIter=10, resetProb=0.15)
val continuationPageRank = graph.ops.staticPageRank(numIter=3,  resetProb=0.15, Some(partialPageRank))
 ```

### How was this patch tested?
Yes, some tests were added.
Testing was done as follow:
- Check how many iterations it takes for a static Page Rank computation to converge
- Run the static Page Rank computation for half of these iterations and take result as checkpoint
- Restart computation and check that number of iterations it takes to converge. It never has to be larger than the original one and in most of the cases it is much smaller.

Due to the presence of sinks and the normalization done in [[SPARK-18847]] it is not exactly equivalent to compute static page rank for 2 iterations, take the result at checkpoint and run for 2 more iterations than to compute directly for 4 iterations.

However this checkpointing can give the algorithm a hint about the true distribution of pageRanks in the graph

### CODE REVIEW

**Comment by JoanFM** [comment]
I had to open this PR after closing PR https://github.com/apache/spark/pull/26608
I think because of force pushing some commits were not seen

**Comment by srowen** [comment]
Just to link it, the previous was actually https://github.com/apache/spark/pull/26523

**Review by srowen — COMMENTED** [review]
I think this is OK, API-wise. My only hesitation is that I'd have trouble evaluating whether the rewrite of the impl is the same. Is there any expected change in behavior even in corner cases? The fact that the tests still pass is a good sign on that front.

**Comment by JoanFM** [comment]
There is no expected change in behavior

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
