### PR TITLE
[SPARK-13023][PROJECT INFRA][FOLLOWUP][BRANCH-1.6] Unable to check `root` module ending up failure of Python tests

### PR DESCRIPTION
**Pull request by HyukjinKwon**
## What changes were proposed in this pull request?

This PR fixes incorrect checking for `root` module (meaning all tests).

I realised that https://github.com/apache/spark/pull/13806 is being failed due to this one.

The PR corrects two files in `sql` and `core`. Since it seems fixing `core` module triggers all tests by `root` value from `determine_modules_for_files`.
So, `changed_modules` becomes as below:

```
['root', 'sql']
```

and `module.dependent_modules` becaomes as below:

```
['pyspark-mllib', 'pyspark-ml', 'hive-thriftserver', 'sparkr', 'mllib', 'examples', 'pyspark-sql']
```

Now, `modules_to_test` does not include `root` and this checking is skipped but then both `changed_modules` and `modules_to_test` are being merged after that. So, this includes `root` module to test.

This ends up with failing with the message below (e.g. https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/60990/consoleFull):

```
Error: unrecognized module 'root'. Supported modules: pyspark-core, pyspark-sql, pyspark-streaming, pyspark-ml, pyspark-mllib
```
## How was this patch tested?

N/A

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @yhuai and @JoshRosen

**Comment by yhuai** [comment]
Looks good. @JoshRosen can you take a quick look as well?

**Comment by HyukjinKwon** [comment]
@JoshRosen Could you take a look by any change please?

**Comment by JoshRosen** [comment]
LGTM as well, so I'm going to merge this to branch-1.6. Thanks @HyukjinKwon!

**Comment by JoshRosen** [comment]
(Now that this is merged, you'll have to close this PR manually since GitHub can't auto-close it).

**Comment by HyukjinKwon** [comment]
Sure! Thank you!

**Pull request closed without merging**
