### PR TITLE
[SPARK-24938][Core] Prevent Netty from using onheap memory for headers without regard for configuration

### PR DESCRIPTION
**Pull request by NiharS**
## What changes were proposed in this pull request?

In MessageEncoder.java, the header would always be allocated on onheap memory regardless of whether netty was configured to use/prefer onheap or offheap. By default this made netty allocate 16mb of onheap memory for a tiny header message. It would be more practical to use preallocated buffers.

Using a memory monitor tool on a simple spark application, the following services currently allocate 16 mb of onheap memory:
netty-rpc-client
netty-blockTransfer-client
netty-external-shuffle-client

With this change, the memory monitor tool reports all three of these services as using 0 b of onheap memory. The offheap memory allocation does not increase, but more of the already-allocated space is used.

## How was this patch tested?

Manually tested change using spark-memory-tool https://github.com/squito/spark-memory

### CODE REVIEW

**Comment by vanzin** [comment]
ok to test

**Comment by vanzin** [comment]
Did you get a chance to measure whether this has any negative effect of performance? Since it's using a buffer pool I wouldn't expect any, but you never know...

**Comment by NiharS** [comment]
Tried with a significantly larger input, both with and without the change. They ran in just about the same time.

**Comment by vanzin** [comment]
ok to test

**Comment by vanzin** [comment]
The tests are failing because they're now using too much direct memory:

```
18/08/17 09:57:35.396 rpc-server-4647-3 WARN TransportChannelHandler: Exception in connection from /192.168.10.22:36322
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 2852126720, max: 2863661056)
```

That's the first test in jenkins; the others seem to fail because of improper cleanup in that first test. But it seems that either we can't just use direct buffers here, or maybe the test might need some tweaking.

**Comment by vanzin** [comment]
retest this please

**Comment by srowen** [comment]
@attilapiros I think you made and then backed out this change in your https://github.com/apache/spark/pull/23540 pull request. Is it something we should merge now after your change, or did you find we shouldn't make this change?

**Comment by attilapiros** [comment]
@srowen we should merge this one too. #23540 was started to fix the OOM experienced right here (which was not reproducible locally). So there I just checked whether fixing those leaks are really enough for solving the OOM coming with this change (but I did not want to take away Nihar's change, just helping with the OOM).

**Review by attilapiros — APPROVED** [review]
LGTM

**Comment by NiharS** [comment]
@attilapiros Thanks for your work on #23540 and for pinging me of the fix! This PR was an old change and I appreciate you thinking of it.

I believe that #23540 completely fixes the bug seen in the Jenkins tests here. Back when this was failing, I was able to reproduce the error with a 50% success rate by running BroadcastSuite and DistributedSuite back-to-back, on my local machine. I pulled @attilapiros's change and reran the suites on loop, and there were no failures.

**Review by srowen — APPROVED** [review]
OK, the logic here sounds good and @vanzin 's test seem to show it is an improvement.

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
