### PR TITLE
[SPARK-14298] [ML] [MLlib] LDA should support disable checkpoint

### PR DESCRIPTION
**Pull request by yanboliang**
## What changes were proposed in this pull request?

In the doc of [`checkpointInterval`](https://github.com/apache/spark/blob/master/mllib/src/main/scala/org/apache/spark/ml/param/shared/sharedParams.scala#L241), we told users that they can disable checkpoint by setting `checkpointInterval = -1`. But we did not handle this situation for LDA actually, we should fix this bug.
## How was this patch tested?

Existing tests.

cc @jkbradley

### CODE REVIEW

**Comment by jkbradley** [comment]
Thanks for catching this.  I'd prefer we make the change in PeriodicCheckpointer.  That way, LDA with EM will still call PeriodicCheckpointer, which can handle persistence even if checkpointing is turned off.

**Comment by yanboliang** [comment]
@jkbradley Agree, I will update the PR soon.

**Comment by yanboliang** [comment]
Jenkins, test this please.

**Comment by yanboliang** [comment]
Jenkins, test this please.

**Comment by yanboliang** [comment]
@jkbradley It's ready for review now.

**Comment by jkbradley** [comment]
Thanks for updating it!
LGTM
Merging with master

Since this was a bug from before, let's add a unit test.  It should be easy to write a unit test now that we keep the last checkpoint by default.  However, that test will be hard to backport to earlier Spark versions. Let's do this:
* I'll merge this now with master.
* Can you please send a follow-up PR with a unit test?
* After merging the unit test, I'll backport this PR to previous Spark versions.

**Comment by yanboliang** [comment]
@jkbradley Sent #12286 for unit test, please help to review. Thanks!

**Comment by jkbradley** [comment]
Backported to 1.6 and 1.5 as well now

**Comment by jkbradley** [comment]
Weird the merge_spark_pr script merged the wrong PR.  Reverting...

**Pull request closed without merging**
