### PR TITLE
[SPARK-40468][SQL] Fix column pruning in CSV when _corrupt_record is selected

### PR DESCRIPTION
**Pull request by sadikovi**
### What changes were proposed in this pull request?

The PR fixes an issue when depending on the name of the `_corrupt_record` field, column pruning would behave differently for a record that has no parsing errors.

For example, with a CSV file like this (c1 and c2 columns):
```
1,a
```

Before the patch, the following query would return:
```scala
val df = spark.read
  .schema("c1 int, c2 string, x string, _corrupt_record string")
  .csv("file:/tmp/file.csv")
  .withColumn("x", lit("A"))

Result:

+---+---+---+---------------+
|c1 |c2 |x  |_corrupt_record|
+---+---+---+---------------+
|1  |a  |A  |1,a            |
+---+---+---+---------------+
```

However, if you rename the corrupt record column, the result is different (the original, arguably correct, behaviour before https://github.com/apache/spark/commit/959694271e30879c944d7fd5de2740571012460a):

```scala
val df = spark.read 
  .option("columnNameCorruptRecord", "corrupt_record")
  .schema("c1 int, c2 string, x string, corrupt_record string") 
  .csv("file:/tmp/file.csv") .withColumn("x", lit("A")) 

+---+---+---+--------------+
|c1 |c2 |x  |corrupt_record|
+---+---+---+--------------+
|1  |a  |A  |null          |
+---+---+---+--------------+
```

This patch fixes the former so both results would return `null` for corrupt record as there are no parsing issues. Note that https://issues.apache.org/jira/browse/SPARK-38523 is still fixed and works correctly.

### Why are the changes needed?

Fixes a bug where corrupt record would be non-null even though the record has no parsing errors.

### Does this PR introduce _any_ user-facing change?

Yes, fixes the output of corrupt record with additional columns provided by user. Everything should be unchanged outside of that scenario.

### How was this patch tested?

I added a unit test that reproduces the issue.

### CODE REVIEW

**Comment by sadikovi** [comment]
@MaxGekk Could you review this PR? Thanks.
I confirmed that there are no regressions for [SPARK-38523](https://issues.apache.org/jira/browse/SPARK-38523) that you fixed.

**Comment by MaxGekk** [comment]
@sadikovi Thanks for the ping. I will look at it soon.

**Review by MaxGekk — APPROVED** [review]

**Comment by MaxGekk** [comment]
+1, LGTM. Merging to master/3.3.
Thank you, @sadikovi.

**Comment by MaxGekk** [comment]
@sadikovi Could you backport this to branch-3.2, please (you pointed out it in JIRA as an affected version). Thank you.

**Comment by sadikovi** [comment]
Thank you 👍.

**Pull request closed without merging**
