### PR TITLE
[SPARK-39318][SQL] Remove tpch-plan-stability WithStats golden files

### PR DESCRIPTION
**Pull request by ulysses-you**
### What changes were proposed in this pull request?

Remove all TPCH with stats golden files.

### Why are the changes needed?

It's a dead golden files since we have no stats with TPCH and no check for that.

### Does this PR introduce _any_ user-facing change?

no, it's for test

### How was this patch tested?

Pass CI

### CODE REVIEW

**Comment by ulysses-you** [comment]
cc @cloud-fan @AngersZhuuuu

**Comment by LuciferYang** [comment]
Do you know when they became dead?

**Comment by ulysses-you** [comment]
@LuciferYang it is dead since it was added

**Comment by LuciferYang** [comment]
amazing ...

**Comment by AngersZhuuuu** [comment]
It was generated by `SPARK_GENERATE_GOLDEN_FILES=1 SPARK_ANSI_SQL_MODE=true build/sbt "sql/testOnly *TPCHPlanStabilitySuite"`

**Comment by AngersZhuuuu** [comment]
Seems caused by I generate these file with both with/without stats, but finally we decide to remove test about `withState` but forgot to  remove the file generated by `withState`.

**Review by AngersZhuuuu — APPROVED** [review]
LGTM

**Comment by AngersZhuuuu** [comment]
@cloud-fan I think we should remove this.

**Review by LuciferYang — APPROVED** [review]
LGTM +1

**Comment by cloud-fan** [comment]
sorry I missed this PR. @ulysses-you can you do a rebase?

**Comment by ulysses-you** [comment]
@cloud-fan rebased

**Comment by AngersZhuuuu** [comment]
ping @cloud-fan @HyukjinKwon

**Review by cloud-fan — APPROVED** [review]

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Pull request closed without merging**
