### PR TITLE
[MINOR][R][DOC] Fix R documentation generation instruction.

### PR DESCRIPTION
**Pull request by vectorijk**
## What changes were proposed in this pull request?

changes in R/README.md
- Make step of generating SparkR document more clear.
- link R/DOCUMENTATION.md from R/README.md
- turn on some code syntax highlight in R/README.md
## How was this patch tested?

local test

### CODE REVIEW

**Comment by vectorijk** [comment]
cc @jkbradley @shivaram @felixcheung 
result you could see [here](https://github.com/vectorijk/spark/tree/R-Readme/R)

**Comment by shivaram** [comment]
LGTM. Thanks @vectorijk

**Comment by felixcheung** [comment]
LGTM

**Comment by shivaram** [comment]
Merging this to master and branch-2.0

**Comment by vectorijk** [comment]
Thanks

**Pull request closed without merging**
