### PR TITLE
[SPARK-29182][Core][Followup] Cache preferred locations of checkpointed RDD

### PR DESCRIPTION
**Pull request by viirya**
### What changes were proposed in this pull request?

This is a followup to #25856. This fixes the document about the config value of spark.rdd.checkpoint.cachePreferredLocsExpireTime.

### Why are the changes needed?

The document is not correct. spark.rdd.checkpoint.cachePreferredLocsExpireTime can not be 0.

### Does this PR introduce any user-facing change?

No

### How was this patch tested?

This is document only change.

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
cc @gatorsmile

**Comment by viirya** [comment]
retest this please

**Comment by dongjoon-hyun** [comment]
Merged to master. Thank you, @viirya .

**Comment by viirya** [comment]
Thanks @gatorsmile @dongjoon-hyun

**Pull request closed without merging**
