### PR TITLE
[SPARK-36614][CORE][UI] Correct executor loss reason caused by decommission in UI

### PR DESCRIPTION
**Pull request by Ngone51**
### What changes were proposed in this pull request?

Post the correct executor loss reason to UI.

### Why are the changes needed?

To show the accurate loss reason.

### Does this PR introduce _any_ user-facing change?

Yes. Users can see the difference from the UI.

Before:
WeChataad8d1f27d9f9aa7cf93ced4bcc820e2
WeChat13c9f1345a096ff83d193e4e9853b165

After:

WeChata4313fa2dbf27bf2dbfaef5c1d4a19cf
WeChat5559d52fd3070ae6c42fe32d56f9dc94

### How was this patch tested?

Manully tested.

### CODE REVIEW

**Comment by Ngone51** [comment]
cc @dongjoon-hyun @cloud-fan Please take a look, thanks!

**Review by gengliangwang — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by cloud-fan** [comment]
late LGTM

**Comment by Ngone51** [comment]
Thanks all!

**Pull request closed without merging**
