### PR TITLE
[SPARK-48989][SQL][FOLLOWUP] Fix SubstringIndex codegen

### PR DESCRIPTION
**Pull request by uros-db**
### What changes were proposed in this pull request?
Fix genCode for `SubstringIndex`.

### Why are the changes needed?
GenCode was not fully correct in the original PR.

### Does this PR introduce _any_ user-facing change?
Yes, genCode now works properly for all collations.

### How was this patch tested?
Additional tests for other collations.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by uros-db** [comment]
Following up on https://github.com/apache/spark/pull/47481, adding @miland-db and @cloud-fan to review

To recap:
- SubstringIndex always treats `count` as an `int`, rather than a string
- collationId is always an `int`, and never a string

So this should be the proper way to implement it in CollationSupport

**Comment by cloud-fan** [comment]
shall we add a test?

**Comment by uros-db** [comment]
yes, will add tests & description

**Review by uros-db — COMMENTED** [review]
added some tests, ready for review now

**Review by cloud-fan — APPROVED** [review]

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Pull request closed without merging**
