### PR TITLE
[SPARK-10766][SPARK-SUBMIT]Add some configuration for the client process in cluster mode.

### PR DESCRIPTION
**Pull request by SaintBacchus**
Add this four configurations for the client only in cluster mode:
-  `spark.client.memory` of property and `--client-memory` of cli command
- `spark.client.extraClassPath` of property and `--client-class-path` of cli command
- `spark.client.extraJavaOptions` of property and `--client-java-options` of cli command
- `spark.client.extraLibraryPath` of property and `--client-library-path` of cli command

### CODE REVIEW

**Comment by SaintBacchus** [comment]
retest this please

**Comment by andrewor14** [comment]
What's the use case for this? If possible I'd rather not introduce new public facing configurations. Also it might be confusing to the new Spark user if we have both driver memory and client memory.

**Comment by SaintBacchus** [comment]
@andrewor14 as I described in [JIRA](https://issues.apache.org/jira/browse/SPARK-10766), in yarn-cluster mode, it's hard to set the class path of the client process. But if I want use the hbase, I had to set the hbase jars into the class path of this process.
BTW, I think spark user may want to do some thing in the this process, so I think it's better to enhance the configuration of client.

**Comment by andrewor14** [comment]
I still don't see why it's necessary to change the class path of the client. If you're using Spark with HBase you should change the driver / executor classpaths, not the client one. Even if you do want to do that, you can workaround this by setting environment variables. I would recommend that we close this issue because it introduces new configs that most people will not use.

**Comment by SaintBacchus** [comment]
OK, I close.

**Pull request closed without merging**
