### PR TITLE
[SPARK-1301][WebUI]Add UI elements to collapse "Aggregated Metrics by Executor" pane on stage page

### PR DESCRIPTION
**Pull request by shankervalipireddy**

### CODE REVIEW

**Comment by shankervalipireddy** [comment]
Sorry. I am first time user and i dont know how to do pull request.

Please ignore/delete this request. its created by mistake.

On Fri, Mar 13, 2015 at 3:27 PM, UCB AMPLab <notifications@github.com>
wrote:

> Can one of the admins verify this patch?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apache/spark/pull/5021#issuecomment-79485817>.
>



-- 
Thanks & Regards,
Shanker

**Comment by srowen** [comment]
@shankervalipireddy just close this pull request, no problem. We can't close it for you.

**Comment by shankervalipireddy** [comment]
I have just closed it. sorry for wasting your time. I am just trying to learn saprk and wanna become spark committer soon.

**Comment by shankervalipireddy** [comment]
Hey,

I just signed the petition "Tik Tok: Ban Tik Tok" and wanted to see if you
could help by adding your name.

Our goal is to reach 1,500 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/sNQ8kHxTFz

Thanks!
Shanker

**Pull request closed without merging**
