### PR TITLE
[SPARK-14789][SQL] Move FunctionResourceLoader into SessionState

### PR DESCRIPTION
**Pull request by andrewor14**
## What changes were proposed in this pull request?

Just a small refactor. It really doesn't belong to `SQLContext`.
## How was this patch tested?

Jenkins.

### CODE REVIEW

**Comment by andrewor14** [comment]
@yhuai

**Comment by rxin** [comment]
Oh I just did this locally too for something else. LGTM.

**Comment by yhuai** [comment]
Thanks! LGTM

**Comment by rxin** [comment]
Actually I merged my other PR which includes this. Can you close this now? Thanks.

**Pull request closed without merging**
