### PR TITLE
[SPARK-19053][ML]Supporting multiple evaluation metrics in DataFrame-based API

### PR DESCRIPTION
**Pull request by hhbyyh**
## What changes were proposed in this pull request?

As an initial step, the PR creates BinaryClassificationMetrics, MultiClassClassificationMetrics, RegressionMetrics in ML. The long term target is to reach function parity with MLlib Metrics and be able to provide more enhancements for DataFrame-based API.

This PR allows the Binary/MultilclassClassification/Regression Evaluator to get a corresponding metrics instance, and users can use the metrics instance to access multiple evaluation Metrics after a single pass, while originally Evaluator only allows access for single metric.  
```
val evaluator = new MulticlassClassificationEvaluator()
val metrics = evaluator.getMetrics(df)
metrics.accuracy
metrics.weightedFMeasure
metrics.weightedPrecision
metrics.weightedRecall
```

To make the review easier, the current PR only includes metrics in the Evaluator to reach function parity. Plan for further development:
1. Initial API and function parity with ML Evaluators. (This PR)
2. Python API.
2. Function parity with MLlib Metrics.
3. Add requested enhancements like including weight, add per-row metrics, add ranking metrics.
4. Reorganize classification Metrics hierarchy, so Binary Classification Metrics can support metrics in MultiClassMetrics (accuracy, recall etc.).
5.  Possibly to be used in training summary.

The current implementation is still based on MLlib Metrics, which is kept completely internal and can be changed to DataFrame-based calculation when necessary.

## How was this patch tested?

new unit tests added.

### CODE REVIEW

**Comment by hhbyyh** [comment]
Please advice if this is a good feature to add. If not I'll close it. Thanks.

**Comment by zhengruifeng** [comment]
LGTM, except for the since annotations.

**Comment by felixcheung** [comment]
this shouldn't say version 2.3.0?

**Comment by hhbyyh** [comment]
Thanks for the comments @zhengruifeng @felixcheung 

It's been nearly 8 months and it took me a while to recall what this PR does. While the PR did provide some improvement for the current API, I wonder if it lays a good foundation for an extensible and flexible `Evaluator` framework for Spark ML.

The current design is not quite user-friendly as it asks users to understand the concept of `Metrics` (BinaryClassificationMetrics, MultiClassClassificationMetrics, RegressionMetrics) which are primarily for internal calculation, and it implies that all the indicators in a `Metrics` can be calculated in one pass of the DataFrame, which creates some difficulty when we add extra indicators in the Metric which cannot be calculated with other indicators.

IMO, API wise, ideally we should allow users to specify any combination of the metrics that they want to add to the `Evaluator`, then the `Evaluator` needs to figure out the best way to efficiently calculate the metrics. Following are the concrete suggestions:

1. Evaluator API:
```
ClassificationEvaluator {

  def setPredictionCol(value: String): this.type

  def setLabelCol(value: String): this.type
  
  // kept for back-ward compatibility and Cross validation
  def setMetricName(value: String): this.type
  
  // kept for back-ward compatibility and Cross validation
  override def evaluate(dataset: Dataset[_]): Double
  
  // calculate multiple metrics, will try to optimize calculation internally
  override def getMetrics(dataset: Dataset[_], metrics: Array[String]): Map[String, Any] // or wrap it with customized class

}

val ce = new ClassificationEvaluator().setLabelCol("x").setPredictionCol("y")
metrics = ce.getMetrics(dataframe, Array(Classification.truePositiveRateByLabel, BinaryClassification.areaUnderROC))
println(metrics)
```
We can basically merge BinaryClassificationEvaluator and MultiClassificationEvaluator.

Similarly we can have `RegressionEvaluator` and `ClusteringEvaluator`, separating those because we may need to provide different setters in each. 

2. Summy classes may invoke Evaluator internally.

@felixcheung , I'm not sure if this can get a shepherd and review bandwidth for the next release. I don't want to just update version numbers every a few months.

**Comment by holdenk** [comment]
Is this still being actively worked on?

**Comment by hhbyyh** [comment]
Closing it. Thanks.

**Pull request closed without merging**
