### PR TITLE
[SPARK-13529][BUILD] Move network/* modules into common/network-*

### PR DESCRIPTION
**Pull request by rxin**
## What changes were proposed in this pull request?

As the title says, this moves the three modules currently in network/ into common/network-*. This removes one top level, non-user-facing folder.
## How was this patch tested?

Compilation and existing tests. We should run both SBT and Maven.

### CODE REVIEW

**Comment by rxin** [comment]
cc @srowen

**Comment by srowen** [comment]
I like the idea of bringing some additional organization here. The difference between `common/` and `core/` is not clear. There are several modules that are separable from Spark itself, mostly. Is that the idea, and could `unsafe` potentially go here?

**Comment by rxin** [comment]
Yea those are good to move too.

**Comment by rxin** [comment]
Basically I just want to find a place to put all the non-user-facing top modules.

**Comment by srowen** [comment]
Same for `tags` ? not even sure what it is.

Related, but separate: the two docker modules really should be in `external`, and the difference between `extras` and `external` is lost on me.

And related but even more separate, every project eventually accumulates the following directories which are substantially redundant: `bin`, `build`, `conf`, `dev`, `project`, `sbin`. The top level is littered with files which, along with these, should probably be reorganized into something more rational. Usually it's `etc/...`

**Comment by rxin** [comment]
OK I'm going to merge this one. 

@srowen do you want to just come up with a list of other dirs to move?

**Pull request closed without merging**
