### PR TITLE
[SPARK-34843][SQL][FOLLOWUP] Fix a test failure in OracleIntegrationSuite

### PR DESCRIPTION
**Pull request by sarutak**
### What changes were proposed in this pull request?

This PR fixes a test failure in `OracleIntegrationSuite`. 
After SPARK-34843 (#31965), the way to divide partitions is changed and `OracleIntegrationSuites` is affected.
```
[info] - SPARK-22814 support date/timestamp types in partitionColumn *** FAILED *** (230 milliseconds)
[info]   Set(""D" < '2018-07-11' or "D" is null", ""D" >= '2018-07-11' AND "D" < '2018-07-15'", ""D" >= '2018-07-15'") did not equal Set(""D" < '2018-07-10' or "D" is null", ""D" >= '2018-07-10' AND "D" < '2018-07-14'", ""D" >= '2018-07-14'") (OracleIntegrationSuite.scala:448)
[info]   Analysis:
[info]   Set(missingInLeft: ["D" < '2018-07-10' or "D" is null, "D" >= '2018-07-10' AND "D" < '2018-07-14', "D" >= '2018-07-14'], missingInRight: ["D" < '2018-07-11' or "D" is null, "D" >= '2018-07-11' AND "D" < '2018-07-15', "D" >= '2018-07-15'])
```

### Why are the changes needed?

To follow the previous change.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

The modified test.

### CODE REVIEW

**Comment by sarutak** [comment]
I ran other integration tests but only `OracleIntegrationSuites` seems to be affected for now.

**Review by HyukjinKwon — APPROVED** [review]
Looks good cc @maropu FYI

**Comment by dongjoon-hyun** [comment]
cc @hanover-fiste and @srowen , too.

**Review by dongjoon-hyun — APPROVED** [review]
+1, @sarutak and @HyukjinKwon  . Thank you for checking and fixing this.
Merged to master.

**Pull request closed without merging**
