### PR TITLE
[SPARK-3854][BUILD] Scala style: require spaces before `{`.

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
## What changes were proposed in this pull request?

Since the opening curly brace, '{', has many usages as discussed in [SPARK-3854](https://issues.apache.org/jira/browse/SPARK-3854), this PR adds a ScalaStyle rule to prevent '){' pattern  for the following majority pattern and fixes the code accordingly. If we enforce this in ScalaStyle from now, it will improve the Scala code quality and reduce review time.

```
// Correct:
if (true) {
  println("Wow!")
}

// Incorrect:
if (true){
   println("Wow!")
}
```

IntelliJ also shows new warnings based on this.
## How was this patch tested?

Pass the Jenkins ScalaStyle test.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Hi, @JoshRosen .
Could you review this issue? I can add more patterns if you want.
I think this PR has its meaning on automated prevention by ScalaStyle.

**Comment by rxin** [comment]
LGTM - this is a good fix.

**Comment by dongjoon-hyun** [comment]
Thank you, @rxin !

**Comment by andrewor14** [comment]
LGTM!

**Comment by andrewor14** [comment]
retest this please

**Comment by dongjoon-hyun** [comment]
@andrewor14  Thank you for your review.

**Comment by andrewor14** [comment]
Merged into master

**Comment by andrewor14** [comment]
what is your JIRA name?

**Comment by dongjoon-hyun** [comment]
Thank you, @andrewor14 !
My JIRA account is `dongjoon`.

**Comment by HyukjinKwon** [comment]
Oh, I have been thinking a space between them is correct. Thanks!

**Comment by dongjoon-hyun** [comment]
Thank you, @HyukjinKwon ! :)

**Pull request closed without merging**
