### PR TITLE
[SPARK-22430][R][Docs] Unknown tag warnings when building R docs with Roxygen 6.0.1

### PR DESCRIPTION
**Pull request by rekhajoshm**
## What changes were proposed in this pull request?
Removed @export tag to get rid of unknown tag warnings

## How was this patch tested?
Existing tests

### CODE REVIEW

**Comment by felixcheung** [comment]
I'm/We're aware of this and to keep diff small and manageable for backporting fixes, it is preferable to avoid broad changes like this.

We can revisit when new releases are stable down, perhaps.

**Comment by srowen** [comment]
I see this too and Roxygen 6.0.1 seems common now. Is there any value to the tags? I don't think these removals can cause much merge conflict. It can go in master right?

**Comment by felixcheung** [comment]
It was not used in the current way we have the export and a change in 6.x started warning about this.

Jenkins is not running Roxygen 6 though. There are pending tasks to upgrade. IMO it's better to update our toolset and validate the doc output is correct officially and then remove these tags for the warnings. The warnings are harmless.

Historically a lot of changes get backported around a new releases (or RCs of releases) and it was a pain to hand merge every single commit.

**Comment by rekhajoshm** [comment]
Ack. thanks for the update @felixcheung @srowen Closing this.

**Comment by felixcheung** [comment]
@rekhajoshm feel free to follow up after we are through with 2.3.0, thanks!

**Comment by srowen** [comment]
@rekhajoshm @felixcheung since 2.3.0 was just finished, OK to merge?

**Comment by felixcheung** [comment]
can you reopen this PR and add [R] in the title?

**Comment by felixcheung** [comment]
ping @rekhajoshm ?

**Comment by rekhajoshm** [comment]
done @felixcheung thanks

**Review by srowen — APPROVED** [review]

**Comment by felixcheung** [comment]
merged to master

**Pull request closed without merging**
