### PR TITLE
[DOC][TYPO] Fix typo in standalone deploy scripts description

### PR DESCRIPTION
**Pull request by yjshen**

### CODE REVIEW

**Comment by srowen** [comment]
Sure, good catch.

**Comment by rxin** [comment]
Thanks. I've merged this.

**Comment by rxin** [comment]
Actually it was already merged -- but github sync was behind.

**Comment by rxin** [comment]
Since this has been merged, @yijieshen can you close the pull request? I'm not sure why it is not closed automatically by github.

**Pull request closed without merging**
