### PR TITLE
Add root degree to PolynomialExpansion

### PR DESCRIPTION
**Pull request by Catadanna**
To PolynomialExpansion I added expansion for root degrees.

I created a pull request for the same problem in the file PolynomialExpansionGeneralized, I shall close it to avoid confusions. 

For example, for root degree 3, and basis vector (x,y) we have : (x, x^(1/2), x^(1/3), y, y^(1/2), y^(1/3)
We can merge simple polynomial expansion with root polynomial expansion: for simple degree 2 and root degree 2:
x, y, xy, x^2, y^2, x^(1/2), y^(1/2)

I used java.lang.Math.pow, and there is a case in it :
If the first argument is finite and less than zero and if the second argument is finite and not an integer,then the result is NaN
For this case I raised a IllegalArgumentException; the user should normalize the features in order to have only positive features.

The case of root degree polynomial expansion is mentioned in the Stanford Machine Learning course on Coursera.
It helped myself to minimize error when performing Linear Regression.

## What changes were proposed in this pull request?

To PolynomialExpansion I added expansion for root degrees.

## How was this patch tested?
I did manual test on different numeric data (Integer, Double, positive, negative, zero, very large numbers, very small numbers). I tested also that the value x^1 appears once and only once in the features, whatever the setting is (setDegree only, setDegreeRoot only, both setDegree and setDegreeRoot).

Please review https://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Comment by Catadanna** [comment]
PolynomialExpansion with root degrees

**Comment by srowen** [comment]
I think the main purpose of the polynomial expansion support is to generate interaction terms like "x * y". This only generates fractional powers of an input. I doubt that anything but square root would be useful in almost all cases? so I doubt this is worth adding to the API.

**Comment by Tagar** [comment]
We use `sqrt` for engineered features quite often, for some of the variables with a larger scale
of values. Haven't seen our DS folks use anything else by 0.5 (sqrt) for the `pow` .. it doesn't mean 
somebody else doesn't have use cases for this. Thanks!

**Comment by Catadanna** [comment]
I used 3rd degree root for a polynomial curve, for temporal linear regression. The 3rd degree root allowed to obtain  particular shape for several exceptional elements. Now, one may say that such a curve favorises high variance, yet it described well those elements as well as the others, and helped minimizing the error for the test set and future data.

**Comment by srowen** [comment]
Sure, but none of that seems to call for a general function to generate the nth roots of an input. It seems harder in the common case that you want just the square or cube root. I would not add this.

**Pull request closed without merging**
