### PR TITLE
[SPARK-31983] Fix Sorting for duration column and make Status column sortable

### PR DESCRIPTION
**Pull request by iRakson**
### What changes were proposed in this pull request?
In #28485 pagination support for tables of Structured Streaming Tab was added. 
It missed 2 things:
* For sorting duration column, `String` was used which sometimes gives wrong results(consider `"3 ms"` and `"12 ms"`). Now we first sort the duration column and then convert it to readable String
* Status column was not made sortable. 

### Why are the changes needed?
To fix the wrong result for sorting and making Status column sortable.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
After changes:
Screenshot 2020-06-08 at 2 18 48 PM

### CODE REVIEW

**Comment by iRakson** [comment]
cc @sarutak @srowen Kindly take a look.

**Review by srowen — COMMENTED** [review]
Looks good. Are there other similar cases, I wonder?

**Comment by iRakson** [comment]
> Looks good. Are there other similar cases, I wonder?

I will look into other places as well.

**Comment by sarutak** [comment]
Looks good. Pending for other similar cases.

**Comment by iRakson** [comment]
I checked. I cannot find any similar case for other tables.

**Comment by HyukjinKwon** [comment]
@gengliangwang FYI

**Comment by srowen** [comment]
LGTM. Do you all have an opinion on back porting to branch-3.0? I think I would.

**Comment by sarutak** [comment]
> LGTM. Do you all have an opinion on back porting to branch-3.0? I think I would. 
Yeah, it would be better. What do you think @iRakson ?

**Comment by iRakson** [comment]
> LGTM. Do you all have an opinion on back porting to branch-3.0? I think I would.
> Yeah, it would be better. What do you think @iRakson ?

Just to be clear, We are talking about back porting pagination support or fixing this sorting issue ?

If we are only fixing this sorting issue then implementation will be slightly different as we are using `listingTable` for generating table.

**Comment by sarutak** [comment]
Pagination feature is not in `branch-3.0` so how about focusing the sorting issue?

**Comment by iRakson** [comment]
Ok. I will raise a PR for that. Just one doubt, for fixing in 3.0 should I file a new JIRA(as implementation will be slightly different) or just raise as a follow up for this only.

**Comment by srowen** [comment]
We will merge this just to master. If you can cleanly fix in 3.0 too, yes that's fine in a new PR. It should be the same JIRA.

**Comment by iRakson** [comment]
> We will merge this just to master. If you can cleanly fix in 3.0 too, yes that's fine in a new PR. It should be the same JIRA.

Oh. I created a new JIRA. [SPARK-31642](https://issues.apache.org/jira/browse/SPARK-31642) is for introducing pagination support in structured streaming tab, so I filed another JIRA(https://issues.apache.org/jira/browse/SPARK-31983). 

I raised a [PR](https://github.com/apache/spark/pull/28823) here.

**Comment by srowen** [comment]
Merged to master. I'll look at the backport.

**Comment by srowen** [comment]
Oh I see, this was attached to the JIRA for pagination. It does make sense to have a separate JIRA for _that_. Let me retroactively fix up the links.

**Comment by iRakson** [comment]
Thank You. @srowen @sarutak.

**Pull request closed without merging**
