### PR TITLE
[SPARK-23787][tests] Fix file download test in SparkSubmitSuite for Hadoop 2.9.

### PR DESCRIPTION
**Pull request by vanzin**
This particular test assumed that Hadoop libraries did not support
http as a file system. Hadoop 2.9 does, so the test failed. The test
now forces a non-existent implementation for the http fs, which
forces the expected error.

There were also a couple of other issues in the same test: SparkSubmit
arguments in the wrong order, and the wrong check later when asserting,
which was being masked by the previous issues.

### CODE REVIEW

**Comment by vanzin** [comment]
@jerryshao

**Review by felixcheung — APPROVED** [review]

**Comment by jiangxb1987** [comment]
LGTM

**Review by jerryshao — APPROVED** [review]
LGTM. Thanks for the fix.

**Comment by jerryshao** [comment]
Merging to master branch.

**Pull request closed without merging**
