### PR TITLE
[SPARK-21886][SQL] Use SparkSession.internalCreateDataFrame to create…

### PR DESCRIPTION
**Pull request by jaceklaskowski**
… Dataset with LogicalRDD logical operator

## What changes were proposed in this pull request?

Reusing `SparkSession.internalCreateDataFrame` wherever possible (to cut dups)

## How was this patch tested?

Local build and waiting for Jenkins

### CODE REVIEW

**Review by gatorsmile — APPROVED** [review]

**Comment by gatorsmile** [comment]
LGTM

**Comment by gatorsmile** [comment]
Thanks! Merging to master.

**Comment by jaceklaskowski** [comment]
That was really quick! Thanks a lot @gatorsmile

**Comment by gatorsmile** [comment]
@jaceklaskowski Maybe you can fix the PR title next time. Thanks for your work!

**Pull request closed without merging**
