### PR TITLE
[SPARK-11796] [test-maven] [WIP] Fixing httpclient and httpcore depedency issues related to docker-client

### PR DESCRIPTION
**Pull request by markgrover**
I was able to get past this error:

```
*** RUN ABORTED ***
  java.lang.NoSuchMethodError: org.apache.http.impl.client.HttpClientBuilder.setConnectionManagerShared(Z)Lorg/apache/http/impl/client/HttpClientBuilder;
  at org.glassfish.jersey.apache.connector.ApacheConnector.<init>(ApacheConnector.java:240)
  at org.glassfish.jersey.apache.connector.ApacheConnectorProvider.getConnector(ApacheConnectorProvider.java:115)
  at org.glassfish.jersey.client.ClientConfig$State.initRuntime(ClientConfig.java:418)
  at org.glassfish.jersey.client.ClientConfig$State.access$000(ClientConfig.java:88)
  at org.glassfish.jersey.client.ClientConfig$State$3.get(ClientConfig.java:120)
  at org.glassfish.jersey.client.ClientConfig$State$3.get(ClientConfig.java:117)
  at org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:340)
  at org.glassfish.jersey.client.ClientConfig.getRuntime(ClientConfig.java:726)
  at org.glassfish.jersey.client.ClientRequest.getConfiguration(ClientRequest.java:285)
  at org.glassfish.jersey.client.JerseyInvocation.validateHttpMethodAndEntity(JerseyInvocation.java:126)
  ...
```

However, then I ran into some class not found errors like these:

```
*** RUN ABORTED ***
  java.lang.NoClassDefFoundError: org/apache/http/ssl/SSLContexts
  at org.apache.http.conn.ssl.SSLConnectionSocketFactory.getSocketFactory(SSLConnectionSocketFactory.java:172)
  at com.spotify.docker.client.DefaultDockerClient.getSchemeRegistry(DefaultDockerClient.java:254)
  at com.spotify.docker.client.DefaultDockerClient.getConnectionManager(DefaultDockerClient.java:242)
  at com.spotify.docker.client.DefaultDockerClient.<init>(DefaultDockerClient.java:205)
  at com.spotify.docker.client.DefaultDockerClient$Builder.build(DefaultDockerClient.java:1370)
  at org.apache.spark.sql.jdbc.DockerJDBCIntegrationSuite.beforeAll(DockerJDBCIntegrationSuite.scala:73)
  at org.scalatest.BeforeAndAfterAll$class.beforeAll(BeforeAndAfterAll.scala:187)
  at org.apache.spark.sql.jdbc.DockerJDBCIntegrationSuite.beforeAll(DockerJDBCIntegrationSuite.scala:58)
  at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:253)
  at org.apache.spark.sql.jdbc.DockerJDBCIntegrationSuite.run(DockerJDBCIntegrationSuite.scala:58)
  ...
  Cause: java.lang.ClassNotFoundException: org.apache.http.ssl.SSLContexts
  at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
  at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
  at org.apache.http.conn.ssl.SSLConnectionSocketFactory.getSocketFactory(SSLConnectionSocketFactory.java:172)
  at com.spotify.docker.client.DefaultDockerClient.getSchemeRegistry(DefaultDockerClient.java:254)
  at com.spotify.docker.client.DefaultDockerClient.getConnectionManager(DefaultDockerClient.java:242)
```

Anyways, finally after trying a few more things and going through @JoshRosen 's previous discussion with docker-client folks, this patch is what I finally came up with.

It goes past all the ClassNotFound errors but on my mac, it gives 404 errors. So, I am trying to post the patch here, in case it doesn't pass on my local environment.

### CODE REVIEW

**Comment by markgrover** [comment]
Jenkins, test this please.

**Comment by markgrover** [comment]
Josh, it would be good test this after removing the disabling of the test in Jenkins. I am happy to try that out but I am not sure I have the right privileges on Jenkins. Feedback/thoughts welcome.

**Comment by JoshRosen** [comment]
@mark, put `[test-maven]` into your PR title and it'll run through the Maven PRB where that disabling is not in effect.

**Comment by JoshRosen** [comment]
Jenkins, this is ok to test.

**Comment by JoshRosen** [comment]
Jenkins, retest this please.

**Comment by markgrover** [comment]
Thanks Josh. So, I have a good news and bad news.

The good news is that the maven/dependency related issues have been resolved. The bad news is that the tests are still failing, albeit due to MySQL and PostgreSQL drivers not being accessible.

The error is pasted here for easier access:
````
MySQLIntegrationSuite:
Exception encountered when invoking run on a nested suite - The code passed to eventually never returned normally. Attempted 70 times over 1.0002781788666666 minutes. Last failure message: No suitable driver found for jdbc:mysql://192.168.10.28:52440/mysql?user=root&password=rootpass. *** ABORTED ***
  Exception encountered when invoking run on a nested suite - The code passed to eventually never returned normally. Attempted 70 times over 1.0002781788666666 minutes. Last failure message: No suitable driver found for jdbc:mysql://192.168.10.28:52440/mysql?user=root&password=rootpass. (DockerJDBCIntegrationSuite.scala:115)
PostgresIntegrationSuite:
Exception encountered when invoking run on a nested suite - The code passed to eventually never returned normally. Attempted 70 times over 1.00021882435 minutes. Last failure message: No suitable driver found for jdbc:postgresql://192.168.10.28:39460/postgres?user=postgres&password=rootpass. *** ABORTED ***
  Exception encountered when invoking run on a nested suite - The code passed to eventually never returned normally. Attempted 70 times over 1.00021882435 minutes. Last failure message: No suitable driver found for jdbc:postgresql://192.168.10.28:39460/postgres?user=postgres&password=rootpass. (DockerJDBCIntegrationSuite.scala:115)
Run completed in 2 minutes, 46 seconds.
Total number of tests run: 0
Suites: completed 1, aborted 2
Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
*** 2 SUITES ABORTED ***
````

**Comment by JoshRosen** [comment]
My hunch is that you'll have to declare an explicit dependency on those drivers, since I think that there's a difference between Maven and SBT handling of test-jars' transitive dependencies. See `sql/pom.xml` for the drivers; if the versions are just hardcoded there, you might want to lift them up to the root pom's dependencyManagement when also declaring the dep. in the docker subproject.

**Comment by markgrover** [comment]
OK, I will do that. I am afk for some time but will take care of this when
I am back. Thanks.

**Comment by srowen** [comment]
Should the client/core versions match up? and be declared as one global version?
I think using the latest of these is generally a Good Thing, but I know so many components rely on different old versions of the library. If it works, great. We probably still need to audit `mvn -Dverbose dependency:tree` to see what other versions still come in, and what components have had their version bumped, and sanity-check that.

**Comment by JoshRosen** [comment]
FWIW it would probably be easier to produce a new release of the Docker client which properly relocates  and shades dependencies; see my comments + discussion at https://github.com/spotify/docker-client/pull/272.

In the meantime, though, doing dependency hacks that are isolated to this Maven subproject seems fine to me.

**Comment by markgrover** [comment]
Thanks @JoshRosen For now, I have added the mysql and postgresql drivers as dependencies and the tests pass now. We just have to make sure that the CI environment has the docker engine and environment set up properly.

Medium term, I agree about new release of Docker client being the right solution.

**Comment by markgrover** [comment]
Jenkins, retest this please.

**Comment by markgrover** [comment]
The failure seems unrelated to my change, so I will ask Jenkins to retest. Also, I am not sure if I have the right permissions to trigger a new build and I'd appreciate if someone could add me to the whitelist.

**Comment by markgrover** [comment]
Jenkins, retest this please.

**Comment by srowen** [comment]
Jenkins add to whitelist

**Comment by markgrover** [comment]
Thanks, @srowen!

**Comment by JoshRosen** [comment]
LGTM. Thanks @markgrover!

**Comment by JoshRosen** [comment]
Tested locally and confirmed that these tests still run fine in SBT, so I'm going to merge this to master and branch-1.6.

**Comment by JoshRosen** [comment]
I'm going to update the PR title and description in the final commit so that they're no longer WIP / so verbose.

**Comment by markgrover** [comment]
Thanks so much, Josh!

**Comment by blbradley** [comment]
@srowen httpclient 4.5.* depends on versions of httpcore 4.4.*

**Pull request closed without merging**
