### PR TITLE
[SPARK-46692][BUILD] Load `inputs.envs` always in `Python` and `Upload`-related steps

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to fix potential environmental variable(eg: `PYTHON_TO_TEST`.) transfer issue in `pyspark job GA`

### Why are the changes needed?
https://github.com/apache/spark/actions/workflows/build_python.yml
Let's take a successful `build_ python` Using as an example, https://github.com/apache/spark/actions/runs/7476792796/job/20348090667

1.python 3.10
Obviously, it is meaningless to enumerate the packages of `Python 3.9` when building PySpark based on `Python 3.10`.
https://github.com/apache/spark/actions/runs/7476792796/job/20348079659
image

2.python 3.11
https://github.com/apache/spark/actions/runs/7476792796/job/20348091081
image

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by panbingkun** [comment]
cc @HyukjinKwon @dongjoon-hyun

**Comment by panbingkun** [comment]
For the sake of conservatism, we can fix this issue first, and then I will observe tomorrow's  Has the environment variable for each step in Python been effective? If it is, we will bring back xxx.

For greater stability, we can fix this issue first, and then I will observe whether the environment variables `PYTHON_TO_TEST` for each step of `build_python` tomorrow are effective. If they are effective, we will bring `https://github.com/apache/spark/pull/44662` back.

**Comment by panbingkun** [comment]
I found that in step `PySpark Run test`, it is used as follows:
https://github.com/panbingkun/spark/blob/efa891c4ea869a7fac58eabf187ac8aeff1fcd38/.github/workflows/build_and_test.yml#L446

**Review by zhengruifeng — APPROVED** [review]

**Comment by panbingkun** [comment]
After this PR is merged, I will observe whether the value of the environment variable 'PYTHON_TO_TEST' in steps `List Python packages (${{ env.PYTHON_TO_TEST }})`, `Upload test results to report` and `Upload unit tests log files` in `build_python` is normal at tomorrow morning.

**Review by dongjoon-hyun — COMMENTED** [review]
Ya, this looks like the root causes.
- Are these all instances?
- Given that the change affects not only `PYTHON_TO_TEST`, but also all environment variables, please revise the PR title.
    > Fix potential issues with environment variable transmission PYTHON_TO_TEST

**Comment by panbingkun** [comment]
> Ya, this looks like the root causes.
> 
> * Are these all instances?
> * Given that the change affects not only `PYTHON_TO_TEST`, but also all environment variables, please revise the PR title.
>   > Fix potential issues with environment variable transmission PYTHON_TO_TEST

@dongjoon-hyun
Yes, in ' pyspark job GA', I checked and found that currently only these 3 steps are affected by this issue.
After this PR is merged, I will continue to observe.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by panbingkun** [comment]
> +1, LGTM.

@dongjoon-hyun
Thank you very much for giving this PR a suitable title. 😄

If tomorrow's scheduled task meets expectations, I will provide a PR to bring `https://github.com/apache/spark/pull/44662` back.

**Comment by dongjoon-hyun** [comment]
Ya, +1 for the plan. Thank you.

**Comment by panbingkun** [comment]
@dongjoon-hyun 
Has the scheduling started yet? I have observed some errors in the `pypy3` environment, such as missing package: `grpc`. Is this expected?
https://github.com/apache/spark/actions/runs/7503864095/job/20429679584
image

**Comment by HyukjinKwon** [comment]
We should but I think that's not available. If grpc is not installed it should skip the tests properly.

**Comment by HyukjinKwon** [comment]
https://github.com/apache/spark/pull/44715

**Comment by panbingkun** [comment]
> We should but I think that's not available. If grpc is not installed it should skip the tests properly.

Okay, let's continue to observe.

**Comment by 09306677806** [comment]
0x161142F93e5Af29B51e7552AFbd84E1f563C8ee8

**Comment by panbingkun** [comment]
@HyukjinKwon 
I have observed the following errors in the environment `pypy3`. 
https://github.com/apache/spark/actions/runs/7519959346/job/20474204069
image

Do we need to install `pyarrow` in the environment? Or do we ignore some UT when we lack `pyarrow` again?

**Comment by HyukjinKwon** [comment]
pyarrow in PyPy isn't available up to my best knowledge.

**Comment by panbingkun** [comment]
> pyarrow in PyPy isn't available up to my best knowledge.

I tried to install 'pyarrow' in pypy3 over the weekend, but one UT failed.
https://github.com/panbingkun/spark/actions/runs/7519505235/job/20468699700
image

So should we ignore it?

**Comment by HyukjinKwon** [comment]
For them, let's skip it for now, and file a JIRA for each tests.

**Comment by panbingkun** [comment]
> For them, let's skip it for now, and file a JIRA for each tests.

Okay.

**Pull request closed without merging**
