### PR TITLE
[SPARK-20924] [SQL] Unable to call the function registered in the not-current database

### PR DESCRIPTION
**Pull request by gatorsmile**
### What changes were proposed in this pull request?
We are unable to call the function registered in the not-current database.
```Scala
sql("CREATE DATABASE dAtABaSe1")
sql(s"CREATE FUNCTION dAtABaSe1.test_avg AS '${classOf[GenericUDAFAverage].getName}'")
sql("SELECT dAtABaSe1.test_avg(1)")
```
The above code returns an error:
```
Undefined function: 'dAtABaSe1.test_avg'. This function is neither a registered temporary function nor a permanent function registered in the database 'default'.; line 1 pos 7
```

This PR is to fix the above issue.
### How was this patch tested?
Added test cases.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
+1, LGTM.

**Comment by gatorsmile** [comment]
cc @cloud-fan 

Thanks! @dongjoon-hyun

**Comment by cloud-fan** [comment]
LGTM, merging to master/2.2!

**Comment by rajeshcode** [comment]
@gatorsmile 
We can't backport this into spark2.1.0  ...

**Comment by gatorsmile** [comment]
@rajeshcode 2.1 branch is not actively maintained. Please use the 2.2 branch

**Pull request closed without merging**
