### PR TITLE
[SPARK-25588][WIP] SchemaParseException: Can't redefine: list when re…

### PR DESCRIPTION
**Pull request by heuermh**
…ading from Parquet

## What changes were proposed in this pull request?

Added failing unit test that demonstrates the issue described in SPARK-25588.

### CODE REVIEW

**Comment by gengliangwang** [comment]
Hi @heuermh ,

I left some comments in JIRA yesterday. I tried the test case in branch-2.3(with tag v2.3.1 and v2.3.0), the case is still reproduced by running:
```
./build/sbt "; clean; project sql; testOnly *Spark25588Suite"
```
Can you confirm that?

I have also seen a similar issue in Parquet 1.10: https://jira.apache.org/jira/browse/PARQUET-1409

**Comment by HyukjinKwon** [comment]
No feedback from the author. Closing.

**Comment by heuermh** [comment]
Please reopen this issue, must of the discussion is happening elsewhere.  I will update further tomorrow morning.

**Comment by HyukjinKwon** [comment]
push a commit. that reopens a PR

**Comment by heuermh** [comment]
> push a commit. that reopens a PR

I'm not seeing that to be true.  I rebased, squashed the two commits into one, and force pushed.

**Comment by HyukjinKwon** [comment]
hm. weird. can you then just create a PR again? Looks somehow I can't reopen.
Screen Shot 2019-04-25 at 2 59 30 PM

**Pull request closed without merging**
