### PR TITLE
[SPARK-35872][INFRA] Automatize some steps to finalize the release

### PR DESCRIPTION
**Pull request by cloud-fan**
### What changes were proposed in this pull request?

After the RC vote, the release manager still need to do many work to finalize the release. This PR updates the script the automatize some steps:
1. create the final git tag
2. publish to pypi
3. publish docs to spark-website
4. move the release binaries from dev directory to release directory.
5. update the KEYS file

### Why are the changes needed?

easy the work of release manager.

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

tested with the recent 3.0.3.

### CODE REVIEW

**Comment by cloud-fan** [comment]
@srowen @dongjoon-hyun @HyukjinKwon

**Review by dongjoon-hyun — APPROVED** [review]
It's nice! Thank you, @cloud-fan .

Actually, I expected `Moving Spark binaries to the release directory` first and then downloading from the Apache Spark release location in order to upload PySpark/SparkWebsite. However, since this is already tested via 3.0.3, I prefer keep the current one instead of verifying newly revised code.

**Comment by cloud-fan** [comment]
>  I expected Moving Spark binaries to the release directory first 

This is a good point, as the release directory should be more powerful to serve download requests. We can try this idea in the next release.

**Comment by dongjoon-hyun** [comment]
Merged to master for Apache Spark 3.2.0.

**Comment by dongjoon-hyun** [comment]
cc @gengliangwang

**Pull request closed without merging**
