### PR TITLE
[SPARK-50196][CONNECT] Fix Python error context to use a proper context

### PR DESCRIPTION
**Pull request by ueshin**
### What changes were proposed in this pull request?

Fixes Python error context in Spark Connect to use a proper context.

### Why are the changes needed?

The Python error context in Spark Connect has a different context than Spark Classic.

```py
spark.conf.set("spark.sql.ansi.enabled": True)

try:
  df = spark.range(10)
  df.withColumn("div_zero", (df.id / 0) * 10).collect()
except Exception as ee:
  e = ee

e.getQueryContext()[0].fragment()
```

- classic

```
>>> e.getQueryContext()[0].fragment()
'__truediv__'
```

- connect

```
>>> e.getQueryContext()[0].fragment()
'__mul__'
```

### Does this PR introduce _any_ user-facing change?

The error context will be the same as Spark Classic.

### How was this patch tested?

Added the related test.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]

**Review by dongjoon-hyun — COMMENTED** [review]
According to the JIRA `Affected Version` field, is this `master` branch only bug? I'm wondering if `branch-3.5` is safe from this, @ueshin .

**Comment by ueshin** [comment]
@dongjoon-hyun Thanks for the heads-up!
I don't think the dataframe query context is available in 3.5 yet, so it should be fine without backporting. cc @itholic

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM (Pending CIs).

Thank you for the confirmation, @ueshin .

**Comment by dongjoon-hyun** [comment]
Could you check the pyspark unit test failures and Python linter failures, @ueshin ?

**Comment by ueshin** [comment]
I don't think the remaining failures are related to this PR.

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
