### PR TITLE
[SPARK-47325][INFRA] Use the latest `buf-setup-action` in github workflow

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to `unpin` specific version `buf-setup-action` in github workflow building.

### Why are the changes needed?
- [The last](https://github.com/apache/spark/pull/45205) `pin` to a `specific version` was due to a bug in the version `v1.29.0-1`.  The latest version has been upgraded to `v1.30.0`, and testing has found that this version is ok.

- This latest version `v1.30.0` has a `change` regarding the upgrade from `node16` to `node20`.
  https://github.com/bufbuild/buf-setup-action/compare/v1.29.0...v1.30.0
  image

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by zhengruifeng** [comment]
LGTM pending CI

**Comment by panbingkun** [comment]
> LGTM pending CI

Well, let it run through GA first, and then I'll observe the log.  
This version has a change regarding the upgrade from `node16` to `node20`.
https://github.com/bufbuild/buf-setup-action/compare/v1.29.0...v1.30.0
image

**Comment by panbingkun** [comment]
The related logs on GA are as follows:
image

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
