### PR TITLE
[SPARK-4387][PySpark] Refactoring python profiling code to make it extensible

### PR DESCRIPTION
**Pull request by davies**
This PR is based on #3255 , fix conflicts and code style.

Closes #3255.

### CODE REVIEW

**Comment by JoshRosen** [comment]
Thanks for picking this up!

**Comment by davies** [comment]
@JoshRosen I did some refactor on this, please take another pass of review, thanks.

**Comment by udnay** [comment]
Thanks @davies

**Comment by davies** [comment]
@JoshRosen @mateiz  This PR will introduce new API for pyspark, please help to review it.

**Comment by davies** [comment]
@JoshRosen Is it ready to go?

**Comment by davies** [comment]
@JoshRosen Should we include this in 1.3?

**Comment by JoshRosen** [comment]
@davies Sure, let's pull this in for 1.3.  Sorry for letting this hang in the review queue for so long.  This looks good to me, so I'm going to merge it to `master`.

**Comment by orenmazor** [comment]
:dancer: :shipit:

**Comment by solmazsh** [comment]
:rocket:

**Comment by yagnik** [comment]
:dancer:

**Pull request closed without merging**
