### PR TITLE
[SPARK-50421][CORE][3.5] Fix executor related memory config incorrect when multiple resource profiles worked

### PR DESCRIPTION
**Pull request by zjuwangg**
### What changes were proposed in this pull request?

Reset the executor's env memory related config when resource profile is not as the default resource profile!

### Why are the changes needed?
When multiple resource profile exists in the same spark application, now the executor's memory related config is not override by resource profile's memory size, which will cause maxOffHeap in `UnifiedMemoryManager` is not correct.
See https://issues.apache.org/jira/browse/SPARK-50421 for more details

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Tests in our inner spark version and jobs.

### Was this patch authored or co-authored using generative AI tooling?
No

This is a backporting from https://github.com/apache/spark/pull/48963 to branch 3.5

### CODE REVIEW

**Review by LuciferYang — APPROVED** [review]

**Comment by LuciferYang** [comment]
need to rebase or re-trigger the GA, thank you  @zjuwangg

**Comment by zjuwangg** [comment]
> need to rebase or re-trigger the GA, thank you @zjuwangg

Done.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @zjuwangg and @LuciferYang .

**Comment by dongjoon-hyun** [comment]
Merged to branch-3.5 for Apache Spark 3.5.4.

**Pull request closed without merging**
