### PR TITLE
[SPARK-41439][CONNECT][PYTHON][FOLLOWUP] Make unpivot of `connect/dataframe.py` consistent with `pyspark/dataframe.py`

### PR DESCRIPTION
**Pull request by beliefer**
### What changes were proposed in this pull request?
This PR lets `unpivot` of `connect/dataframe.py` consistent with `pyspark/dataframe.py` and adds test cases for connect's `unpivot`.

This PR follows up https://github.com/apache/spark/pull/38973

### Why are the changes needed?
1. Lets `unpivot` of `connect/dataframe.py` consistent with `pyspark/dataframe.py`
2. Add test cases for connect's `unpivot`.

### Does this PR introduce _any_ user-facing change?
'No'. New API

### How was this patch tested?
New test cases.

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]
Looks fine. cc @zhengruifeng

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
Hi, @beliefer . The PR title `Add tests for DataFrame.unpivot` is mismatched because you are chaing `dataframe.py`.

**Comment by beliefer** [comment]
> Hi, @beliefer . The PR title `Add tests for DataFrame.unpivot` is mismatched because you are chaing `dataframe.py`.

Yeah. The PR title updated.

**Review by zhengruifeng — APPROVED** [review]

**Comment by zhengruifeng** [comment]
merged into master, thank you all

**Comment by beliefer** [comment]
@zhengruifeng @HyukjinKwon @dongjoon-hyun Thank you all.

**Pull request closed without merging**
