### PR TITLE
[SPARK-11698][Streaming] Add option to ignore kafka messages that are out of limit rate

### PR DESCRIPTION
**Pull request by viirya**
JIRA: https://issues.apache.org/jira/browse/SPARK-11698

With spark.streaming.kafka.maxRatePerPartition, we can control the max rate limit. However, we can not ignore these messages out of limit. These messages will be consumed in next iteration. We have a use case that we need to ignore these messages and process latest messages in next iteration.

In other words, we simply want to consume part of messages in each iteration and ignore remaining messages that are not consumed.

We add an option for this purpose.

### CODE REVIEW

**Comment by viirya** [comment]
retest this please.

**Comment by jerryshao** [comment]
This is a bit of breaking the semantics of current Spark Streaming. Besides why only in direct Kafka stream if this targets to a general solution.

**Comment by viirya** [comment]
I am not sure if this is a general solution. But you can see that the `maxRatePerPartition` only applies to `DirectKafkaInputDStream` too.

**Comment by jerryshao** [comment]
For other receiver-based stream there also has a max rate cap, so my question is that why are you only address here in direct Kafka stream?

**Comment by viirya** [comment]
I just tried to scan current codebase and can't find where the rate cap is actually used in other receiver-based streams. There is `spark.streaming.backpressure.enabled` and corresponding classes such as `RateController` etc., but I can only find there is a member `rateController` in `ReceiverInputDStream`. However, besides `DirectKafkaInputDStream`, I don't see any other InputDStreams use it.

**Comment by jerryshao** [comment]
"spark.streaming.receiver.maxRate" in `RateLimiter`.

**Comment by viirya** [comment]
I see. But where it is used? `RateLimiter` has `getCurrentLimit` to return the rate and `BlockGenerator ` implements `RateLimiter`. `ReceiverSupervisorImpl` has `getCurrentRateLimit` to call `getCurrentLimit` on its `defaultBlockGenerator`. But I don't see other classes use `getCurrentRateLimit`.

**Comment by tdas** [comment]
This seems like a very very specific niche use case. I am not sure whether this sort of a one-off option is a good idea.

**Comment by viirya** [comment]
@tdas Thanks for comment. I would like to close this first.

**Pull request closed without merging**
