### PR TITLE
[SPARK-26756][SQL] Support session conf for thriftserver

### PR DESCRIPTION
**Pull request by caneGuy**
## What changes were proposed in this pull request?

We can add support for session conf.like:
`set spark.sql.xxx.xxx=xxx`
which can be useful for users.

## How was this patch tested?
Exist UT

### CODE REVIEW

**Comment by caneGuy** [comment]
Could you help review this? @maropu  thanks

**Comment by nrchakradhar** [comment]
Can you please provide an example of what kind of parameters are to be used here. May be documentation update is also needed.

**Comment by maropu** [comment]
Yea, how do we set the parameters in JDBC?

**Comment by caneGuy** [comment]
@maropu @nrchakradhar  Thanks!
Config start with 'spark.sql' and which is non static can be set by execute command like below:
`set spark.sql.xxx.xxx=xxx`
I will update the documentation later.

**Comment by HyukjinKwon** [comment]
?? do you mean we cannot set the configuration by `set ...` via Spark thriftserver if we use `beeline`?

**Comment by HyukjinKwon** [comment]
Can you provide reproducible steps?

**Comment by caneGuy** [comment]
Thanks @HyukjinKwon i will try to reproduce later.Since we may change some logic of STS

**Comment by HyukjinKwon** [comment]
Closing this due to author's inactivity.

**Pull request closed without merging**
