### PR TITLE
[SPARK-50583][INFRA][FOLLOW-UP] Fix 3.5 daily build

### PR DESCRIPTION
**Pull request by zhengruifeng**
### What changes were proposed in this pull request?
Fix 3.5 daily build

```
if: (inputs.branch != 'branch-3.5') && (${{ env.PYSPARK_IMAGE_TO_TEST }} != '')
```
the condition returns true for branch-3.5

### Why are the changes needed?
Fix 3.5 daily build

### Does this PR introduce _any_ user-facing change?
no, infra-only

### How was this patch tested?
manually check

1, `${{ inputs.branch != 'master' && env.PYSPARK_IMAGE_TO_TEST != '' }}`

skipped in PR build

https://github.com/zhengruifeng/spark/actions/runs/12354167258/job/34474934451

2, `${{ inputs.branch != 'branch-3.5' && env.PYSPARK_IMAGE_TO_TEST != '' }}`

runned in PR build

### Was this patch authored or co-authored using generative AI tooling?
no

### CODE REVIEW

**Review by LuciferYang — APPROVED** [review]

**Review by LuciferYang — APPROVED** [review]

**Comment by zhengruifeng** [comment]
merged to master

**Comment by dongjoon-hyun** [comment]
May I ask what was the root cause of the daily CI failure, @zhengruifeng ?

Thank you so much for fixing this. However, do you think we can hold on a little this kind test infra refactorying during 3.5.4 voting periods, @zhengruifeng ? If we cannot trust CIs, we cannot make a release. I hope this kind of irrelevant activity is not going to be a release blocker.

**Comment by zhengruifeng** [comment]
@dongjoon-hyun 

the expression `if: (inputs.branch != 'branch-3.5') && (${{ env.PYSPARK_IMAGE_TO_TEST }} != '')` always return true, so the step is not skipped at branch-3.5

**Comment by dongjoon-hyun** [comment]
Oh, I meant when this bug happens, @zhengruifeng ? Does this bug introduced recently?

**Comment by zhengruifeng** [comment]
This bug was introduced in https://github.com/apache/spark/pull/49193 @dongjoon-hyun

**Pull request closed without merging**
