### PR TITLE
Add hadoop-2.5 profile with upgraded jets3t

### PR DESCRIPTION
**Pull request by zh4ngx**
This contribution is my original work and I license the work to the project under the project's open source license.

Adding support for hadoop-2.5.

Also bumped the jets3t version because there are conflicts with the java-aws-sdk under version 0.9.0. 

JIRA: https://issues.apache.org/jira/browse/SPARK-4807

### CODE REVIEW

**Comment by JoshRosen** [comment]
@ZhangBanger Did you end up trying out the Hadoop 2.4 profile?  Did it work or do we need to do further work for this?

**Comment by ZhangBanger** [comment]
It doesn't change between the Hadoop version profiles, so I should separate the ```jets3t``` into a separate issue/PR.

The ```jets3t``` issue arises from transitive dependencies that clash with ```java-aws-sdk```. Is that something we should be resolving on a one-off basis, is there some shading that needs to happen, or is there a better solution altogether?

**Comment by srowen** [comment]
How about including the updated jets3t in your app and ensuring it's used with userClassPathFirst?

**Comment by ZhangBanger** [comment]
That seems like a good approach. Thanks for the help!

**Pull request closed without merging**
