### PR TITLE
[SPARK-43737][BUILD] Upgrade zstd-jni to 1.5.5-3

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
This pr aims upgrade `zstd-jni` from 1.5.5-2 to 1.5.5-3.

### Why are the changes needed?
New version includes some improvement & bug fixed, eg
- https://github.com/luben/zstd-jni/pull/258
- https://github.com/luben/zstd-jni/pull/262
- https://github.com/luben/zstd-jni/issues/253
    
Other changes as follows:
- https://github.com/luben/zstd-jni/compare/v1.5.5-2...v1.5.5-3

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass GA.

### CODE REVIEW

**Comment by panbingkun** [comment]
Let me append the results of ZStandardBenchmark.

**Comment by panbingkun** [comment]
cc @dongjoon-hyun  @srowen @LuciferYang FYI

**Review by LuciferYang — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. (Pending CIs)

**Review by HyukjinKwon — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Merged to master. Thank you, @panbingkun and all.

**Pull request closed without merging**
