### PR TITLE
[SPARK-45567][CONNECT] Remove redundant if in org.apache.spark.sql.connect.execution.ExecuteGrpcResponseSender#run

### PR DESCRIPTION
**Pull request by zhaomin1423**
### What changes were proposed in this pull request?

remove redundant ```if```

### Why are the changes needed?

it is redundant. 
https://issues.apache.org/jira/browse/SPARK-45567?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel

### How was this patch tested?

pass ci.

### Was this patch authored or co-authored using generative AI tooling?

No

### CODE REVIEW

**Comment by zhaomin1423** [comment]
@juliuszsompolski please help me review it, thanks.

**Comment by zhaomin1423** [comment]
https://github.com/apache/spark/blob/2827242c82dcdfc38b7b14bb6bbd7b5e8d0f356e/connector/connect/server/src/main/scala/org/apache/spark/sql/connect/execution/ExecuteGrpcResponseSender.scala#L78

**Review by juliuszsompolski — APPROVED** [review]
LGTM, thanks!

**Comment by juliuszsompolski** [comment]
cc @hvanhovell

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
