### PR TITLE
[SPARK-45074][PYTHON][CONNECT] `DataFrame.{sort, sortWithinPartitions}` support column ordinals

### PR DESCRIPTION
**Pull request by zhengruifeng**
### What changes were proposed in this pull request?
`DataFrame.{sort, sortWithinPartitions}` support column ordinals

### Why are the changes needed?
for feature parity:

SQL:
```
select a, 1, sum(b) from v group by 1, 2 order by 3, 1;
```

DataFrame:
```
df.select("a", sf.lit(1), "b").groupBy(1, 2).agg(sf.sum("b")).sort(3, 1)
```

### Does this PR introduce _any_ user-facing change?
yes, new feature

### How was this patch tested?
added tests

### Was this patch authored or co-authored using generative AI tooling?
NO

### CODE REVIEW

**Comment by zhengruifeng** [comment]
cc @HyukjinKwon @dongjoon-hyun

**Review by HyukjinKwon — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by dongjoon-hyun** [comment]
Thank you. Merged to master for Apache Spark 4.0.0.

**Comment by zhengruifeng** [comment]
@dongjoon-hyun @HyukjinKwon thanks for review

**Pull request closed without merging**
