### PR TITLE
Little typo

### PR DESCRIPTION
**Pull request by dongido001**
## What changes were proposed in this pull request?
Fixed little typo for a comment

## How was this patch tested?
Manual test

Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Comment by srowen** [comment]
That's fine. Can you look for other typos while you're at it? we try to swat several at once. Even a grep for "to [word] to" could be a good use of time.

**Comment by dongido001** [comment]
Sure thing @srowen

**Comment by dongido001** [comment]
I can only spot this for now.

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
