### PR TITLE
[SPARK-29769][SQL] Support non-correlate "exists/not exists" condition as all type Join's on condition

### PR DESCRIPTION
**Pull request by AngersZhuuuu**
### What changes were proposed in this pull request?
As I show in https://issues.apache.org/jira/browse/SPARK-29769
we can't use `EXISTS/NOT EXISTS` as on condition in `LEFTE OUTER JOIN/ FULL OUTER JOIN / LEFT ANTI JOIN` 
This pr is to support this. 

### Why are the changes needed?
Support EXISTS/NOT EXISTS  as join's on condition

### Does this PR introduce any user-facing change?
People can use exits like 
```
SELECT s1.id FROM s1
LEFT OUTER  JOIN s2 ON s1.id = s2.id
 AND EXISTS (SELECT * from s3 where s3.id > 6)

SELECT s1.id FROM s1
RIGHT OUTER JOIN  s2 ON s1.id = s2.id
AND EXISTS (SELECT * from s3 where s3.id > 6)

SELECT s1.id FROM s1
LEFT SEMI  JOIN s2 ON s1.id = s2.id
AND EXISTS (SELECT * from s3 where s3.id > 6)


SELECT s1.id FROM s1
LEFT ANTI  JOIN s2 ON s1.id = s2.id
AND EXISTS (SELECT * from s3 where s3.id > 6)

SELECT s1.id FROM s1
FULL OUTER JOIN  s2 ON s1.id = s2.id
AND EXISTS (SELECT * from s3 where s3.id > 6)
```

### How was this patch tested?
Added UT

### CODE REVIEW

**Comment by AngersZhuuuu** [comment]
@cloud-fan @maropu 
I make a change in PushPredicateThroughJoin to make it split condition according to JoinType.
For left/right join, we should have different split order or we will lose some case.
sice I wasn't familiar with the full details of catalyst's process

**Comment by cloud-fan** [comment]
ok to test

**Comment by cloud-fan** [comment]
do you mean the optimizer rule `PushPredicateThroughJoin` is the culprit that forbids "exists/not exists" condition in outer joins?

**Comment by AngersZhuuuu** [comment]
> do you mean the optimizer rule `PushPredicateThroughJoin` is the culprit that forbids "exists/not exists" condition in outer joins?

My last pr make it can be analyzed since I make it can resolve Subqueries in join condition. 
But for exists,  in current master, you can use `inner/right outer` but you can't use `left outer/full outer/ left ant/ left semi` ， since in origin `PushPredicateThroughJoin `, origin `split()` will solve leftEvaluateCondition first, in our test query `exists` is not about left or right, then will be be pased to leftEvaluateCondition, then if you meet `RIGHT OUTER JOIN`, it will build a new LeftChild. then it change exists condition to a LeftSemi join. But if you are `LEFT OUTER JOIN` it will build a new RightChild,  exists condition was passed to leftEvaluateCondition, so it won't be solved, and it will be a unresolved PhysicalPlan  as I show in jira.

**Comment by AngersZhuuuu** [comment]
> do you mean the optimizer rule `PushPredicateThroughJoin` is the culprit that forbids "exists/not exists" condition in outer joins?

You can see my change in `PushPredicateThroughJoin` I add a new split method to make it fit for join type. it will build left/right EvaluateCondition in different case. Such as LeftOuterJoin, we should build rightEvaluateCondition  first. Since it will build a new Right child.

**Comment by cloud-fan** [comment]
I'm confused. How can we leave the subquery unresolved in analyzer and fix it in optimizer. @dilipbiswal can you take a look?

**Comment by AngersZhuuuu** [comment]
> unresolved



> I'm confused. How can we leave the subquery unresolved in analyzer and fix it in optimizer? @dilipbiswal can you take a look?

My last pr's change on here https://github.com/apache/spark/blob/0a0383936653efc0bf6f588338270e0967601936/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/Analyzer.scala#L1708
Make it can be resolved.

**Comment by cloud-fan** [comment]
OK I was misled by the JIRA ticket. You don't need to show the query plan assuming a commit(your last PR) is reverted.

**Comment by AngersZhuuuu** [comment]
@cloud-fan 
can you help to see the failed test.
https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/113420/testReport/org.apache.spark.sql.hive.thriftserver/ThriftServerQueryTestSuite/sql_2/

The origin result is strange...
`on false ` why have result.

**Comment by cloud-fan** [comment]
So the direct cause is that we can't plan the subquery. What's the problem in the planner?

**Comment by AngersZhuuuu** [comment]
> So the direct cause is that we can't plan the subquery. What's the problem in the planner?

I will see if there are any place I can plan subquery in exists .

**Comment by AngersZhuuuu** [comment]
> So the direct cause is that we can't plan the subquery. What's the problem in the planner?

Checked and try a lot, seems we can't support EXISTS/NOT EXISTS as on's join condition with FULL OUTER JOIN. Since for FULL OUTER JOIN, we can't push down `exists/not exists` condition to left/right and we can't build a LeftSemi Join with `FULL OUTER JOIN` and `EXISTS subqueries`

**Comment by cloud-fan** [comment]
I think we need to update `PlanSubqueries` to fai if it hit subqueries that it can't plan. @AngersZhuuuu  can you send another PR to do it first?

**Comment by AngersZhuuuu** [comment]
> I think we need to update `PlanSubqueries` to fai if it hit subqueries that it can't plan. @AngersZhuuuu can you send another PR to do it first?

`PlanSubqueries` is what I want to find, Thanks a lot for you suggestion, checking on this.

**Comment by AngersZhuuuu** [comment]
Solved in #26437 
Close this.
cc @cloud-fan

**Comment by cloud-fan** [comment]
There is still an issue about correlated EXISTS in join condition. We can keep thinking about how to fix it.

**Comment by AngersZhuuuu** [comment]
> There is still an issue about correlated EXISTS in join condition. We can keep thinking about how to fix it.

Yea, keeping find way to solve correlated EXISTS in join condition.

**Pull request closed without merging**
