### PR TITLE
[SPARK-31561][SQL] Add QUALIFY Clause

### PR DESCRIPTION
**Pull request by AngersZhuuuu**
### What changes were proposed in this pull request?
In a SELECT statement, the QUALIFY clause filters the results of window functions.
QUALIFY does with window functions what HAVING does with aggregate functions and GROUP BY clauses.
In the execution order of a query, QUALIFY is therefore evaluated after window functions are computed.
Examples:
https://docs.snowflake.com/en/sql-reference/constructs/qualify.html#examples

### Why are the changes needed?
Support  QUALIFY sentence.  make SQL more flexiable.

### Does this PR introduce _any_ user-facing change?
People can use `QUALIFY` like below:
Create and load a table:
```
create table qt (i integer, p char(1), o integer);
insert into qt (i, p, o) values
    (1, 'A', 1),
    (2, 'A', 2),
    (3, 'B', 1),
    (4, 'B', 2);
```
This query uses nesting rather than QUALIFY:
```
select * 
    from (
         select i, p, o, 
                row_number() over (partition by p order by o) as row_num
            from qt
        )
    where row_num = 1
    ;
+---+---+---+---------+
| I | P | O | ROW_NUM |
|---+---+---+---------|
| 1 | A | 1 |       1 |
| 3 | B | 1 |       1 |
+---+---+---+---------+
```
This query uses QUALIFY:
```
select i, p, o
    from qt
    qualify row_number() over (partition by p order by o) = 1
    ;
+---+---+---+
| I | P | O |
|---+---+---|
| 1 | A | 1 |
| 3 | B | 1 |
+---+---+---+
```
You can also use QUALIFY to reference window functions that are in the SELECT column list:
```
select i, p, o, row_number() over (partition by p order by o) as row_num
    from qt
    qualify row_num = 1
    ;
+---+---+---+---------+
| I | P | O | ROW_NUM |
|---+---+---+---------|
| 1 | A | 1 |       1 |
| 3 | B | 1 |       1 |
+---+---+---+---------+
```
You can see how the QUALIFY acts as a filter by removing the QUALIFY from the previous query and comparing the output:
```
select i, p, o, row_number() over (partition by p order by o) as row_num
    from qt
    ;
+---+---+---+---------+
| I | P | O | ROW_NUM |
|---+---+---+---------|
| 1 | A | 1 |       1 |
| 2 | A | 2 |       2 |
| 3 | B | 1 |       1 |
| 4 | B | 2 |       2 |
+---+---+---+---------+
```
The QUALIFY clause can also be combined with aggregates and can have subqueries in the predicate, e.g.:
```
select c2, sum(c3) over (partition by c2) as r
  from t1
  where c3 < 4
  group by c2, c3
  having sum(c1) > 3
  qualify r in (
    select min(c1)
      from test
      group by c2
      having min(c1) > 3);
```

### How was this patch tested?
Added UT

### CODE REVIEW

**Comment by bart-samwel** [comment]
I'm not a huge fan of this. For one thing, it is not in ANSI SQL 2016. AFAICT it's a Teradata extension that Snowflake adopted as well because they get a lot of Teradata workloads. To be honest, I find it confusing. There's already WHERE and HAVING, and QUALIFY follows HAVING but the evaluation order is different:

Syntax: SELECT -> FROM -> WHERE -> GROUP BY -> **HAVING -> QUALIFY**
Semantics: FROM -> WHERE -> GROUP BY -> **HAVING -> SELECT -> QUALIFY**

And all it does is basically (SELECT * FROM (SELECT -> FROM -> WHERE -> GROUP BY -> HAVING) WHERE ...). To make this work they've invented a third synonym that basically means "filter", but the meaning is less clear than any of the other synonyms because the order in the syntax is right next to HAVING.

**Comment by gatorsmile** [comment]
@AngersZhuuuu Agree on what @bart-samwel said. Maybe we can revisit this in future? Let us first close this PR?

**Comment by AngersZhuuuu** [comment]
> @AngersZhuuuu Agree on what @bart-samwel said. Maybe we can revisit this in future? Let us first close this PR?

OK， close it.

**Comment by AngersZhuuuu** [comment]
@bart-samwel @HyukjinKwon  @gatorsmile
 One confuse, why we can't  support window function in Filter condition?
Support SQL like this can make some SQL more readable 
```
select id, key, value
from (
select id,  row_number() over (partition by key order by value asc) as rn, key, value  from 
(
select id, key, value from test_score
LATERAL VIEW explode (map(
  'score1', score1,
  'score2', score2
  'score3', score3
)) t2 as key, value
) tmp
) s
where rn=1
```

I can just write like below
```
select id, key, value  from 
(
select id, key, value from test_score
LATERAL VIEW explode (map(
  'score1', score1,
  'score2', score2
  'score3', score3
)) t2 as key, value
) tmp
) s
where  row_number() over (partition by key order by value asc)  = 1, 
```

**Comment by bart-samwel** [comment]
@AngersZhuuuu This is problematic because the `WHERE` clause comes *before* the `GROUP BY` clause, but window functions (and the `SELECT`) are evaluated *after* the GROUP BY clause.

If anything, we could allow this in the HAVING clause, which goes just before SELECT. The trouble with that is that:

(a) the HAVING clause can't reference SELECT list aliases, so this would only be useful if you want to e.g. filter by row_number / rank without actually selecting it in the output. This will inevitably lead to feature requests to allow SELECT list aliases referenced from HAVING, which is not great because it can lead to ambiguous references.

(b) The ANSI SQL standard expressly says that it's not allowed.

**Comment by AngersZhuuuu** [comment]
> @AngersZhuuuu This is problematic because the `WHERE` clause comes _before_ the `GROUP BY` clause, but window functions (and the `SELECT`) are evaluated _after_ the GROUP BY clause.
> 
> If anything, we could allow this in the HAVING clause, which goes just before SELECT. The trouble with that is that:
> 
> (a) the HAVING clause can't reference SELECT list aliases, so this would only be useful if you want to e.g. filter by row_number / rank without actually selecting it in the output. This will inevitably lead to feature requests to allow SELECT list aliases referenced from HAVING, which is not great because it can lead to ambiguous references.
> 
> (b) The ANSI SQL standard expressly says that it's not allowed.

Got the point, may be this is why Teradata add a QUALIFY clause to support direct filter by window function.

**Comment by bart-samwel** [comment]
> Got the point, may be this is why Teradata add a QUALIFY clause to support direct filter by window function.

Yeah, and I'm not saying that it isn't useful in some cases, I'm just saying that it's going to be so rare that it'll confuse people. I asked @hvanhovell who actually used Teradata professionally in the past, and his response was that (a) he used this sometimes and it was useful, and (b) it would confuse the heck out of his colleagues when they encountered it. I think point (b) is the most important thing here -- if people just wrap the query as a subquery and then use WHERE, then everybody can understand it immediately (if they understand window functions, at least). People already have a hard time understanding the difference between WHERE and HAVING. Adding a third and even more obscure option wouldn't help understandability.

**Comment by AngersZhuuuu** [comment]
Yea, have a common SQL standard  is important.   Everyone has a different level of knowledge about SQL.  This pr is useful for people who use Teradata and want to migrate SQL from TeraData to Spark SQL.  They can do it internally

**Pull request closed without merging**
