### PR TITLE
[SPARK-8386] [SQL]add write.mode for insertIntoJDBC when the parm overwrite is false

### PR DESCRIPTION
**Pull request by huaxingao**
the fix is for jira https://issues.apache.org/jira/browse/SPARK-8386

### CODE REVIEW

**Comment by rxin** [comment]
Jenkins, test this please.

**Comment by huaxingao** [comment]
Has the test result come back yet?

**Comment by rxin** [comment]
Nope...

**Comment by JoshRosen** [comment]
Jenkins, retest this please.

**Comment by huaxingao** [comment]
I looked the error log, it failed at fetching changes from the remote Git repository.  Does it mean something is wrong with my pull request and I need to do a new pull request?  Sorry I am new and not familiar with these yet. 
Thanks for your help!!

**Comment by rxin** [comment]
Thanks - I've merged this.

**Pull request closed without merging**
