### PR TITLE
[SPARK-25903][Core] TimerTask should be synchronized on ContextBarrierState

### PR DESCRIPTION
**Pull request by viirya**
### What changes were proposed in this pull request?

BarrierCoordinator sets up a TimerTask for a round of global sync. Currently the run method is synchronized on the created TimerTask. But to be synchronized with handleRequest, it should be synchronized on the ContextBarrierState object, not TimerTask object.

### Why are the changes needed?

ContextBarrierState.handleRequest and TimerTask.run both access the internal status of a ContextBarrierState object. If TimerTask doesn't be synchronized on the same ContextBarrierState object, when the timer task is triggered, handleRequest still accepts new request and modify  requesters field in the ContextBarrierState object. It makes the behavior inconsistency.

### Does this PR introduce any user-facing change?

No

### How was this patch tested?

Test locally

### CODE REVIEW

**Comment by viirya** [comment]
cc @ jiangxb1987 @cloud-fan

**Comment by viirya** [comment]
retest this please.

**Comment by viirya** [comment]
cc @jiangxb1987

**Comment by cloud-fan** [comment]
good catch! LGTM. Why do we need [test] in the title?

**Comment by viirya** [comment]
Because SPARK-25903 is about one flaky test in BarrierTaskContextSuite. I found this issue when looking into the reason. Should I create another JIRA?

**Comment by viirya** [comment]
Sure. Removed. Thanks.

**Comment by cloud-fan** [comment]
thanks, merging to master/2.4!

**Comment by dongjoon-hyun** [comment]
Thank you, @viirya and @cloud-fan !

**Pull request closed without merging**
