### PR TITLE
[SPARK-26350][FOLLOWUP] Add actual verification on new UT introduced on SPARK-26350

### PR DESCRIPTION
**Pull request by HeartSaVioR**
## What changes were proposed in this pull request?

This patch adds the check to verify consumer group id is given correctly when custom group id is provided to Kafka parameter.

## How was this patch tested?

Modified UT.

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
I tried to populate group id in physical plan just before it is provided to Kafka client, but considering all cases for batch/micro-batch/continuous * DSv1/DSv2 matrix is not easy. Hopefully there's a way to populate valid consumer groups in Kafka cluster, so I just took the approach.

@zsxwing Could you please take a look? Thanks in advance.

**Comment by zsxwing** [comment]
This is nice and clean. Thanks for writing the unit test. Could you also add the verification to `KafkaRelationSuite.scala`?

**Comment by HeartSaVioR** [comment]
@zsxwing Thanks for the quick review! Added to KafkaRelationSuite as well. Basically the code is duplicated, but not sure where to extract duplication. (KafkaTest seems for, but it is only used for clearing CachedKafkaProducer)

**Comment by HeartSaVioR** [comment]
Thanks for reviewing and merging, @zsxwing!

**Pull request closed without merging**
