### PR TITLE
[WIP] Fix `SET -v` not to raise exceptions for configs with default value `null`

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
## What changes were proposed in this pull request?

This is to investigate the current `SET -v` behavior.

## How was this patch tested?

Add two test cases.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
This is just to see the isolated result of `SET -v`. After resolving the failure, this will be close and be merged into #16579 .

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by dongjoon-hyun** [comment]
Retest this please

**Comment by dongjoon-hyun** [comment]
Finally, we get the expected failures. (The first MiMa failure and the second `HiveSparkSubmitSuite` was just flaky failures.)
```
 org.apache.spark.sql.SQLQuerySuite.`SET -v` collect test	16 ms	1
 org.apache.spark.sql.SQLQuerySuite.`SET -v` key collect test
```

Hi, @gatorsmile and @srowen .

The current `set -v` command has a problem as we can see in these test failures. I will fix this first here.

**Comment by gatorsmile** [comment]
Sure, please fix it. Thanks!

**Comment by dongjoon-hyun** [comment]
Retest this please

**Comment by dongjoon-hyun** [comment]
The final failure, `HiveSparkSubmitSuite.dir` is irrelevant to this PR.

**Comment by gatorsmile** [comment]
Please update the PR description.

**Comment by dongjoon-hyun** [comment]
Hi, @gatorsmile .
I tested here and applied to #16579 .
PR #16579 has two fixes. After merging #16579 , I'm going to close this one.

**Pull request closed without merging**
