### PR TITLE
[SPARK-44324][SQL][CONNECT] Move CaseInsensitiveMap to sql/api

### PR DESCRIPTION
**Pull request by amaliujia**
### What changes were proposed in this pull request?

Move CaseInsensitiveMap to sql/api. 

### Why are the changes needed?

So that Spark Connect Scala client do not need to depend on the Catalyst.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Existing test

### CODE REVIEW

**Comment by amaliujia** [comment]
@cloud-fan

**Review by cloud-fan — APPROVED** [review]

**Review by HyukjinKwon — APPROVED** [review]

**Review by LuciferYang — CHANGES_REQUESTED** [review]
Please also move the Scala 2.13 version `CaseInsensitiveMap` to `sql/api` together

https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala-2.13/org/apache/spark/sql/catalyst/util/CaseInsensitiveMap.scala

**Comment by amaliujia** [comment]
@LuciferYang oh I see! Done!

**Comment by amaliujia** [comment]
@LuciferYang can you point me where to configure the 2.12 and 2.13 SBT compilation for the same class. Right now SBT reports the class not found so  I assume I need to do something extra?

**Comment by amaliujia** [comment]
@LuciferYang oops. I guess it was my issue. SBT should just compile

**Comment by amaliujia** [comment]
@LuciferYang do you know why such move does not work for mvn?

**Comment by LuciferYang** [comment]
@amaliujia Sorry to late reply, we need add 
```
<plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>add-sources</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>src/main/scala-${scala.binary.version}</source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

to pom.xml like 
https://github.com/apache/spark/blob/4bec3114c3cb6c49eff3c2c853e58ef239d0bacf/sql/catalyst/pom.xml#L191-L207

**Comment by amaliujia** [comment]
@LuciferYang thanks! I have applied your suggestion.

**Review by LuciferYang — APPROVED** [review]
LGTM

But let's add a empty line at the end of `pom.xml`. @amaliujia

**Comment by LuciferYang** [comment]
@amaliujia on the other hand, should we also move `org.apache.spark.sql.catalyst.util.CaseInsensitiveMapSuite` to `sql/api` module?

**Comment by amaliujia** [comment]
@LuciferYang the suite movement is planed for the next. We are not moving suites now as we do not publish those in Spark 3.5. Right now just want to make sure code that need to be published to be refactored. Later we will tackle the suites.

**Comment by LuciferYang** [comment]
@amaliujia Can you re-trigger the failed GA task?

**Review by cloud-fan — APPROVED** [review]

**Comment by cloud-fan** [comment]
thanks, merging to master/3.5 (part of the spark connect scala client project)

**Pull request closed without merging**
