### PR TITLE
[SPARK-42257][CORE] Remove unused variable external sorter

### PR DESCRIPTION
**Pull request by khalidmammadov**
### What changes were proposed in this pull request?
Remove unused variable 

### Why are the changes needed?
To simplify and clean up

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Existing unit tests

### CODE REVIEW

**Comment by srowen** [comment]
That's fine, are there more?

**Comment by khalidmammadov** [comment]
That all I have seen while looking at that code

**Comment by srowen** [comment]
Merged to master. This kind of thing can be a [MINOR] PR with no JIRA

**Comment by khalidmammadov** [comment]
Thanks 👍

**Pull request closed without merging**
