### PR TITLE
[SPARK-35785][SS][FOLLOWUP] Ignore concurrent update and cleanup test

### PR DESCRIPTION
**Pull request by viirya**
### What changes were proposed in this pull request?

This patch ignores the test "ensure that concurrent update and cleanup consistent versions" in #32933. The test is currently flaky and we will address it later.

### Why are the changes needed?

Unblock other developments.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by viirya** [comment]
cc @dongjoon-hyun

**Review by dongjoon-hyun — APPROVED** [review]
If that is a test only issue, I'm +1.
BTW, let's keep the issue open although we merge this.

**Comment by viirya** [comment]
Thanks @dongjoon-hyun!

Yea, I reuse original JIRA with followup only.

@xuanyuanking will address SPARK-35993 by fixing the test later.

And yes, this is test only issue.

**Comment by dongjoon-hyun** [comment]
Oh, perfect, @viirya !
> Yea, I reuse original JIRA with followup only.

**Comment by viirya** [comment]
Thanks @dongjoon-hyun

**Pull request closed without merging**
