### PR TITLE
[SPARK-33589][SQL][FOLLOWUP] Replace Throwable with NonFatal

### PR DESCRIPTION
**Pull request by wangyum**
### What changes were proposed in this pull request?

This pr replace `Throwable` with `NonFatal`.

### Why are the changes needed?

Improve code.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

N/A

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @gatorsmile

**Review by srowen — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thanks, @wangyum , @HyukjinKwon , @srowen .
Merged to master/3.1.

**Comment by mridulm** [comment]
This will cause thread interruptions to result in exceptions being thrown instead of ignored. Is this intentional ?

**Comment by dongjoon-hyun** [comment]
Hi, @mridulm . Is the comment for [the original PR](https://github.com/apache/spark/pull/30536) body or this follow up?
> This will cause thread interruptions to result in exceptions being thrown instead of ignored. Is this intentional ?

Also, cc @gatorsmile once more.

**Pull request closed without merging**
