### PR TITLE
[SPARK-30930][ML] Remove ML/MLLIB DeveloperApi annotations

### PR DESCRIPTION
**Pull request by huaxingao**
### What changes were proposed in this pull request?
jira link: https://issues.apache.org/jira/browse/SPARK-30930

Remove ML/MLLIB DeveloperApi annotations.

### Why are the changes needed?

The Developer APIs in ML/MLLIB have been there for a long time. They are stable now and are very unlikely to be changed or removed, so I unmark these Developer APIs in this PR.

### Does this PR introduce any user-facing change?
Yes. DeveloperApi annotations are removed from docs.

### How was this patch tested?
existing tests

### CODE REVIEW

**Comment by huaxingao** [comment]
retest this please

**Comment by srowen** [comment]
This is a good one for @mengxr @marmbrus and maybe @gatorsmile -- the theory here which I agree with is that, from 3.0 on, we almost surely will not change these public APIs. Therefore marking them as anything less like "Experimental" or "DeveloperApi" doesn't mean much of anything. What do you think? is "DeveloperApi" different, communicating that it's public and stable just generally not meant for applications to call?

**Comment by mengxr** [comment]
@srowen I actually used the annotation to indicate the APIs are for developer use instead of end users. I just checked the definition of the annotation, it seems I misunderstood it. If we always use it to label very unstable API, then I agree that we should remove them. But I still hope that we have some annotation to separate user and developer APIs. cc: @gatorsmile

**Comment by marmbrus** [comment]
+1 to remove them if we expect stability here.

**Review by mengxr — APPROVED** [review]

**Comment by gatorsmile** [comment]
Yes. https://github.com/apache/spark/commit/87bd1f9ef7d547ee54a8a83214b45462e0751efb shows the definition and original motivation. 

+1 to remove them for the stable APIs.

**Comment by srowen** [comment]
Merged to master/3.0

**Comment by huaxingao** [comment]
Thank you all!

**Pull request closed without merging**
