### PR TITLE
[SPARK-24957][SQL][FOLLOW-UP] Clean the code for AVERAGE

### PR DESCRIPTION
**Pull request by gatorsmile**
## What changes were proposed in this pull request?
This PR is to refactor the code in AVERAGE by dsl.

## How was this patch tested?
N/A

### CODE REVIEW

**Comment by holdensmagicalunicorn** [comment]
@gatorsmile, thanks! I am a bot who has found some folks who might be able to help with the review:@rxin, @cloud-fan and @ueshin

**Comment by gatorsmile** [comment]
cc @hvanhovell @rednaxelafx @cloud-fan

**Comment by rxin** [comment]
Why would we want to use the DSL here? Do we use it in other expressions?

**Comment by gatorsmile** [comment]
This will simplify the code and improve the readability. We can do the same in the other expression.

**Comment by rednaxelafx** [comment]
LGTM as well. Thanks a lot!

**Comment by cloud-fan** [comment]
LGTM. shall we create a JIRA ticket to apply this to other `DeclarativeAggregate`s?

**Comment by gatorsmile** [comment]
Thanks! Merged to master. 

Please ignore the last commit.

**Comment by gatorsmile** [comment]
https://issues.apache.org/jira/browse/SPARK-24996 is created,

**Pull request closed without merging**
