### PR TITLE
[SPARK-8291] [MLlib] [PySpark] Add parse functionality to LabeledPoint in PySpark

### PR DESCRIPTION
**Pull request by MechCoder**
It is useful to have functionality that can parse a string into a LabeledPoint while loading files, etc

### CODE REVIEW

**Comment by MechCoder** [comment]
cc: @srowen @brkyvz Can you please have a look at this?

**Comment by MechCoder** [comment]
@davies Could you have a look at this also? :P

**Comment by davies** [comment]
There could be many different formats in a string, so I'm not sure which format we should support. It's better to be done by user.

cc @mengxr

**Comment by MechCoder** [comment]
Hmm. The present supported format is coherent with that done in Scala.

**Comment by davies** [comment]
I see, in order to have similar functionality as Scala, we should do similar things as in #685, having MLUtils.loadLabelPoints() ...

**Comment by davies** [comment]
Also the format we used here, should match with LabelPoint.__str__(), then it can load the RDD after saveAsTextFile.

**Comment by MechCoder** [comment]
I have added tests to verify it.

    from pyspark.mllib.regression import LabeledPoint
    lb = LabeledPoint(2, [0.1, 1.2, 3.4])
    rdd = sc.parallelize([lb, lb, lb])
    rdd.saveAsTextFile("tmp")
    sc.textFile("tmp").map(LabeledPoint.parse)

**Comment by MechCoder** [comment]
MLUtils.LabeledPoints is just a wrapper around the scala code right? Were you trying to infer that this also should be a wrapper around the parse method in Scala? Is that required for something as simple as this?

**Comment by MechCoder** [comment]
@mengxr Should I close this then?

**Pull request closed without merging**
