### PR TITLE
[SPARK-21604][SQL] if the object extends Logging, i suggest to remove the var LOG which is useless.

### PR DESCRIPTION
**Pull request by zuotingbing**
## What changes were proposed in this pull request?

if the object extends Logging, i suggest to remove the var LOG which is useless.

## How was this patch tested?

Exist tests

### CODE REVIEW

**Comment by srowen** [comment]
That looks removable, but this isn't really worth bothering with or opening a JIRA. Can you look for other unused log vars?

**Comment by zuotingbing** [comment]
Thanks @srowen , will do.

**Comment by srowen** [comment]
Ah, I'm sorry I misled you a bit here @zuotingbing . Yes you found another unused variable, but, it's in code that is copied directly from Hive. I think we should leave HiveSessionImplwithUGI untouched. It makes it easier to patch it if we don't have custom changes.
https://github.com/apache/hive/blob/master/service/src/java/org/apache/hive/service/cli/session/HiveSessionImplwithUGI.java

If you'll back that out, and this is the only other change you found, I'll merge it

**Comment by zuotingbing** [comment]
ok, have done. Thanks @srowen .

**Review by srowen — APPROVED** [review]

**Comment by srowen** [comment]
merged to master

**Pull request closed without merging**
