### PR TITLE
[SPARK-45466][ML] `VectorAssembler` should validate the vector elements

### PR DESCRIPTION
**Pull request by zhengruifeng**
### What changes were proposed in this pull request?
Make `VectorAssembler` validate the vector values

### Why are the changes needed?
`VectorAssembler` should validate the vector values

### Does this PR introduce _any_ user-facing change?
yes, in `error` mode, if a vector contains `NaN`, it fails

before this PR:
```
In [15]: from pyspark.ml.linalg import Vectors

In [16]: from pyspark.ml.feature import VectorAssembler

In [17]: df = spark.createDataFrame([(1.0, Vectors.dense(float('nan'))), (0.0, Vectors.sparse(1, [], []))], ["label", "features
    ...: "])

In [18]: vecAssembler = VectorAssembler(outputCol="new_features")

In [19]: vecAssembler.setInputCols(["label", "features"])
Out[19]: VectorAssembler_a3896f503d95

In [20]: vecAssembler.transform(df).show()
+-----+---------+------------+
|label| features|new_features|
+-----+---------+------------+
|  1.0|    [NaN]|   [1.0,NaN]|
|  0.0|(1,[],[])|   (2,[],[])|
+-----+---------+------------+
```

after this PR:
```
In [6]: vecAssembler.transform(df).show()
23/10/10 10:53:20 ERROR Executor: Exception in task 0.0 in stage 5.0 (TID 17)
org.apache.spark.SparkException: [FAILED_EXECUTE_UDF] Failed to execute user defined function (`VectorAssembler$$Lambda$2749/0x0000007001e3fb20`: (struct<label:double,features:struct<type:tinyint,size:int,indices:array<int>,values:array<double>>>) => struct<type:tinyint,size:int,indices:array<int>,values:array<double>>).
	at org.apache.spark.sql.errors.QueryExecutionErrors$.failedExecuteUserDefinedFunctionError(QueryExecutionErrors.scala:194)
    ...
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.apache.spark.SparkException: Encountered NaN while assembling a row with handleInvalid = "error". Consider
removing NaNs from dataset or using handleInvalid = "keep" or "skip".

```

### How was this patch tested?
added UTs

### Was this patch authored or co-authored using generative AI tooling?
no

### CODE REVIEW

**Review by srowen — COMMENTED** [review]
Does this change behavior or just refactor code? I'm actually surprised that NaN is treated as an error but looks like that is existing behavior?

**Comment by zhengruifeng** [comment]
> Does this change behavior or just refactor code? I'm actually surprised that NaN is treated as an error but looks like that is existing behavior?

It is a behavior change.
Before this PR, NaN/null doubles and null vectors are treated as errors, but NaN values inside a vector are ignored.

**Comment by srowen** [comment]
Is that really an error? It's the only way to represent a missing value

**Comment by zhengruifeng** [comment]
> Is that really an error? It's the only way to represent a missing value

https://github.com/apache/spark/blob/d679dabdd1b5ad04b8c7deb1c06ce886a154a928/mllib/src/main/scala/org/apache/spark/ml/feature/VectorAssembler.scala#L72-L81


according to the doc, the `NULL and NaN values` are invalid data.
And the default `handleInvalid` is `error`, which treats invalid values as errors.

If users want to keep the missing value, users can set `handleInvalid=keep`

**Comment by srowen** [comment]
I see. Would users want to filter/catch NaN here and not upstream? maybe. I'm reluctant to change behavior even in 4.0.

**Comment by zhengruifeng** [comment]
ok. I'm fine to close it since there is no strong requirement

**Pull request closed without merging**
