### PR TITLE
[SPARK-47539][SQL] Make the return value of method `castToString` be `Any => UTF8String`

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to:
- make the method `castToString(from: DataType): Any => Any` to `castToString(from: DataType): Any => UTF8String` in `ToStringBase`.
- Add UT for `ToPrettyString` to improve the `coverage` of UT.

### Why are the changes needed?
- Let the method return a UTF8String(`Any` -> `UTF8String`), which is more intuitive.
- Currently, `ToPrettyString` lacks the corresponding `UT`.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
- Add new UT.
- Pass GA.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by panbingkun** [comment]
cc @cloud-fan @MaxGekk

**Review by MaxGekk — COMMENTED** [review]
LGTM in general, but could you improve PR's title (it contains to much details).

**Comment by panbingkun** [comment]
> LGTM in general, but could you improve PR's title (it contains to much details).

Haha, Okay, I have `updated` it.
Thank you very much!

**Review by MaxGekk — APPROVED** [review]

**Review by cloud-fan — APPROVED** [review]

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by mihailom-db** [comment]
Were tests run for this PR? It seems to have broken the master branch.

**Comment by cloud-fan** [comment]
it did pass all tests: https://github.com/panbingkun/spark/runs/23041868866

**Comment by MaxGekk** [comment]
Maybe it conflicts with https://github.com/apache/spark/pull/45575 ?

**Comment by davidm-db** [comment]
Breaks the tests for me as well, on `master` without my changes.

**Comment by MaxGekk** [comment]
Let's revert the changes: https://github.com/apache/spark/pull/45697

**Comment by mihailom-db** [comment]
I can try to fix it if you want.

**Comment by mihailom-db** [comment]
The only problem is that we are testing some behaviour which should not be tested. toPrettyString is not intended to be called on Variant type and the expected result. That feature was not even supported before this PR, so I believe only the test should be removed.

**Comment by panbingkun** [comment]
I have submitted a FOLLOWUP PR to fix this case, here: https://github.com/apache/spark/pull/45702

**Pull request closed without merging**
