### PR TITLE
[SPARK-23261] [PySpark] Rename Pandas UDFs

### PR DESCRIPTION
**Pull request by gatorsmile**
## What changes were proposed in this pull request?
Rename the public APIs and names of pandas udfs. 

- `PANDAS SCALAR UDF` -> `SCALAR PANDAS UDF`
- `PANDAS GROUP MAP UDF` -> `GROUPED MAP PANDAS UDF`
- `PANDAS GROUP AGG UDF` -> `GROUPED AGG PANDAS UDF`

## How was this patch tested?
The existing tests

### CODE REVIEW

**Comment by gatorsmile** [comment]
Had an offline discussion with @sameeragarwal and @cloud-fan . To be consistent with the other APIs, we would propose to make the above changes. 

The major question is about the current name of `Pandas UDAF` when we supporting partial aggregate. 

Also cc @rxin @ueshin  @HyukjinKwon @icexelloss @BryanCutler

**Comment by icexelloss** [comment]
* `PANDAS SCALAR UDF` -> `SCALAR PANDAS UDF`
This doesn't really change the API so +1

* `PANDAS GROUP MAP UDF` -> `GROUPED MAP PANDAS UDF`
The API changes from `PandasUDFType.GROUP_MAP` to `PandasUDFType.GROUPED_MAP`. I think this is fine as well. 

*  `PANDAS GROUP AGG UDF` -> `PANDAS UDAF`
The API changes from `PandasUDFType.GROUP_AGG` to `PandasUDFType.UDAF`. I don't love this because it feels different from `SCALAR` and `GROUPED_MAP`. I would probably call it something like `GROUPED_AGG`. But since this type is not released in 2.3, we can always change later.

**Comment by HyukjinKwon** [comment]
Yup, fortunately(?) we are free to rename `SQL_PANDAS_GROUP_AGG_UDF` within 2.4.0 currently but I believe here is a good place to decide based on what I got so far. The proposal seems fine to me for now.

**Comment by viirya** [comment]
First two changes looks good. The last one, maybe `PANDAS GROUP AGG UDF` -> `GROUPED AGG PANDAS UDF`?

**Comment by sameeragarwal** [comment]
+1 on `GROUPED AGG` as well

**Comment by HyukjinKwon** [comment]
+1 on `GROUPED AGG` to me too, just to be clear.

**Comment by cloud-fan** [comment]
+1 on `GROUPED AGG` too, we may add new UDF type when we support partial aggregate.

**Comment by cloud-fan** [comment]
LGTM

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Review by HyukjinKwon — APPROVED** [review]
LGTM

**Review by viirya — APPROVED** [review]
LGTM

**Comment by viirya** [comment]
Let's also update PR description too.

**Comment by ueshin** [comment]
Jenkins, retest this please.

**Comment by ueshin** [comment]
LGTM.

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by cloud-fan** [comment]
@gatorsmile shall we backport it to 2.3? excluding the `GROUPED AGG`.

**Comment by gatorsmile** [comment]
Yes. We need to backport it to 2.3

**Comment by gatorsmile** [comment]
Let me manually push it to 2.3. Thanks!

**Comment by gatorsmile** [comment]
Will submit a new PR to 2.3

**Pull request closed without merging**
