### PR TITLE
[SPARK-10310] [SQL] Fixes script transformation field/line delimiters

### PR DESCRIPTION
**Pull request by liancheng**
**Please attribute this PR to `Zhichao Li <zhichao.li@intel.com>`.**

This PR is based on PR #8476 authored by @zhichao-li. It fixes SPARK-10310 by adding field delimiter SerDe property to the default `LazySimpleSerDe`, and enabling default record reader/writer classes.

Currently, we only support `LazySimpleSerDe`, used together with `TextRecordReader` and `TextRecordWriter`, and don't support customizing record reader/writer using `RECORDREADER`/`RECORDWRITER` clauses. This should be addressed in separate PR(s).

### CODE REVIEW

**Comment by zhichao-li** [comment]
@liancheng I guess there's still some issue like: 
i.e:  If user specify serde with "LazySimpleSerde" explicitly, then it would use `Text.write` to serialize which would not match the behavior of  `tab as field delimeter and \n as the line delimiter`. 
Maybe we can adding more support in the other PR since most of the user would only depend on the default behavior, and this can cover the majority usages.   :)

**Comment by liancheng** [comment]
@zhichao-li I further special cased `LazySimpleSerDe`, so that we always use `TextRecordReader`/`TextRecordWriter` together with it, and uses can customize field delimiter now. Please check [this test case] [1].

[1]: https://github.com/apache/spark/pull/8860/files#diff-1ea02a6fab84e938582f7f87cc4d9ea1R1207

**Comment by yhuai** [comment]
test this please

**Comment by yhuai** [comment]
https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/42846/testReport/junit/org.apache.spark.sql.hive.execution/SQLQuerySuite/SPARK_10310__script_transformation_using_LazySimpleSerDe/

Looks like a legitimate failure?

**Comment by yhuai** [comment]
@zhichao-li Can you try this PR?

**Comment by zhichao-li** [comment]
LGTM

**Comment by yhuai** [comment]
Thanks! Merging to master and branch 1.5.

**Pull request closed without merging**
