### PR TITLE
[SPARK-26917][SQL] Cache lock recache by condition

### PR DESCRIPTION
**Pull request by DaveDeCaprio**
## What changes were proposed in this pull request?

Related to SPARK-26617 and SPARK-26548.  There was a new location we found where we were still seeing the locks.  We traced it to the recacheByCondition function.  In this PR I have changed that function so that the writeLock is not held while the condition is being evaluated.

@cloud-fan & @gatorsmile This is a further tweak to the other cache PRs we have done (which have helped us tremendously).

## How was this patch tested?

Has been tested on a live system where the blocking was causing major issues and it is working well.
CacheManager has no explicit unit test but is used in many places internally as part of the SharedState.

### CODE REVIEW

**Comment by srowen** [comment]
I don't know this code well, but the change looks reasonable. The question of course is somehow whether the decision to uncache something could change between where it happens before and after. It doesn't seem so, as the intent here seems to be to evaluate what is to be uncached, release the lock, then do it. Maybe CC @cloud-fan

**Comment by cloud-fan** [comment]
seems file, cc @maryannxue @gatorsmile

**Comment by cloud-fan** [comment]
retest this please

**Comment by cloud-fan** [comment]
retest this please

**Comment by DaveDeCaprio** [comment]
I can't see the build results.  Is there a problem with the Jenkins server?

**Comment by srowen** [comment]
(There is a problem with Jenkins ATM yes)

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
