### PR TITLE
[MINOR][SPARKRSQL]Remove unnecessary comment in SqlBase.g4

### PR DESCRIPTION
**Pull request by lys0716**
## What changes were proposed in this pull request?

The issue(https://github.com/antlr/antlr4/issues/781) in the comment is fixed in its duplicate ticket(https://github.com/antlr/antlr4/issues/773).

## How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by srowen** [comment]
It still leads to the underlying issue. Why remove?

**Comment by lys0716** [comment]
Sorry, it is duplicate to https://github.com/antlr/antlr4/issues/773. But on the second thought, the rule is still a workaround for that issue.

**Comment by felixcheung** [comment]
please change your title `SPARKRSQL` -> `SQL`

**Comment by srowen** [comment]
Ok, so close this

**Pull request closed without merging**
