### PR TITLE
[SPARK-17065][SQL]Improve the error message when encountering an incompatible DataSourceRegister

### PR DESCRIPTION
**Pull request by zsxwing**
## What changes were proposed in this pull request?

Add an instruction to ask the user to remove or upgrade the incompatible DataSourceRegister in the error message.
## How was this patch tested?

Test command:

```
build/sbt -Dscala-2.10 package
SPARK_SCALA_VERSION=2.10 bin/spark-shell --packages ai.h2o:sparkling-water-core_2.10:1.6.5

scala> Seq(1).toDS().write.format("parquet").save("foo")
```

Before:

```
java.util.ServiceConfigurationError: org.apache.spark.sql.sources.DataSourceRegister: Provider org.apache.spark.h2o.DefaultSource could not be instantiated
    at java.util.ServiceLoader.fail(ServiceLoader.java:232)
    at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
    at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
    at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
    at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
...
Caused by: java.lang.NoClassDefFoundError: org/apache/spark/Logging
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
    at java.security.AccessController.doPrivileged(Native Method)
...
```

After:

```
java.lang.ClassNotFoundException: Detected an incompatible DataSourceRegister. Please remove the incompatible library from classpath or upgrade it. Error: org.apache.spark.sql.sources.DataSourceRegister: Provider org.apache.spark.h2o.DefaultSource could not be instantiated
    at org.apache.spark.sql.execution.datasources.DataSource.lookupDataSource(DataSource.scala:178)
    at org.apache.spark.sql.execution.datasources.DataSource.providingClass$lzycompute(DataSource.scala:79)
    at org.apache.spark.sql.execution.datasources.DataSource.providingClass(DataSource.scala:79)
    at org.apache.spark.sql.execution.datasources.DataSource.write(DataSource.scala:441)
    at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:213)
    at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:196)
...
```

### CODE REVIEW

**Comment by zsxwing** [comment]
For reviews: use https://github.com/apache/spark/pull/14651/files?w=1 to review the real changes.

**Comment by zsxwing** [comment]
The motivation here is, e.g., if the h2o library is in classpath, even if I don't use it (such as, run `Seq(1).toDS().write.format("parquet").save("foo")`), my code will still fail. The improved error message gives the user a better instruction.

**Comment by zsxwing** [comment]
An alternative fix is just ignoring broken libraries. However, if the user does want to use this library, the exception will be `Failed to find data source: $provider. Please find packages at "http://spark-packages.org"`. It will be confusing because the user already provides the library.

**Comment by yhuai** [comment]
LGTM. Thanks!

**Comment by yhuai** [comment]
Merging to master and branch 2.0.

**Pull request closed without merging**
