### PR TITLE
[SPARK-28371][SQL] Make Parquet "StartsWith" filter null-safe

### PR DESCRIPTION
**Pull request by vanzin**
Parquet may call the filter with a null value to check whether nulls are
accepted. While it seems Spark avoids that path in Parquet with 1.10, in
1.11 that causes Spark unit tests to fail.

Tested with Parquet 1.11 (and new unit test).

### CODE REVIEW

**Comment by vanzin** [comment]
BTW this fix was also part of a separate PR (which has a lot of other changes that are not needed for this): https://github.com/apache/spark/pull/23721/files#diff-67a76299606811fd795f69f8d53b6f2bR594

**Review by dongjoon-hyun — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
cc @gatorsmile and @rdblue

**Comment by rdblue** [comment]
This sounds like a Parquet regression to me. Shouldn't this behavior be changed in Parquet instead?

**Comment by vanzin** [comment]
I was told that this is expected behavior (and a parquet dev pointed me at PARQUET-1489).

**Comment by vanzin** [comment]
(But if this is really a parquet issue then great, just let me know.)

**Comment by vanzin** [comment]
Also FYI the actual Parquet change that introduced the call that triggers the Spark unit test failure is PARQUET-1201.

**Comment by wangyum** [comment]
I try to fix this issue before. more details please see [PARQUET-1488](https://issues.apache.org/jira/browse/PARQUET-1488).

**Comment by rdblue** [comment]
@wangyum, thanks for the additional context. Looks like it was undefined whether a `UserDefinedPredicate` needed to handle null. The requirement was stated only after adding the call with null to check whether a column of all nulls should be kept.

I think this is a regression in Parquet. Parquet should catch exceptions from UserDefinedPredicate and read the row group. That would fix the regression, while allowing Parquet to handle columns of all null values.

At the same time, I think that Spark should update its predicates to handle nulls, so that the filter works correctly. So let's go ahead with this PR and I'll re-open PARQUET-1488.

**Comment by rdblue** [comment]
The change looks correct to me. Is there a test suite for the StartsWith predicate? I'd like to see a test updated as well.

**Comment by vanzin** [comment]
> Is there a test suite for the StartsWith predicate?

Yes, in `ParquetFilterSuite`, but the test only hits the bad code path when you use Parquet 1.11. I don't really know how make the Parquet code call the Spark filter with a `null` in 1.10 (tried a few things to no avail).

But let me see if I can call the Spark code more directly...

**Comment by rdblue** [comment]
+1, thanks for the explanation, @vanzin!

**Comment by vanzin** [comment]
Ok, the added test fails without the fix (even if in "normal" operations everything seems fine with 1.10).

**Review by wangyum — APPROVED** [review]

**Comment by vanzin** [comment]
If anyone is curious, here's the stack trace with 1.10 (which looks like generated code):

```
[info]   Cause: java.lang.NullPointerException:
[info]   at org.apache.spark.sql.execution.datasources.parquet.ParquetFilters$$anon$1.keep(ParquetFilters.scala:616)
[info]   at org.apache.spark.sql.execution.datasources.parquet.ParquetFilters$$anon$1.keep(ParquetFilters.scala:595)
[info]   at org.apache.parquet.filter2.recordlevel.IncrementallyUpdatedFilterPredicateBuilder$50.updateNull(IncrementallyUpdatedFilterPredicateBuilder.java:937)
[info]   at org.apache.parquet.filter2.recordlevel.IncrementallyUpdatedFilterPredicateEvaluator.visit(IncrementallyUpdatedFilterPredicateEvaluator.java:49)
[info]   at org.apache.parquet.filter2.recordlevel.IncrementallyUpdatedFilterPredicate$ValueInspector.accept(IncrementallyUpdatedFilterPredicate.java:122)
[info]   at org.apache.parquet.filter2.recordlevel.IncrementallyUpdatedFilterPredicateEvaluator.evaluate(IncrementallyUpdatedFilterPredicateEvaluator.java:41)
[info]   at org.apache.parquet.filter2.recordlevel.FilteringRecordMaterializer.getCurrentRecord(FilteringRecordMaterializer.java:93)
```

**Review by dongjoon-hyun — APPROVED** [review]

**Review by HyukjinKwon — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you so much, @vanzin , @rdblue , @wangyum , @HyukjinKwon .
Merged to master/2.4.

**Pull request closed without merging**
