### PR TITLE
[MLLIB][SPARK-7615, SPARK-7617, SPARK-7618]: Avoid divided by zero norm, cache normalized Word Vectors

### PR DESCRIPTION
**Pull request by ezli**
1. [SPARK-7615] Commit 8c23ddd: Fix wordVectors divided by norm = 0. Add a ScalaTest for divided by zero scenario;
2. [SPARK-7617] Commit a941a3d: Normalize fVector in findSynonyms() to make cosine distances comparable across all words.
3. [SPARK-7618] Commit 8642ff2: Cache the normalized wordVectors, speed up multiple findSynonyms() calls; Do lazy loading for wordVectors and wordVectorsNormalized;

### CODE REVIEW

**Comment by srowen** [comment]
ok to test

**Comment by mengxr** [comment]
@ezli Thanks for submitting the PR! Please follow https://cwiki.apache.org/confluence/display/SPARK/Spark+Code+Style+Guide for code style and run `dev/lint-scala` to check on your local machine.

**Comment by ezli** [comment]
@mengxr Thanks for your comments. I will check the code style.

**Comment by ezli** [comment]
@mengxr I have fixed the code style. Could you please re-run the tests?

**Comment by srowen** [comment]
@ezli this is pretty old now. Do you intend to update it or close it?

**Comment by ezli** [comment]
I will update this.

**Comment by rxin** [comment]
I'm going to close this pull request. If this is still relevant and you are interested in pushing it forward, please open a new pull request. Thanks!

**Pull request closed without merging**
