### PR TITLE
[SPARK-30825][SQL][DOC] Update documents information for window function.

### PR DESCRIPTION
**Pull request by beliefer**
### What changes were proposed in this pull request?
I checked the all the window function and found all of them not add parameter information and version information to the document.
This PR will make a supplement.

### Why are the changes needed?
Documentation is missing and does not meet new standards.

### Does this PR introduce any user-facing change?
Yes. User will face the information of parameters and version.

### How was this patch tested?
Exists UT

### CODE REVIEW

**Review by HyukjinKwon — COMMENTED** [review]
I am good with this change. cc @hvanhovell

**Comment by beliefer** [comment]
retest this please

**Comment by beliefer** [comment]
retest this please

**Review by srowen — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master and branch-3.0.

**Comment by HyukjinKwon** [comment]
Merged to master and branch-3.0.

**Comment by beliefer** [comment]
@HyukjinKwon @srowen Thanks for your work.

**Pull request closed without merging**
