### PR TITLE
[SPARK-12759][Core][Spark should fail fast if --executor-memory is too small for spark to start]

### PR DESCRIPTION
**Pull request by djalova**
Added an exception to be thrown in UnifiedMemoryManager.scala if the configuration given for executor memory is too low. Also modified the exception message thrown when driver memory is too low.

This patch was tested manually by passing in config options to Spark shell. I also added a test in UnifiedMemoryManagerSuite.scala

### CODE REVIEW

**Comment by andrewor14** [comment]
add to whitelist

**Comment by djalova** [comment]
retest please

**Comment by ajbozarth** [comment]
I checked out the code and tried it out. I tested by running spark-shell with --executor-memory and --driver-memory. I saw the following:
```
16/02/18 14:24:59 ERROR SparkContext: Error initializing SparkContext.
java.lang.IllegalArgumentException: Executor memory 1048576 must be at least 4.718592E8. Please increase executor memory using the --executor-memory option or spark.executor.memory in Spark configuration.
	at org.apache.spark.memory.UnifiedMemoryManager$.getMaxMemory(UnifiedMemoryManager.scala:193)
	at org.apache.spark.memory.UnifiedMemoryManager$.apply(UnifiedMemoryManager.scala:167)
	at org.apache.spark.SparkEnv$.create(SparkEnv.scala:319)
	at org.apache.spark.SparkEnv$.createDriverEnv(SparkEnv.scala:179)
	at org.apache.spark.SparkContext.createSparkEnv(SparkContext.scala:261)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:430)
	at org.apache.spark.repl.Main$.createSparkContext(Main.scala:98)
	at $line3.$read$$iw$$iw.<init>(<console>:12)
	at $line3.$read$$iw.<init>(<console>:22)
	at $line3.$read.<init>(<console>:24)
	at $line3.$read$.<init>(<console>:28)
<...>
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
java.lang.IllegalArgumentException: Executor memory 1048576 must be at least 4.718592E8. Please increase executor memory using the --executor-memory option or spark.executor.memory in Spark configuration.
  at org.apache.spark.memory.UnifiedMemoryManager$.getMaxMemory(UnifiedMemoryManager.scala:193)
  at org.apache.spark.memory.UnifiedMemoryManager$.apply(UnifiedMemoryManager.scala:167)
  at org.apache.spark.SparkEnv$.create(SparkEnv.scala:319)
  at org.apache.spark.SparkEnv$.createDriverEnv(SparkEnv.scala:179)
  at org.apache.spark.SparkContext.createSparkEnv(SparkContext.scala:261)
  at org.apache.spark.SparkContext.<init>(SparkContext.scala:430)
  at org.apache.spark.repl.Main$.createSparkContext(Main.scala:98)
  ... 48 elided
java.lang.NullPointerException
  at org.apache.spark.sql.SQLContext$.createListenerAndUI(SQLContext.scala:1065)
  at org.apache.spark.sql.SQLContext.<init>(SQLContext.scala:75)
  at org.apache.spark.repl.Main$.createSQLContext(Main.scala:112)
  ... 48 elided
<console>:13: error: not found: value sqlContext
       import sqlContext.implicits._
              ^
<console>:13: error: not found: value sqlContext
       import sqlContext.sql
              ^
```
(Note: the <...> is stack trace I deleted to shrink the comment)
Then the shell still starts, is this the intended behavior? it seems clunky, but it's better than the problem just being hidden (which seemed to be how it was before)

**Comment by srowen** [comment]
@djalova what is the status on this one -- @ajbozarth notes that this doesn't actually stop the shell from starting. Maybe that's the best we can do, posting a very noticeable error. Just checking that was your intent.

**Comment by djalova** [comment]
@srowen Yes, that was my intent. I'm not sure if there is a way to stop the Scala shell from starting.

**Comment by ajbozarth** [comment]
If that's the intent, LGTM

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
