### PR TITLE
[SPARK-43973][SS][UI][TESTS][FOLLOWUP][3.4] Fix compilation by switching QueryTerminatedEvent constructor

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This is a follow-up of https://github.com/apache/spark/pull/41468 to fix `branch-3.4`'s compilation issue.

### Why are the changes needed?

To recover the compilation.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?
Pass the CIs.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
cc @rednaxelafx , @gengliangwang , @kazuyukitanimura

**Review by gengliangwang — APPROVED** [review]
Thanks for fixing it!

**Review by kazuyukitanimura — APPROVED** [review]
LGTM (non binding)

**Review by rednaxelafx — APPROVED** [review]
LGTM (non-binding). Thanks a lot for handling the conflict, @dongjoon-hyun ! 🙏

**Pull request closed without merging**
