### PR TITLE
[SPARK-6990] [Build] Add Java linting script; mix minor warnings

### PR DESCRIPTION
**Pull request by dskrvk**
This replaces the botched PR https://github.com/apache/spark/pull/9600

Invoke Checkstyle and print any errors to the console, failing the step.
Use Google's style rules modified according to
https://cwiki.apache.org/confluence/display/SPARK/Spark+Code+Style+Guide
Some important checks are disabled (see TODOs in `checkstyle.xml`) due to
multiple violations being present in the codebase.

Suggest fixing those TODOs in a separate PR(s).

Also fix some of the minor violations that didn't require sweeping changes.

cr: @JoshRosen, @pwendell 

> I state that the contribution is my original work, and I license the work to the project under the project's open source license.

### CODE REVIEW

**Comment by dskrvk** [comment]
Can one of the admins give this a nudge please?

**Comment by JoshRosen** [comment]
Jenkins, this is ok to test.

**Comment by dskrvk** [comment]
Jenkins, retest this please.

**Comment by dskrvk** [comment]
Jenkins, retest this please

**Comment by JoshRosen** [comment]
Jenkins, retest this please.

**Comment by vanzin** [comment]
This PR still looks pretty botched to me. Lots of seemingly unrelated stuff in the patch, lots if weird things (github says "empty file changed"?) and other stuff.

**Comment by dskrvk** [comment]
Yeah, I'm still struggling with the fork syncing workflow. Looks like I'll have to open a new PR yet again to get rid of all those extraneous commits.

**Comment by vanzin** [comment]
Are you sure you're working off the right branch? That's the most common cause of these things; e.g. you're working on branch-1.6 but the PR is against master.

**Comment by dskrvk** [comment]
My setup looks like this:

1. Local master tracks my fork's master.
2. Changes from upstream/master get periodically rebased on top of local master.
3. Local feature branch contains my changes and is being merged into local master before pushing.
4. The PR is master against master.

Is there anything obviously wrong with this workflow?

**Comment by vanzin** [comment]
Sounds similar to what I do, except I don't do step 3 (I just push to a branch on my fork and create a PR from that). Maybe you're doing something wrong in that step (like merging instead of rebasing or something).

**Comment by dskrvk** [comment]
Yes, I believe rebasing instead of merging is the problem since it rewrites history, and if some of the changes I'm rebasing have already been pushed to my remote, it freaks out and creates theses false commits. I'll resubmit a (hopefully) final PR tomorrow.
Sorry everyone.

**Pull request closed without merging**
