### PR TITLE
[SPARK-6293] SQLContext.implicits should provide automatic conversion for RDD[Row]

### PR DESCRIPTION
**Pull request by kaka1992**
Add RDD[Row] implicits change to DataFrame and unit test in DataFrameImplicitsSuite test("RDD[Row]").

### CODE REVIEW

**Comment by yhuai** [comment]
@kaka1992 Most of the time, the schema of a row will be null (actually, only a `GenericRowWithSchema` has a schema). So, I think we cannot add this implicit method.

**Comment by marmbrus** [comment]
ok to test

**Comment by marmbrus** [comment]
I think I agree with @yhuai.  I'm not sure if that test cases is even making the implicit fire.

**Comment by marmbrus** [comment]
As such I would suggest we close this issue.

**Comment by kaka1992** [comment]
Maybe we can rebuild the schema using the exist row when the it doesn't contain schema data.

**Comment by kaka1992** [comment]
I add some code to fix char support in dataTypes when we want to get char schema info.
[SPARK-6412]

**Pull request closed without merging**
