### PR TITLE
[WIP] allow building spark gpu docker images

### PR DESCRIPTION
**Pull request by rongou**
## What changes were proposed in this pull request?

Enhance `bin/docker-image-tool.sh` to allow building GPU images. See https://issues.apache.org/jira/browse/SPARK-26398.

## How was this patch tested?

Docker images are built manually and verified through `docker run`.

### CODE REVIEW

**Review by felixcheung — COMMENTED** [review]
I'm not sure about creating more dockerfile and more output images/types.
I think we have enough work to keep them in sync and maintained as they are...

**Comment by rongou** [comment]
I'm mostly following the current structure. There are a few things that can be done to simplify this and lessen the maintenance burden:
* As I mentioned in the JIRA issue, if we are willing to switch to Ubuntu, both CPU and GPU images can share the same `Dockerfile`, with an argument for different base images.
* Perhaps it's an overkill to have separate JVM/Py/R images, they can be combined into one.
* Spark probably should publish official images to, say, docker hub, so end users can just pull the images directly or use them as base.

**Comment by holdenk** [comment]
Hi @RongGu there's some complications around this. Publishing to docker images as an ASF project is a bit complicated because of GPLd code in the image, I've been meaning to follow up on this but life has been kind of busy. The separate images do seem a bit silly I agree, but the overhead of having a combined image could be non-trivial (e.g. shipping Python to every worker when it's not required.)

I agree with @felixcheung that adding more image types gives us more maintenance burden, if we could simplify this down (maybe have param inside of the other docker files) making it easier for end users to deploy GPU workloads does seem important.

I know @ifilonenko has given a lot of thought about these issues so I'd really value his opinion here.

**Comment by vanzin** [comment]
To be honest, I'm a little wary of the prospect of publishing docker images, not just because of licensing issues. It also means we're on the spot to keep those images up-to-date, e.g. because of security updates in the base images. I generally see the dockerfiles in the distro as "templates" that people could customize to their needs and should manage / publish in their own environments. 

That being said, if we could parameterize things it could be a simple enhancement. Is the base image the only thing that changes in the gpu dockerfiles?

**Comment by rongou** [comment]
@vanzin yes more or less. Since Ubuntu and Alpine use different package managers, the setups are slightly different. If we are willing to use Ubuntu as the base, then I think we can just use one set of dockerfiles and swap out the base image as an arg. Should I give it a try and update this PR?

**Comment by holdenk** [comment]
Swapping the base is a non-trivial change, and if it's what we want to do Spark 3 would probably be the right time to do that but I know some folks have strong opinions about making light-weight base images which Ubuntu might make more challenging (e.g. @ifilonenko @mccheah )?

**Comment by felixcheung** [comment]
I think there are concerns with image size (Ubuntu is much bigger than Alpine) and licensing with Ubuntu as base.

**Comment by tgravescs** [comment]
@felixcheung  do you have specifics about the licensing?  is it with the base licensing?
 
do you know if zeppelin distributes docker images?

The size thing should be easy to check @rongou do you have the size differences in ubuntu vs existing?  I have seen a few things that said a docker image with alpine was quite a bit smaller then ubuntu.

**Comment by ifilonenko** [comment]
There is a considerable size difference between Alpine vs. Ubuntu (~4mb vs. ~120mb). However I am all for having examples of images with GPU support. However, the support for an official Ubuntu based image might be a bit much considering how many images we are already managing. Any chance you can build off of Alpine? At least then it would be a flag you can toggle on the images we already have. I wouldn't recommend to manage nor publish too many base images w.r.t licensing and support issues

**Comment by rongou** [comment]
Building from head, Spark image based on
Alpine: 373MB
Ubuntu 18.04: 617MB

@ifilonenko I was told by the container guys within NVIDIA that Alpine doesn't support NVIDIA drivers.

**Comment by rongou** [comment]
OK, I just pushed a new commit to show what it looks like to use Ubuntu as the base image for both CPU and GPU builds. I think this is cleaner and easier to maintain. What do you all think?

As for licensing, Tensorflow, which is also licensed under Apache 2.0, uses Ubuntu as the base image: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/docker/Dockerfile. It's even published to dockerhub.

**Comment by rongou** [comment]
I think I have a solution to address all the concerns here (well, almost :). By switching the CPU base image to `debian:stretch-slim`, and a couple tricks to trim the image, now the Spark CPU image is 372MB (vs. the Alpine based image that's 345MB). Perhaps that's small enough? Also I assume Debian is less of a concern than Ubuntu for licensing, right?

**Comment by felixcheung** [comment]
Basically, docker image, if published, is similar to convenient binary release and it must not have Catagory X licensed binaries.

http://www.apache.org/legal/resolved#prohibited

“from Category X and that any convenience binaries produced may not include such contents”

Tensorflow is not a ASF project.

Though in any case - I don’t see Spark project is releasing docker images (it’s not on dockerhub) just the Dockerfile (so perhaps that’s not an issue)

**Comment by rongou** [comment]
So basically any docker image based on linux is a no go because of GPL?

In any case, this PR doesn't depend on publishing docker images. I think it's at a stage that can be merged. Can someone please review? Thanks!

**Comment by tgravescs** [comment]
The big thing here I think is the change in the base image.  I don't use the docker image regularly at this point so if people are, are you ok with the base image changing?    @felixcheung @ifilonenko 

This approach is much cleaner then having the multiple docker files but it might depend on what will be most useful to people.

**Comment by mccheah** [comment]
Ubuntu is a really, really big image. I wonder if there's a world where the docker image tool can allow specifying a base image. Then, when the docker image tool runs, it can `sed` the base dockerfile and replace the base image according to the user's request.

We actually propose a similar concept in our Gradle Spark Docker Image plugin: https://github.com/palantir/spark/blob/master/spark-docker-image-generator/src/main/java/org/apache/spark/deploy/kubernetes/docker/gradle/GenerateDockerFileTask.java#L77

**Comment by mccheah** [comment]
I think we want to leave Alpine as the default because it's more lightweight.

**Comment by mccheah** [comment]
Actually we can take a step back here and consider the premise of the change...

I'm not entirely sure if we want to be opinionated towards supporting GPU features in a first-class way in Spark.

If we do that, then what's to stop asks for more features for their custom images, to be built into the Spark ones? For example, how do we decide whether or not we want to include support for particular instrumentation tools? And then as @vanzin has pointed out as well, what if someone wants to use GPU support but doesn't want to use this distribution of Linux? What about other kinds of distributions of Linux that use a different package manager? That requires a different set of Dockerfiles altogether.

To me, the docker image tool and the dockerfile we provide out of the box should be used for the more basic use cases. But the flexibility of Kubernetes allows any user to build their own image however they wish. I think if we optimize for the more general case of building custom images, we'll better support these kinds of features in images without having to make huge Dockerfiles with lots of options.

**Comment by mccheah** [comment]
Something reasonable at a basic level is to support multiple distributions of Linux and have Dockerfiles for each of them. This is a common practice on Dockerhub, for multiple images to be available for different base operating systems. It gets a little messy though because we provide Dockerfiles for the different language bindings as well. So we're multiplying the Dockerfiles we'd have to support in that case.

**Comment by rongou** [comment]
@mccheah with the latest commit this now uses debian slim as the base image for CPUs. The total size is within striking distance of alpine-based image.

I think it was decided that Spark is not going to publish images to docker hub because of licensing constraints. So the shell script and dockerfiles are more of an example than a complete deployment solution. The scenario is different from those projects that support different distributions of linux with the explicit goal to provide ready-to-pull base images.

GPU support is a little trickier because the driver cannot be easily added to all base images, for example, Alpine doesn't support it at all. The easiest approach is to use one of the `nvidia/cuda` images as base, which only support Ubuntu and CentOS. In comparison, other packages (e.g. instrumentation tools) can be easily added as a new layer on top of the base Spark image.

**Comment by mccheah** [comment]
> In comparison, other packages (e.g. instrumentation tools) can be easily added as a new layer on top of the base Spark image.

Because we're not publishing image binaries to Dockerhub, the work required to build a custom image with instrumentation tools is the same amount of work required to change the base image: one creates a Dockerfile, or else modifies the provided Dockerfile in-place, and changes the base image. One can see that being done [here](https://github.com/palantir/spark/blob/master/spark-docker-image-generator/src/main/java/org/apache/spark/deploy/kubernetes/docker/gradle/GenerateDockerFileTask.java#L77), for example (as I've linked above).

So the question is what makes creating a custom image for GPU support that much more difficult than creating a custom image for generally running on Ubuntu or even running on a Fedora image, etc.

**Comment by mccheah** [comment]
One other concern is that adding another option that we say is ready to run out of the box for GPUs, is that we have to maintain this mode and ensure it is tested in CI. Our integration tests cover the use of all the basic Dockerfiles we provide so far, but it can be a poor experience for a user to try to use the GPU option that we haven't tested and they find problems with the GPU integration. Basically this is extra stuff we have to maintain and validate and it's unclear if that's the right direction moving forward, particularly because we're giving GPUs special treatment over other kinds of customizations like OS support.

**Comment by holdenk** [comment]
Maybe while we're discussing this on list we can give this PR a [WIP] tag so folks know to skip it?

**Comment by vanzin** [comment]
Is there any benefit in keeping this PR open until SPARK-24655 is sorted out?

I'm pretty sure we don't want to maintain multiple docker images in the Spark repo.

**Comment by vanzin** [comment]
I'm going to close this for now. Let's focus on defining what images should be before going too crazy changing how many combinations are maintained in the Spark repo.

**Pull request closed without merging**
