### PR TITLE
[SPARK-29565][FOLLOWUP] add setInputCol/setOutputCol in OHEModel

### PR DESCRIPTION
**Pull request by huaxingao**
### What changes were proposed in this pull request?
add setInputCol/setOutputCol in OHEModel

### Why are the changes needed?
setInputCol/setOutputCol should be in OHEModel too.

### Does this PR introduce any user-facing change?
Yes. 
```OHEModel.setInputCol```
```OHEModel.setOutputCol```

### How was this patch tested?
Manually tested.

### CODE REVIEW

**Comment by huaxingao** [comment]
@zhengruifeng

**Comment by zhengruifeng** [comment]
LGTM

**Comment by zhengruifeng** [comment]
Merged to master

**Comment by huaxingao** [comment]
Thank you very much!!

**Pull request closed without merging**
