### PR TITLE
[SPARK-12074] Avoid memory copy involving ByteBuffer.wrap(ByteArrayOutputStream.toByteArray)

### PR DESCRIPTION
**Pull request by tedyu**
SPARK-12060 fixed JavaSerializerInstance.serialize
This PR applies the same technique on two other classes.

@zsxwing

### CODE REVIEW

**Comment by tedyu** [comment]
```
Had test failures in pyspark.streaming.tests with python2.6; see logs.
```
I don't think the above failure was caused this PR

**Comment by tedyu** [comment]
Jenkins, retest this please.

**Comment by zsxwing** [comment]
LGTM pending tests

**Comment by zsxwing** [comment]
LGTM. Merging to master

**Comment by zsxwing** [comment]
Thanks @tedyu

**Pull request closed without merging**
