### PR TITLE
[SPARK-26671][CORE][Minor] Enviroment page in the webui need to display hadoop properties in only in history the ui

### PR DESCRIPTION
**Pull request by shahidki31**
## What changes were proposed in this pull request?
This PR has 3 minor fixes related to the environment page in the webui
1) In local mode, don't show default hadoop properties
2) If the "hadoop properties" is empty, don't display empty table in the env page
3) Show "hadoop properties" only in the history application page

## How was this patch tested?

Existing tests

### CODE REVIEW

**Comment by shahidki31** [comment]
cc @srowen kindly review.

**Comment by srowen** [comment]
Do we need to hide them in local mode? They still matter. Spark uses Hadoop APIs and some Hadoop configs for reading data, and those would be relevant in any deployment context.

**Comment by shahidki31** [comment]
> Do we need to hide them in local mode? They still matter. Spark uses Hadoop APIs and some Hadoop configs for reading data, and those would be relevant in any deployment context.
okay. fine. The actual problem was, Env page displaying all the default hadoop configurations in local mode, including yarn configs. okay. Will update the pr.

**Comment by felixcheung** [comment]
I'm not sure I see the problem. if the config is in fact there, showing it seem like a good idea. yes it might be there it's local deploy mode and it's not using the yarn config, but that seems like a subtle thing. hadoop config is still used even if it's not "hadoop" because for things like hadoop filesystem etc that is everywhere (like Sean says)

**Comment by shahidki31** [comment]
Okay. Then I can close the PR. Thanks for the clarification.

**Pull request closed without merging**
