### PR TITLE
[SPARK-2199] [mllib] topic modeling

### PR DESCRIPTION
**Pull request by akopich**
I have implemented Probabilistic Latent Semantic Analysis (PLSA) and Robust PLSA with support of additive regularization (that actually means that I've implemented Latent Dirichlet Allocation too).

### CODE REVIEW

**Comment by jkbradley** [comment]
@akopich  I had hoped to get this into MLlib, but after more consideration, I believe it is too complex.  Currently, what would be ideal is a simple implementation of LDA since that is all that most users need.  While generalizations like robust PLSA may outperform LDA with proper tuning, it’s somewhat of a research area, and it may be better to go with LDA since it has been very widely tested and used.

However, I am sure some users would want to use your implementation of Robust PLSA, so it would be valuable for you to make it available as a package for Spark.

The best path right now, I believe, will be to create a simple PR with a minimal public API, where that API should be extensible with (a) extra parameters/features and (b) alternate optimization/learning algorithms.  I've posted a public design doc on the LDA JIRA [here](https://issues.apache.org/jira/browse/SPARK-1405), and I’m going to submit such a PR.  I would of course appreciate your feedback on it.  Thanks very much for your understanding.

When we merge the initial LDA PR, @mengxr will be sure to include all of those who have participated as authors of Spark LDA PRs: @akopich @witgo @yinxusen @dlwh @EntilZha @jegonzal

CC: @mengxr

**Comment by akopich** [comment]
@jkbradley, @mengxr, please, include @IlyaKozlov as author too. He's helped a lot with the implementation.

**Comment by jkbradley** [comment]
@akopich   We'll make sure to do that.  Thanks for letting us know.

**Comment by jkbradley** [comment]
@IlyaKozlov  Would you like your email included in the git commit for the initial LDA PR?  If so, please let me (or @mengxr ) know ASAP.  Thanks!

**Comment by renchengchang** [comment]
how to assign document id?

**Comment by renchengchang** [comment]
@akopich how to assign document id?

**Comment by akopich** [comment]
@renchengchang 
1. Hi.
2. Don't use code from this PR. Use either LDA (which is merged with mllib) or https://github.com/akopich/dplsa which is a further development of this PR. 
3. I do not employ the concept of document id.

**Comment by renchengchang** [comment]
Thanks.
I have a question:
if there is not document id ,how can I know the relation between topic vector and raw text?

发件人: Avanesov Valeriy [mailto:notifications@github.com]
发送时间: 2015年3月10日 21:18
收件人: apache/spark
抄送: 任成常
主题: [营销类邮件] Re: [spark] [SPARK-2199] [mllib] topic modeling (#1269)


@renchengchang<https://github.com/renchengchang>
1. Hi.
2. Don't use code from this PR. Use either LDA (which is merged with mllib) or https://github.com/akopich/dplsa which is a further development of this PR.
3. I do not employ the concept of document id.

**Comment by akopich** [comment]
@renchengchang 
What do you mean by "topic vector"? A vector of p(t|d) \forall t?  If so, you can find these vectors in `RDD[DocumentParameters]` which is returned by `infer(documents: RDD[Document], ...)` method. `DocumentParameters` stores a document a vector of p(t|d) \forall t which is referred as `theta`. BTW, the order of documents is remained the same.

**Comment by jkbradley** [comment]
@akopich  Since this is no longer an active PR, could you please close it?

It was very helpful to have this PR as a major basis for the initial LDA PR.  If you do end up using the merged LDA or future versions which may be added, it would be great to get your input about further improvements, especially if they can be added incrementally.  There are people actively working on online variational Bayes and on Gibbs sampling, which should have very different behavior from EM.

**Pull request closed without merging**
