### PR TITLE
[SPARK-23871][ML][PYTHON]add python api for VectorAssembler handleInvalid

### PR DESCRIPTION
**Pull request by huaxingao**
## What changes were proposed in this pull request?

add python api for VectorAssembler handleInvalid

## How was this patch tested?

Add doctest

### CODE REVIEW

**Comment by jkbradley** [comment]
LGTM
But would you mind making one fix in the doc here and in Scala?  "Param for how to handle invalid data (NULL values)" should actually read "Param for how to handle invalid data (NULL **and NaN** values)"

Thanks!

**Comment by huaxingao** [comment]
@jkbradley Thanks for your comment. I will add "and NaN" in the doc.

**Comment by jkbradley** [comment]
Merging with master
Thanks @huaxingao !

**Comment by huaxingao** [comment]
@jkbradley Thank you very much for your help!

**Pull request closed without merging**
