### PR TITLE
[SPARK-5908][SQL] Resolve UdtfsAlias when only single Alias is used

### PR DESCRIPTION
**Pull request by viirya**
`ResolveUdtfsAlias` in `hiveUdfs` only considers the `HiveGenericUdtf` with multiple alias. When only single alias is used with `HiveGenericUdtf`, the alias is not working.

### CODE REVIEW

**Comment by viirya** [comment]
There is another problem previously posted in #5907. Because this two prs have to be addressed together. So I close #5907 and merge two prs.

**Comment by viirya** [comment]
Since #4686 updated DataFrame API, the issue of #4691 is not a problem now. Only keep the commit of hiveUdfs.

**Comment by viirya** [comment]
@marmbrus Please take a look. Thanks!

**Comment by viirya** [comment]
cc @marmbrus.

**Comment by viirya** [comment]
@marmbrus, @liancheng May you take a look of this pr? It should be straightforward. Thanks!

**Comment by marmbrus** [comment]
Sure, we'll get back to reviewing and merging more PRs as soon as the Spark
1.3 release is out the door.

**Comment by viirya** [comment]
Hi @marmbrus, Are you available to go with this pr now? Thanks!

**Comment by marmbrus** [comment]
Thanks!  Merging to master.

**Pull request closed without merging**
