### PR TITLE
[SPARK-18500][SQL] Make GenericStrategy be able to prune plans by itself after placeholders are replaced.

### PR DESCRIPTION
**Pull request by ueshin**
## What changes were proposed in this pull request?

This pr adds a functionality to `GenericStrategy` to be able to prune bad physical plans by itself after their placeholders are replaced.

## How was this patch tested?

Added a test to check if the strategy can prune plans by itself.

### CODE REVIEW

**Comment by ueshin** [comment]
@marmbrus Could you review this pr please?

**Comment by ueshin** [comment]
Jenkins, retest this please.

**Comment by ueshin** [comment]
Jenkins, retest this please.

**Comment by ueshin** [comment]
Jenkins, retest this please.

**Comment by gatorsmile** [comment]
cc @ueshin

**Comment by ueshin** [comment]
I'd close this for now.

**Pull request closed without merging**
