### PR TITLE
[MiNOR][DOCS] Fix a typo in HashAggregateExec.scala

### PR DESCRIPTION
**Pull request by neshkeev**
### What changes were proposed in this pull request?

The patch contains just a small typo fix in a code commentary: `had be` -> `has been`

### Why are the changes needed?

The changes aim to keep the code base free of typos, which simplifies reading the source code by human beings

### Does this PR introduce _any_ user-facing change?

These changes don't introduce any user-facing changes

### How was this patch tested?

The changes relate to a commentary in code, so I assumed no testing required, since the main logic left untouched.

### Was this patch authored or co-authored using generative AI tooling?

This patch was created without any cooperation with any AI tooling

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Mind taking a look at https://github.com/apache/spark/pull/42916/checks?check_run_id=16774936333, and keeping the PR description template https://github.com/apache/spark/blob/master/.github/PULL_REQUEST_TEMPLATE?

**Review by HyukjinKwon — APPROVED** [review]

**Review by yaooqinn — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
@neshkeev once you set up your github acitons in your fork, please rebase this so the test is retriggered.

**Comment by neshkeev** [comment]
@HyukjinKwon , the actions workflows are designed to run when a new pull request appears that is based on a branch inside the `apache/spark` repository, the workflows don't expect contribution from outside repositories apparently. I will look into amending the workflows to accommodate the scenario when a pull request is based on a branch from an outside repository.

**Comment by HyukjinKwon** [comment]
We have our own logic to detect forked repostiories' github actions run. You would need to go to settings in your forked repo, and enable it. For now, seems I can't find the Githuh Actions runs in your repo:

Screenshot 2023-09-20 at 4 25 57 PM

**Pull request closed without merging**
