### PR TITLE
[SPARK-45973][SPARK-45982][INFRA][FOLLOWUPS] Restore apt-get/r installations for branch-3.3/3.4/3.5

### PR DESCRIPTION
**Pull request by zhengruifeng**
### What changes were proposed in this pull request?
Restore apt-get/r installations for branch-3.3/3.4/3.5

### Why are the changes needed?
to restore daily builds for branch-3.3/3.4/3.5

### Does this PR introduce _any_ user-facing change?
no

### How was this patch tested?
ci

### Was this patch authored or co-authored using generative AI tooling?
no

### CODE REVIEW

**Comment by zhengruifeng** [comment]
cc @LuciferYang @dongjoon-hyun

**Comment by LuciferYang** [comment]
Is the maintenance cost high if these two patches are backported to branch-3.x?

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by dongjoon-hyun** [comment]
This one is better, @LuciferYang .

**Comment by dongjoon-hyun** [comment]
Merged to master to recover the reported issues. Thank you, @LuciferYang and @zhengruifeng .

**Comment by zhengruifeng** [comment]
> Is the maintenance cost high if these two patches are backported to branch-3.x?

I think so, BTW we already adopt such way to fix python linter:
```
    - name: Install Python linter dependencies for branch-3.3
      if: inputs.branch == 'branch-3.3'
      run: ...
    - name: Install Python linter dependencies for branch-3.4
      if: inputs.branch == 'branch-3.4'
      run: ...
    - name: Install Python linter dependencies for branch-3.5
      if: inputs.branch == 'branch-3.5'
      run: ...
    - name: Install Python linter dependencies
      if: inputs.branch != 'branch-3.3' && inputs.branch != 'branch-3.4' && inputs.branch != 'branch-3.5'
      run: ...
    - name: Python linter
      run: PYTHON_EXECUTABLE=python3.9 ./dev/lint-python
    - name: Install dependencies for Python code generation check
      if: inputs.branch != 'branch-3.3' && inputs.branch != 'branch-3.4'
      run: ...
```

**Pull request closed without merging**
