### PR TITLE
[SPARK-23863] [SQL] Wholetext mode should not add line breaks

### PR DESCRIPTION
**Pull request by barrenlake**
## What changes were proposed in this pull request?

Writes the WholeTextMode  Param to the InternalRow,  and making a logical decision to determine whether to write a newline character when writing.

## How was this patch tested?

Add unit tests

Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Comment by barrenlake** [comment]
please help to review, thanks!

**Comment by barrenlake** [comment]
@HyukjinKwon  Hello, the unit test describes the scene where this problem occurred. You can run the unit test in the original system. Spark2.3 introduced `wholetext` ( default `false`): If true, read a file as a single row and not split by "\n". So, read the textual content in wholetext mode and  write the content to a new file directly, there is no need to add "\n".

**Comment by HyukjinKwon** [comment]
I am sorry, the unit test uses many private classes, and I think I am not getting the point of this change. Do you mind if I ask some code snippets? 

I think `wholetext` is not related in write path and wonder why it matters here.

**Comment by barrenlake** [comment]
@HyukjinKwon  Oh yes, you are right. This problem was encountered when I added the small file merge function to the Hive module. When I used select count(1) to count the merge result file, I found that the number of wholetext lines was inconsistent with the original. So I submitted this issue. I didn't realize that I would use a private object until I saw you reply. I apologize for taking up your valuable time and offer my heartfelt thanks to you.

**Pull request closed without merging**
