### PR TITLE
[SPARK-18013][SPARKR] add crossJoin API

### PR DESCRIPTION
**Pull request by felixcheung**
## What changes were proposed in this pull request?

Add crossJoin and do not default to cross join if joinExpr is left out
## How was this patch tested?

unit test

### CODE REVIEW

**Comment by rxin** [comment]
cc @srinathshankar

**Review by srinathshankar — APPROVED** [review]
LGTM

**Comment by felixcheung** [comment]
I made some improvements to error handling and added more tests, this should be ready to go.

**Comment by felixcheung** [comment]
merged to master, thanks

**Pull request closed without merging**
