### PR TITLE
[Minor] Fix import order and other coding style

### PR DESCRIPTION
**Pull request by Bilna**
fixed import order and other coding style

### CODE REVIEW

**Comment by rxin** [comment]
Jenkins, test this please.

**Comment by srowen** [comment]
I think the stance has been to avoid one-off non-functional style changes for their own sake, as it buys almost nothing and costs time to review/test/resolve merge conflicts.

If this were going to proceed, I would say you should also squash the ~20 commits here to one.

**Comment by rxin** [comment]
@srowen this one might be ok since it is limited to a smaller scope - but I agree in general it is not a good idea to do massive style changes. When we merge, the merge script does automatic squash, so that it is not a huge problem here (but still would be nice if pr owners can squash for clarity in general).

**Comment by andrewor14** [comment]
Ok, this one doesn't seem too invasive so I will go ahead and merge it in master. Thanks.

**Pull request closed without merging**
