### PR TITLE
[SPARK-28811][DOCS][SQL] Document SHOW TBLPROPERTIES in SQL Reference

### PR DESCRIPTION
**Pull request by dilipbiswal**
### What changes were proposed in this pull request?
Document SHOW TBLPROPERTIES statement in SQL Reference Guide. 

### Why are the changes needed?
Currently Spark lacks documentation on the supported SQL constructs causing
confusion among users who sometimes have to look at the code to understand the
usage. This is aimed at addressing this issue.

### Does this PR introduce any user-facing change?
Yes. 

**Before:**
There was no documentation for this.

**After.**
image
Screen Shot 2019-09-04 at 11 32 11 AM

### How was this patch tested?
Tested using jykyll build --serve

### CODE REVIEW

**Comment by dilipbiswal** [comment]
cc @srowen @gatorsmile

**Comment by dongjoon-hyun** [comment]
Could you add tags to the PR title please, @dilipbiswal ?

**Comment by dilipbiswal** [comment]
@dongjoon-hyun You mean the [DOC] after the JIRA ? Is that the tag you r referring to ?

**Comment by dongjoon-hyun** [comment]
`DOC` and `SQL`?

**Comment by dilipbiswal** [comment]
@dongjoon-hyun Got it.. Thanks a lot.

**Review by gatorsmile — COMMENTED** [review]
updated the PR description. 

LGTM

Thanks! Merged to master

**Pull request closed without merging**
