### PR TITLE
[SPARK-40265][PS] Fix the inconsistent behavior for Index.intersection.

### PR DESCRIPTION
**Pull request by itholic**
### What changes were proposed in this pull request?

This PR proposes to fix the inconsistent behavior for `Index.intersection` function as below:

When `other` is list of tuple, the behavior of pandas API on Spark is difference from pandas.

- pandas API on Spark
```python
>>> psidx
Int64Index([1, 2, 3, 4], dtype='int64', name='Koalas')
>>> psidx.intersection([(1, 2), (3, 4)]).sort_values()
MultiIndex([], )
```

- pandas
```python
>>> pidx
Int64Index([1, 2, 3, 4], dtype='int64', name='Koalas')
>>> pidx.intersection([(1, 2), (3, 4)]).sort_values()
Traceback (most recent call last):
...
ValueError: Names should be list-like for a MultiIndex
```

### Why are the changes needed?

To reach parity with pandas.

### Does this PR introduce _any_ user-facing change?

Yes, the behavior of `Index.intersection` is chaged, when the `other` is list of tuple:

- Before
```python
>>> psidx
Int64Index([1, 2, 3, 4], dtype='int64', name='Koalas')
>>> psidx.intersection([(1, 2), (3, 4)]).sort_values()
MultiIndex([], )
```

- After
```python
>>> psidx
Int64Index([1, 2, 3, 4], dtype='int64', name='Koalas')
>>> psidx.intersection([(1, 2), (3, 4)]).sort_values()
Traceback (most recent call last):
...
ValueError: Names should be list-like for a MultiIndex
```

### How was this patch tested?

Added a unit test.

### CODE REVIEW

**Review by zhengruifeng — APPROVED** [review]

**Comment by zhengruifeng** [comment]
what if the `psidx` itself is a `MultiIndex`?

```
>>> psidx
Int64Index([1, 2, 3, 4], dtype='int64', name='Koalas')
>>> psidx.intersection([(1, 2), (3, 4)]).sort_values()
MultiIndex([], )
```

**Comment by itholic** [comment]
> what if the `psidx` itself is a `MultiIndex`?
> 
> ```
> >>> psidx
> Int64Index([1, 2, 3, 4], dtype='int64', name='Koalas')
> >>> psidx.intersection([(1, 2), (3, 4)]).sort_values()
> MultiIndex([], )
> ```

@zhengruifeng Seems like the `psidx` in your example is still using `Index` rather than `MultiIndex` ?

Maybe do you mean:

```python
>>> psmidx
MultiIndex([(1, 2),
            (3, 4)],
           )
>>> psmidx.intersection([(1, 2), (3, 4)]).sort_values()
MultiIndex([(1, 2),
            (3, 4)],
           )
```

??

In this case, it works same as pandas as below:

```python
>>> psmidx.to_pandas().intersection([(1, 2), (3, 4)])
MultiIndex([(1, 2),
            (3, 4)],
           )
```

**Comment by zhengruifeng** [comment]
got it, `MultiIndex` has its own `intersection` method

**Comment by zhengruifeng** [comment]
Merged to master, thank you @itholic !

**Comment by itholic** [comment]
Thanks for the review, @zhengruifeng !

**Pull request closed without merging**
