### PR TITLE
[SPARK-33831][UI] Update to jetty 9.4.34

### PR DESCRIPTION
**Pull request by srowen**
### What changes were proposed in this pull request?

Update Jetty to 9.4.34

### Why are the changes needed?

Picks up fixes and improvements, including a possible CVE fix.

https://github.com/eclipse/jetty.project/releases/tag/jetty-9.4.33.v20201020
https://github.com/eclipse/jetty.project/releases/tag/jetty-9.4.34.v20201102

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by maropu** [comment]
retest this please

**Review by dongjoon-hyun — COMMENTED** [review]
Thanks, @srowen . The behavior of Jetty seems to change. This fails at
```scala
      // Test Jetty's built-in redirect to add the trailing slash to the context path.
      TestUtils.withHttpConnection(new URL(s"$serverAddr/ctx1")) { conn =>
        assert(conn.getResponseCode() === HttpServletResponse.SC_FOUND)
        val location = Option(conn.getHeaderFields().get("Location"))
          .map(_.get(0)).orNull
        assert(location === s"$proxyRoot/ctx1/")
      }
```

Could you check the root cause and adjust some configuration or the UT `UiSuite.redirect with proxy server support`? It would be great if we have the same behavior, but if it's inevitable, shall we add some comment on the migration guide?
```scala
[info] - redirect with proxy server support *** FAILED *** (32 milliseconds)
[info]   404 did not equal 302 (UISuite.scala:367)
```

**Comment by srowen** [comment]
Weird, doesn't happen on the previous 9.4.34 version. I'll just go with that for now, because either:
- It's a bug in the Spark Jetty code, which I'd punt on this moment as I just want to backport fixes back to 2.x, and want to minimize change
- Or, maybe it's an unintentional change that a slightly later Jetty will fix anyway

**Review by dongjoon-hyun — APPROVED** [review]
Thank you for updates, @srowen .
+1, LGTM (Pending CIs).

**Comment by dongjoon-hyun** [comment]
cc @HyukjinKwon since he is the release manager of Apache Spark 3.2.0.

**Review by HyukjinKwon — APPROVED** [review]
LGTM too. Thanks @dongjoon-hyun for cc'ing me.

**Comment by dongjoon-hyun** [comment]
Merged to master/3.1/3.0/2.4. Thanks.

**Pull request closed without merging**
