### PR TITLE
[Minor][streaming][MQTT streaming example] some trivial fixes

### PR DESCRIPTION
**Pull request by prabeesh**
modified to adhere to accepted coding standards as pointed by  @tdas in PR #3844

### CODE REVIEW

**Comment by srowen** [comment]
I'm not sure about most of these.

- Why is tempDir a field?
- _ is more idiomatic in Scala than null for a reference field's default value.
- Why remove the call to disconnect? almost seems like it should be in a finally block
- The regex change alters the functionality. I think "word count" examples across the world split on space.
- It's probably fine to resume one MqttMessage int he loop but are you sure?

**Comment by prabeesh** [comment]
- the hard code '\tmp' may be creating garbage. so created temp directory using internal methods and deleting after the use.
- revert to _
- added the finally block 
- revert to " " 
- In while loop, the MqttMessage object is getting created so many times. here just send same messages repeatedly

**Comment by srowen** [comment]
@prabeesh my question about `/tmp` was why it is not a local variable.

**Comment by prabeesh** [comment]
@srowen  made it as local variable.

**Comment by prabeesh** [comment]
@rxin  please review this

**Pull request closed without merging**
