### PR TITLE
[SPARK-8117] [SQL] Push codegen implementation into each Expression

### PR DESCRIPTION
**Pull request by rxin**
This PR move codegen implementation of expressions into Expression class itself, make it easy to manage.

It introduces two APIs in Expression:

```
def gen(ctx: CodeGenContext): GeneratedExpressionCode
def genCode(ctx: CodeGenContext, ev: GeneratedExpressionCode): Code
```

gen(ctx) will call genSource(ctx, ev) to generate Java source code for the current expression. A expression needs to override genSource().

Here are the types:

```
type Term String
type Code String

/**
 * Java source for evaluating an [[Expression]] given a [[Row]] of input.
 */
case class GeneratedExpressionCode(var code: Code,
                               nullTerm: Term,
                               primitiveTerm: Term,
                               objectTerm: Term)
/**
 * A context for codegen, which is used to bookkeeping the expressions those are not supported
 * by codegen, then they are evaluated directly. The unsupported expression is appended at the
 * end of `references`, the position of it is kept in the code, used to access and evaluate it.
 */
class CodeGenContext {
  /**
   * Holding all the expressions those do not support codegen, will be evaluated directly.
   */
  val references: Seq[Expression] = new mutable.ArrayBuffer[Expression]()
}
```

This is basically #6660, but fixed style violation and compilation failure.

### CODE REVIEW

**Comment by rxin** [comment]
cc @davies I have a big followup pr to move a lot of expression test code for better grouping.

**Comment by davies** [comment]
@rxin Should we merge this one first?

**Comment by rxin** [comment]
Yes -- except it is failing tests :(

**Comment by rxin** [comment]
cc @liancheng  why is partitioning suites failing?

**Comment by rxin** [comment]
Jenkins, retest this please.

**Comment by rxin** [comment]
@liancheng The failure is due to double type vs float type under the hood. What I don't get is that how come this code was passing before?!

Should we parse 1.5 as double type, or float type?

**Comment by rxin** [comment]
I filed https://github.com/apache/spark/pull/6692 to always use DoubleType. It's much simpler to have only one type for floating point numbers, rather than having to reason about float vs double.

**Comment by liancheng** [comment]
@rxin The test failure was because this PR overrides `Literal.equals` which [uses `value.equals(o.value)`] [1]. A quick Scala REPL check:

```
scala> 1.5 == 1.5f
res2: Boolean = true

scala> 1.5.equals(1.5f)
res3: Boolean = false
```

[1]: https://github.com/apache/spark/pull/6690/files#diff-f52e4a77ff9291d86359d609a9757781R85

**Comment by rxin** [comment]
It's a problem of the test case that manifests from this.

We shouldn't use a double value in the place where we intend to have a float value. Let's be more careful with that in the future.

**Pull request closed without merging**
