### PR TITLE
[SPARK-40419][SQL][TESTS][FOLLOWUP] Remove results/udaf.sql.out

### PR DESCRIPTION
**Pull request by MaxGekk**
### What changes were proposed in this pull request?
Remove the file `results/udaf.sql.out` because it is not generated anymore after https://github.com/apache/spark/pull/37873.

### Why are the changes needed?
The duplicate file might confuse while searching some text in golden files.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
By running the affected test suite:
```
$ PYSPARK_PYTHON=python3 build/sbt "sql/testOnly org.apache.spark.sql.SQLQueryTestSuite"
```

### CODE REVIEW

**Comment by MaxGekk** [comment]
@itholic Could you look at this PR since it is related to your PR (reviewed by @HyukjinKwon).

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Review by HyukjinKwon — COMMENTED** [review]
LGTM2!

**Comment by itholic** [comment]
Sorry for confirming late, LGTM.

**Pull request closed without merging**
