### PR TITLE
SPARK-4579 [WEBUI] Scheduling Delay appears negative

### PR DESCRIPTION
**Pull request by srowen**
Ensure scheduler delay handles unfinished task case, and ensure delay is never negative even due to rounding

### CODE REVIEW

**Comment by kayousterhout** [comment]
LGTM Thanks @srowen !

**Comment by pwendell** [comment]
Jenkins, test this please.

**Comment by pwendell** [comment]
Yeah this would be great to pull into an RC... a very confusing presentation in the UI right now!

**Comment by andrewor14** [comment]
Ok I've pulled this into master and 1.3 thanks.

**Pull request closed without merging**
