### PR TITLE
[SPARK-50477][INFRA] Add a separate docker file for python 3.9 daily build

### PR DESCRIPTION
**Pull request by zhengruifeng**
### What changes were proposed in this pull request?
Add a separate docker file for python 3.9 daily build

### Why are the changes needed?
to isolate the environments

### Does this PR introduce _any_ user-facing change?
no, infra-only

### How was this patch tested?
ci, the second commit and the 4-th commit tested this PR against the new image

https://github.com/zhengruifeng/spark/actions/runs/12135050296/job/33835846375

https://github.com/zhengruifeng/spark/actions/runs/12140138335/job/33850700922

### Was this patch authored or co-authored using generative AI tooling?
no

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Are you aiming to split all Python versions, @zhengruifeng ?

**Comment by zhengruifeng** [comment]
yes, @dongjoon-hyun I plan to split them all

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by dongjoon-hyun** [comment]
BTW, please double-check all CIs after merging this, @zhengruifeng . We frequently broke other CIs.

**Comment by zhengruifeng** [comment]
> BTW, please double-check all CIs after merging this, @zhengruifeng . We frequently broke other CIs.

Sure, I will keep an eye on other CIs.

**Comment by panbingkun** [comment]
late LGTM.

**Comment by LuciferYang** [comment]
late LGTM, Thank @zhengruifeng

**Pull request closed without merging**
