### PR TITLE
[WIP][SPARK-27562][Shuffle]Complete the verification mechanism for shuffle transmitted data

### PR DESCRIPTION
**Pull request by turboFei**
## What changes were proposed in this pull request?

We've seen some shuffle data corruption during shuffle read phase. 

As described in SPARK-26089, spark only checks small  shuffle blocks before PR #23453, which is proposed by ankuriitg.

There are two changes/improvements that are made in PR #23453.

1. Large blocks are checked upto maxBytesInFlight/3 size in a similar way as smaller blocks, so if a
large block is corrupt in the starting, that block will be re-fetched and if that also fails,
FetchFailureException will be thrown.
2. If large blocks are corrupt after size maxBytesInFlight/3, then any IOException thrown while
reading the stream will be converted to FetchFailureException. This is slightly more aggressive
than was originally intended but since the consumer of the stream may have already read some records and processed them, we can't just re-fetch the block, we need to fail the whole task. Additionally, we also thought about maybe adding a new type of TaskEndReason, which would re-try the task couple of times before failing the previous stage, but given the complexity involved in that solution we decided to not proceed in that direction.

However, I think there still exists some problems with the current shuffle transmitted data verification mechanism:

- For a large block, it is checked upto  maxBytesInFlight/3 size when fetching shuffle data. So if a large block is corrupt after size maxBytesInFlight/3, it can not be detected in data fetch phase.  This has been described in the previous section.
- Only the compressed or wrapped blocks are checked, I think we should also check thease blocks which are not wrapped.

This pr complete the verification mechanism for shuffle transmitted data:

Firstly, crc32 is choosed for the checksum verification  of shuffle data.

Crc is also used for checksum verification in hadoop, it is simple and fast.

During shuffle write phase, after completing the partitionedFile, we compute 

the crc32 value for each partition and then write these digests with the indexs into shuffle index file.

For the sortShuffleWriter and unsafe shuffle writer, there is only one partitionedFile for a shuffleMapTask, so the compution of digests(compute the digests for each partition depend on the indexs of this partitionedFile) is  cheap.

For the bypassShuffleWriter, the reduce partitions is little than byPassMergeThreshold, so the cost of digests compution is acceptable.

During shuffle read phase, the digest value will be passed with the block data.

And we will recompute the digest of the data obtained to compare with the origin digest value.
When recomputing the digest of data obtained, it only need an additional buffer(2048Bytes) for computing crc32 value.
After recomputing, we will reset the obtained data inputStream, if it is markSupported we only need reset it, otherwise it is a fileSegmentManagerBuffer, we need recreate it.

So, I think this verification mechanism  proposed for shuffle transmitted data is efficient and complete.

## How was this patch tested?

Unit test.

### CODE REVIEW

**Comment by turboFei** [comment]
@squito  Could you help to review this?

**Comment by turboFei** [comment]
@attilapiros @srowen

**Comment by squito** [comment]
HI @turboFei thanks for posting this.  Have you looked at [SPARK-26089](https://issues.apache.org/jira/browse/SPARK-26089) yet?  That actually addresses two out of your three concerns: 

* only check the first maxBytesInFlight/3 bytes.
* need additional memory.

I'm not saying there is not value here -- that change does not handle the 3rd one "only detect the compressed or wrapped data."  I also have always worried about whether it really makes sense to rely on the the codec to detect corruption, so using a digest could also make sense.  But, this is a large change, so the case should be made clearly.

**Comment by squito** [comment]
@ankuriitg

**Comment by squito** [comment]
oops, I just noticed you actually used that jira for this change.  So clearly if we were going to do this, you should open another jira and explain the case for having a checksum.  or also happy to hear if there is some mistake in the change already committed for SPARK-26089: https://github.com/apache/spark/commit/688b0c01fac0db80f6473181673a89f1ce1be65b

**Comment by turboFei** [comment]
> oops, I just noticed you actually used that jira for this change. So clearly if we were going to do this, you should open another jira and explain the case for having a checksum. or also happy to hear if there is some mistake in the change already committed for SPARK-26089: [688b0c0](https://github.com/apache/spark/commit/688b0c01fac0db80f6473181673a89f1ce1be65b)

Thanks, I will open another jira and make the case clearly.

**Comment by turboFei** [comment]
@squito I have created a new jira[SPARK-27562] and [describe the schema](https://github.com/apache/spark/pull/24447#issue-272954941).

**Comment by turboFei** [comment]
@jerryshao

**Comment by turboFei** [comment]
@cloud-fan Could you help to review this? I think this pr can guarantee the accuracy of shuffle data transmission.

**Comment by jerryshao** [comment]
This seems to be a quite useful feature in heavy load production environment. We're also suffering from such shuffle issue, I think this is a valuable improvement.

@turboFei will you continue to work on this PR? If so, I'm going to reopen and help to review it.

**Comment by cloud-fan** [comment]
This is a nice feature. We need to think about how to integrate it with the batch shuffle fetch though.

**Comment by turboFei** [comment]
I will try to finish it. Please help reopen it, thanks.

**Comment by jerryshao** [comment]
Not sure why this PR is closed again, I'm gonna reopen it. @turboFei seems there's  lots conflicts in code, can you please bring this to the latest?

**Comment by turboFei** [comment]
I will.

**Comment by turboFei** [comment]
It seems that we have to recompute the digest when fetching continuous blocks data.

**Comment by turboFei** [comment]
The behavior of bot is strange, have created a new pr, https://github.com/apache/spark/pull/28525

**Pull request closed without merging**
