### PR TITLE
[WIP][SPARK-41100][INFRA] Upgrade Ubuntu to latest

### PR DESCRIPTION
**Pull request by bjornjorgensen**
### What changes were proposed in this pull request?
Upgrade ubuntu version on runners in github actions from 20.04 to latest

### Why are the changes needed?
"[Ubuntu 22.04 is now generally available on GitHub-hosted runners. To use it now, simply add runs-on: ubuntu-22.04 in your workflow file. Otherwise, our recommendation is to use ubuntu-latest, which currently utilizes Ubuntu 20.04 but will begin running on Ubuntu 22.04 in the near future.](https://github.blog/changelog/2022-08-09-github-actions-ubuntu-22-04-is-now-generally-available-on-github-hosted-runners/)" 

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA

### CODE REVIEW

**Comment by bjornjorgensen** [comment]
@Yikun

**Comment by Yikun** [comment]
I think we should upgrade to `22.04` when github action `ubuntu-latest` point to 22.04, rather than use the `ubuntu-latest` directly, to reduce the potential impacts of OS upgrade breaking change.

You could try to use `ubuntu-22.04` in this PR, once latest upgrade we can merge then.

**Comment by bjornjorgensen** [comment]
https://github.com/gregrahn/tpcds-kit/issues/57

**Comment by bjornjorgensen** [comment]
@Yikun 
[GitHub Actions: Larger Runners using Ubuntu-latest label will now use Ubuntu-22.04](https://github.blog/changelog/2022-12-01-github-actions-larger-runners-using-ubuntu-latest-label-will-now-use-ubuntu-22-04/)

**Comment by Yikun** [comment]
Looks like only tpcds test has some impact, After tpcds bug fixed, we can switch then.


I think Ubuntu 20.04  will also have good supported before Apr 2025.

https://ubuntu.com/about/release-cycle

also cc @HyukjinKwon

**Comment by bjornjorgensen** [comment]
Yes, I will close this PR for now.

**Pull request closed without merging**
