### PR TITLE
[SPARK-13194][BUILD] Update release audit tools to use Scala 2.11

### PR DESCRIPTION
**Pull request by lresende**

### CODE REVIEW

**Comment by JoshRosen** [comment]
Jenkins, this is ok to test.

**Comment by rxin** [comment]
@lresende thanks for doing this. Please merge the relevant pull requests into a single one.

**Comment by srowen** [comment]
@lresende why are there 5 JIRAs now... This is definitely not needed. As Reynold says you should have made one PR

**Comment by lresende** [comment]
@rxin this is now merged into #11092

**Pull request closed without merging**
