### PR TITLE
[SPARK-9000][MLlib]Support generic item type in PrefixSpan

### PR DESCRIPTION
**Pull request by rikima**
modify to support generic item type according to the FPGrowth.

### CODE REVIEW

**Comment by mengxr** [comment]
@rikima I need to hold this PR because we are waiting for changes SPARK-8999, which would change the API. Sorry that I didn't link the JIRA correctly. For this PR, we only need to collect the frequent items (of generic type) to local and then convert items in the input dataset to indices. The implementation is still on integer items, similar to our implementation of `FPGrowth`.

I will ping you when we are ready to work on this.

**Comment by rikima** [comment]
@mengxr Thank you for commenting. I got it. 
I'm sorry that I make a mistake for JIRA number.  I've corrected.

**Comment by feynmanliang** [comment]
Hi @rikima 

I resolved your merge conflicts with the latest version of master on #7837 

Since I cherry-picked your commit your name will be in the commit log.

**Comment by rikima** [comment]
Hi @feynmanliang 
Thank you for informing me and including my tiny modifications.  I think that PrefixSpan for spark is really great function.

**Pull request closed without merging**
