### PR TITLE
[SPARK-8837][SPARK-7114][SQL] support using keyword in column name

### PR DESCRIPTION
**Pull request by cloud-fan**

### CODE REVIEW

**Comment by cloud-fan** [comment]
cc @rxin

**Comment by cloud-fan** [comment]
retest this please.

**Comment by rxin** [comment]
cc @marmbrus

**Comment by marmbrus** [comment]
Thanks!  Merging to master.

**Comment by marmbrus** [comment]
Actually apache is down... will merge when its back up...

**Comment by rxin** [comment]
git is back. I've merged this.

**Pull request closed without merging**
