### PR TITLE
[SPARK-25671] Build external/spark-ganglia-lgpl in Jenkins Test

### PR DESCRIPTION
**Pull request by gatorsmile**
## What changes were proposed in this pull request?
Currently, we do not build external/spark-ganglia-lgpl in Jenkins tests when the code is changed. 

## How was this patch tested?
N/A

### CODE REVIEW

**Comment by gatorsmile** [comment]
```
[error] /home/jenkins/workspace/SparkPullRequestBuilder/external/spark-ganglia-lgpl/src/main/scala/org/apache/spark/metrics/sink/GangliaSink.scala:72: value xyz is not a member of object java.util.Locale
[error]     .map(u => TimeUnit.valueOf(u.toUpperCase(Locale.xyz)))
[error]                                                     ^
[error] one error found
```

**Comment by gatorsmile** [comment]
cc @zsxwing @cloud-fan @HyukjinKwon

**Comment by gatorsmile** [comment]
Also cc @yhuai @liancheng @srowen

**Comment by gatorsmile** [comment]
Locale.ROOT has been fixed as a hot-fix.

**Review by srowen — APPROVED** [review]

**Comment by gatorsmile** [comment]
Thanks! Merged to master/2.4

**Review by HyukjinKwon — COMMENTED** [review]
LGTM

**Pull request closed without merging**
