### PR TITLE
[SPARK-25262][DOC][FOLLOWUP] Fix link tags in html table

### PR DESCRIPTION
**Pull request by viirya**
## What changes were proposed in this pull request?

Markdown links are not working inside html table. We should use html link tag.

## How was this patch tested?

Verified in IntelliJ IDEA's markdown editor and online markdown editor.

### CODE REVIEW

**Comment by viirya** [comment]
cc @rvesse @mccheah @dongjoon-hyun

**Comment by felixcheung** [comment]
@ifilonenko @liyinan926

**Review by felixcheung — APPROVED** [review]

**Review by HyukjinKwon — APPROVED** [review]
LGTM

**Comment by HyukjinKwon** [comment]
Also manually verified:

Before:

screen shot 2018-09-29 at 6 16 46 pm

After:

screen shot 2018-09-29 at 6 17 44 pm

**Review by dongjoon-hyun — COMMENTED** [review]
Late LGTM. Thank you for pinging me.

**Pull request closed without merging**
