### PR TITLE
[SPARK-4600][GraphX]: org.apache.spark.graphx.VertexRDD.diff does not work

### PR DESCRIPTION
**Pull request by brennonyork**
Turns out, per the [convo on the JIRA](https://issues.apache.org/jira/browse/SPARK-4600), `diff` is acting exactly as should. It became a large misconception as I thought it meant set difference, when in fact it does not. To that extent I merely updated the `diff` documentation to, hopefully, better reflect its true intentions moving forward.

### CODE REVIEW

**Comment by brennonyork** [comment]
ok to test

**Comment by srowen** [comment]
LGTM, straightforward doc update.

**Pull request closed without merging**
