### PR TITLE
[SPARK-22410][SQL] Remove unnecessary output from BatchEvalPython's children plans

### PR DESCRIPTION
**Pull request by viirya**
## What changes were proposed in this pull request?

When we insert `BatchEvalPython` for Python UDFs into a query plan, if its child has some outputs that are not used by the original parent node, `BatchEvalPython` will still take those outputs and save into the queue. When the data for those outputs are big, it is easily to generate big spill on disk.

For example, the following reproducible code is from the JIRA ticket.

```python
from pyspark.sql.functions import *
from pyspark.sql.types import *

lines_of_file = [ "this is a line" for x in xrange(10000) ]
file_obj = [ "this_is_a_foldername/this_is_a_filename", lines_of_file ]
data = [ file_obj for x in xrange(5) ]

small_df = spark.sparkContext.parallelize(data).map(lambda x : (x[0], x[1])).toDF(["file", "lines"])
exploded = small_df.select("file", explode("lines"))

def split_key(s):
    return s.split("/")[1]

split_key_udf = udf(split_key, StringType())

with_filename = exploded.withColumn("filename", split_key_udf("file"))
with_filename.explain(True)
```

The physical plan before/after this change:

Before:

```
*Project [file#0, col#5, pythonUDF0#14 AS filename#9]
+- BatchEvalPython [split_key(file#0)], [file#0, lines#1, col#5, pythonUDF0#14]
   +- Generate explode(lines#1), true, false, [col#5]
      +- Scan ExistingRDD[file#0,lines#1]

```

After:

```
*Project [file#0, col#5, pythonUDF0#14 AS filename#9]
+- BatchEvalPython [split_key(file#0)], [col#5, file#0, pythonUDF0#14]
   +- *Project [col#5, file#0]
      +- Generate explode(lines#1), true, false, [col#5]
         +- Scan ExistingRDD[file#0,lines#1]
```

Before this change, `lines#1` is a redundant input to `BatchEvalPython`. This patch removes it by adding a Project.

## How was this patch tested?

Manually test.

### CODE REVIEW

**Comment by viirya** [comment]
retest this please.

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by viirya** [comment]
Seems like a valid error. Checking.

**Comment by HyukjinKwon** [comment]
Ah, I rushed to retrigger .. it has been being failed unexpected globally somehow ..

**Comment by viirya** [comment]
retest this please.

**Comment by viirya** [comment]
retest this please.

**Comment by HyukjinKwon** [comment]
FWIW, I asked this to Jenkins admin. Looks the problem is, the launch script is ran by Python 2.6 from dropping the path in some Jenkins machines, assuming from the quick look for the log. I explicitly printed this message before - https://github.com/apache/spark/pull/19524. Quick observation is these happen in worker 2, 6, and 7.

**Comment by viirya** [comment]
retest this please.

**Comment by viirya** [comment]
hmm, it occurs frequently.

**Comment by viirya** [comment]
retest this please.

**Comment by viirya** [comment]
cc @cloud-fan @ueshin

**Comment by cloud-fan** [comment]
how could this happen? the column pruning rule doesn't work? Can you give a concreate example?

**Comment by viirya** [comment]
Because adjacent Projects are combined, so an underlying Project used to prune columns didn't work.

```
== Analyzed Logical Plan ==
file: string, col: string, filename: string
Project [file#0, col#5, split_key(file#0) AS filename#9]
+- Project [file#0, col#5]
   +- Generate explode(lines#1), true, false, [col#5]
      +- LogicalRDD [file#0, lines#1], false

== Optimized Logical Plan ==
Project [file#0, col#5, split_key(file#0) AS filename#9]
+- Generate explode(lines#1), true, false, [col#5]
   +- LogicalRDD [file#0, lines#1], false

== Physical Plan ==
*Project [file#0, col#5, pythonUDF0#14 AS filename#9]
+- BatchEvalPython [split_key(file#0)], [file#0, lines#1, col#5, pythonUDF0#14]
   +- Generate explode(lines#1), true, false, [col#5]
      +- Scan ExistingRDD[file#0,lines#1]
```

**Comment by cloud-fan** [comment]
I see, is it better to introduce a logical python runner then we can do column pruning correctly?

**Comment by viirya** [comment]
To have a logical python runner, we may need to change some logic of extracting python udfs. May require quite more change than this simple fix. If you prefer it, I can do it. If it is just for column pruning, I'd prefer not to do it. Because this sounds more like execution details more than logical query plan. But I also like to hear others ideas too. @HyukjinKwon what do you think?

**Comment by cloud-fan** [comment]
why is column pruning execution details? Actually I feel it's werid to have `ExtractPythonUDFs` rule applying on physical plans, is there a particular reason?

**Comment by HyukjinKwon** [comment]
For the answer to https://github.com/apache/spark/pull/19642#issuecomment-341688601,

> To have a logical python runner, we may need to change some logic of extracting python udfs. May require quite more change than this simple fix.

I think in the same way, up to my little knowledge.

**Comment by viirya** [comment]
I mean to have an individual python runner operator tells the way we execute python udfs. Currently python udfs are just normal expressions. It seems to me that logically they are just expressions.

Not sure why `ExtractPythonUDFs` are applying on physical plans.

**Comment by viirya** [comment]
To have a python runner operator also has advantage like to work with optimizer better, e.g. column pruning. I am not against this idea. However, since it requires more change, I'd like to have more support before beginning the change.

**Comment by viirya** [comment]
Another concern is, by seeing python udfs as normal expressions without specific operator, we can apply necessary optimization such as CollapseProject. If we extract python udfs earlier in logical plan, we might have multiple python runners that were collapsed originally now.

To deal with it, we may need to add specific optimization rule for collapsing python runners.

This adds more complexity, IMHO. We should consider if it's worth.

**Comment by viirya** [comment]
About why `ExtractPythonUDFs` applies on physical plans, I think it may partly because the wrapper of Python function `PythonFunction` also encapsulates core concepts like `Broadcast` and `Accumulator`, it is out of the scope of catalyst APIs.

**Comment by cloud-fan** [comment]
ah this makes sense, then LGTM.

One thing we can think more is, `Project` is not only an operator but also a column pruning info, this may bring trouble if `Project` can't be whole stage codegened and run as a real operator(python runner).

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Comment by HyukjinKwon** [comment]
Late LGTM too.

**Comment by viirya** [comment]
Thanks @HyukjinKwon @cloud-fan for your review!

**Pull request closed without merging**
