### PR TITLE
[SPARK-3000][CORE] drop old blocks to disk in parallel when free memory is not enough for caching new blocks

### PR DESCRIPTION
**Pull request by liyezhang556520**
Currently, old blocks dropping for new blocks' caching are processed by one thread at the same time. Which can not fully utilize the disk throughput. If the to be dropped block size is huge, then the dropping time will be very long. We need to make it processed in parallel. In this patch, dropping blocks operation are processed in multiple threads, before dropping, each thread will select the blocks that to be dropped for itself.

### CODE REVIEW

**Comment by liyezhang556520** [comment]
Hi @andrewor14 , I don't know if you have reproduced this issue. Since I know most of your cases are tested on Amazon EC2 which are equipped with SSD. And even one SSD's throughput may can be up to more than 3 HDDs' . So that this problem may not that obvious on your cluster.

**Comment by andrewor14** [comment]
@liyezhang556520 I would like to fix the issue you raised in #1165 first (i.e. SPARK-4777) before looking at SPARK-3000, which seems to me more like an optimization. Let's agree on a solution in #3629 before making more progress in this PR, since it seems that there are logical conflicts between the two PRs.

**Comment by liyezhang556520** [comment]
jenkins, retest this please

**Comment by andrewor14** [comment]
@liyezhang556520 this issue has mostly gone stale at this point, and I'm not sure if it's applicable anymore given some of the latest changes in master. Unfortunately I won't have the bandwidth to review this further and push this patch forward. I think we should close this patch for now and reopen it later if there's interest.

**Comment by liyezhang556520** [comment]
ok, I'll close this PR

**Pull request closed without merging**
