### PR TITLE
[SPARK-35311][SS][UI][DOCS] Structured Streaming Web UI state information documentation

### PR DESCRIPTION
**Pull request by gaborgsomogyi**
### What changes were proposed in this pull request?
In this PR I'm adding Structured Streaming Web UI state information documentation.

### Why are the changes needed?
Missing documentation.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
```
cd docs/
SKIP_API=1 bundle exec jekyll build
```
Manual webpage check.

### CODE REVIEW

**Comment by gaborgsomogyi** [comment]
cc @gatorsmile @HeartSaVioR

**Review by HeartSaVioR — APPROVED** [review]
+1

I'll merge in tomorrow if there's no further comment.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

cc @viirya

**Review by viirya — APPROVED** [review]
lgtm

**Comment by viirya** [comment]
BTW, shall we also update the screenshot? Current one doesn't show the added statistics but just original ones.

**Comment by HeartSaVioR** [comment]
Nice catch! 
@gaborgsomogyi Shall we update the screenshot as well? Thanks!

**Comment by gaborgsomogyi** [comment]
@HeartSaVioR @viirya till now I was fighting to make a screenshot from the whole UI part but I don't have such big screen so I've added an additional image where the rest can be seen.

**Comment by gaborgsomogyi** [comment]
The alternative was to zoom out in the screen but then the UI was super tiny, hard to read and just ugly.

**Comment by HeartSaVioR** [comment]
Thanks for the update! Looks great.

@viirya Could you please go through the next round of reviews? If there's no additional feedback I'll merge this at the end of the week.

**Comment by HeartSaVioR** [comment]
Thanks @gaborgsomogyi ! Merged to master.

**Review by viirya — COMMENTED** [review]
sorry for late. lgtm.

**Pull request closed without merging**
