### PR TITLE
[SPARK-38219][SPARK-37691][3.3] Support ANSI Aggregation Function: percentile_cont and percentile_disc

### PR DESCRIPTION
**Pull request by beliefer**
### What changes were proposed in this pull request?
This PR backport https://github.com/apache/spark/pull/35531 and https://github.com/apache/spark/pull/35041 to branch-3.3

### Why are the changes needed?
`percentile_cont` and `percentile_disc` in Spark3.3 release.

### Does this PR introduce _any_ user-facing change?
'No'.
New feature.

### How was this patch tested?
New tests.

### CODE REVIEW

**Comment by beliefer** [comment]
ping @cloud-fan

**Comment by HyukjinKwon** [comment]
Hm, we don't usually backport new features. Is there a reason for this?

**Comment by beliefer** [comment]
> Hm, we don't usually backport new features. Is there a reason for this?

It seems committers forgot merge feature into branch-3.3

**Comment by HyukjinKwon** [comment]
I meant that they were likely intentionally merged to `master` branch only because it's a new feature.

**Comment by HyukjinKwon** [comment]
Oh okay, I missed that this was already discussed in dev mailing list to add it. LGTM

**Review by cloud-fan — APPROVED** [review]

**Comment by cloud-fan** [comment]
thanks, merging to 3.3!

**Comment by beliefer** [comment]
@cloud-fan @HyukjinKwon Thank you.

**Pull request closed without merging**
