### PR TITLE
[SPARK-21449][SPARK-23745][SQL] add ShutdownHook to cloes HiveClient's SessionState to delete residual dirs

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

We initialized a Hive `SessionState` to interact with the external hive metastore server but left it behind after we finished.

We should close the metastore client explicitly in case of connection leaks with HMS
and we should trigger the `SessionState` to close itself to clean the residual dirs to fix issues reported by SPARK-21449 and SPARK-23745.

`hive.downloaded.resources.dir` contains transient files, such as UDF jars, it will not be used anymore after spark applications exit. 

### Why are the changes needed?

1. prevent potential metastore client leak

2. clean `hive.downloaded.resources.dir`

```
    DOWNLOADED_RESOURCES_DIR("hive.downloaded.resources.dir", "${system:java.io.tmpdir}" + File.separator + "${hive.session.id}_resources", "Temporary local directory for added resources in the remote file system."),

```
### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

passing jenkins and verify locally

### CODE REVIEW

**Comment by yaooqinn** [comment]
cc @cloud-fan @HyukjinKwon @gatorsmile @ulysses-you 

also cc @samartinucci,  @liufengdb the reviews from https://github.com/apache/spark/pull/18666

**Comment by yaooqinn** [comment]
retest this please

**Review by cloud-fan — APPROVED** [review]

**Comment by yaooqinn** [comment]
thanks for approving

**Review by dongjoon-hyun — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
cc @wangyum

**Review by wangyum — APPROVED** [review]

**Comment by wangyum** [comment]
Merged to master.

**Pull request closed without merging**
