### PR TITLE
[SPARK-33213][BUILD] Upgrade Apache Arrow to 2.0.0

### PR DESCRIPTION
**Pull request by sunchao**
### What changes were proposed in this pull request?

This upgrade Apache Arrow version from 1.0.1 to 2.0.0

### Why are the changes needed?

Apache Arrow 2.0.0 was released with some improvements from Java side, so it's better to upgrade Spark to the new version.
Note that the format version in Arrow 2.0.0 is still 1.0.0 so API should still be compatible between 1.0.1 and 2.0.0.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Existing UTs.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Yey! Thank you so much, @sunchao !

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
Please run the following and add the updated dependency manifest.
```
dev/test-dependencies.sh --replace-manifest
```

**Comment by HyukjinKwon** [comment]
cc @BryanCutler FYI

**Comment by sunchao** [comment]
> Please run the following and add the updated dependency manifest.
> 
> ```
> dev/test-dependencies.sh --replace-manifest
> ```

Oops forgot about this. Updated. Thanks @dongjoon-hyun .

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @sunchao .

**Comment by dongjoon-hyun** [comment]
The first commit already passed all tests except `Dependency Test` and the second commit only fixed the dependency test. 
Merged to master for Apache Spark 3.1.0.

**Review by BryanCutler — COMMENTED** [review]
LGTM!

**Pull request closed without merging**
