### PR TITLE
[SPARK-19025][SQL] Remove SQL builder for operators

### PR DESCRIPTION
**Pull request by jiangxb1987**
## What changes were proposed in this pull request?

With the new approach of view resolution, we can get rid of SQL generation on view creation, so let's remove SQL builder for operators.

Note that, since all sql generation for operators is defined in one file (org.apache.spark.sql.catalyst.SQLBuilder), it’d be trivial to recover it in the future.

## How was this patch tested?

N/A

### CODE REVIEW

**Comment by hvanhovell** [comment]
cc @rxin @yhuai wdyt? Should we be bold and remove this?

**Comment by hvanhovell** [comment]
LGTM. I'd like to wait a little with merging this in order to build some consensus.

**Comment by hvanhovell** [comment]
I had an offline discussion with @rxin about this, and we have decided to merge this one.

**Comment by gatorsmile** [comment]
Now, we can also remove the generated sqlgen files.

**Comment by passionke** [comment]
@jiangxb1987 

"With the new approach of view resolution, we can get rid of SQL generation on view creation, so let's remove SQL builder for operators."

can you introduce more abount "view resolution"? In my situation, I will use spark with logicalplan optimizer to build better logicalplan, and transfer this logicalplan back to sql for executing outside by spark, such as odps in alibaba etc.

so, can you give me some suggestion for my task? thanks very much!

**Comment by passionke** [comment]
@gatorsmile @ hvanhovell @rxin @ @yhuai

**Pull request closed without merging**
