### PR TITLE
[SPARK-44353][CONNECT][SQL] Remove StructType.toAttributes

### PR DESCRIPTION
**Pull request by hvanhovell**
### What changes were proposed in this pull request?
This PR removes StructType.toAttribute. It is being replace by DataTypeUtils.toAttribute(..).

### Why are the changes needed?
We want to move the DataType hierarchy into sql/api. We need to remove any catalyst specific API.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Existing tests.

### CODE REVIEW

**Comment by hvanhovell** [comment]
cc @amaliujia

**Review by amaliujia — APPROVED** [review]
LGTM. +1 to move the deps over `AttributeReference` to `DataTypeUtils`

**Comment by hvanhovell** [comment]
Merging. Failure is related to ongoing buf work.

**Comment by beliefer** [comment]
It seems remove StructType.toAttributes will lead to break change.
Users always use this method.

**Pull request closed without merging**
