### PR TITLE
[SPARK-47328][SQL] Rename UCS_BASIC collation to UTF8_BINARY

### PR DESCRIPTION
**Pull request by stefankandic**
### What changes were proposed in this pull request?

Change utf8 collation names from 'UCS_BASIC' to 'UTF8_BINARY'.

### Why are the changes needed?

To have the name better describe the actual meaning of the default collation.

### Does this PR introduce _any_ user-facing change?

Yes, now we have different names for utf8 collation

### How was this patch tested?

With existing unit tests.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by MaxGekk** [comment]
cc @srielau

**Comment by srielau** [comment]
A concern was raised that UCS_BASIC which is the order imposed by the Unicode codepoints is not an exact match to the sort order of UTF8 once you get beyond 32k.

**Review by MaxGekk — CHANGES_REQUESTED** [review]
The test failure is related to your changes, it seems. @stefankandic Could you fix it, please:
```
[info] - select_collated_string *** FAILED *** (4 milliseconds)
[info]   com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
[info]   at com.google.protobuf.InvalidProtocolBufferException.invalidTag(InvalidProtocolBufferException.java:110)
[info]   at com.google.protobuf.CodedInputStream$StreamDecoder.readTag(CodedInputStream.java:2084)
```

**Review by MaxGekk — APPROVED** [review]

**Comment by MaxGekk** [comment]
+1, LGTM. Merging to master.
Thank you, @stefankandic and @srielau for review.

**Pull request closed without merging**
