### PR TITLE
[SPARK-21721][SQL][Backport-2.1][Followup] Clear FileSystem deleteOnExit cache when paths are successfully removed 

### PR DESCRIPTION
**Pull request by viirya**
## What changes were proposed in this pull request?

Fix a typo in test.

## How was this patch tested?

Jenkins tests.

### CODE REVIEW

**Comment by viirya** [comment]
cc @cloud-fan

**Comment by cloud-fan** [comment]
LGTM

**Comment by cloud-fan** [comment]
thanks, merging to 2.1

**Comment by viirya** [comment]
Thanks @cloud-fan

**Pull request closed without merging**
