### PR TITLE
[SPARK-38807][CORE] Fix the startup error of spark shell on Windows

### PR DESCRIPTION
**Pull request by 1104056452**
### What changes were proposed in this pull request?
The File.getCanonicalPath method will return the drive letter in the windows system. The RpcEnvFileServer.validateDirectoryUri method uses the File.getCanonicalPath method to process the baseuri, which will cause the baseuri not to comply with the URI verification rules. For example, the / classes is processed into F: \ classes.This causes the sparkcontext to fail to start on windows.
This PR modifies the RpcEnvFileServer.validateDirectoryUri  method and replaces `new File(baseUri).getCanonicalPath`   with 
 `new URI(baseUri).normalize().getPath`. This method can work normally in windows.

### Why are the changes needed?
Fix the startup error of spark shell on Windows system
[[SPARK-35691](https://issues.apache.org/jira/browse/SPARK-35691)] introduced this regression.

### Does this PR introduce any user-facing change?
No

### How was this patch tested?
CI

### CODE REVIEW

**Comment by 1104056452** [comment]
@HyukjinKwon  It has been revised according to your suggestion. 
mind taking a look when you find some time please.  Thank you very much 🙏

**Comment by 1104056452** [comment]
cc @Ngone51 @jiangxb1987 @xuanyuanking, could you please help review this PR? Thanks.

**Review by Ngone51 — APPROVED** [review]

**Comment by srowen** [comment]
The windows tests failed, but, it appears unrelated?

**Comment by HyukjinKwon** [comment]
Yup, that test is broken a while ago..

**Comment by srowen** [comment]
Merged to master/3.3/3.2

**Pull request closed without merging**
