### PR TITLE
[SPARK-8051] [MLLIB] make StringIndexerModel silent if input column does not exist

### PR DESCRIPTION
**Pull request by mengxr**
This is just a workaround to a bigger problem. Some pipeline stages may not be effective during prediction, and they should not complain about missing required columns, e.g. `StringIndexerModel`. @jkbradley

### CODE REVIEW

**Comment by jkbradley** [comment]
As long as this is aimed at 1.4.1 (not 1.4.0), should we design a better fix?  My suggestion would be to have PipelineStage include a Param specifying whether to use it during transform().  Stages could be used in transform() by default, but certain Transformers could override the default to skip during transform().  PipelineModel could read the Param and handle each stage accordingly.

If that's too big a change for 1.4.1, then this temp fix seems tolerable.

Note: We should document the behavior in the docs.

**Comment by mengxr** [comment]
I checked the transformers we have. Perhaps this is the only one that would operate on target labels, and it is blocking users from making predictions without labels. So it would be nice to merge this fix into branch-1.4, before 1.4.1 is out.

**Comment by jkbradley** [comment]
LGTM pending tests

**Comment by jkbradley** [comment]
test this please

**Comment by jkbradley** [comment]
Merging with master and branch-1.4

**Pull request closed without merging**
