### PR TITLE
[SPARK-43373][SQL] Revert [SPARK-39203][SQL] Rewrite table location to absolute URI based on database URI

### PR DESCRIPTION
**Pull request by cloud-fan**
### What changes were proposed in this pull request?

This reverts https://github.com/apache/spark/pull/36625 and its followup https://github.com/apache/spark/pull/38321 .

### Why are the changes needed?

External table location can be arbitrary and has no connection with the database location. It can be wrong to qualify the external table location based on the database location.

If a table written by old Spark versions does not have a qualified location, there is no way to restore it as the information is already lost. People can manually fix the table locations assuming they are under the same HDFS cluster with the database location, by themselves.

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

N/A

### CODE REVIEW

**Comment by cloud-fan** [comment]
cc @wangyum

**Review by HyukjinKwon — APPROVED** [review]

**Review by wangyum — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master and branch-3.4.

**Comment by HyukjinKwon** [comment]
Actually ... we need a JIRA since this change is in 3.4.1 but the original change remains in 3.4.0 .. so difficult to set the fixed JRIA version.

**Comment by dongjoon-hyun** [comment]
Too bad.

To @cloud-fan , as Hyukjin mentioned, we should not revert like this after the official release.

cc @sunchao

**Comment by cloud-fan** [comment]
I've created a new JIRA ticket

**Pull request closed without merging**
