### PR TITLE
[SPARK-33071][SPARK-33536][SQL][FOLLOW-UP] Rename deniedMetadataKeys to nonInheritableMetadataKeys in Alias

### PR DESCRIPTION
**Pull request by HyukjinKwon**
### What changes were proposed in this pull request?

This PR is a followup of https://github.com/apache/spark/pull/30488. This PR proposes to rename `Alias.deniedMetadataKeys` to `Alias.nonInheritableMetadataKeys` to make it less confusing.

### Why are the changes needed?

To make it easier to maintain and read.

### Does this PR introduce _any_ user-facing change?

No. This is rather a code cleanup.

### How was this patch tested?

Ran the unittests written in the previous PR manually. Jenkins and GitHub Actions in this PR should also test them.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @cloud-fan and @Ngone51 can you take a look please?

**Comment by HyukjinKwon** [comment]
Had a short offline discussion with @cloud-fan. Let me just rename the variables to make to address my own concern with a minimized fix.

**Review by cloud-fan — APPROVED** [review]

**Review by Ngone51 — APPROVED** [review]
LGTM. Thanks!

**Comment by HyukjinKwon** [comment]
Merged to master and branch-3.1.

**Comment by HyukjinKwon** [comment]
Thanks @cloud-fan and @Ngone51

**Pull request closed without merging**
