### PR TITLE
[SPARK-8998][MLlib] Collect enough frequent prefixes before projection in PrefixSpan

### PR DESCRIPTION
**Pull request by zhangjiajin**
Add feature: Collect enough frequent prefixes before projection in PrefixSpan.

### CODE REVIEW

**Comment by zhangjiajin** [comment]
@mengxr This PR includes the previous PR. Maybe the previous PR have not be properly closed.

**Comment by mengxr** [comment]
The Apache GitHub is out of sync. You can try to close this PR and re-open it. It might help.

**Comment by mengxr** [comment]
Btw, you shouldn't work directly on your master branch. Instead, you should create a separate branch for each issue, and send pull request from that branch.

**Comment by mengxr** [comment]
@zhangjiajin Let's close this PR and re-submit a PR from a different branch.

**Comment by zhangjiajin** [comment]
@mengxr OK

**Pull request closed without merging**
