### PR TITLE
[SPARK-16558][Examples][MLlib] examples/mllib/LDAExample should use MLVector instead of MLlib Vector

### PR DESCRIPTION
**Pull request by yinxusen**
## What changes were proposed in this pull request?

mllib.LDAExample uses ML pipeline and MLlib LDA algorithm. The former transforms original data into MLVector format, while the latter uses MLlibVector format.
## How was this patch tested?

Test manually.

### CODE REVIEW

**Comment by yinxusen** [comment]
Ping @mengxr @srowen

**Comment by MLnick** [comment]
The fix LGTM - I'm in two minds about whether this example is "good" (illustrating using both `ml` and `mllib` APIs together) or "bad" (for the same reason, since there is LDA available in `ml`).

And we already have a `LatentDirichletExample` in `mllib`... seems to me that these `mllib` examples could use a clean up.

**Comment by yinxusen** [comment]
@MLnick They serve different purpose. This one is for users who have built their tools upon it. The `LatentDirichletAllocationExample` is for ML docs.

**Comment by yanboliang** [comment]
LGTM, merged into master/branch-2.0. Thanks!

**Pull request closed without merging**
