### PR TITLE
[SPARK-14098][SQL] Generate Java code that gets a float/double value in each column of CachedBatch when DataFrame.cache() is called

### PR DESCRIPTION
**Pull request by kiszk**
## What changes were proposed in this pull request?

This PR generates Java code to get a float/double value of each column from CachedBatch when DataFrame.cache() is called. This is done in whole stage code generation.

When DataFrame.cache() is called, data is stored as column-oriented storage (columnar cache) in CachedBatch. This PR avoid conversion from column-oriented storage to row-oriented storage.

This PR handles only float and double that are stored in a column without compression. Another PR will handle other primitive types that may be stored in a column in a compressed format. This is for ease of review by reducing the size of PR

This PR consists of two parts.
1. Pass data in CachedBatch to generated code by using `decompress()` method. CachedBatch consists of multiple ByteBuffer arrays. A ByteBuffer is just passed to generated code.
2. Generate code both for row-oriented storage and column-oriented storage only if
   - InMemoryColumnarTableScan exists in a plan sub-tree. A decision is performed by checking an given iterator is ColumnaIterator at runtime
   - Sort or join does not exist in a plan sub-tree. 

This PR generates Java code for columnar cache only if types in all columns, which are accessed in operations, are primitive

This PR improves performance of aggregate sum by 3.8x - 5.2x. This benchmark is available at [here](https://github.com/kiszk/spark/blob/SPARK-14098/sql/core/src/test/scala/org/apache/spark/sql/DataFrameCacheBenchmark.scala)

Performance results:

```
Java HotSpot(TM) 64-Bit Server VM 1.8.0_66-b17 on Linux 2.6.32-504.el6.x86_64
Intel(R) Xeon(R) CPU E5-2667 v2 @ 3.30GHz

Running benchmark: Double Sum with PassThrough cache
  Running case: InternalRow codegen
  Running case: ColumnVector codegen

Double Sum with PassThrough cache:  Best/Avg Time(ms)    Rate(M/s)   Per Row(ns)   Relative
-------------------------------------------------------------------------------------------
InternalRow codegen                       334 /  342         47.1          21.2       1.0X
ColumnVector codegen                       88 /   99        179.1           5.6       3.8X

Running benchmark: Float Sum with PassThrough cache
  Running case: InternalRow codegen
  Running case: ColumnVector codegen

Float Sum with PassThrough cache:   Best/Avg Time(ms)    Rate(M/s)   Per Row(ns)   Relative
-------------------------------------------------------------------------------------------
InternalRow codegen                       473 /  485         66.5          15.0       1.0X
ColumnVector codegen                       91 /   95        345.6           2.9       5.2X
```

Motivating example:

```
val df = sc.parallelize(0 to 9, 1).map(i => i.toFloat).toDF()
df.cache().filter("value <= 5.1").show()
```

Generated code

``` java
/* 001 */ public Object generate(Object[] references) {
/* 002 */   return new GeneratedIterator(references);
/* 003 */ }
/* 004 */
/* 005 */ /** Codegened pipeline for:
/* 006 */ * Filter (value#1 <= 5.1)
/* 007 */ +- INPUT
/* 008 */ */
/* 009 */ final class GeneratedIterator extends org.apache.spark.sql.execution.BufferedRowIterator {
/* 010 */   private Object[] references;
/* 011 */   private scala.collection.Iterator inputadapter_input;
/* 012 */   private org.apache.spark.sql.execution.metric.LongSQLMetric filter_numOutputRows;
/* 013 */   private org.apache.spark.sql.execution.metric.LongSQLMetricValue filter_metricValue;
/* 014 */   private UnsafeRow filter_result;
/* 015 */   private org.apache.spark.sql.catalyst.expressions.codegen.BufferHolder filter_holder;
/* 016 */   private org.apache.spark.sql.catalyst.expressions.codegen.UnsafeRowWriter filter_rowWriter;
/* 017 */   private scala.collection.Iterator inputadapter_input1;
/* 018 */   private int columnar_batchIdx;
/* 019 */   private int columnar_numRows;
/* 020 */   private org.apache.spark.sql.execution.vectorized.ColumnVector inputadapter_col0;
/* 021 */   private UnsafeRow inputadapter_result;
/* 022 */   private org.apache.spark.sql.catalyst.expressions.codegen.BufferHolder inputadapter_holder;
/* 023 */   private org.apache.spark.sql.catalyst.expressions.codegen.UnsafeRowWriter inputadapter_rowWriter;
/* 024 */   private org.apache.spark.sql.execution.metric.LongSQLMetric filter_numOutputRows1;
/* 025 */   private org.apache.spark.sql.execution.metric.LongSQLMetricValue filter_metricValue1;
/* 026 */   private UnsafeRow filter_result1;
/* 027 */   private org.apache.spark.sql.catalyst.expressions.codegen.BufferHolder filter_holder1;
/* 028 */   private org.apache.spark.sql.catalyst.expressions.codegen.UnsafeRowWriter filter_rowWriter1;
/* 029 */   private org.apache.spark.sql.execution.columnar.ColumnarIterator columnar_itr;
/* 030 */
/* 031 */   public GeneratedIterator(Object[] references) {
/* 032 */     this.references = references;
/* 033 */   }
/* 034 */
/* 035 */   public void init(int index, scala.collection.Iterator inputs[]) {
/* 036 */     partitionIndex = index;
/* 037 */     inputadapter_input = inputs[0];
/* 038 */     this.filter_numOutputRows = (org.apache.spark.sql.execution.metric.LongSQLMetric) references[0];
/* 039 */     filter_metricValue = (org.apache.spark.sql.execution.metric.LongSQLMetricValue) filter_numOutputRows.localValue();
/* 040 */     filter_result = new UnsafeRow(1);
/* 041 */     this.filter_holder = new org.apache.spark.sql.catalyst.expressions.codegen.BufferHolder(filter_result, 0);
/* 042 */     this.filter_rowWriter = new org.apache.spark.sql.catalyst.expressions.codegen.UnsafeRowWriter(filter_holder, 1);
/* 043 */     inputadapter_input1 = inputs[0];
/* 044 */     columnar_batchIdx = 0;
/* 045 */     columnar_numRows = 0;
/* 046 */     inputadapter_col0 = null;
/* 047 */     inputadapter_result = new UnsafeRow(1);
/* 048 */     this.inputadapter_holder = new org.apache.spark.sql.catalyst.expressions.codegen.BufferHolder(inputadapter_result, 0);
/* 049 */     this.inputadapter_rowWriter = new org.apache.spark.sql.catalyst.expressions.codegen.UnsafeRowWriter(inputadapter_holder, 1);
/* 050 */     this.filter_numOutputRows1 = (org.apache.spark.sql.execution.metric.LongSQLMetric) references[1];
/* 051 */     filter_metricValue1 = (org.apache.spark.sql.execution.metric.LongSQLMetricValue) filter_numOutputRows1.localValue();
/* 052 */     filter_result1 = new UnsafeRow(1);
/* 053 */     this.filter_holder1 = new org.apache.spark.sql.catalyst.expressions.codegen.BufferHolder(filter_result1, 0);
/* 054 */     this.filter_rowWriter1 = new org.apache.spark.sql.catalyst.expressions.codegen.UnsafeRowWriter(filter_holder1, 1);
/* 055 */     columnar_itr = null;
/* 056 */   }
/* 057 */
/* 058 */   private void processBatch() throws java.io.IOException {
/* 059 */     /*** PRODUCE: Filter (value#1 <= 5.1) */
/* 060 */
/* 061 */     /*** PRODUCE: INPUT */
/* 062 */
/* 063 */     while (true) {
/* 064 */       if (columnar_batchIdx == 0) {
/* 065 */         columnar_numRows = columnar_itr.initForColumnar();
/* 066 */         if (columnar_numRows < 0) {
/* 067 */           cleanup();
/* 068 */           break;
/* 069 */         }
/* 070 */         inputadapter_col0 = columnar_itr.getColumn(0);
/* 071 */       }
/* 072 */
/* 073 */       while (columnar_batchIdx < columnar_numRows) {
/* 074 */         int inputadapter_rowIdx = columnar_batchIdx++;
/* 075 */         /*** CONSUME: Filter (value#1 <= 5.1) */
/* 076 */
/* 077 */         /* columnVector[inputadapter_col0, inputadapter_rowIdx, float] */
/* 078 */         float inputadapter_value1 = inputadapter_col0.getFloat(inputadapter_rowIdx);
/* 079 */
/* 080 */         /* (input[0, float] <= 5.1) */
/* 081 */         boolean filter_value4 = false;
/* 082 */         filter_value4 = inputadapter_value1 <= 5.1;
/* 083 */         if (!filter_value4) continue;
/* 084 */
/* 085 */         filter_metricValue1.add(1);
/* 086 */
/* 087 */         /*** CONSUME: WholeStageCodegen */
/* 088 */
/* 089 */         filter_rowWriter1.write(0, inputadapter_value1);
/* 090 */         append(filter_result1);
/* 091 */         if (shouldStop()) return;
/* 092 */       }
/* 093 */       columnar_batchIdx = 0;
/* 094 */     }
/* 095 */   }
/* 096 */
/* 097 */   private void processRow() throws java.io.IOException {
/* 098 */     /*** PRODUCE: Filter (value#1 <= 5.1) */
/* 099 */
/* 100 */     /*** PRODUCE: INPUT */
/* 101 */
/* 102 */     while (inputadapter_input.hasNext()) {
/* 103 */       InternalRow inputadapter_row = (InternalRow) inputadapter_input.next();
/* 104 */       /*** CONSUME: Filter (value#1 <= 5.1) */
/* 105 */
/* 106 */       /* input[0, float] */
/* 107 */       float inputadapter_value = inputadapter_row.getFloat(0);
/* 108 */
/* 109 */       /* (input[0, float] <= 5.1) */
/* 110 */       boolean filter_value = false;
/* 111 */       filter_value = inputadapter_value <= 5.1;
/* 112 */       if (!filter_value) continue;
/* 112 */       if (!filter_value) continue;
/* 113 */
/* 114 */       filter_metricValue.add(1);
/* 115 */
/* 116 */       /*** CONSUME: WholeStageCodegen */
/* 117 */
/* 118 */       filter_rowWriter.write(0, inputadapter_value);
/* 119 */       append(filter_result);
/* 120 */       if (shouldStop()) return;
/* 121 */     }
/* 122 */   }
/* 123 */
/* 124 */   private void cleanup() {
/* 125 */     inputadapter_col0 = null;
/* 126 */
/* 127 */     columnar_itr = null;
/* 128 */   }
/* 129 */
/* 130 */   protected void processNext() throws java.io.IOException {
/* 131 */     if ((columnar_batchIdx != 0) ||
/* 132 */       (inputadapter_input1 instanceof org.apache.spark.sql.execution.columnar.ColumnarIterator &&
/* 133 */         (columnar_itr = (org.apache.spark.sql.execution.columnar.ColumnarIterator)inputadapter_input1).isSupportColumnarCodeGen())) {
/* 134 */       processBatch();
/* 135 */     } else {
/* 136 */       processRow();
/* 137 */     }
/* 138 */   }
/* 139 */ }
```
## How was this patch tested?

Tested existing test suites
added test suites for operations to dataframe generated by df.cache().

### CODE REVIEW

**Comment by kiszk** [comment]
Jenkins, retest this please

**Comment by kiszk** [comment]
Jenkins, retest this please

**Comment by kiszk** [comment]
@davies , would it be possible to review this PR?

**Comment by davies** [comment]
This PR is huge, I may not have enough time to review this. Just saw that there is lots of changes in WholeStageCodegen, is it possible to avoid most of them (simplify the logic or move it to InMemoryTableScan)?

**Comment by kiszk** [comment]
I know this is huge. Sorry for that. There are three reasons. One is to include benchmark. The other is include test cases. The last one is to newly introduce decompress() method for each of compression algorithm. Is it better to split this into two parts: decompress() and code generation?

Also, I will try to reduce changes into WholeStageCodegen by moving some of them into other files such as InMemoryTableScan and GenerateColumnAccessor.

**Comment by kiszk** [comment]
@davies, thank you for your great suggestion. Now, I simplified changes in  ```WholeStageCodeGen.scala' by moving a logic regarding ```CachedBatch``` to other files. The total number of increased lines is reduced from 115 to 95.The generated code is also simplified since variables regarding ```CachedBatch``` are moved away. The total number of generated code is also reduced from 150 to 139.

I updated generated code and performance result in this PR.

**Comment by kiszk** [comment]
@rxin, would it be possible to review this PR, too? Especially, for decompression part that you originally wrote.

**Comment by kiszk** [comment]
ping @davies

**Comment by kiszk** [comment]
We can shrink the size of this PR (reducing the number of lines from 1800 to 700) by dropping test suites (1450 lines) and a benchmark program (250 lines). Is it better for ease of your review?

**Comment by davies** [comment]
@kiszk Can we target this for 2.1? We may switch to use Apache Arrow or other in-memory representation instead of current one.

**Comment by kiszk** [comment]
@davies I love your idea to use Apache Arrow or other in-memory format instead of ```Array[Byte]``` for DataFrame cache. That is what I want to create a JIRA entry in near future.
This idea is related to Part 1 (get data from columnar storage for DataFrame cache under ```org.apache.spark.sql.execution.columnar```) in this PR. Even if we use any in-memory format, an interface to code generation would be ColumnVector. As you can see, we already succeeded to wrap ```Array[Byte]``` and Parquet representation by using methods such as ```getInt()``` in ```ColumnVector```.

In this PR, can we target Part 2 (codegen under```org.apache.spark.sql.execution```) of this PR  for 2.0 at least? This is because Part 2 could accept any in-memory representation thru ```ColumnVector```. Part 2 is very small (less than 200 lines) after dropping code for Part 1. Thus, it is easy to review.

**Comment by kiszk** [comment]
@davies for ease of review, it would be good to split this PR into two. One is only for float and double primitive types. The other is for other primitive types. The first one focuses on PassThrough compression type in Dataframe cache. The latter focuses on other compression types in Dataframe cache. I estimated that the size of each of PR is about 900 lines.
Would it be possible to let us know If there are any issues?

**Comment by davies** [comment]
In high level, I think most of the implementation should be done in InMemoryTableScanExec, not in WholeStageCodegenExec.

**Comment by kiszk** [comment]
@davies, thank you for your comment. Based on your previous comment, [this commit](https://github.com/apache/spark/pull/11956/commits/d2161d13dab9871ce0e325fcc3934c2f4f5eca13) already moved some stuff of the implementation to ```InMemoryTableScanExec```. Now, ```WholeStageCodegenExec``` does only the following three features.

1. decide whether code for columnar storage should be generated
2. generate ```processRow()``` and ```processBatch```
3. generate runtime conditional-if statement whether ```processRow()``` or ```processBatch``` called

Do you mean these three features should be moved to ```InMemoryTableScanExec```? While I could do, my understanding is that these features would be implemented by methods in a singleton ```InMemoryTableScanExec```. Do you have any other good ideas to implement these features in ```InMemoryTableScanExec```?

**Comment by davies** [comment]
InMemoryTableScanExec is a case class, not singleton, why can we not implement these there?

**Comment by kiszk** [comment]
I missed something. While I assumed that I would newly declare a singleton object ```InMemoryTableScanExec``` and move 2. and 3. into new methods in the object. As you pointed out, it can be done in a case class.

For example, I will move [lines 263-296](https://github.com/apache/spark/pull/11956/files#diff-28cb12941b992ff680c277c651b59aa0R263) and [lines 374-403](https://github.com/apache/spark/pull/11956/files#diff-28cb12941b992ff680c277c651b59aa0R374) into each of two methods in the ```InMemoryTableScanExec``` and then put method calls into the original places in ``WholeStageCodegenExec```. Is this what you want to do?

**Comment by kiszk** [comment]
@davies As you suggested, I moved most of the implmentation from ```WholeStageCodegenExec``` to ```InMemoryTableScanExec```. Now, the number of changed lines in ```WholeStageCodegenExec.scala``` is about 30 lines. 
Since it is hard to pass an instance of ```InMemoryTableScanExec``` to ```InputAdaptor```, I newly introduced ```object InMemoryTableScanExec```.

Could you please review this PR?

**Comment by kiszk** [comment]
ping @davies

**Comment by kiszk** [comment]
ping @davies

**Comment by davies** [comment]
To be honest, Right now is too late to review and merge this into 2.0. I'm busy with other important things on 2.0, does not have enough bandwidth to review it. You could ask other people to look into the design in details.

**Comment by kiszk** [comment]
@davies thank you for your response. Since @rxin categorized this into 2.1, I understand it should be review for 2.1.
When 2.0 is out, I will ping you for the review. I would appreciate it if you would recommend other possible reviewers when you have time.

**Comment by kiszk** [comment]
@davies Would it be possible to review this if you have bandwidth for this?

**Comment by a-roberts** [comment]
@robbinspg and I are evaluating this from a functional and performance perspective, full disclosure: we both work for IBM with @kiszk.

All unit tests pass including the new ones Ishizaki has added, we've tested this on a variety of platforms, both big and little-endian. This is with IBM Java 8 and tested on three different architectures.

We can run the benchmark with
```
bin/spark-submit --class org.apache.spark.sql.DataFrameCacheBenchmark sql/core/target/spark-sql_2.11-2.0.0-tests.jar
``` 

or can be run against branch-2.0 (Spark 2.0.1 snapshot) with 
```
bin/spark-submit --class org.apache.spark.sql.DataFrameCacheBenchmark sql/core/target/spark-sql_2.11-2.0.1-SNAPSHOT-tests.jar
```

Performance results on a few low powered testing systems are promising.

Linux on Intel: 5.3x increase
```
  Stopped after 15 iterations, 2127 ms

IBM J9 VM pxa6480sr3-20160428_01 (SR3) on Linux 3.13.0-65-generic
Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz
Float Sum with PassThrough cache:        Best/Avg Time(ms)    Rate(M/s)   Per Row(ns)   Relative
------------------------------------------------------------------------------------------------
InternalRow codegen                            669 /  829         47.1          21.3       1.0X
ColumnVector codegen                           127 /  142        248.2           4.0       5.3X
```

Linux on Z: 2.7x increase
```
Stopped after 5 iterations, 2068 ms

IBM J9 VM pxz6480sr3-20160428_01 (SR3) on Linux 3.12.43-52.6-default
16/07/07 09:48:15 ERROR Utils: Process List(/usr/bin/grep, -m, 1, model name, /proc/cpuinfo) exited with code 1:
Unknown processor
Float Sum with PassThrough cache:        Best/Avg Time(ms)    Rate(M/s)   Per Row(ns)   Relative
------------------------------------------------------------------------------------------------
InternalRow codegen                            997 / 1134         31.5          31.7       1.0X
ColumnVector codegen                           371 /  414         84.7          11.8       2.7X

```

Linux on Power: 6.4x increase
```
  Stopped after 7 iterations, 2099 ms

IBM J9 VM pxl6480sr3-20160428_01 (SR3) on Linux 3.13.0-61-generic
16/07/07 14:33:40 ERROR Utils: Process List(/bin/grep, -m, 1, model name, /proc/cpuinfo) exited with code 1:
Unknown processor
Float Sum with PassThrough cache:        Best/Avg Time(ms)    Rate(M/s)   Per Row(ns)   Relative
------------------------------------------------------------------------------------------------
InternalRow codegen                           1199 / 1212         26.2          38.1       1.0X
ColumnVector codegen                           186 /  300        168.8           5.9       6.4X
```

So the performance increase and functionality is solid across platforms, Ishizaki has tested this with OpenJDK 8 also.

One improvement would be add a scale factor parameter so we can use more data than:
```
    doubleSumBenchmark(1024 * 1024 * 15)
    floatSumBenchmark(1024 * 1024 * 30)
```
and with no parameter we'd use the above as a standard/baseline. 

Would also be useful to have the master url as a parameter so we can easily run this using many machines or with more cores to see the performance/functional impact when we scale (exercising various JIT levels for example)

**Comment by kiszk** [comment]
Hi @davies could you please take a look at this since Spark 2.0.0 has been successfully released?

**Comment by kiszk** [comment]
@rxin, could you please review this?

**Comment by kiszk** [comment]
@davies, could you please take a look at this since Spark 2.0.0 has been successfully released?
cc: @rxin

**Comment by kiszk** [comment]
@davies, I hope that you have some bandwidth to review PRs. Could you please review this, too?

**Comment by kiszk** [comment]
@davies could you please review this?

**Comment by davies** [comment]
@kiszk I'm sorry that I do not have the bandwidth to review this, https://github.com/apache/spark/pull/13899/files sounds like an easier approach (have not looked into the details), how do you think of these two?

**Comment by kiszk** [comment]
@davies,  thank you for your comment. I hope that you will have bandwidth soon since Spark 2.0 was released.
[this PR](https://github.com/apache/spark/pull/13899/files) does the same thing. In particular, generated code for reading a column is almost the same.
The difference is to use the conventional `CachedBatch` that uses `Array[Byte]` or to use the new `CachedBatchByte` that may use `ColumnarBatch` created by [generated code ](https://gist.github.com/andrewor14/a9ed9d942029457a0f953e809ac26ee9). I like simplify my PR by using the idea in [the PR](https://github.com/apache/spark/pull/13899/files). For example, I can throw away new files `ByteBufferColumnVector.java`  and `PassThroughSuite.scala`.

I have two question in [the PR](https://github.com/apache/spark/pull/13899/files).
1. Do we use the conventional `CachedBatch` or `ColumnarBatch` for cache?
2. In this implementation, how a cache content in `ColumnarBatch` will be serialized when it must be flushed into a disk?
3. What test cases were failed? Links to test results are not valid now.
4. Will we support compression scheme in the future while we use `ColumnarBatch`?

What do you think?
2.

**Comment by kiszk** [comment]
@davies I would appreciate it if you would make comments on my questions to share how we implement a part of [columnar](https://issues.apache.org/jira/browse/SPARK-15687).

**Comment by kiszk** [comment]
@davies Would it be possible to share your opinions regarding these design questions among us?

**Comment by a-roberts** [comment]
@hvanhovell @marmbrus @srowen I see this PR has been open since the 25th of March and provides substantial performance improvements as mentioned above without introducing functional regressions, as leading SQL/community members what do you guys think?

**Comment by srowen** [comment]
I'm not qualified to comment as I tend to ignore SQL unless it's a simple and easy to evaluate change.

**Comment by kiszk** [comment]
@davies Could you please share your great opinions regarding these design questions among our community while we know you are busy?

**Comment by davies** [comment]
@kiszk The current implementation use ByteBuffer and smart compression algorithms, it too slow to build the in-memory cache, make it useless. So we'd like to improve the performance of building phase also. This PR is built for current representation, which may be throwed away in future, so I'd not rush to merge this PR, or spent to much time to review the details.

PR #13899 could be in the right direction, but need to double-check that by more benchmarks. In order to have better memory efficiency, we could use MEMORY_AND_SER storage level and compress the underlying array with LZ4 when serializing the ColumnVector.

**Comment by davies** [comment]
cc @rxin

**Comment by kiszk** [comment]
@davies Thank you for your reply. I understand the future direction. I will implement this direction by using this PR or another PR. While the future roadmap may consume more memory, the performance will be improved. The compression will be applied only when `ColumnVector` is serialized into disk. Am I correct? 

What benchmark programs do you want to use to double-check this roadmap?

**Comment by davies** [comment]
We could compress them in memory with MEMORY_AND_DISK_SER, this could be controlled by a flag.

**Comment by kiszk** [comment]
Thank you for your clarification. [Here](https://trongkhoanguyenblog.wordpress.com/2014/12/14/understand-the-storage-module-in-spark-core/) is a good summary for me.
We may add property like `spark.sql.cache.compression.codec` to specify a compression method.

**Comment by kiszk** [comment]
@davies, could you please rerun Jenkins for PR [#13899](https://github.com/apache/spark/pull/13899)?  I would like to know which tests were failed by the current implementation.

**Comment by kiszk** [comment]
I saw PR #13899. I understood there are two design points for now. Hopefully, no more points :)
1. `CachedBatch` must be serializable.
2. According to my experiments, we should make a class for a `CachedBatch` simple.

For 1, current ColumnarBatch is not serializable.
For 2, at [this line](https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/storage/memory/MemoryStore.scala#L216), `.next()` returns `CachedBatch`, and then `+=` involves call [`SizeEstimator.estimate()`](https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/util/SizeEstimator.scala#L69). If this method takes longer time for a complicated `CacheBatch` class, the performance is degraded. One of example is `auto_join??` in [this test](https://github.com/apache/spark/blob/master/sql/hive/compatibility/src/test/scala/org/apache/spark/sql/hive/execution/HiveCompatibilitySuite.scala).

**Comment by kiszk** [comment]
Current PR #13899 does not support a case that an element is null.
For now, I am working for the followings:
1. Support all of types
2. Make structures serializable
3. Support null cases

**Comment by gatorsmile** [comment]
@kiszk Is this still the issue? I knew you are working on the related part now.

**Comment by kiszk** [comment]
Thank you for pointing it out. #18747 implemented this feature.

**Pull request closed without merging**
