### PR TITLE
Refactored code to remove null representation

### PR DESCRIPTION
**Pull request by HarshSharma8**
## What changes were proposed in this pull request?

Removed the null value that was returned directly with null representation and returned in a better way.

## How was this patch tested?

The result remains same, its just a refactoring of code.

Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
It seems too tirival. The `default` seems even always `null`. I don't think this is an improvement if there is no other specific reason. The original codes are more readable to me.

**Comment by HarshSharma8** [comment]
May be this is right and readable from your point of view, this code is
returning nothing else, just null again and again as default value if user
along its other values are not present.
From my point of view i just let the user know about the default value that
i am going to use.

**Comment by HyukjinKwon** [comment]
`var` is mutàble and the "default value" seems not exposed to users and being changed.

**Comment by srowen** [comment]
@HarshSharma8  this is not an improvement, please close this. This is not the kind of PR that's worth submitting. See http://spark.apache.org/contributing.html

**Pull request closed without merging**
