### PR TITLE
[SPARK-19393][SQL] Add `approx_percentile` Dataset/DataFrame API

### PR DESCRIPTION
**Pull request by lw-lin**
## What changes were proposed in this pull request?

This patch adds `approx_percentile` API to Dataset/DataFrame. SQL equivalent: [FunctionRegistry.scala#L257-L258](https://github.com/apache/spark/blob/e7f982b20d8a1c0db711e0dcfe26b2f39f98dd64/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala#L257-L258).

Then people could migrate from [StatFunctions#multipleApproxQuantiles()](https://github.com/apache/spark/blob/51b1c1551d3a7147403b9e821fcc7c8f57b4824c/sql/core/src/main/scala/org/apache/spark/sql/execution/stat/StatFunctions.scala#L58) to this newly added api, as there were issues reported with StatFunctions#multipleApproxQuantiles():
- [SPARK-18656] StatFunctions#multipleApproxQuantiles requires too much memory in case of many columns
- [SPARK-19339] StatFunctions.multipleApproxQuantiles can give NoSuchElementException: next on empty iterator

## How was this patch tested?

New test cases

### CODE REVIEW

**Comment by lw-lin** [comment]
@rxin @hvanhovell could you take a look, thanks!

**Comment by lw-lin** [comment]
also @cloud-fan @gatorsmile could you take a look

**Comment by rxin** [comment]
to be honest I really hate it with Scala/Java when we need to add so many functions just for a single function. Can we just tell users to use `expr("approx_percentile(...)")`?

**Comment by lw-lin** [comment]
understood. they really were lots of functions -- let's tell users to use `expr("approx_percentile(...)")`.

closing this. thanks for the comments!

**Pull request closed without merging**
