### PR TITLE
[SPARK-48116][INFRA][FOLLOWUP] Simplify the build with fixing the if condition

### PR DESCRIPTION
**Pull request by HyukjinKwon**
### What changes were proposed in this pull request?

This PR is a followup of https://github.com/apache/spark/pull/46367 that simplifies the build and deduplicate them.

### Why are the changes needed?

To fix the condition, and make it deduplicated.

### Does this PR introduce _any_ user-facing change?

No, dev-only.

### How was this patch tested?

Manually.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @dongjoon-hyun

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you for fixing all, @HyukjinKwon .

**Comment by dongjoon-hyun** [comment]
Feel free to merge at any time when this PR is ready ~

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by HyukjinKwon** [comment]
Reverted. I will make a new try with trying within my own fork. I cherry-picked yours and merged it.

**Comment by dongjoon-hyun** [comment]
Oh, thank you for the fast recovery. Looking forward to seeing the new try.

**Pull request closed without merging**
