### PR TITLE
[SPARK-10782] [Python] Update dropDuplicates documentation

### PR DESCRIPTION
**Pull request by asokadiggs**
Documentation for dropDuplicates() and drop_duplicates() is one and the same.  Resolved the error in the example for drop_duplicates using the same approach used for groupby and groupBy, by indicating that dropDuplicates and drop_duplicates are aliases.

### CODE REVIEW

**Comment by asokadiggs** [comment]
FYI - I've used spark/python/docs/make html to generate the updated HTML versions of the files and visually verified the result in the resulting documentation.

**Comment by srowen** [comment]
I was going to say, I don't think this addresses the problem you identified, but then I realized there's no separate declaration of `drop_duplicates`? so I probably don't understand where that's coming from. If it must necessarily clone `dropDuplicates` docs then I agree with your note. Looks like this needs a style fix though. See the test result.

**Comment by asokadiggs** [comment]
Correct - there is no separate declaration for drop_duplicates.  There is a section in dataframe.py at approximately line 1280-1285 that sets drop_duplicates = dropDuplicates and groupby = groupBy for Pandas compatibility.  So there isn't an option to separately document drop_duplicates or groupby.

I implemented the same solution for drop_duplicates as is already implemented for groupby.  At least for me it's readable and understandable, so it works.

I found the test result - I'll figure out the white space error and resubmit.

**Comment by davies** [comment]
LGTM

**Pull request closed without merging**
