### PR TITLE
[SPARK-10559] DataFrame schema ArrayType should accept ResultIterable

### PR DESCRIPTION
**Pull request by maver1ck**
Patch to repair it.
https://issues.apache.org/jira/browse/SPARK-10559

### CODE REVIEW

**Comment by holdenk** [comment]
If were going to add a new accepted type, maybe having a test that makes sure it works from end-to-end might be a good addition. (Of course just my opinion).

**Comment by maver1ck** [comment]
@holdenk 
I added the test.

**Comment by holdenk** [comment]
This LGTM pending tests passing, maybe @davies  who wrote the type list for ArrayType can take a look?

**Comment by srowen** [comment]
Given the discussion in the JIRA, is this to be closed?

**Comment by maver1ck** [comment]
I think so.

**Comment by davies** [comment]
@maver1ck Can you close this?

**Pull request closed without merging**
