### PR TITLE
[SPARK-15424][SPARK-15437][SQL] Revert SPARK-14807 Create a hivecontext-compatibility module

### PR DESCRIPTION
**Pull request by rxin**
## What changes were proposed in this pull request?

I initially asked to create a hivecontext-compatibility module to put the HiveContext there. But we are so close to Spark 2.0 release and there is only a single class in it. It seems overkill to have an entire package, which makes it more inconvenient, for a single class.
## How was this patch tested?

Tests were moved.

### CODE REVIEW

**Comment by rxin** [comment]
cc @srowen @yhuai @marmbrus

**Comment by yhuai** [comment]
tes this please

**Comment by rxin** [comment]
Any idea why the test would fail this way?

**Comment by gatorsmile** [comment]
@rxin Could you also add the JIRA number SPARK-15437 in this PR? 

With this fix, we are able to create `HiveContext` in SparkR.  https://issues.apache.org/jira/browse/SPARK-15437 

Thanks!

**Comment by rxin** [comment]
added

**Comment by rxin** [comment]
Finally passed! Merging in master/2.0.

**Pull request closed without merging**
