### PR TITLE
[SPARK-38134][BUILD] Upgrade Apache Arrow to 7.0.0

### PR DESCRIPTION
**Pull request by sunchao**
### What changes were proposed in this pull request?

Upgrade Apache Arrow to 7.0.0.

### Why are the changes needed?

To pick up new improvements & bug fixes from the latest release.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by sunchao** [comment]
Sorry @LuciferYang, for using the JIRA you created. I'm trying to test out the RC here.

**Review by dongjoon-hyun — COMMENTED** [review]
Thank you, @sunchao .

**Comment by HyukjinKwon** [comment]
cc @BryanCutler @ueshin FYI

**Comment by sunchao** [comment]
Looks good. The test failure:
```
[info] *** 1 TEST FAILED ***
[26956](https://github.com/sunchao/spark/runs/5118829661?check_suite_focus=true#step:9:26956)
[error] Failed tests:
[26957](https://github.com/sunchao/spark/runs/5118829661?check_suite_focus=true#step:9:26957)
[error] 	org.apache.spark.sql.hive.thriftserver.CliSuite
[26958](https://github.com/sunchao/spark/runs/5118829661?check_suite_focus=true#step:9:26958)
[warn] In the last 2592 seconds, 13.557 (0.5%) were spent in GC. [Heap: 2.84GB free of 3.56GB, max 3.56GB] Consider increasing the JVM heap using `-Xmx` or try a different collector, e.g. `-XX:+UseG1GC`, for better performance.
[26959](https://github.com/sunchao/spark/runs/5118829661?check_suite_focus=true#step:9:26959)
```
is unrelated.

**Comment by dongjoon-hyun** [comment]
Ya, I agree. Could you re-trigger since it's cheap?

**Comment by sunchao** [comment]
Sure, re-triggered

**Review by LuciferYang — APPROVED** [review]
LGTM & please update the pr description @sunchao

**Comment by sunchao** [comment]
Thanks @LuciferYang . Marked the PR as ready for review.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @sunchao and all!
Merged to master for Apache Spark 3.3.0.

**Review by HyukjinKwon — COMMENTED** [review]
LGTM2!

**Pull request closed without merging**
