### PR TITLE
[SPARK-45502][BUILD] Upgrade Kafka to 3.6.0

### PR DESCRIPTION
**Pull request by dengziming**
### What changes were proposed in this pull request?
Upgrade Apache Kafka from 3.4.1 to 3.6.0

### Why are the changes needed?

- https://downloads.apache.org/kafka/3.6.0/RELEASE_NOTES.html
- https://downloads.apache.org/kafka/3.5.1/RELEASE_NOTES.html
- https://archive.apache.org/dist/kafka/3.5.0/RELEASE_NOTES.html

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
GitHub CI.

### Was this patch authored or co-authored using generative AI tooling?
No

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Thank you for making a PR, @dengziming .

**Comment by dongjoon-hyun** [comment]
3-times consecutive failures? Does all test cases pass in your local environment, @dengziming ? Or, do you think this PR may introduce a new flakiness?

Screenshot 2023-10-12 at 2 49 15 AM

**Comment by dengziming** [comment]
Thank you  @dongjoon-hyun for mention this, The first two failures are related to checkstyle problems, and this failed test `KafkaSourceStressSuite` passed in my local environment. I'm investigate this flakiness currently.

**Comment by dongjoon-hyun** [comment]
Thank you, @dengziming . Let me merge this your contribution.

**Comment by dongjoon-hyun** [comment]
Merged to master for Apache Spark 4.0.0.

**Comment by LuciferYang** [comment]
In the 10 builds after this pr was merged, the success rate of `KafkaSourceStressSuite` is quite low. Is there any progress in the investigation? @dengziming 

- https://github.com/apache/spark/actions/runs/6497942586/job/17648192318
- https://github.com/apache/spark/actions/runs/6497999347/job/17648385705
- https://github.com/apache/spark/actions/runs/6502219014/job/17660900989
- https://github.com/apache/spark/actions/runs/6502591917/job/17661861797
- https://github.com/apache/spark/actions/runs/6503144598/job/17663199041
- https://github.com/apache/spark/actions/runs/6503233514/job/17663413817

**Comment by dengziming** [comment]
Hello @LuciferYang,  I have reproduced this locally and investigating, it seems there are more than one reason for this problem and I need some time.

**Comment by LuciferYang** [comment]
Thank you @dengziming

**Comment by LuciferYang** [comment]
If it can't be fixed quickly, can we revert this patch or ignore `KafkaSourceStressSuite` first? The recent CI is almost impossible to succeed.

**Comment by HeartSaVioR** [comment]
> this failed test KafkaSourceStressSuite is also flaky in my local env, I'm investigating this.

Let's be clear about this. Did you mean KafkaSourceStressSuite is also flaky with Kafka 3.4.1 or Kafka 3.6.0 in your local env? If the case is latter then we shouldn't ignore the flakiness.

**Comment by dengziming** [comment]
> is also flaky with Kafka 3.4.1 or Kafka 3.6.0 in your local env

After some attempt, I find that there is a weird situation: deleted topic will com back again. this is the root cause for the flakiness, I will make some deeper debug.

**Pull request closed without merging**
