### PR TITLE
[SPARK-40953][CONNECT][PYTHON] Fix `DataFrame.head` to collect specified number of rows

### PR DESCRIPTION
**Pull request by zhengruifeng**
### What changes were proposed in this pull request?
`head` should return `self.limit(n).toPandas()` instead of `self.toPandas()`

### Why are the changes needed?
bugfix

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
existing tests

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Please file a JIRA issue and use in the PR title, @zhengruifeng .

**Comment by zhengruifeng** [comment]
@dongjoon-hyun thanks for the reminder😄

**Review by itholic — APPROVED** [review]
LGTM

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by amaliujia** [comment]
nice catch!

**Pull request closed without merging**
