### PR TITLE
[SPARK-9553][SQL] remove the no-longer-necessary createCode and createStructCode, and replace the usage

### PR DESCRIPTION
**Pull request by cloud-fan**

### CODE REVIEW

**Comment by cloud-fan** [comment]
cc @rxin

**Comment by rxin** [comment]
LGTM

**Comment by cloud-fan** [comment]
it's not minor anymore as we need `ceateCode` some place else...
I have created a JIRA for it.

**Comment by rxin** [comment]
LGTM

**Comment by rxin** [comment]
I've merged this. Thanks.

**Comment by rxin** [comment]
This hasn't been merged yet because there are some problems with asf git.

https://issues.apache.org/jira/browse/INFRA-10079

**Comment by rxin** [comment]
Merged now.

**Pull request closed without merging**
