### PR TITLE
[YARN] SPARK-8657: Fail to upload conf archive to viewfs in spark-1.4

### PR DESCRIPTION
**Pull request by litao-buptsse**
Fail to upload conf archive to viewfs in spark-1.4
JIRA Link: https://issues.apache.org/jira/browse/SPARK-8657

### CODE REVIEW

**Comment by srowen** [comment]
Close this PR please, it is not valid

**Comment by litao-buptsse** [comment]
@srowen I checkout code from branch-1.4, should I create a merge request to branch-1.4 not master?

**Comment by litao-buptsse** [comment]
@srowen I create a new PR to branch-1.4, PR link: https://github.com/apache/spark/pull/7042

**Comment by srowen** [comment]
Yes, you can see the problem with this PR. Please close this one.

**Pull request closed without merging**
