### PR TITLE
[SPARK-48826][BUILD] Upgrade `fasterxml.jackson` to 2.17.2 

### PR DESCRIPTION
**Pull request by wayneguow**
### What changes were proposed in this pull request?

This PR amis to upgrade `fasterxml.jackson` from 2.17.1 to 2.17.2.

### Why are the changes needed?

There are some bug fixes about [Databind](https://github.com/FasterXML/jackson-databind):
[#4561](https://github.com/FasterXML/jackson-databind/issues/4561): Issues using jackson-databind 2.17.1 with Reactor (wrt DeserializerCache and ReentrantLock)
[#4575](https://github.com/FasterXML/jackson-databind/issues/4575): StdDelegatingSerializer does not consider a Converter that may return null for a non-null input
[#4577](https://github.com/FasterXML/jackson-databind/issues/4577): Cannot deserialize value of type java.math.BigDecimal from String "3." (not a valid representation)
[#4595](https://github.com/FasterXML/jackson-databind/issues/4595): No way to explicitly disable wrapping in custom annotation processor
[#4607](https://github.com/FasterXML/jackson-databind/issues/4607): MismatchedInput: No Object Id found for an instance of X to assign to property '@id'
[#4610](https://github.com/FasterXML/jackson-databind/issues/4610): DeserializationFeature.FAIL_ON_UNRESOLVED_OBJECT_IDS does not work when used with Polymorphic type handling

The full release note of 2.17.2:
https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.17.2

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass GA.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by LuciferYang** [comment]
What modifications are related to Spark? Can you add some details in the PR description?

**Comment by wayneguow** [comment]
@LuciferYang  Thank you for the guidance, let me do some in-depth inspection and update it.

**Comment by wayneguow** [comment]
@LuciferYang  Updated it. And there is `jackson-datatype-jdk8/2.17.0//jackson-datatype-jdk8-2.17.0.jar` which is involved by `parquet` 1.14.1, I think there is no need to update it.  WDYT?

**Review by LuciferYang — APPROVED** [review]

**Comment by LuciferYang** [comment]
Merged into master. Thanks @wayneguow

**Comment by LuciferYang** [comment]
> @LuciferYang Updated it. And there is `jackson-datatype-jdk8/2.17.0//jackson-datatype-jdk8-2.17.0.jar` which is involved by `parquet` 1.14.1, I think there is no need to update it. WDYT?

We can submit an independent pr to try defining additional versions of this dependency.

**Pull request closed without merging**
