### PR TITLE
[MINOR][ML] Remove `BisectingKMeansModel.setDistanceMeasure` method

### PR DESCRIPTION
**Pull request by WeichenXu123**
## What changes were proposed in this pull request?

Remove `BisectingKMeansModel.setDistanceMeasure` method.
In `BisectingKMeansModel` set this param is meaningless.

## How was this patch tested?

N/A

### CODE REVIEW

**Comment by srowen** [comment]
Pardon, why is it meaningless? It's used in the implementation it delegates to.

**Comment by WeichenXu123** [comment]
@srowen The delegated `mllib.BisectingKMeansModel` is:
```
class BisectingKMeansModel private[clustering] (
    private[clustering] val root: ClusteringTreeNode,
    @Since("2.4.0") val distanceMeasure: String
  ) extends...
```
its constructor argument `distanceMeasure` is immutable and the `setDistanceMeasure` here only change the wrapper model's param and it effect nothing.

**Comment by srowen** [comment]
Oh right, the model, not the implementation. CC @mgaido91 too. OK we can take it out because it was only introduced for 2.4.0.

Hm, so the model still has a distanceMeasure, but it's just not something that should be settable.

The bisecting k-means model just wraps the older .mllib model. But I don't see that its getDistanceMeasure would actually return the value inside that wrapped model? I am missing where the wrapper gets updated to return the actual distance measure used.

Is that also an issue or did I miss something?

**Comment by mgaido91** [comment]
Thanks for pinging me @srowen.

> But I don't see that its getDistanceMeasure would actually return the value inside that wrapped model? I am missing where the wrapper gets updated to return the actual distance measure used.

Yes, that is the reason that `setDistanceMeasure` was introduces IIRC. So probably the issue here is that is never set. It would be good if we can add a test for this if there is no-one.

**Comment by srowen** [comment]
OK so the wrapper model's constructor needs to set this value once from the wrapped model? It does seem like it should be immutable and seems to not be exposed to set in k means for example.

**Comment by mgaido91** [comment]
Yes, I think the point here is that the parameter is part of `BisectingKMeansParams` which defines as final the getter method. I think `KMeans` has the same issue. We can probably remove this and set the distanceMeasure from the parent model at creation time.

**Comment by WeichenXu123** [comment]
Do we need to set `distanceMeasure` again for the parent model ?
When parent model created, it will use the same `distanceMeasure` with the one used in training.

**Comment by mgaido91** [comment]
Oh, right, it is already set in `copyValues`. Yes, then we can remove this (we should indeed since it takes no effect and can be misleading). Thanks, LGTM.

**Review by srowen — APPROVED** [review]

**Comment by srowen** [comment]
Merged to master/2.4

**Pull request closed without merging**
