### PR TITLE
[SPARK-27515][Deploy] When application master retry after a long time running, the hdfs delegation tokens may be expired

### PR DESCRIPTION
**Pull request by turboFei**
## What changes were proposed in this pull request?
When submit  a spark yarn application,  we first create a container launch context and store the relative tokens.
And for each attempt of applicationMaster, it would transfer origin tokens  for connecting to yarn.
However, it also transfers origin hdfs delegation tokens.
For a spark streaming application, if its applicationMaster failed when it has run for a long duration.
The hdfs token stored in container launch context may be expired.
When the new attempt applicationMaster `prepareLocalResources`, it would access the hdfs and failed  for token expired.
This error occured when we rolling upgrading our yarn cluster.
 We rolling restart the nodemanagers, the application master failed therefor, then this error occured when application master retry. 

In this PR, I renew hadoop delegation credentials and  transfer them to the new ugi.
## How was this patch tested?
I don't know how to add unit test, i will test it manually.

### CODE REVIEW

**Comment by turboFei** [comment]
@dongjoon-hyun Can you help to review it?

**Comment by turboFei** [comment]
This error occured with spark-2.3.2.
I did not know there is an issue SPARK-23361, which is duplicated with this.
I'm sorry.

**Comment by dongjoon-hyun** [comment]
Hi, @turboFei . 
Since `SPARK-27515` is closed, can we close this PR?

**Comment by turboFei** [comment]
> Thank you for pinging me, @turboFei .
> 
> Since `SPARK-27515` is closed, can we close this PR? We usually do like that.
> 
> You may want to comment on SPARK-23361 JIRA issue if you want to a backport of SPARK-23361.
> 
> BTW, I'm not sure if the backport is possible or not. In general, I'd like to recommend you to try to use Spark 2.4.1 or 2.4.2 RC1.

Thanks. SPARK-23361 has resolved this problem, I will close this pr.

**Comment by dongjoon-hyun** [comment]
Thanks, @turboFei .

**Pull request closed without merging**
