### PR TITLE
[SPARK-15873][Spark Core] JdbcRDD to support more bound types other than Long

### PR DESCRIPTION
**Pull request by weicheng113**
## What changes were proposed in this pull request?

JdbcRDD - generalize lower&upper bound type support, not just long type. Allow multiple lower&upper bound occurrence in SQL. This is demonstrated in the updated tests.
## How was this patch tested?

By integration tests. Some more integration tests are added along with the updated old ones.

### CODE REVIEW

**Comment by weicheng113** [comment]
In the original JdbcRDD, it only supports Long bound type and does not leave room for extension. In the pull request, the implementation support the original Long type plus String type, which is also a commonly used type for primary key. The JdbcPartition trait allows for potential extension as well.

**Comment by rxin** [comment]
Any reason you are not using the jdbc data source in Spark SQL? It seems like it'd only make sense for jdbc to use the jdbc data source since it is structured.

**Comment by weicheng113** [comment]
@rxin , Spark SQL DataFrameReader.jdbc only supports Long lowerBound and upperBound also. String type primary key as lower&upper bound is also commonly used.

The reason i am not using Spark SQL in one of my cases is that i am doing a full data sync from SQL DB to ElasticSearch and don't do any calculation. Selected columns from several joined tables form one ElasticSearch type. Process is: a DB joined row --> a Entity --> a ElasticSearch document. Entity does data conversion, validation and formatting.

if this PR is valid, i will do a final clean up and documenting.

**Comment by weicheng113** [comment]
@rxin , Could you please have a look this PR. I think spark should loosen lower&upper bounds. I did some search. There were some people complaining about it, but somehow they did not raise an issue. Links to complaints in Chinese:
http://www.lai18.com/content/1087463.html
http://my.oschina.net/victorlovecode/blog/344231

**Comment by rxin** [comment]
@weicheng113 can we enhance the jdbc data source to adopt those, rather than fixing the existing jdbc rdd?

**Comment by weicheng113** [comment]
@rxin , With current implementation, i cannot think a way to extend it to support other types, as it restricts itself on long lower&upper bounds only. The major API changes I did are below and support back compatibility:
`class JdbcRDD[T: ClassTag](
    sc: SparkContext,
    getConnection: () => Connection,
    sql: String,
    partitions: Seq[JdbcPartition],
    mapRow: (ResultSet) => T)
extends RDD[T](sc, Nil) with Logging {
...`

`
trait JdbcPartition extends Serializable {
  def fill(stmt: PreparedStatement): Unit
}
`
The changes i think it is necessary as JdbcPartition leave room for extension, allowing any potential types of lower&upper bound types and other cases.

**Comment by rxin** [comment]
The main thing you want is to be able to specify the predicate for each partition in the jdbc data source, isn't it?

**Comment by weicheng113** [comment]
@rxin You are right. How can we achieve it at the moment with modification?

**Comment by JoshRosen** [comment]
I'm closing PR because (a) it's been inactive for a couple of years and (b) the corresponding JIRA was [bulk closed](https://lists.apache.org/thread.html/746658d65d730a7c0ff09c886fc3c3a82f6596ff98e4746f132f2fad@%3Cdev.spark.apache.org%3E).

**Pull request closed without merging**
