### PR TITLE
[SPARK-11808] Remove Bagel.

### PR DESCRIPTION
**Pull request by rxin**

### CODE REVIEW

**Comment by rxin** [comment]
cc @ankurdave

**Comment by rxin** [comment]
cc @pwendell

**Comment by pwendell** [comment]
LGTM (I downloaded your PR and did some grepping to make sure there are no references). One other thing that occured to me is someone could easily create a package with this if they want to continue using in in Spark 2.0+, or just copy-paste the source code.

**Comment by srowen** [comment]
Is it open season on breaking changes? this is something slightly less as it's more like not continuing to publish a submodule. I suppose some changes in master are better after 1.6 is released to avoid strange back-port problems. This is probably worth an announcement if so. YOu're implicitly making a fairly big decision, that work on 1.x is mostly stopping.

**Comment by rxin** [comment]
Great idea. I will send an email out soon.

**Pull request closed without merging**
