### PR TITLE
[SPARK-5129][SQL] make SqlContext support sql like "select date +/- XX DAYS from table"  

### PR DESCRIPTION
**Pull request by pzzs**

### CODE REVIEW

**Comment by scwf** [comment]
can you add a test case for this?

**Comment by marmbrus** [comment]
this seems like something that would be better suited for a UDF instead of adding more syntax.  Is this a common thing in other systems or are we inventing something new?

**Comment by DoingDone9** [comment]
TSQL support it @marmbrus

**Comment by scwf** [comment]
link to https://issues.apache.org/jira/browse/SPARK-4867

**Comment by marmbrus** [comment]
Hey, sorry for the delay here.  I'm really hesitant to add new syntax the SQLParser as we are trying to focus our efforts on the HiveQL.  Anything that we add here we have to support forever, so I'd rather see this done as a UDF.  As a result I'd suggest we close this issue and discuss further on JIRA if you disagree.

**Pull request closed without merging**
