### PR TITLE
[SPARK-29936][R][2.4] Fix SparkR lint errors and add lint-r GitHub Action

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR fixes SparkR lint errors and adds `lint-r` GitHub Action to protect the branch.

### Why are the changes needed?

It turns out that we currently don't run it. It's recovered yesterday. However, after that, our Jenkins linter jobs (`master`/`branch-2.4`) has been broken on `lint-r` tasks.

### Does this PR introduce any user-facing change?

No.

### How was this patch tested?

Pass the GitHub Action on this PR in addition to Jenkins R.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
cc @HyukjinKwon and @viirya

**Review by HyukjinKwon — APPROVED** [review]
LGTM if tests pass

**Review by viirya — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to branch-2.4.

**Comment by HyukjinKwon** [comment]
Ah, technically I had to wait for the build results. I will keep my eyes on that.

**Comment by dongjoon-hyun** [comment]
Thank you for merging, @HyukjinKwon . :)

**Pull request closed without merging**
