### PR TITLE
[SPARK-12411] [CORE] Decrease executor heartbeat timeout to match heartbeat interval

### PR DESCRIPTION
**Pull request by nongli**
Previously, the rpc timeout was the default network timeout, which is the same value
the driver uses to determine dead executors. This means if there is a network issue,
the executor is determined dead after one heartbeat attempt. There is a separate config
for the heartbeat interval which is a better value to use for the heartbeat RPC. With
this change, the executor will make multiple heartbeat attempts even with RPC issues.

### CODE REVIEW

**Comment by andrewor14** [comment]
Is the issue you're trying to fix the following: there can be up to 12 parallel heartbeats to the driver from each executor? Other than that, is there any other change in behavior that you're expecting as of this patch?

**Comment by nongli** [comment]
I think there can only be 1 heartbeat in flight but because of the network timeout, the executor only gets 1 try instead of 12.

**Comment by zsxwing** [comment]
> there can be up to 12 parallel heartbeats to the driver from each executor?

12 parallel heartbeats? Why there are so many heartbeats in flight?

**Comment by andrewor14** [comment]
> 12 parallel heartbeats? Why there are so many heartbeats in flight?

There can't be because we use a single thread for the heartbeat; it was my misunderstanding.

**Comment by andrewor14** [comment]
LGTM merging into master.

**Pull request closed without merging**
