### PR TITLE
[SPARK-47277] PySpark util function assertDataFrameEqual should not support streaming DF

### PR DESCRIPTION
**Pull request by WweiL**
### What changes were proposed in this pull request?

The handy util function should not support streaming dataframes, currently if you call it upon streaming queries, it throws a relatively hard-to-understand error:
```
>>> df1 = spark.readStream.format("rate").load()
>>> df2 = spark.readStream.format("rate").load()
>>> from pyspark.testing.utils import QuietTest, assertDataFrameEqual
>>> assertDataFrameEqual(df1, df2)
/Users/wei.liu/oss-spark/python/pyspark/pandas/__init__.py:43: UserWarning: 'PYARROW_IGNORE_TIMEZONE' environment variable was not set. It is required to set this environment variable to '1' in both driver and executor sides if you use pyarrow>=2.0.0. pandas-on-Spark will set it for you but it does not work if there is a Spark context already launched.
  warnings.warn(
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/wei.liu/oss-spark/python/pyspark/testing/utils.py", line 936, in assertDataFrameEqual
    actual_list = actual.collect()
  File "/Users/wei.liu/oss-spark/python/pyspark/sql/dataframe.py", line 1453, in collect
    sock_info = self._jdf.collectToPython()
  File "/Users/wei.liu/oss-spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
  File "/Users/wei.liu/oss-spark/python/pyspark/errors/exceptions/captured.py", line 221, in deco
    raise converted from None
pyspark.errors.exceptions.captured.AnalysisException: Queries with streaming sources must be executed with writeStream.start();
rate
```
Because the function calls `collect` which is not supported on streaming dataframes. It'd be good if we can catch this earlier.

### Why are the changes needed?

Improve usability

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Unit test

### Was this patch authored or co-authored using generative AI tooling?

Generated-by: Github Copilot
It helped me to pick the error class UNSUPPORTED_OPERATION

### CODE REVIEW

**Comment by WweiL** [comment]
I'm having some local build issue, since this is a small change I want to defer the test to remote CI

**Comment by HyukjinKwon** [comment]
cc @itholic

**Review by HyukjinKwon — APPROVED** [review]

**Comment by WweiL** [comment]
CI error is still related, i'll rebuild locally and verify tomorrow

**Review by xinrong-meng — APPROVED** [review]

**Review by itholic — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

@WweiL would you mind opening a backporting PR to branch-3.5?

**Comment by WweiL** [comment]
@HyukjinKwon Sure

**Pull request closed without merging**
