### PR TITLE
[SPARK-42052][SQL] Codegen Support for HiveSimpleUDF

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
As a subtask of [SPARK-42050](https://issues.apache.org/jira/browse/SPARK-42050), this PR adds Codegen Support for HiveSimpleUDF

### Why are the changes needed?
Improve codegen coverage and performance

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
New UT & Pass GA.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Hm, I think we should better go and figure out to resolve this by using `Invoke` so we don't have to manually implement the codegen logic. I was fine with https://github.com/apache/spark/pull/39555 as a one time thing but seems like there are some more to fix.

**Comment by HyukjinKwon** [comment]
cc @cloud-fan @yaooqinn @dongjoon-hyun FYI

**Comment by dongjoon-hyun** [comment]
I agree with @HyukjinKwon 's comment too.

**Comment by panbingkun** [comment]
> Hm, I think we should better go and figure out to resolve this by using `Invoke` so we don't have to manually implement the codegen logic. I was fine with #39555 as a one time thing but seems like there are some more to fix.

As the first step, I have submitted a new Pr(https://github.com/apache/spark/pull/39949) to rewrite HiveGenericUDF with Invoke.

**Comment by DonnyZone** [comment]
Any progress on this topic? We find the Codegen combined with the expression-reuse feature (https://github.com/apache/spark/pull/29975) can greatly improve the performance. Many users write duplicate hiveUDFs in their queries.

**Pull request closed without merging**
