### PR TITLE
[MINOR] Only rename SparkR tar.gz if names mismatch

### PR DESCRIPTION
**Pull request by shivaram**
## What changes were proposed in this pull request?

For release builds the R_PACKAGE_VERSION and VERSION are the same (e.g., 2.1.0). Thus `cp` throws an error which causes the build to fail. 

## How was this patch tested?

Manually by executing the following script
```
set -o pipefail
set -e
set -x

touch a

R_PACKAGE_VERSION=2.1.0
VERSION=2.1.0

if [ "$R_PACKAGE_VERSION" != "$VERSION" ]; then
  cp a a
fi
```

### CODE REVIEW

**Comment by shivaram** [comment]
cc @rxin

**Comment by felixcheung** [comment]
can we `mv` instead?
https://github.com/apache/spark/pull/16249/files#diff-ba2c046d92a1d2b5b417788bfb5cb5f8R232

**Comment by felixcheung** [comment]
I found an issue with snapshot build just now - `R CMD check` doesn't handle the `-SNAPSHOT` part of the file name in SparkR_*tar.gz. Since it's only an issue with SNAPSHOT build I'll open a PR separately.

**Comment by shivaram** [comment]
Ah I see - yes - using `mv` is a simpler option - BTW when do we run `R CMD check` ? Is this for say when users download the tar.gz and run it ? (We can move this discussion to the JIRA)

**Comment by rxin** [comment]
Merging in master/branch-2.1.

**Pull request closed without merging**
