### PR TITLE
[MINOR][MLLIB] Public visibility for eval metric's dataframe constructor

### PR DESCRIPTION
**Pull request by tanwanirahul**

### CODE REVIEW

**Comment by JoshRosen** [comment]
Not sure whether this should be public or not (I don't know much about MLlib), but shouldn't this have an `@Since(2.0.0)` annotation if it's going to be public?

**Comment by tanwanirahul** [comment]
@JoshRosen Sure. If someone confirms on this, I will add that.

On if we need it: The pipeline apis work on the dataframes. If we don't have this interface, we are required to convert dataframes back to RDD and make it work. 

The other question I had was: Current implementation assumes the first column to be prediction and the second one the label/observation. Is this reasonable assumption to make? Shouldn't we rather expect the prediction and label/observation column names to be provided, the way other ml algorithms expect?

**Comment by tanwanirahul** [comment]
@mengxr - I see you have added this code. Could you please check if this change would be good to have. If not, I will happily close.

**Comment by jkbradley** [comment]
I don't think this should be public.  If this is needed for the DataFrame-based API, then we should discuss providing the evaluation metric classes within the spark.ml package.  Could you please close this PR, and we can discuss more on JIRA?  Thanks.

**Comment by HyukjinKwon** [comment]
@tanwanirahul Could you fill up the PR description with the purpose please?

**Comment by tanwanirahul** [comment]
@jkbradley Make sense. Thanks.

**Pull request closed without merging**
