### PR TITLE
[SPARK-30777][PYTHON][TESTS] Fix test failures for Pandas >= 1.0.0

### PR DESCRIPTION
**Pull request by BryanCutler**
### What changes were proposed in this pull request?

Fix PySpark test failures for using Pandas >= 1.0.0.

### Why are the changes needed?

Pandas 1.0.0 has recently been released and has API changes that result in PySpark test failures, this PR fixes the broken tests.

### Does this PR introduce any user-facing change?

No

### How was this patch tested?

Manually tested with Pandas 1.0.1 and PyArrow 0.16.0

### CODE REVIEW

**Comment by BryanCutler** [comment]
cc @HyukjinKwon , also do you think should add to branch-3.0 and maybe 2.4?

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master and branch-3.0.

Yeah, I think we should port back to branch-2.4 too .. but seems having a conflict. Would you mind a PR to backport?

**Comment by dongjoon-hyun** [comment]
Thank you, @BryanCutler and @HyukjinKwon !

**Comment by BryanCutler** [comment]
>Yeah, I think we should port back to branch-2.4 too .. but seems having a conflict. Would you mind a PR to backport?

Sure, I can do that. It's probably just the file renaming that conflicted.

**Comment by BryanCutler** [comment]
@HyukjinKwon backporting to 2.4 looks to be more complicated. There were a number of other fixes for pandas and pyarrow that went in along with increasing the versions that are only in Spark 3.0.0, e.g. https://issues.apache.org/jira/browse/SPARK-26887 that fixed some issues with date types. I think it would be too risky to try to backport all of these.

**Comment by dongjoon-hyun** [comment]
@BryanCutler and @HyukjinKwon . In that case, I believe we can skip backporting because 2.4.0 is released before Pandas 1.0.0. Supporting Pandas 1.0.0 can be considered as a new feature.

BTW, do we need to document the supported Pandas version in `branch-2.4` for `2.4.6`?

**Comment by BryanCutler** [comment]
>BTW, do we need to document the supported Pandas version in branch-2.4 for 2.4.6?

@dongjoon-hyun I can't remember what pyarrow version we test for branch-2.4, I think it's the same as master, which is pyarrow=0.14.1?  Is that correct @shaneknapp or @HyukjinKwon ?

That would be the highest supported version, then above are use at your own risk. They might fail on some date/timestamp issues, but work for most - not sure if we want to say that though.

**Comment by shaneknapp** [comment]
for 2.4, python 3.6.8:

'''
-bash-4.1$ python -c "import pandas; import pyarrow; print('pandas: %s' % pandas.__version__); print('pyarrow: %s' % pyarrow.__version__)"
pandas: 0.19.2
pyarrow: 0.8.0
'''

**Comment by HyukjinKwon** [comment]
Oh, I thought it's single env. If this is the case, I think it's fine to don't backport.

**Comment by HyukjinKwon** [comment]
+1 for https://github.com/apache/spark/pull/27529#issuecomment-585918641

**Comment by BryanCutler** [comment]
Thanks @shaneknapp !

**Comment by BryanCutler** [comment]
I'll open another PR to add a note for branch 2.4

**Pull request closed without merging**
