### PR TITLE
[SPARK-12037][CORE] initialize heartbeatReceiverRef before calling startDriverHeartbeat

### PR DESCRIPTION
**Pull request by CodingCat**
https://issues.apache.org/jira/browse/SPARK-12037

a simple fix by changing the order of the statements

### CODE REVIEW

**Comment by srowen** [comment]
LGTM

**Comment by lianhuiwang** [comment]
LGTM @andrewor14

**Comment by CodingCat** [comment]
ping @srowen ?

**Comment by srowen** [comment]
Seems OK... I suppose I wanted to at least give people the Monday back from holiday to have a look at things that came up over the weekend, so was delaying merging.

**Comment by andrewor14** [comment]
Looks OK, feel free to merge

**Comment by andrewor14** [comment]
Merged into master 1.6

**Pull request closed without merging**
