### PR TITLE
[SPARK-18222][CORE][SQL][ML] Use math instead of Math

### PR DESCRIPTION
**Pull request by zhengruifeng**
## What changes were proposed in this pull request?
Use `scala.math` instead of `java.lang.Math`.
Using cmd `find . -name '*.scala' | xargs -i bash -c 'egrep "Math\." -n {} && echo {}'` to generate modification candidates.

## How was this patch tested?
existing tests

### CODE REVIEW

**Comment by srowen** [comment]
These are actually usages of java.lang.Math. I do kind of like standardizing in one go, but if so, I wonder if you can add a scalastyle rule to forbid direct use of java.lang.Math?

**Comment by zhengruifeng** [comment]
@srowen You are right. What should I do next: close this PR for `scala.Math` is not used ? or view it as a kind of usage unification?

**Comment by zhengruifeng** [comment]
@srowen OK, I know what you mean. I wil try to make the scalastyle rule.

**Comment by zhengruifeng** [comment]
I add a scalastyle rule and it work in my local env with `./dev/lint-scala`

**Comment by rxin** [comment]
Actually why would we do this at all? Often the scala implementation are just slower than the Java one (sometimes because they are wrappers).

**Comment by srowen** [comment]
Yeah `scala.math` is all wrappers. It can't be faster though I think it won't matter after inlining. I suppose it's nicer stylewise to standardize, and `scala.math` is a bit more natural. If so it deserves a style rule. I don't feel that strongly about it. This PR started under a different assumption about the effect of this change.

**Comment by rxin** [comment]
A lot of wrappers in Scala are slower even with JIT, e.g. at some point Spark used Scala's StringBuffer and some user found it was 30% slower than Java's. Anyway even if there is 0% performance difference, I don't think it is that big of a deal to have some code using scala.math and some using java math.

**Comment by zhengruifeng** [comment]
this pr/jira started with a wrong point: I mistakenly view `Math` as `scala.Math`. I will close it.

**Pull request closed without merging**
