### PR TITLE
[SPARK-37443][PYTHON] Provide a profiler for Python/Pandas UDFs

### PR DESCRIPTION
**Pull request by ueshin**
### What changes were proposed in this pull request?

Provides a profiler for Python/Pandas UDFs.

As each profiler is connected to the `PythonUDF.resultId`, the query plan will show the `resultId`.

For example:

- run PySpark with a config `spark.python.profile=true`:

```
% ./bin/pyspark --conf spark.python.profile=true
```

- run some Python UDFs:

```py
>>> from pyspark.sql.functions import udf
>>> df = spark.range(10)

>>> @udf("long")
... def add1(x):
...   return x + 1
...
>>> @udf("long")
... def add2(x):
...   return x + 2
...
>>> added = df.select(add1("id"), add2("id"), add1("id"))

>>> added.show()
+--------+--------+--------+
|add1(id)|add2(id)|add1(id)|
+--------+--------+--------+
...
+--------+--------+--------+

>>> added.explain()
== Physical Plan ==
*(2) Project [pythonUDF0#27L AS add1(id)#5L, pythonUDF1#28L AS add2(id)#6L, pythonUDF2#29L AS add1(id)#7L]
+- BatchEvalPython [add1(id#0L)#2L, add2(id#0L)#3L, add1(id#0L)#4L], [pythonUDF0#27L, pythonUDF1#28L, pythonUDF2#29L]
   +- *(1) Range (0, 10, step=1, splits=16)

>>> sc.show_profiles()
============================================================
Profile of UDF<id=2>
============================================================
         20 function calls in 0.000 seconds

   Ordered by: internal time, cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
       10    0.000    0.000    0.000    0.000 <stdin>:1(add1)
       10    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}


============================================================
Profile of UDF<id=3>
============================================================
         20 function calls in 0.000 seconds

   Ordered by: internal time, cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
       10    0.000    0.000    0.000    0.000 <stdin>:1(add2)
       10    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}


============================================================
Profile of UDF<id=4>
============================================================
         20 function calls in 0.000 seconds

   Ordered by: internal time, cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
       10    0.000    0.000    0.000    0.000 <stdin>:1(add1)
       10    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}


```

The UDF IDs can be seen at `add1(...)#2L`, `add2(...)#3L`, `add1(...)#4L` of `BatchEvalPython`.

**Currently registered UDFs are not supported.**

### Why are the changes needed?

Currently a profiler is provided for only `RDD` operations, but providing a profiler for Python/Pandas UDFs would be great.

### Does this PR introduce _any_ user-facing change?

Yes, the profiler for Python/Pandas UDFs will work and show the results when a Spark conf `spark.python.profile` is set to `true`.

### How was this patch tested?

Added some tests and manually checked the behavior.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @JoshRosen FYI

**Comment by ueshin** [comment]
@HyukjinKwon @JoshRosen Could you take a look? Thanks!

**Review by HyukjinKwon — APPROVED** [review]
Took a cursory look, LGTM. Maybe we should also add some docs at http://spark.apache.org/docs/latest/api/python/development/debugging.html#id5 but that can be done in a separate PR.

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
