### PR TITLE
[SPARK-48691][BUILD] Upgrade scalatest related dependencies to the 3.2.19 series

### PR DESCRIPTION
**Pull request by wayneguow**
### What changes were proposed in this pull request?

This PR aims to upgrade:
-  `scalatest` to 3.2.19
- `mockto` to 5.12.0
- `selenium` to 4.21
- `bytebuddy` to 1.14.17

### Why are the changes needed?

Full release notes:

scalatest: https://github.com/scalatest/scalatest/releases/tag/release-3.2.19
mockito:
https://github.com/mockito/mockito/releases/tag/v5.12.0
https://github.com/mockito/mockito/releases/tag/v5.11.0
selenium:
https://github.com/SeleniumHQ/selenium/compare/selenium-4.17.0...selenium-4.21.0
bytebuddy:
https://github.com/raphw/byte-buddy/compare/byte-buddy-1.14.11...byte-buddy-1.14.17

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

- Pass GitHub Actions

- Manual tests:

```
build/sbt clean -Dguava.version=33.0.0-jre -Dspark.test.webdriver.chrome.driver=/opt/homebrew/bin/chromedriver -Dtest.default.exclude.tags="org.apache.spark.tags.ExtendedLevelDBTest" -Phive -Phive-thriftserver \
"core/testOnly *HistoryServerSuite"
```
```
build/sbt clean  -Dguava.version=33.0.0-jre -Dspark.test.webdriver.chrome.driver=/opt/homebrew/bin/chromedriver -Dtest.default.exclude.tags="org.apache.spark.tags.ExtendedLevelDBTest" -Phive -Phive-thriftserver \
"core/testOnly *UISeleniumSuite"
```
```
build/sbt clean  -Dguava.version=33.0.0-jre -Dspark.test.webdriver.chrome.driver=/opt/homebrew/bin/chromedriver -Dtest.default.exclude.tags="org.apache.spark.tags.ExtendedLevelDBTest" -Phive -Phive-thriftserver \
"sql/testOnly *UISeleniumSuite"
```
```
build/sbt clean  -Dguava.version=33.0.0-jre -Dspark.test.webdriver.chrome.driver=/opt/homebrew/bin/chromedriver -Dtest.default.exclude.tags="org.apache.spark.tags.ExtendedLevelDBTest" -Phive -Phive-thriftserver \
"streaming/testOnly *UISeleniumSuite"
```
```
build/sbt clean  -Dguava.version=33.0.0-jre -Dspark.test.webdriver.chrome.driver=/opt/homebrew/bin/chromedriver -Dtest.default.exclude.tags="org.apache.spark.tags.ExtendedLevelDBTest" -Phive -Phive-thriftserver \
"hive-thriftserver/testOnly *UISeleniumSuite"
```

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @panbingkun

**Comment by LuciferYang** [comment]
@wayneguow Could you please manually check the test cases with the `@ChromeUITest` tag? You can refer to https://github.com/apache/spark/pull/45174

**Comment by LuciferYang** [comment]
I haven't found the official release notes on https://github.com/scalatest/scalatest/releases yet, let's wait for a while.

**Comment by wayneguow** [comment]
> I haven't found the official release notes on https://github.com/scalatest/scalatest/releases yet, let's wait for a while.

Yes,  and I will do those test cases mentioned late.

**Review by LuciferYang — APPROVED** [review]
LGTM

**Comment by LuciferYang** [comment]
Merged into master. Thanks @wayneguow

**Pull request closed without merging**
