### PR TITLE
[SPARK-45562][DOCS] Regenerate `docs/sql-error-conditions.md` and add `42KDF` to `SQLSTATE table` in `error/README.md`

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr re-generate `docs/sql-error-conditions.md` and add `42KDF` to `SQLSTATE table` in `error/README.md` refer to https://docs.gcp.databricks.com/error-messages/sqlstates.html

image

### Why are the changes needed?
Make GA pass

https://github.com/apache/spark/actions/runs/6874376893/job/18695941494

```
[info] - SQLSTATE invariants *** FAILED *** (30 milliseconds)
[info]   fx.apply(s) was false 42KDF (SparkThrowableSuite.scala:74)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.Assertions.newAssertionFailedException(Assertions.scala:472)
[info]   at org.scalatest.Assertions.newAssertionFailedException$(Assertions.scala:471)
[info]   at org.scalatest.Assertions$.newAssertionFailedException(Assertions.scala:1231)
[info]   at org.scalatest.Assertions$AssertionsHelper.macroAssert(Assertions.scala:1295)
[info]   at org.apache.spark.SparkThrowableSuite.$anonfun$checkCondition$1(SparkThrowableSuite.scala:74)
[info]   at scala.collection.immutable.List.foreach(List.scala:333)
[info]   at org.apache.spark.SparkThrowableSuite.checkCondition(SparkThrowableSuite.scala:73)
[info]   at org.apache.spark.SparkThrowableSuite.$anonfun$new$6(SparkThrowableSuite.scala:138)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[info]   at org.scalatest.enablers.Timed$$anon$1.timeoutAfter(Timed.scala:127)
....
[info] - Error classes match with document *** FAILED *** (71 milliseconds)
[info]   "...gs-error-class.html)[
[info]   
[info]   ### XML_ROW_TAG_MISSING
[info]   
[info]   [SQLSTATE: 42KDF](sql-error-conditions-sqlstates.html#class-42-syntax-error-or-access-rule-violation)
[info]   
[info]   `<rowTag>` option is required for reading files in XML format.]" did not equal "...gs-error-class.html)[]" The error class document is not up to date. Please regenerate it. (SparkThrowableSuite.scala:346)
[info]   Analysis:
[info]   "...gs-error-class.html)[
[info] 
[info] ### XML_ROW_TAG_MISSING
[info] 
[info] [SQLSTATE: 42KDF](sql-error-conditions-sqlstates.html#class-42-syntax-error-or-access-rule-violation)
[info] 
[info] `<rowTag>` option is required for reading files in XML format.]" -> "...gs-error-class.html)[]"
```

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?

- Pass GitHub Actions
- Manual check `build/sbt   "core/testOnly *SparkThrowableSuite"`

**Before**

```
[info] Run completed in 1 second, 205 milliseconds.
[info] Total number of tests run: 19
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 17, failed 2, canceled 0, ignored 0, pending 0
[info] *** 2 TESTS FAILED ***
[error] Failed tests:
[error]         org.apache.spark.SparkThrowableSuite
```
**After**

```
[info] Run completed in 1 second, 131 milliseconds.
[info] Total number of tests run: 19
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 19, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
```

### Was this patch authored or co-authored using generative AI tooling?
No

### CODE REVIEW

**Comment by LuciferYang** [comment]
cc @HyukjinKwon @beliefer @sandip-db

**Comment by sandip-db** [comment]
LGTM. @LuciferYang  Thanks for the quick fix.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Review by beliefer — COMMENTED** [review]
late LGTM.

**Review by HyukjinKwon — COMMENTED** [review]
Thanks, LGTM

**Comment by LuciferYang** [comment]
Thanks @dongjoon-hyun @HyukjinKwon @beliefer @sandip-db

**Pull request closed without merging**
