### PR TITLE
[SPARK-12300][SQL][PYSPARK] fix schema inferance on local collections

### PR DESCRIPTION
**Pull request by holdenk**
Current schema inference for local python collections halts as soon as there are no NullTypes. This is different than when we specify a sampling ratio of 1.0 on a distributed collection. This could result in incomplete schema information.

### CODE REVIEW

**Comment by holdenk** [comment]
cc @nchammas - this is the fix for the local version of SPARK-2870

**Comment by holdenk** [comment]
ping @davies if you have a chance to look at this.

**Comment by davies** [comment]
LGTM, merging this into master, thanks!

**Comment by gatorsmile** [comment]
@holdenk Could you take a look at the test failure? I also hit this issue in my local environment without any code change. 

https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/48609/consoleFull

Thanks!

**Comment by holdenk** [comment]
I'm on vacation with less than great internet but I'll try and repro locally.

**Comment by holdenk** [comment]
ok reproed and I've got a fix (seems just a test issue from a parallel change in how missing fields can be done).

**Pull request closed without merging**
