### PR TITLE
[SPARK-33932][SS] Clean up KafkaOffsetReader API document

### PR DESCRIPTION
**Pull request by viirya**
### What changes were proposed in this pull request?

This patch cleans up KafkaOffsetReader API document.

### Why are the changes needed?

KafkaOffsetReader API documents are duplicated among KafkaOffsetReaderConsumer and KafkaOffsetReaderAdmin. It seems to be good if the doc is centralized.

This also adds missing API doc too.

### Does this PR introduce _any_ user-facing change?

No, dev only.

### How was this patch tested?

Doc only.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @gaborgsomogyi, @HeartSaVioR and @xuanyuanking FYI

**Review by gaborgsomogyi — APPROVED** [review]
LGTM.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by viirya** [comment]
Thanks @HyukjinKwon @gaborgsomogyi

**Pull request closed without merging**
