### PR TITLE
[SPARK-11362][SQL] Use Spark BitSet in BroadcastNestedLoopJoin

### PR DESCRIPTION
**Pull request by viirya**
JIRA: https://issues.apache.org/jira/browse/SPARK-11362

We use scala.collection.mutable.BitSet in BroadcastNestedLoopJoin now. We should use Spark's BitSet.

### CODE REVIEW

**Comment by viirya** [comment]
retest this please.

**Comment by viirya** [comment]
cc @liancheng

**Comment by viirya** [comment]
cc @yhuai

**Comment by davies** [comment]
LGTM, merging this into master, thanks!

**Comment by viirya** [comment]
@davies Looks like it is not merging yet?

**Pull request closed without merging**
