### PR TITLE
[SPARK-43337][UI][3.4] Asc/desc arrow icons for sorting column does not get displayed in the table column

### PR DESCRIPTION
**Pull request by maytasm**
### Why are the changes needed?
DataTables 1.10.25 broke asc/desc arrow icons for sorting column. The sorting icon is not displayed when the column is clicked to sort by asc/desc. Upgrading DataTables to 1.13.2 fixes this issue. 

### How was this patch tested?
Manual test.

### CODE REVIEW

**Comment by maytasm** [comment]
@srowen @gengliangwang 
Address issue mentioned in https://github.com/apache/spark/pull/36226#issuecomment-1530789474

**Review by dongjoon-hyun — COMMENTED** [review]
Is this the only way to fix the issue, @maytasm ?

**Review by dongjoon-hyun — DISMISSED** [review]
Please remove the following from the PR description, @maytasm .
> The 1.10.25 version of DataTables, that Spark currently uses, seems vulerable: https://security.snyk.io/package/npm/datatables.net/1.10.25. The vulnerability may not affect Spark but it is safer to update.

**Comment by maytasm** [comment]
> Is this the only way to fix the issue, @maytasm ?

No. We can also keep the current DataTables version 1.10.25 and modify the jquery.dataTables.1.10.25.min.css file by removing t`!important` i.e. 
`"../images/sort_asc.png") !important` to `"../images/sort_asc.png")`

**Comment by maytasm** [comment]
> Please remove the following from the PR description, @maytasm .
> 
> > The 1.10.25 version of DataTables, that Spark currently uses, seems vulerable: https://security.snyk.io/package/npm/datatables.net/1.10.25. The vulnerability may not affect Spark but it is safer to update.

Done

**Comment by srowen** [comment]
@dongjoon-hyun WDYT? I'm neutral on one change vs the other. I suppose modifying the CSS is a smaller change

**Comment by dongjoon-hyun** [comment]
I prefer the minimal change instead of this PR because there is no easy way for us to guarantee that new version has no regression somewhere. To be honest, actually, it's difficult for me to make it sure.

Anyway, I will not be against this PR too if people are sure about this new version.

**Comment by maytasm** [comment]
@srowen @dongjoon-hyun I don't have strong opinion either way too. However, upon thinking about it more, I am leaning toward minimal CSS change without upgrading DataTables library for the following reason:
- DataTables version upgraded to 1.13.2 is only in master branch and has not been part of any release (i.e. 3.3, 3.4) yet. Making it risky
- I am not familiar with DataTables library and have no idea about the changes between the current version and 1.13.2
- The CSS change is very simple, easy to understand, and has a very minimal surface area.  
I will put up a PR for the CSS change but will leave this PR open for a bit longer in case anyone feel strongly for upgrading DataTables to 1.13.2

**Comment by maytasm** [comment]
@srowen @dongjoon-hyun 
Here is a simple CSS fix instead: https://github.com/apache/spark/pull/41061

**Comment by srowen** [comment]
Yeah let's go with your alternative

**Pull request closed without merging**
