### PR TITLE
[SPARK-26989][CORE][TEST][2.4] DAGSchedulerSuite: ensure listeners are fully processed before checking recorded values

### PR DESCRIPTION
**Pull request by HeartSaVioR**
### What changes were proposed in this pull request?

This patch ensures accessing recorded values in listener is always after letting listeners fully process all events. To ensure this, this patch adds new class to hide these values and access with methods which will ensure above condition. Without this guard, two threads are running concurrently - 1) listeners process thread 2) test main thread - and race condition would occur.

That's why we also see very odd thing, error message saying condition is met but test failed:
```
- Barrier task failures from the same stage attempt don't trigger multiple stage retries *** FAILED ***
  ArrayBuffer(0) did not equal List(0) (DAGSchedulerSuite.scala:2656)
```
which means verification failed, and condition is met just before constructing error message.

The guard is properly placed in many spots, but missed in some places. This patch enforces that it can't be missed.

### Why are the changes needed?

UT fails intermittently and this patch will address the flakyness.

### Does this PR introduce any user-facing change?

No

### How was this patch tested?

Modified UT. 

Also made the flaky tests artificially failing via applying 50ms of sleep on each onXXX method. 

Screen Shot 2019-09-07 at 7 44 15 AM

I found 3 methods being failed. (They've marked as X. Just ignore ! as they failed on waiting listener in given timeout and these tests don't deal with these recorded values - it uses other timeout value 1000ms than 10000ms for this listener so affected via side-effect.)

When I applied same in this patch all tests marked as X passed.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Thank you so much for making this backporting PR, @HeartSaVioR .

**Comment by HeartSaVioR** [comment]
My pleasure. :)

**Comment by HeartSaVioR** [comment]
retest this, please

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Merged to branch-2.4. After review, I verified this locally, too.
Thank you, @HeartSaVioR .

**Comment by HeartSaVioR** [comment]
Thanks for the quick review!

**Pull request closed without merging**
