### PR TITLE
[WIP][SPARK-22674][PYTHON] Removed namedtuple hack and made cloudpickle the default serializer

### PR DESCRIPTION
**Pull request by HyukjinKwon**
### What changes were proposed in this pull request?

TDB

### Why are the changes needed?

TDB

### Does this PR introduce _any_ user-facing change?

TDB

### How was this patch tested?

TDB

### CODE REVIEW

**Comment by tvalentyn** [comment]
Hi, @HyukjinKwon  - do you know what are the next steps on addressing this issue? Do you plan to work on it? If not, is there any chance you can help find an owner? Thanks!

**Comment by HyukjinKwon** [comment]
I plan to remove this out at the end. Investigating.

**Comment by tvalentyn** [comment]
Thanks a lot. Some context: this monkeypatch makes it difficult for other libraries, like tensorflow-extended (tfx) to maintain interoperability for pyspark and requires rather inconvenient hacks to work around it. We would much rather prefer to fix this in pyspark instead.

Do we need help or input from other pyspark maintainers to move forward with the fix?

**Comment by rcrowe-google** [comment]
Is this fixed in Spark 3?

**Comment by tvalentyn** [comment]
According to https://github.com/apache/spark/pull/23008#issuecomment-650138470, it's not.

**Comment by Tagar** [comment]
@rcrowe-google @tvalentyn  just out of curiosity does this affect something in Tensorflow world? 

This was affecting PyTorch and was fixed from PyTorch side yesterday - https://github.com/pytorch/pytorch/pull/45870 so I was wondering if this somehow affects Tensorflow too? Thx

**Comment by hauntsaninja** [comment]
Hello! I recently got bitten by the monkeypatching of namedtuple. Anything I can do to help move this along? :-)

**Comment by HyukjinKwon** [comment]
Hey, yeah we should remove this away since cloudpickle is now backed by C-pickle (Python 3.8+) which is as fast as the regular pickle. I think we can switch to use cloudpickle after removing the hack.

**Pull request closed without merging**
