### PR TITLE
[MINOR] Avoid the 'latest' link that might vary per release in functions.scala's comment

### PR DESCRIPTION
**Pull request by HyukjinKwon**
## What changes were proposed in this pull request?

This PR propose to address https://github.com/apache/spark/pull/21318#discussion_r187843125 comment.

This is rather a nit but looks we better avoid to update the link for each release since it always points the latest (it doesn't look like worth enough updating release guide on the other hand as well).

## How was this patch tested?

N/A

### CODE REVIEW

**Comment by holdensmagicalunicorn** [comment]
@HyukjinKwon, thanks! I am a bot who has found some folks who might be able to help with the review:@gatorsmile, @rxin and @davies

**Comment by HyukjinKwon** [comment]
cc @rxin

**Comment by HyukjinKwon** [comment]
retest this please

**Review by felixcheung — APPROVED** [review]
probably a good idea. any other web link you want to change?

**Comment by HyukjinKwon** [comment]
Nope .. this is rather a followup for the PR to address the comment :-). This link particularly contains some contents that frequently changed (list of functions) release by release.

**Comment by HyukjinKwon** [comment]
Merged to master.

Thank you @felixcheung.

**Pull request closed without merging**
