### PR TITLE
[SPARK-31265][YARN] Add -XX:MaxDirectMemorySize jvm options in yarn mode

### PR DESCRIPTION
**Pull request by wang-zhun**
### What changes were proposed in this pull request?
Current memory composition `amMemory` + `amMemoryOverhead`
```
val capability = Records.newRecord(classOf[Resource])
capability.setMemory(amMemory + amMemoryOverhead)
capability.setVirtualCores(amCores)
if (amResources.nonEmpty) {
 ResourceRequestHelper.setResourceRequests(amResources, capability)
}
logDebug(s"Created resource capability for AM request: $capability")

...

 // Add Xmx for AM memory 
javaOpts += "-Xmx" + amMemory + "m"
```
It is possible that the physical memory of the container exceeds the limit and is killed by yarn.
I suggest setting `-XX:MaxDirectMemorySize` here
```
// Add Xmx for AM memory
 javaOpts += s"-Xmx${amMemory}m"
if (isClusterMode) {
   javaOpts += s"-XX:MaxDirectMemorySize=${amMemoryOverhead}m"
 }
```

### How was this patch tested?
Tested by verifying JVM parameters in the following cases:
- client and cluster mode

### CODE REVIEW

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
Thank you for your first contribution, @wang-zhun .
Did you try to use the existing `spark.yarn.am.memoryOverhead`, `spark.yarn.am.extraJavaOptions` and `spark.executor.extraJavaOptions`?

**Comment by dongjoon-hyun** [comment]
I guess the above configuration helps your situation and close this PR.
Please let us know if the above is insufficient.

**Comment by wang-zhun** [comment]
@dongjoon-hyun Thanks for your responses and suggestions

**Comment by wang-zhun** [comment]
In my opinion memory is mainly composed of two parts:
1.On-heap(amMemory)
2.Off-heap(amMemoryOverhead)
When we don't set `spark.yarn.am.memoryOverhead`, There is also a default value `math.max((MEMORY_OVERHEAD_FACTOR * amMemory).toLong, MEMORY_OVERHEAD_MIN)`, It seems unreasonable to pass `extraJavaOptions`, So here I suggest setting it in the code `-XX:MaxDirectMemorySize=amMemoryOverhead`.

**Comment by dongjoon-hyun** [comment]
Netty library itself also use some off-heap memory.

**Comment by wang-zhun** [comment]
@dongjoon-hyun thanks for the reply. 
I think the `amMemoryOverhead` represents the usable off-heap memory. `amMemory` only means on-heap memory. Add `MaxDirectMemorySize` to better limit the off-heap memory. Of course, our Netty library also occupies this part.

**Comment by dongjoon-hyun** [comment]
@wang-zhun . I'm not saying you are completely wrong. Apache Spark doesn't directly set `-XX:MaxDirectMemorySize` by using `spark.driver.memoryOverhead`, does it? Instead, Apache Spark aims to advise the users to set `JVM` options properly if needed. The above existing configurations exist for that purpose. This PR just break the existing customer environments by introducing a conflict. We don't know what JVM conf is applied. In general, this PR is not aligned to Apache Spark behavior.

**Comment by wang-zhun** [comment]
@dongjoon-hyun Thanks for your advice.

**Comment by dongjoon-hyun** [comment]
Thank you, @wang-zhun .

**Pull request closed without merging**
