### PR TITLE
[SPARK-48829][BUILD] Upgrade `RoaringBitmap` to 1.2.1

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to upgrade `RoaringBitmap` from `1.1.0` to `1.2.1`.

### Why are the changes needed?
- The full release notes: https://github.com/RoaringBitmap/RoaringBitmap/releases/tag/1.2.0
- The latest version has brought bug fixes and some improvements:
  improve: Optimize RoaringBitSet.get(int fromIndex, int toIndex) https://github.com/RoaringBitmap/RoaringBitmap/pull/727
  fix: add bitmapOfRange (non-static) in https://github.com/RoaringBitmap/RoaringBitmap/pull/728

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by panbingkun** [comment]
org.apache.spark.MapStatusesConvertBenchmark
JDK 17: https://github.com/panbingkun/spark/actions/runs/9832998545
JDK 21: https://github.com/panbingkun/spark/actions/runs/9833002646

**Comment by LuciferYang** [comment]
ready to go?

**Comment by panbingkun** [comment]
> ready to go?

Yea, ready for review, thanks!

**Review by LuciferYang — APPROVED** [review]

**Comment by LuciferYang** [comment]
Merged into master. Thanks @panbingkun

**Comment by dongjoon-hyun** [comment]
Thank you, @panbingkun and @LuciferYang .

**Pull request closed without merging**
