### PR TITLE
[SPARK-16416] [Core] force eager creation of loggers to avoid shutdown hook conflicts

### PR DESCRIPTION
**Pull request by mikaelstaldal**
## What changes were proposed in this pull request?

Force eager creation of loggers to avoid shutdown hook conflicts.
## How was this patch tested?

Manually tested with a project using Log4j 2, verified that the shutdown hook conflict issue was solved.

### CODE REVIEW

**Comment by srowen** [comment]
This doesn't seem to be the change discussed in the JIRA

**Comment by mikaelstaldal** [comment]
It is, I just had to apply the same in several places.

**Comment by srowen** [comment]
Should just be necessary in the ShutdownHookManager?

**Comment by mikaelstaldal** [comment]
I realized that it is necessary everywhere where you register a shutdown hook, if you log from within the shutdown hook.

Another way to solve it would be to refrain to log from within shutdown hooks.

**Comment by srowen** [comment]
OK, seems reasonable to me as is.

**Comment by srowen** [comment]
Jenkins test this please

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
