### PR TITLE
[SPARK-27713][SQL] Move org.apache.spark.sql.execution.* in catalyst to core

### PR DESCRIPTION
**Pull request by xy-xin**
## What changes were proposed in this pull request?

`RecordBinaryComparator`, `UnsafeExternalRowSorter` and `UnsafeKeyValueSorter` now locates in catalyst, which should be moved to core, as they're used only in physical plan.

## How was this patch tested?

exist tests.

### CODE REVIEW

**Comment by xianyinxin** [comment]
cc @cloud-fan @JoshRosen @gatorsmile

**Comment by cloud-fan** [comment]
ok to test

**Comment by cloud-fan** [comment]
makes sense to me

**Comment by HyukjinKwon** [comment]
Yup, makes sense to me too

**Comment by kiszk** [comment]
Looks good

**Comment by JoshRosen** [comment]
👍 from me, especially since these classes are low-level and internal to Spark (so I think there's no risk of breaking third-party packages).

**Comment by viirya** [comment]
Makes sense. The related test suite `RecordBinaryComparatorSuite` is in core, too.

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Comment by xianyinxin** [comment]
Thanks. @cloud-fan @HyukjinKwon @kiszk @JoshRosen @viirya

**Pull request closed without merging**
