### PR TITLE
[SPARK-9928][SQL] Removal of LogicalLocalTable 

### PR DESCRIPTION
**Pull request by gatorsmile**
LogicalLocalTable in ExistingRDD.scala is replaced by localRelation in LocalRelation.scala?

Do you know any reason why we still keep this class?

### CODE REVIEW

**Comment by gatorsmile** [comment]
The failure of this test case is not related to the code changes.

**Comment by gatorsmile** [comment]
retest this please.

**Comment by gatorsmile** [comment]
@srowen Could you review the changes? Thanks!

**Comment by gatorsmile** [comment]
Another case failed due to the same reasons. 
```
[error] Test org.apache.spark.ml.util.JavaDefaultReadWriteSuite.testDefaultReadWrite failed: java.lang.IllegalStateException: Cannot call methods on a stopped SparkContext.
```

Timing issues? Or introduced by a recent merge?

**Comment by cloud-fan** [comment]
retest this please.

**Comment by cloud-fan** [comment]
the tests are quite flaky now, we are fixing it.

**Comment by cloud-fan** [comment]
LGTM cc @yhuai

**Comment by yhuai** [comment]
Merging to master and branch 1.6.

**Comment by gatorsmile** [comment]
Thanks!

**Pull request closed without merging**
