### PR TITLE
[SPARK-32135] Show Spark Driver name on Spark history web page

### PR DESCRIPTION
**Pull request by Gaurangi94**
### What changes were proposed in this pull request?
Display driver host name on History UI page. https://issues.apache.org/jira/browse/SPARK-32135

### Why are the changes needed?

Our service dynamically creates short-lived YARN clusters in cloud. Spark applications run on these dynamically created clusters. Log data for these applications is stored on a remote file-system. We configure a static instance of SparkHistoryServer to view information on jobs that ran on these clusters. 

Since we are using a single History Server for multiple clusters, it will be useful for users to have information on where the jobs were executed. We would like to display this information on the main web-page, instead of having users go through multiple links to retrieve this information.

We chose to display driverHost on the web-page as it reflects cluster name. If this information is not available we leave cluster name as blank. 

### Does this PR introduce _any_ user-facing change?
Yes
image-2020-09-02-12-37-55-860

### How was this patch tested?
Added driverHost to json files to verify HTTP response. Ran HistoryServerSuite.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
@Gaurangi94 can you show a screenshot after this fix?

**Comment by Gaurangi94** [comment]
> @Gaurangi94 can you show a screenshot after this fix?

The screenshot is in the JIRA filed by us.  https://issues.apache.org/jira/browse/SPARK-32135

**Comment by tgravescs** [comment]
so I'm a little worried this is going to clutter the UI and not be useful in many situations. the driver host on very large clusters could be any number of thousands of hosts and I don't see its usefulness on the top level page in a normal single cluster instance, people use the app id.   So even here, you are using the host name to indicate what cluster, but what are you using that for?  Just sorting?

also you may have your hostnames setup so that you can tell the cluster, but others may not, it might just be host1.foo.com, host2.foo.com, etc.   Are you running in standalone mode?  Wouldn't master node be more useful and reliable? 

either way if we do allow this we may consider adding a toggle button to not show in my cases.

**Comment by gatorsmile** [comment]
cc @gengliangwang

**Comment by Gaurangi94** [comment]
> so I'm a little worried this is going to clutter the UI and not be useful in many situations. the driver host on very large clusters could be any number of thousands of hosts and I don't see its usefulness on the top level page in a normal single cluster instance, people use the app id. So even here, you are using the host name to indicate what cluster, but what are you using that for? Just sorting?
> 
> also you may have your hostnames setup so that you can tell the cluster, but others may not, it might just be host1.foo.com, host2.foo.com, etc. Are you running in standalone mode? Wouldn't master node be more useful and reliable?
> 
> either way if we do allow this we may consider adding a toggle button to not show in my cases.



> so I'm a little worried this is going to clutter the UI and not be useful in many situations. the driver host on very large clusters could be any number of thousands of hosts and I don't see its usefulness on the top level page in a normal single cluster instance, people use the app id. So even here, you are using the host name to indicate what cluster, but what are you using that for? Just sorting?
> 
> also you may have your hostnames setup so that you can tell the cluster, but others may not, it might just be host1.foo.com, host2.foo.com, etc. Are you running in standalone mode? Wouldn't master node be more useful and reliable?
> 
> either way if we do allow this we may consider adding a toggle button to not show in my cases.

Hello,

I have updated the description of my PR to better describe our use-case. Apologies for the confusion here. We could add master node too if that seems to be better applicable to other use-cases as well.

Thanks!

**Pull request closed without merging**
