### PR TITLE
SPARK-4660: Use correct default classloader in JavaSerializer.

### PR DESCRIPTION
**Pull request by pkolaczk**

### CODE REVIEW

**Comment by pwendell** [comment]
Jenkins, test this please.

**Comment by andrewor14** [comment]
This seems to be failing from a known python imports issue in branch-1.1 not related to this patch.

**Comment by pwendell** [comment]
@pkolaczk can you make a version of this pull request against the master branch?

**Comment by pkolaczk** [comment]
Yes, I can.

**Comment by pwendell** [comment]
@pkolaczk - any luck with the master PR

**Comment by jacek-lewandowski** [comment]
@pwendell here are pull requests for 1.2 and master branches respectively:
https://github.com/apache/spark/pull/4114
https://github.com/apache/spark/pull/4113

@pkolaczk is on vacation so he asked me to prepare these PRs

**Comment by pwendell** [comment]
Okay I've merged this into all the relevant branches. Can you close this issue?

**Comment by jacek-lewandowski** [comment]
I cannot, @pkolaczk can do this

**Pull request closed without merging**
