### PR TITLE
[SPARK-24771][BUILD]Upgrade Apache AVRO to 1.8.2

### PR DESCRIPTION
**Pull request by gengliangwang**
## What changes were proposed in this pull request?

Upgrade Apache Avro from 1.7.7 to 1.8.2. The major new features:

1. More logical types. From the spec of 1.8.2 https://avro.apache.org/docs/1.8.2/spec.html#Logical+Types we can see comparing to [1.7.7](https://avro.apache.org/docs/1.7.7/spec.html#Logical+Types), the new version support:
    - Date
    - Time (millisecond precision)
    - Time (microsecond precision)
    - Timestamp (millisecond precision)
    - Timestamp (microsecond precision)
    - Duration

2. Single-object encoding: https://avro.apache.org/docs/1.8.2/spec.html#single_object_encoding

This PR aims to update Apache Spark to support these new features.

## How was this patch tested?

Unit test

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

Thank you, @gengliangwang .

**Comment by gatorsmile** [comment]
Please do not merge it.

**Review by HyukjinKwon — COMMENTED** [review]
I am not going to merge this but the change itself seems right

**Comment by dongjoon-hyun** [comment]
Hi, @gatorsmile .
Could you review this PR? I'm wondering if we can have this for Spark 2.4 before branch-cut.

**Comment by gatorsmile** [comment]
retest this please

**Comment by gatorsmile** [comment]
LGTM pending Jenkins

**Comment by gatorsmile** [comment]
retest this please

**Comment by gatorsmile** [comment]
Thanks! Merged to master.

**Pull request closed without merging**
