### PR TITLE
[MINOR][SQL] Not dropping all necessary tables

### PR DESCRIPTION
**Pull request by techaddict**
## What changes were proposed in this pull request?

was not dropping table `parquet_t3`
## How was this patch tested?

tested `LogicalPlanToSQLSuite` locally

### CODE REVIEW

**Comment by techaddict** [comment]
jenkins retest this please

**Comment by techaddict** [comment]
cc: @srowen

**Comment by srowen** [comment]
@techaddict I missed this, is it still relevant?

**Comment by techaddict** [comment]
@srowen yes, the issue is still there.

**Comment by srowen** [comment]
Merged to master/2.0 as that was obviously the intent of the test cleanup logic

**Pull request closed without merging**
