### PR TITLE
[SPARK-8027] [SPARKR] Move man pages creation to install-dev.sh

### PR DESCRIPTION
**Pull request by shivaram**
This also helps us get rid of the sparkr-docs maven profile as docs are now built by just using -Psparkr when the roxygen2 package is available

Related to discussion in #6567 

cc @pwendell @srowen -- Let me know if this looks better

### CODE REVIEW

**Comment by pwendell** [comment]
Yeah this seems strictly better

**Comment by shivaram** [comment]
@pwendell I'll wait for @srowen to take a look before merging this -- I'll also send a PR to github.com/pwendell/spark-utils before merging.

**Comment by shivaram** [comment]
@srowen Did you get a chance to look at this ?

**Comment by srowen** [comment]
Yeah thanks I think that helps a lot to keep the R bits out of core. If it works, go for it.

**Pull request closed without merging**
