### PR TITLE
[SPARK-27579][SQL] remove BaseStreamingSource and BaseStreamingSink

### PR DESCRIPTION
**Pull request by cloud-fan**
## What changes were proposed in this pull request?

`BaseStreamingSource` and `BaseStreamingSink` is used to unify v1 and v2 streaming data source API in some code paths.

This PR removes these 2 interfaces, and let the v1 API extend v2 API to keep API compatibility.

The motivation is https://github.com/apache/spark/pull/24416 . We want to move data source v2 to catalyst module, but `BaseStreamingSource` and `BaseStreamingSink` are in sql/core.

## How was this patch tested?

existing tests

### CODE REVIEW

**Comment by cloud-fan** [comment]
cc @jose-torres @gatorsmile

**Comment by gatorsmile** [comment]
cc @jose-torres Please help review this PR.

**Comment by jose-torres** [comment]
lgtm

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Pull request closed without merging**
