### PR TITLE
[SPARK-33274][SS] Stop query in cp mode when total cores less than total kafka partition

### PR DESCRIPTION
**Pull request by warrenzhu25**
What changes were proposed in this pull request?
Add check for total executor cores when SetReaderPartitions message received.

Why are the changes needed?
In continuous processing mode, EpochCoordinator won't add offsets to query until got ReportPartitionOffset from all partitions. Normally, each kafka topic partition will be handled by one core, if total cores is smaller than total kafka topic partition counts, the job will hang without any error message.

Does this PR introduce any user-facing change?
Yes, if total executor cores is smaller than total kafka partition count, the exception with below error will be thrown:
`
Total $numReaderPartitions (kafka partitions) * $cpusPerTask (cpus per task) =
$neededCores needed,
but only have min($numExecutors (executors) * $coresPerExecutor (cores per executor) =
$totalRequestedCores, spark.cores.max = $maxCores) = $totalAvailableCores (total cores).
Please increase total number of executor cores to at least $neededCores.
`

How was this patch tested?
Added test in EpochCoordinatorSuite

### CODE REVIEW

**Review by tardunge — APPROVED** [review]

**Comment by tardunge** [comment]
sorry, didn't mean to approve.

**Comment by warrenzhu25** [comment]
@HeartSaVioR @xuanyuanking @gaborgsomogyi @viirya Could you help take a look?

**Comment by warrenzhu25** [comment]
@Ngone51 @viirya @HeartSaVioR @xuanyuanking @gaborgsomogyi Could you help take a look at this?

**Comment by warrenzhu25** [comment]
@Ngone51 @viirya @HeartSaVioR @xuanyuanking @gaborgsomogyi Could you help take a look at this?

**Pull request closed without merging**
