### PR TITLE
[SPARK-50224][SQL] The replacements of IsValidUTF8|ValidateUTF8|TryValidateUTF8|MakeValidUTF8 shall be NullIntolerant

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

This PR makes replacements of IsValidUTF8|ValidateUTF8|TryValidateUTF8|MakeValidUTF8 functions to be NullIntolerant deriving from their origins so that we can actually construct IsNotNull constraints for them.

This is also a common issue for other RuntimeReplaceable expressions, I will revisit them in groups. SPARK-50223.

### Why are the changes needed?

Common strategy for performance improvement.

### Does this PR introduce _any_ user-facing change?
NO

### How was this patch tested?

new tests

### Was this patch authored or co-authored using generative AI tooling?

no

### CODE REVIEW

**Comment by yaooqinn** [comment]
cc @cloud-fan @dongjoon-hyun @LuciferYang thanks

**Review by LuciferYang — APPROVED** [review]

**Comment by yaooqinn** [comment]
Merged to master, thank you @LuciferYang

**Review by dongjoon-hyun — COMMENTED** [review]
+1, late LGTM.

**Comment by cloud-fan** [comment]
I agree with the problem here but I'm not quite sure if this is the right fix. This is not the first time that we are restricted by the trait-based tagging system. Extending a trait is static as it happens at compile but we really want to be more dynamic at runtime. For example, we added `Expression#stateful` and removed the trait `StatefulExpression` a while ago. I think the same thing happens to `NullIntelerant` now. Shall we also add `Expression#nullIntolerant`?

Another example is `trait Nondeterministic`. We may hit the same issue in the future and try to remove it.

**Comment by yaooqinn** [comment]
Hi @cloud-fan, I understand the issue you've mentioned but it seems beyond the scope of the issue of this PR, which might introduce a lot of code refactoring. We can raise another JIRA ticket to track?

**Pull request closed without merging**
