### PR TITLE
[SPARK-33840][DOCS] Add spark.sql.files.minPartitionNum to performence tuning doc

### PR DESCRIPTION
**Pull request by ulysses-you**
### What changes were proposed in this pull request?

Add `spark.sql.files.minPartitionNum` and it's description to sql-performence-tuning.md.

### Why are the changes needed?

Help user to find it.

### Does this PR introduce _any_ user-facing change?

Yes, it's the doc.

### How was this patch tested?

Pass CI.

### CODE REVIEW

**Comment by ulysses-you** [comment]
Maybe it's better to do it in a followup with that PR, but I just create a JIRA ..
cc @maropu @dongjoon-hyun @HyukjinKwon

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master and branch-3.1.

**Comment by maropu** [comment]
late lgtm

**Comment by ulysses-you** [comment]
thanks for merging !

**Pull request closed without merging**
