### PR TITLE
[SPARK-24188][core] Restore "/version" API endpoint.

### PR DESCRIPTION
**Pull request by vanzin**
It was missing the jax-rs annotation.

### CODE REVIEW

**Review by felixcheung — APPROVED** [review]

**Comment by mgaido91** [comment]
LGTM

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Review by jiangxb1987 — APPROVED** [review]
LGTM

**Comment by jerryshao** [comment]
LGTM, merging to master and branch 2.3.

**Pull request closed without merging**
