### PR TITLE
[SPARK-21963][CORE][TEST]Create temp file should be delete after use

### PR DESCRIPTION
**Pull request by heary-cao**
## What changes were proposed in this pull request?

After you create a temporary table, you need to delete it, otherwise it will leave a file similar to the file name ‘SPARK194465907929586320484966temp’.

## How was this patch tested?

N / A

### CODE REVIEW

**Comment by srowen** [comment]
This is too trivial to bother with. The JVM cleans this on shutdown anyway.

**Comment by kiszk** [comment]
Is it better to use ` DELETE_ON_CLOSE`?

**Comment by kiszk** [comment]
How about other test cases that use `File.createTempFile`? Did they clean the temp file correctly?

**Comment by heary-cao** [comment]
@kiszk thank you for review it.
I checked the other test cases that use ` File.createTempFile` and `Files.createTempFile `.
Except as described in this PR, others test cases that already use `File.deleteOnExit` or` File.delete`.
thanks.

**Comment by jerryshao** [comment]
This seems not a big problem, all the temp files are created under `target/tmp`, this can be cleaned by `mvn clean` or `sbt clean`.

**Comment by srowen** [comment]
Same, let's not bother with stuff this trivial @heary-cao please. 
If it really makes the code consistent on this one point, I'm not against this, other than that it encourages more PRs this small.

**Comment by srowen** [comment]
Merged to master anyway.

**Pull request closed without merging**
