### PR TITLE
[SPARK-32511][SQL][FOLLOWUP] Fix the broken build for Scala 2.13 with Maven

### PR DESCRIPTION
**Pull request by sarutak**
### What changes were proposed in this pull request?

This PR fixes the broken build for Scala 2.13 with Maven.
https://github.com/apache/spark/pull/29913/checks?check_run_id=1187826966

#29795 was merged though it doesn't successfully finish the build for Scala 2.13

### Why are the changes needed?

To fix the build.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

`build/mvn -Pscala-2.13 -Phive -Phive-thriftserver -DskipTests package`

### CODE REVIEW

**Comment by sarutak** [comment]
This compilation error will be fixed by #29955 .

**Comment by sarutak** [comment]
retest this please.

**Comment by sarutak** [comment]
cc: @srowen

**Review by srowen — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
+1, LGTM. Thank you, @sarutak and @srowen .

**Pull request closed without merging**
