### PR TITLE
[SPARK-19240][SQL][TEST] add test for setting location for managed table

### PR DESCRIPTION
**Pull request by cloud-fan**
## What changes were proposed in this pull request?

SET LOCATION can also work on managed table(or table created without custom path), the behavior is a little weird, but as we have already supported it, we should add a test to explicitly show the behavior.

## How was this patch tested?

N/A

### CODE REVIEW

**Comment by cloud-fan** [comment]
cc @yhuai @gatorsmile

**Review by gatorsmile — APPROVED** [review]
Based on the current way, we should not allow users to change the location for the managed table. The definition of `EXTERNAL` is different between Hive and Spark. When users provide a path in Spark SQL, we do not drop the data.  This is our rule. Following this rule, if we allow it, we also need to change the type to `EXTERNAL`. 

LGTM cc @yhuai

**Comment by yhuai** [comment]
I am not sure if it is worth breaking this behavior. If the table is a managed table, it is possible that existing behavior allows users to move a table from one managed place to another managed place (e.g. the location of a database is changed). It is not clear that breaking this behavior can give us any benefit.

**Comment by gatorsmile** [comment]
Just FYI, this only test the behaviors of InMemoryCatalog. I will port it to `HiveDDLSuite` in https://github.com/apache/spark/pull/16592

**Comment by gatorsmile** [comment]
retest this please

**Comment by cloud-fan** [comment]
thanks for the review, merging to master!

**Pull request closed without merging**
