### PR TITLE
[SPARK-23984][K8S][Test] Added Integration Tests for PySpark on Kubernetes

### PR DESCRIPTION
**Pull request by ifilonenko**
## What changes were proposed in this pull request?

I added integration tests for PySpark ( + checking JVM options + RemoteFileTest) which wasn't properly merged in the initial integration test PR. 

## How was this patch tested?

I tested this with integration tests using:

`dev/dev-run-integration-tests.sh --spark-tgz spark-2.4.0-SNAPSHOT-bin-2.7.3.tgz`

### CODE REVIEW

**Comment by ifilonenko** [comment]
@ssuchter @holdenk @mccheah for review

**Comment by ifilonenko** [comment]
I don't know if Jenkins build a distribution with `--pip`. TBD based on success. But locally, this worked when I ran: 
`dev/make-distribution.sh --pip --tgz -Phadoop-2.7 -Pkubernetes`

**Comment by ifilonenko** [comment]
retest this please

**Comment by ifilonenko** [comment]
retest this please

**Comment by ifilonenko** [comment]
retest this please

**Comment by ifilonenko** [comment]
This PR is now just waiting on appropriate changes to `bin/docker-image-tool.sh` which are contained in the following PR: #21551 . Will wait until that is merged.

**Comment by ifilonenko** [comment]
retest this please

**Comment by ifilonenko** [comment]
retest this please

**Comment by foxish** [comment]
@ifilonenko, is this ready to go?

**Comment by ifilonenko** [comment]
The problem is due to the version of Docker @foxish Can we update the Docker version on the nodes? @shaneknapp

**Comment by foxish** [comment]
@ifilonenko, can you elaborate on what the issue is and what version of docker is needed?

**Comment by ifilonenko** [comment]
@foxish The problem is the same as described here: https://github.com/moby/moby/issues/32457 which should have been solved in `Docker 17.05`. As such, this is prompted by a deprecated version Docker and I am waiting for update to happen on the Jenkins nodes (as locally this works perfectly fine with the newest version of Docker).

**Comment by shaneknapp** [comment]
@ifilonenko and @foxish, i will get to the docker upgrade this coming week.

**Comment by shaneknapp** [comment]
actually, i think we're running a supported version of docker:
```sknapp@amp-jenkins-staging-worker-02:~$ docker -v
Docker version 17.05.0-ce, build 89658be
```

**Comment by shaneknapp** [comment]
@ifilonenko -- ok, got it.

the irritating news is that docker installs have changed significantly since i last did our ansible, so it'll take me a couple of hours to refactor and get it working w/the new packages and gpg sigs.

if it looks like this is taking too much time, i can just do things manually and punt on ansible for now.

**Comment by shaneknapp** [comment]
done.

```$ for x in 1 2; do ssh amp-jenkins-staging-worker-0${x} docker -v; done
Docker version 18.03.1-ce, build 9ee9f40
Docker version 18.03.1-ce, build 9ee9f40
```

**Comment by ifilonenko** [comment]
retest this please

**Comment by shaneknapp** [comment]
test this please

**Comment by ifilonenko** [comment]
retest this please

**Comment by shaneknapp** [comment]
@ifilonenko -- minikube is updated to v0.28.0:

```
$ pssh -h ubuntu_workers.txt -i "minikube version"
[1] 12:37:23 [SUCCESS] amp-jenkins-staging-worker-01.amp
minikube version: v0.28.0
[2] 12:37:24 [SUCCESS] amp-jenkins-staging-worker-02.amp
minikube version: v0.28.0
```

we're still running the deprecated kvm drivers, but i will be testing and deploying the fully supported kvm2 drivers in the next couple of days.

**Comment by shaneknapp** [comment]
test this please

**Comment by shaneknapp** [comment]
test this please

**Comment by shaneknapp** [comment]
test this please

**Comment by shaneknapp** [comment]
for the love of all thats holy, test this please

**Comment by mccheah** [comment]
retest this please

**Comment by shaneknapp** [comment]
test this please OR ELSE

**Comment by shaneknapp** [comment]
test this please and work for real this time

**Comment by shaneknapp** [comment]
test this please as im running out of funny real quick

**Comment by shaneknapp** [comment]
test this please

**Comment by shaneknapp** [comment]
test this please, this time w/o a fetch timeout :(

**Comment by shaneknapp** [comment]
test this pease

**Comment by shaneknapp** [comment]
test this please

**Comment by shaneknapp** [comment]
test this please

**Comment by shaneknapp** [comment]
test this please

**Comment by shaneknapp** [comment]
test this please

**Comment by shaneknapp** [comment]
test this please

**Comment by shaneknapp** [comment]
test this please

**Comment by shaneknapp** [comment]
test this please

**Comment by ifilonenko** [comment]
@mccheah
@foxish
Can we merge?

**Comment by mccheah** [comment]
Yeah let's merge this - think there might be some work to clean this up a bit later.

**Pull request closed without merging**
