### PR TITLE
[SQL][MINOR] Remove misleading comment (and tags do better)

### PR DESCRIPTION
**Pull request by jaceklaskowski**
## What changes were proposed in this pull request?

Misleading comment removed (and tags do a better job to express instability)

## How was this patch tested?

Local build

### CODE REVIEW

**Comment by srowen** [comment]
Nothing here explains why you think it's misleading

**Comment by jaceklaskowski** [comment]
Fair enough. Let's do it here. Quoting directly from the code:

> Converts a logical plan into zero or more SparkPlans.  This API is exposed for experimenting with the query planner and is not designed to be stable across spark releases.  Developers writing libraries should instead consider using the stable APIs provided in [[org.apache.spark.sql.sources]]

> Converts a logical plan into zero or more SparkPlans.

It does not. It's a type alias for something that may do so. And moreover it's copied from `SparkStrategy`. No need for repeating it here.

> This API is exposed for experimenting with the query planner and is not designed to be stable across spark releases.

That's the purpose of `@DeveloperApi` and `@InterfaceStability.Unstable` annotations so, yes, you're right, it's not misleading, but a repetition (that cannot be checked by the Scala compiler).

> Developers writing libraries should instead consider using the stable APIs provided in [[org.apache.spark.sql.sources]]

How does `org.apache.spark.sql.sources` help here?! `SparkStrategy` is about query planning not DataSource IO. They're at different levels and may interest different developers. Certainly misleading.

WDYT?

**Comment by srowen** [comment]
@rxin would be able to judge this

**Comment by rxin** [comment]
Hm I don't think the comment makes sense ...

**Comment by jaceklaskowski** [comment]
Is the comment correct then? I don't think so. What about improving it? I don't mind if we stop discussing it either. It's a tiny change after all (and don't want to drag it along and waste your time).

**Pull request closed without merging**
