### PR TITLE
[SPARK-43292][CORE][CONNECT] Move `ExecutorClassLoader` to `core` module and simplify `Executor#addReplClassLoaderIfNeeded`

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr move `ExecutorClassLoader` from `repl` module to `core` module an put it into `executor` package, then `ArtifactManagerSuite` can test using maven.

On the other hand, this pr removed reflection calls in the `Executor#addReplClassLoaderIfNeeded` due to `ExecutorClassLoader` and `Executor` are in the same module after this pr.

### Why are the changes needed?
1. `ExecutorClassLoader` only be used by `Executor`, it is more suitable for placing in the `core` module
2. Make `ArtifactManagerSuite` can test using maven.

### Does this PR introduce _any_ user-facing change?
No, just for maven test

### How was this patch tested?
- Pass GitHub Actions
- Manual test

Run the following commands

```
build/mvn clean install -DskipTests -Phive 
build/mvn test -pl connector/connect/server 
```

**Before**

`ArtifactManagerSuite` test failed due to:

```
23/04/26 16:36:57.140 ScalaTest-main-running-DiscoverySuite ERROR Executor: Could not find org.apache.spark.repl.ExecutorClassLoader on classpath!
```

**After** 

All tests passed.

```
Run completed in 10 seconds, 494 milliseconds.
Total number of tests run: 560
Suites: completed 11, aborted 0
Tests: succeeded 560, failed 0, canceled 0, ignored 0, pending 0
All tests passed.
```

### CODE REVIEW

**Comment by hvanhovell** [comment]
@LuciferYang can we just move the RemoteClassLoader to spark/core?

**Comment by LuciferYang** [comment]
SGTM,  Let GA test it first

**Comment by LuciferYang** [comment]
@hvanhovell Is it better to keep `ExecutorClassLoader` in `org.apache.spark.repl` or move it to other package, like `org.apache.spark.executor`?

**Comment by LuciferYang** [comment]
will update pr title and description later if all test pass

**Comment by hvanhovell** [comment]
Yeah let's put it in `org.apache.spark.executor`.

**Comment by hvanhovell** [comment]
@LuciferYang can you also get rid of the reflection in Executor.scala that used to be needed?

**Comment by LuciferYang** [comment]
> @LuciferYang can you also get rid of the reflection in Executor.scala that used to be needed?

I'll look this today, and I think there should be no need to use reflection anymore.

**Comment by hvanhovell** [comment]
@LuciferYang is this one good to go?

**Review by hvanhovell — APPROVED** [review]
LGTM

**Comment by LuciferYang** [comment]
I think this one is ok

**Comment by hvanhovell** [comment]
Alrighty

**Comment by hvanhovell** [comment]
Merged!

**Comment by LuciferYang** [comment]
Thanks @hvanhovell ~

**Review by dongjoon-hyun — COMMENTED** [review]
+1, LGTM. Thank you!

**Pull request closed without merging**
