### PR TITLE
[SPARK-48242][BUILD] Upgrade extra-enforcer-rules to 1.8.0

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to upgrade `extra-enforcer-rules to 1.8.0` from `1.7.0` to `1.8.0`.

### Why are the changes needed?
The full release notes:
https://github.com/mojohaus/extra-enforcer-rules/releases/tag/1.8.0

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
- Manually test.
```
sh dev/test-dependencies.sh
```
- Pass GA.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by panbingkun** [comment]
cc @dongjoon-hyun

**Comment by LuciferYang** [comment]
The change pipeline doesn't include Maven build tests now. Have you manually confirmed the validity of the upgrade?

**Comment by panbingkun** [comment]
> The change pipeline doesn't include Maven build tests now. Have you manually confirmed the validity of the upgrade?

Yeah, I have verified it in the last `scala-2.13.14 upgrade`. Let me verify it again. Wait a moment.

**Comment by panbingkun** [comment]
checking process as follows:
1.When I delete the following and execute `sh dev/test-dependencies.sh`, the error is as follows:
  image
  image

2.When I restore (only update `extra-enforcer-rules` from `1.7.0` to `1.8.0`) and execute `sh dev/test-dependencies.sh`, the results are as follows:
  image

Meet expectations.

**Review by LuciferYang — APPROVED** [review]
+1, LGTM

**Comment by LuciferYang** [comment]
Merged into master for Spark 4.0. Thanks @panbingkun

**Pull request closed without merging**
