### PR TITLE
[SPARK-7572][MLLIB] do not import Param/Params under pyspark.ml

### PR DESCRIPTION
**Pull request by mengxr**
Remove `Param` and `Params` from `pyspark.ml` and add a section in the doc. @brkyvz

### CODE REVIEW

**Comment by brkyvz** [comment]
LGTM

**Comment by mengxr** [comment]
test this please

**Comment by mengxr** [comment]
The failed test was known to be flaky (SPARK-7497).

**Comment by mengxr** [comment]
Merged into master and branch-1.4.

**Pull request closed without merging**
