### PR TITLE
[SPARK-48661][BUILD] Upgrade `RoaringBitmap` to 1.1.0

### PR DESCRIPTION
**Pull request by wayneguow**
### What changes were proposed in this pull request?

This PR aims to upgrade `RoaringBitmap` to 1.1.0.

### Why are the changes needed?

There are some bug fixes in `RoaringBitmap` 1.1.0:
Fix RunContainer#contains(BitmapContainer) (https://github.com/RoaringBitmap/RoaringBitmap/issues/721) by @LeeWorrall in https://github.com/RoaringBitmap/RoaringBitmap/pull/722
Fix ArrayContainer#contains(RunContainer) (https://github.com/RoaringBitmap/RoaringBitmap/issues/723) by @LeeWorrall in https://github.com/RoaringBitmap/RoaringBitmap/pull/724

Full release note:
https://github.com/RoaringBitmap/RoaringBitmap/releases/tag/1.1.0

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass GA.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by wayneguow** [comment]
Waiting for the latest version to be released in the maven central repo.

**Comment by LuciferYang** [comment]
please update the benchmark result of `MapStatusesConvertBenchmark`

**Comment by wayneguow** [comment]
> @wayneguow please update the benchmark result of `MapStatusesConvertBenchmark`

@LuciferYang Thanks for your guidance, I have added the latest benchmark data.
jdk17: https://github.com/wayneguow/spark/actions/runs/9592491598
jdk21: https://github.com/wayneguow/spark/actions/runs/9592917394

**Review by LuciferYang — APPROVED** [review]
LGTM(pending tests)

**Review by yaooqinn — APPROVED** [review]

**Comment by LuciferYang** [comment]
Merged into master for Spark 4.0. Thanks @wayneguow and @yaooqinn

**Comment by wayneguow** [comment]
Thank you all @LuciferYang @yaooqinn .

**Pull request closed without merging**
