### PR TITLE
[SPARK-30917][SQL]: The behaviour of UnaryMinus should not depend on SQLConf.get

### PR DESCRIPTION
**Pull request by iRakson**
### What changes were proposed in this pull request?
Added new parameter `checkOverflow` to remove dependency on `SQLConf.get`.

### Why are the changes needed?
This allows to avoid the issue when the configuration change between different phases of planning, and this can silently break a query plan which can lead to crashes or data corruption.

### Does this PR introduce any user-facing change?
No

### How was this patch tested?
Existing UTs.

### CODE REVIEW

**Comment by iRakson** [comment]
cc @cloud-fan @HyukjinKwon

**Comment by cloud-fan** [comment]
This doesn't change data type/nullability, so we need to discuss whether or not we should fix the behavior after the expression is created. cc @viirya @maropu

**Comment by cloud-fan** [comment]
OK to test

**Comment by cloud-fan** [comment]
Actually, the behavior is already fixed after the expression is created, as the flag is declared as `private val checkOverflow = SQLConf.get.ansiEnabled`.

So this PR just makes it more stable, to avoid some corner cases like transform the expression tree with a different SQL config.

**Comment by yaooqinn** [comment]
> So this PR just makes it more stable, to avoid some corner cases like transform the expression tree with a different SQL config.


Does it need to keep the config here? https://github.com/apache/spark/pull/27683/files#diff-383a8cdd0a9c58cae68e0a79295520a3R435

**Comment by HyukjinKwon** [comment]
I don't think we have reached any conclusion about other instances, and we haven't made any guarantee about the effective time of configurations. I am -1 to fix other instances without having clear definitions.

**Pull request closed without merging**
