### PR TITLE
[SPARK-15616] [SQL] Metastore relation should fallback to HDFS size of partitions that are involved in Query for JoinSelection.

### PR DESCRIPTION
**Pull request by lianhuiwang**
## What changes were proposed in this pull request?

Currently if some partitions of a partitioned table are used in join operation we rely on Metastore returned size of table to calculate if we can convert the operation to Broadcast join. 
if Filter can prune some partitions, Hive can prune partition before determining to use broadcast joins according to HDFS size of partitions that are involved in Query.So sparkSQL needs it that can improve join's performance for partitioned table.
## How was this patch tested?

integration tests

### CODE REVIEW

**Comment by lianhuiwang** [comment]
cc @cloud-fan @rxin @hvanhovell

**Comment by HyukjinKwon** [comment]
@lianhuiwang, I understand it is painful to keep the PR up-to-date. However, shouldn't we probably have the Jenkins build passed at the last even if it has conflicts?

**Comment by cloud-fan** [comment]
Sorry that I think it's not valid anymore after we have `PruneFileSourcePartitions` rule.

**Comment by lianhuiwang** [comment]
@cloud-fan I do not think that PruneFileSourcePartitions rule is for Hive's CatalogRelation. example in this PR with master branch cannot get expected result. So i will update it with the latest code.

**Comment by lianhuiwang** [comment]
@HyukjinKwon @cloud-fan I will close this PR and create new PR #18193 for it. Thanks.

**Pull request closed without merging**
