### PR TITLE
[SPARK-29753][SQL] refine the default catalog config

### PR DESCRIPTION
**Pull request by cloud-fan**
### What changes were proposed in this pull request?

rename the config to address the comment: https://github.com/apache/spark/pull/24594#discussion_r285431212

improve the config description, provide a default value to simplify the code.

### Why are the changes needed?

make the config more understandable.

### Does this PR introduce any user-facing change?

no

### How was this patch tested?

existing tests

### CODE REVIEW

**Comment by cloud-fan** [comment]
@rdblue @dongjoon-hyun @imback82

**Review by imback82 — APPROVED** [review]
LGTM (one minor comment)

**Comment by cloud-fan** [comment]
retest this please

**Comment by rdblue** [comment]
+1

**Comment by cloud-fan** [comment]
retest this please

**Comment by cloud-fan** [comment]
thanks for review, merging to master!

**Pull request closed without merging**
