### PR TITLE
[SPARK-17221] [SQL] Build File-based Test Cases for Using Join and Left-Semi Join

### PR DESCRIPTION
**Pull request by gatorsmile**
### What changes were proposed in this pull request?

This PR is part of the original PR: https://github.com/apache/spark/pull/14625.

Based on file-based SQL end-to-end testing framework in `SQLQueryTestSuite`, this PR is to create test cases for `left-semi` joins and `using` joins. We did not change the data and query, and thus, the queries and results should match the original ones.

In addition, this PR also moved the test cases from `SQLQuerySuite` to `DataFrameJoinSuite`, because these test cases are not using SQL.
### How was this patch tested?

N/A

### CODE REVIEW

**Comment by gatorsmile** [comment]
To reviewers: to make it easier to review, each commit can be reviewed separately. The name of each commit is self descriptive

**Comment by gatorsmile** [comment]
@rxin How about this one? This is porting our existing test cases, instead of HiveCompatbilitySuite

**Comment by cloud-fan** [comment]
LGTM

**Comment by gatorsmile** [comment]
retest this please

**Pull request closed without merging**
