### PR TITLE
[SPARK-19607] Finding QueryExecution that matches provided executionId

### PR DESCRIPTION
**Pull request by ala**
## What changes were proposed in this pull request?

Implementing a mapping between executionId and corresponding QueryExecution in SQLExecution.

## How was this patch tested?

Adds a unit test.

### CODE REVIEW

**Comment by ala** [comment]
@rxin

**Comment by rxin** [comment]
LGTM (pending Jenkins).

**Comment by rxin** [comment]
Merging in master.

**Comment by dongjoon-hyun** [comment]
Hi, @rxin and @ala .
This seems to cause a test failures.
Could you review the hotfix #16943 ?

**Pull request closed without merging**
