### PR TITLE
[SPARK-37534][BUILD] Bump dev.ludovic.netlib to 2.2.1

### PR DESCRIPTION
**Pull request by luhenry**
### What changes were proposed in this pull request?

Bump the version of dev.ludovic.netlib from 2.2.0 to 2.2.1. This fixes a computation bug in sgemm. See [1]. Diff is [2]

[1] https://github.com/luhenry/netlib/issues/7
[2] https://github.com/luhenry/netlib/compare/v2.2.0...v2.2.1

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Thank you for making a PR, @luhenry .
Do you think you can file an Apache Spark JIRA issue for this and use the JIRA ID prefix in your PR title?

**Comment by luhenry** [comment]
@dongjoon-hyun I created the issue at https://issues.apache.org/jira/browse/SPARK-37534 and linked it in the title.

**Comment by dongjoon-hyun** [comment]
Thank you, @luhenry .

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Merged to master.

**Comment by dongjoon-hyun** [comment]
According to the context, I switched your JIRA type from `Improvement` to `Bug` in order to allow backporting. Could you make a backporting PR to `branch-3.2`? We need to pass CI once more on that branch.

**Comment by luhenry** [comment]
@dongjoon-hyun thank you for merging! I submitted https://github.com/apache/spark/pull/34797 for 3.2

**Pull request closed without merging**
