### PR TITLE
[SPARK-17740] Spark tests should mock / interpose HDFS to ensure that streams are closed

### PR DESCRIPTION
**Pull request by ericl**
## What changes were proposed in this pull request?

As a followup to SPARK-17666, ensure filesystem connections are not leaked at least in unit tests. This is done here by intercepting filesystem calls as suggested by @JoshRosen . At the end of each test, we assert no filesystem streams are left open.

This applies to all tests using SharedSQLContext or SharedSparkContext.
## How was this patch tested?

I verified that tests in sql and core are indeed using the filesystem backend, and fixed the detected leaks. I also checked that reverting https://github.com/apache/spark/pull/15245 causes many actual test failures due to connection leaks.

### CODE REVIEW

**Comment by rxin** [comment]
Thanks - this is super useful!

**Comment by rxin** [comment]
cc @srowen want to review this?

**Comment by rxin** [comment]
Merging in master. Thanks!

**Comment by rxin** [comment]
btw @davies this actually already checks driver side, so we are good here.

**Comment by marmbrus** [comment]
This is good thing for us to test.  However, If you throw an exception in your test that opens a file, it seems that it swallows the exception just telling you that you are leaking files.  Is there anyway we could make this less confusing?

**Comment by ericl** [comment]
Hm, we could it move the actual throw to the afterAll(), that would cause a suite abort instead but presumably leave the test errors intact.

**Pull request closed without merging**
