### PR TITLE
[SPARK-24764] [CORE] Add ServiceLoader implementation for SparkHadoopUtil

### PR DESCRIPTION
**Pull request by shrutig**
## What changes were proposed in this pull request?

Currently SparkHadoopUtil creation is static and cannot be changed. This pull request is to move the creation of SparkHadoopUtil to a ServiceLoader, so that external cluster managers can create their own SparkHadoopUtil.

## How was this patch tested?

Unit Tests have been added in this commit.

Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Comment by dbtsai** [comment]
add to whitelist

**Comment by jerryshao** [comment]
Would you please explain the scenarios of such usage? This `SparkHadoopUtil` is highly hadoop/yarn dependent, I'm not sure how other customized cluster manager use it?

**Comment by shrutig** [comment]
`SparkHadoopUtil` is accessed in multiple points in Apache Spark , and is not limited to usage by yarn.  External cluster managers should also be able to change any functions in `SparkHadoopUtil`, currently there is no way to do so. Internally, we have leveraged the external cluster manager and we would like to control the `runAsSparkUser` method for our authentication method. Just as external cluster manager is pluggable, `SparkHadoopUtil` could also be pluggable.

**Comment by vanzin** [comment]
I don't understand the purpose of this change. Can you explain exactly what part of `SparkHadoopUtil` do you need to customize, and why that change can't just be made to the shared code?

The bug you filed even contains incorrect information. There is a single implementation of `SparkHadoopUtil` used by all cluster managers - if you look at "YarnSparkHadoopUtil.scala", there is only an object there, with some YARN-specific methods, but the YARN code re-uses the shared `SparkHadoopUtil`. I actually made that change; and the only reason `SparkHadoopUtil` didn't just become an object is because it's a semi-public API.

Your code also breaks if you have more than one custom implementation in the classpath. If your goal is to allow cluster managers to override it, that's a pretty big hole, since you can't have the built-in cluster managers overriding them since more often than not they're all in the classpath at the same time.

The only reason this class was overridden in YARN in the past is because Spark used to support both hadoop1 and hadoop2, and code in `core/` could not call hadoop2 APIs (but code in the yarn module could). That is not the case anymore.

**Comment by dbtsai** [comment]
From what I talked to @shrutig offline, the use-case her team has is when `UserGroupInformation.getCurrentUser.getAuthenticationMethod == AuthenticationMethod.KERBEROS`,  they want to set the remote ugi with `AuthMethod.KERBEROS` authentication method as the default remote ugi is using `AuthMethod.SIMPLE`.

I'll suggest to add 
```scala
    ugi.setAuthenticationMethod(
      UserGroupInformation.getCurrentUser.getAuthenticationMethod.getAuthMethod)
```
into `def createSparkUser(): UserGroupInformation` instead of customizing `SparkHadoopUtil`.

**Comment by shrutig** [comment]
@dbtsai @vanzin 
What we are trying to achieve is to make Spark work with plain Kerberos authentication.

We `login user from keytab` at the startup of driver and executors and then use this UserGroupInformation. We do not have Hadoop token authentication method, but use plain Kerberos auth.

Spark's runAsSparkUser creates a new UGI based on the current static UGI and then transfers credentials from this current static UGI to the new UGI. This works well with other auth methods, except Kerberos. For Kerberos, the UGI has to be created from loginUserFromKeytab method only and not simply by doing a transfer credentials from the previous UGI to the new UGI.  This is because  isKeytab and isKrbTkt variables in UGI are needed for the UGI to work properly.

The implementation which has been working is below: 

```
val currentUgi = UserGroupInformation.getCurrentUser
    val ugi = if (currentUgi.getAuthenticationMethod == AuthenticationMethod.KERBEROS) {
      currentUgi      // This worked for us for KERBEROS auth method
    } else {
      val user = Utils.getCurrentUserName()
      val newUgi = UserGroupInformation.createRemoteUser(user)
      transferCredentials(UserGroupInformation.getCurrentUser, newUgi)
      newUgi
    }
    logDebug("running as user: " + ugi.getUserName)
    ugi.doAs(new PrivilegedExceptionAction[Unit] {
      def run: Unit = func()
    })
  }
```

**Comment by dbtsai** [comment]
add @jerryshao for more feedback. Thanks.

**Comment by jerryshao** [comment]
I think the use case here is quite specific, I'm not sure if it is a good idea to make `SparkHadoopUtil` ServiceLoader-able to support your requirement. Typically I don't think user has a such requirement to build their own `SparkHadoopUtil`.

I'm wondering do we have other solutions or workarounds to support your use case?

**Comment by vanzin** [comment]
I really dislike exposing this a something that others can override. We should be going the other way, and making that code as generic as possible.

If there's something that you can fix in the existing code to enable your use case, that would be better. Otherwise, I suggest just patching the needed code in your deployment; sounds from your e-mails like you're already modifying Spark, so...

**Comment by shrutig** [comment]
Thank you for your feedback. I have created a separate JIRA https://issues.apache.org/jira/browse/SPARK-25428 to track Spark support for plain Kerberos authentication. Hence, this PR can be closed.

**Comment by vanzin** [comment]
Only you can close your own PR.

**Pull request closed without merging**
