### PR TITLE
[INFRA] Close stale PRs

### PR DESCRIPTION
**Pull request by HyukjinKwon**
## What changes were proposed in this pull request?

This PR proposes to close PRs ...

  - inactive to the review comments more than a month
  - WIP and inactive more than a month
  - with Jenkins build failure but inactive more than a month
  - suggested to be closed and no comment against that
  - obviously looking inappropriate (e.g., Branch 0.5)

To make sure, I left a comment for each PR about a week ago and I could not have a response back from the author in these PRs below:

Closes #11129
Closes #12085
Closes #12162
Closes #12419
Closes #12420
Closes #12491
Closes #13762
Closes #13837
Closes #13851
Closes #13881
Closes #13891
Closes #13959
Closes #14091
Closes #14481
Closes #14547
Closes #14557
Closes #14686
Closes #15594
Closes #15652
Closes #15850
Closes #15914
Closes #15918
Closes #16285
Closes #16389
Closes #16652
Closes #16743
Closes #16893
Closes #16975
Closes #17001
Closes #17088
Closes #17119
Closes #17272
Closes #17971

Added:
Closes #17778
Closes #17303
Closes #17872

## How was this patch tested?

N/A

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @srowen and @vanzin

**Comment by HyukjinKwon** [comment]
cc @srowen and @vanzin could you take a look please? I think I saw both of you in those PRs frequently.

**Comment by HyukjinKwon** [comment]
Please let me know if any PR in the list is still active and in progress. I will take it out.

**Comment by srowen** [comment]
You can add 

https://github.com/apache/spark/pull/17778
https://github.com/apache/spark/pull/17303
https://github.com/apache/spark/pull/17435
https://github.com/apache/spark/pull/17971
https://github.com/apache/spark/pull/17872

**Comment by vanzin** [comment]
Looks ok; most seem to be ml or sql which I don't monitor very closely.

**Comment by HyukjinKwon** [comment]
(Actually, let me take out #17435. It looks recently updated and I believe it has a point there).

**Comment by HyukjinKwon** [comment]
(#16654 was took out as it was closed).

**Pull request closed without merging**
