### PR TITLE
[SPARK-15596][SPARK-15635][SQL] ALTER TABLE RENAME fixes

### PR DESCRIPTION
**Pull request by andrewor14**
## What changes were proposed in this pull request?

**SPARK-15596**: Even after we renamed a cached table, the plan would remain in the cache with the old table name. If I created a new table using the old name then the old table would return incorrect data. Note that this applies only to Hive tables.

**SPARK-15635**: Renaming a datasource table would render the table not query-able. This is because we store the location of the table in a "path" property, which was not updated to reflect Hive's change in table location following a rename.
## How was this patch tested?

DDLSuite

### CODE REVIEW

**Comment by andrewor14** [comment]
retest this please

**Comment by andrewor14** [comment]
@yhuai

**Comment by yhuai** [comment]
lgtm

**Comment by yhuai** [comment]
merging to master and branch 2.0

**Pull request closed without merging**
