### PR TITLE
WIP [SPARK-12172][SPARKR] Remove internal-only RDD methods

### PR DESCRIPTION
**Pull request by felixcheung**
## What changes were proposed in this pull request?

Remove non-public internal only methods for RDD in SparkR

## How was this patch tested?

Jenkins

### CODE REVIEW

**Review by srowen — APPROVED** [review]
I trust your judgment on this one.

**Comment by srowen** [comment]
@felixcheung where did you end up on this one?

**Comment by felixcheung** [comment]
sorry, didn't get a chance to follow up. Since this is a big change, I might need to revert part of it to see what is leading to some implicit type conversion type of problem, IIRC. I will try to get back in a week.

**Comment by dongjoon-hyun** [comment]
Hi, @felixcheung . Do you think we can have this at 3.0.0~?

**Pull request closed without merging**
