### PR TITLE
[SPARK-35911][SQL] Update exprId for IN subquery in DPP

### PR DESCRIPTION
**Pull request by Swinky**
### What changes were proposed in this pull request?
Update exprId for IN subquery for DPP in executed plan; to have same expr Id as DynamicPruning filter in optimized plan.

### Why are the changes needed?
This minor change shall make debugging easier in complex queries.

### Does this PR introduce _any_ user-facing change?
Yes, just exprId changes in the optimized and executed plans. Now both shall have same exprId for an DPP expression/subquery.

### How was this patch tested?
Added a check in existing UTs.

### CODE REVIEW

**Comment by Swinky** [comment]
@maryannxue, could you please have a look at this, thanks!

**Comment by HyukjinKwon** [comment]
@Swinky can you take a look https://github.com/apache/spark/pull/33110/checks?check_run_id=2926460223 and enable Github Actions in your fork repository?

**Comment by Swinky** [comment]
> @Swinky can you take a look https://github.com/apache/spark/pull/33110/checks?check_run_id=2926460223 and enable Github Actions in your fork repository?

@HyukjinKwon,
I made sure that my branch is based on latest master and GitHub Actions are already enabled. Not sure why this is still failing.
image

image

**Comment by HyukjinKwon** [comment]
@Swinky did you face something like https://github.com/apache/spark/pull/32400#issuecomment-831051189? otherwise rebasing would retrigger the build properly

**Pull request closed without merging**
