### PR TITLE
Revert "[SPARK-37733][BUILD] Change log level of tests to WARN"

### PR DESCRIPTION
**Pull request by viirya**
### What changes were proposed in this pull request?

This reverts commit c0cedb136cf807aebe0319ca86175cf8eed8b8b0.

### Why are the changes needed?

#35011 changes log level and causes some tests that check log message failed.

Actually #34965 was merged not long ago which fixes logging issue for hive-thriftserver module that produces large log output.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Pass tests.

### CODE REVIEW

**Comment by viirya** [comment]
cc @gengliangwang @HyukjinKwon

**Comment by HyukjinKwon** [comment]
Oops sorry my bad

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
let me merge this since this is a clean revert

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by HyukjinKwon** [comment]
sorry guys. I had to wait for the test results.

**Comment by gengliangwang** [comment]
Late LGTM. Thank you @viirya

**Comment by viirya** [comment]
thank you @HyukjinKwon @gengliangwang

**Pull request closed without merging**
