### PR TITLE
[SPARK-18655][SS]Ignore Structured Streaming 2.0.2 logs in history server

### PR DESCRIPTION
**Pull request by zsxwing**
## What changes were proposed in this pull request?

As `queryStatus` in StreamingQueryListener events was removed in #15954, parsing 2.0.2 structured streaming logs will throw the following errror:

```
[info]   com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "queryStatus" (class org.apache.spark.sql.streaming.StreamingQueryListener$QueryTerminatedEvent), not marked as ignorable (2 known properties: "id", "exception"])
[info]  at [Source: {"Event":"org.apache.spark.sql.streaming.StreamingQueryListener$QueryTerminatedEvent","queryStatus":{"name":"query-1","id":1,"timestamp":1480491532753,"inputRate":0.0,"processingRate":0.0,"latency":null,"sourceStatuses":[{"description":"FileStreamSource[file:/Users/zsx/stream]","offsetDesc":"#0","inputRate":0.0,"processingRate":0.0,"triggerDetails":{"latency.getOffset.source":"1","triggerId":"1"}}],"sinkStatus":{"description":"FileSink[/Users/zsx/stream2]","offsetDesc":"[#0]"},"triggerDetails":{}},"exception":null}; line: 1, column: 521] (through reference chain: org.apache.spark.sql.streaming.QueryTerminatedEvent["queryStatus"])
[info]   at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:51)
[info]   at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:839)
[info]   at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1045)
[info]   at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1352)
[info]   at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperties(BeanDeserializerBase.java:1306)
[info]   at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:453)
[info]   at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1099)
...
```

This PR just ignores such errors and adds a test to make sure we can read 2.0.2 logs.

## How was this patch tested?

`query-event-logs-version-2.0.2.txt` has all types of events generated by Structured Streaming in Spark 2.0.2. `testQuietly("ReplayListenerBus should ignore broken event jsons generated in 2.0.2")` verified we can load them without any error.

### CODE REVIEW

**Comment by zsxwing** [comment]
Another option is adding `@JsonIgnoreProperties` to these classes to ignore unknown fields. However, there are two disadvantages:

- It's easy to ignore something that we don't want to ignore in future by mistake.
- Since the old logs don't contain the new added fields, they will be set to `null`. It forces `StreamingQueryListener` to handle null values.

Hence, I don't choose this way.

**Comment by zsxwing** [comment]
cc @tdas

**Comment by tdas** [comment]
LGTM

**Comment by zsxwing** [comment]
retest this please

**Comment by zsxwing** [comment]
> Test build #69423 has started for PR 16085 at commit 33c253f.

This is hanging here but is not related to this change:
```
[info] ExternalAppendOnlyMapSuite:
[info] - single insert insert (144 milliseconds)
[info] - multiple insert (1 second, 342 milliseconds)
[info] - insert with collision (50 milliseconds)
[info] - ordering (99 milliseconds)
[info] - null keys and values (89 milliseconds)
[info] - simple aggregator (1 second, 123 milliseconds)
[info] - simple cogroup (564 milliseconds)
[info] - spilling (16 seconds, 277 milliseconds)
```

**Comment by zsxwing** [comment]
Thanks! Merging to master and 2.1.

**Pull request closed without merging**
