### PR TITLE
[SPARK-23596][SQL] Test interpreted path on encoders test suites

### PR DESCRIPTION
**Pull request by viirya**
## What changes were proposed in this pull request?

We have completed a significant subset of the object related Expressions to provide an interpreted fallback. This PR is going to modify the tests to also test the interpreted code paths.

One concern right now is that by testing the interpreted code paths too, we will double current test time or more. Otherwise, we can only choose to test the interpreted code paths for just few test suites such as encoder related.

## How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by viirya** [comment]
cc @cloud-fan @hvanhovell @kiszk @mgaido91 @maropu

**Comment by viirya** [comment]
retest this please.

**Comment by viirya** [comment]
retest this please.

**Comment by viirya** [comment]
retest this please...

**Comment by hvanhovell** [comment]
@viirya how much time this add to the overall testing time?

If this is too much then we should perhaps just test interpreted encoders. WDYT?

**Comment by viirya** [comment]
@hvanhovell I observed the testing time, roughly for a same test, additional interpreted path will add 50~120% time.

Interpreted encoders? Do you mean to only test interpreted path for `org.apache.spark.sql.catalyst.encoders.*`?

**Comment by viirya** [comment]
@hvanhovell Added tests for interpreted encoders.

**Comment by viirya** [comment]
@hvanhovell Do you think we should test interpreted paths against DatasetSuite and DataFrameSuite?

**Comment by viirya** [comment]
ping @hvanhovell and cc @cloud-fan too.

**Comment by viirya** [comment]
ping @hvanhovell @cloud-fan

**Comment by viirya** [comment]
retest this please.

**Comment by viirya** [comment]
retest this please.

**Comment by kiszk** [comment]
I am not sure whether the increased time is acceptable or not.

If it is not accepted, how about adding an option to control do test in interpreter mode. Then, we test only compiled code path in sbt, and test both paths in mvn?

**Comment by viirya** [comment]
If we only test interpreted path on selected test suites, e.g., `org.apache.spark.sql.catalyst.encoders.*`, I think we won't increase too much test time. I feel that we should not make it different in mvn and sbt building path.

**Comment by viirya** [comment]
ping @hvanhovell @cloud-fan

**Comment by viirya** [comment]
retest this please.

**Comment by HyukjinKwon** [comment]
ok to test

**Review by HyukjinKwon — APPROVED** [review]
LGTM but let me leave it to @hvanhovell.

**Comment by kiszk** [comment]
LGTM

**Comment by mgaido91** [comment]
LGTM too

**Comment by mgaido91** [comment]
retest this please

**Review by HyukjinKwon — APPROVED** [review]
LGTM

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by viirya** [comment]
Thanks @HyukjinKwon @hvanhovell @mgaido91 @kiszk

**Pull request closed without merging**
