### PR TITLE
[SPARK-13974][SQL] sub-query names do not need to be globally unique while generate SQL

### PR DESCRIPTION
**Pull request by cloud-fan**
## What changes were proposed in this pull request?

We only need to make sub-query names unique every time we generate a SQL string, but not all the time. This PR moves the `newSubqueryName` method to `class SQLBuilder` and remove `object SQLBuilder`.

also addressed 2 minor comments in https://github.com/apache/spark/pull/11696
## How was this patch tested?

existing tests.

### CODE REVIEW

**Comment by cloud-fan** [comment]
cc @liancheng @yhuai

**Comment by liancheng** [comment]
LGTM

**Comment by yhuai** [comment]
test this please

**Comment by yhuai** [comment]
test this please

**Comment by cloud-fan** [comment]
merging to master!

**Pull request closed without merging**
