### PR TITLE
[SPARK-8406] [SQL] Backports SPARK-8406 and PR #6864 to branch-1.4

### PR DESCRIPTION
**Pull request by liancheng**

### CODE REVIEW

**Comment by liancheng** [comment]
cc @yhuai

**Comment by nemccarthy** [comment]
Can chance this can be merged today?

**Comment by yhuai** [comment]
LGTM. I am merging it to branch-1.4.

**Comment by yhuai** [comment]
ok. I have merged this. Can you close this PR?

**Pull request closed without merging**
