### PR TITLE
[SPARK-48387][SQL] Postgres: Map TimestampType to TIMESTAMP WITH TIME ZONE

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

Currently, Both TimestampType/TimestampNTZType are mapped to TIMESTAMP WITHOUT TIME ZONE for writing while being differentiated for reading.

In this PR, we map TimestampType to TIMESTAMP WITH TIME ZONE to differentiate TimestampType/TimestampNTZType for writing against Postgres.

### Why are the changes needed?

TimestampType <-> TIMESTAMP WITHOUT TIME ZONE is incorrect and ambiguous with TimestampNTZType

### Does this PR introduce _any_ user-facing change?

Yes
migration guide and legacy configuration provided

### How was this patch tested?

new tests

### Was this patch authored or co-authored using generative AI tooling?
no

### CODE REVIEW

**Comment by yaooqinn** [comment]
cc @cloud-fan @dongjoon-hyun @LuciferYang thanks

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by dongjoon-hyun** [comment]
Thank you, @yaooqinn

**Comment by yaooqinn** [comment]
Merged to master. Thank you very much @dongjoon-hyun

**Pull request closed without merging**
