### PR TITLE
[SPARK-43965][PYTHON][CONNECT][FOLLOWUP] Include test_parity_udtf in spark test module

### PR DESCRIPTION
**Pull request by allisonwang-db**
### What changes were proposed in this pull request?

This is a follow up PR for SPARK-43965 to include `test_parity_udtf` in spark test module. It also fixes a test failure.

### Why are the changes needed?

To include a new test case.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Existing tests

### CODE REVIEW

**Comment by allisonwang-db** [comment]
cc @ueshin

**Comment by ueshin** [comment]
I see some errors in `test_parity_udtf` on my local:

```
======================================================================
FAIL [0.032s]: test_udtf_with_empty_yield (pyspark.sql.tests.connect.test_parity_udtf.ArrowUDTFParityTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/.../python/pyspark/sql/tests/connect/test_parity_udtf.py", line 114, in test_udtf_with_empty_yield
    TestUDTF(lit(1)).collect()
AssertionError: SparkConnectGrpcException not raised

======================================================================
FAIL [0.026s]: test_udtf_with_empty_yield (pyspark.sql.tests.connect.test_parity_udtf.UDTFParityTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/.../python/pyspark/sql/tests/connect/test_parity_udtf.py", line 114, in test_udtf_with_empty_yield
    TestUDTF(lit(1)).collect()
AssertionError: SparkConnectGrpcException not raised

----------------------------------------------------------------------
```

**Review by ueshin — APPROVED** [review]
LGTM, pending tests.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by zhengruifeng** [comment]
merged to master and branch-3.5

**Pull request closed without merging**
