### PR TITLE
[SPARK-9175] [MLlib] BLAS.gemm fails to update matrix C when alpha==0 and beta!=1

### PR DESCRIPTION
**Pull request by rotationsymmetry**
Fix BLAS.gemm to update matrix C when alpha==0 and beta!=1
Also include unit tests to verify the fix.

@mengxr @brkyvz

### CODE REVIEW

**Comment by srowen** [comment]
LGTM

**Comment by srowen** [comment]
ok to test

**Comment by srowen** [comment]
@brkyvz is this OK with you?

**Comment by brkyvz** [comment]
Can we add the same check to gemv please? In addition, instead of calling the dgemm routine to just scale C, maybe we can just call f2jBlas.scal? @mengxr What do you think?

**Comment by rotationsymmetry** [comment]
@brkyvz 

1) I will put in the same check to gemv if everybody agrees.
2) scal for (dense or sparse) matrices will be helpful. I could implement it as well. Will this be considered as new API?

cc @srowen @mengxr

**Comment by mengxr** [comment]
ok to test

**Comment by mengxr** [comment]
I like @brkyvz 's idea about calling `scal` when `alpha == 0`. It would be a noop when `beta == 0`, but handled by `scal`. Since this is a bug, I would like to merge this first and have follow-up JIRAs to implement `scal`.

**Comment by mengxr** [comment]
Merged into master and all branches since 1.2. Thanks!

**Comment by rotationsymmetry** [comment]
Hi @mengxr, thank you for merge. I have also fixed a similar bug in BLAS.gemv, as suggested by @brkyvz . Shall I make another pull request?

**Pull request closed without merging**
