### PR TITLE
[SPARK-39053][PYTHON][PS][TEST] Skip multiindex dtypes test for pandas 1.4.1/1.4.2 and add a not_unique_name test

### PR DESCRIPTION
**Pull request by Yikun**
### What changes were proposed in this pull request?
- Fix `test_multi_index_dtypes` test for pandas 1.4.1/1.4.2
- Add `test_multi_index_dtypes_not_unique_name`  test (a plus and validation on https://github.com/pandas-dev/pandas/commit/d06fb912782834125f1c9b0baaea1d60f2151c69) to make sure this issue also work in PS.

### Why are the changes needed?
Pandas introduce the commits https://github.com/pandas-dev/pandas/commit/d06fb912782834125f1c9b0baaea1d60f2151c69 since 1.4.0, it changes the dtypes behavior of `list[tuple]` as index. This change make our test failed accidently.

Pandas community confirm it's a regression and will be fixed in 1.4.3.

### Does this PR introduce _any_ user-facing change?
Yep, follow pandas behavior

### How was this patch tested?
- UT passed (panda < 1.4).
- `test_multi_index_dtypes_not_unique_name`, `test_multi_index_dtypes` passed with 1.4.x +

### CODE REVIEW

**Comment by Yikun** [comment]
cc @itholic @xinrong-databricks @HyukjinKwon 

also cc @dchvn FYI.

**Comment by xinrong-databricks** [comment]
Would you elaborate on the user-facing change?

A simple example as below helps:
```py
# before
>>> pd.MultiIndex.from_arrays([[1], [2]], names=[1, 1]).dtypes
1    int64
dtype: object

# now
>>> pd.MultiIndex.from_arrays([[1], [2]], names=[1, 1]).dtypes
1    int64
1    int64
dtype: object
```

**Comment by Yikun** [comment]
```
# multiple labels
pmidx = pd.MultiIndex.from_arrays(arrays, names=[("zero", "first"), ("one", "second")])
psmidx = ps.from_pandas(pmidx)
psmidx.dtypes.index

Out[6]: 
MultiIndex([('zero',  'first'),
            ( 'one', 'second')],
           )
pmidx.dtypes.index

Out[7]: Index([('zero', 'first'), ('one', 'second')], dtype='object')
pd.__version__

Out[8]: '1.4.2'
```
cc @xinrong-databricks  index.dtype index mismatch.

But I just rethink it might be an unexpected change on Pandas. I rasie the issue here: https://github.com/pandas-dev/pandas/issues/46900

**Comment by Yikun** [comment]
BTW, as I mentioned in PR description `ps.MultiIndex.from_arrays([[1], [2]], names=[1, 1]).dtypes` is not a regression test for this PR, just a plus test (changes on `test_multi_index_dtypes` is regression).

Let me split them as two patches to make clear, sorry for the misleading.

**Comment by Yikun** [comment]
Let us hold on this if you could get some feedback from https://github.com/pandas-dev/pandas/issues/46900

**Comment by xinrong-databricks** [comment]
Sounds good, thanks for the follow-up.

**Comment by Yikun** [comment]
@xinrong-databricks Finally, pandas community confirm it's an unexpected changes, so I convert this PR to a TESTS PR (skip failed tests for pandas 1.4.1/1.4.2 and add a regression test). It would be if you could good take a another look.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by xinrong-databricks** [comment]
Thanks Yikun, LGTM!

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
