### PR TITLE
[SPARK-21809] : Change Stage Page to use datatables to support sorting columns and searching

### PR DESCRIPTION
**Pull request by pgandhi999**
Support column sort and search for Stage Server using jQuery DataTable and REST API. Before this commit, the Stage page was generated hard-coded HTML and can not support search, also, the sorting was disabled if there is any application that has more than one attempt. Supporting search and sort (over all applications rather than the 20 entries in the current page) in any case will greatly improve the user experience.
Created the stagespage-template.html for displaying application information in datables. Added REST api endpoint and javascript code to fetch data from the endpoint and display it on the data table.
Because of the above change, certain functionalities in the page had to be modified to support the addition of datatables. For example, the toggle checkbox 'Select All' previously would add the checked fields as columns in the Task table and as rows in the Summary Metrics table, but after the change, only columns are added in the Task Table as it got tricky to add rows dynamically in the datatables.

## How was this patch tested?
I have attached the screenshots of the Stage Page UI before and after the fix.
Before:
screen shot-before

After:
screen shot- after

### CODE REVIEW

**Comment by tgravescs** [comment]
ok to test

**Comment by pgandhi999** [comment]
The error logs for test build #81683 state that method this(Long,Int,Int,Long,Long,Long,Long,Long,Long)Unit in class org.apache.spark.status.api.v1.ExecutorStageSummary does not have a correspondent in current version. All I have done is add new fields in the api ExecutorStageSummary and have not modified any existing ones. It should be fine but please let me know if it is not.

**Comment by ajbozarth** [comment]
Just a heads up I am planning on looking at this and just haven't had time yet.

**Comment by ajbozarth** [comment]
It looks like you have a bunch of unrelated code in this PR, this seems to be caused by how you're doing development. You've opened this PR from your master branch and it includes work on 3 other tasks, one of which is already merged. According to https://spark.apache.org/contributing.html you should create a new branch for each task and open a PR from that branch. Based on that could you close this and create a new pr once you've created a clean branch with only the applicable changes. Thanks, and tag me once you open the new PR and I'll review your code :)

**Pull request closed without merging**
