### PR TITLE
[SPARK-50024][PYTHON][CONNECT] Switch to use logger instead of warnings module in client

### PR DESCRIPTION
**Pull request by nija-at**
### What changes were proposed in this pull request?

ReleaseExecute, in some cases, can fail since the operation may
already have been released or dropped by the server. The API call
is best effort.

By logging the error using the Python warnings module, we produce
a user facing warning and can be confusing.
The original intention is to add it to the log output for debugging when
necessary. Switch to use a standard logger instead.

The warnings module should generally be used to warn users of their
choices - deprecated API, unapplied option, etc.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Ran pyspark locally and checked that the log statements are printed.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
@itholic should we use PySparkLogger instead?

**Comment by nija-at** [comment]
> should we use PySparkLogger instead?

@HyukjinKwon The logging class is using PySparkLogger under the hood.

**Comment by itholic** [comment]
Yes it is already using the `PySparkLogger` so it should be fine:

https://github.com/apache/spark/blob/b0414b19a0ea5ffa10067154c00009259419f045/python/pyspark/sql/connect/client/logging.py#L31

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
