### PR TITLE
 [SPARK-27737][SQL] Upgrade to Hive 2.3.5 for Hive Metastore Client and Hadoop-3.2 profile

### PR DESCRIPTION
**Pull request by wangyum**
## What changes were proposed in this pull request?

This PR aims to upgrade to Hive 2.3.5 for Hive Metastore Client and Hadoop-3.2 profile.

Release Notes - Hive - Version 2.3.5

- [[HIVE-21536](https://issues.apache.org/jira/browse/HIVE-21536)] - Backport HIVE-17764 to branch-2.3
- [[HIVE-21585](https://issues.apache.org/jira/browse/HIVE-21585)] - Upgrade branch-2.3 to ORC 1.3.4
- [[HIVE-21639](https://issues.apache.org/jira/browse/HIVE-21639)] - Spark test failed since HIVE-10632
- [[HIVE-21680](https://issues.apache.org/jira/browse/HIVE-21680)] - Backport HIVE-17644 to branch-2 and branch-2.3

https://issues.apache.org/jira/secure/ReleaseNote.jspa?version=12345394&styleName=Text&projectId=12310843

## How was this patch tested?

This PR is tested in two ways.
- Pass the Jenkins with the default configuration for `Hive Metastore Client` testing.
- Pass the Jenkins with `test-hadoop3.2` configuration for `Hadoop 3.2` testing.

### CODE REVIEW

**Review by felixcheung — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
retest this please

**Review by HyukjinKwon — APPROVED** [review]
yes, looks good if the tests pass.

**Comment by wangyum** [comment]
The Hive 2.3.5 jars is not in the [maven repository](https://repo.maven.apache.org/maven2/org/apache/hive/hive-exec/). May be need to wait for a while?

**Comment by HyukjinKwon** [comment]
okie.

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
@wangyum . Please merge this and #24621 because we had better update the dependency file consistently across all profiles from Hive 2.3.5.

cc @gatorsmile and @srowen .

**Comment by dongjoon-hyun** [comment]
BTW, @wangyum . To get reviews, you had better make a PR after the maven repository is ready next time. :)

**Comment by HyukjinKwon** [comment]
Yea agree.

**Comment by wangyum** [comment]
retest this please

**Review by srowen — APPROVED** [review]

**Comment by wangyum** [comment]
retest this please

**Review by HyukjinKwon — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you for updating, @wangyum . After https://github.com/apache/spark/pull/24639 is merged, I'll retrigger this with `[test-hadoop3.2][test-maven]`.

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by dongjoon-hyun** [comment]
I updated the PR title and description. The last Jenkins is running with the following.
```
[info] Building Spark using Maven with these arguments: 
-Phadoop-3.2 -Pkubernetes -Pkinesis-asl -Pyarn -Pspark-ganglia-lgpl
-Phive -Pmesos clean package -DskipTests
```

**Comment by wangyum** [comment]
Hive 2.3.5 should support test with `sbt`.

**Comment by wangyum** [comment]
retest this please

**Comment by dongjoon-hyun** [comment]
Thank you for additional one, @wangyum . To sum up,

- `sbt` on `hadoop-2.7` was tested via https://github.com/apache/spark/pull/24620#issuecomment-493906441 
```
- [info] Building Spark using SBT with these arguments:  -Phadoop-2.7 -Pkubernetes -Phive-thriftserver -Pkinesis-asl -Pyarn -Pspark-ganglia-lgpl -Phive -Pmesos test:package streaming-kinesis-asl-assembly/assembly
```

- `sbt` on `hadoop-3.2` is running on [Test build #105579 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/105579/testReport)

- `maven` on `hadoop-3.2` is running on [Test build #105578 has started](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/105578/testReport)


@wangyum . Do you want to trigger `maven` on `hadoop-2.7`, too?

**Comment by wangyum** [comment]
maven on hadoop-3.2 failed:
```
VersionsSuite:
15:41:45.385 WARN org.apache.spark.sql.hive.client.IsolatedClientLoader: Failed to resolve Hadoop artifacts for the version 3.2.0. We will change the hadoop version from 3.2.0 to 2.7.4 and try again. Hadoop classes will not be shared between Spark and Hive metastore client. It is recommended to set jars used by Hive metastore client through spark.sql.hive.metastore.jars in the production environment.
- success sanity check *** FAILED ***
  java.lang.RuntimeException: [unresolved dependency: com.sun.jersey#jersey-core;1.14: configuration not found in com.sun.jersey#jersey-core;1.14: 'master(compile)'. Missing configuration: 'compile'. It was required from org.apache.hadoop#hadoop-yarn-common;2.7.4 compile]
  at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1331)
  at org.apache.spark.sql.hive.client.IsolatedClientLoader$.$anonfun$downloadVersion$2(IsolatedClientLoader.scala:122)
  at org.apache.spark.sql.catalyst.util.package$.quietly(package.scala:41)
  at org.apache.spark.sql.hive.client.IsolatedClientLoader$.downloadVersion(IsolatedClientLoader.scala:122)
  at org.apache.spark.sql.hive.client.IsolatedClientLoader$.liftedTree1$1(IsolatedClientLoader.scala:77)
  at org.apache.spark.sql.hive.client.IsolatedClientLoader$.forVersion(IsolatedClientLoader.scala:64)
  at org.apache.spark.sql.hive.client.HiveClientBuilder$.buildClient(HiveClientBuilder.scala:58)
  at org.apache.spark.sql.hive.client.VersionsSuite.$anonfun$new$1(VersionsSuite.scala:70)
  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
  at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
```

**Comment by wangyum** [comment]
retest this please

**Comment by wangyum** [comment]
@dongjoon-hyun Do you think we need test maven on hadoop-2.7?

**Comment by dongjoon-hyun** [comment]
Yep. So, if you want, you can trigger it to verify this PR completely.
> Do you think we need test maven on hadoop-2.7?

**Comment by wangyum** [comment]
retest this please

**Comment by dongjoon-hyun** [comment]
Ur, @wangyum . During merging, it seems that we missed to upgrade `hadoop-3.2` profile properly.
```xml
      <id>hadoop-3.2</id>
        ...
        <hive.version.short>2.3.4</hive.version.short>
```
Please update `hadoop-3.2` profile and update the manifests.

**Comment by wangyum** [comment]
How about change `hive.version.short` to 2.3.0?

**Comment by dongjoon-hyun** [comment]
Is there a reason to use that?
> How about change hive.version.short to 2.3.0?

**Comment by wangyum** [comment]
2 reasons:
1. Avoid change these directories: [`sql/core/v2.3.4/src`](https://github.com/apache/spark/tree/master/sql/core/v2.3.4/src), `sql/hive-thriftserver/v2.3.4` and `hive.version.short` if we upgrade Hive 2.3 to 2.3.6, 2.3.7 ...
2. `2.3.0` seems more natural: 
image

**Comment by dongjoon-hyun** [comment]
Does something fail with `2.3.5`? Before Spark 3.0.0 release, Hive 2.3.5 seems to be the last and the most stable Hive release. So, shall we catch up at this time? It would be great if you do the following.
- `dev/test-dependencies.sh --replace-manifest`
- `sql/core/v2.3.4/src` -> `sql/core/v2.3.5/src`

For shortVersion, we use `1.2.1` previously. So, `2.3.5` looks fine to me.

**Comment by wangyum** [comment]
@HyukjinKwon It add `-Phive-thriftserver` after merge upstream:
```
========================================================================
Building Spark
========================================================================
[info] Building Spark using SBT with these arguments:  -Phadoop-3.2 -Pkubernetes -Phive-thriftserver -Pkinesis-asl -Pyarn -Pspark-ganglia-lgpl -Phive -Pmesos test:package streaming-kinesis-asl-assembly/assembly
```

**Comment by HyukjinKwon** [comment]
```
========================================================================
Building Spark
========================================================================
[info] Building Spark using SBT with these arguments:  -Phadoop-3.2 -Pkubernetes -Pkinesis-asl -Pyarn -Pspark-ganglia-lgpl -Phive -Pmesos test:package streaming-kinesis-asl-assembly/assembly
```

Seems not. which build are you referring?

**Comment by HyukjinKwon** [comment]
This build https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/105605/ was against 0f2eb07 before merging upstream.

**Comment by wangyum** [comment]
Retest this please

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by wangyum** [comment]
retest this please

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
