### PR TITLE
[SPARK-42363][CONNECT] Remove SparkSession.register_udf

### PR DESCRIPTION
**Pull request by HyukjinKwon**
### What changes were proposed in this pull request?

This PR proposes to remove `SparkSession.register_udf` and `pyspark.sql.connect.function_builder`.

### Why are the changes needed?

- For API parity w/ regular PySpark.
- They have to be implemented via `SparkSession.udf` (SPARK-41843).
- For non-registered Python and Pandas UDFs, they are implemented at SPARK-42124 and SPARK-42125.
- We implemented all functions so we do not need `pyspark.sql.connect.function_builder` workaround anymore.

### Does this PR introduce _any_ user-facing change?

No to end users.

Yee to the dev because it removes an API `SparkSession.register_udf` and `pyspark.sql.connect.function_builder`.

### How was this patch tested?

CI in this PR should verify them

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @xinrong-meng @grundprinzip @zhengruifeng

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by dongjoon-hyun** [comment]
Merged to master/3.4.

**Comment by HyukjinKwon** [comment]
Thank you !

**Comment by zhengruifeng** [comment]
late LGTM, thanks

**Pull request closed without merging**
