### PR TITLE
[SPARK-14906][ML] Copy linalg in PySpark to new ML package

### PR DESCRIPTION
**Pull request by viirya**
## What changes were proposed in this pull request?

Copy the linalg (Vector/Matrix and VectorUDT/MatrixUDT) in PySpark to new ML package.
## How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by viirya** [comment]
I will fix the style when I come back to laptop.

**Comment by viirya** [comment]
retest this please.

**Comment by viirya** [comment]
ping @mengxr

**Comment by mengxr** [comment]
I'm making a pass now.

**Comment by mengxr** [comment]
@viirya I made one pass and sent you a PR at https://github.com/viirya/spark-1/pull/5. Please take a look and merge it if it looks good to you. Thanks!

**Comment by viirya** [comment]
retest this please.

**Comment by mengxr** [comment]
LGTM. Merged into master and branch-2.0. Thanks!

**Pull request closed without merging**
