### PR TITLE
[SPARK-50410][CONNECT] Refactor the `sql` function in `SparkSession` to eliminate duplicate code

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?

There is duplicate code between

https://github.com/apache/spark/blob/7b4922ea90d19d7e0510a205740b4c150057e988/connector/connect/client/jvm/src/main/scala/org/apache/spark/sql/SparkSession.scala#L214-L235

and

https://github.com/apache/spark/blob/7b4922ea90d19d7e0510a205740b4c150057e988/connector/connect/client/jvm/src/main/scala/org/apache/spark/sql/SparkSession.scala#L245-L267

So this pr introduces a new `private` function named `sql` in `SparkSession`. This function takes the type of `proto.SqlCommand` as its input, and the above two functions are refactored to call the newly added function in order to remove duplicate code. 

### Why are the changes needed?
To eliminate duplicate code.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass GitHub Actions

### Was this patch authored or co-authored using generative AI tooling?
No

### CODE REVIEW

**Review by zhengruifeng — APPROVED** [review]

**Review by dongjoon-hyun — DISMISSED** [review]
Please file a JIRA issue and use it in the PR title, @LuciferYang .

**Comment by dongjoon-hyun** [comment]
I converted this to `Draft` back in order to prevent accidental merging (without JIRA ID), @LuciferYang . Feel free to make it back to normal PR after adding JIRA ID.

**Comment by LuciferYang** [comment]
> Please file a JIRA issue and use it in the PR title, @LuciferYang .

Thanks @dongjoon-hyun , I forgot to fill in the Jira ID yesterday, I've filled it in now

**Comment by LuciferYang** [comment]
Could you please help review it again if you have time @dongjoon-hyun Thanks ~

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @LuciferYang and @zhengruifeng .
Merged to master.

**Comment by LuciferYang** [comment]
Thanks @dongjoon-hyun and @zhengruifeng ~

**Pull request closed without merging**
