### PR TITLE
[SPARK-25321][ML] Revert SPARK-14681 to avoid API breaking change

### PR DESCRIPTION
**Pull request by WeichenXu123**
## What changes were proposed in this pull request?

Revert SPARK-14681 to avoid API breaking change. PR [SPARK-14681] will break mleap. 

## How was this patch tested?

N/A

### CODE REVIEW

**Comment by cloud-fan** [comment]
Since this changes public API, shall we also revert it from master?

**Comment by WeichenXu123** [comment]
@mengxr Should this be put into master ?

**Comment by mengxr** [comment]
We can keep it in master if the next release is 3.0.

**Comment by mengxr** [comment]
LGTM. Merged into branch-2.4. @WeichenXu123 Next time please create dedicated JIRAs for each QA task PR. Thanks!

**Comment by mengxr** [comment]
@WeichenXu123 Please close this PR manually. Thanks!

**Comment by cloud-fan** [comment]
The next version is very likely to be 2.5.0...

**Comment by mengxr** [comment]
@WeichenXu123 @cloud-fan I made https://github.com/apache/spark/pull/22618 to revert the change in master.

**Comment by dongjoon-hyun** [comment]
May I ask a question, @mengxr ? The master becomes 3.0 today by @gatorsmile 's PR and I saw the following your comment here.
> We can keep it in master if the next release is 3.0.

Is there any new reason to change the decision?

**Comment by mengxr** [comment]
@cloud-fan said above the next version is very likely to be 2.5.0 instead of 3.0. Well the next version number is not fully discussed yet. For that reason, I think we should revert the changes in master as well. After that we should check if the feature itself can be added without introducing breaking changes.

**Comment by dongjoon-hyun** [comment]
Thank you! Although `master` becomes [3.0.0](https://github.com/apache/spark/pull/22606) already and seems to start to target `Mar 2019`, I agree with you on reverting for rechecking, @mengxr . Spark 3.0.0 has better have the minimal number of incompatible APIs.

**Pull request closed without merging**
