### PR TITLE
[SPARK-6285] [SQL] Removes unused ParquetTestData and duplicated TestGroupWriteSupport

### PR DESCRIPTION
**Pull request by liancheng**
All the contents in this file are not referenced anywhere and should have been removed in #4116 when I tried to get rid of the old Parquet test suites.

[Review on Reviewable](https://reviewable.io/reviews/apache/spark/5010)

### CODE REVIEW

**Comment by srowen** [comment]
LGTM, go for it if Jenkins succeeds.

**Comment by srowen** [comment]
jenkins, retest this please

**Comment by liancheng** [comment]
@srowen Thanks for the review! Gonna merge this into master and branch-1.3

**Comment by liancheng** [comment]
Actually I'm not quite sure whether this should backported to branch-1.3 at this moment, merged to master only for safe. @pwendell?

**Comment by srowen** [comment]
This is more of a cleanup and improvement than bug fix. Although it can affect the build in some contexts, it does not affect the build of reference. Generally I think of improvements as things that are not back-ported unless they are large, important improvements. So I think it's safe to just merge to master, IMHO.

**Pull request closed without merging**
