### PR TITLE
[SPARK-45283][CORE][TESTS][3.5] Make StatusTrackerSuite less fragile

### PR DESCRIPTION
**Pull request by xiongbo-sjtu**
### Why are the changes needed?

It's discovered from [Github Actions](https://github.com/xiongbo-sjtu/spark/actions/runs/6270601155/job/17028788767) that StatusTrackerSuite can run into random failures, as shown by the following error message.  The proposed fix is to update the unit test to remove the nondeterministic behavior.

The fix has been made to the master branch in https://github.com/apache/spark/pull/43194.  This PR is meant to patch branch-3.5 only.

```
    [info] StatusTrackerSuite:
    [info] - basic status API usage (99 milliseconds)
    [info] - getJobIdsForGroup() (56 milliseconds)
    [info] - getJobIdsForGroup() with takeAsync() (48 milliseconds)
    [info] - getJobIdsForGroup() with takeAsync() across multiple partitions (58 milliseconds)
    [info] - getJobIdsForTag() *** FAILED *** (10 seconds, 77 milliseconds)
    [info] The code passed to eventually never returned normally.
           Attempted 651 times over 10.005059944000001 seconds. 
           Last failure message: Set(3, 2, 1) was not equal to Set(1, 2). (StatusTrackerSuite.scala:148)
```

Full trace can be found [here](https://issues.apache.org/jira/browse/SPARK-45283).

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
```
build/mvn package -DskipTests -pl core
build/mvn -Dtest=none -DwildcardSuites=org.apache.spark.StatusTrackerSuite test
```

### Was this patch authored or co-authored using generative AI tooling?
No

### CODE REVIEW

**Comment by xiongbo-sjtu** [comment]
@LuciferYang  

Per [your request](https://github.com/apache/spark/pull/43194#issuecomment-1763312763), I'm creating this PR.  Please merge it to branch-3.5 at your convenience.

**Comment by smileyboy2019** [comment]
CEP support in Spark Streaming

**Review by LuciferYang — APPROVED** [review]
LGTM if test pass

**Comment by LuciferYang** [comment]
Merged into branch-3.5 to fix the flaky test. Thanks @xiongbo-sjtu

**Pull request closed without merging**
