### PR TITLE
[SPARK-37783][SQL][FOLLOWUP] Enable tail-recursion wherever possible

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr adds `@scala.annotation.tailrec` inspected by IDE (IntelliJ) 

### Why are the changes needed?
To improve performance.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass GA

### CODE REVIEW

**Comment by LuciferYang** [comment]
cc @HyukjinKwon

**Review by HyukjinKwon — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Could you add an empty commit to re-trigger CI, @LuciferYang ?

**Comment by LuciferYang** [comment]
Manual re-trigger CI, waiting for results

**Comment by LuciferYang** [comment]
@dongjoon-hyun @HyukjinKwon GA Passed

**Comment by dongjoon-hyun** [comment]
Yep. Thanks, @LuciferYang .
Merged to master.

**Comment by LuciferYang** [comment]
thanks all

**Pull request closed without merging**
