### PR TITLE
[Hotfix][Examples] fix a Javadoc of a preformated text in JavaSimpleParamsExample

### PR DESCRIPTION
**Pull request by yu-iskw**

### CODE REVIEW

**Comment by vanzin** [comment]
Hi,

Since this is not fixing a build break, "hotfix" doesn't really apply. Otherwise, looks straight-forward enough.

**Comment by srowen** [comment]
Agree, this is not a fix. The modern way to write code javadoc is ...

```
{@code
val foo = ...
}
```

... but for consistency with other javadoc this is good enough.

**Comment by yu-iskw** [comment]
@srowen how about changing all the `<pre>` to `{@code...}`?

**Comment by srowen** [comment]
Hm, I do see many more uses of `{@code }` in the project than `<pre>` for this purpose, which is good. It would be reasonable to fix, at least, all the Java examples in one go here. Or, even fix all 14 instances I see in the code at once, everywhere. If so, make a JIRA please.

**Comment by yu-iskw** [comment]
Alright. I'll create a JIRA to change all `<pre>` to `{@code...}`. I'll send another PR later. Thanks!

**Pull request closed without merging**
