### PR TITLE
[SPARK-46066][SQL] Use the Separators API instead of the String API to construct the `DefaultPrettyPrinter`

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr use the `Separators` API instead of the `String` API to construct Jackson `DefaultPrettyPrinter` due to the   `String` API has been marked as deprecated in Jackson 2.16.0:

```java
    /**
     * Constructor that specifies separator String to use between root values;
     * if null, no separator is printed.
     *<p>
     * Note: simply constructs a {@link SerializedString} out of parameter,
     * calls {@link #DefaultPrettyPrinter(SerializableString)}
     *
     * @param rootSeparator String to use as root value separator
     * @deprecated in 2.16. Use the Separators API instead.
     */
    @Deprecated
    public DefaultPrettyPrinter(String rootSeparator) {
        this((rootSeparator == null) ? null : new SerializedString(rootSeparator));
    }

```

### Why are the changes needed?
Clean up deprecated Jackson API usage.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass Github Actions

### Was this patch authored or co-authored using generative AI tooling?
No

### CODE REVIEW

**Comment by LuciferYang** [comment]
Only one case

**Comment by LuciferYang** [comment]
https://github.com/LuciferYang/spark/actions/runs/6966542450/job/18958629916

image

@dongjoon-hyun A failed case of `RocksDBStateStoreStreamingAggregationSuite` after we move it to dedicated JVM test group

**Comment by dongjoon-hyun** [comment]
Hmm. Ack. Thank u for sharing.

**Comment by dongjoon-hyun** [comment]
Oh, the error message is interesting.
```
10:34:38.776 WARN org.apache.spark.sql.execution.streaming.state.RocksDB StateStoreId(opId=0,partId=0,name=default): Error closing RocksDB
org.apache.spark.SparkException: [CANNOT_LOAD_STATE_STORE.UNRELEASED_THREAD_ERROR] An error occurred during loading state.
StateStoreId(opId=0,partId=0,name=default): RocksDB instance could not be acquired by [ThreadId: Some(1784)] as
it was not released by [ThreadId: Some(1783), task: partition 0.0 in stage 509.0, TID 1365] after 120008 ms.
```

**Comment by LuciferYang** [comment]
> Oh, the error message is interesting. For me, it's a different message.
> 
> ```
> 10:34:38.776 WARN org.apache.spark.sql.execution.streaming.state.RocksDB StateStoreId(opId=0,partId=0,name=default): Error closing RocksDB
> org.apache.spark.SparkException: [CANNOT_LOAD_STATE_STORE.UNRELEASED_THREAD_ERROR] An error occurred during loading state.
> StateStoreId(opId=0,partId=0,name=default): RocksDB instance could not be acquired by [ThreadId: Some(1784)] as
> it was not released by [ThreadId: Some(1783), task: partition 0.0 in stage 509.0, TID 1365] after 120008 ms.
> ```

This is the first time I've seen this error message.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by LuciferYang** [comment]
Thanks @dongjoon-hyun

**Pull request closed without merging**
