### PR TITLE
[SPARK-29152][CORE][2.4] Executor Plugin shutdown when dynamic allocation is enabled

### PR DESCRIPTION
**Pull request by iRakson**
### What changes were proposed in this pull request?
Added a shutdown hook which will ensure that shutdown method of executor plugin is getting called.

### Why are the changes needed?
When dynamic allocation is enabled and executors get killed after idle time out, shutdown method of executor plugin is not getting called.

### Does this PR introduce any user-facing change?
No

### How was this patch tested?
Manually Tested

### CODE REVIEW

**Comment by iRakson** [comment]
@srowen

**Review by srowen — COMMENTED** [review]
Looks OK pending tests

**Comment by dongjoon-hyun** [comment]
Hi, @iRakson . Since you are making contribution continuously, I'd like to recommend you to use ` [SPARK-29152][CORE][2.4]` style for backporting. It's a tiny change, but improves PR's visibility in the community.

**Comment by dongjoon-hyun** [comment]
Also, cc @vanzin .

**Comment by vanzin** [comment]
I'm confused. #26315 was closed because of a conflict, and instead this was open against 2.4.

But doesn't the issue still exist in the master branch? It should be fixed there first.

**Comment by srowen** [comment]
(Did it go away in master when the executor plugin stuff was removed? that was the claim)

**Comment by vanzin** [comment]
The executor plugin stuff wasn't removed, it was changed.

**Pull request closed without merging**
