### PR TITLE
[SPARK-46393][SQL] Classify exceptions in the JDBC table catalog

### PR DESCRIPTION
**Pull request by MaxGekk**
### What changes were proposed in this pull request?
In the PR, I propose to handle exceptions from JDBC drivers in the JDBC table catalog, classify them and converted to appropriate Spark exception w/ an error class. This PR covers the following functions where such errors haven't been classified yet:
- list tables
- namespace exists
- list namespaces

### Why are the changes needed?
To unify Spark exceptions, and migrate onto new error framework.

### Does this PR introduce _any_ user-facing change?
Yes, if user code expects that Spark SQL bypass Java exceptions from JDBC drivers.

### How was this patch tested?
By existing test suites:
```
$ build/sbt "test:testOnly *JDBCV2Suite"
$ build/sbt "test:testOnly *JDBCTableCatalogSuite"
```

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]

**Comment by srielau** [comment]
@MaxGekk 
Is this just doing:
/**
   * Gets a dialect exception, classifies it and wraps it by `AnalysisException`.
   * @param message The error message to be placed to the returned exception.
   * @param e The dialect specific exception.
   * @return `AnalysisException` or its sub-class.
   */
  def classifyException(message: String, e: Throwable): AnalysisException = {
    new AnalysisException(
      errorClass = "_LEGACY_ERROR_TEMP_3064",
      messageParameters = Map("msg" -> message),
      cause = Some(e))
  }
  
  Shouldn't we raise proper error classes instead of hiding behind "message"

**Comment by cloud-fan** [comment]
@srielau This seems like a lot of work as we need to understand different errors from different databases. Shall we have a general error class name as the fallback? Each JDBC dialect can override this method and provide more concrete error classes.

**Comment by srielau** [comment]
> @srielau This seems like a lot of work as we need to understand different errors from different databases. Shall we have a general error class name as the fallback? Each JDBC dialect can override this method and provide more concrete error classes.

I count 8 invocations of classifyException() in this file. Each invocation adds better information using English. Why can't these be error classes?

**Comment by MaxGekk** [comment]
> At a minimum we could give: _LEGACY_ERROR_TEMP_3064 a proper name and each of these invocations picks a subclass.

There are no tests at all for the cases where JDBC op fails. I believe we should go by the regular way: write tests, update docs, assign names, improve error messages, and so.

**Comment by MaxGekk** [comment]
Merging to master. Thank you, all for review.

**Comment by srielau** [comment]
Opened: https://issues.apache.org/jira/browse/SPARK-46410 as follow up.

**Comment by MaxGekk** [comment]
@srielau @cloud-fan The small PR with assigned names is ready: https://github.com/apache/spark/pull/44358

**Pull request closed without merging**
