### PR TITLE
[SPARK-13264][Doc] Removed multi-byte characters in spark-env.sh.template

### PR DESCRIPTION
**Pull request by sasakitoa**
In spark-env.sh.template, there are multi-byte characters, this PR will remove it.

### CODE REVIEW

**Comment by srowen** [comment]
OK, but can you fix the other occurrence in `serialize.R` comments?

**Comment by sasakitoa** [comment]
Thank you for reviewing, @srowen .
I fixed some files which are used multi-byte character.

**Comment by sarutak** [comment]
ok to test.

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
