### PR TITLE
[SPARK-33107][SQL] Remove hive-2.3 workaround code

### PR DESCRIPTION
**Pull request by wangyum**
### What changes were proposed in this pull request?

This pr remove `hive-2.3` workaround code.

### Why are the changes needed?

Make code more clear and readable.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Existing unit tests.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Thank you for the clean-up, @wangyum !

**Comment by HyukjinKwon** [comment]
Thanks, @wangyum.

**Comment by HyukjinKwon** [comment]
cc @juliuszsompolski FYI

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.
Merged to master for Apache Spark 3.1.0.

**Pull request closed without merging**
