### PR TITLE
[SPARK-33921][BUILD] Upgrade Scala version to 2.12.12

### PR DESCRIPTION
**Pull request by viirya**
### What changes were proposed in this pull request?

This proposes to upgrade Scala 2.12 patch version to 2.12.12.

### Why are the changes needed?

To catch up with bug fix and improvement of latest Scala 2.12 patch.

https://github.com/scala/scala/releases/tag/v2.12.11
https://github.com/scala/scala/releases/tag/v2.12.12

* Performance improvements in the collections library, the compiler
* Fix memory leak in runtime reflection's `TypeTag` caches
* Fix some `toX` methods that could expose the underlying mutability of a ListBuffer-generated collection
* ASM was upgraded to 7.3.1, allowing the optimizer to run on JDK 13+

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Unit test

### CODE REVIEW

**Comment by viirya** [comment]
Hm, seems Scala version needs to be upgraded with Kafka together..

**Comment by dongjoon-hyun** [comment]
Thank you for closing, @viirya .

FYI, in terms of Scala 2.12.12, we discussed on our dev mailing list and have a reason not to support due to the regression.
- https://lists.apache.org/thread.html/re1399662a07372186e661a13e2d6bcc67350010c3baccd217b92754d%40%3Cdev.spark.apache.org%3E

We may try this later with Scala 2.12.13 (if it exists).

cc @srowen

**Comment by viirya** [comment]
Hmm, if so, seems we cannot support Kafka 2.7.0. Due to Kafka core inlines the Scala library, seems we cannot use a different Scala patch version than what Kafka used to compile its jars.

**Comment by dongjoon-hyun** [comment]
cc @wangyum too since he is the original author of #29124 ([WIP][SPARK-31168][BUILD] Upgrade Scala to 2.12.12) .

**Pull request closed without merging**
