### PR TITLE
[SPARK-28241][SQL] Show metadata operations on ThriftServerTab

### PR DESCRIPTION
**Pull request by wangyum**
## What changes were proposed in this pull request?

This pr add support show metadata operations on ThriftServerTab.

## How was this patch tested?

manual tests:
image

### CODE REVIEW

**Comment by wangyum** [comment]
cc @juliuszsompolski

**Review by juliuszsompolski — APPROVED** [review]
LGTM. Thanks! cc @gatorsmile

**Review by hvanhovell — APPROVED** [review]
LGTM

**Comment by juliuszsompolski** [comment]
Thank you very much @wangyum for the series of thriftserver improvements!
What do you think of just 1 more improvement idea: Currently, the ThriftServerTab displays a FINISHED state when the operation finishes execution, but quite often it still takes a lot of time to fetch the results. OperationState has state CLOSED for when after the iterator is closed. Could we add CLOSED state to ExecutionState, and override the close() in SparkExecuteStatement / GetSchemas / GetTables / GetColumns to do HiveThriftServerListener.onOperationClosed?

**Comment by wangyum** [comment]
Thank you @juliuszsompolski I'm working on this issue: [SPARK-28260](https://issues.apache.org/jira/browse/SPARK-28260)

**Pull request closed without merging**
