### PR TITLE
[MINOR] Move java file to java directory

### PR DESCRIPTION
**Pull request by ConeyLiu**
## What changes were proposed in this pull request?

move 
```scala
org.apache.spark.sql.execution.streaming.BaseStreamingSource
org.apache.spark.sql.execution.streaming.BaseStreamingSink
```
to java directory

## How was this patch tested?

Existing UT.

### CODE REVIEW

**Comment by ConeyLiu** [comment]
Hi @srowen, can you help to review. Thanks a lot.

**Comment by srowen** [comment]
I agree with moving the code, but why change the package?

**Comment by srowen** [comment]
Offset.java can be moved too?

**Comment by dongjoon-hyun** [comment]
+1 for @srowen 's comment. We should keep the package name.

**Comment by dongjoon-hyun** [comment]
ok to test

**Comment by ConeyLiu** [comment]
thanks @srowen  @dongjoon-hyun for the review. I am referring to @cloud-fan 's point of view. 
[`shall we move these new interfaces to org.apache.spark.sql.sources.v2.reader/write.streaming package?`](https://github.com/apache/spark/pull/19925)

> Offset.java can be moved too?
Will move it later.

**Comment by cloud-fan** [comment]
These 2 interfaces are internal and I don't think we can move them to a public package now.

**Comment by ConeyLiu** [comment]
thanks @cloud-fan, just move those files to java directory. 
Hi @srowen, `Offset.java` already under java directory.

**Comment by srowen** [comment]
I'm looking at `sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/Offset.java` -- seems like that should move too?

**Comment by ConeyLiu** [comment]
thanks @srowen for point out it. I have moved it too.

**Review by attilapiros — APPROVED** [review]
LGTM

I have not found any other '*.java" file under scala directories which can be moved. 
I used the following search:

```
$ find . -name "scala" -exec find \{} -name "*.java" \; | grep -v package-info
./mllib/src/main/scala/org/apache/spark/mllib/JavaPackage.java
./sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/BaseStreamingSink.java
./sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/BaseStreamingSource.java
./sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/Offset.java
```

JavaPackage.java must be kept in its current place as:
```
/**
 * A dummy class as a workaround to show the package doc of <code>spark.mllib</code> in generated
 * Java API docs.
 * @see <a href="http://bugs.java.com/bugdatabase/view_bug.do?bug_id=4492654" target="_blank">
 *      JDK-4492654</a>
 */
```

**Review by srowen — APPROVED** [review]
LG pending tests

**Comment by srowen** [comment]
Merged to master

**Comment by ConeyLiu** [comment]
thanks everyone.

**Pull request closed without merging**
