### PR TITLE
[MINOR] [SQL] Fix sphinx warnings in PySpark SQL

### PR DESCRIPTION
**Pull request by MechCoder**

### CODE REVIEW

**Comment by mengxr** [comment]
Could you also fix the warning in core?

**Comment by MechCoder** [comment]
Which warning is this? I do not get any warning

**Comment by mengxr** [comment]
I got the following:

~~~
/Users/meng/src/spark/python/pyspark/__init__.py:docstring of pyspark.SparkContext.applicationId:4: ERROR: Unexpected indentation.
/Users/meng/src/spark/python/pyspark/__init__.py:docstring of pyspark.SparkContext.applicationId:6: WARNING: Block quote ends without a blank line; unexpected unindent.
~~~

**Comment by MechCoder** [comment]
I still could not reproduce the error. I just guessed it from the warning :P

**Comment by MechCoder** [comment]
test this please

**Comment by mengxr** [comment]
This is the generated html doc:

screen shot 2015-08-13 at 11 35 10 pm

I think we should use `-` with indentation instead of `a]` and `b]`.

**Comment by MechCoder** [comment]
I used asterisks as done in pyspark/mllib/clustering . Hopefully it should look good now.

**Comment by mengxr** [comment]
LGTM. Merged into master and branch-1.5. Thanks!

**Pull request closed without merging**
