### PR TITLE
[SPARK-37934][BUILD][3.2] Upgrade Jetty version to 9.4.44

### PR DESCRIPTION
**Pull request by JackBuggins**
### What changes were proposed in this pull request?

Mirroring https://github.com/apache/spark/pull/35230 but applying this to the 3.2 stream; the only difference is that  `./dev/test-dependencies.sh --replace-manifest` does not appear to modify the test dep manifests in the same way as against master. Core was the only jar in the latest scala 2.12/hadoop 2.7 bundle I could find containing this.

### Why are the changes needed?

April is a little while away and since 3.2.1 has completed, now seems like as sensible a time as any to look at providing the minor dependency update as a precaution for the 3.2 stream to provide mitigation against the original issue reported in https://github.com/eclipse/jetty.project/issues/6973 

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Executing test suites for core.

```
$ build/sbt
> project core
> test
```

On first execution I received the following results 

```
[info] Tests: succeeded 2890, failed 1, canceled 4, ignored 8, pending 0
[info] *** 1 TEST FAILED ***
[error] Failed: Total 3152, Failed 1, Errors 0, Passed 3151, Ignored 8, Canceled 4
[error] Failed tests:
[error]         org.apache.spark.executor.ExecutorSuite
```

After checking out a clean branch from 3.2 I discovered that for some reason this test intermittently fails and it seems unrelated to this change, I have observed this test passing against this changeset and the base branch; is this a known issue?

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
cc @srowen and @HyukjinKwon

**Comment by dongjoon-hyun** [comment]
BTW, @JackBuggins . Could you enable GitHub Action in your forked Spark repository?
- https://github.com/apache/spark/pull/35338/checks?check_run_id=4957367779

**Comment by dongjoon-hyun** [comment]
@JackBuggins . You can reopen this after discussing about the requirement on this PR.

**Comment by ngton** [comment]
@dongjoon-hyun Hi, can this PR be merged?

The is a DoS vulnerability in the current version of jetty: https://github.com/eclipse/jetty.project/issues/6973

CVE:               PRISMA-2021-0182
Sev.:              medium
Package Name:      org.eclipse.jetty_jetty-server
Package Ver.:      9.4.43.v20210629
Status:            fixed in 9.4.44
Description:       org.eclipse.jetty_jetty-server package versions before 9.4.44 are vulnerable to DoS (Denial of Service). Logback-access calls Request.getParameterNames() for request logging. That will force a request body read (if it hasn't been read before) per the servlet. This will now consume resources to read the request body content, which could easily be malicious (in size? in keys? etc), even though the application intentionally didn't read the request body.

Found in Twistlock

Making this change will remediate, just like has been done on master here: https://github.com/apache/spark/pull/35230

**Comment by dongjoon-hyun** [comment]
In general, Spark clusters are operated in the private networks. Do you have a public Spark clusters which are vulnerable, @ngton ?

**Comment by srowen** [comment]
I think it's fine to back-port - DoS is a possibility even on internal networks. Even if the risk is small, the backport is a tiny version bump, so think it's OK. Would you care to open a backport PR vs branch-3.2? Just the same change, applied to 3.2

**Comment by JackBuggins** [comment]
I will create this PR against branch-3.2 today based on a fresh fork, with _Build and test_ and _Report test results_ workflows enabled this time around.

@srowen - regarding `./dev/test-dependencies.sh --replace-manifest` having a different result; is there anything additional I should be running here that is not outlined in [the contributing guide](https://spark.apache.org/contributing.html)?

**Comment by srowen** [comment]
No just run that script and include its changes in the PR. The result ought to be pretty much identical to the change in master.

**Comment by srowen** [comment]
Oh, you can reuse this PR/branch if you want, I didn't realize this was already a 3.2 pull request. Just needs to the dep changes and tests enabled

**Comment by JackBuggins** [comment]
Thanks. I'd removed my fork so I'll have to raise again. I have tests running in https://github.com/JackBuggins/spark/actions/runs/1811822649; they are looking good.

This script is not modifying any other files in this instance; and jetty listed under /dev/deps is pointing at

```
jetty-util/6.1.26//jetty-util-6.1.26.jar
jetty/6.1.26//jetty-6.1.26.jar
```

It looks like no entry was ever made against `9.4.x` of Jetty. After executing the script, the following diffs are empty

```
Jack:spark $ diff dev/pr-deps/spark-deps-hadoop-2.7-hive-2.3 dev/deps/spark-deps-hadoop-2.7-hive-2.3
Jack:spark $ diff dev/pr-deps/spark-deps-hadoop-3.2-hive-2.3 dev/deps/spark-deps-hadoop-3.2-hive-2.3
```

Is there something prior that should be setting this? I'll try and track the commit where it was introduced in the latest branch.

**Comment by JackBuggins** [comment]
Interestingly, this seems consistent with the previous upgrade against this branch - https://github.com/apache/spark/commit/f0844f70b11f5e7d0a3efb5a30abf9edb478d19b

**Comment by srowen** [comment]
It's right here:
https://github.com/apache/spark/blob/master/dev/deps/spark-deps-hadoop-3-hive-2.3#L137

There is also an old copy of jetty from some dependency, but Spark uses 9.x

**Comment by srowen** [comment]
Oh strange, not in branch 3.2. In that case ignore it if there is no deps change

**Pull request closed without merging**
