### PR TITLE
[SPARK-13019][Docs] fix for scala-2.10 build: Replace example code in mllib-statistics.md using include_example

### PR DESCRIPTION
**Pull request by keypointt**
## What changes were proposed in this pull request?

This PR for ticket SPARK-13019 is based on previous PR(https://github.com/apache/spark/pull/11108).
Since PR(https://github.com/apache/spark/pull/11108) is breaking scala-2.10 build, more work is needed to fix build errors.

What I did new in this PR is adding keyword argument for 'fractions':
`val approxSample = data.sampleByKey(withReplacement = false, fractions = fractions)`
`val exactSample = data.sampleByKeyExact(withReplacement = false, fractions = fractions)`

I reopened ticket on JIRA but sorry I don't know how to reopen a GitHub pull request, so I just submitting a new pull request.
## How was this patch tested?

Manual build testing on local machine, build based on scala-2.10.

### CODE REVIEW

**Comment by mengxr** [comment]
add to whitelist

**Comment by mengxr** [comment]
ok to test

**Comment by mengxr** [comment]
LGTM pending Jenkins

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
