### PR TITLE
[MINOR][TESTS] Replace JVM assert with JUnit Assert in tests

### PR DESCRIPTION
**Pull request by srowen**
### What changes were proposed in this pull request?

Use JUnit assertions in tests uniformly, not JVM assert() statements.

### Why are the changes needed?

assert() statements do not produce as useful errors when they fail, and, if they were somehow disabled, would fail to test anything. 

### Does this PR introduce any user-facing change?

No. The assertion logic should be identical.

### How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Is this all? It seems that we have more instances.

**Comment by srowen** [comment]
That's all IntelliJ found in the Java test code. There may be some in non-test code, but some are possibly legitimate. There are, I think, cases where assert() is used for argument checking in non-test code and that's not really what it's for, but a separate thing.

Yeah there are some in Scala tests too, I'll fix those. They're not obvious as scalatest uses assert() too, but we can look for use of scala.Predef.assert()

**Comment by srowen** [comment]
(PS to be clear the latest test failed; its result just came first. I'll investigate)

**Comment by dongjoon-hyun** [comment]
It seems that both Jenkins/GitHubAction fails due to `scala.reflect.macros.TypecheckException: not found: value assertionsHelper`.
```
[error] /home/jenkins/workspace/SparkPullRequestBuilder/core/src/test/scala/org/apache/spark/executor/ExecutorSuite.scala:570: exception during macro expansion: 
[error] scala.reflect.macros.TypecheckException: not found: value assertionsHelper
[error] 	at scala.reflect.macros.contexts.Typers.$anonfun$typecheck$3(Typers.scala:44)
[error] 	at scala.reflect.macros.contexts.Typers.$anonfun$typecheck$2(Typers.scala:38)
[error] 	at scala.reflect.macros.contexts.Typers.doTypecheck$1(Typers.scala:37)
[error] 	at scala.reflect.macros.contexts.Typers.$anonfun$typecheck$7(Typers.scala:50)
[error] 	at scala.reflect.internal.Trees.wrappingIntoTerm(Trees.scala:1756)
[error] 	at scala.reflect.internal.Trees.wrappingIntoTerm$(Trees.scala:1753)
[error] 	at scala.reflect.internal.SymbolTable.wrappingIntoTerm(SymbolTable.scala:28)
[error] 	at scala.reflect.macros.contexts.Typers.typecheck(Typers.scala:50)
[error] 	at scala.reflect.macros.contexts.Typers.typecheck$(Typers.scala:32)
[error] 	at scala.reflect.macros.contexts.Context.typecheck(Context.scala:18)
[error] 	at scala.reflect.macros.contexts.Context.typecheck(Context.scala:18)
[error] 	at scala.reflect.macros.Typers.typeCheck(Typers.scala:70)
[error] 	at scala.reflect.macros.Typers.typeCheck$(Typers.scala:69)
[error] 	at scala.reflect.macros.contexts.Context.typeCheck(Context.scala:18)
[error] 	at org.scalactic.MacroOwnerRepair.repairOwners(MacroOwnerRepair.scala:35)
[error] 	at org.scalactic.BooleanMacro.genMacro(BooleanMacro.scala:837)
[error] 	at org.scalatest.AssertionsMacro$.assert(AssertionsMacro.scala:34)
[error] 	at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at scala.reflect.macros.runtime.JavaReflectionRuntimes$JavaReflectionResolvers.$anonfun$resolveJavaReflectionRuntime$6(JavaReflectionRuntimes.scala:51)
[error] 	at scala.tools.nsc.typechecker.Macros.macroExpandWithRuntime(Macros.scala:824)
[error]           Assertions.assert(TaskContext.get().asInstanceOf[TaskContextImpl].fetchFailed.isDefined)
[error]                            ^
```

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by srowen** [comment]
PS @dongjoon-hyun is this failure 'normal'?

https://github.com/apache/spark/runs/311900764

```
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Using `mvn` from path: /home/runner/work/spark/spark/build/apache-maven-3.6.2/bin/mvn
./build/mvn: line 172: /home/runner/work/spark/spark/build/apache-maven-3.6.2/bin/mvn: No such file or directory
```

Just can't download maven?

**Comment by dongjoon-hyun** [comment]
Yes. It's a normal `Maven` Download failure. I'll try to cache the maven directory, too.

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
