### PR TITLE
Fix for [SPARK-12854][SQL] Implement complex types support in Columna…

### PR DESCRIPTION
**Pull request by jaceklaskowski**
…rBatch

Fixes build for Scala 2.11.

### CODE REVIEW

**Comment by rxin** [comment]
Jenkins, test this please.

**Comment by rxin** [comment]
cc @JoshRosen I can't seem to trigger a test run. If you have a chance please give it a shot.

**Comment by jaceklaskowski** [comment]
I'd appreciate having it merged since the current master is broken without the fix - checked early morning today.

**Comment by JoshRosen** [comment]
I dug into the logs and it looks like the horizontal ellipsis character (…) is breaking the test triggering code because we didn't handle / escape / strip Unicode characters properly. I'll fix this up now and trigger a new test run.

**Comment by jaceklaskowski** [comment]
@JoshRosen @rxin a friendly reminder to merge the change (or close it if irrelevant)

**Comment by rxin** [comment]
Merging this. Thanks.

**Pull request closed without merging**
