### PR TITLE
[SPARK-48974][SQL][SS][ML][MLLIB] Use `SparkSession.implicits` instead of `SQLContext.implicits`

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This PR replaces `SQLContext.implicits`  with `SparkSession.implicits` in the Spark codebase.

### Why are the changes needed?
Reduce the usage of code from `SQLContext` within the internal code of Spark.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass GitHub Actions

### Was this patch authored or co-authored using generative AI tooling?
No

### CODE REVIEW

**Comment by LuciferYang** [comment]
cc @HyukjinKwon 
Do you think we can mark `org.apache.spark.sql.SQLContext.implicits` as `deprecated`?

**Review by HyukjinKwon — APPROVED** [review]

**Comment by LuciferYang** [comment]
Merged into master. Thanks @HyukjinKwon

**Review by dongjoon-hyun — COMMENTED** [review]
+1, LGTM. Thank you, @LuciferYang and @HyukjinKwon .

**Comment by LuciferYang** [comment]
Thank you @dongjoon-hyun  ~

**Pull request closed without merging**
