### PR TITLE
[SPARK-28461][SQL] Pad Decimal numbers with trailing zeros to the scale of the column

### PR DESCRIPTION
**Pull request by wangyum**
## What changes were proposed in this pull request?

[HIVE-12063](https://issues.apache.org/jira/browse/HIVE-12063) improved pad decimal numbers with trailing zeros to the scale of the column. The following description is copied from the description of HIVE-12063.

> HIVE-7373 was to address the problems of trimming tailing zeros by Hive, which caused many problems including treating 0.0, 0.00 and so on as 0, which has different precision/scale. Please refer to HIVE-7373 description. However, HIVE-7373 was reverted by HIVE-8745 while the underlying problems remained. HIVE-11835 was resolved recently to address one of the problems, where 0.0, 0.00, and so on cannot be read into decimal(1,1).
 However, HIVE-11835 didn't address the problem of showing as 0 in query result for any decimal values such as 0.0, 0.00, etc. This causes confusion as 0 and 0.0 have different precision/scale than 0.
The proposal here is to pad zeros for query result to the type's scale. This not only removes the confusion described above, but also aligns with many other DBs. Internal decimal number representation doesn't change, however.

**Spark SQL**:
```sql
// bin/spark-sql
spark-sql> select cast(1 as decimal(38, 18));
1
spark-sql>

// bin/beeline
0: jdbc:hive2://localhost:10000/default> select cast(1 as decimal(38, 18));
+----------------------------+--+
| CAST(1 AS DECIMAL(38,18))  |
+----------------------------+--+
| 1.000000000000000000       |
+----------------------------+--+

// bin/spark-shell
scala> spark.sql("select cast(1 as decimal(38, 18))").show(false)
+-------------------------+
|CAST(1 AS DECIMAL(38,18))|
+-------------------------+
|1.000000000000000000     |
+-------------------------+

// bin/pyspark
>>> spark.sql("select cast(1 as decimal(38, 18))").show()
+-------------------------+
|CAST(1 AS DECIMAL(38,18))|
+-------------------------+
|     1.000000000000000000|
+-------------------------+

// bin/sparkR
> showDF(sql("SELECT cast(1 as decimal(38, 18))"))
+-------------------------+
|CAST(1 AS DECIMAL(38,18))|
+-------------------------+
|     1.000000000000000000|
+-------------------------+
```

**PostgreSQL**:
```sql
postgres=# select cast(1 as decimal(38, 18));
       numeric
----------------------
 1.000000000000000000
(1 row)
```
**Presto**:
```sql
presto> select cast(1 as decimal(38, 18));
        _col0
----------------------
 1.000000000000000000
(1 row)
```

## How was this patch tested?

unit tests and manual test:
```sql
spark-sql> select cast(1 as decimal(38, 18));
1.000000000000000000
```
Spark SQL Upgrading Guide:
image

### CODE REVIEW

**Comment by wangyum** [comment]
retest this please

**Comment by dongjoon-hyun** [comment]
Thank you, @wangyum !

**Comment by HyukjinKwon** [comment]
Thanks @dongjoon-hyun and @wangyum

**Review by HyukjinKwon — APPROVED** [review]
Looks good if tests pass

**Comment by dongjoon-hyun** [comment]
`-Phadoop-3.2 -Phive-2.3` seems to fail with a different reason first.
```
[info] Building Spark using SBT with these arguments:  -Phadoop-3.2 -Phive-2.3 -Pspark-ganglia-lgpl -Pyarn -Pkubernetes -Pmesos -Phadoop-cloud -Phive -Phive-thriftserver -Pkinesis-asl test:package streaming-kinesis-asl-assembly/assembly
```

```
org.mockito.exceptions.base.MockitoException: 
ClassCastException occurred while creating the mockito mock :  
class to mock : 'javax.servlet.http.HttpServletRequest',
loaded by classloader : 'sun.misc.Launcher$AppClassLoader@490d6c15'   created class : 
'org.mockito.codegen.HttpServletRequest$MockitoMock$254323811', loaded by classloader : 'net.bytebuddy.dynamic.loading.MultipleParentClassLoader@6aed7392'   proxy instance class : 'org.mockito.codegen.HttpServletRequest$MockitoMock$254323811', loaded by classloader : 'net.bytebuddy.dynamic.loading.MultipleParentClassLoader@6aed7392'   instance creation by : ObjenesisInstantiator  You might experience classloading issues, please ask the mockito mailing-list. 
```

**Comment by wangyum** [comment]
retest this please

**Comment by wangyum** [comment]
@shahidki31 Could you fix this issue: https://issues.apache.org/jira/browse/SPARK-30068?

**Comment by shahidki31** [comment]
Thanks @wangyum. I will look into it. Not sure why it didn't fail earlier?

**Comment by wangyum** [comment]
@shahidki31 You can reproduce this issue by Github action: https://github.com/spark-thriftserver/spark/pull/1/checks?check_run_id=324625735

**Comment by shahidki31** [comment]
@wangyum I think I couldn't yet reproduce in my local. I will check again. It seems some issue with mocking HttpServletRequest. But there are tests (like AllExecutionPageSuite.scala) which does the same thing seems passing?

**Comment by wangyum** [comment]
Yes. I also couldn't reproduce it on my local machine, but I can reproduce it by Github actions.

**Comment by shahidki31** [comment]
@wangyum I am not sure, why it is suddenly started failing. If it is a blocker, then we can revert the test for time being, I'll raise it again once found the root cause?

**Comment by wangyum** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
Can we hold on for a moment? I am investigating the test failure at https://github.com/apache/spark/pull/26706.

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
^ this test failure will be fixed together at https://github.com/apache/spark/pull/26710

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by wangyum** [comment]
retest this please

**Comment by wangyum** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
Should really be fixed now...

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
