### PR TITLE
[SPARK-33141][SQL][FOLLOW-UP] Fix Scala 2.13 compilation

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to fix Scala 2.13 compilation.

### Why are the changes needed?

To recover Scala 2.13.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass GitHub Action Scala 2.13 build job.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
cc @cloud-fan

**Comment by dongjoon-hyun** [comment]
Also cc @viirya

**Review by viirya — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you so much, @viirya . I verified this manually.
```scala
$ dev/change-scala-version.sh 2.13
$ build/sbt test:compile -Pscala-2.13
[success] Total time: 264 s (04:24), completed Dec 4, 2020, 2:59:39 PM
```

Merged to master/branch-3.1.

**Comment by HyukjinKwon** [comment]
Thanks @dongjoon-hyun and @viirya

**Pull request closed without merging**
