### PR TITLE
[SPARK-42180][BUILD][DOCS] Update `SCALA_VERSION` in `_config.yml` to 2.12.17 

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr aims update `SCALA_VERSION` in `_config.yml` to 2.12.17 

### Why are the changes needed?
Should be consistent with the actual use

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass Github Actions

### CODE REVIEW

**Comment by LuciferYang** [comment]
This one should port to branch-3.4

**Comment by LuciferYang** [comment]
cc @dongjoon-hyun , and I think this one should port to branch-3.4

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by dongjoon-hyun** [comment]
Merged to master/3.4. Thank you!

**Comment by LuciferYang** [comment]
Thanks @dongjoon-hyun

**Pull request closed without merging**
