### PR TITLE
[SPARK-47884][INFRA] Switch ANSI SQL CI job to NON-ANSI SQL CI job

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to switch `ANSI SQL` GitHub Action job to `NON-ANSI SQL` GitHub Action job.
- Rename `build_ansi.yml` to `build_non_ansi.yml`
- Change job name from `ANSI` to `NON-ANSI`
- Change `SPARK_ANSI_SQL_MODE` to `false`.

### Why are the changes needed?

Since SPARK-44111, Apache Spark uses ANSI mode by default. So, we need to switch this to keep `NON-ANSI SQL` mode test coverage.
- https://github.com/apache/spark/pull/46013

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Manual review. This should be tested after merging.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Could you review this, @HyukjinKwon ?

**Review by HyukjinKwon — APPROVED** [review]

**Review by yaooqinn — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by dongjoon-hyun** [comment]
Thank you, @HyukjinKwon and @yaooqinn !

**Comment by dongjoon-hyun** [comment]
cc @cloud-fan

**Pull request closed without merging**
