### PR TITLE
[SPARK-43536][CORE] Fixing statsd sink reporter

### PR DESCRIPTION
**Pull request by venkateshbalaji99**
### What changes were proposed in this pull request?

The metrics type for spark counter metrics exported to statsD are mapped to gauge instead of counter.

### Why are the changes needed?

Due to spark counter metrics being cumulative and statsD counter metrics being delta, there is a contract mismatch between them. This leads to aggregation both on client(spark) and server(statsD) side, which results in the value of the metrics being wrong. Since StatsD does not do aggregation on gauge metric, spark should send its cumulative metrics as gauge too, to obtain correct value of the metric.

### Does this PR introduce _any_ user-facing change?

The counter metrics that are exported by statsD to any backends will be changed to gauge metrics instead of counter metrics. Any application that processes gauge and counter metrics differently will need to account for this change.

### How was this patch tested?

UT has been modified.

### CODE REVIEW

**Comment by venkateshbalaji99** [comment]
retest

**Comment by srowen** [comment]
See https://spark.apache.org/contributing.html and please fix up this PR. Needs more explanation too

**Comment by abmodi** [comment]
@dongjoon-hyun could you please review this. Thanks!

**Review by dongjoon-hyun — COMMENTED** [review]
Hi, @venkateshbalaji99 and @abmodi .
This is a very old behavior since Apache Spark 2.3.0 (6 years). Could you elaborate which `count` metric did you have an issue specifically?

**Comment by venkateshbalaji99** [comment]
> Hi, @venkateshbalaji99 and @abmodi . This is a very old behavior since Apache Spark 2.3.0 (6 years). Could you elaborate which `count` metric did you have an issue specifically?

I primarily tested the recordsRead.count and recordsWritten.count metrics, but the behaviour was similar for other count metrics as well (runTime.count was also behaving similarly)

**Comment by venkateshbalaji99** [comment]
Hi @paymog , as you have pointed out, this seems to be an issue in flink too, where the metric value is not being decremented upon each push, while statsd expects it to. But the motivation behind not wanting to add a decrement logic here is because this system is more resilient towards intermittent failures (like some packets being lost), since the total value will still be retained, whereas in the case where we opt to send delta ourselves, these kind of error might start up adding  up over time. Since gauge metrics match our use case fully, I think remapping the spark counter metrics to be interpreted as gauge by statsD would be the simplest solution.

**Comment by venkateshbalaji99** [comment]
Hi @dongjoon-hyun, can you please take another look if you have time? Thanks!

**Pull request closed without merging**
