### PR TITLE
[SPARK-24093][DStream][Minor]Make some fields of KafkaStreamWriter/In…

### PR DESCRIPTION
**Pull request by merlintang**
…ternalRowMicroBatchWriter visible to outside of the classes

## What changes were proposed in this pull request?

This PR is created to make relevant fields of KafkaStreamWriter and InternalRowMicroBatchWriter visible to outside of the classes.

## How was this patch tested?
manual tests

### CODE REVIEW

**Comment by merlintang** [comment]
@jerryshao  can you review this minor update ?

**Comment by jerryshao** [comment]
Simply making these fields publicly accessible seems a little weird from Spark's side. Maybe we can use reflection instead.

**Comment by merlintang** [comment]
@jerryshao  Actually, we can not use reflection to get this field information.

**Comment by gaborgsomogyi** [comment]
Why is it required at all? Making things visible without proper reason is not a good idea.

**Comment by gaborgsomogyi** [comment]
Sounds weird. The topic names are available when the streaming app submitted. Why this can't be reused? Second option is reflection as jerryshao suggested.

**Comment by HyukjinKwon** [comment]
BTW, fields in class constructors is not visible without `val`. For instance,

```scala
class A(fieldA: String) { }
```

generates:

```bash
$ javap -private A.class
Compiled from "A.scala"
public class A {
  public A(java.lang.String);
}
```

FYI, when `val` is added:

```bash
$ javap -private A.class
Compiled from "A.scala"
public class A {
  private final java.lang.String fieldA;
  private java.lang.String fieldA();
  public A(java.lang.String);
}
```

**Comment by HeartSaVioR** [comment]
Yeah, that's what also I found interestingly on Scala. Constructor parameters can be used like fields in class but they're not exposed as fields, even private accessor. For case class we can pick up values in constructor parameters but it doesn't work with normal class.

**Pull request closed without merging**
