### PR TITLE
[SPARK-1537][WIP]: ats support for spark-on-yarn

### PR DESCRIPTION
**Pull request by zhzhan**
This is the patch to integrate ats and spark-on-yarn build against brach-1.2.  The patch also partially integrate the code from Marcelo Vanzin (Spark-1537).

To enable it, build with -Pyarn-history, and configure spark.yarn.services and spark.history.provider in spark-defaults.conf.

### CODE REVIEW

**Comment by vanzin** [comment]
Hi @zhzhan ,

The reason why I haven't posted my code for review is because Yarn does not provide all the needed public APIs to implement this. If you read the discussion in SPARK-1537 you'll see what I mean. For example, this class is used by my code (and yours too) when it actually shouldn't be:

   @Singleton
    @Provider
    @Unstable
    @Private
    public class YarnJacksonJaxbJsonProvider extends JacksonJaxbJsonProvider {

I strongly feel this code should not go in without Yarn providing the needed, *public* APIs to properly implement this.

**Comment by zhzhan** [comment]
@vanzin Thanks for looking into this. Please feel free to provide any comments and concerns. This is the reason I marked this PR as WIP. The purpose of it is to gather feedback and provide the reference to people who are interested.

**Comment by vanzin** [comment]
@zhzhan the concern is that I have the code to do this already, and it's blocked on Yarn providing the needed public APIs. Another person posting slightly modified code that has the same shortcomings doesn't fix the problem that Yarn still doesn't have those APIs.

**Comment by sryza** [comment]
More generally, it's better not to have PRs up that are blocked on something other than reviews, because it clogs up the review system.

**Comment by andrewor14** [comment]
@zhzhan Also, please file an accompanying JIRA for this. As others have mentioned it is preferable to build this on top of a stable YARN API instead. For this reason I would recommend that we close this PR for now until the proper support is in place.

**Comment by zhzhan** [comment]
@vanzin The patch is relatively small, but it is "not slightly modified code".  Except some routine code, the critical design is totally different. If you look into the code in details, you will be aware of it. In another aspect, you will also find a lot of code in the patch is similar to ats implementation in Tez, Yarn TimelineClient itself, and Spark related code. 

@sryza There are some projects, e.g., Tez, already supporting ATS. It is hard to wait for other component to be perfect, and I think it is more like mutual process to improve both components. For example, spark-on-yarn(alpha, stable, etc) is  in similar situation. But it does not prevent it gaining popularity, and getting more and more stable now.

@andrewor14  The reason I didn't open or attach to a JIRA is that Spark-1537 has opened and assigned. But the JIRA has opened for almost one year,  and I  didn't see progress for long time (please refer to the JIRA history).  This is also the major reason I marked the PR as WIP. In my testing, the patch can handle most of cases, except some corner cases to be identified. If you think it is better to have a jira, I will open one.

Folks, thanks for taking time looking at the code.  @vanzin If you have code ready except some caveats from timeline service in yarn. Please go ahead to send a PR with your patch. I would like to review your patch and don't mind close mine, so that we can make some progress.

**Comment by zhzhan** [comment]
@vanzin I attached the PR to JIRA SPARK-1537. After you send your PR, I don't mind closing mine and would like to review your patch. Thanks.

**Comment by vanzin** [comment]
@zhzhan it's not about the modifications you made to the code, it's about the modifications you did not make. There is no point in reviewing code that cannot go in, because it relies on internal Yarn APIs. If you're willing to rewrite those parts to not use internal APIs, please do so and then send the PR.

Otherwise, this PR is a non-starter. Sorry.

**Comment by zhzhan** [comment]
@vanzin I think my request is minimum and reasonable: please share your patch to the community so that we can move forward,  after the JIRA opened for almost one year, and I talked to and wait for you for more than half year. 

I also want to clarify that it is not modification since I have the core code ready before I was even aware of this PR.

**Comment by vanzin** [comment]
@zhzhan I think you're missing my point. I don't want to share my patch because it uses internal Yarn APIs. We don't want to include such code in Spark because it's bad practice to do so.

Your code uses the same internal APIs. Until you fix that, your patch will also not go forward, just as mine wouldn't.

It's not about me not wanting your patch to go in because I have a similar one. It's because your patch, like mine, has a fatal flaw that makes it not suitable for inclusion in Spark. Fix that flaw and we can go ahead.

**Comment by zhzhan** [comment]
@vanzin Probably some miscommunication here. It is not going into upstream or not. It is sharing the work with community after a long time.

**Comment by vanzin** [comment]
Hi @zhzhan ,

If you want to discuss the architecture of your patch, write a document and attach it to the corresponding bug. Using a code review for that is not the best way forward.

**Comment by srowen** [comment]
@zhzhan take a look at the JIRA where Marcelo posted some of his code. I'm also not clear what you and Zhijie are looking for; it seemed like there has been code and specific YARN issues on offer for a long time. In fact didn't you reuse some of what @vanzin posted? 

But it looks like many of the YARN issues discussed there are resolved as of 2.6, except at least this one involving developer APIs. Maybe you can work on that? I can understand the argument that, hey, let's use non-public APIs and take the risk, but it might be a better use of time to just have it declared stable then. I'd rather not repeat the loop in https://issues.apache.org/jira/browse/SPARK-1537 

My hesitation is that there is already a lot of build complexity to support a bunch of Hadoop versions, and we'd have to have yet another type of build for YARN 2.6+ at least here, and if it changes again in 2.7, another one after that, just to support ATS, which is a nice-to-have but not critical thing. So I can sympathize with wanting to get this right, once.

Is that the only issue? I mean, if that were stable, is this PR what we'd all kind of like to commit? or are we realistically waiting for YARN 2.7, 2.8 before everyone's happy? in which case, yeah, I don't think a `[WIP]` PR makes sense. You can sure keep a branch / patch / design doc live in the JIRA. Even `[WIP]` PRs should be for those with reasonable expectation of going in soonish.

**Comment by zhzhan** [comment]
@srowen Thanks for the input. In the PR description I have mentioned that " The patch also partially integrate the code from Marcelo Vanzin (Spark-1537)."

**Comment by zhzhan** [comment]
@srowen Yarn timeline is in alpha phase, but hadoop is embracing it as it provides a lot of extra functionalities.  I will upload the patch and design doc to the JIRA. Before that, can you provide some clarification on alpha features in spark?

In hadoop, AFAIK such features will be disabled by default and user can enable it if they want to try it.  In spark, how to handle those alpha features that people may be interested in and want to play with it?

**Comment by srowen** [comment]
@zhzhan the problem is not creating 'alpha' features, but consuming them from elsewhere. These APIs don't exist at all until recent versions of YARN, so Spark needs another build profile and module to even compile this code without breaking existing users. 

It won't work for people using Spark with less than the latest YARN. That much is OK; it's only usable to people who want to build or package their own, although it won't benefit most Spark users yet. But this happens any time you want to add features that can only work with a newer version of, say, Hadoop. You just have to do this, if you really need to take advantage of some advanced functionality.

The build complexity is a bit painful. Only recently was YARN alpha support dropped and maintaining the two was a headache. The overhead is smaller for this kind of feature. But it's a modest nice-to-have, and, may end up requiring yet a second implementation if any API changes between, say, 2.6 and 2.7 again. If it were vital, it might be something that just has to be done, but IMHO I sympathize with waiting for stable APIs for a nice-to-have feature. Hence, anything that can be done to bless the APIs that are required in YARN for 2.7 seems like the best use of time.

Last question: I know the build already dodges around some tiny differences in API across YARN versions with reflection. Is that feasible here?

**Comment by zhzhan** [comment]
@srowen The patch works against hadoop-2.6. It does not have any impact on existing code base, and does not break anything without compiling against yarn-history profile and setting corresponding service.

Early adoption is always painful, but it gains a huge momentum  as we observed in spark-on-yarn alpha.
In my point of view, integration with ATS is becoming more and more important. Enabling this feature in spark also can collect feedback and provide feature request to Yarn timeline service. AFAIK, ATS itself is becoming a critical component of yarn and applications running on top of yarn.

I will post the design doc and patch to the JIRA.  Thanks all for the comments and feedback.

**Comment by zhzhan** [comment]
Thanks all for the review and inputs. Close it and post related stuff to JIRA.

**Comment by srowen** [comment]
@zhzhan yes the key is _just_ requires a new module and build profile. If the API changes, we need another one. I think this is the right approach -- for stable APIs. If the API won't change, then just mark it stable? I think that's the easiest way forward. (What do you mean by Spark on YARN?)

**Comment by zhzhan** [comment]
Folks, I post design doc and patch to JIRA. You are welcome to provide any feedback and comments.

**Comment by zhzhan** [comment]
@srowen Just to clarify, the patch has already have a new module and build profile. There is a light shim layer (trait), and even other third party service can be plugged in without any impact on existing code and features.

**Comment by srowen** [comment]
Yes, I referred to that, right? The point is that a module and build profile is a bit of a headache, especially if it might only work for one YARN version.

**Comment by vanzin** [comment]
HI @srowen,

For this particular feature the extra build profile will probably be unavoidable. The ATS API only showed up in hadoop 2.4 (IIRC). What we really should avoid is what you mention before, working with an unstable API and later have to change it - or worse, add another profile - to support the new stable API.

**Pull request closed without merging**
