### PR TITLE
[SPARK-29514][SQL] Add string function support for string_to_array

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

string_to_array(text, text [, text]) | text[] | splits string into array elements using supplied delimiter and optional null string | `string_to_array('xx~^~yy~^~zz', '~^~', 'yy')` | {xx,NULL,zz}
-- | -- | -- | -- | --

_FUNC_(text, delimiter [, replaced]) - splits string into array elements using supplied delimiter and optional null string
arguments：
   text - the original string 
   delimiter - string literal or regex
   replaced - string literal or regex

### Why are the changes needed?

supported by PostgreSQL

### Does this PR introduce any user-facing change?

add a string function

### How was this patch tested?

add ut

```sql
postgres=# select string_to_array(' ', '~.~');
 string_to_array
-----------------
 {" "}
(1 row)

postgres=# select string_to_array('xx~^~yy~^~zz~^~', '~^~', 'yy');
 string_to_array
-----------------
 {xx,NULL,zz,""}
(1 row)

postgres=# select string_to_array('xx~^~yy~^~zz~^~', '.*', 'yy');
  string_to_array
-------------------
 {xx~^~yy~^~zz~^~}
(1 row)

postgres=# select string_to_array('xx~^~yy~^~zz~^~', '~^~', '.*');
 string_to_array
-----------------
 {xx,yy,zz,""}
(1 row)

postgres=# select string_to_array(null, '~^~', '.*');
 string_to_array
-----------------

(1 row)

postgres=# select string_to_array(null, null, '.*');
 string_to_array
-----------------

(1 row)

postgres=# select string_to_array('xx~^~yy~^~zz~^~', null);
         string_to_array
---------------------------------
 {x,x,~,^,~,y,y,~,^,~,z,z,~,^,~}
(1 row)
```

### CODE REVIEW

**Comment by yaooqinn** [comment]
cc @cloud-fan @wangyum @dongjoon-hyun @MaxGekk

**Comment by gatorsmile** [comment]
Any other system besides postgreSQL support this? If not, this function might not be very useful to the Spark community too. Things like this increase the surface of the system, create more code to maintain.

**Comment by yaooqinn** [comment]
close this because it seems pg only

**Comment by HyukjinKwon** [comment]
@yaooqinn, thanks for cleaning up your PRs. Do you mind if I ask resolve the JIRA as `Won't Fix` status as well please? If you're unable to resolve a ticket, please cc me on the JIRAs.

**Comment by yaooqinn** [comment]
@HyukjinKwon OK. I will check. thanks.

**Pull request closed without merging**
