### PR TITLE
[SPARK-49536] Handle error in python streaming data source record prefetching

### PR DESCRIPTION
**Pull request by chaoqin-li1123**
### What changes were proposed in this pull request?
Currently there is an assert that return status code from the python worker is SpecialLengths.START_ARROW_STREAM when python source runner is prefetching records. To improve debugability, check the status code and rethrow an runtime error with detailed error message.

### Why are the changes needed?
To improve debugability

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Existing tests sufficient

### Was this patch authored or co-authored using generative AI tooling?
No

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
can we have a simple test?

**Comment by chaoqin-li1123** [comment]
I find it hard to reproduce this situation, because this happens in the partitions() call of simple data source, which is not calling user code, but the code of the wrapper we implemented for python streaming data source. So we can't throw an error from the data source code like we did for other place where python source error is thrown. Error thrown here would be system error. @HyukjinKwon

**Review by allisonwang-db — APPROVED** [review]

**Comment by chaoqin-li1123** [comment]
All CI have passed.

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
