### PR TITLE
[SPARK-39656][SQL] Fix wrong namespace in DescribeNamespaceExec

### PR DESCRIPTION
**Pull request by ulysses-you**
### What changes were proposed in this pull request?

DescribeNamespaceExec change ns.last to ns.quoted

### Why are the changes needed?

DescribeNamespaceExec should show the whole namespace rather than last

### Does this PR introduce _any_ user-facing change?

yes, a small bug fix

### How was this patch tested?

fix test

### CODE REVIEW

**Review by cloud-fan — APPROVED** [review]
LGTM. Which version starts to have this issue?

**Review by huaxingao — APPROVED** [review]

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Comment by cloud-fan** [comment]
@ulysses-you can you open backport PRs for 3.0 to 3.3? there are conflicts

**Comment by ulysses-you** [comment]
sure will send pr later

**Pull request closed without merging**
