### PR TITLE
[SPARK-35692][K8S] Use AtomicInteger for executor id generating

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

AtomicInteger is enough for executor ids, in this PR, we use it to replace AtomicLong like other cluster managers, e.g. yarn, standalone

### Why are the changes needed?

See the discussion here https://github.com/apache/spark/pull/32610#discussion_r648007320

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

pass CI with existing tests

### CODE REVIEW

**Comment by yaooqinn** [comment]
cc @dongjoon-hyun thanks very much

**Comment by dongjoon-hyun** [comment]
cc @holdenk , @attilapiros , @liyinan926

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @yaooqinn .
Merged to master for Apache Spark 3.2.0.

**Comment by yaooqinn** [comment]
thanks @dongjoon-hyun

**Pull request closed without merging**
