### PR TITLE
[SPARK-25592] Setting version to 3.0.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by gatorsmile**
## What changes were proposed in this pull request?

This patch is to bump the master branch version to 3.0.0-SNAPSHOT.

## How was this patch tested?
N/A

### CODE REVIEW

**Comment by gatorsmile** [comment]
cc @yhuai @rxin @cloud-fan @srowen @dongjoon-hyun

**Review by felixcheung — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
retest this please

**Review by cloud-fan — APPROVED** [review]

**Review by srowen — APPROVED** [review]
I'll move anything resolved for 2.5.0 to 3.0.0 in JIRA

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by gatorsmile** [comment]
Thanks! Merged to master.

**Comment by dongjoon-hyun** [comment]
Great, @gatorsmile ! Could you update Spark website properly, too?

**Comment by gatorsmile** [comment]
@dongjoon-hyun Could you help me fix the website?

**Comment by dongjoon-hyun** [comment]
It's about 3.0.0. So, I guess PMC knows the detail and the future. :)

**Comment by srowen** [comment]
You mean http://spark.apache.org/versioning-policy.html and the reference to 2.4? I think that's still valid. When 2.4 is released, I'd propose to change that to refer to 3.0 being released .. I dunno .. around Mar 2019?

**Comment by gatorsmile** [comment]
Yes. Let us wait for the release of 2.4

**Comment by dongjoon-hyun** [comment]
Thanks, @srowen and @gatorsmile . That sounds good to me.

**Pull request closed without merging**
