### PR TITLE
[SPARK-9918] [MLLIB] remove runs from k-means and rename epsilon to tol

### PR DESCRIPTION
**Pull request by mengxr**
This requires some discussion. I'm not sure whether `runs` is a useful parameter. It certainly complicates the implementation. We might want to optimize the k-means implementation with block matrix operations. In this case, having `runs` may not be worth the trade-off. Also it increases the communication cost in a single job, which might cause other issues.

This PR also renames `epsilon` to `tol` to have consistent naming among algorithms. The Python constructor is updated to include all parameters.

@jkbradley @yu-iskw

### CODE REVIEW

**Comment by jkbradley** [comment]
LGTM, except that the Scala doc for class KMeans needs to be updated.

**Comment by jkbradley** [comment]
Er, and the test suite.

**Comment by jkbradley** [comment]
LGTM pending tests.  Thanks for catching the typos!

**Comment by yu-iskw** [comment]
LTGM

**Comment by mengxr** [comment]
Found more issues. See the updated description.

**Comment by mengxr** [comment]
test this please

**Comment by mengxr** [comment]
test this please

**Comment by jkbradley** [comment]
Thanks for catching all of these issues!

**Comment by mengxr** [comment]
Merged into master and branch-1.5.

**Pull request closed without merging**
