### PR TITLE
[SPARK-45596][CONNECT] Use java.lang.ref.Cleaner instead of org.apache.spark.sql.connect.client.util.Cleaner

### PR DESCRIPTION
**Pull request by zhaomin1423**
### What changes were proposed in this pull request?

Use java.lang.ref.Cleaner instead of org.apache.spark.sql.connect.client.util.Cleaner

### Why are the changes needed?

org.apache.spark.sql.connect.client.util.Cleaner is a temporary class, waiting for the upgrade of jdk to 9 or above.
https://issues.apache.org/jira/browse/SPARK-45596
### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

pass ci

### Was this patch authored or co-authored using generative AI tooling?

No

### CODE REVIEW

**Comment by zhaomin1423** [comment]
Could you help me review it? @zhli1142015 @hvanhovell , also cc @LuciferYang @mridulm

**Comment by LuciferYang** [comment]
also cc @zhenlineo

**Review by zhenlineo — APPROVED** [review]
The change looks good, can I also ask if you could add a test for it, e.g. following [this test example](https://github.com/netty/netty/blob/main/buffer/src/test/java/io/netty5/buffer/tests/BufferCleanerTest.java#L55)?

**Comment by zhaomin1423** [comment]
> The change looks good, can I also ask if you could add a test for it, e.g. following [this test example](https://github.com/netty/netty/blob/main/buffer/src/test/java/io/netty5/buffer/tests/BufferCleanerTest.java#L55)?

Sorry, This example compares memory usage because of the allocated off-heap memory, it seems difficult for us to compare memory usage.

**Comment by zhenlineo** [comment]
@zhaomin1423 Yeah, the trick is to trigger a GC consistently. I was wondering if we can create some garbage memory to produce a GC. If it is too hard, we can go without a test for now. cc @hvanhovell

**Comment by LuciferYang** [comment]
A bit busy today, I'll check this PR later.

**Review by beliefer — COMMENTED** [review]
LGTM except @zhenlineo 's comment.

**Comment by zhaomin1423** [comment]
> @zhaomin1423 Yeah, the trick is to trigger a GC consistently. I was wondering if we can create some garbage memory to produce a GC. If it is too hard, we can go without a test for now. cc @hvanhovell

What I am confused about is, how should we check the effect after gc is triggered

**Review by LuciferYang — APPROVED** [review]
+1, LGTM

**Comment by LuciferYang** [comment]
> What I am confused about is, how should we check the effect after gc is triggered

Construct a case where `SparkResult` won't be manually closed, and check if after registering `cleanable`, `Cleaner.impl.phantomCleanableList` is not empty, but eventually `phantomCleanableList` is empty?  This may require adding some code to get `phantomCleanableList` through reflection, just a suggestion, not sure if it's really feasible.

**Comment by LuciferYang** [comment]
@zhaomin1423 If adding new tests is indeed difficult, do you have a manual way to confirm it is effective?

**Comment by zhaomin1423** [comment]
> > What I am confused about is, how should we check the effect after gc is triggered
> 
> Construct a case where `SparkResult` won't be manually closed, and check if after registering `cleanable`, `Cleaner.impl.phantomCleanableList` is not empty, but eventually `phantomCleanableList` is empty? This may require adding some code to get `phantomCleanableList` through reflection, just a suggestion, not sure if it's really feasible.

Thanks, I will try it and if it doesn't work. I will verify manually by adding logs.

**Comment by zhaomin1423** [comment]
> > > What I am confused about is, how should we check the effect after gc is triggered
> > 
> > 
> > Construct a case where `SparkResult` won't be manually closed, and check if after registering `cleanable`, `Cleaner.impl.phantomCleanableList` is not empty, but eventually `phantomCleanableList` is empty? This may require adding some code to get `phantomCleanableList` through reflection, just a suggestion, not sure if it's really feasible.
> 
> Thanks, I will try it and if it doesn't work. I will verify manually by adding logs.

I did a manual test, there are two steps.
1. org.apache.spark.sql.connect.client.SparkResultCloseable#close add ```println("The resource of spark result closed.")```
```
  override def close(): Unit = {
    resultMap.values.foreach(_._2.foreach(_.close()))
    responses.close()
    // scalastyle:off println
    println("The resource of spark result closed.")
  }
```
2. start connect server and use example below to test. if ```The resource of spark result closed.``` can print to console, it can work well.
```
object ConnectClientTest {

  def main(args: Array[String]): Unit = {
    val spark = SparkSession.builder
      .remote("sc://localhost:15002")
      .getOrCreate()
    var sparkResult = spark.range(0, 10, 1, 10)
      .collectResult()
    // scalastyle:off println
    sparkResult = null
    for (_ <- 0 until 10) {
      System.gc()
      Thread.sleep(100L)
    }
    spark.stop()
  }
}
```
Test result: 
```The resource of spark result closed.``` can print to console, so the org.apache.spark.sql.connect.client.SparkResultCloseable work well.

**Comment by LuciferYang** [comment]
> > > > What I am confused about is, how should we check the effect after gc is triggered
> > > 
> > > 
> > > Construct a case where `SparkResult` won't be manually closed, and check if after registering `cleanable`, `Cleaner.impl.phantomCleanableList` is not empty, but eventually `phantomCleanableList` is empty? This may require adding some code to get `phantomCleanableList` through reflection, just a suggestion, not sure if it's really feasible.
> > 
> > 
> > Thanks, I will try it and if it doesn't work. I will verify manually by adding logs.
> 
> I did a manual test, there are two steps.
> 
> 1. org.apache.spark.sql.connect.client.SparkResultCloseable#close add `println("The resource of spark result closed.")`
> 
> ```
>   override def close(): Unit = {
>     resultMap.values.foreach(_._2.foreach(_.close()))
>     responses.close()
>     // scalastyle:off println
>     println("The resource of spark result closed.")
>   }
> ```
> 
> 2. start connect server and use example below to test. if `The resource of spark result closed.` can print to console, it can work well.
> 
> ```
> object ConnectClientTest {
> 
>   def main(args: Array[String]): Unit = {
>     val spark = SparkSession.builder
>       .remote("sc://localhost:15002")
>       .getOrCreate()
>     var sparkResult = spark.range(0, 10, 1, 10)
>       .collectResult()
>     // scalastyle:off println
>     sparkResult = null
>     for (_ <- 0 until 10) {
>       System.gc()
>       Thread.sleep(100L)
>     }
>     spark.stop()
>   }
> }
> ```
> 
> Test result: `The resource of spark result closed.` can print to console, so the org.apache.spark.sql.connect.client.SparkResultCloseable work well.


Seems just a test issue, we can try to add `--add-opens=java.base/java.lang.ref=ALL-UNNAMED` to `extraJavaTestArgs` and `JavaModuleOptions`.

**Review by hvanhovell — APPROVED** [review]
LGTM

**Comment by hvanhovell** [comment]
If you want to test this, then you have to force GC. Guava had some tricks for this: https://www.javadoc.io/doc/com.google.guava/guava-testlib/12.0/com/google/common/testing/GcFinalization.html

**Comment by hvanhovell** [comment]
BTW I am fine to merge this without a new test.

**Review by beliefer — APPROVED** [review]
LGTM if we allow not add new test.

**Comment by LuciferYang** [comment]
Merged into master for Spark 4.0.
Thanks for your contribution. @zhaomin1423 
Thanks for your review. @hvanhovell @beliefer @zhenlineo

**Comment by zhaomin1423** [comment]
Thank you all.

**Pull request closed without merging**
