### PR TITLE
[SPARK-41354][CONNECT][PYTHON] Implement RepartitionByExpression

### PR DESCRIPTION
**Pull request by dengziming**
### What changes were proposed in this pull request?
Implement DataFrame.repartition and RepartitionByExpressio for pyspark

### Why are the changes needed?
For API coverage

### Does this PR introduce _any_ user-facing change?
Add new APIs for python client

### How was this patch tested?
python test cases.

### CODE REVIEW

**Comment by itholic** [comment]
nit:
> Implement DataFrame.hint for pyspark

Maybe `DataFrame.repartition` or `RepartitionByExpression` instead of `DataFrame.hint` ?

**Comment by zhengruifeng** [comment]
just to confirm, the proto `RepartitionByExpression repartition_by_expression = 27` can support both 

`def repartition(self, *cols: "ColumnOrName")`
`def repartitionByRange(self, *cols: "ColumnOrName")`

right? @dengziming

**Comment by dengziming** [comment]
> just to confirm, the proto `RepartitionByExpression repartition_by_expression = 27` can support both
> 
> `def repartition(self, *cols: "ColumnOrName")` `def repartitionByRange(self, *cols: "ColumnOrName")`

Yes, you are right @zhengruifeng . Both `repartition(cols)` and `repartitionByRange(cols)` will be transformed to `RepartitionByExpression`, this can be seen in `Dataset.scala`

**Review by zhengruifeng — APPROVED** [review]

**Comment by zhengruifeng** [comment]
@dengziming would you mind resolving the conflicts? thanks

**Comment by dengziming** [comment]
> @dengziming would you mind resolving the conflicts? thanks

Done!

**Comment by zhengruifeng** [comment]
merged into master, thank you @dengziming for working on this!

**Pull request closed without merging**
