### PR TITLE
[MINOR][BUILD] Add 2 maven properties(hive.classifier and hive.parquet.group)

### PR DESCRIPTION
**Pull request by wangyum**
## What changes were proposed in this pull request?

This pr adds 2 maven properties to help us upgrade the built-in Hive.

| Property Name | Default | In future |
| ------ | ------ | ------ |
| hive.classifier | (none) | core |
| hive.parquet.group | com.twitter | org.apache.parquet |

## How was this patch tested?

existing tests

### CODE REVIEW

**Comment by wangyum** [comment]
cc @srowen In order to make the upgrade built-in Hive change smaller, I'd like to change this first.

**Comment by srowen** [comment]
I see, this is so we can try Hive 2/3? OK.

**Comment by wangyum** [comment]
> cc @srowen In order to make the upgrade built-in Hive change smaller, I'd like to change this first.

Yes. I have tried it: https://github.com/wangyum/spark/tree/hadoop-3.2
and all test passed.

**Comment by wangyum** [comment]
@srowen Could we merge this to the master?

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
