### PR TITLE
[SPARK-20422][Spark Core] Worker registration retries should be configurable

### PR DESCRIPTION
**Pull request by unsleepy22**
## What changes were proposed in this pull request?
make prolonged registration retries configurable

## How was this patch tested?
unit tests, integration tests

### CODE REVIEW

**Comment by unsleepy22** [comment]
Could someone take a look?

**Review by navneetrastogi — APPROVED** [review]
This looks ok to me

**Comment by navneetrastogi** [comment]
This is a minor change which will help in configuring registration retries. It can be merged.

**Comment by jiangxb1987** [comment]
Could you expand more on the senerio you are changing this? Thank you!

**Comment by gatorsmile** [comment]
We are closing it due to inactivity. please do reopen if you want to push it forward. Thanks!

**Pull request closed without merging**
