### PR TITLE
[SPARK-15837][ML][PySpark]Word2vec python add maxsentence parameter

### PR DESCRIPTION
**Pull request by WeichenXu123**
## What changes were proposed in this pull request?

Word2vec python add maxsentence parameter.
## How was this patch tested?

Existing test.

### CODE REVIEW

**Comment by srowen** [comment]
Seems OK

**Comment by WeichenXu123** [comment]
@srowen Hi srowen, I have another similar PR #13558  which past test on my machine, but the official test fail. It seems to be the test server's problem, can you help to check it ?

**Comment by MLnick** [comment]
LGTM

**Comment by srowen** [comment]
Merged to master/2.0

**Pull request closed without merging**
