### PR TITLE
[MINOR][ML] Use Datasets (to improve internal implementation)

### PR DESCRIPTION
**Pull request by jaceklaskowski**
## What changes were proposed in this pull request?

Change the current implementation to use Datasets (not the "old-school" `map` over `Row`s)

NOTE: I'm sending the pull request to discuss whether my understanding of the change is correct or not and if approved (after discussions and further changes possibly) learn the right way.
## How was this patch tested?

Local build

### CODE REVIEW

**Comment by mengxr** [comment]
@jaceklaskowski This is a correct change. But please create a JIRA for it. I guess there are many other places in MLlib where we can use the new `Dataset.as` API, which make the changes no longer minor.

**Comment by mengxr** [comment]
@jaceklaskowski Do you have time to check other locations?

**Comment by jaceklaskowski** [comment]
Sorry, no. Got distracted and had no time for it. Let me work on it later today (it's 00:21 already).

**Comment by zhengruifeng** [comment]
@jaceklaskowski  It seems that you dont have enough time to work on this.  Would you mind if I create a JIRA for this issue and take it over?

**Comment by zhengruifeng** [comment]
Jenkins, test this please

**Comment by rxin** [comment]
@jaceklaskowski can you close this and reopen when you think it is ready?

**Pull request closed without merging**
