### PR TITLE
[MINOR] Add git ignores for vscode and metals

### PR DESCRIPTION
**Pull request by Kimahriman**
### What changes were proposed in this pull request?

Add new git ignore entries for a Visual Studio Code with Metals Scala plugin setup.

### Why are the changes needed?

To not have to constantly stash and pop my gitignore changes when changing branches.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

It ignores all the VSCode/Metals files I have locally.

### CODE REVIEW

**Review by srowen — APPROVED** [review]

**Review by dongjoon-hyun — COMMENTED** [review]
Are you interested in documenting `Visual Studio Code` IDE Setup for Apache Spark, @Kimahriman ?

**Comment by Kimahriman** [comment]
I could try, but I mostly use it because I'm _not_ a java developer and use VSCode for all my Python/TypeScript/everything else I do. It's mostly just the Scala Metals plugin and that's it. And it can be kinda flaky sometimes

**Comment by dongjoon-hyun** [comment]
Never mind, @Kimahriman ~

**Comment by bjornjorgensen** [comment]
From the [Scala (Metals docks)](https://open-vsx.org/extension/scalameta/metals#files-and-directories-to-include-in-your-gitignore) you need to add `.ammonite/`

**Comment by Kimahriman** [comment]
Didn't know about ammonite because I use bloop, added that as well

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
