### PR TITLE
[SPARK-46529][TESTS] Upgrade guava from 18.0 to 19.0 for `docker-integration-tests`

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

This PR upgrades guava from 18.0 to 19.0 for docker-integration-tests as preparation for https://github.com/apache/spark/pull/44509 

### Why are the changes needed?

requested by @dongjoon-hyun as a separated PR at https://github.com/apache/spark/pull/44509/files#r1437220177

### Does this PR introduce _any_ user-facing change?

no
### How was this patch tested?

existing docker it
### Was this patch authored or co-authored using generative AI tooling?

no

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by dongjoon-hyun** [comment]
Pending CIs.

**Comment by yaooqinn** [comment]
Thank you very much. @dongjoon-hyun

**Comment by yaooqinn** [comment]
Thank you again. @dongjoon-hyun

Merged to master

**Pull request closed without merging**
