### PR TITLE
[SPARK-35951][DOCS] Add since versions for Avro options in Documentation

### PR DESCRIPTION
**Pull request by gengliangwang**
### What changes were proposed in this pull request?

There are two new Avro options `datetimeRebaseMode` and `positionalFieldMatching` after Spark 3.2.
We should document the since version so that users can know whether the option works in their Spark version.

### Why are the changes needed?

Better documentation.

### Does this PR introduce _any_ user-facing change?

No
### How was this patch tested?

Manual preview on local setup.
Screen Shot 2021-06-30 at 5 05 54 PM

Screen Shot 2021-06-30 at 5 06 34 PM

### CODE REVIEW

**Comment by MaxGekk** [comment]
> Manual preview on local setup.

Can you put a screenshot in PR's description. Otherwise LGTM.

**Review by MaxGekk — APPROVED** [review]

**Comment by gengliangwang** [comment]
@MaxGekk Screenshot uploaded, thanks

**Comment by gengliangwang** [comment]
Merging to master

**Comment by HyukjinKwon** [comment]
lgtm2

**Comment by xkrogen** [comment]
Great idea, thx @gengliangwang !

**Pull request closed without merging**
