### PR TITLE
[SPARK-17001] [ML] Enable standardScaler to standardize sparse vectors when withMean=True

### PR DESCRIPTION
**Pull request by srowen**
## What changes were proposed in this pull request?

Allow centering / mean scaling of sparse vectors in StandardScaler, if requested. This is for compatibility with `VectorAssembler` in common usages.
## How was this patch tested?

Jenkins tests, including new caes to reflect the new behavior.

### CODE REVIEW

**Comment by srowen** [comment]
Another one where I'd welcome comments from ... @holdenk @MLnick @davies et al

**Comment by srowen** [comment]
going once, going twice. This would simply let an operation proceed where it errored before, at the cost of giving a user a little more rope to hang him/herself. I think it unblocks a legitimate and common set of use cases, so I think it's worth changing.

**Comment by MLnick** [comment]
As mentioned on the JIRA discussion, I'm neutral on this, though I tend to lean towards allowing the user to do what they want even if it might be "dangerous". I guess +0?

Though perhaps we may want to explicitly log a `WARN` message if sparse input is encountered and `withMean=true`, just so there is a very clear root cause message in the logs if things blow up with OOM (it's in the user guide and doc string, but still may be missed by many users).

**Comment by srowen** [comment]
Warning seems reasonable. I think you'd have to put in a flag to remember if the user has been warned in order to avoid spewing millions of them. Worth it, you think?

**Comment by MLnick** [comment]
Ah right, good point. Actually I realised that the doc in `ml.feature.StandardScaler` needs updating for `withMean`:

```
  /**
   * Whether to center the data with mean before scaling.
   * It will build a dense output, so this does not work on sparse input
   * and will raise an exception.
   * Default: false
   * @group param
   */
  val withMean: BooleanParam = new BooleanParam(this, "withMean",
    "Whether to center data with mean")
```

... as good a place as any to add a warning about using with sparse input (this can then show up in `explainParam` doc as well as ScalaDoc. Python side will probably need it too.

**Comment by srowen** [comment]
If I understood you correctly @MLnick you favored just adding warnings in the doc? I added to three more places that needed it.

**Comment by srowen** [comment]
I'll go for this tomorrow if there are no other comments.

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
