### PR TITLE
[SPARK-18693][ML][MLLIB] ML Evaluators should use weight column

### PR DESCRIPTION
**Pull request by imatiach-msft**
## What changes were proposed in this pull request?

The evaluators BinaryClassificationEvaluator, RegressionEvaluator, and MulticlassClassificationEvaluator and the corresponding metrics classes BinaryClassificationMetrics, RegressionMetrics and MulticlassMetrics should use sample weight data.
The updates to the regression metrics were based on (and updated with new changes based on comments):
https://issues.apache.org/jira/browse/SPARK-11520
("RegressionMetrics should support instance weights")
but the pull request was closed as the changes were never checked in.

## How was this patch tested?

This is still a work in progress, I will be adding more tests soon.  I took the regression tests from:
https://github.com/apache/spark/pull/9907
Which was closed as a stale PR but I updated it with some changes.

### CODE REVIEW

**Comment by imatiach-msft** [comment]
it looks like a random test timed out:
org.apache.spark.scheduler.BasicSchedulerIntegrationSuite.job with fetch failure
Error Details 
java.util.concurrent.TimeoutException: Futures timed out after [1 second]
I will try to run again.

**Comment by imatiach-msft** [comment]
Jenkins retest this please

**Comment by imatiach-msft** [comment]
Jenkins, retest this please

**Comment by imatiach-msft** [comment]
Jenkins, retest this please

**Comment by imatiach-msft** [comment]
Jenkins, retest this please

**Comment by imatiach-msft** [comment]
Jenkins, retest this please

**Comment by imatiach-msft** [comment]
Jenkins doesn't seem to be working ...

**Comment by imatiach-msft** [comment]
@sethah @Lewuathe @thunterdb @WeichenXu123 @jkbradley would you be able to take a look at the changes to add a weight column to binary/multiclass/regression evaluators/metrics classes?  It looks like you are familiar with this code.  Thank you!

**Comment by imatiach-msft** [comment]
Jenkins, retest this please

**Comment by imatiach-msft** [comment]
Jenkins, retest this please

**Comment by imatiach-msft** [comment]
Jenkins, retest this please

**Comment by imatiach-msft** [comment]
Jenkins, retest this please

**Comment by imatiach-msft** [comment]
Jenkins, retest this please

**Comment by imatiach-msft** [comment]
Jenkins, retest this please

**Comment by imatiach-msft** [comment]
ping @sethah @Lewuathe @thunterdb @WeichenXu123 @jkbradley would you be able to take a look at the changes to add a weight column to binary/multiclass/regression evaluators/metrics classes? It looks like you are familiar with this code. Thank you!

**Comment by imatiach-msft** [comment]
ping @sethah @Lewuathe @thunterdb @WeichenXu123 @jkbradley would you be able to take a look at the changes to add a weight column to binary/multiclass/regression evaluators/metrics classes? It looks like you are familiar with this code. Thank you!

**Comment by imatiach-msft** [comment]
ping @sethah @Lewuathe @thunterdb @WeichenXu123 @jkbradley would you be able to take a look at the changes to add a weight column to binary/multiclass/regression evaluators/metrics classes? It looks like you are familiar with this code. Thank you!

**Comment by imatiach-msft** [comment]
@srowen @yanboliang might you be able to take a look at this PR?  Is it possibly too large and I should break it up into 3 PRs, one per evaluator/metrics class?

**Comment by srowen** [comment]
I wouldn't ping that frequently, please. I don't feel qualified to review this myself.

**Comment by sethah** [comment]
+1 for breaking it up, maybe starting with regression. Also, just because something hasn't been reviewed in two weeks does not mean that there is no interest in it. Two weeks is not all that long (I've seen valuable PRs sit for much longer than that) and it likely just means people are busy. As Sean pointed out, it's probably not necessary to ping once per day.

**Comment by thunterdb** [comment]
I agree, let's break this PR. It will go faster, and some changes may require longer discussions.

**Comment by imatiach-msft** [comment]
ok, I will close this and create three new PRs, one for each of the evaluators

**Comment by imatiach-msft** [comment]
I've created 3 PRs, located here:
https://github.com/apache/spark/pull/17084
https://github.com/apache/spark/pull/17085
https://github.com/apache/spark/pull/17086

**Pull request closed without merging**
