### PR TITLE
[MINOR] Simplify the usage of "!isDefined" to "isEmpty"

### PR DESCRIPTION
**Pull request by chong0929**
### What changes were proposed in this pull request?
Change "!attemptId.isDefined" to "attemptId.isEmpty".

### Why are the changes needed?
Appears more intuitive and easy to understand, the function "isDefined" is defined as follows:
```
/** Returns true if the option is an instance of $some, false otherwise.
   *
   * This is equivalent to:
   * {{{
   * option match {
   *   case Some(_) => true
   *   case None    => false
   * }
   * }}}
   */
  def isDefined: Boolean = !isEmpty
```

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Passed GA.

### CODE REVIEW

**Comment by zhengruifeng** [comment]
Can we find similar places, and change them in a batch?

**Review by dongjoon-hyun — COMMENTED** [review]
+1 for @zhengruifeng 's comment.

**Comment by chong0929** [comment]
Thanks for your attention, 18 similar places found as follows and has been submitted for revision.
```
1. core/src/test/scala/org/apache/spark/util/JsonProtocolSuite.scala:937:      assert(!opt2.isDefined)
2. core/src/test/scala/org/apache/spark/deploy/SparkSubmitSuite.scala:609:      assert(!sc2.progressBar.isDefined)
3. core/src/test/scala/org/apache/spark/rdd/LocalCheckpointSuite.scala:73:    assert(!filteredRdd.checkpointData.get.checkpointRDD.isDefined)
4. core/src/main/scala/org/apache/spark/metrics/sink/GraphiteSink.scala:45:  if (!propertyToOption(GRAPHITE_KEY_HOST).isDefined) {
5. core/src/main/scala/org/apache/spark/metrics/sink/GraphiteSink.scala:49:  if (!propertyToOption(GRAPHITE_KEY_PORT).isDefined) {   
6. core/src/main/scala/org/apache/spark/ui/jobs/StagePage.scala:362:                     if (!taskInfo.duration.isDefined) {
7. core/src/main/scala/org/apache/spark/scheduler/TaskSetManager.scala:1100:    if (isZombie || isBarrier || (numTasks == 1 && !speculationTaskDurationThresOpt.isDefined)) {
8. mllib/src/main/scala/org/apache/spark/ml/feature/Interaction.scala:162:          } else if (!attr.name.isDefined) {
9. external/kafka-0-10-sql/src/test/scala/org/apache/spark/sql/kafka010/KafkaMicroBatchSourceSuite.scala:188:      if (!q.exception.isDefined) {
10. external/kafka-0-10-sql/src/test/scala/org/apache/spark/sql/kafka010/KafkaMicroBatchSourceSuite.scala:1061:        if (!q.exception.isDefined) {
11. external/kafka-0-10-sql/src/test/scala/org/apache/spark/sql/kafka010/KafkaMicroBatchSourceSuite.scala:1184:        if (!q.exception.isDefined) {
12. external/kafka-0-10-sql/src/main/scala/org/apache/spark/sql/kafka010/consumer/KafkaDataConsumer.scala:557:    if (!_consumer.isDefined) {
13. external/spark-ganglia-lgpl/src/main/scala/org/apache/spark/metrics/sink/GangliaSink.scala:53:  if (!propertyToOption(GANGLIA_KEY_HOST).isDefined) { 
14. external/spark-ganglia-lgpl/src/main/scala/org/apache/spark/metrics/sink/GangliaSink.scala:57:  if (!propertyToOption(GANGLIA_KEY_PORT).isDefined) { 
15. sql/core/src/test/scala/org/apache/spark/sql/UDTRegistrationSuite.scala:87:    assert(!UDTRegistration.getUDTFor(classOf[TestUserClass3].getName).isDefined)
16. sql/core/src/test/scala/org/apache/spark/sql/execution/benchmark/AggregateBenchmark.scala:573:            if (!loc.isDefined) {
17. sql/core/src/test/scala/org/apache/spark/sql/execution/streaming/sources/RatePerMicroBatchProviderSuite.scala:131:      if (!q.exception.isDefined) {
18. sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/codegen/javaCode.scala:179:      if (!newE.isDefined || newE.get.equals(e)) {  
19. sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/rules/RuleIdCollection.scala:206:    if (!ruleIdOpt.isDefined) {   
```

**Comment by zhengruifeng** [comment]
ok to test

**Comment by zhengruifeng** [comment]
Jenkins, retest this please

**Comment by AngersZhuuuu** [comment]
Should we create a jira ticket and use the ticket id as pr title? like `[SPARK-xxx][module]  Simplify the usage of "!isDefined" to "isEmpty"`

**Pull request closed without merging**
