### PR TITLE
[SPARK-16703][SQL] Remove extra whitespace in SQL generation for window functions

### PR DESCRIPTION
**Pull request by liancheng**
## What changes were proposed in this pull request?

This PR fixes a minor formatting issue of `WindowSpecDefinition.sql` when no partitioning expressions are present.

Before:

``` sql
( ORDER BY `a` ASC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)
```

After:

``` sql
(ORDER BY `a` ASC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)
```
## How was this patch tested?

New test case added in `ExpressionSQLBuilderSuite`.

### CODE REVIEW

**Comment by rxin** [comment]
Can you add a JIRA ticket?

**Comment by dongjoon-hyun** [comment]
Hi, @liancheng .
The failure is due to `LogicalPlanToSQLSuite`. It verifies the generated SQLs. Please use the following command to update the generated SQL answer sets.
```bash
SPARK_GENERATE_GOLDEN_FILES=1 build/sbt "hive/test-only *LogicalPlanToSQLSuite"
```

**Comment by liancheng** [comment]
@rxin @dongjoon-hyun Thanks! JIRA ticket added and updated the golden files.

**Comment by rxin** [comment]
BTW can you change the title to say "Remove extra whitespace in SQL generation for window functions"?

**Comment by hvanhovell** [comment]
LGTM

**Comment by dongjoon-hyun** [comment]
After merging this PR, I will rebase my PR https://github.com/apache/spark/pull/14257 .
Both PRs are related to SQL generations.

**Comment by liancheng** [comment]
@rxin PR title updated.

**Comment by rxin** [comment]
Merging in master/2.0.

**Pull request closed without merging**
