### PR TITLE
Revert "[SPARK-29393][SQL] Add `make_interval` function"

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

This reverts commit 18440151b0bf2d79356393f515b149439e17962e.

### Why are the changes needed?

make_interval is a PostgreSQL specific,  revert it to reduce the maintenance cost.

### Does this PR introduce any user-facing change?

no

### How was this patch tested?

existing tests

### CODE REVIEW

**Comment by yaooqinn** [comment]
cc: @cloud-fan, @gatorsmile  thanks for reviewing this

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
@yaooqinn . 
1.  I don't see any comment on the original PR. Which comment are you referring?
2. What kind of maintenance cost do you consider specifically here? This is just a utility function for convenience.

**Comment by dongjoon-hyun** [comment]
Also, you should ping the original author and committer, too.
This PR looks like an attempt to revert silently. That's not a good.

Anyway, ping @MaxGekk , too.

**Comment by dongjoon-hyun** [comment]
Let's discuss on the original PR first, @yaooqinn .

**Comment by yaooqinn** [comment]
Thanks @dongjoon-hyun

**Comment by MaxGekk** [comment]
I cannot agree with reverting this type constructor. @yaooqinn Please, see the first item which explain the reason of adding it: https://github.com/apache/spark/pull/26446. If you revert it, how would you construct `INTERVAL` column from other interval sub-component columns?

**Comment by HeartSaVioR** [comment]
IMHO, we may want to keep in mind that revert is a "destructive" action rolling back non-trivial efforts from various people. If it really needs to be rolled back, the discussion should be initiated in prior, with proper explanation of rationalization commonly making sense. Reverting without building consensus would make someone feel disregarded.

**Comment by yaooqinn** [comment]
Sorry for my rudeness and thoughtlessness. I didn't mean to heart somebody.

**Pull request closed without merging**
