### PR TITLE
[SPARK-42251][SQL] Forbid deicmal type if precision less than 1

### PR DESCRIPTION
**Pull request by ulysses-you**
### What changes were proposed in this pull request?

throw exception if the decimal precision less than 1.

### Why are the changes needed?

Spark does not actually support decimal type with 0 precision. e.g.

```
– work with in-memory catalog
create table t (c decimal(0, 0)) using parquet;

-- fail with parquet
-- java.lang.IllegalArgumentException: Invalid DECIMAL precision: 0
-- at org.apache.parquet.Preconditions.checkArgument(Preconditions.java:57)
insert into table t values(0);

-- fail with hive catalog
-- Caused by: java.lang.IllegalArgumentException: Decimal precision out of allowed range [1,38]
-- at org.apache.hadoop.hive.serde2.typeinfo.HiveDecimalUtils.validateParameter(HiveDecimalUtils.java:44)
create table t (c decimal(0, 0)) using parquet;
```
### Does this PR introduce _any_ user-facing change?

yes, one main behavior change is: `SELECT cast(0 as decimal(0, 0))`

- before: return 0
- after: throw exception

### How was this patch tested?

add test

### CODE REVIEW

**Comment by ulysses-you** [comment]
I'm not sure this worth a leagcy config. cc @cloud-fan @viirya @gengliangwang

**Comment by cloud-fan** [comment]
how does `cast(0 as decimal(0, 0))` work?

**Comment by cloud-fan** [comment]
Another place to check is user-specified schema when reading data sources, e.g. `spark.read.schema("c1: decimal(0, 0)").json(...)`

**Comment by ulysses-you** [comment]
> how does cast(0 as decimal(0, 0)) work?

It's wrapped in Decimal first which internally use longVal to represent the decimal value so it won't fail. The changePrecision method only fail with decimal(0, 0) if it uses decimalVal(BigDecimal).

> Another place to check is user-specified schema when reading data source

This case should be covered. It's similar with `create table ...` ddl. I added a new test for it.

**Pull request closed without merging**
