### PR TITLE
[SPARK-23387][SQL][PYTHON][TEST][BRANCH-2.3] Backport assertPandasEqual to branch-2.3.

### PR DESCRIPTION
**Pull request by ueshin**
## What changes were proposed in this pull request?

When backporting a pr with tests using `assertPandasEqual` from master to branch-2.3, the tests fail because `assertPandasEqual` doesn't exist in branch-2.3.
We should backport `assertPandasEqual` to branch-2.3 to avoid the failures.

## How was this patch tested?

Modified tests.

### CODE REVIEW

**Comment by ueshin** [comment]
cc @HyukjinKwon @icexelloss @BryanCutler

**Review by HyukjinKwon — APPROVED** [review]
LGTM

**Comment by HyukjinKwon** [comment]
Merged to branch-2.3.

Thanks @ueshin!

**Comment by ueshin** [comment]
Thanks!

**Pull request closed without merging**
