### PR TITLE
[SPARK-13858] [SQL] fix the data type cast issue

### PR DESCRIPTION
**Pull request by bomeng**
## What changes were proposed in this pull request?

I believe this is a critical bug in the Spark related to cast, which is found by running the TPC tests.
Use case:
User table (T) has one column (COL) which is FLOAT data type, it has tuple as (1.49f). the query is:

```
select COL from T where COL = 1.49, or
select COL from T where COL between 0 and 1.49
```

Spark will return nothing. Here is the reason in Scala (try to use Scala shell to test):

```
val a = 1.49f  #a: Float = 1.49
val b = 1.49  #b: Double = 1.49
val c = a == b #c: Boolean = false
val d = a <= b #d: Boolean = false
```

From above, we can see that casting a FLOAT to DOUBLE will not guarantee the comparison is still correct. There are many use cases that user will use =, <=, between in the queries, so it will affect the accuracy quite a lot.

The solution is to use FLOAT type if the column type is FLOAT and value is within the FLOAT range, else we will still use DOUBLE.

1.49 is the number I found with this cast issue, there may be more.
## How was this patch tested?

I did a full test for SQL, updated the expected results for a test suite, and also add a new test case for this scenario.

All tests are passed for now.

### CODE REVIEW

**Comment by jodersky** [comment]
> 1.49 is the number I found with this cast issue, there may be more.
This is a fundamentally related to binary representation, lots of decimal numbers are not representable in binary and comparing them must be done carefully.

I think trying to shield the user from these subtleties by converting floating points to decimals is not the appropriate answer and can lead to subtle errors as conversion is hidden from the user.

**Comment by bomeng** [comment]
Let me figure out the unit tests failures.

**Comment by rxin** [comment]
Yea it seems like comparing floating point numbers are difficult to compare, and if users want to do those, they should use decimal in the schema.

**Comment by bomeng** [comment]
The new approach is similar to the current solution (CAST the value to DOUBLE) but with a little more to deal with the FLOAT. If the comparison is between a FLOAT type and the value within FLOAT range, we will do the cast it to FLOAT, otherwise, we still cast them to DOUBLE. Any suggestions are welcome.

**Pull request closed without merging**
