### PR TITLE
[SPARK-36566][K8S] Add Spark appname as a label to pods

### PR DESCRIPTION
**Pull request by Yikun**
### What changes were proposed in this pull request?
Add Spark appname as a label to pods.

Note that:
- there were a `SPARK_APP_ID_LABEL`: is the unique spark APP applicationId with spark prefix (like "spark-{applicationId}")
- `SPARK_APP_NAME_LABEL` in this patch is the Spark APP name, it's more friendly and readable for k8s cluster maintainer to figure out the spark app name of specific pods. 

### Why are the changes needed?
Then we can find out all pods (driver/executor) list by using: `k get pods -l spark.app.name=xxx`, also can figure out the spark app name of specific pods.

### Does this PR introduce _any_ user-facing change?
Add label to pods.

### How was this patch tested?
Add UT

### CODE REVIEW

**Comment by Yikun** [comment]
cc who marked [SPARK-36566](https://issues.apache.org/jira/browse/SPARK-36566): @holdenk @HyukjinKwon

**Comment by dongjoon-hyun** [comment]
Thank you, @Yikun .

**Review by dongjoon-hyun — COMMENTED** [review]
We had better make the PR and commit log independent as much as possible. Could you elaborate a little more about the difference between `spark-app-selector` and `spark-app-name`? It will become a helpful commit log for the other community members.

**Comment by Yikun** [comment]
> Could you elaborate a little more about the difference between spark-app-selector and spark-app-name?

Sure, done!

**Comment by Yikun** [comment]
Need to address invalid label name...

**Comment by Yikun** [comment]
Label length limit: contain at most 63 characters, pod name limit: contain at most 253 characters

**Comment by Yikun** [comment]
@dongjoon-hyun Looks like failure is unrelated, could you take a look again? Thanks!

**Comment by dongjoon-hyun** [comment]
Sure, thank you for updating, @Yikun .

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @Yikun .
Merged to master for Apache Spark 3.3.

**Pull request closed without merging**
