### PR TITLE
[MINOR] Bump R version to 2.2.0.

### PR DESCRIPTION
**Pull request by yanboliang**
## What changes were proposed in this pull request?
#16126 bumps master branch version to 2.2.0-SNAPSHOT, but it seems R version was omitted. 

## How was this patch tested?
N/A

### CODE REVIEW

**Comment by yanboliang** [comment]
cc @felixcheung @shivaram

**Review by srowen — APPROVED** [review]

**Comment by felixcheung** [comment]
That's odd - this should be done automatically with release-tag script - I guess that is generally when cutting a RC build though?

**Comment by rxin** [comment]
I believe this is done automatically as part of the release scripts, so we don't need to do anything here.

**Comment by shivaram** [comment]
Yeah I think it does get automatically updated during the release but its good to keep this in sync this just for the development builds etc.

**Comment by srowen** [comment]
Agree, seems like, in any event, it ought to be bumped when we bump -SNAPSHOT versions in a branch, so wouldn't hurt to update this.

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
