### PR TITLE
[SPARK-28728][BUILD] Bump Jackson Databind to 2.9.9.3

### PR DESCRIPTION
**Pull request by Fokko**
## What changes were proposed in this pull request?

Update Jackson databind to the latest version for some latest changes.

## How was this patch tested?

Pass the Jenkins.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
@Fokko, shall we file a JIRA?

**Comment by Fokko** [comment]
@HyukjinKwon My mistake, I've already created a Jira, but I didn't add it to the title.

**Comment by dongjoon-hyun** [comment]
@Fokko . I cannot find the reason why we do this here. Could you explain the reason in the PR description or JIRA, please?

**Comment by dongjoon-hyun** [comment]
ok to test

**Comment by dongjoon-hyun** [comment]
cc @srowen

**Comment by dongjoon-hyun** [comment]
Since this is a dependency change, could you run the following, @Fokko ?
```
dev/test-dependencies.sh --replace-manifest
```

**Comment by srowen** [comment]
So there aren't 2.9.9.3 versions of the rest of Jackson? that's fine, I know sometimes databind has done out-of-band sub-maintenance releases. Looks OK modulo updating the deps files.

**Comment by dongjoon-hyun** [comment]
Thank you, @srowen .

@Fokko . I made a PR to you. Could you review and merge it, please?
- https://github.com/Fokko/spark/pull/17

**Comment by Fokko** [comment]
Sorry for the late reply, I'm in a different timezone. I've `git cherry-pick -x`'d your commit onto the branch.

**Review by srowen — APPROVED** [review]
OK pending tests

**Comment by srowen** [comment]
Hm.. that failure looks unrelated, but I don't see it in master, and I see it failed twice the same way. I don't see any significant change in 2.9.9.3 though that seems at all relevant. It's a very small update.

@wangyum I know this was added in the last week or so. Does this test failure make any sense to you? `SparkThriftServerProtocolVersionsSuite.HIVE_CLI_SERVICE_PROTOCOL_V1 get binary type` et al

**Comment by wangyum** [comment]
image

**Comment by wangyum** [comment]
retest this please

**Comment by dongjoon-hyun** [comment]
Ya. Our Jenkins environment didn't come back after the scheduled maintenance.

**Comment by maropu** [comment]
retest this please

**Comment by wangyum** [comment]
retest this please

**Comment by wangyum** [comment]
LGTM

I also can't reproduce `SparkThriftServerProtocolVersionsSuite.HIVE_CLI_SERVICE_PROTOCOL_V1 get binary type` on my local machine.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Merged to master.

Thank you, @Fokko , @HyukjinKwon , @srowen , @maropu , @wangyum .

**Review by HyukjinKwon — APPROVED** [review]

**Comment by Fokko** [comment]
My pleasure

**Pull request closed without merging**
