### PR TITLE
[MINOR][SQL] Improve readability for window execution

### PR DESCRIPTION
**Pull request by beliefer**
### What changes were proposed in this pull request?
I read the comments of `WindowExec` and found some comment will cause confusion and another need to improve.

### Why are the changes needed?
This PR will enhance the readability and let developer works more easy

### Does this PR introduce any user-facing change?
No

### How was this patch tested?
No need

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @hvanhovell

**Comment by cloud-fan** [comment]
cc @maryannxue

**Review by hvanhovell — APPROVED** [review]
LGTM

**Comment by beliefer** [comment]
@HyukjinKwon Could you take a look again?

**Comment by cloud-fan** [comment]
thanks, merging to master/3.0!

**Comment by beliefer** [comment]
@cloud-fan @hvanhovell @HyukjinKwon @dongjoon-hyun  Thanks for all your help.

**Pull request closed without merging**
