### PR TITLE
[SPARK-31952][SQL] Fix incorrect memory spill metric when doing Aggregate

### PR DESCRIPTION
**Pull request by Ngone51**
### What changes were proposed in this pull request?

This PR takes over https://github.com/apache/spark/pull/28780.

1. Counted the spilled memory size when creating the `UnsafeExternalSorter` with the existing `InMemorySorter`

2. Accumulate the `totalSpillBytes` when merging two `UnsafeExternalSorter`

### Why are the changes needed?

As mentioned in https://github.com/apache/spark/pull/28780:

> It happends when hash aggregate downgrades to sort based aggregate.
`UnsafeExternalSorter.createWithExistingInMemorySorter` calls spill on an `InMemorySorter` immediately, but the memory pointed by `InMemorySorter` is acquired by outside `BytesToBytesMap`, instead the allocatedPages in `UnsafeExternalSorter`. So the memory spill bytes metric is always 0, but disk bytes spill metric is right.

Besides, this PR also fixes the `UnsafeExternalSorter.merge` by accumulating the `totalSpillBytes` of two sorters. Thus, we can report the correct spilled size in `HashAggregateExec.finishAggregate`.

Issues can be reproduced by the following step by checking the SQL metrics in UI:

```
bin/spark-shell --driver-memory 512m --executor-memory 512m --executor-cores 1 --conf "spark.default.parallelism=1"
scala> sql("select id, count(1) from range(10000000) group by id").write.csv("/tmp/result.json")
```

Before:

WeChatfe5146180d91015e03b9a27852e9a443

After:

WeChat42ab0e73c5fbc3b14c12ab85d232071d

### Does this PR introduce _any_ user-facing change?

Yes, users can see the correct spill metrics after this PR.

### How was this patch tested?

Tested manually and added UTs.

### CODE REVIEW

**Comment by Ngone51** [comment]
cc @WangGuangxin  @cloud-fan @maropu Please take a look, thanks!

**Review by jaceklaskowski — APPROVED** [review]
LGTM (non-binding)

**Comment by WangGuangxin** [comment]
LGTM

**Review by cloud-fan — APPROVED** [review]

**Comment by cloud-fan** [comment]
thanks, merging to master/3.1!

**Comment by cloud-fan** [comment]
@Ngone51 can you also open a PR for 3.0? thanks!

**Comment by Ngone51** [comment]
@cloud-fan  3.0 PR https://github.com/apache/spark/pull/31140

**Comment by dongjoon-hyun** [comment]
+1, late LGTM. Thanks!

**Pull request closed without merging**
