### PR TITLE
 [MINOR] Fix some typos

### PR DESCRIPTION
**Pull request by for08**
What changes were proposed in this pull request?
Two mistakes in the code comments.
Why are the changes needed?
Modify these two comment mistakes and make code comments more standardized.
Does this PR introduce any user-facing change?
No
How was this patch tested?
No test required

### CODE REVIEW

**Review by srowen — COMMENTED** [review]
Please fill out the template a bit and see https://spark.apache.org/contributing.html
These are correct, but are trivial. Are there more? we usually don't do a PR for just a comment typo

**Review by bjornjorgensen — COMMENTED** [review]
deallocates -> deallocate

**Review by bjornjorgensen — COMMENTED** [review]
waste underlying -> waste the underlying

**Comment by srowen** [comment]
Just make the two changes - this can reopen

**Comment by for08** [comment]
> 

How to reopen this PR?
I don't have permission to reopen.

**Comment by srowen** [comment]
Push a new conmit

**Pull request closed without merging**
