### PR TITLE
[SPARK-35850][BUILD] Upgrade scala-maven-plugin to 4.5.3

### PR DESCRIPTION
**Pull request by williamhyun**
### What changes were proposed in this pull request?
This PR aims to upgrade the scala-maven-plugin version to 4.5.3.

### Why are the changes needed?
This will upgrade `sbt-compiler-bridge` from 1.3.1 to 1.5.5 in order to bring the latest bug fixes. 

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass the CIs.

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]
LGTM if tests pass

**Comment by dongjoon-hyun** [comment]
Retest this please

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @williamhyun and @HyukjinKwon .

**Comment by dongjoon-hyun** [comment]
Ah, the last Maven run is still running. I'll monitor the status here and Jenkins Maven jobs, @HyukjinKwon .

**Comment by HyukjinKwon** [comment]
Hm .. in the plain env with Ubuntu (Jenkins) and another CI (Binder), the build starts to fail with the error below (during `scala-maven-plugin` compilation) after this change. Both Ubuntus installed OpenJDK via `apt-get install openjdk-8-jdk`.

```
[ERROR] ## Exception when compiling 13 sources to /ephemeral/jenkins/shared_job_workspace/spark/common/tags/target/scala-2.12/classes
java.io.IOException: Cannot run program "/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/javac" (in directory "/ephemeral/jenkins/shared_job_workspace/runtime"): error=2, No such file or directory
java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
...
```

Setting Java home and path explicitly work:

```bash
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
export PATH=$JAVA_HOME/bin:$PATH
```

I thought that this is my env issue but it happens in two different CI with plain Ubuntu.

**Comment by HyukjinKwon** [comment]
I don't know why but It doesn't happen if you install JDK 11 (`apt-get install openjdk-11-jdk.`).

**Comment by dongjoon-hyun** [comment]
Thank you for reporting.

**Comment by dongjoon-hyun** [comment]
It's because Java 11 doesn't have JRE as Java language feature.

When we do install `apt-get update; apt-get install openjdk-8-jdk -y` on the vanilla Ubuntu. `java` points `JRE Java`.

**JAVA 8**
```
$ docker run -it --rm ubuntu:21.04 /bin/bash
$ apt-get update; apt-get install openjdk-8-jdk -y
root@c34d6662cd1d:/# which java
/usr/bin/java
root@c34d6662cd1d:/# ls -al /usr/bin/java
lrwxrwxrwx 1 root root 22 Jun 24 18:42 /usr/bin/java -> /etc/alternatives/java
root@c34d6662cd1d:/# ls -al /etc/alternatives/java
lrwxrwxrwx 1 root root 46 Jun 24 18:42 /etc/alternatives/java -> /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
```

**JAVA 11**
```
$ docker run -it --rm ubuntu:21.04 /bin/bash
$ apt-get update; apt-get install openjdk-11-jdk -y
root@8e4884f5da28:/# which java
/usr/bin/java
root@8e4884f5da28:/# ls -al /usr/bin/java
lrwxrwxrwx 1 root root 22 Jun 24 18:41 /usr/bin/java -> /etc/alternatives/java
root@8e4884f5da28:/# ls -al /etc/alternatives/java
lrwxrwxrwx 1 root root 43 Jun 24 18:41 /etc/alternatives/java -> /usr/lib/jvm/java-11-openjdk-amd64/bin/java
```

**Comment by dongjoon-hyun** [comment]
It seems that OpenJava docker images have `JAVA_HOME` with JDK. It seems that we can find some workaround for this. Or, do you want to revert this, @HyukjinKwon ?
```
$ docker run -it --rm openjdk:8
root@8cbf74e3223f:/# echo $JAVA_HOME
/usr/local/openjdk-8

root@8cbf74e3223f:/# which java
/usr/local/openjdk-8/bin/java

root@8cbf74e3223f:/# which javac
/usr/local/openjdk-8/bin/javac
```

**Comment by dongjoon-hyun** [comment]
Hi, @williamhyun . Could you try to address the situation?

**Comment by HyukjinKwon** [comment]
Sorry I'm just getting up now :). Let me take a look a bit more... maybe we should just better explicitly set them ...

**Comment by dongjoon-hyun** [comment]
Hold on, @HyukjinKwon . We found a simple solution for this.

**Comment by dongjoon-hyun** [comment]
@williamhyun will make a PR soon today.

**Comment by HyukjinKwon** [comment]
Thanks!!!!

**Pull request closed without merging**
