### PR TITLE
[SPARK-33955][SS] Add latest offsets to source progress

### PR DESCRIPTION
**Pull request by viirya**
### What changes were proposed in this pull request?

This patch proposes to add latest offset to source progress for streaming queries.

### Why are the changes needed?

Currently we record start and end offsets per source in streaming process. Latest offset is an important information for streaming process but the progress lacks of this info. We can use it to track the process lag and adjust streaming queries. We should add latest offset to source progress.

### Does this PR introduce _any_ user-facing change?

Yes, for new metric about latest source offset in source progress.

### How was this patch tested?

Unit test. Manually test in Spark cluster:

```
    "description" : "KafkaV2[Subscribe[page_view_events]]",
    "startOffset" : {
      "page_view_events" : {
        "2" : 582370921,
        "4" : 391910836,
        "1" : 631009201,
        "3" : 406601346,
        "0" : 195799112
      }
    },
    "endOffset" : {
      "page_view_events" : {
        "2" : 583764414,
        "4" : 392338002,
        "1" : 632183480,
        "3" : 407101489,
        "0" : 197304028
      }
    },
    "latestOffset" : {
      "page_view_events" : {
        "2" : 589852545,
        "4" : 394204277,
        "1" : 637313869,
        "3" : 409286602,
        "0" : 203878962
      }
    },
    "numInputRows" : 4999997,
    "inputRowsPerSecond" : 29287.70501405811,
```

### CODE REVIEW

**Comment by viirya** [comment]
retest this please

**Review by dongjoon-hyun — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
cc @HeartSaVioR and @xuanyuanking FYI

**Comment by HyukjinKwon** [comment]
Looks making sense to me too

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @viirya and @HyukjinKwon .
Merged to master for Apache Spark 3.2.0.

**Pull request closed without merging**
