### PR TITLE
[SPARK-28858][ML][PYSPARK] add tree-based transformation in the py side

### PR DESCRIPTION
**Pull request by zhengruifeng**
### What changes were proposed in this pull request?
expose the newly added tree-based transformation in the py side

### Why are the changes needed?
function parity

### Does this PR introduce any user-facing change?
yes, add `setLeafCol` & `getLeafCol` in the py side

### How was this patch tested?
added tests & local tests

### CODE REVIEW

**Comment by zhengruifeng** [comment]
This PR follows current pyspark's convention, which do support no setter/getter for model.

I am looking into the hierarchy of both scala and py side, and will open a ticket on the sync in next one or two weeks. I think we can sync them in a batch in the future, so in this PR I stick to pyspark's convention.

**Review by srowen — COMMENTED** [review]
Looks reasonable to me. I guess unfortunately all of the examples predict a leaf ID of 0?

**Comment by zhengruifeng** [comment]
@srowen  Yes. But I try other inputs and the returned leafId can be 1.

**Comment by zhengruifeng** [comment]
should I change the input dataset to make some output != 0? @srowen

**Comment by srowen** [comment]
I wouldn't change the examples unless it's easy. It's not a big deal.

**Review by BryanCutler — APPROVED** [review]
LGTM

**Comment by BryanCutler** [comment]
merged to master, thanks @zhengruifeng !

**Comment by zhengruifeng** [comment]
Thanks for reviewing!  @BryanCutler @srowen

**Pull request closed without merging**
