### PR TITLE
[SPARK-31101][BUILD] Upgrade Janino to 3.0.16

### PR DESCRIPTION
**Pull request by HeartSaVioR**
### What changes were proposed in this pull request?

This PR(SPARK-31101) proposes to upgrade Janino to 3.0.16 which is released recently.

* Merged pull request janino-compiler/janino#114 "Grow the code for relocatables, and do fixup, and relocate".

Please see the commit log.
- https://github.com/janino-compiler/janino/commits/3.0.16

You can see the changelog from the link: http://janino-compiler.github.io/janino/changelog.html / though release note for Janino 3.0.16 is actually incorrect.

### Why are the changes needed?

We got some report on failure on user's query which Janino throws error on compiling generated code. The issue is here: janino-compiler/janino#113 It contains the information of generated code, symptom (error), and analysis of the bug, so please refer the link for more details.
Janino 3.0.16 contains the PR janino-compiler/janino#114 which would enable Janino to succeed to compile user's query properly.

### Does this PR introduce any user-facing change?

No.

### How was this patch tested?

Existing UTs.

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
The failure is not from compilation from generated code, but no big deal on rerunning tests.

**Comment by HeartSaVioR** [comment]
retest this, please

**Comment by HeartSaVioR** [comment]
retest this, please

**Comment by HeartSaVioR** [comment]
retest this, please

**Comment by HeartSaVioR** [comment]
retest this, please

**Comment by HeartSaVioR** [comment]
```
org.apache.spark.scheduler.BarrierTaskContextSuite.successively sync with allGather and barrier
 Error Details
org.apache.spark.SparkException: Job aborted due to stage failure: Could not recover from a failed barrier ResultStage. Most recent failure reason: Stage failed because barrier task ResultTask(0, 3) finished unsuccessfully. com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input  at [Source: (String)""; line: 1, column: 0]  at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)  at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1442)  at com.fasterxml.jackson.databind.ObjectReader._initForReading(ObjectReader.java:360)  at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1704)  at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1261)  at org.json4s.jackson.JsonMethods.parse(JsonMethods.scala:25)  at org.json4s.jackson.JsonMethods.parse$(JsonMethods.scala:19)  at org.json4s.jackson.JsonMethods$.parse(JsonMethods.scala:55)  at org.apache.spark.BarrierTaskContext.allGather(BarrierTaskContext.scala:222)  at org.apache.spark.scheduler.BarrierTaskContextSuite.$anonfun$new$12(BarrierTaskContextSuite.scala:118)  at org.apache.spark.rdd.RDDBarrier.$anonfun$mapPartitions$2(RDDBarrier.scala:51)  at org.apache.spark.rdd.RDDBarrier.$anonfun$mapPartitions$2$adapted(RDDBarrier.scala:51)  at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)  at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)  at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)  at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)  at org.apache.spark.scheduler.Task.run(Task.scala:127)  at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:460)  at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)  at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:463)  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)  at java.base/java.lang.Thread.run(Thread.java:834) 
```

Doesn't seem to be related.

**Comment by HeartSaVioR** [comment]
retest this, please

**Comment by HeartSaVioR** [comment]
```
org.apache.spark.ExecutorAllocationManagerSuite.add executors capped by num pending tasks 

Error Details

org.scalatest.exceptions.TestFailedException: 6 did not equal 5

org.apache.spark.scheduler.WorkerDecommissionSuite.verify a task with all workers decommissioned succeeds 

Error Details

java.util.concurrent.TimeoutException: Futures timed out after [2 seconds]

org.apache.spark.storage.BlockManagerReplicationSuite.block replication - mixed between 1x to 5x 

Error Details

org.scalatest.exceptions.TestFailedException: 3 did not equal 4 master did not have 4 locations for test_block-with-disk-memory-deserialized-4x-replicated
```

Another flaky ones.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Merged to master.
Thank you for your long investigating and patience, @HeartSaVioR .

I added the following into the PR description.
```
https://github.com/janino-compiler/janino/commits/3.0.16
```

**Comment by HeartSaVioR** [comment]
Thanks for sorting it out. Could we port back to 3.0 & 2.4 as well, given the origin bug was from Spark 2.3? I'll submit PRs for these versions. Thanks again!

**Comment by HeartSaVioR** [comment]
#27996 for Spark 3.0.0 / #27997 for Spark 2.4.x

**Pull request closed without merging**
