### PR TITLE
[MINOR] Update the PR template for adding a link to the configuration naming guideline 

### PR DESCRIPTION
**Pull request by maropu**
### What changes were proposed in this pull request?

This is a follow-up of #27577. This pr intends to add a link to the configuration naming guideline in `.github/PULL_REQUEST_TEMPLATE`.

### Why are the changes needed?

For reminding developers to follow the naming rules.

### Does this PR introduce any user-facing change?

No.

### How was this patch tested?

N/A

### CODE REVIEW

**Comment by maropu** [comment]
cc: @cloud-fan @HyukjinKwon

**Review by cloud-fan — APPROVED** [review]

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master, since the tests have nothing related to this.

**Comment by maropu** [comment]
Thanks all.

**Comment by dongjoon-hyun** [comment]
+1, LGTM. Thank you, @maropu , @cloud-fan , @HyukjinKwon .

**Pull request closed without merging**
