### PR TITLE
[SPARK-34329][YARN] When hit ApplicationAttemptNotFoundException, we can't just stop app for all case	

### PR DESCRIPTION
**Pull request by AngersZhuuuu**
### What changes were proposed in this pull request?

With `yarn-client` mode, our user meet case that because yarn queue's setting, some app's container is preempted by a higher level request due to the scheduling framework. Then throw `ApplicationAttemptNotFoundException`,  in an old PR https://github.com/apache/spark/pull/10129, it add the behavior we always close app directly without retry when hit `ApplicationAttemptNotFoundException`.

In yarn-client mode, when AM's container was preempted. Then RM can't find this attempt. Then client driver backend receive `ApplicationAttemptNotFoundException`. But for some case, such as queue issue caused by peak usage, we can have a retry then it may success. 

Since for not all case throw `ApplicationAttemptNotFoundException` we don't need to retry. IMO, we should not just catch this exception and stop app. So in this pr, I suppose to add a condition, that only when cluster mode, we just stop when hit 
`ApplicationAttemptNotFoundException`

### Why are the changes needed?
Make job more tolerable about container issue

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Not need

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @tgravescs and @jerryshao FYI

**Comment by tgravescs** [comment]
can you provide more detail here. 
what mode is this running in when you hit this (client or cluster - unmanaged am or managed)?
When you say its preempted, I assume that you mean this application was killed by the RM due to higher priority?  If it was killed how can it stay alive

**Comment by AngersZhuuuu** [comment]
> can you provide more detail here.
> what mode is this running in when you hit this (client or cluster - unmanaged am or managed)?
> When you say its preempted, I assume that you mean this application was killed by the RM due to higher priority? If it was killed how can it stay alive

Our case is client mode. this error throw in driver side.
So we can change to :

1. client- mode, for this error we can have a retry.
2. cluster-mode, since this ApplicationMaster running in the AM container, so we can just stop?
3.

**Comment by tgravescs** [comment]
ok, please update the description with those details.
maybe cluster mode doesn't matter here because application master would be killed anyway.
The original change I believe was before we could handle application master being killed and restarted. I think that is handled ok now. so just to verify with this change, the application master gets preempted and killed and application master gets restarted and the driver process continue, correct?

The only thing better would be if yarn told us this was a preempt case, did you look at that at all?  its been a while since I looked into the yarn code.

**Comment by AngersZhuuuu** [comment]
> ok, please update the description with those details.
> maybe cluster mode doesn't matter here because application master would be killed anyway.
> The original change I believe was before we could handle application master being killed and restarted. I think that is handled ok now. so just to verify with this change, the application master gets preempted and killed and application master gets restarted and the driver process continue, correct?
> 
> The only thing better would be if yarn told us this was a preempt case, did you look at that at all? its been a while since I looked into the yarn code.

From the error stack, it only tell us the attempt can't be found. I got root cause in yarn's log. Since we can't change yarn's code  in spark side, what we can do here is just retry. I am looking into yarn's code these days.

**Comment by AngersZhuuuu** [comment]
retest this please

**Comment by AngersZhuuuu** [comment]
retest this please

**Comment by AngersZhuuuu** [comment]
ping @tgravescs

**Comment by AngersZhuuuu** [comment]
gentle ping @tgravescs Any more suggestion?

**Comment by tgravescs** [comment]
Sorry was out of office for a bit. did you look at the test failure?

>> The only thing better would be if yarn told us this was a preempt case, did you look at that at all? its been a while since I looked into the yarn code.
> From the error stack, it only tell us the attempt can't be found. I got root cause in yarn's log. Since we can't change yarn's code in spark side, what we can do here is just retry. I am looking into yarn's code these days.

did you have a chance to look at the yarn code here?  I thought YARN was supposed to give indication that it was going to preempt you but its been a while since I did anything in YARN.

**Comment by AngersZhuuuu** [comment]
RM clean preempted container's  info, then code in `ClientRMService` throw `ApplicationAttemptNotFoundException`

```
    RMAppAttempt appAttempt = application.getAppAttempts().get(attemptId);
    if (appAttempt == null) {
      throw new ApplicationAttemptNotFoundException(
          "ApplicationAttempt with id '" + attemptId + "' doesn't exist in RM.");
    }
```

`org.apache.spark.deploy.yarn.Client` will receive this exception。

In yarn-client

**Comment by AngersZhuuuu** [comment]
retest this please

**Comment by AngersZhuuuu** [comment]
> Sorry was out of office for a bit. did you look at the test failure?

Seems a flaky test.

**Comment by AngersZhuuuu** [comment]
ping @tgravescs

**Pull request closed without merging**
