### PR TITLE
[MINOR] Remove unused import

### PR DESCRIPTION
**Pull request by sunchao**
### What changes were proposed in this pull request?

Remove unused import in `TimestampNTZType`.

### Why are the changes needed?

Cleanup

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

N/A

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]

**Review by MaxGekk — COMMENTED** [review]
Just in case, I used IntelliJ IDEA to find unused imports in Spark's Java code:
Screenshot 2022-05-04 at 20 42 56
Probably, there is a tool for Scala code too.

**Review by viirya — APPROVED** [review]

**Comment by viirya** [comment]
I remember unused imports will be caught by style check?

**Comment by sunchao** [comment]
> Just in case, I used IntelliJ IDEA to find unused imports in Spark's Java code ...

Cool thanks, this is useful.

I'm also a bit surprised that it isn't caught by the style check. I saw it when reading the code so just figured it's better to fix it while I'm at it :)

**Comment by HyukjinKwon** [comment]
Yeah, it should be caught. Interesting..

**Pull request closed without merging**
