### PR TITLE
[MINOR] Fix Python Lint

### PR DESCRIPTION
**Pull request by zhengruifeng**
### What changes were proposed in this pull request?
Fix Python Lint

### Why are the changes needed?
Python Linter is now broken

```
starting black test...
black checks failed:
would reformat python/pyspark/testing/connectutils.py

Oh no! 💥 💔 💥
1 file would be reformatted, 391 files would be left unchanged.
Please run 'dev/reformat-python' script.
1
```

### How was this patch tested?
manually test

### CODE REVIEW

**Comment by zhengruifeng** [comment]
@HyukjinKwon @dongjoon-hyun

**Comment by zhengruifeng** [comment]
wait for a moment

**Comment by zhengruifeng** [comment]
there is another error:
```
python/pyspark/sql/tests/connect/test_connect_function.py:29: error: Incompatible import of "PandasOnSparkTestCase" (imported name has type "Type[ReusedSQLTestCase]", local name has type "Type[PandasOnSparkTestCase]")  [misc]
```

**Comment by dongjoon-hyun** [comment]
For the first one, I fixed here.
- https://github.com/apache/spark/pull/38931

For the second one, let me check.

**Comment by zhengruifeng** [comment]
thanks, let me close this one

**Comment by dongjoon-hyun** [comment]
For the second one, does it come from `GitHub Action` log?

**Comment by zhengruifeng** [comment]
> For the second one, does it come from `GitHub Action` log?

no, it came from local `dev/lint-python`

**Comment by dongjoon-hyun** [comment]
Thank you. Got it.

**Pull request closed without merging**
