### PR TITLE
 [SPARK-24990][SQL] merge ReadSupport and ReadSupportWithSchema

### PR DESCRIPTION
**Pull request by cloud-fan**
## What changes were proposed in this pull request?

Regarding user-specified schema, data sources may have 3 different behaviors:
1. must have a user-specified schema
2. can't have a user-specified schema
3. can accept the user-specified if it's given, or infer the schema.

I added `ReadSupportWithSchema` to support these behaviors, following data source v1. But it turns out we don't need this extra interface. We can just add a `createReader(schema, options)` to `ReadSupport` and make it call `createReader(options)` by default.

TODO: also fix the streaming API in followup PRs.

## How was this patch tested?

existing tests.

### CODE REVIEW

**Comment by holdensmagicalunicorn** [comment]
@cloud-fan, thanks! I am a bot who has found some folks who might be able to help with the review:@gatorsmile, @zsxwing and @tdas

**Comment by cloud-fan** [comment]
cc @rxin @rdblue @jose-torres

**Comment by jose-torres** [comment]
Wouldn't the redo of the API that we're discussing obsolete this?

**Comment by cloud-fan** [comment]
In the new proposal, we just rename `ReadSupport` to `BatchReadSupportProvider`, so this change is kind of part of the big proposal.

**Comment by rdblue** [comment]
Isn't this unnecessary after the API redesign?

For the redesign, the `DataSourceV2` or a `ReadSupportProvider` will supply a `create` method (or `anonymousTable`) to return a `Table` that implements `ReadSupport`. `ReadSupport` should not accept user schemas because the schema should be accessible from the `Table` itself. That way, we can use the same table-based relation (see https://github.com/apache/spark/pull/21877/files#diff-35ba4ffb5ccb9b18b43226f1d5effa23R82).

**Comment by rdblue** [comment]
@cloud-fan, from your comment around the same time as mine, it sounds like the confusion may just be in how you're updating the current API to the proposed one. Can you post a migration plan? It sounds like something like this:

`ReadSupport` and `ReadSupportWithSchema` -> `BatchReadSupportProvider`
`DataSourceReader` -> `ReadSupport`

Is that right? The re-use of `ReadSupport` would explain the confusion on my end.

**Comment by cloud-fan** [comment]
> a ReadSupportProvider will supply a create method (or anonymousTable) to return a Table that implements ReadSupport...

I'd prefer the current proposal in https://docs.google.com/document/d/1DDXCTCrup4bKWByTalkXWgavcPdvur8a4eEu8x1BzPM/edit?ts=5b613c42 : `ReadSupportProvider#create` returns `ReadSupport`.
1. Table supports both read and write, but we may want to allow read-only data sources.
2. the `Table` interface is still being developed, we can switch to it if we find it's more feasible later.

**Comment by cloud-fan** [comment]
@rdblue the plan is, I will have a big PR that implements the redesign. However, if there is something makes sense even without the redesign, we should have a separated PR. I think merging `ReadSupport` and `ReadSupportWithSchema` is the one.

**Comment by cloud-fan** [comment]
> ReadSupport and ReadSupportWithSchema -> BatchReadSupportProvider
DataSourceReader -> ReadSupport

Yea, this is what I'm doing in my local branch for the redesign. I'll push it soon when it's finished.

**Comment by rdblue** [comment]
Yeah, I'm fine with this, then.

**Comment by gatorsmile** [comment]
@rdblue This change is pretty isolated. It also LGTM to me. 

Since you are fine about the change, I am assuming you are not blocking this. I will merge this soon.

**Comment by rdblue** [comment]
+1

**Review by gatorsmile — COMMENTED** [review]
Thanks! Merged to master.

**Pull request closed without merging**
