### PR TITLE
[SPARK-30721][SQL][TESTS] Fix DataFrameAggregateSuite when enabling AQE

### PR DESCRIPTION
**Pull request by cloud-fan**
### What changes were proposed in this pull request?

update `DataFrameAggregateSuite` to make it pass with AQE

### Why are the changes needed?

We don't need to turn off AQE in `DataFrameAggregateSuite`

### Does this PR introduce any user-facing change?

no

### How was this patch tested?

run `DataFrameAggregateSuite` locally with AQE on.

### CODE REVIEW

**Comment by cloud-fan** [comment]
cc @maryannxue @JkSelf

**Comment by cloud-fan** [comment]
retest it please

**Review by maryannxue — APPROVED** [review]
LGTM

**Comment by cloud-fan** [comment]
retest this please

**Comment by cloud-fan** [comment]
retest this please

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @cloud-fan and @maryannxue .
Merged to master/3.0.

**Pull request closed without merging**
