### PR TITLE
[SPARK-32554][K8S][DOCS] Remove the words "experimental" in the k8s document

### PR DESCRIPTION
**Pull request by maropu**
### What changes were proposed in this pull request?

This PR targets at dropping the words "experimental" in the k8s document from the primary branch.

This update comes from a thread in the spark-dev mailing list: http://apache-spark-developers-list.1001551.n3.nabble.com/spark-on-k8s-is-still-experimental-td29942.html

### Why are the changes needed?

To prepare a GA announcement for the k8s scheduler in the next feature release (v3.1.0)

### Does this PR introduce _any_ user-facing change?

Yes

BEFORE:
Screen Shot 2020-08-10 at 21 17 48
AFTER:

### How was this patch tested?

N/A

### CODE REVIEW

**Comment by maropu** [comment]
cc: @holdenk @srowen

**Comment by holdenk** [comment]
Personally I'd drop the "getting" and I'd drop "External Shuffle Service" (I think non-expiremental dynamic resource allocation with or without external shuffle is good enough). These are just my own opinions though.

**Comment by maropu** [comment]
> Personally I'd drop the "getting" and I'd drop "External Shuffle Service" (I think non-expiremental dynamic resource allocation with or without external shuffle is good enough). These are just my own opinions though.

Thanks for the comment and the suggestion sounds resonable to me, so I updated it.

**Comment by ScrapCodes** [comment]
Hi, I am not absolutely sure where and when it was decided, that we need to wait for External shuffle service, for Spark on k8s to be GA, can anyone help me with the discussion link? So far, It has been stated as if already a fact.

**Comment by srowen** [comment]
I don't know either. I'd wonder, what actionable difference would this make, to declare it still partly experimental? is there any work coming in the foreseeable future on it? is it dangerous to use in production? will an API possibly change?  If we're basically not warning people away from using it as is with the usual understanding that stuff can have minor bugs, then, maybe no value in making this ill-defined statement at all, and avoid confusion.

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
Hi, @maropu .
The PR is completely mismatched with the current K8s development step.
> but Dynamic Resource Allocation needs to be available 

Apache Spark 3.0.0 already shipped Dynamic Allocation via SPARK-28963.
- SPARK-27963 Allow dynamic allocation without a shuffle service.

In addition to the above, Apache Spark 3.1.0 also have the following improvements.
- SPARK-29905 Improve pod lifecycle manager behavior with dynamic allocation

**Comment by dongjoon-hyun** [comment]
cc @felixcheung because this was discussed at dev mailing list "Apache Spark 3.1 Feature Expectation (Dec. 2020)" and he wanted some for K8s GA.
- https://lists.apache.org/thread.html/r9db328c667a2e4ac6c874dbdc41d3b20f33e0c71cb8992c9bc407789%40%3Cdev.spark.apache.org%3E

**Comment by maropu** [comment]
> SPARK-27963 Allow dynamic allocation without a shuffle service.

Thanks for the info, @dongjoon-hyun . I see and I referred to [the other ticket](https://issues.apache.org/jira/browse/SPARK-24432) and [the document statement](https://github.com/apache/spark/blame/master/docs/running-on-kubernetes.md#L491-L495). But, as you said, the current statement doesn't match it. I will checki it again and update it.

>  I'd wonder, what actionable difference would this make, to declare it still partly experimental?...

Thanks for the comment, @srowen. Yea, this statement update doesn't gurantee anything about behaivour/configuration stability... But, I think it is a bit weird that the docment 2.3.x and 3.0.x have the same description about the development status. So, I thought it is worth updating it according to the current situation (I need to consider more about how to write it though...).

> Hi, I am not absolutely sure where and when it was decided, that we need to wait for External shuffle service, for Spark on k8s to be GA, can anyone help me with the discussion link? So far, It has been stated as if already a fact.

Any link to the discussion described in the mailing list, @holdenk ?
Probably, she refered to the discussion @dongjoon-hyun [described above](https://lists.apache.org/thread.html/r9db328c667a2e4ac6c874dbdc41d3b20f33e0c71cb8992c9bc407789%40%3Cdev.spark.apache.org%3E)? I'm still not sure that we have a general consensus about k8s GA though, do you know something about it, @ScrapCodes ? (I roughly looked around the mailing list logs and jira/PR, but I couldn't find it  though...)

**Comment by dongjoon-hyun** [comment]
We don't have a consensus indeed. That's the problem here. :) @maropu

**Comment by ScrapCodes** [comment]
I had say, it should be discussed, we would like to hear from the users. Do we have enough confidence, for example if it is already in use at some company X at a production scale. Would that give us enough confidence.

It is possible, that after external shuffle service is developed, the API may need to change. But, since we do not expose anything in K8s as API, it should not be a problem. Even if we do, we can keep the APIs as experimental, instead of declaring that "Spark on K8s is experimental and not ready for production, until ..." 

Today, I see "so many" people (AFAIK) still using standalone mode on K8s for deploying spark on k8s. It is true, we may be missing a feature or two. But, all of this should be discussed and we should have consensus about when to GA.

**Comment by srowen** [comment]
let me ask this: what is the problem with marking it not-experimental? compared to perhaps people questioning using it in its current state? I don't know that its state is going to change much soon anyway. I'd just unmark it, I think.

**Comment by dongjoon-hyun** [comment]
I also have the same opinion with @srowen . We can declare K8s GA in Apache Spark 3.1.0 with AS-IS status and add new features more. I don't think any new feature blocks K8s GA.

**Comment by ScrapCodes** [comment]
I am in favour of marking it GA too. The feature does not block it's GA status.

**Comment by holdenk** [comment]
Sounds good to me 👍

**Comment by maropu** [comment]
Thanks for the comments, all. Looks like all the (current) discussion participants agree that we will announce GA with as-is status  in the next feature release (3.1.0). So, I think its okay to we can simply drop the statement now in the doc from the primary branch.

**Comment by ScrapCodes** [comment]
Looks good !

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you for leading this, @maropu . And, thank you all for supporting this.
Merged to master.

**Comment by maropu** [comment]
Thanks, @dongjoon-hyun and all!

**Pull request closed without merging**
