### PR TITLE
[MINOR][TEST] Update from 2.2.0 to 2.2.1 in HiveExternalCatalogVersionsSuite

### PR DESCRIPTION
**Pull request by seancxmao**
## What changes were proposed in this pull request?
In `HiveExternalCatalogVersionsSuite`, latest version of 2.2.x is updated from 2.2.0 to 2.2.1

## How was this patch tested?
N/A

### CODE REVIEW

**Comment by wangyum** [comment]
Jenkins, retest this please.

**Review by srowen — APPROVED** [review]

**Comment by srowen** [comment]
Hm:

```
[info] - backward compatibility *** FAILED *** (34 seconds, 96 milliseconds)
[info]   spark-submit returned with exit code 1.
[info]   Command line: './bin/spark-submit' '--class' 'org.apache.spark.sql.hive.PROCESS_TABLES' '--name' 'HiveExternalCatalog backward compatibility test' '--master' 'local[2]' '--conf' 'spark.ui.enabled=false' '--conf' 'spark.master.rest.enabled=false' '--conf' 'spark.sql.warehouse.dir=/home/jenkins/workspace/NewSparkPullRequestBuilder/target/tmp/warehouse-a76e4f7b-3ab5-463f-83be-7e95b5172271' '--driver-java-options' '-Dderby.system.home=/home/jenkins/workspace/NewSparkPullRequestBuilder/target/tmp/warehouse-a76e4f7b-3ab5-463f-83be-7e95b5172271' 'file:/home/jenkins/workspace/NewSparkPullRequestBuilder/target/tmp/spark-f34f7048-27da-4dea-bbad-dec833d34fb4/testJar-1518521748609.jar'
...
[info]   2018-02-13 03:38:04.528 - stderr> Exception in thread "main" org.apache.spark.sql.AnalysisException: Operation not allowed: MSCK REPAIR TABLE only works on partitioned tables: `default`.`tbl_with_col_overlap_2`;
```

**Comment by gatorsmile** [comment]
Let me take this over and do more investigation. This looks suspicious. I think we are changing the behaviors in 2.3 and 2.2.1

**Comment by gatorsmile** [comment]
This is a behavior change introduced in https://github.com/apache/spark/pull/19579. We need to add a migration guide for this case. Will do it by myself. 

@seancxmao Thanks for your contribution!

**Comment by gatorsmile** [comment]
Just submitted a PR https://github.com/apache/spark/pull/20606

**Pull request closed without merging**
