### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by slaven-s**
Hi,

I added section "Books" and a link to the Spark GraphX in Action written by Michael S. Malak and Robin East for Manning Publications. We believe this book is a great resource and all members of community will benefit from this information. If you find this inappropriate, please let me know where I can publish it.

### CODE REVIEW

**Comment by srowen** [comment]
I don't think this belongs on the project readme. Maybe the wiki. Do you mind closing this PR?

**Comment by slaven-s** [comment]
I did it.Please can I ask for the link of the the Wiki? Where could we add Ch 1 for documentation?Thank you very much.Slaven
 


     Datuma 23:37 Nedjelja, 6. Rujan 2015., Sean Owen <notifications@github.com> je napisao:
   

 I don't think this belongs on the project readme. Maybe the wiki. Do you mind closing this PR?—

**Comment by srowen** [comment]
Ah, I thought we already had a page for this and I found it:
http://spark.apache.org/documentation.html

This book is already mentioned actually.

**Comment by slaven-s** [comment]
Thanks for the answer. Please is there some place where we could place chapter 1? Thanks once again.
 


     Datuma 16:52 Utorak, 8. Rujan 2015., Sean Owen <notifications@github.com> je napisao:
   

 Ah, I thought we already had a page for this and I found it:
http://spark.apache.org/documentation.htmlThis book is already mentioned actually.—

**Comment by srowen** [comment]
It's already linked from the landing page from the book. I don't think it makes sense for Spark to host a chapter from this book too?

**Comment by slaven-s** [comment]
Thanks for the answer.
 


     Datuma 17:02 Utorak, 8. Rujan 2015., Sean Owen <notifications@github.com> je napisao:
   

 It's already linked from the landing page from the book. I don't think it makes sense for Spark to host a chapter from this book too?—

**Comment by packtpartner** [comment]
Hi @srowen , where is the Github repository to feature books on http://spark.apache.org/documentation.html ?

**Pull request closed without merging**
