### PR TITLE
[HOTFIX] Fix java style

### PR DESCRIPTION
**Pull request by viirya**
### What changes were proposed in this pull request?

Fix a Java style issue blocking CI.

### Why are the changes needed?

Unblocking CI.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

CI

### CODE REVIEW

**Comment by viirya** [comment]
@sunchao noticed a commit https://github.com/apache/spark/commit/3b0dd14f1c5dd033ad0a6295baa288eda9dfe10a failed CI.

Currently looks like it has a Java style [issue](https://github.com/apache/spark/runs/3306308477):

```
 Error:  src/test/java/org/apache/spark/network/crypto/AuthEngineSuite.java:[158] (sizes) LineLength: Line is longer than 100 characters (found 111).
```

This commit is quite big and seems not from any PR. I'm not sure about its context so don't revert it directly. Just trying to fix the style issue here.

@srowen @dongjoon-hyun @HyukjinKwon

**Comment by srowen** [comment]
Ack, that's my fault. I thought I fixed that.

**Comment by srowen** [comment]
(Yes there is a reason this is not publicly disclosed yet)

**Comment by viirya** [comment]
I only fix the Java style and Java lint test was passed in GHA. I'm going to merge this first to unblock.

**Comment by viirya** [comment]
Merging to master.

**Comment by HyukjinKwon** [comment]
lgtm

**Pull request closed without merging**
