### PR TITLE
SPARK-9070 JavaDataFrameSuite teardown NPEs if setup failed

### PR DESCRIPTION
**Pull request by steveloughran**
fix teardown to skip table delete if hive context is null

### CODE REVIEW

**Comment by srowen** [comment]
LGTM

**Comment by JoshRosen** [comment]
LGTM as well.

**Comment by rxin** [comment]
LGTM. 

(Can this PR have the highest LGTM to LOC change ratio?)

**Comment by rxin** [comment]
Thanks - merging this.

**Pull request closed without merging**
