### PR TITLE
[SPARK-41775][PYTHON][FOLLOWUP] Use pyspark.cloudpickle instead of `cloudpickle` in torch distributor

### PR DESCRIPTION
**Pull request by WeichenXu123**
### What changes were proposed in this pull request?

Use pyspark.cloudpickle instead of `cloudpickle` in torch distributor

### Why are the changes needed?

Make ser and deser code consistent

### Does this PR introduce _any_ user-facing change?

No.

### CODE REVIEW

**Review by zhengruifeng — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by dongjoon-hyun** [comment]
BTW, this seems to happen frequently. Do you think there is a way to prevent this automatically, @WeichenXu123 , @zhengruifeng ? Also, cc @HyukjinKwon .

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Let me see if there's a linter rule to detect this

**Comment by dongjoon-hyun** [comment]
Thank you!

**Comment by dongjoon-hyun** [comment]
Merged to master.

**Pull request closed without merging**
