### PR TITLE
[SPARK-17738] [TEST] Fix flaky test in ColumnTypeSuite

### PR DESCRIPTION
**Pull request by davies**
## What changes were proposed in this pull request?

The default buffer size is not big enough for randomly generated MapType.
## How was this patch tested?

Ran the tests in 100 times, it never fail (it fail 8 times before the patch).

### CODE REVIEW

**Comment by davies** [comment]
@zsxwing

**Comment by zsxwing** [comment]
JVM crash?

**Comment by kiszk** [comment]
@davies I appreciate your efforts. I should have noticed this.

**Comment by davies** [comment]
@zsxwing Should I merge this one to make the jenkins happy?

**Comment by zsxwing** [comment]
retest this please.

This one has not yet passed.

**Comment by davies** [comment]
@zsxwing All tests passed in previous try: https://amplab.cs.berkeley.edu/jenkins/job/NewSparkPullRequestBuilder/3317/consoleFull, I kicked another.

**Comment by zsxwing** [comment]
LGTM. Merging to master and 2.0.

**Pull request closed without merging**
