### PR TITLE
[SPARK-5680][SQL] Sum function on all null values, should return zero

### PR DESCRIPTION
**Pull request by gvramana**
SELECT sum('a'), avg('a'), variance('a'), std('a') FROM src;
Should give output as 
0.0 NULL    NULL    NULL
This fixes hive udaf_number_format.q

Author: Venkata Ramana G ramana.gollamudi@huawei.com

### CODE REVIEW

**Comment by marmbrus** [comment]
ok to test

**Comment by rxin** [comment]
The patch is failing style checker. @gvramana can you update it?

**Comment by gvramana** [comment]
Fixed the same. Thanks. Please retest.

**Comment by gvramana** [comment]
Original fix could not distinguish partial sum expression vs no partitions case. Fixed the same now. @marmbrus, @rxin, please review and test. Thanks

**Comment by adrian-wang** [comment]
The only difference of `CombineSumFunction` and `SumFunction` is in `update`, can we just derive `CombineSumFunction` from `SumFunction` and overwrite the `update` function?

**Comment by gvramana** [comment]
Case classes cannot be derived. Making it non-case class will disturb the uniformity. so I left them like that.

**Comment by adrian-wang** [comment]
That makes sense, thanks!

**Comment by gvramana** [comment]
@marmbrus , Please review and merge the same. Thanks

**Comment by marmbrus** [comment]
Perhaps I am missing something, but why do we need a new `CombineSumFunction`?  Can we not just fix the semantics of `SumFunction`?

**Comment by gvramana** [comment]
We need to satisfy 3 cases:
1) sum of all null values = zero
2) Sum for table column with no data = Null
3) sum of column with null and not null values = sum of not null values

i.e.,
<table border=1>
<tr><th>Combining level</th><th>Paritition(s) level</th><th>Input data</th></tr>
<tr><td>Zero </td><td> &lt;-- Zero(f1) </td><td>&lt;-- null <br/> &lt;-- null <br/> &lt;-- null </td></tr>
<tr><td>null(f2)</td><td>&lt;-- null<br/> &lt;-- null <br/> &lt;-- null</td><td> &lt;-- No data <br/>&lt;-- No data<br/> &lt;-- No data</td></tr>
</table>
if same aggregate expression has to work at partition level and combining level. It cannot distinguish between f1 and f2 cases. As there is no way to know "No data" case at combining expression.
So expressions are separated.

**Comment by marmbrus** [comment]
Can you add this explanation to `CombineSumFunction`'s scala doc?

**Comment by gvramana** [comment]
Updated with comments

**Comment by gvramana** [comment]
Rebased

**Comment by marmbrus** [comment]
Thanks!  Merged into master and 1.3.

BTW, the author tag is automatically added by our merge script so you don't need to put it in the description of the PR :)

**Comment by yhuai** [comment]
@gvramana Can you make a pr to make code gen work with Sum? We need to handle ComebineSum at there. `canBeCodeGened` in `HashAggregation` strategy and `GeneratedAggregate` are the places to update. Thanks.

**Comment by yhuai** [comment]
I have created https://issues.apache.org/jira/browse/SPARK-6451.

**Comment by gvramana** [comment]
I will handle the same, thanks

**Comment by gvramana** [comment]
@yhuai, Submitted PR for the code gen with Sum  #5138 . Thanks

**Pull request closed without merging**
