### PR TITLE
[SPARK-24665][PySpark][FollowUp] Use SQLConf in PySpark to manage all sql configs

### PR DESCRIPTION
**Pull request by xuanyuanking**
## What changes were proposed in this pull request?

Follow up for SPARK-24665, find some others hard code during code review.

## How was this patch tested?

Existing UT.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Are they all instances to fix?

**Comment by xuanyuanking** [comment]
```
Are they all instances to fix?
```
@HyukjinKwon Yep, I grep all `conf.get("spark.sql.xxx")` and make sure for this. The remaining of hard code config is StaticSQLConf `spark.sql.catalogImplementation` in session.py, it can't manage by SQLConf.

**Review by HyukjinKwon — APPROVED** [review]
LGTM

**Comment by xuanyuanking** [comment]
Thanks.

**Pull request closed without merging**
