### PR TITLE
[SPARK-48920][BUILD][3.5] Upgrade ORC to 1.9.4

### PR DESCRIPTION
**Pull request by williamhyun**
### What changes were proposed in this pull request?
This PR aims to upgrade ORC to 1.9.4 for Apache Spark 3.5.2.

### Why are the changes needed?
This is the latest version of ORC 1.9.x.
- https://orc.apache.org/news/2024/07/16/ORC-1.9.4/
- https://github.com/apache/orc/releases/tag/v1.9.4

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass the CIs.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by williamhyun** [comment]
cc: @yaooqinn , @dongjoon-hyun

**Review by yaooqinn — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @williamhyun and @yaooqinn .

**Review by HyukjinKwon — APPROVED** [review]

**Comment by williamhyun** [comment]
Thank you, @yaooqinn , @dongjoon-hyun , @HyukjinKwon !

**Comment by dongjoon-hyun** [comment]
Merged to branch-3.5 for Apache Spark 3.5.2. Thank you all!

**Pull request closed without merging**
