### PR TITLE
[SPARK-26606][CORE] Handle driver options properly when submitting to standalone cluster mode via legacy Client

### PR DESCRIPTION
**Pull request by HeartSaVioR**
## What changes were proposed in this pull request?

This patch fixes the issue that ClientEndpoint in standalone cluster doesn't recognize about driver options which are passed to SparkConf instead of system properties. When `Client` is executed via cli they should be provided as system properties, but with `spark-submit` they can be provided as SparkConf. (SpartSubmit will call `ClientApp.start` with SparkConf which would contain these options.)

## How was this patch tested?

Manually tested via following steps:

1) setup standalone cluster (launch master and worker via `./sbin/start-all.sh`) 

2) submit one of example app with standalone cluster mode

```
./bin/spark-submit --class org.apache.spark.examples.SparkPi --master "spark://localhost:7077" --conf "spark.driver.extraJavaOptions=-Dfoo=BAR" --deploy-mode "cluster" --num-executors 1 --driver-memory 512m --executor-memory 512m --executor-cores 1 examples/jars/spark-examples*.jar 10
```

3) check whether `foo=BAR` is provided in system properties in Spark UI

Screen Shot 2019-03-21 at 8 18 04 AM

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
cc. @pwendell @zsxwing

**Comment by HeartSaVioR** [comment]
cc. @vanzin since passing SparkConf here seemed to be introduced by @vanzin

**Review by attilapiros — APPROVED** [review]
LGTM

**Comment by vanzin** [comment]
Well, the lesson I've learned is that no one must use standalone cluster mode. Because there are no tests at all, which makes it super easy to break stuff...

In any case, that's not your fault, so merging to master / 2.4.

**Comment by HeartSaVioR** [comment]
Hmm... if then shouldn't we put some guide to the doc that end users are encouraged to use other mode? End users who use standalone mode are still reporting the bugs they encountered, like [SPARK-15544](https://issues.apache.org/jira/browse/SPARK-15544), and they have no idea standalone mode is soft kind of discouraged one.
(Honestly the issue is actually in my own backlog, but if we don't want to put efforts on standalone mode, I'll drop it.)

**Comment by HeartSaVioR** [comment]
In any way, thanks all for reviewing and merging!

**Comment by vanzin** [comment]
Standalone *cluster* mode doesn't have any tests. Client mode has a bunch (anything that uses `local-cluster[...]` as the master).

**Comment by vanzin** [comment]
Merged to 2.3 also.

**Comment by HeartSaVioR** [comment]
> Standalone cluster mode doesn't have any tests. Client mode has a bunch (anything that uses local-cluster[...] as the master).

Ah! Got your point. Thanks! Still thinking that might worth to guide.

**Comment by dongjoon-hyun** [comment]
Hi, @vanzin and @HeartSaVioR .
Could you check `branch-2.4`? All profiles fail due to the relevant failures. Since we are going to cut rc8 next Monday. This needs an urgent fix.

- https://amplab.cs.berkeley.edu/jenkins/view/Spark%20QA%20Test%20(Dashboard)/job/spark-branch-2.4-test-maven-hadoop-2.6/335/
- https://amplab.cs.berkeley.edu/jenkins/view/Spark%20QA%20Test%20(Dashboard)/job/spark-branch-2.4-test-maven-hadoop-2.7/342/
- https://amplab.cs.berkeley.edu/jenkins/view/Spark%20QA%20Test%20(Dashboard)/job/spark-branch-2.4-test-sbt-hadoop-2.6/333/
- https://amplab.cs.berkeley.edu/jenkins/view/Spark%20QA%20Test%20(Dashboard)/job/spark-branch-2.4-test-sbt-hadoop-2.7/339/

cc @dbtsai since he is a release manger for 2.4.1.

**Comment by dongjoon-hyun** [comment]
Hmm. The followings are the reported failures in the above. But, for me, it works locally. The nest testing is on the way. Let's wait and see the result on Jenkins.
```
Test Result (2 failures / +2)
org.apache.spark.sql.hive.HiveSparkSubmitSuite.set spark.sql.warehouse.dir
org.apache.spark.sql.hive.HiveSparkSubmitSuite.set hive.metastore.warehouse.dir
```

**Comment by vanzin** [comment]
Hmm, if you suspect this change I'll just revert it. I tested some stuff in core but not everything.

Reverting soon.

**Comment by vanzin** [comment]
Done.

**Comment by vanzin** [comment]
(Err, I only saw your first comment Dongjoon, not the update. If the test passes we could revert the revert...)

**Comment by vanzin** [comment]
Those tests seem to run in client mode which shouldn't be affected by this change. Anyway, I'll check this thread again tomorrow.

**Comment by dongjoon-hyun** [comment]
Oh, thank you. I see. I'll keep monitoring this, too.

**Comment by HeartSaVioR** [comment]
I can see the commit reverted in branch-2.4: maybe we can submit PR which reverts the revert and see the build result, and try to fix on that PR if it keeps failing.

**Comment by vanzin** [comment]
That sounds good.

**Comment by HeartSaVioR** [comment]
#24192

**Pull request closed without merging**
