### PR TITLE
SPARK-13461 Delete duplicate example TrainValidationSplitExample.scala

### PR DESCRIPTION
**Pull request by gliptak**
https://issues.apache.org/jira/browse/SPARK-13461

Validated that examples/src/main/scala/org/apache/spark/examples/ml/TrainValidationSplitExample.scala is not referenced.

### CODE REVIEW

**Comment by srowen** [comment]
This isn't all the items from the JIRA right?

**Comment by gliptak** [comment]
@srowen I asked for clarification on the other item listed ...

**Comment by yinxusen** [comment]
@gliptak This JIRA is to find all duplicated example codes for mllib and ml packages, in Scala/Python/Java. So you need to do some research works and find out those duplicates. And also, be careful with those unmerged JIRAs under [SPARK-11337](https://issues.apache.org/jira/browse/SPARK-11337). They may introduce new duplicates.

**Comment by mengxr** [comment]
@yinxusen It doesn't seems feasible to me to find all duplicated examples in all languages in a single PR. Shall we list possible merges first and then group the tasks into a few JIRAs?

**Comment by yinxusen** [comment]
@mengxr Of course. I'll list them.

**Comment by yinxusen** [comment]
@gliptak @mengxr How about we deleting those files listed here https://issues.apache.org/jira/browse/SPARK-14041 directly?

**Comment by yinxusen** [comment]
@gliptak @mengxr Here is an example of scala/examples/ml: https://github.com/apache/spark/pull/12092. You can find all JIRAs here: https://issues.apache.org/jira/browse/SPARK-13461

**Pull request closed without merging**
