### PR TITLE
[SPARK-38324][SQL] The second range is not [0, 59] in the day time ANSI interval

### PR DESCRIPTION
**Pull request by haoyanzhang**
### What changes were proposed in this pull request?
Throw an error when the second value in day(hour, minute) to second interval out of range [0, 59]

### Why are the changes needed?
Currently an invalid second value will not get an error
```
spark.sql("select INTERVAL '10 01:01:99' DAY TO SECOND")
DataFrame[INTERVAL '10 01:02:39' DAY TO SECOND: interval day to second]{}
```
But minute range check is ok
```
spark.sql("select INTERVAL '10 01:60:01' DAY TO SECOND")
requirement failed: minute 60 outside range [0, 59](line 1, pos 16)
```

### We need check second value too

Does this PR introduce any user-facing change?
no

### How was this patch tested?
New unit tests.

### CODE REVIEW

**Comment by MaxGekk** [comment]
@haoyanzhang It is better to create a separate branch per every PR:
Screenshot 2023-02-16 at 12 54 49

see "Pull request" at https://spark.apache.org/contributing.html

**Review by MaxGekk — APPROVED** [review]

**Comment by MaxGekk** [comment]
@haoyanzhang Do you have an account at OSS JIRA: https://issues.apache.org/jira ? If not, I'll create it for you.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by haoyanzhang** [comment]
> @haoyanzhang It is better to create a separate branch per every PR: Screenshot 2023-02-16 at 12 54 49
> 
> see "Pull request" at https://spark.apache.org/contributing.html

got it,  will do it next time

**Comment by haoyanzhang** [comment]
> @haoyanzhang Do you have an account at OSS JIRA: https://issues.apache.org/jira ? If not, I'll create it for you.

I have one, thanks

**Comment by MaxGekk** [comment]
+1, LGTM. Merging to master.
Thank you, @haoyanzhang and @HyukjinKwon for review.

**Comment by MaxGekk** [comment]
@haoyanzhang Congratulations with the first contribution to Apache Spark!

**Pull request closed without merging**
