### PR TITLE
[MINOR][GRAPHX][3.0] Correct typos in the sub-modules: graphx, external, and examples

### PR DESCRIPTION
**Pull request by jsoref**
### What changes were proposed in this pull request?

This PR intends to fix typos in the sub-modules: graphx, external, and examples.
Split per @holdenk https://github.com/apache/spark/pull/30323#issuecomment-725159710

NOTE: The misspellings have been reported at https://github.com/jsoref/spark/commit/706a726f87a0bbf5e31467fae9015218773db85b#commitcomment-44064356

Backport of #30326

### Why are the changes needed?

Misspelled words make it harder to read / understand content.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

No testing was performed

### CODE REVIEW

**Comment by maropu** [comment]
ok to test

**Review by maropu — APPROVED** [review]

**Comment by maropu** [comment]
retest this please

**Comment by maropu** [comment]
retest this please

**Comment by srowen** [comment]
@maropu do you really think we need to backport? that is generally only for bug fixes. It's not a huge deal either way but not sure we should do that in general.

**Comment by jsoref** [comment]
fwiw, the argument in favor of backporting is that it'll make future backports easier, otherwise any fixes past this point (on master) will be harder to backport (because of the changes made by this work on master).

I'm not arguing in favor/opposed (I have no opinion).

**Comment by maropu** [comment]
> @maropu do you really think we need to backport? that is generally only for bug fixes. It's not a huge deal either way but not sure we should do that in general.

Ah, I see. I thought its better to fix [the user-facing typo](https://github.com/apache/spark/pull/30342/files#diff-6035d93511ae47add2aae39bca1dd5375f02b2f9fbe08bd5ac7adbfc933c8f36R49), so I requested to backport it. But, I don't have a strong feeling on it. We don't need it in branch-3.0, @srowen ? if so, we need to revert it in branch-2.4.

**Comment by srowen** [comment]
Oh I see, already in 2.4. OK go ahead and merge it rather than revert. I don't feel strongly either, just know we don't generally backport anything like this as a rule.

**Comment by maropu** [comment]
ok~, thanks for the check, @srowen

**Comment by maropu** [comment]
retest this please

**Comment by maropu** [comment]
Thanks! Merged to branch-3.0.

**Pull request closed without merging**
