### PR TITLE
[WIP][MINOR][INFRA] Increase GitHub Action Maven connectionTimeout

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR increases Maven's `connectionTimeout ` from 1 minute (default) to 3 minutes.

- https://maven.apache.org/guides/mini/guide-http-settings.html#Connection_Timeouts

```xml
<settings>
  <servers>
    <server>
      <id>central</id>
      <configuration>
        <httpConfiguration>
          <all>
            <connectionTimeout>180000</connectionTimeout>
          </all>
        </httpConfiguration>
      </configuration>
    </server>
  </servers>
</settings>
```

### Why are the changes needed?

Although we added Maven cache inside `GitHub Action`, the timeouts happen too frequently.

```
[ERROR] Failed to execute goal on project spark-mllib_2.12:
...
Connection timed out (Read failed) -> [Help 1]
```

### Does this PR introduce any user-facing change?

No.

### How was this patch tested?

This PR is irrelevant to Jenkins result. This should succeed in GitHub Action.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Hi, @HyukjinKwon, @srowen , @wangyum .
Could you review this PR? Currently, `mvn` build timeout occurs at `GitHub Action` job.
This happens when the caches are invalidated. I hope this will recover this flakiness.

**Comment by dongjoon-hyun** [comment]
Oops. It seems that we also need to increase `Connection timedout`.

**Comment by dongjoon-hyun** [comment]
Hi, @maropu . Could you review this PR, please?

**Comment by maropu** [comment]
Oh! closed?

**Comment by dongjoon-hyun** [comment]
Oops. Sorry, I didn't notice you came to my PR. Here, I tried three approaches but there was no luck. I moved to my personal repository to test this. I'll came back with a verified solution.
- https://github.com/dongjoon-hyun/spark/pull/11

Thank you, @maropu !

**Comment by dongjoon-hyun** [comment]
The last run here (with 3 min limit) is still running. But, I guess I need to repeat multiple times to verify this.
- https://github.com/apache/spark/commit/35920881a2c44a1fba6b0a6d3c28116fcedd6ac5/checks?check_suite_id=346818032

**Comment by dongjoon-hyun** [comment]
And, `master` branch came back with `green` with your last commit. So, it seems that the rush-hour time congestion goes away. :)
- https://github.com/apache/spark/commit/e88d74052bf40eabab9e3388fa09e52097ffa3aa

**Comment by maropu** [comment]
hahaha, I see. Nice.

**Review by srowen — COMMENTED** [review]
Looks OK if it helps.

**Comment by dongjoon-hyun** [comment]
Hi, All.
I made a PR for this.
- https://github.com/apache/spark/pull/26793

**Pull request closed without merging**
