### PR TITLE
[SPARK-43344][BUILD] Upgrade `mlflow` to 2.3.1

### PR DESCRIPTION
**Pull request by bjornjorgensen**
### What changes were proposed in this pull request?
Upgrade `mlflow` >=1.0 from to >=2.3.1

[Release notes](https://github.com/mlflow/mlflow/releases)

### Why are the changes needed?
[Access Restriction Bypass](https://security.snyk.io/vuln/SNYK-PYTHON-MLFLOW-5490116)
CVE NOT AVAILABLE

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Could you update this part too?

https://github.com/apache/spark/blob/a1c7035294ecdc10f507c58a41cb0ed7137717ca/dev/infra/Dockerfile#L68

cc @HyukjinKwon , @xinrong-meng , @Yikun too

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

cc @HyukjinKwon

**Review by HyukjinKwon — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @bjornjorgensen and @HyukjinKwon .
Merged to master for Apache Spark 3.5.0.

**Comment by xinrong-meng** [comment]
Thank you @bjornjorgensen @dongjoon-hyun !

**Pull request closed without merging**
