### PR TITLE
[SPARK-49733][SQL][DOCS] Delete `ExpressionInfo[between]` from `gen-sql-api-docs.py` to avoid duplication

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to delete `ExpressionInfo[between]` from `gen-sql-api-docs.py` to avoid duplication.

### Why are the changes needed?
- In the following doc, `between` is repeatedly displayed `twice`
  https://spark.apache.org/docs/preview/api/sql/index.html#between
  image

After the pr:
image

- After https://github.com/apache/spark/pull/44299, the expression 'between' has been added to `Spark 4.0`.

### Does this PR introduce _any_ user-facing change?
Yes, only for docs.

### How was this patch tested?
Manually check.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Review by MaxGekk — COMMENTED** [review]
Should we preserve the version in `since`: `1.0.0`?

**Comment by panbingkun** [comment]
> Should we preserve the version in `since`: `1.0.0`?

That makes sense, let me update it.

**Comment by panbingkun** [comment]
> Should we preserve the version in `since`: `1.0.0`?

Updated, thanks!

**Comment by MaxGekk** [comment]
I believe [Run / Run Docker integration tests](https://github.com/panbingkun/spark/actions/runs/10957994215/job/30427318577#logs) is not related to the changes.

+1, LGTM. Merging to master.
Thank you, @panbingkun.

**Review by MaxGekk — APPROVED** [review]

**Pull request closed without merging**
