### PR TITLE
[SPARK-15153] [ML] [SparkR] Fix SparkR spark.naiveBayes error when label is numeric type

### PR DESCRIPTION
**Pull request by yanboliang**
## What changes were proposed in this pull request?

Fix SparkR `spark.naiveBayes` error when response variable of dataset is numeric type.
See details and how to reproduce this bug at [SPARK-15153](https://issues.apache.org/jira/browse/SPARK-15153).
## How was this patch tested?

Add unit test.

### CODE REVIEW

**Comment by yanboliang** [comment]
cc @mengxr @jkbradley

**Comment by mengxr** [comment]
Is it okay to always cast the target label column to string?

**Comment by yanboliang** [comment]
It's feasible to always cast the target label column to string, but we should refactor ```RFormula```. ```RFormula``` handles label of numeric type and string type differently, we should unified them. But I'm not sure whether we can finish that before 2.0.

**Comment by felixcheung** [comment]
Do we still need this?

**Comment by jkbradley** [comment]
It's still a problem.  (I just tried the unit test on master.)  Sorry for the delay @yanboliang !

**Comment by felixcheung** [comment]
Should/Would this be better if this is handled in the RFormula level? I could see other models could benefit from this too, in addition to just R.

**Comment by jkbradley** [comment]
Oh!  Now I see the JIRA's linked JIRA.  I agree that updating RFormula is a better solution and that we can close this PR.  I'll check out the other PR.

**Comment by yanboliang** [comment]
Move the new fix to #15431 which leverages ```RFormula forceIndexLabel```, more succinct.

**Pull request closed without merging**
