### PR TITLE
[SPARK-12479] [SPARKR] collect on GroupedData throws R error 'missing val…

### PR DESCRIPTION
**Pull request by paulomagalhaes**
sparkR collect on GroupedData throws R error "missing value where TRUE/FALSE needed" see SPARK-12479 for details

### CODE REVIEW

**Comment by sun-rui** [comment]
Could you rename your PR's title to "[SPARK-12479][SPARKR] ..." to follow Spark style?

Your PR is a workaround, but we'd better to exactly simulate the string hashcode algorithm as that in Java:
```
            for (int i = 0; i < value.length; i++) {
                h = 31 * h + val[i];
            }
```
The problem is that I found it difficult( or impossible?) to handle integer overflow in base R without resorting to some 3rd party packages.

If we simply use val * 31 + addval, no way to extract the lowest 32 bits from a numeric into an integer?

If we use bitwShiftL as right row, bitwShiftL will produce NA if the shifted value has integer overflow.
```
> bitwShiftL(0x20000000L, 2L)
[1] NA
```
so even the following trick does not work
```
  val <- c(bitwAnd(val, c(0x0FFFFFFFL, 0x1FFFFFFFL, 0x3FFFFFFFL, 0x7FFFFFFFL)),
           val)
  vec <- c(bitwShiftL(val, c(4,3,2,1,0)), addVal)
```

**Comment by shivaram** [comment]
@paulomagalhaes Any updates on this PR ? Would be good to have a fix for this problem.

**Comment by paulomagalhaes** [comment]
@shivaram PR renamed.

**Comment by shivaram** [comment]
@paulomagalhaes Sorry for the delay in getting back. Does the current code change fix the problem you were seeing ? It would be good to add a unit test as well for this change.

**Comment by shivaram** [comment]
@sun-rui Do you think the existing PR fixes the problem described in the JIRA ? I'm wondering if we should target this for Spark 2.0

**Comment by sun-rui** [comment]
@shivaram, we can merge this PR first, and submit a new JIRA for long-term solution.

**Comment by shivaram** [comment]
Thanks @sun-rui for taking a look. I think @paulomagalhaes is busy -- Can you open a new PR with this fix that we can run through Jenkins ?

**Comment by sun-rui** [comment]
@shivaram, re-submitted PR at https://github.com/apache/spark/pull/12976

**Comment by sun-rui** [comment]
@paulomagalhaes, could you close this PR? thanks

**Comment by paulomagalhaes** [comment]
closed

**Pull request closed without merging**
