### PR TITLE
[SPARK-21548][SQL] "Support insert into serial columns of table"

### PR DESCRIPTION
**Pull request by lvdongr**
## What changes were proposed in this pull request?
When we use the 'insert into ...' statement we can only insert all the columns into table.But int some cases,our table has many columns and we are only interest in some of them.So we want to support the statement "insert into table tbl (column1, column2,...) values (value1, value2, value3,...)".
https://issues.apache.org/jira/browse/SPARK-21548

## How was this patch tested?
unit tests, integration tests, manual tests

Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Comment by maropu** [comment]
@lvdongr Could you add tests?
@gatorsmile Could you trigger jenkins?

**Comment by gatorsmile** [comment]
ok to test

**Comment by gatorsmile** [comment]
@lvdongr @maropu After a quick look, I found the PR is still far from what we can merge. 

@maropu Could you help @lvdongr address all the issues you can find?

**Comment by maropu** [comment]
@gatorsmile Thanks for the trigger! Yea, I'll check first, then I'll ping you.

**Comment by maropu** [comment]
@lvdongr Could you first add tests and pass all these tests in jenkins? Thanks!

**Comment by gatorsmile** [comment]
We do not have default values, right? I still do not understand the issue we try to address.

**Comment by maropu** [comment]
I think this ticket just targets to support a new syntax in `INSERT` like;
```
scala> sql("create table b2(a int, b double, c string)")
scala> sql("insert into b2 values (1, 3.8, 'a')")
scala> sql("insert into b2(a, c) values (2, 'b')") <-- not supported in the master
org.apache.spark.sql.catalyst.parser.ParseException:
mismatched input 'a' expecting {'(', 'SELECT', 'FROM', 'VALUES', 'TABLE', 'INSERT', 'MAP', 'REDUCE'}(line 1, pos 15)

== SQL ==
insert into b2(a, c) values (2, 'b')
---------------^^^

  at org.apache.spark.sql.catalyst.parser.ParseException.withCommand(ParseDriver.scala:217)
  at org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parse(ParseDriver.scala:114)
  at org.apache.spark.sql.execution.SparkSqlParser.parse(SparkSqlParser.scala:48)
  at org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parsePlan(ParseDriver.scala:68)
  at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:623)
  ... 48 elided
```

**Comment by lvdongr** [comment]
Thank you for review, I will finish the tests as soon as possible.

**Comment by gatorsmile** [comment]
I see. This PR still requires users to provide all the columns, right?

**Comment by maropu** [comment]
I'm still not looking into this pr though, IMHO it would be good for users to select parts of columns like other databases;
```
postgres=# create table t(a int, b text, c float8, d int);

postgres=# insert into t(a, c) values (1, 0.8);
INSERT 0 1

postgres=# select * from t;
 a | b |  c  | d 
---+---+-----+---
 1 |   | 0.8 |  
(1 row)
```

**Comment by maropu** [comment]
I think this pr should be fixed in that way, maybe.

**Comment by lvdongr** [comment]
The target of this pr is support  to insert into specified  columns， all  columns is  no need ， like   insert into t(a, c) values (1, 0.8) .

**Comment by lvdongr** [comment]
You can see this picture,my table has three columns,and I insert only two columns, then the last column is null.  @maropu @gatorsmile 
insertinto

**Comment by gatorsmile** [comment]
This might not be applicable to Spark SQL, because we do not have a concept of DEFAULT VALUE. 
```
column_definition:
    data_type [NOT NULL | NULL] [DEFAULT default_value]
```

**Comment by maropu** [comment]
In the most cases of `SELECT` statements,  `default_value` is `NULL` by default. So, I firstly thought non-specified columns were filled with `NULL`. Anyway, we still have any chance to implement the concept of `DEFAULT`, too?
```
postgresql doc:
DEFAULT default_expr
...
The default expression will be used in any insert operation that does not specify a value 
for the column. If there is no default for a column, then the default is null.
```

**Comment by lvdongr** [comment]
You mean we can provide the different type of values with  different default values? like  int  with 0 ,and string with "" ?Or we set the default values when define the table?  @gatorsmile @maropu  I set the default to Null ,because the "insert into ..." sentence in hive handle in this way, and I want to correspond with Hive.

**Comment by lvdongr** [comment]
ok, I will solve the problems left first, and hold  this PR @gatorsmile.

**Comment by maropu** [comment]
@lvdongr Any progress on this?

**Comment by lvdongr** [comment]
Execute me ,has the concept of default value been introduce to schema in master branch? @gatorsmile thank you.

**Comment by gatorsmile** [comment]
@lvdongr We still do not have a bandwidth to work on this issue. Could you open a JIRA and ask the community for helping this? We need a design discussion before starting the work.

**Comment by maropu** [comment]
Closing this due to author's inactivity

**Pull request closed without merging**
