### PR TITLE
[SPARK-14347] [WIP] Require Java 8 for Spark 2.x

### PR DESCRIPTION
**Pull request by srowen**
(Just a WIP for now)
## What changes were proposed in this pull request?
- Require Java 8
- Remove MaxPermSize settings
- Move Java 8 tests into main modules
- Update references to Java 8 in docs
- ... more still needs to be done
## How was this patch tested?

Jenkins tests

### CODE REVIEW

**Comment by rxin** [comment]
Hey Sean - not sure if you saw the dev list email I sent. After thinking about it a lot more, I am not sure if we want to do this. It's a pretty big impediment to people upgrading, and way more aggressive than what we did with Java 6.

**Comment by srowen** [comment]
Yeah I put this out since @lresende was going to start it and was putting out my WIP. Let's keep discussion on dev@. I appreciate your position, but I am not seeing agreement with it. Are you already just vetoing?

**Comment by rxin** [comment]
Yes.

**Comment by jodersky** [comment]
@srowen, @rxin considering the discussions around the matter, should this pr be closed?

**Comment by srowen** [comment]
Yeah I'll close the PR, it was just a WIP anyway. While I disagree with the veto (see dev@ thread), I can't stop someone from doing that. I disagree that there is "far from consensus", which is the essence of the problem here.

**Pull request closed without merging**
