### PR TITLE
[SPARK-21258][SQL] Fix WindowExec complex object aggregation with spilling

### PR DESCRIPTION
**Pull request by hvanhovell**
## What changes were proposed in this pull request?
`WindowExec` currently improperly stores complex objects (UnsafeRow, UnsafeArrayData, UnsafeMapData, UTF8String) during aggregation by keeping a reference in the buffer used by `GeneratedMutableProjections` to the actual input data. Things go wrong when the input object (or the backing bytes) are reused for other things. This could happen in window functions when it starts spilling to disk. When reading the back the spill files the `UnsafeSorterSpillReader` reuses the buffer to which the `UnsafeRow` points, leading to weird corruption scenario's. Note that this only happens for aggregate functions that preserve (parts of) their input, for example `FIRST`, `LAST`, `MIN` & `MAX`.

This was not seen before, because the spilling logic was not doing actual spills as much and actually used an in-memory page. This page was not cleaned up during window processing and made sure unsafe objects point to their own dedicated memory location. This was changed by https://github.com/apache/spark/pull/16909, after this PR Spark spills more eagerly.

This PR provides a surgical fix because we are close to releasing Spark 2.2. This change just makes sure that there cannot be any object reuse at the expensive of a little bit of performance. We will follow-up with a more subtle solution at a later point.

## How was this patch tested?
Added a regression test to `DataFrameWindowFunctionsSuite`.

### CODE REVIEW

**Comment by gatorsmile** [comment]
LGTM @liancheng @cloud-fan

**Comment by liancheng** [comment]
LGTM pending Jenkins.

**Comment by cloud-fan** [comment]
retes this please

**Comment by cloud-fan** [comment]
retest this please

**Comment by cloud-fan** [comment]
LGTM

**Comment by cloud-fan** [comment]
thanks, merging to master/2.2/2.1!

**Comment by zzcclp** [comment]
Hi, @cloud-fan , @hvanhovell , after merging this pr into **branch-2.1**, there are some errors:
1.
`value WINDOW_EXEC_BUFFER_SPILL_THRESHOLD is not a member of object org.apache.spark.sql.internal.SQLConf`

2.
`overloaded method value json with alternatives:   (jsonRDD: org.apache.spark.rdd.RDD[String])org.apache.spark.sql.DataFrame <and>   (jsonRDD: org.apache.spark.api.java.JavaRDD[String])org.apache.spark.sql.DataFrame <and>   (paths: String*)org.apache.spark.sql.DataFrame <and>   (path: String)org.apache.spark.sql.DataFrame  cannot be applied to (org.apache.spark.sql.Dataset[String])`

**Comment by cloud-fan** [comment]
ah the spilling logic is not in 2.1, let me revert it, sorry for the trouble.

**Pull request closed without merging**
