### PR TITLE
[CORE][MINOR] Whitespace fixes in RangePartitioner

### PR DESCRIPTION
**Pull request by ihainan**
Just a trivial change so I didn't create a corresponding JIRA issue.

### CODE REVIEW

**Comment by srowen** [comment]
I think this is too trivial even for a PR. This doesn't fail style checks right? this isn't worth everyone's cycles.

**Comment by ihainan** [comment]
@srowen Thanks for your suggestion. 

There was a [similar commit](https://github.com/apache/spark/commit/7f7505d8db7759ea46e904f767c23130eff1104a) before and I just want to make the code more consistent.

**Comment by srowen** [comment]
Yes, I think that commit was to pass style checks though. I assume this doesn't fail anything? I mean, I don't mind just merging this, but in my personal opinion I'd like to lightly push back on very small non-functional changes.

**Comment by srowen** [comment]
Why reopened?

**Pull request closed without merging**
