### PR TITLE
[SPARK-10706] [MLLIB] Add java wrapper for random vector rdd

### PR DESCRIPTION
**Pull request by rotationsymmetry**
Add java wrapper for random vector rdd

@holdenk @srowen

### CODE REVIEW

**Comment by holdenk** [comment]
This LGTM, @srowen can hopefully take a look too.

**Comment by srowen** [comment]
LGTM

**Comment by srowen** [comment]
Sorry @rotationsymmetry, some conflicts now -- can you rebase and force push?

**Comment by rotationsymmetry** [comment]
@srowen I have rebased and pushed the PR. Thanks!

cc @holdenk

**Pull request closed without merging**
