### PR TITLE
[WIP][HOTFIX][SPARK-4123]: Fix bug in PR dependency (all deps. removed issue)

### PR DESCRIPTION
**Pull request by brennonyork**
We're seeing a bug sporadically in the new PR dependency comparison test whereby it notes that _all_ dependencies are removed. This happens when the current PR is built, but the final, sorted, dependency file is left blank. I believe this is an error either in the way the `git checkout` calls have been or an error within the `mvn` build for that PR (again, likely related to the `git checkout`). As such I've set the checkouts to now force (with `-f` flag) which is more in line with what Jenkins currently does on the initial checkout.

Setting this as a WIP for now to trigger the build process myriad times to see if the issue still arises.

### CODE REVIEW

**Comment by brennonyork** [comment]
jenkins, retest this please

**Comment by pwendell** [comment]
@brennonyork let me know when this is not WIP and I'll take a look. Seems like you are still testing a bit.

**Comment by brennonyork** [comment]
@shaneknapp can you help me understand how Jenkins is doing the checkouts? I'm seeing the PR builder outputting:

```
Building remotely on amp-jenkins-worker-06 (centos) in workspace /home/jenkins/workspace/SparkPullRequestBuilder
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/apache/spark.git # timeout=10
Fetching upstream changes from https://github.com/apache/spark.git
 > git --version # timeout=10
 > git fetch --tags --progress https://github.com/apache/spark.git +refs/pull/5443/*:refs/remotes/origin/pr/5443/* # timeout=15
 > git rev-parse origin/pr/5443/merge^{commit} # timeout=10
 > git branch -a --contains c5916336e6aff94dd3abfc9a0a41a2528c765fce # timeout=10
 > git rev-parse remotes/origin/pr/5443/merge^{commit} # timeout=10
Checking out Revision c5916336e6aff94dd3abfc9a0a41a2528c765fce (origin/pr/5443/merge)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f c5916336e6aff94dd3abfc9a0a41a2528c765fce
```

although I'm a bit confused what checkout I should switch between if, say, I want to, from a PR, checkout the `master` branch, then switch back to the given PR branch, then possibly back to `master`, and finally back to the PR again.

I'm currently doing what I believe is correct [here](https://github.com/apache/spark/blob/master/dev/tests/pr_new_dependencies.sh#L42) although there are times when the checkout from `master` back to the current PR fails, producing odd dependency reports. I've noticed that Jenkins is using the `-f` flag which I've added, but wanted to see if you had any thoughts into the matter.

Further, I've added `echo` statements to dump the `ghprbActualCommit`, the `sha1`, and the output of `git rev-parse HEAD`. Each are different commit hashes which makes me further think this is the cause for all the errors. Again, any advice?

**Comment by pwendell** [comment]
I think you may need to look at the source code to figure out what is going on:

https://github.com/jenkinsci/ghprb-plugin/blob/master/src/main/java/org/jenkinsci/plugins/ghprb/GhprbTrigger.java#L156

The current set of changes seem pretty straightforward, so maybe I can merge this now to see if the "-f" helps.

**Pull request closed without merging**
