### PR TITLE
[SPARK-38042][SQL] Ensure that ScalaReflection.dataTypeFor works on aliased array types

### PR DESCRIPTION
**Pull request by jtnystrom**
An aliased array type in a product, in a Dataset or Dataframe, causes an exception:

```
type Data = Array[Long]
val xs:List[(Data,Int)] = List((Array(1),1), (Array(2),2))
sc.parallelize(xs).toDF("a", "b")
```

Causing

```
scala.MatchError: Data (of class scala.reflect.internal.Types$AliasNoArgsTypeRef) 
 at org.apache.spark.sql.catalyst.ScalaReflection$.$anonfun$dataTypeFor$1(ScalaReflection.scala:104) 
 at scala.reflect.internal.tpe.TypeConstraints$UndoLog.undo(TypeConstraints.scala:69) 
 at org.apache.spark.sql.catalyst.ScalaReflection.cleanUpReflectionObjects(ScalaReflection.scala:904) 
 at org.apache.spark.sql.catalyst.ScalaReflection.cleanUpReflectionObjects$(ScalaReflection.scala:903) 
 at org.apache.spark.sql.catalyst.ScalaReflection$.cleanUpReflectionObjects(ScalaReflection.scala:49) 
 at org.apache.spark.sql.catalyst.ScalaReflection$.dataTypeFor(ScalaReflection.scala:88) 
 at org.apache.spark.sql.catalyst.ScalaReflection$.$anonfun$serializerFor$6(ScalaReflection.scala:573) 
 at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238) 
 at scala.collection.immutable.List.foreach(List.scala:392) 
 at scala.collection.TraversableLike.map(TraversableLike.scala:238) 
 at scala.collection.TraversableLike.map$(TraversableLike.scala:231) 
 at scala.collection.immutable.List.map(List.scala:298) 
 at org.apache.spark.sql.catalyst.ScalaReflection$.$anonfun$serializerFor$1(ScalaReflection.scala:562) 
 at scala.reflect.internal.tpe.TypeConstraints$UndoLog.undo(TypeConstraints.scala:69) 
 at org.apache.spark.sql.catalyst.ScalaReflection.cleanUpReflectionObjects(ScalaReflection.scala:904) 
 at org.apache.spark.sql.catalyst.ScalaReflection.cleanUpReflectionObjects$(ScalaReflection.scala:903) 
 at org.apache.spark.sql.catalyst.ScalaReflection$.cleanUpReflectionObjects(ScalaReflection.scala:49) 
 at org.apache.spark.sql.catalyst.ScalaReflection$.serializerFor(ScalaReflection.scala:432) 
 at org.apache.spark.sql.catalyst.ScalaReflection$.$anonfun$serializerForType$1(ScalaReflection.scala:421) 
 at scala.reflect.internal.tpe.TypeConstraints$UndoLog.undo(TypeConstraints.scala:69) 
 at org.apache.spark.sql.catalyst.ScalaReflection.cleanUpReflectionObjects(ScalaReflection.scala:904) 
 at org.apache.spark.sql.catalyst.ScalaReflection.cleanUpReflectionObjects$(ScalaReflection.scala:903) 
 at org.apache.spark.sql.catalyst.ScalaReflection$.cleanUpReflectionObjects(ScalaReflection.scala:49) 
 at org.apache.spark.sql.catalyst.ScalaReflection$.serializerForType(ScalaReflection.scala:413) 
 at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder$.apply(ExpressionEncoder.scala:55) 
 at org.apache.spark.sql.Encoders$.product(Encoders.scala:285) 
 at org.apache.spark.sql.LowPrioritySQLImplicits.newProductEncoder(SQLImplicits.scala:251) 
 at org.apache.spark.sql.LowPrioritySQLImplicits.newProductEncoder$(SQLImplicits.scala:251) 
 at org.apache.spark.sql.SQLImplicits.newProductEncoder(SQLImplicits.scala:32) 
 ... 48 elided
```

It seems that this can be fixed by changing, in ScalaReflection.dataTypeFor:

```
val TypeRef(_, _, Seq(elementType)) = tpe
```

to

```
val TypeRef(_, _, Seq(elementType)) = tpe.dealias
```

### Why are the changes needed?

Without this change, any attempt to create datasets or dataframes using such types throws the exception above.

### Does this PR introduce _any_ user-facing change?

No, except for preventing this exception from being thrown.

### How was this patch tested?

Added a test to DatasetSuite

### CODE REVIEW

**Comment by jtnystrom** [comment]
Just in case, pinging @cloud-fan and @marmbrus, who edited this method in the past.

**Comment by HyukjinKwon** [comment]
This actually looks making sense to me.

**Comment by HyukjinKwon** [comment]
cc @viirya FYI

**Review by HyukjinKwon — COMMENTED** [review]
This change looks good to me. cc @zsxwing or @JoshRosen too in case you guys have some comments.

**Review by HyukjinKwon — APPROVED** [review]
LGTM

**Comment by cloud-fan** [comment]
thanks, merging to master/3.2!

**Review by dongjoon-hyun — COMMENTED** [review]
+1, late LGTM. Thank you, @jtnystrom and all!

**Comment by jtnystrom** [comment]
Thank you for reviewing!

**Pull request closed without merging**
