### PR TITLE
[SPARK-48791][CORE][3.5] Fix perf regression caused by the accumulators registration overhead using CopyOnWriteArrayList

### PR DESCRIPTION
**Pull request by Ngone51**
This PR backports https://github.com/apache/spark/pull/47197 to branch-3.5.

### What changes were proposed in this pull request?

This PR proposes to use the `ArrayBuffer` together with the read/write lock rather than `CopyOnWriteArrayList` for `TaskMetrics._externalAccums`.

### Why are the changes needed?

Fix the perf regression that caused by the accumulators registration overhead using `CopyOnWriteArrayList`.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Manually tested.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Review by yaooqinn — APPROVED** [review]

**Review by LuciferYang — APPROVED** [review]
LGTM if the test passes

**Comment by LuciferYang** [comment]
```
Error: ] /home/runner/work/spark/spark/core/src/main/scala-2.12/org/apache/spark/util/ArrayImplicits.scala:20: object compat is not a member of package collection
Error: ] /home/runner/work/spark/spark/core/src/main/scala-2.12/org/apache/spark/util/ArrayImplicits.scala:32: not found: value immutable
Error: ] /home/runner/work/spark/spark/core/src/main/scala-2.12/org/apache/spark/util/ArrayImplicits.scala:33: not found: value immutable
Error: [ERROR] three errors found
Error:  Failed to execute goal net.alchim31.maven:scala-maven-plugin:4.8.0:compile (scala-compile-first) on project spark-core_2.12: Execution scala-compile-first of goal net.alchim31.maven:scala-maven-plugin:4.8.0:compile failed: org.apache.commons.exec.ExecuteException: Process exited with an error: 255 (Exit value: 255) -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
Error:  
Error:  After correcting the problems, you can resume the build with the command
Error:    mvn <args> -rf :spark-core_2.12
Error: Process completed with exit code 1.
```
Maven build failed.

Looking at the dependency tree, `scala-collection-compat` is a cascading dependency of `org.scalanlp:breeze`, but the core module does not depend on `org.scalanlp:breeze`. I recommend explicitly managing the version of `scala-collection-compat` and adding it to the core module. This will not introduce any additional dependencies for Spark, as it is already included in the `spark-deps-hadoop-3-hive-2.3` list.

**Comment by dongjoon-hyun** [comment]
Thank you for making a PR for old release branches. Could you make a separate PR for `branch-3.4` to make it sure that CI passes?

**Comment by Ngone51** [comment]
FYI opned a separate PR for `branch-3.4`: https://github.com/apache/spark/pull/47348.

**Review by LuciferYang — APPROVED** [review]

**Review by yaooqinn — APPROVED** [review]

**Comment by Ngone51** [comment]
`Scala 2.13 build with SBT` failed:
```
[error] /home/runner/work/spark/spark/mllib-local/src/main/scala/org/apache/spark/ml/stat/distribution/MultivariateGaussian.scala:117:34: Symbol 'type scala.collection.compat.package.IterableOnce' is missing from the classpath.
[error] This symbol is required by 'type breeze.linalg.support.LowPrioCanTraverseValues.X'.
[error] Make sure that type IterableOnce is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[error] A full rebuild may help if 'LowPrioCanTraverseValues.class' was compiled against an incompatible version of scala.collection.compat.package.
[error]     val tol = Utils.EPSILON * max(d) * d.length
[error]                                  ^
[error] one error found
```

@LuciferYang Do you have any idea why `mllib` module doesnt't have the depdency of `scala-collection-compat` since we have already directly managed that dependecy in `core` module?  
```
[INFO] --- dependency:3.6.0:tree (default-cli) @ spark-mllib_2.13 ---
[INFO] org.apache.spark:spark-mllib_2.13:jar:3.5.2-SNAPSHOT
[INFO] +- org.scala-lang.modules:scala-parser-combinators_2.13:jar:2.3.0:compile
[INFO] +- org.apache.spark:spark-core_2.13:jar:3.5.2-SNAPSHOT:compile
[INFO] |  \- org.scala-lang.modules:scala-xml_2.13:jar:2.1.0:compile
[INFO] \- org.scala-lang.modules:scala-parallel-collections_2.13:jar:1.0.4:compile
```

**Comment by dongjoon-hyun** [comment]
Thank you for making a PR for 3.4, @Ngone51 .  BTW, yes, Scala 2.13 failure seems to be consistent in both 3.5 and 3.4.

**Comment by dongjoon-hyun** [comment]
Given that `branch-3.4` PR works, could you re-trigger CI, @Ngone51 ?

**Review by LuciferYang — APPROVED** [review]

**Comment by cloud-fan** [comment]
thanks, merging to 3.5!

**Pull request closed without merging**
