### PR TITLE
[SPARK-42779][SQL][FOLLOWUP] Allow V2 writes to indicate advisory shuffle partition size

### PR DESCRIPTION
**Pull request by aokolnychyi**
### What changes were proposed in this pull request?

This PR addresses non-blocking comments for PR #40421.

### Why are the changes needed?

These changes are needed to make sure the new logic only applies in expected cases.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by aokolnychyi** [comment]
cc @cloud-fan @dongjoon-hyun

**Review by dongjoon-hyun — APPROVED** [review]
Thank you for making a followup, @aokolnychyi .

+1, LGTM from my side. I'll leave this to @cloud-fan because this is his request.

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Comment by dongjoon-hyun** [comment]
Thank you, @cloud-fan !

**Comment by aokolnychyi** [comment]
Thanks, @dongjoon-hyun @cloud-fan!

**Pull request closed without merging**
