### PR TITLE
[SPARK-10695] [Documentation][Mesos] Fixing incorrect value informati…

### PR DESCRIPTION
**Pull request by SleepyThread**
…on for spark.mesos.constraints parameter.

### CODE REVIEW

**Comment by ash211** [comment]
Jenkins, test this please.

**Comment by rxin** [comment]
Docs are not built by Jenkins so there is no need to run Jenkins here.

**Comment by rxin** [comment]
cc @tnachen

**Comment by andrewor14** [comment]
Oops that looked wrong. Merging this into master 1.5 thanks for catching this.

**Pull request closed without merging**
