### PR TITLE
[MINOR][CORE] Update Hadoop dependencies to 2.7.7

### PR DESCRIPTION
**Pull request by srowen**
## What changes were proposed in this pull request?

Update Hadoop dependencies from 2.7.4 to 2.7.7. I doubt the bug fixes are relevant; 2.7.7 addressed a CVE (https://hadoop.apache.org/release/2.7.7.html) which again may not affect Spark, but it's a pretty zero-cost update to what's probably the last 2.7.x release.

## How was this patch tested?

Existing tests.

### CODE REVIEW

**Review by viirya — APPROVED** [review]

**Review by dongjoon-hyun — COMMENTED** [review]
Hi, @srowen . Maybe, this is not using JIRA issue because of security issue.

However, SPARK-25015(Update Hadoop 2.7 to 2.7.7) did this and was reverted by SPARK-25330 (Revert Hadoop 2.7 to 2.7.3) due to permission issue.

Since SPARK-25015 is created by you and SPARK-25330 is committed by you, I'm wondering if that permission issue is resolved now. Are we okay with that?

cc @wangyum since he is the author of SPARK-25330.

**Comment by viirya** [comment]
I read through related comments in Hadoop and Hive. IMHO, we should address the issue after upgrading like Hive, because it is an intentional behavior in Hadoop.

**Comment by dongjoon-hyun** [comment]
If this is **required** to address some issues, `[MINOR]` looks wrong to me. Shall we use SPARK-25015 again?

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
If you don't mind, it would be better have a JIRA ID in the title, @srowen . This looks important.

**Comment by srowen** [comment]
Ah, disregard this. I had forgotten about this sequence of issues already. I had this feeling I'd seen this update before when making it but failed to check JIRA.

**Comment by dongjoon-hyun** [comment]
Oh, I see. Thank you for closing this, @srowen .

**Pull request closed without merging**
