### PR TITLE
[MINOR] Fix typos in comments and replace an explicit type with <>

### PR DESCRIPTION
**Pull request by younggyuchun**
## What changes were proposed in this pull request?
This PR fixed typos in comments and replace the explicit type with '<>' for Java 8+.

## How was this patch tested?
Manually tested.

### CODE REVIEW

**Review by srowen — APPROVED** [review]
I'm OK with cleanup like this for 3.0. Are they any more instances of redundant generic types? We can get them all here.

**Comment by younggyuchun** [comment]
> I'm OK with cleanup like this for 3.0. Are they any more instances of redundant generic types? We can get them all here.

I have added more redundant generic types.

**Comment by younggyuchun** [comment]
added all redundant generic types here.

**Comment by younggyuchun** [comment]
@srowen Could you please review this please?

**Comment by srowen** [comment]
Merged to master

**Comment by younggyuchun** [comment]
@srowen Thank you.

**Pull request closed without merging**
