### PR TITLE
Revert "[SPARK-37670][SQL] Support predicate pushdown and column pruning for de-duped CTEs"

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This reverts 1a356858577aa13012f56fdd4b41f8ea6fe230ce except [transformDownWithSubqueries](https://github.com/apache/spark/blob/125555cf2c1388b28fcc34beae09f971c5fadcb7/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/plans/QueryPlan.scala#L486-L510) because SPARK-39259 starts to use it.
- https://github.com/apache/spark/pull/36654
- https://github.com/apache/spark/pull/36765 (Rename transformDownWithSubqueries  to transformDownWithSubqueriesAndPruning)

### Why are the changes needed?

Currently, `branch-3.2` is broken.
- https://github.com/apache/spark/commits/branch-3.2

Screen Shot 2022-06-08 at 7 25 46 PM

Screen Shot 2022-06-08 at 7 25 55 PM

Here is the AS-IS result generation status.
- Although #34929 generates the result with `SPARK_GENERATE_GOLDEN_FILES=1 build/sbt "sql/testOnly *PlanStabilitySuite"`. It causes failure at GitHub Action in branch-3.2.
```
$ SPARK_GENERATE_GOLDEN_FILES=1 build/sbt "sql/testOnly *PlanStabilitySuite" &> /dev/null
$ git status
On branch branch-3.2
Your branch is up to date with 'apache/branch-3.2'.

nothing to commit, working tree clean
```

- In addition, the result is different when we run the test individually.
```
$ SPARK_GENERATE_GOLDEN_FILES=1 build/sbt "sql/testOnly *PlanStabilitySuite -- -z (tpcds-v1.4/q4)" &> /dev/null
$ SPARK_GENERATE_GOLDEN_FILES=1 build/sbt "sql/testOnly *PlanStabilitySuite -- -z (tpcds-v1.4/q5)" &> /dev/null
$ git diff --stat
 sql/core/src/test/resources/tpcds-plan-stability/approved-plans-v1_4/q4/explain.txt | 238 ++++++++++++++++++++++++++++++++++++++++++++++++++++----------------------------------------------------
 sql/core/src/test/resources/tpcds-plan-stability/approved-plans-v1_4/q5/explain.txt | 212 ++++++++++++++++++++++++++++++++++++++++++++++----------------------------------------------
 2 files changed, 225 insertions(+), 225 deletions(-)
```

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the CIs.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
To reviewers, this will wait for @cloud-fan 's PR to fix the PlanStabilitySuite.
- https://github.com/apache/spark/pull/34929#discussion_r893624590

**Comment by dongjoon-hyun** [comment]
Gentle ping, @cloud-fan . I hope to recover the branch first.

**Comment by cloud-fan** [comment]
I have created the PR for 3.2: https://github.com/apache/spark/pull/36828

Can we wait for a few more hours?

**Comment by dongjoon-hyun** [comment]
Thank you. The patch looks good to me.

I close this PR in favor of #36828

**Pull request closed without merging**
