### PR TITLE
[SPARK-35946][PYTHON] Respect Py4J server in InheritableThread API

### PR DESCRIPTION
**Pull request by HyukjinKwon**
### What changes were proposed in this pull request?

Currently ,we sets the environment variable `PYSPARK_PIN_THREAD` at the client side of `InhertiableThread` API for Py4J (`python/pyspark/util.py`). If the Py4J gateway is created somewhere else (e.g., Zeppelin, etc), it could introduce a breakage at:

```python
from pyspark import SparkContext
jvm = SparkContext._jvm
thread_connection = jvm._gateway_client.get_thread_connection()
# `AttributeError: 'GatewayClient' object has no attribute 'get_thread_connection'` (non-pinned thread mode)
# `get_thread_connection` is only in 'ClientServer' (pinned thread mode)
```

This PR proposes to check the given gateway created, and do the pinned thread mode behaviour accordingly so we can avoid any breakage when Py4J server/gateway is created separately from somewhere else without a pinned thread mode.

### Why are the changes needed?

To avoid any potential breakage.

### Does this PR introduce _any_ user-facing change?

No, the change happened only in the master (https://github.com/apache/spark/commit/fdd7ca5f4e35a906090f3c6b160bdba9ac9fd0ca).

### How was this patch tested?

This is actually a partial revert of https://github.com/apache/spark/commit/fdd7ca5f4e35a906090f3c6b160bdba9ac9fd0ca. As long as the existing tests pass, I guess we're all good.

I also manually tested to make doubly sure:

**Before**:

```python
>>> from pyspark import InheritableThread, inheritable_thread_target
>>> InheritableThread(lambda: 1).start()
>>> inheritable_thread_target(lambda: 1)()
Traceback (most recent call last):
  File "/.../python3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/.../python3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/.../spark/python/pyspark/util.py", line 361, in copy_local_properties
    InheritableThread._clean_py4j_conn_for_current_thread()
  File "/.../spark/python/pyspark/util.py", line 381, in _clean_py4j_conn_for_current_thread
    thread_connection = jvm._gateway_client.get_thread_connection()
AttributeError: 'GatewayClient' object has no attribute 'get_thread_connection'

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../spark/python/pyspark/util.py", line 324, in wrapped
    InheritableThread._clean_py4j_conn_for_current_thread()
  File "/.../spark/python/pyspark/util.py", line 381, in _clean_py4j_conn_for_current_thread
    thread_connection = jvm._gateway_client.get_thread_connection()
AttributeError: 'GatewayClient' object has no attribute 'get_thread_connection'
```

**After**:

```python
>>> from pyspark import InheritableThread, inheritable_thread_target
>>> InheritableThread(lambda: 1).start()
>>> inheritable_thread_target(lambda: 1)()
1
```

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
@WeichenXu123 can you take a quick look please?

**Review by dongjoon-hyun — APPROVED** [review]
Since this is only at `utill.py`, we are still able to turn off the pined mode by `PYSPARK_PIN_THREAD=false` via `java_gateway` and `Py4JServer.scala`, right?

**Review by WeichenXu123 — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @HyukjinKwon and @WeichenXu123 . Merged to master.

**Comment by HyukjinKwon** [comment]
Thank you @dongjoon-hyun !!

> Since this is only at utill.py, we are still able to turn off the pined mode by PYSPARK_PIN_THREAD=false via java_gateway and Py4JServer.scala, right?

Yes. This fix is in case other projects (e.g., Zeppelin) create the Java Gateway by themselves (and set it to `SparkContext`). In this case,  `PYSPARK_PIN_THREAD` env won't be respected. (server side)

I fixed `util.py` to respect the created the Java Gateway so it won't cause breakage in the case. (client side)

**Comment by pratyush-prateek** [comment]
@HyukjinKwon I had one basic question. To check if a fully managed spark cluster has pinned thread mode enabled, we try getting the value of thread connection via `jvm._gateway_client.get_thread_connection()`. If the thread connection exists, can we say that the cluster was started with pinned thread mode enabled?

**Comment by HyukjinKwon** [comment]
> If the thread connection exists, can we say that the cluster was started with pinned thread mode enabled?

No, it only affects the client (Spark Driver)

**Comment by pratyush-prateek** [comment]
> > If the thread connection exists, can we say that the cluster was started with pinned thread mode enabled?
> 
> No, it only affects the client (Spark Driver)

Yes, I mean whatever piece of code runs on spark driver to get thread connection, if that throws attribute error.

**Pull request closed without merging**
