### PR TITLE
[SPARK-38673][TESTS] Replace Java assert with Junit API in Java UTs

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
There are some Java UTs use java `assert` for assertion, and these assertions will strongly depend on JVM start with `-ea` mode, so this pr replace them with Junit API.

### Why are the changes needed?
Use Junit API in Java UTs.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]

**Review by srowen — APPROVED** [review]
Looks good if that is all of them

**Comment by LuciferYang** [comment]
> Looks good if that is all of them

Let me check again

**Comment by LuciferYang** [comment]
after [913ba45](https://github.com/apache/spark/pull/35987/commits/913ba4534d38f9cf6d386fd6d5440c14895cc047), I think that's all

**Comment by srowen** [comment]
Merged to master

**Comment by LuciferYang** [comment]
thanks all

**Pull request closed without merging**
