### PR TITLE
[SPARK-17299] TRIM/LTRIM/RTRIM should not strips characters other than spaces

### PR DESCRIPTION
**Pull request by techaddict**
## What changes were proposed in this pull request?

TRIM/LTRIM/RTRIM should not strips characters other than spaces, we were trimming all chars small than ASCII 0x20(space)
## How was this patch tested?

fixed existing tests.

### CODE REVIEW

**Comment by rxin** [comment]
Can you add a unit test for this?

**Comment by techaddict** [comment]
@rxin Done 👍

**Comment by srowen** [comment]
The implementation in `stringExpressions.scala` generates code that calls `trim()`, so just double-checking, that's calling UTF8String not String right? Then yeah LGTM

**Comment by techaddict** [comment]
@srowen yes in stringExpressions the trim is on with UTF8String.

**Comment by srowen** [comment]
LGTM. Seems like this should go into 2.0.x as well since it's really a bug fix.

**Comment by srowen** [comment]
Merged to master/2.0

**Comment by srowen** [comment]
Merged to master/2.0

**Pull request closed without merging**
