### PR TITLE
[SPARK-31927][K8S] Bump Fabric8 to 4.10.2 to support k8s 1.18

### PR DESCRIPTION
**Pull request by jpallari**
### What changes were proposed in this pull request?

Update the Fabric8 Kubernetes client to the latest release to support Kubernetes version 1.18 (and 1.17) in Spark 2.4.x.

### Why are the changes needed?

Kubernetes 1.16 will fall out of support after the next Kubernetes release (which is probably going to be released this summer), so Kubernetes cluster maintainers will want to upgrade their clusters past it. However, the current Spark 2.4.x version can't function in Kubernetes clusters with version higher than 1.16 without upgrading the Kubernetes client.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Using standard `dev/run-tests` script and by executing a demo job in Minikube. Steps for executing in Minikube:

1. Create a Minikube cluster.
2. Build the project using Maven with Kubernetes support.
3. Build the Docker images using `bin/docker-image-tool.sh` with `-m` flag.
4. Create a namespace and a service account for Spark.
5. Submit a Spark job in the cluster:
    ```
    ./bin/spark-submit  \
    --master "k8s://https://$(minikube ip):8443" \
    --name demo \
    --deploy-mode cluster \
    --conf spark.kubernetes.driver.pod.name=demo-driver \
    --conf spark.kubernetes.namespace=spark \
    --conf spark.kubernetes.authenticate.driver.serviceAccountName=spark \
    --conf spark.kubernetes.container.image=spark-py:latest \
    --conf spark.kubernetes.driver.limit.cores=2 \
    --conf spark.kubernetes.container.image.pullPolicy=Never \
    local:///opt/spark/examples/src/main/python/pi.py 10
    ```

### CODE REVIEW

**Comment by jkpl** [comment]
This change is similar to #27443

**Comment by dongjoon-hyun** [comment]
Thank you for making a PR, @jkpl . However, `branch-2.4` is a maintenance release which we cannot change its dependency dramatically. Especially, this is not a bug because this PR aims to support a new K8s version which is released after Apache Spark 2.4.0.

Please see the following example at [Apache Spark 2.4.6](https://downloads.apache.org/spark/spark-2.4.6/) released recently this week. Since we didn't change the dependency, we provide a workaround.
- https://github.com/apache/spark/pull/28638

We hope the users can migrate to 3.0.0 soon.
- https://dist.apache.org/repos/dist/dev/spark/v3.0.0-rc3-bin/

**Comment by jkpl** [comment]
@dongjoon-hyun Thanks for the quick feedback! I understand your concern, but I think that it also puts Spark Kubernetes users to a tough spot. The users will have to pick between stable version of Spark and supported Kubernetes cluster versions. I think it puts a lot of pressure on people to migrate to Spark 3.

**Comment by jkpl** [comment]
@dongjoon-hyun What do you think about bumping the Kubernetes client dependency from 4.6.x to 4.7.x for Spark 2.4 similar to #27443? So instead of using 4.10.x, 4.7.x would be used instead. This would mean that there's less changes in dependencies, but it would still increase the Kubernetes version support.

**Comment by jkpl** [comment]
> Please see the following example at Apache Spark 2.4.6 released recently this week. Since we didn't change the dependency, we provide a workaround. #28638

I managed to get Spark 2.4.6 working with K8s 1.18 using the workaround you suggested. I mistakenly interpreted the HTTP2 issue as a K8s compatibility issue. I withdraw my PR. Thanks!

**Comment by dongjoon-hyun** [comment]
Thank you for understanding, @jkpl  .

**Pull request closed without merging**
