### PR TITLE
[SPARK-26334][SQL] NullPointerException in CallMethodViaReflection when we apply reflect function for empty field

### PR DESCRIPTION
**Pull request by southernriver**
## What changes were proposed in this pull request?
As the description in [SPARK-26334](https://issues.apache.org/jira/browse/SPARK-26334),When we apply reflect function  to empty field,  it will  always  lead to  NullPointerException. We can catch the NPE  when invocation is triggered by reflect function.

## How was this patch tested?
manual tests!
In the table shown below,  for field `url`, some values  are initialized to NULL .

image

When we apply reflect function  to `url` ,
before fix:
image

after fix:
image

Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
As I said in the JIRA, the method itself already throws an NPE:

```
scala> java.net.URLDecoder.decode(null, "UTF-8")
java.lang.NullPointerException
  at java.net.URLDecoder.decode(URLDecoder.java:136)
  ... 29 elided
```

So, the exception is delegated from its original method, which pretty makes sense. Looks Hive is tolerant for the exceptions thrown from the method but Spark doesn't necessarily follow Hive. Let's don't fix it.

**Comment by southernriver** [comment]
@HyukjinKwon  Could you please have a look at this again,I have create  a PR for this. We could handle empty filed in table well when used refelct function like urlDecode. This action would improve robustness for SparkSQL.

**Comment by southernriver** [comment]
Maybe there is no better solution for me to response this case.I think this is a good way to solve this.

**Comment by srowen** [comment]
@southernriver you have opened this vs branch 2.3, and I also don't see that we should change this behavior. You're invoking a method that can't accept null, so this is the expected behavior. You can handle nulls otherwise in your code. It's not really expected to return the string "null" in this case.

**Pull request closed without merging**
