### PR TITLE
[SPARK-26266][BUILD] Update to Scala 2.12.8

### PR DESCRIPTION
**Pull request by srowen**
## What changes were proposed in this pull request?

Update to Scala 2.12.8

## How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by srowen** [comment]
Hm, looks like genjavadocplugin is published for individual Scala releases and doesn't exist yet for 2.12.8: https://mvnrepository.com/artifact/com.typesafe.genjavadoc/genjavadoc-plugin . I'll look at whether we can leave it at 2.12.7 or whether to expect it will be released soon.

**Comment by dongjoon-hyun** [comment]
Now, it's released. Let's try again.
- http://central.maven.org/maven2/com/typesafe/genjavadoc/genjavadoc-plugin_2.12.8/0.11/

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Review by dongjoon-hyun — APPROVED** [review]
I build this PR with maven, too. The building itself looks good.
Let's see the Jenkins result.

**Comment by srowen** [comment]
Hm, one failure was due to a JVM crash, but it fails twice consistent, with sbt just exiting with status 134. No other failures are logged. Not sure what to make of that!

**Review by felixcheung — COMMENTED** [review]
change is ok, but maybe the crash is related to .7 -> .8?

**Comment by dongjoon-hyun** [comment]
Surprisingly, all of three are due to consistent JVM crashes. It seems that Scala 2.12.8 or Spark has some unstable code somewhere.

- https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/99679/consoleFull
```
[info] <span style="color: #00CD00;">- SPARK-17641: collect functions should not collect null values (231 milliseconds)</span>
10:51:04.251 WARN org.apache.spark.sql.execution.window.WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
10:51:04.262 WARN org.apache.spark.sql.execution.window.WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fa843744e44, pid=116353, tid=140360030242560
```
- https://amplab.cs.berkeley.edu/jenkins/job/NewSparkPullRequestBuilder/4451/consoleFull
```
[info] <span style="color: #00CD00;">- read from textfile (508 milliseconds)</span>
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f60ec641e44, pid=40380, tid=140053491689216
#
```

- https://amplab.cs.berkeley.edu/jenkins/job/NewSparkPullRequestBuilder/4452/consoleFull
```
[info] <span style="color: #00CD00;">- SPARK-21996 read from text files generated by file sink -- file name has space (532 milliseconds)</span>
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f399e84ee44, pid=106264, tid=139883238606592
#
```

**Comment by dongjoon-hyun** [comment]
This might be https://bugs.openjdk.java.net/browse/JDK-8136447 (which is resolved later by other issue)
```
$ grep build_loop_late_post consoleFull*
consoleFull.4451:# V  [libjvm.so+0x812e44]  PhaseIdealLoop::build_loop_late_post(Node*)+0x144
consoleFull.4451:# V  [libjvm.so+0x812e44]  PhaseIdealLoop::build_loop_late_post(Node*)+0x144
consoleFull.4452:# V  [libjvm.so+0x812e44]  PhaseIdealLoop::build_loop_late_post(Node*)+0x144
consoleFull.4452:# V  [libjvm.so+0x812e44]  PhaseIdealLoop::build_loop_late_post(Node*)+0x144
consoleFull.4452:# V  [libjvm.so+0x812e44]  PhaseIdealLoop::build_loop_late_post(Node*)+0x144
consoleFull.99679:# V  [libjvm.so+0x812e44]  PhaseIdealLoop::build_loop_late_post(Node*)+0x144
consoleFull.99679:# V  [libjvm.so+0x812e44]  PhaseIdealLoop::build_loop_late_post(Node*)+0x144
consoleFull.99679:# V  [libjvm.so+0x812e44]  PhaseIdealLoop::build_loop_late_post(Node*)+0x144
```

Our jenkins are using the following.
```
JRE version: Java(TM) SE Runtime Environment (8.0_60-b27) (build )
```

cc @shaneknapp

**Comment by srowen** [comment]
Ah OK, so all of them were a JVM crash. It would probably be a good idea to update the JVM on all the workers as _60 is over 3 years old. It's probably not as simple as it sounds but WDYT @shaneknapp ?

**Comment by shaneknapp** [comment]
shouldn't be too hard, but it will require some downtime.

**Comment by shaneknapp** [comment]
https://issues.apache.org/jira/browse/SPARK-26282

**Comment by dongjoon-hyun** [comment]
Thank you, @srowen , @HyukjinKwon , @shaneknapp !

**Comment by felixcheung** [comment]
do we need to relnote jvm compatibility?

**Comment by srowen** [comment]
I'm not sure. I can't find any other reference to this crash and 2.12.8. It could be something only Spark happens to trigger, or could be specific to this JVM + platform but not Spark or Scala. We could drop a release note at least recommending the latest version of Java 8 (and 11) with Spark 2.4 / 3.0

**Comment by shaneknapp** [comment]
okie dokie, java8 update is done!
https://issues.apache.org/jira/browse/SPARK-26282

**Comment by dongjoon-hyun** [comment]
@shaneknapp .
The above run is still using old one. Do we need to retrigger to use JDK8_191?
```
[info] Building Spark (w/Hive 1.2.1) using SBT with these arguments:  -Phadoop-2.7 -Pkubernetes -Phive-thriftserver -Pkinesis-asl -Pyarn -Pspark-ganglia-lgpl -Phive -Pmesos test:package streaming-kinesis-asl-assembly/assembly
Using /usr/java/jdk1.8.0_60 as default JAVA_HOME.
Note, this will be overridden by -java-home if it is set.
```

**Comment by shaneknapp** [comment]
ok, PRB builds updated w/the new JAVA_HOME

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by shaneknapp** [comment]
it's building w/the proper java now.  from the build log:

```
[EnvInject] - Injecting as environment variables the properties content 
JENKINS_MASTER_HOSTNAME=amp-jenkins-master
JAVA_HOME=/usr/java/jdk1.8.0_191
JAVA_7_HOME=/usr/java/jdk1.7.0_79
SPARK_TESTING=1
```

**Comment by srowen** [comment]
Merged to master. I'll open a separate PR for branch-2.4

**Pull request closed without merging**
