### PR TITLE
[SPARK-9101] [PySpark] Add missing NullType

### PR DESCRIPTION
**Pull request by sixers**
JIRA: https://issues.apache.org/jira/browse/SPARK-9101

### CODE REVIEW

**Comment by rxin** [comment]
Jenkins, test this please.

**Comment by rxin** [comment]
cc @davies

**Comment by davies** [comment]
I'm just wondering that is there a real use case that need NullType? Currently, it's only used during type inferring.

**Comment by rxin** [comment]
It can happen if there is a null literal -- I'm not sure what happens in Python though.

**Comment by JoshRosen** [comment]
@rxin, @davies, the JIRA ticket contains an example a query that fails due to this issue: https://issues.apache.org/jira/browse/SPARK-9101

@sixers, it might be nice to add a regression test based on the simple example you gave in the JIRA.

**Comment by davies** [comment]
@JoshRosen I see, thanks!

**Comment by sixers** [comment]
@JoshRosen 
@davies 
@rxin 

This is my first contribution to Spark, would you give me some directions where to put this test?

In general what is broken is parsing schema of Java DataFrame (with NullType). It's done lazily here:
https://github.com/apache/spark/blob/692378c01d949dfe2b2a884add153cd5f8054b5a/python/pyspark/sql/dataframe.py#L182

which eventually uses `_parse_datatype_json_value `: to parse the schema: https://github.com/apache/spark/blob/692378c01d949dfe2b2a884add153cd5f8054b5a/python/pyspark/sql/types.py#L708

So it also breaks in other cases like this:

```python
sqlContext.createDataFrame(sc.parallelize([(None,1),(None,2), (None,3), (None, 4)]), samplingRatio=0.5).collect()
sqlContext.createDataFrame([[None]], schema=StructType([StructField("col", NullType(), True)])).collect()
```

Because of that I think tests should be written for _parse_datatype_json_value.

There are some tests in `_parse_datatype_json_string ` : https://github.com/apache/spark/blob/692378c01d949dfe2b2a884add153cd5f8054b5a/python/pyspark/sql/types.py#L651

Tests for simple types are dynamic, created by iterating over `_all_atomic_types`, where NullType was missing. Now it's included in those tests. : https://github.com/apache/spark/blob/692378c01d949dfe2b2a884add153cd5f8054b5a/python/pyspark/sql/types.py#L660

In general I think there are two options:

- unroll those dynamic checks and write explicit check for each atomic type
- add additional NullType field to `complex_structtype` test: https://github.com/apache/spark/blob/692378c01d949dfe2b2a884add153cd5f8054b5a/python/pyspark/sql/types.py#L680

I'm not sure if it brings any value.

What do you think? Should I go with one of those or you see other places where I can introduce a test for that?

**Comment by JoshRosen** [comment]
@sixers, my suggestion was to add an end-to-end test, like `sqlContext.sql("select null").collect()`, to PySpark SQL's `SQLTests` unittest suite: https://github.com/apache/spark/blob/163e3f1df94f6b7d3dadb46a87dbb3a2bade3f95/python/pyspark/sql/tests.py#L130.  This could be a new test case, named something like `test_select_null_literal`.

The fact that this bug was unnoticed for so long implies that our Python suite doesn't contain any tests which try to select null literals, which is why I wanted to add such a test.

**Comment by sixers** [comment]
@JoshRosen 

I see, thanks for suggestion, I added this test.

**Comment by JoshRosen** [comment]
Jenkins, this is ok to test.

**Comment by rxin** [comment]
Thanks! Going to merge this.

**Comment by rxin** [comment]
Actually I'm having some trouble with ASF git. I will merge when that works.

**Comment by rxin** [comment]
I merged it.

**Comment by rxin** [comment]
Note: I merged it in master (1.5.0), as well as branch-1.4 (1.4.2).

**Pull request closed without merging**
