### PR TITLE
[SPARK-35668][INFRA] Use "concurrency" syntax on Github Actions workflow

### PR DESCRIPTION
**Pull request by Yikun**
### What changes were proposed in this pull request?

This patch uses the "concurrency" syntax to replace the "cancel job" workflow:
- .github/workflows/benchmark.yml
- .github/workflows/labeler.yml
- .github/workflows/notify_test_workflow.yml
- .github/workflows/test_report.yml

Remove the .github/workflows/cancel_duplicate_workflow_runs.yml

Note that the push/schedule based job are not changed to keep the same config in https://github.com/apache/spark/commit/a4b70758d3dfe2d59fb3800321ffb2450206c26f:
- .github/workflows/build_and_test.yml
- .github/workflows/publish_snapshot.yml
- .github/workflows/stale.yml
- .github/workflows/update_build_status.yml

### Why are the changes needed?
We are using [cancel_duplicate_workflow_runs](https://github.com/apache/spark/blob/a70e66ecfa638cacc99b4e9a7c464e41ec92ad30/.github/workflows/cancel_duplicate_workflow_runs.yml#L1) job to cancel previous jobs when a new job is queued. Now, it has been supported by the github action by using ["concurrency"](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency) syntax to make sure only a single job or workflow using the same concurrency group.

Related: https://github.com/apache/arrow/pull/10416 and https://github.com/potiuk/cancel-workflow-runs

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
triger the PR manaully

### CODE REVIEW

**Comment by Yikun** [comment]
cc @potiuk @HyukjinKwon

**Review by potiuk — APPROVED** [review]

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by HyukjinKwon** [comment]
This seems like causing all PR builds canceled for some reasons:

Screen Shot 2021-06-09 at 4 48 38 PM

I reverted it for now.

**Comment by Yikun** [comment]
image

emm, The reason as above.
 
- `pull_request_target` triggered job's `github.ref` is same: `refs/heads/master`
- `pull_request` triggered `github.ref` is like `refs/pull/5/merge`

so looks like, in `pull_request_target`, we can't use this `concurrency` directly. : (

**Comment by Yikun** [comment]
```yaml
concurrency:
  group: ${{ github.repository }}-${{ github.event.pull_request.number }}-${{ github.workflow }}
  cancel-in-progress: true
```

I think we could use `github.event.pull_request.number` to make sure only single PR trigger job once.

**Pull request closed without merging**
