### PR TITLE
[SPARK-50400][BUILD] Upgrade log4j2 to 2.24.2

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to upgrade log4j2 from `2.24.1` to `2.24.2`.

### Why are the changes needed?
- The full release notes:
https://github.com/apache/logging-log4j2/releases/tag/rel%2F2.24.2

- This release fixes a critical bug in Log4j API initialization code, which can cause LogManager.getLogger() to return null under certain conditions. See https://github.com/apache/logging-log4j2/issues/3143 for details.
  Fix key removal issues in Thread Context (https://github.com/apache/logging-log4j2/issues/3048)
  Use hard references to Loggers in LoggerRegistry. (https://github.com/apache/logging-log4j2/issues/3143)
  Fix ArrayIndexOutOfBoundsException in JSON Template Layout truncated exception resolver (https://github.com/apache/logging-log4j2/pull/3216)

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
The patch looks good to me because the failed Oracle DBMS test seems irrelevant. Could you re-trigger the failed CI?

**Comment by panbingkun** [comment]
> The patch looks good to me because the failed Oracle DBMS test seems irrelevant. Could you re-trigger the failed CI?

Okay, I have re-trigger the failed CI, let's wait for it.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. (Pending CIs).

**Comment by dongjoon-hyun** [comment]
Merged to master. Thank you, @panbingkun .

**Pull request closed without merging**
