### PR TITLE
[SPARK-9140][MLlib] Replace TimeTracker by Stopwatch

### PR DESCRIPTION
**Pull request by hhbyyh**
jira: https://issues.apache.org/jira/browse/SPARK-9140
We can replace TImeTracker in tree implementations by Stopwatch. The initial PR could use local stopwatches only.
With the current API of MultiStopwatch:
1.  The typical invoking sequence is not reenterable (causes exception)

```
  multiTimer.addLocal("total")
  multiTimer("total").start()
  ...
  multiTimer("total").stop()
```
1. Maybe we can have a new API combining

```
  multiTimer.addLocal("total")
  multiTimer("total").start()
```

  just for simplification. 

next: Shall we keep TimeTracker ?

### CODE REVIEW

**Comment by mengxr** [comment]
@hhbyyh Could you post the exception you saw?

**Comment by hhbyyh** [comment]
Oh I should have made it more clear. An example:
```
  def run(): Unit ={
    val conf = new SparkConf().setMaster("local").setAppName("ss")
    val sc = new SparkContext(conf)
    val multiTimer = new MultiStopwatch(sc)
    for(i <- 0 to 2) {
      someFunction(multiTimer)
    }
  }

  def someFunction(multiTimer: MultiStopwatch): Unit ={
    multiTimer.addLocal("total")
    multiTimer("total").start()
    // ...
    multiTimer("total").stop()
  }
```
will throw `Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: Stopwatch with name total already exists.`
This is probably by design, yet it's not quite handy. Since users will have to:
1. avoid passing MultiStopwatch around as a parameter 
2. or avoid invoking `someFunction` multiple times.

**Comment by rxin** [comment]
@hhbyyh thanks for the pull request. I'm going through a list of pull requests to cut them down since the sheer number is breaking some of the tooling we have. Due to lack of activity on this pull request, I'm going to push a commit to close it. Feel free to reopen it or create a new one.

**Comment by MechCoder** [comment]
@hhbyyh What is your opinion about adding

**Comment by MechCoder** [comment]
@hhbyyh What is your opinion about renaming `addLocal` to `addOrGetLocal` which returns a local stopwatch if it already exists? That should solve your concerns.

**Pull request closed without merging**
