### PR TITLE
[SPARK-42389][CORE][TESTS] Ensure Live UI dir be cleaned up after test when `LIVE_UI_LOCAL_STORE_DIR` is configured

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
When run Spark UTs with export env `LIVE_UI_LOCAL_STORE_DIR`, there are some  cases not cleaned `LIVE_UI_LOCAL_STORE_DIR` directory after test.

For example, `LauncherBackendSuite`, 

https://github.com/apache/spark/blob/201a91bab0e3d540ee262bd73b597b137f3f987b/core/src/test/scala/org/apache/spark/launcher/LauncherBackendSuite.scala#L70-L72

`handle.kill()` gives `AppStatusStore.close` no chance to execute, and `LIVE_UI_LOCAL_STORE_DIR` will not cleaned up.

So this pr introduces the `cleanupUIDirIfNecessary` function for `SparkFunSuite` to ensure that `LIVE_UI_LOCAL_STORE_DIR` will be cleaned up after test. At the same time, the audit log is added to the `cleanupUIDirIfNecessary` function to facilitate the follow-up investigation of cases that do not clean up `LIVE_UI_LOCAL_STORE_DIR` normally

### Why are the changes needed?
Add a protection mechanism to ensure that `LIVE_UI_LOCAL_STORE_DIR` is cleaned up at the same time, which is more friendly to developers and does not need to manually clean up residual files.

### Does this PR introduce _any_ user-facing change?
No, just for test with export env `LIVE_UI_LOCAL_STORE_DIR`.

### How was this patch tested?
- Pass Github Actions
- Manual test:

run `build/sbt clean "core/testOnly *LauncherBackendSuite"`

**Before**

we can see the residual spark-ui dirs in `LIVE_UI_LOCAL_STORE_DIR` after test:

```
spark-ui-0a416dc8-8732-4b1d-a447-7ce602699411	spark-ui-f6ebf199-41c9-4520-b83e-a82f77df55ce
```

**After**

No files in `LIVE_UI_LOCAL_STORE_DIR` after test, and we can see the following logs in unit-tests.log

```
===== FINISHED o.a.s.launcher.LauncherBackendSuite: 'standalone/client: launcher handle' =====

23/02/10 11:44:41.655 pool-1-thread-1 WARN LauncherBackendSuite: The number of UI dirs not cleaned is 2
```

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Oh, is this some root causes of flakiness? Thanks.

**Comment by dongjoon-hyun** [comment]
cc @gengliangwang

**Comment by LuciferYang** [comment]
For example, `LauncherBackendSuite `

https://github.com/apache/spark/blob/201a91bab0e3d540ee262bd73b597b137f3f987b/core/src/test/scala/org/apache/spark/launcher/LauncherBackendSuite.scala#L70-L72

When I export `LIVE_UI_LOCAL_STORE_DIR` and test it locally, `handle.kill()` gives `AppStatusStore#cleanUpStorePath` no chance to execute, which will cause Live UI dirs to remain.

This will not cause the test to fail, but will increase the disk usage. I didn't look for all similar cases, but I hope to add a protection mechanism to avoid this issue, this may friendly to developers.  At the same time, I added some logs to find out which cases did not actively clean up the Live UI dir.

**Comment by LuciferYang** [comment]
I will update pr description later

**Comment by LuciferYang** [comment]
Think about this more. This way may cause sbt parallel test failed...

**Comment by LuciferYang** [comment]
run the following tests:

```
export LIVE_UI_LOCAL_STORE_DIR=/tmp/spark-ui
build/sbt clean test
```

Before

Some tests have the following similar failures


```
[info] org.apache.spark.DistributedSuite *** ABORTED *** (677 milliseconds)
[info]   java.lang.ExceptionInInitializerError:
[info]   at org.apache.spark.util.kvstore.RocksDB.<clinit>(RocksDB.java:47)
[info]   at org.apache.spark.status.KVUtils$.open(KVUtils.scala:99)
[info]   at org.apache.spark.status.KVUtils$.$anonfun$createKVStore$1(KVUtils.scala:144)
[info]   at scala.Option.map(Option.scala:230)
[info]   at org.apache.spark.status.KVUtils$.createKVStore(KVUtils.scala:127)
[info]   at org.apache.spark.status.AppStatusStore$.createLiveStore(AppStatusStore.scala:882)
[info]   at org.apache.spark.SparkContext.<init>(SparkContext.scala:460)
[info]   at org.apache.spark.SparkContext.<init>(SparkContext.scala:157)
[info]   at org.apache.spark.SparkContext.<init>(SparkContext.scala:170)
[info]   at org.apache.spark.DistributedSuite.$anonfun$new$1(DistributedSuite.scala:52)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.funsuite.AnyFunSuiteLike$$anon$1.apply(AnyFunSuiteLike.scala:226)
[info]   at org.apache.spark.SparkFunSuite.withFixture(SparkFunSuite.scala:207)
[info]   at org.scalatest.funsuite.AnyFunSuiteLike.invokeWithFixture$1(AnyFunSuiteLike.scala:224)
[info]   at org.scalatest.funsuite.AnyFunSuiteLike.$anonfun$runTest$1(AnyFunSuiteLike.scala:236)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[info]   at org.scalatest.funsuite.AnyFunSuiteLike.runTest(AnyFunSuiteLike.scala:236)
[info]   at org.scalatest.funsuite.AnyFunSuiteLike.runTest$(AnyFunSuiteLike.scala:218)
[info]   at org.apache.spark.SparkFunSuite.org$scalatest$BeforeAndAfterEach$$super$runTest(SparkFunSuite.scala:66)
[info]   at org.scalatest.BeforeAndAfterEach.runTest(BeforeAndAfterEach.scala:234)
[info]   at org.scalatest.BeforeAndAfterEach.runTest$(BeforeAndAfterEach.scala:227)
[info]   at org.apache.spark.SparkFunSuite.runTest(SparkFunSuite.scala:66)
[info]   at org.scalatest.funsuite.AnyFunSuiteLike.$anonfun$runTests$1(AnyFunSuiteLike.scala:269)
[info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
[info]   at scala.collection.immutable.List.foreach(List.scala:431)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
[info]   at org.scalatest.funsuite.AnyFunSuiteLike.runTests(AnyFunSuiteLike.scala:269)
[info]   at org.scalatest.funsuite.AnyFunSuiteLike.runTests$(AnyFunSuiteLike.scala:268)
[info]   at org.scalatest.funsuite.AnyFunSuite.runTests(AnyFunSuite.scala:1564)
[info]   at org.scalatest.Suite.run(Suite.scala:1114)
[info]   at org.scalatest.Suite.run$(Suite.scala:1096)
[info]   at org.scalatest.funsuite.AnyFunSuite.org$scalatest$funsuite$AnyFunSuiteLike$$super$run(AnyFunSuite.scala:1564)
[info]   at org.scalatest.funsuite.AnyFunSuiteLike.$anonfun$run$1(AnyFunSuiteLike.scala:273)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
[info]   at org.scalatest.funsuite.AnyFunSuiteLike.run(AnyFunSuiteLike.scala:273)
[info]   at org.scalatest.funsuite.AnyFunSuiteLike.run$(AnyFunSuiteLike.scala:272)
[info]   at org.apache.spark.SparkFunSuite.org$scalatest$BeforeAndAfterAll$$super$run(SparkFunSuite.scala:66)
[info]   at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)
[info]   at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
[info]   at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
[info]   at org.apache.spark.SparkFunSuite.run(SparkFunSuite.scala:66)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:321)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:517)
[info]   at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:413)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info]   at java.lang.Thread.run(Thread.java:750)
[info]   Cause: java.lang.RuntimeException: Unable to load the RocksDB shared library
[info]   at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:73)
[info]   at org.rocksdb.RocksDB.<clinit>(RocksDB.java:39)
[info]   at org.apache.spark.util.kvstore.RocksDB.<clinit>(RocksDB.java:47)
[info]   at org.apache.spark.status.KVUtils$.open(KVUtils.scala:99)
[info]   at org.apache.spark.status.KVUtils$.$anonfun$createKVStore$1(KVUtils.scala:144)
[info]   at scala.Option.map(Option.scala:230)
[info]   at org.apache.spark.status.KVUtils$.createKVStore(KVUtils.scala:127)
[info]   at org.apache.spark.status.AppStatusStore$.createLiveStore(AppStatusStore.scala:882)
[info]   at org.apache.spark.SparkContext.<init>(SparkContext.scala:460)
[info]   at org.apache.spark.SparkContext.<init>(SparkContext.scala:157)
[info]   at org.apache.spark.SparkContext.<init>(SparkContext.scala:170)
[info]   at org.apache.spark.DistributedSuite.$anonfun$new$1(DistributedSuite.scala:52)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
```

After

Some test failure similar to the following, it won't happen before this pr. So when `LIVE_UI_LOCAL_STORE_DIR` is exported, this pr does have a negative impact on the multi-module concurrent test of sbt


```
[info] PregelSuite:
[info] - empty data stream with kryo ser *** FAILED *** (1 second, 80 milliseconds)
[info]   org.rocksdb.RocksDBException: While mkdir if missing: /tmp/spark-ui/spark-ui-13db345a-a563-4c4a-a9d8-44d9ca7efc00/listing.rdb: No such file or directory
[info]   at org.rocksdb.RocksDB.open(Native Method)
[info]   at org.rocksdb.RocksDB.open(RocksDB.java:252)
[info]   at org.apache.spark.util.kvstore.RocksDB.<init>(RocksDB.java:122)
[info]   at org.apache.spark.status.KVUtils$.open(KVUtils.scala:99)
[info]   at org.apache.spark.status.KVUtils$.$anonfun$createKVStore$1(KVUtils.scala:157)
[info]   at scala.Option.map(Option.scala:230)
[info]   at org.apache.spark.status.KVUtils$.createKVStore(KVUtils.scala:127)
[info]   at org.apache.spark.status.AppStatusStore$.createLiveStore(AppStatusStore.scala:882)
[info]   at org.apache.spark.SparkContext.<init>(SparkContext.scala:460)
[info]   at org.apache.spark.SparkContext.<init>(SparkContext.scala:139)
[info]   at org.apache.spark.util.collection.ExternalSorterSuite.emptyDataStream(ExternalSorterSuite.scala:299)
[info]   at org.apache.spark.util.collection.ExternalSorterSuite.$anonfun$new$1(ExternalSorterSuite.scala:35)
[info]   at org.apache.spark.util.collection.ExternalSorterSuite.$anonfun$new$1$adapted(ExternalSorterSuite.scala:35)
[info]   at org.apache.spark.util.collection.ExternalSorterSuite.$anonfun$testWithMultipleSer$1(ExternalSorterSuite.scala:286)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.funsuite.AnyFunSuiteLike$$anon$1.apply(AnyFunSuiteLike.scala:226)
[info]   at org.apache.spark.SparkFunSuite.withFixture(SparkFunSuite.scala:233)
[info]   at org.scalatest.funsuite.AnyFunSuiteLike.invokeWithFixture$1(AnyFunSuiteLike.scala:224)
[info]   at org.scalatest.funsuite.AnyFunSuiteLike.$anonfun$runTest$1(AnyFunSuiteLike.scala:236)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[info]   at org.scalatest.funsuite.AnyFunSuiteLike.runTest(AnyFunSuiteLike.scala:236)
[info]   at org.scalatest.funsuite.AnyFunSuiteLike.runTest$(AnyFunSuiteLike.scala:218)
```

**Comment by LuciferYang** [comment]
Maybe we can only manually clean up the residual files after the test?

**Comment by LuciferYang** [comment]
close this first, I will re-open this if I hava a better solution,

**Pull request closed without merging**
