### PR TITLE
[SPARK-13431] [SQL] [test-maven] split keywords from ExpressionParser.g

### PR DESCRIPTION
**Pull request by davies**
## What changes were proposed in this pull request?

This PR pull all the keywords (and some others) from ExpressionParser.g as KeywordParser.g, because ExpressionParser is too large to compile.
## How was the this patch tested?

unit test, maven build

Closes #11329

### CODE REVIEW

**Comment by davies** [comment]
cc @hvanhovell

**Comment by hvanhovell** [comment]
Haha - that is quick. Have you tried doing a maven build?

**Comment by davies** [comment]
@hvanhovell I'm working on that, have not do maven build before, blocked by something, could you also help to try that?

**Comment by JoshRosen** [comment]
@davies, put [test-maven] into your PR title and the pull request builder will run it through Maven.

**Comment by hvanhovell** [comment]
@davies I just tried this locally and unfortunately I still get the code too large error. The maven command I have used: `build/mvn -Phadoop-2.6 -Dhadoop.version=2.6.0  clean package -DskipTests`

**Comment by davies** [comment]
@hvanhovell After move more stuff, this passed the build with maven. Could you double check that?

**Comment by zzcclp** [comment]
@davies , cool, i build with maven successfully according to this pr,  The maven command I have used: 
mvn clean package -DskipTests -Pscala-2.11 -Phadoop-2.6 -Phive -Phive-thriftserver -Pyarn -Dyarn.version=2.6.0-cdh5.4.7 -Dhadoop.version=2.6.0-cdh5.4.7

**Pull request closed without merging**
