### PR TITLE
[SPARK-42632][CONNECT] Fix scala paths in integration tests

### PR DESCRIPTION
**Pull request by hvanhovell**
### What changes were proposed in this pull request?
We use the current scala version to figure out which jar to load.

### Why are the changes needed?
The jar resolution in the connect client tests can resolve the jar for the wrong scala version if you are working with multiple scala versions.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
It is a test.

### CODE REVIEW

**Comment by hvanhovell** [comment]
cc @zhenlineo @LuciferYang

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you for taking care of this, @hvanhovell .
(Pending CIs)

**Review by zhenlineo — APPROVED** [review]
LGTM. Thanks for fixing this.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master and branch-3.4.

**Pull request closed without merging**
