### PR TITLE
[SPARK-7935][SQL]change sparkContext in sparkPlan as val

### PR DESCRIPTION
**Pull request by baishuo**
I thinke sparkContext  is better defined as val than a function

### CODE REVIEW

**Comment by rxin** [comment]
There isn't really much difference here, since a val under the hood is a function too.

**Comment by baishuo** [comment]
Hi @rxin , sparkContext should be transient, sorry for forget add it.  I think if define as function it will be computed when it was be referenced but val need not be computed, I dont know if it is right :)

**Comment by rxin** [comment]
There's really no difference here for performance reasons, since this is not a hot code path. I think we should just close this.

**Comment by rxin** [comment]
@baishuo do you mind closing this? Thanks.

**Comment by baishuo** [comment]
@rxin no problem,close this PR :)

**Pull request closed without merging**
