### PR TITLE
[SPARK-31876][BUILD] Upgrade to Zstd 1.4.5

### PR DESCRIPTION
**Pull request by williamhyun**
### What changes were proposed in this pull request?

This PR aims to upgrade to Zstd 1.4.5.

### Why are the changes needed?

Zstd 1.4.5 improves performance. 

https://github.com/facebook/zstd/releases/tag/v1.4.5

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Passed the Jenkins.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
ok to test

**Comment by dongjoon-hyun** [comment]
ok to test

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
@williamhyun Can you file a JIRA?

**Comment by williamhyun** [comment]
Sure, I filed SPARK-31876 and updated the PR title.

**Comment by srowen** [comment]
Looks OK if there are no compatibility concerns.

**Comment by dbtsai** [comment]
LGTM. Merged into master.

**Pull request closed without merging**
