### PR TITLE
[SPARK-11354] [Web UI] expose custom log4j to executor page

### PR DESCRIPTION
**Pull request by yongjiaw**

### CODE REVIEW

**Comment by JoshRosen** [comment]
Hey @yongjiaw, thanks for submitting this! I've been wanting to do something like this myself, so I plan to take a look at this PR and will try it out.

**Comment by yongjiaw** [comment]
@JoshRosen, I started this as a hack. The only thing I don't feel good about it is I have to remove the logType checks from LogPage.scala, which runs with the worker process and is not aware of the executor's loggers. It works for the driver's executorPage because the driver is already listening for executor data. Similarly, the worker page right now only has hard-coded links to stdout and stderr. Maybe this can be further improved by letting worker listen to executors. This small step should be useful enough.

**Comment by yongjiaw** [comment]
this PR had some issue, I created another one. Closing this one.

**Comment by yongjiaw** [comment]
https://github.com/apache/spark/pull/9321

**Pull request closed without merging**
