### PR TITLE
[SPARK-32298][ML] tree models prediction optimization

### PR DESCRIPTION
**Pull request by zhengruifeng**
### What changes were proposed in this pull request?
use while-loop instead of the recursive way

### Why are the changes needed?
3% ~ 10% faster

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
existing testsuites

### CODE REVIEW

**Comment by zhengruifeng** [comment]
test:
```
import org.apache.spark.ml.linalg._
import org.apache.spark.ml.classification._
import org.apache.spark.storage.StorageLevel


val df = spark.read.option("numFeatures", "2000").format("libsvm").load("/data1/Datasets/epsilon/epsilon_normalized.t").withColumn("label", (col("label")+1)/2)
df.persist(StorageLevel.MEMORY_AND_DISK)
df.count



val rf = new RandomForestClassifier().setMaxDepth(10).setNumTrees(100)
val model = rf.fit(df)
model.save("/tmp/rf-model")


val rf2 = new RandomForestClassifier().setMaxDepth(20).setNumTrees(100)
val model2 = rf2.fit(df)
model2.save("/tmp/rf-model-d20")



val model = RandomForestClassificationModel.load("/tmp/rf-model")
val model2 = RandomForestClassificationModel.load("/tmp/rf-model-d20")

val vecs = df.select("features").rdd.map(row => row.getAs[Vector](0)).collect

val start = System.currentTimeMillis; Seq.range(0, 20).foreach{_ => vecs.foreach(model.predict)}; val end = System.currentTimeMillis; end - start


val start = System.currentTimeMillis; Seq.range(0, 20).foreach{_ => vecs.foreach(model2.predict)}; val end = System.currentTimeMillis; end - start
```


Results (durations):
this PR: 167640, 404901
Master: 187645, 416243

**Comment by zhengruifeng** [comment]
friendly ping @huaxingao @srowen @viirya 

Different another attempt to save RAM, this should be a clear optimization. I found that those methods can not be marked `@tailrec`, so I use while-loop instead.

**Comment by viirya** [comment]
Is this also memory optimization? But looks like cpu time optimization from the description?

**Comment by zhengruifeng** [comment]
@viirya  This PR is only on cpu.

**Review by srowen — APPROVED** [review]
Looks good as a clean optimization.

**Comment by huaxingao** [comment]
LGTM

**Review by viirya — APPROVED** [review]

**Comment by srowen** [comment]
Merged to master

**Comment by zhengruifeng** [comment]
Thanks all!

**Pull request closed without merging**
