### PR TITLE
[SPARK-22598][CORE] ExecutorAllocationManager does not requests new executors when executor has failed and target has not changed

### PR DESCRIPTION
**Pull request by liutang123**
## What changes were proposed in this pull request?
ExecutorAllocationManager call ExecutorAllocationClient.requestTotalExecutors to request executors when when target has changed. 

Consider the following scene：
We set spark.dynamicAllocation.minExecutors to 3 and set spark.executor.cores to 1. There is only one stage with 3 tasks. The numExecutorsTarget will be 3.  For some reason, all of the 3 executors failed. Because of numExecutorsTarget has no change, ExecutorAllocationManager will not call ExecutorAllocationClient.requestTotalExecutors to request new executors.

In this PR, we check the number of current executors when target has not changed and request new executors when executors is not enough.

## How was this patch tested?

manual test.

### CODE REVIEW

**Comment by liutang123** [comment]
Jenkins, retest this please

**Comment by liutang123** [comment]
@srowen Would you please look at this when you have time?

**Comment by jerryshao** [comment]
Hi @liutang123 would you mind explaining us the issue you met and how to reproduce it? Currently we don't know what actual issue it is and how to evaluate your changes.

**Comment by liutang123** [comment]
Hi @jerryshao , I modified the info of this PR.

**Comment by jerryshao** [comment]
Does this failure ". For some reason, all of the 3 executors failed. " happened during task running or before task submission? Besides, if you're running on yarn, yarn will bring new executors to meet the requirement, also `ExecutorAllocationManager` will be notified with executor lost/register. Can you please tell us how to reproduce your scenario?

**Comment by liutang123** [comment]
Sorry, I can not reproduce it now. But, sometimes, `ExecutorAllocationManager ` did not request new executors and `YarnSchedulerBackend.requestedTotalExecutors` is 0. I will close this PR now and reopen it next time when I encounter this situation.

**Pull request closed without merging**
