### PR TITLE
[SPARK-19302][DOC][MINOR] Fix the wrong item format in security.md

### PR DESCRIPTION
**Pull request by sarutak**
## What changes were proposed in this pull request?

In docs/security.md, there is a description as follows.

```
 steps to configure the key-stores and the trust-store for the standalone deployment mode is as
 follows:
 * Generate a keys pair for each node
 * Export the public key of the key pair to a file on each node
 * Import all exported public keys into a single trust-store
```

According to markdown format, the first item should follow a blank line.

## How was this patch tested?

Manually tested.

Following captures are rendered web page before and after fix.

* before
before

* after
after

### CODE REVIEW

**Comment by felixcheung** [comment]
LGTM

**Review by srowen — APPROVED** [review]
Are there more instances of this in the docs? Might be worth a quick scan since it's easy to search for all the bulleted lists.

**Comment by sarutak** [comment]
I tried to find other instances but I found none.

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
