### PR TITLE
[SPARK-35881][SQL][FOLLOWUP] Remove the AQE post stage creation extension

### PR DESCRIPTION
**Pull request by cloud-fan**
### What changes were proposed in this pull request?

This is a followup of #33140

It turns out that we may be able to complete the AQE and columnar execution integration without the AQE post stage creation extension. The rule `ApplyColumnarRulesAndInsertTransitions` can add to-columnar transition if the shuffle/broadcast supports columnar.

### Why are the changes needed?

remove APIs that are not needed.

### Does this PR introduce _any_ user-facing change?

No, the APIs are not released yet.

### How was this patch tested?

existing and manual tests

### CODE REVIEW

**Comment by cloud-fan** [comment]
@andygrove  @tgravescs Can you try it out? Thanks!

also cc @dongjoon-hyun @maryannxue

**Review by HyukjinKwon — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you for pinging me. If @andygrove and @tgravescs are okay, I'm +1 with this.

**Comment by tgravescs** [comment]
thanks, we will look at it.  I think we don't need these anymore, but doing some verification on that.  At the same time does it hurt to leave these in case someone wants to use these in the future?

**Comment by dongjoon-hyun** [comment]
Yes, @tgravescs , it's a little so because we cannot remove any *public* things in these days technically. Since this extension api is not released yet, we had better remove now and let someone add it in the future when it becomes inevitable. It might be added with different names according to the contexts which I don't know yet. Or, we can remove this from `branch-3.2` first if we need more discussion.

**Comment by HyukjinKwon** [comment]
Yeah, I would remove it if that's possible before a release too.

**Review by tgravescs — APPROVED** [review]
we verified we don't need this anymore.

**Comment by cloud-fan** [comment]
thanks for the review and verification! merging to master/3.2

**Comment by yaooqinn** [comment]
Late LGTM

**Comment by dongjoon-hyun** [comment]
Thank you all!

**Pull request closed without merging**
