### PR TITLE
[SPARK-8732][Build]added import existential type

### PR DESCRIPTION
**Pull request by tijoparacka**
Added import for  existentials

### CODE REVIEW

**Comment by srowen** [comment]
Please instead take the opportunitiy to clear up all similar compiler warnings. There are many more like this, of the same type, and it would be best not to file tiny PRs/JIRAs to deal with them one by one.

**Comment by tijoparacka** [comment]
Sure I will give a try.

**Comment by srowen** [comment]
@tijoparacka is this still needed? recently, warnings were converted to errors, and I don't think we have any errors in the build now, so I wonder if we need to close this PR or whether it is somehow still needed?

**Comment by srowen** [comment]
I just checked and there seem to be no warnings or errors about existentials in master. Do you mind closing this PR?

**Comment by tijoparacka** [comment]
Sorry to be late . I was held up in some other urgent work. 
We can close this issue.

**Pull request closed without merging**
