### PR TITLE
[SPARK-12733][SQL] Refactor duplicate codes in ProjectCollapsing

### PR DESCRIPTION
**Pull request by viirya**
JIRA: https://issues.apache.org/jira/browse/SPARK-12733

Minor PR to refactor duplicate codes in ProjectCollapsing.

### CODE REVIEW

**Comment by viirya** [comment]
cc @liancheng

**Comment by rxin** [comment]
Thanks for submitting this. Unless it is substantially better or super obvious to review, I'd avoid patches that refactor the optimizer for the sake of refactoring.

**Comment by viirya** [comment]
@rxin Thanks for explanation! Actually this PR is a minor one and it just extracts common codes to few methods to avoid duplication. It is more like to de-duplicate than refactoring, as I can tell.

If you still think we shouldn't change this part. Please let me know, I will close it. Thanks.

**Comment by rxin** [comment]
Yea I took another look - I'd prefer not to do it for the sake of doing it, unless we have a real benefit here. The optimizer is pretty hard to get right.

**Comment by viirya** [comment]
okay. Close it now.

**Pull request closed without merging**
