### PR TITLE
[SPARK-39551][SQL][3.2] Add AQE invalid plan check

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This is a backport of https://github.com/apache/spark/pull/36953

This PR adds a check for invalid plans in AQE replanning process. The check will throw exceptions when it detects an invalid plan, causing AQE to void the current replanning result and keep using the latest valid plan.

### Why are the changes needed?

AQE logical optimization rules can lead to invalid physical plans and cause runtime exceptions as certain physical plan nodes are not compatible with others. E.g., `BroadcastExchangeExec` can only work as a direct child of broadcast join nodes, but it could appear under other incompatible physical plan nodes because of empty relation propagation.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Added UT.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
cc @maryannxue , @cloud-fan , @ulysses-you

**Comment by ulysses-you** [comment]
thank you @dongjoon-hyun help backport , I'm a bit late

**Comment by dongjoon-hyun** [comment]
No problem. I wanted to have this at Apache Spark 3.2.2 RC1 next week. That's the reason why I hurried. :)

**Review by cloud-fan — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
All tests passed. Thank you, @ulysses-you and @cloud-fan .
Merged to branch-3.2.

**Pull request closed without merging**
