### PR TITLE
[SPARK-18428][DOC] Update docs for GraphX

### PR DESCRIPTION
**Pull request by zhengruifeng**
## What changes were proposed in this pull request?
1, Add link of `VertexRDD` and `EdgeRDD`
2, Notify in `Vertex and Edge RDDs` that not all methods are listed
3, `VertexID` -> `VertexId`

## How was this patch tested?
No tests, only docs is modified

### CODE REVIEW

**Comment by rxin** [comment]
So I think what we should really say is that this is just an incomplete list, and then link to the API docs. It is not great to duplicate API docs in two places.

**Comment by zhengruifeng** [comment]
@rxin 
This has already been notified in `Summary List of Operators` : `Note that some function signatures have been simplified (e.g., default arguments and type constraints removed) and some more advanced functionality has been removed so please consult the API docs for the official list of operations.`

But it's not said in `VertexRDD`. I will revert this change and and a notification in `VertexRDD`.

**Comment by zhengruifeng** [comment]
@rxin I update this PR to notify in `Vertex and Edge RDDs` that not all methods are listed and add link of `VertexRDD` and `EdgeRDD`.
BTW, use `VertexId` instead of `VertexID`

**Comment by rxin** [comment]
Thanks - merging in master.

**Pull request closed without merging**
