### PR TITLE
[ML] fix getThresholds logic error

### PR DESCRIPTION
**Pull request by mpjlu**
## What changes were proposed in this pull request?

The logic of getThresholds in ML LogisticRegression is not right, and it doesn't match with the comments. 
The problem is fixed by this PR. 

## How was this patch tested?
The existing test.

### CODE REVIEW

**Comment by sethah** [comment]
What is not right? Could you be more specific? The behavior for master branch seems to align with the comments, but maybe I'm missing it.

**Comment by mpjlu** [comment]
If both threshold and thresholds are not set, the master will return thresholds.

**Comment by sethah** [comment]
@mpjlu This is the behavior I get:

````scala
scala> import org.apache.spark.ml.classification.LogisticRegression
import org.apache.spark.ml.classification.LogisticRegression

scala> val lr = new LogisticRegression()
lr: org.apache.spark.ml.classification.LogisticRegression = logreg_2465e281c48e

scala> lr.getThresholds
java.util.NoSuchElementException: Failed to find a default value for thresholds
...
````
So, it throws an exception when nothing is set, as intended it seems.

**Comment by mpjlu** [comment]
@sethah , thanks, I got it wrong. I will close it.

**Pull request closed without merging**
