### PR TITLE
[SPARK-32785][SQL][DOCS][FOLLOWUP] Update migaration guide for incomplete interval literals

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

Address comments @ https://github.com/apache/spark/pull/29635#discussion_r507241899 to improve migration guide

### Why are the changes needed?

improve migration guide

### Does this PR introduce _any_ user-facing change?

NO，only doc update

### How was this patch tested?

passing GitHub action

### CODE REVIEW

**Comment by yaooqinn** [comment]
cc @maropu @gatorsmile ~ thanks

**Review by maropu — APPROVED** [review]

**Comment by maropu** [comment]
@yaooqinn Thanks for the fix and could you fix it in branch-3.0, too?

**Comment by yaooqinn** [comment]
OK~ I will backport this after it gets merged

**Comment by maropu** [comment]
This is trivial, so I merged to master.

**Pull request closed without merging**
