### PR TITLE
[SPARK-14758][ML] Add checking for StepSize and Tol

### PR DESCRIPTION
**Pull request by zhengruifeng**
## What changes were proposed in this pull request?

add the checking for StepSize and Tol in sharedParams
## How was this patch tested?

Unit tests

### CODE REVIEW

**Comment by zhengruifeng** [comment]
cc @srowen 
The ML's sharedParams provide self-contained arg-checking, except the stepSize and Tol.

**Comment by sethah** [comment]
From my understanding `tol` is fairly generic. I tend to agree that `tol` should be > 0, but since convergence tolerance can be specified in many number of ways (with arbitrary units), I'm not sure it should be <= 1. I don't feel too strongly about it though.

**Comment by jkbradley** [comment]
I'd say:
* tol >= 0, but without an upper bound.
* stepSize > 0

**Comment by zhengruifeng** [comment]
@jkbradley @sethah Thanks. I have updated this PR according to your comments.

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
