### PR TITLE
[SPARK-32018][SQL][2.4] UnsafeRow.setDecimal should set null with overflowed value

### PR DESCRIPTION
**Pull request by cloud-fan**
backport https://github.com/apache/spark/pull/29125

### CODE REVIEW

**Comment by cloud-fan** [comment]
cc @dongjoon-hyun

**Comment by dongjoon-hyun** [comment]
Thank you, @cloud-fan !

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Merged to branch-2.4.

**Comment by cloud-fan** [comment]
I'm reverting it from 2.4, see https://github.com/apache/spark/pull/29448#issuecomment-674723823

**Comment by dongjoon-hyun** [comment]
Got it. I understand the situation. Thank you for the decision, @cloud-fan .

**Pull request closed without merging**
