### PR TITLE
[SPARK-37484][CORE][SQL] Replace `get` and `getOrElse` with `getOrElse`

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
There are some combined calls of `get` and `getOrElse` in Spark code, we can call `getOrElse` directly in this scene.

**Before**

```
val map = Map(1 -> 42)
map.get(key).getOrElse(defValue)
```

**After**

```
val map = Map(1 -> 42)
map.getOrElse(key, defValue)
```

### Why are the changes needed?
Code simplification

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?

- Pass the Jenkins or GitHub Action

### CODE REVIEW

**Comment by srowen** [comment]
Also fine; any others? I want to make sure we don't do this module by module

**Review by HyukjinKwon — APPROVED** [review]

**Comment by LuciferYang** [comment]
Yes, that should be all

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by LuciferYang** [comment]
thanks all

**Pull request closed without merging**
