### PR TITLE
[SPARK-16781] [PYSPARK] java launched by PySpark as gateway may not be the same java used in the spark environment

### PR DESCRIPTION
**Pull request by srowen**
## What changes were proposed in this pull request?

Update to py4j 0.10.3 to enable JAVA_HOME support
## How was this patch tested?

Pyspark tests

### CODE REVIEW

**Comment by srowen** [comment]
CC @holdenk @davies for a look

**Comment by srowen** [comment]
Or @MLnick, anyone who might have opinions on Python. I think this is low risk for master, but will wait until tomorrow.

**Comment by holdenk** [comment]
The Py4J upgrade looks good to me & noted the update in the Py4J changelog for using JAVA_HOME in the 0.10.3 releases. +1

**Comment by srowen** [comment]
Merged to master/2.0. This was 'seconded' by https://issues.apache.org/jira/browse/SPARK-17220

**Pull request closed without merging**
