### PR TITLE
SPARK-44111: Bump jetty to v11

### PR DESCRIPTION
**Pull request by HiuKwok**

### CODE REVIEW

**Comment by HiuKwok** [comment]
WIP

**Comment by dongjoon-hyun** [comment]
To @HiuKwok , the JIRA ID is wrong.

**Comment by dongjoon-hyun** [comment]
I close this PR in order to prevent any accidental review and merge on a wrong ID.
Please use a correct JIRA ID and reopen this.

**Comment by bjornjorgensen** [comment]
@HiuKwok it is [SPARK-46938](https://issues.apache.org/jira/browse/SPARK-46938) 
SPARK-44111 is for apache spark 4.0

**Comment by HiuKwok** [comment]
Thanks, both, I will reopen another one.

**Pull request closed without merging**
