### PR TITLE
[SPARK-39495][SQL][TESTS] Support `SPARK_TEST_HIVE_CLIENT_VERSIONS` for `HiveClientVersions`

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to introduce a test environment variable `SPARK_TEST_HIVE_CLIENT_VERSIONS` to control the test target HiveClient Versions in `HiveClientVersions` trait.

### Why are the changes needed?

Currently, `HiveClientVersions` is used in three test suites.
```
$ git grep 'with HiveClientVersions'
sql/hive/src/test/scala/org/apache/spark/sql/hive/client/HiveClientSuites.scala:class HiveClientSuites extends SparkFunSuite with HiveClientVersions {
sql/hive/src/test/scala/org/apache/spark/sql/hive/client/HiveClientUserNameSuites.scala:class HiveClientUserNameSuites extends Suite with HiveClientVersions {
sql/hive/src/test/scala/org/apache/spark/sql/hive/client/HivePartitionFilteringSuites.scala:class HivePartitionFilteringSuites extends Suite with HiveClientVersions {
```

### Does this PR introduce _any_ user-facing change?

No. This is a test only change.

### How was this patch tested?

Pass the CIs and manually test like the following.
```
SPARK_TEST_HIVE_CLIENT_VERSIONS='' build/sbt "hive/testOnly *.HiveClientSuites" -Phive
SPARK_TEST_HIVE_CLIENT_VERSIONS=3.1 build/sbt "hive/testOnly *.HiveClientSuites" -Phive
SPARK_TEST_HIVE_CLIENT_VERSIONS=3.0,3.1 build/sbt "hive/testOnly *.HiveClientSuites" -Phive
```

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Could you review this, @sunchao ?

**Review by HyukjinKwon — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @HyukjinKwon !

**Comment by dongjoon-hyun** [comment]
All tests passed. Merged to master.

**Comment by sunchao** [comment]
Late LGTM too

**Comment by dongjoon-hyun** [comment]
Thank you, @sunchao .

**Pull request closed without merging**
