### PR TITLE
[SPARK-28093][SPARK-28109][SQL][2.4] Fix TRIM/LTRIM/RTRIM function parameter order issue

### PR DESCRIPTION
**Pull request by wangyum**
## What changes were proposed in this pull request?

This pr backport #24902 and #24911 to branch-2.4.

## How was this patch tested?

unit tests

### CODE REVIEW

**Comment by wangyum** [comment]
retest this please

**Comment by wangyum** [comment]
@dongjoon-hyun Please do not merge this into `branch-2.4`. I found a new bug.

**Comment by dongjoon-hyun** [comment]
Okay. What is the JIRA id for the new bug?

**Comment by wangyum** [comment]
It's [SPARK-28109](https://issues.apache.org/jira/browse/SPARK-28109)

**Comment by dongjoon-hyun** [comment]
This PR doesn't have that syntax, does it?

**Comment by dongjoon-hyun** [comment]
I don't think we need [SPARK-28075](ab6bb8fc1ca9f31fc18de8a299a89658aff878fa) here.

**Comment by dongjoon-hyun** [comment]
#24911 is merged. Please proceed at your pace.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @wangyum .
Merged to branch-2.4.
cc @gatorsmile

**Comment by gatorsmile** [comment]
I still prefer to adding the migration guide for this breaking change.  cc @wangyum

**Comment by gatorsmile** [comment]
After rethinking about it, I think we should not fix it in the maintenance releases. This will break the workloads of the existing users who must rely on the previous order. Could we revert this PR?

**Pull request closed without merging**
