### PR TITLE
[SPARK-28719] [Build] Enable Github Actions for master

### PR DESCRIPTION
**Pull request by dbtsai**
## What changes were proposed in this pull request?

Github now provides free CI/CD for build, test, and deploy. This PR enables a simple Github Actions to build master with JDK8 with latest Ubuntu. We can extend it with different versions of JDK, and even build Spark with docker images in the future.

### CODE REVIEW

**Comment by dbtsai** [comment]
cc @dongjoon-hyun

**Comment by dongjoon-hyun** [comment]
I support this approach.

cc @rxin and @srowen .

**Comment by srowen** [comment]
I think it's worth trying. In an ideal world I think we have one CI/CD system rather than a combination Amplab Jenkins, Appveyor, and Github (we're not also on Travis right?). I support experimenting, but would rather subtract than add complexity. It might be easier long-term to get onto Github from Amplab, merely because access to the latter is quite separate from the Github permissions that committers already will have. But let's see how much Github can support the CI/CD we need. It might be a good excuse to simplify the gnarly build environment that's built up over time on Amplab.

**Comment by dbtsai** [comment]
What intrigues me is Github actions supports docker build, so we can use it to customize our build environment for our need. All the configuration will be in yaml file which will also give us more visibility than the current Amplab build infra. 

I'm merging it now to try it out. 

Thanks.

**Comment by dbtsai** [comment]
Okay, first build by github actions succeeded. https://github.com/apache/spark/commit/601fd458143b5f24f42c61e4645b64c6e96f3486/checks

**Comment by dongjoon-hyun** [comment]
Ya. Looks nice. Thank you, @dbtsai !
Screen Shot 2019-08-13 at 4 16 59 PM

**Comment by HyukjinKwon** [comment]
+1 for this try.

**Comment by dbtsai** [comment]
@HyukjinKwon Github Actions supports windows build, so we might be able to remove Appveyor.

**Comment by HyukjinKwon** [comment]
That's cool if possible. I will take a look when I fine some more time.

For a quick FYI to share, actually Appveyor build is dependent on some environment such as Cygwin (Spark build is not supported in a native Windows machine) sadly so might not be easy I guess ..

**Pull request closed without merging**
