### PR TITLE
[SPARK-37347][SQL] Spark Thrift Server (STS) driver fullFC becourse of timeoutExecutor not shutdown correctly

### PR DESCRIPTION
**Pull request by lk246**
### What changes were proposed in this pull request?

Add timeoutExecutor shutdown method in SparkExecuteStatementOperation and shut down when statement finished or error.

### Why are the changes needed?

When spark.sql.thriftServer.queryTimeout or java.sql.Statement.setQueryTimeout is setted >0 , SparkExecuteStatementOperation add timeoutExecutor to kill time-consumed query in SPARK-26533. But timeoutExecutor is not shutdown correctly when statement is finished, it can only be shutdown when timeout. When we set timeout to a long time for example 1 hour, the long-running STS driver will FullGC and the application is not available for a long time.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

No

### CODE REVIEW

**Comment by advancedxy** [comment]
>  But timeoutExecutor is not shutdown correctly when statement is finished
Could you elaborate more on this? 

Also, is it possible for you to add a unit test for this case.

**Comment by lk246** [comment]
> > But timeoutExecutor is not shutdown correctly when statement is finished
> > Could you elaborate more on this?
> 
> Also, is it possible for you to add a unit test for this case.
When we set spark.sql.thriftServer.queryTimeout to 10800s, and STS running for a long time and finish some query submiited  by jdbc.We dump the driver heap and find there are too many thread named 'pool-*-thread-1' and dirver heap is full. 
When we set spark.sql.thriftServer.queryTimeout to 0s,the above phenomenon did not occur again.
image

**Comment by lk246** [comment]
> > But timeoutExecutor is not shutdown correctly when statement is finished
> > Could you elaborate more on this?
> 
> Also, is it possible for you to add a unit test for this case.
When we set spark.sql.thriftServer.queryTimeout to 10800s, and STS running for a long time and finish some query submiited  by jdbc.We dump the driver heap and find there are too many thread named 'pool-*-thread-1' and dirver heap is full. 
When we set spark.sql.thriftServer.queryTimeout to 0s,the above phenomenon did not occur again.
image

**Comment by AngersZhuuuu** [comment]
Title `because`?

**Comment by advancedxy** [comment]
> Also, is it possible for you to add a unit test for this case.
> When we set spark.sql.thriftServer.queryTimeout to 10800s, and STS running for a long time and finish some query submiited  by jdbc.We dump the driver heap and find there are too many thread named 'pool-*-thread-1' and dirver heap is full.
> When we set spark.sql.thriftServer.queryTimeout to 0s,the above phenomenon did not occur again.
> image


So the problem is that the timeoutExecutor doesn't shutdown timely?  The thread will be living at least `timeout` duration even the statement has already finished. This will be a problem for a heavy sts.

**Comment by advancedxy** [comment]
> > Also, is it possible for you to add a unit test for this case.
> > When we set spark.sql.thriftServer.queryTimeout to 10800s, and STS running for a long time and finish some query submiited  by jdbc.We dump the driver heap and find there are too many thread named 'pool-*-thread-1' and dirver heap is full.
> > When we set spark.sql.thriftServer.queryTimeout to 0s,the above phenomenon did not occur again.
> > image
> 
> So the problem is that the timeoutExecutor doesn't shutdown timely? The thread will be living at least `timeout` duration even the statement has already finished. This will be a problem for a heavy sts.

A unit test should possible to check the number of timeout threads for normal queries.

**Pull request closed without merging**
