### PR TITLE
[SPARK-18422][CORE] Fix wholeTextFiles test to pass on Windows in JavaAPISuite

### PR DESCRIPTION
**Pull request by HyukjinKwon**
## What changes were proposed in this pull request?

This PR fixes the test `wholeTextFiles` in `JavaAPISuite.java`. This is failed due to the different path format on Windows.

For example, the path in `container` was

```
C:\projects\spark\target\tmp\1478967560189-0/part-00000
```

whereas `new URI(res._1()).getPath()` was as below:

```
/C:/projects/spark/target/tmp/1478967560189-0/part-00000
```

## How was this patch tested?

Tests in `JavaAPISuite.java`.

Tested via AppVeyor.

**Before**
Build: https://ci.appveyor.com/project/spark-test/spark/build/63-JavaAPISuite-1
Diff: https://github.com/apache/spark/compare/master...spark-test:JavaAPISuite-1

```
[info] Test org.apache.spark.JavaAPISuite.wholeTextFiles started
[error] Test org.apache.spark.JavaAPISuite.wholeTextFiles failed: java.lang.AssertionError: expected:<spark is easy to use.
[error] > but was:<null>, took 0.578 sec
[error]     at org.apache.spark.JavaAPISuite.wholeTextFiles(JavaAPISuite.java:1089)
...
```

**After**
Build started: [CORE] `org.apache.spark.JavaAPISuite` [PR-15866](https://ci.appveyor.com/project/spark-test/spark/branch/198DDA52-F201-4D2B-BE2F-244E0C1725B2)
Diff: https://github.com/apache/spark/compare/master...spark-test:198DDA52-F201-4D2B-BE2F-244E0C1725B2

```
[info] Test org.apache.spark.JavaAPISuite.wholeTextFiles started
...
```

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Build started: [CORE] `org.apache.spark.JavaAPISuite` [PR-15866](https://ci.appveyor.com/project/spark-test/spark/branch/EAC49351-734B-4218-A2CF-13B3C3CB83E8)
Diff: https://github.com/apache/spark/compare/master...spark-test:EAC49351-734B-4218-A2CF-13B3C3CB83E8

**Comment by HyukjinKwon** [comment]
@srowen It seems `org.apache.spark.JavaAPISuite.writeWithNewAPIHadoopFile` is also being failed but the root cause seems different. That is being failed with the exception as below:

```
java.io.IOException: Could not rename file:
...
```

And, other failures specified in the parent JIRA of this seems caused by the problems in `ReceiverTracker` we discussed in https://github.com/apache/spark/pull/15618

Will try to make another PR soon for this.

**Review by srowen — APPROVED** [review]
I'm OK with this, but if the point is to avoid hard-coding "/", is it sufficient to use the `File(String, String)` constructor? whatever works and is most consistent with other tests is OK by me. I know they're not that consistent now anyway.

**Comment by HyukjinKwon** [comment]
Thank you Sean. Actually, this is a bit annoying.

Here is what happens in the original test.

1. Writes a file to read back by `wholeTextFiles`. 

  ```scala
  scala> new File("C:\\a", "/part-0000")
  res10: java.io.File = C:\a\part-0000
  ```

2. and then save the path in a map, `container`.

  ```scala
  scala> val container = Map("C:\\a/part-0000" -> "contents")
  res1: scala.collection.immutable.Map[String,String] = Map(C:\a/part-0000 -> contents)
  ```

3. then it compares the key in `container` to the collected paths from `wholeTextFiles`. The path should be

  ```scala
  scala> val path = "file:/C:/a/part-0000"
  path: String = file:/C:/a/part-0000

  scala> val actualPath = new URI(path).getPath
  res2: String = /C:/a/part-0000
  scala> 
  ```

4. it ends up with..

  ```scala
  scala> container.contains(actualPath)
  res4: Boolean = false
  ```

Just FWIW, (at least for myself to note this problem somewhere and re-visit sometime), it seems both back-slash and slash are fine with `java.io.File`.

```scala
scala> new File("C:/a")
res9: java.io.File = C:\a

scala> new File("C:\\a", "/part-0000")
res10: java.io.File = C:\a\part-0000
```

**Comment by HyukjinKwon** [comment]
Let me add a comment here and will try to clean up more.

**Review by srowen — APPROVED** [review]
OK I trust your judgment about how best to fix it.

**Comment by HyukjinKwon** [comment]
Build started: [CORE] `org.apache.spark.JavaAPISuite` [PR-15866](https://ci.appveyor.com/project/spark-test/spark/branch/198DDA52-F201-4D2B-BE2F-244E0C1725B2)
Diff: https://github.com/apache/spark/compare/master...spark-test:198DDA52-F201-4D2B-BE2F-244E0C1725B2

**Comment by srowen** [comment]
Looks OK to me @HyukjinKwon but does the appveyor result in your comment above mean that it still fails on Windows?

**Comment by HyukjinKwon** [comment]
Oh, the test this PR tries to deal with, `org.apache.spark.JavaAPISuite.wholeTextFiles` is passed. However, another test in here `org.apache.spark.JavaAPISuite.writeWithNewAPIHadoopFile` is being failed for a different reason which I am investigating this.

**Before**

```
[info] Test org.apache.spark.JavaAPISuite.wholeTextFiles started
[error] Test org.apache.spark.JavaAPISuite.wholeTextFiles failed: java.lang.AssertionError: expected:<spark is easy to use.
[error] > but was:<null>, took 0.578 sec
[error]     at org.apache.spark.JavaAPISuite.wholeTextFiles(JavaAPISuite.java:1089)
[error]     ...
```

**After**

```
[info] Test org.apache.spark.JavaAPISuite.wholeTextFiles started
...
[info] Test org.apache.spark.JavaAPISuite.writeWithNewAPIHadoopFile started
[error] Test org.apache.spark.JavaAPISuite.writeWithNewAPIHadoopFile failed: org.apache.spark.SparkException: Job aborted., took 0.407 sec
```

**Comment by srowen** [comment]
OK if it makes the test in question here pass, let's merge it, as a fix for that test. That much is OK right @HyukjinKwon ?

**Comment by HyukjinKwon** [comment]
Yes please. I am pretty sure that this is a right fix without any other side effects.

**Comment by srowen** [comment]
Merged to master/2.1

**Pull request closed without merging**
