### PR TITLE
[SPARK-17721][MLlib][backport] Fix for multiplying transposed SparseMatrix with SparseVector

### PR DESCRIPTION
**Pull request by bwahlgreen**
Backport PR of changes relevant to mllib only, but otherwise identical to #15296 

@jkbradley

### CODE REVIEW

**Comment by srowen** [comment]
Jenkins add to whitelist

**Comment by jkbradley** [comment]
LGTM, merging with branch-1.6 and branch-1.5
Thanks @bwahlgreen !

**Comment by jkbradley** [comment]
Actually, before I merge, could you please update the PR title to match the other PR's title, but with a [backport] tag?

**Comment by rxin** [comment]
+1 on updating the title. The current title doesn't really explain what the pr is.

**Comment by bwahlgreen** [comment]
there 😄

**Comment by jkbradley** [comment]
Perfect, thanks!  Merging now

**Comment by jkbradley** [comment]
Since this is a backport, you'll need to close this manually. Thanks!

**Pull request closed without merging**
