### PR TITLE
[SPARK-16485][DOC][ML] Remove useless latex in a log messge.

### PR DESCRIPTION
**Pull request by lins05**
## What changes were proposed in this pull request?

Removed useless latex in a log messge.
## How was this patch tested?

Check generated scaladoc.

### CODE REVIEW

**Comment by srowen** [comment]
Do a search for some latex tags and you'll find more, like AFTSurvivalRegression.scala, LinearRegression.scala, etc

**Comment by srowen** [comment]
@lins05 can you update with a fix for the additional occurrences?

**Comment by lins05** [comment]
@srowen I have looked about those files, but for complex equations, (e.g. [this one](https://github.com/apache/spark/blob/v2.0.0/mllib/src/main/scala/org/apache/spark/ml/regression/LinearRegression.scala#L778-L782)) I found it difficult to strip the latex symbols without affecting the readability of the javadoc: With the latex symbols there, the users can copy the equation and feed it to a latex viewer like [mathjax online previewer](https://cdn.mathjax.org/mathjax/latest/test/sample-dynamic.html), but it would make it impossible if we remove latex symbols from it.

Meanwhile I find it's possible to use MathJax to render the latex in the scaladoc, as long as we add the necessary javascript to load the MathJax in the scaladoc javascript template. I played with it a bit and you can see the screenshot:

screen shot 2016-07-31 at 12 41 38 am

Do you think it's a good idea to do it?

**Comment by srowen** [comment]
OK, you're saying that the latex in scaladoc could serve some purpose, and where it's not distracting, best left alone. I'm OK with that. I suppose we can still fix the log message. Either close this PR or limit it to the log, as you see fit.

**Comment by lins05** [comment]
@srowen I removed other changes in the PR (only left the fix for the log message), and created a new JIRA [SPARK-16822](https://issues.apache.org/jira/browse/SPARK-16822) for supporting latex in scaladoc.

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
