### PR TITLE
[SPARK-44890][BUILD]Update miswritten remarks

### PR DESCRIPTION
**Pull request by chenyu0513**
It needs to maintain the same writing style as other places instead of miswritten remarks

### CODE REVIEW

**Comment by chenyu-opensource** [comment]
@LuciferYang  please give me a review.
Thank you so much.

**Comment by chenyu-opensource** [comment]
I am responsible for the operation and maintenance of Spark components in the company, and I will continue to participate in the community in the later stage. I hope to have the opportunity to learn from you.

**Comment by LuciferYang** [comment]
@chenyu-opensource Could you also fix the other typos in this `pom.xml`?  Furthermore, you need to fill in the pr description according to the entries in the 'pull request template'.

**Comment by chenyu-opensource** [comment]
> @chenyu-opensource Could you also fix the other typos in this `pom.xml`? Furthermore, you need to fill in the pr description according to the entries in the 'pull request template'.

@LuciferYang Thank you so much for your suggestion. It is my first time to submit a pr for spark.
I will close this pr，then i will follow you suggestion and submit a new pr.
Thank you again.

**Pull request closed without merging**
