### PR TITLE
Revert [SPARK-23094] Fix invalid character handling in JsonDataSource

### PR DESCRIPTION
**Pull request by gatorsmile**
## What changes were proposed in this pull request?
This PR is to revert the PR https://github.com/apache/spark/pull/20302, because it causes a regression.

## How was this patch tested?
N/A

### CODE REVIEW

**Comment by gatorsmile** [comment]
cc @brkyvz @MaxGekk @dongjoon-hyun @HyukjinKwon @hvanhovell

**Comment by brkyvz** [comment]
LGTM, my initial assumption that files had to be UTF-8 encoded was a wrong one :(

**Comment by HyukjinKwon** [comment]
Wait .. do we formally support UTF-16 encoded files in line by line parsing via JSON? I think this accidentally works because the newline character in UTF-8 is the part of UTF-16.

I think I am fine to revert it but how about we avoid adding a test?

**Comment by dongjoon-hyun** [comment]
The failure seems to be irrelevant to this.
```
org.apache.spark.sql.execution.streaming.RateSourceV2Suite.basic microbatch execution
```

**Comment by dongjoon-hyun** [comment]
Retest this please

**Comment by gatorsmile** [comment]
Saw the history. Our UTF-16 support is pretty weak. Let me revert the test case.

**Review by HyukjinKwon — APPROVED** [review]
Seems we should remove the UTF-16 file too.

LGTM too.

**Comment by gatorsmile** [comment]
Since this is just to remove the file and the previous test already passed, I would merge it to master/2.3. Thanks!

**Comment by gatorsmile** [comment]
BTW, the ongoing test will be killed by -9 at midnight

**Pull request closed without merging**
