### PR TITLE
[SPARK-44321][CONNECT] Decouple ParseException from AnalysisException

### PR DESCRIPTION
**Pull request by hvanhovell**
### What changes were proposed in this pull request?
This PR decouples ParseException from AnalysisException.

### Why are the changes needed?
We are moving (parts of) parsing to sql/api to share (datatype) parsing between connect and sql.

### Does this PR introduce _any_ user-facing change?
Yes and no. This is a breaking change in the sense that the parent class of the ParseException changes from AnalysisException to SparkException.

### How was this patch tested?
Existing tests.

### CODE REVIEW

**Comment by hvanhovell** [comment]
cc @amaliujia

**Review by MaxGekk — COMMENTED** [review]
> > This is a breaking change in the sense that the parent class of the ParseException changes from AnalysisException to SparkException.

Since it is, could you update the SQL migration guide.

**Comment by hvanhovell** [comment]
@MaxGekk where can I find that?

**Comment by MaxGekk** [comment]
>where can I find that?

docs/sql-migration-guide.md

**Review by MaxGekk — APPROVED** [review]
Waiting for CI.

**Review by amaliujia — APPROVED** [review]

**Comment by hvanhovell** [comment]
Unrelated failure. Merging.

**Pull request closed without merging**
