### PR TITLE
[SPARK-12200][SQL] Add __contains__ implementation to Row

### PR DESCRIPTION
**Pull request by maver1ck**
https://issues.apache.org/jira/browse/SPARK-12200

### CODE REVIEW

**Comment by holdenk** [comment]
So the JIRA description says it will be doing this instead of some previous behaviour (namely it was perhaps checking values before) - if we do make this change we should probably make sure to document it.

**Comment by maver1ck** [comment]
Yes.
Now, it'll be consistent with Python documentation:
https://docs.python.org/3/reference/datamodel.html

**Comment by holdenk** [comment]
Being consistent with the python datamodel is probably good, just important not to surprise anyone whose code may have been written against the old assumptions.

**Comment by maver1ck** [comment]
OK. I will add few words to documentation.

**Comment by maver1ck** [comment]
Done.

**Comment by maver1ck** [comment]
@holdenk 
Is it OK to merge this patch ?

**Comment by maver1ck** [comment]
@holdenk 
Do you need something more ?

**Comment by maver1ck** [comment]
@holdenk , @davies 
Can anyone verify this patch ?

**Comment by holdenk** [comment]
maybe @jkbradley could take a look?

**Comment by HyukjinKwon** [comment]
Maybe we might have to correct the title just like the others, `[SPARK-XXXX][SQL]` (this is described in https://cwiki.apache.org/confluence/display/SPARK/Contributing+to+Spark).
Also, it would be better if the PR description is updated.

**Comment by HyukjinKwon** [comment]
Maybe @davies because I see most of codes are written by him

**Comment by davies** [comment]
I think it's confusing to support this, for example, you could access the column by `row['col_name']`, but `'col_name' in row` will return False.

**Comment by maver1ck** [comment]
@davies 
But you mentioned current behaviour.

My patch is to change it, so you could access the column by `row['col_name']` and `'col_name' in row` will return **True**.

**Comment by davies** [comment]
@maver1ck Sorry, I misunderstood it. LGTM

**Comment by maver1ck** [comment]
@davies
I fixed whitespaces. Can we test this one more time ?

**Comment by holdenk** [comment]
@maver1ck normally Jenkins will automatically retest on push (although there can be some delay if there is a backlog).

**Comment by maver1ck** [comment]
@holdenk 
Thanks :)

@davies 
I think everything is OK. Can we merge it also into 2.0 branch ?

**Comment by davies** [comment]
cc @rxin  on the sematics change.

**Comment by rxin** [comment]
LGTM - merging in master/2.0.

**Pull request closed without merging**
