### PR TITLE
[SPARK-13363][SQL] Support Aggregator in DataFrame

### PR DESCRIPTION
**Pull request by maropu**
Support user-defined `Aggregator`s in DataFrame.
Currently, the code below does not work because of an unresolved error in `CheckAnalysis`.

```
val simpleSum = new SqlAggregator[Int, Int, Int] {
  def zero: Int = 0                     // The initial value.
  def reduce(b: Int, a: Int) = b + a    // Add an element to the running total
  def merge(b1: Int, b2: Int) = b1 + b2 // Merge intermediate values.
  def finish(b: Int) = b                // Return the final result.
}.toColumn

val df = sc.makeRDD(1 to 3).map(i => (i, i)).toDF("k", "v")
df.groupBy("k").agg(simpleSum).show
```

This pr fix this and add tests according to `DatasetAggregatorSuite`.

### CODE REVIEW

**Comment by maropu** [comment]
Jenkins, retest this please.

**Comment by cloud-fan** [comment]
We are merging DataFrame and Dataset now, I think we should revisit this PR after that.

**Comment by maropu** [comment]
@cloud-fan okay, after the merging finished, I'll revisit this.

**Comment by rxin** [comment]
@maropu mind closing this for now?

**Pull request closed without merging**
