### PR TITLE
[MINOR][TEST]Off -heap memory leaks for unit tests

### PR DESCRIPTION
**Pull request by 10110346**
## What changes were proposed in this pull request?
Free off -heap memory .
I have checked all the unit tests.

## How was this patch tested?
N/A

### CODE REVIEW

**Comment by srowen** [comment]
Can you fix "off-head" to "off-heap"?
This looks reasonable. Are there other tests where memory isn't freed though?

**Comment by 10110346** [comment]
@srowen  Thanks, I have checked all the unit tests,there are no other tests.

**Review by jiangxb1987 — APPROVED** [review]
LGTM

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
