### PR TITLE
[SPARK-39254][BUILD] Upgrade ZSTD-JNI to 1.5.2-3

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr aims upgrade zstd-jni to 1.5.2-3.

### Why are the changes needed?
This version bring some fix and improvements, for example, this version added [Add NoFinalizer variants for the direct buffer streams.](https://github.com/luben/zstd-jni/commit/31060934c26e080031465702ec369591e12874f8) and [Add methods for streaming (de)compression of direct ByteBuffers.](https://github.com/luben/zstd-jni/commit/510bbd6be80592227c6e5cf8cd8d71cb76c0c279).

All changes as follows:

- https://github.com/luben/zstd-jni/compare/v1.5.2-2...v1.5.2-3

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass GitHub Actions

### CODE REVIEW

**Review by yaooqinn — APPROVED** [review]
LGTM

**Comment by LuciferYang** [comment]
should we merge this ? @yaooqinn

**Comment by yaooqinn** [comment]
thanks, merged to master

**Comment by LuciferYang** [comment]
thanks @yaooqinn

**Pull request closed without merging**
