### PR TITLE
[SPARK-13363][SQL] support Aggregator in RelationalGroupedDataset

### PR DESCRIPTION
**Pull request by cloud-fan**
## What changes were proposed in this pull request?

set the input encoder for `TypedColumn` in `RelationalGroupedDataset.agg`.
## How was this patch tested?

new tests in `DatasetAggregatorSuite`

close https://github.com/apache/spark/pull/11269

This PR brings https://github.com/apache/spark/pull/12359 up to date and fix the compile.

### CODE REVIEW

**Comment by cloud-fan** [comment]
cc @rxin

**Comment by rxin** [comment]
Can you remove "race condition" in the description? It sounds like we actually have a race condition in the code base :)

**Comment by rxin** [comment]
LGTM pending Jenkins.

**Comment by cloud-fan** [comment]
retest this please

**Comment by rxin** [comment]
Merging in master.

**Comment by rxin** [comment]
Merging this failed on my laptop. Can you try merge this yourself? I think we are good to go since the failed tests are unrelated.

**Comment by cloud-fan** [comment]
merging to master!

**Pull request closed without merging**
