### PR TITLE
Updated the "Running Tests" section in README.md with mvn test

### PR DESCRIPTION
**Pull request by mrt**
Replaced ./dev/run-tests with an a mvn test example

### CODE REVIEW

**Comment by srowen** [comment]
Why this change? Using the script should be the right thing to do

**Comment by mrt** [comment]
>> Using the script should be the right thing to do
That's what I thought first and ran the script after building with Maven. It didn't work. If we build with mvn, we would have to run mvn test instead of dev/run-tests. Trying to be consistent with the doc (http://spark.apache.org/docs/latest/building-spark.html) Please correct me if I'm wrong.

**Comment by pwendell** [comment]
Hey Taka, So actually, I think the docs here are correct. You tried to first do "mvn package" and then do "dev/run-tests". That's why it broke. In reality users can either do "mvn packge... mvn test" or do "dev/run-tests". The latter is slightly better because it also runs python tests. So I think it may be best as is

**Comment by mrt** [comment]
Ok. I will close this. But should we mention dec/run-tests in the doc (http://spark.apache.org/docs/latest/building-spark.html) or somewhere else in the main doc?

**Comment by mrt** [comment]
Actually I did run mvn package as follows before running the run-tests and got the problem with run-tests. Let me test it again.

$  build/mvn -Pyarn -Phadoop-2.4 -Dhadoop.version=2.4.0 -DskipTests clean package
$ ./dev/run-tests

**Comment by srowen** [comment]
1 and 2 are the intended usages. You are missing a `-Pyarn` in 1, and I think the clean is unnecessary in 2, but should be OK. I don't see why 3 doesn't work given that it should clean the build, but, it's not necessary to do it that way anyway.

**Pull request closed without merging**
