### PR TITLE
[SPARK-22700][ML] Bucketizer.transform incorrectly drops row containing NaN

### PR DESCRIPTION
**Pull request by zhengruifeng**
## What changes were proposed in this pull request?
only drops the rows containing NaN in the input columns

## How was this patch tested?
existing tests and added tests

### CODE REVIEW

**Comment by zhengruifeng** [comment]
ping @MLnick ?

**Comment by hhbyyh** [comment]
LGTM. Good fix.

**Review by WeichenXu123 — APPROVED** [review]
LGTM.

**Comment by MLnick** [comment]
LGTM thanks! Merged to master

**Comment by jkbradley** [comment]
I'm going to backport this to 2.2 since it's a correctness bug.

**Pull request closed without merging**
