### PR TITLE
[SPARK-49704][BUILD] Upgrade `commons-io` to 2.17.0

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
This PR aims to upgrade `commons-io` from `2.16.1` to `2.17.0`.

### Why are the changes needed?
The full release notes: https://commons.apache.org/proper/commons-io/changes-report.html#a2.17.0

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Thank you, @panbingkun .  Could you attach the benchmark results together?

**Comment by dongjoon-hyun** [comment]
Or, we can remove the benchmark code from this PR.

**Comment by panbingkun** [comment]
> Or, we can remove the benchmark code from this PR.

I'm very sorry, I mistakenly submitted code `/ArrayBinarySearchBenchmark`, which is the logic of another PR. 
I have deleted it. Thank you very much for your reminder! ❤️

**Review by LuciferYang — APPROVED** [review]
LGTM

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @panbingkun and @LuciferYang .
Merged to master.

**Pull request closed without merging**
