### PR TITLE
[SPARK-41506][CONNECT][MINOR]: small fix in python code

### PR DESCRIPTION
**Pull request by dengziming**
### What changes were proposed in this pull request?
Fix small code error, this can't pass my local `lint-python`, not sure why it passed in the CI.

### Why are the changes needed?
it's a bug.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
QA

### CODE REVIEW

**Comment by dengziming** [comment]
ping @zhengruifeng

**Comment by zhengruifeng** [comment]
oh, thank for this catch, I just fix it and other issues related to typed_null in https://github.com/apache/spark/pull/39060

**Comment by zhengruifeng** [comment]
> `this can't pass my local lint-python`

is your env different from the CI?  my local lint-python can not catch this issue

**Comment by srowen** [comment]
Closing as duplicate

**Comment by dengziming** [comment]
Thank you @zhengruifeng @srowen , The response time of Spark project is so short, awesome.

**Pull request closed without merging**
