### PR TITLE
[FOLLOW-UP][SPARK-15616][SQL] Sub Optimizer should include super.postHocOptimizationBatches

### PR DESCRIPTION
**Pull request by Ngone51**
### What changes were proposed in this pull request?

Let sub optimizer's  `postHocOptimizationBatches` also includes super's `postHocOptimizationBatches`.

### Why are the changes needed?

It's necessary according to the design of catalyst optimizer.

### Does this PR introduce any user-facing change?

No.

### How was this patch tested?

Pass jenkins.

### CODE REVIEW

**Comment by Ngone51** [comment]
ping @cloud-fan @fuwhu PTAL.

**Review by cloud-fan — APPROVED** [review]
good catch!

**Comment by cloud-fan** [comment]
thanks, merging to master/3.0!

**Comment by fuwhu** [comment]
good catch! thanks @Ngone51

**Comment by Ngone51** [comment]
thanks all!

**Pull request closed without merging**
