### PR TITLE
[SPARK-7290][ML] Add StringVectorizer

### PR DESCRIPTION
**Pull request by viirya**
JIRA: https://issues.apache.org/jira/browse/SPARK-7290

### CODE REVIEW

**Comment by viirya** [comment]
retest this please.

**Comment by viirya** [comment]
retest this please.

**Comment by mengxr** [comment]
@viirya This is essentially `StringIndexer` + `OneHotEncoder`. So any ideas about code reuse?

**Comment by viirya** [comment]
@mengxr Updated.
But by reusing `StringIndexer` and `OneHotEncoder`, we introduce an intermediate column for `StringIndexer`'s output. Now I use `_` + `outputColumnName` as its column name. It is very rare, but still possibly conflicting with dataset's columns.

**Pull request closed without merging**
