### PR TITLE
[SPARK-15899] [SQL] Fix the construction of the file path with hadoop Path for Spark 2.0

### PR DESCRIPTION
**Pull request by avulanov**
This PR contains the adaptation of https://github.com/apache/spark/pull/13868 for Spark 2.0
## What changes were proposed in this pull request?

Fix the construction of the file path in `SQLConf.scala` and unit tests that rely on this: `SQLConfSuite` and `DDLSuite`. Previous way of construction caused the creation of incorrect path on Windows.
## How was this patch tested?

Run unit tests on Windows

### CODE REVIEW

**Comment by srowen** [comment]
Jenkins test this please

**Comment by srowen** [comment]
Thanks @avulanov for the follow up. Merging to 2.0

**Comment by tOverney** [comment]
When can we expect a spark release with those changes incorporated?

**Comment by srowen** [comment]
You can take a look at the JIRA -- would be in 2.0.1 or 2.1.0 whichever comes first. It could be a month or two before one of those happens. There's a workaround in the JIRA though.

**Comment by Praveenmail2him** [comment]
Can anyone post the sample usage for this exception in Spark 2.0, I'm still facing this exception?

**Comment by HyukjinKwon** [comment]
@srowen Do you mind if I ask this is supposed to be closed (as it is merged into 2.0)?

**Comment by srowen** [comment]
Yes @avulanov can you close it? we can't close it directly and the bot can only close PRs opened vs master.

**Review by Praveenmail2him — APPROVED** [review]
It is fixed.

**Pull request closed without merging**
