### PR TITLE
[MINOR][Web UI] Correctly convert bytes in web UI

### PR DESCRIPTION
**Pull request by jerryshao**
## What changes were proposed in this pull request?

should be 1024 based, not 1000.
## How was this patch tested?

Manually verified.

### CODE REVIEW

**Comment by srowen** [comment]
KB = 1000 bytes, KiB = 1024 bytes. According to the suffixes we're using, 1000 is correct at the moment. Is the display inconsistent with something else in the UI or logs?

**Comment by jerryshao** [comment]
Because in the log it shows Memory MB in 1024 based, while in the web UI it is 1000 based, so this is slightly different.

You could check `Utils#bytesToString`. I think we unify this.

**Comment by srowen** [comment]
Ugh, yeah that's wrong in the sense that we are not showing MB, but MiB. I'd favor fixing the labels here and in Utils.bytesToString?

Then again, I see that we will also parse input of "500kb" as if it's "500KiB", using 1024 not 1000. That's wrong too really. But fixing it means a bit of a behavior change. We can support "500KB" or "500kb" but it would now mean 500*1000 bytes not 500*1024.

Well, maybe best to be consistently wrong than inconsistently wrong. Anyone feel at all inclined to take the hit in behavior change or just leave it?

**Comment by jerryshao** [comment]
I think [here](http://ux.stackexchange.com/questions/13815/files-size-units-kib-vs-kb-vs-kb) has a precise definition. AFAIK in Spark the conversion is 1024 based either KB, K, or kb, KiB is not so commonly used. And we usually treat everything as 1024 based, so it might not be so necessary to differentiate them.

**Comment by srowen** [comment]
Meh, it's still ambiguous and there's a defined way to disambiguate, so it's unfortunate, but I'm OK with a step towards consistency in any event.

**Pull request closed without merging**
