### PR TITLE
[SPARK-48405][BUILD] Upgrade `commons-compress` to 1.26.2

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to upgrade `commons-compress` to `1.26.2`.

### Why are the changes needed?
The full release notes: https://commons.apache.org/proper/commons-compress/changes-report.html#a1.26.2

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by panbingkun** [comment]
cc @dongjoon-hyun @LuciferYang

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM (pending CI)

**Review by yaooqinn — APPROVED** [review]

**Review by LuciferYang — APPROVED** [review]
+1, LGTM (pending tests)

**Comment by yaooqinn** [comment]
Thank you @panbingkun @dongjoon-hyun @LuciferYang 

Merged to master

**Pull request closed without merging**
