### PR TITLE
[SPARK-43904][BUILD] Upgrade jackson to 2.15.2

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
 Upgrade FasterXML jackson from 2.15.1 to 2.15.2

### Why are the changes needed?
New version that fix some bugs, release notes as follows:
- https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.15.2

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA.

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]

**Review by LuciferYang — APPROVED** [review]
+1, LGTM 

But I suggest merge https://github.com/apache/spark/pull/41416 before this one

**Comment by dongjoon-hyun** [comment]
Could you rebase this PR, @panbingkun ?

**Comment by panbingkun** [comment]
Ok, let me do it now.

**Comment by panbingkun** [comment]
> Could you rebase this PR, @panbingkun ?

This is done.

**Comment by bjornjorgensen** [comment]
Spark's published dependencies DO NOT MATCH the manifest file (dev/spark-deps).
To update the manifest file, run './dev/test-dependencies.sh --replace-manifest'.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM (Pending CIs)

**Comment by dongjoon-hyun** [comment]
Merged to master~

**Pull request closed without merging**
