### PR TITLE
[SPARK-46094][CORE][FOLLOW-UP] Mark `writing` as volatile at ExecutorJVMProfiler

### PR DESCRIPTION
**Pull request by wForget**
### What changes were proposed in this pull request?

Mark `writing` as volatile.

### Why are the changes needed?

The `writing` variable is used by multiple threads, we should mark it as volatile.

### Does this PR introduce _any_ user-facing change?

No

### Was this patch authored or co-authored using generative AI tooling?

No

### CODE REVIEW

**Comment by wForget** [comment]
cc @parthchandra

**Review by parthchandra — APPROVED** [review]
LGTM.

**Comment by parthchandra** [comment]
Thank yo ufor the fix @wForget. Can you re-run ci? The failures do not appear to be related.

**Comment by wForget** [comment]
> Thank yo ufor the fix @wForget. Can you re-run ci? The failures do not appear to be related.

thanks for your review, ci has passed

**Comment by HyukjinKwon** [comment]
@wForget mind filling:

> Does this PR introduce any user-facing change?
> How was this patch tested?
> Was this patch authored or co-authored using generative AI tooling?

How did you test, and which errors did you see?

**Comment by wForget** [comment]
> @wForget mind filling:
> 
> > Does this PR introduce any user-facing change?
> > How was this patch tested?
> > Was this patch authored or co-authored using generative AI tooling?
> 
> How did you test, and which errors did you see?

Thank you for your reminder. I didn't encounter any exception, just found it while learning the relevant code.

Since the `writeChunk` method is executed in a new thread, if it is called after `finishWriting()`, I guess exception may occur.

**Comment by wForget** [comment]
> if it is called after finishWriting()

This seems difficult to reproduce, so I have trouble adding a test case to cover this fix. But I guess the `if (!writing) {` judgment is to avoid this, so we should fix it.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
