### PR TITLE
[SPARK-43337][UI][3.3] Asc/desc arrow icons for sorting column does not get displayed in the table column

### PR DESCRIPTION
**Pull request by maytasm**
### Why are the changes needed?
DataTables 1.10.25 broke asc/desc arrow icons for sorting column. The sorting icon is not displayed when the column is clicked to sort by asc/desc. Upgrading DataTables to 1.13.2 fixes this issue. 

### How was this patch tested?
Manual test.

### CODE REVIEW

**Comment by maytasm** [comment]
@srowen @gengliangwang 
Address issue mentioned in https://github.com/apache/spark/pull/36226#issuecomment-1530789474

**Comment by srowen** [comment]
I agree with back-porting. We just need to get tests to pass. Did the UI seem OK in a quick manual test? just want to verify the arrows work.

**Review by dongjoon-hyun — COMMENTED** [review]
Is this the only way to fix the issue, @maytasm ?

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
BTW, please remove this from the PR description, @maytasm .
> The 1.10.25 version of DataTables, that Spark currently uses, seems vulerable: https://security.snyk.io/package/npm/datatables.net/1.10.25. The vulnerability may not affect Spark but it is safer to update.

**Comment by maytasm** [comment]
> I agree with back-porting. We just need to get tests to pass. Did the UI seem OK in a quick manual test? just want to verify the arrows work.

Do you know why the `On pull request update / Notify test workflow` failed? Looks like all the tests passed on https://github.com/apache/spark/pull/41011

**Comment by maytasm** [comment]
> BTW, please remove this from the PR description, @maytasm .
> 
> > The 1.10.25 version of DataTables, that Spark currently uses, seems vulerable: https://security.snyk.io/package/npm/datatables.net/1.10.25. The vulnerability may not affect Spark but it is safer to update.

done

**Comment by maytasm** [comment]
> Is this the only way to fix the issue, @maytasm ?

https://github.com/apache/spark/pull/41011#issuecomment-1531983883

**Comment by maytasm** [comment]
@srowen @dongjoon-hyun 
Here is a simple CSS fix instead: https://github.com/apache/spark/pull/41060

**Comment by srowen** [comment]
Yeah let's go with your alternative

**Pull request closed without merging**
