### PR TITLE
[SPARK-16693][SPARKR] Remove methods deprecated in 2.0.0 or before

### PR DESCRIPTION
**Pull request by felixcheung**
## What changes were proposed in this pull request?

Remove deprecated functions which includes:
SQLContext/HiveContext stuff
sparkR.init
jsonFile
parquetFile
registerTempTable
## How was this patch tested?

unit tests
@shivaram

### CODE REVIEW

**Comment by markhamstra** [comment]
See JIRA comment.

**Comment by shivaram** [comment]
Yeah lets discuss this on JIRA / mailing lists and then get back to this

**Comment by gatorsmile** [comment]
Any update on this PR?

**Comment by gatorsmile** [comment]
We are closing it due to inactivity. please do reopen if you want to push it forward. Thanks!

**Pull request closed without merging**
