### PR TITLE
[SPARK-42608][SQL] Use full inner field names in resolution errors

### PR DESCRIPTION
**Pull request by aokolnychyi**
### What changes were proposed in this pull request?

This PR makes `TableOutputResolver` use full names for inner fields in resolution errors.

### Why are the changes needed?

These changes are needed to avoid confusion when there are multiple inner fields with the same name.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

This PR comes with tests.

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
cc @huaxingao , too

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM (Pending CIs)

cc @cloud-fan

**Review by huaxingao — APPROVED** [review]

**Review by cloud-fan — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Could you check the failures or re-trigger the CI for this PR, @aokolnychyi ?

**Comment by aokolnychyi** [comment]
Test failures don't seem to be related. I see similar failures on other PRs. I think the root cause has been recently reverted in master.

**Comment by dongjoon-hyun** [comment]
You need to re-trigger CI, @aokolnychyi , because we cannot re-trigger for you.

**Comment by dongjoon-hyun** [comment]
Merged to master/3.4 for Apache Spark 3.4.0.
Thank you, @aokolnychyi and all!

**Comment by aokolnychyi** [comment]
Thank you, @dongjoon-hyun @huaxingao @cloud-fan!

**Pull request closed without merging**
