### PR TITLE
[SPARK-33752][SQL][3.1] Avoid the getSimpleMessage of AnalysisException adds semicolon repeatedly

### PR DESCRIPTION
**Pull request by beliefer**
### What changes were proposed in this pull request?
This PR related to #30724. This PR backport the version to branch-3.1

### Why are the changes needed?
Fix a bug, because it adds semicolon repeatedly.

### Does this PR introduce _any_ user-facing change?
Yes. the message of AnalysisException will be correct.

### How was this patch tested?
Jenkins test.

### CODE REVIEW

**Comment by beliefer** [comment]
retest this please

**Comment by beliefer** [comment]
cc @HyukjinKwon

**Comment by HyukjinKwon** [comment]
Thanks.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to branch-3.1.

**Comment by beliefer** [comment]
@HyukjinKwon Thank you

**Pull request closed without merging**
