### PR TITLE
[SPARK-12701] [CORE]  FileAppender should use join to ensure writing thread completion

### PR DESCRIPTION
**Pull request by BryanCutler**
Changed Logging FileAppender to use join in `awaitTermination` to ensure that thread is properly finished before returning.

### CODE REVIEW

**Comment by zsxwing** [comment]
You can also remove `@volatile private var stopped = false`, right?

**Comment by BryanCutler** [comment]
Yeah, that variable is no longer needed - I already removed it.  Did you mean `@volatile private var markedForStopped`?  That one is still used to trigger the thread to exit.

**Comment by zsxwing** [comment]
Oh, sorry. Didn't notice that you already removed it.

**Comment by zsxwing** [comment]
LGTM. Merging to master. Thanks, @BryanCutler

**Comment by BryanCutler** [comment]
No problem!  Thanks @zsxwing

**Comment by srowen** [comment]
Also merged to 1.6

**Pull request closed without merging**
