### PR TITLE
[SPARK-49275][SQL][3.5] Fix return type nullness of the xpath expression

### PR DESCRIPTION
**Pull request by chenhao-db**
### What changes were proposed in this pull request?

This is a cherry-pick of https://github.com/apache/spark/pull/47796.

The `xpath` expression incorrectly marks its return type as array of non-null strings. However, it can actually return an array containing nulls. This can cause NPE in code generation, such as query `select coalesce(xpath(repeat('<a></a>', id), 'a')[0], '') from range(1, 2)`.

### Why are the changes needed?

It avoids potential failures in queries that uses the `xpath` expression.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

A new unit test. It would fail without the change in the PR.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by chenhao-db** [comment]
@MaxGekk here is the PR for 3.5.

**Review by MaxGekk — CHANGES_REQUESTED** [review]
@chenhao-db Could you fix the test failure:
```
- function_base64 *** FAILED *** (6 milliseconds)
[info]   Expected and actual plans do not match:
[info]   
[info]   === Expected Plan ===
[info]   Project [staticinvoke(class org.apache.spark.sql.catalyst.expressions.Base64, StringType, encode, cast(g#0 as binary), true, BinaryType, BooleanType, true, true, true) AS base64(g)#0]
[info]   +- LocalRelation <empty>, [id#0L, a#0, b#0, d#0, e#0, f#0, g#0]
[info]   
[info]   
[info]   === Actual Plan ===
[info]   Project [staticinvoke(class org.apache.spark.sql.catalyst.expressions.Base64, StringType, encode, cast(g#0 as binary), true, BinaryType, BooleanType, true, false, true) AS base64(g)#0]
```

**Comment by chenhao-db** [comment]
@MaxGekk Done. There is actually nothing wrong with my code, but `branch-3.5` was broken and now fixed.

**Review by MaxGekk — APPROVED** [review]

**Comment by MaxGekk** [comment]
+1, LGTM. Merging to 3.5.
Thank you, @chenhao-db.

**Pull request closed without merging**
