### PR TITLE
[SPARK-26977][CORE] Fix warn against subclassing scala.App

### PR DESCRIPTION
**Pull request by manuzhang**
## What changes were proposed in this pull request?

Fix warn against subclassing scala.App

## How was this patch tested?

Manual test

### CODE REVIEW

**Comment by manuzhang** [comment]
@srowen I added more comments based on my learnings from https://www.scala-lang.org/api/current/scala/App.html. As a non-native speaker, I'm not sure they can be easily understood  so feel free to rephrase it. Thanks.

**Comment by srowen** [comment]
I just tried compiling `object MyApp extends scala.App` with Scala 2.12 and I get in the bytecode...
`public final class MyApp$ implements scala/App`.
`class MyApp extends scala.App` yields `public class MyApp implements scala/App`. I don't see any `childMainClass`, etc.

I am actually not sure if this ever worked with the `class` version... it tries to invoke a static main() method, but these classes don't get a static main(); they get a non-static main() though.

I find that the current check works if you check whether "MyApp$" extends `scala.App`.
I'd suggest we just add that to the condition?

**Comment by manuzhang** [comment]
> I find that the current check works if you check whether "MyApp$" extends `scala.App`

Could you please provide a `spark-submit` example ?

Both `spark-submit --class MyApp` (for `class MyApp extends scala.App`) and `spark-submit --class MyApp$` (for `object MyApp extends scala.App`) will fail with 

```
Exception in thread "main" java.lang.IllegalStateException: The main method in the given main class must be static
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:44)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:894)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:198)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:228)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by srowen** [comment]
Heh, it's possible this just doesn't work at all. I don't think we ever envisioned people writing a `scala.App` nor is it tested. If so, it's fine to detect these cases correctly and then just fail rather than warn. Or, just remove this check; it'll fail anyway with a good error. (Or, add a note about scala.App to the exception you get)

**Comment by manuzhang** [comment]
Yes, the warning is actually buried in the massive driver logs. Do you mean we should block all `scala.App` applications ? They will still work if no uninitialized fields are used.

**Comment by srowen** [comment]
Wait, aren't you saying above that they never work? what version does?

**Comment by manuzhang** [comment]
In summary,

1. `spark-submit --class MyApp my-app.jar` works fine 

```scala
object MyApp extends scala.App {

  val spark = SparkSession.builder
    .getOrCreate()

  spark.createDataFrame(Seq("a" -> 1, "b" -> 2, "c" -> 3)).foreachPartition { rowIter =>
    println(rowIter.mkString(","))
  }
```

2. `spark-submit --class MyApp my-app.jar foo` will fail since `foo` is uninitialized (as in [SPARK-4170](https://issues.apache.org/jira/browse/SPARK-4170)

```scala
object MyApp extends scala.App {
  val foo = args(0)
  val spark = SparkSession.builder
    .getOrCreate()

  spark.createDataFrame(Seq("a" -> 1, "b" -> 2, "c" -> 3)).foreachPartition { rowIter =>
      assert(foo != null)
      println(rowIter.mkString(","))
  }
```

3.  `spark-submit --class MyApp$ my-app.jar` fail since `main method must be static`

```scala
object MyApp extends scala.App {
   // whatever
}


4. `spark-submit --class MyApp my-app.jar` fail since `main method must be static`

```scala
class MyApp extends scala.App {
    // whatever
}

**Comment by srowen** [comment]
I get it, I misread your comment. The warning can stay as-is. Now we're back to the original issue. I'm still not clear why you don't just want to check whether `MyApp$` extends `scala.App` then, if the user tries to run `MyApp`. in the `object` case that works, that is the class that extends `scala.App`. I don't see the synthetic fields you are checking.

**Comment by manuzhang** [comment]
When user tries to run `MyApp`, the passed in main class is `MyApp` instead of `MyApp$`. The fix is to check whether `MyApp$` extends `scala.App`.

```
childMainClass == "MyApp"
s"$childMainClass$$" == "MyApp$"
```

**Review by srowen — APPROVED** [review]
I agree then, we are on the same page. The string interpolation syntax was throwing me.

**Comment by srowen** [comment]
Merged to master. Thanks for your patience -- almost all of the delay here was me not reading your comments correctly!

**Comment by manuzhang** [comment]
Thanks for review. 😄

**Pull request closed without merging**
