### PR TITLE
[minor] update dev/create-release/known_translations

### PR DESCRIPTION
**Pull request by cloud-fan**
This is a followup of https://github.com/apache/spark/pull/28861 :
1. sort the names by Github ID, suggested by https://github.com/apache/spark/pull/28861#pullrequestreview-433369190
2. add more full names collected in https://github.com/apache/spark/pull/28861
3. The duplicated entry of `linbojin` is removed.
4. Name format is normalized to First Last name style.

### CODE REVIEW

**Comment by cloud-fan** [comment]
I'll keep this PR open for a few more days, to collect more names in https://github.com/apache/spark/pull/28861

**Comment by cloud-fan** [comment]
cc @srowen @dongjoon-hyun

**Review by dongjoon-hyun — COMMENTED** [review]
Thanks, @cloud-fan . Since this will be updated continuously, I checked only the AS-IS and compared with `master` branch. Names looks correct. 
In the PR description, could you mentioned the followings roughly?

1. The duplicated entry of `linbojin` is removed.
```
244d243
< linbojin - Linbo Jin
```

2. Name format is normalized to `First Last` name style.
```
< LinhongLiu - Liu, Linhong
---
> LinhongLiu - Linhong Liu
```

**Comment by cloud-fan** [comment]
Done

**Comment by dongjoon-hyun** [comment]
Thanks~

**Review by dongjoon-hyun — APPROVED** [review]

**Comment by cloud-fan** [comment]
no more updates from https://github.com/apache/spark/pull/28861 , I'm merging to now, thanks!

**Pull request closed without merging**
