### PR TITLE
[SPARK-21111] [TEST] [2.2] Fix the test failure of describe.sql

### PR DESCRIPTION
**Pull request by gatorsmile**
## What changes were proposed in this pull request?
Test failed in `describe.sql`. 

We need to fix the related bug introduced in (https://github.com/apache/spark/pull/17649) in the follow-up PR to master. 

## How was this patch tested?
N/A

### CODE REVIEW

**Comment by gatorsmile** [comment]
cc @yhuai @cloud-fan @sameeragarwal

**Comment by yhuai** [comment]
lgtm

**Comment by gatorsmile** [comment]
retest this please

**Comment by cloud-fan** [comment]
LGTM

**Comment by yhuai** [comment]
thanks! merging to branch-2.2

**Comment by yhuai** [comment]
Thanks! I have merged this pr to branch-2.2.

**Pull request closed without merging**
