### PR TITLE
[MINOR][BUILD] Fix lint-js

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to fix lint-js.

### Why are the changes needed?
https://github.com/panbingkun/spark/actions/runs/6306820397/job/17123186216
image

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Manually test.
image

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by panbingkun** [comment]
cc @yaooqinn

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by zhengruifeng** [comment]
thank you @panbingkun for this quick fix

**Comment by dongjoon-hyun** [comment]
Thank you, @panbingkun !

**Pull request closed without merging**
