### PR TITLE
Failing test for parquet predicate pushdown on columns with dots

### PR DESCRIPTION
**Pull request by ash211**
// checking against Jenkins to make sure this is still live on master

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
I just checked the cause. It seems dot in the column names via `FilterAPI` tries to separate the field name with dot (`ColumnPath` with multiple column paths) whereas the actual column name is `col.dots`.

I just tried several ways to solve this. One is simply to don't push down filters when there are dots in column names. The other way is override `FilterApi` so that we can get a field name via `ColumnPath.get` not `ColumnPath.fromDotString`.

**Comment by HyukjinKwon** [comment]
Do you mind if I open a JIRA and work on it if you are currently not @ash211? and also, could you confirm my investigation is correct and choose one of both ways if I was right @liancheng ?

**Comment by ash211** [comment]
@HyukjinKwon thanks for looking at this!  Please feel free to open a Jira so we can begin discussing a fix.  I haven't started working on a patch yet, only have the test case at this point.  So if you come up with a solution I'd love to see it!

cc @robert3005

**Comment by HyukjinKwon** [comment]
Sure. Thank you for confirmation. Let me cc you in the JIRA.

**Comment by HyukjinKwon** [comment]
I just filed in https://issues.apache.org/jira/browse/SPARK-20364 and I cc'ed you both (I hope the ids were correct). We could close this for now maybe :).

**Comment by ash211** [comment]
Agreed, will close for now until there's a fix to go along with the test

**Pull request closed without merging**
