### PR TITLE
[MINOR][DOCS] Add `docs/_generated/` to .gitignore

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

This PR adds the auto-generated content `docs/_generated/` to .gitignore

### Why are the changes needed?

vcs improvement 

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

existing tests

### Was this patch authored or co-authored using generative AI tooling?

no

### CODE REVIEW

**Review by zhengruifeng — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Merged to master.

**Comment by yaooqinn** [comment]
Thank you @dongjoon-hyun @zhengruifeng

**Comment by yaooqinn** [comment]
Thank you @nchammas

**Comment by yaooqinn** [comment]
cherry-picked this to branch-3.5

**Pull request closed without merging**
