### PR TITLE
[SPARK-8660] [MLLib] removed > symbols from comments in LogisticRegressionSuite.scala for ease of copypaste

### PR DESCRIPTION
**Pull request by Rosstin**
'>' symbols removed from comments in LogisticRegressionSuite.scala, for ease of copypaste

also single-lined the multiline commands (is this desirable, or does it violate style?)

### CODE REVIEW

**Comment by Rosstin** [comment]
@mengxr Would it be desirable to un-multiline the LOC in the file's comments? Or should these remain multiline to follow style? (What I mean is, the lines are long enough that they were being broken into multiple lines, so copy-pasting them would be harder. I made them back into single-line.)

**Comment by holdenk** [comment]
For copypasteing in Scala mode :paste mode makes the multi-line copy/past work well (although requires remembering that + ctrl-d)

**Comment by mengxr** [comment]
Let's keep the line width within 100. As @holdenk mentioned, we can copy & paste a paragraph of code to Scala and ipython easily. I also tried RStudio, which takes multiline statement as well.

**Comment by Rosstin** [comment]
@mengxr @holdenk Alright, I restored the multiline comments conforming to the 100-character rule

**Comment by mengxr** [comment]
ok to test

**Comment by mengxr** [comment]
LGTM pending Jenkins.

**Comment by mengxr** [comment]
Merged into master. Thanks!

**Pull request closed without merging**
