### PR TITLE
[FOLLOWUP][SPARK-32175] Remove flaky test added in SPARK-32175

### PR DESCRIPTION
**Pull request by sarutak**
### What changes were proposed in this pull request?

This PR removes a test added in SPARK-32175(#29002).

### Why are the changes needed?

That test is flaky. It can be mitigated by increasing the timeout but it would rather be simpler to remove the test.
See also the [discussion](https://github.com/apache/spark/pull/29002#issuecomment-666746857).

### Does this PR introduce _any_ user-facing change?

No.

### CODE REVIEW

**Comment by sarutak** [comment]
cc: @tgravescs, @HyukjinKwon

**Comment by sarutak** [comment]
This PR just removes existing test, so I'll merge this, not waiting the CI result.

**Comment by HyukjinKwon** [comment]
LGTM, thanks!

**Comment by sarutak** [comment]
Merged into `master` and `branch-3.0`.

**Pull request closed without merging**
