### PR TITLE
[SPARK-26774][CORE] Update some docs on TaskSchedulerImpl.

### PR DESCRIPTION
**Pull request by squito**
A couple of places in TaskSchedulerImpl could use a minor doc update on
threading concerns.  There is one bug fix here, but only in
sc.killTaskAttempt() which is probably not used much.

### CODE REVIEW

**Comment by squito** [comment]
@pghandi999 @Ngone51 @jiangxb1987 @markhamstra 
Nothing major here, I just thought a few doc updates would help this part of the code.  (I did discover a race condition, but one that is probably irrelevant most of the time.)  I actually originally filed this jira b/c I thought the problem was much worse, but in any case I still think its worth trying to update this a bit.

I will be gone next week so no rush on this, but thought I'd post this before I forgot about it completely.

**Comment by squito** [comment]
Oops, @pgandhi999 I got your handle wrong the first time, so pinging you again :)

**Comment by pgandhi999** [comment]
Is the HashMap `executorIdToRunningTaskIds` also protected by "this"? If not, should it be protected?

**Review by felixcheung — APPROVED** [review]

**Review by Ngone51 — APPROVED** [review]
Good catch for these two `synchronized `. And I think we're safe previously because they were only called from unit test, probably.

**Review by jiangxb1987 — APPROVED** [review]
LGTM

**Comment by jiangxb1987** [comment]
> Is the HashMap `executorIdToRunningTaskIds` also protected by "this"? If not, should it be protected?

IIUC `executorIdToRunningTaskIds` has already been protected, maybe we shall also update its comment.

**Comment by pgandhi999** [comment]
@jiangxb1987 ok, makes sense. LGTM.

**Comment by vanzin** [comment]
Merging to master.

**Pull request closed without merging**
