### PR TITLE
[SPARK-40620] [CORE] Simplify make offers

### PR DESCRIPTION
**Pull request by khalidmammadov**
### What changes were proposed in this pull request?

WorkerOffer build in CoarseGrainedSchedulerBackend is repeated two different places with exact same parameters. We can simplify, deduplicate and increase readability by moving that to a private function

### Why are the changes needed?
Code deduplication and increase readability.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Local build and test

### CODE REVIEW

**Comment by amaliujia** [comment]
If we ever wish to tackle this, will that make more sense to adopt `Builder` pattern that have every place of `new WorkerOffer` to go through such `buildWorkerOffer`?

I found 80+ place that use `new WorkerOffer` and they can be converted to `WorkerOffer.Builder().addExecutorId().addExecutorData().addHost()....`.

**Comment by khalidmammadov** [comment]
> If we ever wish to tackle this, will that make more sense to adopt `Builder` pattern that have every place of `new WorkerOffer` to go through such `buildWorkerOffer`?
> 
> I found 80+ place that use `new WorkerOffer` and they can be converted to `WorkerOffer.Builder().addExecutorId().addExecutorData().addHost()....`.
> 
> Seems to me that `buildWorkerOffer` in this PR is more or less trying to go to Builder pattern.

These 80+ are Unit tests aren't they? In reality `WorkerOffer` only used handful of times as part of a `SchedulerBackend` and is not part of user facing API, so not sure how `Builder` pattern will help. This PR is just to remove/replace duplicated code with more readable one as many developers read these codes and when one see this types of dups we start wondering what is the diff.? and only to find out there is none! :) But already energy and time is spent to find this! So, IMHO this PR makes the code more clean, cut and readable.

**Comment by amaliujia** [comment]
> > If we ever wish to tackle this, will that make more sense to adopt `Builder` pattern that have every place of `new WorkerOffer` to go through such `buildWorkerOffer`?
> > I found 80+ place that use `new WorkerOffer` and they can be converted to `WorkerOffer.Builder().addExecutorId().addExecutorData().addHost()....`.
> > Seems to me that `buildWorkerOffer` in this PR is more or less trying to go to Builder pattern.
> 
> These 80+ are Unit tests aren't they? In reality `WorkerOffer` only used handful of times as part of a `SchedulerBackend` and is not part of user facing API, so not sure how `Builder` pattern will help. This PR is just to remove/replace duplicated code with more readable one as many developers read these codes and when one see this types of dups we start wondering what is the diff.? and only to find out there is none! :) But already energy and time is spent to find this! So, IMHO this PR makes the code more clean, cut and readable.

I agree that this PR is useful. I was just thinking that if we can make it help other places. Let's see if other people in community has an opinion.

**Comment by khalidmammadov** [comment]
@srowen please review

**Review by srowen — APPROVED** [review]

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
