### PR TITLE
[SPARK-7762] [MLLIB] set default value for outputCol

### PR DESCRIPTION
**Pull request by mengxr**
Set a default value for `outputCol` instead of forcing users to name it. This is useful for intermediate transformers in the pipeline. @jkbradley

### CODE REVIEW

**Comment by mengxr** [comment]
test this please

**Comment by jkbradley** [comment]
LGTM
This will have a merge conflict with [https://github.com/apache/spark/pull/6139]

**Comment by jkbradley** [comment]
Streaming failure

**Comment by jkbradley** [comment]
Merging into master and branch-1.4

**Comment by jkbradley** [comment]
Oops, 2 sets of tests...glad they passed

**Pull request closed without merging**
