### PR TITLE
[SPARK-7153][SQL] support all integral type ordinal in GetArrayItem

### PR DESCRIPTION
**Pull request by cloud-fan**
first convert `ordinal` to `Number`, then convert to int type.

### CODE REVIEW

**Comment by cloud-fan** [comment]
Jenkins test it please.

**Comment by cloud-fan** [comment]
Hi @rxin , how can I trigger the jenkins to run test?

**Comment by rxin** [comment]
Jenkins, test this please.

**Comment by rxin** [comment]
(I think you need permission from us to do it)

**Comment by cloud-fan** [comment]
Seems Jenkins got a problem...

**Comment by cloud-fan** [comment]
test this please.

**Comment by cloud-fan** [comment]
As we have moved out all `ExtractValue(GetField)` stuff from `complexType.scala`, we should rename it.

**Comment by cloud-fan** [comment]
cc @marmbrus , it's a minor change.

**Comment by marmbrus** [comment]
ok to test

**Comment by cloud-fan** [comment]
retest this please.

**Comment by marmbrus** [comment]
Thanks!  Merging to master.

**Pull request closed without merging**
