### PR TITLE
[SPARK-36137][SQL][FOLLOWUP] Correct the config key in error msg

### PR DESCRIPTION
**Pull request by ulysses-you**
### What changes were proposed in this pull request?

Change `${SQLConf.HIVE_METASTORE_PARTITION_PRUNING_FALLBACK_ON_EXCEPTION}` to `${SQLConf.HIVE_METASTORE_PARTITION_PRUNING_FALLBACK_ON_EXCEPTION.key}`

### Why are the changes needed?

Correct the error msg.

### Does this PR introduce _any_ user-facing change?

yes, the error msg changed

### How was this patch tested?

just an obvious issue.

### CODE REVIEW

**Comment by ulysses-you** [comment]
cc @sunchao

**Review by MaxGekk — APPROVED** [review]

**Review by sarutak — APPROVED** [review]
Pending Jenkins.

**Comment by MaxGekk** [comment]
I am going to merge this because all GAs passed:
Screenshot 2021-12-09 at 09 51 06

**Comment by MaxGekk** [comment]
+1, LGTM. Merging to master.
Thank you, @ulysses-you and @sarutak for review.

**Comment by ulysses-you** [comment]
thank you @MaxGekk @sarutak !

**Comment by sunchao** [comment]
Thanks for the fix @ulysses-you !

**Pull request closed without merging**
