### PR TITLE
[SPARK-5771][UI][hotfix] Change Requested Cores into * if default cores is not set

### PR DESCRIPTION
**Pull request by jerryshao**
cc @andrewor14, @srowen.

### CODE REVIEW

**Comment by srowen** [comment]
Yes that looks good.

**Comment by andrewor14** [comment]
Yes, LGTM thanks for fixing this.

**Comment by andrewor14** [comment]
retest this please

**Comment by andrewor14** [comment]
Per discussion on #4841 I'm reverting this.

**Pull request closed without merging**
