### PR TITLE
[SPARK-33297][BUILD] Switch to use flat class loader strategy in SBT

### PR DESCRIPTION
**Pull request by HyukjinKwon**
### What changes were proposed in this pull request?

This PR proposes to switch the class loader strategy from `ScalaLibrary` to `Flat` (see https://www.scala-sbt.org/1.x/docs/In-Process-Classloaders.html):

https://github.com/apache/spark/runs/1314691686

```
Error:  java.util.MissingResourceException: Can't find bundle for base name org.scalactic.ScalacticBundle, locale en
Error:  	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1581)
Error:  	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1396)
Error:  	at java.util.ResourceBundle.getBundle(ResourceBundle.java:782)
Error:  	at org.scalactic.Resources$.resourceBundle$lzycompute(Resources.scala:8)
Error:  	at org.scalactic.Resources$.resourceBundle(Resources.scala:8)
Error:  	at org.scalactic.Resources$.pleaseDefineScalacticFillFilePathnameEnvVar(Resources.scala:256)
Error:  	at org.scalactic.source.PositionMacro$PositionMacroImpl.apply(PositionMacro.scala:65)
Error:  	at org.scalactic.source.PositionMacro$.genPosition(PositionMacro.scala:85)
Error:  	at sun.reflect.GeneratedMethodAccessor34.invoke(Unknown Source)
Error:  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Error:  	at java.lang.reflect.Method.invoke(Method.java:498)
```

See also https://github.com/sbt/sbt/issues/5736

### Why are the changes needed?

To make the build unflaky.

### Does this PR introduce _any_ user-facing change?

No, dev-only.

### How was this patch tested?

GitHub Actions build in this test.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
@dongjoon-hyun, @maropu, @gengliangwang, @gemelen, could we merge this and see how it goes if the tests pass?
Seems 5 consecutive builds passed without that issue - I retriggered 5 more builds again just for doubly sure.

**Comment by maropu** [comment]
looks fine. just out of curiosity; this strategy change doesn't affects test running time?

**Comment by HyukjinKwon** [comment]
@maropu, I am not very sure. From reading the doc, seems it dose because it will change a class loader, within SBT, that is used during `test` tasks. I think the SBT maintainer suggested this way by suspecting that there's something wrong in the reused class loader. So by changing it to `Flat`, it won't be reused anymore.

Ideally it should not have any behaviour change even with the default `ScalaLibrary` but seems it did (?).

**Comment by HyukjinKwon** [comment]
I ran the build 15 times. Meaning 150 times build, and I don't see the same error anymore. Other errors look something already going on without this PR.

I am going to merge this.. let's see how it goes.

Merged to master.

**Comment by gemelen** [comment]
Won't it be useful to guard this setting with condition to use only on JVM earlier than 11 then?
// Seems I'm a bit late with that :)

**Comment by HyukjinKwon** [comment]
Oh, @gemelen. Yeah that would have been better. But it's okay because currently there is only one Spark in the release, that is built by JDK 8, that also works on both JDK 8 and JDK 11.

GitHub Actions has a job that builds it with JDK 11 but that's more about a sanity check so we can easily drop JDK 8 and move to JDK 11 later. I think we can just remove this out when we migrate to JDK 11 later.

**Comment by dongjoon-hyun** [comment]
Thank you, @HyukjinKwon !

**Comment by MaxGekk** [comment]
I still observe the issue in https://github.com/apache/spark/pull/30377/checks?check_run_id=1405697533

**Comment by HyukjinKwon** [comment]
Thanks @MaxGekk. It became less frequent given my observation but maybe I was wrong. I will check the builds tomorrow more closely.

**Pull request closed without merging**
