### PR TITLE
[SPARK-25183][SQL] Spark HiveServer2 to use Spark ShutdownHookManager

### PR DESCRIPTION
**Pull request by steveloughran**
## What changes were proposed in this pull request?

Switch `org.apache.hive.service.server.HiveServer2` to register its shutdown callback with Spark's `ShutdownHookManager`, rather than direct with the Java Runtime callback.

This avoids race conditions in shutdown where the filesystem is shutdown before the flush/write/rename of the event log is completed, particularly on object stores where the write and rename can be slow.

## How was this patch tested?

There's no explicit unit for test this, which is consistent with every other shutdown hook in the codebase.

* There's an implicit test when the scalatest process is halted.
* More manual/integration testing is needed.

HADOOP-15679 has added the ability to explicitly execute the hadoop shutdown hook sequence which spark uses; that could be stabilized for testing if desired, after which all the spark hooks could be tested. Until then: external system tests only.

### CODE REVIEW

**Comment by steveloughran** [comment]
Not sure what is up with the build here; worked with mvn locally. Possibly my use of a java 8 lamda-expression as the hook?

**Comment by jerryshao** [comment]
My local maven build also failed.

I think the problem is that`ShutdownHookManager` is implemented in Scala, the complied method signature may be different when invoked from Java, I'm not sure how Scala anonymous function is translated to Java, but it seems like due to this issue.

(Maven has some detailed failure information, whereas SBT doesn't have anything).

**Comment by steveloughran** [comment]
my local maven build *did* work, so maybe its a javac/JVM version thing. Will move back to a java class callback.

**Comment by steveloughran** [comment]
My local build wasn't including that module; it now does and the link works with a subclass of `AbstractFunction0<BoxUnit>`.

The local tests are failing under maven with hive/jackson mismatch though. I'm going to consider that a separate issue.

```
#c=cvalue;d=dvalue
- SPARK-16563 ThriftCLIService FetchResults repeat fetching result *** FAILED ***
  java.sql.SQLException: java.lang.NoSuchMethodError: org.json4s.jackson.JsonMethods$.parse$default$3()Z
  at org.apache.hive.jdbc.HiveStatement.execute(HiveStatement.java:296)
  at org.apache.spark.sql.hive.thriftserver.HiveThriftJdbcTest$$anonfun$withMultipleConnectionJdbcStatement$2.apply(HiveThriftServer2Suites.scala:814)
  at org.apache.spark.sql.hive.thriftserver.HiveThriftJdbcTest$$anonfun$withMultipleConnectionJdbcStatement$2.apply(HiveThriftServer2Suites.scala:813)
  at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
  at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
  at org.apache.spark.sql.hive.thriftserver.HiveThriftJdbcTest.withMultipleConnectionJdbcStatement(HiveThriftServer2Suites.scala:813)
  at org.apache.spark.sql.hive.thriftserver.HiveThriftJdbcTest.withJdbcStatement(HiveThriftServer2Suites.scala:822)
  at org.apache.spark.sql.hive.thriftserver.HiveThriftBinaryServerSuite$$anonfun$2$$anonfun$apply$mcV$sp$2.apply(HiveThriftServer2Suites.scala:100)
  at org.apache.spark.sql.hive.thriftserver.HiveThriftBinaryServerSuite$$anonfun$2$$anonfun$apply$mcV$sp$2.apply(HiveThriftServer2Suites.scala:96)
  at org.apache.spark.sql.hive.thriftserver.HiveThriftBinaryServerSuite.org$apache$spark$sql$hive$thriftserver$HiveThriftBinaryServerSuite$$withCLIServiceClient(HiveThriftServer2Suites.scala:71)
```

**Comment by jerryshao** [comment]
The fix itself LGTM, but I don't think this could solve the STS shutdown hook conflict problem with Hadoop.

**Comment by steveloughran** [comment]
This will eliminate a race condition between FS shutdown (in the hadoop shutdown manager) and the hive callback. Theres a risk today that the filesystems will be closed before that event log close()/rename() is called, so things don't get saved —and this can happen with any FS.

registering the shutdown hook via the spark APIs, with a priority > than the FS shutdown, guarantees that it will be called before the FS shutdown. But it doesn't guarantee that the operation will complete within the 10s time limit hard coded into Hadoop 2.8.x+ for any single shutdown hook to complete. It is going to work in HDFS except in the special case of HDFS NN lock or GC pause.

The Hadoop configurable delay of [HADOOP-15679](https://issues.apache.org/jira/browse/HADOOP-15679) needs to go in. I've increased the default timeout to 30s there for more forgiveness with HDFS, and for object stores with O(data) renames people should configure it with a timeout of minutes, or, if they want to turn it off altogether, hours. 

I'm backporting HADOOP-15679 to all branches 2.8.x+, so all hadoop versions with that timeout will have the timeout configurable & the default time extended.

**Comment by jerryshao** [comment]
I see. Thanks for the explain, I checked the code again, yes you're right. Let me retrigger the test again, will merge it if everything is fine.

**Comment by jerryshao** [comment]
Jenkins, retest this please.

**Comment by jerryshao** [comment]
Merging to master branch.

**Comment by steveloughran** [comment]
thanks

**Pull request closed without merging**
