### PR TITLE
[SPARK-28635][SQL][followup] CatalogManager should reflect the changes of default catalog

### PR DESCRIPTION
**Pull request by cloud-fan**
### What changes were proposed in this pull request?

The current namespace/catalog should be set to None at the beginning, so that we can read the new configs when reporting currennt namespace/catalog later.

### Why are the changes needed?

Fix a bug in CatalogManager, to reflect the change of default catalog config when reporting current catalog.

### Does this PR introduce any user-facing change?

No. The current namespace/catalog stuff is still internal right now.

### How was this patch tested?

a new test suite

### CODE REVIEW

**Comment by cloud-fan** [comment]
cc @imback82 @brkyvz @rdblue

**Review by imback82 — APPROVED** [review]
LGTM

**Comment by gengliangwang** [comment]
retest this please.

**Comment by rdblue** [comment]
+1

**Review by gengliangwang — APPROVED** [review]

**Comment by brkyvz** [comment]
LGTM as well

**Comment by brkyvz** [comment]
Merging to master

**Pull request closed without merging**
