### PR TITLE
[SPARK-9492] [ML] [R] LogisticRegression in R should provide model statistics

### PR DESCRIPTION
**Pull request by yanboliang**
Like ml `LinearRegression`, `LogisticRegression` should provide a training summary including feature names and their coefficients.

### CODE REVIEW

**Comment by yanboliang** [comment]
This PR depends on #9302 , after it merged I will add this test case which has passed on my local test environment.
```R
test_that("summary coefficients match with native glm of Logistic Regression", {
  df <- createDataFrame(sqlContext, iris)
  training <- filter(df, df$Species != "setosa")
  stats <- summary(glm(Species ~ Sepal_Length + Sepal_Width, data = training, family = "binomial"))
  coefs <- as.vector(stats$coefficients)

  rTraining <- iris[iris$Species %in% c("versicolor","virginica"),]
  rCoefs <- as.vector(coef(glm(Species ~ Sepal.Length + Sepal.Width, data = rTraining,
    family = binomial(link = "logit"))))

  expect_true(all(abs(rCoefs - coefs) < 1e-4))
  expect_true(all(
    as.character(stats$features) ==
    c("(Intercept)", "Sepal_Length", "Sepal_Width")))
})
```

**Comment by mengxr** [comment]
@yanboliang Could you rebase master?

**Comment by yanboliang** [comment]
Jenkins, test this please.

**Comment by mengxr** [comment]
LGTM. Merged into master. Thanks!

**Pull request closed without merging**
