### PR TITLE
[SPARK-38489][SQL] Aggregate.groupOnly support foldable expressions

### PR DESCRIPTION
**Pull request by wangyum**
### What changes were proposed in this pull request?

This pr makes `Aggregate.groupOnly` support foldable expressions.

### Why are the changes needed?

Improve query performance.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Unit test.

### CODE REVIEW

**Review by cloud-fan — APPROVED** [review]
I checked all the caller sides of `groupOnly`, all look fine

**Comment by cloud-fan** [comment]
`AggregateOptimizeSuite.SPARK-34808: aggregateExpressions only contains groupingExpressions` fails

**Comment by wangyum** [comment]
Fixed it.

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Pull request closed without merging**
