### PR TITLE
[SPARK-20157]In the menu ‘Storage’in Web UI, click the Go button, and…

### PR DESCRIPTION
**Pull request by guoxiaolongzte**
… shows no paging menu interface.

## What changes were proposed in this pull request?

Choose 'show' text box, fill in the data to show a number greater than or equal to the data to the total number of article. Click on the "Go" button, display interface display the total number of the data, but the page menu disappear, cause I want to continue to choose "show" text box and fill in the article to show the data number, can only leave the interface, select specific link click again come in to look at it.

## How was this patch tested?

 manual tests

### CODE REVIEW

**Comment by srowen** [comment]
@guoxiaolongzte please fix the PR description.
CC @zsxwing  I think this may be correct.

**Comment by guoxiaolongzte** [comment]
Ok, I have fixed the PR description.

**Comment by ajbozarth** [comment]
I actually brought this up with @zsxwing (who designed the paging) in a previous PR and he said this was intentional. The idea is that when a table is too small for paging the paging options shouldn't be shown. This does mean if you expand the table to larger than the total rows the paging options will disappear. Given it can be found again by going "back" in your browser I believe leaving it as designed is better (@zsxwing had to convince me of this during our previous discussion). 

**If** we decide to update this we should do it across all paged tables in the UI not just the storage tab though.

**Comment by guoxiaolongzte** [comment]
I think this design is not reasonable, because I may need to look at all, but I have a look at the time I need to query the page.I can do it  across all paged tables in the UI.

**Comment by guoxiaolongzte** [comment]
if you expand the table to equal the total rows the paging options will disappear. This is too unreasonable. For me a large number of data pages show, it is not convenient and reasonable.

**Comment by guoxiaolongzte** [comment]
Please help to code view,thank you.

**Comment by srowen** [comment]
I don't see the issue here. If you expand the table such that no paging is needed, why do you need to page? if more rows are added you need to refresh to see them anyway. Going back is the natural thing to do if you really want to get back to the previous view, in this corner case. If it was at all intentional, I'd leave it.

**Comment by guoxiaolongzte** [comment]
Sometimes watch I need to see all data, sometimes watch I need to see the paging data, if I go back, the cache data if too much, and I need to find a long time. But if the solution to this problem, I just don't take a long time to find my view of a certain cache table data

**Comment by guoxiaolongzte** [comment]
@srowen

**Comment by srowen** [comment]
I don't quite understand what cached data has to do with it -- is some of this accomplished without a page reload? I'd defer to @ajbozarth et al here.

**Comment by guoxiaolongzte** [comment]
@ajbozarth
Sometimes watch I need to see all data, sometimes watch I need to see the paging data, if I go back, the cache data if too much, and I need to find a long time. But if the solution to this problem, I just don't take a long time to find my view of a certain cache table data.Spark a powerful UI, rather than relying on more of the browser's back button.

**Comment by ajbozarth** [comment]
I'm not quite sure what you mean by cached, but the way paging is implemented every time you change the row count or page number it's a new page load/refresh, so the latest data will be shown (if it's still running). In short the paging is implemented with url params and a refresh so there is no caching

**Comment by guoxiaolongzte** [comment]
@ajbozarth
I now need to constantly switch pageSize to change paging data. Sometimes I want to see all the data, but now show all the data, page area is lost. When I quit, I have to re-select the cache table url I just clicked. If cache table data very much, I found just click to view the cache table, need to spend more time.
If all pageSize is displayed, the page area is not lost, and I can change pageSize again and click the Go button to view the paging data to better view the data.

**Comment by srowen** [comment]
I'm sorry I still don't understand the issue.  In your example, you just hit 'back' to go back from an unpaged view to paged. I think this should be closed given feedback.

**Comment by guoxiaolongzte** [comment]
@srowen 
In jobs in web ui,Choose 'show' text box, fill in the data to show a number greater than or equal to the data to the total number of article. Click on the "Go" button, display interface display the total number of the data, but the page menu no disappear.
In storage in web ui,
Choose 'show' text box, fill in the data to show a number greater than or equal to the data to the total number of article. Click on the "Go" button, display interface display the total number of the data, but the page menu disappear.
I still feel that I changed the more reasonable.

Please refer to the attachment new.png of 'SPARK-20157'.
issue url:https://issues.apache.org/jira/browse/SPARK-20157.

**Pull request closed without merging**
