### PR TITLE
[SPARK-16966] [SQL] [CORE] App Name is a randomUUID even when "spark.app.name" exists

### PR DESCRIPTION
**Pull request by srowen**
## What changes were proposed in this pull request?

Don't override spark.app.name in SparkSession when making a new context, as it will override spark.app.name in SparkConf, and will have already been checked anyway by SparkSubmit
## How was this patch tested?

Jenkins tests.

### CODE REVIEW

**Comment by vanzin** [comment]
Hmm... not all apps start via spark-submit; so it is possible to create a SparkSession before setting the app's name; in which case the `SparkContext.getOrCreate` call (a few lines below your change to SparkSession.scala) could fail if no context currently exists.

Instead, shouldn't the code use `sparkConf.setIfMissing` after the SparkConf is instantiated?

**Comment by srowen** [comment]
The thing is, we've always set an app name in all tests and examples, so I have presumed that it's required even if running without spark-submit. I'd assume the same behavior is assumed for SparkSession. In fact, all the code does set app name, except the one test suite. I assumed it might have been a quick band-aid and not the best solution. Yes you can also check the conf for spark.app.name; it just seemed funny to intro new behavior and another different place and way to set a default name.

**Comment by vanzin** [comment]
I'm personally fine with "things break if you don't set app name", but that's not the expectation set in the API:

```
    /**
     * Sets a name for the application, which will be shown in the Spark web UI.
     * If no application name is set, a randomly generated name will be used.
     *
     * @since 2.0.0
     */
    def appName(name: String): Builder = config("spark.app.name", name)
```

So technically that would be breaking the current API.

**Comment by srowen** [comment]
True, darn. If it's been promised as behavior, I think we'd have to keep the behavior. OK, backing up ...

**Pull request closed without merging**
