### PR TITLE
[SPARK-11272] [Web UI] Add support for downloading event logs from HistoryServer UI

### PR DESCRIPTION
**Pull request by ajbozarth**
## What changes were proposed in this pull request?

This is a reworked PR based on feedback in #9238 after it was closed and not reopened. As suggested in that PR I've only added the download feature. This functionality already exists in the api and this allows easier access to download event logs to share with others.

I've attached a screenshot of the committed version, but I will also include alternate options with screen shots in the comments below. I'm personally not sure which option is best.
## How was this patch tested?

Manual testing 

screen shot 2016-10-07 at 6 11 12 pm

### CODE REVIEW

**Comment by ajbozarth** [comment]
The above screen shot shows a version with an Event Log column that allows download of each application attempt individually. Below is the same without a button:
screen shot 2016-10-07 at 5 59 45 pm


The next two versions don't have a separate column and are a download link for each application, meaning if there's more than one attempt there's only one link to download them all zipped together:
screen shot 2016-10-07 at 4 39 58 pm
screen shot 2016-10-07 at 5 05 29 pm

The last one is tied as my preference with the one I committed, it just a matter of if we want the download to be per application or attempt

**Comment by ajbozarth** [comment]
@steveloughran @andrewor14 Would you be willing to take a look at this and give some feedback since you reviewed the original pr for this?

**Comment by andrewor14** [comment]
retest this please

**Comment by ajbozarth** [comment]
@andrewor14 Is there a reason you retested this? Just wondering since it had already passed tests.

**Comment by andrewor14** [comment]
Usually we retest the PR if it's been a few days since it last ran tests. We have had build breaks before where we merged a PR that passed tests a long time ago.

**Comment by andrewor14** [comment]
This one LGTM I'm merging it into master. Thanks for working on this.

**Pull request closed without merging**
