### PR TITLE
[SPARK-14355][BUILD] Fix typos in Exception/Testcase/Comments and static analysis results

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
## What changes were proposed in this pull request?

This PR contains the following 5 types of maintenance fix over 59 files (+94 lines, -93 lines).
- Fix typos(exception/log strings, testcase name, comments) in 44 lines.
- Fix lint-java errors (MaxLineLength) in 6 lines. (New codes after SPARK-14011)
- Use diamond operators in 40 lines. (New codes after SPARK-13702)
- Fix redundant semicolon in 5 lines.
- Rename class `InferSchemaSuite` to `CSVInferSchemaSuite` in CSVInferSchemaSuite.scala.
## How was this patch tested?

Manual and pass the Jenkins tests.

### CODE REVIEW

**Comment by srowen** [comment]
LGTM

**Comment by dongjoon-hyun** [comment]
Thank you, @srowen .

**Comment by rxin** [comment]
Thanks - merging in master.

**Comment by dongjoon-hyun** [comment]
Thank you, @rxin .

**Pull request closed without merging**
