### PR TITLE
[SPARK-39025][SPARK-39026][K8S] Support k8s tolerations feature for spark

### PR DESCRIPTION
**Pull request by dcoliversun**

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Hi, @dcoliversun . Did you try `PodTemplate` before? Is it insufficient for your use case?

**Comment by dcoliversun** [comment]
@dongjoon-hyun Hi, I tried it before, but unfortunately it didn't fit the needs. 

We need a more flexible spark configuration instead of going through template yaml files. `podTemplate` is not suitable for scheduling jobs on multiple k8s clusters. Different k8s clusters have different configurations. yaml files add complexity to the scheduler. Parameter configuration will be lighter.

**Comment by dongjoon-hyun** [comment]
Could you elaborate how did you try and fail?
> Hi, I tried it before, but unfortunately it didn't fit the needs.

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
@dcoliversun . `podTemplate` is the most flexible way which is applicable for various Spark versions instead of a fixed code. If there is no justification for introducing new configurations like `spark.kubernetes.executor.tolerations.xxx`, I'm -1 for this PR. 

Please feel free to reopen this with a proper justification where `podTemplate` is unable to set pod `toleration`.

**Comment by dcoliversun** [comment]
@dongjoon-hyun Thank you, OK with me. And I will evaluate whether `podTemplate` is suitable and try with `podTemplate` again.

**Pull request closed without merging**
