### PR TITLE
[SPARK-34781][SQL][FOLLOWUP] Adjust the order of AQE optimizer rules

### PR DESCRIPTION
**Pull request by ulysses-you**
### What changes were proposed in this pull request?

Reorder  `DemoteBroadcastHashJoin` and `EliminateUnnecessaryJoin`.

### Why are the changes needed?

Skip unnecessary check in `DemoteBroadcastHashJoin` if `EliminateUnnecessaryJoin` affects.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

No result affect.

### CODE REVIEW

**Comment by ulysses-you** [comment]
cc @maropu @cloud-fan @c21

**Review by maropu — APPROVED** [review]

**Comment by ulysses-you** [comment]
@maropu thank you for the so quick speed.

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Comment by ulysses-you** [comment]
thanks for merging!

**Comment by c21** [comment]
Late LGTM, thanks.

**Pull request closed without merging**
