### PR TITLE
[MINOR][SQL] Fix substr/substring testcases.

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
## What changes were proposed in this pull request?

This PR fixes the following two testcases in order to test the correct usages.

```
checkSqlGeneration("SELECT substr('This is a test', 'is')")
checkSqlGeneration("SELECT substring('This is a test', 'is')")
```

Actually, the testcases works but tests on exceptional cases.

```
scala> sql("SELECT substr('This is a test', 'is')")
res0: org.apache.spark.sql.DataFrame = [substring(This is a test, CAST(is AS INT), 2147483647): string]

scala> sql("SELECT substr('This is a test', 'is')").collect()
res1: Array[org.apache.spark.sql.Row] = Array([null])
```
## How was this patch tested?

Pass the modified unit tests.

### CODE REVIEW

**Comment by srowen** [comment]
CC @gatorsmile

**Comment by gatorsmile** [comment]
LGTM

**Comment by dongjoon-hyun** [comment]
Thank you for review, @gatorsmile and @srowen .

**Comment by dongjoon-hyun** [comment]
Hi, @srowen .
Could you merge this PR please?

**Comment by srowen** [comment]
Merged to master

**Comment by dongjoon-hyun** [comment]
Thank you!

**Pull request closed without merging**
