### PR TITLE
[MINOR][SS] Add implementation note on overriding serialize/deserialize in HDFSMetadataLog methods' scaladoc

### PR DESCRIPTION
**Pull request by HeartSaVioR**
### What changes were proposed in this pull request?

The patch adds scaladoc on `HDFSMetadataLog.serialize` and `HDFSMetadataLog.deserialize` for adding implementation note when overriding - HDFSMetadataLog calls `serialize` and `deserialize` inside try-finally and caller will do the resource (input stream, output stream) cleanup, so resource cleanup should not be performed in these methods, but there's no note on this (only code comment, not scaladoc) which is easy to be missed.

### Why are the changes needed?

Contributors who are unfamiliar with the intention seem to think it as a bug if the resource is not cleaned up in serialize/deserialize of subclass of HDFSMetadataLog, and they couldn't know about the intention without reading the code of HDFSMetadataLog. Adding the note as scaladoc would expand the visibility.

### Does this PR introduce any user-facing change?

No

### How was this patch tested?

Just a doc change.

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
cc. @xy2953396112 as creator of origin PR
cc. @cloud-fan @srowen @dongjoon-hyun @HyukjinKwon as they've reviewed origin PR

**Review by HyukjinKwon — APPROVED** [review]
LGTM

**Comment by HyukjinKwon** [comment]
add to whitelist

**Review by cloud-fan — APPROVED** [review]

**Comment by HeartSaVioR** [comment]
retest this, please

**Comment by srowen** [comment]
Merged to master

**Comment by dongjoon-hyun** [comment]
+1, Late LGTM.

**Comment by HeartSaVioR** [comment]
Thanks all for reviewing and merging!

**Pull request closed without merging**
