### PR TITLE
[SPARK-40811][SQL][TESTS] Use `checkError()` to intercept `ParseException`

### PR DESCRIPTION
**Pull request by MaxGekk**
### What changes were proposed in this pull request?
In the PR, I propose to port the following tests suites onto `checkError` to check valuable error parts instead of error messages:
- JDBCWriteSuite
- JDBCTableCatalogSuite
- JdbcUtilsSuite
- CreateTableAsSelectSuite
- SparkScriptTransformationSuite
- SQLViewSuite
- InsertSuite

### Why are the changes needed?
Migration on `checkError()` will make the tests independent from the text of error messages.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
By running the modified test suites:
```
$ build/sbt "test:testOnly *SQLViewSuite"
$ build/sbt -Phive-2.3 -Phive-thriftserver "test:testOnly org.apache.spark.sql.execution.datasources.v2.jdbc.JDBCTableCatalogSuite"
$ build/sbt "test:testOnly *JdbcUtilsSuite"
$ build/sbt -Phive-2.3 -Phive-thriftserver "test:testOnly *SparkScriptTransformationSuite"
```

### CODE REVIEW

**Comment by MaxGekk** [comment]
@panbingkun FYI

**Review by amaliujia — APPROVED** [review]
LGTM!

**Comment by MaxGekk** [comment]
@cloud-fan Could you approve this PR, please.

**Review by cloud-fan — APPROVED** [review]

**Comment by MaxGekk** [comment]
Merging to master. Thank you, @amaliujia and @cloud-fan for review.

**Pull request closed without merging**
