### PR TITLE
[SPARK-42587][CONNECT][TESTS][FOLLOWUP] Fix `scalafmt` failure

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This is a follow-up of https://github.com/apache/spark/pull/40180.

### Why are the changes needed?

At previous PR, `Scalastyle` is checked but `scalafmt` was missed at the last commit.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass all CI linter jobs.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
cc @viirya

**Comment by dongjoon-hyun** [comment]
Now, it passed. 
Screenshot 2023-02-26 at 7 25 33 PM

**Review by hvanhovell — APPROVED** [review]
LGTM

**Comment by dongjoon-hyun** [comment]
Thank you so much, @hvanhovell . Sorry for the troubles.

**Comment by dongjoon-hyun** [comment]
Merged to master/3.4.

**Comment by viirya** [comment]
Looks good.

**Comment by dongjoon-hyun** [comment]
Thank you, @viirya . Sorry for missing at the first PR.

**Pull request closed without merging**
