### PR TITLE
[SPARK-36326][SQL] Use computeIfAbsent to simplify the process of put a absent value into Map

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
The main change of this pr is try to use `computeIfAbsent` to simplify the process of put and get missing value in a map.

**Before**

```java
  V oldValue = map.get(key);
  if (oldValue == null) {
    V newValue = functionToProduceMissValue
    map.put(key, newValue);
  }
```

**After**

```java
map.computeIfAbsent(key, functionToProduceMissValue);
```

### Why are the changes needed?
Simplify code use Java 8 API.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass the Jenkins or GitHub Action

### CODE REVIEW

**Comment by LuciferYang** [comment]
cc @srowen @HyukjinKwon @dongjoon-hyun  It seems that only this place can do such code simplification

**Comment by srowen** [comment]
There is one other instance you could change in AbstractCommandBuilder.getEffectiveConfig

**Comment by LuciferYang** [comment]
> There is one other instance you could change in AbstractCommandBuilder.getEffectiveConfig
OK, let me check this

**Comment by LuciferYang** [comment]
> There is one other instance you could change in AbstractCommandBuilder.getEffectiveConfig

The original method as follows:

```java
  Map<String, String> getEffectiveConfig() throws IOException {
    if (effectiveConfig == null) {
      effectiveConfig = new HashMap<>(conf);
      Properties p = loadPropertiesFile();
      for (String key : p.stringPropertyNames()) {
        if (!effectiveConfig.containsKey(key)) {
          effectiveConfig.put(key, p.getProperty(key));
        }
      }
    }
    return effectiveConfig;
  }
```

**Comment by HyukjinKwon** [comment]
Can we do sth like:

```java
p.stringPropertyNames().forEach(
  key -> effectiveConfig.computeIfAbsent(key, k -> effectiveConfig.put(p.getProperty(k)));
```

?

**Comment by LuciferYang** [comment]
@HyukjinKwon if we choice to use `computeIfAbsent `, Maybe `effectiveConfig.computeIfAbsent(key, p::getProperty)` is enough, it will put the missing `k -> v` into the map

**Comment by HyukjinKwon** [comment]
> ignore the return value of `computeIfAbsent` method.

Thanks. Just trying to understand more. Why is this a problem?

**Comment by LuciferYang** [comment]
I thought about it carefully, there seems to be no problem, I'll update the code and comments, thx @HyukjinKwon

**Review by HyukjinKwon — APPROVED** [review]

**Comment by srowen** [comment]
Merged to master

**Comment by dongjoon-hyun** [comment]
+1, late LGTM. Thank you, @LuciferYang and all!

**Pull request closed without merging**
