### PR TITLE
[SPARK-33774][UI][CORE]"Back to Master" returns 500 error in Standalone cluster

### PR DESCRIPTION
**Pull request by Ngone51**
### What changes were proposed in this pull request?

Initiate the `masterWebUiUrl` with the `webUi. webUrl` instead of the `masterPublicAddress`.

### Why are the changes needed?

Since [SPARK-21642](https://issues.apache.org/jira/browse/SPARK-21642), `WebUI` has changed from `localHostName` to `localCanonicalHostName` as the hostname to set up the web UI. However, the `masterPublicAddress` is from `RpcEnv`'s host address, which still uses `localHostName`. As a result, it returns the wrong Master web URL to the Worker. 

### Does this PR introduce _any_ user-facing change?

Yes, when users click "Back to Master" in the Worker page:

Before this PR:

WeChat4acbfd163f51c76a5f9bc388c7479785

After this PR:

image

(Return to the Master page successfully.)

### How was this patch tested?

Tested manually.

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Hi, @Ngone51 .
If this is caused by SPARK-21642, is this a fix for all Apache Spark 2.3.0+ releases?

**Comment by Ngone51** [comment]
> If this is caused by SPARK-21642, is this a fix for all Apache Spark 2.3.0+ releases?


I thought it's for 2.4+. IIRC, Spark 2.3 is no longer maintained, right?

**Review by srowen — COMMENTED** [review]
Seems OK to back-port to 2.4, yes. 2.3 is EOL.
Does this have any implications, like would this change break any usages you can think of?

**Comment by Ngone51** [comment]
No. `masterWebUiUrl` is used by both `WorkerPage` and `LogPage`. I tested them and both look fine.

In other cases, e.g., when users configure `SPARK_PUBLIC_DNS` or `spark.driver.host` manually, this should not be an issue for them.

**Comment by gengliangwang** [comment]
@Ngone51 I just tried it with 3.0 release and the "Back to Master" works in my local setup.
Did you enable HTTPS in your local env?

**Comment by Ngone51** [comment]
I didn't enable HTTPS. And I also tried with 3.0 release just now and the issue still exists.

**Review by gengliangwang — APPROVED** [review]

**Comment by srowen** [comment]
Jenkins retest this please

**Comment by Ngone51** [comment]
retest this please

**Comment by srowen** [comment]
This is ready to go? just checking given the open/closing.

**Comment by Ngone51** [comment]
It's ready. open/closing is for re-triggering the Github Action test.

**Comment by srowen** [comment]
Merged to master/3.1/3.0

**Comment by Ngone51** [comment]
thanks all!

**Pull request closed without merging**
