### PR TITLE
[SPARK-6416] [DOCS] RDD.fold() requires the operator to be commutative

### PR DESCRIPTION
**Pull request by srowen**
Document current limitation of rdd.fold.

This does not resolve SPARK-6416 but just documents the issue.
CC @JoshRosen

### CODE REVIEW

**Comment by srowen** [comment]
Jenkins, retest this please

**Comment by JoshRosen** [comment]
Busy with other work so I haven't looked in detail, but a couple of drive-by comments:

- I don't think this is a PySpark-specific issue; I think that the same issue affects the Scala / Java APIs, so their docs should be updated as well.
- Why not just say "using a given associative and commutative function" up on line 815?  The current text makes it sound like this is a bug, whereas I'm not even sure that we could / would want to efficiently support non-commutative functions in the future.

**Comment by JoshRosen** [comment]
It still may be worth having a sentence to explicitly state that this doesn't function exactly like fold() would for non-distributed collections, but I'd consider re-wording that paragraph to make the comparison with other languages / frameworks more explicit.

**Comment by srowen** [comment]
Got it, yeah this is actually generic to all distributed scenarios, where the idea of folding left-to-right either doesn't make sense or is expensive to do. I'll update all the docs to note that the op must be commutative and that this isn't quite like Scala's `fold()` as a result.

**Comment by davies** [comment]
LGTM

**Comment by JoshRosen** [comment]
Hey, mind removing PYSPARK from the issue title?

**Comment by JoshRosen** [comment]
LGTM as well.

**Pull request closed without merging**
