### PR TITLE
[SPARK-33058][SQL][KAFKA] Fetch topic partitions once when getting offset ranges

### PR DESCRIPTION
**Pull request by viirya**
### What changes were proposed in this pull request?

This proposes to change `fetchPartitionOffsets` in `KafkaOffsetReader` to fetch topic partition once.

### Why are the changes needed?

Removing unnecessary poll.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by viirya** [comment]
cc @HeartSaVioR

**Comment by viirya** [comment]
cc @maropu @dongjoon-hyun

**Comment by HeartSaVioR** [comment]
@viirya 
Thanks for the PR. We are proposing the "fundamental change" on driver side (#29729) which may be conflicted with this.

Could you please look into #29729 instead and check whether the unnecessary fetch is done even in #29729? It'd be really appreciated if you'd love to review at #29729. Thanks!

**Comment by viirya** [comment]
@HeartSaVioR Thanks. I will take look at #29729

**Comment by viirya** [comment]
Close in favor of #29729.

**Pull request closed without merging**
