### PR TITLE
[SPARK-38017][SQL][DOCS] Fix the API doc for window to say it supports TimestampNTZType too as timeColumn

### PR DESCRIPTION
**Pull request by sarutak**
### What changes were proposed in this pull request?

This PR fixes the API docs for `window` to say it supports `TimestampNTZType` too as `timeColumn`.

### Why are the changes needed?

`window` function supports not only `TimestampType` but also `TimestampNTZType`.

### Does this PR introduce _any_ user-facing change?

Yes, but I don't think this change affects existing users.

### How was this patch tested?

Built the docs with the following commands.
```
bundle install
SKIP_RDOC=1 SKIP_SQLDOC=1 bundle exec jekyll build
```
Then, confirmed the built doc.
window_timestampntz
window_timestmapntz_python

### CODE REVIEW

**Comment by sarutak** [comment]
NOTE: We have a similar issue in `session_window` function too but this issue affects not only `master` but also `branch-3.2`. So I'll separate the JIRA ticket and PR to allow to backport easily.

**Review by HyukjinKwon — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by sarutak** [comment]
Thank you @HyukjinKwon and @dongjoon-hyun . Mergint to `master` for `3.3.0` and `branch-3.2` for `3.2.2`.

**Comment by dongjoon-hyun** [comment]
Hi, @sarutak . This seems to land to branch-3.2 mistakenly because SPARK-36724 is Apache Spark 3.3.0 patch. Could you confirm that? For now, I'd like to finish Apache Spark 3.2.2 and revert this from `branch-3.2` and update the website doc manually.

cc @bersprockets

**Comment by sarutak** [comment]
@dongjoon-hyun Thank you for pinging me. Let me check it.

**Comment by dongjoon-hyun** [comment]
Thank you!

**Comment by sarutak** [comment]
@dongjoon-hyun 
SPARK-36724 is about `SessionWindow`, while this change is about `TimeWindow` and `TimeWindow` seems already support `TimestampNTZ` in v3.2.1.

https://github.com/apache/spark/blob/4f25b3f71238a00508a356591553f2dfa89f8290/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/TimeWindow.scala#L99

So, I think this change still valid.
Do I miss something?

**Comment by dongjoon-hyun** [comment]
Oh, thank you for checking. It seems that I was confused. Could you reply on Apache Spark 3.2.2 RC1 vot3 and correct me, please?

**Comment by sarutak** [comment]
O.K, I'll reply soon.

**Comment by dongjoon-hyun** [comment]
Ah, I guess the code and doc mismatch might be due to SPARK-36227 `Remove TimestampNTZ from API docs`.

cc @gengliangwang , too.

**Comment by dongjoon-hyun** [comment]
According to SPARK-36227, it seems to be hidden intentionally from API due to the incompleteness.
> The type coercion rules for TimestampNTZType are incomplete.

**Comment by dongjoon-hyun** [comment]
WDYT about that, @sarutak ?

**Comment by gengliangwang** [comment]
@dongjoon-hyun @sarutak The TimestampNTZ project is going to release on Spark 3.4.0. So it would be great if we can remove the TimestampNTZ-related doc in 3.2/3.3

**Comment by sarutak** [comment]
Ah, I understand. So, I'll open a PR to revert this change for `branch-3.2`.

**Comment by dongjoon-hyun** [comment]
Thank you for confirming, @gengliangwang and @sarutak .
I believe this is not a blocker for Apache Spark 3.2.2 RC1 vote.
I'm thinking of updating the webpage after release. And, in the worst case, we can mention this doc typo as a known issue section.

**Comment by dongjoon-hyun** [comment]
If you don't mind, could you participate in `Apache Spark 3.2.2 RC1 vote`, please?
It would be great if we can get more community blessing.

**Comment by sarutak** [comment]
> I believe this is not a blocker for Apache Spark 3.2.2 RC1 vote.

Yeah, I don't think this a blocker. And I'll participate in the vote.

**Comment by dongjoon-hyun** [comment]
Thank you so much!

**Comment by dongjoon-hyun** [comment]
I made a PR to Apache Spark website repo.
- https://github.com/apache/spark-website/pull/404

**Pull request closed without merging**
