### PR TITLE
[build] [hotfix] Fix make-distribution.sh for Scala 2.11.

### PR DESCRIPTION
**Pull request by vanzin**

### CODE REVIEW

**Comment by srowen** [comment]
Is the fix the `$@`? LGTM.

**Comment by vanzin** [comment]
Yeah. I also formatted things to look more like the other, similar code. Thanks to @nightwolfzor for pointing it out.

**Comment by srowen** [comment]
CC @pwendell in case this has implications for the 1.3 release. Obviously looks OK to merge to master (jenkins won't test this anyway) but might even be needed at the last moment for 1.3.

**Comment by vanzin** [comment]
No, this doesn't affect 1.3.

**Comment by srowen** [comment]
Ah right, this was just introduced with SPARK-4924. OK good to go

**Pull request closed without merging**
