### PR TITLE
[MINOR][PYTHON] Fix `MultilayerPerceptronClassifierTest.test_raw_and_probability_prediction`

### PR DESCRIPTION
**Pull request by harupy**
### What changes were proposed in this pull request?

- Increase `rtol`.
- Use `numpy.testing.assert_allclose`.

### Why are the changes needed?

- To make the flaky test less likely to fail.
- To get a better assertion error message.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Updated test

### CODE REVIEW

**Review by WeichenXu123 — APPROVED** [review]
LGTM

**Review by dongjoon-hyun — APPROVED** [review]

**Review by zhengruifeng — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @harupy and all. Merged to master for Apache Spark 3.3.

**Comment by HyukjinKwon** [comment]
@harupy this test seems sill flaky:

https://github.com/apache/spark/runs/5725350556
https://github.com/apache/spark/runs/5711097839

Can we increase the tolerance?

**Comment by harupy** [comment]
@HyukjinKwon Filed https://github.com/apache/spark/pull/35997

**Pull request closed without merging**
