### PR TITLE
[SPARK-43922][SQL] Add named parameter support in parser for function calls

### PR DESCRIPTION
**Pull request by learningchess2003**
### What changes were proposed in this pull request?
We plan on adding two new tokens called ```namedArgumentExpression``` and ```functionArgument``` which would enable this feature. When parsing this logic, we also make changes to ASTBuilder such that it can detect if the argument passed is a named argument or a positional one.

### Why are the changes needed?
This is part of a larger project to implement named parameter support for user defined functions, built-in functions, and table valued functions.

### Does this PR introduce _any_ user-facing change?
Yes, the user would be able to call functions with argument lists that contain named arguments.

### How was this patch tested?
We add tests in the PlanParserSuite that will verify that the plan parsed is as intended.

### CODE REVIEW

**Comment by learningchess2003** [comment]
@MaxGekk Please let me know if the end-to-end tests were what you had in mind.

**Comment by dtenedor** [comment]
> @MaxGekk Please let me know if the end-to-end tests were what you had in mind.

These seem reasonable to me for this PR that only covers parser changes so far.

**Review by dtenedor — APPROVED** [review]
LGTM since this was ported from https://github.com/apache/spark/pull/41429 which I already approved.

**Review by MaxGekk — APPROVED** [review]
Waiting for Ci.

**Comment by MaxGekk** [comment]
+1, LGTM. Merging to master.
Thank you, @learningchess2003 and @dtenedor for review.

**Pull request closed without merging**
