### PR TITLE
[SPARK-5951][YARN] Remove unreachable driver memory properties in yarn client mode

### PR DESCRIPTION
**Pull request by zuxqoj**
Remove unreachable driver memory properties in yarn client mode

### CODE REVIEW

**Comment by sryza** [comment]
LGTM.  This seems in line with SPARK-1953's eradication of these properties for yarn-client mode.

**Comment by srowen** [comment]
Does @andrewor14 's comment at https://github.com/apache/spark/pull/3590#discussion_r25214428 affect this PR? should more stuff be removed for 1.4?

**Comment by zuxqoj** [comment]
@srowen 
Does @andrewor14 's comment at #3590 (comment) affect this PR?
no, he is talking about removing  deprecated properties (SPARK_MASTER_MEMORY and spark.master.memory) from spark in 1.4

**Comment by andrewor14** [comment]
ok to test

**Comment by andrewor14** [comment]
@zuxqoj Thanks for this PR. Actually I'd suggest that we just remove all the deprecated properties here. Calling a Spark executor a "Worker" is just as misleading as calling a Spark driver a "Master".

**Comment by andrewor14** [comment]
I just realized that this patch doesn't actually remove support for those deprecated configs; they were already removed in a patch #3607 that was merged beforehand. What this patch does is just to stop showing the deprecation messages for these configs.

LGTM I'm merging this into master and 1.3.

**Pull request closed without merging**
