### PR TITLE
[SPARK-39196][CORE][SQL][K8S] replace `getOrElse(null)` with `orNull`

### PR DESCRIPTION
**Pull request by dcoliversun**
### What changes were proposed in this pull request?

This PR aims to replace `getOrElse(null)` with `orNull`.

### Why are the changes needed?

Code simplification.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the GA.

### CODE REVIEW

**Review by srowen — COMMENTED** [review]
This is fine. It's kinda trivial but i like the simplification. How about replacing this across the codebase - are there many occurrences?

**Comment by dcoliversun** [comment]
@srowen Hi. I check it again. All `getOrElse(null)`s are replaced with `orNull`. Let's see the result of GA.

**Review by LuciferYang — APPROVED** [review]
LGTM + 1

**Review by srowen — APPROVED** [review]

**Comment by srowen** [comment]
Merged to master

**Comment by dcoliversun** [comment]
Thank for your help @srowen @LuciferYang

**Pull request closed without merging**
