### PR TITLE
[SPARK-7558] Guard against direct uses of FunSuite / FunSuiteLike

### PR DESCRIPTION
**Pull request by andrewor14**
This is a follow-up patch to #6441.

### CODE REVIEW

**Comment by andrewor14** [comment]
@rxin I couldn't figure out how to make the regex start with a lower case character / include spaces.

**Comment by andrewor14** [comment]
Do not merge this yet because it will fail tests in `flume-sink` after the latest commits in master.

**Comment by rxin** [comment]
LGTM.

**Comment by rxin** [comment]
Merged in master.

**Pull request closed without merging**
