### PR TITLE
[Minor][ML] Remove unused imports

### PR DESCRIPTION
**Pull request by zhengruifeng**
## What changes were proposed in this pull request?

Remove unused imports
## How was this patch tested?

local build and unit test

### CODE REVIEW

**Comment by srowen** [comment]
If you have an automated way to look for these, it'd be best to make a pass over all files and clean this up all at once. For example a quick inspection shows SparkSubmitOptionParserSuite has unused imports too. For Java files I think that even fails the style check (?)

**Comment by zhengruifeng** [comment]
@srowen No. I have no automated method to check unused import. I append such issues in a branch when I found them.

**Comment by srowen** [comment]
Yeah, the overhead of opening a lot of little JIRAs and PRs for a basically non-functional change isn't usually worth it. I'd rather push back on you to clean these up more globally, or during other changes, or not at all.

**Comment by zhengruifeng** [comment]
ok, I will add this change into other pr

**Pull request closed without merging**
