### PR TITLE
[SPARK-19851] Add new aggregates EVERY and ANY (SOME).

### PR DESCRIPTION
**Pull request by ptkool**
## What changes were proposed in this pull request?

This pull request implements the EVERY and ANY aggregates.

## How was this patch tested?

Testing was performed using unit tests, integration tests, and manual tests.

### CODE REVIEW

**Comment by hvanhovell** [comment]
@ptkool code wise this looks pretty good. I have one high level question. We could also use the exisiting `min` aggregate for `any` and `max` aggregate for `all`; what is the benefit of adding these operators?

**Comment by hvanhovell** [comment]
ok to test

**Comment by ptkool** [comment]
@hvanhovell I'm not following how `min` and `max` could be used.

**Comment by hvanhovell** [comment]
I am sorry I have flipped the pairs (I have updated the comment). We can use the ordering of booleans here, false is smaller than true. Let's say that we have column `x` which is a boolean. if `max(x)` returns `true` we know that the column contains at least one `true` value. If `min(x)` returns `true` we know that all column only contains `true` values.

**Comment by ptkool** [comment]
I think `every` and `any` are more intuitive, particularly if the operand is a boolean expression. For example, `every(t1.c1 > t2.c2)` vs `max(t1.c1 > t2.c2)`. Also, `every` and `any` return `false` for empty sets, while `min` and `max` return `null`.

**Comment by ptkool** [comment]
`every` and `any` are also part of the SQL standard, so most SQL users will be familiar with them.

**Comment by zjffdu** [comment]
@ptkool Please help the title to include the JIRA Id so that it can be linked to jira automatically.

**Pull request closed without merging**
