### PR TITLE
[SPARK-40851][INFRA ][SQL][TESTS][3.3] Make GA run successfully with the latest Java 8/11/17

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
The main change of this pr as follows:

- Replace `Antarctica/Vostok` to `Asia/Urumqi` in Spark code
- Replace `Europe/Amsterdam` to `Europe/Brussels` in Spark code
- Regenerate `gregorian-julian-rebase-micros.json` using generate 'gregorian-julian-rebase-micros.json' in `RebaseDateTimeSuite` with Java 8u352
- Regenerate `julian-gregorian-rebase-micros.json` using generate 'julian-gregorian-rebase-micros.json' in RebaseDateTimeSuite with Java 8u352

### Why are the changes needed?
Make GA run successfully with the latest Java 8/11/17:

- Java 8u352
- Java 11.0.17
- Java 17.0.5

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?

- Pass GitHub Actions
- Manual test: the following commands can test pass with Java 8u345, 8u352, 11.0.16, 11.0.17, 17.0.4 and 17.0.5
   - `build/sbt "catalyst/test"`
   - `build/sbt "sql/testOnly *SQLQueryTestSuite -- -t \"timestamp-ltz.sql\""`
   - `build/sbt "sql/testOnly *SQLQueryTestSuite -- -t \"timestamp-ntz.sql\""`

### CODE REVIEW

**Comment by LuciferYang** [comment]
waiting ci

**Review by HyukjinKwon — APPROVED** [review]

**Review by MaxGekk — APPROVED** [review]

**Comment by LuciferYang** [comment]
image

3.3 passed

**Comment by HyukjinKwon** [comment]
Merged to branch-3.3.

**Comment by LuciferYang** [comment]
thanks @HyukjinKwon  @MaxGekk

**Pull request closed without merging**
