### PR TITLE
[SPARK-24833][K8S][WIP] Add host name aliases feature

### PR DESCRIPTION
**Pull request by rvesse**
## What changes were proposed in this pull request?

This adds a new feature to the driver and executor builders for K8S that
allows providing host name aliases into the K8S pods.  This is useful
for environments where DNS is not usable or you need to add aliases to
make non-K8S services accessible.

For example in our environment we use host aliases to route internal system services e.g. Zookeeper without having to know the external host name of the system.

We are proposing this feature to replace a current hack we do with injecting host name entries into the Spark generated pods via entry point scripts in a custom images. 

- [x] Implementation
- [x] Unit tests
- [ ] Integration tests

## How was this patch tested?

Added unit tests for this functionality, integration tests to follow

CC @mccheah

### CODE REVIEW

**Comment by liyinan926** [comment]
I think we decided not to take any new configuration options with https://issues.apache.org/jira/browse/SPARK-24434 being worked on. @mccheah @foxish.

**Comment by rvesse** [comment]
@liyinan926 Ok, I will keep an eye on that issue

**Review by felixcheung — CHANGES_REQUESTED** [review]
correct - please contribute to SPARK-24434

**Comment by rvesse** [comment]
@felixcheung No problem, have already made a couple of comments on the design doc

**Pull request closed without merging**
