### PR TITLE
[SPARK-6477][Build]: Run MIMA tests before the Spark test suite

### PR DESCRIPTION
**Pull request by brennonyork**
This moves the MIMA checks to before the full Spark test suite such that, if new PR's fail the MIMA check, they will return much faster having not run the entire test suite. This is preferable to the current scenario where a user would have to wait until the entire test suite completes before realizing it failed on a MIMA check in which case, once the MIMA issues are fixed, the user would have to resubmit and rerun the full test suite again.

### CODE REVIEW

**Comment by srowen** [comment]
Agree, I like this one. Fail-fast checks should go first.

**Comment by andrewor14** [comment]
LGTM

**Comment by pwendell** [comment]
LGTM too

**Pull request closed without merging**
