### PR TITLE
[SPARK-35326][BUILD][FOLLOWUP] Update dependency manifest files

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This is a followup of https://github.com/apache/spark/pull/32453.

### Why are the changes needed?

Jenkins doesn't check dependency manifest files.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the GitHub Action or manually.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Could you review this, @sarutak and @viirya ?

**Comment by sarutak** [comment]
@dongjoon-hyun Thank you for following up. I run `dev/test-dependencies.sh --replace-manifest` on my laptop and got the same result so LGTM.

**Comment by dongjoon-hyun** [comment]
Gentle ping, @sarutak !

**Review by sarutak — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you!

**Comment by viirya** [comment]
lgtm

**Comment by dongjoon-hyun** [comment]
Thank you, @viirya !

**Pull request closed without merging**
