### PR TITLE
[SPARK-8074] Parquet should throw AnalysisException during setup for data type/name related failures.

### PR DESCRIPTION
**Pull request by rxin**

### CODE REVIEW

**Comment by liancheng** [comment]
We may also want to replace the `sys.error` in [this line] [1] with the following:

```scala
              .getOrElse {
                throw new AnalysisException(
                  s"Failed to discover schema of Parquet file(s) in the following location(s):\n" +
                    paths.mkString("\n\t"))
              }
```

Otherwise LGTM.

[1]: https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/parquet/newParquet.scala#L387

**Comment by rxin** [comment]
Jenkins, retest this please.

**Comment by liancheng** [comment]
I think we should also replace all `assert`s and `require`s along the way with `AnalysisException`.

**Comment by liancheng** [comment]
Probably not all, but those related to analysis errors.

**Comment by rxin** [comment]
Let's do that later. We should audit all exceptions and decide what to do.

**Pull request closed without merging**
