### PR TITLE
[SPARK-43100][CORE] Mismatch of field name in log event writer and parser for push shuffle metrics

### PR DESCRIPTION
**Pull request by zhouyejoe**
### What changes were proposed in this pull request?
For push based shuffle metrics, when writting out the event to log file, the field name is ["Push Based Shuffle"](https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/util/JsonProtocol.scala#L548).
But when parsing it out in SHS, the expected field name is ["Shuffle Push Read Metrics"](https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/util/JsonProtocol.scala#L1264). This mismatch makes all the push shuffle metrics 0 from SHS rest calls. This PR changes all the reference to "Push Based Shuffle".

### Why are the changes needed?
Without this change, all the push shuffle metrics will not be rendered correctly through SHS rest calls.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Launched Spark-shell application in Yarn client mode in our cluster, get the log file to local, and started a local Spark History Server to parse the log file. The metrics are shown correctly after this patch.

### CODE REVIEW

**Comment by zhouyejoe** [comment]
cc @mridulm as of the comment here https://github.com/apache/spark/pull/40749#discussion_r1165075248

**Comment by zhouyejoe** [comment]
Tests are failing unrelated. Triggering it again.

**Comment by mridulm** [comment]
+CC @thejdeep PTAL

**Comment by thejdeep** [comment]
LGTM, thanks for fixing it @zhouyejoe !

**Comment by mridulm** [comment]
Can you add a test to validate this through the REST api ?

**Comment by zhouyejoe** [comment]
There are existing tests for querying rest calls and verify the Json response in HistoryServerSuite:
    "stage list with peak metrics" -> "applications/app-20200706201101-0003/stages",
    "stage with peak metrics" -> "applications/app-20200706201101-0003/stages/2/0",
    "stage with summaries" -> "applications/app-20200706201101-0003/stages/2/0?withSummaries=true",

However, a big missing pieces in UT that can reveal to the existing issue is:
Generating the event with the JsonProtocol toJson methods, and parse it in HistoryServerSuite.
@mridulm

**Comment by mridulm** [comment]
The test I am looking for would have failed before we fixed `JsonProtocol`, and worked after this PR.

**Pull request closed without merging**
