### PR TITLE
[SPARK-42536][BUILD] Upgrade log4j2 to 2.20.0

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This version aims upgrade log4j2 from 2.19.0 to 2.20.0

### Why are the changes needed?
This version brings some bug fix like [Fix java.sql.Time object formatting in MapMessage ](https://issues.apache.org/jira/browse/LOG4J2-2297) and [Fix level propagation in Log4jBridgeHandler](https://issues.apache.org/jira/browse/LOG4J2-3634), and some new support like [Add support for timezones in RollingFileAppender](https://issues.apache.org/jira/browse/LOG4J2-1631), the release notes as follows:

- https://logging.apache.org/log4j/2.x/release-notes/2.20.0.html

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass GitHub Actions

### CODE REVIEW

**Review by srowen — APPROVED** [review]

**Review by HyukjinKwon — APPROVED** [review]

**Comment by srowen** [comment]
Merged to master

**Comment by LuciferYang** [comment]
Thanks @srowen @HyukjinKwon

**Comment by viirya** [comment]
Looks good to me. +1

**Comment by LuciferYang** [comment]
Thanks @dongjoon-hyun @viirya ~

**Pull request closed without merging**
