### PR TITLE
[SPARK-45276][INFRA][FOLLOWUP] Fix Java version comment from 11 to 17

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This is a follow-up of
- #43076

### Why are the changes needed?

To match with the code.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Manual review.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
We missed this last time. Could you review this, @panbingkun and @LuciferYang ?

**Review by bjornjorgensen — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @bjornjorgensen .

**Review by yaooqinn — APPROVED** [review]
LGTM

**Comment by dongjoon-hyun** [comment]
Thank you, @yaooqinn ! Merged to master.

**Review by LuciferYang — COMMENTED** [review]
late LGTM

**Comment by dongjoon-hyun** [comment]
Thank you, @LuciferYang !

**Comment by panbingkun** [comment]
late LGTM

**Pull request closed without merging**
