### PR TITLE
[SPARK-25551][SQL] Remove unused InSubquery expression

### PR DESCRIPTION
**Pull request by mgaido91**
## What changes were proposed in this pull request?

The PR removes the `InSubquery` expression which was introduced a long time ago and its only usage was removed in https://github.com/apache/spark/commit/4ce970d71488c7de6025ef925f75b8b92a5a6a79. Hence it is not used anymore.

## How was this patch tested?

existing UTs

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
@mgaido91 . Yep. This is trivial, but code change always requires SPARK issue and also please add '[SQL]` to the title.

**Comment by dongjoon-hyun** [comment]
Also, `unused` instead of `useless`?

**Comment by cloud-fan** [comment]
LGTM, +1 for creating a JIRA

**Comment by viirya** [comment]
LGTM

**Comment by mgaido91** [comment]
thanks @dongjoon-hyun for the comments. I created the JIRA  and updated the title according to your suggestions.

Thank you all for the review.

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Pull request closed without merging**
