### PR TITLE
[SPARK-15470] [SQL] Unify the Configuration Interface in SQLContext

### PR DESCRIPTION
**Pull request by gatorsmile**
#### What changes were proposed in this pull request?

We introduced `RuntimeConfig` in `SQLContext` in the PR https://github.com/apache/spark/pull/12669. Now, `SQLContext` has both `conf` and `runtimeConf`. `SQLContext` is being replaced by `SparkSession`. Like `SparkSession`, we should not have two configuration interfaces. That means, we should not expose `conf` to external users.

This PR contains three major parts:
1. removed `conf` from `SQLContext`. 
2. added the missing functions into `RuntimeConfig`, including two `set` functions and one `clear` function.
3. fixed the test cases in `SparkSessionBuilderSuite.scala`. Without this fix, we are unable to individually run the test cases. All the test cases require `initialSession`.  

@rxin @andrewor14 @yhuai @cloud-fan  Do you think this PR is valid? Thanks!
#### How was this patch tested?

Existing test cases cover it.

### CODE REVIEW

**Comment by cloud-fan** [comment]
What's the difference between runtime conf and normal conf?

**Comment by gatorsmile** [comment]
@cloud-fan Based on my understanding, runtime conf (`class RuntimeConfig`) is designed as the public/external interface for users to access the internal conf. If users want to make a change on Config at runtime, they must use `RuntimeConfig`. In the future, we can further enhance it to block external users to change the internal conf?  Also easier to manage Hadoop configuration in `RuntimeConfig`? 

`SQLConf` will be just an internal implementation of configuration. We do not expect external users to directly access it.

You know, this is just my understanding. : )

**Comment by rxin** [comment]
I don't get it. ConfigEntry is internal to Spark. Why are we exposing that?

**Comment by gatorsmile** [comment]
You are right. Let me add `protected[sql]` before `def set[T](entry: ConfigEntry[T], value: T): Unit` 
https://github.com/gatorsmile/spark/blob/d972e8d8832c5a04d8ff4cc1ee10293cdbfac977/sql/core/src/main/scala/org/apache/spark/sql/RuntimeConfig.scala#L67-L69

That will be like what `RuntimeConfig` already has for `get`, which is `protected[sql] def get[T](entry: ConfigEntry[T], default: T): T`
https://github.com/gatorsmile/spark/blob/d972e8d8832c5a04d8ff4cc1ee10293cdbfac977/sql/core/src/main/scala/org/apache/spark/sql/RuntimeConfig.scala#L115-L117

**Comment by rxin** [comment]
I'd like to avoid contaminating RuntimeConfig with private[sql] methods if possible. Those visibility modifiers have no effect in Java.

**Comment by rxin** [comment]
In this case I guess it is ok though.

**Comment by gatorsmile** [comment]
I see. Thanks!

**Comment by gatorsmile** [comment]
@rxin I am wondering if what this PR does is OK?

**Comment by rxin** [comment]
This looks ok, but can you remind me again what this pull request is actually solving? I feel it's just changing code for the sake of changing code here ...

**Comment by gatorsmile** [comment]
Previously, @yhuai mentions we need to issue exceptions when users change the static configuration at runtime. See https://github.com/apache/spark/pull/13128#issuecomment-220411852 

When trying to do it in a cleaner way, I plan to add these logics into `RuntimeConfig`. However, I found `SQLContext` has two entrances for configuration, one is `conf` and another is `runtimeConf`. Thus, I think we have to remove the duplicate before working on it. 

Do you think my concern is OK?

**Comment by rxin** [comment]
Is the idea to have a list of configs that are marked as mutable and explicitly throw exceptions when users modify them?

I still don't see how that relates to the changes here... Why not just have that list in SQLConf?

**Comment by gatorsmile** [comment]
Initially, I did try to do it in that way. The questions bothering me are how to know which changes are made at runtime? which changes are from external users?

After reading the code base, based on my understanding, we will not externalize `SQLConf` after introducing `RumtimeConfig`. The `set` APIs of `SQLConf` will be for internal usage only? Thus, we can do whatever we want, if necessary. For example, to verify the internal behaviors, our test suites are still allowed to change the configuration at runtime. For example, in multiple test cases, like  [ddlsuite](https://github.com/apache/spark/blob/5afd927a47aa7ede3039234f2f7262e2247aa2ae/sql/core/src/test/scala/org/apache/spark/sql/execution/command/DDLSuite.scala#L129), we change `spark.sql.warehouse.dir` at runtime. 

Then, I am wondering if we just need to block the changes on the static configuration properties through `RuntimeConfig`? That is the reason why this PR is to remove the `conf` from `SQLContext`.

Feel free to let me know which ways are preferred. Thanks!

**Comment by rxin** [comment]
Can we just add a flag to SQLConf to indicate whether SparkSession has been properly initialized?

**Comment by gatorsmile** [comment]
OK, I can do it by adding a flag. Do you want me to close this PR?

**Comment by rxin** [comment]
Please close this. I just feel it adds virtually no benefit but requires non-trivial changes.

**Comment by rxin** [comment]
One thing that would be a lot more useful is to get rid of SQLContext in our test cases, and use only SparkSession. Then most of the problem in your pr just goes away.

**Comment by gatorsmile** [comment]
Sure, let me close it. Thanks!

**Pull request closed without merging**
