### PR TITLE
[SPARK-8099] set executor cores into system in yarn-cluster mode

### PR DESCRIPTION
**Pull request by XuTingjun**

### CODE REVIEW

**Comment by srowen** [comment]
This doesn't look like the right way to do it -- just manually setting a system property here? CC @tgravescs @sryza

**Comment by sryza** [comment]
I think the right place to fix this is probably https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/deploy/SparkSubmit.scala#L449.

We probably want it to look like the line below that sets spark.executor.memory for all cluster managers.

**Comment by XuTingjun** [comment]
Thanks all, I have updated the code, please have a look again.

**Comment by srowen** [comment]
ok to test

**Comment by XuTingjun** [comment]
please retest

**Comment by srowen** [comment]
Jenkins, retest this please

**Comment by srowen** [comment]
@sryza if that's what you meant you can merge it

**Comment by andrewor14** [comment]
lgtm, great catch

**Comment by sryza** [comment]
LGTM, merging

**Pull request closed without merging**
