### PR TITLE
[SPARK-22254][core] Fix the arrayMax in BufferHolder

### PR DESCRIPTION
**Pull request by kiszk**
## What changes were proposed in this pull request?

This PR replaces the old the maximum array size (`Int.MaxValue`) with the new one (`ByteArrayMethods.MAX_ROUNDED_ARRAY_LENGTH`).
This PR also refactor the code to calculate the new array size to easily understand why we have to use `newSize - 2` for allocating a new array.

## How was this patch tested?

Used the existing test

### CODE REVIEW

**Comment by kiszk** [comment]
@srowen @gatorsmile could you please review this?

**Review by srowen — APPROVED** [review]

**Review by jiangxb1987 — APPROVED** [review]
LGTM

**Review by gatorsmile — APPROVED** [review]
LGTM

**Comment by gatorsmile** [comment]
Thanks! Merged to master.

**Pull request closed without merging**
