### PR TITLE
[SPARK-13203] Add scalastyle rule banning use of mutable.SynchronizedBuffer

### PR DESCRIPTION
**Pull request by tedyu**
@andrewor14 
Please take a look

### CODE REVIEW

**Comment by tedyu** [comment]
Jenkins, test this please

**Comment by andrewor14** [comment]
@srowen

**Comment by srowen** [comment]
Yes that's fine if it passes tests and it does

**Comment by holdenk** [comment]
LGTM :)

**Comment by tedyu** [comment]
@andrewor14 
Is there anything I need to do for this ?

**Comment by srowen** [comment]
@tedyu just have some patience. Sometimes we're just giving others a chance to look before merging. Merged to master

**Pull request closed without merging**
