### PR TITLE
[SPARK-15180][SQL] Support subexpression elimination in Fliter

### PR DESCRIPTION
**Pull request by viirya**
## What changes were proposed in this pull request?

This patch tries to add the support of subexpression elimination in wholestage codegen `Fliter`.

Because the predicate expressions are evaluated in `Filter` with an optimized ordering that reduces unnecessary evaluation as much as possible, we follow this ordering when doing subexpression elimination too.

Due to that, we can't just extract all common subexpressions and evaluate them first. Instead, we extract common subexpressions but don't evaluate them. We evaluate common subexpressions only when the predicate expressions containing them are evaluated.
## How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by viirya** [comment]
Codes:

    val ds = Seq(("a", 10), ("a", 20), ("b", 1), ("b", 2), ("c", 1)).toDS().filter("_2 + 1 > 5").filter("_2 + 1 > 20")
    ds.collect()

Generated codes:

    /* 030 */   protected void processNext() throws java.io.IOException {                                  
    /* 031 */     /*** PRODUCE: Filter (((_2#3 + 1) > 20) && ((_2#3 + 1) > 5)) */
    /* 032 */
    /* 033 */     /*** PRODUCE: INPUT */
    /* 034 */
    /* 035 */     while (inputadapter_input.hasNext()) {
    /* 036 */       InternalRow inputadapter_row = (InternalRow) inputadapter_input.next();
    /* 037 */       /*** CONSUME: Filter (((_2#3 + 1) > 20) && ((_2#3 + 1) > 5)) */
    /* 038 */
    /* 039 */       /* ((input[1, int] + 1) > 20) */
    /* 040 */       // Common expression
    /* 041 */       /* (input[1, int] + 1) */
    /* 042 */       /* input[1, int] */
    /* 043 */       /* input[1, int] */
    /* 044 */       int inputadapter_value1 = inputadapter_row.getInt(1);
    /* 045 */
    /* 046 */       int filter_value = -1;
    /* 047 */       filter_value = inputadapter_value1 + 1;
    /* 048 */
    /* 049 */       /* (input[1, int] + 1) */
    /* 050 */
    /* 051 */       boolean filter_value3 = false;
    /* 052 */       filter_value3 = filter_value > 20;
    /* 053 */       if (!filter_value3) continue;
    /* 054 */       /* ((input[1, int] + 1) > 5) */
    /* 055 */       /* (input[1, int] + 1) */
    /* 056 */
    /* 057 */       boolean filter_value5 = false;
    /* 058 */       filter_value5 = filter_value > 5;
    /* 059 */       if (!filter_value5) continue;
    /* 060 */
    /* 061 */       filter_numOutputRows.add(1);
    /* 062 */
    /* 063 */       /*** CONSUME: WholeStageCodegen */
    /* 064 */
    /* 065 */       /* input[0, string] */
    /* 066 */       boolean inputadapter_isNull = inputadapter_row.isNullAt(0);
    /* 067 */       UTF8String inputadapter_value = inputadapter_isNull ? null : (inputadapter_row.getUTF8String(0));
    /* 068 */       filter_holder.reset();
    /* 069 */
    /* 070 */       filter_rowWriter.zeroOutNullBytes();
    /* 071 */
    /* 072 */       if (inputadapter_isNull) {
    /* 073 */         filter_rowWriter.setNullAt(0);
    /* 074 */       } else {
    /* 075 */         filter_rowWriter.write(0, inputadapter_value);
    /* 076 */       }
    /* 077 */
    /* 078 */       filter_rowWriter.write(1, inputadapter_value1);
    /* 079 */       filter_result.setTotalSize(filter_holder.totalSize());
    /* 080 */       append(filter_result);
    /* 081 */       if (shouldStop()) return;
    /* 082 */     }
    /* 083 */   }
    /* 084 */ }

**Comment by viirya** [comment]
cc @davies This is ready for review. Please take a look of this. Thanks.

**Comment by davies** [comment]
@viirya It's too complicated, we may not do this. I think we will not support  subexpression elimination in most of the operators.

**Comment by viirya** [comment]
@davies yea, I think so. The evaluation ordering of predicates makes subexpression elimination more complicated. I will try to simplify it. If it can't be, I will close it then. Thanks.

**Pull request closed without merging**
