### PR TITLE
[SPARK-17750][SQL][BACKPORT-2.0] Fix CREATE VIEW with INTERVAL arithmetic

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
## What changes were proposed in this pull request?

Currently, Spark raises `RuntimeException` when creating a view with timestamp with INTERVAL arithmetic like the following. The root cause is the arithmetic expression, `TimeAdd`, was transformed into `timeadd` function as a VIEW definition. This PR fixes the SQL definition of `TimeAdd` and `TimeSub` expressions.

``` scala
scala> sql("CREATE TABLE dates (ts TIMESTAMP)")

scala> sql("CREATE VIEW view1 AS SELECT ts + INTERVAL 1 DAY FROM dates")
java.lang.RuntimeException: Failed to analyze the canonicalized SQL: ...
```
## How was this patch tested?

Pass Jenkins with a new testcase.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Hi, @gatorsmile .
This is a backport of https://github.com/apache/spark/commit/92b7e5728025b1bb6ed3aab5f1753c946a73568c .

**Comment by gatorsmile** [comment]
LGTM

**Comment by gatorsmile** [comment]
Merged to 2.0. 

@dongjoon-hyun Could you please close it? Thanks!

**Comment by dongjoon-hyun** [comment]
Thank you so much, @gatorsmile !

**Pull request closed without merging**
