### PR TITLE
[Streaming][Kafka] cleanup tests from SPARK-2808

### PR DESCRIPTION
**Pull request by koeninger**
see if requiring producer acks eliminates the need for waitUntilLeaderOffset calls in tests

### CODE REVIEW

**Comment by tdas** [comment]
This is ok to test

**Comment by tdas** [comment]
Ok to test

**Comment by koeninger** [comment]
Pretty sure this error

[error] oro#oro;2.0.8!oro.jar origin location must be absolute: 

isn't related to the commit

**Comment by koeninger** [comment]
@tdas just pinging on this to make sure it doesn't get lost in the shuffle, lmk if there's more explanation needed.

**Comment by tdas** [comment]
I havent forgotten about this. I will pull it in.

**Comment by koeninger** [comment]
Another ping on this, even if it misses 1.4

Seeing waitUntilLeaderOffset all over the place in test code I'm working on right now made me sad :(

**Comment by srowen** [comment]
Just to double check: Jenkins, retest this please

**Comment by srowen** [comment]
Jenkins, retest this please

**Comment by koeninger** [comment]
The only thing I can think of mima complaining about is that this patch is removing a method... even though it's a method in a private class that is only used for testing.  Don't know why it didn't complain the first time around.

**Comment by srowen** [comment]
Looks like it's passing now but needs a rebase

**Comment by koeninger** [comment]
I sort of doubt that wait timeout was related to the merge, the only conflict was the single line of MimaExcludes

**Comment by srowen** [comment]
Jenkins, retest this please

**Comment by srowen** [comment]
@tdas are you OK with this change?

**Pull request closed without merging**
