### PR TITLE
[SPARK-22807] [Scheduler] Remove config that says docker and replace with container

### PR DESCRIPTION
**Pull request by foxish**
## What changes were proposed in this pull request?
Changes discussed in https://github.com/apache/spark/pull/19946#discussion_r157063535
docker -> container, since with CRI, we are not limited to running only docker images.

## How was this patch tested?
Manual testing

### CODE REVIEW

**Comment by foxish** [comment]
cc/ @vanzin @ueshin @jiangxb1987 @erikerlandson @liyinan926

**Comment by liyinan926** [comment]
LGTM.

**Comment by erikerlandson** [comment]
I'm picking up a few stragglers from `git grep`

```
resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/k8s/submit/steps/BaseDriverConfigurationStep.scala
33=private[spark] class BaseDriverConfigurationStep(
49:  private val driverDockerImage = submissionSparkConf
51:    .getOrElse(throw new SparkException("Must specify the driver Docker image"))
113:      .withImage(driverDockerImage)
```

```
core/src/test/scala/org/apache/spark/deploy/SparkSubmitSuite.scala
95=class SparkSubmitSuite
399:      "--conf", "spark.kubernetes.driver.docker.image=bar",
415:    conf.get("spark.kubernetes.driver.docker.image") should be ("bar")
```

**Comment by foxish** [comment]
Done, did another pass over them. Thanks @erikerlandson

**Comment by erikerlandson** [comment]
LGTM

**Comment by vanzin** [comment]
add to whitelist

**Comment by vanzin** [comment]
Please cleanup the PR description.

**Comment by vanzin** [comment]
ok to test

**Comment by vanzin** [comment]
LGTM pending tests.

**Comment by ueshin** [comment]
LGTM pending tests.

**Comment by foxish** [comment]
@ueshin @vanzin SparkR failure seems unrelated to me. Any ideas?

**Comment by jiangxb1987** [comment]
retest this please

**Review by jiangxb1987 — APPROVED** [review]
LGTM

**Comment by jiangxb1987** [comment]
The R tests are pretty flaky recently, any ideas @HyukjinKwon ?

**Comment by HyukjinKwon** [comment]
Seems it's related with https://github.com/apache/spark/commit/e58f275678fb4f904124a4a2a1762f04c835eb0e somehow and then fine back now. I am not yet entirely sure how this change relates to CRAN check. Will take a look soon.

Some related discussions - `https://github.com/apache/spark/pull/19721`, `https://github.com/apache/spark/pull/19944`, `https://github.com/apache/spark/pull/19957` and `https://github.com/apache/spark/pull/19961` in an order.

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
FYI, AppVeyor failure is fixed separately in #20003.

**Comment by foxish** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
@foxish rebasing and pushing it will make the AppVeyor test passed for sure.

**Comment by foxish** [comment]
@HyukjinKwon done. Thanks!

**Comment by jiangxb1987** [comment]
LGTM

**Comment by foxish** [comment]
@ueshin, can this and https://github.com/apache/spark/pull/20007 be merged now?

**Review by felixcheung — APPROVED** [review]

**Comment by vanzin** [comment]
Merging to master.

**Pull request closed without merging**
