### PR TITLE
[SPARK-44468][BUILD] Add daily test GA task for branch3.5

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to add daily test GA task for branch3.5.

### Why are the changes needed?
After the branch 3.5 is cut out from the master, we need a daily GA task to ensure the smooth release of version 3.5.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Manually test.

### CODE REVIEW

**Review by LuciferYang — APPROVED** [review]

**Comment by LuciferYang** [comment]
cc @zhengruifeng @HyukjinKwon FYI

**Comment by zhengruifeng** [comment]
should we also make some changes in `build_and_test` ?

**Review by HyukjinKwon — APPROVED** [review]
LGTM cc @xuanyuanking

**Comment by HyukjinKwon** [comment]
yeah should also change:
- https://github.com/apache/spark/blob/master/.github/workflows/build_and_test.yml#L34 (fix branch-3.5)
- https://github.com/apache/spark/blob/master/.github/workflows/build_and_test.yml#L521 (fix master branch)

cc @xuanyuanking who actually were going to fix soon :-).

**Comment by HyukjinKwon** [comment]
That will be fixed in https://github.com/apache/spark/pull/42055

**Comment by HyukjinKwon** [comment]
Merged to master.

**Review by dongjoon-hyun — COMMENTED** [review]
+1, LGTM. Thank you!

**Pull request closed without merging**
