### PR TITLE
[SPARK-44873][3.4] Support alter view with nested columns in Hive client

### PR DESCRIPTION
**Pull request by kylerong-db**
### What changes were proposed in this pull request?
Backport https://github.com/apache/spark/pull/42532 

### Why are the changes needed?
Support CREATE and ALTER VIEW with Hive-incompatible schema

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Unit tests

### CODE REVIEW

**Review by gengliangwang — APPROVED** [review]

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
Sorry, but this looks like an improvement instead of bugs. IIUC, Apache Spark has never support this before, doesn't it?

**Comment by gengliangwang** [comment]
> Sorry, but this looks like an improvement instead of bugs. IIUC, Apache Spark has never support this before, doesn't it?

@dongjoon-hyun FYI I don't have a strong opinion on this one.  If you are against it, I will not merge it.

**Comment by dongjoon-hyun** [comment]
Thank you, @gengliangwang . Apache Spark 3.5.0 looks enough for me. Since this is merged to Spark 3.5.0, the users can use this with 3.5.0 if they really want.

**Comment by HyukjinKwon** [comment]
Yeah, let's probably don't backport to 3.4 although it's sort of safe.

**Comment by dongjoon-hyun** [comment]
Thank you, @HyukjinKwon , too.

**Comment by dongjoon-hyun** [comment]
Let me close this backport PR. Thank you all.

**Pull request closed without merging**
