### PR TITLE
[SPARK-23835][SQL] Add not-null check to Tuples' arguments deserialization

### PR DESCRIPTION
**Pull request by mgaido91**
## What changes were proposed in this pull request?

There was no check on nullability for arguments of `Tuple`s. This could lead to have weird behavior when a null value had to be deserialized into a non-nullable Scala object: in those cases, the `null` got silently transformed in a valid value (like `-1` for `Int`), corresponding to the default value we are using in the SQL codebase. This situation was very likely to happen when deserializing to a Tuple of primitive Scala types (like Double, Int, ...).

The PR adds the `AssertNotNull` to arguments of tuples which have been asked to be converted to non-nullable types.

## How was this patch tested?

added UT

### CODE REVIEW

**Comment by mgaido91** [comment]
retest this please

**Comment by mgaido91** [comment]
retest this please

**Comment by mgaido91** [comment]
UT errors were caused by another commit which has been reverted.

**Comment by mgaido91** [comment]
cc @cloud-fan @jkbradley @marmbrus @viirya

**Comment by mgaido91** [comment]
kindly ping @cloud-fan @marmbrus @viirya

**Comment by cloud-fan** [comment]
LGTM, can you add an end-to-end test case in `DatasetSuite`?

**Comment by cloud-fan** [comment]
thanks, merging to master/2.3!

**Comment by viirya** [comment]
ah, a late LGTM.

**Pull request closed without merging**
