### PR TITLE
[SPARK-36759][BUILD] Upgrade Scala to 2.12.15

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to upgrade Scala to 2.12.15 to support Java 17/18 better.

### Why are the changes needed?

Scala 2.12.15 improves compatibility with JDK 17 and 18:

https://github.com/scala/scala/releases/tag/v2.12.15

- Avoids IllegalArgumentException in JDK 17+ for lambda deserialization
- Upgrades to ASM 9.2, for JDK 18 support in optimizer

### Does this PR introduce _any_ user-facing change?

Yes, this is a Scala version change.

### How was this patch tested?

Pass the CIs

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
cc @gengliangwang

**Comment by dongjoon-hyun** [comment]
cc @viirya and @sunchao , too.

**Comment by srowen** [comment]
I think that's reasonable for 3.2, IMHO

**Comment by dongjoon-hyun** [comment]
Thank you, @srowen .

**Review by viirya — COMMENTED** [review]
I saw CI was passed. So `silencer-lib` is available?

**Comment by viirya** [comment]
Seems not WIP now, we may need update the PR description.

**Review by viirya — APPROVED** [review]
Looks good. Thanks for upgrading it.

**Review by sunchao — APPROVED** [review]
Looks good to me too

**Comment by dongjoon-hyun** [comment]
Thank you, @viirya and @sunchao , too.
Yes, I made a PR to silencer repo and made the release.
I updated the PR description.

Merged to master/3.2.

**Comment by gengliangwang** [comment]
Late +1

**Pull request closed without merging**
