### PR TITLE
[SPARK-15288] [Mesos] Mesos dispatcher should handle gracefully when any thread gets UncaughtException

### PR DESCRIPTION
**Pull request by devaraj-kavali**
## What changes were proposed in this pull request?

Adding the default UncaughtExceptionHandler to the MesosClusterDispatcher.
## How was this patch tested?

I verified it manually, when any of the dispatcher thread gets uncaught exceptions then the default UncaughtExceptionHandler will handle those exceptions.

### CODE REVIEW

**Comment by tnachen** [comment]
ok to test

**Comment by skonto** [comment]
@mgummelt @srowen  should we get a merge?

**Comment by tnachen** [comment]
LGTM, @srowen can you please take a look?

**Comment by srowen** [comment]
We only otherwise do this in `Executor.scala`. I'm trying to understand if this is the right thing to do? I don't doubt it, just don't know.

**Comment by devaraj-kavali** [comment]
MesosClusterDispatcher also has multiple threads like Executor, when any one thread terminates in the MesosClusterDispatcher process due to some error/exception it keeps running without performing the terminated thread functionality. I think we need to handle those uncaught exceptions from the MesosClusterDispatcher process threads using the UncaughtExceptionHandler and take the action instead of running the MesosClusterDispatcher without performing the functionality and without notifying the user.

**Comment by devaraj-kavali** [comment]
@srowen Can you check this?

**Comment by srowen** [comment]
I can't really evaluate the change; is anyone else familiar with Mesos around to comment? that'd be best.

**Comment by skonto** [comment]
@devaraj-kavali Which threads/Executor you are referring to in MesosClusterDispatcher? 
Could you provide some pointers?

**Comment by skonto** [comment]
Ideally all processes we have should handle thread termination correctly, same applies to MesosClusterDispatcher. Btw I think the call in Executor.scala should be done in static code, for example in MesosExecutorBackend this should happen in its main main which launches the executor. Right now the call is executed when a new Executor class is instantiated which might be a bit late because the createExecutorEnv which always comes first, creates its own threads (eg. MapoutTracker threads).

**Comment by mgummelt** [comment]
LGTM.  @srowen please merge.

Out of curiosity, @devaraj-kavali what exception were you seeing?

**Review by srowen — APPROVED** [review]

**Comment by devaraj-kavali** [comment]
Thanks @mgummelt for the confirmation, It throws SparkException with the bug SPARK-15359/https://github.com/apache/spark/pull/13143.

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
