### PR TITLE
[SPARK-47986][CONNECT][PYTHON] Unable to create a new session when the default session is closed by the server

### PR DESCRIPTION
**Pull request by nija-at**
### What changes were proposed in this pull request?

When the server closes a session, usually after a cluster restart,
the client is unaware of this until it receives an error.

At this point, the client in unable to create a new session to the
same connect endpoint, since the stale session is still recorded
as the active and default session.

With this change, when the server communicates that the session
has changed via a GRPC error, the session and the respective client
are marked as stale. A new default connection can be created
via the session builder.

### Why are the changes needed?

See section above.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Attached unit tests

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]
seems fine from a cursory look ..... but would be great if @juliuszsompolski has a chance to take a quick look ...

**Comment by juliuszsompolski** [comment]
The SESSION_CHANGED error comes from https://github.com/apache/spark/pull/45499, cc @nemanja-boric-databricks and @hvanhovell . This seems like a followup-fix to that change and it looks good to me, but it would be best if Nemanja took a look.
One question from me: do we need that fix in scala client as well?

**Review by nemanja-boric-databricks — APPROVED** [review]
LGTM, yes we most likely need the same for Scala.

**Review by allisonwang-db — APPROVED** [review]

**Comment by zhengruifeng** [comment]
thanks, merged to master

**Comment by juliuszsompolski** [comment]
> yes we most likely need the same for Scala.

@nemanja-boric-databricks @nija-at would one of you have time to followup and check and fix for scala if needed?

**Comment by nemanja-boric-databricks** [comment]
Yeah, I'll followup with the fix PR for scala client

**Comment by changgyoopark-db** [comment]
@juliuszsompolski I just ported the fix + the follow-up to Scala - https://github.com/apache/spark/pull/47008, could you review this?

**Pull request closed without merging**
