### PR TITLE
[SPARK-6122][Core] Upgrade tachyon-client version to 0.6.3

### PR DESCRIPTION
**Pull request by calvinjia**
This is a reopening of #4867.
A short summary of the issues resolved from the previous PR:
1. HTTPClient version mismatch: Selenium (used for UI tests) requires version 4.3.x, and Tachyon included 4.2.5 through a transitive dependency of its shaded thrift jar. To address this, Tachyon 0.6.3 will promote the transitive dependencies of the shaded jar so they can be excluded in spark.
2. Jackson-Mapper-ASL version mismatch: In lower versions of hadoop-client (ie. 1.0.4), version 1.0.1 is included. The parquet library used in spark sql requires version 1.8+. Its unclear to me why upgrading tachyon-client would cause this dependency to break. The solution was to exclude jackson-mapper-asl from hadoop-client. 

It seems that the dependency management in spark-parent will not work on transitive dependencies, one way to make sure jackson-mapper-asl is included with the correct version is to add it as a top level dependency. The best solution would be to exclude the dependency in the modules which require a higher version, but that did not fix the unit tests. Any suggestions on the best way to solve this would be appreciated!

### CODE REVIEW

**Comment by haoyuan** [comment]
Jenkins, test this please.

**Comment by haoyuan** [comment]
Jenkins, test this please

**Comment by JoshRosen** [comment]
Jenkins, retest this please.

**Comment by calvinjia** [comment]
@JoshRosen @haoyuan 
Thanks for retesting, I've updated the pom to exclude the promoted dependencies of jetty and curator.

**Comment by haoyuan** [comment]
Jenkins, retest this please.

**Comment by JoshRosen** [comment]
Jenkins, retest this please.

**Comment by calvinjia** [comment]
@JoshRosen @aarondav @pwendell 
What do you think about the current PR? Is there any better strategy for handling the Jackson-mapper-asl issue?

Thanks!

**Comment by aarondav** [comment]
The change LGTM but I'll leave it to @pwendell to OK the pom changes. I'm not sure if there's a better way to express basically "don't include any of this guy's transitive dependencies".

**Comment by srowen** [comment]
Yea, this is really messy. Why are so many exclusions needed? these are artifacts that are already in the assembly, so, there's no particular problem.

However it does look like the Tachyon client has a lot of big dependencies. Is the client really pulling in `hadoop-core` and `jetty-*`? can the client's dependencies be trimmed somewhat? Basically this declaration says that fewof its dependencies are actually needed.

At the least we need to keep out hadoop-core, the servlet APIs, EL, probably hsqldb if possible, Glassfish. Anything that's added needs its license checked.

**Comment by calvinjia** [comment]
@srowen Thanks for the feedback!

The number of dependencies increased because transitive dependencies were promoted to avoid issues with being unable to exclude transitive dependencies from shaded artifacts (httpclient from thrift).

Are you concerned with the size of the exclusion block or just wondering if all the exclusions are necessary?

**Comment by srowen** [comment]
I think I am wondering two things -- why is it necessary to include some of these things like commons-beanutils, when they are already part of the dependency graph of even core? and second, I wonder why the tachyon _client_ has to bring in things as large as _hadoop-core_ for example?

(As an aside, the dependency graph should be managed in the parent, so that the exclusions would not have to be repeated if this were used in other modules.)

What do you mean about promoting deps to exclude them? That's the point I'm probably missing.

**Comment by calvinjia** [comment]
@srowen 
What I mean by promoting dependencies is like:
Project A depends on Project B
Project B depends on Project C

If Project S depends on Project A, it will pull in A, B, and C (and B & C can be excluded).

If Project A shades project B, Project S cannot see Project B & C to exclude.

If Project A shades project B and promotes transitive dependencies, Project S can see project C to exclude because Project A will just depend on Project C directly (which is why there are so many dependencies).

**Comment by srowen** [comment]
Yes, let's call the shaded B artifact B'. Are you saying that the published artifact of A shades B and C? yes, then it contains B' and C' and they are inseparable. It isn't usual to publish a shaded artifact like that unless it is an assembly / uber jar, which is not what projects depend on when consuming via Maven. 

A would still show a dependency on B and C in the POM, at least, if it were shaded at assembly time using something like the shade plugin.

You are saying that A shades B and C but then declares C as a direct, separate dependency? yes, then it shows a direct dependency on C, though I claim it already had a transitive dependency on C in Maven. We may still be talking about different things when it comes to what is published.

But, what is A here, `tachyon-client`? I'm not sure it's relevant to what I am getting at. If C includes `commons-beanutils`, why exclude it? and, why does C include `hadoop-core` for example? Again, if I understand what's what here.

**Comment by calvinjia** [comment]
Sorry for the bad example, here is (hopefully) a better explanation:

Previously:
`tachyon-client` depends on `tachyon`
`tachyon` depends on `hadoop-client`, `curator`, etc.
`tachyon` shades `thrift`
`thrift` depends on `httpclient`

Unfortunately in this scenario, importing `tachyon-client` would only give visibility to `tachyon`'s transitive dependencies `hadoop-client`, `curator`, etc. but not `httpclient` which caused a conflict.

Now:
`tachyon-client` depends on `tachyon`
`tachyon` depends on `hadoop-client`, `curator`, etc.
`tachyon` shades `thrift`
`tachyon` promotes dependencies, causing top level dependencies of `httpclient`, `hadoop-core`, etc. which are now visible and can be excluded.

**Comment by srowen** [comment]
In this case, `tachyon` includes `thrift` (shaded) and `httpclient` (unshaded). Adding a direct dependency on `httpclient` shouldn't do anything. Shading hasn't changed that it (unshaded) is a transitive dependency. Well, maybe there's more to it.

But my point remains something else. If `httpclient` is needed, you can't exclude it, right? If Spark also depends on `httpclient`, that's fine: Maven resolves the conflict. If Maven's choice is wrong, then _Spark_ manages the dependency in `dependencyManagement`, but, this isn't done with exclusions. For example, this is the situation with `commons-beanutils`.

I suppose my secondary point is still that `tachyon-client` seems to pull in lots of stuff that don't seem like things a client-side library should need, like a web server or `hadoop-core`. I know that this is at best a Tachyon question, but, maybe still valid to consider here since Spark is a primary consumer of Tachyon.

(Third question, which is off topic here I suppose is, why does Tachyon belong as a dependency of the core anyway? I suppose you could make the same argument for Hadoop of course, but I didn't see Tachyon as so nearly essential. I would have expected an optional module or something like YARN, since it's not something that will be enabled by most users.)

**Comment by calvinjia** [comment]
In the original PR, the dependency management was left to maven but it caused dependency issues in tests which is why this new method is being proposed.

For the last question, as you mentioned its a bit off topic for this PR, so let's discuss that in the appropriate forum.

**Comment by srowen** [comment]
That ship may have sailed for better or worse. Yes we have to be careful about bringing things into core, so I'm glad to see the exclusions, but I think there are simpler and less brittle ways.

In general if two components need to agree on a particular version of a dependency, that is resolved in `dependencyManagement` in the parent. `exclusions` is not a great way to do it; as soon as, maybe, the other components stops using X that Tachyon needs, now there are 0 copies of it. So that's still the question -- if there are conflicts, what are they, and why not manage the dependency directly?

The `hadoop-core` stuff is maybe more cosmetic. If `tachyon-client` works fine without it, then perhaps it and other dependencies from upstream are merely redundant? at the least, I'd be sort of surprised if lots of these non-client, server-side libraries are _directly_ used by the client. This seems like maybe it's also trying to exclude a bunch of transient dependencies of something already excluded.

You could say that the exclusions really don't hurt much, or if they do we know it quickly, but I think it's worth double-checking the above first, as this exclusion declaration looks surprising. Goodness knows it is necessary in some cases with Hadoop stuff though -- usually to exclude the *same* code under *different artifact names* because upstream projects made uber-jars or shaded. (Looking at you, Jetty)

**Comment by calvinjia** [comment]
For the first point, the conflict was in `httpclient` which was not resolved correctly by the parent, leading to this iteration of the PR. 

For the second point, I think all the exclusions added actually do exclude a dependency, at least from a quick look at sbt's dependency-tree.

**Comment by srowen** [comment]
I think I'm not getting across the first point: why can't you solve this with an entry in `dependencyManagement` that declares the desired version of thrift to include, for example? That particular example might be tricky, but, then simpler examples like `commons-beanutils`. I am 95% sure this is not necessary, like much of this.

My second point is still different, and it's a question about `tachyon-client` itself. Why does it depend on these things if they're not used, and can that be fixed upstream?

**Comment by calvinjia** [comment]
@JoshRosen @srowen @aarondav 
I've updated the PR to resolve the http client issue by upgrading the version and specifying the version in sql/hive (which was pulling in the 4.2.x version).

**Comment by srowen** [comment]
That sure looks cleaner. Although updating the HTTP client version has some implications across the code base -- we need to see if we harmonize correctly on this version and look at the list of changes to decide whether there are possible conflicts -- I suspect that can be OK and that it helps more than hurts.

Still on Jackson: is it that you want to standardize on a certain version? what version? managing the version is a more robust way to do this.

(Reminds me: separately, I should figure out whether we can pull up all of these messy exclusions into the parent. They shouldn't go in the child POMs.)

Does the new release of Tachyon remove some dependencies? that is, it's great that almost all the exclusions are gone, but that doesn't mean that this now brings in more dependencies does it? Jenkins will tell us ---

**Comment by srowen** [comment]
ok to test

**Comment by srowen** [comment]
Jenkins, retest this please

**Comment by calvinjia** [comment]
@srowen
Thanks for taking another look!
For the Jackson library, spark already has a dependency managed version, but for transitive dependencies I need to exclude it or introduce it as a top direct dependency, is the latter preferred?

**Comment by srowen** [comment]
I dont think it should be a direct dependency just for this purpose, no. This is what the dependencyManagement section is for. What are you trying to achieve with this? Just ensure a certain version wins out right?

**Comment by calvinjia** [comment]
Does dependency management work for transitive dependencies? I'm trying to ensure the higher version wins out.

**Comment by srowen** [comment]
Should do; give it a try. This should be how you control the version of an artifact that is used without creating an actual dependency on it.

**Comment by calvinjia** [comment]
@srowen 
I tried setting httpclient in spark-parent's dependencyManagement and removing my direct dependency, but I encounter the same problem as before (httpclient version mismatch, 4.2.5 jar appears in lib_managed). I notice Jackson-mapper-asl is already a managed dependency, but it still caused versioning issues, so it doesn't seem like dependencyManagement is working as intended?

**Comment by srowen** [comment]
I thought this was about Jackson, since that's what's excluded. It's already managed to version 1.9.13, yes. Is that not the version you need? This is a version that I think a lot of Hadoop components agree on, so would be good if that's also fine for Tachyon.

I don't see anything bringing in httpclient 4.2.5 at the moment. In fact I was confused to see `commons.httpclient.version` doesn't do anything. This actually appears to be added only for Kinesis, and only affects its dependencies. 

@ScrapCodes (looks like you added that bit) this seems pretty confusing since it doesn't affect the version used in the rest of the project, which looks to be some mismatched combination of core 4.3.3 and client 4.3.6.

Since it seems Tachyon wants 4.3.2, can we all agree on `org.apache.httpcomponents:httpclient` and  `org.apache.httpcomponents:httpcore` version 4.3.6?

So: we would explicitly manage both of these versions in the parent `pom.xml` and remove the two manual version management stanzas for Kinesis (the two refs to `${commons.httpclient.version}` in children).

**Comment by ScrapCodes** [comment]
@srowen I am not sure I understand, where did you see hardcoded versions for httpclient/httpcore ?

**Comment by srowen** [comment]
Oh, I'm referring to `commons.httpclient.version` declared in the parent POM. It's actually only used, however, to manage the version of httpclient used by Kinesis. I saw you were the one that added the line, but this could be a false alarm; maybe you were just moving code.

I think the right-er thing to do given the facts here is just make the whole project actually use the version of httpclient / httpcore that this string implies, and make it 4.3.6.

**Comment by ScrapCodes** [comment]
hm.. your approach sounds good to me, we should really make sure we have the same version of a library across dependent projects.

**Comment by calvinjia** [comment]
@srowen 
Despite Jackson being managed by dependencyManagement, lower versions make it into managed_libs which cause issues when `mllib` tests run, since they expect the higher version. This is why I exclude the library from hadoop-client which brings in the lower versions.

For `httpclient`, `4.2.5` is brought in by `sql/hive` when they reference `libthrift`. This causes selenium tests to break since it expects `4.3.2`.

Finding the perfect way to reconcile Spark's dependencies as you mentioned before, deserves its own ticket and will require substantial effort. For example, it is not even easy to tell that different versions of `httpclient` are referenced in Spark.

@ScrapCodes 
Let's address cleaning up the Kinesis profile in a separate PR.

**Comment by srowen** [comment]
I don't see anything in `lib_managed` except the datanucleus jars. Jackson should not be something that has to be managed specially like this and I see no reference to Jackson jars in this dir in the code? are you sure this isn't something left around from some other process? 

Right now, `mvn -Phadoop-2.4 dependency:tree` shows a dependency on Jackson 1.9.13 only, across the project. What are you seeing that is different and that causes a problem? The current Hadoop deps do not bring in a different version, and Tachyon doesn't add new Hadoop deps (right?)

If Tachyon requires HttpClient 4.3.2+, then that will need to be resolved here. Your change does not actually cause Spark to use 4.3.2, as I say above. That's easy to address, and needs to happen in this PR. We don't need a separate PR for the Kinesis change since that's logically part of the change you will have to make here to make this do what you want.

**Comment by calvinjia** [comment]
@srowen
These issues only occur when running the sbt tests using lower versions of Hadoop (ie. 1.0.4).

Tachyon does not require httpclient 4.3.2, it's the selenium tests that do. To be clear, the dependency changes I am making are to address the jar conflicts that occur when running the sbt tests.

**Comment by srowen** [comment]
Why would the Tachyon version change itself alter the jackson or httpclient dependencies? was it already not working?

**Comment by calvinjia** [comment]
The conflicting dependencies were already included prior to my changes. I think since the correct jars were also available, there is a chance to use those and mask the problem.

**Comment by calvinjia** [comment]
@srowen 
Do you have any other comments? Thanks.

**Comment by srowen** [comment]
I'm running SBT tests now just to see if I can reproduce a failure. I guess I'd be surprised if the default SBT build doesn't work, since it would have been this way for a while. I do see that the SBT build adds a bunch of stuff to `lib_managed`, yes, which Maven doesn't.

So, if the dependency changes are not related to Tachyon, I think I'd skip them. There's no problem with Maven right now. The Jackson exclusion should not make a difference; in Maven, the version is consistently 1.8.8 for pre-Hadoop-2 builds, and 1.9.13 for Hadoop 2.2+ builds. The HttpClient situation is a little bit wrong but if it's not actually affecting Tachyon, that can be fixed separately.

**Comment by calvinjia** [comment]
@srowen 
You shouldn't be able to reproduce a failure with master branch, but upgrading Tachyon triggers the issue (picking up the wrong jar out of the ones that get pulled into lib_managed). This is why I made modifications to prevent the wrong jars from being pulled in.

**Comment by srowen** [comment]
Yeah, that still confuses me. If Tachyon doesn't touch `hadoop-client` or `hadoop-common` I'm not sure how it could change the dependencies. I'm wary of doing things like excluding deps to manage versions, especially when Hadoop does in fact need Jackson.

I can appreciate that -- whatever is going on -- we still want the SBT build to work even if it's not the main build, and still want Hadoop 1.x builds to work even if it's not the default. Let me try applying this change and seeing the diff in SBT myself, to try to verify what is essential to change.

**Comment by calvinjia** [comment]
@srowen 
Are you completely opposed to using an exclusion for the jackson library? Thanks for taking a look at the sbt build.

**Comment by srowen** [comment]
I'm still working through this -- I do see the same problem you see with the httpclient library, and it's because the SBT resolution rules are different. It's weird, but yeah that probably has to be patched up as you have done. I have a proposed change that touches up the handling in Kinesis, etc.

I didn't see a Jackson-related problem, not yet, but that may be masked by earlier failures. Basically, I'd be surprised if this exclusion is the only possible solution, so I want to try it out in a different environment.

**Comment by calvinjia** [comment]
@srowen 
You can try running org.apache.spark.mllib.regression.RidgeRegressionSuite with hadoop version 1.0.4 to reproduce the Jackson library conflict.
What kind of solutions are you more open to?

**Comment by srowen** [comment]
I don't see a Jackson-related failure, even when directly running `org.apache.spark.mllib.regression.RidgeRegressionSuite`, with the changes in this patch.

However I do see the HttpClient problem:

```
[info] Exception encountered when attempting to run a suite with class name: org.apache.spark.streaming.UISeleniumSuite *** ABORTED *** (106 milliseconds)
[info]   java.lang.NoSuchMethodError: org.apache.http.impl.cookie.BrowserCompatSpecFactory.create(Lorg/apache/http/protocol/HttpContext;)Lorg/apache/http/cookie/CookieSpec;
```

The change here works, although I think it can be tightened up a little bit. My last experiment will be to see if we can get away with `runtime` scope instead; `test` scope didn't work. I'll post what I have in a branch for you to take a look at after that.

**Comment by srowen** [comment]
This is the best I've got, which still works with SBT:
https://github.com/srowen/spark/commit/c1e40f80d11b20546acac6a96f28613cdc1d9fc7

It's mostly the same, but I don't find a jackson exclusion is needed, and I think the httpclient situation could be further tightened.

@aniketbhatnagar @ScrapCodes does the change to the `kinesis-asl` profile make sense? basically, now we need to manage httpclient versions correctly for the whole project, so I figure there's no need to redundantly manage it in the profiles.

**Comment by srowen** [comment]
It seems like the Jackson dep has to be excluded to get SBT + Hadoop 1.0.4 to work. I think that has to stay then, yeah. I think the httpclient stuff can be cleaned up a small bit but that too is essential.

I'm getting worried at how much the divergence between SBT and Maven is causing us to hack the build, making it harder to get the build right for both. For example, these changes aren't necessary at all for Maven. It's exacerbated by trying to support Hadoop 1.x.

Still maybe we kick this can down the road a bit longer, to get in this change.

**Comment by calvinjia** [comment]
@srowen 
I appreciate the feedback, and I've cleaned up the httpclient versions as you suggested. 
Do you have any other comments? Thanks.

**Comment by aniketbhatnagar** [comment]
+1 from my side. having a consistent httpclient version would be so much better!

**Comment by srowen** [comment]
LGTM. Thank you for your perseverance. This gets the change in with minimal additional change to the build, keeps everything compiling and actually improves the management of one dependency along the way.

I think the large list of removed dependencies above is a false positive. It can't remove these.

Let me merge and let's double check that the other Jenkins builds are still happy.

**Comment by calvinjia** [comment]
@srowen @aniketbhatnagar 
Thanks for reviewing this PR.

**Comment by vnkesarwani** [comment]
Hi,

I have tried applying the patch on spark-1.3.1. I am getting following error 

git apply --check /tmp/5354.patch 
error: launcher/pom.xml: No such file or directory
error: patch failed: pom.xml:146
error: pom.xml: patch does not apply

launcher folder is not available when we download spark-1.3.1 source code.

Any help.

**Comment by JoshRosen** [comment]
@vnkesarwani, try `cherry-pick`ing the commit then resolving the conflicts.

**Pull request closed without merging**
