### PR TITLE
[SPARK-28221][BUILD] Upgrade janino to 3.0.13

### PR DESCRIPTION
**Pull request by wangyum**
## What changes were proposed in this pull request?

Mainly change logs:
### Version 3.0.13:
- Support for JDK 9/10 in Full Compiler
- The syntax elements that can have modifiers now all have sets of "is...()" methods that check for each modifier. Some also have methods "getAccess()" and/or "getAnnotations()".
- Implement "type annotations" (JLS8 9.7.4)
- Implemented parsing (but not compilation) of "modular compilation units" (JLS11 7.3).
- Replaced all "assert...Uncookable(..., Pattern messageRegex)" and "assert...Uncookable(..., String messageInfix)" method pairs with a single "assert...Uncookable(..., String messageRegex)" method.
Minor refactoring: Allowed modifiers are now checked in the Parser, not in Java.*. This saves a lot of THROWS clauses.
- Parse Type inference syntax: Type inference for generic instance creation implemented, test cases added.
- Parse MethodReference, ClassInstanceCreationReference and ArrayCreationReference

### Version 3.0.12
- Fixed: Operator "&" not defined on types "java.lang.Long" and "int"
- Major bug in JavaSourceClassLoader: When loading the second and following classes, CUs were compiled again, leading to an inconsistent class hierarchy.
- Fixed: Java 9 added "@Override public final CharBuffer CharBuffer.rewind() { ..." -- leads easily to a java.lang.NoSuchMethodError
- Changed all occurences of the words "Java bytecode" to "JVM bytecode" to make clearer that the generated bytecode is for the JVMS and not suitable for, e.g. DALVIK.

http://janino-compiler.github.io/janino/changelog.html

## How was this patch tested?

Existing test

### CODE REVIEW

**Comment by maropu** [comment]
Just a question: skips 3.0.12? It seems the change logs for 3.0.13 are listed in the description.

**Comment by wangyum** [comment]
Thank you @maropu I added some change logs for 3.0.12.

**Comment by kiszk** [comment]
Looks good to me

One question. Do you wait for confirming the fix of this issue? @JoshRosen 
https://github.com/janino-compiler/janino/issues/90

**Review by srowen — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
Yay. +1, LGTM, too. So, we are waiting @JoshRosen 's confirmation about janino-compiler/janino#90, right?

**Review by maropu — APPROVED** [review]

**Review by HyukjinKwon — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by dongjoon-hyun** [comment]
Gentle ping, @JoshRosen . It would be really great if we can get a confirmation for you.

**Comment by JoshRosen** [comment]
I haven't had a chance to confirm the Janino bugfix yet, but I don't think that's a blocker to merging this version bump: AFAIK we're not relying on the patched functionality yet.

**Comment by dongjoon-hyun** [comment]
I see. Great. Thank you so much, @JoshRosen .
Merged to master.

Also, Thank you, @wangyum , @kiszk , @srowen , @maropu , @HyukjinKwon !

**Pull request closed without merging**
