### PR TITLE
[SPARK-31136] Revert SPARK-30098 Use default datasource as provider for CREATE TABLE syntax

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This is one of the drafts which we are discussion now to comply with new rubrics.
This PR (SPARK-31136) is created to see how many tests are affected.

### Why are the changes needed?

This aims to comply the new community policy.

### Does this PR introduce any user-facing change?

Yes. This restores the existing behavior to avoid breaking the existing user pipeline.

### How was this patch tested?

Pass the Jenkins.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
As expected, it fails. But, unfortunately, it failed at the first failure.

**Comment by dongjoon-hyun** [comment]
A lot of failures are remaining.
```
 org.apache.spark.sql.SQLQueryTestSuite.sql	1.1 sec	1
 org.apache.spark.sql.SQLQueryTestSuite.sql	3.2 sec	1
 org.apache.spark.sql.connector.DataSourceV2SQLSuite.CreateTable: without USING clause	2 ms	1
 org.apache.spark.sql.connector.DataSourceV2SQLSuite.CreateTableAsSelect: without USING clause	4 ms	1
 org.apache.spark.sql.execution.command.DDLParserSuite.Test CTAS #3	2 ms	1
 org.apache.spark.sql.execution.command.DDLParserSuite.create table - basic	1 ms	1
 org.apache.spark.sql.execution.command.DDLParserSuite.create table - with database name	2 ms	1
 org.apache.spark.sql.execution.command.DDLParserSuite.create table - temporary	2 ms	1
 org.apache.spark.sql.execution.command.DDLParserSuite.create table - external	2 ms	1
 org.apache.spark.sql.execution.command.DDLParserSuite.create table - if not exists	2 ms	1
 org.apache.spark.sql.execution.command.DDLParserSuite.create table - comment	3 ms	1
 org.apache.spark.sql.execution.command.DDLParserSuite.create table - partitioned columns	3 ms	1
 org.apache.spark.sql.execution.command.DDLParserSuite.create table - clustered by	2 ms	1
 org.apache.spark.sql.execution.command.DDLParserSuite.create table - properties	1 ms	1
 org.apache.spark.sql.sources.InsertSuite.SPARK-29174 Support LOCAL in INSERT OVERWRITE DIRECTORY to data source
```

**Comment by cloud-fan** [comment]
I agree that we should evaluate the "cost to break", but looking at unit tests may not be a good idea. They heavily rely on internal assumptions and changing the table format will definitely break a lot of unit tests.

Ideally, table format only decides how the table is stored and should be a performance thing, but hive table is a bit different. IMO, the "cost to break" is losing hive compatibility a bit: Now the tables created without USING may not be readable to hive, and some hive specific commands like LOAD TABLE doesn't work for them.

On the other hand, the "cost to maintain" is losing Spark's perf benefits: Many users just run `CREATE TABLE` like they do in other databases, which creates a hive table before 3.0. This means all the features we build for our native readers are not available, like the vectorized reader, nested column pruning, nested field filter pushdown (@dbtsai is working on it), bucketed table, etc.

I think in this case the "cost to maintain" is more serious and we should accept this change. cc @marmbrus @srowen  @maropu @viirya @HyukjinKwon

**Comment by dongjoon-hyun** [comment]
> I'm not looking at the number of failures.

Since the UT had better be independent to the global conf changes, we had better add guards with `withSQLConf` at least.

**Comment by dongjoon-hyun** [comment]
Hi, All. I marked SPARK-31136 as a correctness issue and added the example.

**Comment by HyukjinKwon** [comment]
Looks coherent to revert it per @marmbrus's policy and reverts made so far, although I personally are not really convinced that we should revert.

Reverting this change discourages users to leverage Spark's new features and edge optimizations, and let users more stick to Hive. What's your thought @marmbrus?

**Comment by HyukjinKwon** [comment]
cc @rxin too

**Comment by dongjoon-hyun** [comment]
It just became a correctness issue due to the another example of `CHAR` type.

**Comment by dongjoon-hyun** [comment]
Retest this please

**Comment by dongjoon-hyun** [comment]
Thank you all! I'm going to close this PR because this is discussed explicitly.

**Pull request closed without merging**
