### PR TITLE
[SPARK-8368] [SPARK-8058] [SQL] HiveContext may override the context class loader of the current thread

### PR DESCRIPTION
**Pull request by yhuai**
https://issues.apache.org/jira/browse/SPARK-8368

Also, I add tests according https://issues.apache.org/jira/browse/SPARK-8058.

### CODE REVIEW

**Comment by yhuai** [comment]
cc @andrewor14 @marmbrus

**Comment by andrewor14** [comment]
retest this please

**Comment by andrewor14** [comment]
lgtm. I will try this patch out locally and report back in a few.

**Comment by andrewor14** [comment]
Alright, I just verified that this patch fixes it. I ran the following:
```
$ build/sbt -Phive assembly compile
$ bin/pyspark --packages "com.databricks:spark-csv_2.10:1.0.3"
> a = {'a':1.0, 'b':'asdf'}
> rdd = sc.parallelize([a])
> df = sqlContext.createDataFrame(rdd)
> df.save("/tmp/d.csv", "com.databricks.spark.csv")
```
It failed before the patch but succeeds after it.

**Comment by andrewor14** [comment]
@marmbrus can you do a final sign-off?

**Comment by marmbrus** [comment]
LGTM

**Comment by appleyuchi** [comment]
this bug happens again in spark2.3.1
could you have a look at this please?@andrewor14
https://issues.apache.org/jira/browse/SPARK-31629

**Pull request closed without merging**
