### PR TITLE
[SPARK-32324][SQL]Fix error messages during using PIVOT and lateral view

### PR DESCRIPTION
**Pull request by GuoPhilipse**
### What changes were proposed in this pull request?
improve error messages

### Why are the changes needed?
Currently when we use `lateral view` and `pivot` together in from clause, if  `lateral view` is before `pivot`, the error message is "LATERAL cannot be used together with PIVOT in FROM clause".if if  `lateral view` is after `pivot`,**the query will be norma**l ,So the error messages "LATERAL cannot be used together with PIVOT in FROM clause" is not accurate, we may improve it.

Steps to reproduce:

```

CREATE TABLE person (id INT, name STRING, age INT, class int, address STRING);
INSERT INTO person VALUES
(100, 'John', 30, 1, 'Street 1'),
(200, 'Mary', NULL, 1, 'Street 2'),
(300, 'Mike', 80, 3, 'Street 3'),
(400, 'Dan', 50, 4, 'Street 4');

```

Query1:

```

SELECT * FROM person
lateral view outer explode(array(30,60)) tabelName as c_age
lateral view explode(array(40,80)) as d_age
PIVOT (
count(distinct age) as a
for name in ('Mary','John')
)

```

Result 1:

```

Error: org.apache.spark.sql.catalyst.parser.ParseException: 
LATERAL cannot be used together with PIVOT in FROM clause(line 1, pos 9)

== SQL ==
SELECT * FROM person
---------^^^
lateral view outer explode(array(30,60)) tabelName as c_age
lateral view explode(array(40,80)) as d_age
PIVOT (
count(distinct age) as a
for name in ('Mary','John')
) (state=,code=0)

```

Query2:

```

SELECT * FROM person
PIVOT (
count(distinct age) as a
for name in ('Mary','John')
)
lateral view outer explode(array(30,60)) tabelName as c_age
lateral view explode(array(40,80)) as d_age

```

Reuslt2:

```

+------+-------+-------+--------+--------+
| id | Mary | John | c_age | d_age |
+------+-------+-------+--------+--------+
| 300 | NULL | NULL | 30 | 40 |
| 300 | NULL | NULL | 30 | 80 |
| 300 | NULL | NULL | 60 | 40 |
| 300 | NULL | NULL | 60 | 80 |
| 100 | 0 | NULL | 30 | 40 |
| 100 | 0 | NULL | 30 | 80 |
| 100 | 0 | NULL | 60 | 40 |
| 100 | 0 | NULL | 60 | 80 |
| 400 | NULL | NULL | 30 | 40 |
| 400 | NULL | NULL | 30 | 80 |
| 400 | NULL | NULL | 60 | 40 |
| 400 | NULL | NULL | 60 | 80 |
| 200 | NULL | 1 | 30 | 40 |
| 200 | NULL | 1 | 30 | 80 |
| 200 | NULL | 1 | 60 | 40 |
| 200 | NULL | 1 | 60 | 80 |
+------+-------+-------+--------+--------+

```

### Does this PR introduce _any_ user-facing change?
NO

### How was this patch tested?
unit test

### CODE REVIEW

**Comment by maropu** [comment]
ok to test

**Comment by HyukjinKwon** [comment]
ok to test

**Comment by maropu** [comment]
The mssage update itself seems okay; cc: @maryannxue @gatorsmile cuz I checked the original PR for `PIVOT`: https://github.com/apache/spark/pull/21187

**Comment by GuoPhilipse** [comment]
We have the following defined in spark/sql/catalyst/src/main/antlr4/org/apache/spark/sql/catalyst/parser/SqlBase.g4.  but it seems `pivotClause` and `lateralView` need to replace the order too?

```
fromClause
    : FROM relation (',' relation)* lateralView* pivotClause?
```

**Comment by GuoPhilipse** [comment]
> The mssage update itself seems okay; cc: @maryannxue @gatorsmile cuz I checked the original PR for `PIVOT`: #21187

 I just pull with latest code, it still behaviors the same as PR description.  any new ideas? @maropu @HyukjinKwon @maryannxue @gatorsmile

**Comment by maropu** [comment]
> We have the following defined in spark/sql/catalyst/src/main/antlr4/org/apache/spark/sql/catalyst/parser/SqlBase.g4. but it seems pivotClause and lateralView need to replace the order too?

Why did you think so? Seems like the definition make the error message explicit:
https://github.com/apache/spark/pull/21324#discussion_r188078585

**Comment by GuoPhilipse** [comment]
> > We have the following defined in spark/sql/catalyst/src/main/antlr4/org/apache/spark/sql/catalyst/parser/SqlBase.g4. but it seems pivotClause and lateralView need to replace the order too?
> 
> Why did you think so? Seems like the definition make the error message explicit:
> [#21324 (comment)](https://github.com/apache/spark/pull/21324#discussion_r188078585)

@maropu  Now my confusing point is the following sytax is not defined in SqlBase.g4. but it seems to be allowed to used in Spark, and no errors throw out. it might be  understandable if this behavior throws error like `LATERAL cannot be used together with PIVOT in FROM clause` or basic sytax error. 

```
SELECT * FROM person
PIVOT (
count(distinct age) as a
for name in ('Mary','John')
)
lateral view outer explode(array(30,60)) tabelName as c_age
lateral view explode(array(40,80)) as d_age
```

**Comment by maropu** [comment]
I don't dig into it though, probably the second case is matched in `querySpecification`:
https://github.com/apache/spark/blob/db47c6e340a63100d7c0e85abf237adc4e2174cc/sql/catalyst/src/main/antlr4/org/apache/spark/sql/catalyst/parser/SqlBase.g4#L501-L502

**Comment by GuoPhilipse** [comment]
> I don't dig into it though, probably the second case is matched in `querySpecification`:
> https://github.com/apache/spark/blob/db47c6e340a63100d7c0e85abf237adc4e2174cc/sql/catalyst/src/main/antlr4/org/apache/spark/sql/catalyst/parser/SqlBase.g4#L501-L502

emmm,   if so, when our user execute the following sql and get expected result, they may think `PIVOT` Clause and work together with `lateral ` clause, we may make it more clear in SqlBase.g4 or error notification ? WDYT?
```
SELECT * FROM person
PIVOT (
count(distinct age) as a
for name in ('Mary','John')
)
lateral view outer explode(array(30,60)) tabelName as c_age
lateral view explode(array(40,80)) as d_age
```

**Comment by maropu** [comment]
> we may make it more clear in SqlBase.g4 

Any idea for that? I personally that the message update this PR proposes looks okay now.

**Comment by GuoPhilipse** [comment]
Thanks @maropu , jenkins please retest it .

**Comment by maropu** [comment]
retest this please

**Comment by GuoPhilipse** [comment]
cc @maropu @HyukjinKwon, Could you please help check what else need i do to close this PR ?

**Comment by HyukjinKwon** [comment]
The previous exception message doesn't particularly wrong to me if you're arguing:

```
LATERAL cannot be used together with PIVOT in FROM clause
```

doesn't explain the case below:

```sql
SELECT * FROM person
PIVOT (
count(distinct age) as a
for name in ('Mary','John')
)
lateral view outer explode(array(30,60)) tabelName as c_age
lateral view explode(array(40,80)) as d_age
```

because it already clarifies `FROM` and `PIVOT`.

**Pull request closed without merging**
