### PR TITLE
[SPARK-31257][SPARK-33561][SQL][FOLLOWUP] Fix Scala 2.13 compilation

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR is a follow-up to fix Scala 2.13 compilation.

### Why are the changes needed?

To support Scala 2.13 in Apache Spark 3.1.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the GitHub Action Scala 2.13 compilation job.

### CODE REVIEW

**Review by rdblue — APPROVED** [review]

**Comment by rdblue** [comment]
Thank you for fixing this, @dongjoon-hyun! Looks good to me, assuming that tests will pass.

**Comment by dongjoon-hyun** [comment]
Thank you, @rdblue !

**Review by srowen — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @srowen !

**Comment by dongjoon-hyun** [comment]
Scala 2.13 passed. I'll merge this.

Screen Shot 2020-11-25 at 9 55 12 AM

**Pull request closed without merging**
