### PR TITLE
Scalable SkipGram-Word2Vec implementation

### PR DESCRIPTION
**Pull request by ezamyatin**
### What changes were proposed in this pull request?

A new SkipGram-Word2Vec implementation has been added to mllib package. 

### Why are the changes needed?

Current Word2Vec implementation has limits on the maximum model size and loses accuracy when scaled. There are no such problems in my implementation.
Advantages of my implementation:
1. The most popular word2vec algorithm: skip-gram with negative sampling.
2. No accuracy degradation as the number of partitions increases.
3. No model size limitations. Vocab size(instead of vocab_size x vector_size) is limited by maximum integer number, but it can be easy solved by changing to long internal id. This limitation is critical when we can't effectively limit the vocab by min_count. The example of such task is node2vec.
4. Better accuracy on downstream tasks. (see Comparison section)
5. Multithreading support.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

JavaSkipGramSuite has been added. I also plan to compare performance and accuracy on a public dataset.

### New implementation description
Suppose the number of partitions is set to **K**. Each epoch is divided in the **K** subiterations. Each subiteration is divided into three stages:
1. Randomly assign word embeddings to partitions by hashing with salt corresponding to current subiteration.
2. Generate train pairs. Assign pairs to partitions by hashing with salt the central word as in the first step. Pairs with different central and context word partitions are dropped.
3. Process each partition by in-memory skip-gram algorithm. Negative samples are taken within the partition.

The probability to keep pair in the second stage is 1/**K**. So after **K** iterations each train pair will be processed on average.

#### Complexity
1. `O(shuffle(|V| * dim))`.
2. `O(read(|D|) + shuffle(|D| * 2 * w / K))`
3. `O(read(|D| * 2 * w * n * dim / K)))`

**|V|** is a vocab size, **dim** is a vector dimensionality, **|D|** is a dataset size, **n** is a number of negative samples, **w** is a widow size. **read** is processing data within partition, **shuffle** is data reshuffling.

### Spark Word2Vec vs SkipGram comparison
The embedding training dataset is [First billion characters from wikipedia](http://mattmahoney.net/dc/enwik9.zip).
The downstream task is [BBC News Classification](https://www.kaggle.com/c/learn-ai-bbc).

Validation protocol:
1. Train embeddings on enwik9 dataset.
5. Train GaussianNB classifier over word embeddings to classify news into topics.
6. Evaluate classification model accuracy.

The validation script is [here](https://gist.github.com/EvgenyZamyatin/56bcea451d275dd2438a40f315faa8ca).

Results:
```
model_type=Word2Vec	training_time=4.985min	    num_partitions=8	    accuracy=0.41184 +/- 0.00435
model_type=Word2Vec	training_time=2.412min	    num_partitions=16	    accuracy=0.42184 +/- 0.00449
model_type=Word2Vec	training_time=1.619min	    num_partitions=32	    accuracy=0.41413 +/- 0.00428
model_type=Word2Vec	training_time=1.165min	    num_partitions=64	    accuracy=0.39551 +/- 0.00429
model_type=Word2Vec	training_time=1.242min	    num_partitions=128	    accuracy=0.39926 +/- 0.00406
```
```
model_type=SkipGram	training_time=4.753min      num_partitions=8	    accuracy=0.48198 +/- 0.00441
model_type=SkipGram	training_time=4.305min      num_partitions=16	    accuracy=0.51076 +/- 0.00402
model_type=SkipGram	training_time=6.319min      num_partitions=32	    accuracy=0.50508 +/- 0.0043
model_type=SkipGram	training_time=10.656min     num_partitions=64	    accuracy=0.50061 +/- 0.00447
model_type=SkipGram	training_time=21.951min     num_partitions=128	    accuracy=0.50037 +/- 0.00402
```
**The best SkipGram's result outperforms the best Word2Vec's result by 20%.**

You can notice that unlike the standard implementation, SkipGram implementation does not accelerate monotonically with the growth of the number of partitions. The optimal number of partitions is not necessarily the maximum. It's because of asymptotic complexity of my solution:
`K * (|D| + |D| * 2 * w * n * dim / K)`,
where **K** is number of partitions, **|D|** is the dataset size, **w** is the window param, **n** is the negative samples param and **dim** is the vector size param. When we increase **K**, we increase time consuming for first term in the sum and decrease for the second.

### CODE REVIEW

**Comment by EvgenyZamyatin** [comment]
Hi! Could anyone review this pr?

**Comment by EvgenyZamyatin** [comment]
How could I fix this error? The problem is due to the change of parallel collections in scala 2.13
I can fix it for scala 2.13, but how I could fix it for cross building?
```
[error] /home/runner/work/spark/spark/mllib/src/main/scala/org/apache/spark/mllib/feature/SkipGram.scala:47:64: object forkjoin is not a member of package concurrent
[error]     val support = new ForkJoinTaskSupport(new scala.concurrent.forkjoin.ForkJoinPool(cpus))
[error]                                                                ^
[error] /home/runner/work/spark/spark/mllib/src/main/scala/org/apache/spark/mllib/feature/SkipGram.scala:49:22: value par is not a member of Seq[A]
[error] did you mean map, max, or span?
[error]       val parr = arr.par
[error]                      ^
[error] /home/runner/work/spark/spark/mllib/src/main/scala/org/apache/spark/mllib/feature/SkipGram.scala:56:64: object forkjoin is not a member of package concurrent
[error]     val support = new ForkJoinTaskSupport(new scala.concurrent.forkjoin.ForkJoinPool(cpus))
[error]                                                                ^
[error] /home/runner/work/spark/spark/mllib/src/main/scala/org/apache/spark/mllib/feature/SkipGram.scala:58:22: value par is not a member of Seq[A]
[error] did you mean map, max, or span?
[error]       val parr = arr.par
[error]                      ^
[error] four errors found
[error] (mllib / Compile / compileIncremental) Compilation failed
[error] Total time: 429 s (07:09), completed Sep 22, 2022 5:09:20 PM
```

**Comment by EvgenyZamyatin** [comment]
@zhengruifeng Hi!
Could you please review my changes?

**Comment by zhengruifeng** [comment]
so this is a totally new implementation of `SkipGram` W2V in `.mllib`

is it possible to improve existing w2v instead of implementing a new one?
what about implementing it in `.ml` side? since `.mllib` was in maintenance mode

I think we should wait for @srowen @WeichenXu123 @huaxingao  @mengxr 's opinions since this is a big change;

**Comment by EvgenyZamyatin** [comment]
> is it possible to improve existing w2v instead of implementing a new one?
Yes. How do you think it should be done? Under a mode setting?

> what about implementing it in .ml side? since .mllib was in maintenance mode
Will do.

**Comment by EvgenyZamyatin** [comment]
@zhengruifeng @srowen @WeichenXu123 @huaxingao @mengxr 
Hi guys! Ping.

**Review by srowen — COMMENTED** [review]
There's a lot that would have to change here about how this is done (like Spark ML impl) but Spark MLlib is not being updated further and I just don't know if this makes sense in Spark vs a separate package

**Comment by EvgenyZamyatin** [comment]
> There's a lot that would have to change here about how this is done (like Spark ML impl) but Spark MLlib is not being updated further and I just don't know if this makes sense in Spark vs a separate package

Is it ok to have a separate class or is it better to make an option inside existing w2v implementation?

**Comment by EvgenyZamyatin** [comment]
The main advantage of my implementation is unlimited model size. It allows to train really large-scale models. I think it would be very useful for community.

**Comment by EvgenyZamyatin** [comment]
Hi, guys!
What do you think about my pull request?
@srowen @WeichenXu123 @huaxingao @mengxr

**Comment by srowen** [comment]
The macro issue here is that we have an implementation in MLlib, and aren't really adding more to it. This is a whole new implementation to maintain. (Minor: it adds the fastuil dependency which we had problems with in the past, but that's not a big deal; see also https://spark.apache.org/contributing.html)

I don't think we would add more here, but would consider changes to the existing impl. Or this can be just released as a separate repo/library.

**Comment by ezamyatin** [comment]
Moved to https://github.com/ezamyatin/node2vec-spark

**Pull request closed without merging**
