### PR TITLE
[SPARK-37837][INFRA] Enable black formatter in dev Python scripts

### PR DESCRIPTION
**Pull request by HyukjinKwon**
### What changes were proposed in this pull request?

This PR proposes to enable [black](https://github.com/psf/black) formatter (automatic Python code formatter) for `dev` directory as well.

### Why are the changes needed?

To have the consistent style, and make for a better development cycle

### Does this PR introduce _any_ user-facing change?

No, dev-only.

### How was this patch tested?

I manually verified it as below:

```bash
dev/reformat-python
dev/linter-python
```

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @zero323 @dongjoon-hyun FYI.

**Review by dongjoon-hyun — APPROVED** [review]
+1, this looks straightforward.

**Comment by dongjoon-hyun** [comment]
Although there is no logical change, I want to see the running, @HyukjinKwon .

BTW, @HyukjinKwon , your public GitHub Action seems to be crowded. This PR is in the queue still.

**Review by yikf — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]

**Review by zero323 — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Merged to master.

**Pull request closed without merging**
