### PR TITLE
[SPARK-20661][WIP] try to dump table names

### PR DESCRIPTION
**Pull request by felixcheung**
## What changes were proposed in this pull request?

.. to see what tables are leaked.

tests are expected to fail.

Do not merge

## How was this patch tested?

Jenkins

### CODE REVIEW

**Comment by felixcheung** [comment]
Jenkins, retest this please

**Comment by felixcheung** [comment]
The leaked tables are


x[1]: "bucketed_table"
y[1]: ""

x[2]: "sorted_bucketed_table"
y[2]: NA

**Comment by gatorsmile** [comment]
Is it created by `readwriter.py`?

**Comment by felixcheung** [comment]
how about here?https://github.com/apache/spark/blob/096df6d933c5326e5782aa8c5de842a0800eb369/sql/core/src/test/scala/org/apache/spark/sql/sources/BucketedWriteSuite.scala#L188  `withTable` isn't there

**Comment by gatorsmile** [comment]
[Second one](https://github.com/apache/spark/blob/096df6d933c5326e5782aa8c5de842a0800eb369/sql/core/src/test/scala/org/apache/spark/sql/sources/BucketedWriteSuite.scala#L188) should not create a table; otherwise, it is a critical bug. 

[The third one](https://github.com/apache/spark/blob/master/sql/hive/src/test/resources/ql/src/test/queries/clientpositive/bucket5.q#L12) are skipped by us. See[ the link](https://github.com/apache/spark/blob/master/sql/hive/compatibility/src/test/scala/org/apache/spark/sql/hive/execution/HiveCompatibilitySuite.scala#L219).

After my previous PR, I think sql/core and sql/hive are safe. Now, the Python side still needs a clean.

**Comment by gatorsmile** [comment]
Two tables `bucketed_table ` and `sorted_bucketed_table ` are from the same file `readwriter.py`.

**Comment by felixcheung** [comment]
ah, you are right. I'm going to fix the python code

**Comment by felixcheung** [comment]
opened PR 17932

**Pull request closed without merging**
