### PR TITLE
[SPARK-17761][SQL] Remove MutableRow

### PR DESCRIPTION
**Pull request by hvanhovell**
## What changes were proposed in this pull request?

In practice we cannot guarantee that an `InternalRow` is immutable. This makes the `MutableRow` almost redundant. This PR folds `MutableRow` into `InternalRow`.

The code below illustrates the immutability issue with InternalRow:

``` scala
import org.apache.spark.sql.catalyst.InternalRow
import org.apache.spark.sql.catalyst.expressions.GenericMutableRow
val struct = new GenericMutableRow(1)
val row = InternalRow(struct, 1)
println(row)
scala> [[null], 1]
struct.setInt(0, 42)
println(row)
scala> [[42], 1]
```

This might be somewhat controversial, so feedback is appreciated.
## How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by hvanhovell** [comment]
cc @cloud-fan we have discussed this in your MutableProjection PR.

**Comment by liancheng** [comment]
Would be nice to add a simple example to illustrate why we can't ensure that a `GenericInternalRow` is immutable. For example, for a `GenericInternalRow` with a `StructType` field, it's legal to put a `MutableRow` into the cell. This essentially makes the outer `GenericInternalRow` mutable. (In fact, we are already doing this in Spark, either intentionally or unintentionally.)

**Comment by marmbrus** [comment]
This seems like a reasonable simplification to me.  A little bit of history (though this has diverged significantly, so don't take this authoritative):  I think this complexity all stems from `SpecificMutableRow`, which had nothing to do with `Immutable` vs `Mutable`, but instead about having a more efficient row that you could mutate without boxing.  This was back before Tungsten/codegen, so is probably obsolete now.

**Comment by hvanhovell** [comment]
Merging to master. Thanks for commenting.

**Pull request closed without merging**
