### PR TITLE
[SPARK-24553][UI][FOLLOWUP] Fix unnecessary UI redirect

### PR DESCRIPTION
**Pull request by jerryshao**
## What changes were proposed in this pull request?

This PR is a follow-up PR of #21600 to fix the unnecessary UI redirect.

## How was this patch tested?

Local verification

### CODE REVIEW

**Comment by jerryshao** [comment]
Jenkins, retest this please.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by jerryshao** [comment]
@dongjoon-hyun , this should also be backported to branch 2.4, let me create a backport PR.

**Pull request closed without merging**
