### PR TITLE
[SPARK-2750] support https in spark web ui

### PR DESCRIPTION
**Pull request by scwf**
https://issues.apache.org/jira/browse/SPARK-2750

enable spark web ui to support https, also compatible with old web ui(http).

user can switch between https and http by configure "spark.http.policy".

### CODE REVIEW

**Comment by JoshRosen** [comment]
Hi @scwf,

I just merged #3571, which added SSL support for Akka and the HTTPServer.  That PR added a common configuration mechanism for SSL, plus some useful utilities for testing this functionality.  If you're interested, it would be great to revisit HTTPS for the web UI now that we've merged that other patch.

**Comment by scwf** [comment]
in that PR now no https support for web ui right? if so i will rework this to support it.

**Comment by JoshRosen** [comment]
@scwf Yep, that PR only added SSL support to Akka and the HTTP FileServer, not the web UI or the shuffle service.

**Comment by scwf** [comment]
i am closing this in favor of #5664

**Comment by pritpalm** [comment]
I want to enable https on spark UI. I added following config to spark-defaults.config, but when we access spark ui via https::/<ip>:8080 or https://<ip>:443 or https://<ip>:8480, it's not able to connect.

spark.ui.https.enabled true
spark.ssl.keyPassword abcd
spark.ssl.keyStore rtmqa-clientid.jks
spark.ssl.keyStorePassword changeit

**Pull request closed without merging**
