### PR TITLE
[SPARK-15782][hotfix] Fix compilation with Scala 2.10.

### PR DESCRIPTION
**Pull request by vanzin**

### CODE REVIEW

**Comment by vanzin** [comment]
@rxin

**Comment by nezihyigitbasi** [comment]
@vanzin thanks for fixing this.

**Comment by rxin** [comment]
Ah the "fix" is much larger than I thought (I thought it would've been an one liner)

@davies was suggesting reverting the commit and then do a proper review.

**Comment by davies** [comment]
@nezihyigitbasi I reverted that commit both in master and 2.0.

**Comment by vanzin** [comment]
It looks large but it's basically just moving the method to the class instead of the object.

**Comment by vanzin** [comment]
But well, you already reverted the change, so @nezihyigitbasi please send the PR again with my changes on top.

**Comment by rxin** [comment]
Thanks @nezihyigitbasi.

**Comment by nezihyigitbasi** [comment]
yep will do.

**Pull request closed without merging**
