### PR TITLE
[SPARK-12973][YARN] Support to set priority when submit spark application to YARN

### PR DESCRIPTION
**Pull request by debugger87**

### CODE REVIEW

**Comment by debugger87** [comment]
I found another similar PR #8943 which is closed in case of that [YARN-1963](https://issues.apache.org/jira/browse/YARN-1963) has not been implemented. I will close this pr for the same reason.

**Comment by jerryshao** [comment]
This will be supported in Hadoop 2.8, probably we could enable this beforehand.

**Comment by debugger87** [comment]
@jerryshao reopen this pr ?

**Comment by srowen** [comment]
I'm not taking any position on whether this should be reopened, but, it should be attached to https://issues.apache.org/jira/browse/SPARK-10879 and take into account the discussion there and on the prior PR.

**Comment by debugger87** [comment]
@srowen The best choice is to close this PR and it's not necessary to do the same work like #8943.

**Pull request closed without merging**
