### PR TITLE
[SPARK-25997][ML]add Python example code for Power Iteration Clustering in spark.ml

### PR DESCRIPTION
**Pull request by huaxingao**
## What changes were proposed in this pull request?

Add python example for Power Iteration Clustering in spark.ml

## How was this patch tested?

Manually tested

### CODE REVIEW

**Comment by holdenk** [comment]
Thanks for working on this! I noticed you have the example on / off tags, normally those correspond with it being included in documentation somewhere the those tags are used -- is that the plan for this PR?

**Comment by srowen** [comment]
@huaxingao is this one still active?

**Comment by huaxingao** [comment]
@srowen Yes, it's still active. Could you please review?

**Review by srowen — APPROVED** [review]

**Comment by srowen** [comment]
Merged to master

**Comment by huaxingao** [comment]
Thanks! @srowen

**Pull request closed without merging**
