### PR TITLE
[SPARK-22519][YARN] Remove unnecessary stagingDirPath null check in ApplicationMaster.cleanupStagingDir()

### PR DESCRIPTION
**Pull request by devaraj-kavali**
## What changes were proposed in this pull request?
Removed the unnecessary stagingDirPath null check in ApplicationMaster.cleanupStagingDir().

## How was this patch tested?
I verified with the existing test cases.

### CODE REVIEW

**Comment by vanzin** [comment]
ok to test

**Comment by srowen** [comment]
Rather, wasn't think likely intended to be a check on whether the env variable exists?

**Comment by vanzin** [comment]
@srowen see discussion in the bug.

**Comment by vanzin** [comment]
Merging to master.

**Pull request closed without merging**
