### PR TITLE
[SPARK-36972][PYTHON]Add max_by/min_by API to PySpark

### PR DESCRIPTION
**Pull request by yoda-mon**
### What changes were proposed in this pull request?

Add max_by/min_by to PySpark

### Why are the changes needed?

for pyspark users' convenience

### Does this PR introduce _any_ user-facing change?

yes, new methods are added

### How was this patch tested?

docstring tests

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]
Looks good otherwise. cc @sarutak FYI

**Comment by HyukjinKwon** [comment]
the test failure on TPC-DS is not related.

**Comment by yoda-mon** [comment]
Finally I switched to `show` and took screenshot of the documents.

image
image

**Review by HyukjinKwon — APPROVED** [review]
Looks good otherwise

**Review by sarutak — APPROVED** [review]
LGTM. Merging to `master`.

**Pull request closed without merging**
