### PR TITLE
[Spark-8343] [Streaming] [Docs] Improve Spark Streaming Guides.

### PR DESCRIPTION
**Pull request by dusenberrymw**
This improves the Spark Streaming Guides by fixing broken links, rewording confusing sections, fixing typos, adding missing words, etc.

### CODE REVIEW

**Comment by JoshRosen** [comment]
Ah, looks like this _just_ conflicted with #6781.

Just wanted to say that I'm a huge fan of these style of documentation cleanup patches: they're a lot of work but have a big impact since these docs are pretty widely consumed. :+1:

**Comment by dusenberrymw** [comment]
@JoshRosen Thanks!  Also, I fixed the conflicts for this request, so we should be good to go now.

**Comment by JoshRosen** [comment]
The wordsmithing seems fine to me, but I'll defer to @tdas to sign off on the technical changes / edits to code examples.

**Comment by dusenberrymw** [comment]
Actually, I think the code example changes were brought in when I merged with #6781.  I'm going to close this PR, and open another one that is merged better.

**Pull request closed without merging**
