### PR TITLE
[SPARK-29506][SQL] Use dynamicPartitionOverwrite in FileCommitProtocol when insert into hive table

### PR DESCRIPTION
**Pull request by viirya**
### What changes were proposed in this pull request?

When insert overwrite into hive table, enabling dynamicPartitionOverwrite when initializing FileCommitProtocol.

### Why are the changes needed?

HadoopMapReduceCommitProtocol uses FileOutputCommitter to commit job output files. 

FileOutputCommitter continues do FileSystem.listStatus for directories in partitions, recursively, and commits job output leaf files:

https://github.com/apache/hadoop/blob/c0a0c353e86fc3f3d4eedd91aeb9d5b9c8eb748a/hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-core/src/main/java/org/apache/hadoop/mapreduce/lib/output/FileOutputCommitter.java#L478-L490

It is inefficient when dynamically overwritting many partitions and files.

HadoopMapReduceCommitProtocol, when dynamicPartitionOverwrite is enabled, writes to staging dir dynamically, and commits written partition directories, instead of leaf files.

### Does this PR introduce any user-facing change?

No

### How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by viirya** [comment]
cc @felixcheung @cloud-fan

**Comment by cloud-fan** [comment]
For hive table insertion, we insert to a fresh staging dir first. So dynamicPartitionOverwrite and normal write are logically the same IIUC. Do you mean dynamicPartitionOverwrite is better for performance?

**Comment by turboFei** [comment]
> For hive table insertion, we insert to a fresh staging dir first. So dynamicPartitionOverwrite and normal write are logically the same IIUC. Do you mean dynamicPartitionOverwrite is better for performance?

Hi, @cloud-fan I think dynamicPartitionOverwrite would keep a filesToMove set and  the times to rename file is partitions-num.
https://github.com/apache/spark/blob/f4d5aa42139ff8412c573c96a1631ef3ccf81844/core/src/main/scala/org/apache/spark/internal/io/HadoopMapReduceCommitProtocol.scala#L181-L183

And normal write(let file output committer algorithm version to 1), per task would commit output to a temp path.
For example:
_temporary/0/task_attempt_1/p1=v1/p2=v2/task1.parquet
_temporary/0/task_attempt_2/p1=v1/p2=v2/task2.parquet
_temporary/0/task_attempt_3/p1=v1/p2=v2/task3.parquet

After all tasks completed,  it would invoke mergePaths to merge these output.
The cost is larger for a partitioned table than dynamicPartitionOverwrite.

But there is a known issue for dynamicPartitionOverwrite,  a task may conflict with its speculation task.
I have created a PR https://github.com/apache/spark/pull/26086, can you help take a look?

**Comment by viirya** [comment]
@cloud-fan FileOutputCommitter commits job in an inefficient way. 

1. List all committed task paths under job attempt path:

https://github.com/apache/hadoop/blob/c0a0c353e86fc3f3d4eedd91aeb9d5b9c8eb748a/hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-core/src/main/java/org/apache/hadoop/mapreduce/lib/output/FileOutputCommitter.java#L402-L406

https://github.com/apache/hadoop/blob/c0a0c353e86fc3f3d4eedd91aeb9d5b9c8eb748a/hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-core/src/main/java/org/apache/hadoop/mapreduce/lib/output/FileOutputCommitter.java#L329-L333

2. Merge paths under committed task paths to job output path. When there are conflicting path names, it merges paths/files recursively:

https://github.com/apache/hadoop/blob/c0a0c353e86fc3f3d4eedd91aeb9d5b9c8eb748a/hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-core/src/main/java/org/apache/hadoop/mapreduce/lib/output/FileOutputCommitter.java#L486-L489

But dynamicPartitionOverwrite simply renames partition paths under staging dir to job output path.

**Comment by cloud-fan** [comment]
Just to confirm, it's all for performance right? Does it fix a correctness issue?

**Comment by viirya** [comment]
@cloud-fan Yeah, this is not about correctness.

**Comment by cloud-fan** [comment]
It looks to me that the underlying issue is: MR committer is slow and we need a home-made custom committer.

I think this is a big story and needs more discussion. This PR is just a trick to bypass the MR committer by using dynamicPartitionOverwrite when the behavior/result is not affected.

**Comment by viirya** [comment]
HadoopMapReduceCommitProtocol is somehow a custom committer in Spark. Actually we use it with dynamicPartitionOverwrite in this way, at least for data source.

**Comment by cloud-fan** [comment]
IIUC `HadoopMapReduceCommitProtocol` is a wrapper of the hadoop MR committer. The code you refer to that proves the inefficient is all from hadoop MR committer, right?

**Comment by viirya** [comment]
yes, that's right.

**Comment by viirya** [comment]
retest this please

**Comment by viirya** [comment]
retest this please

**Comment by viirya** [comment]
This issue causes real problem in our production jobs. Whether to come out a home-made custom committer for this issue, is another story. IMHO, it seems an overkill, because only dynamic partition overwrite is a problem.

I added a config to control it and it is false by default. So it should be conservative and safe.

also cc @HyukjinKwon @dongjoon-hyun for some review and options.

**Comment by rezasafi** [comment]
Enabling dynamic partition overwrite can cause issues like SPARK-27194. Probably better to fix that bug first.

**Comment by viirya** [comment]
@rezasafi thanks for referring that. Is it specified to enabling dynamicPartitionOverwrite? As the task id was fixed in setupJob, I think this is also happened without this patch?

**Comment by turboFei** [comment]
@viirya  Hi,  for the issue mentioned by @rezasafi , I have created a ticket to fix it.
Could you help take a look? Thanks in advance!

**Comment by rezasafi** [comment]
> @rezasafi thanks for referring that. Is it specified to enabling dynamicPartitionOverwrite? As the task id was fixed in setupJob, I think it is also happened without this patch?

Hi @viirya, yeah that issue happens when dynamicPartitionOverwrite is enabled. It seems that after your fix is merged if people there would be more cases that hit SPARK-27194. So was just wondering whether it is better to fix that first before suggesting to use it in more scenarios.
I haven't looked at @turboFei fix.

**Comment by viirya** [comment]
@rezasafi Do you have idea why it only happens when dynamicPartitionOverwrite is enabled?

**Comment by rezasafi** [comment]
I think the jira and also the discussion on the first pr that was created for it is describing the issue in more detail. Basically the current dynamic partition overwrite implementation didn't consider the case that a task may fail during the commit. If a container fail, the task that was running there will fail but its written data won't be cleaned up and the rerun of the task will hit the FileAlreadyExistsException. The discussions under PR#24142 also debated  a proposed solution because of the concern of duplicate data.

**Comment by viirya** [comment]
@rezasafi yea I know that PR and read some discussion there. My question is this seems not specified to dynamic partition overwrite case. I did not see an analysis about it is specified for dynamic partition overwrite case, or I miss it? The problem happens because the filename to write was produced by same params between tasks retries, so the same path was written and FileAlreadyExistsException was thrown. Even dynamic partition overwrite is disabled, I did not see there is difference in determining the path to write. So wondering if it is specified to dynamic partition overwrite or not.

**Comment by rezasafi** [comment]
We experienced that issue only when dynamic partition overwrite was set.  I don't know whether it is possible to hit this issue without dynamic partition overwrite.

**Comment by turboFei** [comment]
@rezasafi  @viirya  For the issue you mentioned.
The reason is that the filename is only escaped with taskId and without attemptId.
We also met it when spark speculation is enabled, for that a task's filename is conflicted with its speculation task. 


https://github.com/apache/spark/blob/077fb99a26a9e92104503fade25c0a095fec5e5d/core/src/main/scala/org/apache/spark/internal/io/HadoopMapReduceCommitProtocol.scala#L108-L118

As shown in the code, I think the risk is same when the output committer is non-FileOutputCommitter, but I have not met this case and I think it is rare.

I have read the comments under PR #24142, and it seems that there is a risk for non-FileOutputCommitter case, if a task aborted and failed to clean up its output, result would be duplicated.
I created a PR #26086, which fix the issue for dynamic partition overwrite only.

**Comment by viirya** [comment]
@cloud-fan Would like to hear if you have other comments? If you still have concern on this, I will close this.

**Pull request closed without merging**
