### PR TITLE
[SPARK-14893][SQL] Re-enable HiveSparkSubmitSuite SPARK-8489 test after HiveContext is removed

### PR DESCRIPTION
**Pull request by dilipbiswal**
## What changes were proposed in this pull request?

Enable the test that was disabled when HiveContext was removed.
## How was this patch tested?

Made sure the enabled test passes with the new jar.

### CODE REVIEW

**Comment by dilipbiswal** [comment]
cc @andrewor14

**Comment by andrewor14** [comment]
@dilipbiswal thanks for fixing this! There's actually one more change that needs to be made in `regression-test-SPARK-8489/Main.scala`, since we're removing `SparkSession.withHiveSupport`. In particular, I would replace these lines (L36):

```
    val sc = new SparkContext("local", "testing")
    val sparkSession = SparkSession.withHiveSupport(sc)
    // This line should not throw scala.reflect.internal.MissingRequirementError.
    // See SPARK-8470 for more detail.
    val df = sparkSession.createDataFrame(Seq(MyCoolClass("1", "2", "3")))
```
with
```
    val spark = SparkSession.builder
      .master("local")
      .appName("testing")
      .enableHiveSupport()
      .getOrCreate()
    // This line should not throw scala.reflect.internal.MissingRequirementError.
    // See SPARK-8470 for more detail.
    val df = spark.createDataFrame(Seq(MyCoolClass("1", "2", "3")))
```

**Comment by dilipbiswal** [comment]
@andrewor14 Sure Andrew. I will change it.

**Comment by andrewor14** [comment]
Thanks, LGTM

**Comment by andrewor14** [comment]
Merging into master 2.0.

**Comment by dilipbiswal** [comment]
@andrewor14 Thank you Andrew !!

**Pull request closed without merging**
