### PR TITLE
[SPARK-14435][BUILD] Shade Kryo in our custom Hive 1.2.1 fork

### PR DESCRIPTION
**Pull request by JoshRosen**
This patch updates our custom Hive 1.2.1 fork in order to shade Kryo in Hive. This is a blocker for upgrading Spark to use Kryo 3 (see #12076).

The source for this new fork of Hive can be found at https://github.com/JoshRosen/hive/tree/release-1.2.1-spark2

Here's the complete diff from the official Hive 1.2.1 release: https://github.com/apache/hive/compare/release-1.2.1...JoshRosen:release-1.2.1-spark2

Here's the diff from the sources that @pwendell used to publish the current `1.2.1.spark` release of Hive: https://github.com/pwendell/hive/compare/release-1.2.1-spark...JoshRosen:release-1.2.1-spark2. This diff looks large because his branch used a shell script to rewrite the groupId, whereas I had to commit the groupId changes in order to prevent the find-and-replace from affecting the package names in our relocated Kryo classes: https://github.com/pwendell/hive/compare/release-1.2.1-spark...JoshRosen:release-1.2.1-spark2#diff-6ada9aaec70e069df8f2c34c5519dd1e

Using these changes, I was able to publish a local version of Hive and verify that this change fixes the test failures which are blocking #12076. Note that this PR will not compile until we complete the review of the Hive POM changes and stage and publish a release.

/cc @vanzin, @steveloughran, and @pwendell for review.

### CODE REVIEW

**Comment by JoshRosen** [comment]
@vanzin, in light of #11941 do you think that we should change the namespace of our shaded protobuf to omit the hyphens?

**Comment by vanzin** [comment]
Yeah, if we're rebuilding dependencies already, might as well avoid issues with the sort-of-illegal package names...

**Comment by JoshRosen** [comment]
Alright, updated to keep the relocated classes under the `org.apache.hive` namespace (like was previously done for Kryo):

```diff
diff --git a/ql/pom.xml b/ql/pom.xml
index 16f3d05..09a59bd 100644
--- a/ql/pom.xml
+++ b/ql/pom.xml
@@ -739,7 +739,7 @@
                 </relocation>
                 <relocation>
                   <pattern>com.google.protobuf</pattern>
-                  <shadedPattern>org.spark-project.hive.shaded.com.google.protobuf</shadedPattern>
+                  <shadedPattern>org.apache.hive.com.google.protobuf</shadedPattern>
                 </relocation>
               </relocations>
             </configuration>
```

**Comment by JoshRosen** [comment]
I have packaged and staged a new release of our custom Hive (I was careful to compile using JDK 7). Provided that tests pass here, I'm going to publish to Maven Central, wait for the new version to propagate, then loop back tomorrow and will commit this to unblock Kryo 3.

**Comment by JoshRosen** [comment]
There are two test failures, but they're both related to tests of the shading: one failed due to my removal of the hyphenated package namespace in relocated protobuf, and the other failed because it was explicitly checking for unshaded Kryo.

**Comment by JoshRosen** [comment]
Okay, so given that this passes all of the relevant Hive tests, I'm going to promote my 1.2.1-spark2 release to Maven Central, then will update this patch to prepare for final merge-readiness.

**Comment by JoshRosen** [comment]
org.spark-project.hive:hive-exec:1.2.1.spark2 is now on Maven Central, so this PR is no longer WIP.

**Comment by JoshRosen** [comment]
Jenkins, retest this please.

**Comment by JoshRosen** [comment]
Jenkins retest this please

**Comment by vanzin** [comment]
LGTM

**Comment by JoshRosen** [comment]
Alright, I'm going to merge this to master and will resume work on the other patch for the Kryo 3 migration.

**Pull request closed without merging**
