### PR TITLE
[SPARK-30032][BUILD] Upgrade to ORC 1.5.8

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to upgrade to Apache ORC 1.5.8.

### Why are the changes needed?

This will bring the latest bug fixes. The following is the full release note.
- https://issues.apache.org/jira/projects/ORC/versions/12346462

### Does this PR introduce any user-facing change?

No.

### How was this patch tested?

Pass the Jenkins with the existing tests.

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]
Looks good if tests pass

**Comment by dongjoon-hyun** [comment]
Opps. Sorry, I added the manifest updated, too.

**Comment by HyukjinKwon** [comment]
Its alright. I noticed but thankfully that's part of our test :D

**Review by viirya — APPROVED** [review]

**Review by gengliangwang — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @HyukjinKwon , @viirya , @gengliangwang .
Merged to master.

**Pull request closed without merging**
