### PR TITLE
[SPARK-7397][Streaming] Add missing inputInfo report code

### PR DESCRIPTION
**Pull request by jerryshao**
I think this issue is introduced in #5732

### CODE REVIEW

**Comment by jerryshao** [comment]
Jenkins, retest this please.

**Comment by tdas** [comment]
I am choosing #5950 in favor of this one as that one has a test to prevent this from happening in the future.Thanks though for catching this! Mind closing this for now.

**Comment by jerryshao** [comment]
Hi @tdas, please take a look at this PR, I think this is a problem introduced by #5732 , and should be fixed. Thanks a lot :)

**Comment by jerryshao** [comment]
OK, cool.

**Pull request closed without merging**
