### PR TITLE
[SPARK-44921][SQL] Remove SqlBaseLexer.tokens from codebase

### PR DESCRIPTION
**Pull request by amaliujia**
### What changes were proposed in this pull request?

https://github.com/apache/spark/commit/8ff6b7a04cbaef9c552789ad5550ceab760cb078#diff-f4df4ce19570230091c3b2432e3c84cd2db7059c7b2a03213d272094bd940454 refactors antlr4 files to `sql/api` but checked in `SqlBaseLexer.tokens`. 

This file is generated so we do not need to check it in.

### Why are the changes needed?

Remove file that do not need to be checked in.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Existing Test.

### Was this patch authored or co-authored using generative AI tooling?

No

### CODE REVIEW

**Comment by amaliujia** [comment]
@cloud-fan @hvanhovell

**Review by hvanhovell — APPROVED** [review]
LGTM

**Review by cloud-fan — APPROVED** [review]

**Review by yaooqinn — APPROVED** [review]

**Comment by yaooqinn** [comment]
thanks, merged to master and 3.5.0

**Comment by LuciferYang** [comment]
late LGTM

**Pull request closed without merging**
