### PR TITLE
[SPARK-12249][SQL] JDBC non-equality comparison operator not pushed down.

### PR DESCRIPTION
**Pull request by HyukjinKwon**
https://issues.apache.org/jira/browse/SPARK-12249
Currently `!=` operator is not pushed down correctly.
I simply added a case for this.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Several things to mention.

Firstly, I did not add the tests for it because not pushed down filters are not correctly tested. I will add as soon as https://github.com/apache/spark/pull/10221 is merged.

Secondly, I just opened this PR without asking if it is really supposed to be supported. This is because I see the test codes intended to check this operator (which is not testing properly) and also I don't think there is no database not supporting this operator as it is a SQL Standard.

**Comment by HyukjinKwon** [comment]
I updated the test for this since https://github.com/apache/spark/pull/10221 is merged.

**Comment by HyukjinKwon** [comment]
cc @rxin @marmbrus

**Comment by HyukjinKwon** [comment]
cc @rxin @marmbrus

**Comment by rxin** [comment]
Thanks - I've merged this into master.

**Pull request closed without merging**
