### PR TITLE
[SPARK-19213] DatasourceScanExec uses runtime sparksession

### PR DESCRIPTION
**Pull request by robert3005**
## What changes were proposed in this pull request?

Physical plan for hadoop fs relation uses active session at the moment of execution

## How was this patch tested?

Tests added to cover the behaviour

### CODE REVIEW

**Comment by hvanhovell** [comment]
@robert3005 why is this needed?

**Comment by robert3005** [comment]
This was posted mostly to get comments on what's the expected behaviour. What's unclear is whether dataset can be shared across sparksessions and if so what are the semantics and behaviour of it. It seems off to me that physical plan of hadoopfsrelation will use sparksession from the moment when it was defined. In cases where sparksession is bound to physical plans we can use Dataset.ofRows to swap sparksession from logical plan but for hadoopfsrelation that won't work. I'd think FileSourceScanExec would at least use the session from the moment of execution (on from SparkPlan). However, if we can share datasets across sessions then it makes sense to not tie the session to concrete physical plan but fetch it every time the plan gets executed.

**Comment by ash211** [comment]
@hvanhovell the need is also explained in the Jira ticket: https://issues.apache.org/jira/browse/SPARK-19213

Does that code snippet make sense?

**Comment by ash211** [comment]
@hvanhovell does that description make sense?

**Comment by hvanhovell** [comment]
I suppose it makes sense. The only thing I am wondering if this doesn't subtly breaks things. I am certain that some weirdness is to be expected with respect to session local configurations. For instance the plan could be analyzed under one set of configurations and be executed under a different set. I do think that we should consistent.

@robert3005 could you revert all the caching logic which is currently part of this PR, and just make this about SparkSessions?

**Comment by gatorsmile** [comment]
retest this please

**Comment by robert3005** [comment]
Removed the caching logic. It was there since I wasn't sure how often we call inputRDDs and how many times the resulting rdd would get created overall since it's a def now

**Pull request closed without merging**
