### PR TITLE
[SPARK-46697][SQL][HIVE] Eliminate Hive configuration time variables conversion

### PR DESCRIPTION
**Pull request by pan3793**
### What changes were proposed in this pull request?

Eliminate the `HiveUtils.formatTimeVarsForHiveClient`

### Why are the changes needed?

`HiveUtils.formatTimeVarsForHiveClient` was introduced to handle compatibility with Hive prior 0.14.0, as Spark 4.0 only supports Hive 2.0+, it's now unnecessary.

> Hive 0.14.0 introduces timeout operations in HiveConf, and changes default values of a bunch
> of time `ConfVar`s by adding time suffixes (`s`, `ms`, and `d` etc.).  This breaks backwards-
> compatibility when users are trying to connecting to a Hive metastore of lower version,
> because these options are expected to be integral values in lower versions of Hive.
>
> Here we enumerate all time `ConfVar`s and convert their values to numeric strings according
> to their output time units.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass GA.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
+1, this looks reasonable to me.

**Comment by dongjoon-hyun** [comment]
Also, cc @LuciferYang

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Mind retriggering https://github.com/pan3793/spark/actions/runs/7501484603/job/20422355010?

**Comment by pan3793** [comment]
@HyukjinKwon CI is green now

**Comment by dongjoon-hyun** [comment]
Merged to master. Thank you, @pan3793 and all.

**Comment by LuciferYang** [comment]
late LGTM ~

**Pull request closed without merging**
