### PR TITLE
[SPARK-45013][TEST] Flaky Test with NPE: track allocated resources by taskId

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

This PR ensures the runningTasks to be updated before subsequent tasks causing NPE

### Why are the changes needed?

fix flakey tests 

### Does this PR introduce _any_ user-facing change?

no
### How was this patch tested?

It shall fix
```
- track allocated resources by taskId *** FAILED *** (36 milliseconds)
[info]   java.lang.NullPointerException: Cannot invoke "org.apache.spark.executor.Executor$TaskRunner.taskDescription()" because the return value of "java.util.concurrent.ConcurrentHashMap.get(Object)" is null
[info]   at org.apache.spark.executor.CoarseGrainedExecutorBackend.statusUpdate(CoarseGrainedExecutorBackend.scala:275)
[info]   at org.apache.spark.executor.CoarseGrainedExecutorBackendSuite.$anonfun$new$22(CoarseGrainedExecutorBackendSuite.scala:351)
[info]
```

### Was this patch authored or co-authored using generative AI tooling?

no

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @yaooqinn .

**Comment by dongjoon-hyun** [comment]
I verified manually.
```
[info] CoarseGrainedExecutorBackendSuite:
[info] - parsing no resources (468 milliseconds)
[info] - parsing one resource (27 milliseconds)
[info] - parsing multiple resources resource profile (11 milliseconds)
[info] - parsing multiple resources (9 milliseconds)
[info] - error checking parsing resources and executor and task configs (18 milliseconds)
[info] - executor resource found less than required resource profile (9 milliseconds)
[info] - executor resource found less than required (8 milliseconds)
[info] - use resource discovery (25 milliseconds)
[info] - use resource discovery and allocated file option with resource profile (19 milliseconds)
[info] - use resource discovery and allocated file option (18 milliseconds)
[info] - track allocated resources by taskId (252 milliseconds)
[info] - SPARK-24203 when bindAddress is not set, it defaults to hostname (1 millisecond)
[info] - SPARK-24203 when bindAddress is different, it does not default to hostname (1 millisecond)
[info] - Tasks launched should always be cancelled. (1 second, 358 milliseconds)
[info] - Tasks not launched should always be cancelled. (175 milliseconds)
[info] - SPARK-40320 Executor should exit when initialization failed for fatal error (2 seconds, 472 milliseconds)
[info] Run completed in 5 seconds, 660 milliseconds.
[info] Total number of tests run: 16
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 16, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[success] Total time: 71 s (01:11), completed Nov 6, 2023, 10:52:27 PM
```

**Comment by dongjoon-hyun** [comment]
According to the `Affected Version` of JIRA, I landed to master branch only.
Please feel free to backport this if you need.

**Comment by yaooqinn** [comment]
Thanks @dongjoon-hyun

**Comment by beliefer** [comment]
@yaooqinn Thank you for the fix.

**Comment by LuciferYang** [comment]
Thanks @yaooqinn !!!

**Pull request closed without merging**
