### PR TITLE
[SPARK-20119][test-maven]Fix the test case fail in DataSourceScanExecRedactionSuite

### PR DESCRIPTION
**Pull request by gatorsmile**
### What changes were proposed in this pull request?
Changed the pattern to match the first n characters in the location field so that the string truncation does not affect it.

### How was this patch tested?
N/A

### CODE REVIEW

**Comment by gatorsmile** [comment]
cc @ueshin @hvanhovell

**Comment by gatorsmile** [comment]
Follow what @kayousterhout suggested in the email. Created a JIRA for the test case issue.

**Comment by kayousterhout** [comment]
Thanks @gatorsmile!

**Comment by hvanhovell** [comment]
LGTM - merging to master. Thanks!

**Pull request closed without merging**
