### PR TITLE
[SPARK-31764][CORE][3.0] JsonProtocol doesn't write RDDInfo#isBarrier

### PR DESCRIPTION
**Pull request by sarutak**
### What changes were proposed in this pull request?

This PR backports the change of #28583 (SPARK-31764) to branch-3.0, which changes JsonProtocol to write RDDInfos#isBarrier.

### Why are the changes needed?

JsonProtocol reads RDDInfos#isBarrier but not write it so it's a bug.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

I added a testcase.

### CODE REVIEW

**Comment by sarutak** [comment]
CC: @jiangxb1987 @HeartSaVioR

**Review by HeartSaVioR — APPROVED** [review]
LGTM

**Comment by HeartSaVioR** [comment]
cc. @jiangxb1987 to see the chance we can include this on 3.0.0.

**Comment by jiangxb1987** [comment]
Retest this please

**Comment by sarutak** [comment]
#28693 seems to break the build for `branch-3.0`.
`DateTimeUtils` doesn't have `microsToMillis` in `branch-3.0`.

**Comment by jiangxb1987** [comment]
The commit has been reverted from branch-3.0 . Please rebase and try again @sarutak , thanks!

**Comment by sarutak** [comment]
Thanks @jiangxb1987 ! I'll retry.

**Comment by jiangxb1987** [comment]
Thanks, merged to 3.0 !

**Pull request closed without merging**
