### PR TITLE
[SPARK-24927][BUILD][BRANCH-2.3] The scope of snappy-java cannot be "provided"

### PR DESCRIPTION
**Pull request by liancheng**
## What changes were proposed in this pull request?

Please see [SPARK-24927][1] for more details.

[1]: https://issues.apache.org/jira/browse/SPARK-24927

## How was this patch tested?

Manually tested.

### CODE REVIEW

**Comment by gatorsmile** [comment]
retest this please

**Comment by liancheng** [comment]
The Kafka DStream test failures seem to be flaky and irrelevant.

**Comment by liancheng** [comment]
retest this please

**Comment by liancheng** [comment]
retest this please

**Comment by cloud-fan** [comment]
LGTM, how far shall we backport this patch?

**Comment by jiangxb1987** [comment]
LGTM

**Comment by liancheng** [comment]
@cloud-fan  Didn't try to actually reproduce this issue in branches other than branch-2.3, but just by checking the POM files, this issue existed ever since at least 1.6.

**Comment by HyukjinKwon** [comment]
Seems right to me too.

**Comment by gatorsmile** [comment]
retest this please

**Comment by gatorsmile** [comment]
Thanks! Merged to master/2.3/2.2

**Pull request closed without merging**
