### PR TITLE
[SPARK-45006][UI] Use the same date format of other UI date elements for the x-axis of timelines

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

This PR introduces a custom date format aligned with other UI elements for the x-axis of the timeline graph. For example,

image

FYI, https://momentjs.com/docs/#/displaying/format/

### Why are the changes needed?

It can be distracting when the values and axes are not presented in the same format.

### Does this PR introduce _any_ user-facing change?

yes

##### Regular size

image

##### zoom in

image

##### zoom out

image

image

### Was this patch authored or co-authored using generative AI tooling?

no

### CODE REVIEW

**Comment by yaooqinn** [comment]
cc @sarutak @dongjoon-hyun @HyukjinKwon, thanks

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @yaooqinn .

**Comment by dongjoon-hyun** [comment]
I verified it manually by building and checking UI.
Merged to master for Apache Spark 4.0.0.

**Comment by dongjoon-hyun** [comment]
I believe this is an UI improvement and updated the JIRA issue type, @yaooqinn .

**Pull request closed without merging**
