### PR TITLE
[SPARK-5236] Fix ClassCastException in SpecificMutableRow

### PR DESCRIPTION
**Pull request by alexbaretta**

### CODE REVIEW

**Comment by squito** [comment]
can you add a unit test for what this fixes?  I don't see how this avoids the exceptions, just seems to push them down into `MutableValue.update`.  A test case would help convince me (admittedly I'm really unfamiliar with this code).

**Comment by alexbaretta** [comment]
@squito This is not new functionality for which it would make sense to write a unit test. This is a hotfix for a bug. I am completely unfamiliar with this code, but I understand pretty well that although Int is a subtype of Any, MutableInt is not a subtype of MutableAny; hence, whereas, it is possible to cast val declared of type Any to an Int--a type-unsafe operation that can fail hard but can also succeed if the payload of the Any val is indeed an int--a cast from MutableAny to MutableInt is simply impossible and will necessarily fail, even if the payload of the MutableAny is indeed an Int. If you look at the JIRA you will see this as the cause of failure:

Caused by: java.lang.ClassCastException: org.apache.spark.sql.catalyst.expressions.MutableAny cannot be cast to org.apache.spark.sql.catalyst.expressions.MutableInt

Now, a question worth asking to the author of this class, is why does SparkSQL rely on this type-casting mechanism to parse Parquet files? I am inclined to believe that there is a deeper issue here. That being said, my patch does allow my SQL queries to complete successfully against my Parquet dataset instead of failing.

**Comment by squito** [comment]
I think finding & fixing a bug in current behavior is a great reason to add a unit test.  Some part of the implementation is confusing enough to have allowed a bug in the first place, a test will help prevent that bug from cropping up again in future changes.

From the description you gave me, this seems like a minimal test case:

```
class SpecificMutableRowTest extends FunSuite with Matchers {

  test("update MutableAny") {
    val row = new SpecificMutableRow(Seq(StringType))
    row.update(0, 1)
    row.getInt(0) should be (1)
  }

}
```

I agree that this does seem kinda suspicious that maybe there is something deeper going on ... why is a field that is supposed to be an int getting assigned a type of `MutableAny` instead of `MutableInt`, though apparently `CatalystPrimitiveConverter` has decided to call the `int` specific methods like `setInt` etc.?

**Comment by squito** [comment]
btw, while you're mucking around in there ... it might be nice to change the `SpecificMutableRow` constructor to take varargs.  Change this constructor:

```
-  def this(dataTypes: Seq[DataType]) =
+  def this(dataTypes: DataType*) =
```

and then just get rid of the other constructor:

```
-  def this() = this(Seq.empty)
-
```

that way you don't have to wrap those types with a `Seq`, eg. instead of `new SpecificMutableRow(Seq(StringType [, IntType, ...]))` you can just do `new SpecificMutableRow(StringType [, IntType,...])`

**Comment by alexbaretta** [comment]
Ok, happy to look into this, but I will be out for the next few days, so this isn't going to happen before the weekend.

**Comment by squito** [comment]
Back to the question of something deeper being wrong ...

I think we'll need to wait for input from somebody more familiar w/ this code. @marmbrus ?
But one helpful thing you could do would be to provide a minimal example that reproduced this.  Eg., some tiny parquet file & an example query maybe?  [SPARK-5236](https://issues.apache.org/jira/browse/SPARK-5236) is really short on details.

(sorry for splitting into so many comments, keep getting distracted ...)

**Comment by liancheng** [comment]
The sole purpose of adding `SpecificMutableRow` is to avoid boxing cost, so using `boxed` here doesn't sound good. For SPARK-5236, schema mismatch can often produce similar exceptions. @alexbaretta Would you please add a snippet that helps reproducing this issue in the JIRA ticket description? I guess the root cause hides elsewhere.

**Comment by liancheng** [comment]
ok to test

**Comment by marmbrus** [comment]
I believe this problem has been fixed and we can close this issue.

**Comment by dilip-k-m** [comment]
I've got the same issue in production.
I was able to replicate in our performance test environment. So, concluded that, with the same cluster configuration, if a spark job is fed growing rate of input traffic, while writing after processing the feed, it generates parquet files with corrupted footer.
Again, this probability of footer corruption increases when more unique values[the input file has more distinct values, i.e. lesser redundant field values] are fed.
If, number of partitions to write is increased, then also this probability is reduced.

I have found that Spark 2.x does not have such issue.

**Pull request closed without merging**
