### PR TITLE
[SPARK-34973][SQL] Cleanup unused fields and methods in vectorized Parquet reader

### PR DESCRIPTION
**Pull request by sunchao**
### What changes were proposed in this pull request?

Remove some unused fields and methods in `SpecificParquetRecordReaderBase` and `VectorizedColumnReader`.

### Why are the changes needed?

Some fields and methods in these classes are no longer used since years ago. It's better to clean them up to make the code easier to maintain and read.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Existing tests

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
Looks reasonable. Pending CIs. Thanks, @sunchao .

**Review by HyukjinKwon — COMMENTED** [review]
If they are not used, then yeah let's remove. Looks good

**Review by viirya — APPROVED** [review]
I guess like Repetition/Definition readers may be for nested reader. It is okay to remove if we don't use it now.

**Comment by HyukjinKwon** [comment]
Oh actually @c21 is working on Parquet nested ones .. might be good to have his look.

**Comment by sunchao** [comment]
Thanks for the review. I'm not sure if these are intended for nested types - they were introduced in #9774 and soon replaced by the vectorized value readers. For nested reader we might want to do something differently instead of reusing the parquet-mr classes, such as decode a batch of def/rep levels at a time according to the batch size.

**Review by c21 — APPROVED** [review]
+1 to remove now given it's not used.

**Comment by viirya** [comment]
Thanks all. Merging to master.

**Pull request closed without merging**
