### PR TITLE
[SPARK-10533][SQL][follow-up] remove DecimalLit

### PR DESCRIPTION
**Pull request by cloud-fan**
A cleanup for https://github.com/apache/spark/pull/9085.

The `DecimalLit` is very similar to `FloatLit`, we can just keep one of them.
Also added low level unit test at `SqlParserSuite`

### CODE REVIEW

**Comment by cloud-fan** [comment]
cc @adrian-wang @liancheng

**Comment by adrian-wang** [comment]
maybe it would be better to keep `DecimalLit`, rather than `FloatLit`.

**Comment by cloud-fan** [comment]
I don't  have a strong preference here, @yhuai  what do you think?

**Comment by rxin** [comment]
DecimalLit sounds better to keep than FloatLit.

**Comment by rxin** [comment]
Thanks - I've merged this.

**Comment by rxin** [comment]
Did you have the wrong jira ticket?

**Comment by cloud-fan** [comment]
ah sorry, I was working on multiple PRs and messed up the jira number...

**Pull request closed without merging**
