### PR TITLE
[SPARK-16484][SQL] Add HyperLogLogPlusPlus sketch generator/evaluator/aggregator

### PR DESCRIPTION
**Pull request by RyanBerti**
### What changes were proposed in this pull request?
This PR converts the existing HyperLogLogPlusPlus case class into a trait, and adds a set of case classes which extend that trait and provide new functionality to generate/evaluate/aggregate the serialized version of the HLL++ sketch.

### Why are the changes needed?
These additional functions are being added to support HLL++ re-aggregation, which can provide significant performance improvements when running distinct counts over time series datasets.

### Does this PR introduce _any_ user-facing change?
Yes, this PR adds two new aggregate functions, approx_count_distinct_sketch and approx_count_distinct_agg_sketch. This PR also introduces a non-aggregate function approx_count_distinct_eval_sketch.

### How was this patch tested?
Unit tests were added to the HyperLogLogPlusPlusSuite and the DataFrameAggregateSuite to test sketch generation, evaluation, and aggregation.

### CODE REVIEW

**Comment by RyanBerti** [comment]
For reference, @dtenedor worked with me on a pre-review of these changes; relevant discussions are available in this PR in my fork: https://github.com/RyanBerti/spark/pull/1

**Comment by dtenedor** [comment]
Hi @RyanBerti, after a few initial conversations about this proposal, we wanted to express some questions and opinions here for your consideration. In general, we wholeheartedly appreciate your time, energy, and attention in working on this collection of features in the interest of expanding the functionality and usefulness of Apache Spark (as well as increasing consistency with other engines).

* We feel strongly that the new function names should not begin with "approx_count_distinct" in order to differentiate the new sketch-based approach against the existing approximate distinct count implementation. In particular, the sketch-based approach exposes intermediate buffers suitable for saving into storage and then retrieving and merging later, whereas the existing "approx_count_distinct" aggregate function consumes input values and then returns the result immediately (without exposing any intermediate sketch to the user). This is essentially a function naming detail, and we can consider a prefix like "HLL_" for the new functions in order to accomplish this objective. This change should not consume too much time to bring into effect.

* After examining the existing helper library in the existing [HyperLogLogPlusPLusHelper utility](https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/util/HyperLogLogPlusPlusHelper.scala), and comparing to other formats for generating and merging sketches for similar purposes, we would like to express a strong preference for using the Apache DataSketches library instead (https://datasketches.apache.org/). This is a dedicated Apache project with more than a decade of investment behind it, supporting very high performance for multiple types of sketches (such as KLL sketches for computing approximate quantiles, for example) and with client library support in C++, Java, and Python. We can use the Java implementation to integrate with Apache Spark using Scala/Java integration. This also aligns with the principles of Apache Spark as an open source project 

Best,
Daniel

@czarifis
@mkaravel
@gatorsmile 
@entong

**Comment by huaxingao** [comment]
@RyanBerti Thanks for the great work!

+1 for using Apache DataSketches library. 

I am wondering if we can use [Theta Sketches](https://datasketches.apache.org/docs/Theta/ThetaSketchFramework.html) because it supports union, intersection and difference, while HLL sketches only supports union. Trino recently has added the support to use Apache DataSketches's Theta sketch to calculate distinct value, and Apache Iceberg defines Apache DataSketches's Theta as the common data sketch for keeping track of distinct values in a table.

**Comment by RyanBerti** [comment]
Hi @dtenedor and @huaxingao 

Thanks for the input! I agree with you both that migrating Spark's existing HLL++ implementation to use the Apache Datasketches library would be ideal. Unfortunately, migrating to another HLL++ implementation would require a bit more work, when compared with exposing the sketch associated with the existing implementation. Here are some of my initial thoughts on what it would take to migrate Spark's existing HLL++ implementations to use the Apache Datasketches library:

- Add [datasketches-java](https://github.com/apache/datasketches-java) as a new dependency to Spark
- Add one or more new AggregateFunctions which forward calls from ImperativeAggregate.update and Expression.eval to a [Datasketch HllSketch instance](https://datasketches.apache.org/api/java/snapshot/apidocs/org/apache/datasketches/hll/HllSketch.html), and forward calls from ImperativeAggregate.merge to a [Datasketch Union instance](https://datasketches.apache.org/api/java/snapshot/apidocs/org/apache/datasketches/hll/Union.html). I think there's technical complexity/unknowns involved in instantiating the HllSketch and Union instances such that they store their intermediate state in the AggregationFunction's aggregation buffer - this would likely involve wrapping the agg buffer in an implementation of Datasketch's [WritableMemory interface](https://datasketches.apache.org/api/memory/snapshot/apidocs/org/apache/datasketches/memory/WritableMemory.html).
- Provide a mechanism for existing users to utilize the new Datasketches based HLL implementation for approx_count_distinct + approx_distinct_count_for_intervals (and utilize the existing HyperLogLogPlusPlus implementation by default?)

I'm not as familiar with Theta Sketches, but it sounds like that sketch format would be best for cross-compatibility between Spark/Presto+Trino/Iceberg, though I'm not sure if there's additional work to support Theta Sketches when compared with HLL sketches. 

Given the increased scope, I'm not sure I can commit to working through this migration in the short term. My opinion is that exposing the existing HLL sketches would still be beneficial, and would not block the migration to Apache Datasketches in the future.

**Comment by dtenedor** [comment]
Hi @RyanBerti just checking up on this :) are you back from PTO and still interested in this work?

**Comment by RyanBerti** [comment]
Closing in favor of https://github.com/apache/spark/pull/40615

**Pull request closed without merging**
