### PR TITLE
[SPARK-14006][SPARKR] Fix SparkR lint-r test errors in branch-1.6.

### PR DESCRIPTION
**Pull request by sun-rui**
## What changes were proposed in this pull request?

A backport of #11652 for branch 1.6. It fixes all newly captured SparkR lint-r errors after the lintr package is updated from github.
## How was this patch tested?

dev/lint-r
SparkR unit tests

### CODE REVIEW

**Comment by mengxr** [comment]
@sun-rui Shall we use a released version of lintr from CRAN? Using `install_github` makes our builds depend on a mutable source. If we need some new features from lintr, we should ask the author to make a release on CRAN first. cc: @jimhester @yhuai

**Comment by mengxr** [comment]
Merged into branch-1.6. @sun-rui Could you close this PR manually? Let's discuss the issue with `install_github` on SPARK-14074.

**Comment by jimhester** [comment]
You can always pin to a specific tag, sha1, PR# using `install_github()`, there is no need for a CRAN release to have a stable source.

**Comment by mengxr** [comment]
Git tags are mutable and commits could be removed from Git repo. CRAN is certainly a more stable source. Similarly, we use maven central for Java libraries and avoid using third-party repos in our build.

**Comment by sun-rui** [comment]
yes. let's continue the discussion in the new JIRA issue. close this PR.

**Pull request closed without merging**
