### PR TITLE
[SPARK-36390][SQL] Replace SessionState.close with SessionState.detachSession

### PR DESCRIPTION
**Pull request by cxzl25**
### What changes were proposed in this pull request?
SPARK-35286 replace `SessionState.start` with `SessionState.setCurrentSessionState`, but `SessionState.close` will create a `HiveMetaStoreClient` , connect to the Hive Meta Store Server, and then load all functions.

SPARK-35556 (Remove close HiveClient's SessionState) When the Hive version used is greater than or equal to 2.1, `SessionState.close` is not called and the resource dir of HiveClient is not cleaned up.

### Why are the changes needed?
Clean up the hive resources dir temporary directory.
Avoid wasting resources and accelerate the exit speed.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
add UT

### CODE REVIEW

**Comment by cxzl25** [comment]
`SessionState.close` -> `Hive.create` -> `registerAllFunctions`
image

**Comment by cxzl25** [comment]
cc @wangyum  @yaooqinn

**Comment by wangyum** [comment]
ok to test.

**Comment by wangyum** [comment]
+ @HyukjinKwon

**Comment by wangyum** [comment]
Could we change [this line](https://github.com/apache/hive/blob/branch-2.3/ql/src/java/org/apache/hadoop/hive/ql/session/SessionState.java#L1596) to `Hive threadLocalHive = Hive.getWithoutRegisterFns(sessionConf);`?

**Comment by HyukjinKwon** [comment]
Thanks for pinging me @wangyum. The fix seems making sense

**Comment by cxzl25** [comment]
> Could we change [this line](https://github.com/apache/hive/blob/branch-2.3/ql/src/java/org/apache/hadoop/hive/ql/session/SessionState.java#L1596) to `Hive threadLocalHive = Hive.getWithoutRegisterFns(sessionConf);`?

[HIVE-17368](https://issues.apache.org/jira/browse/HIVE-17368) avoid creating a `threadLocalHive` in the `unCacheDataNucleusClassLoaders` method.

https://github.com/apache/hive/blob/branch-3.0/ql/src/java/org/apache/hadoop/hive/ql/session/SessionState.java#L1772

> It seems that this change makes hive.downloaded.resources.dir can not be removed.

AFIAK, because `SessionState.start` is not used, the resources directory will not be created.
Because SPARK-35286 avoids creating session dir, that is, it will not call `createSessionDirs`.
```java
  /**
   * Create dirs & session paths for this session:
   * 1. HDFS scratch dir
   * 2. Local scratch dir
   * 3. Local downloaded resource dir
   * 4. HDFS session path
   * 5. hold a lock file in HDFS session dir to indicate the it is in use
   * 6. Local session path
   * 7. HDFS temp table space
   * @param userName
   * @throws IOException
   */
  private void createSessionDirs(String userName) throws IOException {
```

**Comment by yaooqinn** [comment]
can we have a test with `ADD JAR` command to see whether the resource dir being removed successfully after `detachSession `

**Comment by cxzl25** [comment]
[HIVE-12853](https://issues.apache.org/jira/browse/HIVE-12853) (>=2.1) will create the `hive.downloaded.resources.dir` directory when constructing sessionstate.
https://github.com/apache/hive/blob/branch-2.1/ql/src/java/org/apache/hadoop/hive/ql/session/SessionState.java#L389


SPARK-35556 (Remove close HiveClient's SessionState) did not clean up the resource dir even when the Hive version was greater than or equal to 2.1.

Currently need to clean up the resource dir and then `SessionState#detachSession`.

**Comment by cxzl25** [comment]
> can we have a test with `ADD JAR` command to see whether the resource dir being removed successfully after `detachSession `

I can add a UT to check the resource dir cleanup.

SPARK-34955 removed the behavior of `ADD JAR` calling `runSqlHive`, now `ADD JAR` will not put jar in the resource directory.

**Comment by cxzl25** [comment]
The current `SparkSQLCLIDriver` calls `SessionState.close`, so its download resource dir has been cleaned up, but `HiveClientImpl` and `SparkSQLCLIDriver` have not been cleaned up.
In this PR, I clean up these resource dirs.

**Comment by HyukjinKwon** [comment]
cc @juliuszsompolski FYI

**Comment by juliuszsompolski** [comment]
cc @dragqueen95 FYI

**Comment by cxzl25** [comment]
Gentle ping @wangyum @yaooqinn @HyukjinKwon @juliuszsompolski @ @dragqueen95

**Pull request closed without merging**
