### PR TITLE
Spark 2.0 error in Intellij

### PR DESCRIPTION
**Pull request by bigdatatraining**

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Maybe you'd better close this PR and ask this to user-mailing list. I think we can have a better answer. Please refer http://spark.apache.org/community.html to subscribe.

**Comment by yintengfei** [comment]
You can find : File -> Project Structure -> Modules -> Dependcies , change the provided to compile.

As HyukjinKwon say , you'd better  ask this to user-mailing list .

**Comment by srowen** [comment]
Close this PR please

**Comment by HyukjinKwon** [comment]
ping @bigdatatraining

**Pull request closed without merging**
