### PR TITLE
[SPARK-16550] [SPARK-17042] [core] Certain classes fail to deserialize in block manager replication

### PR DESCRIPTION
**Pull request by ericl**
## What changes were proposed in this pull request?

This is a straightforward clone of @JoshRosen 's original patch. I have follow-up changes to fix block replication for repl-defined classes as well, but those appear to be flaking tests so I'm going to leave that for SPARK-17042
## How was this patch tested?

End-to-end test in ReplSuite (also more tests in DistributedSuite from the original patch).

### CODE REVIEW

**Comment by JoshRosen** [comment]
@ericl, these test failures appear legitimate.

**Comment by ericl** [comment]
Weird, both `core/test-only *DistributedSuite*` and `repl/test-only *ReplSuite*` pass locally for me (jdk-8). I'll look into it tomorrow when I have access to my desktop.

**Comment by ericl** [comment]
This does appear to be a Java-7 issue.

**Comment by ericl** [comment]
Ok weird, I can't reproduce locally any more, even after many tries. I wonder if it's just very rarely flaky, though that seems unlikely.

**Comment by ericl** [comment]
Looks like the second jenkins run failed a slightly different set of the tests than the first.

**Comment by rxin** [comment]
We should fix this one and move on ..

**Comment by ericl** [comment]
Ok interesting, seems the repl fix I attempted breaks DistributedSuite in jenkins.

**Comment by ericl** [comment]
I've split the part causing the test flakes into a separate sub-task so we can get the main patch merged. https://issues.apache.org/jira/browse/SPARK-17042

@JoshRosen now this is basically your original patch.

**Comment by JoshRosen** [comment]
Hmm, weird. Looks like replication tests are still failing. I can help investigate later.

**Comment by ericl** [comment]
@JoshRosen could I get ssh access to the jenkins machines to try reproducing the flakiness there?

**Comment by ericl** [comment]
Thanks, attempting to reproduce this on jenkins....

**Comment by ericl** [comment]
On jenkins, it seems sometimes one block manager will fail to register. The only clue from the logs is
```
16/08/18 18:54:25.796 netty-rpc-connection-0 INFO TransportClientFactory: Successfully created connection to /192.168.10.21:44000 after 1534 ms (0 ms spent in bootstraps)
```

1534ms is much longer than the usual

**Comment by rxin** [comment]
Merging in master/2.0.

**Comment by witgo** [comment]
@rxin  @ericl 
This PR may cause the following code to throw an exception  

```scala
private def getRemoteValues(blockId: BlockId): Option[BlockResult] = {
    getRemoteBytes(blockId).map { data =>
      val values =
        serializerManager.dataDeserializeStream(blockId, data.toInputStream(dispose = true))
      new BlockResult(values, DataReadMethod.Network, data.size)
    }
```

**Pull request closed without merging**
