### PR TITLE
[SPARK-30803][DOCS] Fix the home page link for Scala API document

### PR DESCRIPTION
**Pull request by xuanyuanking**
### What changes were proposed in this pull request?
Change the link to the Scala API document.

```
$ git grep "#org.apache.spark.package"
docs/_layouts/global.html:                                <li><a href="api/scala/index.html#org.apache.spark.package">Scala</a></li>
docs/index.md:* [Spark Scala API (Scaladoc)](api/scala/index.html#org.apache.spark.package)
docs/rdd-programming-guide.md:[Scala](api/scala/#org.apache.spark.package), [Java](api/java/), [Python](api/python/) and [R](api/R/).
```

### Why are the changes needed?
The home page link for Scala API document is incorrect after upgrade to 3.0

### Does this PR introduce any user-facing change?
Document UI change only.

### How was this patch tested?
Local test, attach screenshots below:
Before:
image
After:
image

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Thank you, @xuanyuanking . This seems to need a JIRA issue. I'll file one for this.

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
Hi, @xuanyuanking .
Could you fix the other similar places like the followings?
```
[AccumulatorV2](api/scala/index.html#org.apache.spark.util.AccumulatorV2)
[API documentation](api/scala/index.html#org.apache.spark.util.AccumulatorV2)
```
It seems that we have at least 335 places under `docs` directory.
```
$ git grep "api/scala/index.html#" | wc -l
     335
```

**Comment by dongjoon-hyun** [comment]
cc @srowen , @HyukjinKwon , @wangyum , @jiangxb1987

**Comment by srowen** [comment]
Weird, I wonder why it changed? but yeah we should fix it.

**Comment by HyukjinKwon** [comment]
I think it was because we upgraded Scala to 2.12. They changed the doc style radically...

**Comment by xuanyuanking** [comment]
@dongjoon-hyun Sure, thanks for the reminding. Will keep following this fix.

**Comment by xuanyuanking** [comment]
Address all the error link by below command and some manual change.

sed -i "" -f [replace_rule](https://docs.google.com/document/d/1-WrnADdLrTpdhifXZ2miXcOriJz1hdC4szFscwQfx_k/edit?usp=sharing) *.md

**Review by srowen — APPROVED** [review]
Looks OK for 3.0. We will always be building with 2.12 in 3.x, not 2.11.

**Comment by srowen** [comment]
Jenkins test this please

**Comment by srowen** [comment]
Merged to master/3.0

**Comment by HyukjinKwon** [comment]
+1

**Comment by xuanyuanking** [comment]
Thanks for reviewing.

**Pull request closed without merging**
