### PR TITLE
[SPARK-22075][ML] GBTs unpersist datasets cached by Checkpointer

### PR DESCRIPTION
**Pull request by zhengruifeng**
## What changes were proposed in this pull request?
`PeriodicRDDCheckpointer` will automatically persist the last 3 datasets called by `PeriodicRDDCheckpointer.update()`.
In GBTs, the last 3 intermediate rdds are still cached after `fit()`

## How was this patch tested?
existing tests and local test in spark-shell

### CODE REVIEW

**Review by srowen — COMMENTED** [review]
Do other uses of the checkpointer consistently unpersist too or is this the only one?

**Comment by zhengruifeng** [comment]
retest this please

**Comment by zhengruifeng** [comment]
@srowen In MLlib, `PeriodicRDDCheckpointer` is only used in `GradientBoostedTrees`.
I just find that there is another checkpointer `PeriodicGraphCheckpointer`,  I will check it.

**Comment by zhengruifeng** [comment]
@srowen  I check `LDA` : although `unpersistDataSet` is not called in it, no intermediate cached rdds is generated after `fit()`.
Then I check `Pregel`, and find that each call of `connectedComponents` will add two intermediate cached rdds. So I call `unpersistDataSet` in it and the issue is fixed.
There is no other places using checkpointer.

**Review by srowen — APPROVED** [review]

**Comment by zhengruifeng** [comment]
@srowen I found that the cached rdds in `Pregel` is just the result graph. and the intermidiate rdds are already unpersisted directly out of the graphCheckpointer. So I think we don't need to modify `Pregel`

**Review by WeichenXu123 — COMMENTED** [review]
Looks that if we do not manually unpersist this, it will also be automatically unpersist because the `predErrorCheckpointer` and `validatePredErrorCheckpointer` will no longer be referenced by any java object after `fit` return. It will be automatically cleaned.

**Comment by zhengruifeng** [comment]
retest this please

**Review by srowen — APPROVED** [review]

**Comment by zhengruifeng** [comment]
@WeichenXu123 It maybe better to destory intermediate objects ASAP

**Comment by WeichenXu123** [comment]
OK I agree.

**Pull request closed without merging**
