### PR TITLE
[SPARK-5969][PySpark] Fix descending pyspark.rdd.sortByKey.

### PR DESCRIPTION
**Pull request by foxik**
The samples should always be sorted in ascending order, because bisect.bisect_left is used on it. The reverse order of the result is already achieved in rangePartitioner by reversing the found index.

The current implementation also work, but always uses only two partitions -- the first one and the last one (because the bisect_left return returns either "beginning" or "end" for a descending sequence).

### CODE REVIEW

**Comment by JoshRosen** [comment]
Could you add a regression test for this issue?  It looks like you have one in the JIRA ticket, so adding one hopefully should not be much work.  Take a look at `python/pyspark/tests.py` for examples of this.  Make sure to add a comment referencing the JIRA number.

**Comment by foxik** [comment]
I added the regression test. It also tests that sortByKey returns sorted sequence and tests also ascending sequence, which are not strictly necessary for SPARK-5969, but I added them anyway.

**Comment by JoshRosen** [comment]
Jenkins, this is ok to test.

**Comment by foxik** [comment]
I have amended the regression test commit to pass lint-python.

**Comment by JoshRosen** [comment]
@davies, does this look good to you?  Sorry for letting this patch fall off my radar (slowly getting caught up on a backlog of reviews).  If things look good, I can fix the merge conflict (which is probably just a conflict in tests) and get this committed.

**Comment by davies** [comment]
LGTM

**Comment by JoshRosen** [comment]
Alright, merging this into `master` (1.4.0) now.  Thanks!

**Comment by JoshRosen** [comment]
Should this be backported anywhere?

**Comment by davies** [comment]
This is a bug since the beginning (0.8), could we back port it for all 1.0+ branches?

**Comment by JoshRosen** [comment]
I've cherry-picked the fix into `branch-1.2` (1.2.3) and `branch-1.3` (1.3.2).  I'm going to omit the the pre-1.2 backports for now because I hit a test merge conflict and also because I think it's unlikely that we're going to release another 1.1.x version.

**Comment by davies** [comment]
Make sense, thank you!

**Pull request closed without merging**
