### PR TITLE
[SPARK-27591][SQL] Fix UnivocityParser for UserDefinedType

### PR DESCRIPTION
**Pull request by kalkolab**
## What changes were proposed in this pull request?

Fix bug in UnivocityParser. makeConverter method didn't work correctly for UsedDefinedType

## How was this patch tested?

A test suite for UnivocityParser has been extended.

### CODE REVIEW

**Comment by viirya** [comment]
Seems like your repo isn't updated to latest master branch? @kalkolab Can you sync with it?

**Comment by kalkolab** [comment]
yes, I'll sync

**Comment by kalkolab** [comment]
@viirya , fixed

**Comment by dongjoon-hyun** [comment]
ok to test

**Review by HyukjinKwon — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Hi, @HyukjinKwon . This bug fix is based on 2.2.0 code (SPARK-16101). Can we have this bug fix in `branch-2.4/2.3` too?

**Comment by HyukjinKwon** [comment]
UDT is intended to be previate as of SPARK-14155 as of Spark 2.0. And up to my knowledge all other exposed UDTs like VectorUDT are nested struct which CSV doesn't support. So, officially this code bit is intended to be a dead code.

I don't think we should backport into both branches but I don't mind if somebody does.

**Comment by dongjoon-hyun** [comment]
Got it, @HyukjinKwon .

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
