### PR TITLE
[SPARK-37993][SHUFFLE] Avoid multiple calls to configuration parameter values.

### PR DESCRIPTION
**Pull request by weixiuli**
### What changes were proposed in this pull request?
Avoid multiple calls to configuration parameter values.

### Why are the changes needed?
Improve performance.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Existed UT.

### CODE REVIEW

**Comment by weixiuli** [comment]
Friendly ping @srowen

**Comment by srowen** [comment]
Simple enough, but can this make a difference to perf?

**Comment by srowen** [comment]
If you have a case that this increases perf a tiny bit, are there other similar changes that would benefit?

**Comment by weixiuli** [comment]
@srowen Thanks. It may not benefit performance enough, but it can make the code cleaner.

**Comment by srowen** [comment]
I don't think this is worth it, just too small

**Pull request closed without merging**
