### PR TITLE
[SPARK-7202] [MLlib] [PySpark] Add SparseMatrixPickler to SerDe

### PR DESCRIPTION
**Pull request by MechCoder**
Utilities for pickling and unpickling SparseMatrices using SerDe

### CODE REVIEW

**Comment by MechCoder** [comment]
ping @jkbradley @mengxr

**Comment by MechCoder** [comment]
@jkbradley Should this be tagged to the 1.4 release?

**Comment by MechCoder** [comment]
@mengxr Can you please have a look at this? Thanks in advance! :)

**Comment by mengxr** [comment]
LGTM. Let's call Jenkins another time.

**Comment by MechCoder** [comment]
test this please

**Comment by MechCoder** [comment]
@mengxr I'm not sure what the test failure is about..

**Comment by MechCoder** [comment]
test this please

**Comment by MechCoder** [comment]
test this please

**Comment by mengxr** [comment]
Merged into master and branch-1.4. Thanks!

**Pull request closed without merging**
