### PR TITLE
[SPARK-26900][SQL] Simplify truncation to quarter of year

### PR DESCRIPTION
**Pull request by MaxGekk**
## What changes were proposed in this pull request?

In the PR, I propose to simplify timestamp truncation to quarter of year by using *java.time* API directly. The `LocalDate` instance can be truncation to quarter timestamp via adjusting by chrono field `IsoFields.DAY_OF_QUARTER`.  

## How was this patch tested?

This was checked by existing test suite - `DateTimeUtilsSuite`.

### CODE REVIEW

**Comment by MaxGekk** [comment]
@srowen @dongjoon-hyun @HyukjinKwon Please, take a look at the PR.

**Review by srowen — APPROVED** [review]
Looks good; this is covered by tests already?

**Comment by MaxGekk** [comment]
> ; this is covered by tests already?

There are a few tests:
https://github.com/apache/spark/blob/58e42cf50639d5b9d6c877b902ac559e132d041b/sql/catalyst/src/test/scala/org/apache/spark/sql/catalyst/util/DateTimeUtilsSuite.scala#L479-L481
https://github.com/apache/spark/blob/58e42cf50639d5b9d6c877b902ac559e132d041b/sql/catalyst/src/test/scala/org/apache/spark/sql/catalyst/util/DateTimeUtilsSuite.scala#L507-L509
https://github.com/apache/spark/blob/7c7fccfeb5bc079fede41eb64f57ab6b1b4b9018/sql/core/src/test/scala/org/apache/spark/sql/DateFunctionsSuite.scala#L485-L488
https://github.com/apache/spark/blob/64ce1c9f932b4acdf8f483265a628c124c9fd15d/sql/catalyst/src/test/scala/org/apache/spark/sql/catalyst/expressions/DateExpressionsSuite.scala#L637-L640

**Comment by HyukjinKwon** [comment]
I haven't checked super closely but looks fine to me too (given that it's covered by existing tests).

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
