### PR TITLE
[SPARK-9396] [yarn] Spark yarn allocator does not call "removeContainerRequest" for allocated Container requests, resulting in bloated ask[] toYarn RM.

### PR DESCRIPTION
**Pull request by prakhar-jauhari**
Spark-1.2 : Spark's AM does not call removeConatinerRequest for fulfilled container request.

As long as the cluster size is large enough to allocate the bloated container requests, containers are sent to spark yarn allocator in allocate response, spark yarn allocator uses missing number of container to launch new executors and release the extra allocated containers.

The problem increase in case of a long running job with large executor memory requirements. In this case when ever a executor gets killed, the next ask to yarn Resource manager (RM) is of n+1 containers, which might be served by the RM if it still has enough resources, else RM starts reserving cluster resources for a containers which are not even required by spark in the first place. This causes inefficient resource utilization of cluster resources.

I have added and tested changes for removing fulfilled container requests in spark 1.2 code. @vanzin can you please review the changes. Thanks in advance.

The contribution is original work and that I license the work to the project under the project's open source license.

### CODE REVIEW

**Comment by prakhar-jauhari** [comment]
Hey,

Please can some one verify this patch? 
@andrewor14 @sryza @vanzin  can you have a look at this.
Thanks in advance.

regards,
Prakhar

**Comment by andrewor14** [comment]
@prakhar-jauhari we generally don't merge patches into branch-1.2 anymore. Is this still an issue with the latest master branch? If so, would you mind opening the patch there instead?

**Comment by prakhar-jauhari** [comment]
@andrewor14 this is fixed in branch-1.3, we are using spark-1.2 and this issue caused other critical issues related to resource availability in yarn. Thus it seems a important issue to be patched in branch-1.2.

**Comment by srowen** [comment]
@prakhar-jauhari I think that 1.2 is very old in Spark-years, and I would be surprised if there is another 1.2.x release (even 1.3.x is iffy). Given the number of other fixes and improvements you should almost surely invest in upgrading.

**Comment by srowen** [comment]
@prakhar-jauhari do you mind closing this PR? this one would not be committed in any event given that it's only against 1.2.

**Comment by prakhar-jauhari** [comment]
As suggested by @andrewor14  and @srowen they are not merging patches in 1.2.x anymore. Thus i am closing this PR.

**Pull request closed without merging**
