### PR TITLE
[SPARK-12780] Inconsistency returning value of ML python models' properties

### PR DESCRIPTION
**Pull request by yinxusen**
https://issues.apache.org/jira/browse/SPARK-12780

### CODE REVIEW

**Comment by yinxusen** [comment]
test it please

**Comment by yinxusen** [comment]
retest this please

**Comment by yinxusen** [comment]
Something wrong with Jenkins?

**Comment by jkbradley** [comment]
A PR broke the build, but it should work now.

**Comment by jkbradley** [comment]
The feature.py changes look fine to me.

@davies Could you please glance at the serialization change to confirm it's OK?  Thanks!

**Comment by yinxusen** [comment]
@jkbradley @holdenk As I mentioned here https://github.com/apache/spark/pull/10186, we can work around the Ser/De issue with type conversion. So same solution here, I remove the Scala side code. But I still think there is a problem when ser/deing Scala Array. How about we merge this first then file another PR to fix it?

**Comment by yinxusen** [comment]
File a new JIRA https://issues.apache.org/jira/browse/SPARK-12834

**Comment by jkbradley** [comment]
@yinxusen I spoke with @davies and I think it would be best to use ```_call_java``` wherever possible for simplicity.  Otherwise, developers have to remember to put ```list()``` around the JVM methods they call.

Since you have created [https://github.com/apache/spark/pull/10772], let's use it to create the fix.  @davies said your original fix (in Scala in [https://github.com/yinxusen/spark/commit/c5a170da04f9941f4515f3263939bab9886c2c85]) seemed reasonable, so perhaps use that if your new one is not working.  After that gets merged, we can return to this and the other PRs.

**Comment by yinxusen** [comment]
retest it please

**Comment by yinxusen** [comment]
Hi @jkbradley, this is the follow-up PR of https://github.com/apache/spark/pull/10772, shall we merge it?

**Comment by jkbradley** [comment]
LGTM
I'll merge this with master
Thanks!

**Pull request closed without merging**
