### PR TITLE
[SPARK-42763][BUILD] Upgrade ZooKeeper from 3.6.3 to 3.6.4

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to upgrade `ZooKeeper` from 3.6.3 to 3.6.4.

### Why are the changes needed?
Release Notes: https://zookeeper.apache.org/doc/r3.6.4/releasenotes.html
Routine upgrade, ZooKeeper 3.6.4 contains some bugfixes:
image

Why is 3.6.4 but not higher?
https://github.com/apache/spark/pull/37507
https://github.com/apache/spark/pull/32572

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA.

### CODE REVIEW

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
Sorry but this is a duplicate of https://github.com/apache/spark/pull/40079 .

cc @bjornjorgensen

**Comment by dongjoon-hyun** [comment]
Let me close this in favor of the previous PR.

**Comment by panbingkun** [comment]
> Let me close this in favor of the previous PR.

Ok

**Comment by dongjoon-hyun** [comment]
To @panbingkun , you can search the JIRA or PR before making a PR in order to avoid unintentional duplication.

**Pull request closed without merging**
