### PR TITLE
[SPARK-32150][BUILD] Upgrade to ZStd 1.4.5-4

### PR DESCRIPTION
**Pull request by williamhyun**
### What changes were proposed in this pull request?

This PR aims to upgrade to ZStd 1.4.5-4. 

### Why are the changes needed?

ZStd 1.4.5-4 fixes the following. 

- https://github.com/luben/zstd-jni/commit/3d16e515253a0b6941810ab3ee4055201ca9ff54
- https://github.com/luben/zstd-jni/commit/3d51bdcb82c0003f943416cae7aba3f3001b1163
### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the Jenkins.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
ok to test

**Comment by dongjoon-hyun** [comment]
Retest this please

**Comment by maropu** [comment]
Looks okay to me. cc: @dongjoon-hyun @srowen

**Comment by srowen** [comment]
Looks OK to backport to 3.0.x right?

**Comment by maropu** [comment]
branch-3.0 still uses zstd v1.4.4 because we didn't merge the last zstd upgrade commit (https://github.com/apache/spark/pull/28682) into branch-3.0.

// zstd version in branch-3.0
https://github.com/apache/spark/blob/bdbfe6ec15667835000d7e95b0c437b6ab4b251e/pom.xml#L668

If there is no compatiblity issue and the fixes are somewhat critical, I think merging this into branch-3.0 looks fine.

**Comment by maropu** [comment]
retest this please

**Comment by maropu** [comment]
retest this please

**Review by HyukjinKwon — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by maropu** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by maropu** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by dongjoon-hyun** [comment]
Retest this please

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by maropu** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by maropu** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by maropu** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by dongjoon-hyun** [comment]
Retest this please

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by maropu** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by maropu** [comment]
retest this please

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
