### PR TITLE
[SPARK-18114][HOTFIX] Fix line-too-long style error from backport of SPARK-18114

### PR DESCRIPTION
**Pull request by srowen**
## What changes were proposed in this pull request?

Fix style error introduced in cherry-pick of https://github.com/apache/spark/pull/15643 to branch-2.0.

## How was this patch tested?

Existing tests

### CODE REVIEW

**Review by mridulm — APPROVED** [review]
Lgtm

**Comment by rxin** [comment]
Merging in branch-2.0. I'm waiting for this to cut rc2.

**Comment by srowen** [comment]
Yep, sorry for this right in the middle of RC time. The change itself should be a perfectly fine bug fix.

**Comment by rxin** [comment]
Can you close this?

**Pull request closed without merging**
