### PR TITLE
[SPARK-18511] Added the Api for join with only one column name and join type

### PR DESCRIPTION
**Pull request by shiv4nsh**
Added an api for join operations just on column name and the join type. An Api in which we do not have to provide the column sequences.

### CODE REVIEW

**Comment by srowen** [comment]
I don't think this buys much of anything over the method below. We don't need every possible overload here.

**Comment by shiv4nsh** [comment]
@srowen : This would help us write a much cleaner code , making sequence each and everytime makes our life difficult a little bit. This would allow us to write code in a more cleaner way. For example if we need to do left join on two tables using one field then we do not need to put it inside a sequence and then pass , now we can just pass directly.
Like this : `df1.join(df2,"commonFeild","left").show`

**Comment by srowen** [comment]
`Seq("commonField")` is much less clean that `"commonField"`?

**Comment by shiv4nsh** [comment]
Actually I was looking into the code and hence found Seq("commonFeild") in the code , but it was not making much sense as to why one should make it a sequence if only one column name is needed hence I thought this alias can be added. In my opinion , in a larger code base `"commonField"` can be taken as a little more cleaner than `Seq("commonField")` and hence the improvement !

**Comment by HyukjinKwon** [comment]
> We don't need every possible overload here.

+1

**Comment by srowen** [comment]
An API that takes 1 or more things takes a Seq of things, which possibly has 1 element. That doesn't seem confusing to me at all, or difficult. I would not like to make this change, please.

**Comment by shiv4nsh** [comment]
Okay @srowen , if you think so ! please go ahead and close this PR !

**Comment by srowen** [comment]
@shiv4nsh you will have to close this PR

**Pull request closed without merging**
