### PR TITLE
[SPARK-19676][CORE] Flaky test: FsHistoryProviderSuite.SPARK-3697: ignore directories that cannot be read.

### PR DESCRIPTION
**Pull request by uncleGen**
## What changes were proposed in this pull request?

Flaky test: FsHistoryProviderSuite.SPARK-3697: ignore directories that cannot be read.

-The root cause is the filestatus returned from `fs.listStatus()` in local has `rw-rw-rw` access permission, no matter what real access permission the file has.-

~~Before the pr, the debug detail likes:~~

~~`image`~~

~~but the real access permission of file is:~~

~~`image`~~

~~In this pr, we force to check the file access permission with `FileSystem.access()`. In `FileSystem.access()`, file access permission will be updated with real value, and in the same time throw `AccessControlException` if has no permission to access.~~

The root cause is I test it in root user, so it always be readable no matter what access permission. This pr introduce once extra access permission check, as the code scop is catching the AccessControlException. 

## How was this patch tested?

unit test pass locally

### CODE REVIEW

**Comment by uncleGen** [comment]
retest this please.

**Comment by srowen** [comment]
I don't quite see why it can succeed in listing a file that's not readable, later in mergeApplicationListing? won't that fail or generate an error already? Therefore I'm wondering if this is really the cause.

**Comment by vanzin** [comment]
Yes, this is pretty weird. Especially since I've never seen this test fail nor heard about anyone else having seen it fail. If you can point out in the Hadoop code where that discrepancy can occur, that would be better, because then you'd understand why it occurs, not just add a workaround that happens to work for you.

**Comment by uncleGen** [comment]
@srowen @vanzin I will test in some other platforms.

**Comment by uncleGen** [comment]
@srowen @vanzin I think the root cause is I test it in root user. So it always be readable no matter what access permission. IMHO, it is OK to add once extra access permission check, as the code scop is catching the AccessControlException. Maybe, I need to make the comment more clear. What's your opinion?

**Comment by vanzin** [comment]
Don't run things as root. Please close this PR.

**Pull request closed without merging**
