### PR TITLE
[SPARK-47481][INFRA][3.5] Fix Python linter

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to fix `python linter issue` on `branch-3.5` through pinning `matplotlib==3.7.2`

### Why are the changes needed?
Fix `python linter issue` on `branch-3.5`.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Hi, @panbingkun . Shall we rebase this to the master and merge to recover `branch-3.5`?

**Comment by panbingkun** [comment]
> Hi, @panbingkun . Shall we rebase this to the master and merge to recover `branch-3.5`?

Okay

**Comment by panbingkun** [comment]
> > Hi, @panbingkun . Shall we rebase this to the master and merge to recover `branch-3.5`?
> 
> Okay

Done.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by dongjoon-hyun** [comment]
Merged to branch-3.5. Thank you, @panbingkun .

**Pull request closed without merging**
