### PR TITLE
[SPARK-37586][SQL] Add the `mode` and `padding` args to `aes_encrypt()`/`aes_decrypt()`

### PR DESCRIPTION
**Pull request by MaxGekk**
### What changes were proposed in this pull request?
In the PR, I propose to add new optional arguments to the `aes_encrypt()` and `aes_decrypt()` functions with default values:
1. `mode` - specifies which block cipher mode should be used to encrypt/decrypt messages. Only one valid value is `ECB` at the moment.
2. `padding` - specifies how to pad messages whose length is not a multiple of the block size. Currently, only `PKCS` is supported.

In this way, when an user doesn't pass `mode`/`padding` to the functions, the functions apply AES encryption/decryption in the `ECB` mode with the `PKCS5Padding` padding.

### Why are the changes needed?
1. For now, `aes_encrypt()` and `aes_decrypt()` rely on the jvm's configuration regarding which cipher mode to support, this is problematic as it is not fixed across versions and systems. By using default constants for new arguments, we can guarantee the same behaviour across all supported platforms.
2. We can consider new arguments as new point of extension in the current implementation of AES algorithm in Spark SQL. In the future in OSS or in a private Spark fork, devs can implement other modes (and paddings) like GCM. Other systems have already supported different AES modes, see:
   1. Snowflake: https://docs.snowflake.com/en/sql-reference/functions/encrypt.html
   2. BigQuery: https://cloud.google.com/bigquery/docs/reference/standard-sql/aead-encryption-concepts#block_cipher_modes
   3. MySQL: https://dev.mysql.com/doc/refman/8.0/en/encryption-functions.html#function_aes-encrypt
   4. Hive: https://cwiki.apache.org/confluence/display/hive/languagemanual+udf
   5. PostgreSQL: https://www.postgresql.org/docs/12/pgcrypto.html#id-1.11.7.34.8 

### Does this PR introduce _any_ user-facing change?
No. This PR just extends existing APIs.

### How was this patch tested?
By running new checks:
```
$ build/sbt "test:testOnly org.apache.spark.sql.DataFrameFunctionsSuite"
$ build/sbt "sql/test:testOnly org.apache.spark.sql.expressions.ExpressionInfoSuite"
$ build/sbt "sql/testOnly *ExpressionsSchemaSuite"
```

### CODE REVIEW

**Comment by sarutak** [comment]
@MaxGekk Maybe, you need to rebase to `master`.
See https://github.com/apache/spark/commit/fdc276be98ea8d32d74e3248bbd6cfeeb74ef0d7

**Comment by sarutak** [comment]
There are no standard encryption/decryption functions in the popular RDBMS.
Actually, I brought these function from Hive, and Hive seems to have brought them from MySQL.
`aes_encrypt` and `aes_decrypt` in MySQL takes the 3rd optional parameter, which is IV.
https://dev.mysql.com/doc/refman/8.0/en/encryption-functions.html#function_aes-decrypt

So, how about taking IV as the 3rd parameter, and taking `mode` and `padding` as 4th and 5th for the compatibility?
cc: @HyukjinKwon @cloud-fan

**Comment by MaxGekk** [comment]
Let's introduce new argument when it will be really needed. So far, the PR solves this particular issue " ... aes_encrypt() and aes_decrypt() rely on the jvm's configuration regarding which cipher mode to support, this is problematic as it is not fixed across versions and systems."

**Comment by sarutak** [comment]
> So far, the PR solves this particular issue 

I understand this point. My main concern is the compatibility with MySQL's ones (especially, the order of the parameters).
But it's OK, I'll add the parameter for IV by the time of 3.3.0 release.

This change itself LGTM.

**Review by sarutak — APPROVED** [review]

**Comment by MaxGekk** [comment]
> My main concern is the compatibility with MySQL's ones ...

@sarutak I have looked at other dbms (see the PR's description). Seems like everyone has its own syntax. Not sure we should be compatible with MySQL in particular.

**Comment by HyukjinKwon** [comment]
But I guess Hive and MySQL have a similar syntax though assuming from the comments above. We can merge it as is for now but I also think it might be good to stick to one of these implementations. Not necessarily Hive or MySQL though.

Is IV argument difficult to implement? We can add it before Spark 3.3 release, and we're all good.

**Comment by sarutak** [comment]
> Seems like everyone has its own syntax. Not sure we should be compatible with MySQL in particular.

Yes, there is no standard syntax but the name `aes_encrypt` and `aes_decrypt` are apparently come from MySQL so users might expect the same usage.

**Review by HyukjinKwon — APPROVED** [review]
Took a cursory look, and seems good. Maybe we can consider adding IV param @sarutak mentioned in a separate ticket.

**Comment by sarutak** [comment]
Anyway, this change itself looks fine so merging to `master`.
Thank you @MaxGekk and @HyukjinKwon !

**Comment by MaxGekk** [comment]
Thank you, @sarutak . I am going to implement the GCM mode for now, opened the ticket https://issues.apache.org/jira/browse/SPARK-37591 for this.

**Pull request closed without merging**
