### PR TITLE
[SPARK-48822][DOCS] Add examples section header to `format_number` docstring

### PR DESCRIPTION
**Pull request by thomhart31**
### What changes were proposed in this pull request?
This PR adds and "Examples" section header to `format_number` docstring.

### Why are the changes needed?
To improve the documentation.

### Does this PR introduce any user-facing change?
No changes in behavior are introduced.

### How was this patch tested?
Existing tests.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Review by allisonwang-db — COMMENTED** [review]
Thanks for the fix. Could you please create a sub-jira ticket under https://issues.apache.org/jira/browse/SPARK-44728?

**Comment by thomhart31** [comment]
@allisonwang-db Thanks! sub-jira ticket create [here](https://issues.apache.org/jira/browse/SPARK-48822)

**Review by allisonwang-db — APPROVED** [review]

**Comment by zhengruifeng** [comment]
@thomhart31 would you mind enable the github action https://github.com/apache/spark/pull/47237/checks?check_run_id=27093619122 ?

**Comment by zhengruifeng** [comment]
@thomhart31 python linter fails with 
```
black checks failed:
would reformat /__w/spark/spark/python/pyspark/sql/functions/builtin.py

Oh no! 💥 💔 💥
1 file would be reformatted, 1040 files would be left unchanged.
Please run 'dev/reformat-python' script.
```

**Comment by zhengruifeng** [comment]
thanks, merged to master

**Pull request closed without merging**
