### PR TITLE
[SPARK-44670][PYTHON][TESTS][PS][3.4] Fix 'test_dataframe_conversion.DataFrameConversionTest.get_excel_dfs'  test to work with Python 3.7

### PR DESCRIPTION
**Pull request by Madhukar98**
### What changes were proposed in this pull request?

The fix is to use openpyxl by default instead of xlrd.

### Why are the changes needed?

test_to_excel test case was failing in python3.7, asking for xlrd which is unable to read xlsx files. Improves test coverage.

### Does this PR introduce _any_ user-facing change?

No, it's test only

### How was this patch tested?

Manually

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]
LGTM cc @itholic

**Comment by HyukjinKwon** [comment]
cc @xinrong-meng too

**Review by itholic — APPROVED** [review]

**Comment by srowen** [comment]
Do we need this change in master too?

**Comment by Madhukar98** [comment]
Hi @srowen as per my understanding, it will only be required in master if we have python3.7 and 3.8 support, as xlrd will not work in Python 3.9 or newer versions, so it by default takes openpyxl.

**Comment by HyukjinKwon** [comment]
Yeah, we dropped Python 3.7 in branch-3.5 so we don;t need it.

**Comment by HyukjinKwon** [comment]
Merged to branch-3.4.

**Pull request closed without merging**
