### PR TITLE
[SPARK-49461][SS][TESTS][FOLLOWUP] Move related resource files to correct place

### PR DESCRIPTION
**Pull request by WweiL**
### What changes were proposed in this pull request?

I created a new resource location `sql/core/src/test/{scala/org/apache/spark/sql/streaming/resources` before, moving it to the correct structured-streaming resource folder.

### Why are the changes needed?

Better code structure

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Unit test

### Was this patch authored or co-authored using generative AI tooling?

No

### CODE REVIEW

**Review by HeartSaVioR — APPROVED** [review]
+1 pending CI

**Comment by HeartSaVioR** [comment]
@WweiL Shall we rerun the CI? Looks like the relevant module had failed. I guess it's not relevant, but since it's timed out and some tests may not even run...

**Comment by WweiL** [comment]
@HeartSaVioR The tests now pass : )

**Comment by HeartSaVioR** [comment]
Thanks! Merging to master.

**Pull request closed without merging**
