### PR TITLE
[SPARK-42870][CONNECT] Move `toCatalystValue` to `connect-common`

### PR DESCRIPTION
**Pull request by zhengruifeng**
### What changes were proposed in this pull request?
Move `toCatalystValue` to connect-common

### Why are the changes needed?
ml support for SCSC also needs this, see https://github.com/apache/spark/pull/40479/files#r1141524125, so we'd better move it to the `connect-common`

### Does this PR introduce _any_ user-facing change?
no, dev-only

### How was this patch tested?
existing UT

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]

**Comment by LuciferYang** [comment]
also cc @beliefer , https://github.com/apache/spark/pull/40355 maybe need rebase after this one

**Review by LuciferYang — APPROVED** [review]
+1, LGTM

**Review by WeichenXu123 — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by amaliujia** [comment]
late LGTM

**Pull request closed without merging**
