### PR TITLE
[SPARK-20039][ML] rename ChiSquare to ChiSquareTest

### PR DESCRIPTION
**Pull request by jkbradley**
## What changes were proposed in this pull request?

I realized that since ChiSquare is in the package stat, it's pretty unclear if it's the hypothesis test, distribution, or what. This PR renames it to ChiSquareTest to clarify this.

## How was this patch tested?

Existing unit tests

### CODE REVIEW

**Comment by jkbradley** [comment]
CC @thunterdb @imatiach-msft What do you think?

**Review by srowen — COMMENTED** [review]
Just double checking, this was never released under the current name so this doesn't break user code?

**Comment by imatiach-msft** [comment]
LGTM!

**Review by imatiach-msft — APPROVED** [review]

**Comment by imatiach-msft** [comment]
@srowen yes, this was never released, so it shouldn't break user code :)

**Comment by MLnick** [comment]
LGTM

**Comment by jkbradley** [comment]
Yep, thanks for confirming that @srowen  and checking it out @imatiach-msft and @MLnick !

Merging with master

**Pull request closed without merging**
