### PR TITLE
[SPARK-12098] Cross validator with multi-arm bandit search

### PR DESCRIPTION
**Pull request by yinxusen**
https://issues.apache.org/jira/browse/SPARK-12098

The classic cross-validation requires all inner classifiers iterate to a fixed number of iterations, or until convergence states. It is costly especially in the massive data scenario. According to the paper [Non-stochastic Best Arm Identification and Hyperparameter Optimization](http://arxiv.org/pdf/1502.07943v1.pdf), we can see a promising way to reduce the amount of total iterations of cross-validation with multi-armed bandit search.

The multi-armed bandit search for cross-validation (bandit search for short) requires warm-start of ml algorithms, and fine-grained control of the inner behavior of the corss validator.

Since there are bunch of algorithms of bandit search to find the best parameter set, we intent to provide only a few of them in the beginning to reduce the test/perf-test work and make it more stable.

Here we only provide StaticSearch and ExponentialWeightsSearch (See chapter 3 of the [Regret Analysis of Stochastic and Nonstochastic Multi-armed Bandit Problems](http://arxiv.org/abs/1204.5721)) in the version. More search strategies and perf-test please see https://github.com/yinxusen/spark/tree/bandit.

### CODE REVIEW

**Comment by yinxusen** [comment]
The error is caused by my modification in `LogisticRegression`. I add `Controllable` to it without implementing the save/load for new params.

However, this is not the right place to add those functionalities here, I plan to add warm-start to estimators in other JIRA issue. Then go back and fix the error here.

**Comment by jkbradley** [comment]
@yinxusen I just commented on the JIRA about this, but could we please close this issue for now?  I'd like to postpone this feature due to limited review bandwidth.  But definitely post it as a Spark package, and see if you can get some feedback from users.  Thanks very much.

**Comment by yinxusen** [comment]
@jkbradley Get it and close it.

**Comment by yinxusen** [comment]
Close it for more feedbacks.

**Pull request closed without merging**
