### PR TITLE
[SPARK-10759][ML] update cross validator with include_example

### PR DESCRIPTION
**Pull request by JeremyNixon**
This pull request uses {%include_example%} to add an example for the python cross validator to ml-guide.

### CODE REVIEW

**Comment by mengxr** [comment]
ok to test

**Comment by mengxr** [comment]
cc @yinxusen

**Comment by yinxusen** [comment]
@mengxr LGTM

**Comment by JeremyNixon** [comment]
@mengxr @yinxusen I made an update to an error in the train-validation-split example, it's currently pointing to the wrong data (was overwritten by https://issues.apache.org/jira/browse/SPARK-13012). Let me know if you'd prefer I create a new JIRA.

**Comment by yinxusen** [comment]
@JeremyNixon There is no need to fix those two examples. Actually we have duplicated example code now - JavaModelSelectionViaTrainValidationSplitExample VS JavaTrainValidationSplitExample, etc. We prepare to remove the duplicated JavaTrainValidationSplitExample later under JIRA https://issues.apache.org/jira/browse/SPARK-13461

**Comment by JeremyNixon** [comment]
@yinxusen Great to hear, this PR should be good to go.

**Comment by mengxr** [comment]
Merged into master. Thanks!

**Comment by JeremyNixon** [comment]
@mengxr My pleasure!

**Pull request closed without merging**
