### PR TITLE
[SPARK-26499][SQL][FOLLOW-UP] Replace `update` with `setByte` for ByteType in JdbcUtils.makeGetter

### PR DESCRIPTION
**Pull request by maropu**
### What changes were proposed in this pull request?

This is a follow-up pr to fix the code coming from #23400; it replaces `update` with `setByte` for ByteType in `JdbcUtils.makeGetter`.

### Why are the changes needed?

For better code.

### Does this PR introduce any user-facing change?

No.

### How was this patch tested?

Existing tests.

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by maropu** [comment]
retest this please

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
The test cases should be fixed as of https://github.com/apache/spark/commit/65a189c7a1ddceb8ab482ccc60af5350b8da5ea5

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by maropu** [comment]
Oh, nice! Thanks for the re-trigger.

**Comment by srowen** [comment]
Merged to master/2.4

**Pull request closed without merging**
