### PR TITLE
Added import for Spark Context

### PR DESCRIPTION
**Pull request by ChetanBhasin**
Added import for Spark Context so that methods such as reduceByKey may work.

### CODE REVIEW

**Comment by srowen** [comment]
Hm, but it already compiles right? You do not need these imports.

**Comment by ChetanBhasin** [comment]
Actually no, it doesn't. This is what I got when I tried it without imports:

    /mllib/fpm/FPGrowth.scala:131: value reduceByKey is not a member of org.apache.spark.rdd.RDD[(Item, Long)]
    [error] possible cause: maybe a semicolon is missing before `value reduceByKey'?
    [error]       reduceByKey(partitioner, _ + _).

**Comment by srowen** [comment]
The code plainly compiles in master, as you can see from Jenkins builds. What are you compiling?

**Comment by ChetanBhasin** [comment]
Oh! I see. I might have messed up a few files between different versions on my end.

I'll recheck the code on my end. Sorry for the useless request.

**Comment by srowen** [comment]
OK. Mind closing this PR?

**Comment by ChetanBhasin** [comment]
Right away.

**Pull request closed without merging**
