### PR TITLE
[SPARK-41113][BUILD] Upgrade sbt to 1.8.0

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr aims to upgrade sbt from 1.7.3 to 1.8.0

### Why are the changes needed?
This version fix 2 CVE:

- Updates to Coursier 2.1.0-RC1 to address https://github.com/advisories/GHSA-wv7w-rj2x-556x
- Updates to Ivy 2.3.0-sbt-a8f9eb5bf09d0539ea3658a2c2d4e09755b5133e to address https://github.com/advisories/GHSA-wv7w-rj2x-556x

The full release notes as follows:

- https://github.com/sbt/sbt/releases/tag/v1.8.0 

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?

- Pass GitHub Actions
- Run ` dev/sbt-checkstyle` passed

### CODE REVIEW

**Comment by LuciferYang** [comment]
test first

**Review by dongjoon-hyun — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
cc @HyukjinKwon

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
cc @linhongliu-db too

**Comment by LuciferYang** [comment]
@LinhongLiu Please help double check. Thanks ~

 I don't know what you need. I just checked `dev/sbt-checkstyle` manually

**Comment by dongjoon-hyun** [comment]
That will be enough, @LuciferYang .

Thank you, @LuciferYang and @HyukjinKwon . Merged to master.

**Comment by LuciferYang** [comment]
Thanks @dongjoon-hyun @HyukjinKwon

**Pull request closed without merging**
