### PR TITLE
[SPARK-40703][SQL] Introduce shuffle on SinglePartition to improve parallelism

### PR DESCRIPTION
**Pull request by sunchao**
### What changes were proposed in this pull request?

This PR fixes a performance regression issue when one side of a join uses `HashPartitioning` with `ShuffleExchange` while the other side uses `SinglePartition`. In this case, Spark will re-shuffle the side with `HashPartitioning` and both sides will end up with only a single partition. This could hurt query performance a lot if the side with `HashPartitioning` contains a lot of input data.

### Why are the changes needed?

After SPARK-35703, when Spark sees that one side of the join has `ShuffleExchange` (meaning it needs to be shuffled anyways), and the other side doesn't, it'll try to avoid shuffling the side without `ShuffleExchange`. For instance:

```
ShuffleExchange(HashPartition(200)) <-> HashPartition(150)
```

will be converted into
```
ShuffleExchange(HashPartition(150)) <-> HashPartition(150)
```

However, when the side without `ShuffleExchange` is `SinglePartition`, like the following:
```
ShuffleExchange(HashPartition(150)) <-> SinglePartition
```

Spark will also do the same which causes the left-hand side to only use one partition. This can hurt job parallelism dramatically, especially when using DataSource V2, since `SinglePartition` is used by the V2 scan. On the other hand, it seems DataSource V1 won't be impacted much as it always report `UnknownPartitioning` in this situation.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Added new unit tests in `EnsureRequirementsSuite`.

### CODE REVIEW

**Review by bryanck — APPROVED** [review]
I ran a few tests and this fixes the issue I was seeing.

**Comment by zhengruifeng** [comment]
Looks reasonable to me

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Review by huaxingao — APPROVED** [review]

**Review by viirya — APPROVED** [review]

**Review by c21 — APPROVED** [review]

**Review by wangyum — APPROVED** [review]

**Comment by wangyum** [comment]
Merged to master and branch-3.3

**Comment by sunchao** [comment]
Thanks @wangyum @bryanck @zhengruifeng @dongjoon-hyun @huaxingao @viirya @c21 !

**Pull request closed without merging**
