### PR TITLE
[SQL][SPARK-4226]: Add support for subqueries in where in clause

### PR DESCRIPTION
**Pull request by saucam**
this PR adds support for subquery in where in clause by adding a dynamic filter class that will compute the values list from the subquery first and then create a hash-set , using it as input to inset class.

### CODE REVIEW

**Comment by saucam** [comment]
Hi, @marmbrus can you please take a look and suggest changes ; Have tested for a few queries and this approach looks simpler than an already existing PR.

**Comment by rxin** [comment]
Jenkins, test this please.

**Comment by marmbrus** [comment]
This is simpler, but it has several disadvantages to the other approach:
 - The InSet it collected to the driver and thus could cause OOMs when large
 - I don't think that it handles correlated subqueries
 - The `execute()` involves eager evaluation and breaks RDD lineage

For these reasons I think we should stick to extending the approach taken by the other PR.

**Comment by saucam** [comment]
Hi Michael, 

Thanks for the feedback.

1. Yes it does not handle correlated queries. It definitely makes more sense to convert correlated queries to joins, 
but for uncorrelated queries, i think its too slow if table size is large and user is querying on smaller data:

eg: 2 tables with ~ 45 million rows each ; subquery returns only 90 rows:
  
select * from Y1 where Y1.id in (select Y2.id from Y2 where Y2.id < 90);

takes about 12 seconds to run by this approach on a single machine (--executor-memory 16G --driver-memory 8G)

by following the join approach, query is changed to : 

select * from Y1 left semi join (select Y2.id as sqc0 from Y2 where id < 90) subquery on Y1.id = subquery.sqc0;

which takes 660 seconds to run on the same machine

2. This approach can handle arbitrary nesting of subqueries : 

select * from Y1 where Y1.id in (select Y2.id where Y2.timestamp in (select Y3.timestamp limit 20))

Can we take some hybrid approach from the two ?

**Comment by marmbrus** [comment]
The problem with a hybrid approach is: how do you choose between them?  If we had good statistics I would agree with you that we should use those to decide.  However, we don't at this point.  Given that, I think a safe option that may be slower but never OOMs the driver is better than aiming for optimal performance in the small data cases.

Also, were you testing with broadcast left semi join enabled and statistics for your tables?  Avoiding a shuffle there might speed things up.

**Comment by marmbrus** [comment]
Also if we use statistics we would still need to figure out how to make the calculation lazy.

**Comment by saucam** [comment]
Can we have some kind of hint mechanism in the query itself , if the user knows the subquery is small ? Then perhaps we can change the plan accordingly ?

**Comment by sryza** [comment]
@saucam if this is going to stay open, mind tagging it with [SQL] so it gets sorted properly?

**Comment by marmbrus** [comment]
@saucam, thanks for working on this and sorry for the delay due to the 1.3 release.  I think the best option here is to use statistics and only collect when we know the size is going to be pretty small.  It would also be good to reconcile it with the other options for handling exist queries when the statistics suggest the other table is large.  Finally, we'll need a bunch of tests for this new feature.  Until you have time to update, I suggest we close this issue to keep the PR queue small and manageable.

**Comment by saucam** [comment]
hey @marmbrus , thanks for the feedback, i'll close this one and work on another PR , incorporating the changes you have suggested.

**Pull request closed without merging**
