### PR TITLE
[SPARK-29186][SQL][2.4][Followup] AliasIdentifier should be converted to Json in prettyJson

### PR DESCRIPTION
**Pull request by viirya**
### What changes were proposed in this pull request?

This is a follow-up to #25959. There is import inconsistency between master and 2.4 in TreeNodeSuite, so the automatic backport misses the import of SubqueryAlias.

### Why are the changes needed?

Without this, branch-2.4 can't be compiled.

### Does this PR introduce any user-facing change?

Yes. Fixed compilation error.

### How was this patch tested?

Manual test.

### CODE REVIEW

**Comment by viirya** [comment]
cc @HyukjinKwon @dongjoon-hyun

**Review by dongjoon-hyun — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
It was a compilation error, and now GitHub Action looks good. I'll merge this to branch-2.4.

**Comment by viirya** [comment]
Thanks @dongjoon-hyun

**Comment by dongjoon-hyun** [comment]
No problem~

**Pull request closed without merging**
