### PR TITLE
[SPARK-30784] Use ORC nohive 

### PR DESCRIPTION
**Pull request by yhuai**
### What changes were proposed in this pull request?
This PR sets orc's classifier to nohive, which has shaded hive-storage-api.

### Why are the changes needed?

Right now, Hive 2.3 profile pulls in regular orc, which depends on hive-storage-api. However, hive-storage-api and hive-common have the following common class files

```
org/apache/hadoop/hive/common/ValidReadTxnList.class
org/apache/hadoop/hive/common/ValidTxnList.class
org/apache/hadoop/hive/common/ValidTxnList$RangeResponse.class
```

For example, https://github.com/apache/hive/blob/rel/storage-release-2.6.0/storage-api/src/java/org/apache/hadoop/hive/common/ValidReadTxnList.java (pulled in by orc 1.5.8) and https://github.com/apache/hive/blob/rel/release-2.3.6/common/src/java/org/apache/hadoop/hive/common/ValidReadTxnList.java (from hive-common 2.3.6) both are in the classpath and they are different. Having both versions in the classpath can cause unexpected behavior due to classloading order. We should still use orc-nohive, which has hive-storage-api shaded.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @wangyum

**Comment by dongjoon-hyun** [comment]
Hi, @yhuai . Thank you for making a PR. Could you fix the UT failures?

**Comment by yhuai** [comment]
oh hive-storage-api still gets pulled in. Let me check.

**Comment by yhuai** [comment]
hmm. We need to keep hive-storage-api. But I will need to check why we hit the runtime exception. Somehow we used hive-storage-api's VectorizedRowBatch instead of orc's VectorizedRowBatch for orc code path.

**Comment by yhuai** [comment]
Also, the error cause was
```
Caused by: sbt.ForkMain$ForkError: java.lang.NoSuchMethodError: org.apache.orc.TypeDescription.createRowBatch(I)Lorg/apache/hadoop/hive/ql/exec/vector/VectorizedRowBatch;
	at org.apache.hadoop.hive.ql.io.orc.WriterImpl.<init>(WriterImpl.java:96)
	at org.apache.hadoop.hive.ql.io.orc.OrcFile.createWriter(OrcFile.java:320)
	at org.apache.hadoop.hive.ql.io.orc.OrcOutputFormat$OrcRecordWriter.write(OrcOutputFormat.java:103)
	at org.apache.spark.sql.hive.execution.HiveOutputWriter.write(HiveFileFormat.scala:156)
	at org.apache.spark.sql.execution.datasources.SingleDirectoryDataWriter.write(FileFormatDataWriter.scala:140)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.$anonfun$executeTask$1(FileFormatWriter.scala:273)
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1411)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.executeTask(FileFormatWriter.scala:281)
	... 9 more
```

Seems org.apache.hadoop.hive.ql.io.orc.WriterImpl was hive's orc.

**Comment by yhuai** [comment]
taking https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/118207/testReport/org.apache.spark.sql.hive/CompressionCodecSuite/both_table_level_and_session_level_compression_are_set/ as an example, I am not getting why the table was turned to a hive orc table.

**Comment by xuanyuanking** [comment]
retest this please

**Comment by yhuai** [comment]
@dongjoon-hyun @wangyum do you happen to know what happened with https://github.com/apache/spark/pull/27536#issuecomment-585042303? Seems in hive module, we are sending orc project created VectorizedRowBatch to hive's orc data source instead of the data source file inside orc project.

**Comment by dongjoon-hyun** [comment]
Not yet, @yhuai . Let me check that tonight and during weekend. I didn't dig that deeper until now. I'll ping here if I got something.

**Comment by yhuai** [comment]
thank you @dongjoon-hyun !

**Comment by wangyum** [comment]
Hi @omalley. Is the nohive variant compatible with Hive 2.3?  https://issues.apache.org/jira/browse/ORC-174

**Comment by wangyum** [comment]
I personally think it is incompatible, I have tried it many times before.
@yhuai How about replace our `hive-thriftserver` with [another thriftserver that does not depend on Hive](https://github.com/spark-thriftserver/spark-thriftserver/tree/master/sql/service). After that, we can easily upgrade the built-in Hive to Hive 3.x to workaround the conflict issue.

**Comment by dongjoon-hyun** [comment]
@wangyum . `hive-thriftserver` is irrelevant to `hive` module failures, e.g., `org.apache.spark.sql.hive.CompressionCodecSuite`, isn't it?

**Review by dongjoon-hyun — COMMENTED** [review]
Hi, @yhuai . I took a look at the failure and the related code in Spark/Orc/Hive. The current `sql/hive` module failures are mainly due to the following difference.

1. Hive 1.2 ~ 2.x use the embedded ORC like `org.apache.hive.orc.TypeDescription`
2. Hive 2.3 uses Apache ORC like `org.apache.orc.TypeDescription`. (Note that the package name is different)
```
$ javap -cp orc-core-1.5.9.jar org.apache.orc.TypeDescription | grep "createRowBatch(int)"
  public org.apache.hadoop.hive.ql.exec.vector.VectorizedRowBatch createRowBatch(int);
```
3. ORC nohive library has the following. (Note that the return type is different)
```
$ javap -cp orc-core-1.5.9-nohive.jar org.apache.orc.TypeDescription | grep "createRowBatch(int)"
  public org.apache.orc.storage.ql.exec.vector.VectorizedRowBatch createRowBatch(int);
```

As we know, `orc:nohive` is for no-hive environment like `sql/core`. As a result, all ORC tests in `sql/core` passes always. However, along with that, `orc:nohive` doesn't aim to support `Hive` code itself. Hive code needs the original `orc` library. I believe that this was the original technical difficulty which @wangyum and @gatorsmile tried to fix in https://github.com/apache/spark/pull/23788 .

**Comment by yhuai** [comment]
@dongjoon-hyun thank you for looking into it. How did sql/hive work with hive 1.2 and orc nohive? Does sql/hive also use hive's orc when hive 1.2 was used?

**Comment by dongjoon-hyun** [comment]
Yes. Right. `Hive 1.2` exists before `Apache ORC` and has all ORC related stuff as a embedded manner like `org.apache.hive.orc.TypeDescription`.

**Comment by yhuai** [comment]
@dongjoon-hyun So, hive 2.3 depends on apache orc instead of using orc embedded in hive, which means we will need to pull in regular orc instead of orc-nohive. Is my understanding correct?

**Comment by dongjoon-hyun** [comment]
The current failure analysis is due to the following.

For pulling regular ORC here, cc @wangyum and @gatorsmile for the reasoning of the original PR.

**Comment by omalley** [comment]
Sorry for being late to the thread. Yes, now that Spark depends on Hive >= 2.3, we should move away from the nohive variant and share the same ORC release.

**Comment by yhuai** [comment]
thank you @omalley and @dongjoon-hyun!

btw, are we concerned that hive-common shipped with hive 2.3.6 and hive-storage-api 2.6.0 used by orc 1.5.9 share duplicate classes that have different versions? I am worried that we may not consistently pick up the right version due to class loading order, which can cause confusing runtime exception.

**Comment by yhuai** [comment]
Closing it as we need to use regular orc

**Pull request closed without merging**
