### PR TITLE
[SPARK-36374][FOLLOW-UP] Change config key spark.shuffle.server.mergedShuffleFileManagerImpl to spark.shuffle.push.server.mergedShuffleFileManagerImpl

### PR DESCRIPTION
**Pull request by venkata91**
### What changes were proposed in this pull request?

Minor changes to change the config key name from `spark.shuffle.server.mergedShuffleFileManagerImpl` to `spark.shuffle.push.server.mergedShuffleFileManagerImpl`. This is missed out in https://github.com/apache/spark/pull/33615.

### Why are the changes needed?

To keep the config names consistent

### Does this PR introduce _any_ user-facing change?

Yes, this is a change in the config key name. But the new config name changes are yet to be released. Technically there is no user facing change because of this change.

### How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by venkata91** [comment]
cc @mridulm @Ngone51 I missed to change one of the config key to use `spark.shuffle.push.server.mergedShuffleFileManagerImpl`. Sorry about that.

**Comment by mridulm** [comment]
Ok to test

**Review by mridulm — APPROVED** [review]

**Comment by mridulm** [comment]
+CC @gengliangwang, @Ngone51

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
We should technically wait for RC 1 to fail before merging .... although typically RC1 would very very likely fail .. :-).

**Comment by mridulm** [comment]
RC.1 does not include #33790, which results in test failure - so it will unfortunately fail.

**Comment by mridulm** [comment]
Merged to master and branch-3.2
+CC @gengliangwang 

Thanks for fixing this @venkata91 !
Thanks for the review @HyukjinKwon :-)

**Comment by gengliangwang** [comment]
Late +1

**Pull request closed without merging**
