### PR TITLE
[SPARK-21155][WEBUI] Add (? running tasks) into Spark UI progress

### PR DESCRIPTION
**Pull request by ericvandenbergfb-zz**
## What changes were proposed in this pull request?

Add metric on number of running tasks to status bar on Jobs / Active Jobs.

## How was this patch tested?

Run a long running (1 minute) query in spark-shell and use localhost:4040 web UI to observe progress.  See jira for screen snapshot.

### CODE REVIEW

**Comment by ajbozarth** [comment]
could you please include before and after screen shots of the UI change

**Comment by ericvandenbergfb** [comment]
before:
screen shot 2017-06-20 at 3 40 39 pm

after:
screen shot 2017-06-20 at 12 32 58 pm

**Comment by ajbozarth** [comment]
Thanks, could you get a shot where there're both running and failed or skipped, I'm a bit worried if all three shoe up it'll look off. Otherwise I'm ok with this add.

**Comment by ericvandenbergfb** [comment]
screen shot 2017-06-22 at 9 58 08 am

Good point, modified to only show runningTasks if no skipped or failed tasks.

**Comment by jiangxb1987** [comment]
LGTM

**Comment by jiangxb1987** [comment]
ok to test

**Comment by jiangxb1987** [comment]
ok to test

**Comment by cloud-fan** [comment]
ok to test

**Comment by cloud-fan** [comment]
LGTM

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Pull request closed without merging**
