### PR TITLE
[SPARK-14613][ML] Add @Since into the matrix and vector classes in spark-mllib-local

### PR DESCRIPTION
**Pull request by pravingadakh**
## What changes were proposed in this pull request?

This PR add `@Since` annotations in `Vectors.scala` and `Matrices.scala` of spark-mllib-local.
## How was this patch tested?

Scala Style Checks.

### CODE REVIEW

**Comment by pravingadakh** [comment]
cc @dbtsai

**Comment by dbtsai** [comment]
Test this please

**Comment by srowen** [comment]
Jenkins test this please

**Comment by dbtsai** [comment]
Thanks. Merged into master and 2.0 branch.

**Pull request closed without merging**
