### PR TITLE
[SPARK-46733][CORE] Simplify the BlockManager by the exit operation only depend on interrupt thread.

### PR DESCRIPTION
**Pull request by beliefer**
### What changes were proposed in this pull request?
This PR propose to simplify the `BlockManager`.

### Why are the changes needed?
Currently, close or destroy `BlockManager` depend on interrupt thread and the volatile variable `stopped`.
In fact, we can change the `stopped` to a local variable on stack and let the close operation of `BlockManager` only depend on interrupt thread.
For further optimization, this PR using `running` instead of `stopped`.

### Does this PR introduce _any_ user-facing change?
'No'.

### How was this patch tested?
GA tests.

### Was this patch authored or co-authored using generative AI tooling?
'No'.

### CODE REVIEW

**Review by mridulm — COMMENTED** [review]
Unlike `ReloadingX509TrustManager `, here the `InterruptedException` is caught and ignored in some of the downstream methods: so we cant rely on that pattern here.

**Comment by beliefer** [comment]
> Unlike `ReloadingX509TrustManager `, here the `InterruptedException` is caught and ignored in some of the downstream methods: so we cant rely on that pattern here.

`ContextCleaner` catches `InterruptedException` but ignore it. How can downstream capture it?

**Comment by beliefer** [comment]
> Unlike `ReloadingX509TrustManager `, here the `InterruptedException` is caught and ignored in some of the downstream methods: so we cant rely on that pattern here.

I reverted the `ContextCleaner`.

**Review by mridulm — COMMENTED** [review]
Looks reasonable to me.
+CC @dongjoon-hyun as well who reviewed the prev pr.

**Comment by beliefer** [comment]
@dongjoon-hyun @srowen @LuciferYang

**Comment by LuciferYang** [comment]
This change of this pr is fine to me. 

However, I would like to raise a question: Would it be simpler and clearer to implement the logic for cleaning up the `DownloadFile` resource using the `java.lang.ref.Cleaner` mechanism instead of the current approach?

**Comment by beliefer** [comment]
`Java.lang.ref.Cleaner` cannot respond to interrupts.

**Comment by beliefer** [comment]
cc @mridulm 
Could you take a review again?

**Comment by mridulm** [comment]
Since you looked into this - do you have any other thoughts on this @LuciferYang ? Thanks

**Comment by LuciferYang** [comment]
no more, the change is fine to me

**Review by mridulm — APPROVED** [review]
LGTM

**Comment by mridulm** [comment]
Merged to master.
Thanks for working on this @beliefer !
Thanks for the review @LuciferYang :-)

**Comment by beliefer** [comment]
@mridulm @LuciferYang Thank you!

**Pull request closed without merging**
