### PR TITLE
[SPARK-5790][GraphX]: VertexRDD's won't zip properly for `diff` capability (added tests)

### PR DESCRIPTION
**Pull request by brennonyork**
Added tests that @maropu [created](https://github.com/maropu/spark/blob/1f64794b2ce33e64f340e383d4e8a60639a7eb4b/graphx/src/test/scala/org/apache/spark/graphx/VertexRDDSuite.scala) for vertices with differing partition counts. Wanted to make sure his work got captured /merged as its not in the master branch and I don't believe there's a PR out already for it.

### CODE REVIEW

**Comment by srowen** [comment]
OK, is the idea that these are tests that pass, that should be included, or tests that fail and demonstrate a problem? Jenkins will tell us soon.

**Comment by srowen** [comment]
OK to merge, since tests are good. Does this mean SPARK-5790 is essentially resolved by this? sounds like it was fixed separately, and this is about getting in additional tests created by the parallel effort to address this.

**Comment by brennonyork** [comment]
Sorry @srowen I should've been more clear, but yes you're correct. SPARK-5790 ended up duplicating most effort from SPARK-1955, PR #4705, but @maropu had created tests with his that I hadn't included. Wanted to make sure those were captured and, since SPARK-5790 wasn't closed, thought it best to include those here. Does that make sense? Sorry about the confusion!

**Pull request closed without merging**
