### PR TITLE
[MINOR][DOCS] Remove consecutive duplicated words/typo in Spark Repo 

### PR DESCRIPTION
**Pull request by neurons**
## What changes were proposed in this pull request?
There are many locations in the Spark repo where the same word occurs consecutively. Sometimes they are appropriately placed, but many times they are not. This PR removes the inappropriately duplicated words.

## How was this patch tested?
N/A since only docs or comments were updated.

### CODE REVIEW

**Comment by neurons** [comment]
@tdas could you accept this small PR?

**Comment by srowen** [comment]
Better idea: grep for all instances of repeated words and fix more than just this in one go. I actually see quite a few. This is a quick and dirty grep that shows most of them `grep -rE "[^m] ([a-zA-Z]+) \1 " * | grep -E "\.(md|scala|java):"`

**Comment by neurons** [comment]
@srowen -- indeed, better; thanks for the suggestion. I also ran this command: `grep -rE "[^m] \b(\w+)\s+\1\b" * | grep -E "\.(md|scala|java|py):"` and removed some duplicates not caught by your regex search.

**Comment by felixcheung** [comment]
whoa. LGTM.

**Review by srowen — APPROVED** [review]

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
