### PR TITLE
[SPARK-49624][BUILD] Upgrade `aircompressor` to 2.0.2

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to upgrade `aircompressor` from `0.27` to `2.0.2`.

### Why are the changes needed?
https://github.com/airlift/aircompressor/releases/tag/2.0
(ps: 2.0.2 was built against `JDK 1.8`).

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Oh, is it fixed? IIRC, 2.0.0 was built against Java 22.

**Comment by panbingkun** [comment]
@dongjoon-hyun 
Thank you very much for your reminder, the verification process is as follows:
- v2.0.2
```shell
(base) ➜  io find . -name "*.class" | xargs javap -v | grep "major version" | sort | uniq
  major version: 52
(base) ➜  io pwd
/Users/panbingkun/.m2/repository/io/airlift/aircompressor/2.0.2/tmp/io
(base) ➜  io
```

- v2.0.0
```shell
(base) ➜  io find . -name "*.class" | xargs javap -v | grep "major version" | sort | uniq
  major version: 66
(base) ➜  io pwd
/Users/panbingkun/Downloads/aircompressor-2.0/io
```

### From the verification process, it has indeed been fixed.

**Comment by dongjoon-hyun** [comment]
Nice, @panbingkun !

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @panbingkun .
Merged to master for Apache Spark 4.0.0-preview2.

**Comment by panbingkun** [comment]
> +1, LGTM. Thank you, @panbingkun . Merged to master for Apache Spark 4.0.0-preview2.

Thanks!

**Pull request closed without merging**
