### PR TITLE
[SPARK-45779][INFRA] Add a check step for jira issue ticket to be resolved

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

This PR moves the step for printing the summary of the Jira issue and adds a confirmation step for committers before assigning it to a user.

Also, we show the final status of the Jira issue after resolution.

### Why are the changes needed?

The JIRA ID mentioned in the PR title can sometimes be incorrect due to carelessness. Double-checking the ID is necessary to ensure that it is accurate. It is now too late for the committers to modify the ID once they have seen the ticket summary.

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

Tested with SPARK-45776.

Note that the message below may seem noisy because I declined the merge script at first.

```
Would you like to update an associated JIRA? (y/n): y
Enter a JIRA id[SPARK-45776]:
=== JIRA SPARK-45776 ===
summary		Remove the defensive null check added in SPARK-39553.
assignee	None
status		Open
url		https://issues.apache.org/jira/browse/SPARK-45776

Check if the JIRA information is as expected(y/n): n
Enter the revised JIRA ID again or leave blank to skip[]: SPARK-45776
=== JIRA SPARK-45776 ===
summary		Remove the defensive null check added in SPARK-39553.
assignee	None
status		Open
url		https://issues.apache.org/jira/browse/SPARK-45776

Check if the JIRA information is as expected(y/n): y
JIRA is unassigned, choose assignee
[0] Yang Jie (Reporter)
Enter number of user, or userid, to assign to (blank to leave unassigned):0
Enter comma-separated fix version(s) [4.0.0]:
=== JIRA SPARK-45776 ===
summary		Remove the defensive null check added in SPARK-39553.
assignee        Yang Jie
status		RESOLVED
url		https://issues.apache.org/jira/browse/SPARK-45776

Successfully resolved SPARK-45776 with fixVersions=['4.0.0']!
Enter a JIRA id[SPARK-39553]:
```
### Was this patch authored or co-authored using generative AI tooling?

no

### CODE REVIEW

**Comment by yaooqinn** [comment]
cc @dongjoon-hyun @HyukjinKwon , thanks

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by yaooqinn** [comment]
Thank you, @dongjoon-hyun.

**Review by beliefer — APPROVED** [review]
Looks good!

**Comment by yaooqinn** [comment]
Thank you @dongjoon-hyun and @beliefer 

Merged to master

**Review by HyukjinKwon — COMMENTED** [review]
Nice, LGTM

**Pull request closed without merging**
