### PR TITLE
[SPARK-7687] [SQL] DataFrame.describe() should cast all aggregates to String

### PR DESCRIPTION
**Pull request by JoshRosen**
In `DataFrame.describe()`, the `count` aggregate produces an integer, the `avg` and `stdev` aggregates produce doubles, and `min` and `max` aggregates can produce varying types depending on what type of column they're applied to.  As a result, we should cast all aggregate results to String so that `describe()`'s output types match its declared output schema.

### CODE REVIEW

**Comment by JoshRosen** [comment]
I discovered this issue while extending CatalystTypeConverters to convert UnsafeRows into Scala Rows.  My new converter is stricter about types, which caused a test failure that exposed this bug.

**Comment by rxin** [comment]
LGTM

**Comment by JoshRosen** [comment]
Jenkins, retest this please.

**Comment by JoshRosen** [comment]
Jenkins, retest this please.

**Comment by rxin** [comment]
Jenkins, retest this please.

**Comment by JoshRosen** [comment]
Jenkins, retest this please.

**Comment by JoshRosen** [comment]
Whoops, looks like I forgot to update the R test:

```
1. Failure(@test_sparkSQL.R#764): describe() on a DataFrame --------------------
collect(stats)[4, "name"] == "Andy" isn't true
```

**Comment by JoshRosen** [comment]
@rxin, it looks like this test is failing because the R test expects the `min` of a string-valued column to return a string:

```r
test_that("describe() on a DataFrame", {
  df <- jsonFile(sqlCtx, jsonPath)
  stats <- describe(df, "age")
  expect_true(collect(stats)[1, "summary"] == "count")
  expect_true(collect(stats)[2, "age"] == 24.5)
  expect_true(collect(stats)[3, "age"] == 5.5)
  stats <- describe(df)
  expect_true(collect(stats)[4, "name"] == "Andy")
  expect_true(collect(stats)[5, "age"] == 30.0)
})
```

How should we handle this?

**Comment by rxin** [comment]
Does describe work on non-numeric columns?

**Comment by JoshRosen** [comment]
Yeah, it seems to because it looks like we don't actually enforce types:

```scala
    val describeNonNumericColumn = describeTestData.describe("name")
```

When I collect and print the output, this outputs:

```
WrappedArray([count,4], [mean,null], [stddev,null], [min,Alice], [max,David])
```

**Comment by rxin** [comment]
If we actually support running describe on non-numeric columns, then stringtype is the only option.

**Comment by JoshRosen** [comment]
Maybe we could use some sort of least-upper-bound to determine which cast to perform.  For instance, if we have all numeric columns, then perform a Double cast and declare the output columns as DoubleType, otherwise use StringType.

**Comment by rxin** [comment]
It's not that big of a deal to optimize this. Basically describe is only used for interactive data exploration for viewing results, so any data type that doesn't crash the system is OK, e.g. string.

**Comment by JoshRosen** [comment]
My concern was users who might be relying on the existing defined behavior of this returning all double columns.  Basically, it seems like aggregating over all numeric columns is defined behavior, whereas aggregating over non-numeric columns is undefined behavior.  It's fine to change undefined behavior, but I think we should avoid changing defined behavior if it's possible to do so.

**Comment by rxin** [comment]
describe should only be used for interactive data analysis -- i.e. no users should depend on its output. We should perhaps update documentation to include that.

**Comment by JoshRosen** [comment]
Whoops, looks like I overlooked the Scaladoc comment:

```
   * This function is meant for exploratory data analysis, as we make no guarantee about the
   * backward compatibility of the schema of the resulting [[DataFrame]]. If you want to
   * programmatically compute summary statistics, use the `agg` function instead.
```

I'll update it to include the string casts.

**Comment by JoshRosen** [comment]
I've updated the code and PR description for the string cast.

**Comment by shivaram** [comment]
R tests LGTM.

**Comment by JoshRosen** [comment]
Looks like the R test failed in Jenkins:

```
1. Failure(@test_sparkSQL.R#765): describe() on a DataFrame --------------------
collect(stats)[5, "age"] == "30.0" isn't true
```

I remember verifying that the tests passed locally before pushing my latest changes, so let me try to run again to see if I can reproduce the failure.

**Comment by shivaram** [comment]
It might be a problem with how the rows are ordered / partitioned ? @davies had fixed some of these before in other tests.

**Comment by JoshRosen** [comment]
Does R have an equivalent of ScalaTest's fancy `assert` macro or its `should` matchers to give better error messages?  It would be really helpful to know what's actually being returned by this failing command.

**Comment by davies** [comment]
This one is different, it may be related to format of a double value (the number of ending zeros).

**Comment by shivaram** [comment]
We use testthat https://github.com/hadley/testthat to do assertions. I am not sure if it supports the ScalaTest like error messages.

**Comment by JoshRosen** [comment]
Ah, looks like we can use `expect_equal` instead of `expect_true`: http://r-pkgs.had.co.nz/tests.html.

The problem here was an extra decimal point:

```
2. Failure(@test_sparkSQL.R#765): describe() on a DataFrame --------------------
collect(stats)[5, "age"] not equal to "30.0"
1 string mismatches:
x[1]: "30.0"
y[1]: "30"
```

**Comment by shivaram** [comment]
Ah - good catch ! You can also file a JIRA to audit the rest of the test cases to use `expect_equal`

**Comment by JoshRosen** [comment]
@shivaram I've filed https://issues.apache.org/jira/browse/SPARK-7714 for the SparkR test improvements.

**Comment by JoshRosen** [comment]
Test failures appear to be unrelated ORC failures, although that means that R didn't get a chance to run.  I think that this has been fixed in master, so let's try another round of testing.

**Comment by JoshRosen** [comment]
Jenkins, retest this please.

**Pull request closed without merging**
