### PR TITLE
[SPARK-45044][PYTHON][DOCS] Refine docstring of `groupBy/rollup/cube`

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
This pr aims to refine docstring of `DataFrame.groupBy/rollup/cube` and fix potentially wrong underline length.

### Why are the changes needed?
- To improve PySpark documentation.

- Fix potentially wrong underline length.
   image

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
- Pass GA.
- Manually test.
```
cd python/docs
make clean html
```

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by panbingkun** [comment]
cc @HyukjinKwon @zhengruifeng

**Comment by zhengruifeng** [comment]
thanks @panbingkun , would you mind waiting for https://github.com/apache/spark/pull/42832 which happen to add new feature to `rollup/cube` ?

**Comment by panbingkun** [comment]
> thanks @panbingkun , would you mind waiting for #42832 which happen to add new feature to `rollup/cube` ?

Okay, let's wait for it.

**Comment by panbingkun** [comment]
@zhengruifeng 
I have synchronized the changes after https://github.com/apache/spark/pull/42832 to this PR.

**Review by zhengruifeng — APPROVED** [review]

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by zhengruifeng** [comment]
thanks, merged to master

**Pull request closed without merging**
