### PR TITLE
[SPARK-10617] [SQL] Fixed AddMonths leap year calculations

### PR DESCRIPTION
**Pull request by alexrovner**

### CODE REVIEW

**Comment by rxin** [comment]
cc  @davies

**Comment by davies** [comment]
@alexrovner The current behavior followes Hive, see https://issues.apache.org/jira/browse/HIVE-9357

**Comment by davies** [comment]
From Oracle: https://docs.oracle.com/cd/B28359_01/server.111/b28286/functions004.htm
```
If date is the last day of the month or if the resulting month has fewer days than the day component of date, then the result is the last day of the resulting month.
```

**Comment by srowen** [comment]
(Do you mind closing this PR too?)

**Comment by alexrovner** [comment]
Indeed Hive's behavior is exactly the same, although this is not consistent across platform / DB engines. Closing...

**Pull request closed without merging**
