### PR TITLE
[SPARK-25433][PYSPARK] Add support for pex in PySpark

### PR DESCRIPTION
**Pull request by fhoering**
## What changes were proposed in this pull request?

This change aims to provide the very basic support to provision the executors with pex files (instead of conda or virtual env). It contains only the minimal required changes. Everything else can be setup with environment variables.
Similar to how it works today with conda the user needs to make sure that he has the same environment when submitting the Spark job and the environment provided in the pex file.

## How was this patch tested?

Various runs with spark-submit (client, cluster) and by directly creating a SparkContext on a Yarn Cluster.

Also tested with a unit test using a locally created pex file (inspired by python/pyspark/tests/AddFileTests). The issue is that pex files contain information about the platform/runtime and therefore I can't provide a generic test because of the check to have the same python minor version on the client and on executors. It would mean to create a pex file for every python runtime and every existing platform. I can provide some code in here in order to execute locally. Maybe it is also possible to use SparkSubmitTests ?

### CODE REVIEW

**Comment by fhoering** [comment]
It turns out all this can be tailored by tuning the existing environment variables. It is enough to generate the pex file with a generic entry point that does the redirection to the custom module and then even the existing code work: `Arrays.asList(pythonExec, "-m", workerModule)`
Will close this PR.

**Comment by rs-trevor** [comment]
@fhoering Any chance we can document this a bit more here?

I think you're saying 

- Add a __main__.py to the root level for an entry point?
- `spark-submit a.pex`?

**Comment by fhoering** [comment]
@rs-trevort 
It is documented here with some examples:
https://medium.com/criteo-labs/packaging-code-with-pex-a-pyspark-example-9057f9f144f3

**Comment by rs-trevor** [comment]
This is great. What a guy! Thanks @fhoering

**Pull request closed without merging**
