### PR TITLE
[SPARK-46904][UI] Fix display issue of History UI summary

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

This PR segments the content definition of the History Page into `summary/table/links` to make it much more elegant. The previous giant variable seems to be a perfect place for bugs to lurk. The problem here is a kinda upstream issue that rendered one single-tagged `<script .../>` wrongly to an unclosed paired tag `<script>,` which missed a close tag.

### Why are the changes needed?

bugfix
### Does this PR introduce _any_ user-facing change?

no
### How was this patch tested?

locally tested

image

### Was this patch authored or co-authored using generative AI tooling?

no

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Thank you, @yaooqinn . 

At the bottom of this page, `Show Incomplete applications` seems to start to be misaligned. Could you align them too?

Screenshot 2024-01-29 at 8 02 02 AM


For example,

**Apache Spark 3.5.0**
Screenshot 2024-01-29 at 8 04 46 AM

**This PR**
Screenshot 2024-01-29 at 8 05 36 AM

**Comment by dongjoon-hyun** [comment]
I fixed it
```scala
     val pageLink =
-      <div>
+      <div class="container-fluid">
```

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

I verified this PR with my last commit on this PR. Thank you again, @yaooqinn .

Merged to master.

**Comment by yaooqinn** [comment]
@dongjoon-hyun, Thank you for the review and hotfix :)

**Pull request closed without merging**
