### PR TITLE
[SPARK-39113][CORE][MLLIB][PYTHON] Rename `self` to `cls`

### PR DESCRIPTION
**Pull request by bjornjorgensen**
### What changes were proposed in this pull request?
Rename `self` to `cls`

### Why are the changes needed?
Function def train(self....) is decorated as a @classmethod

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass existed tests.

### CODE REVIEW

**Comment by Yikun** [comment]
I'm fine with it. This is not mandatory but it's suggestion from pep8.

[1] https://peps.python.org/pep-0008/#function-and-method-arguments

```
# grep -R "@classmethod" **/*.py -A2 | grep self
python/pyspark/mllib/clustering.py-        self,
python/pyspark/testing/sqlutils.py-    def sqlType(self):
python/pyspark/testing/sqlutils.py-    def sqlType(self):
```

Then, let's also fix other style error together.

**Comment by srowen** [comment]
Are there any other cases?

**Comment by bjornjorgensen** [comment]
Thank you @Yikun 
What tool are you using? 

@srowen Not that I can find. 

I`m using [sonarqube](https://sonar-spark.duckdns.org) but I can`t search after only this one thing.

**Comment by Yikun** [comment]
@bjornjorgensen No tool in here, just a script as I mentioned in last comment: `grep -R "@classmethod" **/*.py -A2 | grep self`

**Review by Yikun — APPROVED** [review]

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
