### PR TITLE
[SPARK-16589][PYTHON] Chained cartesian produces incorrect number of records

### PR DESCRIPTION
**Pull request by zero323**
## What changes were proposed in this pull request?

If either self or other is serialized using `CartesianSerializer` it is reserialized with default serializer before executing `_jrdd.cartesian`.
## How was this patch tested?

Using existing unit tests as well as additional test case to address  SPARK-16589.

### CODE REVIEW

**Comment by holdenk** [comment]
Is this the best way to fix this? e.g. does the cartesian serializer only have problems when chained with other cartesian products or is this a problem that might make sense to look at in the CartesianSerializer its self instead?
Anyways cc @JoshRosen

**Comment by zero323** [comment]
@holdenk [I had the same doubts](https://issues.apache.org/jira/browse/SPARK-16589?focusedCommentId=15382614&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15382614) and to be honest I am not sure what is the right approach here.

On a side note chained `cartesian` didn't work before 1.3 at all and is broken since 1.4 and for some reason results are not even consistent between Python version. So in general problem can be much more complex than this.

**Comment by holdenk** [comment]
In that case maybe we should consider investigating it a bit more before we fix this one specific case?

**Comment by zero323** [comment]
@holdenk Can we move this discussion to JIRA?

**Pull request closed without merging**
