### PR TITLE
[SPARK-39308][BUILD][SQL] Upgrade parquet to 1.12.3

### PR DESCRIPTION
**Pull request by wangyum**
### What changes were proposed in this pull request?

Upgrade Parquet version to 1.12.3.

### Why are the changes needed?

[PARQUET-1968](https://issues.apache.org/jira/browse/PARQUET-1968) can simplify current In predicate filter pushdown.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Existing test.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
cc @sunchao

**Review by sunchao — APPROVED** [review]
LGTM

**Comment by huaxingao** [comment]
@wangyum I saw 1.12.3 was released 4 hours ago, but somehow I can't find the release notes. Do you have a link to the release notes? Trying to see the list of PRs that are included in 1.12.3.

**Comment by wangyum** [comment]
@huaxingao You can compare two tags: https://github.com/apache/parquet-mr/compare/apache-parquet-1.12.2...apache-parquet-1.12.3

**Review by huaxingao — APPROVED** [review]

**Comment by wangyum** [comment]
Thank you all.

**Comment by wangyum** [comment]
Merged  to master.

**Review by dongjoon-hyun — COMMENTED** [review]
+1, LGTM. Thank you all.

**Pull request closed without merging**
