### PR TITLE
[SPARK-43056][SS] RocksDB state store commit should continue background work only if its paused

### PR DESCRIPTION
**Pull request by anishshri-db**
### What changes were proposed in this pull request?
RocksDB state store commit should continue background work in finally only if its paused

### Why are the changes needed?
If an exception is thrown earlier in the commit sequence before background work is paused, we fail with an exception in the finally clause.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Ran unit tests
```
StateStoreIntegrationSuite
[info] Run completed in 16 seconds, 131 milliseconds.
[info] Total number of tests run: 5
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 5, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
```

```
StateStoreSuite
[info] Run completed in 1 minute, 18 seconds.                                                                                                                                                                                                                                              [info] Total number of tests run: 73
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 73, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
```

With simulated exception and without the fix, the code crashes with stack trace below. With the fix, we don't see the issue in the finally block.
```
  org.rocksdb.RocksDBException: InvalidArgument
  at org.rocksdb.RocksDB.continueBackgroundWork(Native Method)
  at org.rocksdb.RocksDB.continueBackgroundWork(RocksDB.java:3611)
  at org.apache.spark.sql.execution.streaming.state.RocksDB.commit(RocksDB.scala:421)
```

### CODE REVIEW

**Comment by anishshri-db** [comment]
@HeartSaVioR - PTAL. Thanks

**Review by HeartSaVioR — APPROVED** [review]
+1 Nice finding!

**Comment by HeartSaVioR** [comment]
CI fails with odd errors.
@anishshri-db Could you please rebase so that CI is retriggered? If the new trial fails again, maybe good to post to dev@ and see whether someone encountered this before, and/or someone is willing to volunteer to fix if that's not a transient issue.

**Comment by anishshri-db** [comment]
>  Could you please rebase so that CI is retriggered? If the new trial fails again, maybe good to post to dev@ and see whether someone encountered this before, and/or someone is willing to volunteer to fix if that's not a transient issue.

Seems like a known issue someone already posted to dev channel - https://github.com/sbt/sbt/issues/7202

**Comment by anishshri-db** [comment]
@HeartSaVioR - all tests passed. Please merge when you get a chance. Thx

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by HeartSaVioR** [comment]
Missed the notification. Thanks! Merging to master.

**Pull request closed without merging**
