### PR TITLE
[SPARK-31831][SQL][TESTS] HiveSessionImplSuite flakiness fix via mocking instances earlier than initializing HiveSessionImpl

### PR DESCRIPTION
**Pull request by HeartSaVioR**
### What changes were proposed in this pull request?

This patch changes the HiveSessionImplSuite to mock instances "before" initializing HiveSessionImpl, to avoid possible classloader issue. 

### Why are the changes needed?

The failures of HiveSessionImplSuite always come from classloader issue. While I don't have clear idea what is happening, there's no part possibly dealing with classloader, except initializing HiveSessionImpl. We can move the mock initializations earlier than initialing HiveSessionImpl so that it can avoid possible classloader issue.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Verified with multiple triggers of Jenkins builds

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
Rationalization: the failures always come from classloader issue;

```
sbt.ForkMain$ForkError: org.mockito.exceptions.base.MockitoException: 
ClassCastException occurred while creating the mockito mock :
  class to mock : 'org.apache.hive.service.cli.session.SessionManager', loaded by classloader : 'sun.misc.Launcher$AppClassLoader@2d6d8735'
  created class : 'org.mockito.codegen.SessionManager$MockitoMock$2028320452', loaded by classloader : 'net.bytebuddy.dynamic.loading.MultipleParentClassLoader@4058f9df'
  proxy instance class : 'org.mockito.codegen.SessionManager$MockitoMock$2028320452', loaded by classloader : 'net.bytebuddy.dynamic.loading.MultipleParentClassLoader@4058f9df'
  instance creation by : ObjenesisInstantiator

You might experience classloading issues, please ask the mockito mailing-list.

	at org.apache.spark.sql.hive.thriftserver.HiveSessionImplSuite.beforeAll(HiveSessionImplSuite.scala:44)
	at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:212)
	at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
	at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
	at org.apache.spark.SparkFunSuite.run(SparkFunSuite.scala:59)
	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:317)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:510)
	at sbt.ForkMain$Run$2.call(ForkMain.java:296)
	at sbt.ForkMain$Run$2.call(ForkMain.java:286)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: sbt.ForkMain$ForkError: java.lang.ClassCastException: org.mockito.codegen.SessionManager$MockitoMock$2028320452 cannot be cast to org.mockito.internal.creation.bytebuddy.MockAccess
	at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.createMock(SubclassByteBuddyMockMaker.java:48)
	at org.mockito.internal.creation.bytebuddy.ByteBuddyMockMaker.createMock(ByteBuddyMockMaker.java:25)
	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:35)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:63)
	at org.mockito.Mockito.mock(Mockito.java:1908)
	at org.mockito.Mockito.mock(Mockito.java:1817)
	... 13 more
```

while I don't have clear idea what is happening, there's no part possibly dealing with classloader, except initializing `HiveSessionImpl` (only suspect, no clear evidence yet). This patch is to verify the idea that mocking instances before initializing HiveSessionImpl would avoid the classloader issue.

It's less flaky then CliSuite and only checked once per build, so to verify multiple times I just create 9 duplicated suites to test 10 times per build.

**Comment by HeartSaVioR** [comment]
retest this, please

**Comment by HeartSaVioR** [comment]
retest this, please

**Comment by HeartSaVioR** [comment]
retest this, please

**Comment by HeartSaVioR** [comment]
retest this, please

**Comment by HeartSaVioR** [comment]
retest this, please

**Comment by HeartSaVioR** [comment]
Summary of 4 builds:

> 125361 (https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/125361/testReport/)

HiveSessionImplSuite(s) passed

> 125368 (https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/125368/testReport/)

HiveSessionImplSuite(s) passed

> 125371 (https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/125371/testReport/)

HiveSessionImplSuite(s) passed

> 125375 (https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/125375/testReport/)

HiveSessionImplSuite(s) passed

I'll trigger more builds to confirm, and once the new builds also pass HiveSessionImplSuite(s), turn the PR to be ready to review.

**Comment by HeartSaVioR** [comment]
retest this, please

**Comment by HeartSaVioR** [comment]
retest this, please

**Comment by HeartSaVioR** [comment]
retest this, please

**Comment by HeartSaVioR** [comment]
retest this, please

**Comment by HeartSaVioR** [comment]
retest this, please

**Comment by HeartSaVioR** [comment]
retest this, please

**Comment by HeartSaVioR** [comment]
retest this, please

**Comment by HeartSaVioR** [comment]
Another summary for next set of builds

> 125405 (https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/125405/testReport/)

All suites passed

> 125410 (https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/125410/testReport/)

Lots of tests in CliSuite failed - #29036 is to fix flakiness, so please cross-check this and #29036 together

> 125416 (https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/125416/testReport/)

All suites passed

> 125412 (https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/125412/testReport/)

Lots of tests in CliSuite failed

> 125420 (https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/125420/testReport/)

Lots of tests in CliSuite failed

**Comment by HeartSaVioR** [comment]
cc. @dongjoon-hyun @alismess-db

**Review by srowen — APPROVED** [review]
Likewise looks good if it passes and fixes the issue.

**Comment by dongjoon-hyun** [comment]
Thank you for pinging me, @HeartSaVioR .

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @HeartSaVioR and @srowen .
Merged to master because the affected version of SPARK-31831 is only `3.1.0`.

**Comment by HeartSaVioR** [comment]
Thanks for reviewing and merging! We can port back anytime when we find the flakiness in other branches, so it should be OK to start with only master branch.

**Pull request closed without merging**
