### PR TITLE
[SPARK-44260][SQL] Assign names to the error class _LEGACY_ERROR_TEMP_[1215-1245-2329] & Use checkError() to check Exception in *CharVarchar*Suite

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to:
1.Assign clear error class names for some logic in `CharVarcharCodegenUtils` that directly uses exceptions
- EXCEED_LIMIT_LENGTH

2.Assign names to the error class
- _LEGACY_ERROR_TEMP_1215 -> UNSUPPORTED_CHAR_OR_VARCHAR_AS_STRING
- _LEGACY_ERROR_TEMP_1245 -> NOT_SUPPORTED_CHANGE_COLUMN
- _LEGACY_ERROR_TEMP_2329  -> merge to NOT_SUPPORTED_CHANGE_COLUMN(_LEGACY_ERROR_TEMP_1245)

3.Use checkError() to check Exception in `*CharVarchar*Suite`

### Why are the changes needed?
The changes improve the error framework.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
- Update UT
- Pass GA
- Manually test.

### CODE REVIEW

**Comment by panbingkun** [comment]
The pr original intention was to use checkError() to check Exception in *CharVarchar*Suite, the above modifications have emerged in this process.

**Comment by panbingkun** [comment]
cc @MaxGekk

**Review by MaxGekk — APPROVED** [review]
Waiting for CI.

**Comment by MaxGekk** [comment]
+1, LGTM. Merging to master.
Thank you, @panbingkun.

**Pull request closed without merging**
