### PR TITLE
[SPARK-22243][DStreams]spark.yarn.jars reload from config when Checkpoint recovery

### PR DESCRIPTION
**Pull request by ChenjunZou**
add spark.yarn.jars to the checkpoint reload configs.

### CODE REVIEW

**Comment by zsxwing** [comment]
ok to test

**Comment by zsxwing** [comment]
LGTM. cc @jerryshao to take a look.

**Comment by jerryshao** [comment]
@ChenjunZou did you get a chance to look at my left comment?

**Comment by ssaavedra** [comment]
I think that may be a good idea. I'd say this can depend on the scheduler. Should that be discussed under a different JIRA number?

**Comment by felixcheung** [comment]
@jerryshao I think it's a good idea to have a design to work with different resource manager.

As of now though there is only one additional config needed for k8s, and from this PR one for yarn.
What's next?

**Comment by ssaavedra** [comment]
The one I submitted here https://issues.apache.org/jira/browse/SPARK-22294 is not kubernetes-related as such, although it does affect deployments in Kubernetes. It should affect any spark-submit done with a custom bindAddress.

But yes, there might be a k8s-related config at some point, just like there is specific configuration for YARN already.

But the currently proposed PRs are just bugs caught at some point by other PRs. Maybe they should be merged and then a more general architecture can be proposed? This way we'll have all the properties known to need reloading already in the code before refactoring.

Is there anything we should know about structured streaming in regards to checkpoints?

**Comment by jerryshao** [comment]
@felixcheung As you can see there's bunch of configurations needs to be added here in https://github.com/apache-spark-on-k8s/spark/pull/516, that's why I'm asking a general solutions for such related issue.

I'm OK to merge this PR. But I would suspect similar PRs will still be created in future, since those issues are quite scenario specific, users may have different scenarios and can touch different issues regarding to this. So I'm just wondering if we could have a better solution for this.

**Comment by felixcheung** [comment]
Ah, I didn't realize there is a change in that PR.
I agree we need a better solution

**Comment by zsxwing** [comment]
Sorry for the delay. I think it's not worth to design a new feature that's only for DStream. Instead, I would encourage people to use Structured Streaming in the new Spark versions.

I'm okey to just merge this PR and future minor PRs (I don't think it will be a lot) for the similar issues. @ChenjunZou could you reopen this PR, please?

**Comment by felixcheung** [comment]
sure, @zsxwing please beaware of https://github.com/apache-spark-on-k8s/spark/pull/516 and https://github.com/apache/spark/pull/19427

**Comment by zsxwing** [comment]
> sure, @zsxwing please beaware of apache-spark-on-k8s#516 and #19427

Yeah. I'm aware of them. I will review #19427.

**Comment by zsxwing** [comment]
FYI, looks like @ChenjunZou opened a new PR #19637 rather than reopening this. Since the content is the same, I just merged #19637.

**Pull request closed without merging**
