### PR TITLE
[SPARK-34934] Fix race condition while adding/removing sources in MetricsSystem

### PR DESCRIPTION
**Pull request by BOOTMGR**
### What changes were proposed in this pull request?

Synchronise access to `registerSource` and `removeSource` method since underlying `ArrayBuffer` is not thread safe.

### Why are the changes needed?

Unexpected behaviours are possible due to lack of thread safety, Like we got `ArrayIndexOutOfBoundsException` while adding new source.

### Does this PR introduce _any_ user-facing change?

No

### CODE REVIEW

**Comment by srowen** [comment]
I suppose getMetricsByName references it too.
I'm not sure if it is possible to do these concurrently but doesn't hurt.

**Comment by BOOTMGR** [comment]
> I suppose getMetricsByName references it too.
> I'm not sure if it is possible to do these concurrently but doesn't hurt.

By `getMetricsByName` I assume you mean `getSourcesByName`. Thanks for pointing out that. Since we compact buffer in case of remove, it perfectly makes sense to synchronize get operation. I have updated patch to synchronize it. Bdw, do you think synchronizing all of them on same object would be performant enough? or we should opt for `ReadWriteLock`?

**Comment by srowen** [comment]
Right, getSourcesByName. I think this approach is fine.

**Comment by srowen** [comment]
Jenkins test this please

**Review by srowen — APPROVED** [review]
Just thinking out loud - does `sinks` have the same problem? they can't be removed but can be added while `foreach` is called, potentially, but I'm not sure that makes sense semantically to re-register sinks while running.

**Comment by BOOTMGR** [comment]
`registerSinks` is private to class. The only reference is `MetricsSystem#start` which I believe is called during initialization of `instance`. So, I believe it should be fine.

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
