### PR TITLE
[SPARK-36167][PYTHON][3.2] Revisit more InternalField managements

### PR DESCRIPTION
**Pull request by ueshin**
### What changes were proposed in this pull request?

This is a backport of #33377.

Revisit and manage `InternalField` in more places.

### Why are the changes needed?

There are other places we can manage `InternalField`, and we can keep extension dtypes or `CategoricalDtype`.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Added some tests.

### CODE REVIEW

**Comment by ueshin** [comment]
cc @HyukjinKwon

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
looks like there's a valid test failure:

```
======================================================================
ERROR [1.825s]: test_intersection (pyspark.pandas.tests.indexes.test_category.CategoricalIndexTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/apache-spark/apache-spark/python/pyspark/testing/pandasutils.py", line 138, in assertPandasEqual
    assert_index_equal(left, right, check_exact=check_exact)
  File "/__t/Python/3.6.14/x64/lib/python3.6/site-packages/pandas/_testing.py", line 747, in assert_index_equal
    _check_types(left, right, obj=obj)
  File "/__t/Python/3.6.14/x64/lib/python3.6/site-packages/pandas/_testing.py", line 717, in _check_types
    assert_attr_equal("dtype", l, r, obj=obj)
AssertionError: Index are different

Attribute "dtype" are different
[left]:  CategoricalDtype(categories=['z', 'y', 'x', 'w'], ordered=False)
[right]: CategoricalDtype(categories=['x', 'y'], ordered=False)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/__w/apache-spark/apache-spark/python/pyspark/pandas/tests/indexes/test_category.py", line 163, in test_intersection
    psidx1.intersection(psidx2).sort_values(), pidx1.intersection(pidx2).sort_values()
  File "/__w/apache-spark/apache-spark/python/pyspark/testing/pandasutils.py", line 223, in assert_eq
    self.assertPandasEqual(lobj, robj, check_exact=check_exact)
  File "/__w/apache-spark/apache-spark/python/pyspark/testing/pandasutils.py", line 145, in assertPandasEqual
    raise AssertionError(msg) from e
AssertionError: Index are different

Attribute "dtype" are different
[left]:  CategoricalDtype(categories=['z', 'y', 'x', 'w'], ordered=False)
[right]: CategoricalDtype(categories=['x', 'y'], ordered=False)

Left:
CategoricalIndex(['y', 'x'], categories=['z', 'y', 'x', 'w'], ordered=False, dtype='category')
category

Right:
CategoricalIndex(['x', 'y'], categories=['x', 'y'], ordered=False, dtype='category')
category

----------------------------------------------------------------------
```

**Comment by ueshin** [comment]
Jenkins, retest this please.

**Comment by ueshin** [comment]
Hmm, seems like some tests are pretty unstable.

- `test_parameter_convergence (pyspark.mllib.tests.test_streaming_algorithms.StreamingLinearRegressionWithTests)` is flaky
- In `Java 11 build with Maven`, `mvn` command keeps being killed for some reason.
 
```
 ./build/mvn: line 178:  1766 Killed                  "${MVN_BIN}" "$@"
Error: Process completed with exit code 137.
```

- In` Run TPC-DS queries with SF=1`, the tests keep being killed for some reason.

```
/home/runner/work/apache-spark/apache-spark/build/sbt-launch-lib.bash: line 77:  3808 Killed                  "$@"
Error: Process completed with exit code 137.
```

**Comment by HyukjinKwon** [comment]
Merged to branch-3.2.

**Pull request closed without merging**
