### PR TITLE
[SPARK-22121][SQL] Correct database location for namenode HA.

### PR DESCRIPTION
**Pull request by squito**
## What changes were proposed in this pull request?

If hdfs HA is turned on after a hive database is already created, the db
location may still reference just one namenode, instead of the
nameservice, if users do not properly follow all upgrade instructions.
After this change, spark detects the misconfiguration and tries to
auto-adjust for it, since this is the behavior from hive as well.

## How was this patch tested?

Added unit tests.  Also deployed on a cluster with hdfs ha, with the database location set to only one instance, and then I failed over the namenode so the other instance was the active one.  After this change, things worked without a problem.

### CODE REVIEW

**Comment by gatorsmile** [comment]
This is not `[CORE]`. The title should be updated to `[SQL]`

**Comment by gatorsmile** [comment]
Spark SQL might not be deployed in the HDFS system. Conceptually, this HDFS-specific codes should not be part of our `HiveExternalCatalog`

**Comment by squito** [comment]
whoops, sorry I wrote [CORE] out of habit!

> Spark SQL might not be deployed in the HDFS system. Conceptually, this HDFS-specific codes should not be part of our HiveExternalCatalog . HiveExternalCatalog is just for using Hive metastore. It does not assume we use HDFS.

yes, I totally understand that.  Even for users that are on hdfs, this is clear user-error, they should be using hive's metatool to update the database location.  Originally I thought this would be unnecessary complication in spark, but with enough complaints I figured maybe spark could just handle it automatically.

Is there another place this could go instead?

Anyway, if you really feel like this doesn't belong in spark, that is fine.

**Comment by gatorsmile** [comment]
@squito Thank you! 

Instead of changing the source codes, could we just update the document https://spark.apache.org/docs/2.2.0/sql-programming-guide.html#hive-tables ? This might be enough for this issue.

**Comment by squito** [comment]
I don't see much point in putting this in the docs ... it seems too fine-grained a detail to be useful there.  I just don't see the users who encounter this exception from going to look at the spot in the docs to figure out exactly what is wrong.  I put an example exception in the JIRA, so at least users can find it with a search.  

Sounds like you feel pretty strongly we should close this as "won't fix"?  I'd still prefer to have this in, but will settle for just having the workaround be easily searchable

**Comment by gatorsmile** [comment]
Thanks! Maybe we can close it now and revisit it when we have a better way to resolve the file system specific issues?

**Comment by squito** [comment]
OK, closing this and the jira

**Pull request closed without merging**
