### PR TITLE
[SPARK-33357][k8s]Support SparkLauncher in Kubernetes

### PR DESCRIPTION
**Pull request by hddong**
### What changes were proposed in this pull request?

Support SparkLauncher in Kubernetes and the application status can be obtained normally.

### Why are the changes needed?

Now, the application status can not be obtained normally when submit by SparkLauncher.

### Does this PR introduce _any_ user-facing change?

No

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Hi, @hddong
Could you fill the PR description?

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
Could you please provide a test case or a reproducible procedure for verification?

**Comment by HyukjinKwon** [comment]
Yeah, what does this PR exactly targets to add, and how did you test?

**Comment by dongjoon-hyun** [comment]
I close this due to the inactivity. Please feel free to reopen this when the PR is ready.

**Pull request closed without merging**
