### PR TITLE
[SQL] [TEST] [Minor] Uses a temporary log4j.properties in HiveThriftServer2Test to ensure expected logging behavior

### PR DESCRIPTION
**Pull request by liancheng**
The `HiveThriftServer2Test` relies on proper logging behavior to assert whether the Thrift server daemon process is started successfully. However, some other jar files listed in the classpath may potentially contain an unexpected Log4J configuration file which overrides the logging behavior.

This PR writes a temporary `log4j.properties` and prepend it to driver classpath before starting the testing Thrift server process to ensure proper logging behavior.

cc @andrewor14 @yhuai

### CODE REVIEW

**Comment by andrewor14** [comment]
Does this mean the test results won't appear in `unit-test.logs`?

**Comment by yhuai** [comment]
It should only affect the thrift server. Not the client side (those unit tests).

**Comment by andrewor14** [comment]
I see, because it's adding it to the driver JVM, not to the test JVM.

**Comment by andrewor14** [comment]
I just tried this patch out locally on top of #6441 and verified that the `hive-thriftserver` tests now pass.

**Comment by andrewor14** [comment]
Merging into master 1.4 once tests pass.

**Comment by andrewor14** [comment]
OK, I re-merged this in 1.4 since the follow up fix for java 6 is up.

**Comment by andrewor14** [comment]
@liancheng seems like this is needed for branch-1.3 for #6602. Could you open a branch against that one?

**Comment by andrewor14** [comment]
Actually I got it.

**Pull request closed without merging**
