### PR TITLE
[SPARK-25472][SS] Don't have legitimate stops of streams cause stream exceptions

### PR DESCRIPTION
**Pull request by brkyvz**
## What changes were proposed in this pull request?

Legitimate stops of streams may actually cause an exception to be captured by stream execution, because the job throws a SparkException regarding job cancellation during a stop. This PR makes the stop more graceful by swallowing this cancellation error.

## How was this patch tested?

This is pretty hard to test. The existing tests should make sure that we're not swallowing other specific SparkExceptions. I've also run the `KafkaSourceStressForDontFailOnDataLossSuite`100 times, and it didn't fail, whereas it used to be flaky.

### CODE REVIEW

**Comment by brkyvz** [comment]
cc @zsxwing @jose-torres

**Comment by zsxwing** [comment]
LGTM pending tests. Could you add `[SS]` to your title?

**Comment by jose-torres** [comment]
Lgtm pending tests

**Comment by brkyvz** [comment]
thanks! merging to master

**Pull request closed without merging**
