### PR TITLE
[SPARK-14127][SQL] Makes 'DESC [EXTENDED|FORMATTED] <table>' support data source tables

### PR DESCRIPTION
**Pull request by liancheng**
## What changes were proposed in this pull request?

This is a follow-up of PR #12844. It makes the newly updated `DescribeTableCommand` to support data sources tables.
## How was this patch tested?

A test case is added to check `DESC [EXTENDED | FORMATTED] <table>` output.

### CODE REVIEW

**Comment by liancheng** [comment]
cc @yhuai

**Comment by yhuai** [comment]
LGTM. Can we also convert the schema/partitionColumn/bucketingColumn/sortingColumn strings to the ColumnColumn to display them nicely?

**Comment by liancheng** [comment]
The test failures was because of temporary tables: `SessionCatalog.getTableMetadata()` only supports persisted tables. The last commit added back support for temporary tables.

**Comment by liancheng** [comment]
@yhuai I'm going to add better support for data source tables in a follow-up PR.

**Comment by yhuai** [comment]
LGTM. Merging to master and branch 2.0.

**Pull request closed without merging**
