### PR TITLE
[SPARK-26321][SQL] Port HIVE-15297: Hive should not split semicolon within quoted string literals

### PR DESCRIPTION
**Pull request by wangyum**
## What changes were proposed in this pull request?

This pr port [HIVE-15297](https://issues.apache.org/jira/browse/HIVE-15297) to fix **spark-sql** should not split semicolon within quoted string literals.

## How was this patch tested?
unit tests and manual tests:
image

### CODE REVIEW

**Comment by gatorsmile** [comment]
Could you port the test cases from the original PR https://github.com/apache/spark/pull/23276

**Comment by HyukjinKwon** [comment]
@wangyum, if this is simply porting the fix, let's go ahead. can you resolve conflicts?

**Comment by wangyum** [comment]
@HyukjinKwon Done

**Comment by HyukjinKwon** [comment]
retest this please

**Review by HyukjinKwon — COMMENTED** [review]
@wangyum, I think you can merge if you're pretty confident on this.

**Comment by wangyum** [comment]
Thank you @HyukjinKwon I added another test case.

**Comment by wangyum** [comment]
retest this please

**Comment by wangyum** [comment]
Merged to master.

**Pull request closed without merging**
