### PR TITLE
[SPARK-35746][UI] Fix taskid in the stage page task event timeline

### PR DESCRIPTION
**Pull request by shahidki31**
### What changes were proposed in this pull request?
Task id is given incorrect in the timeline plot in Stage Page

### Why are the changes needed?
Map event timeline plots to correct task
**Before:**
image

**After**
image
### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Manually tested

### CODE REVIEW

**Comment by shahidki31** [comment]
cc @srowen @maropu Kindly review

**Review by srowen — APPROVED** [review]
LGTM pending tests.

**Comment by shahidki31** [comment]
Retest this please

**Review by sarutak — APPROVED** [review]

**Comment by sarutak** [comment]
Merged to `master`, `branch-3.1` and `branch-3.0`. Thanks!

**Comment by shahidki31** [comment]
Thanks @sarutak , @srowen for the reviews

**Comment by stczwd** [comment]
Hm, could any one tell me why we change taskIndex.attemptId to taskId.attempt? @shahidki31 @srowen @sarutak 
It seems we should either use `Task 0 (attempt 0)` or `Task 100`, not the `Task 100 (attempt 0)`

**Comment by stczwd** [comment]
Shall we revert this？

**Pull request closed without merging**
