### PR TITLE
[SPARK-48266][CONNECT] Move package object `org.apache.spark.sql.connect.dsl` to test directory

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
As discussed in https://github.com/apache/spark/pull/46559, the package object `org.apache.spark.sql.connect.dsl` is purely used for testing now, so this pr move it from `src/main/scala/org/apache/spark/sql/connect/dsl` to `src/test/scala/org/apache/spark/sql/connect/dsl`.

### Why are the changes needed?
The code only used for testing should be placed in the test directory.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass GitHub Actions

### Was this patch authored or co-authored using generative AI tooling?
No

### CODE REVIEW

**Comment by LuciferYang** [comment]
cc @zhengruifeng @amaliujia 
Let's test first

**Comment by HyukjinKwon** [comment]
can you write from where to where in the pr description

**Comment by LuciferYang** [comment]
> can you write from where to where in the pr description

done

**Review by HyukjinKwon — APPROVED** [review]
LGTM if it works

**Review by amaliujia — APPROVED** [review]

**Review by zhengruifeng — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by LuciferYang** [comment]
Thanks @HyukjinKwon @zhengruifeng @amaliujia

**Pull request closed without merging**
