### PR TITLE
[SPARK-11535][ML] handling empty string in StringIndexer

### PR DESCRIPTION
**Pull request by pravingadakh**
Replacing "" (not null) with string "EMPTY_STRING" in StringIndexer. Another approach is to use "0" (or next available integer), but it may have performance issues when input column has integer values say (0 to 100000). We can use another string to replace "" values if "EMPTY_STRING" is commonly used.

### CODE REVIEW

**Comment by pravingadakh** [comment]
@jkbradley Any updates on this?

**Comment by jkbradley** [comment]
@pravingadakh Apologies, but I may need to hold off on review for a bit as we prepare the 1.6 release.  Once that's out of the way, I'll be able to resume regular code review.  Thanks for being patient!

**Comment by thunterdb** [comment]
@pravingadakh sorry for the delay. Would you mind resolving the conflicts?

**Comment by pravingadakh** [comment]
@thunterdb Hi, I think I messed up while merging, thus closing this pull request creating a new one for the same.

**Comment by pravingadakh** [comment]
@thunterdb Please refer following PR. [https://github.com/apache/spark/pull/11575](PR)

**Pull request closed without merging**
