### PR TITLE
[EXAMPLES] fix typo.

### PR DESCRIPTION
**Pull request by fukuo33**

### CODE REVIEW

**Comment by srowen** [comment]
Good catch. Trivial fix and this would otherwise prevent this example from working. I'm merging into 1.3 and master.

**Comment by fukuo33** [comment]
Thanks.

**Comment by rnowling** [comment]
@srowen This affects the Spark 1.2.1 release as well.  (wasn't present in Spark 1.2.0 release.)  Please merge into 1.2 branch.

**Comment by rnowling** [comment]
Created JIRA here: https://issues.apache.org/jira/browse/SPARK-6167

**Pull request closed without merging**
