### PR TITLE
[SPARK-37017][SQL] Reduce the scope of synchronized to prevent potential deadlock

### PR DESCRIPTION
**Pull request by chenzhx**
### What changes were proposed in this pull request?

There is a `synchronize` block in `CatalogManager.currentNamespace` function.
This PR pulls `SessionCatalog.getCurrentDatabase` out from this `synchronize` block to prevent potential deadlock.

### Why are the changes needed?

In our case, we have implemented an external catalog, and there is a thread that directly calls SessionCatalog.getTempViewOrPermanentTableMetadata and holds the lock of SessionCatalog. It eventually goes into our external catalog, unfortunately, we then call some functions of SparkSession, e.g. sql. When it calls CatalogManager.currentNamespace, it tries to hold the lock of CatalogManager.

In the meantime, there are some query threads that execute sqls via DataFrame interface.

This is how deadlock occurs.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Currently spark cannot trigger this deadlock. So we wrote our own test to verify the effectiveness of this change.
In our external catalog code base, We write a UT to call SessionCatalog.getTempViewOrPermanentTableMetadata in one thread and while calling spark.sql("show databases") in other thread. Without this patch, a deadlock occurs and timeout exception was thrown. With this patch, UT works correctly.
We also tested this patch on the client's production environment, and the deadlock is fixed.

### CODE REVIEW

**Comment by AngersZhuuuu** [comment]
can you desc the deadlock case?

**Comment by chenzhx** [comment]
> can you desc the deadlock case?

The CatalogManager.currentNamespace function locks sessionCatalog.
And the SessionCatalog.getCurrentDatabase function locks currentDb.
These two methods lead to deadlock.

**Comment by baibaichen** [comment]
@cloud-fan It is what I talked to you about in the private chat.

It looks like Spark assume the lock order is `CalatogManager` => `SessionCatalog`.  We implement a new external catalog that could result in reverse order and hence deadlock.

To extract `v1SessionCatalog.getCurrentDatabase` from the  `CalatogManager`'s synchronized block could avoid deadlock as well as improving scalability.

**Comment by HyukjinKwon** [comment]
@baibaichen, existing unittests don't test the change. Can you guys describe how you tested this patch?

> It looks like Spark assume the lock order is `CalatogManager` => `SessionCatalog`.  We implement a new external catalog that could result in reverse order and hence deadlock.

It would be easier to follow if the reverse order was necessary in your implementation.

Also, please make sure describe them all in PR description (as guided in the PR template)

**Comment by chenzhx** [comment]
@cloud-fan

**Comment by cloud-fan** [comment]
ok to test

**Comment by HyukjinKwon** [comment]
Please elabourate problem and address my standing comment: https://github.com/apache/spark/pull/34292#issuecomment-945235842.

**Comment by baibaichen** [comment]
@HyukjinKwon Reducing the scope of a synchronized block is always a good idea.

I don't understand your question,  do you mean to add a test to show the deadlock? As @cloud-fan said the current Apache Spark can't hit this deadlock, so the current unit test is enough.

In our case, we have implemented an external catalog, and there is a thread that directly calls `SessionCatalog.getTempViewOrPermanentTableMetadata` and holds the lock of `SessionCatalog`. It eventually goes into our external catalog, unfortunately, we then call some functions of `SparkSession`,  e.g. `sql`. When it calls `CatalogManager.currentNamespace`, it tries to hold the lock of `CatalogManager`.

In the meantime, there are some query threads that execute sqls via `DataFrame` interface. 

This is how deadlock occurs.

**Comment by HyukjinKwon** [comment]
Yes I checked. Does the existing test cases cover this change?

**Comment by HyukjinKwon** [comment]
@chenzhx please describe how you tested this patch, and what user facing behaviour was made on the deadlock.

**Comment by HyukjinKwon** [comment]
Thanks @baibaichen and @chenzhx for addressing my comment.

**Pull request closed without merging**
