### PR TITLE
[SPARK-40424][CORE][TESTS] Refactor `ChromeUIHistoryServerSuite` to add UTs for RocksDB

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
`ChromeUIHistoryServerSuite` only test LevelDB backend now, this pr refactor the UTs of `ChromeUIHistoryServerSuite` to add UTs for RocksDB

### Why are the changes needed?
Add UTs related to RocksDB.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?

- Pass GA
- Manual test on Apple Silicon environment：

```
build/sbt -Dguava.version=31.1-jre -Dspark.test.webdriver.chrome.driver=/path/to/chromedriver -Dtest.default.exclude.tags="" "core/testOnly org.apache.spark.deploy.history.RocksBackendChromeUIHistoryServerSuite"
```

```
[info] RocksBackendChromeUIHistoryServerSuite:
Starting ChromeDriver 105.0.5195.52 (412c95e518836d8a7d97250d62b29c2ae6a26a85-refs/branch-heads/5195@{#853}) on port 54402
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
[info] - ajax rendered relative links are prefixed with uiRoot (spark.ui.proxyBase) (5 seconds, 387 milliseconds)
[info] Run completed in 20 seconds, 838 milliseconds.
[info] Total number of tests run: 1
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 1, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[success] Total time: 118 s (01:58), completed 2022-9-15 10:30:53
```

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @sarutak FYI

**Comment by LuciferYang** [comment]
rebased and updated pr description

**Comment by LuciferYang** [comment]
also cc @dongjoon-hyun due to the new test is for RocksDB

**Comment by LuciferYang** [comment]
friendly ping  @sarutak

**Review by dongjoon-hyun — COMMENTED** [review]
Sorry for being late. Could you rename the test suite class, @LuciferYang ?
```
- RocksBackendChromeUIHistoryServerSuite
+ RocksDBBackendChromeUIHistoryServerSuite
```

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. I tested this test-only PR manually. Merged to master.

```
$ build/sbt -Dguava.version=31.1-jre -Dspark.test.webdriver.chrome.driver=/opt/homebrew/bin/chromedriver -Dtest.default.exclude.tags="" "core/testOnly org.apache.spark.deploy.history.RocksDBBackendChromeUIHistoryServerSuite"
...
[info] RocksDBBackendChromeUIHistoryServerSuite:
Starting ChromeDriver 105.0.5195.52 (412c95e518836d8a7d97250d62b29c2ae6a26a85-refs/branch-heads/5195@{#853}) on port 64391
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
[info] - ajax rendered relative links are prefixed with uiRoot (spark.ui.proxyBase) (1 second, 736 milliseconds)
[info] Run completed in 4 seconds, 924 milliseconds.
[info] Total number of tests run: 1
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 1, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[success] Total time: 12 s, completed Sep 18, 2022, 6:28:18 PM
```

**Comment by dongjoon-hyun** [comment]
Thank you, @LuciferYang and @HyukjinKwon .

**Comment by LuciferYang** [comment]
> Sorry for being late. Could you rename the test suite class, @LuciferYang ?
> 
> ```
> - RocksBackendChromeUIHistoryServerSuite
> + RocksDBBackendChromeUIHistoryServerSuite
> ```

Thanks for your help  @dongjoon-hyun ~

**Pull request closed without merging**
