### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by tynan-cr**
## What changes were proposed in this pull request?

Small typo fixes in Pyspark. These were the only ones I stumbled across after looking around for a while.

## How was this patch tested?

Manually

Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
ok to test

**Comment by HyukjinKwon** [comment]
It's okie but mind taking another look and fix them in a batch while we are here, @tynan-cr?

**Comment by tynan-cr** [comment]
Yes, I will add more if I find anything!

**Comment by kiszk** [comment]
#22070 addresses more typo.

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
