### PR TITLE
[SPARK-39743][DOCS] Improve `spark.io.compression.(lz4|snappy|zstd)` conf scope description

### PR DESCRIPTION
**Pull request by zzzzming95**
### What changes were proposed in this pull request?

Updated some `spark.io.compression` configuration descriptions to clarify parameter application scope.

### Why are the changes needed?

Users are easily confused and mistakenly think that these parameters can be applied to sparksql.

For example, the user wants to write a parquet file and set some compression configurations such as zstd level (as the following code). In the original document, user found that there is a `spark.io.compression.zstd.level` in the relevant configuration, which seems to be the desired configuration, but after using it, it is found that it does not take effect, which will make users confused.

```
    sparkSession.sessionState.newHadoopConfWithOptions(   
      "spark.io.compression.zstd.level" -> "10"
    )

    df.coalesce(1).write.parquet("file:///home/test_data/nn_parq_10")
```

### Does this PR introduce _any_ user-facing change?

no

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
@zzzzming95 mind filing a JIRA please?

**Review by dongjoon-hyun — COMMENTED** [review]
Could you elaborate more about the SQL cases you mentioned? For example, about how new sentence `This configuration only applies to spark.io.compression.codec` can help those users?
> Users are easily confused and mistakenly think that these parameters can be applied to sparksql.

**Comment by dongjoon-hyun** [comment]
@zzzzming95 . You should put them into the PR description because PR description will become a permanent commit message while JIRA issue is not . Each commit had better be complete.
> Detailed discussion can be viewed in jira : https://issues.apache.org/jira/browse/SPARK-39743

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @zzzzming95 . Merged to master for Apache Spark 3.4.0 documentation.

Welcome to the Apache Spark community.

**Pull request closed without merging**
