### PR TITLE
[SPARK-29686][ML] LinearSVC should persist instances if needed

### PR DESCRIPTION
**Pull request by zhengruifeng**
### What changes were proposed in this pull request?
persist the input if needed

### Why are the changes needed?
training with non-cached dataset will hurt performance

### Does this PR introduce any user-facing change?
No

### How was this patch tested?
existing tests

### CODE REVIEW

**Comment by zhengruifeng** [comment]
retest this please

**Review by srowen — APPROVED** [review]
Looks OK pending tests

**Comment by srowen** [comment]
Hm, that SparkR failure is unrelated. Let's see if we can get it resolved, for a day or two.

**Comment by huaxingao** [comment]
One general question: what is the criteria to add the persistence support? I took a quick look of the ml code, seems some of them have the persistence support, some of them don't. For example, in classification, ```LogisticRegression```, ```OneVsRest``` and this ```LinearSVC``` have persistence support, but others don't. I didn't quite figure out when we need to persist the data.

**Comment by zhengruifeng** [comment]
@huaxingao I think we should persist dataset if it will be used several times.

> For example, in classification, LogisticRegression, OneVsRest and this LinearSVC have persistence support, but others don't.

`DecisionTreeClassifier`,`GBTClassifier`,`RandomForestClassifier` persist a transformed dataset named `baggedInput` internally.
`MultilayerPerceptronClassifier` persist the input in `Layer.scala`.
`NaiveBayes` normally only need one pass (sometime it needs twice).

**Comment by zhengruifeng** [comment]
retest this please

**Comment by huaxingao** [comment]
LGTM

**Comment by zhengruifeng** [comment]
merged to master, thanks @srowen @huaxingao !

**Pull request closed without merging**
