### PR TITLE
[SPARK-13238][Core] Add ganglia dmax parameter

### PR DESCRIPTION
**Pull request by ekasitk**
The current ganglia reporter doesn't set metric expiration time (dmax). The metrics of all finished applications are indefinitely left displayed in ganglia web. The dmax parameter allows user to set the lifetime of the metrics. The default value is 0 for compatibility with previous versions.

### CODE REVIEW

**Comment by holdenk** [comment]
@ekasitk could you maybe update this against master (the ganglia code has been moved around a bit)? Also maybe the Shepard for this JIRA could take look ( @pwendell )  once that is done.

**Comment by ekasitk** [comment]
@holdenk @pwendell I've updated it with master.

**Comment by vanzin** [comment]
ok to test

**Comment by vanzin** [comment]
Merging to master.

**Pull request closed without merging**
