### PR TITLE
[SPARK-5846] Correctly set job description and pool for SQL jobs

### PR DESCRIPTION
**Pull request by kayousterhout**
This is #4630 but modified for the 1.2 branch, because I'm guessing it makes sense to fix this issue in that branch (again, unless I missed something obvious here...)

### CODE REVIEW

**Comment by marmbrus** [comment]
test this please

**Comment by liancheng** [comment]
LGTM, thanks! Merging into branch-1.2.

**Comment by marmbrus** [comment]
Mind closing this now?

**Pull request closed without merging**
