### PR TITLE
[SPARK-16872][ML][WIP] Gaussian Naive Bayes Classifier

### PR DESCRIPTION
**Pull request by zhengruifeng**
## What changes were proposed in this pull request?

implement Gaussian NB in ML
## How was this patch tested?

local test in spark-shell, comparing to Scikit-Learn
added unit tests

### CODE REVIEW

**Comment by zhengruifeng** [comment]
cc @yanboliang @MLnick Can you please review this in spare time?

**Comment by sethah** [comment]
Was there some discussion as to whether GaussianNB should be part of the NaiveBayes estimator or its own estimator? It seems the semantics are different enough between multinomial NB and Gaussian NB to at least warrant discussion. The meaning `theta` matrix in Gaussian NB vs multinomial is very different in this patch - one is matrix of Gaussian distribution paramters, and the other is a matrix of class conditional probabilities. Also, some params only apply to one and not the other. My apologies if I have missed this conversation somewhere. Thanks!

**Comment by MLnick** [comment]
I tend to agree with Seth on this - the gaussian case is different enough that it could be separate.

Though in terms of the estimator, from a public-facing API perspective it is one param that is unused, so it it's not that big a deal to be unified.

However in terms of the model, I really, really don't like the hack of putting the `theta` and `sigma` into one matrix. That leaves us with either creating a new estimator/model combo (let's see how much code duplication that involves), or having a `def getSigma` or a new val `sigma` that is only used for Gaussian. Not super pretty...

**Comment by zhengruifeng** [comment]
@yanboliang  what is your opioion?

**Comment by zhengruifeng** [comment]
@MLnick @sethah Thanks for your review. This PR now is just like what I am using in work. I agree that it will bring some inconvenience to merge `theta` and `sigma` together. I will change it to another estimator if needed.

**Comment by yanboliang** [comment]
I'm against to merge ```theta``` and ```sigma``` together, it should be two individual variables of model. To the question that whether GaussianNB should be part of the ```NaiveBayes``` estimator, I'm ambivalent between these two opinions but I'm more prefer to add another variable ```sigma``` to the model. When it's a gaussian NB model, both ```theta``` and ```sigma``` are effective; otherwise, only ```theta``` is valid. We keep private constructor for all models, so add another variable is not a big issue. I'm open to hear others' thoughts. cc @jkbradley

**Comment by zhengruifeng** [comment]
I tend to make GaussianNB as a special `modelType` option in current NB. 
However, there are significant differences:
1, 'theta' matrix is used to store means
2, extra `sigma` matrix needed to store variance
3, param `smoothing` has no effert, according to [sklearn's implementation](http://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.GaussianNB.html#sklearn.naive_bayes.GaussianNB). 

To keep current NB design, I think there are two methods to include GaussianNB:
1, merge `theta` and `sigma` together (you are all against this)
2, update `NaiveBayesModel` and include `sigma` as a extra matrix, and `sigma` is only meaningful when using GaussianNB

I'm open on this issue, and I will update this PR when we come to a conclusion.

**Comment by zhengruifeng** [comment]
Jenkins, retest this please.

**Comment by zhengruifeng** [comment]
@sethah @MLnick @yanboliang Thanks for your comments, and  I will work to make GNB a separated classifier.

**Comment by zhengruifeng** [comment]
Jenkins, retest this please

**Comment by zhengruifeng** [comment]
@jkbradley What's your opinion about whether GNB should be a separated Classifier or a modeltype in existing NB?

**Pull request closed without merging**
