### PR TITLE
[SPARK-28527][FOLLOW-UP][SQL][TEST] Add guides for ThriftServerQueryTestSuite

### PR DESCRIPTION
**Pull request by wangyum**
### What changes were proposed in this pull request?
This PR add guides for `ThriftServerQueryTestSuite`.

### Why are the changes needed?
Add guides

### Does this PR introduce any user-facing change?
No.

### How was this patch tested?
N/A

### CODE REVIEW

**Comment by wangyum** [comment]
cc @HyukjinKwon @MaxGekk @beliefer

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Merged to master. 
Thank you, @wangyum .

**Review by HyukjinKwon — COMMENTED** [review]
LGTM. thank you for documenting this.

**Comment by beliefer** [comment]
LGTM. I learned it.

**Pull request closed without merging**
