### PR TITLE
[SPARK-34952][SQL][FOLLOWUP] Move aggregates to a separate package

### PR DESCRIPTION
**Pull request by huaxingao**
### What changes were proposed in this pull request?
Add `aggregate` package under `sql/catalyst/src/main/java/org/apache/spark/sql/connector/expressions` and move all the aggregates (e.g. `Count`, `Max`, `Min`, etc.) there.

### Why are the changes needed?
Right now these aggregates are under `sql/catalyst/src/main/java/org/apache/spark/sql/connector/expressions`. It looks OK now, but we plan to add a new `filter` package under `expressions` for all the DSV2 filters. It will look strange that filters have their own package, but aggregates don't.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Existing tests

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Hi, @huaxingao .
Just a question. Do you want this at branch-3.2?
- If you do, please ping @gengliangwang 
- If not, you should not share the same JIRA id. The fixed version of SPARK-34952 is 3.2.0 and this will land only at 3.3.0.

**Comment by huaxingao** [comment]
@dongjoon-hyun yes, this needs to be in 3.2.

**Comment by huaxingao** [comment]
cc @gengliangwang @cloud-fan @viirya

**Comment by gengliangwang** [comment]
@huaxingao yes, +1 for have this one in 3.2

**Review by viirya — APPROVED** [review]

**Comment by viirya** [comment]
But I think this is only in 3.2 if the current RC fails?

**Comment by huaxingao** [comment]
> But I think this is only in 3.2 if the current RC fails?

There is a -1 from Wu Yi

**Comment by viirya** [comment]
Then pending CI.

**Comment by viirya** [comment]
Thanks! Merging to master/3.2.

**Comment by huaxingao** [comment]
Thank you all!

**Comment by dongjoon-hyun** [comment]
Thank you, @huaxingao and all. :)

**Pull request closed without merging**
