### PR TITLE
[SPARK-40505][K8S] Remove min heap setting for executor in entrypoint.sh

### PR DESCRIPTION
**Pull request by bryanck**
### What changes were proposed in this pull request?

This PR removes the min heap setting (`-Xms`) from the JVM args when starting the executor process.

### Why are the changes needed?

Removing the min heap setting is consistent with the settings for the YARN executor process and allows the JVM to reduce the heap when needed to reduce memory consumption.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

We have this change deployed in our production environment to solve for OOM kills we were experiencing when running in K8S but were not seeing when running in YARN.

### CODE REVIEW

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
Hi, @bryanck . Thank you for making a PR. We know that K8s is more rigoursly managing the manager than YARN. However, I don't think this addresses your issue correctly. I'd recommend to set `spark.executor.memoryOverhead` explicitly.
> We have this change deployed in our production environment to solve for OOM kills we were experiencing when running in K8S but were not seeing when running in YARN.

**Comment by bryanck** [comment]
Thanks for pointing out memory settings @dongjoon-hyun , the goal of this PR is to bring more consistent memory usage behavior between YARN and k8s rather than to solve for a specific use case. If the community has determined a fixed heap size is optimal, then that should be set for YARN as well, unless there is some reasoning for the difference.

**Comment by dongjoon-hyun** [comment]
You can propose to YARN committers as a YARN PR, but I believe we don't want to make any surprise to the existing YARN users when there is no issue there like you mentioned. Although consistency is good in general, there is a reason why we have separate resource manager modules like K8s, YARN, Mesos.

**Comment by dongjoon-hyun** [comment]
Let me close this PR for now. We can continue our discussion on this PR.

**Comment by bryanck** [comment]
I don't follow how a YARN PR will help? AFAIK, the executor heap is [set by Spark](https://github.com/apache/spark/blob/07061f1a07a96f59ae42c9df6110eb784d2f3dab/resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/ExecutorRunnable.scala#L132)

**Comment by dongjoon-hyun** [comment]
I mean K8s module has been choosing the best practice in K8s control plane and I believe YARN module is the same situation I guess.
> You mentioned there is a reason for the different modules, can you explain the reason k8s is configured to use a fixed heap size and YARN does not?

I seems that you misunderstand. Your PR description claim like that, not me. This is what you wrote, `settings for the YARN executor process and allows the JVM to reduce the heap when needed to reduce memory consumption.`, in this PR description, isn't it?
> I don't follow how a YARN PR will help?

**Comment by bryanck** [comment]
I don't believe it is best practice to set a fixed JVM heap on k8s and not on YARN. If that is the case, I would be very interested in reading more about that.

**Pull request closed without merging**
