### PR TITLE
[SPARK-50380][SQL][TESTS][FOLLOWUP] Enable ANSI for conditional branches with error expression test

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This is a follow-up to recover non-ANSI CI.
- #48918

### Why are the changes needed?

The original PR broke non-ANSI CI because the test case assumes ANSI setting.

- https://github.com/apache/spark/actions/runs/11964792566
- https://github.com/apache/spark/actions/runs/11982859814

### Does this PR introduce _any_ user-facing change?

No, this is a test-only change.

### How was this patch tested?

Manual tests.

**BEFORE**

```
$ SPARK_ANSI_SQL_MODE=false build/sbt "catalyst/testOnly *.ReorderAssociativeOperatorSuite -- -z SPARK-50380"
...
[info] *** 1 TEST FAILED ***
[error] Failed tests:
[error] 	org.apache.spark.sql.catalyst.optimizer.ReorderAssociativeOperatorSuite
[error] (catalyst / Test / testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 8 s, completed Nov 23, 2024, 11:50:45 AM
```

**AFTER**

```
$ SPARK_ANSI_SQL_MODE=false build/sbt "catalyst/testOnly *.ReorderAssociativeOperatorSuite -- -z SPARK-50380"
...
[info] ReorderAssociativeOperatorSuite:
[info] - SPARK-50380: conditional branches with error expression (508 milliseconds)
[info] Run completed in 1 second, 413 milliseconds.
[info] Total number of tests run: 1
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 1, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[success] Total time: 11 s, completed Nov 23, 2024, 11:51:34 AM
```

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
cc @cloud-fan and @viirya

**Comment by viirya** [comment]
> This is fine normally, but we added a new contract in ConstantFolding with https://github.com/apache/spark/pull/36468 , due to the introduction of ANSI mode and we don't want to fail eagerly for expressions within conditional branches. ReorderAssociativeOperator does not follow this contract.

Okay, I think the behavior is only for ANSI mode, according to the PR description.

**Review by viirya — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @viirya

**Comment by dongjoon-hyun** [comment]
Merged to master to recover non-ANSI CI.
- https://github.com/apache/spark/actions/workflows/build_non_ansi.yml

**Comment by dongjoon-hyun** [comment]
For the record, `catalyst` test pipeline is recovered successfully.
- https://github.com/apache/spark/actions/runs/12001580128/job/33452303617

**Comment by viirya** [comment]
Thank you @dongjoon-hyun

**Comment by cloud-fan** [comment]
thank you @dongjoon-hyun !

**Pull request closed without merging**
