### PR TITLE
[SPARK-8199][SQL] follow up; revert change in test

### PR DESCRIPTION
**Pull request by tarekbecker**
@rxin / @davies 

Sorry for that unnecessary change. And thanks again for all your support!

### CODE REVIEW

**Comment by davies** [comment]
@tarekauel If Calendar is created inside for-loop (i), we should use `i`, otherwise use 1, is it correct?

**Comment by davies** [comment]
there are four more places (below that) need to be fixed.

**Comment by davies** [comment]
After this rush, you should have more rest, also me. :)

**Comment by tarekauel** [comment]
Now it's right, isn't it?

**Comment by davies** [comment]
LGTM.

**Comment by rxin** [comment]
Thanks - I've merged this.

**Pull request closed without merging**
