### PR TITLE
[SPARK-37555][TEST][FOLLOWUP] Increase timeout of CLI test `spark-sql should pass last unclosed comment to backend`

### PR DESCRIPTION
**Pull request by AngersZhuuuu**
### What changes were proposed in this pull request?
Fix flaky test  `spark-sql should pass last unclosed comment to backend`,
it's timeout should be caused by unstable GA env, so I increase timeout time for the test

### Why are the changes needed?
Fix flaky test.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Not need

### CODE REVIEW

**Comment by LuciferYang** [comment]
flaky test?

**Comment by AngersZhuuuu** [comment]
> flaky test?

yea

**Comment by AngersZhuuuu** [comment]
@cloud-fan Triggered  six times, the flaky test not failed.

**Comment by cloud-fan** [comment]
@AngersZhuuuu can you fill the PR description? Then we can merge it.

**Comment by AngersZhuuuu** [comment]
> @AngersZhuuuu can you fill the PR description? Then we can merge it.

done

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Pull request closed without merging**
