### PR TITLE
[SPARK-13646] [MLlib] QuantileDiscretizer counts dataset twice in get…

### PR DESCRIPTION
**Pull request by eliasah**
## What changes were proposed in this pull request?

It avoids counting the dataframe twice.

### CODE REVIEW

**Comment by srowen** [comment]
Jenkins test this please

**Comment by eliasah** [comment]
I'm not sure why the *scala style tests" fails.

**Comment by srowen** [comment]
It's in the test output -- stray space before the comma :)

**Comment by eliasah** [comment]
Ok, sorry this is my first PR. Should I correct, push and pr again ?

**Comment by srowen** [comment]
Yes just push a tiny commit to the same branch

**Comment by eliasah** [comment]
Done !

**Comment by srowen** [comment]
Jenkins, retest this please

**Comment by eliasah** [comment]
Now that the tests passed. How can this be merged ?

**Comment by srowen** [comment]
Things may take a day or more to get a response given workloads and timezones. I often leave things open a couple days just to see if there are comments. This is so straightforward that I'm comfortable merging it.

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
