### PR TITLE
[SPARK-19225][SQL]round decimal return normal value but not null

### PR DESCRIPTION
**Pull request by discipleforteen**
## What changes were proposed in this pull request?

in https://issues.apache.org/jira/browse/SPARK-19225,
change the round decimal function. select round(4.4, 2) can return 4.4 , not return null when round scale is larger than decimal scale

## How was this patch tested?

Jeckins

Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Comment by rxin** [comment]
Can you add a test?

**Comment by rxin** [comment]
Also I think we need to update the code gen path as well.

**Comment by discipleforteen** [comment]
ok. i will try to update code gen and MathFunctionsSuite.scala

**Comment by discipleforteen** [comment]
@AmplabJenkins @rxin

**Comment by discipleforteen** [comment]
how about cast constant 4.4 to double instead of decimal like spark 1.x. @rxin

**Pull request closed without merging**
