### PR TITLE
[SPARK-37718][MINOR][DOCS] Demo sql is incorrect

### PR DESCRIPTION
**Pull request by wooplevip**
### What changes were proposed in this pull request?

Modify `SELECT * FROM person GROUP BY age HAVING max(age) > 18;`
to
`SELECT age, count(*) FROM person GROUP BY age HAVING max(age) > 18;`

### Why are the changes needed?

Making the demo sql running correctly.

### Does this PR introduce any user-facing change?

NO

### How was this patch tested?

cd docs
SKIP_API=1 bundle exec jekyll build

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
ok to test

**Comment by HyukjinKwon** [comment]
Mind enabling GitHub Actions in your forked repository? see also https://github.com/apache/spark/pull/34992/checks?check_run_id=4614179658

**Comment by wooplevip** [comment]
@HyukjinKwon  Sorry, I have enabled just now. Should I submit PR again?

**Comment by HyukjinKwon** [comment]
You can simply rebase or push an empty commit :-).

**Review by srowen — APPROVED** [review]

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
