### PR TITLE
[SPARK-23911][SQL][FOLLOW-UP] Fix examples of aggregate function.

### PR DESCRIPTION
**Pull request by ueshin**
## What changes were proposed in this pull request?

This pr is a follow-up pr of #21982 and fixes the examples.

## How was this patch tested?

Existing tests.

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]
LGTM too

**Comment by cloud-fan** [comment]
LGTM

**Comment by kiszk** [comment]
LGTM

**Comment by ueshin** [comment]
Thanks! merging to master.

**Pull request closed without merging**
