### PR TITLE
[SPARK-44247][BUILD] Upgrade Arrow to 13.0.0

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to upgrade arrow from 12.0.1 to 13.0.0.

### Why are the changes needed?
1. Arrow 12.0.1 VS 13.0.0
https://github.com/apache/arrow/compare/apache-arrow-12.0.1...apache-arrow-13.0.0

2. Arrow 13.0.0 is the first version to support Java 21.
    - https://github.com/apache/arrow/pull/36370

When arrow version 12.0.1 running on Java21, the following error occurred:
```
java.lang.UnsupportedOperationException: sun.misc.Unsafe or java.nio.DirectByteBuffer.<init>(long, int) not available
       org.apache.arrow.memory.util.MemoryUtil.directBuffer(MemoryUtil.java:167)
       org.apache.arrow.memory.ArrowBuf.getDirectBuffer(ArrowBuf.java:228)
       org.apache.arrow.memory.ArrowBuf.nioBuffer(ArrowBuf.java:223)
       org.apache.arrow.vector.ipc.ReadChannel.readFully(ReadChannel.java:87)
       org.apache.arrow.vector.ipc.message.MessageSerializer.readMessageBody(MessageSerializer.java:727)
       org.apache.arrow.vector.ipc.message.MessageChannelReader.readNext(MessageChannelReader.java:67)
       org.apache.arrow.vector.ipc.ArrowStreamReader.loadNextBatch(ArrowStreamReader.java:145)
```
After this PR, we can try to enable netty related testing in Java21.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
- Pass GA.

### CODE REVIEW

**Comment by LuciferYang** [comment]
We need upgrade arrow 13.0 and netty 4.1.94+ together

**Comment by LuciferYang** [comment]
cc @dongjoon-hyun seems arrow 13.0.0 released, we can re-enable arrow-based test case after this one for Java 21 :)

**Comment by LuciferYang** [comment]
@panbingkun It appears it hasn’t been published to the Maven Central Repository yet. We can testing it using asf-staging first :)

**Comment by panbingkun** [comment]
> @panbingkun It appears it hasn’t been published to the Maven Central Repository yet. We can testing it using asf-staging first :)

Thanks @LuciferYang , let's test it in advance. 😄

**Comment by panbingkun** [comment]
image

**Comment by LuciferYang** [comment]
@panbingkun 
1. Please update the pr title due to we upgrade both netty & arrow in this one
2. Please update the PR description and add an explanation for "why we need to upgrade these two dependencies in the one pr?", such as what errors will occur if we only upgrade arrow, and what errors will occur if we only upgrade netty (although I know this is because netty has changed a developer API that arrow is using). It is best to list the pr links or issue links related to netty and arrow

**Comment by panbingkun** [comment]
Let's hold it first because when I wrote this PR, Netty had already released version 4.1.96.Final
image
https://github.com/netty/netty/releases/tag/netty-4.1.96.Final

**Comment by LuciferYang** [comment]
@panbingkun Only upgrade arrow to 13.0.0, the netty version is 4.1.93.Final, the test failed will like 

```
java.lang.NoSuchMethodError: io.netty.buffer.PooledByteBufAllocatorL$InnerAllocator.threadCache()Lio/netty/buffer/PoolArenasCache;
    at io.netty.buffer.PooledByteBufAllocatorL$InnerAllocator.newDirectBufferL(PooledByteBufAllocatorL.java:164)
    at io.netty.buffer.PooledByteBufAllocatorL$InnerAllocator.directBuffer(PooledByteBufAllocatorL.java:214)
    at io.netty.buffer.PooledByteBufAllocatorL.allocate(PooledByteBufAllocatorL.java:58)
    at org.apache.arrow.memory.NettyAllocationManager.<init>(NettyAllocationManager.java:77)
    at org.apache.arrow.memory.NettyAllocationManager.<init>(NettyAllocationManager.java:84)
    at org.apache.arrow.memory.NettyAllocationManager$1.create(NettyAllocationManager.java:34)
    at org.apache.arrow.memory.BaseAllocator.newAllocationManager(BaseAllocator.java:355)
    at org.apache.arrow.memory.BaseAllocator.newAllocationManager(BaseAllocator.java:350)
    at org.apache.arrow.memory.BaseAllocator.bufferWithoutReservation(BaseAllocator.java:338)
    at org.apache.arrow.memory.BaseAllocator.buffer(BaseAllocator.java:316)
    at org.apache.arrow.memory.BaseAllocator.buffer(BaseAllocator.java:280)
    at org.apache.arrow.vector.BaseVariableWidthVector.allocateBytes(BaseVariableWidthVector.java:462)
    at org.apache.arrow.vector.BaseVariableWidthVector.allocateNew(BaseVariableWidthVector.java:420)
    at org.apache.arrow.vector.BaseVariableWidthVector.allocateNew(BaseVariableWidthVector.java:380)
    at org.apache.spark.sql.execution.arrow.ArrowWriter$.$anonfun$create$1(ArrowWriter.scala:44)
    at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
    at scala.collection.Iterator.foreach(Iterator.scala:943)
    at scala.collection.Iterator.foreach$(Iterator.scala:943)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
    at scala.collection.IterableLike.foreach(IterableLike.scala:74)
    at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
    at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
    at scala.collection.TraversableLike.map(TraversableLike.scala:286)
    at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
    at scala.collection.AbstractTraversable.map(Traversable.scala:108)
    at org.apache.spark.sql.execution.arrow.ArrowWriter$.create(ArrowWriter.scala:43)
    at org.apache.spark.sql.execution.arrow.ArrowConverters$ArrowBatchIterator.<init>(ArrowConverters.scala:93)
    at org.apache.spark.sql.execution.arrow.ArrowConverters$ArrowBatchWithSchemaIterator.<init>(ArrowConverters.scala:138)
    at org.apache.spark.sql.execution.arrow.ArrowConverters$$anon$1.<init>(ArrowConverters.scala:226)
    at org.apache.spark.sql.execution.arrow.ArrowConverters$.createEmptyArrowBatch(ArrowConverters.scala:224)
    at org.apache.spark.sql.connect.planner.SparkConnectPlanner.handleSqlCommand(SparkConnectPlanner.scala:2430)
    at org.apache.spark.sql.connect.planner.SparkConnectPlanner.process(SparkConnectPlanner.scala:2374)
    at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.handleCommand(ExecuteThreadRunner.scala:170)
    at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.$anonfun$executeInternal$1(ExecuteThreadRunner.scala:146)
    at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.$anonfun$executeInternal$1$adapted(ExecuteThreadRunner.scala:124)
    at org.apache.spark.sql.connect.service.SessionHolder.$anonfun$withSession$2(SessionHolder.scala:192)
    at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
    at org.apache.spark.sql.connect.service.SessionHolder.$anonfun$withSession$1(SessionHolder.scala:192)
    at org.apache.spark.JobArtifactSet$.withActiveJobArtifactState(JobArtifactSet.scala:94)
    at org.apache.spark.sql.connect.service.SessionHolder.$anonfun$withContextClassLoader$1(SessionHolder.scala:179)
    at org.apache.spark.util.Utils$.withContextClassLoader(Utils.scala:199)
    at org.apache.spark.sql.connect.service.SessionHolder.withContextClassLoader(SessionHolder.scala:178)
    at org.apache.spark.sql.connect.service.SessionHolder.withSession(SessionHolder.scala:191)
    at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.executeInternal(ExecuteThreadRunner.scala:124)
    at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.org$apache$spark$sql$connect$execution$ExecuteThreadRunner$$execute(ExecuteThreadRunner.scala:79)
    at org.apache.spark.sql.connect.execution.ExecuteThreadRunner$ExecutionThread.run(ExecuteThreadRunner.scala:188)
```

I think we can supplement this section in the pr description.

- Only upgrade netty: 

```
java.lang.NoSuchMethodError: io.netty.buffer.PooledByteBufAllocatorL$InnerAllocator.threadCache()Lio/netty/buffer/PoolThreadCache;
```

- Only upgrade arrow:

```
java.lang.NoSuchMethodError: io.netty.buffer.PooledByteBufAllocatorL$InnerAllocator.threadCache()Lio/netty/buffer/PoolArenasCache;
```

then, we can say that both dependencies must be upgraded simultaneously

**Comment by panbingkun** [comment]
> @panbingkun Only upgrade arrow to 13.0.0, the netty version is 4.1.93.Final, the test failed will like
> 
> ```
> java.lang.NoSuchMethodError: io.netty.buffer.PooledByteBufAllocatorL$InnerAllocator.threadCache()Lio/netty/buffer/PoolArenasCache;
>     at io.netty.buffer.PooledByteBufAllocatorL$InnerAllocator.newDirectBufferL(PooledByteBufAllocatorL.java:164)
>     at io.netty.buffer.PooledByteBufAllocatorL$InnerAllocator.directBuffer(PooledByteBufAllocatorL.java:214)
>     at io.netty.buffer.PooledByteBufAllocatorL.allocate(PooledByteBufAllocatorL.java:58)
>     at org.apache.arrow.memory.NettyAllocationManager.<init>(NettyAllocationManager.java:77)
>     at org.apache.arrow.memory.NettyAllocationManager.<init>(NettyAllocationManager.java:84)
>     at org.apache.arrow.memory.NettyAllocationManager$1.create(NettyAllocationManager.java:34)
>     at org.apache.arrow.memory.BaseAllocator.newAllocationManager(BaseAllocator.java:355)
>     at org.apache.arrow.memory.BaseAllocator.newAllocationManager(BaseAllocator.java:350)
>     at org.apache.arrow.memory.BaseAllocator.bufferWithoutReservation(BaseAllocator.java:338)
>     at org.apache.arrow.memory.BaseAllocator.buffer(BaseAllocator.java:316)
>     at org.apache.arrow.memory.BaseAllocator.buffer(BaseAllocator.java:280)
>     at org.apache.arrow.vector.BaseVariableWidthVector.allocateBytes(BaseVariableWidthVector.java:462)
>     at org.apache.arrow.vector.BaseVariableWidthVector.allocateNew(BaseVariableWidthVector.java:420)
>     at org.apache.arrow.vector.BaseVariableWidthVector.allocateNew(BaseVariableWidthVector.java:380)
>     at org.apache.spark.sql.execution.arrow.ArrowWriter$.$anonfun$create$1(ArrowWriter.scala:44)
>     at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
>     at scala.collection.Iterator.foreach(Iterator.scala:943)
>     at scala.collection.Iterator.foreach$(Iterator.scala:943)
>     at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
>     at scala.collection.IterableLike.foreach(IterableLike.scala:74)
>     at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
>     at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
>     at scala.collection.TraversableLike.map(TraversableLike.scala:286)
>     at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
>     at scala.collection.AbstractTraversable.map(Traversable.scala:108)
>     at org.apache.spark.sql.execution.arrow.ArrowWriter$.create(ArrowWriter.scala:43)
>     at org.apache.spark.sql.execution.arrow.ArrowConverters$ArrowBatchIterator.<init>(ArrowConverters.scala:93)
>     at org.apache.spark.sql.execution.arrow.ArrowConverters$ArrowBatchWithSchemaIterator.<init>(ArrowConverters.scala:138)
>     at org.apache.spark.sql.execution.arrow.ArrowConverters$$anon$1.<init>(ArrowConverters.scala:226)
>     at org.apache.spark.sql.execution.arrow.ArrowConverters$.createEmptyArrowBatch(ArrowConverters.scala:224)
>     at org.apache.spark.sql.connect.planner.SparkConnectPlanner.handleSqlCommand(SparkConnectPlanner.scala:2430)
>     at org.apache.spark.sql.connect.planner.SparkConnectPlanner.process(SparkConnectPlanner.scala:2374)
>     at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.handleCommand(ExecuteThreadRunner.scala:170)
>     at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.$anonfun$executeInternal$1(ExecuteThreadRunner.scala:146)
>     at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.$anonfun$executeInternal$1$adapted(ExecuteThreadRunner.scala:124)
>     at org.apache.spark.sql.connect.service.SessionHolder.$anonfun$withSession$2(SessionHolder.scala:192)
>     at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
>     at org.apache.spark.sql.connect.service.SessionHolder.$anonfun$withSession$1(SessionHolder.scala:192)
>     at org.apache.spark.JobArtifactSet$.withActiveJobArtifactState(JobArtifactSet.scala:94)
>     at org.apache.spark.sql.connect.service.SessionHolder.$anonfun$withContextClassLoader$1(SessionHolder.scala:179)
>     at org.apache.spark.util.Utils$.withContextClassLoader(Utils.scala:199)
>     at org.apache.spark.sql.connect.service.SessionHolder.withContextClassLoader(SessionHolder.scala:178)
>     at org.apache.spark.sql.connect.service.SessionHolder.withSession(SessionHolder.scala:191)
>     at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.executeInternal(ExecuteThreadRunner.scala:124)
>     at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.org$apache$spark$sql$connect$execution$ExecuteThreadRunner$$execute(ExecuteThreadRunner.scala:79)
>     at org.apache.spark.sql.connect.execution.ExecuteThreadRunner$ExecutionThread.run(ExecuteThreadRunner.scala:188)
> ```
> 
> I think we can supplement this section in the pr description.
> 
> * Only upgrade netty:
> 
> ```
> java.lang.NoSuchMethodError: io.netty.buffer.PooledByteBufAllocatorL$InnerAllocator.threadCache()Lio/netty/buffer/PoolThreadCache;
> ```
> 
> * Only upgrade arrow:
> 
> ```
> java.lang.NoSuchMethodError: io.netty.buffer.PooledByteBufAllocatorL$InnerAllocator.threadCache()Lio/netty/buffer/PoolArenasCache;
> ```
> 
> then, we can say that both dependencies must be upgraded simultaneously

Done.

**Comment by LuciferYang** [comment]
@panbingkun if arrow 13.0.0 is target to support Netty 4.1.96, then it is no longer coupled with the upgrade of Arrow. Can you create a separate PR to upgrade Netty to 4.1.96 first?

**Comment by panbingkun** [comment]
> then it is no longer coupled with the upgrade of Arrow. Can you create a separate PR to upgrade Netty to 4.1.96 first?

Okay, let me do it.

**Comment by panbingkun** [comment]
Last week, I submitted a PR(https://github.com/apache/arrow/pull/36926) on netty arrow memory to make `netty arrow memory 13.0.0` run well with `the netty newest version 4.1.96.Final`.
Based on my limited understanding, this PR will be released with the official version of `netty arrow memory 13.0.0`.

**Comment by dongjoon-hyun** [comment]
Thank you for working on this, @panbingkun and @LuciferYang .
I saw the tag was created 5 hours ago. Please let us know again when the artifacts become available.
- https://github.com/apache/arrow/releases/tag/apache-arrow-13.0.0

**Comment by dongjoon-hyun** [comment]
BTW, I updated the PR title with SPARK-44247 instead of SPARK-44563.

**Comment by LuciferYang** [comment]
Yes, arrow `13.0.0-rc2` has been released, and this version should be able to support Netty <=4.1.93 and >=4.1.96. We can remove the Netty part from this pr and test the new rc today @panbingkun :)

**Comment by panbingkun** [comment]
> Yes, arrow `13.0.0-rc2` has been released, and this version should be able to support Netty <=4.1.93 and >=4.1.96. We can remove the Netty part from this pr and test the new rc today @panbingkun :)

Let's verify in advance that it is ready for staging: https://repository.apache.org/content/groups/staging/org/apache/arrow/arrow-memory-netty/13.0.0/

**Comment by dongjoon-hyun** [comment]
Thank you, @panbingkun .

**Comment by LuciferYang** [comment]
hmm... It seems like it didn’t fetch the new release…

**Comment by dongjoon-hyun** [comment]
Thank you for re-triggering.

**Comment by panbingkun** [comment]
After clearing the cache, it seems that it is ok.

**Comment by dongjoon-hyun** [comment]
Interesting. Thank you for the experiment. And, it's great to see the successful run. Let's not forget to recover it at the next update.

> After clearing the cache, it seems that it is ok.

**Comment by LuciferYang** [comment]
`Arrow` 13.0 has been released to the central repository. 

https://repo1.maven.org/maven2/org/apache/arrow/arrow-memory-netty/13.0.0/

image


It is now possible to cleanup redundant code to perform tests.

**Comment by dongjoon-hyun** [comment]
Finally!

**Review by dongjoon-hyun — COMMENTED** [review]
Could you make this PR ready, @panbingkun ?

**Comment by panbingkun** [comment]
> Could you make this PR ready, @panbingkun ?

Done.

**Comment by dongjoon-hyun** [comment]
Thank you so much, @panbingkun .

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM (Pending CIs)

**Review by LuciferYang — APPROVED** [review]
LGTM

**Comment by LuciferYang** [comment]
This doesn't need to be merged into 3.5, right? @dongjoon-hyun

**Comment by dongjoon-hyun** [comment]
Yes, it's too late for Apache Spark 3.5.0.

**Comment by LuciferYang** [comment]
> Yes, it's too late for Apache Spark 3.5.0.

OK

**Comment by dongjoon-hyun** [comment]
The affected version of SPARK-44247 (this PR) is 4.0.0.
And, the target version of SPARK-43831 (Java 21) is 4.0.0.

**Comment by dongjoon-hyun** [comment]
All tests passed.

**Comment by dongjoon-hyun** [comment]
Merged to master for Apache Spark 4.

**Pull request closed without merging**
