### PR TITLE
[SPARK-31680][SQL][TESTS] Support Java 8 datetime types by Random data generator

### PR DESCRIPTION
**Pull request by MaxGekk**
### What changes were proposed in this pull request?
Generates java.time.Instant/java.time.LocalDate for DateType/TimestampType by `RandomDataGenerator.forType` when the SQL config `spark.sql.datetime.java8API.enabled` is set to `true`.

### Why are the changes needed?
To improve test coverage, and check java.time.Instant/java.time.LocalDate types in round trip tests.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
By running modified test suites `RowEncoderSuite`, `RandomDataGeneratorSuite` and `HadoopFsRelationTest`.

### CODE REVIEW

**Comment by MaxGekk** [comment]
@HyukjinKwon @cloud-fan Please, review this PR.

**Comment by HyukjinKwon** [comment]
Seems fine to me.

**Comment by srowen** [comment]
Also for 3.0, right?

**Comment by cloud-fan** [comment]
it's test only so should be fine for 3.0

**Comment by cloud-fan** [comment]
thanks, merging to master/3.0!

**Pull request closed without merging**
