### PR TITLE
[SPARK-32785][SQL][DOCS][FOLLOWUP][3.0] Update migration guide for incomplete interval literals

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

Address comments @ https://github.com/apache/spark/pull/29635#discussion_r507241899 to improve migration guide

### Why are the changes needed?

improve migration guide

### Does this PR introduce _any_ user-facing change?

NO，only doc update

### How was this patch tested?

passing GitHub action

### CODE REVIEW

**Comment by yaooqinn** [comment]
cc @maropu thanks

**Comment by yaooqinn** [comment]
retest this please

**Review by maropu — APPROVED** [review]

**Comment by maropu** [comment]
Thanks! This is trivial, so I merged to branch-3.0.

**Comment by yaooqinn** [comment]
thanks for merging @maropu ~

**Pull request closed without merging**
