### PR TITLE
[SPARK-37887][CORE] Fix the check of repl log level

### PR DESCRIPTION
**Pull request by viirya**
### What changes were proposed in this pull request?

This patch fixes the check of repl's log level. So we can correctly know if the repl class is set with log level or not.

### Why are the changes needed?

Same as the check in `SparkShellLoggingFilter`, `getLevel` cannot be used anymore to check if the log level is set or not for a logger in log4j2.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Manual verified locally.

### CODE REVIEW

**Comment by viirya** [comment]
cc @HyukjinKwon @dongjoon-hyun

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @viirya .

**Comment by viirya** [comment]
Thank you @dongjoon-hyun

**Comment by dongjoon-hyun** [comment]
Merged to master. :)

**Comment by HyukjinKwon** [comment]
Thanks!

**Pull request closed without merging**
