### PR TITLE
[SPARK-25943][SQL] Fail if mismatching nested struct fields when writing to datasource

### PR DESCRIPTION
**Pull request by j-baker**
At present, Spark reorders mismatched columns when writing to
a datasource, but does not reorder nested structs.

This causes failure at present if the types do not match, but
not if the names do not match; this causes structs to get
silently mangled.

It's not obvious to me where I should add tests, so would
appreciate guidance on that!

## What changes were proposed in this pull request?

Unify DatasourcesV1 behaviour with DatasourcesV2, by throwing if the names are mismatched.

## How was this patch tested?

Nothing. I'd really appreciate a suggestion of where to put tests for this; I'm unfamiliar with the codebase and I couldn't find any obvious looking tests of that codepath.

### CODE REVIEW

**Comment by mccheah** [comment]
Ok to test

**Comment by mccheah** [comment]
@cloud-fan for review.

**Review by dongjoon-hyun — COMMENTED** [review]
It seems that we need to update PR or test cases first, @j-baker .
```
org.apache.spark.sql.AnalysisException: It is not safe to write out datatype 
NullType into a table of type DoubleType, because struct columns would be in the wrong order.;
```

**Comment by j-baker** [comment]
have got a test and have hopefully fixed the existing ones!

**Comment by j-baker** [comment]
Hm, it seems that we consider this behaviour to be a feature, and there is a test for this specific thing. This PR would additionally break the code:

```sql
CREATE TABLE t5(i1 INT, t5 STRUCT<i1:INT, i2:INT>) USING parquet;
INSERT INTO t5 VALUES(1, (2, 3));
```

Not really sure how to proceed.

**Comment by HyukjinKwon** [comment]
Can we allow that case specifically?

**Comment by HyukjinKwon** [comment]
Closing due to author's inactivity.

**Pull request closed without merging**
