### PR TITLE
[SPARK-38569][BUILD] Rename `external` top level dir to `connector`

### PR DESCRIPTION
**Pull request by alkis**
### What changes were proposed in this pull request?
Rename the `external` top level directory to `connector`.

### Why are the changes needed?
`external` is a hardwired special name for bazel and this causes all sorts of issues with both native bazel or extensions like [bazel-compile-commands-extractor](https://github.com/hedronvision/bazel-compile-commands-extractor). Spark forks using bazel to build Spark have to go through hoops to make things work if at all.

Amongst other things, making the source code browsable [through top level `external` symlink](
https://github.com/hedronvision/bazel-compile-commands-extractor#make-external-code-easily-browsable-also-necessary-for-this-tool-to-function-correctly) is impossible with a top level `external` directory in the repository.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Ran `./build/mvn -DskipTests clean package` and `./dev/run-tests`.

### CODE REVIEW

**Comment by alkis** [comment]
> It makes sense to avoid using reserved name for some build systems. Can we create a JIRA ticket for it?

Sure thing. Done.

**Comment by alkis** [comment]
FYI for more details on how this causes major issues in practice https://github.com/hedronvision/bazel-compile-commands-extractor/issues/30

**Review by cloud-fan — APPROVED** [review]
LGTM, can you fix the merge conflcts?

**Review by HyukjinKwon — APPROVED** [review]

**Review by dongjoon-hyun — DISMISSED** [review]
Since this is big, shall we discuss a little more in the dev mailing list before merging, please?

**Comment by dongjoon-hyun** [comment]
Although `Apache Spark` is irrelevant to `bazel`, I fully understand the requirement from downstream projects here.
What we need is simply an officially discussion with a broader community audience.

**Comment by alkis** [comment]
> Although `Apache Spark` is irrelevant to `bazel`, I fully understand the requirement from downstream projects here. What we need is simply an officially discussion with a broader community audience.

Thank you Dongjoon. This is my first contribution to `Apache Spark` so bear with my perhaps silly questions. Could you advice what topics we want to discuss - the move itself, the final directory name or something else? While the PR looks big, at its core this is a single directory rename.

**Comment by alkis** [comment]
Thank you Dongjoon. Makes sense. I started a conversation at dev@spark mailing list.

**Comment by dongjoon-hyun** [comment]
Could you revise the PR title and description according to the PR content?

**Comment by alkis** [comment]
> Could you revise the PR title and description according to the PR content?

Done.

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Comment by alkis** [comment]
> thanks, merging to master!

Woohoo, thank you!

**Pull request closed without merging**
