### PR TITLE
[Minor] Fix the value represented by spark.executor.id for consistency.

### PR DESCRIPTION
**Pull request by sarutak**
The property  `spark.executor.id` can represent both `driver` and `<driver>`  for one driver.
It's inconsistent.

This issue is minor so I didn't file this in JIRA.

### CODE REVIEW

**Comment by sarutak** [comment]
retest this please.

**Comment by andrewor14** [comment]
LGTM I will merge this once the tests pass. Quick question though this seems to affect not only local mode right? If so, could you remove that from the title and the description?

**Comment by sarutak** [comment]
@andrewor14 Yeah, this can affects to any other modes so I changed the description and title.

**Comment by wangxiaojing** [comment]
@srowen @andrewor14 This change can affects for users monitoring driver's metrics. The property is used for metrics value.
eg: `<EXTRA_ELEMENT NAME="DESC" VAL="local-1422350105844.<driver>.jvm.pools.Eden-Space.usage"/>`,  parser error : Unescaped '<' not allowed in attributes values.

**Comment by srowen** [comment]
@sarutak I still don't get the purpose of this change, and as you say it not only potentially broke metrics, but seems to have. Although maybe you can fix it forward, is this a good change?

**Comment by sarutak** [comment]
Sorry I didn't notice this change affects for specific metrics sinks.
I still think this change is needed. The identifier is used for metrics name so without this change, the metrics name for the driver is different between local mode and any other mode. It confuses monitoring.
Also, regardless of this change, the parse issue could occur because the identifier `<driver>` has been used for `spark.executor.id` in local mode even before this change.

I'll fix this issue by renaming the identifier from `<driver>` to `driver`.

**Comment by srowen** [comment]
OK. Can this be fixed by just escaping the value in the XML output? because if it's `<driver>` elsewhere then it seems like it would also break the output elsewhere.

**Comment by sarutak** [comment]
So, how about escaping the specific characters like `<` or `>` in each sink instead of changing the identifier?

**Comment by sarutak** [comment]
Maybe, we can resolve the parse issue by updating `com.codahale.metrics` library from `3.0.0` to `3.1.0`. `3.1.0` sanitizes `<` and `>`.

**Comment by srowen** [comment]
Already proposed at https://issues.apache.org/jira/browse/SPARK-5413. Perhaps we can close this issue and PRs then if that's the way forward.

**Comment by sarutak** [comment]
O.K, let's wait for being merged the PR.

**Pull request closed without merging**
