### PR TITLE
[SPARK-29981][BUILD][FOLLOWUP] Change hive.version.short

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This is a follow-up according to @liancheng 's advice.
- https://github.com/apache/spark/pull/26619#discussion_r349326090

### Why are the changes needed?

Previously, we chose the full version to be carefully. As of today, it seems that `Apache Hive 2.3` branch seems to become stable.

### Does this PR introduce any user-facing change?

No.

### How was this patch tested?

Pass the compile combination on GitHub Action.
1. hadoop-2.7/hive-1.2/JDK8
2. hadoop-2.7/hive-2.3/JDK8
3. hadoop-3.2/hive-2.3/JDK8
4. hadoop-3.2/hive-2.3/JDK11

Also, pass the Jenkins with `hadoop-2.7` and `hadoop-3.2` for (1) and (4). 
(2) and (3) is not ready in Jenkins.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by dongjoon-hyun** [comment]
cc @liancheng , @srowen , @wangyum , @HyukjinKwon

**Comment by srowen** [comment]
I'm OK with it pending tests. It's just a move of files, right?

**Comment by dongjoon-hyun** [comment]
Yes, right, @srowen .

**Comment by dongjoon-hyun** [comment]
The first run on `hadoop-2.7/hive-1.2` is currently running `SparkR` test.
The second run on `hadoop-3.2/hive-2.3` seems to fail due to `Objenesis` `mock` flakiness.
```
sbt.ForkMain$ForkError: org.mockito.exceptions.base.MockitoException: 
ClassCastException occurred while creating the mockito mock :
  class to mock : 'javax.servlet.http.HttpServletRequest', loaded by classloader : 'sun.misc.Launcher$AppClassLoader@490d6c15'
  created class : 'org.mockito.codegen.HttpServletRequest$MockitoMock$1109942067', loaded by classloader : 'net.bytebuddy.dynamic.loading.MultipleParentClassLoader@6e9119e9'
  proxy instance class : 'org.mockito.codegen.HttpServletRequest$MockitoMock$1109942067', loaded by classloader : 'net.bytebuddy.dynamic.loading.MultipleParentClassLoader@6e9119e9'
  instance creation by : ObjenesisInstantiator
```

**Comment by dongjoon-hyun** [comment]
Thank you for review. Merged to master.

**Review by HyukjinKwon — COMMENTED** [review]
Looks good to me

**Pull request closed without merging**
