### PR TITLE
[SPARK-17281][ML][MLLib] Add treeAggregateDepth parameter for AFTSurvivalRegression

### PR DESCRIPTION
**Pull request by WeichenXu123**
## What changes were proposed in this pull request?

Add treeAggregateDepth parameter for AFTSurvivalRegression to keep consistent with LiR/LoR.
## How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by WeichenXu123** [comment]
cc @yanboliang

**Comment by WeichenXu123** [comment]
cc @jkbradley thanks!

**Comment by WeichenXu123** [comment]
cc @srowen thanks!

**Comment by yanboliang** [comment]
LGTM, merged into master. Thanks!

**Pull request closed without merging**
