### PR TITLE
[Spark-11478] [ML] ML StringIndexer return inconsistent schema

### PR DESCRIPTION
**Pull request by rekhajoshm**
```
val data = sc.parallelize(Seq((0, "a"), (1, "b"), (2, "c"), (3, "a"), (4, "a"), (5, "c")), 2)
val df = sqlContext.createDataFrame(data).toDF("id", "label")
val indexer = new StringIndexer()
  .setInputCol("label")
  .setOutputCol("labelIndex")
  .fit(df)
val transformed = indexer.transform(df)

println(transformed.schema.toString())
println(indexer.transformSchema(df.schema))
```

With a quick look, verified that two print of transformed schema return different nullable
StructType(StructField(id,IntegerType,false), StructField(label,StringType,true), StructField(labelIndex,DoubleType,true))

StructType(StructField(id,IntegerType,false), StructField(label,StringType,true), StructField(labelIndex,DoubleType,false))

### CODE REVIEW

**Comment by mengxr** [comment]
cc @yanboliang

**Comment by yanboliang** [comment]
I think the patch is not appropriate because it does not pass regression test and will produce error in other test cases. I have found the cause of this bug, but not figure out a way to resolve it. Please see my comments at [SPARK-11478](https://issues.apache.org/jira/browse/SPARK-11478). I think disable ```nullable``` check is a workaround, looking forward to others' opinions. @rekhajoshm @mengxr

**Comment by rekhajoshm** [comment]
Thanks @yanboliang for your comments.My findings were similar to yours, and that nullable is the cause, driven by attr.toStructField().This was a few secs quick look/pull. Agree it needs more conversation. @mengxr

**Comment by jkbradley** [comment]
Is this still active?  If not, can you please close this issue pending discussion on the JIRA?  Thanks!

**Pull request closed without merging**
