### PR TITLE
[SPARK-46474][INFRA] Upgrade upload-artifact action to v4

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to upgrade upload-artifact action from v3 to v4.
After PR https://github.com/apache/spark/pull/44698, our environment variable(`PYTHON_TO_TEST`) is correctly passed and assigned value.
We will bring back this PR: https://github.com/apache/spark/pull/44662

### Why are the changes needed?
- v4.0.0 release notes: https://github.com/actions/upload-artifact/releases/tag/v4.0.0
They have numerous performance and behavioral improvements.

- v3 VS v4: https://github.com/actions/upload-artifact/compare/v3...v4.0.0

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by panbingkun** [comment]
The verification of environmental variables is as follows:
Before:


After:

**Comment by panbingkun** [comment]
cc @HyukjinKwon @dongjoon-hyun

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by panbingkun** [comment]
Let's continue to observe. Additionally, I am trying to fix the `pypy3 test`, which involves a lot of files.

**Comment by panbingkun** [comment]
According to the `latest schedule`, `the upload action` is currently successful.

**Pull request closed without merging**
