### PR TITLE
[BUILD] Closing some stale PRs

### PR DESCRIPTION
**Pull request by HyukjinKwon**
## What changes were proposed in this pull request?

This PR proposes to close some stale PRs and ones suggested to be closed by committer(s) or obviously inappropriate PRs (e.g. branch to branch).

Closes #13458
Closes #15278
Closes #15294
Closes #15339
Closes #15283
## How was this patch tested?

N/A

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Just to defense myself, it seems the PR such 15339 against a branch to a branch leaving a failure mark for each commit in the branches ([branch-2.0](https://github.com/apache/spark/commits/branch-2.0)). Could you please take a look please @srowen ?

**Comment by HyukjinKwon** [comment]
FYI, for 15294, the JIRA is set as `Won't fix`.

**Review by srowen — APPROVED** [review]
Although I think 14565 and 15078 should be closed, I usually don't force close them unless it's been like a week and it hasn't been closed by the author. 

You can add https://github.com/apache/spark/pull/15283 and it LGTM.

**Comment by HyukjinKwon** [comment]
Do you mind if I ask to confirm https://github.com/apache/spark/pull/12355 too? if you are uncertain, I'd like to not add it here.

**Comment by srowen** [comment]
Same thing, I think. I agree it should _probably_ be closed but given that there's not a big hurry, I like to do the courtesy of giving at least days if not a week for someone to reply. I just put it on my big to-do list for later (FWIW I manage all this stuff with Gmail Inbox snooze / reminders and it works quite well for me, to easily "check on X and act in Y days")

**Comment by HyukjinKwon** [comment]
Ah, sure. I just wanted to include as many as I could as I already opened this but I will keep it in mind. Thank you for your tip.

**Pull request closed without merging**
