### PR TITLE
[SPARK-40365][BUILD] Bump ANTLR runtime version from 4.8 to 4.9.3

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aim to upgrade ANTLR runtime version from 4.8 to 4.11.1.

### Why are the changes needed?
The last upgrade occurred 1 year ago.
v4.8 VS v4.11.1: https://github.com/antlr/antlr4/compare/4.8...4.9.3
#### bring security issue fix:
image

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA.

### CODE REVIEW

**Comment by LuciferYang** [comment]
We can't upgrade this due to ANTLR 4.11 depends on JDK 11, but spark needs to be compatible with Java 8

**Comment by LuciferYang** [comment]
image

**Comment by panbingkun** [comment]
> We can't upgrade this due to ANTLR 4.11 depends on JDK 11, but spark needs to be compatible with Java 8
> 
> Also cc @HyukjinKwon FYI

Maybe 4.9.3 is best effort.

**Comment by LuciferYang** [comment]
We can have a try

**Comment by LuciferYang** [comment]
4.8 -> 4.9.3 : Only one [patch]( https://github.com/antlr/antlr4/pull/3261 ) is related to Java?

**Review by srowen — APPROVED** [review]
Seems OK to pick up even minor improvements

**Review by HyukjinKwon — APPROVED** [review]

**Comment by LuciferYang** [comment]
image
hmm... the pr description is wrong, should be `The pr aim to upgrade ANTLR runtime version from 4.8 to 4.9.3.`

**Comment by LuciferYang** [comment]
> > We can't upgrade this due to ANTLR 4.11 depends on JDK 11, but spark needs to be compatible with Java 8
> > Also cc @HyukjinKwon FYI
> 
> Antlr runtime is compatible with jdk8. Antlr tool requires jdk11.

Could you give a PR for upgrade? @melin

**Comment by melin** [comment]
Introduce caseInsensitive lexer rule option

**Pull request closed without merging**
