### PR TITLE
[SPARK-26124][BUILD] Update plugins to latest versions

### PR DESCRIPTION
**Pull request by srowen**
## What changes were proposed in this pull request?

Update many plugins we use to the latest version, especially MiMa, which entails excluding some new errors on old changes.

## How was this patch tested?

N/A

### CODE REVIEW

**Comment by srowen** [comment]
Will do. I'm going to update some SBT plugins too. Many we can't update because they kind of go hand-in-hand with SBT 1.x, and those versions in turn seem to go with Scala 2.12, so they may all have to happen together.

We can update MiMa to get some fixes, but they uncover some new errors on old code. I'm going to make a JIRA.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
reest this please

**Comment by viirya** [comment]
retest this please.

**Comment by srowen** [comment]
It's OK; it clearly does merge cleanly and tests pass. I have seen apparently spurious "does not merge cleanly" messages before and I assume it's because something else transient went wrong with a git command.

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
