### PR TITLE
[MINOR][CORE] Improve log message during storage decommission

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to improve the log message for better analysis.

### Why are the changes needed?

Good logs are crucial always.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Manual review.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Could you review this, @holdenk ?

**Comment by holdenk** [comment]
LGTM pending CI

**Comment by dongjoon-hyun** [comment]
Thank you, @holdenk !

**Comment by dongjoon-hyun** [comment]
Retest this please

**Comment by dongjoon-hyun** [comment]
GitHub Action passed. (We can ignore `Report test results` job)

**Pull request closed without merging**
