### PR TITLE
[FLAKY-TEST-FIX][STREAMING][TEST] Make sure StreamingContexts are shutdown after test

### PR DESCRIPTION
**Pull request by tdas**

### CODE REVIEW

**Comment by tdas** [comment]
@zsxwing Please take a look. Most of the change is in indentation.

**Comment by tdas** [comment]
@zsxwing Please merge this to older branches if possible.

**Comment by JoshRosen** [comment]
Diff minus whitespace changes: https://github.com/apache/spark/pull/10124/files?w=0

**Comment by zsxwing** [comment]
This one doesn't fix the flaky test. Instead, it just makes sure `StreamingContexts` will be shutdown if the tests fail. Right?

**Comment by tdas** [comment]
It is kindof. One test failure, would cause many subsequent tests to fail. So it is a fix for flakiness of the subsequent tests in the suite :)

**Comment by zsxwing** [comment]
LGTM

**Pull request closed without merging**
