### PR TITLE
[MINOR][CORE] Modify some field name because it may be cause confusion

### PR DESCRIPTION
**Pull request by wangjiaochun**
## What changes were proposed in this pull request?
There is different field name style for tracking allocated data pages, 
such as class BytesToBytesMap use field name dataPages for allocated data pages,
class UnsafeExternalSorter and ShuffleExternalSorter use field name allocatedPages for allocated data pages
They are all belong to memory consumer, so I think it is best to use unified name;
and class TaskMemoryManager filed name allocatedPages is modified to pagesBitSet，used to indicate the function of bitmap ;

## How was this patch tested?
Existing tests

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)
(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Comment by heary-cao** [comment]
ok to test

**Comment by heary-cao** [comment]
ok to test

**Comment by HyukjinKwon** [comment]
I don't think it's worth to change naming the variable in a single PR. Let's do that when we fix some codes around here, or let other people try to fix later.

**Comment by srowen** [comment]
Agree, this isn't worthwhile.

**Comment by wangjiaochun** [comment]
ok,close this PR.

**Pull request closed without merging**
