### PR TITLE
[SPARK-13038][SPARK-13388][PySpark] Add load/save to pipeline and change it to use the Scala implementation

### PR DESCRIPTION
**Pull request by yinxusen**
## What changes were proposed in this pull request?

JIRA issues:
- https://issues.apache.org/jira/browse/SPARK-13038
- https://issues.apache.org/jira/browse/SPARK-13388
## How was the patch tested?

The patch is tested with Python doctest. I remove the original unit test for Pipeline and PipelineModel since the `MockEstimator` and `MockTransformer` are not suitable to use in Pipeline now because they have no Java Object.

### CODE REVIEW

**Comment by yinxusen** [comment]
retest it please

**Comment by yinxusen** [comment]
cc @yanboliang @mengxr

**Comment by yanboliang** [comment]
@yinxusen I will make a pass soon.

**Comment by yanboliang** [comment]
@yinxusen I notice that your change made ```Pipeline``` and ```PipelineModel``` as the wrapper of peer Java object. But I vote to keep the exist behavior, ```Pipeline``` still should be a pure Python object. 
We do not need to bother a peer Java object for ```Pipeline```. Because most stages(Estimator/Transformer) have already supported save/load, so implementing ```Pipeline``` persistence at Python side is more simple than your change.
May be we should here others' thoughts. cc @mengxr @jkbradley

**Comment by yinxusen** [comment]
Implementing Pipeline with its Scala companion helps keep consistency between Scala and Python sides. The Pipeline in Scala side may evolve many times, it's easy to maintenance the Python interface in such scenario. In this PR, I only add two more functions: `_transfer_stages_to/from_java`. And I think this is also useful later when we want to port warm-start interfaces to Python side.

**Comment by jkbradley** [comment]
My thoughts on the pros/cons of having Python's Pipeline be a wrapper for the Java Pipeline:

Pros:
* Less code duplication.  This would have an even higher impact for CrossValidator, which is annoying to implement twice.
Cons:
* This will break the code of anyone who has written a PipelineStage from Python.  We have not supported this very explicitly so far, but I think it's something we should support eventually.

I'd propose:
* Short-term (for 2.0): We do not make Pipeline into a Java wrapper.  But we implement save/load by transferring the stages to Java (as you did in this PR).
* Long-term: We can eventually consider better ways to support Python users who wish to write their own PipelineStages in Python.  If useful for combining code paths, we could also consider making Pipeline into a Java wrapper, as long as we come up with a good way to have a Java wrapper for a PipelineStage defined in Python (like a Python UDF).

**Comment by yinxusen** [comment]
@jkbradley I'll try to make it.

**Comment by yinxusen** [comment]
Close it since we have https://github.com/apache/spark/pull/11683. I'll leave JIRA SPARK-13388 to be solved later.

**Pull request closed without merging**
