### PR TITLE
[SPARK-6741][SQL] Add support for SELECT ALL syntax.

### PR DESCRIPTION
**Pull request by smola**
https://issues.apache.org/jira/browse/SPARK-6741

### CODE REVIEW

**Comment by marmbrus** [comment]
ok to test

**Comment by marmbrus** [comment]
Thanks for the contribution, but I'm pretty hesitant to add unnecessary syntax to the SQL parser.  One reason is that each new keyword actually could break existing code.  Any user that has a column named `all` would now need to start using backticks.  Is there a strong reason to add this that I'm missing?

**Comment by smola** [comment]
@marmbrus My goal is to have a parser as compatible as possible with standard SQL. *SELECT [ALL | DISTINCT]* is the standard syntax since SQL'92 and it's implemented this way in every major SQL implementation.

**Comment by smola** [comment]
@marmbrus Maybe this and https://github.com/apache/spark/pull/5468 can be left for an alternative SQL dialect implementation in Spark that aims for completeness and interoperability rather than backwards compatibility.

**Comment by marmbrus** [comment]
@smola, that sounds like a great idea to me!  I would really like to have better SQL92 support, but the parser combinators are pretty brittle and we have gotten a lot of complaints in the past when we have added keywords the broke existing queries.

**Comment by marmbrus** [comment]
Given the plan to do this as a plugable parser could you close this issue for now?

**Pull request closed without merging**
