### PR TITLE
[SPARK-26033][PYTHON][TESTS] Break large ml/tests.py file into smaller files

### PR DESCRIPTION
**Pull request by BryanCutler**
## What changes were proposed in this pull request?

This PR breaks down the large ml/tests.py file that contains all Python ML unit tests into several smaller test files to be easier to read and maintain.

The tests are broken down as follows:
```
pyspark
├── __init__.py
...
├── ml
│   ├── __init__.py
...
│   ├── tests
│   │   ├── __init__.py
│   │   ├── test_algorithms.py
│   │   ├── test_base.py
│   │   ├── test_evaluation.py
│   │   ├── test_feature.py
│   │   ├── test_image.py
│   │   ├── test_linalg.py
│   │   ├── test_param.py
│   │   ├── test_persistence.py
│   │   ├── test_pipeline.py
│   │   ├── test_stat.py
│   │   ├── test_training_summary.py
│   │   ├── test_tuning.py
│   │   └── test_wrapper.py
...
├── testing
...
│   ├── mlutils.py
...
```

## How was this patch tested?

Ran tests manually by module to ensure test count was the same, and ran `python/run-tests --modules=pyspark-ml` to verify all passing with Python 2.7 and Python 3.6.

### CODE REVIEW

**Comment by BryanCutler** [comment]
Dist by line count:
```
348 ./test_algorithms.py
 84 ./test_base.py
 71 ./test_evaluation.py
314 ./test_feature.py
118 ./test_image.py
392 ./test_linalg.py
367 ./test_param.py
369 ./test_persistence.py
 77 ./test_pipeline.py
 56 ./test_stat.py
254 ./test_training_summary.py
552 ./test_tuning.py
116 ./test_wrapper.py

```

**Comment by BryanCutler** [comment]
cc @HyukjinKwon

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Let me leave a cc for @holdenk, @MLnick, @jkbradley and @mengxr FYI.

**Comment by HyukjinKwon** [comment]
Will merge this one tomorrow if this is not merged till then.

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
