### PR TITLE
[SPARK-12150] [SQL] [Minor] Add range API without specifying the slice number

### PR DESCRIPTION
**Pull request by gatorsmile**
For usability, add another sqlContext.range() method. Users can specify start, end, and step without specifying the slice number. The slice number is based on the sparkContext's defaultParallelism. It just makes consistent with the RDD range API.

### CODE REVIEW

**Comment by gatorsmile** [comment]
@marmbrus @cloud-fan This PR changes the external API. Not sure if this will be merged or we should revisit it after the release of 1.6? Thank you!

**Comment by marmbrus** [comment]
This seems reasonable, but if we are going to do work on `sqlContext.range` it would be nice if we could take care of a bigger issue.  Right now this code is much slower than it needs to be.

screen shot 2015-12-08 at 4 20 59 pm

I think that is is because we are boxing and creating a new Row for each element.  Instead, we should consider creating an actual logical/physical operator for range.  the implementation of doExecute() can mirror the code in `sparkContext.range`, but would allocate one `UnsafeRow` per partition and just call `setLong` for each element (reusing the same buffer).

Does that make sense?

Benchmark code here: https://github.com/databricks/spark-sql-perf/blob/master/src/main/scala/com/databricks/spark/sql/perf/DatasetPerformance.scala

**Comment by gatorsmile** [comment]
That sounds an interesting work! Let me think about it. 

Do you want me close this PR?

**Comment by gatorsmile** [comment]
I will make a try this week. Thanks for your insights! : )

**Comment by marmbrus** [comment]
Cool, let me know if you run into any problems.

**Comment by gatorsmile** [comment]
Thanks! Will do my best. : )

**Pull request closed without merging**
