### PR TITLE
[SPARK-36487][CORE] Modify exit executor log logic

### PR DESCRIPTION
**Pull request by zwangsheng**
### What changes were proposed in this pull request?
Adjust the log logic of CoarseGrainedExecutorBackend

### Why are the changes needed?
When exit executor with system code 0, coarseGrainedExecutorBackend will print ERROR log.
That doesn't make sense, because it seems to me that executor's normal decommission is not caused by an exception.

### Does this PR introduce _any_ user-facing change?
no

### How was this patch tested?
local

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
can you file a JIRA please? Also it would be great to show the console output you got from the manual test.

**Comment by zwangsheng** [comment]
> can you file a JIRA please? Also it would be great to show the console output you got from the manual test.

OK, i will do it later.

**Comment by zwangsheng** [comment]
Write a unit tests to reflect exitExecutor method
 
popo_2021-08-12  18-11-16

Using code 0 can print info log

POPO20210812-181011

**Comment by zwangsheng** [comment]
Please take a check, thank you. @HyukjinKwon

**Comment by yaooqinn** [comment]
ok to test

**Comment by Ngone51** [comment]
Strictly speaking, I think this should be a user-facing change.

**Review by Ngone51 — COMMENTED** [review]
Sounds reasonable to me.

**Review by mridulm — APPROVED** [review]

**Review by yaooqinn — APPROVED** [review]
LGTM

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
