### PR TITLE
[MINOR][DOCS] Fix grammatical error in streaming programming guide

### PR DESCRIPTION
**Pull request by wangaustin**
### What changes were proposed in this pull request?

This change fixes a grammatical error in the documentation.

### Why are the changes needed?

There is a grammatical error in the documentation.

### Does this PR introduce _any_ user-facing change?

Yes.
Previously the sentence in question reads "This leads to two kinds of data in the system that
need to recovered in the event of failures," but it should instead read "This leads to two kinds of data in the system that
need to be recovered in the event of failures."

### How was this patch tested?

Tests were not added. This was a simple text change that can be previewed immediately.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
That's fine but mind taking a look and see if there are more typos while we're here?

**Comment by wangaustin** [comment]
> That's fine but mind taking a look and see if there are more typos while we're here?

Sure thing, I can read through everything on this page for this particular PR

**Comment by wangaustin** [comment]
> That's fine but mind taking a look and see if there are more typos while we're here?

New commit fixed all the typos I found on this page

**Review by HyukjinKwon — APPROVED** [review]

**Review by MaxGekk — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
