### PR TITLE
[SPARK-24685][build] Restore support for building old Hadoop versions of 2.1.

### PR DESCRIPTION
**Pull request by vanzin**
Update the release scripts to build binary packages for older versions
of Hadoop when building Spark 2.1. Also did some minor refactoring of that
part of the script so that changing these later is easier.

This was used to build the missing packages from 2.1.3-rc2.

### CODE REVIEW

**Review by srowen — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by vanzin** [comment]
Even though there's talk of EOLing 2.1, I think this can still be helpful later since there's also talk of removing the hadoop-2.6 build from 2.4, and the code here makes it easy to make those adjustments.

Merging to master.

**Pull request closed without merging**
