### PR TITLE
[SPARK-11611][MLlib][Python] Python API for bisecting k-means

### PR DESCRIPTION
**Pull request by yu-iskw**

### CODE REVIEW

**Comment by yu-iskw** [comment]
@mengxr could you review it?

**Comment by jkbradley** [comment]
@yu-iskw Sorry for the long delay!  Would you have time to update this?

**Comment by yanboliang** [comment]
@jkbradley This feature has been finished by #10150, @yu-iskw would you mind to close this PR?

**Comment by jkbradley** [comment]
@yanboliang Oh, thanks for pointing that out!
@yu-iskw I'm sorry for losing track of this PR.

**Pull request closed without merging**
