### PR TITLE
[SPARK-49182][DOCS][PYTHON] Stop publish site/docs/{version}/api/python/_sources dir

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

Remove dangling links like:
https://spark.apache.org/docs/3.5.1/api/python/_sources/user_guide/sql/index.rst.txt

### Why are the changes needed?

reduce the size of documentation publication

```
$ du -h 3.5.1/api/python/_sources
 68K	3.5.1/api/python/_sources/development
148K	3.5.1/api/python/_sources/user_guide/pandas_on_spark
 40K	3.5.1/api/python/_sources/user_guide/sql
208K	3.5.1/api/python/_sources/user_guide
 20K	3.5.1/api/python/_sources/migration_guide
2.9M	3.5.1/api/python/_sources/reference/pyspark.sql/api
3.0M	3.5.1/api/python/_sources/reference/pyspark.sql
180K	3.5.1/api/python/_sources/reference/pyspark.ss/api
196K	3.5.1/api/python/_sources/reference/pyspark.ss
2.5M	3.5.1/api/python/_sources/reference/api
3.0M	3.5.1/api/python/_sources/reference/pyspark.pandas/api
3.1M	3.5.1/api/python/_sources/reference/pyspark.pandas
8.8M	3.5.1/api/python/_sources/reference
4.1M	3.5.1/api/python/_sources/getting_started
 13M	3.5.1/api/python/_sources
```

### Does this PR introduce _any_ user-facing change?

NO
### How was this patch tested?

build locally

```
ls api/python
_images         _static         getting_started migration_guide reference       searchindex.js
_modules        development     index.html      objects.inv     search.html     user_guide
```
### Was this patch authored or co-authored using generative AI tooling?

NO

### CODE REVIEW

**Review by cloud-fan — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

cc @HyukjinKwon

**Comment by dongjoon-hyun** [comment]
BTW, I revised the PR description by adding the following.

```
$ du -h 3.5.1/api/python/_sources
 68K	3.5.1/api/python/_sources/development
148K	3.5.1/api/python/_sources/user_guide/pandas_on_spark
 40K	3.5.1/api/python/_sources/user_guide/sql
208K	3.5.1/api/python/_sources/user_guide
 20K	3.5.1/api/python/_sources/migration_guide
2.9M	3.5.1/api/python/_sources/reference/pyspark.sql/api
3.0M	3.5.1/api/python/_sources/reference/pyspark.sql
180K	3.5.1/api/python/_sources/reference/pyspark.ss/api
196K	3.5.1/api/python/_sources/reference/pyspark.ss
2.5M	3.5.1/api/python/_sources/reference/api
3.0M	3.5.1/api/python/_sources/reference/pyspark.pandas/api
3.1M	3.5.1/api/python/_sources/reference/pyspark.pandas
8.8M	3.5.1/api/python/_sources/reference
4.1M	3.5.1/api/python/_sources/getting_started
 13M	3.5.1/api/python/_sources
```

**Comment by dongjoon-hyun** [comment]
According to our website, there seems to be only one mistake which we expose this `_sources` directory like the following.

- https://spark.apache.org/docs/3.2.3/api/python/_sources/index.html

Screenshot 2024-08-09 at 08 39 27

**Comment by yaooqinn** [comment]
Merged to master, 3.5, 3.4.

I will manually handle 3.5.2 in doc release

**Comment by HyukjinKwon** [comment]
This PR actually causes a regression.. https://spark.apache.org/docs/latest/api/python/index.html 
Screenshot 2025-08-05 at 10 50 16 AM

Show Sources button does not work..  Seems like it's just to reduce the size of the docs so let me revert this out.

**Pull request closed without merging**
