### PR TITLE
[SPARK-19901][Core]Clean up the clunky method signature of acquireMemory

### PR DESCRIPTION
**Pull request by ConeyLiu**
## What changes were proposed in this pull request?

Clean up the clunky method signature of acquireMemory.

## How was this patch tested?

Exists test.

### CODE REVIEW

**Comment by ConeyLiu** [comment]
Sorry for the mistake, reopen it.

**Comment by srowen** [comment]
This doesn't look simpler to me.

**Comment by HyukjinKwon** [comment]
I don't think this is particular better too. We should avoid style changes by a personal taste.

**Comment by ConeyLiu** [comment]
Hi, @srowen @HyukjinKwon, thanks for the review. This patch stems from the `TODO` list,  which is used to streamline the method signature, make it more readable. If you think there is no essential change here, how about get these two methods(`maybeGrowExecutionPool` & `computeMaxExecutionPoolSize`) in the parent class, this will improve the existing method(`acquireMemory`) signature.

**Comment by srowen** [comment]
I'm not sure what this refers to. Unless it's giving a clear and non-trivial improvement to the method signatures, I don't think is worth the time to discuss and review. This particular change does not seem worthwhile.

**Comment by ConeyLiu** [comment]
ok, I will close it.

**Pull request closed without merging**
