### PR TITLE
[SPARK-37920][BUILD] Remove tab character and trailing space in pom.xml

### PR DESCRIPTION
**Pull request by jackylee-ch**
### Why are the changes needed?
There are some tabs in pom.xml, which don't seem to be standardized. This pr tries to modify this problem.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
origin tests

### CODE REVIEW

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
Hi, @stczwd .
Could you be more specific in the PR title? You can say `Remove tab character and trailing space in pom.xml`.

`Change ... problem` doesn't sound like fixing a problem.

**Comment by stczwd** [comment]
> Hi, @stczwd . Could you be more specific in the PR title? You can say `Remove tab character and trailing space in pom.xml`.
> 
> `Change ... problem` doesn't sound like fixing a problem.

Thanks for your reply @dongjoon-hyun , I have changed the title.

**Review by williamhyun — APPROVED** [review]
+1 LGTM

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @stczwd and @williamhyun .
Merged to master.

**Pull request closed without merging**
