### PR TITLE
[SPARK-38619][TESTS] Clean up Junit api usage in scalatest

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr clean up Junit api usage in scalatest and replace them with native scalatest api.

### Why are the changes needed?
Use scalatest api in scalatest and Junit api in Java test

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA

### CODE REVIEW

**Review by martin-g — APPROVED** [review]

**Review by srowen — APPROVED** [review]

**Comment by srowen** [comment]
Is that all of them? yes good fix.

**Comment by LuciferYang** [comment]
Yes, that's all

**Comment by srowen** [comment]
Merged to master

**Comment by LuciferYang** [comment]
thanks all

**Pull request closed without merging**
