### PR TITLE
 [SPARK-27247][SQL] If the logicPlan get from cached is invalid, invalid it and retry instead of throwing an assert error directly.

### PR DESCRIPTION
**Pull request by turboFei**
## What changes were proposed in this pull request?
Catalyst cache some logic plan.
During relationConversions(Relation conversion from metastore relations to data source relations for better performance), if the logicPlan get from cached is invalid, it would touch an assert error.
However, if the cached logicPlan is invalid, we should remove it from cache and retry instead of throwing an assert error directly.

## How was this patch tested?

UnitTest

### CODE REVIEW

**Comment by hustfeiwang** [comment]
@cloud-fan @gatorsmile

**Comment by maropu** [comment]
Could you add some tests?

**Comment by cloud-fan** [comment]
Do you know how this can happen? Using `assert` means it should never happen unless we have a bug. I'd like to find the root cause instead of hiding the bug.

**Comment by hustfeiwang** [comment]
> Could you add some tests before Jenkins run?

**Comment by hustfeiwang** [comment]
> Do you know how this can happen? Using `assert` means it should never happen unless we have a bug. I'd like to find the root cause instead of hiding the bug.

I would find the cause.

**Comment by hustfeiwang** [comment]
> Could you add some tests before Jenkins run?

I try my best.

**Comment by maropu** [comment]
Why this pr closed?

**Pull request closed without merging**
