### PR TITLE
[SPARK-15043] [MLLIB] Fix and re-enable flaky test: mllib.stat.JavaStatisticsSuite.testCorr

### PR DESCRIPTION
**Pull request by srowen**
## What changes were proposed in this pull request?

Following https://github.com/apache/spark/pull/12779 this test became flaky. The issue is that the mean, computed for a covariance calculation, is now calculated with the standard and slightly more accurate `MultivariateOnlineSummarizer`. However I think the fact that it uses `treeAggregate` internally can lead to a different order of summation and very very slightly different results on different runs.

The immediate fix for the test, which asserts equality, is to use 1 partition. We can find out if that appears to be robust.

More generally, it's an interesting question whether we want `MultivariateOnlineSummarizer` to be deterministic. I'm not sure if another aggregation method would provide more guarantees of this, in theory or practice.
## How was this patch tested?

Existing Java stats suite.

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by srowen** [comment]
FWIW you can consistently reproduce the differing results with ..

```
val x = sc.parallelize(Seq(1.0, 2.0, 3.0, 4.0))
val y = sc.parallelize(Seq(1.1, 2.2, 3.1, 4.3))
(0 to 10).map(i => Statistics.corr(x,y)).distinct
```

With 1 partition the result is always the same. The result is the same if I use `aggregate` instead of `treeAggregate`.

**Comment by jkbradley** [comment]
This patch changed the test to use approx equality: https://github.com/apache/spark/commit/19a6d192d53ce6dffe998ce110adab1f2efcb23e

**Comment by jkbradley** [comment]
It would be great to have it be deterministic, but it sounds hard or impossible to ensure beyond numerical precision in general.

**Comment by mengxr** [comment]
@srowen If we only use 1 partition, it doesn't touch the code path of `treeAggregation`, which means the coverage is not sufficient. I think we should use multiple partitions and test equality with a small tolerance.

**Comment by srowen** [comment]
Sounds good, it's either make it so simple that it's deterministic or tolerate tiny variation.

**Comment by srowen** [comment]
Oh already addressed in https://github.com/apache/spark/commit/19a6d192d53ce6dffe998ce110adab1f2efcb23e

**Pull request closed without merging**
