### PR TITLE
[SPARK 5280] RDF Loader added + documentation

### PR DESCRIPTION
**Pull request by lukovnikov**
Have been testing it with DBpedia dumps, works well so far.
Any help with custom partitioning and optimization is welcome.

### CODE REVIEW

**Comment by ankurdave** [comment]
ok to test

**Comment by lukovnikov** [comment]
style errors fixed

**Comment by maropu** [comment]
Please add tests for your RDF loader, and see my codes as an example:
https://github.com/maropu/spark/commit/cc5ac0b08ca39c3c339fdca905779bb3b037f8fa

BTW, I think that it'd would be better to divide an interface and the implementations
for GraphLoader because we'll possibly add the some types of GraphLoader
for different formats in a future.

e.g.,)
- an interface
o.a.spark.graphx.GraphLoader:
abstract class GraphLoader {
  def edgeListFile(...)
}

- the implementations
o.a.spark.graphx.impl.loader.LineLoader
class LineLoader extends GraphLoader {
  def edgeListFile() = {the current implementation of GraphLoader#edgeListFile}
}

o.a.spark.graphx.impl.loader.RDFLoader
class RDFLoader extends GraphLoader {
  def edgeListFile() = {your codes}
}


Thought?

**Comment by lukovnikov** [comment]
Will add tests soon.

I was also thinking about making one interface for different loaders (with a load() method instead of edgeListFile()) and maybe a facade combining all loaders.

**Comment by lukovnikov** [comment]
Added test + a test file (small excerpt from DBpedia 3.9) + small fix in RDFLoader

**Comment by lukovnikov** [comment]
@maropu tests are added and build tests passed. Is it ready for merging now?

**Comment by blankdots** [comment]
I would really like to have this -  is it going to be merged ?

**Comment by emir-munoz** [comment]
+1, Is this going to be merged?

**Comment by maropu** [comment]
@emir-munoz @blankdots This PR is totally stale, so it'd better to refactor ithis if you're interested in.
Also, ISTM this kind of loader extensions should be registered in spark packages.

**Comment by emir-munoz** [comment]
thanks @maropu I will take a closer look into it

**Comment by rvesse** [comment]
A Spark plugin seems like a much better approach, I've done some experimentation on a plugin for this which seems like a much cleaner and lightweight approach though I have no idea if it will ever be open sourced (it is work for my employer) or move beyond the experimentation stage.

I would strongly suggest looking at leveraging existing libraries like [Apache Jena](http://jena.apache.org) to do a lot of the work for you and avoid having to implement your own RDF parsers.  Personally I am using the [Apache Jena Elephas](http://jena.apache.org/documentation/hadoop/) modules for this since the Hadoop Input formats can simply be used by Spark.  (*Disclaimer* - I am a committer on Apache Jena and the main contributor to the Elephas modules)

**Comment by blankdots** [comment]
@maropu @emir-munoz also considering taking a look at it.
@rvesse good suggestions

**Comment by set0gut1** [comment]
```scala
def gethash(in:String):Long = {
  var h = 1125899906842597L
  for (x <- in) {
    h = 31 * h + x;
  }
  return h
}
```

This hash function seems to be weak.
I tried this with subject URIs of DBpedia's `labels_en.nt` ([sample](http://downloads.dbpedia.org/preview.php?file=2015-04_sl_core-i18n_sl_en_sl_labels_en.nt.bz2)).
There are 11,519,154 unique URIs, and the hash values of 20,741 URIs collided (0.18%).

For example, the hash values of these URI are same (-3127496886112549146).

* `http://dbpedia.org/resource/Dms`
* `http://dbpedia.org/resource/EOT`
* `http://dbpedia.org/resource/F15`
* `http://dbpedia.org/resource/EP5`

**Comment by MLnick** [comment]
@lukovnikov if there is still interest in this, the best approach would be to first release something in spark-packages.org as a set of utilities to create Graphs. Using existing 3rd party Hadoop formats makes the most sense as per @rvesse.

Could you close this PR please?

**Comment by andrewor14** [comment]
+1 to making this a Spark package. I would recommend that we close this PR since it's gone stale.

**Pull request closed without merging**
