### PR TITLE
[SQL][minor] use lazy val instead of do the initialization manually

### PR DESCRIPTION
**Pull request by cloud-fan**
`lazy val` looks more clear.

### CODE REVIEW

**Comment by srowen** [comment]
I'm just curious about how this interacts with `transient`. The deserialized form will recognize again that the field has not been initialized and do so again? or will it 'remember' that it's been initialized and not update it from `null`? Maybe not a problem at all, just occurred to me as a question.

**Comment by cloud-fan** [comment]
@srowen it will recognize again that the field has not been initialized.  We have already done similar stuff at [Rand](https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/random.scala#L45)

**Comment by cloud-fan** [comment]
retest this please.

**Comment by cloud-fan** [comment]
cc @rxin

**Comment by rxin** [comment]
@cloud-fan I'd prefer not to do this change for two reasons:

1. It was marked private[this] in order to avoid function call (field access rather than function calls). JVM JIT is pretty good about inlining these things, but it sometimes doesn't work. Although you could argue in this case it wouldn't matter since performance sucks elsewhere, but there isn't a lot of benefits to changing it either.

2. In the long run, we should move towards explicitly initializing all operators with states, rather than relying on lazy transient val. This is a direction similar to the expression codegen init stuff you did.

**Comment by cloud-fan** [comment]
Alright agreed, should leave it to the future expression init stuff, closing.

**Pull request closed without merging**
