### PR TITLE
[SPARK-16214] [Examples] fix the denominator of SparkPi

### PR DESCRIPTION
**Pull request by yanghaogn**
## What changes were proposed in this pull request?

reduce the denominator of SparkPi by 1
## How was this patch tested?

  integration tests

### CODE REVIEW

**Comment by yanghaogn** [comment]
As the denominator is n, the iteration time should also be n

**Comment by HyukjinKwon** [comment]
Get ready to receive a comment suggesting following https://cwiki.apache.org/confluence/display/SPARK/Contributing+to+Spark..

**Comment by srowen** [comment]
Nah @HyukjinKwon I think this is a simple fix that's self-contained here. Either the iterations or the estimate formula is wrong here and that's all there is to it. `(0 until n)` would be fine too.

**Comment by srowen** [comment]
@yanghaogn since you already made a JIRA, connect it in the title please. It is not resolved

**Comment by srowen** [comment]
Jenkins test this please

**Comment by yanghaogn** [comment]
@srowen It's been related now

**Comment by srowen** [comment]
Not quite, see https://cwiki.apache.org/confluence/display/SPARK/Contributing+to+Spark and other PRs

**Comment by yanghaogn** [comment]
As explained in apache#2874
```
The max size of the input seq was Int.MaxValue - 1
```
This change may cause a bug. For the input is very big and It can be treated as `not a problem`. But then it's hard to understand the logic if users have not read the apache#2874

**Comment by srowen** [comment]
I see, maybe better to just fix the denominator then.

**Comment by srowen** [comment]
Jenkins retest this please

**Comment by srowen** [comment]
Merged to master/2.0/1.6

**Pull request closed without merging**
