### PR TITLE
[SPARK-16014][SQL] Rename optimizer rules to be more consistent

### PR DESCRIPTION
**Pull request by rxin**
## What changes were proposed in this pull request?

This small patch renames a few optimizer rules to make the naming more consistent, e.g. class name start with a verb. The main important "fix" is probably SamplePushDown -> PushProjectThroughSample. SamplePushDown is actually the wrong name, since the rule is not about pushing Sample down.
## How was this patch tested?

Updated test cases.

### CODE REVIEW

**Comment by rxin** [comment]
cc @cloud-fan

**Comment by hvanhovell** [comment]
Shall we also rename the `DistinctAggregateRewriter` into `RewriteDistinctAggregates`?

**Comment by cloud-fan** [comment]
+1for @hvanhovell 's suggestion, otherwise LGTM

**Comment by liancheng** [comment]
LGTM

Renaming `DistinctAggregateRewriter` sounds reasonable, but it is an analysis rule rather than an optimization rule.

**Comment by hvanhovell** [comment]
LGTM

**Comment by rxin** [comment]
Merging in master/2.0.

**Pull request closed without merging**
