### PR TITLE
[SPARK-18656][SQL] Memory efficient implementation of the org.apache.spark.sql.execution.stat.StatFunctions#multipleApproxQuantiles

### PR DESCRIPTION
**Pull request by sinasohangirsc**
@thunterdb 

## What changes were proposed in this pull request?

Creating quantile summaries per partition and then merge together, to be more memory efficient. 

## How was this patch tested?

Passes: ./dev/run-tests
Also ran compared results between the old and new implementation.

### CODE REVIEW

**Comment by rxin** [comment]
We now have an aggregate function for this, so we can deprecate this usage now, can't we?

cc @thunterdb

**Comment by sinasohangirsc** [comment]
Totally right. I jumped into conclusion too fast. Already put the JIRA issue for later. Forgot to close this.

**Comment by barrybecker4** [comment]
@rxin, what is the new aggregate function that we should be using instead of multipleApproxQuantiles?

**Comment by poplav** [comment]
@barrybecker4 Following the trail of this issue...What is the solution for many columns rather than the workaround for chunking?  Thanks!

**Comment by barrybecker4** [comment]
I used chunking the columns to avoid running out of memory when using multipleApproxQuantiles. I don't know if there is a better way.

**Pull request closed without merging**
