### PR TITLE
[SPARK-46204][K8S] Fix `dev-run-integration-tests.sh` to use 17 for `JAVA_VERSION`

### PR DESCRIPTION
**Pull request by hannahkamundson**
### What changes were proposed in this pull request?
Tie the Kubernetes integration dev test script to Java 17.

### Why are the changes needed?
The Kubernetes dev integration test shell script was tied to Java 8. When it was run as is (and not forcing Java version >= 14), the build would fail because it couldn't build different features that required Java >= 14.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
I ran `./dev/dev-run-integration-tests.sh` and it worked.

### Was this patch authored or co-authored using generative AI tooling?
No

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
Thank you for making a PR, @hannahkamundson .

**Comment by dongjoon-hyun** [comment]
It seems to be missed because the CI doesn't use `./dev/dev-run-integration-tests.sh` .

**Comment by dongjoon-hyun** [comment]
Merged to master for Apache Spark 4.0.0. Thank you again, @hannahkamundson .

**Comment by hannahkamundson** [comment]
@dongjoon-hyun No prob! Thanks for the fast review!

**Pull request closed without merging**
