### PR TITLE
[SPARK-33405][BUILD][3.0] Upgrade commons-compress to 1.20

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to upgrade `commons-compress` from 1.8 to 1.20.

### Why are the changes needed?

- https://commons.apache.org/proper/commons-compress/security-reports.html

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the CIs.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
The Jenkins failure is due to the broken Maven directory and is irrelevant to this one.
```
sing `mvn` from path: /home/jenkins/tools/hudson.tasks.Maven_MavenInstallation/Maven_3.6.3/bin/mvn
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-install-plugin:3.0.0-M1:install (default-cli) on project spark-launcher_2.12: ArtifactInstallerException: Failed to install metadata org.apache.spark:spark-launcher_2.12/maven-metadata.xml: Could not parse metadata /home/jenkins/.m2/repository/org/apache/spark/spark-launcher_2.12/maven-metadata-local.xml: in epilog non whitespace content is not allowed but got > (position: END_TAG seen ...</metadata>\n>... @13:2) -> [Help 1]
```

**Comment by maropu** [comment]
Seems like `master` has the same issue though, this PR targets at branch-3.0? Upgrading it looks fine.

**Comment by dongjoon-hyun** [comment]
@maropu . A PR to `master` branch was created before this PR.
- https://github.com/apache/spark/pull/30304

**Comment by maropu** [comment]
oh, I see.

**Review by maropu — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @maropu !

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to branch-3.0.

**Comment by dongjoon-hyun** [comment]
Thank you, @HyukjinKwon !

**Pull request closed without merging**
