### PR TITLE
[SPARK-12032] [SQL] Joinorder adjustment

### PR DESCRIPTION
**Pull request by flyson**
This change is to adjust the join order of multi-table join so that the join conditions can be correctly pushed down to the Join Operator.

### CODE REVIEW

**Comment by holdenk** [comment]
To help with the review it can be useful to put the JIRA your changes relate to in the title (e.g. [SPARK-...] details)

**Comment by davies** [comment]
@flyson How is this change compared to https://github.com/apache/spark/pull/10073 ?

**Comment by andrewor14** [comment]
@flyson please file a JIRA and put it in the title. See how other patches are opened.

**Comment by rxin** [comment]
Thanks for the pull request. I'm going through a list of pull requests to cut them down since the sheer number is breaking some of the tooling we have. Due to lack of activity on this pull request, I'm going to push a commit to close it. Feel free to reopen it or create a new one.

**Pull request closed without merging**
