### PR TITLE
[DO-NOT-MERBE] Investigate Appveyor failure of master

### PR DESCRIPTION
**Pull request by HyukjinKwon**
### What changes were proposed in this pull request?

Do not merge.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Let me keep investigating in few days. cc @dongjoon-hyun

**Comment by dongjoon-hyun** [comment]
@HyukjinKwon . Is there any progress on this? We are still locked on `4.2.0`.

**Comment by dongjoon-hyun** [comment]
Let's continue to investigation on https://github.com/apache/spark/pull/26457 since `4.3.0` is released. I'll close this~

**Comment by HyukjinKwon** [comment]
Sure, sorry for slow progress : (

**Pull request closed without merging**
