### PR TITLE
[MINOR][DOCS] Add import for MultivariateGaussian to Docs

### PR DESCRIPTION
**Pull request by TheHollidayInn**
### What changes were proposed in this pull request?
I've added import to the docs example.

### Why are the changes needed?
This keeps consistent with the other examples that import the class in the example.

### Does this PR introduce _any_ user-facing change?
Yes, this affects this docs

### CODE REVIEW

**Comment by srowen** [comment]
While you're here, are there any other instances like this that you can see?

**Comment by TheHollidayInn** [comment]
I will double check. I was going through each item and found this one.

**Comment by srowen** [comment]
Jenkins test this please

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
