### PR TITLE
[SPARK-5469] restructure pyspark.sql into multiple files

### PR DESCRIPTION
**Pull request by davies**
All the DataTypes moved into pyspark.sql.types

The changes can be tracked by `--find-copies-harder -M25`

```
davies@localhost:~/work/spark/python$ git diff --find-copies-harder -M25 --numstat master..
2       5       python/docs/pyspark.ml.rst
0       3       python/docs/pyspark.mllib.rst
10      2       python/docs/pyspark.sql.rst
1       1       python/pyspark/mllib/linalg.py
21      14      python/pyspark/{mllib => sql}/__init__.py
14      2108    python/pyspark/{sql.py => sql/context.py}
10      1772    python/pyspark/{sql.py => sql/dataframe.py}
7       6       python/pyspark/{sql_tests.py => sql/tests.py}
8       1465    python/pyspark/{sql.py => sql/types.py}
4       2       python/run-tests
1       1       sql/core/src/main/scala/org/apache/spark/sql/test/ExamplePointUDT.scala
```

Also `git blame -C -C python/pyspark/sql/context.py` to track the history.

### CODE REVIEW

**Comment by davies** [comment]
@rxin I think this PR is ready, the failed tests are flaky, not related to this one.

**Comment by rxin** [comment]
Jenkins, retest this please.

**Comment by rxin** [comment]
Jenkins, retest this please.

**Comment by rxin** [comment]
Thanks. I'm merging this in master and 1.3.

**Pull request closed without merging**
