### PR TITLE
[SPARK-42090][3.3] Introduce sasl retry count in RetryingBlockTransferor

### PR DESCRIPTION
**Pull request by akpatnam25**
### Why are the changes needed?
Previously a boolean variable, saslTimeoutSeen, was used. However, the boolean variable wouldn't cover the following scenario:

1. SaslTimeoutException
2. IOException
3. SaslTimeoutException
4. IOException

Even though IOException at #2 is retried (resulting in increment of retryCount), the retryCount would be cleared at step #4. Since the intention of saslTimeoutSeen is to undo the increment due to retrying SaslTimeoutException, we should keep a counter for SaslTimeoutException retries and subtract the value of this counter from retryCount.

### How was this patch tested?
New test is added, courtesy of Mridul.

Closes #39611 from tedyu/sasl-cnt.

Authored-by: Ted Yu <yuzhihong@gmail.com>
Signed-off-by: Mridul Muralidharan <mridul<at>gmail.com>

### CODE REVIEW

**Comment by akpatnam25** [comment]
@mridulm @dongjoon-hyun backport for 3.2 for SPARK-42090

**Comment by akpatnam25** [comment]
cc @tedyu

**Comment by akpatnam25** [comment]
fyi, this was a clean backport.

**Review by mridulm — APPROVED** [review]
LGTM, will wait for CI to pass

**Comment by mridulm** [comment]
The test failure is unrelated.
Merged to 3.3.
Thanks for backporting this @akpatnam25 !

**Pull request closed without merging**
