### PR TITLE
[SPARK-18319][ML][QA2.1] 2.1 QA: API: Experimental, DeveloperApi, final, sealed audit

### PR DESCRIPTION
**Pull request by hhbyyh**
## What changes were proposed in this pull request?
make a pass through the items marked as Experimental or DeveloperApi and see if any are stable enough to be unmarked. Also check for items marked final or sealed to see if they are stable enough to be opened up as APIs.

Some discussions in the jira: https://issues.apache.org/jira/browse/SPARK-18319

## How was this patch tested?
existing ut

### CODE REVIEW

**Comment by jkbradley** [comment]
test this please

**Comment by jkbradley** [comment]
Quick note: These items will need to be updated in pyspark too.

**Comment by jkbradley** [comment]
Has anyone requested that LDAModel be unsealed?  I'm trying to recall.

**Comment by jkbradley** [comment]
This looks good, except for the pyspark updates.  Thank you @hhbyyh !

**Comment by hhbyyh** [comment]
Thanks for the review @jkbradley . Updated Python part.

**Comment by jkbradley** [comment]
LGTM
merging with master and branch-2.1
Thanks!

**Pull request closed without merging**
