### PR TITLE
[SPARK-50215][SQL] Refactored StringType pattern matching in jdbc code stack

### PR DESCRIPTION
**Pull request by vladanvasi-db**
### What changes were proposed in this pull request?

I propose chaning pattern matching of `StringType` in the `jdbc` code stack.

### Why are the changes needed?

These changes are needed in order to properly handle collated `StringType` in the `jdbc` code stack.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

No testing was needed.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by vladanvasi-db** [comment]
@MaxGekk @stevomitric please take a look at this PR

**Review by MaxGekk — COMMENTED** [review]
@dbatomic @milastdbx  Could you review this PR, please.

**Review by MaxGekk — APPROVED** [review]
Waiting for CI.

**Comment by MaxGekk** [comment]
@vladanvasi-db Could you retrigger only the failed GA [Run / Linters, licenses, and dependencies](https://github.com/vladanvasi-db/spark/actions/runs/11667441583/job/32487401576#logs)

**Comment by vladanvasi-db** [comment]
@MaxGekk the CI has passed now, it is wrongly shown in the ui, all the build tests have passed after retriggering thisGA

**Comment by MaxGekk** [comment]
+1, LGTM. Merging to master.
Thank you, @vladanvasi-db.

**Pull request closed without merging**
