### PR TITLE
[SPARK-48206][SQL][TESTS] Add tests for window rewrites with RewriteWithExpression

### PR DESCRIPTION
**Pull request by kelvinjian-db**
### What changes were proposed in this pull request?

This PR adds more testing for `RewriteWithExpression` around `Window` operators.

### Why are the changes needed?

Adds more testing for `RewriteWithExpression`, which can be fragile around `WindowExpressions`.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Unit tests.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by kelvinjian-db** [comment]
depends on https://github.com/apache/spark/pull/46443

**Comment by kelvinjian-db** [comment]
@cloud-fan

**Comment by cloud-fan** [comment]
sorry it has conflicts now

**Comment by kelvinjian-db** [comment]
fixed

**Review by cloud-fan — APPROVED** [review]

**Pull request closed without merging**
