### PR TITLE
[SPARK-16761][DOC][ML] Fix doc link in docs/ml-guide.md

### PR DESCRIPTION
**Pull request by sundapeng**
## What changes were proposed in this pull request?

Fix the link at http://spark.apache.org/docs/latest/ml-guide.html.
## How was this patch tested?

None

### CODE REVIEW

**Comment by BryanCutler** [comment]
LGTM!

**Comment by srowen** [comment]
Jenkins test this please

**Comment by srowen** [comment]
Merged to master/2.0

**Comment by sundapeng** [comment]
Thank @BryanCutler and @srowen for your review

**Pull request closed without merging**
