### PR TITLE
[SPARK-6486] [MLlib] [Python] Add BlockMatrix to PySpark.

### PR DESCRIPTION
**Pull request by dusenberrymw**
@mengxr This adds the `BlockMatrix` to PySpark.  I have the conversions to `IndexedRowMatrix` and `CoordinateMatrix` ready as well, so once PR #7554 is completed (which relies on PR #7746), this PR can be finished.

### CODE REVIEW

**Comment by mengxr** [comment]
@dusenberrymw Did you coordinate with @MechCoder about this? I thought he already started working on it.

**Comment by dusenberrymw** [comment]
@mengxr We've been discussing things on PR #7554, but I wasn't sure if Manoj was working on this one.  It's a pretty natural extension of 7554, so I already had most of it completed.

@MechCoder Apologies if we were both working on this one.  I've appreciated the thoughts on #7554, and I'd definitely love any thoughts on this one as well so far.

**Comment by mengxr** [comment]
@dusenberrymw Next time, you should check and ping the JIRA page first before you start coding to avoid duplicate work.

**Comment by dusenberrymw** [comment]
@mengxr Yes, certainly.

As soon as you merge #7746, I can finish #7554 and this PR.  I'd also like to work on SPARK-6488.

**Comment by dusenberrymw** [comment]
Jenkins, retest this please.

**Comment by MechCoder** [comment]
@dusenberrymw You could have pinged me on the JIRA, since I already started work on this. (But no hard feelings)

I can give a pass on this after I get back access to my machine on Saturday.

**Comment by dusenberrymw** [comment]
@MechCoder Yes, apologies again for not realizing you were also working on this.  I look forward to your thoughts!

**Comment by mengxr** [comment]
LGTM. Merged into master and branch-1.5. Thanks!

**Comment by dusenberrymw** [comment]
Great, thanks @mengxr!

**Pull request closed without merging**
