### PR TITLE
[SPARK-13843][Streaming]Move streaming-flume, streaming-mqtt, streaming-zeromq, streaming-akka, streaming-twitter to Spark packages

### PR DESCRIPTION
**Pull request by zsxwing**
## What changes were proposed in this pull request?

Currently there are a few sub-projects, each for integrating with different external sources for Streaming.  Now that we have better ability to include external libraries (spark packages) and with Spark 2.0 coming up, we can move the following projects out of Spark to https://github.com/spark-packages
- streaming-flume
- streaming-akka
- streaming-mqtt
- streaming-zeromq
- streaming-twitter

They are just some ancillary packages and considering the overhead of maintenance, running tests and PR failures, it's better to maintain them out of Spark. In addition, these projects can have their different release cycles and we can release them faster.

I have already copied these projects to https://github.com/spark-packages
## How was this patch tested?

Jenkins tests

### CODE REVIEW

**Comment by srowen** [comment]
FWIW I think that's a grand idea. These are fairly ancillary packages and probably the overhead of maintaining them, running tests, patching failures doesn't justify keeping them in the core project. There might even be more packages for which this is true.

**Comment by ksakellis** [comment]
I would also like to see the Kafka modules removed in a similar way. We have had trouble balancing Spark's compatibility requirements and Kafka's every breaking client APIs. By having this clean separation, it makes it easier for user applications to just declare which Kafka client version they want to use.

**Comment by zsxwing** [comment]
retest this please

**Comment by zsxwing** [comment]
retest this please

**Comment by zsxwing** [comment]
cc @rxin @tdas @JoshRosen

**Comment by zsxwing** [comment]
@ksakellis Most of Streaming users use Kafka. It may affect a lot of people. I think it's better to discuss how to support Kafka 0.9 ([SPARK-13252](https://issues.apache.org/jira/browse/SPARK-13252)) before deciding whether moving Kafka out.

**Comment by zsxwing** [comment]
retest this please

**Comment by harishreedharan** [comment]
I agree with @ksakellis on this one. It would be great if we can pull Kafka out as well. I understand that there are a lot of users who might find it difficult, but if you think about it, most people use the plugins via mvn anyway (since we don't actually package them in our assembly). I am not sure what the policy is if we pull it into a different repo and if we can keep the same groupId and artifactId, but that could be an alternative and most likely will not break too many users.

**Comment by JoshRosen** [comment]
Merge conflict is probably my fault (I modified a file that this PR deleted).

**Comment by zsxwing** [comment]
@JoshRosen could you take a look at this PR?

**Comment by harishreedharan** [comment]
Hi @zsxwing, I think the discussion on supporting Kafka 0.9 should happen **if** we decide to keep Kafka in Spark itself. 
At this point, I think the piece that benefits the most out of moving out of Spark is the kafka integration - since that is the one where more of the API compatibility issues are.

I really think we should discuss moving Kafka out and come to an agreement on that as well.

**Comment by rxin** [comment]
Can we have a JIRA ticket to discuss that? I am not sure this github pr is the place to discuss moving kafka out.

**Comment by harishreedharan** [comment]
Thanks @rxin. Opened [SPARK-11806](https://issues.apache.org/jira/browse/SPARK-11806) to discuss this

**Comment by rxin** [comment]
OK apparently the recent mima failures on the master branch is caused by the mqtt dependency not being in maven. We can either fix that with some build hack, or just merge this pr.

Since these are the least contentious choices, I'm going to merge this pull request. We should discuss kafka/kinesis separately.

**Comment by rxin** [comment]
Merging in master.

**Comment by JoshRosen** [comment]
FYI this has been merged but GitHub mirror is lagging; see https://git-wip-us.apache.org/repos/asf?p=spark.git. Until the GitHub merge goes through, I think that PR builds are going to continue to fail since the merge commits that we test are automatically generated by GitHub.

**Comment by steveloughran** [comment]
This didn't cut the relevant doc/streaming-*.md files BTW

**Comment by zsxwing** [comment]
> This didn't cut the relevant doc/streaming-*.md files BTW

Thanks for reminding. I will submit a PR to remove them after I copy all of them to the new projects.

**Pull request closed without merging**
