### PR TITLE
[SPARK-28939][SQL][FOLLOWUP] Avoid useless Properties

### PR DESCRIPTION
**Pull request by mgaido91**
### What changes were proposed in this pull request?

Removes useless `Properties` created according to @hvanhovell 's suggestion.

### Why are the changes needed?

Avoid useless code.

### Does this PR introduce any user-facing change?

No.

### How was this patch tested?

existing UTs

### CODE REVIEW

**Comment by mgaido91** [comment]
cc @cloud-fan @dongjoon-hyun

**Review by cloud-fan — APPROVED** [review]

**Review by hvanhovell — APPROVED** [review]
LGTM

**Review by maropu — APPROVED** [review]

**Comment by maropu** [comment]
Thanks! Merged to master.

**Comment by maropu** [comment]
oh, I didn't notice that the tests not finished..., but, that failuare is not related to this pr.

**Comment by maropu** [comment]
retest this please

**Comment by maropu** [comment]
Just in case, I've checked that the Jenkins tests passed in https://amplab.cs.berkeley.edu/jenkins/view/Spark%20QA%20Test/job/spark-master-test-maven-hadoop-2.7/6838/

**Comment by dongjoon-hyun** [comment]
Late LGTM. Thank you all!

**Pull request closed without merging**
