### PR TITLE
[SPARK-16972][CORE] Move DriverEndpoint out of CoarseGrainedSchedulerBackend

### PR DESCRIPTION
**Pull request by lshmouse**
## What changes were proposed in this pull request?

Move DriverEndpoint out of CoarseGrainedSchedulerBackend and make the two classes clean.
## How was this patch tested?

Pass the unit tests in local.

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by srowen** [comment]
Jenkins test this please

**Comment by lshmouse** [comment]
Jenkins test this please

**Comment by lshmouse** [comment]
Jenkins test this please

**Comment by lshmouse** [comment]
@srowen Please help to trigger the Jenkins test, Thanks~

**Comment by lshmouse** [comment]
@zsxwing @srowen 
Could you  please help to review this patch? Thanks~

**Comment by jerryshao** [comment]
Do you have any specific reason or use case that have to refactor this part?

IMHO, I think unless we have a concrete reason to change it, it is better not to do refactoring on this critical path. Currently from what I understood of this patch, it only changes the code structure, it may not be so necessary to do it.

**Comment by lshmouse** [comment]
@jerryshao 
The patch doesn't just change the code structure. It distinguish the responsibility of these two classes.
What's more, it's the first step to refactor the schedule path, because the codes of TaskSchedulerImpl and CoarseGrainedSchedulerBackend depend on each other and are hard to understand and debug.

**Comment by vanzin** [comment]
retest this please

**Comment by zsxwing** [comment]
Agreed with @jerryshao. @lshmouse  could you submit the whole refactoring PR in order to show why this one is necessary? It's better to not refactor stable code paths unless there is a strong reason.

**Comment by vanzin** [comment]
I'd rather not see a huge refactoring PR, but instead a document that outlines what would be done and the reasons for it. It's better if the PRs themselves are small-ish.

**Comment by jaceklaskowski** [comment]
Finally someone took the responsibility and is clearing that important and critical path in Spark Core. Whenever I see the code, I feel what @lshmouse felt -- it has to be refactored to invite further contributions. Kudos @lshmouse!

**Comment by jaceklaskowski** [comment]
LGTM

**Comment by vanzin** [comment]
@lshmouse did you get the chance to write a document / something explaining what's the long term goal for this change?

The way it is, I don't see it helping much. There's still a lot of coupling between these two classes, so the fact that they now live in different source files doesn't really make things easier to understand - in fact one could argue it can make things more complicated because you had to add *more* methods in the backend to expose functionality needed by the driver endpoint.

**Comment by vanzin** [comment]
If there's no long-term goal for these changes we should close this PR. By itself I don't see it making things any less complicated.

**Pull request closed without merging**
