### PR TITLE
[SPARK-34995] Port/integrate Koalas remaining codes into PySpark

### PR DESCRIPTION
**Pull request by itholic**
### What changes were proposed in this pull request?

There are some more changes in Koalas such as [databricks/koalas#2141](https://github.com/databricks/koalas/commit/c8f803d6becb3accd767afdb3774c8656d0d0b47), [databricks/koalas#2143](https://github.com/databricks/koalas/commit/913d68868d38ee7158c640aceb837484f417267e) after the main code porting, this PR is to synchronize those changes with the `pyspark.pandas`.

### Why are the changes needed?

We should port the whole Koalas codes into PySpark and synchronize them.

### Does this PR introduce _any_ user-facing change?

Fixed some incompatible behavior with pandas 1.2.0 and added more to the `to_markdown` docstring.

### How was this patch tested?

Manually tested in local.

### CODE REVIEW

**Comment by itholic** [comment]
cc @ueshin @xinrong-databricks 

Would you please take a look at this when you find some time? :-)

**Comment by HyukjinKwon** [comment]
Are they all changes to port? Might be good to confirm with @ueshin

**Comment by itholic** [comment]
Yeah, it includes the all changes after the porting in the main code.

**Review by ueshin — APPROVED** [review]
Yes, databricks/koalas#2141 and databricks/koalas#2143 are the commits after the first porting in the main code.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by HyukjinKwon** [comment]
Seems like it broke the tests:

```

======================================================================
ERROR [4.255s]: test_frame_iloc_setitem (pyspark.pandas.tests.test_indexing.IndexingTest)
----------------------------------------------------------------------
ValueError: setting an array element with a sequence.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/__w/spark/spark/python/pyspark/pandas/tests/test_indexing.py", line 1093, in test_frame_iloc_setitem
    kdf.iloc[0, 0] = -kdf.max_speed
AssertionError: "Incompatible indexer with Series" does not match "setting an array element with a sequence."

======================================================================
ERROR [13.432s]: test_series_iloc_setitem (pyspark.pandas.tests.test_indexing.IndexingTest)
----------------------------------------------------------------------
ValueError: setting an array element with a sequence.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/__w/spark/spark/python/pyspark/pandas/tests/test_indexing.py", line 1238, in test_series_iloc_setitem
    kser.iloc[1] = kdf[["b"]]
AssertionError: "Incompatible indexer with DataFrame" does not match "setting an array element with a sequence."

----------------------------------------------------------------------
Ran 39 tests in 221.061s

FAILED (errors=2, skipped=5)
```

I am going to revert this. @itholic can you take a look please?

**Comment by dongjoon-hyun** [comment]
Oh, interesting. The test seems to pass`GitHub Action` and `Jenkins` before merging. And, it fails at master branch.

**Comment by itholic** [comment]
@dongjoon-hyun Yeah, this PR was created before https://github.com/apache/spark/pull/32152 merged, which include `test_indexing.py` that causes test failure at master branch.

I should have better to checked that PR and apply the changes to this PR.  😅

Thanks for pointing it out!

**Pull request closed without merging**
