### PR TITLE
[SPARK-44985][CORE] Use toString instead of stacktrace for task reaper threadDump

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

In addition to the stack trace, the `toString` function includes information on the thread's ID, name, state, locks, and held locks.

### Why are the changes needed?

improve debug messages for task reaper

### Does this PR introduce _any_ user-facing change?

yes, log changes

### How was this patch tested?

existing ut

### Was this patch authored or co-authored using generative AI tooling?

no

### CODE REVIEW

**Comment by yaooqinn** [comment]
cc @zhengruifeng @cloud-fan @HyukjinKwon @dongjoon-hyun, thanks

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM for Apache Spark 4.
Thank you, @yaooqinn .

**Comment by dongjoon-hyun** [comment]
Merged to master.

**Comment by yaooqinn** [comment]
Thank you @dongjoon-hyun

**Pull request closed without merging**
