### PR TITLE
[INFRA] Close stale PRs

### PR DESCRIPTION
**Pull request by HyukjinKwon**
## What changes were proposed in this pull request?

This PR proposes to close stale PRs, mostly the same instances with https://github.com/apache/spark/pull/18017

I believe the author in #14807 removed his account.

Closes #7075
Closes #8927
Closes #9202
Closes #9366
Closes #10861
Closes #11420
Closes #12356
Closes #13028
Closes #13506
Closes #14191
Closes #14198
Closes #14330
Closes #14807
Closes #15839
Closes #16225
Closes #16685
Closes #16692
Closes #16995
Closes #17181
Closes #17211
Closes #17235
Closes #17237
Closes #17248
Closes #17341
Closes #17708
Closes #17716
Closes #17721
Closes #17937

Added:
Closes #14739
Closes #17139
Closes #17445
Closes #18042
Closes #18359

Added:
Closes #16450
Closes #16525
Closes #17738

Added:
Closes #16458
Closes #16508
Closes #17714

Added:
Closes #17830
Closes #14742

## How was this patch tested?

N/A

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Please let me know if any author is active on any PR. Let me take them out. I picked up inclusively.

**Comment by HyukjinKwon** [comment]
Please let me know if any author is active on any PR. Let me take them out. I picked up inclusively. My point here is to close inactive PRs and leave PRs that wait for a review. Leave any comment if it is in a progress in any way.

**Comment by HyukjinKwon** [comment]
Please let me know if any author is active on any PR. Let me take them out. I picked up inclusively. My point here is to close inactive PRs and leave PRs that wait for a review. Leave any comment if it is in a progress in any way. If missed, reopening would be welcome.

**Comment by HyukjinKwon** [comment]
cc @srowen, @vanzin, @gatorsmile and @jiangxb1987 who I believe are interested in this PR. Could you take a look please?

**Comment by srowen** [comment]
Suggest adding:
https://github.com/apache/spark/pull/14739
https://github.com/apache/spark/pull/17139
https://github.com/apache/spark/pull/17445
https://github.com/apache/spark/pull/18042
https://github.com/apache/spark/pull/18359

**Comment by jiangxb1987** [comment]
Let's keep the following PRs open, because I believe they're good to have and the authors will soon be responding:
#15405
#17401
#17716

Also, I'd suggest we add the following PRs to the list:
#16450
#16525
#17738

Thanks!

**Comment by HyukjinKwon** [comment]
I added all suggested one and took out 15405 and 17716 per requested. I guess the author should be responsive and I took out 17716 before. I think it is unfair to take out this again.

**Comment by HyukjinKwon** [comment]
I added all suggested one and took out 15405 and 17401 per requested. I guess the author should be responsive and I took out 17716 before. I think it is unfair to take out this again.

**Comment by imatiach-msft** [comment]
an you please keep 17084 open?  thanks!

**Comment by HyukjinKwon** [comment]
Sure.

**Comment by jiangxb1987** [comment]
Please add the following:
#16458
#16508
#17714

Thanks!

**Comment by HyukjinKwon** [comment]
Added.

**Comment by HyukjinKwon** [comment]
14957 was taken out as closed.

**Comment by gatorsmile** [comment]
Three more PRs?
https://github.com/apache/spark/pull/17830
https://github.com/apache/spark/pull/14742
https://github.com/apache/spark/pull/17211

**Comment by HyukjinKwon** [comment]
Sure.

**Comment by HyukjinKwon** [comment]
(17211 is a dupe)

**Comment by HyukjinKwon** [comment]
12257 was taken out as closed.

**Comment by ScrapCodes** [comment]
15258 can also be taken out

**Comment by HyukjinKwon** [comment]
Sure, I did.

**Comment by srowen** [comment]
Merged this pass to master

**Pull request closed without merging**
