### PR TITLE
[MINOR][DOCS] Fix typos in ScalaDocs for DataStreamWriter#foreachBatch

### PR DESCRIPTION
**Pull request by ammar1x**
The title is pretty self-explanatory.

### What changes were proposed in this pull request?

Fixing typos in the docs for `foreachBatch` functions.

### Why are the changes needed?

To fix typos in JavaDoc/ScalaDoc.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Yes.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Looks fine though the linter complains about the line length. Can you take a look for this file and see if there are some more typos since you're here?

**Comment by srowen** [comment]
Jenkins test this please

**Comment by srowen** [comment]
Oh shoot I missed that this fails the linter. @ammar1x can you fix that?

**Comment by ammar1x** [comment]
HyukjinKwon: I couldn't find any other typos in this file :)
srowen: I think it should be fixed now

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
