### PR TITLE
[SPARK-26897][SQL][TEST][FOLLOW-UP] Remove workaround for 2.2.0 and 2.1.x in HiveExternalCatalogVersionsSuite

### PR DESCRIPTION
**Pull request by maropu**
## What changes were proposed in this pull request?
This pr just removed workaround for 2.2.0 and 2.1.x in HiveExternalCatalogVersionsSuite.

## How was this patch tested?
Pass the Jenkins.

### CODE REVIEW

**Comment by maropu** [comment]
@srowen @dongjoon-hyun If no problem, could you merge this?

**Review by srowen — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master, branch-2.4, and branch-2.3.

**Review by dongjoon-hyun — COMMENTED** [review]
+1, late LGTM, too.

**Comment by srowen** [comment]
Oh @HyukjinKwon would branch-2.4 and branch-2.3 still potentially be testing vs older Spark versions? I had thought this was for master.

**Comment by HyukjinKwon** [comment]
Hm, I thought we disabled tests for those EOL releases by:

https://github.com/apache/spark/commit/bb9745904f4c439be21fa435f2bb5c66de164f61#diff-451a407d92e675bc747901202e46472a

https://github.com/apache/spark/commit/b6c464997e179bf648250435dfe6295c84e76784#diff-451a407d92e675bc747901202e46472a

**Comment by srowen** [comment]
I guess that's fine; if a release is EOL now but wasn't when the branch was started, still reasonable to stop testing it in the branch.

**Comment by HyukjinKwon** [comment]
I see. Thanks, @srowen. BTW, Please feel free to revert this in branch-2.3 and branch-2.4 @srowen if you see any other concern later. I don't mind at all.

**Pull request closed without merging**
