### PR TITLE
[SPARK-10046] [SQL] Hive warehouse dir not set in current directory when not …

### PR DESCRIPTION
**Pull request by xwu0226**
Doc change to align with HiveConf default in terms of where to create `warehouse` directory.

### CODE REVIEW

**Comment by xwu0226** [comment]
@marmbrus and @yhuai , how do you think about this doc change? Thanks!

**Comment by xwu0226** [comment]
@rxin would you please review this doc change? Thank you very much!

**Comment by rxin** [comment]
I've merged this. Thanks.

**Comment by xwu0226** [comment]
@rxin , thank you very much!

**Pull request closed without merging**
