### PR TITLE
[SPARK-43380][SQL][Follow-up] Fix slowdown in Avro read

### PR DESCRIPTION
**Pull request by zeruibao**
### What changes were proposed in this pull request?
Fix slowdown in Avro read. There is a https://github.com/apache/spark/pull/42503 that causes the performance regression. It seems that `SQLConf.get.getConf(confKey)` is very costly. Move it out of `newWriter` function.

### Why are the changes needed?
Need to fix the performance regression of Avro read.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Existing UT test

### Was this patch authored or co-authored using generative AI tooling?
No

### CODE REVIEW

**Review by gengliangwang — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by zeruibao** [comment]
Hi @gengliangwang and @dongjoon-hyun, all avro related tests have passed. Should be good to merge now haha.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by gengliangwang** [comment]
Thanks,merging to master/branch-3.5

**Review by beliefer — COMMENTED** [review]
LGTM later.

**Pull request closed without merging**
