### PR TITLE
[BUILD] Close stale PRs

### PR DESCRIPTION
**Pull request by maropu**
## What changes were proposed in this pull request?
This pr proposed to close stale PRs. Currently, we have 400+ open PRs and there are some stale PRs whose JIRA tickets have been already closed and whose JIRA tickets does not exist (also, they seem not to be minor issues).

// Open PRs whose JIRA tickets have been already closed
Closes #11785
Closes #13027
Closes #13614
Closes #13761
Closes #15197
Closes #14006
Closes #12576
Closes #15447
Closes #13259
Closes #15616
Closes #14473
Closes #16638
Closes #16146
Closes #17269
Closes #17313
Closes #17418
Closes #17485
Closes #17551
Closes #17463
Closes #17625

// Open PRs whose JIRA tickets does not exist and they are not minor issues
Closes #10739
Closes #15193
Closes #15344
Closes #14804
Closes #16993
Closes #17040
Closes #15180
Closes #17238

## How was this patch tested?
N/A

### CODE REVIEW

**Comment by maropu** [comment]
IIUC I listed up the PRs that it is worth closing.  Cloud you check this? (I pinged you cuz you opened possibly similar PRs) cc: @srowen @HyukjinKwon

**Review by srowen — APPROVED** [review]

**Review by HyukjinKwon — APPROVED** [review]
I hope the PRs in the latter case are double-checked by committers while this PR is open though.

**Comment by maropu** [comment]
Thanks for checking, guys! yea, I also think the double-checking is needed there.

**Comment by HyukjinKwon** [comment]
Oh @maropu, BTW, does just "Close" work too? I haven't tested the merge script but I thought it should be "Closes".

**Comment by maropu** [comment]
oh, yea, I'll fix soon. Thanks!

**Pull request closed without merging**
