### PR TITLE
[SPARK-29189][FOLLOW-UP][SQL] Beautify config name

### PR DESCRIPTION
**Pull request by wangshisan**
### What changes were proposed in this pull request?
Beautify comment

### Why are the changes needed?
The config name now is pretty weird.

### Does this PR introduce any user-facing change?
No

### How was this patch tested?
No test.

### CODE REVIEW

**Comment by wangyum** [comment]
ok to test

**Comment by HyukjinKwon** [comment]
cc @squito

**Comment by HyukjinKwon** [comment]
retest this please

**Review by HyukjinKwon — APPROVED** [review]

**Review by squito — APPROVED** [review]
lgtm

**Review by cloud-fan — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Merged to master. Thank you all!

**Pull request closed without merging**
