### PR TITLE
[SPARK-5297][Streaming][backport] Backport SPARK-5297 to Spark 1.2

### PR DESCRIPTION
**Pull request by jerryshao**

### CODE REVIEW

**Comment by jerryshao** [comment]
Jenkins, retest this please.

**Comment by jerryshao** [comment]
Quite strange the test is OK in my local test but failed in Jenkins.

**Comment by jerryshao** [comment]
Jenkins, retest this please.

**Comment by jerryshao** [comment]
Jenkins, retest this please.

**Comment by jerryshao** [comment]
Hi @pwendell , would you mind taking a look at this backport PR, thanks a lot.

**Comment by tdas** [comment]
@jerryshao We generally dont make binary compatibility changes within patch releases. So I dont think this is a good idea. If there is a way this fix can be made without breaking binary compatibility, I can consider merging.

**Comment by srowen** [comment]
@jerryshao Given the comment from @tdas, let's close this PR and not merge this change into 1.2.x. I think that's prudent.

**Comment by jerryshao** [comment]
OK, I will close this PR, thanks a lot for your comments.

**Pull request closed without merging**
