### PR TITLE
[SPARK-24159] [SS] Enable no-data micro batches for streaming mapGroupswithState

### PR DESCRIPTION
**Pull request by tdas**
## What changes were proposed in this pull request?

Enabled no-data batches in flatMapGroupsWithState in following two cases.
- When ProcessingTime timeout is used, then we always run a batch every trigger interval. 
- When event-time watermark is defined, then the user may be doing arbitrary logic against the watermark value even if timeouts are not set. In such cases, it's best to run batches whenever the watermark has changed, irrespective of whether timeouts (i.e. event-time timeout) have been explicitly enabled.   

## How was this patch tested?
updated tests

### CODE REVIEW

**Comment by tdas** [comment]
@zsxwing  can you take a look?

**Comment by zsxwing** [comment]
LGTM pending tests

**Comment by tdas** [comment]
@zsxwing can you take another look?

**Comment by zsxwing** [comment]
LGTM again. Merging to master.

**Comment by koertkuipers** [comment]
we are testing spark 2.4 internally and had some unit tests break because of this change i believe.

i am not suggesting this should be changed or undone, just wanted to point out that it might have minor implications for people upgrading. so this is just an FYI.

it seems that our unit tests for logic that uses flatMapGroupsWithState with GroupStateTimeout.ProcessingTimeTimeout now will hang if query.processAllAvailable() is called. so i am looking for an alternative way to test now that does not involve usage of processAllAvailable.

**Pull request closed without merging**
