### PR TITLE
[MINOR][INFRA] Comments in GitHub scripts should start with #

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to fix a typo in github action script, `comments` in GitHub scripts should start with `#`.

### Why are the changes needed?
In the GitHub runtime logs, we often observe runtime prompts similar to the one below:
https://github.com/panbingkun/spark/actions/runs/7167111730/job/19513821177
https://github.com/panbingkun/spark/actions/runs/7167111730/job/19513823103
image
Although it does not affect the overall task execution, I think it is necessary to correct it.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Manually test.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by panbingkun** [comment]
cc @LuciferYang

**Review by LuciferYang — APPROVED** [review]
+1, LGTM
Good Catch

**Comment by LuciferYang** [comment]
Is this the only case?

**Comment by panbingkun** [comment]
> Is this the only case?

Yes, I `grep` and only found this place so far.

**Review by zhengruifeng — APPROVED** [review]

**Comment by zhengruifeng** [comment]
thanks, merged to master

**Pull request closed without merging**
