### PR TITLE
[SPARK-38587][SQL] Validating new location for rename command should use formatted names

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

Fix bug for `getDatabase` with a unformatted database name.

```java
[info] - ALTER TABLE .. RENAME using V1 catalog V1 command: newName *** FAILED *** (61 milliseconds)
[info]   org.apache.spark.sql.catalyst.analysis.NoSuchDatabaseException: Database 'CaseUpperCaseLower' not found
[info]   at org.apache.spark.sql.catalyst.catalog.ExternalCatalog.requireDbExists(ExternalCatalog.scala:42)
[info]   at org.apache.spark.sql.catalyst.catalog.ExternalCatalog.requireDbExists$(ExternalCatalog.scala:40)
[info]   at org.apache.spark.sql.catalyst.catalog.InMemoryCatalog.requireDbExists(InMemoryCatalog.scala:47)
[info]   at org.apache.spark.sql.catalyst.catalog.InMemoryCatalog.getDatabase(InMemoryCatalog.scala:171)
[info]   at org.apache.spark.sql.catalyst.catalog.ExternalCatalogWithListener.getDatabase(ExternalCatalogWithListener.scala:65)
[info]   at org.apache.spark.sql.catalyst.catalog.SessionCatalog.validateNewLocationOfRename(SessionCatalog.scala:1863)
[info]   at org.apache.spark.sql.catalyst.catalog.SessionCatalog.renameTable(SessionCatalog.scala:739)
[info]   at org.apache.spark.sql.execution.command.AlterTableRenameCommand.run(tables.scala:209
```

### Why are the changes needed?

bugfix

### Does this PR introduce _any_ user-facing change?

no, bugfix
### How was this patch tested?

added new tests

### CODE REVIEW

**Comment by yaooqinn** [comment]
cc @HyukjinKwon @cloud-fan @gengliangwang

**Review by cloud-fan — APPROVED** [review]

**Comment by cloud-fan** [comment]
how far shall we backport this?

**Comment by yaooqinn** [comment]
> how far shall we backport this?

Since v2.4.0 / https://issues.apache.org/jira/browse/SPARK-24675, maybe 3.0 if it is not EOL?

**Comment by cloud-fan** [comment]
yea let's backport it to 3.0 and above.

**Comment by yaooqinn** [comment]
thanks, @cloud-fan, merged to master/3.3/3.2/3.1/3.0

**Pull request closed without merging**
