### PR TITLE
[CORE][MINOR] - Add minor code change to TaskState and Task

### PR DESCRIPTION
**Pull request by erenavsarogullari**
## What changes were proposed in this pull request?
- TaskState and ExecutorState expose isFailed and isFinished functions. It can be useful to add test coverage for different states. Currently, Other enums do not expose any functions so this PR aims just these two enums.
- `private` access modifier is added for Finished Task States Set
- A minor doc change is added.
## How was this patch tested?

New Unit tests are added and run locally.

### CODE REVIEW

**Comment by rxin** [comment]
hm I agree having good unit test coverage is important -- this seems too trivial to test?

**Comment by erenavsarogullari** [comment]
Hi @rxin, 

Firstly, thanks for quick reply.

I was thinking for unit-test coverage perspective and a starter point to contribute project but it is ok for me if PR is closed as well ;)

**Comment by srowen** [comment]
This is to some degree covered by other tests, yes. It's probably just not worth 100 lines of test code to test the contents of a Set from all angles.

I think the other two non-test changes are trivial but I'd be willing to commit them.

**Comment by erenavsarogullari** [comment]
Thanks @srowen for the comment. The change-set looks ready.

**Comment by srowen** [comment]
OK, can you modify the title? it becomes the commit message. "Minor code change to TaskState and Task" or something.

Normally I'd say this is too trivial to commit by itself but I know it didn't start that way, and because it's a first commit I'm more inclined to merge even a little part of it to get you through the process once.

**Comment by erenavsarogullari** [comment]
Thanks @srowen. PR Title is updated.

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
