### PR TITLE
[SPARK-39160][SQL] Remove workaround for ARROW-1948

### PR DESCRIPTION
**Pull request by pan3793**
### What changes were proposed in this pull request?

Remove workaround for ARROW-1948(got fixed in arrow 0.9) which originally comes from SPARK-22530

### Why are the changes needed?

Remove unnecessary code.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

The exsiting UT `ArrowColumnVectorSuite`

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @BryanCutler

**Review by sunchao — APPROVED** [review]
LGTM

**Review by BryanCutler — APPROVED** [review]
LGTM

**Comment by BryanCutler** [comment]
merged to master, thanks @pan3793

**Review by dongjoon-hyun — COMMENTED** [review]
+1, LGTM. Thank you all.

**Pull request closed without merging**
