### PR TITLE
[SPARK-40381][DEPLOY] Support standalone worker recommission

### PR DESCRIPTION
**Pull request by warrenzhu25**
### What changes were proposed in this pull request?
Support standalone worker recommission from master rest api

### Why are the changes needed?
Support standalone worker recommission is neeeded.

### Does this PR introduce _any_ user-facing change?
Yes. Added a new api in standalone master to recommission workers

### How was this patch tested?
Added tests in `MasterSuite`

### CODE REVIEW

**Comment by warrenzhu25** [comment]
@dongjoon-hyun Could you help take a look?

**Comment by dongjoon-hyun** [comment]
Sorry, but I don't use Standalone cluster.

**Comment by warrenzhu25** [comment]
> Sorry, but I don't use Standalone cluster.

Any ideas who is right person to review this?

**Comment by holdenk** [comment]
Whats the intent of recommissioning? I don't super get it normally decommissioning means the worker is going away is this for the situation where (for example) planned maintance is cancelled?

**Comment by warrenzhu25** [comment]
> Whats the intent of recommissioning? I don't super get it normally decommissioning means the worker is going away is this for the situation where (for example) planned maintance is cancelled?

@holdenk Thanks for looking at this. We're doing manually scaling up and down workers based on spark metric. Manually means we're using master rest api to kill workers. Let's say we have 10 nodes to be decommissioned. 9 nodes finished quickly, but the last one took long as it might have more shuffle data to migrate or some long tail tasks still running. So we want to cancel the long tail node decommission to avoid shuffle data loss or task failure as during decommission it can't run new tasks it's waste of resource.

**Pull request closed without merging**
