### PR TITLE
[SPARK-5165][SQL] Add support for rollup and cube in sqlcontext

### PR DESCRIPTION
**Pull request by scwf**

### CODE REVIEW

**Comment by chenghao-intel** [comment]
The SQL enhanced aggregation syntax may looks like in HiveContext as:
```
GROUP BY expression list WITH ROLLUP
GROUP BY expression list WITH CUBE
GROUP BY expression list, GROUPING SETS (expression list2)
```
See https://cwiki.apache.org/confluence/display/Hive/Enhanced+Aggregation,+Cube,+Grouping+and+Rollup
Currently in logical analysis and execution, we follows the Hive's specification, however, in SQL99, it also supports the format like:
```
GROUP BY expression list, GROUPING SETS (expression list2), expression list3
GROUP BY expression list, CUBE(expression list2), expression list3
GROUP BY expression list, ROLLUP(expression list2), expression list3
```
The `grouping column reference list` is optionally required by `CUBE` and `ROLLUP` (http://savage.net.au/SQL/sql-99.bnf.html) , and there are some additional work need to be done on the `Logical Node` and `Analyzer` to support the semantics like for this.

Probably we'd better implement the Hive-Like format first in SQLContext, what do you think?

**Comment by scwf** [comment]
Hi @chenghao-intel , actually this syntax is referred to TPC-DC benchmark. If we want to follow hiveQL syntax in sqlcontext i agree with you, but i am not sure this is a good idea.

**Comment by chenghao-intel** [comment]
@scwf, I can understand we need to make it compatible with the TPC-DC.

In SQL Server 2008, I found the format you suggested is one of the variances:
http://technet.microsoft.com/en-us/library/bb522631(v=sql.105).aspx

In MySQL, seems it works in the way of Hive does:
http://dev.mysql.com/doc/refman/5.6/en/group-by-modifiers.html

And both variances are the subset of SQL 99 spec's, I don't mind which format is supported first, and we can add the other later on.
@marmbrus , not sure if you have any concerns on what the specs that we should follow for SQLContext parser.

**Comment by scwf** [comment]
i am closing this.

**Pull request closed without merging**
