### PR TITLE
[SPARK-32492][SQL][FOLLOWUP][test-maven] Fix jenkins maven jobs

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

The newly added test fails Jenkins maven jobs, see https://github.com/apache/spark/pull/29303#discussion_r464729021

We move the test from `ThriftServerWithSparkContextSuite` to `SparkMetadataOperationSuite`, the former uses an embedded thrift server where the server and the client are in the same JVM process and the latter forks a new process to start the server where the server and client are isolated.
The sbt runner seems to be fine with the test in the `ThriftServerWithSparkContextSuite`, but the maven runner with `scalates`t plugin will face the classloader issue as we will switch classloader to the one in the `sharedState` which is not the one that hive uses to load some classes. This is more like an issue that belongs to the maven runner or the `scalatest`.
So in this PR, we simply move it to bypass the issue.

BTW, we should test against the way of using embedded thrift server to verify whether it is just a maven issue or not, there could be some use cases with this API.

### Why are the changes needed?

Jenkins recovery

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

modified uts

### CODE REVIEW

**Comment by yaooqinn** [comment]
cc @cloud-fan @dongjoon-hyun, let's see whether the JDBC client could pass maven jobs or not. thanks very much.

**Comment by dongjoon-hyun** [comment]
@yaooqinn . It's still failing. In that case, you had better mark this as `WIP`.
```
- check results from get columns operation from thrift server *** FAILED ***
  org.apache.hive.service.cli.HiveSQLException: java.lang.RuntimeException: org.apache.hadoop.hive.ql.metadata.HiveException: java.lang.ClassCastException: org.apache.hadoop.hive.ql.security.HadoopDefaultAuthenticator cannot be cast to 
```

**Comment by cloud-fan** [comment]
Seems `HiveThriftServer2Test` and `SharedThriftServer` test 2 different ways to connect to the thrift server, but `SharedThriftServer` has problems to test certain APIs like `getColumns`.

**Comment by yaooqinn** [comment]
retest this please

**Comment by yaooqinn** [comment]
retest this please

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Comment by dongjoon-hyun** [comment]
Thank you, @yaooqinn and @cloud-fan !

**Pull request closed without merging**
