### PR TITLE
[SPARK-14298] [ML] [MLlib] Add unit test for EM LDA disable checkpointing

### PR DESCRIPTION
**Pull request by yanboliang**
## What changes were proposed in this pull request?

This is follow up for #12089, add unit test for EM LDA which test disable checkpointing when set `checkpointInterval = -1`.
## How was this patch tested?

unit test.

cc @jkbradley

### CODE REVIEW

**Comment by holdenk** [comment]
We could maybe make this a more complete test and actually check that their are no checkpoint files generated? Although that might be over kill.

**Comment by yanboliang** [comment]
@holdenk Thanks for your comments! Actually ```model.getCheckpointFiles.isEmpty``` checked that their are no checkpoint files generated.

**Comment by holdenk** [comment]
@yanboliang that makes sense. I was thinking maybe checking the actual checkpoint directory to catch anything else (or even just clearing the checkpoint directory so checkpointing fails), but if `getCheckpointFiles` was correct even before the fix than that is probably a fine way to test it to.

**Comment by jkbradley** [comment]
@holdenk I agree with you, but I'm worried it could fail if checkpoint deletion/cleanup does not happen quickly enough across tests in this suite.  I'd prefer to leave it as is.

**Comment by jkbradley** [comment]
@yanboliang Thanks!  LGTM
Merging with master

**Pull request closed without merging**
