### PR TITLE
[SPARK-8897][SPARKR] SparkR DataFrame fail to return data of float type.

### PR DESCRIPTION
**Pull request by sun-rui**

### CODE REVIEW

**Comment by viirya** [comment]
@sun-rui I think this is duplicate to #7280.

**Comment by shivaram** [comment]
@sun-rui Lets use the other PR as it also has a test case in it. I think the test case can be improved and you can help review it.

**Comment by sun-rui** [comment]
OK

**Comment by shivaram** [comment]
@sun-rui Could you close this PR ? Only people who open the PR have permission to close it right now.

**Pull request closed without merging**
