### PR TITLE
[SPARK-6227][MLLIB][PYSPARK] Implement PySpark wrappers for SVD and PCA (v2)

### PR DESCRIPTION
**Pull request by MLnick**
Add PCA and SVD to PySpark's wrappers for `RowMatrix` and `IndexedRowMatrix` (SVD only).

Based on #7963, updated.

## How was this patch tested?

New doc tests and unit tests. Ran all examples locally.

### CODE REVIEW

**Comment by MLnick** [comment]
Based on @MechCoder's work in #7963.

cc @holdenk @dusenberrymw

**Comment by holdenk** [comment]
Thanks for reviving this @MLnick :)

**Review by dusenberrymw — COMMENTED** [review]
Yeah, great to see this being finished up, @MLnick.  LGTM.

**Comment by MechCoder** [comment]
Thanks @MLnick !

**Comment by MLnick** [comment]
If no further comments I'll merge this into branch-2.2 within a few days.

**Comment by MLnick** [comment]
Jenkins retest this please

**Comment by holdenk** [comment]
LGTM

**Comment by MLnick** [comment]
Merged to master/branch-2.2. Thanks again for the original work @MechCoder!

**Comment by SixAlien3** [comment]
@MLnick Hi, I'm interesting in this PySpark wrapper for SVD. How many columns can this support? Cuz I see in the old document it can only support columns <1000. How about this wrapper?

**Pull request closed without merging**
