### PR TITLE
[SPARK-42656][CONNECT][Followup] Improve the script to start spark-connect server

### PR DESCRIPTION
**Pull request by zhenlineo**
### What changes were proposed in this pull request?
Make the server to start with Hive dependency and make the script to build with the correct scala version set in pom files.
Also allow the server to take any extra spark configurations.

### Why are the changes needed?
Adding hive dependency to allow some tests of write ops easier.
Allow the server to start with the same Scala version set in the project.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Manually tested.

### CODE REVIEW

**Review by hvanhovell — APPROVED** [review]
LGTM

**Comment by amaliujia** [comment]
LGTM

**Comment by zhenlineo** [comment]
Or even better? -> https://github.com/apache/spark/pull/40305

**Review by LuciferYang — APPROVED** [review]
+1, LGTM

**Comment by hvanhovell** [comment]
Merging

**Pull request closed without merging**
