### PR TITLE
[SPARK-14515][DOC] Add python example for ChiSqSelector

### PR DESCRIPTION
**Pull request by zhengruifeng**
## What changes were proposed in this pull request?

Add the missing python example for ChiSqSelector
## How was this patch tested?

manual tests

### CODE REVIEW

**Comment by holdenk** [comment]
This looks good to me, I manually ran the example with spark-submit to verify. Maybe @jkbradley or @mengxr could take a look?

**Comment by yanboliang** [comment]
LGTM

**Comment by jkbradley** [comment]
Thanks all!  I'll take a look now

**Comment by jkbradley** [comment]
LGTM too
Merging with master
Thanks!

**Pull request closed without merging**
