### PR TITLE
[SPARK-31235][FOLLOWUP][TESTS][test-hadoop3.2] Fix test "specify a more specific type for the ap…

### PR DESCRIPTION
**Pull request by wang-zhun**
### What changes were proposed in this pull request?
Update the input parameters for instantiating `RMAppManager` and `ClientRMService`

### Why are the changes needed?
For hadoop3.2, if `RMAppManager` is not created correctly, the following exception will occur:
```
java.lang.RuntimeException: java.lang.NullPointerException
	at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:135)
	at org.apache.hadoop.yarn.security.YarnAuthorizationProvider.getInstance(YarnAuthorizationProvider.java:55)
	at org.apache.hadoop.yarn.server.resourcemanager.RMAppManager.<init>(RMAppManager.java:117)
```

### How was this patch tested?
UTs

### CODE REVIEW

**Comment by wang-zhun** [comment]
test this please

**Comment by viirya** [comment]
ok to test

**Comment by wang-zhun** [comment]
@viirya How to specify "Hadoop profile hadoop3.2" to perform the test

**Comment by tgravescs** [comment]
test this please

**Review by jiangxb1987 — APPROVED** [review]
LGTM

**Comment by tgravescs** [comment]
test this please

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by dongjoon-hyun** [comment]
Hi, @tgravescs . Could you review this PR?

**Review by tgravescs — APPROVED** [review]
changes look fine to me, I was running the tests multiple times since this seemed to be intermittent failure

**Comment by tgravescs** [comment]
merging this to master

**Comment by dongjoon-hyun** [comment]
Thank you so much, @tgravescs !

**Comment by dongjoon-hyun** [comment]
Ur, in `Maven` environment, this seems to cause more UT failures in the other suite.
- https://amplab.cs.berkeley.edu/jenkins/view/Spark%20QA%20Test%20(Dashboard)/job/spark-master-test-maven-hadoop-3.2-hive-2.3/407/

It seems that this have a side effect.
```
Test Result (11 failures / +7)
org.apache.spark.deploy.yarn.YarnClusterSuite.run Spark in yarn-client mode
org.apache.spark.deploy.yarn.YarnClusterSuite.run Spark in yarn-cluster mode with different configurations, ensuring redaction
org.apache.spark.deploy.yarn.YarnClusterSuite.yarn-cluster should respect conf overrides in SparkHadoopUtil (SPARK-16414, SPARK-23630)
org.apache.spark.deploy.yarn.YarnClusterSuite.run Spark in yarn-cluster mode with additional jar
org.apache.spark.deploy.yarn.YarnClusterSuite.run Python application in yarn-cluster mode
org.apache.spark.deploy.yarn.YarnClusterSuite.run Python application in yarn-cluster mode using spark.yarn.appMasterEnv to override local envvar
org.apache.spark.deploy.yarn.YarnClusterSuite.user class path first in cluster mode
org.apache.spark.deploy.yarn.YarnClusterSuite.executor env overwrite AM env in cluster mode
org.apache.spark.deploy.yarn.YarnShuffleAuthSuite.external shuffle service
org.apache.spark.deploy.yarn.YarnShuffleIntegrationSuite.external shuffle service
```

**Comment by dongjoon-hyun** [comment]
Although this is the first one hitting them, this may not be the root cause.

**Comment by wang-zhun** [comment]
Thank you @dongjoon-hyun , it may be caused by me, I will investigate this reason

**Comment by dongjoon-hyun** [comment]
Thank you so much, @wang-zhun .

**Comment by dongjoon-hyun** [comment]
Unfortunately, this test case follow-up broadens the failure surface to the other test suites,  `YarnClusterSuite`, `YarnShuffleAuthSuite`, and `YarnShuffleIntegrationSuite`.

Definitely, this seems that some uncleaned YarnClient issue, but it's not clear to me. I'll revert this first to narrow down the failure this specific test case only.

After that, if the original test case, `specify a more specific type for ...` , is not fixed in a short term, we may consider another approaches (ignoring this in Hadoop 3.2 or reverting the original commit).

Sorry guys.

**Comment by dongjoon-hyun** [comment]
For the follow-up PR, please use `[test-maven][test-hadoop3.2]` in the PR title, @wang-zhun .

**Comment by tgravescs** [comment]
that's fine, if its causing problems lets revert it. We can do some other more basic tests just to make sure value passed as expected and perhaps add something in the Cluster Suite

**Comment by dongjoon-hyun** [comment]
Hi, All. I made a follow-up PR. Until now, it looks promising.
- https://github.com/apache/spark/pull/28550

**Comment by dongjoon-hyun** [comment]
Inevitably, the test case will be disabled temporarily on Hadoop 3.2 profile only. We will keep this test coverage in Hadoop 2.7.
- https://github.com/apache/spark/pull/28552

**Comment by wang-zhun** [comment]
Thank you @dongjoon-hyun

**Pull request closed without merging**
