### PR TITLE
[SPARK-24052][CORE][UI] Add spark version information on environment page

### PR DESCRIPTION
**Pull request by caneGuy**
## What changes were proposed in this pull request?

Since we may have multiple version in production cluster,we can showing some information on environment page like below:
environment-page

## How was this patch tested?
Exist UT

### CODE REVIEW

**Comment by srowen** [comment]
We already have SparkBuildInfo for this purpose.

**Comment by vanzin** [comment]
The Spark version already shows next to the Spark logo on every page in the UI?

**Comment by caneGuy** [comment]
It is version for the historyserver @vanzin 
May be i can reuse SparkBuildInfo? @srowen @vanzin 
Thanks!

**Comment by vanzin** [comment]
The SHS shows the application's Spark version in the title (or the SHS version in the listing page).

**Comment by caneGuy** [comment]
Ok i will close this pr.
Thanks for your time @srowen @vanzin

**Pull request closed without merging**
