### PR TITLE
[SPARK-8170][Python]Add signal handler to trap Ctrl-C in pyspark and cancel all running jobs

### PR DESCRIPTION
**Pull request by ashwinshankar77**
This patch adds a signal handler to trap Ctrl-C and cancels running job.

### CODE REVIEW

**Comment by ashwinshankar77** [comment]
@davies 
@JoshRosen

**Comment by davies** [comment]
Jenkins, OK to test

**Comment by davies** [comment]
LGTM

**Comment by ashwinshankar77** [comment]
Test failures are unrelated.

**Comment by ashwinshankar77** [comment]
Test failures are unrelated

**Comment by ashwinshankar77** [comment]
Hi @davies, did you have any comments on the patch ? Also is it possible for a user
to kick off Jenkins build for his/her patch, when such unrelated test failures happen ?

**Comment by davies** [comment]
@ashwinshankar77 I worried that the failed test is actually related to the change in this PR, could you run test locally?

**Comment by ashwinshankar77** [comment]
@davies I did run it locally and the pyspark tests passed. I also ran ./dev/run-tests and tests passed. :
Running PySpark tests. Output is in /Users/ashankar/Documents/workspace/spark-apache/spark/python/unit-tests.log
Will test against the following Python executables: ['python2.6']
Will test the following Python modules: ['pyspark-core', 'pyspark-ml', 'pyspark-mllib', 'pyspark-sql', 'pyspark-streaming']
Finished test(python2.6): pyspark.conf (4s)
Finished test(python2.6): pyspark.broadcast (6s)
Finished test(python2.6): pyspark.accumulators (9s)
Finished test(python2.6): pyspark.rdd (16s)
Finished test(python2.6): pyspark.shuffle (0s)
Finished test(python2.6): pyspark.serializers (12s)
Finished test(python2.6): pyspark.profiler (5s)
Finished test(python2.6): pyspark.context (21s)
Finished test(python2.6): pyspark.ml.clustering (10s)
Finished test(python2.6): pyspark.ml.feature (16s)
Finished test(python2.6): pyspark.ml.classification (16s)
Finished test(python2.6): pyspark.ml.recommendation (17s)
Finished test(python2.6): pyspark.ml.regression (16s)
Finished test(python2.6): pyspark.ml.tuning (16s)
Finished test(python2.6): pyspark.ml.evaluation (11s)
Finished test(python2.6): pyspark.ml.tests (16s)
Finished test(python2.6): pyspark.mllib.classification (18s)
Finished test(python2.6): pyspark.mllib.evaluation (10s)
Finished test(python2.6): pyspark.mllib.feature (16s)
Finished test(python2.6): pyspark.mllib.linalg.__init__ (0s)
Finished test(python2.6): pyspark.mllib.clustering (25s)
Finished test(python2.6): pyspark.mllib.fpm (11s)
Finished test(python2.6): pyspark.mllib.random (8s)
Finished test(python2.6): pyspark.mllib.linalg.distributed (14s)
Finished test(python2.6): pyspark.mllib.recommendation (19s)
Finished test(python2.6): pyspark.mllib.stat.KernelDensity (0s)
Finished test(python2.6): pyspark.mllib.stat._statistics (12s)
Finished test(python2.6): pyspark.mllib.regression (19s)
Finished test(python2.6): pyspark.mllib.util (9s)
Finished test(python2.6): pyspark.mllib.tree (15s)
Finished test(python2.6): pyspark.sql.types (8s)
Finished test(python2.6): pyspark.sql.context (15s)
Finished test(python2.6): pyspark.sql.column (13s)
Finished test(python2.6): pyspark.sql.group (15s)
Finished test(python2.6): pyspark.sql.dataframe (29s)
Finished test(python2.6): pyspark.tests (156s)
Finished test(python2.6): pyspark.sql.window (5s)
Finished test(python2.6): pyspark.sql.functions (19s)
Finished test(python2.6): pyspark.streaming.util (0s)
Finished test(python2.6): pyspark.sql.readwriter (23s)
Finished test(python2.6): pyspark.sql.tests (41s)
Finished test(python2.6): pyspark.mllib.tests (135s)
Finished test(python2.6): pyspark.streaming.tests (371s)
Tests passed in 552 seconds

**Pull request closed without merging**
