### PR TITLE
[SPARK-35495][R] Change SparkR maintainer for CRAN

### PR DESCRIPTION
**Pull request by felixcheung**
### What changes were proposed in this pull request?

As discussed, update SparkR maintainer for future release.

### Why are the changes needed?

Shivaram will not be able to work with this in the future, so we would like to migrate off the maintainer contact email.

@shivaram

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @felixcheung .

**Comment by dongjoon-hyun** [comment]
Merged to master/3.1/3.0.

**Comment by shivaram** [comment]
Thanks @felixcheung +1 from me as well

**Comment by dongjoon-hyun** [comment]
Thank you, @shivaram !

**Pull request closed without merging**
