### PR TITLE
[SPARK-50150][BUILD][3.5] Upgrade Jetty to 9.4.56.v20240826

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to upgrade Jetty to 9.4.56.v20240826.

### Why are the changes needed?

To bring the latest bug fixes.

### Does this PR introduce _any_ user-facing change?

No behavior change.

### How was this patch tested?

Pass the CIs.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Could you review this PR, @attilapiros ?

**Comment by dongjoon-hyun** [comment]
Could you review this PR, @viirya ?

**Review by attilapiros — APPROVED** [review]
lgtm

**Comment by dongjoon-hyun** [comment]
Thank you, @attilapiros !

**Comment by dongjoon-hyun** [comment]
Merged to branch-3.5.

**Review by viirya — COMMENTED** [review]
Looks good to me.

**Comment by dongjoon-hyun** [comment]
Thank you, @viirya , too.

**Pull request closed without merging**
