### PR TITLE
[WIP][SPARK-15208][Core][Streaming][Docs] Update Spark examples with AccumulatorV2

### PR DESCRIPTION
**Pull request by lw-lin**
## What changes were proposed in this pull request?

The patch updates the codes & docs in the example module as well as the related doc module:
- [ ] [docs] `streaming-programming-guide.md`
  - [x] scala code part
  - [ ] java code part
  - [ ] python code part
- [x] [examples] `RecoverableNetworkWordCount.scala`
- [ ] [examples] `JavaRecoverableNetworkWordCount.java`
- [ ] [examples] `recoverable_network_wordcount.py`
## How was this patch tested?

Ran the examples and verified results manually.

### CODE REVIEW

**Comment by lw-lin** [comment]
Once the AccumulatorV2 Java API is finalized, I would update the Java & Python part. Thanks

**Comment by rxin** [comment]
Do you want to bring this up to date?

**Comment by lw-lin** [comment]
@rxin sure, I'll resolve the conflicts very soon; and once the Java APIs are updated in the next couple of days, I'll update the Java examples accordingly.

Thank you for bringing this up!

**Comment by srowen** [comment]
This looks good. Are there other accumulator examples that need an update?

**Comment by lw-lin** [comment]
@srowen, there are no other examples that need an update :-)

**Comment by srowen** [comment]
Merged to master/2.0

**Pull request closed without merging**
