### PR TITLE
[SPARK-38563][PYTHON] Upgrade to Py4J 0.10.9.5

### PR DESCRIPTION
**Pull request by HyukjinKwon**
### What changes were proposed in this pull request?

This PR is a retry of https://github.com/apache/spark/pull/35871 with bumping up the version to 0.10.9.5.
It was reverted because of Python 3.10 is broken, and Python 3.10 was not officially supported in Py4J.

In Py4J 0.10.9.5, the issue was fixed (https://github.com/py4j/py4j/pull/475), and it added Python 3.10 support officially with CI set up (https://github.com/py4j/py4j/pull/477).

### Why are the changes needed?

See https://github.com/apache/spark/pull/35871 

### Does this PR introduce _any_ user-facing change?

See https://github.com/apache/spark/pull/35871 

### How was this patch tested?

Py4J sets up Python 3.10 CI now, and I manually tested PySpark with Python 3.10 with this patch:

```bash
./bin/pyspark
```

```
import py4j
py4j.__version__
spark.range(10).show()
```

```
Using Python version 3.10.0 (default, Mar  3 2022 03:57:21)
Spark context Web UI available at http://172.30.5.50:4040
Spark context available as 'sc' (master = local[*], app id = local-1647571387534).
SparkSession available as 'spark'.
>>> import py4j
>>> py4j.__version__
'0.10.9.5'
>>> spark.range(10).show()
+---+
| id|
+---+
...
```

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @dongjoon-hyun @wangyum FYI

**Review by dongjoon-hyun — COMMENTED** [review]
Actually, we cannot use the same JIRA ID because branch-3.2 has `Py4J 0.10.9.4` already with SPARK-38563. Could you use a new JIRA ID for `Py4J 0.10.9.5`? You can still land it to branch-3.2 too.

**Comment by dongjoon-hyun** [comment]
SPARK-38563 solved the resource leakage and new JIRA adds Python 3.10 support.

**Comment by HyukjinKwon** [comment]
Oh no. That's not released yet. i reverted it from branch-3.2 too.

**Comment by HyukjinKwon** [comment]
BTW, Python 3.10 already works with Spark 3.2 too

**Comment by HyukjinKwon** [comment]
Technically what you said is correct because `branch-3.2` only officially supports Python up to 3.9 but I will port this together to branch-3.2 if you don't mind just to reduce the breakage (although it's not official). The risk here is very small.

**Comment by dongjoon-hyun** [comment]
Oh, got it. If you reverted cleanly from all branches, there is no problem.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by HyukjinKwon** [comment]
Merged to master, branch-3.3 and branch-3.2.

**Pull request closed without merging**
