### PR TITLE
[SPARK-12020] [TESTS] [test-hadoop2.0] PR builder cannot trigger hadoop 2.0 test

### PR DESCRIPTION
**Pull request by yhuai**
https://issues.apache.org/jira/browse/SPARK-12020

### CODE REVIEW

**Comment by rxin** [comment]
LGTM

**Comment by yhuai** [comment]
test this please

**Comment by yhuai** [comment]
https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/46804/consoleFull did test hadoop 2.0 profile. I am merging this to master.

**Comment by yhuai** [comment]
oh, actually I probably to merge this to branch 1.6 (otherwise, pr for 1.6 branch will not be able to test with hadoop 2.0 profile?).

**Pull request closed without merging**
