### PR TITLE
[SPARK-9650][SQL] Fix quoting behavior on interpolated column names

### PR DESCRIPTION
**Pull request by marmbrus**
Make sure that `$"column"` is consistent with other methods with respect to backticks.  Adds a bunch of tests for various ways of constructing columns.

### CODE REVIEW

**Comment by JoshRosen** [comment]
I wonder if I could extend my fuzz tester to cover these cases...

**Comment by marmbrus** [comment]
test this please

**Comment by rxin** [comment]
cc @cloud-fan for review

**Comment by cloud-fan** [comment]
LGTM

**Comment by rxin** [comment]
Merging this in.

**Pull request closed without merging**
