### PR TITLE
[DOC]fix 'spark.memory.offHeap.enabled' default value to false

### PR DESCRIPTION
**Pull request by zzcclp**
modify 'spark.memory.offHeap.enabled' default value to false

### CODE REVIEW

**Comment by zzcclp** [comment]
@JoshRosen

**Comment by sarutak** [comment]
ok to test.

**Comment by sarutak** [comment]
LGTM

**Comment by sarutak** [comment]
@zzcclp Could you file this issue in JIRA and modify the title of this PR like `[SPARK-XXXX][DOC]fix...` ?

**Comment by zzcclp** [comment]
@sarutak , i think this is a little fix, dose it need to file a issue in JIRA?

**Comment by rxin** [comment]
For this one it is probably OK. We can just merge it (into master & branch-1.6).

**Comment by rxin** [comment]
I've merged this.

**Comment by zzcclp** [comment]
@sarutak , @rxin  , thanks

**Pull request closed without merging**
