### PR TITLE
 [SPARK-37524][SQL] We should drop all tables after testing dynamic partition pruning.

### PR DESCRIPTION
**Pull request by weixiuli**
### What changes were proposed in this pull request?

Drop all tables after testing dynamic partition pruning.

### Why are the changes needed?
We should drop all tables after testing dynamic partition pruning.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Exist unittests

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
ok to test

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
@weixiuli can you file a new JIRA instead of reusing the old one? It should have different properties for, for example, fixed versions.

**Comment by weixiuli** [comment]
> @weixiuli can you file a new JIRA instead of reusing the old one? It should have different properties for, for example, fixed versions.

Done, thanks.

**Comment by HyukjinKwon** [comment]
Tests already got passed with the same change before.

Merged to master.

**Comment by dongjoon-hyun** [comment]
+1, LGTM.

**Comment by weixiuli** [comment]
Thank you @HyukjinKwon @dongjoon-hyun

**Pull request closed without merging**
