### PR TITLE
[WIP][DO-NOT-MERGE] Test the -Yrepl-class-based changes

### PR DESCRIPTION
**Pull request by dwijnand**
Hi!  This PR is to test the change to the scala compiler's `-Yrepl-class-based` option (which the Spark REPL uses) that landed in https://github.com/scala/scala/pull/8712.

I don't expect it to be merged. :)

I tested this locally with:

    ./build/mvn -P scala-integration -Dscala.version=2.12.11-bin-4c726db -pl :spark-repl_2.12 -Dtest=none -DwildcardSuites='org.apache.spark.repl.ReplSuite,org.apache.spark.repl.SingletonReplSuite,org.apache.spark.repl.ExecutorClassLoaderSuite' test

and that subset passed for me.  I'm interested to see if those or any other tests fail in CI.

### CODE REVIEW

**Comment by dwijnand** [comment]
Could anyone tell me in which check tests like `ReplSuite` are run, please?

**Comment by srowen** [comment]
Jenkins test this please

**Comment by srowen** [comment]
@dwijnand It should run all tests as the parent POM changed, including ReplSuite.

**Comment by dwijnand** [comment]
Could someone run Jenkins again, please?

**Comment by srowen** [comment]
Jenkins, OK to test

**Comment by dwijnand** [comment]
Is there another incantation to get it to run again?

**Comment by srowen** [comment]
Jenkins test this please

**Comment by dwijnand** [comment]
Jenkins test this please

**Comment by srowen** [comment]
Jenkins test this please

**Comment by srowen** [comment]
Jenkins add to whitelist

**Comment by dwijnand** [comment]
Too late to change any details on this now: https://github.com/scala/scala/releases/tag/v2.12.11

Let us know if you notice any impact from upgrading.

**Pull request closed without merging**
