### PR TITLE
[SPARK-42161][BUILD] Upgrade Apache Arrow to 11.0.0

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This PR aims to upgrade Apache Arrow to 11.0.0.

### Why are the changes needed?
The release note as follows:

- https://arrow.apache.org/release/11.0.0.html

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA.

### CODE REVIEW

**Comment by LuciferYang** [comment]
Still in ASF staging repository, test first

**Comment by HyukjinKwon** [comment]
cc @itholic

**Review by dongjoon-hyun — COMMENTED** [review]
Yay! Thank you, @LuciferYang .

cc @sunchao

**Comment by dongjoon-hyun** [comment]
Is there any update, @LuciferYang ?

**Comment by LuciferYang** [comment]
No, it's still in ASF staging repository, not been published to central repository

**Comment by dongjoon-hyun** [comment]
Thank you for tracking this and sharing it.

**Comment by LuciferYang** [comment]
https://repo1.maven.org/maven2/org/apache/arrow/arrow-memory/11.0.0/

Seems it can be downloaded from the central repository now , re-trigger GA

**Review by sunchao — APPROVED** [review]
LGTM (pending CI)

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by dongjoon-hyun** [comment]
Also, cc @xinrong-meng since she is the release manager for Apache Spark 3.4.0.

We want to have this in branch-3.4 too? WDTY, @xinrong-meng ?

**Comment by dongjoon-hyun** [comment]
BTW, we cannot use PyArrow 11.0.0 yet. Please let us know if this is a blocker for Arrow 11.0.0, @HyukjinKwon and @itholic .
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
mlflow 2.1.1 requires pyarrow<11,>=4.0.0, but you have pyarrow 11.0.0 which is incompatible.
```

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
I think it's fine to have it in 3.4.

**Comment by LuciferYang** [comment]
https://github.com/LuciferYang/spark/actions/runs/4026979492

image

Seems all GA task passed

**Comment by dongjoon-hyun** [comment]
Merged to master/3.4. Thank you all.

**Comment by LuciferYang** [comment]
Thanks @dongjoon-hyun  @HyukjinKwon @sunchao

**Pull request closed without merging**
