### PR TITLE
SPARK-6454 [DOCS] Fix links to pyspark api

### PR DESCRIPTION
**Pull request by kamilsmuga**

### CODE REVIEW

**Comment by srowen** [comment]
LGTM, definitely fixes the links.

**Comment by srowen** [comment]
Actually, there are about 15 other instances of `-class.html` URLs that appear to not work. I'm going to make a JIRA to fix them all: https://issues.apache.org/jira/browse/SPARK-6454

You can change the title here to include `SPARK-6454 [DOCS] ...` to link it. Feel free to have a look at the other occurrences and fix them too, or else I can separately tomorrow.

**Comment by kamilsmuga** [comment]
Is documentation generated somehow or you guys just using static markdown files? 
Found 19 matches across 6 files in docs. Fixing it.

**Comment by kamilsmuga** [comment]
Just took a look DOM elements and looks like permalinks are properly generated. E.g.
```<a class="headerlink" href="#pyspark.mllib.stat.Statistics.colStats" title="Permalink to this definition">¶</a>```

**Comment by srowen** [comment]
API docs are generated but the source that needs fixing here is in the markdown. 

For example in http://spark.apache.org/docs/latest/mllib-data-types.html there is a link to SparseVector under the Python tab and it goes to http://spark.apache.org/docs/latest/api/python/pyspark.mllib.linalg.SparseVector-class.html which doesn't exist.

I think it's all the occurrences of links ending with `-class.html` at the moment.

**Comment by kamilsmuga** [comment]
In the middle of refactoring I realised my fork is 440+ commits behind upstream. I did merge with upstream - that's why 13240cb shows up. 
Anyways, can you please verify the changes?

**Comment by srowen** [comment]
That's fine, the commits will be squashed anyway. You generally just push new commits, and if you need to resolve a merge conflict with `master`, then use `rebase`.

Do you have an account on https://issues.apache.org/jira/browse/SPARK so I can assign the JIRA to you?

LGTM.

**Comment by kamilsmuga** [comment]
Now I have. Username: smugakamil

**Pull request closed without merging**
