### PR TITLE
[SPARK-21749][DOC] Add comments for MessageEncoder to explain the wire format

### PR DESCRIPTION
**Pull request by neoremind**
## What changes were proposed in this pull request?

Spark RPC is built upon TCP tier and leverage netty framework. It would be better to have some comments in RPC module especially to explain the RPC message wire format since it is critical to understand what Message consists (header + payload). So Javadoc comments can be added into MessageEncoder class.

## How was this patch tested?

Only comments added. Existing unit tests are all passed.

### CODE REVIEW

**Comment by neoremind** [comment]
@jerryshao please review my separated PR. Thanks!

**Comment by jiangxb1987** [comment]
Seems you should add the `[DOC]` tag in your title.

**Comment by jerryshao** [comment]
We usually don't have the PRs which only add comments to explain something, so I'm neutral to this change.

**Comment by neoremind** [comment]
I see, anyway this is what I found when I dig into the wire protocol of spark rpc since wire format is a big part of understanding the message structure. If someone thinks this is not necessary I can close the PR.

**Comment by srowen** [comment]
I think the more important question is, is it a protocol that we are guaranteeing? not sure that is. If not then I don't think it should be in user-facing docs.

**Comment by neoremind** [comment]
@srowen I see your concern, it is more internal oriented and maybe updated by developer as lib evolves, I will close the PR then. Thanks for reviewing!

**Pull request closed without merging**
