### PR TITLE
[SPARK-15541] Casting ConcurrentHashMap to ConcurrentMap (branch-1.6)

### PR DESCRIPTION
**Pull request by maver1ck**
## What changes were proposed in this pull request?

Casting ConcurrentHashMap to ConcurrentMap allows to run code compiled with Java 8 on Java 7
## How was this patch tested?

Compilation. Existing automatic tests

### CODE REVIEW

**Comment by maver1ck** [comment]
@jkbradley 
Could you look at it ?
I think this is problem from: https://issues.apache.org/jira/browse/SPARK-10086
Maybe we should merge this PR to branch-1.6 before testing ?
https://github.com/apache/spark/pull/10909/files

**Comment by srowen** [comment]
LGTM

**Comment by srowen** [comment]
... but this needs to be opened vs master first. Don't worry about the flaky test here.

**Comment by srowen** [comment]
Ping @maver1ck

**Comment by maver1ck** [comment]
I added another PR vs master. Using following command to find suspicious code.
```
for i in `grep -c -R ConcurrentHashMap | grep -v ':0' | sed -e s/:.*//`; do echo $i; grep keySet $i ; done
```

https://github.com/apache/spark/pull/14459

**Comment by srowen** [comment]
Can you close this PR please?

**Comment by maver1ck** [comment]
Could you tell me why ?
We need different PR against different branches.

**Comment by srowen** [comment]
We merge to master first and then cherry pick into other branches. Unless the patch is quite different in other branches, we can just merge it into others automatically.

**Comment by maver1ck** [comment]
I know that. 
And this patch is quite different. On master there are changes only in Dispatcher.scala.
On branch-1.6 we need changes also in Catalog.scala.

**Comment by maver1ck** [comment]
As you merged https://github.com/apache/spark/pull/14459 I removed changes in Dispatcher.scala.

**Comment by srowen** [comment]
Ah, I get it now. I will merge this too then. Thank you.

**Comment by srowen** [comment]
Merged. @maver1ck you'll have to manually close it since the ASF bot won't close PRs not open vs master.

**Comment by maver1ck** [comment]
Done.
Thank you.

**Comment by maver1ck** [comment]
@srowen 
I missed one change in Catalog.scala

**Comment by zzcclp** [comment]
@maver1ck  I think you need to open another pr for change in Catalog.scala.

**Comment by srowen** [comment]
@maver1ck this is already merged, leave it closed

**Pull request closed without merging**
