### PR TITLE
[Spark-27406][SQL]UnsafeArrayData serialization breaks when two machi…

### PR DESCRIPTION
**Pull request by pengbo**
This PR is the branch-2.4 version for https://github.com/apache/spark/pull/24317

### CODE REVIEW

**Comment by pengbo** [comment]
cc @cloud-fan , as discussed in https://github.com/apache/spark/pull/24317

**Comment by cloud-fan** [comment]
ok to test

**Comment by cloud-fan** [comment]
thanks, merging to 2.4!

**Comment by srowen** [comment]
Closing because it's merged

**Pull request closed without merging**
