### PR TITLE
[SPARK-29152][2.4][CORE] Executor Plugin shutdown when dynamic allocation is enabled

### PR DESCRIPTION
**Pull request by iRakson**
### What changes were proposed in this pull request?
Added `shutdownHook` for shutdown method of executor plugin. This will ensure that shutdown method will be called always.

### Why are the changes needed?
Whenever executors are not going down gracefully, i.e getting killed due to idle time or getting killed forcefully, shutdown method of executors plugin is not getting called. Shutdown method can be used to release any resources that plugin has acquired during its initialisation. So its important to make sure that every time a executor goes down shutdown method of plugin gets called.

### Does this PR introduce any user-facing change?
No

### How was this patch tested?
Tested Manually

### CODE REVIEW

**Comment by iRakson** [comment]
cc @vanzin

**Comment by vanzin** [comment]
ok to test

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Merged to branch-2.4.
Thank you, @iRakson and @vanzin .

**Comment by dongjoon-hyun** [comment]
Hi, All. I'm testing this PR on Jenkins Maven job because this seems to have a side effect.

**Comment by dongjoon-hyun** [comment]
I reproduced the same failure by triggerring Maven PR builder on `branch-2.4` with dummy commit.
- https://github.com/apache/spark/pull/26900

Also, I'm testing the result about reverting this, @iRakson .

**Comment by dongjoon-hyun** [comment]
In #26900 , I verified that the Maven Jenkins is recovered after reverting this. 
It seems that there is a mismatch between test suites and this PR. I'll revert this.

**Comment by dongjoon-hyun** [comment]
@iRakson Could you make a PR this PR once more with `[test-maven]` string in the PR title?

**Pull request closed without merging**
