### PR TITLE
[SPARK-49791][SQL][FOLLOWUP][3.5] Fix `import` statement

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR is a follow-up for `branch-3.5` due to the difference of `import` statement.
- #48257 

### Why are the changes needed?

To fix the compilation.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the CIs.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Could you review this, @huaxingao ? After backporting, I found that the difference of `import` in branch-3.5.

**Review by huaxingao — APPROVED** [review]
LGTM

**Comment by dongjoon-hyun** [comment]
Thank you so much always, @huaxingao !

**Comment by dongjoon-hyun** [comment]
Merged to branch-3.5.

**Pull request closed without merging**
