### PR TITLE
[MINOR][BUILD] When building spark project, remove spark-tags-tests.jar from…

### PR DESCRIPTION
**Pull request by xiuzhu9527**
### What changes were proposed in this pull request?

When building spark project, remove spark-tags-tests.jar from the $spark_home/jars

### Why are the changes needed?

When building spark project, remove spark-tags-tests.jar from the $spark_home/jars

### Does this PR introduce _any_ user-facing change?

No

### CODE REVIEW

**Comment by xiuzhu9527** [comment]
> Can one of the admins verify this patch?

yes

**Comment by xiuzhu9527** [comment]
@dongjoon-hyun Could you take a look? thanks!

**Comment by xiuzhu9527** [comment]
cc @dongjoon-hyun @HyukjinKwon  @srowen

**Comment by srowen** [comment]
This does not explain why?

**Comment by xiuzhu9527** [comment]
> @dongjoon-hyun Could you take a look? thanks!

**Comment by xiuzhu9527** [comment]
> @dongjoon-hyun Could you take a look? thanks!

**Comment by xiuzhu9527** [comment]
> This does not explain why?
Thank you very much for your reply！After spark build is completed, the $spark_project_home/assembly/target/scala-2.11/jars directory contains spark-tags-tests.jar, I don't think spark-tags-tests.jar should appear in the jars directory

**Comment by xiuzhu9527** [comment]
> This does not explain why?



> > This does not explain why?
> > Thank you very much for your reply！After spark build is completed, the $spark_project_home/assembly/target/scala-2.11/jars directory contains spark-tags-tests.jar, I don't think spark-tags-tests.jar should appear in the jars directory

cc @srowen

**Comment by srowen** [comment]
Why not?

**Comment by xiuzhu9527** [comment]
> Why not?

spark-tags-tests.jar is used in maven test phase.

**Comment by srowen** [comment]
I see comments in the POM files like:
```
    <!--
      This spark-tags test-dep is needed even though it isn't used in this module, otherwise testing-cmds that exclude
      them will yield errors.
    -->
```
It might be safe to remove, but does it harm anything? probably not worth special casing, and I'm not sure there's not an impact

**Comment by xiuzhu9527** [comment]
> not



> I see comments in the POM files like:
> 
> ```
>     
> ```
> 
> It might be safe to remove, but does it harm anything? probably not worth special casing, and I'm not sure there's not an impact

It hasn't done any harm yet, but I think it's not standardized, spark-tags-tests.jar should only appear in maven test phase, but it appears in spark release package

**Comment by xiuzhu9527** [comment]
@kiszk  Hello, can I ask you a question? Why didn't you set the scope to test when you introduced the spark-tags dependency in the kubernetes module？

**Review by srowen — APPROVED** [review]

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
