### PR TITLE
[CORE] [SPARK-9760] Use Option instead of Some for Ivy repos

### PR DESCRIPTION
**Pull request by shivaram**
This was introduced in #7599 

cc @rxin @brkyvz

### CODE REVIEW

**Comment by shivaram** [comment]
Also I am not sure how to add a test case for this as our existing unit tests use a custom Ivy repository which is always specified in `--repositories`. The bug only happens when `--repositories` is not specified

**Comment by rxin** [comment]
LGTM - @brkyvz this is why our coding style wants Option instead of Some!

**Comment by brkyvz** [comment]
Sorry for introducing this. A way to test this is to not provide a repository, and use a fake coordinate so that it fails with a RuntimeException, and not a NullPointerException.

**Comment by shivaram** [comment]
Added a test case but I'm not sure how useful it is as a lot of things can throw a RuntimeException ? @rxin let me know if its worth having it vs. a few seconds added to the test suites.

**Comment by brkyvz** [comment]
I see why SparkSubmitUtilsSuite didn't catch this. I think I use either Some(repo) or none. Never Some(null). I thought we could add it to SparkSubmitUtilsSuite and use the intercept, not in an end to end SparkSubmitSuite test... May be you can add a comment on the line and say that they should remain as Options? I don't think the test is very useful in the current setup

**Comment by brkyvz** [comment]
retest this please

**Comment by shivaram** [comment]
Jenkins, retest this please

**Comment by shivaram** [comment]
@brkyvz Removed the test case now. I'm not sure adding a comment is really relevant as the argument to the method is an `Option`. And you are right that we can't quite test this in SparkSubmitUtilsSuite as passing `None` wouldn't trigger the bug.

**Comment by rxin** [comment]
Merging this - thanks.

**Comment by brkyvz** [comment]
Hallelujah! Finally

**Pull request closed without merging**
