### PR TITLE
[SPARK-43584][BUILD] Update `sbt-assembly`, `sbt-revolver`, `sbt-mima-plugin` plugins

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to update some sbt plugins to newest version. include:
- sbt-assembly from 2.1.0 to 2.1.1
- sbt-mima-plugin from 1.1.0 to 1.1.2
- sbt-revolver from 0.9.1 to 0.10.0

### Why are the changes needed?
Routine upgrade.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA.

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. (Pending CIs)

**Comment by LuciferYang** [comment]
cc@zhenlineo I remember you mentioned a bug in mima 1.1.1: `where the MiMa will not be able to check the class methods if the object is marked private`, so Spark have been using 1.1.0 before, do you have time to help confirm if 1.1.2 has fixed this issue?

**Comment by dongjoon-hyun** [comment]
Oh, +1 for @LuciferYang 's comment.

**Comment by zhenlineo** [comment]
I checked locally. MiMa 1.1.2 can find errors about missing private classes e.g. `private[sql] object Dataset`
```
object org.apache.spark.sql.Dataset does not have a correspondent in client version
```
So it is good to upgrade to 1.1.2!

**Comment by dongjoon-hyun** [comment]
Thank you, @panbingkun , @LuciferYang , @zhenlineo !
Merged to master.

**Comment by LuciferYang** [comment]
late LGTM

**Pull request closed without merging**
