### PR TITLE
[SPARK-40166][SPARK-40167][PYTHON][R][SQL] Expose array_sort(column, comparator) in Python and R

### PR DESCRIPTION
**Pull request by zero323**
### What changes were proposed in this pull request?

This PR exposes array_sort(column, comparator) in Python and R.

### Why are the changes needed?

Feature parity.

### Does this PR introduce _any_ user-facing change?

New signature in Python and R APIs.

### How was this patch tested?

- New doctest, manual testing (Python)
- New unit test (R)

### CODE REVIEW

**Comment by zero323** [comment]
cc @HyukjinKwon FYI

**Review by HyukjinKwon — APPROVED** [review]
LGTM if tests pass (seems line the line length check fails)

**Review by zhengruifeng — APPROVED** [review]
LGTM

**Comment by zero323** [comment]
Merged to master.

Thanks @HyukjinKwon and @zhengruifeng!

**Pull request closed without merging**
