### PR TITLE
[SPARK-33938][SQL][3.1] Optimize Like Any/All by LikeSimplification

### PR DESCRIPTION
**Pull request by beliefer**
### What changes were proposed in this pull request?
We should optimize Like Any/All by LikeSimplification to improve performance.

### Why are the changes needed?
Optimize Like Any/All

### Does this PR introduce _any_ user-facing change?
'No'.

### How was this patch tested?
Jenkins test.

### CODE REVIEW

**Comment by beliefer** [comment]
@cloud-fan

**Review by cloud-fan — APPROVED** [review]

**Comment by cloud-fan** [comment]
retest this please

**Comment by cloud-fan** [comment]
thanks, merging to 3.1!

**Comment by beliefer** [comment]
@cloud-fan Thanks for your work

**Comment by dongjoon-hyun** [comment]
Although this is an improvement, I'm okay with this backport.

cc @HyukjinKwon .

**Comment by HyukjinKwon** [comment]
I am okay too. If it's pretty major and safe, I am okay with porting back.

**Comment by cloud-fan** [comment]
It's a 3.1 perf regression: https://github.com/apache/spark/pull/30975#issuecomment-755158004

**Pull request closed without merging**
