### PR TITLE
[SPARK-48958][BUILD] Upgrade `zstd-jni` to 1.5.6-4

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to upgrade `zstd-jni` from `1.5.6-3` to `1.5.6-4`.

### Why are the changes needed?
1.v1.5.6-3 VS v1.5.6-4
https://github.com/luben/zstd-jni/compare/v1.5.6-3...v1.5.6-4

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by panbingkun** [comment]
cc @dongjoon-hyun @LuciferYang

**Comment by LuciferYang** [comment]
update benchmark result of ZStandardBenchmark?

**Comment by panbingkun** [comment]
> ZStandardBenchmark

org.apache.spark.io.ZStandardBenchmark
JDK 17:
JDK 21:

**Comment by panbingkun** [comment]
> ZStandardBenchmark

Done.

**Review by LuciferYang — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @panbingkun and @LuciferYang .
Merged to master.

**Pull request closed without merging**
