### PR TITLE
[SQL] Optimize arithmetic and predicate operators

### PR DESCRIPTION
**Pull request by kai-zeng**
Existing implementation of arithmetic operators and BinaryComparison operators have redundant type checking codes, e.g.:
Expression.n2 is used by Add/Subtract/Multiply.
(1) n2 always checks left.dataType == right.dataType. However, this checking should be done once when we resolve expression types;
(2) n2 requires dataType is a NumericType. This can be done once.

This PR optimizes arithmetic and predicate operators by removing such redundant type-checking codes.

Some preliminary benchmarking on 10G TPC-H data over 5 r3.2xlarge EC2 machines shows that this PR can reduce the query time by 5.5% to 11%.
The benchmark queries follow the template below, where OP is plus/minus/times/divide/remainder/bitwise and/bitwise or/bitwise xor.

SELECT l_returnflag,  l_linestatus, SUM(l_quantity OP cnt1), SUM(l_quantity OP cnt2), ...., SUM(l_quantity OP cnt700)
FROM (
    SELECT l_returnflag, l_linestatus, l_quantity, 1 AS cnt1, 2 AS cnt2, ..., 700 AS cnt700
    FROM lineitem
    WHERE l_shipdate <= '1998-09-01'
)
GROUP BY l_returnflag,  l_linestatus;

### CODE REVIEW

**Comment by kai-zeng** [comment]
Jenkins, retest this please.

**Comment by marmbrus** [comment]
Thanks for doing this.  Can you undo the permission changes on the files `100644 → 100755`.  I think you made them executable.

**Comment by chenghao-intel** [comment]
@kai-zeng The code LGTM, and I've tested the `Add` in an aggregation benchmark, it shows about 20% performance improved. So can you rebase the code?

**Comment by kai-zeng** [comment]
@chenghao-intel Done rebasing

**Comment by chenghao-intel** [comment]
@kai-zeng can you also revert the file permission bit for `aggregates.scala`?

**Comment by kai-zeng** [comment]
@chenghao-intel you mean revert aggregates.scala to executable?

**Comment by cloud-fan** [comment]
`aggregates.scala` is the only file in folder `expressions` which is executable, I think it was a mistake and we should make it un-executable.

**Comment by kai-zeng** [comment]
@cloud-fan Yeah, aggregates.scala is executable in spark master. And I have made it un-executable in this PR. BTW, these files are also executable in spark master (I chmod them too):

./catalyst/src/main/scala/org/apache/spark/sql/catalyst/dsl/package.scala
./catalyst/src/main/scala/org/apache/spark/sql/catalyst/SqlParser.scala
./catalyst/src/main/scala/org/apache/spark/sql/types/Metadata.scala
./catalyst/src/test/scala/org/apache/spark/sql/catalyst/util/MetadataSuite.scala
./core/src/main/scala/org/apache/spark/sql/execution/Aggregate.scala
./hive-thriftserver/src/main/scala/org/apache/spark/sql/hive/thriftserver/SparkSQLCLIDriver.scala

**Comment by marmbrus** [comment]
Thanks!  merged to master and branch 1.3

**Pull request closed without merging**
