### PR TITLE
[SPARK-38814][BUILD][TESTS] Migrate Junit 4 to Junit 5

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr aims to migrate Junit 4 to Junit 5 jupiter api, the main changes are as follows:

1. Change JUnit 4 related test dependencies to JUnit 5 to ensure Maven and SBT can run JUnit test normally: `junit` -> `junit-jupiter`, `com.github.sbt:junit-interface` -> `net.aichler:jupiter-interface`, `jmock-junit4` -> `jmock-junit5` and add `sbt-jupiter-interface` plugin to plugins.sbt
2. API migration：
2.1 Annotations reside in the `org.junit.jupiter.api` package
2.2 `@Before` and `@After` no longer exist, use `@BeforeEach` and `@AfterEach` instead
2.3 `@BeforeClass` and `@AfterClass` no longer exist, use `@BeforeAll` and `@AfterAll` instead
2.4 `@Ignore` no longer exists, use `@Disabled` instead
2.5 `Assertions` reside in `org.junit.jupiter.api.Assertions` and the assertion api with error message has a little changes there are a few api changes, for example: `assertEquals("my message", 1, 2)` -> `assertEquals(1, 2, "my message")`
2.6 Assumptions reside in `org.junit.jupiter.api.Assumptions`

### Why are the changes needed?
JUnit5 is a powerful and flexible update to the JUnit framework, and it provides a variety of improvements and new features to organize and
describe test cases, as well as help in understanding test results：
1. JUnit 5 leverages features from Java 8 or later, such as lambda functions, making tests more powerful and easier to maintain, but Junit 4 still a Java 7 compatible version
2. JUnit 5 has added some useful new features for describing, organizing, and executing tests. For examples: [Parameterized Tests](https://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests) and [Conditional Test Execution](https://junit.org/junit5/docs/current/user-guide/#extensions-conditions) may make our test code look simpler, [Parallel Execution](https://junit.org/junit5/docs/current/user-guide/#writing-tests-parallel-execution) may make our test faster

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA

### CODE REVIEW

**Comment by LuciferYang** [comment]
@srowen @dongjoon-hyun @HyukjinKwon I'm sorry to take up your time. I tried to migrate Junit 4 to Junit 5, passed all UTs and give this draft pr. 

I haven't create a new jira yet because I'm not sure if we we're interested in it.

I think JUnit 5 provides some new features that will help us simplify the test code in the future, so I give this draft pr.

For examples, when we use the [Parameterized Tests](https://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests), the following test code

https://github.com/apache/spark/blob/fb3f380b3834ca24947a82cb8d87efeae6487664/common/kvstore/src/test/java/org/apache/spark/util/kvstore/RocksDBTypeInfoSuite.java#L46-L74

can be simplified to

```scala
  @ParameterizedTest
  @ValueSource(classes = {NoNaturalIndex.class, NoNaturalIndex2.class, DuplicateIndex.class,
     EmptyIndexName.class, IllegalIndexName.class, IllegalIndexMethod.class})
  public void testIllegalType(Class<?> type) {
    assertThrows(IllegalArgumentException.class, () -> newTypeInfo(type));
  }
```

For another example, JUnit 5 provides `EnabledOnOs`, `DisabledIfSystemProperty` and other annotations, which makes it easier for us to enable or disable some UTs.

I'd like to know your suggestions to decide whether to continue to finish this work

**Comment by LuciferYang** [comment]
At the same time, we have a way to split this into multiple small pr for migration. Junit5  provides `vintage` engine to run the UTs written in Junit 4

**Comment by srowen** [comment]
The change looks OK. It's a big change. I think it's definitely OK for Spark 4, and, maybe fine for Spark 3.4 too

**Comment by LuciferYang** [comment]
@srowen OK ~ I have created a new jira and will maintain this patch for a long time. 

There are some work can be completed first without Junit version change, such as 

2.5 `@Test` no longer has `expected`parameters, use `Assertions.assertThrows` instead

**Comment by HyukjinKwon** [comment]
Yeah, I have the same thought w/ Sean's

**Comment by LuciferYang** [comment]
> Yeah, I have the same thought w/ Sean's

Got it ~

**Comment by LuciferYang** [comment]
Is this possible for Spark 3.4? Or only for Spark 4? @HyukjinKwon @srowen

**Comment by srowen** [comment]
It's a ton of change and I don't know if Junit 5 offers that much benefit? I wouldn't put it in 3.4 just because of the size of the change relative to benefit

**Comment by LuciferYang** [comment]
> It's a ton of change and I don't know if Junit 5 offers that much benefit?

We can minimize changes if use `Vintage` instead of `Jupiter`, but the `Vintage` way has been rejected by you before. Let's wait until spark 4 to discuss this change.

**Comment by LuciferYang** [comment]
Close  this pr and wait until Spark 4.0 to discuss the necessity of migrate Junit 4 to Junit 5, thanks @srowen @HyukjinKwon

**Pull request closed without merging**
