### PR TITLE
[SPARK-33640][TESTS] Extend connection timeout to DB server for DB2IntegrationSuite and its variants

### PR DESCRIPTION
**Pull request by sarutak**
### What changes were proposed in this pull request?

This PR extends the connection timeout to the DB server for DB2IntegrationSuite and its variants.

The container image ibmcom/db2 creates a database when it starts up.
The database creation can take over 2 minutes.

DB2IntegrationSuite and its variants use the container image but the connection timeout is set to 2 minutes so these suites almost always fail.
### Why are the changes needed?

To pass those suites.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

I confirmed the suites pass with the following commands.
```
$ build/sbt -Pdocker-integration-tests -Phive -Phive-thriftserver package "testOnly org.apache.spark.sql.jdbc.DB2IntegrationSuite"
$ build/sbt -Pdocker-integration-tests -Phive -Phive-thriftserver package "testOnly org.apache.spark.sql.jdbc.v2.DB2IntegrationSuite"
$ build/sbt -Pdocker-integration-tests -Phive -Phive-thriftserver package "testOnly org.apache.spark.sql.jdbc.DB2KrbIntegrationSuite"

### CODE REVIEW

**Comment by sarutak** [comment]
retest this please.

**Comment by sarutak** [comment]
retest this please.

**Comment by sarutak** [comment]
retest this please.

**Comment by sarutak** [comment]
cc: @gaborgsomogyi

**Comment by sarutak** [comment]
cc: @dongjoon-hyun and @HyukjinKwon too.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM for Apache Spark 3.1.0. Thank you, @sarutak . 
Merged to master.

**Comment by gaborgsomogyi** [comment]
Late LGTM. Thanks for notifying.

**Pull request closed without merging**
