### PR TITLE
[SPARK-39945][BUILD] Upgrade `sbt-mima-plugin` to 1.1.0

### PR DESCRIPTION
**Pull request by williamhyun**
### What changes were proposed in this pull request?
This PR aims to upgrade `sbt-mima-plugin` to 1.1.0.

### Why are the changes needed?
This will bring the latest improvements and bug fixes. 

- https://github.com/lightbend/mima/releases/tag/1.1.0
- https://github.com/lightbend/mima/releases/tag/1.0.1
- https://github.com/lightbend/mima/releases/tag/1.0.0

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass the CIs.

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]
LGTM if tests pass

**Review by LuciferYang — APPROVED** [review]
LGTM +1

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by dongjoon-hyun** [comment]
The SparkR failure is irrelevant to this PR. Merged to master.
Thank you, @williamhyun , @HyukjinKwon , @LuciferYang .

**Pull request closed without merging**
