### PR TITLE
[SPARK-6954] [YARN] ExecutorAllocationManager can end up requesting a ne...

### PR DESCRIPTION
**Pull request by sryza**
gative number of executors

### CODE REVIEW

**Comment by sryza** [comment]
@andrewor14

**Comment by andrewor14** [comment]
retest this please

**Comment by andrewor14** [comment]
I'm merging this into 1.3

**Comment by andrewor14** [comment]
Hm, merge script is acting up a little... for some reason I can't merge this.

**Comment by srowen** [comment]
Yeah, I get...

```
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['git', 'commit', '--author="Sandy Ryza <sandy@cloudera.com>"', '-m', u'[SPARK-6954] [YARN] ExecutorAllocationManager can end up requesting a ne...', '-m', u'...gative n...\r\n\r\n...umber of executors\r\n\r\nAuthor: Sandy Ryza <sandycloudera.com>\r\n\r\nCloses #5704 from sryza/sandy-spark-6954 and squashes the following commits:\r\n\r\nb7890fb [Sandy Ryza] Avoid ramping up to an existing number of executors\r\n6eb516a [Sandy Ryza] SPARK-6954. ExecutorAllocationManager can end up requesting a negative number of executors', '-m', 'Author: Sandy Ryza <sandy@cloudera.com>', '-m', u'Closes #5856 from sryza/sandy-backport-6954 and squashes the following commits:', '-m', '1cb517a [Sandy Ryza] [SPARK-6954] [YARN] ExecutorAllocationManager can end up requesting a negative n...']' returned non-zero exit status 1
```

Not sure why `git` fails. Maybe I can try executing this command by hand, carefully.

**Comment by srowen** [comment]
My guess is it's something to do with the text of the commit message, since it comes from a copy and paste of a commit message. Maybe something doesn't quite get escaped or confuses git.

I tried this just after failure but didn't work for other reasons (untracked files in the working dir; guess I'd have to do something else at this point in the script to make it work but I'm not sure what):

```
git commit --author="Sandy Ryza <sandy@cloudera.com>" -m "[SPARK-6954] [YARN] ExecutorAllocationManager can end up requesting a negative number of executors." -m "Author: Sandy Ryza <sandy@cloudera.com>" -m "Closes #5856 from sryza/sandy-backport-6954 and squashes the following commits:" -m "1cb517a [Sandy Ryza] [SPARK-6954] [YARN] ExecutorAllocationManager can end up requesting a negative n..."
```

@sryza to test my theory are you able to simplify the description to not include the old commit message stuff? maybe that just makes it work.

**Comment by andrewor14** [comment]
Interesting. That might actually be the case. @sryza could you update the description?

**Comment by sryza** [comment]
@andrewor14 @srowen updated it.

**Comment by andrewor14** [comment]
Weird, it still doesn't work. @sryza @srowen do you want to give it a try?

**Comment by srowen** [comment]
OK, I'm confused and/or dumb, but this failed because it was already merged, by me:
https://github.com/apache/spark/commit/98ac39d2f5828fbdad8c9a4e563ad1169e3b9948
(i.e. git says "nothing is different" and exits with status 1)
I don't recall how/why I merged that when Andrew merged the other bit, when it might have looked like it wasn't auto-mergeable for 1.3. Anyway, this can be closed.

**Comment by andrewor14** [comment]
Haha wow, good to know. Let's close this then.

**Comment by andrewor14** [comment]
Hey @sryza can you close this PR? It's already merged.

**Comment by sryza** [comment]
Oops sorry for the delay

**Pull request closed without merging**
