### PR TITLE
[SPARK-48204][INFRA] Fix release script for Spark 4.0+

### PR DESCRIPTION
**Pull request by cloud-fan**
### What changes were proposed in this pull request?

Before Spark 4.0, Scala 2.12 was primary and Scala 2.13 was secondary. The release scripts build more packages (hadoop3, without-hadoop, pyspark, sparkr) for the primary Scala version but only one package for the secondary. However, Spark 4.0 removes Scala 2.12 support and the release script needs to be updated accordingly.

### Why are the changes needed?

to make the release scripts work

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

manual.

### Was this patch authored or co-authored using generative AI tooling?

no

### CODE REVIEW

**Comment by cloud-fan** [comment]
Note: it does not fix all the issues. The next issue I'm debugging is the pyspark version number mismatch. The script produces pyspark packages with version `4.0.0.dev0` but at the end it tries to find `4.0.0.dev`.

cc @HyukjinKwon @dongjoon-hyun

**Comment by dongjoon-hyun** [comment]
Ack!

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Merged to master.

**Pull request closed without merging**
