### PR TITLE
[SPARK-19379][CORE] SparkAppHandle.getState not registering FAILED state upon Spark app failure in Local mode

### PR DESCRIPTION
**Pull request by thomastechs**
## What changes were proposed in this pull request?
As per the bug, the state corresponding to app failures are not getting registered with call back to the launcher.So, the already available isFailed() check of TaskState.scala, is utilized to send the explicit status of SparkAppHandle.State.FAILED back to the launcherBackend, which under the hood updates the status for (LOST == state) || (FAILED == state).
The already available TaskState.isFinished() is used to set the value SparkAppHandle.State.FINISHED, as under the hood, it considers FINISHED, FAILED, KILLED, LOST as part of FINISHED state.
Since the isFailed() is checked first, the isFinished is checked in the else if condition to get the mutually exclusive scenarios.

## How was this patch tested?
This patch was tested manually. The tests included, by simply submitting local jobs, the states are set correctly. Also, the tests included with some fail prone codes executed and tested the status set as FAILED. It looks difficult to write testcase to create an error prone scnario code and check the status.

### CODE REVIEW

**Comment by srowen** [comment]
CC @zsxwing as this was last touched in https://issues.apache.org/jira/browse/SPARK-6602

**Comment by adamstatdna** [comment]
@thomastechs It looks like it would be more appropriate to call private method, stop(SparkAppHandle.State) so that ensures closure (in addition to the callback) of the backend rather than just the callback.

**Comment by zsxwing** [comment]
I don't get the point. You are using a task state to update an application state.

**Comment by adamstatdna** [comment]
@zsxwing What's the best way to callback and update the SparkAppHandle state upon FAILURE or FINISHED state of the spark application? It currently lacks handling FAILURE.

**Comment by zsxwing** [comment]
> What's the best way to callback and update the SparkAppHandle state upon FAILED or FINISHED state of the spark application?

Maybe I'm missing something. Why need to set it in the local mode? There is no public way to query the state.

**Comment by adamstatdna** [comment]
My use case is end-to-end automated testing in local mode using programmatic Launcher. I have tests where the Spark app is expected to be FINISHED and those where it is expected to be FAILED.

**Comment by thomastechs** [comment]
One point, as discussed, statusChange gets called for task status change. So, if we can identify the point where the job or that executor(Only one executor for local mode, right) is failed, we can give  a call back at that point. If you could give some insights about it, that fix can be applied.

**Comment by vanzin** [comment]
There's no way to set the app state currently because in client mode (which includes local) Spark lacks an API to do that. So the code guesses that since "stop" was called, the app finished successfully. In cluster mode, Spark has more info and can propagate the proper status.

It might be possible to detect failure in client mode by checking the exit code of the underlying spark-submit process. But the current code here is wrong. A task failing does not mean the application failed.

**Comment by HyukjinKwon** [comment]
Hi @thomastechs, is it still active and any opinion on ^ ? Otherwise, I would like to propose to close this.

**Comment by adamstatdna** [comment]
Yes, I believe it is still active. The solution stated by Marcelo of
detecting the exit code in local mode would be a solution for my purposes
of testing where you want to do end-to-end integration testing in local
mode and test for failure/success states of the spark app in question.

**Comment by vanzin** [comment]
This PR has been silent for months, so unless the owner of the PR replies it should be closed. If you want to pick up the work, you'll have to open a new PR anyway.

**Pull request closed without merging**
