### PR TITLE
[SPARK-7224][SPARK-7306] mock repository generator for --packages tests without nio.Path

### PR DESCRIPTION
**Pull request by brkyvz**
The previous PR for SPARK-7224 (#5790) broke JDK 6, because it used java.nio.Path, which was in jdk 7, and not in 6. This PR uses Guava's `Files` to handle directory creation, and etc... 

The description from the previous PR:

> This patch contains an `IvyTestUtils` file, which dynamically generates jars and pom files to test the `--packages` feature without having to rely on the internet, and Maven Central.

cc @pwendell 

I also rand the flaky test about 20 times locally, it didn't fail a single time, but I think it may fail like once every 100 builds? I still haven't figured the cause yet, but the test before it, `--jars` was also failing after we turned off the `--packages` test in `SparkSubmitSuite`. It may be related to the launch of SparkSubmit.

### CODE REVIEW

**Comment by brkyvz** [comment]
ping @pwendell this should stabilize SparkSubmitUtilsSuite tests

**Comment by JoshRosen** [comment]
Jenkins, retest this please.

**Comment by JoshRosen** [comment]
Hey @brkyvz, what's the status on this?  If the delta from the previous reverted PR to this PR is really small, then it's probably okay to pull this in to re-enable that test.

**Comment by brkyvz** [comment]
@JoshRosen it is very small. The only difference is 
`import com.google.common.io.Files` instead of
`import java.nio.{Files, Path}`

**Comment by JoshRosen** [comment]
Ah, great.  Going to merge this into master and branch-1.4 (1.4.0) so that we regain test coverage for this feature.

**Pull request closed without merging**
