### PR TITLE
[SPARK-45473][SQL][3.5] Fix incorrect error message for RoundBase

### PR DESCRIPTION
**Pull request by viirya**
### What changes were proposed in this pull request?

This minor patch fixes incorrect error message of `RoundBase`.

### Why are the changes needed?

Fix incorrect error message.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Unit test

### Was this patch authored or co-authored using generative AI tooling?

No

### CODE REVIEW

**Comment by viirya** [comment]
cc @dongjoon-hyun

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. (Pending CIs)

It's interesting. I saw some conflicts about quota, but this PR is very clean. Thanks!

**Review by beliefer — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Merged to branch-3.5.

**Comment by viirya** [comment]
Thanks @dongjoon-hyun @beliefer.

**Pull request closed without merging**
