### PR TITLE
[SPARK-10431][ Spark Core ] Fix intermittent test failure. Wait for event queue to be clear

### PR DESCRIPTION
**Pull request by robbinspg**

### CODE REVIEW

**Comment by srowen** [comment]
Although I'm not so familiar with this, seems reasonable to me.

**Comment by robbinspg** [comment]
I see the test failure is https://issues.apache.org/jira/browse/SPARK-9869 which I'm sure is not related to this pull request.

Ironically, looking at SPARK-9869 it looks like it could be a very similar issue to this fix, ie waiting for the listenerBus is empty before the asserts!

**Comment by srowen** [comment]
Agree, let's see what happens on a second run here.

**Comment by andrewor14** [comment]
retest this please

**Comment by andrewor14** [comment]
Yup, LGTM. In the specific test you reported in the JIRA we ran a job before calling `runAndReturnMetrics`, so it makes sense to ensure the queue is empty before running the thing we actually care about.

**Comment by andrewor14** [comment]
Merged into master 1.5

**Pull request closed without merging**
