### PR TITLE
[SPARK-7691] [SQL] Refactor CatalystTypeConverter to use type-specific row accessors

### PR DESCRIPTION
**Pull request by JoshRosen**
This patch significantly refactors CatalystTypeConverters to both clean up the code and enable these conversions to work with future Project Tungsten features.

At a high level, I've reorganized the code so that all functions dealing with the same type are grouped together into type-specific subclasses of `CatalystTypeConveter`.  In addition, I've added new methods that allow the Catalyst Row -> Scala Row conversions to access the Catalyst row's fields through type-specific `getTYPE()` methods rather than the generic `get()` / `Row.apply` methods.  This refactoring is a blocker to being able to unit test new operators that I'm developing as part of Project Tungsten, since those operators may output `UnsafeRow` instances which don't support the generic `get()`.

The stricter type usage of types here has uncovered some bugs in other parts of Spark SQL:
- #6217: DescribeCommand is assigned wrong output attributes in SparkStrategies
- #6218: DataFrame.describe() should cast all aggregates to String
- #6400: Use output schema, not relation schema, for data source input conversion

Spark SQL current has undefined behavior for what happens when you try to create a DataFrame from user-specified rows whose values don't match the declared schema.  According to the `createDataFrame()` Scaladoc:

>  It is important to make sure that the structure of every [[Row]] of the provided RDD matches the provided schema. Otherwise, there will be runtime exception.

Given this, it sounds like it's technically not a break of our API contract to fail-fast when the data types don't match. However, there appear to be many cases where we don't fail even though the types don't match. For example, `JavaHashingTFSuite.hasingTF` passes a column of integers values for a "label" column which is supposed to contain floats.  This column isn't actually read or modified as part of query processing, so its actual concrete type doesn't seem to matter. In other cases, there could be situations where we have generic numeric aggregates that tolerate being called with different numeric types than the schema specified, but this can be okay due to numeric conversions.

In the long run, we will probably want to come up with precise semantics for implicit type conversions / widening when converting Java / Scala rows to Catalyst rows.  Until then, though, I think that failing fast with a ClassCastException is a reasonable behavior; this is the approach taken in this patch.  Note that certain optimizations in the inbound conversion functions for primitive types mean that we'll probably preserve the old undefined behavior in a majority of cases.

### CODE REVIEW

**Comment by JoshRosen** [comment]
I noticed that `CatalystTypeConverters` and many of its methods are public; is this intentional or should they be `private[sql]`?

**Comment by JoshRosen** [comment]
I should probably re-run the original CatalystTypeConverter benchmarks to check that this hasn't regressed performance.

**Comment by rayortigas** [comment]
@JoshRosen, thanks for the heads-up.

This refactoring looks good. Grouping the conversions for each type makes it easier to find them. It also sets expectations for any other conversions that might be added.

I'll comment specifically on #5713 over there.

**Comment by rayortigas** [comment]
As for the public methods that were in `CatalystTypeConverters`, I also think they could be `private[sql]`. You might want to ask @vlyubin, who originally extracted the class (#5279).

**Comment by JoshRosen** [comment]
Based on the last set of test failures, it looks like there's another other corner-case where the actual data types don't match the declared ones.

**JavaHashingTFSuite.hasingTF**:

```
sbt.ForkMain$ForkError: java.lang.Integer cannot be cast to java.lang.Double
	at scala.runtime.BoxesRunTime.unboxToDouble(BoxesRunTime.java:119)
	at org.apache.spark.sql.catalyst.expressions.GenericRow.getDouble(rows.scala:93)
	at org.apache.spark.sql.catalyst.CatalystTypeConverters$DoubleConverter$.toScalaImpl(CatalystTypeConverters.scala:303)
	at org.apache.spark.sql.catalyst.CatalystTypeConverters$DoubleConverter$.toScalaImpl(CatalystTypeConverters.scala:302)
	at org.apache.spark.sql.catalyst.CatalystTypeConverters$CatalystTypeConverter.toScala(CatalystTypeConverters.scala:87)
	at org.apache.spark.sql.catalyst.CatalystTypeConverters$StructConverter.toScala(CatalystTypeConverters.scala:235)
	at org.apache.spark.sql.catalyst.CatalystTypeConverters$StructConverter.toScala(CatalystTypeConverters.scala:202)
	at org.apache.spark.sql.catalyst.CatalystTypeConverters$$anonfun$createToScalaConverter$1.apply(CatalystTypeConverters.scala:360)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeTake$2.apply(SparkPlan.scala:150)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeTake$2.apply(SparkPlan.scala:150)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:108)
	at org.apache.spark.sql.execution.SparkPlan.executeTake(SparkPlan.scala:150)
	at org.apache.spark.sql.execution.Limit.executeCollect(basicOperators.scala:125)
	at org.apache.spark.sql.DataFrame.collect(DataFrame.scala:1157)
	at org.apache.spark.sql.DataFrame.head(DataFrame.scala:1091)
	at org.apache.spark.sql.DataFrame.take(DataFrame.scala:1150)
	at org.apache.spark.ml.feature.JavaHashingTFSuite.hashingTF(JavaHashingTFSuite.java:76)
```

It also looks like there are some cases in HadoopFSRelationTest where we expect to receive a string but receive an Integer instead.  I'll take a closer look at these cases to see whether this indicates a bug or whether we should just call toString() on any non-string type that we receive.

**Comment by JoshRosen** [comment]
I had put this patch on hold while finishing up some 1.4.0 stuff, but I plan to return to this soon.  The fact that this is causing lots of test failures suggests that this could break things in bad ways for user code if we're not careful.  I think that the main issue is that the old code would implicitly pass through primitives that were of the wrong type and allow implicit numeric conversions to take place.  For instance, if I had a table that expected double-valued columns, it would be fine to pass integers since we never did any Scala -> Catalyst conversion for integers and the internal code implicitly handles these conversions somewhere.

I'll see if I can come up with a clean way of allowing these implicit numeric conversions to still take place but guarantee that they're performed as part of the inbound Row conversion rather than implicitly in lower-level code.

**Comment by JoshRosen** [comment]
It looks like we have some undefined behavior that may be very difficult to preserve.  If you declare a column to have some primitive type, like float, then proceed to pass in some value of an arbitrary different type, this won't cause any errors as long as you don't perform any operations on that column which rely on it being a particular type.  In a nutshell, the schema's type for a column seems to be irrelevant if that column is just passed through unmodified / unaccessed as part of query processing.

**Comment by JoshRosen** [comment]
I've pushed a change which will cause `ClassCastExceptions` to be thrown as early as possible in the Scala Row -> Catalyst Row conversion process. I've realized that this is going to fail a different set of tests due some null-handling corner-cases that I've missed, so I'm going to create a new `CatalystTypeConvertersSuite` and will try to write some test cases to serve as a spec for the converter behavior.

Technically, it looks like our Scaladoc API docs give us the leeway to throw exceptions if the input data doesn't match the expected schema and there's no mention of implicit casting / widening, so I think it's _technically_ okay to change this undefined behavior, although it could be frustrating for users.

```scala
   * :: DeveloperApi ::
   * Creates a [[DataFrame]] from an [[RDD]] containing [[Row]]s using the given schema.
   * It is important to make sure that the structure of every [[Row]] of the provided RDD matches
   * the provided schema. Otherwise, there will be runtime exception.
```

**Comment by JoshRosen** [comment]
I'm working on tackling the HadoopFsRelationTest failures right now.  Here's one odd failure from `SimpleTextHadoopFsRelationSuite`'s "save()/load() - partitioned table - simple queries" test:

```scala
java.lang.ClassCastException: org.apache.spark.sql.types.UTF8String cannot be cast to java.lang.Integer
	at scala.runtime.BoxesRunTime.unboxToInt(BoxesRunTime.java:106)
	at org.apache.spark.sql.catalyst.CatalystTypeConverters$IntConverter$.toCatalystImpl(CatalystTypeConverters.scala:293)
	at org.apache.spark.sql.catalyst.CatalystTypeConverters$CatalystTypeConverter.toCatalyst(CatalystTypeConverters.scala:84)
	at org.apache.spark.sql.catalyst.CatalystTypeConverters$$anonfun$createToCatalystConverter$1.apply(CatalystTypeConverters.scala:333)
	at org.apache.spark.sql.execution.RDDConversions$$anonfun$rowToRowRdd$1$$anonfun$apply$2.apply(ExistingRDD.scala:75)
	at org.apache.spark.sql.execution.RDDConversions$$anonfun$rowToRowRdd$1$$anonfun$apply$2.apply(ExistingRDD.scala:72)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at scala.collection.Iterator$$anon$14.hasNext(Iterator.scala:389)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at scala.collection.Iterator$class.isEmpty(Iterator.scala:256)
	at scala.collection.AbstractIterator.isEmpty(Iterator.scala:1157)
	at org.apache.spark.sql.execution.RDDConversions$$anonfun$rowToRowRdd$1.apply(ExistingRDD.scala:63)
	at org.apache.spark.sql.execution.RDDConversions$$anonfun$rowToRowRdd$1.apply(ExistingRDD.scala:62)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$17.apply(RDD.scala:686)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$17.apply(RDD.scala:686)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:277)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:244)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:277)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:244)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:63)
	at org.apache.spark.scheduler.Task.run(Task.scala:70)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by JoshRosen** [comment]
The datasources test failures were actually due to a bug in schema handling during data sources input conversion: we were using the relation schema, not the output schema, for performing conversion.  I've opened #6400 to fix this.

**Comment by JoshRosen** [comment]
I've rebased this on top of #6400 to verify that there aren't any more type conversion bugs.  Once #6400 gets merged, I'll rebase again and ping for review.

**Comment by JoshRosen** [comment]
Hmm, looks like another test is still failing even after including #6400.

**org.apache.spark.sql.DataFrameSuite.explode**:

```
Error Message

Invalid call to dataType on unresolved object, tree: 'letters
Stacktrace

sbt.ForkMain$ForkError: Invalid call to dataType on unresolved object, tree: 'letters
	at org.apache.spark.sql.catalyst.analysis.UnresolvedAttribute.dataType(unresolved.scala:59)
	at org.apache.spark.sql.catalyst.expressions.UserDefinedGenerator$$anonfun$1.apply(generators.scala:85)
	at org.apache.spark.sql.catalyst.expressions.UserDefinedGenerator$$anonfun$1.apply(generators.scala:85)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at org.apache.spark.sql.catalyst.expressions.UserDefinedGenerator.org$apache$spark$sql$catalyst$expressions$UserDefinedGenerator$$initializeConverters(generators.scala:85)
	at org.apache.spark.sql.catalyst.expressions.UserDefinedGenerator.<init>(generators.scala:90)
	at org.apache.spark.sql.DataFrame.explode(DataFrame.scala:993)
	at org.apache.spark.sql.DataFrameSuite$$anonfun$10.apply$mcV$sp(DataFrameSuite.scala:122)
	at org.apache.spark.sql.DataFrameSuite$$anonfun$10.apply(DataFrameSuite.scala:119)
	at org.apache.spark.sql.DataFrameSuite$$anonfun$10.apply(DataFrameSuite.scala:119)
	at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:166)
	at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
	at org.scalatest.FunSuite.withFixture(FunSuite.scala:1555)
	at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:163)
	at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:175)
	at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:175)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
	at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:175)
	at org.scalatest.FunSuite.runTest(FunSuite.scala:1555)
	at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:208)
	at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:208)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
	at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:208)
	at org.scalatest.FunSuite.runTests(FunSuite.scala:1555)
	at org.scalatest.Suite$class.run(Suite.scala:1424)
	at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1555)
	at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:212)
	at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:212)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
	at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:212)
	at org.scalatest.FunSuite.run(FunSuite.scala:1555)
	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:462)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:671)
	at sbt.ForkMain$Run$2.call(ForkMain.java:294)
	at sbt.ForkMain$Run$2.call(ForkMain.java:284)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by JoshRosen** [comment]
Ah, this failure is due to a change thatI made to UserDefinedGenerator.  It's now creating a single row converter and re-using it across calls to `eval(row)`, but this had the side-effect of causing it's child's attribute to be accessed before it has been resolved.  I've pushed a fix.

**Comment by JoshRosen** [comment]
@rxin, I noticed that the old code (and this code) might have a small inconsistency w.r.t how we handle `Option` values.  In `createToCatalystConverter`, the code extracts values from options, whereas `convertToCatalyst` does not attempt to do that.  Here's a test case which demonstrates this:

```scala
  test("option handling in convertToCatalyst") {
    assert(CatalystTypeConverters.convertToCatalyst(Some(123)) === Some(123))
  }

  test("option handling in createToCatalystConverter") {
    assert(CatalystTypeConverters.createToCatalystConverter(IntegerType)(Some(123)) === 123)
  }
```

I guess that the `convertToCatalyst` is only used in a couple of contexts which aren't passed options.  Maybe we should add another `case` statement to handle those, though, just to keep these two methods consistent.

By the way, I figured out the minor microbenchmark perf. issue that I mentioned offline: in the old code, `createToCatalystConverter` would return the same function for all primitives, whereas the new code returns different functions.  If you were converting a row which only contained numeric primitives, then the old code would have a monomorphic callsite to the conversion function whereas the new code  is polymorphic.  This issue also affects the common case of converting rows which only contain either primitive types of strings, since the new code takes what used to be a bimorphic calllsite and makes it polymorphic.  I've found a simple fix for this, which I'll push in a new commit.

**Comment by JoshRosen** [comment]
Alright, pushed a commit to document the Option-handling semantics as well as to address the method dispatch issues for primitive types.  This should be ready for review now.  /cc @davies, you might want to look at this also.

**Comment by JoshRosen** [comment]
Jenkins, retest this please.

**Comment by davies** [comment]
LGTM, thanks!

**Pull request closed without merging**
