### PR TITLE
[SPARK-44513][BUILD][3.4] Upgrade snappy-java to 1.1.10.3

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
- The pr is for branch-3.4.
- The pr aims to upgrade snappy-java from  1.1.10.2 to 1.1.10.3.

### Why are the changes needed?
1.The newest version include a bug fixed:
- Fix the GLIBC_2.32 not found issue of libsnappyjava.so in certain Linux distributions on s390x by @kun-lu20 in https://github.com/xerial/snappy-java/pull/481

2.Release notes:
https://github.com/xerial/snappy-java/releases/tag/v1.1.10.3

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA.

### CODE REVIEW

**Comment by panbingkun** [comment]
@LuciferYang

**Comment by panbingkun** [comment]
@LuciferYang

**Comment by panbingkun** [comment]
cc @wangyum

**Review by wangyum — APPROVED** [review]

**Review by LuciferYang — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Could you re-run the failed test pipelines, @panbingkun ?

**Comment by panbingkun** [comment]
> Could you re-run the failed test pipelines, @panbingkun ?

Done, let's waiting CI.

**Comment by panbingkun** [comment]
@LuciferYang Do we need to backport https://github.com/apache/spark/pull/42091 to branch-3.4
https://github.com/panbingkun/spark/actions/runs/5643752423/job/15345611131
image

**Comment by LuciferYang** [comment]
> @LuciferYang Do we need to backport #42091 to branch-3.4 https://github.com/panbingkun/spark/actions/runs/5643752423/job/15345611131 image

ok

**Comment by LuciferYang** [comment]
> @LuciferYang Do we need to backport #42091 to branch-3.4 https://github.com/panbingkun/spark/actions/runs/5643752423/job/15345611131 image

https://github.com/apache/spark/pull/42162

**Comment by LuciferYang** [comment]
`Python code generation check` failed too

image

**Comment by panbingkun** [comment]
> `Python code generation check` failed too
> 
> image

@dongjoon-hyun @HyukjinKwon @LuciferYang @wangyum 
To resolve the above issues, do we need to backport https://github.com/apache/spark/pull/41933 to branch-3.4?

**Comment by LuciferYang** [comment]
Can we just skip the check of `Python code generation check` in branch-3.4?

**Comment by HyukjinKwon** [comment]
yeah, I think so

**Comment by panbingkun** [comment]
Ignoring `connect-check-protos` logic in GA testing for branch-3.4
https://github.com/apache/spark/pull/42166

**Comment by panbingkun** [comment]
The GA finally turned green.

**Comment by wangyum** [comment]
Thanks. Merged to branch-3.4.

**Pull request closed without merging**
