### PR TITLE
[SPARK-24553][UI][FOLLOWUP][2.4 Backport] Fix unnecessary UI redirect

### PR DESCRIPTION
**Pull request by jerryshao**
## What changes were proposed in this pull request?

This is a backport PR of #23116 .

This PR is a follow-up PR of #21600 to fix the unnecessary UI redirect.

## How was this patch tested?

Local verification

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Merged to `branch-2.4`.

**Comment by dongjoon-hyun** [comment]
I had better ask about the target branches. :)
Thanks, @jerryshao . Now, it lands for 2.4.1.

**Comment by srowen** [comment]
@jerryshao you can close this now

**Comment by jerryshao** [comment]
OK, thanks for the reminder.

**Pull request closed without merging**
