### PR TITLE
[SPARK-45547][ML] Validate Vectors with built-in function

### PR DESCRIPTION
**Pull request by zhengruifeng**
### What changes were proposed in this pull request?
Validate Vectors with built-in function

### Why are the changes needed?
with built-in function, the logic might be optimized further

### Does this PR introduce _any_ user-facing change?
no

### How was this patch tested?
ci

### Was this patch authored or co-authored using generative AI tooling?
no

### CODE REVIEW

**Comment by srowen** [comment]
Is this actually faster? I would be surprised

**Comment by zhengruifeng** [comment]
```
scala> import org.apache.spark.ml.linalg._
     |
     | val df = Seq.range(0, 1000000).map(i => (i,Vectors.dense(Array.fill(256)(1.0)))).toDF("i", "vec")
     |
import org.apache.spark.ml.linalg._
val df: org.apache.spark.sql.DataFrame = [i: int, vec: vector]

scala> df.count()
23/10/17 16:28:31 WARN TaskSetManager: Stage 0 contains a task of very large size (1391 KiB). The maximum recommended task size is 1000 KiB.
val res0: Long = 1000000

scala> val validateUDF = udf { vector: Vector =>
     |     vector match {
     |       case dv: DenseVector =>
     |         dv.values.forall(v => !v.isNaN && !v.isInfinity)
     |       case sv: SparseVector =>
     |         sv.values.forall(v => !v.isNaN && !v.isInfinity)
     |     }
     |   }
val validateUDF: org.apache.spark.sql.expressions.UserDefinedFunction = SparkUserDefinedFunction($Lambda$4177/0x000000b00198fa00@17640714,BooleanType,List(Some(class[value[0]: vector])),Some(class[value[0]: boolean]),None,false,true)

scala> val validatedCol = forall(unwrap_udt(col("vec")).getField("values"), v => not(v.isNaN) && abs(v) =!= expr("double('inf')"))
val validatedCol: org.apache.spark.sql.Column = forall(unwrap_udt(vec)[values], lambdafunction(and(`!`(isNaN(x_0)), `!`(`=`(abs(x_0), double(inf)))), x_0))

scala> val start = System.currentTimeMillis; df.select(bool_and(validateUDF(col("vec")))).head(); System.currentTimeMillis - start
23/10/17 16:28:47 WARN TaskSetManager: Stage 3 contains a task of very large size (176683 KiB). The maximum recommended task size is 1000 KiB.
val start: Long = 1697531323779
val res1: Long = 4562

scala>

scala> val start = System.currentTimeMillis; df.select(bool_and(validatedCol)).head(); System.currentTimeMillis - start; System.currentTimeMillis - start
23/10/17 16:28:52 WARN TaskSetManager: Stage 6 contains a task of very large size (176683 KiB). The maximum recommended task size is 1000 KiB.
val start: Long = 1697531329903
val res2: Long = 4637
```

I did a quick test, it seems there is no significant change. Especially, this validation is only performed once.

Using built-in functions can help simplify the codes and get potential benefit from SQL optimization.

**Comment by srowen** [comment]
Ok seems fine if you like

**Comment by zhengruifeng** [comment]
thanks, I happen to find another a few similar places, please hold on and let me add them all

**Comment by zhengruifeng** [comment]
on second thought, let's let it alone

**Comment by zhengruifeng** [comment]
@srowen would you mind taking another look? I think all vector validation related udfs are covered in this PR.

when we check the values, the performances are similar;
when we check the size, the new implementation is much faster since it can directly utilize the `size` field in `VectorUDT`

**Review by srowen — APPROVED** [review]

**Comment by zhengruifeng** [comment]
merged to master

**Pull request closed without merging**
