### PR TITLE
[SPARK-21040][CORE][FOLLOW-UP] Only calculate executorKillTime when speculation is enabled

### PR DESCRIPTION
**Pull request by Ngone51**
### What changes were proposed in this pull request?

Only calculate `executorKillTime` in `TaskSetManager.executorDecommission()` when speculation is enabled.

### Why are the changes needed?

Avoid unnecessary operations to save time/memory.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass existed tests.

### CODE REVIEW

**Comment by Ngone51** [comment]
@prakharjain09 @cloud-fan Please take a look, thanks!

**Comment by cloud-fan** [comment]
looks reasonable.

**Comment by prakharjain09** [comment]
@Ngone51 Looks good.

**Comment by cloud-fan** [comment]
github action passed, merging to master!

**Comment by Ngone51** [comment]
thanks all!!

**Pull request closed without merging**
