### PR TITLE
[SPARK-41883][BUILD] Upgrade dropwizard metrics 4.2.15

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr aims upgrade dropwizard metrics to 4.2.15.

### Why are the changes needed?
The release notes as follows:

- https://github.com/dropwizard/metrics/releases/tag/v4.2.14
- https://github.com/dropwizard/metrics/releases/tag/v4.2.15

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass Github Actions

### CODE REVIEW

**Comment by srowen** [comment]
Can you try rerunning the tests? they're stuck or something

**Review by HyukjinKwon — APPROVED** [review]

**Comment by srowen** [comment]
Merged to master

**Comment by LuciferYang** [comment]
Thanks @srowen

**Comment by LuciferYang** [comment]
Thanks @HyukjinKwon

**Pull request closed without merging**
