### PR TITLE
[SPARK-11102] [SQL] Uninformative exception when specifing non-exist …

### PR DESCRIPTION
**Pull request by zjffdu**
…input for JSON data source

### CODE REVIEW

**Comment by srowen** [comment]
Looking good, though I'm not clear that this comment from the old PR got addressed: https://github.com/apache/spark/pull/9142#discussion_r42208743 CC @chenghao-intel

**Comment by zjffdu** [comment]
Still put the input paths checking in JsonRelation. Because there's still some cases that is valid for empty input.  e.g. when creating a table based on an empty directory.  The base class HadoopFsRelation don't know when fileStatusCache will be used. So it would be better put the input paths checking in sub class.

**Comment by zjffdu** [comment]
SPARK-11274 introduce the same issue in TextRelation. Need to fix it in TextRelation too. But SPARK-11264 is not in this branch. Should I rebase this branch and commit in this branch or make another PR ?

**Comment by chenghao-intel** [comment]
That's actually what I mean, this is a general problem of the empty path, we'd better fix it in one place, I thought we can fix it in the `fileStatusCache`, seems we have to take another solution.

I will look at the code, and give some input.

**Comment by chenghao-intel** [comment]
Probably we also need to add the assertion at:

```scala
class HadoopFsRelation {
...
  final private[sql] def buildScan(
      requiredColumns: Array[String],
      filters: Array[Filter],
      inputPaths: Array[String],
      broadcastedConf: Broadcast[SerializableConfiguration])
...
}
```

I'll agree the JsonRelation is not exactly the same case, as we will try to infer the schema in another code path. 
So will that be OK if we add assertion at the `buildScan` in the parent class(as above), and also add the assertion at the `override lazy val dataSchema = ...` in `JsonRelation`(not the `createBaseRdd`)?

/cc @liancheng

**Comment by srowen** [comment]
@zjffdu are you still working on this?

**Comment by zjffdu** [comment]
@chenghao-intel  The JsonRelation has another special case that it allow input paths as empty when it takes RDD[String] as input. So HadoopFsRelation can not assume all its sub classes must have non-empty input paths.  Maybe need to add another flag "allowEmptyInputPaths" in HadoopFsRelation and allow its implementation to decide that.

**Comment by zjffdu** [comment]
Close it as needs to rebase the code base. Open #9490

**Pull request closed without merging**
