### PR TITLE
[SPARK-30763][SQL][2.4] Fix java.lang.IndexOutOfBoundsException No group 1 for regexp_extract

### PR DESCRIPTION
**Pull request by beliefer**
### What changes were proposed in this pull request?
This PR follows https://github.com/apache/spark/pull/27508 and used to spark2.4.

### Why are the changes needed?
Fix a bug `java.lang.IndexOutOfBoundsException No group 1`

### Does this PR introduce any user-facing change?
Yes

### How was this patch tested?
New UT.

### CODE REVIEW

**Comment by beliefer** [comment]
cc @cloud-fan

**Review by cloud-fan — APPROVED** [review]

**Comment by beliefer** [comment]
retest this please

**Review by HyukjinKwon — APPROVED** [review]

**Comment by cloud-fan** [comment]
thanks, merging to 2.4!

**Comment by dongjoon-hyun** [comment]
+1, late LGTM. Thank you, @beliefer , @cloud-fan , @HyukjinKwon .

**Comment by maropu** [comment]
late LGTM, thanks for the backport, @beliefer !

**Comment by beliefer** [comment]
@cloud-fan @HyukjinKwon @dongjoon-hyun @maropu Thanks a lot!

**Pull request closed without merging**
