### PR TITLE
[SPARK-12396][Core]Once driver connect to a master successfully, stop it connect to master again.

### PR DESCRIPTION
**Pull request by echoTomei**

### CODE REVIEW

**Comment by andrewor14** [comment]
ok to test

**Comment by andrewor14** [comment]
Good catch, this change looks fine.

**Comment by andrewor14** [comment]
@echoTomei it's failing style tests because there's a whitespace at the end of the line

**Comment by echoTomei** [comment]
@andrewor14  Sorry for my careless.I'll create another PR.

**Comment by echoTomei** [comment]
@SparkQA The build error shows that  the function cancel() is not a member of [java.util.concurrent.ScheduledFuture[_]] . I check the interface ScheduledFuture API ,confirming that this interface has cancel() function. So I don't understand why occur this error. Can you give me some suggestion?Thanks.

**Comment by andrewor14** [comment]
retest this please

**Comment by andrewor14** [comment]
That is really confusing... @srowen do you know if we're missing something obvious?

**Comment by srowen** [comment]
Actually the error says that the var is an `AtomicReference` and this does not have a `cancel` method. Indeed, it does in master, after https://github.com/apache/spark/commit/e1bcf6af9ba4f131f84d71660d0ab5598c0b7b67

Is this PR against a quite old version of master? while it doesn't technically need a rebase, it really does.

**Comment by zsxwing** [comment]
I think a better approach is changing `registrationRetryThread.scheduleAtFixedRate` to `registrationRetryThread.schedule`.

**Comment by andrewor14** [comment]
> I think a better approach is changing registrationRetryThread.scheduleAtFixedRate to registrationRetryThread.schedule.

+1. Right now we call it both recursively and iteratively, which doesn't make sense...

**Comment by echoTomei** [comment]
It seemed that change to registrationRetryThread.schedule is a better way.

**Comment by zsxwing** [comment]
Could you rebase on the latest master?

**Comment by andrewor14** [comment]
Can you close this PR now that you've opened another one #10447

**Pull request closed without merging**
