### PR TITLE
[SPARK-6827] [mllib] Wrap FPGrowthModel.freqItemsets and make it consistent with Java API

### PR DESCRIPTION
**Pull request by yanboliang**
Make PySpark `FPGrowthModel.freqItemsets` consistent with Java/Scala API like `MatrixFactorizationModel.userFeatures`
It return a RDD with each tuple is composed of an array and a long value.
I think it's difficult to implement namedtuples to wrap the output because items of freqItemsets can be any type with arbitrary length which is tedious to impelement corresponding SerDe function.

### CODE REVIEW

**Comment by mengxr** [comment]
@yanboliang Sent you a PR at https://github.com/yanboliang/spark/pull/2 for using namedtuples.

I'm also thinking about pickling the items into byte strings on the Python side before training. Then on the JVM side, the items are all strings and we don't need to worry about the compatibility of SerDe. When we map the frequent itemsets back, we can unpickle the byte strings. Maybe we can try this in another PR.

**Comment by yanboliang** [comment]
@mengxr Thank you for your comments and help, I have merged your PR to this PR.
I will investigate the pickle/unpickle problems and file another PR to resolve it.

**Comment by mengxr** [comment]
test this please

**Comment by mengxr** [comment]
LGTM. Merged into master. Thanks!

**Comment by mengxr** [comment]
That is different. In FPGrowth, we don't really care about the item type as long as they are serializable. So it is not necessary to map Python objects into their equivalent JVM objects through SerDes. Instead, we can pickle the items on Python side and treat all items as strings on the JVM side. I'm not sure whether it is worth doing this optimization. Maybe we should wait and see whether there are issues with the current implementation first.

**Pull request closed without merging**
