### PR TITLE
[SPARK-7837] [SQL] Avoids double closing output writers when commitTask() fails

### PR DESCRIPTION
**Pull request by liancheng**
When inserting data into a `HadoopFsRelation`, if `commitTask()` of the writer container fails, `abortTask()` will be invoked. However, both `commitTask()` and `abortTask()` try to close the output writer(s). The problem is that, closing underlying writers may not be an idempotent operation. E.g., `ParquetRecordWriter.close()` throws NPE when called twice.

### CODE REVIEW

**Comment by liancheng** [comment]
cc @yhuai

**Comment by yhuai** [comment]
LGTM

**Comment by liancheng** [comment]
Merging to master and branch-1.5.

**Comment by liancheng** [comment]
Merged to master and branch-1.5.

**Pull request closed without merging**
