### PR TITLE
[SPARK-21789][PYTHON] Remove obsolete codes for parsing abstract schema strings

### PR DESCRIPTION
**Pull request by HyukjinKwon**
## What changes were proposed in this pull request?

This PR proposes to remove private functions that look not used in the main codes, `_split_schema_abstract`, `_parse_field_abstract`, `_parse_schema_abstract` and `_infer_schema_type`.

## How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @davies and @joshrosen, I was looking at the first place that introduced this - https://github.com/apache/spark/commit/880eabec37c69ce4e9594d7babfac291b0f93f50. Could you take a look and see if i missed something here when you have some time?

I was thinking we should explicitly expose this or remove them out rather than leaving them in the codes.

**Comment by HyukjinKwon** [comment]
gentle ping @davies and @JoshRosen. I guess it is mainly just about a decision - whether we expose it in any way or remove it out if I am not mistaken.

**Comment by HyukjinKwon** [comment]
cc @holdenk too ...

**Comment by felixcheung** [comment]
@ueshin

**Comment by holdenk** [comment]
LGTM

**Comment by holdenk** [comment]
Although I'd recommend doing a JIRA.

**Comment by HyukjinKwon** [comment]
Definitely @holdenk. Thanks for taking a look

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
I double checked these **`_split_schema_abstract`**, **`_parse_field_abstract`**, **`_parse_schema_abstract`** and **`_infer_schema_type`** are not used in a public API.

Under `./python/pyspark`:

**1. `_split_schema_abstract`**:

```
$ grep -r "_split_schema_abstract" .
```

shows

```
./sql/types.py:def _split_schema_abstract(s):
./sql/types.py:    >>> _split_schema_abstract("a b  c")
./sql/types.py:    >>> _split_schema_abstract("a(a b)")
./sql/types.py:    >>> _split_schema_abstract("a b[] c{a b}")
./sql/types.py:    >>> _split_schema_abstract(" ")
./sql/types.py:    parts = _split_schema_abstract(s)
```

Non doctests / tests:

```
./sql/types.py:    parts = _split_schema_abstract(s)
```

This is within **3. `_parse_schema_abstract`**:


https://github.com/apache/spark/blob/b56f79cc359d093d757af83171175cfd933162d1/python/pyspark/sql/types.py#L1274


**2. `_parse_field_abstract`**:

```
$ grep -r "_parse_field_abstract" .
```

shows

```
./sql/types.py:def _parse_field_abstract(s):
./sql/types.py:    >>> _parse_field_abstract("a")
./sql/types.py:    >>> _parse_field_abstract("b(c d)")
./sql/types.py:    >>> _parse_field_abstract("a[]")
./sql/types.py:    >>> _parse_field_abstract("a{[]}")
./sql/types.py:    fields = [_parse_field_abstract(p) for p in parts]
```

Non doctests / tests:

```
fields = [_parse_field_abstract(p) for p in parts]
```

This is within **3. `_parse_schema_abstract`**:

https://github.com/apache/spark/blob/b56f79cc359d093d757af83171175cfd933162d1/python/pyspark/sql/types.py#L1275


**3. `_parse_schema_abstract`**:

```
$ grep -r "_parse_schema_abstract" .
```

shows

```
./sql/tests.py:        from pyspark.sql.types import _parse_schema_abstract, _infer_schema_type
./sql/tests.py:        schema = _parse_schema_abstract(abstract)
./sql/types.py:        return StructField(name, _parse_schema_abstract(s[idx:]), True)
./sql/types.py:def _parse_schema_abstract(s):
./sql/types.py:    >>> _parse_schema_abstract("a b  c")
./sql/types.py:    >>> _parse_schema_abstract("a[b c] b{}")
./sql/types.py:    >>> _parse_schema_abstract("c{} d{a b}")
./sql/types.py:    >>> _parse_schema_abstract("a b(t)").fields[1]
./sql/types.py:        return _parse_schema_abstract(s[1:-1])
./sql/types.py:        return ArrayType(_parse_schema_abstract(s[1:-1]), True)
./sql/types.py:        return MapType(NullType(), _parse_schema_abstract(s[1:-1]))
./sql/types.py:    >>> schema = _parse_schema_abstract("a b c d")
./sql/types.py:    >>> schema = _parse_schema_abstract("a[] b{c d}")
```

Non doctests / tests:

```
./sql/types.py:        return StructField(name, _parse_schema_abstract(s[idx:]), True)
./sql/types.py:        return _parse_schema_abstract(s[1:-1])
./sql/types.py:        return ArrayType(_parse_schema_abstract(s[1:-1]), True)
./sql/types.py:        return MapType(NullType(), _parse_schema_abstract(s[1:-1]))
```

These four are within **`2. _parse_field_abstract`** and within **`3. _parse_schema_abstract`**:

https://github.com/apache/spark/blob/b56f79cc359d093d757af83171175cfd933162d1/python/pyspark/sql/types.py#L1243

https://github.com/apache/spark/blob/b56f79cc359d093d757af83171175cfd933162d1/python/pyspark/sql/types.py#L1266

https://github.com/apache/spark/blob/b56f79cc359d093d757af83171175cfd933162d1/python/pyspark/sql/types.py#L1269

https://github.com/apache/spark/blob/b56f79cc359d093d757af83171175cfd933162d1/python/pyspark/sql/types.py#L1272


**4. `_infer_schema_type`**:

```
$ grep -r "_infer_schema_type"
```

shows

```
./sql/tests.py:        from pyspark.sql.types import _parse_schema_abstract, _infer_schema_type
./sql/tests.py:        typedSchema = _infer_schema_type(rdd.first(), schema)
./sql/types.py:def _infer_schema_type(obj, dataType):
./sql/types.py:    >>> _infer_schema_type(row, schema)
./sql/types.py:    >>> _infer_schema_type(row, schema)
./sql/types.py:        eType = _infer_schema_type(obj[0], dataType.elementType)
./sql/types.py:        return MapType(_infer_schema_type(k, dataType.keyType),
./sql/types.py:                       _infer_schema_type(v, dataType.valueType))
./sql/types.py:        fields = [StructField(f.name, _infer_schema_type(o, f.dataType), True)
```

Non doctests / tests:

```
./sql/types.py:        eType = _infer_schema_type(obj[0], dataType.elementType)
./sql/types.py:        return MapType(_infer_schema_type(k, dataType.keyType),
./sql/types.py:                       _infer_schema_type(v, dataType.valueType))
./sql/types.py:        fields = [StructField(f.name, _infer_schema_type(o, f.dataType), True)

```

These four are within **4. `_infer_schema_type`**:

https://github.com/apache/spark/blob/b56f79cc359d093d757af83171175cfd933162d1/python/pyspark/sql/types.py#L1299

https://github.com/apache/spark/blob/b56f79cc359d093d757af83171175cfd933162d1/python/pyspark/sql/types.py#L1304

https://github.com/apache/spark/blob/b56f79cc359d093d757af83171175cfd933162d1/python/pyspark/sql/types.py#L1305

https://github.com/apache/spark/blob/b56f79cc359d093d757af83171175cfd933162d1/python/pyspark/sql/types.py#L1311

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by HyukjinKwon** [comment]
Thank you @felixcheung and @holdenk.

**Pull request closed without merging**
