### PR TITLE
[SPARK-25952][SQL] Passing actual schema to JacksonParser

### PR DESCRIPTION
**Pull request by MaxGekk**
## What changes were proposed in this pull request?

The PR fixes an issue when the corrupt record column specified via `spark.sql.columnNameOfCorruptRecord` or JSON options `columnNameOfCorruptRecord` is propagated to JacksonParser, and returned row breaks an assumption in `FailureSafeParser` that the row must contain only actual data. The issue is fixed by passing actual schema without the corrupt record field into `JacksonParser`.

## How was this patch tested?

Added a test with the corrupt record column in the middle of user's schema.

### CODE REVIEW

**Comment by MaxGekk** [comment]
@cloud-fan @HyukjinKwon May I ask you to have a look at this PR.

**Comment by cloud-fan** [comment]
good catch! do we need to fix the CSV side?

**Comment by HyukjinKwon** [comment]
For CSV, looks we are already doing so:

https://github.com/apache/spark/blob/76813cfa1e2607ea3b669a79e59b568e96395b2e/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/csvExpressions.scala#L109-L111

**Comment by HyukjinKwon** [comment]
@MaxGekk, BTW, can you call `verifyColumnNameOfCorruptRecord` here and datasource as well for JSON and CSV? Of course in a separate PR.

**Review by HyukjinKwon — APPROVED** [review]
LGTM

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
