### PR TITLE
[SPARK-47402][BUILD] Upgrade `ZooKeeper` to 3.9.2

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to upgrade `ZooKeeper` to 3.9.2.

### Why are the changes needed?

To match the versions with the latest server-side bug fixes.
- https://zookeeper.apache.org/doc/r3.9.2/releasenotes.html

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the CIs.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Review by bjornjorgensen — APPROVED** [review]

**Comment by bjornjorgensen** [comment]
LGTM

**Comment by dongjoon-hyun** [comment]
Thank you, @bjornjorgensen .

**Comment by dongjoon-hyun** [comment]
Could you review this dependency PR, @huaxingao ?

**Review by huaxingao — APPROVED** [review]
LGTM. Thanks @dongjoon-hyun

**Comment by dongjoon-hyun** [comment]
Thank you, @huaxingao ! Merged to master for Apache Spark 4.0.0.

**Pull request closed without merging**
