### PR TITLE
[SPARK-27482][SQL][WEBUI] Show BroadcastHashJoinExec numOutputRows statistics info on SparkSQL UI page

### PR DESCRIPTION
**Pull request by pengbo**
## What changes were proposed in this pull request?
Currently, the SparkSQL UI page shows only actual metric info in each SparkPlan node. However with `statistics` info may help us understand how the plan is designed and the reason it runs slowly. This PR is to show `BroadcastHashJoinExec` `numOutputRows` `statistic` info on SparkSQL UI page first when it's available. 

The main changes:
1. Add `stats` field in `SparkPlan`
2. Initialize `BroadcastHashJoinExec` with the `stats` in `Join` `LogicalPlan`
3. Add `stats` field in `SQLMetric` and show it on UI page when it's available

## How was this patch tested?
Regarding unit test has been added, manual UI test has been tested

SPARK-27482-1

### CODE REVIEW

**Comment by pengbo** [comment]
CC  @cloud-fan @srowen @dongjoon-hyun

**Comment by cloud-fan** [comment]
I agree with the use case, but the implementation is too hacky. We need a general approach the propagate the statistics from logical plan to physical plan.

**Comment by pengbo** [comment]
> I agree with the use case, but the implementation is too hacky. We need a general approach to propagate the statistics from logical plan to physical plan.

How about:
1. Add `stats` field and getter/setter in `SparkPlanStats` (trait of `SparkPlan`)
2. Create a `StatisticsPropagation` `SparkPlan` strategy as the first strategy after `extraPlanningStrategies` that creates a `PlanLater(loginPlan)` with `stats` copied from `LogicalPlan`. To avoid infinity loop, one variable `isStatsPropagated` in `LogicalPlan` may be needed to indicate whether the `LogicalPlan` has been applied the strategy.
3. `SparkPlan.makeCopy` copy the `stats` as well

Your feedback will be appreciated. @cloud-fan

**Comment by pengbo** [comment]
> I agree with the use case, but the implementation is too hacky. We need a general approach to propagate the statistics from logical plan to physical plan.

Thanks for your comments. 

How about:
1. Add `stats` field and getter/setter in `SparkPlanStats` (trait of `SparkPlan`)
2. Add `setPlanProperty(plan, candidate)` before `collectPlaceholders` in `QueryPlanner.plan` which is override by `SparkPlanner` to set the `stats` value in `candidate: SparkPlan` from `plan: LogicalPlan`

Your feedback is appreciated.  @cloud-fan @dongjoon-hyun

**Comment by pengbo** [comment]
Propagate the statistics from logical plan to physical plan in Strategy.apply method instead

**Comment by dongjoon-hyun** [comment]
ok to test

**Comment by pengbo** [comment]
@dongjoon-hyun @cloud-fan 
Back to use propagate template method in `QueryPlanner.plan` method, as the previous way may break the `SparkStrategy` Extension compatibility.

**Comment by pengbo** [comment]
retest it please

**Comment by pengbo** [comment]
Thanks @cloud-fan has created a more general approach 
https://github.com/apache/spark/pull/24626

**Comment by cloud-fan** [comment]
Hi @pengbo, my PR just adds the foundation: physical plan knows the statistics of its corresponding logical plan. But we still need some work to make the statistics available in the SQL UI. We still need your PR after my PR is merged.

**Comment by pengbo** [comment]
> Hi @pengbo, my PR just adds the foundation: physical plan knows the statistics of its corresponding logical plan. But we still need some work to make the statistics available in the SQL UI. We still need your PR after my PR is merged.

Thanks for info, I will open another one when your PR is merged.

**Pull request closed without merging**
