### PR TITLE
[SPARK-7230] [SPARKR] Make RDD private in SparkR.

### PR DESCRIPTION
**Pull request by shivaram**
This change makes the RDD API private in SparkR and all internal uses of the SparkR API use SparkR::: to access private functions.

### CODE REVIEW

**Comment by shivaram** [comment]
cc @rxin @pwendell

**Comment by pwendell** [comment]
Thanks Shivaram, one thing is the example still refer to the lower level API - however all of them can be pretty easily written using Dataframes I believe. Would it make sense to update those also? It might be confusing for people otherwise.

**Comment by shivaram** [comment]
Ah yes - thats a good point. I think we can remove the RDD examples and instead add data frame examples as described in https://issues.apache.org/jira/browse/SPARK-6799 . Porting the existing examples may be tricky as they do things like KMeans or Logistic Regression and we don't have ML integration yet.

**Comment by rxin** [comment]
Thanks. I'm merging this.

**Pull request closed without merging**
