### PR TITLE
[SPARK-22452][SQL] Add getDouble to DataSourceV2Options

### PR DESCRIPTION
**Pull request by skambha**
- Implemented getDouble method in DataSourceV2Options
- Add unit test

### CODE REVIEW

**Comment by gatorsmile** [comment]
ok to test

**Comment by cloud-fan** [comment]
LGTM

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Comment by skambha** [comment]
Thanks @cloud-fan, @gatorsmile

**Pull request closed without merging**
