### PR TITLE
[SPARK-12340][SQL]fix Int overflow in the SparkPlan.executeTake, RDD.take and AsyncRDDActions.takeAsync

### PR DESCRIPTION
**Pull request by QiangCai**
@srowen  I new this pull request to to resolve the problem.

another pull request 
https://github.com/apache/spark/pull/10310

jira
https://issues.apache.org/jira/browse/SPARK-12340

### CODE REVIEW

**Comment by srowen** [comment]
LGTM

**Comment by sarutak** [comment]
@QiangCai LGTM but could you add test cases?

**Comment by QiangCai** [comment]
@sarutak I will try to add test cases.

**Comment by QiangCai** [comment]
@sarutak When  I am rebasing  from master,  I get many conflicts. I don't known how to resolve it. I have  just pushed  the commit "merge".

**Comment by srowen** [comment]
@QiangCai the merge commit is wrong as you can see. You can revert it, commit, rebase from master, fix conflicts, and force-push a merge to fix. Or, if you're not sure how to do it, close this PR and open a new one.

**Comment by QiangCai** [comment]
I have created another pull request https://github.com/apache/spark/pull/10562.

**Pull request closed without merging**
