### PR TITLE
[SPARK-10723] Add reduceOption API to RDD

### PR DESCRIPTION
**Pull request by Attsun1031**
This is PR for https://issues.apache.org/jira/browse/SPARK-10723
#### Question

When I ran tests, mima binary compatibility test failed because of following error. 

```
method reduceOption(org.apache.spark.api.java.function.Function2)com.google.common.base.Optional in trait org.apache.spark.api.java.JavaRDDL
ike does not have a correspondent in old version
```

To avoid this error, I mark reduceOption method as Experimental, and pass mima tests.

Is it proper way to cope with such error ?

### CODE REVIEW

**Comment by srowen** [comment]
Yes, you can't quite just add the method to this trait as it is technically a breaking change. For various reasons, i believe we can exclude it.

However, I personally am not convinced this method pulls its weight and justifies the change. You can use `isEmpty` and I'm not sure the JIRA notes that.

**Comment by srowen** [comment]
Do you mind closing this PR? There are a couple votes for wont-fix.

**Comment by Attsun1031** [comment]
Thanks for comment and advice. I'll use isEmpty or fold to deal with my case.

**Comment by davies** [comment]
@Attsun1031 Can you close this?

**Pull request closed without merging**
