### PR TITLE
[Spark-10692][Streaming] Expose failureReasons in BatchInfo for streaming UI to clear failed batches

### PR DESCRIPTION
**Pull request by tdas**
Slightly modified version of #8818, all credit goes to @zsxwing

### CODE REVIEW

**Comment by zsxwing** [comment]
LGTM

**Comment by harishreedharan** [comment]
Is this for a different branch? Why a new PR for the same thing?

**Comment by tdas** [comment]
@harishreedharan I took over the PR that @zsxwing was doing to speed up the process... 1.5.1 to be cut any time.

**Comment by tdas** [comment]
Merging this master and 1.5

**Comment by rxin** [comment]
I've merged this.

**Pull request closed without merging**
