### PR TITLE
[SPARK-22308][test-maven] Support alternative unit testing styles in external applications

### PR DESCRIPTION
**Pull request by nkronenfeld**
Continuation of PR#19528 (https://github.com/apache/spark/pull/19529#issuecomment-340252119)

The problem with the maven build in the previous PR was the new tests.... the creation of a spark session outside the tests meant there was more than one spark session around at a time.
I was using the spark session outside the tests so that the tests could share data; I've changed it so that each test creates the data anew.

### CODE REVIEW

**Comment by nkronenfeld** [comment]
@gatorsmile @srowen  I think this is set now.

**Comment by nkronenfeld** [comment]
ok, now I question my own testing... does maven not run scalastyle tests? Or did I not run the tests properly somehow? I just ran mvn test from root, and it all seemed to work on my machine

**Comment by gatorsmile** [comment]
To check the syntax, you can run the following command
> dev/lint-scala

**Review by gatorsmile — APPROVED** [review]
LGTM

**Comment by gatorsmile** [comment]
Thanks! Merged to master.

**Pull request closed without merging**
