### PR TITLE
[SPARK-14790] Always run scalastyle on sbt compile and test

### PR DESCRIPTION
**Pull request by ericl**
## What changes were proposed in this pull request?

Sbt compile and test should also run scalastyle. This makes it less likely you forget to run scalastyle and fail in jenkins. Scalastyle results are cached for efficiency.

This patch was originally written by @ahirreddy; I just fixed it up to work with scalastyle 0.8.0.
## How was this patch tested?

Tested manually with `build/sbt package`.

### CODE REVIEW

**Comment by srowen** [comment]
I'm not sure about that; it's a separable idea and phase. In Maven, this would generally happen in "verify" phase after "compile". In fact we've had the opposite complaint before, that some other build scripts run style checks and it should be disable-able. I think this adds a fair bit of code too. I would not make this change.

**Comment by rxin** [comment]
I was concerned about this increasing the time but last night I had 3 prs that failed style checkers and now do think it would've been great if the checking was more automatic...!

**Comment by srowen** [comment]
(Can it be done without all this code though?)
You can run style checks before submitting of course, and they do get run by the PR builder. Does it change much except forcing you to run style checks when compiling?

**Comment by rxin** [comment]
Yea I think the main thing is that this will be more integrated and more automated. Many pull requests when they were first submitted fail our style checker, both from long-term contributors and newer ones.

**Comment by srowen** [comment]
I'm not very against it (though Maven should ideally change to check style as well on 'pre-compile'). I remember someone arguing that they didn't want to have to pass all style checks every time they compile a WIP patch locally and so didn't want them to be forced for every compile. It's an argument to consider, or at least, why it works this way now.

**Comment by rxin** [comment]
Would it be possible to disable this via some other thing? Then we satisfy both worlds. I just took a look at the pr backlog and almost every pr failed style test once!

**Comment by ericl** [comment]
@rxin @srowen I added a check for `NOLINT_ON_COMPILE` in the environment, which disables this check if set. The user can add this to their shell profile if they want. I couldn't really figure how how to get sbt to print out an message advising of this option, but at least it's there.

**Comment by rxin** [comment]
I believe @vanzin  was the main person that didn't like this. Copy him here just in case.

**Comment by vanzin** [comment]
I'm not strongly opposed, it's just that when debugging things I sometimes add a bunch of "println" statements in the code to trace what's going on. Having the style checks running would make that a lot more complicated. Guess I'll have to get used to using `System.err.printf` instead, until someone adds a style rule for that too...

**Comment by rxin** [comment]
There is an environment variable here that you can set in your profile to never trigger this.

**Comment by vanzin** [comment]
> There is an environment variable here that you can set in your profile

Yeah, I saw that, but I don't start sbt every time I run something, it's just running in the background all the time, so I can't really change that at will. Anyway, no biggie, I can live with the change.

**Comment by ericl** [comment]
The println() is a good point. Let me see if I can turn that to a warn just in the compile check.

**Comment by ericl** [comment]
Same with import ordering. We can probably turn those to WARN on compile step. Trying to figure out how to do that without forking the entire xml config...

**Comment by vanzin** [comment]
The maven plugin has a `failOnViolation` configuration; I assume the sbt one has something similar. Maybe just setting that to `false` during test or compile? Then people will get the errors and warnings, but their build won't fail.

Not as effective as failing the build, though.

**Comment by srowen** [comment]
I like the idea of just warning, rather than making the rules slightly different. It's simpler. I suppose it only benefits those who are kind of looking for style failures, but that's the purpose. It can't stop people from submitting with a style problem, and Jenkins still fails the build on style violations either way.

**Comment by ericl** [comment]
@vanzin scalastyle has this option to not fail the task on error. The problem I ran into with this was with SBT task caching, which hides the warnings if you ever compiled the code before. This didn't seem very friendly since your output was basically unpredictable. Also I think warnings tend to get lost since there are a lot of other ones in the build already.

I opted to just turn the `println` thing into a warning on compile, keeping everything else as an error. I think this is probably fine because most developers remember to remove their debug prints before submitting code for review, but more easily forget other style nits.

The current implementation is a hacky search-and-replace in the xml, but this seemed more maintainable than copying the entire xml file. The way it's done now you get a sbt error if the replacement ever fails, so it will not break easily.

**Comment by srowen** [comment]
This just seems like a lot of complexity, versus just adding style checks as warnings -- or am I misunderstanding what it would take to just enable that? it seems like a few lines of config change, except perhaps this issue of caching. Even that, not sure if it's worth working around. We're just trying to make style violations somewhat more visible during development.

**Comment by vanzin** [comment]
I think part of the complexity is because of the cached task... I'm not exactly sure I understand what it's doing. Is it just avoiding re-building the list of files on every invocation of `compile` or `test`? If that's the case, if you add a new file, won't it be skipped by the checks? And if you remove a file, won't you end up with an error?

**Comment by ericl** [comment]
Most of the code in `cachedScalaStyle` is just the boilerplate needed to call scalastyle manually. The caching code is only a few lines supporting the FileFunctions.cached call (it's a built-in sbt function: http://www.scala-sbt.org/0.13.0/docs/faq.html).

We could remove the task caching code, however this significantly impacts incremental compile time (when I evaluated it, `~compile` went up from 3s -> 8s, and would go up more on slower machines).

Since the purpose of the sbt build is to support faster iteration in dev, I think it's worth the lines to give immediate style feedback. I don't quite buy the complexity argument here, since the added code is self-contained and does not impact other components.

**Comment by vanzin** [comment]
Ignoring the complexity argument for a bit, does the caching work correctly when you add or remove files from the repo? i.e. are new files checked and removed files ignored?

**Comment by ericl** [comment]
Yeah, I just double checked those cases and FileFunction.cached handles it correctly. Also FWIW we've been using this rule internally at databricks for a while, and it's worked fine.

**Comment by vanzin** [comment]
It's unfortunate that you need so much code for something that should be simple, but well. Only minor issues I see are:

- IIUC, changing the scalastyle configuration will not make sbt use the new rules; you'd need to restart sbt. Correct? Given how rarely that changes, it's probably ok.

- It'd be nice if you could disable or enable the checks inside an existing sbt session, instead of having to exit sbt and change the env variable. But also not a big deal, especially with the println changes.

**Comment by ericl** [comment]
That's right, you need to run `reload` to pick up the new changes to the xml. And for the runtime toggle, I think maybe keep it simple for now, since you can always scalastyle manually.

**Comment by jodersky** [comment]
Thanks for looking into this, I constantly forget to run the style checker.

Since you change the dependencies of `compile`, it would be great to still have a task that *just compiles* (maybe call it `compileOnly`) the sources, for debugging purposes, in case someone just wants to run a quick dirty fix without worrying about style issues.

As an alternative, (and my preferred choice) what about creating a separate task "validate" or something along the line that depends on `compile`, `scalastyle` and maybe also runs the license header checks? It would avoid lots of extra code in the build, not change the meaning of `compile`, and still enable developers to *only* compile when they are debugging.

**Comment by jodersky** [comment]
As a follow up to @vanzin's comment:

> It'd be nice if you could disable or enable the checks inside an existing sbt session, instead of having to exit sbt and change the env variable. But also not a big deal, especially with the println changes.

you could actually do that by defining a new setting like "enableChecks" and then run "set enableChecks := false" in your existing sbt session. It's not ideal however, and in general sbt encourages you to define new tasks that do things with the results of other, existing tasks.
(That's why I would prefer to define a new task that runs the style checks and compile, instead of changing compile)

**Comment by ericl** [comment]
@jodersky Could you get the validate task to run for things like `~sql/test-only` though? Seems like it would be outside the task dag of most common operations, which would defeat the purpose (since you may as well just run scalastyle manually).

I am interested in getting the settings var to work, but that seems to be beyond the scope of my sbt foo... for the settings key I define I get
```
> set lintOnCompile := true
<set>:1: error: not found: value lintOnCompile
lintOnCompile := true
^
[error] Type error in expression
```

Interestingly sbt still tab-completes it...

**Comment by jodersky** [comment]
Hmm, maybe you need to add the project or config too? As in "set lintOnCompile in project in Config := true"? Sbt isn't too friendly when setting command line options in an interactive session.

Regarding your first question, you're correct that the validate task would not integrate into the DAG of existing tasks like `~sql/test-only`. The question is whether you actually want that though?

The main issue I see is that hooking into compile makes things more complicated for developers wanting to do quick and dirty prototyping, and does not really correspond to the meaning of "compile" that people used to sbt might expect. I see the advantages of integrated stylechecking though (I forget it often myself), I just don't think it should be integrated into compiling.

As a compromise, what do you think of adding style and other validation into the `package` task? It is run far less frequently during normal development but I still usually run it once before submitting a PR.

As a comprom

**Comment by rxin** [comment]
hm most people don't run package and just compile or test:compile, so adding it there would reduce the gain.

**Comment by jodersky** [comment]
Fair enough, test:compile is alright too. I would just avoid compile:compile

**Comment by ericl** [comment]
Ah, that syntax seems complicated enough to not be worth it (probably no-one will remember how to set it).

I think that for those with workflows that conflict with scalastyle, they can just set `NOLINT_ON_COMPILE=1` in their bashrc. Though hopefully most contributors keep it enabled, so we avoid the jenkins round-trips.

My reservation against doing it halfway is that it seems likely to be confusing for those that don't appreciate the nuances of e.g. compile / package.

**Comment by rxin** [comment]
I just ran into this issue again (pull requests failing style test). I'm going to merge this. Let's see how it goes ... we can always disable it if it ends up too annoying.

**Pull request closed without merging**
