### PR TITLE
[SPARK-6016][SQL] Cannot read the parquet table after overwriting the existing table when spark.sql.parquet.cacheMetadata=true

### PR DESCRIPTION
**Pull request by yhuai**
Please see JIRA (https://issues.apache.org/jira/browse/SPARK-6016) for details of the bug.

### CODE REVIEW

**Comment by yhuai** [comment]
@liancheng Can we remove `FilteringParquetRowInputFormat` since task side split is in parquet?

**Comment by liancheng** [comment]
@yhuai As long as we decide to completely deprecate client side metadata reading, it's OK to remove `FilteringParquetInputFormat`.

**Comment by liancheng** [comment]
@yhuai Actually, as we discussed offline, `FilteringParquetRowInputFormat` is still necessary, as we have to do schema merging in `getSplits` to prevent the exception thrown in [SPARK-6010] [1]

[1]: https://issues.apache.org/jira/browse/SPARK-6010

**Comment by liancheng** [comment]
This LGTM, please help rebasing it, then I can merge it.

**Comment by liancheng** [comment]
Merging into master and branch-1.3, thanks!

**Comment by karthikgolagani** [comment]
@liancheng 
Hi lian, if you are using sparkContext(sc), you can set ("parquet.enable.summary-metadata", "false") like below:

sc.("parquet.enable.summary-metadata", "false"). This fixed my issue instantly .
I did it in my spark streaming application.

> WARN ParquetOutputCommitter: could not write summary file for hdfs://localhost/user/hive/warehouse java.lang.NullPointerException

**Pull request closed without merging**
