### PR TITLE
[SPARK-6894]spark.executor.extraLibraryOptions => spark.executor.extraLibraryPath

### PR DESCRIPTION
**Pull request by WangTaoTheTonic**
https://issues.apache.org/jira/browse/SPARK-6894

cc @vanzin

### CODE REVIEW

**Comment by srowen** [comment]
Yes, good catch. LGTM. @vanzin

**Comment by sryza** [comment]
LGTM as well

**Comment by vanzin** [comment]
Oops. LGTM.

**Comment by andrewor14** [comment]
Oops, merging this into master thanks.

**Pull request closed without merging**
