### PR TITLE
[SPARK-11746][CORE]Use cache-aware method dependencies

### PR DESCRIPTION
**Pull request by suyanNone**
a small change

### CODE REVIEW

**Comment by andrewor14** [comment]
please file JIRA and explain why you're doing this

**Comment by srowen** [comment]
I think that's probably right, as it is a "checkpoint aware and caching" getter for `getDependencies`, but man that is confusing.

**Comment by rxin** [comment]
@suyanNone can you create a JIRA ticket for this?

**Comment by rxin** [comment]
The change itself LGTM.

**Comment by andrewor14** [comment]
Merged into master 1.6.

**Pull request closed without merging**
