### PR TITLE
[SPARK-15618][SQL][MLLIB] Use SparkSession.builder.sparkContext if applicable.

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
## What changes were proposed in this pull request?

This PR changes function `SparkSession.builder.sparkContext(..)` from **private[sql]** into **private[spark]**, and uses it if applicable like the followings.

```
- val spark = SparkSession.builder().config(sc.getConf).getOrCreate()
+ val spark = SparkSession.builder().sparkContext(sc).getOrCreate()
```
## How was this patch tested?

Pass the existing Jenkins tests.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
At this time, Scala 2.10 build is also tested locally.

**Comment by dongjoon-hyun** [comment]
Hi, @andrewor14 .
Could you review this?

**Comment by dongjoon-hyun** [comment]
Hi, @andrewor14 .
Could you review this PR?

**Comment by andrewor14** [comment]
LGTM thanks for doing this. Merging into master 2.0

**Comment by dongjoon-hyun** [comment]
Thank you, @andrewor14 .

**Pull request closed without merging**
