### PR TITLE
[SPARK-25242][SQL] make sql config setting fluent

### PR DESCRIPTION
**Pull request by bomeng**
## What changes were proposed in this pull request?

User can now set conf more easily by doing this:
```
sparkSession.conf.set(...).set(...).unset(...)
```

## How was this patch tested?

More tests for those writings are added to the existing test cases.

### CODE REVIEW

**Comment by bomeng** [comment]
The tests failed due to method signatures' change, but it should not affect the existing test cases and  existing usages.

**Comment by HyukjinKwon** [comment]
?? This doesn't break source compatibility but breaks binary compatibility.

**Comment by maropu** [comment]
oh, yes, this is the issue of binary compatibility...

**Comment by gatorsmile** [comment]
We can think about this API change in 3.0 release. Now, Spark 2.4 release is not allowed to break the binary compatibility.

**Comment by HyukjinKwon** [comment]
Shall we leave this closed for now @bomeng ?

**Pull request closed without merging**
