### PR TITLE
[SPARK-41255] [CONNECT] Rename RemoteSparkSession

### PR DESCRIPTION
**Pull request by grundprinzip**
### What changes were proposed in this pull request?
For better source compatibility, this PR changes the type name of RemoteSparkSession to SparkSession and follows the same builder pattern. The communication with the GRPC endpoint is kept in `client.py` whereas the public facing Spark Session related functionality is implemented in `SparkSession` in `session.py`.

The new class does not support the full behavior of the existing Spark Session. To connect to Spark Connect using the new code use the following example:

```
# Connection to a remote endpoint
SparkSession.builder.remote("sc://endpoint/;config=abc").getOrCreate()
```

or

```
# Local connection to a locally running server
SparkSession.builder.remote().getOrCreate()
```

or

```
SparkSession.builder.conf("spark.connect.location", "sc://endpoint").getOrCreate()
```

### Why are the changes needed?
Compatibility.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
UT

### CODE REVIEW

**Comment by grundprinzip** [comment]
R: @HyukjinKwon @cloud-fan @zhengruifeng

**Comment by amaliujia** [comment]
Per design, Is the RemoteSparkSession as powerful as the SparkSession (e.g. decide to launch cluster, etc.)?

**Comment by grundprinzip** [comment]
> Per design, Is the RemoteSparkSession as powerful as the SparkSession? Is there a limitation?

"as powerful" is a very strong statement. I don't think we have fully defined exactly what is going to be supported. Right now, the goal is to reflect the simplicity of the basics and try to be opinionated when it comes to configurations. The reason the session allows configuration values right now is purely for code compatibility purposes.

**Comment by amaliujia** [comment]
1. It is ok for now. But we need to have a clear documentation or throws errors for the Connect's SparkSession, especially for those bits that does not work as PySpark SparkSession. It is because now the API looks compatible, then users will easy to assume they can do what they usually do with PySpark SparkSession, which is certainly causing confusions.

2. I still think we should keep `client.py`. For the new `session.py`, there are compatible SparSession API. For dealing with gRPC and proto, we keep those in `client.py`. These two logically can be separated.

**Review by HyukjinKwon — APPROVED** [review]

**Review by cloud-fan — APPROVED** [review]

**Comment by grundprinzip** [comment]
I will split the session and client back out again to make it a bit easier to reason about.

**Comment by amaliujia** [comment]
LGTM. Thanks for update the code structure!

**Comment by grundprinzip** [comment]
@cloud-fan @hvanhovell @HyukjinKwon any chance you can merge this so that we can rebase the other changes? Thank you!

**Comment by hvanhovell** [comment]
merging

**Pull request closed without merging**
