### PR TITLE
[MINOR][DOCS] Fix typos in ML doc

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
## What changes were proposed in this pull request?

This PR fixes some typos in ML and MLLib markdown document files.
## How was the this patch tested?

manual tests

### CODE REVIEW

**Comment by rxin** [comment]
@dongjoon-hyun if you are doing a few of these, can you merge them into a single bigger patch?

**Comment by dongjoon-hyun** [comment]
Oh, sure! Then, I will close this and make another PR after reviewing all md files in docs. Is it okay for you?

**Comment by rxin** [comment]
Sounds good.

**Comment by dongjoon-hyun** [comment]
Thank you for your advice, @rxin.

**Pull request closed without merging**
