### PR TITLE
[SQL] [Minor] Refactor SimpleTextRelation to test the data type conversion code paths

### PR DESCRIPTION
**Pull request by liancheng**
In `SimpleTextRelation`, we specified `needsConversion` to `true`, indicating that values produced by this testing relation should be of Scala types, and need to be converted to Catalyst types when necessary. However, we also used `Cast` to convert strings to expected data types. And `Cast` always produces values of Catalyst types, thus no conversion is done at all. This PR makes `SimpleTextRelation` produce Scala values so that data conversion code paths can be properly tested.

### CODE REVIEW

**Comment by liancheng** [comment]
cc @JoshRosen @yhuai

**Comment by JoshRosen** [comment]
Nice, it looks like the test failure reproduces #6400:

```
Lost task 0.0 in stage 405.0 (TID 974, localhost): java.lang.ClassCastException: java.lang.String cannot be cast to org.apache.spark.sql.types.UTF8String  at org.apache.spark.sql.execution.SparkSqlSerializer2$$anonfun$createSerializationFunction$1.apply(SparkSqlSerializer2.scala:319)  at org.apache.spark.sql.execution.SparkSqlSerializer2$$anonfun$createSerializationFunction$1.apply(SparkSqlSerializer2.scala:212)  at org.apache.spark.sql.execution.Serializer2SerializationStream.writeKey(SparkSqlSerializer2.scala:65)  at org.apache.spark.storage.DiskBlockObjectWriter.write(BlockObjectWriter.scala:206)  at org.apache.spark.util.collection.WritablePartitionedIterator$$anon$3.writeNext(WritablePartitionedPairCollection.scala:104)  at org.apache.spark.util.collection.ExternalSorter.spillToPartitionFiles(ExternalSorter.scala:375)  at org.apache.spark.util.collection.ExternalSorter.insertAll(ExternalSorter.scala:208)  at org.apache.spark.shuffle.sort.SortShuffleWriter.write(SortShuffleWriter.scala:62)  at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:70)  at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)  at org.apache.spark.scheduler.Task.run(Task.scala:70)  at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)  at java.lang.Thread.run(Thread.java:745)  Driver stacktrace: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 405.0 failed 1 times, most recent failure: Lost task 0.0 in stage 405.0 (TID 974, localhost): java.lang.ClassCastException: java.lang.String cannot be cast to org.apache.spark.sql.types.UTF8String  at org.apache.spark.sql.execution.SparkSqlSerializer2$$anonfun$createSerializationFunction$1.apply(SparkSqlSerializer2.scala:319)  at org.apache.spark.sql.execution.SparkSqlSerializer2$$anonfun$createSerializationFunction$1.apply(SparkSqlSerializer2.scala:212)  at org.apache.spark.sql.execution.Serializer2SerializationStream.writeKey(SparkSqlSerializer2.scala:65)  at org.apache.spark.storage.DiskBlockObjectWriter.write(BlockObjectWriter.scala:206)  at org.apache.spark.util.collection.WritablePartitionedIterator$$anon$3.writeNext(WritablePartitionedPairCollection.scala:104)  at org.apache.spark.util.collection.ExternalSorter.spillToPartitionFiles(ExternalSorter.scala:375)  at org.apache.spark.util.collection.ExternalSorter.insertAll(ExternalSorter.scala:208)  at org.apache.spark.shuffle.sort.SortShuffleWriter.write(SortShuffleWriter.scala:62)  at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:70)  at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)  at org.apache.spark.scheduler.Task.run(Task.scala:70)  at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)  at java.lang.Thread.run(Thread.java:745)  Driver stacktrace:  at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1266)  at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1257)  at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1256)  at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)  at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1256)  at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:730)  at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:730)  at scala.Option.foreach(Option.scala:236)  at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:730)  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1450)  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1411)  at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)            
```

How do you want to handle merging this and #6400?  I think that #6400 needs to go first so that we don't commit broken code.  Should I rebase my branch to include this commit and remove the regression test that I added?  Or should we leave both tests in place?

**Comment by yhuai** [comment]
@JoshRosen I think we can add this change to #6400 and also keep your regression test.

**Comment by JoshRosen** [comment]
@liancheng's commit message is really nice, so I'll quote it in my PR so that we don't lose it.

**Comment by liancheng** [comment]
Closing this as it's already merged into #6400.

**Pull request closed without merging**
