### PR TITLE
[SPARK-14087][PySpark][ML] [WIP] PySpark JavaModel Param ownership error

### PR DESCRIPTION
**Pull request by BryanCutler**
When a PySpark model is created after fitting data, its UID is initialized to the parent estimator's value. Before this assignment, any params defined in the model are copied from the object to the class in Params._copy_params() and assigned a different parent UID. This causes PySpark to think the params are not owned by the model and can lead to a ValueError raised from Params._shouldOwn

**\* Still thinking of a possible test for this

### CODE REVIEW

**Comment by jkbradley** [comment]
Early comment: Could you please add a unit test, and make sure the test fails before your patch?

**Comment by jkbradley** [comment]
I feel like JavaModel's init method should get a UID if one does not yet exist and pass that it its parent classes' init methods as needed.  Eventually, Python users might construct models by hand and want to specify UIDs, and this setup should support that better.

**Comment by BryanCutler** [comment]
> How did you uncover this issue in the first place? The code you used then should be usable to create a unit test for this.

I tried to explain in the JIRA, but I probably should have done so here also..
For SPARK-13967, I was adding a binary flag `Param` to the `CountVectorizerModel` and when the model is created from the estimator, this problem comes up and an exception is raised.

As far as I can tell, this is only a problem when a `Param` is defined in the PySpark model only and it is created by an JavaWrapper estimator.  I don't see that happening anywhere currently, so I haven't come up with a unit test.  I could maybe include a temporary version of the `CountVectorizerModel` that I was working on, just for testing purposes until I do a PR for SPARK-13967, would that be ok?

**Comment by jkbradley** [comment]
Ohhh, I see.  I didn't read it carefully enough.  I think the real issue is that CountVectorizer needs the Param as well.  We need all Estimators to contain the Model Params so that users can configure the whole Pipeline/Estimator before running fit. I'll create a JIRA for that.

**Comment by BryanCutler** [comment]
Hmmm, I'm not sure if that would completely solve this.. The scala version of `CountVectorizerModel` allows to construct it from a "vocab" set, instead of fitting the estimator.  So when I tried that on the Python side, I needed to define an "inputCol" param.  After adding the `HasInputCol` mixin to the model class, this ownership problem happened.

I think there still needs to be some way to override the default `JavaModel` UID before calling the parent `__init__()`

**Comment by jkbradley** [comment]
I see.  It sounds like my suggestion would let us add the binary toggle param.  However, to add a constructor for CountVectorizerModel taking a vocab, we would need to address this issue.  I agree we should support taking a vocab, but can we separate it out as a future task?

**Comment by BryanCutler** [comment]
Yeah, with your suggestion I could proceed with SPARK-13967 and add the binary toggle to PySpark CountVectorizer.  I'll just need to fix up a few things and change the tests a little.

**Comment by jkbradley** [comment]
OK thanks!

**Comment by BryanCutler** [comment]
Do you mind if I go ahead and open a JIRA to construct `CountVectorizerModel` from vocab in PySpark?

**Comment by jkbradley** [comment]
Please do, thanks

**Comment by BryanCutler** [comment]
closing, no longer an issue now that resetUid() is called

**Pull request closed without merging**
