### PR TITLE
[SPARK-11872] Prevent the call to SparkContext#stop() in the listener bus's thread

### PR DESCRIPTION
**Pull request by tedyu**
This is continuation of SPARK-11761

Andrew suggested adding this protection. See tail of https://github.com/apache/spark/pull/9741

### CODE REVIEW

**Comment by tedyu** [comment]
@andrewor14 @zsxwing 
Kindly review

**Comment by zsxwing** [comment]
@tedyu could you add a unit test? Just to avoid someone breaking it in future.

**Comment by tedyu** [comment]
Should I add test in StreamingListenerSuite.scala (stopping SparkContext instead of stopping StreamingContext) ?
Which notification should be overridden ?

Thanks

**Comment by zsxwing** [comment]
You can add the test to SparkListenerSuite in core

**Comment by zsxwing** [comment]
retest this please

**Comment by tedyu** [comment]
```
[error] Failed: Total 378, Failed 1, Errors 0, Passed 377, Ignored 2
[error] Failed tests:
[error] 	org.apache.spark.streaming.CheckpointSuite
[info] ExecutorClassLoaderSuite:
[info] - child first (4 seconds, 178 milliseconds)
[info] - parent first (49 milliseconds)
[info] - child first can fall back (47 milliseconds)
[info] - child first can fail (44 milliseconds)
[info] - failing to fetch classes from HTTP server should not leak resources (SPARK-6209) *** FAILED *** (1 second, 886 milliseconds)
[info]   java.lang.ClassNotFoundException: ReplFakeClass2
[info]   at org.apache.spark.repl.ExecutorClassLoader.findClass(ExecutorClassLoader.scala:68)
```
I don't think the above failures were related to my change

**Comment by tedyu** [comment]
Manually ran org.apache.spark.streaming.CheckpointSuite (with this change) which passed.

**Comment by zsxwing** [comment]
LGTM

**Comment by tedyu** [comment]
@zsxwing @andrewor14 
Is there anything I need to do ?

**Comment by zsxwing** [comment]
Merged to master and 1.6. Thanks!

**Pull request closed without merging**
