### PR TITLE
[SPARK-33022][CORE] Partition length is wrong after merge partition segments in BypassMergeSortShuffleWriter

### PR DESCRIPTION
**Pull request by duanmeng**
The segment file may be empty even after writer committing caused by disk/kernel in heavy load cluster. Compare segment length with copied length to guard it.

A data file might be empty even after  DiskBlockObjectWriter committing it in BypassMergeSortShuffleWriter, returned wrong lengths in writePartitionedFile used by MapStatus, and then cause data lost.

This is related to disk/kernel but we can avoid it in spark without any performance loss. We can compare partitionWriterSegments[i].length with the length[i] after Utils.copyStream.

I added some logs and reproduce the issue,

The log when this issue happened
```
20/09/28 00:42:44 INFO sort.BypassMergeSortShuffleWriter: partitionWriterSegments[0]: (name=temp_shuffle_38244ef5-8e97-4428-97b8-feffc16fc9f7, offset=0, length=1462) 
20/09/28 00:42:46 INFO sort.BypassMergeSortShuffleWriter: File length: 0 
20/09/28 00:42:46 INFO sort.BypassMergeSortShuffleWriter: Copied stream length: 0
```
 

The peer log when this issue didn't happen
```
20/09/28 10:11:45 INFO sort.BypassMergeSortShuffleWriter: partitionWriterSegments[0]: (name=temp_shuffle_f6937469-39fd-4576-b40e-69f4276cc8e4, offset=0, length=1462)
20/09/28 10:11:45 INFO sort.BypassMergeSortShuffleWriter: File length: 1462
20/09/28 10:11:45 INFO sort.BypassMergeSortShuffleWriter: Copied stream length: 1462
```

### CODE REVIEW

**Comment by Ngone51** [comment]
Hi @duanmeng  Could you elaborate more on how to reproduce the issue?

**Comment by duanmeng** [comment]
> Hi @duanmeng Could you elaborate more on how to reproduce the issue?

**Comment by duanmeng** [comment]
> > Hi @duanmeng Could you elaborate more on how to reproduce the issue?

Sorry that I accidently close it, I will repoen it.

This issue is hard to reproduce for it should be a bug of to the cluster's disk / kernel, which make the shuffle data file empty after records committing. But we defend it in spark, should we change it from **bug** to **improvement**?

**Comment by Ngone51** [comment]
It should be a bug. I thought you were able to reproduce it because you said "I added some logs and reproduce the issue." I may misunderstand it.

**Comment by duanmeng** [comment]
> It should be a bug. I thought you were able to reproduce it because you said "I added some logs and reproduce the issue." I may misunderstand it.

We have have two identical spark app in two clusters and compare results (it's a critical task so we have to double check its result).  There might be diffs caused by data lost every 3-4 weeks. I add logs in the bypass shuffle writer and caught this issue when it reproduced.

However its root cause should be the disk or kernel in our cluster (disk pressue is very high), which happens occasionlly. `spark.shuffle.sync` could be used to force sync writes but it have performance impact, so I suggest to add length checking.

**Comment by jiangxb1987** [comment]
> This is related to disk/kernel but we can avoid it in spark without any performance loss.

Do you have any reference regarding the kernel issue？In other words, do you have any evidence to support the issue is caused by a kernel issue?

**Comment by duanmeng** [comment]
> > This is related to disk/kernel but we can avoid it in spark without any performance loss.
> 
> Do you have any reference regarding the kernel issue？In other words, do you have any evidence to support the issue is caused by a kernel issue?

Unfortunately I don't have directly evidence since it's rarely to happen and the kernel is a inhouse kernel. I can only infer from the log that the file exist and its length is 1462 but read 0 bytes from it, maybe the data is still in the block layer when the file was read, so IMHO we can defend it in framework level (eg, spark) since the actual length is count after writing records and commiting.

**Comment by LuciferYang** [comment]
Disk load is unlikely to cause this problem. Is it possible caused by disk failure, is there any valuable information in `dmesg` or `/var/log/message`

**Comment by mridulm** [comment]
In theory, with disk, driver or kernal bugs, any write can silently have issues.
Validating every write from spark is not practical (what about data writes, network writes, etc).

Did you find a reference to the underlying bug in linux @duanmeng ? Is there any mitigating factors, env where it is more commonly triggered, how to reproduce it ?

**Comment by duanmeng** [comment]
> In theory, with disk, driver or kernal bugs, any write can silently have issues.
Validating every write from spark is not always practical.

Yes you're right, so I want to reuse the segment's length to do a lightweight check, which has been naturally done by record the count of byte when writing in both [LocalDiskShuffleMapOutputWriter used by SortShuffleWriter](https://github.com/apache/spark/blob/master/core/src/main/java/org/apache/spark/shuffle/sort/io/LocalDiskShuffleMapOutputWriter.java#L244) and [ShuffleExternalSorter used by UnsafeShuffleWriter](https://github.com/apache/spark/blob/master/core/src/main/java/org/apache/spark/shuffle/sort/ShuffleExternalSorter.java#L204). 

>Is there any mitigating factors, env where it is more commonly triggered, how to reproduce it ?

We once had a issue caused by a disk check script (use smartctl) that corrupt the data. However the issue described in this PR should be related to other env factor and is rarely reproduced (Honestly I don't know to reproduced or trigger), and disappeared after I applied this patch.

Thanks @mridulm .

**Comment by mridulm** [comment]
Sorry for the delay in getting back to this @duanmeng.
+CC @otterc since you had looked at corruption issues recently.

**Pull request closed without merging**
