### PR TITLE
[SPARK-38393][SQL] Clean up deprecated usage of `GenSeq/GenMap`

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
`GenSeq/GenMap`  is identified as `@deprecated` since Scala 2.13.0 and `Gen* collection types have been removed`.  

On the other hand, for Scala 2.12：

-  `trait Map[K, +V] extends Iterable[(K, V)] with GenMap[K, V] with MapLike[K, V, Map[K, V]]`
- `trait Seq[+A] extends PartialFunction[Int, A] with Iterable[A] with GenSeq[A] with GenericTraversableTemplate[A, Seq] with SeqLike[A, Seq[A]]`

It is not necessary to declare as `GenSeq/GenMap`, so this pr change to use `Map/Seq` to clean up deprecated usage.

### Why are the changes needed?
Clean up deprecated usage.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass GA

### CODE REVIEW

**Comment by LuciferYang** [comment]
cc @srowen

**Review by martin-g — APPROVED** [review]

**Comment by srowen** [comment]
Looks OK, I can't think of a reason this specific type is needed

**Comment by srowen** [comment]
Merged to master

**Comment by LuciferYang** [comment]
thanks all

**Pull request closed without merging**
