### PR TITLE
[SPARK-40210][PYTHON][FOLLOW-UP][TEST] Speed up new tests using one action instead of many

### PR DESCRIPTION
**Pull request by khalidmammadov**
### What changes were proposed in this pull request?
This is follow up PR for https://github.com/apache/spark/pull/37748 to improve and speed tests as suggested by @zero323

### Why are the changes needed?

Improve test cases

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Existing unit tests

### CODE REVIEW

**Review by zero323 — APPROVED** [review]

**Comment by zero323** [comment]
cc @zhengruifeng

**Comment by zero323** [comment]
@khalidmammadov Could you adjust the title to `[SPARK-40210][PYTHON][FOLLOW-UP][TEST] Speed up new tests using one action instead of many`? Thanks.

**Comment by khalidmammadov** [comment]
> @khalidmammadov Could you adjust the title to `[SPARK-40210][PYTHON][FOLLOW-UP][TEST] Speed up new tests using one action instead of many`? Thanks.

Done

**Comment by zero323** [comment]
Merged to master.

**Comment by zhengruifeng** [comment]
LGTM2

**Pull request closed without merging**
