### PR TITLE
[Minor][Core] Fix display wrong free memory size in the log

### PR DESCRIPTION
**Pull request by jerryshao**
## What changes were proposed in this pull request?

Free memory size displayed in the log is wrong (used memory), fix to make it correct.
## How was this patch tested?

N/A

### CODE REVIEW

**Comment by jerryshao** [comment]
Jenkins, retest this please.

**Comment by srowen** [comment]
Certainly looks more correct

**Comment by jerryshao** [comment]
Any further comments @srowen , from my understanding it worth fixing.

**Comment by srowen** [comment]
Merged to master/2.0

**Comment by jerryshao** [comment]
Thanks a lot @srowen .

**Comment by lw-lin** [comment]
hi @jerryshao, let's also back-port this into 1.6.x ([MemoryStore.scala#L395](https://github.com/apache/spark/blob/branch-1.6/core/src/main/scala/org/apache/spark/storage/MemoryStore.scala#L395)) maybe?

**Comment by jerryshao** [comment]
OK, let me do it.

**Pull request closed without merging**
