### PR TITLE
[MINOR] Remove redundant return

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
Remove redundant return in scala code.

### Why are the changes needed?
Syntactic simplification.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Are they all in the codebase?

**Comment by panbingkun** [comment]
> Are they all in the codebase?

Yes, I inspect all scala code in spark by 
> Tool: "/Applications/IntelliJ IDEA CE.app/Contents/bin/inspect.sh"
> Rule: Syntactic simplification - redundant return

**Review by HyukjinKwon — APPROVED** [review]

**Review by LuciferYang — APPROVED** [review]
LGTM +1

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by panbingkun** [comment]
> Merged to master.

I am very sorrry, I miss some scala code with the same problem. @HyukjinKwon 
Followup PR:

**Pull request closed without merging**
