### PR TITLE
[SPARK-11681][Streaming] Correctly update state timestamp even when state is not updated

### PR DESCRIPTION
**Pull request by tdas**
Bug: Timestamp is not updated if there is data but the corresponding state is not updated. This is wrong, and timeout is defined as "no data for a while", not "not state update for a while".

Fix: Update timestamp when timestamp when timeout is specified, otherwise no need.
Also refactored the code for better testability and added unit tests.

### CODE REVIEW

**Comment by tdas** [comment]
@zsxwing Could you please take a look at this PR

**Comment by zsxwing** [comment]
retest this please

**Comment by zsxwing** [comment]
LGTM

**Comment by tdas** [comment]
Thanks for the review @zsxwing, merging this to master and 1.6

**Comment by tdas** [comment]
Oops there are conflicts. Fixing them and then merging.

**Pull request closed without merging**
