### PR TITLE
[SPARK-43331][CONNECT][FOLLOWUP] Fix typo in test

### PR DESCRIPTION
**Pull request by juliuszsompolski**
### What changes were proposed in this pull request?

Fix typo in test - should check q2, not q1 twice.

### Why are the changes needed?

Fix typo.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

CI

### CODE REVIEW

**Comment by juliuszsompolski** [comment]
@hvanhovell @LuciferYang

**Review by LuciferYang — APPROVED** [review]

**Review by grundprinzip — APPROVED** [review]

**Review by hvanhovell — APPROVED** [review]
LGTM

**Review by Hisoka-X — APPROVED** [review]

**Comment by juliuszsompolski** [comment]
Hold with merging, I may make some more small changes to print better errors here, as I try to reproduce and debug https://github.com/apache/spark/pull/41005#discussion_r1200551487

**Review by dongjoon-hyun — COMMENTED** [review]
Is the PR ready, @juliuszsompolski ?

**Review by HyukjinKwon — APPROVED** [review]

**Comment by juliuszsompolski** [comment]
@dongjoon-hyun yes, it's ready as is.
I was trying to debug https://github.com/apache/spark/pull/41005#discussion_r1200924867 and maybe do something to fix it, but I'm stumped there. It seems to be some manifestation of https://issues.apache.org/jira/browse/SPARK-43227 and may need a separate investigation, and is orthogonal of query interrupt.
It also isn't failing in CI, so seems specific to some environment...

**Review by dongjoon-hyun — APPROVED** [review]
Thanks. +1, LGTM. Merged to master.

**Comment by LuciferYang** [comment]
> It also isn't failing in CI, so seems specific to some environment...

GA passed because it uses sbt for testing, and the connect server fork by sbt will with classpath of connect client, which will masks some issues

**Comment by juliuszsompolski** [comment]
> GA passed because it uses sbt for testing, and the connect server fork by sbt will with classpath of connect client, which will masks some issues

I see.
But it's still interesting that the same test copied to `UserDefinedFunctionE2ETestSuite`, which should have the same classpath, works...

**Comment by dongjoon-hyun** [comment]
Ur? Do you mean that this PR causes failures?

**Comment by dongjoon-hyun** [comment]
For the Maven failure issue, shall we file a dedicated JIRA issue, @LuciferYang ?
- https://github.com/apache/spark/pull/41005#discussion_r1200551487

**Comment by juliuszsompolski** [comment]
I will create a JIRA issue.

**Comment by juliuszsompolski** [comment]
Created https://issues.apache.org/jira/browse/SPARK-43744

**Comment by LuciferYang** [comment]
> Created https://issues.apache.org/jira/browse/SPARK-43744

Actually I have created https://issues.apache.org/jira/browse/SPARK-43648 yesterday :)

**Comment by dongjoon-hyun** [comment]
Thanks. Then, let's track that in SPARK-43648 instead of here.
And, sorry again for missing your comment, @LuciferYang .

**Comment by LuciferYang** [comment]
@dongjoon-hyun No problem :)

**Pull request closed without merging**
