### PR TITLE
[SPARK-33480][SQL][FOLLOWUP] do not expose user data in error message

### PR DESCRIPTION
**Pull request by cloud-fan**
### What changes were proposed in this pull request?

This is a followup of https://github.com/apache/spark/pull/30412. This PR updates the error message of char/varchar table insertion length check, to not expose user data.

### Why are the changes needed?

This is risky to expose user data in the error message, especially the string data, as it may contain sensitive data.

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

updated tests

### CODE REVIEW

**Comment by cloud-fan** [comment]
cc @maropu @dongjoon-hyun @HyukjinKwon

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. (Pending CIs)

**Comment by dongjoon-hyun** [comment]
Merged to master/3.1.

**Comment by maropu** [comment]
late lgtm

**Comment by HyukjinKwon** [comment]
LGTM, nice.

**Pull request closed without merging**
