### PR TITLE
[SPARK-27493][BUILD] Upgrade ASM to 7.1

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
## What changes were proposed in this pull request?

[SPARK-25946](https://issues.apache.org/jira/browse/SPARK-25946) upgraded ASM to 7.0 to support JDK11. This PR aims to update ASM to 7.1 to bring the bug fixes.
- https://asm.ow2.io/versions.html
- https://issues.apache.org/jira/browse/XBEAN-316

## How was this patch tested?

Pass the Jenkins.

### CODE REVIEW

**Review by srowen — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by dongjoon-hyun** [comment]
Thank you for review and approval, @srowen and @HyukjinKwon !

**Comment by srowen** [comment]
PS @dongjoon-hyun should the ASM dependency have been updated in the SBT build here? it still has...
```
libraryDependencies += "org.ow2.asm"  % "asm" % "7.0"

libraryDependencies += "org.ow2.asm"  % "asm-commons" % "7.0"
```

**Comment by dongjoon-hyun** [comment]
Oops. Thank you, @srowen . I'll make a follow-up PR.

**Pull request closed without merging**
