### PR TITLE
[SPARK-9737][YARN] Add the suggested configuration when required executor memory is above the max threshold of this cluster on YARN mode

### PR DESCRIPTION
**Pull request by watermen**

### CODE REVIEW

**Comment by srowen** [comment]
LGTM CC @sryza

**Comment by watermen** [comment]
retest this please

**Comment by watermen** [comment]
retest this please

**Comment by watermen** [comment]
retest this please

**Comment by watermen** [comment]
@srowen Is Jenkins wrong?

**Comment by watermen** [comment]
retest this please

**Comment by watermen** [comment]
retest this please

**Comment by rxin** [comment]
@srowen any reason you don't merge this nicer error message into branch-1.5?

**Comment by srowen** [comment]
Oh, just because it is a not a bug fix? Being in the release window. I suppose it is really docs. No problem to back port

**Pull request closed without merging**
