### PR TITLE
[SPARK-49384][BUILD] Upgrade rocksdbjni to 9.5.2

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to upgrade rocksdbjni from `9.2.1` to `9.5.2`.

### Why are the changes needed?
The full release notes as follows:
https://github.com/facebook/rocksdb/releases/tag/v9.5.2
https://github.com/facebook/rocksdb/releases/tag/v9.4.0
https://github.com/facebook/rocksdb/releases/tag/v9.3.1

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by panbingkun** [comment]
Recently, there has been an upgrade related to `rocksdbjni`. This PR will be held for now. 
Let's test it first to verify its stability and performance

**Comment by LuciferYang** [comment]
Has there been any new progress on this one

**Comment by panbingkun** [comment]
> Has there been any new progress on this one

Let's wait a little longer, I think version 9.5 should be released soon
image
Thanks.

**Comment by panbingkun** [comment]
Let me run the benchmark: StateStoreBasicOperationsBenchmark
JDK17: 
JDK21:

**Comment by panbingkun** [comment]
cc @LuciferYang @dongjoon-hyun

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @panbingkun .
Merged to master.

**Pull request closed without merging**
