### PR TITLE
Revert [SPARK-19355][SPARK-25352]

### PR DESCRIPTION
**Pull request by viirya**
## What changes were proposed in this pull request?

This goes to revert sequential PRs based on some discussion and comments at https://github.com/apache/spark/pull/16677#issuecomment-422650759.

#22344
#22330
#22239
#16677

## How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by viirya** [comment]
cc @cloud-fan

**Comment by cloud-fan** [comment]
LGTM, thanks!

**Comment by dilipbiswal** [comment]
retest this please

**Comment by cloud-fan** [comment]
thanks, merging to master/2.4!

**Pull request closed without merging**
