### PR TITLE
[SPARK-15576] Add back hive tests blacklisted by SPARK-15539

### PR DESCRIPTION
**Pull request by techaddict**
## What changes were proposed in this pull request?

Add back hive tests blacklisted by SPARK-15539 except for `date_1` it requires timestamp and date functions
## How was this patch tested?

ran HiveCompatibilitySuite

### CODE REVIEW

**Comment by andrewor14** [comment]
@techaddict you've misunderstood the JIRA. I removed them from `HiveCompatibilitySuite` on purpose because they don't pass there. Instead you should add them back to `HiveQuerySuite` and fix the usages of `DROP TABLE` there.

**Comment by andrewor14** [comment]
@techaddict please close this PR as this is not the right fix.

**Comment by techaddict** [comment]
@andrewor14 I've made the changes, can you take a look now ?

**Comment by techaddict** [comment]
@andrewor14 ping.

**Pull request closed without merging**
