### PR TITLE
[SPARK-19902][SQL] Add optimization rule to simplify expressions comprised of Add, Subtract, Multiply and Divide

### PR DESCRIPTION
**Pull request by viirya**
## What changes were proposed in this pull request?

An expression comprised of `Add` and `Subtract`, and combination of `Multiply` and `Divide`, can be simplified further, e.g., `a + b - b` to `a`.

This patch adds an optimization rule to simplify those expressions.

## How was this patch tested?

Jenkins tests.

Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Comment by viirya** [comment]
cc @cloud-fan @hvanhovell

**Comment by cloud-fan** [comment]
> like `a + b - b` and `a` which are semantically equal

shouldn't we put it in optimizer?

**Comment by viirya** [comment]
> shouldn't we put it in optimizer?
Yes, I think we should. The new rules can be used for optimization too.

**Comment by viirya** [comment]
@cloud-fan I would like to defer the optimization part to another PR, if possible.

**Comment by viirya** [comment]
ping @cloud-fan Except for the optimization integration, do you have more comments on this change? Thanks.

**Comment by cloud-fan** [comment]
not "integration", but "move". I think this logic belongs to optimizer instead of canonicalizer

**Comment by viirya** [comment]
hmm, so you don't think canonicalizer should use this?

**Comment by viirya** [comment]
anyway, I will move it to optimizer in next update.

**Comment by viirya** [comment]
retest this please.

**Comment by viirya** [comment]
@cloud-fan I've moved this to the optimizer, please take a look. Thanks.

**Comment by viirya** [comment]
ping @cloud-fan @hvanhovell Can you help review this? Thanks.

**Comment by viirya** [comment]
@cloud-fan Please let me know if you have time to review this. Thanks.

**Comment by viirya** [comment]
ping @cloud-fan @hvanhovell

**Comment by viirya** [comment]
ping @cloud-fan Can you take a look of this? If you don't think this is appropriate direction, please let me know.

**Pull request closed without merging**
