### PR TITLE
[SPARK-24704][WebUI] Fix the order of stages in the DAG graph

### PR DESCRIPTION
**Pull request by stanzhai**
## What changes were proposed in this pull request?

Before:

wx20180630-155537

After:

wx20180630-155604

## How was this patch tested?

Manual tests.

### CODE REVIEW

**Review by felixcheung — APPROVED** [review]
ok looks reasonable?

**Comment by felixcheung** [comment]
ok to test

**Review by jiangxb1987 — APPROVED** [review]
LGTM

**Comment by hvanhovell** [comment]
Merging to master. Thanks!

**Pull request closed without merging**
