### PR TITLE
[SPARK-13643][SQL] Implement SparkSession

### PR DESCRIPTION
**Pull request by andrewor14**
## What changes were proposed in this pull request?

After removing most of `HiveContext` in 8fc267ab3322e46db81e725a5cb1adb5a71b2b4d we can now move existing functionality in `SQLContext` to `SparkSession`. As of this PR `SQLContext` becomes a simple wrapper that has a `SparkSession` and delegates all functionality to it.
## How was this patch tested?

Jenkins.

### CODE REVIEW

**Comment by andrewor14** [comment]
@rxin @yhuai

**Comment by yhuai** [comment]
Thank you! This one looks good. Seems MIMA is complaining the following.
```
[error]  * method getSchema(java.lang.Class)scala.collection.Seq in class org.apache.spark.sql.SQLContext does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("org.apache.spark.sql.SQLContext.getSchema")
```

**Comment by andrewor14** [comment]
retest this please

**Comment by yhuai** [comment]
LGTM. Thanks. Merging to master.

**Pull request closed without merging**
