### PR TITLE
Backport [SPARK-11327] [MESOS] Dispatcher does not respect all args f…

### PR DESCRIPTION
**Pull request by jayv**
Backport for https://github.com/apache/spark/pull/10370 @andrewor14

### CODE REVIEW

**Comment by andrewor14** [comment]
add to whitelist

**Comment by andrewor14** [comment]
Thanks, this looks good.

**Comment by dragos** [comment]
Thanks @jayv for the backport!

**Comment by andrewor14** [comment]
Merged into 1.6 thanks.

**Comment by andrewor14** [comment]
can you close this PR now

**Pull request closed without merging**
