### PR TITLE
[SPARK-8510] [CORE] [PYSPARK] NumPy matrices as values in sequence files

### PR DESCRIPTION
**Pull request by paberline**
Added support for storing NumPy arrays and matrices as value elements of Sequence Files.

Each value element is a discrete matrix or array.  This is useful where you have many matrices that you don't want to join into a single Spark DataFrame to store in a Parquet file.

### CODE REVIEW

**Comment by paberline-rms** [comment]
JIRA: https://issues.apache.org/jira/browse/SPARK-8510

**Comment by paberline** [comment]
JIRA: https://issues.apache.org/jira/browse/SPARK-8510

**Comment by JoshRosen** [comment]
@mengxr @jkbradley, could one of you help to triage to see if we should add this feature? My layperson's gut instinct says that it might be too narrow to want to put into Spark, but I'd like your opinion.

**Comment by holdenk** [comment]
I think its safe to say that this isn't something that there is committer interest on bringing into Spark. Especially now that we can use DataFrames to write out to other formats from Python its probably not as useful. One last double check with @mengxr @jkbradley & @davies but otherwise maybe it would be good to close?

**Comment by paberline** [comment]
Hi @holdenk - thanks for taking the time to look at this. I understand this PR 
might be too esoteric for Spark core. I will close it once @mengxr 
@jkbradley and @davies confirm.

However, your comments yesterday on the the DataSet API JIRA issue are 
timely: https://issues.apache.org/jira/browse/SPARK-12776?focusedCommentId=15557224&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15557224

If the DataSet API was implemented in PySpark, then, as per the Scala API,  
DataFrame = Dataset[Row]. Then I think this would enable me to simply convert each 
matrix to a DataFrame then save the Dataset as parquet or sequence file. Is my understanding correct?

**Comment by HyukjinKwon** [comment]
@paberline, can we then close this for now? I guess it is a soft-yes for closing.

**Comment by paberline** [comment]
Closing as requested due to this feature being too narrow a use case for core Spark.

**Comment by HyukjinKwon** [comment]
Thank you @paberline.

**Pull request closed without merging**
