### PR TITLE
[SPARK-47244][CONNECT] `SparkConnectPlanner` make internal functions private

### PR DESCRIPTION
**Pull request by zhengruifeng**
### What changes were proposed in this pull request?
`SparkConnectPlanner` make internal functions private

### Why are the changes needed?
they are internal functions, should not be exposed to users

### Does this PR introduce _any_ user-facing change?
no

### How was this patch tested?
ci

### Was this patch authored or co-authored using generative AI tooling?
no

### CODE REVIEW

**Review by amaliujia — APPROVED** [review]

**Review by xinrong-meng — APPROVED** [review]

**Comment by xinrong-meng** [comment]
LGTM, thank you!

**Comment by xinrong-meng** [comment]
Just curious do we consider such changes as "user-facing" considering users may import those methods in their existing code?

**Comment by HyukjinKwon** [comment]
This class isn't actually an API so it's more just for us to prevent making some mistakes :-).

Let me just merge it in - it's just a cleanup.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
