### PR TITLE
[MINOR][DOCS] Remove PySpark doc build warnings

### PR DESCRIPTION
**Pull request by HyukjinKwon**
### What changes were proposed in this pull request?

This PR fixes a various documentation build warnings in PySpark documentation

### Why are the changes needed?

To render the docs better.

### Does this PR introduce _any_ user-facing change?

Yes, it changes the documentation to be prettier. Pretty minor though.

### How was this patch tested?

I manually tested it by building the PySpark documentation

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @xinrong-databricks and @zero323 FYI.

@itholic BTW, I remember we talked about warnings in Sphinx build before. I think it should fail for these warnings but not sure why it doesn't. Would you mind taking a look for this one, and making it failed if there are warnings detected during the build?

**Comment by itholic** [comment]
@HyukjinKwon sure, let me take a look

**Comment by itholic** [comment]
Just opened a PR at https://github.com/apache/spark/pull/36058 to make warning to be failed.

So, let me cherry-pick this fix to the opened PR after merging.

**Review by itholic — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master, branch-3.3, and branch-3.2.

**Pull request closed without merging**
