### PR TITLE
[SPARK-23122][PYSPARK][FOLLOWUP] Replace registerTempTable by createOrReplaceTempView

### PR DESCRIPTION
**Pull request by gatorsmile**
## What changes were proposed in this pull request?
Replace `registerTempTable` by `createOrReplaceTempView`. 

## How was this patch tested?
N/A

### CODE REVIEW

**Comment by ueshin** [comment]
Seems like `JavaUDAFSuite.java` still uses `registerTempTable`. Should we replace it as well?

**Comment by HyukjinKwon** [comment]
Let's make another JIRA ...

**Comment by ueshin** [comment]
Sure, I'll take it.

**Comment by HyukjinKwon** [comment]
Oh, no. I mean another JIRA for this PR. Sorry for confusion.

**Comment by ueshin** [comment]
I see, then, I'll leave it to @gatorsmile for now.

**Comment by HyukjinKwon** [comment]
Thanks, @ueshin.

**Review by felixcheung — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master and branch-2.3.

**Pull request closed without merging**
