### PR TITLE
[SPARK-42334][CONNECT][BUILD] Make sure connect client assembly and sql package is built before running client tests - SBT

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
`build/sbt clean "connect-client-jvm/test"` will fail after SPARK-42172 merged, so this pr make sure sbt assembles the connect client assembly jar and sbt package the sql jar before we run `CompatibilitySuite` of client module.

### Why are the changes needed?
Similar as SPARK-42284, it makes it easier to develop and test the JVM client for Spark Connect.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Manually tested.

```
build/sbt clean "connect-client-jvm/test"
```

**Before**

```
[info] - compatibility MiMa tests *** FAILED *** (34 milliseconds)
[info]   java.lang.AssertionError: assertion failed: Failed to find the jar inside folder: /Users/yangjie01/SourceCode/git/spark-mine-sbt/connector/connect/client/jvm/target
[info]   at scala.Predef$.assert(Predef.scala:223)
[info]   at org.apache.spark.sql.connect.client.util.IntegrationTestUtils$.findJar(IntegrationTestUtils.scala:67)
[info]   at org.apache.spark.sql.connect.client.CompatibilitySuite.clientJar$lzycompute(CompatibilitySuite.scala:57)
[info]   at org.apache.spark.sql.connect.client.CompatibilitySuite.clientJar(CompatibilitySuite.scala:53)
[info]   at org.apache.spark.sql.connect.client.CompatibilitySuite.$anonfun$new$1(CompatibilitySuite.scala:69)
....
[info] *** 2 TESTS FAILED ***
[error] Failed tests:
[error] 	org.apache.spark.sql.connect.client.CompatibilitySuite
[error] (connect-client-jvm / Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 196 s (03:16), completed 2023-2-3 17:20:40
```

**After**

```
[info] Run completed in 20 seconds, 652 milliseconds.
[info] Total number of tests run: 31
[info] Suites: completed 6, aborted 0
[info] Tests: succeeded 31, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[success] Total time: 230 s (03:50), completed 2023-2-3 17:35:37
```

### CODE REVIEW

**Comment by LuciferYang** [comment]
cc @hvanhovell

**Comment by LuciferYang** [comment]
also cc @HyukjinKwon @dongjoon-hyun

**Review by hvanhovell — APPROVED** [review]
LGTM - merging

**Review by HyukjinKwon — COMMENTED** [review]
LGTM2

**Pull request closed without merging**
