### PR TITLE
SPARK-11382 Replace example code in mllib-decision-tree.md using incl…

### PR DESCRIPTION
**Pull request by gliptak**
…ude_example

### CODE REVIEW

**Comment by mengxr** [comment]
@yinxusen Could you help review?

**Comment by gliptak** [comment]
@mengxr Could you trigger a build (including site?)? Thanks

**Comment by yinxusen** [comment]
@mengxr Yes I will review it.

**Comment by yinxusen** [comment]
@gliptak Why the code changes do not match with the title? I think the SPARK-11382 should fix mllib-decision-tree.md and mllib-ensembles.md.

**Comment by gliptak** [comment]
I was planning to split into two commits (although I'm open to work the other file in this same commit). Thanks

**Comment by yinxusen** [comment]
@gliptak  I mean, this JIRA issue aiming to modify decision-tree.md and mllib-ensembles.md, but your pull request changes mllib-frequent-pattern-mining.md.

**Comment by gliptak** [comment]
Can I add new JIRA covering mllib-ensembles.md?

**Comment by yinxusen** [comment]
Yes you can.

**Comment by gliptak** [comment]
Created https://issues.apache.org/jira/browse/SPARK-11445 and updated description of https://issues.apache.org/jira/browse/SPARK-11382

**Comment by mengxr** [comment]
ok to test

**Comment by gliptak** [comment]
This became a duplicate of https://github.com/apache/spark/pull/9340

commit 820064e613609bbf7edd726d982da1de60bf417a
Author: Pravin Gadakh <pravingadakh177@gmail.com>
Date:   Wed Nov 4 08:32:08 2015 -0800

    [SPARK-11380][DOCS] Replace example code in mllib-frequent-pattern-mining.md using include_example
    
    Author: Pravin Gadakh <pravingadakh177@gmail.com>
    Author: Pravin Gadakh <prgadakh@in.ibm.com>
    
    Closes #9340 from pravingadakh/SPARK-11380.

**Comment by yinxusen** [comment]
@gliptak Yes it is duplicated with #9340 . Do you plan to change example code of mllib decision tree?

**Comment by yinxusen** [comment]
@gliptak And sorry for my mistake of the mismatch between the title and content in [SPARK-11382](https://issues.apache.org/jira/browse/SPARK-11382). I have already corrected its content.

**Comment by gliptak** [comment]
https://issues.apache.org/jira/browse/SPARK-11445 is already being worked at https://github.com/apache/spark/pull/9407

**Comment by yinxusen** [comment]
@gliptak, SPARK-11445 aims to fix mllib-ensemble.md, while this one (SPARK-11382) aims to fix mllib-decision-tree.md. They are two different JIRA issues.

**Comment by gliptak** [comment]
@yinxusen 

Now I'm confused myself. Current master already have mllib-frequent-pattern-mining.md corrected:

https://raw.githubusercontent.com/apache/spark/master/docs/mllib-frequent-pattern-mining.md

so this pull request was superceded (although the title doesn't match changes in my branch).

Please confirm that I see this correctly.

Thanks

**Pull request closed without merging**
