### PR TITLE
[SPARK-7085][MLlib] Fix miniBatchFraction parameter in train method called with 4 arguments

### PR DESCRIPTION
**Pull request by kuromt**

### CODE REVIEW

**Comment by srowen** [comment]
ok to test

**Comment by srowen** [comment]
Given the comment and the case below this, this looks like a correct change.

**Comment by srowen** [comment]
@kuromatsu-nobuyuki  the title of this isn't in the right format; review https://cwiki.apache.org/confluence/display/SPARK/Contributing+to+Spark

**Comment by kuromatsu-nobuyuki** [comment]
Sorry, can I rename this title?

**Comment by srowen** [comment]
Yes, just edit it right here.

**Comment by kuromatsu-nobuyuki** [comment]
Thanks, I have edited.

**Comment by jkbradley** [comment]
LGTM.  The only place that was used was the unit test runRidgeRegressionUsingStaticMethods.
I've made a note to include this in the migration guide for Spark 1.4
Thanks!  I'll merge it into master

**Pull request closed without merging**
