### PR TITLE
[SPARK-25901][CORE] Use only one thread in BarrierTaskContext companion object 

### PR DESCRIPTION
**Pull request by yogeshg**
## What changes were proposed in this pull request?

Now we use only one `timer` (and thus a backing thread) in `BarrierTaskContext` companion object, and the objects can add `timerTasks` to that `timer`.

## How was this patch tested?

This was tested manually by generating logs and seeing that they look the same as ones before, namely, that is, a partition waiting on another partition for 5seconds generates 4-5 log messages when the frequency of logging is set to 1second.

### CODE REVIEW

**Comment by yogeshg** [comment]
In an offline discussion with @MrBago , we noted that there's at most as many (non-cancelled) `timerTasks` on the `timer` as there are slots. So, one thread for managing logging is probably fine, in fact if anything, we should also think about how we can just use the main thread. Also, this means that the `timer.purge()` call in the finally block is also `O(n + log c) \in O(constant)` where `n` is the total number of tasks and `c` is the number of cancelled tasks.

**Comment by HyukjinKwon** [comment]
cc @jiangxb1987 and @mengxr

**Review by jiangxb1987 — APPROVED** [review]
LGTM

**Comment by jiangxb1987** [comment]
Thanks, merging to master!

**Pull request closed without merging**
