### PR TITLE
[MINOR][DOCS] Fix spacings in Structured Streaming Programming Guide

### PR DESCRIPTION
**Pull request by dongjinleekr**
## What changes were proposed in this pull request?

1. Omitted space between the sentences: `... on static data.The Spark SQL engine will ...` -> `... on static data. The Spark SQL engine will ...`
2. Omitted colon in Output Model section.

## How was this patch tested?

None.

### CODE REVIEW

**Comment by srowen** [comment]
Please review the rest of the docs for simple typos like this too. Better to get it done in one go.

**Comment by dongjinleekr** [comment]
No problem! I will notify you after the review.

**Comment by srowen** [comment]
Ping @dongjinleekr do you have any other typos to report? if not, after a reasonable review, this can be just merged.

**Comment by dongjinleekr** [comment]
@srowen I just completed the review. I could not find any other typos from this document. :)

**Comment by srowen** [comment]
Merged to master/2.1

**Pull request closed without merging**
