### PR TITLE
[SPARK-25352][SQL][Followup] Add helper method and address style issue

### PR DESCRIPTION
**Pull request by viirya**
## What changes were proposed in this pull request?

This follow-up patch addresses [the review comment](https://github.com/apache/spark/pull/22344/files#r217070658) by adding a helper method to simplify code and fixing style issue.

## How was this patch tested?

Existing unit tests.

### CODE REVIEW

**Comment by viirya** [comment]
cc @hvanhovell @dbtsai @cloud-fan

**Comment by viirya** [comment]
retest this please.

**Comment by cloud-fan** [comment]
LGTM

**Review by hvanhovell — APPROVED** [review]
LGTM - merging to master/2.4

**Pull request closed without merging**
