### PR TITLE
[SPARK-13703][BUILD] Remove obsolete scala-2.10 source files

### PR DESCRIPTION
**Pull request by lresende**
## What changes were proposed in this pull request?

Remove obsolete scala-2.10 source files
## How was this patch tested?

unit tests

### CODE REVIEW

**Comment by srowen** [comment]
Aren't these still required for Scala 2.10 support?

**Comment by lresende** [comment]
@srowen  I was under the impression we were not supporting 2.10 anymore, if this is not the case I will close this PR.

**Comment by markhamstra** [comment]
@lresende It is not the case.  In Spark 2.0, the default build will now use Scala 2.11, but we will still be supporting Scala 2.10.

**Comment by srowen** [comment]
Yeah, no support has been dropped. You can close this PR.

**Comment by lresende** [comment]
Jenkins retest this please

**Comment by markhamstra** [comment]
Why has this been re-opened?

**Comment by lresende** [comment]
@markhamstra I had done this is the past, and with the current discussion of droping jdk 7 and scala 2.10 i think this might be useful now. Any concerns reopening this ?

**Comment by markhamstra** [comment]
Re-opening is not appropriate at this time.  There has been discussion on the dev list about dropping Java 7.  That is a separate issue from whether Scala 2.10 support is discontinued.  For both of these, discussion on the dev list does not constitute a decision by the Spark PMC.  Until there is such a decision, both Java 7 and Scala 2.10 support remain part of the Spark 2.0 release plan.

**Comment by lresende** [comment]
@markhamstra The discussion seems to be getting consensus, so it's not that I am jumping the gun and creating something completely new, but reopening something that seems to be aligned with the direction the community is going (mainly because it was done already). Anyway, what constitute a decision ? Does the community needs to have a vote for these types of decision ? If you feel strongly about closing this, please let me know.

**Comment by markhamstra** [comment]
There was no consensus reached in that discussion thread.  Reynold opened the thread to get a sense of how the Spark community feels about dropping Java 7 for Java 8 in Spark 2.0.  While those of us on the PMC seek to respect the opinions of others in the Spark community, ultimately the overall direction of the project is in our hands, regardless of any replies to such a comment thread.  If you look at the posts of PMC members in that thread, you will find no strong commitment to definitely dropping Java 7.  More to the point of this PR, the only PMC replies to that thread on the issue of dropping Scala 2.10 leaned toward not dropping 2.10.

Regardless, my basic point remains: There has not yet been any decision by the PMC to either drop Java 7 or Scala 2.10 support in Spark 2.0; re-opening this PR is not appropriate.

**Comment by markhamstra** [comment]
Thanks.

Before the 2.0.0 release we will need to make final decisions on both Java 7 and Scala 2.10.  It's not really difficult to remove support for either of those, so it's my opinion that delaying making the decisions is a reasonable approach for now.  Maybe later we can resurrect this PR.

**Comment by markhamstra** [comment]
One small correction: I believe Mridul was in favor of dropping Scala 2.10 support, so the expressed opinions of PMC members were mixed.

**Comment by srowen** [comment]
@markhamstra the PMC doesn't decide these things. In extreme cases it could be put to a vote. Code changes all work on lazy consensus by default. 

I actually saw no direct opposition to dropping Java 7 support or 2.10. In both cases a few people brought up the counterargument for discussion. I'm on the PMC and support both for example . I walked away with a very different impression.

The output of that thread seemed clearly that 7 support goes, with many informal +1 and no objection. I think we should have a follow on thread for 2.10 for separate clarity about any clear objections. 

But this kind of PR is OK as a WIP. It can even be a data point showing  the resulting change.

**Comment by markhamstra** [comment]
@srowen I see the decisions whether to drop Java 7 or Scala 2.10 as more than just code changes.  I'll agree that there was no objection to dropping Java 7, but there was also no definitive "this is what we are going to do."  On Scala 2.10, if we include you as in favor of dropping support, then we have you and Mridul in favor, myself skeptical, and Michael Armbrust opposed.  In short, I don't see any basis for claiming that a decision has been made to drop 2.10 support or to change from your opinion 24 days ago that this PR should be closed.

We do need to make these decisions before 2.0.0, but I still don't think that we need to decide right now.  A separate discussion on 2.10 would be a good thing, and it may well take a vote to adequately resolve the issue.

**Comment by srowen** [comment]
Yeah there isn't a 'here is the decision' message from a decider. Some in favor and no veto is the end state. Java 7 seems pretty unanimous even so I think we can take that as decided. (Or else someone please make clear their objection.)

Rereading the thread I still see more people than that in favor of dropping 2.10 and I see no veto or strong negative from Michael. Sure that deserves clarity. This PR is OK as a WIP though; you seemed to be asserting there was a decision not to make this change and don't see that happened. The opposite looks more likely actually.

**Comment by markhamstra** [comment]
While I don't see the "I think that it is premature to drop support for 2.10.x." from @marmbrus as particularly ambiguous, I also don't think that a definite decision not to drop 2.10 was made in Reynold's Java 7 thread.  Neither do I think a decision was made to drop 2.10, and I don't know what the outcome would be if it were put to a vote.  In short, I see the 2.10 issue as a no-decision (with several in the community in favor of dropping 2.10 support) and no reason to re-open this PR.

**Comment by marmbrus** [comment]
I would veto removing 2.10 support at this time.

**Pull request closed without merging**
