### PR TITLE
[SPARK-10581][Docs] Groups are not resolved in scaladoc in sql classes

### PR DESCRIPTION
**Pull request by pravingadakh**
Groups are not resolved properly in scaladoc in following classes:

sql/core/src/main/scala/org/apache/spark/sql/Column.scala
sql/core/src/main/scala/org/apache/spark/sql/SQLContext.scala
sql/core/src/main/scala/org/apache/spark/sql/functions.scala

### CODE REVIEW

**Comment by srowen** [comment]
Cool, is that all it takes? you generated the docs and the groups were correct?

**Comment by pravingadakh** [comment]
@srowen Yes, I have verified this in my local environment.

**Comment by pravingadakh** [comment]
@srowen Is there a way to see the generated docs, post a successful build?

**Comment by srowen** [comment]
I don't think so, but of course you can build them locally.

**Comment by pravingadakh** [comment]
I have generated scaladoc locally. Attaching the screenshot.
screen shot 2015-10-16 at 9 56 10 pm

Could you please merge this if there aren't any issues with it?

**Comment by srowen** [comment]
@pravingadakh while it's trivial, I typically would not merge just 5 hours after you opened it. It's not a hurry, and gives others any chance to look too.

**Comment by pravingadakh** [comment]
@srowen Fair enough. Guess I was super excited for the first commit :)

**Comment by rxin** [comment]
I've merged this, given it is now 10 hrs ... :)

**Comment by rxin** [comment]
@pravingadakh do you have an account on JIRA?

**Comment by pravingadakh** [comment]
@rxin Yes, with username pravingadakh.

**Pull request closed without merging**
