### PR TITLE
[SPARK-37645][K8S][TESTS] Rename a variable `labledConfigMaps` to `labeledConfigMaps`

### PR DESCRIPTION
**Pull request by dcoliversun**
### What changes were proposed in this pull request?

The PR aims to ix word spelling error, change `labledConfigMaps` to `labeledConfigMaps`

### Why are the changes needed?

It is a spelling error, work `labeled` is missing first `e`.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

 Pass the CIs.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
+1, LGTM. Thank you, @dcoliversun .

**Comment by dongjoon-hyun** [comment]
Merged to master for Apache Spark 3.3.

**Comment by dongjoon-hyun** [comment]
Welcome to the Apache Spark community. I added you to the Apache Spark contributor group and assigned SPARK-37654 to you.

**Comment by dcoliversun** [comment]
> 

Thank you :)

**Pull request closed without merging**
