### PR TITLE
[3.2][SPARK-39437][SQL][TEST] Normalize plan id separately in PlanStabilitySuite

### PR DESCRIPTION
**Pull request by cloud-fan**
backport https://github.com/apache/spark/pull/36827

### What changes were proposed in this pull request?

In `PlanStabilitySuite`, we normalize expression IDs by matching `#\d+` in the explain string. However, this regex can match plan id in `Exchange` node as well, which will mess up the normalization if expression IDs and plan IDs overlap.

This PR normalizes plan id separately in `PlanStabilitySuite`.
 
### Why are the changes needed?

Make the plan golden file more stable.

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

N/A

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
The patch itself looks good if CI passes.
We need this at `branch-3.3` first before landing at `branch-3.2`, don't we? @cloud-fan .

**Review by viirya — APPROVED** [review]

**Review by HyukjinKwon — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Could you fix more test failures, @cloud-fan ?

**Comment by cloud-fan** [comment]
Since this touches golden files, I'd like to have one PR per branch to be safe.

**Comment by cloud-fan** [comment]
thanks for the review, merging to 3.2!

**Comment by dongjoon-hyun** [comment]
Thank you, @cloud-fan . I also merged https://github.com/apache/spark/pull/36827 .
We need another PR for branch-3.3.

**Comment by allisonwang-db** [comment]
Thanks @cloud-fan for the fix! Updated https://github.com/apache/spark/pull/36386

**Comment by dongjoon-hyun** [comment]
Thank you, @allisonwang-db !

**Pull request closed without merging**
