### PR TITLE
[SPARK-24529][BUILD][test-maven][FOLLOW-UP] Set spotbugs-maven-plugin's fork to true

### PR DESCRIPTION
**Pull request by wangyum**
## What changes were proposed in this pull request?

Set `spotbugs-maven-plugin`'s fork to `true`, otherwise will throw exception when make distribution:
```
./dev/make-distribution.sh --name SPARK-24529  --tgz  -Phadoop-2.7 -Phive -Phive-thriftserver -Pyarn -Phadoop-provided
```
exception:
```java
...
[INFO] Reactor Summary:
[INFO] 
[INFO] Spark Project Parent POM ........................... SUCCESS [  8.753 s]
[INFO] Spark Project Tags ................................. SUCCESS [  9.334 s]
[INFO] Spark Project Sketch ............................... SUCCESS [ 12.029 s]
[INFO] Spark Project Local DB ............................. SUCCESS [ 13.641 s]
[INFO] Spark Project Networking ........................... FAILURE [10:10 min]
[INFO] Spark Project Shuffle Streaming Service ............ SKIPPED
[INFO] Spark Project Unsafe ............................... SUCCESS [ 16.415 s]
[INFO] Spark Project Launcher ............................. SKIPPED
[INFO] Spark Project Core ................................. SKIPPED
[INFO] Spark Project ML Local Library ..................... SKIPPED
[INFO] Spark Project GraphX ............................... SKIPPED
[INFO] Spark Project Streaming ............................ SKIPPED
[INFO] Spark Project Catalyst ............................. SKIPPED
[INFO] Spark Project SQL .................................. SKIPPED
[INFO] Spark Project ML Library ........................... SKIPPED
[INFO] Spark Project Tools ................................ SUCCESS [  8.750 s]
[INFO] Spark Project Hive ................................. SKIPPED
[INFO] Spark Project REPL ................................. SKIPPED
[INFO] Spark Project YARN Shuffle Service ................. SKIPPED
[INFO] Spark Project YARN ................................. SKIPPED
[INFO] Spark Project Hive Thrift Server ................... SKIPPED
[INFO] Spark Project Assembly ............................. SKIPPED
[INFO] Spark Integration for Kafka 0.10 ................... SKIPPED
[INFO] Kafka 0.10 Source for Structured Streaming ......... SKIPPED
[INFO] Spark Project Examples ............................. SKIPPED
[INFO] Spark Integration for Kafka 0.10 Assembly .......... SKIPPED
[INFO] Spark Avro ......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10:29 min (Wall Clock)
[INFO] Finished at: 2018-07-16T21:39:46+08:00
[INFO] Final Memory: 61M/885M
[INFO] ------------------------------------------------------------------------
Timeout: sub-process interrupted
[ERROR] Failed to execute goal com.github.spotbugs:spotbugs-maven-plugin:3.1.3:spotbugs (spotbugs) on project spark-network-common_2.11: Execution spotbugs of goal com.github.spotbugs:spotbugs-maven-plugin:3.1.3:spotbugs failed: Timeout: killed the sub-process -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :spark-network-common_2.11
org.apache.tools.ant.ExitException: Permission ("java.lang.RuntimePermission" "exitVM") was not granted.
        at org.apache.tools.ant.types.Permissions$MySM.checkExit(Permissions.java:194)
        at java.lang.Runtime.exit(Runtime.java:107)
        at java.lang.System.exit(System.java:971)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:358)
Exception in thread "main" org.apache.tools.ant.ExitException: Permission ("java.lang.RuntimePermission" "exitVM") was not granted.
        at org.apache.tools.ant.types.Permissions$MySM.checkExit(Permissions.java:194)
        at java.lang.Runtime.exit(Runtime.java:107)
        at java.lang.System.exit(System.java:971)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:364)
Timeout: sub-process interrupted
```

## How was this patch tested?

manual tests

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
@wangyum, I think we better test the build against maven by adding `[test-maven]` in the PR title.

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
cc @kiszk

**Comment by wangyum** [comment]
retest this please

**Comment by kiszk** [comment]
Now, I am checking `make-distribution.sh` in my environment. If my memory is correct, the error in `spark-sql_2.11` or `spark-catalyst_2.11` was a motivation to stop forking of spotbugs.

**Comment by wangyum** [comment]
retest this please

**Comment by skonto** [comment]
+1 I saw this with my build. I reported on the other PR.

**Comment by kiszk** [comment]
In my environment, `make-distribution.sh` works well without fork.

```
...
[INFO] 
[INFO] --- maven-source-plugin:3.0.1:jar-no-fork (create-source-jar) @ spark-assembly_2.11 ---
[INFO] 
[INFO] --- maven-source-plugin:3.0.1:test-jar-no-fork (create-source-jar) @ spark-assembly_2.11 ---
[INFO] 
[INFO] --- maven-antrun-plugin:1.8:run (default) @ spark-assembly_2.11 ---
[INFO] Executing tasks

main:
[INFO] Executed tasks
[INFO] 
[INFO] --- maven-source-plugin:3.0.1:test-jar-no-fork (create-source-jar) @ spark-examples_2.11 ---
[INFO] Building jar: /home/ishizaki/Spark/PR/overflow/SPARK-24529/spark/examples/target/spark-examples_2.11-2.4.0-SNAPSHOT-test-sources.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Spark Project Parent POM ........................... SUCCESS [  3.749 s]
[INFO] Spark Project Tags ................................. SUCCESS [ 19.141 s]
[INFO] Spark Project Sketch ............................... SUCCESS [ 24.832 s]
[INFO] Spark Project Local DB ............................. SUCCESS [ 19.311 s]
[INFO] Spark Project Networking ........................... SUCCESS [ 53.422 s]
[INFO] Spark Project Shuffle Streaming Service ............ SUCCESS [ 30.715 s]
[INFO] Spark Project Unsafe ............................... SUCCESS [ 33.014 s]
[INFO] Spark Project Launcher ............................. SUCCESS [ 22.917 s]
[INFO] Spark Project Core ................................. SUCCESS [32:29 min]
[INFO] Spark Project ML Local Library ..................... SUCCESS [01:15 min]
[INFO] Spark Project GraphX ............................... SUCCESS [01:24 min]
[INFO] Spark Project Streaming ............................ SUCCESS [04:32 min]
[INFO] Spark Project Catalyst ............................. SUCCESS [14:08 min]
[INFO] Spark Project SQL .................................. SUCCESS [12:10 min]
[INFO] Spark Project ML Library ........................... SUCCESS [04:59 min]
[INFO] Spark Project Tools ................................ SUCCESS [ 16.323 s]
[INFO] Spark Project Hive ................................. SUCCESS [08:14 min]
[INFO] Spark Project REPL ................................. SUCCESS [  7.546 s]
[INFO] Spark Project YARN Shuffle Service ................. SUCCESS [ 17.865 s]
[INFO] Spark Project YARN ................................. SUCCESS [ 59.089 s]
[INFO] Spark Project Hive Thrift Server ................... SUCCESS [ 38.509 s]
[INFO] Spark Project Assembly ............................. SUCCESS [  1.320 s]
[INFO] Spark Integration for Kafka 0.10 ................... SUCCESS [ 46.277 s]
[INFO] Kafka 0.10 Source for Structured Streaming ......... SUCCESS [ 27.301 s]
[INFO] Spark Project Examples ............................. SUCCESS [ 44.678 s]
[INFO] Spark Integration for Kafka 0.10 Assembly .......... SUCCESS [  7.238 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:09 h (Wall Clock)
[INFO] Finished at: 2018-07-17T16:23:18+09:00
[INFO] Final Memory: 78M/1967M
[INFO] ------------------------------------------------------------------------
...
```

**Comment by wangyum** [comment]
@kiszk What is your environment? My environment is:
```
Java HotSpot(TM) 64-Bit Server VM 1.8.0_151-b12 on Mac OS X 10.12.6
```

**Comment by kiszk** [comment]
@wangyum my environment is 
```
$ java -version
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.16.04.1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)
```

**Comment by kiszk** [comment]
I got the same error in my Mac. I understand that the motivation of forking is [this solution](https://stackoverflow.com/questions/22609357/jenkins-fatal-error-timeout-killed-the-sub-process).

Unfortunately, I cannot access my Mac until this weekend. For now, let me retest again.

**Comment by kiszk** [comment]
retest this please

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
@kiszk, let me just push this in since it fixes an actual issue and the build passes; however, please make a followup if you see something else to fix.

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by kiszk** [comment]
@HyukjinKwon @wangyum  thank you.
If there is no error in amp build infra, I think that this is a better way.

**Comment by kiszk** [comment]
@HyukjinKwon @wangyum  thank you. I took a vacation.
If there is no error in amp build infra, I think that this is a better way.

**Pull request closed without merging**
