### PR TITLE
[SPARK-5913] [MLLIB] Python API for ChiSqSelector

### PR DESCRIPTION
**Pull request by yanboliang**
Add a Python API for mllib.feature.ChiSqSelector
https://issues.apache.org/jira/browse/SPARK-5913

### CODE REVIEW

**Comment by yanboliang** [comment]
@mengxr , @jkbradley

**Comment by jkbradley** [comment]
I'll take a look now

**Comment by jkbradley** [comment]
I don't see any issues except for documentation.  Could you please make the Python docs match the Scala ones?  (We've been lazy about keeping them in synch, but I want to push for Python doc parity.)  Thanks!

As a follow up PR, we can finally add a Python code example to the programming guide!

**Comment by jkbradley** [comment]
Oh, also, can you please update the PR description with more details?  Feel free to copy from the JIRA.

**Comment by yanboliang** [comment]
@jkbradley , I think the Python docs for ChiSqSelector and ChiSqSelectorModel have reached parity with Scala ones. Please correct me is I misunderstand.
Yes, I will add a Python code example to the programming guide in a follow up PR. We also need to check other API  and add corresponding Python code examples.

**Comment by jkbradley** [comment]
@yanboliang Sorry, I just assumed the Scala doc had more content.  I'll make that a to-do for later.  In this case, LGTM!

For the API check, we're gradually putting together a list of the many items under this umbrella: [https://issues.apache.org/jira/browse/SPARK-7443]

Merging into master and branch-1.4

**Comment by jkbradley** [comment]
Hm, the merge script complains that this is not mergeable currently.  I'll re-run the tests

**Comment by jkbradley** [comment]
Weird, I'll investigate

**Comment by jkbradley** [comment]
It worked this time.  Thanks!

**Pull request closed without merging**
