### PR TITLE
[SPARK-11788][SQL] surround timestamp/date value with quotes in JDBC data source

### PR DESCRIPTION
**Pull request by huaxingao**
When query the Timestamp or Date column like the following
val filtered = jdbcdf.where($"TIMESTAMP_COLUMN" >= beg && $"TIMESTAMP_COLUMN" < end)
The generated SQL query is "TIMESTAMP_COLUMN >= 2015-01-01 00:00:00.0"
It should have quote around the Timestamp/Date value such as "TIMESTAMP_COLUMN >= '2015-01-01 00:00:00.0'"

### CODE REVIEW

**Comment by JoshRosen** [comment]
Can you add a regression test for this?

**Comment by huaxingao** [comment]
Sure.  Will add a test.

**Comment by huaxingao** [comment]
@JoshRosen 
Regression test added.  Could you please take a look?  
Thanks a lot for your help!!

**Comment by rxin** [comment]
LGTM - Jenkins, test this please.

**Comment by rxin** [comment]
Can you update the title to

"[SPARK-11788][SQL] surround timestamp/date value with quotes in JDBC data source"

**Comment by huaxingao** [comment]
Fixed title and scala style problem.  Thanks!

**Comment by yhuai** [comment]
Merging to master and branch 1.6.

**Comment by yhuai** [comment]
I also merged it in branch 1.5.

**Pull request closed without merging**
