### PR TITLE
[SPARK-32525][DOCS] The layout of monitoring.html is broken

### PR DESCRIPTION
**Pull request by sarutak**
### What changes were proposed in this pull request?

This PR fixes the layout of monitoring.html broken after SPARK-31566(#28354).
The cause is there are 2 `<td>` tags not closed in `monitoring.md`.

### Why are the changes needed?

This is a bug.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Build docs and the following screenshots are before/after.

* Before fixed
broken-doc

* After fixed.
fixed-doc2

Of course, the table is still rendered correctly.
fixed-doc1

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
cc @erenavsarogullari and @gengliangwang

**Review by gengliangwang — APPROVED** [review]
LGTM, thanks for the fix!

**Comment by gengliangwang** [comment]
Merging to master

**Comment by erenavsarogullari** [comment]
Thanks folks for the patch and reviews.

**Pull request closed without merging**
