### PR TITLE
[SPARK-36502][SQL] Remove jaxb-api from `sql/catalyst` module

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to remove `jaxb-api` usage from `sql/catalyst` module.

### Why are the changes needed?

We only use `DatatypeConverter.parseHexBinary` and `DatatypeConverter.printHexBinary` twice.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the CIs.

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]
Looks good. cc @sarutak FYI

**Review by sarutak — APPROVED** [review]
LGTM. Pending GA.

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by dongjoon-hyun** [comment]
Thank you, @HyukjinKwon and @sarutak !

**Pull request closed without merging**
