### PR TITLE
[SPARK-21573][BUILD] Tests failing with run-tests.py SyntaxError occasionally in Jenkins

### PR DESCRIPTION
**Pull request by srowen**
## What changes were proposed in this pull request?

Select Python 2.7 explicitly on Jenkins machines

## How was this patch tested?

Existing tests

### CODE REVIEW

**Comment by srowen** [comment]
CC @holdenk @dongjoon-hyun 
I know the point is to not support 2.6, but, maybe this is just as good as anything as a quick fix?

**Comment by HyukjinKwon** [comment]
@srowen, I actually tried this way ahead. I just ran `python2.6 run-tests.py` for sure against this PR:

```
Traceback (most recent call last):
  File "run-tests.py", line 42, in <module>
    from sparktestsupport.modules import all_modules  # noqa
  File "/.../spark/python/../dev/sparktestsupport/modules.py", line 18, in <module>
    from functools import total_ordering
ImportError: cannot import name total_ordering
```

It looks we need several places to fix. For example, `total_ordering` is new in Python 2.7 -
 https://docs.python.org/2/library/functools.html#functools.total_ordering.

**Comment by HyukjinKwon** [comment]
I googled a bit before. It looks one way I could find is, we should manually add `total_ordering` - `https://github.com/nvie/rq/commit/282f4be9316d608ebbacd6114aab1203591e8f95` however, this looked too much.

**Comment by srowen** [comment]
Ah OK, so it's a no-go. I wonder if writing python2.7 in the shebang will work on the Jenkins machines? @shaneknapp

**Comment by srowen** [comment]
@HyukjinKwon this one just tries to explicitly select 2.7. If it fails, well, I suppose it would already fail the build anyway. If it successfully picks 2.7 then it should resolve this I guess. These are the two instances that explicitly select `python2`

**Comment by HyukjinKwon** [comment]
@srowen, IIRC, I guess this should be correct when we run this as executable. If I understood correctly, we run `run-tests` - https://github.com/apache/spark/blob/master/dev/run-tests-jenkins.py#L115 which actually runs `run-tests.py` with `python` rather than as executable - https://github.com/apache/spark/blob/master/dev/run-tests#L23.

I was thinking a way such as, 

```diff
--- a/dev/run-tests
+++ b/dev/run-tests
@@ -20,4 +20,8 @@
 FWDIR="$(cd "`dirname $0`"/..; pwd)"
 cd "$FWDIR"

-exec python -u ./dev/run-tests.py "$@"
+PYTHON_EXECUTABLE=python
+if hash python2.7 2>/dev/null; then
+  PYTHON_EXECUTABLE=python2.7
+fi
+exec $PYTHON_EXECUTABLE -u ./dev/run-tests.py "$@"
```

I know this bit is hard to test (existing tests indeed cover this but .. I guess it is rather randomly covered) but fortunately I already have an Ubuntu VM having `python` as Python 2.6.9. Do you mind if I take over this and CC you if this way makes sense to you? I guess it's easy to test for me now.

**Comment by srowen** [comment]
Yeah go ahead. I pushed your change here anyway

**Comment by HyukjinKwon** [comment]
Will double check this one and merge it if we need no more changes. Or, will send a PR to your branch or open another PR. I will handle this in any event.

**Comment by HyukjinKwon** [comment]
Ugh.. this still fails:

```
========================================================================
Running Python style checks
========================================================================
PEP8 checks failed.
Compiling ./dev/run-tests.py ...
SyntaxError: ('invalid syntax', ('./dev/run-tests.py', 124, 65, '        {m: set(m.dependencies).intersection(modules_to_test) for m in modules_to_test}, sort=True)\n'))

[error] running /root/test/spark/dev/lint-python ; received return code 1
```

https://github.com/apache/spark/blob/864d94fe879a32de324da65a844e62a0260b222d/dev/run-tests.py#L212 -> https://github.com/apache/spark/blob/864d94fe879a32de324da65a844e62a0260b222d/dev/lint-python#L33

**Comment by srowen** [comment]
That could just mean the machine doesn't have 2.7 installed then. This may really be an env issue.

**Comment by HyukjinKwon** [comment]
Just as a last note I checked, after fixing `lint-python`, it failed again somewhere:

```
========================================================================
Running PySpark tests
========================================================================
Traceback (most recent call last):
  File "./python/run-tests.py", line 42, in <module>
    from sparktestsupport.modules import all_modules  # noqa
  File "/.../spark/python/../dev/sparktestsupport/modules.py", line 18, in <module>
    from functools import total_ordering
ImportError: cannot import name total_ordering
[error] running /.../spark/python/run-tests --parallelism=4 ; received return code 1
```

**Pull request closed without merging**
