### PR TITLE
[SPARK-16971][SQL] Strip trailing zeros for decimal's string representation when using show() API in Dataset

### PR DESCRIPTION
**Pull request by HyukjinKwon**
## What changes were proposed in this pull request?

Currently, `Dataset.show()` prints all the trailing zeros for decimals. For example,

``` scala
spark.range(11).toDF("a").select('a.cast(DecimalType(30, 20))).show()
```

prints below:

``` bash
+--------------------+
|                   a|
+--------------------+
|               0E-20|
|1.000000000000000...|
|2.000000000000000...|
|3.000000000000000...|
|4.000000000000000...|
|5.000000000000000...|
|6.000000000000000...|
|7.000000000000000...|
|8.000000000000000...|
|9.000000000000000...|
|10.00000000000000...|
+--------------------+
```

It might be confusing, in particular, for `0E-20`. Also, I think we can strip the trailing zeros.

This PR fixes this as below:

``` bash
+---+
|  a|
+---+
|  0|
|  1|
|  2|
|  3|
|  4|
|  5|
|  6|
|  7|
|  8|
|  9|
| 10|
+---+
```
## How was this patch tested?

Unit test in `DataFrameSuite`.

### CODE REVIEW

**Comment by rxin** [comment]
hm this is not what postgres does

```
rxin=# select cast(2.01 as numeric(40, 20));
        numeric         
------------------------
 2.01000000000000000000
(1 row)
```

**Comment by rxin** [comment]
I'm going to mark this as won't fix. If it is a decimal type, I actually expect it to show me all the 0s.

**Comment by HyukjinKwon** [comment]
Thanks for your feedback!

**Comment by HyukjinKwon** [comment]
(BTW, it seems this is what hive does)

**Pull request closed without merging**
