### PR TITLE
[SPARK-49764][PYTHON][CONNECT] Support area plots

### PR DESCRIPTION
**Pull request by xinrong-meng**
### What changes were proposed in this pull request?
Support area plots with plotly backend on both Spark Connect and Spark classic.

### Why are the changes needed?
While Pandas on Spark supports plotting, PySpark currently lacks this feature. The proposed API will enable users to generate visualizations. This will provide users with an intuitive, interactive way to explore and understand large datasets directly from PySpark DataFrames, streamlining the data analysis workflow in distributed environments.

See more at [PySpark Plotting API Specification](https://docs.google.com/document/d/1IjOEzC8zcetG86WDvqkereQPj_NGLNW7Bdu910g30Dg/edit?usp=sharing) in progress.

Part of https://issues.apache.org/jira/browse/SPARK-49530.

### Does this PR introduce _any_ user-facing change?
Yes. Area plots are supported as shown below.

```py
>>> from datetime import datetime
>>> data = [
...     (3, 5, 20, datetime(2018, 1, 31)),
...     (2, 5, 42, datetime(2018, 2, 28)),
...     (3, 6, 28, datetime(2018, 3, 31)),
...     (9, 12, 62, datetime(2018, 4, 30))]
>>> columns = ["sales", "signups", "visits", "date"]
>>> df = spark.createDataFrame(data, columns)
>>> fig = df.plot.area(x="date", y=["sales", "signups", "visits"])  # df.plot(kind="area", x="date", y=["sales", "signups", "visits"])
>>> fig.show()     
```
newplot (7)

### How was this patch tested?
Unit tests.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by xinrong-meng** [comment]
@zhengruifeng may I get a review please? Thank you!

**Comment by abhinavgudipati** [comment]
Hello @xinrong-meng! I was wondering if I could contribute to spark! 
I am currently a Data Engineer with a British Bank and I have developed sound knowledge over pyspark through the last several months. 
Could you guide me further over prospective issues I could work on! 

For now I am reading up on merged pull requests to get a picture on the issues taken up so far
Thanks!

**Review by zhengruifeng — APPROVED** [review]

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by xinrong-meng** [comment]
Thank you @zhengruifeng and @HyukjinKwon !

**Comment by xinrong-meng** [comment]
Hi @abhinavgudipati thanks for reaching out! It’s great to hear that you’re interested in contributing to Spark.
A good starting point would be to look at the open issues on the [Apache Spark JIRA](https://issues.apache.org/jira/projects/SPARK/issues). Since you’re already reading up on merged pull requests, you’re on the right track! That will give you a good idea of the areas you can contribute to. You might want to check out the PySpark components since you have experience there.
Also, participating in code reviews is a great way to get familiar with the codebase.
You can find more detailed guidance on https://spark.apache.org/contributing.html good luck with your journey into Spark contributions!

**Pull request closed without merging**
