### PR TITLE
[MINOR][SQL] Additional test case for CheckCartesianProducts rule

### PR DESCRIPTION
**Pull request by aokolnychyi**
## What changes were proposed in this pull request?

While discovering optimization rules and their test coverage, I did not find any tests for `CheckCartesianProducts` in the Catalyst folder. So, I decided to create a new test suite. Once I finished, I found a test in `JoinSuite` for this functionality so feel free to discard this change if it does not make much sense. The proposed test suite covers a few additional use cases.

### CODE REVIEW

**Comment by gatorsmile** [comment]
@aokolnychyi Thank you! Could you compare the original PR and checks whether we miss any test case you added here?  https://github.com/apache/spark/pull/14866

In addition, I also had a PR which is not merged. https://github.com/apache/spark/pull/16762 Maybe you also can use some test cases from that PR.

**Comment by aokolnychyi** [comment]
@gatorsmile I took a look at both PRs. 

I quickly scanned  PR #14866 and did not find tests for existence joins. Also, `SQLConf.CROSS_JOINS_ENABLED = true` is checked only for `left_outer`. So, the proposed tests slightly improve the coverage. 

PR #16762 checks everything from a different prospective than the proposed rules and has some unique scenarios compared to PR #14866. The main question that PR #16762 rises is about, for instance, inner joins with inequality conditions. As far as I understood, the ability to detect such cartesian products was the motivation to move the check away from the Optimizer. Is it still planned? Cannot this be also done by modifying the existing rule in the Optimizer? Currently, it only checks that there are conditions which reference to both sides. Instead, it can rely on equality predicates, right?

**Comment by gatorsmile** [comment]
@aokolnychyi That PR https://github.com/apache/spark/pull/16762 will not be merged. We follow the definition of [CROSS JOIN](http://docs.oracle.com/javadb/10.6.2.1/ref/rrefsqljcrossjoin.html). So far, in this PR, maybe we just add the missing test cases?

**Comment by aokolnychyi** [comment]
@gatorsmile sure, this PR is only about tests, I was just wondering what is planned regarding cross joins with inequality conditions.

I borrowed several tests from PR #16762 and added additional ones. As I mentioned, there is a small overlap between the existing tests and proposed ones but they are defined at different levels.

**Comment by gatorsmile** [comment]
LGTM

**Comment by gatorsmile** [comment]
Thanks! Merging to master.

**Pull request closed without merging**
