### PR TITLE
SPARK-6085 Increase default value for memory overhead

### PR DESCRIPTION
**Pull request by tedyu**

### CODE REVIEW

**Comment by nishkamravi2** [comment]
@tedyu  We had decided to keep the same default for both yarn and mesos, so it would be best to increase both. Please see mesos/MemoryUtils.scala 

Also, docs/running-on-yarn and docs/running-on-mesos would have to be modified accordingly.

**Comment by tedyu** [comment]
Thanks for the reminder, updated accordingly.

**Comment by nishkamravi2** [comment]
LGTM

**Comment by srowen** [comment]
I also tend to think that this is a good change, given that a non-trivial proportion of people seem to be running into this and the point was to make it big enough to only require tuning in a small number of cases.

**Comment by srowen** [comment]
Pinging @vanzin @pwendell @sryza as people who might want to weigh in. I hesitate to commit to 1.3 at this late stage; master seems OK though.

Given the narrow purpose of this change I think it should go on; there's a slightly higher-level debate still going on about whether having this value at all is correct, but would like to not revisit that here.

**Comment by vanzin** [comment]
I'm ok with changing it; the original value was mostly empirical, and it seems that once more people tried things out it turned out to not be enough, so it's ok to bump it.

**Comment by nishkamravi2** [comment]
This number has gone up from 5-8% to 7-10% for the same set of workloads with recent versions of Spark/YARN (no idea why). Bumping the default up seems like the logical thing to do.

**Comment by sryza** [comment]
Bumping the default to 10% seems reasonable to me as well.

**Pull request closed without merging**
