### PR TITLE
[SPARK-21801][SPARKR][TEST] unit test randomly fail with randomforest

### PR DESCRIPTION
**Pull request by felixcheung**
## What changes were proposed in this pull request?

fix the random seed to eliminate variability

## How was this patch tested?

jenkins, appveyor, lots more jenkins

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by felixcheung** [comment]
jenkins, retest this pleace

**Comment by felixcheung** [comment]
jenkins, retest this please

**Comment by felixcheung** [comment]
jenkins, retest this please

**Comment by felixcheung** [comment]
jenkins, retest this please

**Review by WeichenXu123 — COMMENTED** [review]
Thanks!
But I want to ask why use some other seed will cause the failure ? Can we make the test data always succeed under any random seed ?

**Comment by felixcheung** [comment]
the error specifically is:
`The input column stridx_87ea3065aeb2 should have at least two distinct values.`
I don't think this would be only happening in R - I suppose whenever the string label has only one distinct value, ml's random forest will just give up like this.

**Comment by felixcheung** [comment]
but i think in general it's better to make tests more predictable like this

**Comment by felixcheung** [comment]
jenkins, retest this please

**Review by WeichenXu123 — COMMENTED** [review]
I have seen `DecisionTree` in Rtest also have this problem randomly, like:
```
Error: spark.decisionTree (@test_mllib_tree.R#353) --------------------------
java.lang.IllegalArgumentException: requirement failed: The input column stridx_d6a0b492cfa1 should have at least two distinct values.
```
So DecisionTree R-Test is also not deterministic, can you check all ml test in R ? Thanks!

**Comment by WeichenXu123** [comment]
@felixcheung This error occur in the OneHotEncoder inside the RFormula I think. Only OneHotEncoder will print this error message after I search the project...

**Comment by WeichenXu123** [comment]
ping @felixcheung We can make all R tests for trees deterministic (not only random trees). Leave other problems to separate PR. It would be great to fix it soon, Thanks!

**Comment by felixcheung** [comment]
Can you point me to other failures? How frequently does it occur?

I'm reasonably sure setting the seed should fix the randomness, I can get to other changes within a day, but I want to know how many test runs should tell us if it really fixes the problem

________________________________

**Review by WeichenXu123 — COMMENTED** [review]
Line 255: test_that("spark.decisionTree", ...
This also need make seed deterministic.
(The similar error also occur in `decisionTree` Rtest)

**Comment by felixcheung** [comment]
I mean Jenkins log of the test run that failed

**Comment by felixcheung** [comment]
Jenkins, retest this please

**Comment by WeichenXu123** [comment]
@felixcheung In Jenkins Log I only found Random forest and Decision Tree failed, random forest failed more frequently. thanks!

**Review by WeichenXu123 — APPROVED** [review]

**Comment by felixcheung** [comment]
merged to master

**Comment by WeichenXu123** [comment]
cc @felixcheung 
I encounter RTest failed again even when this seed added.
https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/81350/console
error:
```
Failed -------------------------------------------------------------------------
1. Error: spark.decisionTree (@test_mllib_tree.R#355) --------------------------
java.lang.IllegalArgumentException: requirement failed: The input column stridx_629e10e5fd28 should have at least two distinct values.
	at scala.Predef$.require(Predef.scala:224)
	at org.apache.spark.ml.feature.OneHotEncoder$$anonfun$5.apply(OneHotEncoder.scala:113)
	at org.apache.spark.ml.feature.OneHotEncoder$$anonfun$5.apply(OneHotEncoder.scala:111)
	at scala.Option.map(Option.scala:146)
	at org.apache.spark.ml.feature.OneHotEncoder.transformSchema(OneHotEncoder.scala:111)
	at org.apache.spark.ml.feature.OneHotEncoder.transform(OneHotEncoder.scala:141)
	at org.apache.spark.ml.Pipeline$$anonfun$fit$2.apply(Pipeline.scala:161)
	at org.apache.spark.ml.Pipeline$$anonfun$fit$2.apply(Pipeline.scala:149)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableViewLike$Transformed$class.foreach(IterableViewLike.scala:44)
	at scala.collection.SeqViewLike$AbstractTransformed.foreach(SeqViewLike.scala:37)
	at org.apache.spark.ml.Pipeline.fit(Pipeline.scala:149)
	at org.apache.spark.ml.feature.RFormula.fit(RFormula.scala:270)
	at org.apache.spark.ml.r.DecisionTreeClassifierWrapper$.fit(DecisionTreeClassificationWrapper.scala:84)
	at org.apache.spark.ml.r.DecisionTreeClassifierWrapper.fit(DecisionTreeClassificationWrapper.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.spark.api.r.RBackendHandler.handleMethodCall(RBackendHandler.scala:167)
	at org.apache.spark.api.r.RBackendHandler.channelRead0(RBackendHandler.scala:108)
	at org.apache.spark.api.r.RBackendHandler.channelRead0(RBackendHandler.scala:40)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:643)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:566)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
1: spark.decisionTree(traindf, clicked ~ ., type = "classification", maxDepth = 5, maxBins = 16, 
       seed = 46) at /home/jenkins/workspace/SparkPullRequestBuilder/R/pkg/tests/fulltests/test_mllib_tree.R:355
2: spark.decisionTree(traindf, clicked ~ ., type = "classification", maxDepth = 5, maxBins = 16, 
       seed = 46)
3: .local(data, formula, ...)
4: callJStatic("org.apache.spark.ml.r.DecisionTreeClassifierWrapper", "fit", data@sdf, 
       formula, as.integer(maxDepth), as.integer(maxBins), impurity, as.integer(minInstancesPerNode), 
       as.numeric(minInfoGain), as.integer(checkpointInterval), seed, as.integer(maxMemoryInMB), 
       as.logical(cacheNodeIds), handleInvalid)
5: invokeJava(isStatic = TRUE, className, methodName, ...)
6: handleErrors(returnStatus, conn)
7: stop(readString(conn))

DONE ===========================================================================
Error: Test failures
Execution halted
```

Would you like take a look ?

**Comment by felixcheung** [comment]
ouch. I think this is because
```
# Test unseen labels
  data <- data.frame(clicked = base::sample(c(0, 1), 10, replace = TRUE),
  someString = base::sample(c("this", "that"), 10, replace = TRUE),
                            stringsAsFactors = FALSE)
  trainidxs <- base::sample(nrow(data), nrow(data) * 0.7)
  traindf <- as.DataFrame(data[trainidxs, ])
  testdf <- as.DataFrame(rbind(data[-trainidxs, ], c(0, "the other")))
  model <- spark.decisionTree(traindf, clicked ~ ., type = "classification",
                              maxDepth = 5, maxBins = 16, seed = 46)
```
traindf is created from a sampled data.frame. this sampling will be random as well. let me see what I can do.

**Comment by felixcheung** [comment]
#19111

**Pull request closed without merging**
