### PR TITLE
[SPARK-31420][WEBUI][3.0] Infinite timeline redraw in job details page

### PR DESCRIPTION
**Pull request by sarutak**
### What changes were proposed in this pull request?

This PR backports #28192 to branch-3.0.

### Why are the changes needed?

SPARK-31420 affects branch-3.0 too.

### Does this PR introduce any user-facing change?

No.

### How was this patch tested?

Same as #28192

### CODE REVIEW

**Comment by sarutak** [comment]
cc: @gengliangwang , @dongjoon-hyun

**Comment by sarutak** [comment]
Tests failed on CI environment passed on my laptop.

**Comment by sarutak** [comment]
retest this please.

**Comment by sarutak** [comment]
retest this please.

**Review by gengliangwang — APPROVED** [review]
LGTM

**Pull request closed without merging**
