### PR TITLE
[SPARK-46033][SQL][TESTS] Fix flaky ArithmeticExpressionSuite

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to fix flaky ArithmeticExpressionSuite.
https://github.com/panbingkun/spark/actions/runs/6940660146/job/18879997046
image

### Why are the changes needed?
Fix bug.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
- Manually test.
- Pass GA.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by panbingkun** [comment]
cc @kazuyukitanimura

**Review by kazuyukitanimura — APPROVED** [review]
Thank you @panbingkun
Pending CI
cc @dongjoon-hyun

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by dongjoon-hyun** [comment]
Merged to master/3.5/3.4.

**Comment by dongjoon-hyun** [comment]
Thank you, @panbingkun and @kazuyukitanimura .

**Pull request closed without merging**
