### PR TITLE
[SPARK-34916][SQL][FOLLOWUP] Remove duplicate code in `TreeNode.treePatternBits`

### PR DESCRIPTION
**Pull request by gengliangwang**
### What changes were proposed in this pull request?

Remove duplicate code in `TreeNode.treePatternBits`

### Why are the changes needed?

Code clean up. Make it easier for maintainence.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by gengliangwang** [comment]
cc @sigmod @hvanhovell

**Comment by sigmod** [comment]
LGTM.
Thanks for the nice cleanup, Gengliang!

**Review by hvanhovell — APPROVED** [review]
LGTM

**Comment by gengliangwang** [comment]
Merging to master

**Pull request closed without merging**
