### PR TITLE
[BUILD] Close stale PRs

### PR DESCRIPTION
**Pull request by srowen**
Closes https://github.com/apache/spark/pull/20458
Closes https://github.com/apache/spark/pull/20530
Closes https://github.com/apache/spark/pull/20557
Closes https://github.com/apache/spark/pull/20966
Closes https://github.com/apache/spark/pull/20857
Closes https://github.com/apache/spark/pull/19694
Closes https://github.com/apache/spark/pull/18227
Closes https://github.com/apache/spark/pull/20683
Closes https://github.com/apache/spark/pull/20881
Closes https://github.com/apache/spark/pull/20347
Closes https://github.com/apache/spark/pull/20825
Closes https://github.com/apache/spark/pull/20078

Closes https://github.com/apache/spark/pull/21281
Closes https://github.com/apache/spark/pull/19951
Closes https://github.com/apache/spark/pull/20905
Closes https://github.com/apache/spark/pull/20635

### CODE REVIEW

**Comment by vanzin** [comment]
Add:
Closes #21281
Closes #19951
Closes #20905

Maybe:
#18229
#19802

**Comment by vanzin** [comment]
Add:
Closes #20635 (already merged)

**Comment by srowen** [comment]
I'll leave #18229 just to err on the side of caution, but it does look stale.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by yupbank** [comment]
thanks for closing my pr

**Pull request closed without merging**
