### PR TITLE
SPARK-11065 - Display exception in debug for sending warning

### PR DESCRIPTION
**Pull request by jbonofre**
Set the exception stack trace in debug to avoid to "disturb" users.

### CODE REVIEW

**Comment by srowen** [comment]
I tend to agree with that, if in fact this is a warning only, and somewhat commonly encountered in normal operation during shutdown. This code path doesn't only occur during shutdown, but I do tend to agree with making the exception "optional" at the warning level here anyway.

It also rests on the assumption that the case observed in the JIRA is ignorable and just a side effect of components shutting down asynchronously and occasionally complaining that something can't be contacted.

**Comment by jbonofre** [comment]
It's the cause of the warning that I see during shutdown (and not randomly, I always have the exception).

**Comment by andrewor14** [comment]
I actually think having the stack trace is helpful. Otherwise all you see is `Exception in sending message`, which is not a useful warning by itself. (What action is the user supposed to take after seeing this log?)

**Comment by andrewor14** [comment]
If the motivation for this change is because we print a lot of things when we shut down then we should fix that instead. I've observed this myself that in 1.6 a driver that shut down correctly prints a bunch of stack traces. This does not happen in 1.5.

**Comment by jbonofre** [comment]
Actually, I'm working on the cause of the problem (on the netty stack). I will update the PR soon.

**Comment by andrewor14** [comment]
Thanks @jbonofre, that will be very helpful.

**Comment by jbonofre** [comment]
@andrewor14 You're very welcome, I'm more than happy to help ;)

**Comment by srowen** [comment]
Yes the stack trace has some use; the theory here was to not print it at warning level, so you could at least filter it separately. Maybe debug is too low; info level?

**Comment by jbonofre** [comment]
Agree with @srowen . Let me upgrade in the mean time (to log in info, in addition of providing the fix for the cause of the problem).

**Comment by jbonofre** [comment]
I just tested it again and the problem is gone.

**Pull request closed without merging**
