### PR TITLE
[SPARK-11969] [SQL] [PYSPARK] visualization of SQL query for pyspark

### PR DESCRIPTION
**Pull request by davies**
Currently, we does not have visualization for SQL query from Python, this PR fix that.

cc @zsxwing

### CODE REVIEW

**Comment by zsxwing** [comment]
Did you test `saveXXX` methods?

**Comment by davies** [comment]
@zsxwing all the save and write call Java API directly, so they all work as expected.

**Comment by zsxwing** [comment]
> @zsxwing all the save and write call Java API directly, so they all work as expected.

cool. LGTM

**Comment by davies** [comment]
Merging this into master and 1.6!

**Pull request closed without merging**
