### PR TITLE
[SPARK-27212][SQL] Eliminate TimeZone to ZoneId conversion in stringToTimestamp

### PR DESCRIPTION
**Pull request by MaxGekk**
## What changes were proposed in this pull request?

In the PR, I propose to avoid the `TimeZone` to `ZoneId` conversion in `DateTimeUtils.stringToTimestamp` by changing signature of the method, and require a parameter of `ZoneId` type. This will allow to avoid unnecessary conversion (`TimeZone` -> `String` -> `ZoneId`) per each row.

Also the PR avoids creation of `ZoneId` instances from `ZoneOffset` because `ZoneOffset` is a sub-class, and the conversion is unnecessary too. 

## How was this patch tested?

It was tested by `DateTimeUtilsSuite` and `CastSuite`.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
ok to test

**Comment by MaxGekk** [comment]
@HyukjinKwon It seems jenkins doesn't want to listen you.

**Comment by srowen** [comment]
Jenkins is down about half the day at this point; bear with it until the window today opens up again where it works

**Comment by HyukjinKwon** [comment]
cc @ueshin FYI

**Comment by MaxGekk** [comment]
@ueshin @srowen @HyukjinKwon Please, review the PR.

**Comment by ueshin** [comment]
LGTM.

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
