### PR TITLE
[ SPARK-11180 ] [ SQL ] DataFrame.na.fill does not support Boolean Type

### PR DESCRIPTION
**Pull request by rishabhbhardwaj**
Added support for boolean types in fill and replace methods

### CODE REVIEW

**Comment by JoshRosen** [comment]
Jenkins, this is ok to test.

**Comment by rxin** [comment]
Thanks - I'm going to merge this.

**Comment by rxin** [comment]
@rishabhbhardwaj what's your asf jira id?  I need that in order to assign the ticket to you.

**Comment by rishabhbhardwaj** [comment]
Thanks @rxin , My jira id is rishabhbhardwaj

**Pull request closed without merging**
