### PR TITLE
Set SPARK_EC2_VERSION to 1.5.2

### PR DESCRIPTION
**Pull request by apivovarov**

### CODE REVIEW

**Comment by shivaram** [comment]
Jenkins, ok to test

**Comment by srowen** [comment]
Hm, I thought this script/support was removed from Spark just to avoid this kind of maintenance?

**Comment by shivaram** [comment]
It hasn't been completely moved out yet -- We did the first part of the transition i.e. moving to amplab/spark-ec2 from mesos/spark-ec2, but the second part of moving this script out hasn't happened yet.

**Comment by shivaram** [comment]
LGTM. Merging this. Thanks @apivovarov

**Comment by JoshRosen** [comment]
Hi @apivovarov, would you mind closing this PR now that it has been merged? GitHub can't auto-close PRs that are opened against backport branches. Thanks!

**Comment by apivovarov** [comment]
We need to merge recent fixes from master to this branch https://github.com/apache/spark/pull/9975

**Pull request closed without merging**
