### PR TITLE
[SPARK-34132][DOCS][R] Update Roxygen version references to 7.1.1

### PR DESCRIPTION
**Pull request by zero323**
### What changes were proposed in this pull request?

This PR updates `roxygen2` version reference in docs and `DESCRIPTION` file.

### Why are the changes needed?

According to information provided by @shaneknapp (see [this comment](https://issues.apache.org/jira/browse/SPARK-30747?focusedCommentId=17265142&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17265142) to SPARK-30747) all workers use roxygen 7.1.1.

In GitHub workflow we install the latest version

https://github.com/apache/spark/blob/c75c29dcaa9458a9ce0dd7a4d5fafbffb4b7f6a6/.github/workflows/build_and_test.yml#L346

which [is also 7.1.1 at the moment](https://web.archive.org/web/20210115172522/https://cran.r-project.org/web/packages/roxygen2/).

### Does this PR introduce _any_ user-facing change?

Docs and description mention currently used package verison.

### How was this patch tested?

- `dev/lint-r`.
- Manual check of command used in docs.

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Please make a JIRA for this, @zero323 .

**Comment by zero323** [comment]
> Please make a JIRA for this, @zero323 .

Done @dongjoon-hyun

**Review by srowen — APPROVED** [review]

**Review by HyukjinKwon — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @zero323 .
Merged to master/3.1.

**Comment by zero323** [comment]
Thanks @dongjoon-hyun @HyukjinKwon @srowen

**Pull request closed without merging**
