### PR TITLE
[SPARK-8713] Make codegen thread safe

### PR DESCRIPTION
**Pull request by davies**
Codegen takes three steps:
1. Take a list of expressions, convert them into Java source code and a list of expressions that don't not support codegen (fallback to interpret mode).
2. Compile the Java source into Java class (bytecode)
3. Using the Java class and the list of expression to build a Projection.

Currently, we cache the whole three steps, the key is a list of expression, result is projection. Because some of expressions (which may not thread-safe, for example, Random) will be hold by the Projection, the projection maybe not thread safe.

This PR change to only cache the second step, then we can build projection using codegen even some expressions are not thread-safe, because the cache will not hold any expression anymore.

cc @marmbrus @rxin @JoshRosen

### CODE REVIEW

**Comment by marmbrus** [comment]
LGTM.  To make sure I understand, this still requires that the caller passes in a new set of expression for each thread in order to be safe? (which I think we get for free due to the way deserialization happens)

**Comment by davies** [comment]
@marmbrus Yes.

**Comment by davies** [comment]
@JoshRosen Why it run all python tests?

**Comment by JoshRosen** [comment]
@davies, it ran all of the Python tests due to a small mistake that I overlooked when porting the Python test runner script to Python: the `pyspark-core` module still depends directly on `sql`, which causes any SQL change to trigger all Python changes.  @zsxwing noticed this as well and has a fix in his PR: https://github.com/apache/spark/pull/6830#discussion_r33477034

**Pull request closed without merging**
