### PR TITLE
SPARK-10262 Add @Since annotation to ml.attribute

### PR DESCRIPTION
**Pull request by ghost**
@Since annotations for ml.attribute. Most appear to belong 1.4.0 with several exceptions. Please review.

https://issues.apache.org/jira/browse/SPARK-10262

### CODE REVIEW

**Comment by srowen** [comment]
(Please give this a more complete title and description, as in the JIRA)

**Comment by mengxr** [comment]
@hucares This could be my fault. Do you see any non-`DeveloperApi` under `ml.attribute`?

**Comment by hucares** [comment]
@mengxr There are only `DeveloperApi` and now `Since` annotations under `ml.attribute`. I'm still pretty raw at Scala so I'm not sure why annotating a sealed abstract class creates a new class.

**Comment by srowen** [comment]
@hucares I think you can close this PR. As you say in the JIRA, there are no non-Developer non-private APIs in this package.

**Comment by mengxr** [comment]
I closed this PR. @hucares I'm sorry for not checking the API visibility when I created the JIRA. Please feel free to pick another starter task and I'm happy to walk you through the process of contributing to Spark.

**Pull request closed without merging**
