### PR TITLE
[SPARK-19409][BUILD] Bump parquet version to 1.8.2

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
## What changes were proposed in this pull request?

According to the discussion on #16281 which tried to upgrade toward Apache Parquet 1.9.0, Apache Spark community prefer to upgrade to 1.8.2 instead of 1.9.0. Now, Apache Parquet 1.8.2 is released officially last week on 26 Jan. We can use 1.8.2 now.

https://lists.apache.org/thread.html/af0c813f1419899289a336d96ec02b3bbeecaea23aa6ef69f435c142@%3Cdev.parquet.apache.org%3E

This PR only aims to bump Parquet version to 1.8.2. It didn't touch any other codes.

## How was this patch tested?

Pass the existing tests and also manually by doing `./dev/test-dependencies.sh`.

### CODE REVIEW

**Comment by viirya** [comment]
The dependency change looks clear.

**Review by srowen — APPROVED** [review]

**Comment by viirya** [comment]
LGTM too.

**Comment by rxin** [comment]
Merging in master.

**Comment by dongjoon-hyun** [comment]
Thank you for review and merging, @viirya , @srowen , and @rxin !

**Comment by mallman** [comment]
FYI, there are at least two workarounds in the Spark codebase which can potentially be removed as a consequence of this upgrade. For example:

https://github.com/apache/spark/blob/5de1737b02710e36f6804d2ae243d1aeb30a0b32/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetSchemaConverter.scala#L549-L558

and

https://github.com/apache/spark/blob/ca6391637212814b7c0bd14c434a6737da17b258/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetFilters.scala#L175-L178

These come immediately to mind. There may be others.

I think this PR would have been a good opportunity to remove these workarounds, but it's been closed and merged so that's water under the bridge.

**Comment by dongjoon-hyun** [comment]
Ya, @mallman .

However, with the same reason, I conclude to put them away from here. Exactly, the opposite direction of your opinion. If we try to fix all of them in a single shot, it will not merged for a long time.

At least, you can see #16756 starts already. I think those workarounds are going to be cleaned up soon if this commits are not reverted for some reason. :)

**Comment by rxin** [comment]
can you put rest of the cleanups in one place?

**Comment by dongjoon-hyun** [comment]
Hi, @rxin .
Sure, I'll try to put them in a single PR except the ongoing one.
BTW, every time, I noticed that committers have a better and broader perspective than me.
Do you have something more in mind beside those issues mentioned #16281 and here?

**Comment by robbinspg** [comment]
Since this commit our test runs are failing with
ParquetAvroCompatibilitySuite:

*** RUN ABORTED ***
  java.lang.NoClassDefFoundError: org/apache/avro/LogicalType
  at org.apache.parquet.avro.AvroParquetWriter.writeSupport(AvroParquetWriter.java:144)
  at org.apache.parquet.avro.AvroParquetWriter.access$100(AvroParquetWriter.java:35)
  at org.apache.parquet.avro.AvroParquetWriter$Builder.getWriteSupport(AvroParquetWriter.java:173)

Does the avro.version also need to be bumped to 1.8.x?

**Comment by dongjoon-hyun** [comment]
Thank you for informing that, @robbinspg .
Could you make a JIRA issue to keep track?
I'll investigate there.

**Comment by dongjoon-hyun** [comment]
BTW, is there any condition to reproduce that? At least, `sbt` seems not to complain like that.

```
$ build/sbt "project sql" "test-only *.ParquetAvroCompatibilitySuite"
...
[info] ParquetAvroCompatibilitySuite:
10:04:21.541 WARN org.apache.hadoop.util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[info] - required primitives (3 seconds, 937 milliseconds)
[info] - optional primitives (220 milliseconds)
[info] - non-nullable arrays (394 milliseconds)
[info] - nullable arrays (parquet-avro 1.7.0 does not properly support this) !!! IGNORED !!!
[info] - SPARK-10136 array of primitive array (231 milliseconds)
[info] - map of primitive array (259 milliseconds)
[info] - various complex types (418 milliseconds)
[info] - SPARK-9407 Push down predicates involving Parquet ENUM columns (288 milliseconds)
[info] ScalaCheck
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] Warning: Unknown ScalaCheck args provided: -oDF
[info] ScalaTest
[info] Run completed in 8 seconds, 762 milliseconds.
[info] Total number of tests run: 7
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 7, failed 0, canceled 0, ignored 1, pending 0
[info] All tests passed.
[info] Passed: Total 7, Failed 0, Errors 0, Passed 7, Ignored 1
[success] Total time: 283 s, completed Feb 3, 2017 10:04:32 AM
```

**Comment by dongjoon-hyun** [comment]
Ur, I reproduce that with maven test.
It's about test dependency on `parquet-avro` which now depends on `org.apache.avro` 1.8.0.

**Comment by robbinspg** [comment]
Sorry, I've been away for the w/end. Yes we use maven for our test runs. Looks like you have it under control.
Thanks

**Comment by srowen** [comment]
Pardon me, but is there anywhere else keeping track of the build break with SBT? It's been failing for a while in master: https://amplab.cs.berkeley.edu/jenkins/view/Spark%20QA%20Test%20(Dashboard)/job/spark-master-test-maven-hadoop-2.2/

I can have a look at it if nobody else is

**Comment by dongjoon-hyun** [comment]
Hi, @robbinspg and @srowen .
Could you review the PR #16795 for that?

**Pull request closed without merging**
