### PR TITLE
[MINOR][PYTHON] Use a helper in `PythonUtils` instead of direct accessing Scala package

### PR DESCRIPTION
**Pull request by HyukjinKwon**
## What changes were proposed in this pull request?

This PR proposes to use add a helper in `PythonUtils` instead of direct accessing Scala package.

## How was this patch tested?

Jenkins tests.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @squito and @felixcheung I am taking a look to reuse it first in a similar patch. Looks we better fix it whether it's reused or not.

**Comment by squito** [comment]
lgtm

**Comment by HyukjinKwon** [comment]
I am getting this in to other branches. Should be safe to go.

**Comment by HyukjinKwon** [comment]
Merged to master, branch-2.4 and branch-2.3.

**Pull request closed without merging**
