### PR TITLE
[SPARK-7118] [Python] Add the coalesce Spark SQL function available in PySpark

### PR DESCRIPTION
**Pull request by ogirardot**
This patch adds a proxy call from PySpark to the Spark SQL coalesce function and this patch comes out of a discussion on dev@spark with @rxin 

This contribution is my original work and i license the work to the project under the project's open source license.

Olivier.

### CODE REVIEW

**Comment by rxin** [comment]
Jenkins, test this please.

**Comment by rxin** [comment]
Jenkins, test this please.

**Comment by rxin** [comment]
Jenkins, test this please.

**Comment by rxin** [comment]
Jenkins, test this please.

**Comment by ogirardot** [comment]
Jenkins, pretty please :) ?

**Comment by rxin** [comment]
Jenkins really doesn't like coalesce. Maybe close this one and open a new one?

**Pull request closed without merging**
