### PR TITLE
[SPARK-30031][BUILD][SQL] Remove `hive-2.3` profile from `sql/hive` module

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to remove `hive-2.3` profile from `sql/hive` module.

### Why are the changes needed?

Currently, we need `-Phive-1.2` or `-Phive-2.3` additionally to build `hive` or `hive-thriftserver` module. Without specifying it, the build fails like the following. This PR will recover it.
```
$ build/mvn -DskipTests compile --pl sql/hive
...
[ERROR] [Error] /Users/dongjoon/APACHE/spark-merge/sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveExternalCatalog.scala:32: object serde is not a member of package org.apache.hadoop.hive
```

### Does this PR introduce any user-facing change?

No.

### How was this patch tested?

1. Pass GitHub Action dependency check with no manifest change.
2. Pass GitHub Action build for all combinations.
3. Pass the Jenkins UT.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Hi, @tgravescs , @srowen , @wangyum .
Could you review this PR, please?

**Comment by srowen** [comment]
So the point is that these dependencies are valid and necessary for both Hive versions? OK.

**Comment by dongjoon-hyun** [comment]
Yes. It does and we use `provided` dependency for `hive-1.2` profile.

**Review by tgravescs — APPROVED** [review]
changes lgtm. It now builds without the -Phive-2.3 profile

**Comment by dongjoon-hyun** [comment]
Thank you, @tgravescs !

**Comment by dongjoon-hyun** [comment]
I'll revise this PR a little bit more to be the same when we provide pre-built distributions.

**Comment by dongjoon-hyun** [comment]
Thank you, @tgravescs and @srowen . This passed Jenkins test previously. And, the last two commits about the scope and renaming are tested with GitHub Actions. I'll merged this to master.

**Pull request closed without merging**
