### PR TITLE
[STREAMING][MINOR] Fix a duplicate "be" in comments

### PR DESCRIPTION
**Pull request by lw-lin**

### CODE REVIEW

**Comment by lw-lin** [comment]
@rxin @zsxwing Would you take a look when you have time? Thanks!

**Comment by srowen** [comment]
@lw-lin it's not worth bothering with a PR for something this trivial. Consider running a bigger check for misspelling etc if you're going to. This still costs like an hour of attention across everyone just to process it.

**Comment by lw-lin** [comment]
Sure, I'll close this for now. Thanks for your time!

**Comment by rxin** [comment]
Thanks the PR is already here I've merged it. 

@lw-lin in the future please batch more fixes like this. Thanks.

**Comment by lw-lin** [comment]
Sure. @rxin thank you for your review and patient guidance!

**Pull request closed without merging**
