### PR TITLE
[SPARK-49731][K8S] Support K8s volume `mount.subPathExpr` and `hostPath` volume `type`

### PR DESCRIPTION
**Pull request by EnricoMi**
### What changes were proposed in this pull request?
Add the following config options:
- `spark.kubernetes.executor.volumes.[VolumeType].[VolumeName].mount.subPathExpr`
- `spark.kubernetes.executor.volumes.hostPath.[VolumeName].options.type`

### Why are the changes needed?

K8s Spec
- https://kubernetes.io/docs/concepts/storage/volumes/#hostpath-volume-types
- https://kubernetes.io/docs/concepts/storage/volumes/#using-subpath-expanded-environment

These are natural extensions of the existing options
- `spark.kubernetes.executor.volumes.[VolumeType].[VolumeName].mount.subPath`
- `spark.kubernetes.executor.volumes.hostPath.[VolumeName].options.path`

### Does this PR introduce _any_ user-facing change?
Above config options.

### How was this patch tested?
Unit tests

### Was this patch authored or co-authored using generative AI tooling?
No

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Thank you, @EnricoMi . The PR looks good.

Could you add a test coverage for this? What happens when we add both? I believe it would be prevented by error before submitting the jobs to the K8s cluster, @EnricoMi .
- https://kubernetes.io/docs/concepts/storage/volumes/#using-subpath-expanded-environment
> The subPath and subPathExpr properties are mutually exclusive.

**Comment by dongjoon-hyun** [comment]
Also, I revised the PR description by adding K8s reference links because this is a community patch.

**Comment by EnricoMi** [comment]
I have added a check for `subPath` and `subPathExpr` not being set together to provide a useful error message early (noting the exact Spark config key cases the failure).

**Comment by EnricoMi** [comment]
> Could you add a test coverage for this?

I have added more tests.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you so much, @EnricoMi .
Merged to master for Apache Spark 4.0.0.

**Pull request closed without merging**
