### PR TITLE
[MINOR][PYTHON] Use `_memory_limit` to get worker memory conf in `rdd.py`

### PR DESCRIPTION
**Pull request by WangGuangxin**
## What changes were proposed in this pull request?

Replace duplicate code by function `_memory_limit`

## How was this patch tested?

Existing UTs

### CODE REVIEW

**Comment by WangGuangxin** [comment]
cc @HyukjinKwon

**Comment by dongjoon-hyun** [comment]
ok to test

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
Hi, @WangGuangxin . According to the commit history, this can be applied to `branch-2.4/2.3`. Could you make a JIRA issue and use it for traceability?

**Comment by dongjoon-hyun** [comment]
Hmm. Never mind. Let's consider only `master` branch.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Merged to master. Thank you, @WangGuangxin .

**Pull request closed without merging**
