### PR TITLE
[MINOR][PySpark][DOC] Fix wrongly formatted examples in PySpark documentation

### PR DESCRIPTION
**Pull request by HyukjinKwon**
## What changes were proposed in this pull request?

This PR fixes wrongly formatted examples in PySpark documentation as below:
- **`SparkSession`**
  - **Before**
    
    
  - **After**
    
    
- **`Builder`**
  - **Before**
    
  - **After**
    

This PR also fixes several similar instances across the documentation in `sql` PySpark module.
## How was this patch tested?

N/A

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Oh, I will fix them up soon.

**Comment by rxin** [comment]
Can you verify the output after the all the follow-up commits?

**Comment by HyukjinKwon** [comment]
Sure, It seems the output for nested class is varied by the version of Python.

First, I updated this to `<pyspark.sql.session.SparkSession.Builder object at ...>` and got this error below with `pypy`:

```python
Expected:
    <pyspark.sql.session.SparkSession.Builder object at ...>
Got:
    <pyspark.sql.session.Builder object at 0x000000000163e4b8>
```

then I updated this to  `<pyspark.sql.session.Builder object at ...>` and got this error below with `python 3.4`:

```python
Expected:
    <pyspark.sql.session.Builder object at ...>
Got:
    <pyspark.sql.session.SparkSession.Builder object at 0x7f8c5657d9e8>
```


I tested this with Python 2.7 and 3.4 with this module below:

- `test.py`

```
class SparkSession(object):
    class Builder(object):
        pass
    builder = Builder()
```

- Python 2.7 shell

```python
>>> from test import SparkSession
>>> SparkSession.builder
<test.Builder object at 0x7fa9224fa650>
```

- Python 3.4 shell

```python
>>> from test import SparkSession
>>> SparkSession.builder
<test.SparkSession.Builder object at 0x7f11e79e18d0>
```

**Comment by rxin** [comment]
Output is fine -- I just want to make sure the doc is correct.

**Comment by HyukjinKwon** [comment]
Ah, yes it seems fine.

**Comment by rxin** [comment]
Can you scan the Python docs and see if there are more instances?

http://people.apache.org/~pwendell/spark-releases/spark-2.0.0-rc2-docs/api/python/pyspark.sql.html

I found at least one ...

**Comment by HyukjinKwon** [comment]
Sure!

**Comment by HyukjinKwon** [comment]
I just double-checked the built documentation after the last commit. Do you want me to give a pass for other modules (maybe in another PR)?

**Comment by rxin** [comment]
If you can please check other modules too. Thanks!

**Comment by HyukjinKwon** [comment]
Sure! Thanks.

**Comment by HyukjinKwon** [comment]
@rxin It seems theses are all instances related with this (I can't believe!). I just simply corrected indentation for a doc-test in `mllib`.

**Comment by rxin** [comment]
Merging in master/2.0. Thanks.

**Pull request closed without merging**
