### PR TITLE
[SPARK-15475][SQL] Add tests for writing and reading back empty data for Parquet, Json and Text data sources

### PR DESCRIPTION
**Pull request by HyukjinKwon**
## What changes were proposed in this pull request?

This PR adds the tests for writing and reading back empty data for Parquet, JSON and Text data sources.

The tests were not added in `HadoopFsRelationTest` because each test is a little bit different due to the differences among those data sources.
- JSON dose not write schema when it is empty.
- TEXT needs a `dataSchema` option
- Parquet writes schema when it is empty.
## How was this patch tested?

Unit tests in `ParquetHadoopFsRelationSuite`, `JsonHadoopFsRelationSuite`and `SimpleTextHadoopFsRelationSuite`.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
Hi @rxin and @marmbrus,
As you already know a "critical" issue was found here, [SPARK-15393](https://issues.apache.org/jira/browse/SPARK-15393). So, [SPARK-10216](https://issues.apache.org/jira/browse/SPARK-10216) was reverted. It seems writing and reading empty data back were not tested across data sources. This PR includes the test which resembles the one provided in the JIRA ticket. Could you please take a look?

**Comment by rxin** [comment]
Did we ever end up fixing https://issues.apache.org/jira/browse/SPARK-10216 after it was reverted?

**Comment by HyukjinKwon** [comment]
@rxin No. it has not been fixed.. So, I wanted to add some test codes first to check writing and reading empty data to make sure this is working first.

The way to fix [SPARK-10216](https://issues.apache.org/jira/browse/SPARK-10216) might be varied if they are a data-source specific issue. For example, ORC does not allow to write empty data, [SPARK-8501](https://issues.apache.org/jira/browse/SPARK-8501)..

So, I thought I can focus on fixing [SPARK-10216](https://issues.apache.org/jira/browse/SPARK-10216) within Parquet if [SPARK-15393](https://issues.apache.org/jira/browse/SPARK-15393) is a Parquet datasource specific problem.

**Comment by HyukjinKwon** [comment]
I don't mind closing this. I will close if you think so. I can do this together later with [SPARK-10216](https://issues.apache.org/jira/browse/SPARK-10216). 

I just want to be sure writing and reading empty files should be supported for all or some of them, for example, maybe only Parquet,  ORC and CSV because they can write schema separately even if the data is empty.

**Comment by rxin** [comment]
Yea let's just do it together. Thanks.

**Comment by HyukjinKwon** [comment]
Closing this. But could I please ask if it is basically perfered to support to wrtie and read empty data back for all data sources and others (or maybe Parquet, ORC and CSV)?

I just want to be sure on that and want to tes during fixing that.

**Comment by rxin** [comment]
Yes definitely want to be able to read/write empty dfs.

**Comment by HyukjinKwon** [comment]
@rxin Thank you!

**Pull request closed without merging**
