### PR TITLE
[SPARK-24262][Python] Fix typo in UDF type match error message

### PR DESCRIPTION
**Pull request by robinske**
## What changes were proposed in this pull request?

Updates `functon` to `function`. This was called out in @holdenk's PyCon 2018 conference talk. Didn't see any existing PR's for this.

@holdenk happy to fix the Pandas.Series bug too but will need a bit more guidance.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
It's okay but mind quickly checking other typos around this place while we are here?

**Comment by robinske** [comment]
Looked through the other text/error messages and didn't see any other typos jump out.

**Comment by HyukjinKwon** [comment]
ok to test

**Review by HyukjinKwon — APPROVED** [review]
LGTM

**Comment by holdenk** [comment]
LGTM, @robinske & I are hanging out in the United lounge so were just going to merge this now.

**Pull request closed without merging**
