### PR TITLE
[SPARK-45949][INFRA] Upgrade `pyarrow` to 14

### PR DESCRIPTION
**Pull request by zhengruifeng**
### What changes were proposed in this pull request?
Upgrade `pyarrow` to 14

### Why are the changes needed?
test with the latest version of `pyarrow`

### Does this PR introduce _any_ user-facing change?
no

### How was this patch tested?
ci

### Was this patch authored or co-authored using generative AI tooling?
no

### CODE REVIEW

**Comment by zhengruifeng** [comment]
```
pyarrow                  14.0.1
pydantic                 2.5.1
pydantic_core            2.14.3
PyGObject                3.36.0
```

**Review by HyukjinKwon — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by dongjoon-hyun** [comment]
Merged to master. Thank you, @zhengruifeng and @HyukjinKwon .

**Comment by zhengruifeng** [comment]
@dongjoon-hyun @HyukjinKwon thanks for reviews

**Pull request closed without merging**
