### PR TITLE
[SPARK-12021][Streaming][Tests]Fix the potential dead-lock in StreamingListenerSuite

### PR DESCRIPTION
**Pull request by zsxwing**
In StreamingListenerSuite."don't call ssc.stop in listener", after the main thread calls `ssc.stop()`,  `StreamingContextStoppingCollector` may call  `ssc.stop()` in the listener bus thread, which is a dead-lock. This PR updated `StreamingContextStoppingCollector` to only call `ssc.stop()` in the first batch to avoid the dead-lock.

### CODE REVIEW

**Comment by zsxwing** [comment]
cc @tdas @tedyu @andrewor14 

BTW, there is a similar test in SparkListenerSuite. But SparkContext doesn't hold a lock in `stop` method,  it won't be a problem.

**Comment by zsxwing** [comment]
retest this please

**Comment by tedyu** [comment]
Thanks for the quick fix, shixiong

Happy Thanksgiving

**Comment by zsxwing** [comment]
I saw this issue in several PR builds. I'm going to merge this one because it only touches the test codes and it bores other people.

**Comment by zsxwing** [comment]
@tedyu Happy Thanksgiving, too :)

**Comment by CodingCat** [comment]
Thanks, @zsxwing, at least it works for my PR

**Pull request closed without merging**
