### PR TITLE
[MINOR][DOC] Fix the link of 'Getting Started'

### PR DESCRIPTION
**Pull request by mcavdar**
## What changes were proposed in this pull request?

Easy fix in the link. 

## How was this patch tested?

Tested manually

### CODE REVIEW

**Comment by srowen** [comment]
This is fine @mcavdar . While we're at it, there's a link to https://mesos.apache.org/documentation/latest/mesos-frameworks/ that looks dead too -- do you know where that goes?

Also -- just a pet peeve of mine -- I think we can use HTTPS URLs wherever supported. Not worth changing for its own sake, but might be worth it if changing these links for other reasons.

And you're welcome to run a link checker to discover more dead links. I know there are more.

**Comment by mcavdar** [comment]
It has already been fixed. https://github.com/apache/spark/commit/01f183e8497d4931f1fe5c69ff16fe84b1e41492
I'm running a link checker to find and fix more.

**Comment by HyukjinKwon** [comment]
Oh, maybe it's not quite related but do you mind if I ask to fix the below too?

https://github.com/apache/spark/blob/ccdf21f56e4ff5497d7770dcbee2f7a60bb9e3a7/docs/sql-programming-guide.md#L501-L504

to (just adding a newline)

```
 </div> 
 </div> 

 ### Run SQL on files directly 
```

because it currently breaks doc rendering as below:

**Comment by mcavdar** [comment]
@srowen [Here](https://github.com/mcavdar/NLP/blob/master/Broken%20Links/spark/spark_404links.txt) is all broken links, it may be useful. Each line contains broken link and parent page (separated by tab). About 75-100 broken links are related to "http(s)://spark.apache.org/docs/latest".

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
