### PR TITLE
[MINOR][TESTS] Remove unused test jar (udf_noA.jar)

### PR DESCRIPTION
**Pull request by HyukjinKwon**
### What changes were proposed in this pull request?

This jar was added in https://github.com/apache/spark/pull/42069 but moved in https://github.com/apache/spark/pull/43735.

### Why are the changes needed?

To clean up a jar not used.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Existing tests should check

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
@grundprinzip would you mind taking a look and trying to merge this PR :-)?

**Review by grundprinzip — APPROVED** [review]

**Comment by grundprinzip** [comment]
Merging

**Comment by HyukjinKwon** [comment]
Oops, sorry I told him wrongly about merging a PR. I reverted and opened a new PR: https://github.com/apache/spark/pull/47315

**Comment by dongjoon-hyun** [comment]
😄  Ya, this is the 7th instance.
- https://github.com/apache/spark/pulls?q=is%3Apr+is%3Aclosed+is%3Amerged

Given that the last one was last year, this is an annual event.
- #43188

Do you think we need to prevent this kind of mistake by updating our committer docs or changing the following rule?

https://github.com/apache/spark/blob/3923d7f8fcafb86fcbffcedf4215a314fe5b4011/.asf.yaml#L30-L33

**Comment by grundprinzip** [comment]
Conceptually yes, but I wanted to spend some time understanding the delta between the merge button and the script and how GH might have changed in between. One idea would be to use a GH action for the script as well that triggers by a keyword for example so that one does not always need to push directly from a local machine.

**Comment by HyukjinKwon** [comment]
Yeah I think we should block it merge button

**Pull request merged**
