### PR TITLE
[SPARK-18754][SS] Rename recentProgresses to recentProgress

### PR DESCRIPTION
**Pull request by marmbrus**
Based on an informal survey, users find this option easier to understand / remember.

### CODE REVIEW

**Comment by tdas** [comment]
LGTM.

**Comment by tdas** [comment]
retest this please.

**Comment by tdas** [comment]
retest this please

**Comment by zsxwing** [comment]
retest this please

**Comment by tdas** [comment]
Merging this to master and 2.1

**Pull request closed without merging**
