### PR TITLE
[SPARK-42947][SQL] Spark Thriftserver LDAP should not use DN pattern if user contains domain

### PR DESCRIPTION
**Pull request by liujiayi771**
### What changes were proposed in this pull request?
Fixed the problem that LDAP authentication cannot be performed correctly when the domain parameter is passed in. For example, Spark Thrift Server will encounter this problem when using Active Directory and passing domain for LDAP authentication.

### Why are the changes needed?
When the LDAP provider has domain configuration, such as Active Directory, the principal should not be constructed according to the DN pattern, but the user containing the domain should be directly passed to the LDAP provider as the principal.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Existing test.

### CODE REVIEW

**Comment by liujiayi771** [comment]
@srowen Can you help review this PR? We found this problem in the use of connecting AD for authentication. This problem is very similar to [36784](https://github.com/apache/spark/pull/36784), because STS LDAP authentication lacks some functions.

**Comment by srowen** [comment]
It's hard to make out the change because you moved the code. What is the important change?

**Comment by LuciferYang** [comment]
Was this file originally copied from hive? Is there a corresponding fix in the hive?

**Comment by LuciferYang** [comment]
> Was this file originally copied from hive? Is there a corresponding fix in the hive?

difficult to synchronize, this file has changed too much in hive

**Comment by liujiayi771** [comment]
> It's hard to make out the change because you moved the code. What is the important change?

The original code will continue to construct principals according to the DN pattern after processing the domain. After I modify it, when encountering a domain, it will no longer go to the logic of the DN pattern, and the createCandidatePrincipals function will return directly.

**Comment by liujiayi771** [comment]
> > Was this file originally copied from hive? Is there a corresponding fix in the hive?
> 
> difficult to synchronize, this file has changed too much in hive

You can check this file.   [public static List<String> createCandidatePrincipals(HiveConf conf, String user) {](https://github.com/apache/hive/blob/4d21ba11c893038dbecd98c512a81ccf1d4fc6d0/service/src/java/org/apache/hive/service/auth/ldap/LdapUtils.java#L203)

**Comment by liujiayi771** [comment]
I think the community needs to fully synchronize the latest code of hive in the end, but at present this PR can solve LDAP authentication including domain.

**Comment by pan3793** [comment]
The major LDAP enhancement in Apache Hive occurred in HIVE-14713, which also brought UT. There is a Scala version porting in Apache Kyuubi https://github.com/apache/kyuubi/pull/4152. If wanted, I can contribute those parts to Spark, the change should be similar w/ Kyuubi.

**Review by dongjoon-hyun — COMMENTED** [review]
cc @sunchao too

**Comment by liujiayi771** [comment]
> cc @sunchao too

Can this modification be merged?

**Pull request closed without merging**
