### PR TITLE
[SPARK-35619][ML] Refactor LinearRegression - make huber support virtual centering

### PR DESCRIPTION
**Pull request by zhengruifeng**
### What changes were proposed in this pull request?
1, for huber, make it support virtual centering
2, for `LeastSquares`, it was impled in this way: optimize the linear part and then estimate the intercept. So just re-org the its agg and suite to keep in line with other aggs.

### Why are the changes needed?
for better convergence

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
existing and newly added testsuites

### CODE REVIEW

**Comment by zhengruifeng** [comment]
friendly ping @srowen  @WeichenXu123

**Review by srowen — COMMENTED** [review]
Seems fine. Do you want to change more in one PR? separate ones are OK.

**Comment by zhengruifeng** [comment]
This should be the last PR related to virtual centering. I will refactor some common block in following PRs.

**Review by srowen — APPROVED** [review]
Seems OK to merge

**Comment by zhengruifeng** [comment]
Merged to master, thanks @srowen for reviewing!

**Pull request closed without merging**
