### PR TITLE
[SPARK-40231][SQL][TEST] Add 1TB TPCDS Plan stability tests

### PR DESCRIPTION
**Pull request by mskapilks**
### What changes were proposed in this pull request?
Add 1TB (sf=1000) TPCDS plan stability tests.

### Why are the changes needed?
1TB scale TPCDS dataset is used frequently to measure performance improvement. This would make it easier to see the impact of any SQL optimization in terms of plan changes.

The table stats are generated from this script https://gist.github.com/maropu/f553d32c323ee803d39e2f7fa0b5a8c3

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Tests only

### CODE REVIEW

**Comment by LuciferYang** [comment]
How long does the 1TB TPCDS test take?

**Comment by mskapilks** [comment]
> How long does the 1TB TPCDS test take?

@LuciferYang The test run in build took `34328` ms for **1.4** and `17138` ms for **2.7** TPCDS

**Comment by mskapilks** [comment]
cc: @dongjoon-hyun

**Comment by wangyum** [comment]
Personally I don't think it's meaningful.

**Comment by kazuyukitanimura** [comment]
Thanks for the ping. Would you mind providing the context a bit more? E.g. what problems we are trying to solve, why the existing plan stability tests are not good enough, etc...

**Pull request closed without merging**
