### PR TITLE
[SPARK-11301][SQL] fix case sensitivity for filter on partitioned columns

### PR DESCRIPTION
**Pull request by cloud-fan**

### CODE REVIEW

**Comment by cloud-fan** [comment]
cc @liancheng

**Comment by yhuai** [comment]
test this please

**Comment by yhuai** [comment]
@cloud-fan Seems we also need to fix it in branch 1.5?

**Comment by yhuai** [comment]
LGTM. Merging to master. Looks it will not apply cleanly with 1.5 branch. Can you have a separate pr for 1.5 branch?

**Comment by cloud-fan** [comment]
This part of code has been changed a lot by https://github.com/apache/spark/pull/8916/files , should we backport that too?

**Comment by yhuai** [comment]
@cloud-fan Seems not very hard to back port #8916 as well. How about we have a pr against 1.5 to include both #8916 and this one?

**Pull request closed without merging**
