### PR TITLE
[SPARK-8322][EC2] Added spark 1.4.0 into the VALID_SPARK_VERSIONS and…

### PR DESCRIPTION
**Pull request by markmsmith**
… SPARK_TACHYON_MAP

This contribution is my original work and I license the work to the project under the project's open source license.

### CODE REVIEW

**Comment by shivaram** [comment]
Jenkins, ok to test

**Comment by shivaram** [comment]
@markmsmith thanks for the PR. However I am not sure the tachyon mapping is correct. If I am reading it correctly it looks like 1.4 depends on 0.6.4 https://github.com/apache/spark/blob/branch-1.4/core/pom.xml#L293

cc @haoyuan @calvinjia who might know more about tachyon

**Comment by markmsmith** [comment]
Good catch, I'll update and re-push.

**Comment by calvinjia** [comment]
@shivaram 
Yup, Spark 1.4 -> Tachyon 0.6.4.

**Comment by shivaram** [comment]
LGTM. Merging this

**Pull request closed without merging**
