### PR TITLE
[SPARK-33473][SQL] Extend interpreted subexpression elimination to other interpreted projections

### PR DESCRIPTION
**Pull request by viirya**
### What changes were proposed in this pull request?

Similar to `InterpretedUnsafeProjection`, this patch proposes to extend interpreted subexpression elimination to `InterpretedMutableProjection` and `InterpretedSafeProjection`.

### Why are the changes needed?

Enabling subexpression elimination can improve the performance of interpreted projections, as shown in `InterpretedUnsafeProjection`.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Unit test.

### CODE REVIEW

**Comment by maropu** [comment]
Looks fine if the tests pass.

**Comment by viirya** [comment]
retest this please

**Comment by viirya** [comment]
retest this please

**Review by maropu — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @viirya and @maropu .
Merged to master for Apache Spark 3.1.

**Comment by viirya** [comment]
Thanks @maropu @dongjoon-hyun

**Pull request closed without merging**
