### PR TITLE
[SPARK-32937][SPARK-32980][K8S] Fix decom & launcher tests and add some comments to reduce chance of breakage 

### PR DESCRIPTION
**Pull request by holdenk**
### What changes were proposed in this pull request?

Fixes the log strings the decom integration tests looks for and add comments reminding people to run the K8s integration tests when changing those code paths.

### Why are the changes needed?

The strings it looks for have been changed.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

WIP: Verify that the K8s jenkins job succeeds

### CODE REVIEW

**Comment by holdenk** [comment]
Jenkins retest this please.

**Comment by holdenk** [comment]
So The test failure is for `- Launcher client dependencies *** FAILED ***` but the decommissioning test is passing.

**Comment by holdenk** [comment]
cc @Ngone51 @HyukjinKwon @ScrapCodes @dongjoon-hyun

**Comment by holdenk** [comment]
jenkins retest this please

**Comment by dongjoon-hyun** [comment]
Thank you, @holdenk !  Let's see K8s IT result.

**Comment by dongjoon-hyun** [comment]
Yes! Finally, it passed.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @holdenk !

**Comment by dongjoon-hyun** [comment]
Merged to master because it recovers K8s IT and unblocks K8s module.

**Comment by HyukjinKwon** [comment]
Thanks @holdenk and @dongjoon-hyun

**Comment by HyukjinKwon** [comment]
@holdenk, BTW which PR caused this failure? It's a bit odd that we fix a test as a followup here whereas you ask to revert at https://github.com/apache/spark/pull/29722#issuecomment-695517007 https://github.com/apache/spark/pull/29722#issuecomment-695517162

**Comment by holdenk** [comment]
So the launcher tests were broken by a new version of mini kube being released, it wasn’t broken by any specific PR (except maybe arguably the original PR adding integration tests). 

As for the revert, that PR was indeed breaking the test suite and had an incompatible change, I asked for it to be reverted but it turned out that folks have not been running that suite for awhile (a mistake I myself have made), so it there were multiple breaking changes and I decided that since it had been proposed to re-merge code with a broken test suite we would be better served by me focusing on fixing the test suite to unblock everyone.

If you think this is not a reasonable course of action please bring it up with the PMC.

**Pull request closed without merging**
