### PR TITLE
[SPARK-28325][SQL]Support ANSI SQL: SIMILAR TO ... ESCAPE syntax

### PR DESCRIPTION
**Pull request by beliefer**
### What changes were proposed in this pull request?
This PR migrate to https://github.com/apache/spark/pull/27432
`[ NOT ] SIMILAR TO <similar pattern> [ ESCAPE <escape character> ]`
This is a ANSI SQL.
For example:
```
SELECT 'abc' SIMILAR TO 'abc' AS `true`;
SELECT 'abc' SIMILAR TO 'a' AS `false`;
SELECT 'abc' SIMILAR TO '%(b|d)%' AS `true`;
SELECT 'abc' SIMILAR TO '(b|c)%' AS `false`;
```
There are some mainstream database support the syntax.
**PostgreSQL:**
https://www.postgresql.org/docs/current/functions-matching.html#FUNCTIONS-SIMILARTO-REGEXP
**Redshift:**
https://docs.aws.amazon.com/redshift/latest/dg/pattern-matching-conditions-similar-to.html

`SIMILAR TO` is similar to `RLIKE`, but with the following differences:
       1. The `SIMILAR TO` operator returns true only if its pattern matches the entire string,
          unlike `RLIKE` behavior, where the pattern can match any portion of the string.
       2. The regex string allow uses _ and % as wildcard characters denoting any single character
          and any string, respectively (these are comparable to . and .* in POSIX regular
          expressions).
       3. The regex string allow uses escape character like `LIKE` behavior.
       4. '.', '^' and '$' is not a meta character for `SIMILAR TO`.
### Why are the changes needed?
No

### Does this PR introduce any user-facing change?
No

### How was this patch tested?
new UT.

### CODE REVIEW

**Comment by maropu** [comment]
Can you check more, e.g., oracle and mysql, too?

**Comment by beliefer** [comment]
> Can you check more, e.g., oracle and mysql, too?

I checked oracle and mysql, they are not support this syntax.

**Comment by maropu** [comment]
The standard though, is this syntax useful for users? (I didn't know this syntax..) cc: @gatorsmile @cloud-fan

**Comment by beliefer** [comment]
@maropu I think this syntax is useful in two points: one is that `RLIKE` does not support `_` and `%` as wildcards, and `SIMILAR TO` makes it more convenient for users; the other is that `RLIKE` does not support escape char. In some cases, `SIMILAR TO` will also more convenient for users.
In addition, in terms of code changes, there is no actual change in the code of `RLIKE` and `LIKE`, but more than 20 new lines of code have been added.

**Pull request closed without merging**
