### PR TITLE
[SPARK-32321][SS] Remove KAFKA-7703 workaround

### PR DESCRIPTION
**Pull request by gaborgsomogyi**
### What changes were proposed in this pull request?
[KAFKA-7703](https://issues.apache.org/jira/browse/KAFKA-7703) has been discovered and a workaround has been added in SPARK-26267. At that time Spark was using 2.0.0 `kafka-clients` library and the issue was resolved in 2.3.0. Now Spark uses 2.5.0 `kafka-clients` library which allows us to remove the workaround. SPARK-26267 has added multiple things to address this issue:
* Called `position` right after `poll` function which blocks until `poll` result is available
* Introduced a safety logic to make sure positions seen in previous batch are smaller or equals to the newly acquired offsets from Kafka. If this assumption not applies retry happens.

To be on the safe side and detect bugs similar to [KAFKA-7703](https://issues.apache.org/jira/browse/KAFKA-7703) only the first change is removed in this PR. This means if any similar issue may appear retry still happens to correct latest offsets.

### Why are the changes needed?
[KAFKA-7703](https://issues.apache.org/jira/browse/KAFKA-7703) resolved and no workaround needed.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
* Existing unit tests.
* Crafted a special test with sleeps [here](https://github.com/gaborgsomogyi/kafka/commit/466cbbf9cc09c39390409b7675bc1e48bc265e5c).
This is the 2.5.0 adaptation of @zsxwing reproduction code created [here](https://github.com/zsxwing/kafka/commit/4e1aa11bfa99a38ac1e2cb0872c055db56b33246).

### CODE REVIEW

**Comment by srowen** [comment]
Sounds reasonable; I suppose we cannot reasonably support users who downgrade the kafka client.

**Comment by gaborgsomogyi** [comment]
> we cannot reasonably support users who downgrade the kafka client

Definitely not since it may bring in old issues.
[Here](https://gist.github.com/gaborgsomogyi/3476c32d69ff2087ed5d7d031653c7a9) I've collected Spark related `kafka-clients` dependencies.

**Comment by dongjoon-hyun** [comment]
cc @HeartSaVioR

**Comment by HeartSaVioR** [comment]
This looks reasonable to me as well - as there has been two safety guards and even with this patch there's still one safety guard. In worst case (if Kafka client encounters KAFKA-7703-like issue in all trials) it can still make a difference, but even we don't have a strong faith of Kafka client we don't tend to believe Kafka client provides wrong value consistently. With reasonable count of retrial it shouldn't matter.

I'd still like to see @zsxwing voice on this, as he looks to be the one struggled with Kafka client bugs.

**Comment by zsxwing** [comment]
Thanks for raising the PR. Could you clarify what's the cost to keep this?

I believe KAFKA-7703 has been fixed since you have verified it using my reproduction codes. However I'd be more conservative. Although I did report KAFKA-7703, I didn't have any evidence that this was exactly the issue we hit in production, or that was the only possible issue. There were no enough logs to prove it unfortunately. What I know is the workaround we patched in Spark did prevent Kafka consumer from reporting incorrect offsets, but it could hide other potential unknown issues.

Currently there is no Spark release using Kafka 2.5.0, so I don't feel confident that there are no other unknown issues causing the same incorrect offset issue. If the cost to keep this workaround is minor, can we wait until a Spark release using Kafka 2.5.0 is out for a while? Once there is a Spark release available and people start to use it, I can look at our internal logs to see if the warning log in `fetchLatestOffsets` is really gone, which will be an evidence to prove KAFKA-7703 is likely the only issue.

**Comment by gaborgsomogyi** [comment]
I think this is conservative enough since retry still happens and now we're speaking about potential issues which has been never reported but I see your point, closing it.
The intention here is to simplify the offset reader because it's not easy to solve SPARK-32032. The more compact the consumer usage is the easier to discuss it through w/ the Kafka guys. My point is not solving and/or delaying to solve SPARK-32032 is at least that severe just like this one (when SPARK-32032 hits then the whole query stops and there is no workaround).

**Pull request closed without merging**
