### PR TITLE
[SPARK-25867][ML] Remove KMeans computeCost

### PR DESCRIPTION
**Pull request by mgaido91**
## What changes were proposed in this pull request?

The PR removes the deprecated method `computeCost` of `KMeans`.

## How was this patch tested?

NA

### CODE REVIEW

**Comment by mgaido91** [comment]
retest this please

**Comment by mgaido91** [comment]
cc @holdenk @srowen

**Comment by mgaido91** [comment]
any commetn on this @srowen @holdenk ?

**Comment by mgaido91** [comment]
retest this please

**Review by srowen — CHANGES_REQUESTED** [review]
Just grepping for computeCost -- do any examples need updating? I see some instances but they may be a different computeCost.

But what about BisectingKMeans too?

**Comment by mgaido91** [comment]
Yes, the problem is that there is also the `computeCost` of `BisectingKMeans`. I proposed to deprecate it in 2.4 and remove in 3.0, but I didn't manage to have it done for 2.4 (please refer to the discussions on https://github.com/apache/spark/pull/22764 and https://github.com/apache/spark/pull/22756 for the details). So `computeCost` of `BisectingKMeans` cannot be removed in 3.0 (unfortunately). The examples for KMeans have already been updated using ClusteringEvaluator in #19676.

**Comment by srowen** [comment]
How about BisecingKMeansModel? That's what I was looking at. That computeCost is also deprecated.

**Comment by mgaido91** [comment]
Yes, it was deprecated in #22756 and it is deprecated since 3.0, so we cannot remove it...

**Comment by srowen** [comment]
Ah OK I wasn't reading that carefully.

**Review by srowen — APPROVED** [review]
Apologies for the merge conflict now, but looks OK otherwise.

**Comment by mgaido91** [comment]
retest this please

**Comment by mgaido91** [comment]
retest this please

**Review by srowen — APPROVED** [review]
OK by me; apologies for another rebase though. We're merging lots of changes that need MiMa exclusions and it keeps conflicting.

**Comment by mgaido91** [comment]
sure, thanks @srowen , no need to apologize at all, thanks for your help reviewing this.

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
