### PR TITLE
[SPARK-26677][BUILD] Update Parquet to 1.10.1 with notEq pushdown fix.

### PR DESCRIPTION
**Pull request by rdblue**
## What changes were proposed in this pull request?

Update to Parquet Java 1.10.1.

## How was this patch tested?

Added a test from @HyukjinKwon that validates the notEq case from SPARK-26677.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Hi, @rdblue . Shall we try with maven?
```
sbt.ResolveException: unresolved dependency: org.apache.parquet#parquet-column;1.10.1: not found
unresolved dependency: org.apache.parquet#parquet-hadoop;1.10.1: not found
unresolved dependency: org.apache.parquet#parquet-avro;1.10.1: not found
```

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by dongjoon-hyun** [comment]
We had better to add @HyukjinKwon 's test case here. (https://github.com/apache/spark/pull/23622)
```scala
  test("SPARK-26677: negated null-safe equality comparison should not filter matched row groups") {
    (true :: false :: Nil).foreach { vectorized =>
      withSQLConf(SQLConf.PARQUET_VECTORIZED_READER_ENABLED.key -> vectorized.toString) {
        withTempPath { path =>
          // Repeated values for dictionary encoding.
          Seq(Some("A"), Some("A"), None).toDF.repartition(1)
            .write.parquet(path.getAbsolutePath)
          val df = spark.read.parquet(path.getAbsolutePath)
          checkAnswer(stripSparkFilter(df.where("NOT (value <=> 'A')")), df)
        }
      }
    }
  }
```
cc @gatorsmile , @HyukjinKwon

**Comment by rdblue** [comment]
Retest this please.

**Comment by dongjoon-hyun** [comment]
The same irrelevant failures. Retest this please.
```
[ERROR] Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 60.065 s <<< FAILURE! - in org.apache.spark.network.ChunkFetchIntegrationSuite
[ERROR] fetchBothChunks(org.apache.spark.network.ChunkFetchIntegrationSuite)  Time elapsed: 60.01 s  <<< FAILURE!
java.lang.AssertionError: Timeout getting response from the server
	at org.apache.spark.network.ChunkFetchIntegrationSuite.fetchChunks(ChunkFetchIntegrationSuite.java:176)
	at org.apache.spark.network.ChunkFetchIntegrationSuite.fetchBothChunks(ChunkFetchIntegrationSuite.java:210)
```

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by dongjoon-hyun** [comment]
Unfortunately, every run goes to `amp-jenkins-worker-05` and fails with the same flaky test (https://github.com/apache/spark/pull/23700).

**Comment by rdblue** [comment]
@dongjoon-hyun, @HyukjinKwon, I've removed the candidate repository now that 1.10.1 has been officially released. I think this is ready to be committed.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. (Pending Jenkins).

**Review by HyukjinKwon — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @rdblue and @HyukjinKwon . Merged to master/branch-2.4.

**Pull request closed without merging**
