### PR TITLE
[SPARK-8962] Add Scalastyle rule to ban direct use of Class.forName; fix existing uses

### PR DESCRIPTION
**Pull request by JoshRosen**
This pull request adds a Scalastyle regex rule which fails the style check if `Class.forName` is used directly.  `Class.forName` always loads classes from the default / system classloader, but in a majority of cases, we should be using Spark's own `Utils.classForName` instead, which tries to load classes from the current thread's context classloader and falls back to the classloader which loaded Spark when the context classloader is not defined.

[Review on Reviewable](https://reviewable.io/reviews/apache/spark/7350)

### CODE REVIEW

**Comment by JoshRosen** [comment]
This pull request might become intractable to review due to how many files it touches, so I recommend using the Reviewable link to keep track of changes.

**Comment by shivaram** [comment]
The RBackendHandler change looks good to me. I do find it weird that we have scala style rules for not using specific functions, but I guess its hard to track this during code review in a large codebase.

**Comment by JoshRosen** [comment]
@shivaram, in this case I think the style rule is justified even if it's inconvenient or a hassle to implmenet because this `Class.forName` issue has led to a number of separate bugs over the years.

**Comment by rxin** [comment]
@JoshRosen looks like you missed a few places. Can you fix them so we can merge this?

**Comment by rxin** [comment]
Unfortunately another pr created a conflict again ...

**Comment by JoshRosen** [comment]
Argh... will fix now.

**Comment by JoshRosen** [comment]
Jenkins, retest this please.

**Comment by JoshRosen** [comment]
Jenkins, retest this please.

**Comment by JoshRosen** [comment]
Jenkins, retest this please.

**Comment by rxin** [comment]
Thanks - merging this in.

**Pull request closed without merging**
