### PR TITLE
[SPARK-36478][SQL]Removes outer join if all grouping and aggregate expressions are from the streamed side

### PR DESCRIPTION
**Pull request by wankunde**
### What changes were proposed in this pull request?

Removes outer join if all grouping and aggregate expressions are from the streamed side.

For example:

```java
spark.range(200L).selectExpr("id AS a", "id as b", "id as c").createTempView("t1")
spark.range(300L).selectExpr("id AS a").createTempView("t2")
spark.sql("SELECT t1.b, max(t1.c) as c FROM t1 LEFT JOIN t2 ON t1.a = t2.a GROUP BY t1.b").explain(true)
```

Current optimized plan:

```
== Optimized Logical Plan ==
Aggregate [b#3L], [b#3L, max(c#4L) AS c#20L]
+- Project [b#3L, c#4L]
   +- Join LeftOuter, (a#2L = a#10L)
      :- Project [id#0L AS a#2L, id#0L AS b#3L, id#0L AS c#4L]
      :  +- Range (0, 200, step=1, splits=Some(1))
      +- Project [id#8L AS a#10L]
         +- Range (0, 300, step=1, splits=Some(1))
```

Expected optimized plan:
```
== Optimized Logical Plan ==
Aggregate [b#277L], [b#277L, max(c#278L) AS c#290L]
+- Project [id#274L AS b#277L, id#274L AS c#278L]
   +- Range (0, 200, step=1, splits=Some(2))
```

### Why are the changes needed?

`Enhance EliminateOuterJoin` rule

### Does this PR introduce any user-facing change?

No

### How was this patch tested?

Add UTs

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
@wankunde can you create a separate JIRA for it? I assume you target to update aggregate functions together, right?

The example in the PR description doesn't contain `max` BTW. It has to be fixed.

**Comment by wankunde** [comment]
Hi, @HyukjinKwon I just created a new JIRA for this, and updated the title and code.  Thanks for the review.

**Comment by wankunde** [comment]
retest please

**Comment by wankunde** [comment]
Hi, @HyukjinKwon @wangyum 
I had updated the JIRA and PR description and all the checks have passed.

Could you help me to review this PR?

**Review by HyukjinKwon — COMMENTED** [review]
The change makes sense to me. cc @cloud-fan too

**Comment by wangyum** [comment]
@wankunde Is the result of the following query correct if the join keys has duplicate values:
```sql
select t1.a, count(*) from t1 left join t2 on t1.a = t2.a group by t1.a;
```

**Comment by wankunde** [comment]
Close this PR as it may cause data error.

**Comment by HyukjinKwon** [comment]
can we create a list of duplicate safe aggregations, and only allow it for them? e.g.) min max

**Comment by wangyum** [comment]
> can we create a list of duplicate safe aggregations, and only allow it for them? e.g.) min max

+1. This is a real case of our cluster. The view1 is a left outer join:
```sql
SELECT COALESCE((SELECT MAX(CK_DATE) FROM view1 WHERE 1=1), CAST('2018-01-01' AS DATE));
```
Without this optimization | With this optimization
-- | --
image | image

**Pull request closed without merging**
