### PR TITLE
[SPARK-9882][Core] Priority-based scheduling for Spark applications in standalone mode

### PR DESCRIPTION
**Pull request by viirya**
JIRA: https://issues.apache.org/jira/browse/SPARK-9882

This is a priority-based scheduling based on the interface proposed in #7958. It uses a XML configuration file to specify the submission pools for applications. This patch adds a new parameter `--pool` to SparkSubmit under standalone mode to specify which pool the submitted application should be assigned to. The priority of the submitted application is defined by the assigned pool. It also defines the cores it can acquire.

Close #7958.
## Motivation

We implement this patch because in our daily usage of Spark we found that applications scheduling is an important issue for utilizing cluster resources. Currently in standalone mode, we don't have efficient way to schedule multiple Spark applications on a single cluster. We need an efficient way to manage different Spark applications with different priorities.
## Scheduling algorithm interface and configuration

This patch adds an interface `SchedulingAlgorithm` for defining scheduling algorithm across Spark applications under standalone mode.

This patch adds two configurations `spark.master.scheduling.mode` and `spark.master.scheduling.config`. `spark.master.scheduling.mode` specifies which scheduling mode to use. Currently it supports two modes: `FIFO` and `PRIORITY`. Under `PRIORITY` mode, `spark.master.scheduling.config` can be used to specify the path to a XML configuration file.
## FIFO scheduling

The currently used FIFO algorithm is moved to the class `FIFOSchedulingAlgorithm`. This is default mode.
## Priority scheduling

`PrioritySchedulingAlgorithm` implements a priority-based scheduling algorithm. Using `spark.master.scheduling.config` to set up XML configuration file, we can define some pools for Spark applications. Every pool has defined priority, requested cores. The applications assigned to same pool can only require defined cores. The applications in the pools with higher priorities will be scheduled first. In a pool, the applications submitted earlier will be scheduled first.
## Preemptive priority scheduling

In fact we also already implemented preemptive scheduling algorithm but not committed yet. Under preemptive scheduling, the applications with higher priorities can preempt others with lower priorities. We first submitted this patch for review and seeking comments to see if there is an interest to merge this feature into Spark codebase.
## Submit Spark applications to pools

This patch adds a new parameter `--pool` to `SparkSubmit` under standalone mode to specify which pool the submitted application should be assigned to.

### CODE REVIEW

**Comment by viirya** [comment]
retest this please.

**Comment by viirya** [comment]
retest this please.

**Comment by viirya** [comment]
retest this please.

**Comment by thegiive** [comment]
hi @JoshRosen , @andrewor14  , @srowen 

Viirya and I are in the same team. Currently Spark standalone has only one FIFO scheduler outside the application and that what we want to change.

Base on our team's simulation and observe, a advance scheduler will boost the spark standalone cluster's CPU/memory resource usage A LOT. We are working on implement a better scheduler than current version. This is our team's result and we have already push to prod. 

Any idea or comment will be very helpful. Thanks

**Comment by viirya** [comment]
Because there seems be no interesting to this patch, I would close this PR first.

**Comment by fathersson** [comment]
I'd be interested in having preemptive scheduler for standalone deployment.
I'd really appreciate it if you could share your code if it's been implemented.

**Comment by viirya** [comment]
@fathersson this branch is what we implement for preemptive scheduling for standalone mode. I have deployed it on production Spark cluster in my previous company. But as you see that it doesn't catch the interesting from community, I didn't continue the deployment. You may clone this code to have a try.

**Comment by viirya** [comment]
I've just rebase this branch with master branch. So it should be built and use.

**Pull request closed without merging**
