### PR TITLE
[SPARK-35413][INFRA] Use the SHA of the latest commit when checking out databricks/tpcds-kit

### PR DESCRIPTION
**Pull request by maropu**
### What changes were proposed in this pull request?

This PR proposes to use the SHA of the latest commit ([2a5078a782192ddb6efbcead8de9973d6ab4f069](https://github.com/databricks/tpcds-kit/commit/2a5078a782192ddb6efbcead8de9973d6ab4f069)) when checking out `databricks/tpcds-kit`. This can prevent the test workflow from breaking accidentally if the repository changes drastically.

### Why are the changes needed?

For better test workflow.

### Does this PR introduce _any_ user-facing change?

No, dev-only.

### How was this patch tested?

GA passed.

### CODE REVIEW

**Comment by maropu** [comment]
cc: @HyukjinKwon @dongjoon-hyun

**Review by srowen — COMMENTED** [review]
Seems like a fine idea. How often does this change? do we risk not picking up important changes? but yeah we should pin this.

**Comment by kiszk** [comment]
Good idea to prevent unexpected changes in the future while we may have a risk not to pick up the important change.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by maropu** [comment]
Thank you, @srowen @kiszk @dongjoon-hyun I re-triggered a job to generate the data for checking if it works correctly before merging this.

**Comment by maropu** [comment]
> Seems like a fine idea. How often does this change? do we risk not picking up important changes? but yeah we should pin this.

Yea, I  think the change rarely happens, but as its better to avoid unexpected test failures as much as possible.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by maropu** [comment]
okay, I've checked if it works correctly. Merged to master/3.0/3.1.

**Comment by maropu** [comment]
Thank you, @HyukjinKwon , too.

**Pull request closed without merging**
