### PR TITLE
[SPARK-26256][K8s] Fix labels for pod deletion

### PR DESCRIPTION
**Pull request by skonto**
## What changes were proposed in this pull request?
Adds proper labels when deleting executor pods.

## How was this patch tested?
Manually with tests.

### CODE REVIEW

**Review by srowen — APPROVED** [review]

**Review by liyinan926 — APPROVED** [review]
LGTM

**Comment by skonto** [comment]
@srowen I resolved the conflicts feel free to merge.

**Comment by vanzin** [comment]
Merging to master / 2.4.

**Comment by vanzin** [comment]
Actually I forgot 2.4... there's also a conflict. Seems trivial, so I'll do it manually and fix the conflict (and run some local tests).

**Pull request closed without merging**
