### PR TITLE
[SPARK-37389][SQL][FOLLOWUP] SET command shuold not parse comments

### PR DESCRIPTION
**Pull request by cloud-fan**
### What changes were proposed in this pull request?

This PR is a followup of https://github.com/apache/spark/pull/34668 , to fix a breaking change. The SET command uses wildcard which may contain unclosed comment, e.g. `/path/to/*`, and we shouldn't fail it.

This PR fixes it by skipping the unclosed comment check if we are parsing SET command.

### Why are the changes needed?

fix a breaking change

### Does this PR introduce _any_ user-facing change?

no, the breaking change is not released yet.

### How was this patch tested?

new tests

### CODE REVIEW

**Comment by cloud-fan** [comment]
@beliefer @gengliangwang

**Review by HyukjinKwon — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Review by beliefer — APPROVED** [review]
Thank you for the fix.

**Review by gengliangwang — APPROVED** [review]

**Comment by cloud-fan** [comment]
thanks for the review, merging to master!

**Pull request closed without merging**
