### PR TITLE
[SPARK-15431][SQL][branch-2.0-test] rework the clisuite test cases

### PR DESCRIPTION
**Pull request by xwu0226**
## What changes were proposed in this pull request?

This PR reworks on the CliSuite test cases for `LIST FILES/JARS` commands.

CC @yhuai Thanks!

### CODE REVIEW

**Comment by yhuai** [comment]
add to whitelist

**Comment by xwu0226** [comment]
retest this please

**Comment by yhuai** [comment]
Thanks for the fix. What was the problem?

**Comment by xwu0226** [comment]
I missed the`;` at each command that i passed into the `runCliWithin(...)`. So basically, the commands were not really run without the `;`

**Comment by yhuai** [comment]
LGTM. Merging to master and branch 2.0.

**Pull request closed without merging**
