### PR TITLE
[SPARK-50109][PYTHON][DOCS] Refine the docstring for more date functions

### PR DESCRIPTION
**Pull request by zhengruifeng**
### What changes were proposed in this pull request?
Refine the docstring for more date functions

### Why are the changes needed?
1, make example copy-pasteable;
2, clarify `str` is a column name or literal string;
3, `show` both the input columns and output columns, to make the projection more clear;
4, improve the test coverage by adding more doctests;

### Does this PR introduce _any_ user-facing change?
doc change

### How was this patch tested?
ci

### Was this patch authored or co-authored using generative AI tooling?
no

### CODE REVIEW

**Review by xinrong-meng — APPROVED** [review]

**Comment by xinrong-meng** [comment]
LGTM, thank you!

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by dongjoon-hyun** [comment]
Merged to master for Apache Spark 4.0.0 on February 2025.
Thank you, @zhengruifeng and @xinrong-meng .

**Comment by zhengruifeng** [comment]
thank you @dongjoon-hyun and @xinrong-meng so much!

**Pull request closed without merging**
