### PR TITLE
[SPARK-45378][CORE] Add convertToNettyForSsl to ManagedBuffer

### PR DESCRIPTION
**Pull request by hasnain-db**
### What changes were proposed in this pull request?

As the title suggests. In addition to that API, add a config to the `TransportConf` to configure the default block size if desired.

### Why are the changes needed?

Netty's SSL support does not support zero-copy transfers. In order to support SSL using Netty we need to add another API to the `ManagedBuffer` which lets buffers return a different data type.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

CI. This will have tests added later - it's tested as part of https://github.com/apache/spark/pull/42685 from which this is split out.

### Was this patch authored or co-authored using generative AI tooling?

No

### CODE REVIEW

**Comment by hasnain-db** [comment]
cc: @mridulm @JoshRosen this is now ready to review and has all green tests on CI

**Comment by mridulm** [comment]
QQ: If/when there is more widespread adoption of `kernel.ssl.sendfile` (and `ssl_sendfile` from openssl), how will it impact the proposed design ?

**Comment by hasnain-db** [comment]
@mridulm once it's widely adopted and supported in Netty + netty-tcnative, we can remove these APIs and potentially just use `convertToNetty`, depending on how the design is from the netty side. But it's unclear to me what the timelines are for that

**Comment by mridulm** [comment]
Sounds good, can you add a comment to that effect in the `Trait` ?
Rest looks good to me

**Review by mridulm — APPROVED** [review]
Pending CI
+CC @JoshRosen

**Review by JoshRosen — APPROVED** [review]

**Comment by hasnain-db** [comment]
CI is also finally green here

**Comment by mridulm** [comment]
Merged to master.
Thanks for working on this @hasnain-db !
Thanks for review @JoshRosen :-)

**Pull request closed without merging**
