### PR TITLE
[SPARK-12928][SQL] Oracle FLOAT datatype is not properly handled when reading via JDBC

### PR DESCRIPTION
**Pull request by poolis**
The contribution is my original work and that I license the work to the project under the project's open source license.

### CODE REVIEW

**Comment by JoshRosen** [comment]
FYI, I believe that this issue may have come up in the past as well, so someone should search JIRA for the `-127` scale issue.

**Comment by poolis** [comment]
I think you are referring to [Spark-10648](https://issues.apache.org/jira/browse/SPARK-10648).  That only covered numeric types with size 0.  For the float data type you can specify a non-zero size and the scale still gets defaulted to -127.

**Comment by poolis** [comment]
Anything I can do to move this along?

**Comment by Eniemela** [comment]
+1 for resolving this, I face the FLOAT issue when retrieving data from Oracle via JDBC. pyspark.sql.types _parse_datatype_json_value fails since type is decimal(38, -127)

**Comment by rxin** [comment]
@poolis sorry for the delay. Do you mind bringing this up to date so we can test and merge it?

**Comment by poolis** [comment]
I have brought this branch up to date.

**Comment by rxin** [comment]
@poolis why did you need to delete two files?

**Comment by poolis** [comment]
I thought those were created locally. Will that cause a problem?

**Comment by rxin** [comment]
No those are not created locally. Can you revert the deletion of those files?

Also the patch is failing scalastyle check.

**Comment by poolis** [comment]
I reverted those files and resolved the scalastyle check errors.

**Comment by rxin** [comment]
Thanks - merging in master.

**Pull request closed without merging**
