### PR TITLE
[SPARK-46083][PYTHON] Make SparkNoSuchElementException as a canonical error API

### PR DESCRIPTION
**Pull request by HyukjinKwon**
### What changes were proposed in this pull request?

This PR is a kind of a followup of https://github.com/apache/spark/pull/43927 which added `SparkNoSuchElementException` into errors. This PR makes `SparkNoSuchElementException` as a canonical error API.

### Why are the changes needed?

For the end users to catch those exceptions properly via `pyspark.errors.SparkNoSuchElementException` with/without Spark Connect.

### Does this PR introduce _any_ user-facing change?

Yes, it adds a new API `SparkNoSuchElementException` class.

### How was this patch tested?

Manually tested:

```bash
./bin/pyspark
```

```bash
./bin/pyspark --remote local
```

```python
from pyspark.errors import SparkNoSuchElementException

try:
    spark.conf.get("my_key")
except SparkNoSuchElementException as e:
    print("caught properly")
```

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @itholic

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by HyukjinKwon** [comment]
Build: https://github.com/HyukjinKwon/spark/actions/runs/6975938047

Thank you @dongjoon-hyun !

**Review by itholic — APPROVED** [review]
LGTM when test passing.

**Comment by dongjoon-hyun** [comment]
All tests passed. Merged to master for Apache Spark 4.0.0.

**Pull request closed without merging**
