### PR TITLE
[SPARK-40142][PYTHON][SQL][FOLLOW-UP] Make pyspark.sql.functions examples self-contained (FINAL)

### PR DESCRIPTION
**Pull request by khalidmammadov**
### What changes were proposed in this pull request?
It's part of the Pyspark docstrings improvement series (https://github.com/apache/spark/pull/37592, https://github.com/apache/spark/pull/37662, https://github.com/apache/spark/pull/37686, https://github.com/apache/spark/pull/37786, https://github.com/apache/spark/pull/37797, https://github.com/apache/spark/pull/37850)

In this PR I mainly covered missing parts in the docstrings adding some more examples where it needed.

I have also made all examples self explanatory by providing DataFrame creation command where it was missing for clarity to a user.

This should complete "my take" on `functions.py` docstrings & example improvements.

### Why are the changes needed?
To improve PySpark documentation

### Does this PR introduce _any_ user-facing change?
Yes, documentation

### How was this patch tested?
```
PYTHON_EXECUTABLE=python3.9 ./dev/lint-python
./python/run-tests --testnames pyspark.sql.functions
bundle exec jekyll build
```

### CODE REVIEW

**Comment by khalidmammadov** [comment]
@srowen @itholic @HyukjinKwon Please review

**Comment by HyukjinKwon** [comment]
Thanks for finishing this work, @khalidmammadov.

**Review by srowen — APPROVED** [review]

**Comment by khalidmammadov** [comment]
> Thanks for finishing this work, @khalidmammadov.

Happy to help

**Comment by srowen** [comment]
Merged to master

**Comment by itholic** [comment]
Thanks for your efforts to finish this work!

**Pull request closed without merging**
