### PR TITLE
[DOCS] Clarify round mode for format_number & round functions

### PR DESCRIPTION
**Pull request by roxannemoslehi**
## What changes were proposed in this pull request?

Updated the description for the `format_number` description to indicate that it uses `HALF_EVEN` rounding. Updated the description for the `round` description to indicate that it uses `HALF_UP` rounding.

## How was this patch tested?

Just changing the two function comments so no testing involved.

Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Comment by srowen** [comment]
Have a look at http://spark.apache.org/contributing.html as the template says.
I think you'd want to describe this a little more, and consider whether other functions could use this detail?

**Comment by roxannemoslehi** [comment]
Hmm @srowen do you mean describe HALF_EVEN round mode? Also, I know some of the other functions that use this type of rounding already include it in their definition.

**Comment by srowen** [comment]
No I really meant fill out the PR a little more (see link). The title isn't descriptive.
If you mean this is just making the docs consistent that's great, just note that in the description here. Helps reviewers understand why you think this change should happen.

**Comment by ash211** [comment]
Thanks for contributing to Spark @roxannemoslehi !

I think Sean just means updating the title to something more like `[DOCS] Clarify round mode in format_number function`.  It doesn't feel big enough to be worth a Jira ticket for such a small docs change.

**Comment by rxin** [comment]
Yea we definitely need a better title. Thanks for contributing though.

**Comment by rxin** [comment]
@roxannemoslehi can you fix the title? We can then merge this.

**Comment by roxannemoslehi** [comment]
Yup! Sorry about that everyone. Looks like my intended commit message didn't make it through originally but should be fixed now!

**Comment by srowen** [comment]
How about the doc of the `round(Column)` method earlier, same thing?

**Comment by roxannemoslehi** [comment]
Looks like round uses `HALF_UP` rounding mode

**Comment by rxin** [comment]
Thanks - merging in master.

**Pull request closed without merging**
