### PR TITLE
[SPARK-11466] [core] Avoid mockito in multi-threaded FsHistoryProviderSuite test.

### PR DESCRIPTION
**Pull request by vanzin**
The test functionality should be the same, but without using mockito; logs don't
really say anything useful but I suspect it may be the cause of the flakiness,
since updating mocks when multiple threads may be using it doesn't work very
well. It also allows some other cleanup (= less test code in FsHistoryProvider).

### CODE REVIEW

**Comment by yhuai** [comment]
Thanks for the PR! btw, if you want jenkins to test hadoop1, you can add `[test-hadoop1.0]` to the title.

**Comment by vanzin** [comment]
The failure should not be related to the version of hadoop, so testing with 2.x should be fine.

**Comment by vanzin** [comment]
unrelated failure, retest this please.

**Comment by vanzin** [comment]
I'm gonna merge this later if no one has any feedback.

**Pull request closed without merging**
