### PR TITLE
[SPARK-6790] [ML] Add linear regression model import/export features

### PR DESCRIPTION
**Pull request by fayeshine**
add linear regression model import/export features

### CODE REVIEW

**Comment by jkbradley** [comment]
@fayeshine Thanks for your PR!  We're in a bit of a rush to get save/load into Spark, so would you mind if I sent a PR to you directly (to update this PR), rather than regular code review?

**Comment by fayeshine** [comment]
The test failed due to the scala style (whitespace problem) and I have solved it.
Besides, Is the issue11672 solved? Can we add this to the unit test process since it was previously 'ignored' ?

**Comment by fayeshine** [comment]
Dear jkbradley,
        Do you mean you plan to fix this patch directly if there's any bug or problem? I think it's totally OK for me, please fix anything that is not properly written. :smiley: 
                                                       Mark

**Comment by fayeshine** [comment]
Oops, It seems that the API has changed, I'll try to modify as well to save your effort.

**Comment by jkbradley** [comment]
Sure, please do, thank you!

**Comment by jkbradley** [comment]
After you push an update, then I'll take a look.

**Comment by jkbradley** [comment]
And yes, SPARK-11672 should be resolved now.

**Comment by fayeshine** [comment]
Scalastyle checks failed at following occurrences:
[error] /home/jenkins/workspace/SparkPullRequestBuilder@3/mllib/src/main/scala/org/apache/spark/ml/regression/LinearRegression.scala: Expected token RBRACE but got Token(EOF,,34352,)
[error] (mllib/compile:scalastyle) errors exist
[error] Total time: 10 s, completed Nov 17, 2015 5:39:29 PM
[error] /home/jenkins/workspace/SparkPullRequestBuilder@3/mllib/src/main/scala/org/apache/spark/ml/regression/LinearRegression.scala: Expected token RBRACE but got Token(EOF,,34352,)
[error] (mllib/compile:scalastyle) errors exist
[error] Total time: 11 s, completed Nov 17, 2015 5:40:13 PM
[error] running /home/jenkins/workspace/SparkPullRequestBuilder@3/dev/lint-scala ; received return code 1

Sorry, but what is this about? Expected token RBRACE but got Token(EOF,,34352,)
I cannot recognize the scala style bug.

**Comment by fayeshine** [comment]
@jkbradley ,
Sorry to bother you again, I can't recognize the scala style bug. If you are in hurry, please just directly update the PR as you previously planned to. :smiley: 
Thanks for your comments.
                           Mark

**Comment by jkbradley** [comment]
I'll go ahead and send an update.  Thanks for your updates though!

**Comment by jkbradley** [comment]
@fayeshine I had to merge with master to get some updates from a LogReg PR, so I couldn't create a clean PR to send you.  I instead created a new PR: [https://github.com/apache/spark/pull/9814]

Could you please check out the latest commits in it to help review my changes?

I'll make sure you are still listed as the primary author of the PR and on JIRA.

Thank you!

**Comment by jkbradley** [comment]
If the PR I just sent looks good, then you can close this one.

**Comment by fayeshine** [comment]
@jkbradley @mengxr 
Thank you very much! I'll close this PR.

**Pull request closed without merging**
