### PR TITLE
[SPARK-46316][CORE] Enable `buf-lint-action` on `core` module

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to enable `buf-lint-action` on `core` module.

### Why are the changes needed?

To enforce the community guideline.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the CIs.

Screenshot 2023-12-07 at 7 40 54 PM

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Review by LuciferYang — APPROVED** [review]

**Review by yaooqinn — APPROVED** [review]

**Comment by LuciferYang** [comment]
I thought of a question, branch-3.3 does not have this directory, will this cause the daily test to fail?

**Comment by dongjoon-hyun** [comment]
> I thought of a question, branch-3.3 does not have this directory, will this cause the daily test to fail?

No, it's skipped in branch-3.3.

Screenshot 2023-12-07 at 7 55 20 PM

**Comment by LuciferYang** [comment]
Thanks for your answer. @dongjoon-hyun

**Comment by dongjoon-hyun** [comment]
Oh... It seems that we didn't add this to the whitelist yet. Let me check the INFRA JIRAs.

Screenshot 2023-12-07 at 8 00 00 PM

Screenshot 2023-12-07 at 8 01 13 PM

**Comment by dongjoon-hyun** [comment]
Thanks, @HyukjinKwon .

**Comment by dongjoon-hyun** [comment]
ASF Infra team handled it. Let me put this back~

**Pull request closed without merging**
