### PR TITLE
[SPARK-36302][SQL] Refactor thirteenth set of 20 query execution errors to use error classes

### PR DESCRIPTION
**Pull request by dchvn**
### What changes were proposed in this pull request?
Adds error classes to some of the exceptions in QueryExecutionErrors.

### Why are the changes needed?
Improves auditing for developers and adds useful fields for users (error class and SQLSTATE).

### Does this PR introduce _any_ user-facing change?
Fills in missing error class and SQLSTATE fields.

### How was this patch tested?
Existing tests

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @karenfeng FYI

**Review by karenfeng — COMMENTED** [review]
Thanks for working on this @dchvn. Looks good overall, left some small comments. Please ping me when you address them!

**Comment by dchvn** [comment]
ping @karenfeng , can you take a look when you have free time? Many thanks

**Review by karenfeng — COMMENTED** [review]
Thanks for working on this @dchvn! I left some comments; please ping me once you've addressed them.

**Review by karenfeng — APPROVED** [review]
LGTM, thanks @dchvn! I will review your other PRs as well. @HyukjinKwon, can you take another look?

**Comment by dchvn** [comment]
ping @karenfeng, I am so sorry about my mistake, can you take a look? No unused functions in this PR and how about my note in README [#34178](https://github.com/apache/spark/pull/34178) ?

**Pull request closed without merging**
