### PR TITLE
[BACKPORT-2.2][SPARK-19372][SQL] Fix throwing a Java exception at df.fliter() due to 64KB bytecode size limit

### PR DESCRIPTION
**Pull request by kiszk**
## What changes were proposed in this pull request?

This PR is backport of https://github.com/apache/spark/pull/17087 to Spark 2.2

## How was this patch tested?

Add a test suite into `DataFrameSuite`

### CODE REVIEW

**Comment by kiszk** [comment]
ping @zsxwing

**Comment by marmbrus** [comment]
Since this is purely a fallback for a case that would error, it seems possibly okay to include in 2.2.  @zsxwing could you take a look and make sure I'm right?

**Comment by zsxwing** [comment]
@kiszk I just pushed  #17087 directly to branch-2.2 since there is no conflict. Could you close this one?

In addition, I noticed that the test outputs too many logs, could you submit a PR to use `testQuietly` instead?

**Comment by kiszk** [comment]
@zsxwing , sure, I submit another PR.

**Comment by dongjoon-hyun** [comment]
Thank you so much!

**Pull request closed without merging**
