### PR TITLE
[SPARK-30254][SQL] Fix LikeSimplification optimizer to use a given escapeChar

### PR DESCRIPTION
**Pull request by ulysses-you**
### What changes were proposed in this pull request?

Since [25001](https://github.com/apache/spark/pull/25001), spark support like escape syntax.

We should also sync the escape used by `LikeSimplification`.

### Why are the changes needed?

Avoid optimize failed.

### Does this PR introduce any user-facing change?

No.

### How was this patch tested?

Add UT.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Hi, @ulysses-you and reviewers.
Please hold on this until we finish reverting the following. It's not directly related, but we had better be careful.
- https://github.com/apache/spark/pull/26883

**Comment by dongjoon-hyun** [comment]
I merged #26883 .

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by ulysses-you** [comment]
@dongjoon-hyun thanks for remind this.

**Review by maropu — APPROVED** [review]
cc: @HyukjinKwon @dongjoon-hyun

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Merged to master.

**Comment by dongjoon-hyun** [comment]
Thank you, @ulysses-you .
cc @beliefer , @cloud-fan , @gengliangwang since this is a kind of follow-up of https://github.com/apache/spark/pull/25001

**Comment by gengliangwang** [comment]
Thanks for the work, @ulysses-you

**Comment by beliefer** [comment]
Thanks @ulysses-you

**Comment by ulysses-you** [comment]
Thanks all!

**Pull request closed without merging**
