### PR TITLE
[SPARK-44170][BUILD][TESTS] Migrate Junit 4 to Junit 5 

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr aims to migrate Junit 4 to Junit 5 jupiter api, the main changes are as follows:

1. Change JUnit 4 related test dependencies to JUnit 5 to ensure Maven and SBT can run JUnit test normally: `junit` -> `junit-jupiter`, `com.github.sbt:junit-interface` -> `net.aichler:jupiter-interface`, `jmock-junit4` -> `jmock-junit5` and add `sbt-jupiter-interface` plugin to plugins.sbt
2. API migration：
2.1 Annotations reside in the `org.junit.jupiter.api` package
2.2 `@Before` and `@After` no longer exist, use `@BeforeEach` and `@AfterEach` instead
2.3 `@BeforeClass` and `@AfterClass` no longer exist, use `@BeforeAll` and `@AfterAll` instead
2.4 `@Ignore` no longer exists, use `@Disabled` instead
2.5 `Assertions` reside in `org.junit.jupiter.api.Assertions` and the assertion api with error message has a little changes there are a few api changes, for example: `assertEquals("my message", 1, 2)` -> `assertEquals(1, 2, "my message")`
2.6 Assumptions reside in `org.junit.jupiter.api.Assumptions`

### Why are the changes needed?
JUnit5 is a powerful and flexible update to the JUnit framework, and it provides a variety of improvements and new features to organize and describe test cases, as well as help in understanding test results：

1. JUnit 5 leverages features from Java 8 or later, such as lambda functions, making tests more powerful and easier to maintain, but Junit 4 still a Java 7 compatible version
2. JUnit 5 has added some useful new features for describing, organizing, and executing tests. For examples: [Parameterized Tests](https://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests) and [Conditional Test Execution](https://junit.org/junit5/docs/current/user-guide/#extensions-conditions) may make our test code look simpler, [Parallel Execution](https://junit.org/junit5/docs/current/user-guide/#writing-tests-parallel-execution) may make our test faster

More importantly, Junit4 is currently an inactive project, which has not released a new version for more than two years.

More importantly, Junit4 is currently an inactive project, which has not released a new version for more than two years

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass GitHub Actions

### Was this patch authored or co-authored using generative AI tooling?
No

### CODE REVIEW

**Comment by LuciferYang** [comment]
Test first

**Comment by LuciferYang** [comment]
cc @srowen FYI

**Comment by srowen** [comment]
@LuciferYang I think we should indeed "bite the bullet" and upgrade. It touches a ton of files, but, maybe that's fine to do now that we're moving to Spark 4 next. I'd maybe briefly email dev@ to see if there are any strong feelings against this.

**Comment by LuciferYang** [comment]
> @LuciferYang I think we should indeed "bite the bullet" and upgrade. It touches a ton of files, but, maybe that's fine to do now that we're moving to Spark 4 next. I'd maybe briefly email dev@ to see if there are any strong feelings against this.

sent an email to dev@:  https://lists.apache.org/thread/bzpf1cgmdln17j8bp5p3q6n7dgnn76m2

**Comment by srowen** [comment]
Merged to master

**Comment by LuciferYang** [comment]
Thanks @srowen and @mridulm ~ I will keep an eye on whether there are any failures in the CI.

**Pull request closed without merging**
