### PR TITLE
[SPARK-18994] clean up the local directories for application in future by annother thread

### PR DESCRIPTION
**Pull request by liujianhuiouc**
## What changes were proposed in this pull request?

clean up the directories of the app by asynchronous method in future block

### CODE REVIEW

**Comment by srowen** [comment]
I don't know that this is the right way to fix it. The fundamental problem is that the heartbeat message shouldn't block on this.

Also, it might be simpler to do this in parallel rather than asynchronously. T

**Comment by liujianhuiouc** [comment]
yes,  the root cause is the heartbeat message blocked，the Heartbeat could be send in parallel, but in any way, the deleting of the app's directories should be async

**Comment by liujianhuiouc** [comment]
add another thread to send heartbeat in parallel, and also remove the part of deleting directories in async

**Comment by srowen** [comment]
My point is that this is an ad-hoc band-aid for one type of message, and not really a solution to other messages blocking a heartbeat. IT's probably best to fix this for real if at all.

If a band-aid is important, deleting N directories in parallel might solve most practical problems.

**Comment by liujianhuiouc** [comment]
in actual scene, it's only one executor's director for an app, does you mean that delete the child directories in parallel?  in my opinion, it's unnecessary  to delete that in parallel, could be deleted in future, to avoid other message to block the heartbeat, does it right to send heartbeat in another thread?

**Comment by jiangxb1987** [comment]
Should we close this? @srowen

**Pull request closed without merging**
