### PR TITLE
[SPARK-34392][SQL][3.0] Support ZoneOffset +h:mm in DateTimeUtils. getZoneId

### PR DESCRIPTION
**Pull request by maropu**
### What changes were proposed in this pull request?
To support +8:00 in Spark3 when execute sql
`select to_utc_timestamp("2020-02-07 16:00:00", "GMT+8:00")`

This is the backport of #31624 and the original author is @Karl-WangSK .

### Why are the changes needed?
+8:00 this format is supported in PostgreSQL,hive, presto, but not supported in Spark3
https://issues.apache.org/jira/browse/SPARK-34392

### Does this PR introduce _any_ user-facing change?
no

### How was this patch tested?
unit test

### CODE REVIEW

**Comment by maropu** [comment]
cc: @srowen

**Review by MaxGekk — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @maropu and @MaxGekk .
Merged to branch-3.0.

**Comment by srowen** [comment]
LOL I just tried to merge this as well. Hope it worked.

**Comment by dongjoon-hyun** [comment]
Oh. :)

**Comment by dongjoon-hyun** [comment]
I was late. Thanks. :)

**Pull request closed without merging**
