### PR TITLE
[SPARK-31333][SQL][DOCS] Document Join Hints

### PR DESCRIPTION
**Pull request by huaxingao**
### What changes were proposed in this pull request?
Document Join Hints

### Why are the changes needed?
To make SQL Reference complete

### Does this PR introduce any user-facing change?
Yes

Screen Shot 2020-04-03 at 9 20 15 AM

Screen Shot 2020-04-03 at 10 39 55 AM

### How was this patch tested?
Manually build and check

### CODE REVIEW

**Comment by gatorsmile** [comment]
cc @maryannxue

**Comment by maryannxue** [comment]
It would be worth mentioning the conflict resolving policy in case multiple hints are specified in a query. Even in case a hint can be matched against two different relations with same table name under different namespaces.

**Comment by huaxingao** [comment]
@srowen Could you take a look of this one too? Thank you!

**Review by srowen — COMMENTED** [review]
One minor comment. I don't know the behavior well enough to evaluate the content though

**Comment by srowen** [comment]
Merged to master/3.0

**Comment by huaxingao** [comment]
Thanks all!

**Pull request closed without merging**
