### PR TITLE
[SPARK-44934][SQL] Use outputSet instead of output to check if column pruning occurred in PushdownPredicateAndPruneColumnsForCTEDef

### PR DESCRIPTION
**Pull request by wenyuen-db**
### What changes were proposed in this pull request?

Originally, when a CTE has duplicate expression IDs in its output, the rule PushdownPredicatesAndPruneColumnsForCTEDef wrongly assesses that the columns in the CTE were pruned, as it compares the size of the attribute set containing the union of columns (which is unique) and the original output of the CTE (which contains duplicate columns) and notices that the former is less than the latter. This causes incorrect pruning of the CTE output, resulting in a missing reference and causing the error as documented in the ticket.

This PR changes the logic to use the needsPruning function to assess whether a CTE has been pruned, which uses the outputSet to check if any columns has been pruned instead of the output.

### Why are the changes needed?

The incorrect behaviour of PushdownPredicatesAndPruneColumnsForCTEDef in CTEs with duplicate expression IDs in its output causes a crash when such a query is run.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Unit test for the crashing case was added.

### Was this patch authored or co-authored using generative AI tooling?

No

### CODE REVIEW

**Review by sigmod — APPROVED** [review]

**Comment by sigmod** [comment]
@cloud-fan @gengliangwang @peter-toth

**Review by peter-toth — APPROVED** [review]

**Comment by wenyuen-db** [comment]
@peter-toth could you help me merge the PR? :) thanks!

**Comment by dongjoon-hyun** [comment]
Hi, @wenyuen-db , @sigmod , @peter-toth .

Unfortunately, newly added test cases seem to break `branch-3.4` due to some difference among branches. I also verified the failure locally.

https://github.com/apache/spark/actions/runs/5965492707/job/16187941738

Screenshot 2023-08-24 at 10 46 37 AM

Let me revert this from 3.4 and 3.3. Please make two independent backporting PRs for branch-3.4 and branch-3.3, respectively, @wenyuen-db .

**Comment by dongjoon-hyun** [comment]
This is reverted from branch-3.4 via https://github.com/apache/spark/commit/6b6a0d501b65924c836abc1677267cc292566c80 .

**Comment by wenyuen-db** [comment]
Seems like there is an analyzer issue in 3.3 and 3.4 with dealing with CTEs with duplicate expression IDs that cause the query to still fail in 3.3 and 3.4 despite the fix - will investigate further.

**Comment by cloud-fan** [comment]
It seems hard to decide which part to extract from [SPARK-43838](https://issues.apache.org/jira/browse/SPARK-43838) , I'm fine with leaving the fix in 3.5+ only.

**Comment by dongjoon-hyun** [comment]
+1 for keeping this in 3.5+ only. Thank you!

**Pull request closed without merging**
