### PR TITLE
[SPARK-21060][WEB-UI]Css style about paging function is error in the executor page. Css style about paging function is error in the executor page. It is different of history server ui paging function css style.

### PR DESCRIPTION
**Pull request by guoxiaolongzte**
## What changes were proposed in this pull request?

Css style about paging function is error in the executor page. It is different of history server ui paging function css style. 

**But their style should be consistent**. There are three reasons.

1. The first reason: 'Previous', 'Next' and number should be the button format.

2. The second reason: when you are on the first page, 'Previous' and '1' should be gray and can not be clicked.

3. The third reason: when you are on the last page, 'Previous' and 'Max number' should be gray and can not be clicked.

before fix:
fix_before

after fix:
fix_after

The style of history server ui:
history

## How was this patch tested?

manual tests

Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Comment by srowen** [comment]
I tend to take your word, but will CC @ajbozarth just in case.

(BTW why do your PRs have a huge number of merge commits? you generally branch off a clean fork of `master`. They get squashed anyway, just wondering)

**Comment by guoxiaolongzte** [comment]
I know, is not it a bug or an improvement corresponding to a branch? This also makes it easy for you to merge to master.@srowen

**Comment by guoxiaolongzte** [comment]
I'm sorry, I do not understand what you said, can you elaborate on it?

**Comment by srowen** [comment]
Look at all the "Merge branch 'master'..." messages above. I think you're somehow branching off a branch that you keep merging from upstream master. You just need to keep your `master` in sync with upstream with `pull`

**Comment by guoxiaolongzte** [comment]
image
Should choose here. Please forgive me, I really did not pay attention before, thank you. The next time I write PR, I will pay attention.

**Comment by guoxiaolongzte** [comment]
@ajbozarth 
I am sorry and have trouble you. Help with code review.

**Comment by srowen** [comment]
No @guoxiaolongzte I think it's an issue with the branch you have set up to track upstream `master`. You seem to merge changes from master rather than pull/rebase. It doesn't actually cause a problem here, but isn't the right way to manage it. You probably want to delete your fork and master after you're done with PRs and then re-fork it, and never `git merge` your `master, but `git pull upstream master`

**Review by ajbozarth — APPROVED** [review]
LGTM

**Comment by guoxiaolongzte** [comment]
@srowen 
This patch fails Spark unit tests. This error is not due to my code.

**Comment by srowen** [comment]
Merged to master/2.2

**Pull request closed without merging**
