### PR TITLE
[SPARK-11343] [ML] Documentation of float and double prediction/label columns in RegressionEvaluator

### PR DESCRIPTION
**Pull request by dahlem**
@felixcheung , @mengxr 

Just added a message to require()

### CODE REVIEW

**Comment by jkbradley** [comment]
LGTM pending tests

**Comment by felixcheung** [comment]
looks good, perhaps reuse `predictionColName` and `labelColName`, instead of `$(predictionCol)` and `$(labelCol)`, but it is minor

**Comment by jkbradley** [comment]
@dahlem Can you please fix the scala style problems?

**Comment by dahlem** [comment]
Will do.

**Comment by jkbradley** [comment]
Ping

**Comment by dahlem** [comment]
@jkbradley done

**Comment by jkbradley** [comment]
LGTM pending tests ( @felixcheung 's comment is valid, but I guess we can fix it later)

**Comment by jkbradley** [comment]
merging with master and branch-1.6

**Pull request closed without merging**
