### PR TITLE
[SPARK-39332][BUILD] Upgrade RoaringBitmap to 0.9.28

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr aims upgrade `RoaringBitmap` to 0.9.28

### Why are the changes needed?
This version bring bug fix and optimization, for example, [andCardinality/orCardinality without materialising a bitmap](https://github.com/RoaringBitmap/RoaringBitmap/pull/561), optimized `andCardinality/orCardinality` performance.

The changes between 0.9.25 and 0.9.28 as follows:

- https://github.com/RoaringBitmap/RoaringBitmap/compare/0.9.25...0.9.28

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass Github Actions

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Thank you, @LuciferYang .
Could you run `MapStatusesSerDeserBenchmark` like #29233?

**Comment by LuciferYang** [comment]
> Thank you, @LuciferYang . Could you run `MapStatusesSerDeserBenchmark` like #29233?

ok

**Comment by LuciferYang** [comment]
[3da048a](https://github.com/apache/spark/pull/36719/commits/3da048a663b9afe1211276b50ec9454ef512ee00) update bench result of `MapStatusesSerDeserBenchmark`, but I found that the cpu frequency of the machine changed for Java8 & Java 11:

- Java 11: 8370C CPU @ 2.80GHz -> 8272CL CPU @ 2.60GHz
- Java 8: 8272CL CPU @ 2.60GHz -> 8370C CPU @ 2.80GHz

need to re-run to keep them the same @dongjoon-hyun ?

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @LuciferYang .
The difference is okay because we cannot control it.
Merged to master for Apache Spark 3.4.

**Comment by LuciferYang** [comment]
> Thank you, @LuciferYang . Could you run `MapStatusesSerDeserBenchmark` like #29233?

@dongjoon-hyun Sorry to bother you, I used `Intellij Profiler` to run `MapStatusesSerDeserBenchmark` today.  But I found that `MapStatusesSerDeserBenchmark` doesn't seem to use `RoaringBitmap` related APIs.  


It seems that `MapStatusesSerDeserBenchmark` uses `CompressedMapStatus` to test serDe,  if `HighlyCompressedMapStatus` is used, `RoaringBitmap` related APIs will be tested?

https://github.com/apache/spark/blob/57c82ea1e561cbfad4cbc7fd3880036b0bb39ab6/core/src/test/scala/org/apache/spark/MapStatusesSerDeserBenchmark.scala#L56-L62

**Comment by dongjoon-hyun** [comment]
Thank you for pinging me, @LuciferYang . Let me check it.

**Comment by dongjoon-hyun** [comment]
Oh, you are right. Sorry for misleading you so far, @LuciferYang . :(
Yes, `RoaringBitmap` is used in `HighlyCompressedMapStatus` only.

**Comment by LuciferYang** [comment]
> Oh, you are right. Sorry for misleading you so far, @LuciferYang . :(
> Yes, `RoaringBitmap` is used in `HighlyCompressedMapStatus` only.

doesn't matter ~ :)

**Pull request closed without merging**
