### PR TITLE
[SPARK-22893][SQL] Unified the data type mismatch message

### PR DESCRIPTION
**Pull request by wangyum**
## What changes were proposed in this pull request?

We should use `dataType.simpleString` to unified the data type mismatch message:
Before:
```
spark-sql> select cast(1 as binary);
Error in query: cannot resolve 'CAST(1 AS BINARY)' due to data type mismatch: cannot cast IntegerType to BinaryType; line 1 pos 7;
```
After:
```
park-sql> select cast(1 as binary);
Error in query: cannot resolve 'CAST(1 AS BINARY)' due to data type mismatch: cannot cast int to binary; line 1 pos 7;
```

## How was this patch tested?

Exist test.

### CODE REVIEW

**Comment by wangyum** [comment]
retest this please

**Review by gatorsmile — COMMENTED** [review]
LGTM

**Comment by gatorsmile** [comment]
Thanks! Merged to master.

**Comment by dongjoon-hyun** [comment]
Hi, @gatorsmile and @wangyum .
This PR seems to break Jenkins tests. Please see my hotfix.

**Pull request closed without merging**
