### PR TITLE
[SPARK-34080][ML][PYTHON][FOLLOW-UP] Update score function in UnivariateFeatureSelector document

### PR DESCRIPTION
**Pull request by viirya**
### What changes were proposed in this pull request?

This follows up #31160 to update score function in the document.

### Why are the changes needed?

Currently we use `f_classif`, `ch2`, `f_regression`, which sound to me the sklearn's naming. It is good to have it but I think it is nice if we have formal score function name with sklearn's ones.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

No, only doc change.

### CODE REVIEW

**Comment by viirya** [comment]
cc @huaxingao @WeichenXu123

**Comment by viirya** [comment]
cc @HyukjinKwon

**Review by HyukjinKwon — COMMENTED** [review]
Took a quick look. Seems fine.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master and branch-3.1.

**Comment by zhengruifeng** [comment]
Late LGTM

**Pull request closed without merging**
