### PR TITLE
[SPARK-16321] Fixing performance regression when reading…

### PR DESCRIPTION
**Pull request by maver1ck**
## What changes were proposed in this pull request?

This PR add correct support for PPD when using non-vectorized Parquet reader.
## How was this patch tested?

Manual performance tests. Existing automatic tests.

### CODE REVIEW

**Comment by davies** [comment]
@maver1ck Thanks for sending out this, I'd prefer to merge #13701, there are already lots of discussions there.

**Comment by maver1ck** [comment]
@davies 
No problem.
I just want to isolate the reason of performance regression.

**Comment by srowen** [comment]
This should just be closed, no need to wait. It stays around and could even be reopened if needed.

**Comment by maver1ck** [comment]
OK.

**Pull request closed without merging**
