### PR TITLE
[SPARKR][MINOR] Add Xiangrui and Felix to maintainers

### PR DESCRIPTION
**Pull request by shivaram**
## What changes were proposed in this pull request?

This change adds Xiangrui Meng and Felix Cheung to the maintainers field in the package description.
## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by shivaram** [comment]
cc @mengxr @felixcheung 

FYI - This is mostly to ensure that we can have more maintainers who can update the CRAN submissions. This shouldn't affect anything else on the development side.

**Comment by felixcheung** [comment]
LGTM. I guess I should upgrade me spam filter then ;)

**Comment by shivaram** [comment]
Merging to master, branch-2.0

**Comment by felixcheung** [comment]
Oops, it looks like it is only suppose to be a single Maintainer?
https://cran.r-project.org/doc/manuals/r-release/R-exts.html#The-DESCRIPTION-file

It look like this in CRAN check output:
```
Maintainer: ‘Shivaram Venkataraman <shivaram@cs.berkeley.edu> Xiangrui Meng <meng@databricks.com> Felix Cheung <felixcheung_m@hotmail.com>’
```

Instead, we could put something like this in the DESCRIPTION file:
```
Authors@R: c(person("Shivaram", "Venkataraman", role = c("aut", "cre"),
		     email = "shivaram@cs.berkeley.edu"),
	      person("Xiangrui", "Meng", role = "aut"),
	      person("Felix", "Cheung", role = "aut"))
```
And omit Author, Maintainer fields.

**Comment by shivaram** [comment]
Hmm thats a good catch. Unfortunately it looks like CRAN only wants one person / one email address to be in the Maintainer field. This is also documented at http://r-pkgs.had.co.nz/description.html#author in the 'On CRAN' section. 

I don't mind the `Authors@R` format -- it will I think generate a `Maintainers:` and `Authors:` automatically from it. One thing that would be good to add is to add ASF website, JIRA, developer mailing lists. I think we can add it to the `URL` and `BugReports` fields ? @felixcheung Do you want to send a PR for this ?

**Pull request closed without merging**
