### PR TITLE
[SPARK-26718][SS][BRANCH-2.3] Fixed integer overflow in SS kafka rateLimit calculation

### PR DESCRIPTION
**Pull request by linehrr**
## What changes were proposed in this pull request?

Fix the integer overflow issue in rateLimit.

## How was this patch tested?

Pass the Jenkins with newly added UT for the possible case where integer could be overflowed.

### CODE REVIEW

**Comment by linehrr** [comment]
this is regarding back porting from https://github.com/apache/spark/pull/23652

**Comment by dongjoon-hyun** [comment]
ok to test

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Merged to `branch-2.3`.

**Comment by dongjoon-hyun** [comment]
Thank you, @linehrr !

**Pull request closed without merging**
