### PR TITLE
[SPARK-25559] [FOLLOW-UP] Add comments for partial pushdown of conjuncts in Parquet

### PR DESCRIPTION
**Pull request by gatorsmile**
## What changes were proposed in this pull request?
This is a follow up of https://github.com/apache/spark/pull/22574. Renamed the parameter and added comments.

## How was this patch tested?
N/A

### CODE REVIEW

**Comment by gatorsmile** [comment]
cc @dbtsai @cloud-fan

**Comment by dbtsai** [comment]
LGTM. Wait for the PR build. Thanks.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by dbtsai** [comment]
Thanks. Merged into master.

**Review by HyukjinKwon — COMMENTED** [review]
LGTM too

**Pull request closed without merging**
