### PR TITLE
[SPARK-14012][SQL] Extract VectorizedColumnReader from VectorizedParquetRecordReader

### PR DESCRIPTION
**Pull request by sameeragarwal**
## What changes were proposed in this pull request?

This is a minor followup on https://github.com/apache/spark/pull/11799 that extracts out the `VectorizedColumnReader` from `VectorizedParquetRecordReader` into its own file.
## How was this patch tested?

N/A (refactoring only)

### CODE REVIEW

**Comment by sameeragarwal** [comment]
cc @nongli

**Comment by rxin** [comment]
Did any code change?

**Comment by sameeragarwal** [comment]
No (we made all the changes in https://github.com/apache/spark/pull/11799)

**Comment by rxin** [comment]
Thanks - merging in master.

**Pull request closed without merging**
