### PR TITLE
[SPARK-30146][ML][PySpark] Add setWeightCol to GBTs in PySpark

### PR DESCRIPTION
**Pull request by huaxingao**
### What changes were proposed in this pull request?
add ```setWeightCol``` and ```setMinWeightFractionPerNode``` in Python side of ```GBTClassifier``` and ```GBTRegressor```

### Why are the changes needed?
https://github.com/apache/spark/pull/25926 added ```setWeightCol``` and ```setMinWeightFractionPerNode``` in GBTs on scala side. This PR will add ```setWeightCol``` and ```setMinWeightFractionPerNode``` in GBTs on python side

### Does this PR introduce any user-facing change?
Yes

### How was this patch tested?
doc test

### CODE REVIEW

**Review by srowen — COMMENTED** [review]
This just exposes a recently added feature in Python? LGTM pending tests. @zhengruifeng

**Comment by huaxingao** [comment]
@srowen Yes, it just exposes the recently added feature in Python.

**Comment by zhengruifeng** [comment]
Thanks for pinging me.
LGTM

**Review by zhengruifeng — APPROVED** [review]

**Comment by srowen** [comment]
Merged to master

**Comment by huaxingao** [comment]
Thanks! @srowen @zhengruifeng

**Pull request closed without merging**
