### PR TITLE
[SPARK-36228][SQL] Skip splitting a skewed partition when some map outputs are removed

### PR DESCRIPTION
**Pull request by cloud-fan**
### What changes were proposed in this pull request?

Sometimes, AQE skew join optimization can fail with NPE. This is because AQE tries to get the shuffle block sizes, but some map outputs are missing due to the executor lost or something.

This PR fixes this bug by skipping skew join handling if some map outputs are missing in the `MapOutputTracker`.

### Why are the changes needed?

bug fix

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

a new UT

### CODE REVIEW

**Comment by cloud-fan** [comment]
cc @viirya @yaooqinn @ulysses-you @JkSelf

**Review by ulysses-you — APPROVED** [review]

**Comment by viirya** [comment]
retest this please

**Review by viirya — APPROVED** [review]
pending CI

**Review by yaooqinn — APPROVED** [review]
lgtm

**Comment by JkSelf** [comment]
LGTM. +1

**Comment by cloud-fan** [comment]
thanks for the review, merging to master/3.2!

**Pull request closed without merging**
