### PR TITLE
SPARK-5815 [MLLIB] Deprecate SVDPlusPlus APIs that expose DoubleMatrix from JBLAS

### PR DESCRIPTION
**Pull request by srowen**
Deprecate SVDPlusPlus.run and introduce SVDPlusPlus.runSVDPlusPlus with return type that doesn't include DoubleMatrix

CC @mengxr

### CODE REVIEW

**Comment by srowen** [comment]
Retest this please

**Comment by maropu** [comment]
Look good though, it would be better to use SVDPlusPlus.run() as the name of an entry point for usability
because other libraries such TriangleCount and PageRan do so.

How about adding new some arguments so as to keep the signature?

**Comment by srowen** [comment]
@maropu The problem is that we are deprecating a `run()` method with the same arguments, but different return type. The new method has to have a different name. I agree although adding dummy arguments seems hackier. That said, feel free to suggest any legitimate other argument we might use as an excuse.

**Comment by maropu** [comment]
Understood.

I was thinking that not dummy arguments but the duplicated 'Conf' class in SVDPlusPlus
are used so as to solve the issue;

  /** Obsolete: Configuration parameters for SVDPlusPlus. */
  class Conf(
      var rank: Int,
       ....
      var gamma7: Double)
    extends Serializable

  /**Configuration parameters for SVDPlusPlus. */
  class SVDPlusPlusConf(
      var rank: Int,
       ....
      var gamma7: Double)
    extends Serializable

--- new
def run(edges: RDD[Edge[Double]], conf: SVDPlusPlusConf)
--- obsolete
def run(edges: RDD[Edge[Double]], conf: Conf)

Thought?

**Comment by srowen** [comment]
Heh, yeah I get it although it still feels worse than just accepting a different name. Anyone else have an opinion either way?

**Comment by mengxr** [comment]
@srowen Since we are definitely going to remove `run` in 1.4, we should state that explicitly in the message. After we remove `run`, are we going to deprecate `runSVDPlusPlus` and get `run` back?

**Comment by srowen** [comment]
@mengxr All of that is possible and makes some sense. I suppose the issue is then that anyone who calls the undeprecated `runSVDPlusPlus` method in 1.3.x. then finds it missing in 1.4.0. I suppose it can be retained but deprecated in 1.4! It's a little annoying but may be the minimum required to ensure smooth-ish transitions between releases.

**Comment by mengxr** [comment]
If that's the direction we are going to take, let's mention the route `run -> runSVDPlusPlus (1.3) -> run (1.4)` in the deprecation message and the doc, and then mark `runSVDPlusPlus` `@Experimental`.

**Comment by mengxr** [comment]
LGTM. Merged into master and branch-1.3. Thanks!

**Pull request closed without merging**
