### PR TITLE
[SPARK-24609][ML][DOC] PySpark/SparkR doc doesn't explain RandomForestClassifier.featureSubsetStrategy well

### PR DESCRIPTION
**Pull request by zhengruifeng**
## What changes were proposed in this pull request?
update doc of RandomForestClassifier.featureSubsetStrategy

## How was this patch tested?
local built doc

rdoc:
default

pydoc:
default

### CODE REVIEW

**Review by felixcheung — APPROVED** [review]

**Comment by felixcheung** [comment]
what's changed? it was forced pushed so I can't tell what's updated

**Comment by zhengruifeng** [comment]
@felixcheung  I have to force push it so as to change the git username. I will look for what happend

**Comment by zhengruifeng** [comment]
retest this please

**Review by felixcheung — APPROVED** [review]
LGTM

**Review by holdenk — APPROVED** [review]
Python side looks good to me.

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
