### PR TITLE
[MINOR][CORE][SQL][FOLLOWUP] Add missing s prefix to enable string interpolation

### PR DESCRIPTION
**Pull request by EnricoMi**
### What changes were proposed in this pull request?
Adds missing `s` prefix to enable string interpolation. Complements #38297.

### Why are the changes needed?
Strings will not contain substituted values but variable names.

### Does this PR introduce _any_ user-facing change?
Log messages will change.

### How was this patch tested?
Not tested.

### CODE REVIEW

**Comment by EnricoMi** [comment]
@MaxGekk @itholic here are some more places

thanks @gaoyajun02

**Review by HyukjinKwon — APPROVED** [review]

**Review by MaxGekk — APPROVED** [review]

**Review by itholic — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]

**Comment by srowen** [comment]
Can you retrigger tests? there was an unrelated build error earlier

**Comment by EnricoMi** [comment]
Rebased with master, all green.

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
