### PR TITLE
[SPARK-29463][SQL] move v2 commands to a new file

### PR DESCRIPTION
**Pull request by cloud-fan**
### What changes were proposed in this pull request?

move the v2 command logical plans from `basicLogicalOperators.scala` to a new file `v2Commands.scala`

### Why are the changes needed?

As we keep adding v2 commands, the `basicLogicalOperators.scala` grows bigger and bigger. It's better to have a separated file for them.

### Does this PR introduce any user-facing change?

no

### How was this patch tested?

not needed

### CODE REVIEW

**Comment by cloud-fan** [comment]
cc @rdblue @brkyvz @imback82 

also cc @gatorsmile @dongjoon-hyun , I know there is a concern about cross-file code movement, but I think this case is fine because v2 commands are new, they don't have much commit history.

**Review by dongjoon-hyun — APPROVED** [review]
It's always case-by-case, and for this one, +1, LGTM.

**Comment by cloud-fan** [comment]
Another thing I'd like to discuss is the statement plans. They are in the package `org.apache.spark.sql.catalyst.plans.logical.sql` which is a little weird to me as `sql` is not a good sub-package name in Spark SQL.

We should probably move them to `org.apache.spark.sql.catalyst.plans.logical.statement`, or a new file `statements.scala` under `org.apache.spark.sql.catalyst.plans.logical` to be consistent with v2 commands.

**Review by imback82 — APPROVED** [review]
LGTM!

**Comment by imback82** [comment]
> We should probably move them to `org.apache.spark.sql.catalyst.plans.logical.statement`, or a new file `statements.scala` under `org.apache.spark.sql.catalyst.plans.logical` to be consistent with v2 commands.

Either approach sounds good to me. But +1 for the latter (`statements.scala`).

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Merged to master. Thank you, @cloud-fan and @imback82 .
Yes. For the `statements.scala`, let's discuss in the another PR.

**Pull request closed without merging**
