### PR TITLE
[SPARK-15525][SQL][BUILD] Upgrade ANTLR4 SBT plugin

### PR DESCRIPTION
**Pull request by hvanhovell**
## What changes were proposed in this pull request?

The ANTLR4 SBT plugin has been moved from its own repo to one on bintray. The version was also changed from `0.7.10` to `0.7.11`. The latter actually broke our build (@ihji has fixed this by also adding `0.7.10` and others to the bin-tray repo).

This PR upgrades the SBT-ANTLR4 plugin and ANTLR4 to their most recent versions (`0.7.11`/`4.5.3`). I have also removed a few obsolete build configurations.
## How was this patch tested?

Manually running SBT/Maven builds.

### CODE REVIEW

**Comment by hvanhovell** [comment]
cc @rxin @MLnick @vanzin (could you take a look at the build)

**Comment by vanzin** [comment]
LGTM.

**Comment by MLnick** [comment]
Confirmed `build/sbt package` works and the plugin dep resolves.

**Comment by srowen** [comment]
LGTM

**Comment by rxin** [comment]
Merging in master/2.0.

**Pull request closed without merging**
