### PR TITLE
[SPARK-39665][INFRA] Bump workflow versions in GitHub Actions

### PR DESCRIPTION
**Pull request by ArjunSharda**
This pull requests bumps some of the workflow versions as some are outdated. 
*Note, this has not been tested with an IDE, I just did some basic changes I spotted.

### CODE REVIEW

**Review by HyukjinKwon — COMMENTED** [review]
@ArjunSharda mind taking a look at https://spark.apache.org/contributing.html? We should file a JIRA, fix the title format, feel the PR description format, etc.

**Comment by ArjunSharda** [comment]
> @ArjunSharda mind taking a look at https://spark.apache.org/contributing.html? We should file a JIRA, fix the title format, feel the PR description format, etc.

Hey, I thought a JIRA would not be needed as it's a minor change with versions.

**Comment by HyukjinKwon** [comment]
Let's file a JIRA. I think we should track it with a JIRA since technically we're upgrading the major versions of the plugins.

**Comment by ArjunSharda** [comment]
> Let's file a JIRA. I think we should track it with a JIRA since technically we're upgrading the major versions of the plugins.

Alright, made. https://issues.apache.org/jira/browse/SPARK-39665

**Review by dongjoon-hyun — COMMENTED** [review]
May I ask the reason why we need this, @ArjunSharda ?

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
If there is no known issues affecting Apache Spark repository, let's avoid any risk by holding on this PR until `v3` become stable. As we see in the release history, it seems to be still changing in a fast pace unlike `v2`.
- https://github.com/actions/cache/tags

**Comment by ArjunSharda** [comment]
> If there is no known issues affecting Apache Spark repository, let's avoid any risk by holding on this PR until `v3` become stable. As we see in the release history, it seems to be still changing in a fast pace unlike `v2`.
> 
> * https://github.com/actions/cache/tags

I can revert the cache versions

**Comment by dongjoon-hyun** [comment]
Do you think the other GitHub Actions are stabler? IMO, the situation is not different. There is no point to track one by one in case of all GitHub Action. I'd recommend to close this PR.

> > If there is no known issues affecting Apache Spark repository, let's avoid any risk by holding on this PR until `v3` become stable. As we see in the release history, it seems to be still changing in a fast pace unlike `v2`.
> > 
> > * https://github.com/actions/cache/tags
> 
> I can revert the cache versions

**Comment by ArjunSharda** [comment]
> Do you think the other GitHub Actions are stabler? IMO, the situation is not different. There is no point to track one by one in case of all GitHub Action. I'd recommend to close this PR.
> 
> > > If there is no known issues affecting Apache Spark repository, let's avoid any risk by holding on this PR until `v3` become stable. As we see in the release history, it seems to be still changing in a fast pace unlike `v2`.
> > > 
> > > * https://github.com/actions/cache/tags
> > 
> > 
> > I can revert the cache versions

I think as per what I saw except setup-java it should be okay.

**Comment by dongjoon-hyun** [comment]
Yes, setup-java is especially aggressive. So, @ArjunSharda , your approach initially didn't consider much about the GitHub Action's upgrade cadence and the risk on Apache Spark community side. To prevent accidental merging, let me close this PR. We can still continue our discussion about the necessity of this PR content.
> I think as per what I saw except setup-java it should be okay.

**Pull request closed without merging**
