### PR TITLE
[MINOR] Bump SparkR and PySpark version to 2.3.0.

### PR DESCRIPTION
**Pull request by HyukjinKwon**
## What changes were proposed in this pull request?

#17753 bumps master branch version to 2.3.0-SNAPSHOT, but it seems SparkR and PySpark version were omitted.

ditto of https://github.com/apache/spark/pull/16488 / https://github.com/apache/spark/pull/17523

## How was this patch tested?

N/A

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
I found this when testing https://github.com/apache/spark/pull/18335. I thought it is odd that CRAN check generated `SparkR_2.2.0.tar.gz` in the master. I double checked it now generates `SparkR_2.3.0.tar.gz`.

**Comment by HyukjinKwon** [comment]
cc @srowen and @felixcheung

**Review by srowen — APPROVED** [review]
I think this particular field gets auto-updated during the build anyway, IIRC, so it won't matter in the way `2.3.0-SNAPSHOT` matters to Maven, but to avoid confusion I think we can update it

**Comment by felixcheung** [comment]
+1 with what srowen says. 
ditto with python actually https://github.com/apache/spark/blob/master/python/pyspark/version.py
i wonder if we should simply change the release/branch process to update everything

**Review by felixcheung — COMMENTED** [review]
LGTM, but how about updating python too - save one less PR

**Review by felixcheung — APPROVED** [review]

**Review by srowen — APPROVED** [review]
@HyukjinKwon you are also welcome to add a note to `release-process.md` in the `spark-website` repo, but that's optional (and a separate change of course)

**Comment by srowen** [comment]
Merged to master

**Comment by HyukjinKwon** [comment]
Sure, I will do. Thank you.

**Pull request closed without merging**
