### PR TITLE
[SPARK-37846][TESTS] Fix test logic by getting sleep interval in task

### PR DESCRIPTION
**Pull request by wzhfy**
### What changes were proposed in this pull request?

Currently in the tests, `TaskContext.getPartitionId()` is called at driver side, so the sleep interval is always 100ms, which is not expected and makes some tests flaky (on my env it's mainly the test `"verify that an already running task which is going to cache data succeeds on a decommissioned executor after one task ends but before job ends"`).

### Why are the changes needed?

Correct the test logic and make tests stable.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

By existing tests. I also iterated 10 times on the env where the test was flaky, after the change it never failed.

### CODE REVIEW

**Comment by wzhfy** [comment]
cc @Ngone51 @agrawaldevesh

**Comment by wzhfy** [comment]
cc @Ngone51 @agrawaldevesh, could you take a look?

**Review by srowen — APPROVED** [review]

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
(I think it's best to file a JIRA BTW)

**Comment by wzhfy** [comment]
> (I think it's best to file a JIRA BTW)

added jira [SPARK-37846](https://issues.apache.org/jira/browse/SPARK-37846), thanks for the reminder

**Comment by HyukjinKwon** [comment]
Merged to master

**Comment by Ngone51** [comment]
Late LGTM. Good catch @wzhfy !

**Pull request closed without merging**
