### PR TITLE
[SPARK-14261][SQL] Memory leak in Spark Thrift Server

### PR DESCRIPTION
**Pull request by dosoft**
Fixed memory leak (HiveConf in the CommandProcessorFactory)

### CODE REVIEW

**Comment by yhuai** [comment]
ok to test

**Comment by yhuai** [comment]
@dosoft Thank you for the PR. What is the memory footprint of a leaked driver?

**Comment by rxin** [comment]
We should backport this into 1.6 as well.

**Comment by rxin** [comment]
I'm going to merge this in master/2.0/1.6. Thanks.

**Pull request closed without merging**
