### PR TITLE
[TEST janino] v3.1.12 VS v3.1.9

### PR DESCRIPTION
**Pull request by panbingkun**

### CODE REVIEW

**Comment by panbingkun** [comment]
performance comparison:

**Comment by panbingkun** [comment]
https://janino-compiler.github.io/janino/

**Comment by LuciferYang** [comment]
Are there any conclusions from this test?

**Comment by panbingkun** [comment]
> Are there any conclusions from this test?

From the testing, it seems that there is no significant difference in performance. 
Regarding the version of `janino`, we seem to be lagging behind a lot, as follows:
image

**Comment by LuciferYang** [comment]
Since this component is very critical, if there is no noticeable performance enhancement or critical bug fix, I recommend maintaining the use of the current version.
cc @cloud-fan @dongjoon-hyun

**Comment by panbingkun** [comment]
Actually, it has some bug fixes, such as typical ones:
[spark compilation failed with ArrayIndexOutOfBoundsException](https://github.com/janino-compiler/janino/issues/208)

**Comment by LuciferYang** [comment]
> Actually, it has some bug fixes, such as typical ones: [Fixed issue `spark compilation failed with ArrayIndexOutOfBoundsException`](https://github.com/janino-compiler/janino/issues/208)

Can we add the corresponding test cases in the current pr ?

**Comment by LuciferYang** [comment]
Will you continue to push forward this one?

**Pull request closed without merging**
