### PR TITLE
[MINOR] Renamed variables in SparkKMeans.scala, LocalKMeans.scala and kmeans.py to simplify readability

### PR DESCRIPTION
**Pull request by pippobaudos**
With the previous syntax it could look like that the reduceByKey sums separately abscissas and ordinates of some 2D points. Perhaps in this way should be easier to understand the example, especially for who is starting the functional programming like me now.

### CODE REVIEW

**Comment by srowen** [comment]
ok to test

**Comment by srowen** [comment]
OK, pretty trivial but I see your point. There is no lat/lon here though. Also can you make the title descriptive? this doesn't describe anything about the change.

**Comment by pippobaudos** [comment]
Sorry Sean, you are 100% right, just renamed the title and edited the description to make it more descriptive

**Comment by srowen** [comment]
There are two other instances of the same express; one is in `LocalKMeans.scala` and one is in `kmeans.py`. How about updating those too?

**Comment by pippobaudos** [comment]
No problems. I'll do it tonight

**Comment by srowen** [comment]
Jenkins retest this please

**Comment by srowen** [comment]
I can't imagine this change has any functional impact, but since we're not in a hurry, will let jenkins have another go.

**Pull request closed without merging**
