### PR TITLE
[SPARK-11938][PySpark] Expose numFeatures in all ML PredictionModel for PySpark

### PR DESCRIPTION
**Pull request by vectorijk**
## What changes were proposed in this pull request?

JIRA: [https://issues.apache.org/jira/browse/SPARK-11938](https://issues.apache.org/jira/browse/SPARK-11938)

[SPARK-9715](https://issues.apache.org/jira/browse/SPARK-9715) provided support for numFeatures in all ML `PredictionModel`s, we should also expose it at PySpark.
## How was this patch tested?

Unit Test for PySpark

### CODE REVIEW

**Comment by vectorijk** [comment]
cc @jkbradley @yanboliang @Lewuathe

**Comment by lins05** [comment]
Seems the `numFeatures` property is repeated in all these  classification and regression classes. What about adding a `HasNumFeatures` mixin class and move the `numFeatures` property implementation there?

**Comment by MLnick** [comment]
@vectorijk this is covered in #12889 by @holdenk

**Comment by vectorijk** [comment]
@MLnick Thanks! I will close this PR.

**Pull request closed without merging**
