### PR TITLE
[SPARK-29615][SQL]Add a new insertInto method with byName parameter in DataFrameWriter.

### PR DESCRIPTION
**Pull request by fuwhu**
### What changes were proposed in this pull request?
Add a new insertInto method with byName parameter in DataFrameWriter.

### Why are the changes needed?
To provide Spark user a new insertInto method with byName parameter to avoid possible confusion about whether match columns by column name.

### Does this PR introduce any user-facing change?
Yes, added one insertInto method in DataFrameWriter.

### How was this patch tested?
Unit test

### CODE REVIEW

**Comment by maropu** [comment]
I'm not 100% sure that this feature is useful for users. Is it not enough just to verify the schemas of query output and a table before insersion? Or, any existing database-like systems support this by-name matches in insersion?

**Comment by fuwhu** [comment]
> I'm not 100% sure that this feature is useful for users. Is it not enough just to verify the schemas of query output and a table before insersion? Or, any existing database-like systems support this by-name matches in insersion?

I proposed this change because we encountered some problem in our test environment.
In our case, one developer inserted a data frame into hive table, the data frame has exactly same columns as the hive table, but the order is a bit different. Due to the wrong column order, spark take a non-partitioning column as partition column of hive table, and this column has huge cardinality, which lead to huge amount of files and folders created in our test environment and made our name node crash.

When we write SQL query to insert data, we can hardly trigger such problem, but if we use the  DataFrameWriter.insertInto API, it may cause some confusion that developer may assume Spark matches the columns by name automatically.

I just want to add a new insertInto method to make Spark user be aware of the action that Spark take for insertInto API.
WDYT?

**Comment by maropu** [comment]
> When we write SQL query to insert data, we can hardly trigger such problem, but if we use the DataFrameWriter.insertInto API, it may cause some confusion that developer may assume Spark matches the columns by name automatically.

It seems this is a document-related issue?

**Comment by fuwhu** [comment]
@maropu ok, make sense, thanks. Will close this PR.

**Comment by combinatorist** [comment]
It's not just verifying before insert that columns are aligned. Ideally, the method would allow you to insert _even when you already know the columns are not aligned_.

You can easily get the same columns out of order when you use `withColumn` / `dropColumn` / `withColumnRenamed` type transformations.

Also, if spark supports unionByName, then why not insertByName (or insert with byName option). If it's not useful at insert, should we simplify the methods for union as well?

**Comment by combinatorist** [comment]
Also, note databricks has this feature: https://docs.databricks.com/en/sql/language-manual/sql-ref-syntax-dml-insert-into.html#:~:text=%5D%20)%20%7C-,BY%20NAME,-%5D%0A%20%20%20%20query%0A%0AINSERT

**Pull request closed without merging**
