### PR TITLE
[SPARK-40612][CORE] Fixing the principal used for delegation token renewal on non-YARN resource managers   

### PR DESCRIPTION
**Pull request by attilapiros**
### What changes were proposed in this pull request?

When the delegation token is fetched at the first time (see the `fetchDelegationTokens()` call at `HadoopFSDelegationTokenProvider#getTokenRenewalInterval()`) the principal is the current user but at the subsequent token renewals (see `obtainDelegationTokens()` where `getTokenRenewer()` is used to identify the principal) are using a MapReduce/Yarn specific principal even on resource managers different from YARN.

This PR fixes `getTokenRenewer()` to use the current user instead of `org.apache.hadoop.mapred.Master.getMasterPrincipal(hadoopConf)` when the resource manager is not YARN. 
The condition `(master != null && master.contains("yarn"))` is the very same what we already have in `hadoopFSsToAccess()`.

I would like to say thank you for @squito who have done the investigation regarding of the problem which lead to this PR.

### Why are the changes needed?

To avoid `org.apache.hadoop.security.AccessControlException: Permission denied.` for long running applications.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Manually.

### CODE REVIEW

**Comment by attilapiros** [comment]
cc @dongjoon-hyun @viirya

**Comment by dongjoon-hyun** [comment]
Thank you for pinging me, @attilapiros .

**Comment by dongjoon-hyun** [comment]
cc @gaborgsomogyi , too

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM from my side.

**Review by viirya — APPROVED** [review]

**Review by HyukjinKwon — APPROVED** [review]

**Review by weixiuli — APPROVED** [review]

**Review by gaborgsomogyi — APPROVED** [review]
LGTM.

**Comment by dongjoon-hyun** [comment]
Thank you, @attilapiros , @viirya , @HyukjinKwon , @weixiuli , @gaborgsomogyi ! Especially, @gaborgsomogyi !
Merged to master/3.3/3.2.

**Pull request closed without merging**
