### PR TITLE
dataset - toIterator

### PR DESCRIPTION
**Pull request by lxian**
### What changes were proposed in this pull request?
Add a iterator method to dataset

### Why are the changes needed?
The new iterator method will not submit one job for on partition like toLocalIterator() to save scheduling overhead

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

unit test is added

### CODE REVIEW

**Comment by srowen** [comment]
Why does this help vs collect() and iterating over that?
toLocalIterator is optimized over what you are trying to do here on purpose

**Comment by HyukjinKwon** [comment]
Yeah .. there;s no benefit on this ..

**Comment by lxian** [comment]
Correct me if I am wrong. I think toLocalIterator() is going to submit multiple jobs as you iterate through the result.

In my case, I would like to submit only one job and collect all results from all partitions to the driver first. And then do the iteration. I think in this way, I can get the result faster (I can run all partitions in parallel and save the scheduling overhead) and also save the memory on deserialization.

**Comment by srowen** [comment]
Just collect the results, then get an iterator on it then

**Pull request closed without merging**
