### PR TITLE
[SPARK-26329][CORE][FOLLOWUP] Fix ExecutorMetricsPoller class comment miss parameter

### PR DESCRIPTION
**Pull request by AngersZhuuuu**
### What changes were proposed in this pull request?
Fix ExecutorMetricsPoller class comment comment miss parameter

### Why are the changes needed?
Fix comment comment miss parameter

### Does this PR introduce any user-facing change?
NO

### How was this patch tested?
Not need

### CODE REVIEW

**Comment by AngersZhuuuu** [comment]
cc @HyukjinKwon 
Split to two pr, thanks

**Comment by HyukjinKwon** [comment]
No~ @AngersZhuuuu. I meant to make one minor PR to fix many typos instead of making one PR to fix a couple of typos.

**Comment by AngersZhuuuu** [comment]
> No~ @AngersZhuuuu. I meant to make one minor PR to fix many typos instead of making one PR to fix a couple of typos.

emmmm, One pr for more same type  typo, not one pr for different typo?

**Comment by HyukjinKwon** [comment]
Yes, because it costs Jenkins, review and merge. Also, it's difficult to maintain such PRs e.g., backporting. Let's fix them in batch - it's not worthwhile to make a PR for fixing a couple of typos.

**Comment by AngersZhuuuu** [comment]
> Yes, because it costs Jenkins, review and merge. Also, it's difficult to maintain such PRs e.g., backporting. Let's fix them in batch - it's not worthwhile to make a PR for fixing a couple of typos.

ok, I will keep these two pr, and will add more modify to them  when I read some code and find such case.
Thanks a lot.

**Comment by dongjoon-hyun** [comment]
Like @HyukjinKwon 's advice, we prefer to do this kind of clean up together.
BTW, at that time, this PR will not be a followup of SPARK-26329. It should be an independent documentation fix PR. For now, I close this PR. Please feel free to reuse your code and reopen it when you are ready.

**Pull request closed without merging**
