### PR TITLE
[SPARK-10963] [Streaming] [Kafka] make KafkaCluster public

### PR DESCRIPTION
**Pull request by koeninger**

### CODE REVIEW

**Comment by srowen** [comment]
Looks OK to me.

**Comment by srowen** [comment]
@tdas are you OK with this one?

**Comment by tdas** [comment]
there are a number of classes that this exposes. I have to spend some time to think whether it is worth exposing all of that.

**Comment by srowen** [comment]
@tdas what do you think? just trying to get some resolution on this and I know you wanted to think.

**Comment by srowen** [comment]
@tdas do you mind if I merge this?

**Comment by yhilem** [comment]
Which version of the spark the merge is planned?

**Comment by yhilem** [comment]
Which spark version the merge of this pull request is planned?

**Comment by yhilem** [comment]
For which spark version the merge of this pull request is planned?

**Comment by koeninger** [comment]
@tdas @srowen Can we either get this merged, or officially close off the possibility of merging it?  

People are still raising specific issues on a fairly regular basis that would be solved in general by this PR (e.g. https://issues.apache.org/jira/browse/SPARK-13106), and it would be good to have clear expectations one way or the other.

**Comment by srowen** [comment]
@tdas I'd like to merge unless you object. I also find this a useful developer API.

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
