### PR TITLE
[SPARK-48016][SQL][3.4] Fix a bug in try_divide function when with decimals

### PR DESCRIPTION
**Pull request by gengliangwang**
### What changes were proposed in this pull request?

 Currently, the following query will throw DIVIDE_BY_ZERO error instead of returning null
 ```
SELECT try_divide(1, decimal(0)); 
```

This is caused by the rule `DecimalPrecision`:
```
case b @ BinaryOperator(left, right) if left.dataType != right.dataType =>
  (left, right) match {
 ...
    case (l: Literal, r) if r.dataType.isInstanceOf[DecimalType] &&
        l.dataType.isInstanceOf[IntegralType] &&
        literalPickMinimumPrecision =>
      b.makeCopy(Array(Cast(l, DataTypeUtils.fromLiteral(l)), r)) 
```
The result of the above makeCopy will contain `ANSI` as the `evalMode`, instead of `TRY`.
This PR is to fix this bug by replacing the makeCopy method calls with withNewChildren

### Why are the changes needed?

Bug fix in try_* functions.

### Does this PR introduce _any_ user-facing change?

Yes, it fixes a long-standing bug in the try_divide function. 

### How was this patch tested?

New UT

### Was this patch authored or co-authored using generative AI tooling?

No

### CODE REVIEW

**Comment by gengliangwang** [comment]
This one is to backport https://github.com/apache/spark/pull/46286 to branch 3.4

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM (if CI passes)

**Comment by dongjoon-hyun** [comment]
Thank you, @gengliangwang .

**Review by HyukjinKwon — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Could you re-trigger Docker integration test, @gengliangwang ?

**Comment by gengliangwang** [comment]
Merging to 3.4

**Pull request closed without merging**
