### PR TITLE
[SPARK-49840][INFRA] Use `MacOS 15` in `build_maven_java21_macos14.yml`

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to upgrade `MacOS` from `14` to `15` in `build_maven_java21_macos14.yml`.

### Why are the changes needed?

To use the latest MacOS as a part of Apache Spark 4.0.0 preparation.
- https://github.com/actions/runner-images/blob/main/images/macos/macos-15-arm64-Readme.md

### Does this PR introduce _any_ user-facing change?

No. This is an infra change.

### How was this patch tested?

N/A.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Could you review this when you have some time, @huaxingao ?

**Comment by dongjoon-hyun** [comment]
Also, cc @viirya and @HyukjinKwon

**Review by viirya — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @viirya .

**Comment by dongjoon-hyun** [comment]
Merged to master for Apache Spark 4.0.0.

**Review by HyukjinKwon — COMMENTED** [review]
LGTM

**Pull request closed without merging**
