### PR TITLE
[SPARK-26300][SS] Remove a redundant `checkForStreaming` call

### PR DESCRIPTION
**Pull request by 10110346**
## What changes were proposed in this pull request?
If `checkForContinuous`  is called ( `checkForStreaming` is called in `checkForContinuous`  ), the `checkForStreaming`  mothod  will be called twice in `createQuery` , this is not necessary,  and the `checkForStreaming` method has a lot of statements,  so it's better to remove one of them.

## How was this patch tested?

Existing unit tests in `StreamingQueryManagerSuite` and `ContinuousAggregationSuite`

### CODE REVIEW

**Comment by 10110346** [comment]
cc @cloud-fan

**Review by HeartSaVioR — APPROVED** [review]
LGTM. Btw this might be also OK to just be handled as MINOR.

**Comment by cloud-fan** [comment]
cc @zsxwing

**Review by gaborgsomogyi — APPROVED** [review]
LGTM, also +1 on make it MINOR.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. It's logical.

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by dongjoon-hyun** [comment]
cc @tdas , too.

**Comment by 10110346** [comment]
Retest this please.

**Comment by dongjoon-hyun** [comment]
Merged to master.

**Comment by dongjoon-hyun** [comment]
Thank you, @10110346 , @HeartSaVioR , @cloud-fan , @gaborgsomogyi .

**Pull request closed without merging**
