### PR TITLE
[SPARK-25175][SQL] Field resolution should fail if there is ambiguity for ORC native data source table persisted in metastore

### PR DESCRIPTION
**Pull request by seancxmao**
## What changes were proposed in this pull request?
Apache Spark doesn't create Hive table with duplicated fields in both case-sensitive and case-insensitive mode. However, if Spark creates ORC files in case-sensitive mode first and create Hive table on that location, where it's created. In this situation, field resolution should fail in case-insensitive mode. Otherwise, we don't know which columns will be returned or filtered. Previously, SPARK-25132 fixed the same issue in Parquet.

Here is a simple example:

```
val data = spark.range(5).selectExpr("id as a", "id * 2 as A")
spark.conf.set("spark.sql.caseSensitive", true)
data.write.format("orc").mode("overwrite").save("/user/hive/warehouse/orc_data")

sql("CREATE TABLE orc_data_source (A LONG) USING orc LOCATION '/user/hive/warehouse/orc_data'")
spark.conf.set("spark.sql.caseSensitive", false)
sql("select A from orc_data_source").show
+---+
|  A|
+---+
|  3|
|  2|
|  4|
|  1|
|  0|
+---+
```

See #22148 for more details about parquet data source reader.

## How was this patch tested?
Unit tests added.

### CODE REVIEW

**Comment by seancxmao** [comment]
@dongjoon-hyun @cloud-fan @gatorsmile Could you please kindly review this?

**Comment by dongjoon-hyun** [comment]
@seancxmao . Could you explain why we need this PR? Apache Spark 2.3.1 already shows exceptions like the following for the case (for both ORC and Parquet), doesn't it?

```scala
scala> spark.version
res5: String = 2.3.1

scala> sql("set spark.sql.caseSensitive=true")
scala> spark.read.orc("/tmp/o").printSchema
root
 |-- a: integer (nullable = true)
 |-- A: integer (nullable = true)

scala> sql("set spark.sql.caseSensitive=false")
scala> spark.read.orc("/tmp/o").printSchema
18/09/01 20:06:05 WARN DataSource: Found duplicate column(s) in the data schema and the partition schema: `a`;
org.apache.spark.sql.AnalysisException: Found duplicate column(s) in the data schema: `a`;
```

**Comment by seancxmao** [comment]
@dongjoon-hyun I have updated PR description to explain in more details. As you mentioned, this PR is specific to the case when reading from data source table persisted in metastore.

**Comment by dongjoon-hyun** [comment]
Thank you, @seancxmao . I'll review tonight again.

**Comment by dongjoon-hyun** [comment]
Sorry, but I'm still feeling that this PR is losing focus. How about mentioning what you do in this PR like the following?

```
Apache Spark doesn't create Hive table with duplicated fields in both case-sensitive and
case-insensitive mode. However, if Spark creates ORC files in case-sensitive mode first
and create Hive table on that location, it's created. In this situation, field resolution should
fail in case-insensitive mode. Otherwise, we don't know which columns will be returned or
filtered. Previously, SPARK-25132 fixed the same issue in Parquet.

Here is a simple example:
...
```

**Comment by dongjoon-hyun** [comment]
Thank you, @seancxmao .
Also, I made a PR to you, https://github.com/seancxmao/spark/pull/1 , to simply the logic.
Could you review and merge that if you think that's okay?

**Comment by cloud-fan** [comment]
ok to test

**Comment by dongjoon-hyun** [comment]
@seancxmao . I mistook yesterday. Could you restore to your first commit? In the first commit, please adjust the indentation at [line 140](https://github.com/apache/spark/pull/22262/commits/366bb35ad62edb8e6707e65c681a5b9001cc868e#diff-3fb8426b690ab771c4f67f9cad336498R140). Sorry for the back and forth!

**Comment by dongjoon-hyun** [comment]
BTW, I think we need this duplication check in case-sensitive mode, too. I'll ping on previous Parquet PR.

**Comment by seancxmao** [comment]
> ... we need this duplication check in case-sensitive mode ...
Do you mean we may define ORC/Parquet schema with identical field names (even in the same letter case)? Would you please explain a bit more on this?

**Comment by dongjoon-hyun** [comment]
The following is the sequence.

```scala
scala> sql("insert overwrite local directory '/tmp/parquet' stored as parquet select 1 id, 2 id")
```

```
$ parquet-tools schema /tmp/parquet
message hive_schema {
  optional int32 id;
  optional int32 id;
}
```

```scala
scala> sql("create table parquet(id int) USING parquet LOCATION '/tmp/parquet'")
res3: org.apache.spark.sql.DataFrame = []

scala> sql("select * from parquet")
res4: org.apache.spark.sql.DataFrame = [id: int]

scala> sql("select * from parquet").show
18/09/07 23:31:03 ERROR Executor: Exception in task 0.0 in stage 2.0 (TID 2)
java.lang.RuntimeException: [id] INT32 was added twice
```

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

cc @cloud-fan and @gatorsmile

**Comment by dongjoon-hyun** [comment]
Thank you, @seancxmao .

**Comment by seancxmao** [comment]
@dongjoon-hyun Thank you!

**Pull request closed without merging**
