### PR TITLE
[SPARK-3431] [WIP] Parallelize Scala/Java test execution

### PR DESCRIPTION
**Pull request by nchammas**
This is currently a work in progress to experiment with various options for parallelizing our Scala/Java tests using sbt.

### CODE REVIEW

**Comment by JoshRosen** [comment]
Jenkins, retest this please.

**Comment by nchammas** [comment]
Sounds good. Thanks for following up; I haven't had a chance to look over this PR in a while.

(Btw, I rebased for kicks. You can disregard the coming test run.)

**Comment by nchammas** [comment]
Jenkins, retest this please.

**Comment by nchammas** [comment]
Jenkins, retest this please.

**Comment by nchammas** [comment]
Not sure what to make of this @JoshRosen, but there are [several more test failures](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/25870/testReport/) in the most recent run than the 3 we thought we were down to.

For example, why would this DriverSuite test fail?
* Test failure: https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/25870/testReport/org.apache.spark/DriverSuite/driver_should_exit_after_finishing/
* Test code: https://github.com/apache/spark/blob/9a151ce58b3e756f205c9f3ebbbf3ab0ba5b33fd/core/src/test/scala/org/apache/spark/DriverSuite.scala#L31

**Comment by JoshRosen** [comment]
Jenkins, retest this please.

**Comment by nchammas** [comment]
Jenkinmensch, retest this please.

**Comment by pwendell** [comment]
I'd like to close this issue for now pending further development.

**Pull request closed without merging**
