### PR TITLE
[SPARK-29642][SS] Change the element type of underlying array to UnsafeRow for ContinuousRecordEndpoint

### PR DESCRIPTION
**Pull request by HeartSaVioR**
### What changes were proposed in this pull request?

This patch fixes the bug that `ContinuousMemoryStream[String]` throws error regarding ClassCastException - cast String to UTFString. This is because ContinuousMemoryStream and ContinuousRecordEndpoint uses origin input as it is for underlying data structure of Row, and encoding is missing here.

To force encoding, this patch changes the element type of underlying array to UnsafeRow instead of Any for ContinuousRecordEndpoint - ContinuousMemoryStream and TextSocketContinuousStream are modified to reflect the change.

### Why are the changes needed?

Above section describes the bug.

### Does this PR introduce any user-facing change?

No.

### How was this patch tested?

Add new UT to check for availability on couple of types.

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
cc. @tdas @zsxwing @jose-torres @gaborgsomogyi

**Comment by vanzin** [comment]
Looks good as far as I can tell.

**Comment by vanzin** [comment]
retest this please

**Comment by vanzin** [comment]
Merging to master.

**Comment by HeartSaVioR** [comment]
Thanks for reviewing and merging!

**Pull request closed without merging**
