### PR TITLE
[SPARK-15375][SQL][Streaming] Add ConsoleSink to structure streaming

### PR DESCRIPTION
**Pull request by jerryshao**
## What changes were proposed in this pull request?

Add ConsoleSink to structure streaming, user could use it to display dataframes on the console (useful for debugging and demostrating), similar to the functionality of `DStream#print`, to use it:

```
    val query = result.write
      .format("console")
      .trigger(ProcessingTime("2 seconds"))
      .startStream()
```
## How was this patch tested?

local verified.

Not sure it is suitable to add into structure streaming, please review and help to comment, thanks a lot.

### CODE REVIEW

**Comment by rxin** [comment]
Seem like a good idea to me. cc @marmbrus

**Comment by marmbrus** [comment]
I agree this would be useful for debugging.  Can we plug it in as a `StreamSinkProvider` instead of hard coding an `if` into the `DataSource` resolver?

**Comment by jerryshao** [comment]
Sure, let me change the code.

**Comment by rxin** [comment]
Merging in master/2.0. Thanks @jerryshao!

**Pull request closed without merging**
