### PR TITLE
[SPARK-37407][PYTHON] Inline type hints for python/pyspark/ml/functions.py

### PR DESCRIPTION
**Pull request by dchvn**
### What changes were proposed in this pull request?
Inline type hints for python/pyspark/ml/functions.py

### Why are the changes needed?
We can take advantage of static type checking within the functions by inlining the type hints.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Existing tests

### CODE REVIEW

**Comment by dchvn** [comment]
cc @zero323 Please take a look when you have time! Thanks 😄

**Comment by zero323** [comment]
Same as https://github.com/apache/spark/pull/34680#issuecomment-975397090. Ignores here will be obsolete after SPARK-37152 is completed.

**Comment by dchvn** [comment]
cc @zero323 , please review this PR again. Many thanks :smile:

**Comment by dchvn** [comment]
cc @zero323

**Review by zero323 — APPROVED** [review]

**Comment by zero323** [comment]
Merged to master.

**Pull request closed without merging**
