### PR TITLE
[SPARK-7920] [MLlib] Make MLlib ChiSqSelector Serializable (& Fix Related Documentation Example).

### PR DESCRIPTION
**Pull request by dusenberrymw**
The MLlib ChiSqSelector class is not serializable, and so the example in the ChiSqSelector documentation fails. Also, that example is missing the import of ChiSqSelector.

This PR makes ChiSqSelector extend Serializable in MLlib, and adds the ChiSqSelector import statement to the associated example in the documentation.

### CODE REVIEW

**Comment by mengxr** [comment]
add to whitelist

**Comment by mengxr** [comment]
LGTM. Thanks for trying the example code! This issue may only happen in the REPL. Did you try running the example  as a standalone app?

**Comment by dusenberrymw** [comment]
Interesting, yeah I had only tried it in the REPL.  Just tried running it as a standalone app (still with the added import statement, but not the ChiSqSelector fix), and it works without any issues (on a local machine with multiple threads).  I'd love to learn some more about why there is a discrepancy between these.  Do you have any thoughts on where I could start looking?  Thanks!

**Comment by jkbradley** [comment]
LGTM too.  I'll go ahead and merge this with master and branch-1.4
Thanks!

**Pull request closed without merging**
