### PR TITLE
[SPARK-31333][Followup][Doc] Link Join Hints doc in SQL perf tuning guide

### PR DESCRIPTION
**Pull request by gengliangwang**
### What changes were proposed in this pull request?

This is a follow-up of https://github.com/apache/spark/pull/28113. 
There is also a brief section about Join hints in SQL perf tuning guide: https://spark.apache.org/docs/latest/sql-performance-tuning.html . We should link the new Join hint doc in it.

### Why are the changes needed?

So that users can read more examples.

### Does this PR introduce any user-facing change?

No

### How was this patch tested?

Manually build the doc and check it:
image

### CODE REVIEW

**Comment by gengliangwang** [comment]
cc @srowen @huaxingao

**Comment by huaxingao** [comment]
LGTM. Thanks for the follow-up @gengliangwang

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master and branch-3.0.

**Comment by maropu** [comment]
late LGTM, thanks, @gengliangwang !

**Pull request closed without merging**
