### PR TITLE
[SPARK-50270][SS][PYTHON] Added custom state metrics for TransformWithStateInPandas

### PR DESCRIPTION
**Pull request by bogao007**
### What changes were proposed in this pull request?

- Added custom state metrics for TransformWithStateInPandas.
- Clean up TTL properly.

### Why are the changes needed?

Bring parity with Scala TransformWithState.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Python unit test.

### Was this patch authored or co-authored using generative AI tooling?

No

### CODE REVIEW

**Comment by bogao007** [comment]
@HeartSaVioR Could you help review this change? Thanks!

**Review by HeartSaVioR — APPROVED** [review]
+1 pending CI

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HeartSaVioR** [comment]
CI failed with only docker integration test.
https://github.com/bogao007/spark/runs/32741105303

**Comment by HeartSaVioR** [comment]
Thanks! Merging to master.

**Pull request closed without merging**
