### PR TITLE
[SPARK-26681][SQL] Support Ammonite inner-class scopes.

### PR DESCRIPTION
**Pull request by rdblue**
## What changes were proposed in this pull request?

This adds a new pattern to recognize Ammonite REPL classes and return the correct scope.

## How was this patch tested?

Manually tested with Spark in an Ammonite session.

### CODE REVIEW

**Review by srowen — APPROVED** [review]
I'm not familiar with Ammonite but, seems reasonable

**Comment by rdblue** [comment]
Thanks for reviewing, @srowen! Do you need any changes before merging this?

**Comment by srowen** [comment]
It doesn't seem to hurt anything else, and if it makes a use case work, sure seems fine as-is.

**Comment by srowen** [comment]
Merged to master

**Comment by gatorsmile** [comment]
@rdblue @srowen Which Repl do we support? Any documentation? Do we need to do it for all the REPL?

**Comment by gatorsmile** [comment]
@lihaoyi Any comment about this PR? Also cc @liancheng

**Comment by lihaoyi** [comment]
@gatorsmile I actually have no idea what this encoding thing is and how Ammonite interacts with spark. @alexarchambault do you have any idea?

**Comment by alexarchambault** [comment]
This was added in the context of [ammonite-spark](https://github.com/alexarchambault/ammonite-spark), which is a project of mine… There's some details about it in its [README](https://github.com/alexarchambault/ammonite-spark/blob/master/README.md) and the INTERNALS.md document in the ammonite-spark repo.

I guess adding a `def addOuterScopes(pf: String => AnyRef): Unit` to add one's own outer scopes at once, instead of the hard-coded `AmmoniteREPLClass` of this PR, would have worked as well, and would have been more generic and not tied to details that could change in both Ammonite or ammonite-spark.

**Comment by HyukjinKwon** [comment]
I actually was wondering why it's specific to Ammnoite. I didn't comment here because I haven't taken a close look but Zeppelin and Livy interpreters are fine without this change.

**Comment by alexarchambault** [comment]
Zeppelin, Livy, or other Scala kernels such as Toree rely on the default scala repl (that ships with the scala compiler JAR). almond relies on Ammonite, which is slicker IMO.

FYI, ammonite-spark is just bits of [almond](https://github.com/almond-sh/almond), that were moved to a separate repo. almond itself is [more popular](https://github.com/almond-sh/almond/stargazers).

**Comment by alexarchambault** [comment]
That said, I'd be ok substituting what this PR adds for an extra `def addOuterScopes(pf: String => AnyRef): Unit` methods to add one's scopes as a batch (ammonite-spark could rely on it).

**Comment by HyukjinKwon** [comment]
Thanks for explanation. How does `ammonite-spark` relate to `almond`, and Jupyter?

**Comment by HyukjinKwon** [comment]
Let's don't add a fix if this is specific to Ammonite. We could add a general fix but this one looks too specific to one of many third-party projects.

I'm trying to understand if this fix can be a general fix for other projects, or specific to only one of many projects.

Btw do you think there is a workaround for this fix within Ammonite?

**Comment by rdblue** [comment]
> Note that it works with Ammonite 1.6.0 as of now, not later versions.

@lihaoyi, did something change in Ammonite that caused this to stop working?

**Comment by alexarchambault** [comment]
@rdblue The 1.6.0 thing is just some minor binary incompatibility. (Bumping the Ammonite version in ammonite-spark should fix it.) I intend to propose a few changes in Ammonite very soon to limit these breakages.

**Comment by rdblue** [comment]
@alexarchambault, what does ammonite-spark have to do with this change? This allows Spark to find the scope for classes defined in code cells compiled by Ammonite. Did Ammonite's behavior change or not?

**Comment by alexarchambault** [comment]
@rdblue I was under the impression that this would be used mostly through ammonite-spark. But anyone that manages to get spark working through Ammonite, whatever the way, should benefit from that, yes.

**Comment by rdblue** [comment]
@alexarchambault, can you clarify what breaks with Ammonite after 1.6.0? Did something change? Your previous comment seems to imply that ammonite-spark can fix something, but I don't see how that would work.

This change should be independent of ammonite-spark: the classes created follow the conventions of Ammonite, not ammonite-spark. Right?

**Comment by liancheng** [comment]
@rdblue My major concern about this PR is that this change doesn't have any tests (and it's pretty hard to add one). Considering that this change is coupled with Spark, Scala, and Ammonite versions, it's hard to make sure we can surface possible regressions in time whenever any of these versions get updated.

I think the approach @alexarchambault brought up is better because it's REPL agnostic and it's much easier to write a test against a generic `addOuterScopes()` method.

**Comment by gatorsmile** [comment]
@srowen What is our policy for supporting third-party library? The community has many third-party library. Did we merge anything before?

Merging this PR sounds an exception to me. No test coverage and no documentation about the support. I would ping more people before merging such a PR, if we are not confident about the PR. Although ammonite is developed by our teammate Haoyi, I still prefer to having a broader discussion first. Supporting ammonite sounds not trivial. I do not expect we will maintain the support, especially when ammonite-spark has a walkaround. Also, ammonite-spark sounds has a limitation for supporting ammonite.

**Comment by rdblue** [comment]
> Considering that this change is coupled with Spark, Scala, and Ammonite versions, it's hard to make sure we can surface possible regressions in time whenever any of these versions get updated.

If that is true, I agree. My rationale was that Ammonite doesn't often change how it creates classes from blocks of code from the REPL. The version for the basic Scala REPL hasn't changed in 3 years. If Ammonite is similar then I think it is reasonable to go ahead with this tiny bit of code.

If this does actually break after version 1.6.0, as alleged by @alexarchambault, then we should remove it. But it isn't clear what his statements meant. If bumping the version in ammonite-spark fixes the problem, then it sounds like the problem is ammonite-spark, not this patch.

**Comment by srowen** [comment]
Sure, I mean, YARN, ORC, ganglia, tachyon in the past? etc, etc. Spark has a lot of code to support third-party things as you know. I know your point is that we don't want to add a bunch of exceptions and workarounds to complicate Spark just to accommodate every third-party library out there, and I agree.

I don't think we have a formal policy. It's up to our judgment. There is no slippery-slope here.

The logic here is simply that it doesn't impact Spark otherwise, and is a few lines of code, and does help a small class of Spark users. I think the judgment to merge this is fine; I was confident about it.

Tests are good but how would you test it, and what would you document?

We can revert or modify it if others feel strongly, but, now that you've reviewed it, what is your concern? just that it needs some docs?

I'd like to get you and other committers in front of more changes for review before they're merged rather than after the fact, but, I know everyone's busy and sometimes we pay attention to these things only when they arrive downstream in an integration branch.

**Comment by gatorsmile** [comment]
In Spark SQL, we rejected all the similar PRs in the past and I do not remember we made any exception in the past. We normally suggest users to do it in their forks, instead of merging/maintaining them in the upstream. We are very conservative in the code merging, especially when we are not familiar with the changes. For example, the other contributors try it, realize that it does not work well and submit more PRs. We even do not know who can review the changes.    

For this specific PR, actually, @zsxwing @lihaoyi @liancheng had an internal Hackathon project for supporting Ammonite, which is much better than Scala Repl TBH. However, based on my understanding, the sizing is not small if we want to make an official support of Ammonite in Apache Spark. If we want to officially support it, we might need a SPIP with a clear design doc. So far, I think very few people can actually lead this effort to finish, review and maintain it. Thus, I do not think we should simply merge this PR and maintain it without knowing the context, the scope and the motivation. WDYT? @srowen

**Comment by srowen** [comment]
I agree with all that, but I don't think this constitutes official support, nor do I see a case for formally supporting or integrating it. This just lets it work at all, it seems. I think that's the whole of the context here, and indeed not a much bigger change.

**Comment by HyukjinKwon** [comment]
@rdblue and @srowen, I admit I haven't taken a close look so I have no opinions about its details. Maybe I can put more inputs later after reviewing this closely. I have no issue for the fact it was merged - I feel in the same way on your point about review, Sean. We can discuss later if someone raises an issue imho.

My only issue is that I think usually we take an approach for a general fix rather than for one (arguably less-known) third-party project, otherwise I have left -0 or -1 so far. How many projects do need similar changes (to see if we need a general fix) and how many users do get affected (to see if it's worth getting in alone)? Looks this point wasn't made here.

Being non-invasive is good to judge when to merge a PR but we should see if that's worth as well.

**Comment by HyukjinKwon** [comment]
Also, @zsxwing @lihaoyi @liancheng, out of curiosity, is it possible to open the internal Hackathon project for supporting Ammonite as a thrid-party? I think we shouldn't argue here with closed sources since no one can put some inputs about its details than the authors.

**Comment by lihaoyi** [comment]
@gatorsmile our hackathon project was mostly integration with the
company-specific code. @alexarchambault is probabpy the expert on what is
necessary on the OSS side of the ammonite+spark integration.

I don’t mind merging this PR in principle. The maintenance overhead seems
negligible, and if it helps some people start using ammonite+spark more
then great. If it breaks in future versions of either then whoever cares
can fix it, but having something work even without unofficial support is a
good way to get people interested enough to develop official support in
future.

-Haoyi

**Comment by HyukjinKwon** [comment]
I don't feel strongly that we should revert but I also don't know if this fix is worth enough. WDYT, @srowen? I think it's also a good option to take one step back and see if it's worth from scratch.

**Comment by srowen** [comment]
I also can't feel strongly either way. If the issue is simply, "what if 10 more projects want something like this" or "what if this turns into 1000 lines of code" then, it won't. What's the alternative in the near-term, a small SPI to implement some interface? yeah that could be OK too. If the worry is complexity, that's more complex. It's more flexible to support N more such callers, but are there any?

**Comment by HyukjinKwon** [comment]
I wasn't trying to say a specific number as a hard limit .. but .. like .. for instance, it wouldn't make sense, say, I make my repo and make a fix accordingly within Apache Spark.

I am okay as is for now since it doesn't harm anyway. I think we should be sure on that in case such fixes come in the future.

**Comment by gatorsmile** [comment]
I am fine to keep this here, since this has been merged. However, to be clear, the support could be dropped/broken anytime when we change/refactor the code. We do not guarantee the support will be kept in this release or the future releases.

**Comment by rdblue** [comment]
@gatorsmile, I think that's a good pragmatic approach. If it looks like this is going to be a problem or set a bad precedent, I fully support removing it. But if it's a few lines of code that require not maintenance and are useful to some people, then it makes sense to have it.

**Comment by HyukjinKwon** [comment]
Yup, I am okay by this take.

**Pull request closed without merging**
