### PR TITLE
[SPARK-25313][SQL][FOLLOW-UP][BACKPORT-2.3] Fix InsertIntoHiveDirCommand output schema in Parquet issue

### PR DESCRIPTION
**Pull request by wangyum**
## What changes were proposed in this pull request?

Backport https://github.com/apache/spark/pull/22359 to branch-2.3.

## How was this patch tested?

unit tests

### CODE REVIEW

**Comment by cloud-fan** [comment]
LGTM

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by wangyum** [comment]
retest this please

**Review by gengliangwang — APPROVED** [review]
LGTM

**Comment by wangyum** [comment]
retest this please

**Comment by dongjoon-hyun** [comment]
Merged to branch-2.3.

**Pull request closed without merging**
