### PR TITLE
[SPARK-18300][SQL] Fix scala 2.10 build for FoldablePropagation

### PR DESCRIPTION
**Pull request by hvanhovell**
## What changes were proposed in this pull request?
Commit https://github.com/apache/spark/commit/f14ae4900ad0ed66ba36108b7792d56cd6767a69 broke the scala 2.10 build. This PR fixes this by simplifying the used pattern match.

## How was this patch tested?
Tested building manually. Ran `build/sbt -Dscala-2.10 -Pscala-2.10 package`.

### CODE REVIEW

**Comment by hvanhovell** [comment]
cc @gatorsmile @zsxwing

**Comment by zsxwing** [comment]
LGTM

**Comment by gatorsmile** [comment]
LGTM

**Comment by zsxwing** [comment]
Thanks! Merging to master and 2.1.

**Comment by dongjoon-hyun** [comment]
Maybe, could you close this? @hvanhovell  ;)

**Pull request closed without merging**
