### PR TITLE
[SPARK-13903][SQL] Modify output nullability with constraints for Join and Filter operators

### PR DESCRIPTION
**Pull request by viirya**
## What changes were proposed in this pull request?

JIRA: https://issues.apache.org/jira/browse/SPARK-13903

With constraints and optimization, we can make sure some outputs of a Join (or Filter) operator are not nulls. In other words, we actually change output nullability for these operators. But we don't modify their output attribute accordingly. We should modify output nullability to keep correct schema because we will use the output to determine schema . Besides, we can also use this information in later execution to avoid null checking.
## How was this patch tested?

Modified `InferFiltersFromConstraintsSuite`.

### CODE REVIEW

**Comment by viirya** [comment]
retest this please.

**Comment by viirya** [comment]
Investigating why the test will fail...

**Comment by viirya** [comment]
cc @marmbrus @cloud-fan @rxin

**Comment by marmbrus** [comment]
We've talked about doing this, but I'd prefer to come up with a solution that just works everywhere.  Rather than needing to reason about this in both operators and multiple rules.

**Comment by viirya** [comment]
For Join operator, it is indeed complicated as you see. Due to different join type, the output nullability is inferred in different way. However, the output of Join operator is also inferred according to its join type.

Btw, I think only Filter and Join will change output nullability with their condition. Any other operator do that?

**Comment by viirya** [comment]
I come up another approach for this problem. Close this now.

**Pull request closed without merging**
