### PR TITLE
[SPARK-6286][minor] Handle missing Mesos case TASK_ERROR.

### PR DESCRIPTION
**Pull request by dragos**

### CODE REVIEW

**Comment by srowen** [comment]
ok to test

**Comment by srowen** [comment]
Add to whitelist

**Comment by srowen** [comment]
LGTM given the JIRA discussion and approval from @jongyoul

**Comment by jongyoul** [comment]
@dragos You will find more codes which you could fix in *SchedulerBackend which handles MesosTaskState directly.

**Comment by srowen** [comment]
Agree, I think `TASK_ERROR` could also be considered a 'finished' state in `MesosSchedulerBackend` and `CoarseMesosSchedulerBackend`

**Comment by dragos** [comment]
Thanks for the pointer, I'll have a look in Mesos scheduler backends.

**Comment by srowen** [comment]
@dragos are you able to make the other changes here? looks like a simple additional change we could get in.

**Comment by dragos** [comment]
Yes, but I'm not sure I can do it before Scala Days is over. Feel free to close this and I'll reopen if you will. 

BTW, I have a couple other pull requests that are a bit less trivial and didn't get any attention: #4990 and #4984

**Comment by dragos** [comment]
Ok, it was faster than I thought. Please have a look at the last commit.

**Comment by srowen** [comment]
LGTM. That's a nice refactoring too to remove the 3x duplication of the 'finished' logic.

**Comment by jongyoul** [comment]
@srowen Two missing points remains. We should handle `MesosTaskState.TASK_LOST` in `MesosSchedulerBackend` and `CoarseMesosSchedulerBackend`. I will follow up this with another PR.

**Comment by srowen** [comment]
OK sounds good, let me know if there are other instances of this.

**Comment by dragos** [comment]
@jongyoul thanks for pointing out. `TASK_LOST` is already handled [here](https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/scheduler/cluster/mesos/CoarseMesosSchedulerBackend.scala#L280) and [here](https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/scheduler/cluster/mesos/MesosSchedulerBackend.scala#L321). I think what you really mean is to handle `TASK_ERROR` the same way as `TASK_LOST`, right?

Currently the two backends don't behave the same way (`CoarseGrained` considers both `TASK_FAILED` and `TAKS_LOST`, while the other one handles only `TASK_LOST`). Maybe it makes sense to unify this too, maybe in a `TaskState.isFailed` method.

**Comment by jongyoul** [comment]
@dragos Yes, right. I'll make `TaskState.isFailed` method.

**Pull request closed without merging**
