### PR TITLE
[SPARK-22327][SPARKR][TEST][BACKPORT-2.0] check for version warning

### PR DESCRIPTION
**Pull request by felixcheung**
## What changes were proposed in this pull request?

backporting to 2.0 (since it's the first branch "older than" 2.1.2)

## How was this patch tested?

manually
Jenkins, AppVeyor

### CODE REVIEW

**Comment by felixcheung** [comment]
this was the last build https://amplab.cs.berkeley.edu/jenkins/view/Spark%20QA%20Test/job/spark-branch-2.0-test-sbt-hadoop-2.7/977/console

**Review by HyukjinKwon — APPROVED** [review]

**Comment by shivaram** [comment]
LGTM. Thanks @felixcheung

**Comment by felixcheung** [comment]
Jenkins, retest this please

**Comment by HyukjinKwon** [comment]
@felixcheung, are we okay to merge this alone in branch-2.0?

**Pull request closed without merging**
