### PR TITLE
[SPARK-29307][BUILD][TESTS] Remove scalatest deprecation warnings

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to remove `scalatest` deprecation warnings with the following changes.
- `org.scalatest.mockito.MockitoSugar` -> `org.scalatestplus.mockito.MockitoSugar`
- `org.scalatest.selenium.WebBrowser` -> `org.scalatestplus.selenium.WebBrowser`
- `org.scalatest.prop.Checkers` -> `org.scalatestplus.scalacheck.Checkers`
- `org.scalatest.prop.GeneratorDrivenPropertyChecks` -> `org.scalatestplus.scalacheck.ScalaCheckDrivenPropertyChecks`

### Why are the changes needed?

According to the Jenkins logs, there are 118 warnings about this.
```
 grep "is deprecated" ~/consoleText | grep scalatest | wc -l
     118
```

### Does this PR introduce any user-facing change?

No.

### How was this patch tested?

After Jenkins passes, we need to check the Jenkins log.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Review by maropu — APPROVED** [review]
I checked there is no deprecated entry for scalatest in the console result.

**Comment by dongjoon-hyun** [comment]
Merged to master. Thank you, @maropu !

**Comment by srowen** [comment]
Oh thank you, I was just going to try to fix that up. I think the 3.0.5->3.0.8 change introduced that? which kind of surprises me.

**Comment by dongjoon-hyun** [comment]
Yes. I just noticed that warnings yesterday and it happens at `3.0.8`.

**Pull request closed without merging**
