### PR TITLE
SPARK-44058: Removed createPartition deprecated method for HiveShim.scala

### PR DESCRIPTION
**Pull request by amanraj2520**
JIRA link : [SPARK-44058](https://issues.apache.org/jira/browse/SPARK-44058)

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Thank you for making a PR, @amanraj2520 . However, there is no more Apache Hive release, isn't it? Do we need to change this?

**Comment by amanraj2520** [comment]
Hi @dongjoon-hyun There is going to be Hive 3.2.0 release which I am coordinating as well as Hive 4.x release after sometime. But as such this PR is not required. We can close this.

**Comment by dongjoon-hyun** [comment]
Ya, I saw the plan in dev@hive mailing list. Let's keep this PR open for now.
```
4.0.0 Stamatis Zampetakis
4.1.0 Denys Kuzmenko
4.2.0 Sai Hemanth Gantasala
```

Apache Spark also an Apache Spark 4.0.0 plan for next year.

- https://lists.apache.org/thread/5vfof0nm82gt5b2k2o0ws944hofz232g
```
Release Plan for Apache Spark 4.0.0 (June 2024)
```

**Comment by amanraj2520** [comment]
@dongjoon-hyun Also do you think we should migrate spark from 2.3.9 Hive to 3.x?

**Comment by dongjoon-hyun** [comment]
That is an independent topic and we can discuss in Apache Spark 4.0 scope too, @amanraj2520 .
> Also do you think we should migrate spark from 2.3.9 Hive to 3.x?

**Comment by amanraj2520** [comment]
> That is an independent topic and we can discuss in Apache Spark 4.0 scope too, @amanraj2520 .
> 
> > Also do you think we should migrate spark from 2.3.9 Hive to 3.x?

Sure I can start working on the same. Please let me know if we decide on this.

**Pull request closed without merging**
