### PR TITLE
[DO-NOT-MERGE] Test Python 3.12 build

### PR DESCRIPTION
**Pull request by HyukjinKwon**
### What changes were proposed in this pull request?

TBD

### Why are the changes needed?

TBD

### Does this PR introduce _any_ user-facing change?

TBD

### How was this patch tested?

TBD

### Was this patch authored or co-authored using generative AI tooling?

TBD

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
https://github.com/HyukjinKwon/spark/actions/runs/10785604125/job/29911090275

**Comment by dongjoon-hyun** [comment]
According to the log, `test_connect_session` seems to be hung, doesn't it?
```
========================================================================
Running PySpark tests
========================================================================
Running PySpark tests. Output is in /__w/spark/spark/python/unit-tests.log
Will test against the following Python executables: ['python3.12']
Will test the following Python modules: ['pyspark-connect']
python3.12 python_implementation is CPython
python3.12 version is: Python 3.12.5
Starting test(python3.12): pyspark.sql.tests.connect.client.test_artifact (temp output: /__w/spark/spark/python/target/a755809a-48c2-4517-b522-3b9f70efde21/python3.12__pyspark.sql.tests.connect.client.test_artifact__hx_vl9d9.log)
Finished test(python3.12): pyspark.sql.tests.connect.client.test_artifact (1s)
Starting test(python3.12): pyspark.sql.tests.connect.client.test_artifact_localcluster (temp output: /__w/spark/spark/python/target/824f6248-e576-446d-8f9d-0f1f207e6f38/python3.12__pyspark.sql.tests.connect.client.test_artifact_localcluster__mic1k7vz.log)
Finished test(python3.12): pyspark.sql.tests.connect.client.test_artifact_localcluster (24s)
Starting test(python3.12): pyspark.sql.tests.connect.client.test_client (temp output: /__w/spark/spark/python/target/d5b4f0ea-5ebe-4881-89b6-9943695947df/python3.12__pyspark.sql.tests.connect.client.test_client__l_0uy7og.log)
Finished test(python3.12): pyspark.sql.tests.connect.client.test_client (0s)
Starting test(python3.12): pyspark.sql.tests.connect.client.test_reattach (temp output: /__w/spark/spark/python/target/930e8f12-b97a-4e54-b6b2-ff3838ad4fae/python3.12__pyspark.sql.tests.connect.client.test_reattach__q84e9hac.log)
Finished test(python3.12): pyspark.sql.tests.connect.client.test_reattach (10s)
Starting test(python3.12): pyspark.sql.tests.connect.shell.test_progress (temp output: /__w/spark/spark/python/target/be28e332-3ff4-47d7-ac38-a417fc15aee0/python3.12__pyspark.sql.tests.connect.shell.test_progress__s1gy3a5s.log)
Finished test(python3.12): pyspark.sql.tests.connect.shell.test_progress (19s)
Starting test(python3.12): pyspark.sql.tests.connect.streaming.test_parity_foreach (temp output: /__w/spark/spark/python/target/4563155c-a544-4679-aefa-37bd3a12dac0/python3.12__pyspark.sql.tests.connect.streaming.test_parity_foreach__8k5ospka.log)
Finished test(python3.12): pyspark.sql.tests.connect.streaming.test_parity_foreach (19s)
Starting test(python3.12): pyspark.sql.tests.connect.streaming.test_parity_foreach_batch (temp output: /__w/spark/spark/python/target/8173dba8-dbfc-426f-973f-8646f4a2d8d0/python3.12__pyspark.sql.tests.connect.streaming.test_parity_foreach_batch__lvp720ko.log)
Finished test(python3.12): pyspark.sql.tests.connect.streaming.test_parity_foreach_batch (32s) ... 1 tests were skipped
Starting test(python3.12): pyspark.sql.tests.connect.streaming.test_parity_listener (temp output: /__w/spark/spark/python/target/58dc5992-7dce-4db3-abd3-3c3fd3749333/python3.12__pyspark.sql.tests.connect.streaming.test_parity_listener__pfngk1c7.log)
Finished test(python3.12): pyspark.sql.tests.connect.streaming.test_parity_listener (142s)
Starting test(python3.12): pyspark.sql.tests.connect.streaming.test_parity_streaming (temp output: /__w/spark/spark/python/target/adbc231b-7b2f-4db1-9785-d95aea1099f3/python3.12__pyspark.sql.tests.connect.streaming.test_parity_streaming__w8r06qvr.log)
Finished test(python3.12): pyspark.sql.tests.connect.streaming.test_parity_streaming (56s)
Starting test(python3.12): pyspark.sql.tests.connect.test_connect_basic (temp output: /__w/spark/spark/python/target/105ce3ea-07fb-4092-8f29-0634803b7dc7/python3.12__pyspark.sql.tests.connect.test_connect_basic__kyarm65q.log)
Finished test(python3.12): pyspark.sql.tests.connect.test_connect_basic (49s)
Starting test(python3.12): pyspark.sql.tests.connect.test_connect_collection (temp output: /__w/spark/spark/python/target/ebea3579-3940-42d3-a5d5-e199a9dc3e4d/python3.12__pyspark.sql.tests.connect.test_connect_collection__wy48np5l.log)
Finished test(python3.12): pyspark.sql.tests.connect.test_connect_collection (21s)
Starting test(python3.12): pyspark.sql.tests.connect.test_connect_column (temp output: /__w/spark/spark/python/target/a18630ed-9ece-4029-860e-bc64892735a9/python3.12__pyspark.sql.tests.connect.test_connect_column__93nrk0bo.log)
Finished test(python3.12): pyspark.sql.tests.connect.test_connect_column (33s)
Starting test(python3.12): pyspark.sql.tests.connect.test_connect_creation (temp output: /__w/spark/spark/python/target/497236bf-7881-49d9-9317-d846bf57a8d8/python3.12__pyspark.sql.tests.connect.test_connect_creation___s0yuj1k.log)
Finished test(python3.12): pyspark.sql.tests.connect.test_connect_creation (43s)
Starting test(python3.12): pyspark.sql.tests.connect.test_connect_dataframe_property (temp output: /__w/spark/spark/python/target/6fd372bf-7e87-486f-ad7a-f899537cf84d/python3.12__pyspark.sql.tests.connect.test_connect_dataframe_property__gg_uxhqj.log)
Finished test(python3.12): pyspark.sql.tests.connect.test_connect_dataframe_property (25s)
Starting test(python3.12): pyspark.sql.tests.connect.test_connect_error (temp output: /__w/spark/spark/python/target/4c183b83-6501-4b3f-8471-72bbc1c27cff/python3.12__pyspark.sql.tests.connect.test_connect_error__ovoactdw.log)
Finished test(python3.12): pyspark.sql.tests.connect.test_connect_error (45s)
Starting test(python3.12): pyspark.sql.tests.connect.test_connect_function (temp output: /__w/spark/spark/python/target/c123d425-376f-44ce-b611-72441eaa0c21/python3.12__pyspark.sql.tests.connect.test_connect_function__oqs6re9_.log)
Finished test(python3.12): pyspark.sql.tests.connect.test_connect_function (92s)
Starting test(python3.12): pyspark.sql.tests.connect.test_connect_plan (temp output: /__w/spark/spark/python/target/3e856192-1e82-4f1e-9a99-531fce6adcbd/python3.12__pyspark.sql.tests.connect.test_connect_plan__erpavvzk.log)
Finished test(python3.12): pyspark.sql.tests.connect.test_connect_plan (0s)
Starting test(python3.12): pyspark.sql.tests.connect.test_connect_readwriter (temp output: /__w/spark/spark/python/target/34e98118-12fb-4360-b6a6-3319757df670/python3.12__pyspark.sql.tests.connect.test_connect_readwriter__8vauiije.log)
Finished test(python3.12): pyspark.sql.tests.connect.test_connect_readwriter (31s)
Starting test(python3.12): pyspark.sql.tests.connect.test_connect_session (temp output: /__w/spark/spark/python/target/903d2cd4-2d3d-4066-8eb0-a32765c544bd/python3.12__pyspark.sql.tests.connect.test_connect_session__b_4hk53y.log)
Error: The operation was canceled.
```

**Comment by dongjoon-hyun** [comment]
It seems that `Python 3.12 - pyspark-connect` passed in 58 mins today.
- https://github.com/apache/spark/actions/runs/10779540436/job/29948161788

**Comment by HyukjinKwon** [comment]
thanks!!! closing!!!!!

**Pull request closed without merging**
