### PR TITLE
[SPARK-36853][BUILD] Code failing on checkstyle

### PR DESCRIPTION
**Pull request by Shockang**
### What changes were proposed in this pull request?
Fixed the checkstyle error thrown in windows in maven installing phase.

### Why are the changes needed?
Due to some problems in CI system, these obvious errors have not been detected. I think these checkstyle errors should be solved.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
No, there is no need to provide test cases.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
> No, there is no need to provide test cases.

We should describe how you identified these instances, and how you verify it. I guess you faced those errors on Window, right? It should be best to describe what command you ran in which OS so other people can reproduce this.

**Comment by Shockang** [comment]
> > No, there is no need to provide test cases.
> 
> We should describe how you identified these instances, and how you verify it. I guess you faced those errors on Window, right? It should be best to describe what command you ran in which OS so other people can reproduce this.

I can't agree more.

**Comment by srowen** [comment]
Ping @Shockang

**Comment by Shockang** [comment]
> Ping @Shockang

OK, I'll deal with this problem as soon as possible. I've been busy recently  :)

**Comment by Shockang** [comment]
The submitted code is transferred to this PR: https://github.com/apache/spark/pull/35017

**Pull request closed without merging**
