### PR TITLE
[SPARK-26169] Create DataFrameSetOperationsSuite

### PR DESCRIPTION
**Pull request by gatorsmile**
## What changes were proposed in this pull request?

Create a new suite DataFrameSetOperationsSuite for the test cases of DataFrame/Dataset's set operations.

Also, add test cases of NULL handling for Array Except and Array Intersect. 

## How was this patch tested?
N/A

### CODE REVIEW

**Comment by gatorsmile** [comment]
CC @cloud-fan

**Comment by cloud-fan** [comment]
LGTM, waiting for resolving the conflicts.

**Comment by kiszk** [comment]
LGTM, pending Jenkins

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Pull request closed without merging**
