### PR TITLE
[SPARK-11677][SQL] ORC filter tests all pass if filters are actually not pushed down.

### PR DESCRIPTION
**Pull request by HyukjinKwon**
Currently ORC filters are not tested properly. All the tests pass even if the filters are not pushed down or disabled. In this PR, I add some logics for this. 
Since ORC does not filter record by record fully, this checks the count of the result and if it contains the expected values.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Several things to mention.

Firstly, I wonder if it is okay to put `extractSourceRDDToDataFrame` at `QueryTest`. I did not put but I think the `extractSourceRDDToDataFrame` can be shared with `ParquetFilterSuite`. 

Secondly, I originally wanted to add `OrcFilterSuite` separately in order to test actual filter evaluation (using the enums in `ExpressionTree.Operator` and `PredicateLeaf.Operator` at hive); however, I decided not to do it here (I will do in a separate issue or followup PR) and just let the original test way work properly first.

**Comment by HyukjinKwon** [comment]
cc @liancheng

**Comment by HyukjinKwon** [comment]
I will add that function to `SharedSQLContext` if it is okay.

**Comment by HyukjinKwon** [comment]
In this commit, I renamed the function extractSourceRDDToDataFrame to stripSparkFilter.

**Comment by HyukjinKwon** [comment]
Can I add the function `stripSparkFilter` to `SQLTestUtils` for `ParquetFilterSuite` and `OrcQuerySuite` (and possibly `OrcFilterSuite` I will make)?

**Comment by HyukjinKwon** [comment]
The function I mentioned is moved to `SQLTestUtils` in another PR. So I will add a commit for this soon.

**Comment by HyukjinKwon** [comment]
In the commits above, I removed the `stripSparkFilter` function to share this.

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
cc @marmbrus

**Comment by marmbrus** [comment]
Thanks, merging to master.

**Pull request closed without merging**
