### PR TITLE
[SPARK-40843][CORE][TESTS] Clean up deprecated api usage in SparkThrowableSuite

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
A trivial change, this pr fix  deprecated api usage in `SparkThrowableSuite` as follows:

```
[WARNING] /spark-source/core/src/test/scala/org/apache/spark/SparkThrowableSuite.scala:77: [deprecation @ org.apache.spark.SparkThrowableSuite.<local SparkThrowableSuite>.errorClassFileContents | origin=org.apache.commons.io.IOUtils.toString | version=] method toString in class IOUtils is deprecated
[WARNING] /spark-source/core/src/test/scala/org/apache/spark/SparkThrowableSuite.scala:104: [deprecation @ org.apache.spark.SparkThrowableSuite.<local SparkThrowableSuite>.errorClassReadMeContents | origin=org.apache.commons.io.IOUtils.toString | version=] method toString in class IOUtils is deprecated
[WARNING] /spark-source/core/src/test/scala/org/apache/spark/SparkThrowableSuite.scala:325: [deprecation @ org.apache.spark.SparkThrowableSuite.<local SparkThrowableSuite>.$anonfun | origin=org.apache.commons.io.FileUtils.writeStringToFile | version=] method writeStringToFile in class FileUtils is deprecated
[WARNING] /spark-source/core/src/test/scala/org/apache/spark/SparkThrowableSuite.scala:335: [deprecation @ org.apache.spark.SparkThrowableSuite.<local SparkThrowableSuite>.$anonfun.reader | origin=java.io.File.toURL | version=] method toURL in class File is deprecated
[WARNING] /spark-source/core/src/test/scala/org/apache/spark/SparkThrowableSuite.scala:343: [deprecation @ org.apache.spark.SparkThrowableSuite.<local SparkThrowableSuite>.$anonfun | origin=org.apache.commons.io.FileUtils.writeStringToFile | version=] method writeStringToFile in class FileUtils is deprecated
[WARNING] /spark-source/core/src/test/scala/org/apache/spark/SparkThrowableSuite.scala:354: [deprecation @ org.apache.spark.SparkThrowableSuite.<local SparkThrowableSuite>.$anonfun.e | origin=java.io.File.toURL | version=] method toURL in class File is deprecated
[WARNING] /spark-source/core/src/test/scala/org/apache/spark/SparkThrowableSuite.scala:362: [deprecation @ org.apache.spark.SparkThrowableSuite.<local SparkThrowableSuite>.$anonfun | origin=org.apache.commons.io.FileUtils.writeStringToFile | version=] method writeStringToFile in class FileUtils is deprecated
[WARNING] /spark-source/core/src/test/scala/org/apache/spark/SparkThrowableSuite.scala:380: [deprecation @ org.apache.spark.SparkThrowableSuite.<local SparkThrowableSuite>.$anonfun.e | origin=java.io.File.toURL | version=] method toURL in class File is deprecated
```

### Why are the changes needed?
Clean up deprecated api usage in `SparkThrowableSuite`.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GitHub Actions.

### CODE REVIEW

**Review by MaxGekk — APPROVED** [review]

**Comment by MaxGekk** [comment]
Waiting for CI.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by LuciferYang** [comment]
```
[info] *** 12 TESTS FAILED ***
[error] Failed: Total 6746, Failed 12, Errors 0, Passed 6734, Ignored 5
[error] Failed tests:
[error] 	org.apache.spark.sql.catalyst.expressions.CastWithAnsiOffSuite
[error] 	org.apache.spark.sql.catalyst.util.TimestampFormatterSuite
[error] 	org.apache.spark.sql.catalyst.expressions.CastWithAnsiOnSuite
[error] 	org.apache.spark.sql.catalyst.util.RebaseDateTimeSuite
[error] 	org.apache.spark.sql.catalyst.expressions.TryCastSuite
```
The failure is strange

**Comment by LuciferYang** [comment]
I can reproduce the failed with Java 8u352:

```
[info] - SPARK-31557: rebasing in legacy formatters/parsers *** FAILED *** (21 milliseconds)
[info]   zoneId = Antarctica/Vostok 1000-01-01T06:52:23 did not equal 1000-01-01T01:02:03 (TimestampFormatterSuite.scala:281)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.Assertions.newAssertionFailedException(Assertions.scala:472)
[info]   at org.scalatest.Assertions.newAssertionFailedException$(Assertions.scala:471)
[info]   at org.scalatest.Assertions$.newAssertionFailedException(Assertions.scala:1231)
[info]   at org.scalatest.Assertions$AssertionsHelper.macroAssert(Assertions.scala:1295)
[info]   at org.apache.spark.sql.catalyst.util.TimestampFormatterSuite.$anonfun$new$33(TimestampFormatterSuite.scala:281)
[info]   at scala.collection.Iterator.foreach(Iterator.scala:943)
[info]   at scala.collection.Iterator.foreach$(Iterator.scala:943)
[info]   at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[info]   at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[info]   at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[info]   at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[info]   at org.apache.spark.sql.catalyst.util.TimestampFormatterSuite.$anonfun$new$31(TimestampFormatterSuite.scala:280)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[info]   at org.scalatest.Assertions.withClue(Assertions.scala:1065)
[info]   at org.scalatest.Assertions.withClue$(Assertions.scala:1052)
[info]   at org.scalatest.funsuite.AnyFunSuite.withClue(AnyFunSuite.scala:1564)
[info]   at org.apache.spark.sql.catalyst.util.TimestampFormatterSuite.$anonfun$new$30(TimestampFormatterSuite.scala:271)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[info]   at org.apache.spark.sql.catalyst.util.DateTimeTestUtils$.withDefaultTimeZone(DateTimeTestUtils.scala:61)
[info]   at org.apache.spark.sql.catalyst.util.TimestampFormatterSuite.$anonfun$new$29(TimestampFormatterSuite.scala:271)
[info]   at org.apache.spark.sql.catalyst.plans.SQLHelper.withSQLConf(SQLHelper.scala:54)
[info]   at org.apache.spark.sql.catalyst.plans.SQLHelper.withSQLConf$(SQLHelper.scala:38)
[info]   at org.apache.spark.sql.catalyst.util.TimestampFormatterSuite.withSQLConf(TimestampFormatterSuite.scala:31)
[info]   at org.apache.spark.sql.catalyst.util.TimestampFormatterSuite.$anonfun$new$28(TimestampFormatterSuite.scala:270)
[info]   at org.apache.spark.sql.catalyst.util.TimestampFormatterSuite.$anonfun$new$28$adapted(TimestampFormatterSuite.scala:268)
[info]   at scala.collection.immutable.List.foreach(List.scala:431)
[info]   at org.apache.spark.sql.catalyst.util.TimestampFormatterSuite.$anonfun$new$27(TimestampFormatterSuite.scala:268)
[info]   at org.apache.spark.sql.catalyst.plans.SQLHelper.withSQLConf(SQLHelper.scala:54)
[info]   at org.apache.spark.sql.catalyst.plans.SQLHelper.withSQLConf$(SQLHelper.scala:38)
[info]   at org.apache.spark.sql.catalyst.util.TimestampFormatterSuite.withSQLConf(TimestampFormatterSuite.scala:31)
[info]   at org.apache.spark.sql.catalyst.util.TimestampFormatterSuite.$anonfun$new$26(TimestampFormatterSuite.scala:268)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.funsuite.AnyFunSuiteLike$$anon$1.apply(AnyFunSuiteLike.scala:226)
[info]   at org.apache.spark.SparkFunSuite.withFixture(SparkFunSuite.scala:207)
[info]   at org.scalatest.funsuite.AnyFunSuiteLike.invokeWithFixture$1(AnyFunSuiteLike.scala:224)
[info]   at org.scalatest.funsuite.AnyFunSuiteLike.$anonfun$runTest$1(AnyFunSuiteLike.scala:236)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[info]   at org.scalatest.funsuite.AnyFunSuiteLike.runTest(AnyFunSuiteLike.scala:236)
[info]   at org.scalatest.funsuite.AnyFunSuiteLike.runTest$(AnyFunSuiteLike.scala:218)
[info]   at org.apache.spark.SparkFunSuite.org$scalatest$BeforeAndAfterEach$$super$runTest(SparkFunSuite.scala:66)
[info]   at org.scalatest.BeforeAndAfterEach.runTest(BeforeAndAfterEach.scala:234)
[info]   at org.scalatest.BeforeAndAfterEach.runTest$(BeforeAndAfterEach.scala:227)
[info]   at org.apache.spark.SparkFunSuite.runTest(SparkFunSuite.scala:66)
[info]   at org.scalatest.funsuite.AnyFunSuiteLike.$anonfun$runTests$1(AnyFunSuiteLike.scala:269)
[info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
[info]   at scala.collection.immutable.List.foreach(List.scala:431)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
[info]   at org.scalatest.funsuite.AnyFunSuiteLike.runTests(AnyFunSuiteLike.scala:269)
[info]   at org.scalatest.funsuite.AnyFunSuiteLike.runTests$(AnyFunSuiteLike.scala:268)
[info]   at org.scalatest.funsuite.AnyFunSuite.runTests(AnyFunSuite.scala:1564)
[info]   at org.scalatest.Suite.run(Suite.scala:1114)
[info]   at org.scalatest.Suite.run$(Suite.scala:1096)
[info]   at org.scalatest.funsuite.AnyFunSuite.org$scalatest$funsuite$AnyFunSuiteLike$$super$run(AnyFunSuite.scala:1564)
[info]   at org.scalatest.funsuite.AnyFunSuiteLike.$anonfun$run$1(AnyFunSuiteLike.scala:273)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
[info]   at org.scalatest.funsuite.AnyFunSuiteLike.run(AnyFunSuiteLike.scala:273)
[info]   at org.scalatest.funsuite.AnyFunSuiteLike.run$(AnyFunSuiteLike.scala:272)
[info]   at org.apache.spark.SparkFunSuite.org$scalatest$BeforeAndAfterAll$$super$run(SparkFunSuite.scala:66)
[info]   at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)
[info]   at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
[info]   at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
[info]   at org.apache.spark.SparkFunSuite.run(SparkFunSuite.scala:66)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:321)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:517)
[info]   at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:413)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info]   at java.lang.Thread.run(Thread.java:750)
```

**Comment by LuciferYang** [comment]
> I can reproduce the failed with Java 8u352:
> 
> ```
> [info] - SPARK-31557: rebasing in legacy formatters/parsers *** FAILED *** (21 milliseconds)
> [info]   zoneId = Antarctica/Vostok 1000-01-01T06:52:23 did not equal 1000-01-01T01:02:03 (TimestampFormatterSuite.scala:281)
> [info]   org.scalatest.exceptions.TestFailedException:
> [info]   at org.scalatest.Assertions.newAssertionFailedException(Assertions.scala:472)
> [info]   at org.scalatest.Assertions.newAssertionFailedException$(Assertions.scala:471)
> [info]   at org.scalatest.Assertions$.newAssertionFailedException(Assertions.scala:1231)
> [info]   at org.scalatest.Assertions$AssertionsHelper.macroAssert(Assertions.scala:1295)
> [info]   at org.apache.spark.sql.catalyst.util.TimestampFormatterSuite.$anonfun$new$33(TimestampFormatterSuite.scala:281)
> [info]   at scala.collection.Iterator.foreach(Iterator.scala:943)
> [info]   at scala.collection.Iterator.foreach$(Iterator.scala:943)
> [info]   at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
> [info]   at scala.collection.IterableLike.foreach(IterableLike.scala:74)
> [info]   at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
> [info]   at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
> [info]   at org.apache.spark.sql.catalyst.util.TimestampFormatterSuite.$anonfun$new$31(TimestampFormatterSuite.scala:280)
> [info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
> [info]   at org.scalatest.Assertions.withClue(Assertions.scala:1065)
> [info]   at org.scalatest.Assertions.withClue$(Assertions.scala:1052)
> [info]   at org.scalatest.funsuite.AnyFunSuite.withClue(AnyFunSuite.scala:1564)
> [info]   at org.apache.spark.sql.catalyst.util.TimestampFormatterSuite.$anonfun$new$30(TimestampFormatterSuite.scala:271)
> [info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
> [info]   at org.apache.spark.sql.catalyst.util.DateTimeTestUtils$.withDefaultTimeZone(DateTimeTestUtils.scala:61)
> [info]   at org.apache.spark.sql.catalyst.util.TimestampFormatterSuite.$anonfun$new$29(TimestampFormatterSuite.scala:271)
> [info]   at org.apache.spark.sql.catalyst.plans.SQLHelper.withSQLConf(SQLHelper.scala:54)
> [info]   at org.apache.spark.sql.catalyst.plans.SQLHelper.withSQLConf$(SQLHelper.scala:38)
> [info]   at org.apache.spark.sql.catalyst.util.TimestampFormatterSuite.withSQLConf(TimestampFormatterSuite.scala:31)
> [info]   at org.apache.spark.sql.catalyst.util.TimestampFormatterSuite.$anonfun$new$28(TimestampFormatterSuite.scala:270)
> [info]   at org.apache.spark.sql.catalyst.util.TimestampFormatterSuite.$anonfun$new$28$adapted(TimestampFormatterSuite.scala:268)
> [info]   at scala.collection.immutable.List.foreach(List.scala:431)
> [info]   at org.apache.spark.sql.catalyst.util.TimestampFormatterSuite.$anonfun$new$27(TimestampFormatterSuite.scala:268)
> [info]   at org.apache.spark.sql.catalyst.plans.SQLHelper.withSQLConf(SQLHelper.scala:54)
> [info]   at org.apache.spark.sql.catalyst.plans.SQLHelper.withSQLConf$(SQLHelper.scala:38)
> [info]   at org.apache.spark.sql.catalyst.util.TimestampFormatterSuite.withSQLConf(TimestampFormatterSuite.scala:31)
> [info]   at org.apache.spark.sql.catalyst.util.TimestampFormatterSuite.$anonfun$new$26(TimestampFormatterSuite.scala:268)
> [info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
> [info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
> [info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
> [info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
> [info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
> [info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
> [info]   at org.scalatest.funsuite.AnyFunSuiteLike$$anon$1.apply(AnyFunSuiteLike.scala:226)
> [info]   at org.apache.spark.SparkFunSuite.withFixture(SparkFunSuite.scala:207)
> [info]   at org.scalatest.funsuite.AnyFunSuiteLike.invokeWithFixture$1(AnyFunSuiteLike.scala:224)
> [info]   at org.scalatest.funsuite.AnyFunSuiteLike.$anonfun$runTest$1(AnyFunSuiteLike.scala:236)
> [info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
> [info]   at org.scalatest.funsuite.AnyFunSuiteLike.runTest(AnyFunSuiteLike.scala:236)
> [info]   at org.scalatest.funsuite.AnyFunSuiteLike.runTest$(AnyFunSuiteLike.scala:218)
> [info]   at org.apache.spark.SparkFunSuite.org$scalatest$BeforeAndAfterEach$$super$runTest(SparkFunSuite.scala:66)
> [info]   at org.scalatest.BeforeAndAfterEach.runTest(BeforeAndAfterEach.scala:234)
> [info]   at org.scalatest.BeforeAndAfterEach.runTest$(BeforeAndAfterEach.scala:227)
> [info]   at org.apache.spark.SparkFunSuite.runTest(SparkFunSuite.scala:66)
> [info]   at org.scalatest.funsuite.AnyFunSuiteLike.$anonfun$runTests$1(AnyFunSuiteLike.scala:269)
> [info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
> [info]   at scala.collection.immutable.List.foreach(List.scala:431)
> [info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
> [info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
> [info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
> [info]   at org.scalatest.funsuite.AnyFunSuiteLike.runTests(AnyFunSuiteLike.scala:269)
> [info]   at org.scalatest.funsuite.AnyFunSuiteLike.runTests$(AnyFunSuiteLike.scala:268)
> [info]   at org.scalatest.funsuite.AnyFunSuite.runTests(AnyFunSuite.scala:1564)
> [info]   at org.scalatest.Suite.run(Suite.scala:1114)
> [info]   at org.scalatest.Suite.run$(Suite.scala:1096)
> [info]   at org.scalatest.funsuite.AnyFunSuite.org$scalatest$funsuite$AnyFunSuiteLike$$super$run(AnyFunSuite.scala:1564)
> [info]   at org.scalatest.funsuite.AnyFunSuiteLike.$anonfun$run$1(AnyFunSuiteLike.scala:273)
> [info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
> [info]   at org.scalatest.funsuite.AnyFunSuiteLike.run(AnyFunSuiteLike.scala:273)
> [info]   at org.scalatest.funsuite.AnyFunSuiteLike.run$(AnyFunSuiteLike.scala:272)
> [info]   at org.apache.spark.SparkFunSuite.org$scalatest$BeforeAndAfterAll$$super$run(SparkFunSuite.scala:66)
> [info]   at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)
> [info]   at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
> [info]   at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
> [info]   at org.apache.spark.SparkFunSuite.run(SparkFunSuite.scala:66)
> [info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:321)
> [info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:517)
> [info]   at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:413)
> [info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> [info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> [info]   at java.lang.Thread.run(Thread.java:750)
> ```

But it can pass with 8u345

**Comment by srowen** [comment]
Merged to master

**Comment by LuciferYang** [comment]
thanks @srowen @MaxGekk @HyukjinKwon

**Pull request closed without merging**
