### PR TITLE
[SPARK-8476] [CORE] Setters inc/decDiskBytesSpilled in TaskMetrics should also be private.

### PR DESCRIPTION
**Pull request by ueshin**
This is a follow-up of [SPARK-3288](https://issues.apache.org/jira/browse/SPARK-3288).

### CODE REVIEW

**Comment by srowen** [comment]
It's a developer API, but is it worth hiding at this point? does it cause problems?

**Comment by ueshin** [comment]
@srowen, Thank you for your comment.
Yes, it's a developer API for getters, but I think setters should not open for developers like other setters of this class because if they are open, task metrics might be overwritten by developers.

**Comment by srowen** [comment]
A lot of similar stuff was done in 1.3 in SPARK-3288: https://github.com/apache/spark/commit/3453d578ad9933be6881488c8ca3611e5b686af9

Seems consistent, yeah. @rxin are you OK with it? just because you committed this particular line last.

**Comment by rxin** [comment]
LGTM. Merging. Thanks!

**Pull request closed without merging**
