### PR TITLE
[SPARK-46627][SS][UI] Fix timeline tooltip content on streaming ui

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

Fix timeline tooltip content on streaming ui

### Why are the changes needed?

d3 v7 mouseover event has changed, we shall get the values from the 2nd parameter instead of the 1st one which points to the mouse event.

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

image

Additionally, https://issues.apache.org/jira/browse/SPARK-46631 was created to add UT for drawTimeline. We don't do it in this patch because it needs code refactoring beyond the scope of the current PR.

### Was this patch authored or co-authored using generative AI tooling?

no

### CODE REVIEW

**Review by LuciferYang — APPROVED** [review]
+1, LGTM

**Review by sarutak — APPROVED** [review]

**Comment by sarutak** [comment]
Merging to `master`.
Thank you @yaooqinn and @LuciferYang !

**Comment by yaooqinn** [comment]
Thank you @sarutak @LuciferYang

**Comment by dongjoon-hyun** [comment]
+1, LGTM. Thank you, @yaooqinn and all!

**Pull request closed without merging**
