### PR TITLE
[SPARK-22957] ApproxQuantile breaks if the number of rows exceeds MaxInt

### PR DESCRIPTION
**Pull request by juliuszsompolski**
## What changes were proposed in this pull request?

32bit Int was used for row rank.
That overflowed in a dataframe with more than 2B rows.

## How was this patch tested?

Added test, but ignored, as it takes 4 minutes.

### CODE REVIEW

**Comment by srowen** [comment]
Seems reasonable; @clockfly what do you think?
The serialized form changed here, but I'm not sure we'd guarantee compatibility there. This isn't something serialized to files for long-term storage is it?

**Comment by juliuszsompolski** [comment]
If the serialized form change is a problem, that part can probably be reverted - it's far less likely that a single compressed stats chunk will overflow Int.
The bug I hit was in the global rank counter part, and I changed the other part just by reviewing the code around for other places that could conceivably use a Long instead of Int.

**Comment by rxin** [comment]
cc @gatorsmile @cloud-fan

**Comment by cloud-fan** [comment]
LGTM, merging to master/2.3!

**Pull request closed without merging**
