### PR TITLE
[SPARK-31871][CORE][UI] Display the canvas element icon for sorting column

### PR DESCRIPTION
**Pull request by liucht-inspur**
### What changes were proposed in this pull request?
https://issues.apache.org/jira/browse/SPARK-31871
update the url "../"
to"./" of all five places.
For example,
table.dataTable thead .sorting{background-image:url("./images/sort_both.png")}
table.dataTable thead .sorting_asc{background-image:url("./images/sort_asc.png")}
table.dataTable thead .sorting_desc{background-image:url("./images/sort_desc.png")}
table.dataTable thead .sorting_asc_disabled{background-image:url("./images/sort_asc_disabled.png")}
table.dataTable thead .sorting_desc_disabled{background-image:url("./images/sort_desc_disabled.png")}

the path In the current directory:
image

### Why are the changes needed?

The icon could not find the correct path

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?
Fixed existing test.
history server page:
image

executors page:
image

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @gengliangwang and @sarutak FYI

**Comment by HyukjinKwon** [comment]
ok to test

**Comment by sarutak** [comment]
@liucht-inspur 
It's funny that those icons are found in the current `master`.
history
executors

Could you show us the console log of browser and screen shots of before this change?
Also, could you tell us how can we reproduce this issue?

**Comment by liucht-inspur** [comment]
@sarutak 
Thanks for your response .
before this change
history server page like this:
image

Executors page like this:
image

In the current master css code like this:
image
and the icons image really path:
image

so,The icons image url should be changed to ". /images/ XXX " instead of "../images/ XXX "

**Comment by liucht-inspur** [comment]
hi @sarutak the console log of browser is this:

image

**Comment by redsanket** [comment]
@liucht-inspur looks like your history server is 2.4.5? Are we referring to master or an earlier spark 2.4.5 version?

**Comment by sarutak** [comment]
@liucht-inspur As @redsanket pointed out, your history server seems to be version `2.4.5`, while this PR is for `master`.
If this issue occurs for `2.4.5`, could you close this PR and open another PR for `branch-2.4`?

**Comment by liucht-inspur** [comment]
ok，thanks @redsanket @sarutak ,I am doing it.

**Comment by sarutak** [comment]
@liucht-inspur I confirmed this issue happen for `branch-2.4`.
This issue is resolved in `master` by overriding the corresponding style using CSS.
https://github.com/apache/spark/blob/master/core/src/main/resources/org/apache/spark/ui/static/webui-dataTables.css#L46

If you'll open a PR for `branch-2.4`, could you consider the same solution rather than modify the `min.css`?

**Pull request closed without merging**
