### PR TITLE
[SPARK-42754][SQL][UI] Fix backward compatibility issue in nested SQL execution

### PR DESCRIPTION
**Pull request by linhongliu-db**
### What changes were proposed in this pull request?
https://github.com/apache/spark/pull/39268 / [SPARK-41752](https://issues.apache.org/jira/browse/SPARK-41752) added a new non-optional `rootExecutionId: Long` field to the SparkListenerSQLExecutionStart case class.

When JsonProtocol deserializes this event it uses the "ignore missing properties" Jackson deserialization option, causing the rootExecutionField to be initialized with a default value of 0.

The value 0 is a legitimate execution ID, so in the deserialized event we have no ability to distinguish between the absence of a value and a case where all queries have the first query as the root.

Thanks @JoshRosen for reporting and investigating this issue.

### Why are the changes needed?
Bug fix

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
UT

### CODE REVIEW

**Comment by linhongliu-db** [comment]
cc @JoshRosen @rednaxelafx @xinrong-meng

**Review by JoshRosen — APPROVED** [review]
LGTM. Thanks for the fix!

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you so much, @linhongliu-db and @JoshRosen .
I also was suffered by this. :)
Merged to master/3.4.

**Comment by LuciferYang** [comment]
late LGTM

**Pull request closed without merging**
