### PR TITLE
[SPARK-38952][PYTHON] Implement `numeric_only` of `GroupBy.first` and `GroupBy.last`

### PR DESCRIPTION
**Pull request by xinrong-meng**
### What changes were proposed in this pull request?
Implement `numeric_only` of `GroupBy.first/last`.

### Why are the changes needed?
To increase API coverage.

### Does this PR introduce _any_ user-facing change?
Yes. `numeric_only` of `GroupBy.first/last` is supported.

```py
>>> df = ps.DataFrame({"A": [1, 2, 1, 2], "B": [True, False, False, True],  "C": [3, 4, 3, 4], "D": ["a", "b", "b", "a"]})
>>> df
   A      B  C  D
0  1   True  3  a
1  2  False  4  b
2  1  False  3  b
3  2   True  4  a

>>> df.groupby("A").first(numeric_only=True)
       B  C                                                                     
A          
1   True  3
2  False  4
>>> df.groupby("A").last(numeric_only=True)
       B  C
A          
1  False  3
2   True  4
```

### How was this patch tested?
Unit tests.

### CODE REVIEW

**Comment by xinrong-databricks** [comment]
@ueshin @HyukjinKwon @itholic Thank you!

**Review by itholic — APPROVED** [review]
LGTM

**Comment by xinrong-databricks** [comment]
Rebased to update `supported_pandas_api.rst`.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
