### PR TITLE
[SPARK-40379][K8S][FOLLOWUP] Fix scalastyle failure

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This is a follow-up to fix a scalastyle issue.

### Why are the changes needed?

The scalastyle failure was introduced during merging and fixing the indentation manually.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the CIs.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Could you review this, @HyukjinKwon ?

**Comment by dongjoon-hyun** [comment]
Hi, @cloud-fan . Could you review this PR to recover the master branch?

**Review by wangyum — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you so much, @wangyum !

**Comment by wangyum** [comment]
Merged to master

**Pull request closed without merging**
