### PR TITLE
[MINOR][INFRA][3.3] Add ANTLR generated files to .gitignore

### PR DESCRIPTION
**Pull request by yutoacts**
### What changes were proposed in this pull request?

Add git ignore entries for files created by ANTLR.
This is a backport of #35838.

### Why are the changes needed?

To avoid developers from accidentally adding those files when working on parser/lexer.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

By making sure those files are ignored by git status when they exist.

### CODE REVIEW

**Comment by srowen** [comment]
Is this not necessary on the master branch?

**Comment by dongjoon-hyun** [comment]
Actually, this is a backport requested by @pan3793
- https://github.com/apache/spark/pull/35838#issuecomment-1120111003

Although I'm still neutral for this backporting request, cc @MaxGekk since he is the release manager of Apache Spark 3.3.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Guess this is fine. I am okay.

**Comment by srowen** [comment]
Meh, it's just .gitignore entries. If it's at all relevant for 3.3, seems OK

**Comment by srowen** [comment]
Merged to 3.3

**Pull request closed without merging**
