### PR TITLE
[SPARK-36732][SQL][BUILD] Upgrade ORC to 1.6.11

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to upgrade Apache ORC to 1.6.11 to bring the latest bug fixes.

### Why are the changes needed?

Apache ORC 1.6.11 has the following fixes.
- https://issues.apache.org/jira/projects/ORC/versions/12350499

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the CIs.

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @HyukjinKwon ! :)

**Comment by dongjoon-hyun** [comment]
GitHub Action passed. Merged to master/3.2.

**Comment by dongjoon-hyun** [comment]
cc @gengliangwang

**Comment by gengliangwang** [comment]
+1, Thank you @dongjoon-hyun !

**Comment by dongjoon-hyun** [comment]
Thank you, @gengliangwang .

**Pull request closed without merging**
