### PR TITLE
[SPARK-17007][SQL] Move test data files into a test-data folder

### PR DESCRIPTION
**Pull request by petermaxlee**
## What changes were proposed in this pull request?

This patch moves all the test data files in sql/core/src/test/resources to sql/core/src/test/resources/test-data, so we don't clutter the top level sql/core/src/test/resources. Also deleted sql/core/src/test/resources/old-repeated.parquet since it is no longer used.

The change will make it easier to spot sql-tests directory.
## How was this patch tested?

This is a test-only change.

### CODE REVIEW

**Comment by rxin** [comment]
Thanks - merging in master.

**Comment by srowen** [comment]
Seems OK, but src/test/resources was already only a "test data" dir by nature. I don't think this helped anything.

**Comment by cloud-fan** [comment]
backport to 2.0!

**Comment by srowen** [comment]
@cloud-fan why backport into a maintenance release?

**Comment by rxin** [comment]
@srowen there are bug fixes that are tested by this new harness (technically not super relevant to this pr though, but all those files are in the same resources directory).

**Comment by srowen** [comment]
I see. This is also why I would not have made this change.

**Pull request closed without merging**
