### PR TITLE
[SPARK-16502] update depreciated ParquetFileReader()

### PR DESCRIPTION
**Pull request by keypointt**
https://issues.apache.org/jira/browse/SPARK-16502
## What changes were proposed in this pull request?

During code compile, got below depreciation message.

```
/Users/renxin/workspace/spark/sql/core/src/main/java/org/apache/spark/sql/execution/datasources/parquet/SpecificParquetRecordReaderBase.java

Warning:(140, 19) java: ParquetFileReader(org.apache.hadoop.conf.Configuration,org.apache.hadoop.fs.Path,java.util.List<org.apache.parquet.hadoop.metadata.BlockMetaData>,java.util.List<org.apache.parquet.column.ColumnDescriptor>) in org.apache.parquet.hadoop.ParquetFileReader has been deprecated

Warning:(204, 19) java: ParquetFileReader(org.apache.hadoop.conf.Configuration,org.apache.hadoop.fs.Path,java.util.List<org.apache.parquet.hadoop.metadata.BlockMetaData>,java.util.List<org.apache.parquet.column.ColumnDescriptor>) in org.apache.parquet.hadoop.ParquetFileReader has been deprecated

```

Here just updated the method invocation.

from

```
  /** @deprecated */
  public ParquetFileReader(Configuration configuration, Path filePath, List<BlockMetaData> blocks, List<ColumnDescriptor> columns) throws IOException {
    this(configuration, (FileMetaData)null, filePath, blocks, columns);
  }
```

to:

```
  public ParquetFileReader(Configuration configuration, FileMetaData fileMetaData, Path filePath, List<BlockMetaData> blocks, List<ColumnDescriptor> columns) throws IOException {
```
## How was this patch tested?

Tested on local machine, running unit tests.

### CODE REVIEW

**Comment by srowen** [comment]
The thing we have to be careful of in general is making some change that isn't compatible with older versions of things like Hadoop (and their Parquet dependencies). This change could break older Hadoop builds. No idea, but, just suggesting that this is the thing you'd have to test, and the PR builder won't necessarily test vs, say, Hadoop 2.2

**Comment by hvanhovell** [comment]
https://github.com/apache/spark/pull/14159 solves the same thing...

**Comment by keypointt** [comment]
oh I see...sorry didn't notice it's for backward compatibility

I'll close it.

**Comment by srowen** [comment]
I don't know that there's actually a problem, just saying that this is the kind of thing we should be careful about. There are a number of build warnings like this. Your change could be fine.

**Comment by keypointt** [comment]
Hi @srowen I just found it's a duplicate so I closed it.

But, when I ran `./dev/lint-java` I got these style problems. I'm just wondering for these random tiny style fixes, what should I do, just submit a [MINOR] PR?

```
Using `mvn` from path: /usr/local/bin/mvn
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512M; support was removed in 8.0
Checkstyle checks failed at following occurrences:
[ERROR] src/main/java/org/apache/spark/unsafe/memory/HeapMemoryAllocator.java:[27,1] (imports) RedundantImport: Redundant import from the same package - org.apache.spark.unsafe.memory.MemoryAllocator.
[ERROR] src/main/java/org/apache/spark/unsafe/memory/MemoryAllocator.java:[26,3] (modifier) RedundantModifier: Redundant 'public' modifier.
[ERROR] src/main/java/org/apache/spark/unsafe/memory/MemoryAllocator.java:[30,3] (modifier) RedundantModifier: Redundant 'public' modifier.
[ERROR] src/main/java/org/apache/spark/unsafe/memory/MemoryAllocator.java:[31,3] (modifier) RedundantModifier: Redundant 'public' modifier.
[ERROR] src/main/java/org/apache/spark/sql/execution/datasources/parquet/SpecificParquetRecordReaderBase.java:[143] (sizes) LineLength: Line is longer than 100 characters (found 113).
[ERROR] src/main/java/org/apache/spark/sql/execution/datasources/parquet/SpecificParquetRecordReaderBase.java:[208] (sizes) LineLength: Line is longer than 100 characters (found 106).
[ERROR] Failed to execute goal on project spark-streaming-kafka-0-10-assembly_2.11: Could not resolve dependencies for project org.apache.spark:spark-streaming-kafka-0-10-assembly_2.11:jar:2.0.0-SNAPSHOT: Could not find artifact org.apache.spark:spark-streaming-kafka-0-10_2.11:jar:2.0.0-SNAPSHOT in apache.snapshots (http://repository.apache.org/snapshots) -> [Help 1]
```


https://github.com/keypointt/spark/blob/7557e1cf5916331255bebca9d7e4682d8ca4021c/sql/core/src/main/java/org/apache/spark/sql/execution/datasources/parquet/SpecificParquetRecordReaderBase.java#L143

https://github.com/keypointt/spark/blob/7557e1cf5916331255bebca9d7e4682d8ca4021c/sql/core/src/main/java/org/apache/spark/sql/execution/datasources/parquet/SpecificParquetRecordReaderBase.java#L208

**Comment by srowen** [comment]
Yeah, the problem is we don't have anything that runs dev/lint-java regularly. If you find it currently shows errors in master, go ahead and fix them in a [MINOR] PR.

**Comment by keypointt** [comment]
I'll fix these styles, thanks a lot Sean

**Pull request closed without merging**
