### PR TITLE
[SPARK-12112][BUILD] Upgrade to SBT 0.13.9

### PR DESCRIPTION
**Pull request by JoshRosen**
We should upgrade to SBT 0.13.9, since this is a requirement in order to use SBT's new Maven-style resolution features (which will be done in a separate patch, because it's blocked by some binary compatibility issues in the POM reader plugin).

I also upgraded Scalastyle to version 0.8.0, which was necessary in order to fix a Scala 2.10.5 compatibility issue (see https://github.com/scalastyle/scalastyle/issues/156). The newer Scalastyle is slightly stricter about whitespace surrounding tokens, so I fixed the new style violations.

### CODE REVIEW

**Comment by rxin** [comment]
Can we separate the style check update from the sbt update?

**Comment by JoshRosen** [comment]
No, they're tightly coupled which is why the Scalastyle bug was so annoying. For instance, https://github.com/paypal/squbs/issues/36 is an instance of another project whose upgrade was blocked by the same issue.

**Comment by vanzin** [comment]
Since you're upgrading scalastyle, shouldn't you also modify pom.xml?

**Comment by vanzin** [comment]
retest this please

**Comment by vanzin** [comment]
LGTM, btw.

**Comment by JoshRosen** [comment]
@rxin, is it okay with you to merge this with the (necessary) style fixes included?

**Comment by rxin** [comment]
Sure - go head if it is hard to pull out.

**Comment by rxin** [comment]
I've merged this in master.

**Pull request closed without merging**
