### PR TITLE
[SPARK-42136] Refactor BroadcastHashJoinExec output partitioning calculation

### PR DESCRIPTION
**Pull request by peter-toth**
### What changes were proposed in this pull request?
This is PR refactors `BroadcastHashJoinExec` output partitioning calculation using the new `TreeNode.multiTransformDown()` helper so simplify code and improve performance.

### Why are the changes needed?
Simpler code with `TreeNode.multiTransform()`.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Existing UTs.

### CODE REVIEW

**Comment by peter-toth** [comment]
cc @cloud-fan

**Comment by cloud-fan** [comment]
is this PR still update to date?

**Comment by peter-toth** [comment]
> is this PR still up to date?

Yes, it is. This is a simple refactor to utilize `multiTransform()`.

**Comment by peter-toth** [comment]
I've just updated this PR with latest `master`, but it shouldn't make any differene.

**Review by cloud-fan — APPROVED** [review]

**Comment by peter-toth** [comment]
@cloud-fan, please let me know if anything is needed to get this merged.

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Comment by peter-toth** [comment]
Thanks for the review!

**Pull request closed without merging**
