### PR TITLE
[SPARK-35002][INFRA][FOLLOW-UP] Use localhost instead of 127.0.0.1 at SPARK_LOCAL_IP in GA builds

### PR DESCRIPTION
**Pull request by HyukjinKwon**
### What changes were proposed in this pull request?

This PR replaces 127.0.0.1 to `localhost`.

### Why are the changes needed?

- https://github.com/apache/spark/pull/32096#discussion_r610349269
- https://github.com/apache/spark/pull/32096#issuecomment-816442481

### Does this PR introduce _any_ user-facing change?

No, dev-only. 

### How was this patch tested?

I didn't test it because it's CI specific issue. I will test it in Github Actions build in this PR.

### CODE REVIEW

**Review by wangyum — APPROVED** [review]

**Comment by wangyum** [comment]
Merged to master.

**Comment by HyukjinKwon** [comment]
Thanks!

**Comment by HyukjinKwon** [comment]
I merged to branch-3.1 and branch-3.0 too. Seems like it has the same issue.

**Comment by lhotari** [comment]
Just in case it is useful, I created an alternative fix which fixes the root cause of the problem. Reverse name lookups for the current hostname is broken in GitHub Actions Runner VMs (reported as https://github.com/actions/virtual-environments/issues/3185) and this is the workaround: #32173 .

**Pull request closed without merging**
