### PR TITLE
[Docs] fix example code issues in documentation

### PR DESCRIPTION
**Pull request by mawise**
## What changes were proposed in this pull request?

Fixed broken java code examples in streaming documentation

Attn: @tdas

### CODE REVIEW

**Comment by srowen** [comment]
Looks OK, but can you have a look around similar docs and examples for similar issues while you're at it?

**Comment by mawise** [comment]
Nothing jumps out at me as I scan though the docs for similar errors.
There might be some left- I'm not doing a super thorough review.

**Comment by srowen** [comment]
OK. Convention is to add `[MINOR]` to the title BTW. LGTM

**Comment by srowen** [comment]
Jenkins test this please

**Comment by srowen** [comment]
Merged to master/2.0

**Pull request closed without merging**
