### PR TITLE
[SPARK-33498][SQL][TESTS][FOLLOWUP] Remove SQLConf.withExistingConf in CastSuite

### PR DESCRIPTION
**Pull request by maropu**
### What changes were proposed in this pull request?

This PR intends to remove unnecessary `SQLConf.withExistingConf` in `CastSuite`; since we've remove `ParVector ` in #31775, we no longer need to copy SQL configs into each thread env.

### Why are the changes needed?

Clean up the code.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Run the existing tests.

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Thank you for making a follow-up, @maropu .

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.
This is a test-only PR and I verified manually.
```
[info] All tests passed.
[info] Passed: Total 4879, Failed 0, Errors 0, Passed 4879, Ignored 5
[success] Total time: 369 s (06:09), completed Mar 8, 2021 11:51:30 PM
build/sbt "catalyst/test"  1393.45s user 42.65s system 380% cpu 6:16.93 total
```

Merged to master.

**Comment by dongjoon-hyun** [comment]
There is a conflict on branch-3.1. Could you make a backporting PR?

**Comment by dongjoon-hyun** [comment]
Oh, BTW, @maropu .
I realized that this is a follow-up of old SPARK-33498 who fixed version is 3.1.0. It looks a little weird because this goes only to 3.2.0 and 3.1.2.

**Comment by maropu** [comment]
> There is a conflict on branch-3.1. Could you make a backporting PR?

Thanks for your quick review&merge! I'll open a PR for that later.

> I realized that this is a follow-up of old SPARK-33498 who fixed version is 3.1.0. It looks a little weird because this goes only to 3.2.0 and 3.1.2.

Ah, yea, as you said, it looks a bit weird. But, this is a minor update, so IMO it is okay as it is. Or, do you think we need to do anything for that?

**Comment by dongjoon-hyun** [comment]
It's not a problem. I thought it was a follow-up of SPARK-34660 . But, according to this PR's content, it's more proper as a follow-up of SPARK-33498 . Maybe, next time, we had better create a new JIRA for a released patch because the `Fixed Version` are not the same.

**Pull request closed without merging**
