### PR TITLE
[SPARK-25304][SQL][TEST] Fix HiveSparkSubmitSuite SPARK-8489 test for Scala 2.12

### PR DESCRIPTION
**Pull request by da-liii**
## What changes were proposed in this pull request?

remove test-2.10.jar and add test-2.12.jar.

## How was this patch tested?

```
$ sbt -Dscala-2.12
> ++ 2.12.6
> project hive
> testOnly *HiveSparkSubmitSuite -- -z "8489"
```

### CODE REVIEW

**Comment by srowen** [comment]
Oh what's the change here in the .jar file? just copied the jar file for 2.11/2.10?

**Comment by sadhen** [comment]
Remove the deprecated 2.10 jar.

And build a 2.12 jar.

**Comment by sadhen** [comment]
see https://github.com/apache/spark/pull/12924 and https://github.com/apache/spark/pull/11744

**Comment by sadhen** [comment]
@cloud-fan @srowen 

This PR will make our jenkins build green.

https://amplab.cs.berkeley.edu/jenkins/view/Spark%20QA%20Test/job/spark-master-test-maven-hadoop-2.7-ubuntu-scala-2.12/204/testReport/

**Review by felixcheung — COMMENTED** [review]
shouldn't we be careful about having jar in the source tree? (that goes into a release?)

**Comment by srowen** [comment]
@sadhen I mean is this just a copy of the 2.10 jar? what's in the jar?
@felixcheung in this case there's a test specifically testing loading of a jar file, so it has to have a jar file to load. This code isn't part of the non-test code. (The source is there too FWIW)

**Comment by sadhen** [comment]
@srowen  The 2.12 jar is compiled and packaged from `Main.scala` and `MyCoolClass.scala`. Not a copy of 2.10 jar. Diff it, you will verify it.

The steps to generate it:

```
mvn install // install the 2.4.0-SNAPSHOT at project root
sbt package // package at sql/hive/src/test/resources/regression-test-SPARK-8489
```

This is the build.sbt:
```
scalaVersion := 2.12.6
libraryDependencies ++= Seq(
  "org.apache.spark" %% "spark-sql" % "2.4.0-SNAPSHOT"
)
```

**Review by srowen — APPROVED** [review]
OK, that's fine. That makes sense, and it's what the new JAR should be.

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
