### PR TITLE
[SPARK-33457][PYTHON] Adjust mypy configuration

### PR DESCRIPTION
**Pull request by zero323**
### What changes were proposed in this pull request?

This pull request:

- Adds following flags to the main mypy configuration:
  - [`strict_optional`](https://mypy.readthedocs.io/en/stable/config_file.html#confval-strict_optional)
  - [`no_implicit_optional`](https://mypy.readthedocs.io/en/stable/config_file.html#confval-no_implicit_optional)
  - [`disallow_untyped_defs`](https://mypy.readthedocs.io/en/stable/config_file.html#confval-disallow_untyped_calls)

These flags are enabled only for public API and disabled for tests and internal modules.

Additionally, these PR fixes missing annotations.

### Why are the changes needed?

Primary reason to propose this changes is to use standard configuration as used by typeshed project. This will allow us to be more strict, especially when interacting with JVM code. See for example https://github.com/apache/spark/pull/29122#pullrequestreview-513112882

Additionally, it will allow us to detect cases where annotations have unintentionally omitted.

### Does this PR introduce _any_ user-facing change?

Annotations only.

### How was this patch tested?

`dev/lint-python`.

### CODE REVIEW

**Comment by zero323** [comment]
FYI @Fokko  @HyukjinKwon 

Still work in progress, any suggestions about desired flags (I considered `show_error_codes`, for clarity, and `disallow_any_generics`).

**Comment by HyukjinKwon** [comment]
My only concern is the maintenance cost for being strict. If it doesn't add non-trivial overhead, I am good to be more strict on the type hints.

**Comment by zero323** [comment]
> My only concern is the maintenance cost for being strict. If it doesn't add non-trivial overhead, I am good to be more strict on the type hints.

For the first two options - we are already covered, as these were used in `pyspark-stubs`.

The third one required some fixes, but these are mostly things that should be there. In all other cases, we can either ignore the whole module (as with tests and such) or specific lines (for example I considered ignoring `callJavaFunc` as these annotations are hardly useful and  functions are not exactly public). 

So overall, I don't think there's much complexity added and using these, gives us more confidence that annotations are in a good shape.

**Comment by HyukjinKwon** [comment]
@zero323, let me know when you think this is ready. Looks fine to me.

**Review by Fokko — APPROVED** [review]
Looks good!

**Comment by zero323** [comment]
> @zero323, let me know when you think this is ready. Looks fine to me.

Thanks @HyukjinKwon. I went over all violations of `disallow_any_generics` and these are mostly intended (little or no additional value gained by addressing these). So I think it ready to review.


> Looks good!

Thanks for reviewing @Fokko!

**Comment by HyukjinKwon** [comment]
retest this please

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by zero323** [comment]
Thanks @Fokko  and @HyukjinKwon!

**Pull request closed without merging**
