### PR TITLE
[SPARK-28117][ML] LDA and BisectingKMeans cache the input dataset if necessary

### PR DESCRIPTION
**Pull request by zhengruifeng**
## What changes were proposed in this pull request?
cache dataset in BisectingKMeans
cache dataset in LDA if Online solver is chosen.

## How was this patch tested?
existing test

### CODE REVIEW

**Comment by zhengruifeng** [comment]
retest this please

**Review by srowen — COMMENTED** [review]
Looks reasonable

**Comment by zhengruifeng** [comment]
@srowen it seems that this pr is blocked by test suite [SPARK-16473](https://github.com/apache/spark/blob/master/mllib/src/test/scala/org/apache/spark/ml/clustering/BisectingKMeansSuite.scala#L59), would you mind if I disable this test suite for now?
@imatiach-msft  There was some comments about this testsuite in [SPARK-16473](https://issues.apache.org/jira/browse/SPARK-16473) and you suspected that the chached data is changed in the training. However, I test localy and it seems that the dataset unchanged between serveral calls. Would you mind help reviewing this suite?

**Comment by zhengruifeng** [comment]
Or should we divide this pr into two ones: LDA and BIkMeans? If the blocking test suite can not be fixed  quickly?

**Comment by srowen** [comment]
We may need to adjust the test, but I wouldn't disable it. I doubt data is changed, but it may be that caching means the data _doesn't_ change on each iteration. You could simply remove the assertion that there are less than 5 clusters, as I don't see that this is what the test is testing, nor is it invalid to end up with 5 clusters here.

**Comment by imatiach-msft** [comment]
@zhengruifeng  @srowen  +1 I think adjusting the test is fine in this case, I agree that we shouldn't disable it however.  However, if you prefer, you can disable it in this PR and I can investigate and fix the test in a follow-up PR.

**Comment by zhengruifeng** [comment]
@imatiach-msft  as suggested by owen, I just remove the assertion `numClusters < k`

**Review by srowen — APPROVED** [review]

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
