### PR TITLE
[SPARK-45396][DOCS] Add doc entry for `pyspark.ml.connect` module

### PR DESCRIPTION
**Pull request by WeichenXu123**
### What changes were proposed in this pull request?

Add doc entry for `pyspark.ml.connect` module

### Why are the changes needed?

Without doc entry page, user cannot view `pyspark.ml.connect` python APIs on doc website.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Manually

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Review by zhengruifeng — APPROVED** [review]

**Review by HyukjinKwon — APPROVED** [review]
We should also add it to index. I will followup.

**Comment by HyukjinKwon** [comment]
Actually let me take this over since doc build fails.

**Comment by HyukjinKwon** [comment]
Let me take it over at https://github.com/apache/spark/pull/43210

**Comment by WeichenXu123** [comment]
@HyukjinKwon Could you backport this to spark 3.5 branch ?

**Pull request closed without merging**
