### PR TITLE
[MINOR][DOC] Fix a typo in ResolveReferencesInUpdate scaladoc

### PR DESCRIPTION
**Pull request by sdruzkin**
### What changes were proposed in this pull request?
Fixed a typo in the ResolveReferencesInUpdate documentation.

### Does this PR introduce any user-facing change?
No

### How was this patch tested?
CI

### CODE REVIEW

**Review by bjornjorgensen — APPROVED** [review]

**Comment by bjornjorgensen** [comment]
@srowen FYI

**Comment by srowen** [comment]
It's fine, just see if rerunning tests succeeds

**Comment by bjornjorgensen** [comment]
@sdruzkin enable github action on yours fork https://github.com/apache/spark/pull/42322/checks?check_run_id=15597116732

**Comment by sdruzkin** [comment]
Tests are green.

**Comment by srowen** [comment]
Merged to master/3.5

**Pull request closed without merging**
