### PR TITLE
[SPARK-17587][PYTHON][MLLIB] SparseVector __getitem__ should follow __getitem__ contract

### PR DESCRIPTION
**Pull request by zero323**
## What changes were proposed in this pull request?

Replaces`ValueError` with `IndexError` when index passed to `ml` / `mllib` `SparseVector.__getitem__` is out of range. This ensures correct iteration behavior.

Replaces `ValueError` with `IndexError` for `DenseMatrix` and `SparkMatrix` in `ml` / `mllib`.
## How was this patch tested?

PySpark `ml` / `mllib` unit tests. Additional unit tests to prove that the problem has been resolved.

### CODE REVIEW

**Comment by BryanCutler** [comment]
LGTM!

**Comment by BryanCutler** [comment]
It looks like `SparseMatrix` also raises a `ValueError`.  Can you fix that here also?

**Comment by zero323** [comment]
@BryanCutler Sure, here you are. Actually both `Sparse` and `Dense` had to be fixed. 

Note: Technically speaking this can is a breaking change if someone expects `ValueError`.

On a side note it would be nice to support slice and iteration over rows as well but I still hope there is a chance for doing something with [SPARK-16626](https://issues.apache.org/jira/browse/SPARK-16626).

**Comment by jkbradley** [comment]
test this please

**Comment by jkbradley** [comment]
LGTM, merging with master and branch-2.0
Thank you @zero323 for the PR and @BryanCutler for reviewing !

**Pull request closed without merging**
