### PR TITLE
[SPARK-37598][PYTHON] Adding support for ShortWriables to pyspark's newAPIHadoopRDD method

### PR DESCRIPTION
**Pull request by masseyke**
### What changes were proposed in this pull request?
This commit adds support for RDDs containing ShortWritables to pyspark. Right now if a user calls sc.newAPIHadoopRDD() with an InputFormat that provides ShortWritables, the call will fail with an error like the one below because ShortWritable is not explicitly handled by PythonHadoopUtil.
```
>>> rdd = sc.newAPIHadoopRDD(inputFormatClass="org.elasticsearch.hadoop.mr.EsInputFormat",
...                          keyClass="org.apache.hadoop.io.NullWritable",
...                          valueClass="org.elasticsearch.hadoop.mr.LinkedMapWritable",
...                          conf=conf)
2021-12-08 14:38:40,439 ERROR scheduler.TaskSetManager: task 0.0 in stage 15.0 (TID 31) had a not serializable result: org.apache.hadoop.io.ShortWritable
Serialization stack:
	- object not serializable (class: org.apache.hadoop.io.ShortWritable, value: 1)
	- writeObject data (class: java.util.HashMap)
	- object (class java.util.HashMap, {price=1})
	- field (class: scala.Tuple2, name: _2, type: class java.lang.Object)
	- object (class scala.Tuple2, (1,{price=1}))
	- element of array (index: 0)
	- array (class [Lscala.Tuple2;, size 1); not retrying
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/home/hduser/spark-3.1.2-bin-hadoop3.2/python/pyspark/context.py", line 853, in newAPIHadoopRDD
    jconf, batchSize)
  File "/home/hduser/spark-3.1.2-bin-hadoop3.2/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1305, in __call__
  File "/home/hduser/spark-3.1.2-bin-hadoop3.2/python/pyspark/sql/utils.py", line 111, in deco
    return f(*a, **kw)
  File "/home/hduser/spark-3.1.2-bin-hadoop3.2/python/lib/py4j-0.10.9-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.newAPIHadoopRDD.
: org.apache.spark.SparkException: Job aborted due to stage failure: task 0.0 in stage 15.0 (TID 31) had a not serializable result: org.apache.hadoop.io.ShortWritable
Serialization stack:
	- object not serializable (class: org.apache.hadoop.io.ShortWritable, value: 1)
	- writeObject data (class: java.util.HashMap)
	- object (class java.util.HashMap, {price=1})
	- field (class: scala.Tuple2, name: _2, type: class java.lang.Object)
	- object (class scala.Tuple2, (1,{price=1}))
	- element of array (index: 0)
	- array (class [Lscala.Tuple2;, size 1)
	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2258)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2207)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2206)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2206)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1079)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1079)
	at scala.Option.foreach(Option.scala:407)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1079)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2445)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2387)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2376)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:868)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2196)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2217)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2236)
	at org.apache.spark.rdd.RDD.$anonfun$take$1(RDD.scala:1449)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:414)
	at org.apache.spark.rdd.RDD.take(RDD.scala:1422)
	at org.apache.spark.api.python.SerDeUtil$.pairRDDToPython(SerDeUtil.scala:173)
	at org.apache.spark.api.python.PythonRDD$.newAPIHadoopRDD(PythonRDD.scala:385)
	at org.apache.spark.api.python.PythonRDD.newAPIHadoopRDD(PythonRDD.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
```

### Why are the changes needed?
Without these changes, ShortWritables coming from a Hadoop InputFormat will not be converted to Shorts. Instead they will remain ShortWritables. ShortWritables are not Serializable, so spark will fail with a serialization error.

### Does this PR introduce _any_ user-facing change?
Users will be able to use InputFormats that use ShortWritables, which was previously not possible.

### How was this patch tested?
I have adde unit tests in org.apache.spark.api.python.PythonHadoopUtilSuite. Without the code change these tests fail. I have also manually tested this in the situation where this originally came up -- if an Elasticsearch mapping has a short field and you read the data out using es-hadoop's pyspark integration's newAPIHadoopRDD method then it was previously failing but succeeds now.

### CODE REVIEW

**Comment by masseyke** [comment]
This was originally reported here -- https://discuss.elastic.co/t/es-hadoop-serialize-org-apache-hadoop-io-shortwritable-failed/276894

**Comment by HyukjinKwon** [comment]
ok to test

**Review by HyukjinKwon — COMMENTED** [review]
Looks good but how did you test this? it would be great to keep GitHub PR template: https://github.com/apache/spark/blob/master/.github/PULL_REQUEST_TEMPLATE. Also Apache Spark uses GitHub Actions from forked repository, see also https://github.com/apache/spark/pull/34838/checks?check_run_id=4459879248

**Comment by HyukjinKwon** [comment]
We would also have to file a JIRA. See also https://spark.apache.org/contributing.html

**Comment by masseyke** [comment]
> Looks good but how did you test this? it would be great to keep GitHub PR template: https://github.com/apache/spark/blob/master/.github/PULL_REQUEST_TEMPLATE. Also Apache Spark uses GitHub Actions from forked repository, see also https://github.com/apache/spark/pull/34838/checks?check_run_id=4459879248

I didn't see an existing unit test for that class, so I manually tested it by creating a mapping with a short field in Elasticsearch, and then reading that data with es-spark (it fails before the patch). I can put the template back in and add a jira ticket. I believe I've enabled github actions now (not completely sure) but I don't know how to re-trigger the build.

**Comment by HyukjinKwon** [comment]
LGTM

**Comment by masseyke** [comment]
I'm unclear on why tests are failing. They actually don't seem to be executing. I believe I've enabled everything I need to in the actions tab of my fork. Any tips on what I might be missing? Thanks.

**Review by srowen — CHANGES_REQUESTED** [review]
Looks like we are missing ByteWritable too, can you add that here?
Bonus points for adding tests for all the primitive types, as you started a test suite, but not required.

**Comment by srowen** [comment]
I even wonder: should we support String -> Text Writable here too?

**Comment by masseyke** [comment]
> Looks like we are missing ByteWritable too, can you add that here? Bonus points for adding tests for all the primitive types, as you started a test suite, but not required.

Oh you're right -- I missed that there's a separate ByteWritable from BytesWritable. I'll add that (and some more tests).

**Comment by masseyke** [comment]
> I even wonder: should we support String -> Text Writable here too?

Not sure what you mean here -- we do support Text -> String. Maybe a typo, and you meant we ought to support Short -> ShortWritable in convertToWritable()? That would make sense to me.

**Comment by srowen** [comment]
Sorry, no I am just not reading carefully. string is already there in the code, disregard that.

**Comment by masseyke** [comment]
I added ByteWritable, and added roundtrip tests for all of the basic types. That did mean that I needed to update convertToWritable() as well.

**Review by srowen — APPROVED** [review]
Looks good pending tests

**Comment by srowen** [comment]
Maybe a question for @dongjoon-hyun or others more familiar with the GA builds - this fails because it takes more than 6 hours. Are we facing that problem in general with GA tests and is there anything we can do, other than try to shorten the tests?

**Comment by HyukjinKwon** [comment]
@masseyke, can you retrigger https://github.com/masseyke/spark/actions/runs/1565441431 and see how it goes? I think there was an issue in GA env. It should take around 1.5 hours in general.

**Comment by masseyke** [comment]
> @masseyke, can you retrigger https://github.com/masseyke/spark/actions/runs/1565441431 and see how it goes? I think there was an issue in GA env. It should take around 1.5 hours in general.

I have retriggered it.

**Comment by srowen** [comment]
Error looks unrelated, I think? 
```
Error in loadNamespace(x) : there is no package called ‘pkgdown’
Calls: loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
```

**Comment by HyukjinKwon** [comment]
nope, that error is likely from https://github.com/apache/spark/commit/16d1c68e8b185457ae86a248d0874e61c3bc6f3a. the latest master branch requires to have that package but the old branch in the forked repository does not have it. it shouldn't be an issue.

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by dongjoon-hyun** [comment]
Sorry for late reply, @srowen .  I'm +1 for @HyukjinKwon 's analysis.
> Maybe a question for dongjoon-hyun or others more familiar with the GA builds

**Pull request closed without merging**
