### PR TITLE
[SPARK-8548][SparkR] Remove the trailing whitespaces from the SparkR files

### PR DESCRIPTION
**Pull request by yu-iskw**
[[SPARK-8548] Remove the trailing whitespaces from the SparkR files - ASF JIRA](https://issues.apache.org/jira/browse/SPARK-8548)
- This is the result of `lint-r`
  https://gist.github.com/yu-iskw/0019b37a2c1167f33986

### CODE REVIEW

**Comment by yu-iskw** [comment]
@shivaram Could you review it please when you have time? Thanks!

**Comment by shivaram** [comment]
Thanks @yu-iskw -- LGTM. Merging this

**Comment by shivaram** [comment]
Also FYI I also backported this to branch-1.4 as it'll make future cherry-picks easier.

**Comment by yu-iskw** [comment]
@shivaram Thank you for merging it!

**Pull request closed without merging**
