### PR TITLE
[MINOR][PYTHON] Fix python linter in master

### PR DESCRIPTION
**Pull request by zhengruifeng**
### What changes were proposed in this pull request?
Fix python linter

### Why are the changes needed?
https://github.com/apache/spark/actions/runs/6413129615/job/17411605510

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
local test

```
(spark_dev_311) ➜  spark git:(minor_fix_python_linter) dev/lint-python
starting python compilation test...
python compilation succeeded.

starting black test...
black checks passed.

starting flake8 test...
flake8 checks passed.

starting mypy annotations test...
annotations passed mypy checks.

starting mypy examples test...
examples passed mypy checks.

starting mypy data test...
annotations passed data checks.


all lint-python tests passed!
```

### Was this patch authored or co-authored using generative AI tooling?
no

### CODE REVIEW

**Comment by zhengruifeng** [comment]
it seems this change in https://github.com/apache/spark/pull/43215/files was ignored in PR merge:

https://github.com/apache/spark/pull/43215/files#diff-34a75a8676be2e890201fdd0b7c016cf95d9c216086d01f7150e59fdc66cf6c2L1692-L1697

**Comment by zhengruifeng** [comment]
cc @HyukjinKwon

**Comment by zhengruifeng** [comment]
it was a logical conflict between https://github.com/zhengruifeng/spark/commit/05cdec8e06507b7e4d84198209038c39fbb234d1 and https://github.com/zhengruifeng/spark/commit/a99f3106c802710a1fe31773ffbae709bcd5b690

**Review by HyukjinKwon — COMMENTED** [review]
LGTM

**Pull request closed without merging**
