### PR TITLE
[SPARK-20706][SPARK-SHELL] Spark-shell not overriding method/variable definition

### PR DESCRIPTION
**Pull request by mpetruska**
## What changes were proposed in this pull request?

[SPARK-20706](https://issues.apache.org/jira/browse/SPARK-20706): Spark-shell not overriding method/variable definition
This is a Scala repl bug ( [SI-9740](https://github.com/scala/bug/issues/9740) ), was fixed in version 2.11.9 ( [see the original PR](https://github.com/scala/scala/pull/5090) )

## How was this patch tested?

Added a new test case in `ReplSuite`.

### CODE REVIEW

**Comment by srowen** [comment]
OK, so another back-port to fix the 2.11 REPL, which should be resolved in 2.12 anyway?

**Comment by mpetruska** [comment]
This one has a "Major" priority; but otherwise yes, it should be resolved in Scala 2.12 version.

**Comment by mpetruska** [comment]
By the way, are these contributions valuable, or should the focus be 2.12?

**Comment by mpetruska** [comment]
Jenkins, re-test this, please.

**Comment by mpetruska** [comment]
Jenkins, retest this please.

**Comment by srowen** [comment]
Yes, I think it's reasonable to pull these fixes forward to patch medium-sized problems. We don't have 2.12 support fully working yet, even, so punting the solution to 2.12 means punting to 3.0, probably, and that's still ~6 months off. Meanwhile 2.3 is imminent.

**Comment by mpetruska** [comment]
retest this please

**Comment by mpetruska** [comment]
Fixed the style check problems of the documentation comments. Unfortunately I did not find a way to make Jenkins re-run the tests.

**Comment by srowen** [comment]
Jenkins add to whitelist

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
