### PR TITLE
[SPARK-15642][SQL] Bug report: metadata gets lost when selecting a field of a StructType

### PR DESCRIPTION
**Pull request by zommerfelds**
This PR only shows how to reproduce the bug.
https://issues.apache.org/jira/browse/SPARK-15642

I am not sure if this is expected behaviour or not, please comment.

EDIT: removed WIP from title

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Hi @zommerfelds, do you mind if I ask whether you still working on this? It seems inactive for more than a half year. Maybe, it'd be better closed for now if you are currently not able to work on this further.

**Comment by zommerfelds** [comment]
Hi @HyukjinKwon, I never worked on the fix, because I never got confirmation if this is actually a bug or not. This PR demonstrates the bug I posted on Jira.
If you want I can try to find out if this is still present in the most recent version of Spark.

**Comment by HyukjinKwon** [comment]
Aha, then to be strict, it is not WIP but just waiting the feedback. How about closing this and pinging related guys who touched this code path lately in the JIRA?

**Comment by zommerfelds** [comment]
Sure, I agree, I think at the time putting the label seemed to be
reasonable, after reading the documentation.

I will check and see if this error is still present. How would I go about
pinging related people? Git blame and search if they are on Jira?

**Comment by HyukjinKwon** [comment]
Yes, exactly. That's usually I do.

**Comment by zommerfelds** [comment]
The bug is still present. To be honest I don't think I have time to work on this right now, so we can close this PR if you want. I tried to find the code that was related to this functionality but didn't get there yet, so not sure who to contact. Someone might be able to tell really fast if this is a bug or not, and what has to be done to fix it.

**Pull request closed without merging**
