### PR TITLE
[SPARK-34842][SQL][TESTS] Corrects the type of `date_dim.d_quarter_name` in the TPCDS schema

### PR DESCRIPTION
**Pull request by maropu**
### What changes were proposed in this pull request?

SPARK-34083 (#31012) has a typo in the type of `date_dim.d_quarter_name` in the TPCDS schema (`TPCDSBase`). This PR replace `CHAR(1)` with `CHAR(6)`. This fix comes from p28 in [the TPCDS official doc](http://www.tpc.org/tpc_documents_current_versions/pdf/tpc-ds_v2.9.0.pdf).

### Why are the changes needed?

Bugfix.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

N/A

### CODE REVIEW

**Comment by maropu** [comment]
cc: @yaooqinn @dongjoon-hyun @cloud-fan

**Review by yaooqinn — APPROVED** [review]
nice catch~ lgtm

**Review by cloud-fan — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Review by wangyum — APPROVED** [review]

**Review by HyukjinKwon — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @maropu and all. Merged to master/3.1.

**Comment by maropu** [comment]
Thanks, @dongjoon-hyun and all!

**Pull request closed without merging**
