### PR TITLE
[SPARK-42627][SPARK-26494][SQL] Support Oracle TIMESTAMP WITH LOCAL TIME ZONE

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

This PR supports TIMESTAMP WITH LOCAL TIME ZONE Datatype

> TIMESTAMP WITH LOCAL TIME ZONE is another variant of TIMESTAMP. It differs from TIMESTAMP WITH TIME ZONE as follows: data stored in the database is normalized to the database time zone, and the time zone offset is not stored as part of the column data. When users retrieve the data, Oracle returns it in the users' local session time zone. The time zone offset is the difference (in hours and minutes) between local time and UTC (Coordinated Universal Time, formerly Greenwich Mean Time).

### Why are the changes needed?

Improve functionality with Oracle Datasource read/write

### Does this PR introduce _any_ user-facing change?

Yes， TIMESTAMP WITH LOCAL TIME ZONE is supported

### How was this patch tested?

new tests

### Was this patch authored or co-authored using generative AI tooling?
no

### CODE REVIEW

**Comment by steveloughran** [comment]
oh, no another TZ type. From oracle -there's a surprise.

**Comment by dongjoon-hyun** [comment]
What do you mean, @steveloughran ? `TimestampLTZ` itself is used in Apache Spark already.

> oh, no another TZ type. From oracle -there's a surprise.

**Review by MaxGekk — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM (Pending CIs).

Could you re-trigger CIs, @yaooqinn ?

**Comment by yaooqinn** [comment]
Thanks, @steveloughran @dongjoon-hyun @MaxGekk 

merged to master

**Comment by steveloughran** [comment]
@dongjoon-hyun I'm just thinking of all the timestamps in ORC and parquet and when they are local vs UTC...

**Pull request closed without merging**
