### PR TITLE
[SPARK-11553] [SQL] Primitive Row accessors should not convert null to default value

### PR DESCRIPTION
**Pull request by alberskib**
Invocation of getters for type extending AnyVal returns default value (if field value is null) instead of throwing NPE. Please check comments for SPARK-11553 issue for more details.

### CODE REVIEW

**Comment by rxin** [comment]
This change breaks binary compatibility. I think we should just update the documentation to say use isNull to check for primitive types.

**Comment by alberskib** [comment]
We could also change only implementation of methods for primitive types (getInt, getDouble etc) to do null check internally and do not change code of getAs but update documentation as you said.

**Comment by marmbrus** [comment]
ok to test

**Comment by marmbrus** [comment]
Please change the PR title to something more descriptive: `[SPARK-11553] [SQL] Primitive Row accessors should not convert null to default value`

**Comment by alberskib** [comment]
The only failing test is 'Sessions of SQLContext' in org.apache.spark.sql.SQLContextSuite. Unfortunately on my machine I am not able to reproduce the problem - it is working well.

I also noticed that in org.apache.spark.sql.SQLContextSuite there is myadd method which is not used anywhere. I think that is should be removed.

**Comment by alberskib** [comment]
After rebasing to current master all tests are passing

**Comment by hvanhovell** [comment]
```UnsafeRow``` and ```SpecificRow``` have similar problems. Shouldn't we fix those as well? For example:

    import org.apache.spark.sql.types.IntegerType
    import org.apache.spark.sql.catalyst.expressions.SpecificMutableRow
    import org.apache.spark.sql.catalyst.expressions.UnsafeRow

    val srow = new SpecificMutableRow(IntegerType :: Nil)
    srow.isNullAt(0)
    srow.getInt(0)

    val urow = new UnsafeRow()
    urow.pointTo(new Array[Byte](16), 1, 4)
    urow.isNullAt(0)
    urow.getInt(0)

    // Result:
    import org.apache.spark.sql.types.IntegerType
    import org.apache.spark.sql.catalyst.expressions.SpecificMutableRow
    import org.apache.spark.sql.catalyst.expressions.UnsafeRow
    srow: org.apache.spark.sql.catalyst.expressions.SpecificMutableRow = [null]
    res129: Boolean = true
    res130: Int = 0
    urow: org.apache.spark.sql.catalyst.expressions.UnsafeRow = []
    res133: Boolean = false
    res134: Int = 0

I'd actualy rather not touch this at all. When you are using internal API you should be more carefull and expect some quirkiness.

I can currently think of only one place in which this causes some problems: UDFs with primitive parameters. The engine will pass in default values instead of nulls. Are there any other situations in which this causes problems?

**Comment by alberskib** [comment]
Hey @hvanhovell ! Thanks for the comment. I agree with you that if we want to introduce this change we need to take care of `UnsafeRow`  and `SpecificRow` as well.
I have couple of questions for you:
> I'd actualy rather not touch this at all ...

You mean discard change and only update documentation? Yes this is one option - I even think that it is not so bad. 
On the other hand it could be misleading and many users will not notice the difference in documentation - this leads them to making the same errors. I think that right now there is lot of code that is calculating wrong outcomes as a result of this bug.

> I can currently think of only one place in which this causes some problems

You mean problem caused by not introducing this change?

I think that we should analyse pros and cons and decide how to proceed.

**Comment by hvanhovell** [comment]
> You mean discard change and only update documentation? Yes this is one option - I even think that it is not so bad. 

I would only update the documentation. Internal mutable rows are among the most performance critical classes in Spark SQL, so I am not that keen to add (potentially unnecessary) branching to every primitive getter. When someone is using ```InternalRow```s he or she is using a SparkSQL internal API anyway, and really should be knowing what (s)he is doing.

> You mean problem caused by not introducing this change?

Yes, do you know any other problems caused by this?

**Comment by alberskib** [comment]
> Yes, do you know any other problems caused by this?
Right now I did not find any other potential problem.

**Comment by alberskib** [comment]
There is no scaladoc for primitive getters in `UnsafeRow` and `SpecificRow` (and super classes) - everything remains there as is.

**Comment by hvanhovell** [comment]
So I have been making a lot of fuss about internal classes, which you are not touching. Sorry about that.

This change is much more benign, but I still wonder if you need to start throwing ```NPE```'s. I'd prefer to update the documentation.

**Comment by alberskib** [comment]
No problem.
I am not sure which option is better. At the beginning I was thinking that it is easier to notice exception being throwned rather than change in the documentation, but right now it looks like changing only documentation will be more consistent. 
It will be good if more people will express opinion.

**Comment by marmbrus** [comment]
The original behavior of these classes was to throw if you tried to retrieve a null primitive value and I think thats a lot less confusing.  Unfortunately it seems that the tungsten refactoring changed this behavior, but since it was the original behavior I'm in favor of returning to it.

**Comment by marmbrus** [comment]
Regarding the internal classes, my preferred option would be to add assertions that we can elide for performance in production.

**Comment by marmbrus** [comment]
Thanks, I'm going to merge this to master and 1.6.

**Pull request closed without merging**
