### PR TITLE
[Minor] Minor update for document

### PR DESCRIPTION
**Pull request by viirya**
Two minor doc errors in `BytesToBytesMap` and `UnsafeRow`.

### CODE REVIEW

**Comment by srowen** [comment]
LGTM

**Comment by viirya** [comment]
retest this please.

**Comment by viirya** [comment]
jenkins seems unstable?

**Comment by srowen** [comment]
Yeah we have a bad worker -- Patrick is sorting it out as we speak.

**Comment by srowen** [comment]
Jenkins retest this please.

**Pull request closed without merging**
