### PR TITLE
[SPARK-18198][Doc][Streaming] Highlight code snippets

### PR DESCRIPTION
**Pull request by lw-lin**
## What changes were proposed in this pull request?

This patch uses `{% highlight lang %}...{% endhighlight %}` to highlight code snippets in the `Structured Streaming Kafka010 integration doc` and the `Spark Streaming Kafka010 integration doc`.

This patch consists of two commits:
- the first commit fixes only the leading spaces -- this is large
- the second commit adds the highlight instructions -- this is much simpler and easier to review

## How was this patch tested?

SKIP_API=1 jekyll build

## Screenshots

**Before**

snip20161101_3

**After**

snip20161101_1

### CODE REVIEW

**Comment by lw-lin** [comment]
Fix the leading spaces is needed, because without the fixing the code snippet would contain leading spaces as well(see the pic below), which is quite inconsistent with the other programming guides.

snip20161101_5

**Comment by lw-lin** [comment]
@koeninger @srowen it'd be great if you could take a look at this too :)

**Comment by srowen** [comment]
That is nicer. Are there any other code snippets across the code base that need this treatment? seems like this is always the right thing to do.

**Comment by lw-lin** [comment]
@srowen thanks.

I'm afraid the streaming `flume integration doc`, `kinesis integration doc`, as well as `kafka08 integration doc` also need code highlights, but this `{% hightlight %}` syntax seem to be conflict with the indentation syntax (e.g. https://github.com/apache/spark/blame/branch-2.0/docs/streaming-flume-integration.md#L40-L73). So that's why the `flume`, `kinesis`, `kafka08` docs don't have code highlights in the first place. `structured streaming kafka010`, `spark streaming kafka010`doc, on the other hand, don't have such conflicts -- so we're adding code highlights here.

And to my acknowledgement, no other code base need this treatment.

**Comment by srowen** [comment]
What about unindenting those blocks? I don't see why they have to be in the first place. They're HTML tags.

**Comment by lw-lin** [comment]
snip20161101_7

Please see the screenshot above -- this is `flume doc` -- I got this by unindenting the second block. Then:

- the second block's indent does not look as pretty as the first's and the third's
- the third block's numbering just goes wrong -- it should have been `3.`

**Comment by srowen** [comment]
What about keeping the indent of the div tags but un-indenting only the code? it might look weird in markdown but does it look nice in the rendered output?

If it's any more trouble than that, forget it.

**Comment by lw-lin** [comment]
Good question!

Actually I had tried keeping the indent of the div tags but un-indenting only the code before I open this pr -- and it looked like this:

snip20161102_8

That was when I gave up trying more on the `flume`, `kinesis`, `kafka08` docs. :-D

**Comment by srowen** [comment]
I guess we could restructure the headings to not have these numbered, indented sections to begin with, but that's a separate task I think.

**Comment by lw-lin** [comment]
Sounds good!

**Comment by koeninger** [comment]
LGTM

**Comment by HyukjinKwon** [comment]
+1

**Comment by srowen** [comment]
Merged to master

**Comment by lw-lin** [comment]
@srowen thanks -- could we also merge this into branch-2.1?

**Comment by srowen** [comment]
Oops, I see, we've cut branch 2.1. I must have missed that one too along with other dev@ lists going to spam. Yes I will go back and make sure a few I've just merged to master are in 2.1.

**Pull request closed without merging**
