### PR TITLE
[SPARK-30005][INFRA] Update `test-dependencies.sh` to check `hive-1.2/2.3` profile

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to update `test-dependencies.sh` to validate all available `Hadoop/Hive` combination.

### Why are the changes needed?

Previously, we have been checking only `Hadoop2.7/Hive1.2` and `Hadoop3.2/Hive2.3`.
We need to validate `Hadoop2.7/Hive2.3` additionally for Apache Spark 3.0.

### Does this PR introduce any user-facing change?

No. (This is a dev-only change).

### How was this patch tested?

Pass the GitHub Action (Linter) with the newly updated manifest because this is only dependency check.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
cc @srowen , @liancheng , @HyukjinKwon , @wangyum

**Comment by dongjoon-hyun** [comment]
Hi, could you review this please, @maropu ?

**Comment by dongjoon-hyun** [comment]
Hi, @srowen .
Could you review this PR, please?

**Review by srowen — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @srowen !
Merged to master.

**Review by HyukjinKwon — COMMENTED** [review]
+1 looks fine to me too

**Comment by maropu** [comment]
Ur, I missed ping... sorry. late LGTM.

**Pull request closed without merging**
