### PR TITLE
[SPARK-41378][SQL][FOLLOWUP] Use toAttributeMap before comparison

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR is a follow-up to fix Scala 2.13 test failure by using `toAttributeMap` before comparion.

### Why are the changes needed?

To recover Scala 2.13 tests.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the CIs and manually run Scala 2.13.
```
$ dev/change-scala-version.sh 2.13
$ build/sbt -Pscala-2.13 "sql/testOnly *.DataSourceV2SQLSuiteV1Filter -- -z SPARK-41378"
...
[info] DataSourceV2SQLSuiteV1Filter:
[info] - SPARK-41378: test column stats (3 seconds, 312 milliseconds)
[info] Run completed in 11 seconds, 159 milliseconds.
[info] Total number of tests run: 1
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 1, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
```

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
cc @huaxingao and @HyukjinKwon

**Review by huaxingao — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @huaxingao . 
I verified this test PR on both Scala 2.12 and 2.13. I'll merge this to recover Scala 2.13 scheduled CI.

**Comment by HyukjinKwon** [comment]
Thx!

**Comment by cloud-fan** [comment]
thanks for the quick fix!

**Comment by LuciferYang** [comment]
Thanks @dongjoon-hyun

**Pull request closed without merging**
