### PR TITLE
[SPARK-8679] [PySpark] [MLlib] Default values in Pipeline API should be immutable

### PR DESCRIPTION
**Pull request by MechCoder**
It might be dangerous to have a mutable as value for default param. (http://stackoverflow.com/a/11416002/1170730)

e.g

```
def func(example, f={}):
    f[example] = 1
    return f

func(2)

{2: 1}
func(3)
{2:1, 3:1}
```

@mengxr

### CODE REVIEW

**Comment by MechCoder** [comment]
jenkins test this please

**Comment by JoshRosen** [comment]
LGTM.  I used `pylint` / `prospector` to lint this file and it looks like this has fixed all occurrences of the "dangerous-default-value" pattern in this file.

In the future, it might be nice to enable a lint check for this as part of the automated build checks, but lets do that separately (I've filed https://issues.apache.org/jira/browse/SPARK-8706 for this).

@mengxr, I'll let you merge this.

**Comment by MechCoder** [comment]
I pushed one more instance that I came across today. Btw, what's with the comment showing test failed but the build showing test passed.

**Comment by JoshRosen** [comment]
The spurious failure message from AmplabJenkins is a side-effect of some changes which skip the JVM tests for PRs that only touch certain PySpark modules. Ignore the status messages from AmplabJenkins and pay attention to SparkQA instead.  I'm trying to fix this via the Jenkins configuration.

**Comment by MechCoder** [comment]
Thanks for the clarification!

**Comment by MechCoder** [comment]
jenkins test this please

**Comment by JoshRosen** [comment]
The PySpark ML tests passed, so this looks fine to me.

**Comment by JoshRosen** [comment]
Jenkins, retest this please.

**Comment by JoshRosen** [comment]
I'm testing out a slightly silly hack to see if I can prevent the spurious AmplabJenkins errors: at the bottom of our Jenkins "execute shell" command, I'm adding an extra call to `build/sbt unsafe/test`, which will run a Java test suite which only takes maybe 5 seconds to run.  This will ensure that we always run at least one JVM-based test, which will create a JUnit XML test report; this should suppress the "could not find test reports" warning from the Jenkins JUnit plugin.  Let's see if it works...

**Comment by JoshRosen** [comment]
Woohoo, looks like my hack worked :)

**Comment by JoshRosen** [comment]
A slightly related concern is mutation of non-default arguments.  There might be cases where we need to defensively copy the input arguments, but I'm not familiar enough with MLlib to know where they might occur.

**Comment by MechCoder** [comment]
Hmm. Scikit-learn has a `copy` argument in most of the model constructors to avoid this. Imagine a person feeding huge amounts of data to find all of them overwritten. But that's lesser of a concern here because the input data is mostly in the form of RDD's and DataFrames. We can always fix it when it is reported as broke :P

**Comment by JoshRosen** [comment]
Jenkins, retest this please.

**Comment by JoshRosen** [comment]
(Re-testing to test the new PySpark test parallelization)

**Comment by mengxr** [comment]
Merged into master and branch-1.4. Thanks!

**Comment by mengxr** [comment]
@MechCoder The JIRA should be 8678 instead of 8679. Please check the JIRA number next time:)

**Comment by MechCoder** [comment]
alright, thanks! :)

**Pull request closed without merging**
