### PR TITLE
[SPARK-31764][CORE] JsonProtocol doesn't write RDDInfo#isBarrier

### PR DESCRIPTION
**Pull request by sarutak**
### What changes were proposed in this pull request?

This PR changes JsonProtocol to write RDDInfos#isBarrier.

### Why are the changes needed?

JsonProtocol reads RDDInfos#isBarrier but not write it so it's a bug.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

I added a testcase.

### CODE REVIEW

**Comment by sarutak** [comment]
Test seems to be aborted.

**Comment by sarutak** [comment]
retest this please.

**Review by HeartSaVioR — APPROVED** [review]
LGTM

**Comment by HeartSaVioR** [comment]
cc. @jiangxb1987

This is newly added in Spark 3.0.0, which is ideal to be addressed in 3.0.0 if possible.

**Review by seanli-rallyhealth — APPROVED** [review]

**Review by jiangxb1987 — APPROVED** [review]
LGTM

**Comment by jiangxb1987** [comment]
retest this please

**Comment by jiangxb1987** [comment]
retest this please

**Comment by jiangxb1987** [comment]
Thanks, merged to master!

**Pull request closed without merging**
