### PR TITLE
[SPARK-29687][SQL] Fix JDBC metrics counter data type

### PR DESCRIPTION
**Pull request by ulysses-you**
### What changes were proposed in this pull request?

Fix JDBC metrics counter data type. Related pull request [26109](https://github.com/apache/spark/pull/26109).

### Why are the changes needed?

Avoid overflow.

### Does this PR introduce any user-facing change?

No.

### How was this patch tested?

Exists UT.

### CODE REVIEW

**Comment by ulysses-you** [comment]
cc @HeartSaVioR  @HyukjinKwon @maropu

**Review by HeartSaVioR — APPROVED** [review]
LGTM

**Review by srowen — APPROVED** [review]

**Review by maropu — APPROVED** [review]
Ur, I see. Nice catch. LGTM

**Comment by maropu** [comment]
Thanks! Merged to master.

**Comment by ulysses-you** [comment]
Thanks all !

**Pull request closed without merging**
