### PR TITLE
[SPARK-9182][SQL] Cast filters are not passed through to datasources

### PR DESCRIPTION
**Pull request by HyukjinKwon**
As mentioned in https://issues.apache.org/jira/browse/SPARK-9182,

Some casts filters are not passing to datasources  (The original PR was reverted because of some downcasting issues).

So, for this PR, rather than checking the range or constant-folding, I just made the actual cast to check if down-casting actually happens.

Test codes and some codes are basically similar with the previous ones (@yjshen).

 The codes are a bit messy and might need to be cleaned up.

@liancheng Could you please review this PR?

### CODE REVIEW

**Comment by liancheng** [comment]
ok to test

**Comment by rxin** [comment]
Does this actually work? Roundtrip in cast doesn't always end up having the same value (e.g. casting a double to int and back loses precision)

**Comment by HyukjinKwon** [comment]
I think in that cast it does not create any condition as `double -> int -> double` means, the field type is int and the given value type is double. Losing precision during this convert means the given value cannot be converted to the field type. (I might misunderstood your comment). I just tested and added some more test codes. Could you give me the case you think?




I tested and added some more test codes for other type conversions. Could you give me a specific case?

**Comment by HyukjinKwon** [comment]
It look ok to JDBC datasource tough. I am wondering if conversion from `NumericType` to `StringType` should be prevented or treated for each differently as it looks unsafe for Parquet and ORC. For example, when column `A` is string, `A >100' will push down a filter with string value performing string comperison.

**Comment by HyukjinKwon** [comment]
It is OK for JDBC but for Parquet and ORC, it looks the conversion from `StringType` to `NumericType` are not safe.

When the field type is `StringType`, then the given numeric value is converted to `String` and it compares both as string which ends up in wrong comparison. 

Also, it looks sometimes `Cast()` fails when trying to cast unrealistic values. So, it returns false when it fails just in case.

**Comment by liancheng** [comment]
@HyukjinKwon How about only deal with cases that do widening? E.g. int to double, float to double, long to decimal, etc. The original case mentioned in SPARK-9182 is int to decimal. In this way, we can be pretty sure that the casting is safe.

**Comment by HyukjinKwon** [comment]
Yes I will do so.

**Comment by HyukjinKwon** [comment]
It looks the original case became a downcast `Decimal(10, 0)` to `Decimal(7, 2)` which seems when scale and precision of the latter are less than the former, rather than int to decimal. I think there have been an update at Optimizer.

It looks roughly in most cases, the conversions need to be downcasted. 
Here is a list i tested.

1. Where `A` is `IntegerType`
`WHERE A <= 2500` becomes int to int
`WHERE A <= 2500.0` becomes decimal(11, 1) to decimal(10, 0)

2. Where `A` is `Decimal(7,2)`
`WHERE A <= 2500` becomes decimal(10, 0) to decimal(7, 2)
`WHERE A <= 2500.0` becomes decimal(7, 2) to decimal(7, 2)
`WHERE A <= 2500.00` becomes decimal(12, 2) to decimal(7, 2)

3. Where `A` is `Double`
`WHERE A <= 2500` becomes double to double
`WHERE A <= 2500.0` becomes double to double

So I think even if I check the widening cast dealing with types and both precision and scale in `Decimal`, neither this issue can be resolved nor deals with a lot of use-cases.

I'm not too sure if 
1. I should just go for this
2. handles only numbers including downcasts with `Cast(...).eval()`, or 
3. just close this.

**Comment by liancheng** [comment]
ok to test

**Comment by HyukjinKwon** [comment]
In this commit, it only deals with numbers. I removed the roundtrip in cast and It only supports comparisons among other numeric types except `Decimal` and between `Decimal` and `Decimal`  

Otherwise it considers incompatible. e.g. (between `Decimal` and other types except `Decimal`).

**Comment by HyukjinKwon** [comment]
@liancheng Would this casting check be unsafe?
I came across Parquet downcasting check with the actual value 
```java
  public static int checkedCast(long value) {
    int valueI = (int) value;
    if (valueI != value) {
      throw new IllegalArgumentException(String.format("Overflow casting %d to an int", value));
    }
    return valueI;
  }
```

and I see the use of `null` from `eval()` in other codes in Spark.

I would like to close this PR, If this approach is inappropriate for other reasons.

**Comment by davies** [comment]
From the above discussion, we can see that it's easy to get wrong, I also +1 for close this.

**Pull request closed without merging**
