### PR TITLE
[SPARK-14557][SQL] Reading textfile (created though CTAS) doesn't work

### PR DESCRIPTION
**Pull request by kasjain**
## What changes were proposed in this pull request?

These changes fix the below broken functionality and does a small performance improvement. 

1) Reading the CSV table (created through CTAS query) doesn't work when the pathFilter is provided.
A bug in HadoopFileReader. Currently, when the pathFilter is provided, it passes the list of filtered files to the "setInputPaths" which wrongly sets the string of incorrectly escaped comma separated files in an array-sequence of size one. This should have been a sequence of size equal to the number of files obtained after filtering. Hence the exception mentioned in the bug. 
------ FileInputFormat.setInputPaths(jobConf, Seq[Path](new Path%28path%29): _*)

2) Secondly, in this flow,  filtering is triggered twice for each file. Once in hadoopTableReader.applyFilterIfApplicable and then again in FileInputFormat.singleThreadedListStatus.  This is costly and redundant. 

To solve both the issues above, we can just pass the directory path itself even when the pathFilter is enabled.
## How was this patch tested?

Integration tests, manual tests

### CODE REVIEW

**Comment by andrewor14** [comment]
ok to test

**Comment by andrewor14** [comment]
@liancheng @yhuai?

**Comment by saucam** [comment]
I think we can eliminate applyFilterIfNeeded method as well.

**Comment by kasjain** [comment]
Can any of the admin verify the above fix?

**Comment by kasjain** [comment]
Resolved the merge conflicts for easy merging

**Comment by rxin** [comment]
cc @marmbrus

**Comment by kasjain** [comment]
Resolved the merge conflicts for easy merging

**Comment by marmbrus** [comment]
Is it possible to write unit tests for this?

**Comment by marmbrus** [comment]
ok to test

**Comment by kasjain** [comment]
Sure. Let me add the CTAS query in the test suite

**Comment by gatorsmile** [comment]
@kasjain Could you add a test case? Does it still fail in the latest master?

**Comment by gatorsmile** [comment]
We are closing it due to inactivity. please do reopen if you want to push it forward. Thanks!

**Pull request closed without merging**
