### PR TITLE
[SPARK-33129][BUILD][DOCS] Updating the build/sbt references to test-only with testOnly for SBT 1.3.x

### PR DESCRIPTION
**Pull request by ScrapCodes**
### What changes were proposed in this pull request?

test-only - > testOnly in docs across the project.

### Why are the changes needed?

Since the sbt version is updated, the older way or running i.e. `test-only` is no longer valid.

### Does this PR introduce _any_ user-facing change?

docs update.

### How was this patch tested?

Manually.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
As a reminder, we'll have to update https://spark.apache.org/developer-tools.html too.

**Comment by ScrapCodes** [comment]
> As a reminder, we'll have to update https://spark.apache.org/developer-tools.html too. 
@HyukjinKwon I did a quick pass. this doc looks good. Are you referring to something specific.

**Comment by HyukjinKwon** [comment]
I meant this :-)

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @ScrapCodes and @HyukjinKwon .
Ya. Website update is needed too in `spark-website` repo.
Merged to master.

**Pull request closed without merging**
