### PR TITLE
[MINOR][SS][DOCS] Update doc for streaming deduplication

### PR DESCRIPTION
**Pull request by viirya**
### What changes were proposed in this pull request?

This patch fixes an error about streaming dedupliaction is Structured Streaming, and also updates an item about unsupported operation.

### Why are the changes needed?

Update the user document.

### Does this PR introduce _any_ user-facing change?

No. It's a doc only change.

### How was this patch tested?

Doc only change.

### CODE REVIEW

**Comment by viirya** [comment]
Today I looked for streaming deduplication in the document for customer question, and noticed an error. Also took the chance to add an item of unsupported operation.

**Comment by viirya** [comment]
cc @HeartSaVioR @xuanyuanking

**Review by xuanyuanking — APPROVED** [review]
LGTM

**Review by HyukjinKwon — APPROVED** [review]

**Comment by viirya** [comment]
Thanks @xuanyuanking @HyukjinKwon !

**Comment by viirya** [comment]
Merging to master/3.2/3.1.

**Pull request closed without merging**
