### PR TITLE
[SPARK-25926][CORE] Move config entries in core module to internal.config.

### PR DESCRIPTION
**Pull request by ueshin**
## What changes were proposed in this pull request?

Currently definitions of config entries in `core` module are in several files separately. We should move them into `internal/config` to be easy to manage.

## How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by ueshin** [comment]
cc @jiangxb1987 @cloud-fan @gatorsmile

**Comment by gatorsmile** [comment]
Keeping them in separate source files is also fine to me. I think we should put them in the same package.

**Comment by ueshin** [comment]
Jenkins, retest this please.

**Comment by cloud-fan** [comment]
LGTM

**Comment by cloud-fan** [comment]
retest this please

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Pull request closed without merging**
