### PR TITLE
[SPARK-32594][SQL][FOLLOWUP][test-hadoop2.7][test-hive1.2] Override `get()` and use Julian days in `DaysWritable`

### PR DESCRIPTION
**Pull request by MaxGekk**
### What changes were proposed in this pull request?
Override `def get: Date` in `DaysWritable` use the `daysToMillis(int d)` from the parent class `DateWritable` instead of `long daysToMillis(int d, boolean doesTimeMatter)`.

### Why are the changes needed?
It fixes failures of `HiveSerDeReadWriteSuite` with the profile `hive-1.2`. In that case, the parent class `DateWritable` has different implementation before the commit to Hive https://github.com/apache/hive/commit/da3ed68eda10533f3c50aae19731ac6d059cda87. In particular, `get()` calls `new Date(daysToMillis(daysSinceEpoch))` instead of overrided `def get(doesTimeMatter: Boolean): Date` in the child class. The `get()` method returns wrong result `1970-01-01` because it uses not updated `daysSinceEpoch`.

### Does this PR introduce _any_ user-facing change?
Yes.

### How was this patch tested?
By running the test suite `HiveSerDeReadWriteSuite`:
```
$ build/sbt -Phive-1.2 -Phadoop-2.7 "test:testOnly org.apache.spark.sql.hive.execution.HiveSerDeReadWriteSuite"
```
and 
```
$ build/sbt -Phive-2.3 -Phadoop-2.7 "test:testOnly org.apache.spark.sql.hive.execution.HiveSerDeReadWriteSuite"
```

### CODE REVIEW

**Review by viirya — APPROVED** [review]

**Comment by viirya** [comment]
Github Actions was passed. `org.apache.spark.sql.hive.orc.HiveOrcHadoopFsRelationSuite` is another known failure with hive-1.2 profile.

**Comment by viirya** [comment]
Thanks @MaxGekk. Merging this to master.

**Comment by viirya** [comment]
Verified locally this fixed the test in branch-3.0 too.

**Comment by maropu** [comment]
late LGTM. Thanks for the fix, @MaxGekk !

**Comment by dongjoon-hyun** [comment]
Thank you, @MaxGekk and all!

**Pull request closed without merging**
