### PR TITLE
[SPARK-42668][SS] Catch exception while trying to close compressed stream in HDFSStateStoreProvider abort

### PR DESCRIPTION
**Pull request by anishshri-db**
### What changes were proposed in this pull request?
We have seen some cases where the task exits as cancelled/failed which triggers the abort in the task completion listener for HDFSStateStoreProvider. As part of this, we cancel the backing stream and close the compressed stream. However, different stores such as Azure blob store could throw exceptions which are not caught in the current path, leading to job failures. This change proposes to fix this issue by catching all non fatal exceptions thrown by cancel/close.

### Why are the changes needed?
Changes are required to avoid job failures due to exceptions thrown by output stream handlers on abort with the HDFSStateStoreProvider.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Modified a test and simulated a NPE in the abort path and verified that the task and thereby the job fails before this change.
After the change, the test passes fine.

### CODE REVIEW

**Comment by anishshri-db** [comment]
@HeartSaVioR - please take a look. Thx

**Review by HeartSaVioR — APPROVED** [review]
+1

**Comment by anishshri-db** [comment]
> Mind retriggering the build, please? Probably simplest way to do is pushing an empty commit. You can retrigger the build in your fork but it won't be reflected here.

Sure done

**Comment by HeartSaVioR** [comment]
It's taking lot much longer than usual. I've just pushed in my repo as well. Let's see the result.
https://github.com/HeartSaVioR/spark/actions/runs/4341254564/jobs/7580632902

**Comment by HeartSaVioR** [comment]
https://github.com/anishshri-db/spark/actions/runs/4339563807/jobs/7577302766

Here it failed only with [Run / Build modules: sql - other tests](https://github.com/anishshri-db/spark/actions/runs/4339563807/jobs/7577290837#logs)

https://github.com/HeartSaVioR/spark/actions/runs/4341254564/jobs/7580668669

Here [Run / Build modules: sql - other tests](https://github.com/HeartSaVioR/spark/actions/runs/4341254564/jobs/7580648546) succeeded.

**Comment by HeartSaVioR** [comment]
Thanks! Merging to master.

**Pull request closed without merging**
