### PR TITLE
[SPARK-19616][SparkR]:weightCol and aggregationDepth should be improved for some SparkR APIs 

### PR DESCRIPTION
**Pull request by wangmiao1981**
## What changes were proposed in this pull request?

This is a follow-up PR of #16800 

When doing SPARK-19456, we found that "" should be consider a NULL column name and should not be set. aggregationDepth should be exposed as an expert parameter.

## How was this patch tested?
Existing tests.

### CODE REVIEW

**Comment by wangmiao1981** [comment]
cc @felixcheung

**Comment by felixcheung** [comment]
could you add some tests (I don't think we need one for each) that the weight col is set properly?

**Comment by wangmiao1981** [comment]
I will add tests. Now I am looking for dataset other than iris to be used in the document.

**Comment by wangmiao1981** [comment]
I add a test of weightCol for spark.logit.

**Comment by wangmiao1981** [comment]
@felixcheung I have made suggested changes. Thanks!

**Comment by felixcheung** [comment]
merged to master

**Pull request closed without merging**
