### PR TITLE
[SPARK-21444] Be more defensive when removing broadcasts in MapOutputTracker

### PR DESCRIPTION
**Pull request by JoshRosen**
## What changes were proposed in this pull request?

In SPARK-21444, @sitalkedia reported an issue where the `Broadcast.destroy()` call in `MapOutputTracker`'s `ShuffleStatus.invalidateSerializedMapOutputStatusCache()` was failing with an `IOException`, causing the DAGScheduler to crash and bring down the entire driver.

This is a bug introduced by #17955. In the old code, we removed a broadcast variable by calling `BroadcastManager.unbroadcast` with `blocking=false`, but the new code simply calls `Broadcast.destroy()` which is capable of failing with an IOException in case certain blocking RPCs time out.

The fix implemented here is to replace this with a call to `destroy(blocking = false)` and to wrap the entire operation in `Utils.tryLogNonFatalError`.

## How was this patch tested?

I haven't written regression tests for this because it's really hard to inject mocks to simulate RPC failures here. Instead, this class of issue is probably best uncovered with more generalized error injection / network unreliability / fuzz testing tools.

### CODE REVIEW

**Comment by sameeragarwal** [comment]
cc @jiangxb1987

**Comment by sitalkedia** [comment]
@JoshRosen - Thanks for the lightning fast response. The change looks reasonable to me.

**Comment by cloud-fan** [comment]
LGTM

**Review by jiangxb1987 — APPROVED** [review]
LGTM

**Comment by JoshRosen** [comment]
Merged to master. Thanks for the quick reviews.

**Pull request closed without merging**
