### PR TITLE
[SPARK-36621][PYTHON][DOCS] Add Apache license headers to Pandas API on Spark documents

### PR DESCRIPTION
**Pull request by yoda-mon**
### What changes were proposed in this pull request?

 Apache license headers to Pandas API on Spark documents.

### Why are the changes needed?

Pandas API on Spark document sources do not have license headers, while the other docs have.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

`make html`

### CODE REVIEW

**Comment by sarutak** [comment]
ok to test.

**Comment by sarutak** [comment]
LGTM

cc: @HyukjinKwon

**Comment by HyukjinKwon** [comment]
Thanks. Are they all .rst files of missing headers?

**Comment by yoda-mon** [comment]
@HyukjinKwon 
I checked around another directories, and now I found that files under 
https://github.com/apache/spark/tree/master/python/docs/source/reference/pyspark.pandas
miss the header too.
Could I follow up on this PR ?

**Comment by sarutak** [comment]
@yoda-mon I think it's better to do within this PR.

**Comment by yoda-mon** [comment]
@HyukjinKwon Thank you for the title change. I checked around the files again and add the license headers to `reference/pyspark.pandas` .

**Review by HyukjinKwon — APPROVED** [review]

**Review by itholic — APPROVED** [review]
Thanks for adding this!

**Comment by HyukjinKwon** [comment]
Merged to master and branch-3.2.

**Comment by sarutak** [comment]
Hey, under `python/docs/`, all the `rst` files seem to have the license headers but `Makefile`, `make.bat` and `make2.bat` don't.
We should add the headers to them too right?

**Comment by yoda-mon** [comment]
Thank you, I'd like to add to them.  May I create followup PR ?

**Comment by sarutak** [comment]
This PR is about documents for Pandas API on Spark so I think it's better to have a separate PR and JIRA if we need to add license headers to those files.

**Comment by HyukjinKwon** [comment]
Oh thanks for pointing that out!

**Comment by yoda-mon** [comment]
I opend new PR https://github.com/apache/spark/pull/33979# .

**Pull request closed without merging**
