### PR TITLE
[SPARK-20817][core] Fix to return "Unknown processor" on ppc and 390 platforms by Benchmark.getProcessorName() 

### PR DESCRIPTION
**Pull request by kiszk**
## What changes were proposed in this pull request?

This PR fixes that `Benchmark.getProcessorName()` returns `Unknown processor` string on ppc and 390 Linux platforms.

After applying this PR, `Benchmark.getProcessorName()` on two Linux platforms return the following strings:

ppc64le:
```
POWER8E (raw), altivec supported @ 3690.000000MHz
```

s390x:
```
IBM/S390, identification = 01AFF7,  machine = 2964
```

## How was this patch tested?

Manually tested on ppc64le and s390x Linux platforms

### CODE REVIEW

**Review by srowen — APPROVED** [review]

**Comment by kiszk** [comment]
ping @rxin

**Comment by srowen** [comment]
Does it matter that the format of the output isn't quite in the same format - is it just used for display?

**Comment by kiszk** [comment]
It is due to differences among CPU architectures. Here are original outputs of `/proc/info`
It is used to identify CPU architecture and its model.

**POWER**
```
> cat /proc/cpuinfo 

processor	: 0
cpu		: POWER8E (raw), altivec supported
clock		: 3690.000000MHz
revision	: 2.1 (pvr 004b 0201)

processor	: 1
cpu		: POWER8E (raw), altivec supported
clock		: 3690.000000MHz
revision	: 2.1 (pvr 004b 0201)

processor	: 2
cpu		: POWER8E (raw), altivec supported
clock		: 3690.000000MHz
revision	: 2.1 (pvr 004b 0201)

...
processor	: 158
cpu		: POWER8E (raw), altivec supported
clock		: 3690.000000MHz
revision	: 2.1 (pvr 004b 0201)

processor	: 159
cpu		: POWER8E (raw), altivec supported
clock		: 3690.000000MHz
revision	: 2.1 (pvr 004b 0201)

timebase	: 512000000
platform	: PowerNV
model		: 8247-42L
machine		: PowerNV 8247-42L
firmware	: OPAL v3
```

**S390**
```
> cat /proc/cpuinfo 
vendor_id       : IBM/S390
# processors    : 32
bogomips per cpu: 20325.00
features	: esan3 zarch stfle msa ldisp eimm dfp edat etf3eh highgprs te vx 
cache0          : level=1 type=Data scope=Private size=128K line_size=256 associativity=8
cache1          : level=1 type=Instruction scope=Private size=96K line_size=256 associativity=6
cache2          : level=2 type=Data scope=Private size=2048K line_size=256 associativity=8
cache3          : level=2 type=Instruction scope=Private size=2048K line_size=256 associativity=8
cache4          : level=3 type=Unified scope=Shared size=65536K line_size=256 associativity=16
cache5          : level=4 type=Unified scope=Shared size=491520K line_size=256 associativity=30
processor 0: version = 00,  identification = 01AFF7,  machine = 2964
processor 1: version = 00,  identification = 01AFF7,  machine = 2964
processor 2: version = 00,  identification = 01AFF7,  machine = 2964
processor 3: version = 00,  identification = 01AFF7,  machine = 2964
processor 4: version = 00,  identification = 01AFF7,  machine = 2964
processor 5: version = 00,  identification = 01AFF7,  machine = 2964
processor 6: version = 00,  identification = 01AFF7,  machine = 2964
processor 7: version = 00,  identification = 01AFF7,  machine = 2964
processor 8: version = 00,  identification = 01AFF7,  machine = 2964
processor 9: version = 00,  identification = 01AFF7,  machine = 2964
processor 10: version = 00,  identification = 01AFF7,  machine = 2964
processor 11: version = 00,  identification = 01AFF7,  machine = 2964
processor 12: version = 00,  identification = 01AFF7,  machine = 2964
processor 13: version = 00,  identification = 01AFF7,  machine = 2964
processor 14: version = 00,  identification = 01AFF7,  machine = 2964
processor 15: version = 00,  identification = 01AFF7,  machine = 2964
processor 16: version = 00,  identification = 01AFF7,  machine = 2964
processor 17: version = 00,  identification = 01AFF7,  machine = 2964
processor 18: version = 00,  identification = 01AFF7,  machine = 2964
processor 19: version = 00,  identification = 01AFF7,  machine = 2964
processor 20: version = 00,  identification = 01AFF7,  machine = 2964
processor 21: version = 00,  identification = 01AFF7,  machine = 2964
processor 22: version = 00,  identification = 01AFF7,  machine = 2964
processor 23: version = 00,  identification = 01AFF7,  machine = 2964
processor 24: version = 00,  identification = 01AFF7,  machine = 2964
processor 25: version = 00,  identification = 01AFF7,  machine = 2964
processor 26: version = 00,  identification = 01AFF7,  machine = 2964
processor 27: version = 00,  identification = 01AFF7,  machine = 2964
processor 28: version = 00,  identification = 01AFF7,  machine = 2964
processor 29: version = 00,  identification = 01AFF7,  machine = 2964
processor 30: version = 00,  identification = 01AFF7,  machine = 2964
processor 31: version = 00,  identification = 01AFF7,  machine = 2964
```

**Comment by srowen** [comment]
Yeah I get that, but does it cause a problem? it won't if it's just for display, but that's what I'm asking.

**Comment by rxin** [comment]
Does this really matter? I'd rather not complicate the actual code for it to display properly in some niche hardware that very few people use.

**Comment by jiangxb1987** [comment]
@srowen @rxin  Do we still want this？

**Comment by srowen** [comment]
@kiszk unless you want to make the output of this function consistent, I'd say I'm not clear that this is a good change

**Comment by kiszk** [comment]
@srowen What do you mean "consistent"? Is it good to use a consistent format "processor identification information @ clock"?
This PR make outputs of x86_64 and ppc64le similar. I could output "IBM/S390, identification = 01AFF7,  machine = 2964 @ unknown clock" for s390x.

Any other great ideas are appreciated.

**Comment by srowen** [comment]
For example, S390 appears to output "cpu, machine", not "cpu @ clock". If this is actually used by code somewhere it needs to be consistent right? if it's just for display, it's a nice-to-have, but still, seems nicer to output similar strings?

**Comment by kiszk** [comment]
I see. I will try to use "cpu @ clock" format.

**Comment by rxin** [comment]
Please let's not waste more time here. I don't think the gain is worth the effort required (or even the discussions here).

**Pull request closed without merging**
