### PR TITLE
[SPARK-31664][CORE][YARN] Fix a race when YARN scheduler shutdown which leads to uncaught SparkException

### PR DESCRIPTION
**Pull request by baohe-zhang**
### What changes were proposed in this pull request?
Right now the communication mechanism between executor and driver when launching executor is:

1. executor backend sends "RegisterExecutor" to the driver backend.
2. the driver backend replies "true".
3. executor backend instantiates executor once it receives "true" from driver backend.
4. after the executor is instantiated, the executor backend sends "LaunchedExecutor"(introduced in PR#25964) to the driver backend.
5. the driver backend makes offers for executor when received "LaunchedExecutor".

A race can occur in steps 3 and 4. If the driver backend is stopped(hence driver endpoint removed in dispatcher) during step 3, in step 4, when executor backend tries to send "LaunchedExecutor" to driver backend, RPC dispatcher will throw an uncaught SparkException for "Could not find CoarseGrainedScheduler".  These exception logs are verbose and somewhat misleading.

This PR is trying to fix this issue through these changes:
When the CoarseGrainedSchedulerBackend#stop() is called:

- A stopping boolean variable is set to true.
- driverEndpoint will not be stopped at this time. (dispatcher will stop it at the end)

And when the stopping is set to true, the driver backend will:

- replies sendFailure to executor backend when receives "RegisterExecutor".
- replies "StopExecutor" to executor backend (or "RemoveExecutor" to self) when receives "LaunchedExecutor"

### Why are the changes needed?
There is a race between executor backend and scheduler backend.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Re-run with the same command in a YARN cluster multiple times and didn't see the issue happen again.

### CODE REVIEW

**Comment by baohe-zhang** [comment]
cc @vanzin

**Comment by jiangxb1987** [comment]
Even with your patch, the uncaught SparkException would still appear, if the executor is registered, but then the driver shutdown, just before the executor send out LaunchedExecutor message, right?

**Comment by jiangxb1987** [comment]
I really think we should handle the uncaught exception at the Executor side.

**Comment by baohe-zhang** [comment]
With this patch, driverEndpoint is not stopped when CoarseGrainedSchedulerBackend#stop() is called. It is stopped when the dispatcher stop is called. So I think in general executor backends will always exit before the driver backend exits, and the driver backend will exit at the very end of the spark app. I tested many times and haven't seen an uncaught SparkException happen.

**Comment by baohe-zhang** [comment]
The driver endpoint is stopped when rpcEnv.shutdown() is called. So the scenario that rpcEnv.dispatcher is alive and driverEndpoint is stopped can never happen (dispatcher.stop will be set to true before the driverEndpoint removed). Hence that uncaught SparkException can never happen.

**Pull request closed without merging**
