### PR TITLE
[SPARK-25127] DataSourceV2: Remove SupportsPushDownCatalystFilters

### PR DESCRIPTION
**Pull request by rxin**
## What changes were proposed in this pull request?
They depend on internal Expression APIs. Let's see how far we can get without it.

## How was this patch tested?
Just some code removal. There's no existing tests as far as I can tell so it's easy to remove.

### CODE REVIEW

**Comment by rxin** [comment]
cc @rdblue @cloud-fan @gatorsmile

**Comment by rdblue** [comment]
+1 when tests pass. Convenient that there weren't any internal implementations using this.

**Comment by dongjoon-hyun** [comment]
+1, LGTM.

**Comment by cloud-fan** [comment]
LGTM, merging to master!

**Comment by HyukjinKwon** [comment]
+1

**Pull request closed without merging**
