### PR TITLE
[SPARK-27138][TESTS][KAFKA] Remove AdminUtils calls (fixes deprecation)

### PR DESCRIPTION
**Pull request by DylanGuedes**
## What changes were proposed in this pull request?

To change calls to AdminUtils, currently used to create and delete topics in Kafka tests. With this change, it will rely on adminClient, the recommended way from now on.

## How was this patch tested?
I ran all unit tests and they are fine. Since it is already good tested, I thought that changes in the API wouldn't require new tests, as long as the current tests are working fine.

### CODE REVIEW

**Comment by vanzin** [comment]
ok to test

**Review by srowen — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
cc @HeartSaVioR

**Comment by HeartSaVioR** [comment]
I don't know whether it's possible to replace all the ZK related things, but I'm a kind of feel uncomfortable since we just replace some paths which leverages ZK and remain other things. I'd like to kindly ask to investigate whether we call fully replace things dealing with ZK directly, but that may be non-trivial so that would be completely OK if we only want to address a part of.

LGTM given the tests in Kafka module passed. 

Btw, just for recording, `kafka.zk.AdminZkClient` is direct successor of `AdminUtils`, so even if we observe something (including intermittent failure) after the patch, we can move to `kafka.zk.AdminZkClient` then.

**Comment by DylanGuedes** [comment]
@HeartSaVioR That makes sense, I'll start to investigate other deprecated calls (such as `ZkUtils`) then.

Btw, is good to keep in mind that this way, reverting only this commit will replace only calls to AdminUtils, which can be desired in the future (i.e: maybe the Kafka team will only change one of the APIs, so you guys can atomically replace/revert only one of these calls).

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
