### PR TITLE
[SPARK-27125][SQL][Test]Add test suite for sql execution page

### PR DESCRIPTION
**Pull request by shahidki31**
## What changes were proposed in this pull request?
Added test suite for AllExecutionsPage class. Checked the scenarios for SPARK-27019 and SPARK-27075.

## How was this patch tested?
Added UT, manually tested

### CODE REVIEW

**Comment by shahidki31** [comment]
Ok to test

**Comment by shahidki31** [comment]
cc @vanzin @srowen Kindly review

**Review by srowen — APPROVED** [review]

**Review by HyukjinKwon — APPROVED** [review]

**Comment by srowen** [comment]
Merged to master

**Comment by shahidki31** [comment]
Thanks @srowen @HyukjinKwon

**Pull request closed without merging**
