### PR TITLE
[SPARK-44602][SQL][CONNECT][PS] Make `WidenSetOperationTypes` retain the `Plan_ID_TAG`

### PR DESCRIPTION
**Pull request by zhengruifeng**
### What changes were proposed in this pull request?
Make Analyzer rule `WidenSetOperationTypes` retains the `Plan_ID_TAG`

### Why are the changes needed?
for functionality parity

### Does this PR introduce _any_ user-facing change?
yes, APIs enabled:

1. `frame.append`
2. `series.argsort`
3. `ps.concat`

### How was this patch tested?
enabled UTs

### CODE REVIEW

**Comment by zhengruifeng** [comment]
cc @HyukjinKwon @cloud-fan @itholic

**Review by cloud-fan — APPROVED** [review]

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master and branch-3.5.

**Comment by HyukjinKwon** [comment]
Should we merge this to 3.5 too? It depends on https://github.com/apache/spark/pull/42086

**Comment by zhengruifeng** [comment]
cc @itholic should we backport this PR and https://github.com/apache/spark/pull/42086 to 3.5?

If so, would you mind helping backporting them?

**Comment by itholic** [comment]
Yes, it would be great to have this one for 3.5. Let me create a backport PRs soon.

**Comment by itholic** [comment]
Made a backport PR for both https://github.com/apache/spark/pull/42086 and this : https://github.com/apache/spark/pull/42252

**Pull request closed without merging**
