### PR TITLE
[SPARK-28938][K8S] Move to supported OpenJDK docker image for Kubernetes

### PR DESCRIPTION
**Pull request by viirya**
### What changes were proposed in this pull request?

The current docker image used by Kubernetes is `openjdk:8-alpine`. It was not supported and  was removed with the commit https://github.com/docker-library/openjdk/commit/3eb0351b208d739fac35345c85e3c6237c2114ec#diff-f95ffa3d1377774732c33f7b8368e099.

This PR proposes to move to a supported docker image.

### Why are the changes needed?

I think there are at least two reasons:

1. According to the commit, Alpine/musl is not officially supported by the OpenJDK project.
2. As no more OpenJDK 8 Alpine images, new JDK updates including security fixes
, are not applied to it. See below:

```
docker run -it --rm openjdk:8-alpine java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (IcedTea 3.12.0) (Alpine 8.212.04-r0)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
```
```
docker run -it --rm openjdk:8-jdk-slim java -version
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)
```

### Does this PR introduce any user-facing change?

Yes. This changes the base docker image of Spark.

### How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Thank you for making a PR, @viirya . `K8s Integration test` seems to be not triggered here. Did you test the K8s IT locally?

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by viirya** [comment]
Hmm, I was thinking to run the integration test on Jenkins. At least I remember I saw it in previous PRs.

**Comment by dongjoon-hyun** [comment]
Yes. It's weird to me, too.

**Comment by dongjoon-hyun** [comment]
I checked the Jenkins. And, found that it's running here.
- https://amplab.cs.berkeley.edu/jenkins/view/spark%20k8s%20builds/job/SparkPullRequestBuilder-K8s/16803/console

**Comment by viirya** [comment]
oh, thanks. @dongjoon-hyun. Seems Jenkins also posted the comment of Kubernetes integration test too.

**Comment by dongjoon-hyun** [comment]
Let's see the result~ 😄

**Comment by dongjoon-hyun** [comment]
Could you check the K8s IT failure?

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
Please fix `python/Docker` file, too. There might be more dependency images in `R`.
And, could you run K8s IT locally before updating this PR please?

**Comment by dongjoon-hyun** [comment]
There is `R/Dockerfile`, @viirya .

**Comment by viirya** [comment]
@dongjoon-hyun Thanks. Updated Python and R Docker files. Let's see K8s IT result with latest change. If it has failure, I will change to a local environment which can run K8s IT. (current local env cannot)

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
It seems that there are two failures.
- R (Please see `pandoc` error in Jenkins log. It might be irrelevant to this one.)
- Python (I hit this locally.)
```
ensurepip is disabled in Debian/Ubuntu for the system python.

Python modules For the system python are usually handled by dpkg and apt-get.

    apt-get install python-<module name>

Install the python-pip package to use pip itself.  Using pip together
with the system python might have unexpected results for any system installed
module, so use it on your own risk, or make sure to only use it in virtual
environments.

The command '/bin/sh -c apt install -y python &&     apt install -y python3 &&     python -m ensurepip &&     python3 -m ensurepip &&     rm -r /usr/lib/python*/ensurepip &&     pip install --upgrade pip setuptools &&     rm -r /root/.cache && rm -rf /var/cache/apt/*' returned a non-zero code: 1
Failed to build PySpark Docker image, please refer to Docker build output for details.
```

**Comment by viirya** [comment]
About R (Please see pandoc error in Jenkins log. It might be irrelevant to this one.), I think it is happened before K8s IT stuff, according to the log.

There is another ongoing K8s IT build. Let's see the latest result and do necessary change if it needs.

**Comment by viirya** [comment]
And yes, ensurepip is a problem.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @viirya .
Merged to master.

**Comment by dongjoon-hyun** [comment]
Could you make a backport to `branch-2.4`, @viirya ?

**Comment by viirya** [comment]
ok.

**Pull request closed without merging**
