### PR TITLE
[SPARK-10300] [build] [tests] Add support for test tags in run-tests.py.

### PR DESCRIPTION
**Pull request by vanzin**
This change does two things:
- tag a few tests and adds the mechanism in the build to be able to disable those tags,
  both in maven and sbt, for both junit and scalatest suites.
- add some logic to run-tests.py to disable some tags depending on what files have
  changed; that's used to disable expensive tests when a module hasn't explicitly
  been changed, to speed up testing for changes that don't directly affect those
  modules.

### CODE REVIEW

**Comment by vanzin** [comment]
retest this please

**Comment by vanzin** [comment]
retest this please

**Comment by vanzin** [comment]
@pwendell @marmbrus what do you think of this approach? It's partly based on code that @squito wrote before to add tags for long-running tests. Main changes is that I hooked things up to `run-tests.py` to automate enabling / disabling some tags.

Note that the tests for this PR will run everything (since I'm touching files in the respective modules), but I tested locally that things are disabled properly when they should be.

**Comment by marmbrus** [comment]
The `ExtendedHiveTest` tag looks good to me.  I would consider dropping the random smoke test part of things since we have lot of SQL tests and even hive tests that will still be running, so I'm not sure its worth the complexity.  I would be okay just marking the whole test as `ExtendedHiveTest`.

Thanks for working on this!

**Comment by vanzin** [comment]
> I would be okay just marking the whole test as ExtendedHiveTest.

Easy enough (good thing I made that change in a single commit).

**Comment by marmbrus** [comment]
SQL changes LGTM.  I'll let @pwendell comment on build changes.

**Comment by vanzin** [comment]
pyspark failures, seem unrelated. in any case... retest this please

**Comment by vanzin** [comment]
Another pyspark failure (that I've seen countless times in other PRs).

**Comment by vanzin** [comment]
retest this please

**Comment by andrewor14** [comment]
@JoshRosen should look at this

**Comment by vanzin** [comment]
@JoshRosen any comments?

**Comment by vanzin** [comment]
No comments? I already got a +1 from Michael, so as far as I can tell, this is good to go.

**Comment by pwendell** [comment]
LGTM - I've modified that script recently enough to be familiar with how it works. This seems like a good approach and could be useful for us in the future.

**Comment by vanzin** [comment]
ok, merging.

**Comment by vanzin** [comment]
This seems to have caused PR tests to start failing... I'll try things locally again and revert the patch if needed.

**Comment by mengxr** [comment]
Shall we revert the PR first? It is blocking other PRs.

**Comment by vanzin** [comment]
Done.

**Comment by vanzin** [comment]
For the curious, the issue is that the junit test runners (both surefire and the sbt one) need the tag classes around or they'll throw an error, and that happens when building modules where the tag is not available. I'm thinking about a workaround that does not involve removing the junit functionality.

**Comment by JoshRosen** [comment]
Are there plans to revive this PR and attempt another merge?

**Comment by vanzin** [comment]
@JoshRosen #8775

**Pull request closed without merging**
