### PR TITLE
[SPARK-36886][PYTHON] Inline type hints for python/pyspark/sql/context.py

### PR DESCRIPTION
**Pull request by dchvn**
### What changes were proposed in this pull request?
Inline type hints for python/pyspark/sql/context.py from Inline type hints for python/pyspark/sql/context.pyi.

### Why are the changes needed?
Currently, there is type hint stub files python/pyspark/sql/context.pyi to show the expected types for functions, but we can also take advantage of static type checking within the functions by inlining the type hints.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Existing test.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
can you make Jenkins happy (https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/143902/)?

**Comment by HyukjinKwon** [comment]
I think the problem is the versions of mypy and other linter tools are different in GitHub Actions and Jenkins. we would first have to figure out to make both old and new versions happy.

**Comment by dchvn** [comment]
cc @HyukjinKwon,  can you take a look, pls?

**Comment by HyukjinKwon** [comment]
cc @xinrong-databricks @itholic @ueshin FYI

**Review by itholic — APPROVED** [review]
Seems fine to me

**Review by ueshin — APPROVED** [review]

**Comment by dchvn** [comment]
thank you!

**Pull request closed without merging**
