### PR TITLE
[SPARK-15671] performance regression CoalesceRDD.pickBin with large #…

### PR DESCRIPTION
**Pull request by tgravescs**
I was running a 15TB join job with 202000 partitions. It looks like the changes I made to CoalesceRDD in pickBin() are really slow with that large of partitions. The array filter with that many elements just takes to long.
It took about an hour for it to pickBins for all the partitions.
original change:
https://github.com/apache/spark/commit/83ee92f60345f016a390d61a82f1d924f64ddf90

Just reverting the pickBin code back to get currpreflocs fixes the issue

After reverting the pickBin code the coalesce takes about 10 seconds so for now it makes sense to revert those changes and we can look at further optimizations later.

Tested this via RDDSuite unit test and manually testing the very large job.

### CODE REVIEW

**Comment by tgravescs** [comment]
cc @davies

**Comment by davies** [comment]
LGTM.

**Comment by tgravescs** [comment]
test failure was in blacklistsuite which shouldn't have anything to do with this change. I'll kick jenkins again.

**Comment by tgravescs** [comment]
Jenkins, test this please

**Comment by davies** [comment]
Merging this into master and 2.0, thanks!

**Pull request closed without merging**
