### PR TITLE
Better host description for multi-master mesos

### PR DESCRIPTION
**Pull request by malterb**
## What changes were proposed in this pull request?

Since not having the correct zk url causes job failure, the documentation should include all parameters
## How was this patch tested?

no tests necessary

### CODE REVIEW

**Comment by andrewor14** [comment]
@elmalto please add `[Docs][Minor]` to the title.

**Comment by andrewor14** [comment]
@dragos @tnachen

**Comment by tnachen** [comment]
LGTM

**Comment by srowen** [comment]
Jenkins test this please

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
