### PR TITLE
[SQL][MINOR][TEST][3.1] Re-enable some DS v2 char/varchar test

### PR DESCRIPTION
**Pull request by cloud-fan**
### What changes were proposed in this pull request?

Some tests are skipped in branch 3.1 because some bug fixes were not backported. This PR re-enables some tests that are working fine now.

### Why are the changes needed?

enable test

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

N/A

### CODE REVIEW

**Comment by cloud-fan** [comment]
@yaooqinn @maropu

**Comment by yaooqinn** [comment]
LGTM

**Review by yaooqinn — APPROVED** [review]

**Review by maropu — APPROVED** [review]
Looks fine if the tests pass.

**Comment by yaooqinn** [comment]
BTW, add [3.1] to the pr title

**Review by dongjoon-hyun — APPROVED** [review]

**Comment by cloud-fan** [comment]
merging to 3.1!

**Pull request closed without merging**
