### PR TITLE
[SPARK-37652][SQL]Add test for optimize skewed join through union

### PR DESCRIPTION
**Pull request by mcdull-zhang**
### What changes were proposed in this pull request?

https://github.com/apache/spark/pull/34974, solved most scenarios of data skew in union.
add test for it.

### Why are the changes needed?

Added tests for the following scenarios：

<b>scenes 1</b>
```
Union
    SMJ
        ShuffleQueryStage
        ShuffleQueryStage
    SMJ
        ShuffleQueryStage
        ShuffleQueryStage
```

<b>scenes 2</b>
```
Union
    SMJ
        ShuffleQueryStage
        ShuffleQueryStage
    HashAggregate
```

<b>scenes 3: not yet supported, SMJ-3 will introduce a new shuffle, so SMJ-1 cannot be optimized</b>
```
Union
    SMJ-1
        ShuffleQueryStage
        ShuffleQueryStage
    SMJ-2
       SMJ-3
         ShuffleQueryStage
         ShuffleQueryStage
       HashAggregate
```

### Does this PR introduce any user-facing change?

No

### How was this patch tested?

Pass the added test

### CODE REVIEW

**Comment by mcdull-zhang** [comment]
cc @cloud-fan

**Comment by zhengruifeng** [comment]
I think https://github.com/apache/spark/pull/34974 can handle this case.

**Comment by cloud-fan** [comment]
Yea, I think this is already supported.

**Comment by ulysses-you** [comment]
Although we have supported it, I think it's still good to add some test. @mcdull-zhang can you rebase this PR only for the test ?

**Comment by mcdull-zhang** [comment]
@ulysses-you  @cloud-fan  Please take a look, does the test code make sense? If it doesn't make sense, I'll turn off the pr.

**Review by cloud-fan — APPROVED** [review]

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Pull request closed without merging**
