### PR TITLE
[SPARK-28988][SQL][TESTS] Fix invalid tests in CliSuite

### PR DESCRIPTION
**Pull request by LantaoJin**
### What changes were proposed in this pull request?

https://github.com/apache/spark/blob/1f056eb313de792a279c3c7c21b5bccd652c631b/sql/hive-thriftserver/src/test/scala/org/apache/spark/sql/hive/thriftserver/CliSuite.scala#L221 is not strong enough. It will success if class not found.

https://github.com/apache/spark/blob/1f056eb313de792a279c3c7c21b5bccd652c631b/sql/hive-thriftserver/src/test/scala/org/apache/spark/sql/hive/thriftserver/CliSuite.scala#L305 is also incorrect. Whatever the right side value is, it always succeeds.

### Why are the changes needed?
Unit tests should failed if the class not found.

### Does this PR introduce any user-facing change?
No

### How was this patch tested?
Exist UTs

### CODE REVIEW

**Comment by LantaoJin** [comment]
cc @wangyum @HyukjinKwon

**Comment by wangyum** [comment]
ok to test

**Review by wangyum — COMMENTED** [review]
This test also need to fix: https://github.com/apache/spark/pull/25724/files#diff-f3b00321aca176ae6c1aa38ba034141eR305

**Review by srowen — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
