### PR TITLE
[SPARK-9854] [SQL] RuleExecutor.timeMap should be thread-safe

### PR DESCRIPTION
**Pull request by JoshRosen**
`RuleExecutor.timeMap` is currently a non-thread-safe mutable HashMap; this can lead to infinite loops if multiple threads are concurrently modifying the map.  I believe that this is responsible for some hangs that I've observed in HiveQuerySuite.

This patch addresses this by using a Guava `AtomicLongMap`.

### CODE REVIEW

**Comment by marmbrus** [comment]
LGTM

**Comment by JoshRosen** [comment]
SparkQA is going to be unable to post build statuses here due to a temporary Jenkins configuration break, but we can manually check the outcome at https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/40559/.  If this passes tests then I'm going to merge it immediately since I think this might cut down on a lot of the timeout-related flakiness that we've been seeing.

**Comment by JoshRosen** [comment]
Jenkins, retest this please.

**Comment by JoshRosen** [comment]
Jenkins, retest this please.

**Comment by JoshRosen** [comment]
Jenkins, retest this please.

**Comment by JoshRosen** [comment]
I'm going to merge this to master and branch-1.5.

**Pull request closed without merging**
