### PR TITLE
[SPARK-17262][SQL] Fixed missing closing bracket spark/sql/DataFrameSuite.scala

### PR DESCRIPTION
**Pull request by elviento**
## What changes were proposed in this pull request?

Fixed missing closing bracket in branch-2.0 line:1704 of DataFrameSuite.scala which was found during ./dev/make-distribution.sh

/spark/sql/core/target/scala-2.11/test-classes...
/spark/sql/core/src/test/scala/org/apache/spark/sql/DataFrameSuite.scala:1704: Missing closing brace `}' assumed here
[error] }
[error] ^
[error] one error found
[error] Compile failed at Mar 11, 2017 2:36:12 PM [0.610s]

## How was this patch tested?

Tested:
$SPARK_SRC/spark/sql/core/target/scala-2.11/test-classes...

Successful Build:
$SPARK_SRC/dev/make-distribution.sh --tgz -Psparkr -Phadoop-2.7 -Phive -Phive-thriftserver -Pyarn

### CODE REVIEW

**Comment by gatorsmile** [comment]
Can you close it please?

**Comment by srowen** [comment]
@elviento close this

**Comment by elviento** [comment]
it merges into branch-2.0 - added missing bracket in DataFrameSuite.scala line 1704.

**Comment by srowen** [comment]
@elviento this pull request is completely wrong. Close it

**Comment by elviento** [comment]
closed

**Pull request closed without merging**
