### PR TITLE
[SPARK-22993][ML] Clarify HasCheckpointInterval param doc

### PR DESCRIPTION
**Pull request by sethah**
## What changes were proposed in this pull request?

Add a note to the `HasCheckpointInterval` parameter doc that clarifies that this setting is ignored when no checkpoint directory has been set on the spark context.

## How was this patch tested?

No tests necessary, just a doc update.

### CODE REVIEW

**Comment by sethah** [comment]
cc @srowen @holdenk The MLlib counterparts actually make mention of this, but for some reason the note never got ported over to ML package. 

The only caveat I can think of is that this doc is the same for all algos that inherit it, but a new algo could potentially not ignore it, but throw an error or manually set the checkpoint dir. For now, ALS, LDA, and GBT all use it and ignore it in the case the checkpoint dir is not set.

**Review by srowen — APPROVED** [review]

**Review by holdenk — APPROVED** [review]

**Review by felixcheung — COMMENTED** [review]
How about python and R doc?

eg.
https://github.com/apache/spark/blob/master/R/pkg/R/mllib_recommendation.R#L50
https://github.com/apache/spark/blob/master/R/pkg/R/mllib_tree.R#L163

**Comment by sethah** [comment]
Good call @felixcheung! Will update shortly.

**Comment by felixcheung** [comment]
Actually in R setCheckpointDir method is not attached to the SparkContext; I’d leave it as “not set” or “not set in the session”

https://spark.apache.org/docs/latest/api/R/setCheckpointDir.html

**Comment by sethah** [comment]
Thanks, latest commit should fix it.

**Review by felixcheung — APPROVED** [review]

**Comment by felixcheung** [comment]
merged to master/2.3

**Pull request closed without merging**
