### PR TITLE
[SPARK-10397] [PySpark] Made python SparkContext self-descriptive

### PR DESCRIPTION
**Pull request by alexrovner**

### CODE REVIEW

**Comment by rxin** [comment]
Is it too verbose to contain so much information in the normal repl string?

**Comment by alexrovner** [comment]
Its going to be hard for us to guess what info will be useful to the user when inspecting the context. This way you get a dump of it all, with on average around 10-15 lines (guessing) which is not too bad for a manual triggered inspection.

**Comment by alexrovner** [comment]
On the second thought, I can take out the pretty print from "repl" to make it more condensed. Is that what you were referring to?

**Comment by alexrovner** [comment]
pull request updated

**Pull request closed without merging**
