### PR TITLE
A minor fix, change spark.yarn.app.id to spark.app.id to enable SparkConf.getAppId

### PR DESCRIPTION
**Pull request by haiy**

### CODE REVIEW

**Comment by srowen** [comment]
@tgravescs @sarutak do you know if this is really supposed to be `spark.yarn.app.id`, separate from `spark.app.id` used everywhere else?

**Comment by srowen** [comment]
OK to test

**Comment by haiy** [comment]
Test this please.

**Comment by srowen** [comment]
Jenkins, test this please.

**Comment by sarutak** [comment]
I think, we can replace `spark.yarn.app.id` with `spark.app.id`.
`spark.yarn.app.id` is used in YARN cluster mode, and only ApplicationMaster set this property and only YarnClusterSchedulerBackend read it.
Finaly, the value of the property YarnClusterSchedulerBackend read is set to `spark.app.id` in SparkContext.

```
    _applicationId = _taskScheduler.applicationId()
    _applicationAttemptId = taskScheduler.applicationAttemptId()
    _conf.set("spark.app.id", _applicationId)
    _env.blockManager.initialize(_applicationId)
```

**Comment by tgravescs** [comment]
its seems kind of odd to set the same config via SparkContext and then also set it in ApplicationMaster.  I don't have super strong opinion on this but I prefer it the way it now (without this change) just because its more obvious what is going on and less prone to error.

**Comment by ehnalis** [comment]
I'm on the same page with @tgravescs. This would introduce some other problems, and it would be preferable to distinguish YARN's ID that way instead of checking for ID-prefixes.

**Comment by srowen** [comment]
OK @haiy unless you have a stronger reason for this change, do you mind closing this PR?

**Comment by haiy** [comment]
then how to get the yarn  app id without reading the code?

**Comment by haiy** [comment]
ok, i'll close it and thanks for your comments.

**Comment by haiy** [comment]
BTW, what's the difference between the SparkConf.getAppId and SparkContext.applicationId?When we want to get the appId through the SparkConf in yarn cluster mode, actually it will throw an excepiton,  cause this property is not set.

**Comment by haiy** [comment]
Could somone please give a little hints? @srowen , @sarutak , @tgravescs .Thanks so much.

**Comment by srowen** [comment]
I don't know myself, but that's a question for user@spark.apache.org rather than a PR. You don't need to reopen this to ask.

**Comment by haiy** [comment]
Sorry to bother, thanks so much.

**Pull request closed without merging**
