### PR TITLE
[SPARK-43842][BUILD] Upgrade `gcs-connector` to 2.2.14

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to upgrade `gcs-connector` to 2.2.14.

### Why are the changes needed?

- https://github.com/GoogleCloudDataproc/hadoop-connectors/releases/tag/v2.2.14
- https://github.com/GoogleCloudDataproc/hadoop-connectors/releases/tag/v2.2.13
- https://github.com/GoogleCloudDataproc/hadoop-connectors/releases/tag/v2.2.12

### Does this PR introduce _any_ user-facing change?

Although this is a dependency change, there is no user-facing change.

### How was this patch tested?

Pass the CIs and manual verification.

**BUILD**
```
$ dev/make-distribution.sh -Phadoop-cloud
```

**RUN**
```
$ export KEYFILE=YOUR-credentials.json
$ export EMAIL=$(jq -r '.client_email' < $KEYFILE)
$ export PRIVATE_KEY_ID=$(jq -r '.private_key_id' < $KEYFILE)
$ export PRIVATE_KEY="$(jq -r '.private_key' < $KEYFILE)"

$ bin/spark-shell \
    -c spark.hadoop.fs.gs.auth.service.account.email=$EMAIL \
    -c spark.hadoop.fs.gs.auth.service.account.private.key.id=$PRIVATE_KEY_ID \
    -c spark.hadoop.fs.gs.auth.service.account.private.key="$PRIVATE_KEY"
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 3.5.0-SNAPSHOT
      /_/

Using Scala version 2.13.8 (OpenJDK 64-Bit Server VM, Java 17.0.7)
Type in expressions to have them evaluated.
Type :help for more information.
23/05/28 14:43:31 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Spark context Web UI available at http://localhost:4040
Spark context available as 'sc' (master = local[*], app id = local-1685310212206).
Spark session available as 'spark'.

scala> spark.read.text("gs://apache-spark-bucket/README.md").count()
val res0: Long = 124

scala> spark.read.orc("examples/src/main/resources/users.orc").write.mode("overwrite").orc("gs://apache-spark-bucket/users.orc")

scala> spark.read.orc("gs://apache-spark-bucket/users.orc").show()
+------+--------------+----------------+
|  name|favorite_color|favorite_numbers|
+------+--------------+----------------+
|Alyssa|          NULL|  [3, 9, 15, 20]|
|   Ben|           red|              []|
+------+--------------+----------------+
```

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Could you review this PR too, @bjornjorgensen ? I added the manual test result in the PR description.

**Comment by bjornjorgensen** [comment]
Its ok but "This PR aims to upgrade gas-connector to 2.2.14." -> gcs-connector ;)

**Comment by dongjoon-hyun** [comment]
Nice catch. Thank you! I fixed the typo.

**Comment by bjornjorgensen** [comment]
I have never used gcs, but @michTalebzadeh you are using it? can you help us her?

**Comment by dongjoon-hyun** [comment]
Oh, never mind. I can ping other committers. Thanks.
> I have never used gcs, ...

**Comment by michTalebzadeh** [comment]
The current valid gcs-connector is gcs-connector-hadoop3-2.2.0-shaded.jar that works OK with spark 3.4.0

I tend to place it under `$SPARK_HOME/jars`

ls -l gcs*
-rwxr--r--. 1 hduser hadoop 17663298 Apr 20 09:37 gcs-connector-hadoop3-2.2.0-shaded.jar
lrwxrwxrwx. 1 hduser hadoop       38 Apr 20 09:39 gcs-connector.jar -> gcs-connector-hadoop3-2.2.0-shaded.jar
```
What is gas-connector to 2.2.14 a typo?

**Comment by michTalebzadeh** [comment]
Also check this

https://repo1.maven.org/maven2/com/google/cloud/bigdataoss/gcs-connector/

**Comment by dongjoon-hyun** [comment]
Could you review this when you have some time please, @HyukjinKwon and @LuciferYang ?

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by dongjoon-hyun** [comment]
Thank you so much, @HyukjinKwon !

**Comment by LuciferYang** [comment]
late LGTM

**Comment by dongjoon-hyun** [comment]
Thank you, @LuciferYang !

**Pull request closed without merging**
