### PR TITLE
[INFRA] Close stale PR

### PR DESCRIPTION
**Pull request by HyukjinKwon**
Closes #17422
Closes #17619
Closes #18034
Closes #18229
Closes #18268
Closes #17973
Closes #18125
Closes #18918
Closes #19274
Closes #19456
Closes #19510
Closes #19420
Closes #20090
Closes #20177
Closes #20304
Closes #20319
Closes #20543
Closes #20437
Closes #21261
Closes #21726
Closes #14653
Closes #13143
Closes #17894
Closes #19758
Closes #12951
Closes #17092
Closes #21240
Closes #16910
Closes #12904
Closes #21731
Closes #21095

Added:
Closes #19233
Closes #20100
Closes #21453
Closes #21455
Closes #18477

Added:
Closes #21812
Closes #21787

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Mostly they are proposed to be closed by
 1. author's inactivity
 2. committer's decision to close (including me)
 3. account removed
 4. PRs that are bing taken over
 5. etc.

Authors:
  - Please come and say "please take out #XXXXX". I will leave this PR open for few days. 
  - If you guys missed it, please reopen when you guys find some time. That would give more refreshes to make the progress on the proposed changes.

Contributors: please go ahead if you guys find some PRs worth taking over. Please leave a comment and open a PR.

**Comment by jiangxb1987** [comment]
I checked the listed PRs in Core module and it seems fine to close them. Also cc @gatorsmile

**Comment by 10110346** [comment]
please take out  #21079

**Comment by srowen** [comment]
I would add:

https://github.com/apache/spark/pull/19233
https://github.com/apache/spark/pull/20100

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
