### PR TITLE
[SPARK-24420][Build][FOLLOW-UP] Upgrade ASM6 APIs

### PR DESCRIPTION
**Pull request by gatorsmile**
## What changes were proposed in this pull request?
Use ASM 6 APIs after we upgrading it to ASM6.

## How was this patch tested?
N/A

### CODE REVIEW

**Comment by gatorsmile** [comment]
cc @dbtsai @srowen

**Review by felixcheung — APPROVED** [review]

**Comment by kiszk** [comment]
LGTM

**Comment by HyukjinKwon** [comment]
retest this please

**Review by srowen — APPROVED** [review]
The change just updates code to actually use ASM6 in these places? OK, pending tests.

**Comment by dbtsai** [comment]
retest this please

**Comment by dbtsai** [comment]
LGTM. @gatorsmile out of my curiosity, did you run into any issue that asm6 generates older version of bytecode defined in asm5?

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by dbtsai** [comment]
Merged into master. Thanks.

**Comment by gatorsmile** [comment]
@dbtsai Nope. I did not hit any issue. :)

**Pull request closed without merging**
