### PR TITLE
[SPARK-33527][SQL][FOLLOWUP] Fix the scala 2.13 build failure

### PR DESCRIPTION
**Pull request by sarutak**
### What changes were proposed in this pull request?

This PR fixes the Scala 2.13 build failure brought by #30479 .

### Why are the changes needed?

To pass Scala 2.13 build.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Should be done byGitHub Actions.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Thanks, @sarutak .

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM (Pending Jenkins).

**Comment by dongjoon-hyun** [comment]
cc @cloud-fan

**Comment by dongjoon-hyun** [comment]
Scala 2.13 GitHub Action passed. Merged to master.

**Comment by beliefer** [comment]
Thanks, @sarutak

**Pull request closed without merging**
