### PR TITLE
[SPARK-14914][CORE][SQL] Skip/fix some test cases on Windows due to limitation of Windows

### PR DESCRIPTION
**Pull request by HyukjinKwon**
## What changes were proposed in this pull request?

This PR proposes to fix/skip some tests failed on Windows. This PR takes over https://github.com/apache/spark/pull/12696.

**Before**
- **SparkSubmitSuite**
  
  ```
  [info] - launch simple application with spark-submit *** FAILED *** (202 milliseconds)
  [info]   java.io.IOException: Cannot run program "./bin/spark-submit" (in directory "C:\projects\spark"): CreateProcess error=2, The system cannot find the file specifie
  
  [info] - includes jars passed in through --jars *** FAILED *** (1 second, 625 milliseconds)
  [info]   java.io.IOException: Cannot run program "./bin/spark-submit" (in directory "C:\projects\spark"): CreateProcess error=2, The system cannot find the file specified
  ```
- **DiskStoreSuite**
  
  ```
  [info] - reads of memory-mapped and non memory-mapped files are equivalent *** FAILED *** (1 second, 78 milliseconds)
  [info]   diskStoreMapped.remove(blockId) was false (DiskStoreSuite.scala:41)
  ```

**After**
- **SparkSubmitSuite**
  
  ```
  [info] - launch simple application with spark-submit (578 milliseconds)
  [info] - includes jars passed in through --jars (1 second, 875 milliseconds)
  ```
- **DiskStoreSuite**
  
  ```
  [info] DiskStoreSuite:
  [info] - reads of memory-mapped and non memory-mapped files are equivalent !!! CANCELED !!! (766 milliseconds
  ```

For `CreateTableAsSelectSuite` and `FsHistoryProviderSuite`, I could not reproduce as the Java version seems higher than the one that has the bugs about `setReadable(..)` and `setWritable(...)` but as they are bugs reported clearly, it'd be sensible to skip those. We should revert the changes for both back as soon as we drop the support of Java 7.
## How was this patch tested?

Manually tested via AppVeyor.

Closes #12696

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @srowen 

BTW, now I wrote some bunch of scripts and configurations for AppVeyor so I am able to run each test on Windows. I will run the tests against this PR and post a comment just in case.

**Comment by HyukjinKwon** [comment]
So many tests seem already being failed. This PR tries to handle only the suggested changes.

Build started: [CORE] `org.apache.spark.deploy.SparkSubmitSuite` [PR-15320](https://ci.appveyor.com/project/spark-test/spark/branch/3F896DCC-A783-451C-8B2A-404DC84ECA28)

Build started: [CORE] `org.apache.spark.deploy.history.FsHistoryProviderSuite` [PR-15320](https://ci.appveyor.com/project/spark-test/spark/branch/C90834ED-50DC-404C-8272-C9F52737AE24)

Build started: [CORE] `org.apache.spark.storage.DiskStoreSuite` [PR-15320](https://ci.appveyor.com/project/spark-test/spark/branch/E5430A1C-E954-4E89-B520-71A1416A0F1F)

Build started: [SQL] `org.apache.spark.sql.sources.CreateTableAsSelectSuite` [PR-15320](https://ci.appveyor.com/project/spark-test/spark/branch/BE1FE6B9-D65F-4E8E-87FC-1F0029C3A695)

**Comment by HyukjinKwon** [comment]
Sorry for being noisy, but I am thinking of sweeping skipping the tests across Spark and then fixing them bit by bit (maybe each logically related group). Do you think it makes sense?

**Review by srowen — APPROVED** [review]

**Comment by rxin** [comment]
Thanks - merging in master.

**Pull request closed without merging**
