### PR TITLE
[SPARK-42972][DSTREAM]ExecutorAllocationManager cannot allocate new instances when all executors down

### PR DESCRIPTION
**Pull request by liangyu-1**
### What changes were proposed in this pull request?
the PR fix ExecutorAllocationManager cannot allocate new instances when all executors down.

### Why are the changes needed?

fix the bug in issue [SPARK-42972](https://issues.apache.org/jira/browse/SPARK-42972).

when there are only very less executors, the program will be very weak, once the executors are all dead, the driver will never notice this and the whole program will hang.

**Why it happened**
When all executors are dead, there will be no more batches complete, so the _batchProcTimeCount_ will always be zero because it only increases in _onBatchCompleted()_ method and its initial values is zero and will always be set zero in ._manageAllocation()_ method.
In _manageAllocation()_ method, manager will only judge wether to call  _requestExecutors()_ method  when _batchProcTimeCount_ is greater than zero.
The manager will only get new executors when calling _requestExecutors()_ method. 

No executors -> no batch complete -> batchProcTimeCount is zero -> never call requestExecutors -> no executors

This will cause the streaming apps hang. No more batches complete causes _batchProcTimeCount_ always equal to zero; _batchProcTimeCount_ always equal to zero causes the manager never judge whether to call method _requestExecutors_; manager never call method _requestExecutors_ causes that there will no longer be executors to complete new batches. 

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?

I test this in our cluster and the spark streaming app runs normally.

### CODE REVIEW

**Comment by liangyu-1** [comment]
@tdas would you please help me review this pr?

**Comment by mridulm** [comment]
Tagging folks from https://github.com/apache/spark/pull/40621: @HeartSaVioR

**Comment by HeartSaVioR** [comment]
We do deprecate DStream in Spark 3.4 because we have lack of experts in DStream and we have a consensus that SS is the way to go. https://lists.apache.org/thread/342qnjxmnoydzxr0k8yq4roxdmqjhw9x

Btw, I honestly don't know DStream in detail so I cannot be supportive on DStream change.

**Comment by liangyu-1** [comment]
cc @mridulm @tgravescs @HeartSaVioR

**Comment by tgravescs** [comment]
can you please provide details on exactly what is happening in the code to cause it to get stuck?
If the executors are killed, then we should see we don't have enough executors and allocate more. The pr description should describe what isn't working properly such that isn't working.

**Comment by liangyu-1** [comment]
> can you please provide details on exactly what is happening in the code to cause it to get stuck? If the executors are killed, then we should see we don't have enough executors and allocate more. The pr description should describe what isn't working properly such that isn't working.

@tgravescs 

When all executors are dead, there will be no more batches complete, so the _batchProcTimeCount_ will always be zero because it only increases in _onBatchCompleted()_ method.
In _manageAllocation()_ method, manager will only judge wether to request new executor when _batchProcTimeCount_ is greater than zero.
The manager will only get new executors when calling _requestExecutors()_ method. 

This will cause the streaming apps hang. No more batches complete causes _batchProcTimeCount_ always equal to zero; _batchProcTimeCount_ always equal to zero causes the manager never judge whether to call method _requestExecutors_; manager never call method _requestExecutors_ causes that there will no longer be executors to complete new batches.

**Pull request closed without merging**
