### PR TITLE
[SPARK-40735] Consistently invoke bash with /usr/bin/env bash in scripts to make code more portable

### PR DESCRIPTION
**Pull request by huangxiaopingRD**
### What changes were proposed in this pull request?
Consistently invoke bash with /usr/bin/env bash in scripts to make code more portable

### Why are the changes needed?
some bash still use  #!/bin/bash

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
no need test

### CODE REVIEW

**Comment by srowen** [comment]
Sounds good. Is there any situation in which this wouldn't work? I can't think of one

**Comment by huangxiaopingRD** [comment]
> Sounds good. Is there any situation in which this wouldn't work? I can't think of one

"#!/bin/bash" specifies that the path of bash is under the bin directory. Once there is no bash command in the bin directory, the execution will fail, but usually this is unlikely to happen unless the user changes the bash command, such as , with multiple versions of the bash command installed. "#!/usr/bin/env bash" will look for the bash command according to the path set in the environment variable.

**Comment by srowen** [comment]
Right I know that, just wondering if the new version ever doesnt work but I can't think of a scenario

**Comment by srowen** [comment]
Can you try retriggering tests? I think that's an unrelated failure

**Comment by huangxiaopingRD** [comment]
> Can you try retriggering tests? I think that's an unrelated failure

Check passed. Please help to review, thanks~

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
