### PR TITLE
[SPARK-13626] [core] Revert change to SparkConf's constructor.

### PR DESCRIPTION
**Pull request by vanzin**
It shouldn't be private.

### CODE REVIEW

**Comment by vanzin** [comment]
BTW it's a little worrying that MiMA didn't catch this in the original change.

**Comment by rxin** [comment]
LGtm

**Comment by vanzin** [comment]
unrelated test failure. merging to master.

**Comment by dongjoon-hyun** [comment]
Oh, @vanzin .
Sorry for writing comments at the closed PR.

I've read your concern and investigate some. The root cause was `GenerateMIMAIgnore.scala` makes `.generated-mima-class-excludes` from the current code having private class. As a result, it ignores the case : visibility goes from `public` into `private`. Do you think should I make a Jira issue for this?

**Comment by vanzin** [comment]
> Do you think should I make a Jira issue for this?

Please do; this means that APIs that are being changed from public to private might not trigger MiMA failures, when they should. Maybe @JoshRosen could also chime in.

**Comment by dongjoon-hyun** [comment]
Oh, thank you for fast response. I'll do right now.

**Comment by JoshRosen** [comment]
I think this problem relates to the fact that the SparkConf companion object is `private[spark]` and our exclusion generator inappropriately handles cases where classes and their companion objects have different visibility.

I have a good idea of how to fix this, so I'll open a PR in a little bit to address it.

**Comment by dongjoon-hyun** [comment]
Oh, that's great, @JoshRosen .

I made a Jira issue, but could you change that appropriately with yours?

https://issues.apache.org/jira/browse/SPARK-13948

**Comment by JoshRosen** [comment]
I don't think that MiMa is necessarily capable of detecting this problem for things which are evolved to become `private[spark]` because Scala package-private methods become public from Java's point of view and MiMa uses a Java-centric type of binary compatibility; see https://github.com/typesafehub/migration-manager/issues/34. My understanding is that `private[spark]` is a source compatibility issue from Scala's POV and thus is out-of-scope for what MiMa currently detects.

However, I think it's true that we will fail to detect a class which becomes straight-up `private`, so we should definitely fix that.

**Pull request closed without merging**
