### PR TITLE
[MINOR][BUILD] Update all checkstyle dtd to use "https://checkstyle.org"

### PR DESCRIPTION
**Pull request by HeartSaVioR**
## What changes were proposed in this pull request?

Below build failed with Java checkstyle test, but instead of violation it shows FileNotFound on dtd file.
https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/102751/

Looks like the link of dtd file is dead `http://www.puppycrawl.com/dtds/configuration_1_3.dtd`.

This patch updates the dtd link to "https://checkstyle.org/dtds/" given checkstyle repository also updated the URL path.
https://github.com/checkstyle/checkstyle/issues/5601

## How was this patch tested?

Checked the new links.

### CODE REVIEW

**Comment by cloud-fan** [comment]
ok to test

**Comment by cloud-fan** [comment]
cc @HyukjinKwon @srowen

**Review by srowen — APPROVED** [review]

**Comment by kiszk** [comment]
LGTM, pending Jenkins

**Comment by vanzin** [comment]
Merging to master / 2.4 / 2.3.

**Comment by HeartSaVioR** [comment]
Thanks all for reviewing and merging!

**Pull request closed without merging**
