### PR TITLE
[SPARK-13992][Core][PySpark][FollowUp] Update OFF_HEAP semantics for Java api and Python api

### PR DESCRIPTION
**Pull request by lw-lin**
## What changes were proposed in this pull request?
- updated `OFF_HEAP` semantics for `StorageLevels.java`
- updated `OFF_HEAP` semantics for `storagelevel.py`
## How was this patch tested?

no need to test

### CODE REVIEW

**Comment by lw-lin** [comment]
hi @JoshRosen could you take a look? Thanks!

**Comment by lw-lin** [comment]
Jenkins retest this please

**Comment by srowen** [comment]
@lw-lin can you update the comments in these files to not only refer to Tachyon for off-heap storage? should just talk in general about "off-heap"

**Comment by lw-lin** [comment]
@srowen thank you for pointing this out!

Yes sure let's generalize "tachyon" to "off-heap" in these and other files, which has been done in the dedicated PR [[SPARK-14342][Core][Docs][Tests] Remove straggler references to Tachyon](https://github.com/apache/spark/pull/12129).

So it leaves this PR focus on the semantics update, :-)

**Comment by lw-lin** [comment]
@rxin would you mind taking a look, or should I close this PR? Thank you! :-)

**Comment by lw-lin** [comment]
Jenkins retest this please

**Comment by JoshRosen** [comment]
LGTM pending Jenkins. Thanks!

**Comment by rxin** [comment]
Merging in master. Thanks.

**Pull request closed without merging**
