### PR TITLE
[SPARK-41027][SQL] Use `UNEXPECTED_INPUT_TYPE` instead of `MAP_FROM_ENTRIES_WRONG_TYPE`

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr aims to use `UNEXPECTED_INPUT_TYPE` instead of `MAP_FROM_ENTRIES_WRONG_TYPE` and remove the definition of `MAP_FROM_ENTRIES_WRONG_TYPE`.

### Why are the changes needed?
Re-use `UNEXPECTED_INPUT_TYPE `.

### Does this PR introduce _any_ user-facing change?
Yes. The PR changes user-facing error messages.

For example, the error message will change from 

```
The `map_from_entries` accepts only arrays of pair structs, but "a" is of "INT".
```

to

```
parameter 1 requires "ARRAY" of pair "STRUCT" type, however, "a" is of "INT" type.
```

### How was this patch tested?
Pass GA

### CODE REVIEW

**Comment by LuciferYang** [comment]
cc @MaxGekk

**Comment by itholic** [comment]
It would be great if we put some example into the PR description how the error message changes with `Before` and `After` example.

**Comment by LuciferYang** [comment]
Yes, if the exception test lacks the corresponding UT, I will add one

**Comment by MaxGekk** [comment]
@LuciferYang Could you rebase on the recent master and resolve conflicts, please.

**Comment by LuciferYang** [comment]
ok

**Comment by LuciferYang** [comment]
rebase and reuse case add by [SPARK-41021](https://issues.apache.org/jira/browse/SPARK-41021)

**Review by MaxGekk — APPROVED** [review]

**Comment by MaxGekk** [comment]
+1, LGTM. Merging to master.
Thank you, @LuciferYang and @itholic for review.

**Comment by LuciferYang** [comment]
Thanks @MaxGekk @itholic

**Pull request closed without merging**
