### PR TITLE
[MINOR][CORE][SQL] Add missing s prefix to enable string interpolation

### PR DESCRIPTION
**Pull request by EnricoMi**
### What changes were proposed in this pull request?
Adds missing `s` prefix to enable string interpolation.

### Why are the changes needed?
Strings will not contain substituted values but variable names.

### Does this PR introduce _any_ user-facing change?
Log messages will change.

### How was this patch tested?
Not tested.

### CODE REVIEW

**Comment by EnricoMi** [comment]
@HyukjinKwon minor changes fixing log message strings, hoping this does not require a JIRA.

**Review by MaxGekk — APPROVED** [review]

**Review by itholic — APPROVED** [review]
+1

**Comment by MaxGekk** [comment]
+1, LGTM. Merging to master.
Thank you, @EnricoMi.

**Comment by gaoyajun02** [comment]
found some code still missing s, e.g:
https://github.com/apache/spark/blob/0110b1ed88d3c140e1bdf04888740070f1d9d992/core/src/main/scala/org/apache/spark/scheduler/DAGScheduler.scala#L1886

**Comment by EnricoMi** [comment]
And another one:
https://github.com/apache/spark/blob/0110b1ed88d3c140e1bdf04888740070f1d9d992/core/src/main/scala/org/apache/spark/scheduler/TaskSchedulerImpl.scala#L644

Plus five more in tests. Created follow up #38307.

**Pull request closed without merging**
