### PR TITLE
[MINOR][PYTHON] Remove unnecessary quotes in pyspark

### PR DESCRIPTION
**Pull request by dchvn**
### What changes were proposed in this pull request?
Remove unnecessary quotes in pyspark

### Why are the changes needed?
 To make the code clean

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Existing tests

### CODE REVIEW

**Comment by dchvn** [comment]
cc @HyukjinKwon

**Comment by HyukjinKwon** [comment]
cc @zero323 FYI

**Comment by zero323** [comment]
> cc @zero323 FYI

Thanks. Should be OK, as long as the tests pass, though I won't be able to review it properly at the moment.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
