### PR TITLE
[SPARK-25946] [BUILD] Upgrade ASM to 7.x to support JDK11

### PR DESCRIPTION
**Pull request by dbtsai**
## What changes were proposed in this pull request?

Upgrade ASM to 7.x to support JDK11

## How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by dbtsai** [comment]
cc @gatorsmile @srowen @HyukjinKwon

**Review by srowen — APPROVED** [review]
I am guessing this is also needed to support Java 9? either way, yeah, seems good for Spark 3.

**Comment by dbtsai** [comment]
ASM6 supports Java 9 while ASM7 supports Java 9, Java 10, and Java 11.

**Comment by HyukjinKwon** [comment]
Looks good to me.

**Comment by dbtsai** [comment]
Thanks. Merged into master.

**Pull request closed without merging**
