### PR TITLE
[SQL] Fix flaky SET test

### PR DESCRIPTION
**Pull request by marmbrus**

### CODE REVIEW

**Comment by JoshRosen** [comment]
Is this essentially a simplified version of the fix in #2220?  (Just commenting to link the issues together)

**Comment by marmbrus** [comment]
Correct.

**Comment by JoshRosen** [comment]
LGTM, pending Jenkins.  Thanks for fixing this!

**Comment by marmbrus** [comment]
Merging!

**Comment by JoshRosen** [comment]
Cool, thanks!   I think you can close this issue now, since GitHub can't auto-close.

**Pull request closed without merging**
