### PR TITLE
[SPARK-28856][FOLLOW-UP][SQL][TEST] Add the `namespaces` keyword to TableIdentifierParserSuite

### PR DESCRIPTION
**Pull request by highmoutain**
### What changes were proposed in this pull request?

This PR add the `namespaces` keyword to `TableIdentifierParserSuite`.

### Why are the changes needed?
Improve the test.

### Does this PR introduce any user-facing change?
No

### How was this patch tested?
N/A

### CODE REVIEW

**Comment by wangyum** [comment]
ok to test

**Comment by wangyum** [comment]
retest this please

**Comment by wangyum** [comment]
cc @maropu

**Comment by maropu** [comment]
Thanks for your help, @highmoutain. This is only one missing entry there?

**Comment by highmoutain** [comment]
hi @maropu , I think this is the only one missing.

**Review by maropu — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
Welcome to the Apache Spark community and thank you for your first contribution, @highmoutain .
+1, LGTM. Merged to master.

Thank you, @wangyum and @maropu .

**Pull request closed without merging**
