### PR TITLE
[SPARK-31165] Correcting wrong paths in Dockerfile

### PR DESCRIPTION
**Pull request by tech4242**
### What changes were proposed in this pull request?
I have changed a few paths in the Dockerfile that do not seem to reflect the structure of the project anymore. I have described this in detail in SPARK-31165.

### Why are the changes needed?
I think this is clear from above and the commit itself. If this is not 

### Does this PR introduce any user-facing change?
No.

### How was this patch tested?
Manual testing since the Dockerfile build command was not successful, so this mostly involved trial and error.

### CODE REVIEW

**Comment by yaooqinn** [comment]
In fact,  you need to download or build spark distribution first. The Dockerfile is not intended to work with spark source code.

**Comment by tech4242** [comment]
@yaooqinn thanks for reaching out! :) 2 questions from my side:

1) How is the `/kubernetes/ ` path for the resources (in the Dockerfile) ever going to be correct if one is supposed to run this from the root folder (as described in the Dockerfile comment) if all the files are under `/resource-managers/kubernetes/...` and if you e.g. build from source does the folder `/integration-tests/ `suddenly turn to `/tests/` ? I still feel like there are inconsistencies? I feel like your comment might only address the jars folder but for that I would need an answer to 2) below.

2) Do you mean that basically building with `./build/mvn -Pkubernetes -DskipTests clean package` first is pointless or not intended? If that is the case then the documentation should at least be updated or made more a bit easier to understand and I do think that the Dockerfile comment at the beginning of the file is also confusing.

Open to suggestions though - I am just trying to wrap my head around the intended behaviour of this Dockerfile and how it can possible run out of the box.

**Comment by yaooqinn** [comment]
1. Building spark image from source code side, you may use:
```
bin/docker-image-tool.sh -r <repo> -t <tag> build
```

2. Building spark image form distribution you may need to run `dev/make-distribution.sh` with `-Pkubernetes` profile first, untar it, then run the script above under the root of that unzipped folder.

BTW, I am not a committer here, just giving my humble opinion.

**Comment by srowen** [comment]
Yes, at least some of those paths look correct for the distribution structured, not the source tree, so I'd be surprised if this change works as intended. It's possible the kubernetes path is wrong. I'd just ask for more confirmation here, that you built the distro and ran this command and it failed for path X, and the real path is clearly Y now.

**Comment by tech4242** [comment]
@srowen @yaooqinn thank you for your feedback! 

I now ran it with `dev/make-distribution.sh -Pkubernetes` instead of `./build/mvn -Pkubernetes -DskipTests clean package` and it in fact does create a new folder in spark/dist/ where the structure is as described in the Dockerfile. 

I propose that we mention this more explicitly in the documentation https://spark.apache.org/docs/latest/running-on-kubernetes.html to not run `./build/mvn -Pkubernetes -DskipTests clean package` because if you are new-ish to the ecosystem you might end up running that command instead of downloading the distribution or running the said bash script (regardless of what is mentioned in the Prerequisites about the Spark distribution, which I am myself guilty of reading over too quickly) 

Thoughts?

**Comment by srowen** [comment]
Probably a small section under Prerequisites about "How to Build" is fine, unless I'm missing that this is documented elsewhere already.

**Comment by tech4242** [comment]
@srowen sounds good! Would it be ok if I revert the change, squash the commits and make the document change here? Alternatively I'll create a new PR and link to this one

**Comment by srowen** [comment]
Sure just update this pull request.

**Comment by dongjoon-hyun** [comment]
Ya. I saw the same PRs before. This seems to make people confused. Some documentation may help us.

**Comment by dongjoon-hyun** [comment]
BTW, https://spark.apache.org/docs/latest/running-on-kubernetes.html might be not a good place to have that. Please consider https://spark.apache.org/docs/latest/building-spark.html , too.

**Comment by tech4242** [comment]
Thank you @dongjoon-hyun & @srowen I will work on this today/tomorrow and I'll have something ready on the weekend :)

**Comment by srowen** [comment]
@tech4242 do you want to further update?

**Pull request closed without merging**
