### PR TITLE
[SPARK-31831][SQL][FOLLOWUP] Make the GetCatalogsOperationMock for HiveSessionImplSuite compile with the proper Hive version

### PR DESCRIPTION
**Pull request by alismess-db**
### What changes were proposed in this pull request?
#29129 duplicated GetCatalogsOperationMock in the hive-version-specific subdirectories, otherwise profile hive-1.2 would not compile. We can prevent duplication of this class by shimming the required hive-version-specific types.

### Why are the changes needed?
This is a cleanup to avoid duplication of a mock class.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
This patch only changes tests.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
@wangyum

**Review by bogdanghit — APPROVED** [review]
LGTM

**Review by wangyum — COMMENTED** [review]
Could we remove `sql/hive-thriftserver/pom.xml#L155-L166`?https://github.com/apache/spark/blob/9747e8fc9d1c67a4f27f7e4ff94b5f0aca394919/sql/hive-thriftserver/pom.xml#L155-L166

**Review by wangyum — APPROVED** [review]

**Comment by wangyum** [comment]
retest this please

**Comment by wangyum** [comment]
retest this please

**Comment by bogdanghit** [comment]
retest this please

**Comment by wangyum** [comment]
Merged to master.

**Pull request closed without merging**
