### PR TITLE
[SPARK-47342][SQL] Support TimestampNTZ for DB2 TIMESTAMP WITH TIME ZONE

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

This PR Supports TimestampNTZ for DB2 TIMESTAMP WITH TIME ZONE when `preferTimestampNTZ` option is set to true by users

### Why are the changes needed?

improve DB2 connector

### Does this PR introduce _any_ user-facing change?

yes, preferTimestampNTZ works for DB2 TIMESTAMP WITH TIME ZONE
### How was this patch tested?

new tests

### Was this patch authored or co-authored using generative AI tooling?
no

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by dongjoon-hyun** [comment]
Merged to master for Apache Spark 4.0.0.
Thank you, @yaooqinn .

**Comment by dongjoon-hyun** [comment]
Hi, @yaooqinn .

I created an umbrella JIRA issue, SPARK-47361, to give a more visibility to the community JDBC improvement of Apache Spark 4.0.0.

After collecting all patches, I assigned it to you because your contribution is huge. Please feel free to add more subtasks on that umbrella JIRA.

**Comment by yaooqinn** [comment]
Thank you @dongjoon-hyun for creating the umbrella.  It helps a lot for curating recent JDBC data source related change logs.

**Comment by dongjoon-hyun** [comment]
BTW, congratulations for becoming ASF member, @yaooqinn ! 😄

**Comment by yaooqinn** [comment]
Thank you @dongjoon-hyun ;)

**Comment by cloud-fan** [comment]
How can we read TIMESTAMP WITH TIMEZONE as TIMESTAMP WITHOUT TIMEZONE? This doesn't make sense.

**Comment by yaooqinn** [comment]
Many systems supporting TIMESTAMP WITH TIME ZONE will drop the time zone info and use the JVM timezone. Since we get the value from JDBC API with getTimestamp, the conversion is valid?
With JDBC 4.2 spec, we shall use OffsetDateTime/TIMESTAMP_WITH_TIMEZONE = 2014, but it seems rarely supportted.

**Comment by cloud-fan** [comment]
This looks very confusing to end users, as TIMESTAMP WITHOUT TIMEZONE is wall clock time but TIMESTAMP TZ is not. What's wrong with reading TIMESTAMP TZ as TIMESTAMP LTZ?

BTW the option `preferTimestampNTZ` is used to prefer NTZ when reading NTZ in JDBC. This PR kind of abuses it.

**Comment by yaooqinn** [comment]
> When the option is set to <code>true</code>, all timestamps are inferred as TIMESTAMP WITHOUT TIME ZONE.
      Otherwise, timestamps are read as TIMESTAMP with local time zone.

I guess the doc clearly says `all timestamps`?

**Comment by gengliangwang** [comment]
Well, the intention of option `preferTimestampNTZ` is for inferring a value which can be either Timestamp or TimestampNTZ. We use it in file sources like JSON/CSV.

I found the source of the doc: https://github.com/apache/spark/commit/2349175e1b81b0a61e1ed90c2d051c01cf78de9b#diff-bf32dfb48b12b20e3ff6a961e945045faf8e4295df91a633bf525258b8f46ac7R351 . I suggest revising it.

**Comment by cloud-fan** [comment]
> inferring a value which can be either Timestamp or TimestampNTZ

I don't think JDBC TIMESTAMP TZ can be either Timestamp or TimestampNTZ. It can only be Timestamp.

**Comment by yaooqinn** [comment]
+1 for reverting this if the doc is incorrect

**Comment by yaooqinn** [comment]
This is reverted this by[e170252](https://github.com/apache/spark/commit/e170252714e3662c7354321f78a3250114ea7e9e).
After an offline discussion with @cloud-fan, we have reached a consensus for timestamp mapping between databases and spark sql through JDBC APIs.

The decisions can be found at https://github.com/apache/spark/pull/45496.

The revision for DB2 might be raised in followups if necessary

**Comment by dongjoon-hyun** [comment]
Thank you for reverting, @yaooqinn and all.

**Pull request closed without merging**
