### PR TITLE
[SPARK-40084][PYTHON] Upgrade Py4J to 0.10.9.7

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
This PR aim to upgrade Py4J 0.10.9.7, with relevant documentation changes.

### Why are the changes needed?
Py4J 0.10.9.7 support for Java 11/17.
image
Release notes: https://www.py4j.org/changelog.html

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA.

### CODE REVIEW

**Comment by panbingkun** [comment]
Waiting publish version 0.10.9.7 to maven repo, although the official website has been released.

**Comment by HyukjinKwon** [comment]
cc @xinrong-meng

**Comment by xinrong-meng** [comment]
Thanks for working on that! Maven deployment will happen by end of today. I will let you know when it's ready.

**Comment by xinrong-meng** [comment]
In addition, Py4J 0.10.9.7 introduced a fix https://github.com/py4j/py4j/commit/1f8a0b6dc216f16092d9c1b2556897eec8653a62, which is a pre-requisite of supporting NumPy in PySpark built-in functions(as part of [SPARK-39405](https://issues.apache.org/jira/browse/SPARK-39405)).

**Comment by xinrong-meng** [comment]
Hi Maven-side is ready, would you please retrigger the CI tests?

**Comment by panbingkun** [comment]
> Hi Maven-side is ready, would you please retrigger the CI tests?
Okay, I retrigger it.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @panbingkun , @HyukjinKwon and @xinrong-meng .
I believe @xinrong-meng is the best person to merge this PR. :)

**Comment by xinrong-meng** [comment]
Sounds good! Thanks @dongjoon-hyun .

**Comment by xinrong-meng** [comment]
Merged to master. Thank you!

**Pull request closed without merging**
