### PR TITLE
[MINOR] Add Sphinx into dev/requirements.txt

### PR DESCRIPTION
**Pull request by HyukjinKwon**
## What changes were proposed in this pull request?

Not a big deal but this PR adds `sphinx` into `dev/requirements.txt` since we found it needed - https://github.com/apache/spark-website/pull/122#discussion_r200896018

## How was this patch tested?

manually:

```
pip install -r requirements.txt
```

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @felixcheung

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
Merged to master.

**Review by felixcheung — COMMENTED** [review]
LGTM thx

**Comment by HyukjinKwon** [comment]
Thank you @felixcheung.

**Pull request closed without merging**
