### PR TITLE
[Docs] Added csv, orc, and text output format options to DataFrameWriter doc string

### PR DESCRIPTION
**Pull request by mrandrewandrade**
## What changes were proposed in this pull request?

Added the full set of options for the format used in the DataFrameWriter method.

## How was this patch tested?

It's just a trivial doc change.  I tested the format options worked to prepare files in the specified format for csv, orc and text .

### CODE REVIEW

**Comment by mrandrewandrade** [comment]
Since it's a trivial doc change, I didn't make a Jira ticket.  Please let me know if there are any changes required.

**Comment by HyukjinKwon** [comment]
I think it doesn't need to change. It's likely to be changed and we wouldn't want to update this doc everytime we add new datasource.

**Comment by HyukjinKwon** [comment]
It's already documented in official site anyway.

**Comment by mrandrewandrade** [comment]
Why wouldn't you update the documentation to allow users to understand what file formats they can use?  It's really bad practice for users to read source code.

**Comment by HyukjinKwon** [comment]
@mrandrewandrade, let's close this for now.

**Comment by srowen** [comment]
I'm OK with this, but what about adding a hyperlink to https://spark.apache.org/docs/latest/sql-data-sources.html in addition to or instead?

**Pull request closed without merging**
