### PR TITLE
[SPARK-29373][SQL] DataSourceV2: Commands should not submit a spark job

### PR DESCRIPTION
**Pull request by imback82**
### What changes were proposed in this pull request?
DataSourceV2 Exec classes (ShowTablesExec, ShowNamespacesExec, etc.) all extend LeafExecNode. This results in running a job when executeCollect() is called. This breaks the previous behavior [SPARK-19650](https://issues.apache.org/jira/browse/SPARK-19650).

A new command physical operator will be introduced form which all V2 Exec classes derive to avoid running a job.

### Why are the changes needed?

It is a bug since the current behavior runs a spark job, which breaks the existing behavior: [SPARK-19650](https://issues.apache.org/jira/browse/SPARK-19650).

### Does this PR introduce any user-facing change?

No

### How was this patch tested?

Existing unit tests.

### CODE REVIEW

**Comment by imback82** [comment]
@cloud-fan please let me know if this approach is OK. I will update this across all the v2 commands once you are OK with this.

cc: @rdblue

**Comment by cloud-fan** [comment]
LGTM

**Comment by imback82** [comment]
Thanks @cloud-fan. I added the rest of V2 commands. I didn't apply this to physical plans defined in `WriteToDataSourceV2Exec.scala` since they extend `V2TableWriteExec` which runs a spark job.

**Review by cloud-fan — APPROVED** [review]
thanks for catching and fixing this bug！

**Comment by cloud-fan** [comment]
Hi @imback82 , if we don't update `V2TableWriteExec`, does it mean we would submit 2 spark jobs when running `CREATE TABLE AS SELECT`?

**Comment by imback82** [comment]
I double-checked this. `V2TableWriteExec.writeWithV2` returns `sparkContext.emptyRDD`. In this case, `DAGScheduler.submitJob` will return without actually submitting a job. So there will be one job for `CREATE TABLE AS SELECT`.

So theoretically, we could have just returned `sparkContext.emptyRDD` for some of the commands that don't return results (such as `USE`, etc.), but I think the new approach is cleaner (and we still need this new physical operator for `SHOW DATABASE`, etc.)

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Pull request closed without merging**
