### PR TITLE
[SPARK-45576][CORE] Remove unnecessary debug logs in ReloadingX509TrustManagerSuite

### PR DESCRIPTION
**Pull request by hasnain-db**
### What changes were proposed in this pull request?

Remove debug logs that were left in by accident.

### Why are the changes needed?

These were not intended to be committed

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

CI

### Was this patch authored or co-authored using generative AI tooling?

No

### CODE REVIEW

**Comment by hasnain-db** [comment]
cc: @mridulm @JoshRosen

**Review by mridulm — APPROVED** [review]

**Comment by mridulm** [comment]
Merged to master, thanks for fixing this @hasnain-db

**Comment by dongjoon-hyun** [comment]
Hi, @hasnain-db and @mridulm . This seems to break the master branch.

Here is a follow-up to fix Java linter failure.
- https://github.com/apache/spark/pull/43423

**Comment by hasnain-db** [comment]
thank you @dongjoon-hyun ! my apologies here, I should have revisited this once CI signal was back.

**Pull request closed without merging**
