### PR TITLE
[SPARK-4161]Spark shell class path is not correctly set if "spark.driver.extraClassPath" is set in defaults.conf.(branch-1.1 backport)

### PR DESCRIPTION
**Pull request by witgo**
...ath" is set in defaults.conf.(branch-1.1 backport)

### CODE REVIEW

**Comment by andrewor14** [comment]
retest this please

**Comment by witgo** [comment]
Test failure seems to be no related.

**Comment by andrewor14** [comment]
Hm, this seems to be the same test failure from before. @JoshRosen any ideas?

**Comment by andrewor14** [comment]
retest this please

**Comment by andrewor14** [comment]
@witgo actually I already back ported this into branch-1.1 here: https://github.com/apache/spark/commit/7805480dbd8ad2b8859cb5bc6fef6a12e9a16d5e

Would you mind closing this?

**Pull request closed without merging**
