### PR TITLE
[SPARK-16816] Modify java example which is also reflect in documentation exmaple

### PR DESCRIPTION
**Pull request by phalodi**
## What changes were proposed in this pull request?

Modify java example which is also reflect in document.
## How was this patch tested?

run test cases.

### CODE REVIEW

**Comment by phalodi** [comment]
@srowen @rxin Hey guyss i make changes as you suggested but yeah it not exactly what you suggested, i change in example which is also reflect in documentation, so please review it and give give your comments i will change them if you guyss think its not look good.

Changes which i made 

screenshot from 2016-08-01 14-37-10
 
In currently spark 2.0 example for Json Dataset
spark2 0

In previous version example is as follows.
spark1 6

So i make 2.0 example also same as previous version while user do this he/she can also know how to create JavaSparkContext by this.

**Comment by srowen** [comment]
OK, it doesn't hurt. OK to merge if this seems to help your case.

**Comment by phalodi** [comment]
@srowen Yeah i think its look better, complete the example like in earlier versions and also indirectly show how to works with java spark context.

**Comment by srowen** [comment]
Jenkins test this please

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
