### PR TITLE
[SPARK-31215][SPARK-31279][SQL][DOC][3.0] Add version information to the configuration of Static SQL and Hive 

### PR DESCRIPTION
**Pull request by beliefer**
### What changes were proposed in this pull request?
This PR is related to https://github.com/apache/spark/pull/28042 and https://github.com/apache/spark/pull/27981. This PR backport the version to branch-3.0
Commits in this PR:
https://github.com/apache/spark/commit/47c810f8ae186f5b9b7a29c54d22827c3959ccd2
https://github.com/apache/spark/commit/bed21770af67f99f7a1b49a078604abfd0c3e8d6

### Why are the changes needed?
Supplemental configuration version information.

### Does this PR introduce any user-facing change?
'No'.

### How was this patch tested?
Jenkins test.

### CODE REVIEW

**Comment by beliefer** [comment]
@HyukjinKwon You can merge this PR to branch-3.0 directly. Because I have checked the difference between master and branch-3.0.

**Comment by HyukjinKwon** [comment]
@beliefer, thanks. I think there was a bit of miscommunication between us (https://github.com/apache/spark/pull/28124#issuecomment-609514110); however, sure, it's still helpful to refer the conflicts resolved here.

**Comment by beliefer** [comment]
@HyukjinKwon I added two commit log related to this back port PR.

**Comment by HyukjinKwon** [comment]
Thank you @beliefer. I double checked and ported back:

https://github.com/apache/spark/commit/a21a0769b20c5fc613eb1b75362b349ba39290a4
https://github.com/apache/spark/commit/88252acd72a3bd7780e2680264fea076d725b9ef

**Pull request closed without merging**
