### PR TITLE
[SPARK-37298][SQL] Use unique exprIds in RewriteAsOfJoin

### PR DESCRIPTION
**Pull request by allisonwang-db**
### What changes were proposed in this pull request?
This PR updates the `RewriteAsOfJoin` rule to use new exprIds instead of reusing old exprIds.

### Why are the changes needed?
To better guarantee plan integrity and avoid potential issues with exprId reuse.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Existing unit tests

### CODE REVIEW

**Comment by allisonwang-db** [comment]
cc @ueshin

**Comment by ueshin** [comment]
Jenkins, retest this please.

**Review by ueshin — APPROVED** [review]
Using new exprIds makes a lot of sense.
LGTM, pending tests.

**Comment by ueshin** [comment]
Thanks! merging to master.

**Pull request closed without merging**
