### PR TITLE
SPARK-19767 Add note about missing API doc for Kafka 0.10 integration.

### PR DESCRIPTION
**Pull request by nafshartous**
## What changes were proposed in this pull request?

Adding not about missing API docs for Kafka 0.10 

## How was this patch tested?

Viewing generated doc.

### CODE REVIEW

**Comment by srowen** [comment]
It looks like the change got mangled, maybe due to line-ending differences? the diff shows the entire file as a change. Check the CRLF settings in git and try again?

**Comment by nafshartous** [comment]
Should I submit a new PR or is it acceptable to resolve by adding more commits on this one ?

**Comment by srowen** [comment]
Sure you can update this branch too. Force push if you need to.

**Comment by nafshartous** [comment]
Looks like I need to remove the link to the Java source tree as the Java sources are generated not in github.

**Comment by nafshartous** [comment]
Doc link is going to be changed to 0.10 artifact rather than 0.8 in a new PR to address this issue.

**Pull request closed without merging**
