### PR TITLE
[SPARK-44737][SQL][UI] Should not display json format errors on SQL page for non-SparkThrowables on SQL Tab

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

This pull request addresses the issue of inconsistent display for SparkThrowables and others. Currently, SparkThrowables appear as plain text while others are displayed in JSON format on SQL Tab. This fix aims to make the display consistent across all items.

### Why are the changes needed?

To fix the inconsistent behavior, and the JSON format is not correctly displayed.

For those non-SparkThrowables thrown by SQLExecution may contain errors either that we are not ready covered by the new error handling framework or some critical path(what I have met is OOM in RDD.getPartitions), we shall supply the stacktraces 

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

add a unit test

### CODE REVIEW

**Comment by LuciferYang** [comment]
@panbingkun 
https://github.com/yaooqinn/spark/actions/runs/5805477173/job/15746890453

This is the third time I've witnessed a RocksDB crash. It seems like a risk. Do we need to roll back to the previous version that we were using?

There is already a Jira ticket tracking this issue: https://issues.apache.org/jira/browse/SPARK-44580

**Review by LuciferYang — APPROVED** [review]
**Before**

image

**After**

image

LGTM if test pass

**Comment by panbingkun** [comment]
> @panbingkun https://github.com/yaooqinn/spark/actions/runs/5805477173/job/15736662791
> 
> image
> This is the third time I've witnessed the RocksDB crash. It seems like a risk. Do we need to revert to the previous version that we were using?
> 
> There is already a Jira ticket tracking this issue: https://issues.apache.org/jira/browse/SPARK-44580

Let me investigate it first.

**Review by HyukjinKwon — COMMENTED** [review]
Making sense to me but cc @MaxGekk

**Comment by HyukjinKwon** [comment]
cc @gengliangwang too

**Review by MaxGekk — APPROVED** [review]

**Comment by yaooqinn** [comment]
thanks, merged to master and 3.5

**Pull request closed without merging**
