### PR TITLE
[SPARK-4803] [streaming] Remove duplicate RegisterReceiver message

### PR DESCRIPTION
**Pull request by ilayaperumalg**
- The ReceiverTracker receivers `RegisterReceiver` messages two times
   1) When the actor at `ReceiverSupervisorImpl`'s preStart is invoked
   2) After the receiver is started at the executor `onReceiverStart()` at `ReceiverSupervisorImpl`

Though, RegisterReceiver message uses the same streamId and the receiverInfo gets updated everytime
the message is processed at the `ReceiverTracker`, it makes sense to call register receiver only after the
receiver is started.

### CODE REVIEW

**Comment by tdas** [comment]
Ping, any thoughts?

**Comment by ilayaperumalg** [comment]
@tdas sorry, I haven't got a chance to work on this yet. I will try to get something in a few days.

**Comment by tdas** [comment]
Alright.

**Comment by ilayaperumalg** [comment]
@tdas I realized that the issue that is fixed in this PR can be tested via `StreamingListenerSuite`'s receiverInfo reporting test case. Hence, I fixed that test case to:
```
collector.startedReceiverStreamIds.size should equal (1)
```
what do you think?

**Comment by JoshRosen** [comment]
It [looks like](https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/25389/testReport/junit/org.apache.spark.streaming/StreamingListenerSuite/receiver_info_reporting/) the modified test failed?

```
Error Message

The code passed to eventually never returned normally. Attempted 8 times over 1.879575722 seconds. Last failure message: 0 did not equal 1.

Stacktrace

sbt.ForkMain$ForkError: The code passed to eventually never returned normally. Attempted 8 times over 1.879575722 seconds. Last failure message: 0 did not equal 1.
	at org.scalatest.concurrent.Eventually$class.tryTryAgain$1(Eventually.scala:420)
	at org.scalatest.concurrent.Eventually$class.eventually(Eventually.scala:438)
	at org.scalatest.concurrent.Eventually$.eventually(Eventually.scala:478)
	at org.scalatest.concurrent.Eventually$class.eventually(Eventually.scala:307)
	at org.scalatest.concurrent.Eventually$.eventually(Eventually.scala:478)
	at org.apache.spark.streaming.StreamingListenerSuite$$anonfun$2.apply$mcV$sp(StreamingListenerSuite.scala:76)
	at org.apache.spark.streaming.StreamingListenerSuite$$anonfun$2.apply(StreamingListenerSuite.scala:66)```

**Comment by ilayaperumalg** [comment]
Interesting as the test passed initially before the modified test (which means the condition that fails above was greater than equal to 1 when the test passed initially). Could there be timing issues?

Also, I don't understand why the condition was checking `greater than or equal to 1` (which I believe the reason for the issue addressed in this PR) instead of `equal to 1`.

**Comment by ilayaperumalg** [comment]
Any suggestions?

**Comment by tdas** [comment]
This could be a timing issue. Could increase the timeout (say, 2 seconds), and then run it in Jenkins 3-4 times?

**Comment by ilayaperumalg** [comment]
The test passed now (after increasing the timeout value). Can someone re-run the test to see if the test result is consistent?

**Comment by tdas** [comment]
Jenkins, test this please.

**Comment by ilayaperumalg** [comment]
@tdas do you think this is ok to merge now?

**Comment by tdas** [comment]
I think so. Merging this.

**Pull request closed without merging**
