### PR TITLE
[SPARK-12469][CORE][RFC/WIP] Add Consistent Accumulators for Spark

### PR DESCRIPTION
**Pull request by holdenk**
This is an initial PR illustrating one of the possible approaches for providing consistent accumulators in Spark.

Tasks executed on Spark workers are unable to modify values from the driver, and accumulators are the one exception for this. Accumulators in Spark are implemented in such a way that when a stage is recomputed (say for cache eviction) the accumulator will be updated a second time. This makes accumulators inside of transformations more difficult to use for things like counting invalid records (one of the primary potential use cases of collecting side information during a transformation). However in some cases this counting during re-evaluation is exactly the behaviour we want (say in tracking total execution time for a particular function). Spark would benefit from a version of accumulators which did not double count even if stages were re-executed.

Motivating example:

``` scala
val parseTime = sc.accumulator(0L)
val parseFailures = sc.accumulator(0L)
val parsedData = sc.textFile(...).flatMap { line =>
  val start = System.currentTimeMillis()
  val parsed = Try(parse(line))
  if (parsed.isFailure) parseFailures += 1
  parseTime += System.currentTimeMillis() - start
  parsed.toOption
}
parsedData.cache()

val resultA = parsedData.map(...).filter(...).count()

// some intervening code.  Almost anything could happen here -- some of parsedData may
// get kicked out of the cache, or an executor where data was cached might get lost

val resultB = parsedData.filter(...).map(...).flatMap(...).count()

// now we look at the accumulators
```

Here we would want parseFailures to only have been added to once for every line which failed to parse.  Unfortunately, the current Spark accumulator API doesn’t support the current parseFailures use case since if some data had been evicted its possible that it will be double counted.

See the full design document at https://docs.google.com/document/d/1lR_l1g3zMVctZXrcVjFusq2iQVpr4XvRK_UUDsDr6nk/edit?usp=sharing

cc @squito

### CODE REVIEW

**Comment by CodingCat** [comment]
In docs, you need to remove the following sentence 

> For accumulator updates performed inside actions only, Spark guarantees that each task’s update to the accumulator will only be applied once, i.e. restarted tasks will not update the value. In transformations, users should be aware of that each task’s update may be applied more than once if tasks or job stages are re-executed.

**Comment by holdenk** [comment]
That's a good point @codingcat , although the old behavior for regular accumulators is the same I'll add a note about the new API option.

**Comment by holdenk** [comment]
ping @andrewor14 if you have some time to look at this :)

**Comment by holdenk** [comment]
seems unrelated, jenkins retest this please.

**Comment by holdenk** [comment]
I've updated this against master with @andrewor14's Accumulator changes. cc @squito

**Comment by andrewor14** [comment]
@holdenk Thanks for spending the time to put forth the detailed design. I agree 100% with the problem and have thought a great deal about how to fix it myself. However, I personally found the proposed API kind of clunky. It's not super clear what "consistent" means, especially to someone new to Spark. I think it would be cleaner to just implement this in the existing classes themselves and maybe expose only a flag.

It seems that on a high level we want to associate an accumulated value with a particular computation of an RDD. Can we store something like a map from RDD ID to a list of accumulated values in each accumulator? Then if the user calls `acc.value` we just sum all of them up. If the user wants an accumulated value associated with a particular RDD or even a particular computation then they can also do that. E.g.

```
class AccumulableInfo[R, T](...) {
  private val valuesByRDD = mutable.HashMap[Int, ArrayBuffer[R]]
  def value: R = valuesByRDD.values.reduce(mergeThemAll)
  def valueByRDD(rddId: Int): R = valuesByRDD(rddId).reduce(mergeThemAll)
}
```

Even this may solve only part of the problem, where the same accumulator used across different RDDs, but maybe it's a better first step. I may be missing something but I don't see the need to introduce all these new classes; the existing set is confusing enough and in the past we've made the mistake of exposing all of them to the user.

Also, I believe @rxin has some thoughts on this.

**Comment by andrewor14** [comment]
By the way, there's a section on the design doc attached to https://issues.apache.org/jira/browse/SPARK-10620 that describes the same problem by classifying accumulators into different use cases. I think it's simpler to think about this problem in terms of these use cases.

**Comment by holdenk** [comment]
Thanks for taking a look @andrewor14 :) This PR (and the JIRA & design doc) are all very much focused on enabling the _data property_ use case for accumulators.

I introduced the GenericAccumulable as a parent to Accumulable to try and maintain source compatibility between versions and also limit any cost to users of "regular" accumulators - and since we are coming up on Spark 2.0 that might not be worth the overhead so I'm more than happy to simplify that part away. Or if we change the current accumulator base class in such a way it meets the needs while keeping source compatibility all the better.

For the naming of the Consistent Accumulators (or naming of the flag) totally open to ideas - I just didn't have anything else come to mind.

So I'm assuming the clunky part of the API your referring to is the "withAccumulator" part of the transformations - which I do feel is pretty clunky myself. My initial draft attempted to avoid using this (I first tried Implementation Option 1 from the design doc ( https://docs.google.com/document/d/1lR_l1g3zMVctZXrcVjFusq2iQVpr4XvRK_UUDsDr6nk/edit?usp=sharing ) but when multiple transformations are chained together the TaskContext ends up having the RDD id of the inner most RDD. I'd really love to avoid explicitly having the user explicitly pass this information in and if there is a permanent way to do that I'm happy to change this around to give that a shot.

I like the idea of the map of RDD id to accumulated value, since an entire RDD might not be computed in the same task though I think we will need to keep track of the value by RDD ID & Partition ID (or at least keep track of value and bitmask of partitions accumulated per RDD ID). 

cc @squito who did the initial accumulator work and we've gone over the design doc some together.

**Comment by holdenk** [comment]
looks like an internal jenkins issue, jenkins retest this please.

**Comment by holdenk** [comment]
looks like an internal jenkins issue, jenkins retest this please.

**Comment by holdenk** [comment]
jenkins retest this please

**Comment by holdenk** [comment]
@andrewor14 I changed it around a bit so we don't need to have the user explicitly pass the rdd/partition information to the consistent accumulator. It's still got the separate class since we need to keep track of some extra information for consistent accumulators. Think this is closer to the correct direction?

**Comment by holdenk** [comment]
I'm going to close this and re-open one with the "full auto" type approach suggested.

**Pull request closed without merging**
