### PR TITLE
[SPARK-41781][K8S] Add the ability to create pvc before creating driver/executor pod

### PR DESCRIPTION
**Pull request by dcoliversun**
### What changes were proposed in this pull request?

This patch aims to make PVCs as pre-resources and setup them before driver/executor Pod creation. After this patch, the workflow looks like this:
* setup pre-resources (including PVCs) before Pod creation
* create Pod
* refresh all pre-resources' owner references as created Pod
* make the created Pod an owner of other resources and create them

### Why are the changes needed?

These pre-resources are usually necessary in Pod creation and scheduling, they should be ready before Pod creation, should be deleted when user delete Pod, the lifecycle of these resource is same with Pod.   

If PVCs are created after Pod creation, we will have warning event in Pod as follow:  
```plain
error getting PVC "spark/application-exec-1-pvc-0": could not find v1.PersistentVolumeClaim "spark/application-exec-1-pvc-0" 
```

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Add new UTs.

### CODE REVIEW

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
The proposed code changes look like a little too intrusive. Do you think you can minimize some, @dcoliversun ?

**Comment by dcoliversun** [comment]
@dongjoon-hyun Sorry for my late reply. I'm working on minimize intrusive code :)

**Comment by dcoliversun** [comment]
@dongjoon-hyun  
I'd like to discuss two options with you :)
* First: Refer to the idea of [SPARK-37331](https://issues.apache.org/jira/browse/SPARK-37331), I try to move PVC from resources to pre-resources, and set up before driver and executor creation. In future, we could set ConfigMap as pre-resource because there is same warn information about resource not found from k8s scheduler. (This is how this PR works.)
* Second: Leave PVC as resource, filter PVC from resources and setup it before pod creation.

I prefer the first option. First option has more scalability, we could set other k8s resource as pre-resource if need. And I agree with you about code intrusiveness. I think it's worth setting PVC as pre-resource.

Any suggestion is greatly appreciated.

**Review by dongjoon-hyun — COMMENTED** [review]
Thank you for updates. I have two questions.
1. According to the updated PR description, is the only benefit of this refactoring is to remove warning K8s event messages?
2. Does this PR work with the existing feature like SPARK-41515 ?

**Comment by dcoliversun** [comment]
@dongjoon-hyun 
> According to the updated PR description, is the only benefit of this refactoring is to remove warning K8s event messages?

This PR brings two benefit:
* Remove unnecessary warning k8s event messages. We collect events as alarms, and it is currently impossible to determine whether this event is caused by insufficient storage resources or resource creation order.
* In some schedule scenarios, the problem that webhook cannot find PVC based on Pod Spec can be fixed, because old logic is to create PVC after Pod creation.

> Does this PR work with the existing feature like [SPARK-41515](https://issues.apache.org/jira/browse/SPARK-41515) ?  
I'm working on it. Let me check

**Comment by dcoliversun** [comment]
Thank you for the reviews @dongjoon-hyun , I believe I've addressed your comments! Tomorrow is also the Chinese New Year, I wish you a happy Chinese New Year.

**Comment by dcoliversun** [comment]
gentle ping @dongjoon-hyun :)

**Comment by dcoliversun** [comment]
@cometta Hi, this PR is not related to the problem you're having. Could you create an issue in JIRA, attach your spark configuration? I will follow up :)

**Pull request closed without merging**
