### PR TITLE
[MINOR] Spelling mistake: forword -> forward

### PR DESCRIPTION
**Pull request by moqimoqidea**
## What changes were proposed in this pull request?

Spelling mistake: forword -> forward

## How was this patch tested?

This is a private function, there is no place to call this function outside of this file.

### CODE REVIEW

**Comment by srowen** [comment]
OK. Please read https://spark.apache.org/contributing.html though. You need to provide a better, tagged title. We're reasonably open to trivial fixes from new contributors, but longer-term some of these things are better left alone or fixed when the code is otherwise being changed.

**Comment by moqimoqidea** [comment]
> OK. Please read https://spark.apache.org/contributing.html though. You need to provide a better, tagged title. We're reasonably open to trivial fixes from new contributors, but longer-term some of these things are better left alone or fixed when the code is otherwise being changed.

Thank you for your reply, I observed that the general title consists of "[Spark - Numbers] [partial] instructions", sorry I don't know where the numbers and parts are obtained. If there is a more standardized title name, please reply me again, thank you.

**Comment by srowen** [comment]
Just write `[MINOR]` in front of the title -- I'll do it now

**Review by dongjoon-hyun — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
Oops

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
