### PR TITLE
[SPARK-44448][SQL] Add test cases for DenseRankLimitIterator InferWindowGroupLimit bug

### PR DESCRIPTION
**Pull request by jchen5**
### What changes were proposed in this pull request?
This PR adds test cases to demonstrate the bug described in https://issues.apache.org/jira/browse/SPARK-44448. PR for the fix is here: https://github.com/apache/spark/pull/42026

### Why are the changes needed?
Test cases for correctness bug.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Added tests

### CODE REVIEW

**Comment by beliefer** [comment]
This PR is duplicated ?

**Comment by HyukjinKwon** [comment]
yeah, why do we use the same jira?

**Comment by beliefer** [comment]
@jchen5 You could close this one.

**Comment by jchen5** [comment]
Yes, let's just merge https://github.com/apache/spark/pull/42026

**Pull request closed without merging**
