### PR TITLE
[SPARK-9876] [BRANCH-2.0] Revert "[SPARK-9876][SQL] Update Parquet to 1.8.1."

### PR DESCRIPTION
**Pull request by yhuai**
## What changes were proposed in this pull request?

Since we are pretty late in the 2.0 release cycle, it is not clear if this upgrade can be tested thoroughly and if we can resolve the regression issue that we observed before. This PR reverts #13280 from branch 2.0.
## How was this patch tested?

Existing tests

This reverts commit 776d183c82b424ef7c3cae30537d8afe9b9eee83.

### CODE REVIEW

**Comment by yhuai** [comment]
@rdblue  @liancheng Can you review this PR? This is for branch 2.0.

**Comment by rdblue** [comment]
+1, looks fine to me assuming tests pass.

**Comment by liancheng** [comment]
LGTM

**Comment by liancheng** [comment]
Merging to branch-2.0.

**Pull request closed without merging**
