### PR TITLE
[SPARK-10601][SQL] Support `MINUS` set operator

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
## What changes were proposed in this pull request?

This PR adds `MINUS` set operator which is equivalent `EXCEPT DISTINCT`. This will slightly improve the compatibility with Oracle.
## How was this patch tested?

Pass the Jenkins with newly added testcases.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Could you review this PR when you have some time, @hvanhovell ?

**Comment by hvanhovell** [comment]
LGTM - I'll merge as soon as test pass.

**Comment by dongjoon-hyun** [comment]
Thank you so much, @hvanhovell !

**Comment by hvanhovell** [comment]
Merging to master. Thanks!

**Comment by dongjoon-hyun** [comment]
Thank you so much for review and merging, @hvanhovell !

**Pull request closed without merging**
