### PR TITLE
[SPARK-36944][PYTHON] Remove python/pyspark/sql/__init__.pyi

### PR DESCRIPTION
**Pull request by dchvn**
### What changes were proposed in this pull request?
Remove python/pyspark/sql/\_\_init\_\_.pyi

### Why are the changes needed?
Remove python/pyspark/sql/\_\_init\_\_.pyi

### Does this PR introduce _any_ user-facing change?
No
### How was this patch tested?
existing tests

### CODE REVIEW

**Comment by dchvn** [comment]
CC @HyukjinKwon @zero323 FYI

**Comment by HyukjinKwon** [comment]
Please mention that in PR description which PR made this file unused.

**Comment by dchvn** [comment]
@HyukjinKwon It's not a FOLLOW_UP PR. When working on issue [SPARK-36845](https://issues.apache.org/jira/browse/SPARK-36845), i did not found any where use this file, so i think we do not need this file. Thanks!

**Comment by HyukjinKwon** [comment]
Do you mind searching the github history and identify which PR removed the usage?

**Review by zero323 — APPROVED** [review]

**Comment by zero323** [comment]
Merged to master.

**Comment by zero323** [comment]
Thanks @dchvn @HyukjinKwon

**Pull request closed without merging**
