### PR TITLE
[SPARK-5979][SPARK-6032] Smaller safer --packages fix

### PR DESCRIPTION
**Pull request by brkyvz**
@pwendell @tdas 
This is the safer parts of PR #4754:
- SPARK-5979: All dependencies with the groupId `org.apache.spark` passed through `--packages`, were being excluded from the dependency tree on the assumption that they would be in the assembly jar. This is not the case, therefore the exclusion rules had to be defined more explicitly.
- SPARK-6032: Ivy prints a whole lot of logs while retrieving dependencies. These were printed to `System.out`. Moved the logging to `System.err`.

### CODE REVIEW

**Comment by tdas** [comment]
I tested your PR branch and its works pretty well!

**Comment by tdas** [comment]
LGTM
@pwendell Any final look?

**Comment by pwendell** [comment]
LGTM

**Comment by JoshRosen** [comment]
Mind maybe copying some of the description from the other PR into this one so that the commit message is useful?

**Comment by pwendell** [comment]
Pulling this in - thanks Burak!

**Pull request closed without merging**
