### PR TITLE
[SPARK-29036][SQL]SparkThriftServer cancel job after execute() thread interrupted

### PR DESCRIPTION
**Pull request by AngersZhuuuu**
### What changes were proposed in this pull request?
Discuss in https://github.com/apache/spark/pull/25611 

If cancel() and close() is called very quickly after the query is started, then they may both call cleanup() before Spark Jobs are started. Then sqlContext.sparkContext.cancelJobGroup(statementId) does nothing.
But then the execute thread can start the jobs, and only then get interrupted and exit through here. But then it will exit here, and no-one will cancel these jobs and they will keep running even though this execution has exited.

So  when execute() was interrupted by `cancel()`, when get into catch block, we should call canJobGroup again to make sure the job was canceled.

### Does this PR introduce any user-facing change?
NO

### How was this patch tested?
MT

### CODE REVIEW

**Comment by AngersZhuuuu** [comment]
@juliuszsompolski add a new pr for problem we have discussed .

**Review by juliuszsompolski — APPROVED** [review]
LGTM.
Thanks @AngersZhuuuu !

**Review by juliuszsompolski — APPROVED** [review]
LGTM from me. cc @wangyum

**Comment by wangyum** [comment]
retest this please

**Review by wangyum — APPROVED** [review]

**Comment by wangyum** [comment]
Merged to master.

**Pull request closed without merging**
