### PR TITLE
[MINOR] Fixed up pandas_udf related docs and formatting

### PR DESCRIPTION
**Pull request by BryanCutler**
## What changes were proposed in this pull request?

Fixed some minor issues with pandas_udf related docs and formatting.

## How was this patch tested?

NA

### CODE REVIEW

**Comment by BryanCutler** [comment]
@HyukjinKwon @ueshin hopefully this is ok to do without a related JIRA, just some minor cleanup.  Thanks!

**Review by HyukjinKwon — APPROVED** [review]
LGTM

**Review by ueshin — APPROVED** [review]
LGTM too.

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
