### PR TITLE
[SPARK-26306][TEST][BUILD] More memory to de-flake SorterSuite

### PR DESCRIPTION
**Pull request by srowen**
## What changes were proposed in this pull request?

Increase test memory to avoid OOM in TimSort-related tests.

## How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by viirya** [comment]
retest this please.

**Comment by dongjoon-hyun** [comment]
Thank you for making this PR. I know that we are very conservative in this area, but I'm +1 for this PR.

@rxin and @aarondav . Since [SPARK-26306](https://issues.apache.org/jira/browse/SPARK-26306) is related to [SPARK-5984](https://github.com/apache/spark/pull/4804), could you give us some advice for this PR?

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by srowen** [comment]
Merged to master

**Comment by dongjoon-hyun** [comment]
It's great. Thank you, @srowen !

**Pull request closed without merging**
