### PR TITLE
[SPARK-48802][SS][FOLLOWUP] FileStreamSource maxCachedFiles set to 0 causes batch with no files to be processed

### PR DESCRIPTION
**Pull request by ragnarok56**
### What changes were proposed in this pull request?

This is a followup to a bug identified from https://github.com/apache/spark/pull/45362.  When setting `maxCachedFiles` to 0 (to force a full relisting of files for each batch, see https://issues.apache.org/jira/browse/SPARK-44924) subsequent batches of files would be skipped due to a logic error that carried forward an empty array of `unreadFiles` which was only being null checked.  This update includes additional checks to verify that `unreadFiles` is also non-empty as a guard condition to prevent batches executing with no files, as well as checks to ensure that `unreadFiles` is only set if a) there are files remaining in the listing and b) `maxCachedFiles` is greater than 0

### Why are the changes needed?

Setting the `maxCachedFiles` configuration to 0 would inadvertently cause every other batch to contain 0 files, which is an unexpected behavior for users.

### Does this PR introduce _any_ user-facing change?

Fixes the case where users may want to always perform a full listing of files each batch by setting `maxCachedFiles` to 0

### How was this patch tested?

New test added to verify `maxCachedFiles` set to 0 would perform a file listing each batch

### Was this patch authored or co-authored using generative AI tooling?
No

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Mind filing a JiRA? See also https://spark.apache.org/contributing.html

**Comment by ragnarok56** [comment]
Created https://issues.apache.org/jira/browse/SPARK-48802 for this as a bug

**Review by HeartSaVioR — APPROVED** [review]
+1

**Comment by HeartSaVioR** [comment]
Thanks! Merging to master.

**Pull request closed without merging**
