### PR TITLE
[MINOR][DOCS] Fix typos in `configuration.md` and `hardware-provisioning.md`

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
## What changes were proposed in this pull request?

This PR fixes some typos in the following documentation files.
- `NOTICE`, `configuration.md`, and `hardware-provisioning.md`.
## How was the this patch tested?

manual tests

Author: Dongjoon Hyun dongjoon@apache.org

### CODE REVIEW

**Comment by srowen** [comment]
That's fine. The `NOTICE` typos are actually from the upstream source notices, so I guess we really technically don't care / shouldn't change them, but I'm OK with it.

**Comment by srowen** [comment]
Jenkins test this please

**Comment by dongjoon-hyun** [comment]
Oh, thank you, @srowen .

**Comment by rxin** [comment]
I don't think we should change the NOTICE file. Can you reset the change for that?

**Comment by dongjoon-hyun** [comment]
Oh, sure. No problem. Only for `NOTICE`, right?

**Comment by rxin** [comment]
Yes only notice. Thanks.

**Comment by dongjoon-hyun** [comment]
Thank you, @rxin. I remove the change on NOTICE file and rebased it now.

**Comment by rxin** [comment]
Thanks - I've merged this.

**Comment by dongjoon-hyun** [comment]
Thank you for merging, @rxin .

**Pull request closed without merging**
