### PR TITLE
[SPARK-4502][SQL] Rename to spark.sql.optimizer.nestedSchemaPruning.enabled

### PR DESCRIPTION
**Pull request by rxin**
## What changes were proposed in this pull request?
This patch adds an "optimizer" prefix to nested schema pruning.

## How was this patch tested?
Should be covered by existing tests.

### CODE REVIEW

**Comment by rxin** [comment]
cc @cloud-fan

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by dongjoon-hyun** [comment]
Could you add `[FOLLOWUP]` tag to the title, too?

**Comment by rxin** [comment]
done

**Comment by rxin** [comment]
jenkins, retest this again

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
retest this please

**Pull request closed without merging**
