### PR TITLE
Update Word2Vec.scala

### PR DESCRIPTION
**Pull request by dgai91**
## What changes were proposed in this pull request?

add two function cosineSimilarity and doc2Vector 

## How was this patch tested?

i tested it myself and it worked well but maybe the bVecter in doc2Vector can be a param,i will update it soon
i have updated it

### CODE REVIEW

**Comment by lawlietAi** [comment]
sorry i'm confused about to operate the github.what should i do

**Comment by srowen** [comment]
@lawlietAi you should close this and read http://spark.apache.org/contributing.html . This doesn't describe the purpose or need for this change

**Comment by lawlietAi** [comment]
@srowen  sorry, i'll familiar this documentation on my spare time. thanks for your patience

**Comment by gatorsmile** [comment]
Really appreciate your contribution! Sorry, based on the comment, we might need to close this PR, but please submit more PRs in the future. Thanks again!

**Pull request closed without merging**
