### PR TITLE
[Spark-14685] [CORE] Document heritability of localProperties

### PR DESCRIPTION
**Pull request by marcintustin**
## What changes were proposed in this pull request?

This updates the java-/scala- doc for setLocalProperty to document heritability of localProperties. This also adds tests for that behaviour.
## How was this patch tested?

Tests pass. New tests were added.

### CODE REVIEW

**Comment by marcintustin** [comment]
@rxin Documentation and tests PR. Enhancement PR to follow.

**Comment by marcintustin** [comment]
@JoshRosen This may well be of interest. As mentioned above, my enhancement PR is pending (running tests right now).

**Comment by marcintustin** [comment]
The test failures are probably bogus, as per http://mail-archives.apache.org/mod_mbox/spark-dev/201604.mbox/%3CCAMFhwAYRbN0yJGwzvrY8atzS9CCudzioF%3DbcGogCwPq3gPC6Uw%40mail.gmail.com%3E

**Comment by marcintustin** [comment]
@rxin Are you cool to go ahead with this before we resolve the deal on #12456?

**Comment by rxin** [comment]
Thanks - let's merge this first once Jenkins pass.

**Comment by marcintustin** [comment]
@rxin Tests have passed, can we merge? This still seems low risk for Spark-2.0

**Comment by rxin** [comment]
Thanks - merging in master / branch-2.0.

**Pull request closed without merging**
