### PR TITLE
[Minor] Slightly better error message when attempting to query hive tables w/in-mem catalog

### PR DESCRIPTION
**Pull request by ericl**
@andrewor14

### CODE REVIEW

**Comment by andrewor14** [comment]
looks good

**Comment by andrewor14** [comment]
FYI @gatorsmile

**Comment by gatorsmile** [comment]
Thanks!

**Comment by rxin** [comment]
@andrewor14 when you merge pull requests in the future, please have an explicit message that the pr's merged and include the branches.

**Comment by andrewor14** [comment]
Sorry I usually do but forgot for this one. This was merged into master 2.0

**Pull request closed without merging**
