### PR TITLE
[SPARK-26588][CORE] Idle executor should properly be removed when no job is su…

### PR DESCRIPTION
**Pull request by TopGunViper**
## What changes were proposed in this pull request?

I enable dynamic allocation feature with **spark-shell** and do not submit any task. After **spark.dynamicAllocation.executorIdleTimeout** seconds(default 60s), there is still one active executor, which is abnormal. All idle executors are timeout and should be removed.(default  **spark.dynamicAllocation.minExecutors**=0). The spark-shell command show below:

`spark-shell --master=yarn --conf spark.ui.port=8040 --conf spark.dynamicAllocation.enabled=true --conf spark.dynamicAllocation.maxExecutors=8 --conf spark.dynamicAllocation.initialExecutors=4 --conf spark.shuffle.service.enabled=true`

## How was this patch tested?
unit tests

### CODE REVIEW

**Comment by srowen** [comment]
CC @jerryshao

**Comment by jerryshao** [comment]
1) please fix the PR title to follow Spark's way. 2) Can you please figure out which patch introduce this regression? I did remember that this should be OK in my previous test.

**Comment by TopGunViper** [comment]
> 1. please fix the PR title to follow Spark's way. 2) Can you please figure out which patch introduce this regression? I did remember that this should be OK in my previous test.

Hi @jerryshao I guess this problem was introduced by the patch [SPARK-21656](https://github.com/apache/spark/pull/18874).

**Comment by TopGunViper** [comment]
CC @tgravescs

**Comment by jerryshao** [comment]
Jenkins, retest this please.

**Comment by jerryshao** [comment]
I can reproduce this issue, will spend time on it. Thanks.

**Comment by jerryshao** [comment]
Jenkins, retest this please.

**Comment by jerryshao** [comment]
The change itself looks fine to me. @tgravescs @vanzin would you please also take a look.

**Comment by vanzin** [comment]
Already fixed by SPARK-26758.

**Pull request closed without merging**
