### PR TITLE
[SPARK-27998] [SQL] Improve ANSI compliance for strings and double-quoted identifiers

### PR DESCRIPTION
**Pull request by andygrove**
### What changes were proposed in this pull request?

According to SQL-1999 (the latest version of the ANSI SQL specification that I have access to), SQL strings are quoted with single quotes (`'`), and "delimited identifiers" are quoted with double-quotes (`"`).

Spark currently supports both single and double quotes for strings, which is not ANSI-compliant, and does not support double-quotes for identifiers, only backticks.

This PR brings Spark closer to the ANSI specified behavior with single quotes for strings and double quotes for identifiers.

The first commit (https://github.com/apache/spark/pull/35853/commits/bec0b4abd62b41c60266125306086966e0610b45) updates the SQL grammar to make this syntax change.

The second commit (https://github.com/apache/spark/pull/35853/commits/ccc4406f317e447bf31ddf1a3ec8f8982e30c2a5) updates documentation.

The remaining commits update existing tests to consistently use single quotes instead of double quotes for SQL strings.

### Why are the changes needed?

The main motivation is to support the official TPC-DS queries, which use double-quoted aliases.

### Does this PR introduce _any_ user-facing change?

Yes, users will no longer be able to use double quotes for strings and will need to use single quotes instead.

### How was this patch tested?

A new test was added to `ExpressionParserSuite` and other tests have been updated as required. We have tested manually with TPC-DS queries as well.

### CODE REVIEW

**Comment by tgravescs** [comment]
ok to test

**Comment by itholic** [comment]
Are you still working on this ??

IMHO, if it is difficult to pass all the tests at once, how about making a sub-task JIRA and dividing the work into small pieces?

It will also provide convenience to reviewers, anyway.

**Comment by tgravescs** [comment]
@gengliangwang @MaxGekk would be great to get feedback from people working in the ansi area.

**Comment by gengliangwang** [comment]
@andygrove I think it is too late to change the existing behavior now. Most of the Spark SQL users will be affected if we decide to merge this.

> The main motivation is to support the official TPC-DS queries, which use double-quoted aliases.

The queries under https://github.com/apache/spark/tree/master/sql/core/src/test/resources/tpcds are also valid.

**Comment by tgravescs** [comment]
I get we don't want to break, I was wondering if this is something we could config, like strict ansi version XX vs spark ansi.  @andygrove pointed out to me that the antlr stuff might be hard with just a config though.

Do you have any thoughts or ideas?

**Comment by andygrove** [comment]
@gengliangwang @tgravescs I am working on an alternate approach now in https://github.com/apache/spark/pull/36151 so will close this PR. The new approach opens up the option of introducing configs to control the behavior as well.

**Pull request closed without merging**
