### PR TITLE
[Minor] [ML] [Doc] Remove duplicated periods at the end of some sharedParam

### PR DESCRIPTION
**Pull request by yanboliang**
## What changes were proposed in this pull request?

Remove duplicated periods at the end of some sharedParams in ScalaDoc, such as [here](https://github.com/apache/spark/pull/11344/files#diff-9edc669edcf2c0c7cf1efe4a0a57da80L367)
cc @mengxr @srowen 
## How was this patch tested?

Documents change, no test.

### CODE REVIEW

**Comment by srowen** [comment]
@yanboliang this isn't worth changing. The period isn't hurting anything

**Comment by yanboliang** [comment]
@srowen Some ScalaDoc will end with two dots if we don't fix, you can refer [here](https://github.com/apache/spark/pull/11344/files#diff-9edc669edcf2c0c7cf1efe4a0a57da80L367).

**Comment by yanboliang** [comment]
Jenkins, test this please.

**Comment by yanboliang** [comment]
Jenkins, test this please.

**Comment by jkbradley** [comment]
May not be worth it, but I think it's fine to fix.  LGTM  I'll merge this with master

**Pull request closed without merging**
