### PR TITLE
[SPARK-6611][SQL] Add support for INTEGER as synonym of INT.

### PR DESCRIPTION
**Pull request by smola**
https://issues.apache.org/jira/browse/SPARK-6611

### CODE REVIEW

**Comment by liancheng** [comment]
ok to test

**Comment by marmbrus** [comment]
This seems reasonable to me.  Thanks!

Please add a test in `DataTypeParserSuite`.

**Comment by smola** [comment]
It seems there was a git fetch error on Jenkins.

**Comment by marmbrus** [comment]
Thanks!  Merged to master.

**Pull request closed without merging**
