### PR TITLE
[SPARK-30161][SQL] Uncaught Analysis Exception in Spark-Shell

### PR DESCRIPTION
**Pull request by amanomer**
### What changes were proposed in this pull request?
Catch Analysis exception on Spark-Shell.

### Why are the changes needed?
We should catch Analysis Exception like Spark-sql and avoid printing long stack trace.

### Does this PR introduce any user-facing change?
No

### How was this patch tested?
Manually. After the patch,
`sql("select every(1)")`

> org.apache.spark.sql.AnalysisException: Error in query: cannot resolve 'bool_and(1)' due to data type mismatch: Input to function 'bool_and' should have been boolean, but it's [int].; line 1 pos 7;
> 'Aggregate [unresolvedalias(bool_and(1), None)]
> +- OneRowRelation
> ;
>   at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:611)
>   ... 47 elided

### CODE REVIEW

**Comment by amanomer** [comment]
cc @cloud-fan

**Comment by srowen** [comment]
Hm do we do that with any other exceptions? and why just in the shell? I agree the stack trace doesn't add much and maybe worth special-casing for interactive usage like here.

**Comment by amanomer** [comment]
Currently, on spark-sql, we are not printing stack trace for `AnalysisException` and `IllegalArgumentException`

**Comment by srowen** [comment]
OK where is that handled? I'm just wondering if there's a better more central place to catch this. Like would it get all AnalysisException? this just affects sql().

**Comment by amanomer** [comment]
In spark-sql that is handled in SparkcCLIDriver
https://github.com/apache/spark/blob/16f1b23d75c0b44aac61111bfb2ae9bb0f3fab68/sql/hive-thriftserver/src/main/scala/org/apache/spark/sql/hive/thriftserver/SparkSQLCLIDriver.scala#L381-L390

**Comment by srowen** [comment]
OK but shouldn't this similarly be somewhere 'higher up' rather than in the session, and only for sql()?

**Comment by amanomer** [comment]
I think it is getting called from some internal api?

**Comment by amanomer** [comment]
Stack trace is as below:

> **sql:608, SparkSession (org.apache.spark.sql)**
> <init>:24, $read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw ($line14)
> <init>:28, $read$$iw$$iw$$iw$$iw$$iw$$iw$$iw ($line14)
> <init>:30, $read$$iw$$iw$$iw$$iw$$iw$$iw ($line14)
> <init>:32, $read$$iw$$iw$$iw$$iw$$iw ($line14)
> <init>:34, $read$$iw$$iw$$iw$$iw ($line14)
> <init>:36, $read$$iw$$iw$$iw ($line14)
> <init>:38, $read$$iw$$iw ($line14)
> <init>:40, $read$$iw ($line14)
> <init>:42, $read ($line14)
> <init>:46, $read$ ($line14)
> <clinit>:-1, $read$ ($line14)
> $print$lzycompute:7, $eval$ ($line14)
> $print:6, $eval$ ($line14)
> $print:-1, $eval ($line14)
> invoke0:-1, NativeMethodAccessorImpl (sun.reflect)
> invoke:62, NativeMethodAccessorImpl (sun.reflect)
> invoke:43, DelegatingMethodAccessorImpl (sun.reflect)
> invoke:498, Method (java.lang.reflect)
> call:745, IMain$ReadEvalPrint (scala.tools.nsc.interpreter)
> loadAndRun:1021, IMain$Request (scala.tools.nsc.interpreter)
> $anonfun$interpret$1:574, IMain (scala.tools.nsc.interpreter)
> apply:-1, 1810953994 (scala.tools.nsc.interpreter.IMain$$Lambda$1210)
> asContext:41, ScalaClassLoader (scala.reflect.internal.util)
> asContext$:37, ScalaClassLoader (scala.reflect.internal.util)
> asContext:41, AbstractFileClassLoader (scala.reflect.internal.util)
> loadAndRunReq$1:573, IMain (scala.tools.nsc.interpreter)
> interpret:600, IMain (scala.tools.nsc.interpreter)
> interpret:570, IMain (scala.tools.nsc.interpreter)
> interpretStartingWith:894, ILoop (scala.tools.nsc.interpreter)
> command:762, ILoop (scala.tools.nsc.interpreter)
> processLine:464, ILoop (scala.tools.nsc.interpreter)
> loop:485, ILoop (scala.tools.nsc.interpreter)
> **process:239, SparkILoop (org.apache.spark.repl)**
> doMain:78, Main$ (org.apache.spark.repl)
> .
> .

https://github.com/apache/spark/blob/16f1b23d75c0b44aac61111bfb2ae9bb0f3fab68/repl/src/main/scala/org/apache/spark/repl/SparkILoop.scala#L239
Control goes from here to internal APIs. And for every query flow doesn't come back even in case of Exception.

**Comment by srowen** [comment]
Are you trying to solve this for spark-shell or spark-sql? spark-shell right?
So, what about something like `selectExpr("invalid")` - would this also catch that case?

**Comment by amanomer** [comment]
> what about something like selectExpr("invalid") - would this also catch that case?

No.

**Comment by amanomer** [comment]
Current solution will only work when query is submitted using SS.sql().

**Comment by amanomer** [comment]
cc @cloud-fan

**Comment by cloud-fan** [comment]
what's wrong with the stack trace? If people are using Scala APIs, don't they expect to see detailed stack trace?

**Comment by HeartSaVioR** [comment]
> We have to find a common place to catch all exceptions thrown by queries in spark-shell.

I think that's the key - without this I'm not sure it can address the issue properly.

**Comment by dongjoon-hyun** [comment]
Give the limitation of this PR, this PR seems to make our UX environment more heterogeneous. I prefer the current status if we don't have a nicer solution.

**Comment by viirya** [comment]
Why do we need to avoid the stack trace? spark-shell is good for debugging, don't we expect to see stack trace there?

**Comment by dongjoon-hyun** [comment]
Given the above discussion, I close this PR for now.
Thank you for suggestion, @amanomer . You can reopen this PR when you have a new proposal.

**Pull request closed without merging**
