### PR TITLE
[Build] SPARK-2614: (2nd patch) Create a spark-XXX-examples.deb package in addition to the spark-XXX-all.deb (-Pdeb profile)

### PR DESCRIPTION
**Pull request by tzolov**
New patch that takes into consideration Mark Hamstra's suggestion (https://issues.apache.org/jira/browse/SPARK-2614) to create a separate (dedicated) spark_examples package (e.g spark-XXX-examples.deb) instead of bundleing the spark_examples.jar inside the spark-XXX-all.deb.

When build with the -Pdeb profile enabled the project creates two debian packages like this:

```
-rw-r--r--  1 tzoloc  720748206  108151256 Jul 27 23:27 spark_1.1.0-SNAPSHOT-2bbf2353_all.deb
-rw-r--r--  1 tzoloc  720748206   59732472 Jul 27 23:27 spark_1.1.0-SNAPSHOT-2bbf2353_examples.deb
```

### CODE REVIEW

**Comment by nchammas** [comment]
This PR has gone stale. Should it be revived or is it no longer needed?

**Comment by tzolov** [comment]
@nchammas from the discussions so far it seems that this change is not required/desired
But in case that someone is interested i've just rebased and realigned the pull-request to the latest upstream/master

**Comment by srowen** [comment]
Per SPARK-5727, I believe the outstanding Debian issues should be closed.

**Comment by srowen** [comment]
Mind closing this PR?

**Comment by tzolov** [comment]
i'm closing this PR as this functionality is deprecated.

**Pull request closed without merging**
