### PR TITLE
[SPARK-12016][MLlib][PySpark] Wrap Word2VecModel when loading it in pyspark

### PR DESCRIPTION
**Pull request by viirya**
JIRA: https://issues.apache.org/jira/browse/SPARK-12016

We should not directly use Word2VecModel in pyspark. We need to wrap it in a Word2VecModelWrapper when loading it in pyspark.

### CODE REVIEW

**Comment by holdenk** [comment]
This is only a suggestion, but looking at the other Java loadable models which are also wrapped in python it seems the standard approach is to instead add a load[X] method to the PythonMLLibAPI instead of doing the wrapper in Python. Might be worth doing that way just for consistencies sake - what are your thoughts?

**Comment by viirya** [comment]
It makes sense. Thanks. I will update this later.

**Comment by viirya** [comment]
ping @davies @mengxr

**Comment by viirya** [comment]
ping @davies Can you take a look of this? It should be straightforward one.

**Comment by davies** [comment]
LGTM, merging this into master, thanks!

**Comment by jkbradley** [comment]
I just backported this to 1.6 and 1.5

**Pull request closed without merging**
