### PR TITLE
[SPARK-41105][CONNECT] Adopt `optional` keyword from proto3 which offers `hasXXX` to differentiate if a field is set or unset

### PR DESCRIPTION
**Pull request by amaliujia**
### What changes were proposed in this pull request?

We used to wrap those fields into messages to acquire the ability to tell if those field is set or unset. It turns out proto3 offers built-in mechanism to achieve the same thing: https://developers.google.com/protocol-buffers/docs/proto3#specifying_field_rules.

It is as easy as adding `optional` keyword to the field to auto-generate `hasXXX` method.

This PR refactors existing proto to get rid of redundant message definitions.   

### Why are the changes needed?

Codebase simplification. 

### Does this PR introduce _any_ user-facing change?

NO

### How was this patch tested?

Existing UT

### CODE REVIEW

**Comment by amaliujia** [comment]
@cloud-fan 

cc @HyukjinKwon @zhengruifeng @grundprinzip @hvanhovell

**Comment by zhengruifeng** [comment]
why not use `optional` before?

**Comment by amaliujia** [comment]
We didn't know it works by this way.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by cloud-fan** [comment]
There are still some fields documented as optional but don't use the `optional` keywork. Do we need to change them?

**Comment by amaliujia** [comment]
@cloud-fan 

We need to a bit more discussion on when to use `optional`. Right now the most obvious usage is to replace those `message` wrap.

One example is, if a field is required, should we use `optional` notion? It acutally makes sense that required field are those that we need to know whether that is set or not, and `optional` notion offers `hasXXX` to help us tell that.

You see the `optional` itself becomes tricky when we think our need for `required`, `optional with default value`, `optional without default value`, etc.

I think we need more time to think this through.

**Pull request closed without merging**
