### PR TITLE
[SPARK-11695][CORE] Set s3a credentials

### PR DESCRIPTION
**Pull request by Zariel**
Set s3a credentials when creating a new default hadoop configuration.

### CODE REVIEW

**Comment by Zariel** [comment]
@vanzin could you take a look please?

**Comment by vanzin** [comment]
ok to test

**Comment by vanzin** [comment]
Code looks good to me, but I'm not really familiar with s3 configuration.

**Comment by vanzin** [comment]
Merging to master / 1.6.

**Pull request closed without merging**
