### PR TITLE
SPARK-6919 [PYSPARK] Add asDict method to StatCounter

### PR DESCRIPTION
**Pull request by eshilts**
Add method to easily convert a StatCounter instance into a Python dict

https://issues.apache.org/jira/browse/SPARK-6919

Note: This is my original work and the existing Spark license applies.

### CODE REVIEW

**Comment by ash211** [comment]
Jenkins this is ok to test

**Comment by eshilts** [comment]
Any chance we can get this PR looked at or merged?

**Comment by JoshRosen** [comment]
Jenkins, this is ok to test.

**Comment by eshilts** [comment]
AFAICT, the build fails on files I haven't touched. I get assorted failures unrelated to this patch when running all tests locally, too. I'm not sure why that is.

From Jenkins:
```
FAIL: test_trainOn_predictOn (__main__.StreamingKMeansTest)
Test that prediction happens on the updated model.
...
Had test failures in pyspark.mllib.tests with python2.6; see logs.
```

**Comment by eshilts** [comment]
After getting the latest from master and rebuilding Spark, this now passes all tests. It should be ready to be re-tested on Jenkins and merged.

**Comment by davies** [comment]
LGTM, merging into master, thanks!

**Pull request closed without merging**
