### PR TITLE
[SPARK-17415][SQL] Better error message for driver-side broadcast join OOMs

### PR DESCRIPTION
**Pull request by sameeragarwal**
## What changes were proposed in this pull request?

This is a trivial patch that catches all `OutOfMemoryError` while building the broadcast hash relation and rethrows it by wrapping it in a nice error message.
## How was this patch tested?

Existing Tests

### CODE REVIEW

**Comment by sameeragarwal** [comment]
Here is the list of changes with whitespaces ignored: https://github.com/apache/spark/pull/14979/files?w=1

**Comment by sameeragarwal** [comment]
cc @davies

**Comment by hvanhovell** [comment]
LGTM - pending Jenkins.

**Comment by hvanhovell** [comment]
Merging to master. Thanks!

**Pull request closed without merging**
