### PR TITLE
[SPARK-3674] YARN support in Spark EC2

### PR DESCRIPTION
**Pull request by shivaram**
This corresponds to https://github.com/mesos/spark-ec2/pull/116 in the spark-ec2 repo. The only changes required on the spark_ec2.py script is to open the RM port. 

cc @andrewor14

### CODE REVIEW

**Comment by shivaram** [comment]
@andrewor14 - One question I had was whether we should open `8042` in the worker nodes. This might be useful to see the NodeManager UI  ? (See `yarn.nodemanager.webapp.address` in https://hadoop.apache.org/docs/r2.4.1/hadoop-yarn/hadoop-yarn-common/yarn-default.xml)

**Comment by shivaram** [comment]
Jenkins, retest this please

**Comment by shivaram** [comment]
Jenkins, retest this please

**Comment by andrewor14** [comment]
@shivaram I don't believe the NM UI is used by Spark. Everything we need should be exposed or proxied through 8088. Merging into master 1.4.

**Pull request closed without merging**
