### PR TITLE
[SPARK-14961] Build HashedRelation larger than 1G

### PR DESCRIPTION
**Pull request by davies**
## What changes were proposed in this pull request?

Currently, LongToUnsafeRowMap use byte array as the underlying page, which can't be larger 1G.

This PR improves LongToUnsafeRowMap  to scale up to 8G bytes by using array of Long instead of array of byte. 
## How was this patch tested?

Manually ran a test to confirm that both UnsafeHashedRelation and LongHashedRelation could build a map that larger than 2G.

### CODE REVIEW

**Comment by davies** [comment]
cc @sameeragarwal

**Comment by rxin** [comment]
This one is fine, but next time we should just use a chunked array, instead of a single giant array?

**Comment by sameeragarwal** [comment]
Looks great!

**Comment by davies** [comment]
@rxin I also though on that. A chunked way is a little faster to build but slower to probe. In this case, The HashedRelation is built once, but probed millions or billions time, we should optimize it for probing not building, that's the reason I'm choose single array here.

**Comment by rxin** [comment]
Would it actually have a difference in practice? I suspect the overhead is negligible given how many other things we are doing for joins (e.g. breaking unsaferows back into variables, computing offsets, ...)

**Comment by davies** [comment]
When profiling the performance for BytesToBytesMap, it does have difference.

**Comment by davies** [comment]
Merging this into master, thanks!

**Pull request closed without merging**
