### PR TITLE
[SPARK-16477] Bump master version to 2.1.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by rxin**
## What changes were proposed in this pull request?

After SPARK-16476 (committed earlier today as #14128), we can finally bump the version number.
## How was this patch tested?

N/A

### CODE REVIEW

**Comment by rxin** [comment]
cc @srowen

**Comment by srowen** [comment]
Hm I tried this recently and it failed mima. I think this has to bump the base mima version too but then it will fail because 2.0.0 isn't released. I thought we'd have to wait.

**Comment by rxin** [comment]
That's why I did https://github.com/apache/spark/pull/14128

Base mima version is still 1.6, and 2.0 and 2.1 currently has the same set of excludes.

**Comment by srowen** [comment]
OK, later we'd have to make the base version 2.0.0 right? that's fine though either way we have to bump something later, so was going to wait, but, no big deal either way, especially if it reduces confusion about the snapshot number

**Comment by rxin** [comment]
Yup once we actually release we can bump the base version. The good thing with the new approach is that we can now define mima excludes based on 2.0 or 2.1 versions already.

**Comment by rxin** [comment]
I'm going to merge this in master.

**Pull request closed without merging**
