### PR TITLE
[MINOR][SQL][SS] Reorganize packages in streaming sources

### PR DESCRIPTION
**Pull request by uncleGen**
## What changes were proposed in this pull request?

- There is not new code added. Reorganize streaming source impl (v1 or v2) into separate package.
- fix a typo in doc

## How was this patch tested?

No new unit test added.

### CODE REVIEW

**Comment by uncleGen** [comment]
Retest this please

**Comment by srowen** [comment]
Would any of those classes be public, and visible to users? 
Also is it not reasonable to call the existing packages "v1" and only put "v2" in new subpackages?
Don't strongly object here, just wondering how much it's worth moving all that code.

**Comment by uncleGen** [comment]
@srowen Thanks for your reply.

> Would any of those classes be public, and visible to users?

No, there is not any user-visible class changes.

> Also is it not reasonable to call the existing packages "v1" and only put "v2" in new subpackages?

There are some data source implementations located in different packages, and it looks like a little bit confusing. Besides, there are some implementation based on *DataSource V2*. So this PR slightly reorganized these classes. And honestly, I am not totally sure "v1" and "v2" subpackages is a good idea.

Any suggestion is appreciated!

**Comment by uncleGen** [comment]
Retest this please.

**Comment by uncleGen** [comment]
pending on fixing unit test failure

**Comment by gaborgsomogyi** [comment]
I tend to agree with @srowen . Removing the extra `*` is absolutely fine but I wouldn't have also confidence to commit such sudden movement without measurable value.

**Pull request closed without merging**
