### PR TITLE
[SPARK-6149] [SQL] [Build] Excludes Guava 15 referenced by jackson-module-scala_2.10

### PR DESCRIPTION
**Pull request by liancheng**
This PR excludes Guava 15.0 from the SBT build, to make Spark SQL CLI (`bin/spark-sql`) work when compiled against Hive 0.12.0.

[Review on Reviewable](https://reviewable.io/reviews/apache/spark/4890)

### CODE REVIEW

**Comment by liancheng** [comment]
@pwendell I have verified locally that this fixes the SQL CLI tool with Hive 0.12.0. However, I'm not sure whether this is the most proper/elegant way to do the exclusion. Please help review, thanks!

**Comment by pwendell** [comment]
@liancheng can you put this exclusion in the pom.xml file instead of in sbt? If you look there we already have other exclusions.

**Comment by liancheng** [comment]
@pwendell Thanks! Moved to POM.

**Comment by pwendell** [comment]
I'm going to "optimistically" merge this to cut another RC.

**Pull request closed without merging**
