### PR TITLE
[SPARK-27423][SQL] Cast DATE <-> TIMESTAMP according to the SQL standard

### PR DESCRIPTION
**Pull request by MaxGekk**
## What changes were proposed in this pull request?

According to SQL standard, value of `DATE` type is union of year, month, dayInMonth, and it is independent from any time zones. To convert it to Catalyst's `TIMESTAMP`, `DATE` value should be "extended" by the time at midnight - `00:00:00`. The resulted local date+time should be considered as a timestamp in the session time zone, and casted to microseconds since epoch in `UTC` accordingly. 

The reverse casting from `TIMESTAMP` to `DATE` should be performed in the similar way. `TIMESTAMP` values should be represented as a local date+time in the session time zone. And the time component should be just removed. For example, `TIMESTAMP 2019-04-10 00:10:12` -> `DATE 2019-04-10`. The resulted date is converted to days since epoch `1970-01-01`. 

## How was this patch tested?

The changes were tested by existing test suites - `DateFunctionsSuite`, `DateExpressionsSuite` and `CastSuite`.

### CODE REVIEW

**Comment by MaxGekk** [comment]
@cloud-fan Please, take a look at the PR.

**Comment by cloud-fan** [comment]
a correction: the timestamp in Spark is TIMESTAMP WITH LOCAL TIMEZONE. It's non-SQL-standard(but Oracle has it) and is a little different from TIMESTAMP WITH TIMEZONE.

TIMESTAMP WITH TIMEZONE means, each timestamp value has an associated timezone.

TIMESTAMP WITH LOCAL TIMEZONE means, all the timestamp values have a session-global associated timezone.

The casting behavior should be the same though.

**Review by cloud-fan — APPROVED** [review]
LGTM if all tests pass

**Comment by MaxGekk** [comment]
> LGTM if all tests pass

They passed but let me run this with your changes https://github.com/apache/spark/pull/24325 , just in case

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Pull request closed without merging**
