### PR TITLE
[SPARK-48430][SQL] Fix map value extraction when map contains collated strings

### PR DESCRIPTION
**Pull request by nikolamand-db**
### What changes were proposed in this pull request?

Following queries return unexpected results:
```
select collation(map('a', 'b' collate utf8_binary_lcase)['a']);
select collation(element_at(map('a', 'b' collate utf8_binary_lcase), 'a'));
```
Both return `UTF8_BINARY` instead of `UTF8_BINARY_LCASE`.

The error was introduced by changes in https://github.com/apache/spark/pull/46661 that tried to solve other problem with `RaiseError` expression (please refer to PR for details). Partially revert changes of mentioned PR and fix the `RaiseError` issue by explicitly setting `UTF8_BINARY` collation.

### Why are the changes needed?

To fix wrong results of mentioned queries.

### Does this PR introduce _any_ user-facing change?

Yes, it fixed explained error.

### How was this patch tested?

Added test to `CollationSQLExpressionsSuite`.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Review by dbatomic — APPROVED** [review]

**Review by uros-db — APPROVED** [review]
lgtm

**Comment by cloud-fan** [comment]
can we do a more surgical partial revert? I did notice the potential issue in the offending PR but didn't realize it could cause a real issue: https://github.com/apache/spark/pull/46661#discussion_r1609846584

I agree we should match `RaiseError` explicitly in the rule `CollationTypeCasts`, but changes in other files can remain?

**Review by uros-db — APPROVED** [review]
@cloud-fan Since the problem is now contained to `RaiseError`, and this issue is a blocker for @nikolamand-db - I'd suggest that we cross that bridge when we get to it and leave any extra MapType casting support for another time

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Pull request closed without merging**
