### PR TITLE
[SPARK-46901][PYTHON] Upgrade `pyarrow` to 15.0.0

### PR DESCRIPTION
**Pull request by zhengruifeng**
### What changes were proposed in this pull request?
Upgrade `pyarrow` to 15.0.0

### Why are the changes needed?
to support latest pyarrow

### Does this PR introduce _any_ user-facing change?
no

### How was this patch tested?
ci

### Was this patch authored or co-authored using generative AI tooling?
no

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
Nice! (Pending CIs) Does new MLFlow support this?

**Review by LuciferYang — APPROVED** [review]
LGTM

**Comment by dongjoon-hyun** [comment]
Merged to master. Thank you, @zhengruifeng and @LuciferYang .

**Comment by zhengruifeng** [comment]
thanks @dongjoon-hyun and @LuciferYang for reviews

**Pull request closed without merging**
