### PR TITLE
[SPARK-35431][SQL][TESTS] Sort elements generated by collect_set in SQLQueryTestSuite

### PR DESCRIPTION
**Pull request by maropu**
### What changes were proposed in this pull request?

To pass `subquery/scalar-subquery/scalar-subquery-select.sql` (`SQLQueryTestSuite`) in Scala v2.13,  this PR proposes to change the aggregate expr of a test query in the file from `collect_set(...)` to `sort_array(collect_set(...))` because `collect_set` depends on the `mutable.HashSet` implementation and elements in the set are printed in a different order in Scala v2.12/v2.13.

### Why are the changes needed?

To pass the test in Scala v2.13.

### Does this PR introduce _any_ user-facing change?

No, dev-only.

### How was this patch tested?

Manually checked.

### CODE REVIEW

**Comment by maropu** [comment]
cc: @dongjoon-hyun

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM (Pending CIs)

**Comment by dongjoon-hyun** [comment]
Oh, @maropu . Could you use a new JIRA ID?

**Comment by maropu** [comment]
> Oh, @maropu . Could you use a new JIRA ID?

okay, updated.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Merged to master. Thank you, @maropu and @HyukjinKwon .

**Comment by dongjoon-hyun** [comment]
This is backported to branch-3.1, too.
- https://amplab.cs.berkeley.edu/jenkins/view/Spark%20QA%20Test/job/spark-branch-3.1-test-maven-hadoop-2.7-scala-2.13/

I manually checked the result in branch-3.1 with Scala 2.13.
```
...
[info] SQLQueryTestSuite:
23:17:59.055 WARN org.apache.hadoop.util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[info] - subquery/subquery-in-from.sql (741 milliseconds)
[info] - subquery/exists-subquery/exists-joins-and-set-ops.sql (30 seconds, 725 milliseconds)
[info] - subquery/exists-subquery/exists-having.sql (1 second, 60 milliseconds)
[info] - subquery/exists-subquery/exists-orderby-limit.sql (2 seconds, 586 milliseconds)
[info] - subquery/exists-subquery/exists-cte.sql (933 milliseconds)
[info] - subquery/exists-subquery/exists-basic.sql (546 milliseconds)
[info] - subquery/exists-subquery/exists-within-and-or.sql (286 milliseconds)
[info] - subquery/exists-subquery/exists-aggregate.sql (3 seconds, 524 milliseconds)
[info] - subquery/negative-cases/subq-input-typecheck.sql (91 milliseconds)
[info] - subquery/negative-cases/invalid-correlation.sql (110 milliseconds)
23:18:49.431 WARN org.apache.spark.sql.catalyst.util.package: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.
[info] - subquery/scalar-subquery/scalar-subquery-select.sql (2 seconds, 641 milliseconds)
...
```

**Comment by maropu** [comment]
Thank you, @dongjoon-hyun and @HyukjinKwon ~

**Pull request closed without merging**
