### PR TITLE
[SPARK-47993][DOCS][FOLLOWUP] Update RDD programing guide to Python 3.9+

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This is a follow-up of
- #46228

### Why are the changes needed?

To update the RDD programing guide consistently.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Manual review.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
This seems to be the last place which we missed.
```
$ git grep 'Python 3.8'
licenses-binary/LICENSE-loose-version.txt:Starting with Python 3.8.6, examples, recipes, and other code in
licenses/LICENSE-loose-version.txt:Starting with Python 3.8.6, examples, recipes, and other code in
python/docs/source/migration_guide/pyspark_upgrade.rst:* In Spark 4.0, Python 3.8 support was dropped in PySpark.
python/pyspark/cloudpickle/cloudpickle.py:            # backport of the Python 3.8 state_setter pickle operations
python/pyspark/serializers.py:    # For Python 3.8+, we use CPickle-based cloudpickle.
```

**Comment by dongjoon-hyun** [comment]
cc @HyukjinKwon

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by dongjoon-hyun** [comment]
Thank you, @HyukjinKwon !

**Pull request closed without merging**
