### PR TITLE
[SPARK-33251][FOLLOWUP][PYTHON][DOCS][MINOR] Adjusts returns PrefixSpan.findFrequentSequentialPatterns

### PR DESCRIPTION
**Pull request by zero323**
### What changes were proposed in this pull request?

Changes 

    pyspark.sql.dataframe.DataFrame

to

    :py:class:`pyspark.sql.DataFrame`

### Why are the changes needed?

Consistency (see https://github.com/apache/spark/pull/30285#pullrequestreview-526764104).

### Does this PR introduce _any_ user-facing change?

User will see shorter reference with a link.

### How was this patch tested?

`dev/lint-python` and manual check of the rendered docs.

### CODE REVIEW

**Comment by zero323** [comment]
cc @huaxingao

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
@huaxingao, BTW, have you tried to merge PRs? I will leave it for you to try merging :-).

**Review by huaxingao — APPROVED** [review]

**Comment by huaxingao** [comment]
Merged to master. Thanks! @zero323 @HyukjinKwon

**Comment by zero323** [comment]
Thanks @huaxingao @HyukjinKwon!

**Pull request closed without merging**
