### PR TITLE
[SPARK-20974][BUILD] we should run REPL tests if SQL module has code changes

### PR DESCRIPTION
**Pull request by cloud-fan**
## What changes were proposed in this pull request?

REPL module depends on SQL module, so we should run REPL tests if SQL module has code changes.

## How was this patch tested?

N/A

### CODE REVIEW

**Comment by cloud-fan** [comment]
cc @JoshRosen

**Comment by JoshRosen** [comment]
LGTM

**Comment by cloud-fan** [comment]
retest this please

**Comment by JoshRosen** [comment]
Oh, that's a legitimate failure:

```
File "./dev/run-tests.py", line 112, in __main__.determine_modules_to_test
Failed example:
    x # doctest: +NORMALIZE_WHITESPACE
Expected:
    ['sql', 'hive', 'mllib', 'sql-kafka-0-10', 'examples', 'hive-thriftserver',
     'pyspark-sql', 'sparkr', 'pyspark-mllib', 'pyspark-ml']
Got:
    ['sql', 'hive', 'mllib', 'sql-kafka-0-10', 'examples', 'hive-thriftserver', 'pyspark-sql', 'repl', 'sparkr', 'pyspark-mllib', 'pyspark-ml']
```

You need to update the build script's internal tests.

**Comment by cloud-fan** [comment]
thanks for the review, merging to master/2.2/2.1/2.0!

**Pull request closed without merging**
