### PR TITLE
[SPARK-10653] [Core] Remove unnecessary things from SparkEnv

### PR DESCRIPTION
**Pull request by ajbozarth**
## What changes were proposed in this pull request?

Removed blockTransferService and sparkFilesDir from SparkEnv since they're rarely used and don't need to be in stored in the env. Edited their few usages to accommodate the change.
## How was this patch tested?

ran dev/run-tests locally

### CODE REVIEW

**Comment by srowen** [comment]
It probably bears explaining this a little better: it's because they're not really used. It took me some time to sort out the logic about why this looks right.

**Comment by ajbozarth** [comment]
Updated the description with more detail

**Comment by andrewor14** [comment]
@ajbozarth can you link the title to the JIRA

**Comment by ajbozarth** [comment]
@andrewor14 thanks, my page refreshed while I was opening this and I lost all I typed in, must have missed that when retyping everything, explains why I haven't gotten any traction

**Comment by andrewor14** [comment]
LGTM. In the future we can also remove `broadcastManager`, which really doesn't do anything (SPARK-13524).

**Comment by andrewor14** [comment]
Merging into master 2.0.

**Comment by ajbozarth** [comment]
@andrewor14 Thanks, for `broadcastManager` it seemed a lot more work which is why I didn't also tackle it, SPARK-13524 is closed as "Later" currently, would it be worth reopening and tackling if I have time? I know it's not a 2.0 priority

**Pull request closed without merging**
