### PR TITLE
[SPARK-48751][INFRA][PYTHON][TESTS] Re-balance `pyspark-pandas-connect` tests on GA

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to `re-balance` `pyspark-pandas-connect` tests on `GA`.

### Why are the changes needed?
Make the execution cost time of `pyspark-pandas-connect-part[0-3]` testing to a relatively average level, avoiding the occurrence of long tails and resulting in higher overall GA execution cost time.

Here are some currently observed examples:
- https://github.com/apache/spark/pull/47135/checks?check_run_id=26784966983
  image

  Most of them are around `1 hour`, but `part2` cost `1h 49m`, `part3` cost `2h 16m`

- https://github.com/panbingkun/spark/actions/runs/9693237300
  image
  Most of them are around `1 hour`, but `part2` cost `1h 47m`, `part3` cost `2h 20m`

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Manually observing the cost time of `pyspark-pandas-connect-part[0-3]`.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by panbingkun** [comment]
Use the following steps to re-balance:
- Download logs from GA, extract the execution cost time of `each UT`, and calculate the total execution cost time of `each part*`, eg:
- 
```
```

**Comment by panbingkun** [comment]
After this pr:
- First time

**Comment by HyukjinKwon** [comment]
cc @zhengruifeng and @itholic

**Review by itholic — APPROVED** [review]

**Comment by itholic** [comment]
Looks fine for now, but maybe in the future we might need to separate this into more parts instead of just rebalancingif the number of test will be increased.

**Comment by HyukjinKwon** [comment]
Nope, actually splitting the build increases the usage of the resource so I asked to distribute existing test cases for now. We got a bit of pushes from ASF

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by zhengruifeng** [comment]
Late LGTM

**Comment by panbingkun** [comment]
> Nope, actually splitting the build increases the usage of the resource so I asked to distribute existing test cases for now. We got a bit of pushes from ASF

I'm actually quite curious, what does this mean? - `We got a bit of pushes from ASF`
Does ASF require us to `reduce` the usage of resource?

**Comment by HyukjinKwon** [comment]
we now have limited resources. See also https://issues.apache.org/jira/browse/SPARK-48094

**Comment by panbingkun** [comment]
> we now have limited resources. See also https://issues.apache.org/jira/browse/SPARK-48094

Okay, I see, thanks.

**Pull request closed without merging**
