### PR TITLE
[SPARK-4576][SQL] Add concatenation operator

### PR DESCRIPTION
**Pull request by sarutak**
The standard SQL defines `||` as a concatenation operator.
The operator makes concatenated string from 2 operands.

### CODE REVIEW

**Comment by sarutak** [comment]
So, how about adding `CONCAT` function working like the function Hive has?

**Comment by marmbrus** [comment]
Yeah, agreed.  Lets block this on SPARK-4867, but once that is fixed I'd love to have a native `concat` function.

**Comment by marmbrus** [comment]
For now though I propose we close this issue.

**Comment by sarutak** [comment]
O.K, closing this PR.

**Pull request closed without merging**
