### PR TITLE
[SPARK-32237][SQL][3.0] Resolve hint in CTE

### PR DESCRIPTION
**Pull request by LantaoJin**
### What changes were proposed in this pull request?
The backport of #29062

This PR is to move `Substitution` rule before `Hints` rule in `Analyzer` to avoid hint in CTE not working.

### Why are the changes needed?
Below SQL in Spark3.0 will throw AnalysisException, but it works in Spark2.x
```sql
WITH cte AS (SELECT /*+ REPARTITION(3) */ T.id, T.data FROM $t1 T)
SELECT cte.id, cte.data FROM cte
```
```
Failed to analyze query: org.apache.spark.sql.AnalysisException: cannot resolve '`cte.id`' given input columns: [cte.data, cte.id]; line 3 pos 7;
'Project ['cte.id, 'cte.data]
+- SubqueryAlias cte
   +- Project [id#21L, data#22]
      +- SubqueryAlias T
         +- SubqueryAlias testcat.ns1.ns2.tbl
            +- RelationV2[id#21L, data#22] testcat.ns1.ns2.tbl

'Project ['cte.id, 'cte.data]
+- SubqueryAlias cte
   +- Project [id#21L, data#22]
      +- SubqueryAlias T
         +- SubqueryAlias testcat.ns1.ns2.tbl
            +- RelationV2[id#21L, data#22] testcat.ns1.ns2.tbl
```

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Add a unit test

### CODE REVIEW

**Comment by LantaoJin** [comment]
retest this please

**Comment by dongjoon-hyun** [comment]
Could you resolve conflicts, @LantaoJin ?

**Comment by dongjoon-hyun** [comment]
Also, cc @HyukjinKwon for `PySpark pip packaging failure`. It seems that `branch-3.0` still complains for that.

**Comment by HyukjinKwon** [comment]
@dongjoon-hyun, I will backport https://github.com/apache/spark/pull/29117. Thanks for letting me know.

**Comment by dongjoon-hyun** [comment]
Thank you for resolving conflicts, @LantaoJin .
cc @cloud-fan

**Comment by cloud-fan** [comment]
thanks, merging to 3.0!

**Pull request closed without merging**
