### PR TITLE
[SPARK-11780][SQL] Add catalyst type aliases backwards compatibility

### PR DESCRIPTION
**Pull request by maropu**
Changed a target at branch-1.6 from #10635.

### CODE REVIEW

**Comment by maropu** [comment]
Jenkins, retest this please.

**Comment by maropu** [comment]
Jenkins, retest this please.

**Comment by maropu** [comment]
Jenkins, retest this please.

**Comment by maropu** [comment]
@marmbrus Okay and could you check this?

**Comment by marmbrus** [comment]
Thanks, merged to branch-1.6.

**Comment by marmbrus** [comment]
Can you close this PR now?

**Pull request closed without merging**
