### PR TITLE
[SPARK-5130][Deploy]Take yarn-cluster as cluster mode in spark-submit

### PR DESCRIPTION
**Pull request by WangTaoTheTonic**
https://issues.apache.org/jira/browse/SPARK-5130

### CODE REVIEW

**Comment by WangTaoTheTonic** [comment]
Have tested using command `./spark-submit  --class org.apache.spark.examples.SparkPi --master yarn-cluster ../lib/spark-examples*.jar`.
Before this patch, client will launch SparkSubmitDriverBootstrapper first then SparkSubmit process.
After this patch, client will launch SparkSubmit directly.
It meets our expect.

**Comment by WangTaoTheTonic** [comment]
@JoshRosen Could you take a quick look at and merge this?

**Comment by andrewor14** [comment]
Ok LGTM I'm merging this into master thanks.

**Comment by andrewor14** [comment]
By the way in the long term we should deprecate specifying `yarn-cluster` as the master altogether to avoid this kind of hack.

**Pull request closed without merging**
