### PR TITLE
[SPARK-37604][SQL] Change emptyValueInRead's effect to that any fields matching this string will be set as "" when reading csv files

### PR DESCRIPTION
**Pull request by wayneguow**
### What changes were proposed in this pull request?

We change the effect of emptyValueInRead option in CSVOptions to that any fields matching this string will be set as "" when reading csv files. Before this change, the effect of it is to convert quoted empty strings "\\"\\""  to defined emptyValueInRead strings. 

### Why are the changes needed?

 After this change, the effect of emptyValueInRead option is more in line with the user's usage habits and it will has the similar behavior as nullValue option when reading csv files. We can parse dataframe from csv files as the same as the original one when writing and reading with the same emptyValue(emptyValueInWrite == emptyValueInRead) setting. 

Before this change, for codes follows:
```scala
val data = Seq(("Tesla", "")).toDF("make", "comment")
data.show()
data.write.options(Map("header" -> "true", "emptyValue" -> "EMPTY")).csv(path)
```
dataframe shows as:
|make|comment|
|----|----|
|Tesla| |

the csv data shows as:
>Tesla,EMPTY

If we read this csv file with the same emptyValue value:
```scala
spark.read.options(Map("header" -> "true", "emptyValue" -> "EMPTY")).csv(path)
```
We finally get DataFame data shows as:
|make|comment|
|----|----|
|Tesla| EMPTY|

After this change, we can parse the csv file to get the same dataframe.
|make|comment|
|----|----|
|Tesla| |

### Does this PR introduce _any_ user-facing change?

Yes, uses should know this change clearly and be carefully to deal with the emptyValue parameter with self-defined value.

### How was this patch tested?

Upgrade related test cases that already exists in CSVSuite.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
ok to test

**Review by HyukjinKwon — COMMENTED** [review]
Hm,

- `emptyValue` in read path reads the value as `""`.
- `emptyValue` in write path writes `""` as the value.

But the current change will change the behaviour of `emptyValue` in read to:
- `emptyValue` in read path reads the value as `""`  as the value.

I think either way make sense so I wouldn't introduce an unnecessary breaking change here.

**Comment by wayneguow** [comment]
Yes, I agree with you that it would make a breaking change. The parameter `emptyValue` which designed in `CsvParserSettings` of Univocity is used instead of an empty strings when reading csv files.

What makes me confused is that is there any better way to read csv files which are written with self-defined emptyValue. In writing, if emptyValue is set to "EMPTY", when reading, we can't recognize empty strings("EMPTY") but got a "EMPTY" string rather "". We need to handle "EMPTY" strings with hardcode rather than setting options when reading.

**Comment by wayneguow** [comment]
Yes, I agree with you that it would make a breaking change. The parameter `emptyValue` which designed in `CsvParserSettings` of Univocity is used instead of an empty strings when reading csv files.

What makes me confused is that is there any better way to read csv files which are written with self-defined emptyValue. In writing, if emptyValue is set to "EMPTY", when reading, we can't recognize empty strings("EMPTY") but got a "EMPTY" string rather "". We need to handle "EMPTY" strings with hardcode rather than setting options when reading.

**Comment by wayneguow** [comment]
Maybe a kind of possible approach to avoid a breaking change is that adding another boolean option in CSVOptions such as `parseEmptyValueAsEmpty` which is default set as false. And with this option, we can change the `nullSafeDatum` method in UnivocityParser as follows:
```
private def nullSafeDatum(
     datum: String,
     name: String,
     nullable: Boolean,
     options: CSVOptions)(converter: ValueConverter): Any = {
  if (datum == options.nullValue || datum == null) {
    if (!nullable) {
      throw new RuntimeException(s"null value found but field $name is not nullable.")
    }
    null
  } else if (options.parseEmptyValueAsEmpty && datum == options.emptyValueInRead) {
    converter.apply("")
  } else {
    converter.apply(datum)
  }
}
```
With this option, the default behavior is same with before, but for users such as me, we can succeed to parse emptyValue strings to "" when reading csv files.

**Comment by wayneguow** [comment]
Currently, maybe it is not widely required.

**Pull request closed without merging**
