### PR TITLE
[SPARK-10399][CORE][SQL] Introduce OffHeapMemoryBlock to hold DirectByteBuffer, refactor spark.unsafe.Platform

### PR DESCRIPTION
**Pull request by yzotov**
## What changes were proposed in this pull request?
- OffHeapMemoryBlock is introduced which holds reference to java.nio.DirectByteBuffer.
  This allows to have offheap memory which is automatically deallocated by JVM.
- spark.unsafe.Platform interface refactored from indefinite Objects, to MemoryBlocks and arrays of primitives. This has led to large code changes in core, catalyst, sql.
- org.apache.spark.sql.catalyst.expressions.codege.BufferHolder is replaced by MemoryBlockHolder which tests spark.memory.offHeap.enadled configuration property and allocates ByteArrayMemoryBlock or OffHeapMemoryBlock.
## How was this patch tested?

mvn test

### CODE REVIEW

**Comment by yzotov** [comment]
@JoshRosen could you please review the PR, or ask somebody to do this. The main reason for the path is to allow passing UnsafeRow data into C native runtime. I think there could be better approach, but need some feedback from more experienced developers. Thank you in advance.

**Comment by rxin** [comment]
Thanks for the pull request. I'm going through a list of pull requests to cut them down since the sheer number is breaking some of the tooling we have. Due to lack of activity on this pull request, I'm going to push a commit to close it. Feel free to reopen it or create a new one. We can also continue the discussion on the JIRA ticket.


Note: This is a pretty useful idea. I think we will want to revisit it with a stable columnar format so we can use that to send to external systems.

**Comment by rxin** [comment]
Actually I'm going to keep this open :)

**Comment by HyukjinKwon** [comment]
Should we still need to keep this open? If so, when will we review this?

**Comment by jiangxb1987** [comment]
cc @cloud-fan Any thoughts on this?

**Comment by cloud-fan** [comment]
I think this is a useful refactor and allows us to exchange data with native library efficiently via `java.nio.DirectByteBuffer`. @yzotov do you mind bring it up-to-date? I'll review it.

BTW, let's not bother about `BufferHolder` for now.

**Comment by HyukjinKwon** [comment]
gentle ping @yzotov.

**Comment by kiszk** [comment]
kindly ping @yzotov

**Comment by kiszk** [comment]
kindly ping @yzotov

**Comment by HyukjinKwon** [comment]
gentle ping @yzotov

**Comment by kiszk** [comment]
While we pinged @yzotov , @yzotov did not respond to us for a very long time. As @cloud-fan pointed out, this PR seems to be good refactoring. I am willing to continue this refactoring instead of @yzotov if no one expresses concerns.
What do you think? cc: @HyukjinKwon , @cloud-fan , @jiangxb1987

**Comment by HyukjinKwon** [comment]
Please go ahead. I tihink the author has gone inactive.

**Comment by jiangxb1987** [comment]
I'm going to close this PR, related discussions is still going on at #19222

**Pull request closed without merging**
