### PR TITLE
[SPARK-39967][CORE] Use the successful array to count the number of t…

### PR DESCRIPTION
**Pull request by smallzhongfeng**
### What changes were proposed in this pull request?

When counting the number of successful tasks in the stage of spark, spark uses the indicator of `tasksSuccessful`, but in fact, the success or failure of tasks is based on the array of `successful`. Through the log, it is found that the number of failed tasks counted by `tasksSuccessful` is inconsistent with the number of failures stored in the array of `successful`. We should take `successful` as the standard.

### Why are the changes needed?

Statistics on the number of successful tasks is more accurate.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Use origin tests.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Spark 2.X is EOL. Mind checking if the same issue persists in `master` branch?

**Comment by dcoliversun** [comment]
I check `TaskSetManager.scala` in branch-master and logic about `tasksSuccessful` is same as branch-2.4. The problem is likely to exist.   
And I see @smallzhongfeng  have test codes in jira, would you like to patch these codes and check it again?

**Comment by mridulm** [comment]
`tasksSuccessful` is consistent with `tasksSuccessful` - can you point specifically to where it is not ?
It is expensive enumerate through the `successful` array to count number of successfully computed partitions.

**Comment by smallzhongfeng** [comment]
At present, for `master` branch, I can not recur the same situation. I agree with you.@mridulm  So, I'm going to close this PR temporarily.

**Pull request closed without merging**
