### PR TITLE
[SPARK-34431][CORE] Only load `hive-site.xml` once

### PR DESCRIPTION
**Pull request by MaxGekk**
### What changes were proposed in this pull request?
Lazily load Hive's configuration properties from `hive-site.xml` only once.

### Why are the changes needed?
It is expensive to parse the same file over and over.

### Does this PR introduce _any_ user-facing change?
Should not. The changes can improve performance slightly.

### How was this patch tested?
By existing test suites such as `SparkContextSuite`.

### CODE REVIEW

**Comment by MaxGekk** [comment]
@hvanhovell @HyukjinKwon @dongjoon-hyun @yaooqinn Could you review this PR, please.

**Review by hvanhovell — APPROVED** [review]
LGTM - thanks for fixing this

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @MaxGekk and @hvanhovell .

**Comment by dongjoon-hyun** [comment]
Merged to master/3.1/3.0.
cc @HyukjinKwon

**Comment by dongjoon-hyun** [comment]
I backported this to the old branches because this is related to the recent commit.
```
[SPARK-34346][CORE][SQL][3.0] io.file.buffer.size set by spark.buffer.size will override by loading hive-site.xml accidentally may cause perf regression
```

**Comment by dongjoon-hyun** [comment]
Ur, it seems that @MaxGekk 's co-authorship seems to be missed during merging. Sorry for that, @MaxGekk .

**Comment by MaxGekk** [comment]
@dongjoon-hyun nvm, actually the changes were made by Herman in private repo. I just open sourced them.

**Review by HyukjinKwon — COMMENTED** [review]
lgtm2

**Comment by mridulm** [comment]
Wont this not cause issues at executor with user provided hive-site.xml (and use of ChildFirstURLClassLoader)  if platform has a conflicting hive-site in classpath ?
Executor will force load of platform hive-site as part of its initialization (via `SparkHadoopUtil` use/initialization) - while things like TableReader will now depend on config populated with platform hive-site and not user overridden hive-site.

(Was looking at merged PR's, so if I am missing something, please let me know.)

**Comment by hvanhovell** [comment]
@mridulm `TableReader` do not use a `Configuration` that is created on the executor, it uses one that is send from the driver. Your point might still hold for the driver though. However I thought that child first class loader would apply to the entire spark application (including the SparkContext). This seems to be the case for spark-submit, but I might be missing something.

**Pull request closed without merging**
