### PR TITLE
[SQL][Minor] Skip unresolved expression for InConversion 

### PR DESCRIPTION
**Pull request by scwf**

### CODE REVIEW

**Comment by scwf** [comment]
Retest this please

**Comment by liancheng** [comment]
Would you mind to add a test case for this? Otherwise LGTM, thanks!

**Comment by liancheng** [comment]
The added clause makes the code path safer, but for now I couldn't think of a test case that makes the original code fail... I still tend to have this though.

**Comment by scwf** [comment]
yes, actually it is hard to give a test case for now, i met this issue on my inner branch with a tpcds sql.
that sql is invalid on the master branch so i can not add a test now.

**Comment by liancheng** [comment]
I see. I'm merging this to master since it looks pretty safe.

**Comment by liancheng** [comment]
I see. I'm merging this to master since it looks pretty safe.

**Comment by scwf** [comment]
@liancheng should this fix merge to branch-1.4 also?

**Comment by cloud-fan** [comment]
Found a test case for you...
https://issues.apache.org/jira/browse/SPARK-8588
And we should merge this fix into branch 1.4. cc @marmbrus @liancheng

**Comment by liancheng** [comment]
@scwf @cloud-fan Thanks! I'm merging this to branch-1.4.

**Pull request closed without merging**
