### PR TITLE
[SPARK-20633][SQL] FileFormatWriter wrap the FetchFailedException which breaks job's failover

### PR DESCRIPTION
**Pull request by lshmouse**
## What changes were proposed in this pull request?
Handle the fetch failed exception separately in FileFormatWriter.

## How was this patch tested?
manual tests

Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Comment by lshmouse** [comment]
Pending. I am formatting the pull name~

**Comment by mridulm** [comment]
This is not required anymore - post @squito's change.
Though it cant hurt I guess.

**Comment by squito** [comment]
yeah, this isn't a bug anymore, but lets fix it -- cleaner error msg, and at least it will be easier for folks to see the fix in the future, as multiple people have stumbled on it and not realized it was fixed.

@lshmouse can you update the description to reference the fix in SPARK-19276?

**Comment by squito** [comment]
Jenkins, ok to test

**Comment by squito** [comment]
Jenkins, retest this please

**Comment by felixcheung** [comment]
Please rebase to pick up fix for R tests

**Comment by squito** [comment]
Jenkins, retest this please

**Comment by squito** [comment]
since it seems @lshmouse is not updating this, I've resubmitted this here https://github.com/apache/spark/pull/18145, but all credit to the original author.

**Pull request closed without merging**
