### PR TITLE
[SPARK-10849][SQL] Adding field metadata property to override default jdbc data source type mapping.

### PR DESCRIPTION
**Pull request by sureshthalamati**
This patch allows users to override default type mapping of  data frame field to database column type when writing data frame to jdbc data sources.  

In some cases user may want to use specific database data type mapping for fields based on the database configuration (page size , type of table spaces ..etc) instead of the defaults.  For example large varchar size  for all the columns may not fit in row size limits , user may want to use mix of varchar , and clob types. Max precision supported in some database systems might be less than the spark decimal precision, in such cases user can use this option to adjust the decimal type precision , and scale to match the target database. 

Added a new field meta data property name    db.column.type .   I am not sure what is the convention for these type of property names. Please let me know it it needs to be changed. 

@rxin  @marmbrus

### CODE REVIEW

**Comment by marmbrus** [comment]
ok to test

**Comment by sureshthalamati** [comment]
Failed test is test_trainOn_predictOn (__main__.StreamingKMeansTest).   It seems to be unrelated to my changes.  Can we retest this please.

**Comment by sureshthalamati** [comment]
Thinking about this more , I realized current version of the patch may introduce SQL injection. I will update the pull request with a new version of the fix.

**Comment by sureshthalamati** [comment]
Updated the patch to address sql injection issue by removing space characters from the input.  Please review. 

@marmbrus @rxin

**Comment by sureshthalamati** [comment]
retest this please. 

Test  failure is unrelated to my changes. Failed test is org.apache.spark.sql.sources.JsonHadoopFsRelationSuite.test all data types - TimestampType. It passes in my environment.

**Comment by rick-ibm** [comment]
Thanks for addressing the SQL injection concerns, Suresh. LGTM.

**Comment by sureshthalamati** [comment]
Jenkins, retest this please.

**Comment by tristanreid** [comment]
Anyone know the status of this change?  Is there anything blocking, or was it superceded by something else?  Thanks...

**Comment by sureshthalamati** [comment]
Opened two new [WIP] PRs to fix this issue using different approaches.
https://github.com/apache/spark/pull/16208
https://github.com/apache/spark/pull/16209

Closing this PR.

**Pull request closed without merging**
