### PR TITLE
[MINOR][DOCS] Corrected spacing in structured streaming programming

### PR DESCRIPTION
**Pull request by mans2singh**
### What changes were proposed in this pull request?
There is no space between `with` and  `<code>` as shown below:

`... configured with<code>spark.sql.streaming.fileSource.cleaner.numThreads</code> ...`

### Why are the changes needed?
Added space

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Only documentation was changed and no code was change.

### CODE REVIEW

**Review by HyukjinKwon — COMMENTED** [review]
Looks good. Mind taking a look if there are some more typos in this page while we're here?

**Comment by mans2singh** [comment]
@HyukjinKwon - Thanks for your review.  

I did not find any other typo but did see that in this section, there are three notes - the first is labeled `NOTE:` but other two are `NOTE 2:` and `NOTE 3:`.  If you prefer I can change `NOTE: ` to `NOTE 1:` for consistency.  

Please let me know if you have any other advice.

Thanks again.

**Review by srowen — APPROVED** [review]

**Comment by srowen** [comment]
Jenkins test this please

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master, branch-3.2, branch-3.1 and branch-3.0.

**Pull request closed without merging**
