### PR TITLE
[SPARK-10300] [BUILD] [TESTS] Add support for test tags in run-tests.py.

### PR DESCRIPTION
**Pull request by vanzin**

### CODE REVIEW

**Comment by vanzin** [comment]
Re-posting previous PR with a fix for the issue that caused tests to fail in other PRs. For the changes since the last PR, see only the second commit.

I'm not super happy with needing the new module, but I couldn't find an alternative that still allowed us to tag JUnit tests. The extra noise to add the dependencies to all other poms also irks me a little bit.

/cc @pwendell to see if you have a better suggestion...

**Comment by vanzin** [comment]
retest this please

**Comment by vanzin** [comment]
any comments on the new approach?

**Comment by vanzin** [comment]
retest this please

**Comment by vanzin** [comment]
I'll run the tests once again and push this, since I haven't seen any feedback on top of the previous PR. retest this please

**Comment by mengxr** [comment]
LGTM. Merged into master. Thanks! There might be a small issue with the default value. I will test it locally and send follow-up PR if necessary.

**Comment by JoshRosen** [comment]
@mengxr, looks like the merge commit didn't get pushed (or ASF -> Git mirroring is lagging)?

**Comment by vanzin** [comment]
Yes, this was not pushed. I'll push this later if it's still around.

**Comment by vanzin** [comment]
ok merging.

**Pull request closed without merging**
