### PR TITLE
[SPARK-23242][SS][Tests]Don't run tests in KafkaSourceSuiteBase twice

### PR DESCRIPTION
**Pull request by zsxwing**
## What changes were proposed in this pull request?

KafkaSourceSuiteBase should be abstract class, otherwise KafkaSourceSuiteBase will also run.

## How was this patch tested?

Jenkins

### CODE REVIEW

**Comment by tdas** [comment]
LGTM. My bad, I should caught this in the original PR that @jose-torres made.

**Comment by zsxwing** [comment]
retest this please

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by zsxwing** [comment]
Thanks! Merging to master and 2.3.

**Pull request closed without merging**
