### PR TITLE
[SPARK-37796][SQL] ByteArrayMethods arrayEquals should fast skip the check of aligning with unaligned platform

### PR DESCRIPTION
**Pull request by ulysses-you**
### What changes were proposed in this pull request?

The method `arrayEquals` in `ByteArrayMethods` is critical function which is used in `UTF8String.` `equals`, `indexOf`,`find` etc.

After SPARK-16962, it add the complexity of aligned. It would be better to fast sikip the check of aligning if the platform is unaligned.

### Why are the changes needed?

Improve the performance.

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

Pass CI. Run the benchmark using [unaligned-benchmark](https://github.com/ulysses-you/spark/commit/d14d4bfcfeddcf90ccfe7cc3f6cda426d6d6b7e5), and here is the benchmark result:

[JDK8](https://github.com/ulysses-you/spark/actions/runs/1639852573)
```
================================================================================================
byte array equals
================================================================================================

OpenJDK 64-Bit Server VM 1.8.0_312-b07 on Linux 5.11.0-1022-azure
Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz
Byte Array equals:                        Best Time(ms)   Avg Time(ms)   Stdev(ms)    Rate(M/s)   Per Row(ns)   Relative
------------------------------------------------------------------------------------------------------------------------
Byte Array equals fast                             1322           2222         NaN        121.0           8.3       1.0X
Byte Array equals                                  3378           3381           3         47.4          21.1       0.4X
```

[JDK11](https://github.com/ulysses-you/spark/actions/runs/1639853330)
```
================================================================================================
byte array equals
================================================================================================

OpenJDK 64-Bit Server VM 11.0.13+8-LTS on Linux 5.11.0-1022-azure
Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz
Byte Array equals:                        Best Time(ms)   Avg Time(ms)   Stdev(ms)    Rate(M/s)   Per Row(ns)   Relative
------------------------------------------------------------------------------------------------------------------------
Byte Array equals fast                             1860           1891          15         86.0          11.6       1.0X
Byte Array equals                                  2913           2921           8         54.9          18.2       0.6X
```

[JDK17](https://github.com/ulysses-you/spark/actions/runs/1639853938)
```
================================================================================================
byte array equals
================================================================================================

OpenJDK 64-Bit Server VM 17.0.1+12-LTS on Linux 5.11.0-1022-azure
Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz
Byte Array equals:                        Best Time(ms)   Avg Time(ms)   Stdev(ms)    Rate(M/s)   Per Row(ns)   Relative
------------------------------------------------------------------------------------------------------------------------
Byte Array equals fast                             1543           1602          39        103.7           9.6       1.0X
Byte Array equals                                  3027           3029           1         52.9          18.9       0.5X
```

### CODE REVIEW

**Comment by srowen** [comment]
I find that fairly convincing for x86. I'm worried about ARM - not just performance but correctness. ARMv7 supports unaligned access; ARMv5 does not. But v7 seems to have some 'gotchas' that direct access like this may hit. 

If ARM JDKs show up as 'aligned' then I think this is fine, but that's what I don't know right now. Do you have any easy way to check that?

**Comment by ulysses-you** [comment]
I'm not very familiar with arm stuff, cc @Yikun if you have time to take a look, thank you !

**Comment by Yikun** [comment]
Thanks ping me.

- Docker provide [multiarch support now](https://docs.docker.com/desktop/multi-arch/#multi-arch-support-on-docker-desktop), that means you can run any arch docker images in Docker in your host (even if it's x86).
- Docker also provide some [offical images for multiarch](https://github.com/docker-library/official-images#architectures-other-than-amd64)

So, if you want to do check on arm64v7, you could just run it as below:
```
# The example to emulate the arm v7 in x86.
root@yikun-x86:~# uname -a
Linux yikun-x86 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
root@yikun-x86:~# docker run -ti arm32v7/openjdk bash
root@afa30defa503:/# uname -a
Linux afa30defa503 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 armv7l GNU/Linux
```

**Comment by Yikun** [comment]
I also ran the performance test on aarch64 with jdk8, here is the result, also have some improvement:

```
# Linux yikun-arm 5.4.0-89-generic #100-Ubuntu SMP Fri Sep 24 14:29:20 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
OpenJDK 64-Bit Server VM 1.8.0_312-8u312-b07-0ubuntu1~20.04-b07 on Linux 5.4.0-89-generic
Byte Array equals:                        Best Time(ms)   Avg Time(ms)   Stdev(ms)    Rate(M/s)   Per Row(ns)   Relative
------------------------------------------------------------------------------------------------------------------------
Byte Array equals fast                             2832           4607         294         56.5          17.7       1.0X
Byte Array equals                                  8660           8880         213         18.5          54.1       0.3X
```

[1] https://github.com/Yikun/spark/runs/4697868757?check_suite_focus=true

**Comment by Yikun** [comment]
I also triggered the complete test on `aarch64/arm64v8`: https://github.com/Yikun/spark/pull/56 .

Hope it helps.

**Comment by ulysses-you** [comment]
thank you @Yikun , I try to check the unaligned with armv7 using follow command and it works as expected:

```shell
root@5d25e6cb0f3e:/# uname -a
Linux 5d25e6cb0f3e 5.10.76-linuxkit #1 SMP Mon Nov 8 10:21:19 UTC 2021 armv7l GNU/Linux
root@5d25e6cb0f3e:/# jshell
Jan 04, 2022 1:50:10 PM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
|  Welcome to JShell -- Version 11.0.1
|  For an introduction type: /help intro

jshell> System.getProperty("os.arch", "");
$1 ==> "arm"

jshell>

jshell> import java.lang.reflect.Field;

jshell>

jshell> Class<?> bitsClass = Class.forName("java.nio.Bits", false, ClassLoader.getSystemClassLoader());
bitsClass ==> class java.nio.Bits

jshell> Field unalignedField = bitsClass.getDeclaredField("UNALIGNED");
unalignedField ==> private static boolean java.nio.Bits.UNALIGNED

jshell> unalignedField.setAccessible(true);

jshell> unalignedField.getBoolean(null);
$6 ==> false
```

It seems no easy way to check with armv5. But I think it should return something like `arm` or `arm32` which is also aligned. Do you have any thought ? @srowen

**Review by srowen — APPROVED** [review]
That seems pretty convincing to me

**Comment by srowen** [comment]
Oh, is it possible to add the benchmark suite you ran to this PR?

**Comment by ulysses-you** [comment]
combined the benchmark in `ByteArrayBenchmark.scala` and also updated the benchmark result

**Review by Yikun — APPROVED** [review]
LGTM, thanks!

**Comment by srowen** [comment]
Merged to master

**Comment by ulysses-you** [comment]
thank you again ! @srowen @Yikun

**Pull request closed without merging**
