### PR TITLE
[SPARK-12377][Python][Wrong implementation for Row.__call__ in pyspark]

### PR DESCRIPTION
**Pull request by somideshmukh**
Made chnages in types.py file to change "return _create_row(self, args)" to return create_row(self.fields_, args)

### CODE REVIEW

**Comment by JoshRosen** [comment]
Could you add a regression test for this?

**Comment by JoshRosen** [comment]
I see that you've updated this, but this still needs test code which exercises this function.

**Comment by HyukjinKwon** [comment]
I submitted a PR for this in https://github.com/apache/spark/pull/10356 because I guess the author is not answering for about four months.

**Comment by HyukjinKwon** [comment]
@JoshRosen Sorry, it was my mistake. It seems it works as expected and not an issue.

```python
row = Row("f1", "f2")
>>> row(1, 2)
Row(f1=1, f2=2)
```

**Pull request closed without merging**
