### PR TITLE
[SPARK-23907] Removes regr_* functions in functions.scala

### PR DESCRIPTION
**Pull request by rxin**
## What changes were proposed in this pull request?
This patch removes the various regr_* functions in functions.scala. They are so uncommon that I don't think they deserve real estate in functions.scala. We can consider adding them later if more users need them.

## How was this patch tested?
Removed the associated test case as well.

### CODE REVIEW

**Comment by rxin** [comment]
cc @gatorsmile @mgaido91

**Review by gatorsmile — COMMENTED** [review]
LGTM

**Comment by HyukjinKwon** [comment]
Thing is, I am a bit confused when to add it to other APIs. I thought if it's expected to be less commonly used, it shouldn't be added at the first place. We have UDFs.

I have been a bit confused of some functions specifically not added into other APIs. If that's worth being added in an API, I thought it makes sense to add it to other APIs too. Is there a reason to add them to SQL side specifically?

**Comment by HyukjinKwon** [comment]
I am asking this to use the same judgement for when to add it.

**Comment by rxin** [comment]
Adding it to sql would allow it to be available everywhere (through expr)
right?

**Comment by HyukjinKwon** [comment]
Yup, then why not just deprecate other functions in other APIs for 3.0.0, and promote the usage of expr?

**Comment by rxin** [comment]
Better compile time error. Plus a lot of people are already using these.

**Comment by HyukjinKwon** [comment]
Just had a short talk with Reynold. LGTM too. thanks for bearing with me.

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by mgaido91** [comment]
@rxin I also always had some problems in understanding which functions are available and which not. I think it is quite confusing for a user. I am wondering: what do you think if we automatically generate this file in order to make all them available to users? In this way probably we don't have the huge maintenance effort exposing all of them to users.

**Pull request closed without merging**
