### PR TITLE
[SPARK-40057][PYTHON][DOCS] Cleanup "<BLANKLINE>" in doctest

### PR DESCRIPTION
**Pull request by Yikun**
### What changes were proposed in this pull request?
Cleanup `<BLANKLINE>` in doctest

### Why are the changes needed?
See https://github.com/apache/spark/pull/37465#discussion_r943071168, we'd better to cleanup all `<BLANKLINE>` in doctest to make doctest code more clear.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
CI passed

### CODE REVIEW

**Comment by Yikun** [comment]
cc @HyukjinKwon

**Comment by srowen** [comment]
Is there any functional difference in the tests afterwards?

**Comment by Yikun** [comment]
@srowen No, it just only makes the doctest code more clean.

And I think pyspark doctest should ignore blackline match, because it's useless and might cost some dev's time on the text match game. So flag in bottom doctest should be a recommand way.

For users, there is no diff.

**Comment by HyukjinKwon** [comment]
It's just about PySpark documentation style actually. It will remove the `<BLANKLINE>` in PySpark API references so it's sort of improvement in the docs.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
