### PR TITLE
[SPARK-27291][SQL] PartitioningAwareFileIndex: Filter out empty files on listing files

### PR DESCRIPTION
**Pull request by gengliangwang**
## What changes were proposed in this pull request?

In https://github.com/apache/spark/pull/23130, all empty files are excluded from target file splits in `FileSourceScanExec`.
In File source V2, we should keep the same behavior.

This PR suggests to filter out empty files on listing files in `PartitioningAwareFileIndex` so that the upper level doesn't need to handle them.
## How was this patch tested?

Unit test

### CODE REVIEW

**Comment by gengliangwang** [comment]
@cloud-fan @HyukjinKwon @dongjoon-hyun

**Review by HyukjinKwon — APPROVED** [review]

**Review by MaxGekk — COMMENTED** [review]
Looks like the filtered out empty files can impact on calculation of `maxSplitBytes`: 
https://github.com/apache/spark/blob/c0632cec04e5b0f3fb3c3f27c21a2d3f3fbb4f7e/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/FilePartition.scala#L92 . Probably, we need to handle the case there or filter empty files earlier.

**Comment by gengliangwang** [comment]
@MaxGekk Thanks for the suggestion. I have updated the PR.

**Review by MaxGekk — APPROVED** [review]
LGTM

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Pull request closed without merging**
