### PR TITLE
[SPARK-5754] Spark AM not launching on Windows

### PR DESCRIPTION
**Pull request by dharmeshkakadia**
Properly escaping for windows platform as well - single quote -> escaped double quote

### CODE REVIEW

**Comment by dharmeshkakadia** [comment]
@srowen Can you please help me merging this? This is a trivial patch.

**Comment by srowen** [comment]
I don't use Windows at all, so I am not qualified to evaluate this one.

**Comment by dharmeshkakadia** [comment]
@srowen Sorry. I saw your comment on the issue and assumed it. This is my first patch to Spark. How can I find committer who can review this?

**Comment by srowen** [comment]
I usually find who may have written or touched the code last...
https://github.com/apache/spark/blame/master/yarn/src/main/scala/org/apache/spark/deploy/yarn/YarnSparkHadoopUtil.scala

@vanzin I don't suppose you have an opinion? This one may be hard to fix for Windows.

**Comment by vanzin** [comment]
Hmm, I don't think this is right. Quoting on Windows is completely different from bash. What you're doing here is just changing the way the quoted string is wrapped, but not changing the quoting itself. That will only work for strings that do not have any characters that need to be quotes.

On top of that, if you quote a string on Windows when it doesn't need to be quoted, Windows does not strip the quotes from it (aren't batch scripts awesome?).

For an example of quoting on Windows, see:
https://github.com/apache/spark/blob/3697232b7d438979cc119b2a364296b0eec4a16a/launcher/src/main/java/org/apache/spark/launcher/CommandBuilderUtils.java#L262

So, even though I don't have a YARN-on-Windows install I can even try this on, I'm pretty sure it doesn't work for anything but the simplest use cases.

**Comment by dharmeshkakadia** [comment]
I have checked it on windows on yarn and seems to be working. But I agree, that this might not be complete fix. Do we want to check the platform/OS and apply quoting similar to CommandBuilderUtils ?I would like to get the issue fixed and I am willing to work on this. I would love to know if you (or others) have ideas for better fix ?

**Comment by cbvoxel** [comment]
This Change will indeed work for very simple cases on Windows, but I would assume this could break logic elsewhere? If not, it still doesn't deal with the situation that for example '%' must be escaped to '%%'. I have worked on a fix to include a different implementation of escapeForShell for the case that 
Utils.isWindows is true. I still need to check its functionality, but at least all logic can rely on the current implementation. Windows is obviously not supported yet, so we need to build this step by step, while not interfering with the rest.

**Comment by vanzin** [comment]
> Do we want to check the platform/OS and apply quoting similar to CommandBuilderUtils ?

Yes, because that would be the correct fix. I'm not sure you can get as far as running YarnClusterSuite on Windows, but that test suite has command line arguments that would break the app with wrong escaping. You could try to run the app with those args on Windows and check out how it behaves.

In the meantime, since this PR doesn't really fix the problem in the correct way, do you mind closing it?

**Comment by cbvoxel** [comment]
@vanzin why don't we use CommandBuilderUtils then? It is not accessible, could that be changed? Or just copy&paste? 
I see however, that 
-XX:OnOutOfMemoryError='kill %p'
will still break, since CommandBuilderUtils also doesn't escape the '%' and (so far I can tell) doesn't add double quotes because of the ' sign.

**Comment by dharmeshkakadia** [comment]
Running Spark-on-Yarn-on-Windows requires to fixes : (putting it here for reference)
1. single quote to double quote (included in the patch)
2. removing "-XX:OnOutOfMemoryError='kill %p'" being appended to the command line. 

After making these changes, I am able to successfully run Spark-on-Yarn-on-Windows. I have not been able to run testsuite on windows yet, because the dev infra (run-test script etc) are not runnable on windows. Though, I ran the full suite on Linux with these changes, which didn't have any trouble.

As suggested by others, it might require other changes that are not clear to me. I will close this for now, but as previously said, I am willing to work on the better fix - if we have agreement on fix.

**Comment by vanzin** [comment]
For reference:

> 1. single quote to double quote (included in the patch)

This is not correct. The code needs to do correct escaping for Windows, which is not just replacing single quotes with double quotes.

**Comment by dharmeshkakadia** [comment]
Thanks. I assumed it is a correct fix because spark examples and few other simple spark programs I have tried, worked with it.

**Comment by cbvoxel** [comment]
@dharmeshkakadia thank you from me for your action. I'm trying hard myself to find a satisfyable solution ;) (still failing though haha)

But I am confident that I'll work out eventually!

**Comment by dharmeshkakadia** [comment]
@cbvoxel Thanks for your insights ! I am trying Hive-on-Spark-on-Yarn-on-Windows :smile: Let me know if I can help in anyway, though I am fairly new to the Spark code base .

**Pull request closed without merging**
