### PR TITLE
[SPARK-39887][SQL][3.2] RemoveRedundantAliases should keep aliases that make the output of projection nodes unique

### PR DESCRIPTION
**Pull request by peter-toth**
### What changes were proposed in this pull request?
Keep the output attributes of a `Union` node's first child in the `RemoveRedundantAliases` rule to avoid correctness issues.

### Why are the changes needed?
To fix the result of the following query:
```
SELECT a, b AS a FROM (
  SELECT a, a AS b FROM (SELECT a FROM VALUES (1) AS t(a))
  UNION ALL
  SELECT a, b FROM (SELECT a, b FROM VALUES (1, 2) AS t(a, b))
)
```
Before this PR the query returns the incorrect result: 
```
+---+---+
|  a|  a|
+---+---+
|  1|  1|
|  2|  2|
+---+---+
```
After this PR it returns the expected result:
```
+---+---+
|  a|  a|
+---+---+
|  1|  1|
|  1|  2|
+---+---+
```

### Does this PR introduce _any_ user-facing change?
Yes, fixes a correctness issue.

### How was this patch tested?
Added new UTs.

### CODE REVIEW

**Comment by peter-toth** [comment]
cc @cloud-fan

**Review by cloud-fan — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Could you re-trigger CI, @peter-toth ? Linter failure is okay, but there exists SQL failure.

Screen Shot 2022-08-12 at 4 02 40 PM

**Comment by peter-toth** [comment]
> Could you re-trigger CI, @peter-toth ? Linter failure is okay, but there exists SQL failure.
> 
> Screen Shot 2022-08-12 at 4 02 40 PM

Thanks @dongjoon-hyun for checking the results. I've rerun the tests and only `[Linters, licenses, dependencies and documentation generation` failed this time.

**Comment by dongjoon-hyun** [comment]
Thank you. I confirmed that, @peter-toth .
Merged to branch-3.2.

**Comment by dongjoon-hyun** [comment]
Thank you, @peter-toth and @cloud-fan

**Pull request closed without merging**
