### PR TITLE
[SPARK-45799][SQL] Remove some unused method in QueryExecutionErrors & QueryCompilationErrors

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to clear some unused method in `QueryExecutionErrors` &`QueryCompilationErrors` and related error classes in `error-classes.json`.

### Why are the changes needed?
Make code clear.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Review by MaxGekk — APPROVED** [review]

**Comment by MaxGekk** [comment]
@panbingkun Could you remove `hiveCreatePermanentFunctionsUnsupportedError` and `_LEGACY_ERROR_TEMP_1221` since you are here, please.

**Comment by panbingkun** [comment]
> @panbingkun Could you remove `hiveCreatePermanentFunctionsUnsupportedError` and `_LEGACY_ERROR_TEMP_1221` since you are here, please.

Sure, done.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @panbingkun and @MaxGekk .
Merged to master.

**Review by beliefer — COMMENTED** [review]
Late LGTM.

**Pull request closed without merging**
