### PR TITLE
[SPARK-44041][BUILD] Upgrade Ammonite to 2.5.9

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr is aim to upgrade ammonite from 2.5.8 to 2.5.9. 

### Why are the changes needed?
Ammonite 2.5.9  is used to support Scala 2.12.18 and Scala 2.13.11:
- https://github.com/com-lihaoyi/Ammonite/compare/2.5.8...2.5.9

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass GitHub Actions

### CODE REVIEW

**Comment by LuciferYang** [comment]
Test first

**Comment by LuciferYang** [comment]
cc @dongjoon-hyun FYI

**Review by dongjoon-hyun — COMMENTED** [review]
Finally! It's great!

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM (Pending CIs).

**Comment by LuciferYang** [comment]
Thanks @dongjoon-hyun ~

**Pull request closed without merging**
