### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by julienbaley**
disvoered => discovered

### CODE REVIEW

**Comment by srowen** [comment]
OK. Generally if you can take some time to look around for other typos at the same time, that'd be helpful. That way we don't end up with loads of tiny PRs. There may be no other obvious ones.

**Comment by julienbaley** [comment]
Arguably, that should have bee, the job of the people who reviewed the commit. ;-)

**Comment by srowen** [comment]
Definitely so. It falls through the cracks and some of this is from ancient history.

**Comment by julienbaley** [comment]
This one is mid-November 2015.
Just found it because I'm trying to solve some problem I have with "Conflicting directory structures detected. Suspicious paths" for a list of paths that are identical except for the last segment which contains an "=" (used to work in 1.5.2)

**Comment by rxin** [comment]
Thanks - I'm going to merge this.

**Pull request closed without merging**
