### PR TITLE
[SPARK-13439] [Mesos] Document that spark.mesos.uris is comma-separated

### PR DESCRIPTION
**Pull request by mgummelt**

### CODE REVIEW

**Comment by olarayej** [comment]
@mgummelt I'm guessing you got the wrong PR number? Could you please fix this?

**Comment by dragos** [comment]
The failure is spurious. LGTM.

**Comment by mgummelt** [comment]
@olarayej: Fixed.  Thanks.

**Comment by mgummelt** [comment]
retest this please

**Comment by srowen** [comment]
Jenkins, test this please

**Comment by srowen** [comment]
Merged to master/1.6

**Pull request closed without merging**
