### PR TITLE
[WebUI] Remove debug feature for vis.js

### PR DESCRIPTION
**Pull request by sarutak**
`vis.min.js` refers `vis.map` and this even refers `vis.js` which is used for debug `vis.js` but this debug feature is not needed for Spark itself.

This issue is really minor so I don't file this in JIRA.

/CC @andrewor14

### CODE REVIEW

**Comment by sarutak** [comment]
retest this please.

**Comment by JoshRosen** [comment]
This won't actually save any space in the repo, since the old bits are going to stay around in the Git history. And it shouldn't make a difference for page load times?  If that's the case, is there an issue with leaving it as-is?

**Comment by sarutak** [comment]
@JoshRosen Thanks for your comment.
Actually, this issue is suggested in #5947.
If there is `vis.map` without `vis.js` (not `vis.min.js`), we get status code 404 when we use browser-embeded debug tools because `vis.js` is absent.

But in #5947, thare is a suggestion that including `vis.js` in Spark source tree is not reasonable so I decided to remove the usage.

**Comment by andrewor14** [comment]
Yeah right now it actually causes a JS error if you open the developer console because `vis.js` is not found.

**Comment by JoshRosen** [comment]
SGTM.  @andrewor14, want to merge this?

**Comment by andrewor14** [comment]
Ok. Master 1.4.

**Pull request closed without merging**
