### PR TITLE
[SPARK-34508][SQL][TEST] Skip HiveExternalCatalogVersionsSuite if network is down

### PR DESCRIPTION
**Pull request by cloud-fan**
### What changes were proposed in this pull request?

It's possible that the network is down when running Spark tests, and it's annoying to see `HiveExternalCatalogVersionsSuite` keep failing.

This PR proposes to skip this test suite if we can't get the latest Spark version from the Apache website.

### Why are the changes needed?

Make the Spark tests more robust.

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

N/A

### CODE REVIEW

**Comment by cloud-fan** [comment]
cc @dongjoon-hyun @HyukjinKwon

**Comment by cloud-fan** [comment]
another idea is to not run this test suite in PR builders, but only run it in the background QA jobs. I know jenkins have background QA jobs, but not sure about github actions.

**Comment by cloud-fan** [comment]
Another idea is to treat it like the JDBC docker tests and only run it by requests. TBH I haven't seen any bugs caught by this test suite yet after so many years and probably we don't need to run it in every PR builder, as this test triggers a lot of network traffic.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.
I agree with this approach, @cloud-fan .

**Comment by dongjoon-hyun** [comment]
Merged to master/3.1.

**Comment by HyukjinKwon** [comment]
LGTM2

**Pull request closed without merging**
