### PR TITLE
Added missing utility method

### PR DESCRIPTION
**Pull request by mispecto**
Without this method it's impossible to create Kafka direct stream without offsets but with custom message handler function.

### CODE REVIEW

**Comment by hvanhovell** [comment]
@spektom the title is not really informative. Could you improve the title, and prepend it with the relevant JIRA ticket (please create one if you haven't done that yet) and Subproject name, e.g.: `[SPARK-13xyz][STREAMING] Create Kafka direct stream without....`

**Comment by srowen** [comment]
I don't think we want yet another huge overload. Can't you pass an empty map of offsets? if not, let's just support that. @koeninger

**Comment by koeninger** [comment]
Kafkacluster methods are public now, you can do this yourself.
I think its fine to just have two overloads, the easy mode and the flexible mode.

**Comment by koeninger** [comment]
Existing ticket https://issues.apache.org/jira/plugins/servlet/mobile#issue/SPARK-13106

**Comment by JoshRosen** [comment]
+1 on this PR being updated to have a more informative title.

**Comment by HyukjinKwon** [comment]
+1 (maybe by following this, https://cwiki.apache.org/confluence/display/SPARK/Contributing+to+Spark)

**Comment by srowen** [comment]
@spektom please close this PR if it won't be updated

**Pull request closed without merging**
