### PR TITLE
[SPARK-47627][SQL] Add SQL MERGE syntax to enable schema evolution

### PR DESCRIPTION
**Pull request by xupefei**
### Why are the changes needed?

This PR introduces a syntax `WITH SCHEMA EVOLUTION` to the SQL MERGE command, which allows the user to specify automatic schema evolution for a specific operation.

```sql
MERGE WITH SCHEMA EVOLUTION
INTO tgt
USING src
ON ...
WHEN ...
```

When `WITH SCHEMA EVOLUTION` is specified, schema evolution-related features must be turned on for this single statement and only in this statement.

Spark is only responsible for recognizing the existence or absence of the syntax `WITH SCHEMA EVOLUTION`, and the result is passed down to the MERGE command. Data sources must respect the syntax and give appropriate reactions: turn on features that are categorised as "schema evolution" when the syntax does exist. For example, when the underlying table is Delta Lake, the feature "mergeSchema" will be turned on (see https://github.com/delta-io/delta/blob/c41977db3529a3139d6306abe5ded161f070982a/spark/src/main/scala/org/apache/spark/sql/delta/DeltaAnalysis.scala#L538).

### Does this PR introduce _any_ user-facing change?

Yes, see the previous section.

### How was this patch tested?

New tests.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Review by n-young-db — APPROVED** [review]
Stamping, but you probably need a Spark committer to review this.

**Review by srielau — APPROVED** [review]

**Comment by gengliangwang** [comment]
@xupefei could you provide more details in the PR description? For example, what is the difference with/without  `WITH SCHEMA EVOLUTION`

**Comment by xupefei** [comment]
> @xupefei could you provide more details in the PR description? For example, what is the difference with/without `WITH SCHEMA EVOLUTION`

Hi @gengliangwang, I added to the PR description as you advised. Please have a look!

**Review by gengliangwang — APPROVED** [review]

**Comment by gengliangwang** [comment]
Thanks, merging to master

**Pull request closed without merging**
