### PR TITLE
[SPARK-33736][SQL] Handle MERGE in ReplaceNullWithFalseInPredicate

### PR DESCRIPTION
**Pull request by aokolnychyi**
### What changes were proposed in this pull request?

This PR handles merge operations in `ReplaceNullWithFalseInPredicate`.

### Why are the changes needed?

These changes are needed to match what we already do for delete and update operations.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

This PR extends existing tests to cover merge operations.

### CODE REVIEW

**Comment by aokolnychyi** [comment]
cc @dongjoon-hyun @HyukjinKwon @cloud-fan @viirya @sunchao

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @aokolnychyi .

**Review by viirya — APPROVED** [review]
lgtm

**Comment by dongjoon-hyun** [comment]
Thank you all. Merged to master.

**Review by HyukjinKwon — COMMENTED** [review]
Looks there's no controversial change. Looks making sense to me too.

**Comment by aokolnychyi** [comment]
My late thank you to everyone for reviewing, @HyukjinKwon @dongjoon-hyun @viirya!

**Pull request closed without merging**
