### PR TITLE
[SPARK-13207] [SQL] Make partitioning discovery ignore _SUCCESS files.

### PR DESCRIPTION
**Pull request by yhuai**
If a _SUCCESS appears in the inner partitioning dir, partition discovery will treat that _SUCCESS file as a data file. Then, partition discovery will fail because it finds that the dir structure is not valid. We should ignore those `_SUCCESS` files.

In future, it is better to ignore all files/dirs starting with `_` or `.`. This PR does not make this change. I am thinking about making this change simple, so we can consider of getting it in branch 1.6.

To ignore all files/dirs starting with `_` or `, the main change is to let ParquetRelation have another way to get metadata files. Right now, it relies on FileStatusCache's cachedLeafStatuses, which returns file statuses of both metadata files (e.g. metadata files used by parquet) and data files, which requires more changes.

https://issues.apache.org/jira/browse/SPARK-13207

### CODE REVIEW

**Comment by davies** [comment]
LGTM, could you rebase this PR?

**Comment by yhuai** [comment]
sure

**Comment by yhuai** [comment]
Updated. The previous PR did not handle the cases of listing files through spark jobs. I also fixed that part and added the test.

**Comment by davies** [comment]
LGTM

**Comment by yhuai** [comment]
test this please

**Comment by yhuai** [comment]
Thanks. I am merging this to master.

**Pull request closed without merging**
