### PR TITLE
[SPARK-6015] fix links to source code in Python API docs 

### PR DESCRIPTION
**Pull request by davies**

### CODE REVIEW

**Comment by jkbradley** [comment]
LGTM, worked on my machine

**Comment by rxin** [comment]
Merging in master. Thanks!

**Comment by jkbradley** [comment]
@rxin  Uh, this was meant to be a backport for branch-1.2.  It was already fixed in master by [https://github.com/apache/spark/pull/4756]

**Comment by rxin** [comment]
Yup  I meant 1.2... I accidentally also cherry picked it into 1.3, which is a noop.

**Comment by andrewor14** [comment]
Hey @davies can you close this since it's already merged?

**Pull request closed without merging**
