### PR TITLE
[SPARK-48875][COMMON] Variant support quick exit in getFieldByKey

### PR DESCRIPTION
**Pull request by xuzifu666**
Variant support quick exit in getFieldByKey

### What changes were proposed in this pull request?

Variant##getFieldByKey  search part

### Why are the changes needed?

Quick exit in getFieldByKey to improve perfermance.

### CODE REVIEW

**Comment by xuzifu666** [comment]
@yaooqinn PTAL

**Comment by yaooqinn** [comment]
cc @cloud-fan

**Comment by xuzifu666** [comment]
CI error seems not related to the changed code

**Comment by xuzifu666** [comment]
@cloud-fan could you have a review or close the pr plz? Thanks

**Comment by cloud-fan** [comment]
cc @gene-db

**Comment by cloud-fan** [comment]
@xuzifu666 it's better to ping the author of the code you are touching in your PR.

**Comment by chenhao-db** [comment]
I don't feel it has enough benefit to do so.

**Comment by gene-db** [comment]
It is unclear how much this can help. Are there any benchmarks that show significant performance benefits? What would be an example scenario where this would be beneficial? Thanks!

**Comment by xuzifu666** [comment]
OK close it first. @cloud-fan @yaooqinn @chenhao-db @gene-db

**Pull request closed without merging**
