### PR TITLE
[SPARK-12039] [TESTS] [test-hadoop1.0] Add maven and apache repos to remote repos when we want to download jars for metadata hive.

### PR DESCRIPTION
**Pull request by yhuai**
https://issues.apache.org/jira/browse/SPARK-12039

### CODE REVIEW

**Comment by JoshRosen** [comment]
Yep, this [looks pretty flaky](https://spark-tests.appspot.com/tests/org.apache.spark.sql.hive.HiveSparkSubmitSuite/SPARK-9757%20Persist%20Parquet%20relation%20with%20decimal%20column).

I noticed something slightly funny when looking at the test logs:

```
 2015-11-28 14:53:11.15 - stderr> 15/11/28 14:53:11 INFO TestHiveContext: default warehouse location is /user/hive/warehouse
  2015-11-28 14:53:11.168 - stderr> 15/11/28 14:53:11 INFO TestHiveContext: Initializing HiveMetastoreConnection version 0.13.1 using maven.
  2015-11-28 14:53:11.248 - stderr> Ivy Default Cache set to: /home/jenkins/.ivy2/cache
  2015-11-28 14:53:11.248 - stderr> The jars for the packages stored in: /home/jenkins/.ivy2/jars
  2015-11-28 14:53:11.268 - stderr> http://www.datanucleus.org/downloads/maven2 added as a remote repository with the name: repo-1
  2015-11-28 14:53:11.306 - stderr> :: loading settings :: url = jar:file:/home/jenkins/workspace/Spark-1.6-Maven-pre-YARN/HADOOP_VERSION/1.2.1/label/spark-test/assembly/target/scala-2.10/spark-assembly-1.6.0-SNAPSHOT-hadoop1.2.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
  2015-11-28 14:53:11.356 - stderr> org.apache.hive#hive-metastore added as a dependency
  2015-11-28 14:53:11.356 - stderr> org.apache.hive#hive-exec added as a dependency
  2015-11-28 14:53:11.356 - stderr> org.apache.hive#hive-common added as a dependency
  2015-11-28 14:53:11.356 - stderr> org.apache.hive#hive-serde added as a dependency
```

Here, `/home/jenkins/.ivy2/cache` is being used as the Ivy cache, but that cache may also be accessed by other concurrent builds running on the same machine, causing race-conditions. Instead of using that cache, it would be better if we could somehow configure Jenkins such that the per-workspace isolated Ivy caches are used (so the cache path would be something like `/home/sparkivy/7//home/jenkins/workspace/Spark-Master-SBT/AMPLAB_JENKINS_BUILD_PROFILE/hadoop1.0/label/spark-test/.ivy2`). I can take a shot at this later.

**Comment by yhuai** [comment]
test this please

**Comment by yhuai** [comment]
test this please

**Comment by yhuai** [comment]
https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/46857/consoleFull is execurted by worker 3. Let me find another worker.

**Comment by yhuai** [comment]
https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/46858/consoleFull is in worker 6.

**Comment by yhuai** [comment]
I am closing it.

**Pull request closed without merging**
