### PR TITLE
[SPARK-50695][SQL] Alter table with properties check for empty string

### PR DESCRIPTION
**Pull request by xuzifu666**
### What changes were proposed in this pull request?

Alter table with set properties check for key value

### Why are the changes needed?

Currently sparksql not gurad for empty key properties such as '' = 'bb' which is not right

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

DDLSuite: Test alter table command with empty key

### Was this patch authored or co-authored using generative AI tooling?

No

### CODE REVIEW

**Comment by xuzifu666** [comment]
@yaooqinn PTAL if have free time, Thanks

**Comment by yaooqinn** [comment]
What's the problem you met with an empty string key?

**Comment by xuzifu666** [comment]
> What's the problem you met with an empty string key?

In platform indicate this would mistake for users, and this is not fitable for user to set empty key. @yaooqinn

**Comment by xuzifu666** [comment]
Due to this is a breaking change, mainly impact for indicate, so close it first.

**Comment by yaooqinn** [comment]
Thank you @xuzifu666

**Pull request closed without merging**
