### PR TITLE
[SPARK-39634][SQL] Allow file splitting in combination with row index generation

### PR DESCRIPTION
**Pull request by vkorukanti**
### What changes were proposed in this pull request?
- Parquet version `1.13.1` has a fix for [PARQUET-2161](https://issues.apache.org/jira/browse/PARQUET-2161) which allows splitting the parquet files when row index metadata column is selected. Currently the file splitting is disabled. Enable file splitting with row index column.

### Why are the changes needed?
Splitting parquet files allows better parallelization when row index metadata column is selected.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Uncomment the existing unittests.

### CODE REVIEW

**Comment by yihua** [comment]
Hi @vkorukanti, this is an important performance improvement for using the row index from Parquet. Is the PR targeted for Spark 3.5?

**Comment by vkorukanti** [comment]
@yihua Rebased the PR. If possible, it would be good to include this in the Spark 3.5 release.

**Review by ala — APPROVED** [review]
Thanks!

**Comment by yihua** [comment]
@vkorukanti @ala Great, thanks!

**Review by cloud-fan — APPROVED** [review]

**Comment by cloud-fan** [comment]
thanks, merging to master/3.5!

**Pull request closed without merging**
