### PR TITLE
[SPARK-41629][CONNECT] Support for Protocol Extensions in Relation and Expression

### PR DESCRIPTION
**Pull request by grundprinzip**
### What changes were proposed in this pull request?

This PR adds an extension mechanism to the Spark Connect protocol to support custom Relation and Expression types. This is necessary to support custom extensions in Spark like Delta or custom plugins in Catalyst.

This is achieved by adding `protobuf.Any` fields in `Relation`, `Command`, and `Expression`. To load the extension, this PR adds two configuration flags to indicate which classes should be loaded.

  * `spark.connect.extensions.relation.classes`
  * `spark.connect.extensions.expression.classes`
  * `spark.connect.extensions.command.classes`

To add a new plugin, the consumers have to implement either `RelationPlugin`, `CommandPlugin`,  or `ExpressionPlugin` and implement the corresponding `transform()` method. If the plugin does not support the transformation of the input, they plugin must return `None`.

Below is a simplified example of an expression and relation plugin.

First, define the custom message type that are necessary for the particular input.

```proto
message ExamplePluginRelation {
  Relation input = 1;
  string custom_field = 2;

}

message ExamplePluginExpression {
  Expression child = 1;
  string custom_field = 2;
}
```

Second, define the necessary `RelationPlugin` and `ExpressionPlugin` implementations.

```scala
class ExampleRelationPlugin extends RelationPlugin {
  override def transform(
      relation: protobuf.Any,
      planner: SparkConnectPlanner): Option[LogicalPlan] = {

    if (!relation.is(classOf[proto.ExamplePluginRelation])) {
      return None
    }
    val plugin = relation.unpack(classOf[proto.ExamplePluginRelation])
    Some(planner.transformRelation(plugin.getInput))
  }
}

class ExampleExpressionPlugin extends ExpressionPlugin {
  override def transform(
      relation: protobuf.Any,
      planner: SparkConnectPlanner): Option[Expression] = {
    if (!relation.is(classOf[proto.ExamplePluginExpression])) {
      return None
    }
    val exp = relation.unpack(classOf[proto.ExamplePluginExpression])
    Some(
      Alias(planner.transformExpression(exp.getChild), exp.getCustomField)(explicitMetadata =
        None))
  }
}
```

Now, on the client side, the new extensions simply have to be encoded into the `protobuf.Any` value to be available once the the plugins are loaded. Below is an example for wrapping the custom message type into a standard `Relation` with a `Range` child.

```scala
Relation
  .newBuilder()
  .setExtension(
    protobuf.Any.pack(
      proto.ExamplePluginRelation
        .newBuilder()
        .setInput(
          proto.Relation
            .newBuilder()
            .setRange(proto.Range
              .newBuilder()
              .setStart(0)
              .setEnd(10)
              .setStep(1)))
        .build()))
```

When the plan is transformed the custom extensions will behave like any other built-in functionality of Spark.

For an end-to-end example the code in `SparkConnectPluginRegistrySuite` provides a full working example.

### Why are the changes needed?
Extensibility

### Does this PR introduce _any_ user-facing change?
Yes, adds a new extension mechanism to the Spark Connect protoocol.

### How was this patch tested?
Added test coverage for the plugin registry, and end to end transformation and execution.

### CODE REVIEW

**Comment by grundprinzip** [comment]
R: @cloud-fan @hvanhovell @HyukjinKwon @zhengruifeng

**Comment by grundprinzip** [comment]
R: @amaliujia

**Comment by grundprinzip** [comment]
Will add support for `Command` in the same patch.

**Review by cloud-fan — APPROVED** [review]
LGTM if all tests pass

**Review by amaliujia — APPROVED** [review]

**Comment by grundprinzip** [comment]
Added the missing generated Python files.

**Comment by zhengruifeng** [comment]
LGTM, merged into master

**Comment by grundprinzip** [comment]
@sthagedorn can you post this in the dev mailing list thanks!

**Pull request closed without merging**
