### PR TITLE
[SPARK-36976][R] Add max_by/min_by API to SparkR

### PR DESCRIPTION
**Pull request by yoda-mon**
### What changes were proposed in this pull request?

Add max_by/min_by to SparkR

### Why are the changes needed?

for sparkr users' convenience

### Does this PR introduce _any_ user-facing change?

yes, new methods are added

### How was this patch tested?

unit test

### CODE REVIEW

**Review by sarutak — APPROVED** [review]
LGTM. Pending CIs.

**Comment by sarutak** [comment]
I think the AppVeyor failure is irrelevant to this change.

**Comment by HyukjinKwon** [comment]
Yeah, it's not related.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by yoda-mon** [comment]
Example screenshot
Screen Shot 2021-10-13 at 11 33 52

**Pull request closed without merging**
