### PR TITLE
[SPARK-32291][SQL] COALESCE should not reduce the child parallelism if it contains a Join

### PR DESCRIPTION
**Pull request by LantaoJin**
### What changes were proposed in this pull request?
Coalesce should not reduce the child parallelism if it contains a Join.
Add a new optimizer rule `RepartitionForCoalesceWithJoin` to add a Repartition if the child of Coalesce contains a Join.

### Why are the changes needed?
How to reproduce this issue:
```
spark.range(100).createTempView("t1")
spark.range(200).createTempView("t2")
spark.sql("set spark.sql.autoBroadcastJoinThreshold=0")
spark.sql("select /*+ COALESCE(1) */ t1.* from t1 join t2 on (t1.id = t2.id)").show
```
Before
Screenshot_2020-07-15 test-sql-context - Details for Query 26(2)
The number of partitions of SortMergeJoin is 1

After
Screenshot_2020-07-15 test-sql-context - Details for Query 26(4)
The number of partitions of SortMergeJoin is 5.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Add a unit test.

### CODE REVIEW

**Comment by LantaoJin** [comment]
cc @wangyum

**Comment by LantaoJin** [comment]
retest this please

**Comment by LantaoJin** [comment]
retest this please

**Comment by LantaoJin** [comment]
Retest this please

**Comment by LantaoJin** [comment]
retest this please

**Comment by manuzhang** [comment]
@LantaoJin What's the issue you are seeing here ?

**Comment by LantaoJin** [comment]
@manuzhang This is for performance improvement. COALESCE with join will reduce the SMJ operator parallelism. The user case is our internal function: download. Download the query result by one file. We use a COALESCE hint to implement it. But when the join in the query, the parallelism reduced to 1 in the Join operator.

**Comment by LantaoJin** [comment]
retest this please

**Comment by LantaoJin** [comment]
retest this please

**Comment by Tagar** [comment]
I've seen Spark users do this all the time to save to a single file. Great improvement.

Would this change cover `.repartition(1)` too and not just `.coalesce(1)` ?

Thanks

ps. Fun fact, some time back I wrote a small tool to workaround this very issue 
https://github.com/Tagar/abalon/blob/v2.3.3/abalon/spark/sparkutils.py#L444-L445
that used HDFS API calls to coalesce files together to not affecting Spark join pallelism 
https://github.com/Tagar/abalon/blob/v2.3.3/abalon/spark/sparkutils.py#L340

**Comment by wangyum** [comment]
This change will introduce an additional shuffle. We can use `localCheckpoint` to workaround this issue:
```scala
spark.range(100).createTempView("t1")
spark.range(200).createTempView("t2")
spark.sql("set spark.sql.autoBroadcastJoinThreshold=0")
spark.sql("select t1.* from t1 join t2 on (t1.id = t2.id)").localCheckpoint().coalesce(1).show()
```

**Pull request closed without merging**
