### PR TITLE
[SPARK-35687][SQL][TEST] PythonUDFSuite move assume into its methods

### PR DESCRIPTION
**Pull request by ulysses-you**
### What changes were proposed in this pull request?

Move `assume` into methods at `PythonUDFSuite`.

### Why are the changes needed?

When we run Spark test with such command:
`./build/mvn -Phadoop-2.7 -Phive -Phive-thriftserver -Pyarn -Pkubernetes clean test`

get this exception:
```
 PythonUDFSuite:
 org.apache.spark.sql.execution.python.PythonUDFSuite *** ABORTED ***
   java.lang.RuntimeException: Unable to load a Suite class that was discovered in the runpath: org.apache.spark.sql.execution.python.PythonUDFSuite
   at org.scalatest.tools.DiscoverySuite$.getSuiteInstance(DiscoverySuite.scala:81)
   at org.scalatest.tools.DiscoverySuite.$anonfun$nestedSuites$1(DiscoverySuite.scala:38)
   at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
   at scala.collection.Iterator.foreach(Iterator.scala:941)
   at scala.collection.Iterator.foreach$(Iterator.scala:941)
   at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
   at scala.collection.IterableLike.foreach(IterableLike.scala:74)
   at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
   at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
   at scala.collection.TraversableLike.map(TraversableLike.scala:238)
```

The test env has no PYSpark module so it failed.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

manual

### CODE REVIEW

**Comment by ulysses-you** [comment]
cc @HyukjinKwon @viirya

**Review by HyukjinKwon — APPROVED** [review]

**Comment by ulysses-you** [comment]
thank you @HyukjinKwon , seems something wrong with test, I have seen this error many times recently.
```
[error] ## Exception when compiling 479 sources to /home/jenkins/workspace/SparkPullRequestBuilder/sql/catalyst/target/scala-2.12/classes
[error] java.lang.StackOverflowError
[error] scala.reflect.api.Trees$Transformer.transform(Trees.scala:2563)
[error] scala.tools.nsc.transform.CleanUp$CleanUpTransformer.transform(CleanUp.scala:607)
[error] scala.tools.nsc.transform.CleanUp$CleanUpTransformer.transform(CleanUp.scala:37)
```

**Review by viirya — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master, branch-3.1 and branch-3.0.

**Comment by ulysses-you** [comment]
thanks for merging !

**Pull request closed without merging**
