### PR TITLE
[MINOR][DOCS] Fix all typos in markdown files of `doc` and similar patterns in other comments

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
## What changes were proposed in this pull request?

This PR tries to fix all typos in all markdown files under `docs` module, 
and fixes similar typos in other comments, too.
## How was the this patch tested?

manual tests.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Hi, @rxin . 
I finished reviewing all files under the `docs` module and related stuff. 
I think it's all typos for now. Thank you again.

**Comment by rxin** [comment]
LGTM pending tests.

**Comment by srowen** [comment]
Nice. That's a lot of the the

**Comment by srowen** [comment]
merged to master

**Comment by dongjoon-hyun** [comment]
Thank you, @srowen !

**Pull request closed without merging**
