### PR TITLE
[SPARK-40811][SQL][TESTS] Use `checkError()` to intercept `ParseException`: phase 2

### PR DESCRIPTION
**Pull request by MaxGekk**
### What changes were proposed in this pull request?
In the PR, I propose to port the following tests suites onto `checkError` to check valuable error parts instead of error messages:
- ParserUtilsSuite
- TableSchemaParserSuite
- InsertSuite
- HiveDDLSuite
- SQLQuerySuite
- MiscFunctionsSuite

### Why are the changes needed?
Migration on `checkError()` will make the tests independent from the text of error messages.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
By running the modified test suites:
```
$ build/sbt "test:testOnly *.ParserUtilsSuite"
$ build/sbt "test:testOnly *.TableSchemaParserSuite"
$ build/sbt "test:testOnly *.InsertSuite"
$ build/sbt -Phive-2.3 -Phive-thriftserver "test:testOnly *HiveDDLSuite"
$ build/sbt "test:testOnly *SQLQuerySuite"
$ build/sbt "test:testOnly org.apache.spark.sql.MiscFunctionsSuite"
```

### CODE REVIEW

**Comment by MaxGekk** [comment]
cc @panbingkun

**Comment by MaxGekk** [comment]
@LuciferYang @panbingkun @itholic Could you review this PR, please.

**Review by panbingkun — APPROVED** [review]

**Review by cloud-fan — APPROVED** [review]

**Comment by MaxGekk** [comment]
Merging to master. Thank you, @panbingkun and @cloud-fan for review.

**Comment by LuciferYang** [comment]
Late LGTM

**Pull request closed without merging**
