### PR TITLE
[SPARK-32012][SQL] Incrementally create and materialize query stage to avoid unnecessary local shuffle

### PR DESCRIPTION
**Pull request by viirya**
### What changes were proposed in this pull request?

This patch changes the current way of creating query stages in AQE. Instead of creating query stages in batch, incrementally creating query stage can bring the optimization in earlier. It could avoid unnecessary local shuffle.

### Why are the changes needed?

The current way of creating query stage in AQE is in batch. For example, the children of a sort merge join will be materialized as query stages in a batch. Then AQE brings the optimization in and optimize sort merge join to broadcast join. Except for the broadcasted exchange, we don't need do any exchange on another side of join but we already materialized the exchange. Currently AQE wraps the materialized exchange with local reader, but it still brings unnecessary I/O. We can avoid unnecessary local shuffle by incrementally creating query stage.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Unit tests.

### CODE REVIEW

**Comment by viirya** [comment]
retest this please

**Comment by cloud-fan** [comment]
Can you elaborate it more? How does this optimization help to plan broadcast join?

> For example, the children of a sort merge join will be materialized as query stages in a batch. Then AQE brings the optimization in and optimize sort merge join to broadcast join.

The AQE needs to wait for the stage to finish, so that it knows the size and can change to SMJ. How can we avoid unnecessary I/O after the stage is finished?

**Comment by viirya** [comment]
Use an example to elaborate it. This query `SELECT * FROM testData join testData2 ON key = a where value = '1'` is one of test case in `AdaptiveQueryExecSuite`.

The adaptivePlan in current master:
```
 *(3) BroadcastHashJoin [key#13], [a#23], Inner, BuildLeft
:- BroadcastQueryStage 2
:  +- BroadcastExchange HashedRelationBroadcastMode(List(cast(input[0, int, false] as bigint))), [id=#144]
:     +- CustomShuffleReader local
:        +- ShuffleQueryStage 0
:           +- Exchange hashpartitioning(key#13, 5), true, [id=#110]
:              +- *(1) Filter (isnotnull(value#14) AND (value#14 = 1))
:                 +- *(1) SerializeFromObject [knownnotnull(assertnotnull(input[0, org.apache.spark.sql.test.SQLTestData$TestData, true])).key AS key#13, staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, knownnotnull(assertnotnull(input[0, org.apache.spark.sql.test.SQLTestData$TestData, true])).value, true, false) AS value#14]                                                                                                  
:                    +- Scan[obj#12]
+- CustomShuffleReader local
   +- ShuffleQueryStage 1
      +- Exchange hashpartitioning(a#23, 5), true, [id=#121]
         +- *(2) SerializeFromObject [knownnotnull(assertnotnull(input[0, org.apache.spark.sql.test.SQLTestData$TestData2, true])).a AS a#23, knownnotnull(assertnotnull(input[0, org.apache.spark.sql.test.SQLTestData$TestData2, true])).b AS b#24]
            +- Scan[obj#22]
```

In above adaptivePlan, AQE produces two `ShuffleQueryStage`s because two exchanges were materialized in batch and then AQE re-optimizes the query. Although AQE can optimize SortMergeJoin as BroadcastHashJoin, the exchanges were already materialized and only thing AQE can do is reading it with local reader.

The adaptivePlan in this change:
```
*(2) BroadcastHashJoin [key#13], [a#23], Inner, BuildLeft                                  
:- BroadcastQueryStage 1
:  +- BroadcastExchange HashedRelationBroadcastMode(List(cast(input[0, int, false] as bigint))), [id=#137]
:     +- CustomShuffleReader local
:        +- ShuffleQueryStage 0
:           +- Exchange hashpartitioning(key#13, 5), true, [id=#110]
:              +- *(1) Filter (isnotnull(value#14) AND (value#14 = 1))
:                 +- *(1) SerializeFromObject [knownnotnull(assertnotnull(input[0, org.apache.spark.sql.test.SQLTestData$TestData, true])).key AS key#13, staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, from
String, knownnotnull(assertnotnull(input[0, org.apache.spark.sql.test.SQLTestData$TestData, true])).value, true, false) AS value#14]
:                    +- Scan[obj#12]
+- *(2) SerializeFromObject [knownnotnull(assertnotnull(input[0, org.apache.spark.sql.test.SQLTestData$TestData2, true])).a AS a#23, knownnotnull(assertnotnull(input[0, org.apache.spark.sql.test.SQLTestData$TestData2, true])).b AS
b#24]
   +- Scan[obj#22]
```

In this change, AQE only materializes one exchange and then optimizes SortMergeJoin as BroadcastHashJoin. After that, we don't need to produce another exchange.

**Comment by cloud-fan** [comment]
How do you achieve it? Do you hold off the execution of one query stage, and wait until another query stage completes?

**Comment by cloud-fan** [comment]
> It creates one stage first and then re-optimize the join.

This is the confusing part. Creating a stage is not enough, we must wait for it to complete, then we cam know the size and optimize the join to broadcast join.

**Comment by viirya** [comment]
I updated previous comment. "It creates and materializes one stage first..."

**Comment by cloud-fan** [comment]
> It creates and materializes

Do you mean to trigger the materialization or wait for it to complete?

**Comment by viirya** [comment]
It needs to wait for it to complete, this is how AQE does.

**Comment by maryannxue** [comment]
The question is: This means you hold off the other stage, right? Shouldn't it cause any regressions? If this is eventually a SMJ instead of a BHJ, one of the stages will be delayed.
And how do you know if you are starting the larger stage or the smaller one first??

**Comment by viirya** [comment]
Does triggering all stages of a join, mean they are running at the same time actually? I think it means they are put into scheduler. When the stages are put to running depends on resources provision. If first stage uses all resources, I think later stage still needs to held off?

It is also related to one question I have, the speed-up of AQE is gained by triggering all stages (not holding off other stage as you said) together, or optimizing join from SMJ to BHJ (only consider join case)? I may misunderstand, but before having AQE in SparkSQL, I think we don't trigger all stages like that too, right?

**Comment by cloud-fan** [comment]
> If first stage uses all resources, I think later stage still needs to held off?

That's true, but that's an assumption. It's also possible that these 2 jobs indeed run together.

> the speed-up of AQE is gained by triggering all stages (not holding off other stage as you said) together, or optimizing join from SMJ to BHJ (if we only consider join case)

In the benchmark, the default parallelism takes all the CPU cores. I think the most perf gain should be from shuffle partition coalescing and SMJ -> BHJ. cc @JkSelf 

That said, by design AQE triggers all independent stages at the same time, to maximize the parallelism. And it's helpful if the resource is sufficient (or auto-scaling). I don't think we should change this design.

**Comment by cloud-fan** [comment]
And as @maryannxue said, you may trigger the large side first and it doesn't make sense to hold off. Ideally we should trigger both sides and cancel the large side if the small side completes very quickly. It will be great if you can explore the cancelation approach.

**Comment by viirya** [comment]
@cloud-fan Thanks for clarifying. The idea sounds worth exploring as we can avoid local shuffle under current parallelism design of independent stages in AQE. I will explore the possibility.

**Comment by JkSelf** [comment]
In our previous 3TB TPC-DS benchmark, the perf improvement is mainly benefit from the coalescing  shuffle partitions and SMJ -> BHJ two features. The result is [here](https://docs.google.com/spreadsheets/d/1uija2AFblciMcYzU4jnPiy6I8mU8-M0-HwSNNns5aLU/edit?usp=sharing) for reference.

**Comment by dongjoon-hyun** [comment]
Hi, @viirya . Could you rebase this PR to the `master` branch please?

**Pull request closed without merging**
