### PR TITLE
[SPARK-16775][CORE] Remove deprecated accumulator v1 APIs

### PR DESCRIPTION
**Pull request by srowen**
## What changes were proposed in this pull request?

Remove deprecated accumulator v1

## How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by srowen** [comment]
Note this doesn't yet figure out what has to change in Pyspark, SparkR.

**Comment by felixcheung** [comment]
no accumulator in R

**Comment by HyukjinKwon** [comment]
yup, PySpark uses accumulator V2 per https://github.com/apache/spark/commit/90d5754212425d55f992c939a2bc7d9ac6ef92b8

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
adding @cloud-fan since accumulator version 2 was added by you.

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
