### PR TITLE
[SPARK-42827][CONNECT] Support `functions#array_prepend` for Scala connect client

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr aims support  `functions#array_prepend` for Scala connect client.

### Why are the changes needed?
Add Spark connect jvm client api coverage.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Add new test

### CODE REVIEW

**Review by zhengruifeng — APPROVED** [review]
thanks.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by LuciferYang** [comment]
All passed

**Comment by zhengruifeng** [comment]
merged to master

**Comment by LuciferYang** [comment]
Thanks @zhengruifeng @HyukjinKwon

**Pull request closed without merging**
