### PR TITLE
[SPARK-8129] [CORE] [SECURITY] Securely pass auth secrets to executors via stdin

### PR DESCRIPTION
**Pull request by kanzhang**
Currently, in standalone cluster mode, auth secrets are passed to executors as java options on the command line. This is insecure since anyone running a 'ps' command can see it. This patch passes auth secrets to child processes' stdin.

### CODE REVIEW

**Comment by kanzhang** [comment]
For reviewers, for testing purposes, I factored out the building of ApplicationDescription and DriverDescription logic into separate methods in SparkDeploySchedulerBackend and ClientActor, respectively. No logic changes except adding a line to set auth secret in each and changed a line to filter out auth secret from sparkJavaOpts in each. I noticed that in SparkDeploySchedulerBackend, the original code uses Spark conf from two places, one is the passed-in sc.conf and the other is scheduler.sc.conf. For what I can tell, in all instances that SparkDeploySchedulerBackend is created, they points to the same conf. So I consolidate them into sc.conf in the refactored code.

**Comment by kanzhang** [comment]
Please hold on reviewing for now. I'll post an update.

**Comment by kanzhang** [comment]
Ok, this is ready for review. Thx.

**Comment by vanzin** [comment]
Dumb question: can't you just pass it as an environment variable?

Only the process's user (and root) can read `/proc/[xxx]/environ`.

**Comment by kanzhang** [comment]
No question is dumb. :) Yeah, what you said also works, but I was thinking in the future where each job would get its own secret.

Would you be able to help with reviewing?

**Comment by vanzin** [comment]
> but I was thinking in the future where each job would get its own secret.

How would an environment variable break that? You set it per child process. It's going to be a different child process for each job.

**Comment by kanzhang** [comment]
Since those child processes are run using the same user account, they will be able to see each other's /proc, right? Also, /proc is more of a UNIX feature (OS X and Windows don't have /proc?). I would think using pipe is more portable as it is supported by Java.

**Comment by kanzhang** [comment]
Sorry, the discussion on /proc portability is irrelevant.

**Comment by vanzin** [comment]
> Since those child processes are run using the same user account

Standalone is not secure no matter what you do. If you want to prevent users that are not the user running the Spark daemons from reading the secrets of Spark apps, then you can easily do that by using env variables.

You can't protect different Spark apps from each other since they're all running as the same user in standalone mode.

**Comment by kanzhang** [comment]
bq. You can't protect different Spark apps from each other since they're all running as the same user in standalone mode.

I agree. Eventually, it will have to change to have better multi-tenancy support. Short of bigger changes like launching user processes in their own accounts (what Hadoop does), this patch allows us to reap some interim benefits, i.e., support for per-app secret.

**Comment by vanzin** [comment]
> this patch allows us to reap some interim benefits, i.e., support for per-app secret.

You have per-app secrets today as far as I know, don't you?

Removing the secret from the command line is just a matter of using an env variable. No need for the complicated code you're adding.

**Comment by kanzhang** [comment]
bq. You have per-app secrets today as far as I know, don't you?

No, not for the standalone mode. There is only one single cluster-wide secret for all apps. Supporting per-app secrets in standalone mode is one patch I'm working on and it builds on top of this patch. Using env variable wouldn't suffice, as we've discussed.

**Comment by vanzin** [comment]
> Using env variable wouldn't suffice, as we've discussed.

I don't see where you explained that at all. The same code that can write the secret to the child process's stdin (in you patch) can set an env variable when launching that process.

**Comment by kanzhang** [comment]
> I don't see where you explained that at all.

I meant env variables can be seen by other apps since all apps are running as the Spark daemon user. They can't be treated as secrets. Pipes, on the other hand, provide a secure communication channel between parent and child processes and can be used to pass per-child secrets. 

> The same code that can write the secret to the child process's stdin (in you patch) can set an env variable when launching that process.

That's exactly why I don't think setting env variables will make the patch much simpler. One would substitute the 2 utility methods for writing/reading stdin with equivalent ones of setting/reading env variables, but the rest of the changes are still needed.

**Comment by vanzin** [comment]
> I meant env variables can be seen by other apps since all apps are running as the Spark daemon user. 

And I thought we agreed there's no point in trying to fix that, because since they're all running as the same user, they can do things like read the certs used to encrypt the other app's traffic, read the other app's memory, and all other nasty things.

You're not fixing security by removing the secret from the command line. You can only fix security by isolating the apps properly, which means running them as the proper user.

> One would substitute the 2 utility methods for writing/reading stdin with equivalent ones of setting/reading env variables, but the rest of the changes are still needed.

It's bad to use stdin for this. For one, it has weird semantics on Windows. And for second, stdout and stdin are generally considered to belong to the application, and thus Spark shouldn't really touch them if possible.

Even if you still have to change other places, just no having those two utility methods, and avoiding the issues I mentione above, is already a big gain in maintainability.

**Comment by kanzhang** [comment]
> And I thought we agreed there's no point in trying to fix that, because since they're all running as the same user, they can do things like read the certs used to encrypt the other app's traffic, read the other app's memory, and all other nasty things.

My thought was we can still make some gain by leveraging process-level isolation, even though they are running as the same user. Apps won't automatically read each other's memory, right? Being able to read others' SSL certs doesn't mean one can decrypt traffic. Each session is encrypted using a freshly generated session key.

> It's bad to use stdin for this. For one, it has weird semantics on Windows. And for second, stdout and stdin are generally considered to belong to the application, and thus Spark shouldn't really touch them if possible.

That's a valid point. Thanks for bringing it up. I'm not familiar with Windows. Can you expand a little?

**Comment by vanzin** [comment]
> Apps won't automatically read each other's memory, right?

The point is not that they will automatically do it, the point is that they can.

> Being able to read others' SSL certs doesn't mean one can decrypt traffic.

It does because the session key is encrypted using the cert's private key.

> I'm not familiar with Windows. Can you expand a little?

We've had issues in the past with pyspark and Scala code that messed with stdin.

Since there's a trivial option that doesn't involve using stdin and does not have any drawback security-wise, I don't understand what's your reluctance in using it.

**Comment by kanzhang** [comment]
> The point is not that they will automatically do it, the point is that they can.

I guess it's all about how easy it is to do so. Can you show me a trivial example, just so I can convince myself anything in this direction is not worth trying?

> It does because the session key is encrypted using the cert's private key.

Ok, we are each partially correct on this one. Forward/backward secrecy is only supported by certain key-agreement ciphers (Diffie-Hellman).

> We've had issues in the past with pyspark and Scala code that messed with stdin.

I must have missed that. Can you post a pointer?

> Since there's a trivial option that doesn't involve using stdin and does not have any drawback security-wise, I don't understand what's your reluctance in using it.

Well, maybe I set my expectations too high. :) It does have drawback in the sense that it is not a solution for improving multi-tenancy. I'm wiling to be convinced multi-tenancy improvements without running user apps in their own accounts are not worth trying.

**Comment by vanzin** [comment]
> I'm wiling to be convinced multi-tenancy improvements without running user apps 

What do you need to be convinced of that? Apps can read all the data other apps generate (in HDFS or other storage), apps can kill other app processes, apps have access to *anything* other apps running as the same user have access too.

Ignoring that if you really want you can find the secret by looking at the memory of another process, all that the secret prevents is someone connecting back to the driver and pretending to be an executor. Given all of the above, is that really giving *any* extra security to the app?

**Comment by kanzhang** [comment]
> Apps can read all the data other apps generate (in HDFS or other storage)

As long as you give each app a different HDFS delegation token (and as long as we can find a secure way to pass tokens to apps - the current effort is a try in that direction), they won't be able to access each other's HDFS files. Local file system is not secure - that's why we can't use it to pass per-app secrets.

> apps can kill other app processes

That's true. I'm aware of it and consider it a kind of denial of service attack, which is beyond my current goal to defend against.

> apps have access to anything other apps running as the same user have access too.

Yes. But I still wish someone could show me a simple example that defeats my purpose of having a per-app secret for securing per-app communication traffic.

> Ignoring that if you really want you can find the secret by looking at the memory of another process, all that the secret prevents is someone connecting back to the driver and pretending to be an executor. Given all of the above, is that really giving any extra security to the app?

As long as we can find a secure way to distribute a per-app secret, my follow-on patch will fix this by turning on authentication between driver and executor using this per-app key.

**Comment by vanzin** [comment]
> As long as you give each app a different HDFS delegation token

And how do you plan to use delegation tokens in standalone mode without kerberos?

> As long as we can find a secure way to distribute a per-app secret

There's no secure way unless you actually have proper user isolation, which does not exist in standalone mode. Your proposed change protects users that are not running Spark apps from being able to do bad things, so it's an improvement. But you cannot fix standalone mode security just by hiding this secret from the command line.

**Comment by kanzhang** [comment]
> Ignoring that if you really want you can find the secret by looking at the memory of another process, all that the secret prevents is someone connecting back to the driver and pretending to be an executor. Given all of the above, is that really giving any extra security to the app?

Oh, I missed your point in my last reply.  Yes, I do think there is some extra security to be gained by having a per-app secret key for securing per-app communications, assuming there is not a trivial way to compromise the per-app key.

**Comment by kanzhang** [comment]
> And how do you plan to use delegation tokens in standalone mode without kerberos?

Kerberos is in the plan. :) But it is orthogonal to finding a secure way to distribute per-app secrets. The latter is needed no matter Kerberos is supported or not.

> Your proposed change protects users that are not running Spark apps from being able to do bad things, so it's an improvement.

Yes, that's the first goal.

>  But you cannot fix standalone mode security just by hiding this secret from the command line.

My second goal is to improve standalone mode security by having a per-app key. I think what we debate about is whether this is worth trying, given all apps are running as the same user.

**Comment by vanzin** [comment]
> My second goal is to improve standalone mode security by having a per-app key. I think what we debate about is whether this is worth trying, given all apps are running as the same user.

I think you're misunderstanding me. I'm arguing that using the env variable to propagate the secret is *as secure* as using stdin. It's not about per-app keys or anything else you're talking about.

Given that both as *as secure* there's no point in going with the more complicated code.

That's all.

And if you'll use the argument that "oh but it's not as trivial to get the key when it's passed via stdin", then you're missing the point of security.

**Comment by kanzhang** [comment]
> I think you're misunderstanding me. I'm arguing that using the env variable to propagate the secret is as secure as using stdin. It's not about per-app keys or anything else you're talking about.

I get your point. From the point of view of preventing non-Spark users from getting the secret, both stdin and env variable will do. But for me, this patch is just a stepping stone toward supporting per-app secrets in standalone mode, without going full-blown on running user apps in their own accounts. For that, env variable will not work. If, however, this goal is unrealistic, I'll have to scale back and take your suggestion. Thanks for the discussion anyway.

Any comments from others on using stdin to pass secrets to child processes? @rxin @pwendell @andrewor14 ?

**Comment by vanzin** [comment]
>  For that, env variable will not work. 

You have not explained why that won't work. The only difference is that with the env variable it's slightly easier to get the secret. (i.e.., just read a file in `/proc` instead of running `jmap` to get the data from the other app's heap).

So there's absolutely no extra security from using stdin, just more complicated code.

**Comment by kanzhang** [comment]
Ok, that's exactly the kind of opinion I want to hear about. Do others feel the same way?

**Comment by vanzin** [comment]
BTW, using an env variable is mostly a trivial change. You just change the non-YARN path in `SecurityManager::generateSecretKey`; basically, on the driver side, generate a secret, and call `sparkConf.setExecutorEnv("_SPARK_AUTH_SECRET")`. On the executor side, you just do `sys.env.get("_SPARK_AUTH_SECRET")`.

Nothing else in the rest of the code should need to change.

**Comment by kanzhang** [comment]
> Nothing else in the rest of the code should need to change.

Yes, if you are extending the current model where there is a single secret key for the whole cluster. But my purpose was moving toward per-app secrets, as I have said multiple times.

**Comment by vanzin** [comment]
> But my purpose was moving toward per-app secrets, as I have explained.

And as I said multiple times, that change does not depend on whether you use stdin or env variables to pass the security secret to executors.

**Comment by kanzhang** [comment]
> And as I said multiple times, that change does not depend on whether you use stdin or env variables to pass the security secret to executors.

I guess what you meant is to support per-app secrets properly one must run apps in users' own accounts. I certainly agree. What I'm exploring presently is whether there is any low-hanging fruit to be had (or worth to be had) before we get there. I don't have a definitive answer to it. That's why I seek opinions. I know you don't think so. Let's see what others think. I thought about env variable early on but rejected it for my present purpose since it is only private to the user, not private to the process, as you pointed out in your first comment. If, however, we conclude anything less than running apps in users' own accounts is not worth trying, env variable is of course an option. Hope this clarifies.

Independently, I want to understand the drawbacks of using stdin as a private communication channel between Worker and Executor in the spark environment. Pointers welcome.

**Comment by vanzin** [comment]
>  it is only private to the user, not private to the process

That's not a thing. You're not gonna get anywhere, security-wise, without user isolation. Think:

- You can use `jmap` to read the other process's heap if both are being run by the same user. Pretty easy to find any secrets by just searching for the right object in the heap dump.
- Let's say that for some reason `jmap` does not work, and that you implement the "per-app keys" you talk about. The malicious user can kill the `Master` or `Worker` process, starts his own one in their place, and starts recoding all the keys being distributed to apps. All processes are running as the same user, so that's totally feasible.

The change to remove the secret from the command line is a good one, because it makes the secret private to the user, in your own jargon. But that is a trivial change, and has no side-effect on anything else you're trying to do. So unless you provide an explanation of exactly where you want to go with this "stdin communication channel", it's just a complication that doesn't add any security, and thus should be avoided.

We're talking about a patch that would be a few lines long with my suggestion, instead of all the changes you currently have, while achieving exactly the same result.

**Comment by kanzhang** [comment]
> We're talking about a patch that would be a few lines long with my suggestion

The line savings may not be that dramatic. We could save a few lines around getting and setting `appSecret`. But we still need to filter out the secret key from java options. The bulk of this patch is actually unit tests making sure that does happen in all 3 places where we build executor commands, and code refactoring those tests depend on (see my initial comment at the top).

In any case, I'd like to leave this open for a few days, to give others an opportunity to comment on if they wish.

**Comment by vanzin** [comment]
> The line savings may not be that dramatic

Actually it would. Because all you need to do is change SparkConf to not include `spark.authenticate.secret` in the executor's command line, change SecurityManager to look for the secret in an env variable, and change CommandUtils.buildLocalCommand to add the environment variable to the child.

That's a one line change in 3 different files.

**Comment by kanzhang** [comment]
> Because all you need to do is change SparkConf to not include spark.authenticate.secret in the executor's command line

That's what I'm already doing and the filtering has to happen in all 3 places where we build executor commands. That's 3 lines already. :) Plus, the unit tests that make sure that happens. If you see where things can be simplified, please comment on the code.

**Comment by vanzin** [comment]
> That's what I'm already doing and the filtering has to happen in all 3 places

There's a single method in SparkConf that already does the filtering. There's no need to add a bunch of other methods to do slightly different filtering, like you're doing.

The change to fix the bug is, literally, 3 lines of code. Maybe 4 if you need to handle Mesos too.

**Comment by kanzhang** [comment]
> There's a single method in SparkConf that already does the filtering. There's no need to add a bunch of other methods to do slightly different filtering, like you're doing. .... The change to fix the bug is, literally, 3 lines of code. Maybe 4 if you need to handle Mesos too.

Are you referring to `isExecutorStartupConf`? I didn't want to change it because it was also used in YARN. If you are sure there is no side-effect for YARN, I can consolidate `isStandaloneExecutorStartupConf` with it. That saves one method (2 lines). Anything else? We still need to do the actual filtering in `Client`, `StandaloneRestServer` and `SparkDeploySchedulerBackend`, right? That's 3 lines already. And we need the newly introduced `isNotClusterAuthSecretConf` method for the first 2 cases, right? 

Again, please comment on the code so I know exactly what you are talking about.

**Comment by vanzin** [comment]
>  I didn't want to change it because it was also used in YARN.

YARN doesn't use `spark.authenticate.secret`.

> Again, please comment on the code so I know exactly what you are talking about.

I already commented that pretty much your whole change is unnecessary. No point in commenting in the code.

**Comment by vanzin** [comment]
I'm just gonna leave this here as an example of how small this PR can be: https://github.com/vanzin/spark/commit/f43b09656be308949561b89886ff7b942387c2c7

**Comment by kanzhang** [comment]
Thanks. So it's not just 3 lines. :-) Honestly, if you finish it up and add similar tests as I did, you will end up with less but not substantially less code. Apart from a few straight-forward convenience methods in SparkConf and Utils, the rest of my non-test changes are minimal per file or cosmetic. Most of the patch is either tests or refactoring of code chunks into their own methods to support testing (e.g., in `Client`, `SparkDeploySchedulerBackend`).

I found a simpler way to fix it if I don't introduce the concept of per-app key, which is to do all the filtering and setting env variables in `buildLocalCommand`. Thank you for bringing it to my attention earlier. It allows me handle all 3 cases in one place. I just need one set of tests instead of 3, and no code refactoring is needed for testing. I'll submit a new PR. You are welcome to review it.

Let's leave this PR for collecting feedbacks on my stdin approach. I admit I'm guilty of trying to squeeze in more code than necessary to fix the issue in the current model (the `appSecret` stuff). But I was gearing toward per-app secrets with my stdin approach.

**Comment by srowen** [comment]
OK, I think you can close this if it's not active. It doesn't go away and can still be commented on.

**Pull request closed without merging**
