### PR TITLE
[SPARK-44464][SS] Implement applyInPandasWithState in PySpark

### PR DESCRIPTION
**Pull request by siying**
### What changes were proposed in this pull request?
Change the serialization format for group-by-with-state outputs: include an explicit hidden column indicating how many data and state records there are.

### Why are the changes needed?
The current implementation of ApplyInPandasWithStatePythonRunner cannot deal with outputs where the first column of the row is null, as it cannot distinguish the case where the column is null, or the field is filled as the number of data records are smaller than state records. It causes incorrect results for the former case.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Add unit tests that cover null cases and different other scenarios.

### CODE REVIEW

**Review by HeartSaVioR — APPROVED** [review]
+1 Nice finding and great fix!

**Comment by HeartSaVioR** [comment]
Thanks! Merging to master/3.5/3.4!

**Comment by HeartSaVioR** [comment]
@siying 
There was a conflict. Could you please create a PR against branch-3.4? Thanks in advance!

(Btw, I didn't indicate that title is not accurate. Could you please fix the title when you submit a PR for 3.4?)

**Comment by siying** [comment]
Sure. Will do that.

**Comment by siying** [comment]
> @siying There was a conflict. Could you please create a PR against branch-3.4? Thanks in advance!
> 
> (Btw, I didn't indicate that title is not accurate. Could you please fix the title when you submit a PR for 3.4?)

Oops. I didn't realize the title was wrong. Perhaps I did a wrong copy&paste.

**Pull request closed without merging**
