### PR TITLE
[SPARK-43974][CONNECT][BUILD] Upgrade buf to v1.23.1

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to upgrade buf from 1.20.0 to 1.23.1

### Why are the changes needed?
1.Release Notes: 
- https://github.com/bufbuild/buf/releases/tag/v1.23.1
- https://github.com/bufbuild/buf/releases/tag/v1.23.0
- https://github.com/bufbuild/buf/releases/tag/v1.22.0
- https://github.com/bufbuild/buf/releases/tag/v1.21.0

2.The new version brings some bug fixed and improvment, as follow:
- Fix issue where buf beta graph would not print modules within a workspace that
had no dependencies or dependents.
- Fix issue where buf beta graph would print warnings for missing dependencies
that were actually present.
- Fix issue where locally-produced images did not have module information if the corresponding
module was stored in the new cache.
- Remove buf beta registry template.
- Remove buf beta registry plugin {create,deprecate,list,undeprecate,version} and replace with
buf beta registry plugin {push,delete}.
- Update buf beta price with the latest pricing information.

3.Manually test: dev/connect-gen-protos.sh, this upgrade will not change the generated files.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
- Manually test
- Pass GA

### CODE REVIEW

**Review by zhengruifeng — APPROVED** [review]

**Review by dongjoon-hyun — COMMENTED** [review]
Just a head-up. This is 4th commit since 5/1. Shall we hold on this dependency and do accumulated-update monthly. For example, shall we wait until July 1st, @panbingkun and @zhengruifeng ?

```
$ git log --oneline --since 2023-05-01 | grep 'Upgrade buf'
d61c77cac1 [SPARK-43890][CONNECT][BUILD] Upgrade buf to v1.20.0
e186e9dfbf [SPARK-43599][CONNECT][BUILD] Upgrade buf to v1.19.0
7992455de2 [SPARK-43401][CONNECT][BUILD] Upgrade buf to v1.18.0
```

**Comment by zhengruifeng** [comment]
@dongjoon-hyun I am fine with holding on it until July 1st, `buf` release is a bit frequent.
We may also need to upgrade it to the latest version before 3.5 rc.

**Comment by dongjoon-hyun** [comment]
Thank you. Yes, I agree with you. Since the feature freeze is July 16th, maybe after July 10th?
- https://spark.apache.org/versioning-policy.html

**Comment by panbingkun** [comment]
@dongjoon-hyun Ok, Let's holding on it until July 1st.

**Comment by dongjoon-hyun** [comment]
Thank you, @panbingkun . I'm fine any date after July 1st~ Feel free to proceed after than.

**Comment by zhengruifeng** [comment]
> Thank you. Yes, I agree with you. Since the feature freeze is July 16th, maybe after July 10th?
> 
> * https://spark.apache.org/versioning-policy.html


July 10th also works for me

**Comment by LuciferYang** [comment]
I set this to draft first to avoid unexpected merging

**Comment by panbingkun** [comment]
@dongjoon-hyun @zhengruifeng Before we release the new Spark version, let's review this PR again. 😄

**Review by zhengruifeng — APPROVED** [review]

**Comment by zhengruifeng** [comment]
merged to master

**Comment by LuciferYang** [comment]
late LGTM

**Comment by panbingkun** [comment]
There seems to be a problem with this patch, I need a new followup to solve this problem
@zhengruifeng
image

image

**Comment by panbingkun** [comment]
@zhengruifeng Should we migrate or revert it?

**Comment by zhengruifeng** [comment]
@panbingkun  I think this failure started before this PR got merged.

https://github.com/apache/spark/actions/runs/5511781438/jobs/10047815050


does this upgrade cause so many changes in generated codes? https://github.com/apache/spark/pull/41934

**Comment by LuciferYang** [comment]
It's strange that the failure started after upgrading to sbt 1.9.2, which doesn't seem to be related ...

**Comment by panbingkun** [comment]
Yes, when I executed `sh dev/connect-gen-protos.sh` locally, the automatically generated file in Python changed.
My local buf version is: 
image

**Comment by zhengruifeng** [comment]
@panbingkun it is weird since IIRC the CI in this PR passed.

but, if this upgrade cause such large changes in generated codes, let's revert it for now to avoid big changes before code freeze.

**Comment by panbingkun** [comment]
In order to address the https://github.com/apache/spark/pull/41933 issue, the above PR has been reverted and now resubmitted.
https://github.com/apache/spark/pull/41937

**Pull request closed without merging**
