### PR TITLE
[SPARK-43487][SQL] Fix wrong error message used for `ambiguousRelationAliasNameInNestedCTEError`

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to fix  wrong error message used for `ambiguousRelationAliasNameInNestedCTEError`.

### Why are the changes needed?
Fix bug.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA.

### CODE REVIEW

**Comment by MaxGekk** [comment]
@panbingkun Isn't this a duplicate of https://github.com/apache/spark/pull/41155?

**Comment by panbingkun** [comment]
> @panbingkun Isn't this a duplicate of #41155?

It seems like it's duplicated. Should I turn it off?

**Comment by MaxGekk** [comment]
> It seems like it's duplicated. Should I turn it off?

Please, keep it alive so far.

**Comment by MaxGekk** [comment]
@panbingkun Could you close this PR, please.

**Comment by panbingkun** [comment]
> @panbingkun Could you close this PR, please.

OK

**Pull request closed without merging**
