### PR TITLE
[SPARK-24736][k8s] Let spark-submit handle dependency resolution.

### PR DESCRIPTION
**Pull request by vanzin**
Before this change, there was some code in the k8s backend to deal
with how to resolve dependencies and make them available to the
Spark application. It turns out that none of that code is necessary,
since spark-submit already handles all that for applications started
in client mode - like the k8s driver that is run inside a Spark-created
pod.

For that reason, specifically for pyspark, there's no need for the
k8s backend to deal with PYTHONPATH; or, in general, to change the URIs
provided by the user at all. spark-submit takes care of that.

For testing, I created a pyspark script that depends on another module
that is shipped with --py-files. Then I used:

- --py-files http://.../dep.py http://.../test.py
- --py-files http://.../dep.zip http://.../test.py
- --py-files local:/.../dep.py local:/.../test.py
- --py-files local:/.../dep.zip local:/.../test.py

Without this change, all of the above commands fail. With the change, the
driver is able to see the dependencies in all the above cases; but executors
don't see the dependencies in the last two. That's a bug in shared Spark code
that deals with local: dependencies in pyspark (SPARK-26934).

I also tested a Scala app using the main jar from an http server.

### CODE REVIEW

**Comment by attilapiros** [comment]
Jenkins retest this please

**Comment by attilapiros** [comment]
For the flaky test (YarnSchedulerBackendSuite#"RequestExecutors reflects node blacklist and is serializable") I have created a new issue: [SPARK-26891](https://issues.apache.org/jira/browse/SPARK-26891).

**Review by attilapiros — APPROVED** [review]
Have not found any issue but I just read your changes (have not tried to run it). 
I only have one question as I have seen the arg `--other-py-files` is deplemented: are you sure it isn't used already by somebody in same way? If it could be used somehow then I think a meaningful error would be nice.

Otherwise LGTM.

**Comment by vanzin** [comment]
> the arg `--other-py-files` is deplemented

That's just a command line arg for the kubernetes launcher; it's only even used from SparkSubmit. It's not used anywhere else.

**Comment by holdenk** [comment]
So I'm a little confused here since if we look at the YARN cluster manager we also see similar logic around setting the PYTHONPATH

Have you tested this with a zipfile or egg as a dependency since I don't think Python will by default expand all zip files in pwd?

cc @ifilonenko

**Comment by vanzin** [comment]
> if we look at the YARN cluster manager we also see similar logic around setting the PYTHONPATH

YARN is not a good example to follow. It builds its own custom commands instead of using spark-submit / spark-class like the others. e.g. the k8s driver is run using spark-submit inside the cluster, and YARN's driver in cluster mode is not run that way. So the YARN code needs to handle a lot of things that are otherwise handled by spark-submit.

YARN has also special handling for its distributed cache functionality, which others don't have.

The goal here is basically to avoid making in the k8s backend the same mistakes YARN made.

> Have you tested this with a zipfile or egg as a dependency

I'll give it a shot. But like the `local:` dependency issue in executors, if that's not working, it's probably some issue in how the shared code deals with those, and I'd consider it a separate issue. (Which doesn't mean it shouldn't be fixed.)

**Comment by vanzin** [comment]
I re-ran all my previous tests on master and with my change, and also added the same tests with a zip dependency, and turns out the behavior is exactly the same on both. The difference is that this PR gets rid of a bunch of code, and you also get a clean "PYTHONPATH" (with master, you get the "http://" URI verbatim in the value of that env variable).

So, IMO, still a net gain, and we can fix the remaining local: and .zip issues separately, benefiting everybody, not just k8s.

**Comment by vanzin** [comment]
Argh. I filed SPARK-26933 for the .zip thing, but it turns out I did something wrong when testing this morning. I retested again and the .zip dependency works with this change, not with master. So yay!

I'll update the PR description (again) and rebase the code.

**Review by srowen — APPROVED** [review]

**Review by ifilonenko — APPROVED** [review]
Thanks for moving `--py-files` to be resolved by spark-submit. The following simplification clearing makes sense in this context.

**Comment by holdenk** [comment]
LGTM, although a minor optional suggestion.

If you wanted I think it could be an OK test add a zip file test to `resource-managers/kubernetes/integration-tests/src/test/scala/org/apache/spark/deploy/k8s/integrationtest/PythonTestsSuite.scala` but, it's ok as is.

Looking at the logic in `PythonRunner.scala` files ending in `.py` and others are handled differently with path formatting.

**Comment by vanzin** [comment]
> I think it could be an OK test add a zip file test

I actually want to write a proper integration test for all this, but that would be a little too large to include as part of this PR. That test would also remove the external dependency on an external http server that currently exists in one of the tests...

**Comment by vanzin** [comment]
retest this please

**Comment by vanzin** [comment]
retest this please

**Comment by vanzin** [comment]
retest this please

**Comment by vanzin** [comment]
Not sure what's the deal with the k8s tests. They pass locally. Maybe the recent library upgrade doesn't gel with the minikube running on jenkins?

**Comment by vanzin** [comment]
retest this please

**Comment by vanzin** [comment]
Merging to master.

**Pull request closed without merging**
