### PR TITLE
[SPARK-5210] Support group event log when app is long-running

### PR DESCRIPTION
**Pull request by XuTingjun**
For long-running Spark applications (e.g. running for days / weeks), the Spark event log may grow to be very large.

I think group event log by job is an acceptable resolution. 
1. To group eventLog, one application has two kinds file: one meta file and many part files. We put `StageSubmitted/ StageCompleted/ TaskResubmit/ TaskStart/TaskEnd/TaskGettingResult/ JobStart/JobEnd` events into meta file, and put other events into part file. The event log shows like below:

```
application_1439246697595_0001-meta
application_1439246697595_0001-part1
application_1439246697595_0001-part2
```

2.To HistoryServer, every part file will be treated as an application, and it will replay meta file after replay part file. Below is the display of group app on HistoryServer web:
default

### CODE REVIEW

**Comment by markhamstra** [comment]
@XuTingjun you speak of an "acceptable resolution", but you haven't adequately described the problem you are trying to resolve.  Yes, the event log can get long, but I'm not seeing why that is inherently a problem or why you can't "acceptably resolve" your problem by post-processing the event log while leaving that log as a single, unified stream of events.

**Comment by andrewor14** [comment]
@XuTingjun I think this is something good to fix. I've noticed that uncompressed event logs can amount up to 15GB for a 5 minute application. However, I think a lot of functionality is already implemented so we should reuse existing code where possible. In particular, have you looked at `RollingFileAppender`? We can use that and specify a `RollingPolicy` based on number of bytes written. That seems to achieve what we want.

**Comment by andrewor14** [comment]
By the way, since this patch has been opened many months ago it's now mostly stale. If you plan to work on this, would you mind closing this patch and re-opening one that uses the `RollingFileAppender`? Hopefully the size of the diff will be much smaller then.

**Comment by 3ourroom** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

3ourroom@naver.com 님께 보내신 메일 <Re: [spark] [SPARK-5210] Support group event log when app is long-running (#9246)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by satlal** [comment]
@XuTingjun revisiting this thread. Since this patch seems to be abandoned, were you able to work around the large log files issue for long running streaming jobs?

**Comment by eladamitpxi** [comment]
+1 large / infinitely growing event log files are quite a problem for long running streaming jobs

**Pull request closed without merging**
