### PR TITLE
[SPARK-41026][CONNECT] Support Repartition in Connect Proto

### PR DESCRIPTION
**Pull request by amaliujia**
### What changes were proposed in this pull request?

Support `Repartition` in Connect proto, which further supports two API: `repartition` (shuffle=true) and `coalesce` (shuffle=false).  

### Why are the changes needed?

Improve API coverage.

### Does this PR introduce _any_ user-facing change?

NO

### How was this patch tested?

UT

### CODE REVIEW

**Comment by amaliujia** [comment]
R: @cloud-fan

**Review by cloud-fan — APPROVED** [review]

**Comment by cloud-fan** [comment]
please fix code conflicts first.

**Comment by amaliujia** [comment]
Conflict fixed.

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Pull request closed without merging**
