### PR TITLE
[SPARK-5383][SQL] support alias for udfs with multi output columns

### PR DESCRIPTION
**Pull request by scwf**
when a udf output multi columns, now we can not use alias for them in spark-sql, see this flowing sql: 

select stack(1, key, value, key, value) as (a, b, c, d) from src limit 5;

### CODE REVIEW

**Comment by rxin** [comment]
You can do that? What does that even mean to have 2 aliases? What is the column name?

**Comment by scwf** [comment]
@rxin,  for the example `select key as (k1, k2) from src limit 5`
  k1 and k2 both are alias for `key`. And i tested with hive and HiveQL supported this, here is test case in hive:

```
select stack(2, *) as (e1,e2,e3) from (
  select concat(*), concat(a.*), concat(b.*), concat(a.*, b.key), concat(a.key, b.*)
  from src a join src b on a.key+1=b.key where a.key < 100) x limit 10;

```

**Comment by scwf** [comment]
Sorry, probably i made a mistake here. to close this.

**Comment by scwf** [comment]
filed a new PR https://github.com/apache/spark/pull/4186 for this

**Pull request closed without merging**
