### PR TITLE
[SPARK-35355][SQL] Avoid shuffle in some scenes with CollectLimitExec

### PR DESCRIPTION
**Pull request by yikf**
### What changes were proposed in this pull request?
Currently, Some scenes retain the combination of GlobalLimitExec - LocalLimitExec, which can actually be optimized to CollectLimitExec, like: `INSERT INTO t2 SELECT c1 FROM t1 LIMIT 1`

The PR aims to 2 points:

- Improve `INSERT INTO t2 SELECT c1 FROM t1 LIMIT 1` to `CollectLimitExec`
- Add a flag to identifies `CollectLimitExec` as subExec without shuffling and scan all data. 

Example:
> CREATE TABLE t1(id STRING) USING parquet
CREATE TABLE t2(id STRING) USING parquet
INSERT INTO t1 SELECT * FROM t2 LIMIT 5

Before:
Before PR

After:
After PR

### Why are the changes needed?
Optimize logic

### Does this PR introduce _any_ user-facing change?
No, optimize only

### How was this patch tested?
Unit Test and manually test.

### CODE REVIEW

**Comment by yikf** [comment]
@zhengruifeng @cloud-fan Could you take a look when you have a time?

**Comment by cloud-fan** [comment]
I'm not sure if this is a good idea. Yes, you save one shuffle, but you also need to collect data to the driver side and distribute it later to run table insertion, which I don't think is cheaper than a shuffle, and is probably more fragile (causes driver OOM)

**Comment by yikf** [comment]
> I'm not sure if this is a good idea. Yes, you save one shuffle, but you also need to collect data to the driver side and distribute it later to run table insertion, which I don't think is cheaper than a shuffle, and is probably more fragile (causes driver OOM)

1. limit scene which data is less is not prone occur OOM, and CollectLimitExec's outputPartitioning is `SinglePartition`, It is similar to Driver collect limit.
2. If collectExec's shuffle reader node and insert are on the same node, it does reduce exactly the cost of distribution, but if it is not on the same node, it also needs to be distributed. However, the cost of distribution should be less than that of the shuffle operator.

**Comment by cloud-fan** [comment]
> limit scene which data is less is not prone occur OOM

We can't rely on assumptions. Technically the limit can be arbitrarily big. So I think writing to disk and reading back (shuffle) is better than collecting to memory and re-distribute. BTW AQE can optimize shuffles much better.

**Pull request closed without merging**
