### PR TITLE
[SPARK-39256][CORE] Reduce multiple file attribute calls of `JavaUtils#deleteRecursivelyUsingJavaIO`

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr is a minor fix: `JavaUtils#deleteRecursivelyUsingJavaIO` method  performs multiple file attribute calls, this pr change to use `Files.readAttributes` instead of them.

### Why are the changes needed?
Reduce multiple file attribute calls.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass Github Actions

### CODE REVIEW

**Review by srowen — APPROVED** [review]

**Comment by srowen** [comment]
Looks fine, but can you try to rerun tests?

**Comment by LuciferYang** [comment]
[127a515](https://github.com/apache/spark/pull/36636/commits/127a51581da94995b51ece11caf181200416d3bf) merge with master and rerun all tests

**Comment by LuciferYang** [comment]
> Looks fine, but can you try to rerun tests?

GA passed

**Comment by srowen** [comment]
Merged to master

**Comment by LuciferYang** [comment]
thanks @srowen

**Pull request closed without merging**
