### PR TITLE
[SPARK-48441][SQL][FOLLOWUP] Fix StringTrim behaviour for UTF8_LCASE collation

### PR DESCRIPTION
**Pull request by uros-db**
### What changes were proposed in this pull request?
Fix how `StringTrim*` expressions handle edge cases with one-to-many case mapping, by updating the lowercase trimming logic that matches multiple characters from the `srcString` to a single character in `trimStr`. These methods now correctly follow the iterative "longest possible match" behaviour (proposed for StringTrim in the original PR).

### Why are the changes needed?
Fix a subtle bug in `trim`-like functions.

Example:
```
trim("ii\u0307", "İi"); -- returns: "\u0307" (wrong), instead of "" (correct)
```

### Does this PR introduce _any_ user-facing change?
Yes, trim* function behaviour is slightly altered for UTF8_LCASE.

### How was this patch tested?
New tests in `CollationSupportSuite`.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Review by MaxGekk — COMMENTED** [review]
@uros-db Please, move the example to the section `What changes were proposed in this pull request?` like

Before:
example

After:
example

Add add short description of the bug fix to the section: `What changes were proposed in this pull request?
`

**Review by mkaravel — APPROVED** [review]
The changes in this PR look very much (for good a reason: it is the same logic) with the changes for the trim expression. Do you think we could consolidate the code a bit and avoid some of the duplication? Not a blocker for this PR, but rather something to look at to improve the code base if possible.

**Review by MaxGekk — APPROVED** [review]

**Comment by MaxGekk** [comment]
+1, LGTM. Merging to master.
Thank you, @uros-db and @mkaravel for review.

**Comment by MaxGekk** [comment]
@uros-db Only master suffers from the issue, so, we don't need to backport your changes, right?

**Review by uros-db — COMMENTED** [review]
@MaxGekk yes, this is a collation-related code change (master only)

**Pull request closed without merging**
