### PR TITLE
[SPARK-14736][core] Deadlock in registering applications while the Master is in the RECOVERING mode

### PR DESCRIPTION
**Pull request by nirandaperera**
## What changes were proposed in this pull request?

this PR fixes the issue SPARK-14736 Deadlock in registering applications while the Master is in the RECOVERING mode. 
Proposed solution is to keep the registering apps in a separate list when the Master is in the RECOVERING mode and once the recovery is complete, these apps will be registered back. Pls refer the JIRA for more information 
## How was this patch tested?

I have tested the patch manually

### CODE REVIEW

**Comment by mridulm** [comment]
You will need to make this thread safe - the applications are added/re-registered from separate threads, right ?

**Comment by HyukjinKwon** [comment]
Maybe we should correct the title just like the others. Also, the title looks truncated.

**Comment by nirandaperera** [comment]
@mridulm do you mean to say, the method `private def registerApplication(app: ApplicationInfo): Unit = {` needs to synchronized?

**Comment by mridulm** [comment]
No.
Updates to waitingAppsWhileRecovering happens from different threads right ? Hence you will need to protect it.

**Comment by nirandaperera** [comment]
@mridulm You are correct. But if we check the register application method, 

`  private def registerApplication(app: ApplicationInfo): Unit = {
    val appAddress = app.driver.address
    if (addressToApp.contains(appAddress)) {
      logInfo("Attempted to re-register application at same address: " + appAddress)
      return
    }

    applicationMetricsSystem.registerSource(app.appSource)
    apps += app
    idToApp(app.id) = app
    endpointToApp(app.driver) = app
    addressToApp(appAddress) = app
    waitingApps += app
  }`

there are similar array buffers which are getting updated without being synchronized. That is why I omitted making the waitingAppsWhileRecovering synchronized. 
am I doing anything wrong there?

**Comment by mridulm** [comment]
No, you are right - this is called only from the event loop - which should ensure thread safety.
I misread where the re-registeration was happening as outside of the event loop.
Please ignore my comment.

**Comment by nirandaperera** [comment]
Great! can we get this PR merged then? Is there anything else I should do in order to get this merged?

**Comment by BryanCutler** [comment]
Hi @nirandaperera , I'm not too sure about the Master recovery process so I can't really comment on your code, but it would make a much stronger case for this PR if you could include a test that fails without this change.

**Comment by nirandaperera** [comment]
@BryanCutler I was looking for some unit tests which could simulate this scenario in the Master.scala class, but I couldn't find any. But i think I can reproduce this in an integration test environment. can you point me to the spark integration tests?

**Comment by andrewor14** [comment]
ok to test

**Comment by rxin** [comment]
@andrewor14 did you review this?

**Comment by srowen** [comment]
Looks reasonable to me but I don't know this code very well. Also @kayousterhout maybe or @squito

**Comment by kayousterhout** [comment]
@aarondav might be the right person to look at this -- looks like he wrote most of the original code around the "RECOVERING" state way back in 2013.

**Comment by squito** [comment]
unfortunately I'm not very knowledgeable here either.  I agree that this change looks reasonable, but also wish there was a test case for it.  I don't think there is any good integration test framework, and it seems there aren't any tests for recovery state now, so you'd have to build that out yourself.  One possibility -- "local-cluster" mode is closely related to a standalone cluster -- maybe that could be used to create a test?

**Comment by nirandaperera** [comment]
@squito hey. Thanks for the heads up. let me check on that and try to come up with a test

**Comment by jiangxb1987** [comment]
Are you still working on this? @nirandaperera

**Pull request closed without merging**
