### PR TITLE
[SPARK-39295][PYTHON][DOCS] Improve documentation of pandas API support list

### PR DESCRIPTION
**Pull request by beobest2**
### What changes were proposed in this pull request?

The description provided in the supported pandas API list document or the code comment needs improvement. 
Also, there are cases where the link of the function property provided in the document is not connected, so it needs to be corrected.

### Why are the changes needed?

To improve document readability for users and to link to the correct API document.

### Does this PR introduce _any_ user-facing change?

Yes, the "Supported pandas APIs" page has changed as below.
Screen Shot 2022-05-30 at 10 51 12 PM

### How was this patch tested?

Manually check the links in the documents & the existing doc build should be passed.

### CODE REVIEW

**Comment by beobest2** [comment]
@HyukjinKwon The current 'supported API generation' function dynamically compares the modules of `PySpark.pandas` and `pandas` to find the difference. At this time, the inherited class is also aggregated, and the link is not generated correctly (such as `CategoricalIndex.all()`) because it does not match the pattern of each API document. 

ex>
Screen Shot 2022-05-30 at 11 27 55 PM

```
.../reference/pyspark.pandas/api/pyspark.pandas.CategoricalIndex.add_categories.html
    >> exists
.../reference/pyspark.pandas/api/pyspark.pandas.CategoricalIndex.all.html
    >> not exists 
```

So, I thought about the options below:

1. Creates by excluding methods that exist in the parent class.
 
   - For example, in the list of CategoricalIndex class, the list of functions available by inheriting the Index function (methods of base class) is removed.

2. Includes all methods, and creates a document link to the parent class by identifying whether a document corresponding to the path of the parent class exists.

    - In my opinion, the part of "determining whether the corresponding document exists" seems to be difficult, and option 1 seems appropriate because the existing pandas documentation does not document all methods of the parent class. (ex> https://pandas.pydata.org/docs/reference/api/pandas.CategoricalIndex.categories.html?highlight=category)

**Comment by HyukjinKwon** [comment]
@beobest2 I am fine with separating PRs. I can merge this one, and you can go ahead for a separate fix for the link problem.

I remember there are some options in Sphinx about inherited docs, e.g.) https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#directive-option-automodule-members
From a cursory look, we can let the `autosummary` generate the inherited documentations and link it here (?). Maybe we can take a closer look at how they handled it.

**Review by HyukjinKwon — APPROVED** [review]
LGTM as is. For the link problem, feel free to create a separate JIRA if you want. BTW, the PR title seems truncated - should probably fix it.

**Review by itholic — APPROVED** [review]
Looks pretty good

except


> BTW, the PR title seems truncated - should probably fix it.

**Comment by beobest2** [comment]
@HyukjinKwon @itholic With a separate PR, I'd like to look into some options in Sphinx about inherited documents. 
The title of the truncated PR has been corrected.

**Comment by HyukjinKwon** [comment]
Merged to master.

@beobest2 would you mind creating a backport PR to fix https://github.com/apache/spark/blob/branch-3.3/python/docs/source/user_guide/pandas_on_spark/supported_pandas_api.rst too please?

**Comment by beobest2** [comment]
@HyukjinKwon  I just have created a backport PR to branch-3.3 (https://github.com/apache/spark/pull/36748). Please check whether I did it right.

**Comment by HyukjinKwon** [comment]
@beobest2, is there any progress on https://github.com/apache/spark/pull/36729#issuecomment-1141632078?

**Comment by beobest2** [comment]
@HyukjinKwon I've been missing out because there have been some other workloads lately. I will be able to register for PR this week. I have created an issue here. (https://issues.apache.org/jira/browse/SPARK-39456)

**Comment by HyukjinKwon** [comment]
Sure, thanks for tracking this.

**Pull request closed without merging**
