### PR TITLE
[SPARK-12950][SQL] Cache newly accessed hashtable entry in BytesToBytesMap

### PR DESCRIPTION
**Pull request by viirya**
JIRA: https://issues.apache.org/jira/browse/SPARK-12950

As described in JIRA, it is observed that when aggregate with grouping keys, profiling show that lookup in BytesToBytesMap took about 90% of the CPU time.

This patch doesn't change how the lookup works. But we find that every time it is going to call `safeLookup` method, we need to look up for a key from the beginning. So if we want to find a same key, we will perform the same lookup process (comparing hashcode, comparing keys,hitting collision...). This patch tries to cache the newly accessed key and returns the entry early if it is in cache.

### CODE REVIEW

**Comment by rxin** [comment]
Did you do any performance test?

**Comment by davies** [comment]
I don't think this could save much, even with cache hit. It will still calculate the hash, compare the key as bytes, update the address.

**Comment by viirya** [comment]
Ok.

**Comment by viirya** [comment]
The point is if you need to find your key after several comparings, next time you face the same key, you still need to go through this process of wrong comparings. With cache, you can get the address early without above.

**Comment by viirya** [comment]
I don't think you can get final address without any hashcodeing or key comparing.

**Comment by davies** [comment]
With the fill ratio under 70% (will grow after that), it usually does one probe most of the time. Another question is that, the cache hit rate will be very low in practice (considering thousands of unique keys).

**Comment by viirya** [comment]
If so, I am curious what makes lookup cost much cpu time, hashcoding? key comparing?

**Comment by davies** [comment]
Profiling using jvisualvm will help a lots, here are the things that take most of the time:

1. decode address from Long to baseObject and offset
2. calculate hash code
3. compare the bytes (equality check)

**Pull request closed without merging**
