### PR TITLE
[SPARK-14346][SQL] Show Create Table (Native)

### PR DESCRIPTION
**Pull request by xwu0226**
This is a rebased version of [#12132](https://github.com/apache/spark/pull/12132) and [#12406](https://github.com/apache/spark/pull/12406)
## What changes were proposed in this pull request?

Allow users to issue "`SHOW CREATE TABLE`" command natively in SparkSQL. 
-- For tables that are created by Hive, this command will display the DDL in hive syntax. If the syntax includes `CLUSTERED BY, SKEWED BY or STORED BY` clause, there will be a warning message saying that this DDL is not supported in SparkSQL native DDL yet. 

-- For tables that are created by datasource DDL, such as "`CREATE TABLE... USING ... OPTIONS (...)`", it will show the DDL in this syntax. 

-- For tables that are created by dataframe API, such as "`df.write.partitionBy(...).saveAsTable(...)`", currently the command will display DDL with the syntax "CREATE TABLE.. USING...OPTIONS(...)". However, this syntax lose the partitioning information. It is proposed to display create table in the dataframe API format, such as `<DataFarme>.write.partitionBy("a").bucketBy("c").format("parquet").saveAsTable("T1")`
## How was this patch tested?

Unit tests are created.

### CODE REVIEW

**Comment by xwu0226** [comment]
@yhuai @andrewor14 Thanks!

**Comment by liancheng** [comment]
test this please

**Comment by xwu0226** [comment]
@liancheng Thanks for triggering the test! I am looking into the test failure.

**Comment by gatorsmile** [comment]
retest this please

**Comment by xwu0226** [comment]
@yhuai @liancheng , I see PR [#12734](https://github.com/apache/spark/pull/12734) takes care of the PARTITIONED BY and CLUSTERED BY (with SORTED BY) clause for CTAS syntax, but not for non-CTAS syntax.  Now I need to change my PR to adapt to this change, which means that the generated DDL will be something like `create table t1 (c1 int, ...) using .. options (..) partitioned by (..) clustered by (...) sorted by (...) in ... buckets`. But there won't be a "select clause" following it since we do not have the original query. But such generated query will not run because [#12734](https://github.com/apache/spark/pull/12734) does not support it.  Can we add a fake select clause with a warning message?

Also DataFrameWriter.saveAsTable case is like CTAS. Can we then generate the DDL as a regular CTAS syntax? This will change my current implementation in this PR. 
Please advice, thanks a lot!

**Comment by srowen** [comment]
@xwu0226 I think this is superseded by https://github.com/apache/spark/pull/12781 ?

**Comment by xwu0226** [comment]
@srowen Yes, for datasource table. This PR also includes the work for hive syntax DDL too. I see #12781 mentions that there will be followup PR taking care of the hive syntax DDL. So I wondering whether I should continue on this PR. I can close this one if there is no need. Thanks!

**Comment by liancheng** [comment]
Hey @xwu0226, sorry that I didn't explain why I opened another PR for the same issue, was in code rush for 2.0...

So one of the considerations for all the native DDL commands is that we don't want these DDL commands to rely on Hive anymore. This is because we'd like to remove Hive dependency from Spark SQL core and gradually make Hive a separate data source in the future. This means, we shouldn't add new code in places like `HiveClientImpl`. These new DDL command should be implemented upon interfaces like `CatalogTable`.

One apparent problem of this approach is that, current Spark SQL interfaces don't capture all semantics of Hive. For example, some table metadata like skew spec is not covered in `CatalogTable` yet. Our general strategies are:

1. For easy ones, like "owner" and "compressed" in #12844, we may just add them to the interface and leverage them.
2. For features that are not supported in Spark SQL, for example, skew spec, we can simply ignore them for now, since Spark can't handle them anyway.

There will be a follow-up of #12781 to add support for Hive tables. After offline discussion with @yhuai, we decided to add a flag in `CatalogTable` to indicate that whether there unrecognized metadata provided by the underlying external catalog, but not translated and included in `CatalogTable`. In this way, when applying `SHOW CREATE TABLE` to tables containing such metadata, this flag can be set to true, and we can simply refuse to output anything by checking this flag. This makes sense because even if you add things like skew spec in the result of `SHOW CREATE TABLE`, Spark can't handle the generated DDL statement

**Comment by xwu0226** [comment]
@liancheng Thank you for the detail explanation!! Yeah. if the goal is to make sure Spark SQL can handle the generated DDL, then, we need to miss some hive features for now. I will close this PR.

**Pull request closed without merging**
