### PR TITLE
[SPARK-26866][DSTREAMS] Support checkpoint with SubSequenceNumber to external/kinesis-asl

### PR DESCRIPTION
**Pull request by kty1965**
## What changes were proposed in this pull request?

Support checkpoint with SubSequenceNumber to external/kinesis-asl

## How was this patch tested?

manual tests

Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Comment by gaborgsomogyi** [comment]
* Please open a PR against master branch. It's committer responsibility to backport (however as I see this is a feature and not a bug which is not backported).
* In the title please change `[SS]` to `[DSTREAMS]` because SS = Structured Streaming.
* What is the use-case exactly? Why is it needed?

**Comment by kty1965** [comment]
- I will re-open PR against master.
- ok, change the title to [DSTREAM].
- we would like to use KPL(Kinesis Producer Library) which is optimize record size. But this library use called UserRecord which exetended Recrod has SubsequenceNumber.

Kinesis-asl's checkpointer does not cotrol the subsequenceNumber, only sequence number. When re-submit spark stream application, processed duplicate record.

We want to reduce this duplicate record.

**Comment by gaborgsomogyi** [comment]
To reopen against master this has to be closed...
Another suggestion when you open the new one please add a little bit more description about the problem what the PR would like to solve (3rd bullet point). Without knowing kinesis super deep, are there no tests which cover this or just create such? The chance will be bigger a committer feel more confident and merge it...

**Comment by dongjoon-hyun** [comment]
Hi, @kty1965 
We released Apache Spark `2.3.4` as the final release and `branch-2.3` became EOL according to our release cadence. I'll close this PR.
- https://spark.apache.org/release-process.html

**Pull request closed without merging**
