### PR TITLE
[SPARK-23419][SPARK-23416][SS] data source v2 write path should re-throw interruption exceptions directly

### PR DESCRIPTION
**Pull request by cloud-fan**
## What changes were proposed in this pull request?

Streaming execution has a list of exceptions that means interruption, and handle them specially. `WriteToDataSourceV2Exec` should also respect this list and not wrap them with `SparkException`.

## How was this patch tested?

existing test.

### CODE REVIEW

**Comment by gatorsmile** [comment]
Also cc @tdas @marmbrus

**Comment by mgaido91** [comment]
This seems good to me. My only concern is that we still have to rely/maintain a list of exceptions thrown when the stop method is called... This approach seems not very robust to me, but I don't have a better suggestion.

**Comment by jose-torres** [comment]
LGTM also. I'll still take it as an action item to try and think of a cleaner way to handle stopping a stream.

**Comment by zsxwing** [comment]
LGTM

**Comment by cloud-fan** [comment]
thanks, merging to master/2.3! Since it's a bug fix so I included it in branch 2.3, please let me know if you have other concerns, cc @sameeragarwal   @marmbrus

**Pull request closed without merging**
