### PR TITLE
[SPARK-48738][SQL] Correct since version for built-in func alias `random`, `position`, `mod`, `cardinality`, `current_schema`, `user`, `session_user`,`char_length`,`character_length`

### PR DESCRIPTION
**Pull request by wayneguow**
### What changes were proposed in this pull request?

This PR aims to correct since version for built-in method alias `random`, `position`, `mod`, `cardinality`, `current_schema`, `user`, `session_user`, `char_length`, `character_length`.

- https://issues.apache.org/jira/browse/SPARK-28086  random 3.0.0 (rand 1.5.0)

- https://issues.apache.org/jira/browse/SPARK-20754 position 2.3.0 (locate 1.5.0)    

- https://issues.apache.org/jira/browse/SPARK-20754 mod 2.3.0 (% 1.0.0)

- https://issues.apache.org/jira/browse/SPARK-23923 cardinality 2.4.0  (size 1.5.0)

- https://issues.apache.org/jira/browse/SPARK-41323 current_schema  3.4.0  (current_database 1.6.0)

- https://issues.apache.org/jira/browse/SPARK-39138 user 3.4.0 (current_user 3.2.0)

- https://issues.apache.org/jira/browse/SPARK-44860 session_user 4.0.0  (current_user 3.20)

- https://issues.apache.org/jira/browse/SPARK-20749 char_length 2.3.0 (len 1.5.0)

- https://issues.apache.org/jira/browse/SPARK-20749 character_length 2.3.0 (len 1.5.0)

### Why are the changes needed?

The default since version of those method alias is wrong.  

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

- Pass GA
- Make a  check by creating docs manually: `./build/mvn -DskipTests clean package & cd sql & sh create-docs.sh`

Take `current_schema` as an example: 

**Before: the official website**
image
**After: my local site**
image

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by wayneguow** [comment]
Gentle ping @HyukjinKwon  @LuciferYang

**Comment by yaooqinn** [comment]
> How was this patch tested?
Pass GA.

Can you please share screenshots of `sql/api/index.html` for verification instead of relying on GitHub Actions?

**Comment by wayneguow** [comment]
> > How was this patch tested?
> > Pass GA.
> 
> Can you please share screenshots of `sql/api/index.html` for verification instead of relying on GitHub Actions?
Yes, I updated it in the description.

**Comment by wayneguow** [comment]
> > How was this patch tested?
> > Pass GA.
> 
> Can you please share screenshots of `sql/api/index.html` for verification instead of relying on GitHub Actions?
Yes, I updated it in the description.

**Review by allisonwang-db — APPROVED** [review]
Good catch!

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by wayneguow** [comment]
Thank you all. @HyukjinKwon @yaooqinn @allisonwang-db

**Pull request closed without merging**
