### PR TITLE
[SPARK-24292][SQL] Proxy user cannot connect to HiveMetastore in loca…

### PR DESCRIPTION
**Pull request by LantaoJin**
…l mode

## What changes were proposed in this pull request?

[#17335](https://github.com/apache/spark/pull/17335) has fixed the similar issue in yarn mode. Actually, in local mode we still face this problem.

If user want to create a table. Local mode is much easier than launching an AM in yarn.
bin/spark-sql --master local --proxy-user x_user 
But it doesn't work:

> Caused by: MetaException(message:Could not connect to meta store using any of the URIs provided. Most recent failure: org.apache.thrift.transport.TTransportException: GSS initiate failed
at org.apache.thrift.transport.TSaslTransport.sendAndThrowMessage(TSaslTransport.java:232)
at org.apache.thrift.transport.TSaslTransport.open(TSaslTransport.java:316)
at org.apache.thrift.transport.TSaslClientTransport.open(TSaslClientTransport.java:37)
at org.apache.hadoop.hive.thrift.client.TUGIAssumingTransport$1.run(TUGIAssumingTransport.java:52)
at org.apache.hadoop.hive.thrift.client.TUGIAssumingTransport$1.run(TUGIAssumingTransport.java:49)
at java.security.AccessController.doPrivileged(Native Method)
at javax.security.auth.Subject.doAs(Subject.java:422)
at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698)
at org.apache.hadoop.hive.thrift.client.TUGIAssumingTransport.open(TUGIAssumingTransport.java:49)
at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.open(HiveMetaStoreClient.java:420)
at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.<init>(HiveMetaStoreClient.java:236)
at org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient.<init>(SessionHiveMetaStoreClient.java:74)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.apache.hadoop.hive.metastore.MetaStoreUtils.newInstance(MetaStoreUtils.java:1521)
at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.<init>(RetryingMetaStoreClient.java:86)
at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.getProxy(RetryingMetaStoreClient.java:132)
at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.getProxy(RetryingMetaStoreClient.java:104)
at org.apache.hadoop.hive.ql.metadata.Hive.createMetaStoreClient(Hive.java:3005)
at org.apache.hadoop.hive.ql.metadata.Hive.getMSC(Hive.java:3024)
at org.apache.hadoop.hive.ql.session.SessionState.start(SessionState.java:503)
at org.apache.spark.sql.hive.client.HiveClientImpl.<init>(HiveClientImpl.scala:192)

## How was this patch tested?
Run the command below to see if it works.
bin/spark-sql --master local --proxy-user x_user

### CODE REVIEW

**Comment by LantaoJin** [comment]
@jerryshao @vanzin

**Comment by LantaoJin** [comment]
Now the test case succeeds.

**Comment by wangyum** [comment]
This problem seems to have been fixed, can you try [v2.3.1-rc1](https://github.com/apache/spark/releases/tag/v2.3.1-rc1)?

**Comment by LantaoJin** [comment]
@gatorsmile @cloud-fan Could you help to review this?

**Comment by vanzin** [comment]
How is this different from SPARK-23639 or, in other words, why doesn't the fix for that bug work for you?

**Comment by LantaoJin** [comment]
@vanzin Seems duplicated. Let me check.

**Comment by LantaoJin** [comment]
Cool, SPARK-23639 also works for me. Close.

**Pull request closed without merging**
