### PR TITLE
[SPARK-37091][R] SystemRequirements to include Java < 18

### PR DESCRIPTION
**Pull request by Bidek56**
### What changes were proposed in this pull request?
Modifying SystemRequirements to include Java <= 17

### Why are the changes needed?
Currently Java is limited to version 11

### How was this patch tested?
```
$ build/mvn -Phadoop-3.2 -Psparkr -DskipTests package
$ R/install-dev.sh
$ R/run-tests.sh
```

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Thank you for the suggestion, @Bidek56 . Could you include your actual result if you test SparkR with Java 17 already?

```
$ build/mvn -Phadoop-3.2 -Psparkr -DskipTests package
$ R/install-dev.sh
$ R/run-tests.sh
```

At least, I agree that this PR unblocks SparkR installation on Java 17.

**Review by srowen — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
I agree with this change, and LGTM but I would like to understand how this change interacts with what.

**Comment by Bidek56** [comment]
> I agree with this change, and LGTM but I would like to understand how this change interacts with something external.

This [issue](https://github.com/jupyter/drumsticks/issues/1498) is affected by the Java 11 limit

**Comment by HyukjinKwon** [comment]
https://github.com/jupyter/drumsticks repo seems private. Okay, if something is affected, then it's fine - I asked because this Java versions in description are not used in CRAN and rather just a metadata up to my knowledge.

**Comment by HyukjinKwon** [comment]
Mind enabling GitHub Actions in your forked repository? Apache Spark leverages contributor's resources in forked repository in their PRs (https://github.com/apache/spark/pull/34371/checks?check_run_id=3977747161).

**Comment by Bidek56** [comment]
> https://github.com/jupyter/drumsticks repo seems private. Okay, if something is affected, then it's fine - I asked because this Java versions in description are not used in CRAN and rather just a metadata up to my knowledge.

It's a public [repo](https://github.com/jupyter/docker-stacks/issues/1498)

**Comment by Bidek56** [comment]
I did enabled GA but after the failure, not sure to rerun the action, besides using an API.

**Review by HyukjinKwon — APPROVED** [review]

**Pull request closed without merging**
