### PR TITLE
[SPARK-26034][PYTHON][TESTS] Break large mllib/tests.py file into smaller files

### PR DESCRIPTION
**Pull request by BryanCutler**
## What changes were proposed in this pull request?

This PR breaks down the large mllib/tests.py file that contains all Python MLlib unit tests into several smaller test files to be easier to read and maintain.

The tests are broken down as follows:
```
pyspark
├── __init__.py
...
├── mllib
│   ├── __init__.py
...
│   ├── tests
│   │   ├── __init__.py
│   │   ├── test_algorithms.py
│   │   ├── test_feature.py
│   │   ├── test_linalg.py
│   │   ├── test_stat.py
│   │   ├── test_streaming_algorithms.py
│   │   └── test_util.py
...
├── testing
...
│   ├── mllibutils.py
...
```

## How was this patch tested?

Ran tests manually by module to ensure test count was the same, and ran `python/run-tests --modules=pyspark-mllib` to verify all passing with Python 2.7 and Python 3.6. Also installed scipy to include optional tests in test_linalg.

### CODE REVIEW

**Comment by BryanCutler** [comment]
Dist by line count:
```
313 ./test_algorithms.py
201 ./test_feature.py
642 ./test_linalg.py
197 ./test_stat.py
523 ./test_streaming_algorithms.py
115 ./test_util.py
```

**Comment by BryanCutler** [comment]
cc @HyukjinKwon @squito

**Review by HyukjinKwon — APPROVED** [review]
LGTM. I left both comments but we could do that in a followup.

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
@BryanCutler, let me merge this. Let's do the ML one and then clean up both comments throughout ML and MLlib at once.

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
