### PR TITLE
[SPARK-24654][BUILD][FOLLOWUP] Update, fix LICENSE and NOTICE, and specialize for source vs binary

### PR DESCRIPTION
**Pull request by srowen**
## What changes were proposed in this pull request?

Fix location of licenses-binary in binary release, and remove binary items from source release

## How was this patch tested?

N/A

### CODE REVIEW

**Comment by srowen** [comment]
CC @cloud-fan  This one doesn't block 2.4.0 but would be nice to have. Certainly if there's a second RC.

**Comment by cloud-fan** [comment]
Thanks for the fix! I'm not familiar with part though, let's ping @vanzin @felixcheung @jerryshao

**Review by felixcheung — APPROVED** [review]

**Review by jerryshao — APPROVED** [review]
LGTM.

**Comment by srowen** [comment]
Merged to master/2.4

**Pull request closed without merging**
