### PR TITLE
[SPARK-42143][UI] Handle null string values in RDDStorageInfo/RDDDataDistribution/RDDPartitionInfo

### PR DESCRIPTION
**Pull request by gengliangwang**
### What changes were proposed in this pull request?

Similar to https://github.com/apache/spark/pull/39666, this PR handles null string values in RDDStorageInfo/RDDDataDistribution/RDDPartitionInfo
### Why are the changes needed?

Properly handles null string values in the protobuf serializer.
### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

New UTs

### CODE REVIEW

**Comment by gengliangwang** [comment]
cc @LuciferYang

**Review by LuciferYang — APPROVED** [review]
+1, LGTM

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by dongjoon-hyun** [comment]
Merged to master, @gengliangwang .

**Comment by gengliangwang** [comment]
@dongjoon-hyun @LuciferYang Thanks for the review!

**Pull request closed without merging**
