### PR TITLE
[Spark-11158][SQL] Modified _verify_type() to be more informative on Errors by presenting the Object

### PR DESCRIPTION
**Pull request by lababidi**
The _verify_type() function had Errors that were raised when there were Type conversion issues but left out the Object in question. The Object is now added in the Error to reduce the strain on the user to debug through to figure out the Object that failed the Type conversion. 

The use case for me was a Pandas DataFrame that contained 'nan' as values for columns of Strings.

### CODE REVIEW

**Comment by andrewor14** [comment]
@lababidi please file a JIRA and add it to the title of the PR. See how other PRs are opened.

**Comment by JoshRosen** [comment]
Jenkins, this is ok to test.

**Comment by JoshRosen** [comment]
LGTM.

**Comment by JoshRosen** [comment]
I'm going to merge this into master. Thanks!

**Pull request closed without merging**
