### PR TITLE
[SPARK-3873] [build] Add style checker to enforce import ordering.

### PR DESCRIPTION
**Pull request by vanzin**
The checker tries to follow as closely as possible the guidelines of
the code style document, and makes some decisions where the guide is
not clear. In particular:
- wildcard imports come first when there are other imports in the
  same package
- multi-import blocks come before single imports
- lower-case names inside multi-import blocks come before others

In some projects, such as graphx, there seems to be a convention to
separate o.a.s imports from the project's own; to simplify the
checker, I chose not to allow that, which is a strict interpretation
of the code style guide, even though I think it makes sense.

Since the checks are based on syntax only, some edge cases may
generate spurious warnings; for example, when class names start
with a lower case letter (and are thus treated as a package name
by the checker).

The checker is currently only generating warnings, and since there
are many of those, the build output does get a little noisy. The
idea is to fix the code (and the checker, as needed) little by little
instead of having a huge change that touches everywhere.

### CODE REVIEW

**Comment by vanzin** [comment]
This is the same code I sent out a long time ago, updated to also hook up to the maven build. I tried both sbt and maven. There is a huge number of warnings, so I won't even try to fix them (in this change or a separate one), but since there seems to be a push to add more style checks, thought I might send this out again.

**Comment by andrewor14** [comment]
Will this even pass tests in its current state? I imagine we violate the import ordering in a lot of places currently.

**Comment by rxin** [comment]
@andrewor14 he's doing warning level checks right now -- so there will be lots of warnings but still pass. Let's see how many warnings there are ...

**Comment by andrewor14** [comment]
retest this please

**Comment by vanzin** [comment]
The PR builder script redirects the scalastyle output to a file and deletes it... so you don't see the warnings in the output and can't find them on the jenkins machines either.

But you'll see them if you try this change locally.

**Comment by rxin** [comment]
What happens to errors? Are they also redacted?

**Comment by vanzin** [comment]
See `dev/scalastyle`. The script greps for errors and prints them out, everything else is lost. It's trivial to change the script to keep the generated file with all errors and warnings.

**Comment by rxin** [comment]
@vanzin - thanks, this looks great.

Can you do 3 things?

1. Make the import ordering configurable.
2. The style rule is pretty complicated. Add some unit tests for it.
3. Submit a pull request against scalastyle proper.

The reason is we should avoid one-offs that make it harder to upgrade in the future. We can merge this as soon as there is a pull request against scalastyle and way to move forward. And once that is merged into scalastyle and scalastyle releases a new version, we can remove our one-off rule.

This is what we have done for all the one-off rules in the past.

**Comment by JoshRosen** [comment]
By the way, if you make this configurable then I'd model the configuration language / format after IntelliJ's import ordering configuration dialog.

**Comment by vanzin** [comment]
I filed a scalastyle PR (see link above) which contains tests, so I'll avoid adding those tests to this PR.

**Comment by sujkh85** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

sujkh@naver.com 님께 보내신 메일 <Re: [spark] [SPARK-3873] [build] Add style checker to enforce import ordering. (#6502)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by andrewor14** [comment]
LFTM. @rxin?

**Comment by JoshRosen** [comment]
@vanzin, it looks like the Scalastyle PR was merged: https://github.com/scalastyle/scalastyle/pull/147

Given this, can you update this PR to configure Scalastyle to use this new rule?

**Comment by vanzin** [comment]
It was merged but I don't see a new scalastyle release. I was waiting for that before updating this pr.

**Comment by JoshRosen** [comment]
Can you comment on https://github.com/scalastyle/scalastyle/pull/154 to voice your support for a new Scalastyle release? The delays in getting new Scalastyle and Scalastyle-SBT versions published are causing a lot of pain for folks running Scala 2.10.5+, since the current master also contains bugfixes for a Scalariform parser issue.

**Comment by JoshRosen** [comment]
Err, sorry, the link above should have been https://github.com/scalastyle/scalastyle/pull/157

**Comment by JoshRosen** [comment]
Still no Scalastyle release :(

I tried bumping that ticket again.

**Comment by JoshRosen** [comment]
Now that Scalastyle 0.8.0 has been released, I think we can revive this PR. I've opened #10112 to bump the SBT and Scalastyle versions.

**Comment by vanzin** [comment]
I'm looking into it.

**Comment by vanzin** [comment]
I don't expect the tests to pass; there were style errors (unrelated to import ordering) when I tried things locally.

**Comment by vanzin** [comment]
not that it should matter, but retest this please

**Comment by vanzin** [comment]
I'm gonna merge this so we can start cleaning things up before enabling errors.

**Pull request closed without merging**
