### PR TITLE
[SPARK-36483][CORE][TESTS] Fix intermittent test failures at Netty 4.1.52+

### PR DESCRIPTION
**Pull request by Victsm**
### What changes were proposed in this pull request?

Fix an intermittent test failure due to Netty dependency version bump.
Starting from Netty 4.1.52, its AbstractChannel will throw a new `StacklessClosedChannelException` for channel closed exception.
A hardcoded list of Strings to match for channel closed exception in `RPCIntegrationSuite` was not updated, thus leading to the intermittent test failure reported in #33613

### Why are the changes needed?

Fix intermittent test failure

### Does this PR introduce _any_ user-facing change?

No

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Are all latest netty-all versions the same, @Victsm ? Can we avoid the failures at the latest Netty?

**Comment by mridulm** [comment]
+CC @HyukjinKwon, @Ngone51

**Comment by mridulm** [comment]
Ok to test

**Comment by venkata91** [comment]
Since this is not related to SPARK-36378, should we have a separate JIRA to address this issue?

**Comment by Victsm** [comment]
> Are all latest netty-all versions the same, @Victsm ? Can we avoid the failures at the latest Netty?

@dongjoon-hyun looking at the latest from netty 4.1, it's still using this newly introduced `StacklessClosedChannelException`.
I think it's a permanent switch in netty from `java.nio.channels.ClosedChannelException` to this new `StacklessClosedChannelException`.

**Comment by dongjoon-hyun** [comment]
Thank you for checking it, @Victsm .

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
@Victsm would you mind retriggering https://github.com/linkedin/spark/actions/runs/1121218315 just for doubly sure?

**Comment by HyukjinKwon** [comment]
retest this please

**Review by Ngone51 — APPROVED** [review]
Good catch!

**Review by zhuqi-lucas — APPROVED** [review]
Good catch!

**Review by srowen — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
@Victsm would you mind retriggering https://github.com/linkedin/spark/actions/runs/1121218315? you can click "Re-run jobs" buttom.

**Comment by mridulm** [comment]
Ok to test

**Comment by HyukjinKwon** [comment]
Yeah, I think it's fine to go ahead either. +1

**Comment by mridulm** [comment]
Merged to master and branch-3.2 +CC @gengliangwang 

Thanks for fixing this @Victsm !
Thanks for the reviews @dongjoon-hyun, @HyukjinKwon, @Ngone51, @srowen, @zhuqi-lucas :-)

**Pull request closed without merging**
