### PR TITLE
[SPARK-46254][PYTHON] Remove stale Python 3.8/3.7 version checking

### PR DESCRIPTION
**Pull request by HyukjinKwon**
### What changes were proposed in this pull request?

This PR proposes to remove stale Python 3.8/3.7 version checking in the codebase.

### Why are the changes needed?

To remove unnecessary version comparison

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Manually tested the version comparison.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @dongjoon-hyun I checked all. Others seem fine but there are a couple of stale ones.

**Comment by HyukjinKwon** [comment]
Build: https://github.com/HyukjinKwon/spark/actions/runs/7094841200

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you so much, @HyukjinKwon !

**Review by zhengruifeng — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
