### PR TITLE
docs: fix typo

### PR DESCRIPTION
**Pull request by tomsaleeba**
no => no[t]

## What changes were proposed in this pull request?

Fixing a typo.

## How was this patch tested?

Visual check of the docs.

Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
It's okay but mind taking another look and see if there are other typos while we are here? I'm pretty sure there are more.

**Comment by tomsaleeba** [comment]
I don't have time to go hunting for them but if you leave this open for a few days, I'll happily add any others I come across as I learn Spark.

**Review by srowen — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
This is amazing to see many kind of test failures for a typo fix.

**Comment by srowen** [comment]
Because it's obviously a test problem elsewhere, I'll merge this.
@tomsaleeba please see https://spark.apache.org/contributing.html for the future

**Pull request closed without merging**
