### PR TITLE
[SPARK-37528][SQL][CORE] Schedule Tasks By Input Size

### PR DESCRIPTION
**Pull request by ulysses-you**
### What changes were proposed in this pull request?

In general, the larger input data size means longer running time. So ideally, we can let DAGScheduler submit bigger input size task first. It can reduce the whole stage running time.

[design doc](https://docs.google.com/document/d/1vPcuEADUokO4XpqBV1rFH90Zi4rKdsgZtZMYX80c2gw/edit?usp=sharing)

this pr add two cases as initialization implementation:
- datasourcev1 file scan for leaf node
- coalesce partition spec for AQE

### Why are the changes needed?

For example, we have one stage with 4 tasks and the defaultParallelism is 2 and the 4 tasks have different running time [1s, 3s, 2s, 4s].
- in normal, the running time of the stage is: 7s
  - 1, 2
  - 3, 4
- if big task first, the running time of the stage is: 5s
  - 4, 1
  - 3, 2

In worse, if we have a skewed task set [1s, 3s, 3s, 7s, 7s, 20s] with the 2 defaultParallelism:
-  in normal, the running time of the stage is: 31s
   - 1, 3, 7, 20
   - 3, 3, 7
- if big task first, the running time of the stage is: 21s
  - 20, 1
  - 7, 7, 3, 3

### Does this PR introduce _any_ user-facing change?

yes, a new config `spark.scheduler.sortTasksByInputSize.enabled` at core module to decide if we allow to sort tasks.

### How was this patch tested?

Add test in:

- org.apache.spark.scheduler.DAGSchedulerSuite
- org.apache.spark.sql.execution.ScheduleTasksByInputSizeSuiteBase

### CODE REVIEW

**Comment by ulysses-you** [comment]
retest this please

**Comment by zhengruifeng** [comment]
The idea looks reasonable.
If this functionality can only be used in SQL with AQE enabled, what about just making it a `AQEShuffleReadRule` which insert/update `AQEShuffleReadExec`s with reordered `ShufflePartitionSpec`s?

cc @cloud-fan

**Comment by cloud-fan** [comment]
The general idea is to make tasks report more statistics so that the task scheduler can schedule them better. This is really a big feature and I'm a bit hesitant to merge any partial improvements without an overall design.

**Comment by mridulm** [comment]
Btw, this is weak precedence assuming all tasks match the same locality (or no locality) - we should word the config documentation appropriately.

**Comment by ulysses-you** [comment]
> Btw, this is weak precedence assuming all tasks match the same locality (or no locality) - we should word the config documentation appropriately.

it's ture, It doest not affect if the tasks have different locality. It just try the best to make larger task run first without breaking the exists task scheduling.

**Pull request closed without merging**
