### PR TITLE
[SPARK-36645][SQL][FOLLOWUP] Disable min/max push down for Parquet Binary

### PR DESCRIPTION
**Pull request by huaxingao**
### What changes were proposed in this pull request?
Disable min/max push down for Parquet Binary

### Why are the changes needed?
Parquet Binary min/max could be truncated. We may get wrong result if we rely on parquet Binary min/max.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
modify existing tests

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]
looks good from my end.

**Comment by huaxingao** [comment]
also cc @sadikovi @timarmstrong @sunchao @viirya @c21

**Review by wangyum — APPROVED** [review]

**Review by viirya — APPROVED** [review]

**Review by sunchao — APPROVED** [review]

**Review by c21 — APPROVED** [review]
LGTM thanks @huaxingao.

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by huaxingao** [comment]
Thank you so much, everyone!

**Pull request closed without merging**
