### PR TITLE
[SPARK-30267][SQL][FollowUp] Use while loop in Avro Array Deserializer

### PR DESCRIPTION
**Pull request by gengliangwang**
### What changes were proposed in this pull request?

This is a follow-up of https://github.com/apache/spark/pull/26907
It changes the for loop `for (element <- array.asScala)` to while loop

### Why are the changes needed?

As per https://github.com/databricks/scala-style-guide#traversal-and-zipwithindex, we should use while loop for the performance-sensitive code.

### Does this PR introduce any user-facing change?

No

### How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by gengliangwang** [comment]
cc @HyukjinKwon @steven-aerts

**Review by steven-aerts — APPROVED** [review]
I wrote a [small benchmark](https://gist.github.com/steven-aerts/d8173ce0b9c86cb52832486529fd3985) for this.

The `zipWithIndex` is of course  very slow.
This change gains a little bit, but not significantly.
Another nice idiom i think is:

```
for(element:collection.iterator().asScala)
```
Which is also very fast.

**Comment by gengliangwang** [comment]
@steven-aerts Thanks for the benchmark!

**Comment by gengliangwang** [comment]
Merging to master.

**Review by HyukjinKwon — COMMENTED** [review]
LGTM

**Pull request closed without merging**
