### PR TITLE
[WIP][TEST][test-hadoop3.2][test-maven] Verify Hive 2.3.5-SNAPSHOT

### PR DESCRIPTION
**Pull request by wangyum**
## What changes were proposed in this pull request?

This PR to verify Hive 2.3.5-SNAPSHOT.
We should test it on amp-jenkins-worker-03, amp-jenkins-worker-04 or amp-jenkins-worker-06 

## How was this patch tested?

N/A

### CODE REVIEW

**Comment by wangyum** [comment]
retest this please

**Comment by wangyum** [comment]
retest this please

**Comment by wangyum** [comment]
retest this please

**Comment by wangyum** [comment]
retest this please

**Comment by wangyum** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
@wangyum, can I consider this that we're good with Hive 2.3.5?

**Comment by wangyum** [comment]
Yes. I think so. I have tested `sbt` many times on my local machine.

**Comment by wangyum** [comment]
retest this please

**Comment by wangyum** [comment]
retest this please

**Comment by wangyum** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
@wangyum let's send an email to hive dev that we're fine with Hive 2.3.5

**Comment by wangyum** [comment]
@HyukjinKwon OK.

**Pull request closed without merging**
