### PR TITLE
[SPARK-8290]spark class command builder need read SPARK_JAVA_OPTS and SPARK_DRIVER_MEMORY properly

### PR DESCRIPTION
**Pull request by WangTaoTheTonic**
SPARK_JAVA_OPTS was missed in reconstructing the launcher part, we should add it back so process launched by spark-class could read it properly. And so does `SPARK_DRIVER_MEMORY`.

The missing part is [here](https://github.com/apache/spark/blob/1c30afdf94b27e1ad65df0735575306e65d148a1/bin/spark-class#L97).

### CODE REVIEW

**Comment by srowen** [comment]
It seems to be added to specific binaries only. Is this not deprecated?
What is it meant to apply to since it's just hanging in the else branch?

**Comment by WangTaoTheTonic** [comment]
I'm not sure I understood what u mean totally. Before SPARK_JAVA_OPTS will be injected to any class launched by `spark-class`, but was omitted after.

If we run a `beeline`(will go through `spark-class`), it will be very convenient to set extra java options. So does other process launched by `spark-class`.

**Comment by WangTaoTheTonic** [comment]
Jenkins, retest this please.

**Comment by WangTaoTheTonic** [comment]
Looks like something is wrong with RAT. Jenkins, retest this please.

**Comment by srowen** [comment]
Shouldn't this be set for every binary then, rather than in the `else` case?

But I suppose I thought this was deprecated or not supposed to be used anymore. I could be mixing it up with something else, and, clearly it's still passed through for some binaries.

**Comment by WangTaoTheTonic** [comment]
From the old codes we can see daemons like Master or Worker use `SPARK_DAEMON_JAVA_OPTS` and the rest use  `SPARK_JAVA_OPTS`.

Maybe this is not recommended to be used or deprecated(didn't do a deep research), and if so we should remove it clearly in future instead of missing it in some branch now.

**Comment by vanzin** [comment]
LGTM. @WangTaoTheTonic's comment was a little misleading since the previous code would not add it to *all* classes, but to any classes that did not match the pre-existing special cases. From the previous version:

    *)
      OUR_JAVA_OPTS="$SPARK_JAVA_OPTS"
      OUR_JAVA_MEM=${SPARK_DRIVER_MEMORY:-$DEFAULT_MEM}
      ;;

BTW, given that code, the `else` should also probably do:

    memKey = "SPARK_DRIVER_MEMORY";

**Comment by WangTaoTheTonic** [comment]
@vanzin  Thanks for comments. 

I already have added the missing SPARK_DRIVER_MEMORY(oh shame for not finding that) and modified the description.

**Comment by andrewor14** [comment]
LGTM thanks I'm merging into master.

**Pull request closed without merging**
