### PR TITLE
Add comment about defaultMinPartitions

### PR DESCRIPTION
**Pull request by idanz**
Added a comment about using math.min for choosing default partition count

### CODE REVIEW

**Comment by srowen** [comment]
(Can you make the description descriptive? it becomes a commit message.)

**Comment by JoshRosen** [comment]
Jenkins, this is ok to test.

**Comment by JoshRosen** [comment]
This is a spurious test failure: it looks like a test using EasyMock failed during test suite initialization, which leaked a SparkContext and triggered this error.

**Comment by JoshRosen** [comment]
Jenkins, retest this please.

**Comment by JoshRosen** [comment]
Jenkins, retest this please.

**Comment by JoshRosen** [comment]
I'm going to merge this into `master` (1.3.0) and leave a note on the JIRA to say that this has been addressed in the documentation.  Thanks!

**Pull request closed without merging**
