### PR TITLE
[MINOR][DOCS] Mention Hadoop 3 in YARN introduction on cluster-overview.md

### PR DESCRIPTION
**Pull request by yutoacts**
### What changes were proposed in this pull request?

Mentioning Hadoop 3 in YARN introduction on cluster-overview.md.

### Why are the changes needed?

It only mentioned Hadoop 2 but Hadoop3 is currently the latest and I believe the most used version.

### Does this PR introduce _any_ user-facing change?

Yes, docs changed.

### How was this patch tested?

`SKIP_API=1 bundle exec jekyll build`
minor_hadoop

### CODE REVIEW

**Comment by sarutak** [comment]
Are there any similar places where we should modify in bulk?

**Comment by yutoacts** [comment]
Thanks for the review. I believe other similar places are already all fixed.

**Comment by sarutak** [comment]
ok to test.

**Comment by sarutak** [comment]
Merged to `master`. Thanks @yutoacts !

**Pull request closed without merging**
