### PR TITLE
[SPARK-45755][SQL] Improve `Dataset.isEmpty()` by applying global limit `1`

### PR DESCRIPTION
**Pull request by wangyum**
### What changes were proposed in this pull request?

This PR makes `Dataset.isEmpty()` to execute global limit 1 first. `LimitPushDown` may push down global limit 1 to lower nodes to improve query performance.

Note that we use global limit 1 here, because the local limit cannot be pushed down the group only case: https://github.com/apache/spark/blob/89ca8b6065e9f690a492c778262080741d50d94d/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/optimizer/Optimizer.scala#L766-L770

### Why are the changes needed?

Improve query performance.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Manual testing:
```scala
spark.range(300000000).selectExpr("id", "array(id, id % 10, id % 100) as eo").write.saveAsTable("t1")
spark.range(100000000).selectExpr("id", "array(id, id % 10, id % 1000) as eo").write.saveAsTable("t2")
println(spark.sql("SELECT * FROM t1 LATERAL VIEW explode_outer(eo) AS e UNION SELECT * FROM t2 LATERAL VIEW explode_outer(eo) AS e").isEmpty)
```

Before this PR | After this PR
-- | --
image | image

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Review by beliefer — APPROVED** [review]
LGTM if tests passed.

**Review by yaooqinn — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @wangyum and all.

**Comment by dongjoon-hyun** [comment]
I revised the PR title a little, @wangyum . You can change it back if you want.

**Comment by wangyum** [comment]
Thank you @dongjoon-hyun The new PR title looks better than the previous one.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by beliefer** [comment]
Merged to master. Thank you @wangyum 
Thank you @dongjoon-hyun @HyukjinKwon @yaooqinn too.

**Pull request closed without merging**
