### PR TITLE
[SPARK-39156][SQL] Clean up the usage of `ParquetLogRedirector` in `ParquetFileFormat`.

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
SPARK-17993 introduce `ParquetLogRedirector` for Parquet version < 1.9, [PARQUET-305](https://issues.apache.org/jira/browse/PARQUET-305) change to use slf4j instead of jul in Parquet 1.9,  Spark uses Parquet 1.12.2 now  and [no longer relies on Parquet version 1.6](https://github.com/apache/spark/pull/30005) now , the `ParquetLogRedirector` is no longer needed, so this pr clean up the usage of `ParquetLogRedirector` in `ParquetFileFormat`.

### Why are the changes needed?
Clean up the usage of `ParquetLogRedirector` in `ParquetFileFormat`.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?

- Pass GA
- Manual test: 

1. Build Spark client manually before and after this pr
2. Change parquet log4j level to debug:
```
logger.parquet1.name = org.apache.parquet
logger.parquet1.level = debug
logger.parquet2.name = parquet
logger.parquet2.level = debug
```
3. Try to read Parquet file write with 1.6 , for example `sql/core/src/test/resources/test-data/dec-in-i32.parquet`.

```
java -jar parquet-tools-1.10.1.jar meta /${basedir}/dec-in-i32.parquet
file:        file:/${basedir}/dec-in-i32.parquet
creator:     parquet-mr version 1.6.0 
extra:       org.apache.spark.sql.parquet.row.metadata = {"type":"struct","fields":[{"name":"i32_dec","type":"decimal(5,2)","nullable":true,"metadata":{}}]} 

file schema: spark_schema 
--------------------------------------------------------------------------------
i32_dec:     OPTIONAL INT32 O:DECIMAL R:0 D:1

row group 1: RC:16 TS:102 OFFSET:4 
--------------------------------------------------------------------------------
i32_dec:      INT32 GZIP DO:0 FPO:4 SZ:131/102/0.78 VC:16 ENC:RLE,PLAIN_DICTIONARY,BIT_PACKED ST:[no stats for this column]
```

```
spark.read.parquet("file://${basedir}/ptable/dec-in-i32.parquet").show()
```

The log contents before and after this pr are consistent, and there is no error log mentioned in SPARK-17993

### CODE REVIEW

**Review by sunchao — COMMENTED** [review]
Looks OK. Could you cross link the fix (JIRA) from Parquet side?

**Comment by LuciferYang** [comment]
> Looks OK. Could you cross link the fix (JIRA) from Parquet side?

Should be [PARQUET-305](https://issues.apache.org/jira/browse/PARQUET-305) in Parquet 1.9

**Review by sunchao — APPROVED** [review]
LGTM

**Comment by LuciferYang** [comment]
hmm... @sunchao any other need changes?

**Review by huaxingao — APPROVED** [review]

**Comment by huaxingao** [comment]
Thanks! Merged to master.

**Comment by LuciferYang** [comment]
thanks @huaxingao @sunchao

**Pull request closed without merging**
