### PR TITLE
[SPARK-32428] [EXAMPLES] Make BinaryClassificationMetricsExample cons…

### PR DESCRIPTION
**Pull request by titsuki**
…istently print the metrics on driver's stdout

### What changes were proposed in this pull request?

Call collect on RDD before calling foreach so that it sends the result to the driver node and print it on this node's stdout.

### Why are the changes needed?

Some RDDs in this example (e.g., precision, recall) call println without calling collect.
If the job is under local mode, it sends the data to the driver node and prints the metrics on the driver's stdout.
However if the job is under cluster mode, the job prints the metrics on the executor's stdout.
It seems inconsistent compared to the other metrics nothing to do with RDD (e.g., auPRC, auROC) since these metrics always output the result on the driver's stdout.
All of the metrics should output its result on the driver's stdout.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

This is example code. It doesn't have any tests.

### CODE REVIEW

**Comment by huaxingao** [comment]
The change looks reasonable to me. I checked the examples, most of the examples have RDD.collect().foreach, but a few of the examples have RDD.foreach. For example, in ```ElementwiseProductExample```
```
    println("transformedData: ")
    transformedData.foreach(x => println(x))

    println("transformedData2: ")
    transformedData2.foreach(x => println(x))
```
I think we probably also want to change these to make all the examples to output the result on the driver's stdout.

**Comment by huaxingao** [comment]
cc @srowen

**Review by srowen — COMMENTED** [review]
Yep let's fix all such occurrences if possible. Thanks!

**Comment by titsuki** [comment]
@huaxingao @srowen 
Thanks for your reviews! I've also fixed the other examples.

**Comment by HyukjinKwon** [comment]
+1

**Comment by srowen** [comment]
Jenkins test this please

**Review by huaxingao — APPROVED** [review]

**Comment by srowen** [comment]
Merged to master/3.0/2.4

**Pull request closed without merging**
