### PR TITLE
[SPARK-25629][TEST] Reduce ParquetFilterSuite: filter pushdown test time costs in Jenkins

### PR DESCRIPTION
**Pull request by wangyum**
## What changes were proposed in this pull request?

Only test these 4 cases is enough:
https://github.com/apache/spark/blob/be2238fb502b0f49a8a1baa6da9bc3e99540b40e/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetWriteSupport.scala#L269-L279

## How was this patch tested?

Manual tests on my local machine.
before:
```
- filter pushdown - decimal (13 seconds, 683 milliseconds)
```
after:
```
- filter pushdown - decimal (9 seconds, 713 milliseconds)
```

### CODE REVIEW

**Comment by wangyum** [comment]
retest this please

**Comment by wangyum** [comment]
retest this please

**Review by HyukjinKwon — APPROVED** [review]

**Comment by gatorsmile** [comment]
The time reduction is not obvious. Let us keep this unchanged?

**Comment by HyukjinKwon** [comment]
Yea, it is not obvious and only few seconds - might not be so worth. But looks improvement because it fixes the test cases to test what the previous PR targeted. Wouldn't it be better just to go ahead rather then close this since the PR is already open?

**Comment by HyukjinKwon** [comment]
@wangyum, can you reopen this? I don't think we should just close this. Fixing tests to actually test what the previous change targeted sounds definitely an improvement although it's minor. I wouldn't encourage to fix those but at least I would go ahead for this one since the fix is already proposed.

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
