### PR TITLE
[Spark-7781][MLLIB] gradient boosted trees.train regressor missing max bins

### PR DESCRIPTION
**Pull request by holdenk**

### CODE REVIEW

**Comment by holdenk** [comment]
Seems like a spurious git failure, @AmplabJenkins retest this please.

**Comment by holdenk** [comment]
cc @jkbradley

**Comment by jkbradley** [comment]
LGTM  but first I'll retest this please since it's been a little while.

**Comment by jkbradley** [comment]
silly Jenkins  test this please

**Comment by jkbradley** [comment]
Merging with master and branch-1.4
I'm merging for 1.4.1 since this really does prevent usage with a lot of datasets.

@holdenk Thanks!

**Pull request closed without merging**
