### PR TITLE
[SPARK-5363] fix bug: remove() inside iterator is not safe

### PR DESCRIPTION
**Pull request by davies**
During iterating, it's not safe to remove item.

### CODE REVIEW

**Comment by davies** [comment]
cc @JoshRosen

**Comment by JoshRosen** [comment]
LGTM pending Jenkins.

**Comment by JoshRosen** [comment]
Context for other reviewers: removing elements from a mutable HashSet while iterating over it can cause the iteration to skip over entries that weren't removed.  In this case, this would cause PythonRDD to write fewer than `cnt` broadcasts, which caused the Python worker to hang while expecting to read `cnt` total broadcasts.

**Comment by JoshRosen** [comment]
I'm going to merge this into `master` (1.4.0), `branch-1.3` (1.3.0), and `branch-1.2` (1.2.2).  Thanks!

**Pull request closed without merging**
