### PR TITLE
[SPARK-14337][SQL] Push casts beneath CASE WHEN and IF expressions

### PR DESCRIPTION
**Pull request by JoshRosen**
If we have a cast on top of a CASE WHEN or IF expression, then we should push the cast to each conditional branch's result expression.

### CODE REVIEW

**Comment by JoshRosen** [comment]
There's one corner-case related to null-handling that I'd like to clarify (and probably add tests for):

- I think that `CASE WHEN` can return `null` if it's defined without an `ELSE` case. I think it's also the cast that casting preserves nullness, so this should be fine but deserves a code comment and test just to be sure.

**Comment by JoshRosen** [comment]
Similarly, if `IF`'s condition evaluates to `null` then it looks like the result of `IF` is the `falseExpression` rather than `null`, so we don't have to worry about the pushdown breaking things. I'll also add tests for this.

**Comment by rxin** [comment]
I think we do have those test cases in ConditionalExpressionSuite

**Comment by rxin** [comment]
BTW - why should we do this? The reason I'm asking is that this could lead to longer generated code. It is not clear to me this is always better.

**Comment by JoshRosen** [comment]
My original goal was for this to be able to stack with other optimizations to simplify expressions like

```
Cast(
      CaseWhen(
        Seq(Not(EqualTo(UnresolvedAttribute("age"), Literal(4))) -> Literal(0)),
        Literal(1)
      ),
      BooleanType)
```

since those types of overly-complicated expressions were cropping up in my closure -> expression extractor. However, given the concerns over code size plus weird Java nullability semantics I'm thinking that I may want to write some customized simplification rules which only run on the extracted expressions rather than all expressions. Therefore, I'll close this for now.

**Pull request closed without merging**
