### PR TITLE
[SPARK-20097][ML] Fix visibility discrepancy with numInstances and degreesOfFreedom in LR and GLR

### PR DESCRIPTION
**Pull request by BenFradet**
## What changes were proposed in this pull request?

- made `numInstances` public in GLR
- made `degreesOfFreedom` public in LR

## How was this patch tested?

reran the concerned test suites

### CODE REVIEW

**Comment by BenFradet** [comment]
@jkbradley this is what we discussed in #12823

**Comment by MLnick** [comment]
LGTM

We could fix up the annotations for LinearRegression - do you want to open a new JIRA/PR for that?

**Comment by MLnick** [comment]
Merged to master. Thanks!

**Comment by BenFradet** [comment]
Yup, I'm on it, thanks @MLnick !

**Pull request closed without merging**
