### PR TITLE
[SPARK-24432] Support dynamic allocation without external shuffle service

### PR DESCRIPTION
**Pull request by lwwmanning**
## What changes were proposed in this pull request?

This PR adds a limited version of dynamic allocation that does not require the external shuffle service, and thus works on kubernetes (but does not support preemption). 

The basic approach is to track which executors are holding shuffle files, and of those, which have shuffle files depended on by active stages. If an executor contains shuffle files depended on by an active stage, then we treat it as "active" (i.e., prevent the ExecutorAllocationManager from marking it as "idle"). If an executor contains only shuffle files that are not dependencies of active stages, then we treat those shuffle files similarly to cached data (i.e., configurable idle timeout that defaults to "infinity"). 

We also introduce the concept of "shuffle biased task scheduling", a heuristic attempt to schedule tasks for maximal efficacy of dynamic allocation. We do this by attempting to minimize the number of executors that contain (active) shuffle files, by packing as many tasks as possible onto "active" executors first, followed by scheduling them on executors with only inactive shuffle files, and finally all remaining executors.

This is a port of a series of PRs on Palantir's spark fork: https://github.com/palantir/spark/pull/427 https://github.com/palantir/spark/pull/445 https://github.com/palantir/spark/pull/446 https://github.com/palantir/spark/pull/447

Partially addresses https://issues.apache.org/jira/browse/SPARK-24432

cc: @rynorris @mccheah @robert3005

## How was this patch tested?

We added additional tests explicitly as part of the PR, and did additional manual testing on small YARN and k8s clusters (partially documented on https://github.com/palantir/spark/pull/446). Then we successfully rolled this out for a small subset of workloads in production at Palantir, running entirely on kubernetes.

Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Comment by mcheah** [comment]
@mccheah

**Comment by lwwmanning** [comment]
whoops, thanks @mcheah, sorry for the mis-tag!

**Comment by mccheah** [comment]
ok to test

**Comment by mccheah** [comment]
cc @vanzin @rxin. Would a feature like this require an SPIP?

**Comment by markhamstra** [comment]
@mccheah it does feel to me like more discussion is required than is appropriate for a PR. Whether that means a separate JIRA ticket or a SPIP, I'm undecided.

**Comment by vanzin** [comment]
I don't think this needs an SPIP (it's all internal changes), but agree that it should be its own separate bug in JIRA.

It would also be better to separate the k8s-side changes into a different bug/PR, since those fix a different problem than the other changes.

SPARK-24432 is an umbrella bug, so you could just create sub-tasks for it.

**Comment by vanzin** [comment]
Ping?

I'm seeing two or 3 separate PRs here; the ExecutorAllocationManager changes + tracking of active stages being the most obvious. "Shuffle biased scheduling" builds on top of the active stage tracking, but feels separate from the dynamic allocation changes. And the k8s changes definitely should be a separate PR.

Also, instead of adding YARN tests, I'd do that in core. `YarnClusterSuite` does not run when you don't change YARN code, so it often doesn't run when changes are made to the core code in this area. Using a `local-cluster[...]` for this works fine (I've been using it in some code I've been playing with), and even runs a bit faster than tests in the YARN suite.

**Comment by vanzin** [comment]
If there's not going to be any activity here I'll just close this PR and let someone else handle this if they want...

**Comment by lwwmanning** [comment]
Apologize, was on vacation last week. 

I'll file separate sub-issues in JIRA for both the k8s changes and dynamic-allocation-without-ESS. 

Will close this PR and split out as three separate PRs, in order: (1) k8s changes, (2) ExecutorAllocationManager changes / active stage tracking (with additional tests in core), (3) shuffle biased task scheduling.

**Comment by ScrapCodes** [comment]
@lwwmanning Hi, any progress on this work? Do you want some help?

**Comment by ScrapCodes** [comment]
@lwwmanning and @vanzin, There are no updates here or on the issue. IMO this approach is worth considering, it may have its downside, but having it is an option in spark on kube, seems reasonable to me. Shall I take this work forward from here?

**Comment by vanzin** [comment]
I agree that this could be useful, and you're free to open a PR if you want. But I actually do have an implementation of this that is based on some code that is currently under review, and I plan to submit it when the PR it depends on is merged.

**Comment by ScrapCodes** [comment]
Hi @vanzin, Do you have an update? Can you please link the PR you were mentioning here?

**Comment by vanzin** [comment]
SPARK-27963

**Pull request closed without merging**
