### PR TITLE
[SPARK-46637][DOCS] Enhancing the Visual Appeal of Spark doc website

### PR DESCRIPTION
**Pull request by gengliangwang**
### What changes were proposed in this pull request?

Enhance the Visual Appeal of Spark doc website after https://github.com/apache/spark/pull/40269:
#### 1. There is a weird indent on the top right side of the first paragraph of the Spark 3.5.0 doc overview page
Before this PR
image

After this PR:
image

#### 2. All the titles are too big and therefore less readable. In the website https://spark.apache.org/downloads.html, titles are h2 while in doc site https://spark.apache.org/docs/latest/ titles are h1. So we should make the font size of titles smaller.
Before this PR:
image
After this PR:
image

#### 3. The banner image can't be displayed correct. Even when it shows up, it will be hover by the text. To make it simple, let's not show the banner image as we did in https://spark.apache.org/docs/3.4.2/
image
image

### Why are the changes needed?

Improve the Visual Appeal of Spark doc website

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Manually build doc and verify on local setup.

### Was this patch authored or co-authored using generative AI tooling?

No

### CODE REVIEW

**Comment by gengliangwang** [comment]
cc @grundprinzip @allanf-db as well

**Review by srowen — APPROVED** [review]

**Comment by grundprinzip** [comment]
Actually this lost the hero banner somewhere. When I migrated the CSS for the docs I added the 
image
image to the CSS seems that this got lost somehow.

**Comment by gengliangwang** [comment]
@grundprinzip yes I am aware of that. See the PR description
> 3. The banner image can't be displayed correct. Even when it shows up, it will be hover by the text. To make it simple, let's not show the banner image as we did in https://spark.apache.org/docs/3.4.2/

for details. Having the image in https://spark.apache.org/ should be enough.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by gengliangwang** [comment]
@HyukjinKwon Thanks for merging the PR. I just pushed it to branch-3.5 as well: https://github.com/apache/spark/commit/d3e3084808453769ba0cd4278ee8650e40c185ea

**Pull request closed without merging**
