### PR TITLE
[SPARK-4131] Merge HiveTmpFile.scala to SaveAsHiveFile.scala

### PR DESCRIPTION
**Pull request by janewangfb**
## What changes were proposed in this pull request?

The code is already merged to master:
https://github.com/apache/spark/pull/18975

This is a following up PR to merge HiveTmpFile.scala to SaveAsHiveFile.

## How was this patch tested?

Build successfully

### CODE REVIEW

**Comment by gatorsmile** [comment]
ok to test

**Comment by gatorsmile** [comment]
retest this please

**Comment by gatorsmile** [comment]
LGTM

**Comment by gatorsmile** [comment]
Thanks! Merged to master.

**Comment by aoxiangcao** [comment]
i'm sorry if it right to ask here .i have some question when use 'insert overwrite directory /user/appUser/test'. first, i start the thrift by 'hdfs', and login into beeline with user 'appUser'. then, i run sql 'insert overwrite directory ....' , the job cannot move data from staging folder to destination folder. because the result file is own by 'hdfs',the folder '/user/appUser/test' is own by appUser. so permission denied. is something wrong?

**Pull request closed without merging**
