### PR TITLE
[SPARK-9855][SparkR] Add expression functions into SparkR whose params are simple

### PR DESCRIPTION
**Pull request by yu-iskw**
I added lots of expression functions for SparkR. This PR includes only functions whose params  are only `(Column)` or `(Column, Column)`.  And I think we need to improve how to test those functions. However, it would be better to work on another issue.
## Diff Summary
- Add lots of functions in `functions.R` and their generic in `generic.R`
- Add aliases for `ceiling` and `sign`
- Move expression functions from `column.R` to `functions.R`
- Modify `@rdname` from `column` to `functions`

I haven't supported `not` function, because the name has a collesion with `testthat` package. I didn't think of the way  to define it. 
## New Supported Functions

```
approxCountDistinct
ascii
base64
bin
bitwiseNOT
ceil (alias: ceiling)
crc32
dayofmonth
dayofyear
explode
factorial
hex
hour
initcap
isNaN
last_day
length
log2
ltrim
md5
minute
month
negate
quarter
reverse
round
rtrim
second
sha1
signum (alias: sign)
size
soundex
to_date
trim
unbase64
unhex
weekofyear
year

datediff
levenshtein
months_between
nanvl
pmod
```
## JIRA

[[SPARK-9855] Add expression functions into SparkR whose params are simple - ASF JIRA](https://issues.apache.org/jira/browse/SPARK-9855)

### CODE REVIEW

**Comment by yu-iskw** [comment]
@shivaram could you review this PR when you have time?

**Comment by shivaram** [comment]
Thanks @yu-iskw -- This looks pretty good. One question: Do we have any convention on what goes in functions.R and what goes in column.R ? are we following the same convention from Scala / Python ?

Also can you open a new JIRA for tracking the documentation change we need to do ?

**Comment by yu-iskw** [comment]
Yes, I think it would be nice for functionsR to follow the same convention from Scala / Python. 
Alright, I'll create a new JIRA for that.

**Comment by shivaram** [comment]
Sounds good. LGTM. Merging this

**Comment by yu-iskw** [comment]
Thank you for merging it!

It seems that roxygen supports `since` tag used to specify since when (version or time) an entity. Should we support it like Scala / Python in a future? 
Although  `roxygen2` package hasn't  supported `@since` tag yet, we could also use `\since` raw command.
http://www.stack.nl/~dimitri/doxygen/manual/commands.html#cmdsince

**Comment by shivaram** [comment]
Sure - I wasn't too worried about it as SparkR is still an alpha component, but adding `\since` sounds like a good idea. We could also request this feature on roxygen2.

**Comment by yu-iskw** [comment]
I got it. Shall we support `since` tag at 1.6.0. I have requested this feature on roxygen.
https://github.com/klutometis/roxygen/issues/369

**Comment by yu-iskw** [comment]
Ah, I'm sorry. Rd doesn't support a tag to specify since when a function is available. So, it is quite hard to annotate their versions. If I must choose, we could use Rd `\note` function.

**Pull request closed without merging**
