### PR TITLE
[SPARK-4845][Core] Adding a parallelismRatio to control the partitions num of shuffledRDD

### PR DESCRIPTION
**Pull request by scwf**
Adding parallelismRatio to control the partitions num of shuffledRDD, the rule is:

```
 Math.max(1, parallelismRatio * number of partitions of the largest upstream RDD)
```

The ratio is 1.0 by default to make it compatible with the old version. When we have a good experience on it, we can change this.

### CODE REVIEW

**Comment by andrewor14** [comment]
Hi @scwf can you elaborate on the motivation for this?

**Comment by srowen** [comment]
I am also not clear this is a good thing. As a default, it doesn't change anything. There is probably not a globally correct ratio, even if it's not 1, but this implies there is. Is there evidence that a default besides 1.0 is better in most cases? The docs don't even suggest what the tradeoff is here.

Won't this potentially cause more shuffles when the ratio is not 1? I think this is something that must be set on a case-by-case basis, and that can already be done, even as a function of the parent RDD partitions, by the caller.

Can we elaborate on this or close it?

**Comment by sryza** [comment]
In general, a fixed number of partitions is very difficult to work with when configuring a shuffle.  Suppose I have a job where I know a `flatMap` is going to blow up the size of my data by two.  If I want to minimize reduce-side spilling in a shuffle that comes after the `flatMap`, I want the parallelism of the shuffle to be double that of the input stage.  Because the size of my input data could change between different runs of my job, a ratio is a much more natural way to express my needs than a constant.

It's unclear to me whether a global default is useful at all, but a configurable parallelism ratio per shuffle operation definitely is.  (Systems like Crunch take this approach).

**Comment by srowen** [comment]
You can implement this by expressing parallelism as a function of the parent RDD right? yeah you have to write the expression but does an alternative multiplier arg do much better? yeah mostly I'm questioning a global setting.

**Comment by sryza** [comment]
@srowen good point.  I think a ratio argument is prettier than an expression, but arguably not enough to warrant clogging up the API.

**Comment by lianhuiwang** [comment]
i do not think that a global default ratio is right. because in a job the size of each stage is different and they are not Increasing or decreasing.  if we define a partition's ratio for per shuffle operation, there are no different between setting a ration and setting partition number for per shuffle operation.

**Comment by srowen** [comment]
I suggest we close this as I see arguments against, and no replies to those and/or the motivation for this change.

**Comment by andrewor14** [comment]
I agree. @scwf would you mind closing this issue?

**Comment by scwf** [comment]
sorry for delay, my initial idea here is 
1 we can set spark.default.parallsim to control the partitions num for shuffle but this config option do not sensitive to data size of rdd, that is for one job with 1T input data the partitions num is x but for the same job with 1K input data the partitions num is also x. 

2 if we not set spark.default.parallsim, spark rdd use parent rdd's partitions num as its partitions num, but in this way i found that there maybe some mini-tasks in some case due to the big partitions num of parent rdd, so i think maybe we can give a ratio to control the shuffle partition num 

ok, i am closing this

**Pull request closed without merging**
