### PR TITLE
[SPARK-40613][BUILD] Upgrade sbt-protoc to 1.0.6

### PR DESCRIPTION
**Pull request by wangyum**
### What changes were proposed in this pull request?

This PR upgrade sbt-protoc to 1.0.6.

### Why are the changes needed?

sbt-protoc 1.0.1 dose not exist.
image

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Unit test.

### CODE REVIEW

**Review by srowen — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by srowen** [comment]
Merged to master

**Comment by amaliujia** [comment]
cc @HyukjinKwon for who has looked on the SBT issue for spark connect.

**Review by HyukjinKwon — COMMENTED** [review]
LGTM2

**Comment by LuciferYang** [comment]
late  LGTM

**Pull request closed without merging**
