### PR TITLE
[SPARK-45173][UI] Remove some unnecessary sourceMapping files in UI

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

This PR deletes *.[css|jss].map files in URL for sourceMapping

### Why are the changes needed?

The source map files are for debugging purposes, enabling browsers to map JS/CSS created by a preprocessor back to the original source file. For production, we'd better not ship them

### Does this PR introduce _any_ user-facing change?

no
### How was this patch tested?

build and test locally

### Was this patch authored or co-authored using generative AI tooling?

no

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Ur, this is used, isn't it?

https://github.com/apache/spark/blob/91ccc0f8e9fd59ae13ac11640c8440317121d8b7/core/src/main/scala/org/apache/spark/ui/UIUtils.scala#L229

**Comment by dongjoon-hyun** [comment]
If this is really unused, I believe 
- We need to remove `UIUtils.commonHeaderNodes` first.
- Also need to remove from RAT file 
https://github.com/apache/spark/blob/91ccc0f8e9fd59ae13ac11640c8440317121d8b7/dev/.rat-excludes#L27

**Comment by yaooqinn** [comment]
Hi @dongjoon-hyun the sheet file `bootstrap.min.css` is not removed, but `bootstrap.min.css.map`. :)

**Comment by dongjoon-hyun** [comment]
Ah, I missed that it's one line change. Got it. Thanks.

Screenshot 2023-09-14 at 9 39 40 PM

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Review by dongjoon-hyun — COMMENTED** [review]
Just a question for my understanding. May I ask why these map files are unnecessary? I initially thought this PR claims they are broken, but after looking at this again, these look valid to me.
> unnecessary files cleanup

Is it because we don't have `bootstrap.css` in Apache Spark? When we provide only `bootstrap.min.css` only, `bootstrap.min.css.map` is meaningless?

**Comment by dongjoon-hyun** [comment]
If possible, please elaborate a little more in the PR description, @yaooqinn . :)

**Comment by yaooqinn** [comment]
Yeah, the source map files are for debugging purposes which enables browsers to map JS/CSS created by a preprocessor back to the original source file. For production, we'd better not ship them.(Added to PR desc too)

**Comment by dongjoon-hyun** [comment]
Thank you for the confirmation and updating the PR description.

**Comment by dongjoon-hyun** [comment]
Merged to master for Apache Spark 4.0.0.

**Pull request closed without merging**
