### PR TITLE
[SPARK-5699] [SQL] [Tests] Runs hive-thriftserver tests whenever SQL code is modified

### PR DESCRIPTION
**Pull request by liancheng**
[Review on Reviewable](https://reviewable.io/reviews/apache/spark/4486)

### CODE REVIEW

**Comment by liancheng** [comment]
Merging to master and branch-1.3.

**Comment by marmbrus** [comment]
Is there a JIRA so we don't forget to undo this before the release?

**Comment by liancheng** [comment]
@marmbrus I guess you meant to comment in PR #4484. And yes, [SPARK-5700] [1] was opened to track that.

[1]: https://issues.apache.org/jira/browse/SPARK-5700

**Comment by liancheng** [comment]
Update, SPARK-5700 has been fixed by #4499.

**Pull request closed without merging**
