### PR TITLE
[SPARK-42456][DOCS][PYTHON] Consolidating the PySpark version upgrade note pages into a single page to make it easier to read

### PR DESCRIPTION
**Pull request by aldogrut**
### What changes were proposed in this pull request?
Creating a new PySpark migration guide sub page and consolidating the existing 9 separate pages into this one new page. This makes it easier to take a look across multiple version upgrades by simply scrolling on the page instead of having to navigate back and forth. Note that this is similar to the Spark Core Migration Guide page here:
https://spark.apache.org/docs/latest/core-migration-guide.html

Also updating the existing main Migration Guide page to point to this new sub page and making some minor language updates to help readers.

### Why are the changes needed?
To improve usability of the PySpark doc site.

### Does this PR introduce _any_ user-facing change?
Yes, the user facing PySpark documentation is updated.

### How was this patch tested?
Built and tested the PySpark documentation web site locally.

### CODE REVIEW

**Comment by allanf-db** [comment]
CC @HyukjinKwon @zhengruifeng

**Comment by allanf-db** [comment]
Attaching screenshots of the updated Migration Guides page and the new version upgrade sub-page.

pyspark_migration_guides_doc_page

pyspark_migration_guide_upgrade_doc_page

**Review by zhengruifeng — APPROVED** [review]
LGTM, The failed test should be unrelated

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master and branch-3.4.

**Pull request closed without merging**
