### PR TITLE
[SPARK-33498][SQL][TESTS][3.1][FOLLOWUP] Remove SQLConf.withExistingConf in CastSuite

### PR DESCRIPTION
**Pull request by maropu**
### What changes were proposed in this pull request?

This PR intends to remove unnecessary `SQLConf.withExistingConf` in `CastSuite`; since we've remove `ParVector ` in #31775, we no longer need to copy SQL configs into each thread env.

This PR is a backport of #31785.

### Why are the changes needed?

Clean up the code.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Run the existing tests.

### CODE REVIEW

**Comment by maropu** [comment]
cc: @dongjoon-hyun

**Review by HyukjinKwon — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM (Pending CIs). Thank you.

**Comment by dongjoon-hyun** [comment]
This is a test-only PR and I verified the test suite manually.
Merged to branch-3.1.

**Comment by maropu** [comment]
Thanks, @dongjoon-hyun @HyukjinKwon ~

**Pull request closed without merging**
