### PR TITLE
MAINTENANCE. Cleaning up stale PRs.

### PR DESCRIPTION
**Pull request by vanzin**
Closing the following PRs due to requests or unresponsive users.

Closes #13923
Closes #14462
Closes #13123
Closes #14423 (requested by srowen)
Closes #14424 (requested by srowen)
Closes #14101 (requested by jkbradley)
Closes #10676 (requested by srowen)
Closes #10943 (requested by yhuai)
Closes #9936
Closes #10701

### CODE REVIEW

**Comment by vanzin** [comment]
Let me know if there are any concerns.

**Comment by vanzin** [comment]
Also going to add #10474.

**Comment by vanzin** [comment]
Adding #13248

**Comment by vanzin** [comment]
Adding #14347

**Comment by vanzin** [comment]
Adding #10356

**Comment by vanzin** [comment]
Adding #9866

**Comment by srowen** [comment]
Does just mentioning the numbers in comments cause them to close when this merges? I wasn't sure whether the bot or Github looks for "closes ...".

Here are some more on my list:

Closes #14310 
Closes #14347
Closes #14390 
Closes #14343 
Closes #14402 
Closes #14437 
Closes #14232
Closes #12000 
Closes #13248 
Closes #10270

**Comment by vanzin** [comment]
No, just mentioning in comments doesn't work. I'm adding the "Closes #foo" text to the commit message I'll push, and at that time github will close them.

I'll look at adding the ones on your list.

**Comment by vanzin** [comment]
I'll let 10270 since the submitter is active (I'll let him close the PR if he can't fix it). I'll take a look at 14232 since I've played with that code (it's just a comment anyway).

**Comment by vanzin** [comment]
Alright, commit is pushed, lots of PRs are in the process of being closed.

**Pull request closed without merging**
