### PR TITLE
[SPARK-36712][Build] Make scala-parallel-collections in 2.13 POM a direct dependency (not in maven profile)

### PR DESCRIPTION
**Pull request by lrytz**
As [reported on `dev@spark.apache.org`](https://lists.apache.org/thread.html/r84cff66217de438f1389899e6d6891b573780159cd45463acf3657aa%40%3Cdev.spark.apache.org%3E), the published POMs when building with Scala 2.13 have the `scala-parallel-collections` dependency only in the `scala-2.13` profile of the pom.

### What changes were proposed in this pull request?

This PR suggests to work around this by un-commenting the `scala-parallel-collections` dependency when switching to 2.13 using the the `change-scala-version.sh` script.

I included an upgrade to scala-parallel-collections version 1.0.3, the changes compared to 0.2.0 are minor.
  - removed OSGi metadata
  - renamed some internal inner classes
  - added `Automatic-Module-Name`

### Why are the changes needed?

According to the posts, this solves issues for developers that write unit tests for their applications.

Stephen Coy suggested to use the https://www.mojohaus.org/flatten-maven-plugin. While this sounds like a more principled solution, it is possibly too risky to do at this specific point in time?

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Locally

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Thanks for contribution, @lrytz. Would you mind filing a JIRA and linking it to the PR title? See also https://spark.apache.org/contributing.html

**Comment by lrytz** [comment]
@HyukjinKwon done

**Comment by srowen** [comment]
Jenkins test this please

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
~Hi, @lrytz . Could you make another PR for the dependency upgrade to `1.0.3`?~

**Comment by srowen** [comment]
FWIW I think it's fine to do in one go - we're fixing scala-parallel-collections here anyway and the change is small

**Comment by dongjoon-hyun** [comment]
Got it. If you think so, I'm taking my words back.

**Comment by lrytz** [comment]
I'm happy to do it which ever way is preferred.

**Comment by srowen** [comment]
Merged to master / 3.2

**Review by dongjoon-hyun — COMMENTED** [review]
Unfortunately, it turns out that this causes a regression to the existing legacy CI pipeline, @lrytz and @srowen . I'll try to make a follow-up.

**Comment by srowen** [comment]
Arg really what happened? OK yeah hopefully can be touched up

**Comment by dongjoon-hyun** [comment]
Here is the patch~
- https://github.com/apache/spark/pull/33996

**Comment by lrytz** [comment]
Thank you @dongjoon-hyun

**Pull request closed without merging**
