### PR TITLE
[SPARK-8162][BUILD] Run spark-shell cause NullPointerException

### PR DESCRIPTION
**Pull request by Sephiroth-Lin**
see jira https://issues.apache.org/jira/browse/SPARK-8162

### CODE REVIEW

**Comment by srowen** [comment]
I don't think this can be it, since annotations are always optional at runtime.
This is something else. I can't reproduce it though. Can you please add detail about how you built and ran this?

**Comment by Sephiroth-Lin** [comment]
@srowen I build the Spark with comman **`mvn -Pyarn -Phadoop-2.4 -Dhadoop.version=2.7.0 -Phive -Phive-thriftserver -Psparkr -DskipTests package`** and run spark-shell with comman **`./bin/spark-shell --master yarn-client`**

* Maven: 3.x
* JDK: 1.8.0_40
* OS: SUSE 11 SP3

**Comment by srowen** [comment]
Yeah I can reproduce that actually. Phoning friend @vanzin for thoughts. Should this be un-shaded and does it makes sense that this causes the class to fail loading?

**Comment by srowen** [comment]
Jenkins, retest this please

**Comment by vanzin** [comment]
This is weird in two counts:
- why isn't the annotation being shaded?
- why is the runtime code trying to load that annotation?

Let me take a quick look. Not shading that annotation probably is not the end of the world, but I die a little bit every time an exception has to be added to Guava shading.

**Comment by shivaram** [comment]
I ran into this the other day as well. Any ideas what caused this ? The spark-shell on the default build used to work fine till last week or so on my machine

**Comment by andrewor14** [comment]
@srowen @vanzin What is the issue caused by? Is there a quick way to resolve this / a commit to revert to fix this? This is blocking development for a lot of people.

**Comment by JoshRosen** [comment]
If the problem only stems from the VisibleForTesting annotation, then let's just replace that annotation with a comment rather than wholesale reverting the commit that added it.

**Comment by shivaram** [comment]
@andrewor14 Looks like https://github.com/apache/spark/pull/6546/files added the annotation to JobProgressListener.

**Comment by andrewor14** [comment]
I see. It seems that the `VisibleForTesting` annotation is not actually needed in that commit. I believe it's added for good practice and so I think it's safe to just remove it at least for now. @zsxwing

**Comment by shivaram** [comment]
Yeah that sounds reasonable to me. The funny thing is that we use VisibleForTesting in other files (like AsynchronousListenerBus.scala, ExternalSorter.scala etc.) -- Its a mystery to why this specific one leads to the error

**Comment by andrewor14** [comment]
Alright, I opened #6711 to do that.

**Comment by Sephiroth-Lin** [comment]
Close it first as PR #6711 can fix NPE, if we find the root cause of why the `@VisibleForTesting` annotation causes a NPE in the shell then reopen it.

**Pull request closed without merging**
