### PR TITLE
[SPARK-33613][PYTHON][TESTS] Replace deprecated APIs in pyspark tests

### PR DESCRIPTION
**Pull request by BryanCutler**
### What changes were proposed in this pull request?

This replaces deprecated API usage in PySpark tests with the preferred APIs. These have been deprecated for some time and usage is not consistent within tests.

- https://docs.python.org/3/library/unittest.html#deprecated-aliases

### Why are the changes needed?

For consistency and eventual removal of deprecated APIs.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Existing tests

### CODE REVIEW

**Comment by BryanCutler** [comment]
@HyukjinKwon I have noticed these have been inconsistent for a while, and seems like maybe now is a good time to clean up.

**Review by dongjoon-hyun — COMMENTED** [review]
Thank you, @BryanCutler . Does this PR update all of https://docs.python.org/3/library/unittest.html#deprecated-aliases ?

**Comment by dongjoon-hyun** [comment]
BTW, please fix Python linter error.
```
/python/pyspark/tests/test_rdd.py:743:33: E127 continuation line over-indented for visual indent
20
./python/pyspark/tests/test_rdd.py:750:33: E127 continuation line over-indented for visual indent
21
./python/pyspark/tests/test_rdd.py:752:33: E127 continuation line over-indented for visual indent
22
./python/pyspark/tests/test_rdd.py:754:33: E127 continuation line over-indented for visual indent
```

**Comment by BryanCutler** [comment]
> Thank you, @BryanCutler . Does this PR update all of https://docs.python.org/3/library/unittest.html#deprecated-aliases ?

Thanks @dongjoon-hyun , yes it is mostly these plus some uses of importing `pandas.util.testing` to use `pandas.testing`

**Comment by dongjoon-hyun** [comment]
Ur, sorry for misleading you. Those were a subset.
```
./python/pyspark/sql/tests/test_pandas_udf.py:214:42: E127 continuation line over-indented for visual indent
20
./python/pyspark/sql/tests/test_pandas_udf.py:235:42: E127 continuation line over-indented for visual indent
21
./python/pyspark/sql/tests/test_column.py:83:33: E127 continuation line over-indented for visual indent
22
./python/pyspark/sql/tests/test_udf.py:389:33: E127 continuation line over-indented for visual indent
23
./python/pyspark/sql/tests/test_udf.py:394:33: E127 continuation line over-indented for visual indent
24
./python/pyspark/sql/tests/test_udf.py:399:33: E127 continuation line over-indented for visual indent
25
./python/pyspark/sql/tests/test_utils.py:41:33: E127 continuation line over-indented for visual indent
26
./python/pyspark/sql/tests/test_utils.py:44:33: E127 continuation line over-indented for visual indent
27
./python/pyspark/sql/tests/test_utils.py:50:38: E127 continuation line over-indented for visual indent
28
./python/pyspark/sql/tests/test_dataframe.py:430:33: E127 continuation line over-indented for visual indent
29
./python/pyspark/sql/tests/test_dataframe.py:434:33: E127 continuation line over-indented for visual indent
```

**Comment by BryanCutler** [comment]
my fault, I should run it locally before pushing :<

**Review by HyukjinKwon — APPROVED** [review]
LGTM if tests pass

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
