### PR TITLE
[SPARK-31420][WEBUI] Infinite timeline redraw in job details page

### PR DESCRIPTION
**Pull request by sarutak**
### What changes were proposed in this pull request?

Upgrade vis.js to fix an infinite re-drawing issue.

As reported here, old releases of vis.js have that issue.
Fortunately, the latest version seems to resolve the issue.

With the latest release of vis.js, there are some performance issues with the original `timeline-view.js` and `timeline-view.css` so I also changed them.

### Why are the changes needed?

For better UX.

### Does this PR introduce any user-facing change?

No. Appearance and functionalities are not changed.

### How was this patch tested?

I confirmed infinite redrawing doesn't happen with a JobPage which I had reproduced the issue.

With the original version of vis.js, I reproduced the issue with the following conditions.

* Use history server and load core/src/test/resources/spark-events.
* Visit the JobPage for job2 in application_1553914137147_0018.
* Zoom out to 80% on Safari / Chrome / Firefox.

Maybe, it depends on OS and the version of browsers.

### CODE REVIEW

**Comment by sarutak** [comment]
cc: @gengliangwang 
I also reproduce the issue.
infinite-redrawing

After upgrading vis.js, the issue no longer happens in my environment.
Could you check in your environment too?

**Comment by gengliangwang** [comment]
@sarutak Thanks for the quick fix!
I checked it and found such error in console:
image

Should we put vis-timeline-graph2d.js.map into source as well?

**Comment by sarutak** [comment]
Oh, I've forgotten to add them. Will do soon.

**Review by gengliangwang — APPROVED** [review]
LGTM

**Comment by gengliangwang** [comment]
@sarutak @dongjoon-hyun shall we create another PR to fix this in branch-2.4 as well? I tried to cherry-pick and there are conflicts

**Comment by dongjoon-hyun** [comment]
+1 for @gengliangwang 's opinion for backporting.

**Comment by gengliangwang** [comment]
Thanks, merging to master/3.0

**Comment by dongjoon-hyun** [comment]
Thank you, @sarutak and @gengliangwang .

**Comment by gengliangwang** [comment]
BTW, there are conflicts in branch-3.0 as well. We have to back port this with another PR

**Comment by sarutak** [comment]
I'll create backporting-PR for them.

**Comment by srowen** [comment]
@sarutak Just to check: we don't use "vis" anymore but just "vis-timeline"? Just asking because the license was removed for the former. If so then this is OK.

**Comment by sarutak** [comment]
@srowen 
> Just to check: we don't use "vis" anymore but just "vis-timeline"? Just asking because the license was removed for the former. If so then this is OK.

Yes. As of version 5, they seemed to split the library into 5 libraries and each repository is now separate.
https://github.com/almende/vis/issues/2405
https://github.com/visjs

**Pull request closed without merging**
