### PR TITLE
[BUILD] Closes some stale PRs

### PR DESCRIPTION
**Pull request by HyukjinKwon**
## What changes were proposed in this pull request?

This PR proposes to close some stale PRs and ones suggested to be closed by committer(s)

Closes #12415
Closes #14765
Closes #15118
Closes #15184
Closes #15183
Closes #9440
Closes #15023
Closes #14643
Closes #14827
## How was this patch tested?

N/A

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
I might have to propose this later after queuing up those more; however, it seems some PRs against a branch to a branch such as 15118, 15184 and 15183 are triggering AppVeyor tests, leaving a failure mark for each commit in those branches.

**Comment by HyukjinKwon** [comment]
I don't mind closing this if they are so few. cc @srowen

**Comment by srowen** [comment]
Agree, and I would add: 9440 15023 14643 14827

**Comment by HyukjinKwon** [comment]
Thanks, I just updated them.

**Pull request closed without merging**
