### PR TITLE
[SPARK-9752][SQL] Support UnsafeRow in Sample operator.

### PR DESCRIPTION
**Pull request by rxin**
In order for this to work, I had to disable gap sampling.

### CODE REVIEW

**Comment by brkyvz** [comment]
LGTM

**Comment by brkyvz** [comment]
Actually, one question. Should we at least modify the RDD code to use the GapSampling, since we added the default as false?

**Comment by rxin** [comment]
@brkyvz the default is true?

**Comment by brkyvz** [comment]
I saw it as false for a moment for some reason. Nvm. Lgtm

**Comment by rxin** [comment]
I'm going to merge this since the failure is a streaming test.

**Pull request closed without merging**
