### PR TITLE
[SPARK-37649][PYTHON] Switch default index to distributed-sequence by default in pandas API on Spark

### PR DESCRIPTION
**Pull request by HyukjinKwon**
### What changes were proposed in this pull request?

This PR proposes to switch default index to `distributed-sequence` by default.

### Why are the changes needed?

`sequence` type relies on sending all data to one executor that easily causes OOM and make the computation slow
We should better switch to `distributed-sequence` type that truly distributes the data.

In my own internal benchmark, it boosts the performance around 2 ~ 3 times faster on average.

### Does this PR introduce _any_ user-facing change?

Ideally no. Order might be affected but that's not already guaranteed. 

### How was this patch tested?

Existing CI should test it out.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @ueshin @xinrong-databricks @itholic

**Comment by ueshin** [comment]
There are some places the default type in the docs, like:

https://github.com/apache/spark/blob/3704d4d6e7bd7f5f05db05a6a281f8015ad6ae1c/python/docs/source/user_guide/pandas_on_spark/best_practices.rst#L238

https://github.com/apache/spark/blob/3704d4d6e7bd7f5f05db05a6a281f8015ad6ae1c/python/docs/source/user_guide/pandas_on_spark/options.rst#L163

**Review by itholic — APPROVED** [review]
LGTM

**Review by ueshin — APPROVED** [review]
LGTM, pending tests.

**Comment by HyukjinKwon** [comment]
All tests passed at https://github.com/HyukjinKwon/spark/actions/runs/1580641441.

Merged to master.

**Pull request closed without merging**
