### PR TITLE
[SPARK-40781][CORE] Explain exit code 137 as killed due to OOM

### PR DESCRIPTION
**Pull request by warrenzhu25**
### What changes were proposed in this pull request?
Explain exit code 137 as killed due to SIGKILL. This is used in `Yarn` and `Standalone` when creating ExecutorExited as loss reason. 

In `Standalone`, it's most likely caused by oom killer due to OOM. 
In  `Yarn`, it's caused by nodemanager due to memory issue. https://aws.amazon.com/premiumsupport/knowledge-center/container-killed-on-request-137-emr/#:~:text=When%20a%20container%20(Spark%20executor,in%20narrow%20and%20wide%20transformations.

### Why are the changes needed?
Reduce the efforts of users to search the meaning of exit code.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Manually tested.

### CODE REVIEW

**Review by srowen — COMMENTED** [review]
Is that true in general or YARN-specific?

**Comment by warrenzhu25** [comment]
> Is that true in general or YARN-specific?

It's true for Linux.

**Review by dongjoon-hyun — COMMENTED** [review]
@warrenzhu25 I agree with you that this could be useful. I'm wondering where you need this?

In K8s, Apache Spark already provides the following explanation at `Spark UI` `Executor Tab` explicitly.
```
The executor with id 32 exited with exit code 137 (SIGKILL, possible container OOM).
The API gave the following container statuses:
    container name: spark-kubernetes-executor
    container image: ...
    container state: terminated
    container started at: 2022-08-06T16:49:25Z
    container finished at: 2022-08-06T20:04:01Z
    exit code: 137
    termination reason: OOMKilled
```

**Comment by warrenzhu25** [comment]
> possible container OOM

@dongjoon-hyun This is used in Yarn and Standalone when creating `ExecutorExited` as loss reason.

**Comment by dongjoon-hyun** [comment]
Could you add that details into the PR description, please?

> This is used in Yarn and Standalone when creating `ExecutorExited` as loss reason.

**Comment by LuciferYang** [comment]
137 can only represent being killed, such as `kill -9 pid`,  I don't think it must be OOM

**Comment by LuciferYang** [comment]
If  use NodeManager without the ability to persist containers, maybe it will clear all unregistered containers through `kill -9(137 status)` when the NodeManager restarts

**Comment by zhengruifeng** [comment]
IIRC, 143 is also due to OOM

**Comment by mridulm** [comment]
Can you point me to the reference where yarn mode is using `137` for OOM ? IIRC we simply kill the executor process in case there is an OOM

**Comment by warrenzhu25** [comment]
> Can you point me to the reference where yarn mode is using `137` for OOM ? IIRC we simply kill the executor process in case there is an OOM - which usually results in `143` as the return code ...
> 
> ```
> public class Test {
> 
>   public static void main(String[] args) {
>     long[] arr = new long[1024 * 1024 * 999];
>   }
> }
> 
> $ java -XX:OnOutOfMemoryError='kill %p'  -Xmx12m -cp . Test ; echo Error code: $?
> ```
> 
> This is coming from `128 + SIGTERM` - and sigterm is 15 in linux. See here for more [1]
> 
> [1] https://tldp.org/LDP/abs/html/exitcodes.html

My main goal is making exit code more readable in standalone, but this code is shared by both standalone and yarn. I see yarn exit code 137 from https://aws.amazon.com/premiumsupport/knowledge-center/container-killed-on-request-137-emr/#:~:text=When%20a%20container%20(Spark%20executor,in%20narrow%20and%20wide%20transformations.

**Comment by mridulm** [comment]
As I mentioned above, there is a reason why we end up with 143 for OOM - due to the way Apache Spark sets up `OnOutOfMemoryError`.  This ofcourse applies to OOM generated by the JVM - which results in SIGTERM.

`oom_reaper` in Linux is at an OS level - which relies on SIGKILL instead. (And so 128 + SIGKILL == 137).

It is much more common to hit OOM from JVM than from oom_reaper - unlike the machine is heavily oversubscribed: which might be vendor specific behavior.

**Pull request closed without merging**
