### PR TITLE
[INFRA] Close stale PRs

### PR DESCRIPTION
**Pull request by HyukjinKwon**
# What changes were proposed in this pull request?

This PR proposes to close stale PRs, mostly the same instances with https://github.com/apache/spark/pull/18017

Closes #11459
Closes #13833
Closes #13720
Closes #12506
Closes #12456
Closes #12252
Closes #17689
Closes #17791
Closes #18163
Closes #17640
Closes #17926
Closes #18163
Closes #12506
Closes #18044
Closes #14036
Closes #15831
Closes #14461
Closes #17638
Closes #18222

Added:
Closes #18045
Closes #18061
Closes #18010
Closes #18041
Closes #18124
Closes #18130
Closes #12217

Added:
Closes #16291
Closes #17480
Closes #14995

Added:
Closes #12835
Closes #17141

## How was this patch tested?

N/A

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Please let me know if any author is active on this. Let me take them out. I picked up inclusively.

**Comment by HyukjinKwon** [comment]
cc @vanzin and @srowen.

**Comment by gatorsmile** [comment]
cc @jiangxb1987 Could you take a look at the list too?

**Comment by srowen** [comment]
Add to the list:

https://github.com/apache/spark/pull/18045
https://github.com/apache/spark/pull/18061
https://github.com/apache/spark/pull/18010
https://github.com/apache/spark/pull/18041
https://github.com/apache/spark/pull/18124
https://github.com/apache/spark/pull/18130
https://github.com/apache/spark/pull/12217

**Comment by vanzin** [comment]
Add:
#16291
#17480
#14995

**Comment by jiangxb1987** [comment]
Add:
#12835
#17141 
#18044 
#18130

**Comment by HyukjinKwon** [comment]
#18130, #18044 are duplicates. I added all assuming they are inactive or reviewed.

Just to make sure, https://github.com/apache/spark/pull/12835 was also reviewed and then suggested to be closed?

**Comment by HyukjinKwon** [comment]
#18130 and #18044 are duplicates. I added the others assuming they are inactive or reviewed.

Just to make sure, https://github.com/apache/spark/pull/12835 was also reviewed and then suggested to be closed?

**Comment by jiangxb1987** [comment]
@HyukjinKwon How about keep #17716 open? I think we still need this and Herman will continue working on this.

**Comment by HyukjinKwon** [comment]
Sure.

**Comment by HyukjinKwon** [comment]
I took out 17645 per https://github.com/apache/spark/pull/17645#issuecomment-306907150

**Comment by HyukjinKwon** [comment]
Took out 15326 per https://github.com/apache/spark/pull/15326#issuecomment-306974580

**Comment by srowen** [comment]
I'll merge this. If anything got closed that anyone disagrees with, it can easily be reopened, so there is virtually no harm in a false-positive anyway. But looks like the list has been reasonably reviewed.

**Pull request closed without merging**
