### PR TITLE
[SPARK-7624] Revert #4147

### PR DESCRIPTION
**Pull request by davies**

### CODE REVIEW

**Comment by davies** [comment]
cc @JoshRosen @pwendell

**Comment by kayousterhout** [comment]
LGTM

**Comment by JoshRosen** [comment]
Should this patch also go into 1.3.2, since the original patch that it's reverting seems to have caused a regression in 1.3.1?

**Comment by davies** [comment]
@JoshRosen Yes, should I sending another PR (if it can not be back ported cleanly)?

**Comment by JoshRosen** [comment]
Merged to 1.4.0 / master; it doesn't apply cleanly to 1.3.2, so maybe we should open another PR for that.

**Comment by davies** [comment]
@JoshRosen I think we can revert the original patch on 1.3 branch.

**Pull request closed without merging**
