### PR TITLE
[SPARK-42686][CORE] Defer formatting for debug messages in TaskMemoryManager

### PR DESCRIPTION
**Pull request by alkis**
### What changes were proposed in this pull request?

Defer formatting of bytes until debug logging is required. Otherwise we are always spending cycles doing formatting irrespective of if debug logging is enabled.

### Why are the changes needed?
Formatting shows up in profiling scan benchmarks.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Manually.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Mind retriggering https://github.com/alkis/spark/runs/11797022157?

**Comment by alkis** [comment]
> Mind retriggering https://github.com/alkis/spark/runs/11797022157?

Done.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by pan3793** [comment]
Would the following code achieve the same improvements?
```
if (logger.isDebugEnabled()) {
  logger.debug("string {}", <expensive_function>);
}
```

**Comment by mridulm** [comment]
@pan3793's suggestion is simpler and less change.

**Comment by alkis** [comment]
Good idea! Done.

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
