### PR TITLE
[DOC] Minor modification to Streaming docs with regards to parallel data receiving

### PR DESCRIPTION
**Pull request by nishkamravi2**
@pwendell @tdas

### CODE REVIEW

**Comment by srowen** [comment]
That's fine. This does not warrant a JIRA.
(PS why do your PRs have a huge merge history? you'd normally just branch from an updated master right?)

**Comment by nishkamravi2** [comment]
Yeah, the JIRA in the title seems unnecessary (removed). With regards to the merge history: not sure, will have to look into it.

**Comment by tdas** [comment]
LGTM other than the commit history.
Can you just just checkout the spark github master branch and cherry-pick your change (commit 46e8c03) on it. That should keep the commit history clean.

**Comment by srowen** [comment]
FWIW I keep `master` in my fork up to date with `git pull upstream master` and `git push origin master`. Then whenever you make a branch, just branch from your `master`. Have you been merging into your `master`? It should just track the upstream one directly with no variance.

**Pull request closed without merging**
