### PR TITLE
Revert "[SPARK-33228][SQL] Don't uncache data when replacing a view having the same logical plan

### PR DESCRIPTION
**Pull request by viirya**
This reverts commit a85d69049c5ad994b3fb6cde1b3d739f3da336d4.

### CODE REVIEW

**Comment by viirya** [comment]
#30140 causes Python test failed in 2.4 (https://github.com/apache/spark/runs/1307296057) even I re-ran it. I'm going to revert it from 2.4.

**Comment by dongjoon-hyun** [comment]
Please hold on this reverting. I'll take a look.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

Thank you, @viirya !

**Comment by dongjoon-hyun** [comment]
In Jenkins, Python tests passed.
```
...
Finished test(python3.6): pyspark.ml.tests (187s)
Tests passed in 951 seconds
```

**Comment by dongjoon-hyun** [comment]
Merged to branch-2.4.

**Comment by viirya** [comment]
Thanks @dongjoon-hyun

**Pull request closed without merging**
