### PR TITLE
[SPARK-12747][SQL] Use correct type name for Postgres JDBC's real array

### PR DESCRIPTION
**Pull request by viirya**
https://issues.apache.org/jira/browse/SPARK-12747

Postgres JDBC driver uses "FLOAT4" or "FLOAT8" not "real".

### CODE REVIEW

**Comment by viirya** [comment]
retest this please.

**Comment by viirya** [comment]
retest this please.

**Comment by viirya** [comment]
retest this please.

**Comment by viirya** [comment]
Type mapping for various types *** FAILED *** (1 second, 877 milliseconds)
[info]   Array(0.11, 0.22) did not equal Array(0.11, 0.22) (PostgresIntegrationSuite.scala:84)

Array(0.11, 0.22) did not equal Array(0.11, 0.22)?

**Comment by blbradley** [comment]
Looks good, but you should squash your commits into one.

**Comment by JoshRosen** [comment]
@blbradley, no need to squash the commits; that happens automatically as part of our PR merge script.

**Comment by viirya** [comment]
ping @rxin

**Comment by viirya** [comment]
ping @liancheng @yhuai @rxin Can you see if this fixing is good for you? Thanks.

**Comment by blbradley** [comment]
This is blocking me. Can we get it merged soon?

I'm waiting to submit another PR to fix DecimalType also.

**Comment by viirya** [comment]
ping @liancheng @yhuai @rxin How do you think about this? Can we merge it now?

**Comment by rxin** [comment]
Thanks - I've merged this in master.

**Pull request closed without merging**
