### PR TITLE
[SPARK-42114][SQL] Test of uniform parquet encryption

### PR DESCRIPTION
**Pull request by ggershinsky**
Unitest of the new parquet encryption mode, available since parquet 1.12.3.

### CODE REVIEW

**Comment by ggershinsky** [comment]
@dongjoon-hyun I'm submitting the PR we have discussed.

**Comment by ggershinsky** [comment]
Re CI failure : 
"Error: Unhandled error: Error: There was a new unsynced commit pushed. Please retrigger the workflow."
 I've re-opened the PR, but this didn't help.

**Comment by ggershinsky** [comment]
Bypassed this problem by re-creating the PR. Closing this one.

**Comment by dongjoon-hyun** [comment]
I merged the newer PR, @ggershinsky . :)
- https://github.com/apache/spark/commit/e1c630a98c45ae07c43c8cf95979532b51bf59ec

**Pull request closed without merging**
