### PR TITLE
[SPARK-9437][core] avoid overflow in SizeEstimator

### PR DESCRIPTION
**Pull request by squito**
https://issues.apache.org/jira/browse/SPARK-9437

### CODE REVIEW

**Comment by squito** [comment]
any suggestions on a test that doesn't require 2 GB of memory?

**Comment by shivaram** [comment]
LGTM. Could we also check all the other instances where alignSize is called ?

**Comment by squito** [comment]
@shivaram good idea.  I updated one more spot where it seems there could be overflow -- I will admit I don't completely understand what is going on there, but the change seems safe.  the only other place its called is https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/util/SizeEstimator.scala#L217 which is not going to overflow.

**Comment by srowen** [comment]
Does the `val size = math.min(s1, s2)` line need `toLong` too? it gets multiplied by a big number before being divided by one. I could be missing why it's not needed or can't be done but seemed like a possible issue.

**Comment by squito** [comment]
`s1` & `s2` are already longs, which means so is `size` -- so no change needed there.
(not that I had checked this before you mentioned it ...)

**Comment by shivaram** [comment]
Yeah its tricky to add a test case for this -- We could do it by refactoring the code and testing a smaller function which takes in the array size as an argument etc. but that'll be a much bigger code change. Since this is a more contained change I'd actually recommend just merging the current diff for now.

**Comment by squito** [comment]
Jenkins, retest this please

**Comment by squito** [comment]
Jenkins, retest this please

**Comment by shivaram** [comment]
LGTM. Merging this

**Pull request closed without merging**
