### PR TITLE
[SPARK-8733][MLLIB] ML RDD.unpersist calls should use blocking = false

### PR DESCRIPTION
**Pull request by ilganeli**
Updated all usages within the ML Lib module to use blocking = false.

### CODE REVIEW

**Comment by mengxr** [comment]
@ilganeli I'm not sure whether this is a safe change. If the old ones are not deleted from block managers, new RDDs might not be able to cache or have to downgrade the storage level. Since it is hard to tell when the next caching happens, we set blocking to true to be safe. It would be great if you can share some benchmark results, so we can easily see the trade-off and decide.

**Comment by ilganeli** [comment]
@mengxr @jkbradley Initially reported this, perhaps he should weigh in here?

**Comment by andrewor14** [comment]
I think the concern is that the memory cache is not fully LRU. If a new big block shows up when the memory cache is almost full, then there's a chance that the new block will end up being dropped straight to disk instead.

Here's how this issue is related: if the asynchronous unpersist happens too slowly, a workload that previously would have benefited from the new block being cached in memory may now drop the new block to disk directly instead. Whether this happens is largely workload dependent.

@ilganeli Have you had a chance to benchmark performances of a few algorithms before and after this change? It will be hard to assert with confidence that this will actually improve performance for most workloads.

**Comment by jkbradley** [comment]
Good points; I suppose unpersisting without blocking might cause other slowdowns which could cause other timeouts to occur.  This does seem like the kind of change which might require running all of the MLlib tests in spark-perf on a cluster to test for speed changes.  Perhaps a better solution in the meantime is simply to adjust timeout settings as needed.

@mengxr I'm OK with closing the JIRA if it does not seem worth the trouble of testing.  @ilganeli I doubt we have the bandwidth to test right now, but do let us know if you'd like to keep this open & run tests.

**Comment by ilganeli** [comment]
All - thanks for the clarification and weigh in. I don't have any pipelines set up that would exercise this with the level of rigor necessary. I think it's fine to close it for now. Thanks.



Thank you,
Ilya Ganelin



-----Original Message-----

**Comment by jkbradley** [comment]
OK, sorry for the trouble!  Can you please close this PR?  (We can't)

**Comment by ilganeli** [comment]
Will do once I have access to a PC. No trouble at all.



Thank you,
Ilya Ganelin



-----Original Message-----

**Pull request closed without merging**
