### PR TITLE
[SPARK-15118][SQL] Spark SQLConf should support loading hive properties in hive-site.xml

### PR DESCRIPTION
**Pull request by StefanXiepj**
### What changes were proposed in this pull request?

When initializing sqlconf, we merged sparkconf, we should also merge hiveconf too.

### Why are the changes needed?

Usually, we have many default settings, such as:
```
set hive.default.fileformat=orcfile;
```
In hive, the default setting can be in hive-site.xml. I think we should support the same behavior.

In this example, when created a table which is stored as Orc by default, you don't execute command like this:
 ```
set hive.default.fileformat=orcfile;
create table ... stored as orc;
```
but spark need.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

UT test

### CODE REVIEW

**Comment by StefanXiepj** [comment]
hi @maropu ,

    Could you please take a look at this and give some advice? Thx.

Jeff.r

**Review by gatorsmile — CHANGES_REQUESTED** [review]
We will not respect Hive's hive.default.fileformat in Spark 3.1 when creating tables. 
See the JIRA https://issues.apache.org/jira/browse/SPARK-31257.

**Comment by gatorsmile** [comment]
https://github.com/apache/spark/pull/24489 has addressed your major concern. For the other conf, we can discuss it case by case. In general, we are not respecting Hive conf.

**Comment by StefanXiepj** [comment]
> #24489 has addressed your major concern. For the other conf, we can discuss it case by case. In general, we are not respecting Hive conf.

@gatorsmile This pr will  be closed, thanks very much for taking the time to review.

**Pull request closed without merging**
