### PR TITLE
[SPARK-24997[SQL] Enable support of MINUS ALL

### PR DESCRIPTION
**Pull request by dilipbiswal**
## What changes were proposed in this pull request?
Enable support for MINUS ALL which was gated at AstBuilder.

## How was this patch tested?
Added tests in SQLQueryTestSuite and modify PlanParserSuite.

Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Comment by maropu** [comment]
Probably, IMO we need a new jira for this.

**Comment by dilipbiswal** [comment]
@maropu OK. I will create a new JIRA. Actually i missed it in original PR. @gatorsmile had put a code review comment to add "MINUS" in the documentation that got me to test the scenario :-)

**Comment by dilipbiswal** [comment]
retest this please

**Comment by dilipbiswal** [comment]
retest this please

**Review by gatorsmile — COMMENTED** [review]
LGTM

Thanks! Merged to master.

**Pull request closed without merging**
