### PR TITLE
[SPARK-43065][SQL][TESTS] Set job description in `TPCDSQueryBenchmark`

### PR DESCRIPTION
**Pull request by caican00**
### What changes were proposed in this pull request?
Set job description for tpcds queries.

Before optimization：
image

After optimization：
image

### CODE REVIEW

**Comment by caican00** [comment]
@maropu Could you help to review this pr? Thanks

**Review by AngersZhuuuu — APPROVED** [review]
LGTM

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Mind retriggering https://github.com/caican00/spark/runs/12587259773?

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM (Pending CIs) as mentioned in the previous comment.

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by LuciferYang** [comment]
late LGTM

**Pull request closed without merging**
