### PR TITLE
[SPARK-14535][SQL] Remove buildInternalScan from FileFormat

### PR DESCRIPTION
**Pull request by cloud-fan**
## What changes were proposed in this pull request?

Now `HadoopFsRelation` with all kinds of file formats can be handled in `FileSourceStrategy`, we can remove the branches for  `HadoopFsRelation` in `FileSourceStrategy` and the `buildInternalScan` API from `FileFormat`.
## How was this patch tested?

existing tests.

### CODE REVIEW

**Comment by cloud-fan** [comment]
CC @marmbrus @liancheng @yhuai

**Comment by liancheng** [comment]
We can also remove [these pattern match guard conditions][1] and the `spark.sql.sources.fileScan` SQL option.

[1]: https://github.com/apache/spark/blob/e82d95bf63f57cefa02dc545ceb451ecdeedce28/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/FileSourceStrategy.scala#L59-L66

**Comment by liancheng** [comment]
And the ORC data source, which lives in the `sql/hive`, hasn't been cleaned yet.

**Comment by yhuai** [comment]
Ah. sorry. Maybe the commit I just made caused the conflicts...

**Comment by cloud-fan** [comment]
np, I already fixed it :)

**Comment by yhuai** [comment]
LGTM

**Comment by yhuai** [comment]
Thanks. Merging to master.

**Pull request closed without merging**
