### PR TITLE
[SPARK-46197][INFRA] Upgrade `memory-profiler>=0.61.0` for Python 3.12

### PR DESCRIPTION
**Pull request by zhengruifeng**
### What changes were proposed in this pull request?
Upgrade memory-profiler>=0.61.0 for Python 3.12

### Why are the changes needed?
`memory-profiler==0.60.0` does not support Python 3.12

### Does this PR introduce _any_ user-facing change?
no

### How was this patch tested?
ci

### Was this patch authored or co-authored using generative AI tooling?
no

### CODE REVIEW

**Comment by zhengruifeng** [comment]
ci link: https://github.com/zhengruifeng/spark/actions/runs/7056172250

**Review by dongjoon-hyun — APPROVED** [review]
Thank you, @zhengruifeng .

Could you add some PR descriptions where we can find the information about Python 3.12 support?

- https://pypi.org/project/memory-profiler/0.61.0/
- https://github.com/pythonprofilers/memory_profiler/compare/v0.60...v0.61

**Comment by zhengruifeng** [comment]
@dongjoon-hyun It's not documented, but I hit a install failure related to `memory-profiler==0.60.0` in https://github.com/zhengruifeng/spark/actions/runs/7055481499/job/19206520390

I combine two `RUN pip install` together to see whether there are some conflicts:

`RUN python3.12 -m pip install numpy pyarrow>=14.0.0 six==1.16.0 pandas<=2.1.3 scipy unittest-xml-reporting plotly>=4.8 mlflow>=2.8.1 coverage matplotlib openpyxl memory-profiler==0.60.0 scikit-learn>=1.3.2 grpcio==1.59.3 grpcio-status==1.59.3 protobuf==4.25.1 googleapis-common-protos==1.56.4` fails with 

```
#41 1.320 Collecting memory-profiler==0.60.0
#41 1.321   Using cached memory_profiler-0.60.0.tar.gz (38 kB)
#41 1.331   Preparing metadata (setup.py): started
#41 1.398   Preparing metadata (setup.py): finished with status 'error'
#41 1.403   error: subprocess-exited-with-error
#41 1.403   
#41 1.403   × python setup.py egg_info did not run successfully.
#41 1.403   │ exit code: 1
#41 1.403   ╰─> [1 lines of output]
#41 1.403       ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
#41 1.403       [end of output]
#41 1.403   
#41 1.403   note: This error originates from a subprocess, and is likely not a problem with pip.
#41 1.404 error: metadata-generation-failed
#41 1.404 
#41 1.404 × Encountered error while generating package metadata.
#41 1.404 ╰─> See above for output.
#41 1.404 
#41 1.404 note: This is an issue with the package mentioned above, not pip.
#41 1.404 hint: See above for details.
```

then seems the latest version 0.61.0 works

**Comment by dongjoon-hyun** [comment]
Got it~ Thank you for explaining the context. Let me merge this~

**Comment by zhengruifeng** [comment]
@dongjoon-hyun thanks for the reviews

**Pull request closed without merging**
