### PR TITLE
[SPARK-14177] [SQL] Native Parsing for DDL Command "Describe Database" and "Alter Database"

### PR DESCRIPTION
**Pull request by gatorsmile**
#### What changes were proposed in this pull request?

This PR is to provide native parsing support for two DDL commands:  `Describe Database` and `Alter Database Set Properties`

Based on the Hive DDL document:
https://cwiki.apache.org/confluence/display/Hive/LanguageManual+DDL
##### 1. ALTER DATABASE

**Syntax:**

``` SQL
ALTER (DATABASE|SCHEMA) database_name SET DBPROPERTIES (property_name=property_value, ...)
```
- `ALTER DATABASE` is to add new (key, value) pairs into `DBPROPERTIES`
##### 2. DESCRIBE DATABASE

**Syntax:**

``` SQL
DESCRIBE DATABASE [EXTENDED] db_name
```
- `DESCRIBE DATABASE` shows the name of the database, its comment (if one has been set), and its root location on the filesystem. When `extended` is true, it also shows the database's properties
#### How was this patch tested?

Added the related test cases to `DDLCommandSuite`

### CODE REVIEW

**Comment by gatorsmile** [comment]
cc @yhuai @hvanhovell @viirya

**Comment by yhuai** [comment]
LGTM. Let's rebase the PR. Thanks!

**Comment by gatorsmile** [comment]
sure, let me do it now. Thanks!

**Comment by yhuai** [comment]
Merging to master. Thanks!

**Comment by yhuai** [comment]
I have fixed the conflict.

**Pull request closed without merging**
