### PR TITLE
SPARK-16920: Add a stress test for evaluateEachIteration for 2000 trees

### PR DESCRIPTION
**Pull request by mhmoudr**
## What changes were proposed in this pull request?

Just adding a test to prove error by tree is working for 2000 trees, the fix of SPARK-15858
before it was failing to do the calculation after long time
 
## How was this patch tested?

Just run the test

### CODE REVIEW

**Comment by jkbradley** [comment]
The key point @vlad17 made was that an operation which should be O(N) is taking O(N^2) in the current implementation.  Let's fix that, regardless of whether or not we add a stress test.

Also, we can't add such a long test for this.  Unit tests should take seconds at most, and ideally sub-second times.  Offline stress testing is great, though.

Thanks!

**Comment by vlad17** [comment]
Yes, sorry for my wording. A unit test is indeed an inappropriate place for stress tests. An offline test would be sufficient to verify that an O(N) implementation is an improvement over the O(N^2) one. Ideally the stress test would be neatly described in the PR message so that anyone could replicate, perhaps even linking to a gist with the script to run it.

**Comment by jkbradley** [comment]
@mhmoudr Will you be able to update this?

**Comment by mhmoudr** [comment]
Sure .. I am, but just a bit busy nowadays, in general I am planing to investigate the additional complexity issue, and as for the test I agree with the fact that the test should not be added to unit test as far as there is a specific agreed manner for adding stress tests, also to add, in term of the test itself, I would say it will be a wast of time to train the model  every time we need to test this area, so I was thinking of train a model once and save it to resources, then once I need to test the evaluateEachIteration it will be much faster to lead the pre saved model from resources and run the test directly, thoughts?

for the time being I will close the pull request and once I have the change ready I will create a new one.
Mahmoud

**Comment by mhmoudr** [comment]
* To traing a (one-off) model a keep it in resources, then load it to run the test.
* investigate the added comlexity issue.
* To move the test away from unit tests
* Provide instructions on how to run the stress test

**Comment by jkbradley** [comment]
Thanks @mhmoudr
As far as the stress test, I'd recommend posting instructions as a Github gist and linking it to wherever you post results on JIRA or a PR.  We wouldn't want to add a model (a binary file) to git unless absolutely necessary.

When we address the complexity issue, we can post stress test results and the link to the gist.

**Pull request closed without merging**
