### PR TITLE
[SPARK-38885][BUILD] Upgrade Netty to 4.1.76

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr aims to upgrade Netty to 4.1.76

### Why are the changes needed?
This version starts to support [explicitly bind channels to either IPv4 or IPv6](https://github.com/netty/netty/pull/12270), but this feature only works in Java 15+. The release notes as follows:

- https://netty.io/news/2022/04/12/4-1-76-Final.html

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass GA

### CODE REVIEW

**Comment by LuciferYang** [comment]
Test Link: https://github.com/LuciferYang/spark/runs/6020296111

**Review by srowen — APPROVED** [review]
Seems fine. We may not need to pick up every little maintenance release, but if this helps at all, OK

**Comment by LuciferYang** [comment]
ok ~ got it

**Comment by srowen** [comment]
Do you have a link to successful tests in your own github workflow? The PR builder status here still isn't reliable, AFAIK

**Comment by LuciferYang** [comment]
Test Link https://github.com/LuciferYang/spark/runs/6020234537

**Comment by LuciferYang** [comment]
image

**Comment by srowen** [comment]
merged to master

**Comment by LuciferYang** [comment]
@srowen I found a very interesting thing:

After this pr, if I execute `./dev/test-dependencies.sh --replace-manifest ` on Linux, the result files are same as the files  copy in the current master.

But if I execute `./dev/test-dependencies.sh --replace-manifest ` on MacOs, the result files are differences with the files  copy in the current master:

image

The deps file generated on MacOS lacks the native jars related to Linux, do you have any suggestions

**Comment by srowen** [comment]
I also saw something weird like that and manually reverted some of the changes so that it was just a straight change of existing dependencies. I'm not sure what's going on with the script or Macos

**Pull request closed without merging**
