### PR TITLE
[SPARK-34859][SQL] parquet vectorized reader - support column index with rowIndexes

### PR DESCRIPTION
**Pull request by lxian**
### What changes were proposed in this pull request?

Use row indexes to read column values properly in Parquet vectorized reader. It works like follow
1. Save rowIndexes to VectorizedColumnReader
2. In the loop of a readBatch, write batch number of values into a temp vector 
3. Check the indexes of values in the temp vector with rowIndexes, write matched values to the result vector
4. If the result vector is not full, go back to step 2

### Why are the changes needed?

When using column index, pages among different columns may not be aligned. And rowIndexes is needed to synchronize rows in different columns. 

### Does this PR introduce _any_ user-facing change?

no.

### How was this patch tested?

still work in progress. below testes are needed
1. Test for the correctness of filtered result on column index. It need to be tested on unaligned pages.
2. A benchmark on the column index

### CODE REVIEW

**Comment by lxian** [comment]
I did a simple benchmark on it, and the result looks good
```
Running benchmark: simple filters
  Running case: Parquet Vectorized 
  Stopped after 5 iterations, 6065 ms
  Running case: Parquet Vectorized (columnIndex)
  Stopped after 27 iterations, 2048 ms

Java HotSpot(TM) 64-Bit Server VM 1.8.0_111-b14 on Mac OS X 10.14.4
Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
simple filters:                           Best Time(ms)   Avg Time(ms)   Stdev(ms)    Rate(M/s)   Per Row(ns)   Relative
------------------------------------------------------------------------------------------------------------------------
Parquet Vectorized                                 1169           1213          55         13.5          74.3       1.0X
Parquet Vectorized (columnIndex)                     61             76          11        258.4           3.9      19.2X

Running benchmark: range filters
  Running case: Parquet Vectorized 
  Stopped after 5 iterations, 6338 ms
  Running case: Parquet Vectorized (columnIndex)
  Stopped after 6 iterations, 2128 ms

Java HotSpot(TM) 64-Bit Server VM 1.8.0_111-b14 on Mac OS X 10.14.4
Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
range filters:                            Best Time(ms)   Avg Time(ms)   Stdev(ms)    Rate(M/s)   Per Row(ns)   Relative
------------------------------------------------------------------------------------------------------------------------
Parquet Vectorized                                 1222           1268          79         12.9          77.7       1.0X
Parquet Vectorized (columnIndex)                    346            355           8         45.4          22.0       3.5X
```

**Review by HyukjinKwon — COMMENTED** [review]
I think it wouldn't affect the performance significantly when the dataset is actually large with many files in production? I doubt if it's worthwhile to manage a separate index.

It would be great if we run TPC-DS or a proper benchmark and see if there are significant performance improvement.

**Comment by lxian** [comment]
> I think it wouldn't affect the performance significantly when the dataset is actually large with many files in production? I doubt if it's worthwhile to manage a separate index.
> 
> It would be great if we run TPC-DS or a proper benchmark and see if there are significant performance improvement.

I think the performance will depend on the selectivity of the filter in the query. The index will only be applied if there are some pages to be skipped in a rowgroup. There is some benchmark by 
@wangyum  https://github.com/apache/spark/pull/31393

I will run a TPC-DS benchmark later to see if there is some improvements

**Comment by HyukjinKwon** [comment]
Most of row groups will be filtered before we actually read the batch, right. Does the row-index work for row group filtering too?

**Comment by lxian** [comment]
The row indexes is not for filtering pages or rowgroups. The row indexes is used to work with the parquet column index to ensure that the filtered pages in a row group is synchronized among different columns.

**Comment by HyukjinKwon** [comment]
My point is that it the row index will be only effective in the underlying row group. Most of row groups will be filtered out in production. Thats why I said the actual impact won't be significant.

**Comment by lxian** [comment]
https://gist.github.com/lxian/bba60a0460a74d3427994ce0d60d4c79 I've run a benchmark on tpcds with scale 10 and the impact of column index looks subtle.

**Comment by sunchao** [comment]
@lxian does it mean that, without this PR, vectorized Parquet reader may return incorrect results?

**Comment by lxian** [comment]
> @lxian does it mean that, without this PR, vectorized Parquet reader may return incorrect results?

Yes, the result may be incorrect in cases that data page among columns are unaligned (for example, columns of different data types)

**Comment by sunchao** [comment]
@lxian In the current approach we'd have to copy values from one vector to another. I think a better and more efficient approach may be to feed the row indexes to `VectorizedRleValuesReader#readXXX` and skip rows if they are not in the range, so basically we increment both `rowId` and row indexes in parallel.

**Comment by lxian** [comment]
> @lxian In the current approach we'd have to copy values from one vector to another. I think a better and more efficient approach may be to feed the row indexes to `VectorizedRleValuesReader#readXXX` and skip rows if they are not in the range, so basically we increment both `rowId` and row indexes in parallel.

In `VectorizedRleValuesReader` the values are read in batch or in a simple loop. I am wondering whether it will make it slow if we put the row index filtering there.

**Comment by sunchao** [comment]
@lxian I'm thinking that the extra cost is just incrementing two indexes at the same time, so it should be fairly cheap. You can also refer to how [SynchronizingColumnReader](https://github.com/apache/parquet-mr/blob/master/parquet-column/src/main/java/org/apache/parquet/column/impl/SynchronizingColumnReader.java#L89) is doing that. 

Porting that logic to Spark is a bit tricky though, especially when it comes to handle the RLE-encoded definition levels. Let me try experimenting this idea too on my side.

**Comment by lxian** [comment]
@sunchao you are right. it's real tricky and would require a long of changes as well. VectorizedValuesReader currently read and put all values to columns vector for a single data page. Interfaces need to be changed to allow VectorizedValuesReader to read a portion of a data page.

**Comment by sunchao** [comment]
@lxian Yes. I opened #32753 to demonstrate the idea. It's about 1K LOC but mostly because the same code has to be duplicated in several places. This is an existing issue in the Parquet vectorized code path but I think it's possible to eliminate the duplication.

**Pull request closed without merging**
