### PR TITLE
[SPARK-45577][PYTHON] Fix UserDefinedPythonTableFunctionAnalyzeRunner to pass folded values from named arguments

### PR DESCRIPTION
**Pull request by ueshin**
### What changes were proposed in this pull request?

Fix `UserDefinedPythonTableFunctionAnalyzeRunner` to pass folded values from named arguments.

### Why are the changes needed?

In the analysis in Python for Python UDTF, the folded values are not passed from named arguments.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Modified the related tests.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by ueshin** [comment]
cc @dtenedor

**Review by dtenedor — APPROVED** [review]
Thanks for the quick fix!

**Comment by ueshin** [comment]
The failed tests seem not to be related to this PR.

**Comment by ueshin** [comment]
Thanks! merging to master.

**Review by allisonwang-db — COMMENTED** [review]
Good catch!

**Pull request closed without merging**
