### PR TITLE
[SPARK-46430][CONNECT][TESTS] Add test for `ProtoUtils.abbreviate`

### PR DESCRIPTION
**Pull request by zhengruifeng**
### What changes were proposed in this pull request?
Add test for `ProtoUtils.abbreviate`

### Why are the changes needed?
`ProtoUtils.abbreviate` is not tested, for better test coverage
we are going to improve this functionality, before that we should protect its behavior.

### Does this PR introduce _any_ user-facing change?
no, test-only

### How was this patch tested?
added ut

### Was this patch authored or co-authored using generative AI tooling?
no

### CODE REVIEW

**Comment by zhengruifeng** [comment]
cc @HyukjinKwon

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by dongjoon-hyun** [comment]
Merged to master.

**Comment by zhengruifeng** [comment]
thanks @dongjoon-hyun

**Pull request closed without merging**
