### PR TITLE
[SPARK-15528][SQL] Fix race condition in NumberConverter

### PR DESCRIPTION
**Pull request by maropu**
## What changes were proposed in this pull request?

A local variable in NumberConverter is wrongly shared between threads.
This pr fixes the race condition.
## How was this patch tested?

Manually checked.

### CODE REVIEW

**Comment by srowen** [comment]
CC @tarekauel It is certainly a problem if this code is called from several threads in one JVM. It's possible it was written this way because for whatever reason this will never happen. However that doesn't strike me as likely. LGTM

**Comment by maropu** [comment]
@rxin @tarekauel Seems this bug is a kind of critical issues, so we need to fix for the v2.0 release, thought?

**Comment by rxin** [comment]
Yes this is definitely a problem worth fixing. We should probably also backport this into 1.6.

cc @davies @sameeragarwal

**Comment by srowen** [comment]
Merged to master/2.0/1.6

**Comment by maropu** [comment]
thanks!

**Pull request closed without merging**
