### PR TITLE
[SPARK-23279][SS] Avoid triggering distributed job for Console sink

### PR DESCRIPTION
**Pull request by jerryshao**
## What changes were proposed in this pull request?

Console sink will redistribute collected local data and trigger a distributed job in each batch, this is not necessary, so here change to local job.

## How was this patch tested?

Existing UT and manual verification.

### CODE REVIEW

**Comment by jerryshao** [comment]
CC @tdas , please help to review. Thanks!

**Comment by tdas** [comment]
Thank you very much for fixing this.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by jerryshao** [comment]
Merging to master and 2.3. Thanks for the review!

**Pull request closed without merging**
