### PR TITLE
[SPARK-10148][Streaming]Display active and inactive receiver numbers in Streaming page

### PR DESCRIPTION
**Pull request by zsxwing**
Added the active and inactive receiver numbers in the summary section of Streaming page.

screen shot 2015-08-21 at 2 08 54 pm

### CODE REVIEW

**Comment by zsxwing** [comment]
@tdas, I feel there is no enough space to display these numbers along with the average input rate, so I added them in the summary section.

**Comment by tdas** [comment]
I think thats too much information at the top, its getting hard to read. I think its better to do it here. 
https://databricks.com/wp-content/uploads/2015/07/image1.png
Near B, before the "Avg: ..."

**Comment by zsxwing** [comment]
screen shot 2015-08-21 at 11 25 44 pm

**Comment by tdas** [comment]
Sorry, one more suggestion. Maybe more consistent "Avg: .." if we do "Receivers: 1/2 active"
And if there are no receivers, then dont show this line at all.

**Comment by zsxwing** [comment]
Updated.
screen shot 2015-08-22 at 8 36 17 pm

**Comment by tdas** [comment]
LGTM. Merging this to master and 1.5 (since this is a very small change). Thanks @zsxwing

**Pull request closed without merging**
