### PR TITLE
[SPARK-42350][SQL][K8S][SS] Replcace `get().getOrElse` with `getOrElse`

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr just a trivial fix, replcace `get().getOrElse` with `getOrElse`

### Why are the changes needed?
Code simplification

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass GitHub Actions

### CODE REVIEW

**Comment by srowen** [comment]
Can you look for more instances across the code base?

**Comment by LuciferYang** [comment]
should be no more

**Comment by srowen** [comment]
Merged to master

**Comment by LuciferYang** [comment]
Thanks @srowen

**Pull request closed without merging**
