### PR TITLE
[MINOR][DOC] Fix typo in SqlBaseLexer.g4

### PR DESCRIPTION
**Pull request by jiaoqingbo**
### What changes were proposed in this pull request?

Fix typo in SqlBaseLexer.g4

### Why are the changes needed?

Better documentation

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

N/A

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Thank you for making a PR. Is this the last typo instance in this file or in this `parser` directory, @jiaoqingbo ?

**Comment by jiaoqingbo** [comment]
> `parser` directory

No other typo seems to be found in the parser directory

**Comment by jiaoqingbo** [comment]
> Thank you for making a PR. Is this the last typo instance in this file or in this `parser` directory, @jiaoqingbo ?

No other typo seems to be found in the parser directory

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Pull request closed without merging**
