### PR TITLE
[SPARK-25179][PYTHON][DOCS] Document BinaryType support in Arrow conversion

### PR DESCRIPTION
**Pull request by HyukjinKwon**
## What changes were proposed in this pull request?

This PR targets to document binary type in "Apache Arrow in Spark".

## How was this patch tested?

Manually built the documentation and checked.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @BryanCutler and @gatorsmile.

**Review by dongjoon-hyun — APPROVED** [review]

**Review by gatorsmile — COMMENTED** [review]
LGTM

Merged to master/2.4

**Comment by HyukjinKwon** [comment]
Thanks, @dongjoon-hyun and @gatorsmile

**Comment by BryanCutler** [comment]
Thanks @HyukjinKwon , looks good!

**Pull request closed without merging**
