### PR TITLE
[SPARK-36335][DOCS] Remove Local-cluster mode reference (and add a missing period)

### PR DESCRIPTION
**Pull request by yutoacts**
### What changes were proposed in this pull request?

Remove local-cluster mode reference from configuration.md and add a missing period to submitting-application.md.

### Why are the changes needed?

It's a test-only mode for developers so we should remove it to avoid confusing users.
I'll add local-cluster mode documentation to developer tools page (https://spark.apache.org/developer-tools.html) soon.

### Does this PR introduce _any_ user-facing change?

Yes, docs changed.

### How was this patch tested?

`SKIP_API=1 bundle exec jekyll build`
remove
add

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
ok to test

**Comment by HyukjinKwon** [comment]
Can you enable GitHub Actions in your forked repo? See also https://github.com/apache/spark/pull/33568/checks?check_run_id=3188766327

**Comment by yutoacts** [comment]
I actually did it but still fails... I contacted GitHub a while ago and hope it will solve this.

**Comment by HyukjinKwon** [comment]
I'll leave it to @tgravescs and just follow his advice.

**Comment by yutoacts** [comment]
OK, thanks for your help.

**Comment by yutoacts** [comment]
It ended up as https://github.com/apache/spark/pull/33537.

**Pull request closed without merging**
