### PR TITLE
[SPARK-8063][SPARKR] Spark master URL conflict between MASTER env variable and --master command line option.

### PR DESCRIPTION
**Pull request by sun-rui**

### CODE REVIEW

**Comment by shivaram** [comment]
hmm -- so just to confirm, does the `MASTER` env variable get read by `spark-submit` automatically ?

**Comment by andrewor14** [comment]
@shivaram yes it does: https://github.com/apache/spark/blob/2c4d550eda0e6f33d2d575825c3faef4c9217067/core/src/main/scala/org/apache/spark/deploy/SparkSubmitArguments.scala#L138

**Comment by andrewor14** [comment]
I am not familiar with the R code but I believe this change means we delegate the master check to `spark-submit`, where the precedence order is and should be `--master` > `MASTER`. If this is what this patch does then this LGTM, though @shivaram should verify.

**Comment by shivaram** [comment]
Thanks @andrewor14 - LGTM. Merging this.

**Pull request closed without merging**
