### PR TITLE
[SPARK-21131][GraphX]  Fix batch gradient bug in SVDPlusPlus

### PR DESCRIPTION
**Pull request by lxmly**
## What changes were proposed in this pull request?
I think the mode of batch gradient in Graphx SVDPlusPlus is incorrect. The changes of this pull request are as blow:
* Use the mean of batch gradient instead of the sum of batch gradient.
* When calculating the residual of each rating during iteration,  the pred value shouldn't be limit in (minVal, maxVal)
* The method "calculateIterationRMSE" is added to show the iteration effect clearly.

## How was this patch tested?
I test SVDPlusPlus locally by using movielens-100k dataset. The RMSE of origin SVDPlusPlus can't get converged and looks completely wrong.  The RMSE of new SVDPlusPlus gets converged correctly. 

@srowen  @ankurdave

### CODE REVIEW

**Comment by daniellaah** [comment]
I also tested the SVDPlusPlus on movielens-100k dataset. The algorithm just diverged. And the mse on the dataset gets 2.14748364347152E9.  
I tested @lxmly 's code as well, it works but I don't know whether it is proper to use the 'mean gradient'.  
@lxmly How do you get the conclusion 'using mean gradient'? Any reference? Thanks in advance.

**Comment by daniellaah** [comment]
Try another dataset and you will find the algorithm works well.

**Comment by srowen** [comment]
This seems to have a lot of superfluous change. Why is the mean gradient better? It is different just by a scale factor. Also disagree about not clipping predictions but that's separate

**Comment by lxmly** [comment]
which dataset? @daniellaah

**Comment by daniellaah** [comment]
@lxmly deleted. I test on some private data, it turns out that the algorithm works well ... accidentally. 😂

**Comment by lxmly** [comment]
I think this is the process of parallel batch gradient,  and averaging the sum of gradient is necessary.  

I also find the update process of y_j factor  is incorrect. For each rating of the user, all of y_j factors associated with items in the user's action history should be updated, but graphx svd++ only updates y_j factor of the item in the rating. 

$$
\forall j \in N(u):    
y_j \leftarrow y_j + \gamma \cdot (e_{ui}\cdot|N(u)|^{-\frac{1}{2}}\cdot q_i - \lambda \cdot y_j) 
$$

@srowen

**Comment by desperadoxx** [comment]
I also met this problem. The rmse doesn't get converged on some common dataset, including movielens.
At least, it should not be clipped by maxValue and minValue when computing the gradient, which will change loss function to non-convex, but the original is convex.

**Pull request closed without merging**
