### PR TITLE
[Minor] Replace all occurrences of None: Option[X] with Option.empty[X]

### PR DESCRIPTION
**Pull request by techaddict**
## What changes were proposed in this pull request?

Replace all occurrences of `None: Option[X]` with `Option.empty[X]`
## How was this patch tested?

Exisiting Tests

### CODE REVIEW

**Comment by rxin** [comment]
Is this actually an improvement? Might be too trivial to bother doing.

**Comment by techaddict** [comment]
No performance benefits but improves readability.

**Comment by rxin** [comment]
I'm actually not sure this is better in readability in either, since most people know about None/Some/Option, but not necessarily Option.empty (I didn't know about this before your pr).

**Comment by markhamstra** [comment]
Yeah, I wouldn't bother.  The way this PR does it is arguably better because it can be done consistently across all collections:
```scala
val l0 = List.empty[String]
val s0 = Set.empty[Int]
val o0 = Option.empty[Byte]
```
...but it's pretty trivial, and I don't buy the readability argument.

**Comment by srowen** [comment]
I know this is bikeshedding, but I very slightly prefer this change. Casting is uglier than using the 'right' method. I do understand "empty" is slightly less familiar.

**Comment by rxin** [comment]
@srowen it wasn't really casting here. It's just an explicit type definition.

**Comment by srowen** [comment]
The effect for source and readability is that of a cast; yes it is not a call to asInstanceOf. I do not feel strongly though this would have been the righter way to write this code.

**Comment by rxin** [comment]
Let me just merge this to save some time debating. Merging in master/2.0.

**Pull request closed without merging**
