### PR TITLE
[SPARK-15474][SQL]ORC data source fails to write and read back empty dataframe

### PR DESCRIPTION
**Pull request by sbcd90**
## What changes were proposed in this pull request?

Currently ORC data source fails to write and read empty data.
This PR provides a fix for this issue.
## How was this patch tested?

unit tests

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
@sbcd90 I think we will need a test to make sure this fixes the issue and other changes in the future do not break this change.

**Comment by sbcd90** [comment]
Hello @HyukjinKwon , I have added a testcase now. Please review.

**Comment by HyukjinKwon** [comment]
Hi @sbcd90 I am not a committer but I just left a comment because I like your PR. Let me add some more comments which I think might be changed.

**Comment by HyukjinKwon** [comment]
@sbcd90 I just read this JIRA [SPARK-8501](https://issues.apache.org/jira/browse/SPARK-8501) to figure out why it was disabled and tried to manually test this. 

To cut it short, it seems there is a "bug" for writing schema for empty ORC files. When it is empty, it seems it does not write schema (whereas Parquet does). Would there be any way to keep the schema even if the data is empty?

**Comment by sbcd90** [comment]
@HyukjinKwon, this PR exactly fixes that issue. If you test this PR with the sample code you provided in the JIRA ticket

```
val conf = new SparkConf().setAppName("TestApp16").setMaster("local")
  val sc = new SparkContext(conf)
  val sqlContext = new SQLContext(sc)

  val path = new File("check.orc")

  val df = sqlContext.range(10).limit(0)
  df.write.format("orc").save(path.getCanonicalPath)
```
you would find the empty schema being kept. I believe thats the only way to fix this issue.

**Comment by HyukjinKwon** [comment]
Ah, I think he meant this below:

- Parquet

```scala
val emptyDf = spark.range(10).limit(0).toDF()
emptyDf.write
 .format("parquet")
  .save(path.getCanonicalPath)

val copyEmptyDf = spark.read
  .format("parquet")
  .load(path.getCanonicalPath)

copyEmptyDf.printSchema()
```

```
root
 |-- id: long (nullable = true)
```

- ORC (with this PR)

```scala
val emptyDf = spark.range(10).limit(0).toDF()
emptyDf.write
 .format("orc")
  .save(path.getCanonicalPath)

val copyEmptyDf = spark.read
  .format("orc")
  .load(path.getCanonicalPath)

copyEmptyDf.printSchema()
```

```
root
```

**Comment by sbcd90** [comment]
Hello @HyukjinKwon , I think it is an ORC issue. There is a final call to ORC api & feel that the issue should be fixed in ORC.

```
new OrcOutputFormat().getRecordWriter(
      new Path(path, filename).getFileSystem(conf),
      conf.asInstanceOf[JobConf],
      new Path(path, filename).toString,
      Reporter.NULL
    ).asInstanceOf[RecordWriter[NullWritable, Writable]]
```

Do you have any different suggestions?

**Comment by HyukjinKwon** [comment]
@sbcd90 I currently can't think of other alternatives and it seems that's why it has not been enabled again.

**Comment by sbcd90** [comment]
@HyukjinKwon , closing this PR for now.

**Comment by nchammas** [comment]
The discussion on [ORC-152](https://issues.apache.org/jira/browse/ORC-152) suggests that this is an issue with Spark's DataFrame writer for ORC, not with ORC itself.

If you have evidence that this is not the case, it would be good to post it directly on ORC-152 so we can get input from people on that project.

**Comment by omalley** [comment]
Ok, I see the problem. Hive's OrcInputFormat has that property, because it was getting the schema from the ObjectInspector, which only came with the values. When I get a chance, let me look at what would be required to have you guys use the ORC project APIs directly.

**Pull request closed without merging**
