### PR TITLE
[MINOR][SQL] Convert `UnresolvedException` to an internal error

### PR DESCRIPTION
**Pull request by MaxGekk**
### What changes were proposed in this pull request?
In the PR, I propose to change the parent class of `UnresolvedException` from `AnalysisException` to `SparkException` with the error class `INTERNAL_ERROR`. If an user observes the error, this is definitely a bug in the compiler.

### Why are the changes needed?
To unify all Spark exceptions, and assign an error class. So, this should improve user experience with Spark SQL.

### Does this PR introduce _any_ user-facing change?
No, users shouldn't face to the error in regular cases.

### How was this patch tested?
By existing GAs.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by MaxGekk** [comment]
@srielau Could you take a look at the PR, please.

**Review by srielau — APPROVED** [review]

**Comment by MaxGekk** [comment]
Merging to master. Thank you, @srielau for review.

**Review by dongjoon-hyun — COMMENTED** [review]
Although CIs didn't complain. I believe this change might need more reviews or JIRA ID, @MaxGekk .

Let me ping around in order to give an enough heads-up.

cc @cloud-fan , @HyukjinKwon , @wangyum , @yaooqinn , @LuciferYang , @panbingkun

**Comment by cloud-fan** [comment]
Yea it's better to have a JIRA ticket for it.

**Comment by LuciferYang** [comment]
> Yea it's better to have a JIRA ticket for it.

+1

**Pull request closed without merging**
