### PR TITLE
[SPARK-8278] Remove deprecated JsonRDD functionality

### PR DESCRIPTION
**Pull request by NathanHowell**

### CODE REVIEW

**Comment by srowen** [comment]
I'm commenting without knowing the specifics here, but in general, do you really want to delete functionality deprecated for release X in release X+1? that's the least you can do, and may make sense, but is it urgent to remove this?

**Comment by NathanHowell** [comment]
It's an internal class, not part of the public API.

**Comment by rxin** [comment]
Let's wait a little bit  before we completely remove it. Usually we wait for 2 releases (i.e. in this case it'd be 1.6).

**Comment by NathanHowell** [comment]
We had an earlier discussion about removing it in 1.5, so I was following up. I'm fine leaving it in for another release.

**Comment by rxin** [comment]
(or we can wait until the end of 1.5 -- if nobody complains at all about the new implementation, we can remove it)

**Comment by rxin** [comment]
@NathanHowell can we close this one for now? we can reopen / revisit it in late July.

**Comment by NathanHowell** [comment]
Yep.

**Pull request closed without merging**
