### PR TITLE
[SPARK-37415][PYTHON][ML] Inline type hints for pyspark.ml.util

### PR DESCRIPTION
**Pull request by zero323**
### What changes were proposed in this pull request?

This PR migrates type `pyspark.ml.util` annotations from stub file to inline type hints.

### Why are the changes needed?

Part of ongoing migration of type hints.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by zero323** [comment]
This is just a rough draft ‒ I'll revisit it once SPARK-37397 (and revise it to address any possible issues detected during parallel work on SPARK-37416).

**Review by HyukjinKwon — APPROVED** [review]

**Comment by zero323** [comment]
Thanks for the review @HyukjinKwon! I am still working on this one (there was an issue with some of the `Generic` positions, that caused MRO failures) and won't make it final until I have time to finalize `ml.wrapper` ‒  because we have crazy inheritance hierarchies with a lot of abstract things, making small changes tends to escalate all over the place (`ml.wrapper`, which is not big by itself, might require changes in stubs for all `ml` modules 😰, because of the abstract `_things` exposed to type checkers)

**Comment by zero323** [comment]
Run the test run with #35399 and both seem to work well together.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by zero323** [comment]
Merged into master.

Thanks!

**Pull request closed without merging**
