### PR TITLE
adding yarn module in pom

### PR DESCRIPTION
**Pull request by narendrasfo**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)
(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Comment by srowen** [comment]
This is definitely not what we want to do. It's enabled by a profile. Can you close this? please see http://spark.apache.org/contributing.html too

**Comment by vanzin** [comment]
@narendrasfo this is not correct. The yarn module has moved, see the code I posted in the bug you filed. Please close this.

**Comment by narendrasfo** [comment]
closing the  SPARK-18770

**Comment by rxin** [comment]
@narendrasfo can you close the pull request as well?

**Pull request closed without merging**
