### PR TITLE
[SPARK-14284][ML] KMeansSummary deprecating size; adding clusterSizes

### PR DESCRIPTION
**Pull request by shallys**
## What changes were proposed in this pull request?

KMeansSummary class : deprecated size and added clusterSizes

### CODE REVIEW

**Comment by yanboliang** [comment]
@shallys We can rename ```size``` to ```clusterSizes``` directly, because Spark 2.0 has not release so we will not make any break change. Meanwhile, you should also change the call in [SparkRWrapper](https://github.com/apache/spark/blob/master/mllib/src/main/scala/org/apache/spark/ml/r/SparkRWrappers.scala#L109).

**Comment by jkbradley** [comment]
add to whitelist

**Comment by shallys** [comment]
@yanboliang I just made the changes as you suggested.  Please take a look.

**Comment by yanboliang** [comment]
@shallys Because #12039 has been merged, could you update your PR to resolve the conflicts?

**Comment by shallys** [comment]
@yanboliang Updated the PR. Please take a look.

**Comment by jkbradley** [comment]
LGTM
I'll test once before merging.

**Comment by jkbradley** [comment]
@shallys Could you please remove the "WIP" tag from the PR title?

**Comment by shallys** [comment]
@jkbradley Removed the WIP tag.

**Comment by jkbradley** [comment]
LGTM
Merging with master
Thanks!

**Pull request closed without merging**
