### PR TITLE
[SPARK-9780][Streaming][Kafka] prevent NPE if KafkaRDD instantiation …

### PR DESCRIPTION
**Pull request by koeninger**
…fails

### CODE REVIEW

**Comment by tdas** [comment]
LGTM. Merging this to master and 1.5. Thanks!

**Comment by shyamsalimkumar** [comment]
I get the same NPE issue in `Spark 1.4.1` also. I'm not sure what's wrong (yet) as my spark streaming job was running fine printing out `Array[Byte]` data, but after I added a custom decoder (Avro to my class `Swipe`) it keeps spitting the NPE error (`consumer` is `null`). Any hints on what could be the root cause?

`val swipes = KafkaUtils.createDirectStream[Array[Byte], Array[Byte], DefaultDecoder, DefaultDecoder](ssc, kafkaParams, topics)` works, but 
`val swipes = KafkaUtils.createDirectStream[Array[Byte], Swipe, DefaultDecoder, SwipeDecoder](ssc, kafkaParams, topics)` doesn't. In that aspect the NPE is sorta misleading (maybe).

**Comment by koeninger** [comment]
KafkaRDD attempts to instantiate the value decoder right before connecting
the consumer:

    val valueDecoder = classTag[T].runtimeClass.getConstructor(classOf[
VerifiableProperties])

      .newInstance(kc.config.props)

      .asInstanceOf[Decoder[V]]

    val consumer = connectLeader


Something's wrong with your SwipeDecoder

**Comment by shyamsalimkumar** [comment]
Yes... I know. :smile: I had forgotten to accept `props: VerifiableProperties` in it. Silly me. But I still think that the error thrown is misleading (unless of course you know the above).

**Comment by koeninger** [comment]
This PR has already been merged to suppress the NPE when someone messes up
instantiation....

**Pull request closed without merging**
