### PR TITLE
[SPARK-41408][BUILD] Upgrade scala-maven-plugin to 4.8.0

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr aims upgrade scala-maven-plugin to 4.8.0

### Why are the changes needed?
This version upgrade zinc to 1.8.0 and inlcude some bug fix, the all change from 4.7.2 as follows:

- https://github.com/davidB/scala-maven-plugin/compare/4.7.2...4.8.0

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass GitHub Actions

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @steveloughran FYI

**Comment by LuciferYang** [comment]
@steveloughran How can we test your scenario? The compilation of Java 11 and Java 17 in GA Task is run using Maven

**Comment by srowen** [comment]
Seems fine; does this actually update zinc?

**Comment by LuciferYang** [comment]
https://github.com/davidB/scala-maven-plugin/pull/655

I think so. If I understand wrong, please correct me

**Comment by srowen** [comment]
We run zinc separately so may not matter, but it's fine either way

**Comment by LuciferYang** [comment]
https://github.com/apache/spark/pull/31647

scala-maven-plugin 4.x already integrate the Zinc to enable the incremental compiler, it should not be separately now?

**Comment by steveloughran** [comment]
> How can we test your scenario? The compilation of Java 11 and Java 17 in GA Task is run using Maven

do a local build of hadoop trunk and then build against that
```
hadoop.version=3.4.0-SNAPSHOT
```

if the nightlys are building, you could try them
```
hadoop.version=3.4.0-SNAPSHOT -Psnapshots-and-staging
```

**Comment by LuciferYang** [comment]
@HyukjinKwon @srowen @steveloughran In order to not  block this pr, I open another one to investigate the issue mentioned in the dev list : maven build spark master with hadoop 3.4.0-SNAPSHOT

https://github.com/apache/spark/pull/38974

**Comment by LuciferYang** [comment]
@steveloughran maven build spark with hadoop 3.4.0-SNAPSHOT failed not related to `scala-maven-plugin`, after add the following 2 test dependencies to `sql/core` as https://github.com/apache/spark/pull/38974 , compilation can succeed

```
    <dependency>
      <groupId>org.bouncycastle</groupId>
      <artifactId>bcprov-jdk15on</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.bouncycastle</groupId>
      <artifactId>bcpkix-jdk15on</artifactId>
      <scope>test</scope>
    </dependency>
```

@steveloughran Is there any change about hadoop 3.4.0 test dependencies? I am not sure why this dependency needs to be added to `sql/core` module now. But according to the description of the `yarn` module, these two dependencies should only be used by `MiniYARNCluster`?

**Comment by srowen** [comment]
Merged to master

**Comment by steveloughran** [comment]
I think MiniHDFSCluster also needs it, and given that -test jars don't propagate transitive dependencies, that might be the cause.

looking at the yarn imports of bouncycastle jars, its had a test dependency since 2019 (YARN-5309) but maybe some dependency change of an imported module (I'm thinking: hdfs) means that more classes need it -and that has triggered this problem.

Odd way of failure though -it's as if the maven plugin left out a declaration.

**Comment by LuciferYang** [comment]
> I think MiniHDFSCluster also needs it, and given that -test jars don't propagate transitive dependencies, that might be the cause.
> 
> looking at the yarn imports of bouncycastle jars, its had a test dependency since 2019 (YARN-5309) but maybe some dependency change of an imported module (I'm thinking: hdfs) means that more classes need it -and that has triggered this problem.
> 
> Odd way of failure though -it's as if the maven plugin left out a declaration.

If necessary, we can consider merge https://github.com/apache/spark/pull/38974

**Pull request closed without merging**
