### PR TITLE
[SPARK-18333] [SQL] Revert hacks in parquet and orc reader to support case insensitive resolution

### PR DESCRIPTION
**Pull request by ericl**
## What changes were proposed in this pull request?

These are no longer needed after https://issues.apache.org/jira/browse/SPARK-17183

cc @cloud-fan 

## How was this patch tested?

Existing parquet and orc tests.

### CODE REVIEW

**Comment by ericl** [comment]
jenkins retest this please

**Comment by cloud-fan** [comment]
LGTM, can you also point out which PR added this hack? thanks.

**Comment by ericl** [comment]
The hacks were added in https://github.com/apache/spark/pull/14690

**Comment by cloud-fan** [comment]
LGTM

**Comment by cloud-fan** [comment]
merging to master/2.1

**Pull request closed without merging**
