### PR TITLE
[SPARK-10640] History server fails to parse TaskCommitDenied

### PR DESCRIPTION
**Pull request by andrewor14**
... simply because the code is missing!

### CODE REVIEW

**Comment by tgravescs** [comment]
thanks, hadn't had a chance to finish this. I'll try out your changes on my bad history file to make sure it works.

**Comment by andrewor14** [comment]
Great, thanks Tom.

**Comment by tgravescs** [comment]
well your change fixes that error and it now displays the file on the screen. But it does throw an exception. I think its due to the missing fields in the history file for the job id.

org.json4s.package$MappingException: Did not find value which can be converted into int

**Comment by tgravescs** [comment]
+1.

**Comment by andrewor14** [comment]
I see, because in your event log we only logged the name `TaskCommitDenied` but not the job ID and other details. That makes sense.

**Comment by tgravescs** [comment]
Yeah and actually I want to do one more verification to make sure the rest of the history file is useful.  Unfortunately my network connection is slow that its a huge history file.

**Comment by tgravescs** [comment]
ok it finally loaded. So the history UI for that task reports its still RUNNING since it got the error parsing it.  I guess that is ok.  Ideally it would still show end and the task commit error even if it couldn't report the jod id, etc.    Is that something we could do fairly easily?

**Comment by andrewor14** [comment]
Hm, unfortunately it appears that we missed two whole minor versions (1.3.0 and 1.4.0). I wonder if we should add some backward compatible handling for those versions. AFAIK they're not really consumed for any other purpose downstream so we can just put `-1` as default values for all of them. What do you think about this @vanzin?

**Comment by tgravescs** [comment]
Also since those values are missing it also causes duration and completed time to not show up. Makes it difficult for users to debug there job.  This particular job I was looking ran for 7 hours so I can't just rerun to get the data again.

**Comment by vanzin** [comment]
The approach looks ok to me if it works (seems this only affects jobs with speculative execution on?).

**Comment by andrewor14** [comment]
Yes I believe so. @tgravescs can you give it another try?

**Comment by tgravescs** [comment]
yes it only happens with speculation.   I'll try it out.

**Comment by tgravescs** [comment]
That is much better, it reports completed times and duration for the entire application those tasks show up as failed with comment: TaskCommitDenied (Driver denied task commit) for job: -1, partition: -1, attempt: -1  

+1, Thanks Andrew!

**Comment by andrewor14** [comment]
Alright, merging into master 1.5. Thanks everyone.

**Pull request closed without merging**
