### PR TITLE
[SPARK-44197][BUILD] Upgrade Hadoop to 3.3.6

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to upgrade Apache Hadoop dependency to 3.3.6.

### Why are the changes needed?

To bring the latest bug fixes for Apache Spark 3.5.0 and use the artifacts with SBOM
- NEWS: https://hadoop.apache.org/release/3.3.6.html
> It contains 117 bug fixes, improvements and enhancements since 3.3.5.

- DOCS: https://hadoop.apache.org/docs/r3.3.6/index.html

- CHANGELOG:  https://hadoop.apache.org/docs/r3.3.6/hadoop-project-dist/hadoop-common/release/3.3.6/CHANGELOG.3.3.6.html
 
### Does this PR introduce _any_ user-facing change?

This is a dependency change.

### How was this patch tested?

Pass the CIs.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
All tests passed.

Screenshot 2023-06-26 at 3 42 39 PM

**Comment by dongjoon-hyun** [comment]
Could you review this PR, @sunchao ?

**Review by sunchao — APPROVED** [review]
LGTM (pending CI)

**Comment by dongjoon-hyun** [comment]
Thank you, @sunchao . The CI passed already~
Let me merge this~ :)

**Comment by LuciferYang** [comment]
late LGTM

**Pull request closed without merging**
