### PR TITLE
[SPARK-50098][PYTHON][FOLLOWUP] Update `_minimum_googleapis_common_protos_version` in `setup.py`

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This is a follow-up of
- #48638 

### Why are the changes needed?

To be consistent.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the CIs.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Could you review this follow-up, @viirya ?

**Comment by dongjoon-hyun** [comment]
All tests passed.

**Review by viirya — APPROVED** [review]

**Comment by viirya** [comment]
Thanks @dongjoon-hyun

**Comment by dongjoon-hyun** [comment]
Thank you, @viirya !

**Comment by dongjoon-hyun** [comment]
This is only a follow-up to make it sure the enforcement logic. The dependency was updated and tested already in the previous PR. Let me merge this~

**Pull request closed without merging**
