### PR TITLE
[SPARK-44944][INFRA] Auto grant contributor role to first-time contributors

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

This PR improves the experience while merging PR from first-time contributors by creating their contributor role at the ASF Spark Jira side.

### Why are the changes needed?

First-time contributors can fail the merging progress as they are not assignable to issues.

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

locally verified 

```python
>>> try:
...     assign_issue(asf_jira, issue.key, assignee.name)
... except Exception as e:
...     if (
...         e.__class__.__name__ == "JIRAError"
...         and ("'%s' cannot be assigned" % assignee.name)
...         in getattr(e, "response").text
...     ):
...         continue_maybe(
...             "User '%s' cannot be assigned, add to contributors role and try again?"
...             % assignee.name
...         )
...         grant_contributor_role(assignee.name, asf_jira)
...         assign_issue(asf_jira, issue.key, assignee.name)
...     else:
...         raise e
...

User 'liuxun' cannot be assigned, add to contributors role and try again? (y/n): y
True
```

### Was this patch authored or co-authored using generative AI tooling?

no

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]
Yeah, I like this.

**Review by zhengruifeng — APPROVED** [review]

**Comment by zhengruifeng** [comment]
thanks, merged to master

**Review by dongjoon-hyun — COMMENTED** [review]
Thank you, @yaooqinn .

**Comment by yaooqinn** [comment]
Thank you @HyukjinKwon @zhengruifeng and @dongjoon-hyun

**Pull request closed without merging**
