### PR TITLE
[SPARK-26449][PYTHON] Add transform method to DataFrame API

### PR DESCRIPTION
**Pull request by Hellsen83**
## What changes were proposed in this pull request?

Added .transform() method to Python DataFrame API to be in sync with Scala API.

## How was this patch tested?

Addition has been tested manually.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
ok to test

**Comment by HyukjinKwon** [comment]
cc @srowen too

**Comment by srowen** [comment]
We should leave a reference to the original PR: https://github.com/apache/spark/pull/23414
I wonder if it's worth showing chaining at least two functions to highlight the point of the function? No big deal.

**Comment by Hellsen83** [comment]
> We should leave a reference to the original PR: #23414
> 

agreed

> I wonder if it's worth showing chaining at least two functions to highlight the point of the function?

Fine with me.

 No big deal but the doctest needs fixing anyway:
> 
> ```
> **********************************************************************
> File "/home/jenkins/workspace/SparkPullRequestBuilder/python/pyspark/sql/dataframe.py", line 2055, in pyspark.sql.dataframe.DataFrame.transform
> Failed example:
>     df = spark.createDataFrame([Row(a=170.1, b=75.0)])
> Exception raised:
>     Traceback (most recent call last):
>       File "/usr/lib64/pypy-2.5.1/lib-python/2.7/doctest.py", line 1315, in __run
>         compileflags, 1) in test.globs
>       File "<doctest pyspark.sql.dataframe.DataFrame.transform[0]>", line 1, in <module>
>         df = spark.createDataFrame([Row(a=170.1, b=75.0)])
>     NameError: global name 'Row' is not defined
> **********************************************************************
> File "/home/jenkins/workspace/SparkPullRequestBuilder/python/pyspark/sql/dataframe.py", line 2058, in pyspark.sql.dataframe.DataFrame.transform
> Failed example:
>     df.transform(cast_all_to_int).collect()
> Exception raised:
>     Traceback (most recent call last):
>       File "/usr/lib64/pypy-2.5.1/lib-python/2.7/doctest.py", line 1315, in __run
>         compileflags, 1) in test.globs
>       File "<doctest pyspark.sql.dataframe.DataFrame.transform[2]>", line 1, in <module>
>         df.transform(cast_all_to_int).collect()
>       File "/home/jenkins/workspace/SparkPullRequestBuilder/python/pyspark/sql/dataframe.py", line 2061, in transform
>         result = func(self)
>       File "<doctest pyspark.sql.dataframe.DataFrame.transform[1]>", line 2, in cast_all_to_int
>         return input_df.select([col(c_name).cast("int") for c_name in input_df.columns])
>     NameError: global name 'col' is not defined
> **********************************************************************
> ```
> No need to use `Row` anyway. Maybe best to copy the example in the other PR.

Needs an import of col anyway for this example to work..

I will provide a chained example that will pass the doctest later this weekend.

**Comment by Hellsen83** [comment]
>>> from pyspark.sql.functions import col
        >>> df = spark.createDataFrame([(1, 1.0), (2, 2.)], ["int", "float"])
        >>> def cast_all_to_int(input_df):
        ...     return input_df.select([col(col_name).cast("int") for col_name in input_df.columns])
        >>> def sort_columns_asc(input_df):
        ...     return input_df.select(*sorted(input_df.columns))
        >>> df.transform(cast_all_to_int).transform(sort_columns_asc).show()
        +-----+---+
        |float|int|
        +-----+---+
        |    1|  1|
        |    2|  2|
        +-----+---+

`
Thoughts?!

**Review by srowen — APPROVED** [review]

**Comment by Hellsen83** [comment]
> **[Test build #4573 has finished](https://amplab.cs.berkeley.edu/jenkins/job/NewSparkPullRequestBuilder/4573/testReport)** for PR 23877 at commit [`b3cc604`](https://github.com/apache/spark/commit/b3cc604d6f27f9009487b0c72539a7e7839c099b).
> 
> * This patch **fails PySpark unit tests**.
> * This patch merges cleanly.
> * This patch adds no public classes.

Sorry, I did not commit these changes, I just posted this as a proposal. Not on my machine right now, will commit this evening. Sorry for confusion.

**Comment by Hellsen83** [comment]
cool.

**Comment by Hellsen83** [comment]
I guess this is ready to approve, hopefully merge & certainly close, @srowen :)

**Comment by srowen** [comment]
Merged to master

**Comment by srowen** [comment]
Merged to master

**Comment by MrPowers** [comment]
Thanks for getting this merged in!  Looks like [my blog post](https://medium.com/@mrpowers/chaining-custom-pyspark-transformations-4f38a8c7ae55) motivated [this feature request](https://issues.apache.org/jira/browse/SPARK-26449).

Can we provide an example that shows how to structure transformations that take arguments?  How does this look?

```python
from pyspark.sql.functions import col, lit

df = spark.createDataFrame([(1, 1.0), (2, 2.)], ["int", "float"])

def with_funny(word):
    def inner(df):
        return df.withColumn("funny", lit(word))
    return inner

def cast_all_to_int(input_df):
    return input_df.select([col(col_name).cast("int") for col_name in input_df.columns])

df.transform(cast_all_to_int).transform(with_funny("bumfuzzle")).show()
```

```
+---+-----+---------+
|int|float|    funny|
+---+-----+---------+
|  1|    1|bumfuzzle|
|  2|    2|bumfuzzle|
+---+-----+---------+
```

@HyukjinKwon - do you think this is the best way to structure the `with_funny` code?  [This blog post](https://mungingdata.com/pyspark/chaining-dataframe-transformations/) explains how to structure this transformation with functools.partial and cytoolz as well.  Looking forward to figuring out the best way to write PySpark transformations and sharing it with the community!

**Comment by Hellsen83** [comment]
Hello @MrPowers ,
you are right, this is in fact motivated by your excellent blog post - thank you so much for that!
From my experience - i.e. bringing this style of wrting PySpark transformations into a heterogeneous group of roughly 15 devs/data scientists - the following was used most frequently and people new to the game were able to pick this up quickly:

```
def my_logical_name(arg1: type1, arg2: type2):
    """My Docstring Style goes here
    
    :arg1: does something
    :arg2: does something_else
    :returns: a dataframe that was first somethinged and then something_elsed
    """
    def _(df: DataFrame):
        return df.do_something(arg1).do_something_else(arg2)
    return _

def test_my_logical_name_returns_none_if_args_are_equal():
    ..
    result_df: DataFrame = df.transform(my_logical_name(arg1, arg1))
    ..
```

So I am right with ya, but propose "\_" as the inner function name and the above mentioned docstring placement. Main reasons for "_":
1) the amount of visual noise should be lowered as much as possible (when writing many transformations and things do get more complicated, this pays off)
2) if you name the inner function, people _will_ give custom names to it. this goes against 1) and uniform code, as names will start to vary.

**Comment by MrPowers** [comment]
@Hellsen83 - I updated [the blog post](https://mungingdata.com/pyspark/chaining-dataframe-transformations/) to add your suggested convention of using `_` as the inner function name.  Thanks for helping the PySpark community!!

**Comment by MrPowers** [comment]
@hoffrocket pointed out that this can also be accomplished with an inner lambda (to avoid having to name the inner function):

```python
def with_funny(something_funny):
    return lambda df: (
        df.withColumn("funny1", F.lit(something_funny))
    )
```

**Pull request closed without merging**
