### PR TITLE
[SPARK-10272][Pyspark][MLLib] Added @since tags to pyspark.mllib.evaluation

### PR DESCRIPTION
**Pull request by noel-smith**
Duplicated the @since decorator from pyspark.sql into pyspark (also tweaked to handle functions without docstrings).

Added @since to public methods + "versionadded::" to classes (derived from the git file history in pyspark).

Note - I added also the tags to MultilabelMetrics even though it isn't declared as public in the **all** statement... if that's incorrect - I'll remove.

### CODE REVIEW

**Comment by mengxr** [comment]
add to whitelist

**Comment by mengxr** [comment]
test this please

**Comment by mengxr** [comment]
@yu-iskw Could you help review this PR? Thanks!

**Comment by yu-iskw** [comment]
LGTM

**Comment by mengxr** [comment]
Merged into master. Thanks!

**Pull request closed without merging**
