### PR TITLE
[SPARK-21704][DOC] Add the description of 'sbin/stop-slave.sh' in spark-standalone.html.

### PR DESCRIPTION
**Pull request by guoxiaolongzte**
## What changes were proposed in this pull request?

1.Add the description of 'sbin/stop-slave.sh' in spark-standalone.html.
`sbin/stop-slave.sh` - Stops a slave instance on the machine the script is executed on.

2.The description of 'sbin/start-slaves.sh' is not accurate.Should be modified as follows:
Starts all slave instances on each machine specified in the `conf/slaves` file.

## How was this patch tested?

manual tests

Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Comment by srowen** [comment]
@guoxiaolongzte this stuff is too minor to make JIRAs and separate PRs for. I'd refocus yourself on bigger changes

**Comment by guoxiaolongzte** [comment]
Do you mean only PR?No need to submit JIRA?

**Comment by srowen** [comment]
No JIRA, and, consider whether this is worth opening a PR for.
The docs were actually correct. The start-slave and stop-slave scripts aren't really something the end user calls.

**Comment by guoxiaolongzte** [comment]
Okay.

**Pull request closed without merging**
