### PR TITLE
[SPARK-42059][BUILD] Update ORC to 1.8.2

### PR DESCRIPTION
**Pull request by williamhyun**
### What changes were proposed in this pull request?
This PR aims to update ORC to 1.8.2.

### Why are the changes needed?
This will bring the latest bug fixes and changes including an SBOM.
- https://github.com/apache/orc/releases/tag/v1.8.2

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass the CIs.

### CODE REVIEW

**Comment by williamhyun** [comment]
cc: @dongjoon-hyun

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you always, @williamhyun !

**Review by huaxingao — APPROVED** [review]

**Comment by huaxingao** [comment]
+1 Thanks @williamhyun

**Comment by dongjoon-hyun** [comment]
Merged to master for Apache Spark 3.4. Thank you, @williamhyun and @huaxingao .

**Pull request closed without merging**
