### PR TITLE
[SPARK-3561] Initial commit to provide pluggable strategy to facilitate access to nat...

### PR DESCRIPTION
**Pull request by olegz**
Initial commit to provide pluggable strategy to facilitate access to native Hadoop resources

Added HadoopExecutionContext trait and its default implementation DefaultHadoopExecutionContext
Modified SparkContext to instantiate and delegate to the instance of HadoopExecutionContext where appropriate

Changed HadoopExecutionContext to JobExecutionContext
Changed DefaultHadoopExecutionContext to DefaultExecutionContext
Name changes are due to the fact that when Spark executes outside of Hadoop having Hadoop in the name woudl be confusing
Added initial documentation and tests

polished scaladoc

annotated JobExecutionContext with @DeveloperAPI

eliminated TaskScheduler null checks in favor of NoOpTaskScheduler
to be used in cases where execution of Spark DAG is delegated to an external execution environment

added execution-context check to SparkSubmit

Added recognition of execution-context to SparkContext
updated spark-class script to recognize when 'execution-context:' is used

polished merge

changed annotations from @DeveloperApi to @Experimental as part of the PR suggestion

externalized persist and unpersist operations

added classpath hooks to spark-class

### CODE REVIEW

**Comment by maidh91** [comment]
Is this patch still working? when will Spark finish to verify it?

**Comment by nchammas** [comment]
> when will Spark finish to verify it?

@maidh91 - Please follow the discussion on the JIRA issue to get this kind of information: [SPARK-3561](https://issues.apache.org/jira/browse/SPARK-3561)

As for whether this patch still works, it hasn't been updated in a while and currently has a merge conflict, so probably not.

**Comment by srowen** [comment]
Can you close this PR? it's no longer mergeable and looks borked at this point.

**Comment by olegz** [comment]
Well, I am waiting in the resolution of https://issues.apache.org/jira/browse/SPARK-3561 since it has recently been updated to "In Progress". I would rather update the PR, to make it mergable unless there is a different proposed approach which I would like to read about.

**Comment by srowen** [comment]
The update was just made by automated tools, not any person. As far as I can tell the proposal in the JIRA is rejected. The problem with this PR is that not only does it not merge but for some reason it has a lot of other commits in it and touches 820 files. Maybe a full rebase would fix it, not sure. But it can be closed in any event; it will stay here for posterity anyway.

**Comment by olegz** [comment]
Sean
I am not sure I understand the "rejected" part, since no rejection has been issued (-1) in the JIRA.

**Comment by srowen** [comment]
Although I'm pretty sure that's the resolution, sure, leave it open if you like. But this PR can't be merged and seems to have gotten messed up somehow; I'm narrowly asking you to not leave it both in that state and open. Close it, or resolve the conflicts / merge history stuff.

**Comment by maidh91** [comment]
Yes, please fix existing conflicts and merge it. It will be perfect if you can merge with the latest version.

**Comment by srowen** [comment]
@maidh91 this is not going to be merged. I'm suggesting it be closed actually.

**Comment by maidh91** [comment]
I really hope that this patch will become official part in Spark. I think @srowen is right that we should clean all messy things and open again later. Spark 1.4.0 is just released and Spark-Submit 2015 is happened today and they introduce many new features. It is pretty pity that this patch is not one of them.

**Comment by olegz** [comment]
@srowen 
I’d suggest to move this discussion to JIRA and see if we get a disposition there on the overall proposal and idea? The PR may not be in the mergable state and while GitHub is appropriate medium to discuss any technical issues, current discussion seems to go beyond that, hence my suggestion on moving it.

**Comment by srowen** [comment]
That's fine, but in the name of trying to clean up stale PRs, would you mind closing this PR? it's not mergeable and seems corrupted anyway. You can reopen another PR if you really want to.

**Pull request closed without merging**
