### PR TITLE
[SPARK-15297] [SQL] Fix Set -V Command

### PR DESCRIPTION
**Pull request by gatorsmile**
#### What changes were proposed in this pull request?

The command `SET -v` always outputs the default values even if we set the parameter. This behavior is incorrect. Instead, if users override it, we should output the user-specified value.

In addition, the output schema of `SET -v` is wrong. We should use the column `value` instead of `default` for the parameter value.

This PR is to fix the above two issues. 
#### How was this patch tested?

Added a test case.

### CODE REVIEW

**Comment by gatorsmile** [comment]
@andrewor14 @yhuai @rxin Could you please review this PR? Thanks!

**Comment by gatorsmile** [comment]
ping @hvanhovell @cloud-fan Do you have a bandwidth to review this simple fix? Thanks!

**Comment by gatorsmile** [comment]
retest this please

**Comment by cloud-fan** [comment]
LGTM, merging to master and 2.0!

**Comment by gatorsmile** [comment]
Thanks!

**Pull request closed without merging**
