### PR TITLE
[SPARK-41895][SS][UI] Add tests for streaming UI with RocksDB backend

### PR DESCRIPTION
**Pull request by gengliangwang**
### What changes were proposed in this pull request?

Add tests for streaming UI with RocksDB backend

### Why are the changes needed?

Better test coverage when live UI with RocksDB backend is enabled.
### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

GA tests

### CODE REVIEW

**Comment by gengliangwang** [comment]
cc @LuciferYang

**Comment by gengliangwang** [comment]
I am rerunning tests since https://github.com/apache/spark/pull/39416 is merged.

**Comment by LuciferYang** [comment]
```
13:45:13.014 ERROR org.apache.spark.sql.execution.streaming.StreamingQueryListenerBus: Listener StreamingQueryStatusListener threw an exception
java.lang.NullPointerException
	at org.apache.spark.status.protobuf.StoreTypes$StreamingQueryData$Builder.setName(StoreTypes.java:57107)
	at org.apache.spark.status.protobuf.sql.StreamingQueryDataSerializer.serialize(StreamingQueryDataSerializer.scala:33)
	at org.apache.spark.status.protobuf.KVStoreProtobufSerializer.serialize(KVStoreProtobufSerializer.scala:29)
	at org.apache.spark.util.kvstore.RocksDB.write(RocksDB.java:188)
	at org.apache.spark.status.ElementTrackingStore.write(ElementTrackingStore.scala:123)
	at org.apache.spark.status.ElementTrackingStore.write(ElementTrackingStore.scala:127)
	at org.apache.spark.sql.streaming.ui.StreamingQueryStatusListener.onQueryStarted(StreamingQueryStatusListener.scala:82)
	at org.apache.spark.sql.execution.streaming.StreamingQueryListenerBus.doPostEvent(StreamingQueryListenerBus.scala:131)
	at org.apache.spark.sql.execution.streaming.StreamingQueryListenerBus.doPostEvent(StreamingQueryListenerBus.scala:43)
	at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:117)
	at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:101)
	at org.apache.spark.sql.execution.streaming.StreamingQueryListenerBus.postToAll(StreamingQueryListenerBus.scala:88)
	at org.apache.spark.sql.execution.streaming.StreamingQueryListenerBus.post(StreamingQueryListenerBus.scala:77)
	at org.apache.spark.sql.streaming.StreamingQueryManager.postListenerEvent(StreamingQueryManager.scala:231)
	at org.apache.spark.sql.execution.streaming.StreamExecution.postEvent(StreamExecution.scala:402)
	at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:278)
	at org.apache.spark.sql.execution.streaming.StreamExecution$$anon$1.run(StreamExecution.scala:207)
```

https://github.com/apache/spark/blob/99739ae068d6ad828ba3453af2a8c738ab37a3a8/sql/core/src/main/scala/org/apache/spark/status/protobuf/sql/StreamingQueryDataSerializer.scala#L33

`data.name` still needs to be protected to avoid NPE

**Review by LuciferYang — APPROVED** [review]
+1, LGTM

**Comment by gengliangwang** [comment]
Merging to master

**Review by dongjoon-hyun — COMMENTED** [review]
+1, LGTM.

**Review by dongjoon-hyun — COMMENTED** [review]
Hi, @gengliangwang .
This might cause test flakiness. I saw several failures in these days. I filed a JIRA, SPARK-41969 for flaky tests. Could you take a look at this, please?

Screen Shot 2023-01-10 at 12 53 45 PM

Also, cc @xinrong-meng as Apache Spark 3.4.0 release manager.

**Comment by gengliangwang** [comment]
@dongjoon-hyun yes I will try fixing it today

**Pull request closed without merging**
