### PR TITLE
[SPARK-27830][CORE][UI][2.4] Show Spark version at app lists of Spark History UI

### PR DESCRIPTION
**Pull request by liucht-inspur**
## What changes were proposed in this pull request?

This PR aims to show Spark version at application lists of Spark History UI for branch-2.4.
From the following, the first Version column is added. When the application has multiple attempts, this will show the first attempt's version number.
after:
image

### Why are the changes needed?
I modified the branch-2.4 in the same way as dongjoon-hyun did : #24694
Thank you for your modification @dongjoon-hyun 

## How was this patch tested?

Manually launch Spark history server and see the UI. Please use *Private New Window (Safari)* or *New Incognito Window (Chrome)* to avoid browser caching.

```
sbin/start-history-server.sh
```

### CODE REVIEW

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
Hi, @liucht-inspur . Thank you for making a PR, but there exist some issues here.
1. Apache Spark community has a policy for backporting. We don't backport an improvement patch.
2. As an original author of SPARK-27830, I must say that you should not delete the original authorship.
3. You should piggy-bag SPARK-31871 here silently.

**Comment by dongjoon-hyun** [comment]
I'll close this PR to prevent an accidental merge. We can discuss more on this PR.

**Comment by liucht-inspur** [comment]
Hi, @dongjoon-hyun . Thank you for your reminding.
Can I resubmit a new JIRA for this 2.4 release issue?

**Comment by dongjoon-hyun** [comment]
Sorry, but `branch-2.4` is not allowed to have a new improvement by the community backporting policy.

Apache Spark community will deliver bug fixes like security/correctness into `branch-2.4`, but `New Feature` and `Improvement` is out of the scope.

**Comment by dongjoon-hyun** [comment]
Could you try Apache Spark 3.0.0 instead? 
- `3.0.1` is also scheduled in a month.
- `3.1.0` is scheduled on December 2020 (this year)
https://spark.apache.org/versioning-policy.html

**Pull request closed without merging**
