### PR TITLE
[PySpark] Fix typo in comments in PySpark's udf() definition

### PR DESCRIPTION
**Pull request by rednaxelafx**
## What changes were proposed in this pull request?

Just a simple typo fix from `curcuiting` to `circuiting`.

## How was this patch tested?

N/A. This patch does not change any code behavior.

### CODE REVIEW

**Comment by srowen** [comment]
OK. Have a look for more typos while you're at it. We try to avoid whole PRs just to fix each one.

**Comment by rednaxelafx** [comment]
@srowen Thanks for your review! I'll have a look at other typos and update this PR later.

I was actually working on code around this place and thought I'd split out the typo fix to make it cleaner to review. Yes I totally agree it's a good idea to clean up more than one typo in a single PR.

**Comment by srowen** [comment]
You can just combine small-scale fixes to the surrounding code in the main PR then. I think that's fine.

**Comment by HyukjinKwon** [comment]
There's a same typo in `pandas_udf` too BTW.

**Comment by felixcheung** [comment]
let's get them fixed for 2.3?

**Comment by srowen** [comment]
Ping @rednaxelafx

**Comment by HyukjinKwon** [comment]
@rednaxelafx, can you fix the one in `pandas_udf` too? I'll just merge this.

**Comment by HyukjinKwon** [comment]
@rednaxelafx, I was fixing some codes around UDF. I included the current typo in https://github.com/apache/spark/pull/20288. I think you could close this one.

**Comment by rednaxelafx** [comment]
@HyukjinKwon cool! Thanks a lot for including it! Closing this one now.

**Pull request closed without merging**
