### PR TITLE
update the deprecated CountMinSketchMonoid function to TopPctCMS function

### PR DESCRIPTION
**Pull request by caikehe**
http://twitter.github.io/algebird/index.html#com.twitter.algebird.legacy.CountMinSketchMonoid$
The CountMinSketchMonoid has been deprecated since 0.8.1. Newer code should use TopPctCMS.monoid().

image

### CODE REVIEW

**Comment by srowen** [comment]
ok to test

**Comment by srowen** [comment]
We're on 0.8.1, so if it compiles, that seems OK

**Comment by caikehe** [comment]
package orange.fr.scalaTest

import com.twitter.algebird._
import com.twitter.algebird.CMSHasherImplicits._

import org.apache.spark.SparkConf
import org.apache.spark.SparkContext._
import org.apache.spark.storage.StorageLevel
import org.apache.spark.streaming.{Seconds, StreamingContext}
import org.apache.spark.streaming.twitter._

// scalastyle:off
/**
 * Illustrates the use of the Count-Min Sketch, from Twitter's Algebird library, to compute
 * windowed and global Top-K estimates of user IDs occurring in a Twitter stream.
 * <br>
 *   <strong>Note</strong> that since Algebird's implementation currently only supports Long inputs,
 *   the example operates on Long IDs. Once the implementation supports other inputs (such as String),
 *   the same approach could be used for computing popular topics for example.
 * <p>
 * <p>
 *   <a href=
 *   "http://highlyscalable.wordpress.com/2012/05/01/probabilistic-structures-web-analytics-data-mining/">
 *   This blog post</a> has a good overview of the Count-Min Sketch (CMS). The CMS is a data
 *   structure for approximate frequency estimation in data streams (e.g. Top-K elements, frequency
 *   of any given element, etc), that uses space sub-linear in the number of elements in the
 *   stream. Once elements are added to the CMS, the estimated count of an element can be computed,
 *   as well as "heavy-hitters" that occur more than a threshold percentage of the overall total
 *   count.
 * <p><p>
 *   Algebird's implementation is a monoid, so we can succinctly merge two CMS instances in the
 *   reduce operation.
 */
// scalastyle:on
object TwitterAlgebirdCMS {
  def main(args: Array[String]) {
    StreamingExamplesLogging.setStreamingLogLevels()

    val Array(consumerKey, consumerSecret, accessToken, accessTokenSecret) = args.take(4)
    // Set the system properties so that Twitter4j library used by twitter stream
    // can use them to generat OAuth credentials
    System.setProperty("twitter4j.oauth.consumerKey", consumerKey)
    System.setProperty("twitter4j.oauth.consumerSecret", consumerSecret)
    System.setProperty("twitter4j.oauth.accessToken", accessToken)
    System.setProperty("twitter4j.oauth.accessTokenSecret", accessTokenSecret)
    
    // CMS parameters
    val DELTA = 1E-3
    val EPS = 0.01
    val SEED = 1
    val PERC = 0.001
    // K highest frequency elements to take
    val TOPK = 10

    val filters = args.takeRight(args.length - 4)
    val sparkConf = new SparkConf().setAppName("TwitterAlgebirdCMS").setMaster("local[*]")
    val ssc = new StreamingContext(sparkConf, Seconds(10))
    val stream = TwitterUtils.createStream(ssc, None, filters, StorageLevel.MEMORY_ONLY_SER_2)

    val users = stream.map(status => status.getUser.getId)

    //val cms = new CountMinSketchMonoid(EPS, DELTA, SEED, PERC)
    val cms = TopPctCMS.monoid[Long](EPS, DELTA, SEED, PERC)
    var globalCMS = cms.zero
    val mm = new MapMonoid[Long, Int]()
    var globalExact = Map[Long, Int]()

    val approxTopUsers = users.mapPartitions(ids => {
      ids.map(id => cms.create(id))
    }).reduce(_ ++ _)

    val exactTopUsers = users.map(id => (id, 1))
      .reduceByKey((a, b) => a + b)

    approxTopUsers.foreachRDD(rdd => {
      if (rdd.count() != 0) {
        val partial = rdd.first()
        val partialTopK = partial.heavyHitters.map(id =>
          (id, partial.frequency(id).estimate)).toSeq.sortBy(_._2).reverse.slice(0, TOPK)
        globalCMS ++= partial
        val globalTopK = globalCMS.heavyHitters.map(id =>
          (id, globalCMS.frequency(id).estimate)).toSeq.sortBy(_._2).reverse.slice(0, TOPK)
        println("Approx heavy hitters at %2.2f%% threshold this batch: %s".format(PERC,
          partialTopK.mkString("[", ",", "]")))
        println("Approx heavy hitters at %2.2f%% threshold overall: %s".format(PERC,
          globalTopK.mkString("[", ",", "]")))
      }
    })

    exactTopUsers.foreachRDD(rdd => {
      if (rdd.count() != 0) {
        val partialMap = rdd.collect().toMap
        val partialTopK = rdd.map(
          {case (id, count) => (count, id)})
          .sortByKey(ascending = false).take(TOPK)
        globalExact = mm.plus(globalExact.toMap, partialMap)
        val globalTopK = globalExact.toSeq.sortBy(_._2).reverse.slice(0, TOPK)
        println("Exact heavy hitters this batch: %s".format(partialTopK.mkString("[", ",", "]")))
        println("Exact heavy hitters overall: %s".format(globalTopK.mkString("[", ",", "]")))
      }
    })

    ssc.start()
    ssc.awaitTermination()
  }
}

I test this code on my local machine it works, while you test it you should set the twitter anthentication part.

**Comment by srowen** [comment]
@caikehe It failed style tests actually:

```
Scalastyle checks failed at following occurrences:
[error] /home/jenkins/workspace/SparkPullRequestBuilder/examples/src/main/scala/org/apache/spark/examples/streaming/TwitterAlgebirdCMS.scala:71:4: Insert a space after the start of the comment
[error] (examples/compile:scalastyle) errors exist
[error] Total time: 6 s, completed Apr 22, 2015 3:09:11 AM
[error] /home/jenkins/workspace/SparkPullRequestBuilder/examples/src/main/scala/org/apache/spark/examples/streaming/TwitterAlgebirdCMS.scala:71:4: Insert a space after the start of the comment
[error] (examples/compile:scalastyle) errors exist
```

**Comment by caikehe** [comment]
Yes, or just add a space before the comment. Now it should work.

**Comment by caikehe** [comment]
@AmplabJenkins, I checked the build results, access rights to CI server needed? While it is mergeable.

**Comment by srowen** [comment]
Click the results above -- this does not compile.

```
[error] /home/jenkins/workspace/SparkPullRequestBuilder/examples/src/main/scala/org/apache/spark/examples/streaming/TwitterAlgebirdCMS.scala:21: object CMSHasherImplicits is not a member of package com.twitter.algebird
[error] import com.twitter.algebird.CMSHasherImplicits._
[error]                             ^
[error] /home/jenkins/workspace/SparkPullRequestBuilder/examples/src/main/scala/org/apache/spark/examples/streaming/TwitterAlgebirdCMS.scala:72: not found: value TopPctCMS
[error]     val cms = TopPctCMS.monoid[Long](EPS, DELTA, SEED, PERC)
[error]               ^
[error] /home/jenkins/workspace/SparkPullRequestBuilder/examples/src/main/scala/org/apache/spark/examples/streaming/TwitterAlgebirdCMS.scala:79: missing parameter type for expanded function ((x$1, x$2) => x$1.$plus$plus(x$2))
[error]     }).reduce(_ ++ _)
[error]               ^
```

**Comment by caikehe** [comment]
http://twitter.github.io/algebird/#com.twitter.algebird.CMSHasherImplicits$ 
http://mvnrepository.com/artifact/com.twitter/algebird-core_2.10
On the pom.xml file, it needs add the latest version:
 <dependency>
    	<groupId>com.twitter</groupId>
    	
    	<artifactId>algebird-core_2.10</artifactId>
    	<version>0.9.0</version>
  </dependency>

**Comment by srowen** [comment]
I think that's fine, since this is an example, though this is not related to SPARK-7056?

**Comment by caikehe** [comment]
SPARK-7056 is just a new commit, after updating the pom.xml file, the CMSHasherImplicits compatibility problem can be solved as well.

**Comment by srowen** [comment]
The changes look OK; Jenkins will double-check. I am still not sure what you mean about SPARK-7056, which is about the streaming write-ahead log. Typo?

**Comment by caikehe** [comment]
It means nothing, first I intend to update the pom.xml file and give it a new name [spark-7056], while it is a part of this pull request.

**Comment by srowen** [comment]
Normally we do make JIRAs for changes unless it would be pretty redundant with a simple, self-evident pull request. This is borderline. But SPARK-7056 is a real, unrelated JIRA: http://issues.apache.org/jira/browse/SPARK-7056  To avoid confusion: there is no JIRA associated with this pull request at the moment.

**Comment by caikehe** [comment]
It makes sense.

**Pull request closed without merging**
