### PR TITLE
[SPARK-26895][CORE] prepareSubmitEnvironment should be called within doAs for proxy users

### PR DESCRIPTION
**Pull request by abellina**
## What changes were proposed in this pull request?

`prepareSubmitEnvironment` performs globbing that will fail in the case where a proxy user (`--proxy-user`) doesn't have permission to the file. This is a bug also with 2.3, so we should backport, as currently you can't launch an application that for instance is passing a file under `--archives`, and that file is owned by the target user.

The solution is to call `prepareSubmitEnvironment` within a doAs context if proxying.

## How was this patch tested?

Manual tests running with `--proxy-user` and `--archives`, before and after, showing that the globbing is successful when the resource is owned by the target user.

I've looked at writing unit tests, but I am not sure I can do that cleanly (perhaps with a custom FileSystem). Open to ideas.

Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Comment by abellina** [comment]
@jerryshao pinging you as the feature was introduced here: https://github.com/apache/spark/pull/18235.

Also pinging reviewers @vanzin, @cloud-fan, jiangxb1987. Thanks in advance.

**Comment by abellina** [comment]
ok to test

**Comment by vanzin** [comment]
ok to test

**Comment by vanzin** [comment]
BTW your previous PR title was better. Describe the fix, not the problem.

**Comment by abellina** [comment]
@vanzin will update it. Thanks

**Comment by abellina** [comment]
Hmm, python tests failed. Not sure if related though. The tests point at the `/home/jenkins/workspace/SparkPullRequestBuilder/python/unit-tests.log` file, but I can't get to that from jenkins UI it seems (are all prs writing to the same file?). Is this a known issue? Can we move it to the artifacts?

From the error, it seems like the `shmutil.rmtree` function is trying to delete a directory, but there's likely another thread adding entries to a directory, so when it gets to `os.rmdir(path)` it blows up. I think the test should call `q.awaitTermination` after `q.stop`, before going on. I'll file a separate jira. 

`ERROR: test_query_manager_await_termination (pyspark.sql.tests.test_streaming.StreamingTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jenkins/workspace/SparkPullRequestBuilder/python/pyspark/sql/tests/test_streaming.py", line 259, in test_query_manager_await_termination
    shutil.rmtree(tmpPath)
  File "/home/anaconda/lib/python2.7/shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/home/anaconda/lib/python2.7/shutil.py", line 254, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/home/jenkins/workspace/SparkPullRequestBuilder/python/target/072153bd-f981-47be-bda2-e2b657a16f65/tmp4WGp7n'`

**Comment by abellina** [comment]
ok to test

**Comment by vanzin** [comment]
retest this please

**Comment by vanzin** [comment]
Merging to master.

**Pull request closed without merging**
