### PR TITLE
[SPARK-9335][Streaming][Tests]Make sure the test stream is deleted in KinesisBackedBlockRDDSuite

### PR DESCRIPTION
**Pull request by zsxwing**
KinesisBackedBlockRDDSuite should make sure delete the stream.

### CODE REVIEW

**Comment by zsxwing** [comment]
Will run #7661 again to clean up streams after this PR is merged.

**Comment by pwendell** [comment]
Thanks Ryan. This seems like an improvement. But my concern is overall whether we should have a test that depends on external services. What if Kinesis experiences an outage. Then all Spark PR's will start failing and our develoment will be blocked.

**Comment by zsxwing** [comment]
Now, Kinesis tests will run when the Kinesis project or the projects that it depends on (core, streaming) are modified. @JoshRosen Is it possible to run these Kinesis tests only when the Kinesis project is modified? If so, that would be great because I think it's hardly possible that the changes for core or streaming only fail the Kinesis tests.

**Comment by zsxwing** [comment]
@pwendell could you merge this one to avoid reaching the Kinesis limitation again and failing other PR builds? We can figure out how to fix this issue ultimately later.

**Comment by pwendell** [comment]
@zsxwing is this still failing PR's? In master the kinesis test is ignored.

**Comment by pwendell** [comment]
https://git-wip-us.apache.org/repos/asf?p=spark.git;a=blobdiff;f=extras/kinesis-asl/src/test/scala/org/apache/spark/streaming/kinesis/KinesisStreamSuite.scala;h=4992b041765e9e14a3417d0421124e3e91649ce5;hp=f9c952b9468bbc4c722150d762970c546d4c26e5;hb=19bcd6ab12bf355bc5d774905ec7fe3b5fc8e0e2;hpb=c84acd4aa4f8bee98baa550cd6801c797a8a7a25

**Comment by zsxwing** [comment]
KinesisBackedBlockRDDSuite is not ignored in master. So it's still possible to fail the PRs.

**Comment by tdas** [comment]
I am merging this fix.

**Pull request closed without merging**
