### PR TITLE
[SPARK-7570] [SQL] Ignores _temporary during partition discovery

### PR DESCRIPTION
**Pull request by liancheng**
[Review on Reviewable](https://reviewable.io/reviews/apache/spark/6091)

### CODE REVIEW

**Comment by yhuai** [comment]
Also cc @marmbrus

**Comment by marmbrus** [comment]
Should we be ignoring anything that starts with `_`?

**Comment by liancheng** [comment]
@marmbrus No, because there can be dynamic partition column names starting with `_` or `.` (e.g. `/path/to/_1=1/_2=2`).

**Comment by liancheng** [comment]
For now, we can check whether there is an `=` in the directory name. If the directory name

1. doesn't contain `=`, and
2. starts with `_` or `.`

then we can ignore them. But we may want to support customized partition discovery strategies later. For example, one possible strategy that some users had once asked for is not to encode partition column names in directory paths, (i.e., `path/1/2` instead of `path/a=1/b=2`). In that case, we simply can't have any assumption over the partition name, even using `_temporary` is not 100% safe.

**Comment by yhuai** [comment]
LGTM

**Pull request closed without merging**
