### PR TITLE
[SPARK-44537][BUILD] Upgrade kubernetes-client to 6.8.0

### LINKED ISSUE #5221: Empty kube config(root/.kube/config) file cause NPE
### Describe the bug

When I haven't manually disabled AutoConfig and there is an empty kubeconfig file present in the system, it leads to a NullPointerException in the `loadFromKubeConfig` method.

### Fabric8 Kubernetes Client version

other (please specify in additional context)

### Steps to reproduce

1 `echo '' > root/.kube/config`
2 `new ConfigBuilder()`
3 will get a NPE

### Expected behavior

no NPE

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.25.3@latest

### Environment

Linux

### Fabric8 Kubernetes Client Logs

```shell
`Caused by: java.lang.NullPointerException
	at io.fabric8.kubernetes.client.Config.loadFromKubeconfig(Config.java:703)
	at io.fabric8.kubernetes.client.Config.tryKubeConfig(Config.java:666)
	at io.fabric8.kubernetes.client.Config.autoConfigure(Config.java:286)
	at io.fabric8.kubernetes.client.Config.<init>(Config.java:251)
	at io.fabric8.kubernetes.client.Config.<init>(Config.java:242)
	at io.fabric8.kubernetes.client.ConfigBuilder.<init>(ConfigBuilder.java:10)
	at io.fabric8.kubernetes.client.ConfigBuilder.<init>(ConfigBuilder.java:7)
	at `
```

### Additional context

version is 6.6.0
Based on the following code, it seems that you are consciously trying to prevent empty kubeconfig files. However, you are currently only checking for null and not checking for an empty string "".
`
   if (kubeconfigContents == null) {
      return false;
    }
`

### LINKED ISSUE #5233: Support customizable expansion of crd cycles
To support issues like https://github.com/keycloak/keycloak/issues/12725 I think we need to extend the schemaswap behavior to include another parameter to control the depth at which the swap takes place.

### LINKED ISSUE #5262: Determine if all built-in collections should omit empty
Some collections are not marked as omitempty in their go classes: https://github.com/openshift/api/blob/master/apps/v1/types.go#L63

The java generator will not mark those fields for JsonInclude non_empty.

However our builders are opinionated about treating an empty and null collections the same (in some places), and users will end up with empty collections in their serialized forms without realizing it.  This is problematic for merge patches which treat the presense of an empty collection as a full replacement for the existing.

_Originally posted by @shawkins in https://github.com/fabric8io/kubernetes-client/issues/5222#issuecomment-1585653308_
           
We have two options to evaluate:

1. Just to be consistent make all collections default to non-empty (can be done in either the generator or the jsonschema2pojo logic).  This will of course open users up to #4606

2.  Try to modify the builder logic to differentaite between empty and null based upon the JsonInclude annotation - this seems like a tall order, and probably not viable.

### LINKED ISSUE #5281: ConcurrentModificationException accessing map in KubernetesCrudDispatcher
### Describe the bug

The MockWebServer occasionally crashes due to a `ConcurrentModificationException` caused from `KubernetesCrudDispatcher`. Here, this occurs from `handleWatch`, but appears to be possible elsewhere.

```
2023-06-23 13:54:00  okhttp3.mockwebserver.MockWebServer  SEVERE  MockWebServer[54552] connection from /127.0.0.1 crashed 
java.util.ConcurrentModificationException
	at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:756)
	at java.base/java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:788)
	at java.base/java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:786)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at io.fabric8.kubernetes.client.server.mock.KubernetesCrudDispatcher.lambda$handleWatch$6(KubernetesCrudDispatcher.java:298)
	at io.fabric8.kubernetes.client.server.mock.WatchEventsListener.onOpen(WatchEventsListener.java:63)
```

### Fabric8 Kubernetes Client version

6.7.2

### Steps to reproduce

Reproducible by running this test [1] in the Strimzi cluster operator test suite.

[1] https://github.com/strimzi/strimzi-kafka-operator/blob/016c98afdd0e173d3f07f523c73f9b9fdb418020/cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperatorWithPoolsMockTest.java#L621

### Expected behavior

No ConcurrentModificationException :-)

### Runtime

other (please specify in additional context)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

Linux

### Fabric8 Kubernetes Client Logs

_No response_

### Additional context

N/A for runtime/server version. This occurs in unit tests with the mock web server.

### LINKED ISSUE #5298: This change seems to be breaking my application when upgrading from 6.5.0 to 6.5.1?
This change seems to be breaking my application when upgrading from 6.5.0 to 6.5.1?

```
Exception in thread "main" io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://paas.***.be:443/apis/template.openshift.io/v1/namespaces/cbss-test-custom-jobs/templates. Message: templates.template.openshift.io is forbidden: User "system:anonymous" cannot list templates.template.openshift.io in the namespace "cbss-test-custom-jobs": no RBAC policy matched. Received status: Status(apiVersion=v1, code=403, details=StatusDetails(causes=[], group=template.openshift.io, kind=templates, name=null, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=templates.template.openshift.io is forbidden: User "system:anonymous" cannot list templates.template.openshift.io in the namespace "cbss-test-custom-jobs": no RBAC policy matched, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Forbidden, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.KubernetesClientException.copyAsCause(KubernetesClientException.java:238)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.waitForResult(OperationSupport.java:546)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.list(BaseOperation.java:424)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.list(BaseOperation.java:392)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.list(BaseOperation.java:93)
	at be.fgov.kszbcss.batch.client.OpenShiftJobClient.listJobTemplates(OpenShiftJobClient.java:61)
	at be.fgov.kszbcss.batch.cli.ListJobCommand.call(ListJobCommand.java:11)
	at be.fgov.kszbcss.batch.cli.ListJobCommand.main(ListJobCommand.java:27)
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://paas.***.be:443/apis/template.openshift.io/v1/namespaces/cbss-test-custom-jobs/templates. Message: templates.template.openshift.io is forbidden: User "system:anonymous" cannot list templates.template.openshift.io in the namespace "cbss-test-custom-jobs": no RBAC policy matched. Received status: Status(apiVersion=v1, code=403, details=StatusDetails(causes=[], group=template.openshift.io, kind=templates, name=null, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=templates.template.openshift.io is forbidden: User "system:anonymous" cannot list templates.template.openshift.io in the namespace "cbss-test-custom-jobs": no RBAC policy matched, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Forbidden, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.requestFailure(OperationSupport.java:701)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.requestFailure(OperationSupport.java:681)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.assertResponseCode(OperationSupport.java:630)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.lambda$handleResponse$0(OperationSupport.java:591)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at io.fabric8.kubernetes.client.http.StandardHttpClient.lambda$completeOrCancel$5(StandardHttpClient.java:120)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at io.fabric8.kubernetes.client.http.ByteArrayBodyHandler.onBodyDone(ByteArrayBodyHandler.java:52)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at io.fabric8.kubernetes.client.okhttp.OkHttpClientImpl$OkHttpAsyncBody.doConsume(OkHttpClientImpl.java:135)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

_Originally posted by @jpraet in https://github.com/fabric8io/kubernetes-client/issues/4970#issuecomment-1614671230_

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to upgrade kubernetes-client from 6.7.2 to 6.8.0.

### Why are the changes needed?
- The newest version brings some bug fixed & improvment, eg:
Fix https://github.com/fabric8io/kubernetes-client/issues/5221: Empty kube config file causes NPE
Fix https://github.com/fabric8io/kubernetes-client/issues/5281: Ensure the KubernetesCrudDispatcher's backing map is accessed w/lock
Fix https://github.com/fabric8io/kubernetes-client/issues/5298: Prevent requests needing authentication from causing a 403 response
Fix https://github.com/fabric8io/kubernetes-client/issues/5233: Generalized SchemaSwap to allow for cycle expansion
Fix https://github.com/fabric8io/kubernetes-client/issues/5262: all built-in collections will omit empty in their serialized form.

- The full release notes:
https://github.com/fabric8io/kubernetes-client/releases/

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA.

### CODE REVIEW

**Review by yaooqinn — APPROVED** [review]

**Review by yaooqinn — APPROVED** [review]

**Review by LuciferYang — APPROVED** [review]

**Review by HyukjinKwon — APPROVED** [review]
LGTM cc @dongjoon-hyun

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM (Pending CIs)

**Comment by dongjoon-hyun** [comment]
Could you re-trigger the CI once more, @panbingkun ?

**Comment by panbingkun** [comment]
> Could you re-trigger the CI once more, @panbingkun ?

Done.

**Comment by dongjoon-hyun** [comment]
Thank you, @panbingkun and all. Merged to master for Apache Spark 4.0.

**Pull request closed without merging**
