### PR TITLE
[SPARK-19429][PYTHON][SQL] Support slice arguments in Column.__getitem__

### PR DESCRIPTION
**Pull request by zero323**
## What changes were proposed in this pull request?

- Add support for `slice` arguments in `Column.__getitem__`.
- Remove obsolete `__getslice__` bindings.

## How was this patch tested?

Existing unit tests, additional tests covering `[]` with `slice`.

### CODE REVIEW

**Comment by zero323** [comment]
cc @holdenk

**Comment by holdenk** [comment]
Thanks for cleaning this up (yay removing deprecated functions from Python 2.0 :)).

**Comment by holdenk** [comment]
Merged to master, thanks! :)

**Comment by zero323** [comment]
Thanks @holdenk!

**Pull request closed without merging**
