### PR TITLE
[SPARK-12273][STREAMING] Make Spark Streaming web UI list Receivers in order

### PR DESCRIPTION
**Pull request by lw-lin**
Currently the Streaming web UI does NOT list Receivers in order; however, it seems more convenient for the users if Receivers are listed in order.

spark-12273

### CODE REVIEW

**Comment by zsxwing** [comment]
Jenkins, test this please.

**Comment by zsxwing** [comment]
LGTM pending tests

**Comment by zsxwing** [comment]
Merging to master. Thanks @proflin

**Comment by proflin** [comment]
Thanks @zsxwing for reviewing so soon :-)

**Pull request closed without merging**
