### PR TITLE
[SPARK-20021][PySpark] Miss backslash in python code

### PR DESCRIPTION
**Pull request by uncleGen**
## What changes were proposed in this pull request?

Add backslash for line continuation in python code.

## How was this patch tested?

Jenkins.

### CODE REVIEW

**Comment by uncleGen** [comment]
@felixcheung

**Review by felixcheung — APPROVED** [review]
LGTM

**Review by srowen — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
LGTM too.

**Comment by holdenk** [comment]
This looks reasonable, however there is a conflict, can you update this to the latest master?

**Comment by srowen** [comment]
Merged to master / 2.1

**Pull request closed without merging**
