### PR TITLE
[SPARK-7483] [MLlib] Upgrade Chill to 0.7.2 to support Kryo with FPGrowth

### PR DESCRIPTION
**Pull request by mark800**
It registers more Scala classes, including ListBuffer to support Kryo with FPGrowth. 

See https://github.com/twitter/chill/releases for Chill's change log.

### CODE REVIEW

**Comment by srowen** [comment]
0.7.3 is the latest. You need to update the dependencies file before this will pass.

Yes, good that you're looking at the release notes; what are the potential incompatible changes? what transitive deps does it change?

**Comment by srowen** [comment]
@mark800 are you following up on this?

**Comment by witgo** [comment]
@srowen  0.8.0  is the latest.

**Comment by mark800** [comment]
@srowen It passes all the test case with version 0.7.2

No transitive deps problem in checking chill's release notes.

**Comment by srowen** [comment]
Jenkins test this please

**Comment by srowen** [comment]
@mark800 let's go to 0.7.4 while we're here. I agree that it doesn't look like there are incompatible changes. But the tests would show that. Did you run them?

@witgo looks like 0.8 moves to kryo 3.x and I don't know if we can do that just now.

**Comment by srowen** [comment]
Yeah, this did not update dependencies. You'll have to do that as part of evaluating the change. This is what I meant above.

**Comment by witgo** [comment]
@srowen  I've run some simple spark  SQL cases, and it doesn't seem to have any issues.

**Comment by JoshRosen** [comment]
Ping @mark800, can you run `./dev/test-dependencies.sh --replace-manifest` and commit the result in order to get this patch past the build dependency test roadblock so we can run the rest of the tests?

**Comment by srowen** [comment]
@mark800 I'll take this over if you're not able to

**Comment by mark800** [comment]
@srowen Sorry for the late response, just done what you said.

**Comment by srowen** [comment]
@mark800 thanks though this still needs a rebase

**Comment by mark800** [comment]
@srowen  have rebased it.

**Comment by srowen** [comment]
Jenkins, test this please

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
