### PR TITLE
[SPARK-38338][BUILD][CORE] Remove test dependency on `hamcrest`

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
[SPARK-7081](https://issues.apache.org/jira/browse/SPARK-7081) introduces test dependency on `hamcrest` to extend assertion syntax.

But `hamcrest` is not widely used in Spark code, so this pr use `JUnit4` api to replace the corresponding assertion and remove  the dependence on `hamcrest`.

### Why are the changes needed?
Clean up weak dependencies.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA

### CODE REVIEW

**Comment by LuciferYang** [comment]
On the other hand, we can use `assertj` instead of `hamcrest`. It seems that `assertj`  is also popular and  it declares that it supports Java 17 after `3.21.0` at the same time:

- https://mvnrepository.com/artifact/org.assertj/assertj-core
- https://assertj.github.io/doc/#assertj-core-3-21-0-release-notes

cc @dongjoon-hyun @srowen

**Review by srowen — APPROVED** [review]
This is fine, let's stick with standard junit methods

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by LuciferYang** [comment]
thanks @srowen @HyukjinKwon

**Review by dongjoon-hyun — COMMENTED** [review]
+1, LGTM. Thank you, @LuciferYang and all!

**Pull request closed without merging**
