### PR TITLE
[SPARK-37032][SQL] Fix broken SQL syntax link in SQL Reference page

### PR DESCRIPTION
**Pull request by AngersZhuuuu**
### What changes were proposed in this pull request?
Current 4 link about SQL syntax under SQL Reference page is broken, this pr will fix the broken link. And re-link to the subsection under SQL Syntax doc

image

### Why are the changes needed?
Fix SQL Reference doc's broken link

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Not need

### CODE REVIEW

**Comment by AngersZhuuuu** [comment]
ping @dongjoon-hyun @HyukjinKwon @cloud-fan

**Comment by AngersZhuuuu** [comment]
Or link this for tab to subsection in sql-ref page?

**Comment by AngersZhuuuu** [comment]
> mind identifying which PR added this link, and which PR removed them?

This one https://github.com/apache/spark/pull/28360 add these, where removed may need ask @huaxingao

**Comment by HyukjinKwon** [comment]
hey, let's be clear on what you propose. Do you propose to remove these links because the pages are stale now? or did they not exist from the first place? For the latter case, we should fix the links instead of just removing it out.

**Comment by AngersZhuuuu** [comment]
> hey, let's be clear on what you propose. Do you propose to remove these links because the pages are stale now? or did they not exist from the first place? For the latter case, we should fix the links instead of just removing it out.

Yea, that's what I want to say in this https://github.com/apache/spark/pull/34307#issuecomment-945319507, will follow your comment.

**Comment by AngersZhuuuu** [comment]
> hey, let's be clear on what you propose. Do you propose to remove these links because the pages are stale now? or did they not exist from the first place? For the latter case, we should fix the links instead of just removing it out.

Done

**Review by cloud-fan — APPROVED** [review]

**Pull request closed without merging**
