### PR TITLE
[SPARK-6799] [SPARKR] Remove SparkR RDD examples, add dataframe examples

### PR DESCRIPTION
**Pull request by shivaram**
This PR also makes some of the DataFrame to RDD methods private as the RDD class is private in 1.4

cc @rxin @pwendell

### CODE REVIEW

**Comment by rxin** [comment]
LGTM.

**Comment by rxin** [comment]
Jenkins, retest this please.

**Comment by shivaram** [comment]
Jenkins, retest this please

**Comment by rxin** [comment]
Thanks. Merging in master & branch-1.4.

**Pull request closed without merging**
