### PR TITLE
SPARK-21158: Fix case sensitive of temp table/view name

### PR DESCRIPTION
**Pull request by cammachusa**
## What changes were proposed in this pull request?

Most changes have been made to SessionCatalog source file. Shouldn't convert table/view name into lowercase. The hash-table should always contain the exact input name of table. 

## How was this patch tested?

This patch wast tested around containLocalTable and containGlobalTable functions manually for case-sensitive and in-sensitive. They are very simple functions

Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Comment by cammachusa** [comment]
Sorry, It closed by mistake. Please help me to review this patch

**Comment by cammachusa** [comment]
OK to test
@cloud-fan , @gatorsmile , @andrewor14 can you help to review

**Comment by cloud-fan** [comment]
can you give a test case that fails without this patch?

BTW the `GlobalViewManager` documents explicitly:
```
Note that, the view name is always case-sensitive here, callers are responsible to format the
view name w.r.t. case-sensitive config.
```

**Comment by cammachusa** [comment]
Hi @cloud-fan , thanks for you quick response.
The failure test cases is very straight forward, and can be found in the ticket's description: https://issues.apache.org/jira/browse/SPARK-21158.
To summary: 
1. Set your spark sql to case insensitive: spark.sql("SET spark.sql.caseSensitive=false");
2. Create and temp table/view e.g. CameraAndModels
3. Then, check if your CameraAndModes exists in spark.catalog.listTables(). It will return false, while you know for sure that your table does exist.
=> The reason is the formatTable() in SessionCatalog.scala convert your table name to lowercase (btw, by default case sensitive is set to false)

To your second point:
The GlobalViewManager behaves just like the "LocalView", it also call the formatTable() before creating a view. Below is the code in SessionCatalog.scala for your references:
def createGlobalTempView(
      name: String,
      viewDefinition: LogicalPlan,
      overrideIfExists: Boolean): Unit = {
    globalTempViewManager.create(formatTableName(name), viewDefinition, overrideIfExists)
  }

I fixed this issue by simply return the table name itself from the formatTable(), without convert to lowercase. By doing this way, I don't have to clean up the callers which is erroneous (more than 20 references to this function). And provide a convenience way to check if a table exists, and do care about case sensitive at this point.

**Comment by cloud-fan** [comment]
is this a real issue? Ideally you should call `Catalog.tableExists` to check table/view existence. I think it's reasonable for `Catalog.listTables` to return lower-cased table names if case sensitive is off.

BTW, I also don't think this minor "improvement" worth such a big change.

**Comment by cammachusa** [comment]
@cloud-fan ,
1. catalog.tableExists is not always visible to callers (pls refer to the ticket's desc)
2. catalog.listTables: it depends on idea. Reporter, has a good reasons, and use case (pls refer to his ticket), and so I'm on her page.
3. Yes, it's a minor "improvement", but I don't see those are big change.
I'd like to have second reviewer, see what he think.
@gatorsmile , @andrewor14 , @rxin can you help to review this patch as well?
Thanks,

**Comment by gatorsmile** [comment]
I can see the issue, but adding all these APIs might not be worthy.

**Comment by cammachusa** [comment]
It's such a pain when you register your table's name as "MyTempTable", and later in your code you want to check if your table still exists by the same string "MyTempTable", but spark says "No". Now, you start figuring out what's going wrong with your code, and may spend a ton of time for it. And at the end, you realize it's Spark's bug, and that you need to convert it to lower case.

**Pull request closed without merging**
