### PR TITLE
[SPARK-9000][MLlib] Support generic item types in PrefixSpan

### PR DESCRIPTION
**Pull request by feynmanliang**
@mengxr Please review after #7818 merges and master is rebased.

Continues work by @rikima

Closes #7400

### CODE REVIEW

**Comment by srowen** [comment]
@feynmanliang is this really related to https://issues.apache.org/jira/browse/SPARK-9000 ?

**Comment by mengxr** [comment]
@feynmanliang 7400 is the PR number, not JIRA.

**Comment by feynmanliang** [comment]
@srowen @mengxr Thanks for the correction! Yes indeed.

**Comment by feynmanliang** [comment]
@mengxr do we plan to merge this before 1.5? Will need to rebase after #7818

**Comment by mengxr** [comment]
@feynmanliang Please rebase master.

**Comment by mengxr** [comment]
@feynmanliang Please also provide a unit test in Java.

**Comment by feynmanliang** [comment]
@mengxr Java compatibility might require API changes since `Item` type parameter will not be inferred in Java's call to:

```scala
  def run[Item, Basket <: JavaIterable[JavaIterable[Item]]](data: JavaRDD[Basket])
  : JavaRDD[(Iterable[Iterable[Item]], Long)] = {
    implicit val tag = fakeClassTag[Item]
    run[Item](data.rdd.map(_.asScala.toArray.map(_.asScala.toArray)))
      .map { case (pattern: Array[Array[Item]], count: Long) =>
        (pattern.map(_.toIterable).toIterable, count)
      }
      .toJavaRDD()
  }
```

and will instead return a `JavaRDD[(Iterable[Iterable[Object]], Long)]`. `FPGrowth` gets around this by defining an `FPGrowthModel[Item: ClassTag]` from which when Java users call `freqItemsets` the type of the item has been reified and they get the concrete type rather than `Object`.

The options I see are:
 1. Make the API change, introducing a `PrefixSpanModel` class to be returned by `run` with the reified `Item` type
 2. Return `Object` type to Java users, forcing them to cast into their desired item type.
 3. Hold off on generic items for 1.5, only supporting Ints. Generalizing to generic items should be backwards compatible, but we will probably run into this problem about reified Item types in the future.

**Comment by mengxr** [comment]
Okay. Let's merge this first. I will submit a PR for `PrefixSpanModel`.

**Pull request closed without merging**
