### PR TITLE
[SPARK-12625][SPARKR][SQL] replace R usage of Spark SQL deprecated API

### PR DESCRIPTION
**Pull request by felixcheung**
@rxin @davies @shivaram 
Took save mode from my PR #10480, and move everything to writer methods. This is related to PR #10559
- [x] it seems jsonRDD() is broken, need to investigate - this is not a public API though; will look into some more tonight. (fixed)

### CODE REVIEW

**Comment by rxin** [comment]
Thanks for submitting this.

FYI https://github.com/apache/spark/pull/10559 was merged, and R tests were disabled there so you should re-enable them.

**Comment by shivaram** [comment]
Thanks @felixcheung - LGTM if tests pass. Also @davies will be good if you can take a look.

**Comment by felixcheung** [comment]
I found another one after rebasing on #10559 
also fixed jsonRDD

**Comment by rxin** [comment]
Thanks - merging this in master.

**Pull request closed without merging**
