### PR TITLE
[SPARK-30234][SQL][DOCS][FOLOWUP] Update Documentation for ADD FILE and LIST FILE

### PR DESCRIPTION
**Pull request by iRakson**
### What changes were proposed in this pull request?
Updated the doc for ADD FILE and LIST FILE

### Why are the changes needed?
Due to changes made in #26863 , it is necessary to update ADD FILE and LIST FILE doc.

### Does this PR introduce any user-facing change?
Yeah. Document updated.

### How was this patch tested?
Manually

### CODE REVIEW

**Comment by iRakson** [comment]
@HyukjinKwon  @maropu

**Comment by HyukjinKwon** [comment]
ok to test

**Review by HyukjinKwon — APPROVED** [review]
looks okay.

**Review by maropu — APPROVED** [review]

**Comment by maropu** [comment]
Merged to master.

**Pull request closed without merging**
