### PR TITLE
[SPARK-1182][Docs] Sort the configuration parameters in configuration.md

### PR DESCRIPTION
**Pull request by brennonyork**
Sorts all configuration options present on the `configuration.md` page to ease readability.

### CODE REVIEW

**Comment by brennonyork** [comment]
okay to test

**Comment by srowen** [comment]
Don't worry about Jenkins tests; as I was just reminded a) Jenkins doesn't test the doc build and b) we'd have to manually check that it builds before merging. Assume it's OK for now.

I did a sanity check to find the props that were removed and added to make sure they match up:

```
< <code>spark.akka.failure-detector.threshold</code>
21c20
< <code>spark.dynamicAllocation.initialExecutors</code>
---
> <code>spark.dynamicAllocation.maxExecutors</code>
45a45,47
> <code>spark.mesos.coarse</code>
> <code>spark.mesos.executor.home</code>
> <code>spark.mesos.executor.memoryOverhead</code>
```

I think it's expected that the mesos ones are removed but what about the others?

**Comment by brennonyork** [comment]
Correct on the mesos configs (they're in `running-on-mesos.md` now). The others are actually in the file though :/ If you want to check manually (I just did for sanity) its easier to just check out [the .md file](https://github.com/brennonyork/spark/blob/SPARK-1182/docs/configuration.md). I will say that there *originally* were two sets of `spark.dynamicAllocation.maxExecutors` and no reference to `spark.dynamicAllocation.initialExecutors` so I renamed the `maxExecutors` option that described the `initialExecutors`. Just checked on the akka param and its in the new config so not sure why that showed up. Am I missing something?

**Comment by srowen** [comment]
That was just the result of a rough and ready `grep` so it could be wrong, yes. Thanks for double checking. Was any of the text changed, or just moved? if it was changed is there any easy way to summarize what changed to call attention to it for review?

Otherwise I think the big question here is just the merge conflict heck but I think we've generally agreed to do it.

**Comment by brennonyork** [comment]
No text was changed (from the merge from master) and everything was merely updated to account for the upstream changes (if there were any). That said I would assume there's no reason to review further for individual text, but that's coming from the guy who did a manual check to ensure each config option propagated correctly :) If there's any more to explicitly check out let me know and I'll be sure to get on it.

**Comment by rxin** [comment]
Thanks. I'm building this locally. Will merge it after I look through it.

**Comment by rxin** [comment]
Thanks. Merging this. I will leave a couple more comments that can be addressed in followup PRs.

**Pull request closed without merging**
