### PR TITLE
[SPARK-50444][BUILD] Upgrade dropwizard metrics to 4.2.29

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
This pr aims to upgrade `dropwizard metrics` from `4.2.28` to  `4.2.29`.

### Why are the changes needed?
v4.2.28 VS v.4.2.29
https://github.com/dropwizard/metrics/compare/v4.2.28...v4.2.29
https://github.com/dropwizard/metrics/pull/4540

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by panbingkun** [comment]
cc @LuciferYang @dongjoon-hyun

**Review by LuciferYang — APPROVED** [review]

**Comment by LuciferYang** [comment]
Merged into master. Thanks @panbingkun

**Review by dongjoon-hyun — COMMENTED** [review]
+1, LGTM.

**Comment by panbingkun** [comment]
> +1, LGTM.

Thank you, @dongjoon-hyun

**Pull request closed without merging**
