### PR TITLE
[SPARK-31510][R][BUILD] Set setwd in R documentation build

### PR DESCRIPTION
**Pull request by HyukjinKwon**
### What changes were proposed in this pull request?

Seems like in certain environment, it requires to set `setwd` as below:

```
> library(devtools); devtools::document(pkg="./pkg", roclets=c("rd"))
Loading required package: usethis
Error: Could not find package root, is your working directory inside a package?
```

see also https://stackoverflow.com/questions/52670051/how-to-troubleshoot-error-could-not-find-package-root and https://groups.google.com/forum/#!topic/rdevtools/79jjjdc_wjg

We can make up another story too. For example, if you set a specific directory in your `~/.Rprofile`, then R documentation build will fail as below:

```
echo 'setwd("~")' > ~/.Rprofile
sh R/create-rd.sh
``` 

```
Using R_SCRIPT_PATH = /usr/local/bin
Loading required package: usethis
Error: Can't find './pkg'.
Execution halted
```

This PR proposes to set the `setwd` explicitly so it does not get affected on the global environment.

### Why are the changes needed?

To make R dev env more independent.

### Does this PR introduce any user-facing change?

No, dev only.

### How was this patch tested?

Manually tested:

```bash
echo 'setwd("~")' > ~/.Rprofile
sh R/create-rd.sh
``` 

Before:

```
Using R_SCRIPT_PATH = /usr/local/bin
Loading required package: usethis
Error: Can't find './pkg'.
Execution halted
```

After:

```
Using R_SCRIPT_PATH = /usr/local/bin
Loading required package: usethis
Updating SparkR documentation
Loading SparkR
Creating a new generic function for ‘as.data.frame’ in package ‘SparkR’
Creating a new generic function for ‘colnames’ in package ‘SparkR’
Creating a new generic function for ‘colnames<-’ in package ‘SparkR’
Creating a new generic function for ‘cov’ in package ‘SparkR’
Creating a new generic function for ‘drop’ in package ‘SparkR’
Creating a new generic function for ‘na.omit’ in package ‘SparkR’
Creating a new generic function for ‘filter’ in package ‘SparkR’
Creating a new generic function for ‘intersect’ in package ‘SparkR’
...
```

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
retest this please

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Merged to master.

**Comment by dongjoon-hyun** [comment]
Ur, it seems there is anomaly at merging.
```
git fetch apache-github pull/28285/head:PR_TOOL_MERGE_PR_28285
fatal: couldn't find remote ref pull/28285/head
```

**Comment by dongjoon-hyun** [comment]
Could you merge this, @HyukjinKwon ?

**Comment by HyukjinKwon** [comment]
Sure, merged to master.

Thanks, @dongjoon-hyun!

**Comment by HyukjinKwon** [comment]
Huh .. ?  it's weird - I can't use my merge script either .. let me merge it by myself.

**Comment by HyukjinKwon** [comment]
I manually merged. Thanks @dongjoon-hyun!

**Comment by dongjoon-hyun** [comment]
Thank you! Ya. It was really weird.

**Comment by HyukjinKwon** [comment]
I also merged this into branch-3.0.

**Pull request closed without merging**
