### PR TITLE
[SPARK-40676][BUILD] Upgrade `scalatest` related test dependencies to 3.2.14

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr aims upgrade `scalatest` related test dependencies to 3.2.14:

- scalatest: upgrade scalatest to 3.2.14
- scalatestplus
   - scalacheck: upgrade to `scalacheck-1-17` 3.2.14.0
   - mockito: upgrade to `mockito-4-6` to 3.2.14.0
   - selenium: uprade to `selenium-4-4` to 3.2.14.0 and `selenium-java` to 4.4, `htmlunit-driver` to 3.64.0, `htmlunit` to 2.64.0

### Why are the changes needed?
The release notes as follows:

- scalatest:https://github.com/scalatest/scalatest/releases/tag/release-3.2.14
- scalatestplus
   - scalacheck-1-17: https://github.com/scalatest/scalatestplus-scalacheck/releases/tag/release-3.2.14.0-for-scalacheck-1.17
   - mockito-4-6: https://github.com/scalatest/scalatestplus-mockito/releases/tag/release-3.2.14.0-for-mockito-4.6
   - selenium-4-4: https://github.com/scalatest/scalatestplus-selenium/releases/tag/release-3.2.14.0-for-selenium-4.4

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?

- Pass GitHub Actions
- Manual test:

```
build/sbt -Dguava.version=31.1-jre -Dspark.test.webdriver.chrome.driver=/path/to/chromedriver -Dtest.default.exclude.tags="" -Phive -Phive-thriftserver "core/testOnly org.apache.spark.deploy.history.RocksDBBackendChromeUIHistoryServerSuite"
```

```
[info] RocksDBBackendChromeUIHistoryServerSuite:
Starting ChromeDriver 105.0.5195.52 (412c95e518836d8a7d97250d62b29c2ae6a26a85-refs/branch-heads/5195@{#853}) on port 58104
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
[info] - ajax rendered relative links are prefixed with uiRoot (spark.ui.proxyBase) (2 seconds, 216 milliseconds)
[info] Run completed in 7 seconds, 816 milliseconds.
[info] Total number of tests run: 1
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 1, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[success] Total time: 111 s (01:51), completed 2022-10-6 17:14:20
```

### CODE REVIEW

**Review by itholic — COMMENTED** [review]
Looks pretty good

**Review by HyukjinKwon — APPROVED** [review]

**Comment by LuciferYang** [comment]
https://github.com/LuciferYang/spark/actions/runs/3195804964

image

seems all passed, GA not update status

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by LuciferYang** [comment]
thanks @HyukjinKwon

**Pull request closed without merging**
