### PR TITLE
[SPARK-42820][BUILD] Update ORC to 1.8.3

### PR DESCRIPTION
**Pull request by williamhyun**
### What changes were proposed in this pull request?
This PR aims to update ORC to 1.8.3.

### Why are the changes needed?
This will bring the following bug fixes. 
- https://orc.apache.org/news/2023/03/15/ORC-1.8.3/

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass the CIs.

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @williamhyun .

**Review by yaooqinn — APPROVED** [review]

**Comment by yaooqinn** [comment]
LGTM, thanks @williamhyun @dongjoon-hyun

**Comment by dongjoon-hyun** [comment]
It seems that there is some GitHub Action setting issue on William side.

Actually, I was the release manager of Apache ORC 1.8.3 and tested this here in my repo.
- https://github.com/dongjoon-hyun/spark/pull/13

**Comment by dongjoon-hyun** [comment]
Let me merge this~ Merged to master/3.4.

**Pull request closed without merging**
