### PR TITLE
Add some clarifications to kafka usage with SSL

### PR DESCRIPTION
**Pull request by sortega**
## What changes were proposed in this pull request?

It's just a small documentation change to make more clear how to use SSL with kafka in some cases.

## How was this patch tested?

If I were read this version of the docs I've have saved some previous hours today.

### CODE REVIEW

**Comment by srowen** [comment]
Are you sure? it looks like the params are like `ssl.truststore.location` in https://docs.confluent.io/2.0.0/kafka/ssl.html for example. Where does the prefix come from? (I don't know this integration well)

**Comment by sortega** [comment]
It might have to do with the specific way in which I'm passing the arguments. This is my code:

```
df.write
      .format("kafka")
      .option("kafka.bootstrap.servers", bootstrapServers)
      .option("topic", topic)
      .options(optionsMap)
      .save()
```

**Comment by srowen** [comment]
@koeninger would you happen to know if this is correct?

**Comment by koeninger** [comment]
I'm a little confused - it looks like the PR is to change the documentation for the DStream kafka source, but the code example @sortega is giving is for df.write

KafkaUtils.createDirectStream is not expecting the keys in the kafkaParams argument to be prefixed with kafka, it's expecting them to match the org.apache.kafka consumer config documentation

**Pull request closed without merging**
