### PR TITLE
[SPARK-16419][SQL] EnsureRequirements adds extra Sort to already sorted cached table

### PR DESCRIPTION
**Pull request by MasterDDT**
## What changes were proposed in this pull request?

EnsureRequirements compares the required and given sort ordering, but uses Scala equals instead of a semantic equals, so column capitalization isn't considered, and also fails for a cached table. This results in a SortMergeJoin of a cached already-sorted table to add an extra sort.

Using semanticEquals to do the compare instead of scala equals on the two `Seq[SortOrder]`
## How was this patch tested?

Added 3 tests, the last 2 tests break without the fix.

### CODE REVIEW

**Comment by MasterDDT** [comment]
cc @JoshRosen @rxin 

I wasn't sure if the right fix here is that `Expression` should override `equals` and use `semanticEquals`, that would be a bigger change but I think would work. Also I noticed the `EquivalentExpressions` class but that seemed like it was only for codegen.

**Comment by hvanhovell** [comment]
Ok to test

**Comment by MasterDDT** [comment]
cc @hvanhovell

**Comment by hvanhovell** [comment]
@MasterDDT I am sorry that I didn't get back to you sooner. We have recently merged PR https://github.com/apache/spark/pull/14841 which implements similar functionality. Cloud you close this PR? Thank you for working on this!

**Comment by MasterDDT** [comment]
Closing this

**Pull request closed without merging**
