### PR TITLE
[SPARK-40429][SQL][3.3] Only set KeyGroupedPartitioning when the referenced column is in the output

### PR DESCRIPTION
**Pull request by huaxingao**
### What changes were proposed in this pull request?
back porting [PR](https://github.com/apache/spark/pull/37886) to 3.3.
Only set `KeyGroupedPartitioning` when the referenced column is in the output

### Why are the changes needed?
bug fixing

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
New test

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM (Pending CIs)

**Comment by dongjoon-hyun** [comment]
Thank you, @huaxingao .

**Comment by dongjoon-hyun** [comment]
Merged to branch-3.3.

**Comment by huaxingao** [comment]
Thanks a lot @dongjoon-hyun

**Pull request closed without merging**
