### PR TITLE
[SPARK-46286][DOCS] Document `spark.io.compression.zstd.bufferPool.enabled`

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

This PR adds spark.io.compression.zstd.bufferPool.enabled to documentation

### Why are the changes needed?

- Missing docs
- https://github.com/apache/spark/pull/31502#issuecomment-774792276 potential regression

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

doc build

### Was this patch authored or co-authored using generative AI tooling?

no

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @yaooqinn .

**Comment by dongjoon-hyun** [comment]
I merged this to master/3.5/3.4/3.3 as a release manager for Apache Spark 3.3.4.

**Comment by yaooqinn** [comment]
Thank you @dongjoon-hyun

**Review by beliefer — COMMENTED** [review]
Late LGTM.

**Pull request closed without merging**
