### PR TITLE
[SPARK-5193][SQL] Remove Spark SQL Java-specific API.

### PR DESCRIPTION
**Pull request by rxin**
After the following patches, the main (Scala) API is now usable for Java users directly.

https://github.com/apache/spark/pull/4056
https://github.com/apache/spark/pull/4054
https://github.com/apache/spark/pull/4049
https://github.com/apache/spark/pull/4030
https://github.com/apache/spark/pull/3965
https://github.com/apache/spark/pull/3958

### CODE REVIEW

**Comment by rxin** [comment]
cc @mengxr @jkbradley for mllib changes.

**Comment by mengxr** [comment]
MLlib changes look good to me:)

**Comment by jkbradley** [comment]
Same here; ML updates LGTM

**Comment by rxin** [comment]
Ok merging in master!

**Pull request closed without merging**
