### PR TITLE
[MINOR][DOC] Bump minikube minimum version to 1.7.3 in README.md

### PR DESCRIPTION
**Pull request by williamhyun**
### What changes were proposed in this pull request?
This PR updates the k8s `README.md` to be consistent with the Apache Spark website. 
- https://spark.apache.org/developer-tools.html

### Why are the changes needed?

The current minimum version in the `README.md` does not match the minimum version of the website. 

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
N/A

### CODE REVIEW

**Comment by williamhyun** [comment]
Could you review this, @attilapiros ?

**Review by dongjoon-hyun — APPROVED** [review]

**Comment by attilapiros** [comment]
The change is fine but this is also part of https://github.com/apache/spark/pull/31829
Where we are blocked by https://issues.apache.org/jira/browse/SPARK-34738.

**Comment by dongjoon-hyun** [comment]
Oh, in this case, could you close this PR, @williamhyun ? Sorry for asking this.

**Comment by dongjoon-hyun** [comment]
According to our discussion, I'll close this PR, @williamhyun . Thank you for making a PR.

**Pull request closed without merging**
