### PR TITLE
[MINOR][DOCS][TESTS] Fix PLAN_CHANGE_LOG_LEVEL document

### PR DESCRIPTION
**Pull request by viirya**
### What changes were proposed in this pull request?

`PLAN_CHANGE_LOG_LEVEL` config document is wrong. This is to fix it.

### Why are the changes needed?

Fix wrong doc.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Only doc change.

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
~+1, LGTM. Thank you, @viirya .~

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
Oh, please change the following test case, @viirya .
```scala
--- a/sql/catalyst/src/test/scala/org/apache/spark/sql/catalyst/optimizer/OptimizerLoggingSuite.scala
+++ b/sql/catalyst/src/test/scala/org/apache/spark/sql/catalyst/optimizer/OptimizerLoggingSuite.scala
@@ -100,7 +100,7 @@ class OptimizerLoggingSuite extends PlanTest {
         withSQLConf(SQLConf.PLAN_CHANGE_LOG_LEVEL.key -> level) {}
       }
       assert(error.getMessage.contains(
-        "Invalid value for 'spark.sql.optimizer.planChangeLog.level'."))
+        "Invalid value for 'spark.sql.planChangeLog.level'."))
     }
   }
```

**Comment by viirya** [comment]
> Oh, please change the following test case, @viirya .
> 
> ```scala
> --- a/sql/catalyst/src/test/scala/org/apache/spark/sql/catalyst/optimizer/OptimizerLoggingSuite.scala
> +++ b/sql/catalyst/src/test/scala/org/apache/spark/sql/catalyst/optimizer/OptimizerLoggingSuite.scala
> @@ -100,7 +100,7 @@ class OptimizerLoggingSuite extends PlanTest {
>          withSQLConf(SQLConf.PLAN_CHANGE_LOG_LEVEL.key -> level) {}
>        }
>        assert(error.getMessage.contains(
> -        "Invalid value for 'spark.sql.optimizer.planChangeLog.level'."))
> +        "Invalid value for 'spark.sql.planChangeLog.level'."))
>      }
>    }
> ```

Oops, fixed.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you!

**Review by maropu — APPROVED** [review]

**Comment by viirya** [comment]
Thanks @dongjoon-hyun @maropu

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master. Seems GitHub Actions build passed.

**Pull request closed without merging**
