### PR TITLE
[SPARK-8931] [SQL] Fallback to interpreted evaluation if failed to compile in codegen

### PR DESCRIPTION
**Pull request by davies**
Exception will not be catched during tests.

cc @marmbrus @rxin

### CODE REVIEW

**Comment by rxin** [comment]
LGTM.

**Comment by JoshRosen** [comment]
Maybe we should have a flag to disable this fallback in unit tests.

**Comment by rxin** [comment]
Actually that's a great idea.

**Comment by davies** [comment]
@JoshRosen I'm also thinking of that, but how can we easy turn it off for tests?

**Comment by rxin** [comment]
Is there some environmental variable or config variable we set for tests?

**Comment by JoshRosen** [comment]
There's a few ways that we can do this.  Rather than relying on environment variables, I'd consider making this into an undocumented SQLConf setting then using the test runner's system properties configuration to set that property in tests.  To see an example of this, look at the SparkConf setting that's used for controlling whether we throw exceptions if TaskMemoryManager detects a managed memory leak.

I think there's also a `spark.testing` System property / SparkConf that you might be able to use, but I'd grep the build configurations to confirm.

**Comment by davies** [comment]
@JoshRosen Thanks, updated.

**Pull request closed without merging**
