### PR TITLE
[SPARK-20064][PySpark] Bump the PySpark verison number to 2.2

### PR DESCRIPTION
**Pull request by rubenljanssen**
## What changes were proposed in this pull request?
PySpark version in version.py was lagging behind
Versioning is  in line with PEP 440: https://www.python.org/dev/peps/pep-0440/

## How was this patch tested?
Simply rebuild the project with existing tests

### CODE REVIEW

**Comment by holdenk** [comment]
Jenkins OK to test.

**Comment by holdenk** [comment]
Thanks for doing this @setjet & welcome to the Spark project :) This change looks good pending jenkins, if everything passes I'll merge it tonight.

For others looking at this PR wondering, make-distribution writes its own version number when building but this version number is used for development builds so keeping it up-to-date is useful.

**Comment by HyukjinKwon** [comment]
(it would be nicer if the title is fixed to indicate what it proposes in short)

**Comment by felixcheung** [comment]
please update the PR title

**Comment by setjet** [comment]
Done :)

**Comment by holdenk** [comment]
not sure why Jenkins hasn't triggured. Lets try Jenkins Test This Please

**Comment by felixcheung** [comment]
probably need someone who can command Jenkins
(I can't)

**Comment by holdenk** [comment]
In _theory_ I can command Jenkins (the pr-status board says "asked to test" rather than "admin needed" but idk).
Lets see if Jenkins retest this please does anything.

**Comment by srowen** [comment]
Merged to master

**Comment by holdenk** [comment]
Thanks for your first contribution to Spark :)

**Pull request closed without merging**
