### PR TITLE
[SPARK-41418][BUILD] Upgrade scala-maven-plugin from 4.7.2 to 4.8.0

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
This pr aims upgrade scala-maven-plugin from 4.7.2 to 4.8.0

### Why are the changes needed?
1.This version brings enhancements for `Incremental compile`(https://github.com/davidB/scala-maven-plugin/commit/69a45c04a520e4ce691758fd99591a740f6a2c88) and upgrade zinc to 1.8.0(https://github.com/davidB/scala-maven-plugin/commit/7d5d9bcdb3c9a1b9b6bef8077fe0c785182c1c18)

2.4.7.2 VS 4.8.0
https://github.com/davidB/scala-maven-plugin/compare/4.7.2...4.8.0

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA.

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Is there a chance to be related to the latest Hadoop compilation issue discussion on the dev mailing list, @panbingkun ?

**Comment by LuciferYang** [comment]
https://github.com/apache/spark/pull/38936 dup....

**Comment by dongjoon-hyun** [comment]
Ya, let me close this due to the duplication.

**Comment by panbingkun** [comment]
> #38936 dup....

Hmm... ok, close it.

**Pull request closed without merging**
