### PR TITLE
[SPARK-45696][CORE] Fix method tryCompleteWith in trait Promise is deprecated

### PR DESCRIPTION
**Pull request by zhaomin1423**
### What changes were proposed in this pull request?

replace scala.concurrent.Promise#tryCompleteWith with scala.concurrent.Promise#completeWith
### Why are the changes needed?

scala.concurrent.Promise#tryCompleteWith is deprecated since scala_2.13

### Does this PR introduce _any_ user-facing change?

No
### How was this patch tested?

pass actions

### Was this patch authored or co-authored using generative AI tooling?

No

### CODE REVIEW

**Comment by LuciferYang** [comment]
Is there only one relevant case?

**Review by LuciferYang — APPROVED** [review]
+1, LGTM if test pass

**Comment by zhaomin1423** [comment]
> Is there only one relevant case?

only found it.

**Comment by LuciferYang** [comment]
Can you make the GA operate normally? For example, by rebasing the code?

**Comment by LuciferYang** [comment]
@zhaomin1423 Can you rebase the code and make GitHub Actions run successfully?

**Comment by LuciferYang** [comment]
@zhaomin1423 can you rebase this one?

**Comment by zhaomin1423** [comment]
> @zhaomin1423 can you rebase this one?

Sorry for late reply, rebased it.

**Comment by LuciferYang** [comment]
Thanks @zhaomin1423

**Comment by LuciferYang** [comment]
Merged into master for Spark 4.0. Thanks @zhaomin1423

**Pull request closed without merging**
