### PR TITLE
[SPARK-32015][Core]Remote inheritable thread local variables after spark context is stopped

### PR DESCRIPTION
**Pull request by wankunde**
### What changes were proposed in this pull request?

Remove reference from `java.lang.ApplicationShutdownHooks` to `sparkContext` when the spark context is stopped.

### Why are the changes needed?

```java
  /** The active SparkSession for the current thread. */
  private val activeThreadSession = new InheritableThreadLocal[SparkSession]

  protected[spark] val localProperties = new InheritableThreadLocal[Properties]
```
There is still a reference(eg. `java.lang.ApplicationShutdownHooks` -> `org.apache.hive.common.util.ShutdownHookManager$1` -> `SparkContext`) to `sparkContext` after the spark context is stopped because `activeThreadSession` and `localProperties` variables are `InheritableThreadLocal` object , so the JVM cannot collect that. 

If we start and stop sparkSession several times, there will be a OOM exception.
image

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?

Local Tested.

### CODE REVIEW

**Comment by gatorsmile** [comment]
cc @Ngone51

**Comment by Ngone51** [comment]
@wankunde Do you have a way to reproduce the OOM?

**Comment by wankunde** [comment]
> @wankunde Do you have a way to reproduce the OOM?

Just setup and stop a few new SparkSessions, and use spark-sql to read tables managed by hive.

HiveCatalog will init a new child thread in `org.apache.hive.common.util.ShutdownHookManager`, which will have a reference to `SparkContext`(because SparkContext is a inheritable thread local variable)

```java
Runtime.getRuntime().addShutdownHook(
      new Thread() {
        @Override
        public void run() {
          MGR.shutdownInProgress.set(true);
          for (Runnable hook : getShutdownHooksInOrder()) {
            try {
              hook.run();
            } catch (Throwable ex) {
              LOG.warn("ShutdownHook '" + hook.getClass().getSimpleName() +
                       "' failed, " + ex.toString(), ex);
            }
          }
        }
      }
    );
```

Those sparkContexts cannot be garbage collected after stopped because there are references from java.lang.ApplicationShutdownHooks to those sparkContexts..

**Comment by wankunde** [comment]
A detailed trouble shooting description in Chinese :

https://blog.csdn.net/wankunde/article/details/106683680

**Comment by srowen** [comment]
Generally the whole application is done after the SparkContext is stopped, and you wouldn't continue after that. what's the use case?

**Comment by holdenk** [comment]
I could see this being useful in testing using something like `spark-testing-base`, you often want a fresh Spark context but not a whole fresh JVM.

**Comment by wankunde** [comment]
@srowen @holdenk 
Yes, a test is a use case. Another use case is to loop a user application containing sparkcontext.

**Comment by srowen** [comment]
OK, it's just quite a hacky approach here. Can we not clear these in a shutdown / close method?
Or worst case try soft references?

**Comment by wankunde** [comment]
Hi, @srowen , if spark context is not stopped, it is meaningless to delete this reference, if spark context is stopped, we should remove this reference at the same time. Therefore, I think this reference should be deleted in the shutdown method.

I don't think it makes sense to convert `sparkContext` into a soft reference.

**Comment by srowen** [comment]
Yes, the idea is to remove them when stopped. Is it possible, explicitly? This seems too hacky, and may have other side effects anyway; you're clearing all inheritable thread locals everywhere. I am suggesting soft refs for the fields you mention, not SparkContext.

**Comment by wankunde** [comment]
Update PR.

 @srowen Could you help me review the code?

Thanks.

**Comment by Ngone51** [comment]
I agree with @srowen and think the latest update is still too hacky.

I'm thinking about another way that we might avoid passing `activeThreadSession` to threads that are out of Spark by overriding `InheritableThreadLocal.childValue`. We could determine the thread by checking thread's stack trace, e.g:

```
private val activeThreadSession = new InheritableThreadLocal[SparkSession] {
  override def childValue(parentValue: Int): Int = {
      if (isWithinSpark(Thread.currentThread)) {
        parentValue
      } else {
       null
     }
  }
}
```

WDYT?

**Comment by wankunde** [comment]
@Ngone51 Agree with you, and updated the code.

**Comment by srowen** [comment]
Does this help actually clear the reference though?

**Comment by Ngone51** [comment]
@srowen Let me help explain a bit more:

`activeThreadSession` is a `InheritableThreadLocal`. Therefore, any child thread of the Spark main thread could keep a reference to the `SparkSession` (implemented by `childValue()` by default). In this case,  `org.apache.hive.common.util.ShutdownHookManager` creates the hook thread, which should be considered as a child thread of the Spark main thread, during its initialization and adds the hook thread to `java.lang.ApplicationShutdownHooks` at the end. Thus, when we stop the `SparkSession`, its reference is still kept at `java.lang.ApplicationShutdownHooks` since JVM hasn't shut down.

The new idea is to override the function `childValue()` to pass the custom value to the child threads. For child threads which created by Spark, we pass the active `SparkSession`. Otherwise, we pass `null` so that those child threads won't keep references of `SparkSession`.

**Comment by srowen** [comment]
This implies that some callers get a reference to this that they don't need at all. Can we just not retrieve them or clear them in the first place?

**Comment by Ngone51** [comment]
Those threads could be created by third-party libraries. They are not controlled by neither Spark nor users. So I think it's hard to do something in the first place.

**Comment by srowen** [comment]
Yeah, but your change now means they cannot get this value at all. That seems like it could break other code.

**Comment by Ngone51** [comment]
I see, change now may break users' code as well as libraries who depend on Spark. cc @wankunde

**Comment by wankunde** [comment]
@Ngone51 @srowen Update PR,  could we only remove the thread reference created by hive?

**Comment by srowen** [comment]
I dunno, this just feels pretty hacky and like it will break things. Is there no other way to avoid holding the reference with soft references, better cleanup? I think this is an niche, even unsupported, use case, to stop and restart the SparkContext in one JVM.

**Comment by Ngone51** [comment]
yea, I think I have to agree with @srowen . The approach is not perfect as I thought previously, sorry for the misleading @wankunde 

Soft reference could probably work in this case, e.g. `activeThreadSession = new InheritableThreadLocal[SoftReference[SparkSession]]`, but it may also break something potentially with soft reference? Not sure about that.

The use case is really abnormal. Maybe, you should just change your way.

**Comment by wankunde** [comment]
@srowen @Ngone51 

Thanks for all your help.

I will remove the reference after spark context is stopped in my application.

**Pull request closed without merging**
