### PR TITLE
[BUILD] Close stale PRs

### PR DESCRIPTION
**Pull request by jiangxb1987**
Closes #11494
Closes #14158
Closes #16803
Closes #16864
Closes #17455
Closes #17936
Closes #19377 

Added:
Closes #19380
Closes #18642
Closes #18377
Closes #19632

Added:
Closes #14471
Closes #17402
Closes #17953
Closes #18607

Also cc @srowen @vanzin @HyukjinKwon @gatorsmile @cloud-fan to see if you have other PRs to close.

### CODE REVIEW

**Comment by srowen** [comment]
I would close:

https://github.com/apache/spark/pull/19380
https://github.com/apache/spark/pull/16864
https://github.com/apache/spark/pull/16803
https://github.com/apache/spark/pull/17455
https://github.com/apache/spark/pull/18642
https://github.com/apache/spark/pull/18377

**Comment by robert3005** [comment]
#18406 isn't stale, thanks

**Comment by HyukjinKwon** [comment]
Mine is:

#14471
#17402
#17953
#18607

rest of them are basically a subset of the current list.

**Comment by jiangxb1987** [comment]
Removed #18406

**Review by vanzin — APPROVED** [review]

**Review by HyukjinKwon — APPROVED** [review]

**Review by gatorsmile — APPROVED** [review]
LGTM

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
