### PR TITLE
[MINOR][CONNECT] Fix some typos in connect server module

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr just fix some typos in connect server module

### Why are the changes needed?
Fix typos

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass GitHub Actions

### CODE REVIEW

**Review by Hisoka-X — APPROVED** [review]
LGTM

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by LuciferYang** [comment]
Merged into master and 3.5(due to connect)

**Comment by LuciferYang** [comment]
Thanks @dongjoon-hyun @Hisoka-X

**Pull request closed without merging**
