### PR TITLE
[SPARK-32819][SQL] ignoreNullability parameter should be effective recursively

### PR DESCRIPTION
**Pull request by viirya**
### What changes were proposed in this pull request?

This patch proposes to check `ignoreNullability` parameter recursively in `equalsStructurally` method.

### Why are the changes needed?

`equalsStructurally` is used to check type equality. We can optionally ask to ignore nullability check. But the parameter `ignoreNullability` is not passed recursively down to nested types. So it produces weird error like:

```
data type mismatch: argument 3 requires array<array<string>> type, however ... is of array<array<string>> type.
```

when running the query `select aggregate(split('abcdefgh',''), array(array('')), (acc, x) -> array(array( x ) ) )`.

### Does this PR introduce _any_ user-facing change?

Yes, fixed a bug when running user query.

### How was this patch tested?

Unit tests.

### CODE REVIEW

**Comment by viirya** [comment]
cc @cloud-fan @HyukjinKwon @dongjoon-hyun @maropu

**Comment by cloud-fan** [comment]
good catch! thanks, merging to master!

**Comment by cloud-fan** [comment]
@viirya can you open a PR for 3.0?

**Comment by maropu** [comment]
Nice catch.

**Comment by viirya** [comment]
Thanks! I will open a PR for 3.0.

**Comment by HyukjinKwon** [comment]
LGTM!

**Pull request closed without merging**
