### PR TITLE
[SPARK-7118] [Python] Add the coalesce Spark SQL function available in PySpark

### PR DESCRIPTION
**Pull request by ogirardot**
This patch adds a proxy call from PySpark to the Spark SQL coalesce function and this patch comes out of a discussion on dev@spark with @rxin

This contribution is my original work and i license the work to the project under the project's open source license.

Olivier.

### CODE REVIEW

**Comment by rxin** [comment]
Jenkins, test this please.

**Comment by rxin** [comment]
LGTM also.

**Comment by ogirardot** [comment]
Somehow Jenkins doesn't seem to be build this PR : https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/

**Comment by ogirardot** [comment]
is this the job now ? https://amplab.cs.berkeley.edu/jenkins/job/NewSparkPullRequestBuilder/ 
triggered by https://spark-prs.appspot.com/ ?

**Comment by ogirardot** [comment]
Jenkins, test this please. :)

**Comment by rxin** [comment]
Jenkins, test this please.

**Comment by ogirardot** [comment]
rebased properly :)

**Comment by rxin** [comment]
Jenkins, test this please.

**Comment by rxin** [comment]
Actually I think we changed the show() output format slightly, so you'd need to update the test case expected output.

**Comment by ogirardot** [comment]
can you launch the test you and I'll change the test accordingly ?

**Comment by ogirardot** [comment]
test is now fixed and using its own test variables

**Comment by ogirardot** [comment]
@pwendell do you mind launching the jenkins test, please ?

**Comment by pwendell** [comment]
Jenkins, retest this please. Jenkins, add to whitelist.

**Comment by rxin** [comment]
Thanks. Merging this in master and branch-1.4.

**Pull request closed without merging**
