### PR TITLE
[SPARK-9691] [SQL] PySpark SQL rand function treats seed 0 as no seed

### PR DESCRIPTION
**Pull request by yhuai**
https://issues.apache.org/jira/browse/SPARK-9691

@jkbradley @rxin

### CODE REVIEW

**Comment by rxin** [comment]
LGTM

**Comment by rxin** [comment]
Can we add a unit test? (not docstring)

**Comment by jkbradley** [comment]
LGTM, thanks!

**Comment by yhuai** [comment]
test this please

**Comment by rxin** [comment]
Merging.

**Pull request closed without merging**
