### PR TITLE
[SPARK-17671] [WEBUI] Spark 2.0 history server summary page is slow even set spark.history.ui.maxApplications

### PR DESCRIPTION
**Pull request by srowen**
## What changes were proposed in this pull request?

Return Iterator of applications internally in history server, for consistency and performance. See https://github.com/apache/spark/pull/15248 for some back-story.

The code called by and calling HistoryServer.getApplicationList wants an Iterator, but this method materializes an Iterable, which potentially causes a performance problem. It's simpler too to make this internal method also pass through an Iterator.
## How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by srowen** [comment]
CC @wgtmac and @ajbozarth for a look, in case I'm missing something.

**Comment by wgtmac** [comment]
LGTM

**Comment by ajbozarth** [comment]
LGTM

**Comment by ajbozarth** [comment]
LGTM

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
