### PR TITLE
[STREAMING][FLAKY-TEST] Catch execution context race condition in `FileBasedWriteAheadLog.close()`

### PR DESCRIPTION
**Pull request by brkyvz**
There is a race condition in `FileBasedWriteAheadLog.close()`, where if delete's of old log files are in progress, the write ahead log may close, and result in a `RejectedExecutionException`. This is okay, and should be handled gracefully.

Example test failures:
https://amplab.cs.berkeley.edu/jenkins/job/Spark-1.6-SBT/AMPLAB_JENKINS_BUILD_PROFILE=hadoop1.0,label=spark-test/95/testReport/junit/org.apache.spark.streaming.util/BatchedWriteAheadLogWithCloseFileAfterWriteSuite/BatchedWriteAheadLog___clean_old_logs/

The reason the test fails is in `afterEach`, `writeAheadLog.close` is called, and there may still be async deletes in flight.

@tdas @zsxwing

### CODE REVIEW

**Comment by tdas** [comment]
LGTM. @zsxwing what do you think?

**Comment by zsxwing** [comment]
LGTM

**Comment by zsxwing** [comment]
Thanks! Merging to master and 1.6

**Comment by zsxwing** [comment]
@brkyvz no JIRA for this one?

**Comment by brkyvz** [comment]
@zsxwing No. We could create one though if we like

**Pull request closed without merging**
