### PR TITLE
[SPARK-40637][SQL] Fix spark-sql can not show binary result normally

### PR DESCRIPTION
**Pull request by Hisoka-X**
### What changes were proposed in this pull request?
When we store a BINARY value (e.g. BigInt("1").toByteArray) / X'01') either via spark-shell or spark-sql, and then read it from spark-shell, it outputs `[01]`. However, it does not encode correctly when querying it via spark-sql.
```scala
spark-shell: 
scala> import org.apache.spark.sql.Row 
scala> import org.apache.spark.sql.types._
scala> val rdd = sc.parallelize(Seq(Row(BigInt("1").toByteArray)))
rdd: org.apache.spark.rdd.RDD[org.apache.spark.sql.Row] = ParallelCollectionRDD[356] at parallelize at <console>:28
scala> val schema = new StructType().add(StructField("c1", BinaryType, true))
schema: org.apache.spark.sql.types.StructType = StructType(StructField(c1,BinaryType,true))
scala> val df = spark.createDataFrame(rdd, schema)
df: org.apache.spark.sql.DataFrame = [c1: binary]
scala> df.write.saveAsTable("binary_vals_shell")
scala> spark.sql("select * from binary_vals_shell;").show(false)
+----+
|c1  |
+----+
|[01]|
+----+

spark-sql:
spark-sql> select * from binary_vals_shell;

Time taken: 0.077 seconds, Fetched 1 row(s)
```

The difference are `show` method in spark-shell will convert binary to hex string, spark-sql will not.

This PR bring a new sql config `spark.sql.hive.bytesToHex`, when set it to true, we will convert binary to hex string in spark-sql client.
After change:
./bin/spark-sql 
```scala
./bin/spark-sql -c spark.sql.hive.bytesToHex=true
spark-sql (default)> select * from binary_vals_shell;
[01]
Time taken: 2.647 seconds, Fetched 1 row(s)
```

### Why are the changes needed?
We expect the two Spark interfaces (spark-sql & spark-shell) to behave consistently for the same data type (BINARY) & input (BigInt("1").toByteArray) / X'01') combination.

### Does this PR introduce _any_ user-facing change?
Yes, the binary result will be changed after set config `spark.sql.hive.bytesToHex=true`

### How was this patch tested?
Add new test

### CODE REVIEW

**Comment by LuciferYang** [comment]
If this is considered a bug, why does it need to be controlled through a config to fix or not fix?

**Comment by srowen** [comment]
Not a bug, a behavior change at best. I think Databricks does something like this by default in its notebook display. I'm only concerned with breaking compatibility or something, but, not sure anything would rely on this output, or in this fairly useless form anyway

**Comment by cloud-fan** [comment]
I think only humans will read the output of spark-sql. It's not thriftserver that can serve BI clients. It should be OK to change the result directly without a config as the old form is quite useless.

**Comment by srowen** [comment]
I'm not sure it's worth it. Users can base64-encode before displaying if desired; neither is particularly meaningful to a human, so, not sure it's generally worth selecting a binary col for display anyway

**Comment by LuciferYang** [comment]
> I'm not sure it's worth it. Users can base64-encode before displaying if desired; neither is particularly meaningful to a human, so, not sure it's generally worth selecting a binary col for display anyway

As @srowen  said, users can use other ways for display. @Hisoka-X  Is `hex` the most commonly used? How are other competitors made? For example, presto, Snowflake, or Oracle, MySQL?

**Comment by yaooqinn** [comment]
Can you ensure MySQL or Snowflake's behaviors are client-side or server-side?

The hive string method here is used by `spark-sql`(client-server embedded) and
 `thrift server` (client-server separated). The former simply uses it for printing,
 but the latter is much more complicated. Spark only has inlined the source code
 for the server, but for the clients, including thrift client, Hive Beeline,
 and Hive JDBC, we respect upstream fully.

The binary string shall be compatible with all client APIs. Changes here do break
for the JDBC ResultSet.getObject function, which coverts this binary string to byte
array again.


FYI, https://github.com/apache/hive/blob/431e7d9e5431a808106d8db81e11aea74f040da5/jdbc/src/java/org/apache/hive/jdbc/HiveBaseResultSet.java#L541

**Comment by yaooqinn** [comment]
> So I think add a config spark.sql.hive.bytesToHex for spark-sql will be reasonable.

It's not reasonable to add a config for a new bug, usually, we add it for an existing one to avoid behavior change.

> Or add a parameter to identify whether the invoke is from spark-sql or thrift-server.

It will bring inconsistency for this couple when you fix SQL and shell

**Comment by Hisoka-X** [comment]
According discussion with @yaooqinn , the change seem unnecessary. I will close this PR, if you have different view, please let me know.

**Pull request closed without merging**
