### PR TITLE
[MINOR][CORE] Remove code duplication (so the interface is used instead)

### PR DESCRIPTION
**Pull request by jaceklaskowski**
## What changes were proposed in this pull request?

Removed code duplication and used the interface instead.

/cc @JoshRosen @rxin

## How was this patch tested?

Local build. Waiting for OK from Jenkins.

### CODE REVIEW

**Comment by jaceklaskowski** [comment]
Proposed the changes since it made easier to understand the role of `getBlockData` vs `getLocalBytes` and in the end `ShuffleBlockResolver`. I'm not saying it should be accepted, but I'd like to hear your take on why it should not. Thanks!

**Comment by srowen** [comment]
I'm not sure about this. The `getBlockData` method handles both the shuffle/non-shuffle case separately too -- and will actually call back to `getLocalBytes`. It is probably OK now, and won't result in an infinite recursion, but is a distant problem waiting to happen. It looks like this method also purposely intends to handle the shuffle case manually, itself. I don't know that this is an unambiguously good refactoring so would not make this change.

**Comment by jaceklaskowski** [comment]
Partially agree @srowen. The reason for the change was `blockId.isShuffle` condition that both methods use to do their shuffle-specific handling. The change might not be the most correct one but I'm sure something's wrong here, but can't nail it and hence the change to review this part of shuffle system.

> "is a distant problem waiting to happen"

I was concerned about that too, but that's what the tests are supposed to cover. If there are few missing, they should be added, shouldn't they?

**Comment by rxin** [comment]
Can we please close this?

**Comment by jaceklaskowski** [comment]
Closed as per @rxin's request.

**Pull request closed without merging**
