### PR TITLE
[SPARK-19974][Block Manager] in-memory LRU for partitions of multiple RDDs testcase did a get that is no sense

### PR DESCRIPTION
**Pull request by jianran**
## What changes were proposed in this pull request?

in-memory LRU for partitions of multiple RDDs testcase did a get that is no sense; rdd_0_2  is the most recently used item that isn't the reason the rdd_0_2 is remain; `store.getSingleAndReleaseLock(rdd(0, 2)).isDefined ` as same as the previous line `store.memoryStore.contains(rdd(0, 2))`, so remove the no sense code

## How was this patch tested?

run the test

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)
(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Comment by srowen** [comment]
I don't understand why you say this test doesn't make sense. The assertion is correct. You say you think the second assertion should always pass, but, isn't that the purpose of the test?

**Comment by jianran** [comment]
I am sorry,you are right, the second assertion is ok; but what do you think about the assertion comment:_Do a get() on rdd_0_2 so that it is the most recently used item_, what is the purpose of the test?  lru or same rdd rule ;  the reason for rdd_0_2 should *not* be dropped is the same rdd rule, not the comment said _Do a get() on rdd_0_2 so that it is the most recently used item_, so i think the comment is wrong or the assertion is wrong; I am sorry, if the  purpose of the test is only to test rdd_0_2 was not in store, it is ok, I didn't understand the purpose or the comment of the assertion, I am sorry;

**Comment by srowen** [comment]
I'm also not sure about the intent of these lines and it is possible the comment doesn't quite reflect the call that follows because it refers to get(). However it seems like the tests are still valid. Unless you know they are wrong yet pass then i would leave it.

**Comment by jianran** [comment]
do you agree remove the comment is more appreciable? can i only remove the comment?

**Comment by srowen** [comment]
Unless we are sure, I don't think it is worth changing.

**Pull request closed without merging**
