### PR TITLE
[SPARK-20963][SQL] Support column aliases for join relations in FROM clause

### PR DESCRIPTION
**Pull request by maropu**
## What changes were proposed in this pull request?
This pr added parsing rules to support column aliases for join relations in FROM clause.
This pr is a sub-task of #18079.

## How was this patch tested?
Added tests in `AnalysisSuite`, `PlanParserSuite,` and `SQLQueryTestSuite`.

### CODE REVIEW

**Comment by maropu** [comment]
In `visitTableName` in `AstBuilder`, we already have a different analyzer path to resolve column aliases (https://github.com/maropu/spark/blob/6c93f859b7ef2cc7f7cb49ab6fbd0397b43fda84/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/parser/AstBuilder.scala#L685). We could also use `UnresolvedSubqueryColumnAliases` along with `visitAliasedQuery` and `visitAliasedRelation` though, I'm not sure it is worth fixing so. So, could you give me insight on this, too? Thanks.

**Comment by maropu** [comment]
Jenkins, retest this please.

**Comment by maropu** [comment]
ping

**Comment by gatorsmile** [comment]
ping me? : )

Will review it in the next few days.

**Comment by maropu** [comment]
oh, yea. Sorry to forget to add `@`... ;) Thanks!

**Comment by gatorsmile** [comment]
https://github.com/apache/spark/pull/18772#issuecomment-318851145 

This sounds a good idea to me. 👍

**Comment by maropu** [comment]
ok, I'll fix that way. Is it okay to include the fix in this pr? or, follow-up?

**Comment by gatorsmile** [comment]
Let us do it in a separate PR. Thanks!

**Comment by maropu** [comment]
ok. When I finished this pr, I'll do. Thanks!

**Comment by gatorsmile** [comment]
retest this please

**Comment by gatorsmile** [comment]
LGTM pending Jenkins.

**Review by gatorsmile — APPROVED** [review]

**Comment by gatorsmile** [comment]
Thanks! Merging to master.

**Comment by maropu** [comment]
Thanks! I'll make a pr later to fix [this](https://github.com/apache/spark/pull/18772#issuecomment-318967315) as follow-up.

**Pull request closed without merging**
