### PR TITLE
[SPARK-45977][BUILD] Make sbt doc execute successfully

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
This pr aims to make sbt doc execute successfully.

### Why are the changes needed?
https://github.com/panbingkun/spark/actions/runs/6906151815/job/18790542503
image
https://github.com/panbingkun/spark/actions/runs/6906146025/job/18790523608

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Actually, I have an alternative idea because it happens only in `docker-integration-tests`. and the main doc generation pipeline doesn't show failures. WDTY, @panbingkun ?
- https://github.com/apache/spark/pull/43875

**Comment by dongjoon-hyun** [comment]
For the record, `master` branch is recovered.
Screenshot 2023-11-17 at 12 05 50 PM

**Comment by panbingkun** [comment]
> Actually, I have an alternative idea because it happens only in `docker-integration-tests`. and the main doc generation pipeline doesn't show failures. WDTY, @panbingkun ?
> 
> * [[SPARK-45978][INFRA] Skip unidoc step in `docker-integration-tests` GitHub Action job #43875](https://github.com/apache/spark/pull/43875)

Okay, let me turn it off. 
Additionally, I suspect that this PR ` https://github.com/apache/spark/pull/43855` may have caused the problem.
I'm not sure, I will verify it later.

**Comment by dongjoon-hyun** [comment]
Ya, I also have the similar idea, @panbingkun . We may still need this PR for doc generation in some case. Let's keep this open.

**Comment by panbingkun** [comment]
> Ya, I also have the similar idea, @panbingkun . We may still need this PR for doc generation in some case. Let's keep this open.

Okay，😄

**Comment by LuciferYang** [comment]
Haha, I was wondering why this check failed this morning：）

**Pull request closed without merging**
