### PR TITLE
[SPARK-10619] Can't sort columns on Executor Page

### PR DESCRIPTION
**Pull request by tgravescs**
should pick into spark 1.5.2 also.

https://issues.apache.org/jira/browse/SPARK-10619

looks like this was broken by commit: https://github.com/apache/spark/commit/fb1d06fc242ec00320f1a3049673fbb03c4a6eb9#diff-b8adb646ef90f616c34eb5c98d1ebd16
It looks like somethings were change to use the UIUtils.listingTable but executor page wasn't converted so when it removed sortable from the UIUtils. TABLE_CLASS_NOT_STRIPED it broke this page.

Simply add the sortable tag back in and it fixes both active UI and the history server UI.

### CODE REVIEW

**Comment by rxin** [comment]
cc @zsxwing

**Comment by zsxwing** [comment]
@tgravescs good catch. Could you also fix other places that use `TABLE_CLASS_NOT_STRIPED` and `TABLE_CLASS_STRIPED`?

**Comment by tgravescs** [comment]
Updated

**Comment by tgravescs** [comment]
Jenkins, test this please

**Comment by zsxwing** [comment]
LGTM

**Comment by rxin** [comment]
Merging this. Thanks, Tom.

**Pull request closed without merging**
