### PR TITLE
[SPARK-22926] [SQL] Respect table-level conf compression codec `Compression` in multiple scenarios

### PR DESCRIPTION
**Pull request by gatorsmile**
## What changes were proposed in this pull request?
Currently, we ignore table-specific `compression` conf when the Hive serde tables are converted to the data source tables. We also ignore it when users set `compression` in the TBLPROPERTIES clause instead of the OPTIONS clause, even if the tables are native data source tables. This PR is to fix the above issue.

The PR https://github.com/apache/spark/pull/20087 will make the Hive-serde writer aware of the table-level prop. 

The PR https://github.com/apache/spark/pull/20076 will make Spark aware of the table-specific conf `parquet.compression` too

## How was this patch tested?
Added test cases

### CODE REVIEW

**Comment by gatorsmile** [comment]
cc @cloud-fan

**Comment by gatorsmile** [comment]
retest this please

**Comment by cloud-fan** [comment]
I think we should document the difference between table options and properties. AFAIK we added table properties to data source tables since Spark 2.3, and previously table options is the only place for users to put some configs to change some behaviors.

**Comment by dongjoon-hyun** [comment]
@gatorsmile . Did you add some document for this?

**Pull request closed without merging**
