### PR TITLE
[SPARK-43149][SQL] Fix when CTAS with USING fails metadata in metastore gets left

### PR DESCRIPTION
**Pull request by Hisoka-X**
### What changes were proposed in this pull request?
When use CTAS with USING statement, the statement execute failed, like this:
```sql
spark-sql (default)> create table parquet_ds1 using parquet as
                   > select id, date'2018-01-01' + make_dt_interval(0, id)
                   > from range(0, 10);

Cannot create a table having a column whose name contains commas in Hive metastore. Table: `spark_catalog`.`default`.`parquet_ds1`; Column: DATE '2018-01-01' + make_dt_interval(0, id, 0, 0.000000)
```
When execute it second time, the different error will be reported:
```log
spark-sql (default)> create table parquet_ds1 using parquet as
                   > select id, date'2018-01-01' + make_dt_interval(0, id) as ts
                   > from range(0, 10);
[LOCATION_ALREADY_EXISTS] Cannot name the managed table as `spark_catalog`.`default`.`parquet_ds1`, as its associated location 'file:/Users/fanjia/Code/spark/spark-warehouse/parquet_ds1' already exists. Please pick a different table name, or remove the existing location first.
org.apache.spark.SparkRuntimeException: [LOCATION_ALREADY_EXISTS] Cannot name the managed table as `spark_catalog`.`default`.`parquet_ds1`, as its associated location 'file:/Users/fanjia/Code/spark/spark-warehouse/parquet_ds1' already exists. Please pick a different table name, or remove the existing location first.
        at org.apache.spark.sql.errors.QueryExecutionErrors$.locationAlreadyExists(QueryExecutionErrors.scala:2834)
        at org.apache.spark.sql.catalyst.catalog.SessionCatalog.validateTableLocation(SessionCatalog.scala:414)
        at org.apache.spark.sql.execution.command.CreateDataSourceTableAsSelectCommand.run(createDataSourceTables.scala:176)
```

The reason are execute  CTAS with USING will have two step: 1. save data into file path; 2. create table on catalog.
If the step 2 failed, the file will not be deleted, so the second time create table will reported `LOCATION_ALREADY_EXISTS`.
So this PR will delete there file after step 2 failed.

### Why are the changes needed?
Fix the bug when use CTAS with USING failed.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Add new test

### CODE REVIEW

**Comment by Hisoka-X** [comment]
cc @cloud-fan @MaxGekk @dongjoon-hyun

**Comment by cloud-fan** [comment]
It's a long-standing issue that CTAS is not atomic. In DS v2 we introduced `StagedTable` so that implementations can make CTAS atomic. I'm not sure we still want to fix CTAS v1 though.

**Comment by cloud-fan** [comment]
I see many people using the new lakehouse format such as delta lake, iceberg, hudi, etc., not the native file source provided by spark.

**Comment by Hisoka-X** [comment]
But the native file source provided by spark will have this problem right?

**Comment by Hisoka-X** [comment]
Thanks @cloud-fan , after rethink, maybe we shouldn't change current behavior. I close this PR.

**Pull request closed without merging**
