### PR TITLE
[SPARK-44803][BUILD] Replace `publish` with `publishOrSkip` in SparkBuild to eliminate warnings

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to replace `publishOrSkip` with `publish` in SparkBuild to eliminate warnings.

### Why are the changes needed?
After we upgraded SBT to 1.9.1+, the `publish` method has been marked as deprecated, to reduce compilation warnings.
image

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Manual testing.
We use the submodule 'tools' as an example to detect the local repo of mvn and ivy.
command: 
```
  sh build/sbt
  show tools/M2r/publishLocal
  show tools/Sbt/publishLocal
```

### CODE REVIEW

**Comment by panbingkun** [comment]
We executed the following tests at the code level based on the changes made by SBT.
1.The logic of SBT is as follows:
https://github.com/sbt/sbt/blob/1.9.x/main/src/main/scala/sbt/Defaults.scala#L3642-L3653

2.Test is as follows:
image

**Comment by panbingkun** [comment]
cc @LuciferYang

**Comment by panbingkun** [comment]
1.Before
sh build/sbt
image
- Maven:
image

- Ivy:
image

2.After
sh build/sbt
image

- Maven:
image

- Ivy:
image

**Review by LuciferYang — APPROVED** [review]

**Comment by LuciferYang** [comment]
cc @dongjoon-hyun

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Pull request closed without merging**
