### PR TITLE
[SPARK-26025][k8s] Speed up docker image build on dev repo.

### PR DESCRIPTION
**Pull request by vanzin**
The "build context" for a docker image - basically the whole contents of the
current directory where "docker" is invoked - can be huge in a dev build,
easily breaking a couple of gigs.

Doing that copy 3 times during the build of docker images severely slows
down the process.

This patch creates a smaller build context - basically mimicking what the
make-distribution.sh script does, so that when building the docker images,
only the necessary bits are in the current directory. For PySpark and R that
is optimized further, since those images are built based on the previously
built Spark main image.

In my current local clone, the dir size is about 2G, but with this script
the "context" sent to docker is about 250M for the main image, 1M for the
pyspark image and 8M for the R image. That speeds up the image builds
considerably.

I also snuck in a fix to the k8s integration test dependencies in the sbt
build, so that the examples are properly built (without having to do it
manually).

### CODE REVIEW

**Comment by shaneknapp** [comment]
test this please

**Comment by shaneknapp** [comment]
test this please

**Comment by shaneknapp** [comment]
ok, i think i fixed the problem w/the jenkins config. 

test this please

**Comment by shaneknapp** [comment]
test this please

**Comment by vanzin** [comment]
Great, when we want the tests to fail they pass... thanks anyway Shane!

**Comment by vanzin** [comment]
(The log files did show up though. Yay!)

**Review by srowen — APPROVED** [review]
Go for it.

**Comment by vanzin** [comment]
Merging to master.

**Pull request closed without merging**
