### PR TITLE
[SPARK-43222][CORE][SQL][K8S][TESTS] Remove `isHadoop3` check from tests

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
Remove `isHadoop3` related checks from Spark code because Apache Spark 3.5.0 no longer supports Hadoop 2.

### Why are the changes needed?
Code clean up.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass GitHub Actions

### CODE REVIEW

**Comment by LuciferYang** [comment]
Test first, will update pr  description later

**Comment by LuciferYang** [comment]
wait https://github.com/apache/spark/pull/40870

**Comment by LuciferYang** [comment]
cc @sunchao @pan3793

**Review by pan3793 — APPROVED** [review]
LGTM

**Review by HyukjinKwon — APPROVED** [review]

**Review by zhengruifeng — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by LuciferYang** [comment]
Thanks @HyukjinKwon @zhengruifeng @pan3793

**Pull request closed without merging**
