### PR TITLE
[SPARK-21173] There are several configuration about SSL displayed in  configuration.md but never be used.

### PR DESCRIPTION
**Pull request by liu-zhaokun**
[https://issues.apache.org/jira/browse/SPARK-21173](https://issues.apache.org/jira/browse/SPARK-21173)
There are several configuration about SSL displayed in configuration.md but never be used and appear at spark's code.So I think it should be removed from configuration.md.

### CODE REVIEW

**Comment by jerryshao** [comment]
It indeed used in Spark code `SSLOptions`, for example ssl port is used to specify https port for https live and history UI. Also `needClientAuth` is used for mutual authentication. I'm not sure why it is not used, can you please clarify?

**Comment by liu-zhaokun** [comment]
@jerryshao 
Thanks for your reply.I didn't notice "spark.ssl" has been replaced by $ns inSSLOptions,it is my fault.But I still have a question,whether "spark.ssl.[namespace].port" should be modify to "spark.ssl.port" to meet the naming style of others?

**Comment by jerryshao** [comment]
Sorry I cannot get your point?

>But I still have a question,whether "spark.ssl.[namespace].port" should be modify to "spark.ssl.port" to meet the naming style of others?

**Comment by liu-zhaokun** [comment]
@jerryshao 
Sorry,my English is poor.I mean whether we should  change the configuration which named "spark.ssl.[namespace].port" to "spark.ssl.port".

**Comment by jerryshao** [comment]
Can you please point where do we change from "spark.ssl.[namespace].port" to "spark.ssl.port"?

**Comment by liu-zhaokun** [comment]
@jerryshao 
Ok, I get it.

**Comment by srowen** [comment]
This should be closed

**Pull request closed without merging**
