### PR TITLE
[SPARK-50172][BUILD] Upgrade scala-maven-plugin to 4.9.2

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr aims to upgrade scala-maven-plugin from 4.9.1 to 4.9.2

### Why are the changes needed?
The complete diff list is as follows:
- https://github.com/davidB/scala-maven-plugin/compare/4.9.1...4.9.2

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
- Pass Github Actions
- Pass Maven tests: https://github.com/LuciferYang/spark/runs/32260101974

image

### Was this patch authored or co-authored using generative AI tooling?
No

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
According to the commit list, it looks safe. Please let me know when the PR is ready, @LuciferYang .

**Comment by LuciferYang** [comment]
> According to the commit list, it looks safe. Please let me know when the PR is ready, @LuciferYang .

ready ~

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @LuciferYang .

**Review by zhengruifeng — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Merged to master~

**Pull request closed without merging**
