### PR TITLE
[SPARK-39458][CORE][TESTS] Fix `UISuite` for IPv6

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to fix `UISuite` to work in IPv6 environment.

### Why are the changes needed?

IPv6 address contains `:`.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Manual tests in Pure IPv6 environment.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Could you review this test PR, @huaxingao ?

**Comment by huaxingao** [comment]
@dongjoon-hyun Thanks for pinging me. The change looks good to me.

**Review by huaxingao — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @huaxingao !

**Comment by dongjoon-hyun** [comment]
Merged to master.

**Pull request closed without merging**
