### PR TITLE
[SPARK-11531] [ML] : SparseVector error Msg

### PR DESCRIPTION
**Pull request by rekhajoshm**
PySpark SparseVector should have "Found duplicate indices" error message

### CODE REVIEW

**Comment by yu-iskw** [comment]
I think it would be natural to fix the Scala error message and fix the condition in Python. The algorithm checks not the indexes have duplicated values, but the indexes are sorted.

@srowen  What do you think?

## Python
Replace `>=` with `>`.
```
if self.indices[i] > self.indices[i + 1]:
    raise TypeError("indices array must be sorted")
```

## Scala
Change the message.
```
require(prev < i, s"indices array must be sorted: $i.")
```

**Comment by urvishparikh** [comment]
@yu-iskw The indices are sorted within the code base at:
https://github.com/apache/spark/blob/master/python/pyspark/mllib/linalg/__init__.py#L510

So the only way to actually get that error is not by the user supplying unsorted indices, but the user supplying duplicate indices.

**Comment by yu-iskw** [comment]
@urvishparikh oh, got it. Thank you for letting me know. It's my fault. 
If the indexes are already sorted, the condition should be `==`, right?

**Comment by urvishparikh** [comment]
Yes but for consistency sake (and for ensuring sortedness which is crucial for SparseVector to function) I think the >= condition is fine.

**Comment by yu-iskw** [comment]
All right. We should focus on change the error message in this issue. Thank you for making it clear.

LGTM

**Comment by mengxr** [comment]
@urvishparikh People need to know the indices are ordered to understand the implementation here. It would be better if you put both the i-th index and the (i+1)-th index in the error message and say that the indices are not strictly increasing.

**Comment by urvishparikh** [comment]
Yes I agree @mengxr that much is definitely true. If we make that change here then we also have to make that corresponding change in the scala version.

**Comment by jkbradley** [comment]
@rekhajoshm +1 for the suggestion from @mengxr   Could you please update this accordingly?  Thanks!  (Or please comment if you don't have time.)

@urvishparikh There is a bit of inconsistency / lack of clarity currently about which vector construction methods sort vs. not, especially comparing Scala vs. Python.  Let's clean that up in separate issues.

**Comment by rekhajoshm** [comment]
Thanks @jkbradley might have missed it or thought it was under discussion.updated.thanks

**Comment by jkbradley** [comment]
LGTM.  Merging with master
Thanks!

**Pull request closed without merging**
