### PR TITLE
[SPARK-6191] [EC2] Generalize ability to download libs

### PR DESCRIPTION
**Pull request by nchammas**
Right now we have a method to specifically download boto. This PR generalizes it so it's easy to download additional libraries if we want.

For example, adding new external libraries for spark-ec2 is now as simple as:

``` python
external_libs = [
    {
         "name": "boto",
         "version": "2.34.0",
         "md5": "5556223d2d0cc4d06dd4829e671dcecd"
    },
    {
        "name": "PyYAML",
        "version": "3.11",
        "md5": "f50e08ef0fe55178479d3a618efe21db"
    },
    {
        "name": "argparse",
        "version": "1.3.0",
        "md5": "9bcf7f612190885c8c85e30ba41db3c7"
    }
]
```

Likely use cases:
- Downloading PyYAML to allow spark-ec2 configs to be persisted as a YAML file. ([SPARK-925](https://issues.apache.org/jira/browse/SPARK-925))
- Downloading argparse to clean up / modernize our option parsing.

First run output, with PyYAML and argparse added just for demonstration purposes:

``` shell
$ ./spark-ec2 --version
Downloading external libraries that spark-ec2 needs from PyPI to /path/to/spark/ec2/lib...
This should be a one-time operation.
 - Downloading boto...
 - Finished downloading boto.
 - Downloading PyYAML...
 - Finished downloading PyYAML.
 - Downloading argparse...
 - Finished downloading argparse.
spark-ec2 1.2.1
```

Output thereafter:

``` shell
$ ./spark-ec2 --version
spark-ec2 1.2.1
```

### CODE REVIEW

**Comment by nchammas** [comment]
cc @JoshRosen

**Comment by srowen** [comment]
Obviously I'd like to get another actual active EC2 user to review this, but the principle looks fine. this is refactoring the boto-specific mechanism to be general and at the moment does not change behavior.

**Comment by nchammas** [comment]
Yeah, if @JoshRosen (who wrote the original `setup_boto()` function) can't take a look, maybe @shivaram can give this a look.

**Comment by JoshRosen** [comment]
This seems fine to me.  I guess the alternatives would be 

1. storing the libraries in our source tree, which is a bad option for several reasons, including licensing, file size, upgradability, etc.
2. requiring the users to install the libraries themselves using a `pip` requirements file, but that adds another dependency on pip

I think that this is fine for now.  As part of our binary release packaging scripts, we could download and include these archives so that only users who build from source will need to perform these downloads.

**Pull request closed without merging**
