### PR TITLE
[SPARK-50011][INFRA] Add a separate docker file for doc build

### PR DESCRIPTION
**Pull request by zhengruifeng**
### What changes were proposed in this pull request?
Add a separate docker file for doc build

### Why are the changes needed?
currently we only have single test image, for `pyspark`, `sparkr`, `lint` and `docs`, it has two major issues:
1, disk space limitation: we are adding more and more packages in it, the disk space left for testing is very limited, and cause `No space left on device` from time to time;
2, environment conflicts: for example, even though we already install some packages for `docs` in the docker file, we still need to install some additional python packages in `build_and_test`, due to the conflicts between `docs` and `pyspark`. It is hard to maintain because the related packages are installed in two different places.

so I am thinking of spinning off some installations (e.g. `docs`) from the base image, so that:
1, we can completely cache all the dependencies for `docs`;
2, the related installations are centralized;
3, we can free up disk space on the base image (after we spin off other dependency, we can remove unneeded packages from it);

Furthermore, if we want to apply multiple images, we can easily support different environments, e.g. adding a separate image for old versions of `pandas/pyarrow/etc`. 

### Does this PR introduce _any_ user-facing change?
no, infra-only

### How was this patch tested?
ci

### Was this patch authored or co-authored using generative AI tooling?
no

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @zhengruifeng .
Merged to master.

I saw that the doc image was used in this PR builder.
```
 master-11379761301: Pulling from zhengruifeng/apache-spark-ci-image-docs
```

**Comment by zhengruifeng** [comment]
thanks @dongjoon-hyun for reviews!

**Comment by Yikun** [comment]
Have offline discussion with ruifeng:

1. we need to also refresh the image cache job, otherwise cache speed up will not work: 
https://github.com/apache/spark/blob/master/.github/workflows/build_infra_images_cache.yml
  - Fix paths
  - add a step for doc image cache

the infra image cache is a separate job will be triggered when the dockerfile PR is merged (we first make sure ci passed and the dockerfile do the right fix/upgrade/change, then do the [post fresh](https://github.com/apache/spark/blob/75b86667ee7607d3523d7ce75c1022752142a443/.github/workflows/build_infra_images_cache.yml#L24))

2. For branch cache/job images, we could keep original behavior that means:

**For branch jobs (doc and test):**
cache: ghcr.io/apache/spark/apache-spark-github-action-image-cache:branch-3.5
job: apache-spark-ci-image:${{ inputs.branch }}-${{ github.run_id }}

**For master jobs:**
test:
cache: ghcr.io/apache/spark/apache-spark-github-action-image-cache:branch-3.5
job: apache-spark-ci-image:${{ inputs.branch }}-${{ github.run_id }}

doc:
cache: ghcr.io/apache/spark/apache-spark-github-action-image-**docs**-cache:branch-3.5
job: apache-spark-ci-image-**docs**:${{ inputs.branch }}-${{ github.run_id }}

**Comment by zhengruifeng** [comment]
thanks @Yikun , sending a fix in https://github.com/apache/spark/pull/48533

**Comment by dongjoon-hyun** [comment]
Unfortunately, it turns out that the follow-up also broke the release branches
- https://github.com/apache/spark/pull/48533#issuecomment-2422878623

As a release manager of Apache Spark 3.4.4 EOL release, I reverted SPARK-50011 (this and the follow-up commit) for now. Sorry about that.
- https://github.com/apache/spark/commit/aaecab3d3c8b116e4aa32b2b26ad6a1b32f2a80a
- https://github.com/apache/spark/commit/6f710cd9c561c911066108b7d659d5de44099757

**Comment by dongjoon-hyun** [comment]
Can we re-start cleanly to make it sure to pass all CI combinations?

**Pull request closed without merging**
