### PR TITLE
[SPARK-16096][SPARKR] add union and deprecate unionAll

### PR DESCRIPTION
**Pull request by felixcheung**
## What changes were proposed in this pull request?

add union and deprecate unionAll, separate roxygen2 doc for rbind (since their usage and parameter lists are quite different)

`explode` is also deprecated - but seems like replacement is a combination of calls; not sure if we should deprecate it in SparkR, yet.
## How was this patch tested?

unit tests, manual checks for r doc

### CODE REVIEW

**Comment by felixcheung** [comment]
@shivaram

**Comment by shivaram** [comment]
cc @liancheng 

Code changes look good to me

**Comment by shivaram** [comment]
Just wondering -- is there a list of SparkSQL deprecations for 2.0.0 ?

**Comment by felixcheung** [comment]
should that be listed in the Migration Guide section of https://github.com/apache/spark/blob/master/docs/sql-programming-guide.md?

**Comment by felixcheung** [comment]
a search of `@deprecated(..., "2.0.0")` in https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/Dataset.scala

shows `explode` is the only one left (again with no single replacement)

**Comment by shivaram** [comment]
Alright - yeah lets leave `explode` as is for now. LGTM. Merging this to master, branch-2.0

**Pull request closed without merging**
