### PR TITLE
[SPARK-43206][SS][CONNECT][FOLLOWUP] Remove unintended change on `StreamingQueryManager.scala`

### PR DESCRIPTION
**Pull request by WweiL**
### What changes were proposed in this pull request?

https://github.com/apache/spark/pull/40966 introduced a unneeded change in `StreamingQueryManager` by error. This fix removes it.

### Why are the changes needed?

Bug fix

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Existing tests

### CODE REVIEW

**Review by hvanhovell — APPROVED** [review]
LGTM

**Comment by amaliujia** [comment]
LGTM

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by dongjoon-hyun** [comment]
Merged to `master`.
Thank you for the quick fix, @WweiL , @hvanhovell , @amaliujia .

**Pull request closed without merging**
