### PR TITLE
[SPARK-41699][CONNECT][BUILD] Upgrade buf to v1.11.0

### PR DESCRIPTION
**Pull request by zhengruifeng**
### What changes were proposed in this pull request?
Upgrade buf to v1.11.0

### Why are the changes needed?
this upgrade doesn't change the generated codes now, so should be fine to upgrade

### Does this PR introduce _any_ user-facing change?
no

### How was this patch tested?
existing UT

### CODE REVIEW

**Comment by zhengruifeng** [comment]
cc @HyukjinKwon

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.
Since this is new at Apache Spark 3.4.0, the latest version sounds better to me.
Merged to master for Apache Spark 3.4.0.

**Comment by dongjoon-hyun** [comment]
Thank you, @zhengruifeng .

**Comment by zhengruifeng** [comment]
@dongjoon-hyun thank you for merging!

**Review by HyukjinKwon — COMMENTED** [review]
LGTM2

**Pull request closed without merging**
