### PR TITLE
The declared package "org.apache.hive.service.cli.thrift" does not match the expected package "java.org.apache.hive.service.cli.thrift"

### PR DESCRIPTION
**Pull request by Alanthur**
I import the spark source to eclipse.
qq 20171013144705

But I got some error.
The declared package "org.apache.hive.service.cli.thrift" does not match the expected package "java.org.apache.hive.service.cli.thrift"
qq 20171013145024

What should I do?

### CODE REVIEW

**Comment by dahaian** [comment]
@AmplabJenkins  can you help me solve my problem？Thanks

**Comment by srowen** [comment]
@dahaian close this please

**Comment by dahaian** [comment]
@srowen sorry,I just ask a question.If someone can help me.I will close this patch.

**Comment by srowen** [comment]
This isn't where you ask questions, and the branch itself is messed up. Please close it.
Questions go to the mailing list.

**Comment by dahaian** [comment]
@srowen sorry, I do not understand you said "the mailing list"?Please tell me how I ask a question?And I will close this patch.

**Comment by srowen** [comment]
This should be closed no matter what. Please start at the web site. http://spark.apache.org/community.html

**Comment by dahaian** [comment]
@srowen I closed

**Pull request closed without merging**
