### PR TITLE
[SPARK-33757][INFRA][R] Fix the R dependencies build error on GitHub Actions and AppVeyor

### PR DESCRIPTION
**Pull request by sarutak**
### What changes were proposed in this pull request?

This PR fixes the R dependencies build error on GitHub Actions and AppVeyor.
The reason seems that `usethis` package is updated 2020/12/10.
https://cran.r-project.org/web/packages/usethis/index.html

### Why are the changes needed?

To keep the build clean.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Should be done by GitHub Actions.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Nice, thanks @sarutak. Do you mind updating appveyor.yml too?

**Review by HyukjinKwon — APPROVED** [review]
LGTM if tests pass

**Comment by sarutak** [comment]
Sure, I'll try it.

**Comment by HyukjinKwon** [comment]
Merged to master, branch-3.1, branch-3.0 and branch-2.4.

**Comment by dongjoon-hyun** [comment]
Thank you, @sarutak and @HyukjinKwon .

**Pull request closed without merging**
