### PR TITLE
[SPARK-46311][CORE] Log the final state of drivers during `Master.removeDriver`

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to log the final state of drivers during `Master.removeDriver`.

### Why are the changes needed?

We can easily identify the status of all drivers from Master log in a centralized manner.

```
- 23/12/07 13:51:41 INFO Master: Removing driver: driver-20231207135138-0000
+ 23/12/07 13:51:41 INFO Master: Removing driver: driver-20231207135138-0000 (FINISHED)
```

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Manual review.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Could you review this log PR, @sunchao ?

**Review by sunchao — APPROVED** [review]
LGTM

**Comment by dongjoon-hyun** [comment]
Thank you, @sunchao !

**Review by beliefer — COMMENTED** [review]
Late LGTM.

**Pull request closed without merging**
