### PR TITLE
[SPARK-26922][R] Set socket timeout consistently in Arrow optimization

### PR DESCRIPTION
**Pull request by HyukjinKwon**
## What changes were proposed in this pull request?

This PR sets socket timeout consistently across Arrow optimization by `SPARKR_BACKEND_CONNECTION_TIMEOUT`. There looks only one place left.

## How was this patch tested?

Existing tests should cover.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @felixcheung

**Comment by HyukjinKwon** [comment]
Let me just get this in. I am pretty sure this is the only last instance left.

**Comment by HyukjinKwon** [comment]
Merged to master.

**Review by felixcheung — COMMENTED** [review]
LG

**Pull request closed without merging**
