### PR TITLE
[SPARK-43165][SQL] Move canWrite to DataTypeUtils

### PR DESCRIPTION
**Pull request by amaliujia**
### What changes were proposed in this pull request?

Move canWrite to DataTypeUtils.

### Why are the changes needed?

canWrite access SQLConf so we can move it out from DataType to make DataType as public simpiler API.

### Does this PR introduce _any_ user-facing change?

NO

### How was this patch tested?

UT

### CODE REVIEW

**Comment by amaliujia** [comment]
@cloud-fan

**Comment by amaliujia** [comment]
```
[error] spark-catalyst: Failed binary compatibility check against org.apache.spark:spark-catalyst_2.12:3.3.0! Found 2 potential problems (filtered 1415)
[error]  * static method canWrite(org.apache.spark.sql.types.DataType,org.apache.spark.sql.types.DataType,Boolean,scala.Function2,java.lang.String,scala.Enumeration#Value,scala.Function1)Boolean in class org.apache.spark.sql.types.DataType does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("org.apache.spark.sql.types.DataType.canWrite")
[error]  * method canWrite(org.apache.spark.sql.types.DataType,org.apache.spark.sql.types.DataType,Boolean,scala.Function2,java.lang.String,scala.Enumeration#Value,scala.Function1)Boolean in object org.apache.spark.sql.types.DataType does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("org.apache.spark.sql.types.DataType.canWrite")
```

Failing because of this.

In fact this method should be marked as private sql method....

**Comment by hvanhovell** [comment]
@amaliujia IMO it is fine to move this and break compatibility a bit. Let's just update the MiMa checks and move on.

**Comment by amaliujia** [comment]
I updated the MIMA check.

**Review by hvanhovell — APPROVED** [review]
LGTM

**Review by cloud-fan — APPROVED** [review]

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Pull request closed without merging**
