### PR TITLE
[SPARK-8930][SQL] Support a star '*' in generator function arguments

### PR DESCRIPTION
**Pull request by maropu**
The current implementation throws an exception if generators contain a star '_' like codes blow;
val df = Seq(("1", "1,2"), ("2", "4"), ("3", "7,8,9")).toDF("prefix", "csv")
checkAnswer(
df.explode($"_")
{ case Row(prefix: String, csv: String) => csv.split(",").map(v => Tuple1(prefix + ":" + v)) }
,
Row("1", "1,2", "1:1") :: Row("1", "1,2", "1:2")
:: Row("2", "4", "2:4")
:: Row("3", "7,8,9", "3:7") :: Row("3", "7,8,9", "3:8") :: Row("3", "7,8,9", "3:9")
:: Nil
)
[info] - explode takes UnresolvedStar **\* FAILED **\* (14 milliseconds)
[info] org.apache.spark.sql.AnalysisException: cannot resolve '_1' given input columns prefix, csv;
[info] at org.apache.spark.sql.catalyst.analysis.package$AnalysisErrorAt.failAnalysis(package.scala:42)
[info] at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1$$anonfun$apply$2.applyOrElse(CheckAnalysis.scala:55)
[info] at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1$$anonfun$apply$2.applyOrElse(CheckAnalysis.scala:52)
[info] at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformUp$1.apply(TreeNode.scala:291)
[info] at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformUp$1.apply(TreeNode.scala:291)
[info] at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:51)
[info] at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:290)
[info] at org.apache.spark.sql.catalyst.plans.QueryPlan.transformExpressionUp$1(QueryPlan.scala:107)
[info] at org.apache.spark.sql.catalyst.plans.QueryPlan.org$apache$spark$sql$catalyst$plans$QueryPlan$$recursiveTransform$2(QueryPlan.scala:117)
[info] at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$org$apache$spark$sql$catalyst$plans$QueryPlan$$recursiveTransform$2$1.apply(QueryPlan.scala:1
21)
[info] at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
[info] at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
[info] at scala.collection.immutable.List.foreach(List.scala:318)
[info] at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
[info] at scala.collection.AbstractTraversable.map(Traversable.scala:105)

[Review on Reviewable](https://reviewable.io/reviews/apache/spark/7305)

### CODE REVIEW

**Comment by chenghao-intel** [comment]
@maropu Probably this is incorrect.
`Explode` actually only accept single child expression, which should be either in `ArrayType` or `MapType`, pass in a `Star` probably not correct in semantics, particularly the `star` can be expanded into couple of expressions.

And in `Analyzer`, seems you simply transform the generator from `Explode` into `UserDefinedGenerator` if it contains `star`, that's not an `explode` any more.

From the unit test code, probably the SQL like below can achieve the same purpose.
···
 Seq(("1", "1,2"), ("2", "4"), ("3", "7,8,9")).toDF("prefix", "csv").registerTempTable("table")
SELECT prefix, csv, concat(prefix, ':', r) FROM table LATERAL VIEW explode(split(csv,',')) d as r
···

**Comment by maropu** [comment]
@chenghao-intel So I'll fix this PR to throw an AnalysisException if Generate has '*'.
Is it ok?

**Comment by maropu** [comment]
@chenghao-intel Ok, thanks.
Is the limitation only applied to ``Explode`` and I mean that can other generator functions have multiple expressions?
Anyway, I'll fix this PR to throw an AnalysisException if Explode has '*'.

**Comment by maropu** [comment]
I understood that Hive ``explode`` only has a single expression though, should we apply the same limitation into ``UserDefinedGenerator`` used in the DataFrame#explode implementation?
https://github.com/apache/spark/pull/7305/files#diff-57b3d87be744b7d79a9beacf8e5e5eb2R286

**Comment by maropu** [comment]
retest this please

**Pull request closed without merging**
