### PR TITLE
[SPARK-42026][CORE] Protobuf serializer for `AppSummary` and `PoolData`

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
Add Protobuf serializer for `AppSummary` and `PoolData`

### Why are the changes needed?
Support fast and compact serialization/deserialization for `AppSummary` and `PoolData` over RocksDB.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Add new UT

### CODE REVIEW

**Comment by LuciferYang** [comment]
cc @gengliangwang 


I found there are some other objects use KVStoreProtobufSerializer but not match ProtobufSerializer:

```
19781 unmatched class org.apache.spark.status.PoolData
17177 unmatched class org.apache.spark.status.AppSummary
13207 unmatched class org.apache.spark.util.kvstore.RocksDB$TypeAliases
1533 unmatched class org.apache.spark.deploy.history.FsHistoryProviderMetadata
...
```

The first column is the number of unmatched times. `PoolData` and `AppSummary` are simple but high frequency, so I support them in this one.

**Comment by LuciferYang** [comment]
In the use of LiveUI, `RocksDB$TypeAliases` will only be serialized for a limited  times and will not be deserialized, so it can not be processed in Live UI

**Review by gengliangwang — APPROVED** [review]

**Comment by gengliangwang** [comment]
Thanks, merging to master

**Comment by LuciferYang** [comment]
Thanks @gengliangwang

**Pull request closed without merging**
