### PR TITLE
[SPARK-32138][FOLLOW-UP] Drop obsolete StringIO import branching

### PR DESCRIPTION
**Pull request by zero323**
### What changes were proposed in this pull request?

Removal of branched `StringIO` import.

### Why are the changes needed?

Top level `StringIO` is no longer present in Python 3.x.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by zero323** [comment]
cc @HyukjinKwon 

Doesn't seem like we need this one anymore, right?

**Comment by HyukjinKwon** [comment]
Yup!

**Review by HyukjinKwon — APPROVED** [review]
LGTM if tests pass

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by zero323** [comment]
Thanks @HyukjinKwon!

**Pull request closed without merging**
