### PR TITLE
[SPARK-31258][BUILD] Pin the avro version in SBT

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

add arvo dep in SparkBuild

### Why are the changes needed?
fix sbt unidoc like https://github.com/apache/spark/pull/28017#issuecomment-603828597 
```scala
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
[info] Main Scala API documentation to /home/jenkins/workspace/SparkPullRequestBuilder@6/target/scala-2.12/unidoc...
[info] Main Java API documentation to /home/jenkins/workspace/SparkPullRequestBuilder@6/target/javaunidoc...
[error] /home/jenkins/workspace/SparkPullRequestBuilder@6/core/src/main/scala/org/apache/spark/serializer/GenericAvroSerializer.scala:123: value createDatumWriter is not a member of org.apache.avro.generic.GenericData
[error]     writerCache.getOrElseUpdate(schema, GenericData.get.createDatumWriter(schema))
[error]                                                         ^
[info] No documentation generated with unsuccessful compiler run
[error] one error found
```

### Does this PR introduce any user-facing change?

no
### How was this patch tested?

pass jenkins
and verify manually with `sbt dependencyTree`
```scala
 kentyao@hulk  ~/spark   dep  build/sbt dependencyTree | grep avro | grep -v Resolving
[info]   +-org.apache.avro:avro-mapred:1.8.2
[info]   | +-org.apache.avro:avro-ipc:1.8.2
[info]   | | +-org.apache.avro:avro:1.8.2
[info]   +-org.apache.avro:avro:1.8.2
[info]   | | +-org.apache.avro:avro:1.8.2
[info] org.apache.spark:spark-avro_2.12:3.1.0-SNAPSHOT [S]
[info]   | | | +-org.apache.avro:avro-mapred:1.8.2
[info]   | | | | +-org.apache.avro:avro-ipc:1.8.2
[info]   | | | | | +-org.apache.avro:avro:1.8.2
[info]   | | | +-org.apache.avro:avro:1.8.2
[info]   | | | | | +-org.apache.avro:avro:1.8.2
```

### CODE REVIEW

**Comment by yaooqinn** [comment]
cc @HyukjinKwon

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
Hi, @yaooqinn . 
In the PR description, could you use `sbt` `dependencyTree` to show what is used currently?

**Comment by HyukjinKwon** [comment]
Also, let's file a JIRA.

**Comment by yaooqinn** [comment]
@dongjoon-hyun @HyukjinKwon, thanks. I have filed the Jira and update sbt-dependencyTree

**Comment by HyukjinKwon** [comment]
Looks good given they many people faced this randomly in unidoc. I checked the avro version is 1.8.2 from branch-2.4 to master.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master, branch-3.0, and branch-2.4.

**Comment by dongjoon-hyun** [comment]
Hi, @HyukjinKwon and @yaooqinn .
This seems to break `branch-2.4` SBT build at `org.apache.spark.streaming.flume.sink.SparkSinkSuite`.
- https://amplab.cs.berkeley.edu/jenkins/view/Spark%20QA%20Test%20(Dashboard)/job/spark-branch-2.4-test-sbt-hadoop-2.6/
- https://amplab.cs.berkeley.edu/jenkins/view/Spark%20QA%20Test%20(Dashboard)/job/spark-branch-2.4-test-sbt-hadoop-2.7/

**Comment by dongjoon-hyun** [comment]
The current situation is due to the incompatiblity between Avro 1.7 and 1.8.
This might be the outdated `sbt-avro` plugin issue.

**Comment by dongjoon-hyun** [comment]
Currently, this blocks the `branch-2.4` PR builder , too. I'll revert this first from `branch-2.4`. Please make a PR against `branch-2.4`. Thanks.

**Comment by HyukjinKwon** [comment]
Hm, I see. thanks for checking it, and reverting @dongjoon-hyun.

**Comment by HyukjinKwon** [comment]
Let me don't port it back considering the complexity vs the gain for now.

**Pull request closed without merging**
