### PR TITLE
[MINOR][CORE] Quiet request executor remove message.

### PR DESCRIPTION
**Pull request by cfmcgrady**
### What changes were proposed in this pull request?

Settings to quiet for Class `ExecutorAllocationManager` that request message too verbose. otherwise, this class generates too many messages like 
`INFO spark.ExecutorAllocationManager: Request to remove executorIds: 890`
 when we enabled DRA.

### Why are the changes needed?

Log level improvement.

### Does this PR introduce any user-facing change?

No

### CODE REVIEW

**Comment by srowen** [comment]
How frequently executors get removed? I'd be surprised if it's a lot; INFO sounds appropriate without knowing more about what you're seeing. What about other similar log messages?

**Comment by cfmcgrady** [comment]
hi, @srowen 
This is request removes the executor log, not removed executor message. When all executors have arrived expire time, the `ExecutorAllocationManager` will send requests per 100 ms by default, and this log also generates per 100 ms.

**Comment by srowen** [comment]
Yes I understand it's just removing a log message. Hm, so how many messages are being sent, every 100ms, and I wonder why it's frequent to remove executors with a bunch of rapid messages vs all at once?

**Comment by cfmcgrady** [comment]
Only one message will be send at once, but the same expired executor will be repeated request to removing.

**Comment by srowen** [comment]
Are you saying you get a bunch of messages for removing the same executor the same time? or just that it's removed 'often'? how many messages are we talking?

**Comment by cfmcgrady** [comment]
We got a bunch of messages in a long period of time, something like
```
19/12/19 17:31:43 INFO spark.ExecutorAllocationManager: Request to remove executorIds: 263
19/12/19 17:31:44 INFO spark.ExecutorAllocationManager: Request to remove executorIds: 263
19/12/19 17:31:44 INFO spark.ExecutorAllocationManager: Request to remove executorIds: 263
19/12/19 17:31:44 INFO spark.ExecutorAllocationManager: Request to remove executorIds: 263
19/12/19 17:31:44 INFO spark.ExecutorAllocationManager: Request to remove executorIds: 263
19/12/19 17:31:44 INFO spark.ExecutorAllocationManager: Request to remove executorIds: 263
19/12/19 17:31:44 INFO spark.ExecutorAllocationManager: Request to remove executorIds: 263
19/12/19 17:31:44 INFO spark.ExecutorAllocationManager: Request to remove executorIds: 263
19/12/19 17:31:44 INFO spark.ExecutorAllocationManager: Request to remove executorIds: 263
19/12/19 17:31:44 INFO spark.ExecutorAllocationManager: Request to remove executorIds: 263
19/12/19 17:31:44 INFO spark.ExecutorAllocationManager: Request to remove executorIds: 263
19/12/19 17:31:45 INFO spark.ExecutorAllocationManager: Request to remove executorIds: 263
19/12/19 17:31:45 INFO spark.ExecutorAllocationManager: Request to remove executorIds: 263
19/12/19 17:31:45 INFO spark.ExecutorAllocationManager: Request to remove executorIds: 263
19/12/19 17:31:45 INFO spark.ExecutorAllocationManager: Request to remove executorIds: 263
19/12/19 17:31:45 INFO spark.ExecutorAllocationManager: Request to remove executorIds: 263
19/12/19 17:31:45 INFO spark.ExecutorAllocationManager: Request to remove executorIds: 263
19/12/19 17:31:45 INFO spark.ExecutorAllocationManager: Request to remove executorIds: 263
19/12/19 17:31:45 INFO spark.ExecutorAllocationManager: Request to remove executorIds: 263
19/12/19 17:31:45 INFO spark.ExecutorAllocationManager: Request to remove executorIds: 263
```

In our case, we deployed the spark as a thrift server with DRA enabled.
after this application holds min number executors and all executors arrived expired time, the EAM will repeat send requests for removing executors.

https://github.com/apache/spark/blob/974b024788f1467e10d1b009f0cca6779977ea3e/core/src/main/scala/org/apache/spark/ExecutorAllocationManager.scala#L222-L236

notice that the default value of `intervalMillis` is 100ms.

But these requests don't work, because of the min number executors request. And then EAM will send requests once and once again.

https://github.com/apache/spark/blob/974b024788f1467e10d1b009f0cca6779977ea3e/core/src/main/scala/org/apache/spark/ExecutorAllocationManager.scala#L431-L434

So I think we should set this log level to debug.

**Comment by srowen** [comment]
OK I agree with you. Can you change the message to use string interpolation, if it's a debug message?

**Comment by cfmcgrady** [comment]
ok, updated.

**Comment by cfmcgrady** [comment]
It seems this unit test failed wasn't triggered by this commit.

**Comment by cfmcgrady** [comment]
retest this please.

**Comment by srowen** [comment]
This keeps failing because of the PR builder problem. Because it's so trivial, I'm going to merge it and will take responsibility for making sure the master build is OK.

**Pull request closed without merging**
