### PR TITLE
[SPARK-34225][CORE][FOLLOWUP] Replace Hadoop's Path with Utils.resolveURI to make the way to get URI simple

### PR DESCRIPTION
**Pull request by sarutak**
### What changes were proposed in this pull request?

This PR proposes to replace Hadoop's `Path` with `Utils.resolveURI` to make the way to get URI simple in `SparkContext`.

### Why are the changes needed?

Keep the code simple.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by sarutak** [comment]
cc: @HyukjinKwon

**Review by HyukjinKwon — COMMENTED** [review]
Looks okay to me.

**Comment by sarutak** [comment]
retest this please.

**Review by dongjoon-hyun — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thanks, @sarutak and @HyukjinKwon . Merged to master/3.1.

**Pull request closed without merging**
