### PR TITLE
[SPARK-37102][BUILD] Removed redundant exclusions in `hadoop-cloud` module

### PR DESCRIPTION
**Pull request by vmalakhin**
### What changes were proposed in this pull request?
Redundant exclusions were removed for hadoop-cloud module so the build output contains required dependency for hadoop-azure artifact (ackson-mapper-asl).

### Why are the changes needed?
Currently Hadoop ABFS connector (for Azure Data Lake Storage Gen2) is broken due to missing dependency. So required dependencies for hadoop-azure artifact should be included into distribution output if hadoop-cloud module enabled.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Unfortunately Microsoft does not provide support for Data Lake Storage Gen2 within azurite emulator - so the change was tested manually and the diff was checked to see if anything else was picked up for build outputs (before and after the change). So the only change is inclusion of jackson-mapper-asl-1.9.13.jar.

### CODE REVIEW

**Review by sunchao — COMMENTED** [review]
Thanks, could you add more info to the PR description (esp. why the changes are required), so it can go into the git commit eventually.

**Comment by srowen** [comment]
Jenkins test this please

**Comment by srowen** [comment]
Merged to master

**Comment by dongjoon-hyun** [comment]
Thank you, @vmalakhin , @srowen , @sunchao .

**Pull request closed without merging**
