### PR TITLE
[SPARK-45549][CORE] Remove unused `numExistingExecutors` in `CoarseGrainedSchedulerBackend`

### PR DESCRIPTION
**Pull request by huangxiaopingRD**
### What changes were proposed in this pull request?

Remove unused `numExistingExecutors` in `CoarseGrainedSchedulerBackend`

### Why are the changes needed?
Remove unused code, make spark code cleaner

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
No need test

### Was this patch authored or co-authored using generative AI tooling?
No

### CODE REVIEW

**Comment by mridulm** [comment]
Can you fill in the PR template please ? We can merge this once updated - thanks for catching this

**Comment by huangxiaopingRD** [comment]
> Can you fill in the PR template please ? We can merge this once updated - thanks for catching this

done

**Review by srowen — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by dongjoon-hyun** [comment]
Merged to master. Thank you, @huangxiaopingRD and all.

**Pull request closed without merging**
