### PR TITLE
[SPARK-9959][MLlib] Association Rules Java Compatibility

### PR DESCRIPTION
**Pull request by feynmanliang**
@mengxr

### CODE REVIEW

**Comment by mengxr** [comment]
test this please

**Comment by mengxr** [comment]
LGTM pending Jenkins.

**Comment by feynmanliang** [comment]
jenkins test this please

**Comment by mengxr** [comment]
test this please

**Comment by feynmanliang** [comment]
jenkins test this please

**Comment by mengxr** [comment]
Merged into master and branch-1.5. Thanks!

**Pull request closed without merging**
