### PR TITLE
[SPARK-42486][BUILD] Upgrade `ZooKeeper` to 3.6.4

### PR DESCRIPTION
**Pull request by bjornjorgensen**
### What changes were proposed in this pull request?
Upgrade ZooKeeper from 3.6.3 to 3.6.4

[Release notes](https://zookeeper.apache.org/doc/r3.6.4/releasenotes.html)
### Why are the changes needed?
[ZooKeeper 3.6 is EoL since 30th December, 2022](https://zookeeper.apache.org/releases.html)

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA

### CODE REVIEW

**Comment by bjornjorgensen** [comment]
@yaooqinn you did the last upgrade on this one in https://github.com/apache/spark/pull/38733 will you have a look at this one?

**Review by dongjoon-hyun — COMMENTED** [review]
According to the PR description, does this PR aims to upgrade from one EoL version (3.6.3) to another EoL version (3.6.4), @bjornjorgensen ?
> [ZooKeeper 3.6 is EoL since 30th December, 2022(https://zookeeper.apache.org/releases.html)

**Comment by bjornjorgensen** [comment]
@dongjoon-hyun yes, that's right.
I think we can have this small update now to master and branch 3.4. When 3.4 is released, we can try to update to a newer version.

**Comment by dongjoon-hyun** [comment]
Got it. Thank you for the clarification. Sounds safe.

**Comment by dongjoon-hyun** [comment]
Oh, I missed that you are say `branch-3.4`. Are you sure?
> I think we can have this small update now to master and branch 3.4. When 3.4 is released, we can try to update to a newer version.

If you want to claim this PR as a blocker, you need to do that properly. In general, you had better do two things at least.
- Ping, @xinrong-meng , in order to inform her the existence of the blocker.
- Update SPARK-42486 properly. Currently, the JIRA Affected Version is quite opposite from your comment (or intention) here.

Screenshot 2023-02-19 at 5 15 05 PM

**Review by yaooqinn — APPROVED** [review]

**Comment by bjornjorgensen** [comment]
I did upgrade the JIRA ticket now to include 3.4.0. 
This is not a blocker. 
I think this is more a nice too have upgrade for 3.4.0.

**Comment by dongjoon-hyun** [comment]
I'm not sure new 3.6.4 Zookeepr is urgent or safe in branch-3.4. According to the Maven Central, 3.6.4 is the least adopted (unverified) release among the recent versions. Do we have a test case to support that we need this?

Screenshot 2023-02-20 at 3 30 59 PM

**Comment by HyukjinKwon** [comment]
Let's probably don't add it to branch-3.4 ...

**Comment by xinrong-meng** [comment]
Since branch-3.4 CI is down I may have to re-create the tag later. Please let me know if we shall wait for this PR or not.

**Comment by dongjoon-hyun** [comment]
IMO, we don't need to wait for this PR, @xinrong-meng .

**Comment by xinrong-meng** [comment]
Thanks @dongjoon-hyun!

**Comment by bjornjorgensen** [comment]
Ok, thank you, @dongjoon-hyun

**Pull request closed without merging**
