### PR TITLE
[SPARK-31402][SQL][FOLLOWUP] Refine code comments in RebaseDateTime 

### PR DESCRIPTION
**Pull request by cloud-fan**
### What changes were proposed in this pull request?

Refine the code comments of days rebasing, to be consistent with the micros rebasing. i.e. one method is the actual implementation and the other variant is the optimized version.

### Why are the changes needed?

improve code comments

### Does this PR introduce any user-facing change?

No

### How was this patch tested?

N/A

### CODE REVIEW

**Comment by cloud-fan** [comment]
cc @MaxGekk

**Review by MaxGekk — APPROVED** [review]

**Comment by cloud-fan** [comment]
retest this please

**Comment by cloud-fan** [comment]
retest this please

**Comment by MaxGekk** [comment]
@cloud-fan This is just changes in comments. It can be merged if the build succeed? I just want to avoid rebasing of my other PRs that might conflicts with this PR.

**Comment by cloud-fan** [comment]
yea it's comment only, we don't need to wait for tests. merging to master/3.0!

**Pull request closed without merging**
