### PR TITLE
[SPARK-44310][CONNECT] The Connect Server startup log should display the hostname and port

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to make the Connect Server startup log to display the hostname and port.

### Why are the changes needed?
Displaying hostname and port in logs can make it easier for service providers to provide intuitive information to client users.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
- Pass GA.
- Manually Test.

### CODE REVIEW

**Comment by panbingkun** [comment]
Before:
image

After:
image

**Comment by panbingkun** [comment]
In addition, do we need to define another configuration `CONNECT_GRPC_BINDING_HOSTNAME`? When we have multiple network interface, it may be useful to bind one of them and allow users running only one network segment to access the connect server service through the network.

**Review by hvanhovell — APPROVED** [review]
LGTM

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
