### PR TITLE
[SPARK-41345][CONNECT] Add Hint to Connect Proto

### PR DESCRIPTION
**Pull request by amaliujia**
### What changes were proposed in this pull request?

This PR adds `Hint` to Connect proto.

The Hint technically can accept `ANY` parameter, however in this version of implementation by proto, it is limited to only support literals. As a comparison, PySpark hint API even support a few options ((str, list, float, int))

### Why are the changes needed?

Proto API completeness. 

### Does this PR introduce _any_ user-facing change?

NO

### How was this patch tested?

N/A

### CODE REVIEW

**Comment by amaliujia** [comment]
cc @zhengruifeng

**Comment by zhengruifeng** [comment]
I think `[PROTOBUF]` is used for protobuf connecter

**Comment by zhengruifeng** [comment]
I create https://issues.apache.org/jira/browse/SPARK-41349 for `DataFrame.hint`, please go ahead if someone want a try.

**Review by zhengruifeng — APPROVED** [review]

**Comment by zhengruifeng** [comment]
merged into master

**Pull request closed without merging**
