### PR TITLE
[SPARK-35482][K8S] Use `spark.blockManager.port` not the wrong `spark.blockmanager.port` in BasicExecutorFeatureStep

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

most spark conf keys are case sensitive, including `spark.blockManager.port`, we can not get the correct port number with `spark.blockmanager.port`.

This PR changes the wrong key to `spark.blockManager.port` in `BasicExecutorFeatureStep`.

This PR also ensures a fast fail when the port value is invalid for executor containers. When 0 is specified(it is valid as random port, but invalid as a k8s request), it should not be put in the `containerPort` field of executor pod desc. We do not expect executor pods to continuously fail to create because of invalid requests.

### Why are the changes needed?

bugfix

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

new tests

### CODE REVIEW

**Comment by yaooqinn** [comment]
cc @dongjoon-hyun thanks

**Review by dongjoon-hyun — APPROVED** [review]
Thank you so much again, @yaooqinn !
+1, LGTM. Merged to master/3.1.

**Comment by yaooqinn** [comment]
My pleasure and thanks for merging @dongjoon-hyun !

**Comment by dongjoon-hyun** [comment]
Oh, could you make a backport to `branch-3.0`? There was a conflict.

**Comment by yaooqinn** [comment]
ok

**Pull request closed without merging**
