### PR TITLE
[SPARK-8954] [Build] Remove unneeded deb repository from Dockerfile to fix build error in docker.

### PR DESCRIPTION
**Pull request by yongtang**
[SPARK-8954] [Build] 
1. Remove unneeded deb repository from Dockerfile to fix build error in docker.
2. Remove unneeded /var/lib/apt/lists/\* after install to reduce the docker image size (by ~30MB).

### CODE REVIEW

**Comment by JoshRosen** [comment]
Wow, I didn't know that anyone actually used these Dockerfiles.  If someone tests this and confirms that it works, then I think it's fine to merge this.

**Comment by yongtang** [comment]
@JoshRosen 

The test was done with the following:
1. Installed doker first (on Ubuntu 14.04):
```sh
wget -qO- https://get.docker.com/ | sh
```
2. Place the following script in spark directory:
```sh
#!bin/bash

set -xe
sudo docker build -t spark-test-base   docker/spark-test/base/
sudo docker build -t spark-test-master docker/spark-test/master/
sudo docker build -t spark-test-worker docker/spark-test/worker/
```
3. On mater branch you will encounter an error as there is a conflict with package openjdk-7-jre-headless and tzdata-java.
4. On patched one the script will complete successfully.

Please let me know if there is any issues.

Thanks

**Comment by JoshRosen** [comment]
SGTM; I'm going to pull this into master.

**Comment by JoshRosen** [comment]
This has been merged but GitHub was unable to mark this pull request as closed due to some issues in the ASF's GitHub mirroring infrastructure.  To help us keep the PR review queue in a clean state, do you mind closing this pull request? I'd do it myself but don't have the required admin permissions.

**Comment by yongtang** [comment]
Sure, thanks for the review and help.

**Pull request closed without merging**
