### PR TITLE
[SPARK-47860][BUILD][K8S] Upgrade `kubernetes-client` to 6.12.0

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to upgrade `kubernetes-client` to 6.12.0.

### Why are the changes needed?

To bring the latest bug fixes.
- https://github.com/fabric8io/kubernetes-client/releases/tag/v6.12.0

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the CIs.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
All K8s-related unit tests and integration tests passed.

**Comment by dongjoon-hyun** [comment]
Could you review this K8s PR, @huaxingao ?

**Review by huaxingao — APPROVED** [review]
LGTM. Thanks for the PR @dongjoon-hyun

**Comment by dongjoon-hyun** [comment]
Thank you, @huaxingao . Merged to master for Apache Spark 4.0.

**Pull request closed without merging**
