### PR TITLE
[SPARK-18244][SQL] Rename partitionProviderIsHive -> tracksPartitionsInCatalog

### PR DESCRIPTION
**Pull request by rxin**
## What changes were proposed in this pull request?
This patch renames partitionProviderIsHive to tracksPartitionsInCatalog, as the old name was too Hive specific.

## How was this patch tested?
Should be covered by existing tests.

### CODE REVIEW

**Comment by rxin** [comment]
cc @cloud-fan, @ericl, and @mallman

**Comment by cloud-fan** [comment]
LGTM

**Comment by ericl** [comment]
Lgtm

**Comment by rxin** [comment]
Merging in master/branch-2.1.

**Pull request closed without merging**
