### PR TITLE
[MINOR][DOCS] Clarify collect_list and collect_set -> ArrayType

### PR DESCRIPTION
**Pull request by landlord-matt**
### What changes were proposed in this pull request?

This PR clarifies that collect_list and collect_set return a standard [ArrayType ](https://spark.apache.org/docs/3.5.0/api/python/reference/pyspark.sql/api/pyspark.sql.types.ArrayType.html)s and not some new special list or set type.

### Why are the changes needed?

The current description causes confusion about what type this function returns. This change makes it more in line with [the Databricks versions for collect_list](https://docs.databricks.com/en/sql/language-manual/functions/collect_list.html) and [collect_set ](https://docs.databricks.com/en/sql/language-manual/functions/collect_set.html) as well. 

### Does this PR introduce _any_ user-facing change?

It improves the documentation

### How was this patch tested?

Not applicable

### Was this patch authored or co-authored using generative AI tooling?

No

### CODE REVIEW

**Comment by landlord-matt** [comment]
@HyukjinKwon: I now also did a similar thing for collect_set. Any comments on the proposal? I thought you would appreciate this suggestion :'(

**Comment by zhengruifeng** [comment]
I personally think using `list` is fine, `array` in python reminds me of python built-in `array` library and numpy's array

**Comment by landlord-matt** [comment]
@zhengruifeng: Interesting, because the problem I had was that Python has the built in types list and set and they have different properties. If I declare a variable as a set, it will ignore duplicates going forward, but if I declare it a list, it will accept it. In Java/Scala they differentiate arrays, lists and sets. 

I think the naming refers to that the collection step behaves like a list or a set, but it returns a standard array and will behave like a standard array in subsequent steps. If you have memorized the available types in Spark, it is perhaps obvious that it will be an ArrayType, but I think I think the documentation should be clear on the specific return type for beginners as well. 

How about if we use the official terminology ArrayType? They it is not possible to associate it with other arrays in Python.

```    
def collect_list(col: "ColumnOrName") -> Column:
    """
    Aggregate function: Collects the values from a column into a list,
    maintaining duplicates, and returns this list of objects as an ArrayType.

    [...]

    Returns
    -------
    :class:`~pyspark.sql.Column`
        A new Column object representing a list of collected values as an ArrayType, duplicates excluded.
```

**Comment by landlord-matt** [comment]
This is how other functions have solved this

```python
@_try_remote_functions
def find_in_set(str: "ColumnOrName", str_array: "ColumnOrName") -> Column:
    """
    Returns the index (1-based) of the given string (`str`) in the comma-delimited
    list (`strArray`). Returns 0, if the string was not found or if the given string (`str`)
    contains a comma.

    .. versionadded:: 3.5.0
```
    
```python
def split(str: "ColumnOrName", pattern: str, limit: int = -1) -> Column:
    """
    Splits str around matches of the given pattern.
    Returns
    -------
    :class:`~pyspark.sql.Column`
        array of separated strings.
```

**Pull request closed without merging**
