### PR TITLE
[WIP][SPARK-33880][BUILD] Replace Hadoop profile names by using hadoop-2 and hadoop-3

### PR DESCRIPTION
**Pull request by sunchao**
### What changes were proposed in this pull request?

Rename Maven profile names: `hadoop-3.2` to `hadoop-3` and `hadoop-2.7` to `hadoop-2`.

### Why are the changes needed?

Currently we use Hadoop profile names hadoop-3.2 and hadoop-2.7. However as we evolve and upgrade these versions, such as upgrading Hadoop version to 3.3.1, these will become confusing. This proposes to replace the profile names with hadoop-3 and hadoop-2 respectively.

### Does this PR introduce _any_ user-facing change?

Yes. In future they will need to use the new profile when building Spark.

### How was this patch tested?

N/A

### CODE REVIEW

**Comment by sunchao** [comment]
I think we can also replace Hive profile names from `hive-2.3` to, perhaps `hive-2`? given that we may want to start supporting Hive 3.x or 4.x in future. Will take some suggestions.

**Comment by dongjoon-hyun** [comment]
For the Hive, let's do that later, @sunchao , because it's orthogonal.
> I think we can also replace Hive profile names from hive-2.3 to, perhaps hive-2? given that we may want to start supporting Hive 3.x or 4.x in future. Will take some suggestions.

**Comment by xkrogen** [comment]
In the past we've simultaneously had profiles for multiple Hadoop versions, such as 2.6 and 2.7. At one point we even had 5 different profiles from the 2.X line. Unless our confidence is very high that we would never need multiple Hadoop profiles from the 3.X line, I'm against this change. I am concerned it will cause us to unnecessarily only support a single 3.X line when multiple simultaneous profiles could allow a broader range of support.

@sunchao do you have any thoughts on why things might be different now as opposed to the history of Spark when many Hadoop 2.X profiles were supported? Faster release cadence of Hadoop, stronger compatibility guarantees, etc.?

**Comment by sunchao** [comment]
> @sunchao do you have any thoughts on why things might be different now as opposed to the history of Spark when many Hadoop 2.X profiles were supported? Faster release cadence of Hadoop, stronger compatibility guarantees, etc.?

@xkrogen other Hadoop versions can still be supported via the property `hadoop.version`. The `hadoop-2.7` and `hadoop-3.2` are just used to differentiate between 2 and 3, if I understand it correctly. For instance, building with:
```
./build/mvn -Phadoop-3.2 -Dhadoop.version=3.3.0 -DskipTests clean package
```
will build Spark against Hadoop 3.3.0.

**Comment by xkrogen** [comment]
That assumes no other profile changes are necessary to run against 3.2 vs. 3.3. For example, here is a snapshot of the 2.6 and 2.7 profiles from 2018:
```
    <profile>
      <id>hadoop-2.6</id>
      <!-- Default hadoop profile. Uses global properties. -->
    </profile>

    <profile>
      <id>hadoop-2.7</id>
      <properties>
        <hadoop.version>2.7.3</hadoop.version>
        <curator.version>2.7.1</curator.version>
      </properties>
    </profile>
```
In this case, using `-Phadoop-2.7 -Dhadoop.version=2.6.1` would be insufficient since there are other profile changes necessary (the curator version). 

Back in 2015 the situation required even more tweaking:
```
    <profile>
      <id>hadoop-2.2</id>
    <!-- SPARK-7249: Default hadoop profile. Uses global properties. -->
    </profile>

    <profile>
      <id>hadoop-2.3</id>
      <properties>
        <hadoop.version>2.3.0</hadoop.version>
        <jets3t.version>0.9.3</jets3t.version>
      </properties>
    </profile>

    <profile>
      <id>hadoop-2.4</id>
      <properties>
        <hadoop.version>2.4.0</hadoop.version>
        <jets3t.version>0.9.3</jets3t.version>
      </properties>
    </profile>

    <profile>
      <id>hadoop-2.6</id>
      <properties>
        <hadoop.version>2.6.0</hadoop.version>
        <jets3t.version>0.9.3</jets3t.version>
        <zookeeper.version>3.4.6</zookeeper.version>
        <curator.version>2.6.0</curator.version>
      </properties>
    </profile>
```

This is why I bring up the compatibility of Hadoop these days. If we squash it down to a single `hadoop-3` profile, this makes the assumption that all Hadoop versions in the 3.X line will have completely compatible dependency trees.

**Comment by sunchao** [comment]
Thanks for bringing this up - I was not aware of the history there. @dongjoon-hyun do you know why we removed all the other Hadoop profiles?

I'm not sure if Spark community has intention to support another Hadoop 2.x version in future since at one point there was discussion to deprecate Hadoop 2.7, as Hadoop 2.x lines have mostly reached their EOL. On the other hand, I'm hoping that with shaded Hadoop client [(SPARK-33212](https://issues.apache.org/jira/browse/SPARK-33212)) we can avoid the dependency tweaks in separate Hadoop profiles.

**Comment by dongjoon-hyun** [comment]
Hi, @xkrogen . We had multiple profiles at that age and your concern is still valid. However, for a long time, Apache Spark community has been rejected multiple PRs which aims to add a new profile and insists to keep only two profiles (2.x and 3.x). Due to the maintenance burdens, Apache Spark community only focuses on two profiles and it will be the same in the future.
> In the past we've simultaneously had profiles for multiple Hadoop versions, such as 2.6 and 2.7. At one point we even had 5 different profiles from the 2.X line. Unless our confidence is very high that we would never need multiple Hadoop profiles from the 3.X line, I'm against this change. I am concerned it will cause us to unnecessarily only support a single 3.X line when multiple simultaneous profiles could allow a broader range of support.

I'm supporting this PR.

**Comment by dongjoon-hyun** [comment]
BTW, @sunchao , could you send an email to dev mailing list to collect more opinion on this? Like @xkrogen said, this is an important change.

**Comment by sunchao** [comment]
@dongjoon-hyun sure I can do that.

**Comment by xkrogen** [comment]
Thanks for the input @dongjoon-hyun ! Makes sense to me. Assuming we only maintain 2 profiles, I completely agree they should be labeled as `hadoop-2` and `hadoop-3` to more clearly indicate that there is only expected to be one profile per major version.

**Comment by HyukjinKwon** [comment]
Hm, since we upgraded Hadoop to 3.3.1, we might need to think about renaming too. @sunchao is there any plan on this renmaing?

**Comment by sunchao** [comment]
@HyukjinKwon I sent out an email to dev mailing list on this topic and the conclusion there is to do this in the Spark 3.3.0 time frame. I plan to pick this up again after 3.2.0 release is done.

**Comment by HyukjinKwon** [comment]
Thanks!

**Pull request closed without merging**
