### PR TITLE
[SPARK-23601][BUILD] Remove .md5 files from release

### PR DESCRIPTION
**Pull request by srowen**
## What changes were proposed in this pull request?

Remove .md5 files from release artifacts

## How was this patch tested?

N/A

### CODE REVIEW

**Comment by felixcheung** [comment]
The last part with publishing to staging repo (“publish-release”) might not work?

When I did I added a new file .sha512 and it failed the publish, so I wonder if it is specifically looking for certain file extensions. Although I have not tried publishing without the .md5 file or that might have changed now also.

LGTM otherwise

**Review by holdenk — APPROVED** [review]
LGTM

**Review by felixcheung — APPROVED** [review]

**Comment by srowen** [comment]
@felixcheung yeah I don't see any more references to .md5 files now; certainly I don't see anything in the script that would fail if it's not there. I also don't know of any process at the ASF or Nexus that should care about it. I suppose it's one of those things we'd find out next time; not sure if there's any way to test that part of the release process without actually releasing.

**Comment by srowen** [comment]
Merged to master/2.3

**Pull request closed without merging**
