### PR TITLE
[SPARK-26826][SQL] Array indexing functions

### PR DESCRIPTION
**Pull request by zecevicp**
## What changes were proposed in this pull request?

This PR proposes two extra array functions: `array_allpositions` (named after `array_position`) and `array_select`. These functions should make it easier to:
- get an array of indices of all occurences of a value in an array (`array_allpositions`)
- select all elements of an array based on an array of indices (`array_select`)

Although higher-order functions, such as `aggregate` and `transform`, have been recently added, performing tasks above is still not simple, hence this addition.

## How was this patch tested?
Unit tests

### CODE REVIEW

**Comment by mgaido91** [comment]
we usually add new functions only if they are adopted in the most well-known DBs, for feature parity and making easier for people to migrate their queries. I haven't found any DB supporting these 2. So I don't think we are going to have them in.

**Comment by zecevicp** [comment]
There was a short discussion on the dev group where I received some support for this.

**Comment by srowen** [comment]
Same reply as in my email -- I don't think we would add these unless they're in Hive or standard SQL. I didn't see other replies?

**Comment by maropu** [comment]
+1 for the @mgaido91 / @srowen suggestion.

**Comment by zecevicp** [comment]
OK, closing the PR...

**Pull request closed without merging**
