### PR TITLE
[CI] Check if tests are to be run for build and pyspark matrix jobs

### PR DESCRIPTION
**Pull request by EnricoMi**
### What changes were proposed in this pull request?
This makes the CI aware when instances of matrix jobs `build` and `pyspark` do actually not have any changes and there do not run any tests. Then, uploading files can be skipped as well, allowing to enable #36413.

This also makes the fact visible that tests for a matrix job are actually not run:
grafik
Though the job itself is run, the test step is skipped. Before, you would have to open the test step and see no tests were run.

Ideally, the whole job should be skipped. But that would require defining the module sets into the `precondition` job.

### Why are the changes needed?
All instances of matrix jobs `build` and `pyspark` are skipped if none of their respective modules have changes. When changes exists, all instances are run, but some instances then do not run any tests, as their sub-set of modules do not have changes.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Tested here:
- Run without changes (root being removed from changes): https://github.com/G-Research/spark/actions/runs/2511343840
- Run with pyspark changes: https://github.com/G-Research/spark/actions/runs/2511754796
- Run with streaming changes: https://github.com/G-Research/spark/actions/runs/2511785981

### CODE REVIEW

**Comment by EnricoMi** [comment]
@HyukjinKwon do you agree that ideally, the subset of modules build and tested in matrix jobs should be defined in `precondition` job, where it can check each subset for changes and then configure the matrix strategy and skip respective jobs? Than all this magic happens in one place.

**Comment by HyukjinKwon** [comment]
Yeah, I think ideally all has to be skipped properly at precondition, and your previous fix makes sense.

**Comment by HyukjinKwon** [comment]
Yeah, would that need a very big change? If we can make the change surgically, that would be great.

**Comment by EnricoMi** [comment]
I wouldn't call it surgically, more a rework :-/

**Comment by EnricoMi** [comment]
This is the most surgically I could get. Individual matrix jobs cannot be skipped (which I would have preferred) because the `job.<job-id>.if` field cannot evaluate `matrix`, so there is no way to have individual conditions (e.g. sql being skipped entirely while core being tested).

If you are happy with it, I'll create a corresponding JIRA. If not, please feel free to close this.

**Comment by HyukjinKwon** [comment]
> I wouldn't call it surgically, more a rework :-/

Ah, now I got your point. So `precondition` defines the modules to build/test, and the following jobs actully test/build those modules (from `precondition`)   .... I think it sounds like it would be a great improvement.

**Comment by EnricoMi** [comment]
Yes, the idea was to define the strategy matrix as JSON in `precondition`. GitHub gives this working example:
https://docs.github.com/en/actions/learn-github-actions/expressions#fromjson

Then, module sets would be defined once in one place. There, it could run `is-changed.py` for each of the module sets and add that to the JSON. Here is a sketch: https://docs.github.com/en/actions/learn-github-actions/expressions#fromjson

Ideally, individual jobs of the `build` and `pyspark` matrix then would be skipped as easily as this:
```yaml
build:
  strategy:
    matrix: ${{ fromJSON( needs.precondition.outputs.spark-matrix ) }}
  if: matrix.run != 'false' && matrix.changed != 'false'
```

But this is not allowed, `matrix` does not work in the `if` clause: https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability

**Pull request closed without merging**
