### PR TITLE
[SPARK-11030] [SQL] share the SQLTab across sessions

### PR DESCRIPTION
**Pull request by davies**
The SQLTab will be shared by multiple sessions.

If we create multiple independent SQLContexts (not using newSession()), will still see multiple SQLTabs in the Spark UI.

### CODE REVIEW

**Comment by davies** [comment]
ping @zsxwing

**Comment by zsxwing** [comment]
LGTM

**Comment by yhuai** [comment]
LGTM

**Comment by yhuai** [comment]
Thanks! Merging to master.

**Pull request closed without merging**
