### PR TITLE
[SPARK-18958][SPARKR] R API toJSON on DataFrame

### PR DESCRIPTION
**Pull request by felixcheung**
## What changes were proposed in this pull request?

It would make it easier to integrate with other component expecting row-based JSON format.
This replaces the non-public toJSON RDD API.

## How was this patch tested?

manual, unit tests

### CODE REVIEW

**Comment by shivaram** [comment]
LGTM. Thanks @felixcheung

**Comment by shivaram** [comment]
Merging this into master, branch-2.0

**Comment by shivaram** [comment]
Hmm looks like this is merged but not reflected on github ?

**Comment by felixcheung** [comment]
I kept getting error with the merge script - not sure if it went through. we are likely having some sync issue with github?

**Comment by felixcheung** [comment]
ah, it was merged https://git-wip-us.apache.org/repos/asf?p=spark.git

**Pull request closed without merging**
