### PR TITLE
[SPARK-911] allow efficient queries for a range if RDD is partitioned wi...

### PR DESCRIPTION
**Pull request by aaronjosephs**
...th RangePartitioner

### CODE REVIEW

**Comment by andrewor14** [comment]
@aaronjosephs @JoshRosen what is the status of this PR? Is it blocking on more reviews? Although it's old it doesn't seem outdated since this touches a fairly isolated portion of the code.

**Comment by aaronjosephs** [comment]
@andrewor14 at some point @JoshRosen had said he had finished and would commit the next day so that is probably the solution we should go with

**Comment by srowen** [comment]
@aaronjosephs OK although the patch now needs a rebase. Can you bring it up to date and we can see what Jenkins thinks?

**Comment by aaronjosephs** [comment]
@srowen OK pushing with Josh's suggested changes

**Comment by andrewor14** [comment]
ok to test

**Comment by srowen** [comment]
Jenkins, retest this please

**Comment by aaronjosephs** [comment]
@srowen re-pushed because I accidentally deleted some of the docs for repartition and shuffle within partitions, don't know if you want to retest

**Comment by srowen** [comment]
Back to @JoshRosen for a final look; it looks good to me eyes. How about another test for a case where the range begins and ends in the middle of a partition? right now it looks like there are 10 partitions, a multiple of 10 elements, and filter range always starts and ends on a multiple of 10.

**Comment by aaronjosephs** [comment]
@srowen pushed a test with data in the middle of the partitions, retest

**Comment by srowen** [comment]
ok to test

**Comment by srowen** [comment]
Looks good to me and I assume it's OK with Josh since it's basically the code he suggested. I'll wait a short while for more comments before merging, if Josh doesn't first. Let's also see what Jenkins says one last time.

**Comment by JoshRosen** [comment]
LGTM, so I'm going to merge this into `master` (1.4.0).  Thanks!

**Pull request closed without merging**
