### PR TITLE
[SPARK-49292][BUILD] Upgrade dropwizard metrics to 4.2.27

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr aims to upgrade dropwizard metrics from 4.2.26 to  4.2.27.

### Why are the changes needed?
From the code diff, this version mainly upgrades the project dependencies.

- https://github.com/dropwizard/metrics/compare/v4.2.26...v4.2.27

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass GitHub Actions

### Was this patch authored or co-authored using generative AI tooling?
No

### CODE REVIEW

**Comment by LuciferYang** [comment]
Test first

**Comment by dongjoon-hyun** [comment]
It looks good to go. Could you update the PR description, @LuciferYang ?

**Comment by LuciferYang** [comment]
> It looks good to go. Could you update the PR description, @LuciferYang ?

done

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you for informing that, @LuciferYang . Ya, it looks safe to me.
Merged to master.

**Comment by LuciferYang** [comment]
Thanks @dongjoon-hyun

**Pull request closed without merging**
