### PR TITLE
[SPARK-8158] [SQL] several fix for HiveShim

### PR DESCRIPTION
**Pull request by adrian-wang**
1. explicitly import implicit conversion support.
2. use .nonEmpty instead of .size > 0
3. use val instead of var
4. comment indention

### CODE REVIEW

**Comment by rxin** [comment]
LGTM

**Comment by adrian-wang** [comment]
retest this please.

**Comment by adrian-wang** [comment]
retest this please.

**Comment by vanzin** [comment]
#6604?

**Comment by rxin** [comment]
I've merged this. Thanks.

**Pull request closed without merging**
