### PR TITLE
[SPARK-38244][K8S][BUILD] Upgrade kubernetes-client to 5.12.1

### PR DESCRIPTION
**Pull request by Yikun**
### What changes were proposed in this pull request?
Upgrade kubernetes-client to 5.12.1:
Changes list:
- https://github.com/fabric8io/kubernetes-client/releases/tag/v5.12.1
- https://github.com/fabric8io/kubernetes-client/commit/81c11ca5c2044eac2cbebe5107945ec95011e8f4

### Why are the changes needed?
The next kubernetes client version will be 6.x with breaking changes: https://github.com/fabric8io/kubernetes-client/blob/master/CHANGELOG.md#note-breaking-changes-in-the-api .

We'd better to upgrade to latest 5.X to reduce follow upgrade cost.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
- CI
- integration test

### CODE REVIEW

**Comment by Yikun** [comment]
I will mark this as `Ready for review` after https://github.com/apache/spark/pull/35595 merged.

**Comment by dongjoon-hyun** [comment]
Please rebase and test this on `master` branch and let us know.

**Comment by Yikun** [comment]
@dongjoon-hyun Thanks, I will address this soon.

**Comment by dongjoon-hyun** [comment]
Gentle ping, @Yikun .

**Comment by Yikun** [comment]
```
[info] KubernetesSuite:
[info] - Run SparkPi with no resources (35 seconds, 626 milliseconds)
[info] - Run SparkPi with no resources & statefulset allocation (33 seconds, 379 milliseconds)
[info] - Run SparkPi with a very long application name. (28 seconds, 98 milliseconds)
[info] - Use SparkLauncher.NO_RESOURCE (27 seconds, 857 milliseconds)
[info] - Run SparkPi with a master URL without a scheme. (34 seconds, 460 milliseconds)
[info] - Run SparkPi with an argument. (27 seconds, 696 milliseconds)
[info] - Run SparkPi with custom labels, annotations, and environment variables. (26 seconds, 592 milliseconds)
[info] - All pods have the same service account by default (24 seconds, 373 milliseconds)
[info] - Run extraJVMOptions check on driver (17 seconds, 118 milliseconds)
[info] - Run SparkRemoteFileTest using a remote data file (25 seconds, 69 milliseconds)
[info] - Verify logging configuration is picked from the provided SPARK_CONF_DIR/log4j2.properties (37 seconds, 38 milliseconds)
[info] - Run SparkPi with env and mount secrets. (37 seconds, 323 milliseconds)
[info] - Run PySpark on simple pi.py example (21 seconds, 882 milliseconds)
[info] - Run PySpark to test a pyfiles example (27 seconds, 241 milliseconds)
[info] - Run PySpark with memory customization (22 seconds, 228 milliseconds)
[info] - Run in client mode. (11 seconds, 549 milliseconds)
[info] - Start pod creation from template (23 seconds, 572 milliseconds)
[info] - Test basic decommissioning (1 minute, 21 seconds)
[info] - Test basic decommissioning with shuffle cleanup (1 minute, 23 seconds)
[info] - Test decommissioning with dynamic allocation & shuffle cleanups (3 minutes, 2 seconds)
[info] - Test decommissioning timeouts (1 minute, 23 seconds)
[info] - SPARK-37576: Rolling decommissioning (1 minute, 20 seconds)
[info] VolcanoSuite:
[info] - Run SparkPi with volcano scheduler (28 seconds, 793 milliseconds)
```

Test on k8s with docker-desktop

**Comment by Yikun** [comment]
@dongjoon-hyun Sorry for late update, rebase, test and ready to go!

**Comment by dongjoon-hyun** [comment]
Thank you for re-verification, @Yikun .

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by dongjoon-hyun** [comment]
Merged to master again for Apache Spark 3.3.0.

**Pull request closed without merging**
