### PR TITLE
[SPARK-20649][core] Simplify REST API resource structure.

### PR DESCRIPTION
**Pull request by vanzin**
With the new UI store, the API resource classes have a lot less code,
since there's no need for complicated translations between the UI
types and the API types. So the code ended up with a bunch of files
with a single method declared in them.

This change re-structures the API code so that it uses less classes;
mainly, most sub-resources were removed, and the code to deal with
single-attempt and multi-attempt apps was simplified.

The only change was the addition of a method to return a single
attempt's information; that was missing in the old API, so trying
to retrieve "/v1/applications/appId/attemptId" would result in a
404 even if the attempt existed (and URIs under that one would
return valid data).

The streaming API resources also overtook the same treatment, even
though the data is not stored in the new UI store.

### CODE REVIEW

**Comment by vanzin** [comment]
For context:

*Project link: https://issues.apache.org/jira/browse/SPARK-18085
* Upcoming PRs that build on this code: https://github.com/vanzin/spark/pulls

**Comment by squito** [comment]
lgtm

**Comment by squito** [comment]
merged to master

**Comment by bsikander** [comment]
Is this issue related to this PR?
https://issues.apache.org/jira/browse/SPARK-30686

**Pull request closed without merging**
