### PR TITLE
[BackPort-2.1][SPARK-19319][SparkR]:SparkR Kmeans summary returns error when the cluster size doesn't equal to k

### PR DESCRIPTION
**Pull request by wangmiao1981**
## What changes were proposed in this pull request?

Backport fix of #16666 

## How was this patch tested?

Backport unit tests

### CODE REVIEW

**Comment by felixcheung** [comment]
hmm, I wasn't sure to have the parameter changes in 2.1, what do you think?

**Comment by wangmiao1981** [comment]
If we don't want to change the parameters in 2.1, it is not necessary to port it back. It is because the bug occurs only if you use `random` mode with specific `seed`. If we don't provide seed, with default seed, it should be fine. In the future, if there is a case with default seed has problem, we can fix it again.

Thanks!

**Comment by felixcheung** [comment]
merged to 2.1. Thanks @wangmiao1981 please close this PR.

**Comment by felixcheung** [comment]
ping @wangmiao1981 please close this PR - backport PR merged to non-master branch isn't closed automatically.

**Comment by wangmiao1981** [comment]
Thanks! I close it.

**Pull request closed without merging**
