### PR TITLE
[SPARK-23907][SQL] Revert regr_* functions entirely

### PR DESCRIPTION
**Pull request by rxin**
## What changes were proposed in this pull request?
This patch reverts entirely all the regr_* functions added in SPARK-23907. These were added by @mgaido91 (and proposed by @gatorsmile) to improve compatibility with other database systems, without any actual use cases. However, they are very rarely used, and in Spark there are much better ways to compute these functions, due to Spark's flexibility in exposing real programming APIs.

I'm going through all the APIs added in Spark 2.4 and I think we should revert these. If there are strong enough demands and more use cases, we can add them back in the future pretty easily.

## How was this patch tested?
Reverted test cases also.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by HyukjinKwon** [comment]
I'm supportive of this change.

**Review by gatorsmile — COMMENTED** [review]
LGTM

Had an offline discussion with Reynold. Although the other commercial database have these ASNI SQL compliant functions, our Spark SQL users do not have these specific requirements yet. Let us revert these changes from the code base.

**Comment by dilipbiswal** [comment]
retest this please

**Review by HyukjinKwon — APPROVED** [review]
LGTM2

**Comment by HyukjinKwon** [comment]
Merged to master and branch-2.4.

**Pull request closed without merging**
