### PR TITLE
[SPARK-29618] remove V1_BATCH_WRITE table capability

### PR DESCRIPTION
**Pull request by cloud-fan**
### What changes were proposed in this pull request?

Build the `BatchWrite` in the planner and get rid of the `V1_BATCH_WRITE` table capability.

### Why are the changes needed?

It's always better to make the API simpler and easier to implement. When I was working on v1 read fallback API at https://github.com/apache/spark/pull/26231 , I realized that we don't need a table capability for it, because we create the `Scan` object in the planner. We can do the same thing for v1 write fallback API as well.

This can also reduce duplicated code of creating the `WriteBuilder`.

### Does this PR introduce any user-facing change?

no

### How was this patch tested?

existing tests

### CODE REVIEW

**Comment by cloud-fan** [comment]
cc @brkyvz @rdblue

**Comment by cloud-fan** [comment]
A related topic: https://github.com/apache/spark/pull/25990 suggests that we should pass some physical information when creating `Write`. This makes me think if we should have logical and physical write as the read side API does. We create the logical write in the planner, and the physical plan creates physical write given some physical information.

**Comment by brkyvz** [comment]
Until we support Table creation through V2 in DataFrameWriter.save, I'm a -1 on this.

**Comment by cloud-fan** [comment]
I don't get your point. The only change to data source developers is that, they don't need to specify the `V1_BATCH_WRITE` table capability when they implement v1 flalback write (`V1WriteBuilder`). This is a pure simplification to DS v2 implementations that need v1 fallback write.

How is it related to "Table creation through V2 in DataFrameWriter.save"?

**Pull request closed without merging**
