### PR TITLE
[SPARK-44672][INFRA] Fix git ignore rules related to Antlr

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
https://github.com/apache/spark/pull/41928 moved antlr4 related files and directories from the `sql/catalyst` module to the `sql/api` module. This pr fix the corresponding git ignore rules to avoid unexpected diffs when executing `git status`.

### Why are the changes needed?
Avoid unexpected diffs when executing `git status`.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
- Manual check `git status`

**Before**

```
sql/api/gen/
sql/api/src/main/antlr4/org/apache/spark/sql/catalyst/parser/gen/
```

**After**
no diff.

### CODE REVIEW

**Comment by LuciferYang** [comment]
cc @amaliujia @HyukjinKwon @zhengruifeng

**Review by zhengruifeng — APPROVED** [review]

**Review by cxzl25 — APPROVED** [review]
Just ran into this problem.

**Review by wangyum — APPROVED** [review]

**Review by yaooqinn — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Merged to master/3.5. Thank you.

**Comment by amaliujia** [comment]
late LGTM thank you!

**Comment by LuciferYang** [comment]
Thanks @dongjoon-hyun @wangyum @zhengruifeng @yaooqinn @cxzl25 and @amaliujia ~

**Pull request closed without merging**
