### PR TITLE
[SPARK-27173][SQL]Remove （lz4，brotli，zstd）  for hive parquet table

### PR DESCRIPTION
**Pull request by 10110346**
## What changes were proposed in this pull request?

From parquet.hadoop.metadata.CompressionCodecName(parquet-hadoop-bundle-1.6.0.jar ), we can know, for hive parquet table, it only supports snappy, gzip and lzo.
This PR removes （lz4，brotli，zstd）  for hive parquet table

### CODE REVIEW

**Review by felixcheung — COMMENTED** [review]
is this only for hive table? in that case, why check here and not hive should check for this?

**Comment by 10110346** [comment]
> 
> 
> is this only for hive table? in that case, why check here and not hive should check for this?

Yes, it is only for hive table , spark parquet table supports（lz4，brotli，zstd）,and it  is checked in  `ParquetOptions.scala`. 
Thanks.

**Review by wangyum — COMMENTED** [review]
Does `parquet-hadoop-bundle-1.10.1.jar` support these compression codecs?

**Comment by 10110346** [comment]
> 
> 
> Does `parquet-hadoop-bundle-1.10.1.jar` support these compression codecs?

Yeah, it  supports these

**Pull request closed without merging**
