### PR TITLE
[SPARK-12101][CORE] Fix thread pools that cannot cache tasks in Worker and AppClient (backport 1.5)

### PR DESCRIPTION
**Pull request by zsxwing**
backport #10108 to branch 1.5

### CODE REVIEW

**Comment by zsxwing** [comment]
retest this please

**Comment by zsxwing** [comment]
retest this please

**Comment by srowen** [comment]
Looks correct as a back-port of the other PR

**Comment by zsxwing** [comment]
CC @andrewor14

**Comment by zsxwing** [comment]
Merging to 1.5

**Pull request closed without merging**
