### PR TITLE
[SPARK-49595][CONNECT][SQL] Fix `DataFrame.unpivot/melt` in Spark Connect Scala Client

### PR DESCRIPTION
**Pull request by xinrong-meng**
### What changes were proposed in this pull request?
Fix DataFrame.unpivot/melt in Spark Connect Scala Client by correctly assigning the name for the variable column.

The original code used `setValueColumnName` for both the variable and value columns.

### Why are the changes needed?
This fix is necessary to ensure the correct behavior of the unpivot/melt operation. 

### Does this PR introduce _any_ user-facing change?
Yes. Variable and value columns can be set correctly as shown below.

```scala
scala> val df = Seq((1, 11, 12L), (2, 21, 22L)).toDF("id", "int", "long") 
df: org.apache.spark.sql.package.DataFrame = [id: int, int: int ... 1 more field]

scala> df.show() 
+---+---+----+
| id|int|long|
+---+---+----+
|  1| 11|  12|
|  2| 21|  22|
+---+---+----+
```
FROM (current master)
```scala
scala> df.unpivot(Array($"id"), Array($"int", $"long"), "variable", "value").show()  
+---+----+-----+
| id|    |value|
+---+----+-----+
|  1| int|   11|
|  1|long|   12|
|  2| int|   21|
|  2|long|   22|
+---+----+-----+

```

TO
```scala
scala> df.unpivot(Array($"id"), Array($"int", $"long"), "variable", "value").show() 
+---+--------+-----+
| id|variable|value|
+---+--------+-----+
|  1|     int|   11|
|  1|    long|   12|
|  2|     int|   21|
|  2|    long|   22|
+---+--------+-----+
```

### How was this patch tested?
Existing tests.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Review by zhengruifeng — APPROVED** [review]

**Review by hvanhovell — APPROVED** [review]
LGTM! Nice fix!

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Merged to master for Apache Spark 4.0.0-preview2.

Ya, please make a backporting PR to verify all CIs in branch-3.5.

**Comment by dongjoon-hyun** [comment]
Oh, I realized that the original code is in the following since Apache Spark 3.4.0.
- #40019

**Comment by dongjoon-hyun** [comment]
I backported this to branch-3.5/branch-3.4 after manual testing.

**Comment by xinrong-meng** [comment]
@dongjoon-hyun thank you so much for handling the backport!

Thank you @hvanhovell and @zhengruifeng for review.

**Pull request closed without merging**
