### PR TITLE
[SPARK-32248][BUILD] Recover Java 11 build in Github Actions

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to recover Java 11 build in `GitHub Action`.

### Why are the changes needed?

This test coverage is removed before. Now, it's time to recover it.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the GitHub Action.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
cc @HyukjinKwon

**Review by HyukjinKwon — APPROVED** [review]
I was worried about this JDK 11 build removed so I am okay to revive this for the time being. Looks good.

For the long term plan, I was actually thinking about:
- Copy Jenkins periodical jobs at https://amplab.cs.berkeley.edu/jenkins/ to GitHub Actions periodical jobs.
- Add a way to test JDK 11, JDK 8, Hive 1.2, Hive 2.3, Hadoop 2 and Hadoop 3 via PR title or tag (seems feasible). We we will run one default job but have a way to configure the profiles.

I was thinking that JDK 11 build will eventually live in the periodical builds (unless we change the default JDK and profiles). Does this plan make sense?

**Comment by dongjoon-hyun** [comment]
Sure. That sounds like a plan. We can get a freedom if we get more resource limit in GitHub Action. Thanks, @HyukjinKwon . Merged to master.

**Comment by HyukjinKwon** [comment]
Thank you @dongjoon-hyun.

**Pull request closed without merging**
