### PR TITLE
[SPARK-27722][SQL] removed the unsed "UnsafeKeyValueSorter" file.

### PR DESCRIPTION
**Pull request by shivusondur**
## What changes were proposed in this pull request?

removed the unused "UnsafeKeyValueSorter.java" file

## How was this patch tested?

Ran Compilation and UT locally.

Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
ok to test

**Comment by shivusondur** [comment]
please retest this

**Comment by shivusondur** [comment]
@HyukjinKwon 
Test Case failure is not relevant to this MR,
please retest

**Comment by viirya** [comment]
retest this please.

**Comment by cloud-fan** [comment]
ok to test

**Review by HyukjinKwon — APPROVED** [review]
Looks good if build and tests pass. I think there's no point of keeping unused private codes in Spark - it just makes us hard to read the codes.

**Review by viirya — APPROVED** [review]
The build and tests verify this class is not used. If no special reason to keep it, I think it is fine to remove it.

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Comment by shivusondur** [comment]
@HyukjinKwon , @cloud-fan , @viirya

**Pull request closed without merging**
