### PR TITLE
[SPARK-30300][SQL][WEB-UI] Fix updating the UI max value string when driver updates the same metric id as the tasks

### PR DESCRIPTION
**Pull request by nartal1**
### What changes were proposed in this pull request?

In this PR, For a given metrics id we are checking if the driver side accumulator's value is greater than max of all stages value. If it's true, then we are removing that entry from the Hashmap. By doing this, for this metrics, "driver" would be displayed on the UI(As the driver would have the maximum value) 

### Why are the changes needed?

This PR fixes https://issues.apache.org/jira/browse/SPARK-30300. Currently driver's metric value is not compared while caluculating the max.

### Does this PR introduce any user-facing change?

For the metrics where driver's value is greater than max of all stages, this is the change.
Previous : (min, median, max (stageId 0( attemptId 1): taskId 2))
Now:   (min, median, max (driver))

### How was this patch tested?

Ran unit tests.

### CODE REVIEW

**Comment by nartal1** [comment]
ok to test

**Comment by tgravescs** [comment]
thanks for the patch

@nartal1 please update the title to be a bit more descriptive, you could use the text similar to the jira:
Fix updating the UI max value string when driver updates the same metric id as the tasks.

Were you able to run  any manual testing to verify the UI?

**Comment by tgravescs** [comment]
ok to test

**Comment by srowen** [comment]
I don't know this code well, but I still don't quite understand the problem or change. You do or do not want the driver max to be included? it looks like you ignore it here, but the JIRA says you want to take into account the driver in the max calculation

**Comment by tgravescs** [comment]
The issue is if that driver updates the same metric as the tasks update, and the drivers update is the max, the String displayed on the SQL page associated with the max value doesn't get updated properly.  It shows some stage X, attempt y, task Z, when it should show "driver".  
He simply clears it which the stringValue function takes as meaning it was done by the driver and thus displays the proper thing.

https://github.com/apache/spark/pull/26941/files#diff-a74d84702d8d47d5269e96740a55a3caR254

https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/execution/metric/SQLMetrics.scala#L168

**Comment by srowen** [comment]
Would it make more sense to include the driver in the 'max' calculation? if I understand correctly, you remove the max if it's not bigger than the driver's value so that later it 'defaults' to the driver value. Is it more straightforward the former way, or is it harder / slower?

**Comment by tgravescs** [comment]
The max value is calculated as the task events come in. This function here is where any stage/task level metrics get combined with the driver metrics. We don't have access to the driver metrics on the taskend or metrics update events so we can't do it together. 
I think this approach is pretty straight forward, if the removing it part is confusing perhaps we can just add better comments?

Note we remove the value from maxMetricsFromAllStages if the driver value is larger so that the stringValue function defaults it to "driver".

**Comment by srowen** [comment]
OK, yeah a few comments wouldn't hurt. If it's correct and you support it, OK by me.

**Review by tgravescs — APPROVED** [review]
Test this out locally and it works for me.

+1. Thanks @nartal1

**Pull request closed without merging**
