### PR TITLE
[SPARK-44794][CONNECT] Make Streaming Queries work with Connect's artifact management

### PR DESCRIPTION
**Pull request by hvanhovell**
### What changes were proposed in this pull request?
When you try to run a streaming query that contains a UDF from the REPL, for example:
```scala
val add1 = udf((i: Long) => i + 1)
val query = spark.readStream
    .format("rate")
    .option("rowsPerSecond", "10")
    .option("numPartitions", "1")
    .load()
    .withColumn("value", add1($"value"))
    .writeStream
    .format("memory")
    .queryName("my_sink")
    .start()
```
You are currently greeted by a hard to understand deserialization issue, where a serialization proxy cannot be assigned to a field. The underlying cause here is a `ClassNotFoundException` (yes, java serialization is weird). This  `ClassNotFoundException`  is caused by us not propagating the `JobArtifactState` (this - indirectly - contains information about the location of REPL generated classes, and session local libraries) properly to the streaming query execution thread.

This PR fixed this by propagating the `JobArtifactState` into the stream execution thread.

### Why are the changes needed?
It is a bug. We want streaming to work with connect's isolated dependencies.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
I added a test to `ReplE2ESuite`.

### CODE REVIEW

**Comment by hvanhovell** [comment]
@bogao007 PTAL

**Review by grundprinzip — APPROVED** [review]

**Review by vicennial — APPROVED** [review]
Nice debugging!
This also fixes https://issues.apache.org/jira/browse/SPARK-43796 cc @WweiL @rangadi

**Review by rangadi — APPROVED** [review]
LGTM.

**Comment by WweiL** [comment]
Thanks for the fix!

**Review by bogao007 — APPROVED** [review]

**Comment by hvanhovell** [comment]
I am merging this one. The single test failing seems to be flaky.

**Pull request closed without merging**
