### PR TITLE
[SPARK-46650][CORE][SQL][YARN] Replace AtomicBoolean with volatile boolean

### PR DESCRIPTION
**Pull request by beliefer**
### What changes were proposed in this pull request?
This PR propose to replace `AtomicBoolean` with `volatile` boolean for some code.

### Why are the changes needed?
`volatile` could keep the visibility and is a lightweight synchronization method.
We should consider using volatile variables if the following requirements are met.

- The write operation on variables does not depend on the current value of the variable, or only a single thread updates the value of the variable.

- This variable will not be included in the invariant condition along with other state variables.

- No locking is required when accessing variables.

### Does this PR introduce _any_ user-facing change?
'No'.

### How was this patch tested?
GA tests.

### Was this patch authored or co-authored using generative AI tooling?
'No'.

### CODE REVIEW

**Comment by beliefer** [comment]
ping @srowen @dongjoon-hyun @LuciferYang

**Comment by srowen** [comment]
It's probably fine but does this improve anything? It's about the same

**Comment by beliefer** [comment]
> It's probably fine but does this improve anything? It's about the same

Reduce a little overhead due to `AtomicBoolean's` `get` and `set` actually use volatile .

**Review by mridulm — COMMENTED** [review]
As formulated, it is equivalent to what exists ... but I dont see a very good reason to make this change.

**Pull request closed without merging**
