### PR TITLE
[SPARK-15307]  [SQL] speed up listing files for data source

### PR DESCRIPTION
**Pull request by davies**
## What changes were proposed in this pull request?

Currently, listing files is very slow if there is thousands files, especially on local file system, because:
1) FileStatus.getPermission() is very slow on local file system, which is launch a subprocess and parse the stdout.
2) Create an JobConf is very expensive (ClassUtil.findContainingJar() is slow).

This PR improve these by:
1) Use another constructor of LocatedFileStatus to avoid calling FileStatus.getPermission, the permissions are not used for data sources.
2) Only create an JobConf once within one task.
## How was this patch tested?

Manually tests on a partitioned table with 1828 partitions, decrease the time to load the table from 22 seconds to 1.6 seconds (Most of time are spent in merging schema now).

### CODE REVIEW

**Comment by davies** [comment]
cc @liancheng

**Comment by rxin** [comment]
The pull request description is great. Can you put some of those into code as comments?  Especially this part: " FileStatus.getPermission() is very slow on local file system, which is launch a subprocess and parse the stdout."

**Comment by davies** [comment]
@rxin updated.

**Comment by rxin** [comment]
cc @sameeragarwal for review.

**Comment by liancheng** [comment]
LGTM. Thanks for fixing it! Merging to master and branch-2.0.

**Pull request closed without merging**
