### PR TITLE
[SPARK-32804][Launcher][FOLLOWUP] Fix SparkSubmitCommandBuilderSuite test failure without jars

### PR DESCRIPTION
**Pull request by KevinSmile**
### What changes were proposed in this pull request?

It's a followup of https://github.com/apache/spark/pull/29653.
Tests in `SparkSubmitCommandBuilderSuite` may fail if you didn't build first and have jars before test, 
so if `isTesting` we should set a dummy `SparkLauncher.NO_RESOURCE`.

### Why are the changes needed?

Fix tests failure.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

mvn clean test (test without jars built first).

### CODE REVIEW

**Comment by KevinSmile** [comment]
@HyukjinKwon

**Comment by HyukjinKwon** [comment]
ok to test

**Review by HyukjinKwon — APPROVED** [review]

**Comment by KevinSmile** [comment]
Seems that `DecommissionWorkerSuite` is unstable?

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
