### PR TITLE
[SPARK-16545][SQL] Eliminate unnecessary rounds of physical planning in ForeachSink

### PR DESCRIPTION
**Pull request by lw-lin**
## Problem

As reported by [SPARK-16545](https://issues.apache.org/jira/browse/SPARK-16545), in `ForeachSink` we have initialized 3 rounds of physical planning.

More specific:

[1] In `StreamExecution`, [lastExecution.executedPlan](https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/StreamExecution.scala#L369)

[2] In `ForeachSink`, [forearchPartition() calls withNewExecutionId(..., **_queryExection_**)](https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/Dataset.scala#L2145), which further calls [**_queryExecution_**.executedPlan](https://github.com/apache/spark/blob/9a5071996b968148f6b9aba12e0d3fe888d9acd8/sql/core/src/main/scala/org/apache/spark/sql/execution/SQLExecution.scala#L55)

[3] In `ForeachSink`, [val rdd = { ... incrementalExecution = new IncrementalExecution ...}](https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/ForeachSink.scala#L53)
## What changes were proposed in this pull request?

[1] ~~should not be eliminated in general;~~ is eliminated for case `ForeachSink`;

**[2] is eliminated, by replacing the `queryExecution` with `incrementalExecution` provided by [3];**

[3] should be eliminated but can not be done at this stage; let's revisit it when SPARK-16264 is resolved.
## How was this patch tested?
- checked manually now there ~~are only 2 rounds~~ is only 1 round of physical planning in ForeachSink after this patch
- existing tests ensure it cause no regression

### CODE REVIEW

**Comment by mariobriggs** [comment]
> [1] should not be eliminated in general;

  I dont understand the full internal aspects of IncrementalExecution, but my generally thinking was that 1 can be eliminated because 'executedPlan' is a ' lazy val' on QueryExecution ?

>[2] is eliminated by this patch, by replacing the queryExecution with incrementalExecution provided by [3];

If the goal is to get it to just as minimal as possible for now and wait for SPARK-16264 (which i was also thinking where it will have to finally wait for full resolution), why not keep [1] and the change to [2] be the simple case of changing [L52](https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/ForeachSink.scala#L52) to the following
 
``` new Dataset(data.sparkSession, data.queryExecution, implicitly[Encoder[T]]) ```

and no further changes required to your ealier code. Will it be the case that the wrong physical plan will logged in SparkListenerSQLExecutionStart ?

**Comment by mariobriggs** [comment]
What i tried to do as a 'side fix' was like this,
  eliminate [1] since it was a lazy val. 

  Move [2] out of the code path of the main thread i.e. let ListenerBus thread pay the penalty of producing the physical plan for logging ( i was coming from a performance test scenario, so it allowed me to proceed :-) ) . So the change was that SparkListenerSQLExecutionStart only take QueryExecution as a input parameter and not physicalPlanDescription & SparkPlanInfo . However this cannot be the solution since SparkListenerSQLExecutionStart is a public API already.

 [3] remains.

As you might have already noticed ConsoleSink also suffers from the same problem of [2] and these are inside Dataset.withTypedCallback/withCallback, but it is only for Debug purposes

**Comment by lw-lin** [comment]
@mariobriggs Thanks for the information!

> 1 can be eliminated because 'executedPlan' is a ' lazy val' on QueryExecution ?

Yea indeed. Its being there can provide us debug info but on second thought it might not be worth it. So let's also skip it in the case of `ForeachSink`.

> ... However this cannot be the solution since SparkListenerSQLExecutionStart is a public API already

Yea we probably do not want to modify this public API; so what we did in this patch was, passing [3]'s `incrementalExecution` into the listener so we'll only initialize physical planning only once for [2] and [3].

> ... why not keep [1] and the change to [2] be the simple case of changing L52 to the following: new Dataset(data.sparkSession, data.queryExecution, implicitly[Encoder[T]])

This is great. If reviews decide that 2 rounds of physical planning is acceptable, then let's do it your way!

> ... ConsoleSink ... but it is only for Debug purposes

So maybe let us live with it.

**Comment by mariobriggs** [comment]
>Yea we probably do not want to modify this public API; so what we did in this patch was, passing [3]'s incrementalExecution into the listener so we would initialize physical planning only once for [2] and [3].

oh cool. I didn't realize that. I can give it a try and understand it more. Thanks... this was the trick i was missing

**Comment by lw-lin** [comment]
@marmbrus @zsxwing could you take a look and share some ideas? Thanks!

**Comment by marmbrus** [comment]
Thanks for working on this, but I'm tempted to close this as "won't fix".  Its likely we are going to have to rewrite the incremental planner completely for 2.1 and this is just a minor inefficiency if I understand correctly.

In a more general comments:
 - There's no tests
 - If you find yourself needing to reference a bug/JIRA in several different places throughout the code, perhaps we need to reexamine the problem more holistically, rather than continue to pile on hacks.

**Comment by lw-lin** [comment]
Sure let's rewrite the incremental planner to solve problems more holistically; actually this patch is not satisfying to myself either. So I'm closing this, and -- thank you for the ideas!

**Pull request closed without merging**
