### PR TITLE
[MINOR] Update URL of the parquet project in code comment

### PR DESCRIPTION
**Pull request by izchen**
### What changes were proposed in this pull request?
Update URL of the parquet project in code comment.

### Why are the changes needed?
The original url is not available.

### Does this PR introduce _any_ user-facing change?
NO

### How was this patch tested?
No test needed.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
@izchen, let's keep [the GitHub PR template](https://github.com/apache/spark/blob/master/.github/PULL_REQUEST_TEMPLATE) as is. 

This is fine but mind taking another look around here and see if there are similar issues and/or typos?

**Comment by izchen** [comment]
> @izchen, let's keep [the GitHub PR template](https://github.com/apache/spark/blob/master/.github/PULL_REQUEST_TEMPLATE) as is.
> 
> This is fine but mind taking another look around here and see if there are similar issues and/or typos?

@HyukjinKwon, Thank you for review, the other parquet urls in the source code are correct.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master, branch-3.0 and branch-2.4.

**Comment by HyukjinKwon** [comment]
This is very minor but still cc @ScrapCodes and @zhengruifeng FYI

**Pull request closed without merging**
