### PR TITLE
[TEST Only] test sbt 1.10.0 performance without local maven repo cache

### PR DESCRIPTION
**Pull request by panbingkun**

### CODE REVIEW

**Comment by panbingkun** [comment]
In the `mima` step
1.with local maven repo cache:



2.without local maven repo cache:

**Comment by panbingkun** [comment]
cc @LuciferYang @dongjoon-hyun

**Comment by panbingkun** [comment]
I have narrowed the scope of the impact of not using `local maven repo cache` to the step `MIMA test` of the job `lint`

**Comment by LuciferYang** [comment]
MIMA took 8 minutes and 6 seconds, and there doesn't seem to be a significant performance difference. I think this is feasible.

Could you have it run a few more times to confirm that this execution time is relatively stable?

**Comment by panbingkun** [comment]
> MIMA took 8 minutes and 6 seconds, and there doesn't seem to be a significant performance difference. I think this is feasible.
> 
> Could you have it run a few more times to confirm that this execution time is relatively stable? @panbingkun

Sure, let me to do it.

**Comment by panbingkun** [comment]
I ran it twice again today. 
It was verified that the performance of the `mima` step seemed to be `stable` at about `8 min and ... seconds` without `local maven repo cache`. 
@dongjoon-hyun @LuciferYang

**Comment by LuciferYang** [comment]
This is fine for me, and the time is about the same as using the maven local cache. But I suggest splitting `disable maven local cache` and `upgrade to sbt 1.10.0` into two separate PRs.

**Comment by panbingkun** [comment]
> This is fine for me, and the time is about the same as using the maven local cache. But I suggest splitting `disable maven local cache` and `upgrade to sbt 1.10.0` into two separate PRs.

1.Disable `maven local cache` on GA's step `MIMA test`
https://github.com/apache/spark/pull/46551

After the above pr is merged, I will upgrade the `sbt` to `1.10.0` based on this pr.

**Comment by panbingkun** [comment]
A test without `local maven repo cache`
https://github.com/apache/spark/pull/46606

**Pull request closed without merging**
