### PR TITLE
[SPARk-34848][SQL][FLLOW-UP] Fix merge conflict issue cause UT failed

### PR DESCRIPTION
**Pull request by AngersZhuuuu**
### What changes were proposed in this pull request?
Fix issue of  https://github.com/apache/spark/pull/31948#issuecomment-808647121

### Why are the changes needed?
fix ut failed

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Existed UT

### CODE REVIEW

**Comment by AngersZhuuuu** [comment]
gentle ping  @yaooqinn @srowen  cc  @c21

**Review by c21 — APPROVED** [review]
LGTM, thanks for quick fix.

**Comment by AngersZhuuuu** [comment]
@dongjoon-hyun @maropu @cloud-fan @HyukjinKwon Any committer can merge this quick fix? Since it will impact all tests.

**Comment by dongjoon-hyun** [comment]
Let me check.

**Comment by dongjoon-hyun** [comment]
Well, the master branch looks healthy according to the last commit. What is the problem here, @AngersZhuuuu ?
- https://github.com/apache/spark/commit/769cf7b966cd2f980e385ac407f6b29f2a0389b9

**Comment by dongjoon-hyun** [comment]
Hm, got it. I'm running `HistoryServerSuite` now.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. I verified HistoryServerSuite manually. Thanks!

**Comment by srowen** [comment]
Oops, thanks. Looks like we had a bit of a race condition between two merges and test results.

**Pull request closed without merging**
