### PR TITLE
[SPARK-3424][MLLIB] cache point distances during k-means|| init

### PR DESCRIPTION
**Pull request by mengxr**
This PR ports the following feature implemented in #2634 by @derrickburns:
- During k-means|| initialization, we should cache costs (squared distances) previously computed.

It also contains the following optimization:
- aggregate sumCosts directly
- ran multiple (#runs) k-means++ in parallel

I compared the performance locally on mnist-digit. Before this patch:

before

with this patch:

after

It is clear that each k-means|| iteration takes about the same amount of time with this patch.

### CODE REVIEW

**Comment by mengxr** [comment]
test this please

**Comment by derrickburns** [comment]
The conversion of vectors to dense form will only work if the dimension of the space is small, in which case there was little need to provide vectors in sparse form. Therefore, one should assume that sparse vectors are from a high dimensional space, and should never be converted to a dense representation.

**Comment by derrickburns** [comment]
@mengxr I back-ported your port to my com.massivedatascience.clusterer GitHub project (modulo the conversion of data to dense form). :)

**Comment by mengxr** [comment]
@derrickburns This PR doesn't handle sparse centers. The dense one should work with feature dimension up to 10m, which may cover many cases already. We can solve that issue in a separate PR. Does the changes in this PR look good to you? (It seems that there is something wrong with Jenkins.)

Feel free to port the features and it would be great if you can help test the performance:)

**Comment by derrickburns** [comment]
@mengxr

It looks like the final costs rdd is still persisted in exit from the initialization method.

**Comment by derrickburns** [comment]
@mengxr

A nit: I'd pull the range creation on line 331 out of the inner loop.

**Comment by derrickburns** [comment]
@mengxr

FYI, I'm about to work on the performance of clustering millions of sparse vectors of very high dimension particularly when using KL divergence, where smoothing is needed to deal with sparsity.

**Comment by mengxr** [comment]
@derrickburns Thanks! I've addressed your comments!

**Comment by derrickburns** [comment]
@mengxr
You may want to refer to the newer code in GitHub
<https://github.com/derrickburns/generalized-kmeans-clustering> instead of
the old PR going forward.

I've refactored the PointOps interface since the old PR following your
comments.

I also rewrote the KMeansPlusPlus in a similar fashion as to your changes
to KMeansParallel and support sparse points in high dimension, but the
PointOps redesign is the most important change.

**Comment by mengxr** [comment]
Sure. Thanks for keeping your implementation updated!

**Comment by mengxr** [comment]
I've merged this into master.

**Pull request closed without merging**
