### PR TITLE
[SPARK-40853][INFRA] Pin `mypy-protobuf==3.3.0`

### PR DESCRIPTION
**Pull request by zhengruifeng**
### What changes were proposed in this pull request?
[`mypy-protobuf` 3.4.0](https://pypi.org/project/mypy-protobuf/#history) is just released, and will break master shortly

### Why are the changes needed?
to make CI happy

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
manually check

### CODE REVIEW

**Comment by zhengruifeng** [comment]
https://github.com/zhengruifeng/spark/actions/runs/3287636127/jobs/5417056205

after upgrade to 3.4.0, `Python code gen check` will break the CI

**Comment by zhengruifeng** [comment]
cc @HyukjinKwon

**Comment by zhengruifeng** [comment]
cc @Yikun

**Comment by zhengruifeng** [comment]
`Python code gen check` passed https://github.com/zhengruifeng/spark/actions/runs/3287876793/jobs/5418579629

**Review by Yikun — APPROVED** [review]

**Comment by zhengruifeng** [comment]
@Yikun thank you

**Review by HyukjinKwon — COMMENTED** [review]
LGTM

**Pull request closed without merging**
