### PR TITLE
[SPARK-42987][DOCS] Correction of protobuf sql documentation

### PR DESCRIPTION
**Pull request by lucaspompeun**
### What changes were proposed in this pull request?

Correction of  code highlights in SQL protobuf documentation.

old version:
image
new version:
image

### Why are the changes needed?

To help spark users to understand python, scala and java code examples.

### Does this PR introduce _any_ user-facing change?

Yes, it improve user-facing documentation

### How was this patch tested?

Comparing visual structure in the old and the new version in vscode markdown preview and github markdown preview.

### CODE REVIEW

**Comment by lucaspompeun** [comment]
I'have corrected the problem that cause build error in github workflow

**Comment by HyukjinKwon** [comment]
cc @SandishKumarHN and @rangadi

**Review by rangadi — APPROVED** [review]
Thanks for the updates Lucas.
This looks great. 

A few more fixes if you could: 
  - add two space indentation for code sample (first screenshot)
  - Replace comment string ` First, via the protobuf descriptor file, and then via the protobuf message class name.` with `Via Protobuf descriptor file, or via shaded Java class` 
  - In SQL Type conversion table:
     -  Add one more row : `Any` maps to `StructType`


image

**Comment by lucaspompeun** [comment]
The adition of any should be added in wich table? Protobuf -> Spark SQL or Spark SQL -> Protobuf?

**Comment by lucaspompeun** [comment]
@rangadi the first two fixes were made

**Comment by rangadi** [comment]
@lucaspompeun thanks for the updates. LGTM.

`Any` is for 'Protobuf -> Spark SQL' type table.

**Comment by rangadi** [comment]
Thanks.
@HyukjinKwon please merge when you get a chance.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master and branch-3.4.

**Pull request closed without merging**
