### PR TITLE
[PySpark] add picklable SparseMatrix in pyspark.ml.common

### PR DESCRIPTION
**Pull request by WeichenXu123**
## What changes were proposed in this pull request?

add `SparseMatrix` class whick support pickler.
## How was this patch tested?

Existing test.

### CODE REVIEW

**Comment by WeichenXu123** [comment]
@srowen 
I check the ml.python.MLSerde and it support SparseMatrix pickler and at python side the SparseMatrix constructor also match the pickler. So I think the `_picklable_classes` forgot to add `SparkMatrix`, or there is some other reason not to add SparseMatrix to the class list ?

**Comment by WeichenXu123** [comment]
@srowen I guess the `_picklable_classes` list in `ml.linalg.common` is copied from `mllib.linalg.common` so it forgot to add the `SparseMatrix` which is added later.

**Comment by srowen** [comment]
This isn't really my area, but I that sounds plausible

**Comment by WeichenXu123** [comment]
cc @rxin Thanks!

**Comment by WeichenXu123** [comment]
cc @jkbradley Thanks!

**Comment by srowen** [comment]
@holdenk or @MLnick do you happen to know if this sounds right?

**Comment by yanboliang** [comment]
LGTM, merged into master. Thanks.

**Comment by WeichenXu123** [comment]
@srowen We can check python/ml/tests.py, `VectorTests.test_serialize` function, it contains a test for `SparseMatrix` serializing/unserializing, so that we can confirm that this works.

**Pull request closed without merging**
