### PR TITLE
[SPARK-46468] [SQL] Handle COUNT bug for EXISTS subqueries with Aggregate without grouping keys

### PR DESCRIPTION
**Pull request by agubichev**
### What changes were proposed in this pull request?

As Aggregates with no grouping keys always return 1 row (can be NULL), an EXISTs over such subquery should always return true.
This reverts some changes done when we migrated EXISTS/IN to DecorrelateInnerQuery framework, in particular the static detection of potential count bug aggregates is removed (just having an empty grouping key should trigger the count bug treatment now; scalar subqueries still have extra checks that are evaluating the aggregate on an empty input). I suspect the same correctness problem was present in the legacy framework (added one test in the legacy section of exists-count-bug.sql) 

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Query tests

### Was this patch authored or co-authored using generative AI tooling?

No

### CODE REVIEW

**Comment by agubichev** [comment]
@jchen5

**Review by jchen5 — COMMENTED** [review]
Should the title be something like handle COUNT bug for subqueries with aggregate and no group-by?

It looks like your PR just has reverting your earlier count bug changes, was there another part that was missed?

**Comment by agubichev** [comment]
> Should the title be something like handle COUNT bug for subqueries with aggregate and no group-by?
> 
> It looks like your PR just has reverting your earlier count bug changes, was there another part that was missed?

updated

**Review by jchen5 — COMMENTED** [review]
Can we add a legacy behavior flag for this change? Since it seems like the behavior for EXISTS has been wrong for a long time.

**Comment by jchen5** [comment]
Actually, on second thought, we already have DECORRELATE_EXISTS_IN_SUBQUERY_LEGACY_INCORRECT_COUNT_HANDLING_ENABLED which should take care of that

**Review by jchen5 — APPROVED** [review]

**Comment by agubichev** [comment]
@cloud-fan

**Review by cloud-fan — APPROVED** [review]

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Pull request closed without merging**
