### PR TITLE
[MINOR][DOC] Fix ml-guide markdown typos

### PR DESCRIPTION
**Pull request by taoran92**
## What changes were proposed in this pull request?

Easy fix in the markdown.

## How was this patch tested?

Tested manually

Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Comment by felixcheung** [comment]
can you check if we have other typo in the md file?
or similar type of typo in other md files?

**Comment by Lemonjing** [comment]
@felixcheung Yes, I read the entire docs of Spark Mlib. There is no problem with other mds (I may not have seen it or other contributors solved it). This error is obvious, and it affects the link of the later issue, so i found it.
[http://spark.apache.org/docs/latest/ml-guide.html#breaking-changes](url)

**Comment by HyukjinKwon** [comment]
I think you can add all other typos into here.

**Comment by Lemonjing** [comment]
@HyukjinKwon Thanks a lot, could u help me to review these commits if u have time。

**Comment by Lemonjing** [comment]
can someone help me to close this pr?  i have merged these commits to a new pr.
https://github.com/apache/spark/pull/20897

**Comment by felixcheung** [comment]
@Lemonjing you need to close the PR from github.com - we don't have access to close it

**Comment by Lemonjing** [comment]
@felixcheung thanks a lot. and i closed it.

**Pull request closed without merging**
