### PR TITLE
[SPARK-25935][SQL] Allow null rows for bad records from JSON parsers

### PR DESCRIPTION
**Pull request by MaxGekk**
## What changes were proposed in this pull request?

This PR reverts  #22938 per discussion in #23325

Closes #23325

### CODE REVIEW

**Comment by MaxGekk** [comment]
@cloud-fan @HyukjinKwon @bersprockets Please, take a look at the PR.

**Comment by HyukjinKwon** [comment]
Yup, I agree with it for now.

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Comment by bersprockets** [comment]
Should the PR title be "Allow null rows for bad records from JSON parsers"?

**Comment by cloud-fan** [comment]
good catch! I've updated the title

**Pull request closed without merging**
