### PR TITLE
[SPARK-25431][SQL][EXAMPLES] Fix function examples and the example results.

### PR DESCRIPTION
**Pull request by ueshin**
## What changes were proposed in this pull request?

There are some mistakes in examples of newly added functions. Also the format of the example results are not unified. We should fix them.

## How was this patch tested?

Manually executed the examples.

### CODE REVIEW

**Comment by ueshin** [comment]
cc @dongjoon-hyun @gatorsmile

**Review by HyukjinKwon — APPROVED** [review]
LGTM

**Comment by ueshin** [comment]
Jenkins, retest this please.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

I also did double-check manually. Thank you, @ueshin .

**Comment by HyukjinKwon** [comment]
Merged to master and branch-2.4.

**Pull request closed without merging**
