### PR TITLE
[SPARK-27896][ML] Fix definition of clustering silhouette coefficient for 1-element clusters

### PR DESCRIPTION
**Pull request by srowen**
## What changes were proposed in this pull request?

Single-point clusters should have silhouette score of 0, according to the original paper and scikit implementation.

## How was this patch tested?

Existing test suite + new test case.

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by dongjoon-hyun** [comment]
Merged to master/2.4!

**Comment by dongjoon-hyun** [comment]
I reverted this from branch-2.4.

**Comment by srowen** [comment]
That's fine either way. Although it's arguably a bug fix it's fairly minor and slightly changes behavior, so could just do this in 3.0.

**Comment by dongjoon-hyun** [comment]
I see. Thank you. @srowen .

**Comment by mgaido91** [comment]
a late LGTM. I'd probably do this for 2.4 too, as I'd consider this a bug fix; but yes, this is quite a limit case...

**Pull request closed without merging**
