### PR TITLE
[SPARK-42400] Code clean up in org.apache.spark.storage

### PR DESCRIPTION
**Pull request by khalidmammadov**
### What changes were proposed in this pull request?
Code clean up. 
- Simplified conditions
- Removed unused parameters
- Removed explicit default values

### Why are the changes needed?
To make code more readable

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Existing tests

### CODE REVIEW

**Comment by khalidmammadov** [comment]
> I think this is not `MINOR`, please file a new Jira @khalidmammadov , thanks

Done

**Comment by khalidmammadov** [comment]
@srowen can you please review?

**Review by srowen — APPROVED** [review]
Seems OK

**Review by LuciferYang — APPROVED** [review]

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
