### PR TITLE
[SPARK-46582][R][INFRA] Upgrade R Tools version from 4.0.2 to 4.3.2 in AppVeyor

### PR DESCRIPTION
**Pull request by HyukjinKwon**
### What changes were proposed in this pull request?

This PR proposes to upgrade R Tools version from 4.0.2 to 4.3.2 in AppVeyor

### Why are the changes needed?

R Tools 4.3.X is for R 4.3.X. We did not upgrade because of the test failure previously.

### Does this PR introduce _any_ user-facing change?

No, test-only.

### How was this patch tested?

Checking the CI in this PR.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Review by yaooqinn — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Review by dongjoon-hyun — COMMENTED** [review]
+1, LGTM.

**Comment by LuciferYang** [comment]
hmm... the corresponding download link for rtools43 is: https://cloud.r-project.org/bin/windows/Rtools/rtools43/files/rtools43-5863-5818.exe, can the correct download link be generated by only changing the script.... @HyukjinKwon

**Comment by LuciferYang** [comment]
I have tried to upgrade rtools before, and if I remember correctly, there were compilation failures of gcc at that time. Since I didn't see the specific test link for this pr, I want to confirm.

**Comment by dongjoon-hyun** [comment]
Oh, right. According to the log, it hits 404 error but the failure is ignored like the following.

```
[00:01:07] Start-FileDownloadInternal : Error downloading remote file: One or more errors occurred.
[00:01:07] Inner Exception: Remote server returned 404: Not Found
[00:01:07] At C:\Program Files\AppVeyor\BuildAgent\Modules\build-worker-api\build-worker-api.psm1:242 char:2
[00:01:07] +     Start-FileDownloadInternal -Url $Url -FileName $FileName -Timeout ...
[00:01:07] +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[00:01:07]     + CategoryInfo          : NotSpecified: (:) [Start-FileDownloadInternal], Exception
[00:01:07]     + FullyQualifiedErrorId : System.Exception,Appveyor.BuildAgent.Api.Utils.StartFileDownloadInternalCmdlet
[00:01:07]  
[00:01:07] Start-Process : This command cannot be run due to the error: %1 is not a valid Win32 application.
[00:01:07] At C:\projects\spark\dev\appveyor-install-dependencies.ps1:59 char:3
[00:01:07] +   Start-Process -FilePath .\Rtools-current.exe -ArgumentList /VERYSIL ...
[00:01:07] +   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[00:01:07]     + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
[00:01:07]     + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand
[00:01:07]  
[00:01:07] Rtools is now available on drive C:
[00:01:07] 
[00:01:07] 
[00:01:07]     Directory: C:\
[00:01:07] 
[00:01:07] 
[00:01:07] Mode                LastWriteTime         Length Name                                                                                                                                                                                
[00:01:07] ----                -------------         ------ ----                                                                                                                                                                                
[00:01:07] d-----         1/4/2024  12:25 AM                RLibrary                     
```

**Comment by dongjoon-hyun** [comment]
Maybe, do you want to revert this first, @HyukjinKwon ?

**Comment by HyukjinKwon** [comment]
oh

**Comment by HyukjinKwon** [comment]
reverting now.

**Comment by dongjoon-hyun** [comment]
Thank you for reverting, @HyukjinKwon !

**Pull request closed without merging**
