### PR TITLE
[SPARK-5973] [PySpark] fix zip with two RDDs with AutoBatchedSerializer

### PR DESCRIPTION
**Pull request by davies**

### CODE REVIEW

**Comment by davies** [comment]
cc @JoshRosen @jkbradley

**Comment by jkbradley** [comment]
Did that test fail before the fix in rdd.py?  When I run the command locally in the pyspark shell, it works.

**Comment by davies** [comment]
@jkbradley yes, it failed before the patch.

**Comment by jkbradley** [comment]
Running locally with setting numPartitions = 2 made the test fail for me (without the fix).  LGTM if the unit tests definitely use > 1 partition

**Comment by jkbradley** [comment]
LGTM pending tests

**Comment by jkbradley** [comment]
That's weird the set of tests passed before your last commit...

**Comment by davies** [comment]
The tests could pass in the first commit, only broken in second (edited in github editor).

**Comment by jkbradley** [comment]
I'm merging this into master and branch-1.3.  We can backport to 1.2 in another PR

**Comment by davies** [comment]
Can this not been merged into 1.2 cleanly?

**Comment by jkbradley** [comment]
I realized AmplabJenkins hadn't posted it's 3rd "Test PASSed."  Why did the test pass during the 2nd run?

**Comment by davies** [comment]
The second commit is b2c..., jenkins did not test it.

**Comment by jkbradley** [comment]
Ok, merged to master, branch-1.3 and branch-1.2

**Pull request closed without merging**
