### PR TITLE
[MINOR]FsHistoryProvider import cleanup

### PR DESCRIPTION
**Pull request by gaborgsomogyi**
### What changes were proposed in this pull request?
As it has been discussed in https://github.com/apache/spark/pull/26397#discussion_r343726691 `FsHistoryProvider` import section has to be cleaned up.

### Why are the changes needed?
Unused imports.

### Does this PR introduce any user-facing change?
No.

### How was this patch tested?
Existing unit tests.

### CODE REVIEW

**Comment by gaborgsomogyi** [comment]
cc @vanzin @srowen @HeartSaVioR

**Review by srowen — COMMENTED** [review]
Sure, OK. You could remove other unused imports while at it if you like.

**Comment by gaborgsomogyi** [comment]
I've gone through https://github.com/apache/spark/pull/25670 + https://github.com/apache/spark/pull/26397 changes and fixed the import there in order to cover this effort. Do you have something specific in mind?

**Comment by srowen** [comment]
Nah, just if you feel like using IJ to search for unused imports in the rest of the module or code, it's fine too, but not important.

**Review by HeartSaVioR — APPROVED** [review]
LGTM

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
