### PR TITLE
[SPARK-24311][SS] Refactor HDFSBackedStateStoreProvider to remove duplicated logic between operations on delta file and snapshot file

### PR DESCRIPTION
**Pull request by HeartSaVioR**
## What changes were proposed in this pull request?

This patch refactors HDFSBackedStateStoreProvider to extract duplicated logic between operations on delta file and snapshot file, as well as documenting the structure of state delta/snapshot file.

## How was this patch tested?

Existing unit tests: StateStoreSuite

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
Kindly ping again to @tdas 

And cc. to @jose-torres @jerryshao @HyukjinKwon @arunmahadevan for reviewing.

**Comment by HyukjinKwon** [comment]
ok to test

**Comment by HeartSaVioR** [comment]
retest this, please

**Comment by HeartSaVioR** [comment]
retest this, please

**Comment by HeartSaVioR** [comment]
adding cc. to @zsxwing since he has been reviewing PRs for SS so far.

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HeartSaVioR** [comment]
retest this, please

**Comment by HeartSaVioR** [comment]
@tdas 
The rationalization of this patch is to group functions which deal with delta and snapshot files into one so that the difference between delta file and snapshot file will be clearly shown (actually no difference other than allowing TOMBSTONE value in delta file) as well as easy to document about these files. It's also easier to add tests for delta / snapshot files.

Indeed my underlying rationalization is to make the class easier to understand from newcomers (actually I found it helpful to group them logically to understand the code better), but the file has been getting enough love from various contributors so may not worth to put effort to make it easiler.

I respect the rule of Spark project, and happy to close if we don't feel benefitial to go on. Let's close it and revisit some other one feels benefitial. Thanks for providing your voice on this!

**Pull request closed without merging**
