### PR TITLE
[SPARK-15980] [SQL] Support Stata-like tabulation of values in a single column, optionally with weights

### PR DESCRIPTION
**Pull request by shafiquejamal**
## What changes were proposed in this pull request?

See JIRA ticket: https://issues.apache.org/jira/browse/SPARK-15890
## How was this patch tested?

Test is included.

I suspect that the changes in the /dev/pr-deps directory should not have been committed, but I would think that the .gitignore file would have prevented this.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
I think it will be nicer if it follows https://cwiki.apache.org/confluence/display/SPARK/Contributing+to+Spark

**Comment by shafiquejamal** [comment]
Hello, I read the rules at the link before creating the Jira ticket and pull request, and I think I am in compliance. Can you please tell me which point at that link I have not complied with? Thanks.

**Comment by sadikovi** [comment]
@shafiquejamal 
The PR title should be of the form [SPARK-xxxx] [COMPONENT] Title, where SPARK-xxxx is the relevant JIRA number, COMPONENT is one of the PR categories shown at https://spark-prs.appspot.com/ and Title may be the JIRA's title or a more specific title describing the PR itself.

**Comment by shafiquejamal** [comment]
Ok, I'll close this an open a new PR with the title done correctly. Thanks.

**Comment by shafiquejamal** [comment]
Hello, just wanted to know what else I should do in order for this PR to be accepted. Thanks.

**Comment by srowen** [comment]
This PR looks like it has some problems. It adds some deps files that are unrelated. Generally you'd want to argue that this functionality is important enough to justify the burden of maintaining it as an API. I'm not (yet) sure it is.

**Pull request closed without merging**
