### PR TITLE
[SPARK-50209][R][INFRA] Use R 4.4.2 in `windows` R GitHub Action Windows job

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to use R 4.4.2 in `windows` R GitHub Action job.

### Why are the changes needed?

R 4.4.2 (codename "Pile of Leaves") is the latest release which is released on 2024-10-31.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the CIs.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
All tests passed.

**Review by LuciferYang — APPROVED** [review]
LGTM

**Comment by LuciferYang** [comment]
Merged into master for Spark 4.0. Thanks @dongjoon-hyun

**Comment by dongjoon-hyun** [comment]
Thank you, @LuciferYang

**Comment by dongjoon-hyun** [comment]
For the record, this passed in Daily CI.
- https://github.com/apache/spark/actions/runs/11653124333/job/32445167848

Screenshot 2024-11-04 at 14 01 40

**Pull request closed without merging**
