### PR TITLE
[SPARK-48210][DOC]Modify the description of whether dynamic partition…

### PR DESCRIPTION
**Pull request by guixiaowen**
…ing is enabled in the “ Stage Level Scheduling Overview”

### What changes were proposed in this pull request?
“  Stage Level Scheduling Overview ” in running-on-yarn and  running-on-kubernetes

The description of dynamic partitioning is inconsistent with the code implementation verification.

In running-on-yarn 

'

When dynamic allocation is disabled: It allows users to specify different task resource requirements at the stage level and will use the same executors requested at startup.
'

But the  implementation is：

Class：ResourceProfileManager

Fuc：isSupported

private[spark] def isSupported(rp: ResourceProfile): Boolean = {
assert(master != null)
if (rp.isInstanceOf[TaskResourceProfile] && !dynamicEnabled) {
if ((notRunningUnitTests || testExceptionThrown) &&
!(isStandaloneOrLocalCluster || isYarn || isK8s))

{ throw new SparkException("TaskResourceProfiles are only supported for Standalone, " + "Yarn and Kubernetes cluster for now when dynamic allocation is disabled.") }
}

 

The judgment of this code is that it does not support TaskResourceProfile in Yarn and k8s when dynamic partitioning is closed.

 

The description in the document does not match, so the document needs to be modified.

 

### Why are the changes needed?
This description is a bit misleading for users.

### CODE REVIEW

**Comment by guixiaowen** [comment]
@cloud-fan  hi, Can you help me review this PR？

**Comment by dongjoon-hyun** [comment]
cc @mridulm and @tgravescs

**Comment by tgravescs** [comment]
sorry this description is very hard to read.  I think you are trying to say that stage level scheduling isn't supported on k8s and yarn when dynamic allocation is disabled?   When you say dynamic partitions do you mean dynamic allocation of executors?

That is not true we added support - https://issues.apache.org/jira/browse/SPARK-45495

The description as is:
> - When dynamic allocation is disabled: It allows users to specify different task resource requirements at the stage level and will use the same executors requested at startup.

Is correct. When dynamic allocation is off, you can specify a different resource profile that changes the task requiresments but uses the existing executors.

**Comment by guixiaowen** [comment]
> sorry this description is very hard to read. I think you are trying to say that stage level scheduling isn't supported on k8s and yarn when dynamic allocation is disabled? When you say dynamic partitions do you mean dynamic allocation of executors?
> 
> That is not true we added support - https://issues.apache.org/jira/browse/SPARK-45495
> 
> The description as is:
> 
> > * When dynamic allocation is disabled: It allows users to specify different task resource requirements at the stage level and will use the same executors requested at startup.
> 
> Is correct. When dynamic allocation is off, you can specify a different resource profile that changes the task requiresments but uses the existing executors.

@tgravescs  Thank you for your reply.

Can you help me check my configuration, code, and error messages returned.

Is there a problem with our understanding？


set spark.dynamicAllocation.enabled=false

`
import  org.apache.spark.resource.ResourceProfileBuilder
import  org.apache.spark.resource.TaskResourceRequests

val rdd = sc.range(0, 9)
val rpBuilder = new ResourceProfileBuilder()
val taskReqs = new TaskResourceRequests().cpus(1)
val rp = rpBuilder.require(taskReqs).build
rdd.withResources(rp)
`

Return info：

`
org.apache.spark.SparkException: TaskResourceProfiles are only supported for Standalone cluster for now when dynamic allocation is disabled.
  at org.apache.spark.resource.ResourceProfileManager.isSupported(ResourceProfileManager.scala:71)
  at org.apache.spark.resource.ResourceProfileManager.addResourceProfile(ResourceProfileManager.scala:126)
  at org.apache.spark.rdd.RDD.withResources(RDD.scala:1829)
  ... 48 elided

`
According to the document description，  is  '**specify different task resource requirements** ' set TaskResourceRequests？

‘
When dynamic allocation is disabled: It allows users to specify different task resource requirements at the stage level and will use the same executors requested at startup.
’

Is there a problem with my understanding? 
Can you help me answer this? Thank you.

**Comment by tgravescs** [comment]
what version of Spark are you using?  That issue I pointed to was fixed in 4.0.0 and 3.5.1.

The check and error that is on the main branch should read:

```
      if ((notRunningUnitTests || testExceptionThrown) &&
        !(isStandaloneOrLocalCluster || isYarn || isK8s)) {
        throw new SparkException("TaskResourceProfiles are only supported for Standalone, " +
          "Yarn and Kubernetes cluster for now when dynamic allocation is disabled.")
```

https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/resource/ResourceProfileManager.scala#L73

I'm guessing you are using a version of Spark before that change.

**Comment by guixiaowen** [comment]
> what version of Spark are you using? That issue I pointed to was fixed in 4.0.0 and 3.5.1.
> 
> The check and error that is on the main branch should read:
> 
> ```
>       if ((notRunningUnitTests || testExceptionThrown) &&
>         !(isStandaloneOrLocalCluster || isYarn || isK8s)) {
>         throw new SparkException("TaskResourceProfiles are only supported for Standalone, " +
>           "Yarn and Kubernetes cluster for now when dynamic allocation is disabled.")
> ```
> 
> https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/resource/ResourceProfileManager.scala#L73
> 
> I'm guessing you are using a version of Spark before that change.

@tgravescs  
I tested on 3.5.1 and main branch (4.0.0)
The results of these two branch tests are the same. The code is restricted, but the documentation states that it is possible to enable it.
This place is a bit contradictory

**Comment by amogkam** [comment]
also running into this error with 3.5.1 when trying to use stage level scheduling with `dynamicAllocation` set to False

```
: org.apache.spark.SparkException: ResourceProfiles are only supported on YARN and Kubernetes and Standalone with dynamic allocation enabled.
	at org.apache.spark.resource.ResourceProfileManager.isSupported(ResourceProfileManager.scala:88)
	at org.apache.spark.resource.ResourceProfileManager.addResourceProfile(ResourceProfileManager.scala:127)
	at org.apache.spark.rdd.RDD.withResources(RDD.scala:1832)
	at org.apache.spark.api.java.JavaRDD.withResources(JavaRDD.scala:59)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by amogkam** [comment]
the exception being thrown is still in master https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/resource/ResourceProfileManager.scala#L90-L91

**Pull request closed without merging**
