### PR TITLE
SPARK-12416 Jms receiver

### PR DESCRIPTION
**Pull request by tbfenet**
Reliable receiver(s) for JMS. There are two as some JMS providers support asynchronous acknowledgment while the standard does not.

### CODE REVIEW

**Comment by mattf** [comment]
@willb ptal

**Comment by tdas** [comment]
This is a cool patch! JMS is being used quite a bit this is good. However, we are not accepting any further external packages into spark any more to reduce the complexity of managing all of them. To make it easy for people to contribute, we have made spark-packages.org, where many developers have submitted their own receivers, etc. Please submit this to spark-packages.org. Thank you!

**Comment by HyukjinKwon** [comment]
Maybe we might have to correct the title just like the others, `[SPARK-XXXX][SQL]` (this is described in https://cwiki.apache.org/confluence/display/SPARK/Contributing+to+Spark).

**Comment by srowen** [comment]
@tbfenet can you close this PR?

**Pull request closed without merging**
