### PR TITLE
[SPARK-16575][CORE] partition calculation mismatch with sc.binaryFiles

### PR DESCRIPTION
**Pull request by fidato13**
## What changes were proposed in this pull request?

This Pull request comprises of the critical bug SPARK-16575 changes. This change rectifies the issue with BinaryFileRDD partition calculations as  upon creating an RDD with sc.binaryFiles, the resulting RDD always just consisted of two partitions only.
## How was this patch tested?

The original issue ie. getNumPartitions on binary Files RDD (always having two partitions) was first replicated and then tested upon the changes. Also the unit tests have been checked and passed.

This contribution is my original work and I licence the work to the project under the project's open source license

@srowen @hvanhovell @rxin @vanzin @skyluc @kmader @zsxwing @datafarmer Please have a look .

### CODE REVIEW

**Comment by rxin** [comment]
I don't actually think this is a bug, because it is intended to do some coalescing. If there is an issue, the issue would be that we don't take the cost of individual files into account in this code path. The Spark SQL automatic coalescing code path does take that into account.

**Comment by fidato13** [comment]
Hi @rxin , 
Yes, I agree and I believe SQL does take it into account. Should we proceed with this pull request as it does give the correct partitions for other components which may be helpful and rectifies the previous mismatch introduced in 1.6.1 . Please advise.

**Comment by rxin** [comment]
The problem is that it does not make sense to create one partition per file, when files are small. This was actually a bug with the previous implementation.

**Comment by fidato13** [comment]
@rxin Yes, it makes perfect sense to not create a partition per file. 
Looking at the code in PortableDataStream.setMinPartitions:-
val maxSplitSize = math.ceil(totalLen / math.max(minPartitions, 1.0)).toLong

Unless the user specifies minPartitions , the default picked would most likely create just two partitions always irrespective of the size and count of the files.

The change in this pull request makes the partition count consistent with other RDD types . For example , textFile and binaryFiles would be presenting the same number of partitions.

For sure, your concern is to be kept at top priority that is to not create one partition per small file and which most likely may be kept as an improvement change in the near future?

**Comment by fidato13** [comment]
@rxin, Thanks for this. I think we can surely go for creating one partition per 1 block size(default block size 128MB) and would you be able to point me about the second's(cost of opening a file) implementation please.

**Comment by kmader** [comment]
@rxin on the PS, how would you foresee the SQL implementation for binary support? is there a standard method of going from bytestreams to dataframes?

**Comment by fidato13** [comment]
@rxin, The support for openCostInBytes, similar to SQL has now been added for the affected binaryFiles case. Can I please seek for your review and valuable suggestion for taking this forward and merging this pull request. Thanks for your awesome suggestion!

**Comment by fidato13** [comment]
cc @srowen @hvanhovell @vanzin @skyluc @kmader @zsxwing @datafarmer

**Comment by srowen** [comment]
If this mirrors some code in Spark SQL, can we refactor the commonality? I don't know this code well but given the discussion I was expecting more sharing. What is the corresponding config code that this is following?

**Comment by fidato13** [comment]
Hi @srowen

The Spark SQL property/algo that binaryFiles partition calculation is now implementing is the property "spark.files.openCostInBytes" (in org.apache.spark.sql.internal.SQLConf) utilized in org.apache.spark.sql.execution.FileSourceScanExec inside method createNonBucketedReadRDD .

As the original issue states that sc.binaryFiles is always creating an RDD with number of partitions as 2 (irrespective of number and size of files say for 1000 files or for even GB's of file , It will only create two partitions only). 

To resolve , Reynold suggested that we can probably implement somthing like Spark SQL does i.e. to consider the cost of opening a file(more description in the JIRA issue) so that it doesn't create large number of partitions for small files.

Please let me know your suggestions on this, I have now verified that it's now creating an optimized number of partitions . Also, since both properties are used for their respective config's and for the SPARK CORE it's used just once for this issue , Can you please advise about if it would be okay to keep them or How would you like to proceed on this.

Thanks

**Comment by fidato13** [comment]
/**
   * Create an RDD for non-bucketed reads.
   * The bucketed variant of this function is [[createBucketedReadRDD]].
   *
   * @param readFile a function to read each (part of a) file.
   * @param selectedPartitions Hive-style partition that are part of the read.
   * @param fsRelation [[HadoopFsRelation]] associated with the read.
   */
  private def createNonBucketedReadRDD(
      readFile: (PartitionedFile) => Iterator[InternalRow],
      selectedPartitions: Seq[Partition],
      fsRelation: HadoopFsRelation): RDD[InternalRow] = {
    val defaultMaxSplitBytes =
      fsRelation.sparkSession.sessionState.conf.filesMaxPartitionBytes
    val openCostInBytes = fsRelation.sparkSession.sessionState.conf.filesOpenCostInBytes
    val defaultParallelism = fsRelation.sparkSession.sparkContext.defaultParallelism
    val totalBytes = selectedPartitions.flatMap(_.files.map(_.getLen + openCostInBytes)).sum
    val bytesPerCore = totalBytes / defaultParallelism

    val maxSplitBytes = Math.min(defaultMaxSplitBytes, Math.max(openCostInBytes, bytesPerCore))


================ This is the calculation happening currently in Spark SQL while considering openCostInBytes to avoid creating large number of partitions.

**Comment by fidato13** [comment]
@srowen @rxin @zsxwing Can you please have a look and advise. 
Thanks

**Comment by fidato13** [comment]
Can I request anyone to suggest if the changes are not required , I will close the PR!

@srowen @hvanhovell @rxin @vanzin @skyluc @kmader @zsxwing @datafarmer

**Comment by rxin** [comment]
Jenkins, retest this please.

**Comment by fidato13** [comment]
ping @rxin @srowen @zsxwing Can you please have a look and advise Jenkins to retest . In this latest commit fixed "SPARK-12527, it is discarded unused. You may specify targets with meta-annotations" warning, which caused the build to fail due to the above mentioned warning.

**Comment by rxin** [comment]
triggered.

**Comment by fidato13** [comment]
ping @rxin @srowen @zsxwing The build and tests have passed. Request you to merge as you get time. Thanks!

**Comment by fidato13** [comment]
ping @rxin @srowen @zsxwing The build and tests have passed. Request you to have a look and merge as you get time. Thanks!

**Comment by fidato13** [comment]
ping @rxin @srowen @zsxwing The build and tests have passed. Request you to have a look and merge as you get time. Thanks!

**Comment by fidato13** [comment]
ping @rxin @srowen @zsxwing The build and tests have passed. Request you to have a look and merge as you get time. Thanks!

**Comment by fidato13** [comment]
ping @rxin @srowen @zsxwing The build and tests have passed. Request you to have a look and merge as you get time. Thanks!

**Comment by srowen** [comment]
@fidato13 I've gotten 5 pings in the past week. Please address the person you're working with for the review and give people time to reply.

**Comment by fidato13** [comment]
Sure, I had tried to involve all the persons having their previous commits on the file(as mentioned in the guideline). I will remove all but Reynold from the list. Thanks.

**Comment by rxin** [comment]
Merging in master. Thanks.

**Pull request closed without merging**
