### PR TITLE
[SPARK-35340][PYTHON] Standardize TypeError messages for unsupported basic operations

### PR DESCRIPTION
**Pull request by xinrong-meng**
### What changes were proposed in this pull request?
The PR is proposed to standardize TypeError messages for unsupported basic operations by:
- Capitalize the first letter
- Leverage TypeError messages defined in `pyspark/pandas/data_type_ops/base.py`
- Take advantage of the utility `is_valid_operand_for_numeric_arithmetic` to save duplicated TypeError messages

Related unit tests should be adjusted as well.

### Why are the changes needed?
Inconsistent TypeError messages are shown for unsupported data-type-based basic operations.

Take addition's TypeError messages for example:
- addition can not be applied to given types.
- string addition can only be applied to string series or literals.

Standardizing TypeError messages would improve user experience and reduce maintenance costs.

### Does this PR introduce _any_ user-facing change?
No user-facing behavior change. Only TypeError messages are modified.

### How was this patch tested?

Unit tests.

Keyword: SPARK-35337

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]

**Comment by xinrong-databricks** [comment]
Hadoop 2 build with SBT failed retriggered tests.

**Comment by xinrong-databricks** [comment]
CC @ueshin @itholic

**Comment by xinrong-databricks** [comment]
```
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 403.
  API rate limit exceeded for user ID 10925265.

  Rate limit remaining: 0/5000
  Rate limit reset at: 2021-07-07 20:38:12 UTC

  To increase your GitHub API rate limit
  - Use `usethis::browse_github_pat()` to create a Personal Access Token.
  - Use `usethis::edit_r_environ()` and add the token as `GITHUB_PAT`.
Execution halted
```
Retriggered tests

**Comment by HyukjinKwon** [comment]
retest this please

**Review by ueshin — APPROVED** [review]
LGTM.

**Comment by ueshin** [comment]
Thanks! merging to master/3.2.

**Pull request closed without merging**
