### PR TITLE
[SPARK-25290][Core][Test] Reduce the size of acquired arrays to avoid OOM error

### PR DESCRIPTION
**Pull request by viirya**
## What changes were proposed in this pull request?

`BytesToBytesMapOnHeapSuite`.`randomizedStressTest` caused `OutOfMemoryError` on several test runs. Seems better to reduce memory usage in this test.

## How was this patch tested?

Unit tests.

### CODE REVIEW

**Comment by viirya** [comment]
cc @cloud-fan @HyukjinKwon

**Comment by cloud-fan** [comment]
do we have a memory leak here? It seems these arrays are allocated in the loop and can be released soon.

**Comment by viirya** [comment]
The allocated arrays are put in a HashMap and are iterated after the loop, to retrieve and compare with elements from the `BytesToBytesMap`.

**Comment by viirya** [comment]
retest this please.

**Comment by viirya** [comment]
@cloud-fan Ok. Changed as suggestion.

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Pull request closed without merging**
