### PR TITLE
[SPARK-32021][SQL] Increase precision of seconds and fractions of `make_interval`

### PR DESCRIPTION
**Pull request by MaxGekk**
### What changes were proposed in this pull request?
Change precision of seconds and its fraction from 8 to 18 to be able to construct intervals of max allowed microseconds value (long).

### Why are the changes needed?
To improve UX of Spark SQL.

### Does this PR introduce _any_ user-facing change?
Yes

### How was this patch tested?
- Add tests to IntervalExpressionsSuite
- Add an example to the `MakeInterval` expression
- Add tests to `interval.sql`

### CODE REVIEW

**Comment by MaxGekk** [comment]
@dongjoon-hyun @juliuszsompolski Please, review this PR.

**Comment by dongjoon-hyun** [comment]
Thank you for pinging me, @MaxGekk .

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @MaxGekk .
Merged to master.

**Comment by dongjoon-hyun** [comment]
Could you make a backporting PR to branch-3.0?

**Comment by MaxGekk** [comment]
@dongjoon-hyun This is the backport https://github.com/apache/spark/pull/28878

**Pull request closed without merging**
