### PR TITLE
[SPARK-6122][Core] Upgrade Tachyon client version to 0.6.1.

### PR DESCRIPTION
**Pull request by calvinjia**
Changes the Tachyon client version from 0.5 to 0.6 in spark core and distribution script.

New dependencies in Tachyon 0.6.0 include

commons-codec:commons-codec:jar:1.5:compile
io.netty:netty-all:jar:4.0.23.Final:compile

These are already in spark core.

### CODE REVIEW

**Comment by haoyuan** [comment]
@aarondav @pwendell

**Comment by zzcclp** [comment]
why to close this RP?

**Comment by calvinjia** [comment]
@zzcclp Tachyon client has a new api so I will update the relevant spark code and test before reopening this.

**Comment by calvinjia** [comment]
@aarondav @pwendell 
I've updated the client interface and tested it with basic count/wordcount and off heap storage.

**Comment by haoyuan** [comment]
Ok to test.

**Comment by haoyuan** [comment]
jenkins, test this please

**Comment by haoyuan** [comment]
Jenkins, test this please

**Comment by calvinjia** [comment]
@haoyuan @pwendell @aarondav

I've updated the version to the recently released 0.6.1. The dependency info is the same and the api has not changed.

**Comment by aarondav** [comment]
LGTM.

@pwendell Since this touches Spark's dependencies, would you like to sign off?

**Comment by pwendell** [comment]
LGTM

**Comment by aarondav** [comment]
Merged into master, thanks!

**Comment by JoshRosen** [comment]
The master SBT build is currently broken for a few Hadoop profiles due to dependency issues.  Do you think that this patch may have been responsible?  I noticed that it wasn't tested by Jenkins prior to being merged (the last test was 18 days ago with an earlier version of the patch).  See https://amplab.cs.berkeley.edu/jenkins/job/Spark-Master-SBT/1940/

**Comment by calvinjia** [comment]
@JoshRosen Just from a quick glance at the output log, it seems to be a style issue (line > 100 characters). I don't think this patch should have caused the issues, since the errors have been the same as the ones since build #1937.

**Comment by srowen** [comment]
@calvinjia yup this was fall-out from my mistake yesterday at https://github.com/apache/spark/pull/5128/files It's already patched thanks to Reynold, so that should be fine now.

**Comment by calvinjia** [comment]
@srowen Oh I see the build still failed after the fix to that patch. Strange that there would be issues between now and the last test run for this patch since there should not have been any dependency changes.

**Comment by JoshRosen** [comment]
Patrick reverted this patch in 6cd7058b369ec8d01938961f148734ee9eaf76de and it appears that reverting it has fixed the builds: https://amplab.cs.berkeley.edu/jenkins/job/Spark-Master-SBT/1947/

**Comment by aarondav** [comment]
The build only broke when compiled against other versions of Hadoop, so
it's likely that some of the dependency changes overwrote the deps of other
Hadoop versions.

**Comment by syepes** [comment]
is there any change this PR will get merged?

**Comment by srowen** [comment]
@syepes I think the problem would have to be fixed no? you can try applying the patch an examining what changes about dependencies in the builds that broke. Narrowing it down that much may help everyone understand how to fix it.

**Comment by calvinjia** [comment]
@srowen @syepes I'm planning to re-open this when Tachyon 0.6.2 is available. There were two problems encountered in the tests:

1. HTTPClient version mismatch: Selenium (used for UI tests) requires version 4.3.x, and Tachyon included 4.2.5 through a transitive dependency of its shaded thrift jar. To address this, Tachyon 0.6.2 will promote the transitive dependencies of the shaded jar so they can be excluded in spark.

2. Jackson-Mapper-ASL version mismatch: In lower versions of hadoop-client (ie. 1.0.4), version 1.0.1 is included. The parquet library used in spark sql requires version 1.8+. Its unclear to me why upgrading tachyon-client would cause this dependency to break. The solution was to exclude jackson-mapper-asl from hadoop-client. If there is a better way to handle this issue, please let me know.

**Pull request closed without merging**
