### PR TITLE
[SPARK-49712][SQL] Remove encoderFor from connect-client-jvm

### PR DESCRIPTION
**Pull request by hvanhovell**
### What changes were proposed in this pull request?
This PR removes `sql.encoderFor` from the connect-client-jvm module and replaces it by `AgnosticEncoders.agnosticEncoderFor`.

### Why are the changes needed?
It will cause a clash when we swap the interface and the implementation.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Existing tests.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
May I ask hhy this PR includes the following silently?
- #48217

**Comment by hvanhovell** [comment]
Because I messed up...

**Comment by dongjoon-hyun** [comment]
Shall we make this `Draft` to prevent accidental merging for now, please?

**Review by HyukjinKwon — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM because #48217 was merged.
Merged to master.

**Pull request closed without merging**
