### PR TITLE
[SPARK-32657][K8S] Update the log strings we check for & imports in decommission K8s

### PR DESCRIPTION
**Pull request by holdenk**
### What changes were proposed in this pull request?

Update the log strings to match the new log messages.

### Why are the changes needed?

Tests are failing

### Does this PR introduce _any_ user-facing change?

No, test only change.

### How was this patch tested?
WIP: Make sure the DecommissionSuite passes in Jenkins.

### CODE REVIEW

**Comment by holdenk** [comment]
cc @dongjoon-hyun

**Comment by dongjoon-hyun** [comment]
Thank you, @holdenk .

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM (Pending K8s IT)

**Comment by dongjoon-hyun** [comment]
Oh, does it fail?

**Comment by holdenk** [comment]
Huh this is weird that's not something I was expecting `( [ERROR] [Error] /home/jenkins/workspace/SparkPullRequestBuilder-K8s/resource-managers/kubernetes/integration-tests/src/test/scala/org/apache/spark/deploy/k8s/integrationtest/DecommissionSuite.scala:29: value WORKER_DECOMMISSION_ENABLED is not a member of object org.apache.spark.internal.config.Worker
 )`. Looks like something else might have changed in master since when I started. Let me poke at that real quickly.

**Comment by holdenk** [comment]
Looks like `3092527f7557b64ff9a5bedadfac8bb2f189a9b4` was committed and this broke the test suite. We really need to enable the K8s PRB in core.

**Comment by holdenk** [comment]
Token failure is probably unrelated, let’s see if it’s transient. Jenkins retest this please

**Review by agrawaldevesh — APPROVED** [review]
Thanks !.

**Comment by agrawaldevesh** [comment]
Lets get this in soon, so that it can unblock other PRs.

**Comment by dongjoon-hyun** [comment]
Merged to master. Thank you, @holdenk and @agrawaldevesh .

**Comment by holdenk** [comment]
Thanks @dongjoon-hyun for merging and calling my attention to the issue last night :)

**Pull request closed without merging**
