### PR TITLE
[SPARK-36808][BUILD][3.2] Upgrade Kafka to 2.8.1

### PR DESCRIPTION
**Pull request by sarutak**
### What changes were proposed in this pull request?

This PR backports SPARK-36808 (#34050) to `branch-3.2`, upgrading Kafka from `2.8.0` to `2.8.1`.

### Why are the changes needed?

Kafka `2.8.1` was released a few hours ago, which includes a bunch of bug fix.
https://downloads.apache.org/kafka/2.8.1/RELEASE_NOTES.html

As we discussed, we think it would be good to backport this change.
https://issues.apache.org/jira/browse/SPARK-36808?focusedCommentId=17492248&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17492248

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

CIs.

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM (Pending CIs).

**Comment by dongjoon-hyun** [comment]
cc @ijuma

**Review by ijuma — APPROVED** [review]
Thanks, LGTM too.

**Comment by sarutak** [comment]
Thank you @dongjoon-hyun  and @ijuma ! Merging to `branch-3.2`.

**Comment by dongjoon-hyun** [comment]
Thank you, @sarutak and @ijuma .

**Pull request closed without merging**
