### PR TITLE
[SPARK-11962] Added getAsOpt[T]() methods to enable getting values optionally.

### PR DESCRIPTION
**Pull request by aa8y**
Adds methods to get values from a row object optionally. I personally have an implicit class which does this and which I use a lot. I think this feature would be immensely beneficial for everyone. Please let me know if these need changes.

### CODE REVIEW

**Comment by rxin** [comment]
Jenkins, test this please.

**Comment by aa8y** [comment]
Sorry, I am new to this. Does what you wrote trigger a Jenkins build? If yes, that's really cool!

**Comment by rxin** [comment]
Yes - except there is a bug that somehow Jenkins is ignoring me...!

**Comment by aa8y** [comment]
Sorry. I ran the tests and I thought they passed on my machine. A few tests
couldn't be run (like docker) but these looked good. I'll take another look
into it.

Thanks,
Arun

**Comment by JoshRosen** [comment]
Looks like this PR is now broken by a bad merge with master. Would you mind closing for now and re-opening once things are fixed? Thanks!

**Comment by andrewor14** [comment]
@aa8y looks like the diff is screwed up because you accidentally merged in changes from other branches. Would you mind closing this PR or restoring the original diff?

**Comment by aa8y** [comment]
Sure. This is an old PR anyway. I did not know the PRs update themselves with new commits.  #10247 is the PR I am working on now. I'll make the recommended changes and push a new commit. Thanks!

**Pull request closed without merging**
