### PR TITLE
[SPARK-49284][CONNECT][SQL] Create a shared Catalog interface

### PR DESCRIPTION
**Pull request by hvanhovell**
### What changes were proposed in this pull request?
This PR creates a shared Catalog interface. We also move the interfaces to sql/api.

### Why are the changes needed?
We are creating a shared Scala Spark SQL interface for Classic and Connect.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Existing tests.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]

**Comment by xinrong-meng** [comment]
LGTM thank you!

btw ClientStreamingQuerySuite and FlatMapGroupsWithStateStreamingSuite seem flaky and also fail in my PR.

**Review by xinrong-meng — APPROVED** [review]

**Comment by LuciferYang** [comment]
@HyukjinKwon Have there been any major changes to the startup process of the connect-server recently? I've noticed that it has frequently failed to start during recent GA tests, such as the current pr:

- https://github.com/hvanhovell/spark/actions/runs/10706361897/job/29683945623
image

and other cases:
- https://github.com/TongWei1105/spark/actions/runs/10713505479/job/29705646577
- https://github.com/liujiayi771/spark/actions/runs/10712981038/job/29704300464
- https://github.com/hvanhovell/spark/actions/runs/10712663831/job/29703447623

and daily tests:
- https://github.com/apache/spark/actions/runs/10694846297/job/29647315383
- https://github.com/apache/spark/actions/runs/10702260700/job/29670054329
- https://github.com/apache/spark/actions/runs/10693497231/job/29643754734

**Comment by HyukjinKwon** [comment]
Yeah, https://github.com/apache/spark/pull/47994 should fix it

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
