### PR TITLE
[WIP][SPARK-29845][SQL]PostgreSQL dialect: cast to decimal

### PR DESCRIPTION
**Pull request by iRakson**
### What changes were proposed in this pull request?
cast to decimal behaviour in SparkSQL is made consistent with PostgreSQL when spark.sql.dialect is set to PostgreSQL.

### Why are the changes needed?
SparkSQL and PostgreSQL behaviour is very different when casting to decimal.
For e.g: 
select cast('abc' to decimal) in SparkSQL gives null.
select cast('abc' to decimal) in PostgreSQL gives "invalid input syntax for type numeric"

### Does this PR introduce any user-facing change?
Yes.

### How was this patch tested?
Manually tested. Test cases will be added soon

### CODE REVIEW

**Comment by iRakson** [comment]
cc @cloud-fan @maropu

**Comment by maropu** [comment]
Please remove WIP before requesting reviews? Anyway, can you wait until https://github.com/apache/spark/pull/26472 merged? That's because that pr is adding a base class for this kind of Pg-specific casts.

**Comment by dongjoon-hyun** [comment]
Thank you for contribution, @iRakson . As you know, unfortunately, we decided to remove PostgreSQL dialect via SPARK-30125 (#26763). Sorry about that. I'll close this PR, too.

**Comment by cloud-fan** [comment]
We can still have this feature, but not under pgsql dialect. The ANSI SQL standard also requires us to throw exception when casting invalid strings to numbers.

@iRakson can you open new PRs to bring back your cast behaviors changes under the `spark.sql.ansi.enabled` flag?

**Comment by iRakson** [comment]
Yeah Sure. I will.

**Pull request closed without merging**
