### PR TITLE
[SPARK-14589][SQL] Enhance DB2 JDBC Dialect docker tests

### PR DESCRIPTION
**Pull request by lresende**
## What changes were proposed in this pull request?

Enhance the DB2 JDBC Dialect docker tests as they seemed to have had some issues on previous merge causing some tests to fail.
## How was this patch tested?

By running the integration tests locally.

### CODE REVIEW

**Comment by lresende** [comment]
@JoshRosen please review, these are the merge issues I mentioned yesterday, and these changes are passing my local tests as well.

**Comment by lresende** [comment]
Jenkins, retest this please.

**Comment by JoshRosen** [comment]
Can you fix scalastyle?

**Comment by lresende** [comment]
@JoshRosen All good now.

**Comment by lresende** [comment]
@JoshRosen ping

**Comment by srowen** [comment]
Jenkins retest this please

**Comment by srowen** [comment]
This test is ignored now anyway, and given @lresende 's confidence this actually gets it working, LGTM

**Comment by srowen** [comment]
Merged to master/2.0

**Pull request closed without merging**
