### PR TITLE
[SPARK-13067][SQL] workaround for a weird scala reflection problem

### PR DESCRIPTION
**Pull request by cloud-fan**
A simple workaround to avoid getting parameter types when convert a logical plan to json.  Note that this bug only exists locally, but ok on jenkins, not sure why...

### CODE REVIEW

**Comment by cloud-fan** [comment]
CC @davies @yhuai @marmbrus 

@davies can you try it out locally?

**Comment by cloud-fan** [comment]
retest this please

**Comment by cloud-fan** [comment]
retest this please

**Comment by rxin** [comment]
"。" replace with "." ?

**Comment by davies** [comment]
Tested it locally, test passed. I'm merging this into master, thanks!

**Comment by rxin** [comment]
@cloud-fan is this fixing a bug? If yes, please add a test somewhere.

**Comment by marmbrus** [comment]
Existing tests were failing locally, but not on Jenkins.  We are not sure why.

**Comment by rxin** [comment]
OK got it. @cloud-fan  Please add that to the pull request description next time.

**Comment by cloud-fan** [comment]
Sorry I thought the JIRA description tells it, will add it to PR description next time.

**Comment by rxin** [comment]
Yea the pull request description gets merged as commit description, and is the only thing that sticks around forever.

**Comment by atronchi** [comment]
How can we workaround this problem when using 1.6.1?

**Comment by atronchi** [comment]
This solution does not seem to work for datasets on tables using complex types. e.g. Array[Int] still throws the exception `java.lang.AssertionError: assertion failed: Unsound substitution from List(type T, type U) to List()`

**Comment by cloud-fan** [comment]
@atronchi can you create a JIRA and put the code that can reproduce the bug? thanks!

**Comment by atronchi** [comment]
The solution mentioned in [SPARK-17424] by @rdblue fixes this issue.

**Pull request closed without merging**
