### PR TITLE
[SPARK-32099][DOCS] Remove broken link in cloud integration documentation

### PR DESCRIPTION
**Pull request by guykhazma**
### What changes were proposed in this pull request?

The 3rd link in `IBM Cloud Object Storage connector for Apache Spark` is broken. The PR removes this link.

### Why are the changes needed?

broken link

### Does this PR introduce _any_ user-facing change?

yes, the broken link is removed from the doc.

### How was this patch tested?

doc generation passes successfully as before

### CODE REVIEW

**Comment by dilipbiswal** [comment]
cc @skambha @huaxingao Can you please help check if this link https://developer.ibm.com/?s=installing-running-stocator-apache-spark-ibm-cloud-object-storage has moved some place else.

**Comment by guykhazma** [comment]
@dilipbiswal @skambha @huaxingao the preference for now is to remove this link entierly.

**Comment by HyukjinKwon** [comment]
ok to test

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @guykhazma . Merged to master/3.0.
The GitHub (https://github.com/CODAIT/stocator) seems to have an enough resource for that. We can add a new link later if it is found later.

**Pull request closed without merging**
