### PR TITLE
[SPARK-12299][CORE] Remove history serving functionality from Master

### PR DESCRIPTION
**Pull request by BryanCutler**
Remove history server functionality from standalone Master.  Previously, the Master process rebuilt a SparkUI once the application was completed which sometimes caused problems, such as OOM, when the application event log is large (see SPARK-6270).  Keeping this functionality out of the Master will help to simplify the process and increase stability.

Testing for this change included running core unit tests and manually running an application on a standalone cluster to verify that it completed successfully and that the Master UI functioned correctly.  Also added 2 unit tests to verify killing an application and driver from MasterWebUI makes the correct request to the Master.

### CODE REVIEW

**Comment by BryanCutler** [comment]
Removing the history serving from Master is pretty straightforward, but leaves some gaps in the UI and serving JSON requests.  I am marking this as WIP to get some discussion on how to best handle a few of these points.

1. Currently, the Master page has a the application name as a link to the Application UI Page.  While the app is running, it has a link to the live application server, then when complete the Master replaces that link with one for the rebuilt UI.  
Now, since there is no rebuilt UI, I left the live link, then once complete the application name is static and does not provide a link

2. Similarly, the Master Application page has a link to "Application Detail" to open up the Application UI Page.  While the app is running, it has a link to the live application server, then when complete the Master replaces that link with one for the rebuilt UI.  
Now, the live link is still there while the application is running and once complete the "Application Detail" is removed entirely.

3. Currently, the Master follows the REST API to serve JSON data and the MasterPage extends the trait `UIRoot` to allow requests for `ApiRootResource`s. 
Since a SparkUI with application info is required to serve these resources, now MasterPage no longer extends this trait.

4. Although the Master can no long serve `ApiRootResource`s, it still can list applications and also redirect resource requests to any currently running application.
I put in some functionality that redirects requests, but I stopped short of serving the application list (the "/applications" endpoint) because it was getting a little messy.  Is this something that is worth having in?

**Comment by BryanCutler** [comment]
TODO - fix docs to not list master as REST API

**Comment by BryanCutler** [comment]
cc @andrewor14, @squito for thoughts on above

**Comment by BryanCutler** [comment]
ping @andrewor14 , @squito 
Wondering if standalone Master should continue to serve/redirect JSON requests after removing history serving functionality?

**Comment by andrewor14** [comment]
Ah, that's too bad. When I first proposed to do this I did not think there would be a REST API. Overall I'm still in favor of removing the functionality from Master. I don't have strong opinions about what we should do about the REST API but I believe that's less important; I don't think many people depend on the specific get SparkUI call from the standalone Master.

I believe @JoshRosen has some opinions about how we should move forward in Spark 2.0.

**Comment by BryanCutler** [comment]
Hi @JoshRosen , what are your thoughts on the Master REST API if history is no longer available?

**Comment by JoshRosen** [comment]
The Master REST API functionality which existed prior to the unification with the Spark driver REST API should still work after this change, so we shouldn't break or remove those methods.

I think that there are a few ways to handle this JIRA / task, some more complex than others. The only "must have" requirement for 2.0 is removing the HistoryServer functionality; other cleanup and interface refactoring can be deferred for later. So, I wouldn't try to do any major refactoring or cleanup; just remove the feature so we get the API / functionality change in and address the other pieces later.

**Comment by BryanCutler** [comment]
@JoshRosen @andrewor14 , just to be clear what needs to be done here - we want to keep the ability for Master to rebuild a `SparkUI` to be able to respond to REST API calls, but just not automatically rebuild every `SparkUI` when complete?  Also, need to remove UI links to completed apps, etc.

**Comment by JoshRosen** [comment]
I don't think that the Master should have any event-log consumption logic whatsoever.

**Comment by BryanCutler** [comment]
Maybe I'm missing something then.  Most of the REST API defined in [ApiRootResource](https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/status/api/v1/ApiRootResource.scala#L66) depends on having a `SparkUI` object which the Master currently creates by playing back event-log files.  How can we keep this API in the Master and remove event-log consumption without some major refactoring?  Is there some other way for the Master to create a `SparkUI` on the fly?

**Comment by steveloughran** [comment]
There's a more fundamental issue which the history server has too: log replay is too expensive for long-lived applications. replay time is O(jobs)+O(stages), even if GC keeps those numbers in the main UI down.

I'm not proposing a solution other than to observe that it's essentially some form of ETL operation, one that may be possible to do prepare for before building the UI up, just running through the events and discarding old/surplus ones. Has anyone played with something like that ?

**Comment by andrewor14** [comment]
@BryanCutler Actually, for simplicity I would recommend simply removing the REST API related to the Master serving history UIs. Then you can just remove the actual history serving functionality itself easily. I don't see any reason we'll possibly add it back after Spark 2.0 so there's no reason to keep around a REST API that does not have a backing functionality.

Also I haven't heard of anyone relying on this obscure REST API so I don't think it matters a lot. We should never have added this API in the first place.

**Comment by BryanCutler** [comment]
Thanks @andrewor14 , that sounds fine to me also - I just wanted to make sure I didn't remove some functionality that some people relied on.  I already had everything removed, just need to clean up and merge with latest.  I'm on vacation now, but I should be able to finish this up next week.

**Comment by andrewor14** [comment]
Sure, thanks for your work!

**Comment by andrewor14** [comment]
Also, please update `docs/monitoring.md` as well

**Comment by BryanCutler** [comment]
jenkins retest this please

**Comment by BryanCutler** [comment]
jenkins retest this please

**Comment by BryanCutler** [comment]
jenkins retest this please

**Comment by BryanCutler** [comment]
@andrewor14 or @JoshRosen , this is ready for review whenever you get a chance, thanks!

**Comment by BryanCutler** [comment]
jenkins retest this please

**Comment by BryanCutler** [comment]
jenkins retest this please

**Comment by BryanCutler** [comment]
Ping @andrewor14 , please review.  Is this still slated for 2.0 release?  Thanks!

**Comment by andrewor14** [comment]
LGTM! @JoshRosen should have a look too. Also retest this please because this hasn't run tests in a while.

**Comment by andrewor14** [comment]
Merging into master 2.0. Thanks for your work @BryanCutler.

**Comment by BryanCutler** [comment]
Great, thanks!

**Comment by stanzhai** [comment]
We've just upgraded our Spark cluster from 1.6.x to 2.x, I found that the REST APIs from Spark MasterUI is unavailable.

It's important for us to use the REST APIs to monitor our Applications. I believe that some other people would rely on this function too.

Right now, the only way to get them is using the Spark Master WebUI, it's too bad.

It would be great that we have some REST APIs to access Master、Workers and Applications information from Master.

@BryanCutler @andrewor14 @JoshRosen

**Comment by squito** [comment]
@stanzhai I think you have a good point.  I don't think removing the REST API for access to basic app info in the standalone master was really necessary for the original goals of SPARK-12299.  But I'd open another jira, for restoring an api with the same info in the master UI, and move discussion there.

**Comment by squito** [comment]
whoops, now I see this is already present as https://issues.apache.org/jira/browse/SPARK-18683

**Pull request closed without merging**
