### PR TITLE
SPARK-13312 [MLlib] Update java train-validation-split example in ml-guide

### PR DESCRIPTION
**Pull request by JeremyNixon**
Response to JIRA https://issues.apache.org/jira/browse/SPARK-13312.

This contribution is my original work and I license the work to this project.

### CODE REVIEW

**Comment by srowen** [comment]
LGTM

**Comment by srowen** [comment]
Jenkins test this please

**Comment by srowen** [comment]
@JeremyNixon please fix the title
https://cwiki.apache.org/confluence/display/SPARK/Contributing+to+Spark

**Comment by JeremyNixon** [comment]
Sean, thanks - title fixed.

**Comment by srowen** [comment]
Merged to master/1.6

**Pull request closed without merging**
