### PR TITLE
[SPARK-40124][SQL][TEST][3.3] Update TPCDS v1.4 q32 for Plan Stability tests

### PR DESCRIPTION
**Pull request by mskapilks**
### What changes were proposed in this pull request?
This is port of SPARK-40124 to Spark 3.3. Fix query 32 for TPCDS v1.4

### Why are the changes needed?
Current q32.sql seems to be wrong. It is just selection `1`.
Reference for query template: https://github.com/databricks/tpcds-kit/blob/eff5de2c30337b71cc0dc1976147742d2c65d378/query_templates/query32.tpl#L41

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Test change only

### CODE REVIEW

**Comment by mskapilks** [comment]
Seems the GitHub action to generate benchmark files was added in Spark 3.4 only. Any idea on how to generate those files for Spark 3.3 as well?

**Comment by kazuyukitanimura** [comment]
> Seems the GitHub action to generate benchmark files was added in Spark 3.4 only. Any idea on how to generate those files for Spark 3.3 as well?

@mskapilks The TPCDS benchmarks had a bug before Spark 3.4 the results are incorrect. I don't think you need to benchmark results for this back port IMO

**Comment by kazuyukitanimura** [comment]
cc @dongjoon-hyun @viirya @huaxingao @sunchao @parthchandra @wangyum @Swinky

**Review by kazuyukitanimura — APPROVED** [review]
LGTM (non-binding)

**Comment by dongjoon-hyun** [comment]
Thank you for pinging me, @kazuyukitanimura .

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Merged to branch-3.3 for Apache Spark 3.3.1.

**Comment by mskapilks** [comment]
Thanks for the review. 
Make sense on not updating benchmark file for this pr. Will raise PR for other branches as well now.

**Pull request closed without merging**
