### PR TITLE
SPARK-16636 Add CalendarIntervalType to documentation

### PR DESCRIPTION
**Pull request by terma**
## What changes were proposed in this pull request?

Add CalendarIntervalType to SQL Data Types in documentation

## How was this patch tested?

unit tests

@marmbrus please review

### CODE REVIEW

**Comment by srowen** [comment]
@HyukjinKwon is this OK by you?

**Comment by HyukjinKwon** [comment]
I am OK but I remember there are some discussions about whether this type should be exposed or not and I could not track down the conclusion.

**Comment by srowen** [comment]
CC @cloud-fan for https://github.com/apache/spark/pull/13008#r62947902 and @yhuai for https://github.com/apache/spark/pull/8597#r38769233 as they might be what you're referring to?

**Comment by HyukjinKwon** [comment]
It seems there are several ones here and there. Maybe https://github.com/apache/spark/pull/15751#issuecomment-258518577 is related too because it is about supporting reading/writing out that type where it might refer that we can explicitly give the schema with that type.

**Comment by HyukjinKwon** [comment]
(FWIW, I am OK but just worried if it might be supposed to be internal type, maybe in the future)

**Comment by terma** [comment]
@srowen As I understood ```CalendarIntervalType``` only for compatibility with similar type in ```Hive```. So probably better to mark it as internal and close jira?

**Comment by HyukjinKwon** [comment]
^ I want to be very sure if we are not going to expose this or not. Could any SQL committer guy or PMC confirm this?

> `CalendarIntervalType` only for compatibility with similar type in `Hive`.

This means a lot of things for example,

- we might have to hide this

```scala
scala> import org.apache.spark.sql.types.CalendarIntervalType
import org.apache.spark.sql.types.CalendarIntervalType
```

-  maybe disallow explicitly giving this type as a schema as it is not exposed.

-  maybe we should not support reading/writing out this type as raised in https://github.com/apache/spark/pull/15751#issuecomment-258518577 

and etc.

**Comment by cloud-fan** [comment]
Actually `CalendarInterval` is already exposed to users, e.g. we can call `collect` on a DataFrame with `CalendarIntervalType` field, and get rows containing `CalendarInterval`. We don't support reading/writing `CalendarIntervalType` though.

So I'm ok to add documents for it.

**Comment by HyukjinKwon** [comment]
Then, It looks okay to me as describing the current state and I just checked it after building the doc with this, and also

we can already use it as below:

```scala
scala> sql("SELECT interval 1 second").schema(0).dataType.getClass
res0: Class[_ <: org.apache.spark.sql.types.DataType] = class org.apache.spark.sql.types.CalendarIntervalType$

scala> sql("SELECT interval 1 second").collect()(0).get(0).getClass
res1: Class[_] = class org.apache.spark.unsafe.types.CalendarInterval
```

```scala
scala> val rdd = spark.sparkContext.parallelize(Seq(Row(new CalendarInterval(0, 0))))
rdd: org.apache.spark.rdd.RDD[org.apache.spark.sql.Row] = ParallelCollectionRDD[0] at parallelize at <console>:32

scala> spark.createDataFrame(rdd, StructType(StructField("a", CalendarIntervalType) :: Nil))
res1: org.apache.spark.sql.DataFrame = [a: calendarinterval]
```

Another meta concern is, `org.apache.spark.unsafe.types.CalendarInterval` seems undocumented in both scaladoc/javadoc (entire `unsafe` module). Once we document this as a weak promise for this API, then we might have to keep this for backward compatibility.

Maybe just describe it as SQL dedicated type or not supported for now with some `Note:` rather than describing it?

**Comment by cloud-fan** [comment]
CC @rxin, if we are going to expose `CalendarInterval` and `CalendarIntervalType` officially, shall we move `CalendarInterval` to the same package as `Decimal`, or create a new class as the external representation of `CalendarIntervalType`?

**Comment by gatorsmile** [comment]
@terma To avoid confusing the Spark SQL users, we might not document it? How about closing this PR now? Thanks!

**Pull request closed without merging**
