### PR TITLE
[SPARK-42220][CONNECT][BUILD] Upgrade buf from 1.12.0 to 1.13.1

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
 The pr aims to upgrade buf from 1.12.0 to 1.13.1.

### Why are the changes needed?
image
image
Release Notes: https://github.com/bufbuild/buf/releases
https://github.com/bufbuild/buf/compare/v1.12.0...v1.13.1

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA.

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
This PR seems to raise the minimum requirement of dev environment.
May I ask if this is a blocker for Apache Spark 3.4 release, @panbingkun ? Or, is it okay to have this at Spark 3.5 only?

cc @xinrong-meng

**Comment by HyukjinKwon** [comment]
Hm, I would prefer to merge it to 3.4 too (since Spark Connect is alpha component that has not been released yet, and accepts changes more aggressively in general)

**Review by dongjoon-hyun — APPROVED** [review]
Got it. +1 for backporting.

**Comment by dongjoon-hyun** [comment]
Merged to master/3.4. Thank you all.

**Pull request closed without merging**
