### PR TITLE
[SPARK-15290] [BUILD] Move annotations, like @Since / @DeveloperApi, into spark-tags

### PR DESCRIPTION
**Pull request by srowen**
## What changes were proposed in this pull request?

(See https://github.com/apache/spark/pull/12416 where most of this was already reviewed and committed; this is just the module structure and move part. This change does not move the annotations into test scope, which was the apparently problem last time.)

Rename `spark-test-tags` -> `spark-tags`; move common annotations like `@Since` to `spark-tags`
## How was this patch tested?

Jenkins tests.

### CODE REVIEW

**Comment by rxin** [comment]
cc @JoshRosen

**Comment by srowen** [comment]
I'm going to proceed with this since it's better to get it done for 2.0 and enable easier management of annotations going forward. We essentially reviewed this in https://github.com/apache/spark/pull/12416 and it unblocks SPARK-14613, marked for 2.0

**Comment by rxin** [comment]
Actually josh is on vacation. Definitely go ahead. I looked at it and it seemed ok. I'm not a build expert though.

**Comment by srowen** [comment]
Merged to master/2.0

**Pull request closed without merging**
