### PR TITLE
[SPARK-20089] [SQL] [TEST] Added DESC FUNCTION and DESC EXTENDED FUNCTION to SQLQueryTestSuite

### PR DESCRIPTION
**Pull request by gatorsmile**
### What changes were proposed in this pull request?
`DESC FUNCTION` and `DESC EXTENDED FUNCTION` should be added to `SQLQueryTestSuite` for us to review the outputs of each function.

### How was this patch tested?
N/A

### CODE REVIEW

**Comment by gatorsmile** [comment]
retest this please

**Comment by rxin** [comment]
Hm - so this would require us to update the test suite every time there is an update to the docs?

**Comment by gatorsmile** [comment]
@rxin Yes! After we add it to SQLQueryTestSuite, we can copy and paste the contents to the document in http://spark.apache.org/docs/latest/sql-programming-guide.html So far, our Spark SQL users have no idea which functions we provide unless they read the source codes.

In the future, if anybody update the docs in the source codes, they have to update the test suite. Then,  we can add a reminder in the test case to let them also update the document. 

Do you like the idea?

**Comment by gatorsmile** [comment]
retest this please

**Comment by viirya** [comment]
To document the functions available sounds good. But I am not sure if we want to put this into test. Sounds like we use the test as document generator.

**Comment by gatorsmile** [comment]
@viirya That is not only for document generator. It can help us review/correct the output of `DESC FUNCTIONS EXTENDED`. You can find many inconsistent parts we should correct when reading  `describe-functions-extended.sql.out`.

Actually, I also think we need to output the physical plans for many important queries in `SQLQueryTestSuite `. That can help us capture the accidental plan changes when we fix the bugs.

**Comment by viirya** [comment]
I am not sure if it helps review by dumping the output of `DESC EXTENDED FUNCTION` to the test. We may not frequently change the output as I see. IMHO, It is hard to tell which is "correct" output for a function, except for obvious incorrectness like wrong parameters, results. It is also hard to check the consistency of output in a 3000-lines text file.

**Pull request closed without merging**
