### PR TITLE
[SPARK-48172][SQL] Fix escaping issues in JDBCDialects

### PR DESCRIPTION
**Pull request by mihailomilosevic2001**
This PR is a fix of https://github.com/apache/spark/pull/46437. The previous PR was reverted as `LONGTEXT` is not supported by all dialects.

### What changes were proposed in this pull request?
Special case escaping for MySQL and fix issues with redundant escaping for ' character.
New changes introduced in the fix include change `LONGTEXT` -> `VARCHAR(50)`, as well as fix for table naming in the tests.

### Why are the changes needed?
When pushing down startsWith, endsWith and contains they are converted to LIKE. This requires addition of escape characters for these expressions. Unfortunately, MySQL uses ESCAPE '\' syntax instead of ESCAPE '' which would cause errors when trying to push down.

### Does this PR introduce any user-facing change?
Yes

### How was this patch tested?
Tests for each existing dialect.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by yaooqinn** [comment]
https://github.com/apache/spark/actions/workflows/build_branch35.yml
https://github.com/apache/spark/actions/workflows/build_branch34.yml

These daily jobs for branch-3.4 and 3.5 seem to be broken by this PR?

cc @cloud-fan @mihailom-db , also cc @LuciferYang

**Comment by mihailom-db** [comment]
Getting back from the vacation tomorrow, will take a look at this early in the morning.

**Comment by yaooqinn** [comment]
Thank you @mihailom-db

**Comment by mihailom-db** [comment]
Found the error. It seems to be due to the JDK version under which the jobs are run. https://github.com/apache/spark/pull/46803 this PR proposes a change for 3.4. @yaooqinn @cloud-fan

**Pull request closed without merging**
