### PR TITLE
[SPARK-38127][SQL][TESTS] Fix bug of `EnumTypeSetBenchmark` and update benchmark result

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
`EnumTypeSetBenchmark`  use to compare the `create` and `contains` performance of `EnumSet` and `HashSet`.Before this PR, there are some logical errors in the bench case, for example `testContainsOperation `:

https://github.com/apache/spark/blob/9d0563733bacc39ffbb7a07e5d3fc6de71d0cfb3/sql/catalyst/src/test/scala/org/apache/spark/sql/connector/catalog/EnumTypeSetBenchmark.scala#L102-L110

`Use HashSet` circulates 100000 times(`valuesPerIteration `is 100000) and  `Use EnumSet` circulates only once.

So this pr fix this bug and update benchmark result. 

### Why are the changes needed?
Bug fix.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA

### CODE REVIEW

**Comment by LuciferYang** [comment]
cc @srowen

**Comment by srowen** [comment]
Is the idea simply that the benchmark was run on substantially different hardware before?

**Comment by LuciferYang** [comment]
> Is the idea simply that the benchmark was run on substantially different hardware before?

No, this pr focuses on bug fix, for example `testContainsOperation`:

https://github.com/apache/spark/blob/9d0563733bacc39ffbb7a07e5d3fc6de71d0cfb3/sql/catalyst/src/test/scala/org/apache/spark/sql/connector/catalog/EnumTypeSetBenchmark.scala#L102-L110

`Use HashSet` circulates 100000 times(`valuesPerIteration `is 100000) and  `Use EnumSet` circulates only once.


It's my bad, I made a mistake in writing this case before.

**Review by srowen — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by LuciferYang** [comment]
Thanks all

**Pull request closed without merging**
