### PR TITLE
[SPARK-7522] [EXAMPLES] Removed angle brackets from dataFormat option

### PR DESCRIPTION
**Pull request by BryanCutler**
As is, to specify this option on command line, you have to escape the angle brackets.

### CODE REVIEW

**Comment by srowen** [comment]
Ah, so you literally have to write `--\<dataFormat\>`? definitely an oversight then. LGTM

**Comment by srowen** [comment]
ok to test

**Comment by mengxr** [comment]
Merged into master and branch-1.4. @BryanCutler Could you send another PR to branch-1.3? Thanks!

**Comment by BryanCutler** [comment]
@mengxr sure, no problem.  I saw on the JIRA you also mentioned 1.1 and 1.2, do you need PR for those too?

**Pull request closed without merging**
