### PR TITLE
[SPARK-34688][PYTHON] Upgrade to Py4J 0.10.9.2

### PR DESCRIPTION
**Pull request by wankunde**
### What changes were proposed in this pull request?
This PR upgrade Py4J from 0.10.9.1 to 0.10.9.2 that contains some bug fixes and improvements.

* expose shell parameter in Popen inside launch_gateway. ([bartdag/py4j@220efc3](https://github.com/bartdag/py4j/commit/220efc371620c3ffa1cfe75e6bdaa710e70d9d21))
* fixed Flake8 errors ([bartdag/py4j@6c6ee9a](https://github.com/bartdag/py4j/commit/6c6ee9aedcff23ea142306ca08912822426b5f3d))

### Why are the changes needed?
To leverage fixes from the upstream in Py4J.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Jenkins build and GitHub Actions will test it out.

### CODE REVIEW

**Comment by wangyum** [comment]
ok to test.

**Comment by wangyum** [comment]
cc @HyukjinKwon

**Comment by HyukjinKwon** [comment]
ok to test

**Review by HyukjinKwon — COMMENTED** [review]
Can you describe how you got `python/lib/py4j-0.10.9.2-src.zip`? Also looks you should run `./dev/test-dependencies.sh --replace-manifest`

Otherwise, it looks pretty good

**Comment by wankunde** [comment]
Hi,  @HyukjinKwon I ran `./dev/test-dependencies.sh --replace-manifest` and update my code.

I cloned from `https://github.com/bartdag/py4j/tree/0.10.9.2/py4j-python/src/py4j`  and remove the test code. 
Then create `python/lib/py4j-0.10.9.2-src.zip` file.

**Comment by srowen** [comment]
Seems OK in any event, but do the fixes affect Spark?

**Comment by dongjoon-hyun** [comment]
+1 for @srowen 's comment.

**Comment by wankunde** [comment]
> Seems OK in any event, but do the fixes affect Spark?

Not sure, but it may give pyspark users more choice of running mode.

See https://github.com/bartdag/py4j/pull/419#issue-530983438

**Comment by HyukjinKwon** [comment]
Looks like PySpark doesn't expose Py4J's `launch_gateway`.. so virtually nothing affects. We can just leave it as is or just merge it. Either way works.

**Comment by srowen** [comment]
For reference, the diff in the py4j code is:

```
diff py4j-1/clientserver.py py4j-2/clientserver.py
149c149
<             Default is 25333.
---
>             Default is 25334.
diff py4j-1/java_gateway.py py4j-2/java_gateway.py
224c224,225
<                    enable_auth=False, cwd=None, return_proc=False):
---
>                    enable_auth=False, cwd=None, return_proc=False,
>                    use_shell=False):
275a277,278
>     :param use_shell – If True, Popen will be start the java process with
>         shell=True
327,328c330,333
<     proc = Popen(command, stdout=PIPE, stdin=PIPE, stderr=stderr,
<                  cwd=cwd, **popen_kwargs)
---
>     popen_kwargs["shell"] = use_shell
>     proc = Popen(
>         command, stdout=PIPE, stdin=PIPE, stderr=stderr, cwd=cwd,
>         **popen_kwargs)
825c830
<             Default is 25333.
---
>             Default is 25334.
2087c2092,2093
<             create_new_process_group=False, enable_auth=False, cwd=None):
---
>             create_new_process_group=False, enable_auth=False, cwd=None,
>             use_shell=False):
2134a2141,2142
>         :param use_shell – If True, Popen will be start the java process with
>             shell=True
2144c2152,2153
<             enable_auth=enable_auth, cwd=cwd, return_proc=True)
---
>             enable_auth=enable_auth, cwd=cwd, return_proc=True,
>             use_shell=use_shell)
diff py4j-1/version.py py4j-2/version.py
1c1
< __version__ = '0.10.9.1'
---
> __version__ = '0.10.9.2'
```

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
