### PR TITLE
[SPARK-27015] [Mesos] properly escape mesos scheduler arguments

### PR DESCRIPTION
**Pull request by mwlon**
## What changes were proposed in this pull request?

Escape arguments for submissions sent to a Mesos dispatcher; analogous change to https://issues.apache.org/jira/browse/SPARK-24380 for confs.

Since this changes behavior than some users are undoubtedly already working around, probably best to only only merge into master.

## How was this patch tested?

Added a new unit test, covering some existing behavior as well.

### CODE REVIEW

**Comment by felixcheung** [comment]
ok to test

**Comment by mwlon** [comment]
The issue was that the unit test was dependent on a particular OS. Should be fixed now

**Comment by vanzin** [comment]
Merging to master / 2.4.

**Comment by vanzin** [comment]
(No luck with 2.4, so pushed to master only.)

**Comment by mwlon** [comment]
Master only is what I would recommend anyway

**Pull request closed without merging**
