### PR TITLE
[SPARK-31755][SQL][3.0] allow missing year/hour when parsing date/timestamp string

### PR DESCRIPTION
**Pull request by cloud-fan**
### What changes were proposed in this pull request?

This PR allows missing year and hour fields when parsing date/timestamp string, with 1970 as the default year and 0 as the default hour.

### Why are the changes needed?

To keep backward compatibility with Spark 2.4.

### Does this PR introduce _any_ user-facing change?

Yes.

Spark 2.4:
```
scala> sql("select to_timestamp('16', 'dd')").show
+------------------------+
|to_timestamp('16', 'dd')|
+------------------------+
|     1970-01-16 00:00:00|
+------------------------+


scala> sql("select to_date('16', 'dd')").show
+-------------------+
|to_date('16', 'dd')|
+-------------------+
|         1970-01-16|
+-------------------+


scala> sql("select to_timestamp('2019 40', 'yyyy mm')").show
+----------------------------------+
|to_timestamp('2019 40', 'yyyy mm')|
+----------------------------------+
|               2019-01-01 00:40:00|
+----------------------------------+


scala> sql("select to_timestamp('2019 10:10:10', 'yyyy hh:mm:ss')").show
+----------------------------------------------+
|to_timestamp('2019 10:10:10', 'yyyy hh:mm:ss')|
+----------------------------------------------+
|                           2019-01-01 10:10:10|
+----------------------------------------------+
```

in branch 3.0
```
scala> sql("select to_timestamp('16', 'dd')").show
+--------------------+
|to_timestamp(16, dd)|
+--------------------+
|                null|
+--------------------+


scala> sql("select to_date('16', 'dd')").show
+---------------+
|to_date(16, dd)|
+---------------+
|           null|
+---------------+

scala> sql("select to_timestamp('2019 40', 'yyyy mm')").show
+------------------------------+
|to_timestamp(2019 40, yyyy mm)|
+------------------------------+
|           2019-01-01 00:00:00|
+------------------------------+


scala> sql("select to_timestamp('2019 10:10:10', 'yyyy hh:mm:ss')").show
+------------------------------------------+
|to_timestamp(2019 10:10:10, yyyy hh:mm:ss)|
+------------------------------------------+
|                       2019-01-01 00:00:00|
+------------------------------------------+
```

After this PR, the behavior becomes the same as 2.4.

### How was this patch tested?

new tests

### CODE REVIEW

**Comment by cloud-fan** [comment]
@HyukjinKwon @MaxGekk

**Comment by MaxGekk** [comment]
@cloud-fan @HyukjinKwon In which places does branch-3.0 conflict with the original PR?

**Comment by HyukjinKwon** [comment]
Only SQL output file. It was trivial but wanted to make sure the tests get passed.

**Review by HyukjinKwon — APPROVED** [review]

**Review by MaxGekk — APPROVED** [review]

**Comment by cloud-fan** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
Merged to branch-3.0.

**Pull request closed without merging**
