### PR TITLE
[MINOR][DOCS] Use multi-line JavaDoc comments in Scala code.

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
## What changes were proposed in this pull request?

This PR aims to fix all Scala-Style multiline comments into Java-Style multiline comments in Scala codes.
(All comment-only changes over 77 files: +786 lines, −747 lines)
## How was this patch tested?

Manual.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Could you review this PR, @rxin ?

**Comment by dongjoon-hyun** [comment]
`org.apache.spark.sql.execution.streaming.state.StateStoreSuite.maintenance` failure again. 
It's a timeout error, should we increase the timeout for the test?

**Comment by dongjoon-hyun** [comment]
Rebased to trigger Jenkins test.

**Comment by rxin** [comment]
Thanks - merging in master.

**Comment by rxin** [comment]
BTW in the future for changes this size we should create a JIRA ticket.

Can you look into whether it is possible to create a scalastyle rule for this so we don't do the scaladoc style docs in the future?

**Comment by dongjoon-hyun** [comment]
Thank you, @rxin . I see. I'll create a JIRA for large size patch .
And, for creating new ScalaStyle rule to enforce this seems a good idea.
I'll take a look at that tomorrow. Thanks again.

**Comment by dongjoon-hyun** [comment]
Hi, @rxin .
I made a new PR for ScalaStyle rule enforcement ( #12221 ).

**Pull request closed without merging**
