### PR TITLE
[ONLY TEST][SQL] Improve TPCDSCollationQueryTestSuite

### PR DESCRIPTION
**Pull request by panbingkun**
### Why are the changes needed?
https://github.com/panbingkun/spark/actions/runs/9953478770/job/27497045622

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Only test.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by LuciferYang** [comment]
from the log we can see 

```
Warning: [1888.608s][warning][gc,alloc] broadcast-exchange-907: Retried waiting for GCLocker too often allocating 33554434 words
```

If this is the reason for the test failures, I think we should first investigate the root cause of the GCLocker's activity to avoid covering up any unknown performance bottlenecks.

**Comment by panbingkun** [comment]
> from the log we can see
> 
> ```
> Warning: [1888.608s][warning][gc,alloc] broadcast-exchange-907: Retried waiting for GCLocker too often allocating 33554434 words
> ```
> 
> If this is the reason for the test failures, I think we should first investigate the root cause of the GCLocker's activity to avoid covering up any unknown performance bottlenecks.

I have only encountered this `once` so far, and this is just a record. 
Additionally, I believe it originated from `TPCDSQueryTestSuite`. I compared it slightly with `TPCDSQueryTestSuite` and found that there are two major differences between it and `TPCDSQueryTestSuite`:
`joinConfs` and `System.gc()  // Workaround for GitHub Actions memory limitation, see also SPARK-37368`
https://github.com/apache/spark/blob/3b4c423fec08b3740c20257e130c7b016a538e79/sql/core/src/test/scala/org/apache/spark/sql/TPCDSQueryTestSuite.scala#L223-L224

**Comment by panbingkun** [comment]
I will continue to observe and consider aligning them if I encounter them again in the future.

**Comment by LuciferYang** [comment]
> > from the log we can see
> > ```
> > Warning: [1888.608s][warning][gc,alloc] broadcast-exchange-907: Retried waiting for GCLocker too often allocating 33554434 words
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If this is the reason for the test failures, I think we should first investigate the root cause of the GCLocker's activity to avoid covering up any unknown performance bottlenecks.
> 
> I have only encountered this `once` so far, and this is just a record. Additionally, I believe it originated from `TPCDSQueryTestSuite`. I compared it slightly with `TPCDSQueryTestSuite` and found that there are two major differences between it and `TPCDSQueryTestSuite`: `joinConfs` and `System.gc() // Workaround for GitHub Actions memory limitation, see also SPARK-37368`
> 
> https://github.com/apache/spark/blob/3b4c423fec08b3740c20257e130c7b016a538e79/sql/core/src/test/scala/org/apache/spark/sql/TPCDSQueryTestSuite.scala#L223-L224

SPARK-37368 was not added System.gc due to the activity of GCLocker. IIRC, it was to address excessive memory usage leading to the test process being killed.

**Pull request closed without merging**
