### PR TITLE
[SPARK-13845][CORE]Using onBlockUpdated to replace onTaskEnd avioding driver OOM

### PR DESCRIPTION
**Pull request by jeanlyn**
## What changes were proposed in this pull request?

We have a streaming job using `FlumePollInputStream` always driver OOM after few days, here is some driver heap dump before OOM

```
 num     #instances         #bytes  class name
----------------------------------------------
   1:      13845916      553836640  org.apache.spark.storage.BlockStatus
   2:      14020324      336487776  org.apache.spark.storage.StreamBlockId
   3:      13883881      333213144  scala.collection.mutable.DefaultEntry
   4:          8907       89043952  [Lscala.collection.mutable.HashEntry;
   5:         62360       65107352  [B
   6:        163368       24453904  [Ljava.lang.Object;
   7:        293651       20342664  [C
...
```

`BlockStatus` and `StreamBlockId` keep on growing, and the driver OOM in the end.
After investigated, i found the `executorIdToStorageStatus` in `StorageStatusListener` seems never remove the blocks from `StorageStatus`. 
In order to fix the issue, i try to use `onBlockUpdated` replace `onTaskEnd` , so we can update the block informations(add blocks, drop the block from memory to disk and delete the blocks) in time.
## How was this patch tested?

Existing unit tests and manual tests

### CODE REVIEW

**Comment by rxin** [comment]
cc @andrewor14

**Comment by andrewor14** [comment]
add to whitelist

**Comment by andrewor14** [comment]
@jeanlyn Thanks for submitting the patch. It seems strange that `metrics.updatedBlockStatuses` is not being updated. On what Spark versions did you observe this behavior (the affected versions on the JIRA, 1.5.2 and 1.6.1)? There have been recent changes to the way metrics are being set in master branch.

I believe this fix does solve the issue, but we should first investigate whether `metrics.updatedBlockStatuses` is empty or `metrics` simply doesn't exist for these tasks.

**Comment by jeanlyn** [comment]
Thanks @andrewor14 for review. We encounter this issue in branch-1.5, and I had noticed recent changes of metrics. If i understand correctly, I think the root cause of this issue is the `metrics.updatedBlockStatuses` does not be updated in `BlockManager.removeBlock` when removing blocks, but i prefer to use `onBlockUpdated` to solute this issue.

**Comment by jeanlyn** [comment]
@andrewor14 It seems the MIMA failure do not relevant with this patch. Do i need to fix it in this patch?

**Comment by andrewor14** [comment]
retest this please

**Comment by andrewor14** [comment]
I agree that this fixes the solution, but it also masks the problem that `metrics.updatedBlockStatuses` is updated correctly. I think before we proceed with the proposed solution we should at least investigate why the metrics is not being updated.

**Comment by jeanlyn** [comment]
I think the the metrics of `updatedBlockStatuses` does not updated using code like 
```
c.taskMetrics().incUpdatedBlockStatuses(Seq((blockId, status)))
```
 in `BlockManager.removeBlock` and the method invoke `removeBlock` when removing the blocks cause the problem.
see:
master:https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/storage/BlockManager.scala#L1226-1226
branch-1.6:https://github.com/apache/spark/blob/branch-1.6/core/src/main/scala/org/apache/spark/storage/BlockManager.scala#L1108
branch-1.5:https://github.com/apache/spark/blob/branch-1.5/core/src/main/scala/org/apache/spark/storage/BlockManager.scala#L1101
So when the the task end, we can not update the `executorIdToStorageStatus` in `StorageStatusListener` correctly. Let me know if my understanding is wrong.
Forgive me for didn't explain the problem clearly.

**Comment by jeanlyn** [comment]
All test failure is relevant with `HistoryServerSuite`, the reason is we remove the `onTaskEnd`, and it's used to replay the storage page of history server from the even log. It seems that we don't want to log the `onBlockUpdated` even to the file. See:https://github.com/apache/spark/blob/184085284185011d7cc6d054b54d2d38eaf1dd77/core/src/main/scala/org/apache/spark/scheduler/EventLoggingListener.scala#L196
 Hence, is acceptable to generate the new `*_expectation.json` of   `src/test/resources/HistoryServerExpectations/` to pass the unit test for now? @andrewor14

**Comment by jeanlyn** [comment]
close this for accident

**Comment by andrewor14** [comment]
OK, thanks for the explanation. Would you mind filing a JIRA for making sure block manager correctly updates `updatedBlockStatuses`?

**Comment by andrewor14** [comment]
Also about the history server test, yes it's OK to just generate a new event log. The old tests were written in such a way that's difficult to maintain anyway.

**Comment by jeanlyn** [comment]
OK, I will fill a JIRA later.

**Pull request closed without merging**
