### PR TITLE
[SPARK-13014][Docs] Replace example code in mllib-collaborative-filtering.md using include_example

### PR DESCRIPTION
**Pull request by keypointt**
Replace example code in mllib-collaborative-filtering.md using include_example https://issues.apache.org/jira/browse/SPARK-13014

The example code in the user guide is embedded in the markdown and hence it is not easy to test. It would be nice to automatically test them. This JIRA is to discuss options to automate example code testing and see what we can do in Spark 1.6.

Goal is to move actual example code to spark/examples and test compilation in Jenkins builds. Then in the markdown, we can reference part of the code to show in the user guide. This requires adding a Jekyll tag that is similar to https://github.com/jekyll/jekyll/blob/master/lib/jekyll/tags/include.rb, e.g., called include_example.
`{% include_example scala/org/apache/spark/examples/mllib/RecommendationExample.scala %}`
Jekyll will find `examples/src/main/scala/org/apache/spark/examples/mllib/RecommendationExample.scala` and pick code blocks marked "example" and replace code block in 
`{% highlight %}`
 in the markdown. 

See more sub-tasks in parent ticket: https://issues.apache.org/jira/browse/SPARK-11337

### CODE REVIEW

**Comment by mengxr** [comment]
@keypointt Please update the PR description (and JIRA as well) since it is no longer accurate.

**Comment by mengxr** [comment]
cc @yinxusen

**Comment by keypointt** [comment]
@mengxr OK I'll update descriptions.

BTW, seems all my changes are failed by python style, what's the command to check python style? I tried "examples/pythonstyle" in shell by "build/sbt -Pyarn -Phadoop-2.4 -Dhadoop.version=2.5.0 scala-2.10", but not working.

Thansk a lot.

**Comment by yinxusen** [comment]
Try `./dev/lint-python`

**Comment by keypointt** [comment]
Thanks @yinxusen , I'll fix the python style :smile:

**Comment by mengxr** [comment]
ok to test

**Comment by yinxusen** [comment]
@keypointt Sorry for my mistake, there is no need to replace any code for the mllib-collaborative-filtering.md. Shall we close the PR? Sorry for this! We can focus on other PRs.

**Comment by keypointt** [comment]
sure no problem, thanks @yinxusen

**Pull request closed without merging**
