### PR TITLE
[SPARK-15309] Bump master to version 2.1.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by lresende**
## What changes were proposed in this pull request?

Update pom artifact version to 2.1.0-SNAPSHOT to avoid any conflicts with 2.0.0-SNAPSHOT branch.
## How was this patch tested?

Regular build.

### CODE REVIEW

**Comment by lresende** [comment]
@srowen Please review.

**Comment by rxin** [comment]
It's better to do this once we have a 2.0 maven artifact published I think. Otherwise Mima is going to have duplicates and as we do api tweaks during qa period we will have to fight with conflicts. Can you close this?

**Comment by l15k4** [comment]
Hey, I wanted to give a shot to spark 2.0 preview, what is the best way to get the dependency? 
http://people.apache.org/~pwendell/spark-releases/latest/quick-start.html
says : 
```
libraryDependencies += "org.apache.spark" %% "spark-core" % "2.0.0-preview"
```

But I can't find this `2.0.0-preview` or `2.0.0-SNAPSHOT` dependencies anywhere. Do I have to build the master branch to get it ?

**Comment by rxin** [comment]
@l15k4 you can build from branch-2.0.

**Pull request closed without merging**
