### PR TITLE
[SPARK-7345][SQL] Spark cannot detect renamed columns using JDBC connector

### PR DESCRIPTION
**Pull request by osidorkin**
Issue appears when one tries to create DataFrame using sqlContext.load("jdbc"...) statement when "dbtable" contains query with renamed columns.
If original column is used in SQL query once the resulting DataFrame will contain non-renamed column.
If original column is used in SQL query several times with different aliases, sqlContext.load will fail.
Original implementation of JDBCRDD.resolveTable uses getColumnName to detect column names in RDD schema.
Suggested implementation uses getColumnLabel to handle column renames in SQL statement which is aware of SQL "AS" statement.

Readings:
http://stackoverflow.com/questions/4271152/getcolumnlabel-vs-getcolumnname
http://stackoverflow.com/questions/12259829/jdbc-getcolumnname-getcolumnlabel-db2

Official documentation unfortunately a bit misleading in definition of "suggested title" purpose however clearly defines behavior of AS keyword in SQL statement.
http://docs.oracle.com/javase/7/docs/api/java/sql/ResultSetMetaData.html
getColumnLabel - Gets the designated column's suggested title for use in printouts and displays. The suggested title is usually specified by the SQL AS clause. If a SQL AS is not specified, the value returned from getColumnLabel will be the same as the value returned by the getColumnName method.

### CODE REVIEW

**Comment by marmbrus** [comment]
ok to test

**Comment by marmbrus** [comment]
Thanks for fixing this! Would it be possible to add a regression test to `JDBCSuite`?

**Comment by osidorkin** [comment]
Will do.

**Comment by rxin** [comment]
Thanks. I'm merging this in master, branch-1.4, and branch-1.3.

**Pull request closed without merging**
