### PR TITLE
[SPARK-42140][CORE] Handle null string values in ApplicationEnvironmentInfoWrapper/ApplicationInfoWrapper

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
Similar to #39666, this PR handles null string values in ApplicationEnvironmentInfoWrapper/ApplicationInfoWrapper

### Why are the changes needed?
Properly handles null string values in the protobuf serializer.

### Does this PR introduce any user-facing change?
No

### How was this patch tested?
New UTs

### CODE REVIEW

**Comment by LuciferYang** [comment]
cc @gengliangwang

**Review by gengliangwang — APPROVED** [review]

**Comment by LuciferYang** [comment]
Yeah, this one GA passed

**Comment by gengliangwang** [comment]
Thanks, merging to master

**Comment by LuciferYang** [comment]
thanks @gengliangwang

**Pull request closed without merging**
