### PR TITLE
[HOTFIX] Fix ORC build break

### PR DESCRIPTION
**Pull request by marmbrus**
Fix break caused by merging #6225 and #6194.

### CODE REVIEW

**Comment by vanzin** [comment]
LGTM.

**Comment by andrewor14** [comment]
I'm just going to merge this now since master doesn't even compile.

This is going into branches master and 1.4.

**Comment by JoshRosen** [comment]
@marmbrus @andrewor14 , could you also look at #6243, which I think is trying to fix a Maven build break?

**Comment by harishreedharan** [comment]
I realize that master and thus PR builder is broken, but it would be good to wait for the PR builder to complete before merging.

**Comment by marmbrus** [comment]
I disagree.  Failing all PRs for the next two hours is not reasonable.  We
can always watch and make sure the tests pass even though this has been
merged.

**Comment by andrewor14** [comment]
@harishreedharan I think that's reasonable under normal circumstances, but having the PR builder to fail tests on every single patch for the next 2+ hours is very expensive for the process of development across the entire community. In the worst case merging this now causes the build to fail when it's already failing.

**Comment by marmbrus** [comment]
Test failure are addressed in #6247.

**Pull request closed without merging**
