### PR TITLE
[SPARK-22551][SQL] Prevent possible 64kb compile error for common expression types

### PR DESCRIPTION
**Pull request by viirya**
## What changes were proposed in this pull request?

For common expression types, such as BinaryExpression and TernaryExpression, the combination of generated codes of children can possibly be large. We should put the codes into functions to prevent possible 64kb compile error.

## How was this patch tested?

Added test.

### CODE REVIEW

**Comment by viirya** [comment]
cc @cloud-fan @kiszk

**Comment by kiszk** [comment]
Can you add a test case?

**Comment by viirya** [comment]
@kiszk I added a test. But I think after #19767 is merged, the generated codes will be changed too. I may need to adjust the test case after that.

**Comment by viirya** [comment]
I can't reproduce the issue after #19767 is merged. Hopefully it solves this issue too, so I will close this. If not and I can reproduce it later, I will re-open this.

**Pull request closed without merging**
