### PR TITLE
[SPARK-49708][BUILD] Upgrade `RoaringBitmap` to `1.3.0`

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to upgrade `RoaringBitmap` from `1.2.1` to `1.3.0`.

### Why are the changes needed?
- The full release notes: https://github.com/RoaringBitmap/RoaringBitmap/releases/tag/1.3.0

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by LuciferYang** [comment]
ready to go?

**Comment by panbingkun** [comment]
org.apache.spark.MapStatusesConvertBenchmark
JDK 17:
JDK 21:

**Comment by panbingkun** [comment]
> ready to go?

Ready already, thanks!

**Comment by LuciferYang** [comment]
Merged into master for Spark 4.0. Thanks @panbingkun

**Pull request closed without merging**
