### PR TITLE
[SPARK-23992][CORE] ShuffleDependency does not need to be deserialized every time

### PR DESCRIPTION
**Pull request by 10110346**
## What changes were proposed in this pull request?

In the same stage, 'ShuffleDependency' is not necessary to be deserialized each time.

I have tested 3 times in my production environment , it has a bit of performance improvement( about 0.7%):
Before this PR：
duration: 20189(s)
App count: 4736
the sum of time for all Apps: 530470(s)

Afterthis PR：
duration: 20035(s)
the count of Apps : 4736
the sum of time for all Apps: 525220(s)

## How was this patch tested?
Existing unit test

### CODE REVIEW

**Comment by 10110346** [comment]
retest this please

**Comment by rxin** [comment]
Are we talking about a 0.7% margin improvement? It doesn't seem like it's worth the complexity.

**Comment by 10110346** [comment]
This is end-to-end performance improvement, although our data is very small.

**Comment by JoshRosen** [comment]
I agree that the added complexity does not seem justified by the reported performance gains: the change here makes the code harder to understand (and the code comments are no longer clear; they'd need to be updated).

As a result, I'm going to close this PR and JIRA as "Won't Fix".

In general, if we want to optimize task launch latency / throughput then I think the right way to go about that is to develop a set of good microbenchmarks and use those to drive the optimization efforts; end-to-end benchmarks may be too noisy / non-reproducible for this type of change.

**Pull request closed without merging**
