### PR TITLE
[SPARK-19932][SS] Disallow a case that might cause OOM for steaming deduplication

### PR DESCRIPTION
**Pull request by lw-lin**
## Motivating use case

```scala
spark
   .readStream               // schema: (id, eventTime), such as ("a", 10), ("a", 11), ("b", 12) ...
   ...
   .withWatermark("eventTime", "10 seconds")
   .dropDuplicates("id")     // note: "eventTime" is not part of the key columns
   ...
```

As shown above, right now if watermark is specified for a streaming `dropDuplicates` query, but not specified as the key columns, then we'll still get the correct answer, but the state just keeps growing and will never get cleaned up.

The reason is, the `watermark` attribute is not part of the key of the state store in this case. We're not saving event time information in the state store.

## What changes were proposed in this pull request?

This patch adds some checking logic to disallow such cases.

## How was this patch tested?

added a `dropDuplicates` test case

### CODE REVIEW

**Comment by lw-lin** [comment]
@marmbrus @zsxwing would you take a look at this, thanks!

**Comment by marmbrus** [comment]
I'm mixed if we want this to happen implicitly.  Here's how I think about the tradeoffs for this change:  On the pro side, with this change we avoid the case where the user forgets to include the timestamp and their application crashes.

On the con, side we are doing something implicit here that might result in confusing behavior.  In the worst case (where the timestamp is not deterministically correlated with the other deduplication columns), it is possible that the result actually ends up with duplicates in it.

For that reason, I think its safest to require the user to explicitly include the timestamp.  I'd be curious what others think though.

**Comment by lw-lin** [comment]
@marmbrus thanks for the comments.

> In the worst case... it is possible that the result actually ends up with duplicates in it.

Ah, could you elaborate?  I'm not sure why there might be duplicates, since this patch proposes to include the timestamp column implicitly in the state store values rather than in the state store keys.

**Comment by marmbrus** [comment]
Say the eventtime column chosen is the time of delivery into something like Kafka.  Due to retries we end up with two events with different timestamps.  Consider the following stream with a watermark threshold of `5` and where a blank line delineates batch boundaries.

```
[id=a, t=0]

[id=b, t=6]

[id=a, t=10]
```

The first batch emits `a` the second batch emits `b` and drops `a` from the store.  The third batch emits a duplicate `a`.

Since that result seems pretty confusing, I think we may want to require the user to explicitly include the timestamp (or get an explicit though admittedly suboptimal OOM).

**Comment by lw-lin** [comment]
Thank you @marmbrus for the detailed explanation!

> For that reason, I think its safest to require the user to explicitly include the timestamp.

Yea, let me update this in this direction.

**Comment by marmbrus** [comment]
Sorry, I wasn't suggestion we mandate this.  There may be use cases where users are okay deduping a short lived stream w/o a watermark.  I'm only saying the timestamp is mandatory for the watermark to kick in.,

**Comment by lw-lin** [comment]
Sure; sorry I didn't say it out but I meant the same thing :-)

@marmbrus now that I've updated this as well as the JIRA, would you mind taking another look? Thanks!

**Comment by marmbrus** [comment]
Sorry I'm still not sure if this is a good idea.

Why disallow the following,

```scala
spark
   .readStream             
   .withWatermark("eventTime", "10 seconds")
   .dropDuplicates("id")
```

But not this query?

```scala
spark
   .readStream             
   .withWatermark("eventTime", "10 seconds")
   .groupBy("id")
   .agg(first(struct($"*")))
```

I think its an incredibly difficult problem to tell people if their query is scalable without seeing the data.  I'm not sure if we want to do it piecemeal as I'm concerned that is more confusing.

**Comment by lw-lin** [comment]
Thanks for the comments! Closing this.

**Pull request closed without merging**
