### PR TITLE
[MINOR][SQL] Add `IS [NOT] NULL` examples to ArrayFilter/ArrayExists

### PR DESCRIPTION
**Pull request by dilipbiswal**
### What changes were proposed in this pull request?
A minor PR that adds a couple of usage examples for ArrayFilter and ArrayExists that shows how to deal with NULL data.

### Why are the changes needed?
Enhances the examples that shows how to filter out null values from an array and also to test if null value exists in an array.

### Does this PR introduce any user-facing change?
No.

### How was this patch tested?
Tested manually.

### CODE REVIEW

**Comment by dilipbiswal** [comment]
cc @HyukjinKwon

**Review by HyukjinKwon — APPROVED** [review]

**Comment by dilipbiswal** [comment]
retest this please

**Review by dongjoon-hyun — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master and branch-3.0.

**Comment by dilipbiswal** [comment]
Thank you @HyukjinKwon

**Pull request closed without merging**
