### PR TITLE
[SPARK-33215][WEBUI] Speed up event log download by skipping UI rebuild

### PR DESCRIPTION
**Pull request by baohe-zhang**
### What changes were proposed in this pull request?
This patch separates the view permission checks from the getAppUi in FsHistoryServerProvider, thus enabling SHS to do view permissions check of a given attempt for a given user without rebuilding the UI. This is achieved by adding a method "checkUIViewPermissions(appId: String, attemptId: Option[String], user: String): Boolean" to many layers of history server components. Currently, this feature is useful for event log download.

### Why are the changes needed?
Right now, when we want to download the event logs from the spark history server, SHS will need to parse entire the event log to rebuild UI, and this is just for view permission checks. UI rebuilding is a time-consuming and memory-intensive task, especially for large logs. However, this process is unnecessary for event log download. With this patch, UI rebuild can be skipped when downloading event logs from the history server. Thus the time of downloading a GB scale event log can be reduced from several minutes to several seconds, and the memory consumption of UI rebuilding can be avoided.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Added test cases to confirm the view permission checks work properly and download event logs won't trigger UI loading. Also did some manual tests to verify the download speed can be drastically improved and the authentication works properly.

### CODE REVIEW

**Comment by baohe-zhang** [comment]
Hi @HeartSaVioR , could you review this pr when you get a chance?

**Comment by HeartSaVioR** [comment]
Looks good overall. Could we have a test to confirm event log download doesn't trigger ui load? You can add below code to HistoryServerSuite (probably after the test "ui and api authorization checks").

```
  test("SPARK-33215: speed up event log download by skipping UI rebuild") {
    val appId = "local-1430917381535"

    stop()
    init()

    val port = server.boundPort
    val testUrls = Seq(
      s"http://localhost:$port/api/v1/applications/$appId/logs",
      s"http://localhost:$port/api/v1/applications/$appId/1/logs",
      s"http://localhost:$port/api/v1/applications/$appId/2/logs")

    testUrls.foreach { url =>
      TestUtils.httpResponseCode(new URL(url))
    }
    assert(server.cacheMetrics.loadCount.getCount === 0, "downloading event log shouldn't load ui")
  }
```

This would fail without the patch and pass with the patch.

**Comment by HeartSaVioR** [comment]
cc. @gengliangwang @vanzin @squito

**Comment by baohe-zhang** [comment]
@HeartSaVioR I added the test case and verified it can pass with this patch and it would fail without this patch.

**Review by HeartSaVioR — APPROVED** [review]
+1

I'll wait for a couple of days to see there's any more comment from other reviewers, and merge once there's no further comment. Probably early next week.

**Comment by mridulm** [comment]
+CC @zoelin7

**Comment by mridulm** [comment]
Also, CC @zhouyejoe

**Comment by HeartSaVioR** [comment]
retest this, please

**Comment by HeartSaVioR** [comment]
I'll merge once the test passes.

**Comment by HeartSaVioR** [comment]
Thanks for your contribution! Merged into master.

**Comment by baohe-zhang** [comment]
Thanks for the review!

**Review by gengliangwang — COMMENTED** [review]
A late LGTM. @baohe-zhang Thanks for the improvement!

**Pull request closed without merging**
