### PR TITLE
[SPARK-45133][CONNECT] Make Spark Connect queries be FINISHED when last result task is finished

### PR DESCRIPTION
**Pull request by juliuszsompolski**
### What changes were proposed in this pull request?

In the situation before, query will only be FINISHED when all results have been pushed into the output buffers (not necessarily received by client, but pushed out of the server).

For LocalTableScanExec, post FINISHED before sending result batches, because nothing is executed, only cached local results are returned. For regular execution, post FINISHED after all task results have been returned from Spark, not after they have been processed and sent out.

### Why are the changes needed?

Currently, even if a query finished running in Spark, it keeps being RUNNING until all results are sent. Then there is a very small difference between FINISHED and CLOSED. This change makes it behave more similar to e.g. Thriftserver.

### Does this PR introduce _any_ user-facing change?

Yes. Queries will be posted as FINISHED when they finish executing, not when they finish sending results.

### How was this patch tested?

Will add test in https://github.com/apache/spark/pull/42560

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by juliuszsompolski** [comment]
cc @jdesjean @gjxdxh @gengliangwang @hvanhovell @grundprinzip 
I think it kind of regressed in https://github.com/apache/spark/pull/42454
I think it's more logical this way.

**Comment by jdesjean** [comment]
The change seems logical to me as well.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by dongjoon-hyun** [comment]
Hi, @juliuszsompolski and @HyukjinKwon .

I hoped this recovers the master branch, but it seems that CI is still failing since the commit which `ReattachableExecuteSuite` is added. Could you check this comment?
- https://github.com/apache/spark/pull/42560#pullrequestreview-1623698495

**Comment by juliuszsompolski** [comment]
In description I wrote "Will add test in https://github.com/apache/spark/pull/42560", but since that one was merged yesterday, I planned to rebase and add test here. I will add test in a followup.

**Pull request closed without merging**
