### PR TITLE
Update PageRank.scala

### PR DESCRIPTION
**Pull request by ddna1021**
## What changes were proposed in this pull request?

Hi, acording to code below,
"if (id == src) (0.0, Double.NegativeInfinity) else (0.0, 0.0)"
I think the comment can be wrong

## How was this patch tested?
Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Comment by srowen** [comment]
I think that's right; @aray this might have been missed in https://github.com/apache/spark/pull/16483

**Comment by srowen** [comment]
Merged to master

**Comment by dongjoon-hyun** [comment]
Hi, @srowen .
Is this the first Spark 2.4-only commit?

**Comment by srowen** [comment]
Yeah I figured it's minor enough we can go ahead and not bother back-porting to 2.3. I don't mind anyone else backporting.

**Pull request closed without merging**
