### PR TITLE
[SPARK-14931][ML][PySpark] Mismatched default values between pipelines in Spark and PySpark

### PR DESCRIPTION
**Pull request by yinxusen**
## What changes were proposed in this pull request?

When transferring params from Spark pipeline back to PySpark pipeline, only those set params should be transferred back. Otherwise, the potential mismatch default values between Spark pipelines and PySpark pipelines will cause errors.
## How was this patch tested?

Tested with previous existed Python tests.

### CODE REVIEW

**Comment by yinxusen** [comment]
See example here https://github.com/apache/spark/pull/12604#issuecomment-214852153

**Comment by holdenk** [comment]
So this still leaves the difference between the two, but just doesn't impact model persistence. If we do end up doing this fix - might it make sense to leave open another issue to audit the default values between the two and normalize them?

**Comment by yinxusen** [comment]
@holdenk Yes this PR is just a quick fix. I'll create a new JIRA for auditing default values.

**Comment by yinxusen** [comment]
@holdenk It seems not good enough, I'll add a unit test to check the mismatch, then it will be easy to fix the mismatch default values issue.

**Comment by jkbradley** [comment]
Thanks for writing this fix and the general test for checking; it's a good idea.  Some of the fixes need to be done in a different way, and given the time constraints, do you mind if I take over the PR?  You'll still be the primary author.  I'll CC you on the other PR.  Thank you!

**Comment by yinxusen** [comment]
I'll close this one.

**Pull request closed without merging**
