### PR TITLE
[SPARK-45501][CORE][SQL] Use pattern matching for type checking and conversion

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr change to use pattern matching for type checking and conversion instead of the explicit type casting statement in Java code.

The change refer to [JEP 394](https://openjdk.org/jeps/394), and this pr does not include parts of the `hive-thriftserver` module.

Example:

```java
  if (obj instanceof String) {
    String str = (String) obj;
    System.out.println(str);
  }
```
Can be replaced with
```java
  if (obj instanceof String str) {
    System.out.println(str);
  }
```

### Why are the changes needed?
Using `JEP 394: Pattern Matching for instanceof` can bring the following benefits:

1. **Code conciseness**: By eliminating explicit type conversion and redundant variable declarations, the code becomes more concise and easy to read.
2. **Improved safety**: In the past, explicit type conversion was required, and if accidentally converted to the wrong type, a `ClassCastException` would be thrown at runtime. Now, as type checking and type conversion occur in the same step, such errors are no longer possible.
3. **Better semantics**: Previously, instanceof and type casting were two independent steps, which could lead to unclear code intentions. Now, these two steps are merged into one, making the intentions of the code clearer.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass GitHub Actions

### Was this patch authored or co-authored using generative AI tooling?
No

### CODE REVIEW

**Comment by LuciferYang** [comment]
This pr does not include parts of the `hive-thriftserver` module.

**Review by dongjoon-hyun — COMMENTED** [review]
Ya, [JEP 394](https://openjdk.org/jeps/394) looks like a good improvement. Could you file a JIRA and use it, @LuciferYang ?

**Comment by LuciferYang** [comment]
> Ya, [JEP 394](https://openjdk.org/jeps/394) looks like a good improvement. Could you file a JIRA and use it, @LuciferYang ?

done

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. (Pending CIs).

**Comment by LuciferYang** [comment]
GA passed

**Review by srowen — APPROVED** [review]

**Comment by LuciferYang** [comment]
Merged into master, thank @srowen @dongjoon-hyun

**Pull request closed without merging**
