### PR TITLE
[SPARK-4871][SQL] Show sql statement in spark ui when run sql with spark-sql

### PR DESCRIPTION
**Pull request by scwf**

### CODE REVIEW

**Comment by liancheng** [comment]
This LGTM.

**Comment by scwf** [comment]
ping @marmbrus

**Comment by marmbrus** [comment]
Thanks, merged to master

**Comment by wkhapy** [comment]
@marmbrus ，when I use Statement.cancel() from JDBC,web ui shows that query  keep going 。

**Pull request closed without merging**
