### PR TITLE
[Minor][DOC] Fix doc style in ml.ann.Layer and MultilayerPerceptronClassifier

### PR DESCRIPTION
**Pull request by zhengruifeng**
## What changes were proposed in this pull request?

1, fix the indentation
2, add a missing param desc
## How was this patch tested?

unit tests

### CODE REVIEW

**Comment by zhengruifeng** [comment]
BTW, I think the documents in Layer.scala should be more meaningful

**Comment by srowen** [comment]
Hm, yeah it's really trivial, but I also get distracted reading this code when I see the malformed scaladoc. It grabs the eye. Are you able to easily detect this type of problem across the code base and fix any such instance in one go?

**Comment by zhengruifeng** [comment]
@srowen Ok, I will make a quick review of ML/MLLIB tonight. And if there are other file having this issue, I will fix those in this PR.

**Comment by zhengruifeng** [comment]
@srowen  MultilayerPerceptronClassifier was found to have the same problem. Others are OK.

**Comment by srowen** [comment]
OK. On the grounds that this does marginally help readability (I find the out-of-line stars distracting) and we've surveyed for similar problems, i'll merge it.

**Pull request closed without merging**
