### PR TITLE
[SPARK-45268][PYTHON][DOCS] python function categories should be consistent with SQL References

### PR DESCRIPTION
**Pull request by zhengruifeng**
### What changes were proposed in this pull request?
re-org python function categories

### Why are the changes needed?
should be consistent with SQL expression groups

### Does this PR introduce _any_ user-facing change?
yes

### How was this patch tested?
manually check

### Was this patch authored or co-authored using generative AI tooling?
no

### CODE REVIEW

**Comment by zhengruifeng** [comment]
In `functions.py`, I think only the comments are incorrect, I guess we can leave it alone?

https://github.com/apache/spark/blob/c1dc9ae1c10e7c102407526e0ddc3d4b76d84119/python/pyspark/sql/functions.py#L11670


In `functions.scala`, I think we should correct the groups to be the same with expression groups

**Comment by zhengruifeng** [comment]
cc @HyukjinKwon

**Comment by zhengruifeng** [comment]
This PR make categories follow expression descriptions, instead of `functions.scala`:

one major difference is that `lambda function` is in group `collect function` in `functions.scala`

**Review by HyukjinKwon — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]

**Comment by zhengruifeng** [comment]
Please hold off for a while, we may need to rename `lambda functions` which sounds too "technology"

**Comment by zhengruifeng** [comment]
put `lambda functions` into `collection functions`, to be consistent with SQL references and Scala docs

**Comment by zhengruifeng** [comment]
thanks all for reviewing, merged to master

**Pull request closed without merging**
