### PR TITLE
[SPARK-13073] [MLib] [WIP] creating R like summary for logistic Regression in Spark - Scala

### PR DESCRIPTION
**Pull request by mbaddar1**
## What changes were proposed in this pull request?

Implemented initial version of toString method for BinaryLogisticRegressionSummary that converts ROC , Precision , F-Measure data frame members into tabular string representation
## How was this patch tested?

-Unit testing 
-Manual

Author : Mohamed Baddar ( mbaddar2@gmail dot com )

@mengxr Can you help in reviewing this PR

### CODE REVIEW

**Comment by mbaddar1** [comment]
CC @jkbradley @mengxr

**Comment by mbaddar1** [comment]
@AmplabJenkins @jkbradley @mengxr Can any one of the admins verify this PR ?

**Comment by mbaddar1** [comment]
Ping -- Any updates on that PR ?

**Comment by jkbradley** [comment]
add to whitelist

**Comment by jkbradley** [comment]
Some high-level comments:
* It would be great to mimic one of the existing R-based tests:
  * Run on a small dataset in R  (You can see how those other tests do that.)
  * Print the summary in R
  * Copy the R code into a comment in the Scala unit test
  * Copy the R summary into a String in the Scala unit test
  * Compare the 2 printed summaries.  If this can be done via a simple string comparison, great.  If not, I'd like to compare the values and the formatting in some way; we could discuss possibilities.
* Please follow the Scala style guide [https://cwiki.apache.org/confluence/display/SPARK/Spark+Code+Style+Guide].  It's easiest to compare with other code in Spark itself.

Thanks!

**Comment by srowen** [comment]
Ping @mbaddar1 ?

**Comment by mbaddar1** [comment]
@srowen @jkbradley Will work on the comments added by @jkbradley and will update the PR ASAP

**Comment by HyukjinKwon** [comment]
gentle ping @mbaddar1

**Comment by mbaddar1** [comment]
@HyukjinKwon Unfortunately I will not be able to work on it on the time being. Hope if another contributor can take it from here.

**Pull request closed without merging**
