### PR TITLE
[SPARK-15067] [YARN] YARN executors are launched with fixed perm gen size

### PR DESCRIPTION
**Pull request by srowen**
## What changes were proposed in this pull request?

Look for MaxPermSize arguments anywhere in an arg, to account for quoted args. See JIRA for discussion.
## How was this patch tested?

Jenkins tests

### CODE REVIEW

**Comment by jaceklaskowski** [comment]
What do you think about a unit test for this?

**Comment by srowen** [comment]
Jenkins retest this please

**Comment by srowen** [comment]
Jenkins retest this please

**Comment by andrewor14** [comment]
Thanks merging into master 2.0 1.6

**Comment by keithdotpower** [comment]
Is there any workaround for this for 1.6.1? I'm using Amazon's EMR so it's not so easy for me to change

**Pull request closed without merging**
