### PR TITLE
remove unnecessary copy

### PR DESCRIPTION
**Pull request by viper-kun**

### CODE REVIEW

**Comment by srowen** [comment]
If this is an optimization, it's a very small one. Are you sure it improves things? weirdly, I've found this kind of thing can slow down very tight loops since you put a branch in the pipeline.

**Comment by cloud-fan** [comment]
It's not a deep copy, just assign a new reference which is very cheap, and I'm afraid your extra if branch may hurt the performance.

**Comment by andrewor14** [comment]
need JIRA

**Comment by srowen** [comment]
I actually think this PR should just be closed.

**Comment by JoshRosen** [comment]
Yeah, this doesn't have a description / explanation of changes, JIRA ticket, _or_ benchmark results. Let's close for now.

**Comment by viper-kun** [comment]
ok.close it.

**Pull request closed without merging**
