### PR TITLE
[SPARK-36716][SQL] Join estimation support ExistenceJoin join type

### PR DESCRIPTION
**Pull request by 007akuan**
### What changes were proposed in this pull request?

This PR makes join estimation support `ExistenceJoin` join type.

### Why are the changes needed?

To make join estimation more accurate and make the plan better. This change can benefit TPC-DS q10.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Unit test.

### CODE REVIEW

**Comment by wangyum** [comment]
ok to test.

**Comment by 007akuan** [comment]
retest this please.

**Comment by wangyum** [comment]
ok to test

**Comment by wangyum** [comment]
Looks OK to me. cc @cloud-fan

**Pull request closed without merging**
