### PR TITLE
[SPARK-15337] [SPARK-15338] [SQL] Enable Run-time Changes on Hive-related Conf

### PR DESCRIPTION
**Pull request by gatorsmile**
#### What changes were proposed in this pull request?

Currently, we are facing two issues when using the Set Command. 
1. When changing a Hive-related conf at runtime, we are not passing the change to the underlying Hive metastore. For example, `SET hive.metastore.warehouse.dir=/x/y/z` The following link contains the possible conf: https://cwiki.apache.org/confluence/display/Hive/Configuration+Properties
2. When changing the warehouse path conf `spark.sql.warehouse.dir`, we are not changing the corresponding Hive metastore default warehouse path conf: `hive.metastore.warehouse.dir`. Thus, this change does not take effect if the underlying catalog is Hive metastore.

This PR is to fix the above two issues by using the native Hive SQL interface, if necessary. 
#### How was this patch tested?

Added two test cases to verify if the run-time configuration works in either Hive metastore or In-Memory Catalog

### CODE REVIEW

**Comment by hvanhovell** [comment]
@gatorsmile the title of the PR could be better. I thought you were preventing users from making changes to Hive's runtime configuration; it is the opposite.

**Comment by gatorsmile** [comment]
Yeah... : ) Just fix it.

**Comment by yhuai** [comment]
@gatorsmile For 2.0, all confs should go into spark conf or sql conf. What is the reason to change this?

**Comment by gatorsmile** [comment]
@yhuai For example, after we starting Spark, we want to do a run-time configuration change. `set spark.sql.warehouse.dir=x/y/z`. This is not sent to Hive metastore. Basically, metastore is still using the value we set at the beginning. See the link: https://github.com/apache/spark/blob/7bf9b12019bb20470b726a7233d60ce38a9c52cc/sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveSharedState.scala#L39-L48

In addition, I am afraid that `hive.metastore.warehouse.dir` is not the only parameter users might change at runtime. If any change is made at runtime, we just change/set the value in our in-memory configuration . We did not propagate the changes to Hive metastore. Do you think this should be a concern? 

If both are not supported, we should issue exceptions to users that the run-time changes are not supported. Now, we silently accept the Hive-related configuration changes but the changes are not activated.

**Comment by yhuai** [comment]
All Spark confs are not mutable. For SQL, those metastore related confs are also not mutable considering the long-running metastore client that we have. I do think it is reasonable to explicitly mark `spark.sql.warehouse.dir` as not mutable. We can make it clear in our doc (for example, have a list of immutable confs of SQL in Spark SQL programming guide). If we want to throw exceptions, it will be good to consider both Spark conf and immutable SQL confs together.

**Comment by gatorsmile** [comment]
uh, I see. Will submit a separate PR to document them, and another one for issuing exceptions for all the immutable confs.

**Pull request closed without merging**
