### PR TITLE
[SPARK-7237] [SPARK-7741] [Core] [Streaming] Clean more closures that need cleaning

### PR DESCRIPTION
**Pull request by andrewor14**
SPARK-7741 is the equivalent of SPARK-7237 in streaming. This is an alternative to #6268.

### CODE REVIEW

**Comment by tdas** [comment]
foreachRDD is missing.

**Comment by andrewor14** [comment]
Good catch

**Comment by andrewor14** [comment]
Okay, I added tests to verify that closures are being cleaned in DStream operations. @tdas PTAL.

**Comment by andrewor14** [comment]
Regarding `foreachRDD`, I'm actually pretty confused about one thing. Currently when we clean the foreach closure we don't check serializability for the following reason:
```
// because the DStream is reachable from the outer object here, and because 
// DStreams can't be serialized with closures, we can't proactively check 
// it for serializability and so we pass the optional false to SparkContext.clean
new ForEachDStream(this, context.sparkContext.clean(foreachFunc, false)).register()
```
This implies that the closure cannot be serialized ever, which is true because we pull in the whole `ssc` into the closure in `ForEachInputDStream#generateJob`:
```
val jobFunc = () => createRDDWithLocalProperties(time) {
  ssc.sparkContext.setCallSite(creationSite)
  foreachFunc(rdd, time)
}
```
What's the point in cleaning this closure if it can never be cleaned?

**Comment by andrewor14** [comment]
Regarding `foreachRDD`, I'm actually pretty confused about one thing. Currently when we clean the foreach closure we don't check serializability for the following reason:
```
// because the DStream is reachable from the outer object here, and because 
// DStreams can't be serialized with closures, we can't proactively check 
// it for serializability and so we pass the optional false to SparkContext.clean
new ForEachDStream(this, context.sparkContext.clean(foreachFunc, false)).register()
```
This implies that the closure cannot be serialized ever, which is true because we pull in the whole `ssc` into the closure in `ForEachInputDStream#generateJob`:
```
val jobFunc = () => createRDDWithLocalProperties(time) {
  ssc.sparkContext.setCallSite(creationSite)
  foreachFunc(rdd, time)
}
```
What's the point in cleaning this closure if it can never be cleaned?

(By the way, this is a separate issue that we can address later. For now I'm OK with just not checking serializability in `foreachRDD`, which is arbitrary but doesn't really hurt.)

**Comment by andrewor14** [comment]
retest this please

**Comment by andrewor14** [comment]
retest this please

**Comment by tdas** [comment]
LGTM!

**Pull request closed without merging**
