### PR TITLE
[SPARK-41716][CONNECT] Rename _catalog_to_pandas to _execute_and_fetch in Catalog

### PR DESCRIPTION
**Pull request by HyukjinKwon**
### What changes were proposed in this pull request?

This PR proposes to rename `_catalog_to_pandas` to `_execute_and_fetch`, and remove the JIRA in the comment.

### Why are the changes needed?

I tried to factor this out to the client but I realised that there won't be too much difference.
In addition, we need a new design for Catalog API so I proposed to remove the JIRA for now.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Existing test cases should cover.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @zhengruifeng

**Review by dongjoon-hyun — APPROVED** [review]
I believe we don't need to mention like `Remove the JIRA` when we resolved the IDed TODO. :)

**Comment by HyukjinKwon** [comment]
👍

**Comment by dongjoon-hyun** [comment]
Could you rebase this once more?

**Comment by HyukjinKwon** [comment]
sure!

**Comment by dongjoon-hyun** [comment]
PySpark connect module passed. Merged to master/3.4.

**Comment by HyukjinKwon** [comment]
Thank you!!!!

**Pull request closed without merging**
