### PR TITLE
[SPARK-7138][Streaming] Add method to BlockGenerator to add multiple records to BlockGenerator with single callback

### PR DESCRIPTION
**Pull request by tdas**
This is to ensure that receivers that receive data in small batches (like Kinesis) and want to add them but want the callback function to be called only once. This is for internal use only for improvement to Kinesis Receiver that we are planning to do.

### CODE REVIEW

**Comment by huitseeker** [comment]
Would it make sense to add the data using the existing `ReceivedBlockHandler` in this case ? Or is it that you want to reuse the `RateLimiter` ?

**Comment by harishreedharan** [comment]
LGTM

**Comment by tdas** [comment]
@huitseeker Yes, I want to use the existing rate limiter interface. So that any sort of rate controlling in the future can be applied through that interface.

**Comment by jerryshao** [comment]
Looks good to me :).

**Comment by tdas** [comment]
Thanks all! Merging this.

**Pull request closed without merging**
