### PR TITLE
fix runtime filter do not execute when no stats

### PR DESCRIPTION
**Pull request by chenminghua8**
### What changes were proposed in this pull request?
This RP makes the Row-level Runtime Filtering work without stats.

### Why are the changes needed?
At present, Row-level Runtime Filtering will judge whether maxScanSize meets the requirements for performing Row-level Runtime Filtering. When there is no stats in the catalogTable, maxScanSize is equal to 0, which makes it unable to meet the requirements for performing Row-level Runtime Filtering, resulting in Row-level Runtime Filtering not being enabled. By adding the RUNTIME_FILTER__ENABLED_WHEN_NO_STATS parameter, when RUNTIME_FILTER__ENABLED_WHEN_NO_STATS is true, even if maxScanSize is equal to 0 but other conditions can satisfy Row-level Runtime Filtering will still be executed. Avoid Row-level Runtime Filtering not enabled because catalogTable has no stats.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Unit test.

### CODE REVIEW

**Comment by chenminghua8** [comment]
What changes were proposed in this pull request?
This RP makes the Row-level Runtime Filtering work without stats.

Why are the changes needed?
At present, Row-level Runtime Filtering will judge whether maxScanSize meets the requirements for performing Row-level Runtime Filtering. When there is no stats in the catalogTable, maxScanSize is equal to 0, which makes it unable to meet the requirements for performing Row-level Runtime Filtering, resulting in Row-level Runtime Filtering not being enabled. By adding the RUNTIME_FILTER__ENABLED_WHEN_NO_STATS parameter, when RUNTIME_FILTER__ENABLED_WHEN_NO_STATS is true, even if maxScanSize is equal to 0 but other conditions can satisfy Row-level Runtime Filtering will still be executed. Avoid Row-level Runtime Filtering not enabled because catalogTable has no stats.

Does this PR introduce any user-facing change?
No.

How was this patch tested?
Unit test.

**Comment by zhengruifeng** [comment]
A JIRA ticket is needed, you can refer to https://spark.apache.org/contributing.html

if this is a bug fix, it's better to have a UT for the fix.

**Comment by chenminghua8** [comment]
> A JIRA ticket is needed, you can refer to https://spark.apache.org/contributing.html
> 
> if this is a bug fix, it's better to have a UT for the fix.

Ok, let me reproduce the problem scenario completely.

**Comment by chenminghua8** [comment]
> A JIRA ticket is needed, you can refer to https://spark.apache.org/contributing.html
> 
> if this is a bug fix, it's better to have a UT for the fix.

I have created a JIRA（[SPARK-40793](https://issues.apache.org/jira/browse/SPARK-40793)） for this question, what should I do next?

**Comment by chenminghua8** [comment]
change to Pull request 38381

**Pull request closed without merging**
