### PR TITLE
[SPARK-36951][PYTHON] Inline type hints for python/pyspark/sql/column.py

### PR DESCRIPTION
**Pull request by xinrong-meng**
### What changes were proposed in this pull request?
Inline type hints for python/pyspark/sql/column.py

### Why are the changes needed?
Currently, Inline type hints for python/pyspark/sql/column.pyi doesn't support type checking within function bodies. So we inline type hints to support that.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Existing test.

### CODE REVIEW

**Comment by xinrong-databricks** [comment]
CC @ueshin @HyukjinKwon @itholic @zero323

**Comment by zero323** [comment]
Comments aside, LGTM  (sorry for some noise).

**Review by HyukjinKwon — APPROVED** [review]

**Comment by itholic** [comment]
LGTM if the conflicting resolved

**Review by itholic — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
oops, there are some conflicts here. @xinrong-databricks would you mind updating the Pr please.

**Review by ueshin — APPROVED** [review]

**Pull request closed without merging**
