### PR TITLE
[SPARK-19490][SQL] ignore case sensitivity when filtering hive partition columns

### PR DESCRIPTION
**Pull request by cenyuhai**
## What changes were proposed in this pull request?
 ignore hive column names case-sensitive when comparing with partition columns

### CODE REVIEW

**Comment by rxin** [comment]
hm is it safe to just do this change?

**Comment by cenyuhai** [comment]
@rxin I think it is safe, it is only used to check whether the schema contains the columns. Hive columns are not case-sensitive.

**Comment by janua** [comment]
👍 
Just bumped into this issue. The error message doesn't make it obvious what's wrong.

**Comment by taklwu** [comment]
any updates on this PR?

**Comment by cenyuhai** [comment]
@taklwu this pr is completed, you can merge this pr by yourself. A committer told me that  other pr has fixed this bug, my pr will not be merged......

**Comment by taklwu** [comment]
May I get the link of which commit/pr fix this issue? thanks a lot

**Comment by LantaoJin** [comment]
Duplicates to [SPARK-18572](https://github.com/apache/spark/pull/15998)

**Pull request closed without merging**
