### PR TITLE
Revert "[SPARK-35253][SPARK-35398][SQL][BUILD] Bump up the janino version to v3.1.4"

### PR DESCRIPTION
**Pull request by cloud-fan**
### What changes were proposed in this pull request?

This PR reverts https://github.com/apache/spark/pull/32455 and its followup https://github.com/apache/spark/pull/32536 , because the new janino version has a bug that is not fixed yet: https://github.com/janino-compiler/janino/pull/148

### Why are the changes needed?

avoid regressions

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

existing tests

### CODE REVIEW

**Comment by cloud-fan** [comment]
cc @maropu

**Review by gengliangwang — APPROVED** [review]

**Review by viirya — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Could you resolve the conflicts, @cloud-fan ?

**Review by dongjoon-hyun — APPROVED** [review]
Since SPARK-35398 has a different JIRA ID from SPARK-35253, I inevitably added it to the PR title.

**Comment by maropu** [comment]
late lgtm, thanks, @cloud-fan

**Review by LuciferYang — APPROVED** [review]
LGTM

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master and branch-3.2.

**Comment by LuciferYang** [comment]
@maropu It looks like janino is ready to release 3.1.5

https://github.com/janino-compiler/janino/commit/1a2d0b8743690d9d6e1c25f8d891fee5342cc5bc

**Pull request closed without merging**
