### PR TITLE
[SPARK-15574][ML][PySpark] Python meta-algorithms in Scala

### PR DESCRIPTION
**Pull request by yinxusen**
## What changes were proposed in this pull request?
1. Add a PythonStageWrapper in Scala for pure Python implemented pipeline stages in PySpark.
2. Add a PythonTransformer, PythonEstimator, and PythonModel as proxies of PySpark pure Python transformers, estimators, and models.
3. Change pure Python implemented Pipeline in PySpark into Java one.
4. Implement save/load in Pipeline for pure Python pipeline stages.
## How was this patch tested?

Test with Python unit test and doc test.

### CODE REVIEW

**Comment by yinxusen** [comment]
@jkbradley For [SPARK-15574](https://issues.apache.org/jira/browse/SPARK-15574), only Pipeline and Transformer are changed in this PR. I will add Estimator/Model later.

For pure Python transformers, I have to add a `transformSchema`, otherwise it fails in Scala Pipeline schema check.

For saving/loading in pure Python transformers, I think we can either saving/loading them from Python side or serializing and shipping them to Scala side for saving/loading.

**Comment by yinxusen** [comment]
test it please

**Comment by yinxusen** [comment]
test it please

**Comment by yinxusen** [comment]
retest this please

**Comment by yinxusen** [comment]
@jkbradley Update: Now I've added the PythonEstimator and PythonModel. For PythonEvaluator, it's better to commit in along with changes of CrossValidator. It's ready to review.

**Comment by holdenk** [comment]
@yinxusen - is this something you are still interested in? If so updating it to master would be good as well as making sure the unit tests pass in jenkins (a lot of reviwers just skip PRs which are failing tests). Although this is also pretty big so it might make sense to check with @jkbradley that this is something he is still interested in as well before you spend your time on it.

**Comment by yinxusen** [comment]
Thanks @holdenk Yes, I am still interested in this. @jkbradley Do we still need the PR to support meta-algorithms in PySpark?

**Comment by ueshin** [comment]
@yinxusen Hi, are you still working on this?

**Comment by jkbradley** [comment]
@yinxusen  Thanks for this PR!  I still think this seems like a very cool feature, but I've become less convinced that it's worth the engineering and maintenance effort.  The alternative to this feature is to have meta-algorithms all implemented in Python as well as Scala.  Since there are not many such meta-algorithms (4 currently), I think that sounds easier than implementing something like this.

That's my current opinion, at least, especially since I have not seen a lot of demand for more meta-algorithms in MLlib.

**Comment by WeichenXu123** [comment]
+1 @jkbradley For now it is better to keep the current implementation for the 4 meta-algo in pyspark.
@yinxusen Would you mind to close this PR ? But I still appreciate your contribution for this!

**Comment by WeichenXu123** [comment]
cc @srowen Can you help close this ? We won't need this feature for now.

**Pull request closed without merging**
