### PR TITLE
[MINOR][R] Reorder `Collate` fields in DESCRIPTION file

### PR DESCRIPTION
**Pull request by HyukjinKwon**
## What changes were proposed in this pull request?

It seems cran check scripts corrects `R/pkg/DESCRIPTION` and follows the order in `Collate` fields.

This PR proposes to fix `catalog.R`'s order so that running this script does not show up a small diff in this file every time.

## How was this patch tested?

Manually via `./R/check-cran.sh`.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
@felixcheung, it is probably not worth being as a separate PR. I am fine if you add this in any of your PR that is going to be merged soon.

**Comment by felixcheung** [comment]
that's fine I'm at a lost at how it decides the order? The first part is completely unsorted, right?
```
     'schema.R'
     'generics.R'
     'jobj.R'
     'column.R'
     'group.R'
     'RDD.R'
      'pairRDD.R'
      'DataFrame.R'
      'SQLContext.R'
      'WindowSpec.R'
      'backend.R'
```

**Review by felixcheung — APPROVED** [review]

**Comment by felixcheung** [comment]
merged to master.

**Comment by HyukjinKwon** [comment]
I just found some references about the order. It seems there was a question about it - http://stackoverflow.com/questions/18544006/how-do-i-indicate-collate-order-in-roxygen2 and https://cran.r-project.org/web/packages/roxygen2/roxygen2.pdf

I didn't run a lot of tests as fortunately It sounds deterministic at least.

**Pull request closed without merging**
