### PR TITLE
[SPARK-49495][DOCS][FOLLOWUP] Fix Pandoc installation for GitHub Pages publication action

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

Action 'pandoc/actions/setup' is now allowed by the ASF organization account. This followup makes the installation step manual.

### Why are the changes needed?

fix ci

### Does this PR introduce _any_ user-facing change?
no

### How was this patch tested?
https://github.com/yaooqinn/spark/actions/runs/10914663049/job/30293151174

### Was this patch authored or co-authored using generative AI tooling?
no

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @yaooqinn .

**Comment by yaooqinn** [comment]
Merged to master.

Thank you very much @dongjoon-hyun

**Comment by dongjoon-hyun** [comment]
It seems to fail again in Apache Spark repo, @yaooqinn .

- https://github.com/apache/spark/actions/runs/10916383676/job/30297716064
Screenshot 2024-09-18 at 07 41 21

**Comment by dongjoon-hyun** [comment]
It still fails at a new step, `Jekyll Build`. 😢 

Screenshot 2024-09-18 at 07 48 19

**Comment by dongjoon-hyun** [comment]
This task seems to be tricky because we have three commits with no success. Do you think there is a way to verify this in a single shot, @yaooqinn ?
```
$ git log --oneline --format=%s | grep SPARK-49495
[SPARK-49495][DOCS][FOLLOWUP] Enable GitHub Pages settings via .asf.yml
[SPARK-49495][DOCS][FOLLOWUP] Fix Pandoc installation for GitHub Pages publication action
[SPARK-49495][DOCS] Document and Feature Preview on the master branch via Live GitHub Pages Updates
```

**Pull request closed without merging**
