### PR TITLE
[SPARK-33109][BUILD] Upgrade to sbt 1.4.0

### PR DESCRIPTION
**Pull request by gemelen**
### What changes were proposed in this pull request?

Upgrade sbt to release 1.4.0

### Why are the changes needed?

Bring built-in `dependencyTree` instead of removed `sbt-dependency-graph` plugin, that doesn't work with sbt used in build.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Should pass all the tests.

### CODE REVIEW

**Comment by gemelen** [comment]
I'd like to see GH and Jenkins tests, cause I had seen very strange behaviour locally (one of the tasks went into endless loop) and I'm not sure that it is reproducible somewhere else.

**Comment by dongjoon-hyun** [comment]
Thank you, @gemelen !

**Comment by dongjoon-hyun** [comment]
The K8s IT failure seems to be due to the test case flakiness. It's irrelevant.
```
- Run SparkPi with no resources *** FAILED ***
  The code passed to eventually never returned normally. Attempted 190 times over 3.0031691168 minutes. Last failure message: false was not true. (KubernetesSuite.scala:383)
```

**Comment by gemelen** [comment]
Yes, seems like build works fine here and there.
After upgrade I saw few more warnings from build file itself (`setting key is unused`), but my attempt to fix them led to `dependencyTree` output be empty, so I suggest to leave it as is and try to fix later.

**Comment by dongjoon-hyun** [comment]
Sure. We can do that later in another PR.

**Comment by dongjoon-hyun** [comment]
cc @srowen and @HyukjinKwon

**Comment by srowen** [comment]
If it passes tests, OK. I had some trouble with 1.2.x -> 1.4.x in another project but it may not manifest here, as we primarily test and build off Maven.

**Comment by dongjoon-hyun** [comment]
Thank you for confirmation, @srowen .

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @gemelen and @srowen .
This passed Github Action and Jenkins UT (Java/Scala already passed).
Merged to master for Apache Spark 3.1.0.

**Comment by HyukjinKwon** [comment]
Looks good. Nice, thanks for doing this.

**Pull request closed without merging**
