### PR TITLE
[SPARK-15102]  [SQL] remove delegation token support from ThriftServer

### PR DESCRIPTION
**Pull request by davies**
## What changes were proposed in this pull request?

These API is only useful for Hadoop, may not work for Spark SQL.

The APIs is kept for source compatibility. 
## How was this patch tested?

No unit tests needed.

### CODE REVIEW

**Comment by davies** [comment]
@rxin  Should we also remove the APIs?

**Comment by rxin** [comment]
Probably OK to keep the interface for now since it is defined in the thrift protocol.

**Comment by rxin** [comment]
Merging in master/branch-2.0!

**Comment by rxin** [comment]
BTW the title should say [SPARK ...]

**Comment by davies** [comment]
The ThriftServer is only used for SQL, right?

**Comment by rxin** [comment]
Yes - I was referring to the jira ticket number.

**Comment by davies** [comment]
Oh, my bad..

**Pull request closed without merging**
