### PR TITLE
[BACKPORT][SPARK-17531] Don't initialize Hive Listeners for the Execution Client

### PR DESCRIPTION
**Pull request by brkyvz**
## What changes were proposed in this pull request?

If a user provides listeners inside the Hive Conf, the configuration for these listeners are passed to the Hive Execution Client as well. This may cause issues for two reasons:
1. The Execution Client will actually generate garbage
2. The listener class needs to be both in the Spark Classpath and Hive Classpath

This PR empties the listener configurations in HiveUtils.newTemporaryConfiguration so that the execution client will not contain the listener confs, but the metadata client will.
## How was this patch tested?

Unit tests

### CODE REVIEW

**Comment by brkyvz** [comment]
cc @yhuai

**Comment by yhuai** [comment]
LGTM pending jenkins.

**Comment by yhuai** [comment]
Thanks! Merging to branch 1.6.

**Comment by yhuai** [comment]
I have merged this.

**Pull request closed without merging**
