### PR TITLE
[SPARK-39887][SQL] `PullOutGroupingExpressions` should generate different alias names

### PR DESCRIPTION
**Pull request by cfmcgrady**
### Why are the changes needed?

the pr aims to fix the unexpected result of following case

```sql
SELECT to_date(a) a, to_date(b) b
FROM
(SELECT  a, a AS b FROM(SELECT to_date(a) a FROM VALUES ('2020-02-01') as t1(a) GROUP BY to_date(a)) t3
UNION ALL
SELECT a, b FROM (SELECT to_date(a) a, to_date(b) b FROM VALUES ('2020-01-01','2020-01-02') AS t1(a, b) GROUP BY to_date(a), to_date(b)) t4) t5
GROUP BY to_date(a), to_date(b)
```
```
expected result:
+----------+----------+
|         a|         b|
+----------+----------+
|2020-02-01|2020-02-01|
|2020-01-01|2020-01-02|
+----------+----------+
```

1. the rule `PullOutGroupingExpressions` will pull out to a project node under aggregate

<details>
  <summary>logical plan after apply rule org.apache.spark.sql.catalyst.optimizer.Optimizer$FinishAnalysis </summary>

```

=== Applying Rule org.apache.spark.sql.catalyst.optimizer.Optimizer$FinishAnalysis ===
GlobalLimit 21
+- LocalLimit 21
   +- Project [cast(ReportDate#68 as string) AS ReportDate#74, cast(RawdataDate#69 as string) AS RawdataDate#75]
      +- Project [to_date(ReportDate)#64 AS ReportDate#68, to_date(RawdataDate)#65 AS RawdataDate#69]
         +- Aggregate [_groupingexpression#78, _groupingexpression#79], [_groupingexpression#78 AS to_date(ReportDate)#64, _groupingexpression#79 AS to_date(RawdataDate)#65]
            +- Project [ReportDate#33, RawdataDate#35, cast(ReportDate#33 as date) AS _groupingexpression#78, cast(RawdataDate#35 as date) AS _groupingexpression#79]
               +- Union false, false
                  :- Project [to_date(ReportDate)#31 AS ReportDate#33, to_date(ReportDate)#31 AS RawdataDate#35]
                  :  +- Aggregate [_groupingexpression#80], [_groupingexpression#80 AS to_date(ReportDate)#31]
                  :     +- Project [ReportDate#16, cast(ReportDate#16 as date) AS _groupingexpression#80]
                  :        +- Project [ReportDate#16]
                  :           +- Relation [ReportDate#16] parquet
                  +- Project [to_date(ReportDate)#22 AS ReportDate#26, to_date(RawdataDate)#23 AS RawdataDate#27]
                     +- Aggregate [_groupingexpression#81, _groupingexpression#82], [_groupingexpression#81 AS to_date(ReportDate)#22, _groupingexpression#82 AS to_date(RawdataDate)#23]
                        +- Project [ReportDate#9, RawdataDate#10, cast(ReportDate#9 as date) AS _groupingexpression#81, cast(RawdataDate#10 as date) AS _groupingexpression#82]
                           +- Project [ReportDate#9, RawdataDate#10]
                              +- Relation [ReportDate#9,RawdataDate#10] parquet
```

</details>

2. the project will be pushdown to both sides of the union node by the rule `PushProjectionThroughUnion`, and before applying the rule `RemoveRedundantAliases`, the logical plan would like:

<details>
  <summary>logical plan</summary>

```
GlobalLimit 21
+- LocalLimit 21
   +- Aggregate [_groupingexpression#78, _groupingexpression#79], [cast(_groupingexpression#78 as string) AS ReportDate#74, cast(_groupingexpression#79 as string) AS RawdataDate#75]
      +- Project [_groupingexpression#78, _groupingexpression#79]
         +- Union false, false
            :- Aggregate [_groupingexpression#80], [_groupingexpression#80 AS _groupingexpression#78, _groupingexpression#80 AS _groupingexpression#79]
            :  +- Project [ReportDate#16 AS _groupingexpression#80]
            :     +- Relation [ReportDate#16] parquet
            +- Aggregate [_groupingexpression#81, _groupingexpression#82], [_groupingexpression#81 AS _groupingexpression#83, _groupingexpression#82 AS _groupingexpression#84]
               +- Project [ReportDate#9 AS _groupingexpression#81, RawdataDate#10 AS _groupingexpression#82]
                  +- Relation [ReportDate#9,RawdataDate#10] parquet
```
</details>

3. since the metadata and the alias name are the same, the project will be replaced with `Project [_groupingexpression#80, _groupingexpression#80]`, leading to an unexpected final result.
```
GlobalLimit 21
+- LocalLimit 21
   +- Aggregate [_groupingexpression#80, _groupingexpression#80], [cast(_groupingexpression#80 as string) AS ReportDate#74, cast(_groupingexpression#80 as string) AS RawdataDate#75]
      +- Project [_groupingexpression#80, _groupingexpression#80]
         +- Union false, false
            :- Aggregate [_groupingexpression#80], [_groupingexpression#80, _groupingexpression#80]
            :  +- Project [ReportDate#16 AS _groupingexpression#80]
            :     +- Relation [ReportDate#16] parquet
            +- Aggregate [_groupingexpression#81, _groupingexpression#82], [_groupingexpression#81, _groupingexpression#82]
               +- Project [ReportDate#9 AS _groupingexpression#81, RawdataDate#10 AS _groupingexpression#82]
                  +- Relation [ReportDate#9,RawdataDate#10] parquet
```

the PR fix this issue by generating different alias names for the complex grouping expressions

After this PR, the logical plan after applying rule org.apache.spark.sql.catalyst.optimizer.RemoveRedundantAliases

```
GlobalLimit 21
+- LocalLimit 21
   +- Aggregate [_groupingexpression_1#80, _groupingexpression_2#79], [cast(_groupingexpression_1#80 as string) AS ReportDate#74, cast(_groupingexpression_2#79 as string) AS RawdataDate#75]
      +- Project [_groupingexpression_1#80, _groupingexpression_2#79]
         +- Union false, false
            :- Aggregate [_groupingexpression_1#80], [_groupingexpression_1#80, _groupingexpression_1#80 AS _groupingexpression_2#79]
            :  +- Project [ReportDate#16 AS _groupingexpression_1#80]
            :     +- Relation [ReportDate#16] parquet
            +- Aggregate [_groupingexpression_1#81, _groupingexpression_2#82], [_groupingexpression_1#81, _groupingexpression_2#82]
               +- Project [ReportDate#9 AS _groupingexpression_1#81, RawdataDate#10 AS _groupingexpression_2#82]
                  +- Relation [ReportDate#9,RawdataDate#10] parquet
```

### Does this PR introduce _any_ user-facing change?

No, only bug fix.

### How was this patch tested?

Unit test.

### CODE REVIEW

**Comment by cfmcgrady** [comment]
@cloud-fan @HyukjinKwon @peter-toth

**Comment by peter-toth** [comment]
Thanks for pinging me @cfmcgrady.
I see the issue, but this looks more like a bug in `RemoveRedundantAliases` to me.

**Comment by peter-toth** [comment]
So, I was thinking about adding
```
      case _: Union =>
        var first = true
        plan.mapChildren { child =>
          if (first) {
            first = false
            removeRedundantAliases(child, excluded ++ child.outputSet)
          } else {
            removeRedundantAliases(child, excluded)
          }
        }
```
to `RemoveRedundantAliases` (https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/optimizer/Optimizer.scala#L561)

**Comment by cfmcgrady** [comment]
hi, @peter-toth thank you for your feedback.
While these changes of `RemoveRedundantAliases` solve this issue, they break the guarantee of `alias removal should not break after push project through union`.

https://github.com/apache/spark/blob/0f9c1a2e848fbdfb17af0555d0c8be7d5a7191bb/sql/catalyst/src/test/scala/org/apache/spark/sql/catalyst/optimizer/RemoveRedundantAliasAndProjectSuite.scala#L96-L104

```
== FAIL: Plans do not match ===
 Union false, false                   Union false, false
!:- Project [a#0 AS a#0]              :- LocalRelation <empty>, [a#0]
!:  +- LocalRelation <empty>, [a#0]   +- LocalRelation <empty>, [b#0]
!+- LocalRelation <empty>, [b#0]      
         
ScalaTestFailureLocation: org.apache.spark.sql.catalyst.plans.PlanTestBase at (PlanTest.scala:177)
org.scalatest.exceptions.TestFailedException: 
== FAIL: Plans do not match ===
 Union false, false                   Union false, false
!:- Project [a#0 AS a#0]              :- LocalRelation <empty>, [a#0]
!:  +- LocalRelation <empty>, [a#0]   +- LocalRelation <empty>, [b#0]
!+- LocalRelation <empty>, [b#0] 
```

**Comment by peter-toth** [comment]
I don't think that extra `Alias` does any harm in that test, just the expected needs to be amended.

My proposal also fixes the issue of the following:

```
SELECT a, b AS a FROM (
  SELECT a, a AS b FROM (SELECT a FROM VALUES (1) AS t(a))
  UNION ALL
  SELECT a, b FROM (SELECT a, b FROM VALUES (1, 2) AS t(a, b))
)
```
and the query returns the correct result:
```
+---+---+
|  a|  a|
+---+---+
|  1|  1|
|  1|  2|
+---+---+
```

**Comment by cloud-fan** [comment]
`Union.output` is a long-standing issue (same for `Join.output`). It reuses the first child's output but apparently `Union` and its first child output different values. We have to carefully work around this issue in places like `FoldablePropagation`. Maybe we need to do the same in `RemoveRedundantAliases`.

**Comment by peter-toth** [comment]
I've opened a PR with my proposal here: https://github.com/apache/spark/pull/37334

**Pull request closed without merging**
