### PR TITLE
[SPARK-13164][CORE] Replace deprecated synchronized buffer in core

### PR DESCRIPTION
**Pull request by holdenk**
Building with scala 2.11 results in the warning trait SynchronizedBuffer in package mutable is deprecated: Synchronization via traits is deprecated as it is inherently unreliable. Consider java.util.concurrent.ConcurrentLinkedQueue as an alternative. Investigation shows we are already using ConcurrentLinkedQueue in other locations so switch our uses of SynchronizedBuffer to ConcurrentLinkedQueue.

### CODE REVIEW

**Comment by holdenk** [comment]
Note that the explicit toSeq effectively takes a snapshot of the queue, whereas before the implicit conversion would allow elements to be added but since we only call toSeq in the test at the end this should be fine.

**Comment by holdenk** [comment]
cc @srowen who expressed interest on the JIRA

**Comment by andrewor14** [comment]
LGTM merged into master.

**Comment by tedyu** [comment]
Should scalastyle rule be added to ban use of mutable.SynchronizedBuffer ?

**Comment by andrewor14** [comment]
sounds like a good rule

**Pull request closed without merging**
