### PR TITLE
[SPARK-34058][UI] Add button to show/hide all stage details

### PR DESCRIPTION
**Pull request by brandonJY**
### What changes were proposed in this pull request?
Currently there is no way to expand all stages details all in once. It is hard if you want to navigate to search for specific stages details.

Proposed to add a UI elements to collapse/expand all stages detail in stages tab. 
image

### Why are the changes needed?
Currently there is no way to expand all stages details all in once. It is hard if you want to navigate to search for specific stages details.

### Does this PR introduce _any_ user-facing change?
There is no button to cexpand/collapse all stages detail all in once

### How was this patch tested?
manual tested

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @sarutak and @gengliangwang FYI

**Comment by sarutak** [comment]
Hi @brandonJY , I have three comments.

1.  I tried this change but it doesn't work on my environment (Pop!_OS, an Ubuntu variant, and Firefox). When I click the button you added, I get the following error on the browser's console.
errorn-on-click

2. At first, I couldn't notice where is the button. Users might not notice it's a button.

3. Could you add the screenshots for before/after press the button.

**Comment by gengliangwang** [comment]
@brandonJY could you further explain why we need to show all the details? Normally the details are stack traces.

**Comment by brandonJY** [comment]
> @brandonJY could you further explain why we need to show all the details? Normally the details are stack traces.

Hey @gengliangwang , sometimes we would want to quick identify a stage, and the code line number is not that helpful. Instead, we would have to go through all the stage detail (a.k.a stack traces) to quickly identify the stage we are looking for.

**Review by gengliangwang — COMMENTED** [review]
Sorry but I don't think this is not a reasonable feature. Also, it makes the UI more complex.

**Comment by brandonJY** [comment]
ok. thanks for reviewing.

**Pull request closed without merging**
