### PR TITLE
[SPARK-11401] [MLLIB] PMML export for Logistic Regression Multiclass Classification

### PR DESCRIPTION
**Pull request by selvinsource**
Jira issue: https://issues.apache.org/jira/browse/SPARK-11401

### CODE REVIEW

**Comment by dbtsai** [comment]
Jenkins, ok to test

**Comment by dbtsai** [comment]
It's hard to see the changes with moving the file from `BinaryClassificationPMMLModelExport.scala` to `ClassificationPMMLModelExport.scala` Can you create an separate sub-task for moving the class name?

**Comment by selvinsource** [comment]
Here the diff between the two files (BinaryClass vs Class):
http://www.mergely.com/w7ufbahQ/

Practically the difference between the Binary and the Class version is that instead of building two fixed regression tables (YES/NO), I create a Category Zero table (the one without the predictors) and as many regression tables as the number of the categories (numClasses-1).

The code, in case of numClasses = 2, does exactly what it was doing before in the BinaryClassificationPMMLModelExport class that I originally wrote.

My spark validator project confirms both Binary and Multiclass pmml export works fine:
https://github.com/selvinsource/spark-pmml-exporter-validator/tree/logistic_regression_multi_class

See sections: 
Logistic Regression (Binary Classification)
Logistic Regression (Multiclass Classification)

**Comment by dbtsai** [comment]
okay. please fix fails MiMa tests. thanks.

**Comment by selvinsource** [comment]
@dbtsai
how do I fix the following? 
```
[info] spark-mllib: found 1 potential binary incompatibilities (filtered 51)
[error]  * class org.apache.spark.mllib.pmml.export.BinaryClassificationPMMLModelExport does not have a correspondent in new version
[error]    filter with: ProblemFilters.exclude[MissingClassProblem]("org.apache.spark.mllib.pmml.export.BinaryClassificationPMMLModelExport")
```
Not familiar with Mima.

Thanks.

**Comment by dbtsai** [comment]
You need to add `ProblemFilters.exclude[MissingClassProblem]("org.apache.spark.mllib.pmml.export.BinaryClassificationPMMLModelExport")` into Mima in `project/` folder.

**Comment by selvinsource** [comment]
@dbtsai I don't think the issue with failed Spark test is to do with my code.

**Comment by dbtsai** [comment]
Jenkins, retest this please

**Comment by selvinsource** [comment]
@dbtsai any advice on why it is failing? All the pmml tests passed and that is the only thing I changed.

**Comment by dbtsai** [comment]
Can you rebase the master?

**Comment by selvinsource** [comment]
@dbtsai thanks for the suggestion, rebasing from master seems to have fixed it.

**Comment by rxin** [comment]
Thanks for the pull request. I'm going through a list of pull requests to cut them down since the sheer number is breaking some of the tooling we have. Due to lack of activity on this pull request, I'm going to push a commit to close it. Feel free to reopen it or create a new one. 

@dbtsai there are a few pull requests that were waiting on your review. Can you revisit them even if they are closed?

**Pull request closed without merging**
