### PR TITLE
[SPARK-14590] Update pull request template with JIRA link

### PR DESCRIPTION
**Pull request by lresende**
## What changes were proposed in this pull request?

Update pull request template to have direct link to jira issue

### CODE REVIEW

**Comment by rxin** [comment]
Isn't this obvious from the JIRA title?

**Comment by lresende** [comment]
@rxin It is, but you then have to search for the jira. This makes it much more easy to just access the jira, from the link, similar to how the jira has the link to the pr. I have seen this in different projects, and found it very convenient and useful.

**Comment by rxin** [comment]
I'm not sure if we want this. People are already complaining the template is too long. This creates more work to create a pr, and does not add any extra information.

**Comment by lresende** [comment]
ok, I will leave it open for a day in case anyone else has interest on the change, otherwise close it.

**Comment by rxin** [comment]
btw https://spark-prs.appspot.com/ already does this for you

**Comment by srowen** [comment]
Yeah it's redundant and I think it's just another thing to not get filled out

**Pull request closed without merging**
