### PR TITLE
[SPARK-28206][PYTHON] Remove the legacy Epydoc in PySpark API documentation

### PR DESCRIPTION
**Pull request by HyukjinKwon**
## What changes were proposed in this pull request?

Seems like we used to generate PySpark API documentation by Epydoc almost at the very first place (see https://github.com/apache/spark/commit/85b8f2c64f0fc4be5645d8736629fc082cb3587b).

This fixes an actual issue:

Before:

Screen Shot 2019-07-05 at 8 20 01 PM

After:

Screen Shot 2019-07-05 at 8 20 05 PM

It seems apparently a bug within `epytext` plugin during the conversion between`@param` and `:param` syntax. See also [Epydoc syntax](http://epydoc.sourceforge.net/manual-epytext.html).

Actually, Epydoc syntax violates [PEP-257](https://www.python.org/dev/peps/pep-0257/) IIRC and blocks us to enable some rules for doctest linter as well.

We should remove this legacy away and I guess Spark 3 is good timing to do it.

## How was this patch tested?

Manually built the doc and check each.

I had to manually find the Epydoc syntax by `git grep -r "{L"`, for instance.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @rxin, @srowen, @mengxr, @BryanCutler (we talked about PEP-257 before IIRC), @JoshRosen

**Comment by srowen** [comment]
I had never seen this. Looks good if it simplifies and improves docs.

**Comment by rxin** [comment]
seems fine

**Comment by mengxr** [comment]
LGTM. Confirm that `@pandas_udf` is now correctly rendered in API doc. I didn't spot any regression.

**Comment by mengxr** [comment]
Merged into master. I didn't backport the change to branch-2.4 due to number of lines of edit.

**Comment by HyukjinKwon** [comment]
Thanks guys!

**Comment by BryanCutler** [comment]
LGTM, thanks for doing this @HyukjinKwon !

**Pull request closed without merging**
