### PR TITLE
[SPARK-14080] [SQL] remove the unnecessary logical operation

### PR DESCRIPTION
**Pull request by bomeng**
## What changes were proposed in this pull request?

This will remove the unnecessary logical operations in the codegen for Filter. 

For example:

`/* 072 */ if (!(!(filter_isNull2))) continue;`

It will be better to be:
`/* 072 */ if (filter_isNull2) continue;`
## How was this patch tested?

I have run the test cases to verify that it will get the same results as before and the codegen.

### CODE REVIEW

**Comment by rxin** [comment]
What's the query? It's really weird to do this with string manipulation.

**Comment by bomeng** [comment]
for example, test("Test to check we can use Long.MinValue") in the SQLQuerySuite.scala: 
```
    checkAnswer(
      sql(s"SELECT key FROM testData WHERE key > ${Long.MinValue}"),
      (1 to 100).map(Row(_)).toSeq
    )

It will generate the codes as (partially) :
/* 060 */       boolean filter_isNull3 = filter_isNull4;
/* 061 */       Decimal filter_value3 = null;
/* 062 */       if (!filter_isNull4) {
/* 063 */         Decimal filter_tmpDecimal1 = filter_value4.clone();
/* 064 */         
/* 065 */         if (filter_tmpDecimal1.changePrecision(19, 0)) {
/* 066 */           filter_value3 = filter_tmpDecimal1;
/* 067 */         } else {
/* 068 */           filter_isNull3 = true;
/* 069 */         }
/* 070 */         
/* 071 */       }
/* 072 */       if (!(!(filter_isNull3))) continue;
/* 073 */       
/* 074 */       /* (cast(cast(input[0, int] as decimal(10,0)) as decimal(19,0)) > -9223372036854775808) */
/* 075 */       boolean filter_isNull6 = true;
/* 076 */       boolean filter_value6 = false;
/* 077 */       /* cast(cast(input[0, int] as decimal(10,0)) as decimal(19,0)) */
/* 078 */       /* cast(input[0, int] as decimal(10,0)) */
/* 079 */       boolean filter_isNull8 = false;
/* 080 */       Decimal filter_value8 = null;

See line 072. There are also bunch of similar test cases in SQLQuerySuite.scala will generate this.
```

**Comment by bomeng** [comment]
Other test cases generate this issue in SQLQuerySuite.scala:
  test("SPARK-11303: filter should not be pushed down into sample")
  test("SPARK-3173 Timestamp support in the parser")

**Comment by rxin** [comment]
Either way, we shouldn't' do string manipulation on the generated code. If this is a problem, fix it somewhere else.

**Comment by bomeng** [comment]
It would probably be cosmic issue and java compiler could optimize this redundancy away. Close it.

**Comment by rxin** [comment]
Thanks!

**Pull request closed without merging**
