### PR TITLE
[SPARK-38678][TESTS] Enable RocksDB tests on Apple Silicon on MacOS

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to enable `RocksDB`-related test coverage on Apple Silicon on MacOS.
- In `kvstore`, remove the following in `RocksDBSuite` and `RocksDBIteratorSuite` Java test.
```
assumeFalse(SystemUtils.IS_OS_MAC_OSX && SystemUtils.OS_ARCH.equals("aarch64"));
```
- Remove `ExtendedRocksDBTest` test tag.
- Remove `ExtendedRocksDBTest` test tag annotation from the following `core` module tests.
  - `HistoryServerDiskManagerSuite`
  - `HybridStoreSuite`
  - `AppStatusListenerSuite`
- Remove `ExtendedRocksDBTest` test tag annotation from the following `streaming` module tests.
  - `RocksDBStateStoreIntegrationSuite`
  - `RocksDBStateStoreSuite`
  - `RocksDBSuite`
- Remove `RocksDBStateStoreProvider` exclusion from `providerOptions`.
  - `StreamingSessionWindowSuite`

### Why are the changes needed?

RocksDB 7 supports Apple Silicon officially. 

### Does this PR introduce _any_ user-facing change?

No. This is a dev-only change.

### How was this patch tested?

Manually test on Apple Silicon environment with Java 17.
```
$ build/sbt "kvstore/test" "core/testOnly *RocksDB*" "sql/testOnly *RocksDB*" "sql/testOnly *.StreamingSessionWindowSuite"
```

### CODE REVIEW

**Review by viirya — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @viirya !

**Comment by dongjoon-hyun** [comment]
All tests passed in https://github.com/apache/spark/pull/35993/commits/24abff91e5c6f7fbcd37a9ea734c820beade4fff  and Java linter is fixed at https://github.com/apache/spark/pull/35993/commits/d9ae2cb8031167a84795186b93539b1af873f4b7. The Python linter is irrelevant to this PR.
```
annotations failed mypy checks:
[23](https://github.com/dongjoon-hyun/spark/runs/5726920552?check_suite_focus=true#step:15:23)
python/pyspark/pandas/ml.py:62: error: Incompatible types in assignment (expression has type "Index", variable has type "MultiIndex")  [assignment]
[24](https://github.com/dongjoon-hyun/spark/runs/5726920552?check_suite_focus=true#step:15:24)
python/pyspark/pandas/frame.py:6133: error: unused "type: ignore" comment
[25](https://github.com/dongjoon-hyun/spark/runs/5726920552?check_suite_focus=true#step:15:25)
python/pyspark/pandas/frame.py:6292: error: Incompatible types in assignment (expression has type "Index", variable has type "MultiIndex")  [assignment]
[26](https://github.com/dongjoon-hyun/spark/runs/5726920552?check_suite_focus=true#step:15:26)
Found 3 errors in 2 files (checked 325 source files)
```

Merged to master.

**Comment by LuciferYang** [comment]
LGTM + 1, thanks @dongjoon-hyun ~~~

**Comment by dongjoon-hyun** [comment]
Thank you, @LuciferYang !

**Pull request closed without merging**
