### PR TITLE
[SPARK-21254] [WebUI] History UI performance fixes 

### PR DESCRIPTION
**Pull request by 2ooom**
## What changes were proposed in this pull request?

As described in JIRA ticket, History page is taking ~1min to load for cases when amount of jobs is 10k+.
Most of the time is currently being spent on DOM manipulations and all additional costs implied by this (browser repaints and reflows).
PR's goal is not to change any behavior but to optimize time of History UI rendering:

1. The most costly operation is setting `innerHTML` for `duration` column within a loop, which is [extremely unperformant](https://jsperf.com/jquery-append-vs-html-list-performance/24). [Refactoring ](https://github.com/criteo-forks/spark/commit/b7e56eef4d66af977bd05af58a81e14faf33c211) this helped to get page load time **down to 10-15s**

2. Second big gain bringing page load time **down to 4s** was [was achieved](https://github.com/criteo-forks/spark/commit/3630ca212baa94d60c5fe7e4109cf6da26288cec) by detaching table's DOM before parsing it with DataTables jQuery plugin.

3. Another chunk of improvements ([1]https://github.com/criteo-forks/spark/commit/aeeeeb520d156a7293a707aa6bc053a2f83b9ac2), [2](https://github.com/criteo-forks/spark/commit/e25be9a66b018ba0cc53884f242469b515cb2bf4), [3](https://github.com/criteo-forks/spark/commit/91697079a29138b7581e64f2aa79247fa1a4e4af)) was focused on removing unnecessary DOM manipulations that in total contributed ~250ms to page load time.

## How was this patch tested?

Tested by existing Selenium tests in `org.apache.spark.deploy.history.HistoryServerSuite`.

Changes were also tested on Criteo's spark-2.1 fork with 20k+ number of rows in the table, reducing load time to 4s.

### CODE REVIEW

**Comment by jiangxb1987** [comment]
Do we really need to backport this? @srowen

**Comment by srowen** [comment]
Yes, tough call on the back-port. I'd normally say we don't back-port optimizations to maintenance branches. If the optimization relieved a significant usability problem, you could consider it a bug fix. For this one I'm on the fence about it, and would prefer to hear someone else in support of it.

**Comment by ajbozarth** [comment]
I like the idea of back porting this, but I agree with @srowen that this falls into a grey area between an improvement and a bug fix. If there's opposition to the back-port I won't argue, but I'm personally in favor.

**Comment by srowen** [comment]
@2ooom how useful would that be for y'all ?

**Comment by 2ooom** [comment]
@srowen At criteo the issue has grown critical about 3 month ago and at that point (we had 11k rows in history table at a time and) when history page was taking at least 1min to load.  Now we're at 26k+ rows and we're increasing spark adoption.
So I would actually treat this PR as a bug fix and try to merge in all supported branches (2.2, 2.3, maybe even 2.1) to save frustration for other spark-users.

**Comment by srowen** [comment]
@2ooom merged to 2.2. You can close this PR now; it won't auto-close.

**Comment by 2ooom** [comment]
Thank you @srowen

**Pull request closed without merging**
