### PR TITLE
[MINOR][SS] Call fetchEarliestOffsets when it is necessary

### PR DESCRIPTION
**Pull request by viirya**
### What changes were proposed in this pull request?

This minor patch changes two variables where calling `fetchEarliestOffsets` to `lazy` because these values are not always necessary.

### Why are the changes needed?

To avoid unnecessary Kafka RPC calls.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Unit test.

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
cc @gaborgsomogyi, @HeartSaVioR, and @xuanyuanking

**Review by dongjoon-hyun — APPROVED** [review]

**Review by gaborgsomogyi — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master. branch-3.1 and branch-3.0.

This is an improvement but It think it's very safe to port back ...

**Comment by viirya** [comment]
Thanks @dongjoon-hyun @gaborgsomogyi @HyukjinKwon

**Comment by xuanyuanking** [comment]
Late LGTM.

**Pull request closed without merging**
