### PR TITLE
[SPARK-22450][WIP][Core][MLLib][FollowUp] Safely register MultivariateGaussian

### PR DESCRIPTION
**Pull request by zhengruifeng**
## What changes were proposed in this pull request?
register following classes in Kryo:
"org.apache.spark.ml.stat.distribution.MultivariateGaussian",
"org.apache.spark.mllib.stat.distribution.MultivariateGaussian"

## How was this patch tested?
added tests

Due to existing module dependency, I can not import spark-core in mllib-local's testsuits, so I do not add testsuite in `org.apache.spark.ml.stat.distribution.MultivariateGaussianSuite`.
And I notice that class `ClusterStats` in `ClusteringEvaluator` is registered in a different way, should it be modified to keep in line with others in ML? @srowen

### CODE REVIEW

**Comment by srowen** [comment]
Can you explain the issue here? Spark's tests work fine right now.
mllib-local is not supposed to depend on core.

**Comment by zhengruifeng** [comment]
@srowen Existing kryo-register testsuite need to import spark-core:
```
import org.apache.spark.SparkConf
import org.apache.spark.serializer.KryoSerializer

val conf = new SparkConf(false)
conf.set("spark.kryo.registrationRequired", "true")
val ser = new KryoSerializer(conf).newInstance()
```

Since mllib-local is not dependent on spark-core, current classes in mllib-local do not test kryo-serialization at all. E.g. `mllib.linalg.VectorsSuite` contains test `test("kryo class register")`, while `ml.linalg.VectorsSuite`  do not have it.

**Comment by srowen** [comment]
You're requiring registration, which is what makes this fail, right? why do that? I think I'm missing something.

**Comment by zhengruifeng** [comment]
Do you mean fail in this pr? It was caused by a non-registered filed `BDM[Double]`.
`MultivariateGaussian` is used in GMM, kryo-registration should help performance.

As to mllib-local's dependency, it is another thing: current kryo-regiestered classes, like 'ml.linalg.Vector', 'ml.linalg.Matrix', do not have kryo test in their testsuites.

**Comment by srowen** [comment]
OK, that's the issue, yeah. Registration is an optimization. I wonder, what other classes should we add if we're going to add this one? I don't know if it needs a test. But if there are 10 other somewhat commonly-used classes that are serialized during Spark ML operations, they should be registered.

**Comment by zhengruifeng** [comment]
I am not sure, but maybe all serializable classes need to be registered. 
Since `MultivariateGaussian` is a public class, so I think we need to add it.
I also wonder whether a test is needed. If no longer needed, I can list all other public ones in ML in this PR.

**Comment by zhengruifeng** [comment]
not all public serializable classes are needed to registered. Only those one which needed ser-deser should be registered, one important groups should be transformers and prediction models.

**Comment by zhengruifeng** [comment]
retest this please

**Comment by srowen** [comment]
OK, I wonder if you have time to take a quick pass over the "Serializable" classes in MLlib to identify a few more that are likely important to register with Kryo? there are probably a few more. If so then that would help improve this all at once rather than class by class.

**Comment by zhengruifeng** [comment]
retest this please

**Comment by zhengruifeng** [comment]
retest this please

**Comment by srowen** [comment]
Hm. On the one hand, I don't actually think we need to _test_ that certain classes are registered except for some performance critical ones, maybe. However if a class can't be registered except by registering every class it touches (like internal anonymous ones), it may not have any effect to register many of these; Kryo won't work. Further, it may then break usages that have kryo registration required otherwise. I guess back out any registration of classes that seems to require a bunch of anonymous classes be registered too?

**Comment by zhengruifeng** [comment]
@srowen Yes, this is the problem. I have to register `Param*` before any prediction model, but there are too many anonymous classes  in `ParamValidators` and other places, and I have not found an efficient way to list those anonymous ones.
So I wonder whether we could continue to register all of them.  Or only list simple classes like `MultivariateGaussian `?

**Comment by srowen** [comment]
@zhengruifeng you are right, let's stay conservative. Thanks for investigating. Are there any simple, commonly-used classes that should be serializable by themselves without registering other classes, anything else obvious to add? it may just be MultivariateGaussian

**Comment by zhengruifeng** [comment]
retest this please

**Review by srowen — APPROVED** [review]

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
