### PR TITLE
[SPARK-17017][ML][MLLIB][ML][DOC] Updated the ml/mllib feature selection docs for ChiSqSelector

### PR DESCRIPTION
**Pull request by lins05**
## What changes were proposed in this pull request?

A follow up for #14597 to update feature selection docs about ChiSqSelector.
## How was this patch tested?

Generated html docs. It can be previewed at:
- ml: http://sparkdocs.lins05.pw/spark-17017/ml-features.html#chisqselector
- mllib: http://sparkdocs.lins05.pw/spark-17017/mllib-feature-extraction.html#chisqselector

### CODE REVIEW

**Comment by srowen** [comment]
Please add this to #15214 with @yanboliang -- this is getting spread across too many places.

**Comment by lins05** [comment]
Just found #15214 and #15212, I think this one need to wait until those are merged.

**Comment by srowen** [comment]
@lins05 OK, https://github.com/apache/spark/pull/15214 is merged. I don't think this can relate to https://github.com/apache/spark/pull/15212 because it's not necessarily going to be added. Is this doc change still correct/relevant?

**Comment by lins05** [comment]
@srowen I saw there was a proposal to change `setAlpha` to `setFpr` in #15214, but it was not changed when the PR is merged. So I think this PR is up to upate.

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
