### PR TITLE
[SPARK-25063][SQL] Rename class KnowNotNull to KnownNotNull

### PR DESCRIPTION
**Pull request by maryannxue**
## What changes were proposed in this pull request?

Correct the class name typo checked in through SPARK-24891

## How was this patch tested?

Passed all existing tests.

### CODE REVIEW

**Comment by maryannxue** [comment]
@gatorsmile

**Review by gatorsmile — COMMENTED** [review]
LGTM

**Comment by cloud-fan** [comment]
retest this please

**Comment by gatorsmile** [comment]
Thanks! Merged to master.

**Pull request closed without merging**
