### PR TITLE
Close stale PRs.

### PR DESCRIPTION
**Pull request by vanzin**
Closes #16191
Closes #16198
Closes #14561
Closes #14223
Closes #7739
Closes #13026

### CODE REVIEW

**Comment by vanzin** [comment]
Let's see if others have anything to add. @srowen @rxin

**Comment by rxin** [comment]
LGTM

**Comment by rxin** [comment]
Similar to the last pr i coudln't merge this with merge tool but I pushed directly to master.

**Comment by vanzin** [comment]
Ah, cool. I was planning to do that later, but since you already did, closing.

**Pull request closed without merging**
