### PR TITLE
[SPARK-40765][SQL] Optimize redundant fs operation in `CommandUtils#calculateSingleLocationSize#getPathSize` method

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr change the 2nd input parameter from `Path` to `FileStatus` to avoid redundant `fs.getFileStatus(path)` in each recursive call.

### Why are the changes needed?
Reduce one dfs operation in each recursive call.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass Github Actions

### CODE REVIEW

**Comment by LuciferYang** [comment]
cc @HyukjinKwon @zhengruifeng

**Review by HyukjinKwon — APPROVED** [review]

**Comment by LuciferYang** [comment]
Yes, one `fs.getFileStatus(path)` operation is saved for each recursive call

**Comment by LuciferYang** [comment]
image

https://github.com/apache/spark/blob/0dd78341e64a7e146413156834448707f16bba83/sql/core/src/main/scala/org/apache/spark/sql/execution/command/CommandUtils.scala#L116-L132

Line 122 It is a recursive call. The original logic is pass in `status.getPath`, and then execute `val fileStatus = fs.getFileStatus(status.getPath)` (Line 117).

After change, the recursive call reuse the incoming status.

**Comment by srowen** [comment]
But the caller had to add a new call to get the status. It seems to just be moved around. I don't see the same status retrieved twice in the original, so wondering how we can actually avoid a call here

**Comment by LuciferYang** [comment]
> I don't see the same status retrieved twice in the original

Before recursion, there is an exist `status` instance,  then the recursive call will call `getStatus` for the exist `status`.`getPath`,  Isn't this an unnecessary call?

If there is no recursion, there is no saving.

**Comment by srowen** [comment]
I see so it saves one call, not one call per recursion?

**Comment by LuciferYang** [comment]
Every time a recursive call occurs, it will be saved once (the initial call is not counted, and the initial call is not saved)

**Comment by LuciferYang** [comment]
The saved times are related to the directory level and the number of directories in each level

**Comment by srowen** [comment]
I may have to think about it more, but still don't see how this saves much as you have _added_ a new call to getFileStatus too. Right? how can it save all the calls but one?

**Comment by LuciferYang** [comment]
@srowen Is the above example helpful?

**Comment by LuciferYang** [comment]
From the example:

- `fs.getFileStatus(Path(/a))` not saved, but no additional calls are added
- `fs.getFileStatus(Path(/a/b))`,`fs.getFileStatus(Path(/a/b/c))` and `fs.getFileStatus(Path(/a/b/c/d.txt))` saved

**Comment by srowen** [comment]
OK, I'm still not seeing how they are saved, because in the recursive call, getFileStatus is called. After, you are still calling this on /a/b, /a/b/c, etc. Right? That is line 138

**Comment by LuciferYang** [comment]
image


Is it because of code folding? After change, only getFileStatus will be made for `/a`

**Comment by srowen** [comment]
Oh yes I think that's it. The other call is not in the same recursive loop. Ok I get it

**Review by srowen — APPROVED** [review]

**Comment by LuciferYang** [comment]
> Oh yes I think that's it. The other call is not in the same recursive loop. Ok I get it

Yes, and I finally know why you had doubts before :)

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by LuciferYang** [comment]
Thanks @srowen @HyukjinKwon and @zhengruifeng

**Comment by LuciferYang** [comment]
I need to know more about the rules for defining error-class, so close first

**Comment by LuciferYang** [comment]
Ignore the previous

**Pull request closed without merging**
