### PR TITLE
[MINOR][DOCS] Add proper periods and spaces for CLI help messages and `config` doc.

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
## What changes were proposed in this pull request?

This PR adds some proper periods and spaces to Spark CLI help messages and SQL/YARN conf docs for consistency.
## How was this patch tested?

Manual.

### CODE REVIEW

**Comment by srowen** [comment]
OK, it's minor, but I suppose that improves consistency. Fixing the space problems is good.

**Comment by dongjoon-hyun** [comment]
Thank you, @srowen !

**Comment by srowen** [comment]
Merged to master

**Comment by dongjoon-hyun** [comment]
Thank you again!

**Pull request closed without merging**
