### PR TITLE
[SPARK-20208][DOCS][FOLLOW-UP] Add FP-Growth to SparkR programming guide

### PR DESCRIPTION
**Pull request by zero323**
## What changes were proposed in this pull request?

Add `spark.fpGrowth` to SparkR programming guide.

## How was this patch tested?

Manual tests.

### CODE REVIEW

**Review by felixcheung — APPROVED** [review]

**Comment by felixcheung** [comment]
merged to master

**Comment by zero323** [comment]
Thanks.

**Comment by jkbradley** [comment]
@felixcheung  Since this is a doc for an API in 2.2, do you mind merging this into branch-2.2 as well?  Thanks!

**Comment by felixcheung** [comment]
merged to 2.2
it just missed the cut for rc and i missed it afterward.

**Pull request closed without merging**
