### PR TITLE
[SPARK-16850][SQL] Improve type checking error message for greatest/least

### PR DESCRIPTION
**Pull request by petermaxlee**
## What changes were proposed in this pull request?

Greatest/least function does not have the most friendly error message for data types. This patch improves the error message to not show the Seq type, and use more human readable data types.

Before:

```
org.apache.spark.sql.AnalysisException: cannot resolve 'greatest(CAST(1.0 AS DECIMAL(2,1)), "1.0")' due to data type mismatch: The expressions should all have the same type, got GREATEST (ArrayBuffer(DecimalType(2,1), StringType)).; line 1 pos 7
```

After:

```
org.apache.spark.sql.AnalysisException: cannot resolve 'greatest(CAST(1.0 AS DECIMAL(2,1)), "1.0")' due to data type mismatch: The expressions should all have the same type, got GREATEST(decimal(2,1), string).; line 1 pos 7
```
## How was this patch tested?

Manually verified the output and also added unit tests to ConditionalExpressionSuite.

### CODE REVIEW

**Comment by petermaxlee** [comment]
@cloud-fan please take a look. A small issue I found when I was working on the other pull request.

**Comment by cloud-fan** [comment]
LGTM

**Comment by cloud-fan** [comment]
BTW how about we move `Greatest` and `Least` to `arithmetic.scala`? They are not conditional expressions...

**Comment by cloud-fan** [comment]
thanks. merging to master!

**Comment by rxin** [comment]
Yea we should probably move those.

**Comment by rxin** [comment]
I've also cherry picked this into branch-2.0.

**Pull request closed without merging**
