### PR TITLE
[SPARK-10264][Documentation] Added @Since to ml.recomendation

### PR DESCRIPTION
**Pull request by Wenpei**
I create new pr since original pr long time no update.
Please help to review.

@srowen

### CODE REVIEW

**Comment by srowen** [comment]
As a continuation of https://github.com/apache/spark/pull/8532 it seems OK to me; I'll wait a minute to see if @mengxr wants to confirm since I haven't been involved in these kinds of changes

**Comment by Wenpei** [comment]
I guess @mengxr take a long vocation those days.  Just guess from his github contribute status. :-)

**Comment by srowen** [comment]
Merged to master. @Wenpei maybe you want to try finishing the other sub-issues of https://issues.apache.org/jira/browse/SPARK-7751 ?

**Comment by Wenpei** [comment]
Thanks @srowen. I will take a try.

**Pull request closed without merging**
