### PR TITLE
[SPARK-17194] Use single quotes when generating SQL for string literals

### PR DESCRIPTION
**Pull request by JoshRosen**
When Spark emits SQL for a string literal, it should wrap the string in single quotes, not double quotes. Databases which adhere more strictly to the ANSI SQL standards, such as Postgres, allow only single-quotes to be used for denoting string literals (see http://stackoverflow.com/a/1992331/590203).

### CODE REVIEW

**Comment by JoshRosen** [comment]
Jenkins, retest this please.

**Comment by dongjoon-hyun** [comment]
Hi, @JoshRosen .
The generated SQL seems to be changed. In order to pass `LogicalPlanToSQLSuite`, you can regenerate the answer set with the following command.
```
SPARK_GENERATE_GOLDEN_FILES=1 build/sbt "hive/test-only *LogicalPlanToSQLSuite"
```

**Comment by JoshRosen** [comment]
Thanks @dongjoon-hyun for the pointer; I've regenerated the answer set and all tests are now passing.

**Comment by dongjoon-hyun** [comment]
Good for you! :)

**Comment by hvanhovell** [comment]
LGTM - merging to master. Thanks!

**Pull request closed without merging**
