### PR TITLE
[SPARK-43535][BUILD] Adjust the ImportOrderChecker rule to resolve long-standing import order issues

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to adjust the ImportOrderChecker rule to resolve long-standing import order issues.

### Why are the changes needed?
Make code style consistent.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA.

### CODE REVIEW

**Comment by panbingkun** [comment]
I have checked all the codes of the `connect` module.

**Comment by panbingkun** [comment]
Through the debug plugin scalastyle, I found that the logic of the ImportOrderChecker rule is as follows, for example, in the xxx file, the following import：
image

Firstly, when it iterates through the first import - `import ammonite.compiler.CodeClassWrapper`, it believes that there are no imports related to group `group.java` and `group.scala` at this time. The logic enters the check of the third group (`group.3rdParty`), and the rule we configured at this time only does not allow starting with `org.apache.spark.`. This condition is met, but it is not what we want.

By adjusting the regular matching rules of `group.3rdParty` group, the above situation can be avoided. We do not allow starting with `javax?.`, `scala.`, or `org.apache.spark.`.

The logic of `org.scalastyle.scalariform.ImportOrderChecker` is as follows:
image
https://github.com/scalastyle/scalastyle/blob/ec14399543d2d5ccf93c3713aa5df21793844791/src/main/scala/org/scalastyle/scalariform/ImportsChecker.scala#L238-L276

**Comment by panbingkun** [comment]
friendly ping @HyukjinKwon @dongjoon-hyun @srowen @LuciferYang

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM (if CI passes).

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
@LuciferYang would you mind trying to merge this into `master` branch by `./dev/merge_spark_pr.py`? It would require you to set several environment variables like `JIRA_USERNAME`, and `remote`.

For example, this is my remote:

```
git remote -v
...
apache	https://github.com/apache/spark.git (fetch)
apache	https://github.com/apache/spark.git (push)
apache-github	https://github.com/apache/spark.git (fetch)
apache-github	https://github.com/apache/spark.git (push)
...
```

**Comment by LuciferYang** [comment]
> @LuciferYang would you mind trying to merge this into `master` branch by `./dev/merge_spark_pr.py` when the tests pass? It would require you to set several environment variables like `JIRA_USERNAME`, and set the `remote` (please also read `./dev/merge_spark_pr.py` script). You should also install `pip install jira` (https://pypi.org/project/jira/) before running that script.
> 
> For example, this is my remote:
> 
> ```
> git remote -v
> ...
> apache	https://github.com/apache/spark.git (fetch)
> apache	https://github.com/apache/spark.git (push)
> apache-github	https://github.com/apache/spark.git (fetch)
> apache-github	https://github.com/apache/spark.git (push)
> ...
> origin	https://github.com/HyukjinKwon/spark.git (fetch)
> origin	https://github.com/HyukjinKwon/spark.git (push)
> ...
> upstream	https://github.com/apache/spark.git (fetch)
> upstream	https://github.com/apache/spark.git (push)
> ...
> ```

OK

**Review by LuciferYang — APPROVED** [review]
+1, LGTM if all test pass

**Comment by LuciferYang** [comment]
> I hope to be qualified to do this one day in the future. Let me continue to strive for it! Congratulations again to @LuciferYang! haha

Thanks @panbingkun :)

**Comment by LuciferYang** [comment]
Merged to master.

**Comment by panbingkun** [comment]
@HyukjinKwon @dongjoon-hyun @LuciferYang 
I have found issues similar to the above in the Java code. Do we need to make restrictions on this? Because the checkStyle plugin uses a similar configuration.
https://checkstyle.sourceforge.io/config_imports.html#ImportOrder
https://github.com/apache/spark/blob/eeab2e701330f7bc24e9b09ce48925c2c3265aa8/common/network-common/src/main/java/org/apache/spark/network/crypto/AuthEngine.java#L18-L36

**Comment by LuciferYang** [comment]
In fact, Spark does not perform checks on the import order of Java code

**Comment by LuciferYang** [comment]
@panbingkun Checking the import order of Java code involves a lot of code changes, which may cause conflicts with previous versions. I think this is not worth because it is just `import order`.

If we could define a rule that checks the import group without checking the order within the group, it might be easier to accept

**Comment by LuciferYang** [comment]
Oh, I think you can give it a try

**Pull request closed without merging**
