### PR TITLE
[SPARK-6887][SQL] ColumnBuilder misses FloatType

### PR DESCRIPTION
**Pull request by yhuai**
https://issues.apache.org/jira/browse/SPARK-6887

### CODE REVIEW

**Comment by yhuai** [comment]
@liancheng Where should I add the test? At first, I thought `NullableColumnBuilderSuite` is the place But, why `NullableColumnBuilderSuite` does not really use those real column builders?

**Comment by yhuai** [comment]
I will add a test in `InMemoryColumnarQuerySuite`.

**Comment by liancheng** [comment]
Good catch! The change LGTM.

`NullableColumnBuilderSuite` uses a mock builder because the real builders also mix in `CompressibleColumnBuilder`, while `NullableColumnBuilderSuite` is used to test nulls.

This wasn't detected before because we were using a column type ID in the columnar buffer, and column accessors are constructed according to the type ID. However, while adding column type for fixed-decimal, decimals with different precisions and scales are actually different types, a single type ID is not enough to represent complete type information. Thus column type ID is invalidated and now column accessors are built according to the data types in the schema.

**Comment by marmbrus** [comment]
Thanks!  Merged to master.

**Pull request closed without merging**
