### PR TITLE
[SPARK-41160][YARN] Fix error when submitting a task to the yarn that enabled the timeline service

### PR DESCRIPTION
**Pull request by xiuzhu9527**
### What changes were proposed in this pull request?

Added dependency on jersey client: 1.19 and jersey core: 1.19 to yarn pom

### Why are the changes needed?

An error is reported when submitting Spark. If yarn has enabled the timeline service
```
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/jersey/api/client/config/ClientConfig
	at org.apache.hadoop.yarn.client.api.TimelineClient.createTimelineClient(TimelineClient.java:55)
	at org.apache.hadoop.yarn.client.api.impl.YarnClientImpl.createTimelineClient(YarnClientImpl.java:181)
	at org.apache.hadoop.yarn.client.api.impl.YarnClientImpl.serviceInit(YarnClientImpl.java:168)
	at org.apache.hadoop.service.AbstractService.init(AbstractService.java:163)
	at org.apache.spark.deploy.yarn.Client.submitApplication(Client.scala:191)
	at org.apache.spark.deploy.yarn.Client.run(Client.scala:1327)
	at org.apache.spark.deploy.yarn.YarnClusterApplication.start(Client.scala:1764)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:958)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1046)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1055)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: com.sun.jersey.api.client.config.ClientConfig
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 14 more

```
Because TimelineClient depends on jersey-client: 1.x when initializing

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by xiuzhu9527** [comment]
@mridulm  Can you help review this PR? THX!

**Comment by mridulm** [comment]
Would be better for @tgravescs to take a look.

**Comment by tgravescs** [comment]
why is the necessary dependency not picked up via Hadoop dependency?

**Comment by xiuzhu9527** [comment]
@tgravescs Thank you very much for your suggestions. I have made changes

**Comment by tgravescs** [comment]
Ok, I see we are explicitly excluding all the jersey client jars from the hadoop client jar.  But it looks like with this change we would have 2 versions of the jersey-client jars, correct?  These 2 have different package names though?  one is org.glassfish.jersey and one is com.sun.jersey correct?   If that is the case it seems like this is ok, unless of course this results in conflicts with other peoples jars and packages.  I see some discussions around this when we moved to jersey 2 - https://issues.apache.org/jira/browse/SPARK-11081 and https://issues.apache.org/jira/browse/SPARK-12154?  specifically see the section on "To recap the discussion, Jersey 1 has two issues:"

**Comment by xiuzhu9527** [comment]
@tgravescs 
1. Yes, Jersey 1 and Jersey 2 are two different packages, one is com.sun.jersey and one is org.glassfish.jersey
2. I will try to use maven-shade-plugin to change the package path of javax.ws.rs in Jersey 1, this will resolve issues（ https://issues.apache.org/jira/browse/SPARK-11081 ）the Jersey1 problem mentioned in

**Comment by xiuzhu9527** [comment]
@tgravescs Have you had a chance to look over the PR I sent you again? THX！

**Comment by tgravescs** [comment]
What version of YARN are you using?

See issue: https://issues.apache.org/jira/browse/SPARK-15343?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&focusedCommentId=16545225#comment-16545225

Specifically it might be related to https://issues.apache.org/jira/browse/YARN-5271

I'm quite hesitant to include something like this as I'm not sure of all the ramifications and things that could break.

**Comment by xiuzhu9527** [comment]
@tgravescs 
1. I am using version 2.7.4 of yarn
2.  https://issues.apache.org/jira/browse/YARN-5271  YARN-5271 does not fundamentally solve the problem, but it captures exceptions and optimizes the prompt so that YarnClient can continue to run. But the timeline client does not work.

**Comment by xiuzhu9527** [comment]
Jersey 1 and Jersey 2 are two different packages. One is com.sun, and the other is org.grasfish.jersey. In addition, META-INF/services/does not exist in the Jersey 2 client, and I have changed the javax.ws.rs contained in Jersey 1 to org.apache.hadoop.shaded.javaax.ws.rs, so the coexistence of Jersey 1 and Jersey 2 will not interfere with each other.

**Comment by xiuzhu9527** [comment]
This problem should be puzzling many people at present. Important for Yarn Timeline compatibility. I think should consider how to make the timeline work normally instead of closing it when an error occurs

**Pull request closed without merging**
