### PR TITLE
[SPARK-9962][ML] Decision Tree training: prevNodeIdsForInstances.unpersist() at end of training

### PR DESCRIPTION
**Pull request by holdenk**
NodeIdCache: prevNodeIdsForInstances.unpersist() needs to be called at end of training.

### CODE REVIEW

**Comment by feynmanliang** [comment]
Changes LGTM (renaming public method but the class is package private), but why do we need this (CC @jkbradley)? `prevNodeIdsForInstances` is never persisted in the first place

**Comment by holdenk** [comment]
@feynmanliang I think it is (sort of), so nodeIdsForInstances.persist(StorageLevel.MEMORY_AND_DISK) and then eventually prevNodeIdsForInstances is set to this and nodeIdsForInstances is updated. (So there isn't an explicit cache call on something with that name but it totally is set to an RDD we want to unpersist). Or at least thats what I remember from reading through the code/JIRA (could have been off though)

**Comment by jkbradley** [comment]
Yep, it's a valid issue.  But...I just noticed: ```prevNodeIdsForInstances``` is already unpersisted on line 179.  Incorrectly.  That 179 should be within deleteAllCheckpoints.  Would you mind making that fix, removing cleanupCache, and making the same fix in the spark.mllib version?  Thanks!

**Comment by holdenk** [comment]
@jkbradley thanks for catching that, I'll switch this PR back to WIP and ping you when I've got those changes in too.

**Comment by jkbradley** [comment]
Is this still WIP?

**Comment by holdenk** [comment]
Oh no, sorry just forgot to update the title. Will do that momentarily.

On Monday, September 21, 2015, jkbradley <notifications@github.com> wrote:

> Is this still WIP?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apache/spark/pull/8541#issuecomment-142138199>.
>


-- 
Cell : 425-233-8271
Twitter: https://twitter.com/holdenkarau
Linked In: https://www.linkedin.com/in/holdenkarau

**Comment by jkbradley** [comment]
LGTM, merging with master.  Thanks!

**Pull request closed without merging**
