### PR TITLE
[SPARK-29590][WEBUI]JDBC/ODBC tab in the spark UI support hide tables, to make it consistent with other tabs.

### PR DESCRIPTION
**Pull request by shahidki31**
### What changes were proposed in this pull request?

Currently, JDBC/ODBC tab in the WEBUI doesn't support hiding table. Other tabs in the web ui like, Jobs, stages, SQL etc supports hiding table (refer https://github.com/apache/spark/pull/22592).
In this PR, added the support for hide table in the jdbc/odbc tab also.

### Why are the changes needed?
Spark ui about the contents of the form need to have hidden and show features, when the table records very much. Because sometimes you do not care about the record of the table, you just want to see the contents of the next table, but you have to scroll the scroll bar for a long time to see the contents of the next table.

### Does this PR introduce any user-facing change?
No, except support of hide table

### How was this patch tested?
Manually tested
 Screenshot 2019-11-01 at 12 10 05 PM
Screenshot 2019-11-01 at 12 10 43 PM

### CODE REVIEW

**Comment by shahidki31** [comment]
cc @srowen Kindly review

**Comment by shahidki31** [comment]
Retest this please

**Review by srowen — COMMENTED** [review]
Seems OK for consistency. Looks good pending tests.

**Comment by shahidki31** [comment]
Thanks @srowen , I have tested manually also,

Screenshot 2019-11-04 at 1 17 26 PM

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
