### PR TITLE
[HOTFIX][BUILD][test-maven]Remove duplicate dependency

### PR DESCRIPTION
**Pull request by zsxwing**

### CODE REVIEW

**Comment by zsxwing** [comment]
CC @JoshRosen

**Comment by JoshRosen** [comment]
I think test-maven might have to be in lowercase? Let's wait and see

**Comment by zsxwing** [comment]
right... just updated it. retest this please

**Comment by zsxwing** [comment]
retest this please

**Comment by zsxwing** [comment]
retest this please

**Comment by zsxwing** [comment]
retest this please

**Comment by zsxwing** [comment]
retest this please

**Comment by JoshRosen** [comment]
LGTM.

**Comment by zsxwing** [comment]
Merging to master

**Pull request closed without merging**
