### PR TITLE
[SPARK-23112][DOC] Add highlights and migration guide for 2.3

### PR DESCRIPTION
**Pull request by MLnick**
Update ML user guide with highlights and migration guide for `2.3`.

## How was this patch tested?

Doc only.

### CODE REVIEW

**Review by felixcheung — APPROVED** [review]

**Comment by felixcheung** [comment]
is this WIP?

**Comment by MLnick** [comment]
It’s just listing any breaking changes, if I missed them. Will do a pass to
check and then remove WIP. If any folks know of breaking changes ping the
JIRA issue

**Comment by felixcheung** [comment]
I'm not sure if they are sufficiently important to bring attention to, but feel they are interesting enough:
https://issues.apache.org/jira/browse/SPARK-20047
https://issues.apache.org/jira/browse/SPARK-20619

**Comment by MLnick** [comment]
`SPARK-20047` was in 2.2 (and mentioned in the previous highlights). We could also mention `SPARK-20619` but I've tried to limit the list.

I checked through the issues for 2.3 and couldn't find any breaking changes. Ping me if anyone knows of any I missed.

**Comment by MLnick** [comment]
Merged to master/branch-2.3

**Pull request closed without merging**
