### PR TITLE
[Doc][Minor]Remove unused libs from docs directory

### PR DESCRIPTION
**Pull request by sarutak**
I think following libraries are not used.

This issue is really minor so I don't file this issue in JIRA.

### CODE REVIEW

**Comment by srowen** [comment]
I am not sure we should do this. If they're unused, they do little harm even at runtime. This is part of the standard Bootstrap package. If we later change to use more elements of Bootstrap, via some automated plugin or output, this might fail.

**Comment by sarutak** [comment]
@srowen  Unexpectedly I found these are not used and I don't strongly want to change. If you judge these libraries should not be removed, I'll close this PR.

**Comment by srowen** [comment]
Yes because it's the full, generic bootstrap source (this is not from Spark). Unless it causes a specific problem I don't think we should muck with it too much.

**Comment by rxin** [comment]
I agree with @srowen. I think it's best to leave these alone unless they are causing problems. Do yo mind closing this PR?

**Comment by sarutak** [comment]
O.K. I'll close.

**Pull request closed without merging**
