### PR TITLE
[SPARK-36344][CORE][SHUFFLE] Fix some typos in ShuffleBlockPusher class.

### PR DESCRIPTION
**Pull request by zhuqi-lucas**
### What changes were proposed in this pull request?
Just to fix some typos in ShuffleBlockPusher class.

### Why are the changes needed?
Fix the typos, make code clear.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
No need test.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Can you keep the PR description template please?  https://github.com/apache/spark/blob/master/.github/PULL_REQUEST_TEMPLATE

**Comment by zhuqi-lucas** [comment]
Thanks @HyukjinKwon  for reminder, i have added the PR description template.

**Comment by HyukjinKwon** [comment]
ok to test

**Comment by HyukjinKwon** [comment]
While we're here, can you take a look and see if there are some more typos around here?

**Comment by zhuqi-lucas** [comment]
@HyukjinKwon I only find the two typos in this class, i will add more typos if i find, thanks.

**Review by mridulm — APPROVED** [review]

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master and branch-3.2.

**Pull request closed without merging**
