### PR TITLE
Update LDAExample with Spark 2.1.0

### PR DESCRIPTION
**Pull request by ganeshkrishnan1**
Changes: Updated code with new Spark 2.x changes
Removed SparkContext and replaced with Spark Session

Fixed compile time errors in new Spark ("Spark Context cannot be initialized here")

Manual Testing using Intellij Idea

### CODE REVIEW

**Comment by srowen** [comment]
Please see http://spark.apache.org/contributing.html first

This is an example for .mllib. While it works with 2.x, or should, it is not intended to use SparkSession, as I understand.

**Comment by ganeshkrishnan1** [comment]
Fails to compile on Spark 2.1.0

Shouldn't mlib be backward compatible?

**Comment by srowen** [comment]
Yes it is. What error do you get? these examples are compiled with the code and compiles correctly in master and previous 2.x builds.

**Comment by ganeshkrishnan1** [comment]
Error:(194, 8) method sparkContext in class Builder cannot be accessed in org.apache.spark.sql.SparkSession.Builder
      .sparkContext(sc)

Using Spark 2.1.0 and scala 2.11

I can see the master version using Spark 2.2.0-Snapshot which means this code has been tested with latest version of Spark but I still get this error in my unit tests.


If we don't want to use SparkSession instead of SparkContext we close this issue.

**Comment by srowen** [comment]
That code is fine and compiles correctly in master, 2.1, and 2.0. See Jenkins builds. Please close the PR.

**Pull request closed without merging**
