### PR TITLE
[SPARK-16261][EXAMPLES][ML] Fixed incorrect appNames in ML Examples

### PR DESCRIPTION
**Pull request by BryanCutler**
## What changes were proposed in this pull request?

Some appNames in ML examples are incorrect, mostly in PySpark but one in Scala.  This corrects the names.
## How was this patch tested?

Style, local tests

### CODE REVIEW

**Comment by BryanCutler** [comment]
Not sure if this is something worth squeezing into 2.0, but I thought I'd patch it now in case.
cc @mengxr @jkbradley

**Comment by srowen** [comment]
LGTM

**Comment by MLnick** [comment]
LGTM too - I've merged to master/branch-2.0. Set the JIRA fix version to `2.0.1` for now since that seems the be what we're doing. I guess when RC2 is cut we will re-assign those ones...

**Comment by BryanCutler** [comment]
Thanks Nick and Sean!

**Pull request closed without merging**
