### PR TITLE
[SPARK-15585][SQL] Fix NULL handling along with a spark-csv behaivour

### PR DESCRIPTION
**Pull request by maropu**
## What changes were proposed in this pull request?

This pr fixes the behaviour of `format("csv").option("quote", null)` along with one of spark-csv.
Also, it explicitly sets default values for CSV options in python.
## How was this patch tested?

Added tests in CSVSuite.

### CODE REVIEW

**Comment by maropu** [comment]
@rxin Could you check this to satisfy your suggestion? If no problem, I'll also set default values in json options in a similar way.

**Comment by HyukjinKwon** [comment]
Whether it should be done here or not, shouldn't we maybe define explicit behavioirs when the options are set to `null`? I mean, currently some of options allow `null` as a legitimate value whereas most of options throw `NullPointException`.
Maybe at least allowing `null` for the option `quote` should be documented here (and for Scala and Java oneas well).

**Comment by maropu** [comment]
yea, it is a difficult question. We must define explicit a behaviour for `quote`, but I'm not sure about other options. So, An alternative idea is to define a special function for `quote`, e.g., `getCharForQuote`, for the null handling. Thought?

Anyway, yes, we need to document this change. After we get consensus, I'll add this doc.

**Comment by HyukjinKwon** [comment]
I think at least we need to handle the other options as well with a clearer message rather than `java.lang.NullPointerException was thrown.`. I see some of options are being validated. For example, `samplingRatio` in JSON data source throws a clear message when the value is a negative numeric type.  I think maybe this can be done in another PR anyway.

**Comment by maropu** [comment]
This is the meaningful suggestion. I think all the option validation should be done in a single place and, if there is an invalidate option, spark should throw clear messages for making users easily understood.
As for `samplingRatio`, should we check the validation not in `inferSchema`, but `JSONOptions? This is because, for example, the validation of `parseMode` is done there. I think we'd be better of finishing these validation in `JSONOptions` and CSVOptions`.

Anyway, I'm not sure these fixes should be included in this pr and follow-up prs seems to be okay to me.

**Comment by rxin** [comment]
Actually sorry -- I thought about this more and unfortunately we can't do it this way.  The main problem is that we would break existing option use case, e.g. the following code:
```python
df.option("sep", "|").csv("...")
```

In this case, the default sep would still be chosen. I'm going to revert this patch, and then think about a workaround instead.

**Comment by rxin** [comment]
I think the best way is probably to document and ask users to use `'\u0000'` explicitly. @maropu does that work?

**Comment by maropu** [comment]
okay though, I'm getting on the flight to SF. So, I'll check in a day, thanks!

**Pull request closed without merging**
