### PR TITLE
[SPARK-14366] Remove sbt-idea plugin

### PR DESCRIPTION
**Pull request by lresende**
## What changes were proposed in this pull request?

Remove sbt-idea plugin as importing sbt project provides much better support.

### CODE REVIEW

**Comment by srowen** [comment]
LGTM

**Comment by JoshRosen** [comment]
LGTM as well.

**Comment by holdenk** [comment]
+1 and if someone really wants it they can always add it to their local plugins.

**Comment by JoshRosen** [comment]
Merging to master.

**Pull request closed without merging**
