### PR TITLE
[SPARK-32729][SQL][DOCS] Add missing since version for math functions

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

Add missing since version for math functions, including
SPARK-8223 shiftright/shiftleft 
SPARK-8215 pi
SPARK-8212 e
SPARK-6829 sin/asin/sinh/cos/acos/cosh/tan/atan/tanh/ceil/floor/rint/cbrt/signum/isignum/Fsignum/Lsignum/degrees/radians/log/log10/log1p/exp/expm1/pow/hypot/atan2
SPARK-8209 conv
SPARK-8213 factorial
SPARK-20751 cot
SPARK-2813 sqrt
SPARK-8227 unhex
SPARK-8218 log(a,b)
SPARK-8207 bin
SPARK-8214 hex
SPARK-8206 round
SPARK-14614 bround

### Why are the changes needed?

fix SQL docs
### Does this PR introduce _any_ user-facing change?

yes, doc updated

### How was this patch tested?

passing doc generation.

### CODE REVIEW

**Comment by yaooqinn** [comment]
cc @cloud-fan @maropu @HyukjinKwon @dongjoon-hyun, thanks a bunch~

**Comment by maropu** [comment]
Thanks for the work, @yaooqinn ! I think its better to file a jira for the update.

**Comment by HyukjinKwon** [comment]
Nice, thanks @yaooqinn for working on this. +1 for a JIRA.

**Comment by yaooqinn** [comment]
thanks, @maropu @HyukjinKwon, I have filed a Jira ticket SPARK-32729

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
