### PR TITLE
[SPARK-48340][PYTHON] Support TimestampNTZ infer schema miss prefer_timestamp_ntz

### PR DESCRIPTION
**Pull request by AngersZhuuuu**
### What changes were proposed in this pull request?
Support TimestampNTZ infer schema miss prefer_timestamp_ntz

### Why are the changes needed?
Fix bug

### Does this PR introduce _any_ user-facing change?
No

### Was this patch authored or co-authored using generative AI tooling?
No

### CODE REVIEW

**Comment by AngersZhuuuu** [comment]
ping @mengxr @HyukjinKwon

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Actually @AngersZhuuuu can we add a test?

**Comment by HyukjinKwon** [comment]
If `spark.sql.timestampType` is set to `TIMESTAMP_NTZ`, and nested Row contains, `datetime` instance, then it infers as `TimestampNTZType` after this change. Before this change, `TimestampType`?

**Comment by AngersZhuuuu** [comment]
> If `spark.sql.timestampType` is set to `TIMESTAMP_NTZ`, and nested Row contains, `datetime` instance, then it infers as `TimestampNTZType` after this change. Before this change, `TimestampType`?

Yea, doing this

**Pull request closed without merging**
