### PR TITLE
[SPARK-40732][SQL][TESTS] Make `(SQL|ThriftServer)QueryTestSuite` pass except Pandas UDF tests in Java 21

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to make `SQLQueryTestSuite` and `ThriftServerQueryTestSuite` pass except Pandas UDF tests in Java 21.

### Why are the changes needed?

Two Java bug fixes changed the behavior and we need a new test output for those test cases.
- JDK-4511638 changes 'toString' result of Float/Double
- JDK-8282081 changes DataTimeFormatter 'F' symbol

In addition, `Apache Arrow` doesn't support Java 21 until now. So, I excluded it with TODO JIRA, SPARK-44097 in Java 21 environment.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the CIs and do manual test on Java 21.

```
$ java -version
openjdk version "21-ea" 2023-09-19
OpenJDK Runtime Environment (build 21-ea+27-2343)
OpenJDK 64-Bit Server VM (build 21-ea+27-2343, mixed mode, sharing)
```

```
$ build/sbt "sql/testOnly *.SQLQueryTestSuite"
...
[info] Run completed in 8 minutes, 41 seconds.
[info] Total number of tests run: 560
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 560, failed 0, canceled 0, ignored 59, pending 0
[info] All tests passed.
[success] Total time: 683 s (11:23), completed Jun 19, 2023, 1:24:34 AM
```

```
$ build/sbt "hive-thriftserver/testOnly *.ThriftServerQueryTestSuite" -Phive-thriftserver
...
[info] Run completed in 6 minutes, 14 seconds.
[info] Total number of tests run: 211
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 211, failed 0, canceled 0, ignored 19, pending 0
[info] All tests passed.
[success] Total time: 396 s (06:36), completed Jun 19, 2023, 1:43:44 AM
```

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
cc @LuciferYang

**Comment by LuciferYang** [comment]
Will we always keep the semantic differences caused by JDK-8282081? Or will we unify it in Spark 4.0(due to this will be a break change)?

**Comment by dongjoon-hyun** [comment]
The different is only on Java 21 LTS in Apache Spark perspective.
Although we can document both Java11/17 and Java 21 separately, it's difficult for us to change Spark's behavior on Java 11 and Java 17 .

**Comment by dongjoon-hyun** [comment]
Even in Java 21 environment, I guess we may need to introduce a legacy config if we want to mitigate some.

**Review by LuciferYang — APPROVED** [review]
The current fix way is fine to me

**Comment by LuciferYang** [comment]
> Even in Java 21 environment, I guess we may need to introduce a legacy config if we want to mitigate some.

I will think about this. I don't have a mature solution now since it didn't need to be fixed when test with Java 19

**Comment by dongjoon-hyun** [comment]
Thank you, @LuciferYang . Let's find a smoother way for all of this kind issues. We may find more cases .

**Review by MaxGekk — COMMENTED** [review]
@dongjoon-hyun The golden files with the `.java21` extension become outdated. Should we keep them updated somehow and keep as is?

**Comment by LuciferYang** [comment]
> The golden files with the .java21 extension become outdated.

Hmm...why is it outdated? Because of the release of Java 22 and Java 23?

**Comment by dongjoon-hyun** [comment]
To @MaxGekk , Today's Java 21 run seems to pass except Docker integration test failures. Do you mean that?
- https://github.com/apache/spark/actions/runs/11320757169

**Comment by dongjoon-hyun** [comment]
For the question about Java LTS, we can support Java 25 LTS from September 2025. Java 22 ~ 24 are not officially supported in the community because there are non-LTS versions.

**Pull request closed without merging**
