### PR TITLE
[SPARK-23163][DOC][PYTHON] Sync ML Python API with Scala

### PR DESCRIPTION
**Pull request by BryanCutler**
## What changes were proposed in this pull request?

This syncs the ML Python API with Scala for differences found after the 2.3 QA audit.

## How was this patch tested?

NA

### CODE REVIEW

**Comment by BryanCutler** [comment]
@holdenk @MLnick , just found some minor doc differences between python and scala during the audit for 2.3

**Review by MLnick — APPROVED** [review]
LGTM - not sure if we will merge this into `branch-2.3` as RC2 has been cut. Let's wait a bit and see.

**Review by felixcheung — APPROVED** [review]
LGTM.
I guess they are not blockers, but we should probably merge to branch-2.3?

**Comment by holdenk** [comment]
I'd say branch-2.3 since we want the fix in 2.3.1 even if it isn't in 2.3.0.

**Comment by felixcheung** [comment]
merged to master/2.3

**Comment by BryanCutler** [comment]
Thanks @felixcheung and others for reviewing!

**Pull request closed without merging**
