### PR TITLE
[MINOR] Fix newly added java-lint errors

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
## What changes were proposed in this pull request?

This PR fixes some newly added java-lint errors(unused-imports, line-lengsth).
## How was this patch tested?

Pass the Jenkins tests.

### CODE REVIEW

**Comment by JoshRosen** [comment]
I'm actually wary of this change. There's a number of times where I've found redundant returns but have chosen not to remove them because I was afraid of future code refactorings or changes accidentally making the implicit return no longer take effect. If this isn't strictly necessary, I'd prefer to not do this cleanup.

**Comment by dongjoon-hyun** [comment]
Oh, I see. I will close the JIRA. 
By the way, may I fix that minor Java lint error here with changed title?

**Comment by dongjoon-hyun** [comment]
Thank you for quick review. I closed that Jira issue a minute ago.

**Comment by dongjoon-hyun** [comment]
@JoshRosen . Now, this PR only contains removing unused imports and fixing java-lint errors.

**Comment by srowen** [comment]
Merged to master

**Comment by dongjoon-hyun** [comment]
Thank you, @srowen .

**Pull request closed without merging**
