### PR TITLE
[SPARK-6841] [SPARKR] add support for mean, median, stdev etc.

### PR DESCRIPTION
**Pull request by hqzizania**
Moving here from https://github.com/amplab-extras/SparkR-pkg/pull/241
sum() has been implemented. (https://github.com/amplab-extras/SparkR-pkg/pull/242)

Now Phase 1: mean, sd, var have been implemented, but some things still need to be improved with the suggestions in https://issues.apache.org/jira/browse/SPARK-6841

### CODE REVIEW

**Comment by shivaram** [comment]
Jenkins, ok to test

**Comment by hqzizania** [comment]
Implement the describe() as DataFrame API. We could add this to the RDD API in the future if we find a need. Thus, some functions also don't need to be implemented like "histogram", "sampleStdev", "sampleVariance" now, since these still don't exist in DataFrame API of spark.

**Comment by shivaram** [comment]
Thanks @hqzizania -- Could you add a unit test for this ?

cc @rxin

**Comment by shivaram** [comment]
Jenkins, ok to test

**Comment by shivaram** [comment]
@shaneknapp this seems to have hit the same error from maven

**Comment by shivaram** [comment]
@hqzizania we'll also need to bring this up to date with the latest master

**Comment by shaneknapp** [comment]
yep.  i'll take worker 03 offline until i can get a chance to investigate
(i'm OOO this afternoon).

Thanks for the catch!

@shaneknapp <https://github.com/shaneknapp> this seems to have hit the same
error from maven

—
Reply to this email directly or view it on GitHub
<https://github.com/apache/spark/pull/5446#issuecomment-99236952>.

**Comment by shivaram** [comment]
Jenkins, ok to test

**Comment by shivaram** [comment]
Jenkins, add to whitelist

**Comment by rxin** [comment]
Thanks. merging in master.

**Pull request closed without merging**
