### PR TITLE
[SPARK-16732][SQL] Remove unused codes in subexpressionEliminationForWholeStageCodegen

### PR DESCRIPTION
**Pull request by yucai**
## What changes were proposed in this pull request?

Some codes in subexpressionEliminationForWholeStageCodegen are never used actually.
Remove them using this PR.
## How was this patch tested?

Local unit tests.

### CODE REVIEW

**Comment by yucai** [comment]
@chenghao-intel @adrian-wang Kindly help review.

**Comment by adrian-wang** [comment]
good catch!

**Comment by rxin** [comment]
Jenkins, test this please.

**Comment by yucai** [comment]
@rxin this PR has passed tests, could you kindly take a look at? Much thanks!

**Comment by rxin** [comment]
Merging in master/2.0.

**Comment by chenghao-intel** [comment]
Ping @rxin , seems the upstream is not updated.

**Comment by JoshRosen** [comment]
Jenkins, retest this please.

**Comment by JoshRosen** [comment]
Merging to master. Thanks!

**Pull request closed without merging**
