### PR TITLE
[SPARK-4989][CORE] backport for branch-1.2 catch eventlog exception for wrong eventlog conf

### PR DESCRIPTION
**Pull request by liyezhang556520**
JIRA is [SPARK-4989](https://issues.apache.org/jira/browse/SPARK-4989)

### CODE REVIEW

**Comment by liyezhang556520** [comment]
seems the error is not related with this PR.
jenkins, retest this please

**Comment by andrewor14** [comment]
retest this please

**Comment by andrewor14** [comment]
LGTM I'll merge this after the 1.2.1 release is out of the window.

**Comment by andrewor14** [comment]
Hey @liyezhang556520 I just merged this into 1.2 would you mind closing this now that it's merged?

**Comment by liyezhang556520** [comment]
I'll close it, thanks.

**Pull request closed without merging**
