### PR TITLE
[SPARK-5846] Correctly set job description and pool for SQL jobs

### PR DESCRIPTION
**Pull request by kayousterhout**
@marmbrus am I missing something obvious here? I verified that this fixes the problem for me (on 1.2.1) on EC2, but I'm confused about how others wouldn't have noticed this?

### CODE REVIEW

**Comment by marmbrus** [comment]
test this please

**Comment by liancheng** [comment]
This LGTM. This PR also fixes [SPARK-2472] [1]. For most queries, the `sql` is lazy, so the job wasn't submitted until `collect()` or `toLocalIterator()` are called. The problem occurs when DDLs, commands, and CATS statements are executed, since they, or part of them (for CATS) are evaluated eagerly. Thanks for fixing this!

[1]: https://issues.apache.org/jira/browse/SPARK-2472

**Comment by liancheng** [comment]
Merged into master and branch-1.3.

**Comment by kayousterhout** [comment]
Thanks for merging this Cheng!

**Pull request closed without merging**
