### PR TITLE
[SPARK-49417][CONNECT][SQL] Add Shared StreamingQueryManager interface

### PR DESCRIPTION
**Pull request by hvanhovell**
### What changes were proposed in this pull request?
This PR adds a shared StreamingQueryManager interface.

### Why are the changes needed?
We are working on a shared Scala SQL interface for Classic and Connect. This change is part of this work.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Existing tests.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM (Pending CIs).
Thank you, @hvanhovell and @HyukjinKwon .

**Comment by dongjoon-hyun** [comment]
BTW, please fill the PR description, @hvanhovell .

**Comment by dongjoon-hyun** [comment]
Gentle ping, @hvanhovell .

**Comment by hvanhovell** [comment]
Merging.

**Comment by dongjoon-hyun** [comment]
Thank you, @hvanhovell .

**Pull request closed without merging**
