### PR TITLE
[SPARK-35374][SQL] Add string-to-number conversion support to JacksonParser

### PR DESCRIPTION
**Pull request by sarutak**
### What changes were proposed in this pull request?

This PR proposes to add string-to-number conversion support to `JacksonParser`.
In the current implementation, `spark.read.json` doesn't convert numbers represented as string even though types are specified by schema except for `DecimalType`.
Here is anexample.

```
$ cat test.json
{ "value": "foo" }                                                                                                                                
{ "value": "100" }                                                                                                                                
{ "value": "257" }                                                                                                                                
{ "value": "32768" }                                                                                                                              
{ "value": "2147483648" }                                                                                                                         
{ "value": "2.71f" }                                                                                                                              
{ "value": "1.0E100" }  

$ bin/spark-shell
import org.apache.spark.sql.types._
val df = spark.read.
  schema(StructType(StructField("value", DoubleType)::Nil)).json("test.json")
df.show
+-----+
|value|
+-----+
| null|
| null|
| null|
| null|
| null|
| null|
| null|
+-----+
```
### Why are the changes needed?

Sometimes, numbers are represented as string in JSON texts so it's helpful to convert them on load if types are specified by schema.

### Does this PR introduce _any_ user-facing change?

Yes. numbers represented as string is no longer null if users explicitly specify types.

### How was this patch tested?

New test.

### CODE REVIEW

**Comment by sarutak** [comment]
cc: @MaxGekk

**Comment by MaxGekk** [comment]
cc @HyukjinKwon

**Comment by HyukjinKwon** [comment]
Just to double check, are these:

```
{ "value": "foo" }                                                                                                                                
{ "value": "100" }                                                                                                                                
{ "value": "257" }                                                                                                                                
{ "value": "32768" }                                                                                                                              
{ "value": "2147483648" }                                                                                                                         
{ "value": "2.71f" }                                                                                                                              
{ "value": "1.0E100" }  
```

parts of JSON standard for numbers? or are these the output from Spark JSON?

**Comment by sarutak** [comment]
> parts of JSON standard for numbers? or are these the output from Spark JSON?

It's neither JSON standard for numbers nor the output From Spark JSON.
It's not often but such JSON texts can be generated by a system and exchanged with Spark.
One possible case would be that a JSON text is generated from [proto3](https://developers.google.com/protocol-buffers/docs/proto3#json).
proto3 allows its representation to map a JSON representation, and 64-bit integers will be represented as string.

Another possible case is a JSON text originates from a Web service.
Due to 64-bit integers are not ensured to be represented safely in JavaScript, some Web services consider it and return 64-bit integers as string values.

In such cases, 64-bit integers represented as string should be interpreted as `LongType` rather than `DecimalType` when they are loaded.

I have no idea whether numbers except for 64-bit integers can be represented as string but I implemented for them for consistency.

**Pull request closed without merging**
