### PR TITLE
[SPARK-4988][SQL] Fix: 'Create table ..as select ..from..order by .. limit 10' report error when one col is a Decimal

### PR DESCRIPTION
**Pull request by guowei2**

### CODE REVIEW

**Comment by marmbrus** [comment]
I'm also still confused by this solution.  The contract should be as follows:  internally we use catalyst mutable decimal type.  thus, the UDF code should only ever see that type.  When we pass back to the user we should expose the correct type of BigDecimal (but we might be consolidating this so we only ever return the Java BigDecimal type).

/cc @rxin

**Comment by rxin** [comment]
@guowei2 does this problem still exist with the latest master branch?

**Comment by guowei2** [comment]
@rxin  yeah, still exist

**Comment by marmbrus** [comment]
While I would like to fix this issue, the current solution is only masking the problem.  As I said before, `java.math.BigDecimal` should never exist during execution.  Instead of handling this in the hive udf code we should find the place where we are failing to do the conversion on the way in.

Until then, I suggest we close this issue.  If you have a test case that causes the problem from SQL it would be great to add it to the JIRA.

**Comment by guowei2** [comment]
I agree with you. Close it.

**Pull request closed without merging**
