### PR TITLE
[BUILD] Close stale PRs

### PR DESCRIPTION
**Pull request by HyukjinKwon**
Closes #13794
Closes #18474
Closes #18897
Closes #18978
Closes #19152
Closes #19238
Closes #19295
Closes #19334
Closes #19335
Closes #19347
Closes #19236
Closes #19244
Closes #19300
Closes #19315
Closes #19356
Closes #15009
Closes #18253

### CODE REVIEW

**Comment by srowen** [comment]
I'd add 

https://github.com/apache/spark/pull/19236
https://github.com/apache/spark/pull/19244
https://github.com/apache/spark/pull/19300
https://github.com/apache/spark/pull/19315

**Comment by HyukjinKwon** [comment]
Added.

**Comment by vanzin** [comment]
Add:
#15009
#18253

**Comment by HyukjinKwon** [comment]
Added.

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
