### PR TITLE
Implement `skipna`s of statistical functions of Series and DataFrame

### PR DESCRIPTION
**Pull request by xinrong-meng**
### What changes were proposed in this pull request?
Implement `skipna`s of statistical functions of Series and DataFrame

### Why are the changes needed?
To reach parity with pandas API.

### Does this PR introduce _any_ user-facing change?
Yes. `skipna`s of statistical functions are supported.

### How was this patch tested?
Unit tests.

### CODE REVIEW

**Comment by xinrong-databricks** [comment]
The PR is pending because Spark statistical functions ignore Nas always. That means, `skipna` is always True in our case. There doesn't seem to be an easy way to disable `skipna`s altogether.

**Comment by zhengruifeng** [comment]
@xinrong-databricks  I guess the reason is that `NA`s in pandas-on-spark side will be implicitly converted to `null`s in the `internal.spark_frame` (correct me if i am wrong) , and the statisticl functions always ignore `null`s.

If we can convert `NA`s to `Double.NaN`s instead of `null`s, then the results should be `NaN`. But I am not sure whether it is safe to use this attribute.

```
scala> val df = Seq(("1", 1.0), ("2", 2.0), ("3", 3.0), (null, Double.NaN)).toDF("a", "b").select(col("a").cast("double").as("a"), col("b"))
df: org.apache.spark.sql.DataFrame = [a: double, b: double]

scala> df.show
+----+---+
|   a|  b|
+----+---+
| 1.0|1.0|
| 2.0|2.0|
| 3.0|3.0|
|null|NaN|
+----+---+


scala> df.select(avg("a"), avg("b")).show
+------+------+
|avg(a)|avg(b)|
+------+------+
|   2.0|   NaN|
+------+------+


scala> df.select(sum("a"), sum("b")).show
+------+------+
|sum(a)|sum(b)|
+------+------+
|   6.0|   NaN|
+------+------+


scala> df.select(skewness("a"), skewness("b")).show
+-----------+-----------+
|skewness(a)|skewness(b)|
+-----------+-----------+
|        0.0|        NaN|
+-----------+-----------+


```

**Comment by xinrong-databricks** [comment]
Thanks @zhengruifeng! 

What you said makes sense and I do agree `Double.NaN` is better than `null` in this case.

I wanted to add that with `Double.NaN`, adjustments(casting, specific statistical functions, etc.) are still needed in order to reach parity with pandas. An example is as below:

```py
>> pdf = pd.DataFrame({'a':[1.0, 2.0, 3.0, None], 'b':[1.0, 2.0, 3.0, np.nan]})
>>> pdf
     a    b
0  1.0  1.0
1  2.0  2.0
2  3.0  3.0
3  NaN  NaN

>>> pdf.sum()
a    6.0
b    6.0
dtype: float64
```

I haven't calculated the exact efforts needed. I do think this is an interesting topic that needs further discussion.

**Comment by xinrong-databricks** [comment]
The statistical functions behavior difference (from pandas) can be traced back to our design principles in the early stage: we follow SQL standards which ignore NAs.

We'd better call out the principle in docstrings per related API.

FYI @zhengruifeng

**Comment by xinrong-databricks** [comment]
We should call out the principle in docstrings per related API as a follow-up.

**Comment by zhengruifeng** [comment]
@xinrong-databricks  I think we should keep in line with the pandas on dealing with NAs, and end users do not need to know the internal details about converting NAs to nulls.

For this PR, I think we may impl `skipna` in this way:

1, when `skipna=True`, we keep current behavior which converts pandas' NA (None, np.nan) to `null` in SQL;

2, when `skipna=False`, we add an extra conversion which convert `null` to `Double.NaN`;

3, if there are some statistics which can not support `skipna` in above way, we may need to add some dedicated functions in the SQL side.

also cc @HyukjinKwon @itholic  @ueshin

**Comment by xinrong-databricks** [comment]
Thank you @zhengruifeng ! Your suggestion makes sense. I am working on standardizing statistical functions. Hopefully we may fill the gaps and reach parity with pandas soon!

**Comment by xinrong-databricks** [comment]
Closed the PR since it is outdated.

**Pull request closed without merging**
