### PR TITLE
[MINOR] Fix typos in ML scaladocs

### PR DESCRIPTION
**Pull request by BryanCutler**
## What changes were proposed in this pull request?

Fixed some typos found in ML scaladocs

## How was this patch tested?

NA

### CODE REVIEW

**Comment by BryanCutler** [comment]
ping @holdenk @MLnick

**Review by srowen — APPROVED** [review]
Normally I'd say, please look for more typos while you're at it. But I spell-checked the module again and didn't see any obvious ones. Looks fine.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by BryanCutler** [comment]
Thanks @srowen, I honestly tried to look for more and was surprised this was all I could find!

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
