### PR TITLE
[CORE][BUILD] Change to using `build-helper-maven-plugin` to manage the code for `opentelemetry`

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
The main changes in this pr are as follows:

1. In `core/pom.xml`, the `build-helper-maven-plugin` configuration has been added for the `opentelemetry` profile to ensure that when the profile is activated with `-Popentelemetry`, the `opentelemetry/src/main/scala` directory under the `core` module is treated as an additional source path, and `opentelemetry/src/test/scala` is treated as an additional test code path.

```xml
<build>
    <plugins>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>build-helper-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>add-opentelemetry-source</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>add-source</goal>
            </goals>
            <configuration>
              <sources>
                <source>opentelemetry/src/main/scala</source>
              </sources>
            </configuration>
          </execution>
          <execution>
            <id>add-opentelemetry-test-sources</id>
            <phase>generate-test-sources</phase>
            <goals>
              <goal>add-test-source</goal>
            </goals>
            <configuration>
              <sources>
                <source>opentelemetry/src/test/scala</source>
              </sources>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
```

2. Removed the management configuration for `opentelemetry`-related source/test code in `https://github.com/apache/spark/pull/47763`.

Since Spark uses the `sbt-pom-reader` plugin in its sbt configuration, the behavior of the `build-helper-maven-plugin` will also propagate to the sbt build process. Therefore, no additional configuration is required in `SparkBuild.scala` after this pr.

### Why are the changes needed?
The previous configuration way was not very friendly to IntelliJ developers: when debugging code in IntelliJ, regardless of whether they were needed or not, the `opentelemetry` profile had to be activated; otherwise compilation errors would occur when running tests that depended on the core module's source code, for example `DataSourceV2SQLSuiteV2Filter `:

image

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
1. Pass GitHub Actions

- https://github.com/LuciferYang/spark/actions/runs/10697633945/job/29663999051

image

It can be seen that the test cases `OpenTelemetryPushReporterSuite ` and `OpenTelemetryPushSinkSuite` have been successfully executed.

2. Manual Testing Using sbt

- Run `build/sbt "core/testOnly *OpenTelemetryPushReporterSuite *OpenTelemetryPushSinkSuite"`, and without `-Popentelemetry`, no tests will be executed:

```
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] No tests to run for core / Test / testOnly
```

- Run `build/sbt "core/testOnly *OpenTelemetryPushReporterSuite *OpenTelemetryPushSinkSuite" -Popentelemetry`, and with `-Popentelemetry`, `OpenTelemetryPushReporterSuite` and `OpenTelemetryPushSinkSuite` will pass the tests:

```
[info] OpenTelemetryPushReporterSuite:
[info] - Normalize metric name key (10 milliseconds)
[info] - OpenTelemetry actions when one codahale gauge is added (5 milliseconds)
[info] - OpenTelemetry actions when one codahale counter is added (2 milliseconds)
[info] - OpenTelemetry actions when one codahale histogram is added (4 milliseconds)
[info] - OpenTelemetry actions when one codahale meter is added (1 millisecond)
[info] - OpenTelemetry actions when one codahale timer is added (1 millisecond)
[info] OpenTelemetryPushSinkSuite:
[info] - fetch properties map (2 milliseconds)
[info] - OpenTelemetry sink with one counter added (3 milliseconds)
[info] Run completed in 713 milliseconds.
[info] Total number of tests run: 8
[info] Suites: completed 2, aborted 0
[info] Tests: succeeded 8, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
```

3. Manual Testing Using Maven

- Run `build/mvn clean test -pl core -am -Dtest=none -DwildcardSuites=org.apache.spark.metrics.sink.opentelemetry.OpenTelemetryPushReporterSuite,org.apache.spark.metrics.sink.opentelemetry.OpenTelemetryPushSinkSuite`, and without `-Popentelemetry`, no tests will be executed:

```
Discovery starting.
Discovery completed in 764 milliseconds.
Run starting. Expected test count is: 0
DiscoverySuite:
DiscoverySuite:
Run completed in 779 milliseconds.
Total number of tests run: 0
Suites: completed 2, aborted 0
Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
No tests were executed.
```

- Run `build/mvn clean test -pl core -am -Dtest=none -DwildcardSuites=org.apache.spark.metrics.sink.opentelemetry.OpenTelemetryPushReporterSuite,org.apache.spark.metrics.sink.opentelemetry.OpenTelemetryPushSinkSuite -Popentelemetry`, and with `-Popentelemetry`, `OpenTelemetryPushReporterSuite` and `OpenTelemetryPushSinkSuite` will pass the tests:

```
Discovery starting.
Discovery completed in 1 second, 33 milliseconds.
Run starting. Expected test count is: 8
OpenTelemetryPushReporterSuite:
- Normalize metric name key
- OpenTelemetry actions when one codahale gauge is added
- OpenTelemetry actions when one codahale counter is added
- OpenTelemetry actions when one codahale histogram is added
- OpenTelemetry actions when one codahale meter is added
- OpenTelemetry actions when one codahale timer is added
OpenTelemetryPushSinkSuite:
- fetch properties map
- OpenTelemetry sink with one counter added
Run completed in 1 second, 142 milliseconds.
Total number of tests run: 8
Suites: completed 4, aborted 0
Tests: succeeded 8, failed 0, canceled 0, ignored 0, pending 0
All tests passed.
```

4. Testing in IntelliJ (both imported as a Maven project and as an sbt project):
- By default, do not activate `opentelemetry`, and confirm that `opentelemetry`-related code is not recognized as source/test code, and does not affect the compilation and testing of other code.
- Manually activate `opentelemetry`, and confirm that `opentelemetry`-related code is recognized as source/test code, and can be compiled and tested normally.

### Was this patch authored or co-authored using generative AI tooling?
No

### CODE REVIEW

**Comment by LuciferYang** [comment]
Test first.

Before updating the PR description, I will take some time to conduct additional verification (by this Sunday).

**Comment by dongjoon-hyun** [comment]
cc @TQJADE , FYI.

**Comment by LuciferYang** [comment]
image

It can be seen that the test cases `OpenTelemetryPushReporterSuite ` and `OpenTelemetryPushSinkSuite` have been successfully executed.

**Comment by LuciferYang** [comment]
cc @dongjoon-hyun 

The Pr description has been updated, and a number of manual tests have been conducted, all of which align with expectations. If this is acceptable, a similar refactoring could also be applied to the code management of the `volcano` profile in the future.

**Review by dongjoon-hyun — COMMENTED** [review]
Thank you, @LuciferYang . Please proceed toward `volcano` as an independent PR. 

Given the current discussion status, `opentelemetry` code might be reverted from Apache Spark code.

**Comment by LuciferYang** [comment]
> Thank you, @LuciferYang . Please proceed toward `volcano` as an independent PR.
> 
> Given the current discussion status, `opentelemetry` code might be reverted from Apache Spark code.

Got ~

**Comment by dongjoon-hyun** [comment]
BTW, I love this improvement because `volcano` module itself was a headache for me. Thank you really for looking at this part.

**Comment by LuciferYang** [comment]
close this one due to SPARK-49241 has been reverted

**Pull request closed without merging**
