### PR TITLE
[SPARK-50278][BUILD] Upgrade `netty-tcnative` to 2.0.69.Final

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to upgrade `netty-tcnative` from `2.0.66.Final` to `2.0.69.Final`.

### Why are the changes needed?
`2.0.66.Final` VS `2.0.69.Final`
https://github.com/netty/netty-tcnative/compare/netty-tcnative-parent-2.0.66.Final...netty-tcnative-parent-2.0.69.Final

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
- Pass GA.
- Manually check can be found in the comments below.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by panbingkun** [comment]
```shell
./build/sbt -Phadoop-3 -Pkubernetes -Pkinesis-asl -Phive-thriftserver -Pdocker-integration-tests -Pyarn -Phadoop-cloud -Pspark-ganglia-lgpl -Phive -Pjvm-profiler clean package
```

```shell
[info] Note: Some input files use or override a deprecated API.
[info] Note: Recompile with -Xlint:deprecation for details.
[warn] multiple main classes detected: run 'show discoveredMainClasses' to see the list
[success] Total time: 265 s (04:25), completed Nov 10, 2024, 5:54:02 PM
```

```shell
(base) ➜  spark-community git:(SPARK-50278) ✗ ls -1 assembly/target/scala-2.13/jars/netty-*1*
assembly/target/scala-2.13/jars/netty-all-4.1.114.Final.jar
assembly/target/scala-2.13/jars/netty-buffer-4.1.114.Final.jar
assembly/target/scala-2.13/jars/netty-codec-4.1.114.Final.jar
assembly/target/scala-2.13/jars/netty-codec-http-4.1.114.Final.jar
assembly/target/scala-2.13/jars/netty-codec-http2-4.1.114.Final.jar
assembly/target/scala-2.13/jars/netty-codec-socks-4.1.114.Final.jar
assembly/target/scala-2.13/jars/netty-common-4.1.114.Final.jar
assembly/target/scala-2.13/jars/netty-handler-4.1.114.Final.jar
assembly/target/scala-2.13/jars/netty-handler-proxy-4.1.114.Final.jar
assembly/target/scala-2.13/jars/netty-resolver-4.1.114.Final.jar
assembly/target/scala-2.13/jars/netty-transport-4.1.114.Final.jar
assembly/target/scala-2.13/jars/netty-transport-classes-epoll-4.1.114.Final.jar
assembly/target/scala-2.13/jars/netty-transport-classes-kqueue-4.1.114.Final.jar
assembly/target/scala-2.13/jars/netty-transport-native-epoll-4.1.114.Final-linux-aarch_64.jar
assembly/target/scala-2.13/jars/netty-transport-native-epoll-4.1.114.Final-linux-riscv64.jar
assembly/target/scala-2.13/jars/netty-transport-native-epoll-4.1.114.Final-linux-x86_64.jar
assembly/target/scala-2.13/jars/netty-transport-native-kqueue-4.1.114.Final-osx-aarch_64.jar
assembly/target/scala-2.13/jars/netty-transport-native-kqueue-4.1.114.Final-osx-x86_64.jar
assembly/target/scala-2.13/jars/netty-transport-native-unix-common-4.1.114.Final.jar
(base) ➜  spark-community git:(SPARK-50278) ✗ ls -1 assembly/target/scala-2.13/jars/netty-*2*
assembly/target/scala-2.13/jars/netty-codec-http2-4.1.114.Final.jar
assembly/target/scala-2.13/jars/netty-tcnative-boringssl-static-2.0.69.Final-linux-aarch_64.jar
assembly/target/scala-2.13/jars/netty-tcnative-boringssl-static-2.0.69.Final-linux-x86_64.jar
assembly/target/scala-2.13/jars/netty-tcnative-boringssl-static-2.0.69.Final-osx-aarch_64.jar
assembly/target/scala-2.13/jars/netty-tcnative-boringssl-static-2.0.69.Final-osx-x86_64.jar
assembly/target/scala-2.13/jars/netty-tcnative-boringssl-static-2.0.69.Final-windows-x86_64.jar
assembly/target/scala-2.13/jars/netty-tcnative-classes-2.0.69.Final.jar
```

```shell
(pyspark) ➜  spark-community git:(SPARK-50278) ✗ ./python/run-tests --python-executables=python3 --testnames "pyspark.sql.tests.connect.test_connect_collection"
Running PySpark tests. Output is in /Users/panbingkun/Developer/spark/spark-community/python/unit-tests.log
Will test against the following Python executables: ['python3']
Will test the following Python tests: ['pyspark.sql.tests.connect.test_connect_collection']
python3 python_implementation is CPython
python3 version is: Python 3.9.19
Starting test(python3): pyspark.sql.tests.connect.test_connect_collection (temp output: /Users/panbingkun/Developer/spark/spark-community/python/target/676a4a7f-e673-4c4c-8421-5415c534ab0b/python3__pyspark.sql.tests.connect.test_connect_collection__8crh__lb.log)
Finished test(python3): pyspark.sql.tests.connect.test_connect_collection (15s)
Tests passed in 15 seconds
```

```shell
(pyspark) ➜  spark-community git:(SPARK-50278) ✗ ./bin/pyspark --remote "sc://127.0.0.1:8888"
Python 3.9.19 (main, Mar 21 2024, 12:07:41)
[Clang 14.0.6 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /__ / .__/\_,_/_/ /_/\_\   version 4.0.0.dev0
      /_/

Using Python version 3.9.19 (main, Mar 21 2024 12:07:41)
Client connected to the Spark Connect server at 127.0.0.1:8888
SparkSession available as 'spark'.
>>> spark.range(10).collect()
[Row(id=0), Row(id=1), Row(id=2), Row(id=3), Row(id=4), Row(id=5), Row(id=6), Row(id=7), Row(id=8), Row(id=9)]
```

**Comment by panbingkun** [comment]
cc @LuciferYang @dongjoon-hyun

**Review by LuciferYang — APPROVED** [review]

**Comment by LuciferYang** [comment]
also cc @HyukjinKwon

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @panbingkun and @LuciferYang .

Merged to master.

**Pull request closed without merging**
