### PR TITLE
[SPARK-42379][SS] Use FileSystem.exists in FileSystemBasedCheckpointFileManager.exists

### PR DESCRIPTION
**Pull request by HeartSaVioR**
### What changes were proposed in this pull request?

This PR proposes to use FileSystem.exists in FileSystemBasedCheckpointFileManager.exists, which is consistent with other methods in FileSystemBasedCheckpointFileManager.

This PR also removes the test case QueryExecutionErrorsSuite.FAILED_RENAME_PATH: rename when destination path already exists because the test relies on incorrect custom file system instance with non-symmetric implementation between `FileSystemBasedCheckpointFileManager.exists` vs `FileSystem.exists`.
(See detailed explanation from https://github.com/apache/spark/pull/39936#issuecomment-1422101967)

### Why are the changes needed?

Other methods in FileSystemBasedCheckpointFileManager already uses FileSystem.exists for all cases checking existence of the path.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
cc. @cloud-fan @viirya

**Review by HyukjinKwon — APPROVED** [review]

**Review by cloud-fan — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
Although it's a small change, could you file a JIRA for trace-ability, please, @HeartSaVioR ?

**Comment by HeartSaVioR** [comment]
Done.

**Review by viirya — APPROVED** [review]

**Review by dongjoon-hyun — COMMENTED** [review]
Could you check the UT failure?

Screenshot 2023-02-07 at 9 38 25 PM

```
  test("FAILED_RENAME_PATH: rename when destination path already exists") {
    withTempPath { p =>
      withSQLConf(
        "spark.sql.streaming.checkpointFileManagerClass" ->
          classOf[FileSystemBasedCheckpointFileManager].getName,
```

**Comment by HeartSaVioR** [comment]
I'd argue that the test case itself is incorrect. It's heavily bound to the internal implementation - it relies on custom filesystem instance which returns true for all exists() calls, but it does not apply to the getFileStatus() hence it will end up with "file does not exist".

That said, test only passes if filesystem behaves incorrectly. If we change the custom filesystem instance to also provide dummy status for all getFileStatus() calls, the test case will fail.

I don't know how we can test the exception in E2E query. As the exception class denotes, it mainly occurs from concurrent writes for same offset/commit log file. We should have created offset log file concurrently, between "determining start microbatch" and "writing offset log after planning", which is super hard from outside of the query.

I'd suggest just remove the test. WDYT?

**Comment by HyukjinKwon** [comment]
I am fine w/ removing it.

**Comment by cloud-fan** [comment]
+1 to remove it.

**Comment by HeartSaVioR** [comment]
Test removed. Will merge once the build passes.

**Review by LuciferYang — APPROVED** [review]
+1, LGTM

**Comment by viirya** [comment]
Sounds reasonable to remove it.

**Review by viirya — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1 with the final commit.

**Comment by HeartSaVioR** [comment]
Thanks, merging to master.

**Pull request closed without merging**
