### PR TITLE
[SPARK-24628][DOC]Typos of the example code in docs/mllib-data-types.md

### PR DESCRIPTION
**Pull request by huangweizhe123**
## What changes were proposed in this pull request?

The example wants to create a dense matrix ((1.0, 2.0), (3.0, 4.0), (5.0, 6.0)), but the list is given as [1, 2, 3, 4, 5, 6]. Now it is changed as [1, 3, 5, 2, 4, 6].

And the example wants to create an RDD of coordinate entries like:
entries = sc.parallelize([(0, 0, 1.2), (1, 0, 2.1), (2, 1, 3.7)]).
However, it is done with the MatrixEntry class like:
entries = sc.parallelize([MatrixEntry(0, 0, 1.2), MatrixEntry(1, 0, 2.1), MatrixEntry(6, 1, 3.7)]),
where the third MatrixEntry has a different row index.
Now it is changed as MatrixEntry(2, 1, 3.7).

## How was this patch tested?

This is trivial enough that it should not affect tests.

Author: Weizhe Huang <huangweizhe@bbdservice.com>

Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Comment by huangweizhe123** [comment]
ok to test

**Comment by huangweizhe123** [comment]
Jenkins, add to whitelist

**Comment by huangweizhe123** [comment]
cc @gatorsmile @marmbrus  It seems that no one is gonna test this patch. Do I need to ask someone to add Spark QA as a participant?

**Review by srowen — APPROVED** [review]

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
