### PR TITLE
[SPARK-17731][SQL][STREAMING][FOLLOWUP] Refactored StreamingQueryListener APIs for branch-2.0

### PR DESCRIPTION
**Pull request by tdas**
This is the branch-2.0 PR of #15530 to make the APIs consistent with the master. Since these APIs are experimental and not direct user facing (StreamingQueryListener is advanced Structured Streaming APIs), its okay to change them in branch-2.0.
## What changes were proposed in this pull request?

As per @rxin request, here are further API changes
- Changed `Stream(Started/Progress/Terminated)` events to `Stream*Event`
- Changed the fields in `StreamingQueryListener.on***` from `query*` to `event`
## How was this patch tested?

Existing unit tests.

### CODE REVIEW

**Comment by rxin** [comment]
LGTM

**Comment by tdas** [comment]
I cancelled previous jenkins tests, hence the failures.

**Comment by tdas** [comment]
I am merging this.

**Comment by zsxwing** [comment]
@tdas could you close this PR? Thanks!

**Pull request closed without merging**
