### PR TITLE
[SPARK-34987][SQL] AQE improve: change shuffle hash join to sort merg…

### PR DESCRIPTION
**Pull request by exmy**
### What changes were proposed in this pull request?
Change shuffle hash join to sort merge join when skewed shuffle hash join exists.

### Why are the changes needed?
AQE currently can only optimize skewed join for sort merge join, it will be better if we can change shuffle hash join to sort merge join when skewed shuffle hash join exists.

### Does this PR introduce _any_ user-facing change?
no

### How was this patch tested?
Adding new test.

### CODE REVIEW

**Comment by exmy** [comment]
cc @cloud-fan @JkSelf @maryannxue please take a look, thanks.

**Comment by exmy** [comment]
@cloud-fan  could you help take a look and provide some suggestions? thanks.

**Comment by cloud-fan** [comment]
shuffle hash join is disabled by default. If it's explicitly enabled, I think it's better to keep it and optimize it with the same algorithm optimizing sort merge join.

**Comment by zhengruifeng** [comment]
https://github.com/apache/spark/pull/32328, OptimizeSkewedJoin now support ShuffledHashJoinExec

**Pull request closed without merging**
