### PR TITLE
SPARK-3580: New public method for RDD's to have consistent way of obtain...

### PR DESCRIPTION
**Pull request by patmcdonough**
...ing the number of RDD partitions across languages.

### CODE REVIEW

**Comment by andrewor14** [comment]
The changes here look fine. @pwendell @markhamstra any additional thoughts? This PR hasn't had much activity for a while.

**Comment by srowen** [comment]
FWIW I think:

- needs a rebase
- scaladoc should be consistent with others in `RDD.scala` -- no shell example
- `JavaRDD` needs this even more since I think you have to call `javaRDD.rdd().partitions().length` right now
- Shouldn't it be `partitions.length` since it's an array? `size` works but requires an implicit conversion I think. While we're bothering, might as well do the direct efficient thing

The one bummer here is that there are 20-30 usages of `partitions.size` in the code already. It's not hard to make those use the method. The usual worry about annoying merge conflicts rears its head though. Still it feels worth doing right if at all?

**Comment by andrewor14** [comment]
Yeah I think it's still worth doing just to enforce consistent APIs across python and Scala. Merge conflicts may be a little annoying but they shouldn't stop us from bringing the Scala API to parity. Also I think it's fine to continue to use the old way internally since the motivation here is simply to expose it as a public API. I agree that we should also do the same for Java while we're at it.

**Comment by srowen** [comment]
@patmcdonough are you in a position to follow up on the comments above? I'm wondering if this is alive or not or whether it should be closed.

**Comment by patmcdonough** [comment]
Thanks for following up on this @srowen - I didn't even realize it's still open.

I'll close this out in favor of somebody issuing a new patch as I'm not in a position to address the comments right now (a lot can happen in 6 months I guess).  Please shout at me and suggest otherwise if necessary.

CC: @andrewor14 @pwendell

**Pull request closed without merging**
