### PR TITLE
[SPARK-14299][Examples] Remove duplications for scala.examples.ml

### PR DESCRIPTION
**Pull request by yinxusen**
## What changes were proposed in this pull request?

https://issues.apache.org/jira/browse/SPARK-14299

Delete and merge duplications in scala/examples/ml.
- DecisionTreeExample.scala --> DecisionTreeRegressionExample, DecisionTreeClassificationExample
- TrainValidationSplitExample.scala --> ModelSelectionViaTrainValidationSplitExample
- DeveloperApiExample.scala --> I delete it for now because it's only about how to create your classifier, etc, which can be learned easily from other examples and ml codes.
- SimpleParamsExample.scala --> merge with LogisticRegressionSummaryExample.scala
- SimpleTextClassificationPipeline.scala --> ModelSelectionViaCrossValidationExample
- DataFrameExample.scala --> merge with LogisticRegressionSummaryExample.scala

The following examples are intent to reserve (with command line supports):
- examples/src/main/scala/org/apache/spark/examples/ml/DecisionTreeExample.scala
- examples/src/main/scala/org/apache/spark/examples/ml/GBTExample.scala
- examples/src/main/scala/org/apache/spark/examples/ml/LinearRegressionExample.scala
- examples/src/main/scala/org/apache/spark/examples/ml/LogisticRegressionExample.scala
- examples/src/main/scala/org/apache/spark/examples/ml/RandomForestExample.scala
## How was this patch tested?

Test with `SKIP_API=1 jekyll serve` manually to make sure that works well.

### CODE REVIEW

**Comment by yinxusen** [comment]
test it please

**Comment by yinxusen** [comment]
test it please

**Comment by mengxr** [comment]
@yinxusen Some example code can be used as command-line apps, e.g., `LinearRegressionExample`. I think we should keep them since people might want to use them as templates to build their own. Could you make a pass and exclude them from this PR? Later we can call them `App` instead of `Example`.

**Comment by yinxusen** [comment]
Sure thing.

**Comment by yinxusen** [comment]
test it please

**Comment by yinxusen** [comment]
@mengxr Excluded those examples.

**Pull request closed without merging**
