### PR TITLE
[SPARK-14265] Get attempId of stage and transfer it to web

### PR DESCRIPTION
**Pull request by KaiXinXiaoLei**
## What changes were proposed in this pull request?

if a stage is failed and attempt to start again, DAG visualization does not render correctly for this stage. Because in spark-dag-viz.js, the link of stage is ("#stage-" + stageId + "-" + attemptId), and  the value of attemptId is 0 . So I think the  attemptId  of stage sholike this: stageopening spark web, the attemptId of stage should be transfer to web, and make the link of  ("#stage-" + stageId + "-" + attemptId) is correct.
## How was this patch tested?

Please test as fellow. Run spark app, and kill executor to make stage reSubmitted. Then check DAG visualization in web.

### CODE REVIEW

**Comment by holdenk** [comment]
My guess is that the PySpark test failure was unrelated, jenkins retest this please.

**Comment by holdenk** [comment]
cc @ajbozarth who has been working on a number of Spark UI changes lately.

**Comment by KaiXinXiaoLei** [comment]
@ajbozarth help me check, thanks

**Comment by ajbozarth** [comment]
I'll take a look this afternoon

**Comment by ajbozarth** [comment]
I'll have to take a look tomorrow, I've been blocked by local env issues all afternoon

**Comment by ajbozarth** [comment]
I can't seem to recreate the problem you're fixing so my input is limited. Just looking over your code though I don't see any glaring issues. Sorry I can't be more help.

**Comment by ajbozarth** [comment]
@KaiXinXiaoLei this pr has been stale for a long time, is this still an issue you wan to fix? If not could you close it?

**Pull request closed without merging**
