### PR TITLE
[SPARK-27016][SQL][BUILD][FOLLOW-UP] Treat all antlr warnings as errors while generating the parser.

### PR DESCRIPTION
**Pull request by dilipbiswal**
## What changes were proposed in this pull request?
Use the sbt maven plugin option`antlr4TreatWarningsAsErrors` to make sure the warnings are treated as errors while generating the parser. In the absence of it, we may inadvertently introduce problems while making grammar changes. Please refer to PR-23897 to know more about the context. We made a change in [pr-23925](https://github.com/apache/spark/pull/23925) which handled only the maven build. 

In this PR, we handle the sbt build. I had submitted [PR-23](https://github.com/ihji/sbt-antlr4/pull/23) to enhance the sbt-antlr plugin to make is possible to pass the error on warning option. 

## How was this patch tested?
Force an warning in the grammar file to check if the build fails. Then remove the warning to verify the build succeeds.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Nice. Thank you for fixing this from the upstream, @dilipbiswal !

**Comment by dilipbiswal** [comment]
@dongjoon-hyun Thank you :-)

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. (Pending Jenkins).
The first build and second build verified this PR.

**Comment by HyukjinKwon** [comment]
+1 looks good

**Comment by dongjoon-hyun** [comment]
Thank you, @dilipbiswal and @HyukjinKwon .
Merged to master.

**Comment by dilipbiswal** [comment]
Thanks a LOT @dongjoon-hyun @HyukjinKwon

**Pull request closed without merging**
