### PR TITLE
[SPARK-20260][MLLib] String interpolation required for error message

### PR DESCRIPTION
**Pull request by vijaykramesh**
## What changes were proposed in this pull request?
This error message doesn't get properly formatted because of a missing `s`.  Currently the error looks like:

```
Caused by: java.lang.IllegalArgumentException: requirement failed: indices should be one-based and in ascending order; found current=$current, previous=$previous; line="$line"
```
(note the literal `$current` instead of the interpolated value)

Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Comment by vijaykramesh** [comment]
I'm not sure if I should open my own jira for this issue or if that is handled by the project maintainers?  Thanks!

**Comment by srowen** [comment]
Yes, that's fine though I typically encourage people to hunt for other occurrences of the same issue. I used a regex like `^[^"]*[^fs]"("")?[^"]*\$` to find `SparkHadoopUtil:352`, a couple instances in `PowerIterationCluster.scala`, `DecisionTreeModel.scala`, `MLUtils.scala`, a couple copies of `TestingUtils.scala`, `OrcQuerySuite.scala`, and maybe others. Have a look and zap at least those?

**Comment by vijaykramesh** [comment]
@srowen fixed it in some more places. it seems like everywhere else that regexp matches we actually want the $ outputted.  do you want me to squash commits as well?

**Review by srowen — APPROVED** [review]

**Comment by srowen** [comment]
Merged to master/2.1

**Pull request closed without merging**
