### PR TITLE
[SPARK-33285][CORE][SQL] Fix deprecated compilation warnings of "Auto-application to () is deprecated" in Scala 2.13

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
The purpose of this pr is to partial resolve SPARK-33285. 

`Auto-application` is dropped in Scala 3 and deprecated in 2.13.3 (https://github.com/scala/scala/pull/8833) now. So we should add the parens when accessed empty-paren method.

For example, if definition as follows:

```
Class Foo {
   def bar(): Unit = {}
}
val foo = new Foo
```

`foo.bar()` is  recommend , not `foo.bar`. So the main change of this pr is only add the parens where needed.

### Why are the changes needed?
eliminate compilation warnings in Scala 2.13

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass the Jenkins or GitHub Action

### CODE REVIEW

**Comment by LuciferYang** [comment]
cc @srowen this is the first part to fix this compilation warnings, if it's too big, I can split multiple small prs.

**Comment by srowen** [comment]
Hoo boy that is a lot of code to touch. It sounds like eventually it has to happen for Scala 3 and avoids some deprecation noise. I'm not against it though as usual there is a minor concern about making patches harder to back port from 3.1 to 3.0 because of merge conflicts.

**Review by dongjoon-hyun — COMMENTED** [review]
@LuciferYang .
After this PR, do we have a way to prevent this compilation warnings?

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
Thank you so much for this PR, @LuciferYang .
However, shall we postpone this until Scala 2.13 becomes the default Scala version in Apache Spark?

**Comment by LuciferYang** [comment]
> After this PR, do we have a way to prevent this compilation warnings?

It seems that there is no such way now.

> However, shall we postpone this until Scala 2.13 becomes the default Scala version in Apache Spark?

Fix this problem only because there are too many compilation warnings about this and it is compatible with Scala 2.12. At the same time, I agree with you.

**Comment by LuciferYang** [comment]
> After this PR, do we have a way to prevent this compilation warnings?

Let me take a look at it. Maybe we can change the alarm level of the compiler or check-style plugin

**Comment by LuciferYang** [comment]
@srowen & @dongjoon-hyun 

I found there is a very Interesting thing about `RDD#isEmpty()` method, there are some compilation warnings as follow:

```
[WARNING] [Warn] /spark/core/src/test/scala/org/apache/spark/rdd/RDDSuite.scala:74: Auto-application to `()` is deprecated. Supply the empty argument list `()` explicitly to invoke method isEmpty,
or remove the empty argument list from its definition (Java-defined methods are exempt).
In Scala 3, an unapplied method like this will be eta-expanded into a function.
```

but  we found the call method is already "isEmpty()" as follows:

https://github.com/apache/spark/blob/93ad26be01a47fb075310a26188e238d55110098/core/src/test/scala/org/apache/spark/rdd/RDDSuite.scala#L74

I am not sure Is this a bug in of Scala 2.13 compiler

**Comment by LuciferYang** [comment]
@srowen & @dongjoon-hyun 

Since this pr is marked as DRAFT, I will continue to update the changes of other modules and merge the master code.
When the work is completed and the time is right, maybe need to split it into small pr for merging

**Comment by LuciferYang** [comment]
@dongjoon-hyun It seems that except for `RDD.isEmpty` has been fixed.

**Comment by dongjoon-hyun** [comment]
Sorry, but what do you mean?
> It seems that except for RDD.isEmpty has been fixed.

**Comment by LuciferYang** [comment]
seems all case fixed except for `RDD.isEmpty` relevant case

**Comment by LuciferYang** [comment]
Spark SPARK-33775 add some Scalac config to Suppress compilation warnings, no need to fix this now, close it first

**Pull request closed without merging**
