### PR TITLE
[SPARK-30738][K8S] Use specific image version in "Launcher client dependencies" test

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR use a specific version of docker image instead of `latest`. As of today, when I run K8s integration test locally, this test case fails always.

Also, in this PR, I shows two consecutive failures with a dummy change.
- https://github.com/apache/spark/pull/27465#issuecomment-582326614
- https://github.com/apache/spark/pull/27465#issuecomment-582329114
```
- Launcher client dependencies *** FAILED ***
```

After that, I added the patch and K8s Integration test passed.
- https://github.com/apache/spark/pull/27465#issuecomment-582361696

### Why are the changes needed?

[SPARK-28465](https://github.com/apache/spark/pull/25222) switched from `v4.0.0-stable-4.0-master-centos-7-x86_64` to `latest` to catch up the API change. However, the API change seems to occur again. We had better use a specific version to prevent accidental failures.

```scala
- .withImage("ceph/daemon:v4.0.0-stable-4.0-master-centos-7-x86_64")
+ .withImage("ceph/daemon:latest")
```

### Does this PR introduce any user-facing change?

No.

### How was this patch tested?

Pass `Launcher client dependencies` test in Jenkins K8s Integration Suite.
Or, run K8s Integration test locally.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by dongjoon-hyun** [comment]
cc @vanzin

**Comment by dongjoon-hyun** [comment]
Hi, @liyinan926 .
Could you review this PR? This PR aims to recover the K8s integration test suite before 3.0.0 release.

**Comment by dongjoon-hyun** [comment]
Hi, @dbtsai .
Could you review this PR?

**Comment by dbtsai** [comment]
LGTM. Thanks.

**Comment by dongjoon-hyun** [comment]
Thank you, @dbtsai .
Merged to master/3.0.

**Comment by liyinan926** [comment]
LGTM.

**Comment by dongjoon-hyun** [comment]
Oh, thank you, @liyinan926 !

**Pull request closed without merging**
