### PR TITLE
[SPARK-33980][SS] Invalidate char/varchar in spark.readStream.schema

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

invalidate char/varchar in `spark.readStream.schema` just like what we've done for `spark.read.schema` in da72b87374a7be5416b99ed016dc2fc9da0ed88a

### Why are the changes needed?

bugfix, char/varchar is only for table schema while `spark.sql.legacy.charVarcharAsString=false`

### Does this PR introduce _any_ user-facing change?

yes, char/varchar will fail to define ss readers when `spark.sql.legacy.charVarcharAsString=false`

### How was this patch tested?

new tests

### CODE REVIEW

**Comment by yaooqinn** [comment]
cc @cloud-fan @maropu @HyukjinKwon thanks~

**Review by HyukjinKwon — COMMENTED** [review]
I think it's fine since at least it's consistent. But just for doubly sure, in which context char and varchar are supported? Only in pure SQL?

**Comment by yaooqinn** [comment]
> I think it's fine since at least it's consistent. But just for doubly sure, in which context char and varchar are supported? Only in pure SQL?

we currently run into such a situation.

**Review by cloud-fan — APPROVED** [review]

**Comment by cloud-fan** [comment]
> Only in pure SQL?

Only in table schema. User-specified schema can't support char/varchar.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @yaooqinn , @HyukjinKwon , @cloud-fan .
Merged to master/branch-3.1 for Apache Spark 3.1.0.

**Pull request closed without merging**
