### PR TITLE
[SPARK-6070] [yarn] Remove unneeded classes from shuffle service jar.

### PR DESCRIPTION
**Pull request by vanzin**
These may conflict with the classes already in the NM. We shouldn't
be repackaging them.

### CODE REVIEW

**Comment by vanzin** [comment]
I re-generated the jar with this patch and verified there are no "org.apache.hadoop" classes in it.

**Comment by vanzin** [comment]
Also, an alternative solution would be to force the "hadoop-provided" profile to always be on in this module. Should have the same end result.

**Comment by pwendell** [comment]
Thanks for finding this! Either approach seems fine to me. This LGTM... it might be nice to add a comment explaining that this is needed because the root pom is declaring them at compile scope.

**Comment by vanzin** [comment]
I updated the diff with the profile approach since it doesn't requiring looking for what dependencies have their scope overridden, and seems cleaner overall.

**Comment by vanzin** [comment]
Actually, d'oh, there might be an even easier fix. Hang on.

**Comment by pwendell** [comment]
Cool LGTM

**Comment by pwendell** [comment]
Thanks Marcelo, pulling this in!

**Pull request closed without merging**
