### PR TITLE
[SPARK-44523][SQL] Filter's maxRows/maxRowsPerPartition is 0 if condition is FalseLiteral

### PR DESCRIPTION
**Pull request by wangyum**
### What changes were proposed in this pull request?

This PR updates Filter's maxRows/maxRowsPerPartition to 0 if condition is `FalseLiteral`.

### Why are the changes needed?

Provide an accurate value, as some optimization rules use this value to optimize queries.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Unit test.

### CODE REVIEW

**Comment by zhengruifeng** [comment]
LGTM, but I would like @cloud-fan to also take a look

**Review by HyukjinKwon — APPROVED** [review]
LGTM I think this is fine.

**Comment by HyukjinKwon** [comment]
Merged to master.

**Review by beliefer — COMMENTED** [review]
LGTM +1

**Pull request closed without merging**
