### PR TITLE
[SPARK-20661][SPARKR][TEST][FOLLOWUP] SparkR tableNames() test fails

### PR DESCRIPTION
**Pull request by felixcheung**
## What changes were proposed in this pull request?

Change it to check for relative count like in this test https://github.com/apache/spark/blame/master/R/pkg/inst/tests/testthat/test_sparkSQL.R#L3355 for catalog APIs

## How was this patch tested?

unit tests, this needs to combine with another commit with SQL change to check

### CODE REVIEW

**Comment by falaki** [comment]
@felixcheung this approach is fine, but I think it is better if unit tests do not leave any side-effects to begin with. In this case every test should clean up state before and after (similar to `beforeAach()`)

**Comment by felixcheung** [comment]
that I agree completely, @falaki - maybe we should audit the Scala SQL tests - pretty sure R tests do not leave anything behind and only fails apparently when running Scala tests before running R tests

**Comment by felixcheung** [comment]
I think this might be the reason? @yhuai @gatorsmile Am I reading these right that these tables are created but never dropped?
https://github.com/apache/spark/commit/22691556e5f0dfbac81b8cc9ca0a67c70c1711ca#diff-1e55698cc579cbae676f827a89c2dc2eR186

**Comment by yhuai** [comment]
@felixcheung  you are right. That is the problem.

**Comment by yhuai** [comment]
@falaki's PR did not actually trigger that test.

**Comment by yhuai** [comment]
lgtm

**Comment by felixcheung** [comment]
hmm, spoke too soon I think - looks to me like all the `withTable` clause are in place and complete.
not sure what can be leaking through then..

**Comment by yhuai** [comment]
i see. I think https://github.com/apache/spark/pull/17905/commits/d4c1a9db25ee7386f7b12e4dabb54210a9892510 is good. How about we get it checked in first (after jenkins passes)?

**Comment by felixcheung** [comment]
right. I think it's a good way to decouple R tests from any earlier states and also not to mask the error/leak. I'll get that in when Jenkins pass (and see if I could figure out what is leaked)

**Comment by gatorsmile** [comment]
How about https://github.com/apache/spark/pull/17908? It tries to reset the cataloged metadata objects and temporary objects.

**Comment by felixcheung** [comment]
ok Jenkins passes, I'm going to merge this in since there are a bunch of PR failing because of this, even when they say it's up-to-date with master.
I'm going to investigate further though.

**Comment by felixcheung** [comment]
merged to master/2.2

**Pull request closed without merging**
