### PR TITLE
[SPARK-30533][ML][PYSPARK] Add classes to represent Java Regressors and RegressionModels

### PR DESCRIPTION
**Pull request by zero323**
### What changes were proposed in this pull request?

This PR adds:

- `pyspark.ml.regression.JavaRegressor`
- `pyspark.ml.regression.JavaRegressionModel`

classes and replaces `JavaPredictor` and `JavaPredictionModel` in

- `LinearRegression` / `LinearRegressionModel`
- `DecisionTreeRegressor` / `DecisionTreeRegressionModel` (just addition as `JavaPredictionModel` hasn't been used)
- `RandomForestRegressor` / `RandomForestRegressionModel`  (just addition as `JavaPredictionModel` hasn't been used)
- `GBTRegressor` / `GBTRegressionModel` (just addition as `JavaPredictionModel` hasn't been used)
- `AFTSurvivalRegression` / `AFTSurvivalRegressionModel`
- `GeneralizedLinearRegression` / `GeneralizedLinearRegressionModel`
- `FMRegressor` / `FMRegressionModel`

### Why are the changes needed?

- Internal PySpark consistency.
- Feature parity with Scala.
- Intermediate step towards implementing [SPARK-29212](https://issues.apache.org/jira/browse/SPARK-29212)

### Does this PR introduce any user-facing change?

It adds new base classes, so it will affect `mro`. Otherwise interfaces should stay intact.

### How was this patch tested?

Existing tests.

### CODE REVIEW

**Review by srowen — COMMENTED** [review]
Is this more for symmetry than anything else? I don't have a strong opinion. I'd defer to @huaxingao and @zhengruifeng who have been watching this much more closely.

**Review by zhengruifeng — APPROVED** [review]

**Comment by zhengruifeng** [comment]
Looks reasonable

**Comment by huaxingao** [comment]
I think on scala side, it makes more sense to make all Regression classes extend Regressor, because the Regressor class is already there and some of the Regression classes already implement Regressor, so it's better to make all Regression classes follow the same standard. But I am not so sure about python side: the Regressor class is basically empty and I am not sure if we should add another layer of abstraction, so I chose not to add Regressor/Regressor class on python side when I did https://github.com/apache/spark/pull/27168.  But I know you can argue that we need change python too to keep the parity between scala and python. I am OK either way.

**Comment by zero323** [comment]
> The Regressor class is basically empty and I am not sure if we should add another layer of abstraction, so I chose not to add Regressor/Regressor class on python side when I did #27168. But I know you can argue that we need change python too to keep the parity between scala and python. I am OK either way.

I am actually not that interested in  parity (as it is right now it provides little or no value to the end user, inflates `pyspark.ml` codebase, and actually increases effort required to maintain the whole thing) as much as practical value. As I argued in discussion around https://github.com/apache/spark/pull/25776#issuecomment-533488999 ability to distinguish between types of predictors is fundamental for building complex ML workflows, and current API is not sufficient to that (`Classifiers` and non classifier `Predictors` usually have the same API, and produce identical output schema).

> the Regressor class is basically empty

I am afraid that's, for good or bad, argument you can make against significant chunk of the API.

**Comment by huaxingao** [comment]
LGTM

**Comment by srowen** [comment]
Merged to master

**Comment by zero323** [comment]
Thanks @huaxingao @srowen @zhengruifeng

**Pull request closed without merging**
