### PR TITLE
[BUILD] Test closing stale PRs

### PR DESCRIPTION
**Pull request by srowen**
## What changes were proposed in this pull request?

Here I'm seeing if we can close stale PRs via a PR message, as I'd expect.
See thread https://www.mail-archive.com/dev@spark.apache.org/msg14149.html

Closes #9354
Closes #9451
Closes #10507
Closes #10486
Closes #10460
Closes #10967
Closes #10681
Closes #11766
Closes #9907
Closes #10209
Closes #10379
Closes #10403
Closes #10842
Closes #11036
Closes #13003
Closes #10887
## How was this patch tested?

(No changes)

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
+1

**Comment by HyukjinKwon** [comment]
Do you mind adding #13003 maybe?

**Comment by srowen** [comment]
@HyukjinKwon that's already in the description. I'm ignoring the failure since there is no change to anything at all here.

**Comment by srowen** [comment]
Merged to master. Let's see if it worked.

**Comment by srowen** [comment]
PS for anyone who tries this -- it does work, but to make the merge script work with an empty commit, its `git commit` command needs `--allow-empty`. I didn't actually suggest changing the script since we generally don't want to allow that, I think.

**Pull request closed without merging**
