### PR TITLE
[SPARK-37081][SQL][TESTS] Upgrade the version of RDBMS and corresponding JDBC drivers used by docker-integration-tests

### PR DESCRIPTION
**Pull request by sarutak**
### What changes were proposed in this pull request?

This PR upgrades the version of RDBMS and corresponding JDBC drivers used by docker-integration-tests.

### Why are the changes needed?

To ensure the JDBC source works with the latest stable version of the supported RDBMS.
Especially, PostgreSQL 14 was released recently so it's great to care about it.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

`docker-integration-tests` in GitHub Actions.

### CODE REVIEW

**Comment by sarutak** [comment]
retest this please.

**Comment by sarutak** [comment]
cc: @gaborgsomogyi

**Review by gaborgsomogyi — APPROVED** [review]
Thanks for upgrading the versions. LGTM.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
