### PR TITLE
[SQL] Typo in HashedRelation error

### PR DESCRIPTION
**Pull request by aaron-lau**
### What changes were proposed in this pull request?

Fixed typo in exception message of HashedRelations

### Why are the changes needed?

Better exception messages

### Does this PR introduce any user-facing change?

No

### How was this patch tested?

No tests needed

### CODE REVIEW

**Review by armcburney — APPROVED** [review]
LGTM! 🚢 :shipit: 🚀

**Review by philos22 — APPROVED** [review]
Good catch!

**Review by gary-huang — APPROVED** [review]
Can one of the admins verify this patch?

**Comment by HyukjinKwon** [comment]
ok to test

**Review by HyukjinKwon — COMMENTED** [review]
This is fine. but mind checking if there are other typos in this module while we're here? I am sure there are more.

**Comment by srowen** [comment]
I'll merge it to clear it, but yeah we generally ask people to at least look around for others while they're at it, just to avoid 100 PRs for 100 typos. But, nothing wrong with just fixing one if it's material and nothing else pops out. This is pretty trivial though

**Pull request closed without merging**
