### PR TITLE
[SPARK-12170] [SparkR] Deprecate the JAVA-specific deserialized storage levels

### PR DESCRIPTION
**Pull request by yanboliang**
Since the data is always serialized on the R side, the storage levels of JAVA-specific deserialization should be deprecated. We should automatically convert `MEMORY_ONLY` to `MEMORY_ONLY_SER` and deprecated `MEMORY_ONLY_SER` at SparkR side. Please refer the similar change for PySpark at #10092.

### CODE REVIEW

**Comment by sun-rui** [comment]
@yanboliang, thanks for the PR. But for SparkR RDD API, still discussion how to evolve it. So maybe we need more discussion before submitting a PR for all RDD related JIRA issues (Those JIRAs are for tracking purpose for now)

@shivaram, @felixcheung.

**Comment by yanboliang** [comment]
@sun-rui Got it, thanks for your kindly remind.

**Comment by felixcheung** [comment]
yes, in fact we are instructed not to work on Spark 2.0 release yet

**Comment by shivaram** [comment]
@yanboliang Could you close this PR for now ? It just makes the reviewing queue easier

**Comment by yanboliang** [comment]
OK, I will close this PR.

**Pull request closed without merging**
