### PR TITLE
[SPARK-8414] Ensure context cleaner periodic cleanups

### PR DESCRIPTION
**Pull request by andrewor14**
Garbage collection triggers cleanups. If the driver JVM is huge and there is little memory pressure, we may never clean up shuffle files on executors. This is a problem for long-running applications (e.g. streaming).

### CODE REVIEW

**Comment by andrewor14** [comment]
@tdas @JoshRosen

**Comment by andrewor14** [comment]
retest this please

**Comment by andrewor14** [comment]
retest this please

**Comment by JoshRosen** [comment]
After this change, do you think that there's any chance that we could deprecate the somewhat unsafe `spark.cleaner.ttl` parameter? Should we update the docs to reflect this new parameter and suggest that `spark.cleaner.ttl` should no longer need to be set? Also fine to do that separately, but just wondering.

**Comment by andrewor14** [comment]
Let's do that separately

**Comment by JoshRosen** [comment]
LGTM

**Comment by JoshRosen** [comment]
LGTM, so I'm going to merge this into master and branch-1.6.

**Pull request closed without merging**
