### PR TITLE
[SPARK-33594][SQL] Forbid binary type as partition column

### PR DESCRIPTION
**Pull request by AngersZhuuuu**
### What changes were proposed in this pull request?
According to https://issues.apache.org/jira/browse/SPARK-33593 and  https://issues.apache.org/jira/browse/HIVE-24049
Maybe we should avoid use binary type as partition column.

The production environment won't use this case either.

### Why are the changes needed?
use binary  type as partition column may cause data  issue

### Does this PR introduce _any_ user-facing change?
User can't use binary type column as partition column

### How was this patch tested?
Added UT

### CODE REVIEW

**Review by MaxGekk — COMMENTED** [review]
Is the issue specific to Parquet Vectorized reader? or some other datasources work incorrectly?

**Comment by AngersZhuuuu** [comment]
> Is the issue specific to Parquet Vectorized reader? or some other datasources work incorrectly?

Currently only with Parquet  Vectorized Reader

**Comment by srowen** [comment]
I get it, but it still has a well-defined equality and hash value, etc, right? it's not inherently meaningless to partition on it.

**Comment by AngersZhuuuu** [comment]
> I get it, but it still has a well-defined equality and hash value, etc, right? it's not inherently meaningless to partition on it.

Yes,  that makes sense, but we've also disabled other complex data types and intervals,  I suggest to forbid this too to avoid unnecessary data issue. Hope others suggestion.

**Comment by shaneknapp** [comment]
test this please

**Comment by HyukjinKwon** [comment]
cc @wangyum

**Comment by wangyum** [comment]
+1 for disable binary type as partition column.

**Comment by AngersZhuuuu** [comment]
retest this please

**Comment by AngersZhuuuu** [comment]
retest this please

**Comment by AngersZhuuuu** [comment]
Any more update?

**Comment by AngersZhuuuu** [comment]
retest this please

**Comment by AngersZhuuuu** [comment]
retest this please

**Pull request closed without merging**
