### PR TITLE
[SPARK-24209][SHS] Automatic retrieve proxyBase from Knox headers

### PR DESCRIPTION
**Pull request by mgaido91**
## What changes were proposed in this pull request?

The PR retrieves the proxyBase automatically from the header `X-Forwarded-Context` (if available). This is the header used by Knox to inform the proxied service about the base path.

This provides 0-configuration support for Knox gateway (instead of having to properly set `spark.ui.proxyBase`) and it allows to access directly SHS when it is proxied by Knox. In the previous scenario, indeed, after setting `spark.ui.proxyBase`, direct access to SHS was not working fine (due to bad link generated).

## How was this patch tested?

added UT + manual tests

### CODE REVIEW

**Comment by mgaido91** [comment]
@jerryshao may you please review this when you have time? Thanks.

**Comment by nrchakradhar** [comment]
@mgaido91 Just a query. Is this specific to Knox only or will it work when the HistoryServer UI is proxied by different load balancer?

**Comment by mgaido91** [comment]
@nrchakradhar if the load balancer fills the header `X-Forwarded-Context` with the proper base path, then this will work.

**Comment by jerryshao** [comment]
The changes here seems affect so many places, I'm wondering if there's any other way to minimize the changes?

**Comment by mgaido91** [comment]
Thanks for your comment @jerryshao. Unfortunately I don't think so. Since through the SHS you can access all the other pages, all of them have to support the proper detection of the proxy base as well.

**Comment by jerryshao** [comment]
I'm still thinking this change requires so many updates across the whole project, and we may miss it in future if someone add new codes. Though I'm not familiar with knox, my question is that what is the shortage of using "spark.ui.proxyBase", and what is the special advantage of this change?

**Comment by mgaido91** [comment]
@jerryshao I don't think we can miss them. The main change here is the `uiRoot` requires the `request` object. So if you miss to provide it the object, it doesn't compile. All the other changes are just for passing the `request` object where it is needed.

The main advantage is that this change allows to connect to SHS both via Knox gateway and via direct URL. Using `spark.ui.proxyBase`, you can support Knox setting it for instance to `gateway/default/sparkhistoryui`. When you do this, if you access SHS via direct URL, it won't work. So you can't access SHS successfully both via Knox gateway and via the direct URL. This change allows this to happen instead.
Another minor advantage is that (for the same reason) we can support multiple Knox gateway to proxy SHS.

**Comment by mgaido91** [comment]
@vanzin may you please take a look at this too? Thanks.

**Comment by mgaido91** [comment]
@vanzin do you happen to have any time for checking this please? Thanks.

**Comment by vanzin** [comment]
I took a look and it looks ok. I'm just confused about the YARN comments, since the AM does not set anything (the YARN NM will set the `APPLICATION_WEB_PROXY_BASE` env variable, but nothing else sets or even references `spark.ui.proxyBase`).

But that's not part of your change so no need to worry about that.

**Comment by vanzin** [comment]
retest this please

**Comment by vanzin** [comment]
BTW you could probably avoid the plumbing (and noise) by using a DynamicVariable but that feels too hacky and brittle, so I actually prefer this.

**Comment by mgaido91** [comment]
@vanzin thanks for your review.

I checked the comment you mentioned. My understanding is that the property `spark.ui.proxyBase` is used by Oozie and in particular it is set bu the AM of the MapReduce job generated by Oozie.

PS yes, I prefer this approach over the usage of `DynamicVariable` because it seems safer to me: you can miss to set it somewhere (or it doesn't build).

**Comment by vanzin** [comment]
Merging to master.

**Comment by mgaido91** [comment]
thanks @vanzin.

**Pull request closed without merging**
