### PR TITLE
[SPARK-31434][SQL][DOCS] Drop builtin function pages from SQL references

### PR DESCRIPTION
**Pull request by maropu**
### What changes were proposed in this pull request?

This PR intends to drop the built-in function pages from SQL references. We've already had a complete list of built-in functions in the API documents.

See related discussions for more details: 
https://github.com/apache/spark/pull/28170#issuecomment-611917191

### Why are the changes needed?

For better SQL documents.

### Does this PR introduce any user-facing change?

functions

### How was this patch tested?

Manually checked.

### CODE REVIEW

**Comment by maropu** [comment]
cc: @huaxingao @HyukjinKwon @srowen

**Comment by HyukjinKwon** [comment]
+1 as the temporary status. I will try to get the auto-generation done for Spark 3.0 .. if nobody takes it ..

**Comment by HyukjinKwon** [comment]
From my cursory look, seems good to go.

**Comment by huaxingao** [comment]
The changes look good. The only problem is that I don't have a place any more to document the window functions. We don't want to list the window function names and descriptions, but we still want to document what window functions are, how to use them and examples, right?

**Comment by maropu** [comment]
> The changes look good. The only problem is that I don't have a place any more to document the window functions. We don't want to list the window function names and descriptions, but we still want to document what window functions are, how to use them and examples, right?

We still need to document them? They are also listed in the auto-generated API doc, right?

**Comment by huaxingao** [comment]
The auto-generated API doc has the function description, but it doesn't cover the detailed usage such as how to mark the function as window function, how to define the window spec, what's inside the window spec, etc. Window function is quite important and complex, so we need more documentation than function description.
I discussed with @gatorsmile earlier today, if we can't document window function here, he wants me to have detailed documentation for all these window functions in SQL syntax section.

**Comment by maropu** [comment]
If necessary, how about adding them in `sql-ref-syntax-qry-window.md` like table-value functions?

**Comment by huaxingao** [comment]
Sure. I will document these in SQL syntax section instead.

**Comment by maropu** [comment]
Thanks!

**Comment by HyukjinKwon** [comment]
@huaxingao, do you have any page you want to keep here otherwise? Then I will just merge this.

**Comment by huaxingao** [comment]
No... The main purpose of having a builtin function page is to document window function. Now since there is an alternative place to document this, I am OK to remove this page. Please go ahead to merge. Thanks for checking with me. @HyukjinKwon

**Comment by HyukjinKwon** [comment]
Merged to master and branch-3.0.

**Review by HyukjinKwon — APPROVED** [review]
LGTM

**Comment by HyukjinKwon** [comment]
Merged to master and branch-3.0.

**Comment by maropu** [comment]
Thanks, all.

**Pull request closed without merging**
