### PR TITLE
[MINOR] To use the `Utils.tryLog` to eliminate duplicate code in `ExecutorAllocationManager.start` snippet

### PR DESCRIPTION
**Pull request by yikf**
### What changes were proposed in this pull request?

This pr aims to use the `Utils.tryLog` to eliminate duplicate code in `ExecutorAllocationManager.start` snippet.  Other code snippets have been checked and there are no similar problems

### Why are the changes needed?

Code simplification

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

exist tests

### CODE REVIEW

**Review by srowen — COMMENTED** [review]
The semantics look possibly slightly different - tryLog catches NonFatal and logs an error. Is Throwable vs ControlThrowable the same, or close enough? probably.

**Comment by yikf** [comment]
> The semantics look possibly slightly different - tryLog catches NonFatal and logs an error. Is Throwable vs ControlThrowable the same, or close enough? probably.

ControlThrowable is subclass of the Throwable,  It is usually used as a marker trait for flow control, where catch-all behaviour is required ControlThrowable  should be propagated.

tryLog catching ControlThrowable will throw it otherwise logs an error, this is much consistent with `ExecutorAllocationManager.start`(except for the log level, but it's ok probably)

It seems you may have said tryLogNonFatalError? probably. NonFatal extract non-fatal Throwables, Will not match fatal errors like ControlThrowable and other fatal throwable, it seems the semantics is different with `ExecutorAllocationManager.start`(NonFatal don't match ControlThrowable but `ExecutorAllocationManager.start` will throw it)

**Comment by srowen** [comment]
If NonFatal doesn't match ControlThrowable then tryLog will let it throw, so that seems the same. I mean, I think this is fine to standardize in any event, just trying to think if there was any specific reason it should behave differently, if it does at all.

**Comment by yikf** [comment]
emm... i guess whether you are confusing [tryLog](https://github.com/apache/spark/blob/f8d51b9940b5f1f7c1f37693b10931cbec0a4741/core/src/main/scala/org/apache/spark/util/Utils.scala#L2059) with [tryLogNonFatalError](https://github.com/apache/spark/blob/f8d51b9940b5f1f7c1f37693b10931cbec0a4741/core/src/main/scala/org/apache/spark/util/Utils.scala#L1468)? (probably, Sorry if I got this wrong).

&emsp;1\) &ensp; tryLog  catches ControlThrowable will throw it otherwise logs an error, not catches NonFatal and logs an error.
&emsp;2\) &ensp; tryLogNonFatalError catches NonFatal and logs an error.

This pr aims to replace existing duplicate code with `tryLog`(not tryLogNonFatalError) , trylog is consistent with existing logic(catch  `ControlThrowable` will throw it otherwise logs an error), so that seems ok.

and if  `tryLogNonFatalError`(catches NonFatal and logs an error), the semantics possibly slightly different with currently logic.
&emsp;1\) &ensp;  if ControlThrowable, both will be thrown (both consistent).
&emsp;2\) &ensp;  if VirtualMachineError | ThreadDeath | InterruptedException | LinkageError, tryLogNonFatalError will throw these throwable, but currently logic log an error only (this may be the answer to your question).
>  just trying to think if there was any specific reason it should behave differently

&emsp;3\) &ensp;  if others, both log an error (both consistent).

**Comment by srowen** [comment]
Oh yeah, I'm looking at the wrong method, I get it now. So this really isn't a change. OK.

**Review by mridulm — APPROVED** [review]

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
