### PR TITLE
[SPARK-48337][SQL] Fix precision loss for JDBC TIME values

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

The method `java.sql.Time.toLocalTime` discards the fraction parts of time values. In this pull request, we avoid using it by calculating milliseconds to microseconds directly.

### Why are the changes needed?

fix precision loss

### Does this PR introduce _any_ user-facing change?

Yes, 
- Before this PR time values like `11:22.33.456` would result in `1970-01-01 11:22.33` where the fractional part was truncated.
- After this PR, `1970-01-01 11:22.33.456` 

### How was this patch tested?

new tests

### Was this patch authored or co-authored using generative AI tooling?
no

### CODE REVIEW

**Comment by yaooqinn** [comment]
cc @cloud-fan @LuciferYang @dongjoon-hyun thanks

**Review by dongjoon-hyun — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @yaooqinn .

**Review by LuciferYang — APPROVED** [review]
+1, LGTM

**Comment by yaooqinn** [comment]
Merged to master. Thank you @dongjoon-hyun @LuciferYang

**Comment by cloud-fan** [comment]
late LGTM

**Pull request closed without merging**
