### PR TITLE
[MINOR][DOCS] Fix typos in python user guide and "the the" in the whole codebase

### PR DESCRIPTION
**Pull request by sudoliyang**
### What changes were proposed in this pull request?

Fix typos in python user guide and "the the" in the whole codebase.

### Why are the changes needed?

Improve readability.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Tested by checking dictionary.

### CODE REVIEW

**Comment by huaxingao** [comment]
jenkins test this please

**Review by huaxingao — APPROVED** [review]

**Comment by sarutak** [comment]
@sudoliyang 
Could you revise the title with proper tags ? I think it's OK to be like `[MINOR][DOCS] Fix typos in XXX` in this case.
Also, could you do the following things?

* Read [the contribution guide](http://spark.apache.org/contributing.html)
* Enable GitHub Actions on your forked repository (see the `Details` link of the failed job).
* Check the similar typos in the whole code and other typos in the changed file. It's better to fix bunch of typos at once.

**Comment by sarutak** [comment]
@sudoliyang 
Surprised that there are so many `the the`...
In addition to what you have found, `rdd.py` seems to contain `The the`.

**Comment by sarutak** [comment]
Also, could you modify the title properly? Now you change not only python user guide.

**Review by HyukjinKwon — APPROVED** [review]

**Review by sarutak — APPROVED** [review]

**Comment by sarutak** [comment]
Merge to `master`. Thank you all !

**Comment by sudoliyang** [comment]
@sarutak Thanks for all the help!

**Pull request closed without merging**
