### PR TITLE
[SPARK-36992][SQL] Improve byte array sort perf by unify getPrefix function of UTF8String and ByteArray

### PR DESCRIPTION
**Pull request by ulysses-you**
### What changes were proposed in this pull request?

Unify the getPrefix function of `UTF8String` and `ByteArray`.

### Why are the changes needed?

When execute sort operator, we first compare the prefix. However the getPrefix function of byte array is slow. We use first 8 bytes as the prefix, so at most we will call 8 times with `Platform.getByte` which is slower than call once with `Platform.getInt` or `Platform.getLong`.

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

pass `org.apache.spark.util.collection.unsafe.sort.PrefixComparatorsSuite`

### CODE REVIEW

**Comment by kiszk** [comment]
After all code change is finished, could you please compare the result of SortBenchmark w/o and w this PR?   
Sort is one of the critical operations in SQL.

**Comment by cloud-fan** [comment]
looks fine

**Review by srowen — APPROVED** [review]

**Review by JoshRosen — APPROVED** [review]
LGTM.

I was curious to know if there was a reason why these codepaths were originally separate, so I dug into the commit history to find out:

- Sorting of binary type data was originally introduced in #2617. This implemented an ordering based on signed byte array comparisons.
- PrefixComparators support for BinaryType was added in #7676. There was [some discussion](https://github.com/apache/spark/pull/7676#discussion_r36246817) of copying the approach from UTF8String but we didn't do that because of the need to use signed comparisons.
- Later in #18571 we realized that the use of signed comparison for byte arrays was incorrect and switched to unsigned comparisons.

This explains why those paths historically diverged. I'm glad that this PR cleaned things up and got a performance benefit along the way.

**Comment by kiszk** [comment]
@ulysses-you looks good.

I believe `Since JVMs are either 4-byte aligned or 8-byte aligned, we check the size of the bytes` is correct now.   
For future SW and HW platforms, can we add simple test cases for ByteArray that accesses 1, 2, ...., 7, 8 bytes. It would help future porting to new platforms.

**Review by kiszk — APPROVED** [review]
Thank you

**Comment by ulysses-you** [comment]
thank you all !

**Pull request closed without merging**
