### PR TITLE
[SPARK-36276][BUILD][FOLLOWUP] Match the version of SBT's checkstyle plugin to Maven's one

### PR DESCRIPTION
**Pull request by sarutak**
### What changes were proposed in this pull request?

This PR upgrade SBT's checkstyle plugin to `8.43`.

### Why are the changes needed?

The previous PR (#33500) upgraded Maven's plugin but seems to have forgot to do for SBT's one.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

CIs.

### CODE REVIEW

**Review by JoshRosen — COMMENTED** [review]
It looks like we've also forgotten to update the SBT version during past version bumps, too: https://github.com/apache/spark/pull/33207

Could you add a comment before
 https://github.com/apache/spark/blob/9d061e3939a021c602c070fc13cef951a8f94c82/pom.xml#L3154-L3157 to remind developers to bump the SBT version, too?

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by sarutak** [comment]
@JoshRosen O.K, I'll add it.

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
