### PR TITLE
[SPARK-26364][PYTHON][TESTING] Clean up imports in test_pandas_udf*

### PR DESCRIPTION
**Pull request by icexelloss**
## What changes were proposed in this pull request?

Clean up unconditional import statements and move them to the top.

Conditional imports (pandas, numpy, pyarrow) are left as-is.

## How was this patch tested?

Exising tests.

### CODE REVIEW

**Comment by icexelloss** [comment]
cc @BryanCutler @HyukjinKwon @ueshin

**Comment by HyukjinKwon** [comment]
retest this please

**Review by HyukjinKwon — APPROVED** [review]
LGTM

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
