### PR TITLE
[SPARK-10825][Core][Tests]Fix race conditions in StandaloneDynamicAllocationSuite

### PR DESCRIPTION
**Pull request by zsxwing**
Fix the following issues in StandaloneDynamicAllocationSuite:
1. It should not assume master and workers start in order
2. It should not assume master and workers get ready at once
3. It should not assume the application is already registered with master after creating SparkContext
4. It should not access Master.app and idToApp which are not thread safe

The changes includes:
- Use `eventually` to wait until master and workers are ready to fix 1 and 2
- Use `eventually`  to wait until the application is registered with master to fix 3
- Use `askWithRetry[MasterStateResponse](RequestMasterState)` to get the application info to fix 4

### CODE REVIEW

**Comment by zsxwing** [comment]
I will send a new PR to include #6457 and #8905 once this one gets merged.

**Comment by vanzin** [comment]
LGTM but Andrew should take a look. I looked at this code recently and really found it odd that it expected things to just be updated "atomically", so good thing I was not crazy.

**Comment by andrewor14** [comment]
Thanks for fixing this! I'm surprised that it hasn't been flaky until recently. It must be due to the increase on Jenkins load. Merged into master and 1.5.

**Pull request closed without merging**
