### PR TITLE
[SPARK-28548][SQL] explain() shows wrong result for persisted DataFrames after some operations

### PR DESCRIPTION
**Pull request by sarutak**
## What changes were proposed in this pull request?

After some operations against Datasets and then persist them, Dataset.explain shows wrong result.
One of those operations is explain() itself.
An example here.

```
val df = spark.range(10)
df.explain
df.persist
df.explain
```

Expected result is like as follows.
```
== Physical Plan ==
*(1) ColumnarToRow
+- InMemoryTableScan [id#7L]
      +- InMemoryRelation [id#7L], StorageLevel(disk, memory, deserialized, 1 replicas)
            +- *(1) Range (0, 10, step=1, splits=12)
```

But I got this.
```
== Physical Plan ==
*(1) Range (0, 10, step=1, splits=12)
```

This issue is caused by `withCachedData` in `QueryExecution` is materialized early when `explain()` or such methods are called so this patch prevents it.

## How was this patch tested?
Additional test cases in `ExplainSuite.scala`

### CODE REVIEW

**Comment by maropu** [comment]
wait, it seems the query works well in v2.4.3;
```
scala> df.explain
== Physical Plan ==
*(1) Range (0, 10, step=1, splits=4)

scala> df.persist
res1: df.type = [id: bigint]

scala> df.explain
== Physical Plan ==
*(1) InMemoryTableScan [id#0L]
   +- InMemoryRelation [id#0L], StorageLevel(disk, memory, deserialized, 1 replicas)
         +- *(1) Range (0, 10, step=1, splits=4)
scala> 
```
Which commit affects the behaviour?

**Comment by cloud-fan** [comment]
It's by design that a dataframe can't change its physical plan once the physical plan is materialized. That said, `df.persist` has no effect if `df.explain` is called before.

I think the current behavior is corrected and v2.4.3 is wrong. I think this problem is fixed by https://github.com/apache/spark/pull/24654

If you do wanna run the plan with cached data, maybe we can do `val df2 = df.toDF()` and execute `df2` instead.

**Comment by cloud-fan** [comment]
Actually, this does expose a problem. Before #24654, `df.explain` won't materialize the physical plan, but now we do. cc @viirya do you have any ideas? I think this one is hard to fix?

**Comment by sarutak** [comment]
@cloud-fan I have already noticed #24654. The problem mentioned in that PR is that pre-analyzed logical plan was always reused and re-analyzed in explain command even though analyzed-logical plan is already materialized.

This solution consider that problem. If we have already analyzed-logical plan materialized, we use it otherwise create one.

**Comment by viirya** [comment]
We actually take the query execution of dataset to execute. If we have executed a dataset, so its physical plan is materialized, then persist it. In 2.4.3, although df.explain shows a cached plan, I think execution still uses physical plan without cache? This fix also has the issue?

That said, in 2.4.3, df.explain shows query plan with current status like cache, temp view, I think it doesn't really match with dataset execution.

Like:

```scala
val df = spark.range(10)
df.explain // show query plan without cache
df.collect() // execution without cache 
df.persist
df.explain // show query plan with cache
df.collect() // still execution without cache
```

**Comment by maropu** [comment]
We cannot just return a new Dataset in persist, btw, like this?
```
val df = spark.range(10)
df.explain // show query plan without cache
df.collect // execution without cache

val cachedDf = df.persist

df.explain // show query plan without cache
df.collect // execution without cache

cachedDf.explain // show query plan with cache
cachedDf.collect // execution with cache
```

**Comment by cloud-fan** [comment]
@maropu this is a behavior change and can break many queries silently.

**Comment by sarutak** [comment]
@viirya With my change, we can get following result.

```
val df = spark.range(10)
df.explain  // show query plan without cache
df.collect  // execution without cache
df.persist
df.explain // show query plan without cache
df.collect // execution without cache
df.queryExecution.executedPlan.find(_.isInstanceOf[InMemoryTableScanExec]) // None
```

After `collect`, `persist` is still ignored but this result is different from one of `2.4.3` and same for `master` branch.
As you mentioned `df.collect` and some operations materialize the `executedPlan` and cause this problem.

Some operations including `df.show` don't cause this problem because they create the new root plan at the time of execution implicitly so I wonder creating dummy root plan at the time of executing `collect` or similar operations resolve this type of problem?

**Comment by felixcheung** [comment]
... where are we on this? this seems to be severe correctness impacting issue?

**Comment by cloud-fan** [comment]
This is not a correctness issue. This is just an undocumented property "a dataframe can't change its physical plan once the physical plan is materialized" causing confusions.

After so many days, I have a fresh idea now: when `df.cache` is called, reset the `cachedPlan`, `optimizedPlan` and physical plans. We can implement the lazy evaluation manually to support it instead of relying on Scals lazy val.

**Comment by maropu** [comment]
btw, we don't need to describe something about this behaviour in the migration guide if the current one is correct? @gatorsmile @cloud-fan

**Comment by HyukjinKwon** [comment]
I wouldn't mind documenting it but sounds more like a bug fix given my reading, and it seems only affecting a debug API (`explain`). So I suspect it's fine not to document for now.

**Comment by maropu** [comment]
ok, thanks for the check.

**Pull request closed without merging**
