### PR TITLE
[SPARK-27859][SS] Use efficient sorting instead of `.sorted.reverse` sequence

### PR DESCRIPTION
**Pull request by wenxuanguan**
## What changes were proposed in this pull request?

descending sort in HDFSMetadataLog.getLatest instead of two action of ascending sort and reverse

## How was this patch tested?

Jenkins

### CODE REVIEW

**Comment by wenxuanguan** [comment]
please test.

**Review by srowen — APPROVED** [review]

**Comment by wenxuanguan** [comment]
please retest.

**Comment by wenxuanguan** [comment]
retest this please

**Comment by wenxuanguan** [comment]
retest this please.

**Comment by wenxuanguan** [comment]
@dongjoon-hyun @HyukjinKwon  Can you please have a look?

**Comment by dongjoon-hyun** [comment]
Thank you for pinging me, @wenxuanguan . Please make a JIRA issue and use the ID. This is trivial but worth for it.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. I also checked that these three instances are the only left ones (direct sequence, `.sorted.reverse`).

Thank you, @wenxuanguan .

**Comment by dongjoon-hyun** [comment]
Also, please update PR title and description. You didn't include the changes in `streaming/ui/BatchPage.scala`

**Comment by dongjoon-hyun** [comment]
I'll create for you.

**Comment by dongjoon-hyun** [comment]
Merged to master.

**Comment by wenxuanguan** [comment]
@srowen @dongjoon-hyun Thank you for review

**Comment by dongjoon-hyun** [comment]
You're welcome, @wenxuanguan .

**Comment by HyukjinKwon** [comment]
yea LGTM too

**Comment by wenxuanguan** [comment]
> yea LGTM too

Thank you for review

**Pull request closed without merging**
