### PR TITLE
[SPARK-8072] [SQL] Better AnalysisException for writing DataFrame with identically named columns

### PR DESCRIPTION
**Pull request by animeshbaranawal**
1. Created a rule for checking duplicate column names in a dataframe by inspecting its Logical Plan
2. Throw exception message containing duplicate column names if such a dataframe is found.

cc @rxin

### CODE REVIEW

**Comment by cloud-fan** [comment]
Can you add a test for it? And, what if we are in case-insensitive context?

**Comment by animeshbaranawal** [comment]
If we are in case-insensitive context, this won't work. Should I modify it to include case-insensitive context too?

**Comment by marmbrus** [comment]
I'm worried about adding a rule like this.  It could break a lot of existing applications.

**Comment by marmbrus** [comment]
To be clear, I want to have a good error message, but I think we can only do this when writing out to formats where this is a problem and not generally in analysis.

**Comment by animeshbaranawal** [comment]
I am closing this pull request then.

**Comment by sujkh85** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

sujkh@naver.com 님께 보내신 메일 <Re: [spark] [SPARK-8072] [SQL] Better AnalysisException for writing DataFrame with identically named columns (#6933)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Pull request closed without merging**
