### PR TITLE
[SPARK-6964][SQL] jdbc cancel 1.4

### PR DESCRIPTION
**Pull request by dongwang218**
back port of https://github.com/apache/spark/pull/6207

### CODE REVIEW

**Comment by dongwang218** [comment]
cc @yhuai

**Comment by dongwang218** [comment]
jenkins test this please

**Comment by liancheng** [comment]
LGTM

**Comment by pwendell** [comment]
Hey guys - I'd actually prefer not to put this feature in branch 1.4 since that release is already tied off. Let's just put it in the master branch

**Comment by dongwang218** [comment]
I am closing it, it is not going to branch 1.4.

**Pull request closed without merging**
