### PR TITLE
[SPARK-41339][SQL] Close and recreate RocksDB write batch instead of just clearing

### PR DESCRIPTION
**Pull request by Kimahriman**
### What changes were proposed in this pull request?

Instead of just calling `writeBatch.clear`, close the write batch and recreate it.

### Why are the changes needed?

A RocksDB `WriteBatch` (and by extension `WriteBatchWithIndex`) stores its underlying data in a `std::string`. Why? I'm not sure. But after a partition is finished, `writeBatch.clear()` is called (somewhat indirectly through a call to `store.abort`), presumably clearing the data in the `WriteBatch`. This calls `std::string::clear` followed by `std::string::resize` underneath the hood. However, neither of these two things actually reclaims native memory. All the memory allocated for expanding the string when adding data to the `WriteBatch` will be there until the `std::string` is deallocated, which in this case means deleting the `WriteBatch`. This leads to native memory accumulation on an executor and it executes several partitions consecutively, which would happen when your total executor cores is less than your shuffle partitions for your stateful stream. So instead of just calling `writeBatch.clear()`, close the `WriteBatch` and create a new one to free up the native memory.

### Does this PR introduce _any_ user-facing change?

Fix for excess native memory usage.

### How was this patch tested?

Existing UTs, not sure how to test for memory usage.

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
Nice finding! Looks like your explanation makes sense. I've quickly googled and there is `reserve` which may shrink the memory as desired but doesn't seem to be guaranteed. (And it's something we have to fix the code in RocksDB which they may have their own valid reason to do so.) So I agree this is the best approach we can do, and the fix is straightforward.

Just a couple of questions:

1) Have you run the fix with your production workload for a while and see there is no longer the same memory issue? 
2) Did https://github.com/apache/spark/commit/b8b1fbc21c66348d25be3404d3f61099f2a7a9b5 help to figure out the "sort of leaking" memory, or did it report simply the resized memory size and didn't disclose the memory issue?

Otherwise the fix itself looks OK to me.

**Comment by Kimahriman** [comment]
One question I did have, as I started digging into this I thought the problem was simply related to https://issues.apache.org/jira/browse/SPARK-38277, but as I dug into it I realized that `writeBatch.clear` is called, but by a task completion listener that calls `store.abort` [here](https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/state/package.scala#L101-L103). I wasn't sure if this was intentional or not, seems like a slightly awkward way to clear things after a partition completes. If it was intentional that issue can probably be closed.

**Comment by HeartSaVioR** [comment]
It's not intended. It looks like we missed to deal with ticket. Anyway we clear the writebatch before starting a new task for next microbatch, but I see issue when an executor handles multiple tasks for stateful operation.

**Comment by HeartSaVioR** [comment]
Just to give you more context for your previous comment (https://github.com/apache/spark/pull/38853#issuecomment-1333073885)...

We have two different set of code path, 1) two physical nodes for one stateful operator (streaming aggregation) 2) one physical node for one stateful operator (others). For the latter, it only initializes read-write state store, and at the task completion, it only calls abort if the task failed to do commit. For the former, it initializes read only state store as well, which we call abort at the task completion to clean up the resource (NOTE: not to rollback as this is read-only. The name is unfortunately due to compatibility issue during the addition of new interface. See https://github.com/apache/spark/commit/21413b7dd4e19f725b21b92cddfbe73d1b381a05).

It is safe for read-only state store to call abort() even there is another read-write store referring the same, because read-write store would have completed to call commit() if the task works correctly and we expect (effectively) no-op from calling abort() after commit().

**Review by HeartSaVioR — APPROVED** [review]
+1

**Comment by HeartSaVioR** [comment]
Thanks! Merging to master/3.3. ([SPARK-38277](https://issues.apache.org/jira/browse/SPARK-38277) can/should be handled separately.)

**Comment by HeartSaVioR** [comment]
(@Kimahriman Looks like your git is not correctly set in your dev. I manually changed the author of commit based on your mail address in dev@ mailing list.)

**Comment by Kimahriman** [comment]
> (@Kimahriman Looks like your git is not correctly set in your dev. I manually changed the author of commit based on your mail address in dev@ mailing list.)

Thanks, I did this on a new machine and forgot I haven't set that up yet.

**Comment by Kimahriman** [comment]
> Just to give you more context for your previous comment ([#38853 (comment)](https://github.com/apache/spark/pull/38853#issuecomment-1333073885))...
> 
> We have two different set of code path, 1) two physical nodes for one stateful operator (streaming aggregation) 2) one physical node for one stateful operator (others). For the latter, it only initializes read-write state store, and at the task completion, it only calls abort if the task failed to do commit. For the former, it initializes read only state store as well, which we call abort at the task completion to clean up the resource (NOTE: not to rollback as this is read-only. The name is unfortunately due to compatibility issue during the addition of new interface. See [21413b7](https://github.com/apache/spark/commit/21413b7dd4e19f725b21b92cddfbe73d1b381a05)).
> 
> It is safe for read-only state store to call abort() even there is another read-write store referring the same, because read-write store would have completed to call commit() if the task works correctly and we expect (effectively) no-op from calling abort() after commit().

So the abort is there to basically make sure any writes to the read only state store get reverted unless a downstream read-write instance has already committed changes. I know there are a few different code paths for stateful things (sessions, flatmapgroupswithstate, etc), do we know if that abort call covers all the cases for https://issues.apache.org/jira/browse/SPARK-38277? Or do some of the other code paths not end up using that read-only path at all? Or would it be better just do explicitly clear the write batch anyway even if it is redundant with the abort call?

**Pull request closed without merging**
