### PR TITLE
[SPARK-12696] Backport Dataset Bug fixes to 1.6

### PR DESCRIPTION
**Pull request by marmbrus**
We've fixed a lot of bugs in master, and since this is experimental in 1.6 we should consider back porting the fixes.  The only thing that is obviously risky to me is 0e07ed3, we might try to remove that.

### CODE REVIEW

**Comment by marmbrus** [comment]
test this please

**Comment by marmbrus** [comment]
test this please

**Comment by rxin** [comment]
Changes LGTM

**Comment by liancheng** [comment]
LGTM. Double checked 0e07ed3, it's quite self contained and doesn't affect query execution code path. Should be safe to backport (I think fixing all the merge conflicts might be riskier). All other commits also look good.

**Comment by marmbrus** [comment]
Thanks, merging to branch-1.6

**Pull request closed without merging**
