### PR TITLE
[SQL] [outdated] SPARK-6981: Factor out SparkPlanner and QueryExecution from SQLContext

### PR DESCRIPTION
**Pull request by evacchi**
Dependent types add additional, unnecessary complexity to third-parties who may want to extend SQLContext with new rewriting strategies; moreover, HiveContext benefits from this simplifying change as well.

### CODE REVIEW

**Comment by marmbrus** [comment]
ok to test

**Comment by evacchi** [comment]
I may be mistaken here but my code does not change any of PySpark, and the stack trace seems to be pointing at a config error?

> akka.ConfigurationException: Logger specified in config can't be loaded [akka.event.slf4j.Slf4jLogger] due to [akka.event.Logging$LoggerInitializationException: Logger log1-Slf4jLogger did not respond with LoggerInitialized, sent instead [TIMEOUT]]

**Comment by evacchi** [comment]
I can confirm that the pyspark/sql/dataframe.py test case passes successfully on my branch.

**Comment by marmbrus** [comment]
Sorry, it is possible that you hit a flakey test.  If you fix the merge conflicts we can try again.

**Comment by evacchi** [comment]
I tried to rebase. Hope it's not a problem.

**Comment by rxin** [comment]
@evacchi seems like there is a merge problem. Can you try fix this (or submit a new pr)? Thanks.

**Comment by evacchi** [comment]
can you restart the Jenkins build? let's see if anything got messed up.

**Comment by rxin** [comment]
Jenkins, ok to test.

**Comment by evacchi** [comment]
cleaned up in PR #6122. Disregard this PR

**Pull request closed without merging**
