### PR TITLE
[SPARK-26134][CORE] Upgrading Hadoop to 2.7.4 to fix java.version problem

### PR DESCRIPTION
**Pull request by tasanuma**
## What changes were proposed in this pull request?

When I ran spark-shell on JDK11+28(2018-09-25), It failed with the error below.

```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.apache.hadoop.util.StringUtils.<clinit>(StringUtils.java:80)
	at org.apache.hadoop.security.SecurityUtil.getAuthenticationMethod(SecurityUtil.java:611)
	at org.apache.hadoop.security.UserGroupInformation.initialize(UserGroupInformation.java:273)
	at org.apache.hadoop.security.UserGroupInformation.ensureInitialized(UserGroupInformation.java:261)
	at org.apache.hadoop.security.UserGroupInformation.loginUserFromSubject(UserGroupInformation.java:791)
	at org.apache.hadoop.security.UserGroupInformation.getLoginUser(UserGroupInformation.java:761)
	at org.apache.hadoop.security.UserGroupInformation.getCurrentUser(UserGroupInformation.java:634)
	at org.apache.spark.util.Utils$.$anonfun$getCurrentUserName$1(Utils.scala:2427)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.util.Utils$.getCurrentUserName(Utils.scala:2427)
	at org.apache.spark.SecurityManager.<init>(SecurityManager.scala:79)
	at org.apache.spark.deploy.SparkSubmit.secMgr$lzycompute$1(SparkSubmit.scala:359)
	at org.apache.spark.deploy.SparkSubmit.secMgr$1(SparkSubmit.scala:359)
	at org.apache.spark.deploy.SparkSubmit.$anonfun$prepareSubmitEnvironment$9(SparkSubmit.scala:367)
	at scala.Option.map(Option.scala:146)
	at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:367)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:143)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:927)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:936)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end 3, length 2
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
	at java.base/java.lang.String.substring(String.java:1874)
	at org.apache.hadoop.util.Shell.<clinit>(Shell.java:52)
```
This is a Hadoop issue that fails to parse some java.version. It has been fixed from Hadoop-2.7.4(see [HADOOP-14586](https://issues.apache.org/jira/browse/HADOOP-14586)).

Note, Hadoop-2.7.5 or upper have another problem with Spark ([SPARK-25330](https://issues.apache.org/jira/browse/SPARK-25330)). So upgrading to 2.7.4 would be fine for now.

## How was this patch tested?
Existing tests.

### CODE REVIEW

**Comment by kiszk** [comment]
ok to test

**Comment by ueshin** [comment]
I guess we need to update `dev/deps/spark-deps-hadoop-2.7` file as well.

**Comment by ueshin** [comment]
cc @srowen

**Comment by dongjoon-hyun** [comment]
cc @dbtsai

**Comment by ueshin** [comment]
also cc @wangyum for the owner of [SPARK-25330](https://issues.apache.org/jira/browse/SPARK-25330).

**Comment by tasanuma** [comment]
Thanks all for your support. Updated PR addressing  @ueshin's comment.

**Comment by tasanuma** [comment]
Updated PR adding jetty-sslengine to `dev/deps/spark-deps-hadoop-2.7`. It is required by [HADOOP-12765](https://issues.apache.org/jira/browse/HADOOP-12765).

**Comment by kiszk** [comment]
retest this please

**Comment by ueshin** [comment]
Jenkins, retest this please.

**Review by wangyum — APPROVED** [review]
I think upgrade Hadoop to 2.7.4 is safe.

**Comment by kiszk** [comment]
LGTM

**Comment by HyukjinKwon** [comment]
LGTM2

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
Hi, @tasanuma .
We need to fix `IsolatedClientLoader.scala` and Kubernetes `README.md`, too. Could you update them in this PR?
- https://github.com/apache/spark/blob/master/sql/hive/src/main/scala/org/apache/spark/sql/hive/client/IsolatedClientLoader.scala#L68
```scala
val fallbackVersion = "2.7.3"
```

- https://github.com/apache/spark/blame/master/resource-managers/kubernetes/integration-tests/README.md#L110
```
-Phadoop-2.7 -Dhadoop.version=2.7.3 \
```

**Comment by tasanuma** [comment]
Thanks all for your reviews. Updated PR based on the @dongjoon-hyun's review.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by dongjoon-hyun** [comment]
Thank you all. Merged to `master`.

**Comment by tasanuma** [comment]
Thanks a lot!

**Comment by dongjoon-hyun** [comment]
Welcome, @tasanuma !

**Pull request closed without merging**
