### PR TITLE
[SPARK-7736] [core] [yarn] Make pyspark fail YARN app on failure.

### PR DESCRIPTION
**Pull request by vanzin**
The YARN backend doesn't like when user code calls `System.exit`,
since it cannot know the exit status and thus cannot set an
appropriate final status for the application.

So, for pyspark, avoid that call and instead throw an exception with
the exit code. SparkSubmit handles that exception and exits with
the given exit code, while YARN uses the exit code as the failure
code for the Spark app.

### CODE REVIEW

**Comment by vanzin** [comment]
Tested on real cluster. Not sure if it's worth it to add another test in YarnClusterSuite, since those are generally slow, but it would be easy to do so.

**Comment by vanzin** [comment]
Jenkins retest this please.

**Comment by andrewor14** [comment]
can you make this `[Core] [YARN]` so our [PR dashboard](https://spark-prs.appspot.com) displays this properly?

**Comment by vanzin** [comment]
Just ran into an issue where py4j threads are not daemon threads, so the YARN app is not exiting. Taking a look...

**Comment by srowen** [comment]
Seems pretty reasonable to me.

**Comment by vanzin** [comment]
retest this please

**Comment by vanzin** [comment]
retest this please

**Comment by vanzin** [comment]
I'm gonna merge this later today if there are no more comments.

**Comment by vanzin** [comment]
retest this please

**Comment by vanzin** [comment]
retest this please

**Comment by andrewor14** [comment]
retest this please

**Comment by vanzin** [comment]
This has passed tests already, all latest failures are due to flakiness...

retest this please

**Comment by vanzin** [comment]
retest this please

**Comment by vanzin** [comment]
jenkins, retest this please

**Comment by andrewor14** [comment]
retest this please

**Comment by vanzin** [comment]
retest this please

**Comment by vanzin** [comment]
retest this please

**Comment by vanzin** [comment]
retest this please

**Comment by vanzin** [comment]
wtf

**Comment by vanzin** [comment]
retest this please

**Comment by vanzin** [comment]
Streaming tests are really flaky... anyway, all interesting tests passed, so unless I hear otherwise, I'll merge this Monday morning.

**Pull request closed without merging**
