### PR TITLE
[SPARK-43004][CORE] Fix typo in ResourceRequest.equals()

### PR DESCRIPTION
**Pull request by thyecust**
vendor == vendor is always true, this is likely to be a typo.

### What changes were proposed in this pull request?

fix `vendor == vendor` with `that.vendor == vendor`, and `discoveryScript == discoveryScript` with `that.discoveryScript == discoveryScript`

### Why are the changes needed?

vendor == vendor is always true, this is likely to be a typo.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

By GitHub Actions.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Hey, I think all these typo PRs should have a test if this is an actual issue.

**Comment by HyukjinKwon** [comment]
And please file a JIRA if this is an issue, see also https://spark.apache.org/contributing.html

**Comment by bjornjorgensen** [comment]
@thyecust "vendor == vendor is always true"

In line 84 the val vendor field is declared as Optional[String], which means it can have a value of Some(String) when a vendor name is provided, or None when no vendor name is specified.

The failed test is not related to this, can you restart failed test?

**Review by srowen — CHANGES_REQUESTED** [review]
Yeah it's more of a bug fix, good catch. File a JIRA and link in the title please

**Comment by thyecust** [comment]
> Yeah it's more of a bug fix, good catch. File a JIRA and link in the title please

Thank you, this is my first time submitting code for Spark. I have applied for a JIRA account and I will file a bug later.

**Comment by HyukjinKwon** [comment]
cc @tgravescs

**Review by srowen — APPROVED** [review]

**Comment by srowen** [comment]
Merged to master/3.4/3.3/3.2

**Comment by tgravescs** [comment]
definitely looks like a typo, thanks for catching and fixing

**Pull request closed without merging**
