### PR TITLE
[SPARK-36546][SQL] Add array support to union by name

### PR DESCRIPTION
**Pull request by Kimahriman**
### What changes were proposed in this pull request?

This PR adds array of struct support to unionByName. It further tries to simplify some of the logic for re-projecting different types by creating a `mergeFields` method that can find the right method to merge various combinations of fields, currently structs or arrays, but could add maps in the future.

### Why are the changes needed?

Currently unionByName doesn't support arrays of structs or maps of structs. This adds support for the arrays of structs and should make it easy to add maps of structs support in the future.

### Does this PR introduce _any_ user-facing change?

New capability to unionByName with arrays of structs.

### How was this patch tested?

New unit tests

### CODE REVIEW

**Review by viirya — COMMENTED** [review]
We may need to update API doc of `unionByName` in `Dataset` too.

**Comment by Kimahriman** [comment]
> We may need to update API doc of `unionByName` in `Dataset` too.

Ah yep knew I forgot a comment to update somewhere

**Comment by Kimahriman** [comment]
Updated the Dataset docs. Kinda reworded since unionByName works on nested columns now even without allowMissingColumns enabled

**Review by HyukjinKwon — APPROVED** [review]

**Review by viirya — APPROVED** [review]

**Comment by viirya** [comment]
Thanks! Merging to master.

**Comment by Kimahriman** [comment]
Could/should this and https://github.com/apache/spark/pull/34166 be backported now that the 3.2.0 release was cut?

**Comment by viirya** [comment]
For an improvement, we don't backport usually.

**Comment by HyukjinKwon** [comment]
I think this kind of fix is clearly an improvement that affects behaviours so I won't backport either.

**Comment by Kimahriman** [comment]
The lack of 3.1.0 release threw off my timeline for when the last minor release was and how much was included in patch releases, sorry!

**Comment by HyukjinKwon** [comment]
> The lack of 3.1.0 release threw off my timeline for when the last minor release was and how much was included in patch releases, sorry!

It was from my mistake 😢

**Pull request closed without merging**
