### PR TITLE
[SPARK-6953] [PySpark] speed up python tests

### PR DESCRIPTION
**Pull request by davies**
This PR try to speed up some python tests:

```
tests.py                        144s -> 103s      -41s
mllib/classification.py   24s -> 17s          -7s
mllib/regression.py       27s -> 15s          -12s
mllib/tree.py                 27s  -> 13s         -14s
mllib/tests.py                64s -> 31s         -33s
streaming/tests.py       185s -> 84s        -101s
```

Considering python3, the total saving will be 558s (almost 10 minutes) (core, and streaming run three times, mllib runs twice).

During testing, it will show used time for each test file:

```
Run core tests ...
Running test: pyspark/rdd.py ... ok (22s)
Running test: pyspark/context.py ... ok (16s)
Running test: pyspark/conf.py ... ok (4s)
Running test: pyspark/broadcast.py ... ok (4s)
Running test: pyspark/accumulators.py ... ok (4s)
Running test: pyspark/serializers.py ... ok (6s)
Running test: pyspark/profiler.py ... ok (5s)
Running test: pyspark/shuffle.py ... ok (1s)
Running test: pyspark/tests.py ... ok (103s)   144s
```

### CODE REVIEW

**Comment by mengxr** [comment]
@davies Did you measure the speedup on each component?

**Comment by davies** [comment]
@mengxr I had update the difference in the description.

**Comment by mengxr** [comment]
MLlib changes look good to me.

**Comment by rxin** [comment]
I brought this up to date at https://github.com/apache/spark/pull/5605

**Pull request closed without merging**
