### PR TITLE
[SPARK-49450][SQL] Improve normalised collation names

### PR DESCRIPTION
**Pull request by mihailomilosevic2001**
### What changes were proposed in this pull request?
Change of removing case sensitivity and acent sensitivity specifiers from collation names

### Why are the changes needed?
We want collation names to be easier to understand from customer side.

### Does this PR introduce _any_ user-facing change?
Yes, collation names change.

### How was this patch tested?
Existing tests changes names.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by mihailom-db** [comment]
@dbatomic @stefankandic @uros-db @stevomitric @nikolamand-db @MaxGekk @ilicmarkodb I created this PR for updating collation names, please review

**Review by stevomitric — APPROVED** [review]
lgtm.

**Review by uros-db — COMMENTED** [review]
code changes are fine, but we might want to re-think whether we actually want to do this - makes more sense to me to leave everything as it is, in order to ensure backwards compatibility (e.g. when adding new specifiers) and improve readability

**Comment by mihailom-db** [comment]
Closing PR as change was decided not to be added.

**Pull request closed without merging**
