### PR TITLE
[SPARK-50387][SS] Update condition for timer expiry and relevant test

### PR DESCRIPTION
**Pull request by anishshri-db**
### What changes were proposed in this pull request?
Update condition for timer expiry and relevant test

### Why are the changes needed?
To ensure that the expiry and removal conditions are consistent. Also, we don't have to wait for an extra microbatch to expire timers in certain cases.

### Does this PR introduce _any_ user-facing change?
Yes

### How was this patch tested?
Added unit tests

```
[info] Run completed in 4 seconds, 638 milliseconds.
[info] Total number of tests run: 12
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 12, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
```

### Was this patch authored or co-authored using generative AI tooling?
No

### CODE REVIEW

**Comment by anishshri-db** [comment]
cc - @HeartSaVioR - PTAL, thx !

**Review by HeartSaVioR — APPROVED** [review]
+1 pending CI. Nice finding.

**Comment by HeartSaVioR** [comment]
https://github.com/anishshri-db/spark/actions/runs/11964792826/job/33357779164
I guess we have PySpark tests being impacted by this?

**Comment by anishshri-db** [comment]
@HeartSaVioR - tried to run this locally and this fails even with/without my change. Let me merge back from master once

**Comment by anishshri-db** [comment]
@HeartSaVioR - verified on master and I see the same assert locally as well. So don't think its related to this change

```
  File "/Users/anish.shrigondekar/spark/spark/python/pyspark/sql/utils.py", line 154, in call
    self.func(DataFrame(jdf, wrapped_session_jdf), batch_id)
  File "/Users/anish.shrigondekar/spark/spark/python/pyspark/sql/tests/pandas/test_pandas_transform_with_state.py", line 549, in check_results
    assert set(batch_df.sort("id").collect()) == {Row(id="a", timestamp="20")}
AssertionError
 SQLSTATE: 39000
```

@jingz-db @bogao007 - is this a known issue ? do we have a PR to fix this already ?

**Review by HeartSaVioR — APPROVED** [review]
+1 again (the test is fixed, thanks!)

**Comment by HeartSaVioR** [comment]
Thanks! Merging to master.

**Pull request closed without merging**
