### PR TITLE
[SPARK-19320][MESOS][WIP]allow specifying a hard limit on number of gpus required in each spark executor when running on mesos

### PR DESCRIPTION
**Pull request by yanji84**
## What changes were proposed in this pull request?

Currently, spark only allows specifying gpu resources as an upper limit, this adds a new conf parameter to allow specifying a hard limit on the number of gpu cores. If this hard limit is greater than 0, it will override the effect of spark.mesos.gpus.max

## How was this patch tested?

Tests pending

Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Comment by klueska** [comment]
Can you give a bit more context on what this new parameter is supposed to enforce? Maybe it's just the same of the parameter that's confusing me.

**Comment by grisaitis** [comment]
@klueska it enforces a guaranteed number of GPUs allocated to the task, like other resource guarantees (e.g. cpu, memory). 

The max GPU parameter is not a guarantee; you can specify "spark.mesos.gpus.max" to a number greater than 1 and still get zero GPUs allocated. This parameter guarantees that the requested number of GPUs are allocated.

**Comment by vanzin** [comment]
@yanji84 this PR is not correct, can you close it and open a new one with only your changes?

**Comment by gatorsmile** [comment]
We are closing it due to inactivity. please do reopen if you want to push it forward. Thanks!

**Pull request closed without merging**
