### PR TITLE
[SPARK-46047][BUILD][SQL] Fix the usage of Scala 2.13 deprecated APIs and make the usage of Scala 2.13 deprecated APIs as compilation error

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr fixes the remaining usage of Scala 2.13 deprecated APIs and converts the following compilation rule from `silent ` to a compilation `error` to avoid using the related Scala 2.13 deprecated APIs.

```
-Wconf:msg=^(?=.*?method|value|type|object|trait|inheritance)(?=.*?deprecated)(?=.*?since 2.13).+$:s
```

to

```
-Wconf:msg=^(?=.*?method|value|type|object|trait|inheritance)(?=.*?deprecated)(?=.*?since 2.13).+$:e
```

From now on, new cases will  become compilation errors, and developers need to avoid using them》

### Why are the changes needed?
Avoid using Scala 2.13 deprecated APIs.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass GitHub Actions

### Was this patch authored or co-authored using generative AI tooling?
No

### CODE REVIEW

**Comment by LuciferYang** [comment]
cc @srowen @HyukjinKwon @dongjoon-hyun 

Another option is to change this compilation rule to
```
-Wconf:msg=^(?=.*?method|value|type|object|trait|inheritance)(?=.*?deprecated)(?=.*?since 2.13).+$:e
```

which will convert the corresponding compilation `warning` into a compilation `error`, and Scala 2.13 deprecated APIs will be prohibited. This can save the trouble of repeated clean-up. Do you think this is a better approach, or the current PR approach is better?

**Review by dongjoon-hyun — COMMENTED** [review]
Let's make it fails. +1 for the alternative, `error`, approach, @LuciferYang .

**Comment by HyukjinKwon** [comment]
Yeah in principle I agree with making it failed .. just wonder how much we should fix them ... If we should, probably we should just fix them in one go ...

**Comment by LuciferYang** [comment]
There should not be many bad cases left, Ok, I will fix the remaining parts in this PR and convert this rule into compilation error.

**Comment by dongjoon-hyun** [comment]
Thank you!

> There should not be many bad cases left, Ok, I will fix the remaining parts in this PR and convert this rule into compilation error.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM (Pending CIs).

**Comment by LuciferYang** [comment]
Thanks @dongjoon-hyun @HyukjinKwon ~ I will merge this PR as soon as possible and rebase the code locally before merging to perform another compilation check

**Comment by LuciferYang** [comment]
Merged into master for Spark 4.0. Thanks @HyukjinKwon @dongjoon-hyun ~

**Pull request closed without merging**
