### PR TITLE
[SPARK-41196] [CONNECT] Homogenize the protobuf version across the Spark connect server to use the same major version.

### PR DESCRIPTION
**Pull request by grundprinzip**
### What changes were proposed in this pull request?

This patch homogenize the protobuf versions between the Spark Connect server and Python clients to use the same major version.

### Why are the changes needed?
Compatibility

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Existing UT.

### CODE REVIEW

**Comment by amaliujia** [comment]
@grundprinzip 

You need to re-generated the protobuf for Python side.

**Comment by amaliujia** [comment]
Also need to make the Scala side version consistent https://github.com/apache/spark/blob/master/connector/connect/pom.xml#L35?

**Review by hvanhovell — APPROVED** [review]
LGTM

**Comment by amaliujia** [comment]
LGTM

**Pull request closed without merging**
