### PR TITLE
[SPARK-42158][SQL][3.4] Integrate _LEGACY_ERROR_TEMP_1003 into FIELD_NOT_FOUND

### PR DESCRIPTION
**Pull request by itholic**
### What changes were proposed in this pull request?

backport for https://github.com/apache/spark/pull/39706

### Why are the changes needed?

We should want to include PRs related to error classes into Spark 3.4.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

The CI should pass.

### CODE REVIEW

**Review by MaxGekk — APPROVED** [review]
Waiting for CI.

**Comment by MaxGekk** [comment]
+1, LGTM. Merging to 3.4.
Thank you, @itholic.

**Comment by cloud-fan** [comment]
It seems this is not a backport of https://github.com/apache/spark/pull/39706 . The changes are different

**Comment by HyukjinKwon** [comment]
@itholic seems like you picked a wrong commit

**Review by MaxGekk — CHANGES_REQUESTED** [review]
@itholic Could you double check the picked commit, please.

**Comment by itholic** [comment]
Reopened: https://github.com/apache/spark/pull/39859

**Pull request closed without merging**
