### PR TITLE
[SPARK-49221][BUILD] Fix sbt compilation warnings related to `Regular tasks always evaluate task dependencies (.value) regardless of if expressions`

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This PR changes to use `taskDyn` to dynamically define `task` based on the value of `moduleName.value.contains("assembly")` in order to fix compilation warnings:

```
[warn] /home/runner/work/spark/spark/project/SparkBuild.scala:1554:77: value lookup of `/` inside an `if` expression
[warn] 
[warn] problem: `/.value` is inside an `if` expression of a regular task.
[warn]   Regular tasks always evaluate task dependencies (`.value`) regardless of `if` expressions.
[warn] solution:
[warn]   1. Use a conditional task `Def.taskIf(...)` to evaluate it when the `if` predicate is true or false.
[warn]   2. Or turn the task body into a single `if` expression; the task is then auto-converted to a conditional task. 
[warn]   3. Or make the static evaluation explicit by declaring `/.value` outside the `if` expression.
[warn]   4. If you still want to force the static lookup, you may annotate the task lookup with `@sbtUnchecked`, e.g. `(/.value: @sbtUnchecked)`.
[warn]   5. Add `import sbt.dsl.LinterLevel.Ignore` to your build file to disable all task linting.
[warn]     
[warn]         val replClasspathes = (LocalProject("connect-client-jvm") / Compile / dependencyClasspath)
[warn]                                                                             ^
[warn] one warning found
```

### Why are the changes needed?
Fix compilation warnings in the GA compilation log

- https://github.com/apache/spark/actions/runs/10365742495/job/28693551621

image

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
- Pass Github Actions
- Check the GA compilation log, and ensure there are no warnings as mentioned above.
- Manual check

```
build/sbt clean assembly/package -Phive   
ls -l assembly/target/scala-2.13/jars/connect-repl 
```

Before and after this PR, the content under the `assembly/target/scala-2.13/jars/connect-repl ` directory remains consistent.

### Was this patch authored or co-authored using generative AI tooling?
No

### CODE REVIEW

**Comment by LuciferYang** [comment]
cc @HyukjinKwon

**Review by dongjoon-hyun — COMMENTED** [review]
Thank you a lot, @LuciferYang . I also hit this issue before. :)

**Comment by dongjoon-hyun** [comment]
Since this is related to the connect module, I'll leave this to @HyukjinKwon .

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by LuciferYang** [comment]
Thanks @dongjoon-hyun and @HyukjinKwon

**Pull request closed without merging**
