### PR TITLE
[DO-NOT-MERGE] Investigate if PR 18320 causes R tests flaky

### PR DESCRIPTION
**Pull request by HyukjinKwon**
## What changes were proposed in this pull request?

This is just based on my wild guess. Please allow me to test before/after. It is hard to reproduce in my Mac and other OSs too.

## How was this patch tested?

N/A

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
These 6 tests are before that PR.

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
test this please

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
These three tests are R-only tests after that PR.

**Comment by HyukjinKwon** [comment]
these three tests are full tests after that PR.

**Comment by felixcheung** [comment]
hmm... should i revert it for now then it sounds like?

**Comment by HyukjinKwon** [comment]
Yes... it looks so... could I ask twenty minutes?  I can't reproduce this on ...

CentOS Linux release 7.3.1611 (Core) / R version 3.4.0 / Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
macOS 10.12.3 (16D32) / R version 3.4.0 / Java(TM) SE Runtime Environment (build 1.8.0_45-b14)

but now I am running on ...

Ubuntu 14.04 LTS / R version 3.3.1 / Java(TM) SE Runtime Environment (build 1.8.0_131-b11)

Just want to be sure on this.

**Comment by felixcheung** [comment]
sure. I'll check back in an hour or so. I think we are not in a hurry but seems like lots of R tests are failing

**Comment by felixcheung** [comment]
btw, is it really `10`, not `-10`?

errno.h
#define ECHILD          10      /* No child processes */

which would seems related. perhaps it happens when it tries to kill the child but the child is gone

**Comment by felixcheung** [comment]
I suspect if there is a race condition here - if child can somehow gracefully exit by itself then there is nothing to kill, right?
```
        if (unserialize(data) == exitCode) {
 +          # If so, we terminate this child.
 +          tools::pskill(child, tools::SIGUSR1)
 +        }
```

**Comment by HyukjinKwon** [comment]
Thanks for good hints! I will take a look and yea, it sounds worth checking.

One thing I wonder is though, I ran R tests 10-ish times on CentOS and Mac OS and 2 times on Ubuntu just now but I can't reproduce this. Should we maybe go reverting this for now? I will open a PR for this again after being reverted.

Sounds I only can reproduce this with Jenkins and I need some debugs with it ...

**Comment by felixcheung** [comment]
reverted in master. JIRA reopened.https://issues.apache.org/jira/browse/SPARK-21093

**Comment by HyukjinKwon** [comment]
Thank you @felixcheung.

**Comment by HyukjinKwon** [comment]
I am closing this.

**Pull request closed without merging**
