### PR TITLE
[WIP][test-java11] Test Hadoop 2.7 with JDK 11

### PR DESCRIPTION
**Pull request by wangyum**
### What changes were proposed in this pull request?

This PR test Hadoop 2.7 with JDK 11 on our jenkins.

### CODE REVIEW

**Comment by wangyum** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
The test cases should be fixed as of https://github.com/apache/spark/commit/65a189c7a1ddceb8ab482ccc60af5350b8da5ea5

**Comment by wangyum** [comment]
Thank you @HyukjinKwon

**Comment by wangyum** [comment]
All Failed Tests:
```scala
org.apache.spark.sql.kafka010.KafkaSinkMicroBatchStreamingSuite.(It is not a test it is a sbt.testing.SuiteSelector)
org.apache.spark.sql.kafka010.KafkaDelegationTokenSuite.(It is not a test it is a sbt.testing.SuiteSelector)
```

How to reproduce:
```shell
export JAVA_HOME=/usr/lib/jdk-11.0.3
export PATH=$JAVA_HOME/bin:$PATH

build/sbt "sql-kafka-0-10/test-only *.KafkaSinkMicroBatchStreamingSuite" -Phadoop-3.2 -Dhadoop.version=2.7.4 -Dcurator.version=2.7.1
build/sbt "sql-kafka-0-10/test-only *.KafkaDelegationTokenSuite" -Phadoop-3.2 -Dhadoop.version=2.7.4 -Dcurator.version=2.7.1
```

**Comment by wangyum** [comment]
@HyukjinKwon @BryanCutler It seems failed tests related to https://issues.apache.org/jira/browse/ARROW-5412?

**Comment by BryanCutler** [comment]
right, I think for JDK >= 9 this needs to be set "-Dio.netty.tryReflectionSetAccessible=true". This was due to some Netty API that Arrow started using. I can look into it and try to figure out what we should do for Spark.

**Comment by BryanCutler** [comment]
Oh, I saw you just added it as a property in the pom. Hopefully that should do the trick.

**Comment by BryanCutler** [comment]
retest this please

**Comment by wangyum** [comment]
@BryanCutler It seems not working:
```shell
export JAVA_HOME=/usr/lib/jdk-11.0.3
export PATH=$JAVA_HOME/bin:$PATH

build/sbt "sql/test-only *.ArrowConvertersSuite" -Phadoop-3.2 -Dio.netty.tryReflectionSetAccessible=true
```

**Comment by dongjoon-hyun** [comment]
@wangyum . Arrow broke all tests. I'm working in the following PR. After fixing that, I'll ping you here.
- https://github.com/apache/spark/pull/26552

**Comment by wangyum** [comment]
Thank you @dongjoon-hyun

**Comment by wangyum** [comment]
retest this please

**Comment by wangyum** [comment]
All Failed Tests:
```scala
org.apache.spark.sql.kafka010.KafkaSinkMicroBatchStreamingSuite.(It is not a test it is a sbt.testing.SuiteSelector)
org.apache.spark.sql.kafka010.KafkaDelegationTokenSuite.(It is not a test it is a sbt.testing.SuiteSelector)
```

How to reproduce:
```shell
export JAVA_HOME=/usr/lib/jdk-11.0.3
export PATH=$JAVA_HOME/bin:$PATH

build/sbt "sql-kafka-0-10/test-only *.KafkaSinkMicroBatchStreamingSuite" -Phadoop-3.2 -Dhadoop.version=2.7.4 -Dcurator.version=2.7.1
build/sbt "sql-kafka-0-10/test-only *.KafkaDelegationTokenSuite" -Phadoop-3.2 -Dhadoop.version=2.7.4 -Dcurator.version=2.7.1
```
The failed tests may be related to https://issues.apache.org/jira/browse/HADOOP-12911
cc @plusplusjiajia @AngersZhuuuu

**Comment by wangyum** [comment]
retest this please

**Comment by wangyum** [comment]
retest this please

**Comment by wangyum** [comment]
The issue fixed by https://github.com/apache/spark/pull/26594

**Comment by wangyum** [comment]
Another issue:
```
[b_carmel@carmeldevour002-715563 spark-3.0.0-bin]$ bin/spark-sql
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/b_carmel/yumwang/spark-3.1.0-SNAPSHOT-bin-benchmark-bloomfilter/jars/slf4j-log4j12-1.7.30.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/apache/releases/hadoop-2.7.3.2.6.4-ebay.1/share/hadoop/common/lib/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/b_carmel/yumwang/spark-3.1.0-SNAPSHOT-bin-benchmark-bloomfilter/jars/spark-unsafe_2.12-3.1.0-SNAPSHOT.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "DataStreamer for file /tmp/hive-b_carmel/b_carmel/ff396890-3a46-4f2e-a93b-91de0eeefe0b/inuse.info" java.lang.NoSuchMethodError: 'sun.misc.Cleaner sun.nio.ch.DirectBuffer.cleaner()'
	at org.apache.hadoop.crypto.CryptoStreamUtils.freeDB(CryptoStreamUtils.java:41)
	at org.apache.hadoop.crypto.CryptoInputStream.freeBuffers(CryptoInputStream.java:679)
	at org.apache.hadoop.crypto.CryptoInputStream.close(CryptoInputStream.java:315)
	at java.base/java.io.FilterInputStream.close(FilterInputStream.java:179)
	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.closeStream(DFSOutputStream.java:737)
	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.closeInternal(DFSOutputStream.java:685)
	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.run(DFSOutputStream.java:680)
Exception in thread "DataStreamer for file /user/b_carmel/.sparkStaging/application_1595573410068_7264/__spark_libs__7269177261298078316.zip" java.lang.NoSuchMethodError: 'sun.misc.Cleaner sun.nio.ch.DirectBuffer.cleaner()'
	at org.apache.hadoop.crypto.CryptoStreamUtils.freeDB(CryptoStreamUtils.java:41)
	at org.apache.hadoop.crypto.CryptoInputStream.freeBuffers(CryptoInputStream.java:679)
	at org.apache.hadoop.crypto.CryptoInputStream.close(CryptoInputStream.java:315)
	at java.base/java.io.FilterInputStream.close(FilterInputStream.java:179)
	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.closeStream(DFSOutputStream.java:737)
	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.closeInternal(DFSOutputStream.java:685)
	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.run(DFSOutputStream.java:680)
Exception in thread "DataStreamer for file /user/b_carmel/.sparkStaging/application_1595573410068_7264/__spark_conf__.zip" java.lang.NoSuchMethodError: 'sun.misc.Cleaner sun.nio.ch.DirectBuffer.cleaner()'
	at org.apache.hadoop.crypto.CryptoStreamUtils.freeDB(CryptoStreamUtils.java:41)
	at org.apache.hadoop.crypto.CryptoInputStream.freeBuffers(CryptoInputStream.java:679)
	at org.apache.hadoop.crypto.CryptoInputStream.close(CryptoInputStream.java:315)
	at java.base/java.io.FilterInputStream.close(FilterInputStream.java:179)
	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.closeStream(DFSOutputStream.java:737)
	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.closeInternal(DFSOutputStream.java:685)
	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.run(DFSOutputStream.java:680)
Spark master: yarn, Application Id: application_1595573410068_7264
```
More details: https://issues.apache.org/jira/browse/HADOOP-12760

**Pull request closed without merging**
