### PR TITLE
[SQL][DOC][MINOR] Add (Scala-specific) and (Java-specific)

### PR DESCRIPTION
**Pull request by jaceklaskowski**
## What changes were proposed in this pull request?

Adds (Scala-specific) and (Java-specific) to Scaladoc.
## How was this patch tested?

local build

### CODE REVIEW

**Comment by srowen** [comment]
I think this kind of thing is fine to call out, but we haven't used this convention, quite, elsewhere. The APIs are all "Scala-specific" unless otherwise noted. Even then they're callable from Java, just not very conveniently. There are some methods that exist specifically to make calling from Java simpler. In other cases I've just seen this described with a sentence of prose that says this is a convenience method for Java callers. That might be more explanatory than just writing "Java-specific", because indeed even those are callable from Scala and aren't that specific to Java.

I'd just note the methods that are Java-friendly, and borrow a sentence from existing doc of similar methods.

**Comment by jaceklaskowski** [comment]
Frankly, I'd not have bothered with the changes if I had not seen them elsewhere. See http://spark.apache.org/docs/latest/api/scala/index.html#org.apache.spark.sql.Dataset and look for `foreach` and `foreachPartition` for (Java-specific) while http://spark.apache.org/docs/latest/api/scala/index.html#org.apache.spark.sql.Encoders$ and `javaSerialization` /  `kryo` for (Scala-specific). I have seen examples with both in one source like http://spark.apache.org/docs/latest/api/scala/index.html#org.apache.spark.sql.RelationalGroupedDataset. That was the main reason while the other was to understand why there are two different variants of the same method (and then it clicked but only when I'd seen the other examples).

**Comment by srowen** [comment]
OK fair enough LGTM

**Comment by jaceklaskowski** [comment]
@srowen, anyone you'd recommend to accept the PR (after you accepted)?

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
