### PR TITLE
[SPARK-23731][SQL] FileSourceScanExec throws NullPointerException in subexpression elimination

### PR DESCRIPTION
**Pull request by jaceklaskowski**
## What changes were proposed in this pull request?

Avoids ("fixes") a NullPointerException in subexpression elimination for subqueries with FileSourceScanExec.

## How was this patch tested?

Local build. No new tests as I could not reproduce it other than using the query and data under NDA. Waiting for Jenkins.

### CODE REVIEW

**Comment by kiszk** [comment]
retest this please

**Comment by kiszk** [comment]
I think that this problem does not depend on data. Can you create a test case by modifying the query slightly with different column names?

**Comment by gatorsmile** [comment]
What is the test case?

**Comment by jaceklaskowski** [comment]
I spent over 2 days applying different modifications to the query hoping I could cut the number of `CASE WHEN`s and other projections, but noticed no correlation between the number or their "types". I'll see if renaming the columns leads to the issue and submit a test case. Thanks for your support!

**Comment by jaceklaskowski** [comment]
BTW, I've just realized that even without the issue it's clear that creating a new `FileSourceScanExec` will end up with a NPE from the `supportsBatch` field.

**Review by srowen — APPROVED** [review]

**Comment by gatorsmile** [comment]
We are not able to merge it without a valid test case. We need to understand the root cause why `relation` can be null. 

@HyukjinKwon If you can help, please try to create a test case.

**Comment by HyukjinKwon** [comment]
Sure. Let me give a shot to reproduce it.

**Comment by mgaido91** [comment]
@HyukjinKwon thanks for your great analysis. I agree with you that the proposed fix is more a "workaround" than a real fix for the issue we have here.

The main problem here as you pointed out is that we have a bad (invalid?) `FileSourceScanExec` on the executors. Probably this has never been an issue as on the executors we accessed only some properties which were correctly populated and we assumed that the other operation would have been performed only on driver side.

I think the cleanest approach (not sure it is entirely feasible) would be to choose one of the following option:

 - check that all exec expression (in this case `FileSourceScanExec`) are working properly both on driver and executor side;
 - define which operation/attributes can be accessed on executor side too and which only on driver side, document it and enforce it (if feasible).

What do you think?

**Comment by HyukjinKwon** [comment]
cc @hvanhovell too

**Comment by cloud-fan** [comment]
@HyukjinKwon good analysis!

Currently Spark is a little messy about what shall be serialized and sent to executors. Sometimes we just send an entire query tree but only read a few properties of it.

It seems to me it would be better to always do codegen at driver side, to avoid complex expression/plan operations at executor side.(not sure if it's possible, cc @viirya @rednaxelafx @kiszk).

For this particular problem, I think we can just change these `val`s to `lazy val` or `def` in `FileSourceScanExec`, with a unit test.

**Comment by viirya** [comment]
@HyukjinKwon @cloud-fan Thanks for pinging me, sorry for replying late. Yeah I looked at the final fixing at #21815, it looks good for a fixing at this particular problem.

> It seems to me it would be better to always do codegen at driver side, to avoid complex expression/plan operations at executor side.(not sure if it's possible, cc ...).

I do agree that this sounds better. A major part of executor codegen is unsafe codegen classes such as unsafe projection. Most of them if not all are not serializable for now. In order to do codegen at driver side at all, we may need to make them serializable. Is it worth doing this?

**Pull request closed without merging**
