### PR TITLE
SPARK-5059 - create README.md

### PR DESCRIPTION
**Pull request by xhudik**
Let's create a short README.md file to get a basic understanding of Spark REPL subproject

### CODE REVIEW

**Comment by markhamstra** [comment]
Duplicating documentation is a good way for things to get out of sync.  If we really need a README.md here, I'd prefer that it be little more than a link to where spark-shell usage is already documented -- e.g. [Interactive Analysis with the Spark Shell](http://spark.apache.org/docs/latest/quick-start.html#interactive-analysis-with-the-spark-shell).

**Comment by xhudik** [comment]
since Spark REPL is just a mirror/clone I don't think it is a good idea to have some real documentation. I do think simple information that it is actually clone with a link to original project should be enough.

**Comment by nchammas** [comment]
To second @markhamstra's comment, this is how [the README for the EC2 scripts](https://github.com/apache/spark/blob/master/ec2/README) is written: A simple link to where the documentation actually is.

**Comment by srowen** [comment]
This is also not related to SPARK-5059.

**Comment by srowen** [comment]
I think we should either close this PR or change it to imitate the EC2 README.md as a pointer to http://spark.apache.org/docs/latest/quick-start.html#interactive-analysis-with-the-spark-shell  (The proposed text also has some typos anyway.)

**Pull request closed without merging**
