### PR TITLE
[SPARK-12041] [ML] [PySpark] Add columnSimilarities to IndexedRowMatrix

### PR DESCRIPTION
**Pull request by vectorijk**
Add `columnSimilarities` to IndexedRowMatrix for PySpark spark.mllib.linalg.

### CODE REVIEW

**Comment by vectorijk** [comment]
cc @yanboliang

**Comment by yanboliang** [comment]
LGTM @mengxr

**Comment by vectorijk** [comment]
cc @mengxr

**Comment by thunterdb** [comment]
@vectorijk thanks for the PR, it looks good to me. cc @jkbradley

**Comment by jkbradley** [comment]
LGTM  I'll just run the tests once more before merging

**Comment by jkbradley** [comment]
Merging with master

**Comment by jkbradley** [comment]
Thanks for the PR!

**Pull request closed without merging**
