### PR TITLE
[MLLIB][WIP] SPARK-4638: Kernels feature for MLLIB

### PR DESCRIPTION
**Pull request by mandar2812**
1) Class hierarchy for SVM Kernels, with unit tests.
2) Entropy based subset selection for low rank approximation of Large Kernel Matrices, with unit tests.
3) Kernels for density estimation, with 'plug in' based optimum bandwidth selection, with unit tests.

### CODE REVIEW

**Comment by dbtsai** [comment]
jenkins, please test this.

**Comment by debasish83** [comment]
@dbtsai @mandar2812 I found the abstraction for kernel as explained in my PR https://github.com/apache/spark/pull/6213 more generic in practical use-cases compared to the usual interface available in scikit-learn...It will be great if we can come up with a strategy such that this PR calls IndexedRowMatrix.rowSimilarity to get the kernel from the data as represented with RDD[LabeledPoint]

**Comment by dbtsai** [comment]
jenkins, please test this.

**Comment by dbtsai** [comment]
ok to test

**Comment by dbtsai** [comment]
jenkins, ok to test

**Comment by mandar2812** [comment]
Making scala style changes and optimizations and updating pull request asap

**Comment by dbtsai** [comment]
jenkins, ok to test

**Comment by tn531** [comment]
@mandar2812 any status on this PR?

**Comment by mandar2812** [comment]
Yes, I will update this PR by the 20th of December 2015.

**Comment by rxin** [comment]
I'm going to close this pull request. If this is still relevant and you are interested in pushing it forward, please open a new pull request. Thanks!

**Comment by dale-chang91** [comment]
What is the result of this pull request? I can't seem to find the code in the code base anywhere

**Comment by mandar2812** [comment]
It didn't make it into spark. Instead I started the [DynaML](https://github.com/transcendent-ai-labs/DynaML) project and made kernels a key module of it, along with spark support.

**Pull request closed without merging**
