### PR TITLE
[WIP][SPARK-29250][BUILD][test-hadoop3.2][test-maven] Upgrade to Hadoop 3.2.1

### PR DESCRIPTION
**Pull request by HyukjinKwon**
### What changes were proposed in this pull request?

This PR aims to upgrade Hadoop version from 3.2.0 to 3.2.1 in `hadoop-3.2` profile. This is https://github.com/apache/spark/pull/25932.

### Why are the changes needed?

Hadoop 3.2.1 has 493 patches including client bug fixes and improvements.
- https://hadoop.apache.org/docs/r3.2.1/hadoop-project-dist/hadoop-common/release/3.2.1/CHANGELOG.3.2.1.html

### Does this PR introduce any user-facing change?

No.

### How was this patch tested?

Pass the Jenkins with the existing tests.

For the dependency, this PR is tested on both JDK8/JDK11. There is no difference based on JDK versions.

### CODE REVIEW

**Comment by srowen** [comment]
I think you'll have to vary the guava version that we override with, to 27.0-jre IIRC, in the Hadoop 3.2 profile

**Comment by HyukjinKwon** [comment]
Sure, thanks Sean. Let me take a look

**Comment by HyukjinKwon** [comment]
Hm, seems it's difficult to fix:

```
  java.lang.IllegalAccessError: tried to access method com.google.common.collect.Iterators.emptyIterator()Lcom/google/common/collect/UnmodifiableIterator; from class org.apache.hadoop.hive.ql.exec.FetchOperator
  at org.apache.hadoop.hive.ql.exec.FetchOperator.<init>(FetchOperator.java:108)
  at org.apache.hadoop.hive.ql.exec.FetchTask.initialize(FetchTask.java:87)
  at org.apache.hadoop.hive.ql.Driver.compile(Driver.java:541)
  at org.apache.hadoop.hive.ql.Driver.compileInternal(Driver.java:1317)
  at org.apache.hadoop.hive.ql.Driver.runInternal(Driver.java:1457)
  at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1237)
  at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1227)
  at org.apache.spark.sql.hive.client.HiveClientImpl.$anonfun$runHive$1(HiveClientImpl.scala:820)
  at org.apache.spark.sql.hive.client.HiveClientImpl.$anonfun$withHiveState$1(HiveClientImpl.scala:321)
  at org.apache.spark.sql.hive.client.HiveClientImpl.liftedTree1$1(HiveClientImpl.scala:255)
  ...
```

Hive 2.3.6 itself looks needing a fix but seems there's no plan.

**Comment by HyukjinKwon** [comment]
Hm, I can't see the easy way to work around too. Closing for now.

**Pull request closed without merging**
