### PR TITLE
[SPARK-20577][DOC][CORE]Add REST API Documentation in Cluster Mode.

### PR DESCRIPTION
**Pull request by guoxiaolongzte**
## What changes were proposed in this pull request?

Add REST API Documentation in Cluster Mode.
Include:
  Submit an application to the Master with parameters specified in the request.The request is assumed to be a [[SubmitRestProtocolRequest]] in the form of JSON.If the request is successfully processed, return an appropriate response to the client indicating so.

  If a submission ID is specified in the URL, have the Master kill the corresponding
Driver and return an appropriate response to the client.

   If a submission ID is specified in the URL, request the status of the corresponding
Driver from the Master and include it in the response.

## How was this patch tested?

manual tests

Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Comment by jerryshao** [comment]
I remember these REST APIs are not public APIs, it is only used for SparkSubmit internally. shall we add the docs about them?

**Comment by guoxiaolongzte** [comment]
@jerryshao 
Yes, we now have the need to use REST APIs to submit SPARK jobs.

We submit the task of submitting a application to a WEB system, which is designed to manage the functions of the submitted job and set specific parameters and related configurations for different jobs. The WEB management system interacts with the spark cluster. The REST interface is The most convenient.

We have now used these REST APIS to meet our needs. But the current lack of official documents related description, I have learned through their own research and research to understand these interfaces.

**Comment by srowen** [comment]
He is saying you are not intended to call this API.

**Comment by guoxiaolongzte** [comment]
@srowen 
I'm sorry, I did not understand what you meant. Can you give me a detailed analysis? Thank you.

**Comment by srowen** [comment]
It is not documented because it is not something you should call. You do so at your own risk. Documentation is appropriate for supported APIs only.

**Comment by guoxiaolongzte** [comment]
In fact, the three api is three servlets, submitRequestServlet, killRequestServlet, statusRequestServlet. Theoretically should be open to enhance the function of spark.
As for why not open, I still difficult to understand.

**Comment by guoxiaolongzte** [comment]
@jerryshao
I said that the use of the scene is real, do you agree?

**Comment by jerryshao** [comment]
I think @srowen already clarified it very clearly, you can use it at your own risk, but to make it public and add to the doc should be well considered.

**Comment by guoxiaolongzte** [comment]
Where is the risk? High concurrency? Transaction processing? This is where I am puzzled.

**Comment by srowen** [comment]
Nobody is suggesting it doesn't work. It is at least only known to work to support internal callers. It is subject to changes in the API. A public API in contrast needs to retain compatibility over longer periods. This is not something it seems the project wants to guarantee. Only public APIs need docs and this isn't.

**Comment by srowen** [comment]
Unless somebody says this isn't a private API, let's close this PR

**Comment by guoxiaolongzte** [comment]
ok,thanks.

**Pull request closed without merging**
