### PR TITLE
[MINOR][SQL]remove unuse import class

### PR DESCRIPTION
**Pull request by heary-cao**
## What changes were proposed in this pull request?

this PR describe remove the import class that are unused.

## How was this patch tested?

N/A

### CODE REVIEW

**Comment by srowen** [comment]
On the one hand, we don't normally just make a change to remove unused imports. But it's a good idea once in a while to clean up. Would you actually try to find all of them? at least, in several whole modules rather than part of one.

**Comment by heary-cao** [comment]
ok, i will do it.

**Comment by jerryshao** [comment]
Jenkins, test this please.

**Review by srowen — APPROVED** [review]

**Comment by jerryshao** [comment]
What about other components, here you only fixed sql and core module.

**Comment by heary-cao** [comment]
wait, I'm still looking for it.

**Comment by jerryshao** [comment]
Personally I'm not fond of such fix, this will break lots of existing PRs and force them to rebase again. Usually this could be addressed when fixing other issues. IMHO I don't encourage such PRs.

**Comment by srowen** [comment]
I'm neutral. Once in a while a cleanup seems helpful, not all the time. I am a little more receptive to people without much contribution history. But yeah I do not want to review things like this regularly. We have a lot of really minor PRs coming through

**Comment by heary-cao** [comment]
@srowen, @jerryshao several other components, Include spark streaming, launcher,graphx,core,mllib,mllib-local， except for their tests. 
thanks.

**Comment by jerryshao** [comment]
Jenkins, test this please.

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
ok to test

**Comment by ash211** [comment]
A check for unused imports should be added to scalastyle to prevent these from creeping back in.  If this PR was accompanied with that check (failing before, now passing) I think the merge conflicts are worth it to permanently fix the problem.

**Comment by srowen** [comment]
I didn't think scalastyle could do that? didn't see a rule at http://www.scalastyle.org/rules-dev.html

**Comment by srowen** [comment]
I'm going to merge it as a cleanup but yeah let's not do these often.
I would favor adding a style check for this if one can be found, but don't see it in scalastyle.

**Pull request closed without merging**
