### PR TITLE
[SPARK-15808] [SQL] File Format Checking When Appending Data

### PR DESCRIPTION
**Pull request by gatorsmile**
#### What changes were proposed in this pull request?

**Issue:** Got wrong results or strange errors when append data to a table with mismatched file format. 

_Example 1: PARQUET -> CSV_

``` Scala
createDF(0, 9).write.format("parquet").saveAsTable("appendParquetToOrc")
createDF(10, 19).write.mode(SaveMode.Append).format("orc").saveAsTable("appendParquetToOrc")
```

Error we got: 

```
Job aborted due to stage failure: Task 0 in stage 2.0 failed 1 times, most recent failure: Lost task 0.0 in stage 2.0 (TID 2, localhost): java.lang.RuntimeException: file:/private/var/folders/4b/sgmfldk15js406vk7lw5llzw0000gn/T/warehouse-bc8fedf2-aa6a-4002-a18b-524c6ac859d4/appendorctoparquet/part-r-00000-c0e3f365-1d46-4df5-a82c-b47d7af9feb9.snappy.orc is not a Parquet file. expected magic number at tail [80, 65, 82, 49] but found [79, 82, 67, 23]
```

_Example 2: Json -> CSV_

``` Scala
createDF(0, 9).write.format("json").saveAsTable("appendJsonToCSV")
createDF(10, 19).write.mode(SaveMode.Append).format("parquet").saveAsTable("appendJsonToCSV")
```

No exception, but wrong results:

```
+----+----+
|  c1|  c2|
+----+----+
|null|null|
|null|null|
|null|null|
|null|null|
|   0|str0|
|   1|str1|
|   2|str2|
|   3|str3|
|   4|str4|
|   5|str5|
|   6|str6|
|   7|str7|
|   8|str8|
|   9|str9|
+----+----+
```

_Example 3: Json -> Text_

``` Scala
createDF(0, 9).write.format("json").saveAsTable("appendJsonToText")
createDF(10, 19).write.mode(SaveMode.Append).format("text").saveAsTable("appendJsonToText")
```

Error we got: 

```
Text data source supports only a single column, and you have 2 columns.
```

This PR is to issue an exception with appropriate error messages.
#### How was this patch tested?

Added test cases.

### CODE REVIEW

**Comment by gatorsmile** [comment]
cc @cloud-fan

**Comment by cloud-fan** [comment]
Should we forbid users to set format when append to a table/data source? cc @liancheng

**Comment by gatorsmile** [comment]
Agree! This has an external change. Just let me know if we can do it. Thanks!

**Comment by liancheng** [comment]
@cloud-fan @gatorsmile Yea, seems that appending with a different format doesn't make any sense. @yhuai any ideas? Is there any situations that we may want to append using a different format?

**Comment by yhuai** [comment]
I think we cannot ban the format when the append is used in `DataFrameWriter`. For example, when I use `createDF(10, 19).write.mode(SaveMode.Append).format("text").saveAsTable("appendJsonToText")`, I expect it uses text to create the data initially. Then, it is reasonable to expect that this code still work when we want to append data.

**Comment by yhuai** [comment]
test this please

**Comment by yhuai** [comment]
LGTM pending jenkins

**Comment by cloud-fan** [comment]
LGTM

**Comment by yhuai** [comment]
Thanks. Merging to master and branch 2.0.

**Pull request closed without merging**
