### PR TITLE
[SPARK-6519][ML] Add spark.ml API for bisecting k-means

### PR DESCRIPTION
**Pull request by yu-iskw**

### CODE REVIEW

**Comment by yu-iskw** [comment]
@jkbradley @mengxr could you review it when you have time? Thanks.

**Comment by mengxr** [comment]
I will review the PR today:)

**Comment by yu-iskw** [comment]
Thanks!

**Comment by mengxr** [comment]
@yu-iskw Sorry for the delay! The patch looks good to me, though the since versions need to be changed to `2.0.0`. Could you update your PR?

**Comment by yu-iskw** [comment]
Sure!

**Comment by yu-iskw** [comment]
Jenkins, test this please.

**Comment by mengxr** [comment]
LGTM. Merged into master. Thanks!

**Comment by yu-iskw** [comment]
Thank you for merging it!

**Pull request closed without merging**
