### PR TITLE
[SPARK-32664][CORE] Switch the log level from info to debug at BlockManager.getLocalBlockData

### PR DESCRIPTION
**Pull request by dmoore62**
### What changes were proposed in this pull request?
Changing an info log to a debug log based on SPARK-32664

### Why are the changes needed?
It is outlined in SPARK-32664

### Does this PR introduce _any_ user-facing change?
There are changes to the debug and info logs

### How was this patch tested?
Tested by looking at the logs

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Can you elabourate why you want to change log level of this?

**Comment by dmoore62** [comment]
It is in the ticket - https://issues.apache.org/jira/projects/SPARK/issues/SPARK-32664?filter=allissues

**Comment by maropu** [comment]
@dmoore62 Could you fill the PR description based on the ticket? The description will appear in commit logs, so it is important to clearly describe what's the issue, why we need a fix, brabrabra..., for better tracability.

**Comment by HyukjinKwon** [comment]
ok to test

**Review by Ngone51 — APPROVED** [review]
LGTM for the change. +1 to fill up the PR description.

**Comment by Ngone51** [comment]
cc @holdenk

**Comment by holdenk** [comment]
LGTM, thanks for the change.

**Review by HyukjinKwon — APPROVED** [review]
LGTM2. Merged to master.

**Pull request closed without merging**
