### PR TITLE
[SPARK-13702][CORE][SQL][MLLIB] Use diamond operator for generic instance creation in Java code.

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
## What changes were proposed in this pull request?

In order to make `docs/examples` (and other related code) more simple/readable/user-friendly, this PR replaces existing codes like the followings by using `diamond` operator.

```
-    final ArrayList<Product2<Object, Object>> dataToWrite =
-      new ArrayList<Product2<Object, Object>>();
+    final ArrayList<Product2<Object, Object>> dataToWrite = new ArrayList<>();
```

Java 7 or higher supports **diamond** operator which replaces the type arguments required to invoke the constructor of a generic class with an empty set of type parameters (<>). Currently, Spark Java code use mixed usage of this. 
## How was this patch tested?

Manual. 
Pass the existing tests.

### CODE REVIEW

**Comment by srowen** [comment]
Although I personally like this change, I'm less certain about it since it does not add any functional improvement or avoid a potential bug. It does add a little readability and only touches the relatively fewer Java files. I'd like to wait for others to give an opinion.

**Comment by dongjoon-hyun** [comment]
Thank you for review, @srowen . 
I agree. This has a little limited benefit; only small portion Java and no functional improvement. 
Actually, I started this PR to improve docs/examples (28 of 61 files) for simplicity and eventually hoped to apply all code to keep it consistently.

**Comment by dongjoon-hyun** [comment]
The conflict will be resolved via #11567 . After #11567 is committed, I will update this.

**Comment by mengxr** [comment]
+1 on the code changes, which simplifies the Java code and shows some benefits from dropping Java 6, but the changes to the pom file should be discussed in a separate PR.

**Comment by mengxr** [comment]
add to whitelist

**Comment by mengxr** [comment]
ok to test

**Comment by dongjoon-hyun** [comment]
Thank you, @mengxr !
I will remove `pom.xml` and checkstyle part from this PR soon.

**Comment by dongjoon-hyun** [comment]
Hi, @mengxr . 
I removed the change on build related files. Now this PR contains pure `Java` and `md` files.
Also, the description of PR/JIRA issue is updated accordingly.

**Comment by dongjoon-hyun** [comment]
Hi, @mengxr . 
The latest commit passes the test.
Could you review this again please?

**Comment by dongjoon-hyun** [comment]
The latest one is at commit `2e20843`, and all three builds (including that) passes.

**Comment by srowen** [comment]
LGTM, merging to master. This is now just straightforward use of the diamond operator only.

**Comment by dongjoon-hyun** [comment]
Thank you, @srowen . Yes, it is.

**Pull request closed without merging**
