### PR TITLE
[SPARK-14672][SQL] Move HiveContext analyze logic to AnalyzeTable

### PR DESCRIPTION
**Pull request by yhuai**
## What changes were proposed in this pull request?

Move the implementation of `hiveContext.analyze` to the command of `AnalyzeTable`.
## How was this patch tested?

Existing tests.

Closes #12429

### CODE REVIEW

**Comment by yhuai** [comment]
The original changes in #12429 look good to me. I have fixed the style and the conflicts. Will merge it once it passes tests.

**Comment by rxin** [comment]
LGTM

**Comment by yhuai** [comment]
Thanks @andrewor14 @rxin. Merging to master.

**Comment by lw-lin** [comment]
Seems like `org.apache.spark.sql.hive.HiveSparkSubmitSuite` have been failing since this merging:
https://spark-tests.appspot.com/tests/org.apache.spark.sql.hive.HiveSparkSubmitSuite/SPARK-8020:%20set%20sql%20conf%20in%20spark%20conf
https://spark-tests.appspot.com/tests/org.apache.spark.sql.hive.HiveSparkSubmitSuite/SPARK-9757%20Persist%20Parquet%20relation%20with%20decimal%20column

**Pull request closed without merging**
