### PR TITLE
[MINOR] Fix typos

### PR DESCRIPTION
**Pull request by smallzhongfeng**
### What changes were proposed in this pull request?

Fix typo in ReceiverSupervisorImpl.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

No need.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
This is fine but mind taking a look and see if there are more typos?

**Comment by smallzhongfeng** [comment]
OK. I need to look a little.

**Comment by smallzhongfeng** [comment]
cc. @HyukjinKwon

**Review by HyukjinKwon — APPROVED** [review]

**Review by MaxGekk — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
