### PR TITLE
[SPARK-36118][SQL] Add bitmap functions for Spark SQL

### PR DESCRIPTION
**Pull request by ReachInfi**
### What changes were proposed in this pull request?

add functions of bitmap building and computing cardinality for Spark SQL, If this is ok, I will update function.scala and FunctionRegistry.scala.

### Why are the changes needed?

Bitmaps are used more and more widely, and many frameworks have native support, such as Clickhouse

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

CI, it performs well on billions of rows based on our real demand

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
@ReachInfi can you file a JIRA and link it to the PR title please? See also https://spark.apache.org/contributing.html

**Comment by ReachInfi** [comment]
Ok,tks

**Comment by ReachInfi** [comment]
https://issues.apache.org/jira/browse/SPARK-36118

**Comment by HyukjinKwon** [comment]
Can you link it to the PR titile?

**Comment by ReachInfi** [comment]
done

**Comment by HyukjinKwon** [comment]
@ReachInfi BTW, are there any reference in other DBMSes for this specific expression?

**Comment by ReachInfi** [comment]
Clickhouse: https://clickhouse.tech/docs/zh/sql-reference/aggregate-functions/reference/groupbitmapor/

I think udaf may be a good way, just like hyperloglog

**Comment by HyukjinKwon** [comment]
are there more references?

**Comment by ReachInfi** [comment]
Clickhouse has two styles of bitmap fuction. 
The other is as follows：
https://clickhouse.tech/docs/en/sql-reference/functions/bitmap-functions/

doris also supports bitmap operator. 
http://doris.apache.org/master/zh-CN/sql-reference/sql-functions/bitmap-functions/

presto and mysql have some bitwise function：
https://dev.mysql.com/doc/refman/8.0/en/bit-functions.html
https://prestodb.io/docs/current/functions/bitwise.html

In other frameworks, I did not find any bitmap-related functions. I think the high-throughput feature is very suitable for batch offline building of bitmaps

**Comment by ReachInfi** [comment]
Hi, do i need update function.scala and FunctionRegistry.scala?

**Pull request closed without merging**
