### PR TITLE
[SPARK-19851] Add support for EVERY and ANY (SOME) aggregates

### PR DESCRIPTION
**Pull request by ptkool**
## What changes were proposed in this pull request?

This pull request implements the EVERY and ANY aggregates.

## How was this patch tested?

Testing was performed using unit tests, integration tests, and manual tests.

### CODE REVIEW

**Comment by ptkool** [comment]
Moved this PR to a feature branch and lost comments. The original PR is here: https://github.com/apache/spark/pull/17194

**Comment by rxin** [comment]
Can we just do a logical rewrite to turn them into "condA + condB + condC > 0" (for Some/Any) ?

**Comment by ptkool** [comment]
@rxin I'm not sure where you're going with your proposal. These are aggregate functions, not scalar functions.

**Comment by rxin** [comment]
I was saying rather than implementing them, just rewrite them into an aggregate on the conditions and compare them against the value.

**Comment by ptkool** [comment]
@rxin Ok. So you're proposing rewrites for these aggregates that look something like this?

```
some(cond)  => sum(cond) > 0
every(cond) => sum(not(cond)) = 0
```

**Comment by ptkool** [comment]
@rxin Actually, @hvanhovell proposed the following rewrites which I think are better:

```
some(cond)  => max(cond) = true
every(cond) => min(cond) = true
```

**Comment by rxin** [comment]
sgtm

**Comment by gatorsmile** [comment]
@ptkool Could you address the comments and we can review it? Thanks!

**Comment by HyukjinKwon** [comment]
ok to test

**Comment by HyukjinKwon** [comment]
@ptkool mind updating the PR please?

**Comment by gatorsmile** [comment]
@dilipbiswal Could you take this over?

**Comment by dilipbiswal** [comment]
@gatorsmile Sure.

**Comment by gatorsmile** [comment]
@ptkool Thanks for your contribution! This feature will be available in the next release. Spark 3.0

**Pull request closed without merging**
