### PR TITLE
[SPARK-22664] The logs about "Connected to Zookeeper" in ReliableKafkaReceiver.scala are in wrong position

### PR DESCRIPTION
**Pull request by liu-zhaokun**
[https://issues.apache.org/jira/browse/SPARK-22664](https://issues.apache.org/jira/browse/SPARK-22664)
The logs about "Connecting to Zookeeper" and "Connected to Zookeeper" in ReliableKafkaReceiver.scala should be printed when new a zkClient() in line 122.

### CODE REVIEW

**Comment by srowen** [comment]
You shouldn't create a JIRA for items like this, where the description is the same as the PR. I wouldn't move the initial log, as creating the Consumer is part of connecting. It won't matter much. But in case of error you will have logged what you were connecting to first.

**Comment by liu-zhaokun** [comment]
@srowen
Thanks for your reply.Could you help me review it?

**Comment by liu-zhaokun** [comment]
@srowen 
Please help merge this PR as it has passed all tests.

**Comment by jerryshao** [comment]
I guess the original purpose of such log is to reflect the behavior of consumer connection. It is not super necessary to do such trivial change. Also `ReliableKafkaReceiver` is not recommended any more, let's keep as it is.

**Comment by liu-zhaokun** [comment]
@jerryshao 
I think the log can't reflect the  behavior of consumer connection,because consumer.create doesn't do any connect,it only construct a ZookeeperConsumerConnector instance,so the right position is where zkclient connect to zk. ReliableKafkaReceiver is not marked deprecated,so users will use it.To avoid misleading by this log when a problem of connect to zk occur ,I think we should fix it.

**Comment by jerryshao** [comment]
>I think the log can't reflect the behavior of consumer connection,because consumer.create doesn't do any connect,it only construct a ZookeeperConsumerConnector instance

That's not true, `ZookeeperConsumerConnector` will also connect to ZK during initialization, please see here (https://github.com/apache/kafka/blob/c9f930e3fe25e5675e64550c8b396356c5349ca7/core/src/main/scala/kafka/consumer/ZookeeperConsumerConnector.scala#L126).

**Comment by jerryshao** [comment]
Actually there's no issue here, IMHO I think your understanding of this log is slightly different from the original purpose.

**Comment by liu-zhaokun** [comment]
@jerryshao 
Yes,you are right,but this log is not accurate,I think it should log like this "consumerconnector has been created",it is too ambiguity now.

**Comment by srowen** [comment]
This is trivial and not obviously a useful change, so it should be closed

**Pull request closed without merging**
