### PR TITLE
[SPARK-44318][BUILD] Remove useless dependencies - javax.ws.rs-api

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to remove useless dependencies - javax.ws.rs-api.

### Why are the changes needed?
Make code and dependency concisely.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA.

### CODE REVIEW

**Comment by LuciferYang** [comment]
@panbingkun Can you explain why these two dependencies are no longer useful?

**Comment by panbingkun** [comment]
1.(Jersey depend on it) The first PR to introduce the dependency of `javax.ws.rs.javax.ws.rs-api`
PR: [SPARK-12154] Upgrade to Jersey 2
CommitID: b7fdc23ccc5967de5799d8cf6f14289e71f29a1e

https://github.com/apache/spark/commit/b7fdc23ccc5967de5799d8cf6f14289e71f29a1e#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8R624-R627
image

2.Because Jersey depends on it, however, with the upgrade of Jersey version, the `rs-api` package name it depends on has been moved from: `javax.ws.rs.javax.ws.rs-api` to: `jakarta.ws.rs.jakarta.ws.rs-api` in version 2.28, but there is no corresponding removal in Spark.
- Jersey 2.27: https://repo1.maven.org/maven2/org/glassfish/jersey/project/2.27/project-2.27.pom
image

- Jersey 2.28: https://repo1.maven.org/maven2/org/glassfish/jersey/project/2.28/project-2.28.pom
image

- The PR that was modified in Jersey is: https://github.com/eclipse-ee4j/jersey/pull/3994
https://github.com/eclipse-ee4j/jersey/pull/3994/files#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8R1363-R1364

3.
image

4.In fact, we can only depends on `[jakarta.ws.rs](https://mvnrepository.com/artifact/jakarta.ws.rs) » [jakarta.ws.rs-api](https://mvnrepository.com/artifact/jakarta.ws.rs/jakarta.ws.rs-api)` in Spark because its package name has changed.

**Comment by panbingkun** [comment]
cc @LuciferYang @dongjoon-hyun

**Comment by panbingkun** [comment]
> There is no change on dependency manifest file?

Yes, that's right, it doesn't exist in `spark-deps-hadoop-3-hive-2.3`.
Only the changed package exists:
image

**Pull request closed without merging**
