### PR TITLE
[MINOR] change new Exception to IllegalArgumentException

### PR DESCRIPTION
**Pull request by adrian-wang**

### CODE REVIEW

**Comment by srowen** [comment]
I agree that it's not good practice to throw `Exception`, or `RuntimeException`, as these are generic base classes. `sys.error` just causes a `RuntimeException` though. I think that's not a real improvement and is less clear, and `sys.error` isn't used in the rest of the code as a rule anyway.

Instead these should be more meaningful exception types.

**Comment by rxin** [comment]
@srowen do you have a better suggestion for this case? In these cases, these cases are not supposed to happen at runtime. It is almost like an assert.

**Comment by srowen** [comment]
A subclass of `RuntimeException` is appropriate then. I use `IllegalArgumentException` for something basically related to input to the method, and `IllegalStateException` as a more general subclass of `RuntimeException`. It's quite minor, but while we're here, I'd rather do what I think is the general best practice in Java-land.

**Comment by rxin** [comment]
+1

**Comment by rxin** [comment]
Sorry @adrian-wang I think in this case IllegalArgumentException is more appropriate.

**Comment by rxin** [comment]
@adrian-wang  can you update the exception to IllegalArgumentException so I can merge this?

**Comment by adrian-wang** [comment]
Oh, sorry for missing this, I'll update it very soon.

**Comment by rxin** [comment]
Thanks. I've merged this.

**Pull request closed without merging**
