### PR TITLE
[SPARK-5623][GraphX] Replace an obsolete mapReduceTriplets with a new aggregateMessages in GraphSuite

### PR DESCRIPTION
**Pull request by maropu**

### CODE REVIEW

**Comment by ankurdave** [comment]
ok to test

**Comment by srowen** [comment]
@maropu this looks stale. Is it still something you think should be merged? maybe you can rebase and then it can be reviewed if so.

**Comment by maropu** [comment]
ok, fixed.

**Comment by srowen** [comment]
@ankurdave OK with you?

**Comment by srowen** [comment]
@maropu I think this was actually a good change, as we have had these deprecation warnings for a long time. Do you want to revive this and try to remove as many usages as possible? There may be some usages of the deprecated method in tests that try to test the deprecated method of course. Or, I may just propose separately that we remove deprecated methods in GraphX for 2.x

**Comment by maropu** [comment]
@srowen yes and I agreed that these duplicated methods should be removed in 2.x. However, since activities in the GraphX component are almost inactive, I don't  think pull requests someones make for GraphX are reviewed and merged actively in the current situation.

**Comment by srowen** [comment]
Yes, in this regard I'm happy to review and merge changes, since it is only removing use of a method that's already deprecated. In fact I think several other people are comfortable reviewing changes that remove the deprecated methods for Spark 2.x. If you feel up for it, go for it, otherwise I may have a look.

**Comment by maropu** [comment]
@srowen Okay and I'll do that.

**Comment by maropu** [comment]
@srowen Is there any JIRA ticket about this topic?

**Comment by srowen** [comment]
SPARK-5623 I suppose, but that's not about removing the deprecated methods. You could close it and make a subtask of https://issues.apache.org/jira/browse/SPARK-11806 for this.

**Comment by maropu** [comment]
okay.

**Pull request closed without merging**
