### PR TITLE
SPARK-7063 when lz4 compression is used, it causes core dump

### PR DESCRIPTION
**Pull request by JihongMA**
please review this pull request. Thank you!

### CODE REVIEW

**Comment by pwendell** [comment]
Jenkins, test this please.

**Comment by srowen** [comment]
Looks like this requires Java 7?
https://github.com/jpountz/lz4-java/commits/master
We can't use it if so, but, the tests passed anyway.
It looks like a lot changed in this library, so you'd need to check whether this has introduced any other compatibility changes.

**Comment by linlin200605** [comment]
lz4-1.3.0 needs Java 7 for building the jar, usually not necessarily require JDK 7 at runtime if there is backward compatibility. I will follow up on that.

**Comment by srowen** [comment]
@linlin200605 any update on this? java 7 bytecode can't even be loaded in java 6. It's not an API question. If not we have to close this I'm afraid or at least target it for a later version when Java 7 can be required.

**Comment by pwendell** [comment]
@srowen yeah maybe let's close this as a won't fix and just give the workaround for IBM users to upgrade the dependency themselves.

**Comment by linlin200605** [comment]
I just found out there are changes introduced in 1.3.0 which are not backward compatible with JDK6, if supporting JDK6 is a must, then we can consider to target it for future when Spark moves to JDK7 or later version as suggested above.

**Comment by srowen** [comment]
@JihongMA this needs a rebase now, and has an unrelated change? if you make it just about updating the lz4 version, I'll merge it for master.

**Comment by JihongMA** [comment]
sorry, I was busy and missed this message. I created a new pull request, which rebased the change with latest master.

**Comment by srowen** [comment]
(That's fine -- you can also just rebase and force-push the existing branch/PR. The advantage there is that it retains the discussion in a single PR. But no big deal here.)

**Pull request closed without merging**
