### PR TITLE
[MINOR][DOCS] Fix type Information in Quick Start and Programming Guide

### PR DESCRIPTION
**Pull request by techaddict**

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
(I think it would be nice if the PR description is fill up and even nicer if the PR title follows others such as `[MINOR][DOCS] XXXXX`.)

**Comment by srowen** [comment]
LGTM assuming this is now what the shell would output

**Comment by techaddict** [comment]
@srowen Yupp copied after running in spark-shell.

screen shot 2016-05-02 at 6 25 03 pm

**Comment by techaddict** [comment]
@srowen Can you merge this ?

**Comment by srowen** [comment]
Merged to master/2.0

**Pull request closed without merging**
