### PR TITLE
[SPARK-45341][CORE] Correct the title level in the comments of KVStore.java to make `sbt doc` run successfully with Java 17

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr aims to correct the title level in the comments of `KVStore.java` to make `sbt doc` run successfully with Java 17.

### Why are the changes needed?
Make the `sbt doc` command execute successfully with Java 17

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
- Manually check.

run `build/sbt clean doc -Phadoop-3 -Phadoop-cloud -Pmesos -Pyarn -Pkinesis-asl -Phive-thriftserver -Pspark-ganglia-lgpl -Pkubernetes -Phive -Pvolcano`

**Before**

```
[error] /Users/yangjie01/SourceCode/git/spark-mine-sbt/Picked up JAVA_TOOL_OPTIONS:-Duser.language=en
[error] Loading source file /Users/yangjie01/SourceCode/git/spark-mine-sbt/common/kvstore/src/main/java/org/apache/spark/util/kvstore/LevelDBTypeInfo.java...
[error] Loading source file /Users/yangjie01/SourceCode/git/spark-mine-sbt/common/kvstore/src/main/java/org/apache/spark/util/kvstore/ArrayWrappers.java...
[error] Loading source file /Users/yangjie01/SourceCode/git/spark-mine-sbt/common/kvstore/src/main/java/org/apache/spark/util/kvstore/KVIndex.java...
[error] Loading source file /Users/yangjie01/SourceCode/git/spark-mine-sbt/common/kvstore/src/main/java/org/apache/spark/util/kvstore/InMemoryStore.java...
[error] Loading source file /Users/yangjie01/SourceCode/git/spark-mine-sbt/common/kvstore/src/main/java/org/apache/spark/util/kvstore/LevelDBIterator.java...
[error] Loading source file /Users/yangjie01/SourceCode/git/spark-mine-sbt/common/kvstore/src/main/java/org/apache/spark/util/kvstore/RocksDB.java...
[error] Loading source file /Users/yangjie01/SourceCode/git/spark-mine-sbt/common/kvstore/src/main/java/org/apache/spark/util/kvstore/RocksDBTypeInfo.java...
[error] Loading source file /Users/yangjie01/SourceCode/git/spark-mine-sbt/common/kvstore/src/main/java/org/apache/spark/util/kvstore/UnsupportedStoreVersionException.java...
[error] Loading source file /Users/yangjie01/SourceCode/git/spark-mine-sbt/common/kvstore/src/main/java/org/apache/spark/util/kvstore/LevelDB.java...
[error] Loading source file /Users/yangjie01/SourceCode/git/spark-mine-sbt/common/kvstore/src/main/java/org/apache/spark/util/kvstore/KVStoreIterator.java...
[error] Loading source file /Users/yangjie01/SourceCode/git/spark-mine-sbt/common/kvstore/src/main/java/org/apache/spark/util/kvstore/KVStore.java...
[error] Loading source file /Users/yangjie01/SourceCode/git/spark-mine-sbt/common/kvstore/src/main/java/org/apache/spark/util/kvstore/KVStoreView.java...
[error] Loading source file /Users/yangjie01/SourceCode/git/spark-mine-sbt/common/kvstore/src/main/java/org/apache/spark/util/kvstore/KVTypeInfo.java...
[error] Loading source file /Users/yangjie01/SourceCode/git/spark-mine-sbt/common/kvstore/src/main/java/org/apache/spark/util/kvstore/RocksDBIterator.java...
[error] Loading source file /Users/yangjie01/SourceCode/git/spark-mine-sbt/common/kvstore/src/main/java/org/apache/spark/util/kvstore/KVStoreSerializer.java...
[error] Constructing Javadoc information...
[error] Building index for all the packages and classes...
[error] Standard Doclet version 17.0.8+7-LTS
[error] Building tree for all the packages and classes...
[error] /Users/yangjie01/SourceCode/git/spark-mine-sbt/common/kvstore/src/main/java/org/apache/spark/util/kvstore/KVStore.java:32:1:  error: heading used out of sequence: <H3>, compared to implicit preceding heading: <H1>
[error]  * <h3>Serialization</h3>
[error]    ^Generating /Users/yangjie01/SourceCode/git/spark-mine-sbt/common/kvstore/target/scala-2.13/api/org/apache/spark/util/kvstore/InMemoryStore.html...
[error] Generating /Users/yangjie01/SourceCode/git/spark-mine-sbt/common/kvstore/target/scala-2.13/api/org/apache/spark/util/kvstore/KVIndex.html...
[error] Generating /Users/yangjie01/SourceCode/git/spark-mine-sbt/common/kvstore/target/scala-2.13/api/org/apache/spark/util/kvstore/KVStore.html...
[error] Generating /Users/yangjie01/SourceCode/git/spark-mine-sbt/common/kvstore/target/scala-2.13/api/org/apache/spark/util/kvstore/KVStoreIterator.html...
[error] Generating /Users/yangjie01/SourceCode/git/spark-mine-sbt/common/kvstore/target/scala-2.13/api/org/apache/spark/util/kvstore/KVStoreSerializer.html...
[error] Generating /Users/yangjie01/SourceCode/git/spark-mine-sbt/common/kvstore/target/scala-2.13/api/org/apache/spark/util/kvstore/KVStoreView.html...
[error] Generating /Users/yangjie01/SourceCode/git/spark-mine-sbt/common/kvstore/target/scala-2.13/api/org/apache/spark/util/kvstore/KVTypeInfo.html...
[error] Generating /Users/yangjie01/SourceCode/git/spark-mine-sbt/common/kvstore/target/scala-2.13/api/org/apache/spark/util/kvstore/LevelDB.html...
[error] Generating /Users/yangjie01/SourceCode/git/spark-mine-sbt/common/kvstore/target/scala-2.13/api/org/apache/spark/util/kvstore/LevelDB.TypeAliases.html...
[error] Generating /Users/yangjie01/SourceCode/git/spark-mine-sbt/common/kvstore/target/scala-2.13/api/org/apache/spark/util/kvstore/RocksDB.html...
[error] Generating /Users/yangjie01/SourceCode/git/spark-mine-sbt/common/kvstore/target/scala-2.13/api/org/apache/spark/util/kvstore/RocksDB.TypeAliases.html...
[error] Generating /Users/yangjie01/SourceCode/git/spark-mine-sbt/common/kvstore/target/scala-2.13/api/org/apache/spark/util/kvstore/UnsupportedStoreVersionException.html...
[error] Generating /Users/yangjie01/SourceCode/git/spark-mine-sbt/common/kvstore/target/scala-2.13/api/org/apache/spark/util/kvstore/package-summary.html...
[error] Generating /Users/yangjie01/SourceCode/git/spark-mine-sbt/common/kvstore/target/scala-2.13/api/org/apache/spark/util/kvstore/package-tree.html...
[error] Generating /Users/yangjie01/SourceCode/git/spark-mine-sbt/common/kvstore/target/scala-2.13/api/constant-values.html...
[error] Generating /Users/yangjie01/SourceCode/git/spark-mine-sbt/common/kvstore/target/scala-2.13/api/serialized-form.html...
[error] Generating /Users/yangjie01/SourceCode/git/spark-mine-sbt/common/kvstore/target/scala-2.13/api/overview-tree.html...
[error] Building index for all classes...
[error] Generating /Users/yangjie01/SourceCode/git/spark-mine-sbt/common/kvstore/target/scala-2.13/api/allclasses-index.html...
[error] Generating /Users/yangjie01/SourceCode/git/spark-mine-sbt/common/kvstore/target/scala-2.13/api/allpackages-index.html...
[error] Generating /Users/yangjie01/SourceCode/git/spark-mine-sbt/common/kvstore/target/scala-2.13/api/index-all.html...
[error] Generating /Users/yangjie01/SourceCode/git/spark-mine-sbt/common/kvstore/target/scala-2.13/api/index.html...
[error] Generating /Users/yangjie01/SourceCode/git/spark-mine-sbt/common/kvstore/target/scala-2.13/api/help-doc.html...
[error] 1 error
[warn] javadoc exited with exit code 1
...
[error] sbt.inc.Doc$JavadocGenerationFailed
[error] 	at sbt.inc.Doc$.sbt$inc$Doc$$$anonfun$cachedJavadoc$1(Doc.scala:51)
[error] 	at sbt.inc.Doc$$anonfun$cachedJavadoc$2.run(Doc.scala:41)
[error] 	at sbt.inc.Doc$.sbt$inc$Doc$$$anonfun$prepare$1(Doc.scala:62)
[error] 	at sbt.inc.Doc$$anonfun$prepare$5.run(Doc.scala:57)
[error] 	at sbt.inc.Doc$.go$1(Doc.scala:73)
[error] 	at sbt.inc.Doc$.$anonfun$cached$5(Doc.scala:82)
[error] 	at sbt.inc.Doc$.$anonfun$cached$5$adapted(Doc.scala:81)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:220)
[error] 	at sbt.inc.Doc$.sbt$inc$Doc$$$anonfun$cached$1(Doc.scala:85)
[error] 	at sbt.inc.Doc$$anonfun$cached$7.run(Doc.scala:68)
[error] 	at sbt.Defaults$.$anonfun$docTaskSettings$4(Defaults.scala:2178)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:63)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:69)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:283)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[error] 	at sbt.Execute.work(Execute.scala:292)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:283)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error] 	at java.base/java.lang.Thread.run(Thread.java:833)
[error] (kvstore / Compile / doc) sbt.inc.Doc$JavadocGenerationFailed
[error] Total time: 118 s (01:58), completed Sep 26, 2023, 10:11:02 PM
```

The command execution failed because after Java 9, the JavaDoc tool has stricter requirements for title levels, and title tags must be used in the correct order(start with `<h2>`).

**After**

```
[success] Total time: 115 s (01:55), completed Sep 26, 2023, 10:14:20 PM
```

### Was this patch authored or co-authored using generative AI tooling?
No

### CODE REVIEW

**Comment by LuciferYang** [comment]
Since Github Action is checking `sbt unidoc`, this issue was not exposed. cc @srowen @HyukjinKwon @dongjoon-hyun FYI

**Review by srowen — APPROVED** [review]

**Review by dongjoon-hyun — COMMENTED** [review]
I'm just curious why this is SBT issue?

This javadoc issue should happen in Maven because we have the following.

https://github.com/apache/spark/blob/ea3104fa71b0d7b6ac5e74292c28e40acb1e6537/pom.xml#L3187-L3188

**Comment by LuciferYang** [comment]
> I'm just curious why this is SBT issue?
> 
> This javadoc issue should happen in Maven because we have the following.
> 
> https://github.com/apache/spark/blob/ea3104fa71b0d7b6ac5e74292c28e40acb1e6537/pom.xml#L3187-L3188

An interesting question, the maven build indeed did not throw any errors, I can't provide an answer right now, need to investigate it for maven

**Comment by LuciferYang** [comment]
@dongjoon-hyun we can test as follows
```
build/mvn javadoc:javadoc -pl common/kvstore -am
```

then we can see

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.5.0:javadoc (default-cli) on project spark-kvstore_2.13: An error has occurred in Javadoc report generation: 
[ERROR] Exit code: 1
[ERROR] 正在加载程序包org.apache.spark.util.kvstore的源文件...
[ERROR] 正在构造 Javadoc 信息...
[ERROR] 正在构建所有程序包和类的索引...
[ERROR] 标准 Doclet 版本 17.0.8+7-LTS
[ERROR] 正在构建所有程序包和类的树...
[ERROR] /Users/yangjie01/SourceCode/git/spark-mine-13/common/kvstore/src/main/java/org/apache/spark/util/kvstore/KVStore.java:32: 错误: 使用的标题超出序列：<H3>（与隐式前导标题相比：<H1>）
[ERROR]  * <h3>Serialization</h3>
[ERROR]    ^
[ERROR] 正在生成/Users/yangjie01/SourceCode/git/spark-mine-13/common/kvstore/target/site/apidocs/org/apache/spark/util/kvstore/InMemoryStore.html...
[ERROR] 正在生成/Users/yangjie01/SourceCode/git/spark-mine-13/common/kvstore/target/site/apidocs/org/apache/spark/util/kvstore/KVIndex.html...
[ERROR] 正在生成/Users/yangjie01/SourceCode/git/spark-mine-13/common/kvstore/target/site/apidocs/org/apache/spark/util/kvstore/KVStore.html...
[ERROR] 正在生成/Users/yangjie01/SourceCode/git/spark-mine-13/common/kvstore/target/site/apidocs/org/apache/spark/util/kvstore/KVStoreIterator.html...
[ERROR] 正在生成/Users/yangjie01/SourceCode/git/spark-mine-13/common/kvstore/target/site/apidocs/org/apache/spark/util/kvstore/KVStoreSerializer.html...
[ERROR] 正在生成/Users/yangjie01/SourceCode/git/spark-mine-13/common/kvstore/target/site/apidocs/org/apache/spark/util/kvstore/KVStoreView.html...
[ERROR] 正在生成/Users/yangjie01/SourceCode/git/spark-mine-13/common/kvstore/target/site/apidocs/org/apache/spark/util/kvstore/KVTypeInfo.html...
[ERROR] 正在生成/Users/yangjie01/SourceCode/git/spark-mine-13/common/kvstore/target/site/apidocs/org/apache/spark/util/kvstore/LevelDB.html...
[ERROR] 正在生成/Users/yangjie01/SourceCode/git/spark-mine-13/common/kvstore/target/site/apidocs/org/apache/spark/util/kvstore/LevelDB.TypeAliases.html...
[ERROR] 正在生成/Users/yangjie01/SourceCode/git/spark-mine-13/common/kvstore/target/site/apidocs/org/apache/spark/util/kvstore/RocksDB.html...
[ERROR] 正在生成/Users/yangjie01/SourceCode/git/spark-mine-13/common/kvstore/target/site/apidocs/org/apache/spark/util/kvstore/RocksDB.TypeAliases.html...
[ERROR] 正在生成/Users/yangjie01/SourceCode/git/spark-mine-13/common/kvstore/target/site/apidocs/org/apache/spark/util/kvstore/UnsupportedStoreVersionException.html...
[ERROR] 正在生成/Users/yangjie01/SourceCode/git/spark-mine-13/common/kvstore/target/site/apidocs/org/apache/spark/util/kvstore/package-summary.html...
[ERROR] 正在生成/Users/yangjie01/SourceCode/git/spark-mine-13/common/kvstore/target/site/apidocs/org/apache/spark/util/kvstore/package-tree.html...
[ERROR] 正在生成/Users/yangjie01/SourceCode/git/spark-mine-13/common/kvstore/target/site/apidocs/constant-values.html...
[ERROR] 正在生成/Users/yangjie01/SourceCode/git/spark-mine-13/common/kvstore/target/site/apidocs/serialized-form.html...
[ERROR] 正在生成/Users/yangjie01/SourceCode/git/spark-mine-13/common/kvstore/target/site/apidocs/org/apache/spark/util/kvstore/class-use/KVIndex.html...
[ERROR] 正在生成/Users/yangjie01/SourceCode/git/spark-mine-13/common/kvstore/target/site/apidocs/org/apache/spark/util/kvstore/class-use/InMemoryStore.html...
[ERROR] 正在生成/Users/yangjie01/SourceCode/git/spark-mine-13/common/kvstore/target/site/apidocs/org/apache/spark/util/kvstore/class-use/RocksDB.html...
[ERROR] 正在生成/Users/yangjie01/SourceCode/git/spark-mine-13/common/kvstore/target/site/apidocs/org/apache/spark/util/kvstore/class-use/RocksDB.TypeAliases.html...
[ERROR] 正在生成/Users/yangjie01/SourceCode/git/spark-mine-13/common/kvstore/target/site/apidocs/org/apache/spark/util/kvstore/class-use/UnsupportedStoreVersionException.html...
[ERROR] 正在生成/Users/yangjie01/SourceCode/git/spark-mine-13/common/kvstore/target/site/apidocs/org/apache/spark/util/kvstore/class-use/LevelDB.html...
[ERROR] 正在生成/Users/yangjie01/SourceCode/git/spark-mine-13/common/kvstore/target/site/apidocs/org/apache/spark/util/kvstore/class-use/LevelDB.TypeAliases.html...
[ERROR] 正在生成/Users/yangjie01/SourceCode/git/spark-mine-13/common/kvstore/target/site/apidocs/org/apache/spark/util/kvstore/class-use/KVStoreIterator.html...
[ERROR] 正在生成/Users/yangjie01/SourceCode/git/spark-mine-13/common/kvstore/target/site/apidocs/org/apache/spark/util/kvstore/class-use/KVStore.html...
[ERROR] 正在生成/Users/yangjie01/SourceCode/git/spark-mine-13/common/kvstore/target/site/apidocs/org/apache/spark/util/kvstore/class-use/KVStoreView.html...
[ERROR] 正在生成/Users/yangjie01/SourceCode/git/spark-mine-13/common/kvstore/target/site/apidocs/org/apache/spark/util/kvstore/class-use/KVTypeInfo.html...
[ERROR] 正在生成/Users/yangjie01/SourceCode/git/spark-mine-13/common/kvstore/target/site/apidocs/org/apache/spark/util/kvstore/class-use/KVStoreSerializer.html...
[ERROR] 正在生成/Users/yangjie01/SourceCode/git/spark-mine-13/common/kvstore/target/site/apidocs/org/apache/spark/util/kvstore/package-use.html...
[ERROR] 正在生成/Users/yangjie01/SourceCode/git/spark-mine-13/common/kvstore/target/site/apidocs/overview-tree.html...
[ERROR] 正在构建所有类的索引...
[ERROR] 正在生成/Users/yangjie01/SourceCode/git/spark-mine-13/common/kvstore/target/site/apidocs/allclasses-index.html...
[ERROR] 正在生成/Users/yangjie01/SourceCode/git/spark-mine-13/common/kvstore/target/site/apidocs/allpackages-index.html...
[ERROR] 正在生成/Users/yangjie01/SourceCode/git/spark-mine-13/common/kvstore/target/site/apidocs/index-all.html...
[ERROR] 正在生成/Users/yangjie01/SourceCode/git/spark-mine-13/common/kvstore/target/site/apidocs/index.html...
[ERROR] 正在生成/Users/yangjie01/SourceCode/git/spark-mine-13/common/kvstore/target/site/apidocs/help-doc.html...
[ERROR] 注: 可能覆盖将来的标准标记的定制标记:  @todo, @note, @tparam, @constructor, @groupname, @example, @group。为了避免出现可能的覆盖, 请在定制标记名称中至少使用一个句点字符 (.)。
[ERROR] 注: 找不到的定制标记:  @todo, @note, @tparam, @constructor, @groupname, @example, @group
[ERROR] 1 个错误
[ERROR] Command line was: /Users/yangjie01/Tools/zulu17/zulu-17.jdk/Contents/Home/bin/javadoc -Xdoclint:all -Xdoclint:-missing @options @packages
[ERROR] 
[ERROR] Refer to the generated Javadoc files in '/Users/yangjie01/SourceCode/git/spark-mine-13/common/kvstore/target/site/apidocs' dir.
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :spark-kvstore_2.13
```
Sorry, there are some non-English characters in the compilation log.

In GitHub Action, we run "mvn install", but the "mvn install" command does not execute "javadoc:javadoc" by default. This is because "javadoc:javadoc" belongs to the site lifecycle phase, and the install lifecycle phase comes before site. A simple fix would be to change the execution command to "mvn install javadoc:javadoc" for additional checks.

**Comment by LuciferYang** [comment]
I create a new jira SPARK-45348 and will give a pr later

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
