### PR TITLE
[SPARK-36270][BUILD][FOLLOWUP] Reduce metaspace size for pyspark

### PR DESCRIPTION
**Pull request by viirya**
### What changes were proposed in this pull request?

Notice that pyspark GA module `pyspark-pandas-slow` sometimes still has return code 137. Try to reduce its metaspace size further.

### Why are the changes needed?

Fix return code 137 for pyspark GA module.

### Does this PR introduce _any_ user-facing change?

No, dev only.

### How was this patch tested?

GA

### CODE REVIEW

**Comment by viirya** [comment]
cc @dongjoon-hyun @HyukjinKwon

**Comment by viirya** [comment]
All GA tests are passed.

**Comment by viirya** [comment]
Jenkins is also passed.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @viirya .
Merged to master/3.2.

**Comment by viirya** [comment]
Thank you @dongjoon-hyun

**Comment by HyukjinKwon** [comment]
Lgtm

**Pull request closed without merging**
