### PR TITLE
[SPARK-45700][SPARK-45702][SPARK-45703][BUILD][CORE][SQL][MLLIB] Fix the compile warning suppression rule added in SPARK-35496 

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This PR fixed the issues corresponding to the compile suppression rules added in SPARK-35496 for upgrading to Scala 2.13.7, and cleaned up these rules.

```
// SPARK-35496 Upgrade Scala to 2.13.7 and suppress:
// 1. `The outer reference in this type test cannot be checked at run time`
// 2. `the type test for pattern TypeA cannot be checked at runtime because it
//    has type parameters eliminated by erasure`
// 3. `abstract type TypeA in type pattern Seq[TypeA] (the underlying of
//    Seq[TypeA]) is unchecked since it is eliminated by erasure`
// 4. `fruitless type test: a value of TypeA cannot also be a TypeB`
"-Wconf:cat=unchecked&msg=outer reference:s",
"-Wconf:cat=unchecked&msg=eliminated by erasure:s",
"-Wconf:msg=^(?=.*?a value of type)(?=.*?cannot also be).+$:s",
```

The specific fixes are as follows:
- Added the corresponding `outer reference` to fix issue 1
- Used fine-grained `@unchecked` declarations to clean up issues 2 and 3
- Since the case corresponding to issue 4 no longer exists, the corresponding suppression rule was directly deleted.

### Why are the changes needed?
Clean up the compile issue suppression rules added in SPARK-35496 for upgrading to Scala 2.13.7.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass GitHub Actions

### Was this patch authored or co-authored using generative AI tooling?
No

### CODE REVIEW

**Comment by LuciferYang** [comment]
Test first

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Nice!

**Comment by LuciferYang** [comment]
Thanks @dongjoon-hyun ~

**Comment by LuciferYang** [comment]
Very sorry, I forgot to add labels in the pr title, just supplemented them, even though the PR has already been merged ...

**Pull request closed without merging**
