### PR TITLE
[SPARK-45318][SHELL][TESTS] Merge test cases from `SingletonRepl2Suite/Repl2Suite` back into `SingletonReplSuite/ReplSuite`

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr aims to merge test cases from `SingletonRepl2Suite/Repl2Suite` back into `SingletonReplSuite/ReplSuite` to reduce duplicate code.

### Why are the changes needed?
https://github.com/apache/spark/pull/28545 split the relevant test cases from `SingletonReplSuite/ReplSuite` into `SingletonRepl2Suite/Repl2Suite`, distinguishing different test versions of Scala 2.12 and Scala 2.13. 

Currently, Spark 4.0 no longer supports Scala 2.12, so they can be merged back into the original files to reduce duplicate code.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass GitHub Actions

### Was this patch authored or co-authored using generative AI tooling?
No

### CODE REVIEW

**Comment by LuciferYang** [comment]
cc @HyukjinKwon @srowen @dongjoon-hyun

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM

**Comment by LuciferYang** [comment]
Thanks @dongjoon-hyun

**Comment by dongjoon-hyun** [comment]
Merged to master for Apache Spark 4.

**Review by HyukjinKwon — COMMENTED** [review]
LGTM2

**Pull request closed without merging**
