### PR TITLE
[SPARK-27056][MESOS]Remove  start-shuffle-service.sh

### PR DESCRIPTION
**Pull request by 10110346**
## What changes were proposed in this pull request?

 `start-shuffle-service.sh`  was only used by Mesos  before `start-mesos-shuffle-service.sh`.
Obviously, `start-mesos-shuffle-service.sh` solves some problems, it is better than  `start-shuffle-service.sh`.
So now we should delete `start-shuffle-service.sh` in case users use it.

## How was this patch tested?
N/A

### CODE REVIEW

**Comment by srowen** [comment]
Isn't this used by standalone? I admit I haven't kept up with how the shuffle service is or isn't launched by various RMs (YARN doesn't use it right?) but are you sure it was Mesos-only?

**Comment by 10110346** [comment]
> 
> 
> Isn't this used by standalone? I admit I haven't kept up with how the shuffle service is or isn't launched by various RMs (YARN doesn't use it right?) but are you sure it was Mesos-only?
 
Thanks @srowen 
I got some information from these two PR:
1. #4990, `start-shuffle-service.sh` was added in this PR, this PR description is for Mesos to add this file.
2. #7881, `start-mesos-shuffle-service.sh` was added in this PR, this PR solves some problems for Mesos 

Also, I found this description in the  `job-scheduling.md (L80)`:
` In standalone mode, simply start your workers with spark.shuffle.service.enabled set to true.`
In fact,  in standalone mode, if we started workers and we didn't set  spark.shuffle.service.enabled to true ,and then we can run `$SPARK_HOME/sbin/start-shuffle-service.sh` to start shuffle service. In this case, we only need to modify the description of  `job-scheduling.md (L80)`.

**Comment by srowen** [comment]
Hm, maybe. @squito or @dragos or @vanzin do you have any background on whether this shuffle service script is used anymore, as there is a script specific to Mesos.

The underlying non-Mesos shuffle service implementation is still there. I hesitate to only remove the script but I have a feeling you may be right.

**Comment by dragos** [comment]
Sorry, I have not been involved with Spark lately, so I don't really know, but /cc @skyluc

**Comment by squito** [comment]
I agree that its not needed in yarn or standalone.  I don't really know much about mesos.  the explanation of of @10110346 sounds right, but I'm also a bit hesitant to delete it from lack of knowledge.

**Comment by felixcheung** [comment]
@tnachen @susanxhuynh do you know about this for mesos?

**Comment by tnachen** [comment]
Spark on Mesos users should only just use the mesos shuffle service, so I don't think anyone on the Mesos side will be using the start-shuffle-service.sh script.

**Review by srowen — APPROVED** [review]

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
