### PR TITLE
[SPARK-21526] [MLlib] Add support to ML LogisticRegression for setting initial model

### PR DESCRIPTION
**Pull request by JohnHBrock**
## What changes were proposed in this pull request?

* Change ML LogisticRegression setInitialModel from private to public.
* Add getInitialModel method.

## How was this patch tested?

Running `./dev/run-tests`.

### CODE REVIEW

**Comment by JohnHBrock** [comment]
This contribution is my original work and I license the work to the project under the project’s open source license.

**Comment by MLnick** [comment]
Hi there, thanks for this. However, please see #18610 and related JIRA tickets. The solution is slightly more complex and needs to be done in a more generic way. I suggest that this be updated once agreement on #18610 is reached, and makes use of the shared trait in that PR, etc.

**Review by WeichenXu123 — COMMENTED** [review]
Yes pls pending until #18610 is done.

**Comment by JohnHBrock** [comment]
#18610 seems to be stuck in purgatory. Is there any option other than waiting for that PR to be resolved? This feels like the perfect being the enemy of the good.

**Comment by sethah** [comment]
I actually completely agree about perfect being the enemy of good in this case. We should provide something workable that can be safely modified in the future if needed. Still, this needs to be done in the other PR https://github.com/apache/spark/pull/18610, so I suggest providing feedback and code review on that one until it gets merged, then we can revisit here. Thanks!

**Pull request closed without merging**
