### PR TITLE
[SPARK-37965][SQL] Remove check field name when reading/writing existing data in Orc

### PR DESCRIPTION
**Pull request by AngersZhuuuu**
### What changes were proposed in this pull request?
Remove `supportFieldName` check in DataSource ORCFormat.
1. org.apache.spark.sql.hive.orc.OrcFileFormat didn't add this check too
2. Tried a lot of wield column name, all can be reading and writing.

### Why are the changes needed?
Remove unnecessary check

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Added UT

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
I checked the history. Seems like we added this check mainly because Parquet restricts the column names that will be removed from https://github.com/apache/spark/pull/35229. So this change seems fine to me but would be great to double check w/ @dongjoon-hyun

**Comment by HyukjinKwon** [comment]
@AngersZhuuuu BTW, I think it would be great to explain why we can remove this change in the PR description with pointing out the commits in the history.

**Comment by AngersZhuuuu** [comment]
> @AngersZhuuuu BTW, I think it would be great to explain why we can remove this change in the PR description with pointing out the commits in the history.

Yea, will do this later.

**Review by dongjoon-hyun — COMMENTED** [review]
Yep, @HyukjinKwon 's comment is correct.
Let's review this after #35229 landed to the master first.

Thank you for keeping Apache Spark data sources consistent.

**Comment by AngersZhuuuu** [comment]
This check is added in https://github.com/apache/spark/pull/19124 but change to use back quote to wrap field name in https://github.com/apache/spark/pull/29761

**Comment by AngersZhuuuu** [comment]
ping @cloud-fan @HyukjinKwon @dongjoon-hyun

**Review by HyukjinKwon — APPROVED** [review]

**Review by cloud-fan — APPROVED** [review]

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Comment by dongjoon-hyun** [comment]
+1, LGTM.

**Comment by cxzl25** [comment]
I think we still check for the empty character case, or add the `supportFieldName` method back.

Here are some tests.

## native
#### native write
```sql
set spark.sql.orc.impl=native;
create table t_1 stored as orc  as select '' ;
```
suceess.
#### native read
````sql
set spark.sql.orc.impl=native;
select t_1;
````

```
java.lang.IllegalArgumentException: Empty quoted field name at '``^'
        at org.apache.orc.impl.ParserUtils.parseName(ParserUtils.java:114)
        at org.apache.orc.OrcUtils.convertTypeFromProtobuf(OrcUtils.java:352)
        at org.apache.orc.impl.OrcTail.<init>(OrcTail.java:72)
        at org.apache.orc.impl.ReaderImpl.extractFileTail(ReaderImpl.java:845)
        at org.apache.orc.impl.ReaderImpl.<init>(ReaderImpl.java:566)
        at org.apache.orc.OrcFile.createReader(OrcFile.java:385)
        at org.apache.spark.sql.execution.datasources.orc.OrcFileFormat.$anonfun$buildReaderWithPartitionValues$2(OrcFileFormat.scala:147)

```

#### hive read
```sql
set spark.sql.orc.impl=hive;
select t_1;
```

```
java.lang.IllegalArgumentException: Empty quoted field name at '``^'
        at org.apache.orc.impl.ParserUtils.parseName(ParserUtils.java:114)
        at org.apache.orc.OrcUtils.convertTypeFromProtobuf(OrcUtils.java:352)
        at org.apache.orc.impl.OrcTail.<init>(OrcTail.java:72)
        at org.apache.orc.impl.ReaderImpl.extractFileTail(ReaderImpl.java:845)
        at org.apache.orc.impl.ReaderImpl.<init>(ReaderImpl.java:566)
        at org.apache.hadoop.hive.ql.io.orc.ReaderImpl.<init>(ReaderImpl.java:63)
        at org.apache.hadoop.hive.ql.io.orc.OrcFile.createReader(OrcFile.java:55)
        at org.apache.spark.sql.hive.orc.OrcFileOperator$.$anonfun$getFileReader$3(OrcFileOperator.scala:76)

```

## hive
#### hive write
```sql
set spark.sql.orc.impl=hive;
create table t_1 stored as orc  as select '' ;
```

```
java.lang.IllegalArgumentException: Error: name expected at the position 7 of 'struct<:string>' but ':' is found.
        at org.apache.hadoop.hive.serde2.typeinfo.TypeInfoUtils$TypeInfoParser.expect(TypeInfoUtils.java:378)
        at org.apache.hadoop.hive.serde2.typeinfo.TypeInfoUtils$TypeInfoParser.parseType(TypeInfoUtils.java:502)
        at org.apache.hadoop.hive.serde2.typeinfo.TypeInfoUtils$TypeInfoParser.parseTypeInfos(TypeInfoUtils.java:329)
        at org.apache.hadoop.hive.serde2.typeinfo.TypeInfoUtils.getTypeInfoFromTypeString(TypeInfoUtils.java:831)
        at org.apache.spark.sql.hive.orc.OrcSerializer.<init>(OrcFileFormat.scala:242)
        at org.apache.spark.sql.hive.orc.OrcOutputWriter.<init>(OrcFileFormat.scala:279)
        at org.apache.spark.sql.hive.orc.OrcFileFormat$$anon$1.newInstance(OrcFileFormat.scala:110)
        at org.apache.spark.sql.execution.datasources.SingleDirectoryDataWriter.newOutputWriter(FileFormatDataWriter.scala:161)
```

**Comment by cloud-fan** [comment]
@AngersZhuuuu is there a way to only check field name in the write side?

**Pull request closed without merging**
