### PR TITLE
[SPARK-5802][MLLIB] cache transformed data in glm

### PR DESCRIPTION
**Pull request by mengxr**
If we need to transform the input data, we should cache the output to avoid re-computing feature vectors every iteration. @dbtsai

### CODE REVIEW

**Comment by mengxr** [comment]
test this please

**Comment by mengxr** [comment]
Merged into master and branch-1.3.

**Comment by dbtsai** [comment]
Sorry for the late reply since I'm traveling recently. My concern is that will this cause "caching twice" in the new ML api? For example, in ml/classification/LogisticRegression.scala, the data is persisted before any transformation, and then we cache the data again after the feature transformation. Should we remove the persist in ml package and just cache it after feature transformation here?

**Comment by joshdevins** [comment]
I have the same concern as @dbtsai in his comment. Most consumers of this API will already be caching their dataset before the learning phase. Without user care, this will introduce effectively double caching (in terms of data size of cached RDDs) and will cause many jobs to fail after upgrading by exceeding available heap for RDD cache. Furthermore, we are making assumptions about how to cache -- in-memory only in this case. Should we parameterise this? Perhaps that will help send the message in the API that there is caching also done before learning. (FWIW, in-memory is definitely the right default choice here.)

See email thread on dev for my specific encountering of this bug: 
http://mail-archives.apache.org/mod_mbox/spark-dev/201502.mbox/%3CCAH5MZvMBjqOST-9Nr9k1z1rUODfSiczr_fV9kwqDFqAMNLC2Zw%40mail.gmail.com%3E

**Comment by petro-rudenko** [comment]
@dbtsai, @joshdevins  here's an issue i have. I'm using new ml pipeline with hyperparameter grid search. Because folds doesn't depend from hyperparameter, i've reimplemented a bit LogisticRegression to not unpersist data:
```scala
class CustomLogisticRegression extends LogisticRegression {
  var oldInstances: RDD[LabeledPoint] = null
  
  override def fit(dataset: SchemaRDD, paramMap: ParamMap): LogisticRegressionModel = {
    println(s"Fitting dataset ${dataset.id} with ParamMap $paramMap.")
    transformSchema(dataset.schema, paramMap, logging = true)
    import dataset.sqlContext._
    val map = this.paramMap ++ paramMap
    val instances = dataset.select(map(labelCol).attr, map(featuresCol).attr)
      .map {
        case Row(label: Double, features: Vector) =>
          LabeledPoint(label, features)
      }

    //For parallel grid search 
    this.synchronized({
      if (oldInstances == null || oldInstances.id != instances.id) {
        if (oldInstances != null) {
          oldInstances.unpersist()
        }
        oldInstances = instances
        instances.setName(s"Instances for LR with ParamMap $paramMap and RDD ${dataset.id}")
        instances.persist(StorageLevel.MEMORY_AND_DISK)
      }
    })

    val lr = (new LogisticRegressionWithLBFGS)
      .setValidateData(false)

    lr.optimizer
      .setRegParam(map(regParam))
      .setNumIterations(map(maxIter))
    val lrOldModel = lr.run(instances)
    val lrm = new LogisticRegressionModel(this, map, lr.run(instances).weights)
    //instances.unpersist()
    // copy model params
    Params.inheritValues(map, this, lrm)
    lrm
  }
}
```

Then for 3 folds in crossvalidation and 3 hyperparameters to LogisticRegression i got something like this:

```
Fitting dataset 11 with ParamMap {
    CustomLogisticRegression-f35ae4d3-regParam: 0.5
}
Fitting dataset 11 with ParamMap {
    CustomLogisticRegression-f35ae4d3-regParam: 0.1
}
Fitting dataset 11 with ParamMap {
    CustomLogisticRegression-f35ae4d3-regParam: 0.01
}

Fitting dataset 12 with ParamMap {
    CustomLogisticRegression-f35ae4d3-regParam: 0.5
}
Fitting dataset 12 with ParamMap {
    CustomLogisticRegression-f35ae4d3-regParam: 0.1
}
Fitting dataset 12 with ParamMap {
    CustomLogisticRegression-f35ae4d3-regParam: 0.01
}
```

So persistence on the model level need to cache folds for hyperparameters grid search, but persistence on GLM level need to speed-up Standart scalar transformation etc. Don't know yet how to do this efficiently without double caching.

**Pull request closed without merging**
