### PR TITLE
[Doc][Minor][SparkR] Update SparkR doc for names, columns and colnames

### PR DESCRIPTION
**Pull request by actuaryzhang**
Update R doc:
1. columns, names and colnames returns a vector of strings, not **list** as in current doc.
2. `colnames<-` does allow the subset assignment, so the length of `value` can be less than the number of columns, e.g., `colnames(df)[1] <- "a"`. 

@felixcheung

### CODE REVIEW

**Comment by actuaryzhang** [comment]
@felixcheung I see lots of the SparkDataFrame methods use the following in examples:
```
 path <- "path/to/file.json"
 df <- read.json(path)
``` 
I'm not sure where this json file resides. Do you think it's better to use a more concrete data example?

**Comment by HyukjinKwon** [comment]
( @actuaryzhang , maybe we could make the PR title more meaningful to summerise the change just for a better shaped PR )

**Comment by srowen** [comment]
Yes please. The file doesn't exist. Its name suggests this is just an example path.

**Comment by felixcheung** [comment]
great thanks!
- we could say return a `vector of` in cases it makes sense
- `colnames<- does allow the subset assignment` - would be good to add example and tests if we don't have it already! ;)
- `path <- "path/to/file.json"` yea it doesn't exist, it's mean to illustrate reading from a file. We have "don't run" for the examples so it doesn't matter much, but if you have ideas on how to make it more clear or concrete I'd definitely welcome that

**Comment by actuaryzhang** [comment]
@HyukjinKwon Thanks. Updated title.
@felixcheung Updated doc and added tests. Thanks!

**Comment by actuaryzhang** [comment]
@srowen @felixcheung 
Thanks for the clarification. I will open another PR to add real data examples for the SparkDataFrame methods. 

I have seen lots of R package document the methods together in a single doc. This way, it's easier to see what methods are available. Also the examples for all methods can be documented together, sharing the same data set (so that we don't have to create one data set for each method). We can use the @describeIn tag to do this. Let me know if this is a good approach.

**Comment by felixcheung** [comment]
@actuaryzhang can you point me to an example you are thinking of?

**Comment by felixcheung** [comment]
yeah, looking at `columns` the example there isn't that great (in fact, the example for all the sql functions are pretty simplistic)

**Comment by felixcheung** [comment]
this merged to master

**Pull request closed without merging**
