### PR TITLE
[SPARK-33264][SQL][DOCS] Add a dedicated page for SQL-on-file in SQL documents

### PR DESCRIPTION
**Pull request by maropu**
### What changes were proposed in this pull request?

This PR intends to add a dedicated page for SQL-on-file in SQL documents.
This comes from the comment: https://github.com/apache/spark/pull/30095/files#r508965149

### Why are the changes needed?

For better documentations.

### Does this PR introduce _any_ user-facing change?

Screen Shot 2020-10-28 at 9 56 59

### How was this patch tested?

N/A

### CODE REVIEW

**Comment by maropu** [comment]
cc: @huaxingao @HyukjinKwon @gatorsmile

**Comment by HyukjinKwon** [comment]
Looks fine

**Review by HyukjinKwon — APPROVED** [review]

**Comment by maropu** [comment]
Thanks for the review, @HyukjinKwon

**Comment by maropu** [comment]
Thanks! Merged to master/3.0.

**Comment by dongjoon-hyun** [comment]
+1, late LGTM. Thanks!

**Pull request closed without merging**
