### PR TITLE
[SPARK-22107] Change as to alias in python quickstart

### PR DESCRIPTION
**Pull request by jgoleary**
## What changes were proposed in this pull request?

Updated docs so that a line of python in the quick start guide executes. Closes #19283

## How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
How does it relate to https://github.com/apache/spark/pull/19283?

**Comment by jgoleary** [comment]
@HyukjinKwon looks like this does the same thing as `name()` is an alias for `alias()`. Happy to close but suggest merging one of these to help future noobs.

**Comment by HyukjinKwon** [comment]
That's fine. I believe we don't usually need a JIRA for a trivial change though. Would you mind double checking if there are similar instances in the PySpark doc?

Also, it'd be great if we add `Closes #19283` in the PR description so that `#19283` can be automatically closed when this PR is merged. It looks `#19283` has gone inactive.

**Comment by jgoleary** [comment]
Updated description. The only other mentions of `as()` I can find in the docs are in Java examples, and the method appears to exist on the Java side.

**Comment by HyukjinKwon** [comment]
ok to test

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master and branch-2.2.

@jgoleary, I merged this considering the first contribution but let's do this in a batch if possible in the future.

**Pull request closed without merging**
