### PR TITLE
[SPARK-42200][INFRA] Put `connect-client-jvm`  into separate test groups and xxx

### PR DESCRIPTION
**Pull request by LuciferYang**
### Does this PR introduce _any_ user-facing change?
No

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
@LuciferYang Please use `Draft` PR instead of `[DON'T MERGE]` tag.

**Comment by LuciferYang** [comment]
Thanks @dongjoon-hyun

**Comment by LuciferYang** [comment]
I guess there may be test failures in `connect-client-jvm` module . If so I will ignore the failed cases first In this pr.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
cc @grundprinzip @hvanhovell @zhenlineo FYI

**Comment by LuciferYang** [comment]
[252f93f](https://github.com/apache/spark/pull/39756/commits/252f93f2e6e7f7b977ebfb90265474cf4065c4f4) move `connect-client-jvm` to another group for one more test

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
@LuciferYang I did this already. Please see the master branch result.
- https://github.com/apache/spark/actions/runs/4020447150/jobs/6908393722

```
[info] ClientE2ETestSuite:
[info] - test spark result schema (174 milliseconds)
...
[info] SparkConnectClientSuite:
[info] - Placeholder test: Create SparkConnectClient (2 milliseconds)
...
[info] DatasetSuite:
[info] - limit (20 milliseconds)
...
[info] All tests passed.
```

**Comment by dongjoon-hyun** [comment]
This is done via SPARK-42046 already, @LuciferYang .
- https://github.com/apache/spark/pull/39549

**Comment by dongjoon-hyun** [comment]
Let me close this PR first to prevent accidental merging.

**Comment by LuciferYang** [comment]
image

Thanks @dongjoon-hyun,  but will this make `connect` test before `connect-client-jvm`?If so, this may hide some problems. I hope to check `connect-client-jvm` before `connect`, which may cause a test failure. You can run `build/sbt clean "connect-client-jvm/test"` locally to check.


> @LuciferYang I did this already. Please see the master branch result.
> 
> * https://github.com/apache/spark/actions/runs/4020447150/jobs/6908393722
> 
> ```
> [info] ClientE2ETestSuite:
> [info] - test spark result schema (174 milliseconds)
> ...
> [info] SparkConnectClientSuite:
> [info] - Placeholder test: Create SparkConnectClient (2 milliseconds)
> ...
> [info] DatasetSuite:
> [info] - limit (20 milliseconds)
> ...
> [info] All tests passed.
> ```

I I checked this log and found that `connect` was tested before `connect-client-jvm`

**Comment by dongjoon-hyun** [comment]
That sounds totally different from the PR title's claim, `Enable GA build and test for connect-client-jvm module`, @LuciferYang .

**Comment by LuciferYang** [comment]
So I push [252f93f](https://github.com/apache/spark/pull/39756/commits/252f93f2e6e7f7b977ebfb90265474cf4065c4f4) and put them into different groups for testing in order to re-produce the test failure in GA

**Comment by dongjoon-hyun** [comment]
You had better elaborate more narrowly about the PR's contribution.

**Comment by LuciferYang** [comment]
> You had better elaborate more narrowly about the PR's contribution.

Got it, it is my bad. I found possible problems after submitting pr, but I didn't update title and pr description in time. I'm very sorry, let me submit another pr for testing.

**Comment by dongjoon-hyun** [comment]
You can revise and reuse this PR because the last commit is still running.

**Comment by dongjoon-hyun** [comment]
JIRA issue is the same. I didn't `Close` it so that you can reopen it.

**Comment by LuciferYang** [comment]
Thanks, let me reopen this one and make it as Draft first.

**Comment by LuciferYang** [comment]
hmm... it seems that a new pr will be submitted. I can't reopen the pr you closed. Let me wait for the test results first

**Comment by dongjoon-hyun** [comment]
I reopened this for you.

**Comment by LuciferYang** [comment]
> I reopened this for you.

Thank you very much. Let me try to reproduce the local test error on the GA in this pr. If it can be reproduced, I will update Pr description and title later

**Comment by dongjoon-hyun** [comment]
Got it.

**Comment by LuciferYang** [comment]
I can't reproduce the problem I encountered in the local test through GA, because GA has done a lot of preparation work, so that the jar that should not have been found can be found.

Let me close this pr.

Thank you very much for your help @dongjoon-hyun

**Comment by dongjoon-hyun** [comment]
I guess you hit the requirement of assembly building. Last time, I asked the similar questions on some `connector` PR. If you hit the local failure again, please try `build/sbt package` first and run the commit.

**Comment by LuciferYang** [comment]
> I guess you hit the requirement of assembly building. Last time, I asked the similar questions on some `connector` PR. If you hit the local failure again, please try `build/sbt package` first and run the module testing you posted here..

Yes, sbt can solve this problem by this way. Maven needs more steps, such as:

```
build/mvn clean install -pl connector/connect/server -am -DskipTests
build/mvn clean install -pl connector/connect/client/jvm -DskipTests
build/mvn test -pl connector/connect/client/jvm
```

This can solve the problem that the `jar cannot be found`, but there is still `Failed to start the test server on port xxx` problem(sbt local test no this issue). I haven't found the root cause

**Pull request closed without merging**
