### PR TITLE
[SQL][minor] Simplify data source predicate filter translation.

### PR DESCRIPTION
**Pull request by rxin**
## What changes were proposed in this pull request?

This is a small patch to rewrite the predicate filter translation in DataSourceStrategy. The original code used excessive functional constructs (e.g. unzip) and was very difficult to understand.
## How was this patch tested?

Should be covered by existing tests.

### CODE REVIEW

**Comment by rxin** [comment]
cc @yhuai  / @liancheng  I think you two wrote some of this.

**Comment by yhuai** [comment]
LGTM

**Comment by yhuai** [comment]
Merging to master.

**Comment by liancheng** [comment]
LGTM

**Pull request closed without merging**
