### PR TITLE
[SPARK-28516][SQL][FOLLOWUP] Remove try_to_char function

### PR DESCRIPTION
**Pull request by cloud-fan**
### What changes were proposed in this pull request?

`try_to_char` is exactly the same as `to_char` now, because `to_char` only fails if the format string is invalid, which `try_to_char` will fai as well. This PR removes `try_to_char`.

### Does this PR introduce _any_ user-facing change?

No because the function is not released yet.

### How was this patch tested?

N/A

### CODE REVIEW

**Comment by cloud-fan** [comment]
cc @dtenedor @gengliangwang

**Review by dtenedor — APPROVED** [review]
Thanks for taking care of this cleanup.

**Comment by gengliangwang** [comment]
We need to remove it from docs/sql-ref-number-pattern.md as well

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by cloud-fan** [comment]
> We need to remove it from docs/sql-ref-number-pattern.md as well

We didn't mention `try_to_char` there :P

**Comment by cloud-fan** [comment]
thanks for the review, merging to master!

**Comment by HyukjinKwon** [comment]
We actually did ...

```
docs/sql-ref-number-pattern.md:The following examples use the `to_number`, `try_to_number`, `to_char`, and `try_to_char` SQL
docs/sql-ref-number-pattern.md:> SELECT try_to_char(decimal(-12454.8), '99,999.9S');
docs/sql-ref-number-pattern.md:> SELECT try_to_char(decimal(12454.8), 'L99,999.9');
docs/sql-ref-number-pattern.md:  Error: cannot resolve 'try_to_char(Decimal(12454.8), 'L99,999.9')' due to data type mismatch:
```

**Pull request closed without merging**
