### PR TITLE
[SPARK-11270] [STREAMING] Add improved equality testing for TopicAndPartition from the Kafka Streaming API

### PR DESCRIPTION
**Pull request by ontarionick**
@jerryshao @tdas 

I know this is kind of minor, and I know you all are busy, but this brings this class in line with the `OffsetRange` class, and makes tests a little more concise.

Instead of doing something like:

```
assert topic_and_partition_instance._topic == "foo"
assert topic_and_partition_instance._partition == 0
```

You can do something like:

```
assert topic_and_partition_instance == TopicAndPartition("foo", 0)
```

Before:

```
>>> from pyspark.streaming.kafka import TopicAndPartition
>>> TopicAndPartition("foo", 0) == TopicAndPartition("foo", 0)
False
```

After:

```
>>> from pyspark.streaming.kafka import TopicAndPartition
>>> TopicAndPartition("foo", 0) == TopicAndPartition("foo", 0)
True
```

I couldn't find any tests - am I missing something?

### CODE REVIEW

**Comment by jerryshao** [comment]
LGTM, the test is in `pyspark/streaming/tests.py`, you can refer to it.

**Comment by manygrams** [comment]
Tests added!

**Comment by tdas** [comment]
this is ok to test

**Comment by tdas** [comment]
ok to test

**Comment by tdas** [comment]
LGTM. Will merge when tests pass.

**Comment by tdas** [comment]
Could you update the code to fix the python style issues?

**Comment by manygrams** [comment]
@tdas fixed!

**Pull request closed without merging**
