### PR TITLE
[SPARK-16029][SPARKR] SparkR add dropTempView and deprecate dropTempTable

### PR DESCRIPTION
**Pull request by felixcheung**
## What changes were proposed in this pull request?

Add dropTempView and deprecate dropTempTable
## How was this patch tested?

unit tests

@shivaram @liancheng

### CODE REVIEW

**Comment by liancheng** [comment]
LGTM pending Jenkins. Thanks!

**Comment by shivaram** [comment]
Thanks @felixcheung @liancheng - LGTM. Merging this to master, branch-2.0

Are there any other catalog functions that have changed in Spark 2.0 that we also expose in SparkR ? Or are `createTempTable` and `dropTempTable` the only ones ?

**Comment by felixcheung** [comment]
Only registerTempTable and dropTempTable have name changes.

**Comment by liancheng** [comment]
@shivaram I think we've covered all of them.

**Pull request closed without merging**
