### PR TITLE
Diversity

### PR DESCRIPTION
**Pull request by jflittner**
Adding a bit of diversity to the people.json file.

## What changes were proposed in this pull request?

Adding diversity to examples/src/main/resources/people.json

## How was this patch tested?

The JSON is valid.

Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Please review http://spark.apache.org/contributing.html before opening a pull request.

Also, I don't think it's worth to fix.

**Comment by kmarekspartz** [comment]
To clarify, which portion of those guidelines is this not compliant with?

There’s no JIRA, but the guidelines are clear that no JIRA is required for contributions like these.

**Comment by kmarekspartz** [comment]
> A bug may be reported by creating a JIRA but without creating a pull request 

> However, trivial changes, where the what should change is virtually the same as the how it should change do not require a JIRA. Example: Fix typos in Foo scaladoc

**Comment by HyukjinKwon** [comment]
See all the minor PRs https://github.com/apache/spark/pulls?q=is%3Apr+minor+is%3Aclosed

Why do you think the guide doesn't work for this PR specifically? What makes you think this PR complies the doc? Shall we fix the doc then?

**Comment by kmarekspartz** [comment]
The guidelines say nothing about requirements for minor PRs. If you are going to close minor PRs for being non-compliant, please upgrade the guidelines so that people know the undocumented hoops they have to jump through to make a contribution.

Note, too: the term “guidelines” implies optional. You may want to rebrand them as “contribution requirements” when you add the currently undocumented requirements.

**Comment by HyukjinKwon** [comment]
No, read the comment and document above. I closed this PR because the change does't look worth to fix. Title should be specific: `Title may be the JIRA’s title or a more specific title describing the PR itself.`

**Comment by HyukjinKwon** [comment]
Here's also the place to discuss about the change itself not the policy. If you're unhappy about it and think something should be changed, please send an email to dev mailing list and discuss in the mailing list about this rather then wasting our time here. I don't see nothing wrong here tho.

**Comment by HyukjinKwon** [comment]
More specifically that's an example. I think the example jsons already contain what to show enough. That's not even test case that's previously not covered. What's the gain of this PR? And why are you wasting your time here?

**Comment by jflittner** [comment]
Hello @HyukjinKwon and @kmarekspartz. I appreciate all of the conversation and thoughts on this PR. I apologize if I did not follow the PR standards and certainly would not want to set some sort of precedent for less than ideal PR etiquette.

All of that said, @HyukjinKwon I would encourage you and other Spark committers to consider adding some diversity to your people.json and elsewhere in the projects you work on. This project is used as a reference for many in the data community. Anything we can do to be more inclusive is very much worth it.

Thank you very much for your consideration.

**Comment by HyukjinKwon** [comment]
Again, I don't see the gain from what this PR proposes considering all potential overhead. The examples already contains possible cases to show. No point of some more people in the JSON examples. Since this project is used as a reference in many places, I would like you to encourage to focus on more important stuff rather then putting efforts on such minor stuff.

**Pull request closed without merging**
