### PR TITLE
[MINOR][DOC] Fix a typo 'lister' -> 'listener'

### PR DESCRIPTION
**Pull request by lys0716**
## What changes were proposed in this pull request?

Fix the typo in java doc.

## How was this patch tested?

N/A

Signed-off-by: Yishuang Lu <luystu@gmail.com>

### CODE REVIEW

**Comment by srowen** [comment]
There are 3 more instances of this typo; can you fix all of them?
Any more typos you see?

**Comment by HyukjinKwon** [comment]
ok to test

**Review by HyukjinKwon — COMMENTED** [review]
Let's add some more similar instances next time. LGTM considering it's the first contribution.

**Comment by HyukjinKwon** [comment]
I am merging this because related linter checks passed.

**Pull request closed without merging**
