### PR TITLE
[SPARK-47461][CORE] Remove private function `totalRunningTasksPerResourceProfile` from `ExecutorAllocationManager`

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr remove private function `totalRunningTasksPerResourceProfile` from `ExecutorAllocationManager`.

This function only used by test in `ExecutorAllocationManagerSuite` and this pr also change the test function to directly call `manager.listener.totalRunningTasksPerResourceProfile` instead of invoking the private function `ExecutorAllocationManager#totalRunningTasksPerResourceProfile` through reflection.

### Why are the changes needed?
Code clean up

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass GitHub Actions

### Was this patch authored or co-authored using generative AI tooling?
No

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Review by mridulm — COMMENTED** [review]
This exists to ensure the call happens in the synchronized block ?
+CC @tgravescs

**Comment by tgravescs** [comment]
well it definitely changes  the synchronization, everywhere else that is referenced is in synchronized block.  Now since its only testing I'm not sure if you will see any issues there.  At the same time this feels like one of those prs that doesn't need to be done and is just introducing risk.

It was also abstracting things so you weren't going straight into the listener.  I think listener should really be private here but looking at history was opened up for a test that doesn't exist.

Personally I would prefer to see this reverted

**Comment by dongjoon-hyun** [comment]
To @mridulm and @tgravescs , do you mean you are depending on the `private` method of `ExecutorAllocationManager` somehow? Just for my understanding, could you elaborate how you are affected?
```scala
  private def totalRunningTasksPerResourceProfile(id: Int): Int = synchronized {
    listener.totalRunningTasksPerResourceProfile(id)
  }
```

**Comment by dongjoon-hyun** [comment]
Do you mean that we need to revert this commit because `ExecutorAllocationManagerSuite` needs that for stable test coverage?

**Comment by mridulm** [comment]
I was looking at it from point of view of, is the change safe - is the behavior the same before and after ?
From that point of view, at face value of the PR, it appears that it need not be the same after the PR - the access was protected earlier by a synchronized lock, and could have ensured visibility of updates.

I have ofcourse not done an analysis of whether this safety is required, are there other mitigating reasons why it is still safe (perhaps an outer lock, etc) ... and so tagged Tom.

Note that there is also diminishing reasons given this is for tests, and is a private method :-)

**Comment by mridulm** [comment]
To give context, I am prototyping dynamically adapting a stage/tasks resource profile based on runtime execution behavior, and so happened to have looked at this code recently and had gone through a similar "is this method useless" question :-)

**Comment by dongjoon-hyun** [comment]
Thank you for the context, @mridulm and @tgravescs .

WDYT, @LuciferYang . Shall we revert this simply for now and revisit later (if needed), @LuciferYang ?

**Comment by LuciferYang** [comment]
1. I am fine to revert this commit, but while revert, I think some comments should be added to the `totalRunningTasksPerResourceProfile ` function to clarify that this function needs to be retained for testing.
2. Another thing I want to clarify is, should we restrict the access level of listener to private? Would this action pose any risks? 

@dongjoon-hyun @tgravescs @mridulm

**Comment by dongjoon-hyun** [comment]
+1 for (1) adding a new comment to clarify that this `synchronized` function needs to be retained for testing.

I'm not sure for (2) because it's a separate issue in this context.

**Comment by LuciferYang** [comment]
Submitted a PR for revert: https://github.com/apache/spark/pull/45602

**Pull request closed without merging**
