### PR TITLE
[SPARK-34275][CORE][SQL][MLLIB] Replaces filter and size with count

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
Use `count` to simplify `find + size(or length)` operation, it's semantically consistent, but looks simpler.

**Before**
```
seq.filter(p).size
```

**After**
```
seq.count(p)
```

### Why are the changes needed?
Code Simpilefications.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass the Jenkins or GitHub Action

### CODE REVIEW

**Comment by LuciferYang** [comment]
If need other PR for branch-3.0 and branch-2.4, please ping me

**Comment by HyukjinKwon** [comment]
Yeah, let's do that. When we fix such kind of things, the conflicts are one of the usual problems pointed out by people. It should be better to port them back.

**Review by HyukjinKwon — APPROVED** [review]
LGTM

**Comment by HyukjinKwon** [comment]
BTW, they are all instances, right?

**Comment by LuciferYang** [comment]
> BTW, they are all instances, right?
Yes

**Comment by LuciferYang** [comment]
> Yeah, let's do that. When we fix such kind of things, the conflicts are one of the usual problems pointed out by people. It should be better to port them back.

OK

**Comment by LuciferYang** [comment]
@HyukjinKwon 

- branch-3.0: https://github.com/apache/spark/pull/31375
- branch-2.4: https://github.com/apache/spark/pull/31376

**Comment by dongjoon-hyun** [comment]
Why do we need to backport improvement?

**Comment by HyukjinKwon** [comment]
Merged to master and branch-3.1.

**Comment by LuciferYang** [comment]
thx @HyukjinKwon

**Pull request closed without merging**
