### PR TITLE
[MINOR][INFRA][3.3] Add ANTLR generated files to .gitignore

### PR DESCRIPTION
**Pull request by pan3793**
### What changes were proposed in this pull request?

Backport https://github.com/apache/spark/pull/35838 to 3.3

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Technically, this is not a release blocker.

**Comment by dongjoon-hyun** [comment]
In addition, if we want to backport this, we had better backport the original one with the original authorship. Let me close this PR because of that issue.

**Comment by pan3793** [comment]
> In addition, if we want to backport this, we had better backport the original one with the original authorship. Let me close this PR because of that issue.

Would you please backport it to 3.3 directly? It should be safe and won't break the release.

**Comment by dongjoon-hyun** [comment]
You can ask backport on the original PR. That's the way we do. 

BTW, the following is not a criteria for back-portable patch. We are already doing RCs.
> It should be safe and won't break the release.

**Comment by pan3793** [comment]
> You can ask backport on the original PR. 

Got it, thanks

**Pull request closed without merging**
