### PR TITLE
[SPARK-35926][SQL] Add support YearMonthIntervalType for width_bucket

### PR DESCRIPTION
**Pull request by Peng-Lei**
### What changes were proposed in this pull request?
Support width_bucket(YearMonthIntervalType, YearMonthIntervalType, YearMonthIntervalType, Long), it return long result
 eg:
```
width_bucket(input_value, min_value, max_value, bucket_nums)
width_bucket(INTERVAL '1' YEAR, INTERVAL '0' YEAR, INTERVAL '10' YEAR, 10)
It will divides the range between the max_value and min_value into 10 buckets.
[ INTERVAL '0' YEAR,  INTERVAL '1' YEAR),  [ INTERVAL '1' YEAR,  INTERVAL '2' YEAR)......  [INTERVAL '9' YEAR,  INTERVAL '10' YEAR)
Then, calculates which bucket the given input_value locate.
```

The function `width_bucket` is introduced from [SPARK-21117](https://issues.apache.org/jira/browse/SPARK-21117)
### Why are the changes needed?
[35926](https://issues.apache.org/jira/browse/SPARK-35926)
1. The `WIDTH_BUCKET` function assigns values to buckets (individual segments) in an equiwidth histogram. The ANSI SQL Standard Syntax is like follow: `WIDTH_BUCKET( expression, min, max, buckets)`. [Reference](https://www.oreilly.com/library/view/sql-in-a/9780596155322/re91.html). 
2. `WIDTH_BUCKET` just support `Double` at now, Of course, we can cast `Int` to `Double` to use it. But we cloud not cast `YearMonthIntervayType` to `Double`. 
3. I think it has a use scenario. eg:  Histogram of employee years of service, the `years of service` is a column of `YearMonthIntervalType` dataType.

### Does this PR introduce _any_ user-facing change?
Yes. The user can use `width_bucket` with YearMonthIntervalType.

### How was this patch tested?
Add ut test

### CODE REVIEW

**Comment by Peng-Lei** [comment]
@MaxGekk Could you take a look?

**Comment by MaxGekk** [comment]
> Why are the changes needed?
> 35926

@Peng-Lei I would like to see why the changes are really needed. Could you explain that, please.

Just in case, I would like to propose to focus on feature parity with `CalendarIntervalType` in the release 3.2. So, users could smoothly replace it by new ANSI types. Could you re-check Spark's code base, and point out the places where we miss handling of the ANSI interval types.

**Comment by Peng-Lei** [comment]
> > Why are the changes needed?
> > 35926
> 
> @Peng-Lei I would like to see why the changes are really needed. Could you explain that, please.
> 
> Just in case, I would like to propose to focus on feature parity with `CalendarIntervalType` in the release 3.2. So, users could smoothly replace it by new ANSI types. Could you re-check Spark's code base, and point out the places where we miss handling of the ANSI interval types.

@MaxGekk Firstly, the `WIDTH_BUCKET` function assigns values to buckets (individual segments) in an equiwidth histogram. The ANSI SQL Standard Syntax is like follow: `WIDTH_BUCKET( expression, min, max, buckets)`. [Reference](https://www.oreilly.com/library/view/sql-in-a/9780596155322/re91.html). Secondly, `WIDTH_BUCKET` just support `Double` at now, Of course, we can cast `Int` to `Double` to use it. But we cloud not cast `YearMonthIntervayType` to `Double`. Finally, I think it has a use scenario. eg:  Histogram of employee years of service, the `years of service` is a column of `YearMonthIntervalType` dataType.
Maybe I'm wrong. When I studied the `WIDTH_BUCKET` code, I wondered if I could support `YearMonthIntervalType`. Thank you for reminding me. I will check whether there are miss handling of the ANSI interval types and test ANSI interval types features added.

**Comment by MaxGekk** [comment]
> Firstly, ... Secondly, ... Finally, ...

Thank you for the explanation. Could you add the text to the section `Why are the changes needed?` in PR's description.

**Review by MaxGekk — APPROVED** [review]

**Pull request closed without merging**
