### PR TITLE
[SPARK-36257][SQL] Updated the version of TimestampNTZ related changes as 3.3.0

### PR DESCRIPTION
**Pull request by gengliangwang**
### What changes were proposed in this pull request?

As we decided to release TimestampNTZ type in Spark 3.3, we should update the versions of TimestampNTZ related changes as 3.3.0.

### Why are the changes needed?

Correct the versions in documentation/code comment.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Existing UT

### CODE REVIEW

**Comment by gengliangwang** [comment]
cc @beliefer as well

**Review by cloud-fan — APPROVED** [review]

**Review by yaooqinn — APPROVED** [review]

**Comment by gengliangwang** [comment]
jenkins, retest this please

**Review by beliefer — APPROVED** [review]
LGTM

**Review by HyukjinKwon — APPROVED** [review]

**Review by MaxGekk — COMMENTED** [review]
How about:
https://github.com/apache/spark/blob/e9b18b07992e7871fdd2ea75fd5fd9a1c04f6e07/sql/core/src/main/scala/org/apache/spark/sql/functions.scala#L2984-L2986

**Comment by gengliangwang** [comment]
@MaxGekk Thanks, I have updated the code.

**Review by MaxGekk — APPROVED** [review]

**Comment by gengliangwang** [comment]
Merging to master

**Pull request closed without merging**
