### PR TITLE
[SPARK-31171][SQL][followup] update document

### PR DESCRIPTION
**Pull request by cloud-fan**
### What changes were proposed in this pull request?

A followup of https://github.com/apache/spark/pull/27936 to update document.

### Why are the changes needed?

correct document

### Does this PR introduce any user-facing change?

no

### How was this patch tested?

N/A

### CODE REVIEW

**Comment by cloud-fan** [comment]
cc @dongjoon-hyun @HeartSaVioR @maropu

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Review by maropu — APPROVED** [review]

**Comment by maropu** [comment]
Merged to master/3.0.

**Comment by HeartSaVioR** [comment]
Late LGTM

**Pull request closed without merging**
