### PR TITLE
[SPARK-5176] The thrift server does not support cluster mode

### PR DESCRIPTION
**Pull request by tpanningnextcen**
Output an error message if the thrift server is started in cluster mode.

### CODE REVIEW

**Comment by andrewor14** [comment]
@liancheng

**Comment by andrewor14** [comment]
ok to test

**Comment by liancheng** [comment]
@andrewor14 Yes, currently the Thrift server doesn't support YARN cluster mode. I'm trying to deliver a fix for this before 1.3.0 code freeze. I think it's OK to have this PR before I get it done.

**Comment by andrewor14** [comment]
This is also true for standalone cluster mode right, not just YARN cluster mode?

**Comment by liancheng** [comment]
@andrewor14 Per our offline discuss, it still requires some minor work to make the Thrift server support standalone cluster mode (mainly related to the `spark-internal` argument). Currently, at least we don't want to add it in 1.3.0 yet. So this PR LGTM.

@tpanningnextcen Thanks for working on this!

**Comment by andrewor14** [comment]
Yup LGTM. I will merge this into master shortly.

**Pull request closed without merging**
