### PR TITLE
[SPARK-48323][SQL] DB2: Map BooleanType to BOOLEAN instead of CHAR(1)

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

This PR maps BooleanType to BOOLEAN instead of CHAR(1) when writing DB2 tables, users can restore the old behavior by setting spark.sql.legacy.db2.booleanTypeMapping.enabled to true

### Why are the changes needed?

DB2 has supported boolean since v9.7, which is already EOL. It's reasonable to BooleanType to BOOLEAN

### Does this PR introduce _any_ user-facing change?

yes, spark.sql.legacy.db2.booleanTypeMapping.enabled is provided to restore
### How was this patch tested?

new tests

### Was this patch authored or co-authored using generative AI tooling?

no

### CODE REVIEW

**Comment by yaooqinn** [comment]
cc @dongjoon-hyun @cloud-fan @LuciferYang thanks

**Comment by LuciferYang** [comment]
Due to the existence of `user-facing change`, should it be documented in the migration document?

**Comment by yaooqinn** [comment]
> should it be documented in the migration document?

Thank you @LuciferYang for the reminder. I missed that.

**Review by LuciferYang — APPROVED** [review]

**Comment by yaooqinn** [comment]
Merged to master. Thank you @LuciferYang

**Comment by cloud-fan** [comment]
late LGTM

**Pull request closed without merging**
