### PR TITLE
[SPARK-21596] Update StreamExecution.scala

### PR DESCRIPTION
**Pull request by ddna1021**
[SPARK-21596]

link to https://issues.apache.org/jira/browse/SPARK-21596   

## What changes were proposed in this pull request?

class OffsetSeqLog is subclass of HDFSMetadataLog，so it should ensure places calling OffsetSeqLog.get check the return value also.

## How was this patch tested?

jenkins

### CODE REVIEW

**Comment by srowen** [comment]
I'm not clear how this relates to the JIRA. You are just changing an error message. Does this occur in practice?

**Comment by ddna1021** [comment]
[SPARK-21596] means we must check the return value HDFSMetadataLog.get(), so it should  ensure all the places taht calling the get() method of subclass of HDFSMetadataLog check the return value.

**Comment by viirya** [comment]
Is any chance you link to wrong JIRA?

**Comment by ddna1021** [comment]
[SPARK-21596] means we must check the return value HDFSMetadataLog.get(), so it should ensure all the places taht calling the get() method of subclass of HDFSMetadataLog check the return value.

**Comment by viirya** [comment]
Ok. But there is already a PR created #18799.

**Comment by ddna1021** [comment]
Ok,that menas my PR is invalid？

**Comment by viirya** [comment]
@ddna1021 Thanks for working on this. The PR is created days ago and looks more comprehensive. So I'd suggest we go with that one.

**Comment by ddna1021** [comment]
Should I close my PR，Sorry，I am a rookie

**Comment by srowen** [comment]
Please close this

**Pull request closed without merging**
