### PR TITLE
[SPARK-14987] [SQL] inline hive-service (cli) into sql/hive-thriftserver

### PR DESCRIPTION
**Pull request by davies**
## What changes were proposed in this pull request?

This PR copy the thrift-server from hive-service-1.2 (including  TCLIService.thrift and generated Java source code) into sql/hive-thriftserver, so we can do further cleanup and improvements.
## How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by rxin** [comment]
LGTM pending Jenkins.

**Comment by rxin** [comment]
cc @JoshRosen can you take a look at the dep changes?

**Comment by rxin** [comment]
Whenever you change the dependencies you'd need to change the file I think.

**Comment by rxin** [comment]
Actually it seems like some files are missing?

For example, ThriftBinaryCLIService.java is not there, but it is in Hive.

**Comment by JoshRosen** [comment]
The current build dependency changes seem tentatively okay to me. Removing the ASM 3 dependency should not be a problem because Spark depends on a shaded copy anyways.

**Comment by rxin** [comment]
Merging in master.

**Pull request closed without merging**
