### PR TITLE
[SPARK-38844][PYTHON][TESTS][FOLLOW-UP] Test pyspark.pandas.tests.test_generic_functions

### PR DESCRIPTION
**Pull request by HyukjinKwon**
### What changes were proposed in this pull request?

This is a minor followup of https://github.com/apache/spark/pull/36127 that actually activates the tests added.

### Why are the changes needed?

To make sure the regression tests running in CI.

### Does this PR introduce _any_ user-facing change?

No, test-only.

### How was this patch tested?

CI in this PR should test it out.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Build link: https://github.com/HyukjinKwon/spark/runs/6086874477

**Comment by zhengruifeng** [comment]
great catch! thanks @HyukjinKwon !

**Review by Yikun — APPROVED** [review]

**Review by itholic — APPROVED** [review]
Thanks!

**Comment by HyukjinKwon** [comment]
All pyspark tests passed.

Merged to master.

**Comment by HyukjinKwon** [comment]
Thanks all!

**Comment by dongjoon-hyun** [comment]
+1, LGTM.

**Pull request closed without merging**
