### PR TITLE
[SPARK-14205][SQL] remove trait Queryable

### PR DESCRIPTION
**Pull request by cloud-fan**
## What changes were proposed in this pull request?

After DataFrame and Dataset are merged, the trait `Queryable` becomes unnecessary as it has only one implementation. We should remove it.
## How was this patch tested?

existing tests.

### CODE REVIEW

**Comment by cloud-fan** [comment]
cc @liancheng @rxin @gatorsmile

**Comment by rxin** [comment]
```
[error]  * the type hierarchy of class org.apache.spark.sql.Dataset is different in current version. Missing types {org.apache.spark.sql.execution.Queryable}
[error]    filter with: ProblemFilters.exclude[MissingTypesProblem]("org.apache.spark.sql.Dataset")
```

**Comment by rxin** [comment]
LGTM (except the mima issue).

**Comment by liancheng** [comment]
LGTM

**Comment by gatorsmile** [comment]
LGTM

**Comment by rxin** [comment]
```
[error] /home/jenkins/workspace/SparkPullRequestBuilder/sql/core/src/test/scala/org/apache/spark/sql/QueryTest.scala:31: object Queryable is not a member of package org.apache.spark.sql.execution
[error] import org.apache.spark.sql.execution.{LogicalRDD, Queryable}
[error]        ^
[error] /home/jenkins/workspace/SparkPullRequestBuilder/sql/core/src/test/scala/org/apache/spark/sql/QueryTest.scala:185: not found: type Queryable
[error]   def assertCached(query: Queryable, numCachedTables: Int = 1): Unit = {
[error]                           ^
[error] /home/jenkins/workspace/SparkPullRequestBuilder/sql/core/src/test/scala/org/apache/spark/sql/QueryTest.scala:291: not found: type Queryable
[error]   def assertEmptyMissingInput(query: Queryable): Unit = {
[error]                                      ^
```

**Comment by rxin** [comment]
Thanks - merging in master.

**Pull request closed without merging**
