### PR TITLE
Add a config option to print DAG.

### PR DESCRIPTION
**Pull request by KaiXinXiaoLei**
Add a config option "spark.rddDebug.enable" to check whether to print DAG info. When "spark.rddDebug.enable" is true, it will print information about DAG in the log.

### CODE REVIEW

**Comment by ScrapCodes** [comment]
You can print the same details by calling rdd.toDebugString in your program ?

**Comment by KaiXinXiaoLei** [comment]
15/01/26 22:38:37 INFO SparkContext: RDD.toDebugString:
 (12) MappedRDD[13] at map at dagPrint.scala:26 []
 |   MappedRDD[12] at map at dagPrint.scala:25 []
 |   FlatMappedValuesRDD[11] at join at dagPrint.scala:24 []
 |   MappedValuesRDD[10] at join at dagPrint.scala:24 []
 |   CoGroupedRDD[9] at join at dagPrint.scala:24 []
 |   ShuffledRDD[4] at reduceByKey at dagPrint.scala:17 []
 +-(2) MappedRDD[3] at map at dagPrint.scala:16 []
    |  MappedRDD[2] at map at dagPrint.scala:15 []
    |  /data.txt MappedRDD[1] at textFile at dagPrint.scala:14 []
    |  /data.txt HadoopRDD[0] at textFile at dagPrint.scala:14 []
 +-(2) MappedRDD[8] at map at dagPrint.scala:22 []
    |  MappedRDD[7] at map at dagPrint.scala:21 []
    |  /data2.txt MappedRDD[6] at textFile at dagPrint.scala:20 []
    |  /data2.txt HadoopRDD[5] at textFile at dagPrint.scala:20 []

**Comment by rxin** [comment]
I think @ScrapCodes's question is ... is this necessary, given users can easily print the dag themselves?

**Comment by pwendell** [comment]
@rxin I have noticed that very few users know about `toDebugString`. Maybe we should open a JIRA to add better documentation for that function (i.e. discuss it in the programming guide). Overall, I agree with you and @ScrapCodes in that I'm not sure this particular flag is super useufl.

**Comment by rxin** [comment]
Actually now I think about it - users don't always control the RDDs. For example, if they are using the ML pipeline API or calling some other libraries. Maybe there is some merit in including this, especially if they are off by default?

**Comment by pwendell** [comment]
Fair, but the issue is in some cases (e.g. GraphX) the printed representation of the DAG can be many hundreds of lines long. could that potentially explode the output?

**Comment by KaiXinXiaoLei** [comment]
I think, when running a application, users just need change a config option, not modify binary code. And the default value of  this config option is false. When users need get DAG info, users will go to modify this value. So i think there is a small chance of exploded output, or there is  Impossible of  exploded output.

**Comment by KaiXinXiaoLei** [comment]
@pwendell 
For example, I had completed binary package, and put it on spark cluster. Now i want to get DAG info, i not need to change code and build again. I just change a config option. After i had got info, I change the config option to false. So I think there is impossible of exploded output. Thanks.

**Comment by srowen** [comment]
ok to test

**Comment by rxin** [comment]
Maybe we can include this, provided that it is off by default.

That said, I think a better name for this option is "spark.logLineage".

**Comment by KaiXinXiaoLei** [comment]
@rxin 
OK. I had changed the option name to "spark.logLineage". Thanks.

**Comment by rxin** [comment]
Thanks. I've merged this.

**Pull request closed without merging**
