### PR TITLE
[SPARK-20291][SQL][BACKPORT] NaNvl(FloatType, NullType) should not be cast to N…

### PR DESCRIPTION
**Pull request by dbtsai**
…aNvl(DoubleType, DoubleType)

## What changes were proposed in this pull request?

This is a backport of https://github.com/apache/spark/pull/17606

`NaNvl(float value, null)` will be converted into `NaNvl(float value, Cast(null, DoubleType))` and finally `NaNvl(Cast(float value, DoubleType), Cast(null, DoubleType))`.

This will cause mismatching in the output type when the input type is float.

By adding extra rule in TypeCoercion can resolve this issue.

## How was this patch tested?

unite tests.

Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Comment by viirya** [comment]
Shall we add backport tag in the title?

**Comment by dbtsai** [comment]
@viirya Added. Thanks.

**Comment by gatorsmile** [comment]
retest this please

**Review by gatorsmile — APPROVED** [review]
Thanks! Merging to 2.0.

Could you close it?

**Comment by dbtsai** [comment]
Thanks.

**Pull request closed without merging**
