### PR TITLE
[SPARK-16580][CORE] class Accumulator in package spark is deprecated: use AccumulatorV2

### PR DESCRIPTION
**Pull request by keypointt**
https://issues.apache.org/jira/browse/SPARK-16580#
## What changes were proposed in this pull request?

When I was working on the R wrapper, I found the compile warn.

```
> project mllib
> console
[warn] /Users/renxin/workspace/spark/core/src/main/scala/org/apache/spark/api/python/PythonRDD.scala:78: class Accumulator in package spark is deprecated: use AccumulatorV2
[warn]     accumulator: Accumulator[JList[Array[Byte]]])
[warn]
[warn] /Users/renxin/workspace/spark/core/src/main/scala/org/apache/spark/api/python/PythonRDD.scala:78: class Accumulator in package spark is deprecated: use AccumulatorV2
[warn]     accumulator: Accumulator[JList[Array[Byte]]])
[warn]
[warn] /Users/renxin/workspace/spark/core/src/main/scala/org/apache/spark/api/python/PythonRDD.scala:78: class Accumulator in package spark is deprecated: use AccumulatorV2
[warn]     accumulator: Accumulator[JList[Array[Byte]]])
[warn]
[warn] /Users/renxin/workspace/spark/core/src/main/scala/org/apache/spark/api/python/PythonRDD.scala:71: class Accumulator in package spark is deprecated: use AccumulatorV2
[warn] private[spark] case class PythonFunction(
[warn]
[warn] /Users/renxin/workspace/spark/core/src/main/scala/org/apache/spark/api/python/PythonRDD.scala:78: class Accumulator in package spark is deprecated: use AccumulatorV2
[warn]     accumulator: Accumulator[JList[Array[Byte]]])
[warn]
[warn] /Users/renxin/workspace/spark/core/src/main/scala/org/apache/spark/api/python/PythonRDD.scala:873: trait AccumulatorParam in package spark is deprecated: use AccumulatorV2
[warn]   extends AccumulatorParam[JList[Array[Byte]]] {
[warn]
[warn] /Users/renxin/workspace/spark/core/src/main/scala/org/apache/spark/util/AccumulatorV2.scala:459: trait AccumulableParam in package spark is deprecated: use AccumulatorV2
[warn]     param: org.apache.spark.AccumulableParam[R, T]) extends AccumulatorV2[T, R] {
[warn]
[warn] /Users/renxin/workspace/spark/core/src/main/scala/org/apache/spark/util/AccumulatorV2.scala:459: trait AccumulableParam in package spark is deprecated: use AccumulatorV2
[warn]     param: org.apache.spark.AccumulableParam[R, T]) extends AccumulatorV2[T, R] {
[warn]
```

Using `AccumulatorV2` and warnings on "PythonRDD.scala:78" and "PythonRDD.scala:71" disappeared. 

I didn't change `AccumulableParam` or `AccumulatorParam`, since they are being used in `class LegacyAccumulatorWrapper` of `AccumulatorV2`.
## How was this patch tested?

Tested manually on my laptop.

### CODE REVIEW

**Comment by srowen** [comment]
@keypointt what do you think about following up on this?

**Comment by keypointt** [comment]
@srowen sorry, I had a very busy week passed, now I have time to look into it. Will keep you posted :)

**Comment by MLnick** [comment]
I think #14467 is addressing this, and seems to be further along (it is a little more involved to make it work than what you have here)

**Comment by srowen** [comment]
Yeah let's close this one as a duplicate

**Comment by keypointt** [comment]
sure, closing it

**Pull request closed without merging**
