### PR TITLE
[SPARK-19900][core]Remove driver when relaunching.

### PR DESCRIPTION
**Pull request by lycplus**
## What changes were proposed in this pull request?

* remove failed apps when worker down
* do not reuse driver id when relaunching driver

## How was this patch tested?

manual tests

@CodingCat

### CODE REVIEW

**Comment by jiangxb1987** [comment]
Could you expand more on this change? It would be great if some failing test cases could be provided!

Also cc @cloud-fan

**Comment by liyichao** [comment]
Thanks for reviewing. Basically, the problem is that when relaunching a driver and later the original driver reconnect, there will be an application which does not have a corresponding driver. I will try to add a test case.

**Comment by cloud-fan** [comment]
As the reporter gives the code to reproduce the bug, I reopened that ticket

**Comment by liyichao** [comment]
Sorry, it seems I make a mistake when rebase. I will open another pr.

**Pull request closed without merging**
