### PR TITLE
[SPARK-24236][SS] Continuous replacement for ShuffleExchangeExec

### PR DESCRIPTION
**Pull request by xuanyuanking**
## What changes were proposed in this pull request?

1. New RDD named ContinuousShuffleRowRDD
2. New case class ContinuousShuffleExchangeExec
3. The rule named ReplaceShuffleExchange to replace original ShuffleExchange to ContinuousShuffleExchangeExec

## How was this patch tested?

Existing UT. Add more UT later.

### CODE REVIEW

**Comment by xuanyuanking** [comment]
cc @jose-torres 
As we discussion in #21293, the main difference between us is whether we can reuse current implementation of scheduler and shuffle, but in this part about the implementation of ShuffleExchangeExec, we may have the same imagine. 
Can you give a review about this? Great thanks!

**Comment by jose-torres** [comment]
We're definitely agreed on the broad idea of having a ContinuousShuffleExchangeExec which reuses most of the existing ShuffleExchangeExec.

As discussed in the other PR, I'm not sure about how we're integrating with the scheduler here, so I can't really give a more detailed review at this point.

**Comment by xuanyuanking** [comment]
> As discussed in the other PR, I'm not sure about how we're integrating with the scheduler here, so I can't really give a more detailed review at this point.

My bad, I'm preparing the part about integrating with scheduler first. That's the last part for our preview PR. I will marked the duplicated part of #21293 for convenient review.

**Comment by gaborgsomogyi** [comment]
@xuanyuanking are you still working on this? If not may I ask to close?

**Comment by xuanyuanking** [comment]
Yeah, I'll close all the outdated preview PR.

**Pull request closed without merging**
