### PR TITLE
[SPARK-36337][PYTHON][CORE] Switch pyrolite v4.30 to pickle v1.2 to fix decimal NaN issue

### PR DESCRIPTION
**Pull request by Yikun**
### What changes were proposed in this pull request?
Switch (or upgrade) the [irmen/pyrolite.pickle](https://github.com/irmen/Pyrolite/tree/master) v4.30 to [irmen/pickle](https://github.com/irmen/pickle) v1.2 in this patch

### Why are the changes needed?
- Spark was using `Pyrolite.pickle` (v4.30) to pickle Java objects to python objects, but there was [a problem when pickling decimal(NaN)](https://github.com/irmen/pickle/issues/7) .
- irmen/Pyrolite pickle is splited as separate [irmen/pickle](https://github.com/irmen/pickle) library after Pyrolite v5, the bugfix would not be backported to v4.x, that means we have to switch pyrolite to pickle.
- The double NaN pickled issue solved in https://github.com/irmen/pickle/issues/7 in [irmen/pickle](https://github.com/irmen/pickle) v1.2

So, We switch (or upgrade) the pyrolite.pickle to pickle in this patch.

### Does this PR introduce _any_ user-facing change?

Before this patch:
```python
>>> import decimal
>>> spark.createDataFrame(data=[decimal.Decimal('NaN')], schema='decimal')
DataFrame[value: decimal(10,0)]
>>> spark.createDataFrame(data=[decimal.Decimal('NaN')], schema='decimal').collect()
21/10/14 18:06:47 ERROR Executor: Exception in task 7.0 in stage 5.0 (TID 31)
net.razorvine.pickle.PickleException: problem construction object: java.lang.reflect.InvocationTargetException
    at net.razorvine.pickle.objects.AnyClassConstructor.construct(AnyClassConstructor.java:29)
    at net.razorvine.pickle.Unpickler.load_reduce(Unpickler.java:773)
    at net.razorvine.pickle.Unpickler.dispatch(Unpickler.java:213)
    at net.razorvine.pickle.Unpickler.load(Unpickler.java:123)
    at net.razorvine.pickle.Unpickler.loads(Unpickler.java:136)
    at org.apache.spark.api.python.SerDeUtil$.$anonfun$pythonToJava$2(SerDeUtil.scala:121)
    ... ...
```
After this patch:
```python
>>> import decimal
>>> spark.createDataFrame(data=[decimal.Decimal('NaN')], schema='decimal')
DataFrame[value: decimal(10,0)]
>>> spark.createDataFrame(data=[decimal.Decimal('NaN')], schema='decimal').collect()
[Row(value=None)]
```

### How was this patch tested?
```
>>> import decimal
>>> spark.createDataFrame(data=[decimal.Decimal('NaN')], schema='decimal').collect()
```

### CODE REVIEW

**Comment by Yikun** [comment]
I will add [the testcase which xinrong mentioned](https://issues.apache.org/jira/browse/SPARK-36000?focusedCommentId=17383667&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17383667) under `pyspark/sql/tests/test_dataframe.py` in next commit, like:

```python
    # test for SPARK-36337
    def test_create_nan_decimal_dataframe(self):
        self.assertEqual(
            self.spark.createDataFrame(data=[Decimal('NaN')], schema='decimal').collect(),
            [Row(value=None)]
        )
```

**Comment by HyukjinKwon** [comment]
Thanks for making a PR!

**Review by HyukjinKwon — APPROVED** [review]
Looks good but cc @ueshin @JoshRosen @viirya FYI

**Review by viirya — APPROVED** [review]
Looks good. CI was also passed.

**Review by ueshin — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Let's merge this one and see how it goes .. it's early development cycle so I think should be good timing to get this in.

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
