### PR TITLE
Branch 2.1

### PR DESCRIPTION
**Pull request by ghost**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)
(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Hi @bupt2012, it seems this PR is mistakenly open. Could you please close this?

**Comment by HyukjinKwon** [comment]
Hi @bupt2012, could you just click the "Close pull request" button below?

**Comment by vanzin** [comment]
@bupt2012 please close this PR.

**Comment by uncleGen** [comment]
mistakenly opened? close it please!

**Pull request closed without merging**
