### PR TITLE
[SPARK-49707][BUILD] Upgrade rocksdbjni to 9.7.3

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to upgrade rocksdbjni from `9.5.2` to `9.7.3`.

### Why are the changes needed?
The full release notes as follows:
https://github.com/facebook/rocksdb/releases/tag/v9.7.3
https://github.com/facebook/rocksdb/releases/tag/v9.6.1

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by LuciferYang** [comment]
any update on this one @panbingkun ?

**Comment by panbingkun** [comment]
[RocksDB 9.7.3](https://github.com/facebook/rocksdb/releases/tag/v9.7.3)
The version `9.7.3` of `RocksDB` has been released, let's wait a little longer for it.

**Comment by dongjoon-hyun** [comment]
Ya, please ping us when the PR is ready. :)

**Comment by panbingkun** [comment]
> Ya, please ping us when the PR is ready. :)

Thanks ❤️

**Comment by panbingkun** [comment]
The benchmark: StateStoreBasicOperationsBenchmark
JDK17: 
JDK21:

**Comment by panbingkun** [comment]
@dongjoon-hyun @LuciferYang 
It's already ready, thank you all ❤️!

**Review by LuciferYang — APPROVED** [review]
+1, LGTM

**Comment by LuciferYang** [comment]
Merged into master for Spark 4.0. Thanks @panbingkun and @dongjoon-hyun

**Comment by dongjoon-hyun** [comment]
+1, LGTM.

Thank you again, @panbingkun and @LuciferYang .

**Comment by panbingkun** [comment]
Thanks all @LuciferYang @dongjoon-hyun ❤️

**Pull request closed without merging**
