### PR TITLE
Remove SizeEstimator from o.a.spark package.

### PR DESCRIPTION
**Pull request by rxin**
See comments on https://github.com/apache/spark/pull/3913

### CODE REVIEW

**Comment by sryza** [comment]
LGTM.  Sorry I didn't have a chance to get to this.

**Comment by sryza** [comment]
Actually, I believe the doc in the tuning section needs to be updated as well.

**Comment by sryza** [comment]
Scratch that last comment, the current wording still applies.

**Comment by rxin** [comment]
The test failure looks different. I'm going to merge this.

**Pull request closed without merging**
