### PR TITLE
[SPARK-16196][SQL] Codegen in-memory scan with ColumnarBatches

### PR DESCRIPTION
**Pull request by andrewor14**
## What changes were proposed in this pull request?

This patch makes `InMemoryRelation` faster by generating code to store the input rows as `ColumnarBatches`. This code path is enabled by default but only supports primitive types, falling back to the old, slower code path if there are unsupported types (e.g. strings, arrays, UDTs) in the schema.

The old code path reads the input rows into `ColumnBuilder`s, which is slow because these builders are backed by `ByteBuffer`s and there are a lot of virtual function calls involved, especially when compression is enabled.

The following numbers are derived from the read path (i.e. returning rows from cached batches in memory). The baseline is the first row. The second and third rows describe caching performance before this patch. The last row describes caching performance after this patch.

```
Cache random keys:                       Best/Avg Time(ms)   Rate(M/s)   Per Row(ns)   Relative
-----------------------------------------------------------------------------------------------
cache = F                                      890 /  920        47.1          21.2       1.0X
cache = T columnar_batches = F compress = F   1950 / 1978        21.5          46.5       0.5X
cache = T columnar_batches = F compress = T   1893 / 1927        22.2          45.1       0.5X
cache = T columnar_batches = T                 540 /  544        77.7          12.9       1.6X
```

Future TODOs (outside the scope of this issue):
- support compression in the new code path
- scan should return rows as `ColumnarBatch.Row`s instead of `UnsafeRow`s so operators downstream can further benefit from the columnar representation
## How was this patch tested?

`CacheBenchmark`, `InMemoryColumnarQuerySuite`, existing tests
## Generated code

Write path: https://gist.github.com/andrewor14/a9ed9d942029457a0f953e809ac26ee9
Read path: https://gist.github.com/andrewor14/7ce4c37a3c6bcd5cc2b6b16c861859e9

### CODE REVIEW

**Comment by andrewor14** [comment]
@rxin @sameeragarwal @ooq

**Comment by kiszk** [comment]
@andrewor14 Looks interesting.

I created two PRs that generate similar code like [your code](https://gist.github.com/andrewor14/7ce4c37a3c6bcd5cc2b6b16c861859e9). My PRs use current ```ByteBuffer``` and supports compressions for primitive types. Do these PRs help you?
https://github.com/apache/spark/pull/11956
https://github.com/apache/spark/pull/12894

I am waiting for review.

**Comment by kiszk** [comment]
jenkins retest this please

**Comment by andrewor14** [comment]
Closing for now; too many conflicts.

**Pull request closed without merging**
