### PR TITLE
[SPARK-32949][R][SQL] Add timestamp_seconds to SparkR

### PR DESCRIPTION
**Pull request by zero323**
### What changes were proposed in this pull request?

This PR adds R wrapper for `timestamp_seconds` function.

### Why are the changes needed?

Feature parity.

### Does this PR introduce _any_ user-facing change?

Yes, it adds a new R function.

### How was this patch tested?

New unit tests.

### CODE REVIEW

**Comment by zero323** [comment]
Retest this please.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @zero323 .
Merged to master for Apache Spark 3.1.0 on December 2020.

Could you make a PR for the other functions of SPARK-31797?

**Review by HyukjinKwon — APPROVED** [review]
LGTM too

**Comment by zero323** [comment]
Thanks @dongjoon-hyun @HyukjinKwon 

About that:

> Could you make a PR for the other functions of [SPARK-31797](https://issues.apache.org/jira/browse/SPARK-31797)?

Do you meaning adding `TIMESTAMP_{MILLIS|MICROS}` for all supported APIs?

**Comment by dongjoon-hyun** [comment]
This PR aims the following. I thought we may want it. If you don't want, never mind. :)
```
### Why are the changes needed?

Feature parity.
```

**Comment by zero323** [comment]
Wrapping all three was my initial intention, hence the question under [ano
ther PR](https://github.com/apache/spark/pull/28593, but I see a merit in limiting language APIs to the commonly used functions (if that was the intention for not having a wrapper).

Personally I don't have strong opinion here.

**Pull request closed without merging**
