### PR TITLE
[SPARK-14739][Python] Fix for Sparse and Dense Vector Parsing Errors

### PR DESCRIPTION
**Pull request by vishnu667**
## What changes were proposed in this pull request?

Fixed parsing empty dense and sparse vectors, corrected dead parsing tests.
## How was this patch tested?

Fixed parsing tests, added tests specific to SPARK-14739

### CODE REVIEW

**Comment by viirya** [comment]
duplicate to #12516.

**Comment by srowen** [comment]
Yes @vishnu667 please close this PR

**Comment by vishnu667** [comment]
@viirya @srowen 

#12516  Has not Fixed the Incorrect Test cases and has only added his test case to the existing 

They have been comparing the parsing the values using assertTrue instead of assertEquals.
[Fix for the Existing previous test cases](https://github.com/apache/spark/pull/12513/commits/c5f2510a8a53e54502a45fce7893ed1f6c7a0510)

**Comment by srowen** [comment]
Good point, but please make that comment on the existing PR.

**Comment by vishnu667** [comment]
@srowen I've tested both the PR and both have the issue Fixed the only difference is the test case I've mentioned earlier which is already patched in this request.

**Comment by srowen** [comment]
Jenkins test this please

**Comment by srowen** [comment]
Looks pretty good to me based on my understanding of the issue

**Comment by arashpa** [comment]
@srowen I had another PR https://github.com/apache/spark/pull/12510 coming in first but made a mistake by closing it. I'm also the original person who found the bug and created the first solution for it. Please if possible consider #12516 as the candidate solution.

**Comment by srowen** [comment]
EDIT again: OK, see discussion on https://github.com/apache/spark/pull/12516 about why maybe that's fairer to merge

**Comment by srowen** [comment]
Thank you @vishnu667 for the assist, you can close this PR.

**Comment by vishnu667** [comment]
#12516

**Pull request closed without merging**
