### PR TITLE
[SPARK-35930][BUILD] Upgrade kinesis-client to 1.14.4

### PR DESCRIPTION
**Pull request by sarutak**
### What changes were proposed in this pull request?

This PR upgrades kinesis-client from 1.14.0 to 1.14.4

### Why are the changes needed?

Upgrading to 1.14.1 or newer is recommended by the community for users who use kinesis-client 1.14.0 due to a [bug](https://github.com/awslabs/amazon-kinesis-client/issues/778).
https://github.com/awslabs/amazon-kinesis-client/tree/master#recommended-upgrade-for-all-users-of-the-1x-amazon-kinesis-client

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Ran `*Kinesis*Suite` with `ENABLE_KINESIS_TESTS=1` and they passed on an AWS environment

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Thank you for making a PR, @sarutak . BTW, is it tested manually because this is not covered by CIs?

**Comment by sarutak** [comment]
@dongjoon-hyun Thank you, I forgot that kinesis tests don't run on CI.
I ran `*Kinesis*Suite` with `ENABLE_KINESIS_TESTS=1` and they passed on my AWS environment.
But kinesis-client seems to need newer Guava regardless of `1.14.4` or currently used `1.14.0`.
Otherwise, we'll get like the following exception.
```
[info] org.apache.spark.streaming.kinesis.WithAggregationKinesisStreamSuite *** ABORTED *** (7 seconds, 229 milliseconds)
[info]   org.apache.spark.SparkException: Only one SparkContext should be running in this JVM (see SPARK-2243).The currently running SparkContext was created at:
[info] org.apache.spark.SparkContext.<init>(SparkContext.scala:85)
[info] org.apache.spark.streaming.StreamingContext$.createNewSparkContext(StreamingContext.scala:851)
[info] org.apache.spark.streaming.StreamingContext.<init>(StreamingContext.scala:85)
[info] org.apache.spark.streaming.kinesis.KinesisInputDStreamBuilderSuite.<init>(KinesisInputDStreamBuilderSuite.scala:36)
[info] sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[info] sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[info] sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[info] java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[info] java.lang.Class.newInstance(Class.java:442)
[info] org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:450)
[info] sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:413)
[info] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info] java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info] java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
```
So, I tried with `-Dguava.version=27.0-jre`. Is this expected?

I also ran kinesis tests on the commit a9e8e0528a52d19103463bae0a which upgraded kinesis-client to `1.14.0` but this also seems to need newer Guava.
On the other hand, the commit 82267acfe8c78a70d56a6 which is the parent commit of a9e8e0528a52d19103463bae0a doesn't need newer Guava.

**Comment by dongjoon-hyun** [comment]
`-Dguava.version=27.0-jre` sounds like a regression because the vanilla Apache Spark 3.2.x doesn't work while 3.1.x works. 

Since there are some previous works to address the Guava restriction, ping @viirya , @sunchao , @HyukjinKwon .

**Comment by sarutak** [comment]
> -Dguava.version=27.0-jre sounds like a regression because the vanilla Apache Spark 3.2.x doesn't work while 3.1.x works.

Yeah, a9e8e05 was not merged to `branch-3.1` so I think that is the reason it works with `3.1.x` while doesn't with `3.2.x`.

**Comment by sunchao** [comment]
Does it mean we'd need to upgrade Guava version in order for kinesis-client to work in Spark 3.2.0?

**Comment by viirya** [comment]
FYI, I re-opened #29326 to try upgrading guava again.

**Comment by HyukjinKwon** [comment]
Shall we revert a9e8e0528a52d19103463bae0a9420127a99bf59 first?

**Comment by dongjoon-hyun** [comment]
Since SPARK-34549 is reverted, I'll close this PR, @sarutak . Thank you for checking.

After Guava issue is resolved, feel free to reopen this.

**Pull request closed without merging**
