### PR TITLE
Revert "[SPARK-29644][SQL] Corrected ShortType and ByteType mapping to SmallInt and TinyInt in JDBCUtils

### PR DESCRIPTION
**Pull request by shivsood**
This reverts commit f7e53865 i.e PR #26301 from master

### CODE REVIEW

**Comment by shivsood** [comment]
@dongjoon-hyun as FYI on revert for #26301 in master

**Comment by dongjoon-hyun** [comment]
Ur, do you want to revert fully? What I meant was the `ByteType` <-> `TinyInt` part only.
For the full revert, I can do that without making a PR.

**Comment by dongjoon-hyun** [comment]
cc @gatorsmile , @srowen

**Comment by shivsood** [comment]
@dongjoon-hyun 'll prefer a full revert to keep this clean and inline with what was done in 2.4. I will come back with PR for ShortType and ByteType separately as i get better grasp of the issue and fix.

**Comment by HyukjinKwon** [comment]
ok to test

**Comment by HyukjinKwon** [comment]
Either way seems fine to me. Let me merge this since the PR is open already.

**Review by HyukjinKwon — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
This is revert. Merged to master.

**Comment by srowen** [comment]
Just for my info, all of the related changes in 2.4 are fully reverted now, so we can focus on master?

**Comment by dongjoon-hyun** [comment]
Yes. We checked the other `TinyInt` <-> `ByteType` mapping commits, but it's a legitimate dialect for H2 database.

**Pull request closed without merging**
