### PR TITLE
[SPARK-8596] Add module for rstudio link to spark

### PR DESCRIPTION
**Pull request by koaning**
@shivaram, added module for rstudio install

### CODE REVIEW

**Comment by koaning** [comment]
I just realized I picked the wrong Jira number. Made edit to title.

**Comment by shivaram** [comment]
LGTM. Merging this

**Comment by sarutak** [comment]
@koaning This PR has been already merged. Do you mind closing this PR?

**Comment by koaning** [comment]
This link https://issues.apache.org/jira/browse/SPARK-8684 is still open, see comment from shivarim. This can only be updated when a different AMI is chosen. 
 
This link https://issues.apache.org/jira/browse/SPARK-8596 has been closed.

**Comment by shivaram** [comment]
@koaning -- We can keep the JIRA open, but the PR can be closed as it has been merged. Usually this happens automatically but we've been having some problems in syncing Github with the Apache project (See https://issues.apache.org/jira/browse/INFRA-9988) and need to manually close PRs right now.  Also the way the permissions are setup also mean that only the author of a PR can close it

**Comment by koaning** [comment]
done.

On Wed, Jul 15, 2015 at 4:05 PM, Shivaram Venkataraman <
notifications@github.com> wrote:

> @koaning <https://github.com/koaning> -- We can keep the JIRA open, but
> the PR can be closed as it has been merged. Usually this happens
> automatically but we've been having some problems in syncing Github with
> the Apache project (See https://issues.apache.org/jira/browse/INFRA-9988)
> and need to manually close PRs right now. Also the way the permissions are
> setup also mean that only the author of a PR can close it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apache/spark/pull/7366#issuecomment-121625502>.
>



-- 

grtz
Vincent

**Comment by srowen** [comment]
@koaning doesn't look like it's closed?

**Comment by koaning** [comment]
now?

**Comment by srowen** [comment]
@koaning no, you see it still shows open at the top left right? You are clicking Close?

**Comment by koaning** [comment]
image

**Comment by sarutak** [comment]
@koaning We mean, please close *this PR* in GitHub, not the ticket in JIRA. You can push the close button at the bottom of the comment text field.

**Comment by sarutak** [comment]
@koaning Thanks ;)

**Pull request closed without merging**
