### PR TITLE
[SPARK-29411][CORE][ML][SQL][DSTREAM] Replace use of Unit object with () for Scala 2.13

### PR DESCRIPTION
**Pull request by srowen**
### What changes were proposed in this pull request?

Replace `Unit` with equivalent `()` where code refers to the `Unit` companion object.

### Why are the changes needed?

It doesn't compile otherwise in Scala 2.13.
- https://github.com/scala/scala/blob/v2.13.0/src/library/scala/Unit.scala#L30

### Does this PR introduce any user-facing change?

Should be no behavior change at all.

### How was this patch tested?

Existing tests.

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Merged to master.

Thank you for pinging me. I noticed that GitHub Action seems to show additional three runs (and failures) due to its flakiness. It's irrelevant.

**Comment by srowen** [comment]
Jenkins tests didn't run. While I'm quite sure that this isn't even a change except at the source level, you think it's ok to go on the compile result from GitHub actions? Could be reasonable in a case like this

**Comment by dongjoon-hyun** [comment]
@srowen . `GitHub Action` is just optional infra. I ran UTs local (core/ml/stream/catalyst and some `sql`).

**Comment by dongjoon-hyun** [comment]
The above comment on the `GitHub Action` is an explaination on the current outage of `GitHub Action`.

**Pull request closed without merging**
