### PR TITLE
[MINOR][DOCS] Axe deprecated doc refs

### PR DESCRIPTION
**Pull request by MichaelChirico**
Continuation of #22370. Summary of discussion there:

There is some inconsistency in the R manual w.r.t. supercedent functions linking back to deprecated functions.

 - `createOrReplaceTempView` and `createTable` both link back to functions which are deprecated (`registerTempTable` and `createExternalTable`, respectively)
 - `sparkR.session` and `dropTempView` do _not_ link back to deprecated functions

This PR takes the view that it is preferable _not_ to link back to deprecated functions, and removes these references from `?createOrReplaceTempView` and `?createTable`.

As `registerTempTable` was included in the `SparkDataFrame functions` `@family` of functions, other documentation pages which included a link to `?registerTempTable` will similarly be altered.

### CODE REVIEW

**Comment by srowen** [comment]
CC @felixcheung 
I'd also prefix the title with `[MINOR][DOCS]` to match our conventions

**Comment by MichaelChirico** [comment]
@srowen thanks; done

**Comment by HyukjinKwon** [comment]
ok to test

**Comment by felixcheung** [comment]
could you check the doc output manually for registerTempTable and createTable?

**Comment by MichaelChirico** [comment]
@felixcheung is that to me?

**Comment by felixcheung** [comment]
yes please - please double the doc created looks correct - there is no automatic test for that

**Comment by MichaelChirico** [comment]
@felixcheung done

screen shot 2018-09-16 at 3 15 06 pm

screen shot 2018-09-16 at 3 16 00 pm

**Comment by felixcheung** [comment]
thx. merged to master/2.4

**Review by felixcheung — APPROVED** [review]

**Pull request closed without merging**
