### PR TITLE
[SPARK-18401][SPARKR][ML] SparkR random forest should support output original label.

### PR DESCRIPTION
**Pull request by yanboliang**
## What changes were proposed in this pull request?
SparkR ```spark.randomForest``` classification prediction should output original label rather than the indexed label. This issue is very similar with [SPARK-18291](https://issues.apache.org/jira/browse/SPARK-18291).

## How was this patch tested?
Add unit tests.

### CODE REVIEW

**Comment by yanboliang** [comment]
cc @felixcheung

**Comment by felixcheung** [comment]
LGTM, thx

**Comment by wangmiao1981** [comment]
@felixcheung @yanboliang I will do the same change for spark.logit. It has the same issue. I will create PR and JIRA tonight. Thanks!

**Comment by yanboliang** [comment]
Merged into master and branch-2.1. Thanks for reviewing.

**Pull request closed without merging**
