### PR TITLE
[MINOR][SQL] Avoid wildcard import Network in KafkaRDD.

### PR DESCRIPTION
**Pull request by beliefer**
## What changes were proposed in this pull request?

KafkaRDD exists import with wildcard, I think this is a minor task. but it's OK.

## How was this patch tested?

Exists UT.

### CODE REVIEW

**Comment by jerryshao** [comment]
There has lots of places using wildcard import, also seems it doesn't violate scalastyle check, so to me it is not so necessary to fix, unless we have a style warning about it.

**Comment by HyukjinKwon** [comment]
Yea, let's don't fix this alone.

**Comment by beliefer** [comment]
> Yea, let's don't fix this alone.

Do you mean to solve multiple similar problems? or do not need to solve it at all?

**Comment by jerryshao** [comment]
The changes will introduce lots of conflicts to other PRs, I would suggest to not fix it unless we have a consensus on this style change.

**Comment by beliefer** [comment]
> The changes will introduce lots of conflicts to other PRs, I would suggest to not fix it unless we have a consensus on this style change.

Thanks for your review first! I think these conflicts is easy to solve. We have a consensus on this style change is the important thing.

**Comment by HyukjinKwon** [comment]
Where was the consensus made? They have been usually rejected.

Since we're going ahead for Spark 3, some changes like this are being merged when they fix multiple cleanups but the changes like this are not encouraged.

**Comment by HyukjinKwon** [comment]
e.g, https://github.com/apache/spark/pull/24857.

Also, causing conflicts itself is a problem because we need to manually fix the conflicts in files. This is an overhead comparing to just `git cherry-pick` and `git push`.

Also, think about multiple conflicts like this. Those changes are usually rejected for those reasons because fixing style is virtually nothing real but it causes a real problem.

**Comment by beliefer** [comment]
@jerryshao @HyukjinKwon OK. I get it. I will close this PR.

**Comment by beliefer** [comment]
@jiangxb1987

**Comment by beliefer** [comment]
@haoyuan

**Comment by beliefer** [comment]
@liyinan926

**Comment by beliefer** [comment]
@davie

**Comment by beliefer** [comment]
@davies

**Comment by beliefer** [comment]
@mengxr

**Comment by beliefer** [comment]
@wzhfy

**Comment by beliefer** [comment]
@xiajunluan

**Comment by beliefer** [comment]
@zsxwing

**Comment by beliefer** [comment]
@rxin

**Pull request closed without merging**
