### PR TITLE
[SPARK-5758][SQL] Use LongType as the default type for integers in JSON schema inference.

### PR DESCRIPTION
**Pull request by yhuai**

### CODE REVIEW

**Comment by rxin** [comment]
lgtm - assuming tests pass.

**Comment by rxin** [comment]
cc @mengxr this broke MLlib... thoughts?

**Comment by davies** [comment]
I think some Integers are dumped into JSON, then come out as LongType, then break some APIs.

**Comment by mengxr** [comment]
Yes, we use `row.getInt()` in MLlib. I think we should use json4s directly in MLlib's export/import.

**Comment by mengxr** [comment]
@yhuai I created a JIRA to use json4s directly in MLlib: https://issues.apache.org/jira/browse/SPARK-5757. Could you make a JIRA for this PR and link them?

**Comment by yhuai** [comment]
@mengxr Sure. I have created https://issues.apache.org/jira/browse/SPARK-5758.

**Comment by yhuai** [comment]
test this please

**Pull request closed without merging**
