### PR TITLE
Revert [SPARK-24882][SQL] improve data source v2 API from branch 2.4

### PR DESCRIPTION
**Pull request by cloud-fan**
## What changes were proposed in this pull request?

As discussed in the dev list, we don't want to include https://github.com/apache/spark/pull/22009 in Spark 2.4, as it needs data source v2 users to change the implementation intensitively, while they need to change again in next release.

## How was this patch tested?

existing tests

### CODE REVIEW

**Comment by cloud-fan** [comment]
cc @rxin @rdblue

**Comment by dongjoon-hyun** [comment]
This seems to be the complete revert of SPARK-24882 (#22009 and the followup #22245). Am I right?

**Comment by kiszk** [comment]
Incorrect import still may exist there.
```
[error] /home/jenkins/workspace/SparkPullRequestBuilder/sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/continuous/ContinuousTextSocketSource.scala:40: object SupportsDeprecatedScanRow is not a member of package org.apache.spark.sql.sources.v2.reader
[error] import org.apache.spark.sql.sources.v2.reader.{InputPartition, InputPartitionReader, SupportsDeprecatedScanRow}
[error]        ^
```

**Comment by jose-torres** [comment]
MicroBatchExecution.scala and ContinuousExecution.scala look right after the revert, although it would be helpful to understand what the diff is between this and a straight `git revert`.

**Review by gatorsmile — COMMENTED** [review]
LGTM

Thanks! Merged to 2.4.

**Comment by gatorsmile** [comment]
Unable to merge to master. @cloud-fan Could you submit another PR to the master branch?

**Comment by dongjoon-hyun** [comment]
Ur, @gatorsmile . Why do we need to revert this from `master`?

**Comment by cloud-fan** [comment]
As we discussed in the dev list, we only want to revert it from 2.4. I'm closing it now.

**Pull request closed without merging**
