### PR TITLE
[SPARK-33352][CORE][SQL][SS][MLLIB][AVRO][K8S] Fix procedure-like declaration compilation warnings  in Scala 2.13

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
There are two similar compilation warnings about procedure-like declaration in Scala 2.13:

```
[WARNING] [Warn] /spark/core/src/main/scala/org/apache/spark/HeartbeatReceiver.scala:70: procedure syntax is deprecated for constructors: add `=`, as in method definition
```
and 

```
[WARNING] [Warn] /spark/core/src/main/scala/org/apache/spark/storage/BlockManagerDecommissioner.scala:211: procedure syntax is deprecated: instead, add `: Unit =` to explicitly declare `run`'s return type
```

this pr is the first part to resolve SPARK-33352：

- For constructors method definition add `=` to convert to function syntax

- For without `return type` methods definition add `: Unit =` to convert to function syntax

### Why are the changes needed?
Eliminate compilation warnings in Scala 2.13 and this change should be compatible with Scala 2.12

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass the Jenkins or GitHub Action

### CODE REVIEW

**Comment by LuciferYang** [comment]
cc @srowen & @dongjoon-hyun

**Comment by srowen** [comment]
I'm OK with proceeding with this one; I think it won't have huge impact and require lots of changes. Up to your judgment about how to break it up into PRs.

**Comment by LuciferYang** [comment]
At most three pr, Sql module need change about 10 files, mllib module 4 files, streaming needn't change, the rest is not finished yet, so I don't think there will be too many changes

**Comment by srowen** [comment]
Meh, you could put it into one if that's the scope of it.

**Comment by dongjoon-hyun** [comment]
+1 for @srowen 's [suggestion](https://github.com/apache/spark/pull/30255#issuecomment-722434912).

**Comment by LuciferYang** [comment]
ok ~

**Comment by dongjoon-hyun** [comment]
BTW, @LuciferYang . When you add `[WIP]` tag into the PR title, it would be great if you convert this to `Draft` PR in GitHub next time.

**Comment by LuciferYang** [comment]
> BTW, @LuciferYang . When you add [WIP] tag into the PR title, it would be great if you convert this to Draft PR in GitHub next time.

Ok~ I will do this next time

**Comment by LuciferYang** [comment]
cc @srowen & @dongjoon-hyun this pr is ready for review now, It seems that all modules no longer have this compilation warnings.

**Comment by LuciferYang** [comment]
https://github.com/scalastyle/scalastyle/blob/ec14399543d2d5ccf93c3713aa5df21793844791/src/main/scala/org/scalastyle/scalariform/ProcedureDeclarationChecker.scala#L17-L35

`ProcedureDeclarationChecker` can help us to discover new compilation warnings about `procedure syntax is deprecated`, but it can't check constructor methods now

**Review by srowen — APPROVED** [review]

**Comment by srowen** [comment]
Merged to master

**Comment by LuciferYang** [comment]
thx ~ @srowen & @dongjoon-hyun

**Pull request closed without merging**
