### PR TITLE
[SPARK-4890] Upgrade Boto to 2.34.0; automatically download Boto from PyPi instead of packaging it

### PR DESCRIPTION
**Pull request by JoshRosen**
This patch upgrades `spark-ec2`'s Boto version to 2.34.0, since this is blocking several features.  Newer versions of Boto don't work properly when they're loaded from a zipfile since they try to read a JSON file from a path relative to the Boto library sources.

Therefore, this patch also changes spark-ec2 to automatically download Boto from PyPi if it's not present in `SPARK_EC2_DIR/lib`, similar to what we do in the `sbt/sbt` script. This shouldn't ben an issue for users since they already need to have an internet connection to launch an EC2 cluster.  By performing the downloading in spark_ec2.py instead of the Bash script, this should also work for Windows users.

I've tested this with Python 2.6, too.

### CODE REVIEW

**Comment by piskvorky** [comment]
@JoshRosen how exactly does `boto` get distributed to the cluster machines?

My app is failing and it seems to be connected to the fact that all EC2 nodes have boto 2.8.0 (as opposed to the driver machine, which has correctly downloaded and used 2.34.0).

**Comment by JoshRosen** [comment]
@piskvorky, the `boto` on the EC2 instances itself should be provided through the AMI, AFAIK.

**Comment by piskvorky** [comment]
Got it, thanks Josh!

By the way, would you be interested in a spark_ec2.py patch that exposes its functionality programatically as well?

Right now, it's a bit hard to use it as part of a larger pipeline, with all the `sys.exit`s and `print`s sprinkled inside.

**Comment by piskvorky** [comment]
(sorry to hijack this issue, will open a new one if you think the patch is worth it)

**Pull request closed without merging**
