### PR TITLE
[SPARK-32408][BUILD] Enable crossPaths back to prevent side effects

### PR DESCRIPTION
**Pull request by HyukjinKwon**
### What changes were proposed in this pull request?

This PR proposes to enable `corssPaths` back for now to match with the build as it was.
It still indeterministically doesn't run JUnit tests given my observation, and this PR basically reverts the partial fix from https://github.com/apache/spark/pull/29057.

See also https://github.com/apache/spark/pull/29205 for the full context.

### Why are the changes needed?

To prevent the side effects from crossPaths such as SPARK_PREPEND_CLASSES or tests that run conditionally if the test classes are present in PySpark.

### Does this PR introduce _any_ user-facing change?

No, dev-only.

### How was this patch tested?

Manually tested:

```bash
build/sbt -Phadoop-2.7 -Phive -Phive-2.3 -Phive-thriftserver -DskipTests clean test:package
./python/run-tests --python-executable=python3 --testname="pyspark.sql.tests.test_dataframe QueryExecutionListenerTests"
```

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @srowen and @dongjoon-hyun. This should be much safer for now.

**Comment by HyukjinKwon** [comment]
I reverted 5e79db6 here and get it back again to confirm IntegratedUDFTestUtils and pandas related tests are not being skipped.

**Comment by HyukjinKwon** [comment]
I reverted 5e79db6 here and get it back again to show full logs about JUnit tests.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Merged to master.

**Comment by HyukjinKwon** [comment]
Thank you @dongjoon-hyun.

**Pull request closed without merging**
