### PR TITLE
[SPARK-12842][test-hadoop2.7] Add Hadoop 2.7 build profile

### PR DESCRIPTION
**Pull request by JoshRosen**
This patch adds a Hadoop 2.7 build profile in order to let us automate tests against that version.

/cc @rxin @srowen

### CODE REVIEW

**Comment by srowen** [comment]
Yes, seems fine to me.

**Comment by rxin** [comment]
LGTM.

**Comment by JoshRosen** [comment]
Huh, there's no obvious test failure here. Let's try again and hope that it's just some flaky infra problem.

**Comment by JoshRosen** [comment]
Jenkins, retest this please.

**Comment by rxin** [comment]
I've merged this. Thanks.

**Pull request closed without merging**
