### PR TITLE
Creating KafkaStreamToCassandra

### PR DESCRIPTION
**Pull request by SaddamKhan1490**
## What changes were proposed in this pull request?

(This patch is intended to read records from existing Kafka topic and writing those records to existing table under specified keyspace in Cassandra leveraging SparkStreaming )

## How was this patch tested?
(This patch was tested : manual tests)

Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Doesn't this require a thridparty library?

**Comment by SaddamKhan1490** [comment]
hi @HyukjinKwon : 

1> Yes it requires third party library dependency i.e. """libraryDependencies += "com.datastax.spark" %% "spark-cassandra-connector" % ''"", & this library is open sourced "https://mvnrepository.com/artifact/com.datastax.spark/spark-cassandra-connector_2.10" and fall under Apache i.e. https://github.com/apache/cassandra, which is also the parent for Spark i.e. https://github.com/apache/spark
2> Also its only NoSQL which offers direct integration with spark
3> https://docs.databricks.com/spark/latest/data-sources/cassandra.html

**Comment by HyukjinKwon** [comment]
yup but then wouldn't ir make more sense that the thridpart library has the example?

**Comment by SaddamKhan1490** [comment]
@HyukjinKwon : Well in that case you can close the PR #21076

**Comment by HyukjinKwon** [comment]
Yea, I think we should better leave this closed.

**Comment by jerryshao** [comment]
@SaddamKhan1490 would you please close this PR. Thanks!

**Pull request closed without merging**
