### PR TITLE
[SPARK-30191][YARN] optimize yarn allocator

### PR DESCRIPTION
**Pull request by Neilxzn**
### What changes were proposed in this pull request?
add the factor `numExecutorsExiting` in YarnAllocator's method `updateResourceRequests` 

### Why are the changes needed?
when driver lost its executors because of machine hardware problem and all of service includes nodemanager, executor on the node has been killed,  it means that Resourcemanager can't update the containers info on the node until Resourcemanager try to remove the node,   but it always takes 10 mins or longger, and in the meantime, AM doesn't add the new resource request and driver missing executors. 
so maybe AM should add the factor `numExecutorsExiting` in YarnAllocator's method `updateResourceRequests`  to optimize it.

### Does this PR introduce any user-facing change?

No

### How was this patch tested?
add test("lost executor removed from driver")

### CODE REVIEW

**Comment by Neilxzn** [comment]
@dongjoon-hyun @jiangxb1987 any suggestion for this review? thanks

**Comment by AngersZhuuuu** [comment]
cc @cloud-fan @maropu @wangyum @srowen

**Comment by srowen** [comment]
I don't know enough to really review this. It seems plausible to add the number of executors that are going to be lost to the target, but I don't know the implications of that.

**Comment by tgravescs** [comment]
overall this isn't a bad idea, the downside is that the resources are still being used from the yarn point of view, but trying to get another one shouldn't be bad.  I'll try to look closer at this next week

**Pull request closed without merging**
