### PR TITLE
[SPARK-16964][SQL] Remove private[sql] and private[spark] from sql.execution package [Backport]

### PR DESCRIPTION
**Pull request by hvanhovell**
## What changes were proposed in this pull request?

This PR backports https://github.com/apache/spark/pull/14554 to branch-2.0.

I have also changed the visibility of a few similar Hive classes.
## How was this patch tested?

(Only a package visibility change)

### CODE REVIEW

**Comment by hvanhovell** [comment]
cc @rxin

**Comment by rxin** [comment]
LGTM - merging in branch-2.0.

**Comment by rxin** [comment]
hm damn - this one includes https://github.com/apache/spark/pull/14654 and I merged that one first. I ended up reverting the other one from branch-2.0 to merge this one.

Can you close this ticket now?

**Comment by hvanhovell** [comment]
Thanks!

**Pull request closed without merging**
