### PR TITLE
[SPARK-39777][DOCS] Remove Hive bucketing incompatiblity documentation

### PR DESCRIPTION
**Pull request by c21**
### What changes were proposed in this pull request?

We support Hive bucketing (with Hive hash function - https://issues.apache.org/jira/browse/SPARK-32709 and https://issues.apache.org/jira/browse/SPARK-32712) started from Spark 3.3.0, we should also update the documentation to reflect the fact, that we are no longer incompatible with Hive bucketing.

### Why are the changes needed?

Update user-facing documentation to avoid confusion.

### Does this PR introduce _any_ user-facing change?

Yes, the doc itself.

### How was this patch tested?

Manually checked the doc file locally.

### CODE REVIEW

**Comment by c21** [comment]
The removed documentation is on https://spark.apache.org/docs/latest/sql-migration-guide.html:
Screen Shot 2022-07-14 at 12 32 53 AM

**Comment by c21** [comment]
@cloud-fan - could you help take a look when you have time? Thanks.

**Review by HyukjinKwon — APPROVED** [review]
LGTM but it would be great to mention the relavant JIRAs in the PR description though.

**Comment by c21** [comment]
> LGTM but it would be great to mention the relavant JIRAs in the PR description though.

@HyukjinKwon - sure, added.

**Comment by HyukjinKwon** [comment]
Merged to master and branch-3.3.

**Pull request closed without merging**
