### PR TITLE
[SPARK-45948][K8S] Make single-pod spark jobs respect `spark.app.id`

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to make single-pod Spark jobs respect `spark.app.id` in K8s environment.

### Why are the changes needed?

Since Apache Spark 3.4.0, SPARK-42190 allows users to run single-pod Spark jobs in K8s environment by utilizing `LocalSchedulerBackend` in the driver pod. However, `LocalSchedulerBackend` doesn't respect `spark.app.id` while `KubernetesClusterSchedulerBackend` does. This PR aims to improve K8s UX by reducing the behavior difference between single-pod Spark jobs and multi-pod Spark jobs in K8s environment.

### Does this PR introduce _any_ user-facing change?

Yes, but it's more consistent with the existing general K8s jobs.

### How was this patch tested?

Pass the CIs with the newly added test case.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Could you review this when you have some time, please, @LuciferYang ?

**Review by yaooqinn — APPROVED** [review]

**Review by LuciferYang — APPROVED** [review]
LGTM

**Comment by dongjoon-hyun** [comment]
Thank you, @yaooqinn and @LuciferYang !

**Comment by dongjoon-hyun** [comment]
All tests passed. Merged to master.

**Pull request closed without merging**
