### PR TITLE
[SPARK-42369][CORE] Fix constructor for java.nio.DirectByteBuffer

### PR DESCRIPTION
**Pull request by luhenry**
### What changes were proposed in this pull request?

In the latest JDK, the constructor `DirectByteBuffer(long, int)` was replaced with `DirectByteBuffer(long, long)`. We just want to support both by probing for the legacy one first and falling back to the newer one second.

This change is completely transparent for the end-user, and makes sure Spark works transparently on the latest JDK as well.

### Why are the changes needed?

It's required to support the latest versions of the JDK.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

It was built and ran locally against the newest JDK.

### CODE REVIEW

**Comment by mridulm** [comment]
The type mismatch at invocation time (`int` vs `long` now) would work fine due to promotion I guess ? I did not see this documented in `Constructor`, so wanted to clarify,

**Comment by luhenry** [comment]
Yes, and it wouldn't work the other way since `long` doesn't fit in `int`. It's the implicit conversion of `int` to `long` that comes into play here.

**Review by mridulm — APPROVED** [review]
+CC @srowen

**Review by srowen — APPROVED** [review]

**Comment by srowen** [comment]
(Please make a JIRA, etc. though - https://spark.apache.org/contributing.html )

**Review by dongjoon-hyun — COMMENTED** [review]
Thank you for making a PR, @luhenry .
Is this isolated for **Java 21 LTS** only? Do you know which Java versions will have the original patch?

**Comment by LuciferYang** [comment]
> Thank you for making a PR, @luhenry . Is this isolated for **Java 21 LTS** only? Do you know which Java versions will have the original patch?

It should start from Java 21. Java 20 still uses Int.

https://github.com/openjdk/jdk/blob/jdk-20+34/src/java.base/share/classes/java/nio/Direct-X-Buffer.java.template

**Comment by luhenry** [comment]
The change happens in https://github.com/openjdk/jdk/commit/a56598f5a534cc9223367e7faa8433ea38661db9 which will be released first in Java 21.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM (Pending CI).
Could you rebase to `master` branch once more to trigger CI, @luhenry ?

**Review by LuciferYang — APPROVED** [review]
+1, LGTM

**Review by wangyum — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @luhenry , @mridulm , @srowen , @LuciferYang , @wangyum .
Merged to master for Apache Spark 3.5.0.

**Comment by AlanBateman** [comment]
Would it be possible to provide a summary on what Spark is doing? It's untenable to rely on JDK internals like this as it could break at any time. In this case, I'm guessing that you want to create a ByteBuffer that is backed by some off-heap memory. The standard API for that is JNI NewDirectByteBuffer. Going forward, the j.l.foreign API might be what you want. In the current preview it can be done with a restricted method like `MemorySegment.ofAddress(address, size).asByteBuffer()`

**Comment by srowen** [comment]
It's in the comments, to some extent. I believe it's to allow larger allocations than normally possible.
The catch is we need to support Java 8 for now, so the foreign APIs won't help.

**Comment by AlanBateman** [comment]
The elements in a ByteBuffer are addressed by an int so the capacity is limited to Integer.MAX_VALUE. Using standard APIs such as JNI NewDirectByteBuffer or FileChannel.map allows you have ByteBuffer views over memory/mappings that are much larger. I really hope the Spark maintainers will re-examine this code as these hacks are way too fragile.

**Comment by srowen** [comment]
No, that's not it. It relates to `MaxDirectMemorySize` and its default. I think this is all to avoid that limit without having everyone set it differently. What problem are you seeing with this?

**Comment by AlanBateman** [comment]
Strong encapsulation has been enabled by default since JDK 16 so presumably the setAccessible has been failing with InaccessibleObjectException since then, unless it is run with --add-opens to open this package? If there is somewhere to put command line options then maybe you could put -XX:MaxDirectMemorySize=100g or some other large value? If there there is a compelling case for running without limits on direct memory then maybe you can bring it to the OpenJDK mailing lists for discussion, nio-dev or core-libs-dev in this case. The concern with the hack is that they can break at any time and prevents upgrading the JDK. In this case, we fixed an issue with JNI NewDirectByteBuffer for JDK 21 and that required change a private constructor.

The issue came to light with the renaissance benchmark:
   https://github.com/renaissance-benchmarks/renaissance/issues/370

**Comment by srowen** [comment]
Yes I agree with all that, but it isn't true for Java 8, which is still supported. 
I agree, could break. If it does this just 'falls back' to normal limits and you have to set a command line flag or something.

**Comment by AlanBateman** [comment]
It's the same issue for JDK 8 where it was completely unsupported to be make use of the JDK private constructor. For the JDK side, all we can do it strongly courage the Spark project to move away from these hacks. If there are compelling cases for introducing new APIs or interfaces then please bring them to the OpenJDK mailing lists for discussion.

**Pull request closed without merging**
