### PR TITLE
[SPARK-10124] [MESOS] Fix removing queued driver in mesos cluster mode.

### PR DESCRIPTION
**Pull request by tnachen**
Currently the spark applications can be queued to the Mesos cluster dispatcher, but when multiple jobs are in queue we don't handle removing jobs from the buffer correctly while iterating and causes null pointer exception.

This patch copies the buffer before iterating them, so exceptions aren't thrown when the jobs are removed.

### CODE REVIEW

**Comment by tnachen** [comment]
@andrewor14 PTAL!

**Comment by andrewor14** [comment]
LGTM

**Comment by tnachen** [comment]
retest this please

**Comment by andrewor14** [comment]
pyspark tests are irrelevant to mesos. I'm merging this into master 1.5 thanks @tnachen.

**Comment by andrewor14** [comment]
Can you close this now? looks like github is not auto-closing PRs again.

**Pull request closed without merging**
