### PR TITLE
[SPARK-34590][TESTS] Allow JDWP debug for tests

### PR DESCRIPTION
**Pull request by sarutak**
### What changes were proposed in this pull request?

This PR proposes a new feature that allows developers to debug test code using JDWP with sbt an Maven.
More specifically, this PR introduces the following profile options.

* `jdwp-test-debug`: An profile which controls enable/disable JDWP debug
* `test.jdwp.address`: An option which corresponds to `address` option in JDWP
* `test.jdwp.suspend`: An option which corresponds to `suspend` option in JDWP
* `test.jdwp.server`: An option which corresponds to `server` option in JDWP
* `test.debug.suite`: An option which controls whether debug ScalaStyle suites (Maven only)

For `sbt`, this feature can be used like `build/sbt -Pjdwp-test-debug -Dtest.jdwp.address=localhost:9876 -Dtest.jdwp.suspend=y -Dtest.jdwp.server=y` and can be used for both JUnit tests and ScalaTest tests.

For `Maven`, this feature can be used like as follows:

(For JUnit tests) `build/mvn -Pjdwp-test-debug -Dtest.jdwp.address=localhost:9876 -Dtest.jdwp.suspend=y -Dtest.jdwp.server=y`
(For ScalaTest suites) `build/mvn -Pjdwp-test-debug -Dtest.debug.suite=true -Dtest.jdwp.address=localhost:9876 -Dtest.jdwp.suspend=y -Dtest.jdwp.server=y` (It might be useful to specify specific sub-modules like `-pl sql/core,sql/catalyst`).

### Why are the changes needed?

It's useful to debug test code.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

I confirmed the following things.

* `jdwp-tes-debug` can switch JDWP enabled/disabled
* `test.jdwp.address` can change address and port.
* `test.jdwp.suspend` can change the behavior that the target debugee suspends or not.
* `test.jdwp.server` can change the behavior that the JDWP debugger run as a server or client.
* ScalaTest suites can be debugged with Maven with setting `test.debug.suite` to `true`.

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Thanks, @sarutak . Is there a reason not to do this in Maven?

**Comment by sarutak** [comment]
@dongjoon-hyun It's just I don't know how to do the same thing for Maven for now. I'll add the same feature after I find the way.

**Review by srowen — APPROVED** [review]

**Comment by srowen** [comment]
It would just be a new profile that modifies some test runner settings or something

**Comment by sarutak** [comment]
@srowen
Thanks for the advice. Now we can switch this feature with `-Pjdwp-test-debug` both for `sbt` and `Maven`.

@dongjoon-hyun 
For Maven, `scalatest-maven-plugin` supports JDWP debug but it's a little bit unuseful (suspended for each sub-modules even though a sub-module doesn't contain suites to run) so I've added `test.debug.suite` property only for Maven.

**Comment by srowen** [comment]
I think it's OK to just add for SBT.

**Comment by sarutak** [comment]
> I think it's OK to just add for SBT.

I usually use SBT so it's OK for me but @dongjoon-hyun , do you think it's OK even if this change doesn't contain this feature for Maven?

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @sarutak . 
Sure, I agree that the AS-IS approach is enough.

**Comment by dongjoon-hyun** [comment]
Merged to master. Thank you, @sarutak and @srowen .

**Pull request closed without merging**
