### PR TITLE
[SPARK-42410][CONNECT][TESTS] Support Scala 2.12/2.13 tests in `connect` module

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to support both Scala 2.12/13 tests in `connect` module by splitting the golden files.

### Why are the changes needed?

After #39933, Scala 2.13 CIs are broken .
- **master**: https://github.com/apache/spark/actions/runs/4157806226/jobs/7192575602
- **branch-3.4**: https://github.com/apache/spark/actions/runs/4155578848/jobs/7188777977
```
[info] - function_udf *** FAILED *** (29 milliseconds)
[info]   java.io.InvalidClassException: org.apache.spark.sql.TestUDFs$$anon$1; local class incompatible: stream classdesc serialVersionUID = 505010451380771093, local class serialVersionUID = 643575318841761245
```

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the CIs and do Scala 2.13 tests manually.

```
$ dev/change-scala-version.sh 2.13
$ build/sbt -Dscala.version=2.13.8 -Pscala-2.13 -Phadoop-3 assembly/package "connect/test"
...
[info] - function_udf_2.13 (19 milliseconds)
[info] Run completed in 8 seconds, 964 milliseconds.
[info] Total number of tests run: 119
[info] Suites: completed 8, aborted 0
[info] Tests: succeeded 119, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[success] Total time: 18 s, completed Feb 12, 2023, 3:33:40 PM
```

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
cc @hvanhovell , @HyukjinKwon , @xinrong-meng

**Review by HyukjinKwon — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @HyukjinKwon !

**Comment by dongjoon-hyun** [comment]
For this one, I verified locally, but CI seems to fail weird. Let me take a look at the failure, @HyukjinKwon .

**Comment by dongjoon-hyun** [comment]
It turns out that I missed one wrong Scala 2.12 renaming due to my outdated test resource directory. I fixed it.
```
$ build/sbt -Phadoop-3 assembly/package "connect/test"
...
[info] - function_udf_2.12 (15 milliseconds)

$ build/sbt -Dscala.version=2.13.8 -Pscala-2.13 -Phadoop-3 assembly/package "connect/test"
...
[info] - function_udf_2.13 (19 milliseconds)
```

**Comment by dongjoon-hyun** [comment]
GitHub Action passed. Merged to master/3.4. Thank you, @HyukjinKwon .
```
[info] ProtoToParsedPlanTestSuite:
[info] - select (24 milliseconds)
[info] - column_alias (2 milliseconds)
[info] - column_by_name (3 milliseconds)
[info] - function_lit (8 milliseconds)
[info] - range (4 milliseconds)
[info] - function_udf_2.12 (28 milliseconds)
[info] - sql (3 milliseconds)
[info] - function_col (8 milliseconds)
[info] - limit (2 milliseconds)
[info] - filter (2 milliseconds)
[info] - column_equals (3 milliseconds)
[info] - column_add (2 milliseconds)
[info] Run completed in 19 seconds, 726 milliseconds.
[info] Total number of tests run: 119
[info] Suites: completed 8, aborted 0
[info] Tests: succeeded 119, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
```

**Comment by dongjoon-hyun** [comment]
Thank you, @hvanhovell !

**Pull request closed without merging**
