### PR TITLE
[SPARK-23069][DOCS][SPARKR] fix R doc for describe missing text

### PR DESCRIPTION
**Pull request by felixcheung**
## What changes were proposed in this pull request?

fix doc truncated

## How was this patch tested?

manually

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
retest this please

**Review by HyukjinKwon — APPROVED** [review]
Just double checked. LGTM

**Comment by HyukjinKwon** [comment]
Merged to master and branch-2.3.

**Comment by felixcheung** [comment]
thanks

**Pull request closed without merging**
