### PR TITLE
[SPARK-40953][CONNECT][PYTHON][TESTS][FOLLOW-UP] Add a test case for head(n)

### PR DESCRIPTION
**Pull request by amaliujia**
### What changes were proposed in this pull request?

Following up on https://github.com/apache/spark/pull/38424, we can actually add a test case for `head(n)`. 

### Why are the changes needed?

Improve test coverage.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

UT

### CODE REVIEW

**Comment by amaliujia** [comment]
R: @zhengruifeng

**Review by HyukjinKwon — APPROVED** [review]

**Review by itholic — APPROVED** [review]
LGTM

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by zhengruifeng** [comment]
late lgtm

**Pull request closed without merging**
