### PR TITLE
[SPARK-6365] jetty-security also needed for SPARK_PREPEND_CLASSES to work

### PR DESCRIPTION
**Pull request by squito**
https://issues.apache.org/jira/browse/SPARK-6365

thanks @vanzin for helping me figure this out

### CODE REVIEW

**Comment by vanzin** [comment]
LGTM.

**Comment by srowen** [comment]
LGTM2. Simple one. Let me let it sit a short while for comments though.

**Comment by JoshRosen** [comment]
Is there an easy way to add a regression test for this?

**Comment by squito** [comment]
@JoshRosen  I couldn't think of anything, but to be honest I didn't really rack my brain too hard since its just a developer util.  I'm open to any suggestions ...

**Comment by JoshRosen** [comment]
Doh, I looked at this too quickly and somehow mixed this up with one of the "user classpath first" options.  This looks good to me, too.

**Comment by vanzin** [comment]
nit: can you add the bug number to the PR title like other PRs? thx!

**Comment by srowen** [comment]
Also, should this go back into branch-1.3 or no?

**Comment by squito** [comment]
hmm, this should go in branch-1.3 as well -- however git was unhappy when I tried to do the merge w/ 1.3.  I opened another PR for 1.3 https://github.com/apache/spark/pull/5071 , just want to make sure the tests go through and then I'll merge that also

**Pull request closed without merging**
