### PR TITLE
[SPARK-46002][INFRA] Upgrade to Python 3.9 in SQL test

### PR DESCRIPTION
**Pull request by zhengruifeng**
### What changes were proposed in this pull request?
Upgrade to Python 3.9 in SQL test

### Why are the changes needed?
this version has not been upgraded in more than 3 years

### Does this PR introduce _any_ user-facing change?
no, test-only

### How was this patch tested?
ci

### Was this patch authored or co-authored using generative AI tooling?
no

### CODE REVIEW

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
Sorry, but Python 3.8 is still a version of supported.
If we need to upgrade the default Python test version, it should be consistent with PySpark, @zhengruifeng .

**Comment by zhengruifeng** [comment]
> Sorry, but Python 3.8 is still a version of supported. If we need to upgrade the default Python test version, it should be consistent with PySpark, @zhengruifeng .

yeah, let me switch to 3.9 to be consistent first.

**Comment by dongjoon-hyun** [comment]
Thank you! Python 3.9 sounds good.

**Review by dongjoon-hyun — APPROVED** [review]
Thank you for updating. Pending Draft and CI.

**Comment by zhengruifeng** [comment]
also cc @HyukjinKwon

**Comment by dongjoon-hyun** [comment]
Merged to master. Thank you, @zhengruifeng .

**Pull request closed without merging**
