### PR TITLE
[SPARK-36702][SQL] ArrayUnion handle duplicated Double.NaN and Float.Nan

### PR DESCRIPTION
**Pull request by AngersZhuuuu**
### What changes were proposed in this pull request?
For query
```
select array_union(array(cast('nan' as double), cast('nan' as double)), array())
```
This returns [NaN, NaN], but it should return [NaN].
This issue is caused by `OpenHashSet` can't handle `Double.NaN` and `Float.NaN` too.
In this pr we handle `NaN` like `Null` value

### Why are the changes needed?
Fix bug

### Does this PR introduce _any_ user-facing change?
ArrayUnion won't show duplicated `NaN` value

### How was this patch tested?
Added UT

### CODE REVIEW

**Comment by AngersZhuuuu** [comment]
ping @cloud-fan

**Comment by srowen** [comment]
How does this differ from https://github.com/apache/spark/pull/33955 ?

**Comment by AngersZhuuuu** [comment]
> How does this differ from #33955 ?

#33955 make all flag in SQLOpenHashSet,

**Comment by HyukjinKwon** [comment]
Mind elabourating https://github.com/apache/spark/pull/33951#issuecomment-917524836? Also let's keep one PR only for the issue if we're clear on which approach to go ahead for.

**Comment by AngersZhuuuu** [comment]
> Mind elabourating [#33951 (comment)](https://github.com/apache/spark/pull/33951#issuecomment-917524836)? Also let's keep one PR only for the issue if we're clear on which approach to go ahead for.

Make this as draft, you can go ahead on that pr.

**Pull request closed without merging**
