### PR TITLE
[SPARK-24519][CORE] Compute SHUFFLE_MIN_NUM_PARTS_TO_HIGHLY_COMPRESS only once

### PR DESCRIPTION
**Pull request by rxin**
## What changes were proposed in this pull request?
Previously SPARK-24519 created a modifiable config SHUFFLE_MIN_NUM_PARTS_TO_HIGHLY_COMPRESS. However, the config is being parsed for every creation of MapStatus, which could be very expensive. Another problem with the previous approach is that it created the illusion that this can be changed dynamically at runtime, which was not true. This PR changes it so the config is computed only once.

## How was this patch tested?
Removed a test case that's no longer valid.

### CODE REVIEW

**Review by srowen — APPROVED** [review]

**Comment by rxin** [comment]
Jenkins, retest this please.

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by dongjoon-hyun** [comment]
@rxin . Could you fill the PR description, too?

**Comment by rxin** [comment]
yup; just did

**Review by dongjoon-hyun — APPROVED** [review]
Thank you.
+1, LGTM.

**Comment by dongjoon-hyun** [comment]
nit. Could you add `[CORE]` to the PR title, too?

**Comment by dilipbiswal** [comment]
retest this please

**Comment by cloud-fan** [comment]
retest this please

**Comment by rxin** [comment]
seems like our tests are really flaky

**Comment by cloud-fan** [comment]
retest this please

**Comment by dongjoon-hyun** [comment]
Ya. It's amazing to see 5 different failures in the same PR. :(

1. org.apache.spark.scheduler.MapStatusSuite.SPARK-24519: HighlyCompressedMapStatus has configurable threshold
2. This patch fails SparkR unit tests.
3. This patch fails due to an unknown error code, -9.
4. This patch fails PySpark unit tests.
5.  org.apache.spark.sql.streaming.continuous.ContinuousSuite.query without test harness

**Comment by cloud-fan** [comment]
retest this please

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Review by jiangxb1987 — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Merged to master/branch-2.4.

**Pull request closed without merging**
