### PR TITLE
[SPARK-26010][R] fix vignette eval with Java 11

### PR DESCRIPTION
**Pull request by felixcheung**
## What changes were proposed in this pull request?

changes in vignette only to disable eval

## How was this patch tested?

Jenkins

### CODE REVIEW

**Review by srowen — APPROVED** [review]

**Comment by felixcheung** [comment]
merged to master/2.4

**Comment by felixcheung** [comment]
merged to branch-2.3 also (since we are making 2.3.3)

**Comment by felixcheung** [comment]
@maropu could you pick up this for 2.3.3? looks like I've just missed by 15min

**Comment by maropu** [comment]
@felixcheung Thanks, pinging me! Yea, I'll do that.

**Pull request closed without merging**
