### PR TITLE
[SPARK-15796] [CORE] Reduce spark.memory.fraction default to avoid overrunning old gen in JVM default config

### PR DESCRIPTION
**Pull request by srowen**
## What changes were proposed in this pull request?

Reduce `spark.memory.fraction` default to 0.6 in order to make it fit within default JVM old generation size (2/3 heap). See JIRA discussion. This means a full cache doesn't spill into the new gen. CC @andrewor14 
## How was this patch tested?

Jenkins tests.

### CODE REVIEW

**Comment by darabos** [comment]
Thanks Sean! 0.66 would probably work well. But I think @gaborfeher tested only with 0.6, and this value seemed to be the conclusion on JIRA ([comment](https://issues.apache.org/jira/browse/SPARK-15796?focusedCommentId=15318526&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15318526)).

If you're updating the documentation files anyway, how about copying the line from `spark.storage.memoryFraction` to `spark.memory.fraction`? It's good advice:

> This should not be larger than the "old" generation of objects in the JVM, which by default is given 0.6 of the heap, but you can increase it if you configure your own old generation size.

Thanks!

**Comment by srowen** [comment]
Jenkins retest this please

**Comment by andrewor14** [comment]
This looks OK but somewhat arbitrary. This whole thing depends a lot on the data structures the user allocates outside of Spark so no matter how low we make it there will be some applications that will not work.

Also will those potentially introduce a different kind of regression, where apps in 1.6 with memory fraction = 0.75 run faster than apps in 2.0 with a lower memory fraction? Maybe it's OK if all the other performance advances in 2.0 are sufficient in offsetting that.

**Comment by srowen** [comment]
Yeah this does not guarantee that you won't fill the old generation, though that's always been a possibility. It does tend to keep all Spark's likely tenured objects within the old generation. Really, lots of real-world use cases have always needed a higher non-default setting for `NewRatio`. If you mostly fill `spark.memory.fraction` with cached data now you'll definitely fill the old gen.

I think this was an issue in 1.6 in that setting `spark.storage.memoryFraction` to 0.75 and filling up the cache would also run over the old gen.

Really I'm just sense-checking the change; it makes sense but I also am sort of surprised we didn't encounter this before?

**Comment by andrewor14** [comment]
cc @davies @JoshRosen for sanity check

**Comment by davies** [comment]
LGTM

**Comment by srowen** [comment]
Merged to master/2.0

**Pull request closed without merging**
