### PR TITLE
[SPARK-3611] [Web UI] Show number of cores for each executor in application web UI

### PR DESCRIPTION
**Pull request by ajbozarth**
Added a Cores column in the Executors UI

### CODE REVIEW

**Comment by ajbozarth** [comment]
Since we have api access to the information now as I discovered in #10154 I've added the Cores column. 

Do we want to move where it is located in the table?

spark-3611_cores
[Note: this screenshot is take with the fix in #11038]

**Comment by ajbozarth** [comment]
looping in @tgravescs @zsxwing @JoshRosen since you reviewed the first PR

**Comment by holdenk** [comment]
Seems like the test failure is unrelated (I got the same in one of my PRs too). Jenkins retest this please.

**Comment by ajbozarth** [comment]
Can't seem to win with Jenkins. Jenkins retest this please.

**Comment by zsxwing** [comment]
retest this please

**Comment by zsxwing** [comment]
LGTM. Merging to master. Thanks, @ajbozarth

**Pull request closed without merging**
