### PR TITLE
[SPARK-13493][SQL] Enable case sensitiveness in json schema inference.

### PR DESCRIPTION
**Pull request by zuowang**
## What changes were proposed in this pull request?

Pass "caseSensitiveAnalysis" to InferSchema. Change field name to lowercase when "caseSensitiveAnalysis" is false.
## How was this patch tested?

Add new test case in DataFrameSuite.

### CODE REVIEW

**Comment by tedyu** [comment]
Jenkins, test this please

**Comment by zuowang** [comment]
What would be the case like in CSV? I don't think anybody want to conbine "user" and "User" column when "caseSensitiveAnalysis" is false.
`scala> val jsonDF = sqlContext.read.option("header", "true").csv("file.csv")
jsonDF: org.apache.spark.sql.DataFrame = [user: string,  User: string ... 1 more field]

scala> jsonDF.show
+-------+-------+-----+
|   user|   User| hits|
+-------+-------+-----+
|     om|  scala|  120|
| daniel|  spark|   80|
|3754978|  spark|    1|
+-------+-------+-----+`

**Comment by maropu** [comment]
@rxin Currently, do we have any policy to handle case-sensitivity inside spark? e.g., `postgresql` always holds names into lower case (https://www.postgresql.org/docs/9.5/static/sql-syntax-lexical.html) and `h2` does into upper one. It seems there are many case-sensitivity issue in not only `json`, but also other other datasources.

unquoted names are always folded to lower case.

**Comment by gatorsmile** [comment]
@maropu Yes. We need to consider case sensitivity for the built-in data sources at least.

**Comment by gatorsmile** [comment]
@zuowang @maropu Are you still working on this? We should resolve this issue.

**Comment by maropu** [comment]
I'm not, so it's okay to do so.

**Comment by zuowang** [comment]
I'm not, could you work to resolve it?

**Comment by HyukjinKwon** [comment]
Let's close this if it is not in a progress.

**Comment by gatorsmile** [comment]
We are closing it due to inactivity. please do reopen if you want to push it forward. Thanks!

**Pull request closed without merging**
