### PR TITLE
[SPARK-17320] add build_profile_flags entry to mesos build module

### PR DESCRIPTION
**Pull request by mgummelt**
## What changes were proposed in this pull request?

add build_profile_flags entry to mesos build module
## How was this patch tested?

unit tests

### CODE REVIEW

**Comment by srowen** [comment]
Can you attack this in the title to the original JIRA to make the Mesos profile? LGTM though

**Comment by mgummelt** [comment]
Damn, you're quick.  I added a new JIRA before I saw this message.  Hope that's alright too.

**Comment by srowen** [comment]
OK, no big deal.

**Comment by mgummelt** [comment]
cc @srowen for merge

**Comment by vanzin** [comment]
Merging to master.

**Pull request closed without merging**
