### PR TITLE
[SPARK-43448][BUILD] Remove dummy dependency `hadoop-openstack`

### PR DESCRIPTION
**Pull request by pan3793**
### What changes were proposed in this pull request?

Remove the dummy dependency `hadoop-openstack` from Spark binary artifacts.

### Why are the changes needed?

[HADOOP-18442](https://issues.apache.org/jira/browse/HADOOP-18442) removed the `hadoop-openstack` and temporarily retained a dummy jar for the downstream project which consumes it.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass GA.

### CODE REVIEW

**Comment by pan3793** [comment]
cc @dongjoon-hyun @sunchao @steveloughran

**Review by dongjoon-hyun — COMMENTED** [review]
It's really interesting because that kind of dependency deletion happened in the maintenance release (Apache Hadoop 3.3.5).

**Comment by steveloughran** [comment]
we emptied the jar but left the stub artifact there so that things which did explicitly pull it in wouldn't start breaking.

Now that spark is 3.3.5+ only most of the hadoop-cloud-storage dependencies can be reworked down to just
* import hadoop-cloud-storage
* cut alliyun-sdk if you don't want it (the 3.3.5 version isn't breaking s3 any more, FWIW)
* add google gcs

**Comment by pan3793** [comment]
@steveloughran does Hadoop 3.3.5 guarantee compatibility w/ previous versions? e.g. is it OK to use Hadoop 3.3.5 client to access Hadoop 3.3.0~3.3.4 server?

**Review by dongjoon-hyun — APPROVED** [review]
Thank you for the context, @pan3793 and @steveloughran .

**Comment by dongjoon-hyun** [comment]
Merged to master for Apache Spark 3.5.0.

**Comment by steveloughran** [comment]
>  is it OK to use Hadoop 3.3.5 client to access Hadoop 3.3.0~3.3.4 server?

should be. IPC is all based on protobuf and we try not to remove things to avoid breaking existing code. HDFS compatibility across major versions is something which mattersd a lot, I believe webhdfs has the strongest guarantees.

what does break, guaranteed, is mixing hadoop libraries from different versions on the classpath. Avoid that. on and for cloudstuff openssl/wildfly is a source of extreme brittleness, even though when it works it's often faster than JVM ssl

**Comment by pan3793** [comment]
Got it, thanks @steveloughran

**Pull request closed without merging**
