### PR TITLE
[SPARK-38389][SQL] Add the `DATEDIFF()` and `DATE_DIFF()` aliases for `TIMESTAMPDIFF()` 

### PR DESCRIPTION
**Pull request by MaxGekk**
### What changes were proposed in this pull request?
In the PR, I propose to add two aliases for the `TIMESTAMPDIFF()` function introduced by https://github.com/apache/spark/pull/35607:
- `DATEDIFF()`
- `DATE_DIFF()`

### Why are the changes needed?
1. To make the migration process from other systems to Spark SQL easier.
2. To achieve feature parity with other DBMSs.

### Does this PR introduce _any_ user-facing change?
No. The new aliases just extend Spark SQL API.

### How was this patch tested?
1. By running the existing test suites:
```
$ build/sbt "test:testOnly *SQLKeywordSuite"
```
3. and new checks:
```
$ build/sbt "sql/testOnly org.apache.spark.sql.SQLQueryTestSuite -- -z date.sql"
$ build/sbt "sql/testOnly org.apache.spark.sql.SQLQueryTestSuite -- -z datetime-legacy.sql"
```

### CODE REVIEW

**Comment by MaxGekk** [comment]
@cloud-fan @HyukjinKwon @gengliangwang @superdupershant Could you review this PR, please.

**Review by cloud-fan — APPROVED** [review]

**Comment by MaxGekk** [comment]
Merging to master. Thank you, @cloud-fan for review.

**Comment by Obbay2** [comment]
@MaxGekk How can this be reconciled with the fact that the `datediff` function already exists in Spark SQL since 1.5.0? The order of the parameters are also different such that older `datediff` function is endDate followed by startDate.

https://github.com/MaxGekk/spark/blob/6a8b74a02cb8f5bfac0cbcf45f3aada0ad6f2614/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/datetimeExpressions.scala#L2314

**Comment by cloud-fan** [comment]
Maybe we should deprecate the old `datediff` function. The new `datediff` function has a special parser rule so that it won't conflict with the old one, but I agree that 2 `datedff` functions with different syntax and semantic is weird. cc @srielau

**Comment by srielau** [comment]
> Maybe we should deprecate the old `datediff` function. The new `datediff` function has a special parser rule so that it won't conflict with the old one, but I agree that 2 `datedff` functions with different syntax and semantic is weird. cc @srielau

There seem to be two camps here: datediff() SQL server and friends which is the newer form. And datediff() IBM, mySQL and friends, which is the older form https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_datediff . 
We have a long standing tradition of supporting diofferent spellings etc for similar/same functions.
This particular one is actually rather harmless since number of arguments differ.
So I propose to leave them be.

**Pull request closed without merging**
