### PR TITLE
[SPARK-21484][SQL] Fix inconsistent query plans of Dataset after persist/unpersist

### PR DESCRIPTION
**Pull request by viirya**
## What changes were proposed in this pull request?

After the call of persist/unpersis, the query plans of a `Dataset` should be changed accordingly. But currently the query plans are the same. So you will see the inconsistent query plans like:

    scala> val x1 = Seq(1).toDF()
    x1: org.apache.spark.sql.DataFrame = [value: int]
    scala> println(x1.queryExecution.executedPlan) // query plans are materialized before persist()
    LocalTableScan [value#1]
    scala> x1.persist()
    scala> x1.count()
    scala> println(x1.queryExecution.executedPlan)
    LocalTableScan [value#1]

    scala> val x1 = Seq(1).toDF()
    x1: org.apache.spark.sql.DataFrame = [value: int]
    scala> x1.persist()
    scala> x1.count()
    scala> println(x1.queryExecution.executedPlan) // query plans are materialized after persist()
    InMemoryTableScan [value#24]
       +- InMemoryRelation [value#24], true, 10000, StorageLevel(disk, memory, deserialized, 1 replicas)
             +- LocalTableScan [value#1]
    scala> x1.unpersist()
    scala> println(x1.queryExecution.executedPlan)
    InMemoryTableScan [value#24]
       +- InMemoryRelation [value#24], true, 10000, StorageLevel(disk, memory, deserialized, 1 replicas)
             +- LocalTableScan [value#1]

After this fix:

    scala> val x1 = Seq(1).toDF()
    x1: org.apache.spark.sql.DataFrame = [value: int]
    scala> println(x1.queryExecution.executedPlan)
    LocalTableScan [value#1]
    scala> x1.persist()
    scala> x1.count()
    scala> println(x1.queryExecution.executedPlan)
    InMemoryTableScan [value#1]
       +- InMemoryRelation [value#1], true, 10000, StorageLevel(disk, memory, deserialized, 1 replicas)
             +- LocalTableScan [value#1]
    scala> x1.unpersist()
    scala> println(x1.queryExecution.executedPlan)
    LocalTableScan [value#1]

## How was this patch tested?

Added test case.

### CODE REVIEW

**Comment by viirya** [comment]
cc @cloud-fan

**Comment by cloud-fan** [comment]
Should `Dataset` be thread-safe? cc @rxin @gatorsmile

**Comment by viirya** [comment]
Btw, as `QueryExecution.toRdd` executes the executed plan. Once it is materialized by the Dataset before persist, it still executes the uncached executed plan. There're few places in Dataset calling `toRdd`.

**Comment by gatorsmile** [comment]
Thanks for fixing this, but this PR does not fix all the cases that caused by our materialized plans in the QueryExecution. For examples,
```Scala
      Seq("1", "2").toDF().write.saveAsTable("t")
      val ds1 = spark.table("t")
      val ds2 = spark.table("t")
      ds1.collect()
      ds2.persist()
      ds1.collect() --> this still use the uncached plan.
```

**Comment by viirya** [comment]
@gatorsmile Thanks for reporting that.

It is hard to argue the reported case is valid in semantics. Actually ds1 and ds2 are two different Datasets. In semantics, you cache one Dataset, why another Dataset needs to be cached too?

**Comment by gatorsmile** [comment]
My above example is pretty common in many Spark SQL use cases. Many users rely on it. As long as one table is cached in one session, the other sessions can use the cached table without reading the table again.

**Comment by viirya** [comment]
Ok. Sounds reasonable. I'm preparing new fix for the case.

**Comment by viirya** [comment]
@gatorsmile This introduces another question, when one table in cached in one session, and other session uncache the table, now is the original table cached or uncached?

**Comment by viirya** [comment]
There is another case we should fix. You can see the storage level of ds2 is StorageLevel.NONE, but its executed plan is still cached version. 

    scala> Seq("1", "2").toDF().write.saveAsTable("t")
    scala> val ds1 = spark.table("t")
    ds1: org.apache.spark.sql.DataFrame = [value: string]
    scala> val ds2 = spark.table("t")
    ds2: org.apache.spark.sql.DataFrame = [value: string]

    scala> ds1.persist()
    res1: ds1.type = [value: string]

    scala> ds2.queryExecution.executedPlan
    res2: org.apache.spark.sql.execution.SparkPlan =
    InMemoryTableScan [value#11]
       +- InMemoryRelation [value#11], true, 10000, StorageLevel(disk, memory, deserialized, 1 replicas)
             +- *FileScan parquet default.t[value#7] Batched: true, Format: Parquet, Location: InMemoryFileIndex[file:/root/repos/spark-1/spark-warehouse/t], PartitionFilters: [], PushedFilters: [], ReadSchema: struct<value:string>

    scala> ds1.unpersist()
    res3: ds1.type = [value: string]

    scala> ds2.queryExecution.executedPlan
    res4: org.apache.spark.sql.execution.SparkPlan =
    InMemoryTableScan [value#11]
       +- InMemoryRelation [value#11], true, 10000, StorageLevel(disk, memory, deserialized, 1 replicas)
             +- *FileScan parquet default.t[value#7] Batched: true, Format: Parquet, Location: InMemoryFileIndex[file:/root/repos/spark-1/spark-warehouse/t], PartitionFilters: [], PushedFilters: [], ReadSchema: struct<value:string>
    scala> ds2.storageLevel
    res5: org.apache.spark.storage.StorageLevel = StorageLevel(1 replicas)

**Comment by viirya** [comment]
We need to well define the cache behavior of Dataset.

I agree that once a table is cached, other Dataset should use the cached table without reading it again.

Then once a table is uncached, other Dataset now should use the cached table or uncached table?

**Comment by gatorsmile** [comment]
It is well defined, but never well documented. So far, there are multiple issues in the existing cache mechanism. We hesitate to do any major change until we figure out what is the next step of the whole cache management.

**Comment by viirya** [comment]
Since you said it is well defined, then I suppose that the coded behavior of cache:

* Once a dataset is cached, the same fragment of logical plan in other datasets should use the cached plan.
* Once a dataset is uncached, the same fragment of logical plan in other datasets should fallback to uncached plan.

is correct and we don't want to change.

**Comment by gatorsmile** [comment]
> Once a dataset is uncached, the same fragment of logical plan in other datasets should fallback to uncached plan.

This is true, although the plan looks like the same. However, the execution is not using the cached data.

> Once a dataset is cached, the same fragment of logical plan in other datasets should use the cached plan.

This is true, if and only if your first execution of `queryExecution` is after `persist()`. If you check most of our APIs, we are building a new `QueryExecution`.

**Comment by gatorsmile** [comment]
I think you might push more changes in the following few hours. If the changes are clean and safe, we still need a SQLConf to ensure the behaviors can be changed back. We might not be able to accept any behavior change in 2.x. 

The changes of this PR (before this comment) is changing the fundamental of the Catalyst design. More importantly, it could also hurt the third-party libraries which are built on Spark SQL. Thus, writing a detailed design doc (SPIP) might be better.

**Comment by viirya** [comment]
Except for fixing the weird consequence of caching e.g. https://github.com/apache/spark/pull/18687#issuecomment-317159979 and  https://github.com/apache/spark/pull/18687#issuecomment-317186128, I'd keep the current behavior described above https://github.com/apache/spark/pull/18687#issuecomment-317220129 and https://github.com/apache/spark/pull/18687#issuecomment-317230592.

**Comment by viirya** [comment]
>> Once a dataset is uncached, the same fragment of logical plan in other datasets should fallback to uncached plan.

> This is true, although the plan looks like the same. However, the execution is not using the cached data.

There're few places in `Dataset` directly calling `QueryExecution.toRdd`, which uses the materialized query plan that still contains cached relation.

**Comment by viirya** [comment]
> The changes of this PR (before this comment) is changing the fundamental of the Catalyst design. More importantly, it could also hurt the third-party libraries which are built on Spark SQL. Thus, writing a detailed design doc (SPIP) might be better.

If it's necessary, I'd write the doc. Currently the change is just limited to the internal of `QueryExecution`.

**Comment by kiszk** [comment]
Jenkins, retest this please

**Comment by viirya** [comment]
@kiszk There're test failure. I'm trying to fix it.

**Comment by gatorsmile** [comment]
After rethinking it, to fundamentally fix the issue, the ideal design is to introduce a mechanism like a global `dynamic statement cache`. This can resolve many our existing issues and also improve the performance of our query compilation.

**Comment by viirya** [comment]
Do we have dynamic SQL statements?

**Comment by gatorsmile** [comment]
So far, we do not support dynamic SQL statement, but this is a potential feature we can explore in the future. A global statement cache and management can reduce the optimization costs, especially when our CBO optimizer is more advanced. 

At the same time, it also resolves a more general issue. We can invalidate all the physical plans that are built based on the stale info. Data cache is just one of the examples. It could also include out-of-dated statistics. The previous optimized plan might not make sense any more when the underlying tables inserts/deletes a large amount of data.

**Comment by viirya** [comment]
> So far, we do not support dynamic SQL statement, but this is a potential feature we can explore in the future. A global statement cache and management can reduce the optimization costs, especially when our CBO optimizer is more advanced.

I agree. The dynamic statement cache is used to reduce the costly preparation process by reusing prepared (parsed, analyzed and optimized) statement. IIUC, this only works for identical dynamic SQL statements. When CBO optimizer goes more advanced and more costly, the statement cache might help reduce the cost for identical statements.

The current cache in SparkSQL is not for statement cache, but for query plan fragment (and its execution result) cache. A query doesn't need to be identical to cached query plan. It can reuse the cached plan even when the cached one is just a fragment of it.

So seems to me they are orthogonal and can be complementary.

**Comment by viirya** [comment]
cc @cloud-fan Can you help review this too? Thanks.

**Comment by gatorsmile** [comment]
This really depends on how you implement the global statement cache and management. All the compiled plans can be stored in the cache. The plans can be reused, if possible (the reused plans might not be identical). 

The plan recompilation in this PR can be part of global statement cache and management. Plan recompilation can be manual or automatic. In this specific case, it should be done automatically.

**Comment by viirya** [comment]
ping @cloud-fan Please help review this too. Thanks.

**Comment by gatorsmile** [comment]
@viirya Could you close this PR?

**Comment by viirya** [comment]
Sure.

**Comment by viirya** [comment]
@gatorsmile Any suggestion for this issue? Leave it as it for now?

**Pull request closed without merging**
