### PR TITLE
[MINOR][DOCS] Emphasize the Streaming tab is for DStream API

### PR DESCRIPTION
**Pull request by xuanyuanking**
### What changes were proposed in this pull request?
Emphasize the Streaming tab is for DStream API.

### Why are the changes needed?
Some users reported that it's a little confusing of the streaming tab and structured streaming tab.

### Does this PR introduce _any_ user-facing change?
Document change.

### How was this patch tested?
N/A

### CODE REVIEW

**Comment by xuanyuanking** [comment]
cc @HyukjinKwon @xccui as a minor follow up for SPARK-31792

**Review by HyukjinKwon — APPROVED** [review]

**Review by srowen — APPROVED** [review]

**Comment by xccui** [comment]
LGTM

**Comment by HyukjinKwon** [comment]
Merged to master and branch-3.0

**Comment by xuanyuanking** [comment]
Thanks for reviewing.

**Pull request closed without merging**
