### PR TITLE
[SPARK-28199][SS][FOLLOWUP] Mention the change of SPARK-28199 into the SS migration guide

### PR DESCRIPTION
**Pull request by HeartSaVioR**
### What changes were proposed in this pull request?

SPARK-28199 (#24996) made the trigger related public API to be exposed only from static methods of Trigger class. This is backward incompatible change, so some users may experience compilation error after upgrading to Spark 3.0.0.

While we plan to mention the change into release note, it's good to mention the change to the migration guide doc as well, since the purpose of the doc is to collect the major changes/incompatibilities between versions and end users would refer the doc.

### Why are the changes needed?

SPARK-28199 is technically backward incompatible change and we should kindly guide the change.

### Does this PR introduce _any_ user-facing change?

Doc change.

### How was this patch tested?

N/A, as it's just a doc change.

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
cc. @cloud-fan @srowen

**Comment by cloud-fan** [comment]
thanks, merging to master/3.0!

**Comment by HeartSaVioR** [comment]
Thanks for reviewing and merging!

**Comment by srowen** [comment]
That seems fine, but we're not going to roll another RC for this anyway

**Pull request closed without merging**
