### PR TITLE
[SPARK-40391][SQL][TESTS][FOLLOWUP] Change to use `mockito-inline` instead of manually write MockMaker

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr aims use `mockito-inline` instead of manually write `MockMaker`

### Why are the changes needed?
`mockito-inline` is a more recommended [way](https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html#39) to use mockito to mocking final types, enums and final methods
 and `mllib` and `mllib-local` module is already using `mockito-inline`.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?

- Pass GitHub Actions
- Manual test:run `build/sbt clean "sql/testOnly *QueryExecutionErrorsSuite"` with Java 8u352, 11.0.17 and 17.0.5, all 3 Java versions passed

### CODE REVIEW

**Review by panbingkun — APPROVED** [review]

**Comment by LuciferYang** [comment]
cc @MaxGekk @HyukjinKwon

**Comment by LuciferYang** [comment]
@panbingkun as discuss offline, I run `build/sbt clean "sql/testOnly *QueryExecutionErrorsSuite"` with this pr, all test passed

**Review by MaxGekk — APPROVED** [review]
Waiting for CI.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by LuciferYang** [comment]
All passed

**Comment by LuciferYang** [comment]
Thanks @srowen @HyukjinKwon @MaxGekk @panbingkun

**Pull request closed without merging**
