### PR TITLE
[SPARK-12647][SQL] Fix o.a.s.sqlexecution.ExchangeCoordinatorSuite.determining the number of reducers: aggregate operator

### PR DESCRIPTION
**Pull request by robbinspg**
change expected partition sizes

### CODE REVIEW

**Comment by rxin** [comment]
Jenkins, test this please.

**Comment by rxin** [comment]
cc @yhuai

**Comment by yhuai** [comment]
LGTM. Merging to branch 1.6.

**Comment by yhuai** [comment]
I have merged this. Can you close the PR? Thank you!

**Comment by robbinspg** [comment]
I closed this as per request but it states "Closed with unmerged commits"

**Comment by yhuai** [comment]
@robbinspg oh that does not matter. It has been merged (https://github.com/apache/spark/commit/5afa62b20090e763ba10d9939ec214a11466087b).

**Pull request closed without merging**
