### PR TITLE
[SPARK-49643][SQL] Merge _LEGACY_ERROR_TEMP_2042 into ARITHMETIC_OVERFLOW

### PR DESCRIPTION
**Pull request by mihailomilosevic2001**
### What changes were proposed in this pull request?
Merging related legacy error to its proper class.

### Why are the changes needed?
We want to get remove legacy errors, as they are not properly migrated to the new system of errors. Also, [PR](https://github.com/apache/spark/pull/48206/files#diff-0ffd087e0d4e1618761a42c91b8712fd469e758f4789ca2fafdefff753fe81d5) started getting to big, so this is an effort to split the change needed.

### Does this PR introduce _any_ user-facing change?
Yes, legacy error is now merged into ARITHMETIC_OVERFLOW.

### How was this patch tested?
Existing tests check that the error message stayed the same.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Review by srielau — APPROVED** [review]

**Review by MaxGekk — COMMENTED** [review]
@mihailom-db Don't we have any test for the case? You changed the error condition but there are no affected tests. Please, check the case.

**Comment by mihailom-db** [comment]
@MaxGekk the problem here is that legacy_error_temp_2042 would have returned the same message as ARITHMETIC_OVERFLOW, but someone just added a new method in QueryExecutionErrors for codeGen path, even though in eval path we threw the same error, but just under different class. I can add a golden file test, to throw this error, but I am not sure if golden files call codeGen or eval path?

**Comment by MaxGekk** [comment]
@mihailom-db `checkErrorInExpression` checks both codegen and non-codegen

**Comment by mihailom-db** [comment]
I see, I found tests in `IntervalExpressionSuite.scala` but they did not check for anything in the error, they just checked that error is there. Will update them so they do the right check.

**Comment by mihailom-db** [comment]
@MaxGekk updated the test, it seems the whole class is just checking if error is thrown and not actually what errors are thrown, so codeGen and eval might be different errors for even more expressions

**Review by MaxGekk — APPROVED** [review]
Waiting for CI.

**Comment by MaxGekk** [comment]
+1, LGTM. Merging to master.
Thank you, @mihailom-db.

**Pull request closed without merging**
