### PR TITLE
[SPARK-20877][SPARKR][WIP] add timestamps to test runs

### PR DESCRIPTION
**Pull request by felixcheung**
## What changes were proposed in this pull request?

to investigate how long they run

## How was this patch tested?

Jenkins, AppVeyor

### CODE REVIEW

**Comment by felixcheung** [comment]
AppVeyor test portion took about 5 min https://ci.appveyor.com/project/ApacheSoftwareFoundation/spark/build/1361-master

**Comment by felixcheung** [comment]
perhaps we could cut down a lot more tests though http://r-pkgs.had.co.nz/tests.html#test-cran
if the target is under 1 min...

**Comment by shivaram** [comment]
@felixcheung This is very cool. Let me try this on a windows VM and winbuilder and get back to you.

**Comment by marmbrus** [comment]
Ping?  I'd like to cut the next RC.

**Comment by felixcheung** [comment]
We were talking about another more drastic approach but what we have here would be improvement.

I'm reverting as-cran so this can go in (after another round of tests), and I think then should unblock RC.

**Comment by felixcheung** [comment]
ok passes. @shivaram what do you think about this?

**Comment by shivaram** [comment]
LGTM. Thanks @felixcheung for the update and @marmbrus for the ping

**Comment by felixcheung** [comment]
@shivaram did you get the chance to look at refactoring tests we discussed?

**Pull request closed without merging**
