### PR TITLE
SPARK-6846 [WEBUI] Stage kill URL easy to accidentally trigger and possibility for security issue

### PR DESCRIPTION
**Pull request by srowen**
kill endpoints now only accept a POST (kill stage, master kill app, master kill driver); kill link now POSTs

### CODE REVIEW

**Comment by squito** [comment]
can you add a test that kill no longer supports GET?  something like:

```
  test("kill stage is POST only") {
    withSpark(getSparkContext(killEnabled = true)) { sc =>
      runSlowJob(sc)
      eventually(timeout(5 seconds), interval(50 milliseconds)) {
        val url = new URL(sc.ui.get.appUIAddress.stripSuffix("/") + "/stages/stage/kill/?id=0&terminate=true")
        getResponseCode(url, "GET") should be (405)
        getResponseCode(url, "POST") should be (200)
      }
    }
  }
```

**Comment by srowen** [comment]
Sounds like you just did! thanks for that. I'll include that and also figure out the test failure.

**Comment by squito** [comment]
lgtm

**Comment by devldevelopment** [comment]
Looks good and much safer. However, is it still possible to kill a spark stage "externally"(outside of the UI or context) via POST even if spark.ui.killEnabled = false?

I'm just wondering also whether a job can be killed external by clients in an unsafe way. 

In relation, is there a test for what happens when a kill id does not exist?

**Comment by devldevelopment** [comment]
Looks much safer. Although is it still possible to kill a stage from an external client (non-ui) when spark.ui.killEnabled=false?

Similarly what is the behaviour when trying to kill a stage that does not exist? E.g when invoked from an external client.

**Comment by srowen** [comment]
Yeah I think that's right, you could still kill a stage by sending a request directly. That's easy to change. Killing a non-existent stage would result in some error / 5xx response. An explicit 4xx would probably be better but probably not that important.

**Comment by witgo** [comment]
@srowen  This PR seems to have a bug in yarn-client:

```
HTTP ERROR 405

Problem accessing /proxy/application_1429108701044_0316/stages/stage/kill/. Reason:

    HTTP method POST is not supported by this URL
````

**Comment by srowen** [comment]
Hm, can @sryza or @vanzin or someone who understands YARN help me understand what this proxy is? I know there's some redirecting that happens to get you to the Spark UI on YARN, but then I don't see why any further links would be proxied on that UI?

**Comment by vanzin** [comment]
IIUC when you link your application in the RM, the RM proxies all calls to the application's UI while it's alive. And apparently it doesn't support POST...

**Comment by srowen** [comment]
Hmh. https://hadoop.apache.org/docs/r2.6.0/hadoop-yarn/hadoop-yarn-site/WebApplicationProxy.html I see the purpose here, but surely it can proxy a POST? this seems like something some config something controls but I don't know what it may be.

@witgo are you sure you have the latest Spark build on your cluster? trying to figure out if the proxy is reporting something from the actual Spark UI. Or can you send a POST directly to the Spark endpoint to verify that it works?

**Comment by witgo** [comment]
The hadoop version of my test cluster is `2.3.0-cdh5.0.1`.  I'm not sure, tomorrow I'll test what you said.

**Comment by witgo** [comment]
`curl -d "id=3&terminate=true" "http://host:4040/stages/stage/kill/"` does not work.  There are other better way?

**Comment by srowen** [comment]
Doesn't work in that you get a 405?

**Comment by witgo** [comment]
No, get blanks.  but 
 `curl -d "id=3&terminate=true" "http://host:9082/proxy/application_1429108701044_0377/stages/stage/kill/"` get a 405

**Comment by srowen** [comment]
That's fine, in the sense that the endpoint returns no data. OK, so it works except for this proxying. Hm, surely the YARN proxy can pass on a POST. We'll have to look into this. Any wisdom from YARN folks about where to look?

**Comment by vanzin** [comment]
The [source](https://github.com/apache/hadoop/blob/branch-2/hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-web-proxy/src/main/java/org/apache/hadoop/yarn/server/webproxy/WebAppProxyServlet.java) seems to indicate the proxy code only supports `GET`...

**Comment by srowen** [comment]
That's surely unfortunate. OK, looks like I need to partly undo this change. The link needs to `GET` and the endpoint needs to accept `GET` unfortunately, but everything else can stay the same.

**Comment by srowen** [comment]
Followed up in https://github.com/apache/spark/pull/5837

**Pull request closed without merging**
