### PR TITLE
[SPARK-6303][SQL] Remove unnecessary Average in GeneratedAggregate

### PR DESCRIPTION
**Pull request by viirya**
Because `Average` is a `PartialAggregate`, we never get a `Average` node when reaching `HashAggregation` to prepare `GeneratedAggregate`.

That is why in SQLQuerySuite there is already a test for `avg` with codegen. And it works.

But we can find a case in `GeneratedAggregate` to deal with `Average`. Based on the above, we actually never execute this case.

So we can remove this case from `GeneratedAggregate`.

### CODE REVIEW

**Comment by viirya** [comment]
@marmbrus @liancheng Would you please take a look of this? Thanks!

**Comment by viirya** [comment]
@liancheng @yhuai @marmbrus Please take a look, thanks.

**Comment by marmbrus** [comment]
Please add a test in SQLQuerySuite "aggregation with codegen".

**Comment by viirya** [comment]
After doing more search, I just found that because `Average` is a `PartialAggregate`, we never get a `Average` node when reaching `HashAggregation` to prepare `GeneratedAggregate`. So we don't need to add `Average` as this pr did.

That is why in SQLQuerySuite there is already a test for `avg` with codegen. And it works.

What interesting is that we can find a case in `GeneratedAggregate` to deal with `Average`. Based on the above, we actually never execute this case.

So I would like to remove this case from `GeneratedAggregate`.

**Pull request closed without merging**
