### PR TITLE
[SPARK-6041][GraphX] Compute shortest path for graph with edge distances

### PR DESCRIPTION
**Pull request by viirya**
Add the function to compute shortest path for graph with edge distances.

### CODE REVIEW

**Comment by viirya** [comment]
Not sure who is do the review for this part. Does anyone like to review this? Thanks!

**Comment by viirya** [comment]
@ankurdave @srowen Can you help review this pr? Thanks!

**Comment by srowen** [comment]
I think Ankur would have to review/approve this one, or maybe @jegonzal

**Comment by srowen** [comment]
I think this has timed out, would you mind closing this PR for now?

**Comment by viirya** [comment]
Ok.

**Pull request closed without merging**
