### PR TITLE
[SPARK-44863][UI][3.5] Add a button to download thread dump as a txt in Spark UI

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

This PR added a button to download thread dump as a txt w.r.t. jstack formatting

### Why are the changes needed?

The formatting of raw jstack can be relatively easy to read and analyze using various thread tools.

### Does this PR introduce _any_ user-facing change?

image

#### Raw Dump File
[driver.txt](https://github.com/apache/spark/files/12388302/driver.txt)

#### Reporting by external tools

https://fastthread.io/my-thread-report.jsp?p=c2hhcmVkLzIwMjMvMDgvMjAvZHJpdmVyLnR4dC0tMTMtNTMtMjI=&

### Was this patch authored or co-authored using generative AI tooling?

no

### CODE REVIEW

**Review by zhengruifeng — APPROVED** [review]

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
I love your passion, @yaooqinn and @zhengruifeng, but we are in RC2 stage. This PR is a new feature completely and looks inappropriate to branch-3.5 at this time.

Screenshot 2023-08-24 at 10 38 47 AM

**Comment by zhengruifeng** [comment]
@dongjoon-hyun yes, thanks for the reminder.

@yaooqinn let's keep this feature only in master, sorry for asking for merging to 3.5

**Comment by yaooqinn** [comment]
It's okay @zhengruifeng. And thank you, @dongjoon-hyun, for the clarification.

**Comment by dongjoon-hyun** [comment]
Thank you for the decision, @yaooqinn and @zhengruifeng .

**Pull request closed without merging**
