### PR TITLE
[SPARK-48487][INFRA] Update License & Notice according to the dependency changes

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

This PR updated License & Notice files according to the dependency changes

I also did a little refactoring to make it in alphabetical order

### Why are the changes needed?

to meet apache release policy

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

manually check
### Was this patch authored or co-authored using generative AI tooling?
no

### CODE REVIEW

**Comment by yaooqinn** [comment]
cc @cloud-fan as the release manager of 4.0.0-preview1

**Review by cloud-fan — APPROVED** [review]

**Comment by cloud-fan** [comment]
should we put it in the release process guideline so that it's a step of the release?

**Comment by yaooqinn** [comment]
Yes. We also need to do this in routine dependency update PRs，which can sufficiently reduce the RM's workload

**Review by HyukjinKwon — APPROVED** [review]

**Comment by yaooqinn** [comment]
Merged to master

**Pull request closed without merging**
