### PR TITLE
[SPARK-33159][SQL] Use hive-service-rpc as dependency instead of inlining the generated code

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

Hive's `hive-service-rpc` module started since hive-2.1.0 and it contains only the thrift IDL file and the code generated by it.

Removing the inlined code will help maintain and upgrade builtin hive versions

### Why are the changes needed?

to simply the code.

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

passing CI

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Sounds nice!

**Comment by HyukjinKwon** [comment]
cc @wangyum and @juliuszsompolski FYI

**Review by wangyum — COMMENTED** [review]
Sorry, this change will cause user unable to modify `TCLIService.thrift`, for example, we have made these modifications to `TCLIService.thrift`:
```diff
diff --git a/sql/hive-thriftserver/v2.3/if/TCLIService.thrift b/sql/hive-thriftserver/v2.3/if/TCLIService.thrift
index 9026cd25df5..ce8843a1061 100644
--- a/sql/hive-thriftserver/v2.3/if/TCLIService.thrift
+++ b/sql/hive-thriftserver/v2.3/if/TCLIService.thrift
@@ -716,6 +716,50 @@ struct TExecuteStatementResp {
   2: optional TOperationHandle operationHandle
 }

+// UploadData()
+//
+// Upload data from JDBC client.
+struct TUploadDataReq {
+  // The session to execute the statement against
+  1: required TSessionHandle sessionHandle
+
+  // The path to be stored
+  2: required string path
+
+  // The data to be transferred
+  3: required binary values
+}
+
+struct TUploadDataResp {
+  1: required TStatus status
+  2: required TOperationHandle operationHandle
+}
+
+// DownloadData()
+//
+// Download data to JDBC client.
+struct TDownloadDataReq {
+  // The session to download data
+  1: required TSessionHandle sessionHandle
+
+  // The download table name
+  2: optional TPatternOrIdentifier tableName
+
+  // The download query
+  3: optional string query
+
+  // The download file format
+  4: optional string format
+
+  // The download options
+  5: optional map<string, string> downloadOptions
+}
+
+struct TDownloadDataResp {
+  1: required TStatus status
+  2: required TOperationHandle operationHandle
+}
+
 // GetTypeInfo()
 //
 // Get information about types supported by the HiveServer instance.
@@ -1054,6 +1098,10 @@ struct TGetOperationStatusResp {
 
   10: optional TProgressUpdateResp progressUpdateResponse
 
+  11: optional double progressedPercentage
+
+  12: optional i64 numModifiedRows
+
 }
```

**Comment by yaooqinn** [comment]
HI @wangyum the case you give seem not  a regular one. If you are maintaining a custom spark branch, it makes not much difference whether you modify the code in spark or in a privately maintained hive-service-rpc artifact.

**Comment by dongjoon-hyun** [comment]
Hi, @wangyum . Can we apply the patch to the upstream Apache Hive?

cc @sunchao

**Comment by wangyum** [comment]
@dongjoon-hyun I'm not sure. We use it to upload or download data to the JDBC client, because we only want to expose the JDBC interface to users.

**Comment by HyukjinKwon** [comment]
@wangyum, can you be more specific? Seems I can't find `UploadData` or `DownloadData` in the current master. Do you mean other forks can't do such modification?

**Comment by HyukjinKwon** [comment]
OSS side seems it's correct to remove the unnecessary duplication. Other forks will likely have to exclude this change and keep their own changes in their fork.

@yaooqinn one thing we'd have to check if there''re any Hive upgrades vs our inlined generated codes, and whitelist what new they bring and if we have to port anything.

**Comment by wangyum** [comment]
@HyukjinKwon We add `UploadData` and `DownloadData` to our own Spark fork for these reasons:
1. Upload data to cluster by JDBC/ODBC client.
2. Download hundreds of GB data from Spark Thrift Server by JDBC/ODBC client.
3. Make it possible to fetch hundreds of GB data to MicroStrategy/Tableau from Spark Thrift Server.


On the other hand, do we plan to use Hive's `TCLIService.thrift` all the time?

**Comment by yaooqinn** [comment]
> @yaooqinn one thing we'd have to check if there''re any Hive upgrades vs our inlined generated codes, and whitelist what new they bring and if we have to port anything.

Yes, I have checked that. There is no diff between our inlined codes and those from `hive-service-rpc:2.3.7`. Add I also checked Hive' master branch, it added `HIVE_CLI_SERVICE_PROTOCOL_V11` since 3.0.0 and V11 added timestamp with timezone type. This hive type is not supported by spark just like the existing INTERVAL_DAY_TIME_TYPE.
So I believe there is nothing we need to port now. We only need to add unimplemented APIs to just make the compiler happy when we upgrade the builtin hive

**Comment by yaooqinn** [comment]
> On the other hand, do we plan to use Hive's TCLIService.thrift all the time?

hi, @wangyum, I believe that when you changed the IDL of `TCLIService.thrift`, you have to make your `hive-jdbc` artifact for the APIs that you added. 

Similarly, if we are not going to use `TCLIService.thrift` anymore in the future, we have to make our own JDBC driver module, and the `hive-jdbc` from Hive may be not able to use anymore. 

If we really need to extend something of spark's own in the future. A more legitimate way is to use `thrift Include` to inherit `TCLIService.thrift`

**Comment by dongjoon-hyun** [comment]
@wangyum First of all, if that is beneficial to Apache Hive in the same way, please make it possible in Apache Hive. Hive community will welcome it.
> We add UploadData and DownloadData to our own Spark fork for these reasons:
> 1. Upload data to cluster by JDBC/ODBC client.
> 2. Download hundreds of GB data from Spark Thrift Server by JDBC/ODBC client.
> 3. Make it possible to fetch hundreds of GB data to MicroStrategy/Tableau from Spark Thrift Server.

Second, if this is not used in Apache Spark, we had better remove the deadcode from Apache Spark 3.1. It's a community burden. We had better remove those `63,672` lines.

cc @gatorsmile and @cloud-fan

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @yaooqinn , @HyukjinKwon , @wangyum .

In the forked Spark repository, we can do everything including reverting this commit (not only using different `TCLIService.thrift`)

Merged to master for Apache Spark 3.1.0.

**Review by HyukjinKwon — COMMENTED** [review]
LGTM too

**Pull request closed without merging**
