### PR TITLE
[MINOR]Fix Long Type mismatch

### PR DESCRIPTION
**Pull request by kelvin-qin**
The maximumSize(long size) need long Type param ,but conf.get(config.STORAGE_LOCAL_DISK_BY_EXECUTORS_CACHE_SIZE) return Int Type,So Type mismatch,just fix it.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
I don't think it's worth fixing it. isn't it a legitimate upcasting?

**Comment by srowen** [comment]
This doesn't do anything. It's an int conf. Obviously, it works to pass it as a long param.

**Comment by kelvin-qin** [comment]
fine,thank you for closing it .

**Comment by kelvin-qin** [comment]
Actually,the conf.get return ConfigEntry[Int] type,This will cause a warning or error message in IDE. 

> This doesn't do anything. It's an int conf. Obviously, it works to pass it as a long param.

**Pull request closed without merging**
