### PR TITLE
[SPARK-38993][PYTHON] Impl DataFrame.boxplot and DataFrame.plot.box

### PR DESCRIPTION
**Pull request by zhengruifeng**
### What changes were proposed in this pull request?
Impl DataFrame.boxplot and DataFrame.plot.box

### Why are the changes needed?
to increase pandas API coverage in PySpark

### Does this PR introduce _any_ user-facing change?
yes

```
In [2]: df = ps.DataFrame([[5.1, 3.5, 0], [4.9, 3.0, 0], [7.0, 3.2, 1], [6.4, 3.2, 1], [5.9, 3.0, 2]], columns=['length', 'width', 'species'])

In [3]: df.boxplot()
Out[3]:                                                                         
In [4]: df.plot.box()
Out[4]: 
```

image

### How was this patch tested?
added ut and manually tests

### CODE REVIEW

**Comment by zhengruifeng** [comment]
gentlely ping @HyukjinKwon @ueshin @itholic @xinrong-databricks

**Comment by zhengruifeng** [comment]
`boxplot` in the pandas' side:

```
In [25]: df = pd.DataFrame([[5.1, 3.5, 0], [4.9, 3.0, 0], [7.0, 3.2, 1], [6.4, 3.2, 1], [5.9, 3.0, 2]], columns=['length', 'width', 'species'])

In [26]: 

In [26]: df.boxplot(backend='plotly')
    ...: 
Out[26]: 
In [27]: df.plot.box(backend='plotly')
Out[27]: 


```

image

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by HyukjinKwon** [comment]
@zhengruifeng thank you really so much for working on this. this is really awesome.

**Comment by zhengruifeng** [comment]
@HyukjinKwon Thanks for reviewing!

**Pull request closed without merging**
