### PR TITLE
[SPARK-26019][PYTHON] Fix race condition in accumulators.py: _start_update_server()

### PR DESCRIPTION
**Pull request by Tagar**
## What changes were proposed in this pull request?

Fixing race condition that happens in accumulators.py: _start_update_server()

1) SocketServer:TCPServer defaults bind_and_activate to True
https://github.com/python/cpython/blob/2.7/Lib/SocketServer.py#L413 

2) Also `handle()` is defined in derived class _UpdateRequestHandler here 
https://github.com/apache/spark/blob/master/python/pyspark/accumulators.py#L232

These both together can causes a race condition that leads to race condition explained in 
https://issues.apache.org/jira/browse/SPARK-26019

> 
> Exception happened during processing of request from ('127.0.0.1', 43418)
>
> Traceback (most recent call last):
>   File "/opt/cloudera/parcels/Anaconda/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
>     self.process_request(request, client_address)
>   File "/opt/cloudera/parcels/Anaconda/lib/python2.7/SocketServer.py", line 318, in process_request
>     self.finish_request(request, client_address)
>   File "/opt/cloudera/parcels/Anaconda/lib/python2.7/SocketServer.py", line 331, in finish_request
>     self.RequestHandlerClass(request, client_address, self)
>   File "/opt/cloudera/parcels/Anaconda/lib/python2.7/SocketServer.py", line 652, in __init__
>     self.handle()
>   File "/opt/cloudera/parcels/SPARK2-2.3.0.cloudera4-1.cdh5.13.3.p0.611179/lib/spark2/python/lib/pyspark.zip/pyspark/accumulators.py", line 263, in handle
>     poll(authenticate_and_accum_updates)
>   File "/opt/cloudera/parcels/SPARK2-2.3.0.cloudera4-1.cdh5.13.3.p0.611179/lib/spark2/python/lib/pyspark.zip/pyspark/accumulators.py", line 238, in poll
>     if func():
>   File "/opt/cloudera/parcels/SPARK2-2.3.0.cloudera4-1.cdh5.13.3.p0.611179/lib/spark2/python/lib/pyspark.zip/pyspark/accumulators.py", line 251, in authenticate_and_accum_updates
>     received_token = self.rfile.read(len(auth_token))
> TypeError: object of type 'NoneType' has no len()
>  

## How was this patch tested?

Tested in the same environment where I can always reproduce it. 
This change fixes this issue.
Tested manually.

### CODE REVIEW

**Comment by Tagar** [comment]
@squito please help review this PR

Thank you.

**Comment by HyukjinKwon** [comment]
> race condition explained in https://issues.apache.org/jira/browse/SPARK-26019

How race condition happens? Can you clarify it in PR description. I think @viirya's analysis is matched to what I investigated (https://issues.apache.org/jira/browse/SPARK-26019?focusedCommentId=16692722&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16692722).

**Comment by Tagar** [comment]
@HyukjinKwon  This is somehow related to the fact that it is reproducible when PySpark was created using an existing py4j gateway (for example, it reproduces from within Zeppelin)

https://github.com/apache/spark/blob/f83fedc9f20869ab4c62bb07bac50113d921207f/python/pyspark/context.py#L99 

In case of Zeppelin, it creates its own Gateway 

https://github.com/apache/zeppelin/blob/adf83a3f5d009efd0e0416a7bf1d8b6fd86ea58a/spark/interpreter/src/main/resources/python/zeppelin_ipyspark.py#L33

And if `PY4J_GATEWAY_SECRET` environment variable wasn't set, it creates Gateway without `auth_token` set:
`gateway = JavaGateway(GatewayClient(address="${JVM_GATEWAY_ADDRESS}", port=${JVM_GATEWAY_PORT}), auto_convert=True)`

py4j allows working without auth tokens :
https://github.com/bartdag/py4j/blob/079fcf11ec18058af0b356f78974125eb7384711/py4j-python/src/py4j/java_gateway.py#L774

As I mentioned in SPARK-26019, it's only first request that gets this error 

```
  File "../lib/spark2/python/lib/pyspark.zip/pyspark/accumulators.py", line 263, in handle
    poll(authenticate_and_accum_updates)
  File "../lib/spark2/python/lib/pyspark.zip/pyspark/accumulators.py", line 238, in poll
    if func():
  File "../lib/spark2/python/lib/pyspark.zip/pyspark/accumulators.py", line 251, in authenticate_and_accum_updates
    received_token = self.rfile.read(len(auth_token))
TypeError: object of type 'NoneType' has no len()
 
```

Rerunning same request works later on fine. 

Is it because auth_token gets set? Or just because there are no accumulator update requests for following requests? I don't know internals of Spark that well to answer that, but hopefully this provides some more context to help assess this problem and why this PR fixes it.

Thank you.

**Comment by squito** [comment]
I'm not sure if I follow the entire discussion here yet.  I did spend a while trying to figure out if there is a race condition, and I'm pretty sure there is not.  From your last comments, it looks like there is a bug in zepplin for not correctly ensuring that authentication is enabled on the java gateway, and as @HyukjinKwon indicates, perhaps a bug in spark for not failing more obviously. 

I dont' think I understand this:

> auto token should be set to use Spark

what "auto token" are you referring to?


We should be able to support creating the java gateway inside zepplin, I think its conceptually the same as what is done when you launch a pyspark shell.  Probably zepplin should be doing something like this: https://github.com/apache/spark/blob/master/python/pyspark/java_gateway.py#L40

**Comment by HyukjinKwon** [comment]
Typo... auth_token ...  Zeppelin supports it BTW.

**Comment by Tagar** [comment]
`auth_token` is only used in accumulators update server 
https://github.com/apache/spark/search?q=auth_token&unscoped_q=auth_token
- relatively new code that was added in this commit - https://github.com/apache/spark/commit/15fc2372269159ea2556b028d4eb8860c4108650#diff-c3339bbf2b850b79445b41e9eecf57c4R249 

We use Zeppelin 0.8, and it was working fine before 2.3.2 upgrade - all other releases of Spark 2.2, 2.1 and 2.3.1 were working fine. 

If pySpark context is created using existing jvm gateway, like Zeppelin does, then making `auth_token` mandatory seems to be a breaking change? A temporary workaround for 2.3 and 2.4 branches might be just adding an `if` condition here https://github.com/apache/spark/blob/master/python/pyspark/accumulators.py#L254 and bypass `auth_token` check if spark context doesn't have it set? 

I agree it's a good idea to add a check if `auth_token` exists in existing jvm gateway, and maybe silently set a new `auth_token` or fail spark context creation like you were saying, but again it's a breaking change for a next major release?

Also I still don't know why rerunning same code fixes the issue. It might be just due to the fact that there are no updates are coming to the accumulators update server - it only happens on 1st run? Then the problem just lurking until next update will come to the accumulators update server. 

Thoughts? Thank you both.

**Comment by HyukjinKwon** [comment]
Adding @rxin and @gatorsmile fyi. We'll discuss this separately per policy.

**Comment by HyukjinKwon** [comment]
So, are we going to update this PR for issuing warning or create another PR?

**Comment by squito** [comment]
I chatted w/ @Tagar , sounds like he doesn't have time to pick this up -- could you close this PR then?  I also updated SPARK-26019 and created SPARK-26349 with what is happening and the plan for updating.

i think this work is up for grabs if anybody would like to volunteer.  I should get a chance to by next week, if nobody else can.

**Pull request closed without merging**
