### PR TITLE
[SPARK-31082][CORE] MapOutputTrackerMaster.getMapLocation should handle last mapIndex correctly

### PR DESCRIPTION
**Pull request by Ngone51**
### What changes were proposed in this pull request?

In `getMapLocation`, change the condition from `...endMapIndex < statuses.length` to `...endMapIndex <= statuses.length`.

### Why are the changes needed?

`endMapIndex` is exclusive, we should include it when comparing to `statuses.length`. Otherwise, we can't get the location for last mapIndex.

### Does this PR introduce any user-facing change?

No.

### How was this patch tested?

Updated existed test.

### CODE REVIEW

**Comment by Ngone51** [comment]
ping @cloud-fan @JkSelf Please take a look, thanks!

**Comment by JkSelf** [comment]
Good catch!  LGTM

**Comment by cloud-fan** [comment]
thanks, merging to master/3.0!

**Comment by Ngone51** [comment]
thanks all!

**Pull request closed without merging**
