### PR TITLE
[SPARK-13031] [SQL] cleanup codegen and improve test coverage

### PR DESCRIPTION
**Pull request by davies**
1. enable whole stage codegen during tests even there is only one operator supports that.
2. split doProduce() into two APIs: upstream() and doProduce()
3. generate prefix for fresh names of each operator
4. pass UnsafeRow to parent directly (avoid getters and create UnsafeRow again)
5. fix bugs and tests.

This PR re-open #10944 and fix the bug.

### CODE REVIEW

**Comment by rxin** [comment]
What's the bug?

**Comment by davies** [comment]
When there is no aggregate functions, it did not generate the output using resultExpression, which have only literals (I was mislead by the comment in AggregateIterator).

**Comment by rxin** [comment]
Thanks - can you add a test case that would catch this? In the long run, we don't want to rely on HiveCompatibilitySuite.

**Comment by davies** [comment]
The way we managed HiveCompatibilitySuite is actually better than our unit tests (sql query and golden results in text format). Even if we don't want to be compatible with Hive, it's still good to have those tests (don't call them HiveCompatibilitySuite), and also managed in similar way.

**Comment by rxin** [comment]
Sure it's a good idea to use that golden file infrastructure. Given we don't have that yet, can you just add a test case?

**Comment by rxin** [comment]
The issue here is that we want test cases that are targeted for specific problems, and the Hive ones are not (they are just a giant blackbox we took to bootstrap coverage).

**Comment by davies** [comment]
@rxin Added.

**Comment by rxin** [comment]
LGTM

**Comment by rxin** [comment]
I've merged this.

**Pull request closed without merging**
