### PR TITLE
[SPARK-6113] [mllib] Stabilize DecisionTree and ensembles APIs

### PR DESCRIPTION
**Pull request by jkbradley**
This is a PR for cleaning up and finalizing the DecisionTree and tree ensembles APIs.

_Please discuss overall design on the JIRA and implementation details here in this PR._
### Goal

Here is the description copied from the JIRA:

> **Issue**: The APIs for DecisionTree and ensembles (RandomForests and GradientBoostedTrees) have been experimental for a long time. The API has become very convoluted because trees and ensembles have many, many variants, some of which we have added incrementally without a long-term design.
> **Proposal**: This JIRA is for discussing changes required to finalize the APIs. After we discuss, I will make a PR to update the APIs and make them non-Experimental. This will require making many breaking changes; see the design doc for details.
> **[Design doc](https://docs.google.com/document/d/1rJ_DZinyDG3PkYkAKSsQlY0QgCeefn4hUv7GsPkzBP4)** : This outlines current issues and the proposed API.

Overall code layout:
- The old API in mllib.tree.\* will remain the same.
- The new API will reside in mllib.classification.\* and mllib.regression.*
### Summary of changes

PR content: 1/6 examples, 1/2 actual code, 1/3 test suites

Old API
- Exactly the same, except I made 1 method in Loss private (but that is not a breaking change since that method was introduced after the Spark 1.3 release).

New APIs
- The new API preserves functionality, except:
  - New API does NOT store prob (probability of label in classification).  I want to have it store the full vector of probabilities but feel that should be in a later PR.
- Only use getter/setter methods
- Use abstractions for parameters, estimators, and models to avoid code duplication
- Limit parameters to relevant algorithms
- For enum-like types, only expose Strings
  - We can make these pluggable later on.

Test suites
- I organized DecisionTreeSuite, but I made absolutely no changes to the tests themselves.
- The test suites for the new API only test (a) similarity with the results of the old API and (b) elements of the new API.
  - After code is moved to this new API, we should move the tests from the old suites which test the internals.
#### Changed names

Parameters
- useNodeIdCache -> cacheNodeIds
- categoricalFeaturesInfo -> categoricalFeatures
- featureSubsetStrategy -> featuresPerNode

Algs/models
- GradientBoostedTrees\* -> GBT*
#### Other changes
- Split: Changed categories to set instead of list
### Questions for reviewers
- Is "DecisionTreeClassificationModel" too long a name?
- Which loss names are best?  SquaredError vs L2loss, AbsoluteError vs. L1loss
- Is this OK in the docs?

```
class DecisionTreeRegressor extends TreeRegressor[DecisionTreeRegressionModel] with DecisionTreeParams[DecisionTreeRegressor] with TreeRegressorParams[DecisionTreeRegressor]
```
### Future

We should open up the abstractions at some point.  E.g., it would be useful to be able to set tree-related parameters in 1 place and then pass those to multiple tree-based algorithms.

Follow-up JIRAs will be (in this order):
- Deprecate old tree code
- Move DecisionTree implementation code to new API.
- Move tests from the old suites which test the internals.
- Update programming guide
- Python API
- Change RandomForest\* to always use bootstrapping, even when numTrees = 1
- Provide the probability of the predicted label for classification.  After we move code to the new API and update it to maintain probabilities for all labels, then we can add the probabilities to the new API.

CC: @mengxr  @manishamde  @codedeft  @chouqin  @MechCoder

### CODE REVIEW

**Comment by jkbradley** [comment]
Here's a copy of the generated docs so you can see how types show up in Scala vs. Java docs:
https://www.dropbox.com/s/m63oid2z0kaoaqo/SPARK-6113-docs_site.zip?dl=0

One note: Even though FeatureSubsetStrategy is very usable in Java, it shows up weirdly in the Java docs (with dollar signs $).  That seems hard to avoid though.

**Comment by jkbradley** [comment]
Note: After conferring with @mengxr  I'll make the enum-like types private for now and only expose an interface taking basic types (String).

**Comment by mengxr** [comment]
* `featuresSubsetStrategy`: R uses `mtry`, which I couldn't understand. sklearn uses `max_features`, which is slightly easier to understand. I don't have good names. How about `featureSampleRatio`? For example, `featuresSampleRatio="auto"`, `featureSampleRatio="sqrt"`, and `featureSampleRatio=0.2`.
* For the implementation of enum-like types, please check the thread on dev list.

**Comment by jkbradley** [comment]
I'm not a fan of "ratio" since none of the options we want are represented as ratios.  My votes would be for one of the following, depending on how pluggable we plan to make this eventually:
* "featuresPerNode" or "featureSubset": Both of these are shorter and clearer to me than other options.
* "featureSubsetStrategy": If we eventually want users to be able to pass in fancy functions beyond log and sqrt, then "strategy" could be meaningful.

For enum-like types, I'll mimic your example from the dev list, but per our discussions, I'll only expose Strings for now and will keep the enum-like types private.  I'd like to expose the enum-like types eventually and even make them pluggable, but we'll postpone that discussion.

**Comment by jkbradley** [comment]
Those updates are partial; the DecisionTreeClassifier and RandomForestClassifier APIs are done, but I need to fill in the rest now.

**Comment by jkbradley** [comment]
Still need to do GBT and Random Forest Regressors, plus save/load for new API.

**Comment by jkbradley** [comment]
Still need to fill out doc, write Java tests, and update examples to use new API. Will then deprecate old API.

And apparently rebase

**Comment by jkbradley** [comment]
Final stretch!  I just need to update the docs now.

**Comment by jkbradley** [comment]
DONE!  I believe everything is ready, and I updated the description.

**Comment by manishamde** [comment]
@jkbradley Apologies for not reviewing earlier. I hope to make one pass over the weekend.

I have one quick question -- what's the rationale for abbreviating gradient boosting and not random forests? Also, I have seen GBDT and GBRT more commonly used even though I prefer GBT. :-)

**Comment by jkbradley** [comment]
@manishamde No problem; thanks in advance!  It's a really long PR but is hopefully simple to review since it's basically just API and tests.

I abbreviated "GradientBoostedTrees" since it's longer than "RandomForest" and since "GBT" is more recognizable than "RF."  The choice of "GradientBoostedTrees" over other variations of the name came from checking usage frequency via Google searches.

I would vote for "GradientBoosting" if we supported more than trees, but that may happen instead in the spark.ml API.

**Comment by jkbradley** [comment]
I'm closing this PR after discussion with @mengxr 

Because of how much code it involves, I'm going to move it to the spark.ml API and will not add it to the spark.mllib API.  (3 copies of the tree API seems egregious when it's this extensive.)  I'll submit each algorithm separately.

**Pull request closed without merging**
