### PR TITLE
[SPARK-42562][CONNECT] UnresolvedNamedLambdaVariable in python do not need unique names

### PR DESCRIPTION
**Pull request by beliefer**
### What changes were proposed in this pull request?
`UnresolvedNamedLambdaVariable` do not need unique names in python. We already did this for the scala client, and it is good to have parity between the two implementations.

### Why are the changes needed?
Try to avoid unique names for `UnresolvedNamedLambdaVariable`.

### Does this PR introduce _any_ user-facing change?
'No'.
New feature

### How was this patch tested?
N/A

### CODE REVIEW

**Comment by hvanhovell** [comment]
@HyukjinKwon @zhengruifeng the rationale for this change is that analyzer takes care of making lambda variables unique.

**Comment by beliefer** [comment]
@hvanhovell After my test, `python/run-tests --testnames 'pyspark.sql.connect.dataframe'` will not passed.

**Comment by zhengruifeng** [comment]
I guess we will need to rewrite the lamda function in spark connect planner.

cc @ueshin as well, since existing implementation follows the fix in https://github.com/apache/spark/pull/32523

**Comment by beliefer** [comment]
image

**Comment by beliefer** [comment]
> I guess we will need to rewrite the lamda function in spark connect planner.

Yeah.

**Comment by hvanhovell** [comment]
@beliefer scala does support nested lambda variables as well, and they actually work. So either (my) testing on the scala side is incomplete (which might well be the case), or something weird is going on here.

**Comment by beliefer** [comment]
@hvanhovell Scala also uses `UnresolvedNamedLambdaVariable.freshVarName("x")` to get the unique names. see: 
https://github.com/apache/spark/blob/201e08c03a31c763e3120540ac1b1ca8ef252e6b/sql/core/src/main/scala/org/apache/spark/sql/functions.scala#L4096

**Comment by hvanhovell** [comment]
@beliefer here is the thing. When this was designed it was mainly aimed at sql, and there we definitely do not generate unique names in lambda functions either. This is all done in the analyzer. We should be able to follow the same path.

Do you happen to know if test failing for python also fail for scala?

**Comment by beliefer** [comment]
> @beliefer here is the thing. When this was designed it was mainly aimed at sql, and there we definitely do not generate unique names in lambda functions either. This is all done in the analyzer. We should be able to follow the same path.
>

It seems only the lambda functions in SQL will be transformed with analyzer. But the scala, pyspark API will not through analyzer.

**Comment by hvanhovell** [comment]
Ehhhh... SQL/scala/Python all use the analyzer; they are all just frontends to the same thing.

**Comment by beliefer** [comment]
> Ehhhh... SQL/scala/Python all use the analyzer; they are all just frontends to the same thing.

I found the reason. Although the scala API use analyzer too. `object ResolveLambdaVariables extends Rule[LogicalPlan]` can't resolve the issue.
See at: https://github.com/apache/spark/blob/2e7207f96e1ff848def135de63f63bcda7402517/sql/core/src/test/scala/org/apache/spark/sql/DataFrameFunctionsSuite.scala#L5250
image

**Comment by beliefer** [comment]
@hvanhovell Do we still need this change ?

**Comment by zhengruifeng** [comment]
If the nested lambda issue also exists in the Scala Client, do we need to fix it in the same way?

**Pull request closed without merging**
