### PR TITLE
[SPARK-30887][SPARK-30888][SPARK-30889][SPARK-30891][SPARK-30908][SPARK-30909][SPARK-30910][SPARK-30911][SPARK-30912][SPARK-30913][SPARK-30914][3.0] Add version information to the configuration of Deploy, History, NetWork, Worker, Tests, R, Python, Status, Kryo, UI

### PR DESCRIPTION
**Pull request by beliefer**
### What changes were proposed in this pull request?
This PR is related to https://github.com/apache/spark/pull/27668, https://github.com/apache/spark/pull/27708, https://github.com/apache/spark/pull/27704, #27674, #27734, #27751, #27745, #27783, #27806 and used to spark3.0.

### Why are the changes needed?
Supplemental configuration version information.

### Does this PR introduce any user-facing change?
'No'.

### How was this patch tested?
Jenkins test.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
I picked/verified each commit related to this PR manually to branch-3.0.

@beliefer, do you mean keep the commit logs in your PR so that I can manually cherry-pick the commits from your PR to branch-3.0?

Also, it would be nice if we mention the difference against the master. For example, I found two differences:

https://github.com/apache/spark/commit/ebcff675e0c8c915075541af8fa8f9a24087ac11#diff-8b4ea8f3b0cc1e7ce7e943de1abbb165R66

https://github.com/apache/spark/commit/ebcff675e0c8c915075541af8fa8f9a24087ac11#diff-8b4ea8f3b0cc1e7ce7e943de1abbb165R72

**Comment by beliefer** [comment]
@HyukjinKwon Because the three config not exists in branch-3.0, so I not mention them. I want you merge this PR that has resolved these issue or conflict. I think this PR will make you work easier.

**Comment by beliefer** [comment]
@HyukjinKwon I found you pick these change from master, but you forgot `branch-3.0/core/src/main/scala/org/apache/spark/internal/config/Status.scala`.

**Comment by HyukjinKwon** [comment]
Thanks @beliefer for double checking, I will fix it.
For clarification, I would like to keep the commit log similarly in branch-3.0 too, instead of one big PR. We usually open each PR for each backport; however, I asked to open fewer PRs that contains multiple commits because there are too many to backport, and most of them are directly able to backport.

I meant to open a PR, for example, as below:

Title:
`[SPARK-30887][SPARK-30888][SPARK-30889][SPARK-30891][SPARK-30908][SPARK-30909][SPARK-30910][SPARK-30911][SPARK-30912][SPARK-30913][SPARK-30914][3.0] Add version information to the configuration of Deploy, History, NetWork, Worker, Tests, R, Python, Status, Kryo, UI`

Commits in this PR:

Conflict-resolved https://github.com/apache/spark/commit/7911de9d10e39960fcdda379815baf7386b8c34e
Conflict-resolved https://github.com/apache/spark/commit/776e21af40a1f1351b57ff3290d87ee4a4c4c4df
Conflict-resolved https://github.com/apache/spark/commit/c2857501d5a1d06e940e48069e162f184bda5460
...

And then, I backport each commit each conflict-resolved commit manually from your PR to branch-3.0.

**Comment by HyukjinKwon** [comment]
> @HyukjinKwon I found you pick these change from master, but you forgot branch-3.0/core/src/main/scala/org/apache/spark/internal/config/Status.scala.

Seems like you forgot to mention https://github.com/apache/spark/pull/27848 :). I will port it back too.

**Comment by HyukjinKwon** [comment]
#27848 seems dependent on https://github.com/apache/spark/pull/27847 due to a couple of changes such as https://github.com/apache/spark/commit/bd2b3f9132f39588564b3581beda3baa89ed062e#diff-76e731333fb756df3bff5ddb3b731c46R519.

I ported back both #27847 and #27848

**Comment by beliefer** [comment]
@HyukjinKwon I get your mean. I will follows your suggestion and add corresponding commits info.

**Pull request closed without merging**
