### PR TITLE
[SPARK-6464][Core]Add a function named 'processCoalesce' in RDD to support partition combination

### PR DESCRIPTION
**Pull request by SaintBacchus**
Nowadays, the transformation coalesce was always used to expand or reduce the number of the partition in order to gain a good performance.
But coalesce can't make sure that the child partition will be executed in the same executor as the parent partition. And this will lead to have a large network transfer.
In some scenario such as I mentioned in the title small and cached rdd, we want to coalesce all the partition in the same executor into one partition and make sure the child partition will be executed in this executor. It can avoid network transfer and reduce the scheduler of the Tasks and also can reused the cpu core to do other job. 
In this scenario, our performance had improved 20% than before.

### CODE REVIEW

**Comment by sryza** [comment]
@SaintBacchus is my understanding correct that this functions the same as `coalesce` but with an additional performance optimization?  What would be the advantages and disadvantages of always just turning this on in `coalesce`?

**Comment by SaintBacchus** [comment]
@sryza it's very close to the 'coalesce', but 'coalesce' can't make sure the next compution will be in the same executor and this cause network transfor
The advantage of 'processCoalesce' is : reduce the network transfor and save the num of cores;
The disadvantage is also that: it almost only can be used in the small cached rdd.
BTW, in this patch I had expose an interface of executor level task scheduler.

**Comment by srowen** [comment]
This seems like a lot of extra code to add; can we quantify the performance difference at all? I agree with @sryza that it sounds like one of those things worth doing under the existing method if at all, not adding a second path for.

**Comment by SaintBacchus** [comment]
@srowen Ok, I will take this `RDD` into the transformation of `coalesce` later.
And about the performance, in our scenario we reused the cached RDD tens of times.
So if coalescing the partition into one at the same executor without any network transfer, the performance will obviously be improved. Actually 20% as we tested.

**Comment by SaintBacchus** [comment]
Hi @srowen this PR have many code, so I had divided this PR into 3 sub task. Can you have a look at the https://github.com/apache/spark/pull/5240 ?

**Pull request closed without merging**
