### PR TITLE
[SPARK-38817][K8S][BUILD] Upgrade kubernetes-client to 5.12.2

### PR DESCRIPTION
**Pull request by Yikun**
### What changes were proposed in this pull request?
Upgrade kubernetes-client to 5.12.2:
Changes list:
- https://github.com/fabric8io/kubernetes-client/releases/tag/v5.12.2

  - Volcano extension doesn't support queue API (bug)

### Why are the changes needed?
The next kubernetes client version will be 6.x with breaking changes: https://github.com/fabric8io/kubernetes-client/blob/master/CHANGELOG.md#note-breaking-changes-in-the-api .

We'd better to upgrade to latest 5.X first to reduce follow upgrade cost.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
- CI
- integration test

### CODE REVIEW

**Comment by Yikun** [comment]
```
[info] KubernetesSuite:
[info] - Run SparkPi with no resources (9 seconds, 309 milliseconds)
[info] - Run SparkPi with no resources & statefulset allocation (7 seconds, 707 milliseconds)
[info] - Run SparkPi with a very long application name. (8 seconds, 799 milliseconds)
[info] - Use SparkLauncher.NO_RESOURCE (7 seconds, 864 milliseconds)
[info] - Run SparkPi with a master URL without a scheme. (7 seconds, 646 milliseconds)
[info] - Run SparkPi with an argument. (7 seconds, 718 milliseconds)
[info] - Run SparkPi with custom labels, annotations, and environment variables. (7 seconds, 561 milliseconds)
[info] - All pods have the same service account by default (7 seconds, 568 milliseconds)
[info] - Run extraJVMOptions check on driver (4 seconds, 578 milliseconds)
[info] - Run SparkRemoteFileTest using a remote data file (7 seconds, 602 milliseconds)
[info] - Verify logging configuration is picked from the provided SPARK_CONF_DIR/log4j2.properties (8 seconds, 28 milliseconds)
[info] - Run SparkPi with env and mount secrets. (14 seconds, 724 milliseconds)
[info] - Run PySpark on simple pi.py example (9 seconds, 723 milliseconds)
[info] - Run PySpark to test a pyfiles example (9 seconds, 579 milliseconds)
[info] - Run PySpark with memory customization (7 seconds, 587 milliseconds)
[info] - Run in client mode. (6 seconds, 218 milliseconds)
[info] - Start pod creation from template (7 seconds, 764 milliseconds)
[info] - SPARK-38398: Schedule pod creation from template (7 seconds, 649 milliseconds)
[info] - Test basic decommissioning (41 seconds, 771 milliseconds)
[info] - Test basic decommissioning with shuffle cleanup (42 seconds, 582 milliseconds)
[info] - Test decommissioning with dynamic allocation & shuffle cleanups (2 minutes, 42 seconds)
[info] - Test decommissioning timeouts (43 seconds, 111 milliseconds)
[info] - SPARK-37576: Rolling decommissioning (1 minute, 6 seconds)
[info] VolcanoSuite:
[info] - Run SparkPi with no resources (9 seconds, 231 milliseconds)
[info] - Run SparkPi with no resources & statefulset allocation (8 seconds, 898 milliseconds)
[info] - Run SparkPi with a very long application name. (8 seconds, 805 milliseconds)
[info] - Use SparkLauncher.NO_RESOURCE (8 seconds, 813 milliseconds)
[info] - Run SparkPi with a master URL without a scheme. (8 seconds, 712 milliseconds)
[info] - Run SparkPi with an argument. (8 seconds, 706 milliseconds)
[info] - Run SparkPi with custom labels, annotations, and environment variables. (8 seconds, 650 milliseconds)
[info] - All pods have the same service account by default (8 seconds, 661 milliseconds)
[info] - Run extraJVMOptions check on driver (4 seconds, 545 milliseconds)
[info] - Run SparkRemoteFileTest using a remote data file (9 seconds, 72 milliseconds)
[info] - Verify logging configuration is picked from the provided SPARK_CONF_DIR/log4j2.properties (9 seconds, 262 milliseconds)
[info] - Run SparkPi with env and mount secrets. (16 seconds, 952 milliseconds)
[info] - Run PySpark on simple pi.py example (8 seconds, 981 milliseconds)
[info] - Run PySpark to test a pyfiles example (10 seconds, 819 milliseconds)
[info] - Run PySpark with memory customization (8 seconds, 895 milliseconds)
[info] - Run in client mode. (6 seconds, 181 milliseconds)
[info] - Start pod creation from template (8 seconds, 853 milliseconds)
[info] - SPARK-38398: Schedule pod creation from template (8 seconds, 798 milliseconds)
[info] - Test basic decommissioning (43 seconds, 708 milliseconds)
[info] - Test basic decommissioning with shuffle cleanup (42 seconds, 464 milliseconds)
[info] - Test decommissioning with dynamic allocation & shuffle cleanups (2 minutes, 41 seconds)
[info] - Test decommissioning timeouts (44 seconds, 231 milliseconds)
[info] - SPARK-37576: Rolling decommissioning (1 minute, 7 seconds)
[info] - Run SparkPi with volcano scheduler (9 seconds, 42 milliseconds)
[info] - SPARK-38187: Run SparkPi Jobs with minCPU (26 seconds, 549 milliseconds)
[info] - SPARK-38187: Run SparkPi Jobs with minMemory (26 seconds, 718 milliseconds)
[info] - SPARK-38188: Run SparkPi jobs with 2 queues (only 1 enabled) (16 seconds, 513 milliseconds)
[info] - SPARK-38188: Run SparkPi jobs with 2 queues (all enabled) (23 seconds, 970 milliseconds)
[info] - SPARK-38423: Run driver job to validate priority order (16 seconds, 557 milliseconds)
```

**Review by srowen — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @Yikun and @srowen .
Merged to master/3.3 for the latest bug fixes including `Volcano extension doesn't support queue API ` bug.

- Fix https://github.com/fabric8io/kubernetes-client/issues/3582: SSL truststore can be loaded in FIPS enabled environments
- Fix https://github.com/fabric8io/kubernetes-client/pull/3797: Implement SchemaSwap; generate CRD from model not owned
- Fix https://github.com/fabric8io/kubernetes-client/pull/3811: Reintroduce Replaceable interface in NonNamespaceOperation
- Fix https://github.com/fabric8io/kubernetes-client/issues/3818: adding missing throws to launderThrowable
- Fix https://github.com/fabric8io/kubernetes-client/issues/3848: Supports Queue (cluster) API for Volcano extension
- Fix https://github.com/fabric8io/kubernetes-client/issues/3859: refined how a deserialization class is chosen to not confuse types with the same kind
- Fix https://github.com/fabric8io/kubernetes-client/issues/3880: Synchronize access to map in KubernetesCrudDispatcher
- Fix https://github.com/fabric8io/kubernetes-client/pull/3936: Kubernetes Mock Server .metadata.generation field is an integer
- Fix https://github.com/fabric8io/kubernetes-client/issues/3957: Lister onOpen should be called before marking the connection as open
- Fix https://github.com/fabric8io/kubernetes-client/issues/4022: Reintroduce Deletable interface in NonNamespaceOperation

**Comment by dongjoon-hyun** [comment]
BTW, @Yikun . `Volcano extension doesn't support queue API ` was a bug.
I switched SPARK-38817 to `Bug` from `Improvement` and backported it to branch-3.3.

**Comment by Yikun** [comment]
@dongjoon-hyun Thanks! Yes, it is.

BTW, this queue api haven't be used by spark yet, but it will help some when we want to create queue and change capacity simply in IT (such as resource limited case, I will try recently).

**Pull request closed without merging**
