### PR TITLE
[SPARK-44256][BUILD] Upgrade rocksdbjni to 8.3.2

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
This pr aims to upgrade rocksdbjni from 8.1.1.1 to 8.3.2.

### Why are the changes needed?
The release notes: https://github.com/facebook/rocksdb/releases/tag/v8.3.2
- Bug Fixes
Reduced cases of illegally using Env::Default() during static destruction by never destroying the internal PosixEnv itself (except for builds checking for memory leaks). (https://github.com/facebook/rocksdb/pull/11538)

- Performance Improvements
Fixed higher read QPS during DB::Open() reading files created prior to https://github.com/facebook/rocksdb/pull/11406, especially when reading many small file (size < 52 MB) during DB::Open() and partitioned filter or index is used.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
- Pass GA.
- Manual test: `org.apache.spark.util.kvstore.RocksDBBenchmark`

**A.8.1.1.1**
```
                                        	count	mean	min	max	95th
dbClose                                 	4	0.472	0.413	0.527	0.527
dbCreation                              	4	263.388	42.032	922.916	922.916
naturalIndexCreateIterator              	1024	0.005	0.001	2.646	0.004
naturalIndexDescendingCreateIterator    	1024	0.002	0.002	0.055	0.002
naturalIndexDescendingIteration         	1024	0.003	0.003	0.021	0.004
naturalIndexIteration                   	1024	0.009	0.003	3.156	0.012
randomDeleteIndexed                     	1024	0.017	0.013	0.381	0.023
randomDeletesNoIndex                    	1024	0.010	0.009	0.032	0.011
randomUpdatesIndexed                    	1024	0.066	0.025	19.900	0.074
randomUpdatesNoIndex                    	1024	0.017	0.015	0.380	0.019
randomWritesIndexed                     	1024	0.097	0.024	52.970	0.093
randomWritesNoIndex                     	1024	0.019	0.015	1.101	0.021
refIndexCreateIterator                  	1024	0.002	0.002	0.044	0.002
refIndexDescendingCreateIterator        	1024	0.001	0.001	0.013	0.001
refIndexDescendingIteration             	1024	0.004	0.003	0.070	0.005
refIndexIteration                       	1024	0.005	0.003	0.230	0.005
sequentialDeleteIndexed                 	1024	0.016	0.013	0.104	0.022
sequentialDeleteNoIndex                 	1024	0.011	0.009	0.044	0.011
sequentialUpdatesIndexed                	1024	0.027	0.019	0.660	0.050
sequentialUpdatesNoIndex                	1024	0.025	0.016	0.523	0.033
sequentialWritesIndexed                 	1024	0.030	0.020	1.526	0.040
sequentialWritesNoIndex                 	1024	0.030	0.017	4.410	0.035
```
**B.8.3.2**
```
                                        	count	mean	min	max	95th
dbClose                                 	4	0.488	0.424	0.556	0.556
dbCreation                              	4	241.375	35.710	850.488	850.488
naturalIndexCreateIterator              	1024	0.004	0.001	1.555	0.006
naturalIndexDescendingCreateIterator    	1024	0.002	0.002	0.064	0.002
naturalIndexDescendingIteration         	1024	0.004	0.003	0.035	0.004
naturalIndexIteration                   	1024	0.011	0.003	4.464	0.012
randomDeleteIndexed                     	1024	0.018	0.013	0.505	0.024
randomDeletesNoIndex                    	1024	0.010	0.009	0.025	0.011
randomUpdatesIndexed                    	1024	0.065	0.024	20.210	0.077
randomUpdatesNoIndex                    	1024	0.019	0.015	0.449	0.027
randomWritesIndexed                     	1024	0.087	0.026	38.782	0.096
randomWritesNoIndex                     	1024	0.019	0.016	1.040	0.019
refIndexCreateIterator                  	1024	0.002	0.002	0.051	0.002
refIndexDescendingCreateIterator        	1024	0.001	0.001	0.013	0.001
refIndexDescendingIteration             	1024	0.004	0.003	0.064	0.004
refIndexIteration                       	1024	0.005	0.003	0.253	0.006
sequentialDeleteIndexed                 	1024	0.016	0.013	0.286	0.024
sequentialDeleteNoIndex                 	1024	0.010	0.009	0.071	0.012
sequentialUpdatesIndexed                	1024	0.026	0.020	0.711	0.042
sequentialUpdatesNoIndex                	1024	0.024	0.016	0.455	0.030
sequentialWritesIndexed                 	1024	0.025	0.020	1.359	0.033
sequentialWritesNoIndex                 	1024	0.028	0.017	4.354	0.030
```

    B.Checked core module UTs with rocksdb live ui
    ```
    export LIVE_UI_LOCAL_STORE_DIR=/${basedir}/spark-ui
    build/mvn clean install -pl core -am -Dtest.exclude.tags=org.apache.spark.tags.ExtendedLevelDBTest -fn
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD SUCCESS
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time:  39:09 min
    [INFO] Finished at: 2023-06-30T09:48:44+08:00
    [INFO] ------------------------------------------------------------------------
    ```

### CODE REVIEW

**Comment by panbingkun** [comment]
Let me add the results of org.apache.spark.sql.execution.benchmark.StateStoreBasicOperationsBenchmark.

**Comment by LuciferYang** [comment]
cc @dongjoon-hyun @HeartSaVioR FYI

**Comment by yaooqinn** [comment]
Can we revert the benchmark result to minimize the diff？

**Comment by panbingkun** [comment]
> Can we revert the benchmark result to minimize the diff？

@HeartSaVioR may be concerned about the potential impact on RocksDBStateStore performance when upgrading to the 'rocksdbjni' version. Do we need to synchronously update the benchmark results of `StateStoreBasicOperationsBenchmark`?

**Comment by yaooqinn** [comment]
IMO, it's only necessary to refresh the result in the codebase when it has a notable improvement for setting a new baseline. Otherwise, I'd rather keep it AS-IS and attach the result in the PR desc.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. I prefer to have the benchmark result in the same PR.

**Comment by dongjoon-hyun** [comment]
Merged to master. Thank you, @panbingkun, @LuciferYang and @yaooqinn .

**Comment by LuciferYang** [comment]
A bad case report @panbingkun: I found a RocksDB crash case during the GitHub Action testing task, which was my first encounter and I am not sure the root cause and its severity now. I have created SPARK-44580 to record it:

- https://github.com/LuciferYang/spark/actions/runs/5666554831/job/15395578871

```
#
17177# A fatal error has been detected by the Java Runtime Environment:
17178#
17179#  SIGSEGV (0xb) at pc=0x00007f8a077d2743, pid=4403, tid=0x00007f89cadff640
17180#
17181# JRE version: OpenJDK Runtime Environment (8.0_372-b07) (build 1.8.0_372-b07)
17182# Java VM: OpenJDK 64-Bit Server VM (25.372-b07 mixed mode linux-amd64 compressed oops)
17183# Problematic frame:
17184# C  [librocksdbjni886380103972770161.so+0x3d2743]  rocksdb::DBImpl::FailIfCfHasTs(rocksdb::ColumnFamilyHandle const*) const+0x23
17185#
17186# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
17187#
17188# An error report file with more information is saved as:
17189# /home/runner/work/spark/spark/sql/core/hs_err_pid4403.log
17190#
17191# If you would like to submit a bug report, please visit:
17192#   https://github.com/adoptium/adoptium-support/issues
17193# The crash happened outside the Java Virtual Machine in native code.
17194# See problematic frame for where to report the bug.
17195# 
```

**Comment by panbingkun** [comment]
> A bad case report @panbingkun: I found a RocksDB crash case during the GitHub Action testing task, which was my first encounter and I am not sure the root cause and its severity now. I have created [SPARK-44580](https://issues.apache.org/jira/browse/SPARK-44580) to record it:
> 
> * https://github.com/LuciferYang/spark/actions/runs/5666554831/job/15395578871
> 
> ```
> #
> 17177# A fatal error has been detected by the Java Runtime Environment:
> 17178#
> 17179#  SIGSEGV (0xb) at pc=0x00007f8a077d2743, pid=4403, tid=0x00007f89cadff640
> 17180#
> 17181# JRE version: OpenJDK Runtime Environment (8.0_372-b07) (build 1.8.0_372-b07)
> 17182# Java VM: OpenJDK 64-Bit Server VM (25.372-b07 mixed mode linux-amd64 compressed oops)
> 17183# Problematic frame:
> 17184# C  [librocksdbjni886380103972770161.so+0x3d2743]  rocksdb::DBImpl::FailIfCfHasTs(rocksdb::ColumnFamilyHandle const*) const+0x23
> 17185#
> 17186# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
> 17187#
> 17188# An error report file with more information is saved as:
> 17189# /home/runner/work/spark/spark/sql/core/hs_err_pid4403.log
> 17190#
> 17191# If you would like to submit a bug report, please visit:
> 17192#   https://github.com/adoptium/adoptium-support/issues
> 17193# The crash happened outside the Java Virtual Machine in native code.
> 17194# See problematic frame for where to report the bug.
> 17195# 
> ```

Let's monitor again.

**Pull request closed without merging**
