### PR TITLE
[SPARK-11572] Process outstanding requests after seeing stop flag

### PR DESCRIPTION
**Pull request by tedyu**
This is to address the regression Josh discovered.

### CODE REVIEW

**Comment by JoshRosen** [comment]
I'd like @zsxwing to help take a look at this and figure out whether this is a sufficient fix or whether we should revert your original patch and go back to the drawing board.

**Comment by JoshRosen** [comment]
It's possible that there's a cleaner way to fix the original bug that motivated the incorrect patch vs. trying to patch up the problems introduced by the fix by layering more fixes on top. Let's see.

**Comment by tedyu** [comment]
```
sbt.ForkMain$ForkError: Test failed with compression using codec org.apache.spark.io.LZ4CompressionCodec:

assertion failed: expected groupByKey to spill, but did not
	at scala.Predef$.assert(Predef.scala:179)
	at org.apache.spark.TestUtils$.assertSpilled(TestUtils.scala:169)
	at org.apache.spark.util.collection.ExternalAppendOnlyMapSuite.org$apache$spark$util$collection$ExternalAppendOnlyMapSuite$$testSimpleSpilling(ExternalAppendOnlyMapSuite.scala:254)
	at org.apache.spark.util.collection.ExternalAppendOnlyMapSuite$$anonfun$10$$anonfun$apply$mcV$sp$8.apply(ExternalAppendOnlyMapSuite.scala:218)
	at org.apache.spark.util.collection.ExternalAppendOnlyMapSuite$$anonfun$10$$anonfun$apply$mcV$sp$8.apply(ExternalAppendOnlyMapSuite.scala:216)
	at scala.collection.immutable.Stream.foreach(Stream.scala:547)
```
I think the above was not related to change in AsynchronousListenerBus

**Comment by zsxwing** [comment]
IMO, we should revert https://github.com/apache/spark/commit/3e0a6cf1e02a19b37c68d3026415d53bb57a576b

The user should not call `stop` or other long-time work in a listener since it will block the listener thread, and prevent from stopping SparkContext/StreamingContext.

I cannot see an approach since we need to stop the listener bus's thread before stopping  SparkContext/StreamingContext totally.

**Comment by JoshRosen** [comment]
I'm going to revert those commits now to try to unbreak the SBT builds.

**Comment by tedyu** [comment]
Sounds like we should prevent the call to StreamingContext#stop() in the listener bus's thread.
How about setting a ThreadLocal Boolean to indicate to StreamingContext that the stop() call should not be honored ?

**Comment by zsxwing** [comment]
> Sounds like we should prevent the call to StreamingContext#stop() in the listener bus's thread.
> How about setting a ThreadLocal Boolean to indicate to StreamingContext that the stop() call should not be honored ?

Sound like a good idea. Ping @tdas, what do you think?

**Pull request closed without merging**
