### PR TITLE
[SPARK-10118][SparkR][Docs] Improve SparkR API docs for 1.5 release

### PR DESCRIPTION
**Pull request by yu-iskw**
cc: @shivaram 
## Summary
- Modify `@tdname` of expression functions. i.e. `ascii`: `@rdname functions` => `@rdname ascii`
- Replace the dynamical function definitions to the static ones because of thir documentations.
## Generated PDF File

https://drive.google.com/file/d/0B9biIZIU47lLX2t6ZjRoRnBTSEU/view?usp=sharing
## JIRA

[[SPARK-10118] Improve SparkR API docs for 1.5 release - ASF JIRA](https://issues.apache.org/jira/browse/SPARK-10118)

### CODE REVIEW

**Comment by yu-iskw** [comment]
@shivaram could you review it?

**Comment by shivaram** [comment]
Thanks @yu-iskw for this change and also for sending the PDF. One question I have is if there is any way we can change the documentation from appearing as `floor,Column-method` to just `floor`. I think we can do this with aliases, but I haven't tried this out. 

cc @davies

**Comment by yu-iskw** [comment]
@shivaram it seems that we can change them with `@name`. I'll try it.

**Comment by yu-iskw** [comment]
@shivaram These are the gists of floor.Rd to show the difference if using `@name` or not. If there are any issues, I can revert the update.

- [floor.Rd with `@name`](https://gist.github.com/yu-iskw/02ec81a225721cc786e6)
- [floor.Rd without `@name`](https://gist.github.com/yu-iskw/9bcd173044dc160f548c)

**Comment by shivaram** [comment]
@yu-iskw Thanks this is looking great ! I tried this locally and ran into one small problem while running `knitr` (using `R/create-docs.sh`). It needs the following diff to work correctly -- Can you add this to the PR ?

```
-Rscript -e 'library(SparkR, lib.loc="../../lib"); library(knitr); knit_rd("SparkR")'
+Rscript -e 'libDir <- "../../lib"; library(SparkR, lib.loc=libDir); library(knitr); knit_rd("SparkR", links = tools::findHTMLlinks(paste(libDir, "SparkR", sep="/")))'
```

Also we should do a similar cleanup of other methods in `columns.R` and `DataFrame.R` but we can do it in a separate PR.

**Comment by yu-iskw** [comment]
@shivaram sure. I have just modified it.

**Comment by shivaram** [comment]
Thanks @yu-iskw -- LGTM. Merging this

**Comment by yu-iskw** [comment]
Thank you for merging it!

**Pull request closed without merging**
