### PR TITLE
[SPARK-16226][SQL]change the way of JDBC commit

### PR DESCRIPTION
**Pull request by lihongliustc**
## What changes were proposed in this pull request?

I change the way of commit.In the original version,it commit once in a partition.I commit after executeBatch.
## How was this patch tested?

 unit tests

change the way of JDBC commit

### CODE REVIEW

**Comment by hvanhovell** [comment]
@lihongliustc could you take a look at the JIRA ticket, and respond to @srowen's very valid comment? I don't think we should do this.

**Comment by gatorsmile** [comment]
As @srowen and @hvanhovell said, changing commits is not right or not enough.

Even if the atomicity might not be needed in some cases, you need to implement something like `NOT ATOMIC CONTINUE ON SQLEXCEPTION`. However, that requires much more efforts to implement.

**Comment by lihongliustc** [comment]
@hvanhovell and @srowen  I just change the way of commits.When there is an exception,it will rollback as usual.The "commited" is a flag of the method.Any exception in the try clause will cause the rollback of the partition.It is same as the situation before i changed the commits.It is still atomic .And I am sure that if we do not change commits,it will cause the blocking.

**Comment by lihongliustc** [comment]
@gatorsmile Thanks.But I think it is still atomic.As I comment above.How do think about it?

**Comment by srowen** [comment]
No, an exception will now only roll back anything that happened since the last commit. It is not the same. The whole reason it's 'blocking' is that you are holding open a transaction, but, that's the point.

There's an interesting point here though; this code is willing to proceed if the RDBMS does not support transactions at all, in which case it _will_ write partial results that can't be rolled back. Really I'd think that in this case you want to call `executeBatch()` only once at the end. I wonder if that's actually a bug (CC @rxin who wrote that bit?)

However, if that is acceptable, then perhaps a weaker JDBC transaction isolation level is acceptable for the case where transactions are supported. If you're willing to accept dirty reads with `TRANSACTION_READ_UNCOMMITTED`, then I don't think (?) the table has to be locked, which may solve your problem. It still means the writes would be rolled back in case of a failure, which is much of the point here according to comments.

CC @CK50 for the transaction question. Also barely related but shouldn't it just call `supportsTransactions()` at the beginning?

**Comment by CK50** [comment]
@sowen: yes, supportsTransactions() sounds good. I do not remember why I 
took the other two conditions and whether this makes any difference.

I agree that committing in between defeats the purpose of the 
transaction action handling.

**Comment by maver1ck** [comment]
@srowen 
Recently I modified MySQL JDBC driver because both supportsDataManipulationTransactionsOnly() and supportsDataDefinitionAndDataManipulationTransactions() return false.

So maybe we can change this condition ?

**Comment by srowen** [comment]
Yes @maver1ck I think that's probably a good change, though it may end up being separate, and related to the isolation level change.

@lihongliustc this PR can be closed. The right solution for this, if any, is to reduce the transaction isolation level. That seems reasonable to me.

As to the issue of non-transactional RDBMSes seeing partial writes that can't be rolled back -- the only thing I can see as a solution is to not use batching, but I think that would run out of memory easily. It may just be how it is without transactions. The javadoc kind of says as much.

**Comment by lihongliustc** [comment]
@srowen Thanks.I will close the PR.And I will try my best to do something like @gatorsmile said.Thanks to every participant.

**Comment by maver1ck** [comment]
@srowen 
Maybe we should change this condition to `conn.getMetaData().supportsTransactions()` ?
I can prepare PR.

**Comment by srowen** [comment]
I think the important change regards the transaction isolation level that's in effect here, but yes that change is also a good one.

**Pull request closed without merging**
