### PR TITLE
[SPARK-41214][SQL] - SQL Metrics are missing from Spark UI when AQE for Cached DataFrame is enabled

### PR DESCRIPTION
**Pull request by erenavsarogullari**
### What changes were proposed in this pull request?

JIRA: https://issues.apache.org/jira/browse/SPARK-41214
`spark.sql.optimizer.canChangeCachedPlanOutputPartitioning` enables AQE optimizations under `InMemoryRelation`(IMR) nodes by creating sub-SparkPlans for AQE optimizations. However, when `spark.sql.optimizer.canChangeCachedPlanOutputPartitioning = true`, Spark UI does not show correct final DAG due to lack of final sub-plans (under IMR) submissions (into UI).

### Why are the changes needed?

`spark.sql.optimizer.canChangeCachedPlanOutputPartitioning` enables AQE optimizations under `InMemoryRelation`(IMR) nodes. Sample query in Jira has IMR node on both `BroadcastHashJoin` legs. However, 
when `spark.sql.optimizer.canChangeCachedPlanOutputPartitioning = true`, following datas are missed due to lack of final sub-plans (under IMR) submissions (into UI).
- Physical operators' SQLMetrics (before AdaptiveSparkPlan) are missed such as Exchange and HashAggregate on left BHJ leg and HashAggregate on right BHJ leg,
- WSCG blocks are missed on left BHJ leg, 
- AQEShuffleRead node is missed on left BHJ leg.

**DAG before fix:**
DAG when AQE=ON and AQECachedDFSupport=ON without fix

**DAG after fix:**
DAG when AQE=ON and AQECachedDFSupport=ON with fix

### Does this PR introduce _any_ user-facing change?

Currently, Spark UI does not show final DAG when `spark.sql.optimizer.canChangeCachedPlanOutputPartitioning = true` so this causes some physical operators metrics as missed. This PR aims to fix this problem.

### How was this patch tested?

Specific UT Coverage will be added (In Progress).

### CODE REVIEW

**Comment by erenavsarogullari** [comment]
cc @cloud-fan @Ngone51

**Comment by cloud-fan** [comment]
is this still a problem after https://github.com/apache/spark/pull/38558 ?

**Comment by ulysses-you** [comment]
The reason is, the `AdaptiveSparkPlanExec` inside `InMemoryTableScanExec` does not register a new execution id in `SQLExecution`. Then when it materializes, `AdaptiveSparkPlanExec.getExecutionId` can not find the corresponding QueryExecution.
https://github.com/apache/spark/blob/0ae82d99d13988086a297920d45a766115a70578/sql/core/src/main/scala/org/apache/spark/sql/execution/adaptive/AdaptiveSparkPlanExec.scala#L221-L226

A simple example like:
```
          ...
           |
  AdaptiveSparkPlanExec (queryexecution 0, no execution id)
           |
  InMemoryTableScanExec
           |
          ...
           |
  AdaptiveSparkPlanExec (queryexecution 1, execution id 0)
```

**Comment by ulysses-you** [comment]
>i s this still a problem after https://github.com/apache/spark/pull/38558 ?

@cloud-fan oh just see it. it not related

**Comment by cloud-fan** [comment]
after https://github.com/apache/spark/pull/38558 , I think only the first cache access will miss the metrics?

**Comment by ulysses-you** [comment]
There is another issue.. before doing a new action, we will reset the metrics. This issue is not about AQE, that means even we disable AQE for cache plan, we still can not get valid metrics after first access.

**Pull request closed without merging**
