### PR TITLE
[SPARK-8130] - Made spark.files.useFetchCache off by default

### PR DESCRIPTION
**Pull request by piganesh**

### CODE REVIEW

**Comment by piganesh** [comment]
Made spark.files.useFetchCache off by default

**Comment by JoshRosen** [comment]
We also need to update the documentation in `docs/configuration.md` to reflect this change (and should also grep to see whether it needs to be modified anywhere else).

**Comment by andrewor14** [comment]
ok to test

**Comment by andrewor14** [comment]
FYI @lianhuiwang

**Comment by andrewor14** [comment]
@JoshRosen and I discussed this offline. So apparently this feature has been broken for a long time. Since recently, each Spark executor actually gets its own unique directory so a shared cache doesn't even make sense anymore. The proposal is just to remove this feature since it (1) doesn't work, (2) is very complex, and (3) there is no way to fix it given the fundamental executor temp dir constraints.

**Comment by andrewor14** [comment]
Update: I don't think we should change the default behavior without better understanding of how this feature works. The first step would be to write tests and update the documentation (SPARK-8716). Then we can decide whether or not we actually want this feature.

For this reason I have closed SPARK-8130. @piganesh would you mind closing this patch? Thanks for your work.

**Pull request closed without merging**
