### PR TITLE
[SPARK-13950] [SQL] generate code for sort merge left/right outer join

### PR DESCRIPTION
**Pull request by davies**
## What changes were proposed in this pull request?

This PR generate the code for sort merge left/right outer join (full outer join is too complicated, could be done in separate PR).
## How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by davies** [comment]
Since I did not see any speedup in benchmark, i'd like to close this one. We could re-visit this if the sorting getting faster. cc @rxin

**Comment by rxin** [comment]
Do you have breakdown on the time spent in sorting vs join?

**Comment by hvanhovell** [comment]
Is this worth revisiting once https://github.com/apache/spark/pull/12490 gets in?

**Comment by davies** [comment]
@hvanhovell Will revisit this once that get in.

**Comment by davies** [comment]
Even with radix sort (faster than TimSort for integer key), the improvement from codegen version still small (below 10%), I'd close this PR.

**Pull request closed without merging**
