### PR TITLE
[SPARK-27405][SQL][TEST] Restrict the range of generated random timestamps

### PR DESCRIPTION
**Pull request by MaxGekk**
## What changes were proposed in this pull request?

In the PR, I propose to restrict the range of random timestamp literals generated in `LiteralGenerator. timestampLiteralGen`. The generator creates instances of `java.sql.Timestamp` by passing milliseconds since epoch as `Long` type. Converting the milliseconds to microseconds can cause arithmetic overflow of Long type because Catalyst's Timestamp type stores microseconds since epoch in `Long` type internally as well. Proposed interval of random milliseconds is `[Long.MinValue / 1000, Long.MaxValue / 1000]`.

For example, generated timestamp `new java.sql.Timestamp(-3948373668011580000)` causes `Long` overflow at the method:
```scala
  def fromJavaTimestamp(t: Timestamp): SQLTimestamp = {
  ...
      MILLISECONDS.toMicros(t.getTime()) + NANOSECONDS.toMicros(t.getNanos()) % NANOS_PER_MICROS
  ...
  }
```
because `t.getTime()` returns `-3948373668011580000` which is multiplied by `1000` at `MILLISECONDS.toMicros`, and the result `-3948373668011580000000` is less than `Long.MinValue`.

## How was this patch tested?

By `DateExpressionsSuite` in the PR https://github.com/apache/spark/pull/24311

### CODE REVIEW

**Comment by MaxGekk** [comment]
@dongjoon-hyun @srowen Please, take a look at the PR.

**Comment by dongjoon-hyun** [comment]
Thank you for splitting this, @MaxGekk !

**Comment by dongjoon-hyun** [comment]
Could you add a concrete example in the PR description for the following, too?
> Converting the milliseconds to microseconds can cause arithmetic overflow of Long type because Catalyst's Timestamp type stores microseconds since epoch in Long type internally as well.

**Comment by MaxGekk** [comment]
jenkins, retest this, please

**Comment by MaxGekk** [comment]
> BTW, this PR is not tested ... because this reduces the range of generated data.
> By DateExpressionsSuite in the PR #24311

I would agree the PR is not tested by an explicit test but what would you like to test? I think we can trust to ScalaCheck's  `Gen.choose` that it returns longs in the range `[Long.MinValue / 1000, Long.MaxValue / 1000]`. There is theoretical foundation that generated milliseconds out of the range cause Long arithmetic overflow, so, the range cannot be wider. What should the test proof?

**Review by srowen — APPROVED** [review]
This seems OK to me. I think the point is that Arbitrary is going to pick values that aren't valid for this test? The range changes then as a fix, and we can see that tests pass before and after. What else?

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Merged to master.
The updated document is correct and enough. What I want is to make it explicit in the PR description, @MaxGekk .

Thank you, @MaxGekk and @srowen .

**Pull request closed without merging**
