### PR TITLE
[SPARK-9726] [Python] PySpark DF join no longer accepts on=None

### PR DESCRIPTION
**Pull request by btashton**
@rxin 

First pull request for Spark so let me know if I am missing anything
The contribution is my original work and I license the work to the project under the project's open source license.

### CODE REVIEW

**Comment by rxin** [comment]
Thanks - do you think you can add a test case in python/pyspark/sql/tests.py for this?

**Comment by rxin** [comment]
Jenkins, ok to test.

**Comment by davies** [comment]
LGTM, thanks to working on this!

**Comment by btashton** [comment]
I will add a test today or tomorrow around this.  It does not look like there are any tests for joins on pyspark right now,

**Comment by btashton** [comment]
Still need to add tests, but it looks like this failed on the pyspark.mllib tests not anything to do with pyspark.sql

**Comment by marmbrus** [comment]
I'm going to merge this so that we can have the fix in the 1.5 preview.  Please do add the test still in a follow up pr!

Thanks!

**Pull request closed without merging**
