### PR TITLE
[SPARK-7744] [Docs] [MLlib] "Distributed matrix" section in MLlib "Data Types" documentation should be reordered.

### PR DESCRIPTION
**Pull request by dusenberrymw**
The documentation for BlockMatrix should come after RowMatrix, IndexedRowMatrix, and CoordinateMatrix, as BlockMatrix references the later three types, and RowMatrix is considered the "basic" distributed matrix.  This will improve comprehensibility of the "Distributed matrix" section, especially for the new reader.

### CODE REVIEW

**Comment by mengxr** [comment]
Just to confirm. Are there any other changes in this PR rather than moving the entire block?

**Comment by dusenberrymw** [comment]
No, the only change is moving the BlockMatrix section to the bottom.

**Comment by mengxr** [comment]
ok to test

**Comment by mengxr** [comment]
LGTM. Waiting for Jenkins.

**Comment by mengxr** [comment]
Merged into master, branch-1.4, and branch-1.3. Thanks!

**Comment by dusenberrymw** [comment]
Awesome, thanks @mengxr!

**Pull request closed without merging**
