### PR TITLE
[SPARK-30465][Core]bytesToString util adapts to negative number

### PR DESCRIPTION
**Pull request by sddyljsx**
### What changes were proposed in this pull request?
bytesToString util adapts to negative number

### Why are the changes needed?
when the input of bytesToString is negative number, the string returned  is unfriendly.
For Example:
-5368709120 will return -5368709120B, not -5.0 GiB

### Does this PR introduce any user-facing change?
No

### How was this patch tested?
The UT has been added in UtilsSuite

### CODE REVIEW

**Review by Ngone51 — COMMENTED** [review]
When do we have negative bytes?

BTW, does  positive `5368709120B` returns `5.0 GiB`?

**Comment by sddyljsx** [comment]
> When do we have negative bytes?
In some case, the number is negative. I am trying to find the reason, but as a common tool, it should adapt to this case.
remaining memory

> BTW, does positive `5368709120B` returns `5.0 GiB`?
yes, it is.
5 * 1024 * 1024 * 1024 = 5368709120

**Comment by Ngone51** [comment]
@sddyljsx thanks for providing the snapshot. I feel negative bytes may caused by mistakenly computing of memory or overflow. I think it's better to find out the root cause of negative bytes while improving formats for negative bytes doesn't make sense to me.

**Comment by sddyljsx** [comment]
> @sddyljsx thanks for providing the snapshot. I feel negative bytes may caused by mistakenly computing of memory or overflow. I think it's better to find out the root cause of negative bytes while improving formats for negative bytes doesn't make sense to me.

It is very necessary to to find out the root cause. I am working on this these days and a new PR will be added. But I think improving formats for negative bytes also makes sense.  It's just a general function and no one stipulates that the input of this function cannot be negative.

**Comment by srowen** [comment]
The case you cite is either a bug, or simply that someone forgot to flip a negative sign or something. I do not think in general there's a situation where negative bytes is useful to display

**Comment by dongjoon-hyun** [comment]
I also agree with the above comments. I'll close this PR. Thank you, @sddyljsx and all.

**Pull request closed without merging**
