### PR TITLE
[SPARK-16497][SQL] Don't throw an exception if drop non-existent TABLE/VIEW/Function/Partitions

### PR DESCRIPTION
**Pull request by lianhuiwang**
## What changes were proposed in this pull request?

from https://cwiki.apache.org/confluence/display/Hive/Configuration+Properties#ConfigurationProperties-hive.exec.drop.ignorenonexistent, Hive use 'hive.exec.drop.ignorenonexistent'(default=true) to do not report an error if DROP TABLE/VIEW/PARTITION/INDEX/TEMPORARY FUNCTION specifies a non-existent table/view. So SparkSQL also should support it.
## How was this patch tested?

add unit tests.

### CODE REVIEW

**Comment by hvanhovell** [comment]
This is by design; we throw exceptions for all invalid commands. Why should we follow Hive here?

See for more context: https://github.com/apache/spark/pull/13307 & https://github.com/apache/spark/pull/13302

**Comment by lianhuiwang** [comment]
@hvanhovell I cannot find why Hive support it from https://issues.apache.org/jira/browse/HIVE-1856.
But now many Spark users have used Hive before, So that make some previous these queries failed. How about set spark.sql.drop.ignorenonexistent=false? If you think this PR is unnecessary, I will close it. thank. btw: I find that presto/impala/mysql will throw a exception for it.

**Comment by hvanhovell** [comment]
@lianhuiwang I don't think this necessary. Could you close it? Thanks for working on it!

**Comment by lianhuiwang** [comment]
OK, I close it. Thanks.

**Pull request closed without merging**
