### PR TITLE
[SPARK-19589][SQL] Removal of SQLGEN files

### PR DESCRIPTION
**Pull request by gatorsmile**
### What changes were proposed in this pull request?
SQLGen is removed. Thus, the generated files should be removed too.

### How was this patch tested?
N/A

### CODE REVIEW

**Comment by gatorsmile** [comment]
cc @hvanhovell @jiangxb1987

**Comment by jiangxb1987** [comment]
Thank you for doing this, this looks good to me.

**Comment by hvanhovell** [comment]
LGTM

**Comment by hvanhovell** [comment]
Merging to master. Thanks!

**Pull request closed without merging**
