### PR TITLE
[SPARK-47701][SQL][TESTS] Postgres: Add test for Composite and Range types

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

Add tests for Composite and Range types of postgres.

### Why are the changes needed?

test improvments

### Does this PR introduce _any_ user-facing change?

no, test-only

### How was this patch tested?

new tests

### Was this patch authored or co-authored using generative AI tooling?
no

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM (Pending CIs).

**Comment by yaooqinn** [comment]
Thank you @dongjoon-hyun, I further added tests for Range types to reduce # of small PRs

**Review by dongjoon-hyun — APPROVED** [review]
Thank you for adding that.

**Comment by dongjoon-hyun** [comment]
Merged to master for Apache Spark 4.0.0.

**Pull request closed without merging**
