### PR TITLE
[SPARK-11523][SQL] Throw AnalysisException for Spark UDFs if using Hive to handle CREATE VIEW

### PR DESCRIPTION
**Pull request by viirya**
JIRA: https://issues.apache.org/jira/browse/SPARK-11523

When `spark.sql.nativeView = false` (default value), we use Hive native command to handle `CREATE VIEW`. If there are Spark UDFs, users will see `org.apache.hadoop.hive.ql.parse.SemanticException`. We should throw an AnalysisException for that.

### CODE REVIEW

**Comment by viirya** [comment]
retest this please.

**Comment by viirya** [comment]
Looks like we don't have good way to know if a function is Spark-only or not. I will close this PR first.

**Comment by viirya** [comment]
retest this please.

**Comment by viirya** [comment]
ping @liancheng

**Comment by liancheng** [comment]
@cloud-fan Would you mind to have a look at this one?

**Comment by yhuai** [comment]
What's the stacktrace thrown from hive?

**Comment by yhuai** [comment]
So, the problem is that when we define a view using Spark SQL UDF, Hive tries to validate that UDF is a Hive one and then throw an exception?

**Comment by viirya** [comment]
Yes. If we use a Spark UDF in CREATE VIEW executed by Hive, Hive will throw exception. I think we should throw our exception in advance and provide related information.

**Comment by cloud-fan** [comment]
I'm thinking about if it worth to do this. Finally we will only create native view, and the changes in this PR looks hacky to me.

cc @marmbrus

**Comment by viirya** [comment]
Actually we already have native view, but it is configurable (`spark.sql.nativeView`, default value is false). Without showing this information, the users may not know what happens when they use Spark UDFs in CREATE VIEW (e.g. the reported case in this JIRA).

**Comment by cloud-fan** [comment]
it's configurable because it's uncomplete... I mean we will improve it and only allow native view at that point.

**Comment by viirya** [comment]
Yes. I think the question is should we add this before the native view is completely ready.

**Comment by rxin** [comment]
It will be ready in the next release, so I think it is ok to not have this now.

**Comment by viirya** [comment]
Got it. Close it now.

**Pull request closed without merging**
