### PR TITLE
[SPARK-8808][SPARKR] Fix assignments in SparkR.

### PR DESCRIPTION
**Pull request by sun-rui**

### CODE REVIEW

**Comment by yu-iskw** [comment]
@sun-rui great work! Could you show us the result of `lint-r`?

**Comment by shivaram** [comment]
Thanks @sun-rui LGTM.

**Comment by shivaram** [comment]
@sun-rui -- I just ran `dev/lint-r` and it looks like there are a few more places where we need to fix assignment. Pasting the list below

```
cat dev/lint-r-report.log | grep "assignment" -A 1
inst/tests/test_binary_function.R:79:12: style: Use <-, not =, for assignment.
  mockFile = c("Spark is pretty.", "Spark is awesome.")
--
inst/tests/test_binaryFile.R:23:10: style: Use <-, not =, for assignment.
mockFile = c("Spark is pretty.", "Spark is awesome.")
--
inst/tests/test_rdd.R:450:12: style: Use <-, not =, for assignment.
  mockFile = c("Spark is pretty.", "Spark is awesome.")
--
inst/tests/test_rdd.R:486:12: style: Use <-, not =, for assignment.
  mockFile = c("Spark is pretty.", "Spark is awesome.")
--
inst/tests/test_textFile.R:23:10: style: Use <-, not =, for assignment.
mockFile = c("Spark is pretty.", "Spark is awesome.")
--
inst/tests/test_utils.R:122:5: style: Use <-, not =, for assignment.
  t = 4  # Override base::t in .GlobalEnv.
--
R/client.R:39:24: style: Use <-, not =, for assignment.
    sparkSubmitBinName = "spark-submit"
--
R/client.R:41:24: style: Use <-, not =, for assignment.
    sparkSubmitBinName = "spark-submit.cmd"
--
R/DataFrame.R:1331:35: style: Use <-, not =, for assignment.
                options[['path']] = path
--
R/group.R:90:18: style: Use <-, not =, for assignment.
            cols = list(...)
--
R/group.R:100:31: style: Use <-, not =, for assignment.
                    cols[[n]] = alias(cols[[n]], n)
--
R/utils.R:44:26: style: Use <-, not =, for assignment.
                keyBytes = callJMethod(obj, "_1")
--
R/utils.R:45:26: style: Use <-, not =, for assignment.
                valBytes = callJMethod(obj, "_2")
````

**Comment by sun-rui** [comment]
OK. I will clean them together

**Comment by sun-rui** [comment]
All reported issues of such kind are cleaned.

**Comment by shivaram** [comment]
LGTM. Merging this

**Pull request closed without merging**
