### PR TITLE
[SPARK-4707][STREAMING] Reliable Kafka Receiver can lose data if the blo...

### PR DESCRIPTION
**Pull request by harishreedharan**
...ck generator fails to store data.

The Reliable Kafka Receiver commits offsets only when events are actually stored, which ensures that on restart we will actually start where we left off. But if the failure happens in the store() call, and the block generator reports an error the receiver does not do anything and will continue reading from the current offset and not the last commit. This means that messages between the last commit and the current offset will be lost.

This PR retries the store call four times and then stops the receiver with an error message and the last exception that was received from the store.

### CODE REVIEW

**Comment by harishreedharan** [comment]
@tdas Any comments on this one, or is this one ready to go in?

**Comment by jerryshao** [comment]
Hi @harishreedharan , After carefully looking at the code, I think data will not be lost even in such failure situation. For example, if we meet exception in `onPushBlock` which is called in `BlockGenerator#keepPushingBlocks`, this function will catch the exception and call `reportError` to notify the exception, After that the thread of `blockPushingThread` is exited. So there's no chance to call `onPushBlock` again, in another words, `storeBlockAndCommitOffset` will not be called again, so offset will not be committed to ZK from the failure point.

And the receiving thread will keep getting data and pushed into `blockForPushing` until it is full, after that, the whole receiver system is blocked.

**Comment by jerryshao** [comment]
So I think the aim of this patch is to fix the recoverable problems of data store with retries, not prevent data loss. That's my thought, sorry for my misunderstanding.

**Comment by harishreedharan** [comment]
No, this does prevent data loss - basically if the store fails multiple times, we shutdown the receiver completely. So the new receiver which gets started starts from the last commit, so we are safe.

**Comment by tdas** [comment]
ok to test.

**Comment by tdas** [comment]
@harishreedharan This begs a higher level questions of whether the write ahead log (which is the probably component to fail) should have its own retries independent of the receiver retrying.

**Comment by tdas** [comment]
I can merge this for now and we can focus on that issue later.

**Comment by harishreedharan** [comment]
Agreed. I will file a jira. We should discuss the issue there. This one was more of a break-fix, but that would be a more elaborate fix.

**Pull request closed without merging**
