### PR TITLE
[SPARK-45525][SQL][PYTHON] Support for Python data source write using DSv2

### PR DESCRIPTION
**Pull request by allisonwang-db**
### What changes were proposed in this pull request?

This PR adds initial support for Python data source write by implementing the DSv2 `SupportsWrite` interface for `PythonTableProvider`.

Note this PR only supports the `def write(self, iterator)` API. `commit` and `abort` will be supported in [SPARK-45914](https://issues.apache.org/jira/browse/SPARK-45914).

### Why are the changes needed?

To support Python data source APIs. For instance:

```python
class SimpleWriter(DataSourceWriter):
    def write(self, iterator: Iterator[Row]) -> WriterCommitMessage:
        for row in iterator:
            print(row)
        return WriterCommitMessage()

class SimpleDataSource(DataSource):
    def writer(self, schema, overwrite):
        return SimpleWriter()

# Regsiter the Python data source
spark.dataSource.register(SimpleDataSource)

df.range(10).write.format("SimpleDataSource").mode("append").save()
```

### Does this PR introduce _any_ user-facing change?

Yes, this PR supports writing data into a Python data source.

### How was this patch tested?

New unit tests

### Was this patch authored or co-authored using generative AI tooling?

No

### CODE REVIEW

**Comment by allisonwang-db** [comment]
@cloud-fan @HyukjinKwon @ueshin This PR is ready for review. It focuses on the optimizer/execution part of data source write and is independent of the DataFrameWriter.

**Review by ueshin — APPROVED** [review]
Although I see some `TODO`s, LGTM as an initial support.

**Comment by allisonwang-db** [comment]
cc @HyukjinKwon @cloud-fan

**Review by HyukjinKwon — APPROVED** [review]
Looks good from a cursory look. Would be great to have Wenchen's look too.

**Review by cloud-fan — APPROVED** [review]

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Pull request closed without merging**
