### PR TITLE
[SPARK-36512][UI][TESTS] Fix UISeleniumSuite in sql/hive-thriftserver

### PR DESCRIPTION
**Pull request by sarutak**
### What changes were proposed in this pull request?

This PR fixes an issue that `UISeleniumSuite` in `sql/hive-thriftserver` doesn't work even though the ignored test is enabled due to the following two reasons.

(1) The suite waits for thriftserver starting up by reading a startup message from stdin but the expected message is never read.
(2) The URL and CSS selector for test are wrong.

To resolve (1), this PR adopt the way that `HiveThriftServer2Suite` does.
https://github.com/apache/spark/blob/3f8ec0dae4ddfd7ee55370dad5d44d03a9f10387/sql/hive-thriftserver/src/test/scala/org/apache/spark/sql/hive/thriftserver/HiveThriftServer2Suites.scala#L1222-L1248

This PR also enables the ignored test. Let's disable it again in the following PR if it's still flaky.

### Why are the changes needed?

Bug fix.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

CIs.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @gengliangwang FYI

**Comment by sarutak** [comment]
cc: @dongjoon-hyun too.

**Comment by gengliangwang** [comment]
@sarutak sorry for the late reply. It seems that the test is ignored. Shall we enable it in this PR?

**Comment by sarutak** [comment]
@gengliangwang Thank you for the reply. The reason the test was ignored seems flakiness (#6345).
But it's 6 years ago and now it's difficult to know how flaky the test was.
How about enabling the ignored test and disable again if it's still flaky?

**Comment by gengliangwang** [comment]
If we are not going to enable it, it doesn't make sense to fix it...
Let's see how the CI test behaves. I tried on my local setup and the test passes.

**Review by gengliangwang — APPROVED** [review]

**Comment by gengliangwang** [comment]
Thanks, merging to master

**Pull request closed without merging**
