### PR TITLE
[SPARK-6544][build] Increment Avro version from 1.7.6 to 1.7.7

### PR DESCRIPTION
**Pull request by deanchen**
Fixes bug causing Kryo serialization to fail with Avro files in between stages. 

https://issues.apache.org/jira/browse/AVRO-1476?focusedCommentId=13999249&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13999249

### CODE REVIEW

**Comment by srowen** [comment]
We should probably sync this to the underlying Hadoop version. However I know this already doesn't match it and I suspect that bumping a maintenance release won't hurt. If you have a moment would be good to see which version of Hadoop uses this or else what if any incompatible changes may exist. I call it out since I had some issues with older Avro releases in the past.

**Comment by deanchen** [comment]
Here are the 3 issues resolved in 1.7.7 compared to 1.7.6

https://issues.apache.org/jira/browse/AVRO/fixforversion/12326041/?selectedTab=com.atlassian.jira.jira-projects-plugin:version-summary-panel

[AVRO-1632](https://issues.apache.org/jira/browse/AVRO-1632) - is marked as not a problem so there was no code change
[AVRO-1439](https://issues.apache.org/jira/browse/AVRO-1439) - looks like a new API so it is new code as opposed to modification of existing code
[AVRO-1476](https://issues.apache.org/jira/browse/AVRO-1476) - is the issue causing the GenericRecord problem and the motivation behind the version upgrade

So it looks like a low risk change.


The Hadoop MR client doesn't appear to specify the avro package version so it should be on 1.7.7 since Avro 1.7.7 was released on 07/23/2014.

https://github.com/apache/hadoop/blob/3c9181722b05a9192f5440ea8f3f77231f84eac6/hadoop-mapreduce-project/hadoop-mapreduce-client/pom.xml

**Comment by srowen** [comment]
Yeah I think it's pretty safe, LGTM.

**Comment by pwendell** [comment]
Yeah LGTM - I think bumping maintenance releases like this has usually been fine for us with Avro. It may be best not merge this into 1.3 though, since we typically keep dependencies fixed in patch releases.

**Comment by srowen** [comment]
ok to test

**Comment by deanchen** [comment]
@pwendell this is a blocker for any jobs using Avro and Kryo that passes GenericData.Records between stages so I think you should consider merging it in to 1.3 so it will be available in the next patch release. The other change from Avro 1.7.6 to 1.7.7 is just a new API so should be very low risk.

**Comment by pwendell** [comment]
It's a fair point - in some cases we have made minor (patch) release updates in our own patch versions. @srowen what do you think? It can cause some friction for packagers if dependencies change in these patch releases, but this upgrade may be alright.

**Comment by pwendell** [comment]
Okay after reviewing the changes to Avro I've decided to backport this. I looked a bit more and in other cases we have done fairly small dependency updates like this provided the changes in the dependency have been minimal between versions.

**Comment by deanchen** [comment]
Thanks!

**Pull request closed without merging**
