### PR TITLE
[SPARK-6321] [SQL] Adapt the number of partitions used by the Exchange rule to the cluster specifications

### PR DESCRIPTION
**Pull request by opuertas**

### CODE REVIEW

**Comment by srowen** [comment]
(Add `[SQL]` to the title please)

**Comment by srowen** [comment]
ok to test

**Comment by marmbrus** [comment]
Hey @ojkar, thanks for working on this.  I'd love to have better support for automatically setting the numbers of partitions.  However, I'm hesitant to do it based on cluster size.  Specifically, I'm worried that existing jobs that run on a small cluster, but with lots of data, might start OOMing where they did not before.  Instead, I think this needs to be controlled by a conf (perhaps when `spark.sql.shuffle.partitions` is set to `auto`), and have it based on the # of input partitions.  What do you think?

**Comment by marmbrus** [comment]
In the meantime, to keep the PR queue at a manageable size, I propose we close this issue until its passing tests.

**Pull request closed without merging**
