### PR TITLE
[SPARK-30468][SQL] Use multiple lines to display data columns for show create table command

### PR DESCRIPTION
**Pull request by wzhfy**
### What changes were proposed in this pull request?
Currently data columns are displayed in one line for show create table command, when the table has many columns (to make things even worse, columns may have long names or comments), the displayed result is really hard to read.

To improve readability, we print each column in a separate line. Note that other systems like Hive/MySQL also display in this way.

Also, for data columns, table properties and options, we put the right parenthesis to the end of the last column/property/option, instead of occupying a separate line.

### Why are the changes needed?
for better readability

### Does this PR introduce any user-facing change?
before the change:
```
spark-sql> show create table test_table;
CREATE TABLE `test_table` (`col1` INT COMMENT 'This is comment for column 1', `col2` STRING COMMENT 'This is comment for column 2', `col3` DOUBLE COMMENT 'This is comment for column 3')
USING parquet
OPTIONS (
  `bar` '2',
  `foo` '1'
)
TBLPROPERTIES (
  'a' = 'x',
  'b' = 'y'
)
```
after the change:
```
spark-sql> show create table test_table;
CREATE TABLE `test_table` (
  `col1` INT COMMENT 'This is comment for column 1',
  `col2` STRING COMMENT 'This is comment for column 2',
  `col3` DOUBLE COMMENT 'This is comment for column 3')
USING parquet
OPTIONS (
  `bar` '2',
  `foo` '1')
TBLPROPERTIES (
  'a' = 'x',
  'b' = 'y')
```

### How was this patch tested?
modified existing tests

### CODE REVIEW

**Comment by srowen** [comment]
Probably fine. CC @gengliangwang

**Comment by wzhfy** [comment]
also cc @maropu

**Comment by maropu** [comment]
retest this please

**Review by maropu — APPROVED** [review]
Looks nice, thanks for the follow-up, @wzhfy ! cc: @dongjoon-hyun @HyukjinKwon

**Review by gengliangwang — APPROVED** [review]
LGTM

**Pull request closed without merging**
