### PR TITLE
[SPARK-19180][SQL] the offset of short should be 2 in OffHeapColumn

### PR DESCRIPTION
**Pull request by yucai**
## What changes were proposed in this pull request?

the offset of short is 4 in OffHeapColumnVector's putShorts, but actually it should be 2.

## How was this patch tested?

unit test

### CODE REVIEW

**Comment by yucai** [comment]
@chenghao-intel @adrian-wang kindly help review.

**Comment by aray** [comment]
The title should say 2.

**Comment by yucai** [comment]
Thanks @aray , good catch!

**Comment by yucai** [comment]
retest please.

**Comment by gatorsmile** [comment]
ok to test

**Comment by gatorsmile** [comment]
cc @sameeragarwal @davies @rxin

**Comment by gatorsmile** [comment]
retest this please

**Comment by davies** [comment]
lgtm, merging it into master, 2.1 and 2.0 branch.

**Comment by sameeragarwal** [comment]
Thanks @yucai!

**Pull request closed without merging**
