### PR TITLE
[SPARKR] [SPARK-11587] Fix the summary generic to match base R

### PR DESCRIPTION
**Pull request by shivaram**
The signature is summary(object, ...) as defined in
https://stat.ethz.ch/R-manual/R-devel/library/base/html/summary.html

### CODE REVIEW

**Comment by shivaram** [comment]
cc @mengxr @yanboliang @sun-rui

**Comment by sun-rui** [comment]
LGTM.

I just want to discuss a BKM here for all cases of such kind. That is we want to add in SparkR a function  which also an existing S3 geneirc function defined in R Base package.  There are two ways for use to add such function in SparkR:
1. Define an S4 generic function, which has compatible signature with the existing S3 generic function in Base package. Then use setMethod() to define the our own method for SparkR;
2. No need to define an S4 generic function. Just define a new S3 method  for the existing S3 generic function. For example, for this case, we could:
  summary.DataFrame <- ...

I am not sure which is better. I think we can have a discussion and find a preferred style. We can consistently use that style later.

**Comment by shivaram** [comment]
Yeah thats a good point. I mostly prefer (1) because it makes our code base only contain S4 functions. However we do end up with a risk of bugs like this one. I do like the idea you used to add a test for `rank` and I think we should add tests that check the base R function works wherever we have a conflict.

**Comment by shivaram** [comment]
Alright I'm merging this to catch 1.6. @sun-rui if we have more points to discuss, we can continue on the mailing list or JIRA.

**Pull request closed without merging**
