### PR TITLE
[SPARK-38544][BUILD] Upgrade log4j2 to 2.17.2

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr aims to upgrade log4j2 to 2.17.2.

### Why are the changes needed?
This version brings a lot of fixes released to log1.x support, the release notes and change report as follows:

- https://logging.apache.org/log4j/2.x/index.html#News
- https://logging.apache.org/log4j/2.x/changes-report.html#a2.17.2

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass GA

### CODE REVIEW

**Review by martin-g — APPROVED** [review]

**Review by yaooqinn — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @LuciferYang and all!
Merged to master for Apache Spark 3.3.

**Comment by LuciferYang** [comment]
thanks all

**Comment by LuciferYang** [comment]
@dongjoon-hyun @yaooqinn should revert this first? I haven't found the cause of the failure yet

**Comment by wangyum** [comment]
Reverted through https://github.com/apache/spark/commit/2a63fea139ec7e5d0883ccd5b33080bdad21e009

**Comment by LuciferYang** [comment]
thanks @wangyum

**Comment by dongjoon-hyun** [comment]
Thank you for reverting.

**Pull request closed without merging**
