### PR TITLE
Revert [SPARK-19355][SPARK-25352]

### PR DESCRIPTION
**Pull request by viirya**
## What changes were proposed in this pull request?

This goes to revert [SPARK-19355](https://github.com/apache/spark/pull/16677) and [SPARK-25352](https://github.com/apache/spark/pull/22344), based on some discussion and comments at https://github.com/apache/spark/pull/16677#issuecomment-422650759.

## How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by viirya** [comment]
cc @cloud-fan @rxin @hvanhovell

**Comment by HyukjinKwon** [comment]
@viirya, not a big deal but mind leaving few explicit discussion links (in the PRs you pointed out) to the current PR description?

**Comment by maropu** [comment]
I just put the link here: https://github.com/apache/spark/pull/16677#issuecomment-422650759

**Comment by viirya** [comment]
Thanks @HyukjinKwon @maropu. I've put it in the PR description.

**Comment by cloud-fan** [comment]
@viirya Thanks for doing it! To ease the review, can you revert these 4 commits sequentially with `git revert commit-hash`? Thanks!
https://github.com/apache/spark/pull/22344
https://github.com/apache/spark/pull/22330
https://github.com/apache/spark/pull/22239
https://github.com/apache/spark/pull/16677

**Comment by viirya** [comment]
@cloud-fan Ok. Let me try it.

**Comment by viirya** [comment]
@cloud-fan Shall we have 4 PRs to revert these PRs individually?

**Comment by cloud-fan** [comment]
just one PR including 4 commits

**Pull request closed without merging**
