### PR TITLE
[SPARK-14772][PYTHON][ML] Fixed Params.copy method to match Scala implementation

### PR DESCRIPTION
**Pull request by BryanCutler**
## What changes were proposed in this pull request?
Fixed the PySpark Params.copy method to behave like the Scala implementation.  The main issue was that it did not account for the _defaultParamMap and merged it into the explicitly created param map.

## How was this patch tested?
Added new unit test to verify the copy method behaves correctly for copying uid, explicitly created params, and default params.

### CODE REVIEW

**Comment by BryanCutler** [comment]
Ping @holdenk @jkbradley , please take a look when you get a chance - thanks!

**Comment by holdenk** [comment]
Let me try and take a look tomorrow - I'm in transit today.

**Comment by BryanCutler** [comment]
ping @holdenk - mind taking a look?

**Comment by jkbradley** [comment]
LGTM
Merging with master

@BryanCutler would you mind sending a backport PR against branch-2.1 to run Jenkins tests?

Thank you!

**Comment by jkbradley** [comment]
well...will merge after new tests

**Comment by jkbradley** [comment]
jenkins test this please

**Comment by jkbradley** [comment]
OK merging now.  @BryanCutler do let me know if you don't have time to send a backport--thanks!

**Comment by BryanCutler** [comment]
Thanks @jkbradley!  I'll do a backport later tonight

On Feb 23, 2017 6:09 PM, "asfgit" <notifications@github.com> wrote:

Closed #16772 <https://github.com/apache/spark/pull/16772> via 2f69e3f
<https://github.com/apache/spark/commit/2f69e3f60f27d4598f001a5454abc21f739120a6>
.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/apache/spark/pull/16772#event-975421332>, or mute the
thread

**Pull request closed without merging**
