### PR TITLE
update parquet version  1.11.1 and avro version 1.9.2

### PR DESCRIPTION
**Pull request by melin**
update parquet version  1.11.1 and avro version 1.9.2，iceberg rely on these versions

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
cc @sunchao

**Comment by srowen** [comment]
I think this has more implications for compatibility with other libraries.
There are already JIRAs for this.
You need to update the deps/ files too.

**Comment by gemelen** [comment]
@melin there is one more place to upgrade Avro dependency version, in project/plugins.sbt
Please, see https://github.com/apache/spark/blob/master/project/plugins.sbt#L37

**Comment by sunchao** [comment]
Sorry for the late reply. Yes @melin : there's ongoing effort on this. Please see #27609 and #26804 for details.

To make the migration smooth we'll also need to upgrade Hive because 2.3.7 is using an old Avro version with incompatible API usage against Avro 1.9+. Therefore we're fixing that in Hive branch-2.3 and plan to do a new release after that. The details is in https://issues.apache.org/jira/browse/HIVE-21737.

**Comment by dongjoon-hyun** [comment]
Thank you for making a PR, @melin . For now, I'll close this PR in favor of the prior approaches.

**Pull request closed without merging**
