### PR TITLE
[SPARK-44942][INFRA] Use Jira notification options to sync with Github

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

The dev/github_jira_sync.py does not work well these days, this PR tries to solve this issue by using a much more reliable service - https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features#Git.asf.yamlfeatures-Jiranotificationoptions

And maybe we can remove dev/github_jira_sync.py but I don't know where we run this script yet.
### Why are the changes needed?

for jira and github sync

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

Took a tour of a few Apache projects
 
### Was this patch authored or co-authored using generative AI tooling?

no

### CODE REVIEW

**Review by zhengruifeng — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by yaooqinn** [comment]
Just FYI, I have also created an ASF Infra ticket[1] to see the underlying problems with syncing. After the fixing, it's working functionally so far.

`dev/github_jira_sync.py` in our code repo might safe to be deleted.


[1] https://issues.apache.org/jira/browse/INFRA-24962

**Comment by dongjoon-hyun** [comment]
Thank you for checking and doing the follow-up.

+1 for deletion. Feel free to make a PR to delete it, @yaooqinn .

**Comment by yaooqinn** [comment]
thank you @dongjoon-hyun

**Pull request closed without merging**
