### PR TITLE
[SPARK-15509][Follow-up][ML][SparkR] R MLlib algorithms should support input columns "features" and "label"

### PR DESCRIPTION
**Pull request by yanboliang**
## What changes were proposed in this pull request?
#13584 resolved the issue of features and label columns conflict with `RFormula` default ones when loading libsvm data, but it still left some issues should be resolved:

1, It’s not necessary to check and rename label column.
Since we have considerations on the design of `RFormula`, it can handle the case of label column already exists(with restriction of the existing label column should be numeric/boolean type). So it’s not necessary to change the column name to avoid conflict. If the label column is not numeric/boolean type, `RFormula` will throw exception.

2, We should rename features column name to new one if there is conflict, but appending a random value is enough since it was used internally only. We done similar work when implementing `SQLTransformer`.

3, We should set correct new features column for the estimators. Take `GLM` as example:
`GLM` estimator should set features column with the changed one(rFormula.getFeaturesCol) rather than the default “features”. Although it’s same when training model, but it involves problems when predicting. The following is the prediction result of GLM before this PR:
image
We should drop the internal used feature column name, otherwise, it will appear on the prediction DataFrame which will confused users. And this behavior is same as other scenarios which does not exist column name conflict.
After this PR:
image
## How was this patch tested?

Existing unit tests.

### CODE REVIEW

**Comment by yanboliang** [comment]
cc @jkbradley @mengxr @shivaram @felixcheung @junyangq

**Comment by shivaram** [comment]
cc @keypointt

**Comment by keypointt** [comment]
Vote for appending a random_sequence, and I believe almost definitely no collision for this random_sequence

**Comment by yanboliang** [comment]
@keypointt Thanks for review. Then this should be go?

**Comment by keypointt** [comment]
hi @yanboliang it looks good to me but I don't have right to merge to master, maybe you have to ping the other reviewers :p

**Comment by felixcheung** [comment]
LGTM

**Comment by yanboliang** [comment]
Merged into master, thanks for all your review.

**Pull request closed without merging**
