### PR TITLE
[SPARK-45643][CORE][SQL] Replace `s.c.mutable.MapOps#transform` with `s.c.mutable.MapOps#mapValuesInPlace`

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr replace `s.c.mutable.MapOps#transform` with `s.c.mutable.MapOps#mapValuesInPlace` due to `transform` has been marked as deprecated since Scala 2.13.0.

```scala
  @deprecated("Use mapValuesInPlace instead", "2.13.0")
  @inline final def transform(f: (K, V) => V): this.type = mapValuesInPlace(f)
```

### Why are the changes needed?
Clean up deprecated API usage.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass GitHub Actions

### Was this patch authored or co-authored using generative AI tooling?
No

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM (Pending CIs)

**Comment by LuciferYang** [comment]
Thanks @dongjoon-hyun

**Review by beliefer — APPROVED** [review]
LGTM if tests passed.

**Comment by dongjoon-hyun** [comment]
Merged to master~

**Comment by LuciferYang** [comment]
Thanks @dongjoon-hyun and @beliefer

**Pull request closed without merging**
