### PR TITLE
[SPARK-11694][FOLLOW-UP] Clean up imports, use a common function for metadata and add a test for FIXED_LEN_BYTE_ARRAY

### PR DESCRIPTION
**Pull request by HyukjinKwon**
As discussed https://github.com/apache/spark/pull/9660 https://github.com/apache/spark/pull/9060, I cleaned up unused imports, added a test for fixed-length byte array and used a common function for writing metadata for Parquet.

For the test for fixed-length byte array, I have tested and checked the encoding types with [parquet-tools](https://github.com/Parquet/parquet-mr/tree/master/parquet-tools).

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
I will cc you @liancheng just so that you can easily find :).

**Comment by liancheng** [comment]
Thanks for cleaning this up! Merging to master.

**Comment by liancheng** [comment]
@HyukjinKwon This PR doesn't merge cleanly with branch-1.6. Would you please file another PR to backport this change to branch-1.6? Thanks!

**Comment by HyukjinKwon** [comment]
yes I will.

**Pull request closed without merging**
