### PR TITLE
[SPARK-5475][CORE] Java 8 tests are like maintenance overhead.

### PR DESCRIPTION
**Pull request by ScrapCodes**
Having tests that validate the same code compatible with java 8 and java 7 is like asserting that java 8 is backward compatible with java 7 and still supports java 8 features(lambda expressions to be precise). This was once necessary as asm was not compatible with java 8 and so on.

Running java8-tests on the current code base results in more than 100 compilation errors, it felt as if they are never run. This is based on the fact that compilation errors have existed for a pretty long period. So IMHO, we should really remove them, if we don't plan to maintain.

Thoughts?

### CODE REVIEW

**Comment by shaneknapp** [comment]
i will kick this off again once i restart jenkins.

**Comment by shaneknapp** [comment]
jenkins, test this please.

**Comment by srowen** [comment]
Please see the JIRA, I think this is a misunderstanding. These tests work and are not redundant with other Java API tests.

**Comment by rxin** [comment]
@ScrapCodes can we close this?

**Comment by ScrapCodes** [comment]
I can not get these tests to run, not sure if there is a way to run them that I do not know. Please see jira for related comment.

**Comment by srowen** [comment]
Let's close this PR. The Java 8 tests run if you enable the Java 8 profile and run with Java 8. The failure noted in the PR was unrelated.

**Pull request closed without merging**
