### PR TITLE
[SPARK-47130][CORE] Use listStatus to bypass block location info when cleaning driver logs

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

Use `listStatus` instead of `listLocatedStatus` to bypass block location info when cleaning driver logs.

### Why are the changes needed?

Reduce the loader of the file system

### Does this PR introduce _any_ user-facing change?

no
### How was this patch tested?

existing tests
### Was this patch authored or co-authored using generative AI tooling?
no

### CODE REVIEW

**Review by mridulm — APPROVED** [review]
Looks good to me, thanks for fixing this @yaooqinn !

**Comment by yaooqinn** [comment]
Thank you @mridulm, merged to master

**Review by dongjoon-hyun — COMMENTED** [review]
+1, late LGTM.

**Comment by yaooqinn** [comment]
Thank you @dongjoon-hyun

**Pull request closed without merging**
