### PR TITLE
[SPARK-41350][SQL][FOLLOWUP] Allow simple name access of join hidden columns after alias

### PR DESCRIPTION
**Pull request by cloud-fan**
### What changes were proposed in this pull request?

This is a followup of https://github.com/apache/spark/pull/38862 . https://github.com/apache/spark/pull/38862 only handles plan alias, but expression alias is missed. This PR fixes it.

### Why are the changes needed?

fix a regression

### Does this PR introduce _any_ user-facing change?

Yes, certain querys that failed with `UNRESOLVED_COLUMN` before this PR can work now.

### How was this patch tested?

new tests

### CODE REVIEW

**Comment by cloud-fan** [comment]
cc @viirya @MaxGekk

**Review by MaxGekk — APPROVED** [review]

**Review by viirya — APPROVED** [review]

**Comment by MaxGekk** [comment]
+1, LGTM. Merging to 3.3/master.
Thank you, @cloud-fan and @viirya for review.

**Comment by MaxGekk** [comment]
@cloud-fan This causes conflicts in branch-3.3. Please, open a separate PR if it is needed.

**Comment by cloud-fan** [comment]
3.3 PR created https://github.com/apache/spark/pull/39121

**Pull request closed without merging**
