### PR TITLE
[SPARK-43405][SQL] Remove useless `getRowFormatSQL`, `inputRowFormatSQL`, `outputRowFormatSQL` method

### PR DESCRIPTION
**Pull request by Hisoka-X**
### What changes were proposed in this pull request?

Remove useless code in class `ScriptInputOutputSchema`. Include `getRowFormatSQL`, `inputRowFormatSQL`, `outputRowFormatSQL` method. It unused when #16869

### Why are the changes needed?
Clear code.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Unnecessary.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @AngersZhuuuu

**Comment by AngersZhuuuu** [comment]
First, pls write a jira and assign this pr to jira ticket
These code is used to format sql from LogicalPlan, seems copied from Hive, ok to remove.

**Comment by Hisoka-X** [comment]
> First, pls write a jira and assign this pr to jira ticket These code is used to format sql from LogicalPlan, seems copied from Hive, ok to remove.

Ok, I create [SPARK-43405](https://issues.apache.org/jira/browse/SPARK-43405)

**Review by dongjoon-hyun — COMMENTED** [review]
This PR actually removes `inputRowFormatSQL` and `outputRowFormatSQL` method additionally.

1. Could you revise the PR title and description, @Hisoka-X ?
2. Do you happen to know when these methods become useless?

**Comment by Hisoka-X** [comment]
> 1. Could you revise the PR title and description, @Hisoka-X ?

Done

> 2. Do you happen to know when these methods become useless?

It unused when https://github.com/apache/spark/pull/16869 .

**Comment by dongjoon-hyun** [comment]
Thank you for the info, @Hisoka-X .

cc @jiangxb1987 and @hvanhovell from #16868

**Comment by hvanhovell** [comment]
@dongjoon-hyun that is looonnnnggg time ago :)

Let me take a look.

**Review by hvanhovell — APPROVED** [review]
LGTM

**Comment by hvanhovell** [comment]
Merging.

**Comment by dongjoon-hyun** [comment]
Thank you, @Hisoka-X and @hvanhovell . :)

**Pull request closed without merging**
