### PR TITLE
[SPARK-5722][SQL] fix for infer long type in python similar to Java long (master branch)

### PR DESCRIPTION
**Pull request by dondrake**
Corresponding fix for SPARK-5722 for the master (1.3) branch.  See Pull #4521 for 1.2 version.

### CODE REVIEW

**Comment by marmbrus** [comment]
ok to test

**Comment by marmbrus** [comment]
test this please

**Comment by davies** [comment]
@dondrake Would you mind to close this one?

**Comment by dondrake** [comment]
Closed as #4666 resolved this.

**Pull request closed without merging**
