### PR TITLE
[SPARK-20190]'/applications/[app-id]/jobs' in rest api,status should be [running|s…

### PR DESCRIPTION
**Pull request by guoxiaolongzte**
…ucceeded|failed|unknown]

## What changes were proposed in this pull request?

'/applications/[app-id]/jobs' in rest api.status should be'[running|succeeded|failed|unknown]'.
now status is '[complete|succeeded|failed]'.
but '/applications/[app-id]/jobs?status=complete' the server return 'HTTP ERROR 404'.
Added '?status=running' and '?status=unknown'.
code ：
public enum JobExecutionStatus {
RUNNING,
SUCCEEDED,
FAILED,
UNKNOWN;

## How was this patch tested?

 manual tests

Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Comment by guoxiaolongzte** [comment]
@srowen Help code review,thank you!

**Review by srowen — APPROVED** [review]

**Comment by guoxiaolongzte** [comment]
help merge  spark master@srowen

**Comment by srowen** [comment]
@guoxiaolongzte no need to ping nearly this frequently. We frequently leave changes open for comments for at least a few days. Ping if you have addressed all comments but haven't seen replies in over a week.

**Comment by srowen** [comment]
Merged to master/2.1

**Pull request closed without merging**
