### PR TITLE
[SPARK-36174][SQL] Support explain final plan in AQE

### PR DESCRIPTION
**Pull request by ulysses-you**
### What changes were proposed in this pull request?

Add a new grammar `EXPLAIN FINAL XXX` to explain final plan in AQE.

### Why are the changes needed?

The executed plan will be changed during running in AQE, however the current implementation of explain does not support this.

As the AQE is enabled by default, user may want to get the final plan using query, so it should make sense to add a new grammar to support it.

### Does this PR introduce _any_ user-facing change?

yes, new grammar.

### How was this patch tested?

add test.

### CODE REVIEW

**Comment by ulysses-you** [comment]
What do you think about this idea ? @maropu @cloud-fan @dongjoon-hyun @HyukjinKwon

**Review by dongjoon-hyun — COMMENTED** [review]
Hi, @ulysses-you . 
I understand the intention, but this is only useful for short queries, isn't it?
For big batch queries with hours or days execution time, it's infeasible for users to wait and see the executed plans.

**Comment by cloud-fan** [comment]
We should be very careful to invent new SQL syntaxes in Spark. Can you study this area and see what other systems are doing?

**Comment by cloud-fan** [comment]
And echo to @dongjoon-hyun 's opinion: I think EXPLAIN command doesn't fit AQE very well. We probably need a completely different way to track the AQE plan changes.

**Comment by ulysses-you** [comment]
thank you @dongjoon-hyun @cloud-fan @maropu , I agree the thought you pointed out. Close this now.

We can still do some discussion at this place if other people have good idea.

**Comment by dongjoon-hyun** [comment]
Thank you, @ulysses-you . Yep, I fully understand your needs.

**Comment by HyukjinKwon** [comment]
Yeah, I would avoid adding this for now either.

**Pull request closed without merging**
