### PR TITLE
Revert "Revert "[SPARK-26606][CORE] Handle driver options properly when submitting to standalone cluster mode via legacy Client""

### PR DESCRIPTION
**Pull request by HeartSaVioR**
This reverts commits 3fc626d874d0201ada8387a7e5806672c79cd6b3.

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
retest this, please

**Comment by HeartSaVioR** [comment]
Let's start with two concurrent builds. If they all fails for same reason I'll take a look.

**Comment by dongjoon-hyun** [comment]
Thank you, @HeartSaVioR !

**Comment by dongjoon-hyun** [comment]
Sorry, @vanzin and @HeartSaVioR . According to the latest Jenkins result, the old concurrent failures seems that some flaky environment issue instead of the patch.

**Comment by HeartSaVioR** [comment]
No problem! Could we revert the revert commit?

**Comment by dongjoon-hyun** [comment]
Yes, @HeartSaVioR .

**Comment by dongjoon-hyun** [comment]
Merged to `branch-2.4`.

Sorry for this trouble and thank you, @vanzin and @HeartSaVioR !

**Pull request closed without merging**
