### PR TITLE
[SPARK-38213][STREAMING] Adding KafkaSink Metrics feature

### PR DESCRIPTION
**Pull request by senthh**
### What changes were proposed in this pull request?

KafkaSink Metrics feature is added

### Why are the changes needed?

KafkaSink Metrics feature will be useful to collect and store the Spark application's metrics into Kafka topic.

### Does this PR introduce _any_ user-facing change?

Yes

### How was this patch tested?

Created test case
also tested manually in internal cluster too

### CODE REVIEW

**Comment by senthh** [comment]
@dongjoon-hyun @HyukjinKwon @cloud-fan Could you pls review this PR?

**Comment by senthh** [comment]
@wzhfy

**Comment by senthh** [comment]
@dgd-contributor @gaborgsomogyi @squito Could you pls review this PR?

**Comment by senthh** [comment]
@dongjoon-hyun Could you be kind to review this PR, Please?

**Comment by fhygh** [comment]
LGTM

**Comment by senthh** [comment]
@dongjoon-hyun @dgd-contributor @gaborgsomogyi @squito Could you be kind to review this PR, Please?

**Comment by senthh** [comment]
@dongjoon-hyun @dgd-contributor @gaborgsomogyi @squito Could you be kind to review this PR, Please?

**Comment by senthh** [comment]
@dongjoon-hyun @dgd-contributor @gaborgsomogyi @squito Could you be kind to review this PR, Please?

**Comment by senthh** [comment]
@jerryshao @dongjoon-hyun @HyukjinKwon Could you please review this PR?

**Pull request closed without merging**
