### PR TITLE
[CI] Run all linters even if some fail, unless install deps failed

### PR DESCRIPTION
**Pull request by EnricoMi**
### What changes were proposed in this pull request?
Currently, the GitHub Actions CI stops running linters if one fail. This makes it run all linters, even if some fail.

### Why are the changes needed?
For instance, changes in Java and Scala and Python may contain linter errors, which a single pass of the CI could highlight. Currently, all issues for Scala have to be fixed first, in order to see the Java errors.

### Does this PR introduce _any_ user-facing change?
Only CI changes.

### How was this patch tested?
No

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Hm, we're actually suffering from the lack of GA resources (one ASF org shares all GA resources). I would prefer to leave it as a failfast.

**Comment by EnricoMi** [comment]
Interesting point! For PRs from forks, these steps run in the context of the fork repository, so the GA resources do not count towards ASF org resources. With 05225dd, the fail-fast continues to apply to PRs from apache/spark but not from non-apache forks.

**Comment by Yikun** [comment]
@EnricoMi emm, I'm guessing you want to see all the lint questions by one GA job triggered? But the best practice is probably to execute `dev/lint-java` and `dev/lint-scala` in your local env before PR submitted, especially, when you have hitted the lint error before?

**Comment by EnricoMi** [comment]
You are right, best practice is to run those tests locally before pushing to git. But when this hasn't been practised and the actions are run any way, why not facing the author with all the issues. Just my suggestion of good practice for your CI.

**Comment by EnricoMi** [comment]
@HyukjinKwon @Yikun if you happen to change your mind, you know where to find this change.

**Pull request closed without merging**
