### PR TITLE
[SPARK-8511][pyspark] Modify a test to remove a saved model in `regression.py`

### PR DESCRIPTION
**Pull request by yu-iskw**
[[SPARK-8511] Modify a test to remove a saved model in `regression.py` - ASF JIRA](https://issues.apache.org/jira/browse/SPARK-8511)

### CODE REVIEW

**Comment by yu-iskw** [comment]
Jenkins, test this please.

**Comment by jkbradley** [comment]
This actually appears in even more places in MLlib.  Would you mind fixing those too with this JIRA/PR?  Thanks for catching this issue!

**Comment by yu-iskw** [comment]
@jkbradley sure! will do!

**Comment by yu-iskw** [comment]
Jenkins, test this please.

**Comment by jkbradley** [comment]
LGTM pending tests
Thanks!

**Comment by yu-iskw** [comment]
@jkbradley Thank you for reviewing it!

**Comment by jkbradley** [comment]
The tests passed, but posting here failed.  I'll merge with master and branch-1.4

**Comment by yu-iskw** [comment]
@jkbradley thank you for merging it!

**Pull request closed without merging**
