### PR TITLE
[SPARK-40189][SQL] Add `json_array_get` function

### PR DESCRIPTION
**Pull request by Hisoka-X**
### What changes were proposed in this pull request?
At the moment we do not have any function to get value of JSON array by use specified index.
I add a `json_array_get` function which will return the value of JSON array by use specified index.

- This function will return value of JSON array, if JSON array is valid.

```sql

select json_array_get('[{"a":123},{"b":"hello"}]', 1);

+--------------------------------------------+
|json_array_get([{"a":123},{"b":"hello"}], 1)|
+--------------------------------------------+
|                               {"b":"hello"}|
+--------------------------------------------+
```

- In case of any other valid JSON string, the specified index does not exist, invalid JSON string or null array or NULL input , NULL will be returned.

```sql

select json_array_get("[[1],[2,3],[]]", 4);

+---------------------------------+
|json_array_get([[1],[2,3],[]], 4)|
+---------------------------------+
|                             NULL|
+---------------------------------+
```

### Why are the changes needed?
- As mentioned in JIRA, this function is supported by presto
- For better user experience and ease of use.

### Does this PR introduce _any_ user-facing change?
Yes, now users can get value of a json array by using `json_array_get`.

### How was this patch tested?
Add new test

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
quick question, do you have any reference of this expression in other DBMSes?

**Comment by Hisoka-X** [comment]
> quick question, do you have any reference of this expression in other DBMSes?

Just presto. https://prestodb.io/docs/current/functions/json.html#json_array_get

**Comment by LuciferYang** [comment]
image

It seems that presto does not recommend using this function, and it may be removed in future presto version, so is it necessary for Spark to support it?

**Comment by Hisoka-X** [comment]
> image
> It seems that presto does not recommend using this function, and it may be removed in future presto version, so is it really necessary for Spark to support it?

The reason as presto say, the semantics of this function are broken. If we will not have the same issue, I think we can support it.

**Comment by Hisoka-X** [comment]
By the way, does Spark have any way to get json array value use specified index. This is a useful function, if we can achieve this requirement without this function, this function maybe unnecessary.

**Comment by Hisoka-X** [comment]
Seem like this function are unnecessary, I close the PR. Thanks @HyukjinKwon @LuciferYang @advancedxy

**Pull request closed without merging**
