### PR TITLE
[SPARK-44802][INFRA] Token based ASF JIRA authentication

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

This PR add a env JIRA_ACCESS_TOKEN for merge script to enable token auth

### Why are the changes needed?

Tokens are more secure and easily revoked or expired.

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

1. locally tested 

```python
>>> JIRA_ACCESS_TOKEN is not None
True
>>> asf_jira.issue("SPARK-44801")
<JIRA Issue: key='SPARK-44801', id='13547185'>
>>> if JIRA_ACCESS_TOKEN is not None:
...     asf_jira = jira.client.JIRA(jira_server, token_auth=JIRA_ACCESS_TOKEN)
... else:
...     asf_jira = jira.client.JIRA(
...         jira_server, basic_auth=(JIRA_USERNAME, JIRA_PASSWORD)
...     )
...
>>> asf_jira.issue("SPARK-44801")
<JIRA Issue: key='SPARK-44801', id='13547185'>
```

2. merged https://github.com/apache/spark/pull/42470 with this

### CODE REVIEW

**Comment by yaooqinn** [comment]
cc @cloud-fan @HyukjinKwon @dongjoon-hyun, thanks

**Review by HyukjinKwon — APPROVED** [review]

**Review by cloud-fan — APPROVED** [review]

**Comment by yaooqinn** [comment]
Thanks, merged to master

**Comment by dongjoon-hyun** [comment]
Hi, @yaooqinn and all. This PR seems to be a partial work. According to the code, it seems to be supposed to replace ID and PASSWD, but this doesn't work correctly in two places.

1. This fails at the last update stage because the rest of code requires JIRA_USERNAME **and** JIRA_PASSWORD still.
```
Would you like to pick afe18868 into another branch? (y/n): n
JIRA_USERNAME and JIRA_PASSWORD not set
Exiting without trying to close the associated JIRA.
```

2. This shows improper warning at the initial stage.
```
$ dev/merge_spark_pr.py
git rev-parse --abbrev-ref HEAD

The env-vars JIRA_USERNAME and/or JIRA_PASSWORD are not set. Continue? (y/n): y
Which pull request would you like to merge? (e.g. 34):
```

Could you double-check and make a follow-up? FYI, I test this in the AS-IS `master` branch by unsetting both JIRA_USERNAME and JIRA_PASSWORD completely and using JIRA_ACCESS_TOKEN only.

**Comment by dongjoon-hyun** [comment]
I made a quick fix. Please check this manually, @yaooqinn .
- https://github.com/apache/spark/pull/42502

**Pull request closed without merging**
