### PR TITLE
[MINOR][SQL][DOCS] Update `sql/README.md` and remove some unused imports in `sql` module.

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
## What changes were proposed in this pull request?

This PR updates `sql/README.md` according to the latest console output and removes some unused imports in `sql` module. This is done by manually, so there is no guarantee to remove all unused imports.
## How was this patch tested?

Manual.

### CODE REVIEW

**Comment by rxin** [comment]
LGTM pending Jenkins.

**Comment by dongjoon-hyun** [comment]
Thank you always. :)

**Comment by dongjoon-hyun** [comment]
Rebased.

**Comment by rxin** [comment]
Thanks - merging this in master.

**Comment by dongjoon-hyun** [comment]
Thank you for merging, @rxin .

**Pull request closed without merging**
