### PR TITLE
[SPARK-29284][SQL] Adaptive query execution works correct…

### PR DESCRIPTION
**Pull request by hn5092**
### What changes were proposed in this pull request?

```
spark.sql("SET spark.sql.adaptive.enabled=true")
spark.sql("SET spark.sql.shuffle.partitions=1")
val result = spark.range(0).distinct().count
or spark.table("empty table").distinct.count
```
throw java.util.NoSuchElementException: next on empty iterator

### Why are the changes needed?

Fix bug.

### Does this PR introduce any user-facing change?

No

### How was this patch tested?

Add UT :org.apache.spark.sql.execution.ExchangeCoordinatorSuite

### CODE REVIEW

**Comment by wangyum** [comment]
Thank you @hn5092 Please verify if the issue still exist in master branch.

**Comment by hn5092** [comment]
> Thank you @hn5092 Please verify if the issue still exist in master branch.

master not exist this issue

**Comment by wangyum** [comment]
OK. Thank you. Could we close this?

**Comment by hn5092** [comment]
2.4.x needn't fix this bug?

**Comment by HyukjinKwon** [comment]
@hn5092, please identify which PR fixed this, and see if it's feasible to backport.

**Comment by hn5092** [comment]
> @hn5092, please identify which PR fixed this, and see if it's feasible to backport.

The new AE fix this bug but we can't cherry-pick to branch 2.4

**Pull request closed without merging**
