### PR TITLE
[SPARK-9420][SQL] Move expressions in sql/core package to catalyst.

### PR DESCRIPTION
**Pull request by rxin**
Since catalyst package already depends on Spark core, we can move those expressions
into catalyst, and simplify function registry.

This is a followup of #7478.

### CODE REVIEW

**Comment by marmbrus** [comment]
LGTM

**Comment by rxin** [comment]
I also renamed spark__partition__id to spark_partition_id.

cc @JDrit

**Comment by JDrit** [comment]
The other function in the umbrella ticket was for `input_file_name()` in which @rxin has suggested to use a thread local variable in `SqlNewHadoopRDD`. That function could not be put in `FunctionRegistry` since it would need access to the SQL package right?

**Comment by rxin** [comment]
We can add the thread local variable in sql/core, and the expression itself in sql/catalyst? There is no build dependency for looking up thread local variables.

**Pull request closed without merging**
