### PR TITLE
[DON'T MERGE] CI

### PR DESCRIPTION
**Pull request by LuciferYang**

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
I filed a JIRA at https://issues.apache.org/jira/browse/SPARK-39959

**Comment by LuciferYang** [comment]
should not be associated with SPARK-39902, I tried to revert it but still fail

**Comment by LuciferYang** [comment]
https://github.com/LuciferYang/spark/runs/7645272948?check_suite_focus=true

**Comment by HyukjinKwon** [comment]
It's very likely a dependency problem from R doc generation

**Comment by Yikun** [comment]
FYI: https://github.com/apache/spark/pull/37399

**Pull request closed without merging**
