### PR TITLE
[SPARK-34019][WEBUI] Keep same quantiles of task summary between Web UI and restful API

### PR DESCRIPTION
**Pull request by AngersZhuuuu**
### What changes were proposed in this pull request?
We should keep same quantiles about task summary about Web UI and Restful API

The direct result of resuful API is not same with Web UI is confusing. We'd better to keep same.

### Why are the changes needed?
Keep same result between restful API and web ui

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Existed UI

### CODE REVIEW

**Comment by AngersZhuuuu** [comment]
ping @gengliangwang @sarutak 
found this when we discuss about https://github.com/apache/spark/pull/31001#discussion_r551530183
We should keep all consistent. also. cc @ron8hu

**Comment by AngersZhuuuu** [comment]
ping @squito @dongjoon-hyun @srowen @tgravescs since you have commit to this part.

**Comment by sarutak** [comment]
The UI for a stage shows `0,0`, `0.25`, `0.50`, `0.75` and `1.0` percentiles so it seems to be consistent.
https://github.com/apache/spark/blob/master/core/src/main/resources/org/apache/spark/ui/static/stagepage.js#L180

**Comment by AngersZhuuuu** [comment]
> The UI for a stage shows `0,0`, `0.25`, `0.50`, `0.75` and `1.0` percentiles so it seems to be consistent.
> https://github.com/apache/spark/blob/cc201545626ffe556682f45edc370ac6fe29e9df/core/src/main/resources/org/apache/spark/ui/static/stagepage.js#L180-L212

But restful is `0.05,0.25,0.5,0.75,0.95`

**Comment by sarutak** [comment]
> But restful is 0.05,0.25,0.5,0.75,0.95
Yes, I understand.
I mean the change seems reasonable to align to the UI.

**Comment by AngersZhuuuu** [comment]
> Yes, I understand.
> I mean the change seems reasonable to align to the UI.

Ur, you mean change UI to be consistent with RestFul API. Is there any discuss about why use  `0.05,0.25,0.5,0.75,0.95`

**Comment by sarutak** [comment]
I saw the [past PR](https://github.com/apache/spark/pull/5940) but I don't see the discussion.

**Comment by AngersZhuuuu** [comment]
> > Ur, you mean change UI to be consistent with RestFul API. Is there any discuss about why use 0.05,0.25,0.5,0.75,0.95?
> 
> No, I don't think it's necessary to change the UI. This change seems reasonable to conform to the UI.
> I saw the [past PR](https://github.com/apache/spark/pull/5940) but I don't see the discussion about the quantile.

Yea

**Comment by AngersZhuuuu** [comment]
retest this please

**Comment by srowen** [comment]
What does the UI look like before and after? what is in the REST API not in the UI?

**Comment by AngersZhuuuu** [comment]
> What does the UI look like before and after? what is in the REST API not in the UI?

The problem is :

1. In spark web ui task summary the quantiles is `0.0.0.25,0.5,0.75,1.0`
2. In restful API /applications/[app-id]/stages/[stage-id]/[stage-attempt-id]/taskSummary the quantiles is `0.05,0.25,0.5,0.75,1.0`

The result is not same, we'd better keep it consistent

For one APP running in our env, stage=4 & stageAttemptId=0 
We can see the scheduler delay. the value is not same.
Screen Shot 2021-01-08 at 10 03 21 PM
Screen Shot 2021-01-08 at 10 03 46 PM

**Comment by tgravescs** [comment]
those are just default values so the user can change what they request.  Normally I would agree that keeping the same makes sense. I tried to go back to see if there was a reason it was made this way but didn't see any comments on it.

One question is whether this is a breaking change because users that do this will now get a different result.  thoughts from others? Ideally it doesn't matter as they would check what the quantiles are but if they aren't it would be different results.

**Comment by AngersZhuuuu** [comment]
> those are just default values so the user can change what they request. Normally I would agree that keeping the same makes sense. I tried to go back to see if there was a reason it was made this way but didn't see any comments on it.
> 
> One question is whether this is a breaking change because users that do this will now get a different result. thoughts from others? Ideally it doesn't matter as they would check what the quantiles are but if they aren't it would be different results.

Yea, and default value is not show in [monitoring page](https://spark.apache.org/docs/3.0.0/monitoring.html) and user will see ui's quantiles in Web UI. They may think the are same. we need to add this default to monitoring page too.

**Comment by srowen** [comment]
I see, OK. Yes I agree the default should be consistent with the UI, but, it is a minor breaking change, I suppose. I wonder if it's worth it, or needs to wait until Spark 4. Open to dev@ if you like for visibility and comments.

**Comment by gengliangwang** [comment]
Though it's a minor breaking change, I think it makes more sense to be consistent with the UI and show Min/Max instead of 0.05/0.95 quantiles.

**Comment by AngersZhuuuu** [comment]
Seems got no reply from other dev, emmmm,  What should I do next？ ping @srowen @gengliangwang @sarutak @tgravescs

**Comment by tgravescs** [comment]
I'm more on the side of putting it into a 4.0 since it could break someone and if someone doesn't like it they just set what they want.

**Comment by AngersZhuuuu** [comment]
> I'm more on the side of putting it into a 4.0 since it could break someone and if someone doesn't like it they just set what they want.

Ok, wait for spark 4.0 release.

**Pull request closed without merging**
