### PR TITLE
[SQL][minor] remove duplicated resolveGetField and update comment

### PR DESCRIPTION
**Pull request by cloud-fan**
It's after https://github.com/apache/spark/pull/5189

### CODE REVIEW

**Comment by cloud-fan** [comment]
cc @marmbrus

**Comment by marmbrus** [comment]
ok to test

**Comment by marmbrus** [comment]
Thanks for reopening this.  Sorry for missing your PR against my branch.

**Comment by cloud-fan** [comment]
Hi @marmbrus , is it ready to go? Or should we create a companion object `GetField` and put `resolveGetField` into it?

**Comment by marmbrus** [comment]
Sorry for the delay.  I'm going to go ahead and merge so we don't forget to remove the duplication.  I do like the idea of putting this in an `object` instead.

**Comment by JoshRosen** [comment]
(bump to get Spark PRs to refresh this)

**Pull request closed without merging**
