### PR TITLE
[SPARK-10053] Export lapply and lapplyPartition from sparkR

### PR DESCRIPTION
**Pull request by reactormonk**

### CODE REVIEW

**Comment by sun-rui** [comment]
RDD API is deliberatly hidden in spark 1.4.  For discussion of exposing subset of RDD API and high level parallel computation API, please refer to https://issues.apache.org/jira/browse/SPARK-7264

**Comment by reactormonk** [comment]
This is part of the DataFrame API, not the RDD.

**Comment by sun-rui** [comment]
Yes, DataFrame API has lapply and lapplyPartition, but actually there are RDD-like API ,and its implementation is based on the corresponding RDD API after converting the DataFrame into an RDD. The RDD-like API of DataFrame and RDD API are both hidden now.

UDF of DataFrame API is to be supported. Does that meet your requirement?

**Comment by reactormonk** [comment]
I haven't found any documentation on how to write UDFs with R. https://issues.apache.org/jira/browse/SPARK-6817 tells me it's not going to happen anytime soon.

**Comment by sun-rui** [comment]
I think UDF() is important, hope it can be available in 1.6 release.

**Comment by JoshRosen** [comment]
@shivaram @rxin @marmbrus, I'm guessing that this is still "won't fix for now" as of 1.6?

**Comment by JoshRosen** [comment]
Hey @reactormonk, would you mind closing this PR for now? We can easily re-open / resubmit later. Thanks!

**Pull request closed without merging**
