### PR TITLE
[SPARK-16122][DOCS] application environment rest api

### PR DESCRIPTION
**Pull request by uncleGen**
## What changes were proposed in this pull request?

follow up pr of #16949.

## How was this patch tested?

jenkins

### CODE REVIEW

**Comment by uncleGen** [comment]
cc @srowen

**Comment by uncleGen** [comment]
cc @vanzin

**Comment by vanzin** [comment]
can you add the bug # for the original change in the title?

**Comment by uncleGen** [comment]
@vanzin done

**Comment by vanzin** [comment]
Thanks. Merging to master.

**Pull request closed without merging**
