### PR TITLE
[SPARK-45273][CORE][UI] Support for set the access host in http header

### PR DESCRIPTION
**Pull request by chenyu0513**
**What changes were proposed in this pull request?**
The PR supports to set the access host in http header.

**Why are the changes needed?**
It can avoid http head attack.

**Does this PR introduce any user-facing change?**
No

**How was this patch tested?**
add new test

**Was this patch authored or co-authored using generative AI tooling?**
No

### CODE REVIEW

**Comment by chenyu-opensource** [comment]
Please give me a review when you have time.@srowen 
Thank you so much.

**Comment by srowen** [comment]
I don't see any explanation of what this does or why it is useful

**Comment by beliefer** [comment]
@chenyu-opensource Please add more detail in description.

**Comment by chenyu-opensource** [comment]
> I don't see any explanation of what this does or why it is useful

I had submit a new commit for description.
This pr is  to solve the problem of request header attacks. We should add filtering logic to set access whitelist for request headers.

**Comment by srowen** [comment]
There is still no explanation of what problem this solves

**Comment by chenyu-opensource** [comment]
> There is still no explanation of what problem this solves

HTTP Host header attack is a network security vulnerability that utilizes the "Host" header in HTTP requests. The Host header in the HTTP protocol is used to identify the target server of the HTTP request, indicating which host name or IP address the client wants to access the web application.

If the server directly trusts the Host header without verifying its legitimacy, an attacker may use this controllable variable to inject the Host and manipulate the server's behavior.

This pr used a whitelist method to solve this problem.

**Comment by srowen** [comment]
What 'trusts' a host header in Spark? what happens if it's spoofed?
This is still not explaining the issue.

**Comment by chenyu-opensource** [comment]
> What 'trusts' a host header in Spark? what happens if it's spoofed? This is still not explaining the issue.

What I mean is that there are no restrictions on request headers in Spark itself, which means that the client can freely pass through the server, so attackers can use this variable parameter to attack.
This pr helps us that when setting the parameter 'host' in HTTP header request, we can verify this parameter instead of directly letting it pass.

**Comment by srowen** [comment]
Attack _what_?

**Comment by chenyu-opensource** [comment]
> Attack _what_?

It may cause the transmission of malicious code and It may cause cache pollution and password reset.
I have already used this method to solve this problem in the production environment, and after vulnerability scanning, the problem did not occur.

**Comment by srowen** [comment]
How does this arise? Use private@spark.apache.org if needed. I am not clear what attack you have in mind or whether it can affect spark, so, no this would not be useful unless there's an argument it solves something

**Pull request closed without merging**
