### PR TITLE
[SPARK-49080][SQL][TEST] Upgrade `mssql-jdbc` to 12.8.0.jre11 and MsSQLServer docker image tag to `2022-CU14-ubuntu-22.04`

### PR DESCRIPTION
**Pull request by wayneguow**
### What changes were proposed in this pull request?

This PR aims to upgrade `mssql-jdbc` to 12.8.0.jre11 and MySQLServer docker image to `mcr.microsoft.com/mssql/server:2022-CU14-ubuntu-22.04`.

### Why are the changes needed?

This is the latest stable version of `mssql-jdbc`,  related release notes:

https://github.com/microsoft/mssql-jdbc/releases/tag/v12.7.0
https://github.com/microsoft/mssql-jdbc/releases/tag/v12.7.1
https://github.com/microsoft/mssql-jdbc/releases/tag/v12.8.0

Some fixed issues:

- Fix to ensure metadata returned follows JDBC data type specs https://github.com/microsoft/mssql-jdbc/pull/2326
- Added token cache map to fix use of unintended auth token for subsequent connections https://github.com/microsoft/mssql-jdbc/pull/2341
- Clear prepared statement handle before reconnect https://github.com/microsoft/mssql-jdbc/pull/2364
- Reset socketTimeout to original value after a successful connection open https://github.com/microsoft/mssql-jdbc/pull/2355
- Clear prepared statement cache when resetting statement pool connection https://github.com/microsoft/mssql-jdbc/pull/2361
- Fixed ClassLoader leak of ActivityCorrelator ThreadLocal https://github.com/microsoft/mssql-jdbc/pull/2366

### Does this PR introduce _any_ user-facing change?

No.
### How was this patch tested?

Pass GA.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by wayneguow** [comment]
cc @LuciferYang

**Comment by yaooqinn** [comment]
Can we also update MsSQLServer to 2022-CU14-ubuntu-22.04？

**Comment by wayneguow** [comment]
> Can we also update MsSQLServer to 2022-CU14-ubuntu-22.04？

No problem, let me work on this.

**Comment by yaooqinn** [comment]
If you don't mind, we can also switch the docker registry from mcr to https://hub.docker.com/r/microsoft/mssql-server directly

**Comment by wayneguow** [comment]
> If you don't mind, we can also switch the docker registry from mcr to https://hub.docker.com/r/microsoft/mssql-server directly

Is this the part? `mcr.microsoft.com/mssql/server`
But it seems that this is already the link you gave https://hub.docker.com/r/microsoft/mssql-server? Or am I not getting what you mean?

https://github.com/apache/spark/blob/080e7eb0de06d49959f2f2b05a1f446adf12fadb/connector/docker-integration-tests/src/test/scala/org/apache/spark/sql/jdbc/v2/MsSqlServerNamespaceSuite.scala#L32

**Comment by yaooqinn** [comment]
You are right, I made a mistake

**Review by yaooqinn — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @wayneguow and @yaooqinn .
Merged to master.

**Pull request closed without merging**
