### PR TITLE
[SQL][DOC] updating doc for JSON source to link to jsonlines.org

### PR DESCRIPTION
**Pull request by felixcheung**
## What changes were proposed in this pull request?

API and programming guide doc changes for Scala, Python and R.
## How was this patch tested?

manual test

### CODE REVIEW

**Comment by felixcheung** [comment]
@marmbrus would you take a look? thanks

**Comment by HyukjinKwon** [comment]
Oh @felixcheung, I happened to look at this PR. Should we change the documentation in `DataStreamReader`[1] , the equivalent one[2] in  `streaming.py` the ones in `SQLContext`[3][4]?

[1]https://github.com/apache/spark/blob/bb1aaf28eca6d9ae9af664ac3ad35cafdfc01a3b/sql/core/src/main/scala/org/apache/spark/sql/streaming/DataStreamReader.scala#L137
[2]https://github.com/apache/spark/blob/7a531e3054f8d4820216ed379433559f57f571b8/python/pyspark/sql/streaming.py#L643
[3]https://github.com/apache/spark/blob/689de920056ae20fe203c2b6faf5b1462e8ea73c/sql/core/src/main/scala/org/apache/spark/sql/SQLContext.scala#L818
[4]https://github.com/apache/spark/blob/689de920056ae20fe203c2b6faf5b1462e8ea73c/sql/core/src/main/scala/org/apache/spark/sql/SQLContext.scala#L830

**Comment by felixcheung** [comment]
thanks, streaming are good ones. I'm not sure about changing the deprecated methods in SQLContext though.

**Comment by marmbrus** [comment]
I don't think we have to update deprecated methods.  This LGTM.

**Comment by felixcheung** [comment]
fixes the 2 streaming case too, thanks @marmbrus for the review

**Comment by felixcheung** [comment]
merged to master.

**Pull request closed without merging**
