### PR TITLE
[SPARK-7473][MLLIB] Add reservoir sample in RandomForest

### PR DESCRIPTION
**Pull request by aihex**
reservoir feature sample by using existing api

### CODE REVIEW

**Comment by jkbradley** [comment]
LGTM pending tests.  I just made a JIRA for this.  Can you please add it to the PR title? [https://issues.apache.org/jira/browse/SPARK-7473]

**Comment by jkbradley** [comment]
ok to test

**Comment by jkbradley** [comment]
Oops, I should have realized you need to pass in a random seed.  Could you please update that?

**Comment by AiHe** [comment]
Seems like SamplingUtils.reservoirSampleAndCount has a default value for the seed. I don't think that's the reason for the failure.

**Comment by jkbradley** [comment]
That seed is set to a new random number on each call, so you'll use a different seed every time you run RandomForest.  Please pass a seed to reservoirSampleAndCount, where you generate that seed via rng.nextLong.

**Comment by AiHe** [comment]
Yes, you are right. That's why two tree are not identical in the test. Thank you.

**Comment by AiHe** [comment]
@jkbradley Please test it. Thank you.

**Comment by jkbradley** [comment]
@AiHe You need to pass it a new seed created by rng.nextLong.  Please see my comment above.

**Comment by jkbradley** [comment]
(Otherwise, the same will not change between iterations.  You create a new seed using rng so that, overall, the algorithm is deterministic based on the initial seed.)

**Comment by jkbradley** [comment]
@AiHe Thanks!  That should fix it.  LGTM pending tests

**Comment by jkbradley** [comment]
@AiHe RandomForestSuite's test "alternating categorical and continuous features with multiclass labels to test indexing" failed.  It looks like it's not robust and should not really be testing the accuracy.  Could you please remove the failing line?
```
EnsembleTestHelper.validateClassifier(model, arr, 1.0)
```
Thanks!

**Comment by AiHe** [comment]
@jkbradley Thanks for pointing out. Yes, the case seems not that helpful. Removed that out already.

**Comment by jkbradley** [comment]
LGTM merging into master and branch-1.4
Thanks!

**Comment by jkbradley** [comment]
@AiHe  Can you please ping me on the JIRA with your username so I can assign it to you?

**Pull request closed without merging**
