### PR TITLE
[SPARK-46393][SQL][FOLLOWUP] Classify exceptions in JDBCTableCatalog.loadTable

### PR DESCRIPTION
**Pull request by cloud-fan**
### What changes were proposed in this pull request?

This is a followup of https://github.com/apache/spark/pull/44335 , which missed to handle `loadTable`

### Why are the changes needed?

better error message

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

existing test

### Was this patch authored or co-authored using generative AI tooling?

no

### CODE REVIEW

**Comment by cloud-fan** [comment]
cc @MaxGekk @yaooqinn

**Review by yaooqinn — APPROVED** [review]

**Comment by yaooqinn** [comment]
Thank you
Merged to master

**Comment by panbingkun** [comment]
@cloud-fan @yaooqinn 
It seems that some `UTs` have failed, as follows:
https://github.com/panbingkun/spark/actions/runs/9411155017/job/25926739251
image
image

I have submitted a PR attempt to fix it: https://github.com/apache/spark/pull/46912

**Comment by yaooqinn** [comment]
Oops, My bad, can you cherry-pick 82b4ad2af64845503604da70ff02748c3969c991 into your new PR? I just reverted this to recover the CI

**Comment by panbingkun** [comment]
> Oops, My bad, can you cherry-pick [82b4ad2](https://github.com/apache/spark/commit/82b4ad2af64845503604da70ff02748c3969c991) into your new PR? I just reverted this to recover the CI

Okay, let me to do it.

**Pull request closed without merging**
