### PR TITLE
[SPARK-22757][K8S] Enable spark.jars and spark.files in KUBERNETES mode

### PR DESCRIPTION
**Pull request by liyinan926**
## What changes were proposed in this pull request?

We missed enabling `spark.files` and `spark.jars` in https://github.com/apache/spark/pull/19954. The result is that remote dependencies specified through `spark.files` or `spark.jars` are not included in the list of remote dependencies to be downloaded by the init-container. This PR fixes it.
 
## How was this patch tested?

Manual tests.

@vanzin Can you help review? Thanks!

@foxish

### CODE REVIEW

**Comment by vanzin** [comment]
Looks good pending tests.

**Comment by foxish** [comment]
LGTM, thanks!

**Comment by vanzin** [comment]
Please open the PR against master.

**Comment by liyinan926** [comment]
@vanzin created https://github.com/apache/spark/pull/20160. Closing this one.

**Pull request closed without merging**
