### PR TITLE
[SPARK-9304] [BUILD] Improve backwards compatibility of SPARK-8401

### PR DESCRIPTION
**Pull request by srowen**
Add back change-version-to-X.sh scripts, as wrappers for new script, for backwards compatibility

### CODE REVIEW

**Comment by pwendell** [comment]
Thanks Sean, looks good. We can also have it print a deprecation warning directing users to the new script.

**Comment by mallman** [comment]
Thanks for the fix @srowen. It was my oversight to assume it was safe to remove these scripts in the first place.

**Comment by srowen** [comment]
Nah, my bad if anything since I suggested it. Yes I'll add warnings to the wrappers.

**Comment by pwendell** [comment]
LGTM - no problem @mallman, it's not something that's well documented as a public API, but it did break a few things downstream to remove these scripts, so if we can keep them cheaply for compatibility purposes, we should do it.

**Comment by srowen** [comment]
(What broke though? I saw https://amplab.cs.berkeley.edu/jenkins/job/Spark-Master-Scala211-Compile/ but it shows no errors)

**Pull request closed without merging**
