### PR TITLE
[SPARK-40303][DOCS] Deprecate old Java 8 versions prior to 8u362

### PR DESCRIPTION
**Pull request by wangyum**
### What changes were proposed in this pull request?

This PR aims to deprecate old Java 8 versions prior to 8u362. 

### Why are the changes needed?

8u362 fixed a performance issue: https://github.com/openjdk/jdk8u-dev/pull/161

Benchmark code:
```scala
val dir = "/tmp/spark/benchmark"
val N = 2000000
val columns = Range(0, 100).map(i => s"id % $i AS id$i")

spark.range(N).selectExpr(columns: _*).write.mode("Overwrite").parquet(dir)

val cnt = 60
val selectExps = columns.take(cnt).map(_.split(" ").last).map(c => s"count(distinct $c)")
val start = System.currentTimeMillis()
spark.read.parquet(dir).selectExpr(selectExps: _*).collect()
println(s"Benchmark result. Java version: ${System.getProperty("java.version")}. Time(ms): ${System.currentTimeMillis() - start}")
```

8u352 benchmark result:
```shell
export JAVA_HOME=/Users/yumwang/Downloads/zulu8.66.0.15-ca-jdk8.0.352-macosx_x64
export PATH=${JAVA_HOME}/bin:${PATH}

bin/spark-shell  --master "local[2]" -i benchmark.scala
Benchmark result. Java version: 1.8.0_352. Time(ms): 641155
```

8u362 benchmark result:
```shell
export JAVA_HOME=/Users/yumwang/Downloads/zulu8.68.0.19-ca-jdk8.0.362-macosx_x64
export PATH=${JAVA_HOME}/bin:${PATH}

bin/spark-shell  --master "local[2]" -i benchmark.scala
Benchmark result. Java version: 1.8.0_362. Time(ms): 79360
```

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

N/A.

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Shall we simply deprecate, @wangyum ?
```
- Java 8 prior to version 8u201 support is deprecated as of Spark 3.2.0.
+ Java 8 prior to version 8u362 support is deprecated as of Spark 3.4.0.
```

**Comment by dongjoon-hyun** [comment]
Oh, is `Zulu` only have that released version, @wangyum ?
- https://bugs.openjdk.org/browse/JDK-8296506

I cannot find docker image and Adoptium (Temurin) Java yet.
- https://hub.docker.com/_/openjdk/tags?page=1&name=8u

**Comment by wangyum** [comment]
> Oh, does `Zulu` only have that released version, @wangyum ?
> 
> * https://bugs.openjdk.org/browse/JDK-8296506
> 
> I cannot find docker image and Adoptium (Temurin) Java yet.
> 
> * https://hub.docker.com/_/openjdk/tags?page=1&name=8u
> * https://adoptium.net/temurin/archive/?version=8

It is in progress:
image

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM for Apache Spark 3.4.0.

cc @srowen , @HyukjinKwon , @xinrong-meng , @LuciferYang

**Review by LuciferYang — APPROVED** [review]
+1, LGTM, thanks @wangyum

**Review by HyukjinKwon — APPROVED** [review]

**Comment by LuciferYang** [comment]
One problem is that GA is still using Temurin 8u352 for build and test. We need to wait for a while before running GA tasks using 8u362.

**Comment by LuciferYang** [comment]
Could you use 8u362 to run full UTs offline to check compatibility? Thanks ~ @wangyum

**Comment by dongjoon-hyun** [comment]
To @LuciferYang , I don't think this is a compatibility or any failure.

**Comment by LuciferYang** [comment]
@dongjoon-hyun Hmm...do you remember SPARK-40846? When we upgrade from 8u345 to 8u352 for GA testing, there are some time zone issue that need to be solved by changing the code, so I am not sure whether it is the right time to directly recommend a Java version without GA verification in the document. But maybe I'm too conservative.

**Comment by dongjoon-hyun** [comment]
Timezone issues are inevitably which we need to adjust the code in a regular basis, @LuciferYang .

**Comment by dongjoon-hyun** [comment]
BTW, we didn't cut the branch yet and we still have one month for Apache Spark 3.4.0 release. I'm considering that time period for this decision, @LuciferYang . You are also correct and being conservative is better if we don't have a room like that.

**Comment by LuciferYang** [comment]
Ok, plenty of time. I am fine to make this change

**Comment by dongjoon-hyun** [comment]
Now, both Zulu and Adoptiun(Temurin) are available. Thank you all. Merged to master.
Screenshot 2023-01-20 at 9 02 42 AM

**Comment by dongjoon-hyun** [comment]
FYI, GitHub Action is currently on the old version but `jdk8u362` will be automatically applied in one or two weeks. I'll keep monitoring the version change.

Screenshot 2023-01-20 at 9 28 23 AM

**Pull request closed without merging**
