### PR TITLE
[SPARK-11205] [PYSPARK] Match the output of DataFrame#explain() in both scala api and python

### PR DESCRIPTION
**Pull request by zjffdu**
…rint in python

No test needed. Verify it manually in pyspark shell

### CODE REVIEW

**Comment by JoshRosen** [comment]
While I agree that it would be nice to have both outputs match, I'm not sure that this is the right way to do it. After your change, the output is being printed by a separate process, breaking the tests and possibly breaking this feature for certain environments where the Py4J Gateway JVM's stdout / stderr isn't captured or display.

If you still want to fix this, can you come up with an approach which prints the header in Python or otherwise harmonizes the output without changing which process performs the printing?

**Comment by rxin** [comment]
I think this would break a lot of things, including output redirection in Python.

**Comment by rxin** [comment]
@zjffdu mind closing this pull request?

**Comment by zjffdu** [comment]
@rxin  I will make a new commit soon to match the output in python and scala. Should be a trivial change.

**Comment by rxin** [comment]
Can you show the before and after changes?

**Comment by JoshRosen** [comment]
@rxin, I believe that the doctest itself reflects the before/after.

**Comment by rxin** [comment]
Thanks - I've merged this.

**Comment by zjffdu** [comment]
Sorry, @rxin forget to change the title.

**Pull request closed without merging**
