### PR TITLE
[Minor] [SparkR] Update data-manipulation.R to use native csv reader

### PR DESCRIPTION
**Pull request by yanboliang**
## What changes were proposed in this pull request?
- Since Spark has supported native csv reader, it does not necessary to use the third party `spark-csv` in `examples/src/main/r/data-manipulation.R`. Meanwhile, remove all `spark-csv` usage in SparkR.
- Running R applications through `sparkR` is not supported as of Spark 2.0, so we change to use `./bin/spark-submit` to run the example.
## How was this patch tested?

Offline test.

### CODE REVIEW

**Comment by yanboliang** [comment]
cc @shivaram @davies @srowen

**Comment by srowen** [comment]
There are more refs to spark-csv in the R docs -- looks like they too can be removed?

**Comment by yanboliang** [comment]
@srowen Removed all refs to ```spark-csv``` in SparkR related code and docs.

**Comment by davies** [comment]
LGTM, merging into master and 1.0.

**Pull request closed without merging**
