### PR TITLE
[SPARK-35966][SQL] Port HIVE-17952: Fix license headers to avoid dangling javadoc warnings

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

Port HIVE-17952: Fix license headers to avoid dangling javadoc warnings

### Why are the changes needed?

Fix license headers 

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

pass rat check

### CODE REVIEW

**Review by wangyum — APPROVED** [review]

**Review by LuciferYang — APPROVED** [review]

**Comment by yaooqinn** [comment]
thank you all for the review, merged to master

**Comment by dongjoon-hyun** [comment]
Hi, @yaooqinn .
Did you use `dev/merge_spark_pr.py`? The merge script help you clean up the PR description.
- https://github.com/apache/spark/commit/6699f76fe2afa7f154b4ba424f3fe048fcee46df

**Comment by dongjoon-hyun** [comment]
cc @gengliangwang

**Comment by gengliangwang** [comment]
+1, late LGTM!

**Comment by dongjoon-hyun** [comment]
@yaooqinn According to your message, you entered `33169` which is invalid. You should input `y` or `n`.
> Would you like to use the modified body? (y/n): 33169

**Comment by yaooqinn** [comment]
oooops, my bad. I will be more careful from now on.

**Comment by dongjoon-hyun** [comment]
No problem at all, @yaooqinn ~ :)

**Pull request closed without merging**
