### PR TITLE
[SPARK-34408][PYTHON] Refactor spark.udf.register to share the same path to generate UDF instance

### PR DESCRIPTION
**Pull request by HyukjinKwon**
### What changes were proposed in this pull request?

This PR proposes to use `_create_udf` where we need to create `UserDefinedFunction` to maintain codes easier.

### Why are the changes needed?

For the better readability of codes and maintenance. 

### Does this PR introduce _any_ user-facing change?

No, refactoring.

### How was this patch tested?

Ran the existing unittests. CI in this PR should test it out too.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @ueshin @viirya can you take a quick look please?

**Review by ueshin — APPROVED** [review]
LGTM.

**Comment by HyukjinKwon** [comment]
Thanks @ueshin. Merged to master.

**Review by viirya — COMMENTED** [review]
late lgtm

**Pull request closed without merging**
