### PR TITLE
 [SPARK-30312][SQL][FOLLOWUP] Rename conf by adding `.enabled`

### PR DESCRIPTION
**Pull request by viirya**
### What changes were proposed in this pull request?

Based on the [comment](https://github.com/apache/spark/pull/26956#discussion_r366680558), this patch changes the SQL config name from `spark.sql.truncateTable.ignorePermissionAcl` to `spark.sql.truncateTable.ignorePermissionAcl.enabled`.

### Why are the changes needed?

Make this config consistent other SQL configs.

### Does this PR introduce any user-facing change?

No.

### How was this patch tested?

Unit test.

### CODE REVIEW

**Comment by viirya** [comment]
cc @dongjoon-hyun @gatorsmile

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by viirya** [comment]
@dongjoon-hyun Do you have some comment on this change? If not, I will merge this.

**Comment by viirya** [comment]
@dongjoon-hyun I found you cut v2.4.5-rc1 already. If this goes into master/2.4, then you need to cut rc2?

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @viirya and @HyukjinKwon .
Merged to master/2.4.

Yes. I'm planning to cut RC2 on next Monday.

**Pull request closed without merging**
