### PR TITLE
[SPARK-2205] [SPARK-7871] [SPARK-9372] [SQL] [WIP] Improving SQL query planner

### PR DESCRIPTION
**Pull request by yhuai**
This PR introduces three improvements to SQL planner..

First, it adds an optimization rule `FilterNullsInJoinKey` to add `Filter` before join operators to filter out rows having null values for join keys.

Second, it adds `NullUnsafeClusteredDistribution` and `NullUnsafeHashPartitioning`, which can be used to distribute rows having null values for join keys evenly. `NullUnsafeClusteredDistribution` is basically the same with `ClusteredDistribution` (now renamed to `NullSafeClusteredDistribution`) except that it does not require rows having null values for join keys be clustered.

Third, it adds `PartitioningCollection`, which is used to represent the `outputPartitioning` for `SparkPlan`s with multiple children (e.g. `ShuffledHashJoin`). So, a `SparkPlan` can have multiple descriptions of its partitioning schemes. Taking `ShuffledHashJoin` as an example, it has two descriptions of its partitioning schemes, i.e. `left.outputPartitioning` and `right.outputPartitioning`. So when we have a query like `select * from t1 join t2 on (t1.x = t2.x) join t3 on (t2.x = t3.x)` will only have three Exchange operators (when shuffled joins are needed) instead of four.

Optimizations in the first and second improvement are guarded by `spark.sql.advancedOptimization`.

I will add more comments/doc and test later.

### CODE REVIEW

**Comment by JoshRosen** [comment]
@yhuai, do you think that we should carve this up into multiple PRs to ease reviews?  It looks like `FilterNullsInJoinKey` should be easy to split out.

**Comment by yhuai** [comment]
@JoshRosen yeah. Let me split it.

**Comment by yhuai** [comment]
btw, `FilterNullsInJoinKeySuite` is not deterministic. I will change it later.

**Comment by yhuai** [comment]
I am closing it.

**Pull request closed without merging**
