### PR TITLE
[SPARK-40793][SQL] Fix the LogicalRelation computeStats for Row-level Runtime Filtering cannot be applied

### PR DESCRIPTION
**Pull request by chenminghua8**
### What changes were proposed in this pull request?

This RP modifies the "computeStats" method of the "LogicalRelation" class: when the external table does not perform pre-analysis to generate statistics, it calculates the space size of the HDFS file corresponding to the table as the return value and uses this value to update the external table Statistics's sizeInBytes value for lazy calculation of external table statistics. This solves the problem that Row-level Runtime Filtering cannot be applied when the external table does not have pre-performed analysis to generate statistics.

### Why are the changes needed?

When using external tables, Row-level Runtime Filtering cannot be applied without pre-performing analysis on the table to generate statistics. In actual use, external tables usually do not have pre-executed analysis to generate statistics, but it is also hoped that Row-level Runtime Filtering can be used to improve execution efficiency. The reason why Row-level Runtime Filtering cannot be enabled is that the "InjectRuntimeFilter" class calls the "satisfyByteSizeRequirement" method to determine whether the Bloom filter application side plan's aggregated scan size meets the requirements, and this value is finally calculated by the "computeStats" method of the "LogicalRelation" class. The current implementation of the 'computeStats' method first determines whether there is statistics in the external table, and if not, returns the value of 'spark.sql.defaultSizeInBytes', which results in that the calculated value returned when no pre-analysis is performed on the table to generate statistics cannot be satisfied Requirements for applying Row-level Runtime Filtering.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

New unit tests.

### CODE REVIEW

**Comment by chenminghua8** [comment]
[SPARK-40793](https://issues.apache.org/jira/browse/SPARK-40793) is the JIRA  for this PR.

**Comment by HyukjinKwon** [comment]
@chenminghua8 mind linking the JIRA ticket into the PR title? See also https://spark.apache.org/contributing.html

**Comment by chenminghua8** [comment]
> @chenminghua8 mind linking the JIRA ticket into the PR title? See also https://spark.apache.org/contributing.html
@HyukjinKwon Thank you! but I don't know how to get the JIRA ticket. can you tell me how to get it?

**Comment by HyukjinKwon** [comment]
e.g., `[SPARK-40793][SQL] Fix the LogicalRelation computeStats for Row-level Runtime Filtering cannot be applied `

**Comment by chenminghua8** [comment]
> e.g., `[SPARK-40793][SQL] Fix the LogicalRelation computeStats for Row-level Runtime Filtering cannot be applied `
@HyukjinKwon I have linked the JIRA ticket into the PR title. thanks!

**Comment by chenminghua8** [comment]
Added assert that external table statistics were updated in tests.

**Pull request closed without merging**
