### PR TITLE
[SPARK-46069][SQL][FOLLOWUP] Simplify the algorithm and add comments

### PR DESCRIPTION
**Pull request by cloud-fan**
### What changes were proposed in this pull request?

This is a followup of https://github.com/apache/spark/pull/43982, to simplify the algorithm without the "add one day" operation. This makes the algorithm easier to document.

### Why are the changes needed?

code simplication.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

updated tests

### Was this patch authored or co-authored using generative AI tooling?

no

### CODE REVIEW

**Comment by cloud-fan** [comment]
cc @wankunde @wangyum

**Review by dongjoon-hyun — COMMENTED** [review]
Thank you for simplifying and adding comments. Could you provide your CI link or re-trigger CI, @cloud-fan ?

**Comment by wankunde** [comment]
LGTM

**Comment by cloud-fan** [comment]
thanks for review, merging to master!

**Pull request closed without merging**
