### PR TITLE
[SPARK-29152][CORE]Executor Plugin shutdown when dynamic allocation is enabled

### PR DESCRIPTION
**Pull request by iRakson**
### What changes were proposed in this pull request?
Added `shutdownHook` for shutdown method of executor plugin. This will ensure that shutdown method will be called always.

### Why are the changes needed?
Whenever executors are not going down gracefully, i.e getting killed due to idle time or getting killed forcefully, shutdown method of executors plugin is not getting called. Shutdown method can be used to release any resources that plugin has acquired during its initialisation. So its important to make sure that every time a executor goes down shutdown method of plugin gets called. 

### Does this PR introduce any user-facing change?
No.

### How was this patch tested?

Tested Manually.

### CODE REVIEW

**Comment by iRakson** [comment]
cc @vanzin

**Comment by vanzin** [comment]
ok to test

**Comment by iRakson** [comment]
`org.apache.spark.rdd.AsyncRDDActionsSuite.async failure handling` passes when i run it locally.

**Comment by iRakson** [comment]
retest this please

**Comment by vanzin** [comment]
retest this please

**Comment by vanzin** [comment]
retest this please

**Comment by vanzin** [comment]
Merging to master. This will not merge cleanly to 2.4, so open a separate PR if you want the backport.

**Pull request closed without merging**
