### PR TITLE
[SPARK-8236][SQL] misc functions: crc32

### PR DESCRIPTION
**Pull request by qiansl127**
https://issues.apache.org/jira/browse/SPARK-8236

### CODE REVIEW

**Comment by qiansl127** [comment]
@davies Hi, could your help to check this PR?

**Comment by JoshRosen** [comment]
Jenkins, this is ok to test.

**Comment by JoshRosen** [comment]
Ah, looks like this _just_ conflicted with #7109, which renames ExpectsInputTypes => AutoCastInputTypes.

**Comment by qiansl127** [comment]
retest this please

**Comment by chenghao-intel** [comment]
seems unrelated failure.

**Comment by davies** [comment]
LGTM

**Pull request closed without merging**
