### PR TITLE
[SPARK-9021][PySpark] Change RDD.aggregate() to do reduce(mapPartitions()) instead of mapPartitions.fold()

### PR DESCRIPTION
**Pull request by shanghaiclown**
I'm relatively new to Spark and functional programming, so forgive me if this pull request is just a result of my misunderstanding of how Spark should be used.

Currently, if one happens to use a mutable object as `zeroValue` for `RDD.aggregate()`, possibly unexpected behavior can occur.

This is because pyspark's current implementation of `RDD.aggregate()` does not serialize or make a copy of `zeroValue` before handing it off to `RDD.mapPartitions(...).fold(...)`. This results in a single reference to `zeroValue` being used for both `RDD.mapPartitions()` and `RDD.fold()` on each partition. This can result in strange accumulator values being fed into each partition's call to `RDD.fold()`, as the `zeroValue` may have been changed in-place during the `RDD.mapPartitions()` call.

As an illustrative example, submit the following to `spark-submit`:

```
from pyspark import SparkConf, SparkContext
import collections

def updateCounter(acc, val):
    print 'update acc:', acc
    print 'update val:', val
    acc[val] += 1
    return acc

def comboCounter(acc1, acc2):
    print 'combo acc1:', acc1
    print 'combo acc2:', acc2
    acc1.update(acc2)
    return acc1

def main():
    conf = SparkConf().setMaster("local").setAppName("Aggregate with Counter")
    sc = SparkContext(conf = conf)

    print '======= AGGREGATING with ONE PARTITION ======='
    print sc.parallelize(range(1,10), 1).aggregate(collections.Counter(), updateCounter, comboCounter)

    print '======= AGGREGATING with TWO PARTITIONS ======='
    print sc.parallelize(range(1,10), 2).aggregate(collections.Counter(), updateCounter, comboCounter)

if __name__ == "__main__":
    main()
```

One probably expects this to output the following:

```
Counter({1: 1, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1, 7: 1, 8: 1, 9: 1})
```

But it instead outputs this (regardless of the number of partitions):

```
Counter({1: 2, 2: 2, 3: 2, 4: 2, 5: 2, 6: 2, 7: 2, 8: 2, 9: 2})
```

This is because (I believe) `zeroValue` gets passed correctly to each partition, but after `RDD.mapPartitions()` completes, the `zeroValue` object has been updated and is then passed to `RDD.fold()`, which results in all items being double-counted within each partition before being finally reduced at the calling node.

I realize that this type of calculation is typically done by `RDD.mapPartitions(...).reduceByKey(...)`, but hopefully this illustrates some potentially confusing behavior. I also noticed that other `RDD` methods use this `deepcopy` approach to creating unique copies of `zeroValue` (i.e., `RDD.aggregateByKey()` and `RDD.foldByKey()`), and that the Scala implementations do seem to serialize the `zeroValue` object appropriately to prevent this type of behavior.

### CODE REVIEW

**Comment by JoshRosen** [comment]
Hi @njhwang,

Thanks for submitting this pull request.  Do you mind filing a JIRA ticket at https://issues.apache.org/jira/browse/SPARK to report this issue?

Check out https://cwiki.apache.org/confluence/display/SPARK/Contributing+to+Spark for an overview of how the Spark contribution process works.

I agree that we should try to guard against mutation of the zero original zero value.  I'd also look into whether we should be using a copy on line 904 in `return self.mapPartitions(func).fold(zeroValue, combOp)`; there might be other cases that need to be addressed, too.

It would be good to add a regression test for this.  Take a look at `python/pyspark/tests.py` for examples of how to do this (once you've created the JIRA, I'd reference the JIRA ticket number in your test via a line comment).

**Comment by njhwang** [comment]
JIRA ticket here: https://issues.apache.org/jira/browse/SPARK-9021

Will look into regression tests and other contribution requirements.

**Comment by njhwang** [comment]
I'll note that I did consider adding more copies on line 904 as you mention, as well as within `RDD.fold()`. I don't believe another copy is needed, as `RDD.fold()` appears to properly guard against mutation (see comment in `RDD.fold()`). It appeared other places within the `RDD` module were good as well, but will investigate more closely with the forthcoming regression tests.

**Comment by JoshRosen** [comment]
Ah, cool.  I suspected that you might have looked into the case on line 904, but just wanted to confirm.  Wouldn't hurt to add a line comment there to explain this :)

**Comment by njhwang** [comment]
Okay, think that does it; let me know if the tests seem sufficient (or overkill). Took the liberty of replacing a few calls to `range()` with `xrange()` per the documentation for `parallelize()`. Confirmed that `RDD.aggregate()` appears to be the only problematic handling of zero values, and that this PR fixes the issue.

**Comment by JoshRosen** [comment]
Jenkins this is ok to test

**Comment by njhwang** [comment]
Did not realize `collections.Counter()` wasn't introduced until Python 2.7, and that tests were run against Python 2.6...will change those tests to use a different data structure later today.

**Comment by njhwang** [comment]
Hooray. Sorry for the churn, guess I should have a Python 2.6 environment to do backwards compatibility tests :).

**Comment by JoshRosen** [comment]
I'm actually going to kick off another build now since we _just_ merged a change to the Python linter and I want to avoid a committing race that leads to a build break.

**Comment by JoshRosen** [comment]
Jenkins, retest this please.

**Comment by JoshRosen** [comment]
@davies, this would be another good PR for you to review, esp. now that it's passing tests.

**Comment by davies** [comment]
@njhwang @JoshRosen The reason we need to do deepcopy here is that the two mapPartition() will be combined together as a single task. When the closure is serialized by pickle, the zeroValue will be memorized by Pickler, and deserialized as single object for two mapParition(). It's weird to call fold() inside aggregate(), because it does not need to run `combOp` on each partition, it should be change to:
```
  return reduce(combOp, self.mapPartitions(func).collect(), zeroValue)
```

Then we don't need to do the deep copy (deep copy may fail in some cases, for example, object from C extension).

**Comment by njhwang** [comment]
@davies That makes sense. I just confirmed this works (and it's exactly what you do in `RDD.fold()` anyway). Will do another build/test sequence locally later today before pushing and having Mr. Jenkins put it through the ringer again.

**Comment by davies** [comment]
LGTM, could you update the title and description?

**Comment by njhwang** [comment]
Done!

**Comment by davies** [comment]
Thanks, merging into master!

**Pull request closed without merging**
