### PR TITLE
[SPARK-48763][CONNECT][BUILD][FOLLOW-UP] Move Spark Connect common/server into sql directory

### PR DESCRIPTION
**Pull request by HyukjinKwon**
### What changes were proposed in this pull request?

This PR is a followup of https://github.com/apache/spark/pull/47157 that moves `connect` into `sql/connect`.

### Why are the changes needed?

The reasons are as follow:
- There was a bit of question about moving `connect` as a standalone top level (https://github.com/apache/spark/pull/47157#issuecomment-2202337766).
- Technically all Spark Connect related code have to placed under `sql` just like Hive thrift server.
  - Spark Connect server is 99% SQL dedicated code for now
  - Spark Connect server already is using a lot of `spark.sql` configurations, e.g., `spark.sql.connect.serverStacktrace.enabled`
  - Spark Connect common is only for SQL module. If other components have to be implemented, that common has to be placed within that directory.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

CI in this PR should verify it.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @hvanhovell

**Review by dongjoon-hyun — APPROVED** [review]
Although this is a massive change, +1 for the direction for Apache Spark 4.0.0 . Thank you, @HyukjinKwon .

**Comment by HyukjinKwon** [comment]
Thank you!!!

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
