### PR TITLE
[SPARK-12362][SQL][WIP] Inline Hive Parser

### PR DESCRIPTION
**Pull request by hvanhovell**
This PR inlines the Hive SQL parser in Spark SQL.

The previous (merged) incarnation of this PR passed all tests, but had and still has problems with the build. These problems are caused by a the fact that - for some reason - in some cases the ANTLR generated code is not included in the compilation fase.

This PR is a WIP and should not be merged until we have sorted out the build issues.

### CODE REVIEW

**Comment by hvanhovell** [comment]
retest this please

**Comment by hvanhovell** [comment]
retest this please

**Comment by hvanhovell** [comment]
retest this please

**Comment by hvanhovell** [comment]
retest this please

**Comment by hvanhovell** [comment]
retest this please

**Comment by hvanhovell** [comment]
last one promise :)

**Comment by hvanhovell** [comment]
retest this please

**Comment by hvanhovell** [comment]
@JoshRosen I just had to recreate the deps file. Not much seems to have changed, it appears that only the sorting is different. Is this correct?

**Comment by JoshRosen** [comment]
The script calls into the Unix `sort` command in order to sort the dependencies. I wonder whether `sort` is returning different results on your machine vs. mine. Maybe we should shell into Python to perform the sort in order to get more portability.

**Comment by rxin** [comment]
I triggered the build 5 times.

**Comment by hvanhovell** [comment]
retest this please

**Comment by hvanhovell** [comment]
retest this please

**Comment by hvanhovell** [comment]
retest this please

**Comment by hvanhovell** [comment]
retest this please

**Comment by hvanhovell** [comment]
@JoshRosen these builds fail often and non-deterministically with a **fails build dependency** tests. The problem is that I cannot find the cause of this problem (the build fails with no helpfull message), these builds share this problem:
* https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/48518/consoleFull
* https://amplab.cs.berkeley.edu/jenkins/job/NewSparkPullRequestBuilder/2279/consoleFull (NewSparkPullRequestBuilder?)
* https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/48550/consoleFull
* https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/48552/consoleFull
* https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/48553/consoleFull

After the initial error I thought I messed up the dependencies (I am messing with the build). I changed them and I got a correct build failure with 'nice' error message:
* https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/48521/consoleFull

Could you take a look?

**Comment by hvanhovell** [comment]
retest this please

**Comment by JoshRosen** [comment]
I have a few hunches about what could be causing the dependency manifest checking problems. I'll keep investigating when I get home later tonight. I think I've spotted two potential problems: there might be some portability issues with how we're using `sort` and I think there might be a mistake in the exit-code-handling logic.

**Comment by rxin** [comment]
Should we revert that dependency check thing first?

**Comment by JoshRosen** [comment]
Aha! It appears that there _is_ a portability issue in `sort`, or at least in how we're using it in the dependency-checking script.

When I run `echo -e "breeze-macros\nbreeze_2.0" | sort` on my Mac, I get 

```
breeze-macros
breeze_2.0
```

but I get the opposite ordering when running on AMPLab Jenknis.

On my mac, `sort --version` outputs `sort (GNU coreutils) 5.93`, whereas AMP Jenkins has `sort (GNU coreutils) 8.4`. But it turns out that this isn't the problem! It's a locale-dependent issue: https://stackoverflow.com/questions/28881/why-doesnt-sort-sort-the-same-on-every-machine

We need to set `LC_ALL=C` in order to make things portable. I'm going to open a hotfix PR to address these issues, then will retest this PR once my fix is in.

**Comment by JoshRosen** [comment]
Patch to fix it is at #10543; planning to merge soon.

**Comment by JoshRosen** [comment]
Jenkins, retest this please.

**Comment by rxin** [comment]
I triggered 3 more runs.

**Comment by rxin** [comment]
cc @JoshRosen dependency failed again

**Comment by rxin** [comment]
@JoshRosen I pushed a commit directly to disable test-dependencies.

**Comment by rxin** [comment]
OK merging again.

**Comment by gatorsmile** [comment]
After this merge, I am unable to make a build in IntelliJ IDEA. It might be related to the naming? I hit the following the errors:

```
Error:(1477, 5) not found: value SparkSqlParser
    SparkSqlParser.Number,
    ^
Error:(1478, 5) not found: value SparkSqlParser
    SparkSqlParser.TinyintLiteral,
    ^
Error:(1479, 5) not found: value SparkSqlParser
    SparkSqlParser.SmallintLiteral,
    ^
Error:(1480, 5) not found: value SparkSqlParser
    SparkSqlParser.BigintLiteral,
    ^
Error:(1481, 5) not found: value SparkSqlParser
    SparkSqlParser.DecimalLiteral)
    ^
Error:(1686, 41) not found: value SparkSqlParser
    case ast: ASTNode if ast.getType == SparkSqlParser.StringLiteral =>
                                        ^
Error:(1689, 41) not found: value SparkSqlParser
    case ast: ASTNode if ast.getType == SparkSqlParser.TOK_DATELITERAL =>
                                        ^
Error:(1692, 41) not found: value SparkSqlParser
    case ast: ASTNode if ast.getType == SparkSqlParser.TOK_CHARSETLITERAL =>
                                        ^
Error:(1695, 41) not found: value SparkSqlParser
    case ast: ASTNode if ast.getType == SparkSqlParser.TOK_INTERVAL_YEAR_MONTH_LITERAL =>
                                        ^
Error:(1698, 41) not found: value SparkSqlParser
    case ast: ASTNode if ast.getType == SparkSqlParser.TOK_INTERVAL_DAY_TIME_LITERAL =>
                                        ^
Error:(1701, 41) not found: value SparkSqlParser
    case ast: ASTNode if ast.getType == SparkSqlParser.TOK_INTERVAL_YEAR_LITERAL =>
                                        ^
Error:(1704, 41) not found: value SparkSqlParser
    case ast: ASTNode if ast.getType == SparkSqlParser.TOK_INTERVAL_MONTH_LITERAL =>
                                        ^
Error:(1707, 41) not found: value SparkSqlParser
    case ast: ASTNode if ast.getType == SparkSqlParser.TOK_INTERVAL_DAY_LITERAL =>
                                        ^
Error:(1710, 41) not found: value SparkSqlParser
    case ast: ASTNode if ast.getType == SparkSqlParser.TOK_INTERVAL_HOUR_LITERAL =>
                                        ^
Error:(1713, 41) not found: value SparkSqlParser
    case ast: ASTNode if ast.getType == SparkSqlParser.TOK_INTERVAL_MINUTE_LITERAL =>
                                        ^
Error:(1716, 41) not found: value SparkSqlParser
    case ast: ASTNode if ast.getType == SparkSqlParser.TOK_INTERVAL_SECOND_LITERAL =>
                                        ^
```

**Comment by gatorsmile** [comment]
nvm, I just need to reimport all maven projects. The problem has been fixed. Thanks!

**Comment by hvanhovell** [comment]
Good one, was looking for that myself :)...

**Pull request closed without merging**
