### PR TITLE
[SPARK-11250] [SQL] Generate different alias for columns with same name during join

### PR DESCRIPTION
**Pull request by NarineK**
It's confusing to see columns with same name after joining, and hard to access them, we could generate different alias for them in joined DataFrame.

see https://github.com/apache/spark/pull/9012/files#r42696855 as example

### CODE REVIEW

**Comment by NarineK** [comment]
it seems that there is an issue for python, I'll fix the signature soon!

I'd appreciate your feedback on the signature and the logic @davies @shivaram @rxin @sun-rui 

Thanks,
Narine

**Comment by NarineK** [comment]
retest this please

**Comment by NarineK** [comment]
@davies, would you, please, let me know what do you think or maybe you know someone who can review this ?
Thnx,
Narine

**Comment by holdenk** [comment]
Just pinging @davies or @marmbrus  to see if this is something you might have bandwith to review (in which case we can ask the author if they have the time to update to the latest master).

**Comment by NarineK** [comment]
I'd be happy to update to the latest master if we want to review this now.

**Comment by marmbrus** [comment]
Thanks for working on this!  Sorry for letting this PR go stale.  While I think this could be a good feature, I'm worried that as its implemented it would be a breaking change (since we are renaming columns).  It also seems like its broken some python tests?

Perhaps it would be best to go back to JIRA and agree on the API.  In pandas for example, I think you might need to explicitly ask for a prefix.

As a minor note, there are also a few style issues.  The [style guide](https://cwiki.apache.org/confluence/display/SPARK/Spark+Code+Style+Guide) talks more about our rules for indenting, etc.

**Comment by NarineK** [comment]
I see, I can go over the pull request this weekend. Thanks for the feedback.

**Comment by NarineK** [comment]
I am trying different ways to solve the problem without renaming the columns and it seems that a better place to change the column names would be here: https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/basicLogicalOperators.scala#L268

By changing the names of output attributes.
Do you have any preferences @marmbrus ?

**Comment by marmbrus** [comment]
I would not bake this logic into the logical operator, I think the general approach of doing it in Dataset is better.  I just think that we need to do it in a way that does not change existing join functionality at all.  It would be helpful to survey other systems and describe their APIs and make a proposal based on that.

**Comment by NarineK** [comment]
Thank you for following up on this, @marmbrus !
I looked into two places: R and Pandas DataFrames.

In R it seems that they give new names to columns(columns which aren't in merge/join condition) and then merge:
https://github.com/talgalili/R-code-snippets/blob/master/merge.data.frame.r#L86

In SparkR I've implemented it for the merge: https://github.com/apache/spark/pull/9012

In Pandas, DataFrame join has the suffixes too.
It creates new labels using suffixes:
https://github.com/pandas-dev/pandas/blob/master/pandas/tools/merge.py#L901

then, uses the new labels, as an axis (I assume column names) of the joined DataFrame.
https://github.com/pandas-dev/pandas/blob/master/pandas/tools/merge.py#L916
 
Maybe we can have something similar to Pandas ?

**Comment by NarineK** [comment]
In pandas it has 2 arguments:
lsuffix='', rsuffix='', respectively for left and right sides. And it appends the suffixes to all column names regardless if they are in join condition or not .

**Comment by NarineK** [comment]
I'd propose to have:

1. One input argument: suffixes[left, right] (if you want we can have 2 similar to pandas). 
2. Default values for suffixes (I think defaults are more convenient but we can do it like in pandas and make it required )
3. The logic can be implemented like in pandas: we will add suffixes regardless if the columns are in join condition or not
4. We can have a separate method for join with suffixes and set new column names after join has happened and do not touch existing join functions ... 

What do you think @marmbrus, @holdenk

**Comment by gatorsmile** [comment]
Thanks for submitting this PR. We are following how the SQL interface handles the issue. For example,
```SQL
create table t1(c1 int, c2 int);
create table t2(c1 int, c2 int);

insert into t1 values (1, 2);
insert into t2 values (1, 2);

select c1 from (select * from t1, t2) t;
```

When Oracle executing the last line, it will trigger the error
> ORA-00918: column ambiguously defined

We can revisit automatic alias name generation in the future. How about closing this PR now?

**Comment by HyukjinKwon** [comment]
Hi @NarineK, is there any opinion on ^?

**Comment by NarineK** [comment]
@HyukjinKwon do you mean closing or fixing the PR ? As I understand from @gatorsmile he wants to close it ....

**Comment by gatorsmile** [comment]
@NarineK I think we can close it at first.

**Comment by shahanesanket** [comment]
Is there a solution available for this yet? I am still seeing this spark join issue with column names. No prefixes get added by default and I don't see an option to add it in the join function as well.

**Pull request closed without merging**
