### PR TITLE
[SPARK-42461][CONNECT] Scala Client implement first batch of functions

### PR DESCRIPTION
**Pull request by hvanhovell**
### What changes were proposed in this pull request?
This PR adds the following functions to Spark Connect Scala Client:
- Sort Functions
- Aggregate Functions
- Misc Functions
- Math Functions

### Why are the changes needed?
We want to the Spark Connect Scala Client to reach parity with the original functions API.

### Does this PR introduce _any_ user-facing change?
Yes, it adds a lot of functions.

### How was this patch tested?
Added test for all functions and their significant variations.

### CODE REVIEW

**Comment by hvanhovell** [comment]
Not for the reviewer. I still want to add a couple of tests for duplicate functions.

**Review by dongjoon-hyun — DISMISSED** [review]
Did you verify this with Scala 2.13?

To reviewers, please hold on approving this PR. This module has been broken already with Scala 2.13. The broken branch blocks other community member's development severely.

**Review by dongjoon-hyun — COMMENTED** [review]
FYI, the previous PR leaves 9 UT failures.
```
     [info] *** 9 TESTS FAILED ***
     [error] Failed tests:
     [error] 	org.apache.spark.sql.connect.ProtoToParsedPlanTestSuite
     [error] (connect / Test / test) sbt.TestsFailedException: Tests unsuccessful
     [error] Total time: 41 s, completed Feb 16, 2023, 7:06:12 AM
```

**Comment by hvanhovell** [comment]
@dongjoon-hyun I will fix those today. I do think we should have a discussion about this. Currently we have both maven and scala-2.13 that are not tested during CI. That seems wrong if both are apparently supported. The mental overhead of testing these manually is very high.

**Comment by hvanhovell** [comment]
As for blocking other community members severely, the same applies to the lack of testing of scala-2.13.

**Comment by hvanhovell** [comment]
Fix for 2.13 has merged. I am going to hold this off until https://github.com/apache/spark/pull/40056 is merged.

**Review by zhengruifeng — APPROVED** [review]

**Review by HyukjinKwon — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM (Pending CIs).
I assume that this is tested with Scala 2.13 in the same way, @hvanhovell .

**Comment by hvanhovell** [comment]
merging

**Comment by hvanhovell** [comment]
thanks all

**Pull request closed without merging**
