### PR TITLE
[SPARK-43436][BUILD] Upgrade rocksdbjni to 8.1.1.1

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr aims to upgrade rocksdbjni from 8.0.0 to 8.1.1.1.

### Why are the changes needed?
The full release notes as follows:

- https://github.com/facebook/rocksdb/releases/tag/v8.1.1

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?

- Pass GitHub Actions
- Manual test `RocksDBBenchmark`:

**8.0.0**

```
[INFO] Running org.apache.spark.util.kvstore.RocksDBBenchmark
                                                count   mean    min     max     95th
dbClose                                         4       0.339   0.256   0.532   0.532
dbCreation                                      4       69.637  4.128   268.371 268.371
naturalIndexCreateIterator                      1024    0.005   0.002   1.581   0.006
naturalIndexDescendingCreateIterator            1024    0.005   0.005   0.067   0.007
naturalIndexDescendingIteration                 1024    0.006   0.004   0.029   0.008
naturalIndexIteration                           1024    0.006   0.004   0.069   0.009
randomDeleteIndexed                             1024    0.026   0.018   0.200   0.035
randomDeletesNoIndex                            1024    0.015   0.012   0.050   0.018
randomUpdatesIndexed                            1024    0.088   0.033   33.234  0.096
randomUpdatesNoIndex                            1024    0.035   0.032   0.497   0.039
randomWritesIndexed                             1024    0.129   0.035   56.362  0.121
randomWritesNoIndex                             1024    0.041   0.034   1.415   0.047
refIndexCreateIterator                          1024    0.005   0.004   0.029   0.006
refIndexDescendingCreateIterator                1024    0.003   0.003   0.028   0.004
refIndexDescendingIteration                     1024    0.007   0.005   0.044   0.008
refIndexIteration                               1024    0.008   0.005   0.367   0.010
sequentialDeleteIndexed                         1024    0.023   0.017   1.716   0.025
sequentialDeleteNoIndex                         1024    0.015   0.012   0.043   0.017
sequentialUpdatesIndexed                        1024    0.045   0.037   0.943   0.054
sequentialUpdatesNoIndex                        1024    0.041   0.029   0.838   0.053
sequentialWritesIndexed                         1024    0.051   0.043   2.945   0.056
sequentialWritesNoIndex                         1024    0.037   0.030   2.828   0.042
```

**8.1.1.1**

```
[INFO] Running org.apache.spark.util.kvstore.RocksDBBenchmark
                                                count   mean    min     max     95th
dbClose                                         4       0.319   0.233   0.514   0.514
dbCreation                                      4       69.826  3.767   268.894 268.894
naturalIndexCreateIterator                      1024    0.005   0.002   1.409   0.007
naturalIndexDescendingCreateIterator            1024    0.005   0.005   0.062   0.007
naturalIndexDescendingIteration                 1024    0.006   0.004   0.026   0.008
naturalIndexIteration                           1024    0.007   0.004   0.182   0.011
randomDeleteIndexed                             1024    0.027   0.020   0.259   0.037
randomDeletesNoIndex                            1024    0.016   0.013   0.041   0.019
randomUpdatesIndexed                            1024    0.087   0.033   29.514  0.102
randomUpdatesNoIndex                            1024    0.036   0.033   0.495   0.040
randomWritesIndexed                             1024    0.120   0.033   53.330  0.126
randomWritesNoIndex                             1024    0.041   0.035   1.403   0.047
refIndexCreateIterator                          1024    0.006   0.005   0.019   0.007
refIndexDescendingCreateIterator                1024    0.003   0.003   0.028   0.005
refIndexDescendingIteration                     1024    0.007   0.005   0.053   0.008
refIndexIteration                               1024    0.008   0.006   0.254   0.010
sequentialDeleteIndexed                         1024    0.023   0.018   1.237   0.027
sequentialDeleteNoIndex                         1024    0.015   0.013   0.043   0.018
sequentialUpdatesIndexed                        1024    0.046   0.038   0.816   0.057
sequentialUpdatesNoIndex                        1024    0.042   0.030   0.719   0.052
sequentialWritesIndexed                         1024    0.050   0.042   2.089   0.057
sequentialWritesNoIndex                         1024    0.036   0.030   2.030   0.042
```

- Checked core module UTs with rocksdb live ui

```
export LIVE_UI_LOCAL_STORE_DIR=/${basedir}/spark-ui    
build/mvn clean install -pl core -am -Dtest.exclude.tags=org.apache.spark.tags.ExtendedLevelDBTest -fn
```

all test passed

### CODE REVIEW

**Comment by LuciferYang** [comment]
will update result of `StateStoreBasicOperationsBenchmark` later

**Comment by LuciferYang** [comment]
When I tried this upgrade, I found that the result of 'StateStoreBasicOperationsBenchmark' was unexpected. For check if it was a new version(8.1.1.1) issue, I also ran the 'StateStoreBasicOperationsBenchmark' on the master branch(with 8.0.0), and there were significant differences between the test data and the previous records and 'StateStoreBasicOperationsBenchmark' also run timeout（more than 6hours, It should have been completed in 3 hours before）:

https://github.com/LuciferYang/spark/actions/runs/4949396450/jobs/8856766625

``
[success] Total time: 791 s (13:11), completed May 11, 2023 7:33:07 PM
23/05/11 19:33:12 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Running org.apache.spark.sql.execution.benchmark.StateStoreBasicOperationsBenchmark:
23/05/11 19:33:15 WARN SparkContext: The JAR file:/home/runner/work/spark/spark/core/target/scala-2.12/spark-core_2.12-3.5.0-SNAPSHOT-tests.jar at spark://localhost:44659/jars/spark-core_2.12-3.5.0-SNAPSHOT-tests.jar has been added already. Overwriting of added jar is not supported in the current version.
Running benchmark: putting 10000 rows (10000 rows to overwrite - rate 100)
  Running case: In-memory
  Stopped after 10000 iterations, 82351 ms
  Running case: RocksDB (trackTotalNumberOfRows: true)
  Stopped after 10000 iterations, 599839 ms
  Running case: RocksDB (trackTotalNumberOfRows: false)
  Stopped after 10000 iterations, 210482 ms

OpenJDK 64-Bit Server VM 1.8.0_362-b09 on Linux 5.15.0-1037-azure
Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
putting 10000 rows (10000 rows to overwrite - rate 100):  Best Time(ms)   Avg Time(ms)   Stdev(ms)    Rate(M/s)   Per Row(ns)   Relative
---------------------------------------------------------------------------------------------------------------------------------------
In-memory                                                            7              8           1          1.4         739.9       1.0X
RocksDB (trackTotalNumberOfRows: true)                              58             60           1          0.2        5828.2       0.1X
RocksDB (trackTotalNumberOfRows: false)                             20             21           0          0.5        2033.4       0.4X

OpenJDK 64-Bit Server VM 1.8.0_362-b09 on Linux 5.15.0-1037-azure
Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
putting 10000 rows (7500 rows to overwrite - rate 75):  Best Time(ms)   Avg Time(ms)   Stdev(ms)    Rate(M/s)   Per Row(ns)   Relative
-------------------------------------------------------------------------------------------------------------------------------------
In-memory                                                          8              9           1          1.3         772.9       1.0X
RocksDB (trackTotalNumberOfRows: true)                            56             58           1          0.2        5567.7       0.1X
RocksDB (trackTotalNumberOfRows: false)                           21             23           4          0.5        2126.2       0.4X

OpenJDK 64-Bit Server VM 1.8.0_362-b09 on Linux 5.15.0-1037-azure
Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
putting 10000 rows (5000 rows to overwrite - rate 50):  Best Time(ms)   Avg Time(ms)   Stdev(ms)    Rate(M/s)   Per Row(ns)   Relative
-------------------------------------------------------------------------------------------------------------------------------------
In-memory                                                          8              9           1          1.3         760.7       1.0X
RocksDB (trackTotalNumberOfRows: true)                            51             53           1          0.2        5089.3       0.1X
RocksDB (trackTotalNumberOfRows: false)                           21             22           1          0.5        2133.7       0.4X


OpenJDK 64-Bit Server VM 1.8.0_362-b09 on Linux 5.15.0-1037-azure
Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
putting 10000 rows (2500 rows to overwrite - rate 25):  Best Time(ms)   Avg Time(ms)   Stdev(ms)    Rate(M/s)   Per Row(ns)   Relative
-------------------------------------------------------------------------------------------------------------------------------------
In-memory                                                          7              8           1          1.3         747.6       1.0X
RocksDB (trackTotalNumberOfRows: true)                            46             47           1          0.2        4603.3       0.2X
RocksDB (trackTotalNumberOfRows: false)                           21             22           1          0.5        2141.8       0.3X


OpenJDK 64-Bit Server VM 1.8.0_362-b09 on Linux 5.15.0-1037-azure
Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
putting 10000 rows (1000 rows to overwrite - rate 10):  Best Time(ms)   Avg Time(ms)   Stdev(ms)    Rate(M/s)   Per Row(ns)   Relative
-------------------------------------------------------------------------------------------------------------------------------------
In-memory                                                          7              8           1          1.4         732.3       1.0X
RocksDB (trackTotalNumberOfRows: true)                            43             44           1          0.2        4283.7       0.2X
RocksDB (trackTotalNumberOfRows: false)                           21             22           1          0.5        2132.0       0.3X


OpenJDK 64-Bit Server VM 1.8.0_362-b09 on Linux 5.15.0-1037-azure
Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
putting 10000 rows (500 rows to overwrite - rate 5):  Best Time(ms)   Avg Time(ms)   Stdev(ms)    Rate(M/s)   Per Row(ns)   Relative
-----------------------------------------------------------------------------------------------------------------------------------
In-memory                                                        7              8           1          1.4         732.3       1.0X
RocksDB (trackTotalNumberOfRows: true)                          42             43           1          0.2        4169.4       0.2X
RocksDB (trackTotalNumberOfRows: false)                         21             22           1          0.5        2124.4       0.3X


OpenJDK 64-Bit Server VM 1.8.0_362-b09 on Linux 5.15.0-1037-azure
Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
putting 10000 rows (0 rows to overwrite - rate 0):  Best Time(ms)   Avg Time(ms)   Stdev(ms)    Rate(M/s)   Per Row(ns)   Relative
---------------------------------------------------------------------------------------------------------------------------------
In-memory                                                      7              8           1          1.4         727.9       1.0X
RocksDB (trackTotalNumberOfRows: true)                        40             42           1          0.2        4038.6       0.2X
RocksDB (trackTotalNumberOfRows: false)                       21             22           1          0.5        2129.9       0.3X

.......

OpenJDK 64-Bit Server VM 1.8.0_362-b09 on Linux 5.15.0-1037-azure
Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
evicting 1000 rows (maxTimestampToEvictInMillis: 999) from 10000 rows:  Best Time(ms)   Avg Time(ms)   Stdev(ms)    Rate(M/s)   Per Row(ns)   Relative
-----------------------------------------------------------------------------------------------------------------------------------------------------
In-memory                                                                          5              5           0          2.2         458.3       1.0X
RocksDB (trackTotalNumberOfRows: true)                                             9              9           0          1.1         871.2       0.5X
RocksDB (trackTotalNumberOfRows: false)                                            5              6           0          1.9         518.3       0.9X

Running benchmark: evicting 500 rows (maxTimestampToEvictInMillis: 499) from 10000 rows
  Running case: In-memory
  Stopped after 10000 iterations, 50617 ms
  Running case: RocksDB (trackTotalNumberOfRows: true)
Error: The operation was canceled.
```

I will try to investigate this issue, cc @dongjoon-hyun @HeartSaVioR FYI

**Comment by dongjoon-hyun** [comment]
Thank you for your investigation, @LuciferYang !

**Comment by HeartSaVioR** [comment]
That's because we no longer use writebatch which has been problematic on memory usage. We should have probably run the benchmark and updated the result...

The overall performance won't be significantly reduced as we pay the cost in each operation without writebatch which we are going to pay the cost at once in commit phase when we use writebatch & flush in commit phase. (We benchmarked by ourselves.)

cc. @anishshri-db Would you mind adding more context here? We probably need to update the benchmark, with reduce of the number of operations.

**Comment by LuciferYang** [comment]
If this is expected, optimizing benchmark testing should be more reasonable, as current benchmark testing will fail due to GA timeout

**Comment by anishshri-db** [comment]
@LuciferYang - As @HeartSaVioR mentioned, this is part of our broader effort to reduce memory usage for rocksdb. As part of that change, we don't use writeBatch any more and have also moved to disable the write ahead log. As part of this, puts/deletes will be written to memtables and gets will also be served from memtables/block cache which might lead to some difference in perf for those options. We can cover up for most of that since the db write during commit is now eliminated and we can also do periodic flushing with a related upcoming change.

Could you let me know which b/mark test will fail and how we run that ?

@HeartSaVioR - do you proposing changing the b/mark itself ? or rerunning and updating the results page ?

**Comment by LuciferYang** [comment]
@anishshri-db I need to update the results of `StateStoreBasicOperationsBenchmark` when upgrade rocksdbjni, we can run `StateStoreBasicOperationsBenchmark` with GA as following:

image
 
It did not fail and was killed by GA due to timeout. Previously, 'StateStoreBasicOperationsBenchmark' was executed for 3 hours, but now it has been executed for more than 6 hours and has not been completed yet.

**Comment by anishshri-db** [comment]
@LuciferYang - ok cool thanks. I'll update the b/mark and try running this workflow.

**Comment by LuciferYang** [comment]
Thanks @anishshri-db

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Review by anishshri-db — APPROVED** [review]

**Pull request closed without merging**
