### PR TITLE
[SPARK-35409][SQL] Skip escaping meta-characters for EXPLAIN command using show()

### PR DESCRIPTION
**Pull request by shahidki31**
### What changes were proposed in this pull request?

Explain SQL command using show is not user friendly. New line characters are escaped by default in spark3.2, hence plan is not showing in the tree structure. In this PR, we are preventing skipping meta characters in case of Explain command.

### Why are the changes needed?

`scala>sql("EXPLAIN COST SELECT item.i_brand, count(1), date_dim.d_year, item.i_brand_id, sum(store_sales.ss_ext_sales_price) AS ext_price, item.i_item_sk
FROM store_sales INNER JOIN date_dim ON (date_dim.d_date_sk = store_sales.ss_sold_date_sk) INNER JOIN item ON (store_sales.ss_item_sk = item.i_item_sk)
GROUP BY item.i_brand, date_dim.d_date, item.i_item_desc, date_dim.d_year, item.i_brand_id, item.i_item_sk").show(false)`

**Before**
image

**After**
`
image

### Does this PR introduce _any_ user-facing change?
Yes

### How was this patch tested?
Manual testing

### CODE REVIEW

**Review by srowen — COMMENTED** [review]
When would you not want to escape them?

**Comment by shahidki31** [comment]
Hi @srowen , This was added to fix an issue in the JIRA: https://issues.apache.org/jira/browse/SPARK-33690. But after that it would be difficult to see spark plans using show command. In this PR, we are adding a flag, so that user can control whether to enable or not, especially in case of seeing plan using show command.

**Comment by srowen** [comment]
Can we somehow special case EXPLAIN output? I don't think it makes sense to make users figure this out..

**Comment by shahidki31** [comment]
> Can we somehow special case EXPLAIN output? I don't think it makes sense to make users figure this out..

Sure. I will try.

**Comment by shahidki31** [comment]
@srowen I have updated the PR. Please check

**Review by srowen — COMMENTED** [review]
@sarutak what do you think of this as a special case?

**Comment by sarutak** [comment]
How about overload `show` which takes a parameter controlling which special character is not escaped.
I don't think it's a good idea to treat only `explain` as a special case.

**Comment by sarutak** [comment]
Also, why not doing `spark.sql("...").explain` rather than `spark.sql("EXPLAIN ...").show`?

**Comment by shahidki31** [comment]
> Also, why not doing `spark.sql("...").explain` rather than `spark.sql("EXPLAIN ...").show`?

Yes right. There are many ways to see the plan of a query. Ideally explain command should also show the plan properly. 
Also, I am not sure we need to override the show just for this special case. If we think this behaviour is fine, then we can leave as it is?

**Comment by HyukjinKwon** [comment]
The special characters break the format in the console table and it confuses which value belong to which field.

**Comment by HyukjinKwon** [comment]
We could think about having an option or configuration but I think the default behaviour should stay same with escaping the special characters.

**Comment by shahidki31** [comment]
I will close this PR for now till we find a better solution . Thanks @srowen @sarutak for the feedback.

**Pull request closed without merging**
