### PR TITLE
[SPARK-6136] [SQL] Removed JDBC integration tests which depends on docker-client

### PR DESCRIPTION
**Pull request by liancheng**
Integration test suites in the JDBC data source (`MySQLIntegration` and `PostgresIntegration`) depend on docker-client 2.7.5, which transitively depends on Guava 17.0. Unfortunately, Guava 17.0 is causing test runtime binary compatibility issues when Spark is compiled against Hive 0.12.0, or Hadoop 2.4.

Considering `MySQLIntegration` and `PostgresIntegration` are ignored right now, I'd suggest moving them from the Spark project to the [Spark integration tests](|https://github.com/databricks/spark-integration-tests) project. This PR removes both the JDBC data source integration tests and the docker-client test dependency.

[Review on Reviewable](https://reviewable.io/reviews/apache/spark/4872)

### CODE REVIEW

**Comment by srowen** [comment]
Isn't it a little extreme to remove the tests? what about just excluding the Guava dep so that 14.0 is used? it may just work

**Comment by liancheng** [comment]
@srowen These two test suites do a bunch of time consuming jobs like setting up docker contains, pulling in MySQL/PostgreSQL, etc., and are thus ignored from the very beginning. (You may see the `@Ignore` annotations.) I've put moving them to the [Spark integration tests project] [1] on my todo list. I believe that's a better place for us to run these complex integration tests, especially because that project has already been well dockerized.

[1]: https://github.com/databricks/spark-integration-tests

**Comment by srowen** [comment]
@liancheng Ah I looked right past the `@Ignore`. Well, I tend to agree with your logic. You guys know better than I would.

**Comment by marmbrus** [comment]
+1 to moving these to integration tests, especially if they are causing build problems.  Can you make sure there is a JIRA somewhere (where?) to make sure we don't forget though.  These tests actually did find all kinds of quirks with the various drivers.

**Comment by liancheng** [comment]
@marmbrus @srowen Filed [SPARK-6147] [1] to track this. Thanks for the comments!

[1]: https://issues.apache.org/jira/browse/SPARK-6147

**Pull request closed without merging**
