### PR TITLE
[SPARK-37101][CORE] In class ShuffleBlockPusher, use config instead of key

### PR DESCRIPTION
**Pull request by jinhai-cloud**
### What changes were proposed in this pull request?

In class ShuffleBlockPusher, We can use config.REDUCER_MAX_SIZE_IN_FLIGHT and config.REDUCER_MAX_REQS_IN_FLIGHT instead of "spark.reducer.maxSizeInFlight" and "spark.reducer.maxReqsInFlight"

### Why are the changes needed?

Unified config instead of hard coding

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Existing test

### CODE REVIEW

**Review by dohongdayi — COMMENTED** [review]
LGTM

**Review by HyukjinKwon — COMMENTED** [review]
How was this patch tested?

**Comment by HyukjinKwon** [comment]
Please fill the PR description as guided in the template.

**Review by HyukjinKwon — APPROVED** [review]
Looks good otherwise. cc @Ngone51 too fyi

**Review by Ngone51 — COMMENTED** [review]
LGTM if tests pass. cc @mridulm @otterc

**Review by mridulm — APPROVED** [review]

**Pull request closed without merging**
