### PR TITLE
[Core][ SPARK-5065]Fix: BroadCast can still work after sc had been stopped.

### PR DESCRIPTION
**Pull request by SaintBacchus**
Fix the bug as code shows:

``` scala
val sc1 = new SparkContext
sc1.stop
val sc2 = new SparkContext
sc1.broadcast(1)
```

The broadCast can still work after sc had down.
So throw an exception to fix it  when broadcast called in such scenario.

### CODE REVIEW

**Comment by JoshRosen** [comment]
This is a nice fix, but it would be nice to include a test case for this.  This is probably going to merge-conflict with my PR #3884, so I may end up incorporating this change into that PR.

**Comment by SaintBacchus** [comment]
Hi, @JoshRosen I had added the test in my PR.But I can't find where having confilict with your PR #3884 . Can you point it out for me?

**Comment by JoshRosen** [comment]
@SaintBacchus I've incorporated the change in this PR into my PR in #3884, plus I've also added tests to prevent other SparkContext methods from being called after the context was stopped (e.g. sc.parallelize(), sc.accumulator(), etc).  Please take a look at my most recent commit.

**Comment by SaintBacchus** [comment]
Ok, @JoshRosen . Your PR has covered mine. I will open until yours have merged into the master branch.
But I still have a question: do we need add so many `assertNotStopped` in these methods?
As far as I know, only the `broadcast` method can work well, others will throw the runtime exception to be ended.

**Comment by JoshRosen** [comment]
@SaintBacchus Some of the others _don't_ work well: calling `sc.parallelize` would throw a confusing NullPointerException, for example.  I took the shotgun-blast approach of just adding assertNotStopped everywhere since it seemed simpler than going through the methods on a case-by-case basis.

**Pull request closed without merging**
