### PR TITLE
[SPARK-7696][SQL] Aggregate function's result should be nullable only if the input expression is nullable

### PR DESCRIPTION
**Pull request by ogirardot**
The following functions are now nullable or not according to their child expressions :
- Min, Max
- First, Last
- Sum, Average

### CODE REVIEW

**Comment by ogirardot** [comment]
added the license to the test file

**Comment by ogirardot** [comment]
Seems to fail for something completely different : 
```
[error] /home/jenkins/workspace/SparkPullRequestBuilder/sql/hive/src/main/scala/org/apache/spark/sql/hive/orc/OrcRelation.scala:174: overriding method buildScan in class HadoopFsRelation of type (requiredColumns: Array[String], filters: Array[org.apache.spark.sql.sources.Filter], inputPaths: Array[String])org.apache.spark.rdd.RDD[org.apache.spark.sql.catalyst.expressions.Row];
[error]  method buildScan cannot override final member
[error]   override def buildScan(requiredColumns: Array[String],
[error]                ^
```

Not really related to this patch.

**Comment by andrewor14** [comment]
retest this please

**Comment by marmbrus** [comment]
I believe that all of these expressions will return null when run on an empty result set, so technically they are always nullable.

**Comment by ogirardot** [comment]
@marmbrus I may misunderstand the nullable flag, but I can have an empty dataset with a non-nullable column.
For example : 
```
scala> val r = sc.parallelize(List((1, true), (3, false)))

scala> val a = r.toDF

scala> a.printSchema
root
 |-- _1: integer (nullable = false)
 |-- _2: boolean (nullable = false)

scala> a.filter("_1 < 1").groupBy("_1").agg(avg("_1")).show()
AVG('_1)                                                                                                                                                                                                    

scala> a.filter("_1 < 1").groupBy("_1").agg(avg("_1")).printSchema
root
 |-- AVG('_1): double (nullable = true)
```

I don't think that AVG(_1) should be nullable, if you think so then yes this PR is useless.

Regards, 

Olivier.

**Comment by chenghao-intel** [comment]
But you will see null outputs:
```scala
a.filter("_1 < 1").groupBy("_1").agg(avg("_1")).collect
res5:Array[org.apache.spark.sql.Row] = Array()
```

**Comment by ogirardot** [comment]
I don't really understand, the Array is empty not filled with nulls

**Comment by ogirardot** [comment]
@rxin any input ?

**Comment by rxin** [comment]
What does other SQL systems do? i.e. Hive, MySQL.

it might make sense for sum ot return 0, but should avg return null if there is no data?

**Comment by chenghao-intel** [comment]
That's the output from mysql:
```
mysql> create table t4(k int, v int);
Query OK, 0 rows affected (0.17 sec)

mysql> select avg(k) from t4;
+--------+
| avg(k) |
+--------+
|   NULL |
+--------+
1 row in set (0.04 sec)

mysql> select avg(k) from t4 group by v;
Empty set (0.00 sec)

mysql> 
```
If no group by key specified, it outputs `NULL` otherwise it output empty set. I think Spark SQL works in the same way.

**Comment by chenghao-intel** [comment]
From this point of view, I think it's reasonable to say aggregation functions should always be nullable, but depends on different use scenarios. (with / without grouping keys)

**Comment by marmbrus** [comment]
I believe it is the SQL standard that says they should return null.

**Comment by rxin** [comment]
Yup - @ogirardot then we should close this PR.

**Comment by ogirardot** [comment]
ok - :-/

**Pull request closed without merging**
