### PR TITLE
[SPARK-5022] [SQL] [MLlib] Change VectorUDT to object

### PR DESCRIPTION
**Pull request by MechCoder**

### CODE REVIEW

**Comment by MechCoder** [comment]
cc @rxin I am unable to understand how to change this line

`@SQLUserDefinedType(udt = classOf[VectorUDT])` . I tried doing `@SQLUserDefinedType(udt = VectorUDT.getClass)`

Sorry if this seems dumb, because I'm relatively new.

**Comment by MechCoder** [comment]
@jkbradley I'm also not sure how the `SQLUserDefinedType` is supposed to work. Do you mind giving me a short note?

**Comment by jkbradley** [comment]
@MechCoder  This may require changing SQLUserDefinedType.udt() to return an instance of the class, rather than the class tag.  That way, it may return either a new instance or a static (object) instance.

**Comment by MechCoder** [comment]
@jkbradley Thanks for the clarification. I gave a few attempts, but I don't think I'm doing it the right way. This is what you mean right?

Presently in `SQLUserDefinedType` we have `udt` of type Class which inherits from a `UserDefinedType`. This corresponds to the class tag generated by `classOf[VectorUDT]` in the annotation.

But now since we have changed `VectorUDT` to an object, in `SQLUserDefinedType` I need to change the definition of `udt` such that it corresponds to an instance of the class (or) an object rather than the class itself. But how do I do this?

Also, is it possible in cases where instantiation needs variables in the constructor? For example in this case (https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/test/ExamplePointUDT.scala#L31) ?

**Comment by rxin** [comment]
What do you mean by instantiation needs variables in the constructor?

I actually have no idea about the annotation for the object thing. If you can't figure it out, maybe it is best to just close the ticket. I'm not sure how important it is to change it to an object so we can remove one equals method.

**Comment by MechCoder** [comment]
Thanks for the comment.

I meant that now udt is a ClassTag. If udt were to be an Object or an instance of a class, then I'm not sure if it possible if the class accepts parameters as in the case of ExamplePointUDT.

Actually Java annotations don't support objects. (http://stackoverflow.com/questions/1458535/which-types-can-be-used-for-java-annotation-members) which explains the errors.

Can you think of any workaround?

**Comment by rxin** [comment]
Sorry not sure how to do this. That's why I think it might be ok to not do this one at all, since it should have no impact on end user, and very little on maintainability.

**Comment by MechCoder** [comment]
Alright, closing could you please mark the issue as fixed?

Sad that I've had to close two Pull Request's for the same reasons. Hopefully I'll find something more substantial to contribute.

**Comment by jkbradley** [comment]
I agree this is not that important and is OK to cancel the JIRA.  I didn't know about annotation members not supporting objects--thanks for finding that out!

**Pull request closed without merging**
