### PR TITLE
[SPARK-7845] [Build] Bump "Hadoop 1" tests to version 1.2.1

### PR DESCRIPTION
**Pull request by yhuai**
https://issues.apache.org/jira/browse/SPARK-7845

### CODE REVIEW

**Comment by pwendell** [comment]
LGTM pending tests

**Comment by srowen** [comment]
LGTM

**Comment by yhuai** [comment]
Thanks! I am merging it to master and branch 1.4.

**Comment by srowen** [comment]
Minor point of process: merging something like this for 1.4 probably doesn't matter either way as it affects Jenkins builds, but, probably shouldn't be then? no harm done but then I wonder, can we mark this as fixed for 1.4.0? If RC2 is final (and I somehow doubt it won't be) then this is not fixed for 1.4.0

**Comment by yhuai** [comment]
@srowen Yeah, only merging this kind of prs to master makes sense. Thank you for pointing it out.

Regarding the fix version, what will be a good practice to set fix version(s) for jiras that get merged after a RC? Maybe add a label to the jira when it is merged and after the release, we check if the fix version is correctly set for those jiras? For example, because this one was merged after RC2, we add a `1.4.0-RC3` label (it means that it will be included in 1.4.0's RC3) to the jira and set the fix version to `1.4.0` for now. If RC2 is final, after the release, we set the fix version of this one to `1.4.1` and `1.5.0`, and then remove the `1.4.0-RC3` label.

**Comment by srowen** [comment]
I don't know, it's an interesting question. Right now there are some things I'd like to merge for _1.4.1_ but we can't really do that now. You can mark them `backport-needed` if it's important, I suppose, and not merge into 1.4.0 at all right now.

**Comment by yhuai** [comment]
oh, actually, for this one, we indeed want this change affects our 1.4 jenkins build. If we only merge it to master, 1.4 jenkins build will not be changed, right?

**Comment by srowen** [comment]
True, yes if this needs to affect the 1.4 branch it should go in at some point; if it were a more delicate change it could be done after the release for 1.4.1. For this it isn't a big deal in any event, I was just wondering out loud about how we manage this.

**Pull request closed without merging**
