### PR TITLE
[WIP][SPARK-24498][SQL] Add JDK compiler for runtime codegen

### PR DESCRIPTION
**Pull request by kiszk**
## What changes were proposed in this pull request?

This PR allow a user to select Javac bytecode compiler to compile a DataFrame/Dataset program.
Details will be filled later.

This PR is based on @maropu's implementation.

## How was this patch tested?

Added `CompilerSuite`

### CODE REVIEW

**Comment by gatorsmile** [comment]
@maropu @kiszk Thank you for taking this effort!

Based on my initial understanding, the code generated by the JDK compiler can be better optimized by JIT in many cases. Is my understanding right?

**Comment by maropu** [comment]
Yea, as you said, the JDK compiler generates different bytecode though, I couldn't get obvious performance gains for TPCDS as compared to the janino one. So, I couldn't find the strong reason to implement this in terms of performance; https://docs.google.com/spreadsheets/d/1Mgdd9dfFaACXOUHqKfaeKrj09hB3X1j9sKTJlJ6UM6w/edit#gid=1236423798

As another viewpoint, I think it might be useful to check if the generated Java code of Spark could be compiled by the JDK compiler (JDK8 code compatibility checks). But, since the compilation of the JDK compiler is too slow (see the performance values in the google spread sheet above), IMO it is impractical to check this in Jenkins.... (I found it took 7~8 hours to run the tests of the `spark/sql` only in aws instances). WDYT?

**Comment by gatorsmile** [comment]
Also cc @rednaxelafx

**Comment by maropu** [comment]
btw, it seems this pr exceeds the current timeout...　Any way to temporarily make the timeout longer?   We always need to configure timeout in the Jenkins-side like https://github.com/apache/spark/pull/20222#issuecomment-357004091?

**Comment by kiszk** [comment]
It is a good question. Let me think and investigate for a while.
I appreciate comment from @rednaxelafx

**Comment by gatorsmile** [comment]
@maropu Based on my understanding, the bytecodes generated by these two compilers are different. That is why the performance should be different. Previously, I expected the bytecodes generated by JDK compiler can be better optimized by JIT, compared with the one generated by Janino. Maybe our JVM internal experts @kiszk and @rednaxelafx can give more guidance.

**Comment by maropu** [comment]
@kiszk Can you close this?

**Pull request closed without merging**
