### PR TITLE
[SPARK-26016][DOCS] Clarify that text DataSource read/write, and RDD methods that read text, always use UTF-8

### PR DESCRIPTION
**Pull request by srowen**
## What changes were proposed in this pull request?

Clarify that text DataSource read/write, and RDD methods that read text, always use UTF-8 as they use Hadoop's implementation underneath. I think these are all the places that this needs a mention in the user-facing docs.

## How was this patch tested?

Doc tests.

### CODE REVIEW

**Comment by srowen** [comment]
CC @MaxGekk

**Review by MaxGekk — APPROVED** [review]
LGTM

**Review by HyukjinKwon — APPROVED** [review]
LGTM except one nit

**Comment by HyukjinKwon** [comment]
Merged to master.

Tests are already passed. I manually ran scalastyle against this PR in my local to be doubly sure.

**Pull request closed without merging**
