### PR TITLE
[MINOR]Hide the error logs for 'SQLListenerMemoryLeakSuite'

### PR DESCRIPTION
**Pull request by zsxwing**
Hide the error logs for 'SQLListenerMemoryLeakSuite' to avoid noises. Most of changes are space changes.

### CODE REVIEW

**Comment by zsxwing** [comment]
@marmbrus  Please use https://github.com/apache/spark/pull/10363?w=1 to review. `quietly` doesn't work for this test. So I used `log4j` API directly.

**Comment by marmbrus** [comment]
This seems reasonable (although might make it slightly hard to debug if there is ever a failure since I think we are fully turning off those messages, even to `unit-test.log`).  We might consider making this an extra feature of `quietly`, but I'm okay merging this as is.

**Comment by zsxwing** [comment]
Okey. Merging to master, 1.6 and 1.5

**Comment by zsxwing** [comment]
Just merged to master due to conflicts with 1.6 and 1.5

**Pull request closed without merging**
