### PR TITLE
[SPARK-31612][SQL][DOCS] SQL Reference clean up

### PR DESCRIPTION
**Pull request by huaxingao**
### What changes were proposed in this pull request?
SQL Reference cleanup

### Why are the changes needed?
To complete SQL Reference

### Does this PR introduce _any_ user-facing change?
Fix the following stuff:

- Example -> Examples
- SET DBPROPERTIES ( property_name = property_value, ... ) -> SET DBPROPERTIES ( property_name = property_value [ , ... ] )  
// be consistent with format. brackets [ and ] indicate optional parts, and dots ... mean that the 
// preceding element can be repeated.
- col_spec [ , col_spec ... ] -> col_spec [ , ... ] // same as above, be consistent with format.
- [USING data_source] -> [ USING data_source ] // be consistent with format. space between [ and text
- change function_name format to make it consistent with others
- from -> FROM // uppercase keyword
- { { VALUES ( { value | NULL } [ , ... ] ) [ , ( ... ) ] } | query } ->  { VALUES ( { value | NULL } [ , ... ] ) [ , ( ... ) ] | query } // remove unnecessary { } 
- DROP ( DATABASE | SCHEMA ) -> DROP { DATABASE | SCHEMA } 
// Braces { and } and vertical lines | indicate that you must choose one alternative
- fix a few link and typo too. 

Also updated sql-ref-syntax-qry.html

before
Screen Shot 2020-04-29 at 11 08 25 PM

after
Screen Shot 2020-04-29 at 11 05 55 PM

### How was this patch tested?
Manually build and check

### CODE REVIEW

**Comment by huaxingao** [comment]
cc @gatorsmile @maropu 
In the first round of clean-up, I will focus on syntax and typos. After I finish this, I will remove all the html syntax following this PR https://github.com/apache/spark/pull/28414. Then change HTML tables to MD tables following this PR https://github.com/apache/spark/pull/28415
I have added a couple of ```<code> </code>``` in this PR, because when I did this, I didn't know we will remove html syntax. I will just leave these ```<code> </code>```, will remove all the html syntax in the second round of clean-up.

**Review by srowen — APPROVED** [review]

**Review by maropu — APPROVED** [review]

**Comment by maropu** [comment]
Thanks! Merged to master/3.0.

**Comment by huaxingao** [comment]
Thanks! @maropu @srowen

**Comment by maropu** [comment]
Ur, plz add what's cleaned up in the PR description.

**Comment by huaxingao** [comment]
Updated.

**Pull request closed without merging**
