### PR TITLE
[SPARK-17108][SQL]: Fix BIGINT and INT comparison failure in spark sql

### PR DESCRIPTION
**Pull request by weiqingy**
## What changes were proposed in this pull request?

Add a function to check if two integers are compatible when invoking `acceptsType()` in `DataType`.
## How was this patch tested?

Manually.  
E.g.

```
    spark.sql("create table t3(a map<bigint, array<string>>)")
    spark.sql("select * from t3 where a[1] is not null")
```

Before:

```
cannot resolve 't.`a`[1]' due to data type mismatch: argument 2 requires bigint type, however, '1' is of int type.; line 1 pos 22
org.apache.spark.sql.AnalysisException: cannot resolve 't.`a`[1]' due to data type mismatch: argument 2 requires bigint type, however, '1' is of int type.; line 1 pos 22
    at org.apache.spark.sql.catalyst.analysis.package$AnalysisErrorAt.failAnalysis(package.scala:42)
    at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1$$anonfun$apply$2.applyOrElse(CheckAnalysis.scala:82)
    at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1$$anonfun$apply$2.applyOrElse(CheckAnalysis.scala:74)
at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformUp$1.apply(TreeNode.scala:307)
```

After:
 Run the sql queries above. No errors.

### CODE REVIEW

**Comment by hvanhovell** [comment]
Could you try to fix this by adding implicit casting to the `GetMapValue` (make it extend `ImplicitCastInputTypes` instead of `ExpectsInputTypes`)?

**Comment by hvanhovell** [comment]
Also add unit tests please.

**Comment by weiqingy** [comment]
Hi, @hvanhovell Thanks for the quick feedback. Yes, I will update the PR.

**Comment by weiqingy** [comment]
Hi, @hvanhovell I have updated the PR, could you help review it again?

**Comment by weiqingy** [comment]
Hi, @hvanhovell Could you review this PR again? Thanks.

**Comment by weiqingy** [comment]
Hi, @hvanhovell Could you review this PR again? Thanks.

**Comment by hvanhovell** [comment]
LGTM. Merging to master/2.1. Thanks!

My apologies for the long wait!

**Comment by weiqingy** [comment]
@hvanhovell Thanks for the review!

**Pull request closed without merging**
