### PR TITLE
[SPARK-19817][SS] Make it clear that `timeZone` is a general option in DataStreamReader/Writer

### PR DESCRIPTION
**Pull request by lw-lin**
## What changes were proposed in this pull request?

As timezone setting can also affect partition values, it works for all formats, we should make it clear.

## How was this patch tested?

N/A

### CODE REVIEW

**Comment by lw-lin** [comment]
This is the fix for the streaming counter-part (i.e. Structured Streaming), @ueshin @gatorsmile would you take a look? Thanks!

**Comment by cloud-fan** [comment]
LGTM

**Comment by ueshin** [comment]
LGTM, thank you for your follow-up!

**Comment by ueshin** [comment]
Thanks! Merging to master.

**Pull request closed without merging**
