### PR TITLE
#SPARK-2808 update kafka to version 0.8.2

### PR DESCRIPTION
**Pull request by helena**
https://issues.apache.org/jira/browse/SPARK-2808 update kafka to version 0.8.2. Kafka 0.8.2 is in beta still.

### CODE REVIEW

**Comment by helena** [comment]
Waiting for kafka 0.8.2 to move to GA, still beta

**Comment by rustyrazorblade** [comment]
Kafka 0.8.2 is now listed as latest stable.

**Comment by tdas** [comment]
Aah cool. However 0.8.1 and 0.8.2 have pretty big changes between them, so lets merge this for the next release. We are already doing a lot of experimental Kafka stuff in this release (feature merge window has closed).

**Comment by helena** [comment]
@tdas what shall I do with this PR to complete it then?

**Comment by tdas** [comment]
The first step would be to see whether upgrading to 0.8.2 passes the
inbuilt unit-tests or not (including the new Kafka stuff).
In addition, is there are documentation somewhere that talks about the
compatibility of 0.8.2 with 0.8.0 / 0.8.1.1 kafka clusters? We can figure
out the path accordingly. In any case, it will be in the next release cycle
(1.4).

**Comment by helena** [comment]
All streaming-kafka sbt tests and  /dev/run-tests passed in my initial push as beta, and with the GA update all still pass.  Should I resubmit this PR against another branch?

I am getting cluster backwards compat docs..

**Comment by tdas** [comment]
Jenkins, this is ok to test.

**Comment by tdas** [comment]
Then for the new API (which does not store offsets externally) may need to be updated to ensure compatibility. I am not sure whether the current unit tests will catch such issues. This will require a bit of manual testing. Will do after 1.3 release rush. :)

Thanks for the link!

**Comment by helena** [comment]
NP, I think manual may not be necessary, just the addition of tests that automate testing the version or testing all and handling the execution path properly. I can add that when merged.

**Comment by srowen** [comment]
@helena I too would like to update to Kafka 0.8.2 as it does have a number of good improvements. can you rebase? @tdas are you OK with merging this for only master / 1.4.0?

**Comment by helena** [comment]
Hi @srowen, will do.

**Comment by koeninger** [comment]
This will need some changes to KafkaCluster and possibly other things related to the new api... let me know if you want a hand.

**Comment by helena** [comment]
@koeninger Yes, there consumer offset and some other minor changes to make.
I'm finding it hard to carve out time for this, high ticket load this week. Go for it if you want, otherwise I'll do it later in the week.

**Comment by helena** [comment]
@koeninger this is a definite blocker for me, I'm upgrading the connector to scala 2.11 with a cross build. Let me know if you have time, otherwise I will get back to this tomorrow morning.

**Comment by koeninger** [comment]
@helena I updated it, pr is at https://github.com/apache/spark/pull/4537

**Comment by helena** [comment]
Great I'll close this.

**Pull request closed without merging**
