### PR TITLE
[SPARK-4284] BinaryClassificationMetrics precision-recall method names s...

### PR DESCRIPTION
**Pull request by Lewuathe**
...hould correspond to return types

Precision-recall curve is the general term. Therefore I decided not to change `prCurve` names.

### CODE REVIEW

**Comment by mengxr** [comment]
@Lewuathe `precision-recall` is widely used. It could be a little strange to call it "RP". If you feel the method is still confusing even with the doc, maybe we can add `prCurve` and `rocCurve` and deprecate `pr` and `roc` to make it clear that this is the `precision-recall curve`.

**Comment by Lewuathe** [comment]
@mengxr I think it is difficult to infer what the order of precision and recall is returned from `pr` method name. So I think keeping the order of returned values on method name is useful for API user. But I also think it is a reasonable way to make public `prCurve` and `rocCurve` instead of `pr` and `roc` for preventing misunderstanding.

**Comment by srowen** [comment]
@Lewuathe FWIW I vote for deprecating existing methods, but leaving the behavior the same, and introducing new methods like `prCurve` whose return value is 'corrected'.

**Comment by mengxr** [comment]
@srowen By definition, the precision-recall curve consists of (recall, precision) points. It is unfortunate that it was named this way. I don't have strong preference on whether we should return (precision, recall) or (recall, precision) for `prCurve`, because I feel that both of them could cause troubles.

**Comment by srowen** [comment]
@mengxr That's a fair point, since it's always drawn as a curve with recall on the x axis and of course the x component is conventionally first. It's a precision-as-function-of-recall curve. Well, that's a reasonable reason to just say that the current method is correct as-is and clearly document its return value.

**Comment by mengxr** [comment]
@Lewuathe I think we can either deprecate `pr`/`roc` and  create `prCurve`/`rocCurve` with exactly the same behavior, or simply leave them as-is. I prefer the former a little bit, but no strong preference.

**Comment by Lewuathe** [comment]
@mengxr @srowen Thank you for reviewing. I agree to the reason why `pr` method is also reasonable in terms of drawing curve. I'll keep it as-is. 
But anyway I want to make it explicit in [official document](https://spark.apache.org/docs/latest/mllib-guide.html) although there seems to be no `mllib.evaluation` item here. Is there already documentation about `mllib.evaluation`?

**Comment by mengxr** [comment]
@Lewuathe For binary classification, the documentation is here: 

https://spark.apache.org/docs/latest/mllib-linear-methods.html#evaluation-metrics

But we don't have a section for evaluation. It would be good to have one and add other evaluation metrics in the user guide.

**Comment by mengxr** [comment]
@Lewuathe Do you mind closing this PR? If you want to update the official document, we can do that in another PR. Thanks for the discussion!

**Comment by Lewuathe** [comment]
@mengxr Thank you for reminding me. I create another PR as soon as possible.

**Pull request closed without merging**
