### PR TITLE
[SPARK-22222][CORE][TEST][FOLLOW-UP] Remove redundant and deprecated `Timeouts`

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
## What changes were proposed in this pull request?

Since SPARK-21939, Apache Spark uses `TimeLimits` instead of the deprecated `Timeouts`. This PR fixes the build warning `BufferHolderSparkSubmitSuite.scala` introduced at [SPARK-22222](https://github.com/apache/spark/pull/19460/files#diff-d8cf6e0c229969db94ec8ffc31a9239cR36) by removing the redundant `Timeouts`.
```scala
trait Timeouts in package concurrent is deprecated: Please use org.scalatest.concurrent.TimeLimits instead
[warn]     with Timeouts {
```
## How was this patch tested?

N/A

### CODE REVIEW

**Review by srowen — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thanks, @srowen !

**Comment by dongjoon-hyun** [comment]
Thanks, @srowen !

**Review by HyukjinKwon — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thanks, @HyukjinKwon .

**Review by jiangxb1987 — APPROVED** [review]
LGTM

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by dongjoon-hyun** [comment]
Thank you, @HyukjinKwon , @srowen , and @jiangxb1987 .

**Pull request closed without merging**
