### PR TITLE
[SPARK-27528][SQL] Use Parquet logical type TIMESTAMP_MICROS by default

### PR DESCRIPTION
**Pull request by MaxGekk**
## What changes were proposed in this pull request?

In the PR, I propose to use the `TIMESTAMP_MICROS` logical type for timestamps written to parquet files. The type matches semantically to Catalyst's `TimestampType`, and stores microseconds since epoch in UTC time zone. This will allow to avoid conversions of microseconds to nanoseconds and to Julian calendar. Also this will reduce sizes of written parquet files.

## How was this patch tested?

By existing test suites.

### CODE REVIEW

**Review by felixcheung — COMMENTED** [review]
could we document this? persistence data format changes are potentially fairly impactful

**Review by HyukjinKwon — APPROVED** [review]
Looks good given that INT96 is deprecated in Parquet too, and apparently migrating looks fine https://github.com/apache/spark/commit/777b797867045c9717813e9dab2ab9012a1889fc

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
