### PR TITLE
[SPARK-19273]shuffle stage should retry when fetch shuffle fail

### PR DESCRIPTION
**Pull request by viper-kun**
## What changes were proposed in this pull request?
shuffle stage should retry when fetch shuffle fail

## How was this patch tested?
see  https://issues.apache.org/jira/browse/SPARK-19273

### CODE REVIEW

**Comment by srowen** [comment]
You have not opened this vs master

**Comment by viper-kun** [comment]
@srowen I have not test in master version. I will do it later.

**Comment by srowen** [comment]
@viper-kun OK but in any event, we would not merge this PR, so it can be closed.

**Comment by viper-kun** [comment]
ok, close it.

**Pull request closed without merging**
