### PR TITLE
SPARK-6063

### PR DESCRIPTION
**Pull request by msjgriffiths**
Remove unicode characters from MLlib file.

### CODE REVIEW

**Comment by pwendell** [comment]
LGTM

**Comment by jkbradley** [comment]
LGTM

**Comment by mengxr** [comment]
test this please

**Comment by jkbradley** [comment]
Not sure why these unrelated tests are failing....  By the way, can you please add more of a title to the PR?

**Comment by srowen** [comment]
I don't think it's necessary to wait on Jenkins. This doc change can't cause a problem. We can fix the title on merge too. I'll wait anyway for that, but figure one of us can just merge soon in any event.

**Pull request closed without merging**
