### PR TITLE
[SPARK-19005][SQL] Keep column ordering when a schema is explicitly specified

### PR DESCRIPTION
**Pull request by maropu**
## What changes were proposed in this pull request?
This pr is to keep column ordering when a schema is explicitly specified.
A concrete example is as follows;

```
scala> import org.apache.spark.sql.types._
scala> case class A(a: Long, b: Int)
scala> val as = Seq(A(1, 2))
scala> spark.createDataFrame(as).write.parquet("/Users/maropu/Desktop/data/a=1/")
scala> val df = spark.read.parquet("/Users/maropu/Desktop/data/")
scala> df.printSchema
root
 |-- a: integer (nullable = true)
 |-- b: integer (nullable = true)

scala> val schema = new StructType().add("a", LongType).add("b", IntegerType)
scala> val df = spark.read.schema(schema).parquet("/Users/maropu/Desktop/data/")
scala> df.printSchema
root
 |-- b: integer (nullable = true)
 |-- a: long (nullable = true)

 ```

This fix removes the code to filter out the overlapped fields of a data schema in `getOrInferFileFormatSchema`. Then, it respects column ordering in `HadoopFsRelation#schema`.

## How was this patch tested?
Added tests in `ParquetPartitionDiscoverySuite`.
This pr comes from SPARK-18108(#16030).

### CODE REVIEW

**Comment by maropu** [comment]
I'm looking into the failure...

**Comment by maropu** [comment]
This fix change some existing behaviour in datasource.
For instance,
```
scala> sql("""CREATE TABLE testTable(a INT, b INT, c INT, d INT) USING PARQUET PARTITIONED BY (b, c)""")
scala> sql("""INSERT INTO TABLE testTable PARTITION (b=14, c) SELECT 13, 15, 16""").explain
scala> sql("""SELECT * FROM testTable""").show
```

```
// A new column ordering
+---+---+---+---+
|  a|  b|  c|  d|
+---+---+---+---+
| 13| 14| 15| 16|
+---+---+---+---+
```

```
// An old column ordering
+---+---+---+---+
|  a|  d|  b|  c|
+---+---+---+---+
| 13| 15| 14| 16|
+---+---+---+---+
```
I'm not sure this is acceptable, so welcome any advices.
cc: @cloud-fan

**Comment by cloud-fan** [comment]
`create table t(a int, b int) partitioned by (a)`, the schema of table t is: <b int, a int>.

This behavior is intentional and already published, we can not change it. What we should do is to find out other places that don't follow this rule and respect the given schema, i.e. you are doing the opposite thing.

**Comment by maropu** [comment]
Aha, okay and I'll fix that way. Thanks!

**Comment by maropu** [comment]
Jenkins, retest this please.

**Comment by maropu** [comment]
Jenkins, retest this please.

**Comment by maropu** [comment]
Jenkins, retest this please.

**Comment by maropu** [comment]
I looked around the code and then I though this is an expected behaviour, so I'll close this. Thanks!

**Pull request closed without merging**
