### PR TITLE
[SPARK-33740][SQL][3.0] hadoop configs in hive-site.xml can overrides pre-existing hadoop ones

### PR DESCRIPTION
**Pull request by yaooqinn**
Backport  #30709 to 3.0

### What changes were proposed in this pull request?

 org.apache.hadoop.conf.Configuration#setIfUnset will ignore those with defaults too

### Why are the changes needed?

    fix a regression

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

new tests

### CODE REVIEW

**Comment by yaooqinn** [comment]
cc @dongjoon-hyun

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
Please fix the compilation error.
```
error] /home/runner/work/spark/spark/sql/core/src/test/scala/org/apache/spark/sql/internal/SharedStateSuite.scala:59: too many arguments (3) for method loadHiveConfFile: (sparkConf: org.apache.spark.SparkConf, hadoopConf: org.apache.hadoop.conf.Configuration)Unit
2355
[error]     SharedState.loadHiveConfFile(conf, hadoopConf, Map.empty)
```

**Comment by dongjoon-hyun** [comment]
Thank you for updates, @yaooqinn .

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thanks, @yaooqinn .
Merged to branch-3.0.

**Pull request closed without merging**
