### PR TITLE
[SPARK-13117][Web UI] WebUI should use the local ip not 0.0.0.0

### PR DESCRIPTION
**Pull request by devaraj-kavali**
Fixed the HTTP Server Host Name/IP issue i.e. HTTP Server to take the
configured host name/IP and not '0.0.0.0' always.

### CODE REVIEW

**Comment by srowen** [comment]
Jenkins, test this please

**Comment by srowen** [comment]
LGTM

**Comment by devaraj-kavali** [comment]
> -  This patch fails Spark unit tests.

I don't see any test failures here https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/50971/testReport/

**Comment by srowen** [comment]
They're there: https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/50971/consoleFull
but I don't think it can be related.

**Comment by srowen** [comment]
Jenkins, retest this please

**Comment by srowen** [comment]
@devaraj-kavali this might be a legitimate failure. Does it pass for you?

**Comment by devaraj-kavali** [comment]
@srowen I am investigating it, will update. Thanks

**Comment by srowen** [comment]
Jenkins, retest this please

**Comment by devaraj-kavali** [comment]
Thanks @srowen for trying jenkins test to check this.

```javascript
[info] - verify that correct log urls get propagated from workers (2 seconds, 508 milliseconds)
Exception in thread "Thread-46" Exception in thread "Thread-53" java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:196)
	at java.net.SocketInputStream.read(SocketInputStream.java:122)
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.io.ObjectInputStream$PeekInputStream.peek(ObjectInputStream.java:2293)
	at java.io.ObjectInputStream$BlockDataInputStream.peek(ObjectInputStream.java:2586)
	at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2596)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1318)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
	at sbt.React.react(ForkTests.scala:114)
	at sbt.ForkTests$$anonfun$mainTestTask$1$Acceptor$2$.run(ForkTests.scala:74)
	at java.lang.Thread.run(Thread.java:745)
java.io.EOFException
	at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2598)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1318)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
	at org.scalatest.tools.Framework$ScalaTestRunner$Skeleton$1$React.react(Framework.scala:945)
	at org.scalatest.tools.Framework$ScalaTestRunner$Skeleton$1.run(Framework.scala:934)
	at java.lang.Thread.run(Thread.java:745)
[info] ScalaTest
[info] Run completed in 10 minutes, 41 seconds.
[info] Total number of tests run: 1378
[info] Suites: completed 152, aborted 0
[info] Tests: succeeded 1378, failed 0, canceled 0, ignored 5, pending 0
[info] All tests passed.
[error] Error: Total 0, Failed 0, Errors 0, Passed 0
[error] Error during tests:
[error] 	Running java with options -classpath /home/jenkins/workspace/SparkPullRequestBuilder/core/target/scala-2.11/test-classes:/home/jenkins/workspace/SparkPullRequestBuilder/core/target/scala-2.11/classes:/home/jenkins/workspace/SparkPullRequestBuilder/launcher/target/scala-2.11/classes:/home/jenkins/workspace/SparkPullRequestBuilder/network/common/target/scala-2.11/classes:/home/jenkins/workspace/SparkPullRequestBuilder/network/shuffle/target/scala-2.11/classes:/home/jenkins/workspace/SparkPullRequestBuilder/unsafe/target/scala-2.11/classes:/home/jenkins/wor............:/home/sparkivy/per-executor-caches/7/.sbt/boot/scala-2.10.5/org.scala-sbt/sbt/0.13.9/test-agent-0.13.9.jar:/home/sparkivy/per-executor-caches/7/.sbt/boot/scala-2.10.5/org.scala-sbt/sbt/0.13.9/test-interface-1.0.jar sbt.ForkMain 55745 failed with exit code 1
[info] MQTTStreamSuite:
```
```javascript
[info] Passed: Total 975, Failed 0, Errors 0, Passed 975, Ignored 12
[error] (core/test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 4484 s, completed Feb 17, 2016 5:23:51 AM
[error] running /home/jenkins/workspace/SparkPullRequestBuilder/build/sbt -Pyarn -Phadoop-2.3 -Phive -Pkinesis-asl -Phive-thriftserver -Dtest.exclude.tags=org.apache.spark.tags.ExtendedHiveTest,org.apache.spark.tags.ExtendedYarnTest test ; received return code 1
```

I think Jenkins are showing test failures because of these, I don't see any test case failure here. Can anyone help me to give some information about how to check these test errors?

**Comment by srowen** [comment]
Jenkins, test this please

**Comment by srowen** [comment]
@devaraj-kavali Let's try one more time. I'm not seeing that failure in other builds. Although the exception's ultimate cause isn't so clear, it could still be due to this change.

**Comment by devaraj-kavali** [comment]
I see the test/Jenkins failure is due to the PR change.

Here org.apache.spark.deploy.LogUrlsStandaloneSuite is failing because of the below exception,

```
16/02/22 17:38:32.257 dispatcher-event-loop-5 ERROR Worker: Connection to master failed! Waiting for master to reconnect...
16/02/22 17:38:42.441 ScalaTest-main-running-LogUrlsStandaloneSuite ERROR SparkUI: Failed to bind SparkUI
java.net.SocketException: Unresolved address
	at sun.nio.ch.Net.translateToSocketException(Net.java:157)
	at sun.nio.ch.Net.translateException(Net.java:183)
	at sun.nio.ch.Net.translateException(Net.java:189)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:76)
	at org.eclipse.jetty.server.nio.SelectChannelConnector.open(SelectChannelConnector.java:187)
	at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:316)
	at org.eclipse.jetty.server.nio.SelectChannelConnector.doStart(SelectChannelConnector.java:265)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.Server.doStart(Server.java:293)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.apache.spark.ui.JettyUtils$.org$apache$spark$ui$JettyUtils$$connect$1(JettyUtils.scala:283)
	at org.apache.spark.ui.JettyUtils$$anonfun$5.apply(JettyUtils.scala:293)
	at org.apache.spark.ui.JettyUtils$$anonfun$5.apply(JettyUtils.scala:293)
	at org.apache.spark.util.Utils$$anonfun$startServiceOnPort$1.apply$mcVI$sp(Utils.scala:1973)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:166)
	at org.apache.spark.util.Utils$.startServiceOnPort(Utils.scala:1964)
	at org.apache.spark.ui.JettyUtils$.startJettyServer(JettyUtils.scala:293)
	at org.apache.spark.ui.WebUI.bind(WebUI.scala:137)
	at org.apache.spark.SparkContext$$anonfun$13.apply(SparkContext.scala:458)
	at org.apache.spark.SparkContext$$anonfun$13.apply(SparkContext.scala:458)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:458)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:133)
	at org.apache.spark.deploy.LogUrlsStandaloneSuite$$anonfun$2.apply$mcV$sp(LogUrlsStandaloneSuite.scala:59)
	at org.apache.spark.deploy.LogUrlsStandaloneSuite$$anonfun$2.apply(LogUrlsStandaloneSuite.scala:55)
	at org.apache.spark.deploy.LogUrlsStandaloneSuite$$anonfun$2.apply(LogUrlsStandaloneSuite.scala:55)
	at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
```



In LogUrlsStandaloneSuite.scala, SPARK_PUBLIC_DNS is getting set as "public_dns" and same is trying to use while starting the jetty server in WebUI.scala and it is failing to resolve the "public_dns".

```javascript
 test("verify that log urls reflect SPARK_PUBLIC_DNS (SPARK-6175)") {
    val SPARK_PUBLIC_DNS = "public_dns"
    val conf = new SparkConfWithEnv(Map("SPARK_PUBLIC_DNS" -> SPARK_PUBLIC_DNS)).set(
      "spark.extraListeners", classOf[SaveExecutorInfo].getName)
    sc = new SparkContext("local-cluster[2,1,1024]", "test", conf)
```


```javascript
protected val publicHostName = Option(conf.getenv("SPARK_PUBLIC_DNS")).getOrElse(localHostName)
........
  def bind() {
    assert(!serverInfo.isDefined, "Attempted to bind %s more than once!".format(className))
    try {
      serverInfo = Some(startJettyServer(publicHostName, port, sslOptions, handlers, conf, name))
      logInfo("Started %s at http://%s:%d".format(className, publicHostName, boundPort))
```

**Comment by devaraj-kavali** [comment]
It is not giving clear details about the failure and exiting with the exit code 1 is because of ***System.exit(1)***. I think we can skip this ***System.exit(1)*** while running tests to avoid the termination of jvm for these kind of exceptions and show them as test failures. 

```javascript
    try {
      serverInfo = Some(startJettyServer(publicHostName, port, sslOptions, handlers, conf, name))
      logInfo("Started %s at http://%s:%d".format(className, publicHostName, boundPort))
    } catch {
      case e: Exception =>
        logError("Failed to bind %s".format(className), e)
        System.exit(1)
    }

```

**Comment by devaraj-kavali** [comment]
@srowen, I have fixed the test failure, Can you have a look into this? Thanks

**Comment by srowen** [comment]
Jenkins test this please

**Comment by srowen** [comment]
That seems logical. I'm actually not sure why it ever used 0.0.0.0 and "public_dns"

**Comment by devaraj-kavali** [comment]
Earlier there was no problem in the test because the jetty server was getting started with ‘0.0.0.0’ and was not taking effect of the value configured for SPARK_PUBLIC_DNS and test assertions are checking the host name of the url's and those url's are getting derived from the SPARK_PUBLIC_DNS.

**Comment by srowen** [comment]
Merged to master

**Comment by zsxwing** [comment]
@srowen Just found a problem when using spark-shell. 

After this change, when I start spark-shell, it binds to my real ip. It means I cannot use `localhost` or `127.0.0.1` to access the web UI. It's really not friendly to the beginners since they may have no idea why they cannot access web UI using `localhost:4040`.

Moreover, by default, spark-shell's log level will be WARN. So I cannot find the web UI link in the log when using spark-shell unless I manually change the log level before starting spark-shell.

As `spark-shell` is usually the first step for the Spark beginners, we should fix it. If it's not easy, I would like to revert this patch.

**Comment by zsxwing** [comment]
In addition, this affects people who use `client` mode. They cannot access the web ui using localhost.

**Comment by srowen** [comment]
Ah... We can revert if it is a big deal. I wonder if there is a way to fix forward. It seemed weird to bind to all IPs but this is a good counterexample. Not at my keyboard at the moment but fine if anyone needs to revert it for the momebt

**Comment by zsxwing** [comment]
@srowen Okey, I'm going to revert it.

**Comment by JeremiahDJordan** [comment]
If someone wants it to bind 0.0.0.0 then they should specify that and it could be the default. But there needs to be a way to override and specify only binding one ip.

**Comment by srowen** [comment]
Yeah, this change would have made the bind address configurable. The problem is the default was not 0.0.0.0. I am not sure what the implications of changing this default everywhere would be; could be just fine. That's probably the only way forward

**Comment by JeremiahDJordan** [comment]
Could just add a new config option for this instead of reusing the existing one, and default that to 0.0.0.0

**Comment by srowen** [comment]
Yes, though unless there is a logically separate thing to configure, this just makes things worse. I'm not clear if the local host address ever needs to be two different things to two parts of the code. The cases I can think of are: address to bind web apps to, and, address to advertise to other services.

**Comment by devaraj-kavali** [comment]
@srowen 
Would it be OK if we start the Jetty server with the default value as "0.0.0.0" instead of the local host name and it can take effect of the configured value for SPARK_PUBLIC_DNS if it is configured? It would change only for the Web UI and doesn't impact any others.

**Pull request closed without merging**
