### PR TITLE
[SPARK-39947][BUILD] Upgrade Jersey to 2.36

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr upgrade Jersey from 2.35 to 2.36.

### Why are the changes needed?
This version adapts to Jack 2.13.3, which is also used by Spark currently

- [Adopt Jackson 2.13](https://github.com/eclipse-ee4j/jersey/pull/4928)
- [Update Jackson to 2.13.3](https://github.com/eclipse-ee4j/jersey/pull/5076)

The release notes as follows:

- https://github.com/eclipse-ee4j/jersey/releases/tag/2.36

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass GitHub Actions

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]

**Comment by srowen** [comment]
I suppose we can back port to 3.3.x for the fixes and the possible 2.13 support improvement

**Comment by LuciferYang** [comment]
> improvement

OK, If can't merge into 3.3 directly, please let me know

**Review by dongjoon-hyun — APPROVED** [review]

**Comment by srowen** [comment]
Merged to master/3.3

**Comment by LuciferYang** [comment]
thanks @srowen @dongjoon-hyun @HyukjinKwon

**Pull request closed without merging**
