### PR TITLE
[SPARK-12581][SQL] Support case-sensitive table names in postgresql

### PR DESCRIPTION
**Pull request by maropu**
Table names in postgresql is originally case-insensitive.
To support case-sensitive table names, we need to wrap names in double quotes.

### CODE REVIEW

**Comment by maropu** [comment]
retest this please

**Comment by maropu** [comment]
retest this please

**Comment by maropu** [comment]
@liancheng @yhuai Could you review this?

**Comment by yhuai** [comment]
@maropu Thank you for the PR. So, when you quote a table name in postgres, the name is case-sensitive, right? Looks like we are always quoting the table name? If so, seems we are changing the semantic because if I use a table name `fOO` and I want it case-insensitive, we still treat it as a case sensitive table name?

**Comment by maropu** [comment]
@yhuai Yes, quoted tables in postgres are always case-sensitive. We need to support case-insensitive table names? Table names in sparksql (`DataFrame#registerTempTable`) and typical databases such as oracle and mysql are also case-sensitive, so IMO we need to comply with the rule.

**Comment by yhuai** [comment]
@maropu Let me explain. The case sensitivity in spark sql is actually configurable. For HiveContext, we use case insensitive resolution.

**Comment by maropu** [comment]
@yhuai Ah..., I misunderstood. Okay and how about turning on/off case sensitivity in configurations, e.g., `spark.sql.jdbc.caseSensitivity`?

**Comment by yhuai** [comment]
Is it a postgresql specific thing? Maybe it is better to allow users to set a conf in the data source optionsS (a conf that can be set by doing `sqlContext.read.option(key, value)`) instead of introducing a new sql conf?

**Comment by maropu** [comment]
@yhuai yes and it's a pg-specific thing. I agree that we add it as a data source option instead of sql conf. If the fix is acceptable, I'll fix this pr to add a data source option like `sqlContext.read.option("caseSensitiveTableName" -> "true")`.

**Comment by maropu** [comment]
Close this for now and, if needed, I'll reopen this.

**Pull request closed without merging**
