### PR TITLE
[SPARK-26389][SS][FOLLOW-UP]Format config name to follow the other boolean conf naming convention

### PR DESCRIPTION
**Pull request by Ngone51**
### What changes were proposed in this pull request?

Rename `spark.sql.streaming.forceDeleteTempCheckpointLocation` to `spark.sql.streaming.forceDeleteTempCheckpointLocation.enabled`.

### Why are the changes needed?

To follow the other boolean conf naming convention.

### Does this PR introduce any user-facing change?

No, as this config is newly added in 3.0.

### How was this patch tested?

Pass Jenkins.

### CODE REVIEW

**Comment by Ngone51** [comment]
cc @gatorsmile @cloud-fan @gaborgsomogyi @HeartSaVioR

**Comment by HeartSaVioR** [comment]
It would be great if we make clear about "Does this PR introduce any user-facing change?"; which versions are affected by such incompatible change. If official versions are contained we should also link both via AlternateConfig.

I know that's only applied to 3.0.0 so I don't expect we want to use AlternateConfig to couple them, but given the description of PR describes "yes" on the statement, so better to be clear. (Given this is FOLLOW-UP of the feature which is not released officially, maybe "No" is OK as well.)

**Review by HeartSaVioR — APPROVED** [review]
Other than PR description, the code change LGTM.

**Comment by Ngone51** [comment]
> Given this is FOLLOW-UP of the feature which is not released officially, maybe "No" is OK as well.

Make sense.

**Comment by cloud-fan** [comment]
ok to test

**Comment by cloud-fan** [comment]
@Ngone51 can you update the PR description and explicitly mention that this config is newly added in 3.0?

**Comment by Ngone51** [comment]
> @Ngone51 can you update the PR description and explicitly mention that this config is newly added in 3.0?

updated, thanks!

**Comment by cloud-fan** [comment]
retest this please

**Comment by cloud-fan** [comment]
retest this please

**Comment by Ngone51** [comment]
It seems that Jenkins has crashed for the whole day...

**Comment by cloud-fan** [comment]
retest this please

**Comment by HeartSaVioR** [comment]
retest this, please

**Comment by HeartSaVioR** [comment]
FYI #27001 (SPARK-30345) is raised to fix the test build 115646 (https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/115646/testReport)

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Comment by Ngone51** [comment]
Thanks all!

**Pull request closed without merging**
