### PR TITLE
[SPARK-16617][BUILD][CORE] Upgrade to Avro 1.8.x

### PR DESCRIPTION
**Pull request by srowen**
## What changes were proposed in this pull request?

Update to Avro 1.8.x to match Parquet 1.8 dependency.

See also https://github.com/apache/spark/pull/13986

## How was this patch tested?

Existing tests

### CODE REVIEW

**Review by srowen — COMMENTED** [review]
Phoning people like @vanzin @markgrover @steveloughran to comment on risks of updating Avro to 1.8. I know Hadoop is still on 1.7 (?) but we have already moved to Parquet 1.8.x which needs Avro 1.8.x. So this conflict is already here.

**Comment by vanzin** [comment]
If Avro is good at backwards compatibility it shouldn't be an issue; @JoshRosen seems to maintain the spark-avro package so he might have more insights.

**Comment by steveloughran** [comment]
It's invariably the transient stuff isn't it? 
Mvnrepo on Avro 1.8.1 logs [jackson as a a compile time dependency](http://mvnrepository.com/artifact/org.apache.avro/avro/1.8.1); that's the one I'd fear. But as it is a 1.9.x dependency, changes in Spark's 2.x use is irrelevant there.

Looking in Hadoop, [HADOOP-12527](https://issues.apache.org/jira/browse/HADOOP-12527) is the current state. Moving up to the 1.8.1 for Hadoop 3 seems wise; As for branch-2; I don't have any concerns about avro, just that little jackson dependency

**Comment by steveloughran** [comment]
Looking @ hadoop source, there's not much in hadoop common terms of use of `import org.apache.avro`, ut the `avro.Utf8` surfaces, and someone has tagged `fs.Path` as `@Stringable`, which is a pain; makes it a core dependency of the code.

Otherwise, the MR job client has a file `hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-core/src/main/avro/Events.avpr` which contains the avro schemas for job history. The biggest risk is going to be whether or not avro is backwards compatible with generated classes. I know protobuf isn't; don't know about about Avro...you'll need to ask around there.

**Comment by srowen** [comment]
Fortunately, yes, they both agree on the Jackson 1.x version -- 1.9.13. That much should be OK.

**Comment by steveloughran** [comment]
Checj with @busbey about binary compatibility with older generated/compiled classes; that's the recurrent problem with protobuf

**Comment by srowen** [comment]
I pinged Sean B. offline. I also happened to mention this to @tomwhite and he says he doesn't know of a reason that this Avro update would be problematic. I'm inclined to proceed for Spark 2.2.

**Comment by busbey** [comment]
The two main concerns going from 1.7 to 1.8 are:

* AVRO-1502 requires recompilation of some generates classes. Definitely those based on a fixed bytes schema, maybe nested fixed as well. See the jira for discussion
* AVRO-997 changed how the generic API handles enum schemas to be more strict, which will break common incorrect usage.

**Comment by vanzin** [comment]
> AVRO-1502 requires recompilation of some generated classes.

This sounds bad, because it basically means it's not backwards compatible (which is the concern @steveloughran raised). Spark also has modules that depend on Flume, which is called out explicitly in AVRO-1502 as being affected. So at this point, let me ask: is this upgrade *necessary* for parquet, as in, what breaks if we don't upgrade?

The Spark bug talks about a new feature in avro that would be nice for Spark, but there are known workarounds for it, or one can use the spark-avro library. So if it breaks backwards compatibility, I'm not so sure it's worth the upgrade.

If parquet really needs the new avro, it might be possible to hack things - relocating the new avro classes just for the parquet dependencies, but that would be pretty nasty.

**Comment by srowen** [comment]
Hm, that sounds non-trivial indeed. The risk is that Parquet trips itself over something like https://issues.apache.org/jira/browse/SPARK-19697 but we haven't observed that in Spark itself, as far as I know. We might therefore wait until we have a concrete problem to solve. Right now it's trading one unknown potential issue for another.

**Comment by steveloughran** [comment]
oh, this sucks. Find anyone who experienced "The great protobuf update of 2012" and ask them if they want to do it again.

Looking at the issues, AVRO-997 catches out "wrong" use of an API: if that can be identified at compile time, it could be corrected in uses of Spark's dependencies, then that sounds like something they should do pre-emptively.

Returning to Hadoop, it's use is in in bits of the YARN API, as far as I Can see.
1. Bumping up to a later avro version for Hadoop 3 will help sync things up, at the cost of "yet another piece of pain for everyone who upgrades".
2. Somehow shading that stuff, separate story.

Classpaths are the enemy of my life. If I had to split my working life between "classpath hell", "interesting code" and "wondering why my tests are all broken", I think CP may have the edge

**Comment by steveloughran** [comment]
FWIW, if there is something related to serialization that people should be pushing for in Hadoop 3, it is making all the little types serializable, such as `Path`, `FileStatus` and the like; those little things that you discover you can't use in closures because somebody forgot to mark them as `Serializable`. Easily fixed, if someone provides the patches. As it is, they only tend to go in when my code doesn't work, so coverage is limited to the classes I use

**Comment by busbey** [comment]
> > AVRO-1502 requires recompilation of some generated classes.
> This sounds bad, because it basically means it's not backwards compatible (which is the concern  @steveloughran raised). Spark also has modules that depend on Flume, which is called out explicitly in AVRO-1502 as being affected. So at this point, let me ask: is this upgrade necessary for parquet, as in, what breaks if we don't upgrade?

No, it is definitely not backwards compatible. Avro 1.8 is, generally speaking, not backwards compatible with Avro 1.7 (for runtime libraries / api stuff). Avro version numbers are %data format% dot %major version% dot %minor version%. [there were a total of 4 changes in Avro 1.8.0 marked as incompatible](https://issues.apache.org/jira/issues/?jql=project%20%3D%20AVRO%20AND%20fixVersion%20%3D%201.8.0%20AND%20%22Hadoop%20Flags%22%20%3D%20%22Incompatible%20change%22), these two were just the ones I think are most likely to impact folks.

I don't know if it's necessary for the parquet upgrade. If there's some feature of Avro 1.8 that Parquet needs we could also talk about backporting that to Avro 1.7, presuming it doesn't require some non-backwards compatible change. AFAIK the Avro community is still (trying to) make releases for the 1.7 line.

> oh, this sucks. Find anyone who experienced "The great protobuf update of 2012" and ask them if they want to do it again.

I agree that it's unfortunate, but libraries need the ability to make non-backwards compatible changes. Avro at least makes the effort to do it on major versions and flag when it happens, so I don't think comparisons to protobuf are fair here. FWIW, I made the case for backwards compatibility on both of these issues.

> Looking at the issues, AVRO-997 catches out "wrong" use of an API: if that can be identified at compile time, it could be corrected in uses of Spark's dependencies, then that sounds like something they should do pre-emptively.

Yes, this is something folks should do proactively. I don't know of any static analysis that will flag it for us, unfortunately.

> Returning to Hadoop, it's use is in in bits of the YARN API, as far as I Can see.
> 
> 1. Bumping up to a later avro version for Hadoop 3 will help sync things up, at the cost of "yet another piece of pain for everyone who upgrades".

I am a big +1 on bumping to Avro 1.8 in Hadoop 3. IMHO it's been so long since the Hadoop 2 release that saving this one bit of pain is minor in comparison to the risk of sticking to the 1.7 line through to Hadoop 4.

**Pull request closed without merging**
