### PR TITLE
[SPARK-38082][PYTHON] Update minimum numpy version to 1.15

### PR DESCRIPTION
**Pull request by zero323**
### What changes were proposed in this pull request?

This PR changes minimum required numpy version to 1.15.

Additionally, it replaces calls to deprecated `tostring` method.

### Why are the changes needed?

Current lower bound is ancient and no longer supported by the rest our dependencies.

Additionally, supporting it, requires usage of long deprecated methods creating unnecessary gaps in our type checker coverage.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Existing tests.

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM (Pending CI).

cc @HyukjinKwon

**Comment by dongjoon-hyun** [comment]
Merged to master for Apache Spark 3.3.

**Review by HyukjinKwon — COMMENTED** [review]
LGTM2

**Comment by zero323** [comment]
Thanks!

**Pull request closed without merging**
