### PR TITLE
SPARK-33686: Spark SQL unrecognized `db.tbl`

### PR DESCRIPTION
**Pull request by StefanXiepj**
### What changes were proposed in this pull request?

In this PR, if somebody created table like this:
```
create table `bigdata_db.test_spark_33686` (c1 int);
```
it's mean db name is `bigdata_db`, table name is `test_spark_33686`, but current version don't support it and throws exception like:
```
spark-sql> create table `bigdata_db.test_spark_33686` (c1 int);
Error in query: `bigdata_db.test_spark_33686` is not a valid name for tables/databases. Valid names only contain alphabet characters, numbers and _.;
```
we should support it.

### Why are the changes needed?

This is more relaxed and friendly syntax support.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

add new tests

### CODE REVIEW

**Comment by srowen** [comment]
If you back-tick-quote it, then you are not specifying a DB and table name, right? you're just specifying a table name, and the error is correct. Just don't quote it, right?

**Comment by StefanXiepj** [comment]
> If you back-tick-quote it, then you are not specifying a DB and table name, right? you're just specifying a table name, and the error is correct. Just don't quote it, right?

thx for your report. We have a lot of tasks about hive sql, when migrating it to spark sql, we found we can't, but hive support it, if Spark also supports it, it will be easier for users to use Spark.

**Comment by StefanXiepj** [comment]
@cloud-fan Could you review this PR , thanks.

**Comment by cloud-fan** [comment]
I don't think spark can support it, as we may have catalog implementations that support table name with dot, and this change will break it.

**Comment by StefanXiepj** [comment]
> I don't think spark can support it, as we may have catalog implementations that support table name with dot, and this change will break it.

I am glad to receive your reply.  emm... i have some questions need your help. spark support table name with dot,  Could you give me some examples, it is better for me to understand this question.

**Comment by cloud-fan** [comment]
We have `TableCatalog` now, and the implementation can accept any table name as it wants.

That said, I think it's OK to do it as a Hive-catalog-specific feature, but not at the parser side.

**Comment by StefanXiepj** [comment]
> We have `TableCatalog` now, and the implementation can accept any table name as it wants.
> 
> That said, I think it's OK to do it as a Hive-catalog-specific feature, but not at the parser side.

yeah, this is just for hive catalog, my purpose is to better migrate tasks from hive to spark. I like Spark, but we hive many tasks running on hive, we want to migrate it. I will move it from parser side to hive-catalog, have you got anything special in mind?

**Comment by cloud-fan** [comment]
`SessionCatalog` is a wrapper of the hive catalog and the name validation is done there. You can try to add this feature there.

**Comment by StefanXiepj** [comment]
> `SessionCatalog` is a wrapper of the hive catalog and the name validation is done there. You can try to add this feature there.

Ok, thanks very much, i will do it.

**Pull request closed without merging**
