### PR TITLE
[SPARK-3723] [MLlib] Adding instrumentation to random forests

### PR DESCRIPTION
**Pull request by smurching**
## What changes were proposed in this pull request?

In RandomForest.run(), added instrumentation for the number of node groups, along with the min, max, and average number of nodes per group.

Also fixed a typo in BaggedPoint.scala documentation.
## How was this patch tested?

Tested by running RandomForestClassifierSuite, checking the test output manually to make sure instrumentation information was present and reasonable.

### CODE REVIEW

**Comment by mengxr** [comment]
ok to test

**Comment by smurching** [comment]
Does it make sense to only perform instrumentation-related computations (i.e. updating the max/min nodes per group) if the instrumentation argument to RandomForest.run (instr) is not None? This isn't checked for in the current implementation.

**Comment by jkbradley** [comment]
Sorry for the long delay!  Whenever you get a chance to update this, it'd be nice to log this info via the Instrumentation class, rather than logInfo.

**Comment by HyukjinKwon** [comment]
Hi @smurching, is this still active?

**Pull request closed without merging**
