### PR TITLE
[SPARK-17023][BUILD] Upgrade to Kafka 0.10.0.1 release

### PR DESCRIPTION
**Pull request by lresende**
## What changes were proposed in this pull request?

Update Kafka streaming connector to use Kafka 0.10.0.1 release
## How was this patch tested?

Tested via Spark unit and integration tests

### CODE REVIEW

**Comment by lresende** [comment]
Jenkins test this please

**Comment by srowen** [comment]
I think that's fine, but is there any particular thing this fixes?

**Comment by lresende** [comment]
Couple of [bugs](https://archive.apache.org/dist/kafka/0.10.0.1/RELEASE_NOTES.html) seemed interesting to Spark, also good to maintain dependency currency similar to what we have been doing with kafka 0.8x

**Comment by koeninger** [comment]
Did you actually test this against a production sized workload?

As Sean said, probably fine, but i'm curious what bugs you think are especially relevant to the spark connector.

**Comment by srowen** [comment]
I'm going to merge to master/2.0 because it's a sub-maintenance release with no apparent behavior change, so should be fine regardless of whether a fix affects this project

**Pull request closed without merging**
