### PR TITLE
[MINOR][DOC] updated some grammar and a missed period in the tuning doc

### PR DESCRIPTION
**Pull request by dwsmith1983**
### What changes were proposed in this pull request?

I changed some grammatical issues in the documentation. One potential change could be debatable though so please take a look.
https://spark.apache.org/docs/latest/tuning.html

### Why are the changes needed?

Some grammatical mistakes in the documentation.

### Does this PR introduce _any_ user-facing change?

Yes, this corrects some issues in documentation related to Tuning Spark. The following changes were made
Check if there are too many garbage collections by collecting GC stats. If a full GC is invoked multiple times ~~for~~
  before a task completes, it means that there isn't enough memory available for executing tasks.
with `-XX:G1HeapRegionSize`. (added missing period).
we can estimate the size of Eden to be `4*3*128MiB`. (added the to estimate the size--this one I guess debatable)

### How was this patch tested?

No tests added as this was markdown documentation for the user facing page.

### CODE REVIEW

**Review by itholic — APPROVED** [review]
It would be great if the screen-capture for generated documentation is attached to the PR description for documentation work, but I think it's not necessary for this case since the change is small.

**Comment by dwsmith1983** [comment]
> It would be great if the screen-capture for generated documentation is attached to the PR description for documentation work, but I think it's not necessary for this case since the change is small.

I can add it. I was reading over this doc which is why I noticed them. Just a render markdown screenshot or the text file? Or side by side? @itholic

**Review by srowen — APPROVED** [review]
This is fine, but fairly trivial - let's do one big PR with many docs if going to do this

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
