### PR TITLE
[SPARK-7584] [MLLIB] User guide for VectorAssembler

### PR DESCRIPTION
**Pull request by mengxr**
This PR adds a section in the user guide for `VectorAssembler` with code examples in Python/Java/Scala. It also adds a unit test in Java.

@jkbradley

### CODE REVIEW

**Comment by jkbradley** [comment]
@mengxr  I don't see any problems, so LGTM.  One comment: Should the Java unit test be identical (or as close as possible) to the example, to help test it?

Caveat: I read but did not generate the docs.

**Comment by mengxr** [comment]
The Java unit test is the same as the Scala unit test, but the example code in the user guide is different. I thought about this difference. One reason is that the unit test is for API coverage while the example code is for hands-on. So it would be too much if we show, e.g., both sparse vectors and dense vectors in the example code. But it would be nice to have some level of similarity.

**Comment by jkbradley** [comment]
@mengxr Oh OK that makes sense.  LGTM

**Comment by mengxr** [comment]
Merged into master and branch-1.4.

**Pull request closed without merging**
