### PR TITLE
[SPARK-31465][SQL][DOCS][FOLLOW-UP] Document Literal in SQL Reference

### PR DESCRIPTION
**Pull request by huaxingao**
### What changes were proposed in this pull request?
Need to address a few more comments 

### Why are the changes needed?
Fix a few problems

### Does this PR introduce any user-facing change?
Yes

### How was this patch tested?
Manually build and check

### CODE REVIEW

**Comment by huaxingao** [comment]
@cloud-fan @maropu 
Sorry, your guys are too fast for me :)

**Comment by maropu** [comment]
Oops, I see. LGTM.

**Review by maropu — APPROVED** [review]

**Comment by maropu** [comment]
Since this fix is not related to the tests, I'll merge it. Thanks.

**Comment by maropu** [comment]
Merged to master/3.0.

**Pull request closed without merging**
