### PR TITLE
[SPARK-19329][SQL][BRANCH-2.1]Reading from or writing to a datasource table with a non pre-existing location should succeed

### PR DESCRIPTION
**Pull request by windpiger**
## What changes were proposed in this pull request?

This is a backport pr of https://github.com/apache/spark/pull/16672 into branch-2.1.

## How was this patch tested?
Existing tests.

### CODE REVIEW

**Comment by windpiger** [comment]
cc @gatorsmile

**Review by gatorsmile — APPROVED** [review]
LGTM

**Comment by gatorsmile** [comment]
Thanks! Merging to 2.1.

**Comment by gatorsmile** [comment]
@windpiger Could you please close it? Thanks!

**Pull request closed without merging**
