### PR TITLE
[ML] modify `validateParams` method of  `org.apache.spark.ml.clustering.LDA.scala` file, change  docConcentration values from  >= 0 to >=1

### PR DESCRIPTION
**Pull request by endymecy**
change 285 and 296 line, modify "getTopicConcentration >= 0" to "getTopicConcentration >= 1"

### CODE REVIEW

**Comment by endymecy** [comment]
For EM optimizer, docConcentration values must be >= 1,so "getTopicConcentration >= 1" should be right.

**Comment by mengxr** [comment]
@endymecy Could you update the PR title to make it more specific?

**Comment by mengxr** [comment]
ok to test

**Comment by srowen** [comment]
@endymecy your title and description are basically a repeat of the diff itself, in English. This is redundant. What is the motivation for the change? that's what you should set out in the description. Normally we'd ask for a JIRA for a functional change.

**Comment by jkbradley** [comment]
One more thing: The checks should actually ensure that docConcentration and topicConcentration for EM are > 1.0 (strictly greater).  Could you please make that update too?

**Comment by rxin** [comment]
Thanks for the pull request. I'm going through a list of pull requests to cut them down since the sheer number is breaking some of the tooling we have. Due to lack of activity on this pull request, I'm going to push a commit to close it. Feel free to reopen it or create a new one. We can also continue the discussion on the JIRA ticket.

**Pull request closed without merging**
