### PR TITLE
[SPARK-26219][CORE][branch-2.4] Executor summary should get updated for failure jobs in the history server UI

### PR DESCRIPTION
**Pull request by shahidki31**
## What changes were proposed in this pull request?
Back port the commit https://github.com/apache/spark/pull/23181 into Spark2.4 branch

## How was this patch tested?
Added UT

### CODE REVIEW

**Comment by shahidki31** [comment]
Jenkins, test this please

**Comment by shahidki31** [comment]
cc @vanzin . Kindly review

**Review by srowen — APPROVED** [review]

**Comment by vanzin** [comment]
Merging to 2.4. Please close the PR manually.

**Comment by shahidki31** [comment]
Thanks a lot @vanzin @srowen

**Pull request closed without merging**
