### PR TITLE
[WIP] [SPARK-12177] [STREAMING] Update KafkaDStreams to new Kafka 0.9 Consu…

### PR DESCRIPTION
**Pull request by nikit-os**
…mer API

### CODE REVIEW

**Comment by syepes** [comment]
+1

**Comment by markgrover** [comment]
Nikita, since we are still working on this, could you please mark this PR as [WIP] in the title so no one gets confused? Thanks!

**Comment by markgrover** [comment]
Hi @nikit-os, I have made a bunch of more changes in my personal branch at https://github.com/markgrover/spark/tree/kafka09-integration and some WIP changes for the python implementation at https://github.com/markgrover/spark/tree/kafka09-integration-python.

For now, I want to drive forward the Java/Scala and get feedback from the community. To make that easier, I would love to file a separate pull request that will be based off your original PR (i.e. this pull request). My desire is not take credit away from you, in fact, I will keep the history in tact, and explicitly mention that you have contributed a good chunk of this work but I don't want the logistical overhead of having to issue you a pull request to your branch, every time I want to update this pull request.

Would it be ok if I create a new pull request, that's a super set of, and supersedes this pull request?

**Comment by nikit-os** [comment]
Hi, @markgrover! 

Yes, I am not against new PR and closing this. Thank you!

**Comment by markgrover** [comment]
Thanks @nikit-os https://github.com/apache/spark/pull/10953 now supersedes this.

**Pull request closed without merging**
