### PR TITLE
[SPARK-13126] fix the right margin of history page.

### PR DESCRIPTION
**Pull request by zhuoliu**
The right margin of the history page is little bit off. A simple fix for that issue.

### CODE REVIEW

**Comment by ajbozarth** [comment]
Can you post a screenshot?

**Comment by zhuoliu** [comment]
history-margin
Sure.

**Comment by ajbozarth** [comment]
It looks a bit off to me when I make the window wider
page_width_fixed

**Comment by andrewor14** [comment]
ok to test

**Comment by andrewor14** [comment]
@zhuoliu is your screenshot before or after? Can you post both of them so we can compare?

**Comment by ajbozarth** [comment]
@andrewor14 I posted this before in the jira: 
page_width

**Comment by zhuoliu** [comment]
Hi @ajbozarth , the screenshot you pasted is a little different from mine since your date and app-Id are wrapped into two lines while there is still lots of space on the right side. 

In my test, when you drag your browser to be too wide, there do exist white space on the right side.
Would be happy if we can come up with a better solution than disabling the "row-fluid". 
Thanks.

**Comment by ajbozarth** [comment]
Looked through all 4500 results in my history server (glad it was that short) and found this guy:
width_long_name
Seems that DataTables formats for the entire table not just the currently visible. I think we should change it if possible, but it's a problem irrelevant to this particular fix.

So LGTM and I'll file a Jira on the other issue.

**Comment by ajbozarth** [comment]
Jenkins has been giving me problems too. Jenkins retest this please.

**Comment by ajbozarth** [comment]
@tgravescs also a fix on the DataTables addition if you want to take a look

**Comment by tgravescs** [comment]
+1

**Pull request closed without merging**
