### PR TITLE
[#SPARK-16897] Refactored the code and changed the var to val

### PR DESCRIPTION
**Pull request by shiv4nsh**
## What changes were proposed in this pull request?

 Updated the documentation with the correct use of val instead of var
## How was this patch tested?

 By Running test cases and generating the docs

screenshot from 2016-08-04 18-00-49

### CODE REVIEW

**Comment by srowen** [comment]
This is too trivial to make a change for. Yes it is better to write val but not worth everyone's time to process single line changes like this that are almost a no op

**Comment by shiv4nsh** [comment]
@srowen : I found out that var is used here and then I got confused that why as there is no need , hence I made this pull request. If you feel that this can't be merged. Let me know I will close the PR

**Comment by shiv4nsh** [comment]
@srowen : One more thing I have found in the docs that some of the links are broken and they are not pointing to the place that they should point. So should I make the change for that too or can that be skipped ! 
Please share your thoughts ! Thanks !

**Comment by srowen** [comment]
Yes, this is below the threshold. We want to encourage focus on slightly more meaningful changes because it takes probably a person-hour to look at any change and there is so much demand. Your second point sounds unrelated. Before opening a change, please ask on user@ to confirm if it's a problem -- because I think maybe you're talking about markdown not HTML.

**Comment by shiv4nsh** [comment]
@srowen : But do change it by yourself if you have time , because that was a bit confusing for a new user because of the point at which it is present

**Comment by srowen** [comment]
This should be closed, please.

**Pull request closed without merging**
