### PR TITLE
[SPARK-40726][DOCS] Supplement undocumented orc configurations in documentation

### PR DESCRIPTION
**Pull request by dcoliversun**
### What changes were proposed in this pull request?

This PR aims to supplement undocumented orc configurations in documentation.

### Why are the changes needed?

Help users to confirm configurations through documentation instead of code.

### Does this PR introduce _any_ user-facing change?

Yes, more configurations in documentations.

### How was this patch tested?

Pass the GA.

### CODE REVIEW

**Comment by dcoliversun** [comment]
cc @dongjoon-hyun @srowen 
It would be good if you have a time to review

**Review by srowen — APPROVED** [review]

**Comment by srowen** [comment]
Merged to master

**Comment by dcoliversun** [comment]
Thanks for @srowen review

**Review by dongjoon-hyun — COMMENTED** [review]
+1, late LGTM. Thank you.

**Pull request closed without merging**
