### PR TITLE
[SPARK-21164] [SQL] Remove isTableSample from Sample and isGenerated from Alias and AttributeReference

### PR DESCRIPTION
**Pull request by gatorsmile**
## What changes were proposed in this pull request?
`isTableSample` and `isGenerated ` were introduced for SQL Generation respectively by https://github.com/apache/spark/pull/11148 and https://github.com/apache/spark/pull/11050

Since SQL Generation is removed, we do not need to keep `isTableSample`.

## How was this patch tested?
The existing test cases

### CODE REVIEW

**Comment by hvanhovell** [comment]
Shouldn't we remove all the `isGenerated` stuff then? See `Alias` for example.

**Comment by gatorsmile** [comment]
@hvanhovell Yes! Let me remove them in this PR too. : )

**Comment by hvanhovell** [comment]
LGTM - pending jenkins.

**Comment by gatorsmile** [comment]
Thanks! Merging to master.

**Pull request closed without merging**
