### PR TITLE
[SPARK-39868][CORE][TESTS] StageFailed event should attach with the root cause

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr follow https://github.com/apache/spark/pull/37245
StageFailed event should attach with the root cause

### Why are the changes needed?
**It may be a good way for users to know the reason of failure.**

By carefully investigating the issue: https://issues.apache.org/jira/browse/SPARK-39622,
I found the root cause of test failure: StageFailed don't attach the failed reason from executor.
when OutputCommitCoordinator execute 'taskCompleted', the 'reason' is ignored.

Scenario 1: receive TaskSetFailed (Success)
> InsertIntoHadoopFsRelationCommand
> FileFormatWriter.write
> _**handleTaskSetFailed**_ (**attach root cause**)
> abortStage
> failJobAndIndependentStages
> SparkListenerJobEnd

Scenario 1: receive StageFailed (Fail)
> InsertIntoHadoopFsRelationCommand
> FileFormatWriter.write
> _**handleStageFailed**_ (**don't attach root cause**)
> abortStage
> failJobAndIndependentStages
> SparkListenerJobEnd

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Manual run UT & Pass GitHub Actions

### CODE REVIEW

**Comment by panbingkun** [comment]
CC @LuciferYang

**Comment by LuciferYang** [comment]
cc @HyukjinKwon

**Review by HyukjinKwon — APPROVED** [review]

**Comment by LuciferYang** [comment]
@panbingkun `OutputCommitCoordinatorIntegrationSuite` test failed,  seems related to this pr

**Comment by panbingkun** [comment]
> @panbingkun `OutputCommitCoordinatorIntegrationSuite` test failed,  seems related to this pr

okay, I'll fix it later

**Comment by panbingkun** [comment]
> @panbingkun `OutputCommitCoordinatorIntegrationSuite` test failed, seems related to this pr

Done

**Review by LuciferYang — APPROVED** [review]
LGTM +1

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
