### PR TITLE
[SPARK-16318][SQL] Implement all remaining xpath functions (branch-2.0)

### PR DESCRIPTION
**Pull request by petermaxlee**
## What changes were proposed in this pull request?

This patch implements all remaining xpath functions that Hive supports and not natively supported in Spark: xpath_int, xpath_short, xpath_long, xpath_float, xpath_double, xpath_string, and xpath.

This is based on https://github.com/apache/spark/pull/13991 but for branch-2.0.
## How was this patch tested?

Added unit tests and end-to-end tests.

### CODE REVIEW

**Comment by petermaxlee** [comment]
cc @cloud-fan

**Comment by cloud-fan** [comment]
LGTM, pending jenkins

**Comment by cloud-fan** [comment]
retest this please

**Comment by cloud-fan** [comment]
looks like we also need to backport the improvement to `checkEvaluation`

**Comment by petermaxlee** [comment]
I've added the checkEvaluation fix here too.

**Comment by rxin** [comment]
Merging in branch-2.0.

**Comment by rxin** [comment]
@petermaxlee can you close this?

**Pull request closed without merging**
