### PR TITLE
[MINOR][SQL] Clean up ObjectProducerExec operators

### PR DESCRIPTION
**Pull request by jaceklaskowski**
## What changes were proposed in this pull request?

Cleaned up (removed) code duplication in `ObjectProducerExec` operators so they use the trait's methods.

## How was this patch tested?

Local build. Waiting for Jenkins.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Hi, @jaceklaskowski . Could you make a JIRA issue for this?

**Comment by srowen** [comment]
A JIRA won't hurt but this looks like just a code cleanup; there should be no functional change.

**Comment by jaceklaskowski** [comment]
@dongjoon-hyun When I created the PR I thought to make a JIRA issue, but it's just a simple refactoring (code cleanup) so I don't think it begs for one.

**Comment by dongjoon-hyun** [comment]
Okay. Then, I leave this PR to the other reviews.

**Comment by HyukjinKwon** [comment]
I'm fine either way. I also prefer to have a JIRA in general for trackability, for instance, backporting stuff. I think this PR is boundary between no JIRA and JIRA :-).

**Comment by srowen** [comment]
Merged to master. I think it's fine.

**Pull request closed without merging**
