### PR TITLE
[SPARK-41074][DOC] Add option `--upgrade` in dependency installation command

### PR DESCRIPTION
**Pull request by zhengruifeng**
### What changes were proposed in this pull request?
Add option `--upgrade` in dependency installation command

### Why are the changes needed?

for the packages whose version are not pinned, `pip install -r dev/requirements.txt` can not upgrade them

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
manually check

### CODE REVIEW

**Comment by zhengruifeng** [comment]
cc @HyukjinKwon @Yikun

**Review by LuciferYang — APPROVED** [review]
+1, LGTM

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by zhengruifeng** [comment]
thank you @HyukjinKwon @LuciferYang

**Pull request closed without merging**
