### PR TITLE
[SPARK-20601][ML] Python API for Constrained Logistic Regression

### PR DESCRIPTION
**Pull request by yanboliang**
## What changes were proposed in this pull request?
Python API for Constrained Logistic Regression based on #17922 , thanks for the original contribution from @zero323 .

## How was this patch tested?
Unit tests.

### CODE REVIEW

**Review by WeichenXu123 — COMMENTED** [review]
LGTM.

**Comment by yanboliang** [comment]
Merged into master, thanks for reviewing.

**Comment by BryanCutler** [comment]
@yanboliang , I'm not sure why but this PR did not make it onto the JIRA.  I've noticed it has happened a couple times elsewhere too, maybe some script is broken?  Just fyi, if you want to add a link manually.

**Comment by yanboliang** [comment]
@BryanCutler I linked this PR to the JIRA manually. Thanks for remind.

**Comment by zero323** [comment]
Thanks @yanboliang

**Pull request closed without merging**
