### PR TITLE
[SPARK-15932][SQL][DOC] document the contract of encoder serializer expressions

### PR DESCRIPTION
**Pull request by cloud-fan**
## What changes were proposed in this pull request?

In our encoder framework, we imply that serializer expressions should use `BoundReference` to refer to the input object, and a lot of codes depend on this contract(e.g. ExpressionEncoder.tuple).  This PR adds some document and assert in `ExpressionEncoder` to make it clearer.
## How was this patch tested?

existing tests

### CODE REVIEW

**Comment by cloud-fan** [comment]
cc @hvanhovell @liancheng @clockfly

**Comment by liancheng** [comment]
LGTM

**Comment by rxin** [comment]
Please create a JIRA ticket.

**Comment by cloud-fan** [comment]
JIRA is down, will create a ticket later.

**Comment by hvanhovell** [comment]
LGTM

**Comment by rxin** [comment]
Merging in master/2.0.

**Pull request closed without merging**
