### PR TITLE
[SPARK-31503][SQL][2.4] fix the SQL string of the TRIM functions

### PR DESCRIPTION
**Pull request by cloud-fan**
backport https://github.com/apache/spark/pull/28281 to 2.4

This backport has one difference: there is no `EXTRACT(... FROM ...)` SQL syntax in 2.4, so this PR just uses the common function call syntax.

### CODE REVIEW

**Comment by cloud-fan** [comment]
cc @dongjoon-hyun

**Review by HyukjinKwon — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Merged to branch-2.4. Thank you, @cloud-fan and @HyukjinKwon .
cc @holdenk since she is a release manager for 2.4.6.

**Comment by dongjoon-hyun** [comment]
Oops. I'm late. :)

**Comment by dongjoon-hyun** [comment]
Oh, this one seems to out of sync too. I cannot see the merged commit in GitHub branch-2.4
Screen Shot 2020-04-22 at 9 33 20 AM

**Comment by dongjoon-hyun** [comment]
Fixed.

**Pull request closed without merging**
