### PR TITLE
[WIP][SPARK-35253][BUILD][SQL] Upgrade Janino from 3.0.16 to 3.1.3

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?

This PR proposes to upgrade Janino from 3.0.16 to 3.1.3 because the 3.0.x line is deprecated ([janino-change-log](http://janino-compiler.github.io/janino/changelog.html)).

### Why are the changes needed?
 the Janino 3.0.x line is deprecated

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass the Jenkins or GitHub Action

### CODE REVIEW

**Comment by LuciferYang** [comment]
I found  SPARK-31214 (https://github.com/apache/spark/pull/27860) was reversed, I'm not sure if we need to upgrade this lib,  there are still some UT failures now.

**Comment by LuciferYang** [comment]
It seems that SPARK-32640 has not been solved with  Janino 3.1.3

**Comment by maropu** [comment]
Hi, @LuciferYang. Since janino-3.1.3 has some critical issues, I think spark cannot land on it. So, I'm fixing janino these issues, e.g.,
 - https://github.com/janino-compiler/janino/pull/145
 - https://github.com/janino-compiler/janino/pull/146

**Comment by LuciferYang** [comment]
@maropu Thank you for your feedback, maybe we need to wait until the next version of Janino to upgrade it

**Comment by LuciferYang** [comment]
@maropu After janino-compiler/janino#145 and janino-compiler/janino#146 merged,  I will try to use the snapshot  version to verify whether there are other blocking issue

**Comment by LuciferYang** [comment]
close this because SPARK-35253

**Pull request closed without merging**
