### PR TITLE
[BUILD] Closing stale PRs

### PR DESCRIPTION
**Pull request by srowen**
Closes #15303
Closes #15078
Closes #15080
Closes #15135
Closes #14565
Closes #12355
Closes #15404

### CODE REVIEW

**Comment by rxin** [comment]
Merging in master.

**Comment by rxin** [comment]
Actually I'm getting error when merging. Not sure why.

**Comment by vanzin** [comment]
Let me try...

**Comment by vanzin** [comment]
Done. I had to temporarily add `--allow-empty` to the `git commit` command in `./dev/merge_spark_pr.py`. Perhaps we should fix the script to always add that option (or have some command line switch for it).

**Comment by srowen** [comment]
Yes you have to add `--allow-empty` temporarily. I hadn't added it to the script because usually we don't want to allow an empty commit. Yes if this becomes pretty regular, probably worth some kind of check and prompt during the script that would allow this to proceed without temporarily changing the script.

**Pull request closed without merging**
