### PR TITLE
[SPARK-10172][core]disable sort in HistoryServer webUI

### PR DESCRIPTION
**Pull request by josiahsams**
This pull request is to address the JIRA SPARK-10172 (History Server web UI gets messed up when sorting on any column). 
The content of the table gets messed up due to the rowspan attribute of the table data(cell) during sorting. 
The current table sort library used in SparkUI (sorttable.js) doesn't support/handle cells(td) with rowspans.
The fix will disable the table sort in the web UI, when there are jobs listed with multiple attempts.

### CODE REVIEW

**Comment by andrewor14** [comment]
@vanzin could you take a look?

**Comment by vanzin** [comment]
@josiahsams sorry for the delay. Do you have a screenshot of this? From the code it seems like the app information will be repeated, and there will be no visual aid indicating that the different attempts belong to the same app (which is what the rowspan did).

I'm not sure how the sorting is done on the javascript side, but is there a rowspan-aware sort that could be used instead?

**Comment by josiahsams** [comment]
@vanzin , As you rightly pointed out, I have removed the row level grouping (rowspan) based on the Attempt ID, as the current javascript library used for sorting table "sorttable.js" messes up the table data during sorting. For that matter, as far as I know, no stable table sort logic out there that can support rowspan. 

But we can definitely try out workarounds like, creating inner tables inside the cells for each column and make that table data non-sortable. This will call for more code  changes but will result in having more non-sortable fields.

So in order to keep things simple, I removed "rowspan" from the equation, and made the "App ID" field to show values(links will be different based on the attempt ID) for every attempt made.

**Comment by vanzin** [comment]
Hi @josiahsams,

I played a little with this and it seems like it would be rather easy to get both rowspan and sorting working using jQuery's table sorter plugin: https://mottie.github.io/tablesorter/docs/index.html

After I added the necessary code, all I needed to do was add `class="tablesorter-childRow"` to the child rows and the plugin sorts things correctly.

Would you be willing to take a stab at using that to sort the table instead? I really don't like losing the link between the app and its attempts.

There might be some added complexity to do things correctly; for example, if I understand correctly, my quick hack only sorts based on the most recent attempt's information, so for example when sorting based on start time, the sort order wouldn't be correct.

Another approach is to remove sorting altogether. Since sorting is based on just the current page, and the current page doesn't really have that many entries, sorting isn't super useful to start with.

**Comment by josiahsams** [comment]
@vanzin, I tried tablesorter jquery plugin and figured out there are no way to sort the childrows out of the box. Still exploring all the customization. In this approach, I'm suspecting lot of code changes and new scripts and css additions as the table creation in Spark UI is done in a generic way. 

But we need to take a decision whether its worth putting that much effort for this issue (or) simply make the table non-sortable(only in case of multiple attempts) as suggested by you. 

Waiting for your reply for this one.

**Comment by vanzin** [comment]
I'm wondering if there's much benefit from having sorting at all in this table, regardless of multiple attempts or not. There are limited entries per page (20 I think), which is not bad. Sorting is not maintained across pages; and is not really aware that there are multiple pages. So it sorts only the current list, not the complete list of applications. The behavior ends up being a little weird.

Personally I wouldn't miss sorting in the current implementation. It might be worth it to refactor this page so that it's more dynamic instead of relying on the HTML code embedded in Scala, and then have better sorting, but that's a much bigger effort.

**Comment by josiahsams** [comment]
I pushed a wrong commit and I'm reopening the pull request.

**Comment by vanzin** [comment]
ok to test

**Comment by vanzin** [comment]
LGTM after tests. Could you update the title and description of the PR to reflect the new changes?

**Comment by josiahsams** [comment]
Title & Description changed.

**Comment by vanzin** [comment]
great, merging (master, 1.5 & 1.4).

**Comment by mengxr** [comment]
@josiahsams @vanzin I reverted the changes to branch-1.4 because it doesn't compile. I re-opened the JIRA for 1.4.

**Comment by vanzin** [comment]
oh sorry about that. forgot to monitor the 1.4 builds after I merged.

**Pull request closed without merging**
