### PR TITLE
[SPARK-16020][SQL]Fix complete mode aggregation with console sink

### PR DESCRIPTION
**Pull request by zsxwing**
## What changes were proposed in this pull request?

We cannot use `limit` on DataFrame in ConsoleSink because it will use a wrong planner. This PR just collects `DataFrame` and calls `show` on a batch DataFrame based on the result. This is fine since ConsoleSink is only for debugging.
## How was this patch tested?

Manually confirmed ConsoleSink now works with complete mode aggregation.

### CODE REVIEW

**Comment by marmbrus** [comment]
LGTM and we should merge before the RC.

How hard to add a test?  You could redirect stdout temporarily?

**Comment by marmbrus** [comment]
There are examples in `quietly`.

**Comment by zsxwing** [comment]
Added a test.

**Comment by zsxwing** [comment]
The added test passed. I'm going to merge it into master and 2.0 to make sure it's in rc1.

**Comment by holdenk** [comment]
Would it make sense to follow up with a warning in ConsoleSink that it is only for debugging and collects the entire microbatch to the driver? This seems like some people might use it for logging inside of a production application and have some unexpected surprise. Some people might assume numRows restriction is applied upstream of the collect.

**Comment by zsxwing** [comment]
@holdenk it will be documented here: https://github.com/apache/spark/pull/13945/files#diff-21245da8f8dbfef6401c5500f559f0bcR531

**Comment by holdenk** [comment]
@zsxwing great I've left the similar comment on the that PR

**Pull request closed without merging**
