### PR TITLE
[SPARK-10326] [yarn] Fix app submission on windows.

### PR DESCRIPTION
**Pull request by vanzin**

### CODE REVIEW

**Comment by rxin** [comment]
Jenkins, retest this please.

**Comment by vanzin** [comment]
retest this please

**Comment by andrewor14** [comment]
@vanzin was this a regression from 1.4 or 1.3?

**Comment by andrewor14** [comment]
In case others are wondering where this line comes from: #8053. LGTM feel free to merge it.

**Comment by rxin** [comment]
I've merged this. @vanzin can you close the pull request?

**Comment by vanzin** [comment]
(I think Andrew deleted his question, but this is not a problem in 1.4 nor 1.3.)

**Comment by jamartinh** [comment]
I have tested it on windows with spark 1.5.0 and 1.5.1 and the problem still remains.

**Pull request closed without merging**
