### PR TITLE
[SPARK-44638][SQL][TESTS] Add test for Char/Varchar in JDBC custom options

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

Char/Varchar in JDBC `customSchema` option once broke in Spark 3.1 ~ 3.4, but seems to be restored in master by some recent works in the JDBC area, this PR add a test to cover.

See report in SPARK-44638

### Why are the changes needed?

test cov

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

test added

### Was this patch authored or co-authored using generative AI tooling?

no

### CODE REVIEW

**Comment by yaooqinn** [comment]
cc @cloud-fan

**Review by cloud-fan — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

Thank you, @yaooqinn and @cloud-fan .

Merged to master.

**Comment by dongjoon-hyun** [comment]
Although we merged this test coverage and https://github.com/apache/spark/pull/47550 , is this feature still broken in branch-3.4, @yaooqinn ? 

Are we going to have another PR for branch-3.4 with the same JIRA ID, SPARK-44638?

**Comment by yaooqinn** [comment]
I will test 3.4 in https://github.com/apache/spark/pull/47558 first. If it fails, I will fix it

**Comment by dongjoon-hyun** [comment]
Thank you, @yaooqinn !

**Pull request closed without merging**
