### PR TITLE
[SPARKR][BUILD] AppVeyor change to latest R version

### PR DESCRIPTION
**Pull request by felixcheung**
## What changes were proposed in this pull request?

R version update

## How was this patch tested?

AppVeyor

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]
LGTM if the tests pass

**Comment by HyukjinKwon** [comment]
@felixcheung, BTW, I think optionally we could also consider setting it 3.4.0 a bit more conservatively for now. There was a rather minor problem for using the latest version (see https://github.com/apache/spark/pull/15709) due to sync'ing issue of R version, which was fixed within few hours outside Spark IIRC. Either way is fine to me.

**Comment by felixcheung** [comment]
It's the latest but it's not new - 3.4.1 was release a month ago. I think there shouldn't be the sync problem.

**Comment by HyukjinKwon** [comment]
Ah, I meant, the PR I linked actually describes a case when we were using 3.3.1 but it was broken after 3.3.2 release. The reason was, 3.3.2 was released but 3.3.2 for Windows was not synced (but was synced after few hours).

The script we are using checks if it is latest or not and adds `../old/..` part to build the download link correctly. So..

- Check given version is latest via https://rversions.r-pkg.org/r-release
  - If so, don't add `../old/..`, e.g., https://cran.r-project.org/bin/windows/base/R-3.3.1-win.exe
  - if not, add `../old/..`,  e.g., https://cran.r-project.org/bin/windows/base/old/3.3.1/R-3.3.1-win.exe

But, the issue was, https://rversions.r-pkg.org/r-release gives 3.3.2 after the release but 3.3.1 for WIndows was not in old repo as the latest.

**Comment by HyukjinKwon** [comment]
To cut this short, it was ...

- 3.3.2 release for Linux only
- Gives the latest as 3.3.2 and the download link for 3.3.1 becomes `windows/base/old`
- 3.3.2 release for WIndows yet
- 3.3.1 is still not in `windows/base/old` but `windows/base`
- Failed to download

**Comment by HyukjinKwon** [comment]
@felixcheung, actually, should we try to replace `http://rversions.r-pkg.org/r-release` in line 29 to `http://rversions.r-pkg.org/r-release-win`?  I referred https://github.com/krlmlr/r-appveyor/commit/01ce943929993bbf27facd2cdc20ae2e03808eb4

**Comment by HyukjinKwon** [comment]
Will try to open a separate PR. LGTM.

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by felixcheung** [comment]
Right, this PR isn't changing how you have made the version to test with sticky - we won't still pick up the latest automatically, which is fine for now.

But we should bump (manually) to the later/latest version in one of the test matrix to make sure it works.

**Comment by HyukjinKwon** [comment]
I agree this PR should be okay alone, which fixes what it targets for now and I realised my suggestion is rather an extra bit. I opened another one for replacing `r-release` to `r-release-win`.

**Pull request closed without merging**
