### PR TITLE
[SPARK-38052][SQL] Refactor UnsafeRow#isFixedLength and UnsafeRow#isMutable use looping

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
Methods UnsafeRow#isFixedLength and UnsafeRow#isMutable use tail recursion now , this pr can refactor with looping, which will be considerably faster.

### Why are the changes needed?
Replace tail recursion with looping.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass GA

### CODE REVIEW

**Comment by LuciferYang** [comment]
Seeing the code here and changed it casually. I'm not sure if it's really valuable

**Comment by hvanhovell** [comment]
@LuciferYang do you have any benchmark for this? The only recursion I see is the unpacking of the UDT.

**Comment by LuciferYang** [comment]
Let me make one

**Comment by LuciferYang** [comment]
Let me make one

**Comment by LuciferYang** [comment]
The following two methods are simulated and tested with nested objects:

I do a test for the following 2 methods:

```java 
// use loop
public static boolean isNumber1(Object o) {
        while (true) {
            if (o instanceof NestedObject) {
                o = ((NestedObject) o).innerValue();
                continue;
            }

            return o instanceof Number;
        }
    }

   // use recursion
    public static boolean isNumber2(Object o) {
        if(o instanceof NestedObject) {
            return isNumber2(((NestedObject) o).innerValue());
        }
        return o instanceof Number;
    }
```

The test code as follows:

``` scala
object LoopAndRecursionBenchmark extends BenchmarkBase {

  override def runBenchmarkSuite(mainArgs: Array[String]): Unit = {
    val valuesPerIteration = 10000;
    doTest(valuesPerIteration, create1LayerNestedObject(), 1)
    doTest(valuesPerIteration, create3LayerNestedObject(), 3)
    doTest(valuesPerIteration, create5LayerNestedObject(), 5)
  }

  def doTest(
      valuesPerIteration: Int, obj: NestedObject, layer: Int): Unit = {

    val benchmark = new Benchmark(
      s"Test loop and Recursion $layer",
      valuesPerIteration,
      output = output)

    benchmark.addCase("Use loop") { _: Int =>
      for (_ <- 0L until valuesPerIteration) {
        TestLoopUtils.isNumber1(obj)
      }
    }

    benchmark.addCase("Use Recursion") { _: Int =>
      for (_ <- 0L until valuesPerIteration) {
        TestLoopUtils.isNumber2(obj)
      }
    }
    benchmark.run()
  }

  def create1LayerNestedObject(): NestedObject = {
    new NestedObject(1)
  }

  def create3LayerNestedObject(): NestedObject = {
    new NestedObject(new NestedObject(new NestedObject(1)))
  }

  def create5LayerNestedObject(): NestedObject = {
    new NestedObject(new NestedObject(create3LayerNestedObject()))
  }
}

class NestedObject(inner: Any) {
  def innerValue(): Any = inner
}
```

**Comment by LuciferYang** [comment]
The bench result generate with GA:

```
OpenJDK 64-Bit Server VM 1.8.0_322-b06 on Linux 5.11.0-1027-azure
Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
Test loop and Recursion 1:                Best Time(ms)   Avg Time(ms)   Stdev(ms)    Rate(M/s)   Per Row(ns)   Relative
------------------------------------------------------------------------------------------------------------------------
Use loop                                              0              0           0        114.4           8.7       1.0X
Use Recursion                                         0              0           0        127.1           7.9       1.1X

OpenJDK 64-Bit Server VM 1.8.0_322-b06 on Linux 5.11.0-1027-azure
Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
Test loop and Recursion 3:                Best Time(ms)   Avg Time(ms)   Stdev(ms)    Rate(M/s)   Per Row(ns)   Relative
------------------------------------------------------------------------------------------------------------------------
Use loop                                              0              0           0        155.8           6.4       1.0X
Use Recursion                                         0              0           0         77.2          13.0       0.5X

OpenJDK 64-Bit Server VM 1.8.0_322-b06 on Linux 5.11.0-1027-azure
Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
Test loop and Recursion 5:                Best Time(ms)   Avg Time(ms)   Stdev(ms)    Rate(M/s)   Per Row(ns)   Relative
------------------------------------------------------------------------------------------------------------------------
Use loop                                              0              0           0        129.2           7.7       1.0X
Use Recursion                                         0              0           0         86.4          11.6       0.7X
```

**Comment by LuciferYang** [comment]
In x86 architecture, multi-layer nested recursion is slightly slower than loop, and there is no significant performance difference use Apple Silicon(Manual test on My mac with M1). @hvanhovell

**Comment by HyukjinKwon** [comment]
If there's no significant performance improve, I think we can just drop it. It's just about recursive UDTs, right?

**Comment by LuciferYang** [comment]
> If there's no significant performance improve, I think we can just drop it. It's just about recursive UDTs, right?

Yes, in terms of relative proportion, loop is 20% ~ 50% better than recursion, but the absolute value is relatively small, for example, from 40ns to 20ns.

**Pull request closed without merging**
