### PR TITLE
[SPARK-20720][WEB-UI]'Executor Summary' should show the exact number, 'Removed Executors' should display the specific number, in the Application Page

### PR DESCRIPTION
**Pull request by guoxiaolongzte**
## What changes were proposed in this pull request?

When the number of spark worker executors is large, if the specific number is displayed, will better help us to analyze and observe by spark ui.

Although this is a small improvement, but it is indeed very valuable.

After fix:
executor1

## How was this patch tested?

manual tests

Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Comment by guoxiaolongzte** [comment]
@srowen @ajbozarth
Help to review the code, thanks.

**Comment by ajbozarth** [comment]
If this would be useful I don't see any harm in adding it, its a pretty small change

**Comment by srowen** [comment]
Hm, but do we do this consistently in the UI? show "Thing (count)"? it needs to be uniform if it's changed.

**Comment by guoxiaolongzte** [comment]
We spark ui have two styles.

The first style is to display statistics separately, as follows:
first



The second style is displayed in the table header, with parentheses, as follows:
second


I am modifying this issue by using the second style.

**Comment by srowen** [comment]
I see. I think the first style exists to provide links that jump to running apps because it may be well below the fold if there are many workers. I think that can stay, even though the design of this little header is not great and wastes a lot of white space at the right.

I think it'd be nice to add (count) to all the tables of things in the UI, as I assume that's pretty easy to do, isn't obtrusive, and would make it more consistent. I suppose that goes for stages, tasks, etc. What do you think?

**Comment by guoxiaolongzte** [comment]
Yes, I agree with you. I will work on it.

**Comment by ajbozarth** [comment]
I like it, I think limiting this particular pr to updating the master ui is probably best for now, could you also update `WorkerPage.scala` as well since its part of the "Master UI"

**Comment by guoxiaolongzte** [comment]
@ajbozarth @srowen 
At present I have this branch code ui count test results:
1.master page by i fix, as follows:
master



2.job page , as follows:
job


3.stage page , as follows:
stage


4.task page, as follows:
task


5.work page, as follows:
work

**Comment by ajbozarth** [comment]
Thanks for checking @guoxiaolongzte looks like with this fix every table will now have a (count)

LGTM

**Review by srowen — APPROVED** [review]

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
