### PR TITLE
[SPARK-20751][SQL][FOLLOWUP] Add cot test in MathExpressionsSuite

### PR DESCRIPTION
**Pull request by wangyum**
## What changes were proposed in this pull request?

Add cot test in MathExpressionsSuite as https://github.com/apache/spark/pull/17999#issuecomment-302832794.

## How was this patch tested?

unit tests

### CODE REVIEW

**Comment by wangyum** [comment]
Jenkins, retest this please

**Comment by wzhfy** [comment]
It's a followup pr for [SPARK-20751](https://github.com/apache/spark/commit/bff021dfaf4b5c9ab84c71dad2a37f60907e32d6). Could you add a followup tag in the title?

**Review by maropu — APPROVED** [review]

**Review by gatorsmile — APPROVED** [review]
LGTM

**Comment by gatorsmile** [comment]
Thanks! Merging to master.

**Pull request closed without merging**
