### PR TITLE
[SPARK-36536][SQL] Use CAST for datetime in CSV/JSON by default

### PR DESCRIPTION
**Pull request by MaxGekk**
### What changes were proposed in this pull request?
In the PR, I propose to split the `dateFormat` and `timestampFormat` options in CSV/JSON datasources to:
- In write (`dateFormatInWrite`/`timestampFormatInWrite`). CSV/JSON datasource will use it in formatting of dates/timestamps. If an user doesn't initialise it, it will be set to a default value.
- In read (`dateFormatInRead`/`timestampFormatInRead`). The datasources will use it while parsing of input dates/timestamps strings. If an user doesn't set it, we will keep it as uninitialized (None), and use CAST to parse the input dates/timestamps strings.

### Why are the changes needed?
This should improve user experience with Spark SQL, and make the default parsing behavior more flexible.

### Does this PR introduce _any_ user-facing change?
Potentially, it can.

### How was this patch tested?
By existing test suites, and by new tests that are added to `JsonSuite` and to `CSVSuite`:
```
$ build/sbt "sql/test:testOnly *CSVLegacyTimeParserSuite"
$ build/sbt "sql/test:testOnly *JsonFunctionsSuite"
$ build/sbt "sql/test:testOnly *CSVv1Suite"
$ build/sbt "sql/test:testOnly *JsonV2Suite"
```

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
cc @cloud-fan FYI

**Comment by MaxGekk** [comment]
@HyukjinKwon @cloud-fan Could you take a look at this. At least, all existing tests passed.

**Review by cloud-fan — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
should we maybe update SQL migration guide?

**Comment by MaxGekk** [comment]
@HyukjinKwon This PR is a follow up of https://github.com/apache/spark/pull/33709 which affected partition values, for instance. I also plan to look at function with default pattern. So, I would write an item in the SQL migration guide once for all those related changes if you don't mind.

**Comment by HyukjinKwon** [comment]
+1

**Comment by MaxGekk** [comment]
Merging to master. Thanks to @cloud-fan @HyukjinKwon for review.

**Pull request closed without merging**
