### PR TITLE
[SPARK-43985][PROTOBUF] spark protobuf: fix enums as ints bug

### PR DESCRIPTION
**Pull request by justaparth**
### What changes were proposed in this pull request?
Currently, when deserializing protobufs with `enums.as.ints` set to true, repeated enum fields will raise an exception. This is because the UnsafeArrayData type (which is the array type for primitives) does not support the `.set` method, and we should instead use `.setInt`. 

### Why are the changes needed?
Fixes a bug in the current code.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Unit tests were added to highlight this use case.

### CODE REVIEW

**Comment by justaparth** [comment]
cc @rangadi @SandishKumarHN

**Comment by justaparth** [comment]
> LGTM. @justaparth do you need to update the descriptor file? Btw, with #41377, we don't need to.

ah good catch, i updated and added to the PR.

#41377  looks awesome, thanks for doing that!

**Comment by rangadi** [comment]
@gengliangwang, @LuciferYang could one of you merge this?

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
