### PR TITLE
[SPARK-42452][BUILD] Remove `hadoop-2` profile from Apache Spark 3.5.0

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr aims to remove `hadoop-2` profile from Apache Spark 3.5.0.

### Why are the changes needed?
Spark 3.4.0 no longer releases Hadoop2 binary distribtuion(SPARK-42447) and Hadoop 2 GitHub Action job already removed after SPARK-42447, we can remove `hadoop-2` profile from Apache Spark 3.5.0.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass GitHub Actions

### CODE REVIEW

**Comment by LuciferYang** [comment]
Test first,  need wait until 3.4 release at least

**Review by dongjoon-hyun — COMMENTED** [review]
Thank you, @LuciferYang .

**Comment by dongjoon-hyun** [comment]
Also, cc FYI, @sunchao

**Comment by bjornjorgensen** [comment]
> 

3.4.0 is uploaded to mirrors.

**Comment by LuciferYang** [comment]
> > Test first, need wait until 3.4 release at least
> 
> 3.4.0 is uploaded to mirrors.


I know, but let's wait for the official website update

**Comment by sunchao** [comment]
Personally I like this move, but not sure whether there are other users in the community that still depend on Hadoop 2.x. Has this been discussed before?

**Comment by bjornjorgensen** [comment]
> Personally I like this move, but not sure whether there are other users in the community that still depend on Hadoop 2.x. Has this been discussed before?

yes, like this one [Dropping Apache Spark Hadoop2 Binary Distribution?](https://lists.apache.org/thread/z4jdy9959b6zj9t726zl0zcrk4hzs0xs)

**Comment by sunchao** [comment]
Oh cool, it's good then. Forgot about this thread even though I replied on it ..

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM (from my side)

**Comment by sunchao** [comment]
Just sent an email to the community in case anyone still have concerns on this.

**Review by sunchao — APPROVED** [review]

**Review by bjornjorgensen — APPROVED** [review]

**Comment by LuciferYang** [comment]
friendly ping @dongjoon-hyun @sunchao

**Comment by sunchao** [comment]
Merged to master, thanks!

**Comment by LuciferYang** [comment]
Thanks @sunchao @dongjoon-hyun @bjornjorgensen ~

**Pull request closed without merging**
