### PR TITLE
[SPARK-17456][CORE] Utility for parsing Spark versions

### PR DESCRIPTION
**Pull request by jkbradley**
## What changes were proposed in this pull request?

This patch adds methods for extracting major and minor versions as Int types in Scala from a Spark version string.

Motivation: There are many hacks within Spark's codebase to identify and compare Spark versions. We should add a simple utility to standardize these code paths, especially since there have been mistakes made in the past. This will let us add unit tests as well.  Currently, I want this functionality to check Spark versions to provide backwards compatibility for ML model persistence.
## How was this patch tested?

Unit tests

### CODE REVIEW

**Comment by jkbradley** [comment]
CC: @yanboliang @MLnick Does one of you have time to review this?  It should be very quick.  Thanks!

**Comment by holdenk** [comment]
Would it make sense to replace some of the hacks with this util at the same time?

**Comment by jkbradley** [comment]
I like splitting things into separate PRs, but I'll go ahead and make a follow-up task to check for places which can be fixed.

**Comment by holdenk** [comment]
Sounds good :)

**Comment by yanboliang** [comment]
LGTM, merged into master. Thanks!

**Comment by yanboliang** [comment]
We can replace the hacks by the new utility in [SPARK-17462](https://issues.apache.org/jira/browse/SPARK-17462). Thanks!

**Comment by jkbradley** [comment]
Thanks @yanboliang !

**Comment by jkbradley** [comment]
Actually, I'd like to backport this to 2.0 since I'd like to put [https://issues.apache.org/jira/browse/SPARK-16240] into 2.0 as well.  I'll do the backport.

**Comment by jkbradley** [comment]
OK I did the backport.  I checked out branch-2.0 and ran the test locally.

**Pull request closed without merging**
