### PR TITLE
[SPARK-31963][PYSPARK][SQL] Support both pandas 0.23 and 1.0 in serializers.py

### PR DESCRIPTION
**Pull request by williamhyun**
### What changes were proposed in this pull request?

This PR aims to support both pandas 0.23 and 1.0.

### Why are the changes needed?
```
$ pip install pandas==0.23.2

$ python -c "import pandas.CategoricalDtype"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pandas.CategoricalDtype'

$ python -c "from pandas.api.types import CategoricalDtype"
```
### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the Jenkins.
```
$ pip freeze | grep pandas
pandas==0.23.2

$ python/run-tests.py --python-executables python --modules pyspark-sql
...
Tests passed in 359 seconds
```

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @williamhyun .
Merged to master.

**Comment by BryanCutler** [comment]
Thanks @williamhyun and @dongjoon-hyun  LGTM

**Comment by dongjoon-hyun** [comment]
Thanks, @BryanCutler .

**Comment by HyukjinKwon** [comment]
Lgtm too. There's is_categorical_type actually :) but no biggie

**Pull request closed without merging**
