### PR TITLE
[SPARK-12362][SQL][WIP] Inline Hive Parser

### PR DESCRIPTION
**Pull request by hvanhovell**
This is a WIP. The PR has been taken over from @nongli (see https://github.com/apache/spark/pull/10420). I have removed some additional dead code, and fixed a few issues which were caused by the fact that the inlined Hive parser is newer than the Hive parser we currently use in Spark.

I am submitting this PR in order to get some feedback and testing done. There is quite a bit of work to do:
- [ ] Get it to pass jenkins build/test.
- [ ] Aknowledge Hive-project for using their parser.
- [ ] Refactorings between HiveQl and the java classes.
  - [ ] Create our own ASTNode and integrate the current implicit extentions.
  - [ ] Move remaining `SemanticAnalyzer` and `ParseUtils` functionality to `HiveQl`.
- [ ] Removing Hive dependencies from the parser. This will require some edits in the grammar files.
  - [ ] Introduce our own context which needs to contain a `TokenRewriteStream`.
  - [ ] Add `useSQL11ReservedKeywordsForIdentifier` and `allowQuotedId` to the catalyst or sql configuration.
  - [ ] Remove `HiveConf` from grammar files &HiveQl, and pass in our own configuration.
- [ ] Moving the parser into sql/core.

cc @nongli @rxin

### CODE REVIEW

**Comment by hvanhovell** [comment]
retest this please

**Comment by hvanhovell** [comment]
retest this please

**Comment by hvanhovell** [comment]
retest this please

**Comment by davies** [comment]
@hvanhovell Since this patch is huge, could you defer some changes later so we can merge it ASAP?

**Comment by hvanhovell** [comment]
@davies yeah, that seems like the best course of action. Lets focus on passing all tests and stabilizing the build for this PR.

**Comment by hvanhovell** [comment]
retest this please

**Comment by rxin** [comment]
I'm going to merge this pull request given the size.

@hvanhovell  please submit follow up prs to address the todos. Thanks!

**Comment by rxin** [comment]
I reverted the patch due to the non-deterministic build failures on pull request builders.

**Pull request closed without merging**
