### PR TITLE
[SPARK-34233][SQL][3.1] FIX NPE for char padding in binary comparison

### PR DESCRIPTION
**Pull request by yaooqinn**
As mentioned at https://github.com/apache/spark/pull/31336#issuecomment-768786706 the PR https://github.com/apache/spark/pull/31336 has been reverted to from branch 3.1 due to test failures, this pr fixes for that,

the test failure is due to another patch is missing in branch 3.1, so in this pr, we wait for https://github.com/apache/spark/commit/fc3f22645e5c542e80a086d96da384feb6afe121 to be backport first 
 ### What changes were proposed in this pull request?

we need to check whether the `lit` is null  before calling `numChars`

### Why are the changes needed?

fix an obvious NPE bug

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

new tests

### CODE REVIEW

**Comment by yaooqinn** [comment]
cc @cloud-fan @maropu @MaxGekk @dongjoon-hyun, thanks for reviewing

**Review by MaxGekk — COMMENTED** [review]
https://github.com/apache/spark/commit/fc3f22645e5c542e80a086d96da384feb6afe121 has a test which this PR does not have. How about to cherry-pick my PR to 3.1 entirely (and separately).

**Comment by yaooqinn** [comment]
> [fc3f226](https://github.com/apache/spark/commit/fc3f22645e5c542e80a086d96da384feb6afe121) has a test which this PR does not have. How about to cherry-pick my PR to 3.1 entirely (and separately).

I found not find a proper place to add that test, maybe `AlterTablePartitionV2SQLSuite`?

**Comment by MaxGekk** [comment]
> ... maybe AlterTablePartitionV2SQLSuite?

Yep, I would place the test there.

**Comment by maropu** [comment]
The @MaxGekk suggestion looks fine and could you open a PR to backport fc3f226 for branch-3.1?

**Comment by MaxGekk** [comment]
Here is the backport https://github.com/apache/spark/pull/31411 of https://github.com/apache/spark/pull/31014 to `branch-3.1`.

**Comment by maropu** [comment]
The current PR is the same with the original one #31336 ?

**Comment by yaooqinn** [comment]
@maropu yea, can you directly check-pick by `merge_spark_pr.py` or revert the revert PR?

**Comment by cloud-fan** [comment]
https://github.com/apache/spark/pull/31411 has been merged, can you rebase this PR @yaooqinn ?

**Comment by yaooqinn** [comment]
rebased~, thank you all~

**Review by cloud-fan — APPROVED** [review]

**Comment by maropu** [comment]
retest this please

**Review by maropu — APPROVED** [review]

**Comment by cloud-fan** [comment]
thanks, merging to 3.1!

**Comment by yaooqinn** [comment]
thanks for merging

**Pull request closed without merging**
