### PR TITLE
[SPARK-26348][SQL][TEST] make sure expression is resolved during test

### PR DESCRIPTION
**Pull request by cloud-fan**
## What changes were proposed in this pull request?

cleanup some tests to make sure expression is resolved during test.

## How was this patch tested?

test-only PR

### CODE REVIEW

**Comment by cloud-fan** [comment]
cc @gatorsmile @dongjoon-hyun @HyukjinKwon

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by cloud-fan** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
Looks good to me

**Comment by cloud-fan** [comment]
This is a test-only PR and doesn't touch Spark R, the R failure is a known issue. I'm merging it to master, thanks!

**Pull request closed without merging**
