### PR TITLE
[SPARK-17960][PySpark] [Upgrade to Py4J 0.10.4]

### PR DESCRIPTION
**Pull request by jagadeesanas2**
## What changes were proposed in this pull request?

1) Upgrade the Py4J version on the Java side
2) Update the py4j src zip file we bundle with Spark
## How was this patch tested?

Existing doctests & unit tests pass

### CODE REVIEW

**Comment by holdenk** [comment]
Awesome, thanks for taking this on @jagadeesanas2, this looks pretty reasonable although it might be helpful if we mentioned briefly the PR description what the Py4J changes were in this release since that is what ends up as the commit description once its merged. But the change its self looks good to me - cc @srowen / @davies for the final review.

**Comment by davies** [comment]
cc @JoshRosen

**Comment by srowen** [comment]
I'm OK with it. For the record, was there any fix here that impacts Spark? updating just to keep updated isn't a bad idea but wouldn't want to update through every version of everything. Maybe at least once per minor release it's worth review.

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
