### PR TITLE
[SPARK-45141][PYTHON][INFRA][TESTS] Pin `pyarrow==12.0.1` in CI

### PR DESCRIPTION
**Pull request by zhengruifeng**
### What changes were proposed in this pull request?
Pin `pyarrow==12.0.1` in CI

### Why are the changes needed?
to fix test failure,  https://github.com/apache/spark/actions/runs/6167186123/job/16738683632

```
======================================================================
FAIL [0.095s]: test_from_to_pandas (pyspark.pandas.tests.data_type_ops.test_datetime_ops.DatetimeOpsTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/spark/spark/python/pyspark/testing/pandasutils.py", line 122, in _assert_pandas_equal
    assert_series_equal(
  File "/usr/local/lib/python3.9/dist-packages/pandas/_testing/asserters.py", line 931, in assert_series_equal
    assert_attr_equal("dtype", left, right, obj=f"Attributes of {obj}")
  File "/usr/local/lib/python3.9/dist-packages/pandas/_testing/asserters.py", line 415, in assert_attr_equal
    raise_assert_detail(obj, msg, left_attr, right_attr)
  File "/usr/local/lib/python3.9/dist-packages/pandas/_testing/asserters.py", line 599, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: Attributes of Series are different

Attribute "dtype" are different
[left]:  datetime64[ns]
[right]: datetime64[us]
```

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
CI and manually test

### Was this patch authored or co-authored using generative AI tooling?
No

### CODE REVIEW

**Comment by zhengruifeng** [comment]
I think the reason is:

https://github.com/apache/spark/pull/42842 disable old cache, and rebuild the whole image with [pyarrow=13.0.0](https://pypi.org/project/pyarrow/13.0.0/)


before https://github.com/apache/spark/pull/42842 the cached `pyarrow==12.0.1` is used, even though pyarrow=13.0.0 has been released.

**Comment by zhengruifeng** [comment]
cc @HyukjinKwon @Yikun

**Review by dongjoon-hyun — COMMENTED** [review]
In order to not forget, could you add a TODO PR for PyArrow 13.x, @zhengruifeng ?

**Comment by zhengruifeng** [comment]
@dongjoon-hyun thanks for the reminder, I create https://issues.apache.org/jira/browse/SPARK-45143 to track this issue

**Review by HyukjinKwon — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Review by itholic — APPROVED** [review]

**Comment by zhengruifeng** [comment]
all python tests passed, merged to master

**Comment by itholic** [comment]
Thanks!

**Comment by dongjoon-hyun** [comment]
According to https://github.com/apache/spark/pull/45545#issuecomment-2002355919 , let me backport this to branch-3.5 and 3.4 to recover the CIs.

**Pull request closed without merging**
