### PR TITLE
[SPARK-22662] [SQL] Failed to prune columns after rewriting predicate subquery

### PR DESCRIPTION
**Pull request by wzhfy**
## What changes were proposed in this pull request?

As a simple example:
```
spark-sql> create table base (a int, b int) using parquet;
Time taken: 0.066 seconds
spark-sql> create table relInSubq ( x int, y int, z int) using parquet;
Time taken: 0.042 seconds
spark-sql> explain select a from base where a in (select x from relInSubq);
== Physical Plan ==
*Project [a#83]
+- *BroadcastHashJoin [a#83], [x#85], LeftSemi, BuildRight
   :- *FileScan parquet default.base[a#83,b#84] Batched: true, Format: Parquet, Location: InMemoryFileIndex[hdfs://100.0.0.4:9000/wzh/base], PartitionFilters: [], PushedFilters: [], ReadSchema: struct<a:int,b:int>
   +- BroadcastExchange HashedRelationBroadcastMode(List(cast(input[0, int, true] as bigint)))
      +- *Project [x#85]
         +- *FileScan parquet default.relinsubq[x#85] Batched: true, Format: Parquet, Location: InMemoryFileIndex[hdfs://100.0.0.4:9000/wzh/relinsubq], PartitionFilters: [], PushedFilters: [], ReadSchema: struct<x:int>
```
We only need column `a` in table `base`, but all columns (`a`, `b`) are fetched.

The reason is that, in "Operator Optimizations" batch, `ColumnPruning` first produces a `Project` on table `base`, but then it's removed by `removeProjectBeforeFilter`. Because at that time, the predicate subquery is in filter form. Then, in "Rewrite Subquery" batch, `RewritePredicateSubquery` converts the subquery into a LeftSemi join, but this batch doesn't have the `ColumnPruning` rule. This results in reading all columns for the `base` table.

## How was this patch tested?
Added a new test case.

### CODE REVIEW

**Comment by wzhfy** [comment]
cc @cloud-fan @gatorsmile @hvanhovell

**Comment by gengliangwang** [comment]
Hi @wzhfy , for resolving the issue, how about changing the order of batches? 
E.g. move batch `RewriteSubquery` before `Operator Optimizations`

**Comment by cloud-fan** [comment]
cc @jiangxb1987 who has more context.

**Comment by wzhfy** [comment]
@gengliangwang @cloud-fan Previously this rule is in the batch `Operator Optimizations`, but after [SPARK-14781](https://github.com/apache/spark/pull/12820), it is moved into a separate batch [by this code change](https://github.com/apache/spark/pull/12820#discussion_r61688622).
I think the reason of this change is in the PR description:
>This PR also fix a bug in predicate subquery push down through join (they should not).

I reverted the change in Optimizer and ran all the test suites in that PR, hoping to find some clue. But I found no error in tests. So it seems something has been changed since that PR.

**Comment by gengliangwang** [comment]
I think for 
```
This PR also fix a bug in predicate subquery push down through join (they should not).
```
he meant here: https://github.com/apache/spark/pull/12820/files#diff-a636a87d8843eeccca90140be91d4fafR1213

But I don't know why @davies moved the rule to the end, either.

**Comment by gatorsmile** [comment]
A long story to explain what happened since the initial support of correlated queries.

I am fine to add this rule in this batch now, although it just resolves the issue partially.

**Comment by gatorsmile** [comment]
retest this please

**Review by gatorsmile — APPROVED** [review]
LGTM

**Comment by gatorsmile** [comment]
Thanks! Merged to master.

**Comment by maropu** [comment]
just FYI; this pr is too cool! cuz this fix improved many tpcds queries (e.g., `q94` got more than 10x faster than before!).https://docs.google.com/spreadsheets/d/1V8xoKR9ElU-rOXMH84gb5BbLEw0XAPTJY8c8aZeIqus/edit?usp=sharing

**Comment by wzhfy** [comment]
@maropu Good to know, thanks!

**Pull request closed without merging**
