### PR TITLE
[SPARK-15213][PySpark] Unify 'range' usages

### PR DESCRIPTION
**Pull request by zhengruifeng**
## What changes were proposed in this pull request?

Most python file directly use `range` ignoring the different implement between python 2 and 3.

1, use `range` in pyspark
2, for python2, `range = xrange`
## How was this patch tested?

unit tests

### CODE REVIEW

**Comment by asfer** [comment]
Apart from the merge conflict, everything looks good to me.

**Comment by MechCoder** [comment]
I don't really get the difference, could you please explain it to me..

The previous version renamed `range` in `Python3` to `xrange` and this pull request does the same thing by renaming `xrange` in Python2 to `range`. Not sure this is necessary. There should be no performance changes since both return generators.

**Comment by srowen** [comment]
Yes, @zhengruifeng what's the difference here? could you update or close?

**Comment by srowen** [comment]
Let's close this for lack of follow up

**Comment by zhengruifeng** [comment]
@MechCoder @srowen There is no prefermance diffence. There is only one little difference: Py2 have 'xrange' and 'range', while Py3 only have 'range'. So unifying all case to 'range' may be more acceptable for Py3 users.

**Comment by srowen** [comment]
Yeah I can see that point; the change is ultimately a no-op. I'm neutral on it, not much a python person myself.

**Comment by zhengruifeng** [comment]
@srowen In Python2, `xrange` is more efficient than `range`.  
This PR add 'range = xrange' in files like `python/pyspark/accumulators.py`  `python/pyspark/heapq3.py` `python/pyspark/heapq3.py` etc. So those file may run faster in Python2.

**Comment by srowen** [comment]
How about we make the smaller change, and call `xrange` in those files like the rest of the code does (and add the reverse alias where needed)?

**Comment by zhengruifeng** [comment]
@srowen I update this PR according to your comment, and make it a small PR just to add 'xrange <-> range' alias in files that dont have it.

**Comment by srowen** [comment]
This still makes the alias go the opposite way to the current code base. However there are only 11 occurrences of that currently, and you indicate there are 30 files in total that need some alias. What is the more standard way to alias this in general in Python code? @MechCoder @davies opinions?

**Comment by davies** [comment]
If the number of iteration is not huge, it does not matter to use range() or xrange() in Python 2 (especially when you use it together with `for`). That's said I'm not a fan of this change.

**Comment by MechCoder** [comment]
In sklearn, we use `sklearn.six.moves` which makes `range` and `xrange` to be used interchangeably. In Python3, both `range` and `xrange` would return a `range` instance and in Py2, both `xrange` and `range` would return a `xrange` instance. Something like

```python
if sys.version[0] == '3':
    xrange = range
if sys.version[0] == '2':
    range = xrange
```

That being said, I'm ok with this PR being merged as it is since as a Py3 user, it is more natural for me to use `range`. (But only as a Py3 user). Anyway I believe, we should be consistent in usage.

**Pull request closed without merging**
