### PR TITLE
[SPARK-31791][CORE][TEST] Improve cache block migration test reliability

### PR DESCRIPTION
**Pull request by holdenk**
### What changes were proposed in this pull request?

Increase the timeout and register the listener earlier to avoid any race condition of the job starting before the listener is registered.

### Why are the changes needed?

The test is currently semi-flaky.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?
I'm currently running the following bash script on my dev machine to verify the flakiness decreases. It has gotten to 356 iterations without any test failures so I believe issue is fixed.

```
set -ex
./build/sbt clean compile package
((failures=0))
for (( i=0;i<1000;++i )); do
  echo "Run $i"
  ((failed=0))
  ./build/sbt "core/testOnly org.apache.spark.scheduler.WorkerDecommissionSuite" || ((failed=1))
  echo "Resulted in $failed"
  ((failures=failures+failed))
  echo "Current status is failures: $failures out of $i runs"
done
```

### CODE REVIEW

**Comment by holdenk** [comment]
cc @dongjoon-hyun

**Comment by holdenk** [comment]
I intend to merge by 5pm pacific if no one has suggestions as it is a test-only improvement.

**Comment by holdenk** [comment]
Merged to master.

**Comment by dongjoon-hyun** [comment]
+1, late LGTM.

**Pull request closed without merging**
