### PR TITLE
[SPARK-31055][DOCS] Update config docs for shuffle local host reads to have dep on external shuffle service

### PR DESCRIPTION
**Pull request by tgravescs**
### What changes were proposed in this pull request?

with SPARK-27651 we now support host local reads for shuffle, but only when external shuffle service is enabled. Update the config docs to state that.

### Why are the changes needed?

clarify dependency

### Does this PR introduce any user-facing change?

no

### How was this patch tested?

n/a

### CODE REVIEW

**Comment by tgravescs** [comment]
@attilapiros

**Review by attilapiros — APPROVED** [review]
LGTM

**Comment by tgravescs** [comment]
@dongjoon-hyun @HyukjinKwon if you have time for a quick review

**Review by dongjoon-hyun — APPROVED** [review]
Thank you for pinging me, @tgravescs .

+1, LGTM. Merged to master/3.0.

**Review by HyukjinKwon — COMMENTED** [review]
Late LGTM. Thanks for cc'ing me @tgravescs

**Pull request closed without merging**
