### PR TITLE
[MINOR][DOCS] Fix typos in `pyspark_upgrade.rst`

### PR DESCRIPTION
**Pull request by bjornjorgensen**
### What changes were proposed in this pull request?
Fix typos in pyspark_upgrade.rst

### Why are the changes needed?
Correct English makes it easier to read and understand.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Review by yaooqinn — APPROVED** [review]

**Comment by bjornjorgensen** [comment]
@yaooqinn This PR is a followup from https://github.com/apache/spark/pull/42578#issuecomment-1689101755 so let @itholic correct it or approve it before merging.

**Review by dongjoon-hyun — APPROVED** [review]
Thank you. Is this the last typo?

**Comment by bjornjorgensen** [comment]
in line 74 
In Spark 3.2, the PySpark methods from sql, ml, spark_on_pandas modules raise the ``TypeError`` instead of ``ValueError`` when are applied to an param of inappropriate type.

I think it should be In Spark 3.2, the PySpark methods from sql, ml, spark_on_pandas modules raise the ``TypeError`` instead of ``ValueError`` when are applied to a param of inappropriate type.

a param
but I'm 100 % on this one.. 

The rest of the file looks ok for me. I pasted it in to a ms word 365 doc.

**Comment by bjornjorgensen** [comment]
@dongjoon-hyun :) is it a param or an param?

**Comment by dongjoon-hyun** [comment]
`a param` looks proper to me.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by yaooqinn** [comment]
thanks, merged to master

**Comment by itholic** [comment]
Late LGTM. Thanks for catching this!

**Pull request closed without merging**
