### PR TITLE
[SPARK-48341][CONNECT] Allow plugins to use QueryTest in their tests

### PR DESCRIPTION
**Pull request by tomvanbussel**
### What changes were proposed in this pull request?

This PR changes `QueryTest` to no longer depend on `RemoteSparkSession`.

### Why are the changes needed?

This allows the tests for Spark Connect plugin to provide their version of `RemoteSparkSession` (which depends on some idiosyncrasies of how Spark is built).

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Existing tests to ensure that nothing breaks. Manually tested that this allows a plugin to use `QueryTest`.

### Was this patch authored or co-authored using generative AI tooling?

No

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Can we file a JIRA ticket please?

**Review by HyukjinKwon — APPROVED** [review]
Otherwise, seems fine.

**Comment by zhengruifeng** [comment]
the failed tests seems related:
```
[error] /home/runner/work/spark/spark/connector/connect/client/jvm/src/test/scala/org/apache/spark/sql/CatalogSuite.scala:29:28: illegal inheritance;
[error]  self-type org.apache.spark.sql.CatalogSuite does not conform to org.apache.spark.sql.test.RemoteSparkSession's selftype org.apache.spark.sql.test.RemoteSparkSession with org.scalatest.Suite
[error] class CatalogSuite extends RemoteSparkSession with SQLHelper {
[error]                            ^
[error] /home/runner/work/spark/spark/connector/connect/client/jvm/src/test/scala/org/apache/spark/sql/CatalogSuite.scala:31:3: package org.apache.spark.sql.test is not a value
```

**Comment by tomvanbussel** [comment]
@HyukjinKwon Sorry, I filed a ticket (see branch name) but forgot to include it in the PR title. (I knew I was missing something...)

@zhengruifeng Thanks, should be fixed now!

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
