### PR TITLE
PR10000?

### PR DESCRIPTION
**Pull request by rxin**

### CODE REVIEW

**Comment by gatorsmile** [comment]
wow, What an amazing achievement!

**Comment by markhamstra** [comment]
Reynold is just claiming all the good numbers for himself.

**Comment by rxin** [comment]
:)

**Comment by rxin** [comment]
Now I gotta think hard about what I should submit using this branch when I reopen the pull request.

**Comment by gatorsmile** [comment]
Streaming DataFrames? I think this is a very significant feature!

**Pull request closed without merging**
