### PR TITLE
[MINOR] [DOC] Fix Dockerfile path reference

### PR DESCRIPTION
**Pull request by dlstadther**
### What changes were proposed in this pull request?

Fixes the referenced file path for building Python/R binding docker files.

### Why are the changes needed?

`Running on Kubernetes` documentation notes an incorrect file path for Python and R binding `Dockerfile`s.

### Does this PR introduce any user-facing change?

No

### How was this patch tested?

Documentation change only. Continues to be markdown compliant.

### CODE REVIEW

**Review by srowen — APPROVED** [review]

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
Hi, @dlstadther and @srowen .

Sorry, but the original one is correct because this document is for Apache Spark release (not this source code repo.). Please check `Apache Spark 2.4.3` directory. There is `kubernetes` directory and there is no `resource-managers` directory.

All the official document on website is tightly coupled with the target release.

Please close this PR.

**Comment by srowen** [comment]
Oh, right, sorry I made the same mistake!

**Comment by dlstadther** [comment]
@dongjoon-hyun what `Apache Spark 2.4.3` directory are you referring to? The source code download from Apache's website includes the same directory structure (includes `resource-managers`, but no `kubernetes` directories).

BUT the `running-on-kubernetes.md` file contained in that release does not include these two lines.

Thus, it still appears the version in `master` is not up-to-date.

Could you please direct me to where you see this `kubernetes` dir in 2.4.3? Thanks!

**Comment by srowen** [comment]
The docs are w.r.t. the binary distribution, which is the runnable artifact we'd expect users to use (or build themselves). It differs from the layout of the source files. By the same token much of the documentation doesn't make sense for the source release, as it has nothing to run.

**Pull request closed without merging**
