### PR TITLE
[SPARK-21575][SparkR] Eliminate needless synchronization in java-R serialization

### PR DESCRIPTION
**Pull request by SereneAnt**
## What changes were proposed in this pull request?
Remove surplus synchronized blocks.

## How was this patch tested?
Unit tests run OK.

### CODE REVIEW

**Review by srowen — APPROVED** [review]
Agree. A lock is still acquired, but just the map's lock. Less work is done too. That can help a little.

**Review by jiangxb1987 — APPROVED** [review]
LGTM

**Review by yanboliang — APPROVED** [review]
LGTM

**Comment by yanboliang** [comment]
Merged into master, thanks for all.

**Pull request closed without merging**
