### PR TITLE
[SPARK-18925][STREAMING] Reduce memory usage of mapWithState

### PR DESCRIPTION
**Pull request by vpchelko**
## What changes were proposed in this pull request?

Reduced memory usage of mapWithState by cleaning all 'oldRDDs' except current and last checkpointed - overridden clearMetadata for InternalMapWithStateDStream

## How was this patch tested?

Passed unit tests, manual tests

### CODE REVIEW

**Comment by vpchelko** [comment]
Jenkins, retest this please.

**Comment by vpchelko** [comment]
cc @tdas

**Comment by zsxwing** [comment]
Some operators (e.g., window) may still need to use these RDD, dropping them will slow your application. That's why `DStream` uses `rememberDuration` to filter RDDs.

You can [tune the memory usage of Spark](http://spark.apache.org/docs/latest/configuration.html#memory-management) (e.g., reduce `spark.memory.fraction`). Blocks for MapWithStateRDD will be removed automatically when the memory is not enough.

**Comment by vpchelko** [comment]
We dont use windows operations (Kafka streaming) - so we don't need 'old' RDDs :)

I need to double check if spark.memory.fraction help to us.

**Comment by vpchelko** [comment]
cc @zsxwing, @tdas

**Comment by zsxwing** [comment]
> scala.NotImplementedError: put() should not be called on an EmptyStateMap

This is another issue and not related to the memory issue. Could you create a new ticket, please?

For this PR, I want to understand why the `DStream.clearMetadata` doesn't work? Do you have a simple reproducer for me to run?

**Comment by vpchelko** [comment]
DStream.clearMetadata allows to keep metadata for up to checkpoint_interval_multiplier RDDs.
This PR clears metadata as soon as possible. As the result applicatin uses less memory and less GC overheads.

I need time to prepare an abstact standablone example.

**Comment by wobuxiangtong** [comment]
Excuse me：
    I am using mapwithstate to storage data in sparkstreaming。What confused me is that rememberDuration must more than checkpointDuration。I read the code of MapWithStateRDD and changed is as the follow question and have done some tests  which indicated that it does not matter even though hold only one RDD in storage and no data will lose。it will cut down a lot of memory if doing so like this.
    Maybe i am wrong. Could you help me? the question is here:
https://stackoverflow.com/questions/47784439/what-will-happen-if-i-change-the-rememberduration-in-dstream-less-than-checkpoin

**Comment by vpchelko** [comment]
I don't use anymore approach above.
To unpersist unnecessary RDD, I hacked MapWithStateDStream a little bit by calling unpersist for previously generated RDDs in internalMapWithStateStream.

Сache eviction not working well, from my observations the cache eviction is an expensive operation. Also because of a lot object in JVM the garbage collector starts consuming resources significantly.

P.S.
For my task I don't need mappedValues in cache.
Why mapWithState caching mappedValues in RAM?
Previous mappedValues are not required to calculate the next state, and next mappedValues, they just using the RAM.

**Pull request closed without merging**
