### PR TITLE
[SPARK-14640] Add @DeveloperApi on PythonUserDefinedType

### PR DESCRIPTION
**Pull request by joan38**
## What changes were proposed in this pull request?

Add `@DeveloperApi` on `PythonUserDefinedType`

### CODE REVIEW

**Comment by andrewor14** [comment]
In general `@DeveloperApi`s are only used for public classes. What is the motivation for adding this here?

**Comment by joan38** [comment]
@andrewor14 Sorry I've been confused by the `::DeveloperApi::` in comments.
Should we remove `::DeveloperApi::` from the comment then?

**Comment by andrewor14** [comment]
Oh now I see why you did that. Yeah it doesn't even make sense to add a `::DeveloperApi::` to something without an annotation. I would remove that comment.

**Comment by joan38** [comment]
Cheers @andrewor14 for the clarification. I will do a PR for that.

**Pull request closed without merging**
