### PR TITLE
[SPARK-34711][SQL][TESTS] Exercise code-gen enable/disable code paths for SHJ in join test suites

### PR DESCRIPTION
**Pull request by c21**
### What changes were proposed in this pull request?

Per comment in https://github.com/apache/spark/pull/31802#discussion_r592068440 , we would like to exercise whole stage code-gen enabled and disabled code paths in join unit test suites. This is for better test coverage of shuffled hash join.

### Why are the changes needed?

Better test coverage.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Existing and added unit tests here.

### CODE REVIEW

**Comment by c21** [comment]
cc @dongjoon-hyun could you help take a look when you have time, thanks.

**Review by dongjoon-hyun — APPROVED** [review]
Thank you, @c21 .
+1, LGTM. (Pending CIs)

**Comment by dongjoon-hyun** [comment]
This is a test PR and I verified this manually. Merged to master/3.1.

**Comment by c21** [comment]
Thank you @dongjoon-hyun for review!

**Pull request closed without merging**
