### PR TITLE
[SPARK-23165][DOC] Spelling mistake fix in quick-start doc.

### PR DESCRIPTION
**Pull request by ashashwat**
## What changes were proposed in this pull request?

Fix spelling in quick-start doc.

## How was this patch tested?

Doc only.

### CODE REVIEW

**Review by srowen — APPROVED** [review]
That's fine. We usually don't make a JIRA for this. If you have time, please also spell check more docs around this.

**Comment by ashashwat** [comment]
@srowen Let me go ahead and do that.

**Comment by ashashwat** [comment]
Retest this please.

**Comment by gatorsmile** [comment]
retest this please

**Comment by gatorsmile** [comment]
LGTM

Thanks! Merged to master/2.3

**Pull request closed without merging**
