### PR TITLE
[SPARK-41974][SQL] Turn `INCORRECT_END_OFFSET` into `INTERNAL_ERROR`

### PR DESCRIPTION
**Pull request by itholic**
### What changes were proposed in this pull request?

This PR proposes to update `INCORRECT_END_OFFSET` as `INTERNAL_ERROR`.

### Why are the changes needed?

We should turn error class into INTERNAL_ERROR when it's not triggered by user space.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

`./build/sbt "sql/testOnly org.apache.spark.sql.SQLQueryTestSuite*`

### CODE REVIEW

**Comment by itholic** [comment]
cc @MaxGekk @srielau @HeartSaVioR FYI

**Comment by itholic** [comment]
@srielau Yeah, that makes sense. Just created [OSS ticket](https://issues.apache.org/jira/browse/SPARK-42004) to handle this. Thanks!!

**Review by HeartSaVioR — APPROVED** [review]
+1 I'm not an expert of error framework but it is a right direction to make it be an internal error.

**Review by cloud-fan — APPROVED** [review]

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Pull request closed without merging**
