### PR TITLE
[SPARK-8990] [SQL] SPARK-8990 DataFrameReader.parquet() should respect user specified options

### PR DESCRIPTION
**Pull request by liancheng**

### CODE REVIEW

**Comment by rxin** [comment]
lgtm

**Comment by rxin** [comment]
Thanks. Merging this.

**Comment by rxin** [comment]
It doesn't merge cleanly into branch-1.4. Can you submit a separate pr against branch-1.4? Thanks.

**Comment by rxin** [comment]
I'm going to leave the ticket open for now.

**Comment by liancheng** [comment]
@rxin Opened #7351 for branch-1.4.

**Pull request closed without merging**
