### PR TITLE
[SQL][MINOR][TESTS] Remove GivenWhenThen trait from HiveComparisonTest

### PR DESCRIPTION
**Pull request by maropu**
### What changes were proposed in this pull request?

This pr intends to remove non-used trait, `GivenWhenThen`, from `HiveComparisonTest`.

### Why are the changes needed?

For better code.

### Does this PR introduce any user-facing change?

No

### How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by maropu** [comment]
minor issue though, I found it..  @dongjoon-hyun @HyukjinKwon

**Review by gengliangwang — APPROVED** [review]

**Comment by gengliangwang** [comment]
Thanks, merging to master.

**Comment by maropu** [comment]
Thanks, @gengliangwang !

**Comment by dongjoon-hyun** [comment]
+1, late LGTM.

**Comment by maropu** [comment]
Thanks for the check, @dongjoon-hyun

**Pull request closed without merging**
