### PR TITLE
[SPARK-39686][INFRA] Disable scheduled builds that did not pass even once

### PR DESCRIPTION
**Pull request by HyukjinKwon**
### What changes were proposed in this pull request?

This PR proposes to skip the builds that have never passed in history. https://github.com/apache/spark/pull/36940 added some more combinations to check if they passed, and this PR disables some of them that do not pass.

See also:
- SPARK-39681 (https://github.com/apache/spark/runs/7189972241?check_suite_focus=true)
- SPARK-39685 (https://github.com/apache/spark/runs/7189971643?check_suite_focus=true)
- SPARK-39682 (https://github.com/apache/spark/runs/7189971505?check_suite_focus=true)
- SPARK-39684 (https://github.com/apache/spark/runs/7054055518?check_suite_focus=true)

### Why are the changes needed?

In order to check the test status easily with each combination of profile and branch.

### Does this PR introduce _any_ user-facing change?

No, test-only.

### How was this patch tested?

Virtually configuration changes. Will be checked after it's merged.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @Yikun and @dongjoon-hyun FYI

**Review by Yikun — APPROVED** [review]
LGTM, thanks!

**Review by srowen — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by HyukjinKwon** [comment]
Thanks all!

**Pull request closed without merging**
