### PR TITLE
[SPARK-10799][Core]Fix InboxSuite 'post: multiple threads'

### PR DESCRIPTION
**Pull request by zsxwing**
This is a follow-up PR of #6457 to fix InboxSuite that I forgot to update. I also removed an unnecessary comment.

### CODE REVIEW

**Comment by zsxwing** [comment]
I also saw the following exception here: https://amplab.cs.berkeley.edu/jenkins/view/Spark-QA-Test/job/Spark-Master-SBT/3597/AMPLAB_JENKINS_BUILD_PROFILE=hadoop2.2,label=spark-test/:
```
15/09/24 00:50:13.033 pool-1-thread-1-ScalaTest-running-PageRankSuite ERROR SparkContext: Error initializing SparkContext.
java.net.BindException: Address already in use: Service 'NettyRpcEnv' failed after 100 retries!
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:444)
	at sun.nio.ch.Net.bind(Net.java:436)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:125)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:485)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1089)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:430)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:415)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:903)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:198)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:348)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:357)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at java.lang.Thread.run(Thread.java:745)
```
I'm not sure why it will happen since it's bind to `0`. Is it possible that the Jenkins worker exhausted all ports?

**Comment by shaneknapp** [comment]
jenkins, test this please

**Comment by vanzin** [comment]
Change looks good but I guess it depends on the original change being re-added? You could merge this into that patch.

**Comment by zsxwing** [comment]
Included in  #8944

**Pull request closed without merging**
