### PR TITLE
[SPARK-9866][SQL] Speed up VersionsSuite by using persistent Ivy cache

### PR DESCRIPTION
**Pull request by JoshRosen**
This patch attempts to speed up VersionsSuite by storing fetched Hive JARs in an Ivy cache that persists across tests runs. If `SPARK_VERSIONS_SUITE_IVY_PATH` is set, that path will be used for the cache; if it is not set, VersionsSuite will create a temporary Ivy cache which is deleted after the test completes.

### CODE REVIEW

**Comment by JoshRosen** [comment]
Before this patch, VersionsSuite took ~5-7 minutes in Jenkins; it's 2-3 minutes after.

**Comment by vanzin** [comment]
That is most definitely still a problem. I doubt it will affect jenkins machines, but it affects local builds when you're executing that test and you also use maven for other things. If you could make this configurable, so that based on some env variable set by jenkins it uses the shared cache, I'd be more comfortable.

**Comment by JoshRosen** [comment]
Do you know what the origin of the problem is? Is it a concurrency or locking bug in Spark? There are many applications which use Ivy that don't run into these problems (e.g. running SBT and IntelliJ at the same time), so I'm wondering if Spark is doing something non-standard that breaks this.

**Comment by vanzin** [comment]
I don't really know what's the source of the problem. My best guess is some incompatibility between the version of ivy embedded in sbt and the version of ivy used by Spark, or differences in how they handle dependencies from the local maven cache. I remember nuking the offending artifacts from the local maven cache would fix things (ivy would then download fresh copies into its own cache), but that wasn't a good long-term solution for someone who also uses maven.

**Comment by JoshRosen** [comment]
Maybe @brkyvz has more insights on the Ivy corruption issues that you described?

**Comment by JoshRosen** [comment]
@vanzin, I took a closer look and it appears that Ivy's default locking strategy is "no locking", which is not safe when using a shared cache. I'm going to submit a separate PR to fix this.

**Comment by brkyvz** [comment]
@JoshRosen There are so many things I couldn't figure about Ivy... The library is practically a black box. It unfortunately doesn't have a lot of documentation (at least for the library). There are two problems that I would love to fix:
1) Ivy configurations. Basically, if you publish a library locally in SBT with publishLocal, Spark won't be able to access it due to configurations. publishM2 works fine though.
2) This cache corruption issue.
IMHO, I would suggest taking a flag, which is by default off, but on in Jenkins that would use the shared cache. If this causes flakiness in the SparkSubmitSuite tests, then we'll have to turn it off though :(

**Comment by JoshRosen** [comment]
Isn't `spark-submit`'s default behavior to use a shared Ivy cache? If so, shouldn't we be testing with that as the default rather than the exception so that any bugs which are painful for users are equally painful for us, too? My fear is that if there is somehow a corruption issue then we'll be masking it by not using the shared cache in our own tests. Basically, I'm arguing that the the shared cache in tests should be an opt-out feature, not opt-in.

**Comment by JoshRosen** [comment]
I did some more digging and it looks like this whole locking situation is a much bigger mess than I originally estimated:

- SBT coordinates access to the Ivy cache using a lock file that is shared by all running SBT processes: https://github.com/sbt/sbt/blob/v0.13.8/ivy/src/main/scala/sbt/Ivy.scala#L65. [By default](https://github.com/sbt/sbt/blob/v0.13.8/ivy/src/main/scala/sbt/Ivy.scala#L119), this file is named ".sbt.ivy.lock". This will handle coordination among SBT processes but does not guard against other processes which might also use the Ivy cache.
- Ivy's built-in locking support seems hard to configure and also seems prone to issues related to lock files not being cleaned up when processes crash: https://issues.apache.org/jira/browse/IVY-1388.
- At http://jira.pentaho.com/browse/BISERVER-4809, someone points out that although Ivy's artifact cache can be guarded via locks, its resolution cache is not guardable by any of Ivy's locking strategies.

@brkyvz, given all of this, I wonder whether Spark's default Ivy cache location should be different than `~/.ivy2`.

To help clear this patch out of the queue, though, I'll just go ahead and implement the flag as originally discussed (off by default and using shared cache only in Jenkins, where it happens to be safe because each build workspace has its own isolated Maven and Ivy cache directories which are preserved across builds).

**Comment by JoshRosen** [comment]
@vanzin, I've updated this patch to introduce a `SPARK_VERSIONS_SUITE_IVY_PATH` environment variable which can be used to configure a fixed directory instead of a temporary Ivy directory.

For posterity, here's the configuration change that I pushed to the Jenkins PRB job:

```
SPARK_VERSIONS_SUITE_IVY_PATH=/home/sparkivy/${JOB_NAME}_${EXECUTOR_NUMBER}/.ivy2
```

This configures that variable to point to the per-test-workspace Ivy cache which is persisted across test runs.

**Comment by vanzin** [comment]
Sweet, thanks. LGTM.

**Comment by JoshRosen** [comment]
VersionsSuite has passed in Jenkins and appears to have run pretty quickly, so I've updated the PR description and title and will merge this into master and branch-1.6.

**Pull request closed without merging**
