### PR TITLE
SPARK-11415: Remove timezone shift of Catalyst DateType

### PR DESCRIPTION
**Pull request by RussellSpitzer**
Shifting the timestamp before calculating the days since epoch was
yielding off by one errors. Machines operating in different time zones
would also yeild different results. Treating the input to millisToDays
and daysToMillis as a straight UTC timestamp fixes this issue.

### CODE REVIEW

**Comment by jacek-lewandowski** [comment]
jenkins, test this please

**Comment by marmbrus** [comment]
ok to test

**Comment by yhuai** [comment]
@davies take a look?

**Comment by davies** [comment]
@RussellSpitzer Since you already close the JIRA, could you also close this PR? thanks!

**Comment by RussellSpitzer** [comment]
np

**Pull request closed without merging**
