### PR TITLE
[SPARK-25120][CORE][HistoryServer]Fix the problem of EventLogListener may miss driver SparkListenerBloc…

### PR DESCRIPTION
**Pull request by deshanxiao**
## What changes were proposed in this pull request?

Sometimes in spark history tab "Executors" , it couldn't find driver information because the information of this page created by `EventLog` replaying the event of `SparkListenerBlockManagerAdded`. In `SparkContext`, driver registers blockmanager before adding the `EventLogEventListener` to LiveListenerBus. In this case,the  `EventLogEventListener` may miss the driver's  `SparkListenerBlockManagerAdded` event and the history ui won't show the info of driver in "Executors" .

## How was this patch tested?

N/A

### CODE REVIEW

**Comment by deshanxiao** [comment]
please help me cc @HyukjinKwon

**Comment by felixcheung** [comment]
@vanzin @squito

**Comment by vanzin** [comment]
ok to test

**Comment by squito** [comment]
this looks reasonable, but now I'm wondering whether this will only affect the driver.  Couldn't it also effect the executors?  Executors might get created as soon as there is a [`schedulerBackend`](https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/SparkContext.scala#L493) and they can register as soon as there is a blockManagerMaster, which is done as part of the [SparkEnv creation](https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/SparkContext.scala#L424) -- both happen before the EventLoggingListener is created.  so we'd need to do something different for that case, probably have the listenerBus buffer up events until we tell it all "primimary" listeners are registered.

I suppose that's an extremely unlikely race, so I might be overthinking this.  I do recall seeing cases where the executors didn't have info either, but I doubt this was the cause.

**Comment by vanzin** [comment]
Now that you mention that, the symptoms here look very similar to SPARK-22850. But this one was filed against 2.3.1...

I wonder if there's still some race in the queuing of initial events that we didn't catch.

**Comment by vanzin** [comment]
To be more explicit: events should be queued until `SparkContext.setupAndStartListenerBus()` is called, at which point the queued events should be delivered to all registered listeners even if they were added after the event was posted.

Since that method is called after the logging listener is installed, it should be getting all events. It it's not, there's a race in the listener bus, and this would be the wrong fix.

**Comment by squito** [comment]
ah, right, I thought the listenerbus was doing that, but couldn't find it, I was looking in the wrong place.

so @deshanxiao , given the discussion above, any chance you can share more info about what you're observing so we can determine the right fix?  ideally a snippet of the event logs and driver logs where you see this?

**Comment by deshanxiao** [comment]
@squito @vanzin Thanks, the first time I find it in our cluster is Spark2.1. Spark2.1 has the method `setupAndStartListenerBus`  too, but it still looks like wrong. The phenomenon of executor lose I find it in yesterday. Maybe we should fix them together.

**Comment by deshanxiao** [comment]
@vanzin Sorry..SPARK-22850 has fix the problem. Maybe I will track the executor lose problem next. Thank you!  @vanzin @squito

**Comment by squito** [comment]
can you please close this pr @deshanxiao ?

**Pull request closed without merging**
