### PR TITLE
[HOT-FIX][BUILD] Use the new location of `checkstyle-suppressions.xml`

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
## What changes were proposed in this pull request?

This PR fixes `dev/lint-java` and `mvn checkstyle:check` failures due the recent file location change.
The following is the error message of current master.

```
Checkstyle checks failed at following occurrences:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (default-cli) on project spark-parent_2.11: Failed during checkstyle configuration: cannot initialize module SuppressionFilter - Cannot set property 'file' to 'checkstyle-suppressions.xml' in module SuppressionFilter: InvocationTargetException: Unable to find: checkstyle-suppressions.xml -> [Help 1]
```
## How was this patch tested?

Manual. The following command should run correctly.

```
./dev/lint-java
mvn checkstyle:check
```

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Currently, Jenkins does not run `lint-java`. 
So this failure is not caught before.

**Comment by dongjoon-hyun** [comment]
Could you review this please?
@srowen and @rxin .

**Comment by dongjoon-hyun** [comment]
`PySpark` failure is irrelevant for this PR, but I rebased this PR to the master because this is still a problem.

**Comment by dongjoon-hyun** [comment]
Hi, @srowen and @rxin .

In the dev mailing list, there is another report about the location of `scalastyle-config.xml`.
In `pom.xml`, 
```
<configLocation>dev/scalastyle-config.xml</configLocation>
```
Should I include that FIX here together? 

It means moving `scalastyle-config.xml` into `dev`. 
I guess it is the correct location @srowen  designed. 
Otherwise, please let me know. I'll fix `pom.xml` instead.

**Comment by rxin** [comment]
Yes please do that too. Thanks.

**Comment by dongjoon-hyun** [comment]
Thank you! I see.

**Comment by srowen** [comment]
Ack, hm, that change should not have been in there. I don't know how it passed though. Yes this should be the right change because this file was not moved in the end.

**Comment by srowen** [comment]
The file needs to be moved up a level. I'm back online in 15 mins and can take a full look at what happened there.

**Comment by dongjoon-hyun** [comment]
Thank you, @srowen . The pom.xml file is updated as you said.

**Comment by srowen** [comment]
Ah, OK I see now:

- `scalastyle` config's location was referenced incorrectly. This was a change I should have backed out. I'm not sure why it passed the pull request builder tests then
- I was also not sure why breaking the style rule did in fact got flagged as if it were working: https://github.com/apache/spark/pull/11522 . I think it's because it found the config in its default location anyway?
- `checkstyle` config was never properly updated, and this wasn't caught since it doesn't actually run in the pull request builder (?)

This looks correct then, even given the ?s above. If it passes for several people, great. I'll merge once these tests pass.

**Comment by dongjoon-hyun** [comment]
About `?s part`, @zsxwing gave us some note and pointer in #11438 . 

> FYI because mvn checkstyle:check depends on mvn install which cost huge time for sbt, java style checker is disabled now: https://github.com/apache/spark/blob/master/dev/run-tests.py#L546

**Comment by srowen** [comment]
Merged to master. Thanks all, and sorry about that. I am not sure why the PR builder passed.

**Comment by dongjoon-hyun** [comment]
Thank you for merging.

**Pull request closed without merging**
