### PR TITLE
[SQL] remove redundant field "childOutput" from execution.Aggregate, use child.output instead

### PR DESCRIPTION
**Pull request by kai-zeng**

### CODE REVIEW

**Comment by sryza** [comment]
Hi Kai, mind tagging this [SQL] so it can get properly sorted?

**Comment by rxin** [comment]
Is child.output always guarantee to be available on workers?

**Comment by kai-zeng** [comment]
I think so, as execution.Project is also implemented this way

**Comment by rxin** [comment]
Are you sure? execution.Project doesn't actually use child.output on the executors ....

**Comment by kai-zeng** [comment]
In my opinion, buildProjection is transient lazy, so will be initialized on the executors, which will use child.output

**Comment by rxin** [comment]
Ah yes you are right. Going to merge this. Thanks.

**Pull request closed without merging**
