### PR TITLE
Add 1.3.x to valid versions in EC2 script and update default Spark version

### PR DESCRIPTION
**Pull request by bclune**
Minor changes based off of spark_ec2.py shipping with Spark 1.3.1 from https://spark.apache.org/

### CODE REVIEW

**Comment by bclune** [comment]
My mistake, it looks like the script doesn't like building 1.3.1 from source without some legwork. Closing for now.

**Comment by srowen** [comment]
Hm, though in principle I'm sure you're correct that this should be added.
Have you described what the problems were separately on the list?

**Comment by bclune** [comment]
@srowen I agree, the ec2 script should definitely support 1.3.1. As for problems with the 1.3.1 build, it is likely user error on my part (though 1.2.0 works fine).

I didn't see too many significant differences between the script in the official 1.3.1 release and the script here, aside from improvements in the master branch (particularly the --private-ips flag, which is missing from the official 1.3.1 release), but the scripts _are_ different---I can't seem to find anything in git that matches the official release's script.

How is the official release's spark-ec2 script being maintained?

**Comment by srowen** [comment]
I'm not the best person to ask but it should just be this script and released with releases.

**Comment by srowen** [comment]
Oh I see. @pwendell looks like you add these version updates with releases. Would it be good for me to cherry-pick those into master or would that interfere with your sub-process here? I'd guess master/1.4 could show everything through 1.4.0

**Pull request closed without merging**
