### PR TITLE
[SPARK-34302][FOLLOWUP][SQL][TESTS] Update jdbc.v2.*IntegrationSuite

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to update JDBC v2 integration suite by adding `catalogName`.

### Why are the changes needed?

To recover the integration test suite.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the GitHub Action.

### CODE REVIEW

**Review by cloud-fan — APPROVED** [review]

**Comment by cloud-fan** [comment]
thanks for fixing it!

BTW is there a way to capture it in PR builders? Otherwise, it's too easy to forget checking...

**Comment by dongjoon-hyun** [comment]
This seems to disabled by `ENABLE_DOCKER_INTEGRATION_TESTS` intentionally and designed to be turned on docker module change only at the original commit (2de19e460bb3b305d4d155709fb88ad97efd6142).

cc @sarutak and @HyukjinKwon .

**Comment by dongjoon-hyun** [comment]
I'll make a followup PR for SPARK-35483 to enable it for SQL part change, too.

**Comment by sarutak** [comment]
@dongjoon-hyun 
I think It's because docker-integration-tests don't depend on sql module in `dev/sparktestsupport/modules.py`.

We intentionally let the dependency empty after the [discussion](https://github.com/apache/spark/pull/32631#discussion_r640497898).
If it's better to depends on `sql` module, I'll fix it.

**Review by HyukjinKwon — APPROVED** [review]

**Review by sarutak — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Here is the follow-up for SPARK-35483.
- https://github.com/apache/spark/pull/33125/files

**Comment by dongjoon-hyun** [comment]
Docker integration test passed.
- https://github.com/dongjoon-hyun/spark/runs/2938755266?check_suite_focus=true

Merged to master. Thank you, @cloud-fan , @sarutak , @HyukjinKwon .

**Comment by imback82** [comment]
Thanks @dongjoon-hyun!

**Pull request closed without merging**
