### PR TITLE
[SPARK-12202][REPL] Parse Scala command line arguments

### PR DESCRIPTION
**Pull request by dragos**
..and pass them to the underlying REPL engine (only for Scala 2.11)

Fixes SPARK-12202

### CODE REVIEW

**Comment by dragos** [comment]
Spurious failure:

```
ERROR: Timeout after 15 minutes
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from https://github.com/apache/spark.git
```

**Comment by marmbrus** [comment]
ok to test

**Comment by vanzin** [comment]
Isn't this the same as #9824?

**Comment by dragos** [comment]
Oh, I missed that one. Yes, it's the same. I also show errors if any of the arguments doesn't parse, and stop execution in that case, but there's no reason this can't go in #9824

**Pull request closed without merging**
