### PR TITLE
[SPARK-9808] Remove spark.shuffle.consolidateFiles and associated implementation.

### PR DESCRIPTION
**Pull request by JoshRosen**
I think that we should remove `spark.shuffle.consolidateFiles` and its associated implementation for Spark 1.5.0. Rationale:
- This feature is not properly tested. The sole test for this feature in `HashShuffleManagerSuite` does not appear to be testing the right thing because it never enables shuffle file consolidation.
- The motivation for this feature, reducing the number of shuffle files created on disk, has been addressed by sort-based shuffle, which is better tested.
- Shuffle file consolidation does not work with the external shuffle service.

### CODE REVIEW

**Comment by JoshRosen** [comment]
I think we're actually going to wait until 1.6 for this.

**Comment by aarondav** [comment]
Heartbroken. Let's remove it.

Perhaps we can document its impending deprecation in 1.5.

**Comment by andrewor14** [comment]
Kill it kill it kill it!!

**Comment by JoshRosen** [comment]
```
[error]  * class org.apache.spark.shuffle.FileShuffleBlockResolver#ShuffleFileGroup does not have a correspondent in new version
[error]    filter with: ProblemFilters.exclude[MissingClassProblem]("org.apache.spark.shuffle.FileShuffleBlockResolver$ShuffleFileGroup")
```

Hmm, I guess that class confused MiMa because it's certainly not intended to be public.  I'm going to try adding a 1.5.0 MiMa exclude just because I'm curious to see if tests still pass.  Let's hold off on deciding how / whether to do this for 1.5.0 for now, though.

**Pull request closed without merging**
