### PR TITLE
[SPARK-20589][Core][Scheduler] Allow limiting task concurrency per job group

### PR DESCRIPTION
**Pull request by dhruve**
## What changes were proposed in this pull request?
This change allows the user to specify the maximum no. of tasks running in a given job group. (Kindly see the jira comments section for more context on why this is implemented at a job group level rather than a stage level). This change is beneficial where the user wants to avoid having a DoS while trying to access an eternal service from multiple executors without having the need to repartition or coalesce existing RDDs.

This code change introduces a new user level configuration: `spark.job.[userJobGroup].maxConcurrentTasks` which is used to set the active no. of tasks executing at a given point in time.

The user can use the feature by setting the appropriate jobGroup and passing the conf:

```
conf.set("spark.job.group1.maxConcurrentTasks", "10")
...
sc.setJobGroup("group1", "", false)
sc.parallelize(1 to 100000, 10).map(x => x + 1).count
sc.clearJobGroup
```

#### changes proposed in this fix 
This change limits the no. of tasks (in turn also the no. of executors to be acquired) than can run simultaneously in a given job group and its subsequent job/s and stage/s if the appropriate job group and max concurrency configs are set.

## How was this patch tested?
Ran unit tests and multiple manual tests with various combinations of:
- single/multiple/no job groups
- executors with single/multi cores
- dynamic allocation on/off

### CODE REVIEW

**Comment by dhruve** [comment]
@squito @markhamstra @tgravescs Can you review this PR. Thanks.

**Comment by dhruve** [comment]
Reopened this because CI was having issues with the previous PR. [18950](https://github.com/apache/spark/pull/18950)

**Comment by HyukjinKwon** [comment]
@dhruve, FYI, AppVeyor CI only runs SparkR tests on Windows only when there are changes in R related codes:

https://github.com/apache/spark/blob/75a6d05853fea13f88e3c941b1959b24e4640824/appveyor.yml#L29-L34

Thing is, it looks when `git merge` is performed, https://github.com/apache/spark/commit/8b3830004d69bd5f109fd9846f59583c23a910c7  (not `rebase`), that merging commit one includes usually some changes in R and then the CI is triggered, which is actually quite moderate. So, I think generally we should rebase it when there are conflicts.

**Comment by dhruve** [comment]
@HyukjinKwon Thanks for pointing this out. I will do a rebase and then do a push. The message from appveyor wasn't very obvious so I didn't realize.

**Pull request closed without merging**
