### PR TITLE
[SPARK-44922][TESTS] Disable o.a.p.h.InternalParquetRecordWriter logs for tests

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

This PR disable InternalParquetRecordWriter logs for SQL tests

### Why are the changes needed?

The InternalParquetRecordWriter creates over 1,800 records, which equates to more than 80,000 lines of code. This accounts for 80% of the volume of the "slow tests" before the GitHub action truncates it.

#### A record for example
```
2023-08-22T13:38:14.5103112Z 13:38:14.406 WARN org.apache.parquet.hadoop.InternalParquetRecordWriter: Too much memory used: Store {
2023-08-22T13:38:14.5103259Z  [dummy_col] optional int32 dummy_col {
2023-08-22T13:38:14.5103352Z   r:0 bytes
2023-08-22T13:38:14.5103444Z   d:0 bytes
2023-08-22T13:38:14.5103580Z    data: FallbackValuesWriter{
2023-08-22T13:38:14.5103739Z    data: initial: DictionaryValuesWriter{
2023-08-22T13:38:14.5103854Z    data: initial: dict:8
2023-08-22T13:38:14.5103976Z    data: initial: values:400
2023-08-22T13:38:14.5104079Z    data: initial:}
2023-08-22T13:38:14.5104087Z 
2023-08-22T13:38:14.5104325Z    data: fallback: PLAIN CapacityByteArrayOutputStream 0 slabs, 0 bytes
2023-08-22T13:38:14.5104418Z    data:}
2023-08-22T13:38:14.5104426Z 
2023-08-22T13:38:14.5104695Z    pages: ColumnChunkPageWriter ConcatenatingByteArrayCollector 0 slabs, 0 bytes
2023-08-22T13:38:14.5104795Z    total: 400/408
2023-08-22T13:38:14.5104936Z  }
2023-08-22T13:38:14.5105129Z  [expected_rowIdx_col] optional int32 expected_rowIdx_col {
2023-08-22T13:38:14.5105291Z   r:0 bytes
2023-08-22T13:38:14.5105383Z   d:0 bytes
2023-08-22T13:38:14.5105518Z    data: FallbackValuesWriter{
2023-08-22T13:38:14.5105679Z    data: initial: DictionaryValuesWriter{
2023-08-22T13:38:14.5105797Z    data: initial: dict:400
2023-08-22T13:38:14.5105919Z    data: initial: values:400
2023-08-22T13:38:14.5106022Z    data: initial:}
2023-08-22T13:38:14.5106030Z 
2023-08-22T13:38:14.5106267Z    data: fallback: PLAIN CapacityByteArrayOutputStream 0 slabs, 0 bytes
2023-08-22T13:38:14.5106356Z    data:}
2023-08-22T13:38:14.5106364Z 
2023-08-22T13:38:14.5106636Z    pages: ColumnChunkPageWriter ConcatenatingByteArrayCollector 0 slabs, 0 bytes
2023-08-22T13:38:14.5106736Z    total: 400/800
2023-08-22T13:38:14.5106820Z  }
2023-08-22T13:38:14.5106942Z  [id] required int64 id {
2023-08-22T13:38:14.5107037Z   r:0 bytes
2023-08-22T13:38:14.5107133Z   d:0 bytes
2023-08-22T13:38:14.5107275Z    data: FallbackValuesWriter{
2023-08-22T13:38:14.5107436Z    data: initial: DictionaryValuesWriter{
2023-08-22T13:38:14.5107557Z    data: initial: dict:800
2023-08-22T13:38:14.5107677Z    data: initial: values:400
2023-08-22T13:38:14.5107779Z    data: initial:}
2023-08-22T13:38:14.5107787Z 
2023-08-22T13:38:14.5108022Z    data: fallback: PLAIN CapacityByteArrayOutputStream 0 slabs, 0 bytes
2023-08-22T13:38:14.5108113Z    data:}
2023-08-22T13:38:14.5108121Z 
2023-08-22T13:38:14.5108384Z    pages: ColumnChunkPageWriter ConcatenatingByteArrayCollector 0 slabs, 0 bytes
2023-08-22T13:38:14.5108485Z    total: 800/1,200
2023-08-22T13:38:14.5108570Z  }
2023-08-22T13:38:14.5108655Z }
2023-08-22T13:38:14.5108664Z 
```
### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

see log volume of SQL tests

### Was this patch authored or co-authored using generative AI tooling?

no

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Thank you for investigating and proposing this. Could you make a JIRA issue for this? I believe we need to backport this and it means we had better to have ID for trace-ability, @yaooqinn .

**Comment by HyukjinKwon** [comment]
yeah, let's file a JIRA.

**Comment by yaooqinn** [comment]
Hi @dongjoon-hyun @HyukjinKwon, thanks for the suggestion, the associate JIRA ticket has been attached.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @yaooqinn .

**Comment by yaooqinn** [comment]
Test failures in RocksDBStateStore are frequently occurring and irrelevant.

thanks @dongjoon-hyun @HyukjinKwon 

Merged to master/3.5/3.4.

**Comment by LuciferYang** [comment]
late LGTM

**Pull request closed without merging**
