### PR TITLE
[SPARK-5131][Streaming][DOC]: There is a discrepancy in WAL implementation and configuration doc.

### PR DESCRIPTION
**Pull request by uncleGen**
There is a discrepancy in WAL implementation and configuration doc.

### CODE REVIEW

**Comment by srowen** [comment]
A similar typo exists in the `streaming-programming-guide.md` doc.

**Comment by uncleGen** [comment]
@srowen oops, I missed.
.

**Comment by jerryshao** [comment]
Good catch.

**Comment by andrewor14** [comment]
@tdas

**Comment by tdas** [comment]
Yeah. Merging this and backporting to 1.2 branch.

**Comment by andrewor14** [comment]
It appears that @tdas may have forgotten to merge this, so I put it in master and 1.2 on his behalf.

**Comment by tdas** [comment]
@andrewor14 hey ... thanks! Yeah I think I hadnt pushed to apache before my laptop crashed and I forgot about it.

**Comment by andrewor14** [comment]
I guess you didn't have a write-ahead log to recover from.

**Pull request closed without merging**
