### PR TITLE
[SPARK-44269][SQL] Assign names to the error class _LEGACY_ERROR_TEMP_[2310-2314]

### PR DESCRIPTION
**Pull request by beliefer**
### What changes were proposed in this pull request?
The pr aims to assign names to the error class _LEGACY_ERROR_TEMP_[2310-2314].

### Why are the changes needed?
Improve the error framework.

### Does this PR introduce _any_ user-facing change?
'No'.

### How was this patch tested?
Exists test cases updated and added new test cases.

### CODE REVIEW

**Review by MaxGekk — APPROVED** [review]
Waiting for CI.

**Comment by beliefer** [comment]
@MaxGekk The GA passed.

**Comment by MaxGekk** [comment]
+1, LGTM. Merging to master.
Thank you, @beliefer.

**Comment by beliefer** [comment]
@MaxGekk Thank you!

**Pull request closed without merging**
