### PR TITLE
[SPARK-50228][SQL] Move the `RewriteCollationJoin` rule to `FinishAnalysis`

### PR DESCRIPTION
**Pull request by MaxGekk**
### What changes were proposed in this pull request?
In the PR, I propose to move the `RewriteCollationJoin` rule added by https://github.com/apache/spark/pull/46599 to `FinishAnalysis`.

### Why are the changes needed?
The conversions of join keys that the rule does **should not be** considered as an optimization, but it is needed for correctness. So, we shall not run it as an optimization rule, it should be applied before any. Currently, optimization rules can produce plans (for instance, sub-queries) that become semantically incorrect after `RewriteCollationJoin`.

We could modify `RewriteCollationJoin` and take into account DPP and maybe other optimizations, but might miss something else. Fxing **all** results of optimizations in `RewriteCollationJoin` introduces some unnecessary dependencies.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
By existing GAs. It is improssible to test wrong results of DPP because non-binary collated strings as partitions have not been supported by any built-in datasources yet.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by MaxGekk** [comment]
also cc @uros-db @stefankandic @c27kwan

**Review by stefankandic — APPROVED** [review]
LGTM

**Review by uros-db — APPROVED** [review]
I don't fully agree with the "it's correctness" argument - if you don't perform the rule, join keys will not be binary stable, and spark strategy will opt for SMJ instead

with this in mind, rewriting collation join conditions by injecting sort keys in place of strings is indeed a perf optimization (leads to using HJ)

on another note, I'm fine with moving the rule to FinishAnalysis - although @cloud-fan may want to chime in on this as well, given the initial decision of where to include this rule

**Comment by MaxGekk** [comment]
>  rewriting collation join conditions by injecting sort keys in place of strings is indeed a perf optimization

@uros-db An optimization rule should not modify semantic of a query, but your rule seems does. There could be at least 2 reasons either the rule is incorrect, or it is not an optimization rule. If you insist that it is an optimization one, in that case it is incorrect because it produces incorrect plan after DPP (which produces a correct plan). So, either we must fix ALL results of optimizations including DPP/DFP and others in your rule, or move out from optimizations. I would prefer the last one to don't introduce implict dependcies in your rules from other optimizations.

**Comment by uros-db** [comment]
@MaxGekk yes, this is a good point - in the current state we unfortunately don't have complete coverage. Considering this, I'm onboard with your proposal - but I would also like us to make this purely QO sometime in the future

**Review by cloud-fan — APPROVED** [review]
At least this change makes sure we have consistency for join keys and DPP filters that are inferred from join keys. LGTM

**Comment by MaxGekk** [comment]
Merging to master. Thank you, @uros-db @stefankandic @cloud-fan for review.

**Pull request closed without merging**
