### PR TITLE
[SPARK-34046][SQL][TESTS] Use join hint for constructing joins in JoinSuite and WholeStageCodegenSuite

### PR DESCRIPTION
**Pull request by gengliangwang**
### What changes were proposed in this pull request?

There are some existing test cases that constructing various joins by tuning the SQL configuration AUTO_BROADCASTJOIN_THRESHOLD, PREFER_SORTMERGEJOIN,SHUFFLE_PARTITIONS, etc.

This can be tricky and not straight-forward. In the future development we might have to tweak the configurations again . 
This PR is to construct specific joins by using join hint in test cases. 
### Why are the changes needed?

Make test cases for join simpler and more robust.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Unit test

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Thank you, @gengliangwang . The change looks clear and better, but the title looks a little too broad because this is a partial subset of those instances. Could you revise the PR title more specific? You may want to mention two test suite (which is touched in this PR) explicitly in the PR title.

For example, `BroadcastJoinSuite` has more instances like the following.
```
withSQLConf(SQLConf.AUTO_BROADCASTJOIN_THRESHOLD.key -> "-1") {
```

**Comment by gengliangwang** [comment]
@dongjoon-hyun Thanks. I have updated the title

**Review by cloud-fan — APPROVED** [review]
LGTM, we can slowly fix other test suites one by one later.

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Comment by dongjoon-hyun** [comment]
Thank you!

**Pull request closed without merging**
