### PR TITLE
[SPARK-16924][SQL] - Support option("inferSchema", true) for DataStreamReader

### PR DESCRIPTION
**Pull request by xwu0226**
## What changes were proposed in this pull request?

The issue is that `DataSource.sourceSchema()` has a check against only the SQLConf setting `spark.sql.streaming.schemaInference`, which is only set at the Session level. So even though the user specify `option("inferSchema", true)` as they would usually do for `DataFrameReader` for csv/json file, DataSource.sourceSchema() does not know. and this option is not passed down to `CSVFileFormat.inferSchema`.

This PR is to combine the checking of both the value of `spark.sql.streaming.schemaInference` and the `option("inferSchema")`.
## How was this patch tested?

New unit test added to test creating streaming DataSet with `option("inferSchema", true)`
And ran the regression buckets.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
If my understanding is correct, JSON one does have have `inferSchema` option.

**Comment by HyukjinKwon** [comment]
Actually, `inferSchema` in CSV would be CSV-datasource specific option in order to allow read the headers as column names but to avoid infer the schema.

**Comment by xwu0226** [comment]
@HyukjinKwon Thank you for reviewing and pointing this out.
Looking deeper into the code, I agree with you. Actually, even CSV file can have default schema with StringType for each column, which means it does not require inferring schema or `userSpecifiedSchema`. And JSON file format can inferSchema automatically. Text File format also only uses single column "value" of StringType as schema. So the original error thrown in `DataSource.sourceSchema` should not be related to whether or not inferSchema is specified. 

Refer to the existing code:
```
val isSchemaInferenceEnabled = sparkSession.conf.get(SQLConf.STREAMING_SCHEMA_INFERENCE)
val isTextSource = providingClass == classOf[text.TextFileFormat]
 // If the schema inference is disabled, only text sources require schema to be specified
 if (!isSchemaInferenceEnabled && !isTextSource && userSpecifiedSchema.isEmpty) {
      throw new IllegalArgumentException(
            "Schema must be specified when creating a streaming source DataFrame. " +
              "If some files already exist in the directory, then depending on the file format " +
              "you may be able to create a static DataFrame on that directory with " +
              "'spark.read.load(directory)' and infer schema from it.")
  }
```
I think the real problem now are:
1. Why do we even need to have a checking of `inferSchema`, `userSpecifiedSchema`, and `isTextSource` in `DataSource.sourceSchema` for FileFormat case?   
2. `!isTextSource` condition is the wrong, it should be `isTextSource`, according to the comment. This is the direct cause of the error, since CSV file or JSON file are not TextFileFormat. Plus, text file only has default one column schema.
3. In order to make SQLConf setting "`spark.sql.streaming.schemaInference`" or `option("inferSchema", true)` to be effective for CSVFileFormat, we need code to handle that in `DataSource.inferFileFormatSchema` for CSVFileFormat case. 

What do you think?

**Comment by HyukjinKwon** [comment]
1. I think this issue is related with the question, https://issues.apache.org/jira/browse/SPARK-15458. It seems we want to disable the inference and promote to give schema explicitly in this case.

2. If it is not text data source, I think we should avoid the schema inference due the some problems listed in the issue above. If it becomes `isTextSource` I think we will allow the schema inference even if `spark.sql.streaming.schemaInference` is disabled. I think the comment means it does not throw an exception but set the inferred schema.

3. If my understanding is correct, `inferSchema` in CSV is different with `spark.sql.streaming.schemaInference` nor the case when `userSpecifiedSchema` is not given.

For CSV, we can directly use header as column names, so we have three choices.

- Schema is given and `inferSchema` is `false`: Don't infer schema and don't use header
- Schema is not given and `inferSchema` is `false`: Use header as column names but don't infer schema
- Schema is not given and `inferSchema` is `true`: User header as column names and also infer schema

**Comment by HyukjinKwon** [comment]
To the original issue here, `inferSchema` is CSV-specific option. I guess we don't need this option for other sources because,

- we need anyway to read the same amount of data for JSON (entire scan), Parquet (footer) and ORC (footer) regardless of `inferSchema` 
- whereas CSV only reads the header when `inferSchema` is `false` and needs an entire scan when `inferSchema` is `true`.

**Comment by xwu0226** [comment]
I see. So the purpose of `spark.sql.streaming.schemaInference` is to allow/disallow Spark SQL to infer schema on streaming file datasource. A bit confusion here. Many thanks!  
For CSV file format, I also tried the following on a csv file that has header line for column names:
```
scala> spark.conf.set("spark.sql.streaming.schemaInference", true)
scala> val in = spark.readStream.format("csv").load("/Users/xinwu/spark-test/data/csv1")
in: org.apache.spark.sql.DataFrame = [_c0: string, _c1: string]
scala> val in = spark.readStream.format("csv").option("header", true).load("/Users/xinwu/spark-test/data/csv1")
in: org.apache.spark.sql.DataFrame = [signal: string, flash: string]
scala> val in = spark.readStream.format("csv").option("header", true).option("inferSchema", true).load("/Users/xinwu/spark-test/data/csv1")
in: org.apache.spark.sql.DataFrame = [signal: string, flash: int]
```
And the output looks expected on master branch's code. So I think there is nothing wrong here so far. It was my misunderstanding of the purpose of `spark.sql.streaming.schemaInference`. Unless you think differently, I will close this PR.

**Comment by HyukjinKwon** [comment]
Thank you for all your comments as well. Maybe we can close this if you think this is not an issue.

**Pull request closed without merging**
