### PR TITLE
[SPARK-42152][BUILD][CORE][SQL][PYTHON][PROTOBUF] Use `_` instead of `-`  for relocation package name

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr aims change to use `_` instead of `-`  for relocation package name,  the package name in the relevant comments also fix in this pr.

### Why are the changes needed?
Refer to https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html, Java package name can use `_`, not `-`:

image

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass GitHub Actions

### CODE REVIEW

**Review by itholic — APPROVED** [review]
Looks pretty good to me.

Maybe adding https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html to the PR description would make this change looks more reasonable.

**Comment by LuciferYang** [comment]
@itholic Thanks for your suggestion, pr description has been updated

**Comment by LuciferYang** [comment]
also cc @srowen @dongjoon-hyun @HyukjinKwon

**Review by srowen — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by LuciferYang** [comment]
Thanks @HyukjinKwon @srowen @dongjoon-hyun @itholic  ~

**Comment by dongjoon-hyun** [comment]
@rangadi , this is not a breaking change yet in terms of the Apache Spark community perspective because the Apache Spark community didn't release it yet.

**Comment by rangadi** [comment]
@dongjoon-hyun sure. I know @SandishKumarHN's company is already using this in production. That's why I mentioned it as breaking change for them.

**Pull request closed without merging**
