### PR TITLE
[SPARK-12652][PySpark]Upgrade Py4J to 0.9.1

### PR DESCRIPTION
**Pull request by zsxwing**
- [x] Upgrade Py4J to 0.9.1
- [x] SPARK-12657: Revert SPARK-12617
- [x] SPARK-12658: Revert SPARK-12511
  - Still keep the change that only reading checkpoint once. This is a manual change and worth to take a look carefully. https://github.com/zsxwing/spark/commit/bfd4b5c040eb29394c3132af3c670b1a7272457c
- [x] Verify no leak any more after reverting our workarounds

### CODE REVIEW

**Comment by JoshRosen** [comment]
Jenkins, retest this please.

**Comment by zsxwing** [comment]
retest this please

**Comment by zsxwing** [comment]
```
Traceback (most recent call last):
  File "/usr/lib64/python2.6/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "/home/jenkins/workspace/SparkPullRequestBuilder/python/pyspark/streaming/tests.py", line 1638, in <module>
    kafka_assembly_jar = search_kafka_assembly_jar()
  File "/home/jenkins/workspace/SparkPullRequestBuilder/python/pyspark/streaming/tests.py", line 1564, in search_kafka_assembly_jar
    "remove all but one") % (", ".join(jars)))
Exception: Found multiple Spark Streaming Kafka assembly JARs: /home/jenkins/workspace/SparkPullRequestBuilder/external/kafka-assembly/target/scala-2.10/spark-streaming-kafka-assembly-2.0.0-SNAPSHOT.jar, /home/jenkins/workspace/SparkPullRequestBuilder/external/kafka-assembly/target/spark-streaming-kafka-assembly_2.10-spark-581766.jar; please remove all but one
```
This is pretty weird. Where did `/home/jenkins/workspace/SparkPullRequestBuilder/external/kafka-assembly/target/spark-streaming-kafka-assembly_2.10-spark-581766.jar` come from? @JoshRosen did you see any similar issue?

**Comment by zsxwing** [comment]
retest this please

**Comment by JoshRosen** [comment]
@zsxwing, that file is generated as part of the dummy publishing step which is used to produce POMs for use by the `dev/test-dependencies` checks. Ping me if it happens again and I'll look at the build logs to see if I can figure out what those aren't being cleaned up. We might have to add an additional clean step somewhere.

**Comment by JoshRosen** [comment]
Actually, I think I've spotted the problem. Working on a small fix now.

**Comment by JoshRosen** [comment]
I've opened https://github.com/apache/spark/pull/10704 to fix this

**Comment by zsxwing** [comment]
By the way, I packed py4j-0.9.1-src.zip by myself since I could not find it anywhere.

**Comment by JoshRosen** [comment]
Jenkins, retest this please.

**Comment by JoshRosen** [comment]
PY4J zip packaging and source diffs look good to me, so I think this is good-to-go pending tests.

**Comment by zsxwing** [comment]
> PY4J zip packaging and source diffs look good to me, so I think this is good-to-go pending tests.

This is not ready for merging. I plan to revert our workarounds for Py4J issues in this PR.

**Comment by zsxwing** [comment]
@JoshRosen @davies could you take a look?

**Comment by davies** [comment]
@zsxwing Could you also update the patch for callback server to use new API? see https://github.com/bartdag/py4j/issues/147

**Comment by zsxwing** [comment]
> @zsxwing Could you also update the patch for callback server to use new API? see bartdag/py4j#147

Updated

**Comment by zsxwing** [comment]
@davies could you take a look at my latest commit?

**Comment by davies** [comment]
LGTM

**Comment by zsxwing** [comment]
Thanks, merging to master

**Comment by sarathjiguru** [comment]
Hello @zsxwing ,

This PR is not merged with branch-1.6. Is there a reason for it?
I am hoping latest version of py4j is needed for production ready spark streaming jobs. Please let me know if it is not the case. 

Commits on Jan 13:
Master: https://github.com/apache/spark/commits/master?page=38
v1.6.1: https://github.com/apache/spark/commits/v1.6.1?page=3
branch-1.6: https://github.com/apache/spark/commits/branch-1.6?page=5

This particular commit is not merged with branch-1.6.

**Comment by zsxwing** [comment]
> This PR is not merged with branch-1.6. Is there a reason for it?

@sarathjiguru as we have already merged workarounds to branch-1.6, it's not necessary to upgrade Py4j for 1.6.

**Pull request closed without merging**
