### PR TITLE
[SPARK-29255][SQL][TESTS] Rename package pgSQL to postgreSQL

### PR DESCRIPTION
**Pull request by gengliangwang**
### What changes were proposed in this pull request?

Rename the package pgSQL to postgreSQL

### Why are the changes needed?

To address the comment in https://github.com/apache/spark/pull/25697#discussion_r328431070 . The official full name seems more reasonable.

### Does this PR introduce any user-facing change?

No.

### How was this patch tested?

Existing unit tests.

### CODE REVIEW

**Comment by maropu** [comment]
Looks ok to me. also cc: @dongjoon-hyun @HyukjinKwon

**Review by wangyum — APPROVED** [review]

**Comment by gengliangwang** [comment]
retest this please.

**Comment by dongjoon-hyun** [comment]
@gengliangwang . Could you handle the followings together?
```
$ git grep pgSQL
sql/core/src/test/resources/sql-tests/inputs/udf/postgreSQL/udf-aggregates_part1.sql:-- This test file was converted from pgSQL/aggregates_part1.sql.
sql/core/src/test/resources/sql-tests/inputs/udf/postgreSQL/udf-aggregates_part2.sql:-- This test file was converted from pgSQL/aggregates_part2.sql.
sql/core/src/test/resources/sql-tests/inputs/udf/postgreSQL/udf-aggregates_part3.sql:-- This test file was converted from pgSQL/aggregates_part3.sql.
sql/core/src/test/resources/sql-tests/inputs/udf/postgreSQL/udf-aggregates_part4.sql:-- This test file was converted from pgSQL/aggregates_part4.sql.
sql/core/src/test/resources/sql-tests/inputs/udf/postgreSQL/udf-case.sql:-- This test file was converted from pgSQL/case.sql.
sql/core/src/test/resources/sql-tests/inputs/udf/postgreSQL/udf-join.sql:-- This test file was converted from pgSQL/join.sql.
sql/core/src/test/resources/sql-tests/inputs/udf/postgreSQL/udf-select_having.sql:-- This test file was converted from inputs/pgSQL/select_having.sql
sql/core/src/test/resources/sql-tests/inputs/udf/postgreSQL/udf-select_implicit.sql:-- This test file was converted from pgSQL/select_implicit.sql
```

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM except only the above minor request (changing the path in `sql` script comment consistently).

**Review by HyukjinKwon — APPROVED** [review]
LGTM too except @dongjoon-hyun's comments

**Comment by gengliangwang** [comment]
@dongjoon-hyun Thanks for the suggestion.
The output of `git grep pgSQL` is now empty.

**Comment by wangyum** [comment]
Merged to master.

**Comment by dongjoon-hyun** [comment]
Thank you all!

**Comment by maropu** [comment]
Thanks, @gengliangwang !

**Pull request closed without merging**
