### PR TITLE
[SPARK-3778] newAPIHadoopRDD doesn't properly pass credentials for secure hdfs

### PR DESCRIPTION
**Pull request by tgravescs**
https://issues.apache.org/jira/browse/SPARK-3778

This affects if someone is trying to access secure hdfs something like:
val lines = {
      val hconf = new Configuration()
      hconf.set("mapred.input.dir", "mydir")
      hconf.set("textinputformat.record.delimiter","\003432\n")
      sc.newAPIHadoopRDD(hconf, classOf[TextInputFormat], classOf[LongWritable], classOf[Text])
    }

### CODE REVIEW

**Comment by harishreedharan** [comment]
We really need to merge this soon. This actually makes the NewHadoopRDD useless on secure clusters (users would need to work around this in their own code, and the error message is not even obvious).

**Comment by pwendell** [comment]
Hey guys - sorry don't block on my comment. If you all think this looks good, just merge it.

**Comment by pwendell** [comment]
@tgravescs mind brining it up to date?

**Comment by pwendell** [comment]
I bumped the severity per @harishreedharan's commnet.

**Comment by tgravescs** [comment]
I'll try to bring it up to date today.  I'm out all next week though so if you find issues someone else might need to take it over.

**Comment by tgravescs** [comment]
for whatever reason this pull request didn't update.  Filed new one:
https://github.com/apache/spark/pull/4292

Its rebased and I made the comment change suggested by @JoshRosen

**Pull request closed without merging**
