### PR TITLE
[SPARK-41247][BUILD][FOLLOWUP] Make sbt and maven use the same Protobuf version

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
https://github.com/apache/spark/pull/38783 unify the Protobuf versions in Spark connect and Protobuf connector to `3.21.9` for maven, but sbt build and test still use `3.21.1`, so this pr make sbt also use Protobuf 3.21.9 to build and test.

### Why are the changes needed?
Make sbt and maven use the same Protobuf version for build and test

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass Github Actions

### CODE REVIEW

**Comment by amaliujia** [comment]
LGTM

Could you add `[CONNECT]` to your PR title? I found this is very useful to `git log` and filter all CONNET commits when there is a need.

**Comment by LuciferYang** [comment]
I'm not sure whether [CONNECT] and [PROTOBUF] should be added to this pr, should they be added @HyukjinKwon ?

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

`[SPARK-41247][BUILD][FOLLOWUP]` is correct.

**Comment by LuciferYang** [comment]
Thanks for your confirmation @dongjoon-hyun

**Review by gengliangwang — APPROVED** [review]

**Review by zhengruifeng — APPROVED** [review]
also cc @grundprinzip

**Review by HyukjinKwon — APPROVED** [review]
Thanks @LuciferYang

**Comment by LuciferYang** [comment]
All test passed

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by LuciferYang** [comment]
Thanks @HyukjinKwon @dongjoon-hyun  @gengliangwang @zhengruifeng @amaliujia

**Pull request closed without merging**
