### PR TITLE
[SPARK-14572] [Doc] Update config docs to allow -Xms in extraJavaOptions

### PR DESCRIPTION
**Pull request by dhruve**
## What changes were proposed in this pull request?

The configuration docs are updated to reflect the changes introduced with [SPARK-12384](https://issues.apache.org/jira/browse/SPARK-12384). This allows the user to specify initial heap memory settings through the extraJavaOptions for executor, driver and am. 
## How was this patch tested?

The changes are tested in [SPARK-12384](https://issues.apache.org/jira/browse/SPARK-12384). This is just documenting the changes made.

### CODE REVIEW

**Comment by srowen** [comment]
I don't think this is useful to state, per JIRA.

**Comment by dhruve** [comment]
@srowen Even if we don't specify explicitly that -Xms can be set, we will need to update the doc which currently states that it is illegal to specify heap memory settings.

**Comment by tgravescs** [comment]
So I agree its not explicitly necessary to state Xms here, the only reason I think to mention it is the behavior is different from 1.X to 2.X, but there will be many other things different to so not a big deal to me on that.

I do think some of the other text he added here is useful though and makes the descriptions across driver/executor/am more consistent.

@srowen   What do you think about just removing the sentence "However, specifying an initial heap
 +  size (-Xms) is allowed" from the config descriptions but leaving the rest?

**Comment by tgravescs** [comment]
@dhruve you should put the jira name int he pr description. 

Please see guidelines at: https://cwiki.apache.org/confluence/display/SPARK/Contributing+to+Spark#ContributingtoSpark-PullRequest

**Comment by srowen** [comment]
@tgravescs I agree with that suggestion

**Comment by dhruve** [comment]
I have updated the docs and removed the explicit mentions of Xms being allowed.

**Comment by srowen** [comment]
LGTM

**Comment by tgravescs** [comment]
Jenkins, test this please

**Comment by tgravescs** [comment]
+1, just doc changes so shouldn't really need jenkins, but kicked anyway.

**Pull request closed without merging**
