### PR TITLE
[SPARK-37879][INFRA][FOLLOWUP] Change actions to check-runs in update_build_status.yml

### PR DESCRIPTION
**Pull request by Yikun**
### What changes were proposed in this pull request?
Change actions to check-runs in update_build_status.yml.

### Why are the changes needed?
https://github.com/apache/spark/pull/35179#issuecomment-1011881076

### Does this PR introduce _any_ user-facing change?
No

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Let's just get this in first.

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by HyukjinKwon** [comment]
Ah, this only checks the status of "Configure Jobs" .. am gonna revert this and original PR for now.

**Comment by Yikun** [comment]
Yep, below is the right way for update_build_status:
1. First get the check_suite id:
https://api.github.com/repos/Yikun/spark/check-runs/4797718278
2. Then we need a extra api request on check-suites, get the status of check-suites as final status
https://api.github.com/repos/Yikun/spark/check-suites/4918519335

**Pull request closed without merging**
