### PR TITLE
[SPARK-9222] [MLlib] Make class instantiation variables in DistributedLDAModel private[clustering]

### PR DESCRIPTION
**Pull request by MechCoder**
This makes it easier to test all the class variables of the DistributedLDAmodel.

### CODE REVIEW

**Comment by MechCoder** [comment]
@jkbradley

**Comment by MechCoder** [comment]
jenkins, my friend retest this please

**Comment by jkbradley** [comment]
LGTM, except for the merge conflicts.  Btw, there may be a lot going on with LDA this coming week, so I'll try to focus on reviewing 1 LDA PR at a time to avoid unnecessary rebasing.

**Comment by MechCoder** [comment]
rebased and pushed by force

**Comment by jkbradley** [comment]
LGTM, merging with master.  Thanks!

**Comment by MechCoder** [comment]
I noticed that there are todo's in the LDAModel.scala file. Would you want me to fix them up, because it would be a good exercise?

**Comment by jkbradley** [comment]
If one of them seems major, that would be great.  But if they are minor, I think we should wait until after the 1.5 cutoff (in 1 week), so that more major changes can get in.  This PR is making some big changes to LDA, btw: [https://github.com/apache/spark/pull/7507]

**Pull request closed without merging**
