### PR TITLE
[SPARK-12143]When cloumn type is binary, change to Array[Byte] instead of string

### PR DESCRIPTION
**Pull request by XuTingjun**
In Beeline, execute below sql:
1. create table bb(bi binary);
2. load data inpath 'tmp/data' into table bb;
3.select \* from bb;
Error: java.lang.ClassCastException: java.lang.String cannot be cast to [B (state=, code=0)

### CODE REVIEW

**Comment by andrewor14** [comment]
@yhuai

**Comment by marmbrus** [comment]
Please add a regression test with any bug fix.  Look in `HiveThriftBinaryServerSuite`

**Comment by JoshRosen** [comment]
Ping @XuTingjun, can you add a regression test?

**Comment by JoshRosen** [comment]
Ping again? Safe to assume that this is abandoned at this point?

**Pull request closed without merging**
