### PR TITLE
[SPARK-46124][CORE][SQL][SS][CONNECT][DSTREAM][MLLIB][ML][PYTHON][R][AVRO][K8S][YARN][UI] Replace explicit  `ArrayOps#toSeq` with `s.c.immutable.ArraySeq.unsafeWrapArray`

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
There is a behavioral difference between Scala 2.13 and 2.12 for explicit `ArrayOps.toSeq` calls, similar to the implicit conversion from `Array` to `Seq`.

In Scala 2.12, `ArrayOps.toSeq` will return `thisCollection` ,  and use implicit conversion rules to wrap the `Array` as `mutable.WrappedArray`, this process does not involve any collection copy:

```scala
Welcome to Scala 2.12.18 (OpenJDK 64-Bit Server VM, Java 17.0.9).
Type in expressions for evaluation. Or try :help.

scala> Array(1,2,3).toSeq
res0: Seq[Int] = WrappedArray(1, 2, 3)
```

However, in Scala 2.13, it returns an `immutable.ArraySeq` that with collection copy.

Since we have always used the non-collection copy behavior for this explicit conversion in the era of Scala 2.12, it is safe to assume that no collection copy is needed for Scala 2.13.

Therefore, this pr replaces explicit `ArrayOps.toSeq` in the Spark code with `s.c.immutable.ArraySeq.unsafeWrapArray` to avoid a collection copy, and this pr only involves changes to the production code, and does not involve changes to the test code. 

### Why are the changes needed?
Replace `ArrayOps#toSeq` with `s.c.immutable.ArraySeq.unsafeWrapArray` to save a collection copy, which has potential benefits for performance."

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass GitHub Action

### Was this patch authored or co-authored using generative AI tooling?
No

### CODE REVIEW

**Comment by LuciferYang** [comment]
cc @srowen, could you help to review this pr if you have time. Thanks 

Similar to https://github.com/apache/spark/pull/43666, the purpose of this pr is also to save a collection copy by using `immutable.ArraySeq.unsafeWrapArray `. This pr does not modify similar cases in the test code, and I do not plan to fix test code parts for the time being.

**Comment by srowen** [comment]
Seems reasonable to me, continuing the same refactoring. Is it ready?

**Comment by LuciferYang** [comment]
Yes, it's ready

**Comment by LuciferYang** [comment]
@srowen this PR Is ready, should we push it forward?

**Comment by srowen** [comment]
Merged to master

**Comment by LuciferYang** [comment]
Thanks @srowen

**Pull request closed without merging**
