### PR TITLE
[SPARK-20333] HashPartitioner should be compatible with num of child RDD's partitions.

### PR DESCRIPTION
**Pull request by jinxing64**
## What changes were proposed in this pull request?

Fix test 
"don't submit stage until its dependencies map outputs are registered (SPARK-5259)" ,
"run trivial shuffle with out-of-band executor failure and retry",
"reduce tasks should be placed locally with map output"
in DAGSchedulerSuite.

### CODE REVIEW

**Comment by jinxing64** [comment]
I found this when doing https://github.com/apache/spark/pull/17533

**Comment by jinxing64** [comment]
@squito @srowen 
Could you help comment on this :)

**Comment by jinxing64** [comment]
@kayousterhout @mridulm
Does this pr make sense? 
Could you please take a look this when you have time :)

**Comment by jiangxb1987** [comment]
The test cases are not falling on master branch, are there some good reason to change them?

**Comment by jinxing64** [comment]
@jiangxb1987 
Thank you so much taking time looking into this.
Yes, it is not failing in existing code. But I think it's quite straightforward that partitioner should be compatible with num of child RDD's partitions, right?
In #17533, I have to query the `MapStatus` based on the correctness of partitioner(i.e. num of partitions). That's why I proposed this.
Thanks again taking time reviewing this :) 👍

**Comment by jiangxb1987** [comment]
Don't think we could fail on the original test case for any reason, otherwise the legacy user code could fail unexpectedly, isn't it?

**Comment by jinxing64** [comment]
Yes.  it doesn't fail for sure.
I just think it's fairly  straightforward that partitioner should be compatible with num of child RDD's partitions. I find no reason the num of partitions are not equal in those test.

**Comment by squito** [comment]
lgtm.
sorry for such a late review.  Since its been a while I'll trigger tests again just to be safe before merging.

**Comment by squito** [comment]
merged to master

**Comment by jinxing64** [comment]
@squito 
Thanks a lot for merging :)

**Pull request closed without merging**
