### PR TITLE
[SPARK-30604][CORE] Fix a log message by including hostLocalBlockBytes to total bytes

### PR DESCRIPTION
**Pull request by Udbhav30**
### What changes were proposed in this pull request?

 Add HostLocalBlock size in log total bytes 

### Why are the changes needed?
total size in log is wrong as hostlocal block size is missed

### Does this PR introduce any user-facing change?
no

### How was this patch tested?
Manually checking the log

### CODE REVIEW

**Comment by Udbhav30** [comment]
@dongjoon-hyun please review

**Comment by dongjoon-hyun** [comment]
Thank you for pinging me.

**Comment by dongjoon-hyun** [comment]
ok to test

**Comment by dongjoon-hyun** [comment]
@Udbhav30 
BTW, why do you remove the required template? Although you cannot describe how to do, please add back and mentioned like `Manually checking the log` at least.
> ### How was this patch tested?

**Review by dongjoon-hyun — APPROVED** [review]

**Comment by Udbhav30** [comment]
> @Udbhav30
> BTW, why do you remove the required template? Although you cannot describe how to do, please add back and mentioned like `Manually checking the log` at least.
> 
> > ### How was this patch tested?
@dongjoon-hyun 
Updated, thanks

**Comment by dongjoon-hyun** [comment]
Thanks!

**Comment by dongjoon-hyun** [comment]
Since this seems to be caused by SPARK-27651, cc @attilapiros and @vanzin .

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by dongjoon-hyun** [comment]
Merged to master.

**Pull request closed without merging**
