### PR TITLE
[SPARK-25485][SQL][TEST] Refactor UnsafeProjectionBenchmark to use main method

### PR DESCRIPTION
**Pull request by yucai**
## What changes were proposed in this pull request?

Refactor `UnsafeProjectionBenchmark` to use main method.
Generate benchmark result:

```
SPARK_GENERATE_BENCHMARK_FILES=1 build/sbt "catalyst/test:runMain org.apache.spark.sql.UnsafeProjectionBenchmark"
```

## How was this patch tested?

manual test

### CODE REVIEW

**Comment by yucai** [comment]
retest this please

**Comment by yucai** [comment]
@dongjoon-hyun could you help review?

**Comment by dongjoon-hyun** [comment]
@yucai . Could you review and merge https://github.com/yucai/spark/pull/4 ?

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Pull request closed without merging**
