### PR TITLE
[SPARK-34152][SQL][FOLLOWUP] Do not uncache the temp view if it doesn't exist

### PR DESCRIPTION
**Pull request by cloud-fan**
### What changes were proposed in this pull request?

This PR fixes a mistake in https://github.com/apache/spark/pull/31273. When CREATE OR REPLACE a temp view, we need to uncache the to-be-replaced existing temp view. However, we shouldn't uncache if there is no existing temp view.

This doesn't cause real issues because the uncache action is failure-safe. But it produces a lot of warning messages.

### Why are the changes needed?

Avoid unnecessary warning logs.

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

manually run tests and check the warning messages.

### CODE REVIEW

**Comment by cloud-fan** [comment]
cc @imback82 @LuciferYang

**Review by imback82 — APPROVED** [review]
LGTM (pending tests), thanks @cloud-fan for fixing this!

**Review by viirya — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Merged to master.

**Comment by dongjoon-hyun** [comment]
Thank you, @cloud-fan and all.

**Pull request closed without merging**
