### PR TITLE
[SPARK-10092] [SQL] Multi-DB support follow up.

### PR DESCRIPTION
**Pull request by yhuai**
https://issues.apache.org/jira/browse/SPARK-10092

This pr is a follow-up one for Multi-DB support. It has the following changes:
- `HiveContext.refreshTable` now accepts `dbName.tableName`.
- `HiveContext.analyze` now accepts `dbName.tableName`.
- `CreateTableUsing`, `CreateTableUsingAsSelect`, `CreateTempTableUsing`, `CreateTempTableUsingAsSelect`, `CreateMetastoreDataSource`, and `CreateMetastoreDataSourceAsSelect` all take `TableIdentifier` instead of the string representation of table name.
- When you call `saveAsTable` with a specified database, the data will be saved to the correct location.
- Explicitly do not allow users to create a temporary with a specified database name (users cannot do it before).
- When we save table to metastore, we also check if db name and table name can be accepted by hive (using `MetaStoreUtils.validateName`).

### CODE REVIEW

**Comment by rxin** [comment]
cc @liancheng can you review this? This is now the only blocker for cutting 1.5-rc.

**Comment by liancheng** [comment]
This LGTM. Although the current interface still needs further refactoring to unify different table identifier representations, but we can do it in follow-up PRs.

**Comment by liancheng** [comment]
This PR conflicts with branch-1.5, I'm opening another PR to backport this.

**Comment by liancheng** [comment]
Already merged this to master, and opened #8336 for backporting to branch-1.5.

**Pull request closed without merging**
