### PR TITLE
[SPARK-27434][CORE] Fix mem leak due to hadoop fs caching mechanism when eventLog is enabled

### PR DESCRIPTION
**Pull request by linehrr**
## What changes were proposed in this pull request?

close the unused file system when closing the `EventLoggingListener` to prevent from mem leak.

## How was this patch tested?

No unit tests were implemented for this patch.

### CODE REVIEW

**Comment by liupc** [comment]
IIUC, the `stop` method will only be called when the app is finished, so how could it cause memory leak?

Can you give more information about the concrete case you encountered?

**Comment by HyukjinKwon** [comment]
Also, please fix the PR title to be more specific.

**Comment by JoshRosen** [comment]
Does this component have exclusive ownership of this Hadoop `FileSystem` instance? Could we run into problems in case this ends up closing a shared instance?

**Comment by srowen** [comment]
I don't think you can close `FileSystem` objects. They're shared. Why is it a memory leak?

**Comment by linehrr** [comment]
@srowen please see https://issues.apache.org/jira/browse/SPARK-27434 for detail. 
we have noticed the mem leak and did a heap dump on the spark driver, and looks like it's the accumulating filesystem objects that's causing the issue. 
and in the code, filesystem is never closed even tho they are not needed. all the filesystem objects got cached into the mem and close() method is to remove them from the cache so that GC can clean them, otherwise they are always referenced and will never get GCed.

**Comment by linehrr** [comment]
@srowen filesystem is shared that's true, but it's shared within a spark context, so if the context.close() is called, I think we can safely remove it. also, the static method FileSystem.get() is like a `getOrCreate`, so even if it's removed, other part of the code can get it again, the object will be recreated and cached(if I missed sth, please point me to the code where it could potentially get NPE after close, I can fix that).

**Comment by srowen** [comment]
Hm your heap dump is convincing, although this `FileSystem` is just obtained from Hadoop and its cache. Generally that's not safe to close, but maybe here. I'm trying to figure out if closing it solves the problem though. You'd still have something holding a reference to this object, no? And that I don't quite see here, why that is.

**Comment by linehrr** [comment]
@srowen 
if there is indeed somewhere else that's holding that filesystem object, them this won't solve the problem you are right. but if not, removing from the cache will de-reference it from the cache, therefore could make that object orphan and then can be cleaned by GC. 
I can't really guarantee that there aren't other places that could reference that object, but the fact that when spark context is closing makes me think there should really not be.

**Comment by srowen** [comment]
Let's see what tests say so far. BTW you'll need to improve the title of the PR and JIRA.

**Comment by vanzin** [comment]
Before this goes too far.

You must not close FileSystem instances. The app itself can keep running after the SparkContext is stopped, if you want one reason.

This is not a fix for the memory leak. It's at best a workaround that will only work in very specific cases.

To fix the memory leak you need to understand where it's coming from. You just identified that it is happening, but not why or how. It may be it's not the fault of Spark at all and there's something wrong with the Hadoop code itself.

**Comment by linehrr** [comment]
looked more into the hadoop side, `FileSystem.get(URI uri, Configuration conf)` has caching built in side, unless specifically disabled. 
`return conf.getBoolean(disableCacheName, false) ? createFileSystem(uri, conf) : CACHE.get(uri, conf);`

due to this, fileSystem object will be cached and put into a map using generated Key: 

           Key(URI uri, Configuration conf) throws IOException {
                this(uri, conf, 0L);
            }

            Key(URI uri, Configuration conf, long unique) throws IOException {
                this.scheme = uri.getScheme() == null ? "" : StringUtils.toLowerCase(uri.getScheme());
                this.authority = uri.getAuthority() == null ? "" : StringUtils.toLowerCase(uri.getAuthority());
                this.unique = unique;
                this.ugi = UserGroupInformation.getCurrentUser();
            }

therefore in theory if the baseLogDir is the same, and hadoop conf don't change, object will be reused between spark context, however for some unknown reason it did not and got created every time. 

on the other hand, the `close()` method is safer than you thought. first, it's only going close one of those many cached fileSystems that are cached, not all, so it's likely you are only closing the one you created. also, closing fileSystem does not actually CLOSE that file system, according to the close method: 
    public void close() throws IOException {
        this.processDeleteOnExit();
        CACHE.remove(this.key, this);
    }

it deletes the pending deletions and remove that object from the cache, that's it. 
so if by any chance other threads are possessing this object, it will be fine and that thread can continue using it. 
most important gain from closing this file system object is to get it de-referenced from cache, so GC can eventually reclaim it from the heap when no one else has reference to it no more.

**Comment by linehrr** [comment]
and also, we've tested this with and without eventLog enabled. and the result is clear that with the eventLog enabled, we will run into this leak everytime after we open and close spark context several times in the same JVM and heap dumps are all similar. but without eventLog enabled, we never run into this again.

**Comment by vanzin** [comment]
I understand how the fs cache works. You fix is still wrong.

I understand that you're seeing the memory leak when you enable the event log. But that doesn't explain the memory leak itself. The event log is just writing a file to HDFS, just like many other places in Spark.

**Comment by linehrr** [comment]
@vanzin enable eventLog itself along does not cause problem. like long running streaming jobs, they are fine. problem only shows up when spark context gets open and closed repeatedly. which likely to create file system object every time instead of reusing the one that's cached previously. 

the point where I don't understand is how this is happening, I checked the `Key` in the cache map, it should be the same compared to the previous one, and the `equals` method got overridden properly as well, `hashcode` method override is ok as well. 

therefore I can't explain why cache is not reused for fs object, only thing I know is it's not reused.

**Comment by srowen** [comment]
Hm, I wonder if that's more at the root of the problem: you'd generally not close the SparkContext within one application, one JVM. I think this could be the issue? lots of stuff might not work well if you do.

**Comment by vanzin** [comment]
It's fine (and supported) to run multiple contexts in the same JVM, as long as they're not run concurrently.

**Comment by vanzin** [comment]
For example, https://issues.apache.org/jira/browse/HADOOP-12958 is an OOM in exactly the code path being talked about here. Maybe there are others.

**Comment by linehrr** [comment]
yea, we run multiple contexts in sequence and that works well. 
however looking at this patch: HADOOP-12958
```
-    private class StatisticsDataReference extends PhantomReference<Thread> {
+    private class StatisticsDataReference extends WeakReference<Thread> {
```

we do have that in place, since we are using `hadoop-2.7.3`. also to double make sure we checked runtime jar as well,  and we see that `hadoop-common` is using WeakReference now(from ugly binary Java class): 
``` Statistics^A^@^LInnerClasses^G^@7^A^@^NStatisticsData^A^@;Lorg/apache/hadoop/fs/FileSystem$Statistics$StatisticsData;^A^@^Fthis$0^A^@,Lorg/apache/hadoop/fs/FileSystem$Statistics;^A^@^F<init>^A^@|(Lorg/apache/hadoop/fs/FileSystem$Statistics;Lorg/ap    ache/hadoop/fs/FileSystem$Statistics$StatisticsData;Ljava/lang/Thread;)V^A^@^DCode^A^@^OLineNumberTable^A^@^RLocalVariableTable^A^@^Dthis^A^@^WStatisticsDataReference^A^@DLorg/apache/hadoop/fs/FileSystem$Statistics$StatisticsDataReference;^A^@^Fth    read^A^@^RLjava/lang/Thread;^A^@^GgetData^A^@=()Lorg/apache/hadoop/fs/FileSystem$Statistics$StatisticsData;^A^@^GcleanUp^A^@^C()V^A^@^MStackMapTable^G^@3^G^@8^G^@9^A^@ Signature^A^@1Ljava/lang/ref/WeakReference<Ljava/lang/Thread;>;^A^@```

**but what I see now is**, how would WeakReference fix this problem if you still have strong reference from HashSet refers to this  `StatisticsDataReference`? 

```
    public static final class Statistics {
        private final Set<FileSystem.Statistics.StatisticsDataReference> allData;
        ...
        public Statistics(FileSystem.Statistics other) {
            ...
            this.allData = new HashSet();
        }

        public FileSystem.Statistics.StatisticsData getThreadStatistics() {
            FileSystem.Statistics.StatisticsData data = (FileSystem.Statistics.StatisticsData)this.threadData.get();
            if (data == null) {
                data = new FileSystem.Statistics.StatisticsData();
                this.threadData.set(data);
                FileSystem.Statistics.StatisticsDataReference ref = new FileSystem.Statistics.StatisticsDataReference(data, Thread.currentThread());
                synchronized(this) {
                    this.allData.add(ref);
                }
            }

            return data;
 

}
```

only place this strong reference from HashSet could be removed is by calling `cleanUp` on `StatisticsDataReference`: 
```private class StatisticsDataReference extends WeakReference<Thread> {
            private final FileSystem.Statistics.StatisticsData data;

            public StatisticsDataReference(FileSystem.Statistics.StatisticsData data, Thread thread) {
                super(thread, FileSystem.Statistics.STATS_DATA_REF_QUEUE);
                this.data = data;
            }

            public FileSystem.Statistics.StatisticsData getData() {
                return this.data;
            }

            public void cleanUp() {
                synchronized(Statistics.this) {
                    Statistics.this.rootData.add(this.data);
                    Statistics.this.allData.remove(this);
                }
            }
        }
```

but checking the code, seems it's never called. so it will be held in that HashSet. 

in the meanwhile, new ref is been created every time this is called: 
```        
public FileSystem.Statistics.StatisticsData getThreadStatistics() {
            FileSystem.Statistics.StatisticsData data = (FileSystem.Statistics.StatisticsData)this.threadData.get();
            if (data == null) {
                data = new FileSystem.Statistics.StatisticsData();
                this.threadData.set(data);
                FileSystem.Statistics.StatisticsDataReference ref = new FileSystem.Statistics.StatisticsDataReference(data, Thread.currentThread());
                synchronized(this) {
                    this.allData.add(ref);
                }
            }

            return data;
        }
```
which is called in class `SparkHadoopUtil` by 
```
 private[spark] def getFSBytesWrittenOnThreadCallback(): () => Long = {
    val threadStats = FileSystem.getAllStatistics.asScala.map(_.getThreadStatistics)
    val f = () => threadStats.map(_.getBytesWritten).sum
    val baselineBytesWritten = f()
    () => f() - baselineBytesWritten
  }
 ```
and 
```
  private[spark] def getFSBytesReadOnThreadCallback(): () => Long = {
    val f = () => FileSystem.getAllStatistics.asScala.map(_.getThreadStatistics.getBytesRead).sum
    val baseline = (Thread.currentThread().getId, f())
```

can anyone verify if my finding makes sense?

**Comment by vanzin** [comment]
I think you're going at this from the wrong side. You just posted a screenshot on the bug, which shows there's a memory leak. But there's nothing in the screenshot that allows you to actually identify the nature of the leak.

Have you actually looked at the heap dump to see what is stored in the HashMap that's holding on to all that memory?

Maybe that will confirm your theory, or point somewhere else. But you're the only one that has that data, and I've never seen this leak, so only you can figure that out at the moment.

(BTW I assume you're the person who filed the bug.)

**Comment by linehrr** [comment]
@vanzin 
the dumps shows a HashSet under `FileSystem$Statistics` that's holding up lots of mem.
and from the class definition, there is only one HashSet under that class. 

also I think the HashMap there is just misleading, because in HashSet's implementation, it uses a HashMap for lookup: 
```
public class HashSet<E>
    extends AbstractSet<E>
    implements Set<E>, Cloneable, java.io.Serializable
{
    static final long serialVersionUID = -5024744406713321676L;

    private transient HashMap<E,Object> map;
  /**
     * Constructs a new, empty set; the backing <tt>HashMap</tt> instance has
     * default initial capacity (16) and load factor (0.75).
     */
    public HashSet() {
        map = new HashMap<>();
    }
```

so that HashMap is just under the HashSet holding internal data structure. 

I can look at the dump again, but I don't know if I can see more useful stuff. I will post back if I find anything new. but I agree, this is less likely to be a Spark issue at this moment.

**Pull request closed without merging**
