### PR TITLE
[SPARK-20395][BUILD] Update Scala to 2.11.11 and zinc to 0.3.15

### PR DESCRIPTION
**Pull request by srowen**
## What changes were proposed in this pull request?

Update Scala to 2.11.11 and zinc to 0.3.15

## How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by srowen** [comment]
@ScrapCodes it's good you're here because this might be something you can help with. (CC @dragos as well)

I'm updating to scala 2.11.11, and it looks like the `loadFiles` method that `SparkILoop` hooks into was removed in 2.11.9. I think it's about the same to hook into `process()` instead and do Spark init after it's done. Do you know of any reason that's a bad idea? I'm pushing the change anyway to see.

**Comment by ScrapCodes** [comment]
Hi Sean,
Taking a quick look at the changes that removed loadFiles. [changes](https://github.com/scala/scala/commit/99dad60d984d3f72338f3bad4c4fe905090edd51#diff-f31fa4d21a39bc6ed3c30fd38bcbc9d4)

It seems `startup` is the correct alternative, i.e. just before the call to printWelcome.
See [startup](https://github.com/scala/scala/blob/2.11.x/src/repl/scala/tools/nsc/interpreter/ILoop.scala#L959).

**Comment by srowen** [comment]
@ScrapCodes ah I should have pointed out the other constraint: we want this to still work with 2.11.8. Right now Spark would not run vs Scala 2.11.9+ at runtime, but if we tried to hook into `startup` it wouldn't work with 2.11.8 because that method didn't exist. That's why I was looking at `process`.

**Comment by ScrapCodes** [comment]
Actually, now I am wondering, how would it work without createInerpreter is executed. You constraint, makes things a bit tricky. I will think more before I reply.

**Comment by ScrapCodes** [comment]
If I am not able to come up with the better alternative, then following not so ideal option exist.

1) we can do a scala version check and have two different code paths based on scala version.
In scala 2.11.8+ we can hook out init just before printWelcome()
In scala 2.11.11 we can do it just before `loopPostInit()`.

**Comment by dragos** [comment]
If I'm not mistaken the current patch will fail on files passed via `-i` to spark-shell, since Spark is initialized after `process` is done (the SparkContext is not available during initialization, when `-i` files are loaded).

I'm not sure if there's a better way, especially one that works on all 2.11 series. Mea culpa for not adding a comment on `loadFiles` in the Scala REPL when I worked on the Spark Shell. Maybe @som-snytt has a suggestion for inserting `initializeSpark` in the initialization pipeline?

**Comment by som-snytt** [comment]
The contract was never well-defined.

`sbt` overrides `createInterpreter` and runs its `initialCommands` before returning. So that runs before REPL finishes init in `loopPostInit`: no `$intp`, power mode not entered, start code and `-i` not run yet.

I can't tell just by looking if that suits your needs here, but it's the most ancient hook enshrined by sbt.

https://github.com/sbt/sbt/blob/0.13/compile/interface/src/main/scala/xsbt/ConsoleInterface.scala#L27

@adriaanm is taking executive action to modularize/make API for REPL reuse. Possibly you're aware or he's only just started and is in stealth mode. That will address the issue in future.

**Comment by srowen** [comment]
Yeah, this was always a bit of a hack as this isn't an API. `createInterpreter` sounds like a promising place to hook into for now as it exists across these versions, and would mean Spark is initted a little earlier, before instead of after this middle block in here:

```
  def process(settings: Settings): Boolean = savingContextLoader {
    this.settings = settings
    createInterpreter()

    // sets in to some kind of reader depending on environmental cues
    in = in0.fold(chooseReader(settings))(r => SimpleReader(r, out, interactive = true))
    globalFuture = future {
      intp.initializeSynchronous()
      loopPostInit()
      !intp.reporter.hasErrors
    }
    loadFiles(settings)
    printWelcome()
...
```

**Comment by srowen** [comment]
Darn. I don't know if this is going to work. I'm closing this for now.

**Comment by som-snytt** [comment]
Thanks for the effort. I'll take a hack soon. If it's hopeless, I'll at least try to track developments with the new REPL API.

**Comment by tovbinm** [comment]
@som-snytt @srowen what about `2.11.12`?

**Comment by srowen** [comment]
Unless it changed the internals of the interpreter to afford a different place to hack in the init, don't think it is any different. However the build and most tests already work with 2.12.d

**Comment by tovbinm** [comment]
2.12 would be even better. I haven't seen a ticket related to 2.12 upgrade. I can give it a try.

**Pull request closed without merging**
