### PR TITLE
[SPARK-30545][ML][PYSPARK] Impl Extremely Randomized Trees

### PR DESCRIPTION
**Pull request by zhengruifeng**
### What changes were proposed in this pull request?
Impl ExtraTrees in ML,
the impl is quite similar to RandomForest, two main difference:
1, bootstrap sampling is disabled by default;
2, on each leaf, candidate splits (only one split per feature in Scikit-Learn's impl, refering to [`RandomSplitter`](https://github.com/scikit-learn/scikit-learn/blob/99d3d34d615a7d7b541b24d264b1108238c1953e/sklearn/tree/_splitter.pyx#L591) ) are drawn at random for each feature, and then the best of these randomly-chosen splits is selected. In this PR, I add an expert param `numRandomSplitsPerFeature` to control the number of random splits drawn in each feature.

### Why are the changes needed?
1, Extremely Randomized Trees or ExtraTrees is widely used and impled in Scikit-Learn and OpenCV;

2, ExtraTrees is quite similar to RandomForest, and the main difference lie in that,on each leaf, candidate splits (only one split in Scikit-Learn's impl) are drawn at random for each feature and the best of these randomly-chosen splits is selected.

### Does this PR introduce any user-facing change?
Yes

### How was this patch tested?
added testsuites

### CODE REVIEW

**Comment by zhengruifeng** [comment]
friendly ping @srowen @huaxingao @imatiach-msft

**Comment by huaxingao** [comment]
@zhengruifeng 
I took a quick look of how the random split is picked.
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.65.7485&rep=rep1&type=pdf

image


It seems to me that in the paper, the random threshold is found by sampling from the continuous uniform distribution [min(feature), max(feature)]. Seems to me that in your implementation, the random threshold is sampled uniformly (and discretely) from the set of possible splits generated by findSplits(). I know your way is simpler, but I am not sure if it is close enough to the original method in the paper.

**Comment by zhengruifeng** [comment]
@huaxingao Good point, you are right. Scikit-Learn does this exactly:
```
                    # Draw a random threshold
                    current.threshold = rand_uniform(min_feature_value,
                                                     max_feature_value,
                                                     random_state)
```

In Scikit-Learn, both RF and ET use a greedy method to find an exact threshold.
However, in MLLIB, all tree models are built on binned datasets (`treePoints`), to keep in line with other tree models and to minimize the change, I perfer to randomly draw a split from splits built at the beginning of training. Otherwise, I need to completely impl a new exact threshold finding method.

**Comment by srowen** [comment]
This is a lot of new code for a small variation on random forests. I'm not sure it's worth it?

**Comment by zhengruifeng** [comment]
@srowen  the main part of this PR is doc, example, and the regular methods for a new estimator.
The essential change is in the impl of `RandomForest`.
There are some other algs that share the internal impl, such as RandomForestClassifier and DecisionTreeClassifier.
Since extraTrees is widely used, so I tend to make it a new estimator.

**Comment by srowen** [comment]
I don't know, 2600 lines of code/doc for a small variation, not sure. I don't think ERT is that different, and where it benefits (less compute), well, do we need that? this part of random forests isn't the bottleneck in a distributed implementation. The cost of more trees may be higher in Spark.

**Comment by zhengruifeng** [comment]
@srowen Yes, the computation of finding best split is not remarkable, since the bottleneck should be the computation of histogram.

I just have a idea that do not need to compute the whole histogram in ERT,  just draw a random split, and accumulate its left and right impurity. In this way, the communication cost should be much less than RF.
However current impl of RF does not support this way. I will try to figure out whether it works and how to reuse impl of RF.

**Pull request closed without merging**
