### PR TITLE
[MINOR][DOC] Fix 2 style issues in running-on-kubernetes doc

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

fix style issue in the k8s document, please go to http://spark.apache.org/docs/3.0.0-preview2/running-on-kubernetes.html and search the keyword`spark.kubernetes.file.upload.path` to jump to the error context

### Why are the changes needed?

doc correctness

### Does this PR introduce any user-facing change?

Nah
### How was this patch tested?

Nah

### CODE REVIEW

**Comment by yaooqinn** [comment]
retest this please

**Review by attilapiros — APPROVED** [review]
I was about to open a PR with the same html escaping :)
 
LGTM

**Comment by yaooqinn** [comment]
retest this please

**Review by kiszk — APPROVED** [review]

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master and branch-3.0.

**Pull request closed without merging**
