### PR TITLE
[SPARK-50143][BUILD] Fix `protobuf` module Maven compilation

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to fix `protobuf` module `Maven` compilation failure due to the following `protocol-jar-maven-plugin` bug.
- https://github.com/os72/protoc-jar-maven-plugin/issues/104

Note that this happens only at `Maven` compilation.

### Why are the changes needed?

**BEFORE**
```
$ build/mvn -DskipTests clean install -pl connector/protobuf -e -am
...
[INFO] Spark Protobuf ..................................... FAILURE [  7.295 s]
...
[ERROR] Failed to execute goal com.github.os72:protoc-jar-maven-plugin:3.11.4:run (default) on project spark-protobuf_2.13: Execution default of goal com.github.os72:protoc-jar-maven-plugin:3.11.4:run failed:
Cannot read the array length because "<local6>" is null
```

**AFTER**
```
$ build/mvn -DskipTests clean install -pl connector/protobuf -e -am
...
[INFO] Reactor Summary for Spark Project Parent POM 4.0.0-SNAPSHOT:
[INFO]
[INFO] Spark Project Parent POM ........................... SUCCESS [  2.601 s]
[INFO] Spark Project Tags ................................. SUCCESS [  5.234 s]
[INFO] Spark Project Sketch ............................... SUCCESS [  5.278 s]
[INFO] Spark Project Common Utils ......................... SUCCESS [ 14.695 s]
[INFO] Spark Project Local DB ............................. SUCCESS [  6.258 s]
[INFO] Spark Project Networking ........................... SUCCESS [  9.384 s]
[INFO] Spark Project Shuffle Streaming Service ............ SUCCESS [  7.761 s]
[INFO] Spark Project Variant .............................. SUCCESS [  3.304 s]
[INFO] Spark Project Unsafe ............................... SUCCESS [  8.677 s]
[INFO] Spark Project Connect Shims ........................ SUCCESS [  2.690 s]
[INFO] Spark Project Launcher ............................. SUCCESS [  5.618 s]
[INFO] Spark Project Core ................................. SUCCESS [01:11 min]
[INFO] Spark Project SQL API .............................. SUCCESS [ 21.759 s]
[INFO] Spark Project Catalyst ............................. SUCCESS [01:30 min]
[INFO] Spark Project SQL .................................. SUCCESS [01:53 min]
[INFO] Spark Protobuf ..................................... SUCCESS [ 18.285 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  06:26 min
[INFO] Finished at: 2024-10-27T21:01:12-07:00
[INFO] ------------------------------------------------------------------------
```

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Manually run the following command like I did in the above.
```
$ build/mvn -DskipTests clean install -pl connector/protobuf -e -am
```

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
cc @LuciferYang

**Comment by dongjoon-hyun** [comment]
I verified that this works, @LuciferYang . Could you review this please?

**Comment by dongjoon-hyun** [comment]
Also, cc @viirya .

**Comment by dongjoon-hyun** [comment]
Could you review this PR, @zhengruifeng ?

**Review by zhengruifeng — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you so much, @zhengruifeng !

**Comment by dongjoon-hyun** [comment]
Merged to master to recover Maven CIs.

I'll monitor those CIs after merging this.

**Comment by LuciferYang** [comment]
late LGTM

**Comment by dongjoon-hyun** [comment]
Thank you for reporting and reviewing, @LuciferYang .

**Comment by panbingkun** [comment]
late LGTM

**Review by viirya — COMMENTED** [review]
Looks good to me.

**Comment by dongjoon-hyun** [comment]
Thank you, @panbingkun and @viirya .

**Comment by dongjoon-hyun** [comment]
For the record, Maven CI becomes healthy back after this PR.
- https://github.com/apache/spark/actions/workflows/build_maven.yml
  - https://github.com/apache/spark/actions/runs/11554580358

**Pull request closed without merging**
