### PR TITLE
[SPARK-12340][SQL]fix Int overflow in the SparkPlan.executeTake, RDD.take and AsyncRDDActions.takeAsync for branch-1.6

### PR DESCRIPTION
**Pull request by QiangCai**
I create this PR to merge this code into branch-1.6. And I have merged this code into master in PR https://github.com/apache/spark/pull/10562.

jira
https://issues.apache.org/jira/browse/SPARK-12340

### CODE REVIEW

**Comment by sarutak** [comment]
ok to test

**Comment by QiangCai** [comment]
spark-12340 has passed this test, but just other error has happend.

**Comment by sarutak** [comment]
@QiangCai Do you have time to follow @rxin 's comment in #10562 ?
Also if you'd like to merge this into `branch-1.6`, could you fix this similarly?

**Comment by QiangCai** [comment]
@sarutak I will do it.

**Comment by srowen** [comment]
@QiangCai you may want to close this one, and then make a new one that incorporates the original change and also https://github.com/apache/spark/pull/10670 once it's merged

**Pull request closed without merging**
