### PR TITLE
[SPARK-48913][BUILD][FOLLOWUP] Remove `txw2` from `LICENSE-binary` and delete `LICENSE-txw2.txt`

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to remove `txw2` from `LICENSE-binary` and `licenses-binary/LICENSE-txw2.txt` file.

### Why are the changes needed?

SPARK-44790 added this dependency.
- #43503

SPARK-48487 added the license file.
- #46821

SPARK-48913 removed this library dependency by implementing it inside Spark. Now, we can remove the license.
- #47593

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Manual review.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
cc @yaooqinn

**Review by LuciferYang — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @LuciferYang .

**Review by HyukjinKwon — APPROVED** [review]

**Review by yaooqinn — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @HyukjinKwon and @yaooqinn .

**Comment by dongjoon-hyun** [comment]
Since this is a removal of text which is irrelevant to CI results, let me merge this.

**Pull request closed without merging**
