### PR TITLE
[SPARK-5413] bump metrics dependency to v3.1.0

### PR DESCRIPTION
**Pull request by ryan-williams**
pick up batching of TCP requests to graphite, among other things

### CODE REVIEW

**Comment by srowen** [comment]
What I usually do is diff the output of `mvn dependency:tree` before and after to see if it does anything to downstream dependencies. Would 3.1.0 change anything?

**Comment by ryan-williams** [comment]
Thanks @srowen, [here's a diff](https://gist.github.com/ryan-williams/4e9283fed8dea2ba4815#file-) that seems to imply only changes to this dependency, but the [before](https://gist.github.com/ryan-williams/4e9283fed8dea2ba4815#file-before) and [after](https://gist.github.com/ryan-williams/4e9283fed8dea2ba4815#file-after) both failed with errors like:
```
Failed to execute goal on project spark-assembly_2.10: Could not resolve dependencies for project org.apache.spark:spark-assembly_2.10:pom:1.3.0-SNAPSHOT: Failure to find org.apache.spark:spark-repl_2.10:jar:1.3.0-SNAPSHOT in http://repository.apache.org/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of apache.snapshots has elapsed or updates are forced -> [Help 1]
```

I tried again with `mvn -U dependency:tree` and the error became:
```
Failed to execute goal on project spark-assembly_2.10: Could not resolve dependencies for project org.apache.spark:spark-assembly_2.10:pom:1.3.0-SNAPSHOT: Could not find artifact org.apache.spark:spark-repl_2.10:jar:1.3.0-SNAPSHOT in apache.snapshots (http://repository.apache.org/snapshots) -> [Help 1]
```

This, and my limited maven-fu made me think I need to run a `mvn install -DskipTests` to get `mvn dependency:tree` to work, but of course I just got a bunch of build errors on the `install` command like:
```
[error] /Users/ryan/c/spark/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/dsl/package.scala:314: polymorphic expression cannot be instantiated to expected type;
[error]  found   : [T(in method apply)]org.apache.spark.sql.catalyst.dsl.ScalaUdfBuilder[T(in method apply)]
[error]  required: org.apache.spark.sql.catalyst.dsl.package.ScalaUdfBuilder[T(in method functionToUdfBuilder)]
[error]   implicit def functionToUdfBuilder[T: TypeTag](func: Function1[_, T]): ScalaUdfBuilder[T] = ScalaUdfBuilder(func)
[error]                                                                                                             ^
```

...which tells me I probably need to `mvn clean` and try again.

**Comment by ryan-williams** [comment]
So, I'll do that, but lmk if the above output [through the REPL project, up to Assembly](https://gist.github.com/ryan-williams/4e9283fed8dea2ba4815#file-before-L1284-L1297), satisfies your question about this change's effect on the output of `mvn dependency:tree`

**Comment by srowen** [comment]
Yep, that's good evidence. You may know better whether there are any incompatibilities that matter, but I assume you wouldn't have proposed it if there were any breaking changes.

**Comment by ryan-williams** [comment]
Yea, I've run Spark with metrics-v3.1.0 and used the `MetricsSystem` and it seems to work fine.

**Comment by andrewor14** [comment]
I'm gonna bump the priority for this issue for 1.3 because of the implications it has for #3812. However, if for some reason this doesn't get merged I'll just revert that patch by the release.

**Comment by ryan-williams** [comment]
ah interesting. I had run into graphite struggling with the `<driver>` token previously, that would be great if this also fixes that for free

**Comment by rxin** [comment]
@andrewor14 are you going to merge this?

**Comment by rxin** [comment]
Actually I merged https://github.com/apache/spark/pull/4218 which contains this patch.

**Comment by andrewor14** [comment]
Ok cool. @ryan-williams would you mind closing this then now that it's subsumed by #4218?
@sarutak can you verify whether this solves the issue you raised in #3812?

**Comment by ryan-williams** [comment]
oh, cool, sure thanks

**Pull request closed without merging**
