### PR TITLE
[SPARK-21067][SQL] Initialize the HdfsEncryptionShim and the underlying FileSystem eagerly.

### PR DESCRIPTION
**Pull request by xy-xin**
## What changes were proposed in this pull request?

This pr fix the "Filesystem Closed" exception that caused by the closing of a hive session in thriftserver.

A `sessionState` holds a `hdfsEncryptionShim`, which holds a `fileSystem`. When a session was closed, the fileSystem may be closed. While the fileSystem is cached, so the subsequent using of the same fileSystem may throw "Filesystem closed" exception if previous session closes the fileSystem.

We can move the "holding of the `fileSystem`" from session to thriftserver by triggering `SessionState#getHdfsEncryptionShim` eagerly at the starting phase of the thriftserver, see below,

```
HiveThriftServer2#main()
    hiveClientImpl
        val state = newState
            SessionState.start(state)
                SessionState.setCurrentSession(state)
        **state.getHdfsEncryptionShim**
```

In hive session, the new sessionState will reuse the `fileSystem` created by thriftserver,

```
CliService
    openSession
        HiveSessionImpl
            init
                sessionState = new SessionState
                SessionState.setCurrentSession(sessionState)
            executeStatementInternal
                SessionState.setCurrentSession(sessionState)
                operation.run()
                    hiveSession.getSessionManager().submitBackgroundOperation(operation)
                    **// If some code calls "state.getHdfsEncryptionShim", the cached `fileSystem` is reused.**
```

## How was this patch tested?

manual test

Please review https://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Comment by xianyinxin** [comment]
This pr is for branch-2.4. The master branch may need further investigation since there's a significant refactoring of hive and hadoop dependent code.

**Comment by dongjoon-hyun** [comment]
Hi, @xianyinxin . Thank you for making a PR, but please make a PR to the `master` branch first.
We are reviewing `master` branch first always. I'll close this PR for now. You can reuse this PR by reopening after `master` branch is fixed first.

**Comment by xianyinxin** [comment]
@dongjoon-hyun fine, will do that.

**Comment by dongjoon-hyun** [comment]
Thank you for your understanding, @xianyinxin !

**Pull request closed without merging**
