### PR TITLE
Revert "[SPARK-34209][SQL] Delegate table name validation to the session catalog"

### PR DESCRIPTION
**Pull request by HyukjinKwon**
### What changes were proposed in this pull request?

This reverts commit cf7a13c363ef5d56556c9d70e7811bf6a40de55f.

### Why are the changes needed?

To fix the regression in the error message, also see https://github.com/apache/spark/pull/31541#issuecomment-777155208

### Does this PR introduce _any_ user-facing change?

No, this is a revert.

### How was this patch tested?

Reverted test cases should verify this revert.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
@holdenk, @cloud-fan, @imback82, @dongjoon-hyun, @maropu, I opened a PR to discuss the revert of https://github.com/apache/spark/pull/31427. Could you guys take a look please?

**Review by maropu — APPROVED** [review]
Reverting and re-discussing it looks okay.

**Comment by holdenk** [comment]
I'd rather discuss then revert if we agree that a revert is the best path forward.

**Comment by holdenk** [comment]
So the point is that if folks use a different session catalog (e.g. iceberg), the restriction that exists in Spark limits what the alternate catalog can do, hence the desire to remove the check in the Spark code and delegate the checking to the catalog. cc @rdblue @RussellSpitzer @aokolnychyi

**Comment by RussellSpitzer** [comment]
Our major issue is that it makes this rather special case behavior for spark_catalog named catalogs. For example say I create a catalog called ice

```bash
 ./bin/spark-shell --conf spark.sql.catalog.ice=org.apache.iceberg.spark.SparkCatalog --conf spark.sql.catalog.ice.type=hive --conf spark.sql.catalog.ice.uri=thrift://localhost:9083
```
Then there is no problem with me setting this to the default catalog and accessing a multipart identifier
```sql
USE ice; SELECT * FROM default.table.files
```

But let's say I use the exact same class but name it spark_catalog so that it is the default session catalog.

```bash
./bin/spark-shell --conf spark.sql.catalog.spark_catalog=org.apache.iceberg.spark.SparkCatalog --conf spark.sql.catalog.spark_catalog.type=hive --conf spark.sql.catalog.spark_catalog.uri=thrift://localhost:9083
```

Then the same request fails
```SQL
SELECT * FROM default.table.files 
org.apache.spark.sql.AnalysisException: The namespace in session catalog must have exactly one name part: default.part.files;
  at org.apache.spark.sql.connector.catalog.LookupCatalog$SessionCatalogAndIdentifier$.unapply(LookupCatalog.scala:65)
```

**Comment by HyukjinKwon** [comment]
@holdenk, as I said earlier, I opened this PR to discuss the revert. In fact your PR was not reviewed by the original author or reviewer, neither was approved by any commiter. The reason of the change was not explained either in the PR description. Other people also raised a concern.

spark_sesison is reserved catalog name for the default Spark session catalog. I don't think it makes much sense to allow it as an external catalog. Can we instead document that this is disallowed as an external catalog name? It does look odd to override the default catalog name. Does it even work properly?

**Comment by holdenk** [comment]
From @RussellSpitzer's example it seems like we have a config flag to override the session catalog, so I think that's totally supported.

**Comment by rdblue** [comment]
I don't think that this revert should be committed. In general, we should fix problems like error messages by fixing the problem directly if it isn't caught at review time.

I also don't think that one person that doesn't understand the motivation for a change is a valid reason to revert. However, I do agree that we need to ensure that reviews happen, or that we have a _very_ well understood policy on lazy consensus.

**Comment by HyukjinKwon** [comment]
@rdblue, please read my comments above and the previous PR. Your point that I simple misunderstood is incorrect. My reason to revert this change is that we don't allow that in the default Spark session as I explained above and the previous PR.

Also do you mean we're allowing to overwrite the default Spark session by design, @rdblue? If that's the case we should revisit all changes made for the Spark default session, and multi parts validation.

This is also not about policy but more about the best practice. Do you mean it is healthy to commit changes without getting reviewed from original author, reviewer or other committers?

**Comment by RussellSpitzer** [comment]
I mean I feel like we have been allowing folks to override spark_catalog for a while, and it has been documented in several places like here

https://github.com/apache/spark/blob/9b875ceada60732899053fbd90728b4944d1c03d/sql/catalyst/src/main/scala/org/apache/spark/sql/internal/SQLConf.scala#L2702-L2712

Which makes it sound to me like we are allowed to replace this, and the only requirement is that you would return the same tables that the original session catalog would.

I also know a few other implementers who have been using this parameter to set the Session catalog

Like
https://docs.delta.io/latest/quick-start.html
```
pyspark --packages io.delta:delta-core_2.12:0.8.0 --conf "spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension" --conf "spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog"
```

Maybe we just should lock off this parameter and only allow for setting "default catalog" which is now available?

**Comment by HyukjinKwon** [comment]
I asked it @rdblue because he proposed and introduced this. It would be great if I can hear his answer.

**Comment by rdblue** [comment]
Yes, replacing `spark_catalog` is part of the design.

> Do you mean it is healthy to commit changes without getting reviewed from original author, reviewer or other committers?

Is this question for me? I clearly don't think that.

**Comment by HyukjinKwon** [comment]
Yes, then is it healthy to keep the changes committed without getting reviewed from original author and reviewer, or approved by a committer?

Then we should fix the regression in the error message instead of removing the check out. Now the error message is incorrect if we use the default session.

**Comment by rdblue** [comment]
> Why are the changes needed?
> To fix the regression in the error message, and it is not obvious what was the gain of the fix.

I don't think that these stated reasons justify reverting the commit. Instead, fix the error message directly and listen to people that can provide the needed context.

If you want to object to using lazy consensus, then do that directly.

**Comment by HyukjinKwon** [comment]
@rdblue, sure, I can change the PR description if that looks an issue to you. This is not merged yet so I can change. Can you please answer my question first though?

First, the previous PR was not an incremental improvement. It caused a regression in the most common scenario with the default Spark session.

Second, it should have the test cases to prove that it works.

Third, the PR description should clarify what the change targets to fix, and why. It does not look obvious to me, presumably to other people given their comments.

Forth, people already raised concerns of the merge process and  pointed out several issues in the PR.

Last, the PR was merged without people's opinion, which harms the community.

If you want to keep the community healthy, we should revert the output from that action immediately. New PR should better be created, and should be discussed from scratch. You're assuming that the output from that action does not harm the community health.

This remains as a bad example, and we will have to repeat the same thing if it happens again next time.

**Comment by HyukjinKwon** [comment]
@rdblue and @holdenk If you are against this revert, please file a JIRA and address other people' feedback / opinions with a high priority. Please be diligent on addressing them instead of passively going against the revert. I am okay with this way. This is better than a deadlock.

**Comment by srowen** [comment]
FWIW I wouldn't argue too much about process here. We all know the deal, we all use good judgment and don't have to send around reminders about the importance of reviews. I also find I can't for love or money get someone else to look at a PR and judge it's OK to go ahead. The original PR was open a long time and had at least a late LGTM. One unfortunate truth is that things sometimes get reviewed _after_ they're committed and get built, used by downstream consumers. 

Now we do have some legit concerns about the change it seems, here and in the original PR. I'd say give a fair shot at fixing forward / addressing concerns? If there are still valid outstanding concerns, then it seems reasonable to revert and take it back to the drawing boards. But then I'd say, please engage about resolving the original issue actively, if there is any possible way to satisfy everyone's concerns.

**Comment by holdenk** [comment]
Thanks everyone.

If I had known there were going to be concerns I would have been more active at trying to get someone to review. I'm sorry I didn't judge this one correctly. We all make judgement mistakes but the great thing about version control is we can (for the most part) fix it :) 

I'm going to take a step back from this PR for the rest of the day and have some tea and work on other projects so I can come back with the right frame of mind.

If folks are willing to I have a preference to working to resolve the issue with the error message clarity, and I'll file a JIRA for that tomorrow. If folks feel the need to do a revert and I can do a re-submit tomorrow I am happy to work with that process as well.

I know it's hard working like this where we can't even meet up like usual at conferences and chat, so thanks everyone for understanding. Socially distanced internet hugs to everyone. And when things are better in the world I look forward to us all being able meet up and find out about all of the good and the bad everyone's been through this past year.

**Comment by holdenk** [comment]
I've gone ahead and filed https://issues.apache.org/jira/browse/SPARK-34425

**Comment by HyukjinKwon** [comment]
Thanks @holdenk for chiming in. I fully agree with @srowen's. I do understand this can happen. I have made many mistakes too. The PR was reviewed and approved eventually after the commit, and the leftover comments were (being) addressed properly as above. Handling the case does look appropriate to me - the concerns were raised legitimately, and they are properly being handled.

I am happy that I can confirm we all agree with this, and this clears that my doubt from few discussions here and there.

**Comment by HyukjinKwon** [comment]
I will close this revert since they are being handled separately now. Thanks all for the discussions/

**Comment by HeartSaVioR** [comment]
I feel the all inputs about rationalization in here are all valuable (thanks!) and it'd be nice if we can update the JIRA to let JIRA issue be self-explanation on rationalization. Given we decide not to go with revert, we have lost the chance to fill out the commit message.

One thing I don't still get is the R&R of session catalog (from what I can read from conf doc is that "the catalog provides the opportunity to extend V1 to leverage V2 interface", but I guess it's not only used for such purpose), and what are exactly the right expectations between session catalog vs custom catalog... but I'll ask it in dev@ mailing list instead.

**Comment by cloud-fan** [comment]
Technically people can replace the session catalog with a custom v2 implementation by setting `spark.sql.catalog.spark_catalog`, but this is not the expected usage:
```
  val V2_SESSION_CATALOG_IMPLEMENTATION =
    buildConf(s"spark.sql.catalog.$SESSION_CATALOG_NAME")
      .doc("A catalog implementation that will be used as the v2 interface to Spark's built-in " +
        s"v1 catalog: $SESSION_CATALOG_NAME. This catalog shares its identifier namespace with " +
        s"the $SESSION_CATALOG_NAME and must be consistent with it; for example, if a table can " +
        s"be loaded by the $SESSION_CATALOG_NAME, this catalog must also return the table " +
        s"metadata. To delegate operations to the $SESSION_CATALOG_NAME, implementations can " +
        "extend 'CatalogExtension'.")
      .version("3.0.0")
      .stringConf
      .createOptional
```

Users are only expected to extend the session catalog, not replacing it.

**Comment by cloud-fan** [comment]
@RussellSpitzer I looked at your use case in https://github.com/apache/spark/pull/31541#issuecomment-776882137 , and I think it's a misuse of the session catalog, as you are not extending it but replacing it.

I think the right way is to register your ice catalog and set it as the default via `spark.sql.defaultCatalog=ice`.

**Comment by HyukjinKwon** [comment]
@rdblue, can you confirm? it would be great if you point out which part of your design doc explains this.

**Comment by RussellSpitzer** [comment]
@cloud-fan Yes I used the non extension class in that example. I should have used this class ```org.apache.iceberg.spark.SparkSessionCatalog``` which does extend it. 

https://github.com/apache/iceberg/blob/master/spark3/src/main/java/org/apache/iceberg/spark/SparkSessionCatalog.java

I was just being lazy in my example, but I honestly don't see the difference here.

**Comment by rdblue** [comment]
@cloud-fan, Russell is right. We allow extending `spark_catalog` to layer on more functionality, while still being able to load and use v1 tables. Any validation that is specific to `spark_catalog` should be done there, not in the planner. That's just basic good design and separation of concerns.

In addition, getting this wrong is needlessly limiting. Russell's case is a great example of that, where you can't really augment `spark_catalog` in certain ways, like supporting namespaces that have additional nesting.

**Comment by HeartSaVioR** [comment]
So I'm confused again - the R&R of "session catalog" doesn't seem to be agreed upon.

Still something I don't understand is, why it has to be session catalog? Can your case be solved on custom catalog instead?

I got a feeling there're reasons you have to extend spark_catalog instead of picking another catalog, which sounds like "lacks" of custom catalog and we may be able to just address the lacks in custom catalog, instead of trying to modify "reserved" one.

(Probably if the name of session catalog was "v1_catalog" to give best clarity then no one would try to use it for v2.)

**Comment by cloud-fan** [comment]
The original motivation of extending the session catalog is to support v2 providers, e.g. Delta extends the session catalog to support `CREATE TABLE ... USING delta`.

The doc says `This catalog shares its identifier namespace with the $SESSION_CATALOG_NAME and must be consistent with it`, so @rdblue is right that it's OK for the extended v2 session catalog to support namespaces that have additional nesting, as long as it's still able to load and use v1 tables in the Hive metastore.

I don't have a problem with it, but I'd like to point out that this use case has not been called out explicitly before (or I missed something). I think that why some people are confused.

**Comment by rdblue** [comment]
> why it has to be session catalog? Can your case be solved on custom catalog instead?

The purpose is to be able to continue using the built-in catalog for v1 tables, but also use it for v2 tables. The built-in catalog is the only one that can load v1 tables. Others must go through the v2 API for everything. So if you have tables in your catalog that still use v1, you have to use it for backward compatibility. But, projects like Delta and Iceberg store tables in the same metastore along-side v1 tables and need to use the v2 API. That's why we allow extending this catalog and delegating to the built-in one.

This use case wasn't called out explicitly because we didn't really think about a `spark_catalog` extension supporting other namespaces. But there's nothing wrong with doing that in principle and I think it is a better separation of concerns to enforce catalog restrictions in that catalog rather than in rules.

**Comment by HeartSaVioR** [comment]
OK the reason of using session catalog looks to be clear (support v1/v2 tables altogether in the same metastore), and I agree that's probably not something we could do with custom catalog.
(Some tricks would work, like implementing both session catalog and custom catalog which session catalog ignores v2 tables it can't read, and vice versa, but I'd agree that's quite redundant.)

Probably the possible concern is that once the table name resolution is delegated to the catalog, it gives diverged UX among different implementations of session catalog. I'd guess each session catalog would describe how the resolution works kindly and how it is different from the built-in session catalog, so that Spark issue doesn't go to Delta/Iceberg and vice versa. Otherwise I agree that's not something wrong.

We may still want to have the check in somewhere else just for the built-in session catalog, as there's a comment in #31553.

**Pull request closed without merging**
