### PR TITLE
[SPARK-34125][CORE][2.4] Make EventLoggingListener.codecMap thread-safe

### PR DESCRIPTION
**Pull request by cxzl25**
### What changes were proposed in this pull request?
`EventLoggingListener.codecMap` change `mutable.HashMap` to `ConcurrentHashMap`

### Why are the changes needed?
2.x version of history server
`EventLoggingListener.codecMap` is of type mutable.HashMap, which is not thread safe.
This will cause the history server to suddenly get stuck and not work.
The 3.x version was changed to `EventLogFileReader.codecMap` to `ConcurrentHashMap` type, so there is no such problem.(SPARK-28869)

Multiple threads call `openEventLog`, `codecMap` is updated by multiple threads, `mutable.HashMap` may fall into an infinite loop during `resize`, resulting in history server not working.
https://github.com/scala/bug/issues/10436

PID 117049 0x1c939
image

image

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
exist ut

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
ok to test

**Comment by HeartSaVioR** [comment]
Could we please elaborate more on the impact of the issue in `Why are the changes needed?` via linking Scala issue as we did in JIRA issue?

**Comment by srowen** [comment]
Does this not affect master / 3.x?

**Comment by HeartSaVioR** [comment]
Yes, we changed it already in Spark 3.0, but as a part of commit and we haven't realized it should be fixed in 2.4.x as well.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @cxzl25 and all.

**Comment by HeartSaVioR** [comment]
retest this, please

**Comment by HeartSaVioR** [comment]
Just triggered Jenkins/GA. Once one of them passes I'll merge this.

**Comment by dongjoon-hyun** [comment]
FYI, the first commit already passed with Jenkins here. And, the second commit is an empty commit to retriever Jenkins.
- https://github.com/apache/spark/pull/31194#issuecomment-760982121

**Comment by HeartSaVioR** [comment]
Test passed. Merging.

**Comment by HeartSaVioR** [comment]
Thanks @cxzl25 for the contribution! Merged to branch-2.4.

**Comment by dongjoon-hyun** [comment]
Thank you all!

**Pull request closed without merging**
