### PR TITLE
[SPARK-17346][SQL][Tests]Fix the flaky topic deletion in KafkaSourceStressSuite

### PR DESCRIPTION
**Pull request by zsxwing**
## What changes were proposed in this pull request?

A follow up Pr for SPARK-17346 to fix flaky `org.apache.spark.sql.kafka010.KafkaSourceStressSuite`.

Test log: https://amplab.cs.berkeley.edu/jenkins/job/spark-master-test-sbt-hadoop-2.4/1855/testReport/junit/org.apache.spark.sql.kafka010/KafkaSourceStressSuite/_It_is_not_a_test_/

Looks like deleting the Kafka internal topic `__consumer_offsets` is flaky. This PR just simply ignores internal topics.
## How was this patch tested?

Existing tests.

### CODE REVIEW

**Review by srowen — APPROVED** [review]
Yes we shouldn't be deleting that topic

**Comment by tdas** [comment]
Are you sure we are ignoring all internal topics with that filter?
Because, it maybe better to not make assumption, and rather prefix all topics we create with something, and deleted only those.

**Comment by zsxwing** [comment]
> Are you sure we are ignoring all internal topics with that filter?
> Because, it maybe better to not make assumption, and rather prefix all topics we create with something, and deleted only those.

Good point. Just use `stress` to filter instead.

**Comment by tdas** [comment]
LGTM. Merging it to master and 2.0

**Comment by tdas** [comment]
Correction. Merging to master only. Can you fix the 2.0 PR with this issue since that is still open?

**Comment by zsxwing** [comment]
Since deleting a normal topic may be timeout as well: https://amplab.cs.berkeley.edu/jenkins/job/spark-master-test-sbt-hadoop-2.6/1763/testReport/junit/org.apache.spark.sql.kafka010/KafkaSourceStressSuite/_It_is_not_a_test_/

I just removed the topic deletion codes. It's not necessary since we are going to shut down the kafka cluster.

**Comment by zsxwing** [comment]
@tdas since this one has not yet been merged, I just updated the PR to remove the topic cleanup.

**Comment by tdas** [comment]
Merging it to master, and branch 2.0

**Pull request closed without merging**
