### PR TITLE
[SPARK-49816][SQL] Should only update out-going-ref-count for referenced outer CTE relation

### PR DESCRIPTION
**Pull request by cloud-fan**
### What changes were proposed in this pull request?

This PR fixes a long-standing reference counting bug in the rule `InlineCTE`. Let's look at the minimal repro:
```
      sql(
        """
          |WITH
          |t1 AS (SELECT 1 col),
          |t2 AS (SELECT * FROM t1)
          |SELECT * FROM t2
          |""".stripMargin).createTempView("v")
      // r1 is un-referenced, but it should not decrease the ref count of t2 inside view v.
      val df = sql(
        """
          |WITH
          |r1 AS (SELECT * FROM v),
          |r2 AS (SELECT * FROM v)
          |SELECT * FROM r2
          |""".stripMargin)
```
The logical plan is something like below
```
WithCTE
  CTEDef r1
    View v
      WithCTE
        CTEDef t1
          OneRowRelation
        CTEDef t2
          CTERef t1
        CTERef t2    // main query of the inner WithCTE
  CTEDef r2
    View v   // exactly the same as the view v above
      WithCTE
        CTEDef t1
          OneRowRelation
        CTEDef t2
          CTERef t1
        CTERef t2
  CTERef r2    // main query of the outer WithCTE
```
Ideally, the ref count of `t1`, `t2` and `r2` should be all `1`. They will be inlined and the final plan is the `OneRowRelation`. However, in `InlineCTE#buildCTEMap`, when we traverse into `CTEDef r1` and hit `CTERef t2`, we mistakenly update the out-going-ref-count of `r1`, which means that `r1` references `t2` and this is totally wrong. Later on, in `InlineCTE#cleanCTEMap`, we find that `r1` is not referenced at all, so we decrease the ref count of its out-going-ref, which is `t2`, and the ref count of `t2` becomes `0`. Finally, in `InlineCTE#inlineCTE`, we leave the plan of `t2` unchanged because its ref count is `0`, and the plan of `t2` contains `CTERef t1`. `t2` is still inlined so we end up with `CTERef t1` as the final plan without the `WithCTE` node.

### Why are the changes needed?

bug fix

### Does this PR introduce _any_ user-facing change?

Yes, the query failed before and now can work

### How was this patch tested?

new test

### Was this patch authored or co-authored using generative AI tooling?

no

### CODE REVIEW

**Comment by cloud-fan** [comment]
cc @viirya

**Comment by viirya** [comment]
Looks like it causes CTE test failures:


```
[error] Failed tests:
[error] 	org.apache.spark.sql.CTEInlineSuiteAEOn
[error] 	org.apache.spark.sql.CTEInlineSuiteAEOff
```

**Comment by peter-toth** [comment]
> when we traverse into CTEDef r1 and hit CTERef t2, we mistakenly update the out-going-ref-count of r1, which means that r1 references t2 and this is totally wrong

In that example query `r1` actually refernces `t2` so IMO we do the right thing.
Most probably the root cause of this issue is that CTE `t1` and `t2` are in view `v` and `v` is used 2 times in the main query. The first and second occurance of `t1` and `t2` have conflicting CTE Ids (we don't generate unique CTE Ids when a view plan gets inserted into the referencing query multiple times, do we?) so both `t1` and `t2` get initialized in the global `cteMap` map 2 times with `refCount = 0`: https://github.com/apache/spark/blob/039fd13eacb1cef835045e3a60cebf958589e1a2/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/optimizer/InlineCTE.scala#L82-L88 and the second initialization accidentally resets the `refCount`.

**Comment by cloud-fan** [comment]
@peter-toth The reset of `CTEReferenceInfo` is not a big issue. Only the entire `WithCTE` can be duplicated, not an arbitrary part of it. It's a waste of work to reset `CTEReferenceInfo` and re-calculate it, but it won't change anything.

> In that example query r1 actually refernces t2 so IMO we do the right thing.

It is not. Let's assume `t2` is non-deterministic. The `WithCTE` node is self-contained and the final plan of the view `v` should be just the `OneRowRelation`. However, if we say `r1` references `t2`, then we can't inline.

**Comment by peter-toth** [comment]
I think I get it now, thanks @cloud-fan.

**Comment by cloud-fan** [comment]
@peter-toth View is not the only issue here, people can do `val df = sql("WITH ...")` and use this `df` multiple times to build a new DataFrame

**Review by peter-toth — APPROVED** [review]
LGTM, thanks for the details.

**Comment by cloud-fan** [comment]
thanks for the review, merging to master!

**Comment by peter-toth** [comment]
I was thinking about this issue a bit today.
> Logically, a CTE relation can only reference other CTE relations that were defined before it in the same WithCTE node, or defined in the outer WithCTE, but not in the inner WithCTE.

Actually I'm still not sure this is true. If we take the example of:
```
WITH
  r1 AS (SELECT random()),
  r2 AS (
    WITH
      t1 AS (SELECT * FROM r1),
      t2 AS (SELECT * FROM t1)
    SELECT * FROM t2
  )
SELECT * FROM r1
```
The `refCount` of `r1` is 2, but the only way to get `r1` inlined is to track down the useless `r2` -> `t2` -> `t1` -> `r1` chain. So in this case `r2` needs to reference `t2` despite neither `t2` is defined before in the same WithCTE node and nor `t2` is defined in an outer WithCTE.

Interestingly this PR still works (`r1` gets inlined) for the usecase and it turned out it is becuase the nested CTEs are flattened during analysis and the actual analyzed plan of the above query looks like this:
```
== Analyzed Logical Plan ==
rand(): double
WithCTE
:- CTERelationDef 0, false
:  +- SubqueryAlias r1
:     +- Project [random(4108587657157349701) AS rand()#0]
:        +- OneRowRelation
:- CTERelationDef 1, false
:  +- SubqueryAlias t1
:     +- Project [rand()#0]
:        +- SubqueryAlias r1
:           +- CTERelationRef 0, true, [rand()#0], false
:- CTERelationDef 2, false
:  +- SubqueryAlias t2
:     +- Project [rand()#2]
:        +- SubqueryAlias t1
:           +- CTERelationRef 1, true, [rand()#2], false
:- CTERelationDef 3, false
:  +- SubqueryAlias r2
:     +- Project [rand()#3]
:        +- SubqueryAlias t2
:           +- CTERelationRef 2, true, [rand()#3], false
+- Project [rand()#1]
   +- SubqueryAlias r1
      +- CTERelationRef 0, true, [rand()#1], false
```

So I believe the logic of this PR only works because of CTE flattening. But if we can suppose CTE flattening always happens on self-contained parts of the final plan then we can just revert this PR and fix the issue by a simple reset of the `outerCTEId` when passing it to a child of a `WithCTE` node: https://github.com/peter-toth/spark/commit/809b38c325f11d97aa634def6391a212c9aa5c98

**Comment by peter-toth** [comment]
Anyways, this PR works and we can keep it as it is. But https://github.com/peter-toth/spark/commit/809b38c325f11d97aa634def6391a212c9aa5c98 looks like a much simpler solution for the problem.

**Comment by cloud-fan** [comment]
@peter-toth since the inner CTE can reference outer CTE relations, I think we need to propagate the `outerCTEId` parameter when calling `buildCTEMap` for the CTE main query.

**Comment by cloud-fan** [comment]
It looks like we need to take care of the case when the entire `WithCTE` can be eliminated.

**Comment by cloud-fan** [comment]
@peter-toth I double-checked this by manually building such a logical plan, and everything is fine. Let me explain what happens:
- when we call `buildCTEMap` for the CTE definition of `r2`, it walks through the entire `WithCTE` node including all CTE definitions and the main query, so the references to `r1` will be recorded in the out-going-ref-count of `r2`.
- since `r2` is not referenced, we decrease the ref count of `r1` and finally inline `r1`.

**Comment by cloud-fan** [comment]
@peter-toth the reference to `r1` is not recorded as the out-going-ref-count of `t1`, but the outer `r2`, according to the current code, which I think is reasonable.

**Comment by peter-toth** [comment]
But then in the case of the following query (and again, let's suppose we have nested WithCTE nodes in manually assembed logical plan and CTE flattening doesn't happen):
```
WITH
  r1 AS (SELECT random()),
  r2 AS (
    WITH
      t1 AS (SELECT * FROM r1),
      t2 AS (SELECT * FROM r1)
    SELECT * FROM t2
  )
SELECT * FROM r2
```
- the `refCount` of `r1` is 2
- and `r1` is recorded 2 times as the out-going-ref-count of `r2`
  (and `r1` is not recorded as the out-going-ref-count of `t1` or `t2`)

so `cleanCTEMap` will not clean anything and `r1` won't be inlined.

**Comment by peter-toth** [comment]
IMO, if we can't rely on the fact that currently connected nested WithCTE nodes get flattened and so the remaining WithCTE nodes are the edges of self-contained parts (because in that case we could clear `outerCTEId` when we encounter a WithCTE node) then one option could be to fix the conflicting CTE ids and keep using a global map in `cleanCTEMap()`.

https://github.com/peter-toth/spark/commit/7716dbfd7bca729f481a6bbf811fbcd30925de7c is a change whose parent reverts this PR and the commit fixes the conflicting CTE ids instead.

**Comment by cloud-fan** [comment]
Now I'm convinced. For the conflicting CTE IDs, shall we just accept it and accumulate the ref count?

For my example
```
WithCTE
  CTEDef r1
    View v
      WithCTE
        CTEDef t1
          OneRowRelation
        CTEDef t2
          CTERef t1
        CTERef t2    // main query of the inner WithCTE
  CTEDef r2
    View v   // exactly the same as the view v above
      WithCTE
        CTEDef t1
          OneRowRelation
        CTEDef t2
          CTERef t1
        CTERef t2
  CTERef r2    // main query of the outer WithCTE
```

The ref count for `t1` and `t2` should be both 2. When we remove `r1`, we decrease their ref count by 1, then we can still produce the right plan.

**Comment by peter-toth** [comment]
Yeah, but I don't think we can treat the conflicting CTEs as they are the same. This pseodo plan should produce 2 different random rows:
```
WithCTE
  CTEDef r1
    View v
      WithCTE
        CTEDef t1
          Random()
        CTEDef t2
          CTERef t1
        CTERef t2
  CTEDef r2
    View v
      WithCTE
        CTEDef t1
          Random()
        CTEDef t2
          CTERef t1
        CTERef t2
  CTERef r2
  CTERef r1 Union CTERef r2
```
That's why I'm leaning towards the idea of generating new ids if there is a conflict.

**Comment by peter-toth** [comment]
Or maybe we could clean/inline WithCTE nodes locally and propagate up the remaining outer references in a bottom-up manner.

**Comment by cloud-fan** [comment]
It seems the clearest solution is to do ref count for each `WithCTE` individually. I think generating new IDs is one way to do it, and another idea is to introduce ref counting context for each `WithCTE`.

**Comment by peter-toth** [comment]
Yeah, if you are Ok with generating new Ids then I can open a PR from https://github.com/peter-toth/spark/commit/7716dbfd7bca729f481a6bbf811fbcd30925de7c.

**Comment by cloud-fan** [comment]
Yes please, we can discuss more on your PR later.

**Comment by peter-toth** [comment]
Opened a PR here: https://github.com/apache/spark/pull/48429

**Pull request closed without merging**
