### PR TITLE
[MINOR][SQL] Avoid unnecessary invocation on checkAndGlobPathIfNecessary

### PR DESCRIPTION
**Pull request by Ngone51**
### What changes were proposed in this pull request?

Only invoke `checkAndGlobPathIfNecessary()` when we have to use `InMemoryFileIndex`.

### Why are the changes needed?

Avoid unnecessary function invocation.

### Does this PR introduce any user-facing change?

No.

### How was this patch tested?

Pass Jenkins.

### CODE REVIEW

**Comment by srowen** [comment]
Seems fine. Any other things like this you see?

**Comment by Ngone51** [comment]
No. I didn't search for such things deliberately, just happen to find it.

**Comment by srowen** [comment]
Merged to master

**Comment by Ngone51** [comment]
Thanks:) @srowen

**Pull request closed without merging**
