### PR TITLE
[SPARK-46528][BUILD] Upgrade `zstd-jni` to 1.5.5-11

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to update `zstd-jni` to 1.5.5-11.

### Why are the changes needed?

This version has a few bug fixes and the following improvement.
- https://github.com/luben/zstd-jni/pull/287

Full commit list.
- https://github.com/luben/zstd-jni/compare/v1.5.5-10...v1.5.5-11

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the CIs.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
The benchmark result will be added soon.
- Java 17: https://github.com/dongjoon-hyun/spark/actions/runs/7341467965
- Java 21: https://github.com/dongjoon-hyun/spark/actions/runs/7341470502

**Comment by dongjoon-hyun** [comment]
cc @LuciferYang

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by dongjoon-hyun** [comment]
Thank you, @HyukjinKwon !

**Comment by LuciferYang** [comment]
late LGTM

**Pull request closed without merging**
