### PR TITLE
[SPARK-11376] [SQL] Removes duplicated `mutableRow` field

### PR DESCRIPTION
**Pull request by liancheng**
This PR fixes a mistake in the code generated by `GenerateColumnAccessor`. Interestingly, although the code is illegal in Java (the class has two fields with the same name), Janino accepts it happily and accidentally works properly.

### CODE REVIEW

**Comment by liancheng** [comment]
cc @davies

**Comment by liancheng** [comment]
Experimented with the following snippet:

```scala
      ...
      evaluator.cook(
        s"""private String a = null;
           |
           |private Integer a = null;
           |
           |@Override
           |public int add(int lhs, int rhs) {
           |  System.out.println(a);
           |  return lhs + rhs;
           |}
         """.stripMargin
      )
      ...
```

Janino doesn't complain as long as the duplicated fields are either both null or not referenced.

**Comment by davies** [comment]
L158 Should also be removed.

**Comment by davies** [comment]
LGTM

**Comment by liancheng** [comment]
Thanks for the review, I'm merging this to master.

**Pull request closed without merging**
