### PR TITLE
[SPARK-20722][CORE] Replay newer event log that hasn't be replayed in advance for request

### PR DESCRIPTION
**Pull request by sharkdtu**
## What changes were proposed in this pull request?

History server may replay logs slowly if the size of event logs in current checking period is very large. It will get stuck for a while before entering next checking period, if we request a newer application history ui, we get the error like "Application application_1481785469354_934016 not found". We can let history server replay the newer event log in advance for request.

## How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by sharkdtu** [comment]
cc @srowen @ajbozarth

**Comment by jerryshao** [comment]
From my understanding, with your fix there will be a chance this event log file will be processed twice, this could be a big overhead if event log is very large. Also this PR looks more a temporary fix, rather than a thorough solution.

[SPARK-18085](https://issues.apache.org/jira/browse/SPARK-18085) is working on a thorough fix about the performance of SHS.

**Comment by sharkdtu** [comment]
@jerryshao Event log file will not be processed twice, you can review  `FsHistoryProvider.checkForLogs` and `FsHistoryProvider.mergeApplicationListing`. In next checking period, it will check event log length by comparing to the corresponding appinfo from `fileToAppInfo`.

**Comment by jerryshao** [comment]
I don't think so. Because `mergeApplicationListing` and `getAppUI` are running in two different threads, there could be a chance where this two methods are processing the same event file. This could be happened when `mergeApplicationListing` is processing a large event file, at this time `getAppUI` kicked in.

**Comment by sharkdtu** [comment]
@jerryshao thx, i agree that. this pr may be a temporary fix before SPARK-18085

**Comment by ajbozarth** [comment]
Honestly this feels a bit hack-y, is this a big issue for you? This should only happen if you start up SHS on a large directly then want to access the UI for an App that started after starting the SHS. It just feels like too much of an edge-case to add a potential duplication of log processing. If this case is an big issue though I would agree this is the best "patch" while waiting for SHSv2. I'll defer to @srowen and @vanzin on this.

**Comment by vanzin** [comment]
I haven't looked at the code, but since this won't make it into 2.2, and I'll be pushing hard to get SPARK-18085 into 2.3, this is throw-away code IMO. I'd rather spend resources into getting SPARK-18085 reviewed (hint hint hint) than on this.

**Comment by sharkdtu** [comment]
@ajbozarth Yes, this case is a big issue in my production cluster, where run nearly 20,000 applications every day.

**Pull request closed without merging**
