### PR TITLE
[SPARK-34032][SS]Add truststore and keystore type config possibility for Kafka delegation token

### PR DESCRIPTION
**Pull request by gaborgsomogyi**
### What changes were proposed in this pull request?
Kafka delegation token is obtained with `AdminClient` where security settings can be set. Keystore and trustrore type however can't be set. In this PR I've added these new configurations. This can be useful when the type is different. A good example is to make Spark FIPS compliant where the default JKS is not accepted.

### Why are the changes needed?
Missing configurations.

### Does this PR introduce _any_ user-facing change?
Yes, adding 2 additional config parameters.

### How was this patch tested?
Existing + modified unit tests + simple Kafka to Kafka app on cluster.

### CODE REVIEW

**Review by viirya — APPROVED** [review]

**Comment by viirya** [comment]
cc @HeartSaVioR

**Review by HeartSaVioR — APPROVED** [review]
+1

**Comment by HeartSaVioR** [comment]
I'll merge once test passes.

**Comment by HeartSaVioR** [comment]
retest this, please

**Comment by HeartSaVioR** [comment]
OK test passed. Merging to master.

**Comment by HeartSaVioR** [comment]
Thanks @gaborgsomogyi for the contribution! I merged this to master.

**Comment by gaborgsomogyi** [comment]
Thanks you guys taking care!

**Pull request closed without merging**
