### PR TITLE
[SPARK-12582][Test] IndexShuffleBlockResolverSuite fails in windows

### PR DESCRIPTION
**Pull request by yucai**
[SPARK-12582][Test] IndexShuffleBlockResolverSuite fails in windows
- IndexShuffleBlockResolverSuite fails in windows due to file is not closed.
- mv IndexShuffleBlockResolverSuite.scala from "test/java" to "test/scala".

https://issues.apache.org/jira/browse/SPARK-12582

### CODE REVIEW

**Comment by chenghao-intel** [comment]
LGTM @andrewor14

**Comment by andrewor14** [comment]
Looks good, but maybe we should close the stream in a `finally` block.
ok to test

**Comment by srowen** [comment]
@yucai can you update accordingly?

**Comment by yucai** [comment]
Sure, I will update the codes.

**Comment by JoshRosen** [comment]
Ping again; should be quick to update then we can merge.

**Comment by andrewor14** [comment]
Jenkins, this is ok to test?

**Comment by srowen** [comment]
@yucai should we take this over, in which case you can close this PR, or do you intend to update it?

**Comment by yucai** [comment]
Sorry, I miss the conversation! I will update it right now.

**Comment by yucai** [comment]
Jenkins, retest this please.

**Comment by JoshRosen** [comment]
Jenkins, retest this please.

**Comment by andrewor14** [comment]
retest this please

**Comment by JoshRosen** [comment]
Looks like a known-flaky streaming test.

**Comment by yucai** [comment]
One failure is about flaky streaming test. I retest InputStreamsSuite locally, no failure. 
```
[info] - socket input stream *** FAILED *** (3 seconds, 978 milliseconds)
[info]   4 did not equal 5 (InputStreamsSuite.scala:83)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:500)
[info]   at org.scalatest.FunSuite.newAssertionFailedException(FunSuite.scala:1555)
[info]   at org.scalatest.Assertions$AssertionsHelper.macroAssert(Assertions.scala:466)
```
Another failure looks like some test fail to launch? Like below:
```
[error] Error: Total 0, Failed 0, Errors 0, Passed 0
[error] Error during tests:
[error] 	Running java with options -classpath /home/jenkins/workspace/SparkPullRequestBuilder/core/target/scala-2.10/test-classes:/home/jenkins/workspace/SparkPullRequestBuilder/core/target/scala-2.10/classes:/home/jenkins/workspace/SparkPullRequestBuilder/launcher/target/scala-2.10/classes:/home/jenkins/workspace/SparkPullRequestBuilder/network/common/target/scala-2.10/classes:/home/jenkins/workspace/SparkPullRequestBuilder/network/shuffle/target/scala-
```
How about retest this?

**Comment by yucai** [comment]
@JoshRosen @andrewor14 could you kindly help retest?

**Comment by JoshRosen** [comment]
Jenkins, retest this please.

**Comment by srowen** [comment]
Merged to master/1.6

**Pull request closed without merging**
