### PR TITLE
[SPARK-7281] [yarn] Add option to set AM's lib path in client mode.

### PR DESCRIPTION
**Pull request by vanzin**

### CODE REVIEW

**Comment by sryza** [comment]
LGTM.  Did you try this out on a cluster?

**Comment by vanzin** [comment]
yes I did.

Submit:

    $ spark-submit --conf "spark.yarn.am.extraLibraryPath=/foo" --master yarn-client...

AM:

    # ps axwww | grep Executor
    17935 ?        Ss     0:00 /bin/bash -c LD_LIBRARY_PATH=/foo:...

**Comment by srowen** [comment]
LGTM

**Comment by tgravescs** [comment]
I'm not at all against this, just pointing out we had a discussion on this before: https://github.com/apache/spark/pull/3409

What is the exact use case here for this that has caused this change in thinking?

**Comment by vanzin** [comment]
Depending on your Hadoop config, if you don't have the Hadoop native libraries in the AM's lib path, you get this (sorry the first few lines of the stack trace are missing from our bug report):

    at org.apache.hadoop.security.Groups.getUserToGroupsMappingService(Groups.java:280)
    at org.apache.hadoop.security.UserGroupInformation.initialize(UserGroupInformation.java:269)
    at org.apache.hadoop.security.UserGroupInformation.setConfiguration(UserGroupInformation.java:297)
    at org.apache.spark.deploy.SparkHadoopUtil.<init>(SparkHadoopUtil.scala:43)
    ...

**Comment by vanzin** [comment]
If curious, the JNI-based group mapper is [`org.apache.hadoop.security.JniBasedUnixGroupsMapping`](http://grepcode.com/file/repo1.maven.org/maven2/org.apache.hadoop/hadoop-common/2.5.1/org/apache/hadoop/security/JniBasedUnixGroupsMapping.java).

**Comment by srowen** [comment]
@tgravescs are you OK with that? Seems like you agree with the change.

**Comment by tgravescs** [comment]
yes looks good.

**Pull request closed without merging**
