### PR TITLE
[SPARK-46037][SQL] Correctness fix for Shuffled Hash Join build left without codegen

### PR DESCRIPTION
**Pull request by cloud-fan**
### What changes were proposed in this pull request?

This is a re-submitting of https://github.com/apache/spark/pull/43938 to fix a join correctness bug caused by https://github.com/apache/spark/pull/41398 . Credits go to @mcdull-zhang 

### Why are the changes needed?

correctness fix

### Does this PR introduce _any_ user-facing change?

Yes, the query result will be corrected.

### How was this patch tested?

new test

### Was this patch authored or co-authored using generative AI tooling?

no

### CODE REVIEW

**Comment by cloud-fan** [comment]
cc @szehon-ho @dongjoon-hyun @viirya

**Review by yaooqinn — APPROVED** [review]

**Review by viirya — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @cloud-fan .

cc @huaxingao and @sunchao from #41398

**Review by huaxingao — APPROVED** [review]

**Review by sunchao — APPROVED** [review]
LGTM

**Comment by cloud-fan** [comment]
thanks for the review, merging to master/3.5!

**Comment by szehon-ho** [comment]
Sorry guys was out (computer was stolen) and slowly going through emails.  I must have missed adding the new case to this block when doing #41398 Thanks @cloud-fan  and @mcdull-zhang  for fixing this.

**Pull request closed without merging**
