### PR TITLE
[SPARK-13796] Redirect error message to logWarning

### PR DESCRIPTION
**Pull request by nishkamravi2**
## What changes were proposed in this pull request?

Redirect error message to logWarning
## How was this patch tested?

Unit tests, manual tests

@JoshRosen

### CODE REVIEW

**Comment by andrewor14** [comment]
Looks a lot like #11969. :) @JoshRosen

**Comment by andrewor14** [comment]
retest this please

**Comment by andrewor14** [comment]
retest this please

**Comment by andrewor14** [comment]
Merging into master thanks.

**Comment by nishkamravi2** [comment]
Thanks @andrewor14

**Pull request closed without merging**
