### PR TITLE
[SPARK-6092] [MLLIB] Add RankingMetrics in PySpark/MLlib

### PR DESCRIPTION
**Pull request by yanboliang**

### CODE REVIEW

**Comment by yanboliang** [comment]
Jenkins, retest this please

**Comment by mengxr** [comment]
test this please

**Comment by yanboliang** [comment]
It looks like py4j can not recognize [T: ClassTag] for RankingMetrics.
If I removed [T: ClassTag] and specify the type (for example: Int) of RankingMetrics, py4j can find the constructor. Maybe I need to wrapper the RankingMetrics in scala, looking forward your comments. @mengxr

**Comment by yanboliang** [comment]
Jenkins, retest this please

**Comment by mengxr** [comment]
The current solution looks good to me. We might have problems with Java compatibility with class tags (SPARK-7528). We can figure out a solution later.

**Pull request closed without merging**
