### PR TITLE
[SPARK-46709][SS] Expose partition_id column for state data source

### PR DESCRIPTION
**Pull request by chaoqin-li1123**
### What changes were proposed in this pull request?
Expose the partition_id column of state data source was hidden by default. 

### Why are the changes needed?
partition_id column is useful to users.

### Does this PR introduce _any_ user-facing change?
yes, Expose the partition_id column of state data source was hidden by default and modify the doc accordingly.

### How was this patch tested?
Modify existing integration test.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by chaoqin-li1123** [comment]
@HeartSaVioR

**Review by HeartSaVioR — APPROVED** [review]
+1

**Comment by HeartSaVioR** [comment]
@chaoqin-li1123 Could you please push an empty commit to retrigger GA build? I guess it is not related but let's give a try once more. Thanks in advance!

**Review by HyukjinKwon — APPROVED** [review]
Test failure should be unrelated.

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
