### PR TITLE
[SPARK-20655][core] In-memory KVStore implementation.

### PR DESCRIPTION
**Pull request by vanzin**
This change adds an in-memory implementation of KVStore that can be
used by the live UI.

The implementation is not fully optimized, neither for speed nor
space, but should be fast enough for using in the listener bus.

### CODE REVIEW

**Comment by rxin** [comment]
Is this going to be exposed?

Either way, we should find something like spark.util.kvstore package rather than a top level package.

**Comment by vanzin** [comment]
@rxin 

I wasn't planning on this being exposed at the moment; maybe in the future, since this is sort of a "natural" extension point to allow different storage backends for the UI / SHS. 

I'm also not sure how to make something not "publicly accessible"; I'm pretty sure I didn't add this to any doc target, unless it's automatically picked up (i.e. I did not touch the `Unidoc` object in the sbt build). Should I still go and add the `@Private` annotations to public classes? (That's not done by other private modules, such as the networking module, although that one predates `@Private`.)

I'm not super excited about changing package names at this point, but if you feel strongly about it it's not a big deal.

**Comment by vanzin** [comment]
(Also, because this PR is not adding this package, just adding classes to it, I'd rather do any package name change in a subsequent PR.)

**Comment by jsoltren** [comment]
This looks fine to me. Though, I did have to ask Marcelo a number of questions along the way to clarify what all was going on here. Maybe some of the points I mention below should make their way back to the code in the form of comments. I might suggest a couple of minor code changes from the discussion below.

The idea here is that, in the in memory store, arrays of Java primitive types can be used as keys. (Given an array, use the entire array as a key.) But, since primitive types are not Java objects, we need some code to make this happen. ArrayWrappers.java is the place where this happens. Each primitive type that is supported, needs its own implementation. Not all the primitive types are covered here.

It is unfortunate that there is a bunch of duplicated code in ArrayWrappers.java. Marcelo tells me that Java does not support generic methods for primitive types, so, a bunch of code has to be copy-pasted. I don't see a good way around this.

The testing in ArrapWrappersSuite.java seems adequate, though I'd like to see coverage for long[] here as well, and in the future, for any further primitive types that are supported in ArrayWrappers.

The core of the InMemoryStore implementation is an implementation of KVStore that wraps operations on an InstanceList, which itself wraps operations on a ConcurrentMap. This seems like a reasonable choice for this application.

I don't think there is much that we can do about this, but, this seems like a lot of code for a nice presentation of a ConcurrentMap. I think this is just Java, since we need an Iterator, a View, and an inner class to hold records.

I liked the use of a Java 1.8 anonymous function in InMemoryStore.write().

All the tests pass when run locally.

This change only defines the in-memory KVStore implementation. It does not wire it in to anything.

Nits:

IntelliJ had a bunch of warnings about replacing for with foreach, and about making public methods package-private.

ArrayWrappers.java: 
IntelliJ claims the following import statement appears to be unused:
import com.google.common.base.Objects;
Line 26: I would do s/used as a key/used as keys/.

InMemoryStore.java:
IntelliJ claims the following import statements appear to be unused:
import java.lang.reflect.Array;
import java.util.Arrays;
import java.util.Comparator;
import java.util.TreeMap;

**Comment by vanzin** [comment]
I plan to push this soon to unblock the next steps of the project. I'll leave this open here a little bit in case anyone is still thinking about commenting.

**Comment by vanzin** [comment]
I'll merge this and address Reynold's suggestions in a follow-up commit.

Merging to master.

**Pull request closed without merging**
