### PR TITLE
[SPARK-44340][SPARK-44341][SQL][PYTHON][FOLLOWUP] Set partition index correctly for WindowGroupLimitExec,WindowExec and WindowInPandasExec

### PR DESCRIPTION
**Pull request by beliefer**
### What changes were proposed in this pull request?
This is a followup of https://github.com/apache/spark/pull/41899 and https://github.com/apache/spark/pull/41939, to set the partition index correctly even if it's not used for now. It also contains a few code cleanup.

### Why are the changes needed?
future-proof

### Does this PR introduce _any_ user-facing change?
'No'.

### How was this patch tested?
existing tests

### CODE REVIEW

**Comment by beliefer** [comment]
ping @vinodkc cc @cloud-fan @viirya

**Review by cloud-fan — APPROVED** [review]

**Comment by cloud-fan** [comment]
thanks, merging to master/3.5!

**Comment by beliefer** [comment]
@cloud-fan @vinodkc Thank you!

**Comment by cloud-fan** [comment]
@beliefer can you open a 3.5 backport PR? one of the main PR is in 3.5 but the other is not.

**Comment by beliefer** [comment]
> @beliefer can you open a 3.5 backport PR? one of the main PR is in 3.5 but the other is not.

OK

**Review by viirya — COMMENTED** [review]
Looks good to me.

**Pull request closed without merging**
