### PR TITLE
[SPARK-42468][CONNECT][FOLLOW-UP] Add .agg variants in Dataset

### PR DESCRIPTION
**Pull request by amaliujia**
### What changes were proposed in this pull request?

Add `.agg` in Dataset in Scala client.

### Why are the changes needed?

API coverage.

### Does this PR introduce _any_ user-facing change?

NO
### How was this patch tested?

Existing UT

### CODE REVIEW

**Comment by amaliujia** [comment]
@hvanhovell

**Review by hvanhovell — APPROVED** [review]
LGTM

**Comment by hvanhovell** [comment]
@amaliujia what existing PR cover this?

**Comment by amaliujia** [comment]
@hvanhovell this one https://github.com/apache/spark/pull/40057.

**Comment by hvanhovell** [comment]
@amaliujia those tests are not exercising the new code paths. Since the change is small I am fine with merging it though.

**Comment by hvanhovell** [comment]
Merging this.

**Pull request closed without merging**
