### PR TITLE
[SPARK-12665][CORE][GRAPHX] Remove Vector, VectorSuite and GraphKryoRegistrator which are deprecated and no longer used

### PR DESCRIPTION
**Pull request by sarutak**
Whole code of Vector.scala, VectorSuite.scala and GraphKryoRegistrator.scala  are no longer used so it's time to remove them in Spark 2.0.

### CODE REVIEW

**Comment by rxin** [comment]
LGTM

**Comment by rxin** [comment]
I'd update the title to just say the classes you are removing, since there are only 3.

**Comment by sarutak** [comment]
Thanks for your suggestion. I've update the title and corresponding JIRA.

**Comment by rxin** [comment]
I've merged this.

**Pull request closed without merging**
