### PR TITLE
[SPARK-41926][UI][TESTS] Add Github action test job with RocksDB as UI backend

### PR DESCRIPTION
**Pull request by gengliangwang**
### What changes were proposed in this pull request?

Add Github action test job with RocksDB as UI backend

### Why are the changes needed?

Increase test coverage for the feature

### Does this PR introduce _any_ user-facing change?

No
### How was this patch tested?

GA tests

### CODE REVIEW

**Comment by LuciferYang** [comment]
```
[info] - writing data out metrics with dynamic partition: parquet *** FAILED *** (1 second, 416 milliseconds)
[info]   java.lang.AssertionError: assertion failed: Exactly one of node, cluster values to be set.
[info]   at scala.Predef$.assert(Predef.scala:223)
[info]   at org.apache.spark.sql.execution.ui.SparkPlanGraphNodeWrapper.toSparkPlanGraphNode(SQLAppStatusStore.scala:142)
[info]   at org.apache.spark.sql.execution.ui.SparkPlanGraphWrapper.$anonfun$toSparkPlanGraph$1(SQLAppStatusStore.scala:116)
```
a little weird

**Comment by LuciferYang** [comment]
@gengliangwang A little complicated. For the following definitions:


```
message SparkPlanGraphNodeWrapper {
  SparkPlanGraphNode node = 1;
  SparkPlanGraphClusterWrapper cluster = 2;
}
```

since both `node` and `cluster` may be null, the value should be obtained in the following way during deserialization:

```scala
    val node = if (input.hasNode) {
      deserializeSparkPlanGraphNode(input.getNode)
    } else null
```

**Comment by gengliangwang** [comment]
cc @LuciferYang @panbingkun @techaddict as well.
I tried with hard coding a rocksdb backend path before commit https://github.com/apache/spark/pull/39435/commits/0724fefa2529c57ba5b6ea83e94b3183092e7187, and tests passed.

**Review by LuciferYang — APPROVED** [review]
+1, LGTM

**Comment by LuciferYang** [comment]
Manually checked the core module with this pr as follows:

```
gh pr checkout 39435
export LIVE_UI_LOCAL_STORE_DIR=/Users/yangjie01/SourceCode/spark-ui
build/mvn clean install -Dtest.exclude.tags=org.apache.spark.tags.ExtendedLevelDBTest -pl core -am
```

test passed, and I found there are some other UI objects not match ProtobufSerializer, I will create some new jira later

**Comment by HyukjinKwon** [comment]
Merged to master.


cc @Yikun FYI if you find some time for a posthoc review.

**Review by HyukjinKwon — APPROVED** [review]

**Review by Yikun — COMMENTED** [review]
Late LGTM! Thanks @HyukjinKwon @LuciferYang @gengliangwang

**Pull request closed without merging**
