### PR TITLE
Python sqlContext.getConf() add one argument version

### PR DESCRIPTION
**Pull request by mathieulongtin**
## What changes were proposed in this pull request?

In Python, sqlContext.getConf didn't allow getting the system default (getConf with one parameter).

Now the following are supported:

```
sqlContext.getConf(confName)  # System default if not locally set, this is new
sqlContext.getConf(confName, myDefault)  # myDefault if not locally set
```

I also added doctests to this function
## How was this patch tested?

Manually, but doctests were added.

Cherrypick commit 16a74ac7055bceca23163b60d58bc5a40318d0f9.

### CODE REVIEW

**Comment by rxin** [comment]
Can you update the pull request title to include more information?

**Comment by rxin** [comment]
Also why do we need to introduce csv dependency?

**Comment by mathieulongtin** [comment]
Sorry, just cherry-pick the last commit on that branch. I'm new using git with large project that change all the time.

**Comment by mathieulongtin** [comment]
Nevermind, somehow picked the wrong branch entirely.

**Pull request closed without merging**
