### PR TITLE
[SPARK-7447][SQL] Don't re-merge Parquet schema when the relation is deserialized 

### PR DESCRIPTION
**Pull request by viirya**
JIRA: https://issues.apache.org/jira/browse/SPARK-7447

`MetadataCache` in `ParquetRelation2` is annotated as `@transient`. When `ParquetRelation2` is deserialized, we ask `MetadataCache` to refresh and perform schema merging again. It is time-consuming especially for very many parquet files.

With the new `FSBasedParquetRelation`, although `MetadataCache` is not `@transient` now, `MetadataCache.refresh()` still performs schema merging again when the relation is deserialized.

### CODE REVIEW

**Comment by scwf** [comment]
good catch

**Comment by marmbrus** [comment]
I think this codepath is going to be deleted, but we should make sure that #5526 does not suffer from the same issue.

/cc @liancheng

**Comment by viirya** [comment]
@marmbrus After checking #5526, I think this part of codes is still be there to use. So maybe this pr is still needed.

**Comment by marmbrus** [comment]
Yes, but look at the linked PR that replaces the parquet support with this
new API.

**Comment by viirya** [comment]
OK. I see. You meant https://github.com/liancheng/spark/pull/6.

**Comment by marmbrus** [comment]
Yep!

**Comment by viirya** [comment]
@marmbrus  #6090 was merged. But this problem is still there. I updated the codes. Please take a look. Thanks.

**Comment by marmbrus** [comment]
LGTM

/cc @liancheng

**Comment by liancheng** [comment]
@viirya Sorry for the late reply, I missed this PR while working on #6090. This fix LGTM, could you please rebase this PR? Notice that `fsBasedParquet.scala` was renamed back to `newParquet.scala` since the old `ParquetRelation2` implementation was finally removed.

**Comment by viirya** [comment]
@liancheng updated. Please take a look.

**Comment by liancheng** [comment]
Thanks for fixing this! Merging to master and branch-1.4.

**Pull request closed without merging**
