### PR TITLE
[SPARK-38228][SQL] Legacy store assignment should not fail on error under ANSI mode

### PR DESCRIPTION
**Pull request by gengliangwang**
### What changes were proposed in this pull request?

When using legacy store assignment for table insertion, Spark SQL force using the default cast which doesn't fail on error.

### Why are the changes needed?

As the ANSI store assignment policy force using ANSI cast, the legacy store assignment should force using the default cast which doesn't fail on error.
See discussions in https://github.com/apache/spark/pull/35511#discussion_r807529783 as well.

### Does this PR introduce _any_ user-facing change?

Yes, when using legacy store assignment for table insertion, Spark SQL force using the default cast which doesn't fail on error.

### How was this patch tested?

Unit test

### CODE REVIEW

**Review by cloud-fan — APPROVED** [review]

**Comment by gengliangwang** [comment]
Merging to master

**Comment by zengqinchris** [comment]
how to fix

**Comment by zengqinchris** [comment]
image

**Comment by zengqinchris** [comment]
set set spark.sql.storeAssignment=ANSI; is not use

**Pull request closed without merging**
