### PR TITLE
[SPARK-10526] [CORE] Display cores/memory on ExecutorsTab

### PR DESCRIPTION
**Pull request by zjffdu**
Add core/memory column on the executor tab. Verify it on standalone/yarn/mesos mode
- Pass the memory info to the executor through executor launch arguments and allow the executor pass the memory info back to driver when registering to driver. 
- Cores may change under mesos fine-grained mode, may need to do it in a follow-up ticket.

### CODE REVIEW

**Comment by jerryshao** [comment]
Hi @zjffdu , is there any other we could get memory info of each executor, is passing to executor launch arguments and reporting back the only mechanism to achieve this? I'm guessing Spark driver has enough knowledge to know the memory size of each executor, like spark.executor.memory? I'm just wondered is there any other simple way to get this information.

**Comment by zjffdu** [comment]
@jerryshao Thanks for the review. Ideally I think driver should be able to get these info. The reason why I do this way is that currently the cpu cores are also got through Executor Registration (although it can be got from driver). I don't want to get the cores and memory through different ways which will looks inconsistent.

**Comment by jerryshao** [comment]
What I concerned about is that this patch changes a lot to get core / memory information, whereas this information can be gotten from many other ways, like standalone web UI, RM UI..

**Comment by andrewor14** [comment]
ok to test

**Comment by andrewor14** [comment]
@squito this may be of interest to you

**Comment by srowen** [comment]
@zjffdu I don't think this is going to proceed. Can you close it?

**Pull request closed without merging**
