### PR TITLE
[SPARK-24129] [K8S] Add option to pass --build-arg's to docker-image-tool.sh

### PR DESCRIPTION
**Pull request by devaraj-kavali**
## What changes were proposed in this pull request?

Adding `-b arg` option to take `--build-arg` parameters to pass into the docker command

## How was this patch tested?

I verified by passing proxy details which fails without this change and succeeds with the changes.

### CODE REVIEW

**Comment by felixcheung** [comment]
@foxish

**Comment by felixcheung** [comment]
ok to test

**Comment by devaraj-kavali** [comment]
> This patch fails due to an unknown error code, -9.

I don't see any failures related to the change, can you trigger the test again?

**Comment by felixcheung** [comment]
ok to test

**Comment by felixcheung** [comment]
@devaraj-kavali could you rebase this?

**Comment by srowen** [comment]
@devaraj-kavali @skonto just checking this is still something that should be merged, ready to go?

**Comment by devaraj-kavali** [comment]
@srowen this issue still exists and needs to be merged.

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
