### PR TITLE
[SPARK-4973][CORE] Local directory in the driver of client-mode continues remaining even if application finished when external shuffle is enabled

### PR DESCRIPTION
**Pull request by sarutak**
When we enables external shuffle service, local directories in the driver of client-mode continue remaining even if application has finished.
I think local directories for drivers should be deleted.

### CODE REVIEW

**Comment by andrewor14** [comment]
Why does it matter whether it's client mode or cluster mode? I'd say it should always clean it if it's the driver (which doesn't get killed).

**Comment by sarutak** [comment]
@andrewor14 Ah, exactly. The driver is not killed until the end of the application. I'll fix my previous changes.

**Comment by andrewor14** [comment]
LGTM merging into master when tests pass

**Comment by andrewor14** [comment]
retest this please

**Pull request closed without merging**
