### PR TITLE
[SPARK-21870][SQL][FOLLOW-UP] Clean up string template formats for generated code in HashAggregateExec

### PR DESCRIPTION
**Pull request by maropu**
### What changes were proposed in this pull request?

This pr cleans up string template formats for generated code in HashAggregateExec. This changes comes from @rednaxelafx comment: https://github.com/apache/spark/pull/20965#discussion_r316418729

### Why are the changes needed?

To improve code-readability.

### Does this PR introduce any user-facing change?

No

### How was this patch tested?

N/A

### CODE REVIEW

**Review by rednaxelafx — APPROVED** [review]
LGTM pending Jenkins tests

**Comment by maropu** [comment]
Thanks for the check, @rednaxelafx !

**Comment by dongjoon-hyun** [comment]
Ur, @maropu . Although this is a follow-up, we need +1 from the Apache Spark committers in general~ I know that you are confident on this, of course. 😄

**Comment by maropu** [comment]
Thanks for the double-check, @dongjoon-hyun ;)

**Pull request closed without merging**
