### PR TITLE
[SQL][Docs] updated the documentation for explode

### PR DESCRIPTION
**Pull request by lockwobr**
the syntax was incorrect in the example in explode

### CODE REVIEW

**Comment by sarutak** [comment]
ok to test.

**Comment by sarutak** [comment]
LGTM. Pending Jenkins.

**Comment by rxin** [comment]
Jenkins, ok to test.

**Comment by srowen** [comment]
Does `...(_.split(" "))` work here too? not sure, ignore me if it can't be written that way.
Ideally put `[DOCS]` in the title please, but this may yet be something trivial enough to not need a JIRA. Please review https://cwiki.apache.org/confluence/display/SPARK/Contributing+to+Spark
@sarutak I think you can try out merging when you're ready

**Comment by lockwobr** [comment]
@srowen
Well it can kind of work that way if you type it like this (below) not sure what style spark community prefers, left it more closer to the original documentation. 

    df.explode[String, String]("words", "word"){_.split(" ")}

I didn't think that I needed a JIRA ticket. The [JIRA the documentation](https://cwiki.apache.org/confluence/display/SPARK/Contributing+to+Spark#ContributingtoSpark-ContributingCodeChanges) stated "However, trivial changes, where the what should change is virtually the same as the how it should change do not require a JIRA. Example: "Fix typos in Foo scaladoc"" 

So in the future I should put the [Docs] in the pull request? Is that what you meant?

**Comment by srowen** [comment]
Yes, seems OK to me. Just put `[DOCS]` in the title, still, as a matter of practice.

**Comment by sarutak** [comment]
Thanks @lockwobr ! Merged this to `master` and `branch-1.4`.
Thanks @rxin , @srowen for your assist!

**Pull request closed without merging**
