### PR TITLE
[MINOR] Fix grammar in error message

### PR DESCRIPTION
**Pull request by verhovsky**

### CODE REVIEW

**Review by srowen — APPROVED** [review]

**Comment by srowen** [comment]
You may have to check the test failure, but OK

**Comment by amaliujia** [comment]
Looks like the failing test needs an update on the error message.

Otherwise LGTM.

**Comment by verhovsky** [comment]
I've tried to run it like 3 times now and it seems to error on that test every time. There's 212,798 lines of log file, and I have no idea what the actual error is, if someone can point me to the relevant number I'll fix it, otherwise please feel free to close this because it's not worth it.

**Comment by amaliujia** [comment]
@verhovsky 

there is a failed test report at the bottom of those jobs that you can see the summary of the failing tests:
Screen Shot 2022-10-10 at 10 59 56 AM

**Comment by verhovsky** [comment]
Thanks, fixed

**Review by zhengruifeng — APPROVED** [review]
LGTM
just wondering if there is some spell checker plugin?

**Comment by srowen** [comment]
I'm getting a weird error from the merge script on merging this - is anyone else seeing it? other PRs seem fine.
```
Traceback (most recent call last):
  File "/Users/sean.owen/Documents/spark/./dev/merge_spark_pr.py", line 599, in <module>
    main()
  File "/Users/sean.owen/Documents/spark/./dev/merge_spark_pr.py", line 511, in main
    modified_body = re.sub(re.compile(r"<!--[^>]*-->\n?", re.DOTALL), "", pr["body"]).lstrip()
  File "/usr/local/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/re.py", line 209, in sub
    return _compile(pattern, flags).sub(repl, string, count)
```

**Comment by srowen** [comment]
Merged to master.
I figured out the script problem and will fix it

**Pull request closed without merging**
