### PR TITLE
[SPARK-8323][CORE]Remove mapOutputTracker field in TaskSchedulerImpl

### PR DESCRIPTION
**Pull request by yufan-liu**
Because TaskSchedulerImpl's mapOutputTracker field is only referenced once in TaskSetManager.
I think we could remove the mapOutputTracker field in the TaskSchedulerImpl class.
Instead, we could reference the mapOutputTracker from SparkEnv directly in TaskSetManager.

### CODE REVIEW

**Comment by srowen** [comment]
That's probably OK but what does this fix?

**Comment by yufan-liu** [comment]
@srowen Easier to read the code, especially for those who started to learn the internal implementation of spark core component.

**Comment by srowen** [comment]
I don't think that meaningfully helps readability? I would not change it just to change it; this is too trivial compared to this overhead of reviewing it.

**Comment by yufan-liu** [comment]
I just cannot figure out why we should keep the reference of mapOutputTracker field in the TaskSchedulerImpl. The mapOutputTracker can be referenced from a global entry point, which is SparkEnv. So obviously, the TaskSetManager should reference it directly from SparkEnv.

**Comment by srowen** [comment]
Close this PR please?

**Comment by andrewor14** [comment]
@yufan-liu mind closing this issue?

**Pull request closed without merging**
