### PR TITLE
[SPARK-24310] Add instrumentation to FPGrowth.

### PR DESCRIPTION
**Pull request by MrBago**
## What changes were proposed in this pull request?

Have FPGrowth keep track of model training using the Instrumentation class.

## How was this patch tested?

manually

Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Review by lu-wang-dl — COMMENTED** [review]
Thanks for the PR. It is overall good. Only one question:
Do we need to logParams as other methods?
Something like:

instr.logParams(minSupport, numPartitions, minConfidence, itemsCol, predictionCol)

**Comment by MrBago** [comment]
@ludatabricks thanks for taking a loo, I added `logParams`.

**Comment by ludatabricks** [comment]
LGTM.

**Comment by jkbradley** [comment]
I'll take a look now

**Comment by jkbradley** [comment]
LGTM
It'll be nice when we move the implementation to spark.ml in the future so that we can log more info, but this is good for now.
Thanks @MrBago and @ludatabricks !

Merging with master

**Comment by jkbradley** [comment]
Whoops!  This was merged linked to the wrong JIRA.  It should have been: https://issues.apache.org/jira/browse/SPARK-24310 for the record.

**Pull request closed without merging**
