### PR TITLE
[SPARK-45623][INFRA] Move `mllib` and `mllib-local` to separate test group

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This PR moves the `mllib` and `mllib-local` modules to a new test group to improve the stability of GitHub Action tests.

### Why are the changes needed?
The GitHub Action test task  `Run / Build modules: streaming, sql-kafka-0-10, streaming-kafka-0-10, mllib-local, mllib, yarn, kubernetes, hadoop-cloud, spark-ganglia-lgpl, connect, protobuf` is frequently killed during the testing process of the `mllib` module. 

- https://github.com/apache/spark/actions/runs/6599804849/job/17929210355
- https://github.com/apache/spark/actions/runs/6593262511/job/17915456473
- https://github.com/apache/spark/actions/runs/6589415340/job/17903888469
- https://github.com/apache/spark/actions/runs/6588090355/job/17899662512

image

From the test results, moving the mllib and mllib-local modules to a new group can improve the stability of the tests for the corresponding modules, in multiple tests of the current pr, neither the group containing the `mllib` module nor the group containing the remaining modules have failed again.

- https://github.com/LuciferYang/spark/runs/17807568217
- https://github.com/LuciferYang/spark/runs/17816186236
- https://github.com/LuciferYang/spark/runs/17828354063
- https://github.com/LuciferYang/spark/runs/17845302229
- https://github.com/LuciferYang/spark/runs/17847760930
- https://github.com/LuciferYang/spark/runs/17865354351
- https://github.com/LuciferYang/spark/runs/17922989958
- https://github.com/LuciferYang/spark/runs/17931226157

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Monitor GA

### Was this patch authored or co-authored using generative AI tooling?
Noa

### CODE REVIEW

**Comment by LuciferYang** [comment]
@HyukjinKwon @zhengruifeng @dongjoon-hyun Do we need this pr

**Review by zhengruifeng — APPROVED** [review]
LGTM

**Comment by zhengruifeng** [comment]
some ml tests are flaky, so I think it is reasonable to move them to a separate group. (I already moved `pyspark-ml-*` to a separate one).

I did some investigation (>1 year) before, and IIRC the root cause seems related to the underlying BLAS library and hard to debug.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by LuciferYang** [comment]
rebased

**Comment by LuciferYang** [comment]
Merged into master for Spark 4.0. Thanks @zhengruifeng @HyukjinKwon ~

**Review by dongjoon-hyun — COMMENTED** [review]
+1, late LGTM.

**Comment by LuciferYang** [comment]
Thanks @dongjoon-hyun

**Pull request closed without merging**
