### PR TITLE
[SPARK-24505][SQL] Forbidding string interpolation in CodeBlock

### PR DESCRIPTION
**Pull request by viirya**
## What changes were proposed in this pull request?

The code block interpolator currently accepts strings. Based on previous discussion, we should forbid string interpolation to prevent losing references to expressions (`ExprValue`) in code blocks.

## How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by viirya** [comment]
retest this please.

**Comment by viirya** [comment]
cc @cloud-fan @kiszk @hvanhovell

**Comment by viirya** [comment]
Sorry this change is quite large, but it can't split into smaller pieces because it must be changed as a whole to pass compilation.

**Comment by mgaido91** [comment]
yes, this is a great work @viirya ! It would be great if we can split it into smaller updates. What do you think about starting doing the needed changes in smaller PRs which focus only on specific part and forbidding the string interpolation after those have made the needed changes smaller?

I also like and agree with @kiszk about introducing new APIs. In particular, in the last days I checked the part related to the usage of `freshName `. IMO, we can introduce a new method `addLocalVariable` (and maybe renaming `addMutableState` to `addGlobalVariable`) and make `freshName` private (or if it not feasible as we are using it also for methods' names we can restrict its usage only to that particular case). What do you think?

**Comment by viirya** [comment]
@kiszk @mgaido91 Thanks for your comment!

> What do you think about starting doing the needed changes in smaller PRs which focus only on specific part and forbidding the string interpolation after those have made the needed changes smaller?

By disallowing string interpolation in code blocks, any strings passed into a code block won't pass the compilation. It is also more guaranteed that we don't miss any strings. It is why this change is quite big and not in many smaller pieces. Most important is, I need to have all the changes together to see if we can pass all the tests once we completely forbid string interpolation.

But it doesn't mean we need to review and merge this big change. It is still possible to break this into smaller PRs. It may work like this:

1. Split a part of change into a smaller PR, review it and finally merge it.
2. Incorporate the merged change back to this PR. Make test passed. Go back to step 1.

WDYT?

**Comment by viirya** [comment]
> 1. We are seeing many inline prefix with a few typical patterns.
> Can we introduce new APIs to avoid repetations of adding inline, for example JavaCode.className(Class[_]): JavaCode for the first call.

@kiszk I initially took a similar approach but found soon that I'd create too many APIs. I'm not pretty sure if that is what we want to have distinguish them in API level because they are all actually a simple piece of inline string in code, so I turned to a `inline` to treat them as same.

> 2. We are seeing many JavaCode.global() or JavaCode.variable() when we create a new variable.
Would it be possible to make them simpler?

Yes, I noticed that too. I was planning to change existing API such as `ctx.freshName`. But I leave it as it and set the first goal to pass all tests after forbidding string interpolation. Since the tests are passed now, I think we can incrementally make the changes more simpler and clear. I've proposed to do this part in some smaller PRs (ref: https://github.com/apache/spark/pull/21520#issuecomment-396111725). WDYT?

**Comment by kiszk** [comment]
For 1, I agree with you that it is not good to introduce many APIs at first. On the other hand, it would be good to prepare only a few APIs that are frequently used, not to prepare many APIs. It make code simpler and cleaner.
I think that `inline"${classOf[...].getName}"` and `inline"${CodeGenerator.javaType(...)}"` are frequently used. `inline"${CodeGenerator.boxedType(...)}"` may be prepared for consistency with `inline"${CodeGenerator.javaType(...)}"`.

For 2, new APIs in `ctx` can co-exist with old APIs. Thus, to introduce new APIs can co-exist with your new proposal.

WDYT?

**Comment by viirya** [comment]
@kiszk Seems good to me. I will go to create and use those APIs in pieces of PRs.

**Comment by viirya** [comment]
As I will incrementally split this into smaller PRs, I will first close this.

**Comment by HyukjinKwon** [comment]
@viirya ~ I was just trying to read the PRs. Would you please mind if I ask where is the "Based on previous discussion" ?

**Comment by viirya** [comment]
@HyukjinKwon Thanks for looking into this. It is based on the comment and discussion here https://github.com/apache/spark/pull/21193#discussion_r186627099.

**Pull request closed without merging**
