### PR TITLE
[SPARK-38829][SQL][FOLLOWUP] Add `PARQUET_TIMESTAMP_NTZ_ENABLED` configuration for `ParquetWrite.prepareWrite`

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
SPARK-38829 adds `PARQUET_TIMESTAMP_NTZ_ENABLED` configuration for  Parquet V1&V2 read, V1 write, this pr add it to Parquet V2 write process to keep the configuration consistent although File source v2 write path is currently broken.

### Why are the changes needed?
Keep the configuration consistent between Parquet V1 write and V2 write.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass GA

### CODE REVIEW

**Comment by sadikovi** [comment]
Can you add a test for this? What is "Pass GA"?

**Comment by sadikovi** [comment]
Can you link the code to highlight the inconsistency between v1 and v2 configuration? Thanks.

**Comment by LuciferYang** [comment]
> Can you add a test for this? What is "Pass GA"?

I tried refactor `ParquetIOSuite` to test V1 and V2 like `Write TimestampNTZ type`, but data still write by V1 API now due to 
`File source v2 write path is currently broken`,  let me investigate again.

**Comment by LuciferYang** [comment]
`ParquetFileFormat.prepareWrite` has the following configuration:

https://github.com/apache/spark/blob/5535d932e0c003154ebeecf8b95e8ffde828d788/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetFileFormat.scala#L122-L124

But ParquetWrite doesn't

**Comment by LuciferYang** [comment]
@sadikovi I found you added this configuration at the following location:

`ParquetFileFormat.prepareWrite`

https://github.com/apache/spark/blob/5535d932e0c003154ebeecf8b95e8ffde828d788/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetFileFormat.scala#L122-L124


`ParquetFileFormat.buildReaderWithPartitionValues`

https://github.com/apache/spark/blob/5535d932e0c003154ebeecf8b95e8ffde828d788/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetFileFormat.scala#L227-L229

`ParquetScan.createReaderFactory`

https://github.com/apache/spark/blob/5535d932e0c003154ebeecf8b95e8ffde828d788/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/v2/parquet/ParquetScan.scala#L88-L90

Do you remember why this configuration was not added to `ParquetWrite.prepareWrite`?

**Comment by sadikovi** [comment]
I think I just forgot to be honest and I did not add a test for it so the bug slipped during the review. I think we should add a test for both v1 and v2 data sources to make sure it works there if possible.

**Comment by LuciferYang** [comment]
> I think I just missed it to be honest and I did not add a test for it so the bug slipped during the review. I think we should add a test for both v1 and v2 data sources to make sure it works there if possible.

OK, let me try adding a UT

**Comment by sadikovi** [comment]
Thanks!

**Comment by LuciferYang** [comment]
I found that no UTs can cover `File source v2 write path` in Spark now, need more time to investigate

**Comment by LuciferYang** [comment]
close this first and will re-open  this when we can write parquet data through V2 API

**Pull request closed without merging**
