### PR TITLE
[SPARK-42114][SQL][TESTS] Add uniform parquet encryption test case

### PR DESCRIPTION
**Pull request by ggershinsky**
### What changes were proposed in this pull request?

Unitest of the new parquet encryption mode, available since parquet 1.12.3.
This mode is triggered by setting a hadoop parameter (/df write option) `parquet.encryption.uniform.key` : master key ID for uniform encryption of all columns and footer.

### Why are the changes needed?

To verify end to end Spark SQL encryption and decryption of dataframes in uniform mode.

### Does this PR introduce _any_ user-facing change?

No user-facing changes.

### How was this patch tested?

This patch is the unitest

### CODE REVIEW

**Comment by ggershinsky** [comment]
@dongjoon-hyun I'm submitting the PR we have discussed.

**Comment by HyukjinKwon** [comment]
Mind keeping the PR description template https://github.com/apache/spark/blob/master/.github/PULL_REQUEST_TEMPLATE?

**Comment by ggershinsky** [comment]
Thanks, done.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @ggershinsky and @HyukjinKwon .
Merged to master for Apache Spark 3.4.0.

**Comment by dongjoon-hyun** [comment]
BTW, please add `ggershinsky@apple.com` to your GitHub profile as the secondary email.
```
$ git log -n1
commit e1c630a98c45ae07c43c8cf95979532b51bf59ec (HEAD -> master, apache/master, apache/HEAD)
Author: Gidon Gershinsky <ggershinsky@apple.com>
```

Then, the GitHub commit list will show your profile image correctly, @ggershinsky .

Screenshot 2023-01-20 at 1 54 57 AM

**Comment by dongjoon-hyun** [comment]
I fixed the `Affected Version` from 3.3.1 to 3.4.0 because this fails in `branch-3.3`.
```
[info] ParquetEncryptionSuite:
[info] - SPARK-34990: Write and read an encrypted parquet (2 seconds, 461 milliseconds)
[info] - SPARK-37117: Can't read files in Parquet encryption external key material mode (476 milliseconds)
[info] - SPARK-42114: Test of uniform parquet encryption *** FAILED *** (184 milliseconds)
[info]   "PAR[E]" did not equal "PAR[1]" (ParquetEncryptionSuite.scala:140)
[info]   Analysis:
[info]   "PAR[E]" -> "PAR[1]"
```

**Comment by ggershinsky** [comment]
Thanks Dongjoon.

**Pull request closed without merging**
