### PR TITLE
[SPARK-37211][INFRA] Added descriptions and an image to the guide for enabling GitHub Actions in notify_test_workflow.yml

### PR DESCRIPTION
**Pull request by yutoacts**
### What changes were proposed in this pull request?

Descriptions and an image are added to the guide for enabling GitHub Actions in `notify_test_workflow.yml`.

### Why are the changes needed?

For first-time contributors to know how to enable workflow on their own repositories quicker

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Tested in my repository.
GA

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
do you mind showing the example of the comment?

**Comment by yutoacts** [comment]
@HyukjinKwon Thanks for the review. I'm currently trying to run the edited workflow in my repo to see if my changes work fine. I'll put the image of the result in `How was this patch tested?` section later.

**Review by HyukjinKwon — APPROVED** [review]

**Review by sarutak — APPROVED** [review]
It would be better to make the instruction more elaborate but it's O.K as it is.
Let's see whether the modified instruction can help newbies.

**Comment by sarutak** [comment]
Merged to `master`.

**Pull request closed without merging**
