### PR TITLE
[SPARK-20385][WEB-UI]'Submitted Time' field, the date format needs to be formatted, in running Drivers table or Completed Drivers table in master web ui.

### PR DESCRIPTION
**Pull request by guoxiaolongzte**
## What changes were proposed in this pull request?
Submitted Time' field, the date format **needs to be formatted**, in running Drivers table or Completed Drivers table in master web ui.
Before fix this problem  e.g.

Completed Drivers
Submission ID	             **Submitted Time**  	             Worker	                            State	   Cores	   Memory	       Main Class
driver-20170419145755-0005	 **Wed Apr 19 14:57:55 CST 2017**	 worker-20170419145250-zdh120-40412	FAILED	   1	       1024.0 MB	   cn.zte.HdfsTest

please see the  attachment:https://issues.apache.org/jira/secure/attachment/12863977/before_fix.png

After fix this problem e.g.

Completed Drivers
Submission ID	             **Submitted Time**  	             Worker	                            State	   Cores	   Memory	       Main Class
driver-20170419145755-0006	 **2017/04/19 16:01:25**	 worker-20170419145250-zdh120-40412	         FAILED	   1	       1024.0 MB	   cn.zte.HdfsTest

please see the  attachment:https://issues.apache.org/jira/secure/attachment/12863976/after_fix.png

'Submitted Time' field, the date format **has been formatted**, in running Applications table or Completed Applicationstable in master web ui, **it is correct.**
e.g.
Running Applications
Application ID	                Name	                Cores	Memory per Executor	   **Submitted Time**	      User	   State	        Duration
app-20170419160910-0000 (kill)	SparkSQL::10.43.183.120	1	    5.0 GB	               **2017/04/19 16:09:10**	  root	   RUNNING	    53 s

**Format after the time easier to observe, and consistent with the applications table,so I think it's worth fixing.**

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)
(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
@guoxiaolongzte, I think Web UI changes require snapstops.

(Also, it is not a big deal though, probably, it would be nicer if the branch is rebased and sync'ed to the Spark's master branch.)

**Comment by srowen** [comment]
Agree with those comments, though the JIRA does show the change once you format the code.

Are there other dates in the UI that aren't passed through this method? let's look for all `\${.*[dD]ate}` in the UI code to check

**Comment by guoxiaolongzte** [comment]
Ok, i'm dealing right away.@srowen


This function is very important to our large spark distributed system.Because this UI, the user concerned more, rather than our developers.@HyukjinKwon

**Comment by HyukjinKwon** [comment]
Ah, I didn't mean I am against this PR. I just wanted to make this PR better.

Just FYI in case, just simply dragging and dropping the image into PR description in edit mode uploads the images (I saw simply links were used in your last few PRs). It works fine on Windows 7 & IE (assuming your OS is Windows 7 as said in last few PRs).

Also, we can use markdown https://guides.github.com/features/mastering-markdown/ in both comments and descriptions which I do use a lot because using this can save reviewers time.

Of course, these are not required but just .. FYI.

**Comment by guoxiaolongzte** [comment]
Ok, I have not been how to upload pictures in PR, I will learn about it.Thank you.@HyukjinKwon

**Comment by guoxiaolongzte** [comment]
@srowen 
I found 9 places.
Are the following Scala files:
MesosClusterPage.scala
DriverPage.scala
ApplicationPage.scala

**Comment by guoxiaolongzte** [comment]
Can I use the Jenkins test?

**Comment by HyukjinKwon** [comment]
@guoxiaolongzte, I just tested the backquotes on Windows with Chrome as below:





It is a backquote `` ` `` not a single-quote `'`. Could you try again? I see you made many PRs and I would like them to be more readable.

**Comment by srowen** [comment]
Merged to master/2.2

**Pull request closed without merging**
