### PR TITLE
[SPARK-48582][BUILD] Upgrade `braces` from 3.0.2 to 3.0.3 in ui-test

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr aims to upgrade `braces` from 3.0.2 to 3.0.3 in ui-test.

The original pr was submitted by `dependabot`: https://github.com/apache/spark/pull/46931

### Why are the changes needed?
The new version fix vulnerability https://security.snyk.io/vuln/SNYK-JS-BRACES-6838727

- https://github.com/micromatch/braces/commit/9f5b4cf47329351bcb64287223ffb6ecc9a5e6d3

The complete list of changes is as follows:

- https://github.com/micromatch/braces/compare/3.0.2...3.0.3

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass GitHub Actions

### Was this patch authored or co-authored using generative AI tooling?
No

### CODE REVIEW

**Comment by LuciferYang** [comment]
cc @yaooqinn FYI
I manually submitted https://github.com/apache/spark/pull/46931

**Review by yaooqinn — APPROVED** [review]
LGTM

**Comment by yaooqinn** [comment]
Merged to master. Thank you @LuciferYang

**Comment by LuciferYang** [comment]
Thanks @yaooqinn

**Pull request closed without merging**
