### PR TITLE
[SPARK-32009][ML][PySpark] Remove deprecated method BisectingKMeansModel.computeCost

### PR DESCRIPTION
**Pull request by huaxingao**
### What changes were proposed in this pull request?
Remove deprecated method BisectingKMeansModel.computeCost in 3.1

### Why are the changes needed?
KMeansModel.computeCost was introduced in https://issues.apache.org/jira/browse/SPARK-11029 as a temporary solution. It was deprecated in 2.4 (https://issues.apache.org/jira/browse/SPARK-23451)  and removed in 3.0 (https://issues.apache.org/jira/browse/SPARK-25867). However, deprecation of BisectingKMeansModel.computeCost missed 2.4 release and was done in 3.0. BisectingKMeansModel.computeCost should be removed in 3.1 to be consistent with KMean. 

### Does this PR introduce _any_ user-facing change?
Yes, this introduced an API breaking change, unfortunately.

### How was this patch tested?
existing tests.

### CODE REVIEW

**Comment by huaxingao** [comment]
retest this please

**Comment by huaxingao** [comment]
retest this please

**Comment by huaxingao** [comment]
retest this please

**Comment by huaxingao** [comment]
retest this please

**Comment by huaxingao** [comment]
retest this please

**Comment by huaxingao** [comment]
retest this please

**Comment by huaxingao** [comment]
cc @srowen @zhengruifeng 
I know there are stricter rules for breaking APIs now, but I think BisectingKMeansModel.computeCost should be removed because KMeansModel.computeCost was removed in 3.0.
StringIndexer.labels was deprecated too. I am not sure if that one should be deleted as well.

**Comment by srowen** [comment]
3.0 is released; I'd have agreed for 3.0. I am not sure we can merge for 3.x. It can however be deprecated with a TODO to remove in 4.0

**Comment by zhengruifeng** [comment]
> 3.0 is released; I'd have agreed for 3.0. I am not sure we can merge for 3.x. It can however be deprecated with a TODO to remove in 4.0

+1  I think we have to mark it to be removed in 4.0

**Comment by huaxingao** [comment]
I will close this for now and reopen around 4.0 time. Thanks!

**Pull request closed without merging**
