### PR TITLE
[SPARK-35851][GRAPHX] Modify the wrong variable used in GraphGenerators.sampleLogNormal

### PR DESCRIPTION
**Pull request by zengruios**
### What changes were proposed in this pull request?
modify the wrong variable used in GraphGenerators.sampleLogNormal

### Why are the changes needed?
wrong variable used

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
UT

### CODE REVIEW

**Review by srowen — CHANGES_REQUESTED** [review]
Hm, something is wrong here, but I think it's the docs. If mu and sigma are the mean and stdev of the underlying normal, then this code is correct. The docs define m and s, but those are the mean and stdev of the lognormal distribution that results. 

I dug back into the history of this and this part was changed last almost 8 years ago (!) when it made the opposite change that you propose. My guess is that it simply never fixed the rest of the code and docs.

What we could do here is simply remove `val m` and `val s` as useless, and remove the "In this function" part and fix the formula in the docs accordingly.

**Comment by zengruios** [comment]
OK, I will change it like you say.

**Comment by srowen** [comment]
Jenkins test this please

**Comment by srowen** [comment]
Jenkins retest this please

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
