### PR TITLE
[SPARK-38723][SS][TESTS] Add test for streaming query resume race condition

### PR DESCRIPTION
**Pull request by PhilDakin**
### What changes were proposed in this pull request?
Add a test for the CONCURRENT_QUERY error raised when multiple sessions try to simultaneously resume the same streaming query from checkpoint.

### Why are the changes needed?
Improve testing coverage per https://issues.apache.org/jira/browse/SPARK-38723.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Change is itself a test - ran locally and confirmed the suite passes.
```
[info] All tests passed.
[success] Total time: 129 s (02:09), completed Oct 17, 2023, 2:11:34 PM
```

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by PhilDakin** [comment]
Build failure is in `pyspark` tests, looks unrelated.

@MaxGekk will you review this, or is there someone else to tag?

**Comment by MaxGekk** [comment]
@HeartSaVioR Could you take a look at the PR, please.

**Review by HeartSaVioR — APPROVED** [review]

**Comment by HeartSaVioR** [comment]
I see the test failure is not related. Thanks! Merging to master.

**Comment by HeartSaVioR** [comment]
@PhilDakin Could you please let me know about your ASF JIRA account? It is needed to recognize your effort in ASF JIRA. Thanks!

**Pull request closed without merging**
