### PR TITLE
[SPARK-34970][3.0][SQL] Redact map-type options in the output of explain()

### PR DESCRIPTION
**Pull request by gengliangwang**
### What changes were proposed in this pull request?

The `explain()` method prints the arguments of tree nodes in logical/physical plans. The arguments could contain a map-type option that contains sensitive data.
We should map-type options in the output of `explain()`. Otherwise, we will see sensitive data in explain output or Spark UI.
image

### Why are the changes needed?

Data security.

### Does this PR introduce _any_ user-facing change?

Yes, redact the map-type options in the output of `explain()`

### How was this patch tested?

Unit tests

### CODE REVIEW

**Comment by gengliangwang** [comment]
This is to backport https://github.com/apache/spark/pull/32066 to branch-3.0

**Review by maropu — APPROVED** [review]

**Review by HyukjinKwon — APPROVED** [review]

**Review by dongjoon-hyun — COMMENTED** [review]
Thank you for making a backport, @gengliangwang .
The second test case fails like the following. Could you fix it?
```
[info] ExplainSuite:
08:38:16.800 WARN org.apache.hadoop.util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[info] - SPARK-34970: Redact Map type options in explain output (1 second, 409 milliseconds)
[info] - SPARK-34970: Redact CaseInsensitiveMap type options in explain output *** FAILED *** (1 second, 884 milliseconds)
[info]   "== Parsed Logical Plan ==
[info]   'UnresolvedRelation [t]
[info]
[info]   == Analyzed Logical Plan ==
[info]   id: bigint
[info]   SubqueryAlias spark_catalog.default.t
[info]   +- Relation[id#xL] json
[info]
[info]   == Optimized Logical Plan ==
[info]   Relation[id#xL] json
[info]
[info]   == Physical Plan ==
[info]   FileScan json default.t[id#xL] Batched: false, DataFilters: [], Format: JSON, Location: InMemoryFileIndex[file:/Users/dongjoon/PRS/SPARK-PR-32085/sql/core/spark-warehouse/org.apache.spa..., PartitionFilters: [], PushedFilters: [], ReadSchema: struct<id:bigint>
[info]
[info]   " did not contain "value" (ExplainSuite.scala:66)
```

**Comment by gengliangwang** [comment]
@dongjoon-hyun yes.

**Review by dongjoon-hyun — APPROVED** [review]
Thank you, @gengliangwang .

**Comment by dongjoon-hyun** [comment]
Merged to branch-3.0.

**Pull request closed without merging**
