### PR TITLE
[SPARK-18774][CORE][SQL] Ignore non-existing files when ignoreCorruptFiles is enabled (branch 2.1)

### PR DESCRIPTION
**Pull request by zsxwing**
## What changes were proposed in this pull request?

Backport #16203 to branch 2.1.

## How was this patch tested?

Jennkins

### CODE REVIEW

**Comment by rxin** [comment]
LGTM

**Comment by zsxwing** [comment]
retest this please

**Comment by rxin** [comment]
Merging in branch-2.1.

**Comment by rxin** [comment]
Can you close this?

**Pull request closed without merging**
