### PR TITLE
[EC2] Update default Spark version to 1.2.1

### PR DESCRIPTION
**Pull request by potix2**

### CODE REVIEW

**Comment by srowen** [comment]
@nchammas @shivaram is this something we need to do manually with regularity or should there be any way to handle this automatically?

**Comment by shivaram** [comment]
The release branch (i.e. branch-1.2 in this case) gets updated automatically during the release process [1] - However the master branch usually needs to be manually updated.

[1] https://github.com/apache/spark/commit/07c0fd195eaddf57b3fcfffbde2a5817dff967bf

**Comment by srowen** [comment]
ok to test

**Comment by andrewor14** [comment]
LGTM merging this into master 1.3 and 1.2

**Pull request closed without merging**
