### PR TITLE
[SPARK-12719][HOTFIX] Fix compilation against Scala 2.10

### PR DESCRIPTION
**Pull request by yy2016**
## What changes were proposed in this pull request?

Compilation against Scala 2.10 fails with:
    `
    [error] [warn] /home/jenkins/workspace/spark-master-compile-sbt-scala-2.10/sql/hive/src/main/scala/org/apache/spark/sql/hive/SQLBuilder.scala:483: Cannot check match         for         unreachability.
    [error] (The analysis required more space than allowed. Please try with scalac -Dscalac.patmat.analysisBudget=512 or -Dscalac.patmat.analysisBudget=off.)
    [error] [warn]     private def addSubqueryIfNeeded(plan: LogicalPlan): LogicalPlan = plan match {
`

Changed OneRowRelation to case class
## How was this patch tested?

Compilation against Scala 2.10

### CODE REVIEW

**Comment by JoshRosen** [comment]
-1. This seems like a hacky fix compared to either bumping the analysis budget in the 2.10 compiler config or to a properly rewritten + expanded pattern match.

**Comment by yhuai** [comment]
Can you take a look at the patmatch budget of scala 2.11? Then, let's increase that for 2.10 build accordingly.

**Comment by yy2016** [comment]
@yhuai 
How about this change ?
```
diff --git a/pom.xml b/pom.xml
index 92a32e7..bdb0408 100644
--- a/pom.xml
+++ b/pom.xml
@@ -1800,6 +1800,7 @@
             <recompileMode>incremental</recompileMode>
             <useZincServer>true</useZincServer>
             <args>
+              <arg>-Dscalac.patmat.analysisBudget=512</arg>
               <arg>-unchecked</arg>
               <arg>-deprecation</arg>
               <arg>-feature</arg>
```

**Comment by JoshRosen** [comment]
Only the SBT 2.10 builder is failing, so the fix should go into SparkBuild.scala

**Pull request closed without merging**
