### PR TITLE
[SPARK-30294][SS][FOLLOW-UP] Directly override RDD methods

### PR DESCRIPTION
**Pull request by xuanyuanking**
### Why are the changes needed?
Follow the comment: https://github.com/apache/spark/pull/26935#discussion_r514697997

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Existing test and Mima test.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Hm, that comment was left a week a go before that PR was merged. I wonder why other comments were addressed afterwards but why that comment alone was not addressed. This change looks pretty straightforward and legitimate, @HeartSaVioR.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HeartSaVioR** [comment]
Please note that the PR was submitted in Dec 2019 and sit around a year. His suggestion was to add exclusion on MiMa which is not that always welcomed, as the class we were saying to exclude was "RDD".

**Comment by HyukjinKwon** [comment]
Got it :-).

**Comment by xuanyuanking** [comment]
Thanks for the quick response @HyukjinKwon @HeartSaVioR 
Yes, I volunteer to take some time investigating the Mima error as I mentioned in the comment. The `DirectAbstractMethodProblem` happens when the old method is concrete but the new one is deferred. 
https://github.com/lightbend/mima/blob/f25269a43ca3c19d0b587f61d33655eeddb888aa/core/src/main/scala/com/typesafe/tools/mima/lib/analyze/method/MethodChecker.scala#L56-L57
So it should be a Mima friendly fix then.

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by HeartSaVioR** [comment]
Late +1. Thanks for taking this up!

**Comment by maryannxue** [comment]
Can we at least write some real PR description rather than "Follow the comment: #26935 (comment)" ???

**Pull request closed without merging**
