### PR TITLE
[SPARK-13195][Streaming]Fix NoSuchElementException when a state is not set but timeoutThreshold is defined

### PR DESCRIPTION
**Pull request by zsxwing**
Check the state Existence before calling get.

### CODE REVIEW

**Comment by zsxwing** [comment]
cc @tdas

**Comment by tdas** [comment]
good catch. LGTM. Please merge to both 1.6 and master.

**Comment by zsxwing** [comment]
retest this please

**Comment by YuvalItzchakov** [comment]
Thank you guys for the quick fix. Will the updated binary be available via the spark download page or will I need to compile from source?

**Comment by zsxwing** [comment]
> Thank you guys for the quick fix. Will the updated binary be available via the spark download page or will I need to compile from source?

You need to compile from source for now. If you cannot, a workaround is always updating the state in your codes. This patch will be available in the next release 1.6.1 (should be available soon).

**Comment by zsxwing** [comment]
Merging to master and 1.6

**Comment by YuvalItzchakov** [comment]
Yes, that's how I've worked around it in the meanwhile. Thx @zsxwing

**Comment by ymeymann** [comment]
Just hit this issue too, thanks @zsxwing @YuvalItzchakov for the quick fix and workaround

**Pull request closed without merging**
