### PR TITLE
[SPARK-41412][CONNECT][TESTS][FOLLOW-UP] Exclude binary casting to make the tests to pass with/without ANSI mode

### PR DESCRIPTION
**Pull request by HyukjinKwon**
### What changes were proposed in this pull request?

This PR is another followup of https://github.com/apache/spark/pull/39034 that, instead, make the tests to pass with/without ANSI mode.

### Why are the changes needed?

Spark Connect uses isolated Spark session so setting the configuration in PySpark side does not take an effect. Therefore, the test still fails, see https://github.com/apache/spark/actions/runs/3681383627/jobs/6228030132.

We should make the tests pass with/without ANSI mode for now.

### Does this PR introduce _any_ user-facing change?
No, test-only

### How was this patch tested?

Manually tested via:

```bash
SPARK_ANSI_SQL_MODE=true ./python/run-tests --testnames 'pyspark.sql.tests.connect.test_connect_column'
```

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @amaliujia @zhengruifeng

**Review by amaliujia — APPROVED** [review]
LGTM

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by zhengruifeng** [comment]
LGTM + 1

**Pull request closed without merging**
