### PR TITLE
[SPARK-4925][SQL] Publish Spark SQL hive-thriftserver maven artifact

### PR DESCRIPTION
**Pull request by alexliu68**

### CODE REVIEW

**Comment by marmbrus** [comment]
ok to test

**Comment by marmbrus** [comment]
Thanks! Merged to master and branch-1.2.  @pwendell is going to publish sometime later this weekend.

**Comment by nettok** [comment]
I can't find the artifact in Maven in http://mvnrepository.com/artifact/org.apache.spark

Any reason why it hasn't been published yet?

**Comment by stau** [comment]
It probably got overlooked. The module needs to be published manually since it's not a default module in the root pom.

**Pull request closed without merging**
