### PR TITLE
[SPARK-29082][core] Skip delegation token generation if no credentials are available.

### PR DESCRIPTION
**Pull request by vanzin**
This situation can happen when an external system (e.g. Oozie) generates
delegation tokens for a Spark application. The Spark driver will then run
against secured services, have proper credentials (the tokens), but no
kerberos credentials. So trying to do things that requires a kerberos
credential fails.

Instead, if no kerberos credentials are detected, just skip the whole
delegation token code.

Tested with an application that simulates Oozie; fails before the fix,
passes with the fix. Also with other DT-related tests to make sure other
functionality keeps working.

### CODE REVIEW

**Review by gaborgsomogyi — APPROVED** [review]
LGTM (pending tests).

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by HyukjinKwon** [comment]
Doc failure seems unrelated.

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by gaborgsomogyi** [comment]
`[error] running /home/jenkins/workspace/SparkPullRequestBuilder@2/build/sbt -Phadoop-2.7 -Pkubernetes -Phive-thriftserver -Phadoop-cloud -Pkinesis-asl -Pyarn -Pspark-ganglia-lgpl -Phive -Pmesos test:package streaming-kinesis-asl-assembly/assembly ; process was terminated by signal 9`

**Comment by gaborgsomogyi** [comment]
retest this please

**Comment by gaborgsomogyi** [comment]
Maybe it's related since `No UGI` and `Proxy user` tests are failing.

**Comment by vanzin** [comment]
Hmm, that's a new test IIRC, I'll take a look at what's going on.

**Comment by vanzin** [comment]
The Hive tests passed locally for me. Maybe just needed a merge with master...

**Comment by vanzin** [comment]
retest this please

**Comment by vanzin** [comment]
retest this please

**Comment by vanzin** [comment]
retest this please

**Comment by vanzin** [comment]
(Looks like maven metadata is corrupt everywhere after Jenkins was restarted...)

**Comment by vanzin** [comment]
Ack. Updated the wrong branch...

**Comment by vanzin** [comment]
Ok, no more comments, I'll merge to master.

**Comment by dongjoon-hyun** [comment]
Hi, All.
This seems to break our Jenkins one profile consistently. Could you guys take a look please?
- https://amplab.cs.berkeley.edu/jenkins/view/Spark%20QA%20Test%20(Dashboard)/job/spark-master-test-maven-hadoop-3.2-jdk-11/
```
- zero-partition RDD *** FAILED ***
  java.io.IOException: Can't get Master Kerberos principal for use as renewer
  at org.apache.hadoop.mapreduce.security.TokenCache.obtainTokensForNamenodesInternal(TokenCache.java:134)
  at org.apache.hadoop.mapreduce.security.TokenCache.obtainTokensForNamenodesInternal(TokenCache.java:102)
  at org.apache.hadoop.mapreduce.security.TokenCache.obtainTokensForNamenodes(TokenCache.java:81)
  at org.apache.hadoop.mapred.FileInputFormat.listStatus(FileInputFormat.java:216)
  at org.apache.hadoop.mapred.FileInputFormat.getSplits(FileInputFormat.java:325)
  at org.apache.spark.rdd.HadoopRDD.getPartitions(HadoopRDD.scala:205)
  at org.apache.spark.rdd.RDD.$anonfun$partitions$2(RDD.scala:256)
  at scala.Option.getOrElse(Option.scala:189)
  at org.apache.spark.rdd.RDD.partitions(RDD.scala:254)
  at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:49)
```

**Comment by dongjoon-hyun** [comment]
Sorry guys. Until now, I cannot find a solution for this. I'll revert this one to unblock our JDK11 monitoring. Please make another PR and test with `[test-hadoop3.2][test-java11]`.

**Comment by dongjoon-hyun** [comment]
FYI, all the failures are recovered and the Jenkins is continuing to the next step. If this doesn't hide the other failure during the outage, I guess the Jenkins will pass.
- https://amplab.cs.berkeley.edu/jenkins/view/Spark%20QA%20Test%20(Dashboard)/job/spark-master-test-maven-hadoop-3.2-jdk-11/443/
```
FileSuite:
- text files
- text files (compressed)
- text files do not allow null rows
- SequenceFiles
- SequenceFile (compressed)
- SequenceFile with writable key
- SequenceFile with writable value
- SequenceFile with writable key and value
- implicit conversions in reading SequenceFiles
- object files of ints
- object files of complex types
- object files of classes from a JAR
- write SequenceFile using new Hadoop API
- read SequenceFile using new Hadoop API
- binary file input as byte array
- portabledatastream caching tests
- portabledatastream persist disk storage
- portabledatastream flatmap tests
- SPARK-22357 test binaryFiles minPartitions
- minimum split size per node and per rack should be less than or equal to maxSplitSize
- fixed record length binary file as byte array
- negative binary record length should raise an exception
- file caching
- prevent user from overwriting the empty directory (old Hadoop API)
- prevent user from overwriting the non-empty directory (old Hadoop API)
- allow user to disable the output directory existence checking (old Hadoop API)
- prevent user from overwriting the empty directory (new Hadoop API)
- prevent user from overwriting the non-empty directory (new Hadoop API)
- allow user to disable the output directory existence checking (new Hadoop API
- save Hadoop Dataset through old Hadoop API
- save Hadoop Dataset through new Hadoop API
- Get input files via old Hadoop API
- Get input files via new Hadoop API
- spark.files.ignoreCorruptFiles should work both HadoopRDD and NewHadoopRDD
- spark.hadoopRDD.ignoreEmptySplits work correctly (old Hadoop API)
- spark.hadoopRDD.ignoreEmptySplits work correctly (new Hadoop API)
- spark.files.ignoreMissingFiles should work both HadoopRDD and NewHadoopRDD
```

**Comment by srowen** [comment]
Yeah, I found this caused tests to fail locally too, so it's at least not specific to Jenkins (or Java 11)

**Comment by dongjoon-hyun** [comment]
In addition to this, one another big issue is that one Python UT failure blocks `spark-master-test-sbt-hadoop-2.7` for a long time until now.
- https://amplab.cs.berkeley.edu/jenkins/view/Spark%20QA%20Test%20(Dashboard)/job/spark-master-test-sbt-hadoop-2.7/

**Comment by gaborgsomogyi** [comment]
Having a look but jdk11 has to be set up locally where I have some difficulty...

**Comment by gaborgsomogyi** [comment]
We've found the issue with the help of @squito so going to file a PR soon with the required change...

**Comment by dongjoon-hyun** [comment]
Great! Thank you, @gaborgsomogyi and @squito !

**Pull request closed without merging**
