### PR TITLE
[SPARK-16409] [SQL] regexp_extract with optional groups causes NPE

### PR DESCRIPTION
**Pull request by srowen**
## What changes were proposed in this pull request?

regexp_extract actually returns null when it shouldn't when a regex matches but the requested optional group did not. This makes it return an empty string, as apparently designed.
## How was this patch tested?

Additional unit test

### CODE REVIEW

**Comment by srowen** [comment]
Merged to master/2.0/1.6

**Comment by ericl** [comment]
I think this broke the build: ```[error] /home/jenkins/workspace/spark-branch-1.6-compile-maven-with-yarn-2.4/sql/core/src/test/scala/org/apache/spark/sql/StringFunctionsSuite.scala:82: value toDF is not a member of Seq[String] [error] val df = Seq("aaaac").toDF("s") [error] ^ [warn] two warnings found [error] one error found```

**Comment by srowen** [comment]
Yes, for 1.6: https://github.com/apache/spark/pull/14526

**Comment by rxin** [comment]
@srowen did anybody review this?

**Comment by srowen** [comment]
I proceeded for lack of comments, and because this reproduces the Max's test case in the JIRA.

**Pull request closed without merging**
