### PR TITLE
[SPARK-37575][SQL][FOLLOWUP] Add legacy flag for the breaking change of write null value in csv to unquoted empty string

### PR DESCRIPTION
**Pull request by anchovYu**
### What changes were proposed in this pull request?

Add a legacy flag `spark.sql.legacy.nullValueWrittenAsQuotedEmptyStringCsv` for the breaking change introduced in https://github.com/apache/spark/pull/34853 and https://github.com/apache/spark/pull/34905 (followup).

The flag is disabled by default, so the null values written as csv will output an unquoted empty string. When the legacy flag is enabled, the null will output quoted empty string.

### Why are the changes needed?
The original commit is a breaking change, and breaking changes should be encouraged to add a flag to turn it off for smooth migration between versions.

### Does this PR introduce _any_ user-facing change?
With the default value of the conf, there is no user-facing difference.
If users turn this conf off, they can restore the pre-change behavior.

### How was this patch tested?
Through unit tests.

### CODE REVIEW

**Comment by anchovYu** [comment]
Hi @cloud-fan @MaxGekk would you take a look? Thank you!

**Comment by cloud-fan** [comment]
I'm not sure this is a breaking change. It changes what to write to CSV for null values, which changes the query result (a correctness bug fix) but doesn't break queries.

**Comment by cloud-fan** [comment]
OK `to_csv` function is affected.

**Comment by anchovYu** [comment]
After discussion with @cloud-fan , we still would like to treat it as a breaking change that needs a legacy flag. Hi @cloud-fan, could you review this PR? Thank you!

The test job running: https://github.com/anchovYu/spark/actions/runs/2168649483

**Review by cloud-fan — APPROVED** [review]

**Comment by cloud-fan** [comment]
thanks, merging to master/3.3!

**Comment by cloud-fan** [comment]
Ah sorry I forgot about migration guide. @anchovYu can you open a followup PR to update https://github.com/apache/spark/pull/34905/files#diff-b6c16c7a1a4e60bacda4674b52f9eecde3c8a86f281fb3ef21052267f94c1f01R55 ?

**Comment by anchovYu** [comment]
Oh sorry will do!

**Comment by anchovYu** [comment]
The followup migration guide update: https://github.com/apache/spark/pull/36268

**Pull request closed without merging**
