### PR TITLE
[Spark-8343] [Streaming] [Docs] Improve Spark Streaming Guides.

### PR DESCRIPTION
**Pull request by dusenberrymw**
This improves the Spark Streaming Guides by fixing broken links, rewording confusing sections, fixing typos, adding missing words, etc.

### CODE REVIEW

**Comment by dusenberrymw** [comment]
@JoshRosen Here is the improved version of #6800 that is merged better.

**Comment by rxin** [comment]
Thanks. I'm merging this in master & branch-1.4.

**Comment by dusenberrymw** [comment]
Great, thanks!




--



Michael W. DusenberryB.S. Computer Science

Appalachian State University


GitHub: github.com/dusenberrymw

LinkedIn: linkedin.com/in/mikedusenberry

**Comment by dusenberrymw** [comment]
Great, thanks!

**Pull request closed without merging**
