### PR TITLE
[SPARK-21039] [Spark Core] Use treeAggregate instead of aggregate in DataFrame.stat.bloomFilter

### PR DESCRIPTION
**Pull request by rishabhbhardwaj**
## What changes were proposed in this pull request?
To use treeAggregate instead of aggregate in DataFrame.stat.bloomFilter to parallelize the operation of merging the bloom filters
(Please fill in changes proposed in this fix)

## How was this patch tested?
unit tests passed
(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)
(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
I think we need some figures here. Would you test before/after and share some figures?

**Comment by lovasoa** [comment]
I ran some tests on a cluster with 5 nodes, creating a bloomfilter (with an fpp of 10%) of the column `o_orderkey` of the table `ORDERS` of TPC-H with a scale factor of 100.


## The cluster
image

## Results

### Using `RDD.aggregate`
image

Notice the huge scheduler delay.

** total time: 52 seconds**

### Using `RDD.treeAggregate`

image

#### first stage
image

#### second stage

image

** total time: 17 seconds**

**Comment by lovasoa** [comment]
## Smaller data
You might be wondering: what about smaller data ?
Adding a stage to the computation of course adds some overhead.

I repeated the same experiment as mentioned above, but with a scale factor of 1, (and 1.5M elements in the bloom filter).

### With `RDD.aggregate`
image

### With `RDD.treeAggregate`

image

## conclusion

There is indeed an overhead, but it is quite small. For the creation of a small bloom filter, the old method (with `aggregate`) takes 0.3 seconds, and the new one (with `treeAggregate`) 0.6 seconds.

**Review by srowen — APPROVED** [review]
I'm inclined to use treeAggregate where possible. I think the win for larger data sets is worthwhile.

**Review by HyukjinKwon — APPROVED** [review]
LGTM too given both are semantically identical and the same reason with ^.

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
