### PR TITLE
[SPARK-48507][INFRA] Use Hadoop 3.3.6 winutils in `build_sparkr_window`

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to use `Hadoop 3.3.6` winutils in `build_sparkr_window`.

### Why are the changes needed?
Let's use the latest version.
https://github.com/cdarlint/winutils/tree/master

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
N/A

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
This is fine - you don't need to test. Let's just merge this.

**Comment by panbingkun** [comment]
> This is fine - you don't need to test. Let's just merge this.

Okay, let me make it ready.

**Comment by panbingkun** [comment]
> This is fine - you don't need to test. Let's just merge this.

Done.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
