### PR TITLE
[SPARK-25891][PYTHON] Upgrade to Py4J 0.10.8.1

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
## What changes were proposed in this pull request?

Py4J 0.10.8.1 is released on October 21st and is the first release of Py4J to support Python 3.7 officially. We had better have this to get the official support. Also, there are some patches related to garbage collections.

https://www.py4j.org/changelog.html#py4j-0-10-8-and-py4j-0-10-8-1

## How was this patch tested?

Pass the Jenkins.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by srowen** [comment]
That sounds like a good idea. I wonder if it's safe to back-port to 2.4/2.3? should be if it's just a maintenance release.

**Comment by dongjoon-hyun** [comment]
Thank you, @srowen . I think it's safe to backport. Previously, we backported Py4J 0.7 to `2.4/2.3/2.2/2.1` for security fixes. We need separate PRs per branch to trigger Jenkins.

After review, I'll merge this to `master` only since we are in the middle of voting RC5. For the rest, I'll try later.

**Comment by dongjoon-hyun** [comment]
Hi, @HyukjinKwon and @BryanCutler . Could you review this PR, too?

**Review by BryanCutler — APPROVED** [review]
LGTM!

**Comment by dongjoon-hyun** [comment]
Thank you for review and approval, @BryanCutler .
Merged to master.

**Comment by HyukjinKwon** [comment]
Late LGTM!

**Pull request closed without merging**
