### PR TITLE
[SPARK-34795][SPARK-35192][SPARK-35293][SPARK-35327][SQL][TESTS][3.1] Adds a new job in GitHub Actions to check the output of TPC-DS queries 

### PR DESCRIPTION
**Pull request by maropu**
### What changes were proposed in this pull request?

This PR proposes to add a new job in GitHub Actions to check the output of TPC-DS queries.

NOTE: To generate TPC-DS table data in GA jobs, this PR includes generator code implemented in https://github.com/apache/spark/pull/32243 and https://github.com/apache/spark/pull/32460.

This is the backport PR of https://github.com/apache/spark/pull/31886.

### Why are the changes needed?

There are some cases where we noticed runtime-realted bugs after merging commits (e.g. .SPARK-33822). Therefore, I think it is worth adding a new job in GitHub Actions to check query output of TPC-DS (sf=1).

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

The new test added.

### CODE REVIEW

**Comment by maropu** [comment]
NOTE: Since it is difficult to backport these commits separately, I made a single PR for them.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM if this is the final, @maropu .

**Comment by dongjoon-hyun** [comment]
We are not going to bring SPARK-35327, right? If you want SPARK-35327 too, let's hold on this PR.

**Comment by maropu** [comment]
> We are not going to bring SPARK-35327, right? If you want SPARK-35327 too, let's hold on this PR.

Yea, right. That should be included in this PR, too.

**Comment by dongjoon-hyun** [comment]
Ya, then, let's wait until it lands on the master branch. Thank you for the confirmation, @maropu .

**Comment by dongjoon-hyun** [comment]
Thank you, @maropu . Merged to branch-3.1.

**Comment by maropu** [comment]
Thanks you, @dongjoon-hyun ~

**Pull request closed without merging**
