### PR TITLE
[SPARK-5783] Better eventlog-parsing error messages

### PR DESCRIPTION
**Pull request by ryan-williams**

### CODE REVIEW

**Comment by andrewor14** [comment]
looks good, but it doesn't compile

**Comment by ryan-williams** [comment]
ha yea, need to update test call-sites, brb

**Comment by ryan-williams** [comment]
hopefully fixed now

**Comment by andrewor14** [comment]
retest this please

**Comment by andrewor14** [comment]
Thanks merging into master and 1.3

**Comment by ryan-williams** [comment]
thanks @andrewor14! OOC, what was your calculus for judging build [27379](https://github.com/apache/spark/pull/4573#issuecomment-74163534) above to have been a spurious failure and asking for a retest? I'd looked at it and optimistically thought that maybe that was the situation, but was not sure.

**Comment by andrewor14** [comment]
We've seen flaky objenesis failures taking down a range of tests before. Hopefully this was fixed with a recent patch that was merged: #4578

**Comment by pwendell** [comment]
Thanks @ryan-williams - this is a useful feature.

**Pull request closed without merging**
