### PR TITLE
[SPARK-47396][SQL] Add a general mapping for TIME WITHOUT TIME ZONE to TimestampNTZType

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

Add a general mapping for TIME WITHOUT TIME ZONE to TimestampNTZType

### Why are the changes needed?

TIME WITHOUT TIME ZONE should be able to be configured to map to TimestampNTZType like TIMESTAMP WITHOUT TIME ZONE

### Does this PR introduce _any_ user-facing change?

yes, TIME WITHOUT TIME ZONE can be mapped to TimestampNTZType when preferTimestampNTZ is true

### How was this patch tested?

new tests

### Was this patch authored or co-authored using generative AI tooling?
no

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you for making this general, @yaooqinn .

Pending CIs.

**Comment by yaooqinn** [comment]
Thank you @dongjoon-hyun

**Comment by dongjoon-hyun** [comment]
Oh, it seems that the newly added test case fails at `PostgresIntegrationSuite`.
```
[info] PostgresIntegrationSuite:
[info] - Type mapping for various types (209 milliseconds)
[info] - Basic write test (293 milliseconds)
[info] - Creating a table with shorts and floats (80 milliseconds)
[info] - SPARK-47390: Convert TIMESTAMP/TIME WITH TIME ZONE regardless of preferTimestampNTZ *** FAILED *** (55 milliseconds)
[info]   1970-01-01T09:22:31.949271 was not instance of java.sql.Timestamp (PostgresIntegrationSuite.scala:293)
```

**Comment by dongjoon-hyun** [comment]
Oh, it fails at the previous PR (SPARK-47390) instead of this PR, SPARK-47396.

**Comment by yaooqinn** [comment]
Oops...I Will check the pg time types again. The typeNames for times are copied from existing code，and they might be wrong

**Comment by dongjoon-hyun** [comment]
https://github.com/apache/spark/pull/45522 is merged.

Could you rebase this PR to the `master` branch once more?

**Comment by yaooqinn** [comment]
Thank you very much @dongjoon-hyun

**Comment by dongjoon-hyun** [comment]
Merged to master for Apache Spark 4.0.0. Thank you, @yaooqinn .

**Pull request closed without merging**
