### PR TITLE
[SPARK-33131][SQL][2.4] Fix grouping sets with having clause can not resolve qualified col name

### PR DESCRIPTION
**Pull request by ulysses-you**
This is [#30029](https://github.com/apache/spark/pull/30029) backport for branch-2.4.

### What changes were proposed in this pull request?

Correct the resolution of having clause.

### Why are the changes needed?

Grouping sets construct new aggregate lost the qualified name of grouping expression. Here is a example:
```
-- Works resolved by `ResolveReferences`
select c1 from values (1) as t1(c1) group by grouping sets(t1.c1) having c1 = 1

-- Works because of the extra expression c1
select c1 as c2 from values (1) as t1(c1) group by grouping sets(t1.c1) having t1.c1 = 1

-- Failed
select c1 from values (1) as t1(c1) group by grouping sets(t1.c1) having t1.c1 = 1
```

It wroks with `Aggregate` without grouping sets through `ResolveReferences`, but Grouping sets not works since the exprId has been changed.

### Does this PR introduce _any_ user-facing change?

Yes, bug fix.

### How was this patch tested?

add test.

### CODE REVIEW

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
Please proceed `branch-3.0` first, @ulysses-you .

cc @cloud-fan

**Comment by ulysses-you** [comment]
@dongjoon-hyun thank you, I will push branch-3.0.

**Comment by ulysses-you** [comment]
Seems this error is not related.
```
Traceback (most recent call last):
  File "/home/runner/work/spark/spark/python/pyspark/mllib/tests.py", line 1492, in test_training_and_prediction
    self._eventually(condition, timeout=180.0)
  File "/home/runner/work/spark/spark/python/pyspark/mllib/tests.py", line 133, in _eventually
    lastValue = condition()
  File "/home/runner/work/spark/spark/python/pyspark/mllib/tests.py", line 1487, in condition
    self.assertGreater(errors[1] - errors[-1], 0.3)
AssertionError: -0.07000000000000006 not greater than 0.3
```

cc @viirya @HyukjinKwon  can we backport [#23586](https://github.com/apache/spark/pull/23586) in branch-2.4 ?

**Comment by viirya** [comment]
Ok, let me backport #23586 to branch-2.4.

**Comment by viirya** [comment]
Created #30078.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @ulysses-you and @viirya .
Merged to branch-2.4.

**Comment by ulysses-you** [comment]
thanks for merging!

**Pull request closed without merging**
