### PR TITLE
[SPARK-8851][YARN] In Yarn client mode, Client.scala does not login even when credentials are specified

### PR DESCRIPTION
**Pull request by harishreedharan**
Client.scala does not login since we check if args.principal is null before logging in, which it is since it is passed via SparkConf.
This PR addresses this by ensuring that we login in Client.scala in either case, and also pass the credentials correctly.

### CODE REVIEW

**Comment by harishreedharan** [comment]
@tgravescs Could you please take a look?

**Comment by harishreedharan** [comment]
@SaintBacchus Can you please try this patch out and see if this fixes the issue you reported in #7158 ?

**Comment by SaintBacchus** [comment]
@harishreedharan I think it's not the same problem I reported.
I issue is that: `Streaming` will read the ckeckpoint file before it starts up a `SparkContext`, so in `Yarn-Client` mode we have to `login` before initial the `SparkContext`.
Will you take a look at my issue again if you have time?

**Comment by harishreedharan** [comment]
I am not sure why this would not fix it, since the initial login in client
happens before the spark context is created anyway. So the tokens should
already be there so the read from checkpoint would still be possible. Did
you verify that the issue you saw exists even with this patch?

On Tuesday, July 7, 2015, huangzhaowei <notifications@github.com> wrote:

> @harishreedharan <https://github.com/harishreedharan> I think it's not
> the same problem I reported.
> I issue is that: Streaming will read the ckeckpoint file before it starts
> up a SparkContext, so in Yarn-Client mode we have to login before initial
> the SparkContext.
> Will you take a look at my issue again if you have time?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apache/spark/pull/7255#issuecomment-119130485>.
>


-- 

Thanks,
Hari

**Comment by SaintBacchus** [comment]
@harishreedharan I  had tested it out, your batch did not apply my issue
Use this command twice (both the principal is expired)
```
bin/spark-submit --class xx.KafkaWordCount --master yarn-client --principal spark/hadoop.hadoop.com@HADOOP.COM   --keytab spark.keytab
```
The second time it will throw this exception:
```
 javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]
```

WordCount Code:
```scala
    val ssc = StreamingContext.getOrCreate("checkpoint", ()=> {wordCountFunction(args)})
    ssc.start()
    ssc.awaitTermination()


  def wordCountFunction(args: Array[String]) = {
    val Array(zkQuorum, group, topics, numThreads) = args
    val sparkConf = new SparkConf().setAppName("KafkaWordCount")
    val ssc =  new StreamingContext(sparkConf, Seconds(5))
    ssc.checkpoint("checkpoint")

    val topicMap = topics.split(",").map((_,numThreads.toInt)).toMap
    val lines = KafkaUtils.createStream(ssc, zkQuorum, group, topicMap).map(_._2)
    val words = lines.flatMap(_.split(" "))
    val wordCounts = words.map(x => (x, 1L)).reduceByKey(_+_).transform(x=>x.sortByKey())
    wordCounts.print()
    ssc
  }
```

**Comment by tgravescs** [comment]
the logic looks good. seems like you might be able to simplify some of the ifs with option orelse but its not a big deal.    I'm curious to find out what the issue is for @SaintBacchus

**Comment by harishreedharan** [comment]
As we discussed on #7158, I am going to move the call to do login/credentials setup to `SparkSubmit`. Though I don't really like this, it seems like the only way to get the credentials in the user code in client mode

**Comment by harishreedharan** [comment]
@SaintBacchus Can you give this patch a try? This should fix the issue - and is a bit more generic allowing HDFS access from user code, including reading from checkpoint.

**Comment by harishreedharan** [comment]
@tgravescs I think this one is ready - this should take care of the issue @SaintBacchus reported as well.

**Comment by SaintBacchus** [comment]
@harishreedharan I had tested your PR with my issue, it actually work.
But I doubt  few user may start up `SparkContext` directly bypassing the 'SparkSubmit' , can they still use this?

**Comment by harishreedharan** [comment]
No, that would not work. We can document that if that is the case, you'd really need to do `kinit` yourself.

**Comment by harishreedharan** [comment]
@tgravescs - So this fixes this one issue with yarn-client mode, but there is one issue that actually has always been the case with this one in yarn-client. Since we don't re-login, it looks like we can't actually write to HDFS from user code. My assumption was that the HDFS client API takes care of this, but I get this on the application logs, while the executors continued to write without issues:

```
org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.security.token.SecretManager$InvalidToken): token (HDFS_DELEGATION_TOKEN token 66 for hari) is expired
	at org.apache.hadoop.ipc.Client.call(Client.java:1468)
	at org.apache.hadoop.ipc.Client.call(Client.java:1399)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:232)
	at com.sun.proxy.$Proxy12.renewLease(Unknown Source)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.renewLease(ClientNamenodeProtocolTranslatorPB.java:571)
	at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:187)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
	at com.sun.proxy.$Proxy13.renewLease(Unknown Source)
	at org.apache.hadoop.hdfs.DFSClient.renewLease(DFSClient.java:878)
	at org.apache.hadoop.hdfs.LeaseRenewer.renew(LeaseRenewer.java:417)
	at org.apache.hadoop.hdfs.LeaseRenewer.run(LeaseRenewer.java:442)
	at org.apache.hadoop.hdfs.LeaseRenewer.access$700(LeaseRenewer.java:71)
	at org.apache.hadoop.hdfs.LeaseRenewer$1.run(LeaseRenewer.java:298)
	at java.lang.Thread.run(Thread.java:745)
```

So either we can doc this and ask the user to `kinit` or somehow trigger re-logins in `SparkSubmit` (I am already not a fan of the current change in `SparkSubmit` though). I am fine with either - what do you suggest?

**Comment by tgravescs** [comment]
I totally missed that.   Basically the problem is that the AM is the one that re-logs in and the executors do to, but in the client mode the driver never does, correct?

The exception you report is after 24 hours?  hdfs client will re-login from keytab if the original login if based on a keytab.  With this patch and not logging in via kinit before launching does that exception still occur?

We should fix it so driver re-logs in.  Did you look to see if its possible just to have the driver login similar to the executors?  Like in the YarnClientSchedulerBackend.

On this patch I'm a bit torn.  We didn't document that we would automatically login for you when keytab specified did we?    If we can't make it reliably work all the time in a clean manner I'm almost at the point of we just close it as won't fix and require user to kinit.  

@SaintBacchus how much of an issue is there really for you?

**Comment by harishreedharan** [comment]
Thanks for taking a look!

The exception is not after 24 hours, but after the token renewal interval configured in hdfs-site (I set it to like 10 mins). I didn't try kinit-ing before. I can give that a shot.

I am going to make some change such that it works for both yarn client and cluster mode without too much un-clean code changes.

**Comment by vanzin** [comment]
Last version LGTM. The only minor worry I have is that this may cause multiple logins within some small time window (e.g. user kinits then calls spark-submit, or multiple spark-submit calls in a small period), which may cause login failures. But that issue already existed before in yarn-cluster mode.

**Comment by harishreedharan** [comment]
Jenkins, test this please

**Comment by harishreedharan** [comment]
There is a bug that is causing this to fail in client mode again. I will fix and test it tomorrow and update this PR

**Comment by andrewor14** [comment]
@harishreedharan Thanks for testing this on a real cluster.

On a separate note, I find it a little scary that our unit tests are totally happy even when there is a real issue with client mode. Is there a way to add a test for this feature somehow? I understand there isn't great testing infrastructure for the YARN integration code, so if there's not an easy way to do it feel free to let me know and we can investigate separately.

**Comment by harishreedharan** [comment]
@andrewor14 Right..I'd really love to add unit tests for the whole end-to-end YARN tests - testing on a real cluster is pain (building and then uploading the jar after each change takes quite a while). We should find a way to test the yarn integration in a better way. I will file a jira for this

**Comment by andrewor14** [comment]
Sounds good.

**Comment by harishreedharan** [comment]
I am closing this one for now. I am not happy with the fix which will work for both. I will look at this in sometime, re-thinking the whole thing.

**Pull request closed without merging**
