### PR TITLE
[SPARK-10889] [Streaming] Bump KCL to add MillisBehindLatest metric

### PR DESCRIPTION
**Pull request by akatz**
I don't believe the API changed at all.

### CODE REVIEW

**Comment by srowen** [comment]
Seems OK to me, but the usual question is simply, does it introduce any potential problems too? changes dependencies, incompatible behavior, etc? might skim the release notes and commits if you can to sanity check.

**Comment by akatz** [comment]
I skimmed the changes, it doesn't seem like they changed the public record processing API at all.

**Comment by srowen** [comment]
Merged to master / 1.5

**Comment by MLnick** [comment]
@akatz did you run the Kinesis-specific tests for this PR? It appears this change may have broken Kinesis Streaming in 1.5.2 - https://mail-archives.apache.org/mod_mbox/spark-user/201512.mbox/%3CCALD%2B6GMXKOR5%3DbGYQhezXbV_qaJsoi2Y2cSbaDETeefWbh84Qg%40mail.gmail.com%3E

**Pull request closed without merging**
