### PR TITLE
[SPARK-13190][BUILD] Update pom.xml to reference Scala 2.11

### PR DESCRIPTION
**Pull request by lresende**

### CODE REVIEW

**Comment by JoshRosen** [comment]
Jenkins, this is ok to test.

While this is a correct change, I don't think the old value was actually a problem in practice because it always gets overridden by either the `scala-2.10` or `scala-2.11` profiles, one of which is always active.

**Comment by JoshRosen** [comment]
Jenkins, retest this please.

**Comment by rxin** [comment]
@lresende  thanks for doing this. Please merge the relevant pull requests into a single one.

**Comment by lresende** [comment]
@rxin this is now merged into #11092

**Pull request closed without merging**
