### PR TITLE
[SPARK-49784][PYTHON][TESTS] Add more test for `spark.sql`

### PR DESCRIPTION
**Pull request by zhengruifeng**
### What changes were proposed in this pull request?
add more test for `spark.sql`

### Why are the changes needed?
for test coverage

### Does this PR introduce _any_ user-facing change?
no, test only

### How was this patch tested?
ci

### Was this patch authored or co-authored using generative AI tooling?
no

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]

**Review by dongjoon-hyun — COMMENTED** [review]
Just a question. When it comes to `SQL statement` test, do you think we can have a SQL file based test like we do in `sql` and `hive` module? If we can reuse the existing ones, it would be perfect, @zhengruifeng .

- https://github.com/apache/spark/blob/master/sql/core/src/test/resources/sql-tests/inputs/array.sql

**Review by dongjoon-hyun — APPROVED** [review]

**Comment by zhengruifeng** [comment]
@dongjoon-hyun good point, but I think we cannot reuse existing sql side `.sql` files for now, because this test is mainly for python side feature, e.g.
```
        df0 = self.spark.range(10)
        df1 = self.spark.sql(
            "SELECT * FROM {df} WHERE id > ?",
            args=[1],
            df=df0,
        )
```
which takes a PySpark dataframe as a named argument.

But probably it is doable to introduce a similar framework for PySpark in the future.

**Review by xinrong-meng — APPROVED** [review]

**Comment by xinrong-meng** [comment]
LGTM, thank you!

**Comment by dongjoon-hyun** [comment]
Thanks, @zhengruifeng . It makes sense.

**Comment by zhengruifeng** [comment]
thanks all, merged to master

**Pull request closed without merging**
