### PR TITLE
[SPARK-24931][INFRA][2.4] Fix the GA failure related to R linter

### PR DESCRIPTION
**Pull request by sarutak**
### What changes were proposed in this pull request?

This PR backports the change of #32028 .

This PR fixes the GA failure related to R linter which happens on some PRs (e.g. #32023, #32025).
The reason seems `Rscript -e "devtools::install_github('jimhester/lintr@v2.0.0')"` fails to download `lintr@v2.0.0`.
I don't know why but I confirmed we can download `v2.0.1`.

### Why are the changes needed?

To keep GA healthy.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

GA itself.

### CODE REVIEW

**Comment by sarutak** [comment]
cc: @dongjoon-hyun @HyukjinKwon

**Comment by srowen** [comment]
Merged to 2.4

**Comment by dongjoon-hyun** [comment]
Thank you, @sarutak and @srowen .

**Comment by HyukjinKwon** [comment]
👍👍👍

**Pull request closed without merging**
