### PR TITLE
[SPARK-15722][SQL] Disallow specifying schema in CTAS statement

### PR DESCRIPTION
**Pull request by andrewor14**
## What changes were proposed in this pull request?

As of this patch, the following throws an exception because the schemas may not match:

```
CREATE TABLE students (age INT, name STRING) AS SELECT * FROM boxes
```

but this is OK:

```
CREATE TABLE students AS SELECT * FROM boxes
```
## How was this patch tested?

SQLQuerySuite, HiveDDLCommandSuite

### CODE REVIEW

**Comment by andrewor14** [comment]
@cloud-fan @clockfly

**Comment by cloud-fan** [comment]
I  think this should also throw exception
```
CREATE TABLE students (age INT, name STRING) AS SELECT 1, 'hello'
```

A `SELECT` also defines both the name and data type of its output(the `projectList` in `Project` are all `NamedExpression`), we should not define the schema again.

BTW, what's the behaviour of other DB?

**Comment by andrewor14** [comment]
Sounds good. I've updated the patch.

**Comment by cloud-fan** [comment]
LGTM

**Comment by cloud-fan** [comment]
m2.0

**Comment by xubo245** [comment]
Can CTAS support create table with schema?
Already support:
```
 create table t1(i1 int);
 insert into t1 select i2 from t2;
```
 but don't support this:
```
create table t1 (i1 int) as select 2 from t2;
```

Can spark support it?

**Comment by cloud-fan** [comment]
Can you point out which database supports this?

**Pull request closed without merging**
