### PR TITLE
[SPARK-47844][BUILD][3.4] Upgrade ORC to 1.8.7

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to upgrade ORC to 1.8.7.

### Why are the changes needed?

To bring the latest bug fixes.
- https://orc.apache.org/news/2024/04/14/ORC-1.8.7/
- https://github.com/apache/orc/releases/tag/v1.8.7

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the CIs.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
This is tested during Apache ORC 1.8.7 RC0 vote
- https://github.com/dongjoon-hyun/spark/pull/14

**Comment by dongjoon-hyun** [comment]
Could you review this for Apache Spark 3.4.3 release, please, @viirya ?

**Review by viirya — APPROVED** [review]
Looks good to me.

**Comment by dongjoon-hyun** [comment]
Thank you, @viirya . Merged to branch-3.4.

**Pull request closed without merging**
