### PR TITLE
[SPARK-46414][UI] Use prependBaseUri to render javascript imports

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

Use prependBaseUri to render javascript imports

### Why are the changes needed?

Fix a regression when a proxy is used.

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

locally build and verified

### Was this patch authored or co-authored using generative AI tooling?

no

### CODE REVIEW

**Comment by yaooqinn** [comment]
cc @HyukjinKwon

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
cc @rednaxelafx too

**Review by rednaxelafx — COMMENTED** [review]
Thanks for the fix! Were there any tests that used to test the base URI prefix before this change? If there are any, can we apply the same kind of test for the new change?

**Comment by yaooqinn** [comment]
I did find related test for this, so I manually tested with proxied by standalone master. These links for the thread and heap dumps are valid, which means it worked as expected.
image

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
