### PR TITLE
[SPARK-12263][Docs]: IllegalStateException: Memory can't be 0 for SPARK_WORKER_MEMORY without unit

### PR DESCRIPTION
**Pull request by nssalian**
Updated the Worker Unit IllegalStateException message to indicate no values less than 1MB instead of 0 to help solve this.
Requesting review

### CODE REVIEW

**Comment by srowen** [comment]
LGTM

**Comment by srowen** [comment]
@nssalian you need to fix the line that's too long now

**Comment by nssalian** [comment]
Thanks for the review @srowen. I didn't have access to my machine since I was traveling. 
Modified the line to bring it to 97 characters.

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
