### PR TITLE
[SPARK-30486][BUILD] Bump lz4-java version to 1.7.1

### PR DESCRIPTION
**Pull request by maropu**
### What changes were proposed in this pull request?

This pr intends to upgrade lz4-java from 1.7.0 to 1.7.1.

### Why are the changes needed?

This release includes a bug fix for older macOS. You can see the link below for the changes;
https://github.com/lz4/lz4-java/blob/master/CHANGES.md#171

### How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by maropu** [comment]
cc: @HyukjinKwon @dongjoon-hyun @srowen

**Comment by maropu** [comment]
FYI: https://github.com/lz4/lz4-java/issues/156

**Comment by dongjoon-hyun** [comment]
Yes, I've been waiting for this, @maropu .
However, it seems that we need to wait for one or two days because `Google Maven Central` is not mirroring it yet.
```
[ERROR] Failed to execute goal on project spark-core_2.12: Could not resolve dependencies for project org.apache.spark:spark-core_2.12:jar:3.0.0-SNAPSHOT: Could not find artifact org.lz4:lz4-java:jar:1.7.1 in google-maven-central (https://maven-central.storage-download.googleapis.com/repos/central/data/) -> [Help 1]
```

**Comment by dongjoon-hyun** [comment]
The Jenkins will pass because Google Maven Central is only used in GitHub Action.
So, we can merge this when GitHub Action passes.

**Comment by kiszk** [comment]
This is not available yet at https://mvnrepository.com/artifact/org.lz4/lz4-java/1.7.1, too.

**Comment by kiszk** [comment]
retest this please

**Comment by kiszk** [comment]
It came to https://mvnrepository.com/artifact/org.lz4/lz4-java/1.7.1, but did not come to https://maven-central.storage-download.googleapis.com/repos/central/data/ yet.

**Comment by dongjoon-hyun** [comment]
Hi, @maropu and @kiszk . I found a solution for this. Could you review this?
- https://github.com/apache/spark/pull/27281

**Comment by maropu** [comment]
Rebased to master.

**Comment by dongjoon-hyun** [comment]
Thank you, @maropu !

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. (Pending GitHub Action)

**Review by HyukjinKwon — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @maropu, @kiszk , and @HyukjinKwon .
This PR already passed Jenkins and now GitHub Action also passed.
Merged to master.

**Comment by maropu** [comment]
Thanks, @dongjoon-hyun !

**Pull request closed without merging**
