### PR TITLE
[SPARK-45108][SQL] Improve the InjectRuntimeFilter for check probably shuffle

### PR DESCRIPTION
**Pull request by beliefer**
### What changes were proposed in this pull request?
`InjectRuntimeFilter` needs to check probably shuffle. But the current code may lead to duplicate call of `isProbablyShuffleJoin` if we need the right side of `Join` node as the application side.

### Why are the changes needed?
To avoid the duplicate call of `isProbablyShuffleJoin`.

### Does this PR introduce _any_ user-facing change?
'No'.
Just update the inner implementation.

### How was this patch tested?
Exists test cases.

### Was this patch authored or co-authored using generative AI tooling?
'No'.

### CODE REVIEW

**Comment by beliefer** [comment]
In fact, the GA passed.
https://github.com/beliefer/spark/actions/runs/6129346872

**Comment by beliefer** [comment]
ping @viirya @wangyum cc @somani

**Comment by beliefer** [comment]
ping @cloud-fan @viirya cc @somani

**Review by cloud-fan — APPROVED** [review]

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Comment by beliefer** [comment]
@cloud-fan Thank you!

**Pull request closed without merging**
