### PR TITLE
[SPARK-22323] Design doc for pandas_udf

### PR DESCRIPTION
**Pull request by icexelloss**
I open this PR so we can have a place to discuss the design. 

We don't necessary need to merge a md file for the doc -  this be can embeded python documentation.

### CODE REVIEW

**Comment by icexelloss** [comment]
cc @cloud-fan @ueshin @HyukjinKwon @gatorsmile @viirya 

To continue the discussion on #19505

**Comment by gatorsmile** [comment]
@jiangxb1987 will reorg the existing Spark SQL doc. We can think about how to put this into the new version of Spark SQL doc.

**Comment by srowen** [comment]
I don't think we would merge this to Spark docs right? I don't think this is an efficient way to discuss a design document if that's the intent

**Comment by gatorsmile** [comment]
This is not ready yet. Eventually, we need a document for vectorized Python UDF

**Comment by icexelloss** [comment]
Sorry for the late reply.

@srowen At this point I would like to have feedback on the design doc so we can move forward with implementation or a formal Spark docs if people prefer. What do you think is a best way to discuss design document?

**Comment by icexelloss** [comment]
Do people prefer google doc? I can do that too.

**Comment by cloud-fan** [comment]
I feel google doc is easier to review and discuss

**Comment by icexelloss** [comment]
Ok. I will put in a google doc and ping your guys. Thanks!

**Comment by icexelloss** [comment]
Thanks all for the advice. I've put this in a google doc.

https://docs.google.com/document/d/1KlLaa-xJ3oz28xlEJqXyCAHU3dwFYkFs_ixcUXrJNTc/edit?usp=sharing

**Comment by icexelloss** [comment]
Close this in favor of the google doc.

**Pull request closed without merging**
