### PR TITLE
[SPARK-44073][SQL][PYTHON][CONNECT] Add date time functions to Scala, Python and Connect - part 2

### PR DESCRIPTION
**Pull request by beliefer**
### What changes were proposed in this pull request?
This PR want add some date time functions to Scala, Python and Connect API. These functions show below.

- weekday
- convert_timezone
- now
- timestamp_micros
- timestamp_millis

The origin plan also contains function `extract`. You can see this PR exclude it, since we can't get the data type for unresolved expressions. Please refer
https://github.com/apache/spark/blob/b97ce8b9a99c570fc57dec967e7e9db3d115c1db/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/datetimeExpressions.scala#L2835 and https://github.com/apache/spark/blob/b97ce8b9a99c570fc57dec967e7e9db3d115c1db/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/datetimeExpressions.scala#L2922

### Why are the changes needed?
Add date time functions to Scala, Python and Connect API.

### Does this PR introduce _any_ user-facing change?
'No'.
New feature.

### How was this patch tested?
New test cases.

### CODE REVIEW

**Comment by zhengruifeng** [comment]
as to `extract`, can it be supported by `call_udf`?

**Comment by beliefer** [comment]
ping @zhengruifeng cc @HyukjinKwon @panbingkun 

In fact, the GA passed.
https://github.com/beliefer/spark/actions/runs/5308603759

**Comment by zhengruifeng** [comment]
> 

PySpark tests are all skipped?

**Comment by zhengruifeng** [comment]
> ping @zhengruifeng cc @HyukjinKwon @panbingkun
> 
> In fact, the GA passed. https://github.com/beliefer/spark/actions/runs/5308603759


PySpark tests are all skipped?

**Comment by beliefer** [comment]
@zhengruifeng I rebased.

**Review by zhengruifeng — APPROVED** [review]

**Comment by zhengruifeng** [comment]
@beliefer thank you so much!

merged to master

**Comment by beliefer** [comment]
@zhengruifeng Thank you very much!

**Pull request closed without merging**
