### PR TITLE
[SPARK-44865][SS] Make StreamingRelationV2 support metadata column

### PR DESCRIPTION
**Pull request by zeruibao**
### What changes were proposed in this pull request?
Make StreamingRelationV2 support metadata column

### Why are the changes needed?
It is useful for CDC connector since CDC streaming needs some metadata columns.

### How was this patch tested?
Unit test

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Mind filing a JIRA please? See also https://spark.apache.org/contributing.html

**Comment by zeruibao** [comment]
@HyukjinKwon  sure! https://issues.apache.org/jira/browse/SPARK-44865

**Review by HeartSaVioR — APPROVED** [review]
+1 from me but let me get second eye of review from @cloud-fan if there's a chance.

@cloud-fan Could you please help taking a look? It seems OK but want to double-check with SQL experts.

**Comment by HeartSaVioR** [comment]
@zeruibao 
Btw, the CI failure doesn't look to be from this change, but for completeness' sake, could you please retrigger failed runs of CI? You can either push an empty commit to retrigger entire build, or manually trigger rebuild in Github Action UI and let us know if all modules pass in your fork. Thanks!

**Review by cloud-fan — APPROVED** [review]

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Pull request closed without merging**
