### PR TITLE
[SPARK-34798][SQL][TESTS] Fix incorrect join condition

### PR DESCRIPTION
**Pull request by opensky142857**
### What changes were proposed in this pull request?

join condition 'a.attr == 'c.attr check the reference of  these 2 objects which will always returns false. we need to use === instead

### Why are the changes needed?

Although this join condition always false doesn't break the test but it is not what we expected. We should fix it to avoid future confusing

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

UT

### CODE REVIEW

**Comment by wangyum** [comment]
ok to test.

**Review by wangyum — APPROVED** [review]

**Comment by wangyum** [comment]
ok to test.

**Comment by wangyum** [comment]
Jenkins, retest this please.

**Comment by wangyum** [comment]
cc @cloud-fan

**Review by cloud-fan — APPROVED** [review]
good catch!

**Comment by wangyum** [comment]
Merged to master, branch-3.1 and branch-3.0.

**Pull request closed without merging**
