### PR TITLE
[SPARK-34797][ML] Refactor Logistic Aggregator - support virtual centering

### PR DESCRIPTION
**Pull request by zhengruifeng**
### What changes were proposed in this pull request?

1, add `BinaryLogisticBlockAggregator` and `MultinomialLogisticBlockAggregator` and related testsuites;
2, impl `virtual centering` in standardization;
3, remove old `LogisticAggregator`

### Why are the changes needed?
previous [pr](https://github.com/apache/spark/pull/31693) and related works is too large, we need to split it into 3 prs:
1, this one, impl new agg supporting `virtual centering`, remove old `LogisticAggregator`;
2, adopt new blor-agg in lor,  add new test suite for small var features;
3, adopt new mlor-agg in lor,  add new test suite for small var features, remove `BlockLogisticAggregator`;

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
added testsuites

### CODE REVIEW

**Comment by zhengruifeng** [comment]
I also test using the two new agg in `LogisticRegressionSuite`, and all test passed except "multinomial logistic regression with intercept with L1 regularization":

existing [`interceptsRStd`](https://github.com/apache/spark/blob/master/mllib/src/test/scala/org/apache/spark/ml/classification/LogisticRegressionSuite.scala#L1816) is NOT equals to the [R coef](https://github.com/apache/spark/blob/master/mllib/src/test/scala/org/apache/spark/ml/classification/LogisticRegressionSuite.scala#L1753-L1779)

To pass this case, I need to change `interceptsRStd` to the output of GLMNET. But I think this should be a good change.

**Comment by zhengruifeng** [comment]
friendly ping @srowen @WeichenXu123

**Review by srowen — APPROVED** [review]
LGTM if this is mostly a refactoring. Merge when ready.

**Comment by srowen** [comment]
@zhengruifeng do you want me to merge so you can proceed?

**Review by WeichenXu123 — APPROVED** [review]

**Comment by zhengruifeng** [comment]
@srowen @WeichenXu123 Thanks for reviewing!
The only question is that should we backport it to 3.1? if it is not a correctness issue.

**Comment by WeichenXu123** [comment]
> @srowen @WeichenXu123 Thanks for reviewing!
> The only question is that should we backport it to 3.1? if it is not a correctness issue.

Since this is big change including refactor, for reducing risk, I propose to do not backport.

**Comment by srowen** [comment]
I think Xiangrui favored not backporting the change this supports as well, so I'd just go for master

**Comment by srowen** [comment]
Jenkins test this please

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
