### PR TITLE
[SPARK-43006][PYSPARK] Fix typo in StorageLevel __eq__()

### PR DESCRIPTION
**Pull request by thyecust**
### What changes were proposed in this pull request?

fix `self.deserialized == self.deserialized` with `self.deserialized == other.deserialized`

### Why are the changes needed?

The original expression is always True, which is likely to be a typo.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

No test added. Use GitHub Actions.

### CODE REVIEW

**Comment by srowen** [comment]
Can you make a little JIRA for this and https://github.com/apache/spark/pull/40620 ? they're minor bugs

**Comment by srowen** [comment]
Merged to master/3.4

**Comment by ueshin** [comment]
@thyecust Good catch! Thanks for fixing it!

**Comment by ueshin** [comment]
I submitted a PR #40650 to fix the failed tests.

**Pull request closed without merging**
