### PR TITLE
[SPARK-29402][PYTHON][TESTS] Added tests for grouped map pandas_udf with window

### PR DESCRIPTION
**Pull request by BryanCutler**
### What changes were proposed in this pull request?

Added tests for grouped map pandas_udf using a window.

### Why are the changes needed?

Current tests for grouped map do not use a window and this had previously caused an error due the window range being a struct column, which was not yet supported.

### Does this PR introduce any user-facing change?

No

### How was this patch tested?

New tests added.

### CODE REVIEW

**Comment by BryanCutler** [comment]
cc @HyukjinKwon @viirya @icexelloss

**Comment by BryanCutler** [comment]
This only adds some basic tests, so merging to master

**Review by HyukjinKwon — COMMENTED** [review]
LGTM. sorry for my late response.

**Comment by viirya** [comment]
lgtm too.

**Pull request closed without merging**
