### PR TITLE
[SPARK-31041][BUILD] Show Maven errors from within make-distribution.sh

### PR DESCRIPTION
**Pull request by nchammas**
### What changes were proposed in this pull request?

This PR makes `dev/make-distribution.sh` a bit easier to use by not hiding errors thrown by Maven.

As a supporting change, this PR also suppresses progress bar output from curl and wget that may be output from within `build/mvn`.

### Why are the changes needed?

It's surprising for command-line options to be position-dependent. The errors that get thrown when you pass the correct option (like `--pip`) but in the wrong order are confusing.

### Does this PR introduce any user-facing change?

No.

### How was this patch tested?

I ran a few invocations of `make-distribution.sh` to confirm that, when passed incorrect options, I can actually see the errors thrown directly by Maven.

### CODE REVIEW

**Comment by ScrapCodes** [comment]
@nchammas, the patch looks good to me. We can make one more improvement though.

The command `dev/make-distribution.sh`'s usage help, makes it very clear that maven cli option should be at the end.

Since the error output if the user makes a mistake with the position of the `MAVEN_CLI_OPTIONS` is very misleading. So this patch is helpful !

The improvement, I would recommend is, is the user gives a misspelled CLI option, the error output is still misleading, it might as well be good to fix the error output. e.g.

`./dev/make-distribution.sh --pip -r --tgz`

Produces the error:
`+ VERSION=' -X,--debug                             Produce execution debug output'`
Which is not at all helpful.

**Comment by nchammas** [comment]
Yes, that is the same error you get today if you pass the correct Maven options but in the wrong order, which I mentioned [in the Jira](https://issues.apache.org/jira/browse/SPARK-31041).

Hmm, so we want some way to validate the Maven options, or perhaps make it clearer to the user that the reason the command is failing is because they provided an incorrect option. (And perhaps that would eliminate the need to make the options position-independent in the first place.)

I think we can solve that by not redirecting Maven's error output to `/dev/null`.

**Comment by nchammas** [comment]
OK, new debug statements:

```diff
diff --git a/dev/make-distribution.sh b/dev/make-distribution.sh
index 3c562b0f91..cb68610836 100755
--- a/dev/make-distribution.sh
+++ b/dev/make-distribution.sh
@@ -90,6 +90,15 @@ while (( "$#" )); do
   shift
 done
 
+echo "--tgz $MAKE_TGZ"
+echo "--pip $MAKE_PIP"
+echo "--r $MAKE_R"
+echo "--mvn $MVN"
+echo "--name $NAME"
+echo "mvn-opts: ${MAVEN_CLI_OPTS[@]}"
+
+# exit 1
+
 if [ -z "$JAVA_HOME" ]; then
   # Fall back on JAVA_HOME from rpm, if found
   if [ $(command -v  rpm) ]; then
@@ -148,6 +157,13 @@ SPARK_HIVE=$("$MVN" help:evaluate -Dexpression=project.activeProfiles -pl sql/hi
     # because we use "set -o pipefail"
     echo -n)
 
+echo "VERSION: $VERSION"
+echo "SCALA_VERSION: $SCALA_VERSION"
+echo "SPARK_HADOOP_VERSION: $SPARK_HADOOP_VERSION"
+echo "SPARK_HIVE: $SPARK_HIVE"
+
+exit 1
+
 if [ "$NAME" == "none" ]; then
   NAME=$SPARK_HADOOP_VERSION
 fi
```

And new tests:

```sh
$ ./dev/make-distribution.sh --pip -r --tgz

Using `mvn` from path: .../spark/build/apache-maven-3.6.3/bin/mvn
Unable to parse command line options: Unrecognized option: -r
+ VERSION=' -X,--debug                             Produce execution debug output'
```

```sh
$ ./dev/make-distribution.sh \
    --name custom-spark \
    --pip --r --tgz \
    -Psparkr \
    -Phadoop-2.7 \
    -Phive -Phive-thriftserver \
    -Pmesos -Pyarn -Pkubernetes

VERSION: 3.1.0-SNAPSHOT
SCALA_VERSION: 2.12
SPARK_HADOOP_VERSION: 2.7.4
SPARK_HIVE: 1
```

**Comment by nchammas** [comment]
At this point I suppose we can revert the change to accept Maven options at any position, and just have the bit that shows Maven's error output so the user can figure out what's going on more easily.

What do you think?

**Comment by ScrapCodes** [comment]
> At this point I suppose we can revert the change to accept Maven options at any position, and just have the bit that shows Maven's error output so the user can figure out what's going on more easily.
> 
> What do you think?

Although, I am unsure, why the error output of those maven commands was turned off in the first place. Only reason could be limiting the amount of output that is generated. 
This should work better in practice.

**Review by dongjoon-hyun — COMMENTED** [review]
This will print out all the download information additionally. In Jenkins environment, the progress bar is not one line.
```
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=384m; support was removed in 8.0
exec: curl --progress-bar -L https://downloads.lightbend.com/scala/2.12.10/scala-2.12.10.tgz
############################################################################################################ 100.0%
exec: curl --progress-bar -L https://www.apache.org/dyn/closer.lua?action=download&filename=/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
############################################################################################################ 100.0%
Using `mvn` from path: /Users/dongjoon/PRS/SPARK-PR-27800/build/apache-maven-3.6.3/bin/mvn
```

The given example is only aiming to add the following single error message, isn't it?
```
Unable to parse command line options: Unrecognized option: -r
```

**Comment by nchammas** [comment]
Yes, the aim is to pass along to the user any errors thrown by Maven, because right now they are all suppressed. This makes it very confusing to understand why, for example, `./dev/make-distribution.sh -Phadoop-cloud --pip` doesn't work.

I don't follow the issue with the download information that you are describing. Are you suggesting we should suppress the download progress bars from `./build/mvn`? If so, I'd be happy to do that as part of this PR.

**Comment by dongjoon-hyun** [comment]
For me, it's too annoying and the benefit is big. While it gave us big regression, I'm not sure how many time this PR gives us the benefit.

**Comment by dongjoon-hyun** [comment]
Although I'm a little negative, I'll not be against if someone else are merging this.

**Comment by srowen** [comment]
I'm mildly in favor of it if it helps debugging. The extra log output is a little extra noise in Jenkins, sure.

**Comment by dongjoon-hyun** [comment]
Got it. Please feel free to merge this, @srowen ~

**Comment by nchammas** [comment]
I believe we can explicitly suppress the download progress bars and not have that noise. If that's all the concern is about, why don't I address that as part of this PR? Or, if you prefer, I can make a follow-up PR to do that.

If I'm understanding the concern correctly, we just need to tweak the options here so that the downloads are always quiet: https://github.com/apache/spark/blob/d21aab403a0a32e8b705b38874c0b335e703bd5d/build/mvn#L38-L47

(And for the record, it seems that the current behavior is already to suppress download progress output on Jenkins. It's _outside_ of AMPLab Jenkins that progress bars are shown.)

**Comment by srowen** [comment]
If you can suppress it here, go for it.

**Comment by nchammas** [comment]
Ok, curl and wget will now never show progress bars, but they will still show errors they encounter:

```
$ ./build/mvn
exec: curl --silent --show-error -L https://downloads.lightbend.com/zinc/0.3.15
/zinc-0.3.15.tgz
exec: curl --silent --show-error -L https://downloads.lightbend.com/scala/2.12.
10/scala-2.12.10.tgz
exec: curl --silent --show-error -L https://www.apache.org/dyn/closer.lua?action=download&filename=/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
Using `mvn` from path: .../spark/build/apache-maven-3.6.3/bin/mvn
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
...
```

**Review by srowen — APPROVED** [review]

**Comment by srowen** [comment]
Merged to master

**Comment by dongjoon-hyun** [comment]
Thank you, @nchammas and @srowen .

**Pull request closed without merging**
