### PR TITLE
[SPARK-4194] [core] Make SparkContext initialization exception-safe. 

### PR DESCRIPTION
**Pull request by vanzin**
SparkContext has a very long constructor, where multiple things are
initialized, multiple threads are spawned, and multiple opportunities
for exceptions to be thrown exist. If one of these happens at an
innoportune time, lots of garbage tends to stick around.

This patch re-organizes SparkContext so that its internal state is
initialized in a big "try" block. The fields keeping state are now
completely private to SparkContext, and are "vars", because Scala
doesn't allow you to initialize a val later. The existing API interface
is kept by turning vals into defs (which works because Scala guarantees
the same binary interface for those).

On top of that, a few things in other areas were changed to avoid more
things leaking:
- Executor was changed to explicitly wait for the heartbeat thread to
  stop. LocalBackend was changed to wait for the "StopExecutor"
  message to be received, since otherwise there could be a race
  between that message arriving and the actor system being shut down.
- ConnectionManager could possibly hang during shutdown, because an
  interrupt at the wrong moment could cause the selector thread to
  still call select and then wait forever. So also wake up the
  selector so that this situation is avoided.

### CODE REVIEW

**Comment by vanzin** [comment]
Note the PR contains the commits from #5311. I hope once that is pushed that github will figure things out. (If not I'll rebase manually.) So if you want to skip those changes, just look at the last commit in the list.

With both of these PRs, I was able to run the core/ unit tests and verify that:
- no executor allocator threads were left behind
- no driver heartbeater threads were left behing
- no "AkkaAskTimeout" exceptions show up in the unit test logs

I tried to run MiMA checks locally and they look ok, but let's see what jenkins says.

**Comment by vanzin** [comment]
Oops, borked merge, fixing...

**Comment by vanzin** [comment]
Jenkins, retest this please.

**Comment by vanzin** [comment]
Ping?

**Comment by srowen** [comment]
I tend to trust your hand on this. This is a big change and it's hard to match up the existing logic with new logic in the diff, though it looks like that was the intent and effect from spot-checking some elements. That the tests have passed several times is a good sign. The reorganization is significantly positive since the fields, and their initialization, are clearly grouped now. 

One minor style thing, why the `_member` naming syntax, where it's not otherwise used in Spark? just to make it crystal clear here what's a member?

I think the additional changes look reasonable, like using a Java `Executor` in the, well, `Executor`.

I favor this though weakly on the grounds that I'm mostly relying on tests for correctness. The intent is sound. @rxin @pwendell do you have any thoughts on this one?

**Comment by vanzin** [comment]
> One minor style thing, why the _member naming syntax

That's actually used in lots of places in Spark. It's used when some variable / field name conflicts with a `def`, which is the case in this change.

**Comment by srowen** [comment]
OK right, and that's true of all of them here.

**Comment by pwendell** [comment]
ping @JoshRosen - I think he's proposed this exact change to me in the past.

**Comment by JoshRosen** [comment]
See the description of PR #3121 for my previous discussion of this.  If we want to avoid introducing `vars` in SparkContext, one alternative would be to move the creation of these components outside of the SparkContext constructor and into a method in the companion object, putting the `try / catch` blocks there.  This lets us isolate the mutability into a single method, so things are mutable while we're constructing SparkContext but are immutable once the object has been fully constructed.  I'm not sure whether this approach would be easier or harder to understand than the mutable vars + getters used here.

**Comment by vanzin** [comment]
That aproach would be a lot more complicated. The first reason why it would be complicated is that you'd need an uber-constructor in SparkContext that takes all the initialized internal values. Unless there's some fancy Scala feature I'm not aware of, that in itself is scary as hell, and would mean the other constructors would be similarly ugly in that they'd have to call the companion object.

It would also cause (even more) duplication of the declaration of these things, since they'd have to be declared in the companion object's method too.

Finally, it would complicate `stop()`, because it would have to either be copy & pasted into the companion object so that it cleans up after an exception, or you'd need a stop() method in the companion object that takes all arguments as parameters, so that the SparkContext class can call it.

So while I would love to simplify the code in SparkContext, the alternative suggestion, as far as I can see, does nothing towards that.

And that's why I chose private vars. It's not optimal, and I really wish Scala would allow me to initialize a val after its declaration, like Java does. But it's the easiest approach, and it doesn't expose any mutable SparkContext state that wasn't already exposes before.

**Comment by pwendell** [comment]
I also feel that the current approach makes more sense than Josh's alternative. Changes to SparkContext get a lot of scrutiny during code review, so clear documentation, IMO is sufficient to ensure this is followed correctly (famous last words). I didn't have time to dive into this to make sure there are no correctness issues, but the broad approach looks good to me... I think it's worth fixing this up.

**Comment by srowen** [comment]
Seems like there's support for this change, though needs a rebase @vanzin . Any objections to proceeding after that?

**Pull request closed without merging**
