### PR TITLE
[SPARK-40672][CONNECT][INFRA] Run Scala side tests in GitHub Actions

### PR DESCRIPTION
**Pull request by HyukjinKwon**
### What changes were proposed in this pull request?

This PR proposes to run Spark Connect tests in Scala side in GitHub Actions.

### Why are the changes needed?

To run the tests.

### Does this PR introduce _any_ user-facing change?

No, dev-only.

### How was this patch tested?
CI in this PR should test it out

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @Yikun FYI

**Review by Yikun — APPROVED** [review]
LGTM if CI passed. Because the connect module already added: https://github.com/apache/spark/blob/master/dev/sparktestsupport/modules.py#L274-L274


https://github.com/HyukjinKwon/spark/actions/runs/3194338514/jobs/5213817386#step:9:8

and new module test works well, other failed seems unrelated flaky failed.

**Review by zhengruifeng — APPROVED** [review]
LGTM pending CI

**Comment by HyukjinKwon** [comment]
Merged to master.

(since connect tests passed).

**Pull request closed without merging**
