### PR TITLE
[SPARK-25578][BUILD] Update to Scala 2.12.7

### PR DESCRIPTION
**Pull request by srowen**
## What changes were proposed in this pull request?

Update to Scala 2.12.7. See https://issues.apache.org/jira/browse/SPARK-25578 for why.

## How was this patch tested?

Existing tests.

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM (pending Jenkins).

**Comment by srowen** [comment]
Merged to master/2.4

**Comment by wangyum** [comment]
2.12.8 is out. Do we need to upgrade to 2.12.8?
2.12.8 fixes two regressions that appeared in 2.12.7:
```
Don't reject views with result types which are TypeVars (#7295)
Don't emit static forwarders (which simplify the use of methods in top-level objects from Java) for bridge methods (#7469)
```
More details: https://github.com/scala/scala/releases/tag/v2.12.8

**Comment by srowen** [comment]
@wangyum sounds good. I opened https://github.com/apache/spark/pull/23218

**Pull request closed without merging**
