### PR TITLE
[SPARK-21262] Stop sending 'stream request' when shuffle blocks.

### PR DESCRIPTION
**Pull request by jinxing64**
## What changes were proposed in this pull request?

In current code, client will fetch the remote huge blocks to disk. It is implemented by sending 'stream request', which needs server side support(change). Thus it will break old shuffle service.
Instead of fetching the stream to disk, this pr proposes to convert chunk to `FileSegmentManagedBuffer`.

### CODE REVIEW

**Comment by jinxing64** [comment]
cc @zsxwing @cloud-fan @jiangxb1987

**Comment by cloud-fan** [comment]
does this mean we have to fetch big chunks in memory and then writing to disk?

**Comment by jinxing64** [comment]
In current change, it i fetching big chunk in memory and then writing to disk and then release the memory. I made this change for below reasons:
1. The client shouldn't break old shuffle service, thus cannot send "stream request" to server. We have to send `ChunkFetchRequest` and handle the `ChunkFetchSuccess` for response.
2. It's hard to make 'ChunkFetchSuccess' to be a stream and read it to disk. We need to implement another `TransportFrameDecoder`, which I think is too much cost.

**Comment by jinxing64** [comment]
Very gentle ping @zsxwing , How do you think about this idea?

**Comment by zsxwing** [comment]
In a second thought, I think we don't need this PR. We can disable `spark.reducer.maxReqSizeShuffleToMem` by default. Let's just document this configuration will break old shuffle service and the user should enable it when it's safe (e.g., no old clients will run).

**Comment by jinxing64** [comment]
Sure, I will update the document soon.

**Pull request closed without merging**
