### PR TITLE
[SPARK-31225][SQL][2.4] Override sql method of OuterReference

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

Per https://github.com/apache/spark/pull/32179#issuecomment-822954063 's request to backport SPARK-31225 to branch 2.4

### CODE REVIEW

**Comment by yaooqinn** [comment]
cc @cloud-fan @viirya thanks

**Comment by HyukjinKwon** [comment]
Once Jenkins build passes, it should be good to go.

**Review by cloud-fan — APPROVED** [review]
LGTM if tests pass

**Comment by viirya** [comment]
Can you fix the error message?

**Review by viirya — APPROVED** [review]
looks good. we just need to update the error message in the failed test.

**Comment by viirya** [comment]
Seems there is still other error?

**Comment by cloud-fan** [comment]
thanks, merging to 2.4!

**Comment by viirya** [comment]
Thanks! Merging to 2.4.

**Pull request closed without merging**
