### PR TITLE
[SPARK-49071][SQL] Remove ArraySortLike trait

### PR DESCRIPTION
**Pull request by ulysses-you**
### What changes were proposed in this pull request?

This pr cleanup the legacy code of `SortArray` to remove `ArraySortLike` and inline `nullOrder`. The `ArraySort` has been rewritten since https://github.com/apache/spark/pull/25728, so the `SortArray` is the only implementation of `ArraySortLike`.

### Why are the changes needed?

cleanup the code

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

Pass CI

### Was this patch authored or co-authored using generative AI tooling?

no

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
In the PR title, instead of `Cleanup SortArray`, do you want to say `Remove ArraySortLike trait`, @ulysses-you ?

**Comment by ulysses-you** [comment]
thank you @dongjoon-hyun, changed, also cc @yaooqinn

**Review by yaooqinn — APPROVED** [review]

**Review by dongjoon-hyun — COMMENTED** [review]
Could you make the CI happy by fixing the style issue, @ulysses-you ?

**Review by HyukjinKwon — APPROVED** [review]

**Comment by ulysses-you** [comment]
thank you @dongjoon-hyun @yaooqinn @HyukjinKwon , merging to master

**Pull request closed without merging**
