### PR TITLE
[SPARK-12444][SQL] A lightweight Scala DSL for schema construction

### PR DESCRIPTION
**Pull request by liancheng**
This PR introduces a lightweight Scala DSL for constructing complex Spark SQL schema.

Two DSL methods `!` and `?` are added to `DataType` to help indicating nullability of struct field, array element type, and map value type.
- `!` means non-nullable (or required), while
- `?` means nullable (or optional)
  
  An implicit conversion from any `DataType` `t` to `t -> true` is added, so that the `?` call can be optional in most cases.  This behavior is consistent to existing constructors of complex types, where `nullable`, `containsNull`, and `valueContainsNull` are all `true` by default.

With the help of these two methods, and three more constructors, we can now construct schema like this:

``` scala
StructType(
  "f0" -> IntegerType.!,
  "f1" -> ArrayType(IntegerType).!,
  "f2" -> MapType(
    IntegerType,
    StructType(
      "f20" -> DoubleType.!,
      "f21" -> StringType
    ).!
  )
)
```

which is conciser and arguably more readable than equivalent existing approaches:

``` scala
StructType(Seq(
  StructField("f0", IntegerType, nullable = false),
  StructField("f1", ArrayType(IntegerType), nullable = false),
  StructField("f2", MapType(
    IntegerType,
    StructType(Seq(
      StructField("f20", DoubleType, nullable = false),
      StructField("f21", StringType)
    )),
    valueContainsNull = false
  ))
))

new StructType()
  .add("f0", IntegerType, nullable = false)
  .add("f1", ArrayType(IntegerType), nullable = false)
  .add("f2", MapType(
    IntegerType,
    new StructType()
      .add("f20", DoubleType, nullable = false)
      .add("f21", StringType),
    valueContainsNull = false
  ))
```

### CODE REVIEW

**Comment by liancheng** [comment]
test this please

**Comment by pierre-borckmans** [comment]
Nice small DSL. Small comment, with the regular constructor, the `nullable` field is optional, defaulting to  `true`. You might want to make this DSL follow the same convention to make it even more concise.

The `?` usage would be optional.

**Comment by liancheng** [comment]
retest this please

**Comment by liancheng** [comment]
@pierre-borckmans Yeah, I also realized this. However, to remove this minor inconsistency, I'm afraid I'll have to add implicit conversions, which is something we are trying to avoid whenever possible.

**Comment by liancheng** [comment]
@pierre-borckmans Decided to add the implicit conversion at last. API consistency seems to be more important :) The implicit conversion is added in `object DataType` so that users don't need to pay the `import` tax.

**Comment by markhamstra** [comment]
I can't say that I am a fan of the use of `!` and `?`.  Your proposed DSL is more concise, but it is not clear that it improves readability.  I'd rather see these with proper names since clarity is more important than saving a few keystrokes for something that is done as infrequently as defining a schema.

Incidentally, I am also not a fan of the lack of description in the JIRA.  The JIRA should tell the reader *why* a change is needed or desired, while the PR description should explain *what* is being done.  A JIRA that just says "I made a PR" is not really adequate.

**Comment by rxin** [comment]
I'm with @markhamstra here. It is unclear what ! or ? mean. They are unintuitive, and are not general symbols for schema construction or nullability.

**Comment by cloud-fan** [comment]
hi @markhamstra , defining a schema is very frequent when writing test, do you feel it's a good idea to put this functionality only in test scope?

**Comment by rxin** [comment]
Note that we also have the "ColumnName" implicit. Using that you can already define a struct field using: `'fieldName.int`.

**Comment by cloud-fan** [comment]
@rxin you are right, an example is [`'b.struct('a.int, 'b.long)`](https://github.com/apache/spark/blob/master/sql/catalyst/src/test/scala/org/apache/spark/sql/catalyst/encoders/EncoderResolutionSuite.scala#L67)

**Comment by markhamstra** [comment]
@cloud-fan You're kind of hinting at my point: To me, this DSL seems to make life easier for Spark developers, not Spark users.  In that kind of trade-off, we should always opt for making things easier for users.

Putting this functionality in test scope or otherwise hiding it from the public API isn't as troubling, but having secret or unintuitive shortcuts that only Spark developers use will make getting up to speed more difficult for people looking to contribute to Spark.

**Comment by liancheng** [comment]
@markhamstra @rxin Thanks for the comments. I'm not surprised that you find `!` and `?` not super clear.

@markhamstra You're right, my motivation was to make Spark developers' life easier, especially when writing test cases involving complex nested schemata.

Thanks again for the review and all the comments. I'm closing this PR then.

**Pull request closed without merging**
