### PR TITLE
[SPARK-39110][WEBUI] Add metrics properties to environment tab

### PR DESCRIPTION
**Pull request by AngersZhuuuu**
### What changes were proposed in this pull request?
There are three ways to define metrics properties:

1. Default metrics properties
2. metrics.properties file under $SPARK_CONF_DIR
3. spark.metrics.conf  to include a metrics properties file
4. spark.metrics.conf.xx.xx

Many new users always confused when test with metrics system, i think we can add final metrics properties in the environment tab, to let user can directly know which metrics are working.

截屏2022-05-06 上午11 23 04

截屏2022-05-06 上午11 33 00

### Why are the changes needed?
Make user clear about which metrics properties are working

### Does this PR introduce _any_ user-facing change?
user can see working metrics properties in UI  environment tag

### How was this patch tested?
MT

### CODE REVIEW

**Comment by AngersZhuuuu** [comment]
ping @srowen @cloud-fan

**Comment by srowen** [comment]
It seems reasonable, though I hesitate to clutter the UI further.
How frequently would people need to check this, and how would they currently check these settings? is it that hard that it needs to be in the UI?

**Comment by AngersZhuuuu** [comment]
> It seems reasonable, though I hesitate to clutter the UI further. How frequently would people need to check this, and how would they currently check these settings? is it that hard that it needs to be in the UI?

When users want to develop and configure their own metrics, it may sometimes conflict with the metrics set by the admin. Not displaying these information sometimes makes troubleshooting troublesome. Viewing metrics conf usually occurs when users try to configure metrics conf and when troubleshooting.


Also this table is collapsed as default, won't clutter the UI

**Comment by srowen** [comment]
OK seems alright, just rerun the tests maybe

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
