### PR TITLE
[SPARK-34643][R][DOCS] Use CRAN URL in canonical form

### PR DESCRIPTION
**Pull request by HyukjinKwon**
### What changes were proposed in this pull request?

This PR fixes the URL links to use CRAN URL in canonical form.
CRAN package submission was failed as below:

```
   Found the following (possibly) invalid URLs:
     URL: https://cran.r-project.org/web/packages/e1071/index.html
       From: man/spark.naiveBayes.Rd
       Status: 200
       Message: OK
       CRAN URL not in canonical form
     URL: https://cran.r-project.org/web/packages/mixtools/index.html
       From: man/spark.gaussianMixture.Rd
       Status: 200
       Message: OK
       CRAN URL not in canonical form
     URL: https://cran.r-project.org/web/packages/survival/index.html
       From: man/spark.survreg.Rd
       Status: 200
       Message: OK
       CRAN URL not in canonical form
     URL: https://cran.r-project.org/web/packages/topicmodels/index.html
       From: man/spark.lda.Rd
       Status: 200
       Message: OK
       CRAN URL not in canonical form
     The canonical URL of the CRAN page for a package is
       https://CRAN.R-project.org/package=pkgname
```

### Why are the changes needed?

To fix CRAN package submission

### Does this PR introduce _any_ user-facing change?

It exposes a canoncal form of URLs to end users.

### How was this patch tested?

I manually clicked each links.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @felixcheung, @shivaram, @dongjoon-hyun FYI

**Comment by shivaram** [comment]
LGTM. Thanks @HyukjinKwon

**Review by dongjoon-hyun — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
I create SPARK-34643 for this because this is a kind of release blocker.

**Comment by dongjoon-hyun** [comment]
Merged to master/3.1 for Apache Spark 3.2.0 and 3.1.2..

**Comment by HyukjinKwon** [comment]
Thanks @shivaram and @dongjoon-hyun!

**Pull request closed without merging**
