### PR TITLE
[SPARK-46188][Doc][3.5] Fix the CSS of Spark doc's generated tables

### PR DESCRIPTION
**Pull request by gengliangwang**
### What changes were proposed in this pull request?

After https://github.com/apache/spark/pull/40269, there is no border in the generated tables of Spark doc(for example,  https://spark.apache.org/docs/latest/sql-ref-ansi-compliance.html) .  This PR is to fix it by restoring part of the table style in https://github.com/apache/spark/pull/40269/files#diff-309b964023ca899c9505205f36d3f4d5b36a6487e5c9b2e242204ee06bbc9ce9L26

This PR also unifies all the styles of tables by removing the `class="table table-striped"` in HTML style tables in markdown docs.

### Why are the changes needed?

Fix a regression in the table CSS of Spark docs

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Manually build docs and verify.
Before changes:
image

After changes:
image

### Was this patch authored or co-authored using generative AI tooling?

Generated-by: ChatGPT 4

### CODE REVIEW

**Comment by gengliangwang** [comment]
This is a backport of https://github.com/apache/spark/pull/44096

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @gengliangwang .

**Comment by gengliangwang** [comment]
@dongjoon-hyun Thanks, I am merging this one.

**Comment by viirya** [comment]
Looks good to me.

**Pull request closed without merging**
