### PR TITLE
[SPARK-19422][ML][WIP] Cache input data in algorithms

### PR DESCRIPTION
**Pull request by zhengruifeng**
## What changes were proposed in this pull request?
cache the input data in `DecisionTreeClassifier`, `GBTClassifier`, `RandomForestClassifier`, `LinearSVC`, `BisectingKMeans`, `GaussianMixture`, `LDA`, `DecisionTreeRegressor`, `GBTRegressor`, `GeneralizedLinearRegression` with IRLS solver, `RandomForestRegressor`

## How was this patch tested?
existing tests

### CODE REVIEW

**Comment by zhengruifeng** [comment]
Jenkins, retest it please

**Comment by hhbyyh** [comment]
Hi @zhengruifeng  https://issues.apache.org/jira/browse/SPARK-18608
There's some ongoing discussion about the issue.

**Comment by zhengruifeng** [comment]
@hhbyyh Thanks a lot for pointing this out!

**Comment by zhengruifeng** [comment]
Jenkins, retest this please

**Comment by zhengruifeng** [comment]
This pr is out of date. I will close it.

**Pull request closed without merging**
