### PR TITLE
[SPARK-6578] Small rewrite to make the logic more clear in MessageWithHeader.transferTo.

### PR DESCRIPTION
**Pull request by rxin**

### CODE REVIEW

**Comment by rxin** [comment]
cc @vanzin from #5234

**Comment by vanzin** [comment]
LGTM pending tests.

**Comment by aarondav** [comment]
LGTM too

**Comment by rxin** [comment]
Merging in 1.3 and master.

**Comment by rxin** [comment]
@vanzin do you mind making a PR for 1.2 branch for this fix?

**Comment by vanzin** [comment]
I'll prepare a PR for 1.2 after I'm done with some stuff around here.

**Pull request closed without merging**
