### PR TITLE
[SPARK-41695][BUILD][3.3] Upgrade netty to 4.1.86.Final

### PR DESCRIPTION
**Pull request by tobiasstadler**
### What changes were proposed in this pull request?
Upgrade netty to 4.1.86.Final;

I cherry-picked
* 56086cb
* 6d3c1c1
* 7154fb9
* ad81ba8
* c95ed82
* c26d99e
* 24adac3
* ff68d0e

### Why are the changes needed?
CVEs

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
CI

### CODE REVIEW

**Comment by bjornjorgensen** [comment]
Change [SPARK-41695][BUILD] Upgrade netty to 4.1.86.Final to [SPARK-41695][BUILD][3.3] Upgrade netty to 4.1.86.Final

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
Does this affect Apache Spark technically, @tobiasstadler ?

**Comment by bjornjorgensen** [comment]
https://github.com/apache/spark/commit/56086cb6c6df241e811be96cdf8bc6bc713b649d

### Does this PR introduce _any_ user-facing change?
Yes, all changes are caused by the change of Netty.
If the user wants to maintain the same behavior as the previous version, the user needs to make the following configuration:

- add `-Dio.netty.allocator.useCacheForAllThreads=true` to enable `useCacheForAllThreads `
- add `-Dio.netty.allocator.maxOrder=11` to keep the chunk size of `PooledByteBufAllocator` to 16m

**Comment by bjornjorgensen** [comment]
And this one https://github.com/apache/spark/pull/38981

**Comment by tobiasstadler** [comment]
Ok, I didn‘t read that. I guess it is better to close the PR.

**Comment by bjornjorgensen** [comment]
@tobiasstadler 
Hi, I have enabled [SNYK](https://snyk.io) and Github Dependabot on my repo. 
This way SNYK [are opening PR's](https://github.com/bjornjorgensen/spark/pulls)  and [Dependabot are opening issues](https://github.com/bjornjorgensen/spark/security/dependabot). 

Right now, most of these PR's are related to Hadoop 2.7 which we will remove in spark 3.5 or 3.6.

I also build spark master and scan code with sonar

[This one is for python and javascript](https://sonarcloud.io/project/issues?resolved=false&id=spark-python) 
  
[and this is for](https://sonarcloud.io/project/issues?resolved=false&id=sparklocal)  java, scala and xml

**Comment by bjornjorgensen** [comment]
Hmm.. you can't see the Dependabot page 

image

**Comment by LuciferYang** [comment]
> @tobiasstadler Hi, I have enabled [SNYK](https://snyk.io) and Github Dependabot on my repo. This way SNYK [are opening PR's](https://github.com/bjornjorgensen/spark/pulls) and [Dependabot are opening issues](https://github.com/bjornjorgensen/spark/security/dependabot).
> 
> Right now, most of these PR's are related to Hadoop 2.7 which we will remove in spark 3.5 or 3.6.
> 
> I also build spark master and scan code with sonar
> 
> [This one is for python and javascript](https://sonarcloud.io/project/issues?resolved=false&id=spark-python)
> 
> [and this is for](https://sonarcloud.io/project/issues?resolved=false&id=sparklocal) java, scala and xml
> 
> CC @panbingkun and @LuciferYang

Is the problem detected by sonar worth fixing @bjornjorgensen ?

**Comment by bjornjorgensen** [comment]
My intentions are to explain to a new contributor how I do it and what tools I use. Sonar is built on best practice rules, the problem is that not everything hits equally well. Here are the ones  that I have found using Sonar that have entered the code base.

https://github.com/apache/spark/pull/36465
https://github.com/apache/spark/pull/36383
https://github.com/apache/spark/pull/36364
https://github.com/apache/spark/pull/35775
https://github.com/apache/spark/pull/35755
https://github.com/apache/spark/pull/35741

**Pull request closed without merging**
