### PR TITLE
[SPARK-41990][SQL][FOLLOWUP] Add comments to explain why `FieldReference.column` is used when `ParseException` happens

### PR DESCRIPTION
**Pull request by huaxingao**
### What changes were proposed in this pull request?

Add comments to explain why `FieldReference.column` is used when `ParseException` happens

### Why are the changes needed?
To address this [comment](https://github.com/apache/spark/pull/39564#discussion_r1070788648)

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Only comments are added. No need to test.

### CODE REVIEW

**Comment by huaxingao** [comment]
cc @cloud-fan @dongjoon-hyun

**Review by dongjoon-hyun — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
+1 from my side. I'll leave this PR to @cloud-fan . Thanks!

**Review by cloud-fan — APPROVED** [review]

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Pull request closed without merging**
