### PR TITLE
[SPARK-43343][SS] FileStreamSource should disable an extra file glob check when creating DataSource

### PR DESCRIPTION
**Pull request by siying**
### What changes were proposed in this pull request?
When FileStreamSource creates a DataSource for a file, disable globbing in the option passed to DataSource.

### Why are the changes needed?
It is to fix following bug.

For example, If a directory contains a following file:
/path/abc[123]
and users would load spark.readStream.format("text").load("/path") as stream input. It throws an exception, saying no matching path /path/abc[123]. Spark thinks abc[123] is a regex that only matches file named abc1, abc2 and abc3.

The bug is due to a second glob pattern match within DataSource, against files already glob matched by FileStreamSource. This match turns real file name into file path match pattern. It is unexpected and we would like to disable it.

### Does this PR introduce _any_ user-facing change?
No, except fixing the unexpected buggy behavior.

### How was this patch tested?
Added unit test scenarios which failed before the fix.

### CODE REVIEW

**Comment by siying** [comment]
@HeartSaVioR will you have time to take a look?

**Review by HeartSaVioR — COMMENTED** [review]
Nice finding! Looks great in overall - just to see whether we can still read a single file containing special character via escaping it. I'd OK with it if it does not work in any way (Hadoop side bug or something) but better to confirm.

**Comment by siying** [comment]
> Nice finding! Looks great in overall - just to see whether we can still read a single file containing special character via escaping it. I'd OK with it if it does not work in any way (Hadoop side bug or something) but better to confirm.
 Thanks for your review and suggestion. I gave it a try ant it looks like "\[" works. I updated the PR.

**Comment by siying** [comment]
Not sure why one test ran for 4+ hours and it still didn't succeed or fail.

**Comment by HeartSaVioR** [comment]
It seems like the actual test run is only 2 hours ago - check out the full log via `view raw logs`.

**Review by HeartSaVioR — APPROVED** [review]
+1 pending CI.

**Comment by siying** [comment]
Failed tests don't seem to be related at all:
```
2023-05-08T23:33:54.8173143Z [0m[[0m[31merror[0m] [0m[0mFailed tests:[0m
2023-05-08T23:33:54.8173854Z [0m[[0m[31merror[0m] [0m[0m	org.apache.spark.sql.connect.client.SparkConnectClientSuite[0m
2023-05-08T23:33:54.8805941Z [0m[[0m[31merror[0m] [0m[0m(connect-client-jvm / Test / [31mtest[0m) sbt.TestsFailedException: Tests unsuccessful[0m
```

**Comment by HeartSaVioR** [comment]
I see all tests passed; https://github.com/siying/spark/actions/runs/4920444751

Thanks! Merging to master.

**Pull request closed without merging**
