### PR TITLE
[SPARK-34657][PYTHON][DOCS] Replace the tag of release to the hash to hide RC tags in Binder

### PR DESCRIPTION
**Pull request by HyukjinKwon**
### What changes were proposed in this pull request?

Currently Binder link at Spark 3.1.1 (https://mybinder.org/v2/gh/apache/spark/v3.1.1-rc3?filepath=python%2Fdocs%2Fsource%2Fgetting_started%2Fquickstart.ipynb) shows  `v3.1.1-rc3` like:
Screen Shot 2021-03-08 at 10 10 55 AM

After the fix, it will shows the explicit hash:

Screen Shot 2021-03-08 at 10 17 25 AM

In addition, this also fixes the examples URL while I am fixing it. For example: https://github.com/apache/spark/tree/v3.1.1-rc3/examples/src/main/python -> https://github.com/apache/spark/tree/1d550c4e902/examples/src/main/python

Note that it is hash in order to make both dev and release easier.

### Why are the changes needed?

To hide RC tags.

### Does this PR introduce _any_ user-facing change?

It will just change the URL shown when Binder is being loaded.

### How was this patch tested?

Manually tested:

```bash
make clean html
```

Screen Shot 2021-03-08 at 10 17 06 AM

```bash
git_hash=`git rev-parse --short HEAD`
export GIT_HASH=$git_hash
make clean html
```

Screen Shot 2021-03-08 at 10 17 25 AM

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
@srowen, can you take a quick look please?

**Comment by HyukjinKwon** [comment]
@srowen, can you take a quick look please?

**Review by srowen — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
This requires a manual testing, and it wouldn't affect anything in the tests. It passed the Python linters (documentation build) too. I am just merging it in.

Merged to master.

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
