### PR TITLE
[SPARK-47516][INFRA] Move `remove unused installation package logic` from `each test job` to `create the docker image`

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to move `remove unused installation package logic` from `each test job` to `create the docker image`.

### Why are the changes needed?
Speed up the testing speed of GA once and for all.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @zhengruifeng

**Comment by zhengruifeng** [comment]
thanks, LGTM if the CI is green

**Comment by panbingkun** [comment]
Let me make some improvements.

**Comment by panbingkun** [comment]
Same effect

- Before:
  https://github.com/panbingkun/spark/actions/runs/8372589818/job/22924449880
  image

- After:
  https://github.com/panbingkun/spark/actions/runs/8387322630/job/22969412762
  image

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by zhengruifeng** [comment]
@panbingkun 

Hi, bingkun, when rebuild the image in https://github.com/zhengruifeng/spark/actions/runs/8857365994/job/24324764602

I see such warnings:
```
#35 [29/31] RUN apt-get remove --purge -y     '^aspnet.*' '^dotnet-.*' '^llvm-.*' 'php.*' '^mongodb-.*'     snapd google-chrome-stable microsoft-edge-stable firefox     azure-cli google-cloud-sdk mono-devel powershell libgl1-mesa-dri || true
#35 0.489 Reading package lists...
#35 0.505 Building dependency tree...
#35 0.507 Reading state information...
#35 0.511 E: Unable to locate package ^aspnet.*
#35 0.511 E: Couldn't find any package by glob '^aspnet.*'
#35 0.511 E: Couldn't find any package by regex '^aspnet.*'
#35 0.511 E: Unable to locate package ^dotnet-.*
#35 0.511 E: Couldn't find any package by glob '^dotnet-.*'
#35 0.511 E: Couldn't find any package by regex '^dotnet-.*'
#35 0.511 E: Unable to locate package ^llvm-.*
#35 0.511 E: Couldn't find any package by glob '^llvm-.*'
#35 0.511 E: Couldn't find any package by regex '^llvm-.*'
#35 0.511 E: Unable to locate package ^mongodb-.*
#35 0.511 E: Couldn't find any package by glob '^mongodb-.*'
#35 0.511 EPackage 'php-crypt-gpg' is not installed, so not removed
#35 0.511 Package 'php' is not installed, so not removed
#35 0.511 : Couldn't find any package by regex '^mongodb-.*'
#35 0.511 E: Unable to locate package snapd
#35 0.511 E: Unable to locate package google-chrome-stable
#35 0.511 E: Unable to locate package microsoft-edge-stable
#35 0.511 E: Unable to locate package firefox
#35 0.511 E: Unable to locate package azure-cli
#35 0.511 E: Unable to locate package google-cloud-sdk
#35 0.511 E: Unable to locate package mono-devel
#35 0.511 E: Unable to locate package powershell
#35 DONE 0.5s

#36 [30/31] RUN apt-get autoremove --purge -y
#36 0.063 Reading package lists...
#36 0.079 Building dependency tree...
#36 0.082 Reading state information...
#36 0.088 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
#36 DONE 0.4s
```

would you mind help check whether this removal is needed in ubuntu 2024

**Comment by panbingkun** [comment]
> @panbingkun
> 
> Hi, bingkun, when rebuild the image in https://github.com/zhengruifeng/spark/actions/runs/8857365994/job/24324764602
> 
> I see such warnings:
> 
> ```
> #35 [29/31] RUN apt-get remove --purge -y     '^aspnet.*' '^dotnet-.*' '^llvm-.*' 'php.*' '^mongodb-.*'     snapd google-chrome-stable microsoft-edge-stable firefox     azure-cli google-cloud-sdk mono-devel powershell libgl1-mesa-dri || true
> #35 0.489 Reading package lists...
> #35 0.505 Building dependency tree...
> #35 0.507 Reading state information...
> #35 0.511 E: Unable to locate package ^aspnet.*
> #35 0.511 E: Couldn't find any package by glob '^aspnet.*'
> #35 0.511 E: Couldn't find any package by regex '^aspnet.*'
> #35 0.511 E: Unable to locate package ^dotnet-.*
> #35 0.511 E: Couldn't find any package by glob '^dotnet-.*'
> #35 0.511 E: Couldn't find any package by regex '^dotnet-.*'
> #35 0.511 E: Unable to locate package ^llvm-.*
> #35 0.511 E: Couldn't find any package by glob '^llvm-.*'
> #35 0.511 E: Couldn't find any package by regex '^llvm-.*'
> #35 0.511 E: Unable to locate package ^mongodb-.*
> #35 0.511 E: Couldn't find any package by glob '^mongodb-.*'
> #35 0.511 EPackage 'php-crypt-gpg' is not installed, so not removed
> #35 0.511 Package 'php' is not installed, so not removed
> #35 0.511 : Couldn't find any package by regex '^mongodb-.*'
> #35 0.511 E: Unable to locate package snapd
> #35 0.511 E: Unable to locate package google-chrome-stable
> #35 0.511 E: Unable to locate package microsoft-edge-stable
> #35 0.511 E: Unable to locate package firefox
> #35 0.511 E: Unable to locate package azure-cli
> #35 0.511 E: Unable to locate package google-cloud-sdk
> #35 0.511 E: Unable to locate package mono-devel
> #35 0.511 E: Unable to locate package powershell
> #35 DONE 0.5s
> 
> #36 [30/31] RUN apt-get autoremove --purge -y
> #36 0.063 Reading package lists...
> #36 0.079 Building dependency tree...
> #36 0.082 Reading state information...
> #36 0.088 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
> #36 DONE 0.4s
> ```
> 
> would you mind help check whether this removal is needed in ubuntu 2024

Sure, let me to do it.
Thanks!

**Pull request closed without merging**
