### PR TITLE
[SPARK-23708][CORE] Correct comment for function addShutDownHook in ShutdownHookManager

### PR DESCRIPTION
**Pull request by caneGuy**
## What changes were proposed in this pull request?
Minor modification.Comment below is not right.
```
/**
   * Adds a shutdown hook with the given priority. Hooks with lower priority values run
   * first.
   *
   * @param hook The code to run during shutdown.
   * @return A handle that can be used to unregister the shutdown hook.
   */
  def addShutdownHook(priority: Int)(hook: () => Unit): AnyRef = {
    shutdownHooks.add(priority, hook)
  }
```

## How was this patch tested?

UT

### CODE REVIEW

**Review by Ngone51 — APPROVED** [review]

**Comment by caneGuy** [comment]
cc @cloud-fan @jerryshao

**Review by jiangxb1987 — APPROVED** [review]
The `SparkShutdownHook`s are sorted by reverse order, so the original comment should be updated.

**Comment by caneGuy** [comment]
@jiangxb1987 @Ngone51 Thanks! Any more comments?

**Review by jerryshao — APPROVED** [review]
LGTM, merging to master.

**Comment by jerryshao** [comment]
@caneGuy it is not necessary to create a JIRA for such tiny fix.

**Comment by caneGuy** [comment]
Get it! @jerryshao Thanks!

**Pull request closed without merging**
