### PR TITLE
[SPARK-16086] [SQL] fix Python UDF without arguments (for 1.6)

### PR DESCRIPTION
**Pull request by davies**
## What changes were proposed in this pull request?

Fix the bug for Python UDF that does not have any arguments.
## How was this patch tested?

Added regression tests.

### CODE REVIEW

**Comment by felixcheung** [comment]
looks good!

**Comment by davies** [comment]
Merged into 1.5, 1.6, 2.0 and master.

**Comment by mengxr** [comment]
@davies The PR was sent to branch-1.6 and Jenkins didn't run it for branch-2.0 and master. Does it apply to branch-2.0 and master?

**Comment by mengxr** [comment]
I reverted the changes in branch-2.0 and master and updated the JIRA. Please re-submit PRs to branch-2.0 and master if they need fixes.

**Comment by davies** [comment]
@mengxr My bad, 2.0 and master does not have this bug, but still good to have the test and change, I will send a new PR to fix the conflict.

**Pull request closed without merging**
