### PR TITLE
[SPARK-5667] Remove version from spark-ec2 example.

### PR DESCRIPTION
**Pull request by MiguelPeralvo**
Change spark-version from 1.1.0 to 1.2.0 in the example for spark-ec2/Launch Cluster.

### CODE REVIEW

**Comment by nchammas** [comment]
LGTM. Another thing we could do is just remove the `--spark-version` option since it defaults to the latest release of Spark.

**Comment by MiguelPeralvo** [comment]
I think that's even a better option. I'm happy to propose it.

**Comment by MiguelPeralvo** [comment]
I've amended the commit.

**Comment by nchammas** [comment]
A couple more things @MiguelPeralvo:
* If you would like mention in Spark's release notes, please [create a JIRA](http://issues.apache.org/jira/browse/SPARK) for this issue per [the guidelines](https://cwiki.apache.org/confluence/display/SPARK/Contributing+to+Spark#ContributingtoSpark-ContributingCode).
* Update the title of this PR to "[SPARK-XXXX] Remove version from spark-ec2 example." The "[SPARK-XXXX]" part is optional, depending on whether you want to create a JIRA. The PR title and body become the commit message when this gets merged.

**Comment by JoshRosen** [comment]
I've also merged this into `branch-1.3` (1.3.0).

**Comment by nchammas** [comment]
Oh, I thought we would've wanted to fix the PR title at least, but no biggie.

**Comment by JoshRosen** [comment]
@srowen you can do `git commit --amend` to edit the commit title yourself before pushing to GitHub.

**Comment by srowen** [comment]
@JoshRosen a-ha, so after the script merges locally, go amend it separately, then continue with the script eh?

**Comment by JoshRosen** [comment]
@srowen Yep, it waits and prompts you before pushing to Apache, so at that point you can amend things.  If you amend and then push to master, then proceed to merge the PR into additional branches, the PR script will automatically take care of making sure that the commit that was actually pushed to Apache is pulled into the other branches, too, so the effects of your amend will occur for all cherry-picks performed within the same run of the merge script.

**Comment by MiguelPeralvo** [comment]
Thank you @nchammas, I've done as you suggested (created JIRA [SPARK-5667] and amended title).

**Pull request closed without merging**
