### PR TITLE
[SPARK-40991][PYTHON] Update `cloudpickle` to v2.2.0

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to update `cloudpickle` to `v2.2.0` for Apache Spark 3.4.0.

### Why are the changes needed?

SPARK-37457 updated `cloudpickle` v2.0.0 at Apache Spark 3.3.0.

To bring the latest bug fixes.
- https://github.com/cloudpipe/cloudpickle/releases/tag/v2.2.0
- https://github.com/cloudpipe/cloudpickle/releases/tag/2.1.0

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the CIs.

### CODE REVIEW

**Review by HyukjinKwon — COMMENTED** [review]
Actually we should copy and paste this file too https://github.com/cloudpipe/cloudpickle/blob/master/cloudpickle/cloudpickle_fast.py and `__init__.py` (see also https://github.com/apache/spark/pull/31007).

A couple of minor changes in the import is required too, e.g.)

```
from pyspark.cloudpickle.cloudpickle import *  # noqa
from pyspark.cloudpickle.cloudpickle_fast import CloudPickler, dumps, dump  # noqa
```

in `__init__.py` IIRC

**Comment by itholic** [comment]
+1 for upgrading the `cloudpickle` version

**Comment by dongjoon-hyun** [comment]
Thank you for review, @HyukjinKwon and @itholic .

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by dongjoon-hyun** [comment]
Thank you so much, @HyukjinKwon !

**Pull request closed without merging**
