### PR TITLE
[SPARK-28381][PYSPARK] Upgraded version of Pyrolite to 4.30

### PR DESCRIPTION
**Pull request by viirya**
## What changes were proposed in this pull request?

This upgraded to a newer version of Pyrolite. Most updates [1] in the newer version are for dotnot. For java, it includes a bug fix to Unpickler regarding cleaning up Unpickler memo, and support of protocol 5.

After upgrading, we can remove the fix at SPARK-27629 for the bug in Unpickler.

[1] https://github.com/irmen/Pyrolite/compare/pyrolite-4.23...master

## How was this patch tested?

Manually tested on Python 3.6 in local on existing tests.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
cc @HyukjinKwon

**Review by srowen — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Hey, @viirya. let's create another JIRA. At least I can't properly set fix version in the JIRA :-).

**Review by HyukjinKwon — APPROVED** [review]

**Comment by viirya** [comment]
Oops! Thanks! @HyukjinKwon I wrongly copied the title from previous PR. :D

**Comment by HyukjinKwon** [comment]
@viirya, shall we remove this comment here? https://github.com/apache/spark/commit/d9bcacf94b93fe76542b5c1fd852559075ef6faa#diff-cfbe62fac3cd77efbc7c65bed2752377R131

**Comment by viirya** [comment]
@HyukjinKwon OK. Let me remove it.

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
