### PR TITLE
[SPARK-21970][Core] Fix Redundant Throws Declarations in Java Codebase

### PR DESCRIPTION
**Pull request by original-brownbear**
## What changes were proposed in this pull request?

1. Removing all redundant throws declarations from Java codebase.
2. Removing dead code made visible by this from `ShuffleExternalSorter#closeAndGetSpills`

## How was this patch tested?

Build still passes.

### CODE REVIEW

**Comment by srowen** [comment]
Some of these 'throws' clauses may not be removable because they cause callers that catch the checked exception to fail to compile. 

Removing "throws Exception" in tests isn't obviously helpful, because it means the signature has to change any time the tested code happens to throw a new checked exception. There's no API problem as nothing invokes these methods directly.

Private non-test methods, maybe.

**Comment by original-brownbear** [comment]
@srowen makes perfect sense => rolled back all changes to tests + publicly exposed methods (those package private ones adjusted are on non-public classes).

**Review by srowen — COMMENTED** [review]
This kind of thing looks like good cleanup if it compiles and passes MiMa

**Comment by original-brownbear** [comment]
@srowen looks like we're all green :)

**Comment by srowen** [comment]
Ah OK one more subtle thing @original-brownbear  -- the code you see in org/apache/hive packages is, I believe, copied from Hive. Therefore it's probably best to leave it as-is because it makes it easier to update it if it hasn't varied at all from its source. Could you reverse those? otherwise looks OK.

**Comment by original-brownbear** [comment]
@srowen done, all changes to `org.apache.hive.*` reverted :)

**Review by srowen — APPROVED** [review]

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
