### PR TITLE
[SPARKR] fix R roxygen2 doc for count on GroupedData

### PR DESCRIPTION
**Pull request by felixcheung**
## What changes were proposed in this pull request?

fix code doc
## How was this patch tested?

manual

@shivaram

### CODE REVIEW

**Comment by felixcheung** [comment]
found and discussed in #13734

**Comment by shivaram** [comment]
cc @dongjoon-hyun

**Comment by dongjoon-hyun** [comment]
LGTM. It's that all?

**Comment by shivaram** [comment]
Thanks - LGTM. Merging this to master and branch-2.0 -- (We can reverify this is #13734 I guess ?)

**Pull request closed without merging**
