### PR TITLE
[SPARK-44342][SQL] Replace SQLContext with SparkSession for GenTPCDSData

### PR DESCRIPTION
**Pull request by beliefer**
### What changes were proposed in this pull request?
The `SQLContext` is an old API for Spark SQL.
But `GenTPCDSData` still use it directly.

### Why are the changes needed?
Avoid use the legacy API for `GenTPCDSData`.

### Does this PR introduce _any_ user-facing change?
'No'.
Just update the benchmark utils.

### How was this patch tested?
Manual test by running:
`build/sbt "sql/Test/runMain org.apache.spark.sql.GenTPCDSData --dsdgenDir ... --location ... --scaleFactor 1"`

### CODE REVIEW

**Comment by beliefer** [comment]
ping @cloud-fan

**Review by oss-maker — APPROVED** [review]
LGTM +1

**Review by yaooqinn — APPROVED** [review]

**Comment by yaooqinn** [comment]
thanks, merged to master

**Comment by beliefer** [comment]
@yaooqinn @oss-maker Thank you !

**Pull request closed without merging**
