### PR TITLE
[SPARK-38711][PYTHON][SS] Refactor pyspark.sql.streaming module

### PR DESCRIPTION
**Pull request by HyukjinKwon**
### What changes were proposed in this pull request?

This PR changes `pyspark/sql/streaming.py` module to a package with two files: `pyspark/sql/streaming/query.py` and `pyspark/sql/streaming/readwriter.py`. This is similar with `pyspark/sql/dataframe.py` and `pyspark/sql/readwriter.py`.

There should be no user facing change because I kept the existing import at `pyspark/sql/streaming/__init__.py`.

### Why are the changes needed?

To make the codes easier to read.

### Does this PR introduce _any_ user-facing change?

No, dev-only.

### How was this patch tested?

Existing test cases should cover this change.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @zsxwing and @HeartSaVioR FYI

**Comment by HyukjinKwon** [comment]
For a bit of more background, I plan to add a couple of more modules under `pyspark.sql.streaming`.

**Review by xinrong-meng — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Thanks @xinrong-databricks. cc @viirya too FYI. I am merging this as I don't think there's any controversial change here, and it's all consistent with the existing codebase.

**Comment by HyukjinKwon** [comment]
Merged to master.

**Review by viirya — COMMENTED** [review]
looks fine.

**Review by HeartSaVioR — COMMENTED** [review]
No context but seems to be great refactoring. Thanks for taking up!

**Pull request closed without merging**
