### PR TITLE
[SPARK-39676][CORE][TESTS] Add task partition id for TaskInfo assertEquals method in JsonProtocolSuite

### PR DESCRIPTION
**Pull request by dcoliversun**
### What changes were proposed in this pull request?

In https://github.com/apache/spark/pull/35185 , task partition id was added in taskInfo. And, JsonProtocolSuite#assertEquals about TaskInfo doesn't have partitionId.

### Why are the changes needed?

Should assert partitionId equals or not.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

No need to add unit test.

### CODE REVIEW

**Comment by dcoliversun** [comment]
cc @cloud-fan 
If we want to solve the problem better, we should implement `equals` method in the class declaration. I can submit a PR to do this work if I feel it is necessary.

**Review by HyukjinKwon — APPROVED** [review]

**Review by LuciferYang — APPROVED** [review]
LGTM +1

**Comment by HyukjinKwon** [comment]
Merged to master and branch-3.3.

**Comment by dcoliversun** [comment]
Thanks all :)

**Pull request closed without merging**
