### PR TITLE
[SPARK-39538][SQL] Avoid creating unnecessary SLF4J Logger

### PR DESCRIPTION
**Pull request by pan3793**
### What changes were proposed in this pull request?

Convert `CaseInsensitiveStringMap#logger` to static, it's safe since the `org.slf4j.Logger` is thread-safe.

### Why are the changes needed?

To improve performance.

The overhead of `LoggerFactory.getLogger(CaseInsensitiveStringMap.class)` is non-negligible.

I always see this when I refresh the page "Thread dump for executor".

image
image

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Existing UT.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
@pan3793 mind rebasing your master branch in your forked repo, to the latest master branch in Apache Spark?

**Comment by HyukjinKwon** [comment]
Just fixed. mind syncing again?

**Comment by pan3793** [comment]
Thanks @HyukjinKwon, let me try.

**Comment by HyukjinKwon** [comment]
Pushed another fix just now. Mind trying agian?

**Comment by HyukjinKwon** [comment]
👍

**Comment by pan3793** [comment]
@HyukjinKwon would you please take a look at this PR itself?

**Review by srowen — COMMENTED** [review]
Looks good. I see a few more instances of "private final Logger" in 3 other classes; maybe we can fix those too?

**Comment by pan3793** [comment]
Thanks @srowen, fixed.

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
