### PR TITLE
Fix the import typo in Python example

### PR DESCRIPTION
**Pull request by sjjpo2002**
## What changes were proposed in this pull request?

The Python [example ](https://spark.apache.org/docs/latest/mllib-data-types.html#local-matrix) in local matrix data type in MLlib needs to fix the import line:

`import org.apache.spark.mllib.linalg.{Matrix, Matrices}`

It seems it has been copied from Scala by mistake.

I couldn't find the source to apply the changes.
## How was this patch tested?

It's a typo in the docs

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by vanzin** [comment]
@sjjpo2002 please close this PR; if you actually meant to send a patch, you did something wrong when creating it.

**Comment by srowen** [comment]
Not sure what happened with this PR, but it's clearly in a bad state. Can you close it?

**Comment by sjjpo2002** [comment]
I'm closing this. I'm not sure how this caused build errors. I just referred to the typo in the documentation and didn't make any changes!

**Comment by srowen** [comment]
@sjjpo2002 not a problem with the change you tried to make, maybe, but your branching is incorrect.

**Pull request closed without merging**
