### PR TITLE
[SPARK-14154][MLlib] remove stale comment for KolmogorovSmirnovTest

### PR DESCRIPTION
**Pull request by hhbyyh**
## What changes were proposed in this pull request?

Remove the stale comment for KolmogorovSmirnovTest since the implementation has been changed.
Let me know if a jira is required.
## How was this patch tested?

ut

### CODE REVIEW

**Comment by MLnick** [comment]
LGTM pending test run.

**Comment by MLnick** [comment]
Not strictly necessary to have a JIRA, but is this essentially a follow up to [SPARK-14154] (https://issues.apache.org/jira/browse/SPARK-14154)? In which case maybe just link to that?

**Comment by hhbyyh** [comment]
Good idea. Thanks. I'll update the title.

**Comment by mengxr** [comment]
@hhbyyh Sorry that I just saw #11954. Please see my comments on the JIRA.

**Comment by srowen** [comment]
Ah OK, so then this change will no longer be necessary once the change in #11954 is reverted/revised?

**Comment by hhbyyh** [comment]
Maybe I can just use this PR to revert the change? @mengxr

**Comment by mengxr** [comment]
I will revert that commit directly. Please close this PR manually. Thanks!

**Pull request closed without merging**
