### PR TITLE
[SPARK-50108][INFRA][PYTHON][TESTS] Upgrade PyPy CI to 3.10

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to upgrade `PyPy` CI from 3.9 to 3.10.

### Why are the changes needed?

Since PyPy v7.3.18, Python 3.9 is dropped. To track the latest Python versions, we need to use PyPy 3.10.
- https://doc.pypy.org/en/latest/release-v7.3.17.html

### Does this PR introduce _any_ user-facing change?

No, this is an infra-only change.

### How was this patch tested?

Pass the CIs for building image and manual review because this is a daily CI change.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Review by zhengruifeng — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @zhengruifeng .

**Review by xinrong-meng — APPROVED** [review]

**Comment by xinrong-meng** [comment]
LGTM, thank you!

**Comment by dongjoon-hyun** [comment]
Thank you, @xinrong-meng .

**Comment by dongjoon-hyun** [comment]
Merged to master for Apache Spark 4.0.0 on February 2025.

**Comment by dongjoon-hyun** [comment]
For the record, `PyPy 3.10` Daily CI passed today.
- https://github.com/apache/spark/actions/runs/11520734751

**Pull request closed without merging**
