### PR TITLE
[SPARK-49517][BUILD] Upgrade `netty-tcnative` to 2.0.66.Final

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to upgrade `netty-tcnative` from `2.0.65.Final` to `2.0.66.Final`.

### Why are the changes needed?
`2.0.65.Final` VS `2.0.66.Final`
https://github.com/netty/netty-tcnative/compare/netty-tcnative-parent-2.0.65.Final...netty-tcnative-parent-2.0.66.Final

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Is this ready, @panbingkun ?

**Comment by panbingkun** [comment]
> Is this ready, @panbingkun ?

Ready, thanks!

**Review by xinrong-meng — APPROVED** [review]

**Comment by xinrong-meng** [comment]
LGTM thank you!

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Merged to master.
Thank you, @panbingkun and @xinrong-meng .

**Pull request closed without merging**
