### PR TITLE
[DOCS] Fix cloud-integration.md Typo

### PR DESCRIPTION
**Pull request by KraFusion**
Corrected typo; changed spark-default.conf to spark-defaults.conf

### CODE REVIEW

**Comment by kiszk** [comment]
Thanks, would it possible to address similar issues? For example, in `configurations.md`.

**Comment by KraFusion** [comment]
@kiszk PR created yesterday for ```configurations.md```

**Comment by srowen** [comment]
OK, we should bundle these, but w/e

**Comment by srowen** [comment]
Merged to master

**Comment by kiszk** [comment]
@KraFusion Sorry, I overlooked another PR.

**Pull request closed without merging**
