### PR TITLE
[SPARK-7991] [PySpark] Adding support for passing lists to describe.

### PR DESCRIPTION
**Pull request by ameyc**
This is a minor change.

### CODE REVIEW

**Comment by ameyc** [comment]
@rxin

**Comment by rxin** [comment]
Can you add a docstring test for this?

**Comment by ameyc** [comment]
@rxin : Addressed your comments.

**Comment by rxin** [comment]
Jenkins, test this please.

**Comment by rxin** [comment]
Thanks - I've merged this.

**Pull request closed without merging**
