### PR TITLE
[SPARK-31365][SQL][FOLLOWUP] Refine config document for nested predicate pushdown

### PR DESCRIPTION
**Pull request by viirya**
### What changes were proposed in this pull request?

This is a followup to address the https://github.com/apache/spark/pull/28366#discussion_r420611872 by refining the SQL config document.

### Why are the changes needed?

Make developers less confusing.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Only doc change.

### CODE REVIEW

**Comment by viirya** [comment]
cc @HyukjinKwon

**Review by maropu — APPROVED** [review]

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Thanks @viirya.

**Comment by maropu** [comment]
Merged to master/3.0.

**Comment by viirya** [comment]
Thanks @HyukjinKwon @maropu

**Pull request closed without merging**
