### PR TITLE
[SPARK-14674][SQL] Move HiveContext.hiveconf to HiveSessionState

### PR DESCRIPTION
**Pull request by yhuai**
## What changes were proposed in this pull request?

This is just cleanup. This allows us to remove HiveContext later without inflating the diff too much. This PR fixes the conflicts of https://github.com/apache/spark/pull/12431. It also removes the `def hiveConf` from `HiveSqlParser`. So, we will pass the HiveConf associated with a session explicitly instead of relying on Hive's `SessionState` to pass `HiveConf`.
## How was this patch tested?

Existing tests.

Closes #12431

### CODE REVIEW

**Comment by yhuai** [comment]
test this please

**Comment by yhuai** [comment]
hmm `create table` in VersionsSuite took 1 hour... The size of the log is pretty large (https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/56026/).

**Comment by yhuai** [comment]
test this please

**Comment by gatorsmile** [comment]
test this please

**Comment by yhuai** [comment]
hmm. VersionsSuite is extremely slow.

**Comment by yhuai** [comment]
test this please

**Comment by andrewor14** [comment]
lgtm

**Pull request closed without merging**
