### PR TITLE
SPARK-7436: Fixed instantiation of custom recovery mode factory and added tests

### PR DESCRIPTION
**Pull request by jacek-lewandowski**

### CODE REVIEW

**Comment by JoshRosen** [comment]
@ScrapCodes, could you take a quick look through this since you wrote the original patch that added support for custom recovery mode factories?  See https://issues.apache.org/jira/browse/SPARK-7436 for a description of the issue addressed by this patch.

**Comment by ScrapCodes** [comment]
@JoshRosen Thanks for pointing out. 


Until now I was in the impression of x.getClass is same as classOf[x]. 

```scala
scala> class A
defined class A

scala> new A
res0: A = A@2d38eb89

scala> classOf[A]
res1: Class[A] = class A

scala> res0.getClass
res2: Class[_ <: A] = class A

scala> 

```

Thanks a lot for adding a test suite :). There is minor nit regarding style, that we do not allow infix notations in scala syntax. LGTM otherwise.

**Comment by ScrapCodes** [comment]
This is what I mentioned about. https://cwiki.apache.org/confluence/display/SPARK/Spark+Code+Style+Guide#SparkCodeStyleGuide-InfixMethods

**Comment by jacek-lewandowski** [comment]
@ScrapCodes do you mean "should matchers" ?

**Comment by ScrapCodes** [comment]
Yes.

**Comment by jacek-lewandowski** [comment]
I don't agree with this - you already use such notation in a few places (for Idea search for `\d+\sseconds` except comments and string literals shows 16 usages for production code and 71 usages for test code, search for usages of dot-less notation of `===` method shows 4k+ usages).

Although I can see the benefits of this style guide item for the production code, I cannot understand how it could be forbidden for test code? How would you use "should matchers" without this notation? Scala test frameworks are designed to use dot-less notation to improve readability and understanding of test cases, as well as to decrease unneeded verbosity.

**Comment by ScrapCodes** [comment]
I am sorry, I was in an assumption we are religious about it. A quick search across the codebase proved my wrong. Matchers are widely used in at least recently added code. I personally agree with your opinion on scala and makes sense for dsl, but then it was just a convention. 

@JoshRosen if you are okay, I can go ahead and merge this ?

**Comment by ScrapCodes** [comment]
@jacek-lewandowski Can you please close other Pull requests, with same issue id and are irrelevant.

**Comment by jacek-lewandowski** [comment]
Thanks @ScrapCodes :)
Other pull requests with the same issue id are against branch-1.3 and branch-1.4. Isn't going to be applied to those branches?

**Comment by ScrapCodes** [comment]
ahh makes sense then. Thanks a lot @jacek-lewandowski !

**Comment by ScrapCodes** [comment]
Side Note: Unless it is a non trivial merge, our merge scripts takes care of merging to other branches automatically. So we don't need separate PRs for same patch with no conflicts at all.

**Comment by jacek-lewandowski** [comment]
@ScrapCodes so this one is enough then?

**Comment by ScrapCodes** [comment]
Yes, if you think they are all exact same patch.

**Comment by jacek-lewandowski** [comment]
Ahh, i do remember now - i needed to change some thing in the test while creating branch for some release... so i would keep them.

**Comment by JoshRosen** [comment]
Thanks for looking this over, @ScrapCodes.  This looks good to me as well, so I'm going to merge this along with the other backport PRs.  :heart: the fact that this contains more test code than actual changes!

**Pull request closed without merging**
