### PR TITLE
[SPARK-9860][SQL] Join: Determine the join strategy (broadcast join or shuffle join) at runtime

### PR DESCRIPTION
**Pull request by lianhuiwang**
## What changes were proposed in this pull request?
1. add query fragment for execute stage according to exchange.
2. before running no leaf query fragment, optimize plan using mapOutputStatistics of its child fragments.
   if size of one exchange is less than autoBroadcastJoinThreshold, it transforms sort merge join to broadcast join.
   I will support optimization for skew join in another PR.
## How was this patch tested?

unit tests

### CODE REVIEW

**Comment by lianhuiwang** [comment]
cc @rxin @davies

**Comment by sameeragarwal** [comment]
@lianhuiwang could this regress performance for existing queries? Can you please share some benchmarks with us (if any)?

**Comment by gatorsmile** [comment]
We are closing it due to inactivity. please do reopen if you want to push it forward. Thanks!

**Comment by meteorchenwu** [comment]
It is great for BI scene. Why not continue?

**Pull request closed without merging**
