### PR TITLE
[SPARK-41278][CONNECT] Clean up unused QualifiedAttribute in Expression.proto

### PR DESCRIPTION
**Pull request by amaliujia**
### What changes were proposed in this pull request?

With https://github.com/apache/spark/commit/2b2ffcdc5ad1ffde0f4ec351495026106a226614 there is no longer a need to have a schema field in `LocalRelation` proto, thus the old way to specify that schema which was `QualifiedAtttribute` is no longer used. 

This PR cleans `QualifiedAttribute` proto and all its unused code.

### Why are the changes needed?

Codebase cleanup

### Does this PR introduce _any_ user-facing change?

NO

### How was this patch tested?

UT

### CODE REVIEW

**Comment by amaliujia** [comment]
@cloud-fan

**Review by grundprinzip — APPROVED** [review]

**Review by dengziming — APPROVED** [review]
LGTM.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by zhengruifeng** [comment]
late lgtm

**Comment by cloud-fan** [comment]
late LGTM

**Pull request closed without merging**
