### PR TITLE
[SPARK-11626][ML]ml.feature.Word2Vec.transform() function very slow

### PR DESCRIPTION
**Pull request by wangyum**
org.apache.spark.ml.feature.Word2Vec.transform() very slow. we should not read broadcast every sentence.

### CODE REVIEW

**Comment by mengxr** [comment]
@979969786 Could you try marking `

**Comment by 979969786** [comment]
OK, marking wordVectors @transient is better than don't marking, but still very slow

**Comment by mengxr** [comment]
@979969786 I sent you a PR at https://github.com/979969786/spark/pull/1. I think it should fix the problem (though I didn't test).

**Comment by 979969786** [comment]
I 've tested, running correctly and quickly.

**Comment by mengxr** [comment]
ok to test

**Comment by mengxr** [comment]
test this please

**Comment by mengxr** [comment]
Merged into master and branch-1.6. Thanks!

**Comment by mengxr** [comment]
cc @yinxusen for the performance issue and the fix.

**Comment by yinxusen** [comment]
Got it, thanks!

**Pull request closed without merging**
