### PR TITLE
[SPARK-42640][CONNECT] Remove stale entries from the excluding rules for CompatibilitySuite

### PR DESCRIPTION
**Pull request by amaliujia**
### What changes were proposed in this pull request?

Remove stale entries from the excluding rules for CompatibilitySuite.

### Why are the changes needed?

Keep API compatibility list in sync.

### Does this PR introduce _any_ user-facing change?

NO

### How was this patch tested?

UT

### CODE REVIEW

**Comment by amaliujia** [comment]
@hvanhovell @LuciferYang

**Comment by amaliujia** [comment]
We may have https://github.com/apache/spark/pull/40213 merged first since that looks pretty good already.

**Review by LuciferYang — APPROVED** [review]
+1, LGTM

**Review by hvanhovell — APPROVED** [review]
LGTM

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by hvanhovell** [comment]
Merging.

**Pull request closed without merging**
