### PR TITLE
[Don't Review] Only for list python packages for branch-3.4

### PR DESCRIPTION
**Pull request by panbingkun**

### CODE REVIEW

**Comment by panbingkun** [comment]
Fo record:

1.success
```
(base) panbingkun:~/Developer/spark/spark-trunk$pip install --upgrade --no-cache-dir --force-reinstall ./python/dist/pyspark-3.4.3.dev0.tar.gz
Processing ./python/dist/pyspark-3.4.3.dev0.tar.gz
  Preparing metadata (setup.py) ... done
Collecting py4j==0.10.9.7 (from pyspark==3.4.3.dev0)
  Downloading py4j-0.10.9.7-py2.py3-none-any.whl.metadata (1.5 kB)
Downloading py4j-0.10.9.7-py2.py3-none-any.whl (200 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 200.5/200.5 kB 134.2 kB/s eta 0:00:00
Building wheels for collected packages: pyspark
  Building wheel for pyspark (setup.py) ... done
  Created wheel for pyspark: filename=pyspark-3.4.3.dev0-py2.py3-none-any.whl size=626013326 sha256=e423146045a43d8c90ac471489dd5b6fb3702def94274f6db968961c8981731f
  Stored in directory: /private/var/folders/kl/p0fxfzp53g5cc38qjxqwk_cm0000gp/T/pip-ephem-wheel-cache-73zlf_ix/wheels/0d/86/cd/947463e4be802583aec12b9dd00109a2a65ea91253d3ffd32d
Successfully built pyspark
Installing collected packages: py4j, pyspark
  Attempting uninstall: pyspark
    Found existing installation: pyspark 4.0.0.dev0
    Uninstalling pyspark-4.0.0.dev0:
      Successfully uninstalled pyspark-4.0.0.dev0
Successfully installed py4j-0.10.9.7 pyspark-3.4.3.dev0
```

2.fail
```
Writing pyspark-3.4.3.dev0/setup.cfg
creating dist
Creating tar archive
removing 'pyspark-3.4.3.dev0' (and everything under it)
Installing dist into virtual env
Processing ./python/dist/pyspark-3.4.3.dev0.tar.gz
  Preparing metadata (setup.py) ... 25l- done
25hCollecting py4j==0.10.9.7 (from pyspark==3.4.3.dev0)
  Downloading py4j-0.10.9.7-py2.py3-none-any.whl.metadata (1.5 kB)
Downloading py4j-0.10.9.7-py2.py3-none-any.whl (200 kB)
25l   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/200.5 kB ? eta -:--:--
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 200.5/200.5 kB 9.1 MB/s eta 0:00:00
25hBuilding wheels for collected packages: pyspark
```

**Comment by dongjoon-hyun** [comment]
Thank you for investigation. Ya, it's really weird flakiness.

**Comment by panbingkun** [comment]
> Thank you for investigation. Ya, it's really weird flakiness.

@dongjoon-hyun 
The above problem has been addressed, and a detailed explanation is provided here: https://github.com/apache/spark/pull/45624

**Comment by dongjoon-hyun** [comment]
Then, shall we close this PR, @panbingkun ?

**Pull request closed without merging**
