### PR TITLE
[SPARK-45385][SQL][TESTS][FOLLOWUP] Improve the test case for deprecate `spark.sql.parser.escapedStringLiterals`

### PR DESCRIPTION
**Pull request by beliefer**
### What changes were proposed in this pull request?
This PR follows up https://github.com/apache/spark/pull/43187 and improve the test case.

### Why are the changes needed?
Avoid create data set duplicately of the test case.

### Does this PR introduce _any_ user-facing change?
'No'.
Just update the test cases.

### How was this patch tested?
Test cases updated.

### Was this patch authored or co-authored using generative AI tooling?
'No'.

### CODE REVIEW

**Review by MaxGekk — COMMENTED** [review]
> Avoid create data set duplicately and enhance the readability of the test case.

From my point of view, my changes are more readable because linear code is more readable than the code with conditional.

I am neutral about the changes.

**Comment by beliefer** [comment]
> I am neutral about the changes.

OK. Let me revert the change you mentioned. But we can avoid create data set duplicately.

**Comment by beliefer** [comment]
@MaxGekk Could you take a review again ?

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Let's just merge but I would avoid such change in general.

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by beliefer** [comment]
> Let's just merge but I would avoid such change in general.

Yeah. It's a minor change. I will avoid the similar change ! Thank you !

**Pull request closed without merging**
