### PR TITLE
[SPARK-7162][YARN]Launcher error in yarn-client

### PR DESCRIPTION
**Pull request by witgo**
jira: https://issues.apache.org/jira/browse/SPARK-7162

### CODE REVIEW

**Comment by witgo** [comment]
cc @vanzin

**Comment by srowen** [comment]
LGTM

**Comment by vanzin** [comment]
Yeah, I've never seen a subdirectory in the hadoop conf, but it's better to be defensive here. LGTM.

**Comment by sryza** [comment]
LGTM

**Pull request closed without merging**
