### PR TITLE
[SPARK-37884][K8S][BUILD] Upgrade kubernetes-client to 5.10.2

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to upgrade K8s client library to 5.10.2 from 5.10.1.

### Why are the changes needed?

This is a maintenance version upgrade which brings the following fix.
- https://github.com/fabric8io/kubernetes-client/commit/445103004d1ed3153d5abb272473451d05891e39

Please note that this is different from #34939 (5.11.1) which has a breaking change.
In addition, the above bug fix is in `5.10.2` and `5.11.2`, not in `5.11.1`.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the CI.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
cc @Yikun because his PR is going to be valid in the near future. This PR is not blocking this PR.

**Comment by dongjoon-hyun** [comment]
Could you review this, @sarutak and @attilapiros ?

**Review by attilapiros — APPROVED** [review]
LGTM

**Comment by dongjoon-hyun** [comment]
Thank you so much, @attilapiros !

**Comment by dongjoon-hyun** [comment]
All test passed. Merged to master for Apache Spark 3.3.
- https://github.com/dongjoon-hyun/spark/actions/runs/1689118434

**Comment by Yikun** [comment]
> because his PR is going to be valid in the near future. This PR is not blocking this PR.

@dongjoon-hyun Yep, thanks for the notification, this PR is reasonable. late LGTM.

**Comment by sarutak** [comment]
Thank you @dongjoon-hyun . It LGTM !

**Pull request closed without merging**
