### PR TITLE
[SPARK-6095] [MLLIB] Support model save/load in Python's linear models

### PR DESCRIPTION
**Pull request by yanboliang**
Linear models can be stored in Python which is different from other models currently.
So we leverage pickle to implement the function of save/load for LinearModel in regression.py and all sub-class can use it.
Currently save/load can only support binary classification due to Python API does not yet support multiclass classification. I think it can be supported in another following PR.

### CODE REVIEW

**Comment by mengxr** [comment]
@yanboliang The model import/export is designed to cross languages. If we save a model in Scala, it should be loadable in Python. This help us lower the maintenance cost. Could you go with this direction?

**Comment by yanboliang** [comment]
@mengxr Yes, it make sense. After look through the code, I found we have two alternatives:
1, Implement a new PythonMLLibAPI looks like this
def newGeneralizedLinearModel(
      modelClass: String,
      weights: Vector,
      intercept: Double): GeneralizedLinearModel {
}
And at pyspark we could get corresponding java model by this api and call save/load of java model which can make the model saved in Scala loadable in Python and vice versa.
2, Implement the save/load operation in Python independently which do the same thing as in Scala.
I prefer the first one. Because in the second scenario, if we update the save/load in Scala we need to keep the save/load function in Python have the same behavior which may leads to inconsistent. 
Any comments and suggestions?

**Comment by yanboliang** [comment]
@mengxr Yes, it make sense, I will try to implement the save/load operation in Python which do the same thing as in Scala.

**Comment by yanboliang** [comment]
Sorry I closed this PR accidentally, I pull another request #5016 for this issue.
I have implement save/load operation in Python for classification model and looking forward comments.
If this solution is OK, I will extend it to other linear model.

**Pull request closed without merging**
