### PR TITLE
[SPARK-42108][SQL] Make Analyzer transform `Count(*)` into `Count(1)`

### PR DESCRIPTION
**Pull request by zhengruifeng**
### What changes were proposed in this pull request?
Make Analyzer transform `Count(*)` into `Count(1)`

### Why are the changes needed?
Existing `Count(*) -> Count(1)` transformation happens in [`AstBuilder.visitFunctionCall`](https://github.com/apache/spark/blob/97a6955278c55fa02cb9f039ae45e49e6f0f2bfd/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/parser/AstBuilder.scala#L2105-L2132).

The Analyzer requires the `Count(*)` had already been converted to `Count(1)` in Parser, and for a given `Count(*)` expression, the Analyzer itself can not correctly handle it and cause correctness issue in Spark Connect (see https://issues.apache.org/jira/browse/SPARK-41845)

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
added UT, manually test with Spark Connect

### CODE REVIEW

**Review by cloud-fan — APPROVED** [review]

**Comment by cloud-fan** [comment]
@zhengruifeng can you fill the PR description and remove WIP?

**Review by HyukjinKwon — APPROVED** [review]

**Review by HyukjinKwon — APPROVED** [review]

**Comment by zhengruifeng** [comment]
@cloud-fan  I found that removing the `count(*) -> count(1)` in Parser will cause a lot of test failure, so add it back, and only add the support of `count(*) -> count(1)` in Analyzer

**Comment by zhengruifeng** [comment]
all tests passed, minding taking another look? @cloud-fan @HyukjinKwon

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. 

cc @huaxingao , @sunchao , too

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Comment by zhengruifeng** [comment]
thank you @dongjoon-hyun  @cloud-fan @HyukjinKwon

**Pull request closed without merging**
