### PR TITLE
[SPARK-11962] Add optional getAs functions to Row

### PR DESCRIPTION
**Pull request by aa8y**
getAsOpt[T] functions have been added to Row and GeneicRowWithSchema to get the values present in a row object optionally. Corresponding tests have also been added. Filed a pull request again after fixing style issues.

### CODE REVIEW

**Comment by aa8y** [comment]
Anything else you guys need for this?

**Comment by aa8y** [comment]
@rxin You ran a Jenkins build for my previous pull request for this issue. Could you please do the same for this build request?

**Comment by srowen** [comment]
Jenkins, test this please

**Comment by aa8y** [comment]
I remember it passed the style tests last time I checked. I'll run them again.

**Comment by aa8y** [comment]
```aallamsetty@aallamsetty-lap ~/c/spark> ./dev/run-tests
Can't install SparkR as R is was not found in PATH
[info] Using build tool sbt with Hadoop profile hadoop2.3 under environment local
[info] Found the following changed modules: root
[info] Setup the following environment variables for tests:

========================================================================
Running Apache RAT checks
========================================================================
RAT checks passed.

========================================================================
Running Scala style checks
========================================================================
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
Scalastyle checks passed.

========================================================================
Running Python style checks
========================================================================
PEP8 checks passed.

========================================================================
Running R style checks
========================================================================
Ignoring SparkR style check as R was not found in PATH```

@srowen Not sure what's going wrong here. My checks are passing.

**Comment by srowen** [comment]
Not sure but the error is:

```
[error] /home/jenkins/workspace/SparkPullRequestBuilder/sql/catalyst/src/test/scala/org/apache/spark/sql/RowTest.scala:83:0: Whitespace at end of line
```

**Comment by JoshRosen** [comment]
Looks like this PR is now broken by a bad merge with master. Would you mind closing for now and re-opening once things are fixed? Thanks!

**Comment by aa8y** [comment]
@JoshRosen I've created a new pull request, #10247 with a fresh new commit which should merge. @srowen I would really appreciate it if you could get Jenkins to test it. Please let me know if you need me to do anything else.

**Pull request closed without merging**
