### PR TITLE
[SPARK-11508] [Python] Python API for repartition and sortWithinPartitions

### PR DESCRIPTION
**Pull request by kashif**

### CODE REVIEW

**Comment by rxin** [comment]
I don't think Python supports function overloading this way ...

**Comment by kashif** [comment]
@rxin yes sorry fixing it now

**Comment by rxin** [comment]
Looks like @nongli beat you to it https://github.com/apache/spark/pull/9504

**Comment by kashif** [comment]
ah cool no problem!

**Pull request closed without merging**
