### PR TITLE
[SPARK-11150][SQL][FOLLOW-UP]Support Dynamic Partition pruning for HiveTableScanExec

### PR DESCRIPTION
**Pull request by AngersZhuuuu**
### What changes were proposed in this pull request?
Current code just support dynamic partition pruning for DataSourceScan, here we support HiveTableScan

### Why are the changes needed?
Optimize Hive Table Scan partition pruning 

### Does this PR introduce _any_ user-facing change?
NO

### How was this patch tested?
WIP

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @maryannxue FYI

**Comment by AngersZhuuuu** [comment]
retest this please

**Comment by AngersZhuuuu** [comment]
retest this please

**Comment by whcdjj** [comment]
What the cause that this job just halt? I am curious about it @AngersZhuuuu , can you tell me about it ?

**Comment by AngersZhuuuu** [comment]
@whcdjj  I have start a new work on this, pls refer to https://github.com/apache/spark/pull/34139

**Pull request closed without merging**
