### PR TITLE
[SPARK-11870][Streaming][PySpark]Rethrow the exceptions in TransformFunction and TransformFunctionSerializer

### PR DESCRIPTION
**Pull request by zsxwing**
TransformFunction and TransformFunctionSerializer don't rethrow the exception, so when any exception happens, it just return None. This will cause some weird NPE and confuse people.

### CODE REVIEW

**Comment by tdas** [comment]
any unit test?

**Comment by tdas** [comment]
and any other places where this sort of problem may occur?

**Comment by zsxwing** [comment]
Added a test to reproduce this issue

**Comment by tdas** [comment]
LGTM. Will merge to master, 1.6, 1.5, 1.4 if i can. Thanks @zsxwing

**Comment by zsxwing** [comment]
retest this please

**Pull request closed without merging**
