### PR TITLE
[SPARK-21313][SS] ConsoleSink's string representation

### PR DESCRIPTION
**Pull request by jaceklaskowski**
## What changes were proposed in this pull request?

Add `toString` with options for `ConsoleSink` so it shows nicely in query progress.

**BEFORE**

```
  "sink" : {
    "description" : "org.apache.spark.sql.execution.streaming.ConsoleSink@4b340441"
  }
```

**AFTER**

```
  "sink" : {
    "description" : "ConsoleSink[numRows=10, truncate=false]"
  }
```

/cc @zsxwing @tdas 

## How was this patch tested?

Local build

### CODE REVIEW

**Comment by srowen** [comment]
Seems OK, are there other sinks that could use a more useful toString?

**Comment by jaceklaskowski** [comment]
I think that `ConsoleSink` was the only one with this mysterious name. We could however have another JIRA to _somehow_ unify how options are printed out for sources and sinks. I don't think it should be a part of this (smallish) change.

**Comment by HyukjinKwon** [comment]
Just happened to double check to help. Sounds we have the last one, `ForeachSink`, left.

**Comment by jaceklaskowski** [comment]
If you know how to display `ForeachWriter` that's passed in to `ForeachSink` nicely, let me know. `getClass.getName` didn't convince me and so I left it out. It'd be very helpful to see what the implementation is though.

**Review by srowen — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]

**Review by HyukjinKwon — APPROVED** [review]

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
