### PR TITLE
[SPARK-29865][k8s] Ensure client-mode executors have same name prefix.

### PR DESCRIPTION
**Pull request by vanzin**
This basically does what BasicDriverFeatureStep already does to achieve the
same thing in cluster mode; but since that class (or any other feature) is
not invoked in client mode, it needs to be done elsewhere.

I also modified the client mode integration test to check the executor name
prefix; while there I had to fix the minikube backend to parse the output
from newer minikube versions (I have 1.5.2).

### CODE REVIEW

**Comment by vanzin** [comment]
Let's see if I can get anyone to look at this... @mccheah @erikerlandson

**Comment by erikerlandson** [comment]
@vanzin it seems reasonable to me.  IIRC, there was some earlier discussion about getting `FeatureStep` components to run in client-mode. Is setting the pod prefix all you need?

**Comment by vanzin** [comment]
>  getting FeatureStep components to run in client-mode

That would be good to have at some point, but it gets into discussions about how to deal with more complicated things that require creating resources on the API server.

This is a simple change that makes debugging things in client mode a lot easier, so feels worth it to do by itself.

**Comment by erikerlandson** [comment]
@vanzin, that makes sense. Maybe just throw in a couple lines of comments to annotate that "full FeatureStep is to-do and might obsolete this particular stanza in the future" and I'm fine with it

**Pull request closed without merging**
