### PR TITLE
[SPARK-48016][SQL] Fix a bug in try_divide function when with decimals

### PR DESCRIPTION
**Pull request by gengliangwang**
### What changes were proposed in this pull request?

 Currently, the following query will throw DIVIDE_BY_ZERO error instead of returning null
 ```
SELECT try_divide(1, decimal(0)); 
```

This is caused by the rule `DecimalPrecision`:
```
case b @ BinaryOperator(left, right) if left.dataType != right.dataType =>
  (left, right) match {
 ...
    case (l: Literal, r) if r.dataType.isInstanceOf[DecimalType] &&
        l.dataType.isInstanceOf[IntegralType] &&
        literalPickMinimumPrecision =>
      b.makeCopy(Array(Cast(l, DataTypeUtils.fromLiteral(l)), r)) 
```
The result of the above makeCopy will contain `ANSI` as the `evalMode`, instead of `TRY`.
This PR is to fix this bug by replacing the makeCopy method calls with withNewChildren

### Why are the changes needed?

Bug fix in try_* functions.

### Does this PR introduce _any_ user-facing change?

Yes, it fixes a long-standing bug in the try_divide function. 

### How was this patch tested?

New UT

### Was this patch authored or co-authored using generative AI tooling?

No

### CODE REVIEW

**Comment by gengliangwang** [comment]
There is another approach at https://github.com/apache/spark/pull/46251, which fails a test case in the `CanonicalizeSuite`.
Using `withNewChildren` is better here.

**Comment by dongjoon-hyun** [comment]
cc @yaooqinn too

**Review by HyukjinKwon — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by dongjoon-hyun** [comment]
BTW, thank you for adding new test coverage, @gengliangwang .

**Review by yaooqinn — APPROVED** [review]

**Comment by gengliangwang** [comment]
@HyukjinKwon @dongjoon-hyun @yaooqinn Thanks for the review. Merging to master/branch-3.5/branch-3.4

**Comment by dongjoon-hyun** [comment]
Hi, @gengliangwang . 

It's a little weird because
- This PR doesn't contain `sql/core/src/test/resources/log4j2.properties`.
- master commit also does.
- branch-3.5 commit contains `sql/core/src/test/resources/log4j2.properties` whose content is suspicious.
   - https://github.com/apache/spark/commit/e78ee2c5770218a521340cb84f57a02dd00f7f3a
```
- logger.parquet_outputcommitter.name = org.apache.parquet.hadoop.ParquetOutputCommitter
+ logger.parquet_outputcommitter.name = org.sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/TypeCoercion.scalaapache.parquet.hadoop.ParquetOutputCommitter
```

And, the above suspicious change broke `branch-3.5`.

**Comment by gengliangwang** [comment]
@dongjoon-hyun Thanks a lot. I will create a backport for 3.5.

**Pull request closed without merging**
