### PR TITLE
[SPARK-15197][Docs] Added Scaladoc for countApprox and countByValueApprox parameters

### PR DESCRIPTION
**Pull request by ntietz**
This pull request simply adds Scaladoc documentation of the parameters for countApprox and countByValueApprox.

This is an important documentation change, as it clarifies what should be passed in for the timeout. Without units, this was previously unclear.

I did not open a JIRA ticket per my understanding of the project contribution guidelines; as they state, the description in the ticket would be essentially just what is in the PR. If I should open one, let me know and I will do so.

### CODE REVIEW

**Comment by srowen** [comment]
How about doc'ing the Java version as well in JavaRDDLike.scala?
You're welcome to expand on the java/scaladoc of lots of these methods. It'd be nicer to have more complete doc of method args and return type for such a central API.

**Comment by ntietz** [comment]
Good call, I will add it to the Java version as well.

**Comment by ntietz** [comment]
I've added documentation for the Java version. Anything else that should go in with this PR?

**Comment by srowen** [comment]
Hm, then there are actually similar methods for key-value RDDs in `PairRDDFunctions` and `JavaPairRDD` -- basically the non "distinct" ones. 

I think we could also say a little bit more about what confidence means. I believe it's fair to say that, if called repeatedly, this is the fraction of results whose bounds are expected to contain the true count.

If you want to keep going ... man, I see that this value isn't even checked to be in [0,1]. Really (0,1) is all that makes sense. Everywhere in the code that computes an inverse CDF doesn't check this arg, and it will already throw an exception if so.

If you're up for it, make a JIRA to describe the expanded scope. Otherwise I'll do it at some point if you don't have bandwidth.

More points for describing in some more detail what "relativeSD" means for the "approx distinct" count methods.

**Comment by ntietz** [comment]
I'll dig deeper into the documentation and will update!

I've got the bandwidth to work on this. I'll add a JIRA for it tonight and work on it over the course of the week.

**Comment by ntietz** [comment]
I created JIRA SPARK-15197. I think that I covered the expanded scope in there, but if I goofed and missed something feel free to update.

**Comment by srowen** [comment]
@ntietz this looks good, are you able to proceed with the additional changes? I can help if needed.

**Comment by ntietz** [comment]
@srowen For sure, I'm going to work on it this week

**Comment by ntietz** [comment]
@srowen I updated what I am able to. How does it look to you?

I haven't addressed the relativeSD explanations, because I don't really understand it well enough to contribute that. I think I hit the other major points.

**Comment by srowen** [comment]
Jenkins test this please

**Comment by srowen** [comment]
Jenkins retest this please

**Comment by srowen** [comment]
Merged to master/2.0

**Pull request closed without merging**
