### PR TITLE
[SPARK-31168][SPARK-33913][BUILD] Upgrade Scala to 2.12.13 and Kafka to 2.7.0

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR is the 3rd try to upgrade Scala 2.12.x in order to see the feasibility.
- https://github.com/apache/spark/pull/27929 (Upgrade Scala to 2.12.11, @wangyum )
- https://github.com/apache/spark/pull/30940 (Upgrade Scala to 2.12.12, @viirya )

`silencer` library is updated accordingly. And, Kafka version upgrade is required because it fails like the following.
```
[info] KafkaDataConsumerSuite:
[info] org.apache.spark.streaming.kafka010.KafkaDataConsumerSuite *** ABORTED *** (1 second, 580 milliseconds)
[info]   java.lang.NoClassDefFoundError: scala/math/Ordering$$anon$7
[info]   at kafka.api.ApiVersion$.orderingByVersion(ApiVersion.scala:45)
```

### Why are the changes needed?

Apache Spark was stuck to 2.12.10 due to the regression in Scala 2.12.11 and 2.12.12. This will bring all the bug fixes.
- https://github.com/scala/scala/releases/tag/v2.12.13
- https://github.com/scala/scala/releases/tag/v2.12.12
- https://github.com/scala/scala/releases/tag/v2.12.11

### Does this PR introduce _any_ user-facing change?

Yes, but this is a bug-fixed version.

### How was this patch tested?

Pass the CIs.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
1. `Java 11 build with Maven` fails because the new plugin is not available yet in Google Maven cache. It will be resolved automatically.
2. Kafka module failure looks suspicious. I'm looking at it.

**Comment by dongjoon-hyun** [comment]
To fix Kafka issue, it seems that we need to upgrade Kafka to 2.7.0 together.

**Comment by dongjoon-hyun** [comment]
To pass Kafka UI, I'll try to upgrade Kafka version together.
cc @viirya since he has the previous PR for Kafka. (https://github.com/apache/spark/pull/30939)

**Comment by viirya** [comment]
As I said in the previous PRs, the Scala version of Kafak must be matched with Spark. Otherwise, there will be `[info]   java.lang.NoClassDefFoundError: scala/math/Ordering$$anon$7` error.

**Comment by dongjoon-hyun** [comment]
I thought like that, but please see the following. For a single module, it works. Let's wait and see the full CI result.
```scala
$ build/sbt "streaming-kafka-0-10/testOnly *.KafkaDataConsumerSuite"
...
[info] KafkaDataConsumerSuite:
[info] - KafkaDataConsumer reuse in case of same groupId and TopicPartition (188 milliseconds)
[info] - new KafkaDataConsumer instance in case of Task retry (31 milliseconds)
[info] - concurrent use of KafkaDataConsumer (2 seconds, 791 milliseconds)
[info] ScalaTest
[info] Run completed in 8 seconds, 517 milliseconds.
[info] Total number of tests run: 3
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 3, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[info] Passed: Total 3, Failed 0, Errors 0, Passed 3
[success] Total time: 147 s (02:27), completed Jan 17, 2021 9:41:13 PM
```

**Review by jaceklaskowski — APPROVED** [review]
LGTM (non-binding)

**Review by srowen — COMMENTED** [review]
Seems OK - if it works

**Comment by viirya** [comment]
Interesting, seems it works, `NoClassDefFoundError` was gone.

**Review by viirya — DISMISSED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @jaceklaskowski , @srowen , @viirya .

For `Java 11 build failure`, `silencer-plugin_2.12.13.jar` is not synced to `Google Maven Central cache` yet. I guess this can be resolved at next sync.
- https://github.com/apache/spark/pull/31223#issuecomment-761987706
```
org.apache.maven.artifact.resolver.ArtifactNotFoundException:
Could not find artifact com.github.ghik:silencer-plugin_2.12.13:jar:1.6.0 in gcs-maven-central-mirror (https://maven-central.storage-download.googleapis.com/maven2/)
```

**Comment by dongjoon-hyun** [comment]
My bad. I noticed that we have old `silencer-lib` version in `pom.xml` and fixed it, @viirya .

**Review by viirya — APPROVED** [review]
Okay, LGTM and see if latest Java 11 build can pass. Thanks.

**Comment by dongjoon-hyun** [comment]
GitHub Actions passed. Merged to master for Apache Spark 3.2.0.
Thank you all!

**Comment by Ngone51** [comment]
Hi all, I find there's still a regression of scala as reported in https://github.com/scala/bug/issues/12038. I tested the demo locally and verified that the regression does exist in scala 2.12.13 but not 2.12.10. The regression could break users' environment if they use protobuf-java 3.11.4. So I think we may need to revert this. cc @cloud-fan @HyukjinKwon

**Comment by dongjoon-hyun** [comment]
Thank you for reporting. 

Do you think we can add a test case for that with or after reverting?

**Comment by dongjoon-hyun** [comment]
BTW, are we going to downgrade Scala 2.13, too? It seems that the scala issue is open for 2.13, too.

**Comment by dongjoon-hyun** [comment]
To be clear, I'm fine with reverting PR here.

**Comment by HyukjinKwon** [comment]
Thank you @dongjoon-hyun. @Ngone51, can we file a JIRA for Scala 2.13 too so we can track? I think we're fine not to downgrade 2.13 for now since 2.13 is not out yet .. Also I agree that it would be great to know if we can have a way to test.

**Comment by Ngone51** [comment]
Opened the ticket: https://issues.apache.org/jira/browse/SPARK-34258.

Not sure how we add the test for such case in Spark. I'd take a look at least.

Thanks @dongjoon-hyun @HyukjinKwon

**Comment by HyukjinKwon** [comment]
Sure, thanks. Reverted for now.

**Comment by dongjoon-hyun** [comment]
Thank you for the investigation and taking care of that, @Ngone51 and @HyukjinKwon .

**Pull request closed without merging**
