### PR TITLE
[MINOR] [REPL] Remove dead code of Spark Repl in Scala 2.11

### PR DESCRIPTION
**Pull request by gatorsmile**
## What changes were proposed in this pull request?

Remove the dead code of Spark Repl in Scala 2.11. We only support Scala 2.12

## How was this patch tested?
N/A

### CODE REVIEW

**Comment by gatorsmile** [comment]
cc @cloud-fan @srowen

**Comment by cloud-fan** [comment]
LGTM

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Review by srowen — COMMENTED** [review]
Right, good catch, not needed now.

**Pull request closed without merging**
