### PR TITLE
[SPARK-40362][SQL][3.3] Fix BinaryComparison canonicalization

### PR DESCRIPTION
**Pull request by peter-toth**
### What changes were proposed in this pull request?
Change canonicalization to a one pass process and move logic from `Canonicalize.reorderCommutativeOperators` to the respective commutative operators' `canonicalize`.

### Why are the changes needed?
https://github.com/apache/spark/pull/34883 improved expression canonicalization performance but introduced regression when a commutative operator is under a `BinaryComparison`. This is because children reorder by their hashcode can't happen in `preCanonicalized` phase when children are not yet "final".

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Added new UT.

### CODE REVIEW

**Review by cloud-fan — APPROVED** [review]

**Review by dongjoon-hyun — COMMENTED** [review]
The compilation is broken. Please check the code.
```
/__w/spark/spark/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/decimalExpressions.scala:117:58: value preCanonicalized is not a member of org.apache.spark.sql.catalyst.expressions.Expression
[error]   override lazy val preCanonicalized: Expression = child.preCanonicalized
```

**Comment by peter-toth** [comment]
> The compilation is broken. Please check the code.

Thanks @dongjoon-hyun for checking the logs, https://github.com/apache/spark/pull/37866/commits/483d6b76573d18fb9cb3d4a01e3a9721b6a30ec5 should fix it.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @peter-toth and @cloud-fan .
Merged to branch-3.3.

**Comment by peter-toth** [comment]
Thanks @cloud-fan, @dongjoon-hyun.

**Pull request closed without merging**
