### PR TITLE
[SPARK-31442][SQL] Print shuffle id at coalesce partitions target size

### PR DESCRIPTION
**Pull request by ulysses-you**
### What changes were proposed in this pull request?

Minor change. Print shuffle id.

### Why are the changes needed?

Make log more clear. 

### Does this PR introduce any user-facing change?

No.

### How was this patch tested?

Not need.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by maropu** [comment]
retest this please

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Review by maropu — APPROVED** [review]

**Comment by maropu** [comment]
retest this please

**Comment by dongjoon-hyun** [comment]
Merged to master/3.0. Thank you, @ulysses-you and @maropu .

**Comment by ulysses-you** [comment]
@dongjoon-hyun @maropu thanks.

**Pull request closed without merging**
