### PR TITLE
[WIP][SPARK-13994][SQL] Investigate types not supported by vectorized parquet reader

### PR DESCRIPTION
**Pull request by sameeragarwal**
Investigating (via tests) all the data types that are not supported by vectorized parquet record reader.

### CODE REVIEW

**Comment by jodersky** [comment]
Is this meant to be a PR? Looking at the code, it seems more like a wok progress.

Mind closing and reopening once its ready?

**Comment by sameeragarwal** [comment]
@jodersky as part of 2.0, we are trying to extend the vectorized parquet record reader to work with all supported data types. This PR is created to scope out the change by identifying those datatypes that'd currently fall back to the default parquet-mr record reader (by running the entire test suite on it).

**Comment by jodersky** [comment]
Ok, but it seems somewhat premature to open a PR. Maybe you could add a [WIP] into the title?

**Comment by rxin** [comment]
Yes - let's add WIP to the title if a PR is not ready for review.

**Comment by davies** [comment]
@sameeragarwal At least, TimestampType is not supported.

**Comment by sameeragarwal** [comment]
Thanks, from the test failures, it seems like among the supported primitive datatypes, `DecimalType(25,5)` and `TimestampType` are currently not supported. Created followup JIRAs: https://issues.apache.org/jira/browse/SPARK-14015 and https://issues.apache.org/jira/browse/SPARK-14016 to track the followup tasks. Closing this PR.

**Pull request closed without merging**
