### PR TITLE
[SPARK-13550] [ML] Add java example for ml.clustering.BisectingKMeans

### PR DESCRIPTION
**Pull request by zhengruifeng**
JIRA: https://issues.apache.org/jira/browse/SPARK-13550
## What changes were proposed in this pull request?

Just add a java example for ml.clustering.BisectingKMeans
## How was this patch tested?

manual tests were done.

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by srowen** [comment]
I'm not sure we need an example for every single algorithm, unless an example meaningfully explains non-trivial usage that others don't. We already have examples for k-means; does this add much?

**Comment by zhengruifeng** [comment]
@srowen this is the first java example for ml.clustering.BisectingKMeans

**Comment by mengxr** [comment]
@srowen It would be nice to have example code in the user guide for every algorithm. And this PR helps.

**Comment by mengxr** [comment]
ok to test

**Comment by mengxr** [comment]
LGTM. Merged into master. Thanks!

**Pull request closed without merging**
