### PR TITLE
[SPARK-48574][SQL] Fix support for StructTypes with collations

### PR DESCRIPTION
**Pull request by mihailomilosevic2001**
### What changes were proposed in this pull request?
Fix for ExtractValue expression

### Why are the changes needed?
This fix is needed in case we change default collation.

### Does this PR introduce _any_ user-facing change?
Yes, it fixes a problem.

### How was this patch tested?
Added tests in `CollationSQLExpressionsSuite.scala`

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]

**Review by yaooqinn — APPROVED** [review]

**Comment by mihailom-db** [comment]
@cloud-fan This is ready for merge now. Resolved conflicts of test oredering in CollationSQLExpressionsSuite.

**Comment by mihailom-db** [comment]
@HyukjinKwon could we merge this change in?

**Comment by yaooqinn** [comment]
Merged to master, thank you @mihailom-db

**Comment by cloud-fan** [comment]
late LGTM

**Pull request closed without merging**
