### PR TITLE
[SPARK-44406][CONNECT] Make `SparkSession.sql` work properly with dropped temp view

### PR DESCRIPTION
**Pull request by zhengruifeng**
### What changes were proposed in this pull request?

`SparkSession.sql` in Connect actually only return a unresolved plan, however it may reference temp view, it should hold the analyzed plan in the server side in this case, since the temp view maybe dropped somewhere.

### Why are the changes needed?

it is a common pattern:

1. create temp views;
2. reference temp views in `SparkSession.sql` and get a result dataframe;
3. drop temp views;
4. return the dataframe;

for example:
1, in sql_formatter: https://github.com/apache/spark/blob/9aa42a970c4bd8e54603b1795a0f449bd556b11b/python/pyspark/sql/sql_formatter.py#L67-L85
2, in mllib:
https://github.com/apache/spark/blob/d679dabdd1b5ad04b8c7deb1c06ce886a154a928/mllib/src/main/scala/org/apache/spark/ml/feature/SQLTransformer.scala#L70-L75

### Does this PR introduce _any_ user-facing change?
yes

before:
```
In [1]: df = spark.range(0, 10)

In [2]: df.createOrReplaceTempView("t1")

In [3]: df2 = spark.sql("select * from t1")

In [4]: spark.catalog.dropTempView("t1")
Out[4]: True

In [5]: df2.show()
23/07/13 18:33:08 ERROR SparkConnectService: Error during: execute. UserId: ruifeng.zheng. SessionId: 3ce414b0-c99e-450d-ba11-c0f5fcb2daf3.
org.apache.spark.sql.AnalysisException: [TABLE_OR_VIEW_NOT_FOUND] The table or view `t1` cannot be found. Verify the spelling and correctness of the schema and catalog.
If you did not qualify the name with a schema, verify the current_schema() output, or qualify the name with the correct schema and catalog.
To tolerate the error on drop use DROP VIEW IF EXISTS or DROP TABLE IF EXISTS.; line 1 pos 14;
'Project [*]
+- 'UnresolvedRelation [t1], [], false
```

after:
```
In [1]: df = spark.range(0, 10)

In [2]: df.createOrReplaceTempView("t1")

In [3]: df2 = spark.sql("select * from t1")

In [4]: spark.catalog.dropTempView("t1")
Out[4]: True

In [5]: df2.show()
+---+
| id|
+---+
|  0|
|  1|
|  2|
|  3|
|  4|
|  5|
|  6|
|  7|
|  8|
|  9|
+---+
```

### How was this patch tested?
added ut

### CODE REVIEW

**Comment by zhengruifeng** [comment]
cc @HyukjinKwon @cloud-fan @grundprinzip @hvanhovell

**Review by HyukjinKwon — DISMISSED** [review]

**Review by grundprinzip — CHANGES_REQUESTED** [review]
This is a behavioral change. The first version of the SQL() was using a similar cached DF approach but we decided against it because it is now you're creating a lot of state on the server side for no good reason. 

Now simply by using the API the DF becomes stored on the server and it's not easily retriable.

**Comment by hvanhovell** [comment]
Please don't do this. Now the API becomes more inconsistent. E.g. so when you reference a deleted temp view from sql you will get a result, however when you reference the same temp view using `spark.table(...)` you get an error?

**Comment by HyukjinKwon** [comment]
In that case, let's probably just revert https://github.com/apache/spark/pull/41980 out. That feature itself is experimental so we don't necessarily have to support it in Spark Connect.

Another way is just try to cache specifically in `sql` with kwargs. If that can be easily done, we could go ahead

**Comment by zhengruifeng** [comment]
> Please don't do this. Now the API becomes more inconsistent. E.g. so when you reference a deleted temp view from sql you will get a result, however when you reference the same temp view using `spark.table(...)` you get an error?

good point. Do it mean we should also make such changes for `spark.table`?  since the vanilla spark works in this way.

**Comment by zhengruifeng** [comment]
> This is a behavioral change. The first version of the SQL() was using a similar cached DF approach but we decided against it because it is now you're creating a lot of state on the server side for no good reason.
> 
> Now simply by using the API the DF becomes stored on the server and it's not easily retriable.

the problem I think, is that the `spark.sql` becomes nondeterministic. After user get a DF from  `spark.sql`, if user drop/replace the view, the query output can be changed.

spark still have to store the plans in catalog for temp views, which can not be dropped and are exposed to the end users.

**Comment by HyukjinKwon** [comment]
Branchcut is soon so let's revert https://github.com/apache/spark/pull/41980 first.

**Comment by zhengruifeng** [comment]
> Branchcut is soon so let's revert #41980 first.

ok, let's revert that one, since it creates temp view if `kwargs` contains DF variables. I can not find an alternative solution.

**Pull request closed without merging**
