### PR TITLE
[SPARK-35707][ML] optimize sparse GEMM by skipping bound checking

### PR DESCRIPTION
**Pull request by zhengruifeng**
### What changes were proposed in this pull request?
Sparse gemm use mothod `DenseMatrix.apply` to access the values, which can be optimized by skipping checking the bound and `isTransposed`

```
  override def apply(i: Int, j: Int): Double = values(index(i, j))

  private[ml] def index(i: Int, j: Int): Int = {
    require(i >= 0 && i < numRows, s"Expected 0 <= i < $numRows, got i = $i.")
    require(j >= 0 && j < numCols, s"Expected 0 <= j < $numCols, got j = $j.")
    if (!isTransposed) i + numRows * j else j + numCols * i
  }

```

### Why are the changes needed?
to improve performance, about 15% faster in the designed case

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
existing testsuite and additional performance test

### CODE REVIEW

**Comment by zhengruifeng** [comment]
[test](https://github.com/apache/spark/pull/32857/commits/7e8f195fc056ce39b5032fb85706615ada1f66c4) :

```
  test("sparse gemm") {
    val rng = new scala.util.Random(0)
    val m = 1e3.toInt
    val n = 1e3.toInt
    val k = 1e3.toInt
    val alpha = rng.nextDouble
    val beta = rng.nextDouble

    val a = Array.tabulate(m * k) { _ =>
      if (rng.nextDouble < 0.9) 0.0 else rng.nextDouble
    }
    val A = Matrices.dense(m, k, a).toSparse

    val B = Matrices.dense(k, n, Array.fill(k * n)(rng.nextDouble)).toDense

    val C = Matrices.dense(m, n, Array.fill(k * n)(rng.nextDouble)).toDense

    val tic1 = System.nanoTime
    Iterator.range(0, 1000).foreach { i => BLAS.gemm(alpha, A, B, beta, C) }
    val toc1 = System.nanoTime

    // scalastyle:off println
    println(f"new sparse gemm duration: ${(toc1 - tic1) * 1e-9}%.3f")
    // scalastyle:on println
  }

```


results:  master: 92.080;          this pr: 79.319

**Comment by zhengruifeng** [comment]
image

**Comment by zhengruifeng** [comment]
friendly ping @srowen

**Review by srowen — APPROVED** [review]

**Comment by zhengruifeng** [comment]
retest this please

**Comment by zhengruifeng** [comment]
Merged to master, thanks @srowen for reviewing!

**Pull request closed without merging**
