### PR TITLE
[SPARK-16352] Spark daemon run.sh

### PR DESCRIPTION
**Pull request by zasdfgbnm**
## What changes were proposed in this pull request?

I add some shell scripts to support running master and slave foreground, which makes it more convenient to write systemd service and run on HPC.
## How was this patch tested?

I test it manually and it works well on my computer

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
(I think It might be nicer if this contribution follows https://cwiki.apache.org/confluence/display/SPARK/Contributing+to+Spark)

**Comment by zasdfgbnm** [comment]
I see similar pull request here:
https://github.com/apache/spark/pull/3881

But I didn't get what happened to that and why it was closed without adding any support for running in foreground.

**Comment by srowen** [comment]
Please don't open a duplicate JIRA. You can see the discussion on the previous issue and JIRA, which is WontFix, mostly because it ultimately wasn't followed up on. It's not out of the quesiton but you should comment on the JIRA with details about why you think it's important first.

**Comment by zasdfgbnm** [comment]
I followed that PR (https://github.com/apache/spark/pull/3881)
"I was under the impression all the shell scripts were getting refactored and that this patch had become obsolete. I agree it's best to close this out." by @hellertime 

I'm not sure what happened to that. It seems that the previous PR was closed because the scripts had changed a lot before that PR was merged. 

I didn't see anything that support running in foreground and nobody mentioned in that issue that running in foreground is useless and will never be supported.

**Comment by srowen** [comment]
I'm suggesting you keep the conversation together with the original JIRA, at least. I don't know if it was going to be merged or not, but it was not updated by the author in any event.

**Comment by zasdfgbnm** [comment]
OK, but will the status of the original JIRA keep being "won't fix", if someone decide to reopen the discussion on it?
Can anyone give a comment on whether the running on foreground feature are welcome in spark upstream?
Also, if there has already been a good solution to run in foreground easily enough (so that my PR will be useless), could anyone send me a link to the document describing this?

**Pull request closed without merging**
