### PR TITLE
[MINOR][BUILD] Update Jetty to 9.3.24.v20180605

### PR DESCRIPTION
**Pull request by srowen**
## What changes were proposed in this pull request?

Update Jetty to 9.3.24.v20180605 to pick up security fix

## How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by kiszk** [comment]
Release notes
[9.3.21](https://github.com/eclipse/jetty.project/releases/tag/jetty-9.3.21.v20170918)
[9.3.22](https://github.com/eclipse/jetty.project/releases/tag/jetty-9.3.22.v20171030)
[9.3.23](https://github.com/eclipse/jetty.project/releases/tag/jetty-9.3.23.v20180228)
[9.3.24](https://github.com/eclipse/jetty.project/releases/tag/jetty-9.3.24.v20180605)

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by dongjoon-hyun** [comment]
@jerryshao . With this, are we ready for the next RC?

**Comment by kiszk** [comment]
LGTM
These changes are not huge. It looks non-risky.

**Comment by srowen** [comment]
Merged to master / 2.3

**Pull request closed without merging**
