### PR TITLE
[SPARK-31175][SQL] Avoid creating reverse comparator for each compare in InterpretedOrdering

### PR DESCRIPTION
**Pull request by Ngone51**
### What changes were proposed in this pull request?

Prpend `-` to the compare result instead of creating a new reverse comparator for each compare when sorting in DESC order in InterpretedOrdering.

### Why are the changes needed?

Currently, we'll create a new reverse comparator for each compare in InterpretedOrdering, which could generate lots of small and instant object and hurt JVM when there're plenty of data.

### Does this PR introduce any user-facing change?

No.

### How was this patch tested?

Pass Jenkins.

### CODE REVIEW

**Review by maropu — APPROVED** [review]

**Comment by Ngone51** [comment]
ping @cloud-fan @HyukjinKwon  Please take a look, thanks!

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Comment by Ngone51** [comment]
thanks all!

**Comment by dongjoon-hyun** [comment]
+1, late LGTM.

**Pull request closed without merging**
