### PR TITLE
[SPARK-37037][SQL][FOLLOWUP] Remove unused field in UTF8String

### PR DESCRIPTION
**Pull request by ulysses-you**
### What changes were proposed in this pull request?

Remove `IS_LITTLE_ENDIAN` field in `UTF8String`.

### Why are the changes needed?

After SPARK-36992 and SPARK-37037, the usage of `IS_LITTLE_ENDIAN` has been moved to `ByteArray`. The original `IS_LITTLE_ENDIAN` in `UTF8String` is unused.

### Does this PR introduce _any_ user-facing change?

no, just a code cleanup

### How was this patch tested?

Pass CI is enough

### CODE REVIEW

**Comment by itholic** [comment]
LGTM is tests pass

**Review by LuciferYang — APPROVED** [review]
LGTM (non-binding)

**Comment by ulysses-you** [comment]
thank you @itholic @LuciferYang , cc @srowen

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by ulysses-you** [comment]
thanks @HyukjinKwon !

**Pull request closed without merging**
