### PR TITLE
[MINOR][SQL] Add comments for filters values and return values of Row.get()/apply()

### PR DESCRIPTION
**Pull request by MaxGekk**
### What changes were proposed in this pull request?
- Document row field values of `DATE` and `TIMESTAMP` type returned by `Row.get()` and `Row.apply`.
- Refer to `Row.get()` from the description of filter values

### Why are the changes needed?
Reflect current behaviour of Row's method `apply()` and `get()` in comments to inform users about different return types that are depended on the SQL config settings `spark.sql.datetime.java8API.enabled`.

### Does this PR introduce any user-facing change?
No

### How was this patch tested?
Run `$ ./dev/scalastyle`

### CODE REVIEW

**Comment by MaxGekk** [comment]
@cloud-fan @HyukjinKwon Please, review the PR.

**Comment by MaxGekk** [comment]
The comment describes the default case when Java 8 date-time API is off, and it will be absolutely correct after the PR https://github.com/apache/spark/pull/28272 is merged.

**Review by HyukjinKwon — APPROVED** [review]
To me, looks fine but let me leave it to @cloud-fan

**Comment by cloud-fan** [comment]
thanks, merging to master/3.0!

**Pull request closed without merging**
