### PR TITLE
[DOC] Fixed Mesos version in doc from 0.18.1 to 0.21.0

### PR DESCRIPTION
**Pull request by sarutak**
#3934 upgraded Mesos version so we should also fix docs right?

This issue is really minor so I don't file in JIRA.

### CODE REVIEW

**Comment by andrewor14** [comment]
Ok looks good merging thanks.

**Comment by andrewor14** [comment]
Wait actually shouldn't it be 0.21.0?

**Comment by sarutak** [comment]
Oh, I'll fix very soon.

**Comment by andrewor14** [comment]
Ok cool merging thanks.

**Pull request closed without merging**
