### PR TITLE
[SPARK-29224][ML]Implement Factorization Machines as a ml-pipeline component

### PR DESCRIPTION
**Pull request by mob-ai**
### What changes were proposed in this pull request?
Implement Factorization Machines as a ml-pipeline component
1. loss function supports: logloss, mse
2. optimizer: mini batch SGD

### Why are the changes needed?
Factorization Machines is widely used in advertising and recommendation system to estimate CTR(click-through rate).
Advertising and recommendation system usually has a lot of data, so we need Spark to estimate the CTR, and Factorization Machines are common ml model to estimate CTR.
References:
1. S. Rendle, “Factorization machines,” in Proceedings of IEEE International Conference on Data Mining (ICDM), pp. 995–1000, 2010.
https://www.csie.ntu.edu.tw/~b97053/paper/Rendle2010FM.pdf

### Does this PR introduce any user-facing change?
No

### How was this patch tested?
run unit tests

### CODE REVIEW

**Comment by mob-ai** [comment]
Hi, @srowen @zhengruifeng could you please review this PR? thank you!

**Review by srowen — COMMENTED** [review]
You would have to open this vs `master`, not `branch-2.4`, and also include a Python implementation, to start

**Comment by mob-ai** [comment]
> You would have to open this vs `master`, not `branch-2.4`, and also include a Python implementation, to start

ok. I will fix it. Thank you!

**Comment by zhengruifeng** [comment]
@mob-ai Thanks for this work!
But before you continue, I guess you can refer to previous dicsussion [SPARK-7008](https://issues.apache.org/jira/browse/SPARK-7008). I think you should provide some information like convergence curves on common datasets, and proof that mini-batch SGD is a good choice as an efficient solver.
As to the PR itself, besides owen's comments, I think there should be `FMClassifier` & `FMRegressor` respectively.

**Comment by mob-ai** [comment]
> @mob-ai Thanks for this work!
> But before you continue, I guess you can refer to previous dicsussion [SPARK-7008](https://issues.apache.org/jira/browse/SPARK-7008). I think you should provide some information like convergence curves on common datasets, and proof that mini-batch SGD is a good choice as an efficient solver.
> As to the PR itself, besides owen's comments, I think there should be `FMClassifier` & `FMRegressor` respectively.

Thank you for your suggests. I will test FM use public datasets.

**Comment by srowen** [comment]
See https://github.com/apache/spark/pull/26124

**Pull request closed without merging**
