### PR TITLE
[SPARK-39562][SQL][TESTS][FOLLOWUP] Use Utils.localCanonicalHostName instead of localHostNameForURI for IP v6 testing

### PR DESCRIPTION
**Pull request by cloud-fan**
### What changes were proposed in this pull request?

This is a followup of https://github.com/apache/spark/pull/36961 , to use a different way to get localhost, so that we can run tests in AWS EC2. The reason is already explained in https://github.com/apache/spark/pull/37377

### Why are the changes needed?

run tests on cloud

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

N/A

### CODE REVIEW

**Comment by cloud-fan** [comment]
cc @dongjoon-hyun @HeartSaVioR

**Review by HyukjinKwon — APPROVED** [review]

**Review by HeartSaVioR — APPROVED** [review]
+1 assuming the test failed with EC2 and you've tested the PR against EC2 already.

**Review by dongjoon-hyun — APPROVED** [review]
> +1 assuming the test failed with EC2 and you've tested the PR against EC2 already.

Is this true, @cloud-fan ? If then, +1.

**Comment by dongjoon-hyun** [comment]
I saw https://github.com/apache/spark/pull/36961#discussion_r954804814 . Merged to master. Thank you all!

**Pull request closed without merging**
