### PR TITLE
[SPARK-36046][SQL][FOLLOWUP] Implement prettyName for MakeTimestampNTZ and MakeTimestampLTZ

### PR DESCRIPTION
**Pull request by beliefer**
### What changes were proposed in this pull request?
This PR follows https://github.com/apache/spark/pull/33299 and implement `prettyName` for `MakeTimestampNTZ` and `MakeTimestampLTZ` based on the discussion show below
https://github.com/apache/spark/pull/33299/files#r668423810

### Why are the changes needed?
This PR fix the incorrect alias usecase.

### Does this PR introduce _any_ user-facing change?
'No'.
Modifications are transparent to users.

### How was this patch tested?
Jenkins test.

### CODE REVIEW

**Review by gengliangwang — APPROVED** [review]

**Comment by gengliangwang** [comment]
> This PR fix the incorrect alias usecase.

@beliefer I wouldn't say that is incorrect..implementing `prettyName` is more reliable.

**Comment by beliefer** [comment]
> > This PR fix the incorrect alias usecase.
> 
> @beliefer I wouldn't say that is incorrect..implementing `prettyName` is more reliable.

OK. I updated the description.

**Review by HyukjinKwon — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]

**Comment by gengliangwang** [comment]
Thanks, merging to master/branch-3.2

**Comment by beliefer** [comment]
@gengliangwang Thank you for review.
@HyukjinKwon @dongjoon-hyun Thank you too.

**Pull request closed without merging**
