### PR TITLE
[Minor][DOC] Minor typo fixes

### PR DESCRIPTION
**Pull request by zhengruifeng**
## What changes were proposed in this pull request?

Minor typo fixes
## How was this patch tested?

local build

### CODE REVIEW

**Comment by srowen** [comment]
OK, that's pretty trivial. Can you take a pass over other related files for typos and formatting problems?

**Comment by zhengruifeng** [comment]
Jenkins test this please

**Comment by rxin** [comment]
@zhengruifeng Thanks. While the double space isn't ideal, it isn't wrong either. Merging this right before the code freeze can cause a lot of merge conflicts with other pull requests that are actually addressing bugs or finalizing features. I think this is still good to do, but perhaps towards the end of the QA cycle.

**Comment by zhengruifeng** [comment]
@rxin The PR was first created to fix errors in Dataset.scala doc. What about updating this PR by remove changes in other files?

**Comment by rxin** [comment]
LGTM pending jenkins.

**Comment by rxin** [comment]
Merging in master. Thanks!

**Pull request closed without merging**
