### PR TITLE
[SPARK-14900][ML][PySpark] Add accuracy and deprecate precison,recall,f1

### PR DESCRIPTION
**Pull request by zhengruifeng**
## What changes were proposed in this pull request?

1, add accuracy for MulticlassMetrics
2, deprecate overall precision,recall,f1 and recommend accuracy usage
## How was this patch tested?

manual tests in pyspark shell

### CODE REVIEW

**Comment by zhengruifeng** [comment]
```
>>> from pyspark.mllib.evaluation import *
>>> predictionAndLabels = sc.parallelize([(0.0, 0.0), (0.0, 1.0), (0.0, 0.0), (1.0, 0.0), (1.0, 1.0), (1.0, 1.0), (1.0, 1.0), (2.0, 2.0), (2.0, 0.0)])
>>> metrics = MulticlassMetrics(predictionAndLabels)
>>> metrics.recall()
/Users/zrf/Development/OpenSource/spark/python/pyspark/mllib/evaluation.py:253: UserWarning: Deprecated in 2.0.0. Use accuracy.
  warnings.warn("Deprecated in 2.0.0. Use accuracy.")
0.6666666666666666                                                              
>>> metrics.recall(0)
0.5
>>> metrics.accuracy()
0.6666666666666666
```

**Comment by zhengruifeng** [comment]
cc @srowen

**Comment by srowen** [comment]
Looks correct, what are you pointing out?

**Comment by zhengruifeng** [comment]
@srowen It is just the local test code, please ignore it.

**Comment by srowen** [comment]
LGTM

**Comment by srowen** [comment]
Merged to master/2.0

**Pull request closed without merging**
