### PR TITLE
[WIP][SPARK-40597][CORE] local mode should respect TASK_MAX_FAILURES like all other cluster managers

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

The local modes w/o explicitly num of task failures option specified is currently hard coded to 1. The resilience in such scenarios can not be assured by default.

We shall let it respect the user's configuration `spark.task.maxFailures`

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

ing

### CODE REVIEW

**Comment by mridulm** [comment]
The reason to retry on failures is the inherent nature of distributed computation - which does not apply in local mode.
What is the scenario where we are looking for this change to be useful ?

**Comment by yaooqinn** [comment]
> What is the scenario where we are looking for this change to be useful ?

accessing distributed data from distribute storage w/ local mode.

**Comment by mridulm** [comment]
That is an interesting usecase @yaooqinn :-)
Any high level thoughts on this @Ngone51, @tgravescs ?

**Comment by tgravescs** [comment]
I don't have a strong opinion, there is already the LOCAL_N_FAILURES_REGEX mode that could just be used.  why not just use that?

If we do this I think the default in local mode should still be 1. Else I'm guessing it will break some tests or at least the assumption of some tests

**Comment by mridulm** [comment]
I prefer @tgravescs's suggestion of using `LOCAL_N_FAILURES_REGEX` for this - and keep `local` mode unchanged.
Had forgotten about it !

**Comment by yaooqinn** [comment]
OK, Let's keep it AS-IS.

**Pull request closed without merging**
