### PR TITLE
[SPARK-16158][CORE][WIP] Make dynamic allocation heuristics pluggable

### PR DESCRIPTION
**Pull request by nezihyigitbasi**
## What changes were proposed in this pull request?

This WIP PR makes it possible to plug in custom dynamic allocation heuristics. I refactored the existing logic, moved things around and exposed some interfaces/config variables to enable this feature. I wanted to open this PR to get some feedback moving forward.
## How was this patch tested?

With existing unit tests and manual tests with several Spark applications that we have.

/cc @andrewor14

### CODE REVIEW

**Comment by rxin** [comment]
What do we need to do to push this forward? I probably wouldn't create a new top level package just for this api.

**Comment by nezihyigitbasi** [comment]
@rxin I need to rebase, do more testing with all the new changes since my PR, and someone should review it.

**Comment by jiangxb1987** [comment]
Are you still working on this? @nezihyigitbasi

**Comment by nezihyigitbasi** [comment]
@jiangxb1987 nope, I am not. Please go ahead if you want to take it over.

**Comment by vanzin** [comment]
@nezihyigitbasi if you're not working on it please close the PR.

**Pull request closed without merging**
