### PR TITLE
[SPARK-9487] Use the same num. worker threads in Scala/Python unit tests

### PR DESCRIPTION
**Pull request by skanjila**
## What changes were proposed in this pull request?

Changed a set of test files in core directory to use local[4](Please fill in changes proposed in this fix)
## How was this patch tested?

Ran unit tests in core, all passed
(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)
(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

Please review https://cwiki.apache.org/confluence/display/SPARK/Contributing+to+Spark before opening a pull request.

### CODE REVIEW

**Comment by srowen** [comment]
There are a lot more places that would need to change, yes.

**Comment by srowen** [comment]
Jenkins test this please

**Comment by HyukjinKwon** [comment]
(Yes, I guess we should fix many tests too. As far as I remember, many tests are dependent on the default partition number if I remember correctly.)

**Comment by skanjila** [comment]
One step at a time, first lets get the unit tests all working with local[4] in python and scala, I just added a bunch of new commits in unit tests in ml package, once I get the green light I will add python and other tests.


________________________________

**Comment by srowen** [comment]
This needs a rebase before it can be retested. Also please fix the description to remove the boilerplate text.

**Comment by skanjila** [comment]
Sean,
Just confirming when you say needs a rebase, are you saying rebase the changes I have in my branch (namely spark-9487] onto my master branch that I have forked from the main spark repo, just want to make sure I understand the details.
Thanks

**Comment by HyukjinKwon** [comment]
@skanjila It seems something gone wrong. Could you please rebase this?

**Comment by srowen** [comment]
Yeah, you may need to make a new PR to clean this up; this now has a bunch of unrelated changes. The normal procedure for rebasing is to change to your `master` branch, `git pull upstream master`, then switch to your branch and `git rebase master`.

**Comment by skanjila** [comment]
@srowen The steps you describe is exactly what I did, except 1 part, I think I accidentally pointed my master branch to the origin of the upstream master branch which brought in all these changes, I will create a new pull request at this point and move my changes there

**Comment by srowen** [comment]
@skanjila  please close this PR

**Pull request closed without merging**
