### PR TITLE
[SPARK-37842][SQL] Use `multi-catch` to simplify duplicate exception handling behavior in Java code

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
Java 7 began to support the `Multiple exception catching`, This pr uses it to simplify exception handling in Java code.

**Before**

```java
} catch (FirstException ex) {
     logger.error(ex);
     throw ex;
} catch (SecondException ex) {
     logger.error(ex);
     throw ex;
}
```

**After**

```java
} catch (FirstException | SecondException ex) {
    logger.error(ex);
    throw ex;
}
```

### Why are the changes needed?
Code simplification

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass GA

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
@LuciferYang . We don't specify the JIRA's priority in the PR title.
`[MINOR]` is used instead of `[SPARK-XXXXX]` because we don't have a JIRA ID.

**Comment by srowen** [comment]
These are good changes, but, these are changes to copied Hive code. We can 'fix' it but might introduce tiny differences and merge conflicts if we update the Hive code. 

Are there any instances in the Spark code (not in org.apache.hive)? those would be fine to change.

**Comment by LuciferYang** [comment]
> @LuciferYang . We don't specify the JIRA's priority in the PR title.
[MINOR] is used instead of [SPARK-XXXXX] because we don't have a JIRA ID.

Thank you for your explanation

**Comment by LuciferYang** [comment]
@srowen I check that all cases are in `thriftserver` module,  if there is a possibility of conflict, I can close this pr

**Comment by dongjoon-hyun** [comment]
+1, late LGTM. Thank you all!

**Pull request closed without merging**
