### PR TITLE
[SPARK-19994] [HOTFIX] [BRANCH-2.0] Change InnerLike to Inner

### PR DESCRIPTION
**Pull request by wzhfy**
## What changes were proposed in this pull request?

InnerLike => Inner

## How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by wzhfy** [comment]
cc @HyukjinKwon @cloud-fan

**Comment by hvanhovell** [comment]
LGTM

**Comment by cloud-fan** [comment]
LGTM

**Comment by hvanhovell** [comment]
Merging to branch-2.0. Thanks! Can you close?

**Pull request closed without merging**
