### PR TITLE
[SPARK-14464] [MLLIB] Better support for logistic regression when features are sparse

### PR DESCRIPTION
**Pull request by daniel-siegmann-aol**
## What changes were proposed in this pull request?

Where aggregations were being done against feature vectors, replaced the use of arrays with a new `VectorBuilder` class. This class has both dense and sparse implementations, similar to the existing `Vector` class. The dense implementation is essentially a wrapper around an array, while the sparse implementation uses a hashmap. This allows values to be aggregated into the structure (cannot be done with the existing `SparseVector`).

Aggregations are dense by default. There is a new parameter on `LogisticRegression` called `useSparseAgg` to specify that sparse implementations should be used for aggregation; otherwise behavior should be identical to before this PR. Note that this value had to be added to the constructor of `MultivariateOnlineSummarizer` as well, although a default was set so it will not break existing code - WARNING this may break binary compatibility, although this is developer API so I don't expect that to be a problem.

Aside from the new `VectorBuilder` class and the new `useSparseAgg` parameter, the changes are largely line-for-line mapping from using arrays to the new vector builders.

This change was made with the intention of having zero impact for anyone who doesn't explicitly opt in by setting the `useSparseAgg` parameter to true.

While this change has been made only for logistic regression, it is likely the same technique could be applied to other estimators.
## How was this patch tested?

Unit tests added, existing unit tests pass.

The original version of these changes I made by copying some code into my own project and making the changes I needed. These were tested on my production training flow with a few different settings to do verify the performance improvements. Additionally, I attempted to verify this does not degrade performance with dense aggregation, and while it didn't seem to I did not test this thoroughly.

Spark doesn't build on my machine (even on master) so I cannot verify that everything works. I'm not sure what tests exist to defend against performance regressions, but I assume there are some that will be run before the pull request is merged. If there are additional tests that need to be created for the sparse aggregation case, please let me know.

Also, please note that this is the first patch I have attempted to submit to Spark. Please do give my code a careful review.
## Reviewers

PR submission guidelines suggest mentioning some of the committers to the relevant code. Some of those people include @mengxr @dbtsai @jkbradley . Apologies if I missed anyone important.
## Copyright

These changes are copyright AOL, Inc. (my employer). I have received permission to distribute them under the Apache license, as required by the Apache Spark project.

### CODE REVIEW

**Comment by daniel-siegmann-aol** [comment]
I should mention Nick Pentreath pointed me in the right direction on the dev list. So, credit to him for the help!

**Comment by dbtsai** [comment]
Jenkins, ok to test.

**Comment by daniel-siegmann-aol** [comment]
Binary compatibility check failed:
method this()Unit in class org.apache.spark.mllib.stat.MultivariateOnlineSummarizer does not have a correspondent in current version

This is expected. There was no constructor defined on that class originally (there were no parameters) and I added one. There is a default value, so it is source compatible (all existing code compiles without changes).

Is there anything to be done about this? I don't believe this functionality can be cleanly implemented without this change. The only alternative I can think of is to make a copy of `MultivariateOnlineSummarizer`, which would involve duplicating a lot of code - obviously undesirable.

**Comment by dbtsai** [comment]
You need to manually add it into MiMa exclude.

**Comment by dbtsai** [comment]
Make it build first, and then we can start to review the code. Thanks.

**Comment by dbtsai** [comment]
Can you also post the benchmark result with/without this PR for very sparse features? Thanks.

**Comment by daniel-siegmann-aol** [comment]
Is there some Spark benchmark you want me to run?

**Comment by dbtsai** [comment]
You may use some fake data to demonstrate how this PR improves. Thanks.

**Comment by daniel-siegmann-aol** [comment]
I'll give the results of my own training flow too. Testing was done on EMR 4.4.0 with Spark 1.6.0. The cluster was configured with six r3.8xlarge nodes: one master, two core, three task.

Here's my original configuration. Note the driver needs a lot of memory, since there features vector size is ~ 20 million). Also note that there are only 10 executors used, because 100+ executors would increase the training time over 10 hours.

```
    --conf spark.driver.memory=128g
    --conf spark.driver.maxResultSize=112g
    --conf spark.executor.instances=10
    --conf spark.executor.memory=16g
    --conf spark.yarn.executor.memoryOverhead=2048
    --conf spark.default.parallelism=10
    --conf spark.sql.shuffle.partitions=10
```
For these numbers, the first aggregation is done in the `MultivariateOnlineSummarizer`, while the subsequent aggregations are done in the `LogisticAggregator` (a private class in `LogisticRegression`).

**Original**
Total time: 1.3 hours
First agg. time: 13 minutes
Other agg. time: 2.1 - 2.5 minutes

**With Sparse Aggregation**
Total time: 10 minutes
First agg. time: 31 seconds
Other agg. time: 4 - 10 seconds

Additionally, with sparse aggregation, increasing to 100 executors did not increase (or decrease) execution time. Memory could also be reduced - I tested with 8 GB on driver with no problem.

**Comment by daniel-siegmann-aol** [comment]
Note those results above are the results from my production data. For comparison, I'm told by one of our data scientists the training can be done locally with Liblinear in a few minutes.

**Comment by dbtsai** [comment]
Seems to be very promising. Since 2.0 window will be closed soon, it's unlikely to get into 2.0. Let's target 2.1

**Comment by daniel-siegmann-aol** [comment]
Thanks. I'm pretty confident this does what it's suppose to do, my main concern is to make sure performance doesn't degrade for anything else.

The test failure doesn't appear to be related to any of my changes. Can you confirm? Should the tests be rerun?

**Comment by dbtsai** [comment]
Jenkins, please test it again.

**Comment by dbtsai** [comment]
test this please

**Comment by dbtsai** [comment]
Jenkins, test this please

**Comment by dbtsai** [comment]
Jenkins, retest this please

**Comment by daniel-siegmann-aol** [comment]
Good news is the previous failed test now passes. Bad news is two new tests fail: MemorySinkSuite (SQL streaming) and GraphSuite (GraphX). Neither of these appear to have anything to do with my changes.

Do you think these are just flaky tests? Should we just retest?

**Comment by MLnick** [comment]
jenkins retest this please

**Comment by daniel-siegmann-aol** [comment]
Now that the tests are passing, what's the next step? Is there anything else needed from me at this time? (Please forgive my ignorance, this is the first PR I've done.)

**Comment by dbtsai** [comment]
Currently, we're working on 2.0 release. Please ping us again after the release.

**Comment by daniel-siegmann-aol** [comment]
Will do. Thank you for your help!

**Comment by MLnick** [comment]
@daniel-siegmann-aol I think it's a good time to update this PR.

**Comment by MLnick** [comment]
@daniel-siegmann-aol will you have time to work on this? I think it will be important to have this in Spark 2.1. If not, I think between @dbtsai, @sethah and myself we can help take it forward.

**Comment by daniel-siegmann-aol** [comment]
I'll work on merging the changes. However, I no longer work at AOL so I don't have the data to do thoroughly test it.

**Comment by MLnick** [comment]
@daniel-siegmann-aol ok - I think between @dbtsai and me we can run some performance tests. I've been doing some work on Criteo Display Ad Challenge data which makes a nice sparse benchmark dataset.

**Comment by sethah** [comment]
I believe the `VectorBuilder` class should be a part of the new ML linalg library (which maybe didn't exist when this was created?) instead of MLlib.

**Comment by dbtsai** [comment]
I'm benchmarking LOR with 14M features of internal company dataset (unfortunately, it's not public). 

Regrading using sparse data structure for aggregation, I'm not so sure how much this will improve the performance. Since after computing the gradient sum for all the data in one partitions, the gradient vector will be no longer to be very sparse. Even it's sparse, after couple depth of aggregation, it will be very dense. Also, we perform the compression in the shuffle phase, so if there are sparse, even it's in dense vector representation, the vector should take around the same size as sparse representation. We may need to do more investigation on this to understand how much performance we can gain in practice by using sparse vector for aggregating the gradients.

**Comment by HyukjinKwon** [comment]
@daniel-siegmann-aol I would rather like to propose to close this if there is no explicit argument against ^.

**Comment by daniel-siegmann-aol** [comment]
Sorry for the delay, I had forgotten about this.

@dbtsai this patch will only help in the case where most of your feature weights are zero _after_ aggregation. As I mentioned in a previous comment:

> The vectors size is ~20 million, but there are only 7-8 thousand features with non-zero values.

Of course that can also be worked around by scanning through the data to find the indices actually used, and mapping the features to smaller indices. It just requires an extra step.

I do not think this is a common case, and probably is not going to help many people. Even AOL doesn't need this anymore.

Given that I left AOL last year and no longer have access to any data on which to test this patch, I don't feel comfortable merging it. If anyone in the future finds this PR and would be interested in getting this patched merged, please feel free to ping me.

I do appreciate the help with this issue. Sorry it didn't lead to anything.

**Comment by sethah** [comment]
@daniel-siegmann-aol Good points, and thanks for following up on this.

**Pull request closed without merging**
