### PR TITLE
[SPARK-26852][PYTHON] Add absolute transform to CrossValidator

### PR DESCRIPTION
**Pull request by bgweber**
## What changes were proposed in this pull request?

Updates to the `Evaluator` and `CrossValidation` classes to support an absolute transform on metrics.

## How was this patch tested?

I cloned from the following branch:

```bash
git clone --single-branch --branch bgweber-abs-evaluator https://github.com/bgweber/spark.git
```

And ran `./dev/run-tests`

```
========================================================================
Running Python style checks
========================================================================
starting python compilation test...
python compilation succeeded.

downloading pycodestyle from https://raw.githubusercontent.com/PyCQA/pycodestyle/2.4.0/pycodestyle.py...
starting pycodestyle test...
pycodestyle checks passed.

starting flake8 test...
flake8 checks passed.

The pydocstyle command was not found. Skipping pydocstyle checks for now.

The sphinx-build command was not found. Skipping pydoc checks for now.


all lint-python tests passed!
```

### CODE REVIEW

**Comment by holdenk** [comment]
Jenkins, ok to test.
Thanks for working on this @bgweber and welcome to the Spark project! I'd really like to see a test for the new functionality so we know it's both correct and also that the API we're exposing is easily usable.

**Comment by srowen** [comment]
Wouldn't you just want to return the absolute value of this metric, if your goal is to minimize the absolute value? These are error-like metrics, right -- those are inherently nonnegative. Or else what's an example of a metric that is properly negative sometimes but needs to be close to 0 ideally? i'm not sure I see the use case here.

**Comment by bgweber** [comment]
@holdenk I'll put together a test case.

@srowen This likely only happens when you want to average the error over multiple predictions. I provided an example of a custom evaluator where this is useful in the Jira ticket: https://issues.apache.org/jira/browse/SPARK-26852
However, I acknowledge this might be too specific of a use case.

**Comment by srowen** [comment]
In that case aren't you returning MAE = mean absolute error? You don't want to average the errors, but their magnitude -- or else large errors would cancel out and look 'good'. Those are nonnegative so the smallest MAE is also the one closest to 0.

**Comment by srowen** [comment]
Reopen if you think this I've really misunderstood the use case.

**Comment by bgweber** [comment]
Not a misunderstanding, thanks for checking out the suggestion. I had a use case where I wanted the large losses to cancel out and look good, since I was measuring performance across a group of estimations. However, upon further testing it looks like this results in worse performance.

I'm going to try using  RMSE instead of MAE in the _fit function.

**Comment by srowen** [comment]
MAE should also work in this regard as it would regard large negative losses as 'large' too. RMSE does as well of course.

**Pull request closed without merging**
