### PR TITLE
[SPARK-10008] Ensure shuffle locality doesn't take precedence over narrow deps

### PR DESCRIPTION
**Pull request by mateiz**
The shuffle locality patch made the DAGScheduler aware of shuffle data,
but for RDDs that have both narrow and shuffle dependencies, it can
cause them to place tasks based on the shuffle dependency instead of the
narrow one. This case is common in iterative join-based algorithms like
PageRank and ALS, where one RDD is hash-partitioned and one isn't.

### CODE REVIEW

**Comment by mateiz** [comment]
@shivaram here it is.. we should merge this into branch-1.5 too if it's good.

**Comment by shivaram** [comment]
Jenkins, retest this please

**Comment by shivaram** [comment]
LGTM. I think we should merge this into `branch-1.5` as well.

**Comment by shivaram** [comment]
Jenkins, retest this please

**Comment by mateiz** [comment]
Sounds good.. I'll merge it once tests pass.

**Pull request closed without merging**
