### PR TITLE
[SPARK-28551][SQL]Add a Checker Rule when CTAS SQL with LOCATION 

### PR DESCRIPTION
**Pull request by AngersZhuuuu**
## What changes were proposed in this pull request?

When we run SQL like 

`CRETE TABLE TBL `
`LOCATION 'PATH_URI`
`AS`
`SELECT QUERY `
It won't check PATH_URI status, if there is some data under this path, it will just overwrite this path.

If user careless write a path with important data store under the path, it will be a disaster。 

So I wish to add a checker rule in PreWriteChecker to avoid this situation happens

## How was this patch tested?
UT & MT

### CODE REVIEW

**Comment by maropu** [comment]
`IF NOT EXISTS` doesn't work for the case?

**Comment by AngersZhuuuu** [comment]
> `IF NOT EXISTS` doesn't work for the case?

Won't work for this problem, and only this type sql cause this problem

**Comment by AngersZhuuuu** [comment]
gentle ping @wangyum @juliuszsompolski 
I have make a big mistake with this probelm. Do you think it's necessary to add a checker for this.

**Comment by AngersZhuuuu** [comment]
@dongjoon-hyun 
Why this open and re-closed.  0.0

**Comment by dongjoon-hyun** [comment]
Hi, @AngersZhuuuu .

1. Initially, the bot closed this PR on December because there had been no activity for prior 3 months.
2. While I audited all JIRAs for Apache Spark 3.0, I revisited SPARK-28551 and reopened this PR (9 days ago) since the goal itself looks reasonable to me in some way.
3. However, the bot closed this at the next day (8 days ago) automatically because the `Stale` label still exists in this PR.

The above is the current situation. If you want, I can reopen this again and remove the `Stale` tag. That will make this PR alive for the other reviewers (including committers) for next more months.

**Comment by AngersZhuuuu** [comment]
@dongjoon-hyun 
Got it.
I think is really important, recently one of our user use CTAS cover a database's data again because of this pr's case.

Maybe we can reopen it and discuss this problem again.

**Comment by dongjoon-hyun** [comment]
Sure~ I agree.

**Comment by dongjoon-hyun** [comment]
BTW, could you resolve the conflicts?

**Comment by dongjoon-hyun** [comment]
ok to test

**Comment by wangyum** [comment]
1. We'd better be consistent with Hive's behavior:
https://github.com/apache/hive/blob/cf64bb9d4b280b433db82a93ceace1a6091a0506/ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java#L12132-L12134
2. Data source table also need this check, right?

**Comment by AngersZhuuuu** [comment]
> 1. We'd better be consistent with Hive's behavior:
>    https://github.com/apache/hive/blob/cf64bb9d4b280b433db82a93ceace1a6091a0506/ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java#L12132-L12134
> 2. Data source table also need this checker, right?

thought a lot, spark is different, since it support saveAsTable with append mode, so if table exists, we don't need to check.

Sure, DataSource Table need do same thing, I will add this part after I have checked DataSource table write method.

**Comment by AngersZhuuuu** [comment]
After detail check(not notice before):

1. CREATE EXTERNAL TABLE AS SELECT must have LOCATION  and SERDE, the  Spark Plan will be  `OptimizedCreateHiveTableAsSelectCommand` or `CreateHiveTableAsSelectCommand`, and it won't check and overwrite  existed data in location
2. CTAS with LOCATION will be EXTERNAL table  with SERDE will be Hive serde table , SparkPlan will be  `OptimizedCreateHiveTableAsSelectCommand` or `CreateHiveTableAsSelectCommand`, and it won't check and overwrite  existed data in location
3. CTAS with LOCATION will be EXTERNAL table  without SERDE will be datasource table , SparkPlan will be  `CreateDataSourceTableAsSelectCommand`, and it won't check and overwrite  existed data in location
4. Whether it's datasource table or hive serde table, if it's Managed table. it's path will be checked  
when create table metedata in SessionCatalog.

So we only need to care about external table , and external table 's location need to be checked since when CTAS, it will rewrite all data in specified path.

If some user make wrong path and  run this kind of SQL, will rewrite all data.

**Comment by AngersZhuuuu** [comment]
@dongjoon-hyun 
Latest UT test seems not my code's problem, can you help to retest again?

**Comment by AngersZhuuuu** [comment]
retest this please

**Comment by AngersZhuuuu** [comment]
retest this please

**Comment by AngersZhuuuu** [comment]
retest this please

**Comment by AngersZhuuuu** [comment]
retest this please

**Comment by AngersZhuuuu** [comment]
retest this please

**Pull request closed without merging**
