### PR TITLE
[Followup SPARK-8387][WEBUI] Update driver log URL to show only 4096 bytes

### PR DESCRIPTION
**Pull request by carsonwang**
This is to follow up #6834 , update the driver log URL as well for consistency.

### CODE REVIEW

**Comment by srowen** [comment]
Do you need to update `YarnClusterSuite` too? looks like it expects start=0

**Comment by carsonwang** [comment]
Thanks for the reminder, @srowen !  The url in `YarnClusterSuite` is now updated.

**Comment by harishreedharan** [comment]
As long as -4096 works (I didn't test this), this LGTM.

**Comment by andrewor14** [comment]
LGTM, merging into master.

**Pull request closed without merging**
