### PR TITLE
[SPARK-43994][BUILD] Upgrade zstd-jni to 1.5.5-4

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
This pr aims upgrade `zstd-jni` from 1.5.5-3 to 1.5.5-4.

### Why are the changes needed?
New version includes a bug fixed
[Fix bug in ZstdBufferDecompressingStream when array backing ByteBuffer](https://github.com/luben/zstd-jni/commit/355b8511a2967d097a619047a579930cac2ccd9d)
    
Other changes as follows:
- https://github.com/luben/zstd-jni/compare/v1.5.5-3...v1.5.5-4

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass GA.

### CODE REVIEW

**Comment by panbingkun** [comment]
@dongjoon-hyun shall we also hold on it until July 10st?

**Comment by LuciferYang** [comment]
Need to update `ZStandardBenchmark` result :)

**Comment by panbingkun** [comment]
JDK 8: https://github.com/panbingkun/spark/actions/runs/5200739435
JDK 11: https://github.com/panbingkun/spark/actions/runs/5200742500
JDK 17: https://github.com/panbingkun/spark/actions/runs/5200745882

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

No, this one is okay because this dependency doesn't show that kind of frequent update., @panbingkun 
> shall we also hold on it until July 10st?

**Review by LuciferYang — APPROVED** [review]
+1, LGTM

**Comment by LuciferYang** [comment]
Merged to master. Thanks @dongjoon-hyun @panbingkun

**Comment by dongjoon-hyun** [comment]
Thank you, @LuciferYang and @panbingkun .

**Pull request closed without merging**
