### PR TITLE
[SPARK-28773][DOC][SQL] Handling of NULL data in Spark SQL

### PR DESCRIPTION
**Pull request by dilipbiswal**
### What changes were proposed in this pull request?
Document ```NULL``` semantics in SQL Reference Guide. 

### Why are the changes needed?
Currently Spark lacks documentation on how `NULL` data is handled in various expressions and operators. This is aimed at addressing this issue.

### Does this PR introduce any user-facing change?
Yes. 
**Before:**
There was no documentation for this.

**After.**
Screen Shot 2019-09-08 at 11 24 41 PM
Screen Shot 2019-09-08 at 11 24 56 PM
Screen Shot 2019-09-08 at 11 25 08 PM
Screen Shot 2019-09-08 at 11 25 24 PM
Screen Shot 2019-09-08 at 11 25 34 PM
Screen Shot 2019-09-08 at 11 25 49 PM
Screen Shot 2019-09-08 at 11 26 00 PM
Screen Shot 2019-09-08 at 11 26 09 PM
Screen Shot 2019-09-08 at 11 26 20 PM
Screen Shot 2019-09-08 at 11 26 32 PM
Screen Shot 2019-09-08 at 11 26 47 PM
Screen Shot 2019-09-08 at 11 26 59 PM
Screen Shot 2019-09-08 at 11 27 10 PM
Screen Shot 2019-09-08 at 11 27 18 PM
Screen Shot 2019-09-08 at 11 27 27 PM
Screen Shot 2019-09-08 at 11 27 37 PM
Screen Shot 2019-09-08 at 11 27 48 PM
Screen Shot 2019-09-08 at 11 27 59 PM
Screen Shot 2019-09-08 at 11 28 08 PM
Screen Shot 2019-09-08 at 11 28 20 PM

### How was this patch tested?
Tested using jykyll build --serve

### CODE REVIEW

**Comment by dilipbiswal** [comment]
cc @gatorsmile

**Comment by dilipbiswal** [comment]
@gatorsmile Many thanks for correcting the doc. It looks fine to me.

**Comment by gatorsmile** [comment]
Thanks! Merged to master

**Comment by dilipbiswal** [comment]
@gatorsmile Thanks a LOT for your help with the writeup.

**Pull request closed without merging**
