### PR TITLE
[SPARK-29253][SQL] Add agg(String, String*) to Dataset

### PR DESCRIPTION
**Pull request by TomokoKomiyama**
### What changes were proposed in this pull request?
Add agg(String, String*) and its test.

### Why are the changes needed?
Other API (filter, select...etc) can use both of Column and String on argument, butagg() was not able to use String on argument.
I think agg() should be able to use Column on argument, too.

Ex.)
[ Before ] We can use String in groupBy(), but we should use Column in agg().
`df.groupBy("_1").agg($"_2")`

[ After ] We can use String both of in groupBy() and agg().
`df.groupBy("_1").agg("_2")`

### Does this PR introduce any user-facing change?
Yes.
Users can use agg(String, String*).

### How was this patch tested?
Added test case to DataFrameAggregateSuite.scala .

### CODE REVIEW

**Review by HyukjinKwon — COMMENTED** [review]
I think it already can be easily worked around as you described in PR description. Let's don't add APIs just to be consistent.

**Comment by TomokoKomiyama** [comment]
@HyukjinKwon I'm not sure why `select(Column)`, `select(String)`, `filter(Column)` and `filter(String)` work, but `agg(String)` doesn't work?
I think it needs to add `agg(String)` to be consistent with `select()` and `filter()`.

**Comment by HyukjinKwon** [comment]
Those might have to be removed ideally but it's there for a legacy reason. See functions.scala's comments.

**Comment by TomokoKomiyama** [comment]
I got it.

When will these legacy functions remove?

**Comment by HyukjinKwon** [comment]
Not sure but we decided to keep it at 3.0. So it might be removed at 4.0(?)

**Comment by HyukjinKwon** [comment]
Closing this.

**Pull request closed without merging**
