### PR TITLE
[Minor][Core] Cleanup unused vals in `DAGScheduler.handleTaskCompletion`

### PR DESCRIPTION
**Pull request by jiangxb1987**
## What changes were proposed in this pull request?

Cleanup unused vals in `DAGScheduler.handleTaskCompletion` to reduce the code complexity slightly.

## How was this patch tested?

Existing test cases.

### CODE REVIEW

**Comment by jiangxb1987** [comment]
cc @cloud-fan

**Comment by cloud-fan** [comment]
retest this please

**Comment by kiszk** [comment]
retest this please

**Review by gatorsmile — COMMENTED** [review]
LGTM

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Pull request closed without merging**
