### PR TITLE
Revert "[SPARK-21428] Turn IsolatedClientLoader off while using builtin Hive jars for reusing CliSessionState

### PR DESCRIPTION
**Pull request by cloud-fan**
This reverts commit b83b502c4189c571bda776511c6f7541c6067aae.

It has a regression as reported in https://github.com/apache/spark/pull/19068#issuecomment-328260611 , seems the fix is not trivial, we should revert this commit first.

This revert has some conflicts, so try to go through jenkins to avoid to mess up something.

### CODE REVIEW

**Comment by cloud-fan** [comment]
cc @yaooqinn @jiangxb1987

**Comment by yaooqinn** [comment]
ok to me, more tests are needed on #18648

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by cloud-fan** [comment]
closing it as the regression is fixed by https://github.com/apache/spark/pull/19068

**Pull request closed without merging**
