### PR TITLE
[SPARK-35559][TEST] Speed up one test in AdaptiveQueryExecSuite

### PR DESCRIPTION
**Pull request by cloud-fan**
### What changes were proposed in this pull request?

I just noticed that `AdaptiveQueryExecSuite.SPARK-34091: Batch shuffle fetch in AQE partition coalescing` takes more than 10 minutes to finish, which is unacceptable.

This PR sets the shuffle partitions to 10 in that test, so that the test can finish with 5 seconds.

### Why are the changes needed?

speed up the test

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

N/A

### CODE REVIEW

**Review by viirya — APPROVED** [review]

**Comment by viirya** [comment]
lgtm, pending CI.

**Review by dongjoon-hyun — APPROVED** [review]
Since we need this patch at branch-3.1, I filed a JIRA issue for this. Thank you, @cloud-fan and @viirya .

**Comment by viirya** [comment]
Thank you @dongjoon-hyun

**Comment by yaooqinn** [comment]
nice catch & LGTM

**Pull request closed without merging**
