### PR TITLE
[SPARK-32886][SPARK-31882][WEBUI][2.4] fix 'undefined' link in event timeline view

### PR DESCRIPTION
**Pull request by zhli1142015**
### What changes were proposed in this pull request?

Fix [SPARK-32886](https://issues.apache.org/jira/projects/SPARK/issues/SPARK-32886) in branch-2.4. i cherry-pick [29757](https://github.com/apache/spark/pull/29757) and partial [28690](https://github.com/apache/spark/pull/28690)(test part is ignored as conflict), which PR `29757` has dependency on PR `28690`. This change fixes two below issues in branch-2.4. 
[SPARK-31882: DAG-viz is not rendered correctly with pagination.](https://issues.apache.org/jira/projects/SPARK/issues/SPARK-31882)
[SPARK-32886: '.../jobs/undefined' link from "Event Timeline" in jobs page](https://issues.apache.org/jira/projects/SPARK/issues/SPARK-32886)
### Why are the changes needed?

@sarutak found `29757` has dependency on `28690`. If we only merge `29757` to 2.4 branch, it would cause UI break. And I verified both issues mentioned in [SPARK-32886](https://issues.apache.org/jira/projects/SPARK/issues/SPARK-32886) and [SPARK-31882](https://issues.apache.org/jira/projects/SPARK/issues/SPARK-31882)  exist in branch-2.4. So i cherry pick them to branch 2.4 in same PR.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Manually tested.
dag
eventTLJPG

### CODE REVIEW

**Comment by zhli1142015** [comment]
@sarutak , @srowen , @dongjoon-hyun , please take a look, thanks.

**Comment by srowen** [comment]
Jenkins test this please

**Comment by srowen** [comment]
Jenkins retest this please

**Comment by sarutak** [comment]
retest this please.

**Comment by sarutak** [comment]
retest this please.

**Comment by sarutak** [comment]
I asked @shaneknapp to investigate the .m2 corruption issue on JIRA
https://issues.apache.org/jira/browse/SPARK-32153

**Comment by sarutak** [comment]
Try again.
retest this please.

**Comment by HyukjinKwon** [comment]
I think we can just use GitHub Actions build. GitHub Actions build was ported back to replace Jenkins build in branch-2.4.

It is flaky on few specific machines in Jenkins due to malformed `.m2` when you check the dependencies in branch-2.4. This is being skipped in master and branch-3.0 when it runs on Jenkins.

**Comment by HyukjinKwon** [comment]
`StreamingLogisticRegressionWithSGDTests.test_training_and_prediction` is a known flaky test. I am pretty confident we can ignore it here.

**Comment by srowen** [comment]
Jenkins retest this please

**Review by sarutak — APPROVED** [review]

**Comment by srowen** [comment]
Merged to 2.4

**Pull request closed without merging**
