### PR TITLE
[SPARK-9982] [SPARKR] SparkR DataFrame fail to return data of Decimal type

### PR DESCRIPTION
**Pull request by ashkurenko**

### CODE REVIEW

**Comment by shivaram** [comment]
Thanks @ashkurenko for the patch. Could we also add a unit test for this ?

**Comment by shivaram** [comment]
Jenkins ok to test

**Comment by shivaram** [comment]
Jenkins, retest this please

**Comment by shivaram** [comment]
@shaneknapp https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/41264/ is another one of those `target` cannot be removed failures

**Comment by shivaram** [comment]
Jenkins, retest this please

**Comment by shaneknapp** [comment]
Whoops, bad bash on my part.  I'll be in shortly and will fix that right
up.

**Comment by shivaram** [comment]
Jenkins, retest this please

**Comment by shivaram** [comment]
Jenkins, retest this please

**Comment by shivaram** [comment]
Jenkins, retest this please

**Comment by shivaram** [comment]
@davies Does this look ok to you ? If so I think we can add some more tests later and get this fix in for 1.5

**Comment by davies** [comment]
LGTM

**Comment by ashkurenko** [comment]
I am working on the unit test(s)

**Pull request closed without merging**
