### PR TITLE
[WEBUI][SPARK-17342] Style of event timeline is broken

### PR DESCRIPTION
**Pull request by sarutak**
## What changes were proposed in this pull request?

SPARK-15373 (#13158) updated the version of vis.js to 4.16.1. As of 4.0.0, some class was renamed like 'timeline to vis-timeline' but that ticket didn't care and now style is broken.

In this PR, I've restored the style by modifying `timeline-view.css` and `timeline-view.js`.
## How was this patch tested?

manual tests.

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)
- Before
  
- After

### CODE REVIEW

**Comment by robert3005** [comment]
have you seen #14791 ? Should fix the biggest offender but full clean up is definitely useful

**Comment by srowen** [comment]
@sarutak can you connect this to your JIRA in the title?

**Comment by sarutak** [comment]
@robert3005 Thanks for the information. I think the PR you informed me still doesn't restore the style to what it was.

@srowen Thanks, I forgot to do it. I've connected to corresponding JIRA.

**Comment by sarutak** [comment]
retest this please.

**Comment by sarutak** [comment]
retest this please.

**Comment by srowen** [comment]
LGTM. In light of this change, was https://github.com/apache/spark/pull/14791 necessary, or at least still a valid change?

**Comment by sarutak** [comment]
@srowen Actually, I don't think that change is necessary because [an existing setting](https://github.com/apache/spark/pull/14900/files#diff-da6276fc4ab5cb98bed11c7259b60eaeR98) encompasses that change added in #14791 .

**Comment by sarutak** [comment]
retest this please.

**Comment by srowen** [comment]
Merged to master/2.0

**Pull request closed without merging**
