### PR TITLE
[WIP][SPARK-41271][SQL] Parameterized SQL queries

### PR DESCRIPTION
**Pull request by MaxGekk**
### Why are the changes needed?
1. To improve user experience with Spark SQL via
    - Using Spark as remote service (microservice).
    - Write SQL code that will power reports, dashboards, charts and other data presentation solutions that need to account for criteria modifiable by users through an interface.
    - Build a generic integration layer based on the SQL API. The goal is to expose managed data to a wide application ecosystem with a microservice architecture. It is only natural in such a setup to ask for modular and reusable SQL code, that can be executed repeatedly with different parameter values.

2. To achieve feature parity with other systems that support named parameters:
    - Redshift: https://docs.aws.amazon.com/redshift/latest/mgmt/data-api.html#data-api-calling
    - BigQuery: https://cloud.google.com/bigquery/docs/parameterized-queries#api
    - MS DBSQL: https://learn.microsoft.com/en-us/azure/databricks/sql/user/queries/query-parameters

### Does this PR introduce _any_ user-facing change?
No, this is an extension of the existing APIs.

### How was this patch tested?
By running new tests:
```
$ build/sbt "test:testOnly *PlanParserSuite"
$ build/sbt "test:testOnly *AnalysisSuite"
$ build/sbt "test:testOnly *QueryCompilationErrorsSuite"
```

### CODE REVIEW

**Comment by xkrogen** [comment]
Can you provide more information on how this proposal compares to the behavior of other popular SQL dialects (e.g. ANSI, Postgres, MySQL, Trino, HiveQL, Snowflake)? One thing that stands out to me is that this PR only supports named parameters; I think positional parameters are more common? For example AFAIK JDBC only supports positional parameters ([ref](https://docs.oracle.com/javase/tutorial/jdbc/basics/prepared.html)).

**Comment by MaxGekk** [comment]
> Can you provide more information ... of other popular SQL dialects

@xkrogen Named parameters are supported by:
1. Redshift: https://docs.aws.amazon.com/redshift/latest/mgmt/data-api.html#data-api-calling
2. BigQuery: https://cloud.google.com/bigquery/docs/parameterized-queries#api
3. MS DBSQL: https://learn.microsoft.com/en-us/azure/databricks/sql/user/queries/query-parameters

**Comment by xkrogen** [comment]
All 3 of the examples you provided use different syntax (`:id` vs `@id` vs `{{ id }}`). Can we provide more motivation for why we are picking the syntax used in this implementation? [SQL-92 defined ANSI Dynamic SQL](https://docs.oracle.com/cd/A81042_01/DOC/appdev.816/a76942/pc_14ady.htm) which uses colons (`:id`). One other example using `:` is [SQLAlchemy](https://docs.sqlalchemy.org/en/14/core/tutorial.html#using-textual-sql). 

Other examples (besides JDBC) only supporting positional arguments:
* [Trino](https://trino.io/docs/current/sql/execute.html) & [PrestoDB](https://prestodb.io/docs/current/sql/execute.html)
* [PostgreSQL](https://www.postgresql.org/docs/current/ecpg-dynamic.html)
* [Snowflake](https://docs.snowflake.com/en/sql-reference/sql/execute-immediate.html)
* [MySQL][(https://dev.mysql.com/doc/refman/8.0/en/user-variables.html](https://dev.mysql.com/doc/refman/8.0/en/sql-prepared-statements.html)

So from what I am seeing, positional arguments (with `?` placeholders) are the most common, and when named parameters are supported, colons are the most common way to denote them (including ANSI support). I feel there is a good argument to be made that named arguments are much easier to work with than positional so I am supportive of using named args rather than positional, but I feel we should at least follow the ANSI standard and use colons rather than at-signs.

**Comment by MaxGekk** [comment]
> Can we provide more motivation for why we are picking the syntax used in this implementation?

@xkrogen The `@` marker has been chosen to make migrating from BigQuery to Spark SQL easier.

> [SQL-92 defined ANSI Dynamic SQL](https://docs.oracle.com/cd/A81042_01/DOC/appdev.816/a76942/pc_14ady.htm) which uses colons (:id).

Actually, this is just Oracle's proprietary implementation.

> I feel we should at least follow the ANSI standard and use colons rather than at-signs.

I agree that we should follow standards whenever it is possible but there are no standards for this feature so far.

**Comment by xkrogen** [comment]
> Actually, this is just Oracle's proprietary implementation.

I don't think this is true, but admittedly my knowledge of the SQL standardization process is limited, so please correct me if you find gaps in my reasoning. In the [SQL-92 standard](https://www.contrib.andrew.cmu.edu/~shadow/sql/sql1992.txt) (this is the only reference to the full standard I can find with a few minutes of searching; please let me know if you have a better source), `Dynamic SQL` is defined in section 17, and on page 98 it explicitly defines a parameter name as being prefixed by a colon:
```
         <parameter name> ::= <colon> <identifier>
```

> The `@` marker has been chosen to make migrating from BigQuery to Spark SQL easier.

This seems, to me, like a pretty shaky argument? I could just as easily say that we should choose `:` to make it easier to migrate from Redshift, or, what seems to be a strong argument based on what I found in my last comment, that we should choose positional argument support (`?`) to make it easier to migrate from Trino, PrestoDB, PosgreSQL, Snowflake, _and_ MySQL. Why are we giving BigQuery precedence here?

**Pull request closed without merging**
