### PR TITLE
[SPARK-50185][EXAMPLE][TESTS] Unify `*.sh` file naming patterns by replacing `_` with `-`

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to unify `*.sh` file naming patterns by replacing `_` with `-` because `Apache Spark` uses `-` patterns in`sbin` directory.

```bash
$ ls sbin
decommission-worker.sh  start-connect-server.sh start-workers.sh        stop-thriftserver.sh
spark-config.sh         start-history-server.sh stop-all.sh             stop-worker.sh
spark-daemon.sh         start-master.sh         stop-connect-server.sh  stop-workers.sh
spark-daemons.sh        start-thriftserver.sh   stop-history-server.sh  workers.sh
start-all.sh            start-worker.sh         stop-master.sh
```

### Why are the changes needed?

**BEFORE**
```
$ find . -name '*.sh' | grep '_' | wc -l
       6
```

**AFTER**
```
$ find . -name '*.sh' | grep '_' | wc -l
       0
```

### Does this PR introduce _any_ user-facing change?

- All files except one example file are test resources.
- The exceptional example file, `submit_pi.sh`, is a new file. So, we can change it before Spark 4.0 release.

### How was this patch tested?

Pass the CIs.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Could you review this PR, @LuciferYang ?

**Review by LuciferYang — APPROVED** [review]
+1, LGTM

**Comment by dongjoon-hyun** [comment]
Thank you, @LuciferYang .

**Review by yaooqinn — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @yaooqinn !

**Comment by dongjoon-hyun** [comment]
Since this is a trivial renaming in test resources and one example file, let me merge this. Thank you again.
Merged to master.

**Comment by panbingkun** [comment]
+1, LGTM

**Comment by dongjoon-hyun** [comment]
Thank you, @panbingkun .

**Pull request closed without merging**
