### PR TITLE
[SPARK-14906][ML] Move VectorUDT and MatrixUDT in PySpark to new ML package

### PR DESCRIPTION
**Pull request by viirya**
## What changes were proposed in this pull request?

Move the VectorUDT and MatrixUDT in PySpark to new ML package.
## How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by jkbradley** [comment]
@viirya Thanks for this PR.   I'll make a few high-level comments.

We need to keep the old pyspark.mllib.linalg APIs.  We also want to freeze the pyspark.mllib.linalg APIs, which means we need to keep that old code (not just alias it).

Can you please modify the PR to do the following:
* Keep the pyspark.mllib.linalg code
* Copy the linalg code to pyspark.ml.linalg, including unit tests
* Update the pyspark.ml.linalg code as needed to handle UDTs and make tests run

Thanks!

**Comment by viirya** [comment]
@jkbradley Thanks for your comments. I want to make sure that you said we will freeze the pyspark.mllib.linalg APIs, so do I need to change the current PySpark ml/mllib codes which use pyspark.mllib.linalg APIs to use new pyspark.ml.linalg?

I just did that. So if you mean we don't touch that, I need to revert it back. Thanks.

**Comment by viirya** [comment]
ping @jkbradley @dbtsai @mengxr

**Comment by shaneknapp** [comment]
i will retrigger this build once maintenance is over.

**Comment by shaneknapp** [comment]
jenkins, test this please

**Comment by shaneknapp** [comment]
jenkins, test this please

**Comment by mengxr** [comment]
@viirya Sorry for late response! The changes should be similar to mllib-local. The scope is not moving UDTs but copying the entire linalg package to `spark.ml`. We should leave `spark.mllib` unchanged and turn it to maintenance mode in 2.0. Do you have time to make this change? Or I can send a PR based on yours. Thanks!

**Comment by viirya** [comment]
@mengxr Currently I moved only Vector/Matrix and their UDTs to `pyspark.ml` and made `pyspark.ml` and `pyspark.mllib` codes to use moved `ml.linalg` Vector/Matrix. Besides, `pyspark.mllib` is untouched.

Do you mean that we want to keep `pyspark.mllib` codes using `pyspark.mllib.linalg` and let `pyspark.ml` codes using new `pyspark.ml.linalg`?

**Comment by viirya** [comment]
@mengxr @dbtsai Separating the pickle paths for `pyspark.ml` and `pyspark.mllib` is not possible without the changes in #12627, as it requires the Scala ML code changes as well.

I will submit another PR for this jira that only copies `pyspark.mllib.linalg` to `pyspark.ml.linalg`. When that PR is merged, I will apply the changes of python codes in this PR against #12627 by submitting a PR for it. Then I think it should solve the problem.

**Comment by viirya** [comment]
@mengxr @dbtsai That PR is at #13099.

**Comment by dbtsai** [comment]
Ping @mengxr

**Pull request closed without merging**
