### PR TITLE
[SPARK-16049][SQL] Make InsertIntoTable's expectedColumns support case-insensitive resolution properly

### PR DESCRIPTION
**Pull request by viirya**
## What changes were proposed in this pull request?

Right now, `InsertIntoTable`'s `expectedColumns` uses the method of `contains` to find static partitioning columns. When analyzer is case-insensitive, the initialization of this lazy val will not work as expected.
## How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by viirya** [comment]
ping @liancheng @yhuai @cloud-fan

**Comment by liancheng** [comment]
@viirya Could you please help verify that whether #13769 already fixed this issue?

**Comment by liancheng** [comment]
Oh, #13769 only solves case-insensitive resolution for partition columns.

**Comment by viirya** [comment]
@liancheng yes.

**Comment by viirya** [comment]
@liancheng hmm, for that part, seems so.

**Comment by liancheng** [comment]
Yea, but partitioning is only available for `HadoopFsRelation`.

**Comment by yhuai** [comment]
@viirya Thank you for the pr. After I filed the jira, I did some investigation. Actually as I noted at https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/basicLogicalOperators.scala#L372, the parser will turn the keys to their lowercase forms. So, I think there is nothing really broken assuming case-insensitive resolution is used. How about we close this PR? We need to address the case-sensitivity flag in a holistic way. We can revisit this particular issue later.

**Comment by gatorsmile** [comment]
https://github.com/apache/spark/pull/12993#issuecomment-217955839 This is the comment left by @rxin in my PR. I assume this will not be addressed in this release. Anything is changed?

**Comment by viirya** [comment]
@yhuai I've run test against current branch. When case-insensitive resolution is used, exepctedColumns is not correct actually. So I am not sure why you said it is not really broken? I will close this first because I think this approach is not good. Maybe I will try alternative one later. Thanks!

**Comment by yhuai** [comment]
@viirya Can you comment in the jira with your case?

**Comment by viirya** [comment]
@yhuai What case you meant?

**Comment by yhuai** [comment]
Tests that you mentioned in `I've run test against current branch. When case-insensitive resolution is used, exepctedColumns is not correct actually`

**Pull request closed without merging**
