### PR TITLE
[SPARK-8344] Add message processing time metric to DAGScheduler

### PR DESCRIPTION
**Pull request by JoshRosen**
This commit adds a new metric, `messageProcessingTime`, to the DAGScheduler metrics source. This metrics tracks the time taken to process messages in the scheduler's event processing loop, which is a helpful debugging aid for diagnosing performance issues in the scheduler (such as SPARK-4961).

In order to do this, I moved the creation of the DAGSchedulerSource metrics source into DAGScheduler itself, similar to how MasterSource is created and registered in Master.

### CODE REVIEW

**Comment by JoshRosen** [comment]
@aarondav, this is the metric that I mentioned.

**Comment by kayousterhout** [comment]
LGTM!

**Comment by sujkh85** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

sujkh@naver.com 님께 보내신 메일 <Re: [spark] [SPARK-8344] Add message processing time metric to DAGScheduler (#7002)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by JoshRosen** [comment]
I'm going to merge this into master.  Thanks!

**Comment by akashsethi24** [comment]
@JoshRosen  @kayousterhout  I Know this is old PR but I just want to know for messageProcessingTime value like mean, mean_rate are calculated and shown for each fresh batch or aggregated with the old mean and mean_rate?
Thanks

**Pull request closed without merging**
