### PR TITLE
[Spark-27416][SQL]UnsafeMapData & UnsafeArrayData Kryo serialization breaks when two machines have different Oops size

### PR DESCRIPTION
**Pull request by pengbo**
## What changes were proposed in this pull request?
Finish the rest work of https://github.com/apache/spark/pull/24317, https://github.com/apache/spark/pull/9030
a. Implement Kryo serialization for UnsafeArrayData
b. fix UnsafeMapData Java/Kryo Serialization issue when two machines have different Oops size
c. Move the duplicate code "getBytes()" to Utils.

## How was this patch tested?
According Units has been added & tested

### CODE REVIEW

**Comment by pengbo** [comment]
@srowen Sorry for closing https://github.com/apache/spark/pull/24340 accidentally

To Continue our discussion:

> OK do we need to add these classes to the list that is automatically registered with Kryo by default too?

I am not quite sure what's the main advantage. If that's for performance, I think in this case it makes no difference.

**Comment by srowen** [comment]
It would be for performance, for the same reason all the basic spark classes are registered; otherwise Kryo serializes the class name with each instance. Why wouldn't it matter? maybe I'm missing something

**Comment by pengbo** [comment]
> It would be for performance, for the same reason all the basic spark classes are registered; otherwise Kryo serializes the class name with each instance. Why wouldn't it matter? maybe I'm missing something

The kyro & java serialization are using the same method that's why I think it would makes no different. 
I am not quite familiar with how kyro is using in spark yet, let me know what i'm missing and the following step I can do.

Thanks

**Comment by srowen** [comment]
I'm thinking of what KryoSerializer.newKryo does; I'm guessing we should register all Unsafe Kryo-serializable classes by default

**Comment by pengbo** [comment]
@srowen done. Let me know if you have any other advice.

**Pull request closed without merging**
