### PR TITLE
[SPARK-13928] Move org.apache.spark.Logging into org.apache.spark.internal.Logging

### PR DESCRIPTION
**Pull request by cloud-fan**
## What changes were proposed in this pull request?

Logging was made private in Spark 2.0. If we move it, then users would be able to create a Logging trait themselves to avoid changing their own code.
## How was this patch tested?

existing tests.

### CODE REVIEW

**Comment by srowen** [comment]
What does this change accomplish? I wasn't clear from the JIRA

**Comment by cloud-fan** [comment]
We made the `Logging` class private and broke user code. To minimize the code change, users can create `org.apache.spark.Logging` class themselves. However, we have to move our `org.apache.spark.Logging` to another place or they will conflict. cc @rxin for more details and correct me if I said wrong.

**Comment by srowen** [comment]
Logging is an internal class though ... it's not something anyone should use. For 2.x that can be enforced more strongly. I don't think this is harmful as a change but seems unnecessary.

**Comment by rxin** [comment]
@srowen it was only documented as private but not actually set as private in 1.x. As a result, a lot of user applications are unfortunately using it.

**Comment by JoshRosen** [comment]
I think the following exclude should fix things cleanly:

```
diff --git a/project/MimaExcludes.scala b/project/MimaExcludes.scala
index 2a4a874..ce982d2 100644
--- a/project/MimaExcludes.scala
+++ b/project/MimaExcludes.scala
@@ -322,6 +322,13 @@ object MimaExcludes {
       ) ++ Seq(
         // [SPARK-13686][MLLIB][STREAMING] Add a constructor parameter `reqParam` to (Streaming)LinearRegressionWithSGD
         ProblemFilters.exclude[MissingMethodProblem]("org.apache.spark.mllib.regression.LinearRegressionWithSGD.this")
+      ) ++ Seq(
+        // [SPARK-13928] Move org.apache.spark.Logging into org.apache.spark.internal.Logging
+        (problem: Problem) => problem match {
+          case MissingTypesProblem(_, missing)
+            if missing.map(_.fullName).sameElements(Seq("org.apache.spark.Logging")) => false
+          case _ => true
+        }
       )
     case v if v.startsWith("1.6") =>
       Seq(
```

**Comment by cloud-fan** [comment]
@JoshRosen thanks a lot! It's very helpful.

**Comment by cloud-fan** [comment]
hi @rxin , this PR changes too many files and can't  be reviewed on github. You can fetch my branch and run `git diff` locally after tests pass. It should be easy to review as most of the changes are 1 or 2 lines per file.

**Comment by cloud-fan** [comment]
The log says: `java.lang.RuntimeException: spark-core: Binary compatibility check failed!`, but no reason is provided...  cc @JoshRosen

**Comment by JoshRosen** [comment]
```
[error]  * trait org.apache.spark.Logging does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[MissingClassProblem]("org.apache.spark.Logging")
```

**Comment by cloud-fan** [comment]
Sorry I missed it as this message is so far away from the final one... @JoshRosen thanks again!

**Comment by rxin** [comment]
LGTM - merge it as soon as you get tests to pass.

**Comment by cloud-fan** [comment]
retest this please

**Comment by cloud-fan** [comment]
merging to master

**Pull request closed without merging**
