### PR TITLE
[SPARK-29053][WEBUI] Sort does not work on some columns

### PR DESCRIPTION
**Pull request by amanomer**
### What changes were proposed in this pull request?
Setting custom sort key for duration and execution time column.

### Why are the changes needed?
Sorting on duration and execution time columns consider time as a string after converting into readable form which is the reason for wrong sort results as mentioned in [SPARK-29053](https://issues.apache.org/jira/browse/SPARK-29053).

### Does this PR introduce any user-facing change?
No

### How was this patch tested?
Test manually. Screenshots are attached.

After patch:
**Duration**
Duration
**Execution time**
Execution Time

### CODE REVIEW

**Comment by wangyum** [comment]
ok to test

**Comment by amanomer** [comment]
cc @srowen @gatorsmile

**Review by srowen — APPROVED** [review]
Looks good, but do other pages have a similar problem too? I would not be surprised.

**Comment by amanomer** [comment]
No, I haven't found this issue anywhere else.

**Comment by amanomer** [comment]
thanks @srowen

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
Hi, @amanomer . Thank you for your contribution. I'd like to recommend the followings first.
1. Please attach your PR's screenshot. The current one is your internal one as you see the Spark version `2.3.2.020x`.
2. While you are here, could you fix the `Execution Time` which is the very left column to this? `Execution Time` has the same issue. If you build your PR branch, you can see that column.
   - Please see [line 74](https://github.com/apache/spark/pull/25855/files#diff-51d2e064901c3a6d560aac7ea29fb405L74).

After fixing the above two, you need to update the PR title and description and JIRA accordingly, too. Thanks!

**Comment by amanomer** [comment]
@dongjoon-hyun thanks for your feedback.
I am working on this.

**Comment by dongjoon-hyun** [comment]
Thanks, @amanomer . I'll review again after you update this PR.

**Comment by amanomer** [comment]
@dongjoon-hyun kindly review the updated PR.

**Review by srowen — COMMENTED** [review]
Looks good pending tests.

**Comment by srowen** [comment]
Merged to master. It didn't pick cleanly into 2.4. If we need it there, open another PR with the back-port.

**Comment by amanomer** [comment]
Thanks @srowen . 
I will open another PR to back-port this commit in 2.4.

**Comment by dongjoon-hyun** [comment]
Thank you, @amanomer and @srowen !

**Pull request closed without merging**
