### PR TITLE
[SPARK-35949][CORE]Fixes bug for sparkContext stopped on client mode

### PR DESCRIPTION
**Pull request by sunpe**
SPARK-35949
### What changes were proposed in this pull request?

Fixes a bug that the spark context was stopped while application is started on client mode.

### Why are the changes needed?

Due to pr https://github.com/apache/spark/commit/c625eb4f9f970108d93bf3342c7ccb7ec873dc27#diff-f8564df81d845c0cd2f621bc2ed22761cbf9731f28cb2828d9cbd0491f4e7584. In client mode, the spark context will be stopped on application start.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Manually on the production environment in my company.

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Thank you for your first contribution, @sunpe . I'd like to recommend two things.
1. Create an Apache Spark JIRA issue and use it as the PR title prefix.
2. Provide the failure procedure in the PR description.

**Comment by sunpe** [comment]
> Thank you for your first contribution, @sunpe . I'd like to recommend two things.
> 
> 1. Create an Apache Spark JIRA issue and use it as the PR title prefix.
> 2. Provide the failure procedure in the PR description.

**Comment by sunpe** [comment]
> Thank you for your first contribution, @sunpe . I'd like to recommend two things.
> 
> 1. Create an Apache Spark JIRA issue and use it as the PR title prefix.
> 2. Provide the failure procedure in the PR description.

hello dongjoon-hyun, I create an issue at this page SPARK-35949

**Comment by HyukjinKwon** [comment]
Can you fix the PR title to be matched with others? see also https://spark.apache.org/contributing.html

**Pull request closed without merging**
