### PR TITLE
[SPARK-10543] [CORE] Peak Execution Memory Quantile should be Per-task Basis

### PR DESCRIPTION
**Pull request by saurfang**
Read `PEAK_EXECUTION_MEMORY` using `update` to get per task partial value instead of cumulative value. 

I tested with this workload:

``` scala
val size = 1000
val repetitions = 10
val data = sc.parallelize(1 to size, 5).map(x => (util.Random.nextInt(size / repetitions),util.Random.nextDouble)).toDF("key", "value")
val res = data.toDF.groupBy("key").agg(sum("value")).count
```

Before:
image

After:
image

Tasks view:
image

cc @andrewor14 I appreciate if you can give feedback on this since I think you introduced display of this metric.

### CODE REVIEW

**Comment by andrewor14** [comment]
add to whitelist

**Comment by andrewor14** [comment]
yeah, I think this is correct. Would you mind adding a unit test for it? If you prefer to do it separately we can also just merge this first.

**Comment by saurfang** [comment]
I added a naive unit test. Let me know if you think it's sufficient or clear.

**Comment by andrewor14** [comment]
Yup it looks good, thanks for fixing this I'm merging into master and 1.5.

**Pull request closed without merging**
