### PR TITLE
[SPARK-10083] [SQL] CaseWhen should support type coercion of DecimalType and FractionalType

### PR DESCRIPTION
**Pull request by adrian-wang**
create t1 (a decimal(7, 2), b long);
select case when 1=1 then a else 1.0 end from t1;
select case when 1=1 then a else b end from t1;

### CODE REVIEW

**Comment by adrian-wang** [comment]
retest this please.

**Comment by adrian-wang** [comment]
@davies @rxin

**Comment by rxin** [comment]
cc @marmbrus

**Comment by davies** [comment]
LGTM

**Comment by marmbrus** [comment]
Thanks!  Merging to master and 1.5

**Pull request closed without merging**
