### PR TITLE
[SPARK-30494][SQL][2.4] Fix cached data leakage during replacing an existing view

### PR DESCRIPTION
**Pull request by LantaoJin**
### What changes were proposed in this pull request?

This is backport of #27185 to branch-2.4.

The cached RDD for plan "select 1" stays in memory forever until the session close. This cached data cannot be used since the view temp1 has been replaced by another plan. It's a memory leak.

We can reproduce by below commands:
```
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 3.0.0-SNAPSHOT
      /_/

Using Scala version 2.12.10 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_201)
Type in expressions to have them evaluated.
Type :help for more information.

scala> spark.sql("create or replace temporary view temp1 as select 1")
scala> spark.sql("cache table temp1")
scala> spark.sql("create or replace temporary view temp1 as select 1, 2")
scala> spark.sql("cache table temp1")
scala> assert(spark.sharedState.cacheManager.lookupCachedData(sql("select 1, 2")).isDefined)
scala> assert(spark.sharedState.cacheManager.lookupCachedData(sql("select 1")).isDefined)
```

### Why are the changes needed?
Fix the memory leak, specially for long running mode. 

### Does this PR introduce any user-facing change?
No.

### How was this patch tested?
Add a unit test.

### CODE REVIEW

**Comment by LantaoJin** [comment]
retest this please

**Comment by dongjoon-hyun** [comment]
Thank you, @LantaoJin .

**Comment by dongjoon-hyun** [comment]
The root cause of `pip package failure` is reverted from `branch-2.4`. (cc @HyukjinKwon )
```
nsatisfiableError: The following specifications were found to be in conflict:
  - python=3.5
  - setuptools=46.0.0 -> python[version='>=3.8,<3.9.0a0'] -> openssl[version='>=1.1.1d,<1.1.2a']
Use "conda search <package> --info" to see the dependencies for each package.
```

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Merged to `branch-2.4`.

**Comment by maropu** [comment]
late LGTM, thanks, @LantaoJin

**Comment by HyukjinKwon** [comment]
Thanks @dongjoon-hyun!

**Comment by LantaoJin** [comment]
Thank you, @dongjoon-hyun @HyukjinKwon

**Pull request closed without merging**
