### PR TITLE
[SPARK-37862][SQL] RecordBinaryComparator should fast skip the check of aligning with unaligned platform

### PR DESCRIPTION
**Pull request by ulysses-you**
### What changes were proposed in this pull request?

`RecordBinaryComparator` compare the entire row, so it need to check if the platform is unaligned. #35078 had given the perf number to show the benefits. So this PR aims to do the same thing that fast skip the check of aligning with unaligned platform.

### Why are the changes needed?

Improve the performance.

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

Pass CI. And the perf number should be same with #35078

### CODE REVIEW

**Comment by ulysses-you** [comment]
cc @srowen

**Comment by srowen** [comment]
Are there other instances like this?
Any chance there is an easy way to produce a benchmark result for this change too?

**Comment by ulysses-you** [comment]
> Are there other instances like this?

That's all. I searched and this PR is the only place should be changed

> Any chance there is an easy way to produce a benchmark result for this change too?

the related code are totally same, so cannot find the reason to re-produce the bencharmk result..

**Comment by srowen** [comment]
Merged to master

**Comment by ulysses-you** [comment]
thank you @srowen

**Pull request closed without merging**
