### PR TITLE
[SPARK-39981][SQL] Throw the exception QueryExecutionErrors.castingCauseOverflowErrorInTableInsert in Cast

### PR DESCRIPTION
**Pull request by HyukjinKwon**
### What changes were proposed in this pull request?

This PR is a followup of https://github.com/apache/spark/pull/37283. It missed `throw` keyword in the interpreted path.

### Why are the changes needed?

To throw an exception as intended instead of returning an exception itself.

### Does this PR introduce _any_ user-facing change?

Yes, it will throw an exception as expected in the interpreted path.

### How was this patch tested?

Haven't tested because it's too much straightforward.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @cloud-fan @gengliangwang

**Review by gengliangwang — APPROVED** [review]

**Comment by gengliangwang** [comment]
Thanks for catching it, @HyukjinKwon !

**Comment by gengliangwang** [comment]
BTW, it would be great if we could have a test case to capture the non-codegen code patch.

**Review by beliefer — COMMENTED** [review]
LGTM

**Comment by HyukjinKwon** [comment]
Merged to master and branch-3.3.

**Comment by HyukjinKwon** [comment]
Test conflicts. I just removed the test part in branch-3.3.

**Pull request closed without merging**
