### PR TITLE
backport [SPARK-27747][SPARK-27816][SPARK-28344]

### PR DESCRIPTION
**Pull request by cloud-fan**
backport 3 PRs to 2.4 to fix ambiguous self-join. This PR excludes the logical plan link which is not necessary in 2.4.

For more details about ambiguous self-join, please refer to https://github.com/apache/spark/pull/25107

### CODE REVIEW

**Comment by cloud-fan** [comment]
cc @dongjoon-hyun

**Comment by cloud-fan** [comment]
Seems we need backport more:
https://github.com/apache/spark/pull/25111
https://github.com/apache/spark/pull/25055

Shall we reconsider the decision of backport?

**Comment by dongjoon-hyun** [comment]
Thank you so much, @cloud-fan . Sure, I'm +1 to remove`Target Version` with the reason `Technical Difficulty`. While removing the `Target Version`, could you add a comment with the reason `Technical Difficulty` and a pointer to this PR please?

**Comment by dongjoon-hyun** [comment]
You mean this is difficult because it requires at least 5 patches. Did I understand correctly?

**Comment by cloud-fan** [comment]
Yea so far I find that 5 commits need to be backported. It's still possible to backport but we need to re-evaluate the risks.

**Comment by dongjoon-hyun** [comment]
Got it~ cc @srowen, @tgravescs , @gatorsmile

**Comment by srowen** [comment]
I don't know enough to really eval, but trust @cloud-fan on this one

**Comment by tgravescs** [comment]
its definitely starting to be a lot of changes to pull back that could cause side affects, I'm ok with not backporting to  2.4.5

**Comment by gatorsmile** [comment]
The risk is high based on the code changes in this PR.

**Comment by dongjoon-hyun** [comment]
Thank you all for your opinion. Especially, thank you for making this PR, @cloud-fan . I'll remove `Target Version: 2.4.5` for now. If we need this in `branch-2.4`, `Target Version` will be `2.4.6`.

**Comment by rshkv** [comment]
@cloud-fan, @tgravescs, @gatorsmile, I was wondering if you could say a little more about the risks you saw here.

We found some "surprising" results and consider taking this backport over on our palantir/spark fork. I just want to better understand why you decided against merging and see if we're willing to take risk. Were you afraid of false positives? Was it the amount of changes? I understand it's been a while since you thought about this.

**Comment by cloud-fan** [comment]
The risk is that many commits need to be backported. And there are probably more now as we have new bug fixes of the self-join detection in 3.x.

**Pull request closed without merging**
