### PR TITLE
[SPARK-39887][SQL][3.3] RemoveRedundantAliases should keep aliases that make the output of projection nodes unique

### PR DESCRIPTION
**Pull request by peter-toth**
### What changes were proposed in this pull request?
Keep the output attributes of a `Union` node's first child in the `RemoveRedundantAliases` rule to avoid correctness issues.

### Why are the changes needed?
To fix the result of the following query:
```
SELECT a, b AS a FROM (
  SELECT a, a AS b FROM (SELECT a FROM VALUES (1) AS t(a))
  UNION ALL
  SELECT a, b FROM (SELECT a, b FROM VALUES (1, 2) AS t(a, b))
)
```
Before this PR the query returns the incorrect result: 
```
+---+---+
|  a|  a|
+---+---+
|  1|  1|
|  2|  2|
+---+---+
```
After this PR it returns the expected result:
```
+---+---+
|  a|  a|
+---+---+
|  1|  1|
|  1|  2|
+---+---+
```

### Does this PR introduce _any_ user-facing change?
Yes, fixes a correctness issue.

### How was this patch tested?
Added new UTs.

### CODE REVIEW

**Comment by peter-toth** [comment]
cc @cloud-fan

**Comment by cloud-fan** [comment]
GA passed: https://github.com/peter-toth/spark/runs/7772855648

**Comment by cloud-fan** [comment]
thanks, merging to 3.3!

**Comment by cloud-fan** [comment]
@peter-toth unfortunately, due to the changes of golden files, this PR has conflicts with all branches... can you create another 2 PRs for 3.2 and 3.1? thanks!

**Comment by peter-toth** [comment]
Sure, here is the 3.2 version: https://github.com/apache/spark/pull/37491 and the 3.1 version: https://github.com/apache/spark/pull/37496.

**Pull request closed without merging**
