### PR TITLE
[SPARK-46747][SQL] Avoid scan in getTableExistsQuery for JDBC Dialects

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

[SPARK-46747](https://issues.apache.org/jira/browse/SPARK-46747) reported an issue that Postgres instances suffered from too many shared locks, which was caused by Spark‘s get table exist query. In this PR, we supplanted `"SELECT 1 FROM $table LIMIT 1"` with `"SELECT 1 FROM $table WHERE 1=0"` to prevent data from being scanned.

### Why are the changes needed?

overhead reduction for JDBC datasources

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

existing JDBC v1/v2 datasouce tests.

### Was this patch authored or co-authored using generative AI tooling?

no

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @yaooqinn .

**Comment by yaooqinn** [comment]
Thank you @dongjoon-hyun, merged to master

**Comment by bala-bellam** [comment]
Thank you @yaooqinn , @dongjoon-hyun . Can this patch be pushed to older versions as well, thank you.

**Comment by dongjoon-hyun** [comment]
For me, this looks like a perf improvement, @bala-bellam .
However, I will not object if someone backports this.

**Comment by yaooqinn** [comment]
Thank you, @dongjoon-hyun; I backported this to 3.3/3.4/3.5.

Hi @bala-bellam. Considering you are still in 2.3, as I suggested in JIRA comments, you can backport this to your in-house branch.

**Comment by yaooqinn** [comment]
I just noticed that the latest release of branch 3.3 is 3.3.4, so there will be no official 3.3.5 release that comes out with this patch.

**Comment by dongjoon-hyun** [comment]
That's too bad. 
> We are bound to older version because we are stuck with EMR. And we have been moving to EMR 6.8, which comes with 3.3.0.

However, the latest EMR also provides Spark 3.5.0 (emr-7.0.0) and (Spark 3.4.1) emr-6.15.0. I believe AWS support team is capable of delivering next Apache Spark releases without any issues.
- https://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-spark.html

Given that the situation, it seems that you have another non-Spark blocker issues in your production to block you from upgrading your EMR. Please try to fix it first. You need to catch up the latest EMP and Spark version first while you are waiting, @bala-bellam .

**Pull request closed without merging**
