### PR TITLE
[SPARK-45089][BUILD][TEST] Remove obsolete repo of DB2 JDBC driver

### PR DESCRIPTION
**Pull request by pan3793**
### What changes were proposed in this pull request?

Remove obsolete repo https://app.camunda.com/nexus/content/repositories/public/

### Why are the changes needed?

The repo was introduced in SPARK-10521, because the DB2 JDBC driver jars did not exist in Maven Central on that day.

Now, the https://app.camunda.com/nexus/content/repositories/public/ sunset and https://repo1.maven.org/maven2/com/ibm/db2/jcc/11.5.8.0/jcc-11.5.8.0.jar available in Maven Central.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass GA.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by pan3793** [comment]
cc @srowen @LuciferYang

**Review by LuciferYang — APPROVED** [review]
LGTM if test passed

**Review by yaooqinn — APPROVED** [review]

**Comment by yaooqinn** [comment]
thanks, merged to master

**Comment by dongjoon-hyun** [comment]
Hi, @pan3793 , @LuciferYang , @yaooqinn .

This commit doesn't have a proper JIRA ID. We need a trace-ability in the community.

**Comment by pan3793** [comment]
@dongjoon-hyun Sorry for the incorrect PR tile, the corresponding JIRA ticket is SPARK-45089. I'm not sure if it is worth to revert and re-commit with the correct title.

**Comment by dongjoon-hyun** [comment]
Don't worry. No need to revert. I just want to inform that we had better make it sure next time.

**Comment by pan3793** [comment]
@dongjoon-hyun Got it, thanks for checking and informing.

**Pull request closed without merging**
