### PR TITLE
[SPARK-18080][ML][PySpark] Locality Sensitive Hashing (LSH) Python API.

### PR DESCRIPTION
**Pull request by yanboliang**
## What changes were proposed in this pull request?
Add ```MinHash``` and ```RandomProjection``` Python API. 

## How was this patch tested?
Add doc tests.

### CODE REVIEW

**Comment by yanboliang** [comment]
cc @jkbradley @sethah

**Comment by sethah** [comment]
I began to review this, but got sidetracked with a lot of the details we are currently discussing on the [original LSH PR](https://github.com/apache/spark/pull/15148).

**Comment by jkbradley** [comment]
This can now proceed since [https://github.com/apache/spark/pull/15874] has been merged.  Sorry for the delay!  This will need to slip to 2.2

**Comment by jkbradley** [comment]
Pinging on this: What's a reasonable ETA for updating the PR?  Thanks @yanboliang !

**Comment by yanboliang** [comment]
@jkbradley I just came back from vacation, and will update this PR before the weekend. Thanks.

**Comment by jkbradley** [comment]
Btw, @yanboliang and @Yunni  did you sync?  I'm fine with the takeover, but don't want to stomp on toes.  Both can be listed as authors when this gets merged.  Should we close this issue with the other taking its place?

**Comment by yanboliang** [comment]
I'm OK to close this one and glad to help to review #16715 , but I think I will have time until next week.

**Pull request closed without merging**
