### PR TITLE
[SPARK-21721][SQL][Backport-2.1] Clear FileSystem deleteOnExit cache when paths are successfully removed

### PR DESCRIPTION
**Pull request by viirya**
## What changes were proposed in this pull request?

Backport SPARK-21721 to branch 2.1:

We put staging path to delete into the deleteOnExit cache of FileSystem in case of the path can't be successfully removed. But when we successfully remove the path, we don't remove it from the cache. We should do it to avoid continuing grow the cache size.

## How was this patch tested?

Added test.

### CODE REVIEW

**Comment by viirya** [comment]
cc @yzheng616 @gatorsmile Backport #18934 to branch 2.1.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Review by gatorsmile — APPROVED** [review]

**Comment by gatorsmile** [comment]
LGTM

Merging to 2.1

**Comment by gatorsmile** [comment]
@viirya Could you close it? Thanks!

**Comment by viirya** [comment]
Thanks @gatorsmile @dongjoon-hyun

**Pull request closed without merging**
