### PR TITLE
[SPARK-20433][BUILD] Bump jackson from 2.6.5 to 2.6.7.1

### PR DESCRIPTION
**Pull request by srowen**
## What changes were proposed in this pull request?

Taking over https://github.com/apache/spark/pull/18789 ; Closes #18789

Update Jackson to 2.6.7 uniformly, and some components to 2.6.7.1, to get some fixes and prep for Scala 2.12

## How was this patch tested?

Existing tests

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by gatorsmile** [comment]
cc @zsxwing

**Comment by vanzin** [comment]
Can you add "Closes #18789" to automate the closing of the other PR?

**Comment by zsxwing** [comment]
retest this please

**Comment by zsxwing** [comment]
LGTM pending tests

**Comment by vanzin** [comment]
I assume this is not needed in other branches since the CVE doesn't affect Spark?

Merging to master.

**Pull request closed without merging**
