### PR TITLE
[SPARK-41773][CONNECT][PYTHON][TESTS] Enable the doctests for window functions

### PR DESCRIPTION
**Pull request by zhengruifeng**
### What changes were proposed in this pull request?
1, Enable the doctests for window functions
2, Add additional test in connect

### Why are the changes needed?
for test coverage

### Does this PR introduce _any_ user-facing change?
no

### How was this patch tested?
enabled and added tests

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.
Please use `[TESTS]` for test-only PRs, @zhengruifeng . That's very helpful for the others. I believe `doc` tests also are tests.

**Comment by zhengruifeng** [comment]
@dongjoon-hyun yes, it should use `[TESTS]`, thanks for the reminder!

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by zhengruifeng** [comment]
thank you for the reviews @dongjoon-hyun @HyukjinKwon

**Pull request closed without merging**
