### PR TITLE
[SPARK-46766][SQL][AVRO] ZSTD Buffer Pool Support For AVRO datasource

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

This PR adds ZSTD Buffer Pool Support For AVRO datasource writing with zstd compression codec

### Why are the changes needed?

Enable a tuning technique for users

### Does this PR introduce _any_ user-facing change?

yes, add a new configuration

### How was this patch tested?

passing existing ci shall be sufficient

### Was this patch authored or co-authored using generative AI tooling?

no

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

Does Avro community provide a benchmark for this, @yaooqinn ? Or, we may need to add one like `ZStandardBenchmark.scala`.

**Comment by yaooqinn** [comment]
Hi @dongjoon-hyun I've not found any benchmark for this part in arvo repo or website.

I think we can have one of our own

**Comment by yaooqinn** [comment]
https://issues.apache.org/jira/browse/SPARK-46772 is created to do the benchmark thing

Thanks @dongjoon-hyun , merged this to master

**Comment by dongjoon-hyun** [comment]
Thank you, @yaooqinn !

**Pull request closed without merging**
