### PR TITLE
[SPARK-20223][SQL] Fix typo in tpcds q77.sql

### PR DESCRIPTION
**Pull request by wzhfy**
## What changes were proposed in this pull request?

Fix typo in tpcds q77.sql

## How was this patch tested?

N/A

### CODE REVIEW

**Comment by srowen** [comment]
Looks like a typo, yes, but I wonder how this worked at all? is it not used?

**Comment by wzhfy** [comment]
@srowen There's a benchmark test `TPCDSQueryBenchmark` that user can run, so I think it should be fixed.

**Comment by wzhfy** [comment]
retest this please

**Comment by srowen** [comment]
@wzhfy yeah it's a dumb question maybe, but is that not run automatically and thus why it isn't caught by tests?

**Comment by gatorsmile** [comment]
I think we are not running it in our test case batches. This is for performance evaluation.

**Review by gatorsmile — APPROVED** [review]
LGTM

**Comment by gatorsmile** [comment]
Thanks! Merging to master/2.1/2.0

**Comment by wzhfy** [comment]
@srowen It's not run automatically. And even if it is run, no error would be caught, the predicate will just become `null` because casting `'2000-08-03]'` to Date is failed.

**Pull request closed without merging**
