### PR TITLE
[MINOR][CONNECT][PYTHON] Miscellaneous cleanup in Spark Connect componenet

### PR DESCRIPTION
**Pull request by HyukjinKwon**
### What changes were proposed in this pull request?

This PR proposes:
1. Fix the code style in `SparkConnectPlugin.scala` and `SparkBuild.scala` to be consistent with others.
2. Rename `data_frame` to `dataframe` to be consistent with existing PySpark codes.

This Pr is a sort of a followup of https://github.com/apache/spark/pull/37710

### Why are the changes needed?

To follow existing codebase, and style.

### Does this PR introduce _any_ user-facing change?

No, the codes are not released yet. The only notable change would be renaming `data_frame` to `dataframe` to be consistent.

### How was this patch tested?

Ci in this PR should validate the changes.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @dongjoon-hyun FYI

**Comment by amaliujia** [comment]
Big +1!

LGTM

**Review by LuciferYang — APPROVED** [review]
+1, LGTM

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. (Pending CIs).

**Comment by dongjoon-hyun** [comment]
YarnClusterSuite failure is irrelevant to this PR. Merged to master.
```
[info] *** 4 TESTS FAILED ***
[error] Failed tests:
[error] 	org.apache.spark.deploy.yarn.YarnClusterSuite
```

**Comment by zhengruifeng** [comment]
Late LGTM

**Pull request closed without merging**
