### PR TITLE
[SPARK-36220][PYTHON] Fix pyspark.sql.types.Row type annotation

### PR DESCRIPTION
**Pull request by tobiasedwards**
### What changes were proposed in this pull request?

This change changes the type annotations for `pyspark.sql.types.Row`'s `__new__` and `__init__` methods when invoked without keyword arguments (_i.e._, `*args` rather than `**kwargs`) from `str` to `Any`.

### Why are the changes needed?

When creating a [Row](https://hyukjin-spark.readthedocs.io/en/latest/reference/api/pyspark.sql.types.Row.html) with unnamed fields which are not of type `str` (_e.g._, `row1 = Row("Alice", 11)` appears in the `Row` documentation) type checkers produce an error.

The implementation doesn't assume the arguments are of type `str`, and in fact the documentation includes an example where non-`str` types are provided in this way (see [the final example here](https://hyukjin-spark.readthedocs.io/en/latest/reference/api/pyspark.sql.types.Row.html)).

An example of the type error produced by [pyright](https://github.com/microsoft/pyright) is
```
error: No overloads for "__init__" match the provided arguments
    Argument types: (Literal['Alice'], Literal[11]) (reportGeneralTypeIssues)
```

### Does this PR introduce _any_ user-facing change?

It changes the python type annotation for `Row`, which is user facing. The change makes the type annotation more general, and should not be a breaking change in any sense.

The previous type annotation behaves like so:
```python
# Will not produce type errors:
Row("Alice", "Bob")
# Will produce type errors:
Row("Alice", 11)
```
After this change, both lines will be accepted by a type checker.

### How was this patch tested?

- [x] MyPy tests of PySpark source code
    ```
    mypy --no-incremental --config python/mypy.ini python/pyspark
    ```
    For me, this currently fails on `master` with the following errors:
    ```
    python/pyspark/mllib/tree.pyi:29: error: Overloaded function signatures 1 and 2 overlap with incompatible return types
    python/pyspark/mllib/tree.pyi:38: error: Overloaded function signatures 1 and 2 overlap with incompatible return types
    python/pyspark/mllib/feature.pyi:34: error: Overloaded function signatures 1 and 2 overlap with incompatible return types
    python/pyspark/mllib/feature.pyi:42: error: Overloaded function signatures 1 and 2 overlap with incompatible return types
    python/pyspark/mllib/feature.pyi:48: error: Overloaded function signatures 1 and 2 overlap with incompatible return types
    python/pyspark/mllib/feature.pyi:54: error: Overloaded function signatures 1 and 2 overlap with incompatible return types
    python/pyspark/mllib/feature.pyi:76: error: Overloaded function signatures 1 and 2 overlap with incompatible return types
    python/pyspark/mllib/feature.pyi:124: error: Overloaded function signatures 1 and 2 overlap with incompatible return types
    python/pyspark/mllib/feature.pyi:165: error: Overloaded function signatures 1 and 2 overlap with incompatible return types
    python/pyspark/mllib/clustering.pyi:45: error: Overloaded function signatures 1 and 2 overlap with incompatible return types
    python/pyspark/mllib/clustering.pyi:72: error: Overloaded function signatures 1 and 2 overlap with incompatible return types
    python/pyspark/mllib/classification.pyi:39: error: Overloaded function signatures 1 and 2 overlap with incompatible return types
    python/pyspark/mllib/classification.pyi:52: error: Overloaded function signatures 1 and 2 overlap with incompatible return types
    Found 13 errors in 4 files (checked 314 source files)
    ```
    Re-running after my change doesn't introduce any new errors. MyPy version 0.910 was used.

Tagging @HyukjinKwon and @zero323 as you both seem to have worked on type annotations recently. Thanks in advance for your help 😃

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
yeah, looks like we should fix. Would you mind filing a JIRA and link it to the PR title please? (see also https://spark.apache.org/contributing.html). Also please enable GitHub Actions in your forked reopository - Apache Spark leverages the resources allocated to your forked repository (see https://github.com/apache/spark/pull/33428/checks?check_run_id=3110204626)

**Comment by tobiasedwards** [comment]
Will do, thanks for that!

**Comment by tobiasedwards** [comment]
Hey @HyukjinKwon, I've added a Jira ticket here: [SPARK-36220](https://issues.apache.org/jira/browse/SPARK-36220) and enabled GitHub Actions on my forked repo. Is there anything I need to do to kick off the "Build and test" action again?

**Comment by HyukjinKwon** [comment]
ah actually this is the limitation .. I can;t retrigger the test because it belongs to your repo :-) .. can you rebase and push it again? e.g.) `git checkout python-sql-row-type-annotation git fetch upstream && git rebase upstream master && git push origin python-sql-row-type-annotation`

**Comment by tobiasedwards** [comment]
Whoops I think I've messed up my rebase, give me a minute

**Comment by tobiasedwards** [comment]
There we go, that should be better.

When I botched the rebase the bot added some incorrect labels though, are you able to remove them, @HyukjinKwon?

Thanks again for your help!

**Comment by HyukjinKwon** [comment]
Jenkins, ok to test

**Comment by HyukjinKwon** [comment]
Looks correct to me but I would defer to @zero323

**Comment by HyukjinKwon** [comment]
(the other test failures in GA look unrelated. should be fine to go ahead and merge)

**Comment by zero323** [comment]
I am sitting on the fence here. While 

```python
Row("Alice", 11)
```

is a technically valid initialization of a `Row`, I always considered it actual usage a code-smell. Hence the choice of annotations, where `*args` form is intended to be used with combination with `__call__`. Using it to initialize unnamed `Rows` is not only rather inefficient, but also leaves us with this awkward object, which is intended as factory of named `Rows`, but never used as such.

**Comment by tobiasedwards** [comment]
Thanks @zero323 for chiming in on this, that's really interesting insight. I'm new to working with PySpark and hadn't realised it was a discouraged use case.

Given it is a valid initialization, and is included in the docs, my position is that we should fix the type annotation and then add to the documentation to explain this/deprecate this type of initialization later.

What do you think?

**Comment by zero323** [comment]
I'd like to wait and see if other folks are interested in giving some feedback.  

On top of the concerns raised above, there is also a matter of ambiguity introduced by application of `Any`.  In particular, we want users to avoid creating `Rows` with fields that cannot be referenced:

```python
>>> a42 = Row("a", 42)
>>> a42instance = a42("foo", "bar")

>>> a42instance[42]
Traceback (most recent call last):
...
IndexError: tuple index out of range

>>> a42instance["42"]
Traceback (most recent call last):
...
ValueError: 42
```

Personally, I believe that it's better to have useful annotations which cover majority of known use cases, rather than too broad annotations that cover edge scenarios, but make annotations useless for majority of users.

**Comment by srowen** [comment]
If it functions as a warning for unintended usage, that seems OK. But it would need to be clearly documented why this isn't used this way. Maybe we need to fix the example that shows the unintended usage

**Comment by HyukjinKwon** [comment]
Yeah, if it gets too long to write up in the type annotation for all valid cases, we could just use `Any` for now, and document the expected usage for now.

**Comment by zero323** [comment]
> Yeah, if it gets too long to write up in the type annotation for all valid cases, we could just use `Any` for now, and document the expected usage for now.

Just a clarification ‒ as is, I don't think we can have meaningful annotation if we want to annotate this specific usage. Once we have `*args: Any` it will make any other signature ambiguous. In other words  there is no way to tell what is the intention behind code like this:

```
Row("foo", "bar")
```

**Comment by Don-Burns** [comment]
I am jumping in very late on this.
But hoping to learn from it.
If you are creating a DF from scratch what is the suggested way of creating rows with null values if having non-strings passed as positional args is discouraged/a code smell?
There are cases where column names are valid for spark but not able to be expressed as python keywords. e.g. has a dash in the name


e.g. I define the schema separately and build my row data to create the df

```python
from pyspark.sql import SparkSession
from pyspark.sql.types import Row, StringType, StructField, StructType

spark = SparkSession.builder.getOrCreate()
schema = StructType(
    [
        StructField("some-col", StringType(), True),
    ]
)

data = [Row("a value"), Row(None)]

df = spark.createDataFrame(data=data, schema=schema)
df.show()
```
image
image

**Comment by Don-Burns** [comment]
Welp, you learn something new every day. Didn't know it accepted plain list of tuples for data in create DF 🤦
Thank you @zero323

**Pull request closed without merging**
