### PR TITLE
Revert "[SPARK-34549][BUILD] Upgrade aws kinesis to 1.14.0 and java sdk 1.11.844"

### PR DESCRIPTION
**Pull request by sarutak**
### What changes were proposed in this pull request?

This PR reverts the change of SPARK-34549 ( #31658).

### Why are the changes needed?

See #33133.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Confirmed all the `*Kinesis*Suite` pass with the following command without newer Guava.
```
ENABLE_KINESIS_TESTS=1 KINESIS_TEST_ENDPOINT_URL=https://kinesis.ap-northeast-1.amazonaws.com build/sbt -Pkinesis-asl 'testOnly *Kinesis*Suite'
```

### CODE REVIEW

**Comment by sarutak** [comment]
cc: @HyukjinKwon @dongjoon-hyun @viirya 
I'll check all the kinesis tests work on AWS environment.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by sarutak** [comment]
Confirmed all the `*Kinesis*Suite` pass with the following command without newer Guava.
```
ENABLE_KINESIS_TESTS=1 KINESIS_TEST_ENDPOINT_URL=https://kinesis.ap-northeast-1.amazonaws.com build/sbt -Pkinesis-asl 'testOnly *Kinesis*Suite'
```

**Comment by HyukjinKwon** [comment]
Let me merge this one first since it cause the regression, @dongjoon-hyun @viirya

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by dongjoon-hyun** [comment]
Thank you, @sarutak and @HyukjinKwon !

cc @gengliangwang

**Comment by viirya** [comment]
lgtm, thanks!

**Comment by sarutak** [comment]
Let's try to upgrade again once Guava is successfully upgraded.

**Pull request closed without merging**
