### PR TITLE
[WebUI] Fix collapse of WebUI layout

### PR DESCRIPTION
**Pull request by sarutak**
When we decrease the width of browsers, the header of WebUI wraps and collapses like as following image.

### CODE REVIEW

**Comment by pwendell** [comment]
@sarutak can you give a screenshot of what it looks like before your patch (or after?). I can't tell whether the one here is before or after.

**Comment by sarutak** [comment]
@pwendell That's the before patch applied. I've updated the description.

**Comment by andrewor14** [comment]
Hey @sarutak I tried this out locally and it appears that the "Jobs, Stages, Storage ..." and the application name are shifted upwards too close to the top of the page. Is there something we can do about it?

**Comment by sarutak** [comment]
@andrewor14 I fixed the layout as follows. How do you think?

**Comment by andrewor14** [comment]
Ok, looks good. This just changes CSS so the tests are irrelevant here. I'm merging this into master thanks.

**Pull request closed without merging**
