### PR TITLE
[SPARK-11439][ML] Optimization of creating sparse feature without dense one

### PR DESCRIPTION
**Pull request by nakul02**
Sparse feature generated in LinearDataGenerator does not create dense vectors as an intermediate any more.

### CODE REVIEW

**Comment by nakul02** [comment]
I got an e-mail saying that the Jenkins Tests Failed. The log said:
ERROR: Timeout after 15 minutes
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from https://github.com/apache/spark.git

Could you please run the Jenkins test again?

**Comment by holdenk** [comment]
You can ask jenkins to re-run the tests with Jenkins retest this please

**Comment by nakul02** [comment]
jenkins retest this please

**Comment by nakul02** [comment]
Commit history was all messed up. I redid everything and am going to open a pull request.

**Pull request closed without merging**
