### PR TITLE
[BUILD] refactor dev/lint-python in to something readable

### PR DESCRIPTION
**Pull request by shaneknapp**
## What changes were proposed in this pull request?

`dev/lint-python` is a mess of nearly unreadable bash.  i would like to fix that as best as i can.

## How was this patch tested?

the build system will test this.

### CODE REVIEW

**Comment by shaneknapp** [comment]
test this please

**Comment by shaneknapp** [comment]
test this please

**Comment by shaneknapp** [comment]
see the output from the following build to get the gory details of what's happening:
https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/98664/console

i removed `set -x` from the top to clean up the output in the build logs.

**Comment by shaneknapp** [comment]
test this please

**Comment by shaneknapp** [comment]
test this please

**Comment by shaneknapp** [comment]
test this please

**Comment by HyukjinKwon** [comment]
I agree with this change. The current script is a total mess - I will try to help take a look when the tests pass. BTW, it would be awesome if PR description contains what this PR tries to fix later when the tests pass

**Comment by shaneknapp** [comment]
i have no idea why the tests aren't passing btw.  :\

**Comment by shaneknapp** [comment]
test this please

**Comment by shaneknapp** [comment]
test this please

**Comment by shaneknapp** [comment]
alright, i think we're g2g.   i'll squash my commits now before merging.

**Comment by shaneknapp** [comment]
(weird, github ate my last comment)

@HyukjinKwon i think we're g2g for merging this in to master and backports.  you want to do this, or should i?

**Comment by HyukjinKwon** [comment]
I haven't taken a look super closely but the idea looks itself okay. Is it urgent? if yes, yup. I don't object to go ahead right away. Otherwise, might be good to leave open for few days for review comments .. 

Let me leave some cc's for @srowen, @felixcheung, @holdenk ..

**Comment by shaneknapp** [comment]
nah, it's not urgent at all.

i also tested this locally by breaking various python scripts and
confirming that it caught errors as expected.

**Comment by shaneknapp** [comment]
howdy howdy!  i opened this nearly 2 weeks ago, and was wondering if i could get another set of eyeballs on it...

@holdenk @srowen @felixcheung

**Comment by srowen** [comment]
I don't know this script well enough nor Python to really comment, but if it works, push it.

**Comment by shaneknapp** [comment]
okie dokie...  this will be my first official push to the spark repo!  :)

**Comment by shaneknapp** [comment]
gonna hold off on backporting until i inspect each branch independently.

**Comment by HyukjinKwon** [comment]
This was merged to master (and branch-3.0).

**Pull request closed without merging**
