### PR TITLE
[SPARK-39182][BUILD] Upgrade to Arrow 8.0.0

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to upgrade Apache Arrow to 8.0.0 for Apache Spark 3.4. PyArrow will be handled separately.

### Why are the changes needed?

To get the latest features and bug fixes

https://arrow.apache.org/release/8.0.0.html

### Does this PR introduce _any_ user-facing change?

This should work fine with old versions.

### How was this patch tested?

Pass the CIs.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
cc @sunchao

**Comment by dongjoon-hyun** [comment]
BTW, this is tested in my local first.
- https://github.com/dongjoon-hyun/spark/pull/3

**Review by sunchao — APPROVED** [review]
LGTM

**Comment by dongjoon-hyun** [comment]
Thank you for your review and approval, @sunchao !

**Comment by dongjoon-hyun** [comment]
All tests passed. Merged to master for Apache Spark 3.4.

**Pull request closed without merging**
