### PR TITLE
[SPARK-6761][SQL] Aggregation function for approximate quantile

### PR DESCRIPTION
**Pull request by viirya**
JIRA: https://issues.apache.org/jira/browse/SPARK-6761

This patch adds an aggregation function for approximate quantile. Its previous version at #6042 uses RDD operations to perform the computation. This path uses new aggregation expression API.

Since there is no existing aggregation1 expression for it, it only supports AggregateExpression2.

This computes approximate quantile based on the paper Greenwald, Michael and Khanna, Sanjeev, "Space-efficient Online Computation of Quantile Summaries," SIGMOD '01.

Close #6042.

### CODE REVIEW

**Comment by viirya** [comment]
ping @rxin @liancheng @yhuai This PR is submitted for a long time. I just bring it up to date. Do you have time to take a look? Thanks.

**Comment by viirya** [comment]
retest this please.

**Comment by liancheng** [comment]
ping @mengxr

**Comment by viirya** [comment]
Reopen #6042 and close this one.

**Pull request closed without merging**
