### PR TITLE
[SPARK-33662][BUILD] Setting version to 3.2.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to update `master` branch version to 3.2.0-SNAPSHOT.

### Why are the changes needed?

Start to prepare Apache Spark 3.2.0.

### Does this PR introduce _any_ user-facing change?

N/A.

### How was this patch tested?

Pass the CIs.

### CODE REVIEW

**Review by srowen — APPROVED** [review]

**Review by tgravescs — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @tgravescs !

**Review by gengliangwang — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @gengliangwang !

**Comment by dongjoon-hyun** [comment]
Retest this please

**Comment by dongjoon-hyun** [comment]
For one Jenkins UT failure, it's a known flakiness issue, SPARK-33273 .
```
org.apache.spark.sql.SQLQueryTestSuite.subquery/scalar-subquery/scalar-subquery-predicate.sql
```

For one Jenkins K8s IT failure, it's also a known flaky one. (cc @ScrapCodes )
```
- Verify logging configuration is picked from the provided SPARK_CONF_DIR/log4j.properties *** FAILED ***
```

**Comment by dongjoon-hyun** [comment]
Scala 2.13 seems to be broken by https://github.com/apache/spark/pull/30575 .

**Comment by dongjoon-hyun** [comment]
Jenkins passed. Merged to master.

**Comment by dongjoon-hyun** [comment]
Thank you all!

**Comment by HyukjinKwon** [comment]
Oh thanks Dongjoon :-).

**Comment by ScrapCodes** [comment]
> For one Jenkins UT failure, it's a known flakiness issue, [SPARK-33273](https://issues.apache.org/jira/browse/SPARK-33273) .
> 
> ```
> org.apache.spark.sql.SQLQueryTestSuite.subquery/scalar-subquery/scalar-subquery-predicate.sql
> ```
> 
> For one Jenkins K8s IT failure, it's also a known flaky one. (cc @ScrapCodes )
> 
> ```
> - Verify logging configuration is picked from the provided SPARK_CONF_DIR/log4j.properties *** FAILED ***
> ```
> 
> GitHub Action jobs are still on the queue for two hours.

Thanks @dongjoon-hyun, can you help me spot one more flaked instance of this test. So that I am sure, of the cause. (In my local testing, it never failed so far.)

**Comment by dongjoon-hyun** [comment]
@ScrapCodes . You can find more instances easily at the failure links of https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder-K8s job. I saw this failure several times.
- https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder-K8s/36854/console
- https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder-K8s/36852/console
- https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder-K8s/36850/console

**Comment by ScrapCodes** [comment]
Thanks @dongjoon-hyun, I have opened a pr #30616 to address this.

**Pull request closed without merging**
