### PR TITLE
[SPARK-23418][SQL]: Fail DataSourceV2 reads when user schema is passed, but not supported.

### PR DESCRIPTION
**Pull request by rdblue**
## What changes were proposed in this pull request?

DataSourceV2 initially allowed user-supplied schemas when a source doesn't implement `ReadSupportWithSchema`, as long as the schema was identical to the source's schema. This is confusing behavior because changes to an underlying table can cause a previously working job to fail with an exception that user-supplied schemas are not allowed.

This reverts commit adcb25a0624, which was added to #20387 so that it could be removed in a separate JIRA issue and PR.

## How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by rdblue** [comment]
@cloud-fan, here's the PR to fix user-supplied schema behavior. Once #20387 is committed, I'll rebase and remove its commits from this PR.

**Comment by rdblue** [comment]
@cloud-fan, this implements SPARK-23418, which rejects user-supplied schemas when ReadSupportWithSchema is not available.

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Comment by rdblue** [comment]
Thanks for reviewing, @cloud-fan!

**Pull request closed without merging**
