### PR TITLE
[SPARK-4920][UI]: back port the PR-3763 to branch 1.1

### PR DESCRIPTION
**Pull request by uncleGen**

### CODE REVIEW

**Comment by JoshRosen** [comment]
Jenkins, retest this please.

**Comment by JoshRosen** [comment]
Jenkins, retest this please.

**Comment by JoshRosen** [comment]
Looks like the "automatically cleanup RDD + shuffle + broadcast in distributed mode.automatically cleanup RDD + shuffle + broadcast in distributed mode" is failing; is that test flaky?

**Comment by JoshRosen** [comment]
(Whoops, my earlier (deleted) comment was for a different PR).

This looks good to me, so I'm going to merge it into `branch-1.1` (1.1.2).

**Comment by JoshRosen** [comment]
Actually, I can't merge this now due to some Apache Git infra maintenance; if I don't end up merging this later today / tomorrow, send me a reminder and I'll do it.

**Comment by uncleGen** [comment]
@JoshRosen OK， thank you！

**Comment by JoshRosen** [comment]
I've merged this into `branch-1.1` (1.1.2).  Now that this is merged, do you mind closing this PR (GitHub can't auto-close PRs that are opened against maintenance branches).

**Pull request closed without merging**
