### PR TITLE
[SPARK-50123][TESTS] Move BitmapExpressionUtilsSuite & ExpressionImplUtilsSuite from java to scala test sources folder

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

Move the BitmapExpressionUtilsSuite and ExpressionImplUtilsSuite from the Java to the Scala test sources folder where they belong.

### Why are the changes needed?

code refactoring

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

existing tests

### Was this patch authored or co-authored using generative AI tooling?

no

### CODE REVIEW

**Review by MaxGekk — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, Nice catch, @yaooqinn .

**Review by dongjoon-hyun — COMMENTED** [review]
BTW, we need a JIRA ID because we need to backport this, @yaooqinn .

It's because `BitmapExpressionUtilsSuite` was added by [SPARK-44154](https://issues.apache.org/jira/browse/SPARK-44154) at Apache Spark 3.5.0 and the other file was too.

**Comment by yaooqinn** [comment]
Thank you @dongjoon-hyun  @MaxGekk  just filed https://issues.apache.org/jira/browse/SPARK-50123

**Comment by MaxGekk** [comment]
+1, LGTM. Merging to master/3.5.
Thank you, @yaooqinn and @dongjoon-hyun for review.

**Pull request closed without merging**
