### PR TITLE
[SPARK-15769][SQL] Add Encoder for input type to Aggregator

### PR DESCRIPTION
**Pull request by koertkuipers**
## What changes were proposed in this pull request?

Aggregator also has an Encoder for the input type
## How was this patch tested?

Add tests to DatasetAggregatorSuite to upcast aggregator input types and apply Aggregator only to selected columns

### CODE REVIEW

**Comment by cloud-fan** [comment]
Can you give some examples to show how this PR make the aggregator API more friendly and easier to use?

**Comment by koertkuipers** [comment]
@cloud-fan from the (added) unit tests:
```
val df2 = Seq("a" -> 1, "a" -> 3, "b" -> 3).toDF("i", "j")
checkAnswer(df2.groupBy("i").agg(ComplexResultAgg.toColumn),
  Row("a", Row(2, 4)) :: Row("b", Row(1, 3)) :: Nil)
```
this shows how the underlying type is Row (with a schema consisting of Strings and Ints), and it gets converted to the input type of the Aggregator which is (String, Long), so this involves both conversion and upcast.

and:
```
val df3 = Seq(("a", "x", 1), ("a", "y", 3), ("b", "x", 3)).toDF("i", "j", "k")
checkAnswer(df3.groupBy("i").agg(ComplexResultAgg("i", "k")),
  Row("a", Row(2, 4)) :: Row("b", Row(1, 3)) :: Nil)
```
this is similar to the previous example but i also select the columns i want the Aggregator to operate on (namely columns "i" and "k")

**Comment by koertkuipers** [comment]
@cloud-fan i am running into some trouble updating my branch to the latest master. i get errors in tests due to Analyzer.validateTopLevelTupleFields

the issue seems to be that in KeyValueGroupedDataset[K, T] the Aggregators are supposed to operate on T, but the logicalPlan at this point already has K appended to T because AppendColumns(func, inputPlan) is applied to the plan before its passed into KeyValueGroupedDataset. so validateTopLevelTupleFields also sees the column for the key in the inputs and believes the deserializer for T is missing a field.

any suggestions on how to get around this?

**Comment by cloud-fan** [comment]
`Aggregator` API is designed for typed `Dataset` only, not for untyped `DataFrame`. It can work if users use `Row` as the input type of `Aggregator`, but it's not a recommended usage.

On the other way, it's dangerous to use a different encoder when apply a typed operation on `Dataset`. Let's say we have a `Dataset[T]` called `ds`, and its data is encoded from instances of `T` by `enc1`. Now you apply an `Aggregator` on the `ds`, with input encoder `enc2`. We can not guarantee that `enc2` can decode the data of `ds` to `T` instances, because the data is encoded by `enc1`.

We can discuss it further if you have other ideas, and close this PR if you think my explaintion makes sense, thanks for working on it anyway!

**Comment by koertkuipers** [comment]
If Aggregator is designed for typed Dataset only then that is a bit of a shame, because its a elegant and generic api that should be useful for DataFrame too. this causes fragmentation (Aggregator versus UserDefinedAggregationFunction). 
I am not sure what the better way to do this is, but i would like a single high level Aggregator-like api that i can use in Dataset and DataFrame.

**Comment by cloud-fan** [comment]
a possible approach may be to enable untyped grouping(`groupBy`) support typed aggregating(`Aggregator`), i.e. something like `df.groupBy("i").keyAs[Int].agg(ComplexResultAgg.toColumn)`

**Comment by koertkuipers** [comment]
well that was sort of what i was trying to achieve. the unit tests i added were for using Aggregator for untyped grouping(```groupBy```). 
and i think for it to be useful within that context one should also be able to select the columns that the Aggregator operates on.

**Comment by koertkuipers** [comment]
for example with this branch you can do:
```
val df3 = Seq(("a", "x", 1), ("a", "y", 3), ("b", "x", 3)).toDF("i", "j", "k")
df3.groupBy("i").agg(
  ComplexResultAgg.apply("i", "k"),
  SumAgg.apply("j"),
  AverageAgg.apply("j")
)
````
so these are multiple Aggregators applied in an untyped groupBy, each on selected columns.

**Comment by koertkuipers** [comment]
@cloud-fan i thought about this a little more, and my suggested changes to the Aggregator api does not allow one to use a different encoder when applying a typed operation on Dataset. so i do not think it is dangerous as such.

it does enable usage within the untyped grouping, which is where type conversions are already customary anyhow. its not more dangerous than say using a udaf in a DataFrame.

**Pull request closed without merging**
