### PR TITLE
[SPARK-47721][DOC] Guidelines for the Structured Logging Framework

### PR DESCRIPTION
**Pull request by gengliangwang**
### What changes were proposed in this pull request?

As suggested in https://github.com/apache/spark/pull/45834/files#r1549565157, I am creating initial guidelines for the structured logging framework.

### Why are the changes needed?

We need guidelines to align the logging migration works in the community. 

### Does this PR introduce _any_ user-facing change?

No
### How was this patch tested?

It's just doc change.
### Was this patch authored or co-authored using generative AI tooling?

Yes. Generated-by: GitHub Copilot 1.2.17.2887

### CODE REVIEW

**Comment by gengliangwang** [comment]
cc @panbingkun @pan3793 @dtenedor @dongjoon-hyun @cloud-fan @itholic

**Review by dongjoon-hyun — COMMENTED** [review]
Just a question. Which part do you mean by this, @gengliangwang ?
> Yes, from Github copilot.

**Comment by gengliangwang** [comment]
@dongjoon-hyun Thanks for pointing it out. I just updated the PR description.

**Review by dongjoon-hyun — APPROVED** [review]

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by itholic** [comment]
Thanks for writing this. It's helpful

**Pull request closed without merging**
