### PR TITLE
[SPARK-12138] [SQL] Escape \u in the generated comments of codegen

### PR DESCRIPTION
**Pull request by gatorsmile**
When \u appears in a comment block (i.e. in /**/), code gen will break. So, in Expression and CodegenFallback, we escape \u to \u.

@yhuai Please review it. I did reproduce it and it works after the fix. Thanks!

### CODE REVIEW

**Comment by gatorsmile** [comment]
Weird... 

My code changes are not related to the failed test case in SparkR. 
```
count(sampled3) < 3 isn't true
```

**Comment by gatorsmile** [comment]
retest this please

**Comment by gatorsmile** [comment]
Found a bug in the function `sample` of R. Will submit a PR later. Thanks!

**Comment by yhuai** [comment]
Thanks. LGTM. Merging to master and branch 1.6.

**Comment by yhuai** [comment]
Will also merge it to branch 1.5.

**Comment by yhuai** [comment]
I have also merged it to branch 1.5.

**Pull request closed without merging**
