### PR TITLE
[SPARK-10288][Yarn] Add REST client for Spark on Yarn to support application submission

### PR DESCRIPTION
**Pull request by jerryshao**
This PR adds a REST client for Spark on Yarn to submit, query and kill applications. This function is already supported in Standalone and Mesos mode, here to add the Yarn supported. ~~Still miss some parts like unit tests,~~ will continue to work on it.

Any comment is greatly appreciated.

### CODE REVIEW

**Comment by jerryshao** [comment]
Jenkins, retest this please.

**Comment by andrewor14** [comment]
@jerryshao doesn't YARN already come with a stable REST API [1] for submitting applications? The main reason why we did it for standalone mode is because the Master used to only accept registrations through Akka, which provides little compatibility guarantees.

Is the motivation here to provide an additional level of convenience for the user to submit Spark applications on YARN?

[1] https://hadoop.apache.org/docs/stable/hadoop-yarn/hadoop-yarn-site/ResourceManagerRest.html

**Comment by jerryshao** [comment]
Hi @andrewor14 , thanks a lot for your comment. To some extent, this PR provides an additional choice for user to submit application on Yarn. For users they want to build a gateway to submit applications, this rest client will be easy for them to do it.

I admitted this PR will increase the complexity of current yarn/client code, not sure what is your opinion and suggestion on it?

Thanks a lot.

**Comment by srowen** [comment]
My snap reaction is that this is a lot of new code to support something that's not that Spark-specific; you could imagine a general REST API for YARN that doesn't need to belong to Spark.

**Comment by sryza** [comment]
My reaction is similar to Andrew's.  I haven't across much user pain around the way that Spark submits apps to YARN.  If particular use cases where the current way of doing things causes problems, I'd be willing to reconsider.

**Comment by vanzin** [comment]
Hi all,

I think at this point it's better to focus on why this is needed and getting a spec up to capture all the desired changes. This change as is raises more questions than it answers, so at this point I think it's better to discuss things in the bug (SPARK-10288) and close this PR until we have a workable spec.

**Comment by jerryshao** [comment]
OK, fine, I will close it.

**Pull request closed without merging**
