### PR TITLE
[SPARK-39154][PYTHON][DOCS] Remove outdated statements on distributed-sequence default index 

### PR DESCRIPTION
**Pull request by xinrong-meng**
### What changes were proposed in this pull request?
Remove outdated statements on distributed-sequence default index.

### Why are the changes needed?
Since distributed-sequence default index is updated to be enforced only while execution, there are stale statements in documents to be removed.

### Does this PR introduce _any_ user-facing change?
No. Doc change only.

### How was this patch tested?
Manual tests.

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master and branch-3.3.

**Comment by HyukjinKwon** [comment]
uhoh, the JIRA number was wrong.

**Comment by HyukjinKwon** [comment]
let me just revert and remerge .. I think it's trickier to switch the JIRA ..

**Comment by xinrong-databricks** [comment]
My bad.. Thanks @HyukjinKwon !

**Pull request closed without merging**
