### PR TITLE
[SPARK-43760][SQL] Nullability of scalar subquery results

### PR DESCRIPTION
**Pull request by agubichev**
### What changes were proposed in this pull request?
Makes sure that the results of scalar subqueries are declared as nullable. 

### Why are the changes needed?

This is an existing correctness bug, see https://issues.apache.org/jira/browse/SPARK-43760

### Does this PR introduce _any_ user-facing change?
Fixes a correctness issue, so it is user-facing.

### How was this patch tested?

Query tests.

### CODE REVIEW

**Comment by bersprockets** [comment]
Is there some setting needed to materialize the issue? Using the queries you added as tests (in `scalar-subquery-predicate.sql` and `scalar-subquery-select.sql`), I am getting your expected results on the master branch:
```
spark-sql (default)> select version();
3.5.0 5f325ec917ced819a19911b472ebf7eb52010203
Time taken: 2.69 seconds, Fetched 1 row(s)
spark-sql (default)> select *
                   > from range(1, 3) t1
                   > where (select sum(c) from (
                   >         select t2.id * t2.id c
                   >         from range (1, 2) t2 where t1.id = t2.id
                   >         group by t2.id
                   >        )
                   > ) is not null;
1
Time taken: 1.141 seconds, Fetched 1 row(s)
spark-sql (default)> select *
                   > from
                   > (
                   >  select t1.id c1, (
                   >                     select sum(c)
                   >                     from (
                   >                       select t2.id * t2.id c
                   >                       from range (1, 2) t2 where t1.id = t2.id
                   >                       group by t2.id
                   >                     )
                   >                    ) c2
                   >  from range (1, 3) t1
                   > ) t
                   > where t.c2 is not null;
1	1
Time taken: 0.404 seconds, Fetched 1 row(s)
spark-sql (default)> 
```

**Comment by sigmod** [comment]
@gengliangwang  @cloud-fan

**Review by jchen5 — APPROVED** [review]
Looks good!

**Comment by bersprockets** [comment]
Makes more sense now. Can you update the Jira as well?

**Comment by agubichev** [comment]
Updated Jira ticket too

**Comment by agubichev** [comment]
Conflicts are resolved.

**Review by cloud-fan — APPROVED** [review]

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Comment by dongjoon-hyun** [comment]
Thank you, @agubichev, @cloud-fan and all!
According to the affected version, `3.4.0`, can we have this at `branch-3.4` too?

**Comment by cloud-fan** [comment]
@agubichev can you open a backport PR for 3.4? thanks!

**Pull request closed without merging**
