### PR TITLE
[SPARK-21750][SQL] Use Arrow 0.6.0

### PR DESCRIPTION
**Pull request by kiszk**
## What changes were proposed in this pull request?

Update Arrow version to 0.6.0
Here is a [release note](http://arrow.apache.org/release/0.6.0.html).

## How was this patch tested?

Existing tests

### CODE REVIEW

**Comment by kiszk** [comment]
ping @srowen @ueshin @BryanCutler

**Comment by kiszk** [comment]
ping @srowen @ueshin @BryanCutler

**Comment by BryanCutler** [comment]
Thanks for this @kiszk.  I was thinking we would need to do an upgrade for DecimalType support.  I'm going to help out with that on the Arrow side, but it still might not be ready until 1 or 2 more releases.  I'm not sure what the general Spark stance is on updating dependencies like Arrow, but I can say that I did test 0.6 myself and did not see anything that might cause issues.  Maybe someone else can share the policies on upgrading?

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.
Since Apache Spark 2.3.0 is the debut of Apache Arrow in Spark, I think we had better to use the latest one.

**Comment by dongjoon-hyun** [comment]
According to #18459, I'm pining @holdenk and @cloud-fan , too.

**Comment by kiszk** [comment]
I agree with the usage of the latest one.
It would be good to periodically update a library if the library does not introduce drastic change (e.g. changing APIs) for ensuring stability for a longer period.
What do you think?

**Comment by cloud-fan** [comment]
I'm ok with it if arrow 0.6.0 doesn't introduce new dependencies.

**Comment by ueshin** [comment]
Do we need to upgrade pyarrow in Jenkins environment?
LGTM except for it.

**Comment by holdenk** [comment]
as with @rushing my primary concern with the upgrade here is the Jenkins interaction of when we eventually need to upgrade th Python side as well. It seems like we might not need to yet for 0.6.0 but I'm hesitant about having mixed versions since I believe that is explicitly not an arrow guarantee in general.

**Comment by kiszk** [comment]
Thank you for comments. I understand issues regarding Jenkins interaction in the Python side. I close this PR for now since the Python side is not ready for upgrading Arrow.

**Comment by dongjoon-hyun** [comment]
Hi, All.
Two more Arrow releases seem to be out. How about the Python side? Can we catch up some?
- 0.7.1 (1 October 2017)
- 0.7.0 (17 September 2017)

**Pull request closed without merging**
