### PR TITLE
[SPARK-42493][DOCS][PYTHON] Make Python the first tab for code examples - Spark SQL, DataFrames and Datasets Guide

### PR DESCRIPTION
**Pull request by aldogrut**
### What changes were proposed in this pull request?
Making Python the first tab for code examples in the Spark SQL, DataFrames and Datasets Guide.

### Why are the changes needed?
Python is the easiest approachable and most popular language so this change moves it to the first tab (showing by default) for code examples.

### Does this PR introduce _any_ user-facing change?
Yes, the user facing Spark documentation is updated.

### How was this patch tested?
I built the website locally and manually tested the pages.

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]
I like this. cc @srowen @dongjoon-hyun for more thoughts.

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
Sorry but I'm not sure this is the right direction, @HyukjinKwon and @allanf-db .

This PR aims to demote our defacto language, Scala, apparently. Shall we discuss this in the community first?

**Comment by HyukjinKwon** [comment]
+1 to raise a discussion thread in mailing list

**Comment by allanf-db** [comment]
Absolutely! Will start a thread @dongjoon-hyun.

**Comment by dongjoon-hyun** [comment]
Thank you, @allanf-db and @HyukjinKwon .

**Comment by dongjoon-hyun** [comment]
BTW, I changed the affected version of this JIRA from 3.4.0 to 3.5.0.
I don't think Apache Spark 3.4 needs this in any cases.

**Comment by allanf-db** [comment]
Attaching screenshot illustrating the change.
Current page on the left - Scala code example on the first tab.
New page on the right - Python code example on the first tab.

making_python_first_tab

**Comment by mateiz** [comment]
We should discuss this on the list, but I'm +1 on making Python first (in fact I suggested to Allan to do this). There are way more users of Spark in Python than Scala today, and people who want to see another language can just click that other tab. (In fact, if we want to make this better, we could even remember the language preference in a cookie and flip all tabs at the same time when you click one). Even our homepage at https://spark.apache.org has used Python for its example for a long time.

**Comment by srowen** [comment]
(FWIW I'm OK with showing Python first too)

**Comment by dongjoon-hyun** [comment]
Of course, I'm also open for discussion. IIRC, there are several issues like feature parity because Scala is still our first development language.

**Comment by HyukjinKwon** [comment]
Per the discussion in https://lists.apache.org/thread/1p8s09ysrh4jqsfd47qdtrl7rm4rrs05, I will merge this in with few days if there's no objection.

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by dongjoon-hyun** [comment]
Thank you all for initiating the official discussion. I also agree with the decision to merge this for Apache Spark 3.5.0.

**Pull request closed without merging**
