### PR TITLE
[SPARK-18697][BUILD] Upgrade sbt plugins

### PR DESCRIPTION
**Pull request by weiqingy**
## What changes were proposed in this pull request?

This PR is to upgrade sbt plugins. The following sbt plugins will be upgraded:
```
sbteclipse-plugin: 4.0.0 -> 5.0.1
sbt-mima-plugin: 0.1.11 -> 0.1.12
org.ow2.asm/asm: 5.0.3 -> 5.1 
org.ow2.asm/asm-commons: 5.0.3 -> 5.1 
```
## How was this patch tested?
Pass the Jenkins build.

### CODE REVIEW

**Comment by weiqingy** [comment]
Hi, @srowen  The previous [PR#16159](https://github.com/apache/spark/pull/16159#issuecomment-265000724) broke [spark-master-compile-sbt-scala-2.10 ](https://amplab.cs.berkeley.edu/jenkins/view/Spark%20QA%20Compile/job/spark-master-compile-sbt-scala-2.10/3301/consoleFull). As the console output shows, when running the command line “`build/sbt -mem 4096 -Phive -Phive-thriftserver -Pyarn -Phadoop-2.3 -Pkinesis-asl -Pspark-ganglia-lgpl -Pmesos -Dscala-2.10 assembly`”, it not only compiled the code but also ran the tests, which led to “`java.lang.OutOfMemoryError: Java heap space`”. That command line is supposed to compile the code without running the unit tests. 

To skip the test during assembly, we set “`test in assembly := {}`” in [object Assembly SparkBuild.scala](https://github.com/apache/spark/blob/master/project/SparkBuild.scala#L606). But the [PR#16159](https://github.com/apache/spark/pull/16159#issuecomment-265000724) upgraded sbt-assembly from 0.11.2 to 0.14.3, that made “test in assembly := {}” did not work. 
 
Need more time to dig it out. To make it safe, I did not upgrade sbt-assembly in this PR.

**Review by srowen — APPROVED** [review]
Thank you @weiqingy for the detailed investigation. You are our SBT expert now.

**Comment by weiqingy** [comment]
Thanks @srowen for the review.

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
