### PR TITLE
Create SparkAPSP.scala

### PR DESCRIPTION
**Pull request by deeppradhan**
The input to the program is an edge list file. The format should be the following, where each pair is an edge <src_id  dest_id>

1 2
2 1
2 3
2 4
3 2
3 3
4 2
4 3

### CODE REVIEW

**Comment by deeppradhan** [comment]
What does that mean?

On Wed, Feb 4, 2015 at 2:27 PM, UCB AMPLab <notifications@github.com> wrote:

> Can one of the admins verify this patch?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apache/spark/pull/4362#issuecomment-72811846>.
>



-- 
*Whether you think you can or you cannot.....either way you are right....*
With Regards...
Deep

**Comment by cloud-fan** [comment]
Have you checked the GraphX example https://spark.apache.org/docs/latest/graphx-programming-guide.html#pregel-api? It implemented single source shortest path.

**Comment by deeppradhan** [comment]
Yes, I have checked it out. This one is on pure Spark.

**Comment by ankurdave** [comment]
ok to test

**Comment by deeppradhan** [comment]
Do I need to add the license headers in the file?
The one which is there within /*Licensed to..........under the license*/  in every file in the Spark examples? Or do I have to sign up any license?

**Comment by deeppradhan** [comment]
Do I need to submit another pull request for this new file?

**Comment by srowen** [comment]
(You need a JIRA) What's the value of this example, if it's showing a graph algorithm without GraphX and doesn't use its format or abstractions? you can host any example you like on github; why should this be a part of Spark?

**Comment by deeppradhan** [comment]
The error file says that a particular line contains a tab, but I have removed it. The error log says the same thing again. What does this mean?

**Comment by cloud-fan** [comment]
You could run `./dev/scalastyle` in your spark dir to check the style locally before push to github. And I think [this page](https://cwiki.apache.org/confluence/display/SPARK/Contributing+to+Spark) is helpful for new contributors.

**Comment by deeppradhan** [comment]
Thank You Fan,
I rewrote the whole thing and the error have gone.
I will surely do that next time I try pulling a request.

On Thu, Feb 5, 2015 at 10:23 AM, Wenchen, Fan <notifications@github.com>
wrote:

> You could run ./dev/scalastyle in your spark dir to check the style
> locally before push to github. And I think this page
> <https://cwiki.apache.org/confluence/display/SPARK/Contributing+to+Spark>
> is helpful for new contributors.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apache/spark/pull/4362#issuecomment-72994165>.
>



-- 
*Whether you think you can or you cannot.....either way you are right....*
With Regards...
Deep

**Comment by rxin** [comment]
Hi @deeppradhan

Thanks for submitting the patch. This is much more sophisticated than the usual examples we have. Examples we include typically are there as examples on how to use the API.

This seems like something you can easily host on your site. Do you mind closing the pull request and host it somewhere else?

**Comment by JoshRosen** [comment]
I agree; let's close this issue for now.

**Comment by srowen** [comment]
Mind closing this PR?

**Comment by andrewor14** [comment]
@deeppradhan would you mind closing this PR? From the comments of the other committers it seems unlikely to be merged at this point.

**Pull request closed without merging**
