### PR TITLE
[SPARK-43225][BUILD][SQL] Remove jackson-core-asl and jackson-mapper-asl from pre-built distribution

### PR DESCRIPTION
**Pull request by wangyum**
### What changes were proposed in this pull request?

- Remove `jackson-core-asl` from maven dependency.
- Change the scope of `jackson-mapper-asl` from compile to test.
- Replace all `Hive.get(conf)` with `Hive.getWithoutRegisterFns(conf)`.

### Why are the changes needed?

To fix CVE issue: https://github.com/apache/spark/security/dependabot/50.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

manual test.

### CODE REVIEW

**Comment by pan3793** [comment]
It drops support for building w/ pre Hive 2.3.9, then SPARK-37446 can be reverted.

**Comment by bjornjorgensen** [comment]
CC @srowen

**Comment by srowen** [comment]
Is this possible now that Hadoop 2 support is gone? just checking what the implications of this change are.
Are the Hive.get changes needed, or can we batch those changes with reverting the Hive <2.3.9 support? I also don't know what the implication of that is.

**Comment by pan3793** [comment]
@srowen 

> Are the `Hive.get` changes needed

Yes, `Hive.get(conf)` triggers the Hive built-in JSON functions initialization, which requires the Jackson 1.x classes.

@sunchao I suppose Spark does not officially support building against Hive other than 2.3.9, for cases listed in SPARK-37446, it's the vendor's responsibility to port HIVE-21563 into their maintained Hive 2.3.8-[vender-custom-version]

**Comment by pan3793** [comment]
@sunchao can we expect a new release(focus on security) for Hive 2.3? Considering Spark master and all maintained branches use Hive 2.3.9, which was reported some CVEs e.g. thrift, guava, log4j, jackson.

Or, Spark should move forward to a new Hive version. (should take much effort and not sure of benefits other than getting rid of CVEs)

**Comment by sunchao** [comment]
@pan3793 AFAIK the development efforts in Hive community are only in Hive 3.x/4.x at the moment, and the 2.x branch is barely maintained. I can try to start a conversation in the Hive community to have a new 2.3.10 release and see how it looks like.

From the long term perspective, it'd be better for Spark to move to Hive 3.x/4.x.

**Comment by srowen** [comment]
OK, am I right that this does not make Spark any _less_ compatible with any version of Hive that is currently supported (>= 2.3.9)? If so then this is fine

**Comment by pan3793** [comment]
> OK, am I right that this does not make Spark any _less_ compatible with any version of Hive that is currently supported (>= 2.3.9)? If so then this is fine

Yes.

**Comment by srowen** [comment]
Merged to master

**Comment by Madhukar525722** [comment]
HI @pan3793 @dongjoon-hyun . Since, the spark 4.0.0 has been upgraded to hive 2.3.10 and hadoop 3.3.6. Cant we now implement this change back to remove jackson-mapper-asl and jackson-core-asl

**Comment by dongjoon-hyun** [comment]
Hi, @Madhukar525722 . No, we can't because the existing users have Hive UDF jars which are built against old Hive 2.3.9 and older. Technically, we cannot enforce Apache Spark users to rebuilt every Hive UDF jars in their company. Actually, no user wants to rebuild all their Hive UDF jars against on newly arrived Hive 2.3.10.

> HI @pan3793 @dongjoon-hyun . Since, the spark 4.0.0 has been upgraded to hive 2.3.10 and hadoop 3.3.6. Cant we now implement this change back to remove jackson-mapper-asl and jackson-core-asl from pre-built distribution

However, Apache Spark community provides an alternative way in order to remove them from `jars` directory at Apache Spark 4.0.0 `jars` directory by isolating them into another directory `hive-jackson`.
- #45237
- #45201

Here are the difference between Apache Spark 4.0.0-preview2 and Apache Spark 3.5.4 .
```
$ ls spark-3.5.4-bin-hadoop3/jars/*asl*
spark-3.5.4-bin-hadoop3/jars/jackson-core-asl-1.9.13.jar   spark-3.5.4-bin-hadoop3/jars/jackson-mapper-asl-1.9.13.jar

$ ls spark-4.0.0-preview2-bin-hadoop3/jars/*asl*
zsh: no matches found: spark-4.0.0-preview2-bin-hadoop3/jars/*asl*
```

Please try to use Apache Spark 4.0.0-preview2 and let us know your pain point, @Madhukar525722 .

**Comment by Madhukar525722** [comment]
Hi @dongjoon-hyun 
I tried replicating SPARK-44719, it failed with hive 2.3.9, as expected. Once i upgraded inbuilt hive 2.3.10 and removed jackson-core-asl and jackson-mapper-asl, the issue was not coming. Are there more identified similar scenarios of failure?

**Comment by pan3793** [comment]
@Madhukar525722 I think either upgrading Hive 2.3.10 or applying SPARK-51466 should allow Spark to get rid of `jackson-core-asl` and `jackson-mapper-asl`, see tech details at https://github.com/apache/spark/pull/46521 and https://github.com/apache/spark/pull/50232.

"SPARK-48231 Remove unused CodeHaus Jackson dependencies" is on the 4.1 roadmap. (I think it also could be done in 4.0, and we do remove them in our internal 4.0 distribution, but given 4.0.0 has reached RC3, might be too late)

**Pull request closed without merging**
