### PR TITLE
[SPARK-50373] Prohibit Variant from set operations

### PR DESCRIPTION
**Pull request by harshmotw-db**
### What changes were proposed in this pull request?

Prior to this PR, Variant columns could be used with set operations like `DISTINCT`, `INTERSECT` and `EXCEPT`. This PR prohibits this behavior since Variant is not orderable.

### Why are the changes needed?

Variant equality is not defined, and therefore, these operations are also undefined.

### Does this PR introduce _any_ user-facing change?

Yes, users will now no longer be able to perform set operations on variant columns.

### How was this patch tested?

Unit tests

### Was this patch authored or co-authored using generative AI tooling?

No

### CODE REVIEW

**Comment by harshmotw-db** [comment]
@gene-db @cloud-fan Can you please look at this? Thanks!

**Review by gene-db — APPROVED** [review]
@harshmotw-db Thanks catching the undefined behavior!

LGTM

**Review by dtenedor — APPROVED** [review]
LGTM, we should probably not allow these until we can think about it further. What about GROUP BY and SELECT DISTINCT, should we prohibit those too?

**Comment by harshmotw-db** [comment]
@dtenedor This PR prohibits `select distinct`, and `GROUP BY` was [already disabled](https://github.com/apache/spark/blob/ad46db4ef671d8829dfffba2780ba0f6b4f4e43d/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/ExprUtils.scala#L203). It was believe that this code path would also disable other operations which require grouping but apparently not.

**Review by cloud-fan — APPROVED** [review]

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Pull request closed without merging**
