### PR TITLE
[SPARK-34158] Incorrect url of the only developer Matei in pom.xml

### PR DESCRIPTION
**Pull request by pingsutw**
### What changes were proposed in this pull request?

Update the Incorrect URL of the only developer Matei in pom.xml

### Why are the changes needed?

The current link was broken

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

change the link to https://cs.stanford.edu/people/matei/

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Okay, simply fixing link itself is fine.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master and branch-3.1.

**Comment by HyukjinKwon** [comment]
@pingsutw, what's your JIRA id? can you add a comment in the JIRA so I can assign the ticket to you?

**Comment by pingsutw** [comment]
@HyukjinKwon Thanks for the review. My Jira ID is `pingsutw`.

**Pull request closed without merging**
