### PR TITLE
[SPARK-10835] [ML] Word2Vec should accept non-null string array, in addition to existing null string array

### PR DESCRIPTION
**Pull request by srowen**
## What changes were proposed in this pull request?

To match Tokenizer and for compatibility with Word2Vec, output a nullable string array type in NGram
## How was this patch tested?

Jenkins tests.

### CODE REVIEW

**Comment by srowen** [comment]
This change merely parallels https://github.com/apache/spark/pull/7414 from @hhbyyh  (what do you think?) I'd still sort of like to understand why we didn't 'fix' Word2Vec instead in that change?

**Comment by hhbyyh** [comment]
Hi @srowen. By fixing `Word2Vec`, do you mean to change its input type to `Array(String, false)`?

I cannot recall all the details. Right now I think the primary reason is to be consistent with auto schema inference, thus to support usage like https://github.com/apache/spark/blob/180fd3e0a3426db200c97170926afb60751dfd0e/examples/src/main/scala/org/apache/spark/examples/ml/Word2VecExample.scala

**Comment by srowen** [comment]
Or really to have it accept an array of strings, whether nullable or not. Right now it can accept a nullable string array type, but will pointlessly reject input that is _not_ nullable. The check is too strict. We could just loosen that and then any string array input would work, which seems like the idea?

**Comment by hhbyyh** [comment]
I'm not sure what will happen if we actually send an `Array(String, false)` column to Word2Vec. If nothing goes wrong, I think we can loosen the constraint.

I'll try something locally.

**Comment by hhbyyh** [comment]
Checked locally and Word2Vec can work with `Array(String, false)`. We can loosen the constraint. Maybe a new UT can be added.

**Comment by srowen** [comment]
I think the problem is that it won't accept anything that outputs `Array(String, true)`? it seems like it's looking for exactly the same type. Elsewhere I see a similar check written so as to not have to match nullability.

**Comment by hhbyyh** [comment]
`CountVectorizer` can accept both `Array(String, true)` and `Array(String, false)`. Perhaps we can just change the validation code.

**Comment by srowen** [comment]
Yes that's better IMHO. It makes this more consistent. Word2Vec was the only case that looked for an exact match on nullability when it was expecting nullable input (i.e. pointlessly disallowed non-null input)

**Comment by hhbyyh** [comment]
LGTM. How about adding an UT for the input type new ArrayType(StringType, false)?

**Comment by srowen** [comment]
Sorry, what's a UT here? user defined type?

**Comment by hhbyyh** [comment]
Sorry, I meant unit test

**Comment by jkbradley** [comment]
Accepting more input types SGTM too (with unit tests).  The PR title and description (and perhaps the JIRA too) should be updated.  Thanks!

**Comment by hhbyyh** [comment]
Thanks Sean. LGTM.

**Comment by srowen** [comment]
Merged to master/2.0

**Pull request closed without merging**
