### PR TITLE
[SPARK-44581][YARN] Fix the bug that ShutdownHookManager get wrong hadoop user group information

### PR DESCRIPTION
**Pull request by liangyu-1**
### What changes were proposed in this pull request?

I make the SecurityManager instance a lazy value 

### Why are the changes needed?

fix the bug in issue [SPARK-44581](https://issues.apache.org/jira/browse/SPARK-44581)

**Bug:**
In spark3.2 it throws the org.apache.hadoop.security.AccessControlException, but in spark2.4 this hook does not throw exception.

I rebuild the hadoop-client-api.jar, and add some debug log before the hadoop shutdown hook is created, and rebuild the spark-yarn.jar to add some debug log when creating the spark shutdown hook manager, here is the screenshot of the log: 
image

We can see from the screenshot, the ShutdownHookManager is initialized before the ApplicationManager create a new ugi.

**Reason**

The main cause is that ShutdownHook thread is created before we create the ugi in ApplicationMaster.

When we set the config key "hadoop.security.credential.provider.path", the ApplicationMaster will try to get a filesystem when generating SSLOptions, and when initialize the filesystem during which it will generate a new thread whose ugi is inherited from the current process (yarn).
After this, it will generate a new ugi (SPARK_USER) in ApplicationMaster and execute the doAs() function.

Here is the chain of the call:
ApplicationMaster.(ApplicationMaster.scala:83) -> org.apache.spark.SecurityManager.(SecurityManager.scala:98) -> org.apache.spark.SSLOptions$.parse(SSLOptions.scala:188) -> org.apache.hadoop.conf.Configuration.getPassword(Configuration.java:2353) -> org.apache.hadoop.conf.Configuration.getPasswordFromCredentialProviders(Configuration.java:2434) -> org.apache.hadoop.security.alias.CredentialProviderFactory.getProviders(CredentialProviderFactory.java:82)

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

I didn't add new UnitTest for this, but I rebuild the package, and runs a program in my cluster, and turns out that the user when I delete the staging file turns to be the same with the SPARK_USER.

### CODE REVIEW

**Comment by liangyu-1** [comment]
cc @mridulm @tgravescs @HeartSaVioR

**Comment by yaooqinn** [comment]
The staging directory is cleaned automatically by Spark, why do you even need this hook？

**Comment by liangyu-1** [comment]
> The staging directory is cleaned automatically by Spark, why do you even need this hook？

@yaooqinn 
Spark cleans the staging directory in this Hook, in spark 2.4 it will clean the directory correctly, but in spark3.2 it will throw exception during the cleaning action.

**Comment by yaooqinn** [comment]
I see where the hook added.

But I have checked some of our online apps versioned 3.1 and 3.3, the stagings are deleted successfully. Is it a 3.2-specific issue?

**Comment by liangyu-1** [comment]
> I see where the hook added.
> 
> But I have checked some of our online apps versioned 3.1 and 3.3, the stagings are deleted successfully. Is it a 3.2-specific issue?

I don't think it's a 3.2-specific issue, sure that it will delete the staging files at last, but when I checked the hdfs-audit logs, I found that there were 2 operations to delete the staging file, the first operation is to delete by the driver which will throw exception, the other operation is to delete the staging file by the client where you submit your apps, which succeeded. 
The two deletion operations were performed by different users on different machines.

**Comment by yaooqinn** [comment]
If it's not 3.2-specific, and everything is OK on my side by checking the hdfs audit log too, I guess it could be an environment or configuration issue of yours.

**Review by mridulm — COMMENTED** [review]
+CC @tgravescs who has more context on this.
On the face of it, this looks ok, but would be good to get more eyes on this.

**Comment by mridulm** [comment]
+CC @zhouyejoe as well

**Comment by yangjiandan** [comment]
although there is an execeptin in applicationMaster, staging directory will also be cleaned successful when running on cluster mode, because spark client also executes cleaning. but i think this is a bug and we should fix it.

**Comment by lvkaihua** [comment]
I also encountered this problem in my environment, and I did not use tools such as ranger here.

**Comment by liangyu-1** [comment]
The main cause is that ShutdownHook thread is created before we create the ugi in ApplicationMaster.

When we set the config key _"hadoop.security.credential.provider.path"_, the ApplicationMaster will try to get a filesystem when generating SSLOptions, and when initialize the filesystem during which it will generate a new thread whose ugi is inherited from the current process (yarn).
After this, it will generate a new ugi (SPARK_USER) in ApplicationMaster and execute the doAs() function.

Here is the chain of the call:
ApplicationMaster.<init>(ApplicationMaster.scala:83) -> org.apache.spark.SecurityManager.<init>(SecurityManager.scala:98) -> org.apache.spark.SSLOptions$.parse(SSLOptions.scala:188) -> org.apache.hadoop.conf.Configuration.getPassword(Configuration.java:2353) -> org.apache.hadoop.conf.Configuration.getPasswordFromCredentialProviders(Configuration.java:2434) -> org.apache.hadoop.security.alias.CredentialProviderFactory.getProviders(CredentialProviderFactory.java:82)

**Comment by yaooqinn** [comment]
Hi, @liangyu-1, thanks for the detailed information.

Looks like we can either make the SecurityManager instance a lazy value or move the ApplicationMaster instantiating and assignment inside the `doAs` block.

**Review by yaooqinn — APPROVED** [review]

**Comment by liangyu-1** [comment]
I moved the  ApplicationMaster instantiating and assignment inside the doAs block, and I rebuild the project and test it on my cluster, the shutdown hook thread now has the correct ugi.

**Comment by yaooqinn** [comment]
LGTM, please update the PR description according the code updates so far

**Comment by yaooqinn** [comment]
Hi @liangyu-1, please also take care of the CI

**Comment by liangyu-1** [comment]
Hi @yaooqinn, I have changed my ci, please help me check if it's ok now.

**Comment by yaooqinn** [comment]
It's not OK https://github.com/apache/spark/actions/runs/5794118171/job/15703082268?pr=42295

**Comment by liangyu-1** [comment]
Hi, @yaooqinn  I encountered this problem and have no idea about what to do next:
Ref: SPARK-44581
SHA: e0a6db4d5d04c1a43e91e13c263be47b65441a9b
TypeError: Cannot read properties of undefined (reading 'head_sha')
    at eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:15143:16), <anonymous>:81:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async main (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:15236:20)
Error: Unhandled error: TypeError: Cannot read properties of undefined (reading 'head_sha')

**Comment by yaooqinn** [comment]
(I'm not sure but,) You may sync apache/spark master branch with the one in your fork

**Comment by liangyu-1** [comment]
It's the problem that I changed my action permissions, I have reset it and everything is OK now.
thanks a lot @yaooqinn

**Pull request closed without merging**
