### PR TITLE
[SPARK-16280][SQL] Implement histogram_numeric SQL function

### PR DESCRIPTION
**Pull request by tilumi**
## What changes were proposed in this pull request?

This PR implements histogram_numeric according to the Algorithm I & II on the paper: Yael Ben-Haim and Elad Tom-Tov, "A streaming parallel decision tree algorithm", J. Machine Learning Research 11 (2010), pp. 849--872.
## How was this patch tested?

I add a test "SPARK-16280: test histogram_numeric." and "SPARK-16280: skip null when computing histogram_numeric." in DataFrameAggregateSuite.

### CODE REVIEW

**Comment by hvanhovell** [comment]
@tilumi could show some benchmarks for this? I think that this will have some performance problems. Using an array in a DeclarativeAggregate is not the most efficient.

**Comment by tilumi** [comment]
Ok, I'll change the implementation to non-array version and run benchmark on both versions.

**Comment by tilumi** [comment]
May I ask why an array in DeclarativeAggregate is not the most efficient??

**Comment by tilumi** [comment]
I think the cause may be it'll use sortAggregation instead of hashaggregation if I use array as an buffer

**Comment by tilumi** [comment]
I Implement 3 kinds of histogram_numeric and the result is 

      (100000, 100)).map((pair) => {

**Comment by tilumi** [comment]
According to the result, I figured out the performance  of the  codegen version is bounded by the number of bins since the large generated code for array creation.

**Comment by tilumi** [comment]
I'll improve it

**Comment by tilumi** [comment]
I finally come out a optimal solution. Since the number of attributes in aggregation buffer is linear to generated code size & code generation time, I instead use just one attribute with array type.

The benchmark result is:

|(rows, numOfBins)|codegen_with_arrayAggBuffer_histogram_numeric|codegen_histogram_numeric|declarative_histogram_numeric|imperative_histogram_numeric|
|-----------------|-----------------------------------------------|-------------------------|-----------------------------|----------------------------|
|           (10,1)|                                            346|                      166|                          186|                         336|
|          (10,10)|                                            132|                      209|                          136|                         203|
|         (10,100)|                                            138|                     1967|                          226|                         261|
|         (1000,1)|                                            128|                      140|                          159|                         222|
|        (1000,10)|                                            122|                      154|                          181|                         265|
|       (1000,100)|                                            131|                     1690|                          300|                         494|
|       (100000,1)|                                            169|                      188|                          561|                         729|
|      (100000,10)|                                            219|                      506|                         1609|                        1901|
|     (100000,100)|                                            331|                     3926|                         6371|                        8394|

I'll polish the PR for reviewing

**Comment by tilumi** [comment]
I optimized the 'codeGenWithArrayAggBufferNumericHistogram' algorithm and the benchmark result is:

|(rows, numOfBins)|codegen_with_array_agg_buffer_histogram_numeric|codegen_histogram_numeric|declarative_histogram_numeric|imperative_histogram_numeric|
|-----------------|-----------------------------------------------|-------------------------|-----------------------------|----------------------------|
|           (10,1)|                                            472|                      248|                          263|                         708|
|          (10,10)|                                            180|                      250|                          166|                         328|
|         (10,100)|                                            260|                     2023|                          170|                         226|
|         (1000,1)|                                            101|                      135|                          183|                         208|
|        (1000,10)|                                            122|                      164|                          162|                         230|
|       (1000,100)|                                            137|                     1902|                          367|                         546|
|       (100000,1)|                                            219|                      311|                          860|                         864|
|      (100000,10)|                                            231|                      447|                         1417|                        1543|
|     (100000,100)|                                            354|                     3345|                         8739|                        8155|

**Comment by tilumi** [comment]
It's ready for review.

**Comment by yangyangyyy** [comment]
would love to have this. 

also can we also have the same functionality not only in sql, but for RDD/Dataset too?

**Comment by windpiger** [comment]
ping @tilumi someone can review this?

**Comment by cenyuhai** [comment]
Is this pr available?

**Comment by cloud-fan** [comment]
CC @wzhfy have we already implemented it during the histogram work?

**Comment by wzhfy** [comment]
@cloud-fan I think this PR is to implement Hive's `histogram_numeric` function. It produces a histogram to approximate data distribution. It's different from standard equi-width or equi-height histogram used in estimation.

**Comment by iceted** [comment]
When is this going to be available?

**Comment by rolandjohann** [comment]
@hvanhovell @cloud-fan @wzhfy can you verify this patch that it can get merged? Sad to see that such a useful implementation gets orphaned caused by missing feedback by maintainers

**Pull request closed without merging**
