### PR TITLE
[SPARK-20211][SQL]Fix a bug in FLOOR and CEIL when a decimal's precision < scale

### PR DESCRIPTION
**Pull request by stanzhai**
## What changes were proposed in this pull request?

`precision` in a decimal indicates the length of the arbitrary precision integer. Here are a few examples of numbers with the same scale, but different precision:

- 12345 / 100000 = 0.12345 // scale = 5, precision = 5
- 12340 / 100000 = 0.1234 // scale = 5, precision = 4
- 1 / 100000 = 0.00001 // scale = 5, precision = 1

This PR fix a bug in `floor` and `ceil` in `org.apache.spark.sql.types.Decimal` that will throw a `Decimal scale (0) cannot be greater than precision (-2)` exception when its `precision < scale`.

Before the fix, the following SQL will throw an exception:

```
select 1 > 0.0001 from tb
select floor(0.0001) from tb
select ceil(0.0001) from tb
```

## How was this patch tested?

Added unit tests.

### CODE REVIEW

**Comment by stanzhai** [comment]
cc @chenghao-intel

**Comment by stanzhai** [comment]
cc @gatorsmile

**Comment by gatorsmile** [comment]
We might need to fix it in a different way. Let me play with it.

**Comment by gatorsmile** [comment]
@stanzhai Could you review my fix in https://github.com/apache/spark/pull/18244? Does it resolve your issue? Thanks!

**Comment by gatorsmile** [comment]
The PR is merged. Could you close this? Thanks!

**Pull request closed without merging**
