### PR TITLE
[SPARK-30950][BUILD] Setting version to 3.1.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by gatorsmile**
### What changes were proposed in this pull request?
This patch is to bump the master branch version to 3.1.0-SNAPSHOT.

### Why are the changes needed?
N/A

### Does this PR introduce any user-facing change?
N/A

### How was this patch tested?
N/A

### CODE REVIEW

**Comment by gatorsmile** [comment]
cc @cloud-fan @yhuai @srowen

**Review by srowen — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Review by HyukjinKwon — APPROVED** [review]

**Review by cloud-fan — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
BTW, currently, PRBuilder seems to skip Pandas Python tests and Arrow R tests.
```
test_register_nondeterministic_vectorized_udf_basic 
(pyspark.sql.tests.test_pandas_udf_scalar.ScalarPandasUDFTests)
... skipped u'Pandas >= 0.23.2 must be installed; however, your version was 0.19.2.'
```
```
test_sparkSQL_arrow.R:25: skip: createDataFrame/collect Arrow optimization
arrow cannot be loaded
```

**Comment by dongjoon-hyun** [comment]
Merged to master.

**Comment by HyukjinKwon** [comment]
Yeah, we should install Arrow R to test it out. cc @shaneknapp 

```
test_sparkSQL_arrow.R:25: skip: createDataFrame/collect Arrow optimization
arrow cannot be loaded
```

At least it's being tested in AppVeyor currently.

```
test_register_nondeterministic_vectorized_udf_basic 
(pyspark.sql.tests.test_pandas_udf_scalar.ScalarPandasUDFTests)
... skipped u'Pandas >= 0.23.2 must be installed; however, your version was 0.19.2.'
```

It's being tested in Python 3 but not in Python 2.7. We should test it ideally but might be fine as we're going to remove it away very soon in the master.

**Comment by shaneknapp** [comment]
FYI, i can't keep up w/all of the @ mentions on github.  please file jiras
and assign them to me.

also, R is a nightmare to install and manage, so these upgrades are not as
simple as they might seem.

**Comment by h-vetinari** [comment]
> @shaneknapp: also, R is a nightmare to install and manage, so these upgrades are not as
simple as they might seem.

Conda is able to install R and takes *a lot* of the hassle out of it (I'd say effectively all of it, except the effort of setting up conda in the CI jobs).

**Comment by shaneknapp** [comment]
> > @shaneknapp: also, R is a nightmare to install and manage, so these upgrades are not as
> > simple as they might seem.
> 
> Conda is able to install R and takes _a lot_ of the hassle out of it (I'd say effectively all of it, except the effort of setting up conda in the CI jobs).

i experimented w/conda and R, and i was having lots of issues with activating environments and keeping a sane `PATH` that didn't have conflicts between the conda python environments that these builds rely on.

after spending a few hours tearing my hair out over this (which was proceeded by a couple of days tying to find the combination of R 3.4.x apt packages + libraries to install via `install.packages`), i gave up and just installed the latest and greatest apt packages R 3.6.3 and a bunch of associated libraries.

via apt:
```
      - r-base-core
      - r-base-dev
      - r-cran-rjava
      - r-cran-rodbc
      - r-mathlib
```

via `install.packages()`:
```
    - digest
    - knitr
    - devtools
    - plyr
    - roxygen2
    - rmarkdown
    - e1071
    - testthat
```

via `devtools::install_github()`:
```
jimhester/lintr@v2.0.0
```

all R tests pass, and i'm about to enable these two ubuntu 18 workers in the jenkins pool and allow 3.0 and master builds to run on them.  see:  https://amplab.cs.berkeley.edu/jenkins/label/ubuntu-18/

i'm also about to duplicate this setup on the ubuntu 16 workers as well.

the pull request builder job runs on centos 6.9 (yeah, i know.  working on that...) and are running R 3.5.X which should be fine until i'm able to decommission them.

**Comment by shaneknapp** [comment]
> Yeah, we should install Arrow R to test it out. cc @shaneknapp
> 
> ```
> test_sparkSQL_arrow.R:25: skip: createDataFrame/collect Arrow optimization
> arrow cannot be loaded
> ```
> 
yeah, this is on my list, but getting this set up and working is (sadly) more than just `install.packages('arrow')`.

> ```
> test_register_nondeterministic_vectorized_udf_basic 
> (pyspark.sql.tests.test_pandas_udf_scalar.ScalarPandasUDFTests)
> ... skipped u'Pandas >= 0.23.2 must be installed; however, your version was 0.19.2.'
> ```
> 
> It's being tested in Python 3 but not in Python 2.7. We should test it ideally but might be fine as we're going to remove it away very soon in the master.

i can try and update pandas for py2.7...  we haven't been testing 2.7 against pandas for QUITE a while and if i'm going to focus my effort on something, this will have to be very low on my priority stack.

**Pull request closed without merging**
