### PR TITLE
[SPARK-13410][SQL] Support unionAll for DataFrames with UDT columns.

### PR DESCRIPTION
**Pull request by damnMeddlingKid**
## What changes were proposed in this pull request?

This PR adds equality operators to UDT classes so that they can be correctly tested for dataType equality during union operations.

This was previously causing `"AnalysisException: u"unresolved operator 'Union;""` when trying to unionAll two dataframes with UDT columns as below.

```
from pyspark.sql.tests import PythonOnlyPoint, PythonOnlyUDT
from pyspark.sql import types

schema = types.StructType([types.StructField("point", PythonOnlyUDT(), True)])

a = sqlCtx.createDataFrame([[PythonOnlyPoint(1.0, 2.0)]], schema)
b = sqlCtx.createDataFrame([[PythonOnlyPoint(3.0, 4.0)]], schema)

c = a.unionAll(b)
```
## How was the this patch tested?

Tested using two unit tests in sql/test.py and the DataFrameSuite. 

Additional information here : https://issues.apache.org/jira/browse/SPARK-13410

### CODE REVIEW

**Comment by rxin** [comment]
cc @davies

**Comment by davies** [comment]
LGTM, pending on tests.

**Comment by damnMeddlingKid** [comment]
That should be it.

**Comment by rxin** [comment]
One of the unit test runs failed. Maybe it is flaky?

**Comment by damnMeddlingKid** [comment]
Yeah I think its just the order of the output. I've made the ordering more explicit now, i've run these tests on my local machine and they pass.

**Comment by rxin** [comment]
I will merge it once tests pass 3 times in a row.

**Comment by rxin** [comment]
Going to merge this in master.

**Comment by damnMeddlingKid** [comment]
@rxin any chance this will make it into 1.6.1 ?

**Comment by rxin** [comment]
This didn't merge cleanly -- can you submit a patch against branch-1.6 asap and I can merge into it.

**Pull request closed without merging**
