### PR TITLE
[SPARK-32018][SQL][FollowUp][3.0] Throw exception on decimal value overflow of sum aggregation

### PR DESCRIPTION
**Pull request by gengliangwang**
### What changes were proposed in this pull request?

This is a followup of https://github.com/apache/spark/pull/29125
In branch 3.0: 
1. for hash aggregation, before https://github.com/apache/spark/pull/29125 there will be a runtime exception on decimal overflow of sum aggregation; after https://github.com/apache/spark/pull/29125, there could be a wrong result.
2. for sort aggregation, with/without https://github.com/apache/spark/pull/29125, there could be a wrong result on decimal overflow.

While in master branch(the future 3.1 release), the problem doesn't exist since in https://github.com/apache/spark/pull/27627 there is a flag for marking whether overflow happens in aggregation buffer. However, the aggregation buffer is written in steaming checkpoints. Thus, we can't change to aggregation buffer to resolve the issue. 

As there is no easy solution for returning null/throwing exception regarding `spark.sql.ansi.enabled` on overflow in branch 3.0, we have to make a choice here: always throw exception on decimal value overflow of sum aggregation.
### Why are the changes needed?

Avoid returning wrong result in decimal value sum aggregation.

### Does this PR introduce _any_ user-facing change?

Yes, there is always exception on decimal value overflow of sum aggregation, instead of a possible wrong result.

### How was this patch tested?

Unit test case

### CODE REVIEW

**Comment by gengliangwang** [comment]
cc @cloud-fan @skambha @dongjoon-hyun @ScrapCodes

**Comment by cloud-fan** [comment]
This adds perf overhead as we need to check overflow after each Add operation, while the master branch only checks overflow at the end because we have an extra agg buffer slot.

I think this perf overhead is necessary to avoid this correctness bug in 3.0/2.4, but I'm open to other opinions. cc @skambha @dongjoon-hyun @viirya @maropu

**Comment by viirya** [comment]
> However, the aggregation buffer is written in steaming checkpoints. Thus, we can't change to aggregation buffer to resolve the issue.

Is this saying the `isEmpty` in `Sum` cannot be backported to branch-3.0?

**Comment by viirya** [comment]
And looks like we don't have many choices. I think correctness should be considered first.

**Comment by cloud-fan** [comment]
> Is this saying the isEmpty in Sum cannot be backported to branch-3.0?

I think so. 3.0 doesn't even have mechanisms to detect incompatible state store format, and it may be too much work to backport the bug fix and the streaming state store checks.

**Comment by maropu** [comment]
>> And looks like we don't have many choices. I think correctness should be considered first.

I have the same opnion with @viirya, and I think the overhead is inevitable.

**Comment by dongjoon-hyun** [comment]
Thank you for pinging me, @cloud-fan .

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by cloud-fan** [comment]
thanks for the review, merging to 3.0!

**Comment by dongjoon-hyun** [comment]
Thank you all!

**Comment by maropu** [comment]
It seems this commit caused the valid test failure in `DataFarmeSuite`;
```
[info] - SPARK-28224: Aggregate sum big decimal overflow *** FAILED *** (384 milliseconds)
[info]   org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 77.0 failed 1 times, most recent failure: Lost task 0.0 in stage 77.0 (TID 197, 192.168.11.10, executor driver): java.lang.ArithmeticException: Decimal(expanded,111111111111111111110.246000000000000000,39,18}) cannot be represented as Decimal(38, 18).
[info] 	at org.apache.spark.sql.types.Decimal.toPrecision(Decimal.scala:369)
[info] 	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage2.agg_doAggregate_sum_0$(Unknown Source)
[info] 	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage2.agg_doConsume_0$(Unknown Source)
[info] 	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage2.agg_doAggregateWithoutKey_0$(Unknown Source)
[info] 	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage2.processNext(Unknown Source)
[info] 	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
```
https://amplab.cs.berkeley.edu/jenkins/view/Spark%20QA%20Test%20(Dashboard)/job/spark-branch-3.0-test-maven-hadoop-2.7-hive-2.3/533/

I've checked that the test failed w/this commit and  passed w/o it in my local env.
@gengliangwang Could you check the failure?

**Comment by gengliangwang** [comment]
@maropu Thanks for reporting. I have created https://github.com/apache/spark/pull/29448.

**Comment by cloud-fan** [comment]
ah it's branch-3.0 so the github action doesn't count. @HyukjinKwon how hard it is to have github action in branch-3.0?

**Comment by HyukjinKwon** [comment]
@cloud-fan, I will port it back to other branches. I think it's doable.

**Pull request closed without merging**
