### PR TITLE
[SPARK-30918][SQL][followup] Fix typo in OptimizeSkewedJoin

### PR DESCRIPTION
**Pull request by cloud-fan**
### What changes were proposed in this pull request?

This is a follow up of #27669 in order to fix a typo.

### Why are the changes needed?

N/A

### Does this PR introduce any user-facing change?

no

### How was this patch tested?

N/A

### CODE REVIEW

**Comment by cloud-fan** [comment]
cc @dongjoon-hyun

**Comment by kiszk** [comment]
Is this title correct? It seems to be `[SPARK-30842]`. It is also good to include `#27669` in the description.

**Comment by dongjoon-hyun** [comment]
Thank you, @cloud-fan and @kiszk . I addressed @kiszk 's comment.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Merged to master/3.0.

**Comment by kiszk** [comment]
late LGTM
@dongjoon-hyun thanks

**Pull request closed without merging**
