### PR TITLE
[SPARK-10496][SQL] Add DataFrame cumulative sum

### PR DESCRIPTION
**Pull request by zhengruifeng**
## What changes were proposed in this pull request?

Add DataFrame cumulative sum. 
Given numeric columns, create new columns which are the cumulative sum.
## How was this patch tested?

unit tests and manual tests

### CODE REVIEW

**Comment by rxin** [comment]
Thanks for contributing, but isn't this similar to just window function?

**Comment by zhengruifeng** [comment]
@rxin It is said in [JIRA](https://issues.apache.org/jira/browse/SPARK-10496) that window function is not efficient for a large number of rows in this problem. @jkbradley

**Comment by rxin** [comment]
I'm going to move the discussions over to JIRA.

**Comment by zhengruifeng** [comment]
This PR is out of date, I think it's time to close it.

**Pull request closed without merging**
