### PR TITLE
[SPARK-21363][SQL] Prevent name duplication in (global/local) temporary views

### PR DESCRIPTION
**Pull request by maropu**
## What changes were proposed in this pull request?
This pr prevented name duplication in (global/local) temporary views. Currently, the master only prevents the duplication in permanent views, for example:
```
// Permanent view case
scala> sql("CREATE VIEW t AS SELECT * FROM VALUES (1, 2), (2, 3) t(a, a)")
org.apache.spark.sql.AnalysisException: Found duplicate column(s) in the view definition: `a`;

scala> sql("CREATE VIEW t AS SELECT * FROM VALUES (1, 2), (2, 3) t(a, b)")
scala> sql("SELECT * FROM t").show
+---+---+
|  a|  b|
+---+---+
|  1|  2|
|  2|  3|
+---+---+

scala> sql("ALTER VIEW t AS SELECT * FROM VALUES (4, 5), (5, 6) t(b, b)")
org.apache.spark.sql.AnalysisException: Found duplicate column(s) in the view definition: `b`;

// Local temporary view case
scala> sql("CREATE TEMPORARY VIEW t AS SELECT * FROM VALUES (1, 2), (2, 3) t(a, a)")
scala> sql("SELECT * FROM t").show
+---+---+
|  a|  a|
+---+---+
|  1|  2|
|  2|  3|
+---+---+

scala> sql("ALTER VIEW t AS SELECT * FROM VALUES (4, 5), (5, 6) t(b, b)")
scala> sql("SELECT * FROM t").show
+---+---+
|  b|  b|
+---+---+
|  4|  5|
|  5|  6|
+---+---+

// Global temporary view case
scala> sql("CREATE GLOBAL TEMPORARY VIEW t AS SELECT * FROM VALUES (1, 2), (2, 3) t(a, a)")
scala> sql("SELECT * FROM global_temp.t").show
+---+---+
|  a|  a|
+---+---+
|  1|  2|
|  2|  3|
+---+---+

scala> sql("ALTER VIEW t AS SELECT * FROM VALUES (4, 5), (5, 6) t(b, b)")
scala> sql("SELECT * FROM t").show
+---+---+
|  b|  b|
+---+---+
|  4|  5|
|  5|  6|
+---+---+
```
This is a follow-up of SPARK-21363 though, this pr changed the existing behaviour.

## How was this patch tested?
Modified the existing tests in `DDLSuite`.

### CODE REVIEW

**Comment by maropu** [comment]
IMHO, other database(-like) systems prevent this name duplication in temporary table/view, so it seems we might do so along with them. 
```
// postgresql case
postgres=# create table s0 (a int, b int);
CREATE TABLE

postgres=# create table s1 (a int, b int);
CREATE TABLE

postgres=# select * from s0, s1 where s0.a = s1.a;
 a | b | a | b 
---+---+---+---
(0 rows)

postgres=# create view s2 as select * from s0, s1 where s0.a = s1.a;
ERROR:  column "a" specified more than once

postgres=# create temporary view s2 as select * from s0, s1 where s0.a = s1.a;
ERROR:  column "a" specified more than once


// mysql case
mysql> create table s0 (a int, b int);
Query OK, 0 rows affected (0.02 sec)

mysql> create table s1 (a int, b int);
Query OK, 0 rows affected (0.02 sec)

mysql> select * from s0, s1 where s0.a = s1.a;
Empty set (0.00 sec)

mysql> create view s2 as select * from s0, s1 where s0.a = s1.a;
ERROR 1060 (42S21): Duplicate column name 'a'

mysql> create temporary table s2 as select * from s0, s1 where s0.a = s1.a;
ERROR 1060 (42S21): Duplicate column name 'a'


// hive case
hive> create table s0 (a int, b int);
OK

hive> create table s1 (a int, b int);
OK

hive> select * from s0, s1 where s0.a = s1.a;
OK

hive> create temporary view s2 as select * from s0, s1 where s0.a = s1.a;
FAILED: ParseException line 1:17 cannot recognize input near 'create' 'temporary' 'view' in ddl statement


hive> create view s2 as select * from s0, s1 where s0.a = s1.a;
FAILED: SemanticException org.apache.hadoop.hive.ql.optimizer.calcite.CalciteViewSemanticException: Duplicate column name: a

hive> create temporary table s2 as select * from s0, s1 where s0.a = s1.a;
FAILED: SemanticException [Error 10036]: Duplicate column name: a
```


But, I think this name duplication is an expected one in the 2.x releases (for example, we already have some tests related to this: 
https://github.com/apache/spark/blob/master/sql/hive/src/test/scala/org/apache/spark/sql/hive/ErrorPositionSuite.scala#L37). So, this might be fixed for v3.x releases, maybe.

**Review by gatorsmile — COMMENTED** [review]
Yes, we are unable to break the existing applications. Thus, we still need to support it.

**Comment by maropu** [comment]
We still support this for 3.x releases? If so, I'll close jira as "Won't fix".

**Comment by gatorsmile** [comment]
Not sure. You can bring it up when we decide to jump to 3.x. Thanks!

**Comment by maropu** [comment]
ok, I'll close for now. If you get time, could you set 3.0 at the jira target? Thx!

**Pull request closed without merging**
