### PR TITLE
[MLlib][Doc] Seed fix in mllib naive bayes example

### PR DESCRIPTION
**Pull request by mupakoz**
Previous seed resulted in empty test data set.

### CODE REVIEW

**Comment by srowen** [comment]
I can't reproduce this. On master this results in a test set with 1 element. changing to 13 yields a test set with 2 elements. I don't mind changing it but are you sure?

**Comment by mupakoz** [comment]
I'm getting empty test set with spark-core_2.11 version 1.4.0 and spark-mllib_2.11 v. 1.4.0 used as SBT dependencies.

**Comment by srowen** [comment]
OK. This could be down to difference in Spark, Scala, the RNG across versions. If 13 works in your case, and still works for the plain-vanilla master + 2.10 build, I think we can just make this change.

**Comment by mupakoz** [comment]
So I thought. I can confirm that version 1.4.1 still results in empty test set.

**Comment by mengxr** [comment]
We use Java's Random in randomSplit, which shouldn't be affected by the Scala version. Which JVM did you use?

**Comment by mupakoz** [comment]
1.8.0_45, Windows 8

**Comment by srowen** [comment]
I'm on 1.8.0_45 / OS X

**Comment by mengxr** [comment]
@mupakoz I got the same result as @srowen . I don't think changing the seed is the solution. Instead, we should add more rows to `sample_naive_bayes_data.txt`. Could you do that instead?

**Comment by mupakoz** [comment]
Of course, no problem :). I'll prepare the commit later today.

**Comment by mupakoz** [comment]
@mengxr done. I added a few rows to the sample data and reverted the seed change. However, I had to add two rows for each class for the test set not to be empty after the split. Adding one row didn't resolve the problem.

**Comment by mengxr** [comment]
@mupakoz We can add more rows to avoid this (even with duplicates).

**Comment by mengxr** [comment]
LGTM. Merged into master (skipped Jenkins). Thanks!

**Pull request closed without merging**
