### PR TITLE
[SPARK-25321][ML] Revert SPARK-14681 to avoid API breaking change

### PR DESCRIPTION
**Pull request by mengxr**
## What changes were proposed in this pull request?

This is the same as #22492 but for master branch. Revert SPARK-14681 to avoid API breaking changes.

cc: @WeichenXu123 

## How was this patch tested?

Existing unit tests.

### CODE REVIEW

**Comment by WeichenXu123** [comment]
LGTM. Thanks!

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

I also confirm that this is a clean cherry-pick from `branch-2.4` to `master`.

For the discussion on backport, please see https://github.com/apache/spark/pull/22492 .

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by dongjoon-hyun** [comment]
Merged to master.

**Pull request closed without merging**
