### PR TITLE
[SPARK-31871][CORE][WEBUI][2.3] History page and Executors tab page show the correct sort icons

### PR DESCRIPTION
**Pull request by liucht-inspur**
### What changes were proposed in this pull request?
This PR was designed to solve the problem of incorrect display of History page and Executor tab page ICONS in spark 2.3.
Fixed the correct path for the display icon.

### Why are the changes needed?
Sorting doesn't show icons correctly, especially when the list is long and confusing.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Screenshots attached.

change before:
History page:
image

Executors tab page:
image

change after:
History page:
image

Executors tab page:
image

### CODE REVIEW

**Comment by sarutak** [comment]
Hi @liucht-inspur , sorry but `branch-2.3` is no longer maintained so please close this PR?
You can see our versioning policy [here](https://spark.apache.org/versioning-policy.html).
Thanks!

**Comment by liucht-inspur** [comment]
> Hi @liucht-inspur , sorry but `branch-2.3` is no longer maintained so please close this PR?
> You can see our versioning policy [here](https://spark.apache.org/versioning-policy.html).
> Thanks!

Oh! Are 2.2, 2.1, and 2.0 no longer maintained?

**Comment by sarutak** [comment]
> Oh! Are 2.2, 2.1, and 2.0 no longer maintained?
Yes.

**Comment by dongjoon-hyun** [comment]
Yes. , @liucht-inspur . Please see `Maintenance Releases and EOL` section of https://spark.apache.org/versioning-policy.html .
+1 for @sarutak 's advice (closing this PR).

**Comment by dongjoon-hyun** [comment]
FYI, Apache Spark 3.0.0 is released.
- https://spark.apache.org/releases/spark-release-3-0-0.html

**Comment by liucht-inspur** [comment]
Thank you all.

**Pull request closed without merging**
