### PR TITLE
[SPARK-18338][SQL][test-maven] Fix test case initialization order under Maven builds

### PR DESCRIPTION
**Pull request by liancheng**
## What changes were proposed in this pull request?

Test case initialization order under Maven and SBT are different. Maven always creates instances of all test cases and then run them all together.

This fails `ObjectHashAggregateSuite` because the randomized test cases there register a temporary Hive function right before creating a test case, and can be cleared while initializing other successive test cases. In SBT, this is fine since the created test case is executed immediately after creating the temporary function.

To fix this issue, we should put initialization/destruction code into `beforeAll()` and `afterAll()`.

## How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by yhuai** [comment]
Seems it does not work with sbt?

**Comment by zsxwing** [comment]
Could you add `[test-maven]` to the title to run the PR with maven build?

**Comment by zsxwing** [comment]
> Seems it does not work with sbt?

I saw the same `java.lang.OutOfMemoryError: Java heap space` in my PR as well. I think it's just because these tests are flaky.

**Comment by liancheng** [comment]
@cloud-fan already reported the OOM issue. I'm trying to reproduce it locally.

Added the `[test-maven]` tag to trigger Maven tests.

**Comment by liancheng** [comment]
retest this please

**Comment by liancheng** [comment]
retest this please.

**Comment by liancheng** [comment]
The last build failure was caused by an irrelevant flaky test.

BTW, I've reproduced the OOM issue locally by running `ObjectHashAggregateSuite` 200 times within a single SBT REPL session. Analyzing the heap dump.

**Comment by yhuai** [comment]
I am going to merge this to fix maven build.

**Pull request closed without merging**
