### PR TITLE
[SPARK-5285][SQL] Removed GroupExpression in catalyst

### PR DESCRIPTION
**Pull request by scwf**
Removed GroupExpression since we no need to have this wrapper

### CODE REVIEW

**Comment by marmbrus** [comment]
I don't think transformations recurse into `Seq[Expression]` do they?  That was the point of the container here.

Seems there might be a whole in our unit tests that they still pass with the removal of this. /cc @chenghao-intel

**Comment by scwf** [comment]
yeah getit，i will check to add some unittests here

**Comment by chenghao-intel** [comment]
The `GroupExpression` is not used as transformation in `Analyzer`, but in `Optimizer`, that's why it still can pass the unit test. I should document this.

**Comment by scwf** [comment]
@chenghao-intel， do we need to add unit test fot this?

**Comment by marmbrus** [comment]
I think there still could be a unit test to make sure that things in GroupExpressions get optimized.

**Comment by scwf** [comment]
@marmbrus after my investigate i think it is very rare case we will optimize GroupExpressions. 
Should our optimization cover sql such as ```SELECT a, b, count(*) FROM T1 GROUP BY a, b, 1+1 GROUPING SETS (1+1, a, (a, b), b, ())```? if not maybe we do not need to optimize it, then the change of this PR is safe.

**Comment by marmbrus** [comment]
I don't really see the benefit of removing it.  Transform should be able to walk all expression, even if there  are no optimizations that apply today.

**Comment by scwf** [comment]
Yes, i agree.  Then should i add the unit test i give above?

**Comment by chenghao-intel** [comment]
Well, actually it will be widely optimized.
e.g. `SELECT MAX(a), MAX(b) FROM t1 GROUP BY a, b GROUPING SETS (a, b)`
It will produces 2 `GroupExpression`s:
`MAX(Literal(null)), MAX(b)` and MAX(a), MAX(Literal(null))` and eventually it turns to
`null, MAX(b)` and `MAX(a), null`.

**Pull request closed without merging**
