### PR TITLE
[SPARK-37901] Upgrade Netty from 4.1.72 to 4.1.73

### PR DESCRIPTION
**Pull request by dchristle**
### What changes were proposed in this pull request?
Upgrade Netty dependency from 4.1.72 to 4.1.73.

### Why are the changes needed?
Netty has a new release that upgrades log4j to 2.17.1. Although I didn't find obvious dependence on log4j via netty in my search of Spark's codebase, it would be good to pick up this specific version anyway. The Netty version Spark currently depends on is 4.1.72, which depends on log4j 2.15. Several CVE's have been fixed in log4j between 2.15 and 2.17.1.

Besides this dependency update, several minor bugfixes have been made in this release, as described [here](https://netty.io/news/2022/01/12/4-1-73-Final.html).

Associated JIRA is here: https://issues.apache.org/jira/browse/SPARK-37901

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Passes local tests and CI.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Can you also run `./dev/test-dependencies.sh --replace-manifest` and push the changes together

**Review by HyukjinKwon — APPROVED** [review]

**Review by srowen — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
@dchristle mind retriggering the test please? https://github.com/dchristle/spark/runs/4823855818?check_suite_focus=true

**Comment by dchristle** [comment]
> @dchristle mind retriggering the test please? 

Done. All the components finished successfully. On the previous test runs, I think some flakiness was the root cause of failures - tests that did error seemed unrelated to anything about Netty.

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
