### PR TITLE
[SPARK-8603] [sparkR] In windows, Incorrect file seperator passed to Java and Scripts from R

### PR DESCRIPTION
**Pull request by pcp-dev**
[SPARK-8603] [sparkR] In windows, Incorrect file seperator passed to Java and Scripts from R

Issue 1:
R supports both file separator in the file path (Unix : / and Windows: ) irrespective of the operating system but when passing file path to Java or script program, it has to be converted according to operating system

issue 2: launchBackend function signature missmatch

### CODE REVIEW

**Comment by sujkh85** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

sujkh@naver.com 님께 보내신 메일 <[spark] [SPARK-8603] [sparkR] In windows, Incorrect file seperator passed to Java and Scripts from R (#7012)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by sujkh85** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

sujkh@naver.com 님께 보내신 메일 <Re: [spark] [SPARK-8603] [sparkR] In windows, Incorrect file seperator passed to Java and Scripts from R (#7012)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by shivaram** [comment]
@prakashpc Thanks for the change. I am not sure windows file path separator is actually a problem it seems to work fine on my Windows VM even without changing the file separator.  Does changing the file separator actually fix the problem in your setting ?

However the other one is a pretty obvious bug. Can you open a new PR with just the `packages` change ? We can discuss the file separator more in the JIRA

**Comment by prakashpc** [comment]
Yes !  the change fixed the issue.
ok.I will create the separate PR for the signature mismatch issue.

**Comment by shivaram** [comment]
@prakashpc I actually fixed the packages thing in #7022 -- I'll try out the file separator fix today and get back to you.

**Comment by prakashpc** [comment]
Closing the pull request to split this pull request to two
1) File separator issue
2) Signature mismatch issue

**Comment by Vonisoa** [comment]
I have the same trouble but can you explain me how to solve it please?

**Pull request closed without merging**
