### PR TITLE
[SPARK-47109][BUILD] Upgrade `commons-compress` to 1.26.0

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to upgrade `commons-compress` to 1.26.0.

### Why are the changes needed?

To bring the latest bug fixes.
- https://commons.apache.org/proper/commons-compress/changes-report.html#a1.26.0

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the CIs.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Review by xinrong-meng — APPROVED** [review]

**Comment by xinrong-meng** [comment]
LGTM once CI passes, thanks!

**Comment by dongjoon-hyun** [comment]
Thank you, @xinrong-meng !

**Review by HyukjinKwon — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @HyukjinKwon .

**Comment by dongjoon-hyun** [comment]
All tests passed. Merged to master for Apache Spark 4.0.0.

**Pull request closed without merging**
