### PR TITLE
[SPARK-24011][CORE][WIP] cache rdd's immediate parent ShuffleDependencies to accelerate getShuffleDependencies

### PR DESCRIPTION
**Pull request by Ngone51**
## What changes were proposed in this pull request?

When creating stages for jobs, we need to find a rdd's (except the final rdd) immediate parent ShuffleDependencies by method `getShuffleDependencies()` for at least 2 times (first in
`getMissingAncestorShuffleDependencies()`, and second in `getOrCreateParentStages()`).

So, we can cache the result at the fist time we call `getShuffleDependencies()`.
This is helpful for cutting time consuming when there's many `NarrowDependencies` between the rdd and its immediate parent `ShuffleDependencies` or if the rdd has a number of immediate parent `ShuffleDependencies` .
 
There's an exception for checkpointed rdd. If a rdd is checkpointed, it's immediate parent `ShuffleDependencies` should adjust to empty.
## How was this patch tested?

TODO.

### CODE REVIEW

**Comment by markhamstra** [comment]
As is, this PR isn't acceptable on multiple levels. Even if I were convinced (which I am not presently) that the sequence of `getShuffleDependencies` calls covered in this PR is the only one possible and therefore can be cached/memoized as this PR does, a complete lack of test coverage for the new code is not something we want in something as critical as the DAGScheduler. And I can tell you right now that there is at least one missing test that this PR will fail. You are adding a new data structure to the DAGScheduler, so at a bare minimum you also need to add that HashMap to `assertDataStructuresEmpty` in the DAGSchedulerSuite. Never deleting unneeded elements from a DAGScheduler data structure is an unacceptable resource leak.

**Comment by Ngone51** [comment]
Thank you for your comments @markhamstra .
Yeah, I'm considering adding a UT to support this change. And thank for reminding me of DAGScheduler's basic principle.

**Comment by squito** [comment]
its not a bad idea, but as @markhamstra mentions we can't have an `rddToImmediateShuffleDependency` data structure which keeps growing.  You could keep it local to one job submission, which would also slightly diminish its utility.

Did you observe this as a bottleneck from some profiling?   Otherwise I'm inclined to say its not worth the complexity right now.  I'd normally expect to only have to walk through a very small number of RDDs and so it'll be quick.

**Comment by Ngone51** [comment]
Thanks for your opinions @squito @markhamstra . 

Maybe, I should leave it for now.

**Pull request closed without merging**
