### PR TITLE
[MINOR][DOCS] Fix ForEachWriter Java example

### PR DESCRIPTION
**Pull request by roland1982**
### What changes were proposed in this pull request?
Structured streaming documentation example fix

### Why are the changes needed?
Currently the java example uses incorrect syntax

### Does this PR introduce any user-facing change?
Yes

### How was this patch tested?
In IDE

### CODE REVIEW

**Review by srowen — APPROVED** [review]
Good catch -- any others?

**Comment by srowen** [comment]
Jenkins test this please

**Comment by roland1982** [comment]
I think I've found some more but can't find them right now. I'll submit another pull request when I find them unless they've been fixed already.

**Review by dongjoon-hyun — APPROVED** [review]

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master, branch-3.0 and branch-2.4.

**Pull request closed without merging**
