### PR TITLE
[SPARK-44332][CORE][WEBUI] Fix the sorting error of Executor ID Column on Executors UI Page

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to fix the sorting error of `Executor ID` Column on `Executor Page`.

### Why are the changes needed?
Fix UI Sort bug.
PS: Can be reproduced using: sh bin/spark-shell --master "local-cluster[12,1,1024]"

- Before patch
    Before - asc:
    image

    Before - desc:
    image

- After patch
    After - asc:
    image

    After - desc:
    image

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
- Pass GA.
- Manually test.

### CODE REVIEW

**Comment by panbingkun** [comment]
Before:



After:

**Comment by panbingkun** [comment]
Thank you very much for the scenario provided by @LuciferYang ❤️

**Comment by LuciferYang** [comment]
So the `executorId` of `Yarn` and `k8s` both start with 1? I think it's fine to unify to start with 1

**Comment by LuciferYang** [comment]
cc @srowen FYI

**Comment by panbingkun** [comment]
> So the `executorId` of `Yarn` and `k8s` both start with 1? I think it's fine to unify to start with 1

Yes, that's right.

**Comment by LuciferYang** [comment]
Does mesos also start with 1?

**Comment by panbingkun** [comment]
> Does mesos also start with 1?

Let me to check it.

**Comment by panbingkun** [comment]
I have fixed this issue by adjusting the JavaScript logic.

**Review by LuciferYang — APPROVED** [review]
LGTM

**Comment by LuciferYang** [comment]
cc @yaooqinn

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
