### PR TITLE
[SPARK-14387][SQL] Exceptions thrown when querying ORC tables in Hive

### PR DESCRIPTION
**Pull request by rajeshbalamohan**
## What changes were proposed in this pull request?

Physical files stored in Hive as ORC would have internal columns as _col1,_col2 etc and column mapping would be available in HiveMetastore.  It was possible to query ORC tables stored in Hive via Spark's beeline client in earlier branches, and with master branch this was broken. When reading ORC files, it would be good map hive schema to physical schema for supporting backward compatibility.  This PR addresses this issue.
## How was this patch tested?

Manual execution of TPC-DS queries at 200 GB scale.

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

…in Hive

### CODE REVIEW

**Comment by rajeshbalamohan** [comment]
Changes:
- Rebased patch to master branch
- Removed OrcTableScan as it is not used anywhere.

**Comment by rajeshbalamohan** [comment]
\cc @liancheng

**Comment by rajeshbalamohan** [comment]
\cc @liancheng , @rxin  - Can you please review when you find time?

**Comment by yuananf** [comment]
I tested this patch, and it can fix the bug.
@rajeshbalamohan seems this need to rebase.
When will this get merged? we really need this, or we will face a lot of compatibility issues.

**Comment by rajeshbalamohan** [comment]
@yuananf Thanks for trying it out. I have rebased it and created https://github.com/apache/spark/pull/14471. Closing this one.

**Pull request closed without merging**
