### PR TITLE
[SPARK-48532][BUILD] Upgrade maven plugin to latest version

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to upgrade some maven plugins to latest version, includes:
- `org.apache.maven.plugins:maven-enforcer-plugin` from `3.4.1` to `3.5.0`
- `org.apache.maven.plugins:maven-shade-plugin` from `3.5.2` to `3.6.0`
- `org.apache.maven.plugins:maven-checkstyle-plugin` from `3.3.1` to `3.5.0`
- `org.apache.maven.plugins:maven-dependency-plugin` from `3.6.1` to `3.8.0`
- `org.apache.maven.plugins:maven-surefire-plugin` from `3.2.5` to `3.5.0`
- `org.apache.maven.plugins:maven-jar-plugin` from `3.4.0` to `3.4.2`
- `org.apache.maven.plugins:maven-clean-plugin` from `3.3.2` to `3.4.0`
- `org.apache.maven.plugins:maven-install-plugin` from `3.1.2` to `3.1.3`
- `org.apache.maven.plugins:maven-deploy-plugin` from `3.1.2` to `3.1.3`

- `org.codehaus.mojo:exec-maven-plugin` from `1.6.0`(`dev/test-dependencies.sh`)/`3.2.0`(`pom.xml`) to `3.4.1`
- `org.codehaus.mojo:build-helper-maven-plugin` from `3.5.0` to `3.6.0`
- `org.codehaus.mojo:versions-maven-plugin` from `2.16.2` to `2.17.1`.

- `net.alchim31.maven:scala-maven-plugin` from `4.9.1` to `4.9.2`

### Why are the changes needed?
- `org.apache.maven.plugins:maven-enforcer-plugin`
  https://github.com/apache/maven-enforcer/releases/tag/enforcer-3.5.0

-  `org.apache.maven.plugins:maven-shade-plugin`
  https://github.com/apache/maven-shade-plugin/compare/maven-shade-plugin-3.5.2...maven-shade-plugin-3.6.0

- `org.apache.maven.plugins:maven-checkstyle-plugin`
  https://github.com/apache/maven-checkstyle-plugin/compare/maven-checkstyle-plugin-3.3.1...maven-checkstyle-plugin-3.5.0

- `org.apache.maven.plugins:maven-dependency-plugin` 
  https://github.com/apache/maven-dependency-plugin/releases/tag/maven-dependency-plugin-3.8.0
  https://github.com/apache/maven-dependency-plugin/releases/tag/maven-dependency-plugin-3.7.1
  https://github.com/apache/maven-dependency-plugin/releases/tag/maven-dependency-plugin-3.7.0

- `org.apache.maven.plugins:maven-surefire-plugin`
  https://github.com/apache/maven-surefire/releases/tag/surefire-3.5.0
  https://github.com/apache/maven-surefire/releases/tag/surefire-3.4.0
  https://github.com/apache/maven-surefire/releases/tag/surefire-3.3.1
  https://github.com/apache/maven-surefire/releases/tag/surefire-3.3.0

- `org.apache.maven.plugins:maven-jar-plugin`
  https://github.com/apache/maven-jar-plugin/releases/tag/maven-jar-plugin-3.4.2
  https://github.com/apache/maven-jar-plugin/releases/tag/maven-jar-plugin-3.4.1

- `org.apache.maven.plugins:maven-clean-plugin`
  https://github.com/apache/maven-clean-plugin/releases/tag/maven-clean-plugin-3.4.0

- `org.apache.maven.plugins:maven-install-plugin`
  https://github.com/apache/maven-install-plugin/releases/tag/maven-install-plugin-3.1.3

- `org.apache.maven.plugins:maven-deploy-plugin`
  https://github.com/apache/maven-deploy-plugin/releases/tag/maven-deploy-plugin-3.1.3

- `org.codehaus.mojo:exec-maven-plugin`
  https://github.com/mojohaus/exec-maven-plugin/releases/tag/3.4.1
  https://github.com/mojohaus/exec-maven-plugin/releases/tag/3.4.0
  https://github.com/mojohaus/exec-maven-plugin/releases/tag/3.3.0
  https://github.com/mojohaus/exec-maven-plugin/releases/tag/3.2.0
  https://github.com/mojohaus/exec-maven-plugin/releases/tag/3.1.1
  https://github.com/mojohaus/exec-maven-plugin/releases/tag/3.1.0
  https://github.com/mojohaus/exec-maven-plugin/releases/tag/3.0.0

- `org.codehaus.mojo:build-helper-maven-plugin`
  https://github.com/mojohaus/build-helper-maven-plugin/releases/tag/3.6.0

- `org.codehaus.mojo:versions-maven-plugin`
  https://github.com/mojohaus/versions/releases/tag/2.17.1
  https://github.com/mojohaus/versions/releases/tag/2.17.0

- `net.alchim31.maven:scala-maven-plugin`
  https://github.com/davidB/scala-maven-plugin/compare/4.9.1...4.9.2

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Manually test, the verification process for various Maven plugins is as follows:
- `org.codehaus.mojo:exec-maven-plugin` **Meet expectations**
  ```
  sh dev/test-dependencies.sh

  ...
  + sort
  + grep -v spark
  Using `mvn` from path: /Users/panbingkun/Developer/spark/spark-community/build/apache-maven-3.9.7/bin/mvn
  + [[ '' == **replace-manifest** ]]
  + for HADOOP_HIVE_PROFILE in '"${HADOOP_HIVE_PROFILES[@]}"'
  + set +e
  ++ git diff --no-index dev/deps/spark-deps-hadoop-3-hive-2.3 dev/pr-deps/spark-deps-hadoop-3-hive-2.3
  + dep_diff=
  + set -e
  + '[' '' '!=' '' ']'
  + [[ -d /Users/panbingkun/Developer/spark/spark-community/dev/pr-deps ]]
  + rm -rf /Users/panbingkun/Developer/spark/spark-community/dev/pr-deps
  + exit 0
  + reset_version
  + find /Users/panbingkun/.m2/
  + grep spark-858355
  + xargs rm -rf
  + build/mvn -q versions:set -DnewVersion=4.0.0-SNAPSHOT -DgenerateBackupPoms=false
  Using `mvn` from path: /Users/panbingkun/Developer/spark/spark-community/build/apache-maven-3.9.7/bin/mvn
  ```

- `org.apache.maven.plugins:maven-enforcer-plugin` **Meet expectations**
  1.When I delete the following and execute `sh dev/test-dependencies.sh`, the error is as follows:
  image
  image

  2.When I restore it and execute `sh dev/test-dependencies.sh`, the results are as follows:
  image

- `org.apache.maven.plugins:maven-javadoc-plugin` **Meet expectations**
Is `genJavadoc` compatible with the latest `javadoc-3.7.0`?
  1.Check GA's generated files
  Javadoc - 3.6.3: https://github.com/panbingkun/spark/runs/26053653416
  Site File Link: https://github.com/panbingkun/spark/actions/runs/9458329785/artifacts/1587905559
  Javadoc - 3.7.0: https://github.com/panbingkun/spark/runs/26053674038
  Site File Link: https://github.com/panbingkun/spark/actions/runs/9458337388/artifacts/1588044558

  **I compared the contents of the two files(`docs/_site/api/(java|scala)`) above and found no other differences.**

  2.Manually check local generated files
  ```
  cd docs
  export SKIP_PYTHONDOC=1
  export SKIP_RDOC=1
  export SKIP_SQLDOC=1
  bundle exec jekyll build
  ```
  `v3.6.3` VS `v3.7.0`
  image

  ```
  SKIP_API=1 bundle exec jekyll serve --watch --host=127.0.0.1 --port=8080
  ```
  (scala api docs): http://127.0.0.1:8080/api/scala/org/apache/spark/index.html
  (java api docs): http://127.0.0.1:8080/api/java/index.html
  **Through manual observation, normal**

  - `org.apache.maven.plugins:maven-shade-plugin` **Meet expectations**
  ```
  ./build/mvn -pl :spark-core_2.13 clean package -Phadoop-3 -Pyarn -Phive-thriftserver -DskipTests -am
  ```
  `v3.5.2` VS `v3.6.0`
  image

  - `org.apache.maven.plugins:maven-checkstyle-plugin` **Meet expectations**
  ```
  sh dev/lint-java
  ```
  image

- Pass GA.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by panbingkun** [comment]
cc @LuciferYang @dongjoon-hyun @HyukjinKwon

**Comment by HyukjinKwon** [comment]
> maven-javadoc-plugin
Can we check if the Scaladoc/Javadoc generation work fine? IIRC, genjavadoc is pretty old, and we should see if that's compatible with javadoc plugin upgrade

**Comment by LuciferYang** [comment]
Without this PR, I tried to run `mvn javadoc:javadoc` and `mvn javadoc:jar` on `master/branch-3.5/branch-3.4`, and they both failed. I think we can initiate the upgrade of `maven-javadoc-plugin` after fixing them @panbingkun

**Comment by panbingkun** [comment]
Javadoc - 3.6.3: 
Javadoc - 3.7.0:

**Comment by panbingkun** [comment]
> > maven-javadoc-plugin
> 
> Can we check if the Scaladoc/Javadoc generation work fine? IIRC, genjavadoc is pretty old, and we should see if that's compatible with javadoc plugin upgrade

@HyukjinKwon 
The compatibility between plugin `genJavadoc ` and `the latest version(3.7.0) of javadoc` has been verified above, and no issues have been found, I have added the `verification steps` to the `description` of PR.

**Comment by panbingkun** [comment]
> Without this PR, I tried to run `mvn javadoc:javadoc` and `mvn javadoc:jar` on `master/branch-3.5/branch-3.4`, and they both failed. I think we can initiate the upgrade of `maven-javadoc-plugin` after fixing them @panbingkun

@LuciferYang 
Because we have a mixed code structure of `Java` and `Scala`, we generate Java and Scala documents through the plugin `genJavadoc `. For this reason, our execution of `mvn ... javadoc:javadoc` or `javadoc:jar` in the current configuration should not be successful unless we adjust the configuration, as follows: https://github.com/lightbend/genjavadoc
image
image

**Comment by LuciferYang** [comment]
hmm... IIRC,  https://github.com/panbingkun/spark/actions/runs/9458329785/artifacts/1587905559 is generated by `sbt unidoc`, it should not have used `maven-javadoc-plugin`

**Comment by panbingkun** [comment]
> hmm... IIRC, https://github.com/panbingkun/spark/actions/runs/9458329785/artifacts/1587905559 is generated by `sbt unidoc`, it should not have used `maven-javadoc-plugin`

Yes, that's right. I tested a PR that completely removed `javadoc`, and `GA` seems to be okay. I `guess` one possible implicit use of this plugin is:
https://repo1.maven.org/maven2/org/apache/spark/spark-core_2.13/4.0.0-preview1/
image

**Comment by LuciferYang** [comment]
> > hmm... IIRC, https://github.com/panbingkun/spark/actions/runs/9458329785/artifacts/1587905559 is generated by `sbt unidoc`, it should not have used `maven-javadoc-plugin`
> 
> Yes, that's right. I tested a PR (#46922) that completely removed `javadoc`, and `GA` seems to be okay. I `guess` one possible implicit use of this plugin is: https://repo1.maven.org/maven2/org/apache/spark/spark-core_2.13/4.0.0-preview1/ image

```
[INFO] --- scala:4.9.1:doc-jar (attach-scaladocs) @ spark-common-utils_2.13 ---
/Users/yangjie01/SourceCode/git/spark-mine-13/common/utils/src/main/scala/org/apache/spark/sql/streaming/StreamingQueryException.scala:25: warning: Could not find any member to link for "StreamingQuery".
Applicable -Wconf / @nowarn filters for this warning: msg=<part of the message>, cat=scaladoc, site=org.apache.spark.sql.streaming.StreamingQueryException
/**
^
/Users/yangjie01/SourceCode/git/spark-mine-13/common/utils/src/main/java/org/apache/spark/SparkThrowable.java:25: warning: Could not find any member to link for "SparkArithmeticException".
Applicable -Wconf / @nowarn filters for this warning: msg=<part of the message>, cat=scaladoc, site=org.apache.spark.SparkThrowable
/**
^
2 warnings
[INFO] Building jar: /Users/yangjie01/SourceCode/git/spark-mine-13/common/utils/target/spark-common-utils_2.13-4.0.0-SNAPSHOT-javadoc.jar
[INFO] 
```

In fact, it should be generated by `scala-maven-plugin` ...

**Comment by dongjoon-hyun** [comment]
Gentle ping. What is the current status of this PR, @panbingkun ?

**Comment by panbingkun** [comment]
> Gentle ping. What is the current status of this PR, @panbingkun ?

I will update in the next few days. Thanks!

**Pull request closed without merging**
