### PR TITLE
[SPARK-25021][K8S][BACKPORT] Add spark.executor.pyspark.memory limit for K8S

### PR DESCRIPTION
**Pull request by ifilonenko**
## What changes were proposed in this pull request?

Add spark.executor.pyspark.memory limit for K8S [BACKPORT]

## How was this patch tested?

Unit and Integration tests

### CODE REVIEW

**Comment by ifilonenko** [comment]
the unit test flakiness is unrelated

**Comment by ifilonenko** [comment]
retest this please

**Comment by felixcheung** [comment]
Jenkins, retest this please

**Comment by ifilonenko** [comment]
retest this please

**Comment by ifilonenko** [comment]
This flakiness of integration tests seems in relation to the executor issue logged by [SPARK-25291]. Will require a separate PR to master and `2.4`. Still not related to this PR however. (Odd that the PRB still cannot stably run the full unit tests suite properly.)

**Comment by felixcheung** [comment]
Jenkins, retest this please

**Comment by ifilonenko** [comment]
This PR is waiting on https://github.com/apache/spark/pull/22416. And should then be stable on the K8s end for merging.

**Review by holdenk — COMMENTED** [review]
LGTM pending Jenkins retest after test flakiness fix merged and removal of test falky comment (assuming it's fixed in the test falkiness PR).

**Comment by ifilonenko** [comment]
retest this please

**Comment by holdenk** [comment]
Jenkins, ok to test.

**Comment by holdenk** [comment]
Jenkins retest this please

**Comment by holdenk** [comment]
The 3 failing tests reported in Jenkins were fixed in 76514a015168de8d8b54b3abf6b835050eefd8c2 and are unrelated to this change.

**Comment by holdenk** [comment]
For future reference the original PR is at https://github.com/apache/spark/pull/22298/files/fe8cc5aa6759cdf893e11c3d83814f8dffddce9c

**Comment by holdenk** [comment]
Jenkins retest this please

**Comment by ifilonenko** [comment]
retest this please

**Comment by holdenk** [comment]
Merged with branch-2.4, feel free to close. Test failures are unrelated.

**Pull request closed without merging**
