### PR TITLE
[SPARK-36030][SQL][FOLLOW-UP] Remove duplicated test suite

### PR DESCRIPTION
**Pull request by viirya**
### What changes were proposed in this pull request?

Removes `FileFormatDataWriterMetricSuite` which duplicated.

### Why are the changes needed?

`FileFormatDataWriterMetricSuite` should be renamed to `InMemoryTableMetricSuite`. But it was wrongly copied. 

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by viirya** [comment]
cc @HyukjinKwon

**Review by HyukjinKwon — APPROVED** [review]

**Comment by viirya** [comment]
Thanks @HyukjinKwon. This only removed duplicated test suite. I'm going to merge this.

**Comment by HyukjinKwon** [comment]
Yeah +1

**Comment by viirya** [comment]
Sorry, I typed too quickly when merging script asked if to pick to another branch. I will open another for 3.2...

**Comment by HyukjinKwon** [comment]
lol I think you can just directly push it to. Pr is fine either

**Pull request closed without merging**
