### PR TITLE
[SPARK-45123][PS] Raise `TypeError` for `DataFrame.interpolate` when all columns are object-dtype.

### PR DESCRIPTION
**Pull request by itholic**
### What changes were proposed in this pull request?

This PR proposes to aise `TypeError` for `DataFrame.interpolate` when all columns are object-dtype.

### Why are the changes needed?

To match the behavior of Pandas:
```python
>>> pd.DataFrame({"A": ['a', 'b', 'c'], "B": ['a', 'b', 'c']}).interpolate()
...
TypeError: Cannot interpolate with all object-dtype columns in the DataFrame. Try setting at least one column to a numeric dtype.
```
We currently return empty DataFrame instead of raise TypeError:
```python
>>> pd.DataFrame({"A": ['a', 'b', 'c'], "B": ['a', 'b', 'c']}).interpolate()
Empty DataFrame
Columns: []
Index: [0, 1, 2]
```

### Does this PR introduce _any_ user-facing change?

Compute `DataFrame.interpolate` on DataFrame that has all object-dtype columns will raise TypeError instead of returning an empty DataFrame.

### How was this patch tested?

Added UT.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by itholic** [comment]
cc @zhengruifeng

**Review by zhengruifeng — APPROVED** [review]

**Comment by zhengruifeng** [comment]
merged to master

**Comment by ueshin** [comment]
@itholic The JIRA iD in the title seems to be wrong?

**Comment by itholic** [comment]
Oops.. Updated. Thanks, @ueshin !

**Pull request closed without merging**
