### PR TITLE
RoutingTablePartition code comment errors

### PR DESCRIPTION
**Pull request by zhipwang**
There is an error in description of RoutingTablePartition object. The "edge partition" is encoded in the lower 30 bits of the Int, not 30 bytes of the Int. And the same mistake is made in "position is encoded in the upper 2 bytes of the Int".

### CODE REVIEW

**Comment by srowen** [comment]
OK, that's fine.

**Comment by srowen** [comment]
@vanzin @jkbradley can any of you try merging this? git keeps failing when I try and I don't see why. Just "error code 1". Looks entirely mergeable.

**Comment by jkbradley** [comment]
@srowen Sure, I'll try merging it with master now.

**Comment by jkbradley** [comment]
I got the same problem.  I'll try to figure out why...

**Comment by zhipwang** [comment]
Should I close it and make a new PR?

**Comment by srowen** [comment]
You should not need to, however I still don't see why this does not merge. In the past I recall something like this happened when the PR description had some certain funny characters. I don't see them here and thought the script was improved. You could try taking out the quotes in the description since they become part of the git command line, but really that should not be a problem. You could try another PR too just to see.

**Comment by zhipwang** [comment]
OK~ I will keep this and open a new one. Thanks~

**Comment by zhipwang** [comment]
I'm not quite sure but I can't make another PR while keeping this one. I will close it and try a new one.

**Pull request closed without merging**
