### PR TITLE
[SPARK-38419][BUILD] Replace tabs that exist in the script with spaces

### PR DESCRIPTION
**Pull request by jackylee-ch**
### Why are the changes needed?
There are some tabs in some script, which don't seem to be standardized. This pr tries to replace tabs that exist in the script with spaces.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
UT

### CODE REVIEW

**Review by srowen — COMMENTED** [review]
Can you check other scripts in one go here? minor but fine to fix, but nice to fix all at once

**Comment by stczwd** [comment]
> Can you check other scripts in one go here? minor but fine to fix, but nice to fix all at once

Thanks for your attension. That's all I can found.

**Comment by srowen** [comment]
Merged to master. Doesn't really need a JIRA for really minor things like that

**Comment by stczwd** [comment]
> Merged to master. Doesn't really need a JIRA for really minor things like that

Ah, I got it, thanks.

**Pull request closed without merging**
