### PR TITLE
[SPARK-35899][SQL][FOLLOWUP] Utility to convert connector expressions to Catalyst

### PR DESCRIPTION
**Pull request by aokolnychyi**
### What changes were proposed in this pull request?

This PR addresses post-review comments on PR #33096:
- removes `private[sql]` modifier
- removes the option to pass a resolver to simplify the API

### Why are the changes needed?

These changes are needed to simply the utility API.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by aokolnychyi** [comment]
@HyukjinKwon, could you take a look, please?

**Review by HyukjinKwon — APPROVED** [review]
LGTM, thanks @aokolnychyi for addressing my comments.

**Comment by aokolnychyi** [comment]
Thanks, @HyukjinKwon!

**Comment by dongjoon-hyun** [comment]
Merged to master. Thank you, @aokolnychyi and @HyukjinKwon .

**Comment by aokolnychyi** [comment]
Thanks, @dongjoon-hyun!

**Pull request closed without merging**
