### PR TITLE
[SPARK-45274][CORE][SQL][UI] Implementation of a new DAG drawing approach for job/stage/plan graphics to avoid fork

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

Currently, we use a forked [repo](https://github.com/yaooqinn/dagre-d3/commit/faf82545c4e6d8a72f690107ba0b372868e7b508) of `dagre-d3` for UI to render DAG graphics for jobs, stages and plans.

The reasons for the fork can be summarized as follows:
- (1) Add identifiers to the `class` of clusters and nodes for late retrieving
- (2) Calculate the coordinates and size for complex clusters. For example,
   - The width of `Stage 8` must fit the maximum width of its child clusters, which are `AQEShuffleRead`, `WholeStageCodegen (8)` and `mapPartitionsInternal`, and also fit its label text length.
   - The height of `Stage 8` needs to be increased to display its label on the top right corner to avoid overlapping, which also needs to add the max increment of its children.  

image
   

In this PR,
- To achieve the goal of (1), we apply `id` for graph/cluster/node in dot-file, which will be rendered as `HTML/SVG element id. And use id for selections.
- To achieve the goal of (2), we post-process it right after rendering the dot file. Especially for job graph rendering, we need to complete it before rendering the second dot file, as we need to deliver the final coordinates to the follower.

Additionally, tooltips for WholeStageCodegen clusters on the execution page are supported. It's convenient for users to learn the information of a plan node when it is out of the screen.

 
### Why are the changes needed?

Avoid fork and custom upstream libs

### Does this PR introduce _any_ user-facing change?

Yes, tooltips for WholeStageCodegen clusters on the execution page are supported; otherwise, mainly code refactoring.

### How was this patch tested?

Tested manually,

#### use case

```sql
SELECT   Avg(t1.id)
FROM     RANGE(1) t1
join     RANGE(2) t2
join     RANGE(3) t3
join     RANGE(4) t4
join     RANGE(5) t5
join     RANGE(6) t6
join     RANGE(7) t7
ON       t1.id = t2.id
AND      t2.id = t3.id
AND      t3.id=t4.id
AND      t4.id=t5.id
AND      t5.id = t6.id
AND      t6.id=t7.id
GROUP BY t1.id % 5;
```

#### Job DAG Visualization
image

image

##### Cached

image

#### Stage DAG Visualization

image

#### Plan Visualization

image

##### 

### Was this patch authored or co-authored using generative AI tooling?

NO

### CODE REVIEW

**Comment by yaooqinn** [comment]
cc @sarutak @cloud-fan @dongjoon-hyun @HyukjinKwon @mridulm, thanks

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @yaooqinn .

**Comment by mridulm** [comment]
Nice job @yaooqinn  !

**Review by mridulm — APPROVED** [review]

**Review by sarutak — APPROVED** [review]
@yaooqinn  LGTM. Thank you for refactoring!

**Comment by dongjoon-hyun** [comment]
Merged to master for Apache Spark 4.0.0. Thank you, @yaooqinn and all.

**Comment by yaooqinn** [comment]
Thank you all.

**Review by HyukjinKwon — COMMENTED** [review]
Awesomeness!

**Comment by dongjoon-hyun** [comment]
Hi, @yaooqinn . Unfortunately, I found that this commit broke `ChromeUISeleniumSuite` suite. Could you double-check this?

```
$ build/sbt -Dguava.version=32.1.2-jre \
-Dspark.test.webdriver.chrome.driver=/opt/homebrew/bin/chromedriver \
-Dtest.default.exclude.tags="" -Phive -Phive-thriftserver \
"core/testOnly org.apache.spark.ui.ChromeUISeleniumSuite"
```

- 19532b32665
```
[info] ChromeUISeleniumSuite:
[info] - SPARK-31534: text for tooltip should be escaped (1 second, 181 milliseconds)
[info] - SPARK-31882: Link URL for Stage DAGs should not depend on paged table. (444 milliseconds)
[info] - SPARK-31886: Color barrier execution mode RDD correctly (231 milliseconds)
[info] - Search text for paged tables should not be saved (944 milliseconds)
[info] Run completed in 4 seconds, 451 milliseconds.
[info] Total number of tests run: 4
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 4, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
```

- 51938fea36a
```
[info] ChromeUISeleniumSuite:
[info] - SPARK-31534: text for tooltip should be escaped *** FAILED *** (10 seconds, 819 milliseconds)
...
[info] *** 2 TESTS FAILED ***
[error] Failed tests:
[error] 	org.apache.spark.ui.ChromeUISeleniumSuite
[error] (core / Test / testOnly) sbt.TestsFailedException: Tests unsuccessful
```

**Comment by dongjoon-hyun** [comment]
Hi, @yaooqinn . I made a PR to fix the test suite.
- https://github.com/apache/spark/pull/45078

**Pull request closed without merging**
