### PR TITLE
[SPARK-49470][UI] Update dataTables stylesheets and javascripts from 1.13.5 to 1.13.11

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

This PR updates datatables from 1.13.5 to 1.13.11
FYI, https://cdn.datatables.net/releases.html

### Why are the changes needed?

Improve UI dependency management

### Does this PR introduce _any_ user-facing change?
no

### How was this patch tested?

Locally Build and Test
image

image

### Was this patch authored or co-authored using generative AI tooling?
no

### CODE REVIEW

**Comment by yaooqinn** [comment]
cc @sarutak @dongjoon-hyun @HyukjinKwon, thank you

**Review by HyukjinKwon — APPROVED** [review]

**Comment by yaooqinn** [comment]
Merged to master. Thank you @HyukjinKwon

**Review by HyukjinKwon — COMMENTED** [review]
Seems like we missed the version name in the file `core/src/main/resources/org/apache/spark/ui/static/jquery.dataTables.min.js`. Should we better restore it?

**Comment by yaooqinn** [comment]
Hi @HyukjinKwon, Did any issues occur after removing the version? If not,  I prepare to remove versions from the rest during upgrading, since most of our UI dependencies have no version numbers in their file names.

**Pull request closed without merging**
