### PR TITLE
[SPARK-40124][SQL][TEST][3.1] Update TPCDS v1.4 q32 for Plan Stability tests

### PR DESCRIPTION
**Pull request by mskapilks**
### What changes were proposed in this pull request?
This is port of SPARK-40124 to Spark 3.1. Fix query 32 for TPCDS v1.4

### Why are the changes needed?
Current q32.sql seems to be wrong. It is just selection `1`.
Reference for query template: https://github.com/databricks/tpcds-kit/blob/eff5de2c30337b71cc0dc1976147742d2c65d378/query_templates/query32.tpl#L41

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Test change only

### CODE REVIEW

**Comment by mskapilks** [comment]
cc: @kazuyukitanimura @dongjoon-hyun

**Comment by kazuyukitanimura** [comment]
Hmm, some checks are failing...

**Comment by mskapilks** [comment]
> Hmm, some checks are failing... not sure if related

Failures are not related. Python linter throwing some error in pyspark.

**Comment by dongjoon-hyun** [comment]
Thank you for making a PR, @mskapilks . However, Apache Spark 3.1.x is EOL already because Apache Spark 3.1.1 was released on March 2, 2021. Please see our versioning policy for more details.

https://spark.apache.org/versioning-policy.html

Currently, we are focusing on preparing Apache Spark 3.3.1 instead of EOL releases. Let me close this PR to avoid accidental merging.

**Pull request closed without merging**
