### PR TITLE
[SPARK-20876][SQL][Backport-2.2]If the input parameter is float type for ceil or floor,the result is not we expected

### PR DESCRIPTION
**Pull request by 10110346**
## What changes were proposed in this pull request?

This PR is to backport #18103 to Spark 2.2

## How was this patch tested?
unit test

### CODE REVIEW

**Comment by ueshin** [comment]
ok to test

**Comment by ueshin** [comment]
Jenkins, retest this please.

**Comment by ueshin** [comment]
LGTM, cc @gatorsmile

**Review by gatorsmile — APPROVED** [review]
LGTM too

**Comment by gatorsmile** [comment]
Thanks! Merging to 2.0. 

Could you manually close this PR? Thanks!

**Comment by 10110346** [comment]
@gatorsmile  OK,thanks

**Pull request closed without merging**
