### PR TITLE
[SPARK-29381][PYTHON][ML] Add _ before the XXXParams classes

### PR DESCRIPTION
**Pull request by huaxingao**
### What changes were proposed in this pull request?
Add _ before XXXParams classes to indicate internal usage

### Why are the changes needed?
Follow the PEP 8 convention to use _single_leading_underscore to indicate internal use 

### Does this PR introduce any user-facing change?
No

### How was this patch tested?
use existing tests

### CODE REVIEW

**Review by srowen — COMMENTED** [review]
Would this affect anyone who has subclassed these quasi-internal classes? I'm trying to figure out how likely it is that this breaks someone's extension vs the value. We can break this in 3.0 but just weigh it against how important it is.

**Comment by huaxingao** [comment]
Almost all of these  quasi-internal classes _XXXParams are newly added in these parity jiras with very few exceptions. One of them is ```LSHParams```. If user has subclass this ```LSHParams```, with the name changed to ```_LSHParams```,  user has to explicitly import this class like ```from pyspark.ml.feature import _LSHParams```because import * does not import objects whose names start with an underscore.

**Review by srowen — APPROVED** [review]
Seems OK pending tests.

**Comment by srowen** [comment]
Merged to master

**Comment by huaxingao** [comment]
Thanks a lot! @srowen

**Pull request closed without merging**
