### PR TITLE
[MINOR] [DOCS] fixed list display in ml-ensembles

### PR DESCRIPTION
**Pull request by BenFradet**
The list in ml-ensembles.md wasn't properly formatted and, as a result, was looking like this:
old

This PR aims to make it look like this:
new

### CODE REVIEW

**Comment by BenFradet** [comment]
Pinging @mengxr

**Comment by srowen** [comment]
LGTM

**Comment by BenFradet** [comment]
Thanks for having a look @srowen.

**Comment by mengxr** [comment]
Merged into master and branch-1.6. Thanks!

**Pull request closed without merging**
