### PR TITLE
[SPARK-14498][ML][PYTHON][SQL] Many cleanups to ML and ML-related docs

### PR DESCRIPTION
**Pull request by jkbradley**
## What changes were proposed in this pull request?

Cleanups to documentation.  No changes to code.
- GBT docs: Move Scala doc for private object GradientBoostedTrees to public docs for GBTClassifier,Regressor
- GLM regParam: needs doc saying it is for L2 only
- TrainValidationSplitModel: add .. versionadded:: 2.0.0
- Rename “_transformer_params_from_java” to “_transfer_params_from_java”
- LogReg Summary classes: “probability” col should not say “calibrated”
- LR summaries: coefficientStandardErrors —> document that intercept stderr comes last.  Same for t,p-values
- approxCountDistinct: Document meaning of “rsd" argument.
- LDA: note which params are for online LDA only
## How was this patch tested?

Doc build

### CODE REVIEW

**Comment by jkbradley** [comment]
CC @dbtsai Could you please confirm the doc changes about coefficientStandardErrors and GLM's regParam?  Thanks!

**Comment by dbtsai** [comment]
Both looks good to me. Thanks. I'll go ahead and merge it soon.

**Comment by dbtsai** [comment]
Thanks. Merged into master.

**Comment by jkbradley** [comment]
Thanks for taking a look!

**Pull request closed without merging**
