### PR TITLE
[SPARK-35434][BUILD] Upgrade scalatestplus artifacts to 3.2.9.0

### PR DESCRIPTION
**Pull request by sarutak**
### What changes were proposed in this pull request?

This PR upgrades the scalatestplus artifacts and scalacheck.

### Why are the changes needed?

scalatestplus artifacts Spark uses are two years old and these artifacts are currently renamed.
So, let's follow up.
Also, the latest releases seem to support Scala 3.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

GA passed on my repository.

### CODE REVIEW

**Review by srowen — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by cloud-fan** [comment]
After this commit, I can't run tests with sbt console
```
[error] /Users/wenchen/dev/spark/core/src/test/scala/org/apache/spark/SparkContextInfoSuite.scala:22:8: Symbol 'type org.scalactic.TripleEquals' is missing from the classpath.
[error] This symbol is required by 'trait org.scalatest.Assertions'.
[error] Make sure that type TripleEquals is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[error] A full rebuild may help if 'Assertions.class' was compiled against an incompatible version of org.scalactic.
[error] import org.scalatest.Assertions
[error]        ^
[error] one error found
```

**Comment by sarutak** [comment]
@cloud-fan 

`SparkContextInfoSuite` passes on my laptop with the following procedure.
```
$ build/sbt
sbt:spark-parent> Test / testOnly org.apache.spark.SparkContextSuite
...
[info] SparkContextInfoSuite:
[info] compiling 292 Scala sources and 6 Java sources to /home/kou/work/oss/spark/sql/catalyst/target/scala-2.12/test-classes ...
[info] compiling 505 Scala sources and 65 Java sources to /home/kou/work/oss/spark/sql/core/target/scala-2.12/classes ...
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] No tests to run for graphx / Test / testOnly
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] No tests to run for mllib-local / Test / testOnly
[info] - getPersistentRDDs only returns RDDs that are marked as cached (2 seconds, 869 milliseconds)
[info] - getPersistentRDDs returns an immutable map (83 milliseconds)
[info] - getRDDStorageInfo only reports on RDDs that actually persist data (1 second, 84 milliseconds)
[info] - call sites report correct locations (180 milliseconds)
[info] Run completed in 6 seconds, 516 milliseconds.
[info] Total number of tests run: 4
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 4, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
```

How did you launch sbt and run test?

**Comment by cloud-fan** [comment]
I did
```
$ ./build/sbt
sbt:spark-parent> project sql
sbt:sql> testOnly some_sql_test_suite
```

**Comment by sarutak** [comment]
Hmm... I've tried the following test which contains "import org.scalatest.Assersions" with `scalactic*` and `scalatestplus*` removed from `~/.ivy2`, `~/.m2` and `~/.cache` but still succeeds...
```
sbt:spark-parent> project sql
sbt:spark-sql> testOnly org.apache.spark.sql.execution.WholeStageCodegenSparkSubmitSuite
```

**Comment by cloud-fan** [comment]
I'll clean up my env and try again, thanks for checking!

**Comment by wypoon** [comment]
@cloud-fan @sarutak I ran into this exact same problem. I sync'd to master yesterday and the HEAD was at this commit. I could not run tests in sbt. I was doing the same thing as @cloud-fan.
I reset to the commit before this one, and then it worked.
@cloud-fan if you do get sbt to work, can you please post the steps here?

**Comment by dongjoon-hyun** [comment]
Hi, @wypoon . If something goes wrong, you can start cleanly by removing 3 places in general.
```
$ rm -rf ~/.ivy2
$ rm -rf ~/.m2
$ rm -rf ~/.cache
```

**Comment by sarutak** [comment]
@wypoon 
If you use macOS, rm `~/Library/Caches/Coursier` rather than `~/.cache`.

**Comment by wypoon** [comment]
@dongjoon-hyun and @sarutak, thanks for the tips. (I am on macOS.)
I'd cleaned out my .ivy2 but that didn't help. I did 'rm -rf .m2/repository/org/scala*' and also 'rm -rf Library/Caches/Coursier' and now I can run test in sbt.

**Comment by zhengruifeng** [comment]
on ubuntu, this works:

```
rm -rf .ivy2
rm -rf .m2/repository/org/scala*
rm -rf .cache/coursier/
```

**Pull request closed without merging**
