### PR TITLE
[SPARK-43203][SQL][3.4] Move all Drop Table case to DataSource V2

### PR DESCRIPTION
**Pull request by Hisoka-X**
### What changes were proposed in this pull request? 
cherry pick #41348 and #42056 , this a bug fixed should be included in 3.4.2

### Why are the changes needed?
Fix DROP table behavior in session catalog

### Does this PR introduce _any_ user-facing change? 
No

### How was this patch tested?
Tested by:
- V2 table catalog tests: `org.apache.spark.sql.execution.command.v2.DropTableSuite`
- V1 table catalog tests: `org.apache.spark.sql.execution.command.v1.DropTableSuiteBase`

### CODE REVIEW

**Comment by Hisoka-X** [comment]
cc @cloud-fan @viirya @aokolnychyi

**Comment by beliefer** [comment]
Spark will discard the v1 API ?

**Comment by Hisoka-X** [comment]
> Spark will discard the v1 API ?

Not, this is a bug fix for drop table case, please refer https://github.com/apache/spark/pull/41348

**Comment by holdenk** [comment]
@aokolnychyi since you asked for the backport maybe good to take a look.

**Review by cloud-fan — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @Hisoka-X and all.

Also, cc @viirya .

Merged to branch-3.4 for Apache Spark 3.4.2.

**Comment by viirya** [comment]
lgtm

**Pull request closed without merging**
