### PR TITLE
[SPARK-12248][CORE] Adds limits per cpu for mesos coarse mode

### PR DESCRIPTION
**Pull request by drcrallen**
- Add spark.cores.mb.min for minimum memory per core
- Add spark.cores.mb.max for max memory per core

### CODE REVIEW

**Comment by drcrallen** [comment]
Doesn't affect heap memory properly, closing until fixed

**Comment by drcrallen** [comment]
local fork of spark at https://github.com/metamx/spark/tree/v1.5.2-mmx is using this successfully, but since #10993 will probably be the way to go forward, I'm not going to re-raise this PR unless requested.

**Comment by PedroAlvarado** [comment]
@drcrallen Did https://github.com/apache/spark/pull/4027 covered the memory constraints you were adding as part of this issue? I can't find another open or closed issue that addresses the issue raised here.

**Comment by drcrallen** [comment]
@PedroAlvarado I just looked at master and 2.0 and the limit of one task per slave seems to have been removed. I do not think this is valid anymore. Closing out ticket.

**Pull request closed without merging**
