### PR TITLE
[SPARK-10114][SQL] Add optional getters to the Row

### PR DESCRIPTION
**Pull request by crakjie**
Add a clean syntax to request nullable field

### CODE REVIEW

**Comment by srowen** [comment]
Please look at https://cwiki.apache.org/confluence/display/SPARK/Contributing+to+Spark before opening a PR

**Comment by JoshRosen** [comment]
@rxin @marmbrus, do we want this syntactic sugar?

**Comment by andrewor14** [comment]
ok to test. I think there's a more updated patch that's already going through reviews: #10247. @crakjie would you mind closing this patch?

**Comment by crakjie** [comment]
@andrewor14 No #10247 can't close this ticket, because it's bugged. getOption ( witch should be getOption[T](fieldName: String) to respect scala way to name theses function ) return all the time None.

And getOption[T](i: Int) use is own exception logic and don't just use the logic of getAs[T](i : Int)

**Comment by crakjie** [comment]
And I don't see theses white spaces 
```
[error] /home/jenkins/workspace/SparkPullRequestBuilder/sql/catalyst/src/main/scala/org/apache/spark/sql/Row.scala:326:0: Whitespace at end of line
[error] /home/jenkins/workspace/SparkPullRequestBuilder/sql/catalyst/src/main/scala/org/apache/spark/sql/Row.scala:331:4: Whitespace at end of line
[error] /home/jenkins/workspace/SparkPullRequestBuilder/sql/catalyst/src/main/scala/org/apache/spark/sql/Row.scala:348:0: Whitespace at end of line
[error] /home/jenkins/workspace/SparkPullRequestBuilder/sql/catalyst/src/main/scala/org/apache/spark/sql/Row.scala:353:4: Whitespace at end of line
```

I have looked closely with my editor. Some one have a hint about it?

**Comment by srowen** [comment]
@crakjie you'd be the only person that can close it. If you're logged in you'll be able to. Otherwise our automated script will eventually, if I say these words: Do you mind closing this PR?

**Comment by crakjie** [comment]
@srowen I will not close it because it's not resolved by #10247.
I know I can close this issue by clicking on "close this issue".
My problem is the Scala style tests which say there is white space but I don't see them.

**Comment by srowen** [comment]
What isn't resolved? these PRs look like they cover the same ground, but the other one is more complete and farther along (and for whatever reason isn't running afoul of the style checker). If you have other changes you want to suggest, I'd converge on the other PR and close this one. I don't see a reason this should stay open since I'm going to resolve this JIRA as a dupe of the other anyway.

**Comment by crakjie** [comment]
have you did a code review on the other PR ? It's bugged as I said. Yes theses two par adresse the same issue. But this one is simpler. And there is no need for test because getAs is already test and we can say we trust the scala Option.

**Comment by srowen** [comment]
I'd please add comments to the other PR if you think it has a problem. But I think you're misunderstanding the PR, as the method that returns `None` always is overridden. This one won't be merged in any event and should be closed.

**Pull request closed without merging**
