### PR TITLE
[MINOR] Fix typos in comments and testcase name of code

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
## What changes were proposed in this pull request?

This PR fixes typos in comments and testcase name of code.
## How was this patch tested?

manual.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Since it's not about documents and contains testcase name typo, so I couldn't choose `DOCS` as component name.

**Comment by sarutak** [comment]
ok to test.

**Comment by rxin** [comment]
LGTM pending tests

**Comment by dongjoon-hyun** [comment]
Thank you, @sarutak and @rxin !

**Comment by dongjoon-hyun** [comment]
Hi, @sarutak and @rxin .

**WithAggregationKinesisBackedBlockRDDSuite** took about 2 hours and still is running.
The following is the last part of Jenkins logs. It seems abnormal. Could you trigger another test run please?
```
[info] WithAggregationKinesisBackedBlockRDDSuite:
Using endpoint URL https://kinesis.us-west-2.amazonaws.com for creating Kinesis streams for tests.
[2016-03-02 18:39:50.670894] [0x00007f2565bb6700] [info] [kinesis_producer.cc:79] Created pipeline for stream "KinesisTestUtils-2198454940508828809"
[2016-03-02 18:39:50.671040] [0x00007f2565bb6700] [info] [shard_map.cc:83] Updating shard map for stream "KinesisTestUtils-2198454940508828809"
[2016-03-02 18:39:50.929527] [0x00007f25647b4700] [info] [shard_map.cc:163] Successfully updated shard map for stream "KinesisTestUtils-2198454940508828809" found 2 shards
[info] - Basic reading from Kinesis (2 seconds, 186 milliseconds)
[info] - Read data available in both block manager and Kinesis (77 milliseconds)
```

**Comment by dongjoon-hyun** [comment]
Oh, thank you for re-triggering.

**Comment by sarutak** [comment]
@dongjoon-hyun Once a commiter trigger a test, you can trigger another one by yourself in the same PR by saying like "retest this please" .

**Comment by dongjoon-hyun** [comment]
Thank you for your advice!
Is the magic word of a committer **Jenkins, test this please** and **ok to test** then?

**Comment by dongjoon-hyun** [comment]
Hi, @sarutak and @rxin .
three builds hanged at the same test **WithAggregationKinesisBackedBlockRDDSuite**.
The first build fails due to timeout, the others seems to fail with the same reason.

I'm not sure this is the case for the followings? Or, any other reason?
  1. File a JIRA issue for **WithAggregationKinesisBackedBlockRDDSuite**
  2. Pass the test by removing the typo fix on Kinesis-related files
    * KinesisBackedBlockRDDSuite.scala
    * KinesisReceiverSuite.scala

I think it is out of this PR's scope to fix `WithAggregationKinesisBackedBlockRDDSuite`.

**Comment by srowen** [comment]
Jenkins, test this please

**Comment by srowen** [comment]
Yeah, I'm certain it's not this PR as it only changes a test name in the kinesis module. Something's wrong with the tests there. I'm not sure what do with this one; unless someone knows the problem and is fixing it, we can maybe just avoid fixing the files in kinesis and sort out the test separately

**Comment by dongjoon-hyun** [comment]
Thank you for confirming. I'll avoid that in this PR.

**Comment by dongjoon-hyun** [comment]
retest this please.

**Comment by dongjoon-hyun** [comment]
Finally, it passed. 
I filed the Kinesis issue as [SPARK-13655](https://issues.apache.org/jira/browse/SPARK-13655), too.

**Comment by srowen** [comment]
Merged to master

**Comment by dongjoon-hyun** [comment]
Thank you, @srowen !

**Pull request closed without merging**
