### PR TITLE
[SPARK-44843][TESTS] Double streamingTimeout for StateStoreMetricsTest to make RocksDBStateStore related streaming tests reliable

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

This PR increases streamingTimeout and the check interval for StateStoreMetricsTest to make RocksDBStateStore-related streaming tests reliable, hopefully.

### Why are the changes needed?

```
SPARK-35896: metrics in StateOperatorProgress are output correctly (RocksDBStateStore with changelog checkpointing) *** FAILED *** (1 minute)
[info]   Timed out waiting for stream: The code passed to failAfter did not complete within 60 seconds.
[info]   java.base/java.lang.Thread.getStackTrace(Thread.java:1619)
```

The probability of these tests failing is close to 100%, which seriously affects the UX of making PRs for the contributors.
 

https://github.com/yaooqinn/spark/actions/runs/6744173341/job/18333952141

### Does this PR introduce _any_ user-facing change?

no, test only

### How was this patch tested?

this can be verified by `sql - slow test` job in CI

### Was this patch authored or co-authored using generative AI tooling?

no

### CODE REVIEW

**Comment by yaooqinn** [comment]
cc @LuciferYang

**Review by LuciferYang — APPROVED** [review]
LGTM ~

Let's give it a try.

**Comment by yaooqinn** [comment]
Thank you @LuciferYang , merged to master

**Review by dongjoon-hyun — COMMENTED** [review]
Thank you so much!

**Comment by dongjoon-hyun** [comment]
`RocksDBStateStoreStreamingAggregationSuite` seems to be still flaky in another test case. I made a PR to run this suite in a dedicated JVM completely, @yaooqinn and @LuciferYang . I hope it could improve the stability.
- https://github.com/apache/spark/pull/43916

**Pull request closed without merging**
