### PR TITLE
[SPARK-42944][PYTHON][FOLLOW-UP] Rename tests from foreachBatch to foreach_batch

### PR DESCRIPTION
**Pull request by HyukjinKwon**
### What changes were proposed in this pull request?

This PR proposes to rename tests from foreachBatch to foreach_batch.

### Why are the changes needed?

Non-API should follow snake_naming rule per PEP 8.

### Does this PR introduce _any_ user-facing change?

No, dev-only.

### How was this patch tested?

CI in this PR should test it out.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @WweiL

**Review by yaooqinn — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Review by zhengruifeng — APPROVED** [review]

**Review by LuciferYang — APPROVED** [review]

**Review by WweiL — APPROVED** [review]

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
Oh, could you fix this leftover, too?
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/__w/spark/spark/python/pyspark/sql/tests/connect/streaming/test_parity_foreach_batch.py", line 66, in <module>
    from pyspark.sql.tests.connect.streaming.test_parity_foreachBatch import *  # noqa: F401,E501
ModuleNotFoundError: No module named 'pyspark.sql.tests.connect.streaming.test_parity_foreachBatch'
```

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you for updating.

**Comment by dongjoon-hyun** [comment]
BTW, `pyspark-pandas-connect` (3h 12min) and `pyspark-pandas-slow-connect` (3h 33min) seems to take very long time frequently. Do you think we can improve these pipeline?
- https://github.com/apache/spark/actions/runs/5979206329/job/16222875461
- https://github.com/apache/spark/actions/runs/5979206329/job/16222875615

**Comment by dongjoon-hyun** [comment]
It seems that `pyspark-connect` module took 6 hours and was cancelled by timeout. Could you re-run?

Screenshot 2023-08-26 at 9 24 39 AM

**Comment by dongjoon-hyun** [comment]
`pyspark-connect` was the only failure last time. Now, it passed. Merged to master.

Screenshot 2023-08-26 at 9 50 41 PM

**Comment by dongjoon-hyun** [comment]
There is a conflict on branch-3.5. Please make a backporting PR on `branch-3.5` please.

**Comment by HyukjinKwon** [comment]
Will do. Thank you!

**Comment by HyukjinKwon** [comment]
https://github.com/apache/spark/pull/42692

**Comment by HyukjinKwon** [comment]
@itholic mind taking a look at https://github.com/apache/spark/pull/42675#issuecomment-1694246392?

**Pull request closed without merging**
