### PR TITLE
[SPARK-30689][CORE][FOLLOW-UP] Add @since annotation for ResourceDiscoveryScriptPlugin/ResourceInformation

### PR DESCRIPTION
**Pull request by Ngone51**
### What changes were proposed in this pull request?

Added `@since 3.0.0` for `ResourceDiscoveryScriptPlugin` and `ResourceInformation`.

### Why are the changes needed?

It's required for exposed APIs(https://github.com/apache/spark/pull/27689#discussion_r426488851).

### Does this PR introduce _any_ user-facing change?

Yes, they can easily know when does Spark introduces the API.

### How was this patch tested?

Pass Jenkins.

### CODE REVIEW

**Comment by Ngone51** [comment]
I checked the related module and only found these two are missing the annotation. Please let me know if I missed someone else. Thanks!

cc @HyukjinKwon @tgravescs

**Review by HyukjinKwon — APPROVED** [review]
LGTM pending tests

**Comment by Ngone51** [comment]
retest this please

**Review by tgravescs — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master and branch-3.0.

**Pull request closed without merging**
