### PR TITLE
Added the PrefixSpan MLlib example based on the current documentation

### PR DESCRIPTION
**Pull request by ledormeurduval**
## What changes were proposed in this pull request?

```
Added the PrefixSpan MLlib example based on the current documentation
```
## How was this patch tested?

with this command line : 
./bin/spark-submit ./examples/src/main/python/mllib/prefix_span_example.py

### CODE REVIEW

**Comment by holdenk** [comment]
Thanks @rangeonnicolas for taking the effort to improve our Python MLlib documentation :)
For this to show up in the documentation you will also need to update the `./docs/mllib-frequent-pattern-mining.md` file.

After you'e done that you can verify the new docs locally following the steps in `./docs/README.md` :)

**Comment by holdenk** [comment]
Hi @rangeonnicolas are you still interested in working on this change?

**Comment by rangeonnicolas** [comment]
Yes, I'm doing it!

2016-11-04 1:02 GMT+01:00 Holden Karau <notifications@github.com>:

**Comment by rangeonnicolas** [comment]
I think it's done, But I didn't managed to test the doc. github doens't not display it well

**Comment by holdenk** [comment]
Ah yes, testing the documentation can be a bit difficult. You can take a look at the guide under docs/README.md to see how to build the documentation locally and verify it looks like you expect it to. Let me know how that goes and we can try and find a committer to take a look at this.

**Pull request closed without merging**
