### PR TITLE
[SPARK-48724][SQL][TESTS] Fix incorrect conf settings of `ignoreCorruptFiles` related tests case in `ParquetQuerySuite` 

### PR DESCRIPTION
**Pull request by wayneguow**
### What changes were proposed in this pull request?

This PR aims to fix incorrect conf settings of `ignoreCorruptFiles` related tests case in `ParquetQuerySuite`. The inner `withSQLConf (SQLConf.IGNORE_CORRUPT_FILES.key -> "false")` will overwrite the outer configuration, making it impossible to test the situation where `sqlConf` is true.

### Why are the changes needed?

Fix test coverage logic.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass GA.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by wayneguow** [comment]
cc @dongjoon-hyun @Yaohua628

**Review by Yaohua628 — APPROVED** [review]
Ah, good catch! Thanks for fixing that!

**Review by LuciferYang — APPROVED** [review]
+1, LGTM

**Comment by LuciferYang** [comment]
@wayneguow please file a new jira, SPARK-38767 belongs to Spark 3.4, not 4.0

**Comment by LuciferYang** [comment]
Merged into master. Thanks @wayneguow and @Yaohua628

**Comment by wayneguow** [comment]
Thanks for reviewing. @Yaohua628 @LuciferYang

**Pull request closed without merging**
