### PR TITLE
[SPARK-4891][PySpark][MLlib] Add gamma/log normal/exp dist sampling to P...

### PR DESCRIPTION
**Pull request by rnowling**
...ySpark MLlib

This is a follow up to PR3680 https://github.com/apache/spark/pull/3680 .

### CODE REVIEW

**Comment by rnowling** [comment]
@mengxr The test failures seem to be unrelated to my changes -- they were in streaming, but I modified rand.

**Comment by mengxr** [comment]
Let's retry Jenkins, test this please.

**Comment by rnowling** [comment]
Thanks, @mengxr !

**Comment by mengxr** [comment]
@rnowling The code LGTM, but let's make Jenkins happy. Since you are on the whitelist, I think you should be able to trigger Jenkins by "test this please".

**Comment by rnowling** [comment]
Jenkins, test this please.

**Comment by rnowling** [comment]
@mengxr tested passed! :)

**Comment by mengxr** [comment]
Merged into master. Thanks!

**Pull request closed without merging**
