### PR TITLE
[SPARK-13057][SQL] Add benchmark codes and the performance results for implemented compression schemes for InMemoryRelation

### PR DESCRIPTION
**Pull request by maropu**
This pr adds benchmark codes for in-memory cache compression to make future developments and discussions more smooth.

### CODE REVIEW

**Comment by maropu** [comment]
The size of in-memory columnar cache is much bigger than parquet data on disk because Spark uses simpler compression algorithms than parquet does in `CompressionSchemes` (See a discussion on spark-user mailing list - https://www.mail-archive.com/user@spark.apache.org/msg45241.html).

Since spark-sql already has `parquet-column` dependency, we can use the same efficient compression algorithms with Parquet to reduce GC pressure.
Thought?

**Comment by maropu** [comment]
I tried to use `DeltaBinaryPackingValuesReader` and `DeltaBinaryPackingValuesWriter` in `parquet-column` package.

```
Benchmark
Running benchmark: INT Decode(Lower Skew)
  Running case: PassThrough(1.000)
  Running case: RunLengthEncoding(1.005)
  Running case: DictionaryEncoding(0.500)
  Running case: IntDelta(0.250)
  Running case: ParquetIntDelta(0.072)

Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz
INT Decode(Lower Skew):            Avg Time(ms)    Avg Rate(M/s)  Relative Rate
-------------------------------------------------------------------------------
PassThrough(1.000)                       278.04           241.36         1.00 X
RunLengthEncoding(1.005)                 741.29            90.53         0.38 X
DictionaryEncoding(0.500)                954.02            70.34         0.29 X
IntDelta(0.250)                          836.38            80.24         0.33 X
ParquetIntDelta(0.072)                   839.36            79.95         0.33 X

Running benchmark: INT Decode(Higher Skew)
  Running case: PassThrough(1.000)
  Running case: RunLengthEncoding(1.339)
  Running case: DictionaryEncoding(0.501)
  Running case: IntDelta(0.250)
  Running case: ParquetIntDelta(0.161)

Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz
INT Decode(Higher Skew):           Avg Time(ms)    Avg Rate(M/s)  Relative Rate
-------------------------------------------------------------------------------
PassThrough(1.000)                       899.44            74.61         1.00 X
RunLengthEncoding(1.339)                1192.31            56.28         0.75 X
DictionaryEncoding(0.501)                981.44            68.38         0.92 X
IntDelta(0.250)                          874.43            76.75         1.03 X
ParquetIntDelta(0.161)                   937.08            71.61         0.96 X
```

**Comment by maropu** [comment]
@rxin Could you give me any comment on this?

**Comment by rxin** [comment]
cc @nongli is this useful?

**Comment by maropu** [comment]
@nongli ping

**Comment by cloud-fan** [comment]
the benchmark infra is updated, I think we need to rerun it and update the results.

**Comment by nongli** [comment]
The benchmark LGTM and I think this is useful.

@maropu Before you make significant changes to this, can you write up what you plan to do?

**Comment by maropu** [comment]
@nongli Okay, I'll let you know the plan first. plz give me some time to look around similar codes in `Parquet` and `Orc`.

**Comment by rxin** [comment]
Thanks - I've merged this in master.

**Pull request closed without merging**
