### PR TITLE
[SPARK-26677][FOLLOWUP][BRANCH-2.4] Update Parquet manifest with Hadoop-2.6

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
## What changes were proposed in this pull request?

During merging Parquet upgrade PR, `hadoop-2.6` profile dependency manifest is missed.

## How was this patch tested?

Manual. 

```
./dev/test-dependencies.sh
```

Also, this will recover `branch-2.4` with `hadoop-2.6` build.
- https://amplab.cs.berkeley.edu/jenkins/view/Spark%20QA%20Test%20(Dashboard)/job/spark-branch-2.4-test-sbt-hadoop-2.6/281/

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Hi, @srowen . I missed that we still have `hadoop-2.6` in `branch-2.4` while reviewing the PR. Could you review this PR?

**Review by srowen — APPROVED** [review]
Oops right, looks good

**Comment by dongjoon-hyun** [comment]
Thank you, @srowen !

**Comment by dongjoon-hyun** [comment]
Merged to `branch-2.4`.

**Pull request closed without merging**
