### PR TITLE
[SPARK-38227][SQL][SS] Apply strict nullability of nested column in time window / session window

### PR DESCRIPTION
**Pull request by HeartSaVioR**
### What changes were proposed in this pull request?

This PR proposes to apply strict nullability of nested column in window struct for both time window and session window, which respects the dataType of TimeWindow and SessionWindow.

### Why are the changes needed?

The implementation of rule TimeWindowing and SessionWindowing have been exposed the possible risks of inconsistency between the dataType of TimeWindow/SessionWindow and the replacement. For the replacement, it is possible that analyzer/optimizer may decide the value expressions to be non-nullable.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

New tests added.

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
cc. @cloud-fan @sigmod @viirya @xuanyuanking

**Comment by HeartSaVioR** [comment]
It would be ideal if we have a great idea to technically prevent such case (code level, or at least runtime level like fast-fail the query) instead of adding tests to guard against. I don't know whether it is technically feasible or not, just thinking ideally.

**Review by sigmod — APPROVED** [review]

**Comment by HeartSaVioR** [comment]
cc. @cloud-fan @sigmod @viirya @xuanyuanking Friendly reminder.

**Review by cloud-fan — APPROVED** [review]

**Review by viirya — APPROVED** [review]

**Comment by viirya** [comment]
Thanks. Merging to master.

**Comment by HeartSaVioR** [comment]
Thanks all for reviewing and merging!

**Pull request closed without merging**
