### PR TITLE
[SPARK-22771][SQL] Add a missing return statement in Concat.checkInputDataTypes

### PR DESCRIPTION
**Pull request by maropu**
## What changes were proposed in this pull request?
This pr is a follow-up to fix a bug left in #19977.

## How was this patch tested?
Added tests in `StringExpressionsSuite`.

### CODE REVIEW

**Comment by maropu** [comment]
cc: @gatorsmile

**Comment by maropu** [comment]
retest this please

**Review by gatorsmile — COMMENTED** [review]
LGTM

**Comment by gatorsmile** [comment]
Thanks! Merged to master and 2.3

**Comment by maropu** [comment]
Thanks!

**Pull request closed without merging**
