### PR TITLE
[SPARK-41197][BUILD] Upgrade Kafka to 3.3.1

### PR DESCRIPTION
**Pull request by tedyu**
### What changes were proposed in this pull request?
This PR upgrades Kafka to 3.3.1 release.

The new default partitioner keeps track of how many bytes are produced per-partition and once the amount exceeds `batch.size`, it switches to the next partition. For spark kafka tests, this will result in records being sent to only one partition in some tests.
`KafkaTestUtils.producerConfiguration` is modified to use `DefaultPartitioner`.

### Why are the changes needed?
Kafka 3.3.1 release has new features along with bug fixes: https://www.confluent.io/blog/apache-kafka-3-3-0-new-features-and-updates/

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Existing test suite

### CODE REVIEW

**Comment by tedyu** [comment]
@HeartSaVioR 
Can you take a look ?

**Comment by bjornjorgensen** [comment]
Hi, 3.3.0 A significant bug was found in the 3.3.0 release after artifacts were pushed to Apache and Maven central but prior to the release announcement. As a result, the decision was made to not announce 3.3.0 and instead release 3.3.1 with the fix. It is recommended that 3.3.0 not be used.

Can you try with 3.3.1

**Comment by tedyu** [comment]
@bjornjorgensen 
I have updated the PR.

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
Hi, @tedyu . Could you fix UT failures?
```
[info] *** 90 TESTS FAILED ***
[error] Failed tests:
[error] 	org.apache.spark.sql.kafka010.KafkaMicroBatchV2SourceSuite
[error] 	org.apache.spark.sql.kafka010.KafkaMicroBatchV1SourceWithAdminSuite
[error] 	org.apache.spark.sql.kafka010.KafkaMicroBatchV1SourceSuite
[error] 	org.apache.spark.sql.kafka010.KafkaContinuousSourceSuite
[error] 	org.apache.spark.sql.kafka010.KafkaMicroBatchV2SourceWithAdminSuite
```

**Comment by tedyu** [comment]
I noticed the test failures.
Let me analyze the test output.

**Comment by bjornjorgensen** [comment]
Can it have something to do with https://github.com/apache/kafka/pull/12794 ?

**Comment by tedyu** [comment]
Possible.
When would the next Kafka be released ?

**Comment by HyukjinKwon** [comment]
cc @dongjoon-hyun and @HeartSaVioR FYI

**Comment by tedyu** [comment]
@HyukjinKwon @dongjoon-hyun @HeartSaVioR 
Please take a look - tests pass.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @tedyu , @bjornjorgensen , @dengziming, @HyukjinKwon .
Merged to master for Apache Spark 3.4.

**Comment by dongjoon-hyun** [comment]
This is merged via https://github.com/apache/spark/commit/0ff201cc219884d3cbb6844732c681546e53f4d4 .

**Pull request closed without merging**
