### PR TITLE
[SPARK-40088][SQL][TESTS] Add SparkPlanWithAQESuite

### PR DESCRIPTION
**Pull request by kazuyukitanimura**
### What changes were proposed in this pull request?
This PR proposes to add `SparkPlanWithAQESuite` i.e. test cases of `SparkPlanSuite` with AQE (Adaptive Query Execution) turned on.

### Why are the changes needed?
Currently `SparkPlanSuite` assumes that AQE is always turned off. We should also test with AQE turned on

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Added an AQE version tests along with the non AQE version

### CODE REVIEW

**Comment by kazuyukitanimura** [comment]
cc @sunchao @viirya

**Review by dongjoon-hyun — APPROVED** [review]

**Review by viirya — APPROVED** [review]

**Comment by kazuyukitanimura** [comment]
Thank you all for the quick reviews!

**Review by sunchao — APPROVED** [review]

**Comment by kazuyukitanimura** [comment]
Sorry style fixed and CI passed

**Comment by viirya** [comment]
Thanks. Merging to master.

**Comment by cloud-fan** [comment]
If we want to test AQE off for all test suites, can we add one more job in Github Action with AQE turned off?

**Comment by kazuyukitanimura** [comment]
The intention is to add tests where that fails for AQE "force" apply on. I can add one more job ing Github Action with AQE force applied if it makes sense?

**Comment by kazuyukitanimura** [comment]
Actually, there is only one more suite that fails with AQE force apply as far as I know. I don't think we need to test all suits with a separate Github Action.

**Comment by cloud-fan** [comment]
why do we care about AQE force apply? It's a testing feature and should never be enabled in production.

**Pull request closed without merging**
