### PR TITLE
[SPARK-40448][CONNECT][FOLLOWUP] Use more suitable variable name and fix code style.

### PR DESCRIPTION
**Pull request by beliefer**
### What changes were proposed in this pull request?
We are very concerned about the progress of the Spark Connect, so we understand the current draft and read preliminary implementation. We can see that some code style are inappropriate, or even cause confusion. Therefore, this PR try to correct it.

### Why are the changes needed?
Fix code style on scala server side.

### Does this PR introduce _any_ user-facing change?
'No'.
Spark Connect just started.

### How was this patch tested?
N/A

### CODE REVIEW

**Comment by amaliujia** [comment]
It's ok to fix code style on, for example, scala server side. 

I want to hold a bit on the proto side. The proto itself will evolve quickly and itself is not at a stable position now. Whatever we change now could be no longer useful soon. Plus every time we update the proto we need to update the generate file on the python side. We are planing to change the python side with some sort of automatic way for python proto generation. 

Before that is achieved, the idea could be that we limit changes on the proto to only core API coverage to unblock other pieces (DataFrame API etc.)

**Comment by beliefer** [comment]
> Before that is achieved, the idea could be that we limit changes on the proto to only core API coverage to unblock other pieces (DataFrame API support in clients etc.)

Thank you. I will revert the changes on the proto.

**Review by amaliujia — COMMENTED** [review]
LGTM!

**Comment by beliefer** [comment]
ping @grundprinzip

**Review by grundprinzip — APPROVED** [review]

**Comment by beliefer** [comment]
cc @dongjoon-hyun @HyukjinKwon

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by beliefer** [comment]
@amaliujia @grundprinzip @HyukjinKwon Thank you!

**Pull request closed without merging**
