### PR TITLE
[test-maven][test-hadoop1.0][SPARK-11236][CORE] Update Tachyon dependency 0.7.1 -> 0.8.1

### PR DESCRIPTION
**Pull request by calvinjia**
This is a reopening of #9204 which failed hadoop1 sbt tests.

With the original PR, a classpath issue would occur due to the MIMA plugin pulling in hadoop-2.2 dependencies regardless of the hadoop version when building the `oldDeps` project. These affect the hadoop1 sbt build because they are placed in `lib_managed` and Tachyon 0.8.0's default hadoop version is 2.2.

### CODE REVIEW

**Comment by calvinjia** [comment]
@yhuai 
Could you take a look? Thanks!

**Comment by yhuai** [comment]
cc @pwendell @srowen This is the new pr that upgrades Tachyon. I reverted the original one, which caused hadoop 1 test failures.

**Comment by yhuai** [comment]
btw, the profiles that we used in hadoop 1 tests are `-Phadoop-1 -Dhadoop.version=1.2.1 -Pkinesis-asl -Phive-thriftserver -Phive`.

**Comment by calvinjia** [comment]
@yhuai 
Thanks for the the response! The last PR would pass with those parameters, but and would only fail if the entire dev/runtests cycle was ran (specifically if MIMA ran before). I've tested locally that the issues do not occur when running dev/runtests with this change.

**Comment by pwendell** [comment]
@calvinjia can you add "[test-hadoop1.0]" to the title of this PR and then retest it? That will run the tests with hadoop 1. See more info here:

https://cwiki.apache.org/confluence/display/SPARK/Useful+Developer+Tools

**Comment by calvinjia** [comment]
@pwendell could you trigger a build for me? Or should I just make an empty commit?

**Comment by pwendell** [comment]
Jenkins, test this please.

**Comment by calvinjia** [comment]
Thanks!

**Comment by calvinjia** [comment]
@pwendell 

It seems like the previous issue is gone. The only error (which seems to be triggered by an oom / jvm crash?) that occurs is:

```
Exception in thread "Thread-58" Exception in thread "Thread-62" java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:196)
	at java.net.SocketInputStream.read(SocketInputStream.java:122)
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.io.ObjectInputStream$PeekInputStream.peek(ObjectInputStream.java:2293)
	at java.io.ObjectInputStream$BlockDataInputStream.peek(ObjectInputStream.java:2586)
	at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2596)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1318)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
	at sbt.React.react(ForkTests.scala:114)
	at sbt.ForkTests$$anonfun$mainTestTask$1$Acceptor$2$.run(ForkTests.scala:74)
	at java.lang.Thread.run(Thread.java:745)
java.io.EOFException
	at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2598)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1318)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
	at org.scalatest.tools.Framework$ScalaTestRunner$Skeleton$1$React.react(Framework.scala:945)
	at org.scalatest.tools.Framework$ScalaTestRunner$Skeleton$1.run(Framework.scala:934)
	at java.lang.Thread.run(Thread.java:745)
```

It doesn't seem like its related to this change.

**Comment by yhuai** [comment]
test this please

**Comment by calvinjia** [comment]
@yhuai Thanks for the retest. I'm not sure if this will go away by re-running or if there is something up with Jenkins/Spark master branch. It seems like the current `Spark-Master-SBT` build is not happy on `hadoop1.0` for the same reason. (See: https://amplab.cs.berkeley.edu/jenkins/job/Spark-Master-SBT/3911/AMPLAB_JENKINS_BUILD_PROFILE=hadoop1.0,label=spark-test/consoleFull)

**Comment by pwendell** [comment]
Hm - can you try also adding [test-maven] - might be better to test with
maven.

**Comment by calvinjia** [comment]
@pwendell Sure, I've updated it.

**Comment by pwendell** [comment]
Jenkins, test this please.

**Comment by calvinjia** [comment]
@pwendell 
It seems like the maven tests failed with: 
```
java.lang.IllegalArgumentException: Logging directory specified is not a directory: file:/home/jenkins/workspace/SparkPullRequestBuilder/core/target/tmp/spark-ab60a5c8-38dd-4340-a4e9-109cf8dcf18e/
```
This doesn't seem like something that would be introduced by this change?

**Comment by calvinjia** [comment]
@pwendell 

It seems like the `Spark-Master-Maven` build running for hadoop1.0 is also failing with the same problem (see: https://amplab.cs.berkeley.edu/jenkins/job/Spark-Master-Maven-pre-YARN/HADOOP_VERSION=1.2.1,label=spark-test/4631/).

**Comment by calvinjia** [comment]
@pwendell @yhuai 
Is the only blocker for this PR the stability of hadoop1.0 tests in Spark master? Thanks!

**Comment by pwendell** [comment]
Hey @calvinjia seems okay to merge since this is just triggering other failures. Can you explain more though how this works around the mima issue - the patch seems the same as #9204. Did something change between Tachyon 0.8.0 and 0.8.1?

**Comment by calvinjia** [comment]
@pwendell 
We changed the default hadoop version from 2.2. MIMA was pulling in `hadoop2.2` jars into the `lib_managed` directory when it built `oldDeps`. In `spark.utils.ShutdownHookManager`, we do some reflection to see if we are using Hadoop 2.x, and it will get a false positive leading to the failures. (See: https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/util/ShutdownHookManager.scala#L221)

**Comment by pwendell** [comment]
Got it- thanks I can merge it then.

**Comment by calvinjia** [comment]
@pwendell @yhuai
Thanks for the pointers and reviewing this PR.

**Pull request closed without merging**
