### PR TITLE
[SPARK-44033][PYTHON] Added support for binary ops for list like objects

### PR DESCRIPTION
**Pull request by gdhuper**
### Why are the changes needed?

Fix for [Spark-44033](https://issues.apache.org/jira/browse/SPARK-44033)

### Was this patch authored or co-authored using generative AI tooling?

TODO
- [ ]  complete the PR description
- [ ] Add a basic unit tests
- [ ] Reformatting codes by running ./dev/reformat-python

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @itholic

**Comment by itholic** [comment]
Let's fill the PR description and add a unit tests first to verify the if the function is working as expected.

We can start with adding a very basic test into `python/pyspark/pandas/tests/data_type_ops/test_binary_ops.py`.

**Comment by itholic** [comment]
Also let's reformat the Python codes. We can easily reformat by running `./dev/reformat-python` on the project root path.

**Comment by itholic** [comment]
Basically, could you do:
- [ ] complete the PR description
- [ ] Add a basic unit tests
- [ ] Reformatting codes by running `./dev/reformat-python`

**Pull request closed without merging**
