### PR TITLE
[SPARK-11329] [SQL] Cleanup from spark-11329 fix.

### PR DESCRIPTION
**Pull request by nongli**

### CODE REVIEW

**Comment by srowen** [comment]
Dumb question, but why wasn't this part of SPARK-11329? or attached to it?

**Comment by nongli** [comment]
My bad. Does this do the trick?

**Comment by yhuai** [comment]
@srowen Since the original pr did not have any fundamental issue and we will probably see a burst of commits (as we will cut the branch soon), I committed the original one to avoid potential merge conflict. We will attach this pr to the original jira. So, it will be clear from the commit history.

**Comment by srowen** [comment]
I figured. My motivation is mostly to make sure that it's easy to find all the commits that belong to one logical change. And maybe reducing noise but that's minor.

**Comment by yhuai** [comment]
@srowen yeah. That's a good point.

**Comment by yhuai** [comment]
Thanks! LGTM. Merging to master!

**Pull request closed without merging**
