### PR TITLE
[WIP][SPARK-42696]Speed up parquet reading with Java Vector API

### PR DESCRIPTION
**Pull request by jiangjiguang**
### What changes were proposed in this pull request?
Parquet has supported vector read speed up with this PR [Vectorized BytePacker decoder using Java Vector API](https://github.com/apache/parquet-mr/pull/1011)
The performance gain is 4x ~ 8x according to the parquet microbenchmark
TPC-H(SF100) Q6 has 11% performance increase with Apache Spark integrating parquet vector optimization

### Why are the changes needed?
This PR used to support parquet vector optimization

### Does this PR introduce _any_ user-facing change?
Add configuration  spark.sql.parquet.vector512.read.enabled, If true and CPU contains avx512vbmi & avx512_vbmi2 instruction set, parquet decodes using Java Vector API. For Intel CPU, Ice Lake or newer contains the required instruction set.

### How was this patch tested?
For the test case, there are some problems to fix:
1. It is necessary to Parquet-mr community release new java version to use the parquet vector optimization. 
2. Parquet Vector optimization does not release default, so users have to build parquet with **mvn clean install -P vector-plugins** manually to get the parquet-encoding-vector-{VERSION}.jar and put it on the {SPARK_HOME}/jars path
3. github doesn't support select runners with specific instruction set. So it is impossible (a self-hosted runner can do it) to verify the optimization on github runners machine.

### CODE REVIEW

**Comment by LuciferYang** [comment]
> Add configuration spark.sql.parquet.vector512.read.enabled, If true and CPU contains avx512vbmi & avx512_vbmi2 instruction set, parquet decodes using Java Vector API. For Intel CPU, Ice Lake or newer contains the required instruction set.

hmm... what happens if machines that support AVX 512 are prohibited from using AVX 512?

**Comment by LuciferYang** [comment]
```
[error] /home/runner/work/spark/spark/sql/catalyst/src/main/scala/org/apache/spark/sql/internal/SQLConf.scala:4512:7: method parquetAggregatePushDown is defined twice;
[error]   the conflicting method parquetAggregatePushDown was defined at line 4510:7
[error]   def parquetAggregatePushDown: Boolean = getConf(PARQUET_VECTOR512_READ_ENABLED)
[error]       ^
[error] one error found
```

compile failed

**Comment by jiangjiguang** [comment]
> > Add configuration spark.sql.parquet.vector512.read.enabled, If true and CPU contains avx512vbmi & avx512_vbmi2 instruction set, parquet decodes using Java Vector API. For Intel CPU, Ice Lake or newer contains the required instruction set.
> 
> hmm... what happens if machines that support AVX 512 are prohibited from using AVX 512?

@LuciferYang this is a good question.  As far as I know, Cascade Lake currently used by most users. Compared with Ice lake, Cascade Lake is Intel's previous generation CPU and it does not contains avx512vbmi & avx512_vbmi2 instruction set.  If running the parquet vector optimization on Cascade Lake, it will become very slowly(0.01x), but there is a JDK [Patch](https://bugs.openjdk.org/browse/JDK-8290322) to fix this problem, with the patch, it will be 1.7x.  Under normal situation, it will be 5.5x on Ice Lake with Java17. The patch has been merged Java17.

**Comment by jiangjiguang** [comment]
> ```
> [error] /home/runner/work/spark/spark/sql/catalyst/src/main/scala/org/apache/spark/sql/internal/SQLConf.scala:4512:7: method parquetAggregatePushDown is defined twice;
> [error]   the conflicting method parquetAggregatePushDown was defined at line 4510:7
> [error]   def parquetAggregatePushDown: Boolean = getConf(PARQUET_VECTOR512_READ_ENABLED)
> [error]       ^
> [error] one error found
> ```
> 
> compile failed

@LuciferYang Thanks, I will fix it

**Comment by frankliee** [comment]
Since avx256 has been supported by more types of x86 servers, could this PR also supports avx256 ?

**Pull request closed without merging**
