### PR TITLE
[SPARK-40058][CORE] Avoid filter file path more than once in HadoopFSUtils

### PR DESCRIPTION
**Pull request by guanziyue**
### What changes were proposed in this pull request?
Refactor path filter logic in HadoopFSUtils to avoid the same filter logic is applied to a file multiple time. Method listLeafFiles is called recursively. Especially, this filter will be used in single thread on all files at driver side. This will lead to a performance issue when the filter logic is heavy. 

### Why are the changes needed?
Apply filter only on filestatus as soon as they are firstly met.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
No test was added as such change is simple enough.

### CODE REVIEW

**Comment by JoshRosen** [comment]
(Drive-by comment / note to other reviewers): it looks like this PR and https://github.com/apache/spark/pull/37467 are aiming to solve the same problem (and thus are duplicates). We should pick a preferred approach and close one of the PRs / JIRAs as a duplicate.

**Comment by guanziyue** [comment]
> (Drive-by comment / note to other reviewers): it looks like this PR and #37467 are aiming to solve the same problem (and thus are duplicates). We should pick a preferred approach and close one of the PRs / JIRAs as a duplicate.

Thanks for your remind and wangguangxin. Could we continue with this PR?

**Review by srowen — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
nit.
- @WangGuangxin 's PR seems to be opened 2 days ago before this PR and smaller than this PR. There is no difference in the logic.
- Also, SPARK-40035 is reported before SPARK-40058.

In this case, technically, we used to keep the smallest JIRA ID (and its earlier code contribution) in the community. And, SPARK-40058 and this PR is supposed to be closed as `Duplicated`.

Just a question. @WangGuangxin and @guanziyue , is there any coordination between you in order to keep this one?

**Comment by WangGuangxin** [comment]
> nit.
> 
> * @WangGuangxin 's PR seems to be opened 2 days ago before this PR and smaller than this PR. There is no difference in the logic.
> * Also, [SPARK-40035](https://issues.apache.org/jira/browse/SPARK-40035) is reported before [SPARK-40058](https://issues.apache.org/jira/browse/SPARK-40058) (this PR's JIRA).
> 
> In this case, technically, we used to keep the smallest JIRA ID (and its earlier code contribution) in the community. And, [SPARK-40058](https://issues.apache.org/jira/browse/SPARK-40058) and this PR is supposed to be closed as `Duplicated`.
> 
> Just a question. @WangGuangxin and @guanziyue , is there any coordination between you in order to keep this one?

Yes, we have been communicated offline, just go ahead please. Thanks

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
