### PR TITLE
[SPARK-46526][SQL] Support LIMIT over correlated subqueries where predicates only reference outer table

### PR DESCRIPTION
**Pull request by agubichev**
### What changes were proposed in this pull request?

The type of query that this PR addresses is the following:

```
SELECT COUNT(DISTINCT(t1a))
FROM t1
WHERE t1d IN (SELECT t2d
              FROM   t2
              WHERE t1a IS NOT NULL
              LIMIT 10);
```

Here, the predicate in the subquery `t1a IS NOT NULL` does not reference the inner table at all, so our standard decorrelation technique of "compute 10 values of t2d per every value of the inner table" does not work. In fact, such predicates can be lifted above the limit 10. This PR achieves exactly that.

### Why are the changes needed?

Fixed the bug.

### Does this PR introduce _any_ user-facing change?

Some broken queries are now working.

### How was this patch tested?

Query tests.

### Was this patch authored or co-authored using generative AI tooling?

No

### CODE REVIEW

**Comment by agubichev** [comment]
@jchen5

**Comment by jchen5** [comment]
Thanks for the PR! Is there any concern about the interaction between limit and pulling outer query filters up over aggregates (since that has been a fairly subtle area)? I see coverage for aggregates without group-by, can we also add test coverage with limit over group by?

**Comment by agubichev** [comment]
> Thanks for the PR, looks good! Is there any concern about the interaction between limit and pulling outer query filters up over aggregates (since that has been a fairly subtle area)? I see coverage for aggregates without group-by, can we also add test coverage with limit over group by?

Added tests with grouping keys (and couple tests with just aggregates) to test those interactions

**Review by jchen5 — APPROVED** [review]
Looks good, thanks!

**Comment by agubichev** [comment]
@cloud-fan

**Review by cloud-fan — APPROVED** [review]

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Pull request closed without merging**
