### PR TITLE
[SPARK-47293][CORE] Build batchSchema with sparkSchema instead of append one by one

### PR DESCRIPTION
**Pull request by zwangsheng**
### What changes were proposed in this pull request?

Simplify the building process of `batchSchema` by passing  `sparkSchema.fields` instead of call `add` function one by one. 

Additional resource overhead is avoided

https://github.com/apache/spark/blob/d7cc708e1e0dbda93f07832ae5e18cbc075f6431/sql/api/src/main/scala/org/apache/spark/sql/types/StructType.scala#L150-L152

### Why are the changes needed?

As the above said.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Exists unit test.

### Was this patch authored or co-authored using generative AI tooling?

No

### CODE REVIEW

**Review by ShreyeshArangath — APPROVED** [review]
LGTM!

**Review by ulysses-you — APPROVED** [review]
cc @yaooqinn @cloud-fan

**Review by yaooqinn — APPROVED** [review]

**Comment by yaooqinn** [comment]
Thank you all. Merged to master

**Comment by zwangsheng** [comment]
@ShreyeshArangath @yaooqinn @ulysses-you thanks all of you!

**Pull request closed without merging**
