### PR TITLE
[SPARK-19033][Core] Add admin acls for history server

### PR DESCRIPTION
**Pull request by jerryshao**
## What changes were proposed in this pull request?

Current HistoryServer's ACLs is derived from application event-log, which means the newly changed ACLs cannot be applied to the old data, this will become a problem where newly added admin cannot access the old application history UI, only the new application can be affected. 

So here propose to add admin ACLs for history server, any configured user/group could have the view access to all the applications, while the view ACLs derived from application run-time still take effect.

## How was this patch tested?

Unit test added.

### CODE REVIEW

**Review by tgravescs — COMMENTED** [review]
Mostly looks good. Please make sure to test all the different scenarios. history admin acls blank with app acls set, user level admin acls blank with history acls set, both blank.

**Comment by jerryshao** [comment]
Thanks @tgravescs for your comments, I've updated the code to add more tests accordingly. Please review.

**Comment by jerryshao** [comment]
Jenkins, retest this please.

**Comment by tgravescs** [comment]
+1

**Pull request closed without merging**
