### PR TITLE
Revert [SPARK-43836][SPARK-43845][SPARK-43858][SPARK-43858] to keep Scala 2.12 for Spark 3.x

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to revert the following 4 commits effectively.

SPARK-43836 Make Scala 2.13 as default in Spark 3.5
SPARK-43845 Setup Scala 2.12 Daily GitHub Action Job
SPARK-43858 Make benchmark Github Action task use Scala 2.13 as default
SPARK-43858 Restore the Scala version to 2.13 after run benchmark

### Why are the changes needed?

According to the dev mailing list discussion, we keep the Scala 2.12 for Spark 3.x.
- https://lists.apache.org/thread/xz7x0nkjn1d13yl9on59lfttm6f0yd45

We open a new thread, "Apache Spark 4.0 Timeframe?", for Spark 4 planning.
- https://lists.apache.org/thread/xhkgj60j361gdpywoxxz7qspp2w80ry6

### Does this PR introduce _any_ user-facing change?

No. This is a recovery to the existing behavior.

### How was this patch tested?
Pass the CIs.

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]
Thank you!

**Comment by dongjoon-hyun** [comment]
Thank you, @HyukjinKwon . Also, cc @srowen , @LuciferYang .

**Review by LuciferYang — APPROVED** [review]
+1, LGTM

**Comment by LuciferYang** [comment]
So we needn't to update the benchmark results for Scala 2.13 for now, right? I'll close [SPARK-43857](https://issues.apache.org/jira/browse/SPARK-43857)

**Comment by dongjoon-hyun** [comment]
We may keep them in a separate directory or different file names later. But, yes, we are unable to overwrite them for now.. Sorry for that.

**Comment by LuciferYang** [comment]
> We may keep them in a separate directory or different file names later. But, yes, we are unable to overwrite them for now.. Sorry for that.

Got it, Let's wait  ~

**Comment by dongjoon-hyun** [comment]
Thank you. Merged to master.

**Pull request closed without merging**
