### PR TITLE
[SPARK-33310][PYTHON] Relax pyspark typing for sql str functions

### PR DESCRIPTION
**Pull request by dhimmel**
### What changes were proposed in this pull request?

Relax pyspark typing for sql str functions. These functions all pass the first argument through `_to_java_column`, such that a string or Column object is acceptable.

### Why are the changes needed?

Convenience & ensuring the typing reflects the functionality

### Does this PR introduce _any_ user-facing change?

Yes, a backwards-compatible increase in functionality. But I think typing support is unreleased, so possibly no change to released versions.

### How was this patch tested?

Not tested. I am newish to Python typing with stubs, so someone should confirm this is the correct way to fix this.

### CODE REVIEW

**Comment by dhimmel** [comment]
Here's the `_to_java_column` source code:

https://github.com/apache/spark/blob/491a0fb08b0c57a99894a0b33c5814854db8de3d/python/pyspark/sql/column.py#L39-L50

**Comment by dhimmel** [comment]
@zero323 is this the right way to update the typing for these functions?

**Comment by zero323** [comment]
Thanks @dhimmel 

Could you create a JIRA ticket and update the title to reflect that (`[SPARK-XXXXX][PYTHON] Relax pyspark typing for sql str functions`)?

> @zero323 is this the right way to update the typing for these functions?

It looks reasonable. It is equivalent, to what's [proposed before](https://github.com/zero323/pyspark-stubs/pull/420) in pyspark-stubs ‒ personally I was concerned that this might be confusing  or ambiguous, but it might be overthinking.

About testing annotations, please check [Contributing and Maintaining Type Hints](https://github.com/apache/spark/blob/master/python/docs/source/development/contributing.rst#contributing-and-maintaining-type-hints). In general things look OK (I tested your PR locally and this is covered by existing tests).

**Comment by dhimmel** [comment]
Thanks @zero323 for the helpful info and pointing me towards https://github.com/zero323/pyspark-stubs/pull/420. I'll add the change to `.locate` as well. Perhaps if this is merged, @harpaj could get credit via the commit message and [GitHub's](https://docs.github.com/en/free-pro-team@latest/github/committing-changes-to-your-project/creating-a-commit-with-multiple-authors):

```
Co-authored-by: Johannes Huber <johannes.huber@trustyou.net>
```

Opened an issue at https://issues.apache.org/jira/browse/SPARK-33310.

**Comment by zero323** [comment]
cc @HyukjinKwon

**Comment by HyukjinKwon** [comment]
ok to test

**Review by HyukjinKwon — APPROVED** [review]

**Review by zero323 — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
