### PR TITLE
Revert "[SPARK-36429][SQL] JacksonParser should throw exception when data type unsupported"

### PR DESCRIPTION
**Pull request by sarutak**
### What changes were proposed in this pull request?

This PR reverts the change in SPARK-36429 (#33654).
See [conversation](https://github.com/apache/spark/pull/33654#issuecomment-894160037).

### Why are the changes needed?

To recover CIs.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

N/A

### CODE REVIEW

**Comment by sarutak** [comment]
Confirmed all the `Json*Suite` pass on my laptop so I'll merge this to `master` and `branch-3.2` not to block other PRs.

**Comment by dongjoon-hyun** [comment]
+1, LGTM. Thank you, @sarutak .

**Comment by HyukjinKwon** [comment]
@sarutak would you mind reopening the JIRA and removing fixed versions too?

**Comment by sarutak** [comment]
@HyukjinKwon #33684 seems to resolve the issue right?

**Comment by HyukjinKwon** [comment]
ohh it was merged back

**Pull request closed without merging**
