### PR TITLE
[HOTFIX] Replace `sqlContext` and `sparkSession` with `spark`.

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
## What changes were proposed in this pull request?

This replaces `sparkSession` with `spark` in CatalogSuite.scala.
## How was this patch tested?

Pass the Jenkins tests.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Hi, @andrewor14   @techaddict 
Typo errors seem to break builds.

**Comment by dongjoon-hyun** [comment]
Oh, there are more. I'll add more commits.

**Comment by techaddict** [comment]
@dongjoon-hyun Thanks for doing this, merging should have caused problems since it was a very big patch. 👍

**Comment by dongjoon-hyun** [comment]
@andrewor14 . I've saw you fixed the first one. Please fix the second one, too.

**Comment by dongjoon-hyun** [comment]
I rebased. 
Right, it was a huge work. Great, @techaddict !

**Comment by andrewor14** [comment]
LGTM merging into master 2.0

**Comment by dongjoon-hyun** [comment]
Thank you. I think that's all. This passed the following, locally.
```
build/mvn -T 4 -q -DskipTests -Pyarn -Phadoop-2.3 -Pkinesis-asl -Phive -Phive-thriftserver install
```

**Comment by andrewor14** [comment]
Thanks for catching this @dongjoon-hyun. I'm surprised Jenkins didn't catch it.

**Pull request closed without merging**
