### PR TITLE
[WIP][CORE] Fix Spark History Server UI

### PR DESCRIPTION
**Pull request by dongjoon-hyun**

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Although I made a draft, this is super ugly and not good. 

If you can recover SHS feature today, I'll leave this to you, @yaooqinn .

**Comment by dongjoon-hyun** [comment]
Please feel free to ping me on your PR if you want to proceed.

**Comment by dongjoon-hyun** [comment]
BTW, both Chrome and Safari Browser Developer tool doesn't give any warnings or error with this kind of `module` issues. I'm starting to worry about any UI issue due to the `module` change.

**Comment by yaooqinn** [comment]
I believe this pain point for migration is mainly caused by `eslint-disable no-unused-vars`; otherwise, we can take care of every function that needs to be exported and covered in the js tests

**Comment by yaooqinn** [comment]
Hi @dongjoon-hyun, I have created #44931 to fix the history page. Could you verify it and see if the problems we try to fix are arecomplementary or the same.

**Comment by dongjoon-hyun** [comment]
Great. Thank you! Sure.

**Comment by dongjoon-hyun** [comment]
I close this in favor of #44931 .

**Pull request closed without merging**
