### PR TITLE
[SPARK-11694] [SQL] Backports #9754

### PR DESCRIPTION
**Pull request by HyukjinKwon**
The main purpose of this PR is to backport https://github.com/apache/spark/pull/9754

I added several commits but they are identical with the PR.

I will cc @liancheng just to find this easily.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
I mistakenly added SPARK-11692 here as I though this is supposed to go to branch 1.6.0 but this is classified for version 1.7.

I will take this out.

**Comment by liancheng** [comment]
LGTM pending Jenkins.

**Comment by liancheng** [comment]
Thanks! Merging to branch-1.6.

BTW, it's not a big deal, but you can cc other users in comments instead of in PR descriptions. Because the PR description will be part of the final commit message when a PR is merged.

**Comment by JoshRosen** [comment]
Hi @HyukjinKwon, would you mind closing this PR on GitHub now that it's been merged? GitHub won't auto-close backport branch PRs like this one.

**Comment by HyukjinKwon** [comment]
Oh. Right. Thanks!

Closing this.

**Pull request closed without merging**
