### PR TITLE
[SPARK-10269][Pyspark][MLLib] Add @since annotation to pyspark.mllib.classification

### PR DESCRIPTION
**Pull request by noel-smith**
Duplicated the @since decorator from pyspark.sql into pyspark (also tweaked to handle functions without docstrings).

Added @since to methods + "versionadded::" to classes derived from the file history.

Note - some methods are inherited from the regression module (i.e. LinearModel.intercept) so these won't have version numbers in the API docs until that model is updated.

### CODE REVIEW

**Comment by noel-smith** [comment]
Jenkins, retest this please

**Comment by mengxr** [comment]
test this please

**Comment by mengxr** [comment]
@yu-iskw Could you help review this PR? Thanks!

**Comment by yu-iskw** [comment]
LGTM

**Comment by mengxr** [comment]
Merged into  master. Thanks!

**Pull request closed without merging**
