### PR TITLE
[SPARK-32816][SQL][3.0] Fix analyzer bug when aggregating multiple distinct DECIMAL columns

### PR DESCRIPTION
**Pull request by linhongliu-db**
### What changes were proposed in this pull request?
This PR fixes a conflict between `RewriteDistinctAggregates` and `DecimalAggregates`.
In some cases, `DecimalAggregates` will wrap the decimal column to `UnscaledValue` using
different rules for different aggregates.

This means, same distinct column with different aggregates will change to different distinct columns
after `DecimalAggregates`. For example:
`avg(distinct decimal_col), sum(distinct decimal_col)` may change to
`avg(distinct UnscaledValue(decimal_col)), sum(distinct decimal_col)`

We assume after `RewriteDistinctAggregates`, there will be at most one distinct column in aggregates,
but `DecimalAggregates` breaks this assumption. To fix this, we have to switch the order of these two
rules.

### Why are the changes needed?
bug fix

### Does this PR introduce _any_ user-facing change?
no

### How was this patch tested?
added test cases

Authored-by: Linhong Liu <linhong.liu@databricks.com>
Signed-off-by: Wenchen Fan <wenchen@databricks.com>
(cherry picked from commit 40ef5c91ade906b38169f959b3991ce8b0f45154)

### CODE REVIEW

**Comment by linhongliu-db** [comment]
This PR depends on https://github.com/apache/spark/pull/30052 to pass tests

**Comment by linhongliu-db** [comment]
retest this please

**Comment by linhongliu-db** [comment]
@cloud-fan This PR depends on another 2 fixes in the master branch. Should we cherry-pick them?
https://github.com/apache/spark/pull/29026
https://github.com/apache/spark/pull/27627

**Comment by cloud-fan** [comment]
ah, that two are hard to backport as they change streaming state store. I guess we can't backport this fix either.

**Comment by linhongliu-db** [comment]
got it. Let's close it for now

**Pull request closed without merging**
