### PR TITLE
[SPARK-39954][BUILD] Upgrade ASM to 9.3

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to upgrade ASM to 9.3.

### Why are the changes needed?

This will help us to use Java 19 and to be ready for the future releases.
- https://openjdk.org/projects/jdk/19/ (RC1: Aug 11st, GA: Sep 20th) 
- https://asm.ow2.io/versions.html
- https://issues.apache.org/jira/browse/XBEAN-334 Upgrade to ASM 9.3

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the CIs.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Could you review this, @viirya ?

BTW, the CRAN check failure is irrelevant to this PR.

**Review by viirya — APPROVED** [review]
Looks good as CI passes and this is minor upgrade.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by viirya** [comment]
Merged. Thanks!

**Comment by dongjoon-hyun** [comment]
Thank you, @HyukjinKwon and @viirya .

**Pull request closed without merging**
