### PR TITLE
[SPARK-35714][FOLLOW-UP][CORE] WorkerWatcher should run System.exit in a thread out of RpcEnv 

### PR DESCRIPTION
**Pull request by Ngone51**
### What changes were proposed in this pull request?

This PR proposes to let `WorkerWatcher` run `System.exit` in a separate thread instead of some thread of `RpcEnv`.

### Why are the changes needed?

`System.exit` will trigger the shutdown hook to run `executor.stop`, which will result in the same deadlock issue with SPARK-14180. But note that since Spark upgrades to Hadoop 3  recently, each hook now will have a [timeout threshold](https://github.com/apache/hadoop/blob/d4794dd3b2ba365a9d95ad6aafcf43a1ea40f777/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/util/ShutdownHookManager.java#L205-L209) which forcibly interrupt the hook execution once reaches timeout. So, the deadlock issue doesn't really exist in the master branch. However, it's still critical for previous releases and is a wrong behavior that should be fixed.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Tested manually.

### CODE REVIEW

**Comment by Ngone51** [comment]
cc @mridulm @cloud-fan @jiangxb1987

**Review by cloud-fan — APPROVED** [review]
good catch!

**Comment by andrewli81** [comment]
Thanks for proactively fixing this!

**Review by jiangxb1987 — APPROVED** [review]
LGTM!

**Comment by Ngone51** [comment]
Thanks all! Merged to Master/branch-3.2/branch-3.1/branch-3.0.

**Comment by mridulm** [comment]
Late +1

**Pull request closed without merging**
