### PR TITLE
[SPARK-47278][BUILD] Upgrade rocksdbjni to 8.11.3

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr aims to upgrade rocksdbjni from 8.8.1 to 8.11.3.

### Why are the changes needed?
The new version bring some bug fixes:

- Fix a corner case with auto_readahead_size where Prev Operation returns NOT SUPPORTED error when scans direction is changed from forward to backward.
- Avoid destroying the periodic task scheduler's default timer in order to prevent static destruction order issues.
- Fix double counting of BYTES_WRITTEN ticker when doing writes with transactions.
- Fix a WRITE_STALL counter that was reporting wrong value in few cases.
- A lookup by MultiGet in a TieredCache that goes to the local flash cache and finishes with very low latency, i.e before the subsequent call to WaitAll, is ignored, resulting in a false negative and a memory leak.
- Fix bug in auto_readahead_size that combined with IndexType::kBinarySearchWithFirstKey + fails or iterator lands at a wrong key
- Fixed some cases in which DB file corruption was detected but ignored on creating a backup with BackupEngine.
- Fix bugs where rocksdb.blobdb.blob.file.synced includes blob files failed to get synced and rocksdb.blobdb.blob.file.bytes.written includes blob bytes failed to get written.
- Fixed a possible memory leak or crash on a failure (such as I/O error) in automatic atomic flush of multiple column families.
- Fixed some cases of in-memory data corruption using mmap reads with BackupEngine, sst_dump, or ldb.
- Fixed issues with experimental preclude_last_level_data_seconds option that could interfere with expected data tiering.
- Fixed the handling of the edge case when all existing blob files become unreferenced. Such files are now correctly deleted.

The full release notes as follows:

- https://github.com/facebook/rocksdb/releases/tag/v8.9.1
- https://github.com/facebook/rocksdb/releases/tag/v8.10.0
- https://github.com/facebook/rocksdb/releases/tag/v8.11.3

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass GitHub Actions

### Was this patch authored or co-authored using generative AI tooling?
No

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Thank you, @LuciferYang . Is it ready?

**Comment by LuciferYang** [comment]
Let's run another two or three rounds of tests

**Review by yaooqinn — APPROVED** [review]

**Comment by yaooqinn** [comment]
Merged to master.

Thank you @LuciferYang @dongjoon-hyun

**Comment by LuciferYang** [comment]
Thanks @yaooqinn @dongjoon-hyun

**Review by dongjoon-hyun — COMMENTED** [review]
+1, LGTM. Thank you!

**Pull request closed without merging**
