### PR TITLE
[SPARK-7867][SQL] Support "revoke role ..."

### PR DESCRIPTION
**Pull request by pzzs**
SQL like

```
revoke role role_a from user user1;
```

### CODE REVIEW

**Comment by DoingDone9** [comment]
@scwf

**Comment by scwf** [comment]
what is "revoke role" ?

**Comment by DoingDone9** [comment]
Cancel user role in permission control

**Comment by DoingDone9** [comment]
@marmbrus

**Comment by rxin** [comment]
Are there any more tests we can enable to run this?

**Pull request closed without merging**
