### PR TITLE
[SPARK-40768][SQL] Migrate type check failures of bloom_filter_agg() onto error classes

### PR DESCRIPTION
**Pull request by lvshaokang**
### What changes were proposed in this pull request?

In the PR, I propose to use error classes in the case of type check failure in Bloom Filter Agg expressions.

### Why are the changes needed?

Migration onto error classes unifies Spark SQL error messages.

### Does this PR introduce _any_ user-facing change?

Yes. The PR changes user-facing error messages.

### How was this patch tested?

```
build/sbt "sql/testOnly *SQLQueryTestSuite"
build/sbt "test:testOnly org.apache.spark.SparkThrowableSuite"
build/sbt "test:testOnly *BloomFilterAggregateQuerySuite"
```

### CODE REVIEW

**Comment by lvshaokang** [comment]
cc @MaxGekk

**Comment by MaxGekk** [comment]
@lvshaokang Isn't the failure related to your changes?
```
Different files: ['base_pb2.pyi', 'commands_pb2.pyi', 'expressions_pb2.pyi', 'relations_pb2.pyi', 'types_pb2.pyi']
Generated files for pyspark-connect are out of sync! Please run ./connector/connect/dev/generate_protos.sh
Error: Process completed with exit code 255.
```

**Comment by lvshaokang** [comment]
@MaxGekk No, It seems to be unrelated, I don't know why it would lead to this, and I tried retrying CI, but it still reports an error.

**Comment by MaxGekk** [comment]
@HyukjinKwon @zhengruifeng @grundprinzip Should we worry about the failures https://github.com/apache/spark/pull/38315#issuecomment-1285894438 or can just ignore them?

**Comment by grundprinzip** [comment]
> @HyukjinKwon @zhengruifeng @grundprinzip Should we worry about the failures https://github.com/apache/spark/pull/38315#issuecomment-1285894438 or can just ignore them?

In theory, of you merge master into your branch this should go away as current master should be in sync.

**Comment by lvshaokang** [comment]
> In theory, of you merge master into your branch this should go away as current master should be in sync.

I have merged the master branch into my branch and push it, wating the CI complete.

**Comment by lvshaokang** [comment]
@MaxGekk CI run successful. Please take a look, thanks.

**Review by MaxGekk — APPROVED** [review]

**Comment by MaxGekk** [comment]
+1, LGTM. Merging to master.
Thank you, @lvshaokang.

**Comment by zhengruifeng** [comment]
> @HyukjinKwon @zhengruifeng @grundprinzip Should we worry about the failures [#38315 (comment)](https://github.com/apache/spark/pull/38315#issuecomment-1285894438) or can just ignore them?

that was due to mypy-protobuf upgrade, now the version was pined in  https://github.com/apache/spark/commit/0643d02e4f03cdadb53efc05af0b6533d22db297

**Pull request closed without merging**
