### PR TITLE
[SPARK-15092][PySpark][ML] Add toDebugString to DecisionTreeModel

### PR DESCRIPTION
**Pull request by holdenk**
## What changes were proposed in this pull request?

Add toDebugString to DecisionTreeModel. This is related to https://github.com/apache/spark/pull/12919 but different base class.
## How was this patch tested?

DocTests

### CODE REVIEW

**Comment by holdenk** [comment]
cc @yanboliang

**Comment by yanboliang** [comment]
This looks good to me, but I think we can collect all missing methods/parameters for one algorithm or component in a single PR which will be easy to review. Could you consolidate this with #12919 into one PR? Thanks!

**Comment by holdenk** [comment]
I can merge this in if we want, it is a seperate alg but related component.

**Comment by holdenk** [comment]
Closing and merging into https://github.com/apache/spark/pull/12919

**Pull request closed without merging**
