### PR TITLE
[SPARK-45288][TESTS] Remove outdated benchmark result files, `*-jdk1[17]*results.txt`

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR is a pure clean-up file to avoid confusion.

### Why are the changes needed?

- Old results are based on Scala 2.12 while the current build is Scala 2.13.
- This result will not be updated in the future because Scala 2.13 support is dropped.
- Java 11 result is also outdated because Java 11 support is dropped .
- Java 17 result will be stored in `-results.txt` instead of `-jdk17-result.txt` file because Java 17 is the default now.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Manual review.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
cc @LuciferYang

**Comment by dongjoon-hyun** [comment]
I tried to clean-up this in my regeneration PR, but it makes the commit log weird because Git thinks is renaming.

**Comment by dongjoon-hyun** [comment]
Could you review this PR, @attilapiros ? After we switching to Java 17+, there are several clean-up PRs like this.

**Comment by dongjoon-hyun** [comment]
This PR is irrelevant from CI result. So, please note that I stopped the runnjng pipelines on this PR manually to unblock my other PRs.

**Review by LuciferYang — APPROVED** [review]
LGTM

**Comment by LuciferYang** [comment]
Merged into master for Apache Spark 4.0, thanks @dongjoon-hyun

**Comment by dongjoon-hyun** [comment]
Thank you, @LuciferYang !

**Pull request closed without merging**
