### PR TITLE
[SPARK-35785][SS][3.2] Cleanup support for RocksDB instance

### PR DESCRIPTION
**Pull request by xuanyuanking**
### What changes were proposed in this pull request?
Add the functionality of cleaning up files of old versions for the RocksDB instance and RocksDBFileManager.

### Why are the changes needed?
Part of the implementation of RocksDB state store.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
New UT added.

### CODE REVIEW

**Comment by xuanyuanking** [comment]
cc @HeartSaVioR and @viirya

**Comment by HeartSaVioR** [comment]
Merged to branch-3.2.

**Comment by HeartSaVioR** [comment]
forgot my +1 . this is just a cherry-pick of #32933.

**Comment by xuanyuanking** [comment]
Thanks @HeartSaVioR!

**Comment by viirya** [comment]
Thanks @xuanyuanking and @HeartSaVioR!

**Pull request closed without merging**
