### PR TITLE
[SPARK-39505][UI] Escape log content rendered in UI

### PR DESCRIPTION
**Pull request by srowen**
### What changes were proposed in this pull request?

Escape log content rendered to the UI.

### Why are the changes needed?

Log content may contain reserved characters or other code in the log and be misinterpreted in the UI as HTML.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Existing tests

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Merged to master. Thank you, @srowen .

**Comment by srowen** [comment]
This needs to back-port - I can do that

**Comment by srowen** [comment]
Also merged to 3.3, 3.2, 3.1

**Comment by dongjoon-hyun** [comment]
+1 for backporting. Thanks.

**Pull request closed without merging**
