### PR TITLE
[SPARK-21965] [SparkR] Add createOrReplaceGlobalTempView and dropGlobalTempView for SparkR

### PR DESCRIPTION
**Pull request by yanboliang**
## What changes were proposed in this pull request?
Add ```createOrReplaceGlobalTempView``` and ```dropGlobalTempView``` for SparkR.

## How was this patch tested?
Unit tests.

### CODE REVIEW

**Comment by yanboliang** [comment]
cc @felixcheung

**Comment by felixcheung** [comment]
Wait. We had this in PR earlier?
And my suggestion is not to have this without having a method to control global session. As of now there isn't a way to keep a global session in R - everything stops when sparkR.session.stop()

I'll find the PR and the discussion there in later.

**Comment by HyukjinKwon** [comment]
I think it should be https://github.com/apache/spark/pull/17941. I was there too.

**Comment by felixcheung** [comment]
Ah yes thanks. I couldn't find it.

I think we should leave the JIRA open and explain we should consider multiple session support (could be a big change) or some workaround for a persisted global session in R.

**Comment by dongjoon-hyun** [comment]
Ya. I was there, too.

**Comment by yanboliang** [comment]
Oh sorry, I didn't find that PR before. Let's discuss this issue in that JIRA, I'll close this PR. Thanks for all your kindly remind.

**Pull request closed without merging**
