### PR TITLE
[SPARK-13105] Reject NATURAL JOIN queries rather than returning wrong answers

### PR DESCRIPTION
**Pull request by JoshRosen**
In Spark 1.6 and earlier, Spark SQL does not support `NATURAL JOIN` queries. However, its SQL parser does not consider `NATURAL` to be a reserved word, which causes natural joins to be parsed as regular joins where the left table has been aliased. For instance,

```
SELECT * FROM foo NATURAL JOIN bar
```

gets interpreted as `foo JOIN bar` where `foo` is aliased to `natural`.

Rather than doing this, which leads to confusing / wrong results for users who expect NATURAL JOIN behavior, Spark should immediately reject these queries at analysis time and should provide an informative error message.

This patch is targeted at Spark 1.6 and earlier because Spark 2.0 will add NATURAL JOIN support.

I chose to implement this check entirely within the parser in order to minimize the scope of the changes and to not introduce any new classes into the logical plan layer. I considered introducing a new `NaturalJoin` join type, parsing the query, then detecting and throwing an error from the analyzer but ended up rejecting this approach because I was concerned that adding a new class to a sealed trait would break compilation for third-party code which pattern-matches on Catalyst join types.

### CODE REVIEW

**Comment by cloud-fan** [comment]
how about hive context? Should we update `HiveQl.scala` too?

**Comment by rxin** [comment]
hm i thought about this more -- i actually think it is too risky to change the behavior here for 1.6.x. For example, there might be users whose queries are depending on the fact that natural is not a reserved keyword.

**Comment by hvanhovell** [comment]
Hive does not have a ```NATURAL``` keyword. It behaves the same as the old SqlParser: 

- It will either treat ```NATURAL``` the alias of the previous table, eg: ```select * from db.a natural join db.b```
- It does not recognize the input at ```NATURAL``` and throws a ```ParseException```, eg: ```select * from db.a as x natural join db.b```

**Comment by JoshRosen** [comment]
Argh, that's annoying. I guess I'll go ahead and close this PR and resolve the JIRA issue as "Not a Problem".

**Pull request closed without merging**
