### PR TITLE
[GRAPHX][EXAMPLES] move graphx test data directory and update graphx document

### PR DESCRIPTION
**Pull request by WeichenXu123**
## What changes were proposed in this pull request?

There are two test data files used for graphx examples existing in directory "graphx/data"
I move it into "data/" directory because the "graphx" directory is used for code files and other test data files (such as mllib, streaming test data) are all in there.

I also update the graphx document where reference the data files which I move place.
## How was this patch tested?

N/A

### CODE REVIEW

**Comment by srowen** [comment]
LGTM

**Comment by WeichenXu123** [comment]
Jenkins retest this please.

**Comment by WeichenXu123** [comment]
Jenkins, test this please.

**Comment by WeichenXu123** [comment]
@srowen Done.

**Comment by srowen** [comment]
Merged to master/2.0

**Pull request closed without merging**
