### PR TITLE
[SPARK-8118] [SQL] Redirects Parquet JUL logger via SLF4J

### PR DESCRIPTION
**Pull request by liancheng**
Parquet hard coded a JUL logger which always writes to stdout. This PR redirects it via SLF4j JUL bridge handler, so that we can control Parquet logs via `log4j.properties`.

This solution is inspired by https://github.com/Parquet/parquet-mr/issues/390#issuecomment-46064909.

### CODE REVIEW

**Comment by liancheng** [comment]
cc @davies

**Comment by liancheng** [comment]
The last build failure was actually caused by a dependency resolution timeout.

**Comment by liancheng** [comment]
retest this please

**Comment by liancheng** [comment]
retest this please

**Comment by davies** [comment]
@liancheng I tried it locally (compiled without assembly), the logging from parquet still came out (updated the log4j configs).

**Comment by liancheng** [comment]
@davies Sorry that I used the wrong logger name, should be package name rather than the class name of the logger.

**Comment by liancheng** [comment]
Seems that now Parquet logs are successfully suppressed, but I hit the opposite problem: I can't get Parquet logs written even if I turn log level under INFO. Instead, I always see this when Parquet logs should be printed:

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

However, slf4j-log4j12 classes are already properly packaged into the assembly jar. This is irrelevant to Hive isolated client loader, since I tested this issue without enabling `-Phive`.

**Comment by davies** [comment]
@liancheng It works like a charm, thanks! LGTM.

**Comment by liancheng** [comment]
@davies Nah, it works too well... Please see my last comment :)

**Comment by liancheng** [comment]
However, I think it's OK to have this merged, since we turned off Parquet logs completely in all prior versions.

**Comment by davies** [comment]
Even without this patch, we still see this warning about failed to load "org.slf4j.impl.StaticLoggerBinder", I think it's a another issue, we can merge this, leave that for another PR (https://issues.apache.org/jira/browse/SPARK-10057).

**Comment by davies** [comment]
cc @yhuai  for another look.

**Comment by yhuai** [comment]
Also add https://github.com/apache/spark/blob/master/sql/core/src/test/resources/log4j.properties#L39-L43 to https://github.com/apache/spark/blob/master/sql/hive/src/test/resources/log4j.properties?

**Comment by liancheng** [comment]
@yhuai Thanks, updated.

**Comment by liancheng** [comment]
The test failure is irrelevant. I'm merging this to master and branch-1.5.

**Pull request closed without merging**
