### PR TITLE
[SPARK-36002][PYTHON] Consolidate tests for data-type-based operations of decimal Series

### PR DESCRIPTION
**Pull request by Yikun**
### What changes were proposed in this pull request?
Merge test_decimal_ops into test_num_ops

- merge test_isnull() into test_num_ops.test_isnull()
- remove test_datatype_ops(), which already covered in https://github.com/apache/spark/blob/11fcbc73cbcbb1bdf5ba5d90eba0aba1edebb15d/python/pyspark/pandas/tests/data_type_ops/test_base.py#L58-L59

### Why are the changes needed?
Tests for data-type-based operations of decimal Series are in two places:

- python/pyspark/pandas/tests/data_type_ops/test_decimal_ops.py
- python/pyspark/pandas/tests/data_type_ops/test_num_ops.py

We'd better merge test_decimal_ops into test_num_ops.

See also [SPARK-36002](https://issues.apache.org/jira/browse/SPARK-36002) .

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
unittests passed

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @xinrong-databricks @ueshin FYI

**Comment by xinrong-databricks** [comment]
Thank you @Yikun! That makes code much cleaner.

What do you think of testing other operators (e.g.`test_add`) for `numeric_withnan_pser_psser_pairs`? That would be helpful to reveal potential differences from pandas' results.

**Comment by Yikun** [comment]
@xinrong-databricks 
> What do you think of testing other operators (e.g.test_add) for numeric_withnan_pser_psser_pairs? That would be helpful to reveal potential differences from pandas' results.

I try to add them, but I found there are so many different unexpection behaviour, looks like we should address them in a separte PR. See example error in https://issues.apache.org/jira/browse/SPARK-36031 .

**Comment by xinrong-databricks** [comment]
Sounds good. I wasn't aware that these operations are not supported for the Decimal series with `nan`.
Thank you!

**Review by xinrong-meng — APPROVED** [review]

**Comment by Yikun** [comment]
@xinrong-databricks done, it has been updated.

**Comment by HyukjinKwon** [comment]
@Yikun sorry there seems some conflicts. Would you mind resolving it please?

**Review by HyukjinKwon — APPROVED** [review]

**Review by ueshin — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
GA passed.
Merged to master and branch-3.2.

**Pull request closed without merging**
