### PR TITLE
[SPARK-41136][K8S][FOLLOW-ON] Adjust graceful shutdown time of ExecutorPodsSnapshotsStoreImpl according to hadoop config

### PR DESCRIPTION
**Pull request by tedyu**
### What changes were proposed in this pull request?
This PR adjusts graceful shutdown time of ExecutorPodsSnapshotsStoreImpl according to hadoop config `hadoop.service.shutdown.timeout`.

### Why are the changes needed?
This is a follow on for commit 9ab8ba73a384b207bd7bbea5db40eeccdc76ffa4, `Shorten graceful shutdown time of ExecutorPodsSnapshotsStoreImpl to prevent blocking shutdown process`.

Since the value of `hadoop.service.shutdown.timeout` may be different from the default value, we should adjust the value for `KUBERNETES_EXECUTOR_SNAPSHOTS_SUBSCRIBERS_GRACE_PERIOD` accordingly.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Existing test suite.

### CODE REVIEW

**Comment by tedyu** [comment]
cc @holdenk @pan3793 @dongjoon-hyun

**Comment by dongjoon-hyun** [comment]
Could you use a new JIRA ID? The proposal has a little different goal and sideeffect.

**Comment by tedyu** [comment]
Sure.
Can I gather some feedback before creating the JIRA ?

e.g. One option is to redefine `KUBERNETES_EXECUTOR_SNAPSHOTS_SUBSCRIBERS_GRACE_PERIOD` to have the meaning of `GRACE_PERIOD_FOR_HADOOP` shown in this PR (assuming `KUBERNETES_EXECUTOR_SNAPSHOTS_SUBSCRIBERS_GRACE_PERIOD` hasn't appeared in any Spark release yet).

**Comment by tedyu** [comment]
We can define `KUBERNETES_EXECUTOR_SNAPSHOTS_SUBSCRIBERS_GRACE_PERIOD` as the percentage based on the value of `hadoop.service.shutdown.timeout`. In @pan3793 's PR, the percentage is 30%.
This way, when the value of `hadoop.service.shutdown.timeout` is bigger than 30s, we can utilize the bigger timeout.

**Comment by pan3793** [comment]
Usually, it's a good idea to make the default value of configurations adaptive, but I'm not sure about this one. (choosing the 20s as the default value is because I don't want to change the behavior a lot from the original 30s, actually, I set this value to 10s in our internal).

In our practice, as all shutdown procedures in SparkShutdownHookManager shares `hadoop.service.shutdown.timeout`, the procedures are usually blocked by custom listeners(they are provided by different teams or spark users, and some of them may do a final flush when accepting `SparkListenerApplicationEnd` that may cost dozens of seconds or even minutes), we recommend all of them to set a timeout to 10s or shorter, so they can works fine w/ default 30s timeout limits in most case. So in my case, if I enlarge `hadoop.service.shutdown.timeout`, it's mostly because listeners cost much time during the shutdown phase, automatically increasing `KUBERNETES_EXECUTOR_SNAPSHOTS_SUBSCRIBERS_GRACE_PERIOD` is not what I want.

**Comment by tedyu** [comment]
@pan3793 
Thanks for sharing the background.
The current formation of this PR goes along with your change.

If `hadoop.service.shutdown.timeout` is lowered, we want to use smaller value for `KUBERNETES_EXECUTOR_SNAPSHOTS_SUBSCRIBERS_GRACE_PERIOD` config so that the intention for the shutdown timeout is satisfied.

**Comment by tedyu** [comment]
Reading @pan3793 's comment again:
```
it's mostly because listeners cost much time during the shutdown phase, automatically increasing KUBERNETES_EXECUTOR_SNAPSHOTS_SUBSCRIBERS_GRACE_PERIOD is not what I want.
```
With higher `hadoop.service.shutdown.timeout` value (than the default), `KUBERNETES_EXECUTOR_SNAPSHOTS_SUBSCRIBERS_GRACE_PERIOD` should be higher as well (to accommodate the listeners).

@pan3793 
Can you elaborate on your last sentence ?

Thanks

**Comment by pan3793** [comment]
@tedyu sorry if my words is ambiguous, the "listener" means `org.apache.spark.scheduler.SparkLisenter`, not the subscribers of "kubernetes executor snapshots".

During shutdown process, they share the "hadoop.service.shutdown.timeout", increasing KUBERNETES_EXECUTOR_SNAPSHOTS_SUBSCRIBERS_GRACE_PERIOD means decreasing grace period of `listenerBus.stop()`.

https://github.com/apache/spark/blob/1d2159f888139e65c80db2003d521b0f684df83a/core/src/main/scala/org/apache/spark/SparkContext.scala#L2125-L2136

For our cases, the authors of listener may not know much about the Spark internal, when they increases 20s to `hadoop.service.shutdown.timeout`, they may expect that the listener will get another 20s grace period.

To be clear, I am not oppose to your idea, just left my concerns.

**Comment by tedyu** [comment]
bq. when they increases 20s to hadoop.service.shutdown.timeout

Here is my proposed change:
```
        if (hadoopTimeout-GRACE_PERIOD_FOR_HADOOP <= awaitSeconds) {
            awaitSeconds = hadoopTimeout-GRACE_PERIOD_FOR_HADOOP
```
where `GRACE_PERIOD_FOR_HADOOP` is 8. This means the user cannot increase beyond 22s (for the default value of `hadoop.service.shutdown.timeout`).

@dongjoon-hyun 
Can you take a closer look at this PR since @pan3793 doesn't object ?

Thanks

**Pull request closed without merging**
