### PR TITLE
[MINOR][DOCS] Fix grammatical error in SortShuffleManager

### PR DESCRIPTION
**Pull request by deshanxiao**
## What changes were proposed in this pull request?

Fix a grammatical error in the comment of SortShuffleManager.

## How was this patch tested?

N/A

### CODE REVIEW

**Comment by holdensmagicalunicorn** [comment]
@deshanxiao, thanks! I am a bot who has found some folks who might be able to help with the review:@JoshRosen, @rxin and @cloud-fan

**Comment by HyukjinKwon** [comment]
It's okay @deshanxiao but mind taking another look and see if there are other typos in this module? I am pretty sure there are more and it should be good to fix them in a batch while we are here.

**Comment by HyukjinKwon** [comment]
ok to test

**Comment by deshanxiao** [comment]
Thanks a lot, I am sorry that I'm not able to find more clear errors. As a beginner, I am very glad to write more docs to help others understanding the spark core easier.

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by kiszk** [comment]
Would it be possible to address the following parts for `can ...`, `could ...`, `may ...`, and `will ...`, too?

`JavaSparkContextSuite.scala`
```
/**
 * Java apps can uses both Java-friendly JavaSparkContext and Scala SparkContext.
 */
``` 

`CodeGeneratorWithInterpretedFallback`
```
/**
 * A codegen object generator which creates objects with codegen path first. Once any compile
 * error happens, it can fallbacks to interpreted implementation. In tests, we can use a SQL config
 * `SQLConf.CODEGEN_FACTORY_MODE` to control fallback behavior.
 */
```

`FileStreamSource.scala`
```
    fs.makeQualified(new Path(path))  // can contains glob patterns
```

`UnsupportedOperationSuites.scala`
```
   * exception simply for not being a streaming plan, even though that plan could exists as batch
```

`CreateHiveTableAsSelectCommand`
```
 * @param tableDesc the Table Describe, which may contains serde, storage handler etc.
```

`SQLMetrics.scala`
```
    // The final result of this metric in physical operator UI may looks like:
```

`KafkaDataConsumer.scala`
```
    // which may causes a NonLocalReturnControl exception when this method is used as a function.
```

`UnsafeSorterSpillMerger.java`
```
      // does not return wrong result because hasNext will returns true
```

`ProgressReporter.scala`
```
      // even multiple times) points and considering it twice will leads to double counting. We
```

`DecimalPrecision.scala`
```
        // which is out of range and therefore it will becomes DECIMAL(38, 7), leading to
```

`SQLTestUtils.scala`
```
   * ConsoleAppender's `follow` should be set to `true` so that it will honors reassignments of
```

`HiveQuerySuite.scala`
```
  // We assume that the Broadcast Join Threshold will works since the src is a small table
```

**Comment by deshanxiao** [comment]
It's ok. Thank you for your suggestions!

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by HyukjinKwon** [comment]
@kiszk, I would appreciate if you feel free to open a PR fixing them, or suggest them in someone's PR fixing them.

**Comment by kiszk** [comment]
@HyukjinKwon sure, I will open a PR.

**Pull request closed without merging**
