### PR TITLE
[SPARK-13124] [Web UI] Fixed CSS and JS issues caused by addition of JQuery DataTables

### PR DESCRIPTION
**Pull request by ajbozarth**
Made sure the old tables continue to use the old css and the new DataTables use the new css. Also fixed it so the Safari Web Inspector doesn't throw errors when on the new DataTables pages.

### CODE REVIEW

**Comment by ajbozarth** [comment]
For reference here's what the issues look like, I returned them to their original look
css_issue
js_issue

**Comment by ajbozarth** [comment]
retest this please

**Comment by ajbozarth** [comment]
@zhuoliu want to take a look since you added the DataTables

**Comment by zhuoliu** [comment]
Tested also for history page. Looks good to me.

**Comment by holdenk** [comment]
So looking at the code we can't mix and match the old style and new style tables on the same page correct?

**Comment by ajbozarth** [comment]
@holdenk not without changing a large amount of css or html. Both styles use common table classes in their basic css. This does seem to be one way though, only the old tables are affected when both css files are available, so we could potentially edit the old tables css to force use of the old style if we want to mix and match on the same page on a case by case basis.

**Comment by ajbozarth** [comment]
@tgravescs since you did a lot of review on the DataTables addition do you want to take a look at this?

**Comment by tgravescs** [comment]
Can you clarify when you see the exception with inspecting element?

Which browser and plugin, etc?  

When I inspect it with firefox I don't see any errors

**Comment by ajbozarth** [comment]
Last I checked I was seeing it on Safari, Firefox and Chrome, no plug-ins. I'll build master and spin up a Web UI and double check right now though.

**Comment by tgravescs** [comment]
Ok, I'll try it again on clean apache build also.

**Comment by ajbozarth** [comment]
Ok so I'm only seeing it in Safari now, and I did a couple searches based on only seeing it in Safari and I found a better fix, I'll push the change shortly

**Comment by ajbozarth** [comment]
It seems that when a expected map file is missing Firefox and Chrome just ignore it, Safari on the other hand throws a 404 error. Given the map file doesn't exist to begin with it makes more sense to remove the reference to it than add the map file.

**Comment by tgravescs** [comment]
+1

**Pull request closed without merging**
