### PR TITLE
[SPARK-19550][DOC][FOLLOW-UP] Update tuning.md to use JDK8

### PR DESCRIPTION
**Pull request by wangyum**
## What changes were proposed in this pull request?

Update `tuning.md` and `rdd-programming-guide.md` to use JDK8.

## How was this patch tested?

manual tests

### CODE REVIEW

**Comment by wangyum** [comment]
cc @srowen

**Comment by srowen** [comment]
Are these all the references to Java 7 docs?
Also, does the advice need a bit of updating since we require Java 8? around GC?

**Comment by wangyum** [comment]
Some references to Java 7, Some references to Java 6.

**Review by srowen — APPROVED** [review]
I was wondering if there were more references to old JDK docs, but I don't see them. I skimmed the GC advice and it still seems consistent with Java 8.

**Comment by wangyum** [comment]
Yes. I can't find more references to the old JDK docs also.

**Review by felixcheung — COMMENTED** [review]
LG but this seems like would be easy to forget to update when we move to newer JDK and not supporting 8 at some point?

**Comment by srowen** [comment]
Yeah, there's no 'latest' link though. The JDK is pretty stable so a link to Java 8 when we're on Java 9 isn't going to be an issue.

**Comment by srowen** [comment]
Merged to master/2.4

**Pull request closed without merging**
