### PR TITLE
[SPARK-31255][SQL][FOLLOWUP] Add missing license headers.

### PR DESCRIPTION
**Pull request by rdblue**
### What changes were proposed in this pull request?

Add missing license headers for new files added in #28027.

### Why are the changes needed?

To fix licenses.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

This is a purely non-functional change.

### CODE REVIEW

**Comment by rdblue** [comment]
@HeartSaVioR, @sunchao, here's a fix.

**Review by sunchao — APPROVED** [review]
thanks @rdblue !

**Review by HeartSaVioR — APPROVED** [review]
+1

This only adds license headers, and I checked #28027 and confirmed these two files are only added.

**Review by HyukjinKwon — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]

**Review by dongjoon-hyun — COMMENTED** [review]
I made a PR to fix the root cause.
- https://github.com/apache/spark/pull/30418

**Comment by dongjoon-hyun** [comment]
Thank you, @rdblue and all.
Merged to master.

**Pull request closed without merging**
