### PR TITLE
[SPARK-37840][SQL] Dynamic Update of UDF

### PR DESCRIPTION
**Pull request by iRakson**
### What changes were proposed in this pull request?
Currently, If we need to change definitions of our UDFs, we need to restart ongoing session.  And register our UDFs again.
Restarting session in production environment is not always feasible.

In this PR, i propose to update our UDFs dynamically.
To achieve this, user can update their UDFs using `CREATE OR REPLACE` command
For e.g:
1. Create a new function
`CREATE TEMPORARY FUNCTION func AS c1 USING JAR jar1;`

2. Once associated jar files are updated, enable dynamic update config and fire following command
`CREATE OR REPLACE TEMPORARY FUNCTION func AS c1 USING JAR jar1;`

Above query will update the classloaders and users will be able to use updated jars.
We can update both permanent and temporary functions.

[Design Doc](https://docs.google.com/document/d/1XktLthq8FkjzgSMDMzmCm8JuNdhk9j5NQlFox-DVz90/edit?usp=sharing)
A new configuration is added for this PR : `spark.sql.function.updateUdfResources`

### Why are the changes needed?
We need to start our thriftserver whenever we want to update our UDF definition. This is not always possible in production environment. These changes will allow users to update them dynamically.

### Does this PR introduce _any_ user-facing change?
Yes,
Now users can update their UDFs without restarting thriftserver using CREATE OR REPLACE FUNCTION command, if dynamic update is turned on.

### How was this patch tested?
Unit Tests added.
More tests will be added for testing other scenarios.

### CODE REVIEW

**Comment by melin** [comment]
Support Permanent Function?

**Comment by Yikf** [comment]
> Support Permanent Function?

The information from suite describe that permanent should be supportive

**Comment by melin** [comment]
Update jar by CREATE OR REPLACE command, it is not very convenient, it is best to insist on jar file modification time update, take effect directly

**Comment by iRakson** [comment]
@HyukjinKwon @dongjoon-hyun
Kindly take a look at this PR. 
UT failure is not related to changes made in this PR.
More UTs will be added covering all other scenarios.

**Comment by melin** [comment]
If there are many functions defined in a JAR file, do they all need to be updated?

**Comment by iRakson** [comment]
> If there are many functions defined in a JAR file, do they all need to be updated?

No.

**Comment by iRakson** [comment]
gentle ping @cloud-fan @wangyum

**Comment by cloud-fan** [comment]
The major change here is in core. cc @jiangxb1987 @Ngone51

**Comment by iRakson** [comment]
@dongjoon-hyun @HyukjinKwon @cloud-fan  Does this feature looks promising enough for community? If Yes, I will add few more UTs for testing other scenarios.

**Comment by iRakson** [comment]
@cloud-fan @Ngone51 @jiangxb1987 If you have some spare time, Kindly take a look at this PR.

**Comment by cutiechi** [comment]
There are two problems with the current test:
1. The classes in the jar package configured by spark.jars cannot be loaded correctly
2. When I modify the udf in the jar package of the same name, the classes in the driver cannot be updated correctly
@iRakson

**Comment by iRakson** [comment]
cc @viirya @sunchao
Kindly take a look at this PR.

**Comment by iRakson** [comment]
@Ngone51 @yaooqinn @beliefer @AngersZhuuuu 
Kindly take a look at this in your free time. I believe this will be very useful for end users.

**Comment by iRakson** [comment]
Yes, users needs to take care of this situation. We can explicitly mention it.

**Comment by iRakson** [comment]
also cc @wzhfy

**Pull request closed without merging**
