### PR TITLE
[SPARK-15460] [SQL] Issue Exceptions from Thrift Server and Spark-SQL Cli when Users Inputting hive.metastore.warehouse.dir

### PR DESCRIPTION
**Pull request by gatorsmile**
#### What changes were proposed in this pull request?

~~Although overriding `hive.metastore.warehouse.dir` in the spark-sql cli, the metastore warehouse directory still uses the default value of `spark.sql.warehouse.dir`. This is a regression. It works in the previous release.~~

Multiple test suites are still using `hive.metastore.warehouse.dir` as the input parameters to the Thrift Server or Spark-SQL Cli. Before this PR, this parameter is simply ignored without any message. However, these parameters took effect to change the default location of database in warehouse until Spark 2.0.0. 

To ensure users correctly use the new parameter, this PR is to issue an exception if users specify the parm: `hive.metastore.warehouse.dir` in Thrift-Server and Spark SQL CLI:

```
Exception in thread "main" java.lang.Error: hive.metastore.warehouse.dir is deprecated. Instead, use spark.sql.warehouse.dir to specify the default location of database.
```
#### How was this patch tested?

Manual testing and also added a test in `CliSuite`

### CODE REVIEW

**Comment by gatorsmile** [comment]
@yhuai @andrewor14 @rxin @liancheng 
**Question**: This PR is to set `spark.sql.warehouse.dir` by using the user-specified value of `hive.metastore.warehouse.dir` in CLI command line. 

Another option is to issue an exception and force users to use `spark.sql.warehouse.dir`. 

Let me know which one is preferrable. Thanks!

**Comment by gatorsmile** [comment]
In the PR https://github.com/apache/spark/pull/12812, we mention we will not use `hive.metastore.warehouse.dir` to set the location. Thus, I think we should issue an exception if users try to set it in the CLI parameter? or just issue a warning LOG message?

**Comment by yhuai** [comment]
@gatorsmile For 2.0, we will use `spark.sql.warehouse.dir` instead of using `hive.metastore.warehouse.dir` (the support of this has been dropped).

**Comment by gatorsmile** [comment]
Thanks! The major reason is the existing users could still follow the previous behaviors. They assume we will accept such inputs. 

I will change the implementation. If users do it, we will issue an exception to tell users the support is dropped.

**Comment by gatorsmile** [comment]
@yhuai This PR has been changed based on your comment. We issue exceptions when users use `--hiveconf hive.metastore.warehouse.dir=/x/y/z` in Spark-SQL CLI or Thrift Server. Thanks!

**Comment by gatorsmile** [comment]
cc @yhuai The code is ready for review. Thanks!

**Pull request closed without merging**
