### PR TITLE
Backport SPARK-17599 and SPARK-17569 to Spark 2.0 branch

### PR DESCRIPTION
**Pull request by brkyvz**
## What changes were proposed in this pull request?

This Backports PR #15153 and PR #15122 to Spark 2.0 branch for Structured Streaming.
It is structured a bit differently because similar code paths already existed in the 2.0 branch. The unit test makes sure that both behaviors don't break.

### CODE REVIEW

**Comment by brkyvz** [comment]
@zsxwing and @cloud-fan

**Comment by rxin** [comment]
Please separate these as two pull requests.

**Comment by brkyvz** [comment]
@rxin The only change that was needed was:
https://github.com/apache/spark/pull/15202/files#diff-e82a44dc550d2a0a92e44d1ec2ecabccR137
Which was equivalent to the two master branch changes

**Comment by zsxwing** [comment]
@rxin this one just added the unit test of #15153 into branch 2.0 +  #15122. Do you still insist on separating them?

**Comment by rxin** [comment]
OK that's fine. Merging in. Thanks.

**Comment by rxin** [comment]
@brkyvz  can you close this now?

**Comment by brkyvz** [comment]
Thanks @rxin

**Pull request closed without merging**
