### PR TITLE
[SPARK-36050][SQL] Spark doesn’t support reading/writing TIMESTAMP_NTZ with ORC

### PR DESCRIPTION
**Pull request by gengliangwang**
### What changes were proposed in this pull request?

The [OrcTimestamp](https://github.com/apache/orc/blob/main/java/mapreduce/src/java/org/apache/orc/mapred/OrcTimestamp.java) of MapReduce library is instant of java.sql.Timestamp. As it is the only support Timestamp type of ORC, Spark doesn’t support reading/writing TIMESTAMP_NTZ with ORC.

This PR is to fail the read/write early on analysis phase with the error message `ORC data source does not support timestamp_ntz data type`

### Why are the changes needed?

Better error message.

### Does this PR introduce _any_ user-facing change?

No
### How was this patch tested?

Unit test

### CODE REVIEW

**Review by MaxGekk — COMMENTED** [review]
ORC format supports both timestamps w/o and w/ tz. See https://orc.apache.org/docs/types.html#timestamps :

- Timestamp is a date and time without a time zone, which does not change based on the time zone of the reader.
- Timestamp with local time zone is a fixed instant in time, which does change based on the time zone of the reader.

I think we can support save/load of timestamp_ntz and timestamp_ltz. Or do you propose just disallow save/load of timestamp_ntz for some time till proper support?

**Comment by gengliangwang** [comment]
@MaxGekk Yes ORC declares that it supports Timestamp without time zone in the link you mentioned.
But for the MapReduce library: 
https://orc.apache.org/docs/mapred.html
https://github.com/apache/orc/blob/main/java/mapreduce/src/java/org/apache/orc/mapred/OrcTimestamp.java

I can't find any support for that.

**Comment by gengliangwang** [comment]
> Or do you propose just disallow save/load of timestamp_ntz for some time till proper support?

If the ORC MapReduce lib supports it, we can support it in Spark.

**Comment by gengliangwang** [comment]
Also cc @dongjoon-hyun for this one (though he is on vacation).

**Comment by MaxGekk** [comment]
Here is the code from OrcMapredRecordWriter.java of orc-mapreduce-1.6.9:
```java
        case TIMESTAMP:
        case TIMESTAMP_INSTANT:
          ((TimestampColumnVector) vector).set(row, (OrcTimestamp) value);
          break;
```
So, you should use the same type `OrcTimestamp` for both ntz and ltz. Need to just set proper type `TIMESTAMP_INSTANT` or `TIMESTAMP`.

**Comment by gengliangwang** [comment]
@MaxGekk Thanks for the suggestions! Closing this one.

**Pull request closed without merging**
