### PR TITLE
[SPARK-14990][SQL] Fix checkForSameTypeInputExpr (ignore nullability)

### PR DESCRIPTION
**Pull request by rxin**
## What changes were proposed in this pull request?

This patch fixes a bug in TypeUtils.checkForSameTypeInputExpr. Previously the code was testing on strict equality, which does not taking nullability into account.

This is based on https://github.com/apache/spark/pull/12768. This patch fixed a bug there (with empty expression) and added a test case.
## How was this patch tested?

Added a new test suite and test case.

Closes #12768.

### CODE REVIEW

**Comment by rxin** [comment]
cc @dosoft

**Comment by rxin** [comment]
cc @yhuai for review

**Comment by cloud-fan** [comment]
LGTM

**Comment by rxin** [comment]
Merging in master/2.0.

**Pull request closed without merging**
