### PR TITLE
[SPARK-45082][DOC] Review and fix issues in API docs for 3.5.0

### PR DESCRIPTION
**Pull request by xuanyuanking**
### What changes were proposed in this pull request?

Compare the 3.4 API doc with the 3.5 RC3 cut. Fix the following issues:

- Remove the leaking class/object in API doc

### Why are the changes needed?
Fix the issues in the Spark 3.5.0 release API docs.

### Does this PR introduce _any_ user-facing change?
No, API doc changes only.

### How was this patch tested?
Manually test.

### Was this patch authored or co-authored using generative AI tooling?
no

### CODE REVIEW

**Comment by srowen** [comment]
Seems OK in principle, just need tests to pass

**Comment by xuanyuanking** [comment]
The test `On pull request update / Notify test workflow (pull_request_target)` that failed has passed for the initial commit. I think it's good to go. @srowen, could you give your approval? I aim to include this in the 3.5 RC4 cut.

**Comment by srowen** [comment]
I'm concerned that this may not pass mima tests and I don't see that this test was run because of other errors. Have you checked that it passes in both branches?

**Comment by xuanyuanking** [comment]
good point, let me run Mima test manually on both master and 3.5

**Comment by xuanyuanking** [comment]
@srowen Checked manually for both master and branch-3.5, the Mima test passed.

**Review by srowen — APPROVED** [review]

**Comment by xuanyuanking** [comment]
Thanks, merged in master and branch-3.5

**Pull request closed without merging**
