### PR TITLE
[SPARK-30689][CORE][YARN]Add resource discovery plugin api to support YARN versions with resource scheduling

### PR DESCRIPTION
**Pull request by tgravescs**
### What changes were proposed in this pull request?

This change is to allow custom resource scheduler (GPUs,FPGAs,etc) resource discovery to be more flexible. Users are asking for it to work with hadoop 2.x versions that do not support resource scheduling in YARN and/or also they may not run in an isolated environment.
This change creates a plugin api that users can write their own resource discovery class that allows a lot more flexibility. The user can chain plugins for different resource types. The user specified plugins execute in the order specified and will fall back to use the discovery script plugin if they don't return information for a particular resource.

I had to open up a few of the classes to be public and change them to not be case classes and make them developer api in order for the the plugin to get enough information it needs.

I also relaxed the yarn side so that if yarn isn't configured for resource scheduling we just warn and go on. This helps users that have yarn 3.1 but haven't configured the resource scheduling side on their cluster yet, or aren't running in isolated environment.

The user would configured this like:
--conf spark.resources.discovery.plugin="org.apache.spark.resource.ResourceDiscoveryFPGAPlugin, org.apache.spark.resource.ResourceDiscoveryGPUPlugin"

Note the executor side had to be wrapped with a classloader to make sure we include the user classpath for jars they specified on submission.

Note this is more flexible because the discovery script has limitations such as spawning it in a separate process. This means if you are trying to allocate resources in that process they might be released when the script returns. Other things are the class makes it more flexible to be able to integrate with existing systems and solutions for assigning resources.

### Why are the changes needed?

to more easily use spark resource scheduling with older versions of hadoop or in non-isolated enivronments.

### Does this PR introduce any user-facing change?

Yes a plugin api

### How was this patch tested?

Unit tests added and manual testing done on yarn and standalone modes.

### CODE REVIEW

**Comment by tgravescs** [comment]
@jiangxb1987

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by revans2** [comment]
Looking at the code I am a little confused about how to use this. Especially if there are multiple resources involved each might want custom code and be vendor specific.

As such I really would like to see one of two things happen.  Either have the core of `ResourceDiscoveryScriptPlugin.discoverResource` be a static method that other plugins can call so they don't have to rewrite the discovery script logic, or change the config/API so that `discoverResource` returns an `Optional[ResourceInformation]`. Then have a list of plugins with the `ResourceDiscoveryScriptPlugin` being a final one that you cannot turn off, and will always return a resource.  This way one vendor can write a GPU specific plugin, and another vendor can write an FPGA specific one, and there would be no contention or overlap between them, and none of them would have to know about the other or the scripting.

**Comment by tgravescs** [comment]
that is a good idea, I'll make it so they can be changed so more easily let different vendor or different plugins work together with the default always be discovery script

**Comment by tgravescs** [comment]
test failures aren't related to my change, seems the yarn minicluster is failing to find classes.

**Comment by tgravescs** [comment]
test this please

**Review by revans2 — APPROVED** [review]
+1 looks good to me

**Comment by tgravescs** [comment]
same weird test failures like it can't find classes.  I'm not sure what is causing these failures, they run fine for me locally and aren't in classes I changed.

**Comment by tgravescs** [comment]
test this please

**Comment by tgravescs** [comment]
I'm running locally with exact same args (including java11), @dongjoon-hyun  have you noticed consistent failures with this on java11 side?  The errors appears it just can't find yarn classes and even one was a spark class itself.

**Comment by tgravescs** [comment]
test this please

**Comment by dongjoon-hyun** [comment]
JDK11 has been healthy until today. I didn't hit any consistent failure. I'll monitor Jenkins more. Today, we landed many patches.

**Comment by dongjoon-hyun** [comment]
The Python failure seems to be some flakiness.

**Comment by dongjoon-hyun** [comment]
I created a testing PR for investigating independently.
- https://github.com/apache/spark/pull/27424

**Comment by dongjoon-hyun** [comment]
The Python failure was a known issue and the flakiness doesn't occur sequentially in JDK11 environment (according to my test, https://github.com/apache/spark/pull/27424)
- https://issues.apache.org/jira/browse/SPARK-29138

I believe we can ignore that.

**Pull request closed without merging**
