### PR TITLE
[SPARK-31010][SQL][FOLLOW-UP] Give an example for typed Scala UDF in error message

### PR DESCRIPTION
**Pull request by Ngone51**
### What changes were proposed in this pull request?

In the error message, adding an example for typed Scala UDF.

### Why are the changes needed?

Help user to know how to migrate to typed Scala UDF.

### Does this PR introduce any user-facing change?

No, it's a new error message in Spark 3.0.

### How was this patch tested?

Pass Jenkins.

### CODE REVIEW

**Comment by Ngone51** [comment]
cc @gatorsmile @cloud-fan

**Review by maropu — APPROVED** [review]

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
I am going to just merge. build and linters passed.

**Comment by HyukjinKwon** [comment]
Merged to master and branch-3.0.

**Comment by Ngone51** [comment]
thanks all!

**Pull request closed without merging**
