### PR TITLE
[SPARK-26884][CORE] Let task acquire memory accurately when using spilled memory

### PR DESCRIPTION
**Pull request by SongYadong**
## What changes were proposed in this pull request?

When task can't get required execution memory, it will call `spill()` of consumers to release more memory. After spilling, it tries again to acquire memory needed which is `(required - got)`. That's not accurate as actually `released `memory by spilling may not equal to size it try to spill. 
So it may be better to acquire memory in more accurate size :
- when released >= needed, acquire needed size. (`required - got`)
- when released < needed, acquire `released `size.

## How was this patch tested?
Existed unit tests.

### CODE REVIEW

**Comment by liupc** [comment]
I think we acquire the amount of memory it needed no mater whether can be satisfied is what we need here, because the memory manager will give the right amount. your change seems does not improve this, but make the behavior change if my understand is correct.

**Comment by SongYadong** [comment]
Thanks for review. It's right the memory manager will try to give the right amount. But when going to spill action, that is to say memory manager probably can't give needed memory now. If we acquire unsatisfied amount after spilling ( when `released` < `required - got`), memory manager will try redundant effort to get memory, even be blocked temporarily. By accurate control, I think acquiring memory may return fast.

**Comment by jiangxb1987** [comment]
Please note that we want to let each task get at least 1 / (2 * numActiveTasks) of the total memory pool, if we can't offer that much then we INTENTIONALLY wait for other tasks to free up more memories. Thus, I'm not sure the change proposed by this PR is the direction we want to follow.

**Comment by liupc** [comment]
+1for @jiangxb1987

**Comment by SongYadong** [comment]
Thanks for reminding me. @jiangxb1987  @liupc 
Before spill, we have called `acquireExecutionMemory `in which task already got at least `1 / (2 * numActiveTasks)` of total memory pool. But `numActiveTasks `may have changed when calling `acquireExecutionMemory `again after spill. That's my mistake. 
If task havn't got `1 / (2 * numActiveTasks)` of total memory pool, the change in this PR will in some cases result in more spill instead of waiting for other tasks to free up more memory. This result may lead to direction we don't want. And spill is more expensive generally.
I will close this PR later.

**Pull request closed without merging**
