### PR TITLE
[SPARK-11577][SQL] Handle code review comments for SPARK-11188

### PR DESCRIPTION
**Pull request by dilipbiswal**
Handle the code review comments from Michael for SPARK-11188

### CODE REVIEW

**Comment by dilipbiswal** [comment]
@marmbrus Hi Michael, please take a look when you get a chance. Thanks a lot.

**Comment by rxin** [comment]
How does this change suppress stack traces?

**Comment by dilipbiswal** [comment]
@rxin Thanks for looking at the changes. Actually SPARK-11188 is where the actual fix to suppress the stack traces was put in. However michael had already merged in the changes into 1.5.2 before the code review comments were handled. Since that JIRA was resolved , michael had advised to open a new JIRA to handle the code review comments to fix up the code style issues.

**Comment by rxin** [comment]
I don't think he meant creating a new JIRA ticket for addressing comments. Please just use the same one in the future. If you do want to use a different one, please at least update the title accordingly (e.g. in this case it should say "address comments for ...")

**Comment by dilipbiswal** [comment]
@rxin Hi Reynold.. sure.. Let me update the title for now. I will use the same JIRA in the future. Very sorry if i misunderstood his comments.

**Comment by dilipbiswal** [comment]
@marmbrus Hi Michael, Sean advised to close 11577 and link this PR to the original 11188 in 

[sean's comment] (https://issues.apache.org/jira/browse/SPARK-11577?focusedCommentId=14995860&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14995860)

. Should i go ahead and do that ? Can there be PRs against an already resolved JIRA ? Please advice ..

**Comment by rxin** [comment]
This has been merged already.

**Comment by dilipbiswal** [comment]
@rxin Thanks a **LOT**. Reynold, the JIRA status shows "In Progress".Normally i have seen the status change after the merge. What should i do here ?

**Comment by rxin** [comment]
I closed your ticket just now.

**Comment by rxin** [comment]
Please also close this pull request. Since it was not merged into master, this pull request won't be closed automatically.

**Comment by dilipbiswal** [comment]
@rxin **Thanks**. Closing the PR now.

**Pull request closed without merging**
