### PR TITLE
[SPARK-36441][INFRA] Fix GA failure related to downloading lintr dependencies

### PR DESCRIPTION
**Pull request by sarutak**
### What changes were proposed in this pull request?

This PR fixes a GA failure which is related to downloading lintr dependencies.
```
 * installing *source* package ‘devtools’ ...
** package ‘devtools’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (devtools)

The downloaded source packages are in
	‘/tmp/Rtmpv53Ix4/downloaded_packages’
Using bundled GitHub PAT. Please add your own PAT to the env var `GITHUB_PAT`
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 401.
  Bad credentials
```

I re-triggered the GA job but it still fail with the same error.
https://github.com/apache/spark/runs/3257853825

The issue seems to happen when downloading lintr dependencies from GitHub. So, the solution is to change the way to download them.

### Why are the changes needed?

To recover GA.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

GA itself.

### CODE REVIEW

**Comment by sarutak** [comment]
Trying to change the way to download lintr.
Waiting the result.

**Comment by sarutak** [comment]
The issue seems resolved.
https://github.com/sarutak/spark/runs/3258113139?check_suite_focus=true#step:9:697

**Comment by sarutak** [comment]
cc: @dongjoon-hyun @HyukjinKwon

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master, branch-3.2, branch-3.1 and branch-3.0.

**Comment by viirya** [comment]
lgtm, thanks for the fix.

**Comment by dongjoon-hyun** [comment]
+1, LGTM

**Pull request closed without merging**
