### PR TITLE
[SPARK-26066][SQL] Move truncatedString to sql/catalyst and add spark.sql.debug.maxToStringFields conf

### PR DESCRIPTION
**Pull request by MaxGekk**
## What changes were proposed in this pull request?

In the PR, I propose:
- new SQL config `spark.sql.debug.maxToStringFields` to control maximum number fields up to which `truncatedString` cuts its input sequences.
- Moving `truncatedString` out of `core` to `sql/catalyst` because it is used only in the `sql/catalyst` packages for restricting number of fields converted to strings from `TreeNode` and expressions of`StructType`.

## How was this patch tested?

Added a test to `QueryExecutionSuite` to check that `spark.sql.debug.maxToStringFields` impacts to behavior of `truncatedString`.

### CODE REVIEW

**Comment by MaxGekk** [comment]
The PR extracts a part of changes from #22429

**Comment by MaxGekk** [comment]
@hvanhovell @gatorsmile @HyukjinKwon @cloud-fan Could you take a look at this PR, please.

**Comment by dongjoon-hyun** [comment]
@MaxGekk . One PR should have one theme with a proper title. We frequently search by commit title. Please don't split this PR into two sub PRs.

**Comment by MaxGekk** [comment]
> let's fix PR description and title for that.
> One PR should have one theme with a proper title. 

@HyukjinKwon @dongjoon-hyun I have renamed this PR. Is new title fine for you?

> We frequently search by commit title. Please don't split this PR into two sub PRs.

Sure, I will not.

**Comment by dongjoon-hyun** [comment]
How about the following?
```
Move `truncatedString` to `sql/catalyst` and add `spark.sql.debug.maxToStringFields` conf
```

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by MaxGekk** [comment]
@gatorsmile @hvanhovell Could you look at the PR, please. I extracted a piece of changes from #22429.

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
There are two failures, but it seems to be irrelevant to this PR.
```
Test Result (2 failures / +2)
org.apache.spark.repl.SingletonReplSuite.(It is not a test it is a sbt.testing.SuiteSelector)
org.apache.spark.sql.streaming.continuous.ContinuousSuite.query without test harness
```

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by dongjoon-hyun** [comment]
Merged to master. Thank you, @MaxGekk and @HyukjinKwon , @kiszk .

**Pull request closed without merging**
