### PR TITLE
[SPARK-20920][SQL] ForkJoinPool pools are leaked when writing hive tables with many partitions

### PR DESCRIPTION
**Pull request by srowen**
## What changes were proposed in this pull request?

Don't leave thread pool running from AlterTableRecoverPartitionsCommand DDL command

## How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by srowen** [comment]
@davies could you help me review as you wrote the original code?
CC @viirya because it's similar to https://github.com/apache/spark/pull/18100

**Comment by viirya** [comment]
The change looks good. Shall we add a test for it?

**Comment by viirya** [comment]
Ah, I remember that it is a bit hard to automatically test it.

**Comment by cloud-fan** [comment]
LGTM, can we add a manual test like #18100 ?

**Comment by srowen** [comment]
@viirya / @cloud-fan what do you mean here by a manual test?

**Comment by viirya** [comment]
@srowen In #18073, I ran the code snippet which can leak the pools, and checked the number of threads before/after the fix by using some tools like jconsole.

**Comment by srowen** [comment]
OK, I tried this as a test:

```
import scala.collection.JavaConverters._

spark.sql("DROP TABLE IF EXISTS my_tab")
spark.sql("CREATE TABLE my_tab(a INT, b STRING, c INT, d String) USING parquet PARTITIONED BY (a, b, c)")
spark.sql("INSERT INTO TABLE my_tab VALUES (1, 'foo', 4, 'bing')")
spark.sql("INSERT INTO TABLE my_tab VALUES (2, 'bar', 5, 'bing')")
spark.sql("INSERT INTO TABLE my_tab VALUES (3, 'baz', 6, 'bing')")

Thread.getAllStackTraces.keySet().asScala.map(_.getName).filter(_.contains("ForkJoinPool"))

res5: scala.collection.mutable.Set[String] = Set(ForkJoinPool-1-worker-13)

spark.sql("ALTER TABLE my_tab RECOVER PARTITIONS")

Thread.getAllStackTraces.keySet().asScala.map(_.getName).filter(_.contains("ForkJoinPool"))

res10: scala.collection.mutable.Set[String] = Set(ForkJoinPool-1-worker-13, ForkJoinPool-1-worker-9, ForkJoinPool-2-worker-13)

spark.sql("ALTER TABLE my_tab RECOVER PARTITIONS")
spark.sql("ALTER TABLE my_tab RECOVER PARTITIONS")
spark.sql("ALTER TABLE my_tab RECOVER PARTITIONS")

res23: scala.collection.mutable.Set[String] = Set(ForkJoinPool-5-worker-13, ForkJoinPool-3-worker-13, ForkJoinPool-2-worker-13, ForkJoinPool-1-worker-11, ForkJoinPool-4-worker-13, ForkJoinPool-1-worker-3)
```

Before the change you can see that it does look like one thread is left from each of several ForkJoinPools.

After the change, the result is `Set(ForkJoinPool-1-worker-13)` every time. I think that does suggest this fixes the issue.

**Comment by viirya** [comment]
Thanks @srowen. I think it looks good.

**Comment by srowen** [comment]
Merged to master/2.2/2.1

**Pull request closed without merging**
