### PR TITLE
SPARK-4746 make it easy to skip IntegrationTests

### PR DESCRIPTION
**Pull request by squito**
- create an `IntegrationTest` tag
- label all tests in core as an `IntegrationTest` if they use a `local-cluster`
- make a `unit` profile in sbt so its easy to skip all the unit tests in local development.

On my laptop, this means that I can run `~unit:test-quick` in my sbt console, which takes ~5 mins on the first run.  But using `test-quick` means that as I make changes, it only re-runs the tests I've effected.  so generally I can update on all tests in a second or two.

Of course this means its skipping a bunch of important tests, but hopefully this is a useful subset of tests that can actually be run locally.  If you don't skip the IntegrationTests, its totally impractical to ever get through even the first run of `test-quick` on my laptop.

An added bonus is that this set of tests can be run without having to ever do the `mvn package` step, since we are never launching a full cluster as an external process.

I also through in an `Active` tag for tests as well -- I find this really useful when developing.  Eg. when I only wanted to run one test in `PairRDDFunctionsSuite`, my dev loop was 7 seconds instead of 30 seconds.

### CODE REVIEW

**Comment by vanzin** [comment]
Hey Imran, haven't looked at the code, but `YarnClusterSuite` could probably use this tag too.

**Comment by squito** [comment]
oh good point Marcelo -- I forgot to add that I've only done this for `core` in this PR.  I wanted to ask others whether its worthwhile to do in other projects or not before I go digging into each one of them.

**Comment by vanzin** [comment]
IIRC there are a few tests under `sql/` that use local-cluster too, but can't name any from the top of my head.

**Comment by pwendell** [comment]
Just curious - what is the before and after time? I.e. what fraction of time does this cut down on?

**Comment by srowen** [comment]
This is not a terribly useful observation, but, this is what `surefire` vs `failsafe` is for in the Maven world, without making a custom mechanism. But we have the SBT build too.

**Comment by squito** [comment]
@pwendell To be honest I'd never had the patience to run all the tests before on my laptop.  But I just tried them both again: 237 seconds vs. 852 seconds (just for core), so these tests are down to ~25% of the total time.  It makes using `test-quick` a reality, while I have no end of complaints about sbt, I really like `test-quick`.

@vanzin yeah there are also a bunch of tests in other projects, I know there are a bunch in mllib as well.  (I guess this is really a WIP at this point, wanted to see if I folks like the idea before I do it in other projects.)

@srowen I wasn't familiar with `surefire` or `failsafe` from maven, but I figured there was some other way to just support an integration test separation.  I am just more familiar with tagging tests, and I think it buys us some more flexibility.  I'll see if I can figure out how to setup a maven task (or whatever its called) to only run the unit tests, but I know very little about maven ...

**Comment by squito** [comment]
Jenkins, retest this please

**Comment by squito** [comment]
so, this doesn't actually work quite the way I wanted it to.  It turns out its skipping all the Junit tests as well.  The junit tests are run if you run with `test-only * -- -l`, but as sound as you add a tag like `test-only * -- -l foo`, then all the junit tests are skipped.  From the [junit-interface docs](https://github.com/sbt/junit-interface) "Any parameter not starting with - or + is treated as a glob pattern for matching tests."

I will look into a solution for this, but I have a feeling this might mean we can't mix junit w/ the tagging approach, and we have to go to a more standard directory / filenaming approach to separating out integration tests.

**Comment by pwendell** [comment]
@squito another thing is that we should look at whether these tests really need to be integration style tests or not. I've seen people often use `local-cluster` because it's easier to write as an integration test, even if they just put more effort in they could write a proper unit test.

Alternatively we could try and see if we can run these `local-cluster` tests more quickly in general. I don't think anyone has tried to optimize the execution time of that test path much.

In an ideal world the vast majority of our tests would actually be unit tests - i.e. they would run in milliseconds, so that we can have thousands of tests and have them run in a reasonable amount of time.

**Comment by squito** [comment]
@pwendell I like the idea of just getting tests to run faster in general, but I think its gonna be hard to make that happen.  (Not the most exciting tasks for beginners and I think the experienced folks have their hands full ...)  This was meant to be an "easy" way to have some useful subset of tests that developers can run locally.  Its great that we have jenkins running tests automatically, but I'd really like to improve the local development process.

Even if we do speed up the other tests, I think there are always going to be some tests that fall into this bucket that we'd like to run, so I think this will still be useful.  But I agree that we the tests could be sped up a lot -- I made some notes on the JIRA about how even after this, eliminating (or speeding up) a small number of tests would have huge gains.

**Comment by pwendell** [comment]
@squito yeah for sure, I think it's nice to have some set of integration tests that are flagged as such. I was just suggesting other ways we can improve our tests as well.

I wouldn't give up so easily on making `local-cluster` faster though... I don't think anyone has looked into optimizing it recently, and it's a common mechanism used by all tests, so if we improve the launch time then it will speed things up across the board. Also, there are other efforts around test parallelization that are ongoing which will speed up the runtime.

**Comment by squito** [comment]
I figured out the magic combination to make sbt, scalatest, junit, and the sbt-pom-reader all play nicely together.  I had to introduce a new config (or scope or something, sbt terminology still baffles me ...) instead of creating a new task.  Now you can run `unit:test` (or any other variant you like, eg `~unit:testQuick`) which will exclude everything tagged as an IntegrationTest.  There is both a tag for scalatests, and a category for junit tests.

I've still only bothered with the tagging in core.  But I think this can be merged as is in any case -- this does the setup so someone more familiar w/ the other projects can figure out what to tag.

**Comment by squito** [comment]
ping

Are others ambivalent about this, eg. maybe because of the complexity it introduces to the build?  If there isn't any more interest in this I'll just close it in a couple days.

**Pull request closed without merging**
