### PR TITLE
[SPARK-28424][TESTS][FOLLOW-UP] Add test cases for all interval units

### PR DESCRIPTION
**Pull request by xuanyuanking**
### What changes were proposed in this pull request?
Add test cases covering all interval units:  MICROSECOND MILLISECOND SECOND MINUTE HOUR DAY WEEK MONTH YEAR

### Why are the changes needed?
For test coverage.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Test only.

### CODE REVIEW

**Comment by xuanyuanking** [comment]
cc @gatorsmile

**Comment by xuanyuanking** [comment]
retest this please

**Review by maropu — APPROVED** [review]
cc: @cloud-fan

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master, and branch-3.0.

**Comment by xuanyuanking** [comment]
Thanks for the review!

**Pull request closed without merging**
