### PR TITLE
[SPARK-35012][PYTHON] Port Koalas DataFrame-related unit tests into PySpark

### PR DESCRIPTION
**Pull request by xinrong-meng**
### What changes were proposed in this pull request?
Now that we merged the Koalas main code into the PySpark code base (#32036), we should port the Koalas DataFrame-related unit tests to PySpark.

### Why are the changes needed?
Currently, the pandas-on-Spark modules are not fully tested. We should enable the DataFrame-related unit tests first.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Enable DataFrame-related unit tests.

Keyword:SPARK-34849

### CODE REVIEW

**Comment by xinrong-databricks** [comment]
CC @ueshin @HyukjinKwon @itholic

**Review by ueshin — APPROVED** [review]
LGTM.

**Comment by ueshin** [comment]
Thanks! Merged to master.

**Comment by xinrong-databricks** [comment]
Thanks!

**Comment by itholic** [comment]
LGTM. Thanks :)

**Pull request closed without merging**
