### PR TITLE
[SPARK-31183][SQL][FOLLOWUP][3.0] Move rebase tests to `AvroSuite` and check the rebase flag out of function bodies

### PR DESCRIPTION
**Pull request by MaxGekk**
### What changes were proposed in this pull request?
1. The tests added by #27953 are moved from `AvroLogicalTypeSuite` to `AvroSuite`.
2. Checking of the `rebaseDateTime` flag is moved out from functions bodies.

This is a backport of https://github.com/apache/spark/pull/27964

### Why are the changes needed?
1. The tests are moved because they are not directly related to logical types.
2. Checking the flag out of functions bodies should improve performance.

### Does this PR introduce any user-facing change?
No

### How was this patch tested?
By running Avro tests via the command `build/sbt avro/test`

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]
LGTM if tests pass. Thanks @dongjoon-hyun and @MaxGekk

**Comment by HyukjinKwon** [comment]
Merged to branch-3.0.

**Comment by dongjoon-hyun** [comment]
Thank you, @MaxGekk and @HyukjinKwon !

**Comment by cloud-fan** [comment]
thanks, merging to 3.0!

**Comment by cloud-fan** [comment]
thanks!

**Pull request closed without merging**
