### PR TITLE
[SPARK-13306][SQL] Revert uncorrelated sub-query [test-maven]

### PR DESCRIPTION
**Pull request by hvanhovell**
### What changes were proposed in this pull request?

The unrelated sub-query PRs unadvertently broke maven builds. This PR reverts this the following commits:
https://github.com/apache/spark/commit/7925071280bfa1570435bde3e93492eaf2167d56
https://github.com/apache/spark/commit/af441ddbd13f48c09b458c451d7bba3965a878d1

The root cause is a combination of the ANTLR3 based parser and the maven shade plugin (which does bytecode rewrites). I am working on reducing the size of the parser.

cc @davies @rxin @dragos @srowen @kiszk
### How was the this patch tested?

The maven build works again.

### CODE REVIEW

**Comment by davies** [comment]
@hvanhovell I think we could have a quick fix for maven build, do not need rush to revert those, because maven build is NOT blocking our daily work.

**Comment by hvanhovell** [comment]
@davies there are people who are relying on maven builds (I thought this wasn't such a big deal either). I am welcome to splitting/modifying the ExpressionParser again; but I feel that we are nearing the end of the road there.

**Comment by davies** [comment]
Will split it in this PR: https://github.com/apache/spark/pull/11331

We have to do it anyway, unless we switch to another parser or using ANTLR4

**Comment by hvanhovell** [comment]
Hmm failed on network tests. Lemme try again.

**Pull request closed without merging**
