### PR TITLE
[SPARK-28921][K8S][FOLLOWUP] Also bump K8S client version in integration-tests

### PR DESCRIPTION
**Pull request by srowen**
### What changes were proposed in this pull request?

Per https://github.com/apache/spark/pull/25640#issuecomment-527397689 also bump K8S client version in integration-tests module.

### Why are the changes needed?

Harmonize the version as intended.

### Does this PR introduce any user-facing change?

No

### How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by srowen** [comment]
@andygrove @shaneknapp @skonto not sure if you all know what to make of this test failure?
```
lsof: WARNING: can't stat() aufs file system /var/lib/docker/aufs/mnt/04f77d5c3184798b175981cb930d3537efa8ab1dac04588c7cbd418972f0688c
lsof: WARNING: can't stat() aufs file system /home/docker/aufs/mnt/04f77d5c3184798b175981cb930d3537efa8ab1dac04588c7cbd418972f0688c
lsof: WARNING: can't stat() tmpfs file system /var/lib/docker/containers/805a48533fb8d67174d0a268446a7886192a6b21fca4760c199bc9293273489c/mounts/shm
lsof: WARNING: can't stat() tmpfs file system /home/docker/containers/805a48533fb8d67174d0a268446a7886192a6b21fca4760c199bc9293273489c/mounts/shm
```

Seems more env-related than anything?

**Comment by andygrove** [comment]
@srowen yes, I agree, this is something env-related

**Comment by srowen** [comment]
Hm, it didn't post the link to the failed test:
https://amplab.cs.berkeley.edu/jenkins//job/testing-k8s-prb-make-spark-distribution-unified/15067/

(The pass above is just for the rest of Spark which should not be affected.)

I know we need to harmonize this version though. I'm tempted to just merge it as we don't have a reason to believe it's a legit failure, and the update is important.

**Comment by skonto** [comment]
@srowen we should trigger the K8s integrations tests just in case here... would also be good to verify once more https://issues.apache.org/jira/browse/SPARK-28953 is not happening upstream.

**Comment by srowen** [comment]
How do I retrigger it?
Are you saying the issue you cite might cause this?
BTW see https://github.com/apache/spark/pull/25599

**Comment by shaneknapp** [comment]
> @andygrove @shaneknapp @skonto not sure if you all know what to make of this test failure?
> 
> ```
> lsof: WARNING: can't stat() aufs file system /var/lib/docker/aufs/mnt/04f77d5c3184798b175981cb930d3537efa8ab1dac04588c7cbd418972f0688c
> lsof: WARNING: can't stat() aufs file system /home/docker/aufs/mnt/04f77d5c3184798b175981cb930d3537efa8ab1dac04588c7cbd418972f0688c
> lsof: WARNING: can't stat() tmpfs file system /var/lib/docker/containers/805a48533fb8d67174d0a268446a7886192a6b21fca4760c199bc9293273489c/mounts/shm
> lsof: WARNING: can't stat() tmpfs file system /home/docker/containers/805a48533fb8d67174d0a268446a7886192a6b21fca4760c199bc9293273489c/mounts/shm
> ```
> 
> Seems more env-related than anything?

you can safely ignore these...

**Comment by shaneknapp** [comment]
test this please

**Comment by shaneknapp** [comment]
k8s integration tests running here:  https://amplab.cs.berkeley.edu/jenkins/job/testing-k8s-prb-make-spark-distribution-unified/15147/

**Comment by srowen** [comment]
Merged to master/2.4

**Pull request closed without merging**
