### PR TITLE
[SPARK-7927] Turn whitespace checker on for more token types.

### PR DESCRIPTION
**Pull request by rxin**
This is the last batch of changes to complete SPARK-7929.

Previous related PRs:
https://github.com/apache/spark/pull/6480
https://github.com/apache/spark/pull/6478
https://github.com/apache/spark/pull/6477
https://github.com/apache/spark/pull/6476
https://github.com/apache/spark/pull/6475
https://github.com/apache/spark/pull/6474
https://github.com/apache/spark/pull/6473

### CODE REVIEW

**Comment by rxin** [comment]
cc @mengxr

**Comment by mengxr** [comment]
LGTM

**Comment by jongwook** [comment]
Hi, this commit is just before the `v1.4.0-rc3` tag and fails me building Spark core with 

```
[INFO] --- scalastyle-maven-plugin:0.7.0:check (default) @ spark-core_2.10 ---
error file=/tmp/spark-build/core/src/main/scala/org/apache/spark/storage/TachyonBlockManager.scala message=No space after token = line=41 column=33
Saving to outputFile=/tmp/spark-build/core/target/scalastyle-output.xml
Processed 465 file(s)
Found 1 errors
Found 0 warnings
Found 0 infos
```

Is this intended or am I doing something wrong?

**Comment by rxin** [comment]
I'm going to push a fix to it.

**Comment by rxin** [comment]
Ok I pushed. It should work now.

**Pull request closed without merging**
