### PR TITLE
[SPARK-40234][Core] Clean only MDC items set by Spark

### PR DESCRIPTION
**Pull request by viirya**
### What changes were proposed in this pull request?

This patch proposes to reduce the range of MDC cleanup from all MDC items to only MDC items set by Spark `setLocalProperty`.

### Why are the changes needed?

Since [SPARK-8981](https://issues.apache.org/jira/browse/SPARK-8981), Spark executor adds MDC support. Before setting MDC items, the executor cleans up all MDC items. But it causes an issue for other MDC items not set by Spark but from users at other places. It causes these custom MDC items not shown in executor log.

### Does this PR introduce _any_ user-facing change?

Yes, previously cleaned MDC items will be shown.

### How was this patch tested?

Test manually.

### CODE REVIEW

**Comment by viirya** [comment]
cc @dongjoon-hyun @cloud-fan @Ngone51

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM

**Comment by viirya** [comment]
Unrelated python error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/dist-packages/black/__main__.py", line 3, in <module>
    patched_main()
  File "/usr/local/lib/python3.9/dist-packages/black/__init__.py", line 1372, in patched_main
    patch_click()
  File "/usr/local/lib/python3.9/dist-packages/black/__init__.py", line 1358, in patch_click
    from click import _unicodefun
ImportError: cannot import name '_unicodefun' from 'click' (/usr/local/lib/python3.9/dist-packages/click/__init__.py)
Please run 'dev/reformat-python' script.
```

**Comment by viirya** [comment]
Thanks. Merging to master.

**Comment by dongjoon-hyun** [comment]
Thank you, @viirya !

**Review by cloud-fan — COMMENTED** [review]
late LGTM

**Comment by viirya** [comment]
Thanks @cloud-fan

**Pull request closed without merging**
