### PR TITLE
[SparkR][Test]:remove unnecessary suppressWarnings

### PR DESCRIPTION
**Pull request by wangmiao1981**
## What changes were proposed in this pull request?

In test_mllib.R, there are two unnecessary suppressWarnings. This PR just removes them.

## How was this patch tested?

Existing unit tests.

### CODE REVIEW

**Comment by wangmiao1981** [comment]
retest it please

**Comment by wangmiao1981** [comment]
windows failure seems unrelated

**Comment by HyukjinKwon** [comment]
Build started: [SparkR] `ALL` [PR-15697](https://ci.appveyor.com/project/spark-test/spark/branch/61EB4045-4845-4B2D-9AE9-6F0CC42B7B6E)
Diff: https://github.com/apache/spark/compare/master...spark-test:61EB4045-4845-4B2D-9AE9-6F0CC42B7B6E

**Comment by HyukjinKwon** [comment]
Hm, yes it seems unrelated. I will look into this deeper.

**Comment by HyukjinKwon** [comment]
It seems R 3.3.2 is released but R 3.3.1 is not registered in old ones yet (in see - https://cloud.r-project.org/bin/windows/base/old). @shivaram and @felixcheung Should we should use R 3.3.0 just for safety?

**Comment by wangmiao1981** [comment]
@HyukjinKwon Thanks for your time!

**Comment by HyukjinKwon** [comment]
Build started: [SparkR] `ALL` [PR-15697](https://ci.appveyor.com/project/spark-test/spark/branch/846E764A-967B-4CB2-A78C-968D86EDFEF2)
Diff: https://github.com/apache/spark/compare/master...spark-test:846E764A-967B-4CB2-A78C-968D86EDFEF2

I am pretty sure it is fine now :) it seems 3.3.2 was just released.

**Comment by wangmiao1981** [comment]
retest this please

**Comment by wangmiao1981** [comment]
retest this please

**Comment by wangmiao1981** [comment]
@HyukjinKwon It seems that windows test still fails with the same error

**Comment by HyukjinKwon** [comment]
Oh, AppVeyor test is not triggered again with the Jebkins one.
Or, do you mean you launched another build via another account and manually tested it?

**Comment by wangmiao1981** [comment]
No, I just launched Jenkins test. I don't know how to manually trigger the AppVeyor test.

**Comment by HyukjinKwon** [comment]
Ah, yes actually that's a problem now unfortunately. It seems even comitters can't retrigger. Actually, that's why I ran this via another account and left the comment above. I am trying to find a better way and will probably open a INFRA jira.

**Comment by HyukjinKwon** [comment]
Hey @wangmiao1981, I just found another (a bit ugly) workaround to re-trigger. It seems it starts to rebuild after closing and re-opening. I just tested in https://github.com/spark-test/spark/pull/11

**Comment by felixcheung** [comment]
@HyukjinKwon the time window when download of an older version for windows could fail seem concerning. Is there a way to address that?

**Comment by HyukjinKwon** [comment]
For the specific failure here, it was due to not syncing the latest version between the releases for Winodws and the others (when R 3.3.2 was released). As we use a fixed version, R 3.3.1 now (not the latest but old one), we wouldn't meet the same case for the same reason in the future (I described this problem in more details in https://github.com/apache/spark/pull/15709). 

However, I guess you meant the concern of re-triggering the spurious failures in general. For re-triggering tests, I am still looking into this deeper. Will make a INFRA JIRA as soon as I figure out the way committers can re-trigger. Current ways I have figured out so far as a (ugly) workaround are, 
- Use another AppVeyor account
- Closing and then re-opening to launch another build.

**Comment by wangmiao1981** [comment]
Now, I try to close and reopen it to trigger another windows test.

**Comment by wangmiao1981** [comment]
reopen it now.

**Comment by felixcheung** [comment]
right, I think I see two problems, both of those you have looked into (thanks)
first, if we can't rely on R releases for multiple platform to be push at roughly the same time, that's problematic if there is no other way to find the latest version of that platform. Since we are fixed on the lowest version on Jenkins, I see one of the benefits with appveyor is that we could pick up the latest version (we have been broken by both, more than once)

second, re-triggering is spotty. Is that perhaps an appveyor issue?

In any case we could likely follow up in separate JIRAs.

**Comment by HyukjinKwon** [comment]
Yes, it is probably an issue because it seems currently no one except who has the AppVeyor account called ApacheSoftwareFoundation can re-trigger. I should look into this further though.. Will update you.

**Comment by wangmiao1981** [comment]
@felixcheung Any comments?

**Comment by felixcheung** [comment]
merged to master.

**Pull request closed without merging**
