### PR TITLE
[SPARK-13197][SQL] When trying to select from the data frame which contains the columns with . in it, it is throwing exception.

### PR DESCRIPTION
**Pull request by thomastechs**
When trying to select from the data frame which contains the columns with . in it, it is throwing exception.
Added the fix in the select method to incorporate the selection of columns containing . in it

### CODE REVIEW

**Comment by hvanhovell** [comment]
I think the same problem is solved in: https://github.com/apache/spark/pull/10943

**Comment by thomastechs** [comment]
@hvanhovell  and @jayadevanmurali    We checked the source code change in the referenced PR@10943. That PR is resolving the similar issue in the drop scenario. But this current fix would be for the explicit select statements as stated in our bug.Also we double checked whether the fix @PR-10943 would resolve the select issue . But, it does not resolve this bug. So ,please let us know your comments.

**Comment by clockfly** [comment]
@thomastechs 

We should use `df.select("`a.c`")` to select a column with name "a.c".
The reason is that we can df.select can be used to select a nested column, for example:

```
scala> case class A(inner: Int)
scala> val df = Seq((A(1), 2)).toDF("a", "b")
scala> df.select("a.inner")
res10: org.apache.spark.sql.DataFrame = [inner: int]

scala> df2.select("a.inner").show()
+-----+
|inner|
+-----+
|    1|
+-----+
```

So, I think this is NOT a bug, current behavior of select is expected.

**Comment by HyukjinKwon** [comment]
+1 for not a problem.

**Pull request closed without merging**
