### PR TITLE
[SPARK-5731][Streaming][Test] Fix incorrect test in DirectKafkaStreamSuite

### PR DESCRIPTION
**Pull request by tdas**
The test was incorrect. Instead of counting the number of records, it counted the number of partitions of RDD generated by DStream. Which is not its intention. I will be testing this patch multiple times to understand its flakiness.

PS: This was caused by my refactoring in https://github.com/apache/spark/pull/4384/

@koeninger check it out.

### CODE REVIEW

**Comment by koeninger** [comment]
LGTM

**Comment by rxin** [comment]
Seems like streamingcontext itself is a bit flaky ...

**Comment by tdas** [comment]
Why? Even the failure of StreamingContext.stop() unit test in the failed Test build #609 above was causing by the same broadcast piece failure.
```
[info] - stop(stopSparkContext=true) after stop(stopSparkContext=false) *** FAILED *** (65 milliseconds)
[info]   org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 1 times, most recent failure: Lost task 0.0 in stage 0.0 (TID 0, localhost): java.io.IOException: org.apache.spark.SparkException: Failed to get broadcast_0_piece0 of broadcast_0
```

This is indeed weird. Anyways, the Kafka test seems pretty solid now. If its okay with you I merging this, and we can continue investigating on the broadcast problem independently.

**Comment by rxin** [comment]
Please go ahead and merge.

**Pull request closed without merging**
