### PR TITLE
[SPARK-6754] Remove unnecessary TaskContextHelper

### PR DESCRIPTION
**Pull request by kayousterhout**
The TaskContextHelper was originally necessary because TaskContext was written in Java, which does
not have a way to specify that classes are package-private, so TaskContextHelper existed to work
around this. Now that TaskContext has been re-written in Scala, this class is no longer necessary.

@rxin can you look at this? It looks like you missed this bit of cleanup when you moved TaskContext from Java to Scala in #4324

cc @ScrapCodes and @pwendell who added this originally.

### CODE REVIEW

**Comment by rxin** [comment]
LGTM

**Comment by pwendell** [comment]
LGTM

**Comment by ScrapCodes** [comment]
(Though it is redundant to say. :) ) LGTM too.

**Comment by rxin** [comment]
I'm merging this in master. Thanks.

**Pull request closed without merging**
