### PR TITLE
[SPARK-29498][SQL] CatalogTable to HiveTable should not change the table's ownership

### PR DESCRIPTION
**Pull request by wangyum**
### What changes were proposed in this pull request?

`CatalogTable` to `HiveTable` will change the table's ownership. How to reproduce:
```scala
import org.apache.spark.sql.catalyst.TableIdentifier
import org.apache.spark.sql.catalyst.catalog.{CatalogStorageFormat, CatalogTable, CatalogTableType}
import org.apache.spark.sql.types.{LongType, StructType}

val identifier = TableIdentifier("spark_29498", None)
val owner = "SPARK-29498"
val newTable = CatalogTable(
  identifier,
  tableType = CatalogTableType.EXTERNAL,
  storage = CatalogStorageFormat(
    locationUri = None,
    inputFormat = None,
    outputFormat = None,
    serde = None,
    compressed = false,
    properties = Map.empty),
  owner = owner,
  schema = new StructType().add("i", LongType, false),
  provider = Some("hive"))

spark.sessionState.catalog.createTable(newTable, false)
// The owner is not SPARK-29498
println(spark.sessionState.catalog.getTableMetadata(identifier).owner)
```

This PR makes it set the `HiveTable`'s owner to `CatalogTable`'s owner if it's owner is not empty when converting `CatalogTable` to `HiveTable`.

### Why are the changes needed?
We should not change the ownership of the table when converting `CatalogTable` to `HiveTable`.

### Does this PR introduce any user-facing change?
No

### How was this patch tested?
unit test

### CODE REVIEW

**Comment by wangyum** [comment]
cc @yaooqinn @cloud-fan

**Comment by yaooqinn** [comment]
IIUC, the ownership of a table only be created/changed(#26068) when we create or alter a table. 
CreateTable - the owner <=> the creator <=> the spark runner
AlterTable - the original owner or the spark runner if none or empty
So I guess both cases are handled with or without this change.

[SPARK-29507](https://issues.apache.org/jira/browse/SPARK-29507), We now just lack the ability to modify the owner of a table.

**Comment by wangyum** [comment]
I think the owner of the `HiveTable` is always the same as the owner of the `CatalogTable` if the owner of the `CatalogTable` is not empty.

This is how we convert `HiveTable` to `CatalogTable`:
https://github.com/apache/spark/blob/86d8325ed10444074ccfbcb145f511492db5cf44/sql/hive/src/main/scala/org/apache/spark/sql/hive/client/HiveClientImpl.scala#L519

**Comment by yaooqinn** [comment]
Anyway, this change can keep the consistency of ownership between catalog table and hive table, so LGTM

**Comment by dongjoon-hyun** [comment]
cc @gatorsmile

**Comment by cloud-fan** [comment]
LGTM, merging to master!

**Comment by dongjoon-hyun** [comment]
Thank you, @cloud-fan , @wangyum .
Since this is a bug reported for the old releases, can we have this in our LTS branch, `branch-2.4`, too?

**Review by HyukjinKwon — COMMENTED** [review]
Thanks @wangyum. Looks fine to me too

**Pull request closed without merging**
