### PR TITLE
[SPARK-42564][CONNECT] Implement SparkSession.version and SparkSession.time

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to implement SparkSession.version and SparkSession.time.

### Why are the changes needed?
API coverage.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Add new UT.

### CODE REVIEW

**Review by hvanhovell — APPROVED** [review]
LGTM

**Comment by hvanhovell** [comment]
Merging

**Comment by hvanhovell** [comment]
Thanks for doing this!

**Comment by dongjoon-hyun** [comment]
Thank you for doing this too!

**Pull request closed without merging**
