### PR TITLE
[SPARK-45850][BUILD] Upgrade oracle jdbc driver to 23.3.0.23.09

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to upgrade oracle jdbc driver from `com.oracle.database.jdbc:ojdbc8:23.2.0.0` to `com.oracle.database.jdbc:ojdbc11:23.3.0.23.09`.

### Why are the changes needed?
It is often found that `Run Docker integration tests` is interrupted due to `OracleIntegrationSuite` failure.
Several possible issues have been identified:
- The `oracle jdbc driver` currently used in Spark is `com.oracle.database.jdbc:ojdbc8`, it not for use with `JDK17`.
https://www.oracle.com/database/technologies/maven-central-guide.html
image

- The `oracle server` version used in our GA environment is also `23.3`
image

After upgrade to `com.oracle.database.jdbc:ojdbc11`, I attempted to trigger `Run Docker integration tests` 6 times (trigger date distribution: day, night or weekend, etc.), and have all been successful for the `first time`.
https://github.com/panbingkun/spark/actions/runs/6760572538/job/18383757692
https://github.com/panbingkun/spark/actions/runs/6765163954/job/18399468066
https://github.com/panbingkun/spark/actions/runs/6778851101/job/18465823046
https://github.com/panbingkun/spark/actions/runs/6797719942/job/18480445904
https://github.com/panbingkun/spark/actions/runs/6804543746/job/18502353511
https://github.com/panbingkun/spark/actions/runs/6809925232/job/18521970051

So, I proposed upgrading this driver first and then continuing to observe the effect.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by panbingkun** [comment]
cc @dongjoon-hyun @HyukjinKwon @LuciferYang

**Comment by LuciferYang** [comment]
Although this may seem somewhat magical, if it can truly solve the problem, I agree to proceed with the upgrade.

**Comment by panbingkun** [comment]
> Although this may seem somewhat magical, if it can truly solve the problem, I agree to proceed with the upgrade.

I'm not sure if it will ultimately make `OracleIntegrationSuite` testing stable, but this version of the driver is more compatible with the JDK17 used by Spark and the Oracle Server version in the container. Maybe we can give it a try.

**Comment by dongjoon-hyun** [comment]
> > Although this may seem somewhat magical, if it can truly solve the problem, I agree to proceed with the upgrade.
> 
> I'm not sure if it will ultimately make `OracleIntegrationSuite` testing stable, but this version of the driver is more compatible with the JDK17 used by Spark and the Oracle Server version in the container. Maybe we can give it a try.

If then, please update the PR title by simply saying that `Upgrade`, @panbingkun .

We can merge this PR for that purpose.

**Comment by panbingkun** [comment]
> > > Although this may seem somewhat magical, if it can truly solve the problem, I agree to proceed with the upgrade.
> > 
> > 
> > I'm not sure if it will ultimately make `OracleIntegrationSuite` testing stable, but this version of the driver is more compatible with the JDK17 used by Spark and the Oracle Server version in the container. Maybe we can give it a try.
> 
> If then, please update the PR title by simply saying that `Upgrade`, @panbingkun .
> 
> We can merge this PR for that Java purpose.

Done.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by dongjoon-hyun** [comment]
Merged to master. Thank you, @panbingkun and @LuciferYang .

**Pull request closed without merging**
