### PR TITLE
Spark-7063 when lz4 compression is used, it causes core dump

### PR DESCRIPTION
**Pull request by JihongMA**
this fix is to solve one issue found in lz4 1.2.0, which caused core dump in Spark Core with IBM JDK.  that issue is fixed in lz4 1.3.0 version.

### CODE REVIEW

**Comment by rxin** [comment]
Can you update the pull request title to make it more informative?

**Comment by srowen** [comment]
ok to test

**Comment by srowen** [comment]
@JihongMA I can merge this, and can even fix the title on merge, but would you fix it up if you have a moment please?

**Comment by JihongMA** [comment]
I have just updated the title. Thanks!

**Comment by srowen** [comment]
@JihongMA the title of this PR has not been updated, please give it a title that matches the JIRA

**Comment by JihongMA** [comment]
sorry, it is done now.

**Pull request closed without merging**
