### PR TITLE
[SPARK-12148][SPARKR] SparkR: rename DataFrame to SparkDataFrame

### PR DESCRIPTION
**Pull request by felixcheung**
## What changes were proposed in this pull request?

Changed class name defined in R from "DataFrame" to "SparkDataFrame". A popular package, S4Vector already defines "DataFrame" - this change is to avoid conflict.

Aside from class name and API/roxygen2 references, SparkR APIs like `createDataFrame`, `as.DataFrame` are not changed (S4Vector does not define a "as.DataFrame").

Since in R, one would rarely reference type/class, this change should have minimal/almost-no impact to a SparkR user in terms of back compat.
## How was this patch tested?

SparkR tests, manually loading S4Vector then SparkR package

### CODE REVIEW

**Comment by felixcheung** [comment]
@shivaram

**Comment by rxin** [comment]
Merging in master. Thanks!

**Comment by shivaram** [comment]
@felixcheung I just noticed that DataFrame.R (the diff for which didn't show up) has a bunch of roxygen comments of the form `SparkSparkDataFrame` -- Could you send a follow up PR to fix those ?

**Comment by felixcheung** [comment]
That's odd. Will do that today.



    _____________________________

**Pull request closed without merging**
