### PR TITLE
[SPARK-47515][SPARK-47406][SQL][FOLLOWUP] Add legacy config spark.sql.legacy.mysql.timestampNTZMapping.enabled

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

This PR adds a legacy config `spark.sql.legacy.mysql.timestampNTZMapping.enabled` to make user available to restore the old type mapping between timestamp_ntz and MySQL TIMESTAMP/DATETIME

### Why are the changes needed?

Avoid unrecoverable breaking changes, following the principles of https://lists.apache.org/thread/6bb1crw9dqgntp2p4dk67b7313mo5frz

### Does this PR introduce _any_ user-facing change?
no

### How was this patch tested?
new tests

### Was this patch authored or co-authored using generative AI tooling?
no

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
cc @cloud-fan

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @yaooqinn .

**Review by HyukjinKwon — APPROVED** [review]

**Comment by yaooqinn** [comment]
Thank you @dongjoon-hyun @HyukjinKwon 

Merged to master

**Comment by cloud-fan** [comment]
late LGTM

**Pull request closed without merging**
