### PR TITLE
[SPARK-45955][UI] Collapse Support for Flamegraph and thread dump details

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

This PR supports collapse flamegraph and thread dump details like other pages

https://github.com/apache/spark/assets/8326978/ea5e224b-7edf-4bcd-bd83-c4243cdd7e58

### Why are the changes needed?

UX improvement for UI

### Does this PR introduce _any_ user-facing change?

yes， UI changes

### How was this patch tested?

As shown in the above video
### Was this patch authored or co-authored using generative AI tooling?

no

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
It's nice. BTW, could you fix `lint-js` failure?

```
/__w/spark/spark/core/src/main/resources/org/apache/spark/ui/static/flamegraph.js
  40:5  error  '$' is not defined  no-undef

/__w/spark/spark/core/src/main/resources/org/apache/spark/ui/static/table.js
  115:3   error  'collapseTable' is not defined  no-undef
  1[17](https://github.com/yaooqinn/spark/actions/runs/6890950658/job/18746764140#step:25:18):13  error  'd3' is not defined             no-undef
  1[19](https://github.com/yaooqinn/spark/actions/runs/6890950658/job/18746764140#step:25:20):5   error  'd3' is not defined             no-undef
  1[21](https://github.com/yaooqinn/spark/actions/runs/6890950658/job/18746764140#step:25:22):5   error  'd3' is not defined             no-undef
```

**Comment by yaooqinn** [comment]
Thank you @dongjoon-hyun

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM (Pending CI). Thank you, @yaooqinn !

**Comment by dongjoon-hyun** [comment]
Merged to master!

**Comment by sarutak** [comment]
Late LGTM. Thank you @yaooqinn !

**Comment by yaooqinn** [comment]
Thank you very much @sarutak !

**Pull request closed without merging**
