### PR TITLE
[SPARK-31554][SQL][TESTS] Retry flaky tests from CliSuite

### PR DESCRIPTION
**Pull request by MaxGekk**
### What changes were proposed in this pull request?
Retry tests from `CliSuite`. This is temporary changes till someone stabilises the test suite. 

### Why are the changes needed?
To not disturb other PRs.

### Does this PR introduce any user-facing change?
No

### How was this patch tested?
By running the test suite locally via:
```
./build/sbt -Phive -Phive-thriftserver "test:testOnly *CliSuite"
```

### CODE REVIEW

**Comment by MaxGekk** [comment]
@cloud-fan @gatorsmile @HyukjinKwon Please, take a look at it.

**Comment by HeartSaVioR** [comment]
What about trying below PRs first and see whether the help, and revisit this?

#28156
#28055

**Comment by MaxGekk** [comment]
@HeartSaVioR This is a temporary fix till the issue of test flakiness is resolved by PRs you mentioned or by some other PRs. /cc @cloud-fan @dongjoon-hyun @srowen @gatorsmile

**Comment by MaxGekk** [comment]
It seems @juliuszsompolski 's PR https://github.com/apache/spark/pull/28156 fixed the issue. I am closing this.

**Pull request closed without merging**
