### PR TITLE
[SPARK-30954][ML][R]Make  file name the same as class name

### PR DESCRIPTION
**Pull request by kevinyu98**
This pr solved the same issue as [pr27919](https://github.com/apache/spark/pull/27919), but this one changes the file names based on comment from previous pr.

### What changes were proposed in this pull request?

Make some of  file names the same as class name in R package.

### Why are the changes needed?

Make the file consistence

### Does this PR introduce any user-facing change?

No
### How was this patch tested?

run `./R/run-tests.sh`

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
ok to test

**Comment by dongjoon-hyun** [comment]
cc @zhengruifeng and @srowen

**Comment by srowen** [comment]
Yep seems OK. CC @felixcheung just FHI

**Review by dongjoon-hyun — APPROVED** [review]

**Comment by huaxingao** [comment]
retest this please

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Merged to master/3.0.
Thank you, @kevinyu98 , @srowen , @huaxingao !

**Comment by felixcheung** [comment]
Ok

**Comment by dongjoon-hyun** [comment]
Thank you, @felixcheung !

**Pull request closed without merging**
