### PR TITLE
[DO_NOT_MERGE] Test netty

### PR DESCRIPTION
**Pull request by zsxwing**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)
## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)
(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

Please review https://cwiki.apache.org/confluence/display/SPARK/Contributing+to+Spark before opening a pull request.

### CODE REVIEW

**Comment by srowen** [comment]
Yeah, this is what I'm trying now, including putting it in the main flume artifact. No go. The assembly definitely has the class. I think it is somehow not sufficient to put this code in the app classpath with --jars. I mean, we could somehow try to merge the assembly jars into one for Pyspark tests. It is starting to get messy!

**Comment by zsxwing** [comment]
@srowen I ran the flume python tests locally and didnt find the same issue...

**Comment by srowen** [comment]
Did you clear your locally built artifacts first? maybe that's the difference. The Jenkins test here hits the same problem I was seeing.

**Comment by srowen** [comment]
PS I got this to work by making the pyspark tests specify the "userClassPathFirst" flags. I think that's actually reasonable to set. I will try this in my PR at https://github.com/apache/spark/pull/15436 and hope it works; if so you can close this I think.

**Pull request closed without merging**
