### PR TITLE
[SPARK-33145] [WEBUI] Fix when `Succeeded Jobs` has many child url elements,they will extend over the edge of the page. 

### PR DESCRIPTION
**Pull request by echohlne**
### What changes were proposed in this pull request?
In Execution web page, when `Succeeded Job`(or Failed Jobs) has many child url elements,they will extend over the edge of the page. 

### Why are the changes needed?
To make the page more friendly.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?

Munual test result shows  as below:

fixed

### CODE REVIEW

**Comment by akiyamaneko** [comment]
cc: @sarutak @gengliangwang

**Comment by gengliangwang** [comment]
ok to test

**Comment by gengliangwang** [comment]
@akiyamaneko Thanks for the improvement!
Could you add the screenshot after fix in the PR description?

**Comment by akiyamaneko** [comment]
I have attached the screenshot, or you can vist [fix-screenshot](https://user-images.githubusercontent.com/52202080/95977319-50734600-0e4b-11eb-93c0-b8deb565bcd8.png)

**Review by gengliangwang — APPROVED** [review]
LGTM

**Comment by gengliangwang** [comment]
Thanks, merging to master

**Pull request closed without merging**
