### PR TITLE
[SPARK-5313][Project Infra]: Create simple framework for highlighting changes introduced in a PR

### PR DESCRIPTION
**Pull request by brennonyork**
Built a simple framework with a `dev/tests` directory to house all pull request related tests. I've moved the two original tests (`pr_merge_ability` and `pr_public_classes`) into the new `dev/tests` directory and tested to the best of my ability. At this point I need to test against Jenkins actually running the new `run-tests-jenkins` script to ensure things aren't broken down the path.

### CODE REVIEW

**Comment by brennonyork** [comment]
For further clarification to build a new PR-related test one merely needs to follow the following rules (also noted within the `run-tests-jenkins` script):

* the file must reside within the dev/tests directory
* be an executable bash script
* accept two arguments on the command line, the first being the Github PR long commit hash and the second the Github SHA1 hash
* and, lastly, return string output to be included in the pr message output that will be posted to Github

/cc @nchammas @pwendell

**Comment by brennonyork** [comment]
jenkins, retest this please

**Comment by brennonyork** [comment]
Awesome. PR is ready to be checked. See Test Build 28813 for the proper output. Thoughts / comments? If this is good I can then push through [SPARK-4123](https://issues.apache.org/jira/browse/SPARK-4123) adding a test for new dependencies.

/cc @srowen as well.

**Comment by srowen** [comment]
So am I right that the purpose here is just to refactor these two different tests into separate scripts? Eyeballing it, it looks like that's exactly what this does, but want to double check that this was also the intent.

**Comment by brennonyork** [comment]
Correct. This refactors out each test independently and allows an easy way forward to add new tests for the PR.

**Comment by srowen** [comment]
OK, as a strict refactoring I think this looks nice. It does make it simple to drop in a new check, and I don't see that this adds much complexity. LGTM but will wait a short while for comments.

**Pull request closed without merging**
