### PR TITLE
[SPARK-7627][SPARK-7472] DAG visualization: style skipped stages

### PR DESCRIPTION
**Pull request by andrewor14**
This patch fixes two things:

**SPARK-7627.** Cached RDDs no longer light up on the job page. This is a simple fix.
**SPARK-7472.** Display skipped stages differently from normal stages.

The latter is a major UX issue. Because we link the job viz to the stage viz even for skipped stages, the user may inadvertently click into the stage page of a skipped stage, which is empty.

---

### CODE REVIEW

**Comment by andrewor14** [comment]
@zsxwing it would be good if you could verify that the listener clean up logic is correct. I have added tests for that purpose but we should test it out in a real long-running streaming application.

**Comment by andrewor14** [comment]
Also cc @mateiz who suggested this change.

**Comment by zsxwing** [comment]
Testing your PR. Let's see if there is any memory leak tomorrow morning.

**Comment by mateiz** [comment]
A small note on the colors -- make them a grayscale version of the colors used in the normal stages, because right now they're quite a bit darker. Just take a picture of the normal stages and turn it to grayscale to grab the right colors.

**Comment by mateiz** [comment]
Alternatively you could also make them lighter and use dashed lines (http://www.w3schools.com/svg/svg_stroking.asp), but I'm not sure how good that will look.

**Comment by andrewor14** [comment]
Ok, I've updated the screenshot. I tried out the dotted lines but I thought the gray looks better.

**Comment by mateiz** [comment]
Cool, this looks pretty good. Maybe I'd make the border on skipped stages slightly darker since the red is darker than blue on the other ones, but overall it's fine.

**Comment by andrewor14** [comment]
I discussed with @zsxwing offline and he found that the memory usage is stable for long-running jobs.  I'm merging this into master and 1.4. Thanks for all the feedback.

**Pull request closed without merging**
