### PR TITLE
[SPARK-18103] [SQL] Rename *FileCatalog to *FileIndex

### PR DESCRIPTION
**Pull request by ericl**
## What changes were proposed in this pull request?

To reduce the number of components in SQL named *Catalog, rename *FileCatalog to *FileIndex. A FileIndex is responsible for returning the list of partitions / files to scan given a filtering expression.

```
TableFileCatalog => CatalogFileIndex
FileCatalog => FileIndex
ListingFileCatalog => InMemoryFileIndex
MetadataLogFileCatalog => MetadataLogFileIndex
PrunedTableFileCatalog => PrunedInMemoryFileIndex
```

cc @yhuai @marmbrus 
## How was this patch tested?

N/A

### CODE REVIEW

**Comment by marmbrus** [comment]
This is okay, but note that "Provider" is equally overloaded in the Data Source API.

**Comment by ericl** [comment]
Hmm, any other suggestions?

**Comment by rxin** [comment]
FileLister? FileListing?

**Comment by ericl** [comment]
How about `FileIndex`, since this class is responsible for both listing and filtering functionality?

**Comment by ericl** [comment]
Concretely, I propose renaming
```
TableFileCatalog => MetastoreFileIndex

ListingFileCatalog => InMemoryFileIndex

MetadataLogFileCatalog => MetadataLogFileIndex

PrunedTableFileCatalog => PrunedInMemoryFileIndex
```
I think this would make the differences between these classes more clear. Previously, the name was only loosely tied with their behavior.

**Comment by rxin** [comment]
FileIndex sounds good to me. I wouldn't call it "Metastore" though, since that is a Hive specific term. I'd call it Catalog.

**Comment by rxin** [comment]
LGTM pending tests.

**Comment by rxin** [comment]
Merging in master.

**Pull request closed without merging**
