### PR TITLE
[SPARK-14933][HOTFIX] Replace `sqlContext` with `spark`.

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
## What changes were proposed in this pull request?

This fixes compile errors.
## How was this patch tested?

Pass the Jenkins tests.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
cc @andrewor14 , @cloud-fan

**Comment by dongjoon-hyun** [comment]
Hi, @mengxr . Could you merge this?

**Comment by yhuai** [comment]
Thanks. I am merging this to master and branch 2.0.

**Comment by yhuai** [comment]
OK. It is in. Thank you!

**Comment by dongjoon-hyun** [comment]
Thank you!

**Pull request closed without merging**
