### PR TITLE
[SPARK-18004][SQL] Make sure the date or timestamp related predicate can be pushed down to Oracle correctly

### PR DESCRIPTION
**Pull request by SharpRay**
## What changes were proposed in this pull request?

1. Override beforeFetch method in OracleDialect to finish the following two things:
    -  Set Oracle's NLS_TIMESTAMP_FORMAT to "YYYY-MM-DD HH24:MI:SS.FF" to match java.sql.Timestamp format.
    -  Set Oracle's NLS_DATE_FORMAT to "YYYY-MM-DD" to match java.sql.Date format.

2. Timestamp and Date type are the same data type in the versions of oracle jdbc after 10g. So we should differentiate Date type from Timestamp type to make sure the Date-related predicates can be pushed down to Oracle correctly. The related work is done in the getCatalystType method of the OracleDialect object.

## How was this patch tested?

An integration test has been added and a existing unit test has been modified.

### CODE REVIEW

**Comment by maropu** [comment]
Hi, I think you need to make pr to not `branch-2.1` but `master`.

**Comment by SharpRay** [comment]
OK, I will make this PR to master, Thank you.

**Comment by SharpRay** [comment]
Please forgive a novice for the wrong operation...
I will post a PR again later.

**Comment by maropu** [comment]
NVM.

**Pull request closed without merging**
