### PR TITLE
[SPARK-37274][SQL]When the value of this parameter is greater than the maximum value of int type, the value will be thrown out of bounds. The document description of this parameter should remind the user of this risk point

### PR DESCRIPTION
**Pull request by dh20**
### What changes were proposed in this pull request?

The data type of some parameters has been modified

### Why are the changes needed?

This will make the user experience better and improve the robustness of the code

### Does this PR introduce _any_ user-facing change?
NO

### How was this patch tested?
Package and go online to the production environment for operation

### CODE REVIEW

**Comment by dh20** [comment]
@sarutak Hi, can you take a look at this PR, thank you

**Comment by sarutak** [comment]
@dh20 Thank you for trying to make the doc better. But users can know the proper data type from the error message.
```
java.lang.IllegalArgumentException: Error while instantiating 'org.apache.spark.sql.hive.HiveSessionStateBuilder':
  at org.apache.spark.sql.SparkSession$.org$apache$spark$sql$SparkSession$$instantiateSessionState(SparkSession.scala:1151)
  at org.apache.spark.sql.SparkSession.$anonfun$sessionState$2(SparkSession.scala:158)
  at scala.Option.getOrElse(Option.scala:189)
  at org.apache.spark.sql.SparkSession.sessionState$lzycompute(SparkSession.scala:156)
  at org.apache.spark.sql.SparkSession.sessionState(SparkSession.scala:153)
  at org.apache.spark.sql.SparkSession.conf$lzycompute(SparkSession.scala:181)
  at org.apache.spark.sql.SparkSession.conf(SparkSession.scala:181)
```
I think it's enough.

Also, even if we mention the data type of the property, we should mention the data types for all the properties.

**Comment by dh20** [comment]
> @dh20 Thank you for trying to make the doc better. But users can know the proper data type from the error message.
> 
> ```
> java.lang.IllegalArgumentException: Error while instantiating 'org.apache.spark.sql.hive.HiveSessionStateBuilder':
>   at org.apache.spark.sql.SparkSession$.org$apache$spark$sql$SparkSession$$instantiateSessionState(SparkSession.scala:1151)
>   at org.apache.spark.sql.SparkSession.$anonfun$sessionState$2(SparkSession.scala:158)
>   at scala.Option.getOrElse(Option.scala:189)
>   at org.apache.spark.sql.SparkSession.sessionState$lzycompute(SparkSession.scala:156)
>   at org.apache.spark.sql.SparkSession.sessionState(SparkSession.scala:153)
>   at org.apache.spark.sql.SparkSession.conf$lzycompute(SparkSession.scala:181)
>   at org.apache.spark.sql.SparkSession.conf(SparkSession.scala:181)
> ```
> 
> I think it's enough.
> 
> Also, even if we mention the data type of the property, we should mention the data types for all the properties.

@sarutak Thank you for reviewing this pr. Thank you for reviewing this pr. in my opinion, the user setting of this parameter may exceed the maximum value of int type. Can it be changed to long type?

**Comment by sarutak** [comment]
Your original claim is to note about the type of the property for clarification isn't it?
But your next claim is to change the type of the property to expand the maximum batch size.
Which is what you really want to do?

Anywai, feel free to open another PR but I think it's not easy to change the type to `long` because the property is related to the index of arrays.

**Comment by dh20** [comment]
> Your original claim is to note about the type of the property for clarification isn't it? But your next claim is to change the type of the property to expand the maximum batch size. Which is what you really want to do?
> 
> Anyway, feel free to open another PR but I think it's not easy to change the type to `long` because the property is related to the index of some kinds of arrays.

Yes, sir. What I want to do is that this parameter should be set to the maximum value of int for users. In that case, we should support it.
However, after reading this code, it is not easy to change this parameter to long type. Therefore, I think it is more rigorous to prompt the user for the boundary value of this parameter in the document rather than in the error!!!
At the same time, I will try to modify the type of this parameter.

**Comment by GuoPhilipse** [comment]
Changing the type to be long seems a good idea, or we may suffer this bounds issue in furture.:)
if we simply want avoid this error ,we can set the value to the max int value when user set this config greater than the max int value,

**Pull request closed without merging**
