### PR TITLE
[SPARK-36820][SQL] Disable tests related to LZ4 for Hadoop 2.7 profile

### PR DESCRIPTION
**Pull request by sunchao**
### What changes were proposed in this pull request?

Disable tests related to LZ4 in `FileSourceCodecSuite`, `FileSuite` and `ParquetCompressionCodecPrecedenceSuite` when using `hadoop-2.7` profile.
### Why are the changes needed?

At the moment, parquet-mr uses LZ4 compression codec provided by Hadoop, and only since HADOOP-17292 (in 3.3.1/3.4.0) the latter added `lz4-java` to remove the restriction that the codec can only be run with native library. As consequence, the test will fail when using `hadoop-2.7` profile.

### Does this PR introduce _any_ user-facing change?

No, it's just test.

### How was this patch tested?

Existing test

### CODE REVIEW

**Comment by sunchao** [comment]
Optionally perhaps we can install lz4 in Spark CI to make this pass, but it may be tricky for the Jenkins pipelines.

**Comment by sunchao** [comment]
cc @viirya @dongjoon-hyun @gengliangwang

**Review by viirya — APPROVED** [review]

**Comment by mridulm** [comment]
I am not sure if this Suite is also having issues with hadoop-2.7 profile; but the issue I had observed was in FileSuite in core.
Full failure message:
```
- SequenceFile (compressed) - lz4 *** FAILED ***
  org.apache.spark.SparkException: Job aborted.
  at org.apache.spark.internal.io.SparkHadoopWriter$.write(SparkHadoopWriter.scala:106)
  at org.apache.spark.rdd.PairRDDFunctions.$anonfun$saveAsHadoopDataset$1(PairRDDFunctions.scala:1090)
  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
  at org.apache.spark.rdd.RDD.withScope(RDD.scala:414)
  at org.apache.spark.rdd.PairRDDFunctions.saveAsHadoopDataset(PairRDDFunctions.scala:1088)
  at org.apache.spark.rdd.PairRDDFunctions.$anonfun$saveAsHadoopFile$4(PairRDDFunctions.scala:1061)
  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  ...
  Cause: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 1.0 failed 1 times, most recent failure: Lost task 0.0 in stage 1.0 (TID 1) (localhost executor driver): java.lang.RuntimeException: native lz4 library not available
        at org.apache.hadoop.io.compress.Lz4Codec.getCompressorType(Lz4Codec.java:125)
        at org.apache.hadoop.io.compress.CodecPool.getCompressor(CodecPool.java:150)
        at org.apache.hadoop.io.compress.CodecPool.getCompressor(CodecPool.java:168)
        at org.apache.hadoop.io.SequenceFile$Writer.init(SequenceFile.java:1263)
        at org.apache.hadoop.io.SequenceFile$Writer.<init>(SequenceFile.java:1156)
        at org.apache.hadoop.io.SequenceFile$BlockCompressWriter.<init>(SequenceFile.java:1511)
        at org.apache.hadoop.io.SequenceFile.createWriter(SequenceFile.java:277)
        at org.apache.hadoop.io.SequenceFile.createWriter(SequenceFile.java:530)
        at org.apache.hadoop.mapred.SequenceFileOutputFormat.getRecordWriter(SequenceFileOutputFormat.java:64)
        at org.apache.spark.internal.io.HadoopMapRedWriteConfigUtil.initWriter(SparkHadoopWriter.scala:238)
        at org.apache.spark.internal.io.SparkHadoopWriter$.executeTask(SparkHadoopWriter.scala:126)
        at org.apache.spark.internal.io.SparkHadoopWriter$.$anonfun$write$1(SparkHadoopWriter.scala:88)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:131)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1462)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

Driver stacktrace:
  at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2403)
  at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2352)
  at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2351)
  at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
  at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
  at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2351)
  at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1109)
  at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1109)
  at scala.Option.foreach(Option.scala:407)
  ...
  Cause: java.lang.RuntimeException: native lz4 library not available
  at org.apache.hadoop.io.compress.Lz4Codec.getCompressorType(Lz4Codec.java:125)
  at org.apache.hadoop.io.compress.CodecPool.getCompressor(CodecPool.java:150)
  at org.apache.hadoop.io.compress.CodecPool.getCompressor(CodecPool.java:168)
  at org.apache.hadoop.io.SequenceFile$Writer.init(SequenceFile.java:1263)
  at org.apache.hadoop.io.SequenceFile$Writer.<init>(SequenceFile.java:1156)
  at org.apache.hadoop.io.SequenceFile$BlockCompressWriter.<init>(SequenceFile.java:1511)
  at org.apache.hadoop.io.SequenceFile.createWriter(SequenceFile.java:277)
  at org.apache.hadoop.io.SequenceFile.createWriter(SequenceFile.java:530)
  at org.apache.hadoop.mapred.SequenceFileOutputFormat.getRecordWriter(SequenceFileOutputFormat.java:64)
  at org.apache.spark.internal.io.HadoopMapRedWriteConfigUtil.initWriter(SparkHadoopWriter.scala:238)
  ...


```

**Comment by sunchao** [comment]
Thanks @mridulm . Let me check that and update the PR

**Comment by viirya** [comment]
Oh, @sunchao I think we also need to exclude lz4 in FileSuite for hadoop 2.7 too.

**Comment by gengliangwang** [comment]
@mridulm I tried the following commands on spark-3.1.1-bin-hadoop2.7 and it failed with `java.lang.RuntimeException: native lz4 library not available`:
```
spark.sql("set spark.sql.parquet.compression.codec=lz4")
spark.range(10).write.parquet("/tmp/foo")
```

The lz4 codec test in FileSuite was added in #33940 which is not on branch-3.1

**Review by gengliangwang — APPROVED** [review]

**Comment by sunchao** [comment]
Also need to fix ParquetCompressionCodecPrecedenceSuite from #34012, which is master only.

**Comment by gengliangwang** [comment]
> Also need to fix ParquetCompressionCodecPrecedenceSuite from #34012, which is master only.

@sunchao could you open a PR against branch-3.2 as well? I would like to build RC4 today.

**Comment by sunchao** [comment]
sure let me do it now

**Comment by viirya** [comment]
Thanks! Merging to master.

**Comment by dongjoon-hyun** [comment]
+1, late LGTM. Thank you, @sunchao and all!

**Pull request closed without merging**
