### PR TITLE
[SPARK-6811] Copy SparkR lib in make-distribution.sh

### PR DESCRIPTION
**Pull request by shivaram**
This change also remove native libraries from SparkR to make sure our distribution works across platforms

Tested by building on Mac, running on Amazon Linux (CentOS), Windows VM and vice-versa (built on Linux run on Mac)

I will also test this with YARN soon and update this PR.

### CODE REVIEW

**Comment by shivaram** [comment]
cc @pwendell

**Comment by pwendell** [comment]
make-distribution changes LGTM

**Comment by shivaram** [comment]
Thanks @pwendell. I'm running the YARN test right now and will merge if that looks good.

Also cc @davies

**Comment by shivaram** [comment]
The YARN test worked out fine. I might leave this open in case @davies also has time to test this out. 
@pwendell Feel free to merge this if its getting close to another RC

**Comment by shivaram** [comment]
Tested this a bit more and I think merging this now will make it easier for others to test this.

**Comment by dragos** [comment]
@shivaram I'm getting this error when I run `make-distribution.sh`. Can't get around it. What am I missing?

```
+ mkdir -p /Volumes/Thunderbolt_SSD/dragos/workspace/Spark/dev/spark/dist/R/lib
+ cp -r /Volumes/Thunderbolt_SSD/dragos/workspace/Spark/dev/spark/R/lib/SparkR /Volumes/Thunderbolt_SSD/dragos/workspace/Spark/dev/spark/dist/R/lib
cp: /Volumes/Thunderbolt_SSD/dragos/workspace/Spark/dev/spark/R/lib/SparkR: No such file or directory
```

**Comment by shivaram** [comment]
@dragos The `R/lib/SparkR` gets created if the maven flag `-Psparkr` is passed to make-distribution.sh
However this broke backwards compatibility for users who dont need SparkR in their build -- so I've  created a hot fix for this in #6379

**Pull request closed without merging**
