### PR TITLE
[SPARK-17044][SQL] Make test files for window functions for SQLQueryTestSuite

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
## What changes were proposed in this pull request?

New `SQLQueryTestSuite` simplifies SQL testcases. This PR aims to replace `WindowQuerySuite.scala` of `sql/hive` module with `window_functions.sql` in `sql/core` module.
## How was this patch tested?

This is about refactoring test cases.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
The following things are discussed so far in #14571 .
- Minimize the verbose test table.
- Make a sharable test table.
- What to do for legacy `WindowQuerySuite.scala` in `sql/hive`.

**Comment by dongjoon-hyun** [comment]
At the first step, I moved the whole test case into here. I'm trying to minimize this while keeping the same test coverage.

**Comment by rxin** [comment]
Is this work in progress?

**Comment by dongjoon-hyun** [comment]
Yes I'm still simplifying and making shareable.

**Comment by rxin** [comment]
Thanks - would be great to label the title with WIP.

**Comment by dongjoon-hyun** [comment]
Yep, I changed the title.

**Comment by dongjoon-hyun** [comment]
Hi, @rxin .
Now, it's less verbose but has the same content and result.
Could you review this?

**Comment by dongjoon-hyun** [comment]
What I wanted additionally here is to remove the legacy safely. You can compare the result with the one of the legacy test suite side by side.

**Comment by dongjoon-hyun** [comment]
Hi, @rxin .
If you think the direction of PR is not appropriate to your initial intention, please let me know.

**Comment by dongjoon-hyun** [comment]
Hi, @rxin .
For `window_function.sql`, could you review again when you have some time?

**Comment by rxin** [comment]
@dongjoon-hyun I understand that the existing test didn't set a great standard, but can you look at the data and query and come up with something a lot shorter? The problem with the current cases is that they are very large, and actually very difficult for somebody to eyeball and figure out whether the result is correct or not.

**Comment by dongjoon-hyun** [comment]
I see what is your point. Then, I'll make a new one without consideration `WindowQuerySuite.scala`. Thank you for guidance, @rxin !

**Comment by dongjoon-hyun** [comment]
Hi, @rxin . 
Could you review this second try for `window_function.sql`? I simplified the test for our eyeballs.

**Comment by rxin** [comment]
Thanks - this is much better!

**Comment by dongjoon-hyun** [comment]
Great! Thank you, @rxin .
Please give me advice about what you want to improve more. I will improve in this direction.

**Comment by dongjoon-hyun** [comment]
Hi, @rxin .
Could you review this PR again?

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by dongjoon-hyun** [comment]
Regenerate the answer set.

**Comment by dongjoon-hyun** [comment]
Hi, @rxin .
Do you think Apache Spark needs `window_functions.sql` in `SQLQueryTestSuite`?

**Comment by dongjoon-hyun** [comment]
The issue is closed as 'LATER'. We can reopen the issue and the PR later if needed.

**Pull request closed without merging**
