### PR TITLE
[SPARK-32490][BUILD] Upgrade netty-all to 4.1.51.Final

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This PR aims to bring the bug fixes from the latest netty version.

### Why are the changes needed?
- 4.1.48.Final: [https://github.com/netty/netty/milestone/223?closed=1](https://github.com/netty/netty/milestone/223?closed=1)(14 patches or issues)
- 4.1.49.Final: [https://github.com/netty/netty/milestone/224?closed=1](https://github.com/netty/netty/milestone/224?closed=1)(48 patches or issues)
- 4.1.50.Final: [https://github.com/netty/netty/milestone/225?closed=1](https://github.com/netty/netty/milestone/225?closed=1)(38 patches or issues)
- 4.1.51.Final: [https://github.com/netty/netty/milestone/226?closed=1](https://github.com/netty/netty/milestone/226?closed=1)(53 patches or issues)

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass the Jenkins with the existing tests.

### CODE REVIEW

**Comment by srowen** [comment]
Sounds fine, if it doesn't introduce behavior changes or anything.

**Comment by srowen** [comment]
Jenkins test this please

**Comment by HyukjinKwon** [comment]
ok to test

**Comment by HyukjinKwon** [comment]
@LuciferYang, can you sync and rebase? then the tests should pass in GitHub Actions.

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by kiszk** [comment]
retest this please

**Comment by maropu** [comment]
retest this please

**Review by maropu — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @LuciferYang and all.
Merged to master. The Jenkins passed.

GitHub Action failure is irrelevant to this one. It failed with R installation again.

**Comment by LuciferYang** [comment]
thx @dongjoon-hyun @maropu @HyukjinKwon @srowen , I'm very sorry that I've been busy with other things these days and haven't paid attention to this ...

**Comment by odidev** [comment]
Hi,

Netty is upgraded to 4.1.51.Final by this PR, but it is not released in latest spark artifact on [maven repo.](https://mvnrepository.com/artifact/org.apache.spark/spark-core_2.12/3.0.1)
Can someone please confirm.

**Comment by srowen** [comment]
This was merged to Spark 3.1.0, not 3.0.1. Spark 3.1 is not released.
You can see that in the merge commit: https://github.com/apache/spark/commit/0693d8bbf2942ab96ffe705ef0fc3fe4b0d9ec11

**Pull request closed without merging**
