### PR TITLE
[SPARK-39576][INFRA] Support GitHub Actions generate benchmark results using Scala 2.13

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr aims let `benchmark` GitHub Actions support the specified Scala version, then it can produce benchmark results using Scala 2.13.

### Why are the changes needed?
Help us check the microbenchmark results using Scala 2.13 and ensure they are not slower than using Scala 2.12

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?

- Pass Github Actions
-

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]
LGTM if it works

**Comment by LuciferYang** [comment]
https://github.com/LuciferYang/spark/actions/runs/2554277213

Testing it , it seems work

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Yes, it looks like working. Thank you, @LuciferYang and @HyukjinKwon 
Merged to master.

**Comment by LuciferYang** [comment]
thanks all

**Pull request closed without merging**
