### PR TITLE
[SPARK-7194][MLLIB] Vectors factors method for sparse vectors should accept the output of zipWithIndex

### PR DESCRIPTION
**Pull request by kaka1992**
Add a new Vectors.sparse(arr: Array[Double])

### CODE REVIEW

**Comment by mengxr** [comment]
@kaka1992 I don't see why this is useful. Creating a dense vector directly is certainly more efficient.

**Comment by kaka1992** [comment]
@mengxr Just provide a way to turn DeseV to SparseV easily. Somebody may need this.

**Comment by mengxr** [comment]
See #5756. Users should be able to write `Vectors.dense(1.0, 0.0, 3.0).toSparse`.

**Comment by kaka1992** [comment]
Ok, I'll close this pr.

**Comment by srowen** [comment]
@kaka1992 this wasn't quite the proposal in the JIRA anyway; it had to do with accepting either order of tuple.

**Pull request closed without merging**
