### PR TITLE
[MINOR][DOCS] Fix documentation for `spark.sql.legacy.doLooseUpcast` in SQL migration guide

### PR DESCRIPTION
**Pull request by amytsai-stripe**
### What changes were proposed in this pull request?

Fixes an error in the SQL migration guide documentation for `spark.sql.legacy.doLooseUpcast`. I corrected the config name and moved it to the section for migration from Spark 2.4 to 3.0 since it was not made available until Spark 3.0.

### Why are the changes needed?

The config was documented as `spark.sql.legacy.looseUpcast` and is inaccurately included in the Spark 2.4 to Spark 2.4.1 section.

I changed the docs to match what is implemented in https://github.com/apache/spark/blob/20df062d85e80422a55afae80ddbf2060f26516c/sql/catalyst/src/main/scala/org/apache/spark/sql/internal/SQLConf.scala#L3873

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Docs only change

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Review by MaxGekk — COMMENTED** [review]
You modified the item in the section `Upgrading from Spark SQL 2.4 to 2.4.1`. Does the version `2.4.1` have the config?

**Review by HyukjinKwon — APPROVED** [review]

**Comment by MaxGekk** [comment]
> @MaxGekk I updated this PR to also move the note to the Spark 2.4 to Spark 3.0 section!

@amytsai-stripe Could you update PR's description, please.

**Comment by amytsai-stripe** [comment]
> > @MaxGekk I updated this PR to also move the note to the Spark 2.4 to Spark 3.0 section!
> 
> @amytsai-stripe Could you update PR's description, please.

@MaxGekk  done!

**Review by MaxGekk — APPROVED** [review]

**Comment by MaxGekk** [comment]
+1, LGTM. Merging to master.
Thank you, @amytsai-stripe and @HyukjinKwon @dongjoon-hyun for review.

**Pull request closed without merging**
