### PR TITLE
Refactor Utils class to create ShutdownHookManager

### PR DESCRIPTION
**Pull request by michellemay**
Branch: master

Fix issue with log4j being initialized too early.  Custom spark class loader is not set on thread context preventing the use of custom appenders and layout engines in log4j.properties.

As discussed here:
http://apache-spark-user-list.1001560.n3.nabble.com/log4j-custom-appender-ClassNotFoundException-with-spark-1-4-1-tt24159.html

### CODE REVIEW

**Comment by srowen** [comment]
I think that message did not actually post to the list. Backing up, it's best to follow the process in https://cwiki.apache.org/confluence/display/SPARK/Contributing+to+Spark and describe your problem (discussing on user@ first, yes) and then JIRA and then a PR explaining the solution. I like the refactoring just for its own sake but why does it resolve a class loading problem? I am not sure it would make this see your custom appender -- does it seem to?

**Comment by michellemay** [comment]
As I explain, the problem arise when log4j gets initialized before MutableURLClassLoader gets set on the thread context by spark in the main method.

When parsing arguments, ShutdownManager is statically initialized by a call to addShutdownHook in the Utils class.  This trigger an initialization of log4j.  When moving shutdown hook things to a separate class, it gets lazily initialized later on.

**Comment by srowen** [comment]
Yes, that makes some sense. But you'll need to make a JIRA here.

**Comment by michellemay** [comment]
https://issues.apache.org/jira/browse/SPARK-9826

**Comment by michellemay** [comment]
Should I redo my PR ?

**Comment by srowen** [comment]
@michellemay did you have a look at the wiki there? there's a process for opening a JIRA and PR. You'll need to update the PR title for example.

**Comment by michellemay** [comment]
ok.. lets start over ;)
I'm closing this PR and following the spark contribution process

**Comment by srowen** [comment]
OK, you can edit the title of a PR and push extra changes to it without closing it, but whatever's easiest.

**Pull request closed without merging**
