### PR TITLE
[SPARK-8765] [MLLIB] [PYTHON] removed flaky python PIC test

### PR DESCRIPTION
**Pull request by jkbradley**
See failure: [https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/36133/console]

CC @yanboliang  @mengxr

### CODE REVIEW

**Comment by mengxr** [comment]
LGTM. We haven't seen any failure from the Scala unit tests. It is strange to see indeterministic behavior here. @yanboliang Could you copy one example from Scala unit tests to Python and run it multiple times? Btw, when you update the PR, please move the code example from `PICModel` to `PIC`, since users usually start with `PIC`.

**Comment by jkbradley** [comment]
@mengxr About the code example being in PICModel vs. PIC, that is actually following existing examples.  Almost all code examples are in the models, rather than in the algorithms.  I'd support moving those examples to the algorithms instead, though, since I agree that makes more sense.

**Comment by mengxr** [comment]
Merged into master. I left the JIRA open.

**Comment by yanboliang** [comment]
@mengxr @jkbradley I have found the test failure caused by the small dataset. If the dataset is small, PowerIterationClustering will behavior indeterministic. I have submit #7177 to solve this problem.
About moving code example from models to algorithms, I think a following JIRA and PR to moving all the code examples is better.

**Pull request closed without merging**
