### PR TITLE
[SPARK-12859] [Streaming] [Web UI] Names of input streams with receivers don't fit in Streaming page

### PR DESCRIPTION
**Pull request by ajbozarth**
Added CSS style to force names of input streams with receivers to wrap

### CODE REVIEW

**Comment by holdenk** [comment]
code wise this looks fine, do we have before/after screen shots handy?

**Comment by ajbozarth** [comment]
screen shot 2016-01-21 at 4 06 59 pm

**Comment by sarutak** [comment]
LGTM but could you paste a **before** screen shot just in case.

**Comment by ajbozarth** [comment]
Before image copied from the jira 
spark-streaming-webui-names-too-long-to-fit

**Comment by holdenk** [comment]
LGTM

**Comment by sarutak** [comment]
O.K, Merging this into `master` and `branch-1.6`. Thanks @ajbozarth !

**Pull request closed without merging**
