### PR TITLE
[SPARK-5722][SQL] fix for infer long type in python similar to Java long (branch-1.3)

### PR DESCRIPTION
**Pull request by dondrake**
This is the same fix applied on branch-1.2 now applied on branch-1.3.

### CODE REVIEW

**Comment by srowen** [comment]
ok to test

**Comment by srowen** [comment]
ok to test

**Comment by rxin** [comment]
Is this PR needed? https://github.com/apache/spark/pull/4521/files

We can just merge #4521 into branch-1.3.

**Comment by dondrake** [comment]
It wasn't entirely clear to me if #4521 contained commits for both branches.  If it does, then this is not needed.

**Comment by rxin** [comment]
Yea don't worry about this PR. Our merge script can just merge it into both master and branch-1.3. You can close this one now. Thanks!

**Comment by dondrake** [comment]
Closing per @rxin suggestion.

**Pull request closed without merging**
