### PR TITLE
 [MINOR][DOCS] fix typo for docs,log message and comments

### PR DESCRIPTION
**Pull request by brandonJY**
### What changes were proposed in this pull request?
Fix typo for docs, log messages and comments

### Why are the changes needed?
typo fix to increase readability 

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
manual test has been performed to test the updated

### CODE REVIEW

**Comment by maropu** [comment]
Thanks for the update, @brandonJY. Have you run a typo checker under `/docs`? I think all the exsiting  typos should be fixed in a single PR.

**Comment by brandonJY** [comment]
> Thanks for the update, @brandonJY. Have you run a typo checker under `/docs`? I think all the exsiting typos should be fixed in a single PR.

@maropu Yes. I have run a spell checker under `/docs`. This is all I found.

**Comment by maropu** [comment]
> There is also a simliar PR (#29443) trying to fix typo in code comments. But that one can be a different PR? Since it touches the codebase.

Which PR? That's the link to this PR though.

**Comment by brandonJY** [comment]
> > There is also a simliar PR (#29443) trying to fix typo in code comments. But that one can be a different PR? Since it touches the codebase.
> 
> Which PR? That's the link to this PR though.

Ah Sorry. My bad. Was referring to https://github.com/apache/spark/pull/29444

**Comment by maropu** [comment]
Ah, I see. I've check the other PR and are only three typos in the codebase?

**Comment by brandonJY** [comment]
> Ah, I see. I've check the other PR and are only three typos in the codebase?

no. For the codebase typo, that is not the complete list. It might result mass merge conflict to other PRs ?

**Comment by HyukjinKwon** [comment]
Let's just fold this and https://github.com/apache/spark/pull/29444, @brandonJY.

**Comment by HyukjinKwon** [comment]
ok to test

**Comment by srowen** [comment]
Yep I'd just merge these into one PR either way.

**Comment by srowen** [comment]
@brandonJY can you merge these PRs and make any additional changes that you see fit?

**Review by srowen — CHANGES_REQUESTED** [review]

**Pull request closed without merging**
