### PR TITLE
[SPARK-29427][SQL] Create KeyValueGroupedDataset from existing columns in DataFrame

### PR DESCRIPTION
**Pull request by viirya**
### What changes were proposed in this pull request?

This PR proposes to add groupByRelationKey API to Dataset. It creates KeyValueGroupedDataset instance using existing relational columns, instead of a typed function in groupByKey API. Because it leverages existing columns, it can use existing data partition, if any, when doing operations like cogroup.

### Why are the changes needed?

Currently if users want to do cogroup on DataFrames, there is no good way to do except for KeyValueGroupedDataset.

1. KeyValueGroupedDataset ignores existing data partition if any. That is a problem.
2. groupByKey calls typed function to create additional keys. You can not reuse existing columns, if you just need grouping by them.

```scala
// df1 and df2 are certainly partitioned and sorted.
val df1 = Seq((1, 2, 3), (2, 3, 4)).toDF("a", "b", "c")
  .repartition($"a", $"b").sortWithinPartitions("a", "b")
val df2 = Seq((1, 2, 4), (2, 3, 5)).toDF("a", "b", "c")
  .repartition($"a", $"b").sortWithinPartitions("a", "b")
```
```scala
// This groupByRelationKey won't unnecessarily repartition the data 
val df3 = df1.groupByRelationKey("a", "b")
  .cogroup(df2.groupByRelationKey("a", "b")) { case (key, data1, data2) =>
    data1.zip(data2).map { p =>
      p._1.getInt(2) + p._2.getInt(2)
    }
}
```

```
== Physical Plan ==
*(5) SerializeFromObject [input[0, int, false] AS value#11206]
+- CoGroup org.apache.spark.sql.DataFrameSuite$$Lambda$4888/206084072@4601674e, createexternalrow(a#11172, b#11173, StructField(a,IntegerType,false), StructField(b,IntegerTy
pe,false)), createexternalrow(a#11172, b#11173, c#11174, StructField(a,IntegerType,false), StructField(b,IntegerType,false), StructField(c,IntegerType,false)), createexterna
lrow(a#11188, b#11189, c#11190, StructField(a,IntegerType,false), StructField(b,IntegerType,false), StructField(c,IntegerType,false)), [a#11172, b#11173], [a#11188, b#11189]
, [a#11172, b#11173, c#11174], [a#11188, b#11189, c#11190], obj#11205: int
   :- *(2) Sort [a#11172 ASC NULLS FIRST, b#11173 ASC NULLS FIRST], false, 0
   :  +- Exchange hashpartitioning(a#11172, b#11173, 5), false, [id=#10174]
   :     +- *(1) Project [_1#11165 AS a#11172, _2#11166 AS b#11173, _3#11167 AS c#11174]
   :        +- *(1) LocalTableScan [_1#11165, _2#11166, _3#11167]
   +- *(4) Sort [a#11188 ASC NULLS FIRST, b#11189 ASC NULLS FIRST], false, 0
      +- Exchange hashpartitioning(a#11188, b#11189, 5), false, [id=#10179]
         +- *(3) Project [_1#11181 AS a#11188, _2#11182 AS b#11189, _3#11183 AS c#11190]
            +- *(3) LocalTableScan [_1#11181, _2#11182, _3#11183]
```

```scala
// Current approach creates additional AppendColumns and repartition data again
df1.groupByKey(r => r.getInt(0)).cogroup(df2.groupByKey(r => r.getInt(0))) {                                                                                 
  case (key, data1, data2) =>
    data1.zip(data2).map { p =>
      p._1.getInt(2) + p._2.getInt(2)
    }
}
```

```
== Physical Plan ==
*(7) SerializeFromObject [input[0, int, false] AS value#11216]
+- CoGroup org.apache.spark.sql.DataFrameSuite$$Lambda$4892/905560656@19f7e6c5, value#11211: int, createexternalrow(a#11172, b#11173, c#11174, StructField(a,IntegerType,false), StructField(b,IntegerType,false), StructField(c,IntegerType,false)), createexternalrow(a#11188, b#11189, c#11190, StructField(a,IntegerType,false), StructField(b,IntegerType,false), StructField(c,IntegerType,false)), [value#11211], [value#11213], [a#11172, b#11173, c#11174], [a#11188, b#11189, c#11190], obj#11215: int                      
   :- *(3) Sort [value#11211 ASC NULLS FIRST], false, 0
   :  +- Exchange hashpartitioning(value#11211, 5), true, [id=#10442]
   :     +- AppendColumns org.apache.spark.sql.DataFrameSuite$$Lambda$4889/2021090091@6396e053, createexternalrow(a#11172, b#11173, c#11174, StructField(a,IntegerType,false), StructField(b,IntegerType,false), StructField(c,IntegerType,false)), [input[0, int, false] AS value#11211]                                                                
   :        +- *(2) Sort [a#11172 ASC NULLS FIRST, b#11173 ASC NULLS FIRST], false, 0
   :           +- Exchange hashpartitioning(a#11172, b#11173, 5), false, [id=#10437]
   :              +- *(1) Project [_1#11165 AS a#11172, _2#11166 AS b#11173, _3#11167 AS c#11174]                                                                           
   :                 +- *(1) LocalTableScan [_1#11165, _2#11166, _3#11167]
   +- *(6) Sort [value#11213 ASC NULLS FIRST], false, 0
      +- Exchange hashpartitioning(value#11213, 5), true, [id=#10452]
         +- AppendColumns org.apache.spark.sql.DataFrameSuite$$Lambda$4891/1736834504@798dbf14, createexternalrow(a#11188, b#11189, c#11190, StructField(a,IntegerType,false), StructField(b,IntegerType,false), StructField(c,IntegerType,false)), [input[0, int, false] AS value#11213]                                                                
            +- *(5) Sort [a#11188 ASC NULLS FIRST, b#11189 ASC NULLS FIRST], false, 0
               +- Exchange hashpartitioning(a#11188, b#11189, 5), false, [id=#10447]
                  +- *(4) Project [_1#11181 AS a#11188, _2#11182 AS b#11189, _3#11183 AS c#11190]                                                                           
                     +- *(4) LocalTableScan [_1#11181, _2#11182, _3#11183]
```

### Does this PR introduce any user-facing change?

Yes, this adds a new groupByRelationKey API to Dataset.

### How was this patch tested?

Unit test.

### CODE REVIEW

**Comment by hagerf** [comment]
Thank you for creating a MR so fast after my submitting the jira ticket! 👍

**Review by hagerf — CHANGES_REQUESTED** [review]

**Comment by viirya** [comment]
@hagerf Thanks for the PR. Your test can not be compiled. I will make needed change later.

**Comment by viirya** [comment]
cc @cloud-fan @HyukjinKwon @dongjoon-hyun Please take a look, what do you think about this idea?

**Comment by hagerf** [comment]
@viirya Oops, sorry. Thanks for the fix!

**Comment by hagerf** [comment]
So, could someone maybe review these changes? They seems to be pretty minor but would be very helpful IMHO

**Comment by HyukjinKwon** [comment]
To me, adding a new API seems a bit overkill to handle rather corner case TBH.

**Comment by viirya** [comment]
if so, let me close this for now.

**Comment by viirya** [comment]
thanks @HyukjinKwon

**Comment by hagerf** [comment]
I don't understand why this would be considered a corner case. I've seen multiple people requesting similar features online. When working with huge data sources often regular joins simply are not performant enough so we are forced to use cogroup on `KeyValueGroupedDataset` (or RDDs). But that the only way to create them is by using inefficient groupByKey with a "cataylst-invisible" function has a significant performance hit.

@HyukjinKwon What about renaming the method to `groupByKey` so that we don't have a new function-name for it? That way we don't have a new API for it, but will be able to use the power of `KeyValueGroupedDataset` without having to compromise with unnecessary shuffling.
@viirya I have added a PR with this renaming, to make it easy.

Again, I want to say that this is a real use-case and daily I'm wasting resources because of this, so it would be very helpful. 
Thanks a lot everyone  🙂

**Comment by HyukjinKwon** [comment]
@hagerf, I would link stackoverflow, JIRA, dev or user mailing lists to show this is requested multiple times.

Current API sounds to me like new API to optimize one case to reuse existing columns to get rid of extra shuffle. Workaround seems easy anyway:

```scala
    val colNames: Seq[String] = col1 +: cols
    val keyAttrs = colNames.map(colName => resolve(colName).toAttribute)
    val keySchema = StructType.fromAttributes(keyAttrs)
    val keyEncoder = RowEncoder(keySchema)
    new KeyValueGroupedDataset(
      keyEncoder,
      encoder,
      queryExecution,
      logicalPlan.output,
      keyAttrs)
```

**Comment by cloud-fan** [comment]
shall we add `cogroup` to `RelationalGroupedDataset`?

**Comment by cloud-fan** [comment]
> When working with huge data sources often regular joins simply are not performant enough

Do we have more details? bucketed join should be as performant as cogroup

**Comment by hagerf** [comment]
Ok, I understand your point, and you're actually right that what I'm probably wanting is an API change (or extension rather). Let me explain why. 

The method `groupByKey` signals that you what to create some structure which is grouped by some key i.e. you want to get a `KeyValueGroupedDataset`. If you use `groupBy` you want a `RelationalGroupedDataset` etc etc. Now, my issue is that currently the only way for a user to get his hands on a `KeyValueGroupedDataset` is to use the method `groupByKey` which takes a function `func: T => K`. Why shouldn't I be able to pass just some columns, or column-names and get a `KeyValueGroupedDataset`? I'm betting the majority of use cases are just key-grouping by some columns, like in almost all my cases I've encountered professionally. Why limit it to a function that takes no regard to the partitioning and always shuffles? Adding this method (I would prefer calling it `groupByKey` but taking `Seq[String]`) would naturally extend the API to cover a common use case which at the same time may prevent expensive shuffling.

I have seen many people googling "cogroup for dataframes" look below at some example links, because the API currently is a bit unclear. If I wanted to do `cogroup` for dataframes of course I could do `.groupByKey(_.getLong(3))` or something similar, but with these changes I could instead just write `.groupByKey("id")` and then automatically avoid any extra shuffling if the DF was already partitioned by id.

https://stackoverflow.com/questions/36513574/cogroup-on-spark-dataframes
http://apache-spark-developers-list.1001551.n3.nabble.com/Thoughts-on-dataframe-cogroup-td26463.html

@HyukjinKwon I don't really understand how the code you wrote would work as a work around. The constructor for `KeyGroupedDataset` is private  along with the encoders etc. If you have some work around that I could use to get it working that would be awsome.

**Comment by hagerf** [comment]
@cloud-fan In my cases I'm joining multi-terabyte DFs with each other, but I'm just interested in a subset of the combinations. Using `cogroup` gives me the power to do some special logic, e.g. sorting, binary searches etc. to generate just the tuples I need. From doing joining to cogrouping made an immense difference.

**Comment by HyukjinKwon** [comment]
@hagerf pandas UDF for cogroup was added in Spark 3.0 and that thread is basically about that. This new particular API seems not requested multiple times to resolve this particular case. You could use reflection though to access private constructor. In fact its package level private so you can mimic the package structure to access as well.

**Comment by hagerf** [comment]
@HyukjinKwon The first link is not about Pandas, but ok, I just did a quick google.

So basically the only way to get this PR merged is if enough people request it? I thought I made some good and valid points and with real use cases. The vast majority of people just use regular joins so obviously this is not the common case, but I still think it makes sense, and is a minor addition.

If this isn't merged or even planned to be merged I'll probably have to create some a package called `org.apache.spark.sql`, but it obviously is a hack to go around a flaw or missing feature in Spark. Reflection is bad practice, so that is out of the question.

Anyway, thanks for looking at it.

**Comment by cloud-fan** [comment]
The `dataframe cogroup` sounds like a valid use case, but not sure how to express it in SQL. Have you tried to do `df.repartition(numPartitions, $"key").rdd` and cogroup the RDD?

**Comment by cloud-fan** [comment]
another option might be to have an API to convert `RelationalGroupedDataset` to `KeyValueGroupedDataset`, something like `df.groupBy('key).as[KeyType].cogroup`

**Comment by hagerf** [comment]
@cloud-fan yes. My first idea was to convert `RelationalGroupedDataset` to `KeyValueGroupedDataset`. But @viirya was super fast in creating this PR, and the changes seemed to be very small, so I thought maybe this would be easier?

I think `df.groupByKey("key").keyAs[String].cogroup(...` is fairly easy to understand as well. I don't really mind which solution, but that the only way to create `KeyValueGroupedDataset` is through a function is unnecessarily limiting.

**Comment by viirya** [comment]
`groupBy` can be specified with multiple grouping expressions, I think the key type should be `Row`? Otherwise I am not sure what the key type can be for `df.groupBy("a", "b", "c")`.

**Comment by cloud-fan** [comment]
> what the key type can be for df.groupBy("a", "b", "c")

It can be a case class. I think this should be similar to `df.as[T]`. We can always find a java type to match a certain schema.

**Comment by viirya** [comment]
So value type of converted `KeyValueGroupedDataset` is always `Row`?

**Comment by hagerf** [comment]
I think that would be fine. Then one can use `keyAs[T]` as I did above.

**Comment by viirya** [comment]
I see. So in some cases, users can specify custom case class for key type. How about value type?

**Comment by hagerf** [comment]
Oh, you mean converting from converting a  `RelationalGroupedDataset` to `KeyValueGroupedDataset`? Right now there is no functionality for the value type. That has to be added then.

**Comment by hagerf** [comment]
That is one of the reasons I like this PR. It would be automatic, you just need to convert the key type.

**Comment by viirya** [comment]
Yea, I currently try to create api for `df.groupByKey("key").keyAs`, so a few questions come out.

**Comment by hagerf** [comment]
I think just renaming the method as I did in the PR to this branch should be enough or?

**Comment by cloud-fan** [comment]
an options is to let `RelationalGroupedDataset` take `Datase` not `DataFrame`, then we can keep the value type information.

**Pull request closed without merging**
