### PR TITLE
[SPARK-47610][CONNECT][FOLLOWUP] Add -Dio.netty.tryReflectionSetAccessible=true for spark-connect-scala-client

### PR DESCRIPTION
**Pull request by pan3793**
### What changes were proposed in this pull request?

Add `-Dio.netty.tryReflectionSetAccessible=true` for `spark-connect-scala-client`

### Why are the changes needed?

The previous change missed spark-connect-scala-client, may be due to bad IDEA index.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass GA

### Was this patch authored or co-authored using generative AI tooling?

No

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Could you re-trigger the failed test pipeline, @pan3793 ?

**Review by HyukjinKwon — APPROVED** [review]
LGTM pending CI

**Comment by pan3793** [comment]
@dongjoon-hyun @HyukjinKwon thanks, CI is green now

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @pan3793 .
Merged to master.

**Pull request closed without merging**
