### PR TITLE
[SPARK-13825][CORE] Upgrade to Scala 2.11.8

### PR DESCRIPTION
**Pull request by jaceklaskowski**
## What changes were proposed in this pull request?

Upgrade to 2.11.8 (from the current 2.11.7)
## How was this patch tested?

A manual build

### CODE REVIEW

**Comment by srowen** [comment]
Jenkins test this please

**Comment by srowen** [comment]
This is OK for 2.x of course, and 1.6.x too I think. It's just  a bug release, and the 2.11 build is the secondary one for 1.6 anyway, so slightly lower risk in any event.

**Comment by JoshRosen** [comment]
Hey @jaceklaskowski, you should run `./dev/test-dependencies.sh --replace-manifest` and commit the result in order to get the dependency tests to pass.

**Comment by jaceklaskowski** [comment]
@srowen Mind triggering a test? Thanks!

**Comment by srowen** [comment]
Jenkins test this please

**Comment by srowen** [comment]
(Copying part of my email) This fails because we don't have the fork of genjavadoc compiled for Spark 2.11.8.

We can see the org.spark-project packages here:

http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.spark-project%22

I've forgotten who maintains the custom fork builds, and I don't know
the reasons we needed a fork of genjavadoc. Is it still relevant?

Heh, there's no plugin for 2.11.8 from the upstream project either anyway:
http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.typesafe.genjavadoc%22

This may be blocked for now

**Comment by srowen** [comment]
@mengxr is it possible to generate these plugins one more time for Scala 2.11.8 and 2.10.6? Maybe it's the last time we need to.
(Upstream now has plugins for 2.11.8/2.10.6)

**Comment by mengxr** [comment]
I will do a cross build and @brkyvz will help publish the jars. cc: @jodersky

**Comment by brkyvz** [comment]
@mengxr @srowen @jaceklaskowski Jars are now published. They should be available in a couple of hours if not already.

**Comment by srowen** [comment]
Jenkins retest this please

**Comment by srowen** [comment]
Thanks @brkyvz -- it doesn't look like it pushed yet but maybe there's a delay. I can check again in a few days. http://search.maven.org/#search%7Cga%7C1%7Corg.spark-project%20genjavadoc

**Comment by srowen** [comment]
@brkyvz @mengxr it looks like the artifacts haven't pushed. Is it possible to double-check what happened there?

**Comment by brkyvz** [comment]
@srowen I realized that I forgot to push the `release` button :( They've been available under staging repositories at:
https://oss.sonatype.org/content/repositories/orgspark-project-1119 and
https://oss.sonatype.org/content/repositories/orgspark-project-1120

very sorry for the delay

**Comment by srowen** [comment]
Ha yeah I've done that before in Sonatype.

**Comment by srowen** [comment]
Jenkins retest this please

**Comment by jodersky** [comment]
FYI, I have two PRs pending to get the genjavadoc changes merged into upstream. I haven't had any feedback yet so if anyone wants to have a look please do typesafehub/genjavadoc#70 typesafehub/genjavadoc#71

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
