### PR TITLE
[SPARK-15555] [Mesos] Driver with --supervise option cannot be killed in Mesos mode

### PR DESCRIPTION
**Pull request by devaraj-kavali**
## What changes were proposed in this pull request?

Not adding the Killed applications for retry.
## How was this patch tested?

I have verified manually in the Mesos cluster, with the changes the killed applications move to Finished Drivers section and will not retry.

### CODE REVIEW

**Comment by tnachen** [comment]
Nice catch, can you add a unit test to test this?

**Comment by tnachen** [comment]
ok to test

**Comment by tnachen** [comment]
Thanks @devaraj-kavali, this LGTM. @andrewor14 can you take a look?

**Comment by vanzin** [comment]
@devaraj-kavali do you mind fixing the conflicts?

**Comment by vanzin** [comment]
Merging to master.

**Pull request closed without merging**
