### PR TITLE
minor doc fix for Row.scala

### PR DESCRIPTION
**Pull request by david-weiluo-ren**
## What changes were proposed in this pull request?

minor doc fix for "getAnyValAs" in class Row
## How was this patch tested?

None. 

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by rxin** [comment]
Jenkins, test this please.

**Comment by rxin** [comment]
LGTM

**Comment by rxin** [comment]
Merging in master/branch-2.0.

**Comment by srowen** [comment]
BTW this was intended to be connected to https://issues.apache.org/jira/browse/SPARK-17883

**Pull request closed without merging**
