### PR TITLE
[SPARK-42318][SPARK-42319][SQL] Assign name to _LEGACY_ERROR_TEMP_(2123|2125)

### PR DESCRIPTION
**Pull request by itholic**
### What changes were proposed in this pull request?

This PR proposes to assign name to _LEGACY_ERROR_TEMP_2123 and _LEGACY_ERROR_TEMP_2125, "CANNOT_MERGE_INCOMPATIBLE_DATA_TYPE".

### Why are the changes needed?

We should assign proper name to _LEGACY_ERROR_TEMP_*

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

`./build/sbt "sql/testOnly org.apache.spark.sql.SQLQueryTestSuite*`

### CODE REVIEW

**Comment by itholic** [comment]
cc @srielau @MaxGekk @cloud-fan Could you review this error class ticket when you find some time 🙏

**Review by srielau — COMMENTED** [review]
Can you explain when this error is being raised?
It seems to be related to a data source?
MERGE is a SQL Statement, so the term is very confusing.
Also there is no action associated or any other context.

**Comment by itholic** [comment]
> MERGE is a SQL Statement, so the term is very confusing.

I agree with that.
Actually the term MERGE here means that `merge` function of `StructType` (`StructType.merge`).
So, seems like it's `StructType` specific error message.

> Can you explain when this error is being raised?

The `StructType.merge` requires two `StructType` to be merged together.
When merging the two `StructType`, it raises error if If both schemas don't match.

Btw, on my second thought,  it seems to be a private function so can't be used in user space ??
```scala
scala> StructType.merge(left, right)
<console>:29: error: method merge in object StructType cannot be accessed in object org.apache.spark.sql.types.StructType
       StructType.merge(left, right)
```
cc @MaxGekk @cloud-fan Would you confirm if we should switched this error into internal error ??

**Comment by srielau** [comment]
If it's an internal error we want to issue an XXK sqlstate. For Analysis I have created XXKD0. Would this be considered analysis?
We can also use XX000 generically.

**Comment by MaxGekk** [comment]
> cc @MaxGekk @cloud-fan Would you confirm if we should switched this error into internal error ??

Don't think so. The function invokes itself recursively to merge struct fields too. Try to reproduce the error from user space using `UNION ALL` when some nested fields are not compatible.

**Comment by itholic** [comment]
I see.
Then maybe we can keep the name as is? or anyone have some better idea for naming?
+ And I just assigned "42825" to `sqlState` and fixed the tests.

**Comment by MaxGekk** [comment]
> Then maybe we can keep the name as is?

I agree with that.

> Also just assigned "42825" to sqlState and fixed the tests.

@itholic Sure. Please, rebase on the recent master.

**Comment by itholic** [comment]
Rebased, thanks!

**Review by MaxGekk — APPROVED** [review]

**Comment by MaxGekk** [comment]
+1, LGTM. Merging to master/3.4.
Thank you, @itholic and @srielau for review.

**Pull request closed without merging**
