### PR TITLE
[SPARK-23823][SQL] ResolveReferences should preserve treenode origins

### PR DESCRIPTION
**Pull request by jiahuijiang**
## What changes were proposed in this pull request?

Fixes https://issues.apache.org/jira/browse/SPARK-23823

Introduced in apache#19585

ResolveReferences stopped doing transfromsUp after this change and Attributes sometimes lose its correct origin

## How was this patch tested?

Manually tested after this change analyze won't throw away correct Origin for columns

### CODE REVIEW

**Comment by gatorsmile** [comment]
@JiahuiJiang Did you hit any error?

**Comment by gatorsmile** [comment]
ok to test

**Comment by JiahuiJiang** [comment]
Yes, for any SQL queries with columns inside.
e.g. "create table `/targetTable` as (\nselect col1 from `/path/to/table1`\n)", after parsing the query, I got a QueryPlan where the "col1" project's origin is (2, 7). But after running analyzer.analyze on that query plan, the origin becomes (2, 0). Tested after this change it retains as (2, 7)

**Comment by gatorsmile** [comment]
retest this please

**Comment by gatorsmile** [comment]
@JiahuiJiang Why do you need to check the value of origin? This is being used for error reporting only.

**Comment by JiahuiJiang** [comment]
We are implementing a [language server](https://microsoft.github.io/language-server-protocol/) that needs to understand where the column locations, so we are depending on some of these internal APIs

**Comment by JiahuiJiang** [comment]
@gatorsmile Seems the tests are still flaking :/ 
And @robertzk proposed this fix https://github.com/JiahuiJiang/spark/pull/2 instead, where we keep the origin directly inside transformExpression, so that all the mapChildren and mapExpressions automatically have their origins kept. Is it better to take that change instead?

**Comment by JiahuiJiang** [comment]
@gatorsmile Is #20961 crazy to do? It makes sure all the origins are kept correctly after analyzing, so future refactor won't cause similar issue. But not sure whether that behavior should be expected

**Pull request closed without merging**
