### PR TITLE
[SQL][TEST] Tests using golden files can fail depending on new line characters in queries

### PR DESCRIPTION
**Pull request by sarutak**
Golden files related to tests of o.a.s.sql.hive are named like *-<md5 of query strings>. Those MD5s are generated from queries whose new line character is "LF" not "CR".
So, when we run those tests on Windows, it can fail.

### CODE REVIEW

**Comment by sarutak** [comment]
retest this please.

**Comment by JoshRosen** [comment]
Does this duplicate / overlap with #7563?

**Comment by sarutak** [comment]
@JoshRosen Ah, maybe overlap with #7563. I'll check it out. Thanks!

**Comment by marmbrus** [comment]
@sarutak thanks for working on this, but I think this is already resolved by #7563 and we can close this issue now.

**Comment by sarutak** [comment]
I see. I'll close this PR. Thanks.

**Pull request closed without merging**
