### PR TITLE
[SPARK-8652] [PYSPARK] Check return value for all uses of doctest.testmod()

### PR DESCRIPTION
**Pull request by JoshRosen**
This patch addresses a critical issue in the PySpark tests:

Several of our Python modules' `__main__` methods call `doctest.testmod()` in order to run doctests but forget to check and handle its return value. As a result, some PySpark test failures can go unnoticed because they will not fail the build.

Fortunately, there was only one test failure which was masked by this bug: a `pyspark.profiler` doctest was failing due to changes in RDD pipelining.

### CODE REVIEW

**Comment by JoshRosen** [comment]
For instance, it turns out that one of the PySpark `profiler` tests is broken and we didn't notice:

```python
Running test: pyspark.profiler ... [GC [PSYoungGen: 132096K->14805K(153600K)] 132096K->14877K(503296K), 0.0141160 secs] [Times: user=0.04 sys=0.01, real=0.01 secs]
[GC [PSYoungGen: 146901K->20583K(153600K)] 146973K->20663K(503296K), 0.0185440 secs] [Times: user=0.07 sys=0.01, real=0.02 secs]
**********************************************************************
File "/Users/joshrosen/Documents/spark/python/pyspark/profiler.py", line 93, in __main__.Profiler
Failed example:
    sc.show_profiles()
Expected:
    My custom profiles for RDD:1
    My custom profiles for RDD:2
Got:
    My custom profiles for RDD:1
**********************************************************************
   1 of   8 in __main__.Profiler
```

**Comment by JoshRosen** [comment]
Luckily, it looks like it was only that single test that was failing:

```
[joshrosen pyspark (testmod-fix)]$ git grep testmod
accumulators.py:    (failure_count, test_count) = doctest.testmod()
broadcast.py:    (failure_count, test_count) = doctest.testmod()
conf.py:    (failure_count, test_count) = doctest.testmod(optionflags=doctest.ELLIPSIS)
context.py:    (failure_count, test_count) = doctest.testmod(globs=globs, optionflags=doctest.ELLIPSIS)
heapq3.py:    (failure_count, test_count) = doctest.testmod()
ml/classification.py:    (failure_count, test_count) = doctest.testmod(
ml/evaluation.py:    (failure_count, test_count) = doctest.testmod(
ml/feature.py:    (failure_count, test_count) = doctest.testmod(globs=globs, optionflags=doctest.ELLIPSIS)
ml/recommendation.py:    (failure_count, test_count) = doctest.testmod(globs=globs, optionflags=doctest.ELLIPSIS)
ml/regression.py:    (failure_count, test_count) = doctest.testmod(globs=globs, optionflags=doctest.ELLIPSIS)
ml/tuning.py:    (failure_count, test_count) = doctest.testmod(
mllib/classification.py:    (failure_count, test_count) = doctest.testmod(globs=globs, optionflags=doctest.ELLIPSIS)
mllib/clustering.py:    (failure_count, test_count) = doctest.testmod(globs=globs, optionflags=doctest.ELLIPSIS)
mllib/evaluation.py:    (failure_count, test_count) = doctest.testmod(globs=globs, optionflags=doctest.ELLIPSIS)
mllib/feature.py:    (failure_count, test_count) = doctest.testmod(globs=globs, optionflags=doctest.ELLIPSIS)
mllib/fpm.py:    (failure_count, test_count) = doctest.testmod(globs=globs, optionflags=doctest.ELLIPSIS)
mllib/linalg.py:    (failure_count, test_count) = doctest.testmod(optionflags=doctest.ELLIPSIS)
mllib/random.py:    (failure_count, test_count) = doctest.testmod(globs=globs, optionflags=doctest.ELLIPSIS)
mllib/recommendation.py:    (failure_count, test_count) = doctest.testmod(globs=globs, optionflags=doctest.ELLIPSIS)
mllib/regression.py:    (failure_count, test_count) = doctest.testmod(globs=globs, optionflags=doctest.ELLIPSIS)
mllib/stat/_statistics.py:    (failure_count, test_count) = doctest.testmod(globs=globs, optionflags=doctest.ELLIPSIS)
mllib/tree.py:    (failure_count, test_count) = doctest.testmod(globs=globs, optionflags=doctest.ELLIPSIS)
mllib/util.py:    (failure_count, test_count) = doctest.testmod(globs=globs, optionflags=doctest.ELLIPSIS)
profiler.py:    (failure_count, test_count) = doctest.testmod()
rdd.py:    (failure_count, test_count) = doctest.testmod(
serializers.py:    (failure_count, test_count) = doctest.testmod()
shuffle.py:    (failure_count, test_count) = doctest.testmod()
sql/column.py:    (failure_count, test_count) = doctest.testmod(
sql/context.py:    (failure_count, test_count) = doctest.testmod(
sql/dataframe.py:    (failure_count, test_count) = doctest.testmod(
sql/functions.py:    (failure_count, test_count) = doctest.testmod(
sql/group.py:    (failure_count, test_count) = doctest.testmod(
sql/readwriter.py:    (failure_count, test_count) = doctest.testmod(
sql/types.py:    (failure_count, test_count) = doctest.testmod(
sql/window.py:    (failure_count, test_count) = doctest.testmod()
streaming/util.py:    (failure_count, test_count) = doctest.testmod()
```

**Comment by JoshRosen** [comment]
Found another minor issue that was masked by this:

```
**********************************************************************
File "/Users/joshrosen/Documents/spark/python/pyspark/serializers.py", line 47, in __main__
Failed example:
    rdd._jrdd.count()
Expected:
    8L
Got:
    8
**********************************************************************
   1 of  10 in __main__
```

**Comment by davies** [comment]
LGTM, thanks!

**Pull request closed without merging**
