### PR TITLE
[SPARK-22159][SQL] Make config names consistently end with "enabled".

### PR DESCRIPTION
**Pull request by rxin**
## What changes were proposed in this pull request?
spark.sql.execution.arrow.enable and spark.sql.codegen.aggregate.map.twolevel.enable -> enabled

## How was this patch tested?
N/A

### CODE REVIEW

**Review by gatorsmile — APPROVED** [review]
LGTM

**Comment by gatorsmile** [comment]
Update the PR title and description?

**Comment by rxin** [comment]
hm the 2nd commit is not meant for this one.

**Comment by rxin** [comment]
I reverted the 2nd commit. Should be good for merge now.

**Comment by gatorsmile** [comment]
Thanks! Merged to master

**Pull request closed without merging**
