### PR TITLE
[SPARK-8185][SPARK-8188][SPARK-8191][SQL]function datediff, to_utc_timestamp, from_utc_timestamp

### PR DESCRIPTION
**Pull request by davies**
This PR is based on #7643 , thanks to @adrian-wang

### CODE REVIEW

**Comment by adrian-wang** [comment]
FYI:
https://github.com/apache/hive/blob/master/ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFDateDiff.java#L73

hive are casting strings in datediff to date/timestamp in UTC timezone.

**Comment by davies** [comment]
@adrian-wang I understand you concern, our goal is to be Hive compatible at our best, not follow the implementation details in Hive.

For datediff, these expression should be have the same results:
```
select datediff('2015-05-06', '2015-05-05')
select datediff(cast('2015-05-06' as date), cast('2015-05-05' as date))
select datediff('2015-05-06 00:00:01', '2015-05-05 23:59:59')
select datediff(cast('2015-05-06 00:00:01' as timestamp), cast('2015-05-05 23:59:59' as timestamp))
```
This is the behavior in MySQL and MS SQL Server, correct me if it's not.

But in Hive, the fourth one is different, kind of silly, I think we should not follow that. We also break the compatibility already (returning different type).

**Comment by davies** [comment]
cc @yhuai @rxin

**Comment by davies** [comment]
I'm going to merge this, if there is something we could improve, could do it later.

**Comment by JasonWHowell** [comment]
Thanks for the hard work here. 

Did this land in documentation yet? I searched for it at https://spark.apache.org/docs/latest/sql-programming-guide.html but didn't find any reference yet.

Someone is asking if there is a way to extract different granularities of the time unit from Spark SQL DateDiff(). Such as milliseconds vs. days vs. months.  I suppose we could with simple division if the DateDiff returns milliseconds units, and divide by 1000 and 60 and 60 up to hours units and again by 24 up to days units.  

If we only return days units in the difference, the result would be rounded (losing hours and seconds precision) so multiplying x24x60x60 to get seconds is going to be extremely lossy.

I think folks are used to the SQL Server implementation of DateDiff (where you provide the DatePart unit), as opposed to the Hive DateDiff and MySQL implementation which seems to return only rounded day parts. https://msdn.microsoft.com/en-us/library/ms189794.aspx

Appreciate any advice, or point me to the right forum. Sorry to bother ~ Jason

**Comment by srowen** [comment]
@JasonWHowell docs go out with releases and none has occurred since this was committed, but looks like it will go in 1.5

**Pull request closed without merging**
