### PR TITLE
[SPARK-28737][CORE] Update Jersey to 2.29

### PR DESCRIPTION
**Pull request by srowen**
## What changes were proposed in this pull request?

Update Jersey to 2.27+, ideally 2.29, for possible JDK 11 fixes.

## How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by dongjoon-hyun** [comment]
Interesting, in this PR, I also saw the same 500 error failure.
- https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/109128/testReport
```
[info] UISeleniumSuite:
...
[info] - effects of unpersist() / persist() should be reflected *** FAILED *** (1 second, 120 milliseconds)
[info]   java.lang.RuntimeException: got code: 500 when getting http://amp-jenkins-worker-05.amp:38637/api/v1/applications/local-1565819875887/storage/rdd w/ error: Some(<html>
[info] <head>
[info] <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
```

cc @wangyum

**Comment by srowen** [comment]
Yep this one doesn't seem straightforward. I'll work on figuring out what's the new error on update. I feel like I tried this a while ago and ran into similar problems. It seems to be mostly that Jersey reorganized its modules and some new ones must be included.

**Comment by wangyum** [comment]
retest this please

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by srowen** [comment]
The test appeared to pass actually, but let me re-run it.

**Comment by dongjoon-hyun** [comment]
Yes. It fails at GitHub posting. It seems to be GitHub outage.
```
Tests passed.
Attempting to post to Github...
Failed to post message to Github.
 > urllib_status: Temporary failure in name resolution
 > data: {"body": "**[Test build #109205 has finished](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/109205/testReport)** for PR 25455 at commit [`57add37`](https://github.com/apache/spark/commit/57add373ba6cc95730f3f57f9e5b2deb13ab121a).\n * This patch passes all tests.\n * This patch merges cleanly.\n * This patch adds no public classes."}
```

**Comment by dongjoon-hyun** [comment]
Oops. Sorry. Although #25474 touches the same files, I thought it's okay because it touches a different part. Could you rebase once more?

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Merged to master.
Thank you, @srowen and @wangyum .

**Pull request closed without merging**
