### PR TITLE
[SPARK-37708][K8S] Provides basic images that support centos7

### PR DESCRIPTION
**Pull request by smallzhongfeng**
### What changes were proposed in this pull request?

To adapt to the production environment, CentOS 7 basic image is provided.

### Why are the changes needed?

If we compile Python on centos and run this package on K8S, I submit it this way：
`spark-submit  \
--archives s3a://zhongjingxiong/python3.6.9.tgz#python3.6 \
--conf spark.pyspark.driver.python=python3.6/bin/python3 \
--conf spark.pyspark.python=python3.6/bin/python3 \
examples/src/main/python/pi.py 10 `

We will report dependency loss.
>  Unpacking an archive s3a://zhongjingxiong/python3.6.9.tgz#python3 from /tmp/spark-0002ed81-3a01-4e40-a9b7-826295b86ece/python3.6.9.tgz to /opt/spark/work-dir/./python3
Traceback (most recent call last):
  File "/tmp/spark-0002ed81-3a01-4e40-a9b7-826295b86ece/pi.py", line 21, in <module>
    from pyspark.sql import SparkSession
  File "/opt/spark/python/lib/pyspark.zip/pyspark/__init__.py", line 121, in <module>
  File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/__init__.py", line 42, in <module>
  File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/types.py", line 27, in <module>
    async def _ag():
  File "/opt/spark/work-dir/python3/lib/python3.6/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
22/01/07 22:56:11 INFO ShutdownHookManager: Shutdown hook called

But it works fine when running on YARN. Therefore, it is better to provide an image that supports centos to run Spark.
### Does this PR introduce _any_ user-facing change?

Yes,this is a new docker file exposed to the customer.

### How was this patch tested?

It has been deployed in the production environment.

### CODE REVIEW

**Comment by bjornjorgensen** [comment]
Why do you wanna have support for CentOS 7 witch are end off live? 
In yours docker filer you are installing python 3.9.0 but here you are using spark.pyspark.driver.python=python3.6/bin/python3

**Comment by bjornjorgensen** [comment]
You have problems with ImportError: libffi.so.6
It looks like many others have the same problems like this post show. https://stackoverflow.com/questions/61875869/ubuntu-20-04-upgrade-python-missing-libffi-so-6 
In yours docker file you fix this with installing python 3.9.0

**Comment by zero323** [comment]
Sorry, but this doesn't seem like a good idea.

Even if we didn't already drop Python 3.6 support with supporting code, maintaining another set of images just for this purpose, wouldn't justify the maintenance cost. These images provide good starting point, but are by no means comprehensive ‒ if you're want to use different interpreters, virtual machines or native dependencies it makes more sense to start from scratch with your own images that fit your requirements.

**Review by zero323 — COMMENTED** [review]
Sorry, but this doesn't seem like a good idea.

Even if we didn't already drop Python 3.6 support with supporting code (see SPARK-37632 among others), maintaining another set of images just for this purpose, wouldn't justify the maintenance cost. These images provide good starting point, but are by no means comprehensive ‒ if you're want to use different interpreters, virtual machines or native dependencies it makes more sense to start from scratch with your own set of images that fit your requirements.

**Comment by HyukjinKwon** [comment]
Yeah, I doubt if we want this. cc @dongjoon-hyun @holdenk FYI

**Review by dongjoon-hyun — COMMENTED** [review]
I agree with @HyukjinKwon and @zero323 .

**Comment by Yikun** [comment]
Agree @zero323, besides, another information is [CentOS will reach EOL](https://www.centos.org/centos-linux-eol/).

But there are indeed some gaps that let users to use Spark easily with different OS, so I think some documentation or dockerfile reference might be necessary. I also heard some from local developer and customer that they need some initial dockerfile template for specific OS. Whether should we deal with these requirement appropriately?

Just some random thoughts, I think the problem is who is responsible for maintaining these doc and dockerfile the continuous evolution and quality of these codes. Perhaps a potential solution should be these scirpt provided by the OS community's SIG, the Spark community documentation link to these.

**Comment by zhongjingxiong** [comment]
Thank you for your review. In fact, this is just a suggestion, because I think a large number of machines adopt CentOS as the operating system, and switch the scheduler from yarn to k8s. The python compiled by the user in centots' operating system can not be directly migrated to k8s for direct use, because it is found that even in the testing stage, python 3 In addition, exceptions will be thrown when loading third-party packages, but they can be executed normally on yarn. We hope to reduce the time cost for users and provide an environment that can be migrated directly from yarn to k8s. Is it better?

**Comment by bjornjorgensen** [comment]
I do build and run containers on k8s with the default spark docker file. And it works, so why do you wanna have CentOS as base image?

**Comment by zero323** [comment]
@zhongjingxiong 

> The python compiled by the user in centots' operating system can not be directly migrated

The real problem here is that software build using dynamically linked libraries (like Python in your case) is really not intended to be portable. Even if you can make it work in a specific case, it is susceptible to minute changes in the OS configuration (compiling dynamically linked Python in my Debian dev sandbox and putting it in these images, wouldn't work any better than in your CentOS case). That's why we have Linux package managers in the first place. Not to mention, providing large runtime bundle from outside the image for each job is extremely wasteful.

If, for whatever reason, you need to compile your own Python version, it should be done as a part of the image building process. This way you can ensure that your images are self-contained. If, for the sake of argument, it is not possible in your case, there are utilities that are designed to create portable Python bundles ([some listed](https://spark.apache.org/docs/latest/api/python/user_guide/python_packaging.html?highlight=packages) in our official docs).

**Comment by zero323** [comment]
@Yikun 

Yeah, there is definitely some opportunity in providing Docker specific documentation, but it is topic for a longer discussion with different scope than this PR. In the past, I entertained some ideas around having configurable builders of Spark images for testing / development, and once you hit guest languages with native dependencies things quickly get out of hand if you try to manually target OS supplied libraries and predict different user requirements.

> I also heard some from local developer and customer that they need some initial dockerfile template for specific OS.

It would be interesting to learn more about the context.

**Comment by zhongjingxiong** [comment]
> I do build and run containers on k8s with the default spark docker file. And it works, so why do you wanna have CentOS as base image?
Yes, there is no problem using the default, but the problem is that if users use their own compiled python, such as I said, python compiled on CentOS operating system and run on k8s, there will be problems. You can try the example I said

**Comment by zhongjingxiong** [comment]
@zero323 In fact, can we provide mainstream operating systems as basic images for users, such as Ubuntu and CentOS, so that users can choose independently?

**Comment by zero323** [comment]
> @zero323 In fact, can we provide mainstream operating systems as basic images for users, such as Ubuntu and CentOS, so that users can choose independently?

If you want to propose such addition @zhongjingxiong,  [developers list](https://lists.apache.org/list?dev@spark.apache.org) would be the right place to do it.

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
Hi, All.

Thank you for all your inputs and discussion. 

First, I want to make it clear that `Apache Spark` community is not aiming to maintain all linux distributions' Dockerfiles in Apache Spark source code. The purpose of built-in `Dockerfile` is purely a reference model for users and to test Apache Spark itself's K8s integration tests to validate its features.

Second, Apache Spark provides `-f` option already from the beginning for your specific purpose. Like you have your code in your repository, we expect you to maintain your Dockerfile in your repository.
```
bin/docker-image-tool.sh -f
```

Third, given that there are heterogenous and various production environments, adding a new single image doesn't solve your production problems at all because it's too narrow and specific. I'm sure that you cannot use the vanilla Spark Docker image and will need to update the community `Dockerfile` again and again endlessly to match your specific SW (Java/Python/R) requirements. Let me illustrate one specific Python issue to you guys. This PR proposes to have `Python 3.9.0` like the following while it's not what the other people want in the production.

https://github.com/apache/spark/blob/969e08f5a01007ed13294fb385185ca8a1152f36/resource-managers/kubernetes/docker/src/main/dockerfiles/spark/bindings/python/Dockerfile.centos7#L29

Please note that the popular [Google Colab](https://colab.research.google.com) also stays with `Python 3.7.12` as of today because there are many 3rd library issues including machine learning. And, for non-machine-learning users also will demand Python 3.9.9 or 3.10.1 instead of Python 3.9.0 (this PR).

Finally, even in a single company, many teams inevitably maintain different Dockerfiles for their own jobs to optimize and minimize Docker image size per jobs. So, I don't think this PR has as much benefits in the production as the PR claims. Technically, having a large bandwagon Docker image for all job is a typical anti-pattern. You need to keep the optimal and minimized Docker image per job.
 
To be clear, Apache Spark community **intentionally** has been using OpenJDK images (`8`, `11`, `11-jre-slim`) to avoid the above issue. It's conceptually irrelevant to an OS distribution. The only reason why I added `FROM Debian:bullseye-slim` at #34586 is documented here. OpenJDK community switched their underlying OS from Java 12 and this was a breaking change to the downstream like us.

https://github.com/apache/spark/blob/3d229f32e9893697fda1735c664740cd8b0022cd/resource-managers/kubernetes/docker/src/main/dockerfiles/spark/Dockerfile.java17#L17-L18

**Comment by dongjoon-hyun** [comment]
For now, I'll close this PR according to the above discussion. We can continue the discussion on dev mailing list because this is a valid discussion topic, @zhongjingxiong . The devils are in the detail always. You can reopen this when all of us satisfied with the proposal.

**Comment by dongjoon-hyun** [comment]
BTW, one more thing I want to highlight in the above is `CentOS EOL`.
```
CentOS Linux 8 will reach End Of Life (EOL) on December 31st, 2021. 
```

In my perspective, if the community want to keep something in Apache Spark repository, it should be live one, not EOL one definitely.

**Comment by Yikun** [comment]
> > I also heard some from local developer and customer that they need some initial dockerfile template for specific OS.

> It would be interesting to learn more about the context.

@zero323 Yes, the discussion of these things is somewhat beyond the scope of this PR. FYI:
- I've also been involved in some work in the openEuler OS community, and I've found some OS users suffers on work that supports Spark. They hope that the OS Big Data SIG or Spark community can provide some basic references.
- Some companies have a unified OS technology stack (which may include optimizations for performance and security), usually these OSs are developed based on upstream operating systems. maybe also cc @LuciferYang 
- Some companies are required to use a specific OS for local policy reasons, so it would be useful if the community could provide an initial reference based on mainly OS.
- Besides this, I remember there are some postive info on spark website:  [we 
greatly encourage contributors who want to work on mainly on 
platform support for specific OSes etc.](https://github.com/apache/spark-website/blame/8fa58d0aebd62637fa17679a649dd91c2d5fdd7b/committers.md#L124-L126) .

**Pull request closed without merging**
