### PR TITLE
[SPARK-42956][CONNECT] Support avro functions for Scala client

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
This pr aims to support avro functions for Scala client.

### Why are the changes needed?
Add Spark connect jvm client api coverage.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?

- Add new test
- Checked Scala 2.13

### CODE REVIEW

**Comment by LuciferYang** [comment]
cc @HyukjinKwon @hvanhovell

**Review by HyukjinKwon — APPROVED** [review]

**Review by yaooqinn — APPROVED** [review]

**Comment by LuciferYang** [comment]
`avro/functions` not in sql module, so `CheckConnectJvmClientCompatibility` cannot perform mima check between `client.jar` and `avro.jar`, created SPARK-42958 to tracking this

**Comment by LuciferYang** [comment]
GA passed

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by LuciferYang** [comment]
Thanks @HyukjinKwon @yaooqinn

**Pull request closed without merging**
