### PR TITLE
[MINOR][HIVE] Typo fixes

### PR DESCRIPTION
**Pull request by jaceklaskowski**
## What changes were proposed in this pull request?

Typo fixes (with expanding a Hive property)

## How was this patch tested?

local build. Awaiting Jenkins

### CODE REVIEW

**Comment by srowen** [comment]
That's fine. As usual please have a look for more if you can.

**Comment by jaceklaskowski** [comment]
I'll try to add more typos from other modules. I didn't mean to "pollute" a minor change and make it bigger (and possibly questionable :))

**Comment by srowen** [comment]
Not sure what you mean; I think typo fixes are always logically related, and are trivial, so can easily be part of one change. For example, I skimmed with my IDE spell checker and found 40 a few weeks ago. I know there is more to do. For experienced people, we generally push back on small PRs.

**Comment by srowen** [comment]
Merged to master/2.3

**Pull request closed without merging**
