### PR TITLE
[SPARK-27700][K8S] SparkSubmit closes with SocketTimeoutException in K8s

### PR DESCRIPTION
**Pull request by Udbhav30**
## What changes were proposed in this pull request?
spark-submit closes with connection timeout exception, i have defined new configurations which can be used to set the timeouts 

## How was this patch tested?
manually

### CODE REVIEW

**Comment by Udbhav30** [comment]
cc @liyinan926

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
Hi, @Udbhav30 .
- Could you add a unit test case in your PR?
- Please use `[K8S]` in the PR title.

**Comment by vanzin** [comment]
This one looks like SPARK-27023...

**Comment by Udbhav30** [comment]
@vanzin yes i think so i will verify if that covers all the scenarios and if required i will raise a PR for that , i will close this as of now.

**Pull request closed without merging**
