### PR TITLE
[SPARK-41467][BUILD] Upgrade httpclient from 4.5.13 to 4.5.14

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
This PR upgrades `commons.httpclient` from `4.5.13` to `4.5.14`.

### Why are the changes needed?
https://archive.apache.org/dist/httpcomponents/httpclient/RELEASE_NOTES-4.5.x.txt
image

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA.

### CODE REVIEW

**Review by LuciferYang — APPROVED** [review]
LGTM if test pass

**Comment by srowen** [comment]
Try rerunning the tests

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Please rerun the failed tests as recommended in the above, @panbingkun .

**Comment by dongjoon-hyun** [comment]
All tests passed. Merged to master. Thank you, @panbingkun and all.

**Pull request closed without merging**
