### PR TITLE
[MINOR][CORE][TESTS] Fix EventLogFileWritersSuite typo

### PR DESCRIPTION
**Pull request by surjikal**
### What changes were proposed in this pull request?
A simple typo fix

### Why are the changes needed?
Not truly necessary, I just saw it and fixed it

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
n/a

### Was this patch authored or co-authored using generative AI tooling?
No

---

cc @dongjoon-hyun

---

As noted in the PR guidelines...

I state that the contribution is my original work and that I license the work to the project under the project’s open source license.

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Is this the only typo in this test suite, @surjikal ?

**Comment by yaooqinn** [comment]
It is not appropriate to use SPARK-34503, which was fixed in v3.2.0.

It would be greatly appreciated if you could modify your title to include `[MINOR][TESTS]` for minor revisions.

Also, please ensure that there are no spelling, grammar or punctuation errors in EventLogFileWritersSuite.

**Comment by dongjoon-hyun** [comment]
Ya, right. We cannot use the released JIRA issue ID. I removed the ID from the PR title according to @yaooqinn 's advice, @surjikal .

**Comment by surjikal** [comment]
> Is this the only typo in this test suite, @surjikal ?

No other typos. I just double checked using a spell checker.

Side note: I wasn't intentionally searching for typos btw, I just stumbled upon it.

> Ya, right. We cannot use the released JIRA issue ID. I removed the ID from the PR title according to yaooqinn's advice

Noted for next time, thanks for the edit!

**Comment by surjikal** [comment]
I just amended the commit message. I realize I used the issue as the branch name... is this a problem?

**Comment by yaooqinn** [comment]
Hi @surjikal, after reviewing the CI https://github.com/apache/spark/pull/43895/checks?check_run_id=18834027975, you need to enable it by following the instructions provided.

> I realize I used the issue id as the branch name too... is this a problem?

It's alright, as it doesn't impact the process of reviewing or committing a PR.

**Comment by surjikal** [comment]
@yaooqinn Apologies, I had assumed I didn't need to do it, given the nature of the change.

This is done.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @surjikal and all.
Merged to master.

**Pull request closed without merging**
