### PR TITLE
[SPARK-38527][K8S][DOCS][FOLLOWUP] Use v1.5.0 tag instead of release-1.5

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR uses the `v1.5.0` tag instead of the branch name.

### Why are the changes needed?

It was a mistake to use `branch` name. It should be an immutable tag.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Manual review.

### CODE REVIEW

**Review by wangyum — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
cc @viirya and @Yikun

**Comment by dongjoon-hyun** [comment]
Thank you, @wangyum !

**Review by viirya — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @viirya !

**Comment by dongjoon-hyun** [comment]
Merged to master.

**Pull request closed without merging**
