### PR TITLE
[HOTFIX] History Server API docs error fix.

### PR DESCRIPTION
**Pull request by harishreedharan**
Minor error in the monitoring docs. Also made indentation changes in `ApiRootResource`

### CODE REVIEW

**Comment by andrewor14** [comment]
Thanks for doing this @harishreedharan. The changes here lgtm.

**Comment by harishreedharan** [comment]
I am adding the docs you mentioned in the other PR. Please hold off for a couple mins before merging.

**Comment by harishreedharan** [comment]
@andrewor14, that should be it.

**Comment by andrewor14** [comment]
merging into master since the changes here are just style and docs.

**Pull request closed without merging**
