### PR TITLE
[SPARK-39790] Replace put element to map one by one to putAll

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
Replace put element to map one by one to putAll

### Why are the changes needed?
Improve performance

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA.

### CODE REVIEW

**Comment by panbingkun** [comment]
Don't review, i will check it!

**Comment by HyukjinKwon** [comment]
Let's do this sort of things when we touch other codes around here.

**Comment by panbingkun** [comment]
> Let's do this sort of things when we touch other codes around here.
@HyukjinKwon, Can I merge the above code changes into PR: https://github.com/apache/spark/pull/37199 ?

**Review by srowen — COMMENTED** [review]
Are there other instances? otherwise this isn't worth it, this is not at all a hot path

**Comment by panbingkun** [comment]
> Are there other instances? otherwise this isn't worth it, this is not at all a hot path

I haven't found another instances yet.

**Comment by panbingkun** [comment]
I will close

**Pull request closed without merging**
