### PR TITLE
[SPARK-37727][SQL] Show ignored confs & hide warnings for conf already set in SparkSession.builder.getOrCreate

### PR DESCRIPTION
**Pull request by HyukjinKwon**
### What changes were proposed in this pull request?

This PR proposes to show ignored configurations and hide the warnings for configurations that are already set when invoking `SparkSession.builder.getOrCreate`.

### Why are the changes needed?

Currently, `SparkSession.builder.getOrCreate()` is too noisy even when duplicate configurations are set. Users cannot easily tell which configurations are to fix. See the example below:

```bash
./bin/spark-shell --conf spark.abc=abc
```

```scala
import org.apache.spark.sql.SparkSession
spark.sparkContext.setLogLevel("DEBUG")
SparkSession.builder.config("spark.abc", "abc").getOrCreate
```

```
21:04:01.670 [main] WARN  org.apache.spark.sql.SparkSession - Using an existing SparkSession; some spark core configurations may not take effect.
```

It is straitforward when there are few configurations but it is difficult for users to figure out when there are too many configurations especially when these configurations are defined in a property file like 'spark-default.conf' maintained separately by system admins in production.

See also https://github.com/apache/spark/pull/34757#discussion_r769248275.

### Does this PR introduce _any_ user-facing change?

Yes.

1. Show ignored configurations in debug level logs:

    ```bash
    ./bin/spark-shell --conf spark.abc=abc
    ```

    ```scala
    import org.apache.spark.sql.SparkSession
    spark.sparkContext.setLogLevel("DEBUG")
    SparkSession.builder
      .config("spark.sql.warehouse.dir", "2")
      .config("spark.abc", "abcb")
      .config("spark.abcd", "abcb4")
      .getOrCreate
    ```

    **Before:**

    ```
    21:13:28.360 [main] WARN  org.apache.spark.sql.SparkSession - Using an existing SparkSession; the static sql configurations will not take effect.
    21:13:28.360 [main] WARN  org.apache.spark.sql.SparkSession - Using an existing SparkSession; some spark core configurations may not take effect.
    ```

    **After**:

    ```
    20:34:30.619 [main] WARN  org.apache.spark.sql.SparkSession - Using an existing Spark session; only runtime SQL configurations will take effect.
    20:34:30.622 [main] DEBUG org.apache.spark.sql.SparkSession - Ignored static SQL configurations:
      spark.sql.warehouse.dir=2
    20:34:30.623 [main] DEBUG org.apache.spark.sql.SparkSession - Configurations that might not take effect:
      spark.abcd=abcb4
      spark.abc=abcb
    ```

2. Do not issue a warning and hide a configuration already explicitly set (with the same value) before.

    ```bash
    ./bin/spark-shell --conf spark.abc=abc
    ```

    ```scala
    import org.apache.spark.sql.SparkSession
    spark.sparkContext.setLogLevel("DEBUG")
    SparkSession.builder.config("spark.abc", "abc").getOrCreate  // **Ignore** warnings because it's already set in --conf
    SparkSession.builder.config("spark.abc.new", "abc").getOrCreate  // **Show** warnings for only configuration newly set.
    SparkSession.builder.config("spark.abc.new", "abc").getOrCreate  // **Ignore** warnings because it's set ^.
    ```

    **Before**:

    ```
    21:13:56.183 [main] WARN  org.apache.spark.sql.SparkSession - Using an existing SparkSession; some spark core configurations may not take effect.
    21:13:56.356 [main] WARN  org.apache.spark.sql.SparkSession - Using an existing SparkSession; some spark core configurations may not take effect.
    21:13:56.476 [main] WARN  org.apache.spark.sql.SparkSession - Using an existing SparkSession; some spark core configurations may not take effect.
    ```

    **After:**

    ```
    20:36:36.251 [main] WARN  org.apache.spark.sql.SparkSession - Using an existing Spark session; only runtime SQL configurations will take effect.
    20:36:36.253 [main] DEBUG org.apache.spark.sql.SparkSession - Configurations that might not take effect:
      spark.abc.new=abc
    ```

3. Do not issue a warning and hide runtime SQL configurations in debug log:

    ```bash
    ./bin/spark-shell
    ```

    ```scala
    import org.apache.spark.sql.SparkSession
    spark.sparkContext.setLogLevel("DEBUG")
    SparkSession.builder.config("spark.sql.ansi.enabled", "true").getOrCreate  // **Ignore** warnings for runtime SQL configurations
    SparkSession.builder.config("spark.buffer.size", "1234").getOrCreate  // **Show** warnings for Spark core configuration
    SparkSession.builder.config("spark.sql.source.specific", "abc").getOrCreate  // **Show** warnings for custom runtime options
    SparkSession.builder.config("spark.sql.warehouse.dir", "xyz").getOrCreate  // **Show** warnings for static SQL configurations
    ```

    **Before**:

    ```
    11:11:40.846 [main] WARN  org.apache.spark.sql.SparkSession - Using an existing SparkSession; some spark core configurations may not take effect.
    11:11:41.037 [main] WARN  org.apache.spark.sql.SparkSession - Using an existing SparkSession; some spark core configurations may not take effect.
    11:11:41.167 [main] WARN  org.apache.spark.sql.SparkSession - Using an existing SparkSession; some spark core configurations may not take effect.
    11:11:41.318 [main] WARN  org.apache.spark.sql.SparkSession - Using an existing SparkSession; the static sql configurations will not take effect.
    ```

    **After**:

    ```
    10:39:54.870 [main] WARN  org.apache.spark.sql.SparkSession - Using an existing Spark session; only runtime SQL configurations will take effect.
    10:39:54.872 [main] DEBUG org.apache.spark.sql.SparkSession - Configurations that might not take effect:
      spark.buffer.size=1234
    10:39:54.988 [main] WARN  org.apache.spark.sql.SparkSession - Using an existing Spark session; only runtime SQL configurations will take effect.
    10:39:54.988 [main] DEBUG org.apache.spark.sql.SparkSession - Configurations that might not take effect:
      spark.sql.source.specific=abc
    10:39:55.107 [main] WARN  org.apache.spark.sql.SparkSession - Using an existing Spark session; only runtime SQL configurations will take effect.
    10:39:55.108 [main] DEBUG org.apache.spark.sql.SparkSession - Ignored static SQL configurations:
      spark.sql.warehouse.dir=xyz
    ```

Note that there is no behaviour change on session state initialization when configurations are not set. For example:

```scala
import org.apache.spark.sql.SparkSession
spark.sparkContext.setLogLevel("DEBUG")
SparkSession.builder.getOrCreate
```

But the session state initialization can be triggered now for static SQL configurations set after this PR. Previously, it was not triggered. This would not introduce something user-facing or a bug but worth noting it.
For runtime SQL configurations, the session state initialization in this code path was introduced at https://github.com/apache/spark/pull/15295.

### How was this patch tested?

It was manually tested as shown above.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @cloud-fan, @dongjoon-hyun @AngersZhuuuu @yaooqinn @maropu FYI when you find some time to review :-).

**Review by yaooqinn — APPROVED** [review]
LGTM

**Comment by Ngone51** [comment]
> 20:36:36.253 [main] DEBUG org.apache.spark.sql.SparkSession - Configurations that might not take effect:
>  spark.abc.new=abc

I feel this could be a bit confused. Users may thought the value `abc` doesn't take effect for the conf `spark.abc.new`. However, it does. The thing is, it's actually the second set doesn't take effect here rather than the value itself.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @HyukjinKwon .

**Comment by HyukjinKwon** [comment]
> I feel this could be a bit confused. Users may thought the value `abc` doesn't take effect for the conf `spark.abc.new`. However, it does. The thing is, it's actually the second set doesn't take effect here rather than the value itself.

This actually was already there. The problem here is that users, for example, might pass some source specific options that Spark side does not now. Maybe we can filter out Spark's runtime configuration here though. Let me take a look while I am here.

**Comment by HyukjinKwon** [comment]
@Ngone51, the current change should address your comment (see 3. in Pr desscription)

**Comment by AngersZhuuuu** [comment]
Maybe we can have a UT in `SparkShellSuite`?

**Comment by HyukjinKwon** [comment]
> Maybe we can have a UT in `SparkShellSuite`?

There is actually a bug I guess from switching to log4j 2 (see SPARK-37729). I would prefer to add it after this gets resolved.

**Comment by AngersZhuuuu** [comment]
> > Maybe we can have a UT in `SparkShellSuite`?
> 
> There is actually a bug I guess from switching to log4j 2 (see [SPARK-37729](https://issues.apache.org/jira/browse/SPARK-37729)). I would prefer to add it after this gets resolved.

Got it, thanks.

**Review by AngersZhuuuu — APPROVED** [review]
LGTM

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by HyukjinKwon** [comment]
Thanks guys for your reviews.

**Comment by Ngone51** [comment]
late lgtm

**Pull request closed without merging**
