### PR TITLE
[MINOR] Convert match statement to pattern match anonymous function and remove unused var in sql.api.r.SQLUtils

### PR DESCRIPTION
**Pull request by techaddict**
## What changes were proposed in this pull request?
1. Convert match statement to pattern match anonymous function
2. Remove unused var

### CODE REVIEW

**Comment by techaddict** [comment]
@srowen

**Comment by srowen** [comment]
This is too trivial. I'd like to push back on changes like this as it takes a bit of time to deal with, and in this case isn't improving runtime or readability.

**Comment by techaddict** [comment]
@srowen Okay makes sense, I'll keep this open and add more stuff as I encounter.

**Comment by srowen** [comment]
Just close it for now to keep it off the radar.
I think these kinds of things can make sense if they fix one small sub-optimal coding practice across the code base, and ideally, put in place some kind of style check to forbid it (not always possible).

**Pull request closed without merging**
