### PR TITLE
[SPARK-49753][BUILD] Upgrade ZSTD-JNI to 1.5.6-6

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
The pr aims to upgrade `zstd-jni` from `1.5.6-5` to `1.5.6-6`.

### Why are the changes needed?
The new version allow including compression level when training a dictionary:  https://github.com/luben/zstd-jni/commit/3ca26eed6c84fb09c382854ead527188e643e206#diff-bd5c0f62db7cb85cac88c7b6cfad1c0e5e2f433ba45097761654829627b7a31c

All changes in the new version are as follows:
- https://github.com/luben/zstd-jni/compare/v1.5.6-5...v1.5.6-6

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GitHub Actions

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by LuciferYang** [comment]
Test first

**Review by dongjoon-hyun — COMMENTED** [review]
Thank you, @LuciferYang . Could you fill the PR description?

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @LuciferYang .
Merged to master.

**Comment by LuciferYang** [comment]
Thanks @dongjoon-hyun

**Pull request closed without merging**
