### PR TITLE
[SPARK-14998][SQL]fix ArrayIndexOutOfBoundsException in 

### PR DESCRIPTION
**Pull request by liyuance**
when I use transformation in SparkSQL, may throw java.lang.ArrayIndexOutOfBoundsException, as some output lines of the transformation script end with sequential TOK_TABLEROWFORMATFIELD.
like:
A\tB\tC\t\t

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Maybe I think the title is incomplete. It would be nicer if the title includes where (in.. where).

**Comment by yhuai** [comment]
ok to test

**Comment by yhuai** [comment]
can you add a regression test?

**Comment by yhuai** [comment]
At here, `A\tB\tC\t\t` represents 5 fields and `A\tB\tC\t` represents 4 fields, right?

**Comment by rxin** [comment]
cc @gatorsmile  would you be able to take this over and add a test case?

**Comment by gatorsmile** [comment]
Sure, will do it. Thanks!

**Comment by gatorsmile** [comment]
Sorry, I am unable to reproduce it. Without the fix, the following test case works well. 

```scala
    val data = Seq(("A\tB\tC\tD\t\t"), ("E\tF\tD\tE\t"))
    data.toDF("d1").createOrReplaceTempView("script_trans")
    checkAnswer(
    sql("SELECT TRANSFORM (d1) USING 'cat' AS (a, b, c, d) FROM script_trans"),
      Row("A", "B", "C", "D") :: Row("E", "F", "D", "E") :: Nil)
```

**Comment by rxin** [comment]
@liyuance can you comment on this?

**Comment by JoshRosen** [comment]
@liyuance, if you don't have a reproduction of this issue could you close this PR? You can always re-open it later once it's ready for review. Thanks!

**Pull request closed without merging**
