### PR TITLE
[SPARK-12717][SPARK-21031][SPARK-21599][SQL][BRANCH-2.2]] Collecting column statistics for datasource tables may fail with java.util.NoSuchElementException

### PR DESCRIPTION
**Pull request by dilipbiswal**
## What changes were proposed in this pull request?
Backports the following JIRAs into 2.2.
```
[SPARK-17410][SPARK-17284] Move Hive-generated Stats Info to HiveClientImpl
[SPARK-21031][SQL] Add `alterTableStats` to store spark's stats and let `alterTable` keep existing stats
[SPARK-21599][SQL] Collecting column statistics for datasource tables may fail with java.util.NoSuchElementException
```
## How was this patch tested?
Tests cases added as part of original fix.

### CODE REVIEW

**Comment by dilipbiswal** [comment]
@gatorsmile I just created this PR for you take a look and decide if we need to back port the above 3 PRs. The problem for SPARK-21599 does not exist on 2.2 as it was introduced as part of SPARK-21031. I took a look at the problem mentioned in SPARK-21031 and it seems like we may want this fix in 2.2 ? 

I will close this PR in case you decide to not back port these. Thanks.

**Review by gatorsmile — COMMENTED** [review]
I think the PR is too large for backporting. We still have such a bug in 2.2, right? We can fix it using different ways.

**Comment by dilipbiswal** [comment]
@gatorsmile Thanks !! To the best of my knowledge, we don't have the problem of analyze table command failing with java.util.NoSuchElement exception in 2.2. In 2.2, we used to add the column stats using alterTable method. Currently we use alterTableStats method where this problem exists. alterTableStats was introduced as part of  SPARK-21031.

I will close this PR for now.

**Comment by gatorsmile** [comment]
I see. Thanks!

**Pull request closed without merging**
