### PR TITLE
[SPARK-7615] [MLLIB] MLLIB Word2Vec wordVectors divided by Euclidean Norm equals to zero

### PR DESCRIPTION
**Pull request by srowen**
Cosine similarity with 0 vector should be 0

Related to https://github.com/apache/spark/pull/10152

### CODE REVIEW

**Comment by MLnick** [comment]
LGTM

**Comment by srowen** [comment]
@sarutak @jkbradley can one of you try merging this? `git` keeps failing for me and I don't know why; trying to track down whether it's something local or not

**Comment by sarutak** [comment]
O.K, I'll try to merge. Which branch would you like to merge?

**Comment by srowen** [comment]
I think this is good for master and 1.6

**Comment by sarutak** [comment]
I also failed to merge. How did you merge?

**Comment by srowen** [comment]
@sarutak that's really strange, it suddenly shows up as merged. I guess it succeeded but `git` on my end failed right after. I'll try to get this merged to 1.6. Not sure what's going on. I am now able to merge other stuff though, whereas all were failing an hour ago. _shrug_

**Comment by srowen** [comment]
Merged to master/1.6

**Pull request closed without merging**
