### PR TITLE
[SPARK-6661] Python type errors should print type, not object

### PR DESCRIPTION
**Pull request by 31z4**

### CODE REVIEW

**Comment by rxin** [comment]
Jenkins, test this please.

**Comment by rxin** [comment]
cc @davies

**Comment by davies** [comment]
@31z4 Thanks to look into this. Personally, I like the type object instead of name of type, for example, you can got the full name of a class:
```
>>> print "but got:", type("")
but got: <type 'str'>
>>> print "but got:", type("").__name__
but got: str
>>> print pyspark.RDD
<class 'pyspark.rdd.RDD'>
>>> print pyspark.RDD.__name__
RDD
```

Also, we may change some `ValueError` to `TypeError`.

**Comment by 31z4** [comment]
@davies Thanks for your comments! I made changes.

**Comment by davies** [comment]
@31z4 After reading the docs again, it should be `TypeError`, see https://docs.python.org/2/reference/datamodel.html#object.__getitem__

```
>>> ""[""]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: string indices must be integers, not str
```

Sorry for that.

**Comment by 31z4** [comment]
@davies It's OK. I may have looked into docs by myself :)

**Comment by davies** [comment]
@31z4 You can run `dev/lint-python` to find the lint errors.

**Comment by 31z4** [comment]
@davies Fixed and rebased.

**Comment by 31z4** [comment]
@davies Fixed errors and rebased.

**Comment by 31z4** [comment]
@davies seems like the failures are in Scala tests. Can anyone look into that? I also had failures in Scala tests on my machine. All Python tests passed without errors though.

**Comment by 31z4** [comment]
@davies What should I do? Either just wait when master will be fixed or rebase to an exact commit?

**Comment by jkbradley** [comment]
@davies  I agree it's nice to get the actual object printed, rather than just the type.  My problem with it was it failing to print meaningful error messages when the object did not have a default conversion to a string.  (It would then print an error about the conversion, rather than about the original error.)

@31z4 What if we kept printing the object (not the type) as before, but did it via a helper method used as follows:
```
  raise TypeError("Found an error with: " + tryToString(myObject))
```
where tryToString first tries printing the object to a string ("object blah") and, if that fails, then tries printing the type to a string ("type: objecttype")?

**Comment by jkbradley** [comment]
@davies Oops, I misinterpreted your above comment.  If we're sticking with types, then nevermind!

**Comment by 31z4** [comment]
@jkbradley Yes, we're sticking with types.

**Comment by 31z4** [comment]
@davies @jkbradley @rxin could someone look into this commit again and trigger the Jenkins test?

**Comment by JoshRosen** [comment]
It looks like this latest test run actually passed, but there was a problem in posting the success message to GitHub.  I haven't been following this PR, but if other committers think it's good to go then we might want to merge it now so that it doesn't merge conflict when the Python 3 patch is merged.

**Comment by 31z4** [comment]
Thanks @JoshRosen! Looking forward for someone's answer.

**Comment by davies** [comment]
LGTM

**Comment by mengxr** [comment]
test this please

**Comment by JoshRosen** [comment]
It looks like this is now merge-conflicted with master due to the Python 3 change, but I think that I should be able to resolve the conflicts myself on merge.

**Comment by JoshRosen** [comment]
Actually, it looks like the MLlib conflicts may not be all due to the Python 3 change, so do you mind fixing up these conflicts?  Sorry for not preventing these conflicts by merging earlier.

**Comment by 31z4** [comment]
@JoshRosen I don't mind. I'll do it.

**Comment by 31z4** [comment]
@JoshRosen Done.

**Comment by JoshRosen** [comment]
Jenkins, retest this please.

**Comment by JoshRosen** [comment]
LGTM, so I'm going to merge this into `master` (1.4.0).  Thanks!

**Pull request closed without merging**
