### PR TITLE
[Minor][SparkR]:fix kstest example error and add unit test

### PR DESCRIPTION
**Pull request by wangmiao1981**
## What changes were proposed in this pull request?

While adding vignettes for kstest, I found some errors in the example:
1. There is a typo of kstest;
2. print.summary.KStest doesn't work with the example;

Fix the example errors;
Add a new unit test for print.summary.KStest;

## How was this patch tested?
Manual test;
Add new unit test;

### CODE REVIEW

**Comment by wangmiao1981** [comment]
cc @felixcheung

**Comment by HyukjinKwon** [comment]
(@wangmiao1981 you could close and re-open this to re-trigger the build as we already talk before if you or any cares).

**Comment by felixcheung** [comment]
LGTM. Let's trigger appveyor again like Hyukjin says

**Comment by yanboliang** [comment]
LGTM

**Comment by wangmiao1981** [comment]
close to trigger appveyor

**Comment by wangmiao1981** [comment]
open to trigger test

**Comment by wangmiao1981** [comment]
windows check passed

**Comment by yanboliang** [comment]
Merged into master and branch-2.1. Thanks!

**Pull request closed without merging**
