### PR TITLE
[SPARK-24499][SQL][DOC][Followup] Fix some broken links

### PR DESCRIPTION
**Pull request by dilipbiswal**
## What changes were proposed in this pull request?
Fix some broken links in the new document. I have clicked through all the links. Hopefully i haven't missed any :-)

## How was this patch tested?
Built using jekyll and verified the links.

### CODE REVIEW

**Comment by dilipbiswal** [comment]
cc @dongjoon-hyun @gatorsmile @xuanyuanking

**Comment by HyukjinKwon** [comment]
I think we better do some proof readings before doing multiple minor followups.

**Comment by dilipbiswal** [comment]
@HyukjinKwon Sure..

**Review by xuanyuanking — APPROVED** [review]
+1 for me with the link fix, sorry for the mistake, I'm keeping checking with similar link.

**Comment by HyukjinKwon** [comment]
It's okay. the doc fix was huge and there should likely be some mistakes. I will read it closely too this weekends.

**Comment by gatorsmile** [comment]
LGTM

Let us merge this PR first. If we find more, feel free to open a new follow-up PR

**Comment by dilipbiswal** [comment]
Thank you @gatorsmile @HyukjinKwon @xuanyuanking

**Pull request closed without merging**
