### PR TITLE
[SPARK-32972][ML] Pass all UTs of  `mllib` module in Scala 2.13

### PR DESCRIPTION
**Pull request by LuciferYang**
### What changes were proposed in this pull request?
The purpose of this pr is to resolve SPARK-32972, total of 51 Scala failed test cases and 3 Java failed test cases were fixed, the main change of this pr as follow:

- Specified `Seq` to `scala.collection.Seq` in case match `Seq` scene and `x.asInstanceOf[Seq[T]]` scene

- Use `Row.getSeq[T]` instead of `Row.getAs[Seq]`

- Manual call `toMap` method to convert `MapView` to `Map` in Scala 2.13

- Change  the tol in the last test to 0.75 to pass `RandomForestRegressorSuite#training with sample weights` in Scala 2.13

### Why are the changes needed?
We need to support a Scala 2.13 build.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
- Scala 2.12: Pass the Jenkins or GitHub Action

- Scala 2.13: Pass  GitHub 2.13 Build Action

Do the follow:

```
dev/change-scala-version.sh 2.13
mvn clean install -DskipTests  -pl mllib -Pscala-2.13 -am
mvn test -pl mllib -Pscala-2.13 -fn
```

**Before**
```
[ERROR] Errors: 
[ERROR]   JavaVectorIndexerSuite.vectorIndexerAPI:51 » ClassCast scala.collection.conver...
[ERROR]   JavaWord2VecSuite.testJavaWord2Vec:51 » Spark Job aborted due to stage failure...
[ERROR]   JavaPrefixSpanSuite.runPrefixSpanSaveLoad:79 » Spark Job aborted due to stage ...

Tests: succeeded 1567, failed 51, canceled 0, ignored 7, pending 0
*** 51 TESTS FAILED ***

```

**After**

```
[INFO] Tests run: 122, Failures: 0, Errors: 0, Skipped: 0

Tests: succeeded 1617, failed 0, canceled 0, ignored 7, pending 0
All tests passed.

```

### CODE REVIEW

**Comment by LuciferYang** [comment]
cc @dongjoon-hyun https://github.com/apache/spark/pull/29861 fix GitHub 2.13 build Action, related to k8s module, I will rebase this pr after it merged.

**Comment by LuciferYang** [comment]
cc @srowen The remaining failed case is 

```
RandomForestRegressorSuite:
- training with sample weights *** FAILED ***
  0.756 was not greater than or equal to 0.78 (MLTestingUtils.scala:285)
```

https://github.com/apache/spark/blob/0bc0e91e4015eb98bd2f4bf17da2ec7135b520a9/mllib/src/test/scala/org/apache/spark/ml/regression/RandomForestRegressorSuite.scala#L171-L200

Input `(50, 10, 0.95, 0.78)` with 

```
MLTestingUtils.testOversamplingVsWeighting[RandomForestRegressionModel,
        RandomForestRegressor](df.as[LabeledPoint], estimator,
        MLTestingUtils.modelPredictionEquals(df, _ ~= _ relTol 0.2, tol), seed)
```
failed.

I found that the following `RandomForest.runBagged` behave differently for the same input in Scala 2.12 and Scala 2.13, maybe related to the follow code block:

https://github.com/apache/spark/blob/0bc0e91e4015eb98bd2f4bf17da2ec7135b520a9/mllib/src/main/scala/org/apache/spark/ml/tree/impl/RandomForest.scala#L191-L215

but I am not familiar with this algorithm and I not find root cause, I think we need an expert to guide how to fix it

**Comment by LuciferYang** [comment]
https://github.com/apache/spark/blob/0bc0e91e4015eb98bd2f4bf17da2ec7135b520a9/mllib/src/test/scala/org/apache/spark/ml/regression/RandomForestRegressorSuite.scala#L36-L54

And I found if we change `nPoints` from 1000 to 1150, the test will pass

**Comment by dongjoon-hyun** [comment]
@LuciferYang . I closed your  #29861 because `master` branch is already fixed two hours ago.
- https://github.com/apache/spark/blob/master/resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/k8s/features/MountVolumesFeatureStep.scala#L117

**Comment by dongjoon-hyun** [comment]
You need to rebase this branch .

**Comment by LuciferYang** [comment]
@dongjoon-hyun Address 4f5eac5 rebase master

**Comment by srowen** [comment]
For the random forest test, it's probably reasonably to simply change the tol in the last test to 0.75 like the others. I don't know why it should be higher.

If you like you can try making the ordering of the Map in this code deterministic to see if that does it:
```
val topNodesForGroup: Map[Int, LearningNode] = 
     nodesForGroup.keys.map(treeIdx => treeIdx -> topNodes(treeIdx)).toMap 
```

But, I don't even know if the result the test is complaining about is 'wrong'.

**Comment by LuciferYang** [comment]
> f you like you can try making the ordering of the Map in this code deterministic to see if that does it:

val topNodesForGroup: Map[Int, LearningNode] = 
     nodesForGroup.keys.map(treeIdx => treeIdx -> topNodes(treeIdx)).toMap 
But, I don't even know if the result the test is complaining about is 'wrong'.

OK ~ I will try this first and feedback later.

But change 0.78 to 0.75 seems simpler, haha :)

**Comment by LuciferYang** [comment]
Synchronize the test result:

https://github.com/apache/spark/blob/0bc0e91e4015eb98bd2f4bf17da2ec7135b520a9/mllib/src/main/scala/org/apache/spark/ml/tree/impl/RandomForest.scala#L194-L202

- **Test A：** Change to use `LinkedHashMap` to store topNodesForGroup and use `nodesForGroup.keys.toSeq.sorted` to init it was no essential impact.

- **Test B：** Change to use `LinkedHashMap` to store `topNodesForGroup` and `nodesForGroup` seems that the goal of unified behavior in Scala 2.12 and 2.13 can be achieved,  but need change the tol in the last test to 0.77(the result is 0.771)

- **Test C：** Only change the tol in the last test to 0.75 can workaround

Which do you recommend better @srowen , B or C?

**Comment by srowen** [comment]
I think the latter option, changing the tol, is fine.

**Comment by LuciferYang** [comment]
ok ~

**Comment by LuciferYang** [comment]
Address f2a26c5 fix RandomForestRegressorSuite.

**Comment by LuciferYang** [comment]
@srowen Is there any other problem in this pr that needs to be fixed?

**Comment by LuciferYang** [comment]
From the first round of code checking, may be this is the last module to fix Scala version compatibility

**Comment by srowen** [comment]
Merged to master

**Comment by LuciferYang** [comment]
thx @srowen ~

**Comment by LuciferYang** [comment]
@dongjoon-hyun Should we consider adding some new GitHubActions to check test in Scala 2.13?

**Pull request closed without merging**
