### PR TITLE
[SPARK-44540][UI] Remove unused stylesheet and javascript files of jsonFormatter

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

This PR safely removes unused stylesheet and javascript files of `jsonFormatter`

### Why are the changes needed?

Simplify css/js dependencies for UI

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

built and verified locally with UI

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @sarutak @gengliangwang FYI

**Review by sarutak — APPROVED** [review]
LGTM.

**Review by gengliangwang — APPROVED** [review]

**Review by LuciferYang — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by yaooqinn** [comment]
Thanks @HyukjinKwon @gengliangwang @sarutak @dongjoon-hyun , merged to master and 3.5

**Pull request closed without merging**
