### PR TITLE
[SPARK-11150][SQL][FOLLOW-UP] Dynamic partition pruning

### PR DESCRIPTION
**Pull request by maryannxue**
### What changes were proposed in this pull request?
This is code cleanup PR for https://github.com/apache/spark/pull/25600, aiming to remove an unnecessary condition and to correct a code comment.

### Why are the changes needed?
For code cleanup only.

### Does this PR introduce any user-facing change?
No.

### How was this patch tested?
Passed existing tests.

### CODE REVIEW

**Comment by maryannxue** [comment]
cc @cloud-fan

**Comment by cloud-fan** [comment]
retest this please

**Comment by cloud-fan** [comment]
LGTM

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Pull request closed without merging**
