### PR TITLE
[SPARK-50147][PYTHON][DOCS][TESTS] Refine docstring for trigonometric functions

### PR DESCRIPTION
**Pull request by zhengruifeng**
### What changes were proposed in this pull request?
Refine docstring for trigonometric functions

### Why are the changes needed?
1, make example copy-pasteable;
2, clarify str is a column name or literal string;
3, show both the input columns and output columns, to make the projection more clear;
4, improve the test coverage by adding more doctests;

### Does this PR introduce _any_ user-facing change?
doc changes

### How was this patch tested?
added doctests

### Was this patch authored or co-authored using generative AI tooling?
no

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @zhengruifeng .
Merged to master for Apache Spark 4.0.0 on February 2025.

**Comment by dongjoon-hyun** [comment]
BTW, is this a subtask of SPARK-44728 , @zhengruifeng ?

**Comment by zhengruifeng** [comment]
@dongjoon-hyun thanks for the review, let me add recent PRs to [SPARK-44728](https://issues.apache.org/jira/browse/SPARK-44728)

**Comment by dongjoon-hyun** [comment]
Thank you, @zhengruifeng !

**Pull request closed without merging**
