### PR TITLE
[SPARK-9885] [SQL] Also pass barrierPrefixes and sharedPrefixes to IsolatedClientLoader when hiveMetastoreJars is set to maven.

### PR DESCRIPTION
**Pull request by yhuai**
https://issues.apache.org/jira/browse/SPARK-9885

cc @marmbrus @liancheng

### CODE REVIEW

**Comment by yhuai** [comment]
@liancheng Can you help me test it in your environment?

**Comment by marmbrus** [comment]
LGTM

**Comment by liancheng** [comment]
LGTM

**Comment by liancheng** [comment]
Verified under my local MySQL backed Hive 0.13.1 metastore and it works. Merging to master and branch-1.5.

**Pull request closed without merging**
