### PR TITLE
[SPARK-9954] [MLLIB] use first 128 nonzeros to compute Vector.hashCode

### PR DESCRIPTION
**Pull request by mengxr**
This could help reduce hash collisions, e.g., in `RDD[Vector].repartition`. @jkbradley

### CODE REVIEW

**Comment by srowen** [comment]
I can't find the JIRA now, but I recall this came up recently. Yes I think this is a good change.

**Comment by jkbradley** [comment]
LGTM

**Comment by MechCoder** [comment]
Great. But is there any reason why 64 is chosen in particular?

**Comment by yinyao123** [comment]
Great. But is there any reason why 64 is chosen in particular?

**Comment by mengxr** [comment]
No particular reason. Just want to have less hash collision while keeping the computation cheap. 16 is certainly not sufficient. See https://en.wikipedia.org/wiki/Java_hashCode()#The_java.lang.String_hash_function. In practice, a sparse instance usually has less than a few hundred nonzeros. I chose 64 for this reason, but I'm okay with 128, 256, 512, or 1024. However, a value greater than 1024 would be too much.

**Comment by mengxr** [comment]
Changed 64 to 128.

**Comment by mengxr** [comment]
Merged into master. Thanks for reviewing!

**Pull request closed without merging**
