### PR TITLE
[SPARK-48230][BUILD] Remove unused `jodd-core`

### PR DESCRIPTION
**Pull request by pan3793**
### What changes were proposed in this pull request?

Remove a jar that has CVE https://github.com/advisories/GHSA-jrg3-qq99-35g7

### Why are the changes needed?

Previously, `jodd-core` came from Hive transitive deps, while https://github.com/apache/hive/pull/5151 (Hive 2.3.10) cut it out, so we can remove it from Spark now.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Pass GA.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM (Pending CIs)

**Comment by dongjoon-hyun** [comment]
Merged to master for Apache Spark 4.0.0.

**Comment by dongjoon-hyun** [comment]
Hi, @pan3793 .

It seems that we need to re-evaluate this dependency removal. Please see the following which is related to `commons-lang:commons:lang`.

- #46528

**Comment by dongjoon-hyun** [comment]
For the existing Hive UDFs which assumes `jodd` library, this could be a breaking change like #46528 . 
```
- import jodd.datetime.JDateTime;
+ import org.apache.hadoop.hive.ql.io.parquet.timestamp.datetime.JDateTime;
```

Sorry but let me revert this first. We need a more graceful way of removing or additional verified migration path (documentation and config).

**Comment by pan3793** [comment]
@dongjoon-hyun Okay, as this fail the CI, we should revert deps removing first and do more investigation later.

While for supporting "legacy Hive UDF jars", I think if the user imports some classes that come from Hive transitive deps, Spark is not responsible for handling that.

For example, Spark only includes part of Hive deps (I mean the all jars shipped by Hive binary tgz), for example, Hive ships `groovy-all-2.4.4.jar` but Spark does not, if user's UDF imports classes from `groovy-all-2.4.4.jar`, it should fail on Spark due to ClassNotFound, in this case user should add thrid party deps by themselves.

I believe jodd/commons-lang 2.x/jackson 1.x are in same position.

**Comment by pan3793** [comment]
Hi, @dongjoon-hyun, since we have successfully upgraded Hive to 2.3.10 in Spark 4.0, do you think we can re-evaluate this PR for Spark 4.1?

**Comment by dongjoon-hyun** [comment]
> Hi, @dongjoon-hyun, since we have successfully upgraded Hive to 2.3.10 in Spark 4.0, do you think we can re-evaluate this PR for Spark 4.1?

+1, @pan3793 .

**Comment by dongjoon-hyun** [comment]
cc @peter-toth

**Pull request closed without merging**
