### PR TITLE
[SPARK-43111][PS][CONNECT][PYTHON] Merge nested `if` statements into single `if` statements

### PR DESCRIPTION
**Pull request by bjornjorgensen**
### What changes were proposed in this pull request?
This PR aims to simplify the code by merging nested `if` statements into single `if` statements using the `and` operator. 

There are 7 of these according to [Sonarcloud](https://sonarcloud.io/project/issues?languages=py&resolved=false&rules=python%3AS1066&id=spark-python&open=AYQdnXXBRrJbVxW9ZDpw). And this PR fix them all. 

### Why are the changes needed?
The changes do not affect the functionality of the code, but they improve readability and maintainability.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA.

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]

**Comment by bjornjorgensen** [comment]
The operation was canceled after 6 hours running.

**Comment by HyukjinKwon** [comment]
Can you rerun? it should be fixed now

**Comment by bjornjorgensen** [comment]
@HyukjinKwon yes, now its works :)

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
