### PR TITLE
[SPARK-21135][WEB UI] On history server page，duration of incompleted applications should be hidden instead of showing up as 0

### PR DESCRIPTION
**Pull request by fjh100456**
## What changes were proposed in this pull request?

Hide duration of incompleted applications.

## How was this patch tested?

manual tests

### CODE REVIEW

**Comment by srowen** [comment]
CC @zhuoliu 
Wouldn't there be more places to apply logic like this?

**Comment by fjh100456** [comment]
I have not found a similar problem on other pages? The CompleteTime of this page has been hidden, indicating that it should have been considered before. 
Have you considered the other question I mentioned in Jira about the abort of the anomaly?   @zhouliu  @srowen

**Review by ajbozarth — APPROVED** [review]
This seems to be a smart follow up to #17588

**Comment by zhuoliu** [comment]
@fjh100456 this change looks good to me. Could you please add a screenshot for your test?

Regarding your question of " the application of an exception abort (such as the application of a background kill or driver outage) will always be treated as an Incompleted application, and I'm not sure if this is a problem", locally such exceptionally aborted application would rather be treated as Completed or at least STOPPED. 
I am not sure whether some other logic or some clients are using this field to decide whether they should retry or not. In that sense, we would have more to consider.

**Comment by fjh100456** [comment]
Yes,it should be. @ajbozarth 

The screenshot：@zhuoliu

default

**Comment by guoxiaolongzte** [comment]
I think it should show the specific time. It need to calculate the duration, rather than hide the title.
@srowen @ajbozarth @jerryshao

**Comment by fjh100456** [comment]
@guoxiaolongzte I have considered this problem, but there is no “EndTime“ value for applications in  processing, including the application of the exception abort I mentioned. So in the Scala code this value is not counted but directly set to 0.

**Comment by jerryshao** [comment]
I'm not familiar with JS, I'm wondering if we could use `currTimeInMs - startTime` as the **Duration** instead of "0". Not sure if it is easy to do in JS.

**Comment by fjh100456** [comment]
@jerryshao  I thought about doing like this, but the application of the exception abort will always be treated as “incompleted application”, if we use “currTimeInMs - startTime”, the duration of this kind of application will be wrong and look very strange. 
I have also considered using the lastUpdated - Starttime, but in some cases this is not very accurate.

**Comment by guoxiaolongzte** [comment]
@fjh100456  Try to follow jerryshao's  advice. I think this is very necessary.

**Comment by guoxiaolongzte** [comment]
image

I think the field needs to be hidden.

**Comment by jerryshao** [comment]
@guoxiaolongzte this column is already hidden in the master code.

@fjh100456 would you please explain more about this?

>the application of the exception abort will always be treated as “incompleted application”, if we use “currTimeInMs - startTime”, the duration of this kind of application will be wrong and look very strange.

**Comment by guoxiaolongzte** [comment]
@jerryshao  Yes, I have just seen your PR.

**Comment by jerryshao** [comment]
@fjh100456 IMO, abrupt abortion of application without application end time is not the normal case. For the most of the incompleted applications "currTimeInMs - startTime" as **Duration** is meaningful. If we'd like to display this column, I think considering normal case should be enough. (My two cents)

**Comment by fjh100456** [comment]
@jerryshao For example, you use shell commands to kill the application's submit process from outside, this application is always treated as a "incomplete application" in history server.In this case it would be wrong to use "currenttime - startTime", and the time will increases with each refresh which should actually be discontinued after the kill.

If we must keep the “duration“, I tend to use "last updated - startTime", although sometimes may not be very accurate, but at least closer to the real value, and more acceptable than display an error value, you think?

**Comment by jerryshao** [comment]
Looks from the [code](https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/deploy/history/FsHistoryProvider.scala#L458), `lastUpdated` will still be increased even after application is finished unexpectedly. So will `lastUpdated` get correct behavior? Please correct me if I'm wrong.

**Comment by fjh100456** [comment]
Sorry, I forgot to explain that what I mean by “Lastupdated“ refers to the value of "Filestatus.Getmodificationtime".Maybe the value of lastUpdated field needs a change too. @jerryshao

**Comment by jerryshao** [comment]
Using modification time may have some issues, please see the comment.

>// Use loading time as lastUpdated since some filesystems don't update modifiedTime
  // each time file is updated. However use modifiedTime for completed jobs so lastUpdated
  // won't change whenever HistoryServer restarts and reloads the file.

**Comment by fjh100456** [comment]
Oops, I didn't notice the comment. But it seems that if we don't change the "lastUpdated", it just be a  "Currenttime".
Even so，I'd like to ask for other contributor's opinions, hide or change to currentTime-startTime,which is better, after all, abnormal scenes may also occur often, such as driver downtime, or task kill process.

I tend to show the right content, not more but possibly incorrect content.  And the duration of the in-process applications can be seen on other pages, not unknowable.

**Comment by eatoncys** [comment]
I think it is better to hide it.

**Comment by eatoncys** [comment]
I think it is better to hide it.

**Comment by eatoncys** [comment]
I think it is better to hide it. @fjh100456

**Comment by fjh100456** [comment]
According to Jerryshao, I should change to use "Currenttime - StartTime", although in some scenarios the value is wrong.
But I tend to hide the duration for incomplete applications, because the duration of incomplete applications has been shown on the master page, there is no need to display a value that might not be always correct here.

Can you help me decide? @srowen @ajbozarth @zhuoliu

**Comment by ajbozarth** [comment]
I think hiding it is the correct choice personally. Users are currently used to it always set to 0 so this wouldn't be a change in functionality. Also it seems from discussion that any attempt to calculate the value would be error prone. If someone could show it's not error prone I might change my mind though.

**Comment by fjh100456** [comment]
It seems to be a big change to solve this problem completely, it may not be worth making such a big change for such a small problem, so I think we should hide it. 
cc @srowen

**Comment by 10075197** [comment]
Since it's hard to compute the accurate duration, I think it's better to hide this field.

**Comment by fjh100456** [comment]
Hi, @srowen , what's your opinion about this issue? There's been no progress for days.

**Comment by srowen** [comment]
This isn't my area, but I see no objection to merging it.

**Comment by srowen** [comment]
Actually, re-reading, @jerryshao are you OK with this approach?

**Comment by jerryshao** [comment]
Yes, I'm with the current solution, since there's no better solution.

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
