### PR TITLE
[SPARK-24931][INFRA] Fix the GA failure related to R linter

### PR DESCRIPTION
**Pull request by sarutak**
### What changes were proposed in this pull request?

This PR fixes the GA failure related to R linter which happens on some PRs (e.g. #32023, #32025).
The reason seems `Rscript -e "devtools::install_github('jimhester/lintr@v2.0.0')"` fails to download `lintr@v2.0.0`.
I don't know why but I confirmed we can download `v2.0.1`.

### Why are the changes needed?

To keep GA healthy.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

GA itself.

### CODE REVIEW

**Comment by sarutak** [comment]
cc @dongjoon-hyun @HyukjinKwon

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @sarutak .
Merged to master.

**Comment by dongjoon-hyun** [comment]
Oh, @sarutak . It seems that you gave the wrong JIRA ID.

**Comment by dongjoon-hyun** [comment]
We cannot change the commit log. Let me switch those issues.
cc @HyukjinKwon

**Comment by sarutak** [comment]
Sorry for that. I've noticed the wrong JIRA ID just now...

**Comment by dongjoon-hyun** [comment]
The switch is finished~ In this case, we are lucky because the old one is not resolved yet.

**Comment by sarutak** [comment]
Yeah, we are lucky. Sorry again and thank you for the work.
BTW, this issue happens on `branch-3.1`, `branch-3.0` and `branch-2.4`.
I'll open backport PRs.

**Comment by dongjoon-hyun** [comment]
BTW, do we need this in old branches? I didn't see Linter failures on branch-3.1/3.0 yet.

**Comment by dongjoon-hyun** [comment]
Oh, I'll backport it then. I'm just blocked due to the JIRA issue issue. You don't need to make backporting PRs.

**Comment by sarutak** [comment]
O.K, I won't. Thanks.

**Comment by dongjoon-hyun** [comment]
It's backported to branch-3.1/3.0. For branch-2.4, there is a conflict.
Could you make a backporting PR to branch-2.4 only?

**Comment by sarutak** [comment]
O.K, I'll open a PR for `branch-2.4`.

**Pull request closed without merging**
