### PR TITLE
[SPARK-24432][k8s] Add support for dynamic resource allocation on Kubernetes 

### PR DESCRIPTION
**Pull request by huafengw**
## What changes were proposed in this pull request?

Enable dynamic resource allocation on Kubernetes by introducing an external shuffle servie on K8S.

## Acknowledgement

The basic idea and most of the code comes from project https://github.com/apache-spark-on-k8s/spark.

### CODE REVIEW

**Comment by liyinan926** [comment]
@huafengw we are working on a new shuffle service + dynamic resource allocation design for k8s, and decided to not adopt the approach we used in the fork. @mccheah.

**Comment by mccheah** [comment]
Yep, please see https://issues.apache.org/jira/browse/SPARK-25299

**Comment by huafengw** [comment]
Hi, @liyinan926 @mccheah, thanks for your reminding. Looks like it's quite a new design and needs a lot of work so what is the status right now? And is it planned to be in version 3.0?

**Comment by vanzin** [comment]
I'm closing this for now since we should first figure out SPARK-25299 before enabling dynamic allocation.

**Comment by maver1ck** [comment]
Half year after. External shuffle is still in plans and this feature is missed by many people.

**Pull request closed without merging**
