### PR TITLE
[SPARK-8125] [SQL] Backports PR #7396 to branch-1.4

### PR DESCRIPTION
**Pull request by liancheng**

### CODE REVIEW

**Comment by liancheng** [comment]
cc @kai-zeng

**Comment by liancheng** [comment]
Closing this PR since this change is too risky to be backported.

**Comment by oliviertoupin** [comment]
Could you give us more details why this is "too risky"

**Comment by liancheng** [comment]
@oliviertoupin Usually we only backports fixes of severe bugs to maintaining branches.

**Comment by oliviertoupin** [comment]
I could open a bug for this, but this PR, along with a small change in newParquet.scala to use metastore schema before using "readSchema()" fix a major or critical bug. This fix a long hang in the driver while querying a table with a lots of files. 

This problem is described in several issues related to metastore, hive, and parquet.

FYI, I merged this in our dev branch to replace our custom (and very similar) fix, with great success.

If we don't merge this we just at least document the issue, so 1.4.2 users could merge this if they experience the problem.

**Comment by liancheng** [comment]
@pwendell @marmbrus Is it OK to have this one (Parquet metadata acceleration) merged to branch-1.4?

**Comment by marmbrus** [comment]
Its a pretty major change, I would error on the side of caution, especially given that 1.5 is coming out soon.

**Comment by marmbrus** [comment]
Its a pretty large change to backport to a release branch.  Given 1.5 is coming out soon I'd probably error on the side of caution.

**Pull request closed without merging**
