### PR TITLE
[SPARK-19219][SQL] Fix Parquet log output defaults

### PR DESCRIPTION
**Pull request by nicklavers**
## What changes were proposed in this pull request?

Changing the default parquet logging levels to reflect the changes made in PR [#15538](https://github.com/apache/spark/pull/15538), in order to prevent the flood of log messages by default.

## How was this patch tested?

Default log output when reading from parquet 1.6 files was compared with and without this change. The change eliminates the extraneous logging and makes the output readable.

### CODE REVIEW

**Comment by nicklavers** [comment]
Link to this JIRA issue: [https://issues.apache.org/jira/browse/SPARK-19219](https://issues.apache.org/jira/browse/SPARK-19219)
Link to original issue: [https://issues.apache.org/jira/browse/SPARK-17993](https://issues.apache.org/jira/browse/SPARK-17993)

**Comment by srowen** [comment]
So the change here is really to turn up the log level for non-test code, not just the test code? it seems possibly reasonable but are there important warnings this would suppress for users?

**Comment by nicklavers** [comment]
That's possible. We could narrow the scope a bit and instead just set ```log4j.logger.org.apache.parquet.CorruptStatistics=ERROR
log4j.logger.parquet.CorruptStatistics=ERROR```,
which also fixes the problem.

**Comment by srowen** [comment]
@nicklavers yeah narrowing the scope seems more conservative and desirable. Do the test configs need to be changed similarly to match your newer proposal?

**Comment by nicklavers** [comment]
I don't see why not

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
