### PR TITLE
[SPARK-5736][Web UI]Add executor log url to Executors page on Yarn

### PR DESCRIPTION
**Pull request by shenh062326**
Currently, there is not executor log url in spark ui (on Yarn), we have to read executor log by login the machine that executor in. I think we should add executor log url to executors pages.

### CODE REVIEW

**Comment by srowen** [comment]
This needs a rebase already. Is it really necessary to push through UI info like this into all the core code?

**Comment by shenh062326** [comment]
Hi @srowen.
We just want to read executor log from UI. is there any easy way to add executor log url to UI?

**Comment by srowen** [comment]
Sandy's right, I forgot this was just committed last week. https://issues.apache.org/jira/browse/SPARK-2450

**Comment by andrewor14** [comment]
Hey @shenh062326 there's already a solution for this that was merged in #3486. Would you mind closing this PR?

**Pull request closed without merging**
