### PR TITLE
[MINOR] Removing redundant parentheses from SQL function docs

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to removing redundant parentheses from SQL function docs.

### Why are the changes needed?
Make the document clearer, reduce misunderstandings.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
- Manually test.

### CODE REVIEW

**Comment by panbingkun** [comment]
image
Extra parentheses, this looks weird.

**Comment by panbingkun** [comment]
cc @HyukjinKwon @MaxGekk @zhengruifeng

**Comment by LuciferYang** [comment]
Any other similar case?

**Comment by panbingkun** [comment]
Currently, no other similar case have been found.

**Comment by panbingkun** [comment]
image
In fact, I accidentally changed one of the PR related to `connect function` a few days ago.
https://github.com/apache/spark/pull/41902/files

**Review by HyukjinKwon — APPROVED** [review]
I am good but as @LuciferYang said, would be great to fix others togehter.

**Comment by panbingkun** [comment]
No further others similar case have been found so far,

Also, I would like to use this place to discuss some question:

- In [FunctionRegistry](https://github.com/apache/spark/blob/8bb07388ea664303d0d22b03cca11a46498b772d/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala#L300), the classification of some functions is incorrect, is it worth doing? eg:

https://github.com/apache/spark/blob/8bb07388ea664303d0d22b03cca11a46498b772d/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala#L357-L363

Obviously, the function `Abs` belongs to https://github.com/apache/spark/blob/8bb07388ea664303d0d22b03cca11a46498b772d/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala#L384-L388

- Do we need to align the classification of functions in scala with that in Python? eg: `EqualNull`
In scala, it belongs to `Misc Function`
https://github.com/apache/spark/blob/8bb07388ea664303d0d22b03cca11a46498b772d/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/predicates.scala#L1114-L1117
https://github.com/apache/spark/blob/8bb07388ea664303d0d22b03cca11a46498b772d/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala#L721-L748

In python, it belongs to `Predicate Functions`
https://github.com/apache/spark/blob/8bb07388ea664303d0d22b03cca11a46498b772d/python/docs/source/reference/pyspark.sql/functions.rst?plain=1#L514-L520

**Review by MaxGekk — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by panbingkun** [comment]
@HyukjinKwon 
Are the above two questions worth doing? To summarize:
1. Make [FunctionRegistry](https://github.com/apache/spark/blob/8bb07388ea664303d0d22b03cca11a46498b772d/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala#)'s classification more accurate
2. Align Scala and Python side classification.

**Pull request closed without merging**
