### PR TITLE
[SPARK-34407][K8S] KubernetesClusterSchedulerBackend.stop should clean up K8s resources

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to fix `KubernetesClusterSchedulerBackend.stop` to wrap `super.stop` with `Utils.tryLogNonFatalError`.

### Why are the changes needed?

[CoarseGrainedSchedulerBackend.stop](https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/scheduler/cluster/CoarseGrainedSchedulerBackend.scala#L559) may throw `SparkException` and this causes K8s resource (pod and configmap) leakage.

### Does this PR introduce _any_ user-facing change?

No. This is a bug fix.

### How was this patch tested?

Pass the CI with the newly added test case.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Could you review this, @viirya ?

**Review by viirya — APPROVED** [review]
lgtm

**Comment by dongjoon-hyun** [comment]
Thank you so much, @viirya !

**Comment by dongjoon-hyun** [comment]
Sorry for updating after approval. I just simplified the test code like the following.
```scala
- val backend = spy(schedulerBackendUnderTest)
- backend.start()
+ schedulerBackendUnderTest.start()
```

**Comment by dongjoon-hyun** [comment]
Merged to master/3.1/3.0/2.4. This is not a blocker for RC vote.
cc @HyukjinKwon

**Comment by HyukjinKwon** [comment]
👌

**Pull request closed without merging**
