### PR TITLE
[SPARK-25170][DOC] Add list and short description of Spark Executor Task Metrics to the documentation.

### PR DESCRIPTION
**Pull request by LucaCanali**
## What changes were proposed in this pull request?

Add description of Executor Task Metrics to the documentation.

### CODE REVIEW

**Comment by kiszk** [comment]
LGTM cc @jiangxb1987 @srowen

**Review by srowen — APPROVED** [review]
The docs looks OK. I guess these weren't documented before? I spot-checked the units on a few metrics and they're right. I guess it's a little unfortunate there are some ns and ms times in here, but not a problem.

**Comment by LucaCanali** [comment]
Thanks @srowen for reviewing this. The metrics are commented in the source code of TaskMetrics class, I took most of the descriptions from there, adding some additional explanations where needed. Indeed I agree that the fact that time units are not uniform is a bit incovenient.

**Comment by srowen** [comment]
Merged to master/2.4

**Comment by kiszk** [comment]
Yes, time unit looks confusing, but not a problem. In general, due to APIs, elapsed time is `ms`, and CPU time is `ns`.

**Pull request closed without merging**
