### PR TITLE
[SPARK-10861] Add range support

### PR DESCRIPTION
**Pull request by JihongMA**
Adding range support through DeclarativeAggregate API, also prototyped an alternative ImperativeAggregate implementation as well for perf comparison,  DeclarativeAggregate perform better with codegen enabled.

### CODE REVIEW

**Comment by rxin** [comment]
Is this a common function in other databases?

**Comment by JihongMA** [comment]
Range is generally included in Univariate Stats.   but Hive doesn't support it as built-in UDF, just checked.

**Comment by rxin** [comment]
I'm mostly wondering if "range" is the proper name for this. Also seems it's super easy to compute: max(c) - min(c). Does it really justify having all of these code for it?

**Comment by JihongMA** [comment]
it is named "range" as part of dispersion measure within Univariate Stats.  this is a sub-task under Univariate Stats umbrella JIRA (SPRK-10384)

**Comment by rxin** [comment]
@JihongMA  I did a bit research and also talked to @mengxr. I don't think this range function provides enough value (since it is just max - min for users) to justify adding it, because:

1. It is non-obvious what range means from the name.
2. There is already a range function on SQLContext. This one is just semantically confusing, but not incompatible since they are in different namespace.
3. There is already a range function in Python, which is incompatible with the range here.

I'm going to close the JIRA ticket as won't fix. Sorry about it.

**Comment by yhuai** [comment]
@JihongMA How about we close this PR for now and revisit it later if necessary? Thanks!

**Comment by JihongMA** [comment]
@yhuai sure, I am closing it now.

**Pull request closed without merging**
