### PR TITLE
[SPARK-8911] Fix local mode endless heartbeats

### PR DESCRIPTION
**Pull request by andrewor14**
As of #7173 we expect executors to properly register with the driver before responding to their heartbeats. This behavior is not matched in local mode. This patch adds the missing event that needs to be posted.

### CODE REVIEW

**Comment by andrewor14** [comment]
retest this please

**Comment by vanzin** [comment]
LGTM.

**Comment by shivaram** [comment]
@andrewor14 can you merge this if this is ready ? The log messages make testing / debugging on a local shell very painful.

**Comment by andrewor14** [comment]
Ok, merging into master.

**Pull request closed without merging**
