### PR TITLE
[SPARK-38572][BUILD] Setting version to 3.4.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by MaxGekk**
### What changes were proposed in this pull request?

This PR aims to update `master` branch version to 3.4.0-SNAPSHOT.

### Why are the changes needed?

Start to prepare Apache Spark 3.4.0 and the published snapshot version should not conflict with `branch-3.3`.

### Does this PR introduce _any_ user-facing change?

N/A.

### How was this patch tested?

Pass the CIs.

### CODE REVIEW

**Comment by MaxGekk** [comment]
I made similar changes as in the PR https://github.com/apache/spark/pull/33196 . @dongjoon-hyun @srowen Could you review this, please.

**Review by dongjoon-hyun — APPROVED** [review]
Thank you, @MaxGekk . +1, LGTM.
I also agree with @srowen 's comment. We can do that here or later seperately.

**Comment by MaxGekk** [comment]
> We can do that here or later seperately.

I would prefer to do that separately if you don't mind.

**Comment by dongjoon-hyun** [comment]
+1 for that from my side, @MaxGekk .

**Comment by dongjoon-hyun** [comment]
cc @tgravescs since he asked version bump-up too in the dev mailing list.

**Comment by dongjoon-hyun** [comment]
To @srowen , your request is reasonable and it requires some audit like the following. So, if you don't mind, shall we let @MaxGekk proceed the audit separately?
- https://github.com/apache/spark/pull/33199/files

**Comment by srowen** [comment]
That's fine by me. It _shouldn't_ cause a problem to remove the exclusions that are irrelevant - if it does, we have a problem! but can be handled separately

**Review by tgravescs — APPROVED** [review]
looks good. thanks for updating.

**Comment by dongjoon-hyun** [comment]
Thank you, @MaxGekk , @srowen , @tgravescs . Merged to master for Apache Spark 3.4.0.

**Pull request closed without merging**
