### PR TITLE
[SPARK-42340][CONNECT][PYTHON] Implement Grouped Map API

### PR DESCRIPTION
**Pull request by xinrong-meng**
### What changes were proposed in this pull request?
Implement Grouped Map API:`GroupedData.applyInPandas` and `GroupedData.apply`.

### Why are the changes needed?
Parity with vanilla PySpark.

### Does this PR introduce _any_ user-facing change?
Yes. `GroupedData.applyInPandas` and `GroupedData.apply` are supported now, as shown below.
```sh
>>> df = spark.createDataFrame([(1, 1.0), (1, 2.0), (2, 3.0), (2, 5.0), (2, 10.0)],("id", "v"))
>>> def normalize(pdf):
...     v = pdf.v
...     return pdf.assign(v=(v - v.mean()) / v.std())
... 
>>> df.groupby("id").applyInPandas(normalize, schema="id long, v double").show()

+---+-------------------+                                                       
| id|                  v|
+---+-------------------+
|  1|-0.7071067811865475|
|  1| 0.7071067811865475|
|  2|-0.8320502943378437|
|  2|-0.2773500981126146|
|  2| 1.1094003924504583|
+---+-------------------+
```

```sh
>>> @pandas_udf("id long, v double", PandasUDFType.GROUPED_MAP)
... def normalize(pdf):
...     v = pdf.v
...     return pdf.assign(v=(v - v.mean()) / v.std())
... 
>>> df.groupby("id").apply(normalize).show()
/Users/xinrong.meng/spark/python/pyspark/sql/connect/group.py:228: UserWarning: It is preferred to use 'applyInPandas' over this API. This API will be deprecated in the future releases. See SPARK-28264 for more details.
  warnings.warn(
+---+-------------------+                                                       
| id|                  v|
+---+-------------------+
|  1|-0.7071067811865475|
|  1| 0.7071067811865475|
|  2|-0.8320502943378437|
|  2|-0.2773500981126146|
|  2| 1.1094003924504583|
+---+-------------------+
```

### How was this patch tested?
(Parity) Unit tests.

SPARK-41661

### CODE REVIEW

**Comment by xinrong-meng** [comment]
@zhengruifeng @HyukjinKwon May I get a review, please?

**Comment by zhengruifeng** [comment]
A grouped data can also be created via `df.roll/cube/pivot`, do they works with `applyInPandas` ?

**Review by HyukjinKwon — APPROVED** [review]
The change itself LGTM

**Comment by xinrong-meng** [comment]
As long as the input relation is GroupedData, `applyInPandas` works.

An example is as shown below:
```sh
>>> df = spark.createDataFrame([(1, 1.0), (1, 2.0), (2, 3.0), (2, 5.0), (2, 10.0)],("id", "v"))
>>> 
>>> def normalize(pdf):
...     v = pdf.v
...     return pdf.assign(v=(v - v.mean()) / v.std())
... 

>>> df.cube('id').applyInPandas(normalize, schema="id long, v double").show()
+---+-------------------+
| id|                  v|
+---+-------------------+
|  1|-0.7071067811865475|
|  1| 0.7071067811865475|
|  2|-0.8320502943378437|
|  2|-0.2773500981126146|
|  2| 1.1094003924504583|
+---+-------------------+

>>> df.rollup('id', df.v).applyInPandas(normalize, schema="id long, v double").show()
+---+----+                                                                      
| id|   v|
+---+----+
|  1|null|
|  1|null|
|  2|null|
|  2|null|
|  2|null|
+---+----+

# I didn't find `df.pivot` in vanilla PySpark.
```
(the same result as vanilla PySpark).

CC @zhengruifeng

**Review by zhengruifeng — APPROVED** [review]
It is another topic whether we should support this function with group types other than `groupby`

**Comment by xinrong-meng** [comment]
Rebased to the latest master; no new changes after reviews.

**Comment by HyukjinKwon** [comment]
Merged to master and branch-3.4.

**Comment by HyukjinKwon** [comment]
It has a conflict with 3.4. mind creating a PR to backport this?

**Comment by xinrong-meng** [comment]
Sure, I'll do. Thanks @HyukjinKwon!

**Pull request closed without merging**
