### PR TITLE
[SPARK-18971][Core]Upgrade Netty to 4.0.43.Final

### PR DESCRIPTION
**Pull request by zsxwing**
## What changes were proposed in this pull request?

Upgrade Netty to `4.0.43.Final` to add the fix for https://github.com/netty/netty/issues/6153 

## How was this patch tested?

Jenkins

### CODE REVIEW

**Comment by rxin** [comment]
LGTM

**Review by srowen — APPROVED** [review]

**Comment by zsxwing** [comment]
retest this please

**Comment by yhuai** [comment]
test this please

**Comment by srowen** [comment]
Merged to master

**Comment by parente** [comment]
Not sure where to ask this: is it reasonable to get this netty version update into Spark 2.1.2 in order to resolve the deadlock problem noted in the associated JIRA?

If there's a better place to ask, please let me know.

**Comment by srowen** [comment]
Low risk, I think, @zsxwing ? seems OK to backport

**Comment by zsxwing** [comment]
@srowen sounds good to me. 2.2.0 was out several months ago and I didn't see any issue caused by the new netty version.

**Comment by srowen** [comment]
Merged to 2.1 as well. I don't know if it will make it into 2.1.2 but think it will as we need a new RC now.

**Pull request closed without merging**
