### PR TITLE
[SPARK-41263][CONNECT][INFRA] Upgrade buf to 1.9.0

### PR DESCRIPTION
**Pull request by zhengruifeng**
### What changes were proposed in this pull request?
Upgrade buf to v1.9.0

### Why are the changes needed?
this upgrade don't change the generated proto files

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
existing CI and local check

### CODE REVIEW

**Comment by zhengruifeng** [comment]
cc @HyukjinKwon @grundprinzip

**Comment by amaliujia** [comment]
Could we not upgrade `buf` so often as this is a command line tool which is not installed through `pip` and `requirement.txt`?

Unless there is urgent fix or some feature useful or old version is deprecated, etc. otherwise it seems to not be useful to ask everyone upgrades their `buf` locally.

**Comment by zhengruifeng** [comment]
@amaliujia actually, v1.8.0 -> v1.9.0 doesn't change the generated python files right now, so it should be a good chance to avoid potential conflicts caused by upgrading in the future.

**Comment by amaliujia** [comment]
hmmm it is ok if this does not enforce everyone upgrade their command line toolchain.

not sure if there is future problem but sounds like now it is the same as 1.8

**Review by HyukjinKwon — APPROVED** [review]

**Comment by zhengruifeng** [comment]
merged into master, thanks

**Pull request closed without merging**
