### PR TITLE
[SPARK-36056][SQL] Combine readBatch and readIntegers in VectorizedRleValuesReader

### PR DESCRIPTION
**Pull request by sunchao**
### What changes were proposed in this pull request?

Combine `readBatch` and `readIntegers` in `VectorizedRleValuesReader` by having them share the same `readBatchInternal` method.

### Why are the changes needed?

`readBatch` and `readIntegers` share similar code path and this Jira aims to combine them into one method for easier maintenance.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Existing tests as this is just a refactoring.

### CODE REVIEW

**Comment by sunchao** [comment]
cc @viirya @cloud-fan @dongjoon-hyun could you take a look? thanks!

**Review by cloud-fan — APPROVED** [review]

**Comment by cloud-fan** [comment]
thanks, merging to master/3.2 (we have a major refactor in parquet reader in 3.2, and it's better to keep master and 3.2 in sync for the parquet reader codebase)

**Comment by dongjoon-hyun** [comment]
+1, LGTM. Thank you for making a PR and backporting this, @sunchao and @cloud-fan .

**Comment by sunchao** [comment]
Thanks @cloud-fan and @dongjoon-hyun ! yes +1 on merging to 3.2 too.

**Comment by viirya** [comment]
Oh, I missed this. Yea. LGTM. +1 for 3.2.

**Pull request closed without merging**
