### PR TITLE
[SPARK-13231] Make count failed values a user facing API.

### PR DESCRIPTION
**Pull request by ScrapCodes**

### CODE REVIEW

**Comment by ScrapCodes** [comment]
I have left-out the renaming for now, not sure about it.

**Comment by JoshRosen** [comment]
/cc @andrewor14, we should look at this PR since I know that we discussed making the metric-style accumulators a public API while working on that patch.

@ScrapCodes, if we do move forward with this I think we'll want to update the programming guide in order to help users discover this feature.

**Comment by ScrapCodes** [comment]
@JoshRosen Thanks for taking a look. I will update it, did you also consider renaming - or may be just updating the doc suffices ?

**Comment by ScrapCodes** [comment]
@andrewor14 Can you take a look ?

**Comment by andrewor14** [comment]
I'm hesitant about this because we would need to maintain backward compatibility if we make it fully public. All the exposed constructors will have to be there forever. If we do decide to do this we need to make sure we like the name because that can't change.

**Comment by andrewor14** [comment]
I just talked with @rxin and we decided that this flag isn't quite ready to be exposed yet. The problem is the default value (false) has weird semantics on stage retries; if you're counting the number of rows in your data and your stage was run twice, then you might get 2X the actual number of rows. This is what #11105 is looking at, and we might proceed from there.

Either way I think we should try to fix the default behavior before exposing a flag that we won't be able to change in the future. Let's keep the issue open but close this PR for now.

**Comment by ScrapCodes** [comment]
@andrewor14 As far as I knew, it worked fine. There is a check in Task.collectAccumulatorUpdates, you mean that check is not sufficient ? Ahh looking at the jira, I understood there are a lot more ways than just task failure that a stage is recomputed e.g. cache eviction. Correct me if I am wrong.

Alright closing this.

**Pull request closed without merging**
