### PR TITLE
[MLLIB] SPARK-1473, SPARK-1303: New Feature Selection and Discretization Algorithms 

### PR DESCRIPTION
**Pull request by sramirez**
**Information Theoretic Feature Selection Framework**

The present framework implements Feature Selection (FS) on Spark for its application on Big Data problems. This package contains a generic implementation of greedy Information Theoretic Feature Selection methods. The implementation is based on the common theoretic framework presented in [1]. Implementations of mRMR, InfoGain, JMI and other commonly used FS filters are provided. In addition, the framework can be extended with other criteria provided by the user as long as the process complies with the framework proposed in [1].

-- Improvements on FS:
- Support for sparse data (in progress).
- Pool optimization for high-dimensional 
- Improved performance: 150 seconds by selected feature for a 65M dataset with 631 attributes.

**Minimum Description Lenght Discretizer**

This package also contains an implementation of Fayyad's discretizer [2] based on Minimum Description Length Principle (MDLP) in order to treat non discrete datasets.

-- Improvements on discretizer:
- Support for sparse data.
- Multi-attribute processing. The whole process is carried out in a single step when the number of boundary points per attribute fits well in one partition (<= 100K boundary points per attribute).
- Support for attributes with a huge number of boundary points (> 100K boundary points per attribute). Extremely rare situation.

This work has associated two submitted contributions to international journals which will be attached to this request as soon as they are accepted This software has been proved with two large real-world datasets such as:
- A dataset selected for the GECCO-2014 in Vancouver, July 13th, 2014 competition, which comes from the Protein Structure Prediction field (http://cruncher.ncl.ac.uk/bdcomp/). The dataset has 32 million instances, 631 attributes, 2 classes, 98% of negative examples and occupies, when uncompressed, about 56GB of disk space.
- Epsilon dataset: http://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/binary.html#epsilon. 400K instances and 2K attributes.

Contributors
- Sergio Ramírez-Gallego (sramirez@decsai.ugr.es) (main contributor and maintainer).
- Héctor Mouriño-Talín (h.mtalin@udc.es)
- David Martínez-Rego (dmartinez@udc.es)

References

[1] Brown, G., Pocock, A., Zhao, M. J., & Luján, M. (2012). 
"Conditional likelihood maximisation: a unifying framework for information theoretic feature selection." 
The Journal of Machine Learning Research, 13(1), 27-66.

[2] Fayyad, U., & Irani, K. (1993).
"Multi-interval discretization of continuous-valued attributes for classification learning."

### CODE REVIEW

**Comment by mengxr** [comment]
@sramirez Thanks for contributing! To expedite the code review, please do consider splitting this PR into small PRs. We can start with the proposal for feature selection interfaces, and then algorithms. JIRAs like "Feature selection for high dimensional dataset" are used for general discussion. We should create concrete JIRAs for each part of this PR.

In the feature selection interface PR, please keep the public APIs minimal and list break changes if there are any. We should avoid any break changes if they are unnecessary. Please also check the Java API compatibility by creating unit tests in Java. It would be nice to have a design doc posted on the JIRA page, e.g., https://issues.apache.org/jira/browse/SPARK-3530.

For each algorithm PR, please list references and document its scalability with some benchmark results. If there are changes to the original algorithm, it would be nice to implement the original algorithm exactly in the first PR and then make changes in follow-up PRs.

**Comment by sramirez** [comment]
@mengxr OK! I will divide this PR in two parts: one for discretization and the other for the feature selection framework. And I will create two concrete JIRAs for each part.

Regarding feature selection interface, maybe I should leave the ChiModel without any change. I propose two interfaces for each task: DiscretizerModel and SelectorModel. SelectorModel is a copy from ChiSqSelectorModel that I made as common interface for my FS algorithms.

The references are listed in this PR. We have made a redesign of this state-of-the-art algorithms following our own choices. So, the original algorithm are thought to be executed sequentially. If you want, I can give you some results, as I did for this first algorithm. However,  the complete results are not public as they have been submitted to a non-free access scientist journal (Machine Learning Journal).

**Comment by srowen** [comment]
Are the two follow-up PRs replacing this one? then can this be closed?
I also generally ask: is the algorithm something that can start life outside Spark? I think that's a better path in general. However adding generic interfaces to the ML framework seems like something that does belong in core Spark.

**Comment by sramirez** [comment]
Yes, this PR can be closed. Here, we propose two distributed version for two sound algorithms in data reduction. I have included the two associated references. The generic interface is necessary if we want to homogeneize the selection and discretization module. The only thing I have done is to remove the selector model from ChiSq and to put it in a general interface for the subsequent selection methods. The same for the method compress used in this method. If not so, the code will be repeated across many methods.

**Pull request closed without merging**
