### PR TITLE
[SPARK-6700] [yarn] Re-enable flaky test.

### PR DESCRIPTION
**Pull request by vanzin**
Test runs have been successful on jenkins. So let's re-enable the test and look out for any failures, and fix things appropriately.

### CODE REVIEW

**Comment by vanzin** [comment]
Jenkins, retest this please.

**Comment by vanzin** [comment]
Jenkins, retest this please.

**Comment by vanzin** [comment]
Jenkins, retest this please.

**Comment by rxin** [comment]
Jenkins, retest this please.

**Comment by rxin** [comment]
It just doesn't fail when you wanted it to fail!

**Comment by vanzin** [comment]
Jenkins, retest this please.

**Comment by vanzin** [comment]
Jenkins, retest this please.

**Comment by vanzin** [comment]
Jenkins, retest this please.

**Comment by vanzin** [comment]
Jenkins, retest this please.

**Comment by vanzin** [comment]
Alright, one last time. If this passes, I'd suggest re-enabling the test, so that if it's still flaky we can look at logs and figure out why. (I worked with Sean and have permissions to look at all the needed files in case that happens.)

/cc @rxin @davies

**Comment by davies** [comment]
I had triggered several runs in a row, waiting for the results. If they all passed, we could merge this.

**Comment by andrewor14** [comment]
Alright, it seems relatively stable. I'm going to merge it into master.

**Pull request closed without merging**
