### PR TITLE
[SPARK-11569] [ML] Fix StringIndexer to handle null value properly

### PR DESCRIPTION
**Pull request by jliwork**
The root cause of this bug is that StringIndexer is unable to handle input column with null value. With my fix, null value can also be indexed just like any other string value.

@jkbradley @holdenk Please let me know of any comments. Thanks!

### CODE REVIEW

**Comment by jliwork** [comment]
@mengxr @jkbradley Can you please help to take a look at my fix? Thanks!

**Comment by mengxr** [comment]
ok to test

**Comment by holdenk** [comment]
So if I understand the change correctly this will treat null values the same as the string "null" yes? If we do this we should document that behavior (it seems like a reasonable approach provided this is the standard but maybe add a comment so people aren't caught by surprise)? It might also make sense to have this be configurable (as per @jkbradley's comments in the JIRA).

**Comment by dragos** [comment]
There are 174 commits in this PR, but I think you only need 1. Could you please rebase on master? It would make life easier for reviewers (for instance, this PR appears in the Mesos section on the [spark-prs](https://spark-prs.appspot.com/#mesos) site, presumably because the other commits touch something on Mesos).

**Comment by jliwork** [comment]
@dragos thanks for pointing it out. i am having some problem with rebase and will close this PR.

**Pull request closed without merging**
