### PR TITLE
[SPARK-28842][DOC]Cleanup the formatting/trailing spaces in the K8s integration testing guide

### PR DESCRIPTION
**Pull request by alaazbair**
### What changes were proposed in this pull request?
Removing the trailing spaces in resource-managers/kubernetes/integration-tests/README.md

### Why are the changes needed?
Improve the formatting of the K8s integration testing guide

### Does this PR introduce any user-facing change?
No

### How was this patch tested?
I have run all tests with ./dev/run-tests but no tests were added because the only change I did was on the README file and I only removed spaces and one empty line.

### CODE REVIEW

**Comment by alaazbair** [comment]
Could someone please review my PR.

**Comment by srowen** [comment]
Why would this matter though? they do not affect the rendered doc.

**Comment by dongjoon-hyun** [comment]
Hi, @alaazbair . Thank you for making a PR, but shall we close this PR if there is no justification?

**Comment by alaazbair** [comment]
Hi @srowen @dongjoon-hyun , sorry for the late response. I think this change will matter the most when between commits we get diffs polluted with unchanged lines (during a change in the documentation, an existing trailing space was removed ). In addition trailing spaces could break some text editors for instance pressing END when the cursor is on a line containing trailing spaces, will not move the cursor to the end of the line and this can be annoying if the formatting isn't consistent throughout the file.

Besides this I can't think of any other justification. if you think this change isn't justified, I will gladly close the PR.

Cheers.

**Comment by srowen** [comment]
Generally I wouldn't make this change; IDEs shouldn't be adding/removing whitespace automatically for just this reason. The other downside is the very small additional chance of spurious merge conflicts, if we try to back-port a doc change that conflicts.

That said, for a first-time contributor we're a lot more open to small changes, and this only affects one file. (By the same token, this won't affect any other .md files, and I don't think we'd change them all).

**Pull request closed without merging**
