### PR TITLE
[SPARK-14681][ML] Added getter for impurityStats

### PR DESCRIPTION
**Pull request by shaynativ**
Adding a simple getter method for the impurity stats.

I'm using this in https://github.com/RedisLabs/spark-redis-ml to export the stats to Redis.

No tests added.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Hi @shaynativ, this PR looks a non-trivial change that needs a JIRA. Please refer http://spark.apache.org/contributing.html.

**Comment by shaynativ** [comment]
It looks like there is a JIRA issue for this:
[SPARK-14681](https://issues.apache.org/jira/browse/SPARK-14681)
How should I proceed?

**Comment by HyukjinKwon** [comment]
If you think it is the JIRA, fix the title to `[SPARK-14681][ML] Added getter for impurityStats`. That would make a link to the JIRA automatically.

**Comment by jkbradley** [comment]
@shaynativ Sorry for the inactivity here.  Btw, for the JIRA & PR title question above, I'd recommend checking out http://spark.apache.org/contributing.html

Since @WeichenXu123 opened a fresh PR for this, would you mind working with him on it?
We can close this issue / PR for now.  Thank you!

**Pull request closed without merging**
