### PR TITLE
[SPARK-7467] Dag visualization: treat checkpoint as an RDD operation

### PR DESCRIPTION
**Pull request by andrewor14**
Such that a checkpoint RDD does not go into random scopes on the UI, e.g. `take`. We've seen this in streaming.

### CODE REVIEW

**Comment by andrewor14** [comment]
@zsxwing @tdas

**Comment by zsxwing** [comment]
I just tried this PR. But it looks not work. 

Test codes:
```Scala
    sc.setCheckpointDir(".")
    val r1 = sc.parallelize(1 to 100)
    r1.checkpoint()
    r1.map(_ + 2).filter(_ < 50).collect()
    r1.map(_ + 2).filter(_ < 50).collect()
```

I opened the spark shell and typed the above codes. And the dag of job 2 is 
screen shot 2015-05-08 at 10 24 14 am

The first one is still `collect`.

**Comment by andrewor14** [comment]
Oops, thanks for the screen shot. It appears that it's still not being captured correctly.

**Comment by andrewor14** [comment]
By the way I have a simpler reproduction:
```
sc.setCheckpointDir("/tmp")
val rdd = sc.parallelize(1 to 10)
rdd.checkpoint()
rdd.take(10)
```
Since the `take` runs multiple jobs and we do the actual checkpointing at the end of each job.

**Comment by andrewor14** [comment]
I think I fixed it in the latest commit.

**Comment by andrewor14** [comment]
retest this please

**Comment by andrewor14** [comment]
Ok I'm merging this into master 1.4.

**Pull request closed without merging**
