### PR TITLE
[SPARK-4989][CORE] backport for branch-1.0(-jdbc) catch eventlog exception for wrong eventlog conf

### PR DESCRIPTION
**Pull request by liyezhang556520**
JIRA is [SPARK-4989](https://issues.apache.org/jira/browse/SPARK-4989)

### CODE REVIEW

**Comment by andrewor14** [comment]
This is failing due to a known issue in branch-1.0. I will spend some time to investigate the failure shortly.

**Comment by JoshRosen** [comment]
Jenkins, retest this please.

**Comment by liyezhang556520** [comment]
Jenkins, retest this please.

**Comment by srowen** [comment]
Heh, are we back-porting to 1.0.x anyway at this point? I think it has some known problems with tests. If not, we could just close all this out. But I'm interested in opinions on whether there would ever be a new 1.0.x release.

**Comment by andrewor14** [comment]
@srowen we should still back port to branch-1.0. The reason why these PRs haven't been merged is because the context cleaner suite hasn't been passing and no one has really looked at it yet. I closed my other UI port PR by mistake when I was deleting my github branches, but before I reopen it I would like to fix the test first (though unfortunately that is of lower priority than fixing flaky tests in master branch).

**Comment by srowen** [comment]
I think we should close this at this point. With 1.4 about to come out, I don't see any expectation of new releases from 1.0.x or even probably 1.1.x. It's back-ported to 1.1.x

**Comment by andrewor14** [comment]
Ok, now that 1.4 is basically released, @liyezhang556520 would you mind closing this?

**Pull request closed without merging**
