### PR TITLE
[SPARK-5604[MLLIB] remove checkpointDir from LDA

### PR DESCRIPTION
**Pull request by mengxr**
`checkpointDir` is a Spark global configuration. Users should set it outside LDA. This PR also hides some methods under `private[clustering] object LDA`, so they don't show up in the generated Java doc (SPARK-5610).

@jkbradley

### CODE REVIEW

**Comment by mengxr** [comment]
test this please

**Comment by jkbradley** [comment]
The changes LGTM

One question: Does private[clustering] on "object LDA" not hide stuff in Java docs because it's an object (not a class)?

**Comment by mengxr** [comment]
genjavadoc maps methods to Java public/protect/private. I haven't found a way to hide public methods under a package private companion object yet ...

**Comment by mengxr** [comment]
Merged into master and branch-1.3.

**Pull request closed without merging**
