### PR TITLE
[SPARK-975][CORE] Visual debugger of stages and callstacks

### PR DESCRIPTION
**Pull request by dnprock**

### CODE REVIEW

**Comment by wbraik** [comment]
Does anyone have a good example of an application which produces multiple (different) jobs, that we could use to test this on ?

**Comment by velvia** [comment]
@wbraik We would love to test this for the Spark job server.  Each context can run multiple job groups each of which may have multiple stages.  I can probably give you real examples by asking our user group, but it wouldn't be too hard to come up with an interesting example that you could run yourself.

**Comment by JoshRosen** [comment]
Spark 1.4 added DAG visualizations to the UI as part of the https://issues.apache.org/jira/browse/SPARK-6942 umbrella, so I think that we can close this issue now.

**Comment by dnprock** [comment]
I notice the new design has separated stages. It may look repetitive if stages go through similar calls. @JoshRosen thanks for letting me know. Close this.

**Pull request closed without merging**
