### PR TITLE
[SPARK-46737][SQL][TESTS] Use the default ORC compression in OrcReadBenchmark

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to use the default ORC compression in `OrcReadBenchmark`.
 
### Why are the changes needed?

After SPARK-46648, Apache Spark will use `Zstandard` as the default ORC compression codec.
We need to benchmark this one.

### Does this PR introduce _any_ user-facing change?

No, this is a test-only PR.

### How was this patch tested?

Manual review.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
I'll convert this into a normal PR after adding the benchmark result. 
Thank you, @HyukjinKwon !

**Review by MaxGekk — COMMENTED** [review]
@dongjoon-hyun Just in case, the benchmark belongs to hive (at least it is in `sql/hive`).  Which codec does hive use, and has it switched to zstandard already?

**Comment by dongjoon-hyun** [comment]
> @dongjoon-hyun Just in case, the benchmark belongs to hive (at least it is in `sql/hive`). Which codec does hive use, and has it switched to zstandard already?

Ah, you're right, @MaxGekk .

I forgot that `org.apache.spark.sql.hive.orc.OrcFileFormat` doesn't support ZStandard.

Let me close this PR. Sorry for making you confused, @HyukjinKwon and @MaxGekk .

For ORC Zstandard benchmark, let me consider how to put it into the Spark code base.

**Comment by dongjoon-hyun** [comment]
Since the last commit is only adding the benchmark test result, let me merge this~

**Comment by dongjoon-hyun** [comment]
Thank you, @HyukjinKwon and @MaxGekk !

**Pull request closed without merging**
