### PR TITLE
[SPARK-40852][CONNECT][PYTHON][FOLLOWUP] Make `Summary` a separate proto plan

### PR DESCRIPTION
**Pull request by zhengruifeng**
### What changes were proposed in this pull request?
Make `Summary` a separate proto plan

### Why are the changes needed?
as per the discussion https://github.com/apache/spark/pull/38578#discussion_r1017875279 , those stats function cannot share fields

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
updated UT

### CODE REVIEW

**Comment by zhengruifeng** [comment]
cc @cloud-fan  @HyukjinKwon @amaliujia

**Review by cloud-fan — APPROVED** [review]

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Comment by zhengruifeng** [comment]
thank you @cloud-fan  for reivews

**Comment by amaliujia** [comment]
LGTM!

**Pull request closed without merging**
