### PR TITLE
[SPARK-36698][SQL] Allow expand 'quotedRegexColumnNames' in all expressions when it’s expanded to one named expression

### PR DESCRIPTION
**Pull request by planga82**
### What changes were proposed in this pull request?

With `spark.sql.parser.quotedRegexColumnNames=true` regular expressions are not allowed in expressions like  
``` SELECT `col_.*`/exp FROM (SELECT 3 AS col_a, 1 as exp) ``` 

This PR propose to improve this behavior and allow this regular expression when it expands to only one named expression. It’s the same behavior in Hive.

Example 1:
```
SELECT `col_.*`/exp FROM (SELECT 3 AS col_a, 1 as exp) 
```
col_.* expands to col_a:  OK

Example 2:
```
SELECT `col_.*`/col_b FROM (SELECT 3 AS col_a, 1 as col_b) 
```
col_.* expands to (col_a, col_b) : Fail like now

Example 3:
```
SELECT `col_a`/exp FROM (SELECT 3 AS col_a, 1 as exp) 
```
col_a expands to col_a:  OK

### Why are the changes needed?

Improve this feature and approaching hive behavior

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Unit testing

### CODE REVIEW

**Comment by planga82** [comment]
CC @HyukjinKwon
Thanks!

**Comment by HyukjinKwon** [comment]
I have less context on this.  cc @cloud-fan, @janewangfb and @gatorsmile from git-blame.

**Comment by HyukjinKwon** [comment]
BTW, is this a valid syntax in other DBMSes or ANSI?

**Comment by planga82** [comment]
I haven't found functionality like this in other DBMS or ANSI. Hive is the only reference I have found and I believe it was the reference when the functionality was developed.

**Comment by cloud-fan** [comment]
Personally, I think this feature looks confusing. Can we get some feedback from our real users first? By sending emails to user/dev list.

**Pull request closed without merging**
