### PR TITLE
[SPARK-26585][K8S] Add additional integration tests for K8s Scheduler Backend

### PR DESCRIPTION
**Pull request by ramaddepally**
## What changes were proposed in this pull request?

Added following integration tests to cover additional tests for K8s scheduler backend functionality
- Run SparkPi with driver and executor image specified independently
- Run SparkPi with custom cpu requirements
- Run SparkPi with custom memory and memory overhead factor requirements
- Run SparkPi with custom memory and memory overhead requirements

## How was this patch tested?

Ran K8s integration tests locally on minikube and all tests succeeded including new ones.

### CODE REVIEW

**Comment by felixcheung** [comment]
Jenkins, retest this please

**Comment by ramaddepally** [comment]
> Hi, @ramaddepally . The Kubernetes integration test failure is irrelevant to this PR.

Thanks @dongjoon-hyun. I will look into this failure today.

**Comment by ramaddepally** [comment]
The compilation failure in integration tests seems to be caused due to changes in SPARK-26491 https://github.com/apache/spark/commit/1a641525e60039cc6b10816e946cb6f44b3e2696

@dongjoon-hyun fixed this compilation failure in https://github.com/apache/spark/commit/b316ebf0c2bc1736cad5c429ec1eb71a4c987d87

So, we should be good to run these tests again.

**Comment by ramaddepally** [comment]
Jenkins, retest this please

**Comment by vanzin** [comment]
I'm a little skeptical of these tests. What benefit do they bring on top of a unit test that checks that these properties are set in the pod descriptor sent to the k8s server?

And even in the case that there is a tangible benefit, why do they need to be separate tests? Why not set these properties in an existing test? Integration tests are expensive to run, adding a bunch of small tests to check specific things means you're wasting 20-40s to test a single config property.

(The latter, btw, also applies to a bunch of existing tests...)

**Comment by ramaddepally** [comment]
> I'm a little skeptical of these tests. What benefit do they bring on top of a unit test that checks that these properties are set in the pod descriptor sent to the k8s server?

Setting properties and verifying they are set is very generic. I do not see any tests (unit tests or integration tests) covering memory and CPU request cases. Especially memory requests are not straight forward as we see [here](https://github.com/apache/spark/blob/master/resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/k8s/features/BasicDriverFeatureStep.scala#L48-L67) and [here](https://github.com/apache/spark/blob/master/resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/k8s/features/BasicExecutorFeatureStep.scala#L52-L68). Without tests around this are, there is not guard for this code. I do not have any preference whether they should be unit test or integration tests, but there should be tests for these.

> And even in the case that there is a tangible benefit, why do they need to be separate tests? Why not set these properties in an existing test? Integration tests are expensive to run, adding a bunch of small tests to check specific things means you're wasting 20-40s to test a single config property.

This is something I can do (consolidate them into existing tests), if we agree there is benefit to these tests based on my above comments.

**Comment by vanzin** [comment]
I'd prefer to have as much as possible in unit tests, and only have integration tests for things that are just not possible to test reliably in unit tests. If unit tests are lacking in coverage, then more unit tests should be added.

**Comment by dongjoon-hyun** [comment]
+1 for @vanzin comment.
Could you close this PR and JIRA issue, @ramaddepally ?

**Pull request closed without merging**
