### PR TITLE
[SPARK-18450][ML] Scala API Change for LSH AND-amplification

### PR DESCRIPTION
**Pull request by Yunni**
## What changes were proposed in this pull request?
Implemented a new Param numHashFunctions as the dimension of AND-amplification for Locality Sensitive Hashing. Now the hash of each feature in LSH is an array of size numHashTables while each element in the array is a vector of size numHashFunctions.

Two features are in the same hash bucket iff ANY pair of the vectors are equal (OR-amplification). Two vectors are equal iff ALL pair of the vector entries are equal (AND-amplification).

Will create follow-up PRs for Python API and Doc/Examples.

## How was this patch tested?
By running unit tests MinHashLSHSuite and BucketedRandomProjectionLSHSuite.

### CODE REVIEW

**Comment by MLnick** [comment]
cc @sethah @jkbradley

**Comment by merlintang** [comment]
It seems this patch provide the AND-OR amplification. Can we provide the option for users to choose the OR-AND amplification as well?

**Comment by Yunni** [comment]
@merlintang We use AND-OR in both approxNearestNeighbor and approxSimilarityJoin, and it's more difficult for approxSimilarityJoin to adopt OR-AND than AND-OR.

My understanding: for a (d1, d2, p1, p2)-sensitive hash families, AND-OR can increase p1 and decrease p2 just like OR-AND does. What are the use cases to use OR-AND rather than AND-OR?

**Comment by merlintang** [comment]
@Yunni  I agree with you that the current NN search and Join are using the AND-OR. We can discuss how to use the OR-AND for that two searching as well.  

For the OR-AND option, it is used when the effective threshold is low. please refer to the table in the page 31 and 33. http://web.stanford.edu/class/cs345a/slides/05-LSH.pdf

You can notice, when the p is lower, the OR-AND can amplify the hash family possibility from 0.0985 to 0.5440.

**Comment by Yunni** [comment]
@merlintang Sorry I still don't quite get why we need to support OR-AND when the effective threshold is low. My understanding is that we can always tune numHashTables and numHashFunctions for AND-OR to make the possibility as good as OR-AND. Please correct me if I am wrong.

My concerns on supporting OR-AND are the followings:
(1) We probably need some backward incompatible API changes. `Array[Vector]`, numHashTables, numHashFunctions seems to make less sense for OR-AND.
(2) To avoid broadcast join, we will need a very different and complicated mechanism for the join step in approxSimilarityJoin for OR-AND.
(3) I am thinking about building index to improve performance for nearest neighbor (https://docs.google.com/document/d/1opWy2ohXaDWjamV8iC0NKbaZL9JsjZCix2Av5SS3D9g/edit). Supporting OR-AND will make the index less efficient when we get records given hash buckets.

@jkbradley @sethah @MLnick Any thoughts?

**Comment by merlintang** [comment]
@Yunni Yes, we can use the AND-OR  to increase the possibility by having more the numHashTables and numHashFunctions. For the further user extension, if users have a hash function with lower possibility, the OR-AND could be used.  

(1) I do not need to change Array[Vector], numHashTables, numHashFunctions, we need to change the function to compute the hashDistance (i.e.,hashDistance), as well as the sameBucket function in the approxNearestNeighbors.

(3) for the simijoin, I have one question here, if you do a join based on the hashed value of input tuples, the joined key would be array(vector). Am i right?  if it is, does this meet OR-amplification? please clarify me if I am wrong. 

(4) for the index part, I think it would be work. it is pretty similar as the routing table idea for the graphx.  thus, I think we can create a other data frame with the same partitioner of the input data frame, then, the newly created data frame would contain the index for the input tables without disturbing the data frame. 

5) the other major concern would be memory overhead, Can we reduce the memory usage for the output hash value i.e., array(vector)? Because the users said that the current way spent extensive of memory. therefore, one way we can do using the bit to respected the hashed value for the min-hash, the other way would use the sparse vector.  what do you think ?

**Comment by Yunni** [comment]
@merlintang 
(1) `hashDistance` is only used for multi-probe NN Search. The term `numHashTables`, `numHashFunctions` is very hard to interpret in OR-AND cases.

(2) For similarity join, we actually first do explode and then join. The join key would be type of vector. 

(3) Yes. However, in order to get rows using hashes, we need to do intersections on large sets of rows. While in AND-OR cases, we do union of small sets of rows, which is more efficient.

I also suggest we limit the scope to the implementation of AND-amplification here. We can open other tickets to discuss memory issues, etc.

**Comment by merlintang** [comment]
@Yunni Ok, if we want to move this quicker, we can keep the current AND-OR implementation.

(2)(3) you mention that you explode the inner table (dataset). Does it mean for each tuple of inner table (says t_i) and multiple hash functions (say h_0, h_1, ... h_l) . you create multiple rows like (h_0, t_i), (h_1, t_i), ... (h_l, t_i). am i correct?

**Comment by Yunni** [comment]
@merlintang Not exactly. Each row will explode to L rows, where L is the number of hash tables. Like the following:
```
+--------------------+-----+--------------------+
|            datasetA|entry|           hashValue|
+--------------------+-----+--------------------+
|[[-10.0,-10.0],Wr...|    0|[-2.0,-2.0,3.0,-2.0]|
|[[-10.0,-10.0],Wr...|    1|[0.0,-3.0,-1.0,-2.0]|
|[[-10.0,-9.0],Wra...|    0|[-2.0,-2.0,3.0,-2.0]|
|[[-10.0,-9.0],Wra...|    1|[0.0,-3.0,-1.0,-2.0]|
|[[-10.0,-8.0],Wra...|    0|[-2.0,-2.0,3.0,-1.0]|
|[[-10.0,-8.0],Wra...|    1| [0.0,-3.0,0.0,-2.0]|
```
You can look at the code here: https://github.com/apache/spark/blob/master/mllib/src/main/scala/org/apache/spark/ml/feature/LSH.scala#L238

**Comment by Yunni** [comment]
The number of rows would be O(LN). The memory usage will be different as the size of each row has changed before and after the explode. Also the Catalyst Optimizer may do projections during join which can also change the size of each row.

**Comment by jkbradley** [comment]
Github isn't handling the merge well, so you might try rebasing

**Comment by Yunni** [comment]
Looks like the rebase is making it even worse. I will reopen a PR.

**Pull request closed without merging**
