### PR TITLE
[SPARK-45546][BUILD][FOLLOW-UP] Remove snapshot repo mistakenly added

### PR DESCRIPTION
**Pull request by HyukjinKwon**
### What changes were proposed in this pull request?

This PR removes snapshot repo mistakenly added in `pom.xml`

### Why are the changes needed?

To clean up.

### Does this PR introduce _any_ user-facing change?

No, dev-only.

### How was this patch tested?

CI in this PR

### Was this patch authored or co-authored using generative AI tooling?

No

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
cc @LuciferYang

**Review by LuciferYang — APPROVED** [review]
Very sorry, I forgot to delete the code tested locally.

**Comment by dongjoon-hyun** [comment]
Thank you, @HyukjinKwon and @LuciferYang .
Merged to master.

**Review by beliefer — COMMENTED** [review]
LGTM later.

**Pull request closed without merging**
