### PR TITLE
[SPARK-33725][BUILD][3.1] Upgrade snappy-java to 1.1.8.2

### PR DESCRIPTION
**Pull request by viirya**
### What changes were proposed in this pull request?

This upgrades snappy-java to 1.1.8.2.

### Why are the changes needed?

Minor version upgrade that includes:

- [Fixed](https://github.com/xerial/snappy-java/pull/265) an initialization issue when using a recent Mac OS X version
- Support Apple Silicon (M1, Mac-aarch64)
- Fixed the pure-java Snappy fallback logic when no native library for your platform is found.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Unit test.

### CODE REVIEW

**Comment by viirya** [comment]
cc @dongjoon-hyun

**Comment by dongjoon-hyun** [comment]
Thanks!

**Comment by dongjoon-hyun** [comment]
BTW, could you make backporting PRs to branch-3.0/branch-2.4 seperately? It would be great to see the test result if possible.

**Review by maropu — APPROVED** [review]

**Comment by viirya** [comment]
> BTW, could you make backporting PRs to branch-3.0/branch-2.4 seperately? It would be great to see the test result if possible. For those branches, snappy-java is older version. So, it's a little bigger change.

Okay. yea, these branches still use 1.1.7. Let's see the test result.

**Review by HyukjinKwon — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you all!
Merged to branch-3.1.

**Pull request closed without merging**
