### PR TITLE
[SPARK-22924][SPARKR] R API for sortWithinPartitions

### PR DESCRIPTION
**Pull request by felixcheung**
## What changes were proposed in this pull request?

Add to `arrange` the option to sort only within partition

## How was this patch tested?

manual, unit tests

### CODE REVIEW

**Comment by felixcheung** [comment]
@shivaram @HyukjinKwon what do you think about this approach?

**Review by HyukjinKwon — COMMENTED** [review]
Seems fine to me. Another option might be to name `withinPartitions` to `global`:

https://github.com/apache/spark/blob/fcf66a32760c74e601acb537c51b2311ece6e9d5/sql/core/src/main/scala/org/apache/spark/sql/Dataset.scala#L3269

https://github.com/apache/spark/blob/fcf66a32760c74e601acb537c51b2311ece6e9d5/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/basicLogicalOperators.scala#L462-L463

but I don't have a strong opinion on this really. 

LGTM for the changes if @shivaram is fine with it too.

**Comment by shivaram** [comment]
LGTM. I think withinPartitions sounds better than global

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
