### PR TITLE
[SPARK-41922][CONNECT][PYTHON] Implement `DataFrame.semanticHash`

### PR DESCRIPTION
**Pull request by techaddict**
### What changes were proposed in this pull request?
Implement `DataFrame.semanticHash`

### Why are the changes needed?
api coverage

### Does this PR introduce _any_ user-facing change?
yes

### How was this patch tested?
new Unit tests

### CODE REVIEW

**Comment by techaddict** [comment]
cc: @HyukjinKwon @zhengruifeng

**Review by HyukjinKwon — APPROVED** [review]

**Comment by zhengruifeng** [comment]
@techaddict many thanks for working on it.

https://github.com/apache/spark/pull/39429#issuecomment-1374336839

but I guess we will not add the two functions. maybe we should update the error message and/or the related comments.

**Comment by HyukjinKwon** [comment]
Oh yeah. Thanks Ruifeng for pointing it out .

**Comment by techaddict** [comment]
@zhengruifeng Closing these and will create a different PR with updated comments

**Pull request closed without merging**
