### PR TITLE
[SPARK-15499][PySpark][Tests] Add python testsuite with remote debug and single test parameter to help developer debug code easier

### PR DESCRIPTION
**Pull request by WeichenXu123**
## What changes were proposed in this pull request?

To python/run-tests.py script, I add the following parameters:

`--single-test=SINGLE_TEST`
`specify a python module to run single python test.`
`--debug-server=DEBUG_SERVER`
`debug server host, only used in single test.`
`--debug-port=DEBUG_PORT`
`debug server port, only used in single test.`

Now, for example, I want to debug only pyspark.tests, I can use the following command:
(first startup debug server in your python IDE such as pycharm or pydev, your IED on machine which has host MY_DEV_MACHINE and using debug port 5678, and make sure the machine running test can connect to MY_DEV_MACHINE, and python must install pydevd module first.)

`python/run-tests --python-executables=python2.7 --single-test=pyspark.tests --debug-server=MY_DEV_MACHINE --debug-port=5678`

the parameter --single-test specify the single python testsuite you want to test, currently you can use the following value:

`pyspark.tests`
`pyspark.ml.tests`
`pyspark.mllib.tests`
`pyspark.sql.tests`
`pyspark.streaming.tests`

Adding parameters then develop and debug python script will be quite easier, I think.
## How was this patch tested?

Existing test.

### CODE REVIEW

**Comment by WeichenXu123** [comment]
Jenkins, test this please.

**Comment by WeichenXu123** [comment]
@davies  How do you think about it ?

**Comment by jkbradley** [comment]
To test a single subpackage, you can already use ```---modules='pyspark-ml'``` etc., so the ```---single-test``` arg may not be necessary.

**Comment by WeichenXu123** [comment]
@jkbradley 
--modules='pyspark-ml' will run a bunch of test in pyspark sub directory parallel, not single python file.
and my purpose is add a way to debug single python file code. Because the python test code should launch with bin/pyspark so it is not convenient to directly debug in IDE.

**Pull request closed without merging**
