### PR TITLE
SPARK-35622: DataFrame's count function do not need groupBy and avoid shuffle

### PR DESCRIPTION
**Pull request by StefanXiepj**
### What changes were proposed in this pull request?

Use `df.rdd.count()` replace `df.count()`.

### Why are the changes needed?

DataFrame's count function do not need groupBy,  use `df.rdd.count()` replace `df.count()` and avoid shuffle

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Added UT test

### CODE REVIEW

**Comment by neilagupta** [comment]
Is there a way we can benchmark the before and after to validate the avoided shuffle? Or if it was done already, somehow have the unit test expose the resulting difference?

**Comment by StefanXiepj** [comment]
> Is there a way we can benchmark the before and after to validate the avoided shuffle? Or if it was done already at least manually, somehow have the unit test expose the resulting difference?

@dgd-contributor have benchmarked it. 
https://issues.apache.org/jira/browse/SPARK-35622?focusedCommentId=17363336&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17363336

**Comment by wangyum** [comment]
This is my benchmark:
```scala
import org.apache.spark.benchmark.Benchmark

val path = "/tmp/spark/benchmark"
val count = 100000000
spark.range(count).selectExpr("id as c1", "id as c2", "id as c3", "id as c4", "id as c5").write.mode("overwrite").parquet(path)

spark.read.parquet(path).newCount()

val benchmark = new Benchmark("Benchmark count", count, minNumIters = 5)

benchmark.addCase("count") { _ =>
  spark.read.parquet(path).count()
}

benchmark.addCase("newCount") { _ =>
  spark.read.parquet(path).newCount() // Add newCount api to Dataset
}
benchmark.run()
```
Benchmark result:
```
Java HotSpot(TM) 64-Bit Server VM 1.8.0_251-b08 on Mac OS X 10.15.7
Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
Benchmark count:                          Best Time(ms)   Avg Time(ms)   Stdev(ms)    Rate(M/s)   Per Row(ns)   Relative
------------------------------------------------------------------------------------------------------------------------
count                                               165            205          56        604.6           1.7       1.0X
newCount                                           4850           5433         582         20.6          48.5       0.0X
```

**Comment by dgd-contributor** [comment]
I don't think these is the right fix for this issue, we might better add an optimizer rule to optimize this pattern, according to @HyukjinKwon

**Comment by StefanXiepj** [comment]
@wangyum thanks for your benchmark，now i known how to benchmark, here is my benchmark:
```
  test("SPARK-35622: DataFrame's count function do not need groupBy and avoid shuffle") {
    val df = Seq((1, 2), (4, 5)).toDF("col1", "col2")
    import org.apache.spark.benchmark.Benchmark
    val count = 100000000
    val benchmark = new Benchmark("Benchmark count", count, minNumIters = 5)
    benchmark.addCase("count") { _ =>
      df.count()
    }
    benchmark.addCase("newCount") { _ =>
      df.newCount() // Add newCount api to Dataset
    }
    benchmark.run()

    assert(df.count == 2)
  }
```
Benchmark result:
```
Testing started at 11:40 上午 ...


11:40:51.318 WARN org.apache.hadoop.util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

Running benchmark: Benchmark count
  Running case: count
  Stopped after 31 iterations, 2025 ms
  Running case: newCount
  Stopped after 214 iterations, 2002 ms

Java HotSpot(TM) 64-Bit Server VM 1.8.0_291-b10 on Mac OS X 10.16
Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
Benchmark count:                          Best Time(ms)   Avg Time(ms)   Stdev(ms)    Rate(M/s)   Per Row(ns)   Relative
------------------------------------------------------------------------------------------------------------------------
count                                                46             65          14       2156.1           0.5       1.0X
newCount                                              8              9           2      13178.2           0.1       6.1X


11:41:05.968 WARN org.apache.spark.sql.DatasetSuite: 

===== POSSIBLE THREAD LEAK IN SUITE o.a.s.sql.DatasetSuite, thread names: rpc-boss-3-1, shuffle-boss-6-1 =====



Process finished with exit code 0
```

@dgd-contributor your right, maybe specific questions needs specific analysizing .

**Comment by wangyum** [comment]
@StefanXiepj It is only 2 rows. You should increase your row count. e.g.: 100000000.

**Pull request closed without merging**
