### PR TITLE
[SPARK-7216][MESOS] Add driver details page to Mesos cluster UI.

### PR DESCRIPTION
**Pull request by tnachen**
Add a details page that displays Mesos driver in the Mesos cluster UI

### CODE REVIEW

**Comment by tnachen** [comment]
@andrewor14 this is a commit that I wanted to add on top of the cluster mode, which basically adds a new cluster driver detail page to display driver info.

**Comment by rxin** [comment]
Can you paste a screenshot to the pull request? Thanks.

**Comment by tnachen** [comment]
screen shot 2015-04-28 at 11 47 22 pm
screen shot 2015-04-28 at 11 48 02 pm

**Comment by tnachen** [comment]
@rxin That's what the detail driver page look like

**Comment by andrewor14** [comment]
retest this please

**Comment by andrewor14** [comment]
Looks like a reasonable follow up to #5144. I'm merging this into master.

**Pull request closed without merging**
