### PR TITLE
[SPARK-47785][BUILD][TESTS] Upgrade `bouncycastle` to 1.78

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to upgrade `bouncycastle` to 1.78.

### Why are the changes needed?

To use the latest bug fixed version.
- https://github.com/bcgit/bc-java/blob/main/docs/releasenotes.html

### Does this PR introduce _any_ user-facing change?

No, this is a test dependency.

### How was this patch tested?

Pass the CIs.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
All tests passed except the known CSV failures which were fixed already in `master` branch an hour ago.
- https://github.com/apache/spark/pull/45958

**Comment by dongjoon-hyun** [comment]
Could you review this test dependency PR, @huaxingao ?

**Review by huaxingao — APPROVED** [review]
LGTM. Thanks @dongjoon-hyun

**Comment by dongjoon-hyun** [comment]
Thank you, @huaxingao !

Merged to master.

**Pull request closed without merging**
