### PR TITLE
[SPARK-43594][SQL] Add LocalDateTime to anyToMicros

### PR DESCRIPTION
**Pull request by Fokko**
### What changes were proposed in this pull request?

Small change to `anyToMicros` to also accept `LocalDateTime` that's being returned when working with `TIMESTAMP_NTZ`. This simplifies some code at the Iceberg side.

### Why are the changes needed?

With the introduction of the TIMESTAMP_NTZ it is convient to also accept LocalDateTime

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Very trivial change, no test needed.

### CODE REVIEW

**Comment by Fokko** [comment]
cc @dongjoon-hyun Any thoughts on this small change?

**Review by MaxGekk — COMMENTED** [review]
The method `anyToMicros()` is assumed to be invoked for the type `TimestampType` which has 2 external Java types: `java.time.Instant` and `java.sql.Timestamp`, see 
https://github.com/apache/spark/blob/7c7b9585a2aba7bbd52c197b07ed0181ae049c75/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/SerializerBuildHelper.scala#L101

@Fokko Could you explain, please, how are you going to get `LocalDateTime` here?

**Comment by Fokko** [comment]
This would actually allow:

```scala
  def createSerializerForLocalDateTime(inputObject: Expression): Expression = {
    StaticInvoke(
      DateTimeUtils.getClass,
      TimestampNTZType,
      "localDateTimeToMicros",
      inputObject :: Nil,
      returnNullable = false)
  }
```

to change to:

```scala
  def createSerializerForLocalDateTime(inputObject: Expression): Expression = {
    StaticInvoke(
      DateTimeUtils.getClass,
      TimestampNTZType,
      "anyToMicros",
      inputObject :: Nil,
      returnNullable = false)
  }
```

This would also make some code on the Iceberg side simpler:

https://github.com/apache/iceberg/blob/8fe6248736a8a15a8dc85376c8741cbce62e6b47/spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkValueConverter.java#L78-L86

**Review by dongjoon-hyun — APPROVED** [review]
Thank you for making a PR, @Fokko . 
To support Iceberg community, I believe this looks fine to have.

To @MaxGekk , do you still have a concern?

**Comment by HyukjinKwon** [comment]
@Fokko no biggie but would be great to fill the PR description.

**Comment by Fokko** [comment]
@dongjoon-hyun @HyukjinKwon I've updated the template. I'd love to move this forward and also get this in 3.4.1

**Comment by dongjoon-hyun** [comment]
Thank you, @Fokko , @MaxGekk , @HyukjinKwon .
I merged to `master` branch for Apache Spark 3.5.0 according to the community guideline.

**Comment by dongjoon-hyun** [comment]
Sorry, @Fokko .

**Comment by dongjoon-hyun** [comment]
Just FYI, @Fokko . Apache Spark 3.5.0 Feature Freeze is next month (July 16th) and you will have Apache Spark 3.5.0 on August.
- https://spark.apache.org/versioning-policy.html

**Comment by Fokko** [comment]
Would it be possible to get this into 3.4.1 as well? You could argue that it is fixing a bug following the new TIMESTAMP_NTZ type.

**Pull request closed without merging**
