### PR TITLE
[SPARK-44329][CONNECT][PYTHON] Add hll_sketch_agg, hll_union_agg, to_varchar, try_aes_decrypt to Scala and Python

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
Add following functions:

- hll_sketch_agg
- hll_union_agg
- to_varchar
- try_aes_decrypt

to:

- Scala API
- Python API
- Spark Connect Scala Client
- Spark Connect Python Client

### Why are the changes needed?
for parity

### Does this PR introduce _any_ user-facing change?
Yes, new functions.

### How was this patch tested?
- Add New UT.

### CODE REVIEW

**Comment by panbingkun** [comment]
cc @zhengruifeng

**Review by zhengruifeng — APPROVED** [review]

**Comment by zhengruifeng** [comment]
so quick, thank you @panbingkun

**Comment by zhengruifeng** [comment]
merged to master

**Comment by LuciferYang** [comment]
late LGTM, thanks @panbingkun

**Pull request closed without merging**
