### PR TITLE
[SPARK-10286][ML][PySpark][Docs] Add @since annotation to pyspark.ml.param and pyspark.ml.*

### PR DESCRIPTION
**Pull request by lidinghao**

### CODE REVIEW

**Comment by mengxr** [comment]
@lidinghao Thanks for working on this! For classes, could you also add `versionadded`? You can find an example here: https://github.com/apache/spark/blob/f85aa06464a10f5d1563302fd76465dded475a12/python/pyspark/mllib/fpm.py#L45.

**Comment by mengxr** [comment]
ok to test

**Comment by lidinghao** [comment]
@mengxr Ok, I will add the versionadded

**Comment by yu-iskw** [comment]
LGTM

@lidinghao I want to confirm one last thing: Since `JavaEvaluator` is a developer API, didn't you add `@since` tags to it?

**Comment by lidinghao** [comment]
@yu-iskw  No,I didn't add `@since` tags to `JavaEvaluator`.

**Comment by mengxr** [comment]
Merged into master. Thanks!

**Pull request closed without merging**
