### PR TITLE
[MINOR][SS] a minor refactor of getOffset in KafkaSource

### PR DESCRIPTION
**Pull request by CodingCat**
## What changes were proposed in this pull request?

This PR factors the verbose code in the original implementation

## How was this patch tested?

regular unit test cases

### CODE REVIEW

**Comment by CodingCat** [comment]
@zsxwing mind taking a look?

**Comment by srowen** [comment]
It's OK by  me but is it really helping?

**Comment by CodingCat** [comment]
Eh...depends on how you define help...remove some unnecessary code is the only benefit...I am ok if you close it...just a 1 min work when reading the source code

**Comment by srowen** [comment]
It's not bad but there are a thousand things in the code that should be cleaned up. I think it could be OK if you sweep the code for similar patterns and fix all of some type. Just on principle and to be fair to other tiny PRs we've requested people close yes I think we maybe shouldn't change things ad-hoc like this if they have no real effect.

**Comment by CodingCat** [comment]
Considering the current size of code base and the diversity of the required domain knowledge to ensure that the changes in all sub projects do not hurt, it is impossible to apply changes to the whole code base in once instead of fix issues progressively. Anyway, I will close it

**Pull request closed without merging**
