### PR TITLE
[SPARK-46698][CORE] Replace Timer with single thread scheduled executor for ConsoleProgressBar.

### PR DESCRIPTION
**Pull request by beliefer**
### What changes were proposed in this pull request?
This PR propose to replace `Timer` with single thread scheduled executor for `ConsoleProgressBar`.

### Why are the changes needed?
The javadoc recommends `ScheduledThreadPoolExecutor` instead of `Timer`.
屏幕快照 2024-01-12 下午12 47 57
 
This change based on the following two points.
**System time sensitivity**

Timer scheduling is based on the absolute time of the operating system and is sensitive to the operating system's time. Once the operating system's time changes, Timer scheduling is no longer precise.
The scheduled Thread Pool Executor scheduling is based on relative time and is not affected by changes in operating system time.

**Are anomalies captured**

Timer does not capture exceptions thrown by Timer Tasks, and in addition, Timer is single threaded. Once a scheduling task encounters an exception, the entire thread will terminate and other tasks that need to be scheduled will no longer be executed.
The scheduled Thread Pool Executor implements scheduling functions based on a thread pool. After a task throws an exception, other tasks can still execute normally.

### Does this PR introduce _any_ user-facing change?
'No'.

### How was this patch tested?
Manual tests.

### Was this patch authored or co-authored using generative AI tooling?
'No'.

### CODE REVIEW

**Comment by beliefer** [comment]
ping @srowen @dongjoon-hyun @LuciferYang

**Review by LuciferYang — APPROVED** [review]
+1 from myside

**Comment by srowen** [comment]
Looks OK, just rerun tests

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by dongjoon-hyun** [comment]
Merged to master. I verified manually the console progress bar. It looks working without any issue as expected.

**Comment by beliefer** [comment]
@dongjoon-hyun @srowen @LuciferYang Thank you!

**Pull request closed without merging**
