### PR TITLE
[SPARK-19459][SQL][BRANCH-2.1] Support for nested char/varchar fields in ORC

### PR DESCRIPTION
**Pull request by hvanhovell**
## What changes were proposed in this pull request?
This is a backport of the two following commits: https://github.com/apache/spark/commit/78eae7e67fd5dec0c2d5b18000053ce86cd0f1ae & https://github.com/apache/spark/commit/de8a03e68202647555e30fffba551f65bc77608d

This PR adds support for ORC tables with (nested) char/varchar fields.

## How was this patch tested?
Added a regression test to `OrcSourceSuite`.

### CODE REVIEW

**Review by gatorsmile — APPROVED** [review]
LGTM, pending Jenkin

**Comment by gatorsmile** [comment]
Thanks! Merging to 2.1.

**Comment by gatorsmile** [comment]
Cloud you close the PR now?

**Comment by hvanhovell** [comment]
Thanks!

**Pull request closed without merging**
