### PR TITLE
[MINOR][TESTS] Rename JSONBenchmark to JsonBenchmark

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR renames `object JSONBenchmark` to `object JsonBenchmark` and the benchmark result file `JSONBenchmark-results.txt` to `JsonBenchmark-results.txt`.

### Why are the changes needed?

Since the file name doesn't match with `object JSONBenchmark`, it makes a confusion when we run the benchmark. In addition, this makes the automation difficult.
```
$ find . -name JsonBenchmark.scala
./sql/core/src/test/scala/org/apache/spark/sql/execution/datasources/json/JsonBenchmark.scala
```
```
$ build/sbt "sql/test:runMain org.apache.spark.sql.execution.datasources.json.JsonBenchmark"
[info] Running org.apache.spark.sql.execution.datasources.json.JsonBenchmark
[error] Error: Could not find or load main class org.apache.spark.sql.execution.datasources.json.JsonBenchmark
```

### Does this PR introduce any user-facing change?

No.

### How was this patch tested?

This is just renaming.

### CODE REVIEW

**Comment by maropu** [comment]
nit: we have no consistent name rule for that? Since `Json` is more popular, `JSONBenchmark` -> `JsonBenchmark` instead of `JsonBenchmark.scala` -> `JSONBenchmark.scala`?
```
$ find . -type f | grep -e "\.scala$" | grep Json
./core/src/main/scala/org/apache/spark/deploy/JsonProtocol.scala
./core/src/main/scala/org/apache/spark/util/JsonProtocol.scala
./core/src/test/scala/org/apache/spark/deploy/JsonProtocolSuite.scala
./core/src/test/scala/org/apache/spark/JsonTestUtils.scala
./core/src/test/scala/org/apache/spark/util/JsonProtocolSuite.scala
./external/kafka-0-10-sql/src/main/scala/org/apache/spark/sql/kafka010/JsonUtils.scala
./external/kafka-0-10-sql/src/test/scala/org/apache/spark/sql/kafka010/JsonUtilsSuite.scala
./mllib/src/main/scala/org/apache/spark/ml/linalg/JsonMatrixConverter.scala
./mllib/src/main/scala/org/apache/spark/ml/linalg/JsonVectorConverter.scala
./mllib/src/test/scala/org/apache/spark/ml/linalg/JsonMatrixConverterSuite.scala
./mllib/src/test/scala/org/apache/spark/ml/linalg/JsonVectorConverterSuite.scala
./sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/json/JsonInferSchema.scala
./sql/catalyst/src/test/scala/org/apache/spark/sql/catalyst/expressions/JsonExpressionsSuite.scala
./sql/catalyst/src/test/scala/org/apache/spark/sql/catalyst/json/JsonInferSchemaSuite.scala
./sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/json/JsonDataSource.scala
./sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/json/JsonFileFormat.scala
./sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/json/JsonOutputWriter.scala
./sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/json/JsonUtils.scala
./sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/v2/json/JsonDataSourceV2.scala
./sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/v2/json/JsonPartitionReaderFactory.scala
./sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/v2/json/JsonScan.scala
./sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/v2/json/JsonScanBuilder.scala
./sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/v2/json/JsonTable.scala
./sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/v2/json/JsonWriteBuilder.scala
./sql/core/src/test/scala/org/apache/spark/sql/execution/datasources/json/JsonBenchmark.scala
./sql/core/src/test/scala/org/apache/spark/sql/execution/datasources/json/JsonParsingOptionsSuite.scala
./sql/core/src/test/scala/org/apache/spark/sql/execution/datasources/json/JsonSuite.scala
./sql/core/src/test/scala/org/apache/spark/sql/execution/datasources/json/TestJsonData.scala
./sql/core/src/test/scala/org/apache/spark/sql/execution/SQLJsonProtocolSuite.scala
./sql/core/src/test/scala/org/apache/spark/sql/JsonFunctionsSuite.scala
./sql/hive/src/test/scala/org/apache/spark/sql/sources/JsonHadoopFsRelationSuite.scala

$ find . -type f | grep -e "\.scala$" | grep JSON
./sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/json/JSONOptions.scala
```

**Comment by srowen** [comment]
Agree with @maropu

**Comment by dongjoon-hyun** [comment]
No problem, @maropu and @srowen .

**Comment by dongjoon-hyun** [comment]
For me, it's okay as long as it's consistent with `object` name and file name.

**Comment by dongjoon-hyun** [comment]
BTW, we need to rename the class and the result file together. It will cause some conflicts with my existing PR.

**Comment by dongjoon-hyun** [comment]
@maropu and @srowen . The PR is updated accordingly to your advice.

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Review by srowen — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @maropu and @srowen .
Merged to master.

**Pull request closed without merging**
