### PR TITLE
[SPARK-15405][yarn] Remove unnecessary upload of config archive.

### PR DESCRIPTION
**Pull request by vanzin**
We only need one copy of it. The client code that was uploading the
second copy just needs to be modified to update the metadata in the
cache, so that the AM knows where to find the configuration.

Tested by running app on YARN and verifying in the logs only one archive
is uploaded.

### CODE REVIEW

**Comment by vanzin** [comment]
@tgravescs

**Comment by tgravescs** [comment]
changes look fine but it looks like we need to update some of the unit tests.

**Comment by vanzin** [comment]
yeah I'll double check the change itself and then look at the tests.

**Comment by tgravescs** [comment]
+1

**Comment by vanzin** [comment]
Merging to master / 2.0.

**Pull request closed without merging**
