### PR TITLE
[SPARK-13116][SQL] TungstenAggregate though it is supposedly capable …

### PR DESCRIPTION
**Pull request by ahshahid**
…of all processing unsafe & safe rows, fails if the input is safe rows.

Allowing targeted mutable row to be set with field values if the target row is Unsafe.

### CODE REVIEW

**Comment by ahshahid** [comment]
@davies

**Comment by davies** [comment]
@ahshahid I think may only Spark 1.6 has this issue, in Spark master, every operator should output UnsafeRow.

In 1.6 branch, a quick fix could be let TungstenAggregate only accept UnsafeRow, then there will be ToUnsafe operator inserted before TungstenAggregate.

**Comment by ahshahid** [comment]
Looks like code which we had contained TungstenAggregate.canProcessSafeRows as true. But in the latest codebase, these methods are not there.  
I have test which showed up this issue. I will check if I get the problem with the latest codebase of spark.

**Comment by JoshRosen** [comment]
Ping @ahshahid, any update here?

**Comment by davies** [comment]
@ahshahid Do you mind close this PR?

**Comment by ahshahid** [comment]
Hi ,
Extremely sorry for the delay.
I am fine with it closing the ticket , but just to be clear , the issue
which I described is there , just that it surfaces if the code gen throws
exception.
Regards
Asif

**Pull request closed without merging**
