### PR TITLE
[SPARK-6978][GraphX] Compute all the direct and indirect relations for e...

### PR DESCRIPTION
**Pull request by balduz**
...ach vertex

Right now you can only get the direct connections of each vertex in a
graph using collectNeighbors or collectNeighborIds. However, it would be
very useful to be able to also get all the indirect connections of each
vertex, with the degree of each of these connections.

I have implemented this using Pregel, you call VertexConnections and
specify the graph and the maximum degree you wish to retrieve (this
second parameter is optional, if not specified it will retrieve every
connection) and returns a map where for each key (degree) it contains a
collection with all of the vertices.

### CODE REVIEW

**Comment by andrewor14** [comment]
ok to test. @ankurdave

**Comment by andrewor14** [comment]
@balduz Are you actively working on this? Could you fix the style issues?

**Comment by balduz** [comment]
@andrewor14 done. Could you try it again? Thanks!

**Comment by balduz** [comment]
@andrewor14 I accidentally commited (don't even know how) almost 3.000 file changes in a commit that I don't know how appeared. Could you cancel the build until I remove this?

**Comment by srowen** [comment]
@balduz this pull request / branch still just shows one changed file. It looks fine.

**Comment by balduz** [comment]
@srowen oh ok, I am not very used to working with git so I freaked out when I saw that number. Thanks!

**Comment by andrewor14** [comment]
retest this please
@ankurdave

**Comment by rxin** [comment]
I'm going to close this pull request. If this is still relevant and you are interested in pushing it forward, please open a new pull request. Thanks!

**Pull request closed without merging**
