### PR TITLE
[SPARK-33725][BUILD] Upgrade snappy-java to 1.1.8.2

### PR DESCRIPTION
**Pull request by viirya**
### What changes were proposed in this pull request?

This upgrades snappy-java to 1.1.8.2.

### Why are the changes needed?

Minor version upgrade that includes:

- [Fixed](https://github.com/xerial/snappy-java/pull/265) an initialization issue when using a recent Mac OS X version
- Support Apple Silicon (M1, Mac-aarch64)
- Fixed the pure-java Snappy fallback logic when no native library for your platform is found.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Unit test.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Yey! Thanks, @viirya .

**Review by dongjoon-hyun — COMMENTED** [review]
BTW, we already support ARM64, don't we? We have ARM64 Jenkins job for a long time.
> Support Apple Silicon (M1, Mac-aarch64)

**Comment by viirya** [comment]
As this is minor upgrade and fixes a few bugs, seems okay to backport to branch-3.1 too. cc @dongjoon-hyun @HyukjinKwon

**Comment by viirya** [comment]
> BTW, we already support ARM64, don't we? We have ARM64 Jenkins job for a long time.
> 
> > Support Apple Silicon (M1, Mac-aarch64)

I guess so. But I am not sure if there is any difference between Apple Silicon and ARM64.

**Comment by dongjoon-hyun** [comment]
@viirya . For the bug fixes, we may need to land this to all live branches (master/branch-3.1/branch-3.2/branch-2.4) if that is true.
> Fixed an initialization issue when using a recent Mac OS X version

**Comment by viirya** [comment]
> > BTW, we already support ARM64, don't we? We have ARM64 Jenkins job for a long time.
> > > Support Apple Silicon (M1, Mac-aarch64)
> 
> I guess so. But I am not sure if there is any difference between Apple Silicon and ARM64.

As I checked snappy-java's Makefile, the original ARM64 support is only for Linux-aarch64 before.

**Comment by dongjoon-hyun** [comment]
Thanks. I converted SPARK-33725 from `Improvement` to `Bug` and set the affected versions `2.4.7, 3.0.1, 3.1.0, 3.2.0
`.

**Comment by viirya** [comment]
Thanks @dongjoon-hyun !

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Merged to master.

**Comment by dongjoon-hyun** [comment]
There is a conflict at branch-3.1. Could you make a backporting PR to old release branches?

**Comment by viirya** [comment]
Yea, thanks @dongjoon-hyun.

**Comment by maropu** [comment]
lgtm

**Pull request closed without merging**
