### PR TITLE
[SPARK-13071] [hadoop-2.7] Coalescing HadoopRDD overwrites existing input metrics

### PR DESCRIPTION
**Pull request by andrewor14**
This issue is causing tests to fail consistently in master with Hadoop 2.6 / 2.7. This is because for Hadoop 2.5+ we overwrite existing values of `InputMetrics#bytesRead` in each call to `HadoopRDD#compute`. In the case of coalesce, e.g.

```
sc.textFile(..., 4).coalesce(2).count()
```

we will call `compute` multiple times in the same task, overwriting `bytesRead` values from previous calls to `compute`.

For a regression test, see `InputOutputMetricsSuite.input metrics for old hadoop with coalesce`. I did not add a new regression test because it's impossible without significant refactoring; there's a lot of existing duplicate code in this corner of Spark.

This was caused by #10835.

### CODE REVIEW

**Comment by andrewor14** [comment]
@yhuai @JoshRosen

**Comment by yhuai** [comment]
test this please

**Comment by yhuai** [comment]
maybe also put hadoop2.7 in the title, so jenkins can test it?

**Comment by andrewor14** [comment]
like this? I didn't know Jenkins can do that

**Comment by andrewor14** [comment]
retest this please

**Comment by andrewor14** [comment]
let's try again. retest this please

**Comment by nongli** [comment]
LGTM

**Comment by andrewor14** [comment]
retest this please

**Comment by andrewor14** [comment]
Merging into master.

**Pull request closed without merging**
