### PR TITLE
[SPARK-24891][FOLLOWUP][HOT-FIX][2.3] Fix the Compilation Errors

### PR DESCRIPTION
**Pull request by gatorsmile**
## What changes were proposed in this pull request?

This PR is to fix the compilation failure in 2.3 build. 

https://amplab.cs.berkeley.edu/jenkins/view/Spark%20QA%20Compile/job/spark-branch-2.3-compile-maven-hadoop-2.7/764/

## How was this patch tested?
N/A

### CODE REVIEW

**Comment by gatorsmile** [comment]
retest this please

**Comment by gatorsmile** [comment]
cc @maryannxue @gengliangwang

**Comment by ueshin** [comment]
LGTM, pending Jenkins.

**Comment by HyukjinKwon** [comment]
Merged to branch-2.3.

**Pull request closed without merging**
