### PR TITLE
[WIP][SPARK-43221][CORE] the BlockManager with the persisted block is preferred

### PR DESCRIPTION
**Pull request by yorksity**
[SPARK-43221][CORE] the BlockManager with the persisted block is preferred

### What changes were proposed in this pull request? 
Fixed bug to avoid exceeding bounds by taking values from empty arrays

### Why are the changes needed?
This bug will occur with probability in certain scenarios under certain conditions:
1. Not using remote shuffle
2. Multiple executors on the same node
3. These executors hold the same block
4. Some executors store the block in memory, while others store the block in disk

### Does this PR introduce _any_ user-facing change? 
No

### How was this patch tested?
existing UTs &&
I will supplement UT for this scenario

### CODE REVIEW

**Comment by mridulm** [comment]
+CC @attilapiros who last looked into this.
I will circle back to this PR later this week - thanks for detailed jira @yorksity !
Can you please fix the PR description as well ? Thanks.

**Comment by yorksity** [comment]
> +CC @attilapiros who last looked into this. I will circle back to this PR later this week - thanks for detailed jira @yorksity ! Can you please fix the PR description as well ? Thanks.

**Comment by attilapiros** [comment]
This seems to me not a bug but a performance improvement, right?

**Comment by attilapiros** [comment]
If this is a bug please try to reproduce it with a unit test which fails with old code and passes with the new one!

**Comment by yorksity** [comment]
> This seems to me not a bug but a performance improvement, right?

Yes, this is a bug. I introduced the reason for this bug in Jira
https://issues.apache.org/jira/browse/SPARK-43221

**Comment by yorksity** [comment]
> If this is a bug please try to reproduce it with a unit test which fails with old code and passes with the new one!

Yes, I am working on resolving this UT error and adding new UT to protect it

**Comment by mridulm** [comment]
Is this still WIP @yorksity ?

**Pull request closed without merging**
