### PR TITLE
SPARK-12417. [SQL] Orc bloom filter options are not propagated during file …

### PR DESCRIPTION
**Pull request by rajeshbalamohan**

### CODE REVIEW

**Comment by zhzhan** [comment]
Any test cases to make sure it works as expected? Do you mind changing the orc ppd enabled as default or using another JIRA.

**Comment by rajeshbalamohan** [comment]
Thanks @zhzhan. Enabled orc PPD by default and also added a test case for bloom filters in the latest commit. ORC RecordReaderImpl is not public in the version of hive that is supported in spark; Hence relying on FileDump utility from ORC to test bloom fitlers.

**Comment by tristanwietsma** [comment]
+1 for this

**Comment by JoshRosen** [comment]
Duplicate of #10842? Can you close one of them and we'll continue on a single PR?

**Comment by rajeshbalamohan** [comment]
Closing this as dup of #10842

**Pull request closed without merging**
