### PR TITLE
[SPARK-45161][3.5][INFRA] Bump previousSparkVersion to 3.5.0

### PR DESCRIPTION
**Pull request by JoshRosen**
### What changes were proposed in this pull request?

This PR is a `branch-3.5` port of https://github.com/apache/spark/pull/42921 which bumps MiMa's `previousSparkVersion` to 3.5.0, cleans up a number of expired exclude rules, adds new modules to the MiMa check, and bumps the `dev/mima` memory.

### Why are the changes needed?

Ensure that future Spark 3.5.x releases remain binary- and source-compatible with Spark 3.5.0.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Scala 2.12

```
dev/mima -Pscala-2.12
```

Scala 2.13

```
dev/change-scala-version.sh 2.13
dev/mima -Pscala-2.13
```

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
@JoshRosen , this backporting PR looks exceptional to me because we don't do this usually. Just a question. Did we break any binary compatibility from 3.4.x somewhere?
> Ensure that future Spark 3.5.x releases remain binary- and source-compatible with Spark 3.5.0.

**Comment by dongjoon-hyun** [comment]
Also, cc @yaooqinn since he is the release manager of Apache Spark 3.5.2.

**Comment by dongjoon-hyun** [comment]
cc @srowen too

**Comment by JoshRosen** [comment]
> @JoshRosen , this backporting PR looks exceptional to me because we don't do this usually. Just a question. Did we break any binary compatibility from 3.4.x somewhere?

@dongjoon-hyun, you're right that previously this has not been standard practice. From the check results, OSS Apache Spark 3.5.2-snapshot remains binary-compatible with 3.5.0 and, transitively, because 3.5.0 was binary compatible with 3.4.0 and so it should also be compatible with 3.4.0 and so on.

I'm proposing this change because:

- It doesn't _hurt_ and, strictly speaking, strengthens our tests to detect more potential incpompatibilies.
- It slightly reduces merge conflicts for any future patches in 4.x which need to be backported to 3.5.x and involve new MiMa excludes (such as https://issues.apache.org/jira/browse/SPARK-46480)
- It reduces merge conflicts / simplifies certain workflows in our internal fork of Spark (where we also use MiMa checks).

**Comment by dongjoon-hyun** [comment]
Yes, as you mentioned, we make the compatibility test pass by adding many **explicit** exclusion rules. After this PR,  there is a chance of losing a binary compatibility at Apache Spark 3.5.2+ against Apache Spark 3.4.x, isn't there?
> because 3.5.0 was binary compatible with 3.4.0 and so it should also be compatible with 3.4.0 (modulo purposeful excludes) and so on.

**Comment by JoshRosen** [comment]
> After this PR, there is a chance of losing a binary compatibility at Apache Spark 3.5.2+ against Apache Spark 3.4.x, isn't there?

I don't think so:

- Assume that Spark 3.5.0 was binary compatible with Spark 3.4.x (except in the known cases we excluded).
- Let's say we make a change in, say, 3.5.2. which breaks compatibility with Spark 3.4.x: because Spark 3.5.0 was compatible with 3.4.x, the 3.4.x methods or types against which we could be incompatible should all be present in a compatible fashion in Spark 3.5.0, so the types of 3.4.x incompatibilities that we want to prevent will also be 3.5.x incompatibilities. 

I think that this argument is sound, but let me know if there is a corner case that I'm overlooking.

**Comment by dongjoon-hyun** [comment]
Here is a general counter example in my mind. (This is not a specific to this PR's deletion).

1. `v3.4.0` has a public API `x`.
2. `v3.5.0` renames `x` to `y` with the exception rules.
3. This PR removes all exclusion rules after switching to `v3.5.0` because `x` is supposed not to exist.
4. `v3.5.2` adds a new public API `x` with different signatures because this is new at 3.5.2.

Then, `v3.5.2` has an incompatibility on API `x` against `v3.4.x ~ v3.5.1`. WDYT?

**Comment by JoshRosen** [comment]
> Here is a general counter example in my mind. (This is not a specific to this PR's deletion).
> 
> 1. `v3.4.0` has a public API `x`.
> 2. `v3.5.0` renames `x` to `y` with the exception rules.
> 3. This PR removes all exclusion rules after switching to `v3.5.0` because `x` is supposed not to exist.
> 4. `v3.5.2` adds a new public API `x` with different signatures because this is new at 3.5.2.
> 
> Then, `v3.5.2` has an incompatibility on API `x` against `v3.4.x ~ v3.5.1`. WDYT?

In the case where we've previously renamed `x` to `y` and have added a missing method exclusion for `x`, then subsequently re-introduce it with a different signature: in that case, wouldn't the previous incompatible renaming _itself_ have been a binary incompatibility?

---

I was hoping this would be straightforward and easy, but if we can't gain consensus then I'm just as glad to abandon this and close without merging.

**Comment by dongjoon-hyun** [comment]
The above example will be prevented if we don't switch like this. The above corner case is going to be missed only if we switch our target.
> wouldn't the previous incompatible renaming itself have been a binary incompatibility?


Ya, sorry for asking this. But, let's not do this because this could bite us in the future. We don't know what the community PRs will do in the future.
> I was hoping this would be straightforward and easy, but if we can't gain consensus then I'm just as glad to abandon this and close without merging.

**Comment by dongjoon-hyun** [comment]
Thank you, @JoshRosen !

**Pull request closed without merging**
