### PR TITLE
[SPARK-27135][WebUI]Add ToolTip support for overflow text

### PR DESCRIPTION
**Pull request by sandeep-katta**
## What changes were proposed in this pull request?

Hover is supported on the description column,so when the description column overflows user can view the complete details

## How was this patch tested?

Manually

## Before Fix
UIIssue
## After Fix 
 e.g. 1
toolTip2
e.g. 2
ToolTipWithLargeQuery

### CODE REVIEW

**Comment by sandeep-katta** [comment]
CC @vanzin @srowen @gengliangwang

**Comment by srowen** [comment]
I think that's probably OK; does the cell expand automatically when you mouse over it?

**Comment by sandeep-katta** [comment]
yes, it expands automatically as attached in the image

**Comment by gengliangwang** [comment]
I tried the patch. To me,  the user experience is not very good. On mouse over, the table size is changed; if the mouse goes over table descriptions, then the table keep changing.

Personally, I prefer the way like tooltip:
image


Or showing the hidden part on click as SQL execution table:
image

**Comment by sandeep-katta** [comment]
ok will work on tooltip and update the code accordingly

**Comment by sandeep-katta** [comment]
With ToolTip it looks like below

toolTip2

**With very large Query**
ToolTipWithLargeQuery

**Comment by srowen** [comment]
I think that's good too, it's unobtrusive and gives the detail.

**Comment by sandeep-katta** [comment]
@gengliangwang  is this tooltip approach is okay ?

**Comment by gengliangwang** [comment]
@sandeep-katta I took a look into this.
I found that there is already a double click event for showing the full description:
https://github.com/apache/spark/pull/6646

I am not sure about adding tooltip now.

**Comment by srowen** [comment]
Ha, I never realized that. I agree, we shouldn't add this then.

**Pull request closed without merging**
