### PR TITLE
[SPARK-50580][BUILD] Upgrade log4j2 to 2.24.3

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to upgrade log4j2 from `2.24.2` to `2.24.3`.

### Why are the changes needed?
- The full release notes:
https://github.com/apache/logging-log4j2/releases/tag/rel%2F2.24.3

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Is it ready, @panbingkun ?

**Comment by panbingkun** [comment]
> Is it ready, @panbingkun ?

Yeah, thanks!

**Review by HyukjinKwon — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you all.

**Comment by LuciferYang** [comment]
@HyukjinKwon Since 2.24.3 includes the following fix:

- https://github.com/apache/logging-log4j2/issues/3234
- https://github.com/apache/logging-log4j2/pull/3235


I believe we can try this change again: https://github.com/apache/spark/pull/48966

**Pull request closed without merging**
