### PR TITLE
[SPARK-45421][SQL] Catch AnalysisException over InlineCTE

### PR DESCRIPTION
**Pull request by amaliujia**
### What changes were proposed in this pull request?

We are catching exceptions for `CheckAnalysis` and attach inlined plan. However, if `InlineCTE` itself throws we can also catch but attach original plan.

### Why are the changes needed?

Attach original plan if `InlineCTE` throws.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Existing UT

### Was this patch authored or co-authored using generative AI tooling?

NO

### CODE REVIEW

**Comment by amaliujia** [comment]
@cloud-fan

**Review by cloud-fan — APPROVED** [review]
LGTM if tests pass

**Comment by amaliujia** [comment]
@cloud-fan thanks! the tests have passed.

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Pull request closed without merging**
