### PR TITLE
[WIP][SPARK-35483][SQL][TESTS] Add a new GA test job for the docker integration tests

### PR DESCRIPTION
**Pull request by maropu**
### What changes were proposed in this pull request?

This PR proposes to add a new GA test job for the docker integration tests.

### Why are the changes needed?

To check the integration tests are healthy.

### Does this PR introduce _any_ user-facing change?

No, dev-only.

### How was this patch tested?

GA passed.

### CODE REVIEW

**Comment by maropu** [comment]
It seems `DB2KrbIntegrationSuite` consistently fails, so I'm looking into this;
```
[info] DB2KrbIntegrationSuite:
[info] - SPARK-35226: JDBCOption should accept refreshKrb5Config parameter *** FAILED *** (2 seconds, 189 milliseconds)
[info]   com.ibm.db2.jcc.am.SqlSyntaxErrorException: DB2 SQL Error: SQLCODE=-104, SQLSTATE=42601, SQLERRMC=);ECT * FROM (SELECT 1;<table_expr>, DRIVER=4.26.14
[info]   at com.ibm.db2.jcc.am.b7.a(b7.java:810)
[info]   at com.ibm.db2.jcc.am.b7.a(b7.java:66)
[info]   at com.ibm.db2.jcc.am.b7.a(b7.java:140)
[info]   at com.ibm.db2.jcc.am.k4.c(k4.java:2824)
```

**Review by dongjoon-hyun — COMMENTED** [review]
I revised the title because we have two integration tests: JDBC and K8s. This one is for the first one.

**Comment by maropu** [comment]
Thank you, @dongjoon-hyun. right, the previous title was ambiguous.

**Comment by maropu** [comment]
I used the wrong jira number, so I fixed it.

**Comment by maropu** [comment]
It seems @sarutak want to work on this, so I'll close this.

**Pull request closed without merging**
