### PR TITLE
[SPARK-34608][SQL] Remove unused output of AddJarCommand

### PR DESCRIPTION
**Pull request by AngersZhuuuu**
### What changes were proposed in this pull request?
Remove unused output of AddJarCommand, keep consistence and clean

### Why are the changes needed?
Keep consistence and clean

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Not need

### CODE REVIEW

**Comment by srowen** [comment]
Is the output really unused anywhere? if it's used at all, like displayed somewhere, maybe worth keeping

**Comment by AngersZhuuuu** [comment]
> Is the output really unused anywhere? if it's used at all, like displayed somewhere, maybe worth keeping

I have check many command that return `Seq.empty[Row]`, they don't need output. And we can see `AddFileCommand` don't have too, also `AddArchiveCommand` https://github.com/apache/spark/pull/31721

**Comment by srowen** [comment]
Seems OK if so, AFAIK

**Review by HyukjinKwon — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.
Merged to master.

**Pull request closed without merging**
