### PR TITLE
[SPARK-40157][PYTHON][DOCS] Make pyspark.files examples self-contained

### PR DESCRIPTION
**Pull request by zhengruifeng**
### What changes were proposed in this pull request?
Make pyspark.files examples self-contained

### Why are the changes needed?
Make pyspark.files examples self-contained

### Does this PR introduce _any_ user-facing change?
yes, new example

### How was this patch tested?
added doctests

### CODE REVIEW

**Comment by zhengruifeng** [comment]
cc @HyukjinKwon

**Review by HyukjinKwon — APPROVED** [review]
should probably add it into `pyspark_core` at `dev/sparktestsupport/modules.py`. LGTM otherwise

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by zhengruifeng** [comment]
thanks for review

**Pull request closed without merging**
