### PR TITLE
[SPARK-30722][DOCS][FOLLOW-UP] Add Pandas Function API into the menu

### PR DESCRIPTION
**Pull request by HyukjinKwon**
### What changes were proposed in this pull request?

This PR adds "Pandas Function API" into the menu.

### Why are the changes needed?

To be consistent and to make easier to navigate.

### Does this PR introduce any user-facing change?

No, master only.

Screen Shot 2020-03-27 at 11 40 29 PM

### How was this patch tested?

Manually verified by `SKIP_API=1 jekyll build`.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
@viirya can you take a quick look?

**Review by viirya — APPROVED** [review]

**Comment by viirya** [comment]
Looks good. Thanks for adding this.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @HyukjinKwon and @viirya .
Merged to master/3.0.

**Comment by HyukjinKwon** [comment]
Thanks!

**Pull request closed without merging**
