### PR TITLE
[SPARK-15400][SQL] CreateNamedStruct and CreateNamedStructUnsafe should preserve metadata of value expressions if it is NamedExpression.

### PR DESCRIPTION
**Pull request by ueshin**
## What changes were proposed in this pull request?

`CreateNamedStruct` and `CreateNamedStructUnsafe` should preserve metadata of value expressions if it is `NamedExpression` like `CreateStruct` or `CreateStructUnsafe` are doing.
## How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by rxin** [comment]
cc @sameeragarwal for review

**Comment by rxin** [comment]
Maybe remove MINOR from title?

**Comment by ueshin** [comment]
@rxin Thank you, I removed [MINOR] from title.

**Comment by cloud-fan** [comment]
LGTM, is it possible to write a test for it?

**Comment by rxin** [comment]
+1 on adding a test!

**Comment by ueshin** [comment]
I see, I'll try it.

**Comment by ueshin** [comment]
Jenkins, retest this please.

**Comment by rxin** [comment]
Merging in master/2.0. Thanks.

**Pull request closed without merging**
