### PR TITLE
[SPARK-46474][INFRA] Upgrade upload-artifact action to v4

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to upgrade upload-artifact action from v3 to v4.

### Why are the changes needed?
- v4.0.0 release notes: https://github.com/actions/upload-artifact/releases/tag/v4.0.0
They have numerous performance and behavioral improvements.

- v3 VS v4: https://github.com/actions/upload-artifact/compare/v3...v4.0.0

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by panbingkun** [comment]
Manually check as follows:
https://github.com/panbingkun/spark/actions/runs/7285550002/job/19853491824
image

**Review by zhengruifeng — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by HyukjinKwon** [comment]
Seems like this is causing the test failure in Python scheduled build: https://github.com/apache/spark/actions/workflows/build_python.yml?page=2.

I am reverting it for now.

**Comment by HyukjinKwon** [comment]
I will get this back again if this isn't the actual root cause

**Comment by dongjoon-hyun** [comment]
Got it. Thank you for investigating and taking care of this, @HyukjinKwon .

**Comment by dongjoon-hyun** [comment]
For the record, the upload failure is fixed. Thank you again, @HyukjinKwon .

**Comment by panbingkun** [comment]
Let me investigate it.

**Pull request closed without merging**
