### PR TITLE
[STREAMING] SPARK-3505: Augmenting SparkStreaming updateStateByKey API with timestamp

### PR DESCRIPTION
**Pull request by xiliu82**
Augment updateStateByKey API by exposing both key and current batch timestamp to applications.

### CODE REVIEW

**Comment by tdas** [comment]
Ping, for updating this PR.

**Comment by xiliu82** [comment]
I will try to do that this week.

**Comment by tdas** [comment]
Hey @xiliu82 if you are not able to get a chance on this, mind closing this? You can always open it when you are ready to submit it for review again.

**Comment by xiliu82** [comment]
Sorry, completely slipped my mind.. I will close it for now, and submit later.

**Comment by tdas** [comment]
This is not closed yet :(

**Pull request closed without merging**
