### PR TITLE
[SPARK-28954][SQL] In SparkSQL CLI, pass extra jar through hive hive conf HIVEAUXJARS, we just  use SessionResourceLoader API to cover multi-version problem

### PR DESCRIPTION
**Pull request by AngersZhuuuu**
### What changes were proposed in this pull request?

[28954](https://issues.apache.org/jira/browse/SPARK-28954#)  

For extra jar passed through hive conf  `HiveConf.ConfVars.HIVEAUXJARS`, we don't need to use complex APIs to fix different hive version problem, we just can handle it through spark's SessionResourceLoader's API. add jar to Spark and SparkSession's  running env.

 For problem mentioned in  #25542 , the root cause is :
In SparkSQLCliDriver, we will create a CliSessionState, then we will call
`SessionState.start(sessionState)`, this method will do like blow in SessionState.
image

Then currentThread's ClassLoader will be replaced by hiveConf's ClassLoader, then cause problem mentioned in #25542 .

Fix it by add origin thread's ClassLoader to CliSessionState's conf's ClassLoader before we call
`SessionState.start(sessionState)`

### Why are the changes needed?
Reduce complex code to fit each version of hive.

### Does this PR introduce any user-facing change?
No

### How was this patch tested?
Existed UT is enough

### CODE REVIEW

**Comment by wangyum** [comment]
ok to test

**Comment by gatorsmile** [comment]
ok to test

**Comment by HyukjinKwon** [comment]
ok to test

**Comment by AngersZhuuuu** [comment]
Change to resolve in #25542 .

**Pull request closed without merging**
