### PR TITLE
[SPARK-19282][ML][SparkR] RandomForest Wrapper and GBT Wrapper return param "maxDepth" to R models

### PR DESCRIPTION
**Pull request by keypointt**
## What changes were proposed in this pull request?

RandomForest R Wrapper and GBT R Wrapper return param `maxDepth` to R models.

Below 4 R wrappers are changed:
* `RandomForestClassificationWrapper`
* `RandomForestRegressionWrapper`
* `GBTClassificationWrapper`
* `GBTRegressionWrapper`

## How was this patch tested?

Test manually on my local machine.

### CODE REVIEW

**Comment by felixcheung** [comment]
Can you clarify? this is on the model summary, not a param?

**Comment by keypointt** [comment]
sorry being vague, I updated the PR description just now

yes, it's for R model summary, R wrapper returning `maxDepth` to R model
as mentioned in the comment at https://issues.apache.org/jira/browse/SPARK-19282, `I don't know how to find the RandomForestRegressionModel in the R docs. R does take the parameter, but it is unclear if it exposes it on the model.`

**Comment by felixcheung** [comment]
ok, great, could you update PR title and JIRA title then.

**Review by felixcheung — CHANGES_REQUESTED** [review]
could you update the documentation on model summary in https://github.com/keypointt/spark/blob/d16b65cc077f3ba2a770d709cc8a7a9ebfda9aad/R/pkg/R/mllib_tree.R#L202

and

https://github.com/keypointt/spark/blob/d16b65cc077f3ba2a770d709cc8a7a9ebfda9aad/R/pkg/R/mllib_tree.R#L409

**Comment by keypointt** [comment]
Jenkins retest it please

**Comment by keypointt** [comment]
Jenkins, retest this please

**Comment by keypointt** [comment]
ping @felixcheung

**Comment by felixcheung** [comment]
merged to master.

**Pull request closed without merging**
