### PR TITLE
[SPARK-24767][Launcher] Propagate MDC to spark-submit thread in InProcessAppHandle

### PR DESCRIPTION
**Pull request by yifeih**
## What changes were proposed in this pull request?

This patch propagate MDC from the launcher thread to the thread that runs spark-submit. 

## How was this patch tested?

Ran sbt tests in the spark-launcher project

### CODE REVIEW

**Comment by mccheah** [comment]
@vanzin would it be possible for you to please take a look at this? Thanks.

**Comment by mccheah** [comment]
test this please

**Comment by yifeih** [comment]
ping @vanzin. thanks!

**Comment by yifeih** [comment]
hey @vanzin can you please take a look at this soon? thanks!

**Comment by vanzin** [comment]
Hmm, why is this desired here and not in any other part of Spark?

The launcher module also must not depend on slf4j. If there is a strong reason for this, then you'll have to use reflection.

**Comment by yifeih** [comment]
Ah ok i see, let's close this out then.

**Pull request closed without merging**
