### PR TITLE
[SPARK-29107][SQL][TESTS] Port window.sql (Part 1)

### PR DESCRIPTION
**Pull request by DylanGuedes**
### What changes were proposed in this pull request?

This PR ports window.sql from PostgreSQL regression tests https://github.com/postgres/postgres/blob/REL_12_STABLE/src/test/regress/sql/window.sql from lines 1~319

The expected results can be found in the link: https://github.com/postgres/postgres/blob/REL_12_STABLE/src/test/regress/expected/window.out

### Why are the changes needed?

To ensure compatibility with PostgreSQL.

### Does this PR introduce any user-facing change?

No

### How was this patch tested?

Pass the Jenkins. And, Comparison with PgSQL results.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
ok to test

**Comment by dongjoon-hyun** [comment]
Thank you, @DylanGuedes !

**Comment by dongjoon-hyun** [comment]
cc @gengliangwang

**Comment by gengliangwang** [comment]
@DylanGuedes Thanks for the work.
Please wait until https://github.com/apache/spark/pull/26107 is merged.

**Comment by dongjoon-hyun** [comment]
#26107 is merged. Thanks, @gengliangwang .

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by dongjoon-hyun** [comment]
According to the failures, we need to update the PR.
```
- Cannot safely cast 'enroll_date': StringType to DateType;
```

**Comment by DylanGuedes** [comment]
@dongjoon-hyun should I JIRA that?

**Comment by HyukjinKwon** [comment]
@DylanGuedes, please skip or fix the tests being failed in the thrift server. cc @wangyum

**Comment by DylanGuedes** [comment]
@HyukjinKwon I have no idea why they are breaking on Thrift, they used to pass in the older PR and they also were fine in my local config (I can't rerun then now because my environment suddenly broken). Do you have any suggestion? I don't think that makes sense to just comment out anything related to date since `date.sql` passed fine and I also don't know why this kind of test is failing on Thrift.

**Comment by HyukjinKwon** [comment]
You can either skip the single test with a comment or add it in a blacklist I think cc @wangyum 
I would file a separate jira for that.

**Review by HyukjinKwon — APPROVED** [review]
Looks fine to me. I will merge in few days.

**Review by maropu — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by maropu** [comment]
Thanks for the work, @DylanGuedes! btw, how many PR parts are left for window.sql? It seems we have no open PRs for this.

**Comment by DylanGuedes** [comment]
@maropu Two parts are missing. I thought that there were more people interested on working on them because I read some comments on JIRA, but since no one opened a MR, I'll create a new one for the other parts and work them as well.

**Comment by maropu** [comment]
Thanks, again!

**Pull request closed without merging**
