### PR TITLE
[SPARK-26578][CORE] Synchronize putBytes's memory allocation and putting block on memoryManager

### PR DESCRIPTION
**Pull request by SongYadong**
## What changes were proposed in this pull request?

Just like operation about memory allocation and putting/evicting blocks in `MemoryStore`'s many other methods, I think it may be better that `putBytes` also be synchronized on `memoryManager`.

## How was this patch tested?

Existing unit tests.

### CODE REVIEW

**Comment by srowen** [comment]
I tend to agree -- @JoshRosen ?

**Comment by kiszk** [comment]
I prefer not to add `sychorized`. This is because the nested `sychorized` may cause deadlock if different order of the nested `sychorized` exist. I think that the current code is correct since `MemoryManager.acquireStorageMemory` is already `sychorized`.

Could you please elaborate why we need this synchronization? Did you see actual problem?

**Comment by SongYadong** [comment]
I'm sorry, I haven't found actual problem. 
I think it may be better that acquiring memory and putting block to LinkHashMap work together as an atomic operation. Could this avoid some data inconsistency?
Nested synchronized here may not cause deadlock beacuse they synchronize on the same lock. If this cause deadlock, `MemoryStore.remove()`, `MemoryStore.clear()`, `MemoryStore.reserveUnrollMemoryForThisTask()`, `MemoryStore.releaseUnrollMemoryForThisTask()` have the same problem.

**Comment by srowen** [comment]
Yeah @kiszk that's a good point. However none of the `entries.synchronized` blocks acquire the `memoryStore` lock; `evictBlocksToFreeSpace` locks a block in the BlockManager though. In that case, it has both the `memoryStore` and `entries` locks (in that order). 

It's also a good question: is this a problem? the issue I was worried about here is `evictBlocksToFreeSpace`. Is this a potential problem:

1. `putBytes` allocates memory (but hasn't added to `entries`)
1. `evictBlocksToFreeSpace` executes and calculates entries to evict and evicts entries
1. `putBytes` adds an entry, causing there to be not enough free memory

I don't know this well enough to know whether that actually happens or is an issue, but is what jumped out at me. The 'allocation' method locks the `memoryStore` the whole time while the 'eviction' method doesn't.

**Comment by srowen** [comment]
@kiszk do you have more of an opinion on this given the above?

**Comment by SongYadong** [comment]
Thanks for review. @srowen @kiszk . I'll try to find out if this could cause actual problems by experiments.

**Comment by srowen** [comment]
Thanks @kiszk - you're saying there probably isn't a problem here? I wasn't clear. Indeed I don't think we've demonstrated a case where something fails here, although it might just be rare.

**Comment by srowen** [comment]
Yeah that's the kind of problem I would expect.  @kiszk what do you think?

**Comment by Ngone51** [comment]
So, what's problem in simulate test ? Isn't the behaviour of step 5 is what we're looking forward to ?

**Comment by SongYadong** [comment]
> So, what's problem in simulate test ? Isn't the behaviour of step 5 is what we're looking forward to ?

That's good question. Yeah, this may not be a big problem that must be fixed. I don't know if behaviour of step 5 is design goal. I just think there's some inconsistency here : we evicted all entries but still got smaller free space than pool size. It seems that no obivous overhead is brought in if we resolve this inconsistency.

**Comment by Ngone51** [comment]
> I just think there's some inconsistency here : we evicted all entries but still got smaller free space than pool size. 

In your test, no blocks in entries when task 2 try to evict blocks, right ? So, how can we say *we evicted all entries but still got smaller free space* ? From my view, task 2 does not evict any blocks, so it can not accquire enough free memory.

**Comment by SongYadong** [comment]
> In your test, no blocks in entries when task 2 try to evict blocks, right ? So, how can we say _we evicted all entries but still got smaller free space_ ? From my view, task 2 does not evict any blocks, so it can not accquire enough free memory.

For simple, my test puts only one block(block1) into it. If we put some blocks into entries before putting block1, task 2 will evict them _all_ first. So we can say we evicted all entries but still got smaller free space than whole pool size?

**Comment by Ngone51** [comment]
> If we put some blocks into entries before putting block1, task 2 will evict them all first. So we can say we evicted all entries but still got smaller free space than whole pool size?

Do you mean other blocks are all in the status as block1, which has already acquired memory but havn't put into entries ? (Ok, let's ignore the possibility of the case temporarily.) 

And at this point, the question may be *does the total size of blocks in entries is always equal to storage pool size*, right ? Follow the test above, for example, there may be another task 3 get a chance to do putIterator before task 2 to do putBytes. And task 3 may reserved a lot of storage unroll memory during the process.  So, when task 2 got a changce to accquire storage memory and trigger evicting blocks, it will find the pool size still do not  increase obviously. So, there may be do not exists strongly consistency between entries and stroage pool.

**Comment by SongYadong** [comment]
This may not be a big problem that must be fixed. I'll close this PR.

**Comment by srowen** [comment]
It was a good analysis, and may actually be a good change, but OK we can leave it for now.

**Comment by SongYadong** [comment]
OK, thanks!

**Pull request closed without merging**
