### PR TITLE
[SPARK-36922][SQL] The SIGN/SIGNUM functions should support ANSI intervals

### PR DESCRIPTION
**Pull request by Peng-Lei**
### What changes were proposed in this pull request?
1. if value of AnsiIntervalType is 0, the sign/signum return 0.0
2. if value of AnsiIntervalType is negative, the sign/signum return -1.0
3. if value of AnsiIntervalType is positive, the sign/signum return 1.0

### Why are the changes needed?
[SPARK-36922](https://issues.apache.org/jira/browse/SPARK-36922)
Extend the sign/signum functions to support ANSI intervals.

### Does this PR introduce _any_ user-facing change?
Yes, user can use YearMonthIntervalType and DayTimeIntervalType as input for SIGN/SIGNUM functions.

### How was this patch tested?
Add ut testcase

### CODE REVIEW

**Comment by Peng-Lei** [comment]
@MaxGekk Could you take a look? Thank you.

**Comment by sarutak** [comment]
ok to test.

**Comment by sarutak** [comment]
add to whitelist.

**Review by MaxGekk — COMMENTED** [review]
PR's description:
> input for SIGN/SIGNUM funcitions

funcitions -> functions

**Review by MaxGekk — COMMENTED** [review]
Please, add an example to the expression description:
```
      > SELECT _FUNC_(40);
       1.0
      > SELECT _FUNC_(INTERVAL -'100' YEAR);
...
```

**Review by MaxGekk — APPROVED** [review]

**Review by sarutak — APPROVED** [review]
LGTM. Pending CIs.

**Comment by Peng-Lei** [comment]
@MaxGekk @sarutak Thank you for your review.

**Comment by sarutak** [comment]
Merged to `master`. Thank you @Peng-Lei and @MaxGekk !

**Pull request closed without merging**
