### PR TITLE
[SPARK-35039][PYTHON] Remove PySpark version dependent codes.

### PR DESCRIPTION
**Pull request by ueshin**
### What changes were proposed in this pull request?

Removes PySpark version dependent codes from `pyspark.pandas` main codes.

### Why are the changes needed?

There are several places to check the PySpark version and switch the logic, but now those are not necessary.
We should remove them.

We will do the same thing after we finish porting tests.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by ueshin** [comment]
cc @HyukjinKwon @itholic @xinrong-databricks

**Comment by xinrong-databricks** [comment]
LGTM, pending tests, thanks!

**Review by itholic — APPROVED** [review]
LGTM

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
