### PR TITLE
[SPARK-46694][SQL][TESTS] Drop the assumptions of 'hive version < 2.0' in Hive version related tests

### PR DESCRIPTION
**Pull request by yaooqinn**
### What changes were proposed in this pull request?

Code clean-up following SPARK-45328, this PR drops the assumptions and workarounds in Hive version-related tests， which work for hive version < 2.0

### Why are the changes needed?

clean dead codes

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

SPARK_TEST_HIVE_CLIENT_VERSIONS=3.1 ./build/sbt  -Phive -Phive-thriftserver "testOnly *HiveClientSuite*"

### Was this patch authored or co-authored using generative AI tooling?

no

### CODE REVIEW

**Comment by yaooqinn** [comment]
cc @HyukjinKwon @dongjoon-hyun thanks

**Review by HyukjinKwon — APPROVED** [review]

**Comment by pan3793** [comment]
this assumption is always true too, could u please update it as well?

https://github.com/apache/spark/blob/b7e976696f51fc4dbb13e222adb6bb705eb8324d/sql/hive/src/test/scala/org/apache/spark/sql/hive/client/HiveVersionSuite.scala#L35-L36

**Comment by yaooqinn** [comment]
>  this assumption is always true too, could u please update it as well?

I left it AS-IS on purpose

**Comment by yaooqinn** [comment]
Thank you all, merged to master

**Review by dongjoon-hyun — COMMENTED** [review]
+1, LGTM. Thank you!

**Pull request closed without merging**
