### PR TITLE
[SPARK-45109][SQL][CONNECT] Fix aes_decrypt and ln functions in Connect

### PR DESCRIPTION
**Pull request by peter-toth**
### What changes were proposed in this pull request?
Fix `aes_descrypt` and `ln` implementations in Spark Connect. The previous `aes_descrypt` reference to `aes_encrypt` is clearly a bug. The `ln` reference to `log` is more like a cosmetic issue, but because `ln` and `log` function implementations are different in Spark SQL we should use the same implementation in Spark Connect too.

### Why are the changes needed?
Bugfix.

### Does this PR introduce _any_ user-facing change?
No, these Spark Connect functions haven't been released.

### How was this patch tested?
Esiting UTs.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by peter-toth** [comment]
cc @xuanyuanking, @panbingkun, @zhengruifeng, @cloud-fan

**Comment by LuciferYang** [comment]
Could you re-trigger the CI again, @peter-toth ?

**Comment by LuciferYang** [comment]
also cc @hvanhovell

**Comment by panbingkun** [comment]
@peter-toth Good catch! But this PR may need to be corrected: eas_encrypt -> aes_ encrypt 😄

**Comment by peter-toth** [comment]
> @peter-toth Good catch! But the title and description of this PR may need to be corrected: eas_decrypt -> aes_decrypt 😄

Ahh, thanks, I can't belive how many times I've made that typo...

**Review by zhengruifeng — APPROVED** [review]

**Comment by zhengruifeng** [comment]
thanks, merged to master and branch-3.5

**Comment by peter-toth** [comment]
Thanks all for the review!

**Review by dongjoon-hyun — COMMENTED** [review]
+1, LGTM. Nice catch.

**Pull request closed without merging**
