### PR TITLE
[SPARK-35082][INFRA] Use permissive and squshed merge when syncing to the latest branch in GitHub Actions testing

### PR DESCRIPTION
**Pull request by Yikun**
### What changes were proposed in this pull request?

There is an issue when syncing to the Apache master branch, see also https://github.com/apache/spark/pull/32168:

```
From https://github.com/yaooqinn/spark
 * branch                  SPARK-35044 -> FETCH_HEAD
fatal: Not possible to fast-forward, aborting.
Error: Process completed with exit code 128.
```

This is because we use `--ff-only` option so it assumes that the fork is always based on the latest master branch.
We should make it less strict.

This PR proposes to use the same command when we merge PRs: 

https://github.com/apache/spark/blob/c8f56eb7bb49d7aafd7b83bad241a0b1b50a0e33/dev/merge_spark_pr.py#L127

### Why are the changes needed?

To unblock PR testing broken.

### Does this PR introduce _any_ user-facing change?

No, dev-only.

### How was this patch tested?

Locally tested

Co-authored-by: Kent Yao <yaooqinn@hotmail.com>

Closes #32168

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Im gonna merge this in and see how it gose.

**Comment by HyukjinKwon** [comment]
Merged to master.

**Review by dongjoon-hyun — APPROVED** [review]

**Comment by Yikun** [comment]
@HyukjinKwon much thanks for your help.

Note that it works in normal case (using `git` push code), but looks like have some problem on page-edited case: https://github.com/Yikun/spark/pull/14 , 

But for this patch, I think we should merge it ASAP to stop breaking other patches merging, and deal with this page-edited case later.

**Comment by HyukjinKwon** [comment]
We can add account and email for doubly sure. i made some suggestions on your branch.

**Review by viirya — APPROVED** [review]

**Review by gengliangwang — APPROVED** [review]

**Comment by Yikun** [comment]
@HyukjinKwon Retest with email and user opt: https://github.com/Yikun/spark/pull/14

**Comment by Yikun** [comment]
the latest code works in my local test: https://github.com/Yikun/spark/runs/2349203988?check_suite_focus=true#step:3:18

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by HyukjinKwon** [comment]
Thanks all especially @Yikun and @yaooqinn. I was a bit in a hurry. thanks for bearing with me all.

**Comment by Yikun** [comment]
Thanks! It makes me feel the active and powerful of our community. : )

**Comment by yaooqinn** [comment]
LGTM

**Pull request closed without merging**
