### PR TITLE
[SPARK-19184][MLlib] Improve numerical stability for method tallSkinnyQR.

### PR DESCRIPTION
**Pull request by hl475**
## What changes were proposed in this pull request?

In method tallSkinnyQR, the final Q is calculated by A * inv(R). When the upper triangular matrix R is ill-conditioned, computing the inverse of R can result in catastrophic cancellation. Instead, we should consider using a forward solve for solving Q such that Q * R = A.
## How was this patch tested?

unit tests and the following codes in Spark Shell:
```
import org.apache.spark.mllib.linalg.{Matrices, Vector, Vectors}
import org.apache.spark.mllib.linalg.distributed.RowMatrix

// Create RowMatrix A.
val mat = Seq(Vectors.dense(1,1,1,1), Vectors.dense(0, 1E-5, 1,1), Vectors.dense(0,0,1E-10,1), Vectors.dense(0,0,0,1E-14))
val denseMat = new RowMatrix(sc.parallelize(mat, 2))

// Apply tallSkinnyQR to A.
val result = denseMat.tallSkinnyQR(true)

// Print the calculated Q and R.
result.Q.rows.collect.foreach(println)
result.R

// Calculate Q*R. Ideally, this should be close to A.
val reconstruct = result.Q.multiply(result.R)
reconstruct.rows.collect.foreach(println)

// Calculate Q'*Q. Ideally, this should be close to the identity matrix.
result.Q.computeGramianMatrix()

System.exit(0)
```
I first create a 4 by 4 RowMatrix A = (1,1,1,1;0,1E-5,0,0;0,0,1E-10,1;0,0,0,1E-14), and then I apply method tallSkinnyQR to A to find RowMatrix Q and Matrix R such that A = Q*R. In this case, A is ill-conditioned and so is R.

### CODE REVIEW

**Comment by srowen** [comment]
Is there not a library method for this?

**Comment by hl475** [comment]
@srowen: We don’t use LAPACK here since there is no pivoted QR in LAPACK that stops when the rank is exhausted. This is highlighted in the inline comments [563 to 565](https://github.com/apache/spark/pull/16556/files#diff-00e48e38779d4534190bf78a0fd962dbR563).

**Comment by tygert** [comment]
Maybe @hl475 could add his remark about how "we don't use LAPACK here since there is no pivoted QR in LAPACK that stops when the rank is exhausted" to the inline comments he highlighted? Incidentally, RSVDPACK -- https://github.com/sergeyvoronin/LowRankMatrixDecompositionCodes -- does include the necessary routine, but neither Spark nor Breeze is planning to incorporate the new RSVDPACK so far as I know.

**Comment by tygert** [comment]
What do you think, @srowen and @hl475, should this entail modifying Breeze in order to leverage LAPACK, or should this bug fix get accepted as it stands?

**Comment by tygert** [comment]
@srowen : MLlib *still* hasn't fixed this problem two years later?! The existing decompositions are completely numerically unstable and unusable for data analytics. Spark still returns NaNs even for the 4x4 example of @hl475

**Comment by srowen** [comment]
I closed this for lack of follow-up in 8 months. If you are interested in pursuing it it would need a new PR. This one didn't even build.

**Comment by tygert** [comment]
Thanks! I haven't been using Spark for a while now, but the bad rap it has for outputting garbage even when the input is fine might be worth fixing. Bear in mind that the kind of example @hl475 produced is the rule, not the exception: if you perform dimensionality reduction or principal component analysis, then some matrix involved in the analysis is very likely to be numerically ill-conditioned. MLlib currently cannot handle ill-conditioned matrices, which makes its use for dimensionality reduction and principal component analysis highly problematic. We have other tools where I work, but not all people have such luxuries.

**Comment by tygert** [comment]
@hl475 : would you be able to get any benefit for your performance reviews by fixing this issue? If so, this might be worth pursuing.

**Comment by srowen** [comment]
A 4x4 matrix isn't the use case for Spark of course and this isn't nearly as likely 'at scale', but, better accuracy is good all else equal. I haven't looked at this, but surprised if breeze doesn't already have such a solver. In any event, if it doesn't even compile, it couldn't be considered, but the principle is fine.

**Comment by hl475** [comment]
@tygert : Unfortunately this will not contribute to my performance reviews.

**Comment by tygert** [comment]
To be honest, @srowen : this is way more likely at scale than for the 4x4 case. That is how we found the problem. @hl475 eventually worked out a small case that was representative of what others had been observing. We got complaints that principal component analysis in Spark was broken, and it turned out that the problem was numerical instability. You could in principle use a least-squares solver rather than inverting matrices, if you wanted to rely on Breeze alone. There seems to be a larger issue, though: solving systems of linear equations by explicitly inverting matrices and without any reason for subspaces to align is something prohibited very early in textbooks on numerical linear algebra. Ideally whoever would be maintaining MLlib would be familiar with condition numbers and numerical instability, though I fully realize that there may not be enough resources available to approach the ideal. If we end up using MLlib more where I work, then perhaps I can fix this in the future. Sorry for the distraction.

**Comment by srowen** [comment]
Hm, I haven't thought about it enough then, but as the # cols increases isn't R less likely to be singular? doesn't really matter though. Simple is better than complex, if it fixes it, but if not, yeah something like this may be needed.

To be clear, nobody thinks this is the best way to do it. It's just what was implemented so far. To your question of why it hasn't been improved, ¯\_(ツ)_/¯ ? that's OSS. It happens by people doing it.

**Comment by tygert** [comment]
Well, in applications to dimension reduction (that is, when principal component analysis is useful), the singular values of the matrix being analyzed need to decay to something relatively negligible. So, no, the problem doesn't get better as the number of columns increases, but actually typically gets worse. You're right that the fix which @hl475 devised is not ideal from the point of view of efficiency; the fix provides numerical stability through code that would ideally be optimized in C or some other lower-level language. Basically all codes that are serious about dimension reduction include some kind of truncation of singular values or regularized pseudoinverse. I've seen people use Spark's MLlib by adding a multiple of identity to AA^T just to avoid the numerical instability. In some sense, that latter hack works and sacrifices accuracy controllably.

**Pull request closed without merging**
