### PR TITLE
[SPARK-10432] spark.port.maxRetries documentation is unclear

### PR DESCRIPTION
**Pull request by tgravescs**

### CODE REVIEW

**Comment by srowen** [comment]
LGTM

**Comment by andrewor14** [comment]
Yup, looks good.

**Comment by holdenk** [comment]
Maybe worth mentioning what happens when the port is given a non-specific value as well?

**Comment by tgravescs** [comment]
I was on the fence about that as it somewhat seemed redundant with the first line, but if people thinks it will help I can add a line like:

Maximum number of retries when binding to a port before giving up.
+ When the port is 0 it retries 0 the specified maximum number of retries.
 When a port is non 0, each subsequent retry will
    increment the port used in the previous attempt by 1 before retrying. This 
    essentially allows it to try a range of ports from the start port specified 
   to port + maxRetries.

@srowen  @andrewor14  thoughts?

**Comment by andrewor14** [comment]
Yeah, sounds a little redundant. I think it's OK given that it's pretty common for 0 to mean a random port. Since we explicitly say (n + 1) only applies to non-0 ports I think it's fine.

**Comment by andrewor14** [comment]
OK, I'm going to merge this into master.

**Pull request closed without merging**
