### PR TITLE
[SPARK-38681][SQL] Support nested generic case classes

### PR DESCRIPTION
**Pull request by eejbyfeldt**
### What changes were proposed in this pull request?

Master and branch-3.3 will fail to derive schema for case classes with generic parameters if the parameter was not used directly as a field, but instead pass on as a generic parameter to another type. e.g.
```
case class NestedGeneric[T](
  generic: GenericData[T])
```

This is a regression from the latest release of 3.2.1 where this works as expected.

### Why are the changes needed?
Support more general case classes that user might have.

### Does this PR introduce _any_ user-facing change?
Better support for generic case classes.

### How was this patch tested?
New specs in ScalaReflectionSuite and ExpressionEncoderSuite. All the new test cases that does not use value classes pass if added to the 3.2 branch

### CODE REVIEW

**Comment by eejbyfeldt** [comment]
While testing the spark 3.3.0 release candidate I noticed that this is actually a regression from 3.2 that was introduced in https://github.com/apache/spark/pull/33205 so I this should also be fixed in the 3.3 branch.

**Review by cloud-fan — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @eejbyfeldt .

cc @srowen

**Review by srowen — APPROVED** [review]

**Comment by srowen** [comment]
Merged to master/3.3

**Comment by dongjoon-hyun** [comment]
Thank you, @eejbyfeldt , @cloud-fan , @srowen !

cc @MaxGekk

**Pull request closed without merging**
