### PR TITLE
[SPARK-4989][CORE] backport for branch-1.1 catch eventlog exception for wrong eventlog conf

### PR DESCRIPTION
**Pull request by liyezhang556520**
JIRA is [SPARK-4989](https://issues.apache.org/jira/browse/SPARK-4989)

### CODE REVIEW

**Comment by liyezhang556520** [comment]
jenkins, retest this please.

**Comment by andrewor14** [comment]
retest this please

**Comment by andrewor14** [comment]
This is failing due to a known python imports problem in branch-1.1

**Comment by andrewor14** [comment]
Python tests have been fixed. retest this please

**Comment by andrewor14** [comment]
retest this please

**Comment by andrewor14** [comment]
Merging into 1.1

**Comment by andrewor14** [comment]
Hey @liyezhang556520 would you mind closing this it's now merged

**Comment by liyezhang556520** [comment]
Done, thanks @andrewor14 .

**Pull request closed without merging**
