### PR TITLE
[SPARK-28524][SQL] Fix ThriftServerTab lost error message

### PR DESCRIPTION
**Pull request by wangyum**
## What changes were proposed in this pull request?

The ThriftServerTab lost the error message since [SPARK-28260](https://issues.apache.org/jira/browse/SPARK-28260):
image
image

This pr fix this issue.

## How was this patch tested?

manual tests
image
image

### CODE REVIEW

**Comment by wangyum** [comment]
cc @juliuszsompolski

**Comment by juliuszsompolski** [comment]
LGTM

**Comment by juliuszsompolski** [comment]
cc @gatorsmile

**Review by gatorsmile — COMMENTED** [review]
LGTM

Thanks! Merged to master.

**Pull request closed without merging**
