### PR TITLE
 [SPARK-25152][K8S] Enable SparkR Integration Tests for Kubernetes

### PR DESCRIPTION
**Pull request by ifilonenko**
## What changes were proposed in this pull request?

Re-introduced SparkR integration tests as part of the SparkR on K8S release. This PR awaits Jenkins availability. 

## How was this patch tested?

This patch was tested with unit tests and integration tests.

### CODE REVIEW

**Comment by ifilonenko** [comment]
This PR should fail integration tests rn, until the Jenkins OS is updated, but error right now is in terms of the minikube environment: 
`Error creating VM: virError(Code=55, Domain=19, Message='Requested operation is not valid: network 'minikube-net' is not active')`

@shaneknapp take a look if you can

**Comment by shaneknapp** [comment]
interesting.  looks like this could be a 'thing' w/minikube.  i was able to use virsh and get the minikube-net network up w/o issue.  related, and quite recent thread here:
https://github.com/kubernetes/minikube/issues/2513

i'll spot check the other workers, but just as an FYI:  i'll be out all day, and unable to check back in until this evening.

**Comment by shaneknapp** [comment]
test this please

**Comment by felixcheung** [comment]
what's the latest on this, btw?

**Comment by ifilonenko** [comment]
this PR is waiting on @shaneknapp to migrate to ubuntu and have R setup in the node responsible for distribution building. This was planning on being done right after the 2.4 cut.

**Comment by felixcheung** [comment]
@shaneknapp could we do this soon?

**Comment by shaneknapp** [comment]
yes, hopefully soon.  i won't be able to start on this for at least another
week due to our lab having a big event this coming week.

**Comment by mccheah** [comment]
Just wanted to ping on this - how close are we to getting this working on CI?

**Comment by shaneknapp** [comment]
closer.  just started working again on the ubuntu port about a week ago.
hopefully before EOY.

**Comment by ifilonenko** [comment]
@shaneknapp just a gentle ping on progress? :)

**Comment by ifilonenko** [comment]
test this please

**Comment by ifilonenko** [comment]
@shaneknapp can we change the make distribution build to include the deployment of spark R docker images? It seems that with Ubuntu the tests should be able to pass now!

**Comment by holdenk** [comment]
Hey @shaneknapp  I'm happy to make the change @ifilonenko is asking for if you're ok with it?

**Comment by holdenk** [comment]
Hey @ifilonenko do you have time to update this?

**Comment by shaneknapp** [comment]
@holdenk go for it!

**Comment by holdenk** [comment]
Ok, I'll try and follow up with this next week :)

**Comment by shaneknapp** [comment]
i'll make the change to the build config right now...  sorry i haven't gotten to it, been slammed here at work and short-handed on staff.

**Comment by shaneknapp** [comment]
builds updated

**Comment by shaneknapp** [comment]
test this please

**Comment by shaneknapp** [comment]
hmm:

```
--smart/-S has been removed.  Use +smart or -smart extension instead.
For example: pandoc -f markdown+smart -t markdown-smart.
Try pandoc --help for more information.
Error: processing vignette 'sparkr-vignettes.Rmd' failed with diagnostics:
pandoc document conversion failed with error 2
Execution halted
```

**Comment by shaneknapp** [comment]
hmm.  i added the `--r` flag to `make-distribution.sh` for the master k8s build and it passed:
https://amplab.cs.berkeley.edu/jenkins/job/spark-master-test-k8s/376/

the jdk11 build is still running, but it also passed the R section:
https://amplab.cs.berkeley.edu/jenkins/job/spark-master-test-k8s-jdk11/29/

i'm going to take a look and see if there's anything missing on the ubuntu worker that the k8s prb job failed on.

**Comment by shaneknapp** [comment]
test this please

**Comment by shaneknapp** [comment]
test this please

**Comment by shaneknapp** [comment]
argh sorry, forgot to run the k8s build on a different worker than the one that failed.

**Comment by shaneknapp** [comment]
test this please

**Comment by shaneknapp** [comment]
> hmm:
> 
> ```
> --smart/-S has been removed.  Use +smart or -smart extension instead.
> For example: pandoc -f markdown+smart -t markdown-smart.
> Try pandoc --help for more information.
> Error: processing vignette 'sparkr-vignettes.Rmd' failed with diagnostics:
> pandoc document conversion failed with error 2
> Execution halted
> ```
> 
> i also reverted the change to the k8s prb build until this is sorted.

well, the build looks like it's going to pass on a different worker than where it failed.

looking at the R packages installed on both machines, there are definitely differences in what's on each one but nothing looks to be missing on research-jenkins-worker-09.

however, i am assuming that the error is caused by `rmarkdown`, and comparing versions across all ubuntu workers shows that 1.1 is installed on everything except amp-jenkins-staging-worker-02, which has 1.8.  this is the worker that the successful k8s prb build ran on.

before i go barking up that tree, i would like to confirm that my suspicions are correct.  anyone?

**Comment by shaneknapp** [comment]
test this please

**Comment by shaneknapp** [comment]
FYI:  the SparkPullRequestBuilder-K8s job has been updated since the end of last week to include `--r` when calling `make-distribution.sh`.

**Comment by ifilonenko** [comment]
@mccheah @felixcheung for merge

**Comment by shaneknapp** [comment]
> @mccheah @felixcheung for merge

i can do this!

**Comment by shaneknapp** [comment]
> hmm:
> 
> ```
> --smart/-S has been removed.  Use +smart or -smart extension instead.
> For example: pandoc -f markdown+smart -t markdown-smart.
> Try pandoc --help for more information.
> Error: processing vignette 'sparkr-vignettes.Rmd' failed with diagnostics:
> pandoc document conversion failed with error 2
> Execution halted
> ```
> 
> i also reverted the change to the k8s prb build until this is sorted.

quick update:  we had a versioning mismatch on this worker and that was resolved by me banging my head against my desk and cursing R for generations.

**Comment by shaneknapp** [comment]
> @mccheah @felixcheung for merge

so happy this is done!  sorry it took so long @ifilonenko ...  the changes on my side were a lot easier than i'd expected them to me.  :)

**Comment by dongjoon-hyun** [comment]
Great! Thanks all!

**Pull request closed without merging**
