### PR TITLE
[SPARK-21324][Test] Improve statistics test suites

### PR DESCRIPTION
**Pull request by wzhfy**
## What changes were proposed in this pull request?

1. move `StatisticsCollectionTestBase` to a separate file.
2. move some test cases to `StatisticsCollectionSuite` so that `hive/StatisticsSuite` only keeps tests that need hive support.
3. clear up some test cases.

## How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by wzhfy** [comment]
cc @gatorsmile @cloud-fan

**Comment by gatorsmile** [comment]
@wzhfy For such a big PR, could you create a JIRA? Thanks!

**Comment by wzhfy** [comment]
retest this please

**Comment by wzhfy** [comment]
@gatorsmile OK, JIRA added. Thanks! I thought it's not needed for test only changes...

**Comment by cloud-fan** [comment]
LGTM, merging to master!

**Pull request closed without merging**
