### PR TITLE
[SPARK-6910] [SQL] Support for pushing predicates down to metastore for partition pruning

### PR DESCRIPTION
**Pull request by liancheng**
This PR forks PR #7421 authored by @piaozhexiu and adds [a workaround](https://github.com/liancheng/spark/commit/536ac41a7e6b2abeb1f6ec1a6491bbf09ed3e591) for fixing the occasional test failures occurred in PR #7421. Please refer to these [two](https://github.com/apache/spark/pull/7421#issuecomment-122527391) [comments](https://github.com/apache/spark/pull/7421#issuecomment-122528059) for details.

(To any committers who might merge this PR: please don't forget to set the "author" field to @piaozhexiu.)

### CODE REVIEW

**Comment by liancheng** [comment]
Gonna fire a bunch of Jenkins builds to see whether the workaround works...

**Comment by liancheng** [comment]
OK, I guess 10 builds should be enough :)

**Comment by liancheng** [comment]
Um, the last wave of Jenkins builds failed due to an embarrassing typo... Updated the PR, but Jenkins is being shut down now. Will try to fire another build wave later.

**Comment by liancheng** [comment]
@marmbrus @piaozhexiu The last five builds all passed. Seems that this workaround is valid. Just fired another 3 builds to double check.

**Comment by piaozhexiu** [comment]
@liancheng Thank you so much for the fix! Look forward to merging the patch again.

**Comment by liancheng** [comment]
@marmbrus I think it's probably OK to merge this one first. But I still haven't got any clue about the root cause mentioned in https://github.com/apache/spark/pull/7421#issuecomment-122527391 yet.

**Comment by marmbrus** [comment]
Great, thanks guys!

**Pull request closed without merging**
