### PR TITLE
[SPARK-20104][SQL] Don't estimate IsNull or IsNotNull predicates for non-leaf node

### PR DESCRIPTION
**Pull request by wzhfy**
## What changes were proposed in this pull request?

In current stage, we don't have advanced statistics such as sketches or histograms. As a result, some operator can't estimate `nullCount` accurately. E.g. left outer join estimation does not accurately update `nullCount` currently. So for `IsNull` and `IsNotNull` predicates, we only estimate them when the child is a leaf node, whose `nullCount` is accurate.

## How was this patch tested?

A new test case is added in `FilterEstimationSuite`.

### CODE REVIEW

**Comment by wzhfy** [comment]
cc @cloud-fan

**Comment by cloud-fan** [comment]
retest this please

**Comment by cloud-fan** [comment]
LGTM

**Comment by wzhfy** [comment]
retest this please

**Comment by wzhfy** [comment]
retest this please

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Pull request closed without merging**
