### PR TITLE
[SPARK-26708][SQL][followup] put the special handling of non-cascade uncache in the uncache method

### PR DESCRIPTION
**Pull request by cloud-fan**
## What changes were proposed in this pull request?

This is a follow up of https://github.com/apache/spark/pull/23644/files , to make these methods less coupled with each other.

## How was this patch tested?

existing tests

### CODE REVIEW

**Comment by maryannxue** [comment]
LGTM, except one minor suggestion.

**Comment by cloud-fan** [comment]
retest this please

**Comment by cloud-fan** [comment]
retest this please

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Pull request closed without merging**
