### PR TITLE
[WIP][SPARK-29164][SQL] Rewrite coalesce(expression, BooleanLiteral) make it more suitable for filter pushdown

### PR DESCRIPTION
**Pull request by AngersZhuuuu**
### What changes were proposed in this pull request?
Coalesce is not eligible for DataSource / Parquet filter pushdown.
Rewrite  `coalesce(expression, BooleanLiteral) ` to  boolean make it more suitable for filter pushdown.

### Why are the changes needed?
Better for some special case when filter push down.

### Does this PR introduce any user-facing change?
no

### How was this patch tested?
ADD UT

### CODE REVIEW

**Review by JoshRosen — COMMENTED** [review]
I haven't reviewed in detail yet, but here's some initial feedback:

- I'm unsure if `ReplaceNullWithFalseInPredicateSuite` is the right place to put this test case; maybe it should go as part of a new suite?
- The current test covers the behavior of the rewrite rule, comparing plans before and after, but we don't have any tests ensuring that the rewrite itself is actually valid / returns an expression which computes the correct result. Could we add a simple "truth-table"-type test which evaluates both the original and rewritten expressions over `true`, `false`, and `null` inputs to check that both expressions produce the same output? This rewrite has the nice property of being exhaustively testable, so I think it would be nice to have a test covering all of those cases.
  - Put differently: what if, hypothetically, we were wrong about `and` vs. `or` in the rewrite and mixed it up in both the rewrite and the test case? Right now I don't think we have a unit test which would detect that logical / design error, so I'm proposing to add a test guarding against mistakes in our own reasoning.

**Comment by AngersZhuuuu** [comment]
> I haven't reviewed in detail yet, but here's some initial feedback:

Nice advise, I will do this.  thanks a lot.

**Comment by maropu** [comment]
As my first impression, this is a bit corner case for optimization... if we add these kinds of niche optimizations, the number of the rules explodes. cc: @gatorsmile @viirya

**Comment by viirya** [comment]
Yeah, this is too corner case, I think.

**Comment by AngersZhuuuu** [comment]
@viirya @maropu  
Yeah, a little corner case. Add this method to ISSUE Comment, and advise user to add this to SparkSessionExtension may be better?

**Pull request closed without merging**
