### PR TITLE
[SPARK-38204][SS][3.2] Use HashClusteredDistribution for stateful operators with respecting backward compatibility

### PR DESCRIPTION
**Pull request by HeartSaVioR**
### What changes were proposed in this pull request?

This PR proposes to use HashClusteredDistribution for stateful operators which requires exact order of clustering keys without allowing sub-clustering keys, so that stateful operators will have consistent partitioning across lifetime of the query. 
(It doesn't cover the case grouping keys are changed. We have state schema checker verifying on the changes, but changing name is allowed so swapping keys with same data type is still allowed. So there are still grey areas.)

The change will break the existing queries having checkpoint in prior to Spark 3.2.2 and bring silent correctness issues. To remedy the problem, we introduce a new internal config `spark.sql.streaming.statefulOperator.useStrictDistribution`, which defaults to true for new queries but defaults to false for queries starting from checkpoint in prior to Spark 3.2.2. If the new config is set to false, stateful operator will use ClusteredDistribution which retains the old requirement of child distribution. 

Note that in this change we don't fix the root problem against old checkpoints. Long-term fix should be crafted carefully, after collecting evidence on the impact of SPARK-38204. (e.g. how many queries on end users would encounter SPARK-38204.)

This PR adds E2E tests for the cases which trigger SPARK-38204, and verify the behavior with new query (3.2.2) & old query (in prior to 3.2.2).

### Why are the changes needed?

Please refer the description of JIRA issue [SPARK-38024](https://issues.apache.org/jira/browse/SPARK-38204) for details, since the description is quite long to include here.

### Does this PR introduce _any_ user-facing change?

Yes, stateful operators no longer accept the child output partitioning having subset of grouping keys and trigger additional shuffle. This will ensure consistent partitioning with stateful operators across lifetime of the query.

### How was this patch tested?

New UTs including backward compatibility are added.

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
cc. @viirya @xuanyuanking @c21 
This is a backport PR of #35673 against 3.2 branch. I had to use HashClusteredDistribution here because porting back the change on StatefulOpClusteredDistribution required more changes and expected.
Please take a look. Thanks!

**Review by xuanyuanking — APPROVED** [review]
LGTM

**Comment by HeartSaVioR** [comment]
Thanks for reviewing! Merging to 3.2.

**Comment by HeartSaVioR** [comment]
Addressed via [c6dd39d](https://github.com/apache/spark/commit/c6dd39da4132fc4861ae5fed2684d63d817c0ba2)

**Pull request closed without merging**
