### PR TITLE
Revert "[SPARK-40976][BUILD] Upgrade sbt to 1.7.3"

### PR DESCRIPTION
**Pull request by linhongliu-db**
### What changes were proposed in this pull request?
This reverts commit 9fc3aa0b1c092ab1f13b26582e3ece7440fbfc3b.

### Why are the changes needed?
The upgrade breaks `dev/sbt-checkstyle` script, below is the error
```
[error] org.xml.sax.SAXParseException; lineNumber: 18; columnNumber: 10; DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true.
[error]         at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
[error]         at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
[error]         at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
[error]         at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
[error]         at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1473)
[error]         at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:914)
[error]         at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
[error]         at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
[error]         at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
[error]         at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
[error]         at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
[error]         at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
[error]         at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
[error]         at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
[error]         at scala.xml.factory.XMLLoader.parse(XMLLoader.scala:73)
[error]         at scala.xml.factory.XMLLoader.loadXML(XMLLoader.scala:54)
[error]         at scala.xml.factory.XMLLoader.loadXML$(XMLLoader.scala:53)
[error]         at scala.xml.XML$.loadXML(XML.scala:62)
[error]         at scala.xml.factory.XMLLoader.loadString(XMLLoader.scala:92)
[error]         at scala.xml.factory.XMLLoader.loadString$(XMLLoader.scala:92)
[error]         at scala.xml.XML$.loadString(XML.scala:62)
[error]         at com.etsy.sbt.checkstyle.Checkstyle$.checkstyle(Checkstyle.scala:35)
[error]         at com.etsy.sbt.checkstyle.CheckstylePlugin$autoImport$.$anonfun$checkstyleTask$1(CheckstylePlugin.scala:36)
[error]         at com.etsy.sbt.checkstyle.CheckstylePlugin$autoImport$.$anonfun$checkstyleTask$1$adapted(CheckstylePlugin.scala:34)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
```

### CODE REVIEW

**Review by itholic — APPROVED** [review]
LGTM when test passing

**Comment by linhongliu-db** [comment]
cc @LuciferYang, maybe you'll have a fix so we won't need to revert it.

**Comment by linhongliu-db** [comment]
BTW, I really couldn't understand how this is problematic: https://github.com/sbt/sbt/compare/v1.7.2...v1.7.3

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master

Since this is a clean revert.

**Comment by dongjoon-hyun** [comment]
Oh, thank you for reverting, @linhongliu-db and @HyukjinKwon .

**Comment by LuciferYang** [comment]
Sorry for the late reply. I want to know why GA doesn't have this issue? master CI always seems healthy,  how can we reproduce this? Let me investigate this.

**Comment by LuciferYang** [comment]
> Sorry for the late reply. I want to know why GA doesn't have this issue? master CI always seems healthy, how can we reproduce this? Let me investigate this.

Run `dev/sbt-checkstyle` locally can reproduce this issue, let me investigate it to find how to solve this problem .

**Comment by LuciferYang** [comment]
Try fix with https://github.com/apache/spark/pull/38481

**Pull request closed without merging**
