### PR TITLE
[SPARK-14659][ML] RFormula supports setting base level both by frequency and alphabetically 

### PR DESCRIPTION
**Pull request by actuaryzhang**
## What changes were proposed in this pull request?
Current RFormula drops the least frequent level for a string feature column because StringIndexer sorts string values in descending order of frequency. Two issues with this:
- In practical applications, there is often need to set the most frequent value as the reference level for better interpretability.  
- Other software such as R sets the first  alphabetical value as the reference level. It's desirable to have such an option in order to compare results.

This PR adds more options to order string values in StringIndexer and RFormula. We add a parameter `stringOrderType` to control how string is ordered which supports four options:  
 - "freq_desc": sort in descending order by frequency of values. In StringIndexer, the most frequent value is indexed 0, and in RFormula the least frequent value is the reference level. This is the default and consistent with current behavior. 
- "freq_asc": sort in ascending order by frequency of values. In StringIndexer, the least frequent value is indexed 0, and in RFormula the most frequent value is the reference level. 
- "alphabet_desc": sort in alphabetically descending order. This sets the first alphabetical value as reference level in RFormula, which is R's default behavior. 
- "alphabet_asc": sort in alphabetically ascending order.

## How was this patch tested?
New tests added for StringIndexer and RFormula.

### CODE REVIEW

**Comment by actuaryzhang** [comment]
@srowen @jkbradley @felixcheung @sethah @yanboliang 

One question is: is it better to move the `HasStringOrderType` trait to the shared params? This is only used by StringIndexer and RFormula now. Please advise. Thanks.

**Comment by actuaryzhang** [comment]
Cannot figure out what's exactly causing the test to fail. Error message is not informative. Any help please?

**Comment by HyukjinKwon** [comment]
(It seems it was due to https://github.com/apache/spark/commit/73f065569d352081b7d64c254af70ce996860c53.)

**Comment by actuaryzhang** [comment]
@HyukjinKwon Thanks. I'll try retesting this.

**Comment by felixcheung** [comment]
thanks! merged to master and branch-2.1

**Pull request closed without merging**
