### PR TITLE
[SPARK-44053][BUILD][3.4] Update ORC to 1.8.4

### PR DESCRIPTION
**Pull request by guiyanakuang**
### What changes were proposed in this pull request?

This PR aims to update ORC to 1.8.4.

### Why are the changes needed?

This will bring the following bug fixes.
- https://issues.apache.org/jira/projects/ORC/versions/12353041

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the CIs.

### CODE REVIEW

**Comment by guiyanakuang** [comment]
cc @dongjoon-hyun

**Comment by wangyum** [comment]
@guiyanakuang Please make the PR against the master branch.

**Comment by guiyanakuang** [comment]
> @guiyanakuang Please make the PR against the master branch. You can change it here: image

[The plan after ORC community discussion is](https://lists.apache.org/thread/53y8vkkttw1qbk5nglvn62s87zg7c4gw)

Apache ORC 1.8.4 (2023-06-16, Yiqun Zhang) => Apache Spark 3.4.1
Apache ORC 1.9.0 (2023-06-30, Dongjoon Hyun) => Apache Spark 3.5.0

So I should have the right branch

**Comment by dongjoon-hyun** [comment]
Hi, @guiyanakuang and @wangyum .

Both of you are right and I'll release Apache ORC 1.9.0 in this month.

This is more like a timing issue where Apache Spark `master` branch is still using `1.8.3` because Apache ORC 1.9.0 is not released yet.

If Apache Spark `master` branch is already `1.9.0`, this PR is correct. 

So, @guiyanakuang , could you make another PR for `master` branch too? I can merge both PRs sequently from `master` first and `branch-3.4` second.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM (Pending CIs)

**Comment by dongjoon-hyun** [comment]
I updated the title of this PR to `[SPARK-44053][BUILD][3.4] Update ORC to 1.8.4`. 
For your new PR for `master` branch, please use `[SPARK-44053][BUILD] Update ORC to 1.8.4`.

**Comment by guiyanakuang** [comment]
I get it. Thanks @dongjoon-hyun and @wangyum

**Comment by dongjoon-hyun** [comment]
Merged to branch-3.4 for Apache Spark 3.4.0.

I merged https://github.com/apache/spark/pull/41593 first to master and merged this one.

**Comment by dongjoon-hyun** [comment]
Welcome to the Apache Spark community again, @guiyanakuang !

**Pull request closed without merging**
