### PR TITLE
[SPARK-21195] Automatically register new metrics from sources and wire default registry

### PR DESCRIPTION
**Pull request by robert3005**
## What changes were proposed in this pull request?
Registers metric listeners on sources metrics that forward actions to metricssystem metric registry. Hooks into default metric registry for easier integration with non spark specific libraries

## How was this patch tested?
Added tests

### CODE REVIEW

**Comment by jiangxb1987** [comment]
ok to test

**Comment by ash211** [comment]
Jenkins this is ok to test

**Comment by ash211** [comment]
@robert3005 looks like a bunch of tests are failing with 
`java.lang.IllegalArgumentException: A metric named local-1498509661743.driver.HiveExternalCatalog.fileCacheHits already exists`

**Comment by jerryshao** [comment]
@robert3005 would you please elaborate the usage scenario of your proposal, AFAIK Spark internally doesn't have such requirement.

**Comment by robert3005** [comment]
This is to facilitate using metrics in libraries that integrate in spark. Since spark already has metric reporting infrastructure and lets you register sources with it it seems natural extension to not require preregistering metrics. I am using instrumentation libraries to create metrics and those can register metrics lazily when necessary

**Comment by jerryshao** [comment]
@robert3005 based on your description, this feature is more like your own customized requirement, not Spark itself. I'm wondering can it be worked out of Spark?

**Comment by robert3005** [comment]
I don't see how this can be worked out. Let's say I am parquet and I want to register my metrics since they're part of application execution. Right now I have to statically define all metrics upfront which is a lot of unnecessary boilerplate

**Comment by jerryshao** [comment]
So the key point is that should metrics system understand dynamic registered metrics, am I understanding right? If the registered metrics are static ones, then I think current code should be enough to work?

**Comment by robert3005** [comment]
Yes, the key point is to register dynamic metrics since enumerating all of them can be a lot of hassle and needs to be kept in sync with external libraries

**Comment by robert3005** [comment]
@jerryshao sorry I missed your comment. Somehow didn't get notification for it

**Pull request closed without merging**
