### PR TITLE
[SPARK-9055][SQL] WidenTypes should also support Intersect and Except

### PR DESCRIPTION
**Pull request by yjshen**
JIRA: https://issues.apache.org/jira/browse/SPARK-9055

cc @rxin

### CODE REVIEW

**Comment by rxin** [comment]
Jenkins, add to whitelist.

**Comment by rxin** [comment]
Jenkins, ok to test.

**Comment by rxin** [comment]
cc @cloud-fan for review

**Comment by yijieshen** [comment]
"why doesn't jenkins like me" :)

**Comment by cloud-fan** [comment]
lgtm.
This PR remind me that we have another place deal with Union at [`Optimizer`](https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/optimizer/Optimizer.scala#L89), maybe we should update that too, or in another PR.

**Comment by rxin** [comment]
Jenkins, ok to test.

**Comment by rxin** [comment]
In addition to union pushdown, there is also the decimal type coercion in the same file. Those can be done as separate pull requests.

**Comment by rxin** [comment]
I filed https://issues.apache.org/jira/browse/SPARK-9173 and https://issues.apache.org/jira/browse/SPARK-9172 for those two.

**Comment by rxin** [comment]
Thanks - merging this.

**Pull request closed without merging**
