### PR TITLE
[SPARK-45812][BUILD][PYTHON][PS] Upgrade Pandas to 2.1.2

### PR DESCRIPTION
**Pull request by itholic**
### What changes were proposed in this pull request?

This PR proposes to upgrade Pandas to 2.1.2.

See https://pandas.pydata.org/docs/dev/whatsnew/v2.1.2.html for detail

### Why are the changes needed?

Pandas 2.1.2 is released, and we should support the latest Pandas.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

The existing CI should pass

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM (Pending CIs).

**Comment by dongjoon-hyun** [comment]
All Python related tests passed.

**Comment by dongjoon-hyun** [comment]
Merged to master. Thank you, @itholic .

**Comment by itholic** [comment]
Thanks for the review, @dongjoon-hyun !

**Pull request closed without merging**
