### PR TITLE
[SPARK-12924][SQL] Make Token pattern matching in the parser case insensitive

### PR DESCRIPTION
**Pull request by rxin**
In addition, I also moved the regular expressions into the companion object, so we don't need to recompile the regexes for every new instance of CatalystQl.

### CODE REVIEW

**Comment by rxin** [comment]
cc @hvanhovell

**Comment by rxin** [comment]
Actually this approach won't work because it also renames all the tokens to upper case. I'm going to close this.

**Comment by hvanhovell** [comment]
There is still merit in moving the regexes, but I can also adress this in a different PR

**Comment by rxin** [comment]
Yea why don't you do it as part of the refactoring. Thanks!

**Comment by rxin** [comment]
@hvanhovell we should also move CatalystQl into the parser package, and rename it BaseQueryParser or something like that rather than CatalystQl.

**Pull request closed without merging**
