### PR TITLE
[SPARK-15898][SQL] DataFrameReader.text should return DataFrame

### PR DESCRIPTION
**Pull request by cloud-fan**
## What changes were proposed in this pull request?

We want to maintain API compatibility for DataFrameReader.text, and will introduce a new API called DataFrameReader.textFile which returns Dataset[String].

affected PRs:
https://github.com/apache/spark/pull/11731
https://github.com/apache/spark/pull/13104
https://github.com/apache/spark/pull/13184
## How was this patch tested?

N/A

### CODE REVIEW

**Comment by rxin** [comment]
LGTM - I guess the main question now is whether we want to change SparkSession.range's return type.

**Comment by liancheng** [comment]
I'd prefer change `SparkSession.range`'s return type to `Dataset[Row]` for better consistency, also there's an annoying nullability issue regarding to `Dataset[java.lang.Long]` (boxed types are nullable while `range` doesn't really return nulls).

**Comment by rxin** [comment]
Can you break the text change from the range change? i.e. 2 prs.

I think @marmbrus doesn't agree with the text change so we should debate more.

**Comment by marmbrus** [comment]
I'm not sure I agree with all of the reasoning here.  Here are my thoughts:
 - `SQLContext` should probably not break any APIs (its only there for compatibility anyway).
 - In `SparkSession`, we should consider that many of the users will be coming from SparkContext and will expect similar semantics (i.e. `sc.textFile`).
 - We should think about the experience of new users who are just getting started with the API.  Several people, who are not as familiar with Spark as you guys, did comment they were surprised that `range`/`text` were returning `Row`, which is why its the way it is today.

> spark.read.text() silently discards partitioned columns when reading a partitioned table in text format since Dataset[String] only contains a single field.  Users have to use spark.read.format("text").load() to workaround this, which is pretty confusing and error-prone.

The behavior is pretty clearly documented.  Have users actually complained about this?

**Comment by rxin** [comment]
@cloud-fan change the title/description to have only text?

**Comment by rxin** [comment]
To summarize:

For people coming from RDD land, they would assume read.text to return Dataset[String], and it is easier to program for those guys.

That said, there are also arguments for using generic DataFrame:

1. Consistent with other methods in DataFrameReader (since all other methods return DataFrame) -- but you could argue text is the only one that has a fixed schema, when partitioning is off.

2. Would be able to support partitioning and make it the same as `format("text").load("...")`

**Comment by cloud-fan** [comment]
I prefer the alternative approach, which also achieves the goal that being more friendly to users from RDD land, and still keeps backward compatibility for `read.text`

**Comment by rxin** [comment]
Can you update the pr and link to this ticket? https://issues.apache.org/jira/browse/SPARK-15898

Thanks.

**Comment by rxin** [comment]
LGTM pending tests.

**Comment by rxin** [comment]
Merging in master/2.0.

**Pull request closed without merging**
