### PR TITLE
[SPARK-30554][SQL] Return `Iterable` from `FailureSafeParser.rawParser`

### PR DESCRIPTION
**Pull request by MaxGekk**
### What changes were proposed in this pull request?
Changed signature of `rawParser` passed to `FailureSafeParser`. I propose to change return type from `Seq` to `Iterable`. I took `Iterable` to easier port the changes on Scala collections 2.13. Also, I replaced `Seq` by `Option` in CSV datasource - `UnivocityParser`, and in JSON parser exception one place in the case when specified schema is `StructType`, and JSON input is an array. 

### Why are the changes needed?
`Seq` is unnecessary requirement for return type from rawParser which may not have multiple rows per input like CSV datasource. 

### Does this PR introduce any user-facing change?
No

### How was this patch tested?
By existing test suites `JsonSuite`, `UnivocityParserSuite`, `JsonFunctionsSuite`, `JsonExpressionsSuite`, `CsvSuite`, and `CsvFunctionsSuite`.

### CODE REVIEW

**Comment by MaxGekk** [comment]
@HyukjinKwon @srowen Please, review this PR.

**Comment by srowen** [comment]
Seems OK; is it just some code polish or does it make an impact on performance?

**Comment by MaxGekk** [comment]
@srowen Main goal is code polish. Potentially, it could improve performance slightly because `Seq` builder is slower than `Option`.

**Comment by MaxGekk** [comment]
jenkins, retest this, please

**Comment by MaxGekk** [comment]
jenkins, retest this, please

**Comment by MaxGekk** [comment]
jenkins, retest this, please

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Thanks @MaxGekk for addressing my comment.

Merged to master.

**Pull request closed without merging**
