### PR TITLE
[SPARK-15784][ML]:Add Power Iteration Clustering to spark.ml

### PR DESCRIPTION
**Pull request by wangmiao1981**
## What changes were proposed in this pull request?

This PR is to add Power Iteration Clustering (`PIC`) to `spark.ml`. The implementation is similar to Kmeans, but there are some fundamental difference (also mentioned in the JIRA SPARK-15784):
1. The input of PIC is a similarity matrix. In this spark.ml implementation, the similarity matrix is represented as dataframe with each row of being a tuple (i, j, s_ij) in `spark.mllib` implementation.
2. PIC is a graph algorithm. Therefore, the output is a cluster assignment of vertices. It implies that the input.size != output.size.
3. PIC is different from Kmeans in terms of prediction. We can't compute a probability to determine new data cluster membership with a trained model, because PIC requires to re-compute the pseudo-eigenvector `v`. 

Considering the above differences, I made the following changes for PIC in `spark.ml`:

For prediction in `PowerIterationClusteringModel`, it takes a new Dataset, instead of single row of a matrix entry. The output is Dataframe of cluster assignments, with vertex indexes as `features`. Note that using input similarity matrix as `features` doesn't make sense. 

For transform in `PowerIterationClusteringModel`, it calls the `PowerIterationClusteringModel.predict` to convert a Dataset to cluster assignment Dataframe.  

For `PowerIterationClustering.fit`, it returns a `PowerIterationClusteringModel` instance and saves the parameters to get the model, because `PowerIterationClusteringModel.predict` will need these parameters.
## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)
Add unit tests which are similar to `spark.mllib` but in Dataframe. Also add tests of prediction and transform. Manual tests.

### CODE REVIEW

**Comment by wangmiao1981** [comment]
@yanboliang As we discussed offline, I made the implementation. You might want to take a pass on the implementation. cc @mengxr @josephkb

**Comment by wangmiao1981** [comment]
ping @mengxr @jkbradley @yanboliang Can you give me some comments on this PR? I can start improving it for 2.1+.

Thanks!

**Comment by jkbradley** [comment]
@wangmiao1981 Sorry for the slow response here!  I do want us to add PIC to spark.ml, but we should discuss the design before the PR.  Could you please close this PR for now but save the branch to re-open after discussion on the JIRA?  I just commented on the JIRA

**Comment by wangmiao1981** [comment]
@jkbradley Thanks for your reply! I just want to initiate the work. I close it now and we can continue the design on JIRA.

**Pull request closed without merging**
