### PR TITLE
[SPARK-39237][DOCS][3.2] Update the ANSI SQL mode documentation

### PR DESCRIPTION
**Pull request by gengliangwang**
### What changes were proposed in this pull request?

1. Remove the Experimental notation in ANSI SQL compliance doc
2. Update the description of `spark.sql.ansi.enabled`

### Why are the changes needed?

1. The ANSI SQL dialect is GAed in Spark 3.2 release: https://spark.apache.org/releases/spark-release-3-2-0.html
We should not mark it as "Experimental" in the doc.
2.  Mention type coercion in the doc of `spark.sql.ansi.enabled`

### Does this PR introduce _any_ user-facing change?

No, just doc change
### How was this patch tested?

Doc preview:
image

image

### CODE REVIEW

**Comment by gengliangwang** [comment]
This is to port https://github.com/apache/spark/pull/36614 to branch-3.2
cc @tanvn as well

**Review by dongjoon-hyun — APPROVED** [review]

**Comment by gengliangwang** [comment]
@dongjoon-hyun Thanks for the review
Merging to 3.2

**Comment by tanvn** [comment]
@gengliangwang 
Thank you for the update!
May I know when will the change be reflected on https://spark.apache.org/docs/latest/sql-ref-ansi-compliance.html ?

**Comment by gengliangwang** [comment]
@tanvn It would be reflected upon 3.3.0 release

**Pull request closed without merging**
