### PR TITLE
[SPARK-41050][BUILD] Upgrade scalafmt from 3.5.9 to 3.6.1

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to upgrade scalafmt from 3.5.9 to 3.6.1

### Why are the changes needed?
A. Release note:
> https://github.com/scalameta/scalafmt/releases

B. V3.5.9 VS V3.6.1
> https://github.com/scalameta/scalafmt/compare/v3.5.9...v3.6.1

C. Bring bug fix:
image
image

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Manually run: sh ./dev/scalafmt

### CODE REVIEW

**Comment by LuciferYang** [comment]
@panbingkun hmm... The changes is inconsistent with the title. Please revert the files that do not need to be change

**Comment by panbingkun** [comment]
> @panbingkun hmm... The changes is inconsistent with the title. Please revert the files that do not need to be change

Err..., Done!

**Review by srowen — COMMENTED** [review]
Looks OK if tests pass

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
