### PR TITLE
[SPARK-7427] [PySpark] Make sharedParams match in Scala, Python

### PR DESCRIPTION
**Pull request by gweidner**
Modified 2 files:
python/pyspark/ml/param/_shared_params_code_gen.py
python/pyspark/ml/param/shared.py

Generated shared.py on Linux using Python 2.6.6 on Redhat Enterprise Linux Server 6.6. 
python _shared_params_code_gen.py > shared.py

Only changed maxIter, regParam, rawPredictionCol based on strings from SharedParamsCodeGen.scala.  Note warning was displayed when committing shared.py:
warning: LF will be replaced by CRLF in python/pyspark/ml/param/shared.py.

### CODE REVIEW

**Comment by jkbradley** [comment]
ok to test

**Comment by gweidner** [comment]
Thank you - monitoring and available in case any issues.

**Comment by jkbradley** [comment]
LGTM pending tests---thanks!  codegen gave me the same results

**Comment by jkbradley** [comment]
Looking into how to make the Python PEP8 checker ignore that generated file...

**Comment by jkbradley** [comment]
OK, found out.  Can you please look at the tox.ini file in the root spark directory?  Add "shared.py" to the exclude line:
```
exclude=cloudpickle.py,heapq3.py,shared.py
```

**Comment by gweidner** [comment]
Definitely - my bad. I just committed shared.py so this Pull Request now shows 3 files changed.

**Comment by gweidner** [comment]
Correction to my last comment - committed tox.ini which now includes shared.py.

**Comment by gweidner** [comment]
In progress updating unit tests to fix failure such as:
Traceback (most recent call last):
  File "pyspark/ml/tests.py", line 131, in test_param
    self.assertEqual(maxIter.doc, "max number of iterations")

**Comment by gweidner** [comment]
Committed updated python/pyspark/ml/tests.py to fix two PySpark unit tests failures (lines 131 and 159).

**Comment by gweidner** [comment]
Jenkins, retest this please

**Comment by jkbradley** [comment]
@gweidner Thanks!  Btw, only committers can generally give Jenkins instructions via comments, and even those are pretty flaky, so tests sometimes have to be started manually.

**Comment by gweidner** [comment]
I can't thank you enough Joseph for you patience and support!  I will do better next time - my mistake again but I now understand why and how to ./run-tests in my local environment.

[bigdata@bdavm159 python]$ ./run-tests
Running PySpark tests. Output is in python/unit-tests.log.
Testing with Python version:
Python 2.6.6
Run core tests ...
...
...
Running test: pyspark/streaming/tests.py
which: no pypy in (/usr/local/apache-maven-3.0.5/bin:/usr/local/apache-maven-3.0.5/bin:/usr/local/apache-maven-3.0.5/bin:/usr/local/apache-maven-3.0.5/bin:/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/lib/node-v0.10.36-linux-x64/bin:/root/bin:/usr/lib/node-v0.10.36-linux-x64/bin:/usr/lib/node-v0.10.36-linux-x64/bin)
Tests passed.
[bigdata@bdavm159 python]$

**Comment by gweidner** [comment]
The modified ml/tests.py succeeded but the log shows the following error in last streaming/tests.py:
Run ml tests ...
Running test: pyspark/ml/feature.py ... ok (28s)
Running test: pyspark/ml/classification.py ... ok (14s)
Running test: pyspark/ml/tuning.py ... ok (9s)
Running test: pyspark/ml/tests.py ... ok (7s)
Running test: pyspark/ml/evaluation.py ... ok (11s)
Run streaming tests ...
Running test: pyspark/streaming/util.py ... ok (1s)
Running test: pyspark/streaming/tests.py ... ..................................F.....
======================================================================
FAIL: test_count_by_value_and_window (__main__.WindowFunctionTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pyspark/streaming/tests.py", line 418, in test_count_by_value_and_window
    self._test_func(input, func, expected)
  File "pyspark/streaming/tests.py", line 133, in _test_func
    self.assertEqual(expected, result)
AssertionError: Lists differ: [[1], [2], [3], [4], [5], [6], [6], [6], [6], [6]] != [[1], [2], [3], [4], [5], [6], [6], [6]]

First list contains 2 additional elements.
First extra element 8:
[6]

- [[1], [2], [3], [4], [5], [6], [6], [6], [6], [6]]
?                                     ----------

+ [[1], [2], [3], [4], [5], [6], [6], [6]]

----------------------------------------------------------------------
Ran 40 tests in 168.147s


Trying to understand how the change could have impacted the streaming test and also see why not happening locally.

**Comment by gweidner** [comment]
@jkbradley - Could test_count_by_value_and_window() be a "flaky test"?
For example, I found the following recent information:
http://apache-spark-developers-list.1001551.n3.nabble.com/Flaky-streaming-tests-td6237.html
SPARK-7341 - Fix the flaky test: org.apache.spark.streaming.InputStreamsSuite.socket input stream

**Comment by gweidner** [comment]
Looking at the history of streaming/tests.py noticed "[SPARK-6953] [PySpark] speed up python tests".
I'm checking if adjusting the following values impacts the test result to see if it's timing-related since as far as I can tell sharedParams not involved in streaming:

dstream.countByValueAndWindow(1, .2)
vs
dstream.countByValueAndWindow(5, 1)

**Comment by jkbradley** [comment]
@gweidner Thanks for looking into it!  There have been flakiness issues we've been trying to fix.  For now, I'll just re-run the tests, but I'll check with TD and Davies about this one test.

**Comment by jkbradley** [comment]
And btw, happy to help!  It's great to have new contributors.

**Comment by jkbradley** [comment]
LGTM merging with master and branch-1.4

**Pull request closed without merging**
