### PR TITLE
[SPARK-22393][SPARK-SHELL] spark-shell can't find imported types in class constructors, extends clause

### PR DESCRIPTION
**Pull request by mpetruska**
## What changes were proposed in this pull request?

[SPARK-22393](https://issues.apache.org/jira/browse/SPARK-22393)

## How was this patch tested?

With a new test case in `RepSuite`

----

This code is a retrofit of the Scala [SI-9881](https://github.com/scala/bug/issues/9881) bug fix, which never made it into the Scala 2.11 branches. Pushing these changes directly to the Scala repo is not practical (see: https://github.com/scala/scala/pull/6195).

### CODE REVIEW

**Comment by mpetruska** [comment]
Sorry, could not refactor the code better; since it makes heavy use of path-dependent types.

**Comment by srowen** [comment]
OK, so this just affects the Scala 2.11 REPL in Spark (good, because the 2.12 version works a little differently and the fix is already in 2.12), and you've just copied in the fixed classes and injected the fixed impl? sounds reasonable.

**Comment by mpetruska** [comment]
@srowen Yes, exactly. Tried to minimize the risks of any problems caused by this change.

**Comment by HyukjinKwon** [comment]
@mpetruska, btw can you fill up the PR description about how it fixes?

**Comment by mpetruska** [comment]
@HyukjinKwon : Hi, yes: this is the "retrofitting" of the original bug fix, which never made it to Scala 2.11. Instead of copy-pasting the original discussion, let me link the [original PR](https://github.com/scala/scala/pull/5640).
I can add more details about specific parts, of course.

**Comment by srowen** [comment]
Merged to master

**Pull request closed without merging**
