### PR TITLE
[SPARK-48590][BUILD] Upgrade netty to `4.1.114.Final`

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to upgrade `netty` from `4.1.110.Final` to `4.1.114.Final`.

### Why are the changes needed?
https://netty.io/news/2024/10/01/4-1-114-Final.html
https://netty.io/news/2024/09/04/4-1-113-Final.html
https://netty.io/news/2024/07/19/4-1-112-Final.html
https://netty.io/news/2024/06/11/4-1-111-Final.html

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Are the failures relevant?

**Comment by panbingkun** [comment]
> Are the failures relevant?

Yes, let me continue investigating it.

**Review by dongjoon-hyun — COMMENTED** [review]
Thank you for moving to `4.1.112.Final`.

**Comment by dongjoon-hyun** [comment]
Could you rebase to the `master` branch once more? It seems that we passed the CIs except the known flaky tests, @panbingkun .
```
[info] *** 6 TESTS FAILED ***
[error] Failed tests:
[error] 	org.apache.spark.sql.connect.execution.ReattachableExecuteSuite
[error] 	org.apache.spark.sql.connect.service.SparkConnectServiceE2ESuite
```

**Comment by panbingkun** [comment]
> Could you rebase to the `master` branch once more? It seems that we passed the CIs except the known flaky tests, @panbingkun .
> 
> ```
> [info] *** 6 TESTS FAILED ***
> [error] Failed tests:
> [error] 	org.apache.spark.sql.connect.execution.ReattachableExecuteSuite
> [error] 	org.apache.spark.sql.connect.service.SparkConnectServiceE2ESuite
> ```

Done.

**Comment by dongjoon-hyun** [comment]
Thank you, @panbingkun .

**Comment by dongjoon-hyun** [comment]
Thank you for keeping tracking and testing `4.1.113.Final`.

**Comment by panbingkun** [comment]
cc @LuciferYang

**Review by LuciferYang — APPROVED** [review]
+1, LGTM

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @panbingkun and @LuciferYang .
Merged to master for Apache Spark 4.0.0 on February 2025.

**Pull request closed without merging**
