### PR TITLE
[SPARK-31786][K8S][BUILD] Upgrade kubernetes-client to 4.9.2

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to upgrade `kubernetes-client` library to bring the JDK8 related fixes. Please note that JDK11 works fine without any problem.
- https://github.com/fabric8io/kubernetes-client/releases/tag/v4.9.2
  - JDK8 always uses http/1.1 protocol (Prevent OkHttp from wrongly enabling http/2)

### Why are the changes needed?

OkHttp "wrongly" detects the Platform as Jdk9Platform on JDK 8u251. 
- https://github.com/fabric8io/kubernetes-client/issues/2212
- https://stackoverflow.com/questions/61565751/why-am-i-not-able-to-run-sparkpi-example-on-a-kubernetes-k8s-cluster

Although there is a workaround `export HTTP2_DISABLE=true` and `Downgrade JDK or K8s`, we had better avoid this problematic situation.

### Does this PR introduce _any_ user-facing change?

No. This will recover the failures on JDK 8u252.

### How was this patch tested?

- [x] Pass the Jenkins UT (https://github.com/apache/spark/pull/28601#issuecomment-632474270)
- [x] Pass the Jenkins K8S IT with the K8s 1.13 (https://github.com/apache/spark/pull/28601#issuecomment-632438452)
- [x] Manual testing with K8s 1.17.3. (Below)

**v1.17.6 result (on Minikube)**
```
KubernetesSuite:
- Run SparkPi with no resources
- Run SparkPi with a very long application name.
- Use SparkLauncher.NO_RESOURCE
- Run SparkPi with a master URL without a scheme.
- Run SparkPi with an argument.
- Run SparkPi with custom labels, annotations, and environment variables.
- All pods have the same service account by default
- Run extraJVMOptions check on driver
- Run SparkRemoteFileTest using a remote data file
- Run SparkPi with env and mount secrets.
- Run PySpark on simple pi.py example
- Run PySpark with Python2 to test a pyfiles example
- Run PySpark with Python3 to test a pyfiles example
- Run PySpark with memory customization
- Run in client mode.
- Start pod creation from template
- PVs with local storage
- Launcher client dependencies
- Test basic decommissioning
Run completed in 8 minutes, 27 seconds.
Total number of tests run: 19
Suites: completed 2, aborted 0
Tests: succeeded 19, failed 0, canceled 0, ignored 0, pending 0
All tests passed.
```

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Since there is a revert on master branch (https://github.com/apache/spark/commit/db5e5fce68f7e3a724eb4516908c4ba9786b0db3), I'll rebase once more to make it sure.

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by dongjoon-hyun** [comment]
The one failure in the last K8s IT is a known flaky one.
```
KubernetesSuite:
- Run SparkPi with no resources *** FAILED ***
  The code passed to eventually never returned normally. Attempted 130 times over 2.0017359222166666 minutes. Last failure message: false was not true. (KubernetesSuite.scala:370)
- Run SparkPi with a very long application name.
- Use SparkLauncher.NO_RESOURCE
- Run SparkPi with a master URL without a scheme.
- Run SparkPi with an argument.
- Run SparkPi with custom labels, annotations, and environment variables.
- All pods have the same service account by default
- Run extraJVMOptions check on driver
- Run SparkRemoteFileTest using a remote data file
- Run SparkPi with env and mount secrets.
- Run PySpark on simple pi.py example
- Run PySpark with Python2 to test a pyfiles example
- Run PySpark with Python3 to test a pyfiles example
- Run PySpark with memory customization
- Run in client mode.
- Start pod creation from template
- PVs with local storage
- Launcher client dependencies
- Test basic decommissioning
- Run SparkR on simple dataframe.R example
Run completed in 14 minutes, 43 seconds.
Total number of tests run: 20
Suites: completed 2, aborted 0
Tests: succeeded 19, failed 1, canceled 0, ignored 0, pending 0
*** 1 TEST FAILED ***
```

**Comment by dongjoon-hyun** [comment]
cc @dbtsai and @holdenk

**Comment by dongjoon-hyun** [comment]
`WorkerDecommissionSuite` is irrelevant to this PR.
```
org.apache.spark.scheduler.WorkerDecommissionSuite.verify a task with all workers decommissioned succeeds
```

**Comment by maver1ck** [comment]
@dongjoon-hyun 
Any reason of not using kubernetes-client 4.10.1?

**Comment by ScrapCodes** [comment]
@dongjoon-hyun, I have the same question as above, why not upgrade to 4.10.1 ?

Looks good otherwise.

**Comment by dongjoon-hyun** [comment]
Thank you for review, @maver1ck and @ScrapCodes .
In this PR, I tried 4.10.1 and 4.10.0 first. However, the dependency change was too huge. And, `kubernetes-model` was split into many jars in 4.10.x. Given the risk and complexity of 4.10.x, 4.9.2 is more safer option which having a minimal change for this issue. Since we need backport this PR to 3.0.0 RC3 and 2.4.6 RC4, minimizing risk is important. We can revisit 4.10.x later for the other issues.
- https://github.com/apache/spark/pull/28601/commits/760030bbb2f50569ef1d2c5427b14d53d2996ef1

**Comment by holdenk** [comment]
Jenkins retest this please.
LGTM pending Jenkins

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Review by viirya — APPROVED** [review]
looks ok and 4.9.2 seems less risky.

**Comment by srowen** [comment]
Yeah a minor update for now, esp if being backported, seems prudent.

**Comment by dongjoon-hyun** [comment]
Thank you all. Merged to master/branch-3.0

**Comment by dongjoon-hyun** [comment]
Due to the conflicts on dependency file, I need to make a backporting PR separately.

BTW, `branch-3.0` is currently broken by https://github.com/apache/spark/pull/28604. 

The backporting PR will fail due the above failure.

**Comment by dongjoon-hyun** [comment]
This is tested with the latest JDK8 and K8s 1.17.x manually and backported to `branch-3.0`.

**Pull request closed without merging**
