### PR TITLE
[SPARK-35057][SQL] Group exception messages in hive/thriftserver

### PR DESCRIPTION
**Pull request by beliefer**
### What changes were proposed in this pull request?
This PR group exception messages in `sql/hive-thriftserver/src/main/scala/org/apache/spark/sql/hive/thriftserver`.

### Why are the changes needed?
It will largely help with standardization of error messages and its maintenance.

### Does this PR introduce _any_ user-facing change?
No. Error messages remain unchanged.

### How was this patch tested?
No new tests - pass all original tests to make sure it doesn't break any existing behavior.

### CODE REVIEW

**Comment by beliefer** [comment]
ping @allisonwang-db

**Review by allisonwang-db — APPROVED** [review]

**Comment by beliefer** [comment]
cc @cloud-fan

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Comment by beliefer** [comment]
@allisonwang-db Thank you for review. @cloud-fan Thanks too!

**Pull request closed without merging**
