### PR TITLE
[SPARK-22000][SQL][FOLLOW-UP] Fix bad test to ensure it can test properly

### PR DESCRIPTION
**Pull request by HeartSaVioR**
## What changes were proposed in this pull request?

There was some mistake on test code: it has wrong assertion. The patch proposes fixing it, as well as fixing other stuff to make test really pass.

## How was this patch tested?

Fixed unit test.

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
cc. @maropu @cloud-fan @srowen This patch fixes a silly mistake in #23854.

**Review by maropu — APPROVED** [review]

**Comment by maropu** [comment]
LGTM, pending Jenkins.

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HeartSaVioR** [comment]
retest this, please

**Comment by maropu** [comment]
Thanks! Merged to master.

**Comment by HeartSaVioR** [comment]
Thanks for the quick review and merge!

**Pull request closed without merging**
