### PR TITLE
[SPARK-16044][SQL] Backport input_file_name() for data source based on NewHadoopRDD to branch 1.6

### PR DESCRIPTION
**Pull request by HyukjinKwon**
## What changes were proposed in this pull request?

This PR backports https://github.com/apache/spark/pull/13759. 

(`SqlNewHadoopRDDState` was renamed to `InputFileNameHolder` and `spark` API does not exist in branch 1.6)
## How was this patch tested?

Unit tests in `ColumnExpressionSuite`.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
It seems the error is not related with this change.

**Comment by HyukjinKwon** [comment]
I will re-run this test here and meanwhile, I will try to build in my local and run the Python tests.

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
I guess it is about https://github.com/apache/spark/commit/f4af6a8b3ce5cea4dc4096e43001c7d60fce8cdb. I will look into this deeper.

**Comment by JoshRosen** [comment]
Jenkins, retest this please.

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
Hm... am I doing something wrong here?

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
Again, I think the error message is not related with this change. I will retest this and meanwhile try to build in my local.

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
retest this please

**Comment by HyukjinKwon** [comment]
@JoshRosen finally I got passed!

**Comment by rxin** [comment]
Merging. Thanks!

Can you close this?

**Pull request closed without merging**
