### PR TITLE
[MINOR][DOCS][3.5] Fix specified java versions in `install.rst`

### PR DESCRIPTION
**Pull request by dvorst**
### What changes were proposed in this pull request?

Documentation change: the JAVA versions mentioned on the getting_started page of PySpark 3.5 are corrected (https://spark.apache.org/docs/3.5.3/api/python/getting_started/install.html#dependencies).

### Why are the changes needed?

The original description "PySpark requires Java 8 or later" is incorrect since 3.5 does not support java prior to 8u371 anymore and the latest supported version is 17, the downloading page (https://spark.apache.org/docs/3.5.3/#downloading) however, does correctly state this. I thus corrected the mentioned java versions.

### Does this PR introduce _any_ user-facing change?

Yes
documentation fix

### How was this patch tested?

Manually

### Was this patch authored or co-authored using generative AI tooling?

No

### CODE REVIEW

**Review by LuciferYang — CHANGES_REQUESTED** [review]
Do you mean that Apache Spark 3.5 no longer supports Java 8 in PySpark? Are there any specific cases? If that's really the case, we should fix it to support Java 8 instead of revising the documentation.

**Comment by dvorst** [comment]
The following is mentioned on the downloadings page (https://spark.apache.org/docs/3.5.3/#downloading)
> Java 8 prior to version 8u371 support is deprecated as of Spark 3.5.0

For some reason, I misread this and was under the impression that support for Java 8 was deprecated in its entirety as of 3.5.0.

I added a new commit where I updated the documentation and included Java 8 back in, with an exception for versions prior to 8u371.

**Comment by LuciferYang** [comment]
Current changes are fine to me, but please do not disrupt the template for the [r description, every item must be filled out, and the title of the pr should also adhere to the standard format. And are there any other cases where the description of Java 8 versions is not accurate?

**Comment by dvorst** [comment]
Apologies, I updated the PR's title and description, reincorporating the template. If the initial removal of the template is causing issues, I can also close this PR and reopen one with the same changes. If the title/description is still not up to standard, I'm happy to change it to meet the requirements.

I also enabled workflows on my repository, which was causing the build to fail.

Lastly, to answer your question, I haven't run into any cases thus far where the description of Java 8 version is inaccurate.

**Review by LuciferYang — APPROVED** [review]
+1, LGTM

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @dvorst and @LuciferYang .
Merged to branch-3.5.

**Pull request closed without merging**
