### PR TITLE
[SPARK-17578][Docs] Add spark.app.name default value for spark session

### PR DESCRIPTION
**Pull request by phalodi**
## What changes were proposed in this pull request?

Modify spark.app.name configuration for spark session
## How was this patch tested?

run all test cases and generate documentation

appname

### CODE REVIEW

**Comment by andrewor14** [comment]
We should probably just make it a random UUID in all cases to be consistent. I don't know if people check whether `spark.app.name` is set, so that might be a backward compatibility concern (though one that we kind of already broke with `SparkSession`).

**Comment by phalodi** [comment]
@andrewor14 So as you suggest we also change it in spark context code because right now we must set app name while creating spark context. So when we add random UUID generate for default value of spark name while creating spark context then it will be consistent for all cases.

**Comment by andrewor14** [comment]
Yeah `SparkSession` will be the new thing moving forward. `SparkContext` is kind of just a legacy thing.

**Comment by phalodi** [comment]
@andrewor14 what is think about this https://github.com/apache/spark/pull/15134 we add random UUID of app name while creating spark context if its not define.

**Comment by phalodi** [comment]
Also change this one according to that now default value of app name is (random) for session and context

random

**Comment by srowen** [comment]
Let's close this PR, per comments on https://github.com/apache/spark/pull/15134. I don't think we shoudl change this.

**Pull request closed without merging**
