### PR TITLE
[SPARK-29923][SQL][TESTS] Set io.netty.tryReflectionSetAccessible for Arrow on JDK9+

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to add `io.netty.tryReflectionSetAccessible=true` to the testing configuration for JDK11 because this is an officially documented requirement of Apache Arrow.

Apache Arrow community documented this requirement at `0.15.0` ([ARROW-6206](https://github.com/apache/arrow/pull/5078)).
> #### For java 9 or later, should set "-Dio.netty.tryReflectionSetAccessible=true".
> This fixes `java.lang.UnsupportedOperationException: sun.misc.Unsafe or java.nio.DirectByteBuffer.(long, int) not available`. thrown by netty.

### Why are the changes needed?

After ARROW-3191, Arrow Java library requires the property `io.netty.tryReflectionSetAccessible` to be set to true for JDK >= 9. After https://github.com/apache/spark/pull/26133, JDK11 Jenkins job seem to fail.

- https://amplab.cs.berkeley.edu/jenkins/view/Spark%20QA%20Test%20(Dashboard)/job/spark-master-test-maven-hadoop-3.2-jdk-11/676/
- https://amplab.cs.berkeley.edu/jenkins/view/Spark%20QA%20Test%20(Dashboard)/job/spark-master-test-maven-hadoop-3.2-jdk-11/677/
- https://amplab.cs.berkeley.edu/jenkins/view/Spark%20QA%20Test%20(Dashboard)/job/spark-master-test-maven-hadoop-3.2-jdk-11/678/

```scala
Previous exception in task: 
sun.misc.Unsafe or java.nio.DirectByteBuffer.<init>(long, int) not available&#010;
io.netty.util.internal.PlatformDependent.directBuffer(PlatformDependent.java:473)&#010;
io.netty.buffer.NettyArrowBuf.getDirectBuffer(NettyArrowBuf.java:243)&#010;
io.netty.buffer.NettyArrowBuf.nioBuffer(NettyArrowBuf.java:233)&#010;
io.netty.buffer.ArrowBuf.nioBuffer(ArrowBuf.java:245)&#010;
org.apache.arrow.vector.ipc.message.ArrowRecordBatch.computeBodyLength(ArrowRecordBatch.java:222)&#010; 
```

### Does this PR introduce any user-facing change?

No.

### How was this patch tested?

Pass the Jenkins with JDK11.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
cc @BryanCutler

**Comment by BryanCutler** [comment]
@dongjoon-hyun I'm not too familiar with Netty and this issue, but it did come about in https://issues.apache.org/jira/browse/ARROW-3191 for Arrow 0.14.0. Is this something that will affect consumers of Spark jars? I actually thought this was defined in the Arrow POM, but looks like it's not possibly due to this comment https://github.com/apache/arrow/pull/4522#issuecomment-520286004. cc @emkornfield who might have some more insight.

**Comment by dongjoon-hyun** [comment]
Thank you for comments, @BryanCutler . I'm also very surprised because this happens suddenly.
- On Mac environment (with JDK 11.0.5), this doesn't happen.
- On Linux environment (with JDK 11.0.4), I reproduced this like Jenkins. However, `io.netty.tryReflectionSetAccessible` doesn't solve this situation.

If we don't have any proper follow-up fix for this, I need to revert your commit about Arrow 0.15.1 because our Jenkins is broken. I'm trying to find a way to avoid that.

**Comment by srowen** [comment]
I am not sure this change in the PR actually sets the system property for tests. I think it needs to be set in the surefire plugin config. Like in `<argLine>` add `-Dio.netty.tryReflectionSetAccessible=true` as a test? If that works, good, but still not a great situation, as it means any JDK 11 users would have to set this.

**Comment by dongjoon-hyun** [comment]
Yes. This is a headache for Arrow users. I'll switch to `argLine`. Thanks.

**Comment by srowen** [comment]
If that works, I'd ask, why not default to allowing this access in Arrow? CCing @BryanCutler as an expert.

**Comment by dongjoon-hyun** [comment]
Yes. Right.
Apache Arrow community seems to document this at `0.15.0` (https://github.com/apache/arrow/pull/5078).

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by dongjoon-hyun** [comment]
Oh, @srowen . Do you mean enabling this in our code base (somewhere arrow-related code)?

**Comment by BryanCutler** [comment]
Thanks for helping out with this @dongjoon-hyun and @srowen. I think this should be taken care of in the Arrow code-base since by default it causes a failure, I'm not sure why it wasn't but I'll followup with the Arrow community about it.

In the meantime, I understand if we need to revert the upgrade from #26133 but we should also downgrade the Jenkins pyarrow at the same time or else it will fail too.

It looks like the last test failed also. I don't know where the proper place to put this is, but I'll try to run some tests also.

**Comment by dongjoon-hyun** [comment]
It passed all Scala/Java UTs. Now, it seems that we need to add this conf to PySpark/SparkR UT.

**Comment by dongjoon-hyun** [comment]
cc @HyukjinKwon

**Comment by BryanCutler** [comment]
For pyspark, the patch below seems to work, but it would only fix unit tests and not all usage

```diff
diff --git a/python/run-tests.py b/python/run-tests.py
index 5bcf8b0..ecf5859 100755
--- a/python/run-tests.py
+++ b/python/run-tests.py
@@ -87,6 +87,7 @@ def run_individual_python_test(target_dir, test_name, pyspark_python):
 
     # Also override the JVM's temp directory by setting driver and executor options.
     spark_args = [
+        "--conf", "spark.driver.extraJavaOptions=-Dio.netty.tryReflectionSetAccessible=true",
         "--conf", "spark.driver.extraJavaOptions=-Djava.io.tmpdir={0}".format(tmp_dir),
         "--conf", "spark.executor.extraJavaOptions=-Djava.io.tmpdir={0}".format(tmp_dir),
         "pyspark-shell"
```

**Comment by dongjoon-hyun** [comment]
Thank you!

**Comment by dongjoon-hyun** [comment]
Ur, do we have two `spark.driver.extraJavaOptions`?

**Comment by dongjoon-hyun** [comment]
For PySpark, I created another PR to do faster iteration.
- https://github.com/apache/spark/pull/26553

**Comment by dongjoon-hyun** [comment]
I'll merge this to recover JDK11 Jenkins job.
Please ignore the AppVeyor failure. It fails on both JDK8/JDK11 due to OOM. We are tracking it in the following PR.
- https://github.com/apache/spark/pull/26555

**Comment by dongjoon-hyun** [comment]
We can remove this later after Apache Arrow has the proper logic inside itself.

**Comment by srowen** [comment]
OK, at least we need to mark this as a release-notes item, until it's undone. 

BTW this isn't really an Arrow behavior, but a Netty one:
http://git.yunmaozj.com/opensource/netty/commit/e72c197aa3a88e97c10793ee7870775ab8807f92
I think it's not great to default to not-working on JDK 9+ vs print a warning. But it happened 2 years ago. I guess Spark doesn't trigger the same kind of issue in its use of Netty.

We can try to set this system property at startup in Spark, though I don't know if we can do it early enough. I don't know if Arrow can or wants to try to set this, likewise? like if not set, set to true? This isn't ideal for JDK 9+ users as several things won't work unless their deployment also sets this value - and same could be true of any Arrow user.

See also https://gitter.im/netty/netty?at=5ce3e8d513e9854e334005d7 which suggests using a different allocator avoids this, but I don't know if it's directly helpful. I think the issue is that Arrow is reaching into its PlatformDependent class directly.

**Comment by dongjoon-hyun** [comment]
Yes. I created [SPARK-29924 Document Arrow requirement in JDK9+](https://issues.apache.org/jira/browse/SPARK-29924) for that.

**Comment by emkornfield** [comment]
For turning on the flag in Arrow we can discuss it again.  When this issue came up the first time, it seemed like it shouldn't be Arrow's job to force this, but I'm happy to reconsider and I suppose we can come up with a mechanism to allow end users to opt out if for some reason there is a need to turn it off (we might also be able to investigate moving away from the components that require this).

**Comment by dongjoon-hyun** [comment]
Thank you, @emkornfield !

**Comment by BryanCutler** [comment]
Thanks @emkornfield ,  I'll start a thread in the Arrow dev list and we can discuss there.

**Review by HyukjinKwon — COMMENTED** [review]
Sorry for my late response. LGTM for now.

**Pull request closed without merging**
