### PR TITLE
[SPARK-38206][SS] Ignore nullability on comparing the data type of join keys on stream-stream join

### PR DESCRIPTION
**Pull request by HeartSaVioR**
### What changes were proposed in this pull request?

This PR proposes to change the assertion of data type against joining keys on stream-stream join to ignore nullability.

### Why are the changes needed?

The existing requirement on checking data types of joining keys is too restricted, as it also requires the same nullability. In batch query (I checked with HashJoinExec), nullability is ignored when checking data types of joining keys.

### Does this PR introduce _any_ user-facing change?

Yes, end users will no longer encounter the assertion error on join keys with different nullability in both keys.

### How was this patch tested?

New test added.

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
I've added test cases for inner & left-outer join. I guess it's redundant to have separate test cases for right-outer/full-outer/left-semi, but please let me know if we would like to have exhausive set of tests.

**Comment by HeartSaVioR** [comment]
cc. @cloud-fan @viirya @xuanyuanking @c21

**Review by cloud-fan — APPROVED** [review]

**Review by viirya — APPROVED** [review]

**Comment by HeartSaVioR** [comment]
Thanks! Merging to master.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by c21** [comment]
Sorry for late comment, just late +1 LGTM.

**Pull request closed without merging**
