### PR TITLE
[SPARK-49174][BUILD][DOCS] Exclude the dir `docs/util` from `_site`

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to `exclude` the dir `docs/util` from `_site`.
eg: https://spark.apache.org/docs/4.0.0-preview1/util/build-error-docs.py

### Why are the changes needed?
Eliminate `unnecessary` files in the `site`.
ref: https://jekyllrb.com/docs/configuration/options/

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Manually check.
- Before
  https://github.com/panbingkun/spark/actions/runs/10311043869/artifacts/1793190911
  image

- After
  https://github.com/panbingkun/spark/actions/runs/10315064902/artifacts/1793887413
  image

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by panbingkun** [comment]
cc @yaooqinn

**Comment by yaooqinn** [comment]
Can it be moved to https://github.com/apache/spark/tree/master/docs/_plugins？

**Comment by panbingkun** [comment]
> Can it be moved to [https://github.com/apache/spark/tree/master/docs/_plugins？](https://github.com/apache/spark/tree/master/docs/_plugins%EF%BC%9F)

I'll give it a try.

**Comment by yaooqinn** [comment]
Thank you @panbingkun

**Comment by panbingkun** [comment]
> Can it be moved to [https://github.com/apache/spark/tree/master/docs/_plugins？](https://github.com/apache/spark/tree/master/docs/_plugins%EF%BC%9F)

It's okay, and I have verified again the content of `the site folder` generated by GA, 
the `util` no longer exists, and there are no other issues with the content.

**Review by yaooqinn — APPROVED** [review]
LGTM

**Comment by yaooqinn** [comment]
Merged to master

**Comment by panbingkun** [comment]
Thanks @yaooqinn

**Pull request closed without merging**
