### PR TITLE
[SPARK-35405][DOC] Submitting Applications documentation has outdated information about K8s client mode support

### PR DESCRIPTION
**Pull request by o-shevchenko**
### What changes were proposed in this pull request?
[Submitting Applications doc](https://spark.apache.org/docs/latest/submitting-applications.html#master-urls) has outdated information about K8s client mode support.
It still says "Client mode is currently unsupported and will be supported in future releases".
image

Whereas it's already supported and [Running Spark on Kubernetes doc](https://spark.apache.org/docs/latest/running-on-kubernetes.html#client-mode) says that it's supported started from 2.4.0 and has all needed information.
image

Changes:
image

JIRA: https://issues.apache.org/jira/browse/SPARK-35405

### Why are the changes needed?
Outdated information in the doc is misleading

### Does this PR introduce _any_ user-facing change?
Documentation changes

### How was this patch tested?
Documentation changes

### CODE REVIEW

**Comment by yaooqinn** [comment]
ok to test

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @o-shevchenko .
Merged to master/3.1/3.0.

**Comment by dongjoon-hyun** [comment]
Thank you for your first contribution, @o-shevchenko . You are added to the Apache Spark contributor group and SPARK-35405 is assigned to you. Welcome to the Apache Spark community!

**Comment by o-shevchenko** [comment]
Thanks a lot for your review!

**Pull request closed without merging**
