### PR TITLE
[SPARK-23417][python] Fix the build instructions supplied by exception messages in python streaming tests

### PR DESCRIPTION
**Pull request by bersprockets**
## What changes were proposed in this pull request?

Fix the build instructions supplied by exception messages in python streaming tests. 

I also added -DskipTests to the maven instructions to avoid the 170 minutes of scala tests that occurs each time one wants to add a jar to the assembly directory.

## How was this patch tested?

- clone branch
- run build/sbt package
- run python/run-tests --modules "pyspark-streaming" , expect error message
- follow instructions in error message. i.e., run build/sbt assembly/package streaming-kafka-0-8-assembly/assembly
- rerun python tests, expect error message
- follow instructions in error message. i.e run build/sbt -Pflume assembly/package streaming-flume-assembly/assembly
- rerun python tests, see success.
- repeated all of the above for mvn version of the process.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
ok to test

**Comment by HyukjinKwon** [comment]
add to whitelist

**Review by HyukjinKwon — APPROVED** [review]

**Review by dongjoon-hyun — APPROVED** [review]

**Comment by bersprockets** [comment]
Do we want to merge this or does it need more eyes?

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by bersprockets** [comment]
@HyukjinKwon Oh, thanks. I guess I learned what "approved these changes" means.

**Pull request closed without merging**
