### PR TITLE
[DO NOT MERGE][SPARK-36409][SQL][TESTS] Splitting test cases from datetime.sql

### PR DESCRIPTION
**Pull request by gengliangwang**
### What changes were proposed in this pull request?

* Split the test cases related to timestamp_ntz or timestamp_ltz functions from datetime.sql. 
* Add end-to-end tests for type constructor with `timestamp_ntz` and `timestamp_ltz`

### Why are the changes needed?

* Reduce the number of lines in `datetime.sql` from 300 to 200. It has a lot of test cases and will continue increasing. 
* The test cases related to timestamp_ntz or timestamp_ltz don't need to run again in datetime_legacy.sql. The refactor reduces unnecessary test runs.
* Add end-to-end tests for new type constructors.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Pass CI tests

### CODE REVIEW

**Review by MaxGekk — COMMENTED** [review]
@gengliangwang Seems the test fail is related to the changes:
```
[info] - timestamp_ltz.sql *** FAILED *** (563 milliseconds)
[info]   Expected "[-1969-12-31 16:00:00]", but got "[java.lang.IllegalArgumentException
[info]   Timestamp format must be yyyy-mm-dd hh:mm:ss[.fffffffff]]" Result did not match for query #1
[info]   select timestamp_ltz'-1969-12-31 16:00:00' (ThriftServerQueryTestSuite.scala:221)
```

**Review by MaxGekk — APPROVED** [review]
Waiting for GA results.

**Comment by gengliangwang** [comment]
@cloud-fan pinged me offline that he is working on a better test split. Let's don't merge this one for now.

**Comment by gengliangwang** [comment]
As @cloud-fan opens https://github.com/apache/spark/pull/33640, I am closing this one.

**Pull request closed without merging**
