### PR TITLE
[SPARK-23932][SQL][FOLLOW-UP] Fix an example of zip_with function.

### PR DESCRIPTION
**Pull request by ueshin**
## What changes were proposed in this pull request?

This is a follow-up pr of #22031 which added `zip_with` function to fix an example.

## How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by ueshin** [comment]
cc @techaddict

**Comment by techaddict** [comment]
@ueshin LGTM

**Comment by HyukjinKwon** [comment]
Merged to master.

**Review by HyukjinKwon — APPROVED** [review]
LGTM too pending Jenkins.

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request closed without merging**
