### PR TITLE
[SPARK-27333][TEST] Update thread audit whitelist to skip broadcast-exchange-.*, process reaper and StatisticsDataReferenceCleaner threads

### PR DESCRIPTION
**Pull request by attilapiros**
## What changes were proposed in this pull request?

Update thread audit whitelist to skip threads of the global broadcast exchange thread pool, process reaper and Hadoop FS statistics data reference cleaner thread.

## How was this patch tested?

Via existing UT using broadcast exchange via `sbt` i.e:

```
> project sql
> testOnly *.SessionStateSuite -- -z "fork new sessions and run query on inherited table"
``` 

Before (wrapped long line for manually to save horizontal scrolling for reviewers):

```
===== POSSIBLE THREAD LEAK IN SUITE o.a.s.sql.SessionStateSuite, 
thread names: broadcast-exchange-6, broadcast-exchange-0, 
broadcast-exchange-2, broadcast-exchange-5, broadcast-exchange-7, 
broadcast-exchange-4, broadcast-exchange-1, process reaper, broadcast-exchange-3,
 org.apache.hadoop.fs.FileSystem$Statistics$StatisticsDataReferenceCleaner =====
```

After this change no possible thread leak detected.

### CODE REVIEW

**Comment by vanzin** [comment]
Why not add "process reaper" while you're here? Seems to be a thread created by the JRE itself.

**Review by srowen — APPROVED** [review]

**Comment by attilapiros** [comment]
jenkins retest this please

**Comment by attilapiros** [comment]
jenkins retest this please

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by dongjoon-hyun** [comment]
Thank you, @attilapiros . This looks very useful.

**Comment by dongjoon-hyun** [comment]
The root cause of failures is reverted in the master.

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Comment by dongjoon-hyun** [comment]
Retest this please.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @attilapiros , @srowen , @vanzin .
Merged to master.

**Pull request closed without merging**
