### PR TITLE
[SPARK-48635][SQL] Assign classes to join type errors and as-of join error

### PR DESCRIPTION
**Pull request by wayneguow**
### What changes were proposed in this pull request?

This PR renames a few error classes related to `join type` and `as-of join`:

- _LEGACY_ERROR_TEMP_1319 -> INVALID_JOIN_TYPE_FOR_JOINWITH
- _LEGACY_ERROR_TEMP_3216 -> UNSUPPORTED_JOIN_TYPE
- _LEGACY_ERROR_TEMP_3217 -> AS_OF_JOIN.UNSUPPORTED_DIRECTION

### Why are the changes needed?

Proper error names and messages improve user experience with Spark SQL.

### Does this PR introduce _any_ user-facing change?

Yes, this PR changes user-facing error class and message.

### How was this patch tested?

Passed GA.
By running test cases in `JoinTypesTest`, `DatasetSuite` and `DataFrameAsOfJoinSuite`.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by wayneguow** [comment]
cc @LuciferYang @panbingkun

**Review by allisonwang-db — APPROVED** [review]

**Comment by allisonwang-db** [comment]
cc @ueshin

**Review by ueshin — APPROVED** [review]

**Review by HyukjinKwon — APPROVED** [review]

**Comment by HyukjinKwon** [comment]
Merged to master.

**Comment by wayneguow** [comment]
Thank you all. @HyukjinKwon @ueshin @allisonwang-db

**Pull request closed without merging**
