### PR TITLE
[SPARK-48692][BUILD] Upgrade `rocksdbjni` to 9.2.1

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
The pr aims to upgrade rocksdbjni from `8.11.4` to `9.2.1`.

### Why are the changes needed?
The full release notes as follows:
https://github.com/facebook/rocksdb/releases/tag/v9.2.1
https://github.com/facebook/rocksdb/releases/tag/v9.1.1
https://github.com/facebook/rocksdb/releases/tag/v9.1.0
https://github.com/facebook/rocksdb/releases/tag/v9.0.1
https://github.com/facebook/rocksdb/releases/tag/v9.0.0

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by panbingkun** [comment]
At present, we are only testing `rocksdbjni's` `9 series` in advance

**Comment by LuciferYang** [comment]
Let's test 9.1.1

**Comment by panbingkun** [comment]
> Let's test 9.1.1

Currently, the version 9.1.1 is not available on `Maven Center Repo`, and the `rocksdbjni` has been released too frequently recently.

**Comment by LuciferYang** [comment]
We can wait for a relatively stable version.

**Comment by LuciferYang** [comment]
ready to go ?

**Comment by panbingkun** [comment]
> ready to go ?

Yea, the last upgrade was two months ago.

**Comment by panbingkun** [comment]
> > ready to go ?
> 
> Yea, the last upgrade was two months ago, Let me run the benchmark: StateStoreBasicOperationsBenchmark JDK17: https://github.com/panbingkun/spark/actions/runs/9640180869 JDK21: https://github.com/panbingkun/spark/actions/runs/9640184179

Done

**Review by LuciferYang — APPROVED** [review]
LGTM (pending tests)

**Comment by LuciferYang** [comment]
Let's wait one more day

**Comment by LuciferYang** [comment]
Merged into master. Thanks @panbingkun

**Comment by panbingkun** [comment]
> Merged into master. Thanks @panbingkun

Thanks.

**Pull request closed without merging**
