### PR TITLE
[SPARK-43130][SQL] Move InternalType to PhysicalDataType

### PR DESCRIPTION
**Pull request by amaliujia**
### What changes were proposed in this pull request?

This PR drops `InternalType` from the logical data type and refactors to use the PhysicalDataType and InternalType.

### Why are the changes needed?

To simplify DataType interface.

### Does this PR introduce _any_ user-facing change?

NO

### How was this patch tested?

UT

### CODE REVIEW

**Comment by amaliujia** [comment]
@cloud-fan

**Comment by amaliujia** [comment]
In fact the compilation is failing on tests. let me fix it first.

**Comment by amaliujia** [comment]
Test issues should have been fixed.

**Review by cloud-fan — APPROVED** [review]

**Comment by cloud-fan** [comment]
thanks, merging to master!

**Pull request closed without merging**
