### PR TITLE
[SPARK-40902] [MESOS][TESTS] Fix issue with mesos tests failing due to quick submission of drivers

### PR DESCRIPTION
**Pull request by mridulm**
##### Quick submission of drivers in tests to mesos scheduler results in dropping drivers

Queued drivers in `MesosClusterScheduler` are ordered based on `MesosDriverDescription` - and the ordering used checks for priority (if different), followed by comparison of submission time.
For two driver submissions with same priority, if made in quick succession (such that submission time is same due to millisecond granularity of Date), this results in dropping the second `MesosDriverDescription` from `queuedDrivers` (since `driverOrdering` returns `0` when comparing the descriptions).

This PR fixes the more immediate issue with tests.

### Why are the changes needed?

Flakey tests, [see here](https://lists.apache.org/thread/jof098qxp0s6qqmt9qwv52f9665b1pjg) for an example.

### Does this PR introduce _any_ user-facing change?

No.
Fixing only tests for now - as mesos support is deprecated, not changing scheduler itself to address this.

### How was this patch tested?

Fixes unit tests

### CODE REVIEW

**Comment by mridulm** [comment]
+CC @dongjoon-hyun, @wangyum

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM (Pending CIs)
Thank you for investigating and fixing this long standing issue, @mridulm .

**Comment by mridulm** [comment]
Thanks for quick review @dongjoon-hyun !

**Comment by dongjoon-hyun** [comment]
I manually tested this test suite fix. Merged to master/3.3/3.2. Thank you, @mridulm .

**Comment by mridulm** [comment]
Thanks for merging it @dongjoon-hyun !

**Pull request closed without merging**
