### PR TITLE
[SPARK-48291][Core] Rename Java Logger as SparkLogger

### PR DESCRIPTION
**Pull request by gengliangwang**
### What changes were proposed in this pull request?

Two new classes `org.apache.spark.internal.Logger` and `org.apache.spark.internal.LoggerFactory` were introduced from https://github.com/apache/spark/pull/46301.
Given that Logger is a widely recognized **interface** in Log4j, it may lead to confusion to have a class with the same name. To avoid this and clarify its purpose within the Spark framework, I propose renaming `org.apache.spark.internal.Logger` to `org.apache.spark.internal.SparkLogger`. Similarly, to maintain consistency, `org.apache.spark.internal.LoggerFactory` should be renamed to `org.apache.spark.internal.SparkLoggerFactory`.

### Why are the changes needed?

To avoid naming confusion and clarify the java Spark logger purpose within the logging framework

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

GA tests
### Was this patch authored or co-authored using generative AI tooling?

No

### CODE REVIEW

**Comment by gengliangwang** [comment]
cc @panbingkun

**Review by dongjoon-hyun — APPROVED** [review]
+1, this looks reasonable and better than before to me. Thank you, @gengliangwang .

**Comment by panbingkun** [comment]
The purpose of the name at that time was to make developers feel `less change`, more `natural` and `smooth`. Of course, if we need to be `very explicit` about this difference, I'm fine. Maybe we need to add some instructions for developers in `org/apache/spark/internal/README.md`?
https://github.com/apache/spark/blob/a2d93d104a6c3307f50dfd91f5cc51a97d4c5837/common/utils/src/main/scala/org/apache/spark/internal/README.md?plain=1#L13

**Comment by gengliangwang** [comment]
> Of course, if we need to be very explicit about this difference

Yes that's the purpose of this PR. I want the class names to be clear.

> Maybe we need to add some instructions for developers in org/apache/spark/internal/README.md

Good point. I will have a follow-up for both scala and java logging.

**Comment by gengliangwang** [comment]
@dongjoon-hyun @panbingkun Thanks for the review. Merging this one to master

**Pull request closed without merging**
