### PR TITLE
[SPARK-31292][CORE][SQL] Replace toSet.toSeq with distinct for readability

### PR DESCRIPTION
**Pull request by sekikn**
### What changes were proposed in this pull request?

This PR replaces the method calls of `toSet.toSeq` with `distinct`.

### Why are the changes needed?

`toSet.toSeq` is intended to make its elements unique but a bit verbose. Using `distinct` instead is easier to understand and improves readability.

### Does this PR introduce any user-facing change?

No

### How was this patch tested?

Tested with the existing unit tests and found no problem.

### CODE REVIEW

**Comment by kiszk** [comment]
ok to test

**Review by maropu — APPROVED** [review]
The change looks fine to me cc: @srowen

**Review by srowen — APPROVED** [review]
OK, minor but reasonable

**Comment by maropu** [comment]
Thanks! Merged to master/3.0

**Comment by srowen** [comment]
I would just have merged to master at this time, but it is so trivial that almost surely won't matter

**Comment by maropu** [comment]
Yea, since too minor & trivial, I've merged it to 3.0, too. If any problem, plz revert it from 3.0.

**Pull request closed without merging**
