### PR TITLE
SPARK-5106 - Add refresh checkbox on the UI

### PR DESCRIPTION
**Pull request by jbonofre**
Add a checkbox to enable auto-refresh. See attached screenshots:

screen

### CODE REVIEW

**Comment by jbonofre** [comment]
Rebase

**Comment by srowen** [comment]
I kind of like the functionality, myself. However I'm only concerned about where and how to expose this. I want to avoid tacking on bits and pieces to the UI until it's just a quilt of info and links. This seems pretty reasonable, still.

**Comment by jbonofre** [comment]
Thanks for the update Sean. Some background:
1. I wanted to avoid "intrusive" code on the server side, that's why the refresh is "client side" using JavaScript.
2. I disable the auto-refresh by default, and let the user enable it if wanted.
3. I think it's useful (for instance, a simple case is when you are on the master UI, and just want to see running applications, workers, etc status change)

**Comment by steveloughran** [comment]
Wont be of much merit on the completed history server UIs, so ought to be something which can be completely omitted off the page

**Comment by andrewor14** [comment]
this feels more like a button thing than a checkbox thing

**Comment by jbonofre** [comment]
@andrewor14 I can change to a link or button (instead of a checkbox), no worries.
@steveloughran agree, I changed in UIUtils to be global. I can add a flag in sparkPage() and sparkBasicPage() functions to not include the JS (for the history server for instance).

Let me prepare an update on this PR according to your comments.

**Comment by jbonofre** [comment]
PR rebased and updated to use a button instead of a checkbox.

**Comment by JoshRosen** [comment]
Are you sure that we want this feature? Isn't this better handled by the user via one of the many browser extensions for auto-refresh?

I feel like this would be a different discussion if this refresh mechanism updated the backing data without reloading the page (similar to how the refresh functionality on https://spark-prs.appspot.com works).

Personally, I'm opposed to this change since it adds ugly UI clutter and seems a bit out-of-scope. Happy to hear counterarguments, though.

**Comment by andrewor14** [comment]
I'm with @JoshRosen. Also there's not really a good place to put it on the UI and it doesn't really add any value.

**Comment by jbonofre** [comment]
I "mimic" what we have on Jenkins for instance. I understand your points guys. I just thought it's a convenient feature for users ;)

**Comment by jbonofre** [comment]
So, what do we do about this ?
First, let me go back to the checkbox (probably better IMHO in term of UI).
@JoshRosen I agree that using pushed async update (using AJAX/websocket) would be better, but it means refactoring of the UI. I would be more than happy to work on this if you want !
Maybe we can define a two steps plan:
1/ using the existing UI, just add the checkbox convenient for the users
2/ in the mean time, I can work on a complete polishing & revamping of the UI to include "push update" feature.

WDYT ?

Thank guys !
Regards
JB

**Comment by jbonofre** [comment]
Rebase and back on the checkbox (instead of the button).

**Comment by JoshRosen** [comment]
I worry that this opens a can of UI / UX worms for very little net benefit to users. For instance, a common complaint with the Jenkins auto-refresh is that the delay is not configurable, leading to the development of Jenkins plugins to add options for controlling the timeout: https://wiki.jenkins-ci.org/display/JENKINS/Config+AutoRefresh+Plugin; I imagine we'd run into similar complains / feature requests as soon as we added this. The net benefit to users seems tiny if we're not going to do in-place updating without the page refresh, so I'm personally against adding this UI clutter.

(By the way, whether we do push vs. pull is slightly orthogonal to updating the view contents without refreshing the whole page; for example, spark-prs' in-place refresh is entirely pull-based; this is a larger discussion which belongs on JIRA, though).

**Comment by jbonofre** [comment]
I can add a text field to let users configure the refresh interval if you want.

**Comment by steveloughran** [comment]
One thing about auto-refresh is it generates load on the back end on every refresh, even if its a tab in the browser that isn't even visible. With a manual reload, you get to schedule the work and so it is likely to be generally less. 

Someone could add a metric for page reloads to measure that, if it isn't there already...that way the impact of auto-reload would be measurable

**Comment by jbonofre** [comment]
Good point Steve. Maybe we can launch a thread on mailing list ?
Anyway, I know bunch of users doing CTRL-R or F5 again and again ;)

**Comment by jbonofre** [comment]
So, what do we do about this guys ? I'm closing this PR and prepare a new one about revamping of the UI ? Or we apply this waiting for new enhancements ?

**Comment by andrewor14** [comment]
I would prefer that we don't add this feature for now. The user can more customized auto-refreshing on the browser than anything we can support.

**Comment by jbonofre** [comment]
Fair enough. I just wait for some more hours and I will close the PR. I think it makes sense to resolved the corresponding Jira as "won't fix".

**Comment by jbonofre** [comment]
By the way, what do you think about discussing this on the mailing list in order to see what the users think about this (the Apache way ;)) ?

**Comment by srowen** [comment]
@jbonofre all of the messages are sent to reviews@spark.apache.org, for those that wish to follow. Significant discussions can be pushed over to dev@ or user@, if appropriate.

**Comment by jbonofre** [comment]
Thoughts ? Do we discuss this on the mailing lists or it's worth to keep it here and close this PR ?

**Comment by JoshRosen** [comment]
Let's close this PR for now. We can always open a new PR if there's a new approach / broader feature to discuss, but for now I don't think there's any immediate further action to take on the refresh checkbox as implemented here.

**Comment by jbonofre** [comment]
Fair enough. I close the PR. Can you close the corresponding Jira please ?

**Comment by sylvinus** [comment]
Might I suggest we have another look at this, to save users from breaking their cmd-R keys? :-)

This JS snippet (which you can paste in the Chrome console to test) solves 2 of the issues mentioned here:
 - Doesn't refresh if the Spark UI stopped to avoid losing results
 - Doesn't refresh if the page is not currently visible

```
(function() {

function tinyxhr(url,cb,method,post,contenttype){var c=url,a=cb,i=method,f=post,b=contenttype;var d,h;try{h=new XMLHttpRequest()}catch(g){try{h=new ActiveXObject("Msxml2.XMLHTTP")}catch(g){if(console){console.log("tinyxhr: XMLHttpRequest not supported")}return null}}d=setTimeout(function(){h.abort();a(new Error("tinyxhr: aborted by a timeout"),"",h)},10000);h.onreadystatechange=function(){if(h.readyState!=4){return}clearTimeout(d);a(h.status!=200?new Error("tinyxhr: server respnse status is "+h.status):false,h.responseText,h)};h.open(i?i.toUpperCase():"GET",c,true);if(!f){h.send()}else{h.setRequestHeader("Content-type",b?b:"application/x-www-form-urlencoded");h.send(f)}};

function spark_refresh() {
	var delay = 2000;
	if (document.hidden) return setTimeout(spark_refresh, delay);
	tinyxhr(window.location.toString(), function(error, html) {
		if (error) return;
		document.documentElement.innerHTML = html;
		setTimeout(spark_refresh, delay);
	}, "GET");
}

spark_refresh();

})();
```

The `delay` could be configured from a dropdown on the top right corner of the page, which is relatively standard in such dashboards.

**Pull request closed without merging**
