### PR TITLE
[SPARK-43484][BUILD][DSTREAM] Kafka/Kinesis Assembly should not package hadoop-client-runtime

### PR DESCRIPTION
**Pull request by pan3793**
### What changes were proposed in this pull request?

Change `hadoop-client-runtime`'s scope to `provided` in kafka/kinesis assembly modules.

### Why are the changes needed?

`hadoop-client-runtime` is already included in Spark binary tgz, we should not package it again into the optional assembly jar.

This issue exists since SPARK-33212.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Manual review.

### CODE REVIEW

**Comment by pan3793** [comment]
cc @srowen @sunchao

**Comment by pan3793** [comment]
There are other unexpected jars that were wrongly included in the assembly jar, would like to address them in separate PRs, since they were caused by different tickets, but I'm fine to fix all issues in one PR if the reviewers prefer.

**Review by srowen — APPROVED** [review]

**Review by sunchao — APPROVED** [review]
LGTM

**Comment by sunchao** [comment]
Merged to master, thanks!

**Review by dongjoon-hyun — COMMENTED** [review]
+1, LGTM. Thank you all

**Pull request closed without merging**
