### PR TITLE
[SQL] SPARK-6548 : Adding stddev to DataFrame functions

### PR DESCRIPTION
**Pull request by dreamquster**
The contribution is my original work and that my license the work to the project under the project's open source license.

sdfox
dreamquster agree the contribution to spark

### CODE REVIEW

**Comment by liancheng** [comment]
ok to test

**Comment by dreamquster** [comment]
image
What's wrong with this?

**Comment by liancheng** [comment]
retest this please

**Comment by dreamquster** [comment]
I'm sorry. Now after reruned ./dev/lint-scala, how I retest this cases?

**Comment by liancheng** [comment]
Once "ok to test" is issued by an admin, the test will be triggered automatically after you push something.

**Comment by dreamquster** [comment]
How to close it or create a new pull request? I had changed something for other issue. And it is not necessary to autotest.

**Comment by liancheng** [comment]
There is a close button at the bottom of this page as long as you are the author of the PR.

**Pull request closed without merging**
