### PR TITLE
SPARK-8064, build against Hive 1.2.1 [test-maven] [test-hadoop1.0]

### PR DESCRIPTION
**Pull request by pwendell**
Attempting to run maven tests on this PR.

### CODE REVIEW

**Comment by pwendell** [comment]
Jenkins, test this please.

**Comment by pwendell** [comment]
Jenkins, retest this please.

**Comment by pwendell** [comment]
Jenkins, retest this please.

**Comment by pwendell** [comment]
Jenkins, test this pleas.e

**Comment by pwendell** [comment]
Jenkins, test this please.

**Comment by pwendell** [comment]
Jenkins, retest this please.

**Comment by pwendell** [comment]
Jenkins, retest this please.

**Comment by pwendell** [comment]
Jenkins, test this please.

**Comment by liancheng** [comment]
Seems that this can be close?

**Pull request closed without merging**
