### PR TITLE
[SPARK-10529][SQL]When creating multiple HiveContext objects in one jvm, jdbc connections to metastore cann't be released and it may cause PermGen OutOfMemoryError.	

### PR DESCRIPTION
**Pull request by GavinGavinNo1**
To resolve problem mentioned in SPARK-10529, I add an attribute of ThreadLocal<URLClassLoader> type in object IsolatedClientLoader. So, no matter how many HiveContext objects are created in the same jvm, they use the same URLClassLoader object. Therefore, no more classes will be loaded and no more jdbc connections will be created.

### CODE REVIEW

**Comment by marmbrus** [comment]
Another reason for the isolation is the ability to connect to multiple metastores.  Since hive uses global static state, new classloaders is likely the only way to accomplish this.  Why are you trying to create more than one HiveContext in a JVM.

**Comment by GavinGavinNo1** [comment]
Thank you much for your comment. I think I haven't got what you mean for the ability to connect to multiple metastores.One HiveContext can only connect to one metastore, right? Or you mean creating multiple HiveContext to connect to multiple metastores with one SparkContext in one JVM? If so, it'll lead to the same JVM OOM problem in theory.
We use spark 1.3.1 formerly. You know it isn't supported for dynamic allocation in standalone mode. We have several apps and each one launches timely tasks using HiveContext. Due to the limit of hardware resources, we must stop SparkContext to release CPU and memory resources when a task is done. When Spark 1.4.1 comes out, it brings many new features and we want to switch to this version. However, problems mentioned in my issue make a lot of trouble to us.

**Comment by GavinGavinNo1** [comment]
@marmbrus Sorry to disturb again. Could you please give me a reply? It's my first try. Maybe I need some advice.

**Comment by marmbrus** [comment]
I would suggest increasing the size of your perm gen, and/or restructuring your app to avoid creating multiple HiveContexts.  Spark 1.5 adds the ability to do dynamic allocation in standalone mode.

**Comment by GavinGavinNo1** [comment]
@marmbrus Thanks a lot. I'm so sorry I didn't make myself clear. I mean I'm not familiar with submitting an issue or contributing to spark. What you suggest I have considered in fact, however I can neither push forward restructuring our app nor wait for stable spark 1.5. Anyway, Spark won't adapt to our app. But I still wander if it'll be a function to support multi HiveContext in one JVM, which I think more flexable.

**Comment by marmbrus** [comment]
You can have multiple contexts, you just have to increase the size of your permgen (or run Java 8).  The problem with this change is it makes things less flexible since you would not longer be able to connect to multiple different metastores from the same JVM.  Given that mind closing this issue?

I'll also add that Spark 1.5 was released last week and we'll be releasing Spark 1.5.1 shortly.

**Comment by GavinGavinNo1** [comment]
@marmbrus Well, we both know that we can have multiple contexts. The difference is that it can't support continuous creating contexts. No matter how much size my permgen is, it'll lead to memory leak  and cause too many jdbc connections error. Another thing you said about different metastores, I think a certain environment normally have a certain version of metastore.
I‘m sure you have brilliant idea for denying my opinion, not only for what you have expressed. Otherwise, adding a parameter to control can deal with both problems.

**Pull request closed without merging**
