### PR TITLE
[SPARK-5287][SQL] Add defaultSizeOf to every data type.

### PR DESCRIPTION
**Pull request by yhuai**
JIRA: https://issues.apache.org/jira/browse/SPARK-5287

This PR only add `defaultSizeOf` to data types and make those internal type classes `protected[sql]`. I will use another PR to cleanup the type hierarchy of data types.

### CODE REVIEW

**Comment by rxin** [comment]
How come we don't want it for all data types?

**Comment by marmbrus** [comment]
Yeah, will this still fail for limits with struct types for example?

**Comment by rxin** [comment]
I'd say we can just put a defaultSize method to datatype trait, and then implement it for all data types.

**Comment by yhuai** [comment]
For now, it will not fail since we [will check if the data type is a NativeType before calling defaultSize](https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/basicOperators.scala#L241). I thought we will implement it for all types when we remove `NativeType`. 

I can move `defaultSize` to datatype trait in this PR.

**Comment by jesman** [comment]
A of a or the reader t AD

**Comment by rxin** [comment]
Sorry @jesman what did you mean?

**Pull request closed without merging**
