### PR TITLE
[SPARK-9060] [SQL] Revert SPARK-8359, SPARK-8800, and SPARK-8677

### PR DESCRIPTION
**Pull request by yhuai**
JIRA: https://issues.apache.org/jira/browse/SPARK-9060

This PR reverts:
- https://github.com/apache/spark/commit/31bd30687bc29c0e457c37308d489ae2b6e5b72a (SPARK-8359)
- https://github.com/apache/spark/commit/24fda7381171738cbbbacb5965393b660763e562 (SPARK-8677)
- https://github.com/apache/spark/commit/4b5cfc988f23988c2334882a255d494fc93d252e (SPARK-8800)

### CODE REVIEW

**Comment by yhuai** [comment]
@viirya and @davies Can you take a look to double check if I accidentally remove any thing useful?

**Comment by davies** [comment]
LGTM

**Comment by viirya** [comment]
LGTM

**Comment by yhuai** [comment]
Thanks! I am merging it to master.

**Pull request closed without merging**
