### PR TITLE
[BUILD] Closing some stale/inappropriate PRs 

### PR DESCRIPTION
**Pull request by HyukjinKwon**
## What changes were proposed in this pull request?

This PR proposes to close some stale PRs and ones suggested to be closed by committer(s) or obviously inappropriate PRs (e.g. branch to branch).

Closes #15689
Closes #14640
Closes #15917
Closes #16188
Closes #16206

## How was this patch tested?

N/A

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @srowen Could you take a look and see if they are reasonable please?

**Comment by rxin** [comment]
Merging in master.

**Comment by rxin** [comment]
For some reason I couldn't merge this one. I pushed a commit directly to master. Can you close this one now?

**Comment by HyukjinKwon** [comment]
Sure, thanks!

**Comment by HyukjinKwon** [comment]
BTW, I believe we should add `--allow-empty` when it is merged.

**Comment by srowen** [comment]
Yes I have to edit the merge script to `git commit --allow-empty ...` but I don't know that we should always set it. It could prompt or something but I was too lazy to implement that.

Anyway that sounds fine and I have my own list of PRs to close that I'll 'flush' with a commit soon too.

**Comment by rxin** [comment]
Yea i'd say in general that `--allow-empty` be there.

**Pull request closed without merging**
