### PR TITLE
[MINOR][CORE] Update taskName in PythonRunner

### PR DESCRIPTION
**Pull request by jiangxb1987**
## What changes were proposed in this pull request?

Update taskName in PythonRunner so it keeps align with that in Executor.

## How was this patch tested?

N/A

### CODE REVIEW

**Review by HyukjinKwon — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Hi, @jiangxb1987 .
Could you make a JIRA issue? Although this looks minor, we sometime have a followup for the minor issues in the worst case.

**Comment by jiangxb1987** [comment]
@dongjoon-hyun Thanks for reminding, but I'm pretty confident this shall not need any followup PR.

**Comment by dongjoon-hyun** [comment]
I see. Thanks, @jiangxb1987 .

**Review by srowen — APPROVED** [review]
Looks like an oversight indeed as the TID is logged in the next line. This only affects a log message anyway

**Comment by jiangxb1987** [comment]
Thanks! Merged to master

**Pull request closed without merging**
