### PR TITLE
[SPARK-48554][INFRA] Use R 4.4.0 in `windows` R GitHub Action Window job

### PR DESCRIPTION
**Pull request by panbingkun**
### What changes were proposed in this pull request?
This PR aims to use R 4.4.0 in `windows` R GitHub Action job.

### Why are the changes needed?
R 4.4.0 is the latest release which is released on 2024-04-24.
https://www.r-project.org/

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass GA.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by HyukjinKwon** [comment]
I think ... this might break SparkR build (https://github.com/apache/spark/actions/runs/9331838894) assuming from the timeline ..

**Comment by panbingkun** [comment]
> Let me revert this first, and see if the build passes.

Okay, Let me investigate it.

**Comment by panbingkun** [comment]
@HyukjinKwon 
It doesn't seem like the issue was caused by this upgrade,
It also encountered similar issues when the version is `4.3.3`
https://github.com/panbingkun/spark/actions/runs/9576846198/job/26404013779
From the `log stack`, it seems that there is an exception in the character `unescape`
I suspect what character on Windows is causing it.

Let me continue to address its `root cause`.

**Comment by panbingkun** [comment]
I have reproduced this issue and let me see how to fix it correctly
image

**Comment by panbingkun** [comment]
@HyukjinKwon 
https://github.com/panbingkun/spark/actions/runs/9611425119/job/26509953539
I have verified `windows R (4.3.3)` on GA and it has passed. Now I will verify the `4.4.0` version again.
If there are no issues, I think we can bring this upgrade back.

**Comment by HyukjinKwon** [comment]
let me revert this back.

**Comment by panbingkun** [comment]
> let me revert this back.

Thanks

**Pull request closed without merging**
