### PR TITLE
[SPARK-23579][Documentation] Added context model image and updated documentation to match it.

### PR DESCRIPTION
**Pull request by arucard21**
## What changes were proposed in this pull request?

We updated the documentation to include more information about the context of Apache Spark. This includes other projects that Apache Spark can interact with but also information about the people that create Apache Spark. We think this provides valuable insight into how Apache Spark fits into the world. 

Both the changes in the text of the documentation and the included image were created by us. It is our original work which we license to the project under the project’s open source license.

We could only change the content in the markdown file, but the image is displayed full-width directly under the text. As far as we could tell, the styling seems to be applied in the documentation website through CSS files. We couldn't really tell how to change and test this. If the current styling isn't acceptable, please let us know how to test any changes in style. We'll mark this PR as [WIP] then, otherwise it should be ready to be merged.

## How was this patch tested?

The documentation was tested using the preview functionality of our markdown editor and verified in the Github-rendered markdown page.
## Co-contributors:
@chialun-yeh
@Hrayo712
@vpourquie

### CODE REVIEW

**Review by srowen — COMMENTED** [review]
I understand you're trying to add more info here, but I think this may be way too much detail for the main page. For example, users would not care that AppVeyor happens to be used somewhere for testing Windows builds, nor anything about JIRA. Some of this is a little misleading, like, the code is actually primarily on ASF git, and only mirrored on github. This preferentially puts a few corporate logos as users, and I'm sure we can't do that in an ASF project. Some of the logos aren't official, like the blue Spark SQL? Finally I think images are hard to update when things change.

For those reasons I'm not sure this is something we can merge, but I understand the intent.

**Comment by arucard21** [comment]
I could try to create a simplified version of this image with just a few of these relations. But since that's still an image it would still be hard to update. 

So I can remove the image but try to describe the context a bit more in text. We already mention the possibility of using Hadoop modules for Cluster Management and Distributed Storage. We can include how there are other options available to provide this functionality. That should provide a more comprehensive overview of the important entities that Spark interacts with. (available APIs + modules to extend functionality + third-party modules for specific functionality = all you need to run Spark)

I'm not sure if this is sufficient added value for the documentation (or if you think this additional information is even needed). If not, let me know and I can just close this PR.

**Comment by srowen** [comment]
I don't think the text change adds much here. Yes you can mention cluster managers, but, this is already covered in the cluster manager docs and it's not that central to understanding, in a first paragraph, what Spark is.

**Comment by rxin** [comment]
Yea we gotta be careful with adding commercial vendor logos here. It's part of the complexity we need to navigate being hosted at the Apache Software Foundation. The project needs to be very vendor neutral.

**Comment by arucard21** [comment]
Ok, sounds fair. Thanks for taking a look at this. I'll close this PR then.

**Pull request closed without merging**
