### PR TITLE
[SPARK-49661][SQL] Removing redudant checks of collation in binary collation hashing expression 

### PR DESCRIPTION
**Pull request by jovanpavl-db**
### What changes were proposed in this pull request?
Removing redudant check of collation in binary collation hashing expression 

### Why are the changes needed?
Code cleanup, trying to speed up joins.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Existing tests should keep passing as join is already well covered with tests.

### Was this patch authored or co-authored using generative AI tooling?
No.
-->

### CODE REVIEW

**Comment by jovanpavl-db** [comment]
@cloud-fan, @stefankandic, @stevomitric please review this urgently.

**Review by stevomitric — APPROVED** [review]
LGTM. The `supportsBinaryEquality` is defined as follows:
```scala
this.supportsBinaryEquality = !supportsSpaceTrimming && isUtf8BinaryType;
```

which incorporates the trimming check, making the ones removed in this PR a valid performance improvement.

**Comment by stefankandic** [comment]
If this is really that performance critical, should we make `supportsBinaryEquality` a lazy val?

**Comment by stevomitric** [comment]
> If this is really that performance critical, should we make supportsBinaryEquality a lazy val?

Can we improve it altogether? Right now it fetches the collator object and gets one of its properties. We can simply do integer comparisons against it.

**Comment by stefankandic** [comment]
> > If this is really that performance critical, should we make supportsBinaryEquality a lazy val?
> 
> Can we improve it altogether? Right now it fetches the collator object and gets one of its properties. We can simply do integer comparisons against it.

How is that an improvement though? If it were a val or a lazy val it would get computed only once, and now we have to do a comparison on each call, which for the interpreted path could happen billions of times.

**Comment by jovanpavl-db** [comment]
@stefankandic it is improvement, equally as using lazy val. By `stringType.collationId == CollationFactory.UTF8_BINARY_COLLATION_ID`, there is no fetching of collation at all (by collationId), just comparing 2 integers which should be pretty same as comparing boolean (supportsBinaryEquality with true).
Issue with current implementation is that we always need to fetch Collation from collationId to check simple boolean flag and that part of fetching Collation is the expensive one. But this is the way it worked before (adding rtrim collation), I added one more condition so it made it fetch 2 times (once for supportsBinaryEquality, once for supportsTrimCollation).

**Comment by MaxGekk** [comment]
@stefankandic Are you ok with the changes?

**Review by MaxGekk — COMMENTED** [review]
Can we just improve perf of `supportsBinaryEquality` by checking collation id in the method `StringType.supportsBinaryEquality` and avoid fetching collation instance:
```scala
  private[sql] def supportsBinaryEquality: Boolean = {
    isUTF8BinaryCollation || CollationFactory.fetchCollation(collationId).supportsBinaryEquality
  }
```

**Comment by stefankandic** [comment]
> @stefankandic Are you ok with the changes?

I am now

**Review by stefankandic — APPROVED** [review]

**Review by MaxGekk — APPROVED** [review]

**Comment by MaxGekk** [comment]
+1, LGTM. Merging to master.
Thank you, @jovanpavl-db and @stefankandic @stevomitric for review.

**Pull request closed without merging**
