### PR TITLE
[SPARK-36729][BUILD] Upgrade Netty from 4.1.63 to 4.1.68

### PR DESCRIPTION
**Pull request by sarutak**
### What changes were proposed in this pull request?

This PR upgrades Netty from `4.1.63` to `4.1.68`.

All the changes from `4.1.64` to `4.1.68` are as follows.

* 4.1.64 and 4.1.65
  * https://netty.io/news/2021/05/19/4-1-65-Final.html
* 4.1.66
  * https://netty.io/news/2021/07/16/4-1-66-Final.html
* 4.1.67
  * https://netty.io/news/2021/08/16/4-1-67-Final.html
* 4.1.68
  * https://netty.io/news/2021/09/09/4-1-68-Final.html

### Why are the changes needed?

Recently Netty `4.1.68` was released, which includes official M1 Mac support.
* Add support for mac m1
  * https://github.com/netty/netty/pull/11666

`4.1.65` also includes a critical bug fix which Spark might be affected.
* JNI classloader deadlock with latest JDK version
  * https://github.com/netty/netty/issues/11209

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

CIs.

### CODE REVIEW

**Review by srowen — APPROVED** [review]
Looks good pending tests - if this is a minor upgrade for 3.2.0 could go in there too IMHO

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @sarutak and @srowen .
Yes, we need this in 3.2.0 for M1 support and https://bugs.openjdk.java.net/browse/JDK-8266310 .

**Comment by dongjoon-hyun** [comment]
cc @gengliangwang

**Comment by gengliangwang** [comment]
Late +1

**Pull request closed without merging**
