### PR TITLE
[SPARK-39452][GraphX] Extend EdgePartition1D with Destination based Strategy

### PR DESCRIPTION
**Pull request by ericsun95**
### What changes were proposed in this pull request?

[SPARK-39452](https://issues.apache.org/jira/browse/SPARK-39452) Extend EdgePartition1D with Destination based Strategy

### Why are the changes needed?

Currently, the [EdgePartition1D](https://github.com/apache/spark/blob/master/graphx/src/main/scala/org/apache/spark/graphx/PartitionStrategy.scala#L101)  use only the source vertex ID.

If doing topological like algorithm on graph, directly partition based on destination vertex ID would improve the performance significantly. The proposal here is adding new case objects EdgePartition1DDst and EdgePartition1DSrc explicitly for EdgePartition1D.

### Does this PR introduce _any_ user-facing change?

Introduce new partition strategy `EdgePartition1DDst` and update `EdgePartition1D` to `EdgePartition1DSrc`.

### How was this patch tested?

Test locally. `mvn test -Denforcer.skip=true`

### CODE REVIEW

**Comment by aray** [comment]
Thanks for the PR. Can you help justify that this is better than using EdgePartition2D for those use cases? As to the change, I'm personally not in favor of deprecating EdgePartition1D just to change its name.

**Comment by ericsun95** [comment]
> Thanks for the PR. Can you help justify that this is better than using EdgePartition2D for those use cases? As to the change, I'm personally not in favor of deprecating EdgePartition1D just to change its name.

Hey, sure. I have experimented with a topological sort like algorithm in a big graph (billions of vertices and edges). The new `EdgePartition1DDst` can have 36% of performance improvement than the `EdgePartition2D`. And it is more stable under different hardware configurations (executor instances types, number of executors, etc). Other partition strategies could not even finish the computation.

In theory, assuming we need to collect messages sending from child nodes to parent nodes iteratively. It is necessary to make sure most data has the same data locality (thus less shuffle). The `EdgePartition2D` could only make sure that there are about `1/3` changes the edges with same dst located in the same partition while the `EdgePartition1DDst` can guarantee that most edges with the same dst id located together. It is more obvious if the graph has a tree structure.

For the naming, I do think it's better to split `EdgePartition1D` to `EdgePartition1DSrc` and `EdgePartition1DDst` just to be consistent on naming instead of `EdgePartition1D` and `EdgePartition1DDst` which is confusing to people without background. And I found that the usage of `EdgePartition1D` in the repo is minimal so it wouldn't be a breaking change. However, I am fine to remove the deprecation if there are concerns on this change.

**Comment by aray** [comment]
Thanks for the performance discussion, sounds like a good improvement for this use case.

**Comment by ericsun95** [comment]
> Thanks for the performance discussion, sounds like a good improvement for this use case. 

Hey, how could we merge it? Anything I need to do to get it approved and merged?

**Pull request closed without merging**
