### PR TITLE
[SPARK-12197] [SparkCore] Kryo & Avro - Support Schema Repo

### PR DESCRIPTION
**Pull request by RotemShaul**
[SPARK-12197] [SparkCore] Kryo & Avro - Support Schema Repo

### CODE REVIEW

**Comment by RotemShaul** [comment]
As explained in the JIRA, this ability enhances the usability of Spark Core and Avro greatly, as dynamic input schemas are supported by using a schema repository.

**Comment by RotemShaul** [comment]
Did anyone take a look ?

**Comment by rxin** [comment]
Thanks for the pull request. I'm going through a list of pull requests to cut them down since the sheer number is breaking some of the tooling we have. Due to lack of activity on this pull request, I'm going to push a commit to close it. Feel free to reopen it or create a new one.

**Comment by RotemShaul** [comment]
Hi, I created an updated PR
https://github.com/apache/spark/pull/13761

I'd really appreciate if u'd take a look. (It was kind of neglected in the
past)
This feature is very important for users of Spark-Core + Avro [Less impo
for with SparkSQL]
In fact, for us at LivePerson it's a must, and we're currently using it in
our framework we've built on top of Spark.

Thanks !

**Pull request closed without merging**
