### PR TITLE
[SPARK-49469][CONNECT][TESTS] Add dummy protos for expression and datatype

### PR DESCRIPTION
**Pull request by zhengruifeng**
### What changes were proposed in this pull request?

We have dummy proto for relations 
https://github.com/apache/spark/blob/c248b0651b1d2efbd445e44e3779a989a02d2184/sql/connect/common/src/main/protobuf/spark/connect/relations.proto#L101-L106

This PR aims to add dummy protos for expression and datatype

### Why are the changes needed?
For testing purposes, e.g. we can use it to build an invalid connect expression.

### Does this PR introduce _any_ user-facing change?
No, test only

### How was this patch tested?
CI

### Was this patch authored or co-authored using generative AI tooling?
No

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
cc @grundprinzip @hvanhovell

**Review by nija-at — CHANGES_REQUESTED** [review]
I don't understand the use case for this. Can you explain why this is needed better?

**Comment by zhengruifeng** [comment]
> I don't understand the use case for this. Can you explain why this is needed better?

@nija-at thanks for reviews

one usage case is information redaction, we can redact the sensitive fields of known nodes, once a new node was add it contains PII, the PII maybe leaked before we update the redaction logic, then we can use this `Unknown` to replace any unknown nodes.

**Comment by xinrong-meng** [comment]
It seems that we also have the message "Unknown" in "relations.proto"

**Comment by zhengruifeng** [comment]
> It seems that we also have the message “Unknown” in “relations.proto” for testing purposes. To maintain consistency, should we add it to all protos as well later?

maybe we can also add one for commands, let me take another look

**Pull request closed without merging**
